= 19.30 - Farm labor contractors.
:toc:

== 19.30.010 - Definitions—Exceptions from chapter.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Agricultural employee" means any person who renders, or has rendered, personal services to, or under the direction of, an agricultural employer in connection with the employer's agricultural activity.

. "Agricultural employer" means any person engaged in agricultural activity, including the growing, producing, or harvesting of farm or nursery products, or engaged in the forestation or reforestation of lands, which includes but is not limited to the planting, transplanting, tubing, precommercial thinning, and thinning of trees and seedlings, the clearing, piling, and disposal of brush and slash, the harvest of Christmas trees, and other related activities.

. "Director" as used in this chapter means the director of the department of labor and industries of the state of Washington.

. "Farm labor contracting activity" means recruiting, soliciting, employing, supplying, transporting, or hiring agricultural employees.

. "Farm labor contractor" means any person, or his or her agent or subcontractor, who, for a fee, performs any farm labor contracting activity. "Farm labor contractor" does not include a person performing farm labor contracting activity solely for a small forestland owner as defined in RCW 76.09.450 who receives services of no more than two agricultural employees at any given time.

. "Fee" means:

.. Any money or other valuable consideration paid or promised to be paid for services rendered or to be rendered by a farm labor contractor.

.. Any valuable consideration received or to be received by a farm labor contractor for or in connection with any of the services described in subsection (4) of this section, and shall include the difference between any amount received or to be received by him, and the amount paid out by him for or in connection with the rendering of such services.

. "Person" includes any individual, firm, partnership, association, corporation, or unit or agency of state or local government.

. This chapter shall not apply to employees of the employment security department acting in their official capacity or their agents, nor to any common carrier or full time regular employees thereof while transporting agricultural employees, nor to any person who performs any of the services enumerated in subsection (4) of this section only within the scope of his or her regular employment for one agricultural employer on whose behalf he or she is so acting, unless he or she is receiving a commission or fee, which commission or fee is determined by the number of workers recruited.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6261-S.SL.pdf?cite=2020%20c%20205%20§%201[2020 c 205 § 1]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1924.SL.pdf?cite=2017%20c%20253%20§%201[2017 c 253 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c280.pdf?cite=1985%20c%20280%20§%201[1985 c 280 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c392.pdf?cite=1955%20c%20392%20§%201[1955 c 392 § 1]; ]

== 19.30.020 - License required—Duplicates.
No person shall act as a farm labor contractor until a license to do so has been issued to him or her by the director, and unless such license is in full force and effect and is in the contractor's possession. The director shall, by regulation, provide a means of issuing duplicate licenses in case of loss of the original license or any other appropriate instances. The director shall issue, on a monthly basis, a list of currently licensed farm labor contractors.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c280.pdf?cite=1985%20c%20280%20§%202[1985 c 280 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c392.pdf?cite=1955%20c%20392%20§%202[1955 c 392 § 2]; ]

== 19.30.030 - Applicants—Qualifications—Fee—Liability insurance—Farm labor contractor account.
. The director shall not issue to any person a license to act as a farm labor contractor until:

.. Such person has executed a written application on a form prescribed by the director, subscribed and sworn to by the applicant, and containing (i) a statement by the applicant of all facts required by the director concerning the applicant's character, competency, responsibility, and the manner and method by which he or she proposes to conduct operations as a farm labor contractor if such license is issued, and (ii) the names and addresses of all persons financially interested, either as partners, stockholders, associates, profit sharers, or providers of board or lodging to agricultural employees in the proposed operation as a labor contractor, together with the amount of their respective interests;

.. The director, after investigation, is satisfied as to the character, competency, and responsibility of the applicant;

.. The applicant has paid to the director a license fee of: (i) Thirty-five dollars in the case of a farm labor contractor not engaged in forestation or reforestation, or (ii) one hundred dollars in the case of a farm labor contractor engaged in forestation or reforestation or such other sum as the director finds necessary, and adopts by rule, for the administrative costs of evaluating applications;

.. The applicant has filed proof satisfactory to the director of the existence of a policy of insurance with any insurance carrier authorized to do business in the state of Washington in an amount satisfactory to the director, which insures the contractor against liability for damage to persons or property arising out of the contractor's operation of, or ownership of, any vehicle or vehicles for the transportation of individuals in connection with the contractor's business, activities, or operations as a farm labor contractor;

.. The applicant has filed a surety bond or other security which meets the requirements set forth in RCW 19.30.040;

.. The applicant executes a written statement which shall be subscribed and sworn to and shall contain the following declaration:

"With regards to any action filed against me concerning my activities as a farm labor contractor, I appoint the director of the Washington department of labor and industries as my lawful agent to accept service of summons when I am not present in the jurisdiction in which the action is commenced or have in any other way become unavailable to accept service"; and

.. The applicant has stated on his or her application whether or not his or her contractor's license or the license of any of his or her agents, partners, associates, stockholders, or profit sharers has ever been suspended, revoked, or denied by any state or federal agency, and whether or not there are any outstanding judgments against him or her or any of his or her agents, partners, associates, stockholders, or profit sharers in any state or federal court arising out of activities as a farm labor contractor.

. The farm labor contractor account is created in the state treasury. All receipts from farm labor contractor licenses, security deposits, penalties, and donations must be deposited into the account. Moneys in the account may be spent only after appropriation. Expenditures from the account may be used only for administering the farm labor contractor licensing program, subject to authorization from the director or the director's designee.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1057-S.SL.pdf?cite=2012%20c%20158%20§%201[2012 c 158 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1087-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2050%20§%20927[2011 1st sp.s. c 50 § 927]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c280.pdf?cite=1985%20c%20280%20§%203[1985 c 280 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c392.pdf?cite=1955%20c%20392%20§%203[1955 c 392 § 3]; ]

== 19.30.040 - Surety bond—Security.
. The director shall require the deposit of a surety bond by any person acting as a farm labor contractor under this chapter to insure compliance with the provisions of this chapter. Such bond shall be in an amount specified by the director in accordance with such criteria as the director adopts by rule but shall not be less than five thousand dollars. The bond shall be payable to the state of Washington and be conditioned on payment of sums legally owing under contract to an agricultural employee. The aggregate liability of the surety upon such bond for all claims which may arise thereunder shall not exceed the face amount of the bond.

. The amount of the bond may be raised or additional security required by the director, upon his or her own motion or upon petition to the director by any person, when it is shown that the security or bond is insufficient to satisfy the contractor's potential liability for the licensed period.

. No surety insurer may provide any bond, undertaking, recognizance, or other obligation for the purpose of securing or guaranteeing any act, duty, or obligation, or the refraining from any act with respect to a contract using the services of a farm labor contractor unless the farm labor contractor has made application for or has a valid license issued under RCW 19.30.030 at the time of issuance of the bond, undertaking, recognizance, or other obligation.

. Surety bonds may not be canceled or terminated during the period in which the bond is executed unless thirty days' notice is provided by the surety to the department. The bond is written for a one-year term and may be renewed or extended by continuation certification at the option of the surety.

. In lieu of the surety bond required by this section, the contractor may file with the director a deposit consisting of cash or other security acceptable to the director. The deposit shall not be less than five thousand dollars in value. The security deposited with the director in lieu of the surety bond shall be returned to the contractor at the expiration of three years after the farm labor contractor's license has expired or been revoked if no legal action has been instituted against the contractor or on the security deposit at the expiration of the three years.

. If a contractor has deposited a bond with the director and has failed to comply with the conditions of the bond as provided by this section, and has departed from this state, service may be made upon the surety as prescribed in RCW 4.28.090.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c216.pdf?cite=1987%20c%20216%20§%201[1987 c 216 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c197.pdf?cite=1986%20c%20197%20§%2015[1986 c 197 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c280.pdf?cite=1985%20c%20280%20§%204[1985 c 280 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c392.pdf?cite=1955%20c%20392%20§%204[1955 c 392 § 4]; ]

== 19.30.045 - Claim for wages—Action upon surety bond or security.
. Any person, having a claim for wages pursuant to this chapter may bring suit upon the surety bond or security deposit filed by the contractor pursuant to RCW 19.30.040, in any court of competent jurisdiction of the county in which the claim arose, or in which either the claimant or contractor resides.

. The right of action is assignable in the name of the director or any other person.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c216.pdf?cite=1987%20c%20216%20§%202[1987 c 216 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c197.pdf?cite=1986%20c%20197%20§%2019[1986 c 197 § 19]; ]

== 19.30.050 - License—Grounds for denying.
A license to operate as a farm labor contractor shall be denied:

. To any person who sells or proposes to sell intoxicating liquors in a building or on premises where he or she operates or proposes to operate as a farm labor contractor, or

. To a person whose license has been revoked within three years from the date of application.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c280.pdf?cite=1985%20c%20280%20§%205[1985 c 280 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c392.pdf?cite=1955%20c%20392%20§%205[1955 c 392 § 5]; ]

== 19.30.060 - License—Revocation, suspension, refusal to issue or renew.
Any person may protest the grant or renewal of a license under this section. The director may revoke, suspend, or refuse to issue or renew any license when it is shown that:

. The farm labor contractor or any agent of the contractor has violated or failed to comply with any of the provisions of this chapter;

. The farm labor contractor has made any misrepresentations or false statements in his or her application for a license;

. The conditions under which the license was issued have changed or no longer exist;

. The farm labor contractor, or any agent of the contractor, has violated or wilfully aided or abetted any person in the violation of, or failed to comply with, any law of the state of Washington regulating employment in agriculture, the payment of wages to farm employees, or the conditions, terms, or places of employment affecting the health and safety of farm employees, which is applicable to the business activities, or operations of the contractor in his or her capacity as a farm labor contractor;

. The farm labor contractor or any agent of the contractor has in recruiting farm labor solicited or induced the violation of any then existing contract of employment of such laborers; or

. The farm labor contractor or any agent of the contractor has an unsatisfied judgment against him or her in any state or federal court, arising out of his or her farm labor contracting activities.

The director shall immediately suspend the license or certificate of a person who has been certified pursuant to RCW 74.20A.320 by the department of social and health services as a person who is not in compliance with a support order or a *residential or visitation order. If the person has continued to meet all other requirements for reinstatement during the suspension, reissuance of the license or certificate shall be automatic upon the director's receipt of a release issued by the department of social and health services stating that the licensee is in compliance with the order.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20846[1997 c 58 § 846]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c280.pdf?cite=1985%20c%20280%20§%206[1985 c 280 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c392.pdf?cite=1955%20c%20392%20§%206[1955 c 392 § 6]; ]

== 19.30.070 - License—Contents.
Each license shall contain, on the face thereof:

. The name and address of the licensee and the fact that he or she is licensed to act as a farm labor contractor for the period upon the face of the license only;

. The number, date of issuance, and date of expiration of the license;

. The amount of the surety bond deposited by the licensee;

. The fact that the license may not be transferred or assigned; and

. A statement that the licensee is or is not licensed to transport workers.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c280.pdf?cite=1985%20c%20280%20§%207[1985 c 280 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c392.pdf?cite=1955%20c%20392%20§%207[1955 c 392 § 7]; ]

== 19.30.081 - License—Duration—Renewal.
Farm labor contractors may hold either a one-year license or a two-year license, at the director's discretion.

The one-year license shall run to and include the 31st day of December next following the date thereof unless sooner revoked by the director. A license may be renewed each year upon the payment of the annual license fee, but the director shall require that evidence of a renewed bond be submitted and that the contractor have a bond in full force and effect.

The two-year license shall run to and include the 31st day of December of the year following the year of issuance unless sooner revoked by the director. This license may be renewed every two years under the same terms as the one-year license, except that a farm labor contractor possessing a two-year license shall have evidence of a bond in full force and effect, and file an application on which he or she shall disclose all information required by *RCW 19.30.030 (1)(b), (4), and (7).

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c216.pdf?cite=1987%20c%20216%20§%203[1987 c 216 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c197.pdf?cite=1986%20c%20197%20§%2016[1986 c 197 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c280.pdf?cite=1985%20c%20280%20§%208[1985 c 280 § 8]; ]

== 19.30.090 - License—Application for renewal.
All applications for renewal shall state the names and addresses of all persons financially interested either as partners, associates or profit sharers in the operation as a farm labor contractor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c392.pdf?cite=1955%20c%20392%20§%209[1955 c 392 § 9]; ]

== 19.30.110 - Farm labor contractor—Duties.
Every person acting as a farm labor contractor shall:

. Carry a current farm labor contractor's license at all times and exhibit it to all persons with whom the contractor intends to deal in the capacity of a farm labor contractor prior to so dealing.

. Disclose to every person with whom he or she deals in the capacity of a farm labor contractor the amount of his or her bond and the existence and amount of any claims against the bond.

. File at the United States post office serving the address of the contractor, as noted on the face of the farm labor contractor's license, a correct change of address immediately upon each occasion the contractor permanently moves his or her address, and notify the director within ten days after an address change is made.

. Promptly when due, pay or distribute to the individuals entitled thereto all moneys or other things of value entrusted to the contractor by any third person for such purpose.

. Comply with the terms and provisions of all legal and valid agreements and contracts entered into between the contractor in the capacity of a farm labor contractor and third persons.

. File information regarding work offers with the nearest employment service office, such information to include wages and work to be performed and any other information prescribed by the director.

. On a form prescribed by the director, furnish to each worker, at the time of hiring, recruiting, soliciting, or supplying, whichever occurs first, a written statement in English and any other language common to workers who are not fluent or literate in English that contains a description of:

.. The compensation to be paid and the method of computing the rate of compensation;

.. The terms and conditions of any bonus offered, including the manner of determining when the bonus is earned;

.. The terms and conditions of any loan made to the worker;

.. The conditions of any transportation, housing, board, health, and day care services or any other employee benefit to be provided by the farm labor contractor or by his or her agents, and the costs to be charged for each of them;

.. The terms and conditions of employment, including the approximate length of season or period of employment and the approximate starting and ending dates thereof, and the crops on which and kinds of activities in which the worker may be employed;

.. The terms and conditions under which the worker is furnished clothing or equipment;

.. The place of employment;

.. The name and address of the owner of all operations, or the owner's agent, where the worker will be working as a result of being recruited, solicited, supplied, or employed by the farm labor contractor;

.. The existence of a labor dispute at the worksite;

.. The name and address of the farm labor contractor;

.. The existence of any arrangements with any owner or agent of any establishment at the place of employment under which the farm labor contractor is to receive a fee or any other benefit resulting from any sales by such establishment to the workers; and

.. The name and address of the surety on the contractor's bond and the workers' right to claim against the bond.

. Furnish to the worker each time the worker receives a compensation payment from the farm labor contractor, a written statement itemizing the total payment and the amount and purpose of each deduction therefrom, hours worked, rate of pay, and pieces done if the work is done on a piece rate basis, and if the work is done under the Service Contract Act (41 U.S.C. Secs. 351 through 401) or related federal or state law, a written statement of any applicable prevailing wage.

. With respect to each worker recruited, solicited, employed, supplied, or hired by the farm labor contractor:

.. Make, keep, and preserve for three years a record of the following information:

... The basis on which wages are paid;

... The number of piecework units earned, if paid on a piecework basis;

... The number of hours worked;

... The total pay period earnings;

.. The specific sums withheld and the purpose of each sum withheld; and

.. The net pay; and

.. Provide to any other farm labor contractor and to any user of farm labor for whom he or she recruits, solicits, supplies, hires, or employs workers copies of all records, with respect to each such worker, which the contractor is required by this chapter to make, keep, and preserve. The recipient of such records shall keep them for a period of three years from the end of the period of employment. When necessary to administer this chapter, the director may require that any farm labor contractor provide the director with certified copies of his or her payroll records for any payment period.

The recordkeeping requirements of this chapter shall be met if either the farm labor contractor or any user of the contractor's services makes, keeps, and preserves for the requisite time period the records required under this section, and so long as each worker receives the written statements specified in subsection (8) of this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c280.pdf?cite=1985%20c%20280%20§%209[1985 c 280 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c392.pdf?cite=1955%20c%20392%20§%2011[1955 c 392 § 11]; ]

== 19.30.120 - Farm labor contractor—Prohibited acts.
No person acting as a farm labor contractor shall:

. Make any misrepresentation or false statement in an application for a license.

. Make or cause to be made, to any person, any false, fraudulent, or misleading representation, or publish or circulate or cause to be published or circulated any false, fraudulent, or misleading information concerning the terms or conditions or existence of employment at any place or places, or by any person or persons, or of any individual or individuals.

. Send or transport any worker to any place where the farm labor contractor knows a strike or lockout exists.

. Do any act in the capacity of a farm labor contractor, or cause any act to be done, which constitutes a crime involving moral turpitude under any law of the state of Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c280.pdf?cite=1985%20c%20280%20§%2010[1985 c 280 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c392.pdf?cite=1955%20c%20392%20§%2012[1955 c 392 § 12]; ]

== 19.30.130 - Rules—Adjustment of controversies.
. The director shall adopt rules not inconsistent with this chapter for the purpose of enforcing and administering this chapter.

. The director shall investigate and attempt to adjust equitably controversies between farm labor contractors and their workers with respect to claims arising under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c280.pdf?cite=1985%20c%20280%20§%2011[1985 c 280 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c392.pdf?cite=1955%20c%20392%20§%2014[1955 c 392 § 14]; ]

== 19.30.150 - Penalties.
Any person who violates any provisions of this chapter, or who causes or induces another to violate any provisions of this chapter, shall be guilty of a misdemeanor punishable by a fine of not more than five thousand dollars, or imprisonment in the county jail for not more than six months, or both.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c392.pdf?cite=1955%20c%20392%20§%2013[1955 c 392 § 13]; ]

== 19.30.160 - Civil penalty—Hearing—Court action.
. In addition to any criminal penalty imposed under RCW 19.30.150, the director may assess against any person who violates this chapter, or any rule adopted under this chapter, a civil penalty of not more than one thousand dollars for each violation.

. The person shall be afforded the opportunity for a hearing, upon request to the director made within thirty days after the date of issuance of the notice of assessment. The hearing shall be conducted in accordance with chapter 34.05 RCW.

. If any person fails to pay an assessment after it has become a final and unappealable order, or after the court has entered final judgment in favor of the agency, the director shall refer the matter to the state attorney general, who shall recover the amount assessed by action in the appropriate superior court. In such action, the validity and appropriateness of the final order imposing the penalty shall not be subject to review.

. Without regard to other remedies provided in this chapter, the department may bring suit upon the surety bond filed by the farm labor contractor on behalf of a worker whose rights under this chapter have been violated by the contractor. The action may be commenced in any court of competent jurisdiction. In any such action, there shall be compliance with the notice and service requirements set forth in RCW 19.30.170.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c216.pdf?cite=1987%20c%20216%20§%204[1987 c 216 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c197.pdf?cite=1986%20c%20197%20§%2017[1986 c 197 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c280.pdf?cite=1985%20c%20280%20§%2015[1985 c 280 § 15]; ]

== 19.30.170 - Civil actions—Damages, costs, attorney's fees—Actions upon bond or security deposit.
. After filing a notice of a claim with the director, in addition to any other penalty provided by law, any person aggrieved by a violation of this chapter or any rule adopted under this chapter may bring suit in any court of competent jurisdiction of the county in which the claim arose, or in which either the plaintiff or respondent resides, without regard to the amount in controversy and without regard to exhaustion of any alternative administrative remedies provided in this chapter. No such action may be commenced later than three years after the date of the violation giving rise to the right of action. In any such action the court may award to the prevailing party, in addition to costs and disbursements, reasonable attorney fees at trial and appeal.

. In any action under subsection (1) of this section, if the court finds that the respondent has violated this chapter or any rule adopted under this chapter, it may award damages up to and including an amount equal to the amount of actual damages, or statutory damages of five hundred dollars per plaintiff per violation, whichever is greater, or other equitable relief.

. Without regard to other remedies provided in this chapter, a person having a claim against the farm labor contractor for any violation of this chapter may bring suit against the farm labor contractor and the surety bond or security deposit filed by the contractor pursuant to RCW 19.30.040, in any court of competent jurisdiction of the county in which the claim arose, or in which either the claimant or contractor resides.

. An action upon the bond or security deposit shall be commenced by serving and filing the summons and complaint within three years from the date of expiration or cancellation of the bond or expiration or cancellation of the license, whichever is sooner, or in the case of a security deposit, within three years of the date of expiration or revocation of the license.

. A copy of the summons and complaint in any such action shall be served upon the director at the time of commencement of the action and the director shall maintain a record, available for public inspection, of all suits so commenced. Such service shall constitute service on the farm labor contractor and the surety for suit upon the bond and the director shall transmit the complaint or a copy thereof to the contractor at the address listed in his or her application and to the surety within forty-eight hours after it has been received.

. The surety upon the bond may, upon notice to the director and the parties, tender to the clerk of the court having jurisdiction of the action an amount equal to the claims or the amount of the bond less the amount of judgments, if any, previously satisfied therefrom and to the extent of such tender the surety upon the bond shall be exonerated.

. If the actions commenced and pending at any one time exceed the amount of the bond then unimpaired, the claims shall be satisfied from the bond in the following order:

.. Wages, including employee benefits;

.. Other contractual damage owed to the employee;

.. Any costs and attorneys' fees the claimant may be entitled to recover by contract or statute.

. If any final judgment impairs the bond so furnished so that there is not in effect a bond undertaking in the full amount prescribed by the director, the director shall suspend the license of the contractor until the bond liability in the required amount unimpaired by unsatisfied judgment claims has been furnished. If such bond becomes fully impaired, a new bond must be furnished.

. A claimant against a security deposit shall be entitled to damages under subsection (2) of this section. If the farm labor contractor has filed other security with the director in lieu of a surety bond, any person having an unsatisfied final judgment against the contractor for any violation of this chapter may execute upon the security deposit held by the director by serving a certified copy of the unsatisfied final judgment by registered or certified mail upon the director. Upon the receipt of service of such certified copy, the director shall pay or order paid from the deposit, through the registry of the court which rendered judgment, towards the amount of the unsatisfied judgment. The priority of payment by the director shall be the order of receipt by the director, but the director shall have no liability for payment in excess of the amount of the deposit.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c216.pdf?cite=1987%20c%20216%20§%205[1987 c 216 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c197.pdf?cite=1986%20c%20197%20§%2018[1986 c 197 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c280.pdf?cite=1985%20c%20280%20§%2016[1985 c 280 § 16]; ]

== 19.30.180 - Injunctions—Costs—Attorney fee.
The director or any other person may bring suit in any court of competent jurisdiction to enjoin any person from using the services of an unlicensed farm labor contractor or to enjoin any person acting as a farm labor contractor in violation of this chapter, or any rule adopted under this chapter, from committing future violations. The court may award to the prevailing party costs and disbursements and a reasonable attorney fee.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c280.pdf?cite=1985%20c%20280%20§%2012[1985 c 280 § 12]; ]

== 19.30.190 - Retaliation against employee prohibited.
No farm labor contractor or agricultural employer may discharge or in any other manner discriminate against any employee because:

. The employee has made a claim against the farm labor contractor or agricultural employer for compensation for the employee's personal services.

. The employee has caused to be instituted any proceedings under or related to RCW 19.30.180.

. The employee has testified or is about to testify in any such proceedings.

. The employee has discussed or consulted with anyone concerning the employee's rights under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c280.pdf?cite=1985%20c%20280%20§%2013[1985 c 280 § 13]; ]

== 19.30.200 - Unlicensed farm labor contractors—Liability for services.
Any person who knowingly uses the services of an unlicensed farm labor contractor shall be personally, jointly, and severally liable with the person acting as a farm labor contractor to the same extent and in the same manner as provided in this chapter. In making determinations under this section, any user may rely upon either the license issued by the director to the farm labor contractor under RCW 19.30.030 or the director's representation that such contractor is licensed as required by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2400.SL.pdf?cite=2000%20c%20171%20§%2048[2000 c 171 § 48]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c280.pdf?cite=1985%20c%20280%20§%2014[1985 c 280 § 14]; ]

== 19.30.902 - Effective date—1985 c 280.
This 1985 act shall take effect January 1, 1986.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c280.pdf?cite=1985%20c%20280%20§%2019[1985 c 280 § 19]; ]

