= 19.58 - Motion picture fair competition act.
:toc:

== 19.58.010 - Purpose.
The purpose of this chapter is to establish fair and open procedures for bidding and negotiation for the right to exhibit motion pictures in the state in order to prevent unfair and deceptive acts or practices and unreasonable restraints of trade in the business of motion picture distribution and exhibition within the state; to promote fair and effective competition in that business; and to insure that exhibitors have the opportunity to view a motion picture and know its contents before committing themselves to exhibiting the motion picture in their communities.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c29.pdf?cite=1979%20ex.s.%20c%2029%20§%201[1979 ex.s. c 29 § 1]; ]

== 19.58.020 - Definitions.
The definitions contained in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Bid" means a written or oral offer or proposal to buy made by an exhibitor to a distributor in response to an invitation to bid for the license or right to exhibit a motion picture, the license stating the terms under which the exhibitor agrees to exhibit the motion picture.

. "Blind bidding" means the exhibitor's bidding or negotiating for, or the exhibitor's offering or agreeing to, terms for the license or right to exhibit a feature motion picture at any time either before the feature motion picture has been trade screened within the state or before the feature motion picture has been otherwise made available for viewing within the state by all exhibitors.

. "Blind selling" means the practice whereby a distributor licenses a feature motion picture before the exhibitor is afforded an opportunity to view the feature motion picture by trade screening.

. "Buying" or "selling" of the right to exhibit a feature motion picture means the licensing of a theater to show the feature motion picture for a certain number of days for a certain price.

. "Distributor" means a person engaged in the business of distributing or supplying more than one feature motion picture per year to exhibitors by rental, sale, licensing, or other agreement.

. "Exhibit" or "exhibition" means playing or showing a feature motion picture to the public for an admission charge.

. "Exhibitor" means a person in the business of operating one or more theaters in which motion pictures are exhibited to the public.

. "Feature motion picture" means a motion picture exceeding sixty minutes in duration.

. "Invitation to bid" means a written or oral solicitation or invitation by a distributor to one or more exhibitors to bid or negotiate for the license or right to exhibit a feature motion picture.

. "Licensing agreement" means a contract, agreement, understanding, or condition between a distributor and an exhibitor relating to the licensing or exhibition of a feature motion picture by the exhibitor.

. "Person" means one or more individuals, firms, partnerships, associations, societies, trusts, organizations, or corporations.

. "Run" means the continuous exhibition of a feature motion picture in a defined geographic area for a specified period of time. A "first run" is the first exhibition of the feature motion picture in the defined area; a "second run" is the second exhibition; and "subsequent runs" are subsequent exhibitions after the second run. "Exclusive run" is a run limited to a single theater in a defined geographic area and a "nonexclusive run" is a run in more than one theater in a defined geographic area.

. "Theater" means an establishment in which feature motion pictures are regularly exhibited to the public for an admission charge.

. "Trade screening" means the exhibition of a feature motion picture, prior to its release for public exhibition by a distributor, in the largest city within the state, which is open to all exhibitors from whom the distributor intends to solicit bids or with whom the distributor intends to negotiate for the license or right to exhibit the feature motion picture.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c29.pdf?cite=1979%20ex.s.%20c%2029%20§%202[1979 ex.s. c 29 § 2]; ]

== 19.58.030 - Blind bidding or blind selling prohibited—Trade screening required—Notice.
. The buying or selling of the right to exhibit a feature motion picture by blind bidding or blind selling is prohibited within the state.

. No bids may be returnable, no negotiations for the exhibition or licensing of a motion picture may take place, and no license agreement or any of its terms may be agreed upon, for the exhibition of a feature motion picture within the state before the feature motion picture has either been trade screened or otherwise made available for viewing by all exhibitors within the state.

. A distributor shall provide reasonable and uniform notice of the trade screening of feature motion pictures to those exhibitors within the state from whom bids will be solicited or with whom negotiations will be conducted for the license or right to exhibit the feature motion picture.

. A purported waiver of the prohibition in this chapter against blind bidding or blind selling is void and unenforceable.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c29.pdf?cite=1979%20ex.s.%20c%2029%20§%203[1979 ex.s. c 29 § 3]; ]

== 19.58.040 - Solicitation of bids.
If bids are solicited from exhibitors for the licensing of a feature motion picture within the state, then:

. The invitation to bid shall specify: (a) Whether the run for which the bid is being solicited is a first, second, or subsequent run; whether the run is an exclusive or nonexclusive run; and, the geographic area for the run; (b) the names of all exhibitors who are being solicited; (c) the date and hour the invitation to bid expires; and (d) the time, date, and location, including the address, where the bids will be opened, which shall be within the state.

. All bids shall be submitted in writing and shall be opened at the same time and in the presence of those exhibitors, or their agents, who submitted bids and who attend the bid opening.

. Immediately upon being opened, the bids shall be subject to examination by the exhibitors, or their agents, who submitted bids, and who are present at the opening. Within ten business days after the bids are opened, the distributor shall notify each exhibitor who submitted a bid either the name of the winning bidder or the fact that none of the bids were acceptable.

. Once bids are solicited, the distributor shall license the feature motion picture only by bidding and may solicit rebids if none of the submitted bids are acceptable.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c29.pdf?cite=1979%20ex.s.%20c%2029%20§%204[1979 ex.s. c 29 § 4]; ]

== 19.58.050 - Violation—Civil suit—Attorneys' fees.
Any person aggrieved by a violation of this chapter may bring a civil action in superior court to enjoin further violations or to recover the actual damages sustained, or both, together with the costs of the suit. In any such action, the court shall award reasonable attorneys' fees to the prevailing party.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c29.pdf?cite=1979%20ex.s.%20c%2029%20§%205[1979 ex.s. c 29 § 5]; ]

== 19.58.900 - Short title.
This chapter may be known and cited as the Washington motion picture fair competition act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c29.pdf?cite=1979%20ex.s.%20c%2029%20§%206[1979 ex.s. c 29 § 6]; ]

