= 19.83 - Trading stamp licenses.
:toc:

== 19.83.010 - License required to use or furnish trading stamps, coupons, or similar devices.
Every person who uses, or furnishes, or sells to any other person for use, in, with, or for the sale of any goods, any trading stamps, coupons, tickets, certificates, cards or other similar devices which entitle the purchaser to procure any goods free of charge or for less than the retail market price thereof, upon the production of any number of such trading stamps, coupons, tickets, certificates, cards, or other similar devices, shall before so furnishing, selling, or using the same obtain a separate license from the auditor of each county wherein such furnishing or selling or using shall take place for each and every store or place of business in that county, owned or conducted by such person from which such furnishing or selling, or in which such using shall take place.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c134.pdf?cite=1913%20c%20134%20§%201[1913 c 134 § 1]; RRS § 8359; ]

== 19.83.020 - Issuance of license—Fee.
In order to obtain such license the person applying therefor shall pay to the county treasurer of the county for which the license is sought the sum of six thousand dollars, and upon such payment being made to the county treasurer he or she shall issue his or her receipt therefor which shall be presented to the auditor of the county, who shall upon the presentation thereof issue to the person making such payment a license to furnish or sell, or a license to use, for one year, trading stamps, coupons, tickets, certificates, cards, or other similar devices. Such license shall contain the name of the licensee, the date of its issue, the date of its expiration, the city or town in which and the location at which the same shall be used, and the license shall be used at no place other than that mentioned therein.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20553[2011 c 336 § 553]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c134.pdf?cite=1913%20c%20134%20§%202[1913 c 134 § 2]; RRS § 8360; ]

== 19.83.030 - Furnishing or selling trading stamps, coupons, or similar devices geographically limited.
No person shall furnish or sell to another for use, in, with, or for the sale of any goods, any trading stamps, coupons, tickets, certificates, cards, or other similar devices to be used in any county, city or town in this state other than that in which such furnishing or selling shall take place.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c221.pdf?cite=1957%20c%20221%20§%202[1957 c 221 § 2]; 1939 c 31 § 1, part; 1913 c 134 § 3, part; RRS § 8361, part; ]

== 19.83.040 - Coupons or similar devices—Exemptions.
. Nothing in this chapter, or in any other statute or ordinance of this state, shall apply to:

.. The issuance and direct redemption by a manufacturer of a premium coupon, certificate, or similar device; or prevent him or her from issuing and directly redeeming such premium coupon, certificate, or similar device, which, however, shall not be issued, circulated, or distributed by retail vendors except when contained in or attached to an original package;

.. The publication by, or distribution through, newspapers or other publications of coupons, certificates, or similar devices; or

.. A coupon, certificate, or similar device which is within, attached to, or a part of a package or container as packaged by the original manufacturer and which is to be redeemed by another manufacturer, if:

... The coupon, certificate, or similar device clearly states the names and addresses of both the issuing manufacturer and the redeeming manufacturer; and

... The issuing manufacturer is responsible for redemption of the coupon, certificate, or similar device if the redeeming manufacturer fails to do so.

. The term "manufacturer," as used in this section, means any vendor of an article of merchandise which is put up by or for him or her in an original package and which is sold under his, her, or its trade name, brand, or mark.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20554[2011 c 336 § 554]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c40.pdf?cite=1983%20c%2040%20§%201[1983 c 40 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c104.pdf?cite=1972%20ex.s.%20c%20104%20§%201[1972 ex.s. c 104 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c221.pdf?cite=1957%20c%20221%20§%203[1957 c 221 § 3]; 1939 c 31 § 1, part; 1913 c 134 § 3, part; RRS § 8361, part; ]

== 19.83.050 - Penalty.
Any person violating any of the provisions of this chapter shall be guilty of a gross misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c134.pdf?cite=1913%20c%20134%20§%204[1913 c 134 § 4]; RRS § 8362; ]

