= 19.40 - Uniform voidable transactions act.
:toc:

== 19.40.011 - Definitions.
As used in this chapter:

. "Affiliate" means:

.. A person that directly or indirectly owns, controls, or holds with power to vote, twenty percent or more of the outstanding voting securities of the debtor, other than a person that holds the securities:

... As a fiduciary or agent without sole discretionary power to vote the securities; or

... Solely to secure a debt, if the person has not in fact exercised the power to vote;

.. A corporation twenty percent or more of whose outstanding voting securities are directly or indirectly owned, controlled, or held with power to vote, by the debtor or a person that directly or indirectly owns, controls, or holds with power to vote, twenty percent or more of the outstanding voting securities of the debtor, other than a person that holds the securities:

... As a fiduciary or agent without sole discretionary power to vote the securities; or

... Solely to secure a debt, if the person has not in fact exercised the power to vote;

.. A person whose business is operated by the debtor under a lease or other agreement, or a person substantially all of whose assets are controlled by the debtor; or

.. A person that operates the debtor's business under a lease or other agreement or controls substantially all of the debtor's assets.

. "Asset" means property of a debtor, but the term does not include:

.. Property to the extent it is encumbered by a valid lien; or

.. Property to the extent it is generally exempt under nonbankruptcy law.

. "Claim," except as used in "claim for relief," means a right to payment, whether or not the right is reduced to judgment, liquidated, unliquidated, fixed, contingent, matured, unmatured, disputed, undisputed, legal, equitable, secured, or unsecured.

. "Creditor" means a person that has a claim.

. "Debt" means liability on a claim.

. "Debtor" means a person that is liable on a claim.

. "Electronic" means relating to technology having electrical, digital, magnetic, wireless, optical, electromagnetic, or similar capabilities.

. "Insider" includes:

.. If the debtor is an individual:

... A relative of the debtor or of a general partner of the debtor;

... A partnership in which the debtor is a general partner;

... A general partner in a partnership described in (a)(ii) of this subsection; or

... A corporation of which the debtor is a director, officer, or person in control;

.. If the debtor is a corporation:

... A director of the debtor;

... An officer of the debtor;

... A person in control of the debtor;

... A partnership in which the debtor is a general partner;

.. A general partner in a partnership described in (b)(iv) of this subsection; or

.. A relative of a general partner, director, officer, or person in control of the debtor;

.. If the debtor is a partnership:

... A general partner in the debtor;

... A relative of a general partner in, or a general partner of, or a person in control of the debtor;

... Another partnership in which the debtor is a general partner;

... A general partner in a partnership described in (c)(iii) of this subsection; or

.. A person in control of the debtor;

.. An affiliate, or an insider of an affiliate as if the affiliate were the debtor; and

.. A managing agent of the debtor.

. "Lien" means a charge against or an interest in property to secure payment of a debt or performance of an obligation, and includes a security interest created by agreement, a judicial lien obtained by legal or equitable process or proceedings, a common-law lien, or a statutory lien.

. "Organization" means a person other than an individual.

. "Person" means an individual, estate, partnership, association, trust, business or nonprofit entity, public corporation, government or governmental subdivision, agency, or instrumentality, or other legal or commercial entity.

. "Property" means anything that may be the subject of ownership.

. "Reasonably equivalent value" includes, without limitation, a transfer or an obligation that is within the range of values for which the transferor would have sold the property or services to, or purchased the property or services from, the transferee in an arm's length transaction at market rates.

. "Record" means information that is inscribed on a tangible medium or that is stored in an electronic or other medium and is retrievable in perceivable form.

. "Relative" means an individual related by consanguinity within the third degree as determined by the common law, a spouse, or an individual related to a spouse within the third degree as so determined, and includes an individual in an adoptive relationship within the third degree.

. "Sign" means, with present intent to authenticate or adopt a record:

.. To execute or adopt a tangible symbol; or

.. To attach to or logically associate with the record an electronic symbol, sound, or process.

. "Transfer" means every mode, direct or indirect, absolute or conditional, voluntary or involuntary, of disposing of or parting with an asset or an interest in an asset, and includes payment of money, release, lease, license, and creation of a lien or other encumbrance.

. "Valid lien" means a lien that is effective against the holder of a judicial lien subsequently obtained by legal or equitable process or proceedings.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5085.SL.pdf?cite=2017%20c%2057%20§%201[2017 c 57 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c444.pdf?cite=1987%20c%20444%20§%201[1987 c 444 § 1]; ]

== 19.40.021 - Insolvency.
. A debtor is insolvent if, at a fair valuation, the sum of the debtor's debts is greater than the sum of the debtor's assets.

. A debtor that is generally not paying the debtor's debts as they become due other than as a result of a bona fide dispute is presumed to be insolvent. The presumption imposes on the party against which the presumption is directed the burden of proving that the nonexistence of insolvency is more probable than its existence.

. Assets under this section do not include property that has been transferred, concealed, or removed with intent to hinder, delay, or defraud creditors or that has been transferred in a manner making the transfer voidable under this chapter.

. Debts under this section do not include an obligation to the extent it is secured by a valid lien on property of the debtor not included as an asset.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5085.SL.pdf?cite=2017%20c%2057%20§%202[2017 c 57 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c444.pdf?cite=1987%20c%20444%20§%202[1987 c 444 § 2]; ]

== 19.40.031 - Value.
. Value is given for a transfer or an obligation if, in exchange for the transfer or obligation, property is transferred or an antecedent debt is secured or satisfied, but value does not include an unperformed promise made otherwise than in the ordinary course of the promisor's business to furnish support to the debtor or another person.

. For the purposes of RCW 19.40.041(1)(b) and 19.40.051, a person gives a reasonably equivalent value if the person acquires an interest of the debtor in an asset pursuant to a regularly conducted, noncollusive foreclosure sale or execution of a power of sale for the acquisition or disposition of the interest of the debtor upon default under a mortgage, deed of trust, or security agreement.

. A transfer is made for present value if the exchange between the debtor and the transferee is intended by them to be contemporaneous and is in fact substantially contemporaneous.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5085.SL.pdf?cite=2017%20c%2057%20§%203[2017 c 57 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c444.pdf?cite=1987%20c%20444%20§%203[1987 c 444 § 3]; ]

== 19.40.041 - Transfers voidable as to present and future creditors.
. A transfer made or obligation incurred by a debtor is voidable as to a creditor, whether the creditor's claim arose before or after the transfer was made or the obligation was incurred, if the debtor made the transfer or incurred the obligation:

.. With actual intent to hinder, delay, or defraud any creditor of the debtor; or

.. Without receiving a reasonably equivalent value in exchange for the transfer or obligation, and the debtor:

... Was engaged or was about to engage in a business or a transaction for which the remaining assets of the debtor were unreasonably small in relation to the business or transaction; or

... Intended to incur, or believed or reasonably should have believed that the debtor would incur, debts beyond the debtor's ability to pay as they became due.

. In determining actual intent under subsection (1)(a) of this section, consideration may be given, among other factors, to whether:

.. The transfer or obligation was to an insider;

.. The debtor retained possession or control of the property transferred after the transfer;

.. The transfer or obligation was disclosed or concealed;

.. Before the transfer was made or obligation was incurred, the debtor had been sued or threatened with suit;

.. The transfer was of substantially all the debtor's assets;

.. The debtor absconded;

.. The debtor removed or concealed assets;

.. The value of the consideration received by the debtor was reasonably equivalent to the value of the asset transferred or the amount of the obligation incurred;

.. The debtor was insolvent or became insolvent shortly after the transfer was made or the obligation was incurred;

.. The transfer occurred shortly before or shortly after a substantial debt was incurred; and

.. The debtor transferred the essential assets of the business to a lienor that transferred the assets to an insider of the debtor.

. A creditor making a claim for relief under subsection (1) of this section has the burden of proving the elements of the claim for relief by a preponderance of the evidence.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5085.SL.pdf?cite=2017%20c%2057%20§%204[2017 c 57 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c444.pdf?cite=1987%20c%20444%20§%204[1987 c 444 § 4]; ]

== 19.40.051 - Transfers voidable as to present creditors.
. A transfer made or obligation incurred by a debtor is voidable as to a creditor whose claim arose before the transfer was made or the obligation was incurred if the debtor made the transfer or incurred the obligation without receiving a reasonably equivalent value in exchange for the transfer or obligation and the debtor was insolvent at that time or the debtor became insolvent as a result of the transfer or obligation.

. A transfer made by a debtor is voidable as to a creditor whose claim arose before the transfer was made if the transfer was made to an insider for an antecedent debt, the debtor was insolvent at that time, and the insider had reasonable cause to believe that the debtor was insolvent.

. Subject to RCW 19.40.021(2), a creditor making a claim for relief under subsection (1) or (2) of this section has the burden of proving the elements of the claim for relief by a preponderance of the evidence.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5085.SL.pdf?cite=2017%20c%2057%20§%205[2017 c 57 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c444.pdf?cite=1987%20c%20444%20§%205[1987 c 444 § 5]; ]

== 19.40.061 - When transfer is made or obligation is incurred.
For the purposes of this chapter:

. A transfer is made:

.. With respect to an asset that is real property other than a fixture, but including the interest of a seller or purchaser under a contract for the sale of the asset, when the transfer is so far perfected that a good-faith purchaser of the asset from the debtor against which applicable law permits the transfer to be perfected cannot acquire an interest in the asset that is superior to the interest of the transferee; and

.. With respect to an asset that is not real property or that is a fixture, when the transfer is so far perfected that a creditor on a simple contract cannot acquire a judicial lien otherwise than under this chapter that is superior to the interest of the transferee;

. If applicable law permits the transfer to be perfected as provided in subsection (1) of this section and the transfer is not so perfected before the commencement of an action for relief under this chapter, the transfer is deemed made immediately before the commencement of the action;

. If applicable law does not permit the transfer to be perfected as provided in subsection (1) of this section, the transfer is made when it becomes effective between the debtor and the transferee;

. A transfer is not made until the debtor has acquired rights in the asset transferred; and

. An obligation is incurred:

.. If oral, when it becomes effective between the parties; or

.. If evidenced by a record, when the record signed by the obligor is delivered to or for the benefit of the obligee.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5085.SL.pdf?cite=2017%20c%2057%20§%206[2017 c 57 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c444.pdf?cite=1987%20c%20444%20§%206[1987 c 444 § 6]; ]

== 19.40.071 - Remedies of creditors.
. In an action for relief against a transfer or obligation under this chapter, a creditor, subject to the limitations in RCW 19.40.081, may obtain:

.. Avoidance of the transfer or obligation to the extent necessary to satisfy the creditor's claim;

.. An attachment or other provisional remedy against the asset transferred or other property of the transferee if available under applicable law; and

.. Subject to applicable principles of equity and in accordance with applicable rules of civil procedure:

... An injunction against further disposition by the debtor or a transferee, or both, of the asset transferred or of other property;

... Appointment of a receiver to take charge of the asset transferred or of other property of the transferee; or

... Any other relief the circumstances may require.

. If a creditor has obtained a judgment on a claim against the debtor, the creditor, if the court so orders, may levy execution on the asset transferred or its proceeds.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5085.SL.pdf?cite=2017%20c%2057%20§%207[2017 c 57 § 7]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2400.SL.pdf?cite=2000%20c%20171%20§%2054[2000 c 171 § 54]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c444.pdf?cite=1987%20c%20444%20§%207[1987 c 444 § 7]; ]

== 19.40.081 - Defenses, liability, and protection of transferee.
. A transfer or obligation is not voidable under RCW 19.40.041(1) or 19.40.051(1) against a person that took in good faith and for a reasonably equivalent value whether or not given to the debtor or against any subsequent transferee or obligee.

. To the extent a transfer is avoidable in an action by a creditor under RCW 19.40.071(1)(a), the following rules apply:

.. Except as otherwise provided in this section, the creditor may recover judgment for the value of the asset transferred, as adjusted under subsection (c) of this section, or the amount necessary to satisfy the creditor's claim, whichever is less. The judgment may be entered against:

... The first transferee of the asset or the person for whose benefit the transfer was made; or

... An immediate or mediate transferee of the first transferee, other than:

(A) A good-faith transferee that took for value; or

(B) An immediate or mediate good-faith transferee of a person described in (a)(ii)(A) of this subsection.

.. Recovery pursuant to RCW 19.40.071 (1)(a) or (2) or from the asset transferred or its proceeds, by levy or otherwise, is available only against a person described in (a)(i) or (ii) of this subsection.

. If the judgment under subsection (2) of this section is based upon the value of the asset transferred, the judgment must be for an amount equal to the value of the asset at the time of the transfer, subject to adjustment as the equities may require.

. Notwithstanding voidability of a transfer or an obligation under this chapter, a good-faith transferee or obligee is entitled, to the extent of the value given the debtor for the transfer or obligation, to:

.. A lien on or a right to retain an interest in the asset transferred;

.. Enforcement of an obligation incurred; or

.. A reduction in the amount of the liability on the judgment.

. A transfer is not voidable under RCW 19.40.041(1)(b) or 19.40.051 if the transfer results from:

.. Termination of a lease upon default by the debtor when the termination is pursuant to the lease and applicable law; or

.. Enforcement of a security interest in compliance with Article 9A of Title 62A RCW, other than acceptance of collateral in full or partial satisfaction of the obligation it secures.

. A transfer is not voidable under RCW 19.40.051(2):

.. To the extent the insider gave new value to or for the benefit of the debtor after the transfer was made, except to the extent the new value was secured by a valid lien;

.. If made in the ordinary course of business or financial affairs of the debtor and the insider; or

.. If made pursuant to a good faith effort to rehabilitate the debtor and the transfer secured present value given for that purpose as well as an antecedent debt of the debtor.

. The following rules determine the burden of proving matters referred to in this section:

.. A party that seeks to invoke subsection (1), (4), (5), or (6) of this section has the burden of proving the applicability of that subsection.

.. Except as otherwise provided in (c) and (d) of this subsection, the creditor has the burden of proving each applicable element of subsection (2) or (3) of this section.

.. The transferee has the burden of proving the applicability to the transferee of subsection (2)(a)(ii)(A) or (B) of this subsection.

.. A party that seeks adjustment under subsection (3) of this section has the burden of proving the adjustment.

. The standard of proof required to establish matters referred to in this section is preponderance of the evidence.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5085.SL.pdf?cite=2017%20c%2057%20§%208[2017 c 57 § 8]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5053.SL.pdf?cite=2001%20c%2032%20§%201[2001 c 32 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c444.pdf?cite=1987%20c%20444%20§%208[1987 c 444 § 8]; ]

== 19.40.091 - Extinguishment of claim for relief.
A claim for relief with respect to a transfer or obligation under this chapter is extinguished unless action is brought:

. Under RCW 19.40.041(1)(a), not later than four years after the transfer was made or the obligation was incurred or, if later, not later than one year after the transfer or obligation was or could reasonably have been discovered by the claimant;

. Under RCW 19.40.041(1)(b) or 19.40.051(1), not later than four years after the transfer was made or the obligation was incurred; or

. Under RCW 19.40.051(2), not later than one year after the transfer was made.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5085.SL.pdf?cite=2017%20c%2057%20§%209[2017 c 57 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c444.pdf?cite=1987%20c%20444%20§%209[1987 c 444 § 9]; ]

== 19.40.101 - Governing law.
. In this section, the following rules determine a debtor's location:

.. A debtor who is an individual is located at the individual's principal residence.

.. A debtor that is an organization and has only one place of business is located at its place of business.

.. A debtor that is an organization and has more than one place of business is located at its chief executive office.

. A claim for relief in the nature of a claim for relief under this chapter is governed by the local law of the jurisdiction in which the debtor is located when the transfer is made or the obligation is incurred. 

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5085.SL.pdf?cite=2017%20c%2057%20§%2010[2017 c 57 § 10]; ]

== 19.40.111 - Application to series organization.
. In this section:

.. "Protected series" means an arrangement, however denominated, created by a series organization that, pursuant to the law under which the series organization is organized, has the characteristics set forth in (b) of this subsection.

.. "Series organization" means an organization that, pursuant to the law under which it is organized, has the following characteristics:

... The organic record of the organization provides for creation by the organization of one or more protected series, however denominated, with respect to specified property of the organization, and for records to be maintained for each protected series that identify the property of or associated with the protected series.

... Debt incurred or existing with respect to the activities of, or property of or associated with, a particular protected series is enforceable against the property of or associated with the protected series only, and not against the property of or associated with the organization or other protected series of the organization.

... Debt incurred or existing with respect to the activities or property of the organization is enforceable against the property of the organization only, and not against the property of or associated with a protected series of the organization.

. A series organization and each protected series of the organization is a separate person for purposes of this chapter, even if for other purposes a protected series is not a person separate from the organization or other protected series of the organization.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5085.SL.pdf?cite=2017%20c%2057%20§%2011[2017 c 57 § 11]; ]

== 19.40.121 - Relation to electronic signatures in global and national commerce act.
This chapter modifies, limits, or supersedes the electronic signatures in global and national commerce act, 15 U.S.C. Sec. 7001 et seq., but does not modify, limit, or supersede section 101(c) of that act, 15 U.S.C. Sec. 7001(c), or authorize electronic delivery of any of the notices described in section 103(b) of that act, 15 U.S.C. Sec. 7003(b).

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5085.SL.pdf?cite=2017%20c%2057%20§%2012[2017 c 57 § 12]; ]

== 19.40.900 - Short title.
This chapter, which was formerly cited as the uniform fraudulent transfer act, may be cited as the uniform voidable transactions act.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5085.SL.pdf?cite=2017%20c%2057%20§%2013[2017 c 57 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c444.pdf?cite=1987%20c%20444%20§%2012[1987 c 444 § 12]; ]

== 19.40.902 - Supplementary provisions.
Unless displaced by the provisions of this chapter, the principles of law and equity, including the law merchant and the law relating to principal and agent, estoppel, laches, fraud, misrepresentation, duress, coercion, mistake, insolvency, or other validating or invalidating cause, supplement its provisions.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c444.pdf?cite=1987%20c%20444%20§%2010[1987 c 444 § 10]; ]

== 19.40.903 - Uniformity of application and construction.
This chapter shall be applied and construed to effectuate its general purpose to make uniform the law with respect to the subject of this chapter among states enacting it.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c444.pdf?cite=1987%20c%20444%20§%2011[1987 c 444 § 11]; ]

== 19.40.904 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%2054[2009 c 521 § 54]; ]

== 19.40.905 - Effect on prior transfers and obligations—2017 c 57.
. Chapter 57, Laws of 2017 applies to a transfer made or obligation incurred on or after July 23, 2017.

. Chapter 57, Laws of 2017 does not apply to a transfer made or obligation incurred before July 23, 2017.

. Chapter 57, Laws of 2017 does not apply to a right of action that has accrued before July 23, 2017.

. For the purposes of this section, a transfer is made and an obligation is incurred at the time provided in RCW 19.40.061.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5085.SL.pdf?cite=2017%20c%2057%20§%2014[2017 c 57 § 14]; ]

