= 19.16 - Collection agencies.
:toc:

== 19.16.100 - Definitions.
Unless a different meaning is plainly required by the context, the following words and phrases as hereinafter used in this chapter shall have the following meanings:

. "Board" means the Washington state collection agency board.

. "Claim" means any obligation for the payment of money or thing of value arising out of any agreement or contract, express or implied.

. "Client" or "customer" means any person authorizing or employing a collection agency to collect a claim.

. "Collection agency" means and includes:

.. Any person directly or indirectly engaged in soliciting claims for collection, or collecting or attempting to collect claims owed or due or asserted to be owed or due another person;

.. Any person who directly or indirectly furnishes or attempts to furnish, sells, or offers to sell forms represented to be a collection system or scheme intended or calculated to be used to collect claims even though the forms direct the debtor to make payment to the creditor and even though the forms may be or are actually used by the creditor himself or herself in his or her own name;

.. Any person who in attempting to collect or in collecting his or her own claim uses a fictitious name or any name other than his or her own which would indicate to the debtor that a third person is collecting or attempting to collect such claim;

.. A debt buyer as defined in this section;

.. Any person or entity attempting to enforce a lien under chapter 60.44 RCW, other than the person or entity originally entitled to the lien.

. "Collection agency" does not mean and does not include:

.. Any individual engaged in soliciting claims for collection, or collecting or attempting to collect claims on behalf of a licensee under this chapter, if said individual is an employee of the licensee;

.. Any individual collecting or attempting to collect claims for not more than one employer, if all the collection efforts are carried on in the name of the employer and if the individual is an employee of the employer;

.. Any person whose collection activities are carried on in his, her, or its true name and are confined and are directly related to the operation of a business other than that of a collection agency, such as but not limited to: Trust companies; savings and loan associations; building and loan associations; abstract companies doing an escrow business; real estate brokers; property management companies collecting assessments, charges, or fines on behalf of condominium unit owners associations, associations of apartment owners, or homeowners' associations; public officers acting in their official capacities; persons acting under court order; lawyers; insurance companies; credit unions; loan or finance companies; mortgage banks; and banks;

.. Any person who on behalf of another person prepares or mails monthly or periodic statements of accounts due if all payments are made to that other person and no other collection efforts are made by the person preparing the statements of account;

.. An "out-of-state collection agency" as defined in this chapter; or

.. Any person while acting as a debt collector for another person, both of whom are related by common ownership or affiliated by corporate control, if the person acting as a debt collector does so only for persons to whom it is so related or affiliated and if the principal business of the person is not the collection of debts.

. "Commercial claim" means any obligation for payment of money or thing of value arising out of any agreement or contract, express or implied, where the transaction which is the subject of the agreement or contract is not primarily for personal, family, or household purposes.

. "Debt buyer" means any person or entity that is engaged in the business of purchasing delinquent or charged off claims for collection purposes, whether it collects the claims itself or hires a third party for collection or an attorney for litigation in order to collect such claims.

. "Debtor" means any person owing or alleged to owe a claim.

. "Director" means the director of licensing.

. "Licensee" means any person licensed under this chapter.

. "Medical debt" means any obligation for the payment of money arising out of any agreement or contract, express or implied, for the provision of health care services as defined in RCW 48.44.010. In the context of "medical debt," "charity care" has the same meaning as provided in RCW 70.170.020.

. "Out-of-state collection agency" means a person whose activities within this state are limited to collecting debts from debtors located in this state by means of interstate communications, including telephone, mail, or facsimile transmission, from the person's location in another state on behalf of clients located outside of this state, but does not include any person who is excluded from the definition of the term "debt collector" under the federal fair debt collection practices act (15 U.S.C. Sec. 1692a(6)).

. "Person" includes individual, firm, partnership, trust, joint venture, association, or corporation.

. "Statement of account" means a report setting forth only amounts billed, invoices, credits allowed, or aged balance due.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2476-S.SL.pdf?cite=2020%20c%2030%20§%201[2020 c 30 § 1]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1531-S.SL.pdf?cite=2019%20c%20227%20§%203[2019 c 227 § 3]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1503-S.SL.pdf?cite=2015%20c%20201%20§%203[2015 c 201 § 3]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1822-S.SL.pdf?cite=2013%20c%20148%20§%201[2013 c 148 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5211.SL.pdf?cite=2003%20c%20203%20§%201[2003 c 203 § 1]; prior:  2001 c 47 § 1; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1983.SL.pdf?cite=2001%20c%2043%20§%201[2001 c 43 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6093-S.SL.pdf?cite=1994%20c%20195%20§%201[1994 c 195 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c190.pdf?cite=1990%20c%20190%20§%201[1990 c 190 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%2081[1979 c 158 § 81]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%201[1971 ex.s. c 253 § 1]; ]

== 19.16.110 - License required.
No person shall act, assume to act, or advertise as a collection agency or out-of-state collection agency as defined in this chapter, except as authorized by this chapter, without first having applied for and obtained a license from the director.

Nothing contained in this section shall be construed to require a regular employee of a collection agency or out-of-state collection agency duly licensed under this chapter to procure a collection agency license.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6093-S.SL.pdf?cite=1994%20c%20195%20§%202[1994 c 195 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%202[1971 ex.s. c 253 § 2]; ]

== 19.16.120 - Unprofessional conduct—Support order, noncompliance.
In addition to other provisions of this chapter, and the unprofessional conduct described in RCW 18.235.130, the following conduct, acts, or conditions constitute unprofessional conduct:

. If an individual applicant or licensee is less than eighteen years of age or is not a resident of this state.

. If an applicant or licensee is not authorized to do business in this state.

. If the application or renewal forms required by this chapter are incomplete, fees required under RCW 19.16.140 and 19.16.150, if applicable, have not been paid, and the surety bond or cash deposit or other negotiable security acceptable to the director required by RCW 19.16.190, if applicable, has not been filed or renewed or is canceled.

. If any individual applicant, owner, officer, director, or managing employee of a nonindividual applicant or licensee:

.. Has had any judgment entered against him or her in any civil action involving forgery, embezzlement, obtaining money under false pretenses, larceny, extortion, or conspiracy to defraud and five years have not elapsed since the date of the entry of the final judgment in said action: PROVIDED, That in no event shall a license be issued unless the judgment debt has been discharged;

.. Has had his or her license to practice law suspended or revoked and two years have not elapsed since the date of such suspension or revocation, unless he or she has been relicensed to practice law in this state;

.. Has had any judgment entered against such a person under the provisions of RCW 19.86.080 or 19.86.090 involving a violation or violations of RCW 19.86.020 and two years have not elapsed since the entry of the final judgment: PROVIDED, That in no event shall a license be issued unless the terms of such judgment, if any, have been fully complied with: PROVIDED FURTHER, That said judgment shall not be grounds for denial, suspension, nonrenewal, or revocation of a license unless the judgment arises out of and is based on acts of the applicant, owner, officer, director, managing employee, or licensee while acting for or as a collection agency or an out-of-state collection agency;

.. Has petitioned for bankruptcy, and two years have not elapsed since the filing of the petition;

.. Is insolvent in the sense that the person's liabilities exceed the person's assets or in the sense that the person cannot meet obligations as they mature;

.. Has failed to pay any civil, monetary penalty assessed in accordance with RCW 19.16.351 within ten days after the assessment becomes final;

.. Has failed to comply with, or violated any provisions of this chapter or any rule or regulation issued pursuant to this chapter, and two years have not elapsed since the occurrence of said noncompliance or violation; or

.. Has been found by a court of competent jurisdiction to have violated the federal fair debt collection practices act, 15 U.S.C. Sec. 1692 et seq., or the Washington state consumer protection act, chapter 19.86 RCW, and two years have not elapsed since that finding.

Except as otherwise provided in this section, any person who is engaged in the collection agency business as of January 1, 1972, shall, upon filing the application, paying the fees, and filing the surety bond or cash deposit or other negotiable security in lieu of bond required by this chapter, be issued a license under this chapter.

The director shall immediately suspend the license or certificate of a person who has been certified pursuant to RCW 74.20A.320 by the department of social and health services as a person who is not in compliance with a support order. If the person has continued to meet all other requirements for reinstatement during the suspension, reissuance of the license or certificate shall be automatic upon the director's receipt of a release issued by the department of social and health services stating that the licensee is in compliance with the order.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20266[2002 c 86 § 266]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20847[1997 c 58 § 847]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6093-S.SL.pdf?cite=1994%20c%20195%20§%203[1994 c 195 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c194.pdf?cite=1977%20ex.s.%20c%20194%20§%201[1977 ex.s. c 194 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c20.pdf?cite=1973%201st%20ex.s.%20c%2020%20§%201[1973 1st ex.s. c 20 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%203[1971 ex.s. c 253 § 3]; ]

== 19.16.130 - License—Application—Form—Contents.
Every application for a license shall be in writing, under oath, and in the form prescribed by the director.

Every application shall contain such relevant information as the director may require.

The applicant shall furnish the director with such evidence as the director may reasonably require to establish that the requirements and qualifications for a licensee have been fulfilled by the applicant.

Every application for a license shall state, among other things that may be required, the name of the applicant with the name under which the applicant will do business and the location by street and number, city and state of each office of the business for which the license is sought.

No license shall be issued in any fictitious name which may be confused with or which is similar to any federal, state, county, or municipal governmental function or agency or in any name which may tend to describe any business function or enterprise not actually engaged in by the applicant or in any name which is the same as or so similar to that of any existing licensee as would tend to deceive the public or in any name which would otherwise tend to be deceptive or misleading. The foregoing shall not necessarily preclude the use of a name which may be followed by a geographically descriptive title which would distinguish it from a similar name licensed but operating in a different geographical area.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%204[1971 ex.s. c 253 § 4]; ]

== 19.16.140 - License—Application—Fees—Exemptions.
Each applicant when submitting his or her application shall pay a licensing fee and an investigation fee determined by the director as provided in RCW 43.24.086. The licensing fee for an out-of-state collection agency shall not exceed fifty percent of the licensing fee for a collection agency. An out-of-state collection agency is exempt from the licensing fee if the agency is licensed or registered in a state that does not require payment of an initial fee by any person who collects debts in the state only by means of interstate communications from the person's location in another state. If a license is not issued in response to the application, the license fee shall be returned to the applicant.

An annual license fee determined by the director as provided in RCW 43.24.086 shall be paid to the director on or before January first of each year. The annual license fee for an out-of-state collection agency shall not exceed fifty percent of the annual license fee for a collection agency. An out-of-state collection agency is exempt from the annual license fee if the agency is licensed or registered in a state that does not require payment of an annual fee by any person who collects debts in the state only by means of interstate communications from the person's location in another state. If the annual license fee is not paid on or before January first, the licensee shall be assessed a penalty for late payment in an amount determined by the director as provided in RCW 43.24.086. If the fee and penalty are not paid by January thirty-first, it will be necessary for the licensee to submit a new application for a license: PROVIDED, That no license shall be issued upon such new application unless and until all fees and penalties previously accrued under this section have been paid.

Any license or branch office certificate issued under the provisions of this chapter shall expire on December thirty-first following the issuance thereof.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20509[2011 c 336 § 509]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6093-S.SL.pdf?cite=1994%20c%20195%20§%204[1994 c 195 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2081[1985 c 7 § 81]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c30.pdf?cite=1975%201st%20ex.s.%20c%2030%20§%2090[1975 1st ex.s. c 30 § 90]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%205[1971 ex.s. c 253 § 5]; ]

== 19.16.150 - Branch office certificate required.
If a licensee maintains a branch office, he, she, or it shall not operate a collection agency business in such branch office until he, she, or it has secured a branch office certificate therefor from the director. A licensee, so long as his, her, or its license is in full force and effect and in good standing, shall be entitled to branch office certificates for any branch office operated by such licensee upon payment of the fee therefor provided in this chapter.

Each licensee when applying for a branch office certificate shall pay a fee determined by the director as provided in RCW 43.24.086. An annual fee determined by the director as provided in RCW 43.24.086 for a branch office certificate shall be paid to the director on or before January first of each year. If the annual fee is not paid on or before January first, a penalty for late payment in an amount determined by the director as provided in RCW 43.24.086 shall be assessed. If the fee and the penalty are not paid by January thirty-first, it will be necessary for the licensee to apply for a new branch office certificate: PROVIDED, That no such new branch office certificate shall be issued unless and until all fees and penalties previously accrued under this section have been paid.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20510[2011 c 336 § 510]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2082[1985 c 7 § 82]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c30.pdf?cite=1975%201st%20ex.s.%20c%2030%20§%2091[1975 1st ex.s. c 30 § 91]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%206[1971 ex.s. c 253 § 6]; ]

== 19.16.160 - License and branch office certificate—Form—Contents—Display.
Each license and branch office certificate, when issued, shall be in the form and size prescribed by the director and shall state in addition to any other matter required by the director:

. The name of the licensee;

. The name under which the licensee will do business;

. The address at which the collection agency business is to be conducted; and

. The number and expiration date of the license or branch office certificate.

A licensee shall display his, her, or its license in a conspicuous place in his, her, or its principal place of business and, if he, she, or it conducts a branch office, the branch office certificate shall be conspicuously displayed in the branch office.

Concurrently with or prior to engaging in any activity as a collection agency, as defined in this chapter, any person shall furnish to his, her, or its client or customer the number indicated on the collection agency license issued to him, her, or it pursuant to this section.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20511[2011 c 336 § 511]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c20.pdf?cite=1973%201st%20ex.s.%20c%2020%20§%202[1973 1st ex.s. c 20 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%207[1971 ex.s. c 253 § 7]; ]

== 19.16.170 - Procedure upon change of name or business location.
Whenever a licensee shall contemplate a change of his, her, or its trade name or a change in the location of his, her, or its principal place of business or branch office, he, she, or it shall give written notice of such proposed change to the director. The director shall approve the proposed change and issue a new license or a branch office certificate, as the case may be, reflecting the change.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20512[2011 c 336 § 512]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%208[1971 ex.s. c 253 § 8]; ]

== 19.16.180 - Assignability of license or branch office certificate.
. Except as provided in subsection (2) of this section, a license or branch office certificate granted under this chapter is not assignable or transferable.

. Upon the death of an individual licensee, the director shall have the right to transfer the license and any branch office certificate of the decedent to the personal representative of his or her estate for the period of the unexpired term of the license and such additional time, not to exceed one year from the date of death of the licensee, as said personal representative may need in order to settle the deceased's estate or sell the collection agency.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20513[2011 c 336 § 513]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%209[1971 ex.s. c 253 § 9]; ]

== 19.16.190 - Surety bond requirements—Cash deposit or securities—Exception.
. Except as limited by subsection (7) of this section, each applicant shall, at the time of applying for a license, file with the director a surety bond in the sum of five thousand dollars. The bond shall be annually renewable on January first of each year, shall be approved by the director as to form and content, and shall be executed by the applicant as principal and by a surety company authorized to do business in this state as surety. Such bond shall run to the state of Washington as obligee for the benefit of the state and conditioned that the licensee shall faithfully and truly perform all agreements entered into with the licensee's clients or customers and shall, within thirty days after the close of each calendar month, account to and pay to his, her, or its client or customer the net proceeds of all collections made during the preceding calendar month and due to each client or customer less any offsets due licensee under RCW 19.16.210 and 19.16.220. The bond required by this section shall remain in effect until canceled by action of the surety or the licensee or the director.

. An applicant for a license under this chapter may furnish, file, and deposit with the director, in lieu of the surety bond provided for herein, a cash deposit or other negotiable security acceptable to the director. The security deposited with the director in lieu of the surety bond shall be returned to the licensee at the expiration of one year after the collection agency's license has expired or been revoked if no legal action has been instituted against the licensee or on said security deposit at the expiration of said one year.

. A surety may file with the director notice of his, her, or its withdrawal on the bond of the licensee. Upon filing a new bond or upon the revocation of the collection agency license or upon the expiration of sixty days after the filing of notice of withdrawal as surety by the surety, the liability of the former surety for all future acts of the licensee shall terminate.

. The director shall immediately cancel the bond given by a surety company upon being advised that the surety company's license to transact business in this state has been revoked.

. Upon the filing with the director of notice by a surety of his, her, or its withdrawal as the surety on the bond of a licensee or upon the cancellation by the director of the bond of a surety as provided in this section, the director shall immediately give notice to the licensee of the withdrawal or cancellation. The notice shall be sent to the licensee by registered or certified mail with request for a return receipt and addressed to the licensee at his, her, or its main office as shown by the records of the director. At the expiration of thirty days from the date of mailing the notice, the license of the licensee shall be terminated, unless the licensee has filed a new bond with a surety satisfactory to the director.

. All bonds given under this chapter shall be filed and held in the office of the director.

. An out-of-state collection agency need not fulfill the bonding requirements under this section if the out-of-state collection agency maintains an adequate bond or legal alternative as required by the state in which the out-of-state collection agency is located.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20514[2011 c 336 § 514]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6093-S.SL.pdf?cite=1994%20c%20195%20§%205[1994 c 195 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2010[1971 ex.s. c 253 § 10]; ]

== 19.16.200 - Action on bond, cash deposit or securities.
In addition to all other legal remedies, an action may be brought in any court of competent jurisdiction upon the bond or cash deposit or security in lieu thereof, required by RCW 19.16.190, by any person to whom the licensee fails to account and pay as set forth in such bond or by any client or customer of the licensee who has been damaged by failure of the licensee to comply with all agreements entered into with such client or customer: PROVIDED, That the aggregate liability of the surety to all such clients or customers shall in no event exceed the sum of such bond.

An action upon such bond or security shall be commenced by serving and filing of the complaint within one year from the date of the cancellation of the bond or, in the case of a cash deposit or other security deposited in lieu of the surety bond, within one year of the date of expiration or revocation of license: PROVIDED, That no action shall be maintained upon such bond or such cash deposit or other security for any claim which has been barred by any nonclaim statute or statute of limitations of this state. Two copies of the complaint shall be served by registered or certified mail upon the director at the time the suit is started. Such service shall constitute service on the surety. The director shall transmit one of said copies of the complaint served on him or her to the surety within forty-eight hours after it shall have been received.

The director shall maintain a record, available for public inspection, of all suits commenced under this chapter upon surety bonds, or the cash or other security deposited in lieu thereof.

In the event of a judgment being entered against the deposit or security referred to in RCW 19.16.190(2), the director shall, upon receipt of a certified copy of a final judgment, pay said judgment from the amount of the deposit or security.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20515[2011 c 336 § 515]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2011[1971 ex.s. c 253 § 11]; ]

== 19.16.210 - Accounting and payments by licensee to customer.
A licensee shall within thirty days after the close of each calendar month account in writing to his, her, or its customers for all collections made during that calendar month and pay to his, her, or its customers the net proceeds due and payable of all collections made during that calendar month except that a licensee need not account to the customer for:

. Court costs recovered which were previously advanced by licensee or his, her, or its attorney.

. Attorneys' fees and interest or other charges incidental to the principal amount of the obligation legally and properly belonging to the licensee, if such charges are retained by the licensee after the principal amount of the obligation has been accounted for and remitted to the customer. When the net proceeds are less than ten dollars at the end of any calendar month, payments may be deferred for a period not to exceed three months.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20516[2011 c 336 § 516]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2012[1971 ex.s. c 253 § 12]; ]

== 19.16.220 - Accounting and payments by customer to licensee.
Every customer of a licensee shall, within thirty days after the close of each calendar month, account and pay to his, her, or its collection agency all sums owing to the collection agency for payments received by the customer during that calendar month on claims in the hands of the collection agency.

If a customer fails to pay a licensee any sums due under this section, the licensee shall, in addition to other remedies provided by law, have the right to offset any moneys due the licensee under this section against any moneys due customer under RCW 19.16.210.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20517[2011 c 336 § 517]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2013[1971 ex.s. c 253 § 13]; ]

== 19.16.230 - Licensee—Business office—Records to be kept.
. Every licensee required to keep and maintain records pursuant to this section, other than an out-of-state collection agency, shall establish and maintain a regular active business office in the state of Washington for the purpose of conducting his, her, or its collection agency business. Said office must be open to the public during reasonable stated business hours, and must be managed by a resident of the state of Washington.

. Every licensee shall keep a record of all sums collected by him, her, or it and all disbursements made by him, her, or it. All such records shall be kept at the business office referred to in subsection (1) of this section, unless the licensee is an out-of-state collection agency, in which case the record shall be kept at the business office listed on the licensee's license.

. Licensees shall maintain and preserve accounting records of collections and payments to customers for a period of four years from the date of the last entry thereon.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20518[2011 c 336 § 518]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6093-S.SL.pdf?cite=1994%20c%20195%20§%206[1994 c 195 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c85.pdf?cite=1987%20c%2085%20§%201[1987 c 85 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c20.pdf?cite=1973%201st%20ex.s.%20c%2020%20§%203[1973 1st ex.s. c 20 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2014[1971 ex.s. c 253 § 14]; ]

== 19.16.240 - Licensee—Trust fund account—Exception.
Each licensee, other than an out-of-state collection agency, shall at all times maintain a separate bank account in this state in which all moneys collected by the licensee shall be deposited except that negotiable instruments received may be forwarded directly to a customer. Moneys received must be deposited within ten days after posting to the book of accounts. In no event shall moneys received be disposed of in any manner other than to deposit such moneys in said account or as provided in this section.

The bank account shall bear some title sufficient to distinguish it from the licensee's personal or general checking account, such as "Customer's Trust Fund Account". There shall be sufficient funds in said trust account at all times to pay all moneys due or owing to all customers and no disbursements shall be made from such account except to customers or to remit moneys collected from debtors on assigned claims and due licensee's attorney or to refund over payments except that a licensee may periodically withdraw therefrom such moneys as may accrue to licensee.

Any money in such trust account belonging to a licensee may be withdrawn for the purpose of transferring the same into the possession of licensee or into a personal or general account of licensee.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6093-S.SL.pdf?cite=1994%20c%20195%20§%207[1994 c 195 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2015[1971 ex.s. c 253 § 15]; ]

== 19.16.245 - Financial statement.
No licensee shall receive any money from any debtor as a result of the collection of any claim until he, she, or it shall have submitted a financial statement showing the assets and liabilities of the licensee truly reflecting that the licensee's net worth is not less than the sum of seven thousand five hundred dollars, in cash or its equivalent, of which not less than five thousand dollars shall be deposited in a bank, available for the use of the licensee's business. Any money so collected shall be subject to the provisions of RCW 19.16.430(2). The financial statement shall be sworn to by the licensee, if the licensee is an individual, or by a partner, officer, or manager in its behalf if the licensee is a partnership, corporation, or unincorporated association. The information contained in the financial statement shall be confidential and not a public record, but is admissible in evidence at any hearing held, or in any action instituted in a court of competent jurisdiction, pursuant to the provisions of this chapter: PROVIDED, That this section shall not apply to those persons holding a valid license issued pursuant to this chapter on July 16, 1973.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20519[2011 c 336 § 519]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c20.pdf?cite=1973%201st%20ex.s.%20c%2020%20§%209[1973 1st ex.s. c 20 § 9]; ]

== 19.16.250 - Prohibited practices.
No licensee or employee of a licensee shall:

. Directly or indirectly aid or abet any unlicensed person to engage in business as a collection agency in this state or receive compensation from such unlicensed person: PROVIDED, That nothing in this chapter shall prevent a licensee from accepting, as forwardee, claims for collection from a collection agency or attorney whose place of business is outside the state.

. Collect or attempt to collect a claim by the use of any means contrary to the postal laws and regulations of the United States postal department.

. Publish or post or cause to be published or posted, any list of debtors commonly known as "bad debt lists" or threaten to do so. For purposes of this chapter, a "bad debt list" means any list of natural persons alleged to fail to honor their lawful debts. However, nothing herein shall be construed to prohibit a licensee from communicating to its customers or clients by means of a coded list, the existence of a check dishonored because of insufficient funds, not sufficient funds or closed account by the financial institution servicing the debtor's checking account: PROVIDED, That the debtor's identity is not readily apparent: PROVIDED FURTHER, That the licensee complies with the requirements of subsection (10)(e) of this section.

. Have in his or her possession or make use of any badge, use a uniform of any law enforcement agency or any simulation thereof, or make any statements which might be construed as indicating an official connection with any federal, state, county, or city law enforcement agency, or any other governmental agency, while engaged in collection agency business.

. Perform any act or acts, either directly or indirectly, constituting the unauthorized practice of law.

. Advertise for sale or threaten to advertise for sale any claim as a means of endeavoring to enforce payment thereof or agreeing to do so for the purpose of soliciting claims, except where the licensee has acquired claims as an assignee for the benefit of creditors or where the licensee is acting under court order.

. Use any name while engaged in the making of a demand for any claim other than the name set forth on his or her or its current license issued hereunder.

. Give or send to any debtor or cause to be given or sent to any debtor, any notice, letter, message, or form, other than through proper legal action, process, or proceedings, which represents or implies that a claim exists unless it shall indicate in clear and legible type:

.. The name of the licensee and the city, street, and number at which he or she is licensed to do business;

.. The name of the original creditor to whom the debtor owed the claim if such name is known to the licensee or employee: PROVIDED, That upon written request of the debtor, the licensee shall provide this name to the debtor or cease efforts to collect on the debt until this information is provided;

.. If the notice, letter, message, or form is the first notice to the debtor or if the licensee is attempting to collect a different amount than indicated in his or her or its first notice to the debtor, an itemization of the claim asserted must be made including:

... Amount owing on the original obligation at the time it was received by the licensee for collection or by assignment;

... Interest or service charge, collection costs, or late payment charges, if any, added to the original obligation by the original creditor, customer or assignor before it was received by the licensee for collection, if such information is known by the licensee or employee: PROVIDED, That upon written request of the debtor, the licensee shall make a reasonable effort to obtain information on such items and provide this information to the debtor;

... Interest or service charge, if any, added by the licensee or customer or assignor after the obligation was received by the licensee for collection;

... Collection costs, if any, that the licensee is attempting to collect;

.. Attorneys' fees, if any, that the licensee is attempting to collect on his or her or its behalf or on the behalf of a customer or assignor; and

.. Any other charge or fee that the licensee is attempting to collect on his or her or its own behalf or on the behalf of a customer or assignor;

.. If the notice, letter, message, or form concerns a judgment obtained against the debtor, no itemization of the amounts contained in the judgment is required, except postjudgment interest, if claimed, and the current account balance;

.. If the notice, letter, message, or form is the first notice to the debtor, an itemization of the claim asserted must be made including the following information:

... The original account number or redacted original account number assigned to the debt, if known to the licensee or employee: PROVIDED, That upon written request of the debtor, the licensee must make a reasonable effort to obtain this information or cease efforts to collect on the debt until this information is provided; and

... The date of the last payment to the creditor on the subject debt by the debtor, if known to the licensee or employee: PROVIDED, That upon written request of the debtor, the licensee must make a reasonable effort to obtain this information or cease efforts to collect on the debt until this information is provided.

. Communicate in writing with a debtor concerning a claim through a proper legal action, process, or proceeding, where such communication is the first written communication with the debtor, without providing the information set forth in subsection (8)(c) of this section in the written communication.

. Communicate or threaten to communicate, the existence of a claim to a person other than one who might be reasonably expected to be liable on the claim in any manner other than through proper legal action, process, or proceedings except under the following conditions:

.. Except as provided in subsection (28)(c) of this section, a licensee or employee of a licensee may inform a credit reporting bureau of the existence of a claim. If the licensee or employee of a licensee reports a claim to a credit reporting bureau, the licensee shall, upon receipt of written notice from the debtor that any part of the claim is disputed, notify the credit reporting bureau of the dispute by written or electronic means and create a record of the fact of the notification and when the notification was provided;

.. A licensee or employee in collecting or attempting to collect a claim may communicate the existence of a claim to a debtor's employer if the claim has been reduced to a judgment;

.. A licensee or employee in collecting or attempting to collect a claim that has not been reduced to judgment, may communicate the existence of a claim to a debtor's employer if:

... The licensee or employee has notified or attempted to notify the debtor in writing at his or her last known address or place of employment concerning the claim and the debtor after a reasonable time has failed to pay the claim or has failed to agree to make payments on the claim in a manner acceptable to the licensee, and

... The debtor has not in writing to the licensee disputed any part of the claim: PROVIDED, That the licensee or employee may only communicate the existence of a claim which has not been reduced to judgment to the debtor's employer once unless the debtor's employer has agreed to additional communications.

.. A licensee may for the purpose of locating the debtor or locating assets of the debtor communicate the existence of a claim to any person who might reasonably be expected to have knowledge of the whereabouts of a debtor or the location of assets of the debtor if the claim is reduced to judgment, or if not reduced to judgment, when:

... The licensee or employee has notified or attempted to notify the debtor in writing at his or her last known address or last known place of employment concerning the claim and the debtor after a reasonable time has failed to pay the claim or has failed to agree to make payments on the claim in a manner acceptable to the licensee, and

... The debtor has not in writing disputed any part of the claim.

.. A licensee may communicate the existence of a claim to its customers or clients if the claim is reduced to judgment, or if not reduced to judgment, when:

... The licensee has notified or attempted to notify the debtor in writing at his or her last known address or last known place of employment concerning the claim and the debtor after a reasonable time has failed to pay the claim or has failed to agree to make payments on the claim in a manner acceptable to the licensee, and

... The debtor has not in writing disputed any part of the claim.

. Threaten the debtor with impairment of his or her credit rating if a claim is not paid: PROVIDED, That advising a debtor that the licensee has reported or intends to report a claim to a credit reporting agency is not considered a threat if the licensee actually has reported or intends to report the claim to a credit reporting agency.

. Communicate with the debtor after notification in writing from an attorney representing such debtor that all further communications relative to a claim should be addressed to the attorney: PROVIDED, That if a licensee requests in writing information from an attorney regarding such claim and the attorney does not respond within a reasonable time, the licensee may communicate directly with the debtor until he or she or it again receives notification in writing that an attorney is representing the debtor.

. Communicate with a debtor or anyone else in such a manner as to harass, intimidate, threaten, or embarrass a debtor, including but not limited to communication at an unreasonable hour, with unreasonable frequency, by threats of force or violence, by threats of criminal prosecution, and by use of offensive language. A communication shall be presumed to have been made for the purposes of harassment if:

.. It is made with a debtor or spouse in any form, manner, or place, more than three times in a single week, unless the licensee is responding to a communication from the debtor or spouse;

.. It is made with a debtor at his or her place of employment more than one time in a single week, unless the licensee is responding to a communication from the debtor;

.. It is made with the debtor or spouse at his or her place of residence between the hours of 9:00 p.m. and 7:30 a.m. A call to a telephone is presumed to be received in the local time zone to which the area code of the number called is assigned for landline numbers, unless the licensee reasonably believes the telephone is located in a different time zone. If the area code is not assigned to landlines in any specific geographic area, such as with toll-free telephone numbers, a call to a telephone is presumed to be received in the local time zone of the debtor's last known place of residence, unless the licensee reasonably believes the telephone is located in a different time zone.

. Communicate with the debtor through use of forms or instruments that simulate the form or appearance of judicial process, the form or appearance of government documents, or the simulation of a form or appearance of a telegraphic or emergency message.

. Communicate with the debtor and represent or imply that the existing obligation of the debtor may be or has been increased by the addition of attorney fees, investigation fees, service fees, or any other fees or charges when in fact such fees or charges may not legally be added to the existing obligation of such debtor.

. Threaten to take any action against the debtor which the licensee cannot legally take at the time the threat is made.

. Send any telegram or make any telephone calls to a debtor or concerning a debt or for the purpose of demanding payment of a claim or seeking information about a debtor, for which the charges are payable by the addressee or by the person to whom the call is made: PROVIDED, That:

.. This subsection does not prohibit a licensee from attempting to communicate by way of a cellular telephone or other wireless device: PROVIDED, That a licensee cannot cause charges to be incurred to the recipient of the attempted communication more than three times in any calendar week when the licensee knows or reasonably should know that the number belongs to a cellular telephone or other wireless device, unless the licensee is responding to a communication from the debtor or the person to whom the call is made.

.. The licensee is not in violation of (a) of this subsection if the licensee at least monthly updates its records with information provided by a commercial provider of cellular telephone lists that the licensee in good faith believes provides reasonably current and comprehensive data identifying cellular telephone numbers, calls a number not appearing in the most recent list provided by the commercial provider, and does not otherwise know or reasonably should know that the number belongs to a cellular telephone.

.. This subsection may not be construed to increase the number of communications permitted pursuant to subsection (13)(a) of this section.

. Call, or send a text message or other electronic communication to, a cellular telephone or other wireless device more than twice in any day when the licensee knows or reasonably should know that the number belongs to a cellular telephone or other wireless device, unless the licensee is responding to a communication from the debtor or the person to whom the call, text message, or other electronic communication is made. The licensee is not in violation of this subsection if the licensee at least monthly updates its records with information provided by a commercial provider of cellular telephone lists that the licensee in good faith believes provides reasonably current and comprehensive data identifying cellular telephone numbers, calls a number not appearing in the most recent list provided by the commercial provider, and does not otherwise know or reasonably should know that the number belongs to a cellular telephone. Nothing in this subsection may be construed to increase the number of communications permitted pursuant to subsection (13)(a) of this section.

. Intentionally block its telephone number from displaying on a debtor's telephone.

. In any manner convey the impression that the licensee is vouched for, bonded to or by, or is an instrumentality of the state of Washington or any agency or department thereof.

. Collect or attempt to collect in addition to the principal amount of a claim any sum other than allowable interest, collection costs or handling fees expressly authorized by statute, and, in the case of suit, attorney's fees and taxable court costs. A licensee may collect or attempt to collect collection costs and fees, including contingent collection fees, as authorized by a written agreement or contract, between the licensee's client and the debtor, in the collection of a commercial claim. The amount charged to the debtor for collection services shall not exceed thirty-five percent of the commercial claim.

. Procure from a debtor or collect or attempt to collect on any written note, contract, stipulation, promise or acknowledgment under which a debtor may be required to pay any sum other than principal, allowable interest, except as noted in subsection (21) of this section, and, in the case of suit, attorney's fees and taxable court costs.

. Bring an action or initiate an arbitration proceeding on a claim when the licensee knows, or reasonably should know, that such suit or arbitration is barred by the applicable statute of limitations.

. Upon notification by a debtor that the debtor disputes all debts arising from a series of dishonored checks, automated clearinghouse transactions on a demand deposit account, or other preprinted written instruments, initiate oral contact with a debtor more than one time in an attempt to collect from the debtor debts arising from the identified series of dishonored checks, automated clearinghouse transactions on a demand deposit account, or other preprinted written instruments when: (a) Within the previous one hundred eighty days, in response to the licensee's attempt to collect the initial debt assigned to the licensee and arising from the identified series of dishonored checks, automated clearinghouse transactions on a demand deposit account, or other preprinted written instruments, the debtor in writing notified the licensee that the debtor's checkbook or other series of preprinted written instruments was stolen or fraudulently created; (b) the licensee has received from the debtor a certified copy of a police report referencing the theft or fraudulent creation of the checkbook, automated clearinghouse transactions on a demand deposit account, or series of preprinted written instruments; (c) in the written notification to the licensee or in the police report, the debtor identified the financial institution where the account was maintained, the account number, the magnetic ink character recognition number, the full bank routing and transit number, and the check numbers of the stolen checks, automated clearinghouse transactions on a demand deposit account, or other preprinted written instruments, which check numbers included the number of the check that is the subject of the licensee's collection efforts; (d) the debtor provides, or within the previous one hundred eighty days provided, to the licensee a legible copy of a government-issued photo identification, which contains the debtor's signature and which was issued prior to the date of the theft or fraud identified in the police report; and (e) the debtor advised the licensee that the subject debt is disputed because the identified check, automated clearinghouse transaction on a demand deposit account, or other preprinted written instrument underlying the debt is a stolen or fraudulently created check or instrument.

The licensee is not in violation of this subsection if the licensee initiates oral contact with the debtor more than one time in an attempt to collect debts arising from the identified series of dishonored checks, automated clearinghouse transactions on a demand deposit account, or other preprinted written instruments when: (i) The licensee acted in good faith and relied on their established practices and procedures for batching, recording, or packeting debtor accounts, and the licensee inadvertently initiates oral contact with the debtor in an attempt to collect debts in the identified series subsequent to the initial debt assigned to the licensee; (ii) the licensee is following up on collection of a debt assigned to the licensee, and the debtor has previously requested more information from the licensee regarding the subject debt; (iii) the debtor has notified the licensee that the debtor disputes only some, but not all the debts arising from the identified series of dishonored checks, automated clearinghouse transactions on a demand deposit account, or other preprinted written instruments, in which case the licensee shall be allowed to initiate oral contact with the debtor one time for each debt arising from the series of identified checks, automated clearinghouse transactions on a demand deposit account, or written instruments and initiate additional oral contact for those debts that the debtor acknowledges do not arise from stolen or fraudulently created checks or written instruments; (iv) the oral contact is in the context of a judicial, administrative, arbitration, mediation, or similar proceeding; or (v) the oral contact is made for the purpose of investigating, confirming, or authenticating the information received from the debtor, to provide additional information to the debtor, or to request additional information from the debtor needed by the licensee to accurately record the debtor's information in the licensee's records.

. Bring an action or initiate an arbitration proceeding on a claim for any amounts related to a transfer of sale of a vehicle when:

.. The licensee has been informed or reasonably should know that the department of licensing transfer of sale form was filed in accordance with RCW 46.12.650 (1) through (3);

.. The licensee has been informed or reasonably should know that the transfer of the vehicle either (i) was not made pursuant to a legal transfer or (ii) was not voluntarily accepted by the person designated as the purchaser/transferee; and

.. Prior to the commencement of the action or arbitration, the licensee has received from the putative transferee a copy of a police report referencing that the transfer of sale of the vehicle either (i) was not made pursuant to a legal transfer or (ii) was not voluntarily accepted by the person designated as the purchaser/transferee.

. Submit an affidavit or other request pursuant to chapter 6.32 RCW asking a superior or district court to transfer a bond posted by a debtor subject to a money judgment to the licensee, when the debtor has appeared as required.

. Serve a debtor with a summons and complaint unless the summons and complaint have been filed with the court and bear the case number assigned by the court.

. If the claim involves medical debt:

.. Fail to include, with the first written notice to the debtor, a statement that informs the debtor of the debtor's right to request the original account number or redacted original account number assigned to the debt, the date of the last payment, and an itemized statement as provided in (b) of this subsection (28);

.. [Empty]
... Fail to provide to the debtor, upon written or oral request by the debtor for more information than is contained in a general balance due letter, an itemized statement free of charge. Unless and until the licensee provides the itemized statement, the licensee must cease all collection efforts. The itemized statement must include:

(A) The name and address of the medical creditor;

(B) The date, dates, or date range of service;

(C) The health care services provided to the patient as indicated by the health care provider in a statement provided to the licensee;

(D) The amount of principal for any medical debt or debts incurred;

(E) Any adjustment to the bill, such as negotiated insurance rates or other discounts;

(F) The amount of any payments received, whether from the patient or any other party;

(G) Any interest or fees; and

(H) Whether the patient was found eligible for charity care or other reductions and, if so, the amount due after all charity care and other reductions have been applied to the itemized statement;

... In the event the debtor has entered into a voluntary payment agreement, the debtor shall give notice if he or she wants the payment plan discontinued. If no notice is given, the payment arrangement may continue.

... Properly executed postjudgment writs, including writs of garnishment and execution, are not required to be ceased and second or subsequent requests for information already provided do not require the cessation of collection efforts;

.. Report adverse information to consumer credit reporting agencies or credit bureaus until at least one hundred eighty days after the original obligation was received by the licensee for collection or by assignment.

. If the claim involves hospital debt:

.. Fail to include, with the first written notice to the debtor, a notice that the debtor may be eligible for charity care from the hospital, together with the contact information for the hospital;

.. Collect or attempt to collect a claim related to hospital debt during the pendency of an application for charity care sponsorship or an appeal from a final determination of charity care sponsorship status. However, this prohibition is only applicable if the licensee has received notice of the pendency of the application or appeal.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1531-S.SL.pdf?cite=2019%20c%20227%20§%204[2019 c 227 § 4]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1066.SL.pdf?cite=2019%20c%20201%20§%202[2019 c 201 § 2]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2274-S.SL.pdf?cite=2016%20c%2086%20§%204[2016 c 86 § 4]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1822-S.SL.pdf?cite=2013%20c%20148%20§%202[2013 c 148 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5956.SL.pdf?cite=2011%201st%20sp.s.%20c%2029%20§%202[2011 1st sp.s. c 29 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1864-S.SL.pdf?cite=2011%20c%20162%20§%201[2011 c 162 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5574-S.SL.pdf?cite=2011%20c%2057%20§%201[2011 c 57 § 1]; prior:  2001 c 217 § 5; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5331.SL.pdf?cite=2001%20c%2047%20§%202[2001 c 47 § 2]; 2001 c 217 § 4; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c107.pdf?cite=1983%20c%20107%20§%201[1983 c 107 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c254.pdf?cite=1981%20c%20254%20§%205[1981 c 254 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2016[1971 ex.s. c 253 § 16]; ]

== 19.16.260 - Licensing prerequisite to suit—Debt buyer—Prohibited acts.
. [Empty]
.. No collection agency or out-of-state collection agency may bring or maintain an action in any court of this state involving the collection of its own claim or a claim of any third party without alleging and proving that he, she, or it is duly licensed under this chapter and has satisfied the bonding requirements hereof, if applicable: PROVIDED, That in any case where judgment is to be entered by default, it shall not be necessary for the collection agency or out-of-state collection agency to prove such matters.

.. A copy of the current collection agency license or out-of-state collection agency license, certified by the director to be a true and correct copy of the original, shall be prima facie evidence of the licensing and bonding of such collection agency or out-of-state collection agency as required by this chapter.

. No debt buyer may:

.. Bring any legal action against a debtor without attaching to the complaint a copy of the contract or other writing evidencing the original debt that contains the signature of the debtor, or:

... If a claim is based on a credit card debt for which a signed writing evidencing the original debt does not exist, a copy of the most recent monthly statement recording a purchase transaction, payment, or other extension of credit and, if the claim is based on a breach of contract, a copy of the terms and conditions in place at the time of the most recent monthly statement recording a purchase transaction, payment, or extension of credit must also be attached; or

... If a claim is based on an electronic transaction for which a signed writing evidencing the original debt never existed, a copy of the records created during the transaction evidencing the debtor's agreement to the debt and recording the date and terms of the transaction and information provided by the debtor during the transaction.

.. Request a default judgment against a debtor in any legal action without providing to the court evidence that satisfies the requirements of rule 803(a)(6) of the rules of evidence and RCW 5.45.020 or is otherwise authorized by law or rule that establishes the amount and nature of the debt, including the documents required by (a) of this subsection, and:

... The original account number at charge-off;

... The original creditor at charge-off;

... The amount due at charge-off or, if the balance has not been charged off, an itemization of the amount claimed to be owed, including the principal, interest, fees, and other charges or reductions from payment made or other credits;

... An itemization of post charge-off additions, if any;

.. The date of the last payment, if applicable, or the date of the last transaction;

.. If the account is not a revolving credit account, the date the debt was incurred; and

.. A copy of the assignment or other writing establishing that the debt buyer is the owner of the debt. If the debt was assigned more than once, each assignment or other writing evidencing transfer of ownership must be attached to establish an unbroken chain of ownership, beginning with the original creditor to the first debt buyer and each subsequent sale.

.. Bring any legal action against a debtor without providing a disclosure in the complaint, in no smaller than ten point type, stating each of the following:

... That the action is being brought by, or for the benefit of, a person or entity that is engaged in the business of purchasing delinquent or charged off claims for collection purposes;

... The date the claim or obligation was purchased;

... The identity of the person or entity from whom or which the claim or obligation was purchased;

... That the plaintiff may have purchased this claim or obligation for less than the value stated in the complaint;

.. If the claim or obligation was at any time sold without any representation or warranty of accuracy, a statement to that effect; and

.. That the action is being commenced within, and is not barred by, an applicable statute of limitations.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2476-S.SL.pdf?cite=2020%20c%2030%20§%202[2020 c 30 § 2]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1822-S.SL.pdf?cite=2013%20c%20148%20§%203[2013 c 148 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20521[2011 c 336 § 521]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6093-S.SL.pdf?cite=1994%20c%20195%20§%208[1994 c 195 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2017[1971 ex.s. c 253 § 17]; ]

== 19.16.270 - Presumption of validity of assignment.
In any action brought by licensee to collect the claim of his, her, or its customer, the assignment of the claim to licensee by his, her, or its customer shall be conclusively presumed valid, if the assignment is filed in court with the complaint, unless objection is made thereto by the debtor in a written answer or in writing five days or more prior to trial.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20522[2011 c 336 § 522]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2018[1971 ex.s. c 253 § 18]; ]

== 19.16.280 - Board created—Composition of board—Qualification of members.
There is hereby created a board to be known and designated as the "Washington state collection agency board." The board shall consist of five members, one of whom shall be the director and the other four shall be appointed by the governor. The director may delegate his or her duties as a board member to a designee from his or her department. The director or his or her designee shall be the executive officer of the board and its chair.

At least two but no more than two members of the board shall be licensees hereunder. Each of the licensee members of the board shall be actively engaged in the collection agency business at the time of his or her appointment and must continue to be so engaged and continue to be licensed under this chapter during the term of his or her appointment or he or she will be deemed to have resigned his or her position: PROVIDED, That no individual may be a licensee member of the board unless he or she has been actively engaged as either an owner or executive employee or a combination of both of a collection agency business in this state for a period of not less than five years immediately prior to his or her appointment.

No board member shall be employed by or have any interest in, directly or indirectly, as owner, partner, officer, director, agent, stockholder, or attorney, any collection agency in which any other board member is employed by or has such an interest.

No member of the board other than the director or his or her designee shall hold any other elective or appointive state or federal office.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20523[2011 c 336 § 523]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2019[1971 ex.s. c 253 § 19]; ]

== 19.16.290 - Board—Initial members—Terms—Oath—Removal.
The initial members of the board shall be named by the governor within thirty days after January 1, 1972. At the first meeting of the board, the members appointed by the governor shall determine by lot the period of time from January 1, 1972, that each of them shall serve, one for one year; one for two years; one for three years; and one for four years. In the event of a vacancy on the board, the governor shall appoint a successor for the unexpired term.

Each member appointed by the governor shall qualify by taking the usual oath of a state officer, which shall be filed with the secretary of state, and each member shall hold office for the term of his or her appointment and until his or her successor is appointed and qualified.

Any member of the board other than the director or his or her designee may be removed by the governor for neglect of duty, misconduct, malfeasance, or misfeasance in office, after being given a written statement of the charges against him or her and sufficient opportunity to be heard thereon.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20524[2011 c 336 § 524]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2020[1971 ex.s. c 253 § 20]; ]

== 19.16.300 - Board meetings—Quorum—Effect of vacancy.
The board shall meet as soon as practicable after the governor has appointed the initial members of the board. The board shall meet at least once a year and at such other times as may be necessary for the transaction of its business.

The time and place of the initial meeting of the board and the annual meetings shall be at a time and place fixed by the director. Other meetings of the board shall be held upon written request of the director at a time and place designated by him or her, or upon the written request of any two members of the board at a time and place designated by them.

A majority of the board shall constitute a quorum.

A vacancy in the board membership shall not impair the right of the remaining members of the board to exercise any power or to perform any duty of the board, so long as the power is exercised or the duty performed by a quorum of the board.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20525[2011 c 336 § 525]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2021[1971 ex.s. c 253 § 21]; ]

== 19.16.310 - Board—Compensation—Reimbursement of travel expenses.
Each member of the board appointed by the governor shall be compensated in accordance with RCW 43.03.240 and in addition thereto shall be reimbursed for travel expenses incurred while on official business of the board and in attending meetings thereof, in accordance with the provisions of RCW 43.03.050 and 43.03.060.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c287.pdf?cite=1984%20c%20287%20§%2054[1984 c 287 § 54]; 1975-'76 2nd ex.s. c 34 § 58; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2022[1971 ex.s. c 253 § 22]; ]

== 19.16.320 - Board—Territorial scope of operations.
The board may meet, function and exercise its powers and perform its duties at any place within the state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2023[1971 ex.s. c 253 § 23]; ]

== 19.16.330 - Board—Immunity from suit.
Members of the board shall be immune from suit in any civil action based upon an official act performed in good faith as members of such board.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2024[1971 ex.s. c 253 § 24]; ]

== 19.16.340 - Board—Records.
All records of the board shall be kept in the office of the director. Copies of all records and papers of the board, certified to be true copies by the director, shall be received in evidence in all cases with like effect as the originals. All actions by the board which require publication, or any writing shall be over the signature of the director or his or her designee.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20526[2011 c 336 § 526]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2025[1971 ex.s. c 253 § 25]; ]

== 19.16.351 - Additional powers and duties of board.
The board, in addition to any other powers and duties granted under this chapter and RCW 18.235.030:

. May adopt, amend, and rescind rules for its own organization and procedure and other rules as it may deem necessary in order to perform its duties under this chapter.

. May inquire into the needs of the collection agency business, the needs of the director, and the matter of the policy of the director in administering this chapter, and make such recommendations with respect thereto as, after consideration, may be deemed important and necessary for the welfare of the state, the welfare of the public, and the welfare and progress of the collection agency business.

. Upon request of the director, confer and advise in matters relating to the administering of this chapter.

. May consider and make appropriate recommendations to the director in all matters referred to the board.

. Upon request of the director, confer with and advise the director in the preparation of any rules to be adopted, amended, or repealed.

. May assist the director in the collection of such information and data as the director may deem necessary to the proper administration of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20267[2002 c 86 § 267]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c194.pdf?cite=1977%20ex.s.%20c%20194%20§%202[1977 ex.s. c 194 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c20.pdf?cite=1973%201st%20ex.s.%20c%2020%20§%208[1973 1st ex.s. c 20 § 8]; ]

== 19.16.390 - Personal service of process outside state.
Personal service of any process in an action under this chapter may be made upon any person outside the state if such person has engaged in conduct in violation of this chapter which has had the impact in this state which this chapter reprehends. Such persons shall be deemed to have thereby submitted themselves to the jurisdiction of the courts of this state within the meaning of RCW 4.28.180 and 4.28.185. A holder of an out-of-state collection agency license is deemed to have appointed the director or the director's designee to be the licensee's true and lawful agent upon whom may be served any legal process against that licensee arising or growing out of any violation of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6093-S.SL.pdf?cite=1994%20c%20195%20§%209[1994 c 195 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2030[1971 ex.s. c 253 § 30]; ]

== 19.16.410 - Rules, orders, decisions, etc.
The board may adopt rules, make specific decisions, orders, and rulings, including therein demands and findings, and take other necessary action for the implementation and enforcement of the board's duties under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1574-S.SL.pdf?cite=2007%20c%20256%20§%204[2007 c 256 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2032[1971 ex.s. c 253 § 32]; ]

== 19.16.420 - Copy of this chapter, rules and regulations available to licensee.
On or about the first day of February in each year, the director shall cause to be made available at reasonable expense to a licensee a copy of this chapter, a copy of the current rules and regulations of the director, and board, and such other materials as the director or board prescribe.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2033[1971 ex.s. c 253 § 33]; ]

== 19.16.430 - Violations—Operating agency without a license—Penalty—Return of fees or compensation.
. Any person who knowingly operates as a collection agency or out-of-state collection agency without a license or knowingly aids and abets such violation is punishable by a fine not exceeding five hundred dollars or by imprisonment not exceeding one year or both.

. Any person who operates as a collection agency or out-of-state collection agency in the state of Washington without a valid license issued pursuant to this chapter shall not charge or receive any fee or compensation on any moneys received or collected while operating without a license or on any moneys received or collected while operating with a license but received or collected as a result of his, her, or its acts as a collection agency or out-of-state collection agency while not licensed hereunder. All such moneys collected or received shall be forthwith returned to the owners of the accounts on which the moneys were paid.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20527[2011 c 336 § 527]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6093-S.SL.pdf?cite=1994%20c%20195%20§%2010[1994 c 195 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c20.pdf?cite=1973%201st%20ex.s.%20c%2020%20§%206[1973 1st ex.s. c 20 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2034[1971 ex.s. c 253 § 34]; ]

== 19.16.440 - Collection agency—Prohibited acts—Unfair and deceptive trade practices under chapter  19.86 RCW.
The operation of a collection agency or out-of-state collection agency without a license as prohibited by RCW 19.16.110 and the commission by a licensee or an employee of a licensee of an act or practice prohibited by RCW 19.16.250 or 19.16.260 are declared to be unfair acts or practices or unfair methods of competition in the conduct of trade or commerce for the purpose of the application of the consumer protection act found in chapter 19.86 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2476-S.SL.pdf?cite=2020%20c%2030%20§%203[2020 c 30 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6093-S.SL.pdf?cite=1994%20c%20195%20§%2011[1994 c 195 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c20.pdf?cite=1973%201st%20ex.s.%20c%2020%20§%207[1973 1st ex.s. c 20 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2035[1971 ex.s. c 253 § 35]; ]

== 19.16.450 - Violation of RCW  19.16.250 or  19.16.260—Additional penalty.
If an act or practice in violation of RCW 19.16.250 or 19.16.260 is committed by a licensee or an employee of a licensee in the collection of a claim, neither the licensee, the customer of the licensee, nor any other person who may thereafter legally seek to collect on such claim shall ever be allowed to recover any interest, service charge, attorneys' fees, collection costs, delinquency charge, or any other fees or charges otherwise legally chargeable to the debtor on such claim: PROVIDED, That any person asserting the claim may nevertheless recover from the debtor the amount of the original claim or obligation.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2476-S.SL.pdf?cite=2020%20c%2030%20§%204[2020 c 30 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2036[1971 ex.s. c 253 § 36]; ]

== 19.16.460 - Violations may be enjoined.
Notwithstanding any other actions which may be brought under the laws of this state, the attorney general or the prosecuting attorney of any county within the state may bring an action in the name of the state against any person to restrain and prevent any violation of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2037[1971 ex.s. c 253 § 37]; ]

== 19.16.470 - Violations—Assurance of discontinuance—Effect.
The attorney general may accept an assurance of discontinuance of any act or practice deemed in violation of this chapter from any person engaging in or who has engaged in such act or practice. Any such assurance shall be in writing and be filed with and subject to the approval of the superior court of the county in which the alleged violator resides or has his, her, or its principal place of business, or in the alternative, in Thurston county.

Such assurance of discontinuance shall not be considered an admission of a violation for any purpose; however, proof of failure to perform the terms of any such assurance shall constitute prima facie proof of a violation of this chapter for the purpose of securing an injunction as provided for in RCW 19.16.460: PROVIDED, That after commencement of any action by a prosecuting attorney, as provided therein, the attorney general may not accept an assurance of discontinuance without the consent of said prosecuting attorney.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20528[2011 c 336 § 528]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2038[1971 ex.s. c 253 § 38]; ]

== 19.16.480 - Violation of injunction—Civil penalty.
Any person who violates any injunction issued pursuant to this chapter shall forfeit and pay a civil penalty of not more than twenty-five thousand dollars. For the purpose of this section the superior court issuing any injunction shall retain jurisdiction, and the cause shall be continued, and in such cases the attorney general acting in the name of the state may petition for the recovery of civil penalties.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2039[1971 ex.s. c 253 § 39]; ]

== 19.16.500 - Public bodies may retain collection agencies to collect public debts—Fees.
. [Empty]
.. Agencies, departments, taxing districts, political subdivisions of the state, counties, and cities may retain, by written contract, collection agencies licensed under this chapter for the purpose of collecting public debts owed by any person, including any restitution that is being collected on behalf of a crime victim.

.. Any governmental entity as described in (a) of this subsection using a collection agency may add a reasonable fee, payable by the debtor, to the outstanding debt for the collection agency fee incurred or to be incurred. The amount to be paid for collection services shall be left to the agreement of the governmental entity and its collection agency or agencies, but a contingent fee of up to fifty percent of the first one hundred thousand dollars of the unpaid debt per account and up to thirty-five percent of the unpaid debt over one hundred thousand dollars per account is reasonable, and a minimum fee of the full amount of the debt up to one hundred dollars per account is reasonable. Any fee agreement entered into by a governmental entity is presumptively reasonable.

. No debt may be assigned to a collection agency unless (a) there has been an attempt to advise the debtor (i) of the existence of the debt and (ii) that the debt may be assigned to a collection agency for collection if the debt is not paid, and (b) at least thirty days have elapsed from the time notice was attempted.

. Collection agencies assigned debts under this section shall have only those remedies and powers which would be available to them as assignees of private creditors.

. For purposes of this section, the term debt shall include fines and other debts, including the fee allowed under subsection (1)(b) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5574-S.SL.pdf?cite=2011%20c%2057%20§%202[2011 c 57 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5827-S.SL.pdf?cite=1997%20c%20387%20§%201[1997 c 387 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c65.pdf?cite=1982%20c%2065%20§%201[1982 c 65 § 1]; ]

== 19.16.510 - Uniform regulation of business and professions act.
The uniform regulation of business and professions act, chapter 18.235 RCW, governs unlicensed practice, the issuance and denial of licenses, and the discipline of licensees under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20268[2002 c 86 § 268]; ]

== 19.16.900 - Provisions cumulative—Violation of RCW  19.16.250 deemed civil.
The provisions of this chapter shall be cumulative and nonexclusive and shall not affect any other remedy available at law: PROVIDED, That the violation of RCW 19.16.250 shall be construed as exclusively civil and not penal in nature.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2040[1971 ex.s. c 253 § 40]; ]

== 19.16.920 - Provisions exclusive—Authority of political subdivisions to levy business and occupation taxes not affected.
. The provisions of this chapter relating to the licensing and regulation of collection agencies and out-of-state collection agencies shall be exclusive and no county, city, or other political subdivision of this state shall enact any laws or rules and regulations licensing or regulating collection agencies.

. This section shall not be construed to prevent a political subdivision of this state from levying a business and occupation tax upon collection agencies or out-of-state collection agencies maintaining an office within that political subdivision if a business and occupation tax is levied by it upon other types of businesses within its boundaries.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6093-S.SL.pdf?cite=1994%20c%20195%20§%2012[1994 c 195 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2042[1971 ex.s. c 253 § 42]; ]

== 19.16.930 - Effective date—1971 ex.s. c 253.
This act shall become effective January 1, 1972.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2044[1971 ex.s. c 253 § 44]; ]

== 19.16.940 - Short title.
This chapter shall be known and may be cited as the "Collection Agency Act".

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2045[1971 ex.s. c 253 § 45]; ]

== 19.16.950 - Section headings.
Section headings used in this chapter shall not constitute any part of the law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c253.pdf?cite=1971%20ex.s.%20c%20253%20§%2046[1971 ex.s. c 253 § 46]; ]

== 19.16.960 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%2052[2009 c 521 § 52]; ]

