= 19.80 - Trade names.
:toc:

== 19.80.001 - Purposes.
The purposes of this chapter are: (1) To require each person who is conducting business in the state of Washington under a trade name to disclose the true and real name of each person conducting that business, and (2) to provide a central registry of businesses operating under a trade name in the state of Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c130.pdf?cite=1984%20c%20130%20§%201[1984 c 130 § 1]; ]

== 19.80.005 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Business" means an occupation, profession, or employment engaged in for the purpose of seeking a profit.

. "Department" means the department of revenue.

. "Person" means any individual, partnership, limited liability company, or corporation conducting or having an interest in a business in the state.

. "Trade name" means a word or name, or any combination of a word or name, used by a person to identify the person's business which:

.. Is not, or does not include, the true and real name of all persons conducting the business; or

.. Includes words which suggest additional parties of interest such as "company," "and sons," or "and associates."

. "True and real name" means:

.. The surname of an individual coupled with one or more of the individual's other names, one or more of the individual's initials, or any combination;

.. The designation or appellation by which an individual is best known and called in the business community where that individual transacts business, if this is used as that individual's legal signature;

.. The registered corporate name of a domestic corporation as filed with the secretary of state;

.. The registered corporate name of a foreign corporation authorized to do business within the state of Washington as filed with the secretary of state;

.. The registered partnership name of a domestic limited partnership as filed with the secretary of state;

.. The registered partnership name of a foreign limited partnership as filed with the secretary of state; or

.. The name of a general partnership which includes in its name the true and real names, as defined in (a) through (f) of this subsection, of each general partner as required in RCW 19.80.010.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2017-S.SL.pdf?cite=2011%20c%20298%20§%2013[2011 c 298 § 13]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2576.SL.pdf?cite=2000%20c%20174%20§%201[2000 c 174 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6168-S.SL.pdf?cite=1996%20c%20231%20§%202[1996 c 231 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c130.pdf?cite=1984%20c%20130%20§%202[1984 c 130 § 2]; ]

== 19.80.010 - Registration required.
Each person or persons who carries on, conducts, or transacts business in this state under any trade name must register that trade name with the department as provided in this section.

. Sole proprietorship or general partnership: The registration must set forth the true and real name or names of each person conducting the same, together with the post office address or addresses of each such person and the name of the general partnership, if applicable.

. Foreign or domestic limited partnership: The registration must set forth the limited partnership name as filed with the office of the secretary of state.

. Foreign or domestic limited liability company: The registration must set forth the limited liability company name as filed with the office of the secretary of state.

. Foreign or domestic corporation: The registration must set forth the corporate name as filed with the office of the secretary of state.

. Other business entities: The registration must set forth the entity's name as required by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1568-S.SL.pdf?cite=2013%20c%20144%20§%2032[2013 c 144 § 32]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2017-S.SL.pdf?cite=2011%20c%20298%20§%2014[2011 c 298 § 14]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2576.SL.pdf?cite=2000%20c%20174%20§%202[2000 c 174 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6168-S.SL.pdf?cite=1996%20c%20231%20§%203[1996 c 231 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c130.pdf?cite=1984%20c%20130%20§%203[1984 c 130 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c22.pdf?cite=1979%20ex.s.%20c%2022%20§%201[1979 ex.s. c 22 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c145.pdf?cite=1907%20c%20145%20§%201[1907 c 145 § 1]; RRS § 9976; ]

== 19.80.025 - Changes in registration—Filing notice of change.
. A notice of change must be filed with the department when a change occurs in:

.. The true and real name of a person conducting a business with a trade name registered under this chapter; or

.. Any mailing address set forth on the registration or any subsequently filed notice of change.

. A notice of cancellation must be filed with the department when use of a trade name is discontinued.

. A notice of cancellation, together with a new registration, must be filed before conducting or transacting any business when:

.. An addition, deletion, or any change of person or persons conducting business under the registered trade name occurs; or

.. There is a change in the wording or spelling of the trade name since initial registration or renewal.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2017-S.SL.pdf?cite=2011%20c%20298%20§%2015[2011 c 298 § 15]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2576.SL.pdf?cite=2000%20c%20174%20§%203[2000 c 174 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c130.pdf?cite=1984%20c%20130%20§%205[1984 c 130 § 5]; ]

== 19.80.040 - Failure to file.
No person or persons carrying on, conducting, or transacting business under any trade name shall be entitled to maintain any suit in any of the courts of this state until such person or persons have properly completed the registration as provided for in RCW 19.80.010. Failure to complete this registration shall not impair the validity of any contract or act of such person or persons and shall not prevent such person or persons from defending any suit in any court of this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c130.pdf?cite=1984%20c%20130%20§%207[1984 c 130 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c145.pdf?cite=1907%20c%20145%20§%205[1907 c 145 § 5]; RRS § 9980; ]

== 19.80.045 - Rules—Fees.
The department must adopt rules as necessary to administer this chapter. The rules may include but are not limited to specifying forms and setting fees for trade name registrations, amendments, searches, renewals, and copies of registration documents. Fees may not exceed the actual cost of administering this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2017-S.SL.pdf?cite=2011%20c%20298%20§%2016[2011 c 298 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c130.pdf?cite=1984%20c%20130%20§%206[1984 c 130 § 6]; ]

== 19.80.075 - Collection and deposit of fees.
All fees collected by the department under this chapter must be deposited with the state treasurer and credited to the business license account.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1568-S.SL.pdf?cite=2013%20c%20144%20§%2033[2013 c 144 § 33]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2017-S.SL.pdf?cite=2011%20c%20298%20§%2017[2011 c 298 § 17]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6461-S.SL.pdf?cite=1992%20c%20107%20§%206[1992 c 107 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c130.pdf?cite=1984%20c%20130%20§%209[1984 c 130 § 9]; ]

== 19.80.080 - Renewal and cancellation.
. The department may require the renewal of trade names and establish a process for renewing trade names. Any such renewal process may not require renewals of trade names more often than annually and must allow persons to renew their trade name at the same time they are required to renew their business license.

. The department may cancel a person's trade name upon request of the person the trade name is registered to or when the person's business license account with the department's business licensing service is inactive. The department may also provide for the cancellation of trade names under circumstances as defined by the department by rule, which may include failure to renew a trade name under a renewal process as may be established by the department under the authority of subsection (1) of this section.

. [Empty]
.. The department must make a reasonable effort to notify a person that the department intends to cancel the person's trade name. This notice is not required when a request for cancellation of a trade name is received by the department from the person the trade name was registered to or the person's authorized representative. The department may comply with this subsection either by mailing the notice to the person's last known address on record with the department or by providing the notice electronically instead of by mail. Such electronic notice is not subject to the confidentiality provisions of RCW 19.02.115 and may be sent by email to the person's last known email address on record with the department. However, if the department sends a notice by email and is notified that the email is undeliverable, the department must resend the notice by mail to the person's last known address on record with the department.

.. The department may cancel a trade name unless, within twenty days of sending the notice required under this subsection, the person notifies the department in writing not to cancel the person's trade name and pays any applicable renewal fee.

. The department may remove any canceled trade names from its database of trade names.

. "Business license" and "business licensing service" have the same meaning as in RCW 19.02.020.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1568-S.SL.pdf?cite=2013%20c%20144%20§%2031[2013 c 144 § 31]; ]

