= 19.25 - Reproduced sound recordings.
:toc:

== 19.25.010 - Definitions.
As used in this chapter:

. "Owner" means a person who owns the sounds fixed in a master phonograph record, master disc, master tape, master film, or other recording on which sound is or can be recorded and from which the transferred recorded sounds are directly or indirectly derived.

. "Fixed" means embodied in a recording or other tangible medium of expression, by or under the authority of the author, so that the matter embodied is sufficiently permanent or stable to permit it to be perceived, reproduced, or otherwise communicated for a period of more than transitory duration.

. "Live performance" means a recitation, rendering, or playing of a series of images; musical, spoken or other sounds; or combination of images and sounds.

. "Recording" means a tangible medium on which sounds, images, or both are recorded or otherwise stored, including an original phonograph record, disc, tape, audio or video cassette, wire, film, or other medium now existing or developed later on which sounds, images, or both are or can be recorded or otherwise stored or a copy or reproduction that duplicates in whole or in part the original.

. "Manufacturer" means the entity authorizing the duplication of the recording in question, but shall not include the manufacturer of the cartridge or casing itself.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5030-S.SL.pdf?cite=1991%20c%2038%20§%201[1991 c 38 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c100.pdf?cite=1974%20ex.s.%20c%20100%20§%201[1974 ex.s. c 100 § 1]; ]

== 19.25.020 - Reproduction of sound without consent of owner unlawful—Fine and penalty.
. A person commits an offense if the person:

.. Knowingly reproduces for sale or causes to be transferred any recording with intent to sell it or cause it to be sold or use it or cause it to be used for commercial advantage or private financial gain without the consent of the owner;

.. Transports within this state, for commercial advantage or private financial gain, a recording with the knowledge that the sounds have been reproduced or transferred without the consent of the owner; or

.. Advertises, offers for sale, sells, or rents, or causes the sale, resale, or rental of or possesses for one or more of these purposes any recording that the person knows has been reproduced or transferred without the consent of the owner.

. [Empty]
.. An offense under this section is a class B felony punishable by a fine of not more than two hundred fifty thousand dollars, imprisonment for not more than ten years, or both if:

... The offense involves at least one thousand unauthorized recordings during a one hundred eighty-day period; or

... The defendant has been previously convicted under this section.

.. An offense under this section is a class C felony punishable by a fine of not more than two hundred fifty thousand dollars, imprisonment for not more than five years, or both, if the offense involves more than one hundred but less than one thousand unauthorized recordings during a one hundred eighty-day period.

.. Any other offense under this section is a gross misdemeanor punishable by a fine of not more than twenty-five thousand dollars, imprisonment for up to three hundred sixty-four days, or both.

. This section does not affect the rights and remedies of a party in private litigation.

. This section applies only to recordings that were initially fixed before February 15, 1972.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5168-S.SL.pdf?cite=2011%20c%2096%20§%2017[2011 c 96 § 17]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20143[2003 c 53 § 143]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5030-S.SL.pdf?cite=1991%20c%2038%20§%202[1991 c 38 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c100.pdf?cite=1974%20ex.s.%20c%20100%20§%202[1974 ex.s. c 100 § 2]; ]

== 19.25.030 - Use of recording of live performance without consent of owner unlawful—Fine and penalty.
. A person commits an offense if the person:

.. For commercial advantage or private financial gain advertises, offers for sale, sells, rents, transports, causes the sale, resale, rental, or transportation of or possesses for one or more of these purposes a recording of a live performance with the knowledge that the live performance has been recorded or fixed without the consent of the owner; or

.. With the intent to sell for commercial advantage or private financial gain records or fixes or causes to be recorded or fixed on a recording a live performance with the knowledge that the live performance has been recorded or fixed without the consent of the owner.

. [Empty]
.. An offense under this section is a class B felony punishable by a fine of not more than two hundred fifty thousand dollars, imprisonment for not more than ten years, or both, if:

... The offense involves at least one thousand unauthorized recordings embodying sound or at least one hundred unauthorized audiovisual recordings during a one hundred eighty-day period; or

... The defendant has been previously convicted under this section.

.. An offense under this section is a class C felony punishable by a fine of not more than two hundred fifty thousand dollars, imprisonment for not more than five years, or both, if the offense involves more than one hundred but less than one thousand unauthorized recordings embodying sound or more than ten but less than one hundred unauthorized audiovisual recordings during a one hundred eighty-day period.

.. Any other offense under this section is a gross misdemeanor punishable by a fine of not more than twenty-five thousand dollars, imprisonment for up to three hundred sixty-four days, or both.

. In the absence of a written agreement or law to the contrary, the performer or performers of a live performance are presumed to own the rights to record or fix those sounds.

. For the purposes of this section, a person who is authorized to maintain custody and control over business records that reflect whether or not the owner of the live performance consented to having the live performance recorded or fixed is a competent witness in a proceeding regarding the issue of consent.

. This section does not affect the rights and remedies of a party in private litigation.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5168-S.SL.pdf?cite=2011%20c%2096%20§%2018[2011 c 96 § 18]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20144[2003 c 53 § 144]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5030-S.SL.pdf?cite=1991%20c%2038%20§%203[1991 c 38 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c100.pdf?cite=1974%20ex.s.%20c%20100%20§%203[1974 ex.s. c 100 § 3]; ]

== 19.25.040 - Failure to disclose origin of certain recordings unlawful—Fine and penalty.
. A person is guilty of failure to disclose the origin of a recording when, for commercial advantage or private financial gain, the person knowingly advertises, or offers for sale, resale, or rent, or sells or resells, or rents, leases, or lends, or possesses for any of these purposes, any recording which does not contain the true name and address of the manufacturer in a prominent place on the cover, jacket, or label of the recording.

. [Empty]
.. An offense under this section is a class B felony punishable by a fine of not more than two hundred fifty thousand dollars, imprisonment for not more than ten years, or both, if:

... The offense involves at least one hundred unauthorized recordings during a one hundred eighty-day period; or

... The defendant has been previously convicted under this section.

.. An offense under this section is a class C felony punishable by a fine of not more than two hundred fifty thousand dollars, imprisonment for not more than five years, or both, if the offense involves more than ten but less than one hundred unauthorized recordings during a one hundred eighty-day period.

.. Any other offense under this section is a gross misdemeanor punishable by a fine of not more than twenty-five thousand dollars, imprisonment for up to three hundred sixty-four days, or both.

. This section does not affect the rights and remedies of a party in private litigation.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5168-S.SL.pdf?cite=2011%20c%2096%20§%2019[2011 c 96 § 19]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20145[2003 c 53 § 145]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5030-S.SL.pdf?cite=1991%20c%2038%20§%204[1991 c 38 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c100.pdf?cite=1974%20ex.s.%20c%20100%20§%204[1974 ex.s. c 100 § 4]; ]

== 19.25.050 - Contraband recordings—Disposition, forfeiture, penalty.
. All recordings which have been fixed transferred, or possessed without the consent of the owner in violation of RCW 19.25.020 or 19.25.030, and any recording which does not contain the true name and address of the manufacturer in violation of RCW 19.25.040 shall be deemed to be contraband. The court shall order the seizure, forfeiture, and destruction or other disposition of such contraband.

. The owner or the prosecuting attorney may institute proceedings to forfeit contraband recordings. The provisions of this subsection shall apply to any contraband recording, regardless of lack of knowledge or intent on the part of the possessor, retail seller, manufacturer, or distributor.

. Whenever a person is convicted of a violation under this chapter, the court, in its judgment of conviction, shall, in addition to the penalty therein prescribed, order the forfeiture and destruction or other disposition of all contraband recordings and any and all electronic, mechanical, or other devices for manufacturing, reproducing, packaging, or assembling such recordings, which were used to facilitate any violation of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5030-S.SL.pdf?cite=1991%20c%2038%20§%205[1991 c 38 § 5]; ]

== 19.25.100 - Truth in music advertising.
. The definitions in this subsection apply throughout this section unless the context clearly requires otherwise.

.. "Performing group" means a vocal or instrumental group seeking to use the name of another group that has previously released a commercial sound recording under that name.

.. "Recording group" means a vocal or instrumental group, at least one of whose members has previously released a commercial sound recording under that group's name and in which the member or members have a legal right by virtue of use or operation under the group name without having abandoned the name or affiliation with the group.

.. "Sound recording" means a work that results from the fixation on a material object of a series of musical, spoken, or other sounds regardless of the nature of the material object, such as a disk, tape, or other phonorecord, in which the sounds are embodied.

. A person shall not advertise or conduct a live musical performance or production through the use of a false, deceptive, or misleading affiliation, connection, or association between a performing group and a recording group unless any of the following apply:

.. The performing group is the authorized registrant and owner of a federal service mark for the group registered in the United States patent and trademark office;

.. At least one member of the performing group was previously a member of the recording group and has a legal right by virtue of use or operation under the group name without having abandoned the name or affiliation of the group;

.. The live musical performance or production is identified in all advertising and promotion as a salute or tribute;

.. The advertising does not relate to a live musical performance or production taking place in this state; or

.. The performance or production is expressly authorized by the recording group.

. [Empty]
.. A person who violates this section is subject to a civil penalty not less than five thousand dollars or more than fifteen thousand dollars per violation. An action for a civil penalty may be brought by the attorney general or a county or city prosecutor and is enforceable as a civil judgment.

.. A person who violates this section is subject to the equitable remedies described in chapter 19.86 RCW.

.. Each performance or production declared unlawful under subsection (2) of this section constitutes a separate violation.

.. This section does not preclude prosecution of a violation of this section under any other provision of law.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5284.SL.pdf?cite=2009%20c%20109%20§%201[2009 c 109 § 1]; ]

== 19.25.800 - Chapter not applicable to broadcast by commercial or educational radio or television.
This chapter shall not be applicable to any recording that is used or intended to be used only for broadcast by commercial or educational radio or television stations.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5030-S.SL.pdf?cite=1991%20c%2038%20§%206[1991 c 38 § 6]; ]

== 19.25.810 - Chapter not applicable to certain nonrecorded broadcast use.
This chapter shall not be applicable to any recording that is received in the ordinary course of a broadcast by a commercial or educational radio or television station where no recording is made of the broadcast.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5030-S.SL.pdf?cite=1991%20c%2038%20§%207[1991 c 38 § 7]; ]

== 19.25.820 - Chapter not applicable to defined public record.
This chapter shall not be applicable to any recording defined as a public record of any court, legislative body, or proceedings of any public body, whether or not a fee is charged or collected for copies.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5030-S.SL.pdf?cite=1991%20c%2038%20§%208[1991 c 38 § 8]; ]

