= 19.85 - Regulatory fairness act.
:toc:

== 19.85.011 - Finding.
The legislature finds that administrative rules adopted by state agencies can have a disproportionate impact on the state's small businesses because of the size of those businesses. This disproportionate impact reduces competition, innovation, employment, and new employment opportunities, and threatens the very existence of some small businesses. The legislature therefore enacts the Regulatory Fairness Act with the intent of reducing the disproportionate impact of state administrative rules on small business.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2510-S2.SL.pdf?cite=1994%20c%20249%20§%209[1994 c 249 § 9]; ]

== 19.85.020 - Definitions.
The definitions in this section apply through this chapter unless the context clearly requires otherwise.

. "Industry" means all of the businesses in this state in any one four-digit standard industrial classification as published by the United States department of commerce, or the North American industry classification system as published by the executive office of the president and the office of management and budget. However, if the use of a four-digit standard industrial classification or North American industry classification system would result in the release of data that would violate state confidentiality laws, "industry" means all businesses in a three-digit standard industrial classification or the North American industry classification system.

. "Minor cost" means a cost per business that is less than three-tenths of one percent of annual revenue or income, or one hundred dollars, whichever is greater, or one percent of annual payroll. However, for the rules of the department of social and health services "minor cost" means cost per business that is less than fifty dollars of annual cost per client or other appropriate unit of service.

. "Small business" means any business entity, including a sole proprietorship, corporation, partnership, or other legal entity, that is owned and operated independently from all other businesses, and that has fifty or fewer employees.

. "Small business economic impact statement" means a statement meeting the requirements of RCW 19.85.040 prepared by a state agency pursuant to RCW 19.85.030.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1525.SL.pdf?cite=2007%20c%20239%20§%202[2007 c 239 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5512.SL.pdf?cite=2003%20c%20166%20§%201[2003 c 166 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2510-S2.SL.pdf?cite=1994%20c%20249%20§%2010[1994 c 249 § 10]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5868-S.SL.pdf?cite=1993%20c%20280%20§%2034[1993 c 280 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c374.pdf?cite=1989%20c%20374%20§%201[1989 c 374 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c6.pdf?cite=1982%20c%206%20§%202[1982 c 6 § 2]; ]

== 19.85.025 - Application of chapter—Limited.
. Unless an agency receives a written objection to the expedited repeal of a rule, this chapter does not apply to a rule proposed for expedited repeal pursuant to RCW 34.05.353. If an agency receives a written objection to expedited repeal of the rule, this chapter applies to the rule-making proceeding.

. This chapter does not apply to a rule proposed for expedited adoption under RCW 34.05.353, unless a written objection is timely filed with the agency and the objection is not withdrawn.

. This chapter does not apply to the adoption of a rule described in RCW 34.05.310(4).

. This chapter does not apply to the adoption of a rule if an agency is able to demonstrate that the proposed rule does not affect small businesses.

. An agency is not required to prepare a separate small business economic impact statement under RCW 19.85.040 if it prepared an analysis under RCW 34.05.328 that meets the requirements of a small business economic impact statement, and if the agency reduced the costs imposed by the rule on small business to the extent required by RCW 19.85.030(2). The portion of the analysis that meets the requirements of RCW 19.85.040 shall be filed with the code reviser and provided to any person requesting it in lieu of a separate small business economic impact statement.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1120-S2.SL.pdf?cite=2017%20c%2053%20§%201[2017 c 53 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1032-S2.SL.pdf?cite=1997%20c%20409%20§%20212[1997 c 409 § 212]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1010-S.SL.pdf?cite=1995%20c%20403%20§%20401[1995 c 403 § 401]; ]

== 19.85.030 - Agency rules—Small business economic impact statement—Reduction of costs imposed by rule.
. [Empty]
.. In the adoption of a rule under chapter 34.05 RCW, an agency shall prepare a small business economic impact statement: (i) If the proposed rule will impose more than minor costs on businesses in an industry; or (ii) if requested to do so by a majority vote of the joint administrative rules review committee within forty-five days of receiving the notice of proposed rule making under RCW 34.05.320. However, if the agency has completed the pilot rule process as defined by RCW 34.05.313 before filing the notice of a proposed rule, the agency is not required to prepare a small business economic impact statement.

.. An agency must prepare the small business economic impact statement in accordance with RCW 19.85.040, and file it with the code reviser along with the notice required under RCW 34.05.320. An agency shall file a statement prepared at the request of the joint administrative rules review committee with the code reviser upon its completion before the adoption of the rule. An agency must provide a copy of the small business economic impact statement to any person requesting it.

. Based upon the extent of disproportionate impact on small business identified in the statement prepared under RCW 19.85.040, the agency shall, where legal and feasible in meeting the stated objectives of the statutes upon which the rule is based, reduce the costs imposed by the rule on small businesses. The agency must consider, without limitation, each of the following methods of reducing the impact of the proposed rule on small businesses:

.. Reducing, modifying, or eliminating substantive regulatory requirements;

.. Simplifying, reducing, or eliminating recordkeeping and reporting requirements;

.. Reducing the frequency of inspections;

.. Delaying compliance timetables;

.. Reducing or modifying fine schedules for noncompliance; or

.. Any other mitigation techniques including those suggested by small businesses or small business advocates.

. If a proposed rule affects only small businesses, the proposing agency must consider all mitigation options defined in this chapter.

. In the absence of sufficient data to calculate disproportionate impacts, an agency whose rule imposes more than minor costs must mitigate the costs to small businesses, where legal and feasible, as defined in this chapter.

. If the agency determines it cannot reduce the costs imposed by the rule on small businesses, the agency must provide a clear explanation of why it has made that determination and include that statement with its filing of the proposed rule pursuant to RCW 34.05.320.

. [Empty]
.. All small business economic impact statements are subject to selective review by the joint administrative rules review committee pursuant to RCW 34.05.630.

.. Any person affected by a proposed rule where there is a small business economic impact statement may petition the joint administrative rules review committee for review pursuant to the procedure in RCW 34.05.655.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1120-S2.SL.pdf?cite=2017%20c%2053%20§%202[2017 c 53 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5500.SL.pdf?cite=2011%20c%20249%20§%202[2011 c 249 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1525.SL.pdf?cite=2007%20c%20239%20§%203[2007 c 239 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2400.SL.pdf?cite=2000%20c%20171%20§%2060[2000 c 171 § 60]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1010-S.SL.pdf?cite=1995%20c%20403%20§%20402[1995 c 403 § 402]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2510-S2.SL.pdf?cite=1994%20c%20249%20§%2011[1994 c 249 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c374.pdf?cite=1989%20c%20374%20§%202[1989 c 374 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%2072[1989 c 175 § 72]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c6.pdf?cite=1982%20c%206%20§%203[1982 c 6 § 3]; ]

== 19.85.040 - Small business economic impact statement—Purpose—Contents.
. A small business economic impact statement must include a brief description of the reporting, recordkeeping, and other compliance requirements of the proposed rule, and the kinds of professional services that a small business is likely to need in order to comply with such requirements. It shall analyze the costs of compliance for businesses required to comply with the proposed rule adopted pursuant to RCW 34.05.320, including costs of equipment, supplies, labor, professional services, and increased administrative costs. It shall consider, based on input received, whether compliance with the rule will cause businesses to lose sales or revenue. To determine whether the proposed rule will have a disproportionate cost impact on small businesses, the impact statement must compare the cost of compliance for small business with the cost of compliance for the ten percent of businesses that are the largest businesses required to comply with the proposed rules using one or more of the following as a basis for comparing costs:

.. Cost per employee;

.. Cost per hour of labor; or

.. Cost per one hundred dollars of sales.

. A small business economic impact statement must also include:

.. A statement of the steps taken by the agency to reduce the costs of the rule on small businesses as required by RCW 19.85.030(2), or reasonable justification for not doing so, addressing the options listed in RCW 19.85.030(2);

.. A description of how the agency will involve small businesses in the development of the rule;

.. A list of industries that will be required to comply with the rule. However, this subsection (2)(c) shall not be construed to preclude application of the rule to any business or industry to which it would otherwise apply; and

.. An estimate of the number of jobs that will be created or lost as the result of compliance with the proposed rule.

. To obtain information for purposes of this section, an agency may survey a representative sample of affected businesses or trade associations and should, whenever possible, appoint a committee under RCW 34.05.310(2) to assist in the accurate assessment of the costs of a proposed rule, and the means to reduce the costs imposed on small business.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1525.SL.pdf?cite=2007%20c%20239%20§%204[2007 c 239 § 4]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1010-S.SL.pdf?cite=1995%20c%20403%20§%20403[1995 c 403 § 403]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2510-S2.SL.pdf?cite=1994%20c%20249%20§%2012[1994 c 249 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c374.pdf?cite=1989%20c%20374%20§%203[1989 c 374 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%2073[1989 c 175 § 73]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c6.pdf?cite=1982%20c%206%20§%204[1982 c 6 § 4]; ]

== 19.85.050 - Agency plan for review of business rules—Scope—Factors applicable to review—Annual list.
. Within one year after June 10, 1982, each agency shall publish and deliver to the office of financial management and to all persons who make requests of the agency for a copy of a plan to periodically review all rules then in effect and which have been issued by the agency which have an economic impact on more than twenty percent of all industries or ten percent of the businesses in any one industry. Such plan may be amended by the agency at any time by publishing a revision to the review plan and delivering such revised plan to the office of financial management and to all persons who make requests of the agency for the plan. The purpose of the review is to determine whether such rules should be continued without change or should be amended or rescinded, consistent with the stated objectives of applicable statutes, to minimize the economic impact on small businesses as described by this chapter. The plan shall provide for the review of all such agency rules in effect on June 10, 1982, within ten years of that date.

. In reviewing rules to minimize any significant economic impact of the rule on small businesses as described by this chapter, and in a manner consistent with the stated objectives of applicable statutes, the agency shall consider the following factors:

.. The continued need for the rule;

.. The nature of complaints or comments received concerning the rule from the public;

.. The complexity of the rule;

.. The extent to which the rule overlaps, duplicates, or conflicts with other state or federal rules, and, to the extent feasible, with local governmental rules; and

.. The degree to which technology, economic conditions, or other factors have changed in the subject area affected by the rule.

. Each year each agency shall publish a list of rules which are to be reviewed pursuant to this section during the next twelve months and deliver a copy of the list to the office of financial management and all persons who make requests of the agency for the list. The list shall include a brief description of the legal basis for each rule as described by RCW 34.05.360, and shall invite public comment upon the rule.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%2074[1989 c 175 § 74]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c6.pdf?cite=1982%20c%206%20§%205[1982 c 6 § 5]; ]

== 19.85.061 - Compliance with federal law.
Unless so requested by a majority vote of the joint administrative rules review committee under RCW 19.85.030, an agency is not required to comply with this chapter when adopting any rule solely for the purpose of conformity or compliance, or both, with federal statute or regulations. In lieu of the statement required under RCW 19.85.030, the agency shall file a statement citing, with specificity, the federal statute or regulation with which the rule is being adopted to conform or comply, and describing the consequences to the state if the rule is not adopted.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1010-S.SL.pdf?cite=1995%20c%20403%20§%20404[1995 c 403 § 404]; ]

== 19.85.070 - Small business economic impact statement—Notice of proposed rule.
When any rule is proposed for which a small business economic impact statement is required, the adopting agency must provide notice to small businesses of the proposed rule through:

. Direct notification of known interested small businesses or trade organizations affected by the proposed rule;

. Providing information of the proposed rule making to publications likely to be obtained by small businesses of the types affected by the proposed rule; and

. Posting on the agency website.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5500.SL.pdf?cite=2011%20c%20249%20§%203[2011 c 249 § 3]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2498-S.SL.pdf?cite=1992%20c%20197%20§%201[1992 c 197 § 1]; ]

