= 19.94 - Weights and measures.
:toc:

== 19.94.005 - Findings.
The legislature finds:

. The accuracy of weighing and measuring instruments and devices used in commerce in the state of Washington affects every consumer throughout the state and is of vital importance to the public interest.

. Fair weights and measures are equally important to business and the consumer.

. This chapter safeguards the consuming public and ensures that businesses receive proper compensation for the commodities they deliver.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1524-S2.SL.pdf?cite=1995%20c%20355%20§%203[1995 c 355 § 3]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%201[1992 c 237 § 1]; ]

== 19.94.010 - Definitions—Director may prescribe by rule.
. The definitions in this section apply throughout this chapter and to any rules adopted pursuant to this chapter unless the context clearly requires otherwise.

.. "City" means a first-class city or a code city, as defined in RCW 35A.01.035, with a population of over fifty thousand persons.

.. "City sealer" means the person duly authorized by a city to enforce and administer the weights and measures program within such city and any duly appointed deputy sealer acting under the instructions and at the direction of the city sealer.

.. "Commodity in package form" means a commodity put up or packaged in any manner in advance of sale in units suitable for either wholesale or retail sale, exclusive, however, of an auxiliary shipping container enclosing packages that individually conform to the requirements of this chapter. An individual item or lot of any commodity not in packaged form, but on which there is marked a selling price based on established price per unit of weight or of measure, shall be construed to be a commodity in package form.

.. "Consumer package" or "package of consumer commodity" means a commodity in package form that is customarily produced or distributed for sale through retail sales agencies or instrumentalities for consumption by persons, or used by persons for the purpose of personal care or in the performance of services ordinarily rendered in or about a household or in connection with personal possessions.

.. "Cord" means the measurement of wood intended for fuel or pulp purposes that is contained in a space of one hundred twenty-eight cubic feet, when the wood is ranked and well stowed.

.. "Department" means the department of agriculture of the state of Washington.

.. "Director" means the director of the department or duly authorized representative acting under the instructions and at the direction of the director.

.. "Fish" means any waterbreathing animal, including shellfish, such as, but not limited to, lobster, clam, crab, or other mollusca that is prepared, processed, sold, or intended for sale.

.. "Net weight" means the weight of a commodity excluding any materials, substances, or items not considered to be part of such commodity. Materials, substances, or items not considered to be part of a commodity shall include, but are not limited to, containers, conveyances, bags, wrappers, packaging materials, labels, individual piece coverings, decorative accompaniments, and coupons.

.. "Nonconsumer package" or "package of nonconsumer commodity" means a commodity in package form other than a consumer package and particularly a package designed solely for industrial or institutional use or for wholesale distribution only.

.. "Meat" means and shall include all animal flesh, carcasses, or parts of animals, and shall also include fish, shellfish, game, poultry, and meat food products of every kind and character, whether fresh, frozen, cooked, cured, or processed.

.. "Official seal of approval" means the seal or certificate issued by the director or city sealer which indicates that a secondary weights and measures standard or a weighing or measuring instrument or device conforms with the specifications, tolerances, and other technical requirements adopted in RCW 19.94.190.

.. "Person" means any individual, receiver, administrator, executor, assignee, trustee in bankruptcy, trust, estate, firm, copartnership, joint venture, club, company, business trust, corporation, association, society, or any group of individuals acting as a unit, whether mutual, cooperative, fraternal, nonprofit, or otherwise.

.. "Poultry" means all fowl, domestic or wild, that is prepared, processed, sold, or intended or offered for sale.

.. "Service agent" means a person who for hire, award, commission, or any other payment of any kind, installs, tests, inspects, checks, adjusts, repairs, reconditions, or systematically standardizes the graduations of a weighing or measuring instrument or device.

.. "Ton" means a unit of two thousand pounds avoirdupois weight.

.. "Weighing or measuring instrument or device" means any equipment or apparatus used commercially to establish the size, quantity, capacity, count, extent, area, heaviness, or measurement of quantities, things, produce, or articles for distribution or consumption, that are purchased, offered or submitted for sale, hire, or award on the basis of weight, measure or count, including any accessory attached to or used in connection with a weighing or measuring instrument or device when such accessory is so designed or installed that its operation affects, or may effect, the accuracy or indication of the device. This definition shall be strictly limited to those weighing or measuring instruments or devices governed by Handbook 44 as adopted under RCW 19.94.190.

.. "Weight" means net weight as defined in this section.

.. "Weights and measures" means the recognized standards or units of measure used to indicate the size, quantity, capacity, count, extent, area, heaviness, or measurement of any consumable commodity.

.. "Secondary weights and measures standard" means the physical standards that are traceable to the primary standards through comparisons, used by the director, a city sealer, or a service agent that under specified conditions defines or represents a recognized weight or measure during the inspection, adjustment, testing, or systematic standardization of the graduations of any weighing or measuring instrument or device.

. The director shall prescribe by rule other definitions as may be necessary for the implementation of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1298-S.SL.pdf?cite=2019%20c%2096%20§%201[2019 c 96 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1524-S2.SL.pdf?cite=1995%20c%20355%20§%204[1995 c 355 § 4]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%203[1992 c 237 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%201[1969 c 67 § 1]; ]

== 19.94.015 - Commercial use of instrument or device—Registration—Fees.
. Except as provided in subsection (4) of this section for the initial registration of an instrument or device, no weighing or measuring instrument or device may be used for commercial purposes in the state unless its commercial use is registered annually. If its commercial use is within a city that has a city sealer and a weights and measures program as provided by RCW 19.94.280, the commercial use of the instrument or device must be registered with the city if the city has adopted fees pursuant to subsection (2) of this section. If its commercial use is outside of such a city, the commercial use of the instrument or device must be registered with the department.

. A city with such a sealer and program may establish an annual fee for registering the commercial use of such a weighing or measuring instrument or device with the city. The annual fee may not exceed the fee established in RCW 19.94.175 for registering the use of a similar instrument or device with the department. Fees upon weighing or measuring instruments or devices within the jurisdiction of the city that are collected under this subsection by city sealers must be deposited into the general fund, or other account, of the city as directed by the governing body of the city.

. Registrations with the department are accomplished as part of the business licensing system under chapter 19.02 RCW. Payment of the registration fee for a weighing or measuring instrument or device under the business licensing system constitutes the registration required by this section.

. The fees established by or under RCW 19.94.175 for registering a weighing or measuring instrument or device must be paid to the department of revenue concurrently with an application for a business license under chapter 19.02 RCW or with the annual renewal of a business license under chapter 19.02 RCW. A weighing or measuring instrument or device must be initially registered with the state at the time the owner applies for a business license for a new business or at the first renewal of the license that occurs after the instrument or device is first placed into commercial use. The department of revenue must remit to the department of agriculture all fees collected under this provision less reasonable collection expenses.

. Each city charging registration fees under this section must notify the department of agriculture at the time such fees are adopted and whenever changes in the fees are adopted.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1568-S.SL.pdf?cite=2013%20c%20144%20§%2034[2013 c 144 § 34]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2017-S.SL.pdf?cite=2011%20c%20298%20§%2019[2011 c 298 § 19]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5374-S.SL.pdf?cite=2011%20c%20103%20§%2038[2011 c 103 § 38]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1524-S2.SL.pdf?cite=1995%20c%20355%20§%201[1995 c 355 § 1]; ]

== 19.94.150 - Standards recognized.
The system of weights and measures in customary use in the United States and the metric system of weights and measures are jointly recognized, and either one or both of these systems shall be used for all commercial purposes in this state. The definitions of basic units of weight and measure and weights and measures equivalents, as published by the national institute of standards and technology or any successor organization, are recognized and shall govern weighing or measuring instruments or devices used in commercial activities and other transactions involving weights and measures within this state.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%204[1992 c 237 § 4]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1856-S.SL.pdf?cite=1991%20sp.s.%20c%2023%20§%204[1991 sp.s. c 23 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2015[1969 c 67 § 15]; ]

== 19.94.160 - State standards.
Physical weights and measures standards that conform to the standards of the United States obtained by the state for use as state weights and measures standards are the primary standards for weight and measure, when certified as such by the national institute of standards and technology or any successor organization. The state weights and measures standards shall be kept in a place designated by the director and shall be maintained in such calibration as prescribed by the national institute of standards and technology or any successor organization.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1298-S.SL.pdf?cite=2019%20c%2096%20§%202[2019 c 96 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1524-S2.SL.pdf?cite=1995%20c%20355%20§%205[1995 c 355 § 5]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%205[1992 c 237 § 5]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1856-S.SL.pdf?cite=1991%20sp.s.%20c%2023%20§%205[1991 sp.s. c 23 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2016[1969 c 67 § 16]; ]

== 19.94.163 - Testing by department—Ensuring enforcement—Issuance of seal of approval—Exception.
. Except as provided in subsection (3) of this section and *RCW 19.94.190(1)(d), the department shall test and inspect each biennium a sufficient number of weighing and measuring instruments and devices to ensure that the provisions of this chapter are enforced.

. The department may issue an official seal of approval for each weighing or measuring instrument or device that has been tested and inspected and found to be correct.

. Except as provided in RCW 19.94.216, this section does not apply to weighing or measuring instruments or devices located in an area of the state that is within a city that has a city sealer and a weights and measures program pursuant to RCW 19.94.280 unless the city sealer does not possess the equipment necessary to test and inspect the weighing or measuring instrument or device.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1524-S2.SL.pdf?cite=1995%20c%20355%20§%202[1995 c 355 § 2]; ]

== 19.94.175 - Registration—Inspection and testing—Fees—Report.
. Pursuant to RCW 19.94.015, the following annual registration fees shall be charged for each weighing or measuring instrument or device used for commercial purposes in this state:

..Weighing devices:(i)Small scales "zero to four hundred pounds capacity" . . . .$16.00(ii)Intermediate scales "four hundred one pounds to five thousand pounds capacity" . . . .$60.00(iii)Large scales "over five thousand pounds capacity" . . . .$120.00(iv)Railroad track scales . . . .$1,200.00(b)Liquid fuel metering devices:(i)Motor fuel meters with flows of twenty gallons or less per minute . . . .$16.00(ii)Motor fuel meters with flows of more than twenty but not more than one hundred fifty gallons per minute . . . .$50.00(iii)Motor fuel meters with flows over one hundred fifty gallons per minute . . . .$75.00(c)Liquid petroleum gas meters:(i)With one inch diameter or smaller dispensers . . . .$40.00(ii)With greater than one inch diameter dispensers . . . .$80.00(d)Fabric meters . . . .$15.00(e)Cordage meters . . . .$15.00(f)Mass flow meters . . . .$300.00(g)Taxi meters . . . .$40.00

..

Weighing devices:

...

Small scales "zero to four hundred pounds capacity" . . . .

$

16.00

...

Intermediate scales "four hundred one pounds to five thousand pounds capacity" . . . .

$

60.00

...

Large scales "over five thousand pounds capacity" . . . .

$

120.00

...

Railroad track scales . . . .

$

1,200.00

..

Liquid fuel metering devices:

...

Motor fuel meters with flows of twenty gallons or less per minute . . . .

$

16.00

...

Motor fuel meters with flows of more than twenty but not more than one hundred fifty gallons per minute . . . .

$

50.00

...

Motor fuel meters with flows over one hundred fifty gallons per minute . . . .

$

75.00

..

Liquid petroleum gas meters:

...

With one inch diameter or smaller dispensers . . . .

$

40.00

...

With greater than one inch diameter dispensers . . . .

$

80.00

..

Fabric meters . . . .

$

15.00

..

Cordage meters . . . .

$

15.00

..

Mass flow meters . . . .

$

300.00

..

Taxi meters . . . .

$

40.00

. With the exception of subsection (3) of this section, no person shall be required to pay more than the annual registration fee for any weighing or measuring instrument or device in any one year.

. The department or a city sealer may establish reasonable inspection and testing fees for each type or class of weighing or measuring instrument or device specially requested to be inspected or tested by the device owner. These inspection and testing fees shall be limited to those amounts necessary for the department or city sealer to cover the direct costs associated with such inspection and testing. The fees shall not be set so as to compete with service agents normally engaged in such services.

. The weights and measures advisory group within the department must review the fees in subsection (1) of this section and report to stakeholders on the financial status of the program supported by the fees by September 1, 2024, and September 1st every five years thereafter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1298-S.SL.pdf?cite=2019%20c%2096%20§%203[2019 c 96 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6365-S.SL.pdf?cite=2006%20c%20358%20§%202[2006 c 358 § 2]; 2006 c 358 § 1; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1524-S2.SL.pdf?cite=1995%20c%20355%20§%207[1995 c 355 § 7]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%207[1992 c 237 § 7]; ]

== 19.94.185 - Deposit of moneys—Weights and measures account—General fund.
. Except as provided in subsection (2) of this section, all moneys collected under this chapter shall be payable to the director and placed in the weights and measures account hereby established in the agricultural local fund. Moneys deposited in this account shall be used solely for the purposes of implementing or enforcing this chapter. No appropriation is required for the disbursement of moneys from the weights and measures account by the director.

. Civil penalties collected by the department under RCW 19.94.510, 19.94.515, and 19.94.517 shall be deposited in the state general fund.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%209[1998 c 245 § 9]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1524-S2.SL.pdf?cite=1995%20c%20355%20§%208[1995 c 355 § 8]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%208[1992 c 237 § 8]; ]

== 19.94.190 - Enforcement—Rules—Penalties.
. The director and duly appointed city sealers must enforce the provisions of this chapter.

. The department's enforcement proceedings under this chapter are subject to the requirement to provide technical assistance in chapter 43.05 RCW and the administrative procedure act, chapter 34.05 RCW. City sealers undertaking enforcement actions must provide equivalent procedures.

. In assessing the amount of a civil penalty, the department or city must give due consideration to the gravity of the violation and history of previous violations.

. The director must adopt rules for enforcing and carrying out the purposes of this chapter including but not limited to the following:

.. Establishing state standards of weight, measure, or count, and reasonable standards of fill for any commodity in package form;

.. The establishment of technical test procedures to be followed, any necessary report and record forms, and marks of rejection to be used by the director and city sealers in the discharge of their official duties as required by this chapter;

.. The establishment of technical test procedures, reporting procedures, and any necessary record and reporting forms to be used by service agents when testing and inspecting instruments or devices under RCW 19.94.255(3) or when otherwise installing, repairing, inspecting, or standardizing the graduations of any weighing or measuring instruments or devices;

.. The establishment of exemptions from the marking or tagging requirements of RCW 19.94.250 with respect to weighing or measuring instruments or devices of such a character or size that the marking or tagging would be inappropriate, impracticable, or damaging to the apparatus in question;

.. The establishment of exemptions from the inspection and testing requirements of RCW 19.94.163 with respect to classes of weighing or measuring instruments or devices found to be of such a character that periodic inspection and testing is unnecessary to ensure continued accuracy;

.. The establishment of inspection and approval techniques, if any, to be used with respect to classes of weighing or measuring instruments or devices that are designed specifically to be used commercially only once and then discarded, or are uniformly mass-produced by means of a mold or die and are not individually adjustable;

.. The establishment of inspection and testing procedures to be used for classes of weighing or measuring instruments or devices found to be few in number, highly complex, and of such character that differential or special inspection and testing is necessary, including railroad track scales. The department's procedures shall include requirements for the provision, maintenance, and transport of any weight or measure necessary for the inspection and testing at no expense to the state;

.. Specifications, tolerances, and other technical requirements for commercial weighing and measuring instruments or devices that must be consistent with the most recent edition of the national institute of standards and technology handbook 44 except where modified to achieve state objectives; and

.. Packaging, labeling, and method of sale of commodities that must be consistent with the most recent edition of the national institute of standards and technology handbook 44 and 130 (for legal metrology and engine fuel quality) except where modified to achieve state objectives.

. Rules adopted under this section must also include specifications and tolerances for the acceptable range of accuracy required of weighing or measuring instruments or devices and must be designed to eliminate from use, without prejudice to weighing or measuring instruments or devices that conform as closely as practicable to official specifications and tolerances, those that: (a) Are of such construction that they are faulty, that is, that are not reasonably permanent in their adjustment or will not repeat their indications correctly; or (b) facilitate the perpetration of fraud.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1298-S.SL.pdf?cite=2019%20c%2096%20§%204[2019 c 96 § 4]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1524-S2.SL.pdf?cite=1995%20c%20355%20§%209[1995 c 355 § 9]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%209[1992 c 237 § 9]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1856-S.SL.pdf?cite=1991%20sp.s.%20c%2023%20§%206[1991 sp.s. c 23 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2036[1989 c 354 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c26.pdf?cite=1977%20ex.s.%20c%2026%20§%205[1977 ex.s. c 26 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2019[1969 c 67 § 19]; ]

== 19.94.205 - Correct and incorrect—Instruments, devices, weights, measures—When deemed.
All weighing or measuring instruments or devices used for commercial purposes within this state must be correct. For the purposes of this chapter, weighing or measuring instruments or devices and weights and measures standards are deemed to be "correct" when they conform to all applicable requirements of this chapter and the requirements of any rule adopted by the department under this chapter; all other weighing or measuring instruments or devices and weights and measures standards are deemed to be "incorrect."

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1298-S.SL.pdf?cite=2019%20c%2096%20§%205[2019 c 96 § 5]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2011[1992 c 237 § 11]; ]

== 19.94.216 - Department inspection—City sealer—Fees.
The department must biennially inspect and test the secondary weights and measures standards of any city having a city sealer appointed under this chapter and must issue an official seal of approval for the same when found to be correct. The department must, by rule, establish a reasonable fee for this and any other inspection and testing services performed by the department's metrology laboratory.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1298-S.SL.pdf?cite=2019%20c%2096%20§%206[2019 c 96 § 6]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1524-S2.SL.pdf?cite=1995%20c%20355%20§%2010[1995 c 355 § 10]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2012[1992 c 237 § 12]; ]

== 19.94.220 - Investigations.
In promoting the general objective of ensuring accuracy of weighing or measuring instruments or devices and the proper representation of weights and measures in commercial transactions, the director or a city sealer shall, upon his or her own initiative and as he or she deems appropriate and advisable, investigate complaints made concerning violations of the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2013[1992 c 237 § 13]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1856-S.SL.pdf?cite=1991%20sp.s.%20c%2023%20§%208[1991 sp.s. c 23 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2022[1969 c 67 § 22]; ]

== 19.94.230 - Inspections and tests to determine conformity to law—Off sale order—Marks, tags, stamps.
. The director or a city sealer may, from time to time, inspect and test packages or amounts of commodities kept, offered, exposed for sale, sold, or in the process of delivery to determine whether the same contain the amounts represented and whether they are kept, offered, exposed for sale or sold in accordance with law. When such packages or amounts of commodities are found not to contain the amounts represented or are found to be kept, offered, or exposed for sale or sold in violation of law, the director or city sealer may order them off sale and may mark, tag, or stamp them in a manner prescribed by the department.

. In carrying out the provisions of this section, the director or city sealer may employ recognized sampling procedures under which the compliance of a given lot of packages will be determined on the basis of a result obtained on a sample selected from and representative of such lot. 

. No person shall (a) sell, keep, offer, or expose for sale any package or amount of commodity that has been ordered off sale as provided in this section unless and until such package or amount of commodity has been brought into full compliance with legal requirements or (b) dispose of any package or amount of commodity that has been ordered off sale and that has not been brought into compliance with legal requirements in any manner except with the specific written approval of the director or city sealer who issued such off sale order.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2014[1992 c 237 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2023[1969 c 67 § 23]; ]

== 19.94.240 - Stop-use, stop-removal, and removal orders.
. The director or a city sealer shall have the power to issue stop-use orders, stop-removal orders, and removal orders with respect to weighing or measuring devices being, or susceptible of being, commercially used within this state.

. The director or a city sealer shall also have the power to issue stop-removal orders and removal orders with respect to packages or amounts of commodities kept, offered, exposed for sale, sold, or in process of delivery.

. The director or a city sealer shall issue such orders whenever in the course of his or her enforcement of the provisions of this chapter or rules adopted hereunder he or she deems it necessary or expedient to issue such orders. 

. No person shall use, remove from the premises specified, or fail to remove from any premises specified any weighing or measuring instrument or device, commodity in packaged form, or amount of commodity contrary to the terms of a stop-use order, stop-removal order or removal order, issued under the authority of this section.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2015[1992 c 237 § 15]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1856-S.SL.pdf?cite=1991%20sp.s.%20c%2023%20§%209[1991 sp.s. c 23 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2024[1969 c 67 § 24]; ]

== 19.94.250 - Inspection of instrument or device to determine if correct—Rejection or seizure—Confiscation or destruction—Use of incorrect instrument or device—Notice.
. If the director or a city sealer discovers upon inspection that a weighing or measuring instrument or device is "incorrect," but in his or her best judgment is susceptible of satisfactory repair, he or she shall reject and mark or tag as rejected any such weighing or measuring instrument or device.

. The director or a city sealer may reject or seize any weighing or measuring instrument or device found to be incorrect that, in his or her best judgment, is not susceptible of satisfactory repair.

. Weighing or measuring instruments or devices that have been rejected under subsection (1) of this section may be confiscated and may be destroyed by the director or a city sealer if not corrected as required by RCW 19.94.255 or if used or disposed of contrary to the requirements of that section.

. The director or a city sealer shall permit the use of an incorrect weighing or measuring instrument or device, pending repairs, if the device is incorrect to the economic benefit of the consumer and the consumer is not the seller. However, if the director or city sealer finds such an error, the director or city sealer shall notify the owner of the instrument or device, or the owner's representative at the business location, regarding the error.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1524-S2.SL.pdf?cite=1995%20c%20355%20§%2011[1995 c 355 § 11]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2016[1992 c 237 § 16]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1856-S.SL.pdf?cite=1991%20sp.s.%20c%2023%20§%2010[1991 sp.s. c 23 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2025[1969 c 67 § 25]; ]

== 19.94.255 - Correction of rejected weights and measures.
. Weighing or measuring instruments or devices that have been rejected under the authority of the director or a city sealer shall remain subject to the control of the rejecting authority until such time as suitable repair or disposition thereof has been made as required by this section.

. The owner of any weighing or measuring instrument or device that has been marked or tagged as rejected by the director or a city sealer shall cause the same to be made correct within thirty days or such longer period as may be authorized by the rejecting authority. In lieu of correction, the owner of such weighing and measuring instrument or device may dispose of the same, but only in the manner specifically authorized by the rejecting authority.

. Weighing and measuring instruments or devices that have been rejected shall not again be used commercially until they have been reexamined and found to be correct by the department, city sealer, or a service agent registered with the department.

. If a weighing or measuring instrument or device marked or tagged as rejected is placed back into commercial service by a service agent registered with the department, the agent shall provide a signed certification to the owner or operator of the instrument or device so indicating and shall report to the rejecting authority as provided by rule under *RCW 19.94.190(1)(c).

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1524-S2.SL.pdf?cite=1995%20c%20355%20§%2012[1995 c 355 § 12]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2017[1992 c 237 § 17]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1856-S.SL.pdf?cite=1991%20sp.s.%20c%2023%20§%2014[1991 sp.s. c 23 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2033[1969 c 67 § 33]; ]

== 19.94.258 - Service agent—Registration certificate.
. Except as authorized by the department, a service agent must be certified by the department before providing services to place a weighing or measuring instrument or device to be placed into commercial use under RCW 19.94.255(3). This registration requirement does not apply to the department or a city sealer.

. Except as provided in RCW 19.94.2584, a service agent registration certificate is valid for one year unless the department specifies a longer period by rule. The certificate may be renewed by submitting a renewal application to the department.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1298-S.SL.pdf?cite=2019%20c%2096%20§%207[2019 c 96 § 7]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2400.SL.pdf?cite=2000%20c%20171%20§%2061[2000 c 171 § 61]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1524-S2.SL.pdf?cite=1995%20c%20355%20§%2015[1995 c 355 § 15]; ]

== 19.94.2582 - Service agent—Registration certificate—Renewal—Competency examination—Fee—Decision—Denial—Notice—Refund.
. Each request for a renewal or new official registration certificate must be in writing and on a form prescribed by the department and must contain any relevant information as the director may require, including but not limited to the following:

.. The name and address of the person, corporation, partnership, or sole proprietorship requesting registration;

.. The names and addresses of all persons requesting an official registration certificate from the department; and

.. The tax registration number as required under RCW 82.32.030 or unified business identifier provided on a business license issued under RCW 19.02.070.

. The department may require persons registering as service agents to attain a satisfactory score on competency examinations administered or approved for use by the department. The director may adopt rules for administering and conducting the examination, including adoption of any examination fees necessary to cover the costs for preparing for and administering the examination. Examination fees are in addition to the application fee under subsection (3) of this section.

. Each person submitting a new or renewal application for an official registration certificate must pay a fee to the department in the amount of one hundred eighty dollars per person per year for the duration of the certificate.

. Renewal applicants filing after a certification expiration date must pay an additional fee equal to twenty percent of the renewal fee unless the applicant submits a declaration or affidavit stating that the applicant has not acted as a service agent following the expiration of the certification.

. Persons submitting new or renewal applications for an official registration certificate must have sufficient equipment available to adequately test devices and a means of identifying work the applicant has performed on weighing and measuring devices. The director may adopt rules for these requirements.

. The department must issue a decision within twenty days of receipt of a new or renewal application. If denying an application, the department must state the reasons for the denial in a written notice to the applicant.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1298-S.SL.pdf?cite=2019%20c%2096%20§%208[2019 c 96 § 8]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1568-S.SL.pdf?cite=2013%20c%20144%20§%2035[2013 c 144 § 35]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6365-S.SL.pdf?cite=2006%20c%20358%20§%205[2006 c 358 § 5]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1524-S2.SL.pdf?cite=1995%20c%20355%20§%2016[1995 c 355 § 16]; ]

== 19.94.2584 - Service agent—Registration certificate—Revocation, suspension, refusal to renew—Appeal.
. The department may revoke, suspend, or refuse to renew the official registration certificate of any service agent for any of the following reasons:

.. Fraud or deceit in obtaining an official registration certificate under this chapter;

.. A finding by the department of a pattern of intentional fraudulent or negligent activities in the installation, inspection, testing, checking, adjusting, or systematically standardizing and approving the graduations of any weighing or measuring instrument or device;

.. Knowingly placing back into commercial service any weighing or measuring instrument or device that is incorrect;

.. A violation of any provision of this chapter; or

.. Conviction of a crime or an act constituting a crime under the laws of this state, the laws of another state, or federal law.

. A service agent may appeal the department's decision to revoke, suspend, or refuse to renew the service agent's registration.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1298-S.SL.pdf?cite=2019%20c%2096%20§%209[2019 c 96 § 9]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2400.SL.pdf?cite=2000%20c%20171%20§%2062[2000 c 171 § 62]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1524-S2.SL.pdf?cite=1995%20c%20355%20§%2017[1995 c 355 § 17]; ]

== 19.94.260 - Rejection—Seizure for use as evidence—Entry of premises—Search warrant.
. With respect to the enforcement of this chapter and any other acts dealing with weights and measures that he or she is, or may be empowered to enforce, the director or a city sealer may reject or seize for use as evidence incorrect weighing or measuring instruments or devices or packages of commodities to be used, retained, offered, exposed for sale, or sold in violation of the law.

. In the performance of his or her official duties conferred under this chapter, the director or a city sealer is authorized at reasonable times during the normal business hours of the person using a weighing or measuring instrument or device to enter into or upon any structure or premises where such weighing or measuring instrument or device is used or kept for commercial purposes. If the director or a city sealer is denied access to any premises or establishment where such access was sought for the purposes set forth in this chapter, the director or a city sealer may apply to any court of competent jurisdiction for a search warrant authorizing access to such premises or establishment for such purposes. The court may, upon such application, issue the search warrant for the purposes requested.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2018[1992 c 237 § 18]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1856-S.SL.pdf?cite=1991%20sp.s.%20c%2023%20§%2011[1991 sp.s. c 23 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2026[1969 c 67 § 26]; ]

== 19.94.265 - Grievances—Procedure—Notice—Hearing—Rules.
. Any person aggrieved by any official action of the department or a city sealer conferred under this chapter, including but not limited to, "stop-use orders," "stop-removal orders," "removal orders," "condemnation," or "off sale order" may within thirty days after an order is given or any action is taken, petition the director for a hearing to determine the matter. Such proceedings and any appeal therefrom shall be taken in accordance with the administrative procedure act, chapter 34.05 RCW.

. The director shall give due notice and hold a hearing within ten days after the confiscation or seizure of any weighing or measuring instrument or device or commodity under RCW 19.94.250 or the seizure of any weighing or measuring instrument or device for evidence under RCW 19.94.260. This hearing shall be for the purposes of determining whether any such weighing or measuring instrument or device or commodity was properly confiscated or seized, to determine whether or not such weighing or measuring instrument or device or commodity was used for, or is in, violation of any provision of this chapter or to determine the disposition to be made of such weighing or measuring instrument or device or commodity. Such proceedings and any appeal therefrom shall be taken in accordance with the administrative procedure act, chapter 34.05 RCW.

. The department may by rule establish procedures for the administration of this section.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2019[1992 c 237 § 19]; ]

== 19.94.280 - City sealers and deputies—Appointment, removal—Record, report—Testing of devices and instruments—Seal of approval.
. There may be a city sealer in every city and such deputies as may be required by ordinance of each such city to administer and enforce the provisions of this chapter.

. Each city electing to have a city sealer shall adopt rules for the appointment and removal of the city sealer and any deputies required by local ordinance. The rules for appointment of a city sealer and any deputies must include provisions for the advice and consent of the local governing body of such city and, as necessary, any provisions for local civil service laws and regulations.

. A city sealer shall keep a complete and accurate record of all official acts performed under the authority of this chapter and shall submit an annual report to the governing body of his or her city and shall make any reports as may be required by the director.

. The city sealer shall test and inspect a sufficient number of weighing and measuring instruments and devices to ensure that the provisions of this chapter are enforced in the city. This subsection does not apply to weighing or measuring instruments or devices for which the sealer does not have the necessary testing or inspection equipment or to instruments or devices that are to be inspected by the department under *RCW 19.94.216(2).

. A city sealer may issue an official seal of approval for each weighing or measuring instrument or device that has been inspected and tested and found to be correct.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1524-S2.SL.pdf?cite=1995%20c%20355%20§%2013[1995 c 355 § 13]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2020[1992 c 237 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2028[1969 c 67 § 28]; ]

== 19.94.310 - City sealers and deputies—Duties of governing body—Sealer to have standards comparison made every two years.
. The governing body of each city for which a city sealer has been appointed as provided for by RCW 19.94.280 shall:

.. Procure at the expense of the city the official weights and measures standards and any field weights and measures standards necessary for the administration and enforcement of the provisions of this chapter or any rule that may be prescribed by the director;

.. Provide a suitable office for the city sealer and any deputies that have been duly appointed; and

.. Make provision for the necessary clerical services, supplies, transportation and for defraying contingent expenses incidental to the official activities of the city sealer and his or her deputies in carrying out the provisions of this chapter.

. When the acquisition of the official weights and measures standards required under subsection (1)(a) of this section has been made and such weights and measures standards have been examined and approved by the director, they shall be the certified weights and measures standards for such city.

. In order to maintain field weights and measures standards in accurate condition, the city sealer shall, at least once every two years, compare the field weights and measures standards used within his or her city to the certified weights and measures standards of such city or to the official weights and measures standards of this state.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2400.SL.pdf?cite=2000%20c%20171%20§%2063[2000 c 171 § 63]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2021[1992 c 237 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2031[1969 c 67 § 31]; ]

== 19.94.320 - City sealers—Director—General oversight powers, concurrent authority—Powers and duties of chapter are additional.
. In cities for which city sealers have been appointed as provided for in this chapter, the director shall have general oversight powers over city weights and measures programs and may, when he or she deems it reasonably necessary, exercise concurrent authority to carry out the provisions of this chapter.

. When the director elects to exercise concurrent authority within a city with a duly appointed city sealer, the director's powers and duties relative to this chapter shall be in addition to the powers granted in any such city by law or charter.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1524-S2.SL.pdf?cite=1995%20c%20355%20§%2014[1995 c 355 § 14]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2022[1992 c 237 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2032[1969 c 67 § 32]; ]

== 19.94.325 - Service agent—Inspection and testing of weights and measures—Seal of approval—Fees—Violation—Penalty.
. Except as otherwise provided for in this chapter or in any rule adopted under the authority of this chapter, any person who engages in business within this state as a service agent shall biennially submit to the department for inspection and testing all weights and measures standards used by the service agent, or any agent or employee of the service agent. If the department finds such weights and measures standards to be correct, the director shall issue an official seal of approval for each such standard.

. The department may by rule adopt reasonable fees for the inspection and testing services performed by the weights and measures laboratory pursuant to this section.

. A service agent shall not use any weight or measure standard that does not have a valid, official seal of approval from the director to install, inspect, adjust, repair, or recondition any weighing or measuring instrument or device. Any service agent who violates this section is subject to a civil penalty to be assessed by the director ranging up to one thousand dollars per occurrence.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1298-S.SL.pdf?cite=2019%20c%2096%20§%2010[2019 c 96 § 10]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2023[1992 c 237 § 23]; ]

== 19.94.340 - Sale of commodities—Measurement—Exceptions—Rules to assure good practice and accuracy.
. Except as provided in subsection (2) of this section, commodities in liquid form must be sold only by liquid measure or by weight, and, except as otherwise provided in this chapter, commodities not in liquid form shall be sold only by weight, by measure of length or area, or by count.

. Liquid commodities may be sold by weight and commodities not in liquid form may be sold by count only if such methods provide accurate information as to the quantity of commodity sold.

. The provisions of this section do not apply to:

.. Commodities sold for immediate consumption on the premises where sold;

.. Vegetables when sold by the head or bunch;

.. Commodities in containers standardized by a law of this state or by federal law;

.. Commodities in package form when there exists a general consumer usage to express the quantity in some other manner;

.. Concrete aggregates, concrete mixtures, and loose solid materials such as earth, soil, gravel, crushed stone, and the like, when sold by cubic measure; or

.. Unprocessed vegetable and animal fertilizer when sold by cubic measure.

. When adopting rules under RCW 19.94.190, the director may issue such rules as necessary to assure that amounts of commodity sold are in accordance with good commercial practice and provide accurate information to all interested parties.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1298-S.SL.pdf?cite=2019%20c%2096%20§%2011[2019 c 96 § 11]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2024[1992 c 237 § 24]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1856-S.SL.pdf?cite=1991%20sp.s.%20c%2023%20§%2015[1991 sp.s. c 23 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2034[1969 c 67 § 34]; ]

== 19.94.350 - Packaged commodities in intrastate commerce—Declaration of contents on outside—Rules.
. Except as otherwise provided in this chapter, any commodity in package form introduced or delivered for introduction into or received in intrastate commerce, kept for the purpose of sale, offered or exposed for sale or sold in intrastate commerce, must bear on the outside of the package such definite, plain, and conspicuous declaration of:

.. The identity of the commodity contained within the package unless the same can easily be identified through the package;

.. The net quantity of the contents in terms of weight, measure or count; and

.. In the case of any package not sold on the premises where packed, the name and place of business of the manufacturer, packer, or distributor, as may be prescribed by rule issued by the director.

. The declaration of weight, measure, or count required under subsection (1)(b) of this section, must not include or be associated with the qualifying term "when packed," any words of similar import, or any term qualifying a unit of weight, measure, or count (for example, "jumbo", "giant", "full", "or over", and the like) that tends to exaggerate the amount of commodity in a package.

. With respect to the declaration of weight, measure, or count required under subsection (1)(b) of this section, the director may by rule establish: (a) Reasonable variations to be allowed; (b) exemptions as to small packages; (c) exemptions as to commodities put up in variable weights or sizes for sale to the consumer intact and either customarily not sold as individual units or customarily weighed or measured at time of sale to the consumer; and (d) methods for checking the net contents of packaged goods.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1298-S.SL.pdf?cite=2019%20c%2096%20§%2012[2019 c 96 § 12]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2025[1992 c 237 § 25]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1856-S.SL.pdf?cite=1991%20sp.s.%20c%2023%20§%2016[1991 sp.s. c 23 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2035[1969 c 67 § 35]; ]

== 19.94.360 - Declaration of price on outside of package.
In addition to the declarations required by RCW 19.94.350, any commodity in package form, the package being one of a lot containing random weights, measures or counts of the same commodity at the time it is exposed for sale at retail, shall bear on the outside of the package a plain and conspicuous declaration of the price per single unit of weight, measure, or count and the total selling price of the package.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1524-S2.SL.pdf?cite=1995%20c%20355%20§%2018[1995 c 355 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2036[1969 c 67 § 36]; ]

== 19.94.370 - Misleading wrappers, containers of packaged commodities—Standards of fill required.
No commodity in package form shall be so wrapped, nor shall it be in a container so made, formed or filled as to mislead the purchaser as to the quantity of the contents of the package, and the contents of a container shall not fall below such reasonable standards of fill as may have been prescribed by the director for the commodity in question.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2026[1992 c 237 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2037[1969 c 67 § 37]; ]

== 19.94.390 - Price not to be misleading, deceiving, misrepresented—Fractions—Examination procedure standard—Department may revise—Electronic scanner screen visibility.
. Whenever any commodity or service is sold, or is offered, exposed, or advertised for sale, by weight, measure, or count, the price shall not be misrepresented, nor shall the price be represented in any manner calculated or tending to mislead or deceive an actual or prospective purchaser. Whenever an advertised, posted or labeled price per unit of weight, measure, or count includes a fraction of a cent, all elements of the fraction shall be prominently displayed and the numeral or numerals expressing the fraction shall be immediately adjacent to, of the same general design and style as, and at least one-half the height and one-half the width of the numerals representing the whole cents.

. The examination procedure recommended for price verification by the price verification working group of the laws and regulations committee of the national conference on weights and measures (as reflected in the fourth draft, dated November 1, 1994) for devices such as electronic scanners shall govern such examinations conducted under this chapter. The procedure shall be deemed to be adopted under this chapter. However, the department may revise the procedure as follows: The department shall provide notice of and conduct a public hearing pursuant to chapter 34.05 RCW to determine whether any revisions to this procedure made by the national institute of standards and technology or its successor organization for incorporating the examination procedure into an official handbook of the institute or its successor, or any subsequent revisions of the handbook regarding such procedures shall also be adopted under this chapter. If the department determines that the procedure should be so revised, it may adopt the revisions. Violations of this section regarding the use of devices such as electronic scanners may be found only as provided by the examination procedures adopted by or under this subsection.

. Electronic scanner screens installed after January 1, 1996, and used in retail establishments must be visible to the consumer at the checkout line.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2400.SL.pdf?cite=2000%20c%20171%20§%2064[2000 c 171 § 64]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1524-S2.SL.pdf?cite=1995%20c%20355%20§%2020[1995 c 355 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2039[1969 c 67 § 39]; ]

== 19.94.400 - Meat, fish, poultry to be sold by weight—Exceptions.
Except for immediate consumption on the premises where sold or as one of several elements comprising a meal sold as a unit, for consumption elsewhere than on the premises where sold, all meat, meat products, fish and poultry offered or exposed for sale or sold as food, unless otherwise provided for by the laws of the state of Washington, shall be offered or exposed for sale and sold by weight.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2040[1969 c 67 § 40]; ]

== 19.94.410 - Butter, margarine to be sold by weight.
Butter, oleomargarine, and margarine offered for sale must be sold by weight.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1298-S.SL.pdf?cite=2019%20c%2096%20§%2013[2019 c 96 § 13]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1524-S2.SL.pdf?cite=1995%20c%20355%20§%2019[1995 c 355 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c63.pdf?cite=1988%20c%2063%20§%201[1988 c 63 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2041[1969 c 67 § 41]; ]

== 19.94.420 - Fluid dairy products to be packaged for retail sale in certain units.
All fluid dairy products, including but not limited to whole milk, skimmed milk, cultured milk, sweet cream, sour cream and buttermilk and all fluid imitation and fluid substitute dairy products shall be packaged for retail sale only in units as provided by the director of the department of agriculture by rule pursuant to the provisions of chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1856-S.SL.pdf?cite=1991%20sp.s.%20c%2023%20§%2017[1991 sp.s. c 23 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c51.pdf?cite=1975%201st%20ex.s.%20c%2051%20§%201[1975 1st ex.s. c 51 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2042[1969 c 67 § 42]; ]

== 19.94.430 - Packaged flour to be sold by weight.
When in package form and when packed, kept, offered, exposed for sale or sold, flour such as, but not limited to, wheat flour, whole wheat flour, graham flour, self-rising wheat flour, phosphated wheat flour, bromated flour, enriched flour, enriched self-rising flour, enriched bromated flour, corn flour, corn meal, and hominy grits must be sold by weight.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1298-S.SL.pdf?cite=2019%20c%2096%20§%2014[2019 c 96 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2043[1969 c 67 § 43]; ]

== 19.94.440 - Commodities sold in bulk—Delivery tickets.
. When a vehicle delivers to an individual purchaser a commodity in bulk, and the commodity is sold in terms of weight units, the delivery must be accompanied by a duplicate delivery ticket with the following information clearly stated, in ink or other indelible marking equipment and, in clarity, equal to type or printing: 

.. The name and address of the vendor;

.. The name and address of the purchaser; and 

.. The weight of the delivery expressed in pounds, and, if the weight is derived from determinations of gross and tare weights, such gross and tare weights also must be stated in terms of pounds.

. One of the delivery tickets shall be retained by the vendor, and the other shall be delivered to the purchaser at the time of delivery of the commodity, or shall be surrendered on demand to the director or the city sealer who, if he or she elects to retain it as evidence, shall issue a weight slip in lieu thereof for delivery to the purchaser.

. If the purchaser himself or herself carries away the purchase, the vendor shall be required only to give the purchaser at the time of sale a delivery ticket stating the number of pounds of commodity delivered.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2027[1992 c 237 § 27]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1856-S.SL.pdf?cite=1991%20sp.s.%20c%2023%20§%2018[1991 sp.s. c 23 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2044[1969 c 67 § 44]; ]

== 19.94.450 - Solid fuels to be sold by weight, cubic measure—Delivery tickets.
. Except as provided in subsection (2) of this section, all solid fuels such as, but not limited to, coal, coke, charcoal, broiler chips, pressed fuels and briquets shall be sold by weight.

. All solid fuels such as hogged fuel, sawdust and similar industrial fuels may be sold or purchased by cubic measure.

. Unless a fuel is delivered to the purchaser in package form, each delivery of such fuel to an individual purchaser must be accompanied by a duplicate delivery ticket with the following information clearly stated, in ink or other indelible marking equipment and, in clarity equal to type or printing:

.. The name and address of the vendor; 

.. The name and address of the purchaser; and 

.. The weight of the delivery and the gross and tare weights from which the weight is computed, each expressed in pounds.

. One of the delivery tickets shall be retained by the vendor and the other shall be delivered to the purchaser at the time of delivery of the fuel, or shall be surrendered, on demand, to the director or the city sealer who, if he or she elects to retain it as evidence, shall issue a weight slip in lieu thereof for delivery to the purchaser.

. If the purchaser himself or herself carries away the purchase, the vendor shall be required only to give to the purchaser at the time of sale a delivery ticket stating the number of pounds of fuel delivered.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2028[1992 c 237 § 28]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1856-S.SL.pdf?cite=1991%20sp.s.%20c%2023%20§%2019[1991 sp.s. c 23 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2045[1969 c 67 § 45]; ]

== 19.94.460 - Heating oils—Delivery tickets—Statements.
. All stove and furnace oil shall be sold by liquid measure or by weight in accordance with the provisions of RCW 19.94.340. 

. Unless such fuel is delivered to the purchaser in package form, each delivery of such fuel in an amount greater than ten gallons in the case of sale by liquid measure or one hundred pounds in the case of sale by weight must be accompanied by a delivery ticket or a written statement on which, in ink or other indelible substance, there shall be clearly and legibly stated:

.. The name and address of the vendor; 

.. The name and address of the purchaser; 

.. The identity of the type of fuel comprising the delivery; 

.. The unit price (that is, price per gallon or per pound, as the case may be), of the fuel delivered; 

.. In the case of sale by liquid measure, the liquid volume of the delivery together with any meter readings from which such liquid volume has been computed, expressed in terms of the gallon and its binary or decimal subdivisions; and 

.. In the case of sale by weight, the net weight of the delivery, together with any weighing scale readings from which such net weight has been computed, expressed in terms of tons or pounds avoirdupois.

. The delivery ticket required under this section must be delivered at the time of delivery unless an agreement, written or otherwise, between the vendor and the purchaser has been reached regarding the delivery of such delivery ticket.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2029[1992 c 237 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2046[1969 c 67 § 46]; ]

== 19.94.470 - Berries and small fruit.
Berries and small fruit shall be offered and exposed for sale and sold by weight, or by measure in open containers having capacities of one-half dry pint, one dry pint or one dry quart: PROVIDED, That the marking provisions of RCW 19.94.340 shall not apply to such dry volume containers.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2047[1969 c 67 § 47]; ]

== 19.94.480 - Fractional units as fractional value.
Fractional parts of any unit of weight or measure shall mean like fractional parts of the value of such unit as prescribed in RCW 19.94.150.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2030[1992 c 237 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2048[1969 c 67 § 48]; ]

== 19.94.485 - Contracts—Construction.
All contracts concerning the sale of commodities and services by weight, measure, or count, will be construed in accordance with the weights and measures adopted under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2031[1992 c 237 § 31]; ]

== 19.94.490 - Obstruction of director or sealer in performance of duties—Penalty.
Any person who hinders or obstructs in any way the director or a city sealer in the performance of official duties under this chapter is subject to a civil penalty up to five thousand dollars.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1298-S.SL.pdf?cite=2019%20c%2096%20§%2015[2019 c 96 § 15]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2032[1992 c 237 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2049[1969 c 67 § 49]; ]

== 19.94.500 - Impersonation of director or sealer—Penalty.
Any person who impersonates in any way the director or a city sealer, by using an official seal of approval without specific authorization to do so or by using a counterfeit seal of approval, or in any other manner, is subject to a civil penalty of no more than five thousand dollars per occurrence.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1298-S.SL.pdf?cite=2019%20c%2096%20§%2016[2019 c 96 § 16]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2033[1992 c 237 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2050[1969 c 67 § 50]; ]

== 19.94.507 - Gasoline delivered to service stations—Invoice required.
Persons delivering gasoline to retail service stations shall supply the station with an invoice which shall include the following information: (1) The gross volume of gasoline and the net volume of gasoline at sixty degrees Fahrenheit; (2) the time and temperature of the gasoline as loaded onto the delivery truck; and (3) the time of delivery to the retail service station.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c42.pdf?cite=1987%20c%2042%20§%202[1987 c 42 § 2]; ]

== 19.94.510 - Unlawful practices—Penalty.
. The acts or omissions under this section are violations of this chapter.

. Any person who, by himself or herself, by his or her agent or employee, or as the agent or employee of another person, performs any one of the acts enumerated in (a) through (l) of this subsection is subject to a civil penalty of no more than five thousand dollars per violation per occurrence:

.. Use or have in possession for the purpose of using for any commercial purpose a weighing or measuring instrument or device that is intentionally calculated to falsify any weight, measure, or count of any commodity, or to sell, offer, expose for sale or hire or have in possession for the purpose of selling or hiring an incorrect weighing or measuring instrument or device or any weighing or measuring instrument or device calculated to falsify any weight or measure.

.. Knowingly use or have in possession for current use in the buying or selling of any commodity or thing, for hire or award, or in the computation of any basic charge or payment for services rendered on the basis of weight, measurement, or count, or in the determination of weight, measurement or count, when a charge is made for such determination, any incorrect weighing or measuring instrument or device.

.. Dispose of any rejected weighing or measuring instrument or device in a manner contrary to law or rule.

.. Remove from any weighing or measuring instrument or device, contrary to law or rule, any tag, seal, stamp or mark placed thereon by the director or a city sealer.

.. Sell, offer or expose for sale less than the quantity he or she represents of any commodity, thing or service.

.. Take more than the quantity he or she represents of any commodity, thing, or service when, as buyer, he or she furnishes the weight, measure, or count by means of which the amount of the commodity, thing or service is determined.

.. Keep for the purpose of sale, advertise, offer or expose for sale or sell any commodity, thing or service known to be in a condition or manner contrary to law or rule.

.. Use in retail trade, except in the preparation of packages put up in advance of sale and of medical prescriptions, a weighing or measuring instrument or device that is not so positioned that its indications may be accurately read and the weighing or measuring operation observable from some position which may reasonably be assumed by a customer.

.. Knowingly approve or issue an official seal of approval for any weighing or measuring instrument or device known to be incorrect.

.. Find a weighing or measuring instrument or device to be correct under RCW 19.94.255 when the person knows the instrument or device is incorrect.

.. Fails to disclose to the department or a city sealer any knowledge of information relating to, or observation of, any device or instrument added to or modifying any weighing or measuring instrument or device for the purpose of selling, offering, or exposing for sale, less than the quantity represented of a commodity or calculated to falsify weight or measure, if the person is a service agent.

.. Violate any other provision of this chapter or of the rules adopted under the provisions of this chapter for which a specific penalty has not been prescribed.

. Any person who, by himself or herself, by his or her agent or employee, or as the agent or employee of another person, violates RCW 19.94.390 as determined by the examination procedure adopted by or under RCW 19.94.390(2) is subject to a civil penalty of no more than two thousand dollars per violation per occurrence.

. Any person who, by himself or herself, by his or her agent or employee, or as the agent or employee of another person, performs any of the following acts is subject to a civil penalty of no more than ten thousand dollars per violation per occurrence:

.. Knowingly adds to or modifies any weighing or measuring instrument or device by the addition of a device or instrument that would allow the sale, or the offering or exposure for sale, of less than the quantity represented of a commodity or falsification of weight or measure.

.. Commits as a fourth or subsequent violation any of the acts listed in subsection (2) or (3) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1298-S.SL.pdf?cite=2019%20c%2096%20§%2017[2019 c 96 § 17]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1524-S2.SL.pdf?cite=1995%20c%20355%20§%2021[1995 c 355 § 21]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2035[1992 c 237 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2051[1969 c 67 § 51]; ]

== 19.94.515 - Unlawful commercial use of instrument or device—Penalty.
A person who owns or uses a weighing or measuring instrument or device and uses or permits the use of the instrument for commercial purposes in violation of RCW 19.94.015 is subject to a civil penalty of one hundred dollars for each such instrument or device used or permitted to be used in violation of RCW 19.94.015.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1298-S.SL.pdf?cite=2019%20c%2096%20§%2018[2019 c 96 § 18]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1524-S2.SL.pdf?cite=1995%20c%20355%20§%2022[1995 c 355 § 22]; ]

== 19.94.517 - Incorrect commercial instrument or device to benefit of owner/operator—Penalties—Appeal.
. Whenever the department or a city sealer tests or inspects a weighing or measuring instrument or device and finds the instrument or device to be incorrect to the economic benefit of the owner/operator of the weighing or measuring instrument or device and to the economic detriment of the customer, the owner of the weighing or measuring instrument or device is subject to the following civil penalties:

Device deviations outside the tolerances stated in Handbook 44. PenaltySmall weighing or measuring instruments or devices: First violation . . . .$200.00 Second or subsequent violation within one year of first violation . . . .$500.00Medium weighing or measuring instruments or devices: First violation . . . .$400.00 Second or subsequent violation within one year of first violation . . . .$1,000.00Large weighing or measuring instruments or devices: First violation . . . .$500.00 Second or subsequent violation within one year of first violation . . . .$2,000.00

Device deviations outside the tolerances stated in Handbook 44.

 

Penalty

Small weighing or measuring instruments or devices:

 

First violation . . . .

$

200.00

 

Second or subsequent violation within one year of first violation . . . .

$

500.00

Medium weighing or measuring instruments or devices:

 

First violation . . . .

$

400.00

 

Second or subsequent violation within one year of first violation . . . .

$

1,000.00

Large weighing or measuring instruments or devices:

 

First violation . . . .

$

500.00

 

Second or subsequent violation within one year of first violation . . . .

$

2,000.00

. For the purposes of this section:

.. The following are small weighing or measuring instruments or devices: Scales of zero to four hundred pounds capacity, liquid fuel metering devices with flows of not more than twenty gallons per minute, liquid petroleum gas meters with one inch in diameter or smaller dispensers, fabric meters, cordage meters, and taxi meters.

.. The following are medium weighing or measuring instruments or devices: Scales of four hundred one to five thousand pounds capacity, liquid fuel metering devices with flows of more than twenty but not more than one hundred fifty gallons per minute, and mass flow meters.

.. The following are large weighing or measuring instruments or devices: Liquid petroleum gas meters with greater than one inch diameter dispensers, liquid fuel metering devices with flows over one hundred fifty gallons per minute, and scales of more than five thousand pounds capacity and scales of more than five thousand pounds capacity with supplemental devices.

. The weighing or measuring instrument or device owner may appeal the civil penalty.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1298-S.SL.pdf?cite=2019%20c%2096%20§%2019[2019 c 96 § 19]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1524-S2.SL.pdf?cite=1995%20c%20355%20§%2023[1995 c 355 § 23]; ]

== 19.94.520 - Injunction against violations.
The director is authorized to apply to any court of competent jurisdiction for, and such court upon hearing and for cause shown may grant, a temporary or permanent injunction restraining any person from violating any provision of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2052[1969 c 67 § 52]; ]

== 19.94.530 - Proof of existence of weighing or measuring instrument or device presumed proof of regular use.
For the purposes of this chapter, proof of the existence of a weighing or measuring instrument or device in or about any building, enclosure, stand, or vehicle in which or from which it is shown that buying or selling is commonly carried on, shall, in the absence of conclusive evidence to the contrary, be presumptive proof of the regular use of such weighing or measuring instrument or device for commercial purposes and of such use by the person in charge of such building, enclosure, stand or vehicle.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2036[1992 c 237 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2053[1969 c 67 § 53]; ]

== 19.94.540 - Antifreeze products—Use of aversive agent.
. Any engine coolant or antifreeze manufactured or distributed in the state of Washington after January 1, 2010, that contains more than ten percent ethylene glycol shall contain denatonium benzoate at a minimum of thirty parts per million and a maximum of fifty parts per million as an aversive agent so as to render the product unpalatable.

. The requirements of this section apply to manufacturers, packagers, distributors, recyclers, or sellers of engine coolant or antifreeze, but not to those who install engine coolant or antifreeze for compensation.

. A manufacturer of a product subject to this section and RCW 19.94.542 and 19.94.544 shall maintain a record of the trade name, scientific name, and active ingredients of any aversive used under this section. The manufacturer shall make this information available to the public upon request.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2996-S.SL.pdf?cite=2008%20c%2068%20§%201[2008 c 68 § 1]; ]

== 19.94.542 - Antifreeze products—Aversive agents—Limitation of liability.
. A manufacturer, packager, distributor, recycler, or seller of an engine coolant or antifreeze that is required to contain an aversive agent as required by RCW 19.94.540 shall not be liable for any personal injury, death, property damage, damage to the environment or a natural resource, or economic loss that results from the inclusion of denatonium benzoate in engine coolant or antifreeze.

. The limitation of liability provided in subsection (1) of this section does not apply to a particular liability that is not caused or is unrelated to the inclusion of denatonium benzoate in engine coolant or antifreeze.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2996-S.SL.pdf?cite=2008%20c%2068%20§%202[2008 c 68 § 2]; ]

== 19.94.544 - Antifreeze products—Aversive agents—Application.
The requirements of this section and RCW 19.94.540 and 19.94.542 shall not apply to the sale of a motor vehicle that contains engine coolant or antifreeze.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1095.SL.pdf?cite=2018%20c%20198%20§%201[2018 c 198 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2996-S.SL.pdf?cite=2008%20c%2068%20§%203[2008 c 68 § 3]; ]

== 19.94.900 - Chapter cumulative and nonexclusive.
The provisions of this chapter shall be cumulative and nonexclusive and shall not affect any other remedy available at law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c67.pdf?cite=1969%20c%2067%20§%2054[1969 c 67 § 54]; ]

== 19.94.920 - Effective date—1992 c 237.
This act shall take effect July 1, 1992.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6483-S.SL.pdf?cite=1992%20c%20237%20§%2041[1992 c 237 § 41]; ]

