= 19.162 - Pay-per-call information delivery services.
:toc:

== 19.162.010 - Application of consumer protection act—Scope.
. The legislature finds that the deceptive use of pay-per-call information delivery services is a matter vitally affecting the public interest for the purpose of applying the consumer protection act, chapter 19.86 RCW.

. The deceptive use of pay-per-call information delivery services is not reasonable in relation to the development and preservation of business. A violation of this chapter is an unfair or deceptive act in trade or commerce for the purpose of applying the consumer protection act, chapter 19.86 RCW, and constitutes an act of deceptive pay-per-call information delivery service.

. This chapter applies to a communication made by a person in Washington or to a person in Washington.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=1991%20c%20191%20§%201[1991 c 191 § 1]; ]

== 19.162.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Person" means an individual, corporation, the state or its subdivisions or agencies, business trust, estate, trust, partnership, association, cooperative, or any other legal entity.

. "Information delivery services" means telephone-recorded messages, interactive programs, or other information services that are provided for a charge to a caller through an exclusive telephone number prefix or service access code.

. "Information provider" means the person who provides the information, prerecorded message, or interactive program for the information delivery service. The information provider generally receives a portion of the revenue from the calls. "Information provider" does not include the medium for advertising information delivery services.

. "Interactive program" means a program that allows an information delivery service caller, once connected to the information provider's delivery service, to use the caller's telephone device to access more specific information or further information or to talk to other callers during the call.

. "Telecommunications company" includes every corporation, company, association, joint stock association, partnership, and person, their lessees, trustees, or receivers appointed by any court whatsoever, and every city or town owning, operating, or managing any facilities used to provide telecommunications for hire, sale, or resale to the general public within the state of Washington.

. "Interexchange carrier" means a carrier providing transmissions between local access and transport areas interstate or intrastate.

. "Billing services" means billing and collection services provided to information providers whether by the local exchange company or the interexchange carrier.

. "Program message" means the information that a caller hears or receives upon placing a call to an information provider.

. "Advertisement" includes all radio, television, or other broadcast, video, newspaper, magazine, or publication, billboard, direct mail, print media, telemarketing, or any promotion of an information delivery service, program, or number, and includes brochures, pamphlets, fliers, coupons, promotions, or the labeling of products or in-store communications circulated or distributed in any manner whatsoever. "Advertisement" does not include any listing in a white page telephone directory. In a yellow page telephone directory, "advertisement" includes only yellow page display advertising.

. "Subscriber" means the person in whose name an account is billed.

. "Does business in Washington" includes providing information delivery services to Washington citizens, advertising information delivery services in Washington, entering into a contract for billing services in Washington, entering into a contract in Washington with a telecommunications company or interexchange carrier for transmission services, or having a principal place of business in Washington.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=1991%20c%20191%20§%202[1991 c 191 § 2]; ]

== 19.162.030 - Program message preamble.
. An information provider that does business in Washington must include a preamble in all program messages for:

.. Programs costing more than five dollars per minute; or

.. Programs having a total potential cost of greater than ten dollars.

. The preamble must:

.. Accurately describe the service that will be provided by the program;

.. Advise the caller of the price of the call, including:

... Any per minute charge;

... Any flat rate charge; and

... Any minimum charge;

.. State that billing will begin shortly after the end of the introductory message; and

.. Be clearly articulated, at a volume equal to that of the program message, in plain English or the language used to promote the information delivery service, and spoken in a normal cadence.

. Mechanisms that provide for the option of bypassing the preamble are only permitted when:

.. The caller has made use of the information provider's service in the past, at which time the preamble required by this section was part of the program message; and

.. The cost of the call has not changed during the thirty-day period before the call.

. When an information provider's program message consists of a polling application that permits the caller to register an opinion or vote on a matter by completing a call, this section does not apply.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=1991%20c%20191%20§%203[1991 c 191 § 3]; ]

== 19.162.040 - Advertisement of services.
An information provider that does business in Washington shall comply with the following provisions in its advertisement of information delivery services:

. Advertisements for information delivery services that are broadcast by radio or television, contained in home videos, or that appear on movie screens must include a voice-over announcement that is clearly audible and articulates the price of the service provided. The announcement must be made at a volume equal to that used to announce the telephone number, spoken in a normal cadence, and in plain English or the language used in the advertisement.

. Advertisements for information delivery services that are broadcast by television, contained in home videos, or that appear on movie screens must include, in clearly visible letters and numbers, the cost of calling the advertised number. This visual disclosure of the cost of the call must be displayed adjacent to the number to be called whenever the number is shown in the advertisement, and the lettering of the visual disclosure of the cost must be in the same size and typeface as that of the number to be called.

. [Empty]
.. Except as otherwise provided in (b) of this subsection, advertisements for information delivery services that appear in print must include, in clearly visible letters and numbers, the cost of calling the advertised number. The printed disclosure of the cost of the call must be displayed adjacent to the number to be called wherever the number is shown in the advertisement.

.. In telephone directory yellow page display advertising and in printed materials published not more than three times a year, instead of disclosing the cost of the service, advertisements for information delivery services, shall include the conspicuous disclosure that the call is a pay-per-call service.

. The advertised price or cost of the information delivery service must include:

.. Any per minute charge;

.. Any flat rate charge; and

.. Any minimum charge.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=1991%20c%20191%20§%204[1991 c 191 § 4]; ]

== 19.162.050 - Services directed at children.
An information provider that does business in the state of Washington shall not direct information delivery services to children under the age of twelve years unless the information provider complies with the following provisions:

. Interactive calls where children under the age of twelve years can speak to other children under the age of twelve years are prohibited.

. Programs directed to children under the age of twelve where the children are asked to provide their names, addresses, telephone numbers, or other identifying information are prohibited.

. Advertisements for information delivery services that are directed to children under the age of twelve years must contain a visual disclosure that clearly and conspicuously in the case of print and broadcast advertising, and audibly in the case of broadcast advertising, states that children under the age of twelve years must obtain parental consent before placing a call to the advertised number.

. Program messages that encourage children under the age of twelve years to make increased numbers of calls in order to obtain progressively more valuable prizes, awards, or similarly denominated items are prohibited.

. Advertisements for information delivery services that are directed to children under the age of twelve years must contain, in age-appropriate language, an accurate description of the services being provided. In the case of print advertising, the information must be clear and conspicuous and in the case of broadcast advertising, it must be visually displayed clearly and conspicuously and verbally disclosed in an audible, clearly articulated manner.

. Program messages that are directed to children under the age of twelve years that employ broadcast advertising where an electronic tone signal is emitted during the broadcast of the advertisement that automatically dials the program message are prohibited.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=1991%20c%20191%20§%205[1991 c 191 § 5]; ]

== 19.162.060 - Nonpayment of charges.
An information provider's failure to substantially comply with any of the provisions of RCW 19.162.030 through 19.162.050 is a defense to the nonpayment of charges accrued as a result of using the information provider's services, billed by any entity, including but not limited to telecommunications companies and interexchange carriers.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=1991%20c%20191%20§%206[1991 c 191 § 6]; ]

== 19.162.070 - Violations—Action for damages.
A person who suffers damage from a violation of this chapter may bring an action against an information provider. In an action alleging a violation of this chapter, the court may award the greater of three times the actual damages sustained by the person or five hundred dollars; equitable relief, including but not limited to an injunction and restitution of money and property; attorneys' fees and costs; and any other relief that the court deems proper. For purposes of this section, a telecommunications company or interexchange carrier is a person.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5518-S.SL.pdf?cite=1991%20c%20191%20§%207[1991 c 191 § 7]; ]

