= 19.146 - Mortgage broker practices act.
:toc:

== 19.146.005 - Findings and declaration.
The legislature finds and declares that the brokering of residential real estate loans substantially affects the public interest, requiring that all actions in mortgage brokering be actuated by good faith, and that mortgage brokers, designated brokers, loan originators, and other persons subject to this chapter abstain from deception, and practice honesty and equity in all matters relating to their profession. The practices of mortgage brokers and loan originators have had significant impact on the citizens of the state and the banking and real estate industries. It is the intent of the legislature to establish a state system of licensure in addition to rules of practice and conduct of mortgage brokers and loan originators to promote honesty and fair dealing with citizens and to preserve public confidence in the lending and real estate community.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2770-S.SL.pdf?cite=2008%20c%20108%20§%2021[2008 c 108 § 21]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2340.SL.pdf?cite=2006%20c%2019%20§%201[2006 c 19 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%201[1994 c 33 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=1993%20c%20468%20§%201[1993 c 468 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c391.pdf?cite=1987%20c%20391%20§%201[1987 c 391 § 1]; ]

== 19.146.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Affiliate" means any person who directly or indirectly through one or more intermediaries, controls, or is controlled by, or is under common control with another person.

. "Borrower" means any person who consults with or retains a mortgage broker or loan originator in an effort to obtain or seek advice or information on obtaining or applying to obtain a residential mortgage loan, or a residential mortgage loan modification, for himself, herself, or persons including himself or herself, regardless of whether the person actually obtains such a loan.

. "Computer loan information systems" or "CLI system" means a real estate mortgage financing information system that facilitates the provision of information to consumers by a mortgage broker, loan originator, lender, real estate agent, or other person regarding interest rates and other loan terms available from different lenders.

. "Department" means the state department of financial institutions.

. "Designated broker" means an individual designated as the person responsible for activities of the licensed mortgage broker in conducting the business of a mortgage broker under this chapter and who meets the experience and examination requirements set forth in RCW 19.146.210(1)(e).

. "Director" means the director of financial institutions.

. "Employee" means an individual who has an employment relationship with a mortgage broker, and the individual is treated as an employee by the mortgage broker for purposes of compliance with federal income tax laws.

. "Federal banking agencies" means the board of governors of the federal reserve system, comptroller of the currency, director of the office of thrift supervision, national credit union administration, and federal deposit insurance corporation.

. "License" means a single license issued under the authority of this chapter.

. "Licensee" means a person to whom one or more licenses have been issued. "Licensee" also means any person, whether located within or outside of this state, who fails to obtain a license required by this chapter.

. [Empty]
.. "Loan originator" means an individual who for direct or indirect compensation or gain, or in the expectation of direct or indirect compensation or gain (i) takes a residential mortgage loan application, or (ii) offers or negotiates terms of a residential mortgage loan. "Loan originator" also includes a person who holds themselves out to the public as able to perform any of these activities. "Loan originator" does not mean persons performing purely administrative or clerical tasks for a mortgage broker. For the purposes of this subsection, "administrative or clerical tasks" means the receipt, collection, and distribution of information common for the processing of a loan in the mortgage industry and communication with a borrower to obtain information necessary for the processing of a residential mortgage loan. A person who holds himself or herself out to the public as able to obtain a residential mortgage loan is not performing administrative or clerical tasks.

.. "Loan originator" also includes an individual who for direct or indirect compensation or gain or in the expectation of direct or indirect compensation or gain performs residential mortgage loan modification services or holds himself or herself out as being able to perform residential mortgage loan modification services.

.. "Loan originator" does not include a person or entity that only performs real estate brokerage activities and is licensed or registered in accordance with applicable state law, unless the person or entity is compensated by a lender, a mortgage broker, or other mortgage loan originator or by any agent of such a lender, mortgage broker, or other mortgage loan originator. For purposes of this chapter, the term "real estate brokerage activity" means any activity that involves offering or providing real estate brokerage services to the public, including:

... Acting as a real estate agent or real estate broker for a buyer, seller, lessor, or lessee of real property;

... Bringing together parties interested in the sale, purchase, lease, rental, or exchange of real property;

... Negotiating, on behalf of any party, any portion of a contract relating to the sale, purchase, lease, rental, or exchange of real property, other than in connection with providing financing with respect to such a transaction;

... Engaging in any activity for which a person engaged in the activity is required to be registered or licensed as a real estate agent or real estate broker under any applicable law; and

.. Offering to engage in any activity, or act in any capacity, described in (c)(i) through (iv) of this subsection.

.. "Loan originator" does not include a person or entity solely involved in extensions of credit relating to timeshare plans, as that term is defined in section 101(53D) of Title 11, United States Code.

.. This subsection does not apply to employees of a housing counseling agency approved by the United States department of housing and urban development unless the employees of a housing counseling agency are required under federal law to be licensed individually as loan originators.

. "Loan processor" means an individual who performs clerical or support duties as an employee at the direction of and subject to the supervision and instruction of a person licensed, or exempt from licensing, under this chapter.

. "Lock-in agreement" means an agreement with a borrower made by a mortgage broker or loan originator, in which the mortgage broker or loan originator agrees that, for a period of time, a specific interest rate or other financing terms will be the rate or terms at which it will make a residential mortgage loan available to that borrower.

. "Mortgage broker" means any person who for direct or indirect compensation or gain, or in the expectation of direct or indirect compensation or gain (a) assists a person in obtaining or applying to obtain a residential mortgage loan or performs residential mortgage loan modification services or (b) holds himself or herself out as being able to assist a person in obtaining or applying to obtain a residential mortgage loan or provide residential mortgage loan modification services.

. "Mortgage loan originator" has the same meaning as "loan originator."

. "Nationwide mortgage licensing system and registry" means a mortgage licensing system developed and maintained by the conference of state bank supervisors for licensing and registration.

. "Person" means an individual, corporation, company, limited liability company, partnership, association, and all other legal entities.

. "Principal" means any person who controls, directly or indirectly through one or more intermediaries, or alone or in concert with others, a ten percent or greater interest in a partnership, company, association, corporation, limited liability company, and the owner of a sole proprietorship.

. "Residential mortgage loan" means any loan primarily for personal, family, or household use secured by a mortgage, deed of trust or other consensual security interest on a dwelling as defined in the truth in lending act, or residential real estate upon which is constructed or intended to be constructed a dwelling.

. "Residential mortgage loan modification" means a change in one or more of a residential mortgage loan's terms or conditions. Changes to a residential mortgage loan's terms or conditions include but are not limited to forbearances; repayment plans; changes in interest rates, loan terms, or loan types; capitalizations of arrearages; or principal reductions.

. "Residential mortgage loan modification services" includes negotiating, attempting to negotiate, arranging, attempting to arrange, or otherwise offering to perform a residential mortgage loan modification. "Residential mortgage loan modification services" also includes the collection of data for submission to any entity performing mortgage loan modification services.

. "S.A.F.E. act" means the secure and fair enforcement for mortgage licensing act of 2008, or Title V of the housing and economic recovery act of 2008 ("HERA"), P.L. 110-289, effective July 30, 2008, codified at 12 U.S.C. Sec. 5101 et seq.

. "Third-party provider" means any person other than a mortgage broker or lender who provides goods or services to the mortgage broker in connection with the preparation of the borrower's residential mortgage loan and includes, but is not limited to, credit reporting agencies, title companies, appraisers, structural and pest inspectors, or escrow companies.

. "Third-party residential mortgage loan modification services" means residential mortgage loan modification services offered or performed by any person other than the owner or servicer of the loan.

. "Unique identifier" means a number or other identifier assigned by protocols established by the nationwide mortgage licensing system and registry.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5299-S.SL.pdf?cite=2015%20c%20229%20§%205[2015 c 229 § 5]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5210-S.SL.pdf?cite=2013%20c%2030%20§%201[2013 c 30 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2608.SL.pdf?cite=2010%20c%2035%20§%2013[2010 c 35 § 13]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1749-S.SL.pdf?cite=2009%20c%20528%20§%201[2009 c 528 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6471.SL.pdf?cite=2008%20c%2078%20§%203[2008 c 78 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2340.SL.pdf?cite=2006%20c%2019%20§%202[2006 c 19 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1678-S.SL.pdf?cite=1997%20c%20106%20§%201[1997 c 106 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%203[1994 c 33 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=1993%20c%20468%20§%202[1993 c 468 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c391.pdf?cite=1987%20c%20391%20§%203[1987 c 391 § 3]; ]

== 19.146.020 - Exemptions from chapter.
. The following are exempt from all provisions of this chapter:

.. Any person doing business under the laws of the state of Washington or the United States, and any federally insured depository institution doing business under the laws of any other state, relating to commercial banks, bank holding companies, savings banks, trust companies, savings and loan associations, credit unions, insurance companies, or real estate investment trusts as defined in 26 U.S.C. Sec. 856 and the affiliates, subsidiaries, and service corporations thereof;

.. Any person doing business under the consumer loan act is exempt from this chapter only for that business conducted under the authority and coverage of the consumer loan act;

.. An attorney licensed to practice law in this state. However, (i) all mortgage broker or loan originator services must be performed by the attorney while engaged in the practice of law; (ii) all mortgage broker or loan originator services must be performed under a business that is publicly identified and operated as a law practice; and (iii) all funds associated with the transaction and received by the attorney must be deposited in, maintained in, and disbursed from a trust account to the extent required by rules enacted by the Washington supreme court regulating the conduct of attorneys;

.. Any person doing any act under order of any court, except for a person subject to an injunction to comply with any provision of this chapter or any order of the director issued under this chapter;

.. A real estate broker or salesperson licensed by the state who obtains financing for a real estate transaction involving a bona fide sale of real estate in the performance of his or her duties as a real estate broker and who receives only the customary real estate broker's or salesperson's commission in connection with the transaction;

.. The United States of America, the state of Washington, any other state, and any Washington city, county, or other political subdivision, and any agency, division, or corporate instrumentality of any of the entities in this subsection (1)(f);

.. A real estate broker who provides only information regarding rates, terms, and lenders in connection with a CLI system, who receives a fee for providing such information, who conforms to all rules of the director with respect to the providing of such service, and who discloses on a form approved by the director that to obtain a loan the borrower must deal directly with a mortgage broker or lender. However, a real estate broker shall not be exempt if he or she does any of the following:

... Holds himself or herself out as able to obtain a loan from a lender;

... Accepts a loan application, or submits a loan application to a lender;

... Accepts any deposit for third-party services or any loan fees from a borrower, whether such fees are paid before, upon, or after the closing of the loan;

... Negotiates rates or terms with a lender on behalf of a borrower; or

.. Provides the disclosure required by RCW 19.146.030(1);

.. Registered mortgage loan originators, or any individual required to be registered;

.. A manufactured or modular home retailer employee who performs purely administrative or clerical tasks and who receives only the customary salary or commission from the employer in connection with the transaction; and

.. Nonprofit housing organizations brokering residential mortgage loans under housing programs that are funded in whole or in part by federal or state programs if the primary purpose of the programs is to assist low-income borrowers with purchasing, repairing, or otherwise providing housing for low-income Washington state residents.

. Any person otherwise exempted from the licensing provisions of this chapter may voluntarily submit an application to the director for a mortgage broker's license. The director shall review such application and may grant or deny licenses to such applicants upon the same grounds and with the same fees as may be applicable to persons required to be licensed under this chapter.

.. Upon receipt of a license under this subsection, the licensee is required to continue to maintain a valid license, is subject to all provisions of this chapter, and has no further right to claim exemption from the provisions of this chapter except as provided in (b) of this subsection.

.. Any licensee under this subsection who would otherwise be exempted from the requirements of licensing by this section may apply to the director for exemption from licensing. The director shall adopt rules for reviewing such applications and shall grant exemptions from licensing to applications which are consistent with those rules and consistent with the other provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5299-S.SL.pdf?cite=2015%20c%20229%20§%206[2015 c 229 § 6]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5210-S.SL.pdf?cite=2013%20c%2030%20§%202[2013 c 30 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1749-S.SL.pdf?cite=2009%20c%20528%20§%202[2009 c 528 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2340.SL.pdf?cite=2006%20c%2019%20§%203[2006 c 19 § 3]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1678-S.SL.pdf?cite=1997%20c%20106%20§%202[1997 c 106 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%205[1994 c 33 § 5]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%204[1994 c 33 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=1993%20c%20468%20§%203[1993 c 468 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c391.pdf?cite=1987%20c%20391%20§%204[1987 c 391 § 4]; ]

== 19.146.0201 - Loan originator, mortgage broker—Prohibitions—Requirements.
It is a violation of this chapter for loan originators, mortgage brokers, officers, directors, employees, independent contractors, or any other person subject to this chapter to:

. Directly or indirectly employ any scheme, device, or artifice to defraud or mislead borrowers or lenders or to defraud any person;

. Directly or indirectly engage in any unfair or deceptive practice toward any person;

. Directly or indirectly obtain property by fraud or misrepresentation;

. Solicit or enter into a contract with a borrower that provides in substance that the mortgage broker may earn a fee or commission through the mortgage broker's "best efforts" to obtain a loan even though no loan is actually obtained for the borrower;

. Solicit, advertise, or enter into a contract for specific interest rates, points, or other financing terms unless the terms are actually available at the time of soliciting, advertising, or contracting from a person exempt from licensing under RCW 19.146.020(1)(f) or a lender with whom the mortgage broker maintains a written correspondent or loan broker agreement under RCW 19.146.040;

. Fail to make disclosures to loan applicants and noninstitutional investors as required by RCW 19.146.030 and any other applicable state or federal law;

. Make, in any manner, any false or deceptive statement or representation with regard to the rates, points, or other financing terms or conditions for a residential mortgage loan or engage in bait and switch advertising;

. Negligently make any false statement or knowingly and willfully make any omission of material fact in connection with any reports filed by a licensee or in connection with any investigation conducted by the department;

. Make any payment, directly or indirectly, to any appraiser of a property, for the purposes of influencing the independent judgment of the appraiser with respect to the value of the property;

. Advertise any rate of interest without conspicuously disclosing the annual percentage rate implied by such rate of interest;

. Fail to comply with state and federal laws applicable to the activities governed by this chapter;

. Fail to pay third-party providers no later than thirty days after the recording of the loan closing documents or ninety days after completion of the third-party service, whichever comes first, unless otherwise agreed or unless the third-party service provider has been notified in writing that a bona fide dispute exists regarding the performance or quality of the third-party service;

. Collect, charge, attempt to collect or charge or use or propose any agreement purporting to collect or charge any fee prohibited by RCW 19.146.030 or 19.146.070;

. [Empty]
.. Except when complying with (b) and (c) of this subsection, act as a loan originator in any transaction (i) in which the loan originator acts or has acted as a real estate broker or salesperson or (ii) in which another person doing business under the same licensed real estate broker acts or has acted as a real estate broker or salesperson;

.. Prior to providing mortgage services to the borrower, a loan originator, in addition to other disclosures required by this chapter and other laws, must provide to the borrower the following written disclosure:

THIS IS TO GIVE YOU NOTICE THAT I OR ONE OF MY ASSOCIATES HAVE/HAS ACTED AS A REAL ESTATE BROKER OR SALESPERSON REPRESENTING THE BUYER/SELLER IN THE SALE OF THIS PROPERTY TO YOU. I AM ALSO A LOAN ORIGINATOR, AND WOULD LIKE TO PROVIDE MORTGAGE SERVICES TO YOU IN CONNECTION WITH YOUR LOAN TO PURCHASE THE PROPERTY.

YOU ARE NOT REQUIRED TO USE ME AS A LOAN ORIGINATOR IN CONNECTION WITH THIS TRANSACTION. YOU ARE FREE TO COMPARISON SHOP WITH OTHER MORTGAGE BROKERS AND LENDERS, AND TO SELECT ANY MORTGAGE BROKER OR LENDER OF YOUR CHOOSING; and

.. A real estate broker or salesperson licensed under chapter 18.85 RCW who also acts as a mortgage broker must carry on such mortgage broker business activities and must maintain such person's mortgage broker business records separate and apart from the real estate broker activities conducted pursuant to chapter 18.85 RCW. Such activities are separate and apart even if they are conducted at an office location with a common entrance and mailing address, so long as each business is clearly identified by a sign visible to the public, each business is physically separated within the office facility, and no deception of the public as to the separate identities of the broker business firms results. This subsection (14)(c) does not require a real estate broker or salesperson licensed under chapter 18.85 RCW who also acts as a mortgage broker to maintain a physical separation within the office facility for the conduct of its real estate and mortgage broker activities where the director determines that maintaining such physical separation would constitute an undue financial hardship upon the mortgage broker and is unnecessary for the protection of the public;

. Fail to comply with any provision of RCW 19.146.030 through 19.146.080 or any rule adopted under those sections;

. Originate loans from any unlicensed location. It is not a violation for a licensed mortgage loan originator to originate loans from an unlicensed location if that location is the licensed mortgage loan originator's residence and the licensed mortgage loan originator and licensed sponsoring company comply with RCW 19.146.265;

. Solicit or accept from any borrower at or near the time a loan application is taken, and in advance of any foreclosure of the borrower's existing residential mortgage loan or loans, any instrument of conveyance of any interest in the borrower's primary dwelling that is the subject of the residential mortgage loan or loans; or

. Make a residential mortgage loan unless the loan is table funded.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5077.SL.pdf?cite=2021%20c%2015%20§%203[2021 c 15 § 3]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5299-S.SL.pdf?cite=2015%20c%20229%20§%207[2015 c 229 § 7]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5210-S.SL.pdf?cite=2013%20c%2030%20§%203[2013 c 30 § 3]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1749-S.SL.pdf?cite=2009%20c%20528%20§%203[2009 c 528 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2340.SL.pdf?cite=2006%20c%2019%20§%204[2006 c 19 § 4]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1678-S.SL.pdf?cite=1997%20c%20106%20§%203[1997 c 106 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%206[1994 c 33 § 6]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=1993%20c%20468%20§%204[1993 c 468 § 4]; ]

== 19.146.030 - Written disclosure of fees and costs—Rules—Contents—Lock-in agreement terms—Excess fees limited.
. Within three business days following receipt of a loan application from a borrower, a mortgage broker or loan originator must provide to the borrower a full written disclosure containing an itemization and explanation of all fees and costs that the borrower is required to pay in connection with obtaining a residential mortgage loan, and specifying the fee or fees which inure to the benefit of the mortgage broker and other such disclosures as may be required by rule. A good faith estimate of a fee or cost must be provided if the exact amount of the fee or cost is not determinable.

. The written disclosure must contain the following information:

.. The annual percentage rate, finance charge, amount financed, total amount of all payments, number of payments, amount of each payment, amount of points or prepaid interest and the conditions and terms under which any loan terms may change between the time of disclosure and closing of the loan; and if a variable rate, the circumstances under which the rate may increase, any limitation on the increase, the effect of an increase, and an example of the payment terms resulting from an increase. Disclosure in compliance with the requirements of the truth in lending act, 15 U.S.C. Sec. 1601 and Regulation Z, 12 C.F.R. Part 1026, as now or hereafter amended, is in compliance with the disclosure requirements of this subsection;

.. The itemized costs of any credit report, appraisal, title report, title insurance policy, mortgage insurance, escrow fee, property tax, insurance, structural or pest inspection, and any other third-party provider's costs associated with the residential mortgage loan. Disclosure through good faith estimates of settlement services and special information booklets in compliance with the requirements of the real estate settlement procedures act, 12 U.S.C. Sec. 2601, and Regulation X, 24 C.F.R. Part 1024, as now or hereafter amended, is in compliance with the disclosure requirements of this subsection;

.. If applicable, the cost, terms, duration, and conditions of a lock-in agreement and whether a lock-in agreement has been entered, and whether the lock-in agreement is guaranteed by the mortgage broker or lender, and if a lock-in agreement has not been entered, disclosure in a form acceptable to the director that the disclosed interest rate and terms are subject to change;

.. If applicable, a statement that if the borrower is unable to obtain a loan for any reason, the mortgage broker must, within five days of a written request by the borrower, give copies of any appraisal, title report, or credit report paid for by the borrower to the borrower, and transmit the appraisal, title report, or credit report to any other mortgage broker or lender to whom the borrower directs the documents to be sent;

.. Whether and under what conditions any lock-in fees are refundable to the borrower; and

.. A statement providing that moneys paid by the borrower to the mortgage broker for third-party provider services are held in a trust account and any moneys remaining after payment to third-party providers will be refunded.

. If subsequent to the written disclosure being provided under this section, a mortgage broker or loan originator enters into a lock-in agreement with a borrower or represents to the borrower that the borrower has entered into a lock-in agreement, then no less than three business days thereafter including Saturdays, the mortgage broker or loan originator must deliver or send by first-class mail to the borrower a written confirmation of the terms of the lock-in agreement, which must include a copy of the disclosure made under subsection (2)(c) of this section.

. A mortgage broker or loan originator on behalf of a mortgage broker must not charge any fee that inures to the benefit of the mortgage broker if it exceeds the fee disclosed on the written disclosure pursuant to this section, unless (a) the need to charge the fee was not reasonably foreseeable at the time the written disclosure was provided and (b) the mortgage broker or loan originator on behalf of a mortgage broker has provided to the borrower, no less than three business days prior to the signing of the loan closing documents, a clear written explanation of the fee and the reason for charging a fee exceeding that which was previously disclosed. However, if the borrower's closing costs on the final settlement statement, excluding prepaid escrowed costs of ownership as defined by rule, does not exceed the total closing costs in the most recent good faith estimate, excluding prepaid escrowed costs of ownership as defined by rule, no other disclosures are required by this subsection.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5299-S.SL.pdf?cite=2015%20c%20229%20§%208[2015 c 229 § 8]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2340.SL.pdf?cite=2006%20c%2019%20§%205[2006 c 19 § 5]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1678-S.SL.pdf?cite=1997%20c%20106%20§%204[1997 c 106 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%2018[1994 c 33 § 18]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=1993%20c%20468%20§%2012[1993 c 468 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c391.pdf?cite=1987%20c%20391%20§%205[1987 c 391 § 5]; ]

== 19.146.040 - Written contract required—Contract entered by loan originator binding on mortgage broker—Written loan broker agreement required.
. Every contract between a mortgage broker, or a loan originator, and a borrower must be in writing and contain the entire agreement of the parties.

. Any contract under this section entered by a loan originator is binding on the mortgage broker.

. A mortgage broker must have a written loan broker agreement with a lender before any solicitation of, or contracting with, the public.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5299-S.SL.pdf?cite=2015%20c%20229%20§%209[2015 c 229 § 9]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2340.SL.pdf?cite=2006%20c%2019%20§%206[2006 c 19 § 6]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%2019[1994 c 33 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c391.pdf?cite=1987%20c%20391%20§%206[1987 c 391 § 6]; ]

== 19.146.050 - Moneys for third-party provider services deemed in trust—Deposit of moneys in trust account—Use of trust account—Rules—Tax treatment.
. All moneys received by a mortgage broker from a borrower for payment of third-party provider services shall be deemed as held in trust immediately upon receipt by the mortgage broker. A mortgage broker shall deposit, prior to the end of the third business day following receipt of such trust funds, all such trust funds in a trust account of a federally insured financial institution located in this state. All trust account funds collected under this chapter must remain on deposit in a trust account in the state of Washington until disbursement. The trust account shall be designated and maintained for the benefit of borrowers. Moneys maintained in the trust account shall be exempt from execution, attachment, or garnishment. A mortgage broker shall not in any way encumber the corpus of the trust account or commingle any other operating funds with trust account funds. Withdrawals from the trust account shall be only for the payment of bona fide services rendered by a third-party provider or for refunds to borrowers.

. The director shall make rules which: (a) Direct mortgage brokers how to handle checks and other instruments that are received by the broker and that combine trust funds with other funds; and (b) permit transfer of trust funds out of the trust account for payment of other costs only when necessary and only with the prior express written permission of the borrower.

. Any interest earned on the trust account shall be refunded or credited to the borrowers at closing.

. Trust accounts that are operated in a manner consistent with this section and any rules adopted by the director, are not considered gross receipts taxable under chapter 82.04 RCW.

. A person violating this section is guilty of a class C felony punishable according to chapter 9A.20 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20158[2003 c 53 § 158]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2315-S.SL.pdf?cite=1998%20c%20311%20§%201[1998 c 311 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1678-S.SL.pdf?cite=1997%20c%20106%20§%205[1997 c 106 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c391.pdf?cite=1987%20c%20391%20§%207[1987 c 391 § 7]; ]

== 19.146.060 - Accounting requirements.
. A mortgage broker shall use generally accepted accounting principles.

. Except as otherwise provided in subsection (3) of this section, a mortgage broker shall maintain accurate and current books and records which shall be readily available at a location available to the director until at least three years have elapsed following the effective period to which the books and records relate.

. Where a mortgage broker's usual business location is outside of the state of Washington, the mortgage broker shall, as determined by the director by rule, either maintain its books and records at a location in this state, or reimburse the director for his or her expenses, including but not limited to transportation, food, and lodging expenses, relating to any examination or investigation resulting under this chapter.

. "Books and records" includes but is not limited to:

.. Copies of all advertisements placed by or at the request of the mortgage broker which mention rates or fees. In the case of radio or television advertisements, or advertisements placed on a telephonic information line or other electronic source of information including but not limited to a computer database or electronic bulletin board, a mortgage broker shall keep copies of the precise script for the advertisement. All advertisement records shall include for each advertisement the date or dates of publication and name of each periodical, broadcast station, or telephone information line which published the advertisement or, in the case of a flyer or other material distributed by the mortgage broker, the dates, methods, and areas of distribution; and

.. Copies of all documents, notes, computer records if not stored in printed form, correspondence or memoranda relating to a borrower from whom the mortgage broker has accepted a deposit or other funds, or accepted a residential mortgage loan application or with whom the mortgage broker has entered into an agreement to assist in obtaining a residential mortgage loan.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5210-S.SL.pdf?cite=2013%20c%2030%20§%204[2013 c 30 § 4]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2340.SL.pdf?cite=2006%20c%2019%20§%207[2006 c 19 § 7]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1678-S.SL.pdf?cite=1997%20c%20106%20§%206[1997 c 106 § 6]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%2020[1994 c 33 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c391.pdf?cite=1987%20c%20391%20§%208[1987 c 391 § 8]; ]

== 19.146.070 - Fee, commission, or compensation—When permitted.
. Except as otherwise permitted by this section, a mortgage broker must not receive a fee, commission, or compensation of any kind in connection with the preparation, negotiation, and brokering of a residential mortgage loan unless a borrower actually obtains a loan from a lender on the terms and conditions agreed upon by the borrower and mortgage broker. A loan originator may not accept a fee, commission, or compensation of any kind from borrowers in connection with the preparation, negotiation, and brokering of a residential mortgage loan.

. A mortgage broker may:

.. If the mortgage broker has obtained for the borrower a written commitment from a lender for a loan on the terms and conditions agreed upon by the borrower and the mortgage broker, and the borrower fails to close on the loan through no fault of the mortgage broker, charge a fee not to exceed three hundred dollars for services rendered, preparation of documents, or transfer of documents in the borrower's file which were prepared or paid for by the borrower if the fee is not otherwise prohibited by the truth in lending act, 15 U.S.C. Sec. 1601, and Regulation Z, 12 C.F.R. Part 1026, as now or hereafter amended; or

.. Solicit or receive fees for third party provider goods or services in advance. Fees for any goods or services not provided must be refunded to the borrower and the mortgage broker may not charge more for the goods and services than the actual costs of the goods or services charged by the third party provider.

. A loan originator may not solicit or receive fees for a third-party provider of goods or services except that a loan originator may transfer funds from a borrower to a licensed mortgage broker, exempt mortgage broker, or third-party provider, if the loan originator does not deposit, hold, retain, or use the funds for any purpose other than the payment of bona fide fees to third-party providers.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5299-S.SL.pdf?cite=2015%20c%20229%20§%2010[2015 c 229 § 10]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2340.SL.pdf?cite=2006%20c%2019%20§%208[2006 c 19 § 8]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=1993%20c%20468%20§%2013[1993 c 468 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c391.pdf?cite=1987%20c%20391%20§%209[1987 c 391 § 9]; ]

== 19.146.080 - Borrowers unable to obtain loans—Mortgage broker to provide copies of certain documents—Conditions—Exceptions.
Except as otherwise required by the United States Code or the Code of Federal Regulations, now or as amended, if a borrower is unable to obtain a loan for any reason and the borrower has paid for an appraisal, title report, or credit report in full, the mortgage broker shall give a copy of the appraisal, title report, or credit report to the borrower and transmit the originals to any other mortgage broker or lender to whom the borrower directs that the documents be transmitted. Regardless of whether the borrower has obtained a loan, the mortgage broker must provide the copies or transmit the documents within five days after the borrower has made the request in writing.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1678-S.SL.pdf?cite=1997%20c%20106%20§%207[1997 c 106 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c391.pdf?cite=1987%20c%20391%20§%2010[1987 c 391 § 10]; ]

== 19.146.085 - Duties—Generally.
The activities of a mortgage broker affect the public interest, and require that all actions of mortgage brokers, designated brokers, loan originators, and other persons subject to this chapter be actuated by good faith, abstain from deception, and practice honesty and equity in all matters related to their profession. The duty of preserving the integrity of the mortgage broker business rests upon the mortgage broker, designated broker, loan originator, and other persons subject to this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2770-S.SL.pdf?cite=2008%20c%20108%20§%2020[2008 c 108 § 20]; ]

== 19.146.095 - Fiduciary duties.
. A mortgage broker has a fiduciary relationship with the borrower. For the purposes of this section, the fiduciary duty means that the mortgage broker has the following duties:

.. A mortgage broker must act in the borrower's best interest and in the utmost good faith toward the borrower, and shall disclose any and all interests to the borrower including, but not limited to, interests that may lie with the lender that are used to facilitate a borrower's request. A mortgage broker shall not accept, provide, or charge any undisclosed compensation or realize any undisclosed remuneration that inures to the benefit of the mortgage broker on an expenditure made for the borrower;

.. A mortgage broker must carry out all lawful instructions provided by the borrower;

.. A mortgage broker must disclose to the borrower all material facts of which the mortgage broker has knowledge that might reasonably affect the borrower's rights, interests, or ability to receive the borrower's intended benefit from the residential mortgage loan;

.. A mortgage broker must use reasonable care in performing duties; and

.. A mortgage broker must provide an accounting to the borrower for all money and property received from the borrower.

. A mortgage broker may contract for or collect a fee for services rendered if the fee is disclosed to the borrower in advance of the provision of those services.

. The fiduciary duty in this section does not require a mortgage broker to offer or obtain access to loan products and services other than those that are available to the mortgage broker at the time of the transaction.

. The director must adopt rules to implement this section.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6381.SL.pdf?cite=2008%20c%20109%20§%201[2008 c 109 § 1]; ]

== 19.146.100 - Violations of chapter—Application of consumer protection act.
The legislature finds that the practices governed by this chapter are matters vitally affecting the public interest for the purpose of applying the consumer protection act, chapter 19.86 RCW. Any violation of this chapter is not reasonable in relation to the development and preservation of business and is an unfair or deceptive act or practice and unfair method of competition in the conduct of trade or commerce in violation of RCW 19.86.020. Remedies provided by chapter 19.86 RCW are cumulative and not exclusive.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%2025[1994 c 33 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c391.pdf?cite=1987%20c%20391%20§%2012[1987 c 391 § 12]; ]

== 19.146.103 - Financial interest in a mortgage broker—Prohibited practices.
. A mortgage broker, loan originator, officer or employee of any mortgage broker, or person who has a financial interest in a mortgage broker shall not, directly or indirectly, give any fee, kickback, payment, or other thing of value to any person as an inducement, reward for placing business, referring business, or causing title insurance business to be given to a title insurance agent in which the mortgage broker, loan originator, or person having a financial interest in the mortgage broker also has a financial interest.

. A mortgage broker, loan originator, or person who has a financial interest in a mortgage broker shall not either solicit or accept, or both, anything of value from: A title insurance company, a title insurance agent, or the employees or representatives of a title insurance company or title insurance agent, that a title insurance company or title insurance agent is not permitted by law or rule to give to the mortgage broker, loan originator, or person who has a financial interest in the mortgage broker.

. A mortgage broker, loan originator, or person who has a financial interest in a mortgage broker shall not prevent or deter a title insurance company, title insurance agent, or their employees or representatives from delivering to a mortgage broker or loan originator or its employees, independent contractors, and clients printed promotional material concerning only title insurance services as long as:

.. The material is business appropriate and is not misleading or false;

.. The material does not malign the mortgage broker or loan originator, its employees, independent contractors, or affiliates;

.. The delivery of the materials is limited to those areas of the mortgage broker or loan originator's physical office reserved for unrestricted public access; and

.. The conduct of the employees or representatives is appropriate for a business setting and does not threaten the safety or health of anyone in the mortgage broker's or loan originator's office.

. A mortgage broker or loan originator shall not require a consumer, as a condition of providing loans or real estate settlement services, to obtain title insurance from a title insurance agent in which the mortgage broker or loan originator has a financial interest.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6847-S.SL.pdf?cite=2008%20c%20110%20§%2012[2008 c 110 § 12]; ]

== 19.146.110 - Criminal penalty.
Any person who violates any provision of this chapter other than RCW 19.146.050 or any rule or order of the director is guilty of a misdemeanor punishable under chapter 9A.20 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20159[2003 c 53 § 159]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=1993%20c%20468%20§%2020[1993 c 468 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c391.pdf?cite=1987%20c%20391%20§%2013[1987 c 391 § 13]; ]

== 19.146.200 - Mortgage broker or loan originator—License required—Suit or action for collection of compensation—Designated broker required.
. A person, unless specifically exempted from this chapter under RCW 19.146.020, may not engage in the business of a mortgage broker or loan originator without first obtaining and maintaining a license under this chapter.

. A person may not bring a suit or action for the collection of compensation in connection with a residential mortgage loan unless the plaintiff alleges and proves that he or she was a duly licensed mortgage broker, or exempt from the license requirement of this chapter, at the time of offering to perform or performing any such an act or service regulated by this chapter.

. Every licensed mortgage broker must at all times have a designated broker responsible for all activities of the mortgage broker in conducting the business of a mortgage broker. A designated broker, principal, or owner who has supervisory authority over a mortgage broker is responsible for a licensee's, employee's, or independent contractor's violations of this chapter and its rules if:

.. The designated broker, principal, or owner directs or instructs the conduct or, with knowledge of the specific conduct, approves or allows the conduct; or

.. The designated broker, principal, or owner who has supervisory authority over the licensed mortgage broker knows or by the exercise of reasonable care and inquiry should have known of the conduct, at a time when its consequences can be avoided or mitigated and fails to take reasonable remedial action.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2255-S.SL.pdf?cite=2012%20c%2017%20§%2012[2012 c 17 § 12]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2340.SL.pdf?cite=2006%20c%2019%20§%209[2006 c 19 § 9]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1678-S.SL.pdf?cite=1997%20c%20106%20§%208[1997 c 106 § 8]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%207[1994 c 33 § 7]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=1993%20c%20468%20§%205[1993 c 468 § 5]; ]

== 19.146.205 - License—Application—Applicant to furnish information establishing identity—Background check—Fee—Bond or alternative.
. Application for a mortgage broker license under this chapter must be made to the nationwide mortgage licensing system and registry and in the form prescribed by the director. The application must contain at least the following information:

.. The name, address, date of birth, and social security number of the applicant, and any other names, dates of birth, or social security numbers previously used by the applicant, unless waived by the director;

.. If the applicant is a partnership, association, or limited liability company the name, address, date of birth, and social security number of each general partner, principal, or member of the association, and any other names, dates of birth, or social security numbers previously used by the members, unless waived by the director;

.. If the applicant is a corporation, the name, address, date of birth, and social security number of each officer, director, registered agent, and each principal stockholder, and any other names, dates of birth, or social security numbers previously used by the officers, directors, registered agents, and principal stockholders unless waived by the director;

.. The street address, county, and municipality where the principal business office is to be located;

.. The name, address, date of birth, and social security number of the applicant's designated broker, and any other names, dates of birth, or social security numbers previously used by the designated broker and a complete set of the designated broker's fingerprints taken by an authorized law enforcement officer; and

.. [Empty]
... Such other information regarding the applicant's or designated broker's background, financial responsibility, experience, character, and general fitness as the director may require by rule.

... The director may waive one or more requirements of this section or permit an applicant to submit other information in lieu of the required information.

. As a part of or in connection with an application for any license under this section, or periodically upon license renewal, the applicant must furnish information concerning his or her identity, including fingerprints for submission to the Washington state patrol, the federal bureau of investigation, the nationwide mortgage licensing system and registry, or any governmental agency or entity authorized to receive this information for a state and national criminal history background check; personal history; experience; business record; purposes; and other pertinent facts, as the director may reasonably require. As part of or in connection with an application for a license under this chapter, the director is authorized to receive criminal history record information that includes nonconviction data as defined in RCW 10.97.030. The department may only disseminate nonconviction data obtained under this section to criminal justice agencies. This section does not apply to financial institutions regulated under chapters 31.12 and 31.13 RCW and Titles 30A, 32, and 33 RCW.

. In order to reduce the points of contact which the federal bureau of investigation may have to maintain, the director may use the nationwide mortgage licensing system and registry as a channeling agent for requesting information from and distributing information to the department of justice or any governmental agency.

. In order to reduce the points of contact which the director may have to maintain, the director may use the nationwide mortgage licensing system and registry as a channeling agent for requesting and distributing information to and from any source so directed by the director.

. At the time of filing an application for a license under this chapter, each applicant must pay to the director through the nationwide mortgage licensing system and registry the appropriate application fee in an amount determined by rule of the director in accordance with RCW 43.24.086 to cover, but not exceed, the cost of processing and reviewing the application. The director must deposit the moneys in the financial services regulation fund, unless the consumer services account is created as a dedicated, nonappropriated account, in which case the director must deposit the moneys in the consumer services account.

. [Empty]
.. Except as provided in (b) of this subsection, each applicant for a mortgage broker's license must file and maintain a surety bond, in an amount which the director deems adequate to protect the public interest, executed by the applicant as obligor and by a surety company authorized to do a surety business in this state as surety. The bonding requirement as established by the director must take the form of a range of bond amounts which vary according to the annual loan origination volume of the licensee. The bond must run to the state of Washington as obligee, and must run first to the benefit of the borrower and then to the benefit of the state and any person or persons who suffer loss by reason of the applicant's or its loan originator's violation of any provision of this chapter or rules adopted under this chapter. The bond must be conditioned that the obligor as licensee will faithfully conform to and abide by this chapter and all rules adopted under this chapter, and must reimburse all persons who suffer loss by reason of a violation of this chapter or rules adopted under this chapter. Borrowers must be given priority over the state and other persons. The state and other third parties must be allowed to receive distribution pursuant to a valid claim against the remainder of the bond. In the case of claims made by any person or entity who is not a borrower, no final judgment may be entered prior to one hundred eighty days following the date the claim is filed. The bond must be continuous and may be canceled by the surety upon the surety giving written notice to the director of its intent to cancel the bond. The cancellation must be effective thirty days after the notice is received by the director. Whether or not the bond is renewed, continued, reinstated, reissued, or otherwise extended, replaced, or modified, including increases or decreases in the penal sum, it is considered one continuous obligation, and the surety upon the bond is not liable in an aggregate or cumulative amount exceeding the penal sum set forth on the face of the bond. In no event is the penal sum, or any portion thereof, at two or more points in time be added together in determining the surety's liability. The bond is not be [is not] liable for any penalties imposed on the licensee , including, but not limited to, any increased damages or attorneys' fees, or both, awarded under RCW 19.86.090. The applicant may obtain the bond directly from the surety or through a group bonding arrangement involving a professional organization comprised of mortgage brokers if the arrangement provides at least as much coverage as is required under this subsection.

.. If the director determines that the bond required in (a) of this subsection is not reasonably available, the director must waive the requirements for such a bond. The mortgage recovery fund account is created in the custody of the state treasurer. The director is authorized to charge fees to fund the account. All fees charged under this section, except those retained by the director for administration of the account, must be deposited into the mortgage recovery fund account. Expenditures from the account may be used only for the same purposes as the surety bond as described in (a) of this subsection. Only the director or the director's designee may authorize expenditures from the account. The account is subject to allotment procedures under chapter 43.88 RCW, but an appropriation is not required for expenditures. A person entitled to receive payment from the mortgage recovery account may only receive reimbursement after a court of competent jurisdiction has determined the actual damages caused by the licensee. The director may determine by rule the procedure for recovery; the amount each mortgage broker must pay through the nationwide mortgage licensing system and registry for deposit in the mortgage recovery account; and the amount necessary to administer the account.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5299-S.SL.pdf?cite=2015%20c%20229%20§%2011[2015 c 229 § 11]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1749-S.SL.pdf?cite=2009%20c%20528%20§%204[2009 c 528 § 4]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2340.SL.pdf?cite=2006%20c%2019%20§%2010[2006 c 19 § 10]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1211.SL.pdf?cite=2001%20c%20177%20§%204[2001 c 177 § 4]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1678-S.SL.pdf?cite=1997%20c%20106%20§%209[1997 c 106 § 9]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%208[1994 c 33 § 8]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=1993%20c%20468%20§%206[1993 c 468 § 6]; ]

== 19.146.210 - License—Requirements for issuance—Denial—Validity—Surrender—Interim license—Rules.
. The director shall issue and deliver a mortgage broker license to an applicant if, after investigation, the director makes the following findings:

.. The applicant has paid the required license fees;

.. The applicant has complied with RCW 19.146.205;

.. Neither the applicant, any of its principals, or the designated broker have had a license issued under this chapter or any similar state statute suspended or revoked within five years of the filing of the present application;

.. Neither the applicant, any of its principals, or the designated broker have been convicted of a gross misdemeanor involving dishonesty or financial misconduct or a felony within seven years of the filing of the present application;

.. The designated broker: (i) Has at least two years of experience in the residential mortgage loan industry; and (ii) has passed a written examination whose content shall be established by rule of the director;

.. The applicant, its principals, and the designated broker have demonstrated financial responsibility, character, and general fitness such as to command the confidence of the community and to warrant a belief that the business will be operated honestly, fairly, and efficiently within the purposes of this chapter; 

.. Neither the applicant, any of its principals, or the designated broker have been found to be in violation of this chapter or rules; and

.. Neither the applicant, any of its principals, nor the designated broker have provided unlicensed residential mortgage loan modification services in this state in the five years prior to the filing of the present application.

. If the director does not find the conditions of subsection (1) of this section have been met, the director shall not issue the license. The director shall notify the applicant of the denial and return to the applicant the bond or approved alternative and any remaining portion of the license fee that exceeds the department's actual cost to investigate the license.

. A license issued pursuant to this section expires on the date one year from the date of issuance which, for license renewal purposes, is also the renewal date. The director shall adopt rules establishing the process for renewal of licenses.

. A licensee may surrender a license by delivering to the director written notice of surrender, but the surrender does not affect the licensee's civil or criminal liability or any administrative actions arising from acts or omissions occurring before such surrender.

. To prevent undue delay in the issuance of a license and to facilitate the business of a mortgage broker, an interim license with a fixed date of expiration may be issued when the director determines that the mortgage broker has substantially fulfilled the requirements for licensing as defined by rule.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2608.SL.pdf?cite=2010%20c%2035%20§%2014[2010 c 35 § 14]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2340.SL.pdf?cite=2006%20c%2019%20§%2011[2006 c 19 § 11]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1678-S.SL.pdf?cite=1997%20c%20106%20§%2010[1997 c 106 § 10]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%2010[1994 c 33 § 10]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=1993%20c%20468%20§%207[1993 c 468 § 7]; ]

== 19.146.215 - Continuing education—Rules.
The designated broker of every licensee shall complete an annual continuing education requirement. The director shall establish standards in rule for approval of professional organizations offering continuing education to designated brokers. The director may approve continuing education taken by designated brokers in other states if the director is satisfied that such continuing education meets the requirements of the continuing education required by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2340.SL.pdf?cite=2006%20c%2019%20§%2012[2006 c 19 § 12]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1678-S.SL.pdf?cite=1997%20c%20106%20§%2011[1997 c 106 § 11]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%2011[1994 c 33 § 11]; ]

== 19.146.218 - Informal settlement of complaints or enforcement actions—Director's discretion.
Except to the extent prohibited by another statute, the director may engage in informal settlement of complaints or enforcement actions including, but not limited to, payment to the department for purposes of financial literacy and education programs authorized under RCW 43.320.150. If any person subject to this chapter makes a payment to the department under this section, the person may not advertise such payment.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2255-S.SL.pdf?cite=2012%20c%2017%20§%2013[2012 c 17 § 13]; ]

== 19.146.220 - Director—Powers and duties—Violations as separate violations—Rules.
. The director may enforce all laws and rules relating to the licensing of mortgage brokers and loan originators, grant or deny licenses to mortgage brokers and loan originators, and hold hearings.

. The director may impose fines and order restitution and refunds against licensees, employees, independent contractors, agents of licensees, and other persons subject to this chapter, and may deny, condition, suspend, decline to renew, decline to reactivate, or revoke licenses for:

.. Violations of orders, including cease and desist orders;

.. False statements or omission of material information on the application that, if known, would have allowed the director to deny the application for the original license;

.. Failure to pay a fee required by the director or maintain the required bond;

.. Failure to comply with any directive, order, or subpoena of the director; or

.. Any violation of this chapter.

. The director may issue orders directing a licensee, its employee, loan originator, independent contractor, agent, or other person subject to this chapter to cease and desist from conducting business or take such other affirmative action as is necessary to comply with this chapter.

. The director may issue orders removing from office or prohibiting from participation in the conduct of the affairs of a licensed mortgage broker, or both, any officer, principal, employee, or loan originator of any licensed mortgage broker or any person subject to licensing under this chapter for:

.. Any violation of this chapter;

.. False statements or omission of material information on the application that, if known, would have allowed the director to deny the application for the original license;

.. Conviction of a gross misdemeanor involving dishonesty or financial misconduct or a felony after obtaining a license; or

.. Failure to comply with any directive or order of the director.

. Each day's continuance of a violation or failure to comply with any directive or order of the director is a separate and distinct violation or failure.

. The statute of limitations on actions not subject to RCW 4.16.160 that are brought under this chapter by the director is five years.

. The director must establish by rule standards for licensure of applicants licensed in other jurisdictions.

. The director must immediately suspend the license or certificate of a person who has been certified pursuant to RCW 74.20A.320 by the department of social and health services as a person who is not in compliance with a support order. If the person has continued to meet all other requirements for reinstatement during the suspension, reissuance of the license or certificate is automatic upon the director's receipt of a release issued by the department of social and health services stating that the licensee is in compliance with the order.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5299-S.SL.pdf?cite=2015%20c%20229%20§%2012[2015 c 229 § 12]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6134.SL.pdf?cite=2014%20c%2036%20§%202[2014 c 36 § 2]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5210-S.SL.pdf?cite=2013%20c%2030%20§%205[2013 c 30 § 5]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2340.SL.pdf?cite=2006%20c%2019%20§%2013[2006 c 19 § 13]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1678-S.SL.pdf?cite=1997%20c%20106%20§%2012[1997 c 106 § 12]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20879[1997 c 58 § 879]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6617.SL.pdf?cite=1996%20c%20103%20§%201[1996 c 103 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%2012[1994 c 33 § 12]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=1993%20c%20468%20§%208[1993 c 468 § 8]; ]

== 19.146.221 - Action by director—Hearing—Sanction.
. The director may, at his or her discretion, take any action as provided for in this chapter to enforce this chapter. If the person subject to such action does not appear in person or by counsel at the time and place designated for any administrative hearing that may be held on the action then the person shall be deemed to consent to the action. If the person subject to the action consents, or if after hearing the director finds by a preponderance of the evidence that any grounds for sanctions under this chapter exist, then the director may impose any sanction authorized by this chapter.

. The director may recover the state's costs and expenses for prosecuting violations of this chapter including staff time spent preparing for and attending administrative hearings and reasonable attorneys' fees unless, after a hearing, the director determines no violation occurred.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5299-S.SL.pdf?cite=2015%20c%20229%20§%2013[2015 c 229 § 13]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%2013[1994 c 33 § 13]; ]

== 19.146.223 - Director—Administration and interpretation.
The director shall have the power and broad administrative discretion to administer and interpret the provisions of this chapter to fulfill the intent of the legislature as expressed in RCW 19.146.005.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%202[1994 c 33 § 2]; ]

== 19.146.225 - Director—Rule-making powers.
In accordance with the administrative procedure act, chapter 34.05 RCW, the director may issue rules under this chapter only for the purpose of governing the activities of licensed mortgage brokers, loan originators, and other persons subject to this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2617-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%207%20§%2070[2010 1st sp.s. c 7 § 70]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2340.SL.pdf?cite=2006%20c%2019%20§%2014[2006 c 19 § 14]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%2015[1994 c 33 § 15]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=1993%20c%20468%20§%209[1993 c 468 § 9]; ]

== 19.146.226 - Director—Licensing rules and interim procedures.
For the purposes of implementing an orderly and efficient licensing process, the director may establish licensing rules and interim procedures for licensing and acceptance of applications. For previously registered or licensed individuals, the director may establish expedited review and licensing procedures.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1749-S.SL.pdf?cite=2009%20c%20528%20§%2013[2009 c 528 § 13]; ]

== 19.146.227 - Cease and desist order—Action to enjoin and enforce.
Whenever the director determines that the public is likely to be substantially injured by delay in issuing a cease and desist order, the director may immediately issue a temporary cease and desist order. The order may direct the licensee to discontinue any violation of this chapter and take such affirmative action as is necessary to comply with this chapter, may include a summary suspension of the licensee's license, and may order the licensee to immediately cease the conduct of business under this chapter. The order becomes effective at the time specified in the order. Every temporary cease and desist order must include a provision that a hearing will be held, within fourteen days unless otherwise specified in chapter 34.05 RCW, upon request to determine whether the order will become permanent.

If it appears that a person has engaged in an act or practice constituting a violation of a provision of this chapter, or a rule or order under this chapter, the director, with or without prior administrative proceedings, may bring an action in the superior court to enjoin the acts or practices and to enforce compliance with this chapter or any rule or order under this chapter. Upon proper showing, injunctive relief or temporary restraining orders must be granted. The director is not required to post a bond in any court proceedings.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5299-S.SL.pdf?cite=2015%20c%20229%20§%2014[2015 c 229 § 14]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%2014[1994 c 33 § 14]; ]

== 19.146.228 - Fees—Exception.
The director must establish fees sufficient to cover, but not exceed, the costs of administering this chapter. These fees may include:

. An annual assessment paid by each licensee on or before a date specified by rule;

. An investigation fee to cover the costs of any investigation of the books and records of a licensee or other person subject to this chapter; and

. An application fee to cover the costs of processing applications made to the director under this chapter.

Mortgage brokers, loan originators, and any person subject to licensing under this chapter must not be charged investigation fees for the processing of complaints when the investigation determines that no violation of this chapter occurred or when the mortgage broker or loan originator provides a remedy satisfactory to the complainant and the director and no order of the director is issued. All moneys, fees, and penalties collected under the authority of this chapter must be deposited into the financial services regulation fund, unless the consumer services account is created as a dedicated, nonappropriated account, in which case all moneys, fees, and penalties collected under this chapter must be deposited in the consumer services account.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5299-S.SL.pdf?cite=2015%20c%20229%20§%2015[2015 c 229 § 15]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1749-S.SL.pdf?cite=2009%20c%20528%20§%205[2009 c 528 § 5]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2340.SL.pdf?cite=2006%20c%2019%20§%2015[2006 c 19 § 15]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1211.SL.pdf?cite=2001%20c%20177%20§%205[2001 c 177 § 5]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1678-S.SL.pdf?cite=1997%20c%20106%20§%2013[1997 c 106 § 13]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%209[1994 c 33 § 9]; ]

== 19.146.230 - Administrative procedure act application.
The proceedings for denying license applications, issuing cease and desist orders, suspending or revoking licenses, and imposing civil penalties or other remedies issued pursuant to this chapter and any appeal therefrom or review thereof shall be governed by the provisions of the administrative procedure act, chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%2016[1994 c 33 § 16]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=1993%20c%20468%20§%2010[1993 c 468 § 10]; ]

== 19.146.233 - Subpoena authority—Application—Contents—Notice—Fees.
. The director or authorized assistants may apply for and obtain a superior court order approving and authorizing a subpoena in advance of its issuance. The application may be made in the county where the subpoenaed person resides or is found, or the county where the subpoenaed documents, records, or evidence are located, or in Thurston county. The application must:

.. State that an order is sought under this section;

.. Adequately specify the documents, records, evidence, or testimony; and

.. Include a declaration made under oath that an investigation is being conducted for a lawfully authorized purpose related to an investigation within the department's authority and that the subpoenaed documents, records, evidence, or testimony are reasonably related to an investigation within the department's authority.

. When an application under this section is made to the satisfaction of the court, the court must issue an order approving the subpoena. An order under this subsection constitutes authority of law for the agency to subpoena the documents, records, evidence, or testimony.

. The director or authorized assistants may seek approval and a court may issue an order under this section without prior notice to any person, including the person to whom the subpoena is directed and the person who is the subject of an investigation. An application for court approval is subject to the fee and process set forth in RCW 36.18.012(3).

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5076.SL.pdf?cite=2011%20c%2093%20§%205[2011 c 93 § 5]; ]

== 19.146.235 - Director's authority to conduct investigations and examinations—Rules—Penalty.
The director or a designee has authority to conduct investigations and examinations as provided in this section.

. For the purposes of investigating violations or complaints arising under this chapter, the director or his or her designee may make an investigation of the operations of any mortgage broker or loan originator as often as necessary in order to carry out the purposes of this chapter.

. Every mortgage broker shall make available to the director or a designee its books and records relating to its operations.

.. For the purpose of examinations, the director or his or her designee may have access to such books and records during normal business hours and interview the officers, principals, loan originators, employees, independent contractors, and agents of the licensee concerning their business.

.. For the purposes of investigating violations or complaints arising under this chapter, the director may at any time, either personally or by a designee, investigate the business, including but not limited to the books, accounts, records, and files used therein, of every licensee and of every person engaged in the business of mortgage brokering, whether such a person acts or claims to act under, or without the authority of, this chapter.

.. The director or designated person may direct, subpoena, or order the attendance of and examine under oath all persons whose testimony may be required about the loans or the business or subject matter of any such examination or investigation, and may direct, subpoena, or order such person to produce books, accounts, records, files, and any other documents the director or designated person deems relevant to the inquiry.

. The director may visit, either personally or by designee, the licensee's place or places of business to conduct an examination. The scope of the examination is limited to documents and information necessary to determine compliance with this chapter and attendant rules. In general, the examination scope may include:

.. A review for trust accounting compliance;

.. Loan file review to determine the mortgage broker's compliance with this chapter and applicable federal regulations covering the business of mortgage brokering and lending;

.. Interviews for the purpose of understanding business and solicitation practices, transactional events, disclosure compliance, complaint resolution, or determining specific compliance with this chapter and the attendant rules; and

.. A review of general business books and records, including employee records, for the purpose of determining specific compliance with this chapter and the attendant rules.

. The purpose of an examination is to make certain that licensees are conducting business in compliance with the law. Therefore, protocols for examination findings and corrective action directed from an examination must be established by rule of the director. To accomplish this purpose, these protocols must include the following:

.. A reporting mechanism from the director to the licensee;

.. A process for clear notification of violations and an opportunity for response by the licensee; and

.. The criteria by which the frequency of examinations will be determined.

. If the examination findings clearly identify the need to expand the scope of the examination, the director or a designee, upon five days' written notification to the licensee with an explanation of the need, may:

.. Expand the examination review to locations other than the examined location regardless of the number of years a location has held a license; or

.. Expand the time period of the examination beyond the five-year period of licensing, provided the expansion of time does not exceed a date certain identified in the written notification in this subsection.

. The director or a designee may consider reports made by independent certified professionals for the mortgage broker covering the same general subject matter as the examination. The director or a designee may incorporate all or part of the report in the report of the examination.

. The director may retain attorneys, accountants, or other professionals and specialists as examiners, auditors, or investigators to conduct or assist in the conduct of examinations or investigations. The cost of these services for investigations only must be billed in accordance with RCW 19.146.228.

. The director may establish by rule travel costs for examination of out-of-state entities.

. [Empty]
.. No person subject to examination or investigation under this chapter may knowingly withhold, abstract, remove, mutilate, destroy, or secrete any books, records, computer records, or other information.

.. A person who commits an act under (a) of this subsection is guilty of a class B felony punishable under RCW 9A.20.021(1)(b) or punishable by a fine of not more than twenty thousand dollars, or both.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1749-S.SL.pdf?cite=2009%20c%20528%20§%206[2009 c 528 § 6]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2340.SL.pdf?cite=2006%20c%2019%20§%2016[2006 c 19 § 16]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1678-S.SL.pdf?cite=1997%20c%20106%20§%2014[1997 c 106 § 14]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%2017[1994 c 33 § 17]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=1993%20c%20468%20§%2011[1993 c 468 § 11]; ]

== 19.146.237 - Director—Powers under chapter  19.144 RCW.
The director or the director's designee may take such action as provided for in this chapter to enforce, investigate, or examine persons covered by chapter 19.144 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2770-S.SL.pdf?cite=2008%20c%20108%20§%2014[2008 c 108 § 14]; ]

== 19.146.240 - Violations—Claims against bond or alternative.
. The director or any person injured by a violation of this chapter may bring an action against the surety bond or approved alternative of the licensed mortgage broker who committed the violation or who employed or engaged the loan originator who committed the violation.

. [Empty]
.. The director or any person who is damaged by the licensee's or its loan originator's violation of this chapter, or rules adopted under this chapter, may bring suit upon the surety bond or approved alternative in the superior court of any county in which jurisdiction over the licensee may be obtained. Jurisdiction shall be exclusively in the superior court. Except as provided in subsection (2)(b) of this section, in the event valid claims of borrowers against a bond or deposit exceed the amount of the bond or deposit, each borrower claimant shall only be entitled to a pro rata amount, based on the amount of the claim as it is valid against the bond or deposit, without regard to the date of filing of any claim or action. If, after all valid borrower claims are paid, valid claims by nonborrower claimants exceed the remaining amount of the bond or deposit, each nonborrower claimant shall only be entitled to a pro rata amount, based on the amount of the claim as it is valid against the bond or deposit, without regard to the date of the filing or any claim or action. A judgment arising from a violation of this chapter or rule adopted under this chapter shall be entered for actual damages and in no case be less than the amount paid by the borrower to the licensed mortgage broker plus reasonable attorneys' fees and costs. In no event shall the surety bond or approved alternative provide payment for any trebled or punitive damages.

.. Borrowers shall be given priority over the director and other persons in distributions in actions against the surety bond. The director and other third parties shall then be entitled to distribution to the extent of their claims as found valid against the remainder of the bond. In the case of claims made by any person or entity who is not a borrower, no final judgment may be entered prior to one hundred eighty days following the date the claim is filed. This provision regarding priority shall not restrict the right of any claimant to file a claim.

. The remedies provided under this section are cumulative and nonexclusive and do not affect any other remedy available at law.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5210-S.SL.pdf?cite=2013%20c%2030%20§%206[2013 c 30 § 6]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1678-S.SL.pdf?cite=1997%20c%20106%20§%2015[1997 c 106 § 15]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%2021[1994 c 33 § 21]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=1993%20c%20468%20§%2014[1993 c 468 § 14]; ]

== 19.146.245 - Violations—Liability.
A licensed mortgage broker is liable for any conduct violating this chapter by the designated broker, a loan originator, or other licensed mortgage broker while employed or engaged by the licensed mortgage broker.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1678-S.SL.pdf?cite=1997%20c%20106%20§%2016[1997 c 106 § 16]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%2022[1994 c 33 § 22]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=1993%20c%20468%20§%2015[1993 c 468 § 15]; ]

== 19.146.250 - Authority restricted to person named in license—Exceptions.
No license issued under the provisions of this chapter shall authorize any person other than the person to whom it is issued to do any act by virtue thereof nor to operate in any other manner than under his or her own name except:

. A licensed mortgage broker may operate or advertise under a name other than the one under which the license is issued by obtaining the written consent of the director to do so; and

. A broker may establish one or more branch offices under a name or names different from that of the main office if the name or names are approved by the director, so long as each branch office is clearly identified as a branch or division of the main office. Both the name of the branch office and of the main office must clearly appear on the sign identifying the office, if any, and in any advertisement or on any letterhead of any stationery or any forms, or signs used by the mortgage firm on which either the name of the main or branch offices appears.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1678-S.SL.pdf?cite=1997%20c%20106%20§%2017[1997 c 106 § 17]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=1993%20c%20468%20§%2016[1993 c 468 § 16]; ]

== 19.146.260 - Registered agent for brokers without physical office in state—Venue.
Every licensed mortgage broker that does not maintain a physical office within the state must maintain a registered agent within the state to receive service of any lawful process in any judicial or administrative noncriminal suit, action, or proceeding against the licensed mortgage broker which arises under this chapter or any rule or order under this chapter, with the same force and validity as if served personally on the licensed mortgage broker. Service upon the registered agent shall not be effective unless the plaintiff, who may be the director in a suit, action, or proceeding instituted by him or her, no later than the next business day sends notice of the service and a copy of the process by registered mail to the defendant or respondent at the last address of the respondent or defendant on file with the director. In any judicial action, suit, or proceeding arising under this chapter or any rule or order adopted under this chapter between the department or director and a licensed mortgage broker who does not maintain a physical office in this state, venue shall be exclusively in the superior court of Thurston county.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2400.SL.pdf?cite=2000%20c%20171%20§%2074[2000 c 171 § 74]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1678-S.SL.pdf?cite=1997%20c%20106%20§%2018[1997 c 106 § 18]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%2023[1994 c 33 § 23]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=1993%20c%20468%20§%2017[1993 c 468 § 17]; ]

== 19.146.265 - Branch offices—Fee—Licenses—Rules.
A licensee may not maintain more than one place of business under the same license unless:

. The director approves the licensed mortgage broker's application, made in a form and manner established in rule, to establish one or more branch offices under the same or different name as the main office. The applicant must be in good standing with the department, as defined in rule by the director, and the director must promptly issue a license for each of the branch offices showing the location of the main office and the particular branch; or

. The place of business is a licensed mortgage loan originator's residence and the licensed mortgage loan originator and licensed sponsoring company comply with state and federal information security requirements and other requirements as provided in this chapter and in rule, consistent with the purposes of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5077.SL.pdf?cite=2021%20c%2015%20§%204[2021 c 15 § 4]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5299-S.SL.pdf?cite=2015%20c%20229%20§%2016[2015 c 229 § 16]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1678-S.SL.pdf?cite=1997%20c%20106%20§%2019[1997 c 106 § 19]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%2024[1994 c 33 § 24]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=1993%20c%20468%20§%2018[1993 c 468 § 18]; ]

== 19.146.300 - Loan originator license—Application—Applicant to furnish information establishing identification—Background check—Fees—Rules.
. Application for a loan originator license under this chapter must be made to the nationwide mortgage licensing system and registry and in the form prescribed by the director. The application must contain at least the following information:

.. The name, address, date of birth, and social security number of the loan originator applicant, and any other names, dates of birth, or social security numbers previously used by the loan originator applicant, unless waived by the director; and

.. Such other information regarding the loan originator applicant's background, experience, character, and general fitness as the director may require by rule or as deemed necessary by the nationwide mortgage licensing system and registry.

. [Empty]
.. As part of or in connection with an application for any license under this section, or periodically upon license renewal, the loan originator applicant must furnish information concerning his or her identity, including fingerprints for submission to the Washington state patrol, the federal bureau of investigation, the nationwide mortgage licensing system and registry, or any governmental agency or entity authorized to receive this information for a state and national criminal history background check; personal history; experience; business record; purposes; and other pertinent facts, as the director may reasonably require. As part of or in connection with an application for a license under this chapter, or periodically upon license renewal, the director is authorized to receive criminal history record information that includes nonconviction data as defined in RCW 10.97.030. The department may only disseminate nonconviction data obtained under this section to criminal justice agencies. This section does not apply to financial institutions regulated under chapters 31.12 and 31.13 RCW and Titles 30A, 32, and 33 RCW.

.. In order to reduce the points of contact which the federal bureau of investigation may have to maintain, the director may use the nationwide mortgage licensing system and registry as a channeling agent for requesting information from and distributing information to the department of justice or any governmental agency.

.. In order to reduce the points of contact which the director may have to maintain, the director may use the nationwide mortgage licensing system and registry as a channeling agent for requesting and distributing information to and from any source so directed by the director.

.. As part of or in connection with an application for a license under this section, the loan originator applicant must furnish to the nationwide mortgage licensing system and registry personal history and experience in a form prescribed by the nationwide mortgage licensing system and registry, including the submission of authorization for the nationwide mortgage licensing system and registry and the director to obtain:

... An independent credit report obtained from a consumer reporting agency described in section 603(p) of the federal fair credit reporting act; and

... Information related to any administrative, civil, or criminal findings by any governmental jurisdiction.

. At the time of filing an application for a license under this chapter, each loan originator applicant must pay to the director the appropriate application fee in an amount determined by rule of the director in accordance with RCW 19.146.228 to cover the cost of processing and reviewing the application. The director must deposit the moneys in the financial services regulation fund.

. The director must establish by rule procedures for accepting and processing incomplete applications.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5299-S.SL.pdf?cite=2015%20c%20229%20§%2017[2015 c 229 § 17]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1749-S.SL.pdf?cite=2009%20c%20528%20§%209[2009 c 528 § 9]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2340.SL.pdf?cite=2006%20c%2019%20§%2019[2006 c 19 § 19]; ]

== 19.146.310 - Loan originator license—Requirements for issuance—Denial—Validity—Expiration—Surrender—Interim license.
. The director shall issue and deliver a loan originator license if, after investigation, the director makes the following findings:

.. The loan originator applicant has paid the required license fees;

.. The loan originator applicant has met the requirements of RCW 19.146.300;

.. The loan originator applicant has never had a license issued under this chapter or any similar state statute revoked except that, for the purposes of this subsection, a subsequent formal vacation of a revocation is not a revocation;

.. [Empty]
... The loan originator applicant has not been convicted of a gross misdemeanor involving dishonesty or financial misconduct or has not been convicted of, or pled guilty or nolo contendere to, a felony in a domestic, foreign, or military court within seven years of the filing of the present application; and

... The loan originator applicant has not been convicted of, or pled guilty or nolo contendere to, a felony in a domestic, foreign, or military court at any time preceding the date of application if the felony involved an act of fraud, dishonesty, breach of trust, or money laundering;

.. The loan originator applicant has passed a written examination whose content shall be established by rule of the director; 

.. The loan originator applicant has not been found to be in violation of this chapter or rules;

.. The loan originator applicant has demonstrated financial responsibility, character, and general fitness such as to command the confidence of the community and to warrant a belief that the business will be operated honestly and fairly within the purposes of this chapter. For the purposes of this section, an applicant has not demonstrated financial responsibility when the applicant shows disregard in the management of his or her financial condition. A determination that an individual has shown disregard in the management of his or her financial condition may include, but is not limited to, an assessment of: Current outstanding judgments, except judgments solely as a result of medical expenses; current outstanding tax liens or other government liens and filings; foreclosures within the last three years; or a pattern of seriously delinquent accounts within the past three years;

.. The loan originator licensee has completed, during the calendar year preceding a licensee's annual license renewal date, a minimum of eight hours of continuing education as established by rule of the director; and

.. Neither the applicant, any of its principals, nor the designated broker have provided unlicensed residential mortgage loan modification services in this state in the five years prior to the filing of the present application.

. If the director does not find the conditions of subsection (1) of this section have been met, the director shall not issue the loan originator license. The director shall notify the loan originator applicant of the denial and return to the loan originator applicant any remaining portion of the license fee that exceeds the department's actual cost to investigate the license.

. The director shall issue a new loan originator license under this chapter to any licensee that has a valid license and is otherwise in compliance with this chapter.

. A loan originator license issued under this section expires on the date one year from the date of issuance which, for license renewal purposes, is also the renewal date. The director shall establish rules regarding the loan originator license renewal process created under this chapter.

. A loan originator licensee may surrender a license by delivering to the director written notice of surrender, but the surrender does not affect the loan originator licensee's civil or criminal liability or any administrative actions arising from acts or omissions occurring before such surrender.

. To prevent undue delay in the issuance of a loan originator license and to facilitate the business of a loan originator, an interim loan originator license with a fixed date of expiration may be issued when the director determines that the loan originator has substantially fulfilled the requirements for loan originator licensing as defined by rule.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2608.SL.pdf?cite=2010%20c%2035%20§%2015[2010 c 35 § 15]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1749-S.SL.pdf?cite=2009%20c%20528%20§%2010[2009 c 528 § 10]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2340.SL.pdf?cite=2006%20c%2019%20§%2020[2006 c 19 § 20]; ]

== 19.146.320 - Loan originator license—Not assignable.
A loan originator license, or the authority granted under such a license, is not assignable and cannot be transferred, sold, or franchised by contract or any other means.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2340.SL.pdf?cite=2006%20c%2019%20§%2021[2006 c 19 § 21]; ]

== 19.146.325 - Loan originator license—Test.
. To obtain a loan originator license, an individual must pass a test developed by the nationwide mortgage licensing system and registry and administered by a test provider approved by the nationwide mortgage licensing system and registry based upon reasonable standards.

. An individual is not considered to have passed a test unless the individual achieves a test score of not less than seventy-five percent correct answers to questions.

.. An individual may retake a test three consecutive times with each consecutive taking occurring at least thirty days after the preceding test.

.. After failing three consecutive tests, an individual must wait at least six months before taking the test again.

.. A licensed mortgage loan originator who fails to maintain a valid license for a period of five years or longer must retake the test, not taking into account any time during which that individual is a registered mortgage loan originator.

. This section does not prohibit a test provider approved by the nationwide mortgage licensing system and registry from providing a test at the location of the employer of the loan originator applicant or any subsidiary or affiliate of the employer of the applicant, or any entity with which the applicant holds an exclusive arrangement to conduct the business of a mortgage loan originator.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1749-S.SL.pdf?cite=2009%20c%20528%20§%208[2009 c 528 § 8]; ]

== 19.146.340 - Loan originator applicants.
. Each loan originator applicant shall complete at least twenty hours of prelicensing education approved by the nationwide mortgage licensing system and registry. The prelicensing education shall include at least three hours of federal law and regulations; three hours of ethics, which shall include instruction on fraud, consumer protection, and fair lending issues; two hours of training related to lending standards for the nontraditional mortgage product marketplace; and at least two hours of training specifically related to Washington law.

. A loan originator applicant having successfully completed the prelicensing education requirements approved by the nationwide mortgage licensing system and registry for any state shall be accepted as credit towards completion of prelicensing education requirements in this state.

. This chapter does not preclude any prelicensing education course, as approved by the nationwide mortgage licensing system and registry, that is provided by the employer of the loan originator applicant or an entity which is affiliated with the applicant by an agency contract, or any subsidiary or affiliate of such an employer or entity. Prelicensing education may be offered either in a classroom, online, or by any other means approved by the nationwide mortgage licensing system and registry.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1749-S.SL.pdf?cite=2009%20c%20528%20§%207[2009 c 528 § 7]; ]

== 19.146.350 - Loan originators—Continuing education—Requirements.
. A licensed mortgage loan originator must complete a minimum of eight hours of continuing education, eight of which is approved by the nationwide mortgage licensing system and registry which must include at least three hours of federal law and regulations; two hours of ethics, which must include instruction on fraud, consumer protection, and fair lending issues; and two hours of training related to lending standards for the nontraditional mortgage product marketplace. Additionally, the director may require at least one hour of continuing education on Washington law provided by and administered through an approved provider.

. The nationwide mortgage licensing system and registry must review and approve continuing education courses. Review and approval of a continuing education course must include review and approval of the course provider.

. A licensed mortgage loan originator may only receive credit for a continuing education course in the year in which the course is taken, and may not take the same approved course in the same or successive years to meet the annual requirements for continuing education.

. A licensed mortgage loan originator who is an instructor of an approved continuing education course may receive credit for the licensed mortgage loan originator's own annual continuing education requirement at the rate of two hours credit for every one hour taught.

. A person having successfully completed the education requirements approved by the nationwide mortgage licensing system and registry for any state must have their credits accepted as credit towards completion of continuing education requirements in this state.

. This section does not preclude any education course, as approved by the nationwide mortgage licensing system and registry, that is provided by the employer of the mortgage loan originator or an entity which is affiliated with the mortgage loan originator by an agency contract, or any subsidiary or affiliate of such employer or entity. Continuing education may be offered either in a classroom, online, or by any other means approved by the nationwide mortgage licensing system and registry.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1749-S.SL.pdf?cite=2009%20c%20528%20§%2011[2009 c 528 § 11]; ]

== 19.146.353 - Residential mortgage loan modification services—Written fee agreement—Limitation on fees—Rules.
. In addition to any other requirements under federal or state law, an advance fee may not be collected for residential mortgage loan modification services unless a written disclosure summary of all material terms, in the format adopted by the department under subsection (2) of this section, has been provided to the borrower.

. The department shall adopt by rule a model written fee agreement, and any other rules necessary to implement this section. This may include, but is not limited to, usual and customary fees for residential mortgage loan modification services.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2608.SL.pdf?cite=2010%20c%2035%20§%2016[2010 c 35 § 16]; ]

== 19.146.355 - Third-party residential mortgage loan modification services providers—Duties—Restrictions.
. In addition to complying with all requirements for loan originators under this chapter, third-party residential mortgage loan modification services providers must:

.. Provide a written fee disclosure summary as described in RCW 19.146.353 before accepting any advance fee;

.. Not receive an advance fee greater than seven hundred fifty dollars;

.. Not charge total fees in excess of usual and customary charges, or total fees that are not reasonable in light of the service provided; and

.. Immediately inform the borrower in writing if the owner of the loan requires additional information from the borrower, or if it becomes apparent that a residential mortgage loan modification is not possible.

. As a condition for providing a loan modification or loan modification services, third-party residential mortgage loan modification services providers and individuals servicing a residential mortgage loan must not require or encourage a borrower to:

.. Sign a waiver of his or her legal defenses, counterclaims, and other legal rights against the servicer for future acts;

.. Sign a waiver of his or her right to contest a future foreclosure;

.. Waive his or her right to receive notice before the owner or servicer of the loan initiates foreclosure proceedings;

.. Agree to pay charges not enumerated in any agreement between the borrower and the lender, servicer, or owner of the loan; or

.. Cease communication with the lender, investor, or loan servicer.

. Failure to comply with subsection (1) of this section is a violation of RCW 19.144.080.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2608.SL.pdf?cite=2010%20c%2035%20§%2017[2010 c 35 § 17]; ]

== 19.146.357 - Mortgage loan originator—License required—Nationwide mortgage licensing system and registry.
An individual defined as a mortgage loan originator may not engage in the business of a mortgage loan originator without first obtaining and maintaining annually a license under this chapter. Each licensed mortgage loan originator must register with and maintain a valid unique identifier issued by the nationwide mortgage licensing system and registry.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2608.SL.pdf?cite=2010%20c%2035%20§%2018[2010 c 35 § 18]; ]

== 19.146.360 - Director's duty—Process to challenge information—Nationwide mortgage licensing system and registry.
The director shall establish a process whereby mortgage loan originators may challenge information entered into the nationwide mortgage licensing system and registry by the director.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1749-S.SL.pdf?cite=2009%20c%20528%20§%2012[2009 c 528 § 12]; ]

== 19.146.370 - Disclosure of information—Privilege—Confidentiality—Exceptions.
. Except as otherwise provided in section 1512 of the S.A.F.E. act, the requirements under any federal law or chapter 42.56 RCW regarding the privacy or confidentiality of any information or material provided to the nationwide mortgage licensing system and registry, and any privilege arising under federal or state law, including the rules of any federal or state court, with respect to that information or material, continues to apply to the information or material after the information or material has been disclosed to the nationwide mortgage licensing system and registry. Information and material may be shared with all state and federal regulatory officials with mortgage industry oversight authority without the loss of privilege or the loss of confidentiality protections provided by federal law or state law.

. For the purposes under subsection (1) of this section, the director is authorized to enter agreements or sharing arrangements with other governmental agencies, the conference of state bank supervisors, the American association of residential mortgage regulators, or other associations representing governmental agencies as established by rule, regulation, or order of the director.

. Information or material that is subject to a privilege or confidentiality under subsection (1) of this section is not subject to:

.. Disclosure under any federal or state law governing the disclosure to the public of information held by an officer or an agency of the federal government or the respective state; or

.. Subpoena or discovery, or admission into evidence, in any private civil action or administrative process unless, with respect to any privilege held by the nationwide mortgage licensing system and registry with respect to that information or material, the person to whom the information or material pertains waives, in whole or in part, in the discretion of that person, that privilege.

. Chapter 42.56 RCW relating to the disclosure of confidential supervisory information or any information or material described in subsection (1) of this section that is inconsistent with subsection (1) of this section is superseded by the requirements of this section.

. This section does not apply to the information or material relating to the employment history of, and publicly adjudicated disciplinary and enforcement actions against, mortgage loan originators that is included in the nationwide mortgage licensing system and registry for access by the public.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1749-S.SL.pdf?cite=2009%20c%20528%20§%2015[2009 c 528 § 15]; ]

== 19.146.380 - Director's authority to contract—Records and fees.
In order to fulfill the purposes of chapter 528, Laws of 2009, the director is authorized to establish relationships or contracts with the nationwide mortgage licensing system and registry or other entities designated by the nationwide mortgage licensing system and registry to collect and maintain records and process transaction fees or other fees related to licensees or other persons subject to this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1749-S.SL.pdf?cite=2009%20c%20528%20§%2016[2009 c 528 § 16]; ]

== 19.146.390 - Mortgage brokers—Call reports—Licensing system and registry.
Each mortgage broker licensee must submit call reports through the nationwide mortgage licensing system and registry in a form and containing the information as prescribed by the director or as deemed necessary by the nationwide mortgage licensing system and registry.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5299-S.SL.pdf?cite=2015%20c%20229%20§%2018[2015 c 229 § 18]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1749-S.SL.pdf?cite=2009%20c%20528%20§%2017[2009 c 528 § 17]; ]

== 19.146.400 - Director's authority—Violation and enforcement reporting.
The director is authorized to regularly report violations of chapter 528, Laws of 2009, as well as enforcement actions and other relevant information, to the nationwide mortgage licensing system and registry.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1749-S.SL.pdf?cite=2009%20c%20528%20§%2018[2009 c 528 § 18]; ]

== 19.146.900 - Short title.
This act shall be known and cited as the "mortgage broker practices act."

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c391.pdf?cite=1987%20c%20391%20§%202[1987 c 391 § 2]; ]

== 19.146.903 - Effective dates—1994 c 33.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and shall take effect immediately [March 21, 1994], except section 5 of this act which shall take effect June 1, 1994.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6083-S.SL.pdf?cite=1994%20c%2033%20§%2029[1994 c 33 § 29]; ]

== 19.146.904 - Implementation of act—2006 c 19.
The director of the department of financial institutions or the director's designee may take such steps as are necessary to ensure that chapter 19, Laws of 2006 is implemented on January 1, 2007.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2340.SL.pdf?cite=2006%20c%2019%20§%2023[2006 c 19 § 23]; ]

== 19.146.905 - Effective date—2006 c 19.
This act takes effect January 1, 2007.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2340.SL.pdf?cite=2006%20c%2019%20§%2024[2006 c 19 § 24]; ]

