= 19.130 - Telephone buyers' protection act.
:toc:

== 19.130.010 - Legislative findings.
The legislature finds that the federal deregulation of the telephone industry provides telephone users with the opportunity to purchase and use telephone and other telecommunications equipment suited to their needs. The legislature finds that competitive markets function optimally when potential buyers have adequate information about the capabilities and reliability of the equipment offered for sale. The legislature further finds that disclosure of certain product information will benefit both buyers and sellers of telephone and other telecommunications equipment and is in the public interest.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c275.pdf?cite=1984%20c%20275%20§%201[1984 c 275 § 1]; ]

== 19.130.020 - Sales of new or reconditioned telephone equipment—Disclosure of certain information.
Any person offering for sale or selling new or reconditioned telephone handsets or keysets, private branch exchanges, or private automatic branch exchanges of not more than a twenty-station capacity, shall clearly disclose prior to sale by methods which may include posting of notice or printing on the equipment package the following:

. Whether the equipment uses pulse, tone, pulse-or-tone, or other signaling methods, and a general description of the services that can be accessed through the equipment;

. Whether the equipment is registered with the federal communications commission under the applicable federal regulations;

. The person responsible for repair of the equipment;

. Standard repair charges, if any; and

. The terms of any written warranty offered with the equipment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c275.pdf?cite=1984%20c%20275%20§%202[1984 c 275 § 2]; ]

== 19.130.030 - Certain advertising media—Application of chapter.
Nothing in this chapter applies to a radio station, television station, publisher, printer, or distributor of a newspaper, magazine, billboard, or other advertising medium which accepts advertising in good faith without knowledge of its violation of any provision of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c275.pdf?cite=1984%20c%20275%20§%203[1984 c 275 § 3]; ]

== 19.130.040 - Certain radio equipment—Application of chapter.
This chapter shall not apply to radio equipment used for land, marine, or air mobile service, or any like service, whether or not such equipment is capable of interconnection by manual or automatic means to a telephone line.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c275.pdf?cite=1984%20c%20275%20§%204[1984 c 275 § 4]; ]

== 19.130.050 - Equipment not intended for connection to telephone network and used equipment located on customer's premises—Application of chapter.
This chapter shall not apply to equipment not intended for connection to the telephone network, nor to used equipment located on the customer's premises.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c275.pdf?cite=1984%20c%20275%20§%205[1984 c 275 § 5]; ]

== 19.130.060 - Violations—Application of consumer protection act.
Violation of this chapter constitutes a violation of chapter 19.86 RCW, the consumer protection act. It shall be presumed that damages to the consumer are equal to the purchase price of any telephone equipment sold in violation of this chapter up to one hundred dollars. Additional damages must be proved.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c275.pdf?cite=1984%20c%20275%20§%207[1984 c 275 § 7]; ]

== 19.130.900 - Chapter cumulative.
The rights, obligations, and remedies under this chapter are in addition to any rights, obligations, or remedies under federal statutes or regulations or other state statutes or rules.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c275.pdf?cite=1984%20c%20275%20§%206[1984 c 275 § 6]; ]

== 19.130.901 - Short title.
This chapter may be known and cited as the telephone buyers' protection act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c275.pdf?cite=1984%20c%20275%20§%208[1984 c 275 § 8]; ]

