= 19.194 - Trade-in or exchange of computer hardware.
:toc:

== 19.194.010 - Recordkeeping by retail establishments—Contents—Inspection—Definitions.
. Any retail establishment doing business in this state that accepts for trade-in or exchange any computer hardware for the purchase of other computer hardware of greater value shall maintain, at the time of each transaction, a record of the following information:

.. The signature of the person with whom the transaction is made;

.. The date of the transaction;

.. The name of the person or employee or the identification number of the person or employee conducting the transaction; and

.. The name, date of birth, and address and telephone number of the person with whom the transaction is made.

. This record is open to the inspection of any commissioned law enforcement officer of the state or any of its political subdivisions, and will be maintained for a period of one year following the date of the transaction.

. As used in this section:

.. "Computer" means a programmable electronic machine that performs high-speed mathematical or logical operation or that assembles, stores, correlates, or otherwise processes information.

.. "Computer hardware" means a computer and the associated physical equipment involved in the performance of data processing or communications functions. The term does not include computer software.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1829-S.SL.pdf?cite=1998%20c%20134%20§%201[1998 c 134 § 1]; ]

== 19.194.020 - Record of transactions—Provided upon request—Forms and format—Lost or stolen hardware.
. Upon request, every retailer doing business in this state that accepts for trade-in or exchange computer hardware shall furnish a full, true, and correct transcript of the record of all transactions conducted, under RCW 19.194.010, on the proceeding [preceding] day. These transactions shall be recorded on such forms as may be provided and in such format as may be required by the chief of police or the county's chief law enforcement officer within a specified time but not less than twenty-four hours.

. If a retailer has good cause to believe that any computer hardware in their possession has been previously lost or stolen, the retailer shall promptly report that fact to the applicable chief of police or the county's chief law enforcement officer, together with the name of the owner, if known, and the date when, and the name of the person from whom, it was received.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1829-S.SL.pdf?cite=1998%20c%20134%20§%202[1998 c 134 § 2]; ]

== 19.194.030 - Prohibited acts—Gross misdemeanor.
It is a gross misdemeanor under chapter 9A.20 RCW for:

. Any person to remove, alter, or obliterate any manufacturer's make, model, or serial number, personal identification number, or identifying marks engraved or etched upon the computer hardware that is received as a trade-in or in exchange on the purchase of other computer hardware of greater value. In addition a retailer shall not accept any computer hardware as a trade-in or in exchange on the purchase of other computer hardware of greater value where the manufacturer's make, model, or serial number, personal identification number, or identifying marks engraved or etched upon the computer hardware has been removed, altered, or obliterated;

. Any person to knowingly make, cause, or allow to be made any false entry or misstatement of any material matter in any book, record, or writing required to be kept under this chapter; or

. Any person to knowingly violate any other provision of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1829-S.SL.pdf?cite=1998%20c%20134%20§%203[1998 c 134 § 3]; ]

== 19.194.040 - Application.
RCW 19.194.010 through 19.194.030 do not apply to trade-in or exchange of computers, or computer hardware, between consumers and retailers, or their branch facilities, when the computer or computer hardware was originally purchased from that same retailer.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1829-S.SL.pdf?cite=1998%20c%20134%20§%204[1998 c 134 § 4]; ]

