= 19.108 - Uniform trade secrets act.
:toc:

== 19.108.010 - Definitions.
Unless the context clearly requires otherwise, the definitions set forth in this section apply throughout this chapter.

. "Improper means" includes theft, bribery, misrepresentation, breach or inducement of a breach of a duty to maintain secrecy, or espionage through electronic or other means;

. "Misappropriation" means:

.. Acquisition of a trade secret of another by a person who knows or has reason to know that the trade secret was acquired by improper means; or

.. Disclosure or use of a trade secret of another without express or implied consent by a person who:

... Used improper means to acquire knowledge of the trade secret; or

... At the time of disclosure or use, knew or had reason to know that his or her knowledge of the trade secret was (A) derived from or through a person who had utilized improper means to acquire it, (B) acquired under circumstances giving rise to a duty to maintain its secrecy or limit its use, or (C) derived from or through a person who owed a duty to the person seeking relief to maintain its secrecy or limit its use; or

... Before a material change of his or her position, knew or had reason to know that it was a trade secret and that knowledge of it had been acquired by accident or mistake.

. "Person" means a natural person, corporation, business trust, estate, trust, partnership, association, joint venture, government, governmental subdivision or agency, or any other legal or commercial entity.

. "Trade secret" means information, including a formula, pattern, compilation, program, device, method, technique, or process that:

.. Derives independent economic value, actual or potential, from not being generally known to, and not being readily ascertainable by proper means by, other persons who can obtain economic value from its disclosure or use; and

.. Is the subject of efforts that are reasonable under the circumstances to maintain its secrecy.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c286.pdf?cite=1981%20c%20286%20§%201[1981 c 286 § 1]; ]

== 19.108.020 - Remedies for misappropriation—Injunction, royalty.
. Actual or threatened misappropriation may be enjoined. Upon application to the court, an injunction shall be terminated when the trade secret has ceased to exist, but the injunction may be continued for an additional reasonable period of time in order to eliminate commercial advantage that otherwise would be derived from the misappropriation.

. If the court determines that it would be unreasonable to prohibit future use, an injunction may condition future use upon payment of a reasonable royalty for no longer than the period of time the use could have been prohibited.

. In appropriate circumstances, affirmative acts to protect a trade secret may be compelled by court order.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c286.pdf?cite=1981%20c%20286%20§%202[1981 c 286 § 2]; ]

== 19.108.030 - Remedies for misappropriation—Damages.
. In addition to or in lieu of injunctive relief, a complainant may recover damages for the actual loss caused by misappropriation. A complainant also may recover for the unjust enrichment caused by misappropriation that is not taken into account in computing damages for actual loss.

. If wilful and malicious misappropriation exists, the court may award exemplary damages in an amount not exceeding twice any award made under subsection (1).

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c286.pdf?cite=1981%20c%20286%20§%203[1981 c 286 § 3]; ]

== 19.108.040 - Award of attorney's fees.
If a claim of misappropriation is made in bad faith, a motion to terminate an injunction is made or resisted in bad faith, or wilful and malicious misappropriation exists, the court may award reasonable attorney's fees to the prevailing party.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c286.pdf?cite=1981%20c%20286%20§%204[1981 c 286 § 4]; ]

== 19.108.050 - Court orders to preserve secrecy of alleged trade secrets.
In an action under this chapter, a court shall preserve the secrecy of an alleged trade secret by reasonable means, which may include granting protective orders in connection with discovery proceedings, holding in-camera hearings, sealing the records of the action, and ordering any person involved in the litigation not to disclose an alleged trade secret without prior court approval.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c286.pdf?cite=1981%20c%20286%20§%205[1981 c 286 § 5]; ]

== 19.108.060 - Actions for misappropriation—Time limitation.
An action for misappropriation must be brought within three years after the misappropriation is discovered or by the exercise of reasonable diligence should have been discovered. For the purposes of this section, a continuing misappropriation constitutes a single claim.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c286.pdf?cite=1981%20c%20286%20§%206[1981 c 286 § 6]; ]

== 19.108.900 - Effect of chapter on other law.
. This chapter displaces conflicting tort, restitutionary, and other law of this state pertaining to civil liability for misappropriation of a trade secret.

. This chapter does not affect:

.. Contractual or other civil liability or relief that is not based upon misappropriation of a trade secret; or

.. Criminal liability for misappropriation of a trade secret.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c286.pdf?cite=1981%20c%20286%20§%207[1981 c 286 § 7]; ]

== 19.108.910 - Construction of uniform act.
This chapter shall be applied and construed to effectuate its general purpose to make uniform the law with respect to the subject of this chapter among states enacting it.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c286.pdf?cite=1981%20c%20286%20§%208[1981 c 286 § 8]; ]

== 19.108.920 - Short title.
This chapter may be known and cited as the uniform trade secrets act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c286.pdf?cite=1981%20c%20286%20§%209[1981 c 286 § 9]; ]

== 19.108.930 - Effective date—Application—1981 c 286.
This chapter takes effect on January 1, 1982, and does not apply to misappropriation occurring prior to the effective date.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c286.pdf?cite=1981%20c%20286%20§%2012[1981 c 286 § 12]; ]

