= 19.148 - Mortgage loan servicing.
:toc:

== 19.148.010 - Finding—Purpose.
The ability of individuals to obtain information relating to their residential mortgage loans is vital to the financial needs of mortgagors in Washington. The public interest is adversely affected when a residential mortgage loan's servicing is sold or transferred with insufficient notification given to the mortgagor. In addition, mortgagors may experience difficulty in obtaining various mortgage loan information including information concerning mortgage loan prepayments, reserve accounts, and adjustments to monthly payments. The legislature finds that the legitimate interests of mortgagors and mortgage loan servicers are served if the disclosure of the potential sale of loan servicing is made to the mortgagor, reasonable notification of a residential mortgage loan servicing's sale is made, and continued mortgagor access to information regarding the mortgage loan is promoted.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c98.pdf?cite=1989%20c%2098%20§%201[1989 c 98 § 1]; ]

== 19.148.020 - Definitions.
Unless the context requires otherwise, the definitions in this section apply throughout this chapter.

. "Lender" shall mean any person in the business of making a loan.

. "Loan" shall mean any loan used to finance the acquisition of a one-to-four family owner occupied residence located in this state.

. "Purchasing servicing agent" is any person who purchases, receives through transfer or assignment, or otherwise acquires the responsibility of the servicing for a loan.

. "Person" shall include an individual, firm, association, partnership, business, trust, corporation, or any other legal entity whether resident or nonresident.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c98.pdf?cite=1989%20c%2098%20§%202[1989 c 98 § 2]; ]

== 19.148.030 - Disclosure requirements—Action for damages.
. If the servicing for the loan is subject to sale, transfer, or assignment, a lender shall so disclose in writing at the time of or prior to loan closing and shall also disclose in the same writing that when such servicing is sold, transferred, or assigned, the purchasing servicing agent is required to provide notification to the mortgagor. If a lender, which has not provided the notice required by this subsection, consolidates with, merges with or is acquired by another institution, and thereafter loan servicing becomes subject to sale, transfer, or assignment, that institution shall within thirty days of such transaction make the disclosure in writing to the obligor primarily responsible for repaying each loan according to the records of the lender.

. If the servicing of a loan is sold, assigned, transferred, or otherwise acquired by another person, the purchasing servicing agent shall:

.. [Empty]
... Issue corrected coupon or payment books, if used and necessary;

... Provide notification to the mortgagor at least thirty days prior to the due date of the first payment to the purchasing servicing agent, of the name, address, and telephone number of the division from whom the mortgagor can receive information regarding the servicing of the loan; and

... Inform the mortgagor of changes made regarding the servicing requirements including, but not limited to, interest rate, monthly payment amount, and escrow balance; and

.. Respond within fifteen business days upon receipt of a written request for information from a mortgagor. A written response must include the telephone number of the company division who can assist the mortgagor.

. Any person injured by a violation of this chapter may bring an action for actual damages and reasonable attorneys' fees and costs incurred in bringing the action.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c98.pdf?cite=1989%20c%2098%20§%203[1989 c 98 § 3]; ]

== 19.148.900 - Effective date—1989 c 98.
This act shall take effect on January 1, 1990.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c98.pdf?cite=1989%20c%2098%20§%205[1989 c 98 § 5]; ]

