= 19.160 - Business telephone listings.
:toc:

== 19.160.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Local telephone directory" means a publication listing telephone numbers for various businesses in a certain geographic area and distributed free of charge to some or all telephone subscribers in that area.

. "Local telephone number" means a specific telephone number, area code and prefix, assigned for the purpose of completing local calls between a calling party or station and any other party or station within a designated exchange or all of its designated local calling areas. The term "local telephone number" does not include long distance telephone numbers or any toll-free telephone numbers listed in a local telephone directory.

. "Person" means an individual, partnership, limited liability partnership, corporation, or limited liability corporation.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1422.SL.pdf?cite=2015%20c%20168%20§%201[2015 c 168 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1471-S.SL.pdf?cite=1999%20c%20156%20§%201[1999 c 156 § 1]; ]

== 19.160.020 - Finding—Application of consumer protection act.
The legislature finds that the practices covered by this chapter are matters vitally affecting the public interest for the purpose of applying the consumer protection act, chapter 19.86 RCW. Violations of this chapter are not reasonable in relation to the development and preservation of business. A violation of this chapter is an unfair or deceptive act in trade or commerce and an unfair method of competition for the purpose of applying the consumer protection act, chapter 19.86 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1471-S.SL.pdf?cite=1999%20c%20156%20§%203[1999 c 156 § 3]; ]

== 19.160.030 - Floral or ornamental products or services—Misrepresentation of geographic location—Penalty—Exemptions.
. For purposes of this section, "floral or ornamental products or services" means floral arrangements, cut flowers, floral bouquets, potted plants, balloons, floral designs, and related products and services.

. It is a violation for a provider or vendor of floral or ornamental products or services to misrepresent the geographic location of its business by doing either of the following:

.. Listing a local telephone number in any advertisement or listing, unless the advertisement or listing identifies the true physical address, including the city, of the provider's or vendor's business; or

.. Listing a fictitious business name or an assumed business name in any advertisement or listing if both of the following criteria are met:

... The name of the business misrepresents the provider's or vendor's geographic location; and

... The advertisement or listing does not identify the true physical address, including the city and state, of the provider's or vendor's business.

. A violation of this section is punishable, exclusively, by a fine not to exceed two hundred fifty dollars.

. This section does not create or impose any duty or obligation on a person other than a vendor or provider of floral or ornamental products or services.

. This section does not apply to any of the following:

.. A publisher of a telephone directory or other publication or a provider of a directory assistance service publishing or providing information about another business.

.. An internet web site that aggregates and provides information about other businesses.

.. An owner or publisher of a print advertising medium providing information about other businesses.

.. An internet service provider.

.. An internet service that displays or distributes advertisements for other businesses.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1422.SL.pdf?cite=2015%20c%20168%20§%202[2015 c 168 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1471-S.SL.pdf?cite=1999%20c%20156%20§%202[1999 c 156 § 2]; ]

