= 19.186 - Roofing and siding contractors and salespersons.
:toc:

== 19.186.005 - Findings—Intent.
The legislature finds that many homeowners are solicited by siding and roofing contractors to purchase home improvements. Some contractors misrepresent the financing terms or the cost of the improvements, preventing the homeowner from making an informed decision about whether the improvements are affordable. The result is that many homeowners face financial hardship including the loss of their homes through foreclosure. The legislature declares that this is a matter of public interest. It is the intent of the legislature to establish rules of business practice for roofing and siding contractors to promote honesty and fair dealing with homeowners.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6124-S.SL.pdf?cite=1994%20c%20285%20§%201[1994 c 285 § 1]; ]

== 19.186.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Roofing or siding contract" means an agreement between a roofing or siding contractor or salesperson and a homeowner that includes, in part, an agreement to install, repair or replace residential roofing or siding for a total cost including labor and materials in excess of one thousand dollars.

This chapter does not apply to the following contracts:

.. Residential remodel or repair contracts where the cost specified for roofing or siding is less than twenty percent of the total contract price;

.. Contracts where the roofing or siding is part of a contract to build a new dwelling or an addition that provides additional living space;

.. Contracts for emergency repairs made necessary by a natural disaster such as an earthquake, windstorm, or hurricane, or after a fire in the dwelling;

.. Homes being prepared for resale; or

.. Roofing or siding contracts in which the homeowner was not directly solicited by a roofing or siding contractor or salesperson. If a roofing or siding contractor or roofing or siding salesperson generally does business by soliciting, it shall be a rebuttable presumption that any roofing or siding contract entered into with a homeowner shall have been the result of a solicitation.

. "Roofing or siding contractor" means a person who owns or operates a contracting business that purports to install, repair, or replace or subcontracts to install, repair, or replace residential roofing or siding.

. "Roofing or siding salesperson" means a person who solicits, negotiates, executes, or otherwise endeavors to procure a contract with a homeowner to install, repair, or replace residential roofing or siding on behalf of a roofing or siding contractor.

. "Residential roofing or siding" means roofing or siding installation, repair or replacement for an existing single-family dwelling or multiple-family dwelling of four or less units, provided that this does not apply to a residence under construction.

. "Person" includes an individual, corporation, company, partnership, joint venture, or a business entity.

. "Siding" means material used to cover the exterior walls of a residential dwelling, excluding paint application.

. [Empty]
.. "Solicit" means to initiate contact with the homeowner for the purpose of selling or installing roofing or siding by one of the following methods:

... Door-to-door contact;

... Telephone contact;

... Flyers left at a residence; or

... Other promotional advertisements which offer gifts, cash, or services if the homeowner contacts the roofing or siding contractor or salesperson, except for newspaper advertisements which offer a seasonal discount.

.. "Solicit" does not include:

... Calls made in response to a request or inquiry by the homeowner; or

... Calls made to homeowners who have prior business or personal contact with the residential roofing or siding contractor or salesperson.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6124-S.SL.pdf?cite=1994%20c%20285%20§%202[1994 c 285 § 2]; ]

== 19.186.020 - Written contract—Requirements—Right to rescind—Notice.
A roofing or siding contract shall be in writing. A copy of the contract shall be given to the homeowner at the time the homeowner signs the contract. The contract shall be typed or printed legibly and contain the following provisions:

. An itemized list of all work to be performed;

. The grade, quality, or brand name of materials to be used;

. The dollar amount of the contract;

. The name and address of the roofing or siding salesperson;

. The name, address, and contractor's registration number of the roofing or siding contractor;

. A statement as to whether all or part of the work is to be subcontracted to another person;

. The contract shall require the homeowner to disclose whether he or she intends to obtain a loan in order to pay for all or part of the amount due under the contract;

. If the customer indicates that he or she intends to obtain a loan to pay for a portion of the roofing or siding contract, the homeowner shall have the right to rescind the contract within three business days of receiving truth-in-lending disclosures or three business days of receiving written notification that the loan application was denied, whichever date is later; and

. The contract shall provide the following notice in ten-point boldface type in capital letters:

"CUSTOMER'S RIGHT TO CANCEL

IF YOU HAVE INDICATED IN THIS CONTRACT THAT YOU INTEND TO OBTAIN A LOAN TO PAY FOR ALL OR PART OF THE WORK SPECIFIED IN THE CONTRACT, YOU HAVE THE RIGHT TO CHANGE YOUR MIND AND CANCEL THIS CONTRACT WITHIN THREE DAYS OF THE DATE WHEN THE LENDER PROVIDES YOU WITH YOUR TRUTH-IN-LENDING DISCLOSURE STATEMENT OR THE DATE WHEN YOU RECEIVE WRITTEN NOTIFICATION THAT YOUR LOAN WAS DENIED.

BE SURE THAT ALL PROMISES MADE BY YOUR CONTRACTOR ARE PUT IN WRITING BEFORE YOU SIGN THIS CONTRACT."

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6124-S.SL.pdf?cite=1994%20c%20285%20§%203[1994 c 285 § 3]; ]

== 19.186.030 - Waiting period to begin work if customer obtaining loan—Effect.
If the customer indicates that he or she intends to obtain a loan to pay for all or part of the cost of the roofing or siding contract, the roofing or siding contractor shall not begin work until after the homeowner's rescission rights provided in RCW 19.186.020(9) have expired. If the roofing or siding contractor commences work under the contract before the homeowner's rescission rights have expired, the roofing or siding contractor or salesperson shall be prohibited from enforcing terms of the contract, including claims for labor or materials, in a court of law and shall terminate any security interest or statutory lien created under the transaction within twenty days of receiving written rescission of the contract from the customer.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6124-S.SL.pdf?cite=1994%20c%20285%20§%204[1994 c 285 § 4]; ]

== 19.186.040 - Liability of contract purchaser or assignee—Notice.
A person who purchases or is otherwise assigned a roofing or siding contract shall be subject to all claims and defenses with respect to the contract that the homeowner could assert against the siding or roofing contractor or salesperson. A person who sells or otherwise assigns a roofing or siding contract shall include a prominent notice of the potential liability under this section.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6124-S.SL.pdf?cite=1994%20c%20285%20§%205[1994 c 285 § 5]; ]

== 19.186.050 - Violation—Consumer protection act.
The legislature finds and declares that a violation of this chapter substantially affects the public interest and is an unfair and deceptive act or practice and unfair method of competition in the conduct of trade or commerce as set forth under chapter 19.86 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6124-S.SL.pdf?cite=1994%20c%20285%20§%206[1994 c 285 § 6]; ]

== 19.186.060 - Liability for failure to comply with chapter.
A roofing or siding contractor or salesperson who fails to comply with the requirements of this chapter shall be liable to the homeowner for any actual damages sustained by the person as a result of the failure. Nothing in this section shall limit any cause of action or remedy available under RCW 19.186.050 or chapter 19.86 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6124-S.SL.pdf?cite=1994%20c%20285%20§%207[1994 c 285 § 7]; ]

