= 19.188 - Electronic media violence.
:toc:

== 19.188.010 - Finding.
The legislature finds that, to the extent that electronic media, including television, motion pictures, video games, and entertainment uses of virtual reality are conducive to increased violent behaviors, especially in children, the state has a duty to protect the public health and safety.

Many parents, educators, and others are concerned about protecting children and youth from the negative influences of the media, and want more information about media content and more control over media contact with their children.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=1994%20sp.s.%20c%207%20§%20801[1994 sp.s. c 7 § 801]; ]

== 19.188.020 - Television time/channel locks.
All new televisions sold in this state after January 1, 1995, shall be equipped with a time/channel lock or shall be sold with an offer to the customer to purchase a channel blocking device, or other device that enables a person to regulate a child's access to unwanted television programming. All cable television companies shall make available to all customers at the company's cost the opportunity to purchase a channel blocking device, or other device that enables a person to regulate a child's access to unwanted television programming. The commercial television sellers and cable television companies shall offer time/channel locks to their customers, when these devices are available. Notice of this availability shall be clearly made to all existing customers and to all new customers at the time of their signing up for service.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=1994%20sp.s.%20c%207%20§%20803[1994 sp.s. c 7 § 803]; ]

== 19.188.030 - Library access policies.
The legislature finds that, as a matter of public health and safety, access by minors to violent videos and violent video games is the responsibility of parents and guardians.

Public libraries, with the exception of university, college, and community college libraries, shall establish policies on minors' access to violent videos and violent video games. Libraries shall make their policies known to the public in their communities.

Each library system shall formulate its own policies, and may, in its discretion, include public hearings, consultation with community networks as defined under chapter 70.190 RCW, or consultation with the Washington library association in the development of its policies.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=1994%20sp.s.%20c%207%20§%20806[1994 sp.s. c 7 § 806]; ]

== 19.188.040 - Video game rating system—Video game retailers shall post signs—Location—Information.
. The definitions in this subsection apply throughout this section.

.. "Video game" means an object or device that stores recorded data or instructions, receives data or instructions generated by a person who uses it, and, by processing the data or instructions, creates an interactive game capable of being played, viewed, or experienced on or through a computer, gaming system, console, or other technology.

.. "Video game retailer" means a person who sells or rents video games to the public.

.. "Point of sale" means the location in the retail establishment at which a transaction occurs resulting in the sale or rental of a video game.

. Every video game retailer shall post signs providing information to consumers about the existence of a nationally recognized video game rating system, or notifying consumers that a rating system is available, to aid in the selection of a game if such a rating system is in existence.

. The signs shall be posted within the retail establishment in prominent areas near the video game displays and points of sale. The signs and lettering shall be clearly visible to consumers at these locations.

. A video game retailer shall make available to consumers, upon request, information that explains the video game rating system.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1366-S.SL.pdf?cite=2005%20c%20230%20§%201[2005 c 230 § 1]; ]

