= 19.138 - Sellers of travel.
:toc:

== 19.138.010 - Legislative finding and declaration.
The legislature finds and declares that advertising, sales, and business practices of certain sellers of travel have worked financial hardship upon the people of this state; that the travel business has a significant impact upon the economy and well-being of this state and its people; that problems have arisen regarding certain sales of travel; and that the public welfare requires registration of sellers of travel in order to eliminate unfair advertising, sales and business practices. The legislature further finds it necessary to establish standards that will safeguard the people against financial hardship and to encourage fair dealing and prosperity in the travel business.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%201[1994 c 237 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c283.pdf?cite=1986%20c%20283%20§%201[1986 c 283 § 1]; ]

== 19.138.021 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Department" means the department of licensing.

. "Director" means the director of licensing or the director's designee.

. "Sale of travel-related benefits" means the sale of travel services if the travel services are not identified at the time of the sale with respect to dates, price, or location and includes:

.. Sales of travel club memberships;

.. Sales of vacation certificates or other documents that purport to grant the holder of the certificate or other document the ability to obtain future travel services, with or without additional consideration; or

.. Sales of travel-industry member benefits including those through either or both the issuance and sale or the consulting with or advising for consideration of persons in connection with the obtaining of international airlines travel agent network identification cards or memberships.

. "Travel club" means a seller of travel that sells memberships to consumers, where the initial membership or maintenance dues are at least twice the amount of the annual membership or maintenance dues.

. "Seller of travel-related benefits" means a person, firm, or corporation that transacts business with Washington consumers for the sale of travel-related benefits.

. "Seller of travel" means a person, firm, or corporation both inside and outside the state of Washington, who transacts business with Washington consumers.

.. "Seller of travel" includes a travel agent and any person who is an independent contractor or outside agent for a travel agency or other seller of travel whose principal duties include consulting with and advising persons concerning travel arrangements or accommodations in the conduct or administration of its business. If a seller of travel is employed by a seller of travel who is registered under this chapter, the employee need not also be registered.

.. "Seller of travel" does not include:

... An air carrier;

... An owner or operator of a vessel, including an ocean common carrier as defined in 46 U.S.C. App. 1702(18), an owner or charterer of a vessel that is required to establish its financial responsibility in accordance with the requirements of the federal maritime commission, 46 U.S.C. App. 817 (e), and a steamboat company whether or not operating over and upon the waters of this state;

... A motor carrier;

... A rail carrier;

.. A charter party carrier of passengers as defined in RCW 81.70.020;

.. An auto transportation company as defined in RCW 81.68.010;

.. A hotel or other lodging accommodation;

.. An affiliate of any person or entity described in (i) through (vii) of this subsection (6)(b) that is primarily engaged in the sale of travel services provided by the person or entity. For purposes of this subsection (6)(b)(viii), an "affiliate" means a person or entity owning, owned by, or under common ownership, with "owning," "owned," and "ownership" referring to equity holdings of at least eighty percent;

... Direct providers of transportation by air, sea, or ground, or hotel or other lodging accommodations who do not book or arrange any other travel services.

. "Travel services" includes transportation by air, sea, or ground, hotel or any lodging accommodations, package tours, or vouchers or coupons to be redeemed for future travel or accommodations for a fee, commission, or other valuable consideration.

. "Advertisement" includes, but is not limited to, a written or graphic representation in a card, brochure, newspaper, magazine, directory listing, or display, and oral, written, or graphic representations made by radio, television, or cable transmission that relates to travel services.

. "Transacts business with Washington consumers" means to directly offer or sell travel services or travel-related benefits to Washington consumers, including the placement of advertising in media based in the state of Washington or that is primarily directed to Washington residents. Advertising placed in national print or electronic media alone does not constitute "transacting business with Washington consumers." Those entities who only wholesale travel services are not "transacting business with Washington consumers" for the purposes of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5219-S.SL.pdf?cite=2001%20c%2044%20§%201[2001 c 44 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2400.SL.pdf?cite=2000%20c%20171%20§%2073[2000 c 171 § 73]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1704-S.SL.pdf?cite=1996%20c%20180%20§%201[1996 c 180 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%202[1994 c 237 § 2]; ]

== 19.138.030 - Advertising—Restrictions—Records.
A seller of travel shall not advertise that any travel services are or may be available unless he or she has, prior to the advertisement, determined that the product advertised was available at the time the advertising was placed. This determination can be made by the seller of travel either by use of an airline computer reservation system, or by written confirmation from the vendor whose program is being advertised.

It is the responsibility of the seller of travel to keep written or printed documentation of the steps taken to verify that the advertised offer was available at the time the advertising was placed. These records are to be maintained for at least one year after the placement of the advertisement.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2090-S.SL.pdf?cite=1999%20c%20238%20§%201[1999 c 238 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1704-S.SL.pdf?cite=1996%20c%20180%20§%202[1996 c 180 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%2010[1994 c 237 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c283.pdf?cite=1986%20c%20283%20§%203[1986 c 283 § 3]; ]

== 19.138.040 - Written statement by seller of travel—Contents.
At or prior to the time of full or partial payment for any travel services, the seller of travel shall furnish to the person making the payment a written statement conspicuously setting forth the information contained in subsections (1) through (6) of this section. However, if payment is made other than in person, the seller of travel shall transmit to the person making the payment the written statement required by this section within three business days of receipt or processing of the payment. The written statement shall contain the following information:

. The name and business address and telephone number of the seller of travel.

. The amount paid, the date of such payment, the purpose of the payment made, and an itemized statement of the balance due, if any.

. The registration number of the seller of travel required by this chapter.

. The name of the vendor with whom the seller of travel has contracted to provide travel arrangements for a consumer and all pertinent information relating to the travel as known by the seller of travel at the time of booking. The seller of travel will make known further details as soon as received from the vendor. All information will be provided with final documentation.

. An advisory regarding the penalties that would be charged in the event of a cancellation or change by the customer. This may contain either: (a) The specific amount of cancellation and change penalties; or (b) the following statement: "Cancellation and change penalties apply to these arrangements. Details will be provided upon request."

. A statement in eight-point boldface type in substantially the following form:

"If transportation or other services are canceled by the seller of travel, all sums paid to the seller of travel for services not performed in accordance with the contract between the seller of travel and the purchaser will be refunded within thirty days of receiving the funds from the vendor with whom the services were arranged, or if the funds were not sent to the vendor, the funds shall be returned within fourteen days after cancellation by the seller of travel to the purchaser unless the purchaser requests the seller of travel to apply the money to another travel product and/or date."

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2090-S.SL.pdf?cite=1999%20c%20238%20§%202[1999 c 238 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1704-S.SL.pdf?cite=1996%20c%20180%20§%203[1996 c 180 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%2011[1994 c 237 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c283.pdf?cite=1986%20c%20283%20§%204[1986 c 283 § 4]; ]

== 19.138.050 - Cancellation—Refund—Material misrepresentation—Exception.
. If the transportation or other services contracted for are canceled, or if the money is to be refunded for any reason, the seller of travel shall refund to the person with whom it contracts for travel services, the money due the person within thirty days of receiving the funds from the vendor with whom the services were arranged. If the funds were not sent to the vendor and remain in the possession of the seller of travel, the funds shall be refunded within fourteen days.

. Any material misrepresentation with regard to the transportation and other services offered shall be deemed to be a cancellation necessitating the refund required by this section.

. When travel services are paid to a vendor and charged to a consumer's credit card by the seller of travel, and the arrangements are subsequently canceled by the consumer, the vendor, or the seller of travel, any refunds to the consumer's credit card must be applied for within ten days from the date of cancellation.

. The seller of travel shall not be obligated to refund any cancellation penalties imposed by the vendor with whom the services were arranged if these penalties were disclosed in the statement required under RCW 19.138.040.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%2012[1994 c 237 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c283.pdf?cite=1986%20c%20283%20§%205[1986 c 283 § 5]; ]

== 19.138.090 - Application of chapter to public charter operators.
This chapter does not apply to the sale of public transportation by a public charter operator who is complying with regulations of the United States department of transportation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c283.pdf?cite=1986%20c%20283%20§%209[1986 c 283 § 9]; ]

== 19.138.100 - Registration—Number posting, use—Duplicates—Fee—Assignment, transfer—New owner—Exemption.
No person, firm, or corporation may act or hold itself out as a seller of travel unless, prior to engaging in the business of selling or advertising to sell travel services or travel-related benefits, the person, firm, or corporation registers with the director under this chapter and rules adopted under this chapter.

. The registration number must be conspicuously posted in the place of business and must be included in all advertisements. Sellers of travel are not required to include registration numbers on institutional advertising. For the purposes of this subsection, "institutional advertising" is advertising that does not include prices or dates for travel services.

. The director shall issue duplicate registrations upon payment of a duplicate registration fee to valid registration holders operating more than one office. The duplicate registration fee for each office shall be an amount equal to the original registration fee.

. No registration is assignable or transferable.

. If a registered seller of travel sells his or her business, when the new owner becomes responsible for the business, the new owner must comply with all provisions of this chapter, including registration.

. If a seller of travel is employed by or under contract as an independent contractor or an outside agent of a seller of travel who is registered under this chapter, the employee, independent contractor, or outside agent need not also be registered if:

.. The employee, independent contractor, or outside agent is conducting business as a seller of travel in the name of and under the registration of the registered seller of travel; and

.. All money received for travel services by the employee, independent contractor, or outside agent is collected in the name of the registered seller of travel and processed by the registered seller of travel as required under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5219-S.SL.pdf?cite=2001%20c%2044%20§%204[2001 c 44 § 4]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2090-S.SL.pdf?cite=1999%20c%20238%20§%203[1999 c 238 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1704-S.SL.pdf?cite=1996%20c%20180%20§%204[1996 c 180 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%203[1994 c 237 § 3]; ]

== 19.138.110 - Registration—Application—Form—Rules—Report.
An application for registration as a seller of travel shall be submitted in the form prescribed by rule by the director, and shall contain but not be limited to the following:

. The name, address, and telephone number of the seller of travel;

. Proof that the seller of travel holds a valid business license in the state of its principal state of business;

. A registration fee in an amount determined under RCW 43.24.086;

. The names, business addresses, and business phone numbers of all employees, independent contractors, or outside agents who sell travel and are covered by the seller of travel's registration. This subsection shall not apply to the out-of-state employees of a corporation that issues a class of equity securities registered under section 12 of the securities exchange act of 1934, and any subsidiary, the majority of voting stock of which is owned by the corporation;

. A report prepared and signed by a bank officer, licensed public accountant, or certified public accountant or other report, approved by the director, that verifies that the seller of travel maintains a trust account at a federally insured financial institution located in Washington state, or other approved account, the location and number of that trust account or other approved account, and verifying that the account exists as required by RCW 19.138.140. The director, by rule, may permit alternatives to the report that provides for at least the same level of verification.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1704-S.SL.pdf?cite=1996%20c%20180%20§%205[1996 c 180 § 5]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%204[1994 c 237 § 4]; ]

== 19.138.120 - Registration—Renewal—Refusal—Notice—Hearing.
. Each seller of travel shall renew its registration on or before July 1st of every year or as otherwise determined by the director.

. Renewal of a registration is subject to the same provisions covering disciplinary action as a registration originally issued.

. The director may refuse to renew a registration for any of the grounds set out under RCW 19.138.130 and 18.235.130, and where the past conduct of the applicant affords reasonable grounds for belief that the applicant will not carry out the applicant's duties in accordance with law and with integrity and honesty. The director shall promptly notify the applicant in writing by certified mail of its intent to refuse to renew the registration. The registrant may request a hearing on the refusal as provided in RCW 18.235.050. The director may permit the registrant to honor commitments already made to its customers, but no new commitments may be incurred, unless the director is satisfied that all new commitments are completely bonded or secured to ensure that the general public is protected from loss of money paid to the registrant.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20277[2002 c 86 § 277]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2090-S.SL.pdf?cite=1999%20c%20238%20§%204[1999 c 238 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%205[1994 c 237 § 5]; ]

== 19.138.130 - Unprofessional conduct—Grounds—Registration—Revocation and reinstatement—Support order, noncompliance.
. In addition to the unprofessional conduct described in RCW 18.235.130, the director may take disciplinary action based on the following conduct, acts, or conditions if the applicant or registrant:

.. Was previously the holder of a registration issued under this chapter, and the registration was revoked for cause and never reissued by the director, or the registration was suspended for cause and the terms of the suspension have not been fulfilled;

.. Suffers a judgment in a civil action involving willful fraud, misrepresentation, or conversion;

.. Has violated this chapter or failed to comply with a rule adopted by the director under this chapter; or

.. Has failed to display the registration as provided in this chapter.

. If the seller of travel is found in violation of this chapter or in violation of the consumer protection act, chapter 19.86 RCW, by the entry of a judgment or by settlement of a claim, the director may revoke the registration of the seller of travel, and the director may reinstate the registration at the director's discretion.

. The director shall immediately suspend the license or certificate of a person who has been certified pursuant to RCW 74.20A.320 by the department of social and health services as a person who is not in compliance with a support order. If the person has continued to meet all other requirements for reinstatement during the suspension, reissuance of the license or certificate shall be automatic upon the director's receipt of a release issued by the department of social and health services stating that the licensee is in compliance with the order.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20278[2002 c 86 § 278]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2090-S.SL.pdf?cite=1999%20c%20238%20§%205[1999 c 238 § 5]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20852[1997 c 58 § 852]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1704-S.SL.pdf?cite=1996%20c%20180%20§%206[1996 c 180 § 6]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%206[1994 c 237 § 6]; ]

== 19.138.140 - Trust account—Filing—Notice of change—Other funds or accounts—Rules—Exceptions.
. A seller of travel shall deposit in a trust account maintained in a federally insured financial institution located in Washington state, or other account approved by the director, all sums held for more than five business days that are received from a person or entity, for retail travel services offered by the seller of travel. This subsection does not apply to travel services sold by a seller of travel, when payments for the travel services are made through the airlines reporting corporation.

. The trust account or other approved account required by this section shall be established and maintained for the benefit of any person or entity paying money to the seller of travel. The seller of travel shall not in any manner encumber the amounts in trust and shall not withdraw money from the account except the following amounts may be withdrawn at any time:

.. Partial or full payment for travel services to the entity directly providing the travel service;

.. Refunds as required by this chapter;

.. The amount of the sales commission;

.. Interest earned and credited to the trust account or other approved account;

.. Remaining funds of a purchaser once all travel services have been provided or once tickets or other similar documentation binding upon the ultimate provider of the travel services have been provided; or

.. Reimbursement to the seller of travel for agency operating funds that are advanced for a customer's travel services.

. The seller of travel may deposit noncustomer funds into the trust account as needed in an amount equal to a deficiency resulting from dishonored customer payments made by check, draft, credit card, debit card, or other negotiable instrument.

. At the time of registration, the seller of travel shall file with the department the account number and the name of the financial institution at which the trust account or other approved account is held as set forth in RCW 19.138.110. The seller of travel shall notify the department of any change in the account number or location within one business day of the change.

. The director, by rule, may allow for the use of other types of funds or accounts only if the protection for consumers is no less than that provided by this section.

. The seller of travel need not comply with the requirements of this section if all of the following apply, except as exempted in subsection (1) of this section:

.. The payment is made by credit card;

.. The seller of travel does not deposit, negotiate, or factor the credit card charge or otherwise seek to obtain payment of the credit card charge to any account over which the seller of travel has any control; and

.. If the charge includes transportation, the carrier that is to provide the transportation processes the credit card charge, or if the charge is only for services, the provider of services processes the credit card charges.

. The seller of travel need not maintain a trust account nor comply with the trust account provisions of this section if the seller of travel:

.. [Empty]
... Files and maintains a surety bond approved by the director in an amount of not less than ten thousand nor more than fifty thousand dollars, as determined by rule by the director based on the gross income of business conducted for Washington state residents by the seller of travel during the prior year. The bond shall be executed by the applicant as obligor by a surety company authorized to transact business in this state naming the state of Washington as obligee for the benefit of any person or persons who have suffered monetary loss by reason of the seller of travel's violation of this chapter or a rule adopted under this chapter. The bond shall be conditioned that the seller of travel will conform to and abide by this chapter and all rules adopted under this chapter, and shall reimburse any person or persons who suffer monetary loss by reason of a violation of this chapter or a rule adopted under this chapter.

... The bond must be continuous and may be canceled by the surety upon the surety giving written notice to the director of the surety's intent to cancel the bond. The cancellation is effective thirty days after the notice is received by the director.

... The applicant may obtain the bond directly from the surety or through other bonding arrangement as approved by the director.

... In lieu of a surety bond, the applicant may, upon approval by the director, file with the director a certificate of deposit, an irrevocable letter of credit, or such other instrument as is approved by the director by rule, drawn in favor of the director for an amount equal to the required bond.

.. Any person or persons who have suffered monetary loss by any act which constitutes a violation of this chapter or a rule adopted under this chapter may bring a civil action in court against the seller of travel and the surety upon such bond or approved alternate security of the seller of travel who committed the violation of this chapter or a rule adopted under this chapter or who employed the seller of travel who committed such violation. A civil action brought in court pursuant to the provisions of this section must be filed no later than one year following the later of the alleged violation of this chapter or a rule adopted under this chapter or completion of the travel by the customer; or

.. Is a member in good standing in a professional association, such as the United States tour operators association or national tour association, that is approved by the director and that provides or requires a member to provide a minimum of one million dollars in errors and professional liability insurance and provides a surety bond or equivalent protection in an amount of at least two hundred fifty thousand dollars for its member companies.

. If the seller of travel maintains its principal place of business in another state and maintains a trust account or other approved account in that state consistent with the requirement of this section, and if that seller of travel has transacted business within the state of Washington in an amount exceeding five million dollars for the preceding year, the out-of-state trust account or other approved account may be substituted for the in-state account required under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5167.SL.pdf?cite=2003%20c%2038%20§%201[2003 c 38 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2090-S.SL.pdf?cite=1999%20c%20238%20§%206[1999 c 238 § 6]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1704-S.SL.pdf?cite=1996%20c%20180%20§%207[1996 c 180 § 7]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%208[1994 c 237 § 8]; ]

== 19.138.150 - Standard of duties, care.
A seller of travel shall perform its duties reasonably and with ordinary care in providing travel services.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%209[1994 c 237 § 9]; ]

== 19.138.160 - Nonresident seller of travel—Director as attorney if none appointed—Service of process—Notice.
. A nonresident seller of travel soliciting business or selling travel in the state of Washington, by mail, telephone, or otherwise, either directly or indirectly, is deemed, absent any other appointment, to have appointed the director to be the seller of travel's true and lawful attorney upon whom may be served any legal process against that nonresident arising or growing out of a transaction involving travel services or the sale of travel-related benefits. That solicitation signifies the nonresident's agreement that process against the nonresident that is served as provided in this chapter is of the same legal force and validity as if served personally on the nonresident seller of travel.

. Service of process upon a nonresident seller of travel shall be made by leaving a copy of the process with the director. The fee for the service of process shall be determined by the director by rule. That service is sufficient service upon the nonresident if the plaintiff or plaintiff's attorney of record sends notice of the service and a copy of the process by certified mail before service or immediately after service to the defendant at the address given by the nonresident in a solicitation furnished by the nonresident, and the sender's post office receipt of sending and the plaintiff's or plaintiff's attorney's affidavit of compliance with this section are returned with the process in accordance with Washington superior court civil rules. Notwithstanding the foregoing requirements, however, once service has been made on the director as provided in this section, in the event of failure to comply with the requirement of notice to the nonresident, the court may order that notice be given that will be sufficient to apprise the nonresident.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5219-S.SL.pdf?cite=2001%20c%2044%20§%205[2001 c 44 § 5]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%2014[1994 c 237 § 14]; ]

== 19.138.170 - Director—Powers and duties.
The director has the following powers and duties:

. To adopt, amend, and repeal rules to carry out the purposes of this chapter;

. To establish fees;

. Upon receipt of a complaint, to inspect and audit the books and records of a seller of travel. The seller of travel shall immediately make available to the director those books and records as may be requested at the seller of travel's place of business or at a location designated by the director. For that purpose, the director shall have full and free access to the office and places of business of the seller of travel during regular business hours. When ten or more complaints have been received by either the department or the attorney general on a seller of travel within a period of ninety days, the department shall inspect and audit books and records of the seller of travel; and

. To do all things necessary to carry out the functions, powers, and duties set forth in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20279[2002 c 86 § 279]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2090-S.SL.pdf?cite=1999%20c%20238%20§%207[1999 c 238 § 7]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%2013[1994 c 237 § 13]; ]

== 19.138.1701 - Reimbursement of appropriated funds—Fees.
Any state funds appropriated to the department of licensing for implementation of chapter 237, Laws of 1994 for the biennium ending June 30, 1995, shall be reimbursed by June 30, 1997, by an assessment of fees sufficient to cover all costs of implementing chapter 237, Laws of 1994.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%2030[1994 c 237 § 30]; ]

== 19.138.180 - Director—Investigations—Publication of violation.
The director, in the director's discretion, may:

. Annually, or more frequently, make public or private investigations within or without this state as the director deems necessary to determine whether a registration should be subject to disciplinary action, or whether a person has violated or is about to violate this chapter or a rule adopted or order issued under this chapter, or to aid in the enforcement of this chapter or in the prescribing of rules and forms of this chapter;

. Publish information concerning a violation of this chapter or a rule adopted or order issued under this chapter; and

. Investigate complaints concerning practices by sellers of travel for which registration is required by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20280[2002 c 86 § 280]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%2015[1994 c 237 § 15]; ]

== 19.138.200 - Director or individuals acting on director's behalf—Immunity.
The director or individuals acting on the director's behalf are immune from suit in any action, civil or criminal, based on acts performed in the course of their duties in the administration and enforcement of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20281[2002 c 86 § 281]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%2020[1994 c 237 § 20]; ]

== 19.138.240 - Violations—Civil penalties—Failure to pay.
. A civil penalty shall be imposed by the court for each violation of this chapter in an amount not less than five hundred dollars nor more than two thousand dollars per violation.

. If a person fails to pay an assessment after it has become a final and unappealable order, or after the court has entered final judgment in favor of the state, the director may recover the amount assessed by action in the appropriate superior court. In the action, the validity and appropriateness of the final order imposing the penalty shall not be subject to review.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20282[2002 c 86 § 282]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%2021[1994 c 237 § 21]; ]

== 19.138.250 - Violation—Restitution assessed by director.
The director may assess against a person or organization that violates this chapter, or a rule adopted under this chapter, the full amount of restitution as may be necessary to restore to a person an interest in money or property, real or personal, that may have been acquired by means of an act prohibited by or in violation of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%2022[1994 c 237 § 22]; ]

== 19.138.260 - Registration prerequisite to suit.
In order to maintain or defend a lawsuit, a seller of travel must be registered with the department as required by this chapter and rules adopted under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%2023[1994 c 237 § 23]; ]

== 19.138.270 - Violations—Giving false information—Criminal penalties.
. Each person who knowingly violates this chapter or who knowingly gives false or incorrect information to the director, attorney general, or county prosecuting attorney in filing statements required by this chapter, whether or not the statement or report is verified, is guilty of a gross misdemeanor punishable under chapter 9A.20 RCW.

. A person who violates this chapter or who gives false or incorrect information to the director, attorney general, or county prosecuting attorney in filing statements required by this chapter, whether or not the statement or report is verified, is guilty of a misdemeanor punishable under chapter 9A.20 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%2024[1994 c 237 § 24]; ]

== 19.138.280 - Action for damages—Costs, attorneys' fees—No limitation of consumer protection act.
In addition to any other penalties or remedies under chapter 19.86 RCW, a person who is injured by a violation of this chapter may bring an action for recovery of actual damages, including court costs and attorneys' fees. No provision in this chapter shall be construed to limit any right or remedy provided under chapter 19.86 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%2028[1994 c 237 § 28]; ]

== 19.138.290 - Violations—Application of consumer protection act.
The legislature finds that the practices governed by this chapter are matters vitally affecting the public interest for the purpose of applying the consumer protection act, chapter 19.86 RCW. Any violation of this chapter is not reasonable in relation to the development and preservation of business and is an unfair and deceptive act or practice and unfair method of competition in the conduct of trade or commerce in violation of RCW 19.86.020. Remedies provided by chapter 19.86 RCW are cumulative and not exclusive.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%2027[1994 c 237 § 27]; ]

== 19.138.310 - Filing public records—Making information public for public interest.
All information, documents, and reports filed with the director under this chapter are matters of public record and shall be open to public inspection, subject to reasonable regulation. The director may make public, on a periodic or other basis, the information as may be necessary or appropriate in the public interest concerning the registration, reports, and information filed with the director or any other matters to the administration and enforcement of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%2026[1994 c 237 § 26]; ]

== 19.138.320 - Contract for sale of travel-related benefits—Cancellation—Process—Seven calendar days—Written disclosure required.
. A contract for the sale of travel-related benefits may be canceled at the option of the purchaser if the purchaser sends notice of the cancellation by certified mail, return receipt requested, to the seller of travel-related benefits at the address contained in the contract and if the notice is postmarked not later than midnight of the seventh calendar day following the day on which the contract is signed or any membership card and all membership materials are received by the purchaser, whichever is later. In addition to this cancellation right, a purchaser who signs a contract for the sale of travel-related benefits of any description from a seller of travel-related benefits without having received the written disclosures required in subsection (2) of this section has cancellation rights until seven calendar days after the receipt of the written disclosures. A purchaser must request cancellation of a contract by sending the notice of cancellation by certified mail, return receipt requested, postmarked not later than midnight of the seventh calendar day following the day on which the contract is signed, any membership card and all membership materials are received by the purchaser, or the day on which the disclosures were actually received, whichever is later, to the seller of travel-related benefits at the address contained in the contract. The purchaser may use the cancellation form prescribed in subsection (2) of this section, however, notice of cancellation is sufficient if it indicates the intention of the purchaser not to be bound by the contract. The purchaser's right of cancellation of a contract for the sale of travel-related benefits may not be waived.

. A contract for the sale of travel-related benefits must include the following statement in at least ten-point bold-face type immediately before the space for the purchaser's signature:

"Purchaser's right to cancel: You may cancel this contract without any cancellation fee or other penalty, or stated reason for doing so, by sending notice of cancellation by certified mail, return receipt requested, to . . . (insert name of the seller of travel-related benefits) at the address indicated below. The notice must be postmarked by midnight of the seventh calendar day following the day on which this contract is signed by you or the day any membership card and all membership materials are received by you, whichever is later. The day on which the contract was signed is not included as a "calendar day," and if the seventh calendar day falls on a Sunday or legal holiday, then the right to cancel this contract expires on the day immediately following that Sunday or legal holiday.

TO CANCEL THIS CONTRACT, SEND A COPY OF THIS NOTICE OF CANCELLATION OR OTHER WRITTEN NOTICE OF CANCELLATION TO:

. . . . . . . . . . .

(Name of Seller)

. . . . . . . . . . .

(Address of Seller)



(Date)

I HEREBY CANCEL THIS CONTRACT

(Date)

. . . . . . . . . . .

(Purchaser's Signature)

. . . . . . . . . . .

(Printed Name)

. . . . . . . . . . .

(Purchaser's Address)"

. Within seven calendar days following timely receipt of notice of cancellation from the purchaser, the seller of travel-related benefits shall provide evidence that the contract has been canceled and return any money or other consideration paid by the purchaser. However, the seller of travel-related benefits may retain payments made for specific travel services utilized by the purchaser.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5219-S.SL.pdf?cite=2001%20c%2044%20§%202[2001 c 44 § 2]; ]

== 19.138.330 - Uniform regulation of business and professions act.
The uniform regulation of business and professions act, chapter 18.235 RCW, governs unlicensed practice, the issuance and denial of licenses, and the discipline of licensees under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20283[2002 c 86 § 283]; ]

== 19.138.340 - Restrictions regarding promoting prostitution, commercial sexual abuse of a minor, or other commercial sex acts.
. No seller of travel shall engage in any of the following:

.. Promoting travel for prostitution or promoting travel for commercial sexual abuse of a minor;

.. Selling, advertising, or otherwise offering to sell travel services or facilitate travel:

... For the purposes of engaging in a commercial sex act;

... That consists of tourism packages or activities using and offering sexual acts as an enticement for tourism; or

... That provides, purports to provide access to, or facilitates the availability of sex escorts or sexual services.

. For the purposes of this section:

.. "Commercial sex act" means any sexual contact, as defined in chapter 9A.44 RCW, for which anything of value is given to or received by any person.

.. "Sexual act" means any sexual contact as defined in chapter 9A.44 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5718-S.SL.pdf?cite=2007%20c%20368%20§%206[2007 c 368 § 6]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6731.SL.pdf?cite=2006%20c%20250%20§%203[2006 c 250 § 3]; ]

== 19.138.901 - Effective date—1986 c 283.
This act shall take effect January 1, 1987.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c283.pdf?cite=1986%20c%20283%20§%2012[1986 c 283 § 12]; ]

== 19.138.903 - Effective date—1994 c 237.
Sections 1 through 29 of this act shall take effect January 1, 1996.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%2033[1994 c 237 § 33]; ]

== 19.138.904 - Implementation—1994 c 237.
The director of licensing, beginning July 1, 1995, may take such steps as are necessary to ensure that this act is implemented on its *effective date[s].

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=1994%20c%20237%20§%2035[1994 c 237 § 35]; ]

