= 19.270 - Computer spyware.
:toc:

== 19.270.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Advertisement" means a communication, the primary purpose of which is the commercial promotion of a commercial product or service, including a communication on an internet website that is operated for a commercial purpose.

. "Computer software" means a sequence of instructions written in any programming language that is executed on a computer. "Computer software" does not include computer software that is a web page, or are data components of web pages that are not executable independently of the web page.

. "Damage" means any significant impairment to the integrity or availability of data, computer software, a system, or information.

. "Deceptive" means: (a) A materially false or fraudulent statement; or (b) a statement or description that omits or misrepresents material information in order to deceive an owner or operator.

. "Execute" means the performance of the functions or the carrying out of the instructions of the computer software.

. "Internet" means the global information system that is logically linked together by a globally unique address space based on the internet protocol (IP), or its subsequent extensions, and that is able to support communications using the transmission control protocol/internet protocol (TCP/IP) suite, or its subsequent extensions, or other IP-compatible protocols, and that provides, uses, or makes accessible, either publicly or privately, high level services layered on the communications and related infrastructure described in this subsection.

. "Owner or operator" means the owner or lessee of a computer, or someone using such computer with the owner's or lessee's authorization. "Owner or operator" does not include any person who owns a computer before the first retail sale of such computer.

. "Person" means any individual, partnership, corporation, limited liability company, or other organization, or any combination thereof.

. "Personally identifiable information" means any of the following with respect to an individual who is an owner or operator:

.. First name or first initial in combination with last name;

.. A home or other physical address including street name;

.. An electronic mail address;

.. A credit or debit card number, bank account number, or a password or access code associated with a credit or debit card or bank account;

.. Social security number, tax identification number, driver's license number, passport number, or any other government-issued identification number; or

.. Any of the following information in a form that personally identifies an owner or operator:

... Account balances;

... Overdraft history; or

... Payment history.

. "Procure" means to knowingly, or with conscious avoidance of knowledge, pay or provide other consideration to, or induce, another person to transmit on one's behalf.

. "Transmit" means to knowingly, or with conscious avoidance of knowledge, transfer, send, or make available computer software, or any component thereof, via the internet or any other medium, including local area networks of computers, other nonwire transmission, and disc or other data storage device. "Transmit" does not include any action by a person providing:

.. The internet connection, telephone connection, or other means of transmission capability through which the software was made available;

.. The storage or hosting of the software program or a web page through which the software was made available, unless the person providing the storage or hosting services knows or reasonably should know there is or will be a violation of this chapter, and participates in or ratifies the actions constituting the violation; or

.. An information location tool, such as a directory, index reference, pointer, or hypertext link, through which the user of the computer located the software, unless such person receives a direct economic benefit from the execution of such software on the computer.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2879-S.SL.pdf?cite=2008%20c%2066%20§%201[2008 c 66 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1012-S.SL.pdf?cite=2005%20c%20500%20§%201[2005 c 500 § 1]; ]

== 19.270.020 - Unlawful activities—Unauthorized transmission of software.
It is unlawful for a person, without the authorization of the owner or operator, to transmit, or procure the transmission of, software to the owner or operator's computer with actual knowledge or conscious avoidance of actual knowledge that the software does any of the following:

. Modifies, through deceptive means, settings that control any of the following:

.. The page that appears when an owner or operator launches an internet browser or similar computer software used to access and navigate the internet;

.. The default provider or web proxy the owner or operator uses to access or search the internet; 

.. The owner or operator's list of bookmarks used to access web pages; or

.. The toolbars or buttons of the owner or operator's internet browser or similar computer software used to access and navigate the internet;

. Collects, through intentionally deceptive means, personally identifiable information through the use of a keystroke-logging function or through extracting the information from the owner or operator's hard drive;

. Prevents, through intentionally deceptive means, an owner or operator's reasonable efforts to block the installation or execution of, or to disable, computer software;

. Misrepresents that computer software will be uninstalled or disabled by an owner or operator's action; 

. Through intentionally deceptive means, removes, disables, or renders inoperative security, antispyware, or antivirus computer software installed on the computer, or through intentionally deceptive means disables the ability of such computer software to update automatically;

. Accesses or uses the modem or internet service for such computer to cause damage to the computer or cause an owner or operator to incur financial charges for a service that is not authorized by the owner or operator;

. Opens multiple, sequential, stand-alone advertisements in the owner or operator's computer without the authorization of the owner or operator and that a reasonable computer user cannot close without turning off the computer or closing the internet browser;

. Uses the owner or operator's computer as part of an activity performed by a group of computers for the purpose of causing damage to another computer or person including, but not limited to, launching a denial of service attack;

. Transmits or relays commercial electronic mail or a computer virus from the owner or operator's computer, where the transmission or relaying is initiated by a person other than the owner or operator;

. Modifies any of the following settings related to the computer's access to, or use of, the internet:

.. Settings that protect information about the owner or operator in order to make unauthorized use of the owner or operator's personally identifiable information; or

.. Security settings in order to cause damage to a computer; or

. Prevents an owner or operator's reasonable efforts to block the installation of, or to disable, computer software by doing any of the following:

.. Presenting the owner or operator with an option to decline installation of computer software and with knowledge or conscious avoidance of knowledge that when the option is selected the installation nevertheless proceeds; or

.. Falsely representing that computer software has been disabled.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2879-S.SL.pdf?cite=2008%20c%2066%20§%202[2008 c 66 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1012-S.SL.pdf?cite=2005%20c%20500%20§%202[2005 c 500 § 2]; ]

== 19.270.040 - Unlawful activities—Installation or execution of software component—Deceptive misrepresentation.
It is unlawful for a person who is not an owner or operator to do any of the following with regard to the owner or operator's computer:

. Induce an owner or operator to install a computer software component onto the computer by deceptively misrepresenting the extent to which installing the software is necessary for maintenance, update, or repair of the computer or computer software, for security or privacy reasons, for the proper operation of the computer, in order to open, view, or play a particular type of content; or

. Induce an owner or operator to install a computer software component onto the computer by displaying a pop-up, web page, or other message that deceptively misrepresents the source of the message; or

. Deceptively cause the execution on the computer of a computer software component that causes the owner or operator to use the component in a manner that violates any other provision of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2879-S.SL.pdf?cite=2008%20c%2066%20§%203[2008 c 66 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1012-S.SL.pdf?cite=2005%20c%20500%20§%204[2005 c 500 § 4]; ]

== 19.270.050 - Application and construction of RCW  19.270.020 (5) through (11) or  19.270.040.
. Neither RCW 19.270.020 (5) through (11) nor 19.270.040 apply to any monitoring of, or interaction with, a subscriber's internet or other network connection or service, or a computer, by a telecommunications carrier, cable operator, computer hardware or software provider, or provider of information service or interactive computer service for network or computer security purposes, diagnostics, technical support, maintenance, repair, authorized updates of software or system firmware, authorized remote system management, or detection or prevention of the unauthorized use of or fraudulent or other illegal activities in connection with a network, service, or computer software, including scanning for and removing software under this chapter.

. This section shall not be construed to provide a defense to liability under the common law or any other state or federal law, nor shall it be construed as an affirmative grant of authority to engage in any of the activities listed in this section.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2879-S.SL.pdf?cite=2008%20c%2066%20§%204[2008 c 66 § 4]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1012-S.SL.pdf?cite=2005%20c%20500%20§%205[2005 c 500 § 5]; ]

== 19.270.060 - Who may bring an action—Damages—Attorneys' fees—Limit of damages.
. In addition to any other remedies provided by this chapter or any other provision of law, the attorney general, or a provider of computer software or owner of a website or trademark who is adversely affected by reason of a violation of this chapter, and whose action arises directly out of such person's status as a provider or owner, may bring an action against a person who violates this chapter to enjoin further violations and to recover either actual damages or one hundred thousand dollars per violation, whichever is greater.

. In an action under subsection (1) of this section, a court may increase the damages up to three times the damages allowed under subsection (1) of this section if the defendant has engaged in a pattern and practice of violating this chapter. The court may also award costs and reasonable attorneys' fees to the prevailing party.

. The amount of damages determined under subsection (1) or (2) of this section may not exceed two million dollars.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2879-S.SL.pdf?cite=2008%20c%2066%20§%205[2008 c 66 § 5]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1012-S.SL.pdf?cite=2005%20c%20500%20§%206[2005 c 500 § 6]; ]

== 19.270.070 - Intent—Chapter preempts local laws.
It is the intent of the legislature that this chapter is a matter of statewide concern. This chapter supersedes and preempts all rules, regulations, codes, ordinances, and other laws adopted by a city, county, city and county, municipality, or local agency regarding spyware and notices to consumers from computer software providers regarding information collection.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1012-S.SL.pdf?cite=2005%20c%20500%20§%207[2005 c 500 § 7]; ]

== 19.270.080 - Chapter  19.86 RCW not affected.
Chapter 500, Laws of 2005 does not add to, contract, alter, or amend any cause of action allowed under chapter 19.86 RCW and does not affect in any way the application of chapter 19.86 RCW to any future case or fact pattern.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1012-S.SL.pdf?cite=2005%20c%20500%20§%208[2005 c 500 § 8]; ]

