= 19.275 - Antipyramid promotional scheme act.
:toc:

== 19.275.010 - Findings.
The legislature finds that pyramid schemes, chain letters, and related illegal schemes are enterprises:

. That finance returns to participants through sums taken from newly attracted participants;

. In which new participants are promised large returns for their investment or contribution; and

. That involve unfair and deceptive sales tactics, including: Misrepresentations of sustainability, profitability and legality of the scheme, and false statements that the scheme is legal or approved by governmental agencies.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6416.SL.pdf?cite=2006%20c%2065%20§%201[2006 c 65 § 1]; ]

== 19.275.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Compensation" means payment, regardless of how it is characterized, of money, financial benefit, or thing of value. "Compensation" does not include payment based on the sale of goods or services to anyone who is purchasing the goods or services for actual use or consumption.

. "Consideration" means the payment, regardless of how it is characterized, of cash or the purchase of goods, services, or intangible property. "Consideration" does not include:

.. The purchase of goods or services furnished at cost to be used in making sales and not for resale;

.. The purchase of goods or services subject to a bona fide repurchase agreement as defined in subsection (5) of this section; or

.. Time and effort spent in pursuit of sales or recruiting activities.

. "Person" means natural persons, corporations, trusts, partnerships, incorporated or unincorporated associations, or any other legal entity.

. "Pyramid schemes" means any plan or operation in which a person gives consideration for the right or opportunity to receive compensation that is derived primarily from the recruitment of other persons as participants in the plan or operation, rather than from the bona fide sale of goods, services, or intangible property to a person or by persons to others. 

. [Empty]
.. "Repurchase agreement" means an enforceable agreement by the seller to repurchase, at the buyer's written request, all currently marketable inventory within one year from its date of purchase; and the refund must not be less than ninety percent of the original net cost, less any consideration received by the buyer when he or she bought the products being returned.

.. Products shall not be considered currently marketable if returned for repurchase after the products' commercially reasonable usable or shelf life has passed, or if it has been clearly disclosed to the buyer that the products are seasonal, discontinued, or special promotion products that are not subject to the repurchase obligation.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6416.SL.pdf?cite=2006%20c%2065%20§%202[2006 c 65 § 2]; ]

== 19.275.030 - Pyramid scheme—Prohibition.
. No person may establish, promote, operate, or participate in any pyramid scheme.

. A limitation as to the number of persons who may participate, or the presence of additional conditions affecting eligibility for the opportunity to receive compensation under the scheme, does not change the identity of the scheme as a pyramid scheme.

. It is not a defense under chapter 65, Laws of 2006 that a person, on giving consideration, obtains goods, services, or intangible property in addition to the right to receive compensation, nor is it a defense to designate the consideration a gift, donation offering, or other word of similar meaning.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6416.SL.pdf?cite=2006%20c%2065%20§%203[2006 c 65 § 3]; ]

== 19.275.040 - Application of the consumer protection act.
The legislature finds that the practices covered by this chapter are matters vitally affecting the public interest for the purpose of applying the consumer protection act, chapter 19.86 RCW. A violation of this chapter is not reasonable in relation to the development and preservation of business and is an unfair or deceptive act in trade or commerce and an unfair method of competition for the purpose of applying the consumer protection act, chapter 19.86 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6416.SL.pdf?cite=2006%20c%2065%20§%204[2006 c 65 § 4]; ]

== 19.275.900 - Short title—2006 c 65.
This act may be cited as the "antipyramid promotional scheme act."

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6416.SL.pdf?cite=2006%20c%2065%20§%205[2006 c 65 § 5]; ]

