= 19.205 - Structured settlement protection.
:toc:

== 19.205.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Annuity issuer" means an insurer that has issued a contract to fund periodic payments under a structured settlement.

. "Dependents" means a payee's spouse and minor children and all other persons for whom the payee is legally obligated to provide support, including alimony.

. "Discounted present value" means the present value of future payments determined by discounting such payments to the present using the most recently published applicable federal rate for determining the present value of an annuity, as issued by the United States internal revenue service.

. "Gross advance amount" means the sum payable to the payee or for the payee's account as consideration for a transfer of structured settlement payment rights before any reductions for transfer expenses or other deductions to be made from such consideration.

. "Independent professional advice" means advice of an attorney, certified public accountant, actuary, or other licensed professional adviser.

. "Interested parties" means, with respect to any structured settlement, the payee, any beneficiary irrevocably designated under the annuity contract to receive payments following the payee's death, the annuity issuer, the structured settlement obligor, and any other party that has continuing rights or obligations under such structured settlement.

. "Net advance amount" means the gross advance amount less the aggregate amount of the actual and estimated transfer expenses required to be disclosed under RCW 19.205.020(5).

. "Payee" means an individual who is receiving tax-free payments under a structured settlement and proposes to make a transfer of payment rights thereunder.

. "Periodic payments" means (a) recurring payments and (b) scheduled future lump sum payments.

. "Qualified assignment agreement" means an agreement providing for a qualified assignment within the meaning of section 130 of the United States internal revenue code (26 U.S.C. Sec. 130), as amended.

. "Responsible administrative authority" means, with respect to a structured settlement, any government authority vested by law with exclusive jurisdiction over the settled claim resolved by such structured settlement.

. "Settled claim" means the original tort claim or workers' compensation claim resolved by a structured settlement.

. "Structured settlement" means an arrangement for periodic payment of compensation for injuries or sickness as described in 26 U.S.C. Sec. 104(a)(1) or (2), as amended, or an arrangement for periodic payment of benefits under a special needs trust as described in 42 U.S.C. Sec. 1396p(d)(4), as amended.

. "Structured settlement agreement" means the agreement, judgment, stipulation, or release embodying the terms of a structured settlement.

. "Structured settlement obligor" means, with respect to any structured settlement, the party that has the continuing obligation to make periodic payments to the payee under a structured settlement agreement or a qualified assignment agreement.

. "Structured settlement payment rights" means rights to receive periodic payments under a structured settlement, whether from the structured settlement obligor or the annuity issuer, if:

.. The payee is domiciled in, or the domicile or principal place of business of the structured settlement obligor or the annuity issuer is located in, this state;

.. The structured settlement agreement was approved by a court or responsible administrative authority in this state; or

.. The structured settlement agreement is expressly governed by the laws of this state.

. "Terms of the structured settlement" means, with respect to any structured settlement, the terms of the structured settlement agreement, the annuity contract, any qualified assignment agreement and any order or other approval of any court or responsible administrative authority or other government authority that authorized or approved such structured settlement.

. "Transfer" means any sale, assignment, pledge, hypothecation or other alienation or encumbrance of structured settlement payment rights made by a payee for consideration. However, "transfer" does not mean the creation or perfection of a security interest in structured settlement payment rights under a blanket security agreement entered into with an insured depository institution, in the absence of any action to redirect the structured settlement payments to such insured depository institution, or an agent or successor in interest thereof, or otherwise to enforce such blanket security interest against the structured settlement payment rights.

. "Transfer agreement" means the agreement providing for a transfer of structured settlement payment rights.

. "Transfer expenses" means all expenses of a transfer that are required under the transfer agreement to be paid by the payee or deducted from the gross advance amount, including, without limitation, court filing fees, attorneys' fees, escrow fees, lien recordation fees, judgment and lien search fees, finders' fees, commissions, and other payments to a broker or other intermediary. "Transfer expenses" does not mean preexisting obligations of the payee payable for the payee's account from the proceeds of a transfer.

. "Transferee" means a party acquiring or proposing to acquire structured settlement payment rights through a transfer.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1347.SL.pdf?cite=2001%20c%20178%20§%202[2001 c 178 § 2]; ]

== 19.205.020 - Disclosure statement—Content.
Not less than three days prior to the date on which a payee signs a transfer agreement, the transferee shall provide to the payee a separate disclosure statement, in bold type no smaller than fourteen points, setting forth:

. The amounts and due dates of the structured settlement payments to be transferred;

. The aggregate amount of such payments;

. The discounted present value of the payments to be transferred, which shall be identified as the "calculation of current value of the transferred structured settlement payments under federal standards for valuing annuities," and the amount of the applicable federal rate used in calculating such discounted present value;

. The gross advance amount;

. An itemized listing of all applicable transfer expenses, other than attorneys' fees and related disbursements payable in connection with the transferee's application for approval of the transfer, and the transferee's best estimate of the amount of any such fees and disbursements;

. The net advance amount;

. The amount of any penalties or liquidated damages payable by the payee in the event of any breach of the transfer agreement by the payee; and

. A statement that the payee has the right to cancel the transfer agreement, without penalty or further obligation, not later than the third business day after the date the agreement is signed by the payee.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1347.SL.pdf?cite=2001%20c%20178%20§%203[2001 c 178 § 3]; ]

== 19.205.030 - Structured settlement payment rights—Transfer—Order—Express findings.
A direct or indirect transfer of structured settlement payment rights is not effective and a structured settlement obligor or annuity issuer is not required to make any payment directly or indirectly to any transferee of structured settlement payment rights unless the transfer has been approved in advance in a final court order or order of a responsible administrative authority based on express findings by such court or responsible administrative authority that:

. The transfer is in the best interest of the payee, taking into account the welfare and support of the payee's dependents;

. The payee has been advised in writing by the transferee to seek independent professional advice regarding the transfer and has either received such advice or knowingly waived such advice in writing; and

. The transfer does not contravene any applicable statute or the order of any court or other government authority.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1347.SL.pdf?cite=2001%20c%20178%20§%204[2001 c 178 § 4]; ]

== 19.205.040 - Posttransfer of rights—Liabilities—Requirements.
Following a transfer of structured settlement payment rights under this chapter:

. The structured settlement obligor and the annuity issuer shall, as to all parties except the transferee, be discharged and released from any and all liability for the transferred payments;

. The transferee shall be liable to the structured settlement obligor and the annuity issuer:

.. If the transfer contravenes the terms of the structured settlement, for any taxes incurred by such parties as a consequence of the transfer; and

.. For any other liabilities or costs, including reasonable costs and attorneys' fees, arising from compliance by such parties with the order of the court or responsible administrative authority or arising as a consequence of the transferee's failure to comply with this chapter;

. Neither the annuity issuer nor the structured settlement obligor may be required to divide any periodic payment between the payee and any transferee or assignee or between two, or more, transferees or assignees; and

. Any further transfer of structured settlement payment rights by the payee may be made only after compliance with all of the requirements of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1347.SL.pdf?cite=2001%20c%20178%20§%205[2001 c 178 § 5]; ]

== 19.205.050 - Application/approval of transfer—Notice—Content.
. An application under this chapter for approval of a transfer of structured settlement payment rights shall be made by the transferee and may be brought in the county in which the payee resides, in the county in which the structured settlement obligor or the annuity issuer maintains its principal place of business, or in any court or before any responsible administrative authority which approved the structured settlement agreement.

. Not less than twenty days prior to the scheduled hearing on any application for approval of a transfer of structured settlement payment rights under RCW 19.205.030, the transferee shall file with the court or responsible administrative authority and serve on all interested parties a notice of the proposed transfer and the application for its authorization, including with such notice:

.. A copy of the transferee's application;

.. A copy of the transfer agreement;

.. A copy of the disclosure statement required under RCW 19.205.020;

.. A listing of each of the payee's dependents, together with each dependent's age;

.. Notification that any interested party is entitled to support, oppose, or otherwise respond to the transferee's application, either in person or by counsel, by submitting written comments to the court or responsible administrative authority or by participating in the hearing; and

.. Notification of the time and place of the hearing and notification of the manner in which and the time by which written responses to the application must be filed, which may not be less than fifteen days after service of the transferee's notice, in order to be considered by the court or responsible administrative authority.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1347.SL.pdf?cite=2001%20c%20178%20§%206[2001 c 178 § 6]; ]

== 19.205.060 - Transfer agreements—Further provisions.
. The provisions of this chapter may not be waived by any payee.

. Any transfer agreement entered into on or after July 22, 2001, by a payee who resides in this state shall provide that disputes under such transfer agreement, including any claim that the payee has breached the agreement, shall be determined in and under the laws of this state. Such a transfer agreement may not authorize the transferee or any other party to confess judgment or consent to entry of judgment against the payee.

. Transfer of structured settlement payment rights do not extend to any payments that are life contingent unless, prior to the date on which the payee signs the transfer agreement, the transferee has established and has agreed to maintain procedures reasonably satisfactory to the annuity issuer and the structured settlement obligor for (a) periodically confirming the payee's survival, and (b) giving the annuity issuer and the structured settlement obligor prompt written notice in the event of the payee's death.

. No payee who proposes to make a transfer of structured settlement payment rights may incur any penalty, forfeit any application fee or other payment, or otherwise incur any liability to the proposed transferee or any assignee based on any failure of such a transfer to satisfy the conditions of this chapter.

. This chapter does not authorize any transfer of structured settlement payment rights in contravention of any law, nor does it imply that any transfer under a transfer agreement entered into prior to July 22, 2001, is valid or invalid.

. Compliance with the requirements set forth in RCW 19.205.020 and fulfillment of the conditions set forth in RCW 19.205.030 is the sole responsibility of the transferee in any transfer of structured settlement payment rights, and neither the structured settlement obligor nor the annuity issuer bear any responsibility for, or any liability arising from, noncompliance with the requirements or failure to fulfill the conditions.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1347.SL.pdf?cite=2001%20c%20178%20§%207[2001 c 178 § 7]; ]

== 19.205.900 - Short title.
This chapter may be known and cited as the structured settlement protection act.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1347.SL.pdf?cite=2001%20c%20178%20§%201[2001 c 178 § 1]; ]

== 19.205.901 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%2058[2009 c 521 § 58]; ]

