= 19.390 - Health care market participants.
:toc:

== 19.390.010 - Intent.
It is the intent of the legislature to ensure that competition beneficial to consumers in health care markets across Washington remains vigorous and robust. The legislature supports that intent through this chapter, which provides the attorney general with notice of all material health care transactions in this state so that the attorney general has the information necessary to determine whether an investigation under the consumer protection act is warranted for potential anticompetitive conduct and consumer harm. This chapter is intended to supplement the federal Hart-Scott-Rodino antitrust improvements act, Title 15 U.S.C. Sec. 18a, by requiring notice of transactions not reportable under Hart-Scott-Rodino reporting thresholds and by providing the attorney general with a copy of any filings made pursuant to the Hart-Scott-Rodino act.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1607-S.SL.pdf?cite=2019%20c%20267%20§%201[2019 c 267 § 1]; ]

== 19.390.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Acquisition" means an agreement, arrangement, or activity the consummation of which results in a person acquiring directly or indirectly the control of another person, and includes the acquisition of voting securities and noncorporate interests, such as assets, capital stock, membership interests, or equity interests.

. "Carrier" means the same as in RCW 48.43.005.

. "Contracting affiliation" means the formation of a relationship between two or more entities that permits the entities to negotiate jointly with carriers or third-party administrators over rates for professional medical services, or for one entity to negotiate on behalf of the other entity with carriers or third-party administrators over rates for professional medical services. "Contracting affiliation" does not include arrangements among entities under common ownership.

. "Health care services" means medical, surgical, chiropractic, hospital, optometric, podiatric, pharmaceutical, ambulance, mental health, substance use disorder, therapeutic, preventative, diagnostic, curative, rehabilitative, palliative, custodial, and any other services relating to the prevention, cure, or treatment of illness, injury, or disease.

. "Health care services revenue" means the total revenue received for health care services in the previous twelve months.

. "Health maintenance organization" means an organization receiving a certificate of registration pursuant to chapter 48.46 RCW which provides comprehensive health care services to enrolled participants of such organization on a group practice per capita prepayment basis or on a prepaid individual practice plan, except for an enrolled participant's responsibility for copayments and deductibles, either directly or through contractual or other arrangements with other institutions, entities, or persons, and which qualifies as a health maintenance organization pursuant to RCW 48.46.030 and 48.46.040.

. "Hospital" means a facility licensed under chapter 70.41 or 71.12 RCW.

. "Hospital system" means:

.. A parent corporation of one or more hospitals and any entity affiliated with such parent corporation through ownership or control; or

.. A hospital and any entity affiliated with such hospital through ownership.

. "Merger" means a consolidation of two or more organizations, including two or more organizations joining through a common parent organization or two or more organizations forming a new organization, but does not include a corporate reorganization.

. "Person" means, where applicable, natural persons, corporations, trusts, and partnerships.

. "Provider" means a natural person who practices a profession identified in RCW 18.130.040.

. "Provider organization" means a corporation, partnership, business trust, association, or organized group of persons, whether incorporated or not, which is in the business of health care delivery or management and that represents seven or more health care providers in contracting with carriers or third-party administrators for the payments of health care services. A "provider organization" includes physician organizations, physician-hospital organizations, independent practice associations, provider networks, and accountable care organizations.

. "Third-party administrator" means an entity that administers payments for health care services on behalf of a client in exchange for an administrative fee.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1607-S.SL.pdf?cite=2019%20c%20267%20§%202[2019 c 267 § 2]; ]

== 19.390.030 - Notice of material change.
. Not less than sixty days prior to the effective date of any transaction that results in a material change, the parties to the transaction shall submit written notice to the attorney general of such material change.

. For the purposes of this section, a material change includes a merger, acquisition, or contracting affiliation between two or more entities of the following types:

.. Hospitals;

.. Hospital systems; or

.. Provider organizations.

. A material change includes proposed changes identified in subsection (2) of this section between a Washington entity and an out-of-state entity where the out-of-state entity generates ten million dollars or more in health care services revenue from patients residing in Washington state, and the entities are of the types identified in subsection (2) of this section. Any party to a material change that is licensed or operating in Washington state shall submit a notice as required under this section.

. For purposes of subsection (2) of this section, a merger, acquisition, or contracting affiliation between two or more hospitals, hospital systems, or provider organizations only qualifies as a material change if the hospitals, hospital systems, or provider organizations did not previously have common ownership or a contracting affiliation.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1607-S.SL.pdf?cite=2019%20c%20267%20§%203[2019 c 267 § 3]; ]

== 19.390.040 - Notice requirements.
. The written notice provided by the parties, as required by RCW 19.390.030, must include:

.. The names of the parties and their current business addresses;

.. Identification of all locations where health care services are currently provided by each party;

.. A brief description of the nature and purpose of the proposed material change; and

.. The anticipated effective date of the proposed material change.

. Nothing in this section prohibits the parties to a material change from voluntarily providing additional information to the attorney general.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1607-S.SL.pdf?cite=2019%20c%20267%20§%204[2019 c 267 § 4]; ]

== 19.390.050 - Requests for additional information.
The attorney general shall make any requests for additional information from the parties under RCW 19.86.110 within thirty days of the date notice is received under RCW 19.390.030 and 19.390.040. Nothing in this section precludes the attorney general from conducting an investigation or enforcing state or federal antitrust laws at a later date.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1607-S.SL.pdf?cite=2019%20c%20267%20§%205[2019 c 267 § 5]; ]

== 19.390.060 - Premerger notification—Copy to attorney general—Hart-Scott-Rodino act.
Any provider or provider organization conducting business in this state that files a premerger notification with the federal trade commission or the United States department of justice, in compliance with the Hart-Scott-Rodino antitrust improvements act, Title 15 U.S.C. Sec. 18a, shall provide a copy of such filing to the attorney general. Providing a copy of the Hart-Scott-Rodino filing to the attorney general satisfies the notice requirement under RCW 19.390.040.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1607-S.SL.pdf?cite=2019%20c%20267%20§%206[2019 c 267 § 6]; ]

== 19.390.070 - Materials submitted to the attorney general.
Information submitted to the attorney general pursuant to this chapter shall be maintained and used by the attorney general in the same manner and under the same protections as provided in RCW 19.86.110. The information, including documentary material, answers to written interrogatories, or transcripts of oral testimony produced pursuant to a demand or copies, must not, unless otherwise ordered by a superior court for good cause shown, be produced for inspection or copying pursuant to chapter 42.56 RCW by the person who produced the material, answered written interrogatories or gave oral testimony. Nothing in this chapter limits the attorney general's authority under RCW 19.86.110 or 19.86.115. Nothing in this chapter expands the attorney general's authority under chapter 19.86 RCW, federal or state antitrust law, or any other law. Failure to comply with this chapter does not provide a private cause of action.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1607-S.SL.pdf?cite=2019%20c%20267%20§%207[2019 c 267 § 7]; ]

== 19.390.080 - Penalty for noncompliance.
Any person who fails to comply with any provision of this chapter is liable to the state for a civil penalty of not more than two hundred dollars per day for each day during which such person is in violation of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1607-S.SL.pdf?cite=2019%20c%20267%20§%208[2019 c 267 § 8]; ]

== 19.390.090 - Notice requirement—Effective date for transactions.
The notice requirement in RCW 19.390.030 applies to transactions with an anticipated effective date on or after January 1, 2020.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1607-S.SL.pdf?cite=2019%20c%20267%20§%209[2019 c 267 § 9]; ]

