= 19.355 - Locksmith services.
:toc:

== 19.355.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Local telephone directory" means a publication listing telephone numbers for various businesses in a certain geographic area and distributed free of charge to some or all telephone subscribers in that area.

. "Local telephone number" means a telephone number that can be dialed without incurring long distance charges from telephones located within the area covered by the local telephone directory in which the number is listed. The term does not include long distance numbers, toll-free numbers, or nine hundred exchange numbers listed in a local telephone directory.

. "Locksmith services" means:

.. Selling, installing, servicing, repairing, repinning, recombinating, and adjusting locks, safes, vaults, or safe deposit boxes;

.. Originating keys;

.. Operating, bypassing, or neutralizing locks, safes, vaults, or safe deposit boxes;

.. Creating, documenting, selling, installing, managing, and servicing master-key systems;

.. Unlocking, bypassing, or neutralizing locks for motor vehicles;

.. Originating keys for motor vehicles, which can include the programming, reprogramming, or bypassing of any security transponder, immobilizer system, or subsequent technology built by the manufacturer; and

.. Keying or recombinating motor vehicle locks.

. "Person" means an individual, partnership, limited liability partnership, corporation, or limited liability corporation.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5296-S.SL.pdf?cite=2015%20c%2028%20§%201[2015 c 28 § 1]; ]

== 19.355.020 - Prohibited practices—Requirements.
. No person whose primary business is to provide locksmith services and who represents himself or herself to the public as a locksmith may misrepresent his, her, or its geographic location by:

.. Listing a local telephone number in a local telephone directory or on an internet web site if:

... Calls to the telephone number are routinely forwarded or otherwise transferred to a business location that is outside the calling area covered by the local telephone directory or outside the local calling area for the local telephone number listed on an internet web site; and

... The listing fails to conspicuously disclose the locality and state in which the business is located; or

.. Listing a business name in a local telephone directory or on an internet web site if:

... The name misrepresents the business's geographic location; and

... The listing fails to disclose the locality and state in which the business is located.

. A person whose primary business is to provide locksmith services and who represents himself or herself to the public as a locksmith must conspicuously display on the business web site and all advertising:

.. The number of the business license issued to it by the state or a local government; or

.. The state unified business identifier account number.

. The requirements of subsections (1) and (2) of this section do not apply to businesses that provide locksmith services that are ancillary to their primary business, such as businesses that provide roadside or towing services.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5296-S.SL.pdf?cite=2015%20c%2028%20§%202[2015 c 28 § 2]; ]

== 19.355.030 - Application of consumer protection act.
The legislature finds that the practices covered by RCW 19.355.020(1) are matters vitally affecting the public interest for the purpose of applying chapter 19.86 RCW. A violation of this chapter is not reasonable in relation to the development and preservation of business and is an unfair or deceptive act in trade or commerce and an unfair method of competition for the purpose of applying chapter 19.86 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5296-S.SL.pdf?cite=2015%20c%2028%20§%203[2015 c 28 § 3]; ]

