= 19.315 - Consumer rebates.
:toc:

== 19.315.010 - Definitions.
As used in this chapter:

. "Person" has the same meaning as in RCW 19.86.010.

. "Rebate" means an offer to provide cash, credit, or credit towards future purchases, that is offered to consumers who acquire or purchase a specified product or service and that is conditioned upon the customer submitting a request for redemption after satisfying the terms and conditions of the offer. "Rebate" does not include: Any discount from the purchase price that is taken at the time of purchase; any discount, cash, credit, or credit towards a future purchase that is automatically provided to a consumer without the need to submit a request for redemption; or any refund that may be given to a consumer in accordance with a company's return, guarantee, adjustment, or warranty policies, or any company's frequent shopper customer reward program.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5978-S.SL.pdf?cite=2009%20c%20374%20§%201[2009 c 374 § 1]; ]

== 19.315.020 - Time for redemption—Transmittal of rebate—Application.
. Any person who offers a consumer rebate shall allow a minimum of fourteen days from the date the consumer purchases the product, or becomes eligible for the rebate upon satisfying the terms and conditions of the offer, for the submission of a request for redemption by the customer.

. Upon receipt of a request for redemption meeting the terms and conditions of the rebate offer, the person offering the rebate shall transmit the rebate funds to the consumer within ninety days.

. If a rebate is sent to a consumer as a check, the check must be mailed in a manner that identifies the piece of mail as the expected rebate check.

. This section applies only to the person offering the rebate, which is the person who provides the cash, credit, or credit towards future purchases to the consumer. This section does not apply to a person who processes a rebate or who provides consumers with instructions or materials related to a rebate.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5978-S.SL.pdf?cite=2009%20c%20374%20§%202[2009 c 374 § 2]; ]

== 19.315.030 - Application of the consumer protection act.
The legislature finds that the practices covered by this chapter are matters vitally affecting the public interest for the purpose of applying the consumer protection act, chapter 19.86 RCW. A violation of this chapter is not reasonable in relation to the development and preservation of business and is an unfair or deceptive act in trade or commerce and an unfair method of competition for the purpose of applying the consumer protection act, chapter 19.86 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5978-S.SL.pdf?cite=2009%20c%20374%20§%203[2009 c 374 § 3]; ]

