= 19.320 - Human trafficking.
:toc:

== 19.320.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Any person" means adults and children of any nationality.

. "Domestic employers of foreign workers" or "domestic employer" means a person or persons residing in the state of Washington who recruit or employ a foreign worker to perform work in Washington state.

. "Forced labor" means all work or service which is exacted from any person under the menace of any penalty and to which the person has not offered himself or herself voluntarily.

. "Foreign worker" or "worker" means a person who is not a citizen of the United States, who comes to Washington state based on an offer of employment, and who holds a nonimmigrant visa for temporary visitors.

. "Human trafficking" or "trafficking" means an act conducted for the purpose of exploitation, including forced labor, by particular means, for example threat of use of force or other forms of coercion, abduction, fraud or deception, abuse of power, or abuse of position of vulnerability.

. "International labor recruitment agency" means a corporation, partnership, business, or other legal entity, whether or not organized under the laws of the United States or any state, that does business in the United States and offers Washington state entities engaged in the employment or recruitment of foreign workers, employment referral services involving citizens of a foreign country or countries by acting as an intermediary between these foreign workers and Washington employers.

. "Menace of any penalty" means all forms of criminal sanctions and other forms of coercion, including threats, violence, retention of identity documents, confinement, nonpayment or illegal deduction of wages, or debt bondage.

. "Work or service" means all types of work, employment, or occupation, whether legal or not.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5342.SL.pdf?cite=2016%20c%204%20§%201[2016 c 4 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6332-S.SL.pdf?cite=2010%20c%20142%20§%201[2010 c 142 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5850-S2.SL.pdf?cite=2009%20c%20492%20§%201[2009 c 492 § 1]; ]

== 19.320.020 - Disclosure statement.
. Except as provided in subsection (4) of this section, domestic employers of foreign workers and international labor recruitment agencies must provide a disclosure statement as described in this section to foreign workers who have been referred to or hired by a Washington employer on or after June 10, 2010.

. The disclosure statement must:

.. Be provided in English or, if the worker is not fluent or literate in English, another language that is understood by the worker;

.. State that the worker may be considered an employee under the laws of the state of Washington and is subject to state worker health and safety laws and may be eligible for workers' compensation insurance and unemployment insurance;

.. State that the worker may be subject to both state and federal laws governing overtime and work hours, including the minimum wage act under chapter 49.46 RCW;

.. Include an itemized listing of any deductions the employer intends to make from the worker's pay for food and housing;

.. Include an itemized listing of the international labor recruitment agency's fees;

.. State that the worker has the right to control over his or her travel and labor documents, including his or her visa, at all times and that the employer may not require the employee to surrender those documents to the employer or to the international labor recruitment agency while the employee is working in the United States, except as otherwise required by law or regulation or for use as supporting documentation in visa applications;

.. Include a list of services or a hotline a worker may contact if he or she thinks that he or she may be a victim of trafficking.

. The department of labor and industries may create a model disclosure form and post the model form on its web site so that domestic employers of foreign workers and international labor recruitment agencies may download the form, or mail the form upon request. The disclosure statement must be given to the worker no later than the date that the worker arrives at the place of employment in Washington.

. If a foreign worker has been provided an informational pamphlet developed under the William Wilberforce trafficking victims protection reauthorization act of 2008, the domestic employer or international labor recruitment agency is not required to provide the disclosure statement under this section. For the purposes of this subsection a worker is presumed to have been provided an informational pamphlet so long as the William Wilberforce trafficking victims protection reauthorization act is in effect and he or she holds an A-3, G-5, NATO-7, H, J, or B-1 personal or domestic servant visa.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6332-S.SL.pdf?cite=2010%20c%20142%20§%202[2010 c 142 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5850-S2.SL.pdf?cite=2009%20c%20492%20§%202[2009 c 492 § 2]; ]

== 19.320.030 - Personal jurisdiction.
For purposes of establishing personal jurisdiction under this chapter, an international labor recruitment agency or a domestic employer of a foreign worker is deemed to be doing business in Washington and is subject to the jurisdiction of the courts of Washington state if the agency or employer contracts for employment services with a Washington resident or is considered to be doing business under any other provision or rule of law.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5850-S2.SL.pdf?cite=2009%20c%20492%20§%203[2009 c 492 § 3]; ]

== 19.320.040 - Liability.
Any domestic employer or international labor recruitment agency which fails to complete the requirements of this chapter with respect to any foreign worker is liable to that foreign worker in a civil action by the foreign worker. The court shall award to a foreign worker who prevails in an action under this section an amount between two hundred dollars and five hundred dollars, or actual damages, whichever is greater. The court may also award other equitable relief. A foreign worker who prevails in an action under this section must be awarded court costs and attorneys' fees.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6332-S.SL.pdf?cite=2010%20c%20142%20§%203[2010 c 142 § 3]; ]

== 19.320.050 - Assistance information.
The department of labor and industries shall integrate information on assisting victims of human trafficking in posters and brochures, as deemed appropriate by the department. The information shall include the toll-free telephone number of the national human trafficking resource center and the Washington state office of crime victims advocacy.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6332-S.SL.pdf?cite=2010%20c%20142%20§%204[2010 c 142 § 4]; ]

