= 19.405 - Washington clean energy transformation act.
:toc:

== 19.405.010 - Findings—Intent—2019 c 288.
. The legislature finds that Washington must address the impacts of climate change by leading the transition to a clean energy economy. One way in which Washington must lead this transition is by transforming its energy supply, modernizing its electricity system, and ensuring that the benefits of this transition are broadly shared throughout the state.

. With our wealth of carbon-free hydropower, Washington has some of the cleanest electricity in the United States. But electricity remains a large source of emissions in our state. We are at a critical juncture for transforming our electricity system. It is the policy of the state to eliminate coal-fired electricity, transition the state's electricity supply to one hundred percent carbon-neutral by 2030, and one hundred percent carbon-free by 2045. In implementing this chapter, the state must prioritize the maximization of family wage job creation, seek to ensure that all customers are benefiting from the transition to a clean energy economy, and provide safeguards to ensure that the achievement of this policy does not impair the reliability of the electricity system or impose unreasonable costs on utility customers.

. The transition to one hundred percent clean energy is underway, but must happen faster than our current policies can deliver. Absent significant and swift reductions in greenhouse gas emissions, climate change poses immediate significant threats to our economy, health, safety, and national security. The prices of clean energy technologies continue to fall, and are, in many cases, competitive or even cheaper than conventional energy sources.

. The legislature finds that Washington can accomplish the goals of chapter 288, Laws of 2019 while: Promoting energy independence; creating high quality jobs in the clean energy sector; maximizing the value of hydropower, our principal renewable resource; continuing to encourage and provide incentives for clean alternative energy sources, including providing electricity for the transportation sector; maintaining safe and reliable electricity to all customers at stable and affordable rates; and protecting clean air and water in the Pacific Northwest. Clean energy creates more jobs per unit of energy produced than fossil fuel sources, so this transition will contribute to job growth in Washington while addressing our climate crisis head on. Our abundance of renewable energy and our strong clean technology sector make Washington well positioned to be at the forefront of the transition to one hundred percent clean electricity.

. The legislature declares that utilities in the state have an important role to play in this transition, and must be fully empowered, through regulatory tools and incentives, to achieve the goals of this policy. In combination with new technology and emerging opportunities for customers, this policy will spur transformational change in the utility industry. Given these changes, the legislature recognizes and finds that the utilities and transportation commission's statutory grant of authority for rate making includes consideration and implementation of performance and incentive-based regulation, multiyear rate plans, and other flexible regulatory mechanisms where appropriate to achieve fair, just, reasonable, and sufficient rates and its public interest objectives.

. The legislature recognizes and finds that the public interest includes, but is not limited to: The equitable distribution of energy benefits and reduction of burdens to vulnerable populations and highly impacted communities; long-term and short-term public health, economic, and environmental benefits and the reduction of costs and risks; and energy security and resiliency. It is the intent of the legislature that in achieving this policy for Washington, there should not be an increase in environmental health impacts to highly impacted communities.

. It is the intent of the legislature to provide flexible tools to address the variability of hydropower for compliance under chapter 288, Laws of 2019.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5116-S2.SL.pdf?cite=2019%20c%20288%20§%201[2019 c 288 § 1]; ]

== 19.405.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Allocation of electricity" means, for the purposes of setting electricity rates, the costs and benefits associated with the resources used to provide electricity to an electric utility's retail electricity consumers that are located in this state.

. "Alternative compliance payment" means the payment established in RCW 19.405.090(2).

. "Attorney general" means the Washington state office of the attorney general.

. "Auditor" means: (a) The Washington state auditor's office or its designee for utilities under its jurisdiction under this chapter that are consumer-owned utilities; or (b) an independent auditor selected by a utility that is not under the jurisdiction of the state auditor and is not an investor-owned utility.

. [Empty]
.. "Biomass energy" includes: (i) Organic by-products of pulping and the wood manufacturing process; (ii) animal manure; (iii) solid organic fuels from wood; (iv) forest or field residues; (v) untreated wooden demolition or construction debris; (vi) food waste and food processing residuals; (vii) liquors derived from algae; (viii) dedicated energy crops; and (ix) yard waste.

.. "Biomass energy" does not include: (i) Wood pieces that have been treated with chemical preservatives such as creosote, pentachlorophenol, or copper-chrome-arsenic; (ii) wood from old growth forests; or (iii) municipal solid waste.

. "Carbon dioxide equivalent" has the same meaning as defined in RCW 70A.45.010.

. [Empty]
.. "Coal-fired resource" means a facility that uses coal-fired generating units, or that uses units fired in whole or in part by coal as feedstock, to generate electricity.

.. [Empty]
... "Coal-fired resource" does not include an electric generating facility that is included as part of a limited duration wholesale power purchase, not to exceed one month, made by an electric utility for delivery to retail electric customers that are located in this state for which the source of the power is not known at the time of entry into the transaction to procure the electricity.

... "Coal-fired resource" does not include an electric generating facility that is subject to an obligation to meet the standards contained in RCW 80.80.040(3)(c).

. "Commission" means the Washington utilities and transportation commission.

. "Conservation and efficiency resources" means any reduction in electric power consumption that results from increases in the efficiency of energy use, production, transmission, or distribution.

. "Consumer-owned utility" means a municipal electric utility formed under Title 35 RCW, a public utility district formed under Title 54 RCW, an irrigation district formed under chapter 87.03 RCW, a cooperative formed under chapter 23.86 RCW, or a mutual corporation or association formed under chapter 24.06 RCW, that is engaged in the business of distributing electricity to more than one retail electric customer in the state.

. "Demand response" means changes in electric usage by demand-side resources from their normal consumption patterns in response to changes in the price of electricity, or to incentive payments designed to induce lower electricity use, at times of high wholesale market prices or when system reliability is jeopardized. "Demand response" may include measures to increase or decrease electricity production on the customer's side of the meter in response to incentive payments.

. "Department" means the department of commerce.

. "Distributed energy resource" means a nonemitting electric generation or renewable resource or program that reduces electric demand, manages the level or timing of electricity consumption, or provides storage, electric energy, capacity, or ancillary services to an electric utility and that is located on the distribution system, any subsystem of the distribution system, or behind the customer meter, including conservation and energy efficiency.

. "Electric utility" or "utility" means a consumer-owned utility or an investor-owned utility.

. "Energy assistance" means a program undertaken by a utility to reduce the household energy burden of its customers.

.. Energy assistance includes, but is not limited to, weatherization, conservation and efficiency services, and monetary assistance, such as a grant program or discounts for lower income households, intended to lower a household's energy burden.

.. Energy assistance may include direct customer ownership in distributed energy resources or other strategies if such strategies achieve a reduction in energy burden for the customer above other available conservation and demand-side measures.

. "Energy assistance need" means the amount of assistance necessary to achieve a level of household energy burden established by the department or commission.

. "Energy burden" means the share of annual household income used to pay annual home energy bills.

. [Empty]
.. "Energy transformation project" means a project or program that: Provides energy-related goods or services, other than the generation of electricity; results in a reduction of fossil fuel consumption and in a reduction of the emission of greenhouse gases attributable to that consumption; and provides benefits to the customers of an electric utility.

.. "Energy transformation project" may include but is not limited to:

... Home weatherization or other energy efficiency measures, including market transformation for energy efficiency products, in excess of: The target established under RCW 19.285.040(1), if applicable; other state obligations; or other obligations in effect on May 7, 2019;

... Support for electrification of the transportation sector including, but not limited to:

(A) Equipment on an electric utility's transmission and distribution system to accommodate electric vehicle connections, as well as smart grid systems that enable electronic interaction between the electric utility and charging systems, and facilitate the utilization of vehicle batteries for system needs;

(B) Incentives for the sale or purchase of electric vehicles, both battery and fuel cell powered, as authorized under state or federal law;

(C) Incentives for the installation of charging equipment for electric vehicles;

(D) Incentives for the electrification of vehicle fleets utilizing a battery or fuel cell for electric supply;

(E) Incentives to install and operate equipment to produce or distribute renewable hydrogen; and

(F) Incentives for renewable hydrogen fueling stations;

... Investment in distributed energy resources and grid modernization to facilitate distributed energy resources and improved grid resilience;

... Investments in equipment for renewable natural gas processing, conditioning, and production, or equipment or infrastructure used solely for the purpose of delivering renewable natural gas for consumption or distribution;

.. Contributions to self-directed investments in the following measures to serve the sites of large industrial gas and electrical customers: (A) Conservation; (B) new renewable resources; (C) behind-the-meter technology that facilitates demand response cooperation to reduce peak loads; (D) infrastructure to support electrification of transportation needs, including battery and fuel cell electrification; or (E) renewable natural gas processing, conditioning, or production; and

.. Projects and programs that achieve energy efficiency and emission reductions in the agricultural sector, including bioenergy and renewable natural gas projects.

. "Fossil fuel" means natural gas, petroleum, coal, or any form of solid, liquid, or gaseous fuel derived from such a material.

. "Governing body" means: The council of a city or town; the commissioners of an irrigation district, municipal electric utility, or public utility district; or the board of directors of an electric cooperative or mutual association that has the authority to set and approve rates.

. "Greenhouse gas" includes carbon dioxide, methane, nitrous oxide, hydrofluorocarbons, perfluorocarbons, sulfur hexafluoride, and any other gas or gases designated by the department of ecology by rule under RCW 70A.45.010.

. "Greenhouse gas content calculation" means a calculation expressed in carbon dioxide equivalent and made by the department of ecology, in consultation with the department, for the purposes of determining the emissions from the complete combustion or oxidation of fossil fuels and the greenhouse gas emissions in electricity for use in calculating the greenhouse gas emissions content in electricity.

. "Highly impacted community" means a community designated by the department of health based on cumulative impact analyses in RCW 19.405.140 or a community located in census tracts that are fully or partially on "Indian country" as defined in 18 U.S.C. Sec. 1151.

. "Investor-owned utility" means a company owned by investors that meets the definition of "corporation" in RCW 80.04.010 and is engaged in distributing electricity to more than one retail electric customer in the state.

. "Low-income" means household incomes as defined by the department or commission, provided that the definition may not exceed the higher of eighty percent of area median household income or two hundred percent of the federal poverty level, adjusted for household size.

. [Empty]
.. "Market customer" means a nonresidential retail electric customer of an electric utility that: (i) Purchases electricity from an entity or entities other than the utility with which it is directly interconnected; or (ii) generates electricity to meet one hundred percent of its own needs.

.. An "affected market customer" is a customer of an investor-owned utility who becomes a market customer after May 7, 2019.

. [Empty]
.. "Natural gas" means naturally occurring mixtures of hydrocarbon gases and vapors consisting principally of methane, whether in gaseous or liquid form, including methane clathrate.

.. "Natural gas" does not include renewable natural gas or the portion of renewable natural gas when blended into other fuels.

. [Empty]
.. "Nonemitting electric generation" means electricity from a generating facility or a resource that provides electric energy, capacity, or ancillary services to an electric utility and that does not emit greenhouse gases as a by-product of energy generation.

.. "Nonemitting electric generation" does not include renewable resources.

. [Empty]
.. "Nonpower attributes" means all environmentally related characteristics, exclusive of energy, capacity reliability, and other electrical power service attributes, that are associated with the generation of electricity, including but not limited to the facility's fuel type, geographic location, vintage, qualification as a renewable resource, and avoided emissions of pollutants to the air, soil, or water, and avoided emissions of carbon dioxide and other greenhouse gases.

.. "Nonpower attributes" does not include any aspects, claims, characteristics, and benefits associated with the on-site capture and destruction of methane or other greenhouse gases at a facility through a digester system, landfill gas collection system, or other mechanism, which may be separately marketable as greenhouse gas emission reduction credits, offsets, or similar tradable commodities. However, these separate avoided emissions may not result in or otherwise have the effect of attributing greenhouse gas emissions to the electricity.

. "Qualified transmission line" means an overhead transmission line that is: (a) Designed to carry a voltage in excess of one hundred thousand volts; (b) owned in whole or in part by an investor-owned utility; and (c) primarily or exclusively used by such an investor-owned utility as of May 7, 2019, to transmit electricity generated by a coal-fired resource.

. "Renewable energy credit" means a tradable certificate of proof of one megawatt-hour of a renewable resource. The certificate includes all of the nonpower attributes associated with that one megawatt-hour of electricity and the certificate is verified by a renewable energy credit tracking system selected by the department.

. "Renewable hydrogen" means hydrogen produced using renewable resources both as the source for the hydrogen and the source for the energy input into the production process.

. "Renewable natural gas" means a gas consisting largely of methane and other hydrocarbons derived from the decomposition of organic material in landfills, wastewater treatment facilities, and anaerobic digesters.

. "Renewable resource" means: (a) Water; (b) wind; (c) solar energy; (d) geothermal energy; (e) renewable natural gas; (f) renewable hydrogen; (g) wave, ocean, or tidal power; (h) biodiesel fuel that is not derived from crops raised on land cleared from old growth or first growth forests; or (i) biomass energy.

. [Empty]
.. "Retail electric customer" means a person or entity that purchases electricity from any electric utility for ultimate consumption and not for resale.

.. "Retail electric customer" does not include, in the case of any electric utility, any person or entity that purchases electricity exclusively from carbon-free and eligible renewable resources, as defined in RCW 19.285.030 as of January 1, 2019, pursuant to a special contract with an investor-owned utility approved by an order of the commission prior to May 7, 2019.

. "Retail electric load" means the amount of megawatt-hours of electricity delivered in a given calendar year by an electric utility to its Washington retail electric customers. "Retail electric load" does not include:

.. Megawatt-hours delivered from qualifying facilities under the federal public utility regulatory policies act of 1978, P.L. 95-617, in operation prior to May 7, 2019, provided that no entity other than the electric utility can make a claim on delivery of the megawatt-hours from those resources; or

.. Megawatt-hours delivered to an electric utility's system from a renewable resource through a voluntary renewable energy purchase by a retail electric customer of the utility in which the renewable energy credits associated with the megawatt-hours delivered are retired on behalf of the retail electric customer.

. "Thermal renewable energy credit" means, with respect to a facility that generates electricity using biomass energy that also generates thermal energy for a secondary purpose, a renewable energy credit that is equivalent to three million four hundred twelve thousand British thermal units of energy used for such secondary purpose.

. "Unbundled renewable energy credit" means a renewable energy credit that is sold, delivered, or purchased separately from electricity. All thermal renewable energy credits are considered unbundled renewable energy credits.

. "Unspecified electricity" means an electricity source for which the fuel attribute is unknown or has been separated from the energy delivered to retail electric customers.

. "Vulnerable populations" means communities that experience a disproportionate cumulative risk from environmental burdens due to:

.. Adverse socioeconomic factors, including unemployment, high housing and transportation costs relative to income, access to food and health care, and linguistic isolation; and

.. Sensitivity factors, such as low birth weight and higher rates of hospitalization.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201004[2020 c 20 § 1004]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5116-S2.SL.pdf?cite=2019%20c%20288%20§%202[2019 c 288 § 2]; ]

== 19.405.030 - Coal-fired resources—Depreciation schedule—Penalties.
. [Empty]
.. On or before December 31, 2025, each electric utility must eliminate coal-fired resources from its allocation of electricity. This does not include costs associated with decommissioning and remediation of these facilities.

.. The commission shall allow in electric rates all decommissioning and remediation costs prudently incurred by an investor-owned utility for a coal-fired resource.

. The commission must accelerate depreciation schedules for any coal-fired resource to a date no later than December 31, 2025. The commission may accelerate the depreciation schedule for any qualified transmission line owned by an investor-owned utility when the commission finds the qualified transmission line is no longer used and useful and there is no reasonable likelihood that the qualified transmission line will be utilized in the future. The adjusted depreciation schedule must require such a qualified transmission line to be fully depreciated on or before December 31, 2025.

. The commission must allow in rates, directly or indirectly, amounts on an investor-owned utility's books of account that the commission finds represent prudently incurred undepreciated investment in a fossil fuel generating resource that has been retired from service when:

.. The retirement is due to ordinary wear and tear, casualties, acts of God, acts of governmental authority, inability to procure or use fuel, termination or expiration of any ownership, or a operation agreement affecting such a fossil fuel generating resource; or

.. The commission finds that the retirement is in the public interest.

. An electric utility that fails to comply with the requirements of subsection (1) of this section must pay the administrative penalty established under RCW 19.405.090(1), except as otherwise provided in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5116-S2.SL.pdf?cite=2019%20c%20288%20§%203[2019 c 288 § 3]; ]

== 19.405.040 - Greenhouse gas neutrality—Responsibilities for electric utilities—Energy transformation project criteria—Penalties.
. It is the policy of the state that all retail sales of electricity to Washington retail electric customers be greenhouse gas neutral by January 1, 2030.

.. For the four-year compliance period beginning January 1, 2030, and for each multiyear compliance period thereafter through December 31, 2044, an electric utility must demonstrate its compliance with this standard using a combination of nonemitting electric generation and electricity from renewable resources, or alternative compliance options, as provided in this section. To achieve compliance with this standard, an electric utility must: (i) Pursue all cost-effective, reliable, and feasible conservation and efficiency resources to reduce or manage retail electric load, using the methodology established in RCW 19.285.040, if applicable; and (ii) use electricity from renewable resources and nonemitting electric generation in an amount equal to one hundred percent of the utility's retail electric loads over each multiyear compliance period. An electric utility must achieve compliance with this standard for the following compliance periods: January 1, 2030, through December 31, 2033; January 1, 2034, through December 31, 2037; January 1, 2038, through December 31, 2041; and January 1, 2042, through December 31, 2044.

.. Through December 31, 2044, an electric utility may satisfy up to twenty percent of its compliance obligation under (a) of this subsection with an alternative compliance option consistent with this section. An alternative compliance option may include any combination of the following:

... Making an alternative compliance payment under RCW 19.405.090(2);

... Using unbundled renewable energy credits, provided that there is no double counting of any nonpower attributes associated with renewable energy credits within Washington or programs in other jurisdictions, as follows:

(A) Unbundled renewable energy credits produced from eligible renewable resources, as defined under RCW 19.285.030, which may be used by the electric utility for compliance with RCW 19.285.040 and this section as provided under RCW 19.285.040(2)(e); and

(B) Unbundled renewable energy credits, other than those included in (b)(ii)(A) of this subsection, that represent electricity generated within the compliance period;

... Investing in energy transformation projects, including additional conservation and efficiency resources beyond what is otherwise required under this section, provided the projects meet the requirements of subsection (2) of this section and are not credited as resources used to meet the standard under (a) of this subsection; or

... Using electricity from an energy recovery facility using municipal solid waste as the principal fuel source, where the facility was constructed prior to 1992, and the facility is operated in compliance with federal laws and regulations and meets state air quality standards. An electric utility may only use electricity from such an energy recovery facility if the department and the department of ecology determine that electricity generation at the facility provides a net reduction in greenhouse gas emissions compared to any other available waste management best practice. The determination must be based on a life-cycle analysis comparing the energy recovery facility to other technologies available in the jurisdiction in which the facility is located for the waste management best practices of waste reduction, recycling, composting, and minimizing the use of a landfill.

.. Electricity from renewable resources used to meet the standard under (a) of this subsection must be verified by the retirement of renewable energy credits. Renewable energy credits must be tracked and retired in the tracking system selected by the department.

.. Hydroelectric generation used by an electric utility in meeting the standard under (a) of this subsection may not include new diversions, new impoundments, new bypass reaches, or expansion of existing reservoirs constructed after May 7, 2019, unless the diversions, bypass reaches, or reservoir expansions are necessary for the operation of a pumped storage facility that: (i) Does not conflict with existing state or federal fish recovery plans; and (ii) complies with all local, state, and federal laws and regulations.

.. Nothing in (d) of this subsection precludes an electric utility that owns and operates hydroelectric generating facilities, or the owner of a hydroelectric generating facility whose energy output is marketed by the Bonneville power administration, from making efficiency or other improvements to its hydroelectric generating facilities existing as of May 7, 2019, or from installing hydroelectric generation in pipes, culverts, irrigation canals, and other man-made waterways, as long as those changes do not create conflicts with existing state or federal fish recovery plans and comply with all local, state, and federal laws and regulations.

.. Nonemitting electric generation used to meet the standard under (a) of this subsection must be generated during the compliance period and must be verified by documentation that the electric utility owns the nonpower attributes of the electricity generated by the nonemitting electric generation resource.

.. Nothing in this section prohibits an electric utility from purchasing or exchanging power from the Bonneville power administration.

. Investments in energy transformation projects used to satisfy an alternative compliance option provided under subsection (1)(b) of this section must use criteria developed by the department of ecology, in consultation with the department and the commission. For the purpose of crediting an energy transformation project toward the standard in subsection (1)(a) of this section, the department of ecology must establish a conversion factor of emissions reductions resulting from energy transformation projects to megawatt-hours of electricity from nonemitting electric generation that is consistent with the emission factors for unspecified electricity, or for energy transformation projects in the transportation sector, consistent with default emissions or conversion factors established by other jurisdictions for clean alternative fuels. Emissions reductions from energy transformation projects must be:

.. Real, specific, identifiable, and quantifiable;

.. Permanent: The department of ecology must look to other jurisdictions in setting this standard and make a reasonable determination on length of time;

.. Enforceable by the state of Washington;

.. Verifiable;

.. Not required by another statute, rule, or other legal requirement; and

.. Not reasonably assumed to occur absent investment, or if an investment has already been made, not reasonably assumed to occur absent additional funding in the near future.

. Energy transformation projects must be associated with the consumption of energy in Washington and must not create a new use of fossil fuels that results in a net increase of fossil fuel usage.

. The compliance eligibility of energy transformation projects may be scaled or prorated by an approved protocol in order to distinguish effects related to reductions in electricity usage from reductions in fossil fuel usage.

. Any compliance obligation fulfilled through an investment in an energy transformation project is eligible for use only: (a) By the electric utility that makes the investment; (b) if the investment is made by the Bonneville power administration, by electric utilities that are preference customers of the Bonneville power administration; or (c) if the investment is made by a joint operating agency organized under chapter 43.52 RCW, by a member of the joint operating agency. An electric utility making an investment in partnership with another electric utility or entity may claim credit proportional to its share invested in the total project cost.

. [Empty]
.. In meeting the standard under subsection (1) of this section, an electric utility must, consistent with the requirements of RCW 19.285.040, if applicable, pursue all cost-effective, reliable, and feasible conservation and efficiency resources, and demand response. In making new investments, an electric utility must, to the maximum extent feasible:

... Achieve targets at the lowest reasonable cost, considering risk;

... Consider acquisition of existing renewable resources; and

... In the acquisition of new resources constructed after May 7, 2019, rely on renewable resources and energy storage, insofar as doing so is consistent with (a)(i) of this subsection.

.. Electric utilities subject to RCW 19.285.040 must demonstrate pursuit of all conservation and efficiency resources through compliance with the requirements in RCW 19.285.040.

. An electric utility that fails to meet the requirements of this section must pay the administrative penalty established under RCW 19.405.090(1), except as otherwise provided in this chapter.

. In complying with this section, an electric utility must, consistent with the requirements of RCW 19.280.030 and 19.405.140, ensure that all customers are benefiting from the transition to clean energy: Through the equitable distribution of energy and nonenergy benefits and reduction of burdens to vulnerable populations and highly impacted communities; long-term and short-term public health and environmental benefits and reduction of costs and risks; and energy security and resiliency.

. Affected market customers must comply with the standard established under subsection (1) of this section.

. A market customer that purchases electricity exclusively from carbon-free resources and eligible renewable resources, as defined in RCW 19.285.030 as of January 1, 2019, pursuant to a special contract with an investor-owned utility approved, prior to May 7, 2019, by order of the commission is subject to the requirements of such an order and not to the standard established in this section. For purposes of interpreting any such special contract, chapter 19.285 RCW, as in effect on January 1, 2019, is not, either directly or indirectly, amended or supplemented.

. To reduce costs for utility customers or avoid exceeding the cost impact limit in RCW 19.405.060(3)(a), a multistate electric utility with fewer than two hundred fifty thousand customers in Washington may apply the total amount of megawatt-hours of coal-fired resources eliminated from the utility's allocation of electricity before December 31, 2025, as an equivalent amount of megawatt-hours of nonemitting electric generation or electricity from renewable resources required to comply with subsection (1)(a) of this section. The utility must demonstrate that for every megawatt-hour of early action compliance credit there is a real, permanent reduction in greenhouse gas emissions in the western interconnection directly associated with that credit. A multistate electric utility must request to use early action compliance credit in its clean energy implementation plan that is submitted under RCW 19.405.060. The multistate electric utility must specify in its clean energy implementation plan the compliance years to which the early action compliance credit will apply, but in no event may the multistate electric utility use the early action compliance credits beyond 2035. The commission must establish conditions for use of early action compliance credits, including a determination of whether action constitutes early action, before the multistate electric utility's use of early action compliance credits in a clean energy implementation plan.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5116-S2.SL.pdf?cite=2019%20c%20288%20§%204[2019 c 288 § 4]; ]

== 19.405.050 - Clean energy implementation—Hydroelectric facilities—Special contracts.
. It is the policy of the state that nonemitting electric generation and electricity from renewable resources supply one hundred percent of all sales of electricity to Washington retail electric customers by January 1, 2045. By January 1, 2045, and each year thereafter, each electric utility must demonstrate its compliance with this standard using a combination of nonemitting electric generation and electricity from renewable resources.

. Each electric utility must incorporate subsection (1) of this section into all relevant planning and resource acquisition practices including, but not limited to: Resource planning under chapter 19.280 RCW; the construction or acquisition of property, including electric generating facilities; and the provision of electricity service to retail electric customers.

. In planning to meet projected demand consistent with the requirements of subsection (2) of this section and RCW 19.285.040, if applicable, an electric utility must pursue all cost-effective, reliable, and feasible conservation and efficiency resources, and demand response. In making new investments, an electric utility must, to the maximum extent feasible:

.. Achieve targets at the lowest reasonable cost, considering risk;

.. Consider acquisition of existing renewable resources; and

.. In the acquisition of new resources constructed after May 7, 2019, rely on renewable resources and energy storage, insofar as doing so is consistent with (a) of this subsection.

. The commission, department, energy facility site evaluation council, department of ecology, and all other state agencies must incorporate this section into all relevant planning and utilize all programs authorized by statute to achieve subsection (1) of this section.

. [Empty]
.. Hydroelectric generation used by an electric utility to satisfy the requirements of this section may not include new diversions, new impoundments, new bypass reaches, or expansion of existing reservoirs constructed after May 7, 2019, unless the diversions, bypass reaches, or reservoir expansions are necessary for the operation of a pumped storage facility that: (i) Does not conflict with existing state or federal fish recovery plans; and (ii) complies with all local, state, and federal laws and regulations.

.. Nothing in (a) of this subsection precludes an electric utility that owns and operates hydroelectric generating facilities, or the owner of a hydroelectric generating facility whose energy output is marketed by the Bonneville power administration, from making efficiency or other improvements to its hydroelectric generating facilities existing as of May 7, 2019, or from installing hydroelectric generation in pipes, culverts, irrigation canals, and other man-made waterways as long as those changes do not create conflicts with existing state or federal fish recovery plans and comply with all local, state, and federal laws and regulations.

. Nothing in this section prohibits an electric utility from purchasing or exchanging power from the Bonneville power administration.

. Affected market customers must comply with the obligations of this section.

. Any market customer that purchases electricity exclusively from carbon-free resources and eligible renewable resources, as defined in RCW 19.285.030 as of January 1, 2019, pursuant to a special contract with an investor-owned utility approved, prior to May 7, 2019, by order of the commission is subject to the requirements of such an order and not to the standards established in this section. For the purposes of interpreting such a special contract, chapter 19.285 RCW, as in effect on January 1, 2019, is not, either directly or indirectly, amended or supplemented.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5116-S2.SL.pdf?cite=2019%20c%20288%20§%205[2019 c 288 § 5]; ]

== 19.405.060 - Clean energy implementation plan—Compliance criteria—Incremental cost of compliance.
. [Empty]
.. By January 1, 2022, and every four years thereafter, each investor-owned utility must develop and submit to the commission:

... A four-year clean energy implementation plan for the standards established under RCW 19.405.040(1) and 19.405.050(1) that proposes specific targets for energy efficiency, demand response, and renewable energy; and

... Proposed interim targets for meeting the standard under RCW 19.405.040(1) during the years prior to 2030 and between 2030 and 2045.

.. An investor-owned utility's clean energy implementation plan must:

... Be informed by the investor-owned utility's clean energy action plan developed under RCW 19.280.030;

... Be consistent with subsection (3) of this section; and

... Identify specific actions to be taken by the investor-owned utility over the next four years, consistent with the utility's long-range integrated resource plan and resource adequacy requirements, that demonstrate progress toward meeting the standards under RCW 19.405.040(1) and 19.405.050(1) and the interim targets proposed under (a)(i) of this subsection. The specific actions identified must be informed by the investor-owned utility's historic performance under median water conditions and resource capability and by the investor-owned utility's participation in centralized markets. In identifying specific actions in its clean energy implementation plan, the investor-owned utility may also take into consideration any significant and unplanned loss or addition of load it experiences.

.. The commission, after a hearing, must by order approve, reject, or approve with conditions an investor-owned utility's clean energy implementation plan and interim targets. The commission may, in its order, recommend or require more stringent targets than those proposed by the investor-owned utility. The commission may periodically adjust or expedite timelines if it can be demonstrated that the targets or timelines can be achieved in a manner consistent with the following:

... Maintaining and protecting the safety, reliable operation, and balancing of the electric system;

... Planning to meet the standards at the lowest reasonable cost, considering risk;

... Ensuring that all customers are benefiting from the transition to clean energy: Through the equitable distribution of energy and nonenergy benefits and the reduction of burdens to vulnerable populations and highly impacted communities; long-term and short-term public health and environmental benefits and reduction of costs and risks; and energy security and resiliency; and

... Ensuring that no customer or class of customers is unreasonably harmed by any resulting increases in the cost of utility-supplied electricity as may be necessary to comply with the standards.

. [Empty]
.. By January 1, 2022, and every four years thereafter, each consumer-owned utility must develop and submit to the department a four-year clean energy implementation plan for the standards established under RCW 19.405.040(1) and 19.405.050(1) that:

... Proposes interim targets for meeting the standard under RCW 19.405.040(1) during the years prior to 2030 and between 2030 and 2045, as well as specific targets for energy efficiency, demand response, and renewable energy;

... Is informed by the consumer-owned utility's clean energy action plan developed under RCW 19.280.030(1) or other ten-year plan developed under RCW 19.280.030(5);

... Is consistent with subsection (4) of this section; and

... Identifies specific actions to be taken by the consumer-owned utility over the next four years, consistent with the utility's long-range resource plan and resource adequacy requirements, that demonstrate progress towards meeting the standards under RCW 19.405.040(1) and 19.405.050(1) and the interim targets proposed under (a)(i) of this subsection. The specific actions identified must be informed by the consumer-owned utility's historic performance under median water conditions and resource capability and by the consumer-owned utility's participation in centralized markets. In identifying specific actions in its clean energy implementation plan, the consumer-owned utility may also take into consideration any significant and unplanned loss or addition of load it experiences.

.. The governing body of the consumer-owned utility must, after a public meeting, adopt the consumer-owned utility's clean energy implementation plan. The clean energy implementation plan must be submitted to the department and made available to the public. The governing body may adopt more stringent targets than those proposed by the consumer-owned utility and periodically adjust or expedite timelines if it can be demonstrated that such targets or timelines can be achieved in a manner consistent with the following:

... Maintaining and protecting the safety, reliable operation, and balancing of the electric system;

... Planning to meet the standards at the lowest reasonable cost, considering risk;

... Ensuring that all customers are benefiting from the transition to clean energy: Through the equitable distribution of energy and nonenergy benefits and reduction of burdens to vulnerable populations and highly impacted communities; long-term and short-term public health and environmental benefits and reduction of costs and risks; and energy security and resiliency; and

... Ensuring that no customer or class of customers is unreasonably harmed by any resulting increases in the cost of utility-supplied electricity as may be necessary to comply with the standards.

. [Empty]
.. An investor-owned utility must be considered to be in compliance with the standards under RCW 19.405.040(1) and 19.405.050(1) if, over the four-year compliance period, the average annual incremental cost of meeting the standards or the interim targets established under subsection (1) of this section equals a two percent increase of the investor-owned utility's weather-adjusted sales revenue to customers for electric operations above the previous year, as reported by the investor-owned utility in its most recent commission basis report. All costs included in the determination of cost impact must be directly attributable to actions necessary to comply with the requirements of RCW 19.405.040 and 19.405.050.

.. If an investor-owned utility relies on (a) of this subsection as a basis for compliance with the standard under RCW 19.405.040(1), then it must demonstrate that it has maximized investments in renewable resources and nonemitting electric generation prior to using alternative compliance options allowed under RCW 19.405.040(1)(b).

. [Empty]
.. A consumer-owned utility must be considered to be in compliance with the standards under RCW 19.405.040(1) and 19.405.050(1) if, over the four-year compliance period, the average annual incremental cost of meeting the standards or the interim targets established under subsection (2) of this section meets or exceeds a two percent increase of the consumer-owned utility's retail revenue requirement above the previous year. All costs included in the determination of cost impact must be directly attributable to actions necessary to comply with the requirements of RCW 19.405.040 and 19.405.050.

.. If a consumer-owned utility relies on (a) of this subsection as a basis for compliance with the standard under RCW 19.405.040(1), and it has not met eighty percent of its annual retail electric load using electricity from renewable resources and nonemitting electric generation, then it must demonstrate that it has maximized investments in renewable resources and nonemitting electric generation prior to using alternative compliance options allowed under RCW 19.405.040(1)(b).

. The commission, for investor-owned utilities, and the department, for consumer-owned utilities, must adopt rules establishing the methodology for calculating the incremental cost of compliance under this section, as compared to the cost of an alternative lowest reasonable cost portfolio of investments that are reasonably available.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5116-S2.SL.pdf?cite=2019%20c%20288%20§%206[2019 c 288 § 6]; ]

== 19.405.070 - Greenhouse gas content calculation.
. Each electric utility must provide to the department, in the case of a consumer-owned utility, or to the commission, in the case of an investor-owned utility, its greenhouse gas content calculation in conformance with this section. A utility's greenhouse gas content calculation must be based on the fuel sources that it reports and discloses in compliance with chapter 19.29A RCW. An investor-owned utility must also report the information required in this subsection to the department.

. For unspecified electricity, the utility must use an emissions rate determined, and periodically updated, by the department of ecology by rule. The department of ecology must adopt an emissions rate for unspecified electricity consistent with the emissions rate established for other markets in the western interconnection. If the department of ecology has not adopted an emissions rate for unspecified electricity, the emissions rate that applies for the purposes of this chapter is 0.437 metric tons of carbon dioxide per megawatt-hour of electricity.

. For the purposes of chapter 288, Laws of 2019, the fuel mix calculated for the Bonneville power administration may exclude any purchases of electric generation that are not associated with load in the state of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5116-S2.SL.pdf?cite=2019%20c%20288%20§%207[2019 c 288 § 7]; ]

== 19.405.080 - Report to legislature.
By January 1, 2024, and at least every four years thereafter and in compliance with RCW 43.01.036, the department must submit a report to the legislature. The report must include the following:

. A review of the standards described in RCW 19.405.030 through 19.405.050 focused on technologies, forecasts, and existing transmission, and an evaluation of safety, environmental and public safety protection, affordability, and system reliability.

. [Empty]
.. An evaluation, produced in consultation with the commission, electric utilities, transmission operators in Washington, the reliability coordinator for electric utilities, any regional planning organization serving electric utilities, public interest and environmental organizations, and the regional entity for the western interconnection identifying the potential benefits, impacts, and risks on system reliability associated with achieving the standards described in RCW 19.405.040 and 19.405.050. The evaluation must assess whether electric utilities have sufficient electric generation resources to meet forecasted retail electric load in addition to adequate transmission capability to implement RCW 19.405.030 through 19.405.050 without: (i) Violating mandatory and enforceable reliability standards of the North American electric reliability corporation; (ii) violating prudent utility practice for assuring resource adequacy; or (iii) compromising the power quality or integrity of the electricity system. Subject to funding appropriated for this purpose, the department must consult with a national laboratory with expertise in grid reliability, security, and resilience.

.. The evaluation should assess the anticipated financial costs and benefits of investments necessary to correct those deficiencies at the lowest reasonable costs as identified by electric utilities, transmission operators in Washington, the regional entity for the western interconnection, or any regional planning organization serving electric utilities. The assessment of these investments in the report is not deemed to be approval of such investments for rate recovery by any authorizing entity.

. An evaluation identifying the nature of any anticipated financial costs and benefits to electric utilities, including customer rate impacts and benefits including, but not limited to:

.. Greenhouse gas emissions of electric utilities;

.. The allocation of risk between customers and electric utilities;

.. The allocation of financial costs among electric utilities in the state and whether retail electric customers are equitably bearing the financial costs of implementing RCW 19.405.030 through 19.405.050;

.. The timing of cost recovery for electricity generated by nonemitting electric generation or renewable resources;

.. The resource procurement process of electric utilities; and

.. The barriers to, and benefits of, implementing RCW 19.405.040 and 19.405.050.

. An evaluation of new or emerging technologies that could be considered to be a renewable resource.

. An assessment of the impacts of RCW 19.405.030 through 19.405.050 on middle-income families, small businesses, and manufacturers in Washington.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5116-S2.SL.pdf?cite=2019%20c%20288%20§%208[2019 c 288 § 8]; ]

== 19.405.090 - Compliance, enforcement, and penalties—Alternatives.
. [Empty]
.. An electric utility or an affected market customer that fails to meet the standards established under RCW 19.405.030(1) and 19.405.040(1) must pay an administrative penalty to the state of Washington in the amount of one hundred dollars, times the following multipliers, for each megawatt-hour of electric generation used to meet load that is not electricity from a renewable resource or nonemitting electric generation:

... 1.5 for coal-fired resources;

... 0.84 for gas-fired peaking power plants; and

... 0.60 for gas-fired combined-cycle power plants.

.. Beginning in 2027, this penalty must be adjusted on a biennial basis according to the rate of change of the inflation indicator, gross domestic product implicit price deflator, as published by the bureau of economic analysis of the United States department of commerce or its successor. Beginning in 2040, the commission may by rule increase this penalty for investor-owned utilities if the commission determines that doing so will accelerate utilities' compliance with the standards established under this chapter and that doing so is in the public interest.

. Consistent with the requirements of RCW 19.405.040(1)(b), a utility may opt to make a payment in the amount of the administrative penalty as an alternative compliance payment, without incurring a penalty for noncompliance.

. [Empty]
.. Upon its own motion or at the request of an investor-owned utility, and after a hearing, the commission may issue an order relieving the utility of its administrative penalty obligation under subsection (1) of this section if it finds that:

... After taking all reasonable measures, the investor-owned utility's compliance with this chapter is likely to result in conflicts with or compromises to its obligation to comply with the mandatory and enforceable reliability standards of the North American electric reliability corporation, violate prudent utility practice for assuring resource adequacy, or compromise the power quality or integrity of its system; or

... The investor-owned utility is unable to comply with the standards established in RCW 19.405.030(1) or 19.405.040(1) due to reasons beyond the reasonable control of the investor-owned utility, as set forth in subsection (6) of this section.

.. If the commission issues an order pursuant to (a) of this subsection that relieves an investor-owned utility of its administrative penalty obligation under subsection (1) of this section, the commission may issue an order:

... Temporarily exempting the investor-owned utility from the requirements of RCW 19.405.040(1) for an amount of time sufficient to allow the investor-owned utility to achieve full compliance with the standard;

... Directing the investor-owned utility to file a progress report to the commission on achieving full compliance with the standard within six months after issuing the order, or within an amount of time determined to be reasonable by the commission; and

... Directing the investor-owned utility to take specific actions to achieve full compliance with the requirements of this chapter.

.. An investor-owned utility may request an extension of a temporary exemption granted under this section. An investor-owned utility that requests an extension must request an update to the order issued by the commission under (b) of this subsection.

. Subsection (3) of this section does not permanently relieve an investor-owned utility of its obligation to comply with the requirements of this chapter.

. [Empty]
.. The governing body of a consumer-owned utility may authorize a temporary exemption from the standard established under RCW 19.405.040(1), for an amount of time sufficient to allow the consumer-owned utility to achieve full compliance with the standard, if the governing body finds that:

... The consumer-owned utility's compliance with the standard is likely to: Result in conflicts with or compromises to its obligation to comply with the mandatory and enforceable reliability standards of the North American electric reliability corporation; violate prudent utility practice for assuring resource adequacy; or compromise the power quality or integrity of its system; or

... The consumer-owned utility is unable to comply with the standard due to reasons beyond the reasonable control of the utility, as set forth in subsection (6) of this section; and

... The consumer-owned utility has provided to the department a plan demonstrating how it plans to achieve full compliance with the standard, consistent with the findings of the report submitted to the legislature under RCW 19.405.080.

.. Upon request by the governing body of a consumer-owned utility, a consumer-owned utility must be relieved of its administrative penalty obligation under subsection (1) of this section if the auditor issues a finding that:

... The governing body of the consumer-owned utility has properly issued a temporary exemption under (a) of this subsection for a period of time not to exceed six months; and

... The governing body of the consumer-owned utility has submitted to the department a plan to take specific actions to achieve full compliance with the standard, consistent with the findings of the report submitted to the legislature under RCW 19.405.080.

.. Upon issuance of a finding by the auditor, the consumer-owned utility must submit a progress report to the department on achieving full compliance with the standard within the term authorized in the temporary exemption.

.. A consumer-owned utility may request an extension of a temporary exemption granted under this subsection, subject to the same requirements as provided in (a) through (c) of this subsection.

.. The attorney general may bring a civil action in the name of the state for any appropriate civil remedy including, but not limited to, injunctive relief, penalties, costs, and attorneys' fees, to enforce compliance with this chapter:

... Upon the failure of the governing body of a consumer-owned utility to comply with the conditions of a temporary exemption found by the auditor to be properly adopted or extended; or

... Upon failure of the governing body of a consumer-owned utility to comply with a finding by the auditor that a temporary exemption is not properly granted.

.. This subsection does not permanently relieve a consumer-owned utility of its obligation to comply with the requirements of this chapter.

. To the extent an event or circumstance cannot be reasonably foreseen and ameliorated, such events or circumstances beyond the reasonable control of an electric utility may include but are not limited to:

.. Weather-related damage;

.. Natural disasters;

.. Mechanical or resource failure;

.. Failure of a third party to meet contractual obligations to the electric utility;

.. Actions of governmental authorities that adversely affect the generation, transmission, or distribution of nonemitting electric generation or renewable resources owned or under contract to an electric utility, including condemnation actions by municipal electric utilities, public utility districts, or irrigation districts that adversely affect an investor-owned utility's ability to meet the standard established in RCW 19.405.030(1) and 19.405.040(1);

.. Inability to acquire sufficient transmission to transmit electricity from nonemitting electric generation or renewable resources to load; and

.. Substantial limitations, restrictions, or prohibitions on nonemitting electric generation or renewable resources.

. An electric utility must notify its retail electric customers in published form within three months of paying the administrative penalty established under subsection (1) of this section. An electric utility is not required to notify its retail electric customers when making a payment in the amount of the administrative penalty as an alternative compliance payment consistent with the requirements of RCW 19.405.040(1)(b).

. Moneys collected under this section must be deposited into the low-income weatherization and structural rehabilitation assistance account created in RCW 70A.35.030.

. For an investor-owned utility, the commission must determine compliance with the requirements of this chapter.

. For consumer-owned utilities, the auditor is responsible for auditing compliance with this chapter and rules adopted under this chapter that apply to those utilities and the attorney general is responsible for enforcing that compliance.

. If the report submitted under RCW 19.405.080 demonstrates adverse system reliability impacts from the implementation of RCW 19.405.040 and 19.405.050, the governor, consistent with the emergency powers under RCW 43.21G.040, may suspend or delay implementation of this chapter, or exempt an electric utility from paying the administrative penalty under this section, until system reliability impacts can be addressed. Adverse system reliability impacts may include, but are not limited to, the inability of electric utilities or transmission operators to meet reliability standards mandated by federal or state law and required by prudent utility practices.

. Notwithstanding RCW 54.16.020, the fair market value compensation for an asset that is condemned by a municipal electric utility, public utility district, or irrigation district and that is either demonstrated in an electric utility's clean energy action plan or clean energy implementation plan to be used or acquired after May 7, 2019, to meet the requirements of RCW 19.405.040 and 19.405.050, or an asset that generates electricity from renewable resources or nonemitting electric generation, must include but not be limited to a replacement value approach. Additionally, the electric utility may seek, and the court may award, damages attributable to the severance, separation, replacement, or relocation of utility assets. The trier of fact may also consider other damages, as well as offsetting benefits, that it finds just and equitable.

. An entity that establishes or extends service to the premises of a customer who is being served by an electric utility or was served by an electric utility prior to May 7, 2019, must serve those premises in a manner that complies with the requirements of chapter 288, Laws of 2019 and with chapter 19.285 RCW, if applicable. An electric utility or other entity that fails to comply with the requirements of this subsection must pay the administrative penalty under subsection (1) of this section for each megawatt-hour of electric generation used to serve load that does not meet the terms of this subsection.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1192.SL.pdf?cite=2021%20c%2065%20§%2020[2021 c 65 § 20]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5116-S2.SL.pdf?cite=2019%20c%20288%20§%209[2019 c 288 § 9]; ]

== 19.405.100 - Rule making.
. It is the intent of this chapter that the commission and department adopt rules to streamline the implementation of chapter 288, Laws of 2019 with chapter 19.285 RCW to simplify compliance and avoid duplicative processes. It is the intent of the legislature that the commission and the department coordinate in developing rules related to process, timelines, and documentation that are necessary for the implementation of this chapter.

. The commission may adopt rules to ensure the proper implementation and enforcement of this chapter as it applies to investor-owned utilities.

. The department may adopt rules to ensure the proper implementation and enforcement of this chapter as it applies to consumer-owned utilities. Nothing in this subsection may be construed to restrict the rate-making authority of the governing body of a consumer-owned utility as otherwise provided by law.

. The department must adopt rules establishing reporting requirements for electric utilities to demonstrate compliance with this chapter. The requirements must, to the extent practicable, be consistent with the disclosures required under chapter 19.29A RCW.

. An investor-owned utility must also report all information required in subsection (4) of this section to the commission.

. An electric utility must also make reports required in this section available to its retail electric customers.

. The department of ecology must adopt rules, in consultation with the commission and the department of commerce, to establish requirements for energy transformation project investments including, but not limited to, verification procedures, reporting standards, and other logistical issues as necessary.

. The department must adopt rules providing for the measuring and tracking of thermal renewable energy credits that may be used for compliance under RCW 19.405.040.

. Pursuant to the administrative procedure act, chapter 34.05 RCW, rules needed for the implementation of this chapter must be adopted by January 1, 2021, unless specified otherwise elsewhere in this chapter. These rules may be revised as needed to carry out the intent and purposes of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5116-S2.SL.pdf?cite=2019%20c%20288%20§%2010[2019 c 288 § 10]; ]

== 19.405.110 - Relationship to the energy independence act.
The requirements of RCW 19.405.030 through 19.405.090 do not replace or modify the requirements established under chapter 19.285 RCW. All utility activities to comply with the requirements established under chapter 19.285 RCW also qualify for compliance with the requirements contained in this chapter, insofar as those activities meet the requirements of chapter 288, Laws of 2019.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5116-S2.SL.pdf?cite=2019%20c%20288%20§%2011[2019 c 288 § 11]; ]

== 19.405.120 - Energy assistance for low-income households.
. It is the intent of the legislature to demonstrate progress toward making energy assistance funds available to low-income households consistent with the policies identified in this section.

. An electric utility must make programs and funding available for energy assistance to low-income households by July 31, 2021. Each utility must demonstrate progress in providing energy assistance pursuant to the assessment and plans in subsection (4) of this section. To the extent practicable, priority must be given to low-income households with a higher energy burden.

. Beginning July 31, 2020, the department must collect and aggregate data estimating the energy burden and energy assistance need and reported energy assistance for each electric utility, in order to improve agency and utility efforts to serve low-income households with energy assistance. The department must update the aggregated data on a biennial basis, make it publicly accessible on its internet website and, to the extent practicable, include geographic attributes.

.. The aggregated data published by the department must include, but is not limited to:

... The estimated number and demographic characteristics of households served by energy assistance for each utility and the dollar value of the assistance;

... The estimated level of energy burden and energy assistance need among customers served, accounting for household income and other drivers of energy burden;

... Housing characteristics including housing type, home vintage, and fuel types; and

... Energy efficiency potential.

.. Each utility must disclose information to the department for use under this subsection, including:

... The amount and type of energy assistance and the number and type of households, if applicable, served for programs administered by the utility;

... The amount of money passed through to third parties that administer energy assistance programs; and

... Subject to availability, any other information related to the utility's low-income assistance programs that is requested by the department.

.. The information required by (b) of this subsection must be from the electric utility's most recent completed budget period and in a form, timeline, and manner as prescribed by the department.

. [Empty]
.. In addition to the requirements under subsection (3) of this section, each electric utility must submit biennially to the department an assessment of:

... The programs and mechanisms used by the utility to reduce energy burden and the effectiveness of those programs and mechanisms in both short-term and sustained energy burden reductions;

... The outreach strategies used to encourage participation of eligible households, including consultation with community-based organizations and Indian tribes as appropriate, and comprehensive enrollment campaigns that are linguistically and culturally appropriate to the customers they serve in vulnerable populations; and

... A cumulative assessment of previous funding levels for energy assistance compared to the funding levels needed to meet: (A) Sixty percent of the current energy assistance need, or increasing energy assistance by fifteen percent over the amount provided in 2018, whichever is greater, by 2030; and (B) ninety percent of the current energy assistance need by 2050.

.. The assessment required in (a) of this subsection must include a plan to improve the effectiveness of the assessed mechanisms and strategies toward meeting the energy assistance need.

. A consumer-owned utility may enter into an agreement with a public university, community-based organization, or joint operating agency organized under chapter 43.52 RCW to aggregate the disclosures required in this section and submit the assessment required in subsections (3) and (4) of this section.

. [Empty]
.. The department must submit a biennial report to the legislature that:

... Aggregates information into a statewide summary of energy assistance programs, energy burden, and energy assistance need;

... Identifies and quantifies current expenditures on low-income energy assistance; and

... Evaluates the effectiveness of additional optimal mechanisms for energy assistance including, but not limited to, customer rates, a low-income specific discount, system benefits charges, and public and private funds.

.. The department must also assess mechanisms to prioritize energy assistance towards low-income households with a higher energy burden.

. Nothing in this section may be construed to restrict the rate-making authority of the commission or the governing body of a consumer-owned utility as otherwise provided by law.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5116-S2.SL.pdf?cite=2019%20c%20288%20§%2012[2019 c 288 § 12]; ]

== 19.405.130 - Stakeholder work group.
. The department and the commission must convene a stakeholder work group to examine the:

.. Efficient and consistent integration of chapter 288, Laws of 2019 and transactions with carbon and electricity markets outside the state; and

.. Compatibility of the requirements under chapter 288, Laws of 2019 relative to a linked cap-and-trade program.

. To assist in its examination of the issues identified in this section, as well as any other issues pertinent to its review, the work group must, at a minimum, consist of electric utilities, gas companies, the Bonneville power administration, public interest and environmental organizations, and other agencies.

. The department and the commission must adopt rules by June 30, 2022, defining requirements, including appropriate specification, verification, and reporting requirements, for the following: (a) Retail electric load met with market purchases and the western energy imbalance market or other centralized market administered by a market operator for the purposes of RCW 19.405.030 through 19.405.050; and (b) to address the prohibition on double counting of nonpower attributes under RCW 19.405.040(1) that could occur under other programs. With respect to purchases from the western energy imbalance market or other centralized market, the department and the commission must consult with the market operator and market participants to consider options that support the objectives of this chapter and the efficient dispatch of the generation resources dispatched by those markets.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5116-S2.SL.pdf?cite=2019%20c%20288%20§%2013[2019 c 288 § 13]; ]

== 19.405.140 - Department of health—Cumulative impact analysis.
By December 31, 2020, the department of health must develop a cumulative impact analysis to designate the communities highly impacted by fossil fuel pollution and climate change in Washington. The cumulative impact analysis may integrate with and build upon other concurrent cross-agency efforts in developing a cumulative impact analysis and population tracking resources used by the department of health and analysis performed by the University of Washington department of environmental and occupational health sciences.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5116-S2.SL.pdf?cite=2019%20c%20288%20§%2024[2019 c 288 § 24]; ]

== 19.405.150 - Finding—Transmission corridors work group. (Expires January 1, 2023.)
. The legislature finds that based on current technology, there will likely need to be upgrades to electricity transmission and distribution infrastructure across the state to meet the goals specified in chapter 288, Laws of 2019. These facilities require a significant planning horizon to deliver electricity generation sites to retail electric load. Pursuant to RCW 80.50.040, the energy facility site evaluation council chair shall convene a transmission corridors work group and report its findings to the governor and the appropriate committees of the legislature by December 31, 2022.

. The work group must include one representative from each of the following state agencies: The department of commerce, the utilities and transportation commission, the department of ecology, the department of fish and wildlife, the department of natural resources, the department of transportation, the department of archaeology and historic preservation, and the state military department. The work group shall also include two representatives designated by the association of Washington cities, one from central or eastern Washington and one from western Washington; two representatives designated by the Washington state association of counties, one from central or eastern Washington and one from western Washington; two members designated by sovereign tribal governments; one member representing affected utility industries; one member representing public utility districts; and two members representing statewide environmental organizations. The energy facility site evaluation council chair shall invite the Bonneville power administration and the United States department of defense to each appoint an ex officio work group member.

. The work group shall:

.. Review the need for upgraded and new electricity transmission and distribution facilities to improve reliability, relieve congestion, and enhance the capability of the transmission and distribution facilities in the state to deliver electricity from electric generation, nonemitting electric generation, or renewable resources to retail electric load;

.. Identify areas where transmission and distribution facilities may need to be enhanced or constructed; and

.. Identify environmental review options that may be required to complete the designation of such corridors and recommend ways to expedite review of transmission projects without compromising required environmental protection.

. The energy facility site evaluation council may contract services to assist in the work group efforts.

. This section expires January 1, 2023.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5116-S2.SL.pdf?cite=2019%20c%20288%20§%2025[2019 c 288 § 25]; ]

== 19.405.900 - Short title.
This chapter may be known and cited as the Washington clean energy transformation act.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5116-S2.SL.pdf?cite=2019%20c%20288%20§%2026[2019 c 288 § 26]; ]

== 19.405.901 - Effective date—2019 c 288.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and takes effect immediately [May 7, 2019].

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5116-S2.SL.pdf?cite=2019%20c%20288%20§%2031[2019 c 288 § 31]; ]

