= 70.85 - Emergency party line telephone calls—Limiting telephone communication in hostage situations.
:toc:

== 70.85.010 - Definitions.
"Party line" means a subscribers' line telephone circuit, consisting of two or more main telephone stations connected therewith, each station with a distinctive ring or telephone number.

"Emergency" means a situation in which property or human life are in jeopardy and the prompt summoning of aid is essential.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c25.pdf?cite=1953%20c%2025%20§%201[1953 c 25 § 1]; ]

== 70.85.020 - Refusal to yield line—Penalty.
Any person who shall wilfully refuse to yield or surrender the use of a party line to another person for the purpose of permitting such other person to report a fire or summon police, medical or other aid in case of emergency, shall be deemed guilty of a misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c25.pdf?cite=1953%20c%2025%20§%202[1953 c 25 § 2]; ]

== 70.85.030 - Request for line on pretext of emergency—Penalty.
Any person who shall ask for or request the use of a party line on pretext that an emergency exists, knowing that no emergency in fact exists, shall be deemed guilty of a misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c25.pdf?cite=1953%20c%2025%20§%203[1953 c 25 § 3]; ]

== 70.85.040 - Telephone directories—Notice.
After September 9, 1953, every telephone directory thereafter distributed to the members of the general public shall contain a notice which explains this chapter, such notice to be printed in type which is no smaller than any other type on the same page and to be preceded by the word "warning": PROVIDED, That the provisions of this section shall not apply to those directories distributed solely for business advertising purposes, commonly known as classified directories.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c25.pdf?cite=1953%20c%2025%20§%204[1953 c 25 § 4]; ]

== 70.85.100 - Authority to isolate telephones in barricade or hostage situation—Definitions.
. The supervising law enforcement official having jurisdiction in a geographical area who reasonably believes that a person is barricaded, or one or more persons are holding another person or persons hostage within that area may order a telephone company employee designated pursuant to RCW 70.85.110 to arrange to cut, reroute, or divert telephone lines for the purpose of preventing telephone communications between the barricaded person or hostage holder and any person other than a peace officer or a person authorized by the peace officer.

. As used in this section:

.. A "hostage holder" is one who commits or attempts to commit any of the offenses described in RCW 9A.40.020, 9A.40.030, or 9A.40.040; and

.. A "barricaded person" is one who establishes a perimeter around an area from which others are excluded and either:

... Is committing or is immediately fleeing from the commission of a violent felony; or

... Is threatening or has immediately prior threatened a violent felony or suicide; or

... Is creating or has created the likelihood of serious harm within the meaning of chapter 71.05 RCW relating to mental illness.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c260.pdf?cite=1985%20c%20260%20§%201[1985 c 260 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c28.pdf?cite=1979%20c%2028%20§%201[1979 c 28 § 1]; ]

== 70.85.110 - Telephone companies to provide contacting information.
The telephone company providing service within the geographical jurisdiction of a law enforcement unit shall inform law enforcement agencies of the address and telephone number of its security office or other designated office to provide all required assistance to law enforcement officials to carry out the purpose of RCW 70.85.100 through 70.85.130. The designation shall be in writing and shall provide the telephone number or numbers through which the security representative or other telephone company official can be reached at any time. This information shall be served upon all law enforcement units having jurisdiction in a geographical area. Any change in address or telephone number or identity of the telephone company office to be contacted to provide required assistance shall be served upon all law enforcement units in the affected geographical area.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c28.pdf?cite=1979%20c%2028%20§%202[1979 c 28 § 2]; ]

== 70.85.120 - Liability of telephone company.
Good faith reliance on an order given under RCW 70.85.100 through 70.85.130 by a supervising law enforcement official shall constitute a complete defense to any civil or criminal action arising out of such ordered cutting, rerouting or diverting of telephone lines.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c28.pdf?cite=1979%20c%2028%20§%203[1979 c 28 § 3]; ]

== 70.85.130 - Applicability.
RCW 70.85.100 through 70.85.120 will govern notwithstanding the provisions of any other section of this chapter and notwithstanding the provisions of chapter 9.73 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c28.pdf?cite=1979%20c%2028%20§%204[1979 c 28 § 4]; ]

