= 70.12 - Public health funds.
:toc:

== 70.12.015 - Secretary may expend funds in counties.
The secretary of health is hereby authorized to apportion and expend such sums as he or she shall deem necessary for public health work in the counties of the state, from the appropriations made to the state department of health for county public health work.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20315[1991 c 3 § 315]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%2086[1979 c 141 § 86]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c191.pdf?cite=1939%20c%20191%20§%202[1939 c 191 § 2]; RRS § 6001-1; ]

== 70.12.025 - County funds for public health.
Each county legislative authority shall annually budget and appropriate a sum for public health work.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c291.pdf?cite=1975%201st%20ex.s.%20c%20291%20§%202[1975 1st ex.s. c 291 § 2]; ]

== 70.12.030 - Public health pooling fund.
Any county, combined city-county health department, or health district is hereby authorized and empowered to create a "public health pooling fund", hereafter called the "fund", for the efficient management and control of all moneys coming to such county, combined department, or district for public health purposes.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20245[1993 c 492 § 245]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c46.pdf?cite=1945%20c%2046%20§%201[1945 c 46 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c190.pdf?cite=1943%20c%20190%20§%201[1943 c 190 § 1]; Rem. Supp. 1945 § 6099-1; ]

== 70.12.040 - Fund, how maintained and disbursed.
Any such fund may be established in the county treasurer's office or the city treasurer's office of a first-class city according to the type of local health department organization existing.

In a district composed of more than one county, the county treasurer of the county having the largest population shall be the custodian of the fund, and the county auditor of said county shall keep the record of receipts and disbursements; and shall draw and the county treasurer shall honor and pay all such warrants.

Into any such fund so established may be paid:

. All grants from any state fund for county public health work;

. Any county current expense funds appropriated for the health department;

. Any other money appropriated by the county for health work;

. City funds appropriated for the health department;

. All moneys received from any governmental agency, local, state or federal which may contribute to the local health department; and

. Any contributions from any charitable or voluntary agency or contributions from any individual or estate.

Any school district may contract in writing for health services with the health department of the county, first-class city or health district, and place such funds in the public health pooling fund in accordance with the contract.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%20170[1983 c 3 § 170]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c46.pdf?cite=1945%20c%2046%20§%202[1945 c 46 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c190.pdf?cite=1943%20c%20190%20§%202[1943 c 190 § 2]; Rem. Supp. 1945 § 6099-2; ]

== 70.12.050 - Expenditures from fund.
All expenditures in connection with salaries, wages and operations incurred in carrying on the health department of the county, combined city-county health department, or health district shall be paid out of such fund.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20246[1993 c 492 § 246]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c46.pdf?cite=1945%20c%2046%20§%203[1945 c 46 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c190.pdf?cite=1943%20c%20190%20§%203[1943 c 190 § 3]; Rem. Supp. 1945 § 6099-3; ]

== 70.12.060 - Expenditures geared to budget.
Any fund established as herein provided shall be expended so as to make the expenditures thereof agree with any respective appropriation period. Any accumulation in any such fund so established shall be taken into consideration when preparing any budget for the operations for the ensuing year.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c190.pdf?cite=1943%20c%20190%20§%204[1943 c 190 § 4]; Rem. Supp. 1943 § 6099-4; ]

== 70.12.070 - Fund subject to audit and check by state.
The public health pool fund shall be subject to audit by the state auditor and shall be subject to check by the state department of health.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1889.SL.pdf?cite=1995%20c%20301%20§%2077[1995 c 301 § 77]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20316[1991 c 3 § 316]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%2087[1979 c 141 § 87]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c190.pdf?cite=1943%20c%20190%20§%205[1943 c 190 § 5]; Rem. Supp. 1943 § 6099-5; ]

