= 70.58 - Vital statistics.
:toc:

== 70.58.005 - Definitions. (Effective until January 1, 2021.)
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Business days" means Monday through Friday except official state holidays.

. "Department" means the department of health.

. "Electronic approval" or "electronically approve" means approving the content of an electronically filed vital record through the processes provided by the department. Electronic approval processes shall be consistent with policies, standards, and procedures developed by the director of the consolidated technology services agency.

. "Embalmer" means a person licensed as required in chapter 18.39 RCW and defined in RCW 18.39.010.

. "Funeral director" means a person licensed as required in chapter 18.39 RCW and defined in RCW 18.39.010.

. "Vital records" means records of birth, death, fetal death, marriage, dissolution, annulment, and legal separation, as maintained under the supervision of the state registrar of vital statistics.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5315-S2.SL.pdf?cite=2015%203rd%20sp.s.%20c%201%20§%20412[2015 3rd sp.s. c 1 § 412]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5024.SL.pdf?cite=2015%20c%20225%20§%20103[2015 c 225 § 103]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1515.SL.pdf?cite=2009%20c%20231%20§%201[2009 c 231 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20151[2005 c 365 § 151]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20342[1991 c 3 § 342]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c223.pdf?cite=1987%20c%20223%20§%201[1987 c 223 § 1]; ]

== 70.58.010 - Registration districts. (Effective until January 1, 2021.)
Each city of the first class shall constitute a primary registration district and each county and the territory of counties jointly comprising a health district, exclusive of the portion included within cities of the first class, shall constitute a primary registration area. All other counties and municipal areas not included in the foregoing shall be divided into registration areas by the state registrar as he or she may deem essential to obtain the most efficient registration of vital events as provided by law.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20383[2012 c 117 § 383]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c52.pdf?cite=1979%20ex.s.%20c%2052%20§%202[1979 ex.s. c 52 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c106.pdf?cite=1951%20c%20106%20§%204[1951 c 106 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c180.pdf?cite=1915%20c%20180%20§%201[1915 c 180 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c83.pdf?cite=1907%20c%2083%20§%202[1907 c 83 § 2]; RRS § 6019; ]

== 70.58.020 - Local registrars—Deputies. (Effective until January 1, 2021.)
Under the direction and control of the state registrar, the health officer of each city of the first class shall be the local registrar in and for the primary registration district under his or her supervision as health officer and the health officer of each county and district health department shall be the local registrar in and for the registration area which he or she supervises as health officer and shall serve as such as long as he or she performs the registration duties as prescribed by law. He or she may be removed as local registrar of the registration area which he or she serves by the state board of health upon its finding of evidence of neglect in the performance of his or her duties as such registrar. The state registrar shall appoint local registrars for those registration areas not included in the foregoing and also in areas where the state board of health has removed the health officer from this position as registrar.

Each local registrar, subject to the approval of the state registrar, shall appoint in writing a sufficient number of deputy registrars to administer the laws relating to vital statistics, and shall certify the appointment of such deputies to the state registrar. Deputy registrars shall act in the case of absence, death, illness, or disability of the local registrar, or such other conditions as may be deemed sufficient cause to require their services.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20384[2012 c 117 § 384]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c52.pdf?cite=1979%20ex.s.%20c%2052%20§%203[1979 ex.s. c 52 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961ex1c5.pdf?cite=1961%20ex.s.%20c%205%20§%205[1961 ex.s. c 5 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c106.pdf?cite=1951%20c%20106%20§%205[1951 c 106 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c180.pdf?cite=1915%20c%20180%20§%202[1915 c 180 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c83.pdf?cite=1907%20c%2083%20§%203[1907 c 83 § 3]; RRS § 6020; ]

== 70.58.030 - Duties of local registrars. (Effective until January 1, 2021.)
The local registrar shall supply blank forms of certificates to such persons as require them. He or she shall carefully examine each certificate of birth, death, and fetal death when presented for record, and see that it has been made out in accordance with the provisions of law and the instructions of the state registrar. If any certificate of death is incomplete or unsatisfactory, the local registrar shall call attention to the defects in the return, and withhold issuing the burial-transit permit until it is corrected. If the certificate of death is properly executed and complete, he or she shall issue a burial-transit permit to the funeral director or person acting as such. If a certificate of a birth is incomplete, he or she shall immediately notify the informant, and require that the missing items be supplied if they can be obtained. He or she shall sign as local registrar to each certificate filed in attest of the date of filing in the office. He or she shall make a record of each birth, death, and fetal death certificate registered in such manner as directed by the state registrar. The local registrar shall transmit to the state registrar each original death or fetal death certificate no less than thirty days after the certificate was registered nor more than sixty days after the certificate was registered. On or before the fifteenth day and the last day of each month, each local registrar shall transmit to the state registrar all original birth certificates that were registered prior to that day and which had not been transmitted previously. A local registrar shall transmit an original certificate to the state registrar whenever the state registrar requests the transfer of the certificate from the local registrar. If no births or no deaths occurred in any month, he or she shall, on the tenth day of the following month, report that fact to the state registrar, on a card provided for this purpose. Local registrars in counties in which a first-class city or a city of twenty-seven thousand or more population is located may retain an exact copy of the original and make certified copies of the exact copy.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c99.pdf?cite=1990%20c%2099%20§%201[1990 c 99 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961ex1c5.pdf?cite=1961%20ex.s.%20c%205%20§%206[1961 ex.s. c 5 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c83.pdf?cite=1907%20c%2083%20§%2018[1907 c 83 § 18]; RRS § 6035; ]

== 70.58.040 - Compensation of local registrars. (Effective until January 1, 2021.)
A local registrar shall be paid the sum of one dollar for each birth, death, or fetal death certificate registered for his or her district which sum shall cover making out the burial-transit permit and record of the certificate to be filed and preserved in his or her office. If no births or deaths were registered during any month, the local registrar shall be paid the sum of one dollar for each report to that effect: PROVIDED, That all local health officers who are by statute required to serve as local registrars shall not be entitled to the fee of one dollar. Neither shall any members of their staffs be entitled to the above fee of one dollar when such persons serve as deputy registrars. All fees payable to local registrars shall be paid by the treasurer of the county or city, properly chargeable therewith, out of the funds of the county or city, upon warrants drawn by the auditor, or other proper officer of the county or city. No warrant shall be issued to a local registrar except upon a statement, signed by the state registrar, stating the names and addresses respectively of the local registrars entitled to fees from the county or city, and the number of certificates and reports of births, deaths, and fetal deaths, properly returned to the state registrar, by each local registrar, during three preceding calendar months prior to the date of the statement, and the amount of fees to which each local registrar is entitled, which statement the state registrar shall file with the proper officers during the months of January, April, July, and October of each year. Upon filing of the statement, the auditor or other proper officer of the county or city shall issue warrants for the amount due each local registrar.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20385[2012 c 117 § 385]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961ex1c5.pdf?cite=1961%20ex.s.%20c%205%20§%207[1961 ex.s. c 5 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c106.pdf?cite=1951%20c%20106%20§%208[1951 c 106 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c180.pdf?cite=1915%20c%20180%20§%2010[1915 c 180 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c83.pdf?cite=1907%20c%2083%20§%2019[1907 c 83 § 19]; RRS § 6036; ]

== 70.58.050 - Duty to enforce law. (Effective until January 1, 2021.)
The local registrars are hereby charged with the strict and thorough enforcement of the provisions of *this act in their districts, under the supervision and direction of the state registrar. And they shall make an immediate report to the state registrar of any violations of this law coming to their notice by observation or upon the complaint of any person, or otherwise. The state registrar is hereby charged with the thorough and efficient execution of the provisions of *this act in every part of the state, and with supervisory power over local registrars, to the end that all of the requirements shall be uniformly complied with. He or she shall have authority to investigate cases of irregularity or violation of law, personally or by accredited representative, and all local registrars shall aid him or her, upon request, in such investigation. When he or she shall deem it necessary, he or she shall report cases of violation of any of the provisions of *this act to the prosecuting attorney of the proper county with a statement of the fact and circumstances; and when any such case is reported to them by the state registrar, all prosecuting attorneys or officials acting in such capacity shall forthwith initiate and promptly follow up the necessary court proceedings against the parties responsible for the alleged violations of law. And upon request of the state registrar, the attorney general shall likewise assist in the enforcement of the provisions of *this act.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20386[2012 c 117 § 386]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c83.pdf?cite=1907%20c%2083%20§%2022[1907 c 83 § 22]; RRS § 6039; ]

== 70.58.055 - Certificates generally. (Effective until January 1, 2021.)
. To promote and maintain nationwide uniformity in the system of vital statistics, the certificates required by this chapter or by the rules adopted under this chapter shall include, as a minimum, the items recommended by the federal agency responsible for national vital statistics including social security numbers.

. [Empty]
.. The state board of health by rule may require additional pertinent information relative to the birth and manner of delivery as it may deem necessary for statistical study. This information shall be placed in a confidential section of the birth certificate form and shall not be used for certification, nor shall it be subject to the view of the public except as provided in (b) of this subsection. The state board of health may eliminate from the forms items that it determines are not necessary for statistical study.

.. Information contained in the confidential section of the birth certificate form may only be available for review by:

... A member of the public upon order of the court; or

... The individual who is the subject of the birth certificate upon confirmation of the identity of the requestor in a manner approved by the state board of health. Confidential information provided to the individual who is the subject of the birth certificate shall be limited to information on the child and shall not include information on the mother or father.

. Each certificate or other document required by this chapter shall be on a form or in a format prescribed by the state registrar.

. All vital records shall contain the data required for registration. No certificate may be held to be complete and correct that does not supply all items of information called for or that does not satisfactorily account for the omission of required items.

. Information required in certificates or documents authorized by this chapter may be filed and registered by photographic, electronic, or other means as prescribed by the state registrar.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1510-S.SL.pdf?cite=2009%20c%2044%20§%201[2009 c 44 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20948[1997 c 58 § 948]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2056-S.SL.pdf?cite=1991%20c%2096%20§%201[1991 c 96 § 1]; ]

== 70.58.061 - Electronic and hard copy transmission. (Effective until January 1, 2021.)
The department is authorized to prescribe by rule the schedule and system for electronic and hard copy transmission of certificates and documents required by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2056-S.SL.pdf?cite=1991%20c%2096%20§%202[1991 c 96 § 2]; ]

== 70.58.065 - Local registrar use of electronic databases. (Effective until January 1, 2021.)
The department, in mutual agreement with a local health officer as defined in RCW 70.05.010, may authorize a local registrar to access the statewide birth database or death database and to issue a certified copy of birth or death certificates from the respective statewide electronic databases. In such cases, the department may bill local registrars for only direct line charges associated with accessing birth and death databases.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2056-S.SL.pdf?cite=1991%20c%2096%20§%203[1991 c 96 § 3]; ]

== 70.58.070 - Registration of births required. (Effective until January 1, 2021.)
All births that occur in the state shall be immediately registered in the districts in which they occur, as hereinafter provided.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c83.pdf?cite=1907%20c%2083%20§%2011[1907 c 83 § 11]; RRS § 6028; ]

== 70.58.080 - Birth certificates—Filing—Establishing paternity—Surname of child. (Effective until January 1, 2021.)
. Within ten days after the birth of any child, the attending physician, midwife, or his or her agent shall:

.. Fill out a certificate of birth, giving all of the particulars required, including: (i) The mother's name and date of birth, and (ii) if the mother and father are married at the time of birth or an acknowledgment of paternity has been signed or one has been filed with the state registrar of vital statistics naming the man as the father, the father's name and date of birth; and

.. File the certificate of birth together with the mother's and father's social security numbers with the state registrar of vital statistics.

. The local registrar shall forward the birth certificate, any signed acknowledgment of paternity that has not been filed with the state registrar of vital statistics, and the mother's and father's social security numbers to the state office of vital statistics pursuant to RCW 70.58.030.

. The state registrar of vital statistics shall make available to the division of child support the birth certificates, the mother's and father's social security numbers and acknowledgments of paternity.

. Upon the birth of a child to an unmarried woman, the attending physician, midwife, or his or her agent shall:

.. Provide an opportunity for the child's mother and natural father to complete an acknowledgment of paternity. The completed acknowledgment shall be filed with the state registrar of vital statistics. The acknowledgment shall be prepared as required by *RCW 26.26.305.

.. Provide written information and oral information, furnished by the department of social and health services, to the mother and the father regarding the benefits of having the child's paternity established and of the availability of paternity establishment services, including a request for support enforcement services. The oral and written information shall also include information regarding the alternatives to, the legal consequences of, and the rights, including, if one parent is a minor any rights afforded due to minority status, and responsibilities that arise from, signing the acknowledgment of paternity.

. The physician or midwife or his or her agent is entitled to reimbursement for reasonable costs, which the department shall establish by rule, when an acknowledgment of paternity is filed with the state registrar of vital statistics.

. If there is no attending physician or midwife, the father or mother of the child, householder or owner of the premises, manager or superintendent of the public or private institution in which the birth occurred, shall notify the local registrar, within ten days after the birth, of the fact of the birth, and the local registrar shall secure the necessary information and signature to make a proper certificate of birth.

. When an infant is found for whom no certificate of birth is known to be on file, a birth certificate shall be filed within the time and in the form prescribed by the state board of health.

. When no alleged father is named on a birth certificate of a child born to an unwed mother the mother may give any surname she so desires to her child but shall designate in space provided for father's name on the birth certificate "None Named".

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2346-S2.SL.pdf?cite=2002%20c%20302%20§%20708[2002 c 302 § 708]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20937[1997 c 58 § 937]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c55.pdf?cite=1989%20c%2055%20§%202[1989 c 55 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961ex1c5.pdf?cite=1961%20ex.s.%20c%205%20§%208[1961 ex.s. c 5 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c106.pdf?cite=1951%20c%20106%20§%206[1951 c 106 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c83.pdf?cite=1907%20c%2083%20§%2012[1907 c 83 § 12]; RRS § 6029; ]

== 70.58.082 - Vital records—Rules—Release of copies. (Effective until January 1, 2021.)
No person may prepare or issue any vital record that purports to be an original, certified copy, or copy of a vital record except as authorized in this chapter.

The department shall adopt rules providing for the release of paper or electronic copies of vital records that include adequate standards for security and confidentiality, ensure the proper record is identified, and prevent fraudulent use of records. All certified copies of vital records in the state must be on paper and in a format provided and approved by the department and must include security features to deter the alteration, counterfeiting, duplication, or simulation without ready detection.

Federal, state, and local governmental agencies may, upon request and with submission of the appropriate fee, be furnished copies of vital records if the vital record will be used for the agencies' official duties. The department may enter into agreements with offices of vital statistics outside the state for the transmission of copies of vital records to those offices when the vital records relate to residents of those jurisdictions and receipt of copies of vital records from those offices. The agreement must specify the statistical and administrative purposes for which the vital records may be used and must provide instructions for the proper retention and disposition of the copies. Copies of vital records that are received by the department from other offices of vital statistics outside the state must be handled as provided under the agreements.

The department may disclose information that may identify any person named in any birth certificate [vital] record for research purposes as provided under chapter 42.48 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20152[2005 c 365 § 152]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1930-S.SL.pdf?cite=1997%20c%20108%20§%201[1997 c 108 § 1]; ]

== 70.58.085 - Birth certificates suitable for display—Issuance—Fee—Disposition of funds. (Effective until January 1, 2021.)
. In addition to the original birth certificate, the state registrar shall issue upon request and upon payment of the fee established pursuant to subsection (3) of this section a birth certificate representing that the birth of the person named thereon is recorded in the office of the registrar. The certificate issued under this section shall be in a form consistent with the need to protect the integrity of vital records but shall be suitable for display. It may bear the seal of the state printed thereon and may be signed by the governor. It shall have the same status as evidence as the original birth certificate.

. Of the funds received under subsection (1) of this section, the amount needed to reimburse the registrar for expenses incurred in administering this section shall be credited to the state registrar account. The remainder shall be credited to the children's trust fund established under RCW 43.121.100.

. The fee shall be set by the council established pursuant to *RCW 43.121.020, at a level likely to maximize revenues for the children's trust fund.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6337.SL.pdf?cite=2004%20c%2053%20§%201[2004 c 53 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c351.pdf?cite=1987%20c%20351%20§%206[1987 c 351 § 6]; ]

== 70.58.095 - New certificate of birth—Legitimation, paternity—Substitution for original—Inspection of original, when—When delayed registration required. (Effective until January 1, 2021.)
The state registrar of vital statistics shall establish a new certificate of birth for a person born in this state when he or she receives a request that a new certificate be established and such evidence as required by regulation of the state board of health proving that such person has been acknowledged, or that a court of competent jurisdiction has determined the paternity of such person. When a new certificate of birth is established, the actual place and date of birth shall be shown. It shall be substituted for the original certificate of birth. Thereafter, the original certificate and the evidence of paternity, or acknowledgment shall not be subject to inspection except upon order of a court of competent jurisdiction, or upon written request of the department of social and health services, the attorney general, or a prosecuting attorney, stating that the documents are being sought in furtherance of an action to enforce a duty of support. If no certificate of birth is on file for the person for whom a new certificate is to be established under this section, a delayed registration of birth shall be filed with the state registrar of vital statistics as provided in RCW 70.58.120.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20387[2012 c 117 § 387]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c41.pdf?cite=1983%201st%20ex.s.%20c%2041%20§%2014[1983 1st ex.s. c 41 § 14]; 1975-'76 2nd ex.s. c 42 § 38; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961ex1c5.pdf?cite=1961%20ex.s.%20c%205%20§%2021[1961 ex.s. c 5 § 21]; ]

== 70.58.098 - Information regarding credit report security freeze. (Effective until January 1, 2021.)
The issuer of a certified birth certificate shall include information prepared by the department setting forth the advisability of a security freeze under RCW 19.182.230 and the process for acquiring a security freeze.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2859-S.SL.pdf?cite=2016%20c%20135%20§%203[2016 c 135 § 3]; ]

== 70.58.100 - Supplemental report on name of child. (Effective until January 1, 2021.)
It shall be the duty of every local registrar when any certificate of birth of a living child is presented without statement of the given name, to make out and deliver to the parents of such child a special blank for the supplemental report of the given name of the child, which shall be filled out as directed and returned to the registrar as soon as the child has been named.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c180.pdf?cite=1915%20c%20180%20§%208[1915 c 180 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c83.pdf?cite=1907%20c%2083%20§%2014[1907 c 83 § 14]; RRS § 6031; ]

== 70.58.104 - Reproductions of vital records—Disclosure of information for research purposes—Furnishing of birth and death records by local registrars. (Effective until January 1, 2021.)
. The state registrar may prepare typewritten, photographic, electronic, or other reproductions of records of birth, death, fetal death, marriage, or decrees of divorce, annulment, or legal separation registered under law or that portion of the record of any birth which shows the child's full name, sex, date of birth, and date of filing of the certificate. Such reproductions, when certified by the state registrar, shall be considered for all purposes the same as the original and shall be prima facie evidence of the facts stated therein.

. The department may authorize by regulation the disclosure of information contained in vital records for research purposes. All research proposals must be submitted to the department and must be reviewed and approved as to scientific merit and to ensure that confidentiality safeguards are provided in accordance with department policy.

. Local registrars may, upon request, furnish certified copies of the records of birth, death, and fetal death, subject to all provisions of state law applicable to the state registrar.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2056-S.SL.pdf?cite=1991%20c%2096%20§%204[1991 c 96 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c223.pdf?cite=1987%20c%20223%20§%202[1987 c 223 § 2]; ]

== 70.58.107 - Fees charged by department and local registrars. (Effective until January 1, 2021.)
The department of health shall charge a fee of twenty dollars for certified copies of records and for copies or information provided for research, statistical, or administrative purposes, and eight dollars for a search of the files or records when no copy is made. The department shall prescribe by regulation fees to be paid for preparing sealed files and for opening sealed files.

No fee may be demanded or required for furnishing certified copies of a birth, death, fetal death, marriage, divorce, annulment, or legal separation record for use in connection with a claim for compensation or pension pending before the veterans administration. No fee may be demanded or required for furnishing certified copies of a death certificate of a sex offender for use by a law enforcement agency in maintaining a registered sex offender database, or that of any offender requested by a county clerk or court in the state of Washington for purposes of extinguishing the offender's legal financial obligation.

The department shall keep a true and correct account of all fees received and transmit the fees to the state treasurer on a weekly basis.

Local registrars shall charge the same fees as the state as hereinabove provided and as prescribed by department regulation except in cases where payment is made by credit card, charge card, debit card, smart card, stored value card, federal wire, automatic clearinghouse system, or other electronic communication. Payment by these electronic methods may be subject to an additional fee consistent with the requirements established by RCW 36.29.190. All such fees collected, except for seven dollars of each fee collected for the issuance of birth certificates and first copies of death certificates and fourteen dollars of each fee collected for additional copies of the same death certificate ordered at the same time as the first copy, shall be paid to the jurisdictional health department.

All local registrars in cities and counties shall keep a true and correct account of all fees received under this section for the issuance of certified copies and shall transmit seven dollars of the fees collected for birth certificates and first copies of death certificates and fourteen dollars of the fee collected for additional copies of death certificates to the state treasurer on or before the first day of January, April, July, and October. All but five dollars of the fees turned over to the state treasurer by local registrars shall be paid to the department of health for the purpose of developing and maintaining the state vital records systems, including a web-based electronic death registration system.

Eight dollars of each fee imposed for the issuance of certified copies, except for copies suitable for display issued under RCW 70.58.085, at both the state and local levels shall be held by the state treasurer in the death investigations' account established by RCW 43.79.445.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1181.SL.pdf?cite=2007%20c%20200%20§%202[2007 c 200 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5190-S.SL.pdf?cite=2007%20c%2091%20§%202[2007 c 91 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1727.SL.pdf?cite=2003%20c%20272%20§%201[2003 c 272 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5545-S.SL.pdf?cite=2003%20c%20241%20§%201[2003 c 241 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1269.SL.pdf?cite=1997%20c%20223%20§%201[1997 c 223 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20343[1991 c 3 § 343]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c40.pdf?cite=1988%20c%2040%20§%201[1988 c 40 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c223.pdf?cite=1987%20c%20223%20§%203[1987 c 223 § 3]; ]

== 70.58.110 - Delayed registration of births—Authorized. (Effective until January 1, 2021.)
Whenever a birth which occurred in this state on or after July 1, 1907, is not on record in the office of the state registrar or in the office of the auditor of the county in which the birth occurred if the birth was prior to July 1, 1907, application for the registration of the birth may be made by the interested person to the state registrar: PROVIDED, That if the person whose birth is to be recorded be a child under four years of age the attending physician, if available, shall make the registration.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c90.pdf?cite=1953%20c%2090%20§%202[1953 c 90 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c176.pdf?cite=1943%20c%20176%20§%201[1943 c 176 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c167.pdf?cite=1941%20c%20167%20§%201[1941 c 167 § 1]; Rem. Supp. 1943 § 6011-1; ]

== 70.58.120 - Delayed registration of births—Application—Evidence required. (Effective until January 1, 2021.)
The delayed registration of birth form shall be provided by the state registrar and shall be signed by the registrant if of legal age, or by the attendant at birth, parent, or guardian if the registrant is not of legal age. In instances of delayed registration of birth where the person whose birth is to be recorded is four years of age or over but under twelve years of age and in instances where the person whose birth is to be recorded is less than four years of age and the attending physician is not available to make the registration, the facts concerning date of birth, place of birth, and parentage shall be established by at least one piece of documentary evidence. In instances of delayed registration of birth where the person whose birth is to be recorded is twelve years of age or over, the facts concerning date of birth and place of birth shall be established by at least three documents of which only one may be an affidavit. The facts concerning parentage shall be established by at least one document. Documents, other than affidavits, or documents established prior to the fourth birthday of the registrant, shall be at least five years old or shall have been made from records established at least five years prior to the date of application.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961ex1c5.pdf?cite=1961%20ex.s.%20c%205%20§%209[1961 ex.s. c 5 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c90.pdf?cite=1953%20c%2090%20§%203[1953 c 90 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c176.pdf?cite=1943%20c%20176%20§%202[1943 c 176 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c167.pdf?cite=1941%20c%20167%20§%202[1941 c 167 § 2]; Rem. Supp. 1943 § 6011-2; ]

== 70.58.130 - Delayed registration of births—Where registered—Copy as evidence. (Effective until January 1, 2021.)
The birth shall be registered in the records of the state registrar. A certified copy of the record shall be prima facie evidence of the facts stated therein.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961ex1c5.pdf?cite=1961%20ex.s.%20c%205%20§%2010[1961 ex.s. c 5 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c90.pdf?cite=1953%20c%2090%20§%204[1953 c 90 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c106.pdf?cite=1951%20c%20106%20§%202[1951 c 106 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c176.pdf?cite=1943%20c%20176%20§%204[1943 c 176 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c167.pdf?cite=1941%20c%20167%20§%204[1941 c 167 § 4]; Rem. Supp. 1943 § 6011-4; ]

== 70.58.145 - Order establishing record of birth when delayed registration not available—Procedure. (Effective until January 1, 2021.)
When a person alleged to be born in this state is unable to meet the requirements for a delayed registration of birth in accordance with RCW 70.58.120, he or she may petition the superior court of the county of residence or of the county of birth for an order establishing a record of the date and place of his or her birth, and his or her parentage. The court shall fix a time for hearing the petition, and the state registrar shall be given notice at least twenty days prior to the date set for hearing in order that he or she may present at the hearing any information he or she believes will be useful to the court. If the court from the evidence presented to it finds that the petitioner was born in this state, the court shall issue an order to establish a record of birth. This order shall include the birth data to be registered. If the court orders the birth of a person born in this state registered, it shall be registered in the records of the state registrar.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20388[2012 c 117 § 388]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961ex1c5.pdf?cite=1961%20ex.s.%20c%205%20§%2020[1961 ex.s. c 5 § 20]; ]

== 70.58.150 - "Fetal death," "evidence of life," defined. (Effective until January 1, 2021.)
A fetal death means any product of conception that shows no evidence of life after complete expulsion or extraction from its mother. The words "evidence of life" include breathing, beating of the heart, pulsation of the umbilical cord, or definite movement of voluntary muscles.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961ex1c5.pdf?cite=1961%20ex.s.%20c%205%20§%2011[1961 ex.s. c 5 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c159.pdf?cite=1945%20c%20159%20§%205[1945 c 159 § 5]; Rem. Supp. 1945 § 6024-5; ]

== 70.58.160 - Certificate of death or fetal death required. (Effective until January 1, 2021.)
A certificate of every death or fetal death shall be filed with the local registrar of the district in which the death or fetal death occurred within three business days after the occurrence is known, or if the place of death or fetal death is not known, then with the local registrar of the district in which the human remains are found within one business day thereafter. In every instance a certificate shall be filed prior to the interment or other disposition of the human remains. However, a certificate of fetal death shall not be required if the period of gestation is less than twenty weeks.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20153[2005 c 365 § 153]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961ex1c5.pdf?cite=1961%20ex.s.%20c%205%20§%2012[1961 ex.s. c 5 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c159.pdf?cite=1945%20c%20159%20§%201[1945 c 159 § 1]; Rem. Supp. 1945 § 6024-1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c180.pdf?cite=1915%20c%20180%20§%204[1915 c 180 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c83.pdf?cite=1907%20c%2083%20§%205[1907 c 83 § 5]; ]

== 70.58.170 - Certificate of death or fetal death—By whom filed. (Effective until January 1, 2021.)
The funeral director or person having the right to control the disposition of the human remains under RCW 68.50.160 shall file the certificate of death or fetal death. In preparing such certificate, the funeral director or person having the right to control the disposition of the human remains under RCW 68.50.160 shall obtain and enter on the certificate such personal data as the certificate requires from the person or persons best qualified to supply them. He or she shall present the certificate of death to the physician, physician's assistant, or advanced registered nurse practitioner last in attendance upon the deceased, or, if the deceased died without medical attendance, to the health officer, medical examiner, coroner, or prosecuting attorney having jurisdiction, who shall certify the cause of death according to his or her best knowledge and belief and shall sign or electronically approve the certificate of death or fetal death within two business days after being presented with the certificate unless good cause for not signing or electronically approving the certificate within the two business days can be established. He or she shall present the certificate of fetal death to the physician, physician's assistant, advanced registered nurse practitioner, midwife, or other person in attendance at the fetal death, who shall certify the fetal death and such medical data pertaining thereto as he or she can furnish.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1515.SL.pdf?cite=2009%20c%20231%20§%202[2009 c 231 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20154[2005 c 365 § 154]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5739.SL.pdf?cite=2000%20c%20133%20§%201[2000 c 133 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c162.pdf?cite=1979%20ex.s.%20c%20162%20§%201[1979 ex.s. c 162 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961ex1c5.pdf?cite=1961%20ex.s.%20c%205%20§%2013[1961 ex.s. c 5 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c159.pdf?cite=1945%20c%20159%20§%202[1945 c 159 § 2]; Rem. Supp. 1945 § 6024-2; ]

== 70.58.175 - Certificate of death—Domestic partnership information. (Effective until January 1, 2021.)
Information recorded on death certificates shall include domestic partnership status and the surviving partner's information to the same extent such information is recorded for marital status and the surviving spouse's information.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5336-S.SL.pdf?cite=2007%20c%20156%20§%2032[2007 c 156 § 32]; ]

== 70.58.180 - Certificate when no physician, physician's assistant, or advanced registered nurse practitioner in attendance—Legally accepted cause of death. (Effective until January 1, 2021.)
If the death occurred without medical attendance, the funeral director or person having the right to control the disposition of the human remains under RCW 68.50.160 shall notify the coroner, medical examiner, or prosecuting attorney if there is no coroner or medical examiner in the county. If the circumstances suggest that the death or fetal death was caused by unlawful or unnatural causes or if there is no local health officer with jurisdiction, the coroner or medical examiner, or the prosecuting attorney shall complete and sign or electronically approve the certification, noting upon the certificate that no physician, physician's assistant, or advanced registered nurse practitioner was in attendance at the time of death. In case of any death without medical attendance in which there is no suspicion of death from unlawful or unnatural causes, the local health officer or his or her deputy, the coroner or medical examiner, and if none, the prosecuting attorney, shall complete and sign or electronically approve the certification, noting upon the certificate that no physician, physician's assistant, or advanced registered nurse practitioner was in attendance at the time of death, and noting the cause of death without the holding of an inquest or performing of an autopsy or postmortem, but from statements of relatives, persons in attendance during the last sickness, persons present at the time of death or other persons having adequate knowledge of the facts.

The cause of death, the manner and mode in which death occurred, as noted by the coroner or medical examiner, or if none, the prosecuting attorney or the health officer and incorporated in the death certificate filed with the department shall be the legally accepted manner and mode by which the deceased came to his or her death and shall be the legally accepted cause of death.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1515.SL.pdf?cite=2009%20c%20231%20§%203[2009 c 231 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20155[2005 c 365 § 155]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5739.SL.pdf?cite=2000%20c%20133%20§%202[2000 c 133 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961ex1c5.pdf?cite=1961%20ex.s.%20c%205%20§%2014[1961 ex.s. c 5 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c188.pdf?cite=1953%20c%20188%20§%205[1953 c 188 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c159.pdf?cite=1945%20c%20159%20§%203[1945 c 159 § 3]; Rem. Supp. 1945 § 6024-3; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c180.pdf?cite=1915%20c%20180%20§%205[1915 c 180 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c83.pdf?cite=1907%20c%2083%20§%207[1907 c 83 § 7]; ]

== 70.58.190 - Permit to dispose of human remains when cause of death undetermined. (Effective until January 1, 2021.)
If the cause of death cannot be determined within three business days, the certification of its cause may be filed after the prescribed period, but the attending physician, coroner, or prosecuting attorney shall give the local registrar of the district in which the death occurred written notice of the reason for the delay, in order that a permit for the disposition of the human remains may be issued if required.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20156[2005 c 365 § 156]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c159.pdf?cite=1945%20c%20159%20§%204[1945 c 159 § 4]; Rem. Supp. 1945 § 6024-4; ]

== 70.58.210 - Birth certificate upon adoption. (Effective until January 1, 2021.)
. Whenever a decree of adoption has been entered declaring a child, born in the state of Washington, adopted in any court of competent jurisdiction in the state of Washington or any other state or any territory of the United States, a certified copy of the decree of adoption shall be recorded with the proper department of registration of births in the state of Washington and a certificate of birth shall issue upon request, bearing the new name of the child as shown in the decree of adoption, the names of the adoptive parents of the child and the age, sex, and date of birth of the child, but no reference in any birth certificate shall have reference to the adoption of the child. However, original registration of births shall remain a part of the record of the board of health.

. Whenever a decree of adoption has been entered declaring a child, born outside of the United States and its territories, adopted in any court of competent jurisdiction in the state of Washington, a certified copy of the decree of adoption together with evidence as to the child's birthdate and birthplace provided by the original birth certificate, or by a certified copy, extract, or translation thereof or by a certified copy of some other document essentially equivalent thereto, shall be recorded with the proper department of registration of births in the state of Washington. The records of the United States immigration and naturalization service or of the United States department of state are essentially equivalent to the birth certificate. A certificate of birth shall issue upon request, bearing the new name of the child as shown in the decree of adoption, the names of the adoptive parents of the child and the age, sex, and date of birth of the child, but no reference in any birth certificate shall have reference to the adoption of the child. Unless the court orders otherwise, the certificate of birth shall have the same overall appearance as the certificate which would have been issued if the adopted child had been born in the state of Washington.

A person born outside of the United States and its territories for whom a decree of adoption has been entered in a court of this state before September 1, 1979, may apply for a certificate of birth under this subsection by furnishing the proper department of registration of births with a certified copy of the decree of adoption together with the other evidence required by this subsection as to the date and place of birth. Upon receipt of the decree and evidence, a certificate of birth shall be issued in accordance with this subsection.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c101.pdf?cite=1979%20ex.s.%20c%20101%20§%202[1979 ex.s. c 101 § 2]; 1975-'76 2nd ex.s. c 42 § 40; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c12.pdf?cite=1943%20c%2012%20§%201[1943 c 12 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c133.pdf?cite=1939%20c%20133%20§%201[1939 c 133 § 1]; Rem. Supp. 1943 § 6013-1; ]

== 70.58.230 - Permits for burial, removal, etc., required—Removal to another district without permit, notice to registrar, fee.
It is unlawful for any person to inter; deposit in a vault, grave, or tomb; perform alkaline hydrolysis or natural organic reduction as defined in RCW 68.04.310; or otherwise dispose of, or disinter or remove from one registration district to another, or hold for more than three business days after death, the human remains of any person whose death occurred in this state or any human remains which shall be found in this state, without obtaining, from the local registrar of the district in which the death occurred or in which the human remains were found, a permit for the burial, disinterment, or removal of the human remains. However, a licensed funeral director or embalmer of this state or a funeral establishment licensed in another state contiguous to Washington, with a current certificate of removal registration issued by the director of the department of licensing, may remove human remains from the district where the death occurred to another registration district or Oregon or Idaho without having obtained a permit but in such cases the funeral director or embalmer must at the time of removing human remains file with or mail to the local registrar of the district where the death occurred a notice of removal upon a blank to be furnished by the state registrar. The notice of removal must be signed or electronically approved by the funeral director or embalmer and must contain the name and address of the local registrar with whom the certificate of death will be filed and the burial-transit permit secured. Every local registrar, accepting a death certificate and issuing a burial-transit permit for a death that occurred outside his or her district, is entitled to a fee of one dollar to be paid by the funeral director or embalmer at the time the death certificate is accepted and the permit is secured. It is unlawful for any person to bring into or transport within the state or inter, deposit in a vault, grave, or tomb, or cremate or otherwise dispose of human remains of any person whose death occurred outside this state unless the human remains are accompanied by a removal or transit permit issued in accordance with the law and health regulations in force where the death occurred, or unless a special permit for bringing the human remains into this state is obtained from the state registrar.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5001-S.SL.pdf?cite=2019%20c%20432%20§%2030[2019 c 432 § 30]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1515.SL.pdf?cite=2009%20c%20231%20§%204[2009 c 231 § 4]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20157[2005 c 365 § 157]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961ex1c5.pdf?cite=1961%20ex.s.%20c%205%20§%2016[1961 ex.s. c 5 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c180.pdf?cite=1915%20c%20180%20§%203[1915 c 180 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c83.pdf?cite=1907%20c%2083%20§%204[1907 c 83 § 4]; RRS § 6021; ]

== 70.58.240 - Duties of funeral directors. (Effective until January 1, 2021.)
Each funeral director or person having the right to control the disposition of the human remains under RCW 68.50.160 shall obtain a certificate of death, sign or electronically approve and file the certificate with the local registrar, and secure a burial-transit permit, prior to any permanent disposition of the human remains. He or she shall obtain the personal and statistical particulars required, from the person best qualified to supply them. He or she shall present the certificate to the attending physician or in case the death occurred without any medical attendance, to the proper official for certification for the medical certificate of the cause of death and other particulars necessary to complete the record. He or she shall supply the information required relative to the date and place of disposition and he or she shall sign or electronically approve and present the completed certificate to the local registrar, for the issuance of a burial-transit permit. He or she shall deliver the burial permit to the sexton, or person in charge of the place of burial, before interring the human remains; or shall attach the transit permit to the box containing the corpse, when shipped by any transportation company, and the permit shall accompany the corpse to its destination.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1515.SL.pdf?cite=2009%20c%20231%20§%205[2009 c 231 § 5]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20158[2005 c 365 § 158]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961ex1c5.pdf?cite=1961%20ex.s.%20c%205%20§%2017[1961 ex.s. c 5 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c180.pdf?cite=1915%20c%20180%20§%206[1915 c 180 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c83.pdf?cite=1907%20c%2083%20§%208[1907 c 83 § 8]; RRS § 6025; ]

== 70.58.250 - Burial-transit permit—Requisites. (Effective until January 1, 2021.)
The burial-transit permit shall contain a statement by the local registrar and over his or her signature or electronic approval, that a satisfactory certificate of death having been filed with him or her, as required by law, permission is granted to inter, remove, or otherwise dispose of the body; stating the name of the deceased and other necessary details upon the form prescribed by the state registrar.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1515.SL.pdf?cite=2009%20c%20231%20§%206[2009 c 231 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961ex1c5.pdf?cite=1961%20ex.s.%20c%205%20§%2018[1961 ex.s. c 5 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c83.pdf?cite=1907%20c%2083%20§%209[1907 c 83 § 9]; RRS § 6026; ]

== 70.58.260 - Burial grounds—Duties of individual in charge of the premises.
It is unlawful for any person in charge of any premises in which bodies of deceased persons are interred, cremated, or otherwise permanently disposed of, to permit the final disposition, or other disposition of any body upon such premises unless it is accompanied by a burial, removal, or transit permit as provided in this chapter. It is the duty of the person in charge of any such premises to, in case of the interment, cremation, alkaline hydrolysis, natural organic reduction as defined in RCW 68.04.310, or other disposition of human remains therein, endorse upon the permit the date and character of such disposition, over his or her signature or electronic approval, to return all permits so endorsed to the local registrar of the district in which the death occurred within ten days from the date of such disposition, and to keep a record of all human remains disposed of on the premises under his or her charge, stating, in each case, the name of the deceased person, if known, the place of death, the date of burial or other disposition, and the name and address of the undertaker, which record must at all times be open to public inspection, and it is the duty of every undertaker, or person acting as such, when burying human remains in a cemetery or burial grounds having no person in charge, to sign or electronically approve the burial, removal, or transit permit, giving the date of burial, write across the face of the permit the words "no person in charge," and file the burial, removal, or transit permit within ten days with the registrar of the district in which the death occurred.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5001-S.SL.pdf?cite=2019%20c%20432%20§%2031[2019 c 432 § 31]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1515.SL.pdf?cite=2009%20c%20231%20§%207[2009 c 231 § 7]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20159[2005 c 365 § 159]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c180.pdf?cite=1915%20c%20180%20§%207[1915 c 180 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c83.pdf?cite=1907%20c%2083%20§%2010[1907 c 83 § 10]; RRS § 6027; ]

== 70.58.270 - Data on inmates of hospitals, etc. (Effective until January 1, 2021.)
All superintendents or managers, or other persons in charge of hospitals, almshouses, lying-in or other institutions, public or private, to which persons resort for treatment of disease, confinement, or are committed by process of law, are hereby required to make a record of all the personal and statistical particulars relative to the inmates in their institutions, at the date of approval of *this act, that are required in the form of the certificate provided for by this act, as directed by the state registrar; and thereafter such record shall be by them made for all future inmates at the time of their admission. And in case of persons admitted or committed for medical treatment of contagious disease, the physician in charge shall specify, for entry in the record, the nature of the disease, and where, in his or her opinion, it was contracted. The personal particulars and information required by this section shall be obtained from the individual himself or herself, if it is practicable to do so; and when they cannot be so obtained, they shall be secured in as complete a manner as possible from the relatives, friends, or other persons acquainted with the facts.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20389[2012 c 117 § 389]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c83.pdf?cite=1907%20c%2083%20§%2016[1907 c 83 § 16]; RRS § 6033; ]

== 70.58.280 - Penalty. (Effective until January 1, 2021.)
. Every person who violates or willfully fails, neglects, or refuses to comply with any provisions of *this act is guilty of a misdemeanor and for a second offense shall be punished by a fine of not less than twenty-five dollars, and for a third and each subsequent offense shall be punished by a fine of not less than fifty dollars or more than two hundred and fifty dollars or by imprisonment for not more than ninety days, or by both fine and imprisonment.

. Every person who willfully furnishes any false information for any certificate required by *this act or who makes any false statement in any such certificate is guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20353[2003 c 53 § 353]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c180.pdf?cite=1915%20c%20180%20§%2012[1915 c 180 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c83.pdf?cite=1907%20c%2083%20§%2021[1907 c 83 § 21]; RRS § 6038; ]

== 70.58.380 - Certificates for out-of-state marriage license requirements. (Effective until January 1, 2021.)
The department shall prescribe by rule a schedule of fees for providing certificates necessary to meet marriage license requirements of other states. The fees shall be predicated on the costs of conducting premarital blood screening tests and issuing certificates.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c284.pdf?cite=1981%20c%20284%20§%201[1981 c 284 § 1]; ]

== 70.58.390 - Certificates of presumed death. (Effective until January 1, 2021.)
A county coroner, medical examiner, or the prosecuting attorney having jurisdiction may file a certificate of presumed death when the official filing the certificate determines to the best of the official's knowledge and belief that there is sufficient circumstantial evidence to indicate that a person has in fact died in the county or in waters contiguous to the county and that it is unlikely that the body will be recovered. The certificate shall recite, to the extent possible, the date, circumstances, and place of the death, and shall be the legally accepted fact of death.

In the event that the county in which the death occurred cannot be determined with certainty, the county coroner, medical examiner, or prosecuting attorney in the county in which the events occurred and in which the decedent was last known to be alive may file a certificate of presumed death under this section.

The official filing the certificate of presumed death shall file the certificate with the local registrar of the county where the death was presumed to have occurred, and thereafter all persons and parties acting in good faith may rely thereon with acquittance.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20160[2005 c 365 § 160]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c176.pdf?cite=1981%20c%20176%20§%201[1981 c 176 § 1]; ]

== 70.58.400 - Certificate of death—Presence of methicillin-resistant staphylococcus aureus (MRSA). (Effective until January 1, 2021.)
In completing a certificate of death in compliance with this chapter, a physician, physician assistant, or advanced registered nurse practitioner must note the presence of methicillin-resistant staphylococcus aureus, if it is a cause or contributing factor in the patient's death.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1123-S.SL.pdf?cite=2009%20c%20244%20§%203[2009 c 244 § 3]; ]

== 70.58.900 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521. (Effective until January 1, 2021.)
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%20153[2009 c 521 § 153]; ]

