= 70.77 - State fireworks law.
:toc:

== 70.77.111 - Intent.
The legislature declares that fireworks, when purchased and used in compliance with the laws of the state of Washington, are legal. The legislature intends that this chapter is regulatory only, and not prohibitory.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%201[1995 c 61 § 1]; ]

== 70.77.120 - Definitions—To govern chapter.
The definitions set forth in this chapter shall govern the construction of this chapter, unless the context otherwise requires.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%201[1961 c 228 § 1]; ]

== 70.77.124 - Definitions—"City."
"City" means any incorporated city or town.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%202[1995 c 61 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2642-S.SL.pdf?cite=1994%20c%20133%20§%202[1994 c 133 § 2]; ]

== 70.77.126 - Definitions—"Fireworks."
"Fireworks" means any composition or device designed to produce a visible or audible effect by combustion, deflagration, or detonation, and which meets the definition of articles pyrotechnic or consumer fireworks or display fireworks.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%204[2002 c 370 § 4]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%203[1995 c 61 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%201[1984 c 249 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%201[1982 c 230 § 1]; ]

== 70.77.131 - Definitions—"Display fireworks."
"Display fireworks" means large fireworks designed primarily to produce visible or audible effects by combustion, deflagration, or detonation and includes, but is not limited to, salutes containing more than 2 grains (130 mg) of explosive materials, aerial shells containing more than 40 grams of pyrotechnic compositions, and other display pieces which exceed the limits of explosive materials for classification as "consumer fireworks" and are classified as fireworks UN0333, UN0334, or UN0335 by the United States department of transportation at 49 C.F.R. Sec. 172.101 as of June 13, 2002, and including fused setpieces containing components which exceed 50 mg of salute powder.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%205[2002 c 370 § 5]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%204[1995 c 61 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%202[1984 c 249 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%202[1982 c 230 § 2]; ]

== 70.77.136 - Definitions—"Consumer fireworks."
"Consumer fireworks" means any small firework device designed to produce visible effects by combustion and which must comply with the construction, chemical composition, and labeling regulations of the United States consumer product safety commission, as set forth in 16 C.F.R. Parts 1500 and 1507 and including some small devices designed to produce audible effects, such as whistling devices, ground devices containing 50 mg or less of explosive materials, and aerial devices containing 130 mg or less of explosive materials and classified as fireworks UN0336 by the United States department of transportation at 49 C.F.R. Sec. 172.101 as of June 13, 2002, and not including fused setpieces containing components which together exceed 50 mg of salute powder.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%206[2002 c 370 § 6]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%205[1995 c 61 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%203[1984 c 249 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%203[1982 c 230 § 3]; ]

== 70.77.138 - Definitions—"Articles pyrotechnic."
"Articles pyrotechnic" means pyrotechnic devices for professional use similar to consumer fireworks in chemical composition and construction but not intended for consumer use which meet the weight limits for consumer fireworks but which are not labeled as such and which are classified as UN0431 or UN0432 by the United States department of transportation at 49 C.F.R. Sec. 172.101 as of June 13, 2002.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%207[2002 c 370 § 7]; ]

== 70.77.141 - Definitions—"Agricultural and wildlife fireworks."
"Agricultural and wildlife fireworks" includes fireworks devices distributed to farmers, ranchers, and growers through a wildlife management program administered by the United States department of the interior or an equivalent state or local governmental agency.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%208[2002 c 370 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%204[1982 c 230 § 4]; ]

== 70.77.146 - Definitions—"Special effects."
"Special effects" means any combination of chemical elements or chemical compounds capable of burning independently of the oxygen of the atmosphere, and designed and intended to produce an audible, visual, mechanical, or thermal effect as an integral part of a motion picture, radio, television, theatrical, or opera production, or live entertainment.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%208[1995 c 61 § 8]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2642-S.SL.pdf?cite=1994%20c%20133%20§%201[1994 c 133 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%204[1984 c 249 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%205[1982 c 230 § 5]; ]

== 70.77.160 - Definitions—"Public display of fireworks."
"Public display of fireworks" means an entertainment feature where the public is or could be admitted or allowed to view the display or discharge of display fireworks.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%209[2002 c 370 § 9]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5970-S.SL.pdf?cite=1997%20c%20182%20§%201[1997 c 182 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%206[1982 c 230 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%209[1961 c 228 § 9]; ]

== 70.77.165 - Definitions—"Fire nuisance."
"Fire nuisance" means anything or any act which increases, or may cause an increase of, the hazard or menace of fire to a greater degree than customarily recognized as normal by persons in the public service of preventing, suppressing, or extinguishing fire; or which may obstruct, delay, or hinder, or may become the cause of any obstruction, delay, or a hindrance to the prevention or extinguishment of fire.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2010[1961 c 228 § 10]; ]

== 70.77.170 - Definitions—"License."
"License" means a nontransferable formal authorization which the chief of the Washington state patrol, through the director of fire protection, is authorized to issue under this chapter to allow a person to engage in the act specifically designated therein.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2010[2002 c 370 § 10]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2044[1995 c 369 § 44]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2099[1986 c 266 § 99]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%207[1982 c 230 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2011[1961 c 228 § 11]; ]

== 70.77.175 - Definitions—"Licensee."
"Licensee" means any person issued a fireworks license in conformance with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2011[2002 c 370 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2012[1961 c 228 § 12]; ]

== 70.77.177 - Definitions—"Local fire official."
"Local fire official" means the chief of a local fire department or a chief fire protection officer or such other person as may be designated by the governing body of a city or county to act as a local fire official under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2642-S.SL.pdf?cite=1994%20c%20133%20§%203[1994 c 133 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%206[1984 c 249 § 6]; ]

== 70.77.180 - Definitions—"Permit."
"Permit" means the official authorization granted by a city or county for the purpose of establishing and maintaining a place within the jurisdiction of the city or county where fireworks are manufactured, constructed, produced, packaged, stored, sold, or exchanged and the official authorization granted by a city or county for a public display of fireworks.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2012[2002 c 370 § 12]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%209[1995 c 61 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%205[1984 c 249 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%208[1982 c 230 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2013[1961 c 228 § 13]; ]

== 70.77.182 - Definitions—"Permittee."
"Permittee" means any person issued a fireworks permit in conformance with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2013[2002 c 370 § 13]; ]

== 70.77.190 - Definitions—"Person."
"Person" includes any individual, firm, partnership, joint venture, association, concern, corporation, estate, trust, business trust, receiver, syndicate, or any other group or combination acting as a unit.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2015[1961 c 228 § 15]; ]

== 70.77.200 - Definitions—"Importer."
"Importer" includes any person who for any purpose other than personal use:

. Brings fireworks into this state or causes fireworks to be brought into this state;

. Procures the delivery or receives shipments of any fireworks into this state; or

. Buys or contracts to buy fireworks for shipment into this state.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%2010[1995 c 61 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2017[1961 c 228 § 17]; ]

== 70.77.205 - Definitions—"Manufacturer."
"Manufacturer" includes any person who manufactures, makes, constructs, fabricates, or produces any fireworks article or device but does not include persons who assemble or fabricate sets or mechanical pieces in public displays of fireworks or persons who assemble consumer fireworks items or sets or packages containing consumer fireworks items.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2014[2002 c 370 § 14]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%2011[1995 c 61 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2018[1961 c 228 § 18]; ]

== 70.77.210 - Definitions—"Wholesaler."
"Wholesaler" includes any person who sells fireworks to a retailer or any other person for resale and any person who sells display fireworks to public display licensees.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2015[2002 c 370 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%209[1982 c 230 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2019[1961 c 228 § 19]; ]

== 70.77.215 - Definitions—"Retailer."
"Retailer" includes any person who, at a fixed location or place of business, offers for sale, sells, or exchanges for consideration consumer fireworks to a consumer or user.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2016[2002 c 370 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2010[1982 c 230 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2020[1961 c 228 § 20]; ]

== 70.77.230 - Definitions—"Pyrotechnic operator."
"Pyrotechnic operator" includes any individual who by experience and training has demonstrated the required skill and ability for safely setting up and discharging display fireworks.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2017[2002 c 370 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2011[1982 c 230 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2023[1961 c 228 § 23]; ]

== 70.77.236 - Definitions—"New fireworks item."
. "New fireworks item" means any fireworks initially classified or reclassified as articles pyrotechnic, display fireworks, or consumer fireworks by the United States department of transportation after June 13, 2002, and which comply with the construction, chemical composition, and labeling regulations of the United States consumer products safety commission, 16 C.F.R., Parts 1500 and 1507.

. The chief of the Washington state patrol, through the director of fire protection, shall classify any new fireworks item in the same manner as the item is classified by the United States department of transportation and the United States consumer product safety commission. The chief of the Washington state patrol, through the director of fire protection, may determine, stating reasonable grounds, that the item should not be so classified.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2018[2002 c 370 § 18]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5970-S.SL.pdf?cite=1997%20c%20182%20§%204[1997 c 182 § 4]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%206[1995 c 61 § 6]; ]

== 70.77.241 - Definitions—"Permanent storage"—"Temporary storage."
. "Permanent storage" means storage of display fireworks at any time and/or storage of consumer fireworks at any time other than the periods allowed under RCW 70.77.420(2) and 70.77.425 and which shall be in compliance with the requirements of chapter 70.74 RCW.

. "Temporary storage" means the storage of consumer fireworks during the periods allowed under RCW 70.77.420(2) and 70.77.425.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2034[2002 c 370 § 34]; ]

== 70.77.250 - Chief of the Washington state patrol to enforce and administer—Powers and duties.
. The chief of the Washington state patrol, through the director of fire protection, shall enforce and administer this chapter.

. The chief of the Washington state patrol, through the director of fire protection, shall appoint such deputies and employees as may be necessary and required to carry out the provisions of this chapter.

. The chief of the Washington state patrol, through the director of fire protection, shall adopt those rules relating to fireworks as are necessary for the implementation of this chapter.

. The chief of the Washington state patrol, through the director of fire protection, shall adopt those rules as are necessary to ensure statewide minimum standards for the enforcement of this chapter. Counties and cities shall comply with these state rules. Any ordinances adopted by a county or city that are more restrictive than state law shall have an effective date no sooner than one year after their adoption.

. The chief of the Washington state patrol, through the director of fire protection, may exercise the necessary police powers to enforce the criminal provisions of this chapter. This grant of police powers does not prevent any other state agency and city, county, or local government agency having general law enforcement powers from enforcing this chapter within the jurisdiction of the agency and city, county, or local government.

. The chief of the Washington state patrol, through the director of fire protection, shall adopt rules necessary to enforce the civil penalty provisions for the violations of this chapter. A civil penalty under this subsection may not exceed one thousand dollars per day for each violation and is subject to the procedural requirements under RCW 70.77.252.

. The chief of the Washington state patrol, through the director of fire protection, may investigate or cause to be investigated all fires resulting, or suspected of resulting, from the use of fireworks.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2019[2002 c 370 § 19]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5970-S.SL.pdf?cite=1997%20c%20182%20§%205[1997 c 182 § 5]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2045[1995 c 369 § 45]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%2012[1995 c 61 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%20100[1986 c 266 § 100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%207[1984 c 249 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2012[1982 c 230 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2027[1961 c 228 § 27]; ]

== 70.77.252 - Civil penalty—Notice—Remission, mitigation, review.
. The penalty provided for in RCW 70.77.250(6) shall be imposed by a notice in writing to the person against whom the civil fine is assessed and shall describe the violation with reasonable particularity. The notice shall be personally served in the manner of service of a summons in a civil action or in a manner which shows proof of receipt. Any penalty imposed by RCW 70.77.250(6) shall become due and payable twenty-eight days after receipt of notice unless application for remission or mitigation is made as provided in subsection (2) of this section or unless application for an adjudicative proceeding is filed as provided in subsection (3) of this section.

. Within fourteen days after the notice is received, the person incurring the penalty may apply in writing to the chief of the Washington state patrol, through the director of fire protection, for the remission or mitigation of the penalty. Upon receipt of the application, the chief of the Washington state patrol, through the director of fire protection, may remit or mitigate the penalty upon whatever terms the chief of the Washington state patrol, through the director of fire protection, deems proper, giving consideration to the degree of hazard associated with the violation. The chief of the Washington state patrol, through the director of fire protection, may only grant a remission or mitigation that it deems to be in the best interests of carrying out the purposes of this chapter. The chief of the Washington state patrol, through the director of fire protection, may ascertain the facts regarding all such applications in a manner it deems proper. When an application for remission or mitigation is made, any penalty incurred under RCW 70.77.250(6) becomes due and payable twenty-eight days after receipt of the notice setting forth the disposition of the application, unless an application for an adjudicative proceeding to contest the disposition is filed as provided in subsection (3) of this section.

. Within twenty-eight days after notice is received, the person incurring the penalty may file an application for an adjudicative proceeding and may pursue subsequent review as provided in chapter 34.05 RCW and applicable rules of the chief of the Washington state patrol, through the director of fire protection.

. Any penalty imposed by final order following an adjudicative proceeding becomes due and payable upon service of the final order.

. The attorney general may bring an action in the name of the chief of the Washington state patrol, through the director of fire protection, in the superior court of Thurston county or of any county in which the violator may do business to collect any penalty imposed under this chapter.

. All penalties imposed under this section shall be paid to the state treasury and credited to the fire services trust fund and used as follows: At least fifty percent is for a statewide public education campaign developed by the chief of the Washington state patrol, through the director of fire protection, and the licensed fireworks industry emphasizing the safe and responsible use of legal fireworks; and the remainder is for statewide efforts to enforce this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2020[2002 c 370 § 20]; ]

== 70.77.255 - Acts prohibited without appropriate licenses and permits—Minimum age for license or permit—Activities permitted without license or permit.
. Except as otherwise provided in this chapter, no person, without appropriate state licenses and city or county permits as required by this chapter may:

.. Manufacture, import, possess, or sell any fireworks at wholesale or retail for any use;

.. Make a public display of fireworks;

.. Transport fireworks, except as a licensee or as a public carrier delivering to a licensee; or

.. Knowingly manufacture, import, transport, store, sell, or possess with intent to sell, as fireworks, explosives, as defined under RCW 70.74.010, that are not fireworks, as defined under this chapter.

. Except as authorized by a license and permit under subsection (1)(b) of this section or as provided in RCW 70.77.311, no person may discharge display fireworks at any place.

. No person less than eighteen years of age may apply for or receive a license or permit under this chapter.

. No license or permit is required for the possession or use of consumer fireworks lawfully purchased at retail.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2021[2002 c 370 § 21]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5970-S.SL.pdf?cite=1997%20c%20182%20§%206[1997 c 182 § 6]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%2013[1995 c 61 § 13]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2642-S.SL.pdf?cite=1994%20c%20133%20§%204[1994 c 133 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2010[1984 c 249 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2014[1982 c 230 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2028[1961 c 228 § 28]; ]

== 70.77.260 - Application for permit.
. Any person desiring to do any act mentioned in RCW 70.77.255(1) (a) or (c) shall apply in writing to a local fire official for a permit.

. Any person desiring to put on a public display of fireworks under RCW 70.77.255(1)(b) shall apply in writing to a local fire official for a permit. Application shall be made at least ten days in advance of the proposed display.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2011[1984 c 249 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2015[1982 c 230 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2029[1961 c 228 § 29]; ]

== 70.77.265 - Investigation, report on permit application.
The local fire official receiving an application for a permit under RCW 70.77.260(1) shall investigate the application and submit a report of findings and a recommendation for or against the issuance of the permit, together with reasons, to the governing body of the city or county.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2642-S.SL.pdf?cite=1994%20c%20133%20§%205[1994 c 133 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2012[1984 c 249 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2030[1961 c 228 § 30]; ]

== 70.77.270 - Governing body to grant permits—Statewide standards—Liability insurance.
. The governing body of a city or county, or a designee, shall grant an application for a permit under RCW 70.77.260(1) if the application meets the standards under this chapter, and the applicable ordinances of the city or county. The permit shall be granted by June 10, or no less than thirty days after receipt of an application whichever date occurs first, for sales commencing on June 28 and on December 27; or by December 10, or no less than thirty days after receipt of an application whichever date occurs first, for sales commencing only on December 27.

. The chief of the Washington state patrol, through the director of fire protection, shall prescribe uniform, statewide standards for retail fireworks stands including, but not limited to, the location of the stands, setback requirements and siting of the stands, types of buildings and construction material that may be used for the stands, use of the stands and areas around the stands, cleanup of the area around the stands, transportation of fireworks to and from the stands, and temporary storage of fireworks associated with the retail fireworks stands. All cities and counties which allow retail fireworks sales shall comply with these standards.

. No retail fireworks permit may be issued to any applicant unless the retail fireworks stand is covered by a liability insurance policy with coverage of not less than fifty thousand dollars and five hundred thousand dollars for bodily injury liability for each person and occurrence, respectively, and not less than fifty thousand dollars for property damage liability for each occurrence, unless such insurance is not readily available from at least three approved insurance companies. If insurance in this amount is not offered, each fireworks permit shall be covered by a liability insurance policy in the maximum amount offered by at least three different approved insurance companies.

No wholesaler may knowingly sell or supply fireworks to any retail fireworks licensee unless the wholesaler determines that the retail fireworks licensee is covered by liability insurance in the same, or greater, amount as provided in this subsection.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2022[2002 c 370 § 22]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5970-S.SL.pdf?cite=1997%20c%20182%20§%208[1997 c 182 § 8]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%2014[1995 c 61 § 14]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2642-S.SL.pdf?cite=1994%20c%20133%20§%206[1994 c 133 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2013[1984 c 249 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2031[1961 c 228 § 31]; ]

== 70.77.280 - Public display permit—Investigation—Governing body to grant—Conditions.
The local fire official receiving an application for a permit under RCW 70.77.260(2) for a public display of fireworks shall investigate whether the character and location of the display as proposed would be hazardous to property or dangerous to any person. Based on the investigation, the official shall submit a report of findings and a recommendation for or against the issuance of the permit, together with reasons, to the governing body of the city or county. The governing body shall grant the application if it meets the requirements of this chapter and the ordinance of the city or county.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%2015[1995 c 61 § 15]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2642-S.SL.pdf?cite=1994%20c%20133%20§%207[1994 c 133 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2014[1984 c 249 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2033[1961 c 228 § 33]; ]

== 70.77.285 - Public display permit—Bond or insurance for liability.
Except as provided in RCW 70.77.355, the applicant for a permit under RCW 70.77.260(2) for a public display of fireworks shall include with the application evidence of a bond issued by an authorized surety company. The bond shall be in the amount required by RCW 70.77.295 and shall be conditioned upon the applicant's payment of all damages to persons or property resulting from or caused by such public display of fireworks, or any negligence on the part of the applicant or its agents, servants, employees, or subcontractors in the presentation of the display. Instead of a bond, the applicant may include a certificate of insurance evidencing the carrying of appropriate liability insurance in the amount required by RCW 70.77.295 for the benefit of the person named therein as assured, as evidence of ability to respond in damages. The local fire official receiving the application shall approve the bond or insurance if it meets the requirements of this section.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%2016[1995 c 61 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2015[1984 c 249 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2016[1982 c 230 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2034[1961 c 228 § 34]; ]

== 70.77.290 - Public display permit—Granted for exclusive purpose.
If a permit under RCW 70.77.260(2) for the public display of fireworks is granted, the sale, possession and use of fireworks for the public display is lawful for that purpose only.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5970-S.SL.pdf?cite=1997%20c%20182%20§%209[1997 c 182 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2016[1984 c 249 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2035[1961 c 228 § 35]; ]

== 70.77.295 - Public display permit—Amount of bond or insurance.
In the case of an application for a permit under RCW 70.77.260(2) for the public display of fireworks, the amount of the surety bond or certificate of insurance required under RCW 70.77.285 shall be not less than fifty thousand dollars and one million dollars for bodily injury liability for each person and event, respectively, and not less than twenty-five thousand dollars for property damage liability for each event.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2017[1984 c 249 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2017[1982 c 230 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2036[1961 c 228 § 36]; ]

== 70.77.305 - Chief of the Washington state patrol to issue licenses—Registration of in-state agents.
The chief of the Washington state patrol, through the director of fire protection, has the power to issue licenses for the manufacture, importation, sale, and use of all fireworks in this state, except as provided in RCW 70.77.311 and 70.77.395. A person may be licensed as a manufacturer, importer, or wholesaler under this chapter only if the person has a designated agent in this state who is registered with the chief of the Washington state patrol, through the director of fire protection.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2023[2002 c 370 § 23]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2046[1995 c 369 § 46]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%20101[1986 c 266 § 101]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2018[1984 c 249 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2018[1982 c 230 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2038[1961 c 228 § 38]; ]

== 70.77.311 - Exemptions from licensing—Purchase of certain agricultural and wildlife fireworks by government agencies—Purchase of consumer fireworks by religious or private organizations.
. No license is required for the purchase of agricultural and wildlife fireworks by government agencies if:

.. The agricultural and wildlife fireworks are used for wildlife control or are distributed to farmers, ranchers, or growers through a wildlife management program administered by the United States department of the interior or an equivalent state or local governmental agency;

.. The distribution is in response to a written application describing the wildlife management problem that requires use of the devices;

.. It is of no greater quantity than necessary to control the described problem; and

.. It is limited to situations where other means of control are unavailable or inadequate.

. No license is required for religious organizations or private organizations or persons to purchase or use consumer fireworks and such audible ground devices as firecrackers, salutes, and chasers if:

.. Purchased from a licensed manufacturer, importer, or wholesaler;

.. For use on prescribed dates and locations;

.. For religious or specific purposes; and

.. A permit is obtained from the local fire official. No fee may be charged for this permit.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2024[2002 c 370 § 24]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%2017[1995 c 61 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2019[1984 c 249 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2019[1982 c 230 § 19]; ]

== 70.77.315 - Application for license.
Any person who desires to engage in the manufacture, importation, sale, or use of fireworks, except use as provided in RCW 70.77.255(4), 70.77.311, and 70.77.395, shall make a written application to the chief of the Washington state patrol, through the director of fire protection, on forms provided by him or her. Such application shall be accompanied by the annual license fee as prescribed in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2025[2002 c 370 § 25]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5970-S.SL.pdf?cite=1997%20c%20182%20§%2010[1997 c 182 § 10]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2047[1995 c 369 § 47]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%2018[1995 c 61 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%20102[1986 c 266 § 102]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2020[1982 c 230 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2040[1961 c 228 § 40]; ]

== 70.77.320 - Application for license to be signed.
The application for a license shall be signed by the applicant. If application is made by a partnership, it shall be signed by each partner of the partnership, and if application is made by a corporation, it shall be signed by an officer of the corporation and bear the seal of the corporation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2041[1961 c 228 § 41]; ]

== 70.77.325 - Annual application for a license—Dates.
. An application for a license shall be made annually by every person holding an existing license who wishes to continue the activity requiring the license during an additional year. The application shall be accompanied by the annual license fees as prescribed in RCW 70.77.343 and 70.77.340.

. A person applying for an annual license as a retailer under this chapter shall file an application no later than May 1 for annual sales commencing on June 28 and on December 27, or no later than November 1 for sales commencing only on December 27. The chief of the Washington state patrol, through the director of fire protection, shall grant or deny the license within fifteen days of receipt of the application.

. A person applying for an annual license as a manufacturer, importer, or wholesaler under this chapter shall file an application by January 31 of the current year. The chief of the Washington state patrol, through the director of fire protection, shall grant or deny the license within ninety days of receipt of the application.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5970-S.SL.pdf?cite=1997%20c%20182%20§%2011[1997 c 182 § 11]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2642-S.SL.pdf?cite=1994%20c%20133%20§%208[1994 c 133 § 8]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1852-S.SL.pdf?cite=1991%20c%20135%20§%204[1991 c 135 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%20103[1986 c 266 § 103]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2020[1984 c 249 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2021[1982 c 230 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2042[1961 c 228 § 42]; ]

== 70.77.330 - License to engage in particular act to be issued if not contrary to public safety or welfare—Transportation of fireworks authorized.
If the chief of the Washington state patrol, through the director of fire protection, finds that the granting of such license is not contrary to public safety or welfare, he or she shall issue a license authorizing the applicant to engage in the particular act or acts upon the payment of the license fee specified in this chapter. Licensees may transport the class of fireworks for which they hold a valid license.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2026[2002 c 370 § 26]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2048[1995 c 369 § 48]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%20104[1986 c 266 § 104]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2022[1982 c 230 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2043[1961 c 228 § 43]; ]

== 70.77.335 - License authorizes activities of sellers, authorized representatives, employees.
The authorization to engage in the particular act or acts conferred by a license to a person shall extend to sellers, authorized representatives, and other employees of such person.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2027[2002 c 370 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2023[1982 c 230 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2044[1961 c 228 § 44]; ]

== 70.77.340 - Annual license fees.
The original and annual license fee shall be as follows:

Manufacturer . . . .$500.00Importer . . . .100.00Wholesaler . . . .1,000.00Retailer (for each separate retail  outlet) . . . .10.00Public display for display fireworks . . . .10.00Pyrotechnic operator for display  fireworks . . . .5.00

Manufacturer . . . .$

500.00

Importer . . . .

100.00

Wholesaler . . . .

1,000.00

Retailer (for each separate retail

  outlet) . . . .

10.00

Public display for display fireworks . . . .

10.00

Pyrotechnic operator for display

  fireworks . . . .

5.00

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2028[2002 c 370 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2024[1982 c 230 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2045[1961 c 228 § 45]; ]

== 70.77.343 - License fees—Additional.
. License fees, in addition to the fees in RCW 70.77.340, shall be charged as follows:

Manufacturer . . . .$1,500.00Importer . . . .900.00Wholesaler . . . .1,000.00Retailer (for each separate outlet) . . . .30.00Public display for display fireworks . . . .40.00Pyrotechnic operator for display  fireworks . . . .5.00

Manufacturer . . . .$

1,500.00

Importer . . . .

900.00

Wholesaler . . . .

1,000.00

Retailer (for each separate outlet) . . . .

30.00

Public display for display fireworks . . . .

40.00

Pyrotechnic operator for display

  fireworks . . . .

5.00

. All receipts from the license fees in this section shall be placed in the fire services trust fund and at least seventy-five percent of these receipts shall be used to fund a statewide public education campaign developed by the chief of the Washington state patrol and the licensed fireworks industry emphasizing the safe and responsible use of legal fireworks and the remaining receipts shall be used to fund statewide enforcement efforts against the sale and use of fireworks that are illegal under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2029[2002 c 370 § 29]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5970-S.SL.pdf?cite=1997%20c%20182%20§%2012[1997 c 182 § 12]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%2019[1995 c 61 § 19]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1852-S.SL.pdf?cite=1991%20c%20135%20§%206[1991 c 135 § 6]; ]

== 70.77.345 - Duration of licenses and retail fireworks sales permits.
Every license and every retail fireworks sales permit issued shall be for the period from January 1st of the year for which the application is made through January 31st of the subsequent year, or the remaining portion thereof.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5970-S.SL.pdf?cite=1997%20c%20182%20§%2013[1997 c 182 § 13]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%2020[1995 c 61 § 20]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1852-S.SL.pdf?cite=1991%20c%20135%20§%205[1991 c 135 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2025[1982 c 230 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2046[1961 c 228 § 46]; ]

== 70.77.355 - General license for public display—Surety bond or insurance—Filing of license certificate with local permit application.
. Any adult person may secure a general license from the chief of the Washington state patrol, through the director of fire protection, for the public display of fireworks within the state of Washington. A general license is subject to the provisions of this chapter relative to the securing of local permits for the public display of fireworks in any city or county, except that in lieu of filing the bond or certificate of public liability insurance with the appropriate local official under RCW 70.77.260 as required in RCW 70.77.285, the same bond or certificate shall be filed with the chief of the Washington state patrol, through the director of fire protection. The bond or certificate of insurance for a general license in addition shall provide that: (a) The insurer will not cancel the insured's coverage without fifteen days prior written notice to the chief of the Washington state patrol, through the director of fire protection; (b) the duly licensed pyrotechnic operator required by law to supervise and discharge the public display, acting either as an employee of the insured or as an independent contractor and the state of Washington, its officers, agents, employees, and servants are included as additional insureds, but only insofar as any operations under contract are concerned; and (c) the state is not responsible for any premium or assessments on the policy.

. The chief of the Washington state patrol, through the director of fire protection, may issue such general licenses. The holder of a general license shall file a certificate from the chief of the Washington state patrol, through the director of fire protection, evidencing the license with any application for a local permit for the public display of fireworks under RCW 70.77.260.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5970-S.SL.pdf?cite=1997%20c%20182%20§%2014[1997 c 182 § 14]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2642-S.SL.pdf?cite=1994%20c%20133%20§%209[1994 c 133 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%20105[1986 c 266 § 105]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2021[1984 c 249 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2026[1982 c 230 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2048[1961 c 228 § 48]; ]

== 70.77.360 - Denial of license for material misrepresentation or if contrary to public safety or welfare.
If the chief of the Washington state patrol, through the director of fire protection, finds that an application for any license under this chapter contains a material misrepresentation or that the granting of any license would be contrary to the public safety or welfare, the chief of the Washington state patrol, through the director of fire protection, may deny the application for the license.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2049[1995 c 369 § 49]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%20106[1986 c 266 § 106]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2022[1984 c 249 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2027[1982 c 230 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2049[1961 c 228 § 49]; ]

== 70.77.365 - Denial of license for failure to meet qualifications or conditions.
A written report by the chief of the Washington state patrol, through the director of fire protection, or a local fire official, or any of their authorized representatives, disclosing that the applicant for a license, or the premises for which a license is to apply, do not meet the qualifications or conditions for a license constitutes grounds for the denial by the chief of the Washington state patrol, through the director of fire protection, of any application for a license.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2050[1995 c 369 § 50]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%20107[1986 c 266 § 107]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2023[1984 c 249 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2028[1982 c 230 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2050[1961 c 228 § 50]; ]

== 70.77.370 - Hearing on denial of license.
Any applicant who has been denied a license for reasons other than making application after the date set forth in RCW 70.77.325 is entitled to a hearing in accordance with the provisions of chapter 34.05 RCW, the Administrative Procedure Act.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2642-S.SL.pdf?cite=1994%20c%20133%20§%2010[1994 c 133 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%20129[1989 c 175 § 129]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2029[1982 c 230 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2051[1961 c 228 § 51]; ]

== 70.77.375 - Revocation of license.
The chief of the Washington state patrol, through the director of fire protection, upon reasonable opportunity to be heard, may revoke any license issued pursuant to this chapter, if he or she finds that:

. The licensee has violated any provisions of this chapter or any rule made by the chief of the Washington state patrol, through the director of fire protection, under and with the authority of this chapter;

. The licensee has created or caused a fire nuisance;

. Any licensee has failed or refused to file any required reports; or

. Any fact or condition exists which, if it had existed at the time of the original application for such license, reasonably would have warranted the chief of the Washington state patrol, through the director of fire protection, in refusing originally to issue such license.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5970-S.SL.pdf?cite=1997%20c%20182%20§%2016[1997 c 182 § 16]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2051[1995 c 369 § 51]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%2021[1995 c 61 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%20108[1986 c 266 § 108]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2030[1982 c 230 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2052[1961 c 228 § 52]; ]

== 70.77.381 - Wholesalers and retailers—Liability insurance requirements.
. Every wholesaler shall carry liability insurance for each wholesale and retail fireworks outlet it operates in the amount of not less than fifty thousand dollars and five hundred thousand dollars for bodily injury liability for each person and occurrence, respectively, and not less than fifty thousand dollars for property damage liability for each occurrence, unless such insurance is not available from at least three approved insurance companies. If insurance in this amount is not offered, each wholesale and retail outlet shall be covered by a liability insurance policy in the maximum amount offered by at least three different approved insurance companies.

. No wholesaler may knowingly sell or supply fireworks to any retail licensee unless the wholesaler determines that the retail licensee carries liability insurance in the same, or greater, amount as provided in subsection (1) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2030[2002 c 370 § 30]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%2027[1995 c 61 § 27]; ]

== 70.77.386 - Retailers—Purchase from licensed wholesalers.
Retail fireworks licensees shall purchase all fireworks from wholesalers possessing a valid wholesale license issued by the state of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%2028[1995 c 61 § 28]; ]

== 70.77.395 - Dates and times consumer fireworks may be sold or discharged—Local governments may limit, prohibit sale or discharge of fireworks.
. It is legal to sell and purchase consumer fireworks within this state from twelve o'clock noon to eleven o'clock p.m. on the twenty-eighth of June, from nine o'clock a.m. to eleven o'clock p.m. on each day from the twenty-ninth of June through the fourth of July, from nine o'clock a.m. to nine o'clock p.m. on the fifth of July, from twelve o'clock noon to eleven o'clock p.m. on each day from the twenty-seventh of December through the thirty-first of December of each year, and as provided in RCW 70.77.311.

. Consumer fireworks may be used or discharged each day between the hours of twelve o'clock noon and eleven o'clock p.m. on the twenty-eighth of June and between the hours of nine o'clock a.m. and eleven o'clock p.m. on the twenty-ninth of June to the third of July, and on July 4th between the hours of nine o'clock a.m. and twelve o'clock midnight, and between the hours of nine o'clock a.m. and eleven o'clock p.m. on July 5th, and from six o'clock p.m. on December 31st until one o'clock a.m. on January 1st of the subsequent year, and as provided in RCW 70.77.311.

. A city or county may enact an ordinance within sixty days of June 13, 2002, to limit or prohibit the sale, purchase, possession, or use of consumer fireworks on December 27, 2002, through December 31, 2002, and thereafter as provided in RCW 70.77.250(4).

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2031[2002 c 370 § 31]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%2022[1995 c 61 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2024[1984 c 249 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2031[1982 c 230 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2056[1961 c 228 § 56]; ]

== 70.77.401 - Sale of certain fireworks prohibited.
No fireworks may be sold or offered for sale to the public as consumer fireworks which are classified as sky rockets, or missile-type rockets, firecrackers, salutes, or chasers as defined by the United States department of transportation and the federal consumer products safety commission except as provided in RCW 70.77.311.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2032[2002 c 370 § 32]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%207[1995 c 61 § 7]; ]

== 70.77.405 - Authorized sales of toy caps, tricks, and novelties.
Toy paper caps containing not more than twenty-five hundredths grain of explosive compound for each cap and trick or novelty devices not classified as consumer fireworks may be sold at all times unless prohibited by local ordinance.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2033[2002 c 370 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2032[1982 c 230 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2058[1961 c 228 § 58]; ]

== 70.77.410 - Public displays not to be hazardous.
All public displays of fireworks shall be of such a character and so located, discharged, or fired as not to be hazardous or dangerous to persons or property.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2059[1961 c 228 § 59]; ]

== 70.77.415 - Supervision of public displays.
Every public display of fireworks shall be handled or supervised by a pyrotechnic operator licensed by the chief of the Washington state patrol, through the director of fire protection, under RCW 70.77.255.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2052[1995 c 369 § 52]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%20109[1986 c 266 § 109]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2025[1984 c 249 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2033[1982 c 230 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2060[1961 c 228 § 60]; ]

== 70.77.420 - Permanent storage permit required—Application—Investigation—Grant or denial—Conditions.
. It is unlawful for any person to store permanently fireworks of any class without a permit for such permanent storage from the city or county in which the storage is to be made. A person proposing to store permanently fireworks shall apply in writing to a city or county at least ten days prior to the date of the proposed permanent storage. The city or county receiving the application for a permanent storage permit shall investigate whether the character and location of the permanent storage as proposed meets the requirements of the zoning, building, and fire codes or constitutes a hazard to property or is dangerous to any person. Based on the investigation, the city or county may grant or deny the application. The city or county may place reasonable conditions on any permit granted.

. For the purposes of this section the temporary storing or keeping of consumer fireworks when in conjunction with a valid retail sales license and permit shall comply with RCW 70.77.425 and the standards adopted under RCW 70.77.270(2) and not this section.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2035[2002 c 370 § 35]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5970-S.SL.pdf?cite=1997%20c%20182%20§%2018[1997 c 182 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2026[1984 c 249 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2034[1982 c 230 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2061[1961 c 228 § 61]; ]

== 70.77.425 - Approved permanent storage facilities required.
It is unlawful for any person to store permanently stocks of fireworks remaining unsold after the lawful period of sale as provided in the person's permit except in such places of permanent storage as the city or county issuing the permit approves. Unsold stocks of consumer fireworks remaining after the authorized retail sales period from nine o'clock a.m. on June 28th to twelve o'clock noon on July 5th shall be returned on or before July 31st of the same year, or remaining after the authorized retail sales period from twelve o'clock noon on December 27th to eleven o'clock p.m. on December 31st shall be returned on or before January 10th of the subsequent year, to the approved permanent storage facilities of a licensed fireworks wholesaler or to a magazine or permanent storage place approved by a local fire official.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2036[2002 c 370 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2027[1984 c 249 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2035[1982 c 230 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2062[1961 c 228 § 62]; ]

== 70.77.430 - Sale of stock after revocation or expiration of license.
Notwithstanding RCW 70.77.255, following the revocation or expiration of a license, a licensee in lawful possession of a lawfully acquired stock of fireworks may sell such fireworks, but only under supervision of the chief of the Washington state patrol, through the director of fire protection. Any sale under this section shall be solely to persons who are authorized to buy, possess, sell, or use such fireworks.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2053[1995 c 369 § 53]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%20110[1986 c 266 § 110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2028[1984 c 249 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2036[1982 c 230 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2063[1961 c 228 § 63]; ]

== 70.77.435 - Seizure of fireworks.
Any fireworks which are illegally sold, offered for sale, used, discharged, possessed, or transported in violation of the provisions of this chapter or the rules or regulations of the chief of the Washington state patrol, through the director of fire protection, are subject to seizure by the chief of the Washington state patrol, through the director of fire protection, or his or her deputy, or by state agencies or local governments having general law enforcement authority.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2037[2002 c 370 § 37]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5970-S.SL.pdf?cite=1997%20c%20182%20§%2020[1997 c 182 § 20]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%2023[1995 c 61 § 23]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2642-S.SL.pdf?cite=1994%20c%20133%20§%2011[1994 c 133 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%20111[1986 c 266 § 111]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2037[1982 c 230 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2064[1961 c 228 § 64]; ]

== 70.77.440 - Seizure of fireworks—Proceedings for forfeiture—Disposal of confiscated fireworks.
. In the event of seizure under RCW 70.77.435, proceedings for forfeiture shall be deemed commenced by the seizure. The chief of the Washington state patrol or a designee, through the director of fire protection or the agency conducting the seizure, under whose authority the seizure was made shall cause notice to be served within fifteen days following the seizure on the owner of the fireworks seized and the person in charge thereof and any person having any known right or interest therein, of the seizure and intended forfeiture of the seized property. The notice may be served by any method authorized by law or court rule including but not limited to service by certified mail with return receipt requested. Service by mail shall be deemed complete upon mailing within the fifteen-day period following the seizure.

. If no person notifies the chief of the Washington state patrol, through the director of fire protection or the agency conducting the seizure, in writing of the person's claim of lawful ownership or right to lawful possession of seized fireworks within thirty days of the seizure, the seized fireworks shall be deemed forfeited.

. If any person notifies the chief of the Washington state patrol, through the director of fire protection or the agency conducting the seizure, in writing of the person's claim of lawful ownership or possession of the fireworks within thirty days of the seizure, the person or persons shall be afforded a reasonable opportunity to be heard as to the claim or right. The hearing shall be before an administrative law judge appointed under chapter 34.12 RCW, except that any person asserting a claim or right may remove the matter to a court of competent jurisdiction if the aggregate value of the seized fireworks is more than five hundred dollars. The hearing before an administrative law judge and any appeal therefrom shall be under Title 34 RCW. In a court hearing between two or more claimants to the article or articles involved, the prevailing party shall be entitled to a judgment for costs and reasonable attorneys' fees. The burden of producing evidence shall be upon the person claiming to have the lawful right to possession of the seized fireworks. The chief of the Washington state patrol, through the director of fire protection or the agency conducting the seizure, shall promptly return the fireworks to the claimant upon a determination by the administrative law judge or court that the claimant is lawfully entitled to possession of the fireworks.

. When fireworks are forfeited under this chapter the chief of the Washington state patrol, through the director of fire protection or the agency conducting the seizure, may:

.. Dispose of the fireworks by summary destruction at any time subsequent to thirty days from such seizure or ten days from the final termination of proceedings under this section, whichever is later; or

.. Sell the forfeited fireworks and chemicals used to make fireworks, that are legal for use and possession under this chapter, to wholesalers or manufacturers, authorized to possess and use such fireworks or chemicals under a license issued by the chief of the Washington state patrol, through the director of fire protection. Sale shall be by public auction after publishing a notice of the date, place, and time of the auction in a newspaper of general circulation in the county in which the auction is to be held, at least three days before the date of the auction. The proceeds of the sale of the seized fireworks under this section may be retained by the agency conducting the seizure and used to offset the costs of seizure and/or storage costs of the seized fireworks. The remaining proceeds, if any, shall be deposited in the fire services trust fund and shall be used as follows: At least fifty percent is for a statewide public education campaign developed by the chief of the Washington state patrol, through the director of fire protection, and the licensed fireworks industry emphasizing the safe and responsible use of legal fireworks; and the remainder is for statewide efforts to enforce this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2038[2002 c 370 § 38]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5970-S.SL.pdf?cite=1997%20c%20182%20§%2021[1997 c 182 § 21]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%2024[1995 c 61 § 24]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2642-S.SL.pdf?cite=1994%20c%20133%20§%2012[1994 c 133 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%20112[1986 c 266 § 112]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2029[1984 c 249 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2065[1961 c 228 § 65]; ]

== 70.77.450 - Examination, inspection of books and premises.
The chief of the Washington state patrol, through the director of fire protection, may make an examination of the books and records of any licensee, or other person relative to fireworks, and may visit and inspect the premises of any licensee he or she may deem at any time necessary for the purpose of enforcing the provisions of this chapter. The licensee, owner, lessee, manager, or operator of any such building or premises shall permit the chief of the Washington state patrol, through the director of fire protection, his or her deputies or salaried assistants, the local fire official, and their authorized representatives to enter and inspect the premises at the time and for the purpose stated in this section.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20395[2012 c 117 § 395]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5970-S.SL.pdf?cite=1997%20c%20182%20§%2022[1997 c 182 § 22]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2642-S.SL.pdf?cite=1994%20c%20133%20§%2013[1994 c 133 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%20113[1986 c 266 § 113]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2067[1961 c 228 § 67]; ]

== 70.77.455 - Licensees to maintain and make available complete records—Exemption from public records act.
. All licensees shall maintain and make available to the chief of the Washington state patrol, through the director of fire protection, full and complete records showing all production, imports, exports, purchases, and sales of fireworks items by class.

. All records obtained and all reports produced, as required by this chapter, are not subject to disclosure through the public records act under chapter 42.56 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20337[2005 c 274 § 337]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5970-S.SL.pdf?cite=1997%20c%20182%20§%2023[1997 c 182 § 23]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2054[1995 c 369 § 54]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%2025[1995 c 61 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%20114[1986 c 266 § 114]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2038[1982 c 230 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2068[1961 c 228 § 68]; ]

== 70.77.460 - Reports, payments deemed made when filed or paid or date mailed.
When reports on fireworks transactions or the payments of license fees or penalties are required to be made on or by specified dates, they shall be deemed to have been made at the time they are filed with or paid to the chief of the Washington state patrol, through the director of fire protection, or, if sent by mail, on the date shown by the United States postmark on the envelope containing the report or payment.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2055[1995 c 369 § 55]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%20115[1986 c 266 § 115]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2069[1961 c 228 § 69]; ]

== 70.77.480 - Prohibited transfers of fireworks.
The transfer of fireworks ownership whether by sale at wholesale or retail, by gift or other means of conveyance of title, or by delivery of any fireworks to any person in the state who does not possess and present to the carrier for inspection at the time of delivery a valid license, where such license is required to purchase, possess, transport, or use fireworks, is prohibited.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2039[1982 c 230 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2073[1961 c 228 § 73]; ]

== 70.77.485 - Unlawful possession of fireworks—Penalties.
It is unlawful to possess any class or kind of fireworks in violation of this chapter. A violation of this section is:

. A misdemeanor if involving less than one pound of fireworks, exclusive of external packaging; or

. A gross misdemeanor if involving one pound or more of fireworks, exclusive of external packaging.

For the purposes of this section, "external packaging" means any materials that are not an integral part of the operative unit of fireworks.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2030[1984 c 249 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2074[1961 c 228 § 74]; ]

== 70.77.488 - Unlawful discharge or use of fireworks—Penalty.
It is unlawful for any person to discharge or use fireworks in a reckless manner which creates a substantial risk of death or serious physical injury to another person or damage to the property of another. A violation of this section is a gross misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2037[1984 c 249 § 37]; ]

== 70.77.495 - Forestry permit to set off fireworks in forest, brush, fallow, etc.
It is unlawful for any person to set off fireworks of any kind in forest, fallows, grass, or brush covered land, either on his or her own land or the property of another, between April 15th and December 1st of any year, unless it is done under a written permit from the Washington state department of natural resources or its duly authorized agent, and in strict accordance with the terms of the permit and any other applicable law.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20396[2012 c 117 § 396]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2039[2002 c 370 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c128.pdf?cite=1988%20c%20128%20§%2011[1988 c 128 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2076[1961 c 228 § 76]; ]

== 70.77.510 - Unlawful sales or transfers of display fireworks—Penalty.
It is unlawful for any person knowingly to sell, transfer, or agree to sell or transfer any display fireworks to any person who is not a fireworks licensee as provided for by this chapter. A violation of this section is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2040[2002 c 370 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2031[1984 c 249 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2040[1982 c 230 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2079[1961 c 228 § 79]; ]

== 70.77.515 - Unlawful sales or transfers of consumer fireworks—Penalty.
. It is unlawful for any person to offer for sale, sell, or exchange for consideration, any consumer fireworks to a consumer or user other than at a fixed place of business of a retailer for which a license and permit have been issued.

. No licensee may sell any fireworks to any person under the age of sixteen.

. A violation of this section is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2041[2002 c 370 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2032[1984 c 249 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2041[1982 c 230 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2080[1961 c 228 § 80]; ]

== 70.77.517 - Unlawful transportation of fireworks—Penalty.
It is unlawful for any person, except in the course of continuous interstate transportation through any state, to transport fireworks from this state into any other state, or deliver them for transportation into any other state, or attempt so to do, knowing that such fireworks are to be delivered, possessed, stored, transshipped, distributed, sold, or otherwise dealt with in a manner or for a use prohibited by the laws of such other state specifically prohibiting or regulating the use of fireworks. A violation of this section is a gross misdemeanor.

This section does not apply to a common or contract carrier or to international or domestic water carriers engaged in interstate commerce or to the transportation of fireworks into a state for the use of United States agencies in the carrying out or the furtherance of their operations.

In the enforcement of this section, the definitions of fireworks contained in the laws of the respective states shall be applied.

As used in this section, the term "state" includes the several states, territories, and possessions of the United States, and the District of Columbia.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2042[2002 c 370 § 42]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2034[1984 c 249 § 34]; ]

== 70.77.520 - Unlawful to permit fire nuisance where fireworks kept—Penalty.
It is unlawful for any person to allow any combustibles to accumulate in any premises in which fireworks are stored or sold or to permit a fire nuisance to exist in such a premises. A violation of this section is a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2043[2002 c 370 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2033[1984 c 249 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2081[1961 c 228 § 81]; ]

== 70.77.525 - Manufacture or sale of fireworks for out-of-state shipment.
This chapter does not prohibit any manufacturer, wholesaler, dealer, or jobber, having a license and a permit secured under the provisions of this chapter, from manufacturing or selling any kind of fireworks for direct shipment out of this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2042[1982 c 230 § 42]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2082[1961 c 228 § 82]; ]

== 70.77.530 - Nonprohibited acts—Signal purposes, forest protection.
This chapter does not prohibit the use of torpedoes, flares, or fusees by motor vehicles, railroads, or other transportation agencies for signal purposes or illumination or for use in forest protection activities.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2083[1961 c 228 § 83]; ]

== 70.77.535 - Articles pyrotechnic, special effects for entertainment media.
The assembling, compounding, use, and display of articles pyrotechnic or special effects in the production of motion pictures, radio or television productions, or live entertainment shall be under the direction and control of a pyrotechnic operator licensed by the state of Washington and who possesses a valid permit from the city or county.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2044[2002 c 370 § 44]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2642-S.SL.pdf?cite=1994%20c%20133%20§%2014[1994 c 133 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2035[1984 c 249 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2043[1982 c 230 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2084[1961 c 228 § 84]; ]

== 70.77.540 - Penalty.
Except as otherwise provided in this chapter, any person violating any of the provisions of this chapter or any rules issued thereunder is guilty of a misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%2036[1984 c 249 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2085[1961 c 228 § 85]; ]

== 70.77.545 - Violation a separate, continuing offense.
A person is guilty of a separate offense for each day during which he or she commits, continues, or permits a violation of any provision of, or any order, rule, or regulation made pursuant to this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20397[2012 c 117 § 397]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2086[1961 c 228 § 86]; ]

== 70.77.547 - Civil enforcement not precluded.
The inclusion in this chapter of criminal penalties does not preclude enforcement of this chapter through civil means.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2642-S.SL.pdf?cite=1994%20c%20133%20§%2015[1994 c 133 § 15]; ]

== 70.77.548 - Attorney general may institute civil proceedings—Venue.
Civil proceedings to enforce this chapter may be brought in the superior court of Thurston county or the county in which the violation occurred by the attorney general or the attorney of the city or county in which the violation occurred on his or her own motion or at the request of the chief of the Washington state patrol, through the director of fire protection.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2048[2002 c 370 § 48]; ]

== 70.77.549 - Civil penalty—Costs.
In addition to criminal penalties, a person who violates this chapter is also liable for a civil penalty and for the costs incurred with enforcing this chapter and bringing the civil action, including court costs and reasonable investigative and attorneys' fees.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2049[2002 c 370 § 49]; ]

== 70.77.550 - Short title.
This chapter shall be known and may be cited as the state fireworks law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2087[1961 c 228 § 87]; ]

== 70.77.555 - Local permit and license fees—Limits.
. A city or county may provide by ordinance for a fee in an amount sufficient to cover all legitimate costs for all needed permits, licenses, and authorizations from application to and through processing, issuance, and inspection, but in no case to exceed a total of one hundred dollars for any one retail sales permit for any one selling season in a year, whether June 28th through July 5th or December 27th through December 31st, or a total of two hundred dollars for both selling seasons.

. A city or county may provide by ordinance for a fee in an amount sufficient to cover all legitimate costs for all display permits, licenses, and authorizations from application to and through processing, issuance, and inspection, not to exceed actual costs and in no case more than a total of five thousand dollars for any one display permit.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2045[2002 c 370 § 45]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=1995%20c%2061%20§%2026[1995 c 61 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c230.pdf?cite=1982%20c%20230%20§%2044[1982 c 230 § 44]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2088[1961 c 228 § 88]; ]

== 70.77.575 - Chief of the Washington state patrol to provide list of consumer fireworks that may be sold to the public.
. The chief of the Washington state patrol, through the director of fire protection, shall adopt by rule a list of the consumer fireworks that may be sold to the public in this state pursuant to this chapter. The chief of the Washington state patrol, through the director of fire protection, shall file the list by October 1st of each year with the code reviser for publication, unless the previously published list has remained current.

. The chief of the Washington state patrol, through the director of fire protection, shall provide the list adopted under subsection (1) of this section by November 1st of each year to all manufacturers, wholesalers, and importers licensed under this chapter, unless the previously distributed list has remained current.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2046[2002 c 370 § 46]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2057[1995 c 369 § 57]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%20117[1986 c 266 § 117]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%208[1984 c 249 § 8]; ]

== 70.77.580 - Retailers to post list of consumer fireworks.
Retailers required to be licensed under this chapter shall post prominently at each retail location a list of the consumer fireworks that may be sold to the public in this state pursuant to this chapter. The posted list shall be in a form approved by the chief of the Washington state patrol, through the director of fire protection. The chief of the Washington state patrol, through the director of fire protection, shall make the list available.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%2047[2002 c 370 § 47]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2058[1995 c 369 § 58]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%20118[1986 c 266 § 118]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c249.pdf?cite=1984%20c%20249%20§%209[1984 c 249 § 9]; ]

== 70.77.900 - Effective date—1961 c 228.
This act shall take effect on January 1, 1962.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c228.pdf?cite=1961%20c%20228%20§%2090[1961 c 228 § 90]; ]

