= 70.58 - Vital statistics.
:toc:

== 70.58.230 - Permits for burial, removal, etc., required—Removal to another district without permit, notice to registrar, fee.
It is unlawful for any person to inter; deposit in a vault, grave, or tomb; perform alkaline hydrolysis or natural organic reduction as defined in RCW 68.04.310; or otherwise dispose of, or disinter or remove from one registration district to another, or hold for more than three business days after death, the human remains of any person whose death occurred in this state or any human remains which shall be found in this state, without obtaining, from the local registrar of the district in which the death occurred or in which the human remains were found, a permit for the burial, disinterment, or removal of the human remains. However, a licensed funeral director or embalmer of this state or a funeral establishment licensed in another state contiguous to Washington, with a current certificate of removal registration issued by the director of the department of licensing, may remove human remains from the district where the death occurred to another registration district or Oregon or Idaho without having obtained a permit but in such cases the funeral director or embalmer must at the time of removing human remains file with or mail to the local registrar of the district where the death occurred a notice of removal upon a blank to be furnished by the state registrar. The notice of removal must be signed or electronically approved by the funeral director or embalmer and must contain the name and address of the local registrar with whom the certificate of death will be filed and the burial-transit permit secured. Every local registrar, accepting a death certificate and issuing a burial-transit permit for a death that occurred outside his or her district, is entitled to a fee of one dollar to be paid by the funeral director or embalmer at the time the death certificate is accepted and the permit is secured. It is unlawful for any person to bring into or transport within the state or inter, deposit in a vault, grave, or tomb, or cremate or otherwise dispose of human remains of any person whose death occurred outside this state unless the human remains are accompanied by a removal or transit permit issued in accordance with the law and health regulations in force where the death occurred, or unless a special permit for bringing the human remains into this state is obtained from the state registrar.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5001-S.SL.pdf?cite=2019%20c%20432%20§%2030[2019 c 432 § 30]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1515.SL.pdf?cite=2009%20c%20231%20§%204[2009 c 231 § 4]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20157[2005 c 365 § 157]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961ex1c5.pdf?cite=1961%20ex.s.%20c%205%20§%2016[1961 ex.s. c 5 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c180.pdf?cite=1915%20c%20180%20§%203[1915 c 180 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c83.pdf?cite=1907%20c%2083%20§%204[1907 c 83 § 4]; RRS § 6021; ]

== 70.58.260 - Burial grounds—Duties of individual in charge of the premises.
It is unlawful for any person in charge of any premises in which bodies of deceased persons are interred, cremated, or otherwise permanently disposed of, to permit the final disposition, or other disposition of any body upon such premises unless it is accompanied by a burial, removal, or transit permit as provided in this chapter. It is the duty of the person in charge of any such premises to, in case of the interment, cremation, alkaline hydrolysis, natural organic reduction as defined in RCW 68.04.310, or other disposition of human remains therein, endorse upon the permit the date and character of such disposition, over his or her signature or electronic approval, to return all permits so endorsed to the local registrar of the district in which the death occurred within ten days from the date of such disposition, and to keep a record of all human remains disposed of on the premises under his or her charge, stating, in each case, the name of the deceased person, if known, the place of death, the date of burial or other disposition, and the name and address of the undertaker, which record must at all times be open to public inspection, and it is the duty of every undertaker, or person acting as such, when burying human remains in a cemetery or burial grounds having no person in charge, to sign or electronically approve the burial, removal, or transit permit, giving the date of burial, write across the face of the permit the words "no person in charge," and file the burial, removal, or transit permit within ten days with the registrar of the district in which the death occurred.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5001-S.SL.pdf?cite=2019%20c%20432%20§%2031[2019 c 432 § 31]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1515.SL.pdf?cite=2009%20c%20231%20§%207[2009 c 231 § 7]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20159[2005 c 365 § 159]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c180.pdf?cite=1915%20c%20180%20§%207[1915 c 180 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c83.pdf?cite=1907%20c%2083%20§%2010[1907 c 83 § 10]; RRS § 6027; ]

