= 70.83E - Prenatal newborn screening for exposure to harmful drugs.
:toc:

== 70.83E.010 - Declaration—Policy.
The policy of the state of Washington is to make every effort to detect as early as feasible and to prevent where possible preventable disorders resulting from parental use of alcohol and drugs.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3103.SL.pdf?cite=1998%20c%2093%20§%201[1998 c 93 § 1]; ]

== 70.83E.020 - Screening criteria, training protocols—Development of.
The department of health, in consultation with appropriate medical professionals, shall develop screening criteria for use in identifying pregnant or lactating women addicted to drugs or alcohol who are at risk of producing a drug-affected baby. The department shall also develop training protocols for medical professionals related to the identification and screening of women at risk of producing a drug-affected baby.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3103.SL.pdf?cite=1998%20c%2093%20§%202[1998 c 93 § 2]; ]

== 70.83E.030 - Department of health—Duties.
The department of health shall investigate the feasibility of medical protocols for laboratory testing or other screening of newborn infants for exposure to alcohol or drugs. The department of health shall consider how to improve the current system with respect to testing, considering such variables as whether such testing is available, its cost, which entity is currently responsible for ordering testing, and whether testing should be mandatory or targeted.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3103.SL.pdf?cite=1998%20c%2093%20§%203[1998 c 93 § 3]; ]

