= 70.87 - Elevators, lifting devices, and moving walks.
:toc:

== 70.87.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Advisory committee" means the elevator advisory committee as described in this chapter.

. "Alteration" means any change to equipment, including its parts, components, and/or subsystems, other than maintenance, repair, or replacement.

. "Automobile parking elevator" means an elevator: (a) Located in either a stationary or horizontally moving hoistway; (b) used exclusively for parking automobiles where, during the parking process, each automobile is moved either under its own power or by means of a power-driven transfer device onto and off the elevator directly into parking spaces or cubicles in line with the elevator; and (c) in which persons are not normally stationed on any level except the receiving level.

. "Belt manlift" means a power driven endless belt provided with steps or platforms and a hand hold for the transportation of personnel from floor to floor.

. "Casket lift" means a lift that (a) is installed at a mortuary, (b) is designed exclusively for carrying of caskets, (c) moves in guides in a basically vertical direction, and (d) serves two or more floors or landings.

. "Conveyance" means an elevator, escalator, dumbwaiter, belt manlift, automobile parking elevator, moving walk, and other elevating devices, as defined in this section.

. "Conveyance work" means the alteration, construction, dismantling, erection, installation, maintenance, relocation, and wiring of a conveyance.

. "Department" means the department of labor and industries.

. "Director" means the director of the department or his or her representative.

. "Dumbwaiter" means a hoisting and lowering mechanism equipped with a car (a) that moves in guides in a substantially vertical direction, (b) the floor area of which does not exceed nine square feet, (c) the inside height of which does not exceed four feet, (d) the capacity of which does not exceed five hundred pounds, and (e) that is used exclusively for carrying materials.

. "Elevator" means a hoisting or lowering machine equipped with a car or platform that moves in guides and serves two or more floors or landings of a building or structure;

.. "Passenger elevator" means an elevator (i) on which passengers are permitted to ride and (ii) that may be used to carry freight or materials when the load carried does not exceed the capacity of the elevator;

.. "Freight elevator" means an elevator (i) used primarily for carrying freight and (ii) on which only the operator, the persons necessary for loading and unloading, and other employees approved by the department are permitted to ride;

.. "Sidewalk elevator" means a freight elevator that: (i) Operates between a sidewalk or other area outside the building and floor levels inside the building below the outside area, (ii) does not have a landing opening into the building at its upper limit of travel, and (iii) is not used to carry automobiles;

.. "Hand elevator" means an elevator utilizing manual energy to move the car;

.. "Inclined elevator" means an elevator that travels at an angle of inclination of seventy degrees or less from the horizontal;

.. "Multideck elevator" means an elevator having two or more compartments located one immediately above the other;

.. "Observation elevator" means an elevator designed to permit exterior viewing by passengers while the car is traveling;

.. "Power elevator" means an elevator utilizing energy other than gravitational or manual to move the car;

.. "Electric elevator" means an elevator where the energy is applied by means of an electric driving machine;

.. "Hydraulic elevator" means an elevator where the energy is applied by means of a liquid under pressure in a cylinder equipped with a plunger or piston;

.. "Direct-plunger hydraulic elevator" means a hydraulic elevator having a plunger or cylinder directly attached to the car frame or platform;

.. "Electro-hydraulic elevator" means a direct-plunger elevator where liquid is pumped under pressure directly into the cylinder by a pump driven by an electric motor;

.. "Maintained-pressure hydraulic elevator" means a direct-plunger elevator where liquid under pressure is available at all times for transfer into the cylinder;

.. "Roped hydraulic elevator" means a hydraulic elevator having its plunger or piston connected to the car with wire ropes or indirectly coupled to the car by means of wire ropes and sheaves;

.. "Rack and pinion elevator" means a power elevator, with or without a counterweight, that is supported, raised, and lowered by a motor or motors that drive a pinion or pinions on a stationary rack mounted in the hoistway;

.. "Screw column elevator" means a power elevator having an uncounterweighted car that is supported, raised, and lowered by means of a screw thread;

.. "Rooftop elevator" means a power passenger or freight elevator that operates between a landing at roof level and one landing below and opens onto the exterior roof level of a building through a horizontal opening;

.. "Special purpose personnel elevator" means an elevator that is limited in size, capacity, and speed, and permanently installed in structures such as grain elevators, radio antenna, bridge towers, underground facilities, dams, power plants, and similar structures to provide vertical transportation of authorized personnel and their tools and equipment only;

.. "Workmen's construction elevator" means an elevator that is not part of the permanent structure of a building and is used to raise and lower workers and other persons connected with, or related to, the building project;

.. "Boat launching elevator" means a conveyance that serves a boat launching structure and a beach or water surface and is used for the carrying or handling of boats in which people ride;

.. "Limited-use/limited-application elevator" means a power passenger elevator where the use and application is limited by size, capacity, speed, and rise, intended principally to provide vertical transportation for people with physical disabilities.

. "Elevator contractor" means any person, firm, or company that possesses an elevator contractor license in accordance with this chapter and who is engaged in the business of performing conveyance work covered by this chapter.

. "Elevator contractor license" means a license that is issued to an elevator contractor who has met the qualification requirements established in RCW 70.87.240.

. "Elevator helper/apprentice" means a person who works under the general direction of a licensed elevator mechanic. A license is not required to be an elevator helper/apprentice.

. "Elevator mechanic" means any person who possesses an elevator mechanic license in accordance with this chapter and who is engaged in performing conveyance work covered by this chapter.

. "Elevator mechanic license" means a license that is issued to a person who has met the qualification requirements established in RCW 70.87.240.

. "Employee" means any person employed by an elevator contractor.

. "Escalator" means a power-driven, inclined, continuous stairway used for raising and lowering passengers.

. "Existing installations" means an installation defined as an "installation, existing" in this chapter or in rules adopted under this chapter.

. "Inspector" means an elevator inspector of the department or an elevator inspector of a municipality having in effect an elevator ordinance pursuant to RCW 70.87.200.

. "License" means a written license, duly issued by the department, authorizing a person, firm, or company to carry on the business of performing conveyance work or to perform conveyance work covered by this chapter.

. "Licensee" means the elevator mechanic or elevator contractor.

. "Maintenance" means a process of routine examination, lubrication, cleaning, servicing, and adjustment of parts, components, and/or subsystems for the purpose of ensuring performance in accordance with this chapter. "Maintenance" includes repair and replacement, but not alteration.

. "Material hoist" means a hoist that is not a part of a permanent structure used to raise or lower materials during construction, alteration, or demolition. It is not applicable to the temporary use of permanently installed personnel elevators as material hoists.

. "Material lift" means a lift that (a) is permanently installed, (b) is comprised of a car or platform that moves in guides, (c) serves two or more floors or landings, (d) travels in a vertical or inclined position, (e) is an isolated, self-contained lift, (f) is not part of a conveying system, and (g) is installed in a commercial or industrial area not accessible to the general public or intended to be operated by the general public.

. "Moving walk" means a passenger-carrying device (a) on which passengers stand or walk and (b) on which the passenger-carrying surface remains parallel to its direction of motion.

. "One-man capacity manlift" means a single passenger, hand-powered counterweighted device, or electric-powered device, that travels vertically in guides and serves two or more landings.

. "Owner" means any person having title to or control of a conveyance, as guardian, trustee, lessee, or otherwise.

. "Permit" means a permit issued by the department: (a) To perform conveyance work, other than maintenance; or (b) to operate a conveyance.

. "Person" means this state, a political subdivision, any public or private corporation, any firm, or any other entity as well as an individual.

. "Personnel hoist" means a hoist that is not a part of a permanent structure, is installed inside or outside buildings during construction, alteration, or demolition, and used to raise or lower workers and other persons connected with, or related to, the building project. The hoist may also be used for transportation of materials.

. "Platform" means a rigid surface that is maintained in a horizontal position at all times when in use, and upon which passengers stand or a load is carried.

. "Private residence conveyance" means a conveyance installed in or on the premises of a single-family dwelling and operated for transporting persons or property from one elevation to another.

. "Public agency" means a county, incorporated city or town, municipal corporation, state agency, institution of higher education, political subdivision, or other public agency and includes any department, bureau, office, board, commission or institution of such public entities.

. "Repair" means the reconditioning or renewal of parts, components, and/or subsystems necessary to keep equipment in compliance with this chapter.

. "Replacement" means the substitution of a device, component, and/or subsystem in its entirety with a unit that is basically the same as the original for the purpose of ensuring performance in accordance with this chapter.

. "Single-occupancy farm conveyance" means a hand-powered counterweighted single-occupancy conveyance that travels vertically in a grain elevator and is located on a farm that does not accept commercial grain.

. "Stairway chair lift" means a lift that travels in a basically inclined direction and is designed for use by individuals with disabilities.

. "Wheelchair lift" means a lift that travels in a vertical or inclined direction and is designed for use by individuals with disabilities.

. "Whistleblower" means any employee who in good faith reports practices or opposes practices that may violate the provisions of this chapter or the rules promulgated hereunder, or of the safety, installation, repair, or maintenance policies of his or her employer. The term also means (a) an employee who is believed to have reported such practices but who, in fact, has not reported such practices or (b) an employee who has assisted in the reporting of practices or has provided testimony or information in connection with the reporting of practices.

. "Workplace reprisal or retaliatory action" includes actions such as discharge or in any manner discrimination against any employee who has reported or filed any complaint or instituted or caused to be instituted any proceeding under or related to this chapter, or has testified or is about to testify in any such proceeding or because of the exercise by such employee on behalf of himself or herself or others of any right or responsibility afforded by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5412-S.SL.pdf?cite=2012%20c%2054%20§%202[2012 c 54 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5793-S.SL.pdf?cite=2009%20c%20128%20§%201[2009 c 128 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5942-S.SL.pdf?cite=2003%20c%20143%20§%209[2003 c 143 § 9]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2629-S.SL.pdf?cite=2002%20c%2098%20§%201[2002 c 98 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2313-S.SL.pdf?cite=1998%20c%20137%20§%201[1998 c 137 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1828.SL.pdf?cite=1997%20c%20216%20§%201[1997 c 216 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c123.pdf?cite=1983%20c%20123%20§%201[1983 c 123 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c52.pdf?cite=1973%201st%20ex.s.%20c%2052%20§%209[1973 1st ex.s. c 52 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c108.pdf?cite=1969%20ex.s.%20c%20108%20§%201[1969 ex.s. c 108 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c26.pdf?cite=1963%20c%2026%20§%201[1963 c 26 § 1]; ]

== 70.87.020 - Conveyances to be safe and in conformity with law.
. The purpose of this chapter is to provide for safety of life and limb, to promote safety awareness, and to ensure the safe design, mechanical and electrical operation, and inspection of conveyances, and performance of conveyance work, and all such operation, inspection, and conveyance work subject to the provisions of this chapter shall be reasonably safe to persons and property and in conformity with the provisions of this chapter and the applicable statutes of the state of Washington, and all orders, and rules of the department. The use of unsafe and defective conveyances imposes a substantial probability of serious and preventable injury to employees and the public exposed to unsafe conditions. The prevention of these injuries and protection of employees and the public from unsafe conditions is in the best interest of the people of this state. It is the policy of the legislature that employees should be protected from workplace reprisal or retaliatory action for the opposition to or reporting in good faith of practices that may violate the provisions of this chapter and the rules promulgated hereunder, or of the safety, installation, repair, or maintenance policies of their employers. Personnel performing work covered by this chapter must, by documented training or experience or both, be familiar with the operation and safety functions of the components and equipment. Training and experience must include, but not be limited to, recognizing the safety hazards and performing the procedures to which the personnel performing conveyance work covered by this chapter are assigned in conformance with the requirements of this chapter. This chapter establishes the minimum standards for personnel performing conveyance work.

. This chapter is not intended to prevent the use of systems, methods, or devices of equivalent or superior quality, strength, fire resistance, code effectiveness, durability, and safety to those required by this chapter, provided that there is technical documentation to demonstrate the equivalency of the system, method, or device, as prescribed in this chapter and the rules adopted under this chapter.

. In any suit for damages allegedly caused by a failure or malfunction of the conveyance, conformity with the rules of the department is prima facie evidence that the conveyance work, operation, and inspection is reasonably safe to persons and property.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5412-S.SL.pdf?cite=2012%20c%2054%20§%201[2012 c 54 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5942-S.SL.pdf?cite=2003%20c%20143%20§%2010[2003 c 143 § 10]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2629-S.SL.pdf?cite=2002%20c%2098%20§%202[2002 c 98 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c123.pdf?cite=1983%20c%20123%20§%202[1983 c 123 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c26.pdf?cite=1963%20c%2026%20§%202[1963 c 26 § 2]; ]

== 70.87.030 - Rules—Waivers during state of emergency.
The department shall adopt rules governing the mechanical and electrical operation, acceptance tests, conveyance work, operation, and inspection that are necessary and appropriate and shall also adopt minimum standards governing existing installations. In the execution of this rule-making power and before the adoption of rules, the department shall consider the rules for safe conveyance work, operation, and inspection, including the American National Standards Institute Safety Code for Personnel and Material Hoists, the American Society of Mechanical Engineers Safety Code for Elevators, Dumbwaiters, and Escalators, and any amendatory or supplemental provisions thereto. The department by rule shall establish a schedule of fees to pay the costs incurred by the department for the work related to administration and enforcement of this chapter. Nothing in this chapter limits the authority of the department to prescribe or enforce general or special safety orders as provided by law.

The department may consult with: Engineering authorities and organizations concerned with standard safety codes; rules and regulations governing conveyance work, operation, and inspection; and the qualifications that are adequate, reasonable, and necessary for the elevator mechanic, contractor, and inspector.

During a state of emergency declared under RCW 43.06.010(12), the governor may waive or suspend the collection of fees under this section or any portion of this section or under any administrative rule, and issue any orders to facilitate the operation of state or local government or to promote and secure the safety and protection of the civilian population.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6950.SL.pdf?cite=2008%20c%20181%20§%20206[2008 c 181 § 206]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5942-S.SL.pdf?cite=2003%20c%20143%20§%2011[2003 c 143 § 11]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2629-S.SL.pdf?cite=2002%20c%2098%20§%203[2002 c 98 § 3]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2313-S.SL.pdf?cite=1998%20c%20137%20§%202[1998 c 137 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2390.SL.pdf?cite=1994%20c%20164%20§%2028[1994 c 164 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c123.pdf?cite=1983%20c%20123%20§%203[1983 c 123 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c52.pdf?cite=1973%201st%20ex.s.%20c%2052%20§%2010[1973 1st ex.s. c 52 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c66.pdf?cite=1971%20c%2066%20§%201[1971 c 66 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c22.pdf?cite=1970%20ex.s.%20c%2022%20§%201[1970 ex.s. c 22 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c26.pdf?cite=1963%20c%2026%20§%203[1963 c 26 § 3]; ]

== 70.87.034 - Additional powers of department.
The department also has the following powers:

. The department may adopt any rules necessary or helpful for the department to implement and enforce this chapter.

. The director may issue subpoenas for the production of persons, papers, or information in all proceedings and investigations within the scope of this chapter. If a person refuses to obey a subpoena, the director, through the attorney general, may ask the superior court to order the person to obey the subpoena.

. The director may take the oral or written testimony of any person. The director has the power to administer oaths.

. The director may make specific decisions, cease and desist orders, other orders, and rulings, including demands and findings.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c123.pdf?cite=1983%20c%20123%20§%2019[1983 c 123 § 19]; ]

== 70.87.036 - Powers of attorney general.
On request of the department, the attorney general may:

. File suit to collect a penalty assessed by the department;

. Seek a civil injunction, show cause order, or contempt order against the person who repeatedly violates a provision of this chapter;

. Seek an ex parte inspection warrant if the person refuses to allow the department to inspect a conveyance;

. File suit asking the court to enforce a cease and desist order or a subpoena issued by the director under this chapter; and

. Take any other legal action appropriate and necessary for the enforcement of the provisions of this chapter.

All suits shall be brought in the district or superior court of the district or county in which the defendant resides or transacts business. In any suit or other legal action, the department may ask the court to award costs and attorney's fees. If the department prevails, the court shall award the appropriate costs and attorney's fees.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c123.pdf?cite=1983%20c%20123%20§%2020[1983 c 123 § 20]; ]

== 70.87.040 - Privately and publicly owned conveyances are subject to chapter.
All privately owned and publicly owned conveyances are subject to the provisions of this chapter except as specifically excluded by this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c123.pdf?cite=1983%20c%20123%20§%204[1983 c 123 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c26.pdf?cite=1963%20c%2026%20§%204[1963 c 26 § 4]; ]

== 70.87.050 - Conveyances in buildings occupied by state, county, or political subdivision.
The conveyance work on, and the operation and inspection of any conveyance located in, or used in connection with, any building owned by the state, a county, or a political subdivision, other than those located within and owned by a city having an elevator code, shall be under the jurisdiction of the department.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5942-S.SL.pdf?cite=2003%20c%20143%20§%2012[2003 c 143 § 12]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2629-S.SL.pdf?cite=2002%20c%2098%20§%204[2002 c 98 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c123.pdf?cite=1983%20c%20123%20§%205[1983 c 123 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c108.pdf?cite=1969%20ex.s.%20c%20108%20§%202[1969 ex.s. c 108 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c26.pdf?cite=1963%20c%2026%20§%205[1963 c 26 § 5]; ]

== 70.87.060 - Responsibility for operation and maintenance of equipment and for periodic tests.
. The person, elevator contractor, or public agency performing conveyance work is responsible for operation and maintenance of the conveyance until the department has issued an operating permit for the conveyance, except during the period when a limited operating permit in accordance with RCW 70.87.090(2) is in effect, and is also responsible for all tests of a new, relocated, or altered conveyance until the department has issued an operating permit for the conveyance.

. The owner or his or her duly appointed agent shall be responsible for the safe operation and proper maintenance of the conveyance after the department has issued the operating permit and also during the period of effectiveness of any limited operating permit in accordance with RCW 70.87.090(2). The owner shall be responsible for all periodic tests required by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5942-S.SL.pdf?cite=2003%20c%20143%20§%2013[2003 c 143 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c123.pdf?cite=1983%20c%20123%20§%206[1983 c 123 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c26.pdf?cite=1963%20c%2026%20§%206[1963 c 26 § 6]; ]

== 70.87.070 - Serial numbers.
All new and existing conveyances shall have a serial number painted on or attached as directed by the department. This serial number shall be assigned by the department and shown on all required permits.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c123.pdf?cite=1983%20c%20123%20§%207[1983 c 123 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c26.pdf?cite=1963%20c%2026%20§%207[1963 c 26 § 7]; ]

== 70.87.080 - Permits—When required—Application for—Posting.
. A permit shall be obtained from the department before performing work, other than maintenance, on a conveyance under the jurisdiction of the department.

. The installer of the conveyance shall submit an application for the permit in duplicate, in a form that the department may prescribe.

. The permit issued by the department shall be kept posted conspicuously at the site of installation.

. A permit is not required for maintenance.

. After the effective date of rules adopted under this chapter establishing licensing requirements, the department may issue a permit for conveyance work only to an elevator contractor unless the permit is for conveyance work on private residence conveyances. After July 1, 2004, the department may not issue a permit for conveyance work on private residence conveyances to a person other than an elevator contractor.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5942-S.SL.pdf?cite=2003%20c%20143%20§%2014[2003 c 143 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c123.pdf?cite=1983%20c%20123%20§%208[1983 c 123 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c26.pdf?cite=1963%20c%2026%20§%208[1963 c 26 § 8]; ]

== 70.87.090 - Operating permits—Limited permits—Duration—Posting.
. An operating permit is required for each conveyance operated in the state of Washington except during its erection by the person or firm responsible for its installation. A permit issued by the department shall be kept conspicuously posted near the conveyance.

. The department may permit the temporary use of a conveyance during its installation or alteration, under the authority of a limited permit issued by the department for each class of service. Limited permits shall be issued for a period not to exceed thirty days and may be renewed at the discretion of the department. This limited-use permit is to provide transportation for construction personnel, tools, and materials only. Where a limited permit is issued, a notice bearing the information that the equipment has not been finally approved shall be conspicuously posted.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2313-S.SL.pdf?cite=1998%20c%20137%20§%203[1998 c 137 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c123.pdf?cite=1983%20c%20123%20§%209[1983 c 123 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c26.pdf?cite=1963%20c%2026%20§%209[1963 c 26 § 9]; ]

== 70.87.100 - Conveyance work to be performed by elevator contractors—Acceptance tests—Inspections.
. All conveyance installations, relocations, or alterations must be performed by an elevator contractor employing an elevator mechanic.

. The elevator contractor employing an elevator mechanic performing such conveyance work shall notify the department before completion of the work, and shall subject the new, moved, or altered portions of the conveyance to the acceptance tests.

. All new, altered, or relocated conveyances for which a permit has been issued, shall be inspected for compliance with the requirements of this chapter by an authorized representative of the department. The authorized representative shall also witness the test specified.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5942-S.SL.pdf?cite=2003%20c%20143%20§%2015[2003 c 143 § 15]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2629-S.SL.pdf?cite=2002%20c%2098%20§%205[2002 c 98 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c123.pdf?cite=1983%20c%20123%20§%2011[1983 c 123 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c26.pdf?cite=1963%20c%2026%20§%2010[1963 c 26 § 10]; ]

== 70.87.110 - Exceptions authorized.
The requirements of this chapter are intended to apply to all conveyances except as modified or waived by the department. They are intended to be modified or waived whenever any requirements are shown to be impracticable, such as involving expense not justified by the protection secured. However, the department shall not allow the modification or waiver unless equivalent or safer construction is secured in other ways. An exception applies only to the installation covered by the application for waiver.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c123.pdf?cite=1983%20c%20123%20§%2012[1983 c 123 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c26.pdf?cite=1963%20c%2026%20§%2011[1963 c 26 § 11]; ]

== 70.87.120 - Inspectors—Inspections and reinspections—Suspension or revocation of permit—Order to discontinue use—Penalties—Investigation by department—Waiver of provisions during state of emergency.
. The department shall appoint and employ inspectors, as may be necessary to carry out the provisions of this chapter, under the provisions of the rules adopted by the Washington personnel resources board in accordance with chapter 41.06 RCW.

. [Empty]
.. Except as provided in (b) of this subsection, the department shall cause all conveyances to be inspected and tested at least once each year. Inspectors have the right during reasonable hours to enter into and upon any building or premises in the discharge of their official duties, for the purpose of making any inspection or testing any conveyance contained thereon or therein. Inspections and tests shall conform with the rules adopted by the department. The department shall inspect all installations before it issues any initial permit for operation. Permits shall not be issued until the fees required by this chapter have been paid.

.. [Empty]
... Private residence conveyances operated exclusively for single-family use shall be inspected and tested only when required under RCW 70.87.100 or as necessary for the purposes of subsection (4) of this section and shall be exempt from RCW 70.87.090 unless an annual inspection and operating permit are requested by the owner.

... The department may perform additional inspections of a private residence conveyance at the request of the owner of the conveyance. Fees for these inspections shall be in accordance with the schedule of fees adopted for operating permits pursuant to RCW 70.87.030. An inspection requested under this subsection (2)(b)(ii) shall not be performed until the required fees have been paid.

. If inspection shows a conveyance to be in an unsafe condition, the department shall issue an inspection report in writing requiring the repairs or alterations to be made to the conveyance that are necessary to render it safe and may also suspend or revoke a permit pursuant to RCW 70.87.125 or order the operation of a conveyance discontinued pursuant to RCW 70.87.145.

.. A penalty may be assessed under RCW 70.87.185 for failure to correct a violation within ninety days after the owner is notified in writing of inspection results.

.. The owner may be assessed a penalty under RCW 70.87.185 for failure to submit official notification in writing to the department that all corrections have been completed.

. The department may investigate accidents and alleged or apparent violations of this chapter.

. During a state of emergency declared under RCW 43.06.010(12), the governor may waive or suspend the collection of fees under this section or any portion of this section or under any administrative rule, and issue any orders to facilitate the operation of state or local government or to promote and secure the safety and protection of the civilian population.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6950.SL.pdf?cite=2008%20c%20181%20§%20207[2008 c 181 § 207]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2313-S.SL.pdf?cite=1998%20c%20137%20§%204[1998 c 137 § 4]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1828.SL.pdf?cite=1997%20c%20216%20§%202[1997 c 216 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2054-S.SL.pdf?cite=1993%20c%20281%20§%2061[1993 c 281 § 61]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c123.pdf?cite=1983%20c%20123%20§%2013[1983 c 123 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c22.pdf?cite=1970%20ex.s.%20c%2022%20§%202[1970 ex.s. c 22 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c26.pdf?cite=1963%20c%2026%20§%2012[1963 c 26 § 12]; ]

== 70.87.125 - Suspension or revocation of license or permit—Grounds—Notice—Stay of suspension or revocation—Removal of suspension or reinstatement of license or permit.
. A license issued under this chapter may be suspended, revoked, or subject to civil penalty by the department upon verification that any one or more of the following reasons exist:

.. Any false statement as to a material matter in the application;

.. Fraud, misrepresentation, or bribery in securing a license;

.. Failure to notify the department and the owner or lessee of a conveyance or related mechanisms of any condition not in compliance with this chapter;

.. A violation of any provisions of this chapter; and

.. If the elevator contractor does not employ an individual designated as the primary point of contact with the department and who has successfully completed the elevator contractor examination. In the case of a separation of employment, termination of this relationship or designation, or death of the designated individual, the elevator contractor must, within ninety days, designate a new individual who has successfully completed the elevator contractor examination.

. The department may suspend or revoke a permit if:

.. The permit was obtained through fraud or by error if, in the absence of error, the department would not have issued the permit;

.. The conveyance for which the permit was issued has not been worked on in accordance with this chapter; or

.. The conveyance has become unsafe.

. The department shall suspend any license issued under this chapter promptly after receiving notice from the department of social and health services that the holder of the license has been certified pursuant to RCW 74.20A.320 as a person who is not in compliance with a support order. If the person has continued to meet all other license requirements during the suspension, reissuance of the license shall be automatic upon the department's receipt of a release issued by the department of social and health services stating that the person is in compliance with the order.

. The department shall notify in writing the owner, licensee, or person performing conveyance work, of its action and the reason for the action. The department shall send the notice using a method by which the mailing can be tracked or the delivery can be confirmed to the last known address of the owner or person. The notice shall inform the owner or person that a hearing may be requested pursuant to RCW 70.87.170.

. [Empty]
.. If the department has suspended or revoked a permit or license because of fraud or error, and a hearing is requested, the suspension or revocation shall be stayed until the hearing is concluded and a decision is issued.

.. If the department has revoked or suspended a license because the licensee performing the work covered by this chapter is working in a manner that does not effectively prevent injuries or deaths or protect employees and the public from unsafe conditions as is required by this chapter, the suspension or revocation is effective immediately and shall not be stayed by a request for a hearing.

.. If the department has revoked or suspended a permit because the conveyance is unsafe or the conveyance work is not permitted and performed in accordance with this chapter, the suspension or revocation is effective immediately and shall not be stayed by a request for a hearing.

. The department must remove a suspension or reinstate a revoked license if the licensee pays all the assessed civil penalties and is able to demonstrate to the department that the licensee has met all the qualifications established by this chapter.

. The department shall remove a suspension or reinstate a revoked permit if a conveyance is repaired or modified to bring it into compliance with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5067-S.SL.pdf?cite=2011%20c%20301%20§%2022[2011 c 301 § 22]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5942-S.SL.pdf?cite=2003%20c%20143%20§%2016[2003 c 143 § 16]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2629-S.SL.pdf?cite=2002%20c%2098%20§%206[2002 c 98 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c123.pdf?cite=1983%20c%20123%20§%2010[1983 c 123 § 10]; ]

== 70.87.140 - Operation without permit enjoinable.
Whenever any conveyance is being operated without a permit required by this chapter, the attorney general or the prosecuting attorney of the county may apply to the superior court of the county in which the conveyance is located for a temporary restraining order or a temporary or permanent injunction restraining the operation of the conveyance until the department issues a permit for the conveyance. No bond may be required from the department in such proceedings.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c123.pdf?cite=1983%20c%20123%20§%2014[1983 c 123 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c26.pdf?cite=1963%20c%2026%20§%2014[1963 c 26 § 14]; ]

== 70.87.145 - Order to discontinue operation—Notice—Conditions—Contents of order—Recision of order—Violation—Penalty—Random inspections.
. An authorized representative of the department may order the owner or person operating a conveyance to discontinue the operation of a conveyance, and may place a notice that states that the conveyance may not be operated on a conspicuous place in the conveyance, if:

.. The conveyance work has not been permitted and performed in accordance with this chapter; or

.. The conveyance has otherwise become unsafe.

The order is effective immediately, and shall not be stayed by a request for a hearing.

. The department shall prescribe a form for the order to discontinue operation. The order shall specify why the conveyance violates this chapter or is otherwise unsafe, and shall inform the owner or operator that he or she may request a hearing pursuant to RCW 70.87.170. A request for a hearing does not stay the effect of the order.

. The department shall rescind the order to discontinue operation if the conveyance is fixed or modified to bring it into compliance with this chapter.

. An owner or a person that knowingly operates or allows the operation of a conveyance in contravention of an order to discontinue operation, or removes a notice not to operate, is:

.. Guilty of a misdemeanor; and

.. Subject to a civil penalty under RCW 70.87.185.

. The department may conduct random on-site inspections and tests on existing installations, witnessing periodic inspections and testing in order to ensure satisfactory conveyance work by persons, firms, or companies performing conveyance work, and assist in development of public awareness programs.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5942-S.SL.pdf?cite=2003%20c%20143%20§%2017[2003 c 143 § 17]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2629-S.SL.pdf?cite=2002%20c%2098%20§%207[2002 c 98 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c123.pdf?cite=1983%20c%20123%20§%2015[1983 c 123 § 15]; ]

== 70.87.170 - Review of department action in accordance with administrative procedure act.
. Any person aggrieved by an order or action of the department denying, suspending, revoking, or refusing to renew a permit or license; assessing a penalty for a violation of this chapter; or ordering the operation of a conveyance to be discontinued, may request a hearing within fifteen days after notice of the department's order or action is received. The date the hearing was requested shall be the date the request for hearing was postmarked.

. The party requesting the hearing must accompany the request with a certified or cashier's check for two hundred dollars payable to the department, except that if a penalty assessment is the issue for the hearing, the check amount shall be ten percent of the penalty amount or two hundred dollars, whichever is less, but in no event less than one hundred dollars. The department shall refund the amount of the check if the party requesting the hearing prevails at the hearing; otherwise, the department shall retain the amount of the check.

. If the department does not receive a timely request for hearing, the department's order or action is final and may not be appealed.

. If the aggrieved party requests a hearing, the department shall ask an administrative law judge to preside over the hearing. The hearing shall be conducted in accordance with chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2146-S.SL.pdf?cite=2014%20c%20190%20§%205[2014 c 190 § 5]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5942-S.SL.pdf?cite=2003%20c%20143%20§%2018[2003 c 143 § 18]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2629-S.SL.pdf?cite=2002%20c%2098%20§%208[2002 c 98 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c123.pdf?cite=1983%20c%20123%20§%2016[1983 c 123 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c26.pdf?cite=1963%20c%2026%20§%2017[1963 c 26 § 17]; ]

== 70.87.180 - Violations.
. The performance of conveyance work, other than maintenance, or the operation of a conveyance without a permit by any person owning or having the custody, management, or operation thereof, except as provided in RCW 70.87.080 and 70.87.090, is a misdemeanor. Each day of violation is a separate offense. A prosecution may not be maintained if a person has requested the issuance or renewal of a permit but the department has not acted.

. The performance of conveyance work, other than the maintenance of conveyances as specified in RCW 70.87.270, without a license by any person is a misdemeanor. Each day of violation is a separate offense. A prosecution may not be maintained if a person has requested the issuance or renewal of a license but the department has not acted.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5942-S.SL.pdf?cite=2003%20c%20143%20§%2019[2003 c 143 § 19]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2629-S.SL.pdf?cite=2002%20c%2098%20§%209[2002 c 98 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c123.pdf?cite=1983%20c%20123%20§%2017[1983 c 123 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c26.pdf?cite=1963%20c%2026%20§%2018[1963 c 26 § 18]; ]

== 70.87.185 - Penalty for violation of chapter—Rules—Notice.
. The department may assess a penalty against a person violating a provision of this chapter. The penalty shall be not more than five hundred dollars. Each day that the violation continues is a separate violation and is subject to a separate penalty.

. The department may not assess a penalty until it adopts rules describing the method it will use to calculate penalties for various violations.

. The department shall notify the violator of its action, and the reasons for its action, in writing. The department shall send the notice using a method by which the mailing can be tracked or the delivery can be confirmed to the violator's last known address. The notice shall inform the violator that a hearing may be requested under RCW 70.87.170. The hearing shall not stay the effect of the penalty.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5067-S.SL.pdf?cite=2011%20c%20301%20§%2023[2011 c 301 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c123.pdf?cite=1983%20c%20123%20§%2018[1983 c 123 § 18]; ]

== 70.87.190 - Accidents—Report and investigation—Cessation of use—Removal of damaged parts.
The owner or the owner's duly authorized agent shall promptly notify the department of each accident to a person requiring the service of a physician or resulting in a disability exceeding one day, and shall afford the department every facility for investigating and inspecting the accident. The department shall without delay, after being notified, make an inspection and shall place on file a full and complete report of the accident. The report shall give in detail all material facts and information available and the cause or causes, so far as they can be determined. The report shall be open to public inspection at all reasonable hours. When an accident involves the failure or destruction of any part of the construction or the operating mechanism of a conveyance, the use of the conveyance is forbidden until it has been made safe; it has been reinspected and any repairs, changes, or alterations have been approved by the department; and a permit has been issued by the department. The removal of any part of the damaged construction or operating mechanism from the premises is forbidden until the department grants permission to do so.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c123.pdf?cite=1983%20c%20123%20§%2021[1983 c 123 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c26.pdf?cite=1963%20c%2026%20§%2019[1963 c 26 § 19]; ]

== 70.87.200 - Exemptions.
. The provisions of this chapter do not apply where:

.. A conveyance is permanently removed from service or made effectively inoperative; 

.. Lifts, hoists for persons, or material hoists are erected temporarily for use during construction work only and are of such a design that they must be operated by a worker stationed at the hoisting machine; or

.. A single-occupancy farm conveyance is used exclusively by a farm operator and the farm operator's family members.

. Except as limited by RCW 70.87.050, municipalities having in effect an elevator code prior to June 13, 1963, may continue to assume jurisdiction over conveyance work and may inspect, issue permits, collect fees, and prescribe minimum requirements for conveyance work and operation if the requirements are equal to the requirements of this chapter and to all rules pertaining to conveyances adopted and administered by the department. Upon the failure of a municipality having jurisdiction over conveyances to carry out the provisions of this chapter with regard to a conveyance, the department may assume jurisdiction over the conveyance. If a municipality elects not to maintain jurisdiction over certain conveyances located therein, it may enter into a written agreement with the department transferring exclusive jurisdiction of the conveyances to the department. The city may not reassume jurisdiction after it enters into such an agreement with the department.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%201025[2009 c 549 § 1025]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5793-S.SL.pdf?cite=2009%20c%20128%20§%202[2009 c 128 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5942-S.SL.pdf?cite=2003%20c%20143%20§%2020[2003 c 143 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c123.pdf?cite=1983%20c%20123%20§%2022[1983 c 123 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c108.pdf?cite=1969%20ex.s.%20c%20108%20§%204[1969 ex.s. c 108 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c26.pdf?cite=1963%20c%2026%20§%2020[1963 c 26 § 20]; ]

== 70.87.205 - Resolution of disputes by arbitration—Appointment of arbitrators—Procedure—Decision—Enforcement.
. Disputes arising under RCW 70.87.200(2) shall be resolved by arbitration. The request shall be sent using a method by which the mailing can be tracked or the delivery can be confirmed.

. The department shall appoint one arbitrator; the municipality shall appoint one arbitrator; and the arbitrators chosen by the department and the municipality shall appoint the third arbitrator. If the two arbitrators cannot agree on the third arbitrator, the presiding judge of the Thurston county superior court, or his or her designee, shall appoint the third arbitrator.

. The arbitration shall be held pursuant to the procedures in chapter 7.04A RCW, except that RCW 7.04A.280(1)(f) shall not apply. The decision of the arbitrators is final and binding on the parties. Neither party may appeal a decision to any court.

. A party may petition the Thurston county superior court to enforce a decision of the arbitrators.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5067-S.SL.pdf?cite=2011%20c%20301%20§%2024[2011 c 301 § 24]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2049[2005 c 433 § 49]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c123.pdf?cite=1983%20c%20123%20§%2023[1983 c 123 § 23]; ]

== 70.87.210 - Deposit of moneys from chapter.
All moneys, except fines and penalties, received or collected under the terms of this chapter shall be deposited in the construction registration inspection account. All fines and penalties received or collected under the terms of this chapter shall be deposited in the general fund.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1716.SL.pdf?cite=2017%203rd%20sp.s.%20c%2011%20§%203[2017 3rd sp.s. c 11 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c26.pdf?cite=1963%20c%2026%20§%2021[1963 c 26 § 21]; ]

== 70.87.220 - Elevator safety advisory committee.
. The department may adopt the rules necessary to establish and administer the elevator safety advisory committee. The purpose of the advisory committee is to advise the department on the adoption of rules that apply to conveyances; methods of enforcing and administering this chapter; and matters of concern to the conveyance industry and to the individual installers, owners, and users of conveyances.

. The advisory committee shall consist of not less than seven persons nor more than nine persons. The director of the department or his or her designee with the advice of the chief elevator inspector shall appoint the committee members as follows:

.. A minimum of one and a maximum of two representatives of licensed elevator contractors;

.. A minimum of one and a maximum of two representatives of elevator mechanics licensed to perform all types of conveyance work;

.. A minimum of one and a maximum of two representatives of owner-employed mechanics exempt from licensing requirements under RCW 70.87.270;

.. One registered architect or professional engineer representative;

.. A minimum of one and a maximum of two building owners or manager representatives;

.. A minimum of one and a maximum of two registered general commercial contractor representatives; and

.. One ad hoc member representing each municipality maintaining jurisdiction of conveyances in accordance with RCW 70.87.200(2).

. The committee members shall serve terms of four years.

. The committee shall meet on the third Tuesday of February, May, August, and November of each year, and at other times at the discretion of the chief elevator inspector. The committee members shall serve without per diem or travel expenses.

. The chief elevator inspector shall be the secretary for the advisory committee.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5471-S.SL.pdf?cite=2019%20c%20151%20§%201[2019 c 151 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5942-S.SL.pdf?cite=2003%20c%20143%20§%207[2003 c 143 § 7]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2629-S.SL.pdf?cite=2002%20c%2098%20§%2011[2002 c 98 § 11]; ]

== 70.87.230 - Conveyance work—Who may perform—Possession of license and identification.
. Except as provided in RCW 70.87.270, a person may not perform conveyance work within the state unless he or she is an elevator mechanic who is regularly employed by and is working: (a) For an owner exempt from licensing requirements under RCW 70.87.270 and performing maintenance; (b) for a public agency performing maintenance; or (c) under the direct supervision of an elevator contractor. A person, firm, public agency, or company is not required to be an elevator contractor for removing or dismantling conveyances that are destroyed as a result of a complete demolition of a secured building or structure or where the building is demolished back to the basic support structure whereby no access is permitted therein to endanger the safety and welfare of a person.

. When performing conveyance work, an elevator mechanic must have his or her license and photo identification in his or her possession. The elevator mechanic must produce his or her license and identification upon request of an authorized representative of the department. The department may establish by rule a requirement that the mechanic also wear and visibly display his or her license.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1055-S.SL.pdf?cite=2009%20c%2036%20§%2010[2009 c 36 § 10]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5942-S.SL.pdf?cite=2003%20c%20143%20§%201[2003 c 143 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2629-S.SL.pdf?cite=2002%20c%2098%20§%2010[2002 c 98 § 10]; ]

== 70.87.240 - Elevator contractor license, elevator mechanic license—Qualifications—Reciprocity.
. Any person, firm, public agency, or company wishing to engage in the business of performing conveyance work within the state must apply for an elevator contractor license with the department on a form provided by the department and be a registered general or specialty contractor under chapter 18.27 RCW.

. Except as provided by RCW 70.87.270, any person wishing to perform conveyance work within the state must apply for an elevator mechanic license with the department on a form provided by the department.

. An elevator contractor license may not be granted to any person or firm who does not possess the following qualifications:

.. Five years' experience performing conveyance work, as verified by current and previous elevator contractors licensed to do business; or

.. Satisfactory completion of a written examination administered by the department on this chapter and the rules adopted under this chapter.

. Except as provided in subsection (5) of this section, RCW 70.87.305, and 70.87.245, an elevator mechanic license may not be granted to any person who does not possess the following qualifications:

.. An acceptable combination of documented experience and education credits: Not less than three years' experience performing conveyance work, as verified by current and previous employers licensed to do business in this state or public agency employers; and

.. Satisfactory completion of a written examination administered by the department on this chapter and the rules adopted under this chapter.

. Any person who furnishes the department with acceptable proof that he or she has performed conveyance work in the category for which a license is sought shall upon making application for a license and paying the license fee receive a license without an examination. The person must have:

.. Worked without direct and immediate supervision for a general or specialty contractor registered under chapter 18.27 RCW and engaged in the business of performing conveyance work in this state. This employment may not be less than each and all of the three years immediately before March 1, 2004. The person must apply within ninety days after the effective date of rules adopted under this chapter establishing licensing requirements;

.. Worked without direct and immediate supervision for an owner exempt from licensing requirements under RCW 70.87.270 or a public agency as an individual responsible for maintenance of conveyances owned by the owner exempt from licensing requirements under RCW 70.87.270 or the public agency. This employment may not be less than each and all of the three years immediately before March 1, 2004. The person must apply within ninety days after the effective date of rules adopted under this chapter establishing licensing requirements; 

.. Obtained a certificate of completion and successfully passed the mechanic examination of a nationally recognized training program for the elevator industry such as the national elevator industry educational program or its equivalent; or

.. Obtained a certificate of completion of an apprenticeship program for an elevator mechanic, having standards substantially equal to those of this chapter, and registered with the Washington state apprenticeship and training council.

. A license must be issued to an individual holding a valid license from a state having entered into a reciprocal agreement with the department and having standards substantially equal to those of this chapter, upon application and without examination.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6650.SL.pdf?cite=2004%20c%2066%20§%202[2004 c 66 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5942-S.SL.pdf?cite=2003%20c%20143%20§%202[2003 c 143 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2629-S.SL.pdf?cite=2002%20c%2098%20§%2012[2002 c 98 § 12]; ]

== 70.87.245 - Material lift mechanic license.
A material lift mechanic license to perform conveyance work on material lifts subject to WAC 296-96-05010 may be granted to any person who possesses the following qualifications:

. The person: (a) Must be employed by an elevator contractor that complies with subsections (2) and (3) of this section; (b) must have successfully completed the training described in subsection (2) of this section; and (c) after successfully completing such training, must have passed a written examination administered by the department that is designed to demonstrate competency with regard to conveyance work on material lifts;

. The employer must provide the persons specified in subsection (1) of this section adequate training, including any training provided by the manufacturer, ensuring worker safety and adherence to the published operating specifications of the conveyance manufacturer; and

. The employer must maintain: (a) A conveyance work log identifying the equipment, describing the conveyance work performed, and identifying the person who performed the conveyance work; (b) a training log describing the course of study applicable to each conveyance and identifying each employee who has successfully completed the training described in subsection (2) of this section and when such training was completed; and (c) a record evidencing that the employer has notified the conveyance owner in writing that the conveyance is not designed to, is not intended to, and should not be used to convey workers.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5942-S.SL.pdf?cite=2003%20c%20143%20§%203[2003 c 143 § 3]; ]

== 70.87.250 - Licenses—Renewals—Fees—Temporary licenses—Continuing education—Records.
. Upon approval of an application, the department may issue a license that is biennially renewable. Each license may include a photograph of the licensee. The fee for the license and for any renewal shall be set by the department in rule.

. The department may issue temporary elevator mechanic licenses. These temporary elevator mechanic licenses will be issued to those certified as qualified and competent by licensed elevator contractors. The company shall furnish proof of competency as the department may require. Each license may include a photograph of the licensee. Each license must recite that it is valid for a period of one year from the date of issuance and for such particular conveyance or geographical areas as the department may designate, and otherwise entitles the licensee to the rights and privileges of an elevator mechanic license issued in this chapter. A temporary elevator mechanic license may be renewed by the department and a fee as established in rule must be charged for any temporary elevator mechanic license or renewal.

. The renewal of all licenses granted under this section is conditioned upon the submission of a certificate of completion of a course designed to ensure the continuing education of licensees on new and existing rules of the department. The course must consist of not less than eight hours of instruction that must be attended and completed within one year immediately preceding any license renewal.

. The courses must be taught by instructors through continuing education providers that may include, but are not limited to, association seminars and labor training programs. The department must approve the continuing education providers. All instructors must be approved by the department and are exempt from the requirements of subsection (3) of this section with regard to his or her application for license renewal, provided that such applicant was qualified as an instructor at any time during the one year immediately preceding the scheduled date for such renewal.

. A licensee who is unable to complete the continuing education course required under this section before the expiration of his or her license due to a temporary disability may apply for a waiver from the department. This will be on a form provided by the department and signed under the pains and penalties of perjury and accompanied by a certified statement from a competent physician attesting to the temporary disability. Upon the termination of the temporary disability, the licensee must submit to the department a certified statement from the same physician, if practicable, attesting to the termination of the temporary disability. At which time a waiver sticker, valid for ninety days, must be issued to the licensee and affixed to his or her license.

. Approved training providers must keep uniform records, for a period of ten years, of attendance of licensees and these records must be available for inspection by the department at its request. Approved training providers are responsible for the security of all attendance records and certificates of completion. However, falsifying or knowingly allowing another to falsify attendance records or certificates of completion constitutes grounds for suspension or revocation of the approval required under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5471-S.SL.pdf?cite=2019%20c%20151%20§%202[2019 c 151 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1055-S.SL.pdf?cite=2009%20c%2036%20§%2011[2009 c 36 § 11]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5942-S.SL.pdf?cite=2003%20c%20143%20§%2021[2003 c 143 § 21]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2629-S.SL.pdf?cite=2002%20c%2098%20§%2013[2002 c 98 § 13]; ]

== 70.87.260 - Liability not limited or assumed by state.
This chapter cannot be construed to relieve or lessen the responsibility or liability of any person, firm, or corporation owning, operating, controlling, testing, inspecting, or performing conveyance work on any conveyance or other related mechanisms covered by this chapter for damages to person or property caused by any defect therein, nor does the state assume any such liability or responsibility therefore or any liability to any person for whatever reason whatsoever by the adoption of this chapter or any acts or omissions arising hereunder.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5942-S.SL.pdf?cite=2003%20c%20143%20§%2022[2003 c 143 § 22]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2629-S.SL.pdf?cite=2002%20c%2098%20§%2014[2002 c 98 § 14]; ]

== 70.87.270 - Exemptions from licensure.
. The licensing requirements of this chapter do not apply to the maintenance of conveyances specified in (a) of this subsection if a person specified in (b) of this subsection performs the maintenance and the owner complies with the requirements specified in (c) and (d) of this subsection.

.. The conveyance: (i) Must be a conveyance other than a passenger elevator to which the general public has access; and (ii) must be located in a facility in which agricultural products are stored, food products are processed, goods are manufactured, energy is generated, or similar industrial or agricultural processes are performed.

.. The person performing the maintenance: (i) Must be regularly employed by the owner; (ii) must have completed the training described in (c) of this subsection; and (iii) must have attained journey level status in an electrical or mechanical trade, but only if the employer has or uses an established journey level program to train its electrical or mechanical trade employees and the employees perform maintenance in the course of their regular employment.

.. The owner must provide the persons specified in (b) of this subsection adequate training to ensure worker safety and adherence to the published operating specifications of the conveyance manufacturer, the applicable provisions of this chapter, and any rules adopted under this chapter.

.. The owner also must maintain both a maintenance log and a training log. The maintenance log must describe maintenance work performed on the conveyance and identify the person who performed the work. The training log must describe the course of study provided to the persons specified in (b) of this subsection, including whether it is general or conveyance specific, and when the persons completed the course of study.

. It is a violation of chapter 49.17 RCW for an owner or an employer: (a) To allow a conveyance exempt from the licensing requirements of this chapter under subsection (1) of this section to be maintained by a person other than a person specified in subsection (1)(b) of this section or a licensee; or (b) to fail to maintain the logs required under subsection (1)(d) of this section.

. The licensing requirements of this chapter do not apply to homeowners, or persons employed by homeowners, for permanent removal of a stairway chair lift or a platform lift located in a private residence as described in the American Society of Mechanical Engineers A18.1 Safety Standard for Platform Lifts and Stairway Chairlifts, Sections 5, 6, and 7.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5471-S.SL.pdf?cite=2019%20c%20151%20§%203[2019 c 151 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5942-S.SL.pdf?cite=2003%20c%20143%20§%204[2003 c 143 § 4]; ]

== 70.87.280 - License categories—Rules.
In order to effectively administer and implement the elevator mechanic licensing of this chapter, the department may establish elevator mechanic license categories in rule.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5942-S.SL.pdf?cite=2003%20c%20143%20§%205[2003 c 143 § 5]; ]

== 70.87.290 - Rules—Effective date.
The department of labor and industries may not adopt rules to implement chapter 98, Laws of 2002, and to implement chapter 143, Laws of 2003 that take effect before March 1, 2004.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5942-S.SL.pdf?cite=2003%20c%20143%20§%206[2003 c 143 § 6]; ]

== 70.87.305 - Private residence conveyances—Licensing requirements—Rules.
. The department shall, by rule, establish licensing requirements for conveyance work performed on private residence conveyances. These rules shall include an exemption from licensing for maintenance work on private residence conveyances performed by an owner or at the direction of the owner, provided the owner resides in the residence at which the conveyance is located and the conveyance is not accessible to the general public. However, maintenance work performed on private residence conveyances located in or at adult family homes licensed under chapter 70.128 RCW, assisted living facilities licensed under chapter 18.20 RCW, or similarly licensed caregiving facilities must comply with the licensing requirements of this chapter.

. The rules adopted under this section take effect July 1, 2004.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2056-S.SL.pdf?cite=2012%20c%2010%20§%2050[2012 c 10 § 50]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6650.SL.pdf?cite=2004%20c%2066%20§%203[2004 c 66 § 3]; ]

== 70.87.310 - Whistleblower—Identity to remain confidential.
. An employee who is a whistleblower and who as a result of being a whistleblower has been subjected to workplace reprisal or retaliatory action has the remedies provided under chapter 49.60 RCW.

. The identity of a whistleblower who reports, in good faith, to the department or to a political subdivision that regulates conveyances, practices that may violate the provisions of this chapter or the rules promulgated hereunder must remain confidential. The provisions of RCW 4.24.500 through 4.24.520, providing certain protections to persons who communicate to government agencies, apply to such reports.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5412-S.SL.pdf?cite=2012%20c%2054%20§%203[2012 c 54 § 3]; ]

