= 70.01 - General provisions.
:toc:

== 70.01.010 - Cooperation with federal government—Construction.
In furtherance of the policy of this state to cooperate with the federal government in the public health programs, the department of health, the state board of health, and the health care authority shall adopt such rules as may become necessary to entitle this state to participate in federal funds unless expressly prohibited by law. Any section or provision of the public health laws of this state which may be susceptible to more than one construction shall be interpreted in favor of the construction most likely to satisfy federal laws entitling this state to receive federal funds for the various programs of public health.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1738-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2015%20§%2081[2011 1st sp.s. c 15 § 81]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1488.SL.pdf?cite=2011%20c%2027%20§%203[2011 c 27 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c213.pdf?cite=1985%20c%20213%20§%2014[1985 c 213 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c25.pdf?cite=1969%20ex.s.%20c%2025%20§%201[1969 ex.s. c 25 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c102.pdf?cite=1967%20ex.s.%20c%20102%20§%2012[1967 ex.s. c 102 § 12]; ]

== 70.01.020 - Donation of blood by person eighteen or over without parental consent authorized.
Any person of the age of eighteen years or over shall be eligible to donate blood in any voluntary and noncompensatory blood program without the necessity of obtaining parental permission or authorization.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c51.pdf?cite=1969%20c%2051%20§%201[1969 c 51 § 1]; ]

== 70.01.030 - Health care fees and charges—Estimate.
. Health care providers licensed under Title 18 RCW and health care facilities licensed under Title 70 RCW shall provide the following to a patient upon request:

.. An estimate of fees and charges related to a specific service, visit, or stay; and

.. Information regarding other types of fees or charges a patient may receive in conjunction with their visit to the provider or facility. Hospitals licensed under chapter 70.41 RCW may fulfill this requirement by providing a statement and contact information as described in RCW 70.41.400.

. Providers and facilities listed in subsection (1) of this section may, after disclosing estimated charges and fees to a patient, refer the patient to the patient's insurer, if applicable, for specific information on the insurer's charges and fees, any cost-sharing responsibilities required of the patient, and the network status of ancillary providers who may or may not share the same network status as the provider or facility.

. Except for hospitals licensed under chapter 70.41 RCW, providers and facilities listed in subsection (1) of this section shall post a sign in patient registration areas containing at least the following language: "Information about the estimated charges of your health services is available upon request. Please do not hesitate to ask for information."

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1869-S.SL.pdf?cite=2009%20c%20529%20§%201[2009 c 529 § 1]; ]

== 70.01.040 - Provider-based clinics that charge a facility fee—Posting of required notice—Reporting requirements.
. Prior to the delivery of nonemergency services, a provider-based clinic that charges a facility fee shall provide a notice to any patient that the clinic is licensed as part of the hospital and the patient may receive a separate charge or billing for the facility component, which may result in a higher out-of-pocket expense.

. Each health care facility must post prominently in locations easily accessible to and visible by patients, including its web site, a statement that the provider-based clinic is licensed as part of the hospital and the patient may receive a separate charge or billing for the facility, which may result in a higher out-of-pocket expense.

. Nothing in this section applies to laboratory services, imaging services, or other ancillary health services not provided by staff employed by the health care facility.

. As part of the year-end financial reports submitted to the department of health pursuant to RCW 43.70.052, all hospitals with provider-based clinics that bill a separate facility fee shall report:

.. The number of provider-based clinics owned or operated by the hospital that charge or bill a separate facility fee;

.. The number of patient visits at each provider-based clinic for which a facility fee was charged or billed for the year;

.. The revenue received by the hospital for the year by means of facility fees at each provider-based clinic; and

.. The range of allowable facility fees paid by public or private payers at each provider-based clinic.

. For the purposes of this section:

.. "Facility fee" means any separate charge or billing by a provider-based clinic in addition to a professional fee for physicians' services that is intended to cover building, electronic medical records systems, billing, and other administrative and operational expenses.

.. "Provider-based clinic" means the site of an off-campus clinic or provider office located at least two hundred fifty yards from the main hospital buildings or as determined by the centers for medicare and medicaid services, that is owned by a hospital licensed under chapter 70.41 RCW or a health system that operates one or more hospitals licensed under chapter 70.41 RCW, is licensed as part of the hospital, and is primarily engaged in providing diagnostic and therapeutic care including medical history, physical examinations, assessment of health status, and treatment monitoring. This does not include clinics exclusively designed for and providing laboratory, X-ray, testing, therapy, pharmacy, or educational services and does not include facilities designated as rural health clinics.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2582-S.SL.pdf?cite=2012%20c%20184%20§%201[2012 c 184 § 1]; ]

== 70.01.050 - Breast cancer—Breast reconstruction and prostheses—Education campaign.
. The health care authority, in coordination with the department of health, must create and implement a campaign to educate breast cancer patients about the availability of insurance coverage for breast reconstruction and breast prostheses.

. The health care authority and department of health may create new educational materials or make available materials published by for-profit or nonprofit organizations. The materials must provide, at a minimum, all of the following:

.. Information about the availability of breast reconstruction surgery following a mastectomy including that the breast reconstruction surgery may be performed at the time of a mastectomy or the breast reconstruction surgery may be delayed until a time after the mastectomy.

.. Information about prostheses or breast forms as alternatives to breast reconstruction surgery.

.. Information about the requirements of the women's health and cancer rights act of 1998 (P.L. 105-277) including the right to breast reconstruction surgery even if the surgery is delayed.

. The educational materials developed or made available under subsection (2) of this section must be distributed by the office of the insurance commissioner and the health care authority to people receiving their services. Distribution may be accomplished through current methods used to inform consumers including posting information online and other methods developed or used by the office of the insurance commissioner and the health care authority.

. The department of health must also make the educational materials developed or made available under subsection (2) of this section available to health care professionals for distribution to patients who may qualify for breast reconstruction surgery following a mastectomy. This may be accomplished through current methods used by the department to provide health care professionals with informational materials, including making them available online.

. This section does not create a private right of action.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5481-S.SL.pdf?cite=2017%20c%2091%20§%201[2017 c 91 § 1]; ]

== 70.01.060 - Eating disorder—Diabetes—Public information availability.
By December 1, 2020, the department of health shall make available on its web site links to existing information related to the condition commonly known as "diabulimia," an eating disorder associated with individuals with type 1 diabetes.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6663-S.SL.pdf?cite=2020%20c%20267%20§%202[2020 c 267 § 2]; ]

