= 70.08 - Combined city-county health departments.
:toc:

== 70.08.005 - Transfer of duties to the department of health.
The powers and duties of the secretary of social and health services under this chapter shall be performed by the secretary of health.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20244[1989 1st ex.s. c 9 § 244]; ]

== 70.08.010 - Combined city-county health departments—Establishment.
Any city with one hundred thousand or more population and the county in which it is located, are authorized, as shall be agreed upon between the respective governing bodies of such city and said county, to establish and operate a combined city and county health department, and to appoint the director of public health.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c124.pdf?cite=1985%20c%20124%20§%201[1985 c 124 § 1]; 1993 c 492 § 244; 1995 c 43 § 16; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c46.pdf?cite=1949%20c%2046%20§%201[1949 c 46 § 1]; Rem. Supp. 1949 § 6099-30; ]

== 70.08.020 - Director of public health—Powers and duties.
The director of public health is authorized to and shall exercise all powers and perform all duties by law vested in the local health officer.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c124.pdf?cite=1985%20c%20124%20§%202[1985 c 124 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c46.pdf?cite=1949%20c%2046%20§%202[1949 c 46 § 2]; Rem. Supp. 1949 § 6099-31; ]

== 70.08.030 - Qualifications.
Notwithstanding any provisions to the contrary contained in any city or county charter, the director of public health, under this chapter shall meet as a minimum one of the following standards of educational achievement and vocational experience to be qualified for appointment to the office:

. Bachelor's degree in business administration, public administration, hospital administration, management, nursing, environmental health, epidemiology, public health, or its equivalent and five years of experience in administration in a community-related field; or

. A graduate degree in any of the fields listed in subsection (1) of this section, or in medicine or osteopathic medicine and surgery, plus three years of administrative experience in a community-related field.

The director shall not engage in the private practice of the director's profession during such tenure of office and shall not be included in the classified civil service of the said city or the said county.

If the director of public health does not meet the qualifications of a health officer or a physician under RCW 70.05.050, the director shall employ a person so qualified to advise the director on medical or public health matters.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1627.SL.pdf?cite=1996%20c%20178%20§%2020[1996 c 178 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c124.pdf?cite=1985%20c%20124%20§%203[1985 c 124 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c25.pdf?cite=1984%20c%2025%20§%203[1984 c 25 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c46.pdf?cite=1949%20c%2046%20§%203[1949 c 46 § 3]; Rem. Supp. 1949 § 6099-32; ]

== 70.08.040 - Director of public health—Appointment.
Notwithstanding any provisions to the contrary contained in any city or county charter, where a combined department is established under this chapter, the director of public health under this chapter shall be appointed by the county executive of the county and the mayor of the city. The appointment shall be effective only upon a majority vote confirmation of the legislative authority of the county and the legislative authority of the city. The director may be removed by the county executive of the county, after consultation with the mayor of the city, upon filing a statement of reasons therefor with the legislative authorities of the county and the city.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1790.SL.pdf?cite=1995%20c%20188%20§%201[1995 c 188 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5253-S.SL.pdf?cite=1995%20c%2043%20§%209[1995 c 43 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c124.pdf?cite=1985%20c%20124%20§%204[1985 c 124 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c57.pdf?cite=1980%20c%2057%20§%201[1980 c 57 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c46.pdf?cite=1949%20c%2046%20§%204[1949 c 46 § 4]; Rem. Supp. 1949 § 6099-33; ]

== 70.08.050 - May act as health officer for other cities or towns.
Nothing in this chapter shall prohibit the director of public health as provided herein from acting as health officer for any other city or town within the county, nor from acting as health officer in any adjoining county or any city or town within such county having a contract or agreement as provided in RCW 70.08.090: PROVIDED, HOWEVER, That before being appointed health officer for such adjoining county, the secretary of health shall first give his or her approval thereto.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20314[1991 c 3 § 314]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%2085[1979 c 141 § 85]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c46.pdf?cite=1949%20c%2046%20§%208[1949 c 46 § 8]; Rem. Supp. 1949 § 6099-37; ]

== 70.08.060 - Director of public health shall be registrar of vital statistics.
The director of public health under this chapter shall be registrar of vital statistics for all cities and counties under his or her jurisdiction and shall conduct such vital statistics work in accordance with the same laws and/or rules and regulations pertaining to vital statistics for a city of the first class.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20372[2012 c 117 § 372]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961ex1c5.pdf?cite=1961%20ex.s.%20c%205%20§%204[1961 ex.s. c 5 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c46.pdf?cite=1949%20c%2046%20§%209[1949 c 46 § 9]; Rem. Supp. 1949 § 6099-38; ]

== 70.08.070 - Employees may be included in civil service or retirement plans of city, county, or combined department.
Notwithstanding any provisions to the contrary contained in any city or county charter, and to the extent provided by the city and the county pursuant to appropriate legislative enactment, employees of the combined city and county health department may be included in the personnel system or civil service and retirement plans of the city or the county or a personnel system for the combined city and county health department that is separate from the personnel system or civil service of either county or city: PROVIDED, That residential requirements for such positions shall be coextensive with the county boundaries: PROVIDED FURTHER, That the city or county is authorized to pay such parts of the expense of operating and maintaining such personnel system or civil service and retirement system and to contribute to the retirement fund in behalf of employees such sums as may be agreed upon between the legislative authorities of such city and county.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c203.pdf?cite=1982%20c%20203%20§%201[1982 c 203 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c57.pdf?cite=1980%20c%2057%20§%202[1980 c 57 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c46.pdf?cite=1949%20c%2046%20§%205[1949 c 46 § 5]; Rem. Supp. 1949 § 6099-34; ]

== 70.08.080 - Pooling of funds.
The city by ordinance, and the county by appropriate legislative enactment, under this chapter may pool all or any part of their respective funds available for public health purposes, in the office of the city treasurer or the office of the county treasurer in a special pooling fund to be established in accordance with agreements between the legislative authorities of said city and county and which shall be expended for the combined health department.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c57.pdf?cite=1980%20c%2057%20§%203[1980 c 57 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c46.pdf?cite=1949%20c%2046%20§%206[1949 c 46 § 6]; Rem. Supp. 1949 § 6099-35; ]

== 70.08.090 - Other cities or agencies may contract for services.
Any other city in said county, other governmental agency or any charitable or health agency may by contract or by agreement with the governing bodies of the combined health department receive public health services.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c46.pdf?cite=1949%20c%2046%20§%207[1949 c 46 § 7]; Rem. Supp. 1949 § 6099-36; ]

== 70.08.100 - Termination of agreement to operate combined city-county health department.
Agreement to operate a combined city and county health department made under this chapter may after two years from the date of such agreement, be terminated by either party at the end of any calendar year upon notice in writing given at least six months prior thereto. The termination of such agreement shall not relieve either party of any obligations to which it has been previously committed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c46.pdf?cite=1949%20c%2046%20§%2010[1949 c 46 § 10]; Rem. Supp. 1949 § 6099-39; ]

== 70.08.110 - Prior expenditures in operating combined health department ratified.
Any expenditures heretofore made by a city of one hundred thousand population or more, and by the county in which it is located, not made fraudulently and which were within the legal limits of indebtedness, towards the expense of maintenance and operation of a combined health department, are hereby legalized and ratified.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c46.pdf?cite=1949%20c%2046%20§%2011[1949 c 46 § 11]; Rem. Supp. 1949 § 6099-40; ]

