= 70.24 - Control and treatment of sexually transmitted diseases.
:toc:

== 70.24.005 - Transfer of duties to the department of health.
The powers and duties of the department of social and health services, the department of licensing, and the secretary of social and health services under this chapter shall be performed by the department of health and the secretary of health.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20247[1989 1st ex.s. c 9 § 247]; ]

== 70.24.015 - Legislative finding.
The legislature declares that sexually transmitted diseases and blood-borne pathogens constitute a serious and sometimes fatal threat to the public and individual health and welfare of the people of the state. The legislature finds that the incidence of sexually transmitted diseases and blood-borne pathogens is rising at an alarming rate and that these diseases result in significant social, health, and economic costs, including infant and maternal mortality, temporary and lifelong disability, and premature death. The legislature further finds that sexually transmitted diseases and blood-borne pathogens, by their nature, involve sensitive issues of privacy, and it is the intent of the legislature that all programs designed to deal with these diseases afford patients privacy, confidentiality, and dignity. The legislature also finds that medical knowledge and information about sexually transmitted diseases and blood-borne pathogens are rapidly changing. It is therefore the intent of the legislature to provide a program that is sufficiently flexible to meet emerging needs, deals efficiently and effectively with reducing the incidence of sexually transmitted diseases and blood-borne pathogens, and provides patients with a secure knowledge that information they provide will remain private and confidential.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1551-S.SL.pdf?cite=2020%20c%2076%20§%201[2020 c 76 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c206.pdf?cite=1988%20c%20206%20§%20901[1988 c 206 § 901]; ]

== 70.24.017 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter:

. "Blood-borne pathogen" means a pathogenic microorganism that is present in human blood and can cause disease in humans, including hepatitis B virus, hepatitis C virus, and human immunodeficiency virus, as well as any other pathogen specified by the board in rule.

. "Board" means the state board of health.

. "Department" means the department of health, or any successor department with jurisdiction over public health matters.

. "Health care facility" means a hospital, nursing home, neuropsychiatric or mental health facility, home health agency, hospice, child care agency, group care facility, family foster home, clinic, blood bank, blood center, sperm bank, laboratory, or other social service or health care institution regulated or operated by the department of health.

. "Health care provider" means any person who is a member of a profession under RCW 18.130.040 or other person providing medical, nursing, psychological, or other health care services regulated by the department of health.

. "Health order" means a written directive issued by the state or local health officer that requires the recipient to take specific action to remove, reduce, control or prevent a risk to public health.

. "Human immunodeficiency virus" or "HIV" means all HIV and HIV-related viruses which damage the cellular branch of the human immune system and leave the person immunodeficient.

. "Legal guardian" means a person appointed by a court to assume legal authority for another who has been found incompetent or, in the case of a minor, a person who has legal custody of the child.

. "Local health officer" has the same meaning as in RCW 70.05.010.

. "Medical treatment" includes treatment for curable diseases and treatment that causes a person to be unable to transmit a disease to others, based upon generally accepted standards of medical and public health science, as specified by the board in rule.

. "Person" includes any natural person, partnership, association, joint venture, trust, public or private corporation, or health facility.

. "Sexually transmitted disease" means a bacterial, viral, fungal, or parasitic infection, determined by the board by rule to be sexually transmitted, to be a threat to the public health and welfare, and to be an infection for which a legitimate public interest will be served by providing for regulation and treatment. The board shall designate chancroid, gonorrhea, granuloma inguinale, lymphogranuloma venereum, genital herpes simplex, chlamydia, trachomitis, genital human papilloma virus infection, syphilis, and human immunodeficiency virus (HIV) infection as sexually transmitted diseases, and shall consider the recommendations and classifications of the centers for disease control and other nationally recognized medical authorities in designating other diseases as sexually transmitted.

. "State health officer" means the secretary of health or an officer appointed by the secretary.

. "Test for a sexually transmitted disease" means a test approved by the board by rule.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1551-S.SL.pdf?cite=2020%20c%2076%20§%202[2020 c 76 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1320-S.SL.pdf?cite=2001%20c%20319%20§%204[2001 c 319 § 4]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20322[1991 c 3 § 322]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c206.pdf?cite=1988%20c%20206%20§%20101[1988 c 206 § 101]; ]

== 70.24.022 - Interviews, examination, counseling, or treatment of infected persons or persons believed to be infected—Dissemination of false information—Penalty.
. The board shall adopt rules authorizing interviews and the state and local public health officers and their authorized representatives may interview, or cause to be interviewed, all persons infected with a sexually transmitted disease and all persons who, in accordance with standards adopted by the board by rule, are reasonably believed to be infected with such diseases for the purpose of investigating the source and spread of the diseases and for the purpose of ordering a person to submit to examination, counseling, or treatment as necessary for the protection of the public health and safety, subject to RCW 70.24.024.

. State and local public health officers or their authorized representatives shall investigate identified partners of persons infected with sexually transmitted diseases in accordance with procedures prescribed by the board.

. All information gathered in the course of contact investigation pursuant to this section shall be considered confidential.

. No person contacted under this section or reasonably believed to be infected with a sexually transmitted disease who reveals the name or names of sexual contacts during the course of an investigation shall be held liable in a civil action for such revelation, unless the revelation is made with a knowing or reckless disregard for the truth.

. Any person who knowingly or maliciously disseminates any false information or report concerning the existence of any sexually transmitted disease under this section is guilty of a gross misdemeanor punishable as provided under RCW 9A.20.021.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c206.pdf?cite=1988%20c%20206%20§%20906[1988 c 206 § 906]; ]

== 70.24.024 - Orders for examinations and counseling—Investigation—Issuance of health order—Notice and hearing—Exception.
. Subject to the provisions of this chapter, the state and local health officers or their authorized representatives may examine and counsel persons reasonably believed to be infected with or to have been exposed to a sexually transmitted disease.

. [Empty]
.. The state or a local health officer may conduct an investigation when:

... He or she knows or has reason to believe that a person in his or her jurisdiction has a sexually transmitted disease and is engaging in specified behavior that endangers the public health; and

... The basis for the health officer's investigation is the officer's direct medical knowledge or reliable testimony of another who is in a position to have direct knowledge of the person's behavior.

.. In conducting the investigation, the health officer shall evaluate the allegations, as well as the reliability and credibility of any person or persons who provided information related to the specified behavior that endangers the public health.

. If the state or local health officer determines upon conclusion of the investigation that the allegations are true and that the person continues to engage in behavior that endangers the public health, the health officer shall document measures taken to protect the public health, including reasonable efforts to obtain the person's voluntary cooperation.

. [Empty]
.. If the measures taken under subsection (3) of this section fail to protect the public health, the state or local health officer may issue a health order requiring the person to:

... Submit to a medical examination or testing, receive counseling, or receive medical treatment, or any combination of these. If ordering a person to receive medical treatment, the health officer must provide the person with at least one additional appropriate option to choose from in the health order; or

... Immediately cease and desist from specified behavior that endangers the public health by imposing such restrictions upon the person as are necessary to prevent the specified behavior that endangers the public health.

.. Any restriction shall be in writing, setting forth the name of the person to be restricted, the initial period of time during which the health order shall remain effective, the terms of the restrictions, and such other conditions as may be necessary to protect the public health. Restrictions shall be imposed in the least-restrictive manner necessary to protect the public health. The period of time during which the health order is effective must be reasonably related to the purpose of the restriction or restrictions contained in the order, up to a maximum period of twelve months.

. [Empty]
.. Upon the issuance of a health order pursuant to subsection (4) of this section, the state or local health officer shall give written notice promptly, personally, and confidentially to the person who is the subject of the order stating the grounds and provisions of the order, including the factual bases therefor, the evidence relied upon for proof of infection and dangerous behavior, and the likelihood of repetition of such behaviors in the absence of such an order. The written notice must inform the person who is the subject of the order that, if he or she contests the order, he or she may file an appeal and appear at a judicial hearing on the enforceability of the order, to be held in superior court. The hearing shall be held within seventy-two hours of receipt of the notice, unless the person subject to the order agrees to comply. If the person contests the order, no invasive medical procedures shall be carried out prior to a hearing being held pursuant to this subsection.

.. The health officer may apply to the superior court for a court order requiring the person to comply with the health order if the person fails to comply with the health order within the time period specified.

.. At a hearing held pursuant to (a) or (b) of this subsection (5), the person subject to the health order may have an attorney appear on his or her behalf at public expense, if necessary. The burden of proof shall be on the health officer to show by clear and convincing evidence that the specified grounds exist for the issuance of the order and for the need for compliance and that the terms and conditions imposed therein are no more restrictive than necessary to protect the public health. Upon conclusion of the hearing, the court shall issue appropriate orders affirming, modifying, or dismissing the health order.

.. If the superior court dismisses the health order, the fact that the order was issued shall be expunged from the records of the department or local department of health.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1551-S.SL.pdf?cite=2020%20c%2076%20§%203[2020 c 76 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c206.pdf?cite=1988%20c%20206%20§%20909[1988 c 206 § 909]; ]

== 70.24.025 - Violations of health order—Penalties.
A person who violates or fails to comply with a health order issued under RCW 70.24.024 is guilty of a gross misdemeanor punishable by confinement until the order has been complied with or terminated, up to a maximum period of three hundred sixty-four days. In lieu of confinement, the court may place the defendant on probation upon condition that the defendant comply with the health order, up to the length of the health order. If the defendant is placed on probation and subsequently violates or fails to comply with the health order, the court shall revoke the probation and reinstate the original sentence of confinement.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1551-S.SL.pdf?cite=2020%20c%2076%20§%204[2020 c 76 § 4]; ]

== 70.24.027 - Intentional transmission of HIV—Penalties.
. It is unlawful for a person who knows that he or she has HIV to have sexual intercourse if:

.. The person has been counseled by a health care provider or public health professional regarding the risk of transmitting HIV to others;

.. The partner or partners exposed to HIV through sexual intercourse did not know that the person had HIV; and

.. The person intended to transmit HIV to the partner.

. It is a defense to a prosecution under this section if:

.. HIV was not transmitted to the partner; or

.. The person took or attempted to take practical means to prevent transmission of HIV.

. [Empty]
.. Except as provided in (b) of this subsection, violation of this section is a misdemeanor punishable as provided in RCW 9A.20.021.

.. Violation of this section is a gross misdemeanor punishable as provided in RCW 9A.20.021 if the person knowingly misrepresented his or her infection status to the partner.

.. Violation of this section does not require registration under RCW 9A.44.130, unless the partner is a child or vulnerable adult victim.

. For purposes of this section, the following terms have the following meanings:

.. "Practical means to prevent transmission" means good faith employment of an activity, behavior, method, or device that is scientifically demonstrated to measurably reduce the risk of transmitting a sexually transmitted disease, including but not limited to: The use of a condom, barrier protection, or other prophylactic device; or good faith participation in a treatment regimen prescribed by a health care provider or public health professional.

.. "Sexual intercourse" has its ordinary meaning and occurs upon any penetration, however slight, of the vagina or anus of one person by the sexual organs of another whether such persons are of the same or another sex.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1551-S.SL.pdf?cite=2020%20c%2076%20§%205[2020 c 76 § 5]; ]

== 70.24.034 - Detention—Grounds—Order—Hearing.
. When the procedures of RCW 70.24.024 have been exhausted and the state or local public health officer, within his or her respective jurisdiction, knows or has reason to believe, because of medical information, that a person has a sexually transmitted disease and that the person continues to engage in behaviors that present an imminent danger to the public health as defined by the board by rule based upon generally accepted standards of medical and public health science, the public health officer may bring an action in superior court to detain the person in a facility designated by the board for a period of time necessary to accomplish a program of counseling and education, excluding any coercive techniques or procedures, designed to get the person to adopt nondangerous behavior. In no case may the period exceed ninety days under each order. The board shall establish, by rule, standards for counseling and education under this subsection. The public health officer shall request the prosecuting attorney to file such action in superior court. During that period, reasonable efforts will be made in a noncoercive manner to get the person to adopt nondangerous behavior.

. If an action is filed as outlined in subsection (1) of this section, the superior court, upon the petition of the prosecuting attorney, shall issue other appropriate court orders including, but not limited to, an order to take the person into custody immediately, for a period not to exceed seventy-two hours, and place him or her in a facility designated or approved by the board. The person who is the subject of the order shall be given written notice of the order promptly, personally, and confidentially, stating the grounds and provisions of the order, including the factual bases therefor, the evidence relied upon for proof of infection and dangerous behavior, and the likelihood of repetition of such behaviors in the absence of such an order, and notifying the person that if he or she refuses to comply with the order he or she may appear at a hearing to review the order and that he or she may have an attorney appear on his or her behalf in the hearing at public expense, if necessary. If the person contests testing or treatment, no invasive medical procedures shall be carried out prior to a hearing being held pursuant to subsection (3) of this section.

. The hearing shall be conducted no later than forty-eight hours after the receipt of the order. The person who is subject to the order has a right to be present at the hearing and may have an attorney appear on his or her behalf in the hearing, at public expense if necessary. If the order being contested includes detention for a period of fourteen days or longer, the person shall also have the right to a trial by jury upon request. Upon conclusion of the hearing or trial by jury, the court shall issue appropriate orders.

The court may continue the hearing upon the request of the person who is subject to the order for good cause shown for no more than five additional judicial days. If a trial by jury is requested, the court, upon motion, may continue the hearing for no more than ten additional judicial days. During the pendency of the continuance, the court may order that the person contesting the order remain in detention or may place terms and conditions upon the person which the court deems appropriate to protect public health.

. The burden of proof shall be on the state or local public health officer to show by clear and convincing evidence that grounds exist for the issuance of any court order pursuant to subsection (2) or (3) of this section. If the superior court dismisses the order, the fact that the order was issued shall be expunged from the records of the state or local department of health.

. Any hearing conducted by the superior court pursuant to subsection (2) or (3) of this section shall be closed and confidential unless a public hearing is requested by the person who is the subject of the order, in which case the hearing will be conducted in open court. Unless in open hearing, any transcripts or records relating thereto shall also be confidential and may be sealed by order of the court.

. Any order entered by the superior court pursuant to subsection (1) or (2) of this section shall impose terms and conditions no more restrictive than necessary to protect the public health.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c206.pdf?cite=1988%20c%20206%20§%20910[1988 c 206 § 910]; ]

== 70.24.050 - Diagnosis of sexually transmitted diseases—Confirmation—Anonymous prevalence reports.
Diagnosis of a sexually transmitted disease in every instance must be confirmed by laboratory tests or examinations in a laboratory approved or conducted in accordance with procedures and such other requirements as may be established by the board. Laboratories testing for HIV shall report anonymous HIV prevalence results to the department, for health statistics purposes, in a manner established by the board.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c206.pdf?cite=1988%20c%20206%20§%20907[1988 c 206 § 907]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c114.pdf?cite=1919%20c%20114%20§%206[1919 c 114 § 6]; RRS § 6105; ]

== 70.24.070 - Detention and treatment facilities.
For the purpose of carrying out this chapter, the board shall have the power and authority to designate facilities for the detention and treatment of persons found to be infected with a sexually transmitted disease and to designate any such facility in any hospital or other public or private institution, other than a jail or correctional facility, having, or which may be provided with, such necessary detention, segregation, isolation, clinic and hospital facilities as may be required and prescribed by the board, and to enter into arrangements for the conduct of such facilities with the public officials or persons, associations, or corporations in charge of or maintaining and operating such institutions.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c206.pdf?cite=1988%20c%20206%20§%20908[1988 c 206 § 908]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c114.pdf?cite=1919%20c%20114%20§%208[1919 c 114 § 8]; RRS § 6107; ]

== 70.24.080 - Penalty.
Except as provided in RCW 70.24.025 and 70.24.027, any person who violates any of the provisions of this chapter or any rule adopted by the board under this chapter, or who fails or refuses to obey any lawful order issued by any state, county or municipal health officer under this chapter shall be deemed guilty of a gross misdemeanor punishable as provided under RCW 9A.20.021.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1551-S.SL.pdf?cite=2020%20c%2076%20§%206[2020 c 76 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c206.pdf?cite=1988%20c%20206%20§%20911[1988 c 206 § 911]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c114.pdf?cite=1919%20c%20114%20§%205[1919 c 114 § 5]; RRS § 6104; ]

== 70.24.084 - Violations of chapter—Aggrieved persons—Right of action.
. Any person aggrieved by a violation of this chapter shall have a right of action in superior court and may recover for each violation:

.. Against any person who negligently violates a provision of this chapter, one thousand dollars, or actual damages, whichever is greater, for each violation.

.. Against any person who intentionally or recklessly violates a provision of this chapter, ten thousand dollars, or actual damages, whichever is greater, for each violation.

.. Reasonable attorneys' fees and costs.

.. Such other relief, including an injunction, as the court may deem appropriate.

. Any action under this chapter is barred unless the action is commenced within three years after the cause of action accrues.

. Nothing in this chapter limits the rights of the subject of a test for a sexually transmitted disease to recover damages or other relief under any other applicable law.

. Nothing in this chapter may be construed to impose civil liability or criminal sanction for disclosure of a test result for a sexually transmitted disease in accordance with any reporting requirement for a diagnosed case of sexually transmitted disease by the department or the centers for disease control of the United States public health service.

. It is a negligent violation of this chapter to cause an unauthorized communication of confidential sexually transmitted disease information by facsimile transmission or otherwise communicating the information to an unauthorized recipient when the sender knew or had reason to know the facsimile transmission telephone number or other transmittal information was incorrect or outdated.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5258.SL.pdf?cite=2001%20c%2016%20§%201[2001 c 16 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1080.SL.pdf?cite=1999%20c%20391%20§%204[1999 c 391 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c206.pdf?cite=1988%20c%20206%20§%20914[1988 c 206 § 914]; ]

== 70.24.090 - Pregnant women—Test for syphilis.
Every physician attending a pregnant woman in the state of Washington during gestation shall, in the case of each woman so attended, take or cause to be taken a sample of blood of such woman at the time of first examination, and submit such sample to an approved laboratory for a standard serological test for syphilis. If the pregnant woman first presents herself for examination after the fifth month of gestation the physician or other attendant shall in addition to the above, advise and urge the patient to secure a medical examination and blood test before the fifth month of any subsequent pregnancies.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c165.pdf?cite=1939%20c%20165%20§%201[1939 c 165 § 1]; RRS § 6002-1; ]

== 70.24.110 - Minors—Treatment, consent, liability for payment for care.
A minor fourteen years of age or older who may have come in contact with any sexually transmitted disease or suspected sexually transmitted disease may give consent to the furnishing of hospital, medical, and surgical care related to the diagnosis or treatment of such disease; and treatment to avoid HIV infection. Such consent shall not be subject to disaffirmance because of minority. The consent of the parent, parents, or legal guardian of such minor shall not be necessary to authorize hospital, medical, and surgical care related to such disease, and such parent, parents, or legal guardian shall not be liable for payment for any care rendered pursuant to this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1551-S.SL.pdf?cite=2020%20c%2076%20§%207[2020 c 76 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c206.pdf?cite=1988%20c%20206%20§%20912[1988 c 206 § 912]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c164.pdf?cite=1969%20ex.s.%20c%20164%20§%201[1969 ex.s. c 164 § 1]; ]

== 70.24.120 - Sexually transmitted disease case investigators—Authority to obtain specimens.
. Disease case investigators, upon specific authorization from a physician or by a physician's standing order, are hereby authorized to gather specimens, including through performance of venipuncture or fingerstick puncture, from a person for the sole purpose of obtaining specimens for use in testing for sexually transmitted diseases, blood-borne pathogens, and other infections as defined by board rule.

. For the purposes of this section:

.. "Disease case investigator" means only those persons who:

... Are employed by public health authorities; and

... Have been trained by a physician in proper procedures to be employed when collecting specimens, including blood, in accordance with training requirements established by the department of health; and

... Possess a statement signed by the instructing physician that the training required by (a)(ii) of this subsection has been successfully completed.

.. "Physician" means any person licensed under the provisions of chapters 18.57 or 18.71 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1551-S.SL.pdf?cite=2020%20c%2076%20§%208[2020 c 76 § 8]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20324[1991 c 3 § 324]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c206.pdf?cite=1988%20c%20206%20§%20913[1988 c 206 § 913]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977c59.pdf?cite=1977%20c%2059%20§%201[1977 c 59 § 1]; ]

== 70.24.130 - Adoption of rules.
. The board shall adopt such rules as are necessary to implement and enforce this chapter, including, but not limited to, rules:

.. Establishing procedures for taking appropriate action, in addition to any other penalty under this chapter, with regard to health care facilities or health care providers that violate this chapter or the rules adopted under this chapter;

.. Prescribing stringent safeguards to protect the confidentiality of the persons and records subject to this chapter, consistent with chapter 70.02 RCW;

.. Establishing reporting requirements for sexually transmitted diseases;

.. Establishing procedures for investigations under RCW 70.24.024;

.. Specifying, for purposes of RCW 70.24.024, behavior that endangers the public health, based upon generally accepted standards of medical and public health science;

.. Defining, for the purposes of RCW 70.24.120, specimens that can be obtained and tests that can be administered for sexually transmitted diseases, blood-borne pathogens, and other infections;

.. Determining, for purposes of RCW 70.24.340, categories of employment that are at risk of substantial exposure to a blood-borne pathogen; and

.. Defining, for purposes of RCW 70.24.340, 70.24.360, and 70.24.370, what constitutes an exposure that presents a possible risk of transmission of a blood-borne pathogen.

. In addition to any rules adopted by the board, the department may adopt any rules necessary to implement and enforce this chapter.

. The procedures set forth in chapter 34.05 RCW apply to the administration of this chapter, except that in case of conflict between chapter 34.05 RCW and this chapter, the provisions of this chapter shall control.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1551-S.SL.pdf?cite=2020%20c%2076%20§%209[2020 c 76 § 9]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20325[1991 c 3 § 325]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c206.pdf?cite=1988%20c%20206%20§%20915[1988 c 206 § 915]; ]

== 70.24.150 - Immunity of certain public employees.
Members of the state board of health and local boards of health, public health officers, and employees of the department of health and local health departments are immune from civil action for damages arising out of the good faith performance of their duties as prescribed by this chapter, unless such performance constitutes gross negligence.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20326[1991 c 3 § 326]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c206.pdf?cite=1988%20c%20206%20§%20918[1988 c 206 § 918]; ]

== 70.24.220 - Sexually transmitted disease education in public schools—Finding.
The legislature finds that the public schools provide a unique and appropriate setting for educating young people about the pathology and prevention of sexually transmitted diseases. The legislature recognizes that schools and communities vary throughout the state and that locally elected school directors should have a significant role in establishing a program of sexually transmitted disease education in their districts, consistent with RCW 28A.230.020 and 28A.300.475.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1551-S.SL.pdf?cite=2020%20c%2076%20§%2010[2020 c 76 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c206.pdf?cite=1988%20c%20206%20§%20401[1988 c 206 § 401]; ]

== 70.24.290 - Public school employees—Rules for blood-borne pathogens education and training.
The superintendent of public instruction shall adopt rules that require appropriate education and training, to be included as part of their present continuing education requirements, for public school employees on the prevention, transmission, and treatment of blood-borne pathogens. The superintendent of public instruction, in consultation with the department of health, shall develop the educational and training material necessary for school employees.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1551-S.SL.pdf?cite=2020%20c%2076%20§%2011[2020 c 76 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c206.pdf?cite=1988%20c%20206%20§%20606[1988 c 206 § 606]; ]

== 70.24.325 - Testing—Insurance requirements.
. This section shall apply to consent for blood-borne pathogen testing administered as part of an application for coverage authorized under Title 48 RCW.

. Persons subject to regulation under Title 48 RCW who are requesting an insured, a subscriber, or a potential insured or subscriber to furnish the results of a blood-borne pathogen test for underwriting purposes as a condition for obtaining or renewing coverage under an insurance contract, health care service contract, or health maintenance organization agreement shall:

.. Provide written information to the individual prior to being tested which explains which blood-borne pathogen test is being administered; and that the purpose of blood-borne pathogen testing in this setting is to determine eligibility for coverage.

.. Obtain informed specific written consent for the blood-borne pathogen test or tests. The written informed consent shall include an explanation of the confidential treatment of the test results which limits access to the results to persons involved in handling or determining applications for coverage or claims of the applicant or claimant.

.. Establish procedures to inform an applicant of the following:

... That the applicant may designate a health care provider or health care agency to whom the insurer, the health care service contractor, or health maintenance organization will provide test results indicative of infection with a blood-borne pathogen for interpretation; and

... That test results indicative of infection with a blood-borne pathogen will be sent directly to the applicant.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1551-S.SL.pdf?cite=2020%20c%2076%20§%2012[2020 c 76 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c387.pdf?cite=1989%20c%20387%20§%201[1989 c 387 § 1]; ]

== 70.24.340 - Employees' substantial exposure to bodily fluids—Procedure and court orders.
A law enforcement officer, firefighter, health care provider, health care facility staff person, department of corrections' staff person, jail staff person, or person employed in other categories of employment to be at risk of exposure that presents a possible risk of transmission of a blood-borne pathogen, who has experienced an exposure to another person's bodily fluids in the course of his or her employment, may request a state or local health officer to order blood-borne pathogen testing for the person whose bodily fluids he or she has been exposed to. If the state or local health officer refuses to order testing under this section, the person who made the request may petition the superior court for a hearing to determine whether an order shall be issued. The hearing on the petition shall be held within seventy-two hours of filing the petition, exclusive of Saturdays, Sundays, and holidays. The standard of review to determine whether the state or local health officer shall be required to issue the order is whether an exposure occurred and whether that exposure presents a possible risk of transmission of a blood-borne pathogen. Upon conclusion of the hearing, the court shall issue the appropriate order.

The person who is subject to the state or local health officer's order to receive testing shall be given written notice of the order promptly, personally, and confidentially, stating the grounds and provisions of the order, including the factual basis therefor. If the person who is subject to the order refuses to comply, the state or local health officer may petition the superior court for a hearing. The hearing on the petition shall be held within seventy-two hours of filing the petition, exclusive of Saturdays, Sundays, and holidays. The standard of review for the order is whether an exposure occurred and whether that exposure presents a possible risk of transmission of a blood-borne pathogen. Upon conclusion of the hearing, the court shall issue the appropriate order.

The state or local health officer shall perform testing under this section if he or she finds that the exposure presents a possible risk of transmission of a blood-borne pathogen or if he or she is ordered to do so by a court.

The testing required under this section shall be completed as soon as possible after the substantial exposure or, if ordered by the court, within seventy-two hours of the order's issuance.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1551-S.SL.pdf?cite=2020%20c%2076%20§%2013[2020 c 76 § 13]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1454.SL.pdf?cite=2011%20c%20232%20§%202[2011 c 232 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1605-S.SL.pdf?cite=1997%20c%20345%20§%203[1997 c 345 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c206.pdf?cite=1988%20c%20206%20§%20703[1988 c 206 § 703]; ]

== 70.24.360 - Jail detainees—Testing of persons who present a possible risk.
Jail administrators, with the approval of the local health officer, may order blood-borne pathogen testing for a person detained in the jail if the local health officer determines that the detainee's behavior exposed the staff, general public, or other persons, and that exposure presents a possible risk of transmitting a blood-borne pathogen. Documentation of the behavior shall be reviewed with the person to ensure that the person understands the basis for testing.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1551-S.SL.pdf?cite=2020%20c%2076%20§%2014[2020 c 76 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c206.pdf?cite=1988%20c%20206%20§%20706[1988 c 206 § 706]; ]

== 70.24.370 - Correction facility inmates—Testing—Procedure.
. The chief medical officer of the department of corrections may order blood-borne pathogen testing for an inmate if the chief medical officer or his or her designee determines that the inmate's behavior exposed the staff, general public, or other inmates, and that exposure presents a possible risk of transmitting a blood-borne pathogen. The department of corrections shall establish a procedure to document the exposure that presents a possible risk of transmitting a blood-borne pathogen which is the basis for the testing. The chief medical officer, or his or her designee, shall review the exposure that presents a possible risk of transmitting a blood-borne pathogen in the documentation of the behavior with the inmate to ensure that he or she understands the basis for the testing.

. Administrative hearing requirements set forth in chapter 34.05 RCW do not apply to the procedure developed by the department of corrections pursuant to this section. This section shall not be construed as requiring any hearing process except as may be required under existing federal constitutional law.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1551-S.SL.pdf?cite=2020%20c%2076%20§%2015[2020 c 76 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c206.pdf?cite=1988%20c%20206%20§%20707[1988 c 206 § 707]; ]

== 70.24.400 - Funding for office on AIDS—Center for AIDS education—Department's duties for awarding grants.
. The secretary of health shall direct that all state or federal funds, excluding those from federal Title XIX for services or other activities authorized in this chapter, shall be allocated to the office on AIDS established in *RCW 70.24.250. The secretary shall further direct that all funds for services and activities specified in subsection (4) of this section shall be provided by the department directly to public and private providers in the communities.

. Efforts shall be made by both the counties and the department to use existing service delivery systems, where possible.

. The University of Washington health science program, in cooperation with the office on AIDS, may, within available resources, establish a center for AIDS education. The center for AIDS education is not intended to engage in state-funded research related to HIV infection, AIDS, or HIV-related conditions. Its duties shall include providing the office on AIDS with the appropriate educational materials necessary to carry out that office's duties.

. The department shall develop standards and criteria for awarding grants to support testing, counseling, education, case management, notification of sexual partners of infected persons, planning, coordination, and other services required by law. In addition, funds shall be allocated for intervention strategies specifically addressing groups that are at a high risk of being infected with the human immunodeficiency virus.

. The department shall reflect in its departmental biennial budget request the funds necessary to implement this section.

. The use of appropriate materials may be authorized by the department in the prevention or control of HIV infection.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2360.SL.pdf?cite=2010%201st%20sp.s.%20c%203%20§%201[2010 1st sp.s. c 3 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%20126[1998 c 245 § 126]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20327[1991 c 3 § 327]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c206.pdf?cite=1988%20c%20206%20§%20801[1988 c 206 § 801]; ]

== 70.24.420 - Additional local funding of treatment programs not required.
Nothing in this chapter may be construed to require additional local funding of programs to treat communicable disease established as of March 23, 1988.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c206.pdf?cite=1988%20c%20206%20§%20919[1988 c 206 § 919]; ]

== 70.24.430 - Application of chapter to persons subject to jurisdiction of department of corrections.
Nothing in this chapter is intended to create a state-mandated liberty interest of any nature for offenders or inmates confined in department of corrections facilities or subject to the jurisdiction of the department of corrections.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c206.pdf?cite=1988%20c%20206%20§%20920[1988 c 206 § 920]; ]

== 70.24.450 - Confidentiality—Reports—Unauthorized disclosures.
. In order to assure compliance with the protections under this chapter and the rules of the board, and to assure public confidence in the confidentiality of reported information, the department shall:

.. Report annually to the board any incidents of unauthorized disclosure by the department, local health departments, or their employees of information protected under RCW 70.02.220. The report shall include recommendations for preventing future unauthorized disclosures and improving the system of confidentiality for reported information; and

.. Assist health care providers, facilities that conduct tests, local health departments, and other persons involved in disease reporting to understand, implement, and comply with this chapter and the rules of the board related to disease reporting.

. This section is exempt from RCW 70.24.084, 70.05.070, and 70.05.120.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1679-S.SL.pdf?cite=2013%20c%20200%20§%2027[2013 c 200 § 27]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1080.SL.pdf?cite=1999%20c%20391%20§%203[1999 c 391 § 3]; ]

== 70.24.901 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%20150[2009 c 521 § 150]; ]

