= 70.90 - Water recreation facilities.
:toc:

== 70.90.101 - Legislative findings.
The legislature finds that water recreation facilities are an important source of recreation for the citizens of this state. To promote the public health, safety, and welfare, the legislature finds it necessary to continue to regulate these facilities.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c222.pdf?cite=1987%20c%20222%20§%201[1987 c 222 § 1]; ]

== 70.90.110 - Definitions.
Unless the context clearly requires otherwise the definitions in this section apply throughout this chapter.

. "Water recreation facility" means any artificial basin or other structure containing water used or intended to be used for recreation, bathing, relaxation, or swimming, where body contact with the water occurs or is intended to occur and includes auxiliary buildings and appurtenances. The term includes, but is not limited to:

.. Conventional swimming pools, wading pools, and spray pools;

.. Recreational water contact facilities as defined in this chapter;

.. Spa pools and tubs using hot water, cold water, mineral water, air induction, or hydrojets; and

.. Any area designated for swimming in natural waters with artificial boundaries within the waters.

. "Recreational water contact facility" means an artificial water associated facility with design and operational features that provide patron recreational activity which is different from that associated with a conventional swimming pool and purposefully involves immersion of the body partially or totally in the water, and that includes but is not limited to, water slides, wave pools, and water lagoons.

. "Local health officer" means the health officer of the city, county, or city-county department or district or a representative authorized by the local health officer.

. "Secretary" means the secretary of health.

. "Person" means an individual, firm, partnership, co- partnership, corporation, company, association, club, government entity, or organization of any kind.

. "Department" means the department of health.

. "Board" means the state board of health.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20352[1991 c 3 § 352]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c222.pdf?cite=1987%20c%20222%20§%202[1987 c 222 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c236.pdf?cite=1986%20c%20236%20§%202[1986 c 236 § 2]; ]

== 70.90.120 - Adoption of rules governing safety, sanitation, and water quality—Exceptions.
. The board shall adopt rules under the administrative procedure act, chapter 34.05 RCW, governing safety, sanitation, and water quality for water recreation facilities. The rules shall include but not be limited to requirements for design; operation; injury and illness reporting; biological and chemical contamination standards; water quality monitoring; inspection; permit application and issuance; and enforcement procedures. However, a water recreation facility intended for the exclusive use of residents of any apartment house complex or of a group of rental housing units of less than fifteen living units, or of a mobile home park, or of a condominium complex or any group or association of less than fifteen homeowners shall not be subject to preconstruction design review, routine inspection, or permit or fee requirements; and water treatment of hydroelectric reservoirs or natural streams, creeks, lakes, or irrigation canals shall not be required.

. In adopting rules under subsection (1) of this section regarding the operation or design of a recreational water contact facility, the board shall review and consider the most recent version of the United States centers for disease control and prevention's model aquatic health code.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1449.SL.pdf?cite=2017%20c%20102%20§%201[2017 c 102 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c222.pdf?cite=1987%20c%20222%20§%205[1987 c 222 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c236.pdf?cite=1986%20c%20236%20§%203[1986 c 236 § 3]; ]

== 70.90.125 - Regulation by local boards of health.
Nothing in this chapter shall prohibit any local board of health from establishing and enforcing any provisions governing safety, sanitation, and water quality for any water recreation facility, regardless of ownership or use, in addition to those rules established by the state board of health under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c222.pdf?cite=1987%20c%20222%20§%206[1987 c 222 § 6]; ]

== 70.90.140 - Enforcement.
The secretary shall enforce the rules adopted under this chapter. The secretary may develop joint plans of responsibility with any local health jurisdiction to administer this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c236.pdf?cite=1986%20c%20236%20§%205[1986 c 236 § 5]; ]

== 70.90.150 - Fees.
. Local health officers may establish and collect fees sufficient to cover their costs incurred in carrying out their duties under this chapter and the rules adopted under this chapter.

. The department may establish and collect fees sufficient to cover its costs incurred in carrying out its duties under this chapter. The fees shall be deposited in the state general fund.

. A person shall not be required to submit fees at both the state and local levels.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c236.pdf?cite=1986%20c%20236%20§%206[1986 c 236 § 6]; ]

== 70.90.160 - Modification or construction of facility—Permit required—Submission of plans.
A permit is required for any modification to or construction of any recreational water contact facility after June 11, 1986, and for any other water recreation facility after July 26, 1987. Water recreation facilities existing on July 26, 1987, which do not comply with the design and construction requirements established by the state board of health under this chapter may continue to operate without modification to or replacement of the existing physical plant, provided the water quality, sanitation, and lifesaving equipment are in compliance with the requirements established under this chapter. However, if any modifications are made to the physical plant of an existing water recreation facility the modifications shall comply with the requirements established under this chapter. The plans and specifications for the modification or construction shall be submitted to the applicable local authority or the department as applicable, but a person shall not be required to submit plans at both the state and local levels or apply for both a state and local permit. The plans shall be reviewed and may be approved or rejected or modifications or conditions imposed consistent with this chapter as the public health or safety may require, and a permit shall be issued or denied within thirty days of submittal.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c222.pdf?cite=1987%20c%20222%20§%207[1987 c 222 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c236.pdf?cite=1986%20c%20236%20§%207[1986 c 236 § 7]; ]

== 70.90.170 - Operating permit—Renewal.
An operating permit from the department or local health officer, as applicable, is required for each water recreation facility operated in this state. The permit shall be renewed annually. The permit shall be conspicuously displayed at the water recreation facility.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c222.pdf?cite=1987%20c%20222%20§%208[1987 c 222 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c236.pdf?cite=1986%20c%20236%20§%208[1986 c 236 § 8]; ]

== 70.90.180 - State and local health jurisdictions—Chapter not basis for liability.
Nothing in this chapter or the rules adopted under this chapter creates or forms the basis for any liability: (1) On the part of the state and local health jurisdictions, or their officers, employees, or agents, for any injury or damage resulting from the failure of the owner or operator of water recreation facilities to comply with this chapter or the rules adopted under this chapter; or (2) by reason or in consequence of any act or omission in connection with the implementation or enforcement of this chapter or the rules adopted under this chapter on the part of the state and local health jurisdictions, or by their officers, employees, or agents.

All actions of local health officers and the secretary shall be deemed an exercise of the state's police power.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c222.pdf?cite=1987%20c%20222%20§%209[1987 c 222 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c236.pdf?cite=1986%20c%20236%20§%209[1986 c 236 § 9]; ]

== 70.90.190 - Reporting of injury, disease, or death.
Any person operating a water recreation facility shall report to the local health officer or the department any serious injury, communicable disease, or death occurring at or caused by the water recreation facility.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c222.pdf?cite=1987%20c%20222%20§%2010[1987 c 222 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c236.pdf?cite=1986%20c%20236%20§%2010[1986 c 236 § 10]; ]

== 70.90.200 - Civil penalties.
County, city, or town legislative authorities and the secretary, as applicable, may establish civil penalties for a violation of this chapter or the rules adopted under this chapter not to exceed five hundred dollars. Each day upon which a violation occurs constitutes a separate violation. A person violating this chapter may be enjoined from continuing the violation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c236.pdf?cite=1986%20c%20236%20§%2011[1986 c 236 § 11]; ]

== 70.90.205 - Criminal penalties.
The violation of any provisions of this chapter and any rules adopted under this chapter shall be a misdemeanor punishable by a fine of not more than five hundred dollars.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c222.pdf?cite=1987%20c%20222%20§%2011[1987 c 222 § 11]; ]

== 70.90.210 - Adjudicative proceeding—Notice.
. Any person aggrieved by an order of the department or by the imposition of a civil fine by the department has the right to an adjudicative proceeding. RCW 43.70.095 governs department notice of a civil fine and a person's right to an adjudicative proceeding.

. Any person aggrieved by an order of a local health officer or by the imposition of a civil fine by the officer has the right to appeal. The hearing is governed by the local health jurisdiction's administrative appeals process. Notice shall be provided by the local health jurisdiction consistent with its due process requirements.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20354[1991 c 3 § 354]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%20130[1989 c 175 § 130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c236.pdf?cite=1986%20c%20236%20§%2012[1986 c 236 § 12]; ]

== 70.90.230 - Insurance required.
. A recreational water contact facility shall not be operated within the state unless the owner or operator has purchased insurance in an amount not less than one hundred thousand dollars against liability for bodily injury to or death of one or more persons in any one accident arising out of the use of the recreational water contact facility.

. The board may require a recreational water contact facility to purchase insurance in addition to the amount required in subsection (1) of this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c236.pdf?cite=1986%20c%20236%20§%2014[1986 c 236 § 14]; ]

== 70.90.240 - Sale of spas, pools, and tubs—Operating instructions and health caution required.
Every seller of spas, pools and tubs under RCW 70.90.110(1) (a) and (c) shall furnish to the purchaser a complete set of operating instructions which shall include detailed instructions on the safe use of the spa, pool, or tub and for the proper treatment of water to reduce health risks to the purchaser. Included in the instructions shall be information about the health effects of hot water and a specific caution and explanation of the health effects of hot water on pregnant women.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c222.pdf?cite=1987%20c%20222%20§%204[1987 c 222 § 4]; ]

== 70.90.250 - Application of chapter.
This chapter applies to all water recreation facilities regardless of whether ownership is public or private and regardless of whether the intended use is commercial or private, except that this chapter shall not apply to:

. Any water recreation facility for the sole use of residents and invited guests at a single-family dwelling;

. Therapeutic water facilities operated exclusively for physical therapy;

. Steam baths and saunas; and

. Inflatable equipment operated at a temporary event, including inflatable water slides, that do not allow water to pool more than six inches and do not recirculate water.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1449.SL.pdf?cite=2017%20c%20102%20§%202[2017 c 102 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c222.pdf?cite=1987%20c%20222%20§%203[1987 c 222 § 3]; ]

