= 70.74 - Washington state explosives act.
:toc:

== 70.74.010 - Definitions.
As used in this chapter, unless a different meaning is plainly required by the context:

. The terms "authorized," "approved," or "approval" shall be held to mean authorized, approved, or approval by the department of labor and industries.

. The term "blasting agent" shall be held to mean and include any material or mixture consisting of a fuel and oxidizer, that is intended for blasting and not otherwise defined as an explosive; if the finished product, as mixed for use or shipment, cannot be detonated by means of a number 8 test blasting cap when unconfined. A number 8 test blasting cap is one containing two grams of a mixture of eighty percent mercury fulminate and twenty percent potassium chlorate, or a blasting cap of equivalent strength. An equivalent strength cap comprises 0.40-0.45 grams of PETN base charge pressed in an aluminum shell with bottom thickness not to exceed 0.03 of an inch, to a specific gravity of not less than 1.4 g/cc., and primed with standard weights of primer depending on the manufacturer.

. The term "dealer" shall be held to mean and include any person who purchases explosives or blasting agents for the sole purpose of resale, and not for use or consumption.

. The term "efficient artificial barricade" shall be held to mean an artificial mound or properly revetted wall of earth of a minimum thickness of not less than three feet or such other artificial barricade as approved by the department of labor and industries.

. The term "explosive" or "explosives" whenever used in this chapter, shall be held to mean and include any chemical compound or mechanical mixture that is commonly used or intended for the purpose of producing an explosion, that contains any oxidizing and combustible units, or other ingredients, in such proportions, quantities, or packing, that an ignition by fire, by friction, by concussion, by percussion, or by detonation of any part of the compound or mixture may cause such a sudden generation of highly heated gases that the resultant gaseous pressures are capable of producing destructive effects on contiguous objects or of destroying life or limb. In addition, the term "explosives" shall include all material which is classified as division 1.1, 1.2, 1.3, 1.4, 1.5, or 1.6 explosives by the United States department of transportation. For the purposes of this chapter, small arms ammunition, small arms ammunition primers, smokeless powder not exceeding fifty pounds, and black powder not exceeding five pounds shall not be defined as explosives, unless possessed or used for a purpose inconsistent with small arms use or other lawful purpose.

. Classification of explosives shall include, but not be limited to, the following:

.. DIVISION 1.1 and 1.2 EXPLOSIVES: Possess mass explosion or detonating hazard and include dynamite, nitroglycerin, picric acid, lead azide, fulminate of mercury, black powder exceeding five pounds, blasting caps in quantities of 1001 or more, and detonating primers.

.. DIVISION 1.3 EXPLOSIVES: Possess a minor blast hazard, a minor projection hazard, or a flammable hazard and include propellant explosives, including smokeless powder exceeding fifty pounds.

.. DIVISION 1.4, 1.5, and 1.6 EXPLOSIVES: Include certain types of manufactured articles which contain division 1.1, 1.2, or 1.3 explosives, or all, as components, but in restricted quantities, and also include blasting caps in quantities of 1000 or less.

. The term "explosive-actuated power devices" shall be held to mean any tool or special mechanized device which is actuated by explosives, but not to include propellant-actuated power devices.

. The term "explosives manufacturing building," shall be held to mean and include any building or other structure (excepting magazines) containing explosives, in which the manufacture of explosives, or any processing involving explosives, is carried on, and any building where explosives are used as a component part or ingredient in the manufacture of any article or device.

. The term "explosives manufacturing plant" shall be held to mean and include all lands, with the buildings situated thereon, used in connection with the manufacturing or processing of explosives or in which any process involving explosives is carried on, or the storage of explosives thereat, as well as any premises where explosives are used as a component part or ingredient in the manufacture of any article or device.

. The term "forbidden or not acceptable explosives" shall be held to mean and include explosives which are forbidden or not acceptable for transportation by common carriers by rail freight, rail express, highway, or water in accordance with the regulations of the federal department of transportation.

. The term "fuel" shall be held to mean and include a substance which may react with the oxygen in the air or with the oxygen yielded by an oxidizer to produce combustion.

. The term "handloader" shall be held to mean and include any person who engages in the noncommercial assembling of small arms ammunition for his or her own use, specifically the operation of installing new primers, powder, and projectiles into cartridge cases.

. The term "handloader components" means small arms ammunition, small arms ammunition primers, smokeless powder not exceeding fifty pounds, and black powder as used in muzzle loading firearms not exceeding five pounds.

. The term "highway" shall be held to mean and include any public street, public alley, or public road, including a privately financed, constructed, or maintained road that is regularly and openly traveled by the general public.

. The term "improvised device" means a device which is fabricated with explosives or destructive, lethal, noxious, pyrotechnic, or incendiary chemicals and which is designed, or has the capacity, to disfigure, destroy, distract, or harass.

. The term "inhabited building," shall be held to mean and include only a building regularly occupied in whole or in part as a habitation for human beings, or any church, schoolhouse, railroad station, store, or other building where people are accustomed to assemble, other than any building or structure occupied in connection with the manufacture, transportation, storage, or use of explosives.

. The term "magazine," shall be held to mean and include any building or other structure, other than an explosives manufacturing building, used for the storage of explosives.

. The term "motor vehicle" shall be held to mean and include any self-propelled automobile, truck, tractor, semi-trailer or full trailer, or other conveyance used for the transportation of freight.

. The term "natural barricade" shall be held to mean and include any natural hill, mound, wall, or barrier composed of earth or rock or other solid material of a minimum thickness of not less than three feet.

. The term "oxidizer" shall be held to mean a substance that yields oxygen readily to stimulate the combustion of organic matter or other fuel.

. The term "person" shall be held to mean and include any individual, firm, partnership, corporation, company, association, society, joint stock company, joint stock association, and including any trustee, receiver, assignee, or personal representative thereof.

. The term "propellant-actuated power device" shall be held to mean and include any tool or special mechanized device or gas generator system which is actuated by a propellant or which releases and directs work through a propellant charge.

. The term "public conveyance" shall be held to mean and include any railroad car, streetcar, ferry, cab, bus, airplane, or other vehicle which is carrying passengers for hire.

. The term "public utility transmission system" shall mean power transmission lines over 10 KV, telephone cables, or microwave transmission systems, or buried or exposed pipelines carrying water, natural gas, petroleum, or crude oil, or refined products and chemicals, whose services are regulated by the utilities and transportation commission, municipal, or other publicly owned systems.

. The term "purchaser" shall be held to mean any person who buys, accepts, or receives any explosives or blasting agents.

. The term "pyrotechnic" shall be held to mean and include any combustible or explosive compositions or manufactured articles designed and prepared for the purpose of producing audible or visible effects which are commonly referred to as fireworks as defined in chapter 70.77 RCW.

. The term "railroad" shall be held to mean and include any steam, electric, or other railroad which carries passengers for hire.

. The term "small arms ammunition" shall be held to mean and include any shotgun, rifle, pistol, or revolver cartridge, and cartridges for propellant-actuated power devices and industrial guns. Military-type ammunition containing explosive bursting charges, incendiary, tracer, spotting, or pyrotechnic projectiles is excluded from this definition.

. The term "small arms ammunition primers" shall be held to mean small percussion-sensitive explosive charges encased in a cup, used to ignite propellant powder and shall include percussion caps as used in muzzle loaders.

. The term "smokeless powder" shall be held to mean and include solid chemicals or solid chemical mixtures in excess of fifty pounds which function by rapid combustion.

. The term "user" shall be held to mean and include any natural person, manufacturer, or blaster who acquires, purchases, or uses explosives as an ultimate consumer or who supervises such use.

Words used in the singular number shall include the plural, and the plural the singular.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20390[2012 c 117 § 390]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%201[2002 c 370 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1118-S.SL.pdf?cite=1993%20c%20293%20§%201[1993 c 293 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c88.pdf?cite=1972%20ex.s.%20c%2088%20§%205[1972 ex.s. c 88 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c72.pdf?cite=1970%20ex.s.%20c%2072%20§%201[1970 ex.s. c 72 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%203[1969 ex.s. c 137 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1931c111.pdf?cite=1931%20c%20111%20§%201[1931 c 111 § 1]; RRS § 5440-1; ]

== 70.74.013 - Funds collected by department.
All funds collected by the department under RCW 70.74.137 through 70.74.146 and 70.74.360 shall be transferred to the state treasurer for deposit into the accident and medical aid funds under RCW 51.44.010 and 51.44.020.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3381.SL.pdf?cite=2008%20c%20285%20§%2011[2008 c 285 § 11]; ]

== 70.74.020 - Restrictions on manufacture, sale, or storage—Users—Reports on storage—Waiver.
. No person shall manufacture, possess, store, sell, purchase, transport, or use explosives or blasting agents except in compliance with this chapter.

. The director of the department of labor and industries shall make and promulgate rules and regulations concerning qualifications of users of explosives and shall have the authority to issue licenses for users of explosives to effectuate the purpose of this chapter: PROVIDED, That where there is a finding by the director that the use or disposition of explosives in any class of industry presents no unusual hazard to the safety of life or limb of persons employed therewith, and where the users are supervised by a superior in an employment relationship who is sufficiently experienced in the use of explosives, and who possesses a license for such use under this chapter, the director in his or her discretion may exclude said users in those classes of industry from individual licensing.

. The director of the department of labor and industries shall make and promulgate rules and regulations concerning the manufacture, sale, purchase, use, transportation, storage, and disposal of explosives, and shall have the authority to issue licenses for the manufacture, purchase, sale, use, transportation, and storage of explosives to effectuate the purpose of this chapter. The director of the department of labor and industries is hereby delegated the authority to grant written waiver of this chapter whenever it can be shown that the manufacturing, handling, or storing of explosives are in compliance with applicable national or federal explosive safety standards: PROVIDED, That any resident of this state who is qualified to purchase explosives in this state and who has complied with the provisions of this chapter applicable to him or her may purchase explosives from an authorized dealer of a bordering state and may transport said explosives into this state for use herein: PROVIDED FURTHER, That residents of this state shall, within ten days of the date of purchase, present to the department of labor and industries a report signed by both vendor and vendee of every purchase from an out of state dealer, said report indicating the date of purchase, name of vendor, vendor's license number, vendor's business address, amount and kind of explosives purchased, the name of the purchaser, the purchaser's license number, and the name of receiver if different than purchaser.

. It shall be unlawful to sell, give away, or otherwise dispose of, or deliver to any person under twenty-one years of age any explosives including black powder, and blasting caps or other explosive igniters, whether said person is acting for himself or herself or for any other person: PROVIDED, That small arms ammunition and handloader components shall not be considered explosives for the purposes of this section: PROVIDED FURTHER, That if there is a finding by the director that said use or disposition of explosives poses no unusual hazard to the safety of life or limb in any class of industry, where persons eighteen years of age or older are employed as users, and where said persons are adequately trained and adequately supervised by a superior in an employment relationship who is sufficiently experienced in the use of explosives, and who possesses a valid license for such use under this chapter, the director in his or her discretion may exclude said persons in that class of industry from said minimum age requirement.

. All persons engaged in keeping, using, or storing any compound, mixture, or material, in wet condition, or otherwise, which upon drying out or undergoing other physical changes, may become an explosive within the definition of RCW 70.74.010, shall report in writing subscribed to by such person or his or her agent, to the department of labor and industries, report blanks to be furnished by such department, and such reports to require:

.. The kind of compound, mixture, or material kept or stored, and maximum quantity thereof;

.. Condition or state of compound, mixture, or material;

.. Place where kept or stored.

The department of labor and industries may at any time cause an inspection to be made to determine whether the condition of the compound, mixture, or material is as reported.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20391[2012 c 117 § 391]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c111.pdf?cite=1982%20c%20111%20§%201[1982 c 111 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c88.pdf?cite=1972%20ex.s.%20c%2088%20§%206[1972 ex.s. c 88 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%204[1969 ex.s. c 137 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c99.pdf?cite=1967%20c%2099%20§%201[1967 c 99 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1931c111.pdf?cite=1931%20c%20111%20§%202[1931 c 111 § 2]; RRS § 5440-2; ]

== 70.74.022 - License required to manufacture, purchase, sell, use, possess, transport, or store explosives—Penalty—Surrender of explosives by unlicensed person—Other relief.
. It is unlawful for any person to manufacture, purchase, sell, offer for sale, use, possess, transport, or store any explosive, improvised device, or components that are intended to be assembled into an explosive or improvised device without having a validly issued license from the department of labor and industries, which license has not been revoked or suspended. Violation of this section is a class C felony.

. Upon notice from the department of labor and industries or any law enforcement agency having jurisdiction, a person manufacturing, purchasing, selling, offering for sale, using, possessing, transporting, or storing any explosive, improvised device, or components of explosives or improvised devices without a license shall immediately surrender those explosives, improvised devices, or components to the department or to the respective law enforcement agency.

. At any time that the director of labor and industries requests the surrender of explosives, improvised devices, or components of explosives or improvised devices, from any person pursuant to subsection (2) of this section, the director may in addition request the attorney general to make application to the superior court of the county in which the unlawful practice exists for a temporary restraining order or such other relief as appears to be appropriate under the circumstances.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1118-S.SL.pdf?cite=1993%20c%20293%20§%202[1993 c 293 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c198.pdf?cite=1988%20c%20198%20§%2010[1988 c 198 § 10]; ]

== 70.74.025 - Magazines—Classification, location and construction—Standards—Use.
The director of the department of labor and industries shall establish by rule or regulation requirements for classification, location and construction of magazines for storage of explosives in compliance with accepted applicable explosive safety standards. All explosives shall be kept in magazines which meet the requirements of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%209[1969 ex.s. c 137 § 9]; ]

== 70.74.030 - Quantity and distance tables for storage—Adoption by rule.
All explosive manufacturing buildings and magazines in which explosives or blasting agents except small arms ammunition and smokeless powder are had, kept, or stored, must be located at distances from inhabited buildings, railroads, highways, and public utility transmission systems in conformity with the quantity and distance tables adopted by the department of labor and industries by rule. The department of labor and industries shall adopt the quantity and distance tables promulgated by the federal bureau of alcohol, tobacco, and firearms unless the department determines the tables to be inappropriate. The tables shall be the basis on which applications for storage license[s] are made and storage licenses issued as provided in RCW 70.74.110 and 70.74.120.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c198.pdf?cite=1988%20c%20198%20§%201[1988 c 198 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c88.pdf?cite=1972%20ex.s.%20c%2088%20§%207[1972 ex.s. c 88 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%2010[1969 ex.s. c 137 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1931c111.pdf?cite=1931%20c%20111%20§%205[1931 c 111 § 5]; RRS § 5440-5; ]

== 70.74.040 - Limit on storage quantity.
No quantity in excess of three hundred thousand pounds, or the equivalent in blasting caps shall be had, kept or stored in any factory building or magazine in this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c72.pdf?cite=1970%20ex.s.%20c%2072%20§%202[1970 ex.s. c 72 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1931c111.pdf?cite=1931%20c%20111%20§%204[1931 c 111 § 4]; RRS § 5440-4; ]

== 70.74.050 - Quantity and distance table for explosives manufacturing buildings.
All explosives manufacturing buildings shall be located one from the other and from other buildings on explosives manufacturing plants in which persons are regularly employed, and all magazines shall be located from factory buildings and buildings on explosives plants in which persons are regularly employed, in conformity with the intraexplosives plant quantity and distance table below set forth:

      EXPLOSIVES PoundsOverPoundsNot OverDistanceFeet   SeparateBuilding orWithinSubstantialDividing Walls. . . . 10   10 25 40 25 50 60 50 100 80 100 200 100 200 300 120 300 400 130 400 500 140 500 750 160 750 1,000 180 1,000 1,500 210 1,500 2,000 230 2,000 3,000 260 3,000 4,000 280 4,000 5,000 300 5,000 6,000 320 6,000 7,000 340 7,000 8,000 360 8,000 9,000 380 9,000 10,000 400 10,000 12,500 420 12,500 15,000 450 15,000 17,500 470 17,500 20,000 490 20,000 25,000 530 25,000 30,000 560 30,000 35,000 590 35,000 40,000 620 40,000 45,000 640 45,000 50,000 660 50,000 55,000 680 55,000 60,000 700 60,000 65,000 720 65,000 70,000 740 70,000 75,000 770 75,000 80,000 780 80,000 85,000 790 85,000 90,000 800 90,000 95,000 820 95,000 100,000 830 100,000 125,000 900 125,000 150,000 950 150,000 175,000 1,000 175,000 200,000 1,050 200,000 225,000 1,100 225,000 250,000 1,150 

 

 

 

 

 

 

EXPLOSIVES

 

Pounds

Over

Pounds

Not Over

Distance

Feet

 

 

 

Separate

Building or

Within

Substantial

Dividing Walls

. . . .

 

10

 

 

 

10

 

25

 

40

 

25

 

50

 

60

 

50

 

100

 

80

 

100

 

200

 

100

 

200

 

300

 

120

 

300

 

400

 

130

 

400

 

500

 

140

 

500

 

750

 

160

 

750

 

1,000

 

180

 

1,000

 

1,500

 

210

 

1,500

 

2,000

 

230

 

2,000

 

3,000

 

260

 

3,000

 

4,000

 

280

 

4,000

 

5,000

 

300

 

5,000

 

6,000

 

320

 

6,000

 

7,000

 

340

 

7,000

 

8,000

 

360

 

8,000

 

9,000

 

380

 

9,000

 

10,000

 

400

 

10,000

 

12,500

 

420

 

12,500

 

15,000

 

450

 

15,000

 

17,500

 

470

 

17,500

 

20,000

 

490

 

20,000

 

25,000

 

530

 

25,000

 

30,000

 

560

 

30,000

 

35,000

 

590

 

35,000

 

40,000

 

620

 

40,000

 

45,000

 

640

 

45,000

 

50,000

 

660

 

50,000

 

55,000

 

680

 

55,000

 

60,000

 

700

 

60,000

 

65,000

 

720

 

65,000

 

70,000

 

740

 

70,000

 

75,000

 

770

 

75,000

 

80,000

 

780

 

80,000

 

85,000

 

790

 

85,000

 

90,000

 

800

 

90,000

 

95,000

 

820

 

95,000

 

100,000

 

830

 

100,000

 

125,000

 

900

 

125,000

 

150,000

 

950

 

150,000

 

175,000

 

1,000

 

175,000

 

200,000

 

1,050

 

200,000

 

225,000

 

1,100

 

225,000

 

250,000

 

1,150

 

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c88.pdf?cite=1972%20ex.s.%20c%2088%20§%208[1972 ex.s. c 88 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1931c111.pdf?cite=1931%20c%20111%20§%205[1931 c 111 § 5]; RRS § 5440-5; ]

== 70.74.061 - Quantity and distance tables for separation between magazines—Adoption by rule.
Magazines containing blasting caps and electric blasting caps shall be separated from other magazines containing like contents, or from magazines containing explosives by distances set in the quantity and distance tables adopted by the department of labor and industries by rule. The department of labor and industries shall adopt the quantity and distance tables promulgated by the federal bureau of alcohol, tobacco, and firearms unless the department determines the tables to be inappropriate. The tables shall be the basis on which applications for storage license[s] are made and storage licenses issued as provided in RCW 70.74.110 and 70.74.120.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c198.pdf?cite=1988%20c%20198%20§%202[1988 c 198 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%2011[1969 ex.s. c 137 § 11]; ]

== 70.74.100 - Storage of caps with explosives prohibited.
No blasting caps, or other detonating or fulminating caps, or detonators, or flame-producing devices shall be kept or stored in any magazine in which other explosives are kept or stored.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%2012[1969 ex.s. c 137 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1931c111.pdf?cite=1931%20c%20111%20§%2010[1931 c 111 § 10]; RRS § 5440-10; ]

== 70.74.110 - Manufacturer's report—Inspection—License.
All persons engaged in the manufacture of explosives, or any process involving explosives, or where explosives are used as a component part in the manufacture of any article or device, on August 11, 1969, shall within sixty days thereafter, and all persons engaging in the manufacture of explosives, or any process involving explosives, or where explosives are used as a component part in the manufacture of any article or device after August 11, 1969, shall, before so engaging, make an application in writing, subscribed to by such person or his or her agent, to the department of labor and industries, the application stating:

. Location of place of manufacture or processing;

. Kind of explosives manufactured, processed, or used;

. The distance that such explosives manufacturing building is located or intended to be located from the other factory buildings, magazines, inhabited buildings, railroads and highways, and public utility transmission systems;

. The name and address of the applicant;

. The reason for desiring to manufacture explosives;

. The applicant's citizenship, if the applicant is an individual;

. If the applicant is a partnership, the names and addresses of the partners, and their citizenship;

. If the applicant is an association or corporation, the names and addresses of the officers and directors thereof, and their citizenship; and

. Such other pertinent information as the director of labor and industries shall require to effectuate the purpose of this chapter.

There shall be kept in the main office on the premises of each explosives manufacturing plant a plan of said plant showing the location of all explosives manufacturing buildings and the distance they are located from other factory buildings where persons are employed and from magazines, and these plans shall at all times be open to inspection by duly authorized inspectors of the department of labor and industries. The superintendent of each plant shall upon demand of said inspector furnish the following information:

.. The maximum amount and kind of explosive material which is or will be present in each building at one time.

.. The nature and kind of work carried on in each building and whether or not said buildings are surrounded by natural or artificial barricades.

Except as provided in RCW 70.74.370, the department of labor and industries shall as soon as possible after receiving such application cause an inspection to be made of the explosives manufacturing plant, and if found to be in accordance with RCW 70.74.030 and 70.74.050 and 70.74.061, such department shall issue a license to the person applying therefor showing compliance with the provisions of this chapter if the applicant demonstrates that either the applicant or the officers, agents, or employees of the applicant are sufficiently experienced in the manufacture of explosives and the applicant meets the qualifications for a license under RCW 70.74.360. Such license shall continue in full force and effect until expired, suspended, or revoked by the department pursuant to this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20392[2012 c 117 § 392]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20870[1997 c 58 § 870]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c198.pdf?cite=1988%20c%20198%20§%205[1988 c 198 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%2013[1969 ex.s. c 137 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c101.pdf?cite=1941%20c%20101%20§%201[1941 c 101 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1931c111.pdf?cite=1931%20c%20111%20§%2011[1931 c 111 § 11]; Rem. Supp. 1941 § 5440-1; ]

== 70.74.120 - Storage report—Inspection—License—Cancellation.
All persons engaged in keeping or storing and all persons having in their possession explosives on August 11, 1969, shall within sixty days thereafter, and all persons engaging in keeping or storing explosives or coming into possession thereof after August 11, 1969, shall before engaging in the keeping or storing of explosives or taking possession thereof, make an application in writing subscribed to by such person or his or her agent, to the department of labor and industries stating:

. The location of the magazine, if any, if then existing, or in case of a new magazine, the proposed location of such magazine;

. The kind of explosives that are kept or stored or possessed or intended to be kept or stored or possessed and the maximum quantity that is intended to be kept or stored or possessed thereat;

. The distance that such magazine is located or intended to be located from other magazines, inhabited buildings, explosives manufacturing buildings, railroads, highways, and public utility transmission systems;

. The name and address of the applicant;

. The reason for desiring to store or possess explosives;

. The citizenship of the applicant if the applicant is an individual;

. If the applicant is a partnership, the names and addresses of the partners and their citizenship;

. If the applicant is an association or corporation, the names and addresses of the officers and directors thereof and their citizenship;

. And such other pertinent information as the director of the department of labor and industries shall require to effectuate the purpose of this chapter.

The department of labor and industries shall, as soon as may be after receiving such application, cause an inspection to be made of the magazine, if then constructed, and, in the case of a new magazine, as soon as may be after same is found to be constructed in accordance with the specification provided in RCW 70.74.025, such department shall determine the amount of explosives that may be kept and stored in such magazine by reference to the quantity and distance tables specified in or adopted under this chapter and shall issue a license to the person applying therefor if the applicant demonstrates that either the applicant or the officers, agents, or employees of the applicant are sufficiently experienced in the handling of explosives and possess suitable storage facilities therefor, and that the applicant meets the qualifications for a license under RCW 70.74.360. Said license shall set forth the maximum quantity of explosives that may be had, kept, or stored by said person. Such license shall be valid until canceled for one or more of the causes hereinafter provided. Whenever by reason of change in the physical conditions surrounding said magazine at the time of the issuance of the license therefor, such as:

.. The erection of buildings nearer said magazine;

.. The construction of railroads nearer said magazine;

.. The opening for public travel of highways nearer said magazine; or

.. The construction of public utilities transmission systems near said magazine; then the amounts of explosives which may be lawfully had, kept, or stored in said magazine must be reduced to conform to such changed conditions in accordance with the quantity and distance table notwithstanding the license, and the department of labor and industries shall modify or cancel such license in accordance with the changed conditions. Whenever any person to whom a license has been issued, keeps or stores in the magazine or has in his or her possession, any quantity of explosives in excess of the maximum amount set forth in said license, or whenever any person fails for thirty days to pay the annual license fee hereinafter provided after the same becomes due, the department is authorized to cancel such license. Whenever a license is canceled by the department for any cause herein specified, the department shall notify the person to whom such license is issued of the fact of such cancellation and shall in said notice direct the removal of all explosives stored in said magazine within ten days from the giving of said notice, or, if the cause of cancellation be the failure to pay the annual license fee, or the fact that explosives are kept for an unlawful purpose, the department of labor and industries shall order such person to dispossess himself or herself of said explosives within ten days from the giving of said notice. Failure to remove the explosives stored in said magazine or to dispossess oneself of the explosives as herein provided within the time specified in said notice shall constitute a violation of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20393[2012 c 117 § 393]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c198.pdf?cite=1988%20c%20198%20§%206[1988 c 198 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%2014[1969 ex.s. c 137 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c101.pdf?cite=1941%20c%20101%20§%202[1941 c 101 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1931c111.pdf?cite=1931%20c%20111%20§%2012[1931 c 111 § 12]; Rem. Supp. 1941 § 5440-12; ]

== 70.74.130 - Dealer in explosives—Application—License.
Every person desiring to engage in the business of dealing in explosives shall apply to the department of labor and industries for a license therefor. Said application shall state, among other things:

. The name and address of applicant;

. The reason for desiring to engage in the business of dealing in explosives;

. Citizenship, if an individual applicant;

. If a partnership, the names and addresses of the partners and their citizenship;

. If an association or corporation, the names and addresses of the officers and directors thereof and their citizenship; and

. Such other pertinent information as the director of labor and industries shall require to effectuate the purpose of this chapter.

Except as provided in RCW 70.74.370, the department of labor and industries shall issue the license if the applicant demonstrates that either the applicant or the principal officers, agents, or employees of the applicant are experienced in the business of dealing in explosives, possess suitable facilities therefor, have not been convicted of any crime that would warrant revocation or nonrenewal of a license under this chapter, and have never had an explosives-related license revoked under this chapter or under similar provisions of any other state.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20871[1997 c 58 § 871]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c198.pdf?cite=1988%20c%20198%20§%207[1988 c 198 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%2016[1969 ex.s. c 137 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c101.pdf?cite=1941%20c%20101%20§%203[1941 c 101 § 3]; Rem. Supp. 1941 § 5440-12a; ]

== 70.74.135 - Purchaser of explosives—Application—License.
All persons desiring to purchase explosives except handloader components shall apply to the department of labor and industries for a license. Said application shall state, among other things:

. The location where explosives are to be used;

. The kind and amount of explosives to be used;

. The name and address of the applicant;

. The reason for desiring to use explosives;

. The citizenship of the applicant if the applicant is an individual;

. If the applicant is a partnership, the names and addresses of the partners and their citizenship;

. If the applicant is an association or corporation, the names and addresses of the officers and directors thereof and their citizenship; and

. Such other pertinent information as the director of the department of labor and industries shall require to effectuate the purpose of this chapter.

The department of labor and industries shall issue the license if the applicant demonstrates that either the applicant or the officers, agents or employees of the applicant are sufficiently experienced in the use of explosives to authorize a purchase license. However, no purchaser's license may be issued to any person who cannot document proof of possession or right to use approved and licensed storage facilities unless the person signs a statement certifying that explosives will not be stored.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c198.pdf?cite=1988%20c%20198%20§%208[1988 c 198 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c302.pdf?cite=1971%20ex.s.%20c%20302%20§%207[1971 ex.s. c 302 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c72.pdf?cite=1970%20ex.s.%20c%2072%20§%203[1970 ex.s. c 72 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%2018[1969 ex.s. c 137 § 18]; ]

== 70.74.137 - Purchaser's license fee.
Every person applying for a purchaser's license, or renewal thereof, shall pay an annual license fee of twenty-five dollars. The director of labor and industries may adjust the amount of the license fee to reflect the administrative costs of the department. The fee shall not exceed one hundred dollars.

Said license fee shall accompany the application and shall be transmitted by the department to the state treasurer: PROVIDED, That if the applicant is denied a purchaser's license the license fee shall be returned to said applicant by registered mail.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3381.SL.pdf?cite=2008%20c%20285%20§%205[2008 c 285 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c198.pdf?cite=1988%20c%20198%20§%2012[1988 c 198 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c88.pdf?cite=1972%20ex.s.%20c%2088%20§%202[1972 ex.s. c 88 § 2]; ]

== 70.74.140 - Storage license fee.
Every person engaging in the business of keeping or storing of explosives shall pay an annual license fee for each magazine maintained, to be graduated by the department of labor and industries according to the quantity kept or stored therein, of fifty dollars. The director of labor and industries may adjust the amount of the license fee to reflect the administrative costs of the department. The fee shall not exceed four hundred dollars.

Said license fee shall accompany the application and shall be transmitted by the department to the state treasurer.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3381.SL.pdf?cite=2008%20c%20285%20§%206[2008 c 285 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c198.pdf?cite=1988%20c%20198%20§%2013[1988 c 198 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%2015[1969 ex.s. c 137 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1931c111.pdf?cite=1931%20c%20111%20§%2013[1931 c 111 § 13]; RRS § 5440-13; ]

== 70.74.142 - User's license or renewal—Fee.
Every person applying for a user's license, or renewal thereof, under this chapter shall pay an annual license fee of fifty dollars. The director of labor and industries may adjust the amount of the license fee to reflect the administrative costs of the department. The fee shall not exceed two hundred dollars.

Said license fee shall accompany the application, and be transmitted by the department to the state treasurer: PROVIDED, That if the applicant is denied a user's license the license fee shall be returned to said applicant by registered mail.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3381.SL.pdf?cite=2008%20c%20285%20§%207[2008 c 285 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c198.pdf?cite=1988%20c%20198%20§%2014[1988 c 198 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c88.pdf?cite=1972%20ex.s.%20c%2088%20§%201[1972 ex.s. c 88 § 1]; ]

== 70.74.144 - Manufacturer's license fee—Manufacturers to comply with dealer requirements when selling.
Every person engaged in the business of manufacturing explosives shall pay an annual license fee of fifty dollars. The director of labor and industries may adjust the amount of the license fee to reflect the administrative costs of the department. The fee shall not exceed two hundred dollars.

Businesses licensed to manufacture explosives are not required to have a dealer's license, but must comply with all of the dealer requirements of this chapter when they sell explosives.

The license fee shall accompany the application and shall be transmitted by the department to the state treasurer.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3381.SL.pdf?cite=2008%20c%20285%20§%208[2008 c 285 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c198.pdf?cite=1988%20c%20198%20§%2015[1988 c 198 § 15]; ]

== 70.74.146 - Seller's license fee—Sellers to comply with dealer requirements.
Every person engaged in the business of selling explosives shall pay an annual license fee of fifty dollars. The director of labor and industries may adjust the amount of the license fee to reflect the administrative costs of the department. The fee shall not exceed two hundred dollars.

Businesses licensed to sell explosives must comply with all of the dealer requirements of this chapter.

The license fee shall accompany the application and shall be transmitted by the department to the state treasurer.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3381.SL.pdf?cite=2008%20c%20285%20§%209[2008 c 285 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c198.pdf?cite=1988%20c%20198%20§%2016[1988 c 198 § 16]; ]

== 70.74.150 - Annual inspection.
The department of labor and industries shall make, or cause to be made, at least one inspection during every year, of each licensed explosives plant or magazine.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1931c111.pdf?cite=1931%20c%20111%20§%2014[1931 c 111 § 14]; RRS § 5440-14; ]

== 70.74.160 - Unlawful access to explosives.
No person, except the director of labor and industries or the director's authorized agent, the owner, the owner's agent, or a person authorized to enter by the owner or owner's agent, or a law enforcement officer acting within his or her official capacity, may enter any explosives manufacturing building, magazine or car, vehicle or other common carrier containing explosives in this state. Violation of this section is a gross misdemeanor punishable under chapter 9A.20 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1118-S.SL.pdf?cite=1993%20c%20293%20§%203[1993 c 293 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%2019[1969 ex.s. c 137 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1931c111.pdf?cite=1931%20c%20111%20§%2015[1931 c 111 § 15]; RRS § 5440-15; ]

== 70.74.170 - Discharge of firearms or igniting flame near explosives.
No person shall discharge any firearms at or against any magazine or explosives manufacturing buildings or ignite any flame or flame-producing device nearer than two hundred feet from said magazine or explosives manufacturing building.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%2020[1969 ex.s. c 137 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1931c111.pdf?cite=1931%20c%20111%20§%2016[1931 c 111 § 16]; RRS § 5440-16; ]

== 70.74.180 - Explosive devices prohibited—Penalty.
Any person who has in his or her possession or control any shell, bomb, or similar device, charged or filled with one or more explosives, intending to use it or cause it to be used for an unlawful purpose, is guilty of a class A felony, and upon conviction shall be punished by imprisonment in a state prison for a term of not more than twenty years.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20354[2003 c 53 § 354]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c55.pdf?cite=1984%20c%2055%20§%201[1984 c 55 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%2021[1969 ex.s. c 137 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1931c111.pdf?cite=1931%20c%20111%20§%2018[1931 c 111 § 18]; RRS § 5440-18; ]

== 70.74.191 - Exemptions.
The laws contained in this chapter and regulations prescribed by the department of labor and industries pursuant to this chapter shall not apply to:

. Explosives or blasting agents in the course of transportation by way of railroad, water, highway, or air under the jurisdiction of, and in conformity with, regulations adopted by the federal department of transportation, the Washington state utilities and transportation commission, and the Washington state patrol;

. The laboratories of schools, colleges, and similar institutions if confined to the purpose of instruction or research and if not exceeding the quantity of one pound;

. Explosives in the forms prescribed by the official United States Pharmacopoeia;

. The transportation, storage, and use of explosives or blasting agents in the normal and emergency operations of United States agencies and departments including the regular United States military departments on military reservations; arsenals, navy yards, depots, or other establishments owned by, operated by, or on behalf of, the United States; or the duly authorized militia of any state; or to emergency operations of any state department or agency, any police, or any municipality or county;

. A hazardous devices technician when carrying out normal and emergency operations, handling evidence, and operating and maintaining a specially designed emergency response vehicle that carries no more than ten pounds of explosive material or when conducting training and whose employer possesses the minimum safety equipment prescribed by the federal bureau of investigation for hazardous devices work. For purposes of this section, a hazardous devices technician is a person who is a graduate of the federal bureau of investigation hazardous devices school and who is employed by a state, county, or municipality;

. The importation, sale, possession, and use of fireworks as defined in chapter 70.77 RCW, signaling devices, flares, fuses, and torpedoes;

. The transportation, storage, and use of explosives or blasting agents in the normal and emergency avalanche control procedures as conducted by trained and licensed ski area operator personnel. However, the storage, transportation, and use of explosives and blasting agents for such use shall meet the requirements of regulations adopted by the director of labor and industries;

. The storage of consumer fireworks as defined in chapter 70.77 RCW pursuant to a forfeiture or seizure under chapter 70.77 RCW by the chief of the Washington state patrol, through the director of fire protection, or his or her deputy, or by state agencies or local governments having general law enforcement authority;

. The transportation and storage of explosive actuated tactical devices, including noise and flash diversionary devices, by local law enforcement tactical response teams and officers in law enforcement department-issued vehicles designated for use by tactical response teams and officers, provided the explosive devices are stored and secured in compliance with regulations and rulings adopted by the federal bureau of alcohol, tobacco, firearms and explosives; and

. Any violation under this chapter if any existing ordinance of any city, municipality, or county is more stringent than this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5264-S.SL.pdf?cite=2013%20c%20140%20§%201[2013 c 140 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%202[2002 c 370 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1308.SL.pdf?cite=1998%20c%2040%20§%201[1998 c 40 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1118-S.SL.pdf?cite=1993%20c%20293%20§%205[1993 c 293 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c191.pdf?cite=1985%20c%20191%20§%202[1985 c 191 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%205[1969 ex.s. c 137 § 5]; ]

== 70.74.201 - Municipal or county ordinances unaffected—State preemption.
This chapter shall not affect, modify or limit the power of a city, municipality or county in this state to make an ordinance that is more stringent than this chapter which is applicable within their respective corporate limits or boundaries: PROVIDED, That the state shall be deemed to have preempted the field of regulation of small arms ammunition and handloader components.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c72.pdf?cite=1970%20ex.s.%20c%2072%20§%205[1970 ex.s. c 72 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%206[1969 ex.s. c 137 § 6]; ]

== 70.74.210 - Coal mining code unaffected.
All acts and parts of acts inconsistent with this act are hereby repealed: PROVIDED, HOWEVER, That nothing in this act shall be construed as amending, limiting, or repealing any provision of chapter 36, session laws of 1917, known as the coal mining code.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1931c111.pdf?cite=1931%20c%20111%20§%2022[1931 c 111 § 22]; RRS § 5440-22; ]

== 70.74.230 - Shipments out of state—Dealer's records.
If any manufacturer of explosives or dealer therein shall have shipped any explosives into another state, and the laws of such other state shall designate an officer or agency to regulate the possession, receipt or storage of explosives, and such officer or agency shall so require, such manufacturer shall, at least once each calendar month, file with such officer or agency of such other state a report giving the names of all purchasers and the amount and description of all explosives sold or delivered in such other state. Dealers in explosives shall keep a record of all explosives purchased or sold by them, which record shall include the name and address of each vendor and vendee, the date of each sale or purchase, and the amount and kind of explosives sold or purchased. Such records shall be open for inspection by the duly authorized agents of the department of labor and industries and by all federal, state and local law enforcement officers at all times, and a copy of such record shall be furnished once each calendar month to the department of labor and industries in such form as said department shall prescribe.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c101.pdf?cite=1941%20c%20101%20§%204[1941 c 101 § 4]; Rem. Supp. 1941 § 5440-23; ]

== 70.74.240 - Sale to unlicensed person prohibited.
No dealer shall sell, barter, give or dispose of explosives to any person who does not hold a license to purchase explosives issued under the provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c72.pdf?cite=1970%20ex.s.%20c%2072%20§%204[1970 ex.s. c 72 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%2017[1969 ex.s. c 137 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c101.pdf?cite=1941%20c%20101%20§%205[1941 c 101 § 5]; Rem. Supp. 1941 § 5440-24; ]

== 70.74.250 - Blasting near fur farms and hatcheries.
Between the dates of January 15th and June 15th of each year it shall be unlawful for any person to do, or cause to be done, any blasting within fifteen hundred feet from any fur farm or commercial hatchery except in case of emergency without first giving to the person in charge of such farm or hatchery twenty-four hours notice: PROVIDED, HOWEVER, That in the case of an established quarry and sand and gravel operations, and where it is necessary for blasting to be done continually, the notice required in this section may be made at the beginning of the period each year when blasting is to be done.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c107.pdf?cite=1941%20c%20107%20§%201[1941 c 107 § 1]; Rem. Supp. 1941 § 5440-25; ]

== 70.74.270 - Malicious placement of an explosive—Penalties.
A person who maliciously places any explosive or improvised device in, upon, under, against, or near any building, car, vessel, railroad track, airplane, public utility transmission system, or structure, in such manner or under such circumstances as to destroy or injure it if exploded is guilty of:

. Malicious placement of an explosive in the first degree if the offense is committed with intent to commit a terrorist act. Malicious placement of an explosive in the first degree is a class A felony;

. Malicious placement of an explosive in the second degree if the offense is committed under circumstances not amounting to malicious placement of an explosive in the first degree and if the circumstances and surroundings are such that the safety of any person might be endangered by the explosion. Malicious placement of an explosive in the second degree is a class B felony;

. Malicious placement of an explosive in the third degree if the offense is committed under circumstances not amounting to malicious placement of an explosive in the first or second degree. Malicious placement of an explosive in the third degree is a class B felony.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1069-S.SL.pdf?cite=1997%20c%20120%20§%201[1997 c 120 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1118-S.SL.pdf?cite=1993%20c%20293%20§%206[1993 c 293 § 6]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2263-S.SL.pdf?cite=1992%20c%207%20§%2049[1992 c 7 § 49]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c55.pdf?cite=1984%20c%2055%20§%202[1984 c 55 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c302.pdf?cite=1971%20ex.s.%20c%20302%20§%208[1971 ex.s. c 302 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%2023[1969 ex.s. c 137 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20400[1909 c 249 § 400]; RRS § 2652; ]

== 70.74.272 - Malicious placement of an imitation device—Penalties.
. A person who maliciously places any imitation device in, upon, under, against, or near any building, car, vessel, railroad track, airplane, public utility transmission system, or structure, with the intent to give the appearance or impression that the imitation device is an explosive or improvised device, is guilty of:

.. Malicious placement of an imitation device in the first degree if the offense is committed with intent to commit a terrorist act. Malicious placement of an imitation device in the first degree is a class B felony;

.. Malicious placement of an imitation device in the second degree if the offense is committed under circumstances not amounting to malicious placement of an imitation device in the first degree. Malicious placement of an imitation device in the second degree is a class C felony.

. For purposes of this section, "imitation device" means a device or substance that is not an explosive or improvised device, but which by appearance or representation would lead a reasonable person to believe that the device or substance is an explosive or improvised device.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1069-S.SL.pdf?cite=1997%20c%20120%20§%202[1997 c 120 § 2]; ]

== 70.74.275 - Intimidation or harassment with an explosive—Class C felony.
Unless otherwise allowed to do so under this chapter, a person who exhibits a device designed, assembled, fabricated, or manufactured, to convey the appearance of an explosive or improvised device, and who intends to, and does, intimidate or harass a person, is guilty of a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1118-S.SL.pdf?cite=1993%20c%20293%20§%204[1993 c 293 § 4]; ]

== 70.74.280 - Malicious explosion of a substance—Penalties.
A person who maliciously, by the explosion of gunpowder or any other explosive substance or material, destroy or damage any building, car, airplane, vessel, common carrier, railroad track, or public utility transmission system or structure is guilty of:

. Malicious explosion of a substance in the first degree if the offense is committed with intent to commit a terrorist act. Malicious explosion of a substance in the first degree is a class A felony;

. Malicious explosion of a substance in the second degree if the offense is committed under circumstances not amounting to malicious explosion of a substance in the first degree and if thereby the life or safety of a human being is endangered. Malicious explosion of a substance in the second degree is a class A felony;

. Malicious explosion of a substance in the third degree if the offense is committed under circumstances not amounting to malicious explosion of a substance in the first or second degree. Malicious explosion of a substance in the third degree is a class B felony.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1069-S.SL.pdf?cite=1997%20c%20120%20§%203[1997 c 120 § 3]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2263-S.SL.pdf?cite=1992%20c%207%20§%2050[1992 c 7 § 50]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c302.pdf?cite=1971%20ex.s.%20c%20302%20§%209[1971 ex.s. c 302 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%2024[1969 ex.s. c 137 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20401[1909 c 249 § 401]; RRS § 2653; ]

== 70.74.285 - "Terrorist act" defined.
For the purposes of RCW 70.74.270, 70.74.272, and 70.74.280 "terrorist act" means an act that is intended to: (1) Intimidate or coerce a civilian population; (2) influence the policy of a branch or level of government by intimidation or coercion; (3) affect the conduct of a branch or level of government by intimidation or coercion; or (4) retaliate against a branch or level of government for a policy or conduct of the government.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1069-S.SL.pdf?cite=1997%20c%20120%20§%204[1997 c 120 § 4]; ]

== 70.74.295 - Abandonment of explosives.
It shall be unlawful for any person to abandon explosives or improvised devices. Violation of this section is a gross misdemeanor punishable under chapter 9A.20 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1118-S.SL.pdf?cite=1993%20c%20293%20§%207[1993 c 293 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c88.pdf?cite=1972%20ex.s.%20c%2088%20§%203[1972 ex.s. c 88 § 3]; ]

== 70.74.297 - Separate storage of components capable of detonation when mixed.
Any two components which, when mixed, become capable of detonation by a No. 6 cap must be stored in separate locked containers or in a licensed, approved magazine.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c88.pdf?cite=1972%20ex.s.%20c%2088%20§%204[1972 ex.s. c 88 § 4]; ]

== 70.74.300 - Explosive containers to be marked—Penalty.
Every person who shall put up for sale, or who shall deliver to any warehouse operator, dock, depot, or common carrier any package, cask, or can containing any explosive, nitroglycerin, dynamite, or powder, without having been properly labeled thereon to indicate its explosive classification, shall be guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20840[2011 c 336 § 840]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%2026[1969 ex.s. c 137 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20254[1909 c 249 § 254]; RRS § 2506; ]

== 70.74.310 - Gas bombs, explosives, stink bombs, etc.
Any person other than a lawfully constituted peace officer of this state who shall deposit, leave, place, spray, scatter, spread, or throw in any building, or any place, or who shall counsel, aid, assist, encourage, incite, or direct any other person or persons to deposit, leave, place, spray, scatter, spread, or throw, in any building or place, or who shall have in his or her possession for the purpose of, and with the intent of depositing, leaving, placing, spraying, scattering, spreading, or throwing, in any building or place, or of counseling, aiding, assisting, encouraging, inciting, or directing any other person or persons to deposit, leave, place, spray, scatter, spread, or throw, any stink bomb, stink paint, tear bomb, tear shell, explosive, or flame-producing device, or any other device, material, chemical, or substance, which, when exploded or opened, or without such exploding or opening, by reason of its offensive and pungent odor, does or will annoy, injure, endanger, or inconvenience any person or persons, shall be guilty of a gross misdemeanor: PROVIDED, That this section shall not apply to persons in the military service, actually engaged in the performance of military duties, pursuant to orders from competent authority nor to any property owner or person acting under his or her authority in providing protection against the commission of a felony.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20394[2012 c 117 § 394]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%2027[1969 ex.s. c 137 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c245.pdf?cite=1927%20c%20245%20§%201[1927 c 245 § 1]; RRS § 2504-1; ]

== 70.74.320 - Small arms ammunition, primers and propellants—Transportation regulations.
The federal regulations of the United States department of transportation on the transportation of small arms ammunition, of small arms ammunition primers, and of small arms smokeless propellants are hereby adopted in this chapter by reference.

The director of the department of labor and industries has the authority to issue future regulations in accordance with amendments and additions to the federal regulations of the United States department of transportation on the transportation of small arms ammunition, of small arms ammunition primers, and of small arms smokeless propellants.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%2028[1969 ex.s. c 137 § 28]; ]

== 70.74.330 - Small arms ammunition, primers and propellants—Separation from flammable materials.
Small arms ammunition shall be separated from flammable liquids, flammable solids and oxidizing materials by a fire-resistant wall of one-hour rating or by a distance of twenty-five feet.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%2029[1969 ex.s. c 137 § 29]; ]

== 70.74.340 - Small arms ammunition, primers and propellants—Transportation, storage and display requirements.
Quantities of small arms smokeless propellant (class B) in shipping containers approved by the federal department of transportation not in excess of fifty pounds may be transported in a private vehicle.

Quantities in excess of twenty-five pounds but not to exceed fifty pounds in a private passenger vehicle shall be transported in an approved magazine as specified by the department of labor and industries rules and regulations.

Transportation of quantities in excess of fifty pounds is prohibited in passenger vehicles: PROVIDED, That this requirement shall not apply to duly licensed dealers.

Transportation of quantities in excess of fifty pounds shall be in accordance with federal department of transportation regulations.

Small arms smokeless propellant intended for personal use in quantities not to exceed twenty-five pounds may be stored without restriction in residences; quantities over twenty-five pounds but not to exceed fifty pounds shall be stored in a strong box or cabinet constructed with three-fourths inch plywood (minimum), or equivalent, on all sides, top, and bottom.

Black powder as used in muzzle loading firearms may be transported in a private vehicle or stored without restriction in private residences in quantities not to exceed five pounds.

Not more than seventy-five pounds of small arms smokeless propellant, in containers of one pound maximum capacity may be displayed in commercial establishments.

Not more than twenty-five pounds of black powder as used in muzzle loading firearms may be stored in commercial establishments of which not more than four pounds in containers of one pound maximum capacity may be displayed.

Quantities in excess of one hundred fifty pounds of smokeless propellant or twenty-five pounds of black powder as used in muzzle loading firearms shall be stored in magazines constructed as specified in the rules and regulations for construction of magazines, and located in compliance with this chapter.

All small arms smokeless propellant when stored shall be packed in federal department of transportation approved containers.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c72.pdf?cite=1970%20ex.s.%20c%2072%20§%206[1970 ex.s. c 72 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%2030[1969 ex.s. c 137 § 30]; ]

== 70.74.350 - Small arms ammunition, primers and propellants—Primers, transportation and storage requirements.
Small arms ammunition primers shall not be transported or stored except in the original shipping container approved by the federal department of transportation.

Truck or rail transportation of small arms ammunition primers shall be in accordance with the federal regulation of the United States department of transportation.

No more than twenty-five thousand small arms ammunition primers shall be transported in a private passenger vehicle: PROVIDED, That this requirement shall not apply to duly licensed dealers.

Quantities not to exceed ten thousand small arms ammunition primers may be stored in a residence.

Small arms ammunition primers shall be separate from flammable liquids, flammable solids, and oxidizing materials by a fire-resistant wall of one-hour rating or by a distance of twenty-five feet.

Not more than seven hundred fifty thousand small arms ammunition primers shall be stored in any one building except as next provided; no more than one hundred thousand shall be stored in any one pile, and piles shall be separated by at least fifteen feet.

Quantities of small arms ammunition primers in excess of seven hundred fifty thousand shall be stored in magazines in accordance with RCW 70.74.025.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c137.pdf?cite=1969%20ex.s.%20c%20137%20§%2031[1969 ex.s. c 137 § 31]; ]

== 70.74.360 - Licenses—Fingerprint and criminal record checks—Fee—Licenses prohibited for certain persons—License fees.
. The director of labor and industries shall require, as a condition precedent to the original issuance and upon renewal every three years thereafter of any explosive license, fingerprinting and criminal history record information checks of every applicant. In the case of a corporation, fingerprinting and criminal history record information checks shall be required for the management officials directly responsible for the operations where explosives are used if such persons have not previously had their fingerprints recorded with the department of labor and industries. In the case of a partnership, fingerprinting and criminal history record information checks shall be required of all general partners. Such fingerprints as are required by the department of labor and industries shall be submitted on forms provided by the department to the identification section of the Washington state patrol and to the identification division of the federal bureau of investigation in order that these agencies may search their records for prior convictions of the individuals fingerprinted. The Washington state patrol shall provide to the director of labor and industries such criminal record information as the director may request. The applicant shall give full cooperation to the department of labor and industries and shall assist the department of labor and industries in all aspects of the fingerprinting and criminal history record information check. The applicant shall be required to pay the current federal and state fee for fingerprint-based criminal history background checks.

. The director of labor and industries shall not issue a license to manufacture, purchase, store, use, or deal with explosives to:

.. Any person under twenty-one years of age;

.. Any person whose license is suspended or whose license has been revoked, except as provided in RCW 70.74.370;

.. Any person who has been convicted in this state or elsewhere of a violent offense as defined in RCW 9.94A.030, perjury, false swearing, or bomb threats or a crime involving a schedule I or II controlled substance, or any other drug or alcohol related offense, unless such other drug or alcohol related offense does not reflect a drug or alcohol dependency. However, the director of labor and industries may issue a license if the person suffering a drug or alcohol related dependency is participating in or has completed an alcohol or drug recovery program acceptable to the department of labor and industries and has established control of their alcohol or drug dependency. The director of labor and industries shall require the applicant to provide proof of such participation and control; or

.. Any person who has previously been adjudged to be mentally ill or insane, or to be incompetent due to any mental disability or disease and who has not at the time of application been restored to competency.

. The director of labor and industries may establish reasonable licensing fees for the manufacture, dealing, purchase, use, and storage of explosives.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1280-S.SL.pdf?cite=2009%20c%2039%20§%201[2009 c 39 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3381.SL.pdf?cite=2008%20c%20285%20§%2010[2008 c 285 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c198.pdf?cite=1988%20c%20198%20§%203[1988 c 198 § 3]; ]

== 70.74.370 - License revocation, nonrenewal, or suspension.
. The department of labor and industries shall revoke and not renew the license of any person holding a manufacturer, dealer, purchaser, user, or storage license upon conviction of any of the following offenses, which conviction has become final:

.. A violent offense as defined in RCW 9.94A.030;

.. A crime involving perjury or false swearing, including the making of a false affidavit or statement under oath to the department of labor and industries in an application or report made pursuant to this title;

.. A crime involving bomb threats;

.. A crime involving a schedule I or II controlled substance, or any other drug or alcohol related offense, unless such other drug or alcohol related offense does not reflect a drug or alcohol dependency. However, the department of labor and industries may condition renewal of the license to any convicted person suffering a drug or alcohol dependency who is participating in an alcoholism or drug recovery program acceptable to the department of labor and industries and has established control of their alcohol or drug dependency. The department of labor and industries shall require the licensee to provide proof of such participation and control;

.. A crime relating to possession, use, transfer, or sale of explosives under this chapter or any other chapter of the Revised Code of Washington.

. The department of labor and industries shall revoke the license of any person adjudged to be mentally ill or insane, or to be incompetent due to any mental disability or disease. The director shall not renew the license until the person has been restored to competency.

. The department of labor and industries is authorized to suspend, for a period of time not to exceed six months, the license of any person who has violated this chapter or the rules promulgated pursuant to this chapter.

. The department of labor and industries may revoke the license of any person who has repeatedly violated this chapter or the rules promulgated pursuant to this chapter, or who has twice had his or her license suspended under this chapter.

. The department of labor and industries shall immediately suspend the license or certificate of a person who has been certified pursuant to RCW 74.20A.320 by the department of social and health services as a person who is not in compliance with a support order or a *residential or visitation order. If the person has continued to meet all other requirements for reinstatement during the suspension, reissuance of the license or certificate shall be automatic upon the department of labor and industries' receipt of a release issued by the department of social and health services stating that the licensee is in compliance with the order.

. Upon receipt of notification by the department of labor and industries of revocation or suspension, a licensee must surrender immediately to the department any or all such licenses revoked or suspended.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20872[1997 c 58 § 872]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c198.pdf?cite=1988%20c%20198%20§%204[1988 c 198 § 4]; ]

== 70.74.380 - Licenses—Expiration—Extension of storage licenses.
With the exception of storage licenses for permanent facilities, every license issued under the authority of this chapter shall expire after one year from the date issued unless suspended or revoked. The director of labor and industries may extend the duration of storage licenses for permanent facilities to two years provided the location, distances, and use of the facilities remain unchanged. The fee for the two-year storage license shall be twice the annual fee.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c198.pdf?cite=1988%20c%20198%20§%209[1988 c 198 § 9]; ]

== 70.74.390 - Implementation of chapter and rules pursuant to chapter  49.17 RCW.
Unless specifically provided otherwise by statute, this chapter and the rules adopted thereunder shall be implemented and enforced, including penalties, violations, citations, appeals, and other administrative procedures, pursuant to the Washington industrial safety and health act, chapter 49.17 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c198.pdf?cite=1988%20c%20198%20§%2011[1988 c 198 § 11]; ]

== 70.74.400 - Seizure and forfeiture.
. Explosives, improvised devices, and components of explosives and improvised devices that are possessed, manufactured, delivered, imported, exported, stored, sold, purchased, transported, abandoned, detonated, or used, or intended to be used, in violation of a provision of this chapter are subject to seizure and forfeiture by a law enforcement agency and no property right exists in them.

. The law enforcement agency making the seizure shall notify the Washington state department of labor and industries of the seizure.

. Seizure of explosives, improvised devices, and components of explosives and improvised devices under subsection (1) of this section may be made if:

.. The seizure is incident to arrest or a search under a search warrant;

.. The explosives, improvised devices, or components have been the subject of a prior judgment in favor of the state in an injunction or forfeiture proceeding based upon this chapter;

.. A law enforcement officer has probable cause to believe that the explosives, improvised devices, or components are directly or indirectly dangerous to health or safety; or

.. The law enforcement officer has probable cause to believe that the explosives, improvised devices, or components were used or were intended to be used in violation of this chapter.

. A law enforcement agency shall destroy explosives seized under this chapter when it is necessary to protect the public safety and welfare. When destruction is not necessary to protect the public safety and welfare, and the explosives are not being held for evidence, a seizure pursuant to this section commences proceedings for forfeiture.

. The law enforcement agency under whose authority the seizure was made shall issue a written notice of the seizure and commencement of the forfeiture proceedings to the person from whom the explosives were seized, to any known owner of the explosives, and to any person who has a known interest in the explosives. The notice shall be issued within fifteen days of the seizure. The notice of seizure and commencement of the forfeiture proceedings shall be served in the same manner as provided in RCW 4.28.080 for service of a summons. The law enforcement agency shall provide a form by which the person or persons may request a hearing before the law enforcement agency to contest the seizure.

. If no person notifies the seizing law enforcement agency in writing of the person's claim of ownership or right to possession of the explosives, improvised devices, or components within thirty days of the date the notice was issued, the seized explosives, devices, or components shall be deemed forfeited.

. If, within thirty days of the issuance of the notice, any person notifies the seizing law enforcement agency in writing of the person's claim of ownership or right to possession of items seized, the person or persons shall be afforded a reasonable opportunity to be heard as to the claim or right. The hearing shall be before the chief law enforcement or the officer's designee of the seizing agency, except that the person asserting the claim or right may remove the matter to a court of competent jurisdiction if the aggregate value of the items seized is more than five hundred dollars. The hearing and any appeal shall be conducted according to chapter 34.05 RCW. The seizing law enforcement agency shall bear the burden of proving that the person (a) has no lawful right of ownership or possession and (b) that the items seized were possessed, manufactured, stored, sold, purchased, transported, abandoned, detonated, or used in violation of a provision of this chapter with the person's knowledge or consent.

. The seizing law enforcement agency shall promptly return the items seized to the claimant upon a determination that the claimant is entitled to possession of the items seized.

. If the items seized are forfeited under this statute, the seizing agency shall dispose of the explosives by summary destruction. However, when explosives are destroyed either to protect public safety or because the explosives were forfeited, the person from whom the explosives were seized loses all rights of action against the law enforcement agency or its employees acting within the scope of their employment, or other governmental entity or employee involved with the seizure and destruction of explosives.

. This section is not intended to change the seizure and forfeiture powers, enforcement, and penalties available to the department of labor and industries pursuant to chapter 49.17 RCW as provided in RCW 70.74.390.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6080-S2.SL.pdf?cite=2002%20c%20370%20§%203[2002 c 370 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1118-S.SL.pdf?cite=1993%20c%20293%20§%208[1993 c 293 § 8]; ]

== 70.74.410 - Reporting theft or loss of explosives.
A person who knows of a theft or loss of explosives for which that person is responsible under this chapter shall report the theft or loss to the local law enforcement agency within twenty-four hours of discovery of the theft or loss. The local law enforcement agency shall immediately report the theft or loss to the department of labor and industries.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1118-S.SL.pdf?cite=1993%20c%20293%20§%209[1993 c 293 § 9]; ]

