= 70.58A - Vital statistics.
:toc:

== 70.58A.005 - Purpose. (Effective January 1, 2021.)
. Protection of public health requires a vital records system that provides proof of vital life events and gathers population health data for assessment, evaluation, research, and other public health purposes. An efficient and effective vital records system is a foundational public health service to support a healthy and productive population.

. The purpose of this chapter is to provide a framework for ongoing administration of a single comprehensive vital records system in the state that is operated and maintained by the department, under the supervision of the state registrar, to preserve the security, integrity, and confidentiality of state vital records and vital statistics, established under RCW 43.70.130 and this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%201[2019 c 148 § 1]; ]

== 70.58A.010 - Definitions. (Effective January 1, 2021, until January 1, 2022.)
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Adult" means a person who is at least eighteen years of age, or an emancipated minor under chapter 13.64 RCW.

. "Amendment" means a change to a certification item on the vital record.

. "Authorized representative" means a person permitted to receive a certification who is:

.. Identified in a notarized statement signed by a qualified applicant; or

.. An agent identified in a power of attorney as defined in chapter 11.125 RCW.

. "Certification" means the document, in either paper or electronic format, containing all or part of the information contained in the original vital record from which the document is derived, and is issued from the central vital records system. A certification includes an attestation by the state or local registrar to the accuracy of information, and has the full force and effect of the original vital record.

. "Certification item" means any item of information that appears on certifications.

. "Coroner" means the person elected or appointed in a county under chapter 36.16 RCW to serve as the county coroner and fulfill the responsibilities established under chapter 36.24 RCW.

. "Cremated remains" has the same meaning as "cremated human remains" in chapter 68.04 RCW.

. "Delayed report of live birth" means the report submitted to the department for the purpose of registering the live birth of a person born in state that was not registered within one year of the date of live birth.

. "Department" means the department of health.

. "Domestic partner" means a party to a state registered domestic partnership established under chapter 26.60 RCW.

. "Facility" means any licensed establishment, public or private, located in state, which provides inpatient or outpatient medical, surgical, or diagnostic care or treatment; or nursing, custodial, or domiciliary care. The term also includes establishments to which persons are committed by law including, but not limited to:

.. Mental illness detention facilities designated to assess, diagnose, and treat individuals detained or committed, under chapter 71.05 RCW;

.. City and county jails;

.. State department of corrections facilities; and

.. Juvenile correction centers governed by Title 72 RCW.

. "Fetal death" means any product of conception that shows no evidence of life, such as breathing, beating of the heart, pulsation of the umbilical cord, or definite movement of voluntary muscles after complete expulsion or extraction from the individual who gave birth that is not an induced termination of pregnancy and:

.. Has completed twenty or more weeks of gestation as calculated from the date the last menstrual period of the individual who gave birth began, to the date of expulsion or extraction; or

.. Weighs three hundred fifty grams or more, if weeks of gestation are not known.

. "Final disposition" means the burial, interment, entombment, cremation, removal from the state, or other manner of disposing of human remains as authorized under chapter 68.50 RCW.

. "Funeral director" means a person licensed under chapter 18.39 RCW as a funeral director.

. "Funeral establishment" means a place of business licensed under chapter 18.39 RCW as a funeral establishment.

. "Government agencies" include state boards, commissions, committees, departments, educational institutions, or other state agencies which are created by or pursuant to statute, other than courts and the legislature; county or city agencies, United States federal agencies, and federally recognized tribes and tribal organizations.

. "Human remains" means the body of a deceased person, includes the body in any stage of decomposition, and includes cremated human remains, but does not include human remains that are or were at any time under the jurisdiction of the state physical anthropologist under chapter 27.44 RCW.

. "Individual" means a natural person.

. "Induced termination of pregnancy" means the purposeful interruption of an intrauterine pregnancy with an intention other than to produce a live-born infant, and which does not result in a live birth.

. "Informational copy" means a birth or death record issued from the central vital records system, containing all or part of the information contained in the original vital record from which the document is derived, and indicating it cannot be used for legal purposes on its face.

. "Legal guardian" means a person who serves as a guardian for the purpose of either legal or custodial matters, or both, relating to the person for whom the guardian is appointed. The term legal guardian includes, but is not limited to, guardians appointed pursuant to chapters *11.88 and 13.36 RCW.

. "Legal representative" means a licensed attorney representing either the subject of the record or qualified applicant.

. "Live birth" means the complete expulsion or extraction of a product of human conception from the individual who gave birth, irrespective of the duration of pregnancy, which, after such expulsion or extraction, breathes or shows any other evidence of life, such as beating of the heart, pulsation of the umbilical cord, or definite movement of voluntary muscles.

. "Local health officer" has the same meaning as in chapter 70.05 RCW.

. "Medical certifier" for a death or fetal death means an individual required to attest to the cause of death information provided on a report of death or fetal death. Each individual certifying cause of death or fetal death may certify cause of death only as permitted by that individual's professional scope of practice. These individuals include:

.. A physician, physician's assistant, or an advanced registered nurse practitioner last in attendance at death or who treated the decedent through examination, medical advice, or medications within the twelve months preceding the death;

.. A midwife, only in cases of fetal death; and

.. A physician performing an autopsy, when the decedent was not treated within the last twelve months and the person died a natural death.

. "Medical examiner" means the person appointed under chapter 36.24 RCW to fulfill the responsibilities established under chapter 36.24 RCW.

. "Midwife" means a person licensed to practice midwifery pursuant to chapter 18.50 RCW.

. "Physician" means a person licensed to practice medicine, naturopathy, or osteopathy pursuant to Title 18 RCW.

. "Registration" or "register" means the process by which a report is approved and incorporated as a vital record into the vital records system.

. "Registration date" means the month, day, and year a report is incorporated into the vital records system.

. "Report" means an electronic or paper document containing information related to a vital life event for the purpose of registering the vital life event.

. "Sealed record" means the original record of a vital life event and the evidence submitted to support a change to the original record.

. "Secretary" means the secretary of the department of health.

. "State" means Washington state unless otherwise specified.

. "State registrar" means the person appointed by the secretary to administer the vital records system under RCW 70.58A.030.

. "Territory of the United States" means American Samoa, the Commonwealth of the Northern Mariana Islands, the Commonwealth of Puerto Rico, Guam, and the United States Virgin Islands.

. "Vital life event" means a birth, death, fetal death, marriage, dissolution of marriage, dissolution of domestic partnership, declaration of invalidity of marriage, declaration of invalidity of domestic partnership, and legal separation.

. "Vital record" or "record" means a report of a vital life event that has been registered and supporting documentation.

. "Vital records system" means the statewide system created, operated, and maintained by the department under this chapter.

. "Vital statistics" means the aggregated data derived from vital records, including related reports, and supporting documentation.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%202[2019 c 148 § 2]; ]

== 70.58A.020 - Rule-making authority.
. The secretary shall have charge of the state vital records system and shall adopt rules to ensure implementation of the vital records system and this chapter.

. The secretary may adopt rules to set fees for services related to the vital records system including, but not limited to, expediting requests, verification and access for government agencies, registering reports of delayed birth, amending vital records, and releasing vital records and vital statistics.

. The state board of health may adopt, amend, or repeal rules requiring statistical information related to birth and manner of delivery.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%203[2019 c 148 § 3]; ]

== 70.58A.030 - Appointment of the state registrar. (Effective January 1, 2021.)
The secretary shall appoint the state registrar in accordance with RCW 43.70.020 and 43.70.150.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%204[2019 c 148 § 4]; ]

== 70.58A.040 - Duties of the state registrar. (Effective January 1, 2021.)
. The state registrar shall administer and enforce the provisions of this chapter and shall:

.. Administer the operation and maintenance of the vital records system to preserve the security, integrity, and confidentiality of state vital records and vital statistics established under RCW 43.70.130 and 43.70.150 and this chapter;

.. Prescribe paper and electronic forms needed to carry out the purposes of this chapter;

.. Prescribe the information required in forms, reports, vital records, certifications, or other documents authorized by this chapter;

.. Prescribe the means for transmission of data, including electronic submission, necessary to accomplish the purpose of complete, accurate, and timely reporting and registration;

.. Review reports to determine if additional information is necessary to register the report. If any reports are incomplete, the state registrar shall require submission of information necessary to make the record complete;

.. Deny or revoke registration of a report or application for an amendment, or withhold or deny issuance of a certification for the reasons permitted by this chapter;

.. Prepare and publish vital statistics pursuant to this chapter;

.. Prepare a plan to provide for the continuity of operations of the vital records system in the event of an emergency;

.. Take measures to prevent the fraudulent use of vital records; and

.. Perform data quality assurance and record matching activities.

. The state registrar may delegate functions and duties vested in the state registrar under this section to employees of the department.

. The state registrar may appoint a deputy state registrar, with the concurrence of the secretary, with the same authority granted to the state registrar under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%205[2019 c 148 § 5]; ]

== 70.58A.050 - Appointment of local and deputy registrars. (Effective January 1, 2021.)
. Under the direction and control of the state registrar, the local health officer of each health jurisdiction is and shall serve as local registrar.

. Subject to the approval of the state registrar, each local registrar shall appoint a sufficient number of deputy registrars to perform the duties prescribed by this chapter applicable to local registrars. The local registrar shall submit each proposed appointment to the state registrar in writing. The state registrar shall either approve or deny the appointment in writing prior to the assumption of duties by the deputy registrar. The state registrar may deny an appointment for good cause.

. The state registrar shall authorize a local or deputy registrar to access the electronic vital records databases to issue birth or death certifications upon the local or deputy registrar's appointment. Access and use of the database by the local or deputy registrar must be consistent with this chapter.

. The state board of health may remove the local health officer as local registrar upon finding evidence of neglect in the performance of duties as local registrar.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%206[2019 c 148 § 6]; ]

== 70.58A.060 - Vital records system security requirements—Fraud detection—Data validation. (Effective January 1, 2021.)
. A person may not prepare or issue any vital record that purports to be an original, certification of, or copy of a vital record except as authorized in this chapter.

. All certifications of vital records must include security features to deter alteration, counterfeiting, or simulation without ready detection.

. All informational copies must indicate that they cannot be used for legal purposes on their face.

. The state registrar may:

.. Authorize users of the vital records system to access specific components of the vital records system based on their official duties;

.. Require users authorized under this section to acknowledge having read and understood security procedures and penalties;

.. Revoke user access of the vital records system when the user violates security procedures or when the user no longer needs access to conduct official duties;

.. Ensure that state birth records are marked as deceased upon receipt of death records; and

.. Periodically test and audit the vital records system for purposes of detecting fraud. If fraud is suspected, the state registrar may provide copies of the evidence to appropriate authorities for further investigation consistent with the provisions of RCW 70.58A.580. The state registrar may retain the results of such tests and audits, which are not subject to inspection or copying except upon order of a court of competent jurisdiction.

. The state registrar may, at the state registrar's discretion, validate data provided in reports filed for registration through site visits or with independent sources outside the vital records system at a frequency specified by the state registrar to maximize the integrity of the data collected.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%207[2019 c 148 § 7]; ]

== 70.58A.070 - Mandatory use of prescribed forms, reporting of data required for registration. (Effective January 1, 2021.)
. Forms prescribed by the state registrar must be used in reporting, registering, and issuing certifications and informational copies, and preserving vital records, or in otherwise carrying out the purpose of this chapter.

. Reports must contain the data required for registration. No report may be held to be complete and correct that does not supply all items of information required under this chapter, or that does not satisfactorily account for the omission of required items.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%208[2019 c 148 § 8]; ]

== 70.58A.100 - Live birth of child of known parentage—Reporting and registration requirements. (Effective January 1, 2021.)
. A facility representative or midwife shall prepare and submit a report of live birth for each live birth at which that person attended that occurs in this state to the department within ten calendar days after the birth occurs. The facility representative or midwife shall:

.. Include all data and evidence required to establish the facts of live birth under this section;

.. Include parentage information consistent with chapters 26.26A and 26.26B RCW;

.. Include all statistical information required about the individual who gave birth;

.. Ensure the accuracy of the personal data entered on the report; and

.. Attest the child was born alive at the place and time, and on the date stated on the report.

. The health care provider or facility representative providing prenatal care shall provide the prenatal care information required for the report of live birth to the facility where the delivery is expected to occur not less than thirty calendar days prior to the expected delivery date.

. When a live birth occurs in a facility or en route to a facility, the facility representative shall submit the report of live birth consistent with this section.

. When a live birth occurs outside a facility and not en route to a facility, the report of live birth must be filed consistent with this section by the:

.. Health care provider in attendance of the live birth; or

.. Facility representative where the individual who gave birth and child are examined, if that examination happens within ten calendar days of live birth.

. For an unattended live birth not reported under subsection (4) of this section, a report of live birth and an affidavit stating the facts of the birth must be filed with the department within ten calendar days of the live birth.

.. The report of live birth must be completed and signed by a person with knowledge of the facts of the birth other than the individual who gave birth to the child.

.. The affidavit attesting to the facts of the birth must be completed and signed by the individual who gave birth, other parent, or other person with knowledge of the facts of the birth.

.. The report of live birth and affidavit must not be signed by the same person.

. When the live birth occurs on a moving conveyance:

.. Within the United States, and the child is first removed from the conveyance in state, the place where the child is first removed from the conveyance must be registered as the place of live birth;

.. While in international waters or air space, or in a foreign country or its air space, and the child is first removed from the conveyance in state, the live birth must be registered in this state. The report of live birth under this subsection must show the actual place of live birth insofar as can be determined.

. The facility representative or midwife shall provide written and oral information and required forms, furnished by the department of social and health services and the state registrar, to the parents of a child about establishing parentage pursuant to chapter 26.26A RCW.

. The state registrar may not register a report of live birth unless it has been completed and filed in accordance with this chapter.

. A report of a live born child of unknown parentage must be registered in accordance with RCW 70.58A.110.

. A delayed report of live birth filed after one year from the date of live birth must be registered in accordance with RCW 70.58A.120.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%209[2019 c 148 § 9]; ]

== 70.58A.110 - Live birth of child of unknown parentage—Reporting and registration requirements. (Effective January 1, 2021.)
. When a child is found for whom no record of live birth is known to be on file, within ten calendar days of the child being found, a report of a live birth must be filed with the department in a manner prescribed by the state registrar.

. If the child is identified at a later date and another live birth record is found, the state registrar shall void the record registered under subsection (1) of this section.

. This section cannot be used when the report of live birth is considered a delayed registration under RCW 70.58A.120 or an unattended live birth under RCW 70.58A.100(5).

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%2010[2019 c 148 § 10]; ]

== 70.58A.120 - Delayed report of live birth—Registration requirements. (Effective January 1, 2021.)
. An individual requesting a delayed report of live birth shall submit to the state registrar a completed and signed delayed report of live birth. Each report must include documentary evidence establishing the facts of the live birth and any applicable fees. The completed delayed report of live birth must be signed and sworn under penalty of perjury by the individual whose live birth is to be registered if the individual is an adult, or by the parent or legal guardian if the individual whose live birth is to be registered is not an adult.

. An individual requesting the delayed report of live birth of an individual under twelve years of age must establish the facts concerning full name, date, and place of live birth.

. An individual requesting the delayed report of live birth of an individual twelve years of age or over must establish the facts concerning full name, date, and place of live birth and the full name prior to first marriage of the individual who gave birth. Documentary evidence for an individual twelve years of age or over, other than affidavits, must have been established at least five years prior to the date of application.

. Each piece of documentary evidence must come from a unique source in the form of the original record or an exact copy thereof. The individual requesting the delayed report of live birth must either be able to authenticate the source of each document presented to the department, or present to the department a signed statement from the custodian of the record or document which attests to the authenticity of the document and the accuracy of the facts contained in the document.

. The state registrar may verify the authenticity and accuracy of documentary evidence provided by the individual requesting a delayed report of live birth.

. The state registrar shall not register a delayed report of live birth until all applicable provisions of this chapter have been met to the satisfaction of the state registrar.

. Upon review and approval of a delayed report of live birth, the state registrar shall register a delayed report of live birth. The delayed birth record must include a description of the evidence used to establish the delayed birth record.

. If the state registrar denies a delayed report of live birth, RCW 70.58A.130 is the sole remedy for decisions made under this section. The administrative procedure act, chapter 34.05 RCW, does not govern review of decisions on registration of delayed reports of live birth made by the state registrar under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%2011[2019 c 148 § 11]; ]

== 70.58A.130 - Court-ordered registration of a delayed report of live birth—Petition and hearing requirements—Burden and standard of proof. (Effective January 1, 2021.)
. If the state registrar denies a delayed report of live birth under the provisions of RCW 70.58A.120, the individual requesting the delayed report of live birth may petition a court of competent jurisdiction for an order establishing a record of the name, date, and place of the live birth, and parentage of the individual whose live birth is to be registered.

. The petition must allege:

.. The individual for whom a delayed report of live birth is sought was born in state;

.. No report of live birth of the individual can be found in the vital records system;

.. Diligent efforts by the petitioner have failed to obtain the evidence required in accordance with RCW 70.58A.120; and

.. The state registrar has denied a delayed report of live birth.

. The petition must be accompanied by a statement of the state registrar made in accordance with RCW 70.58A.120 and all documentary evidence to support such registration which was filed with the state registrar.

. The court shall fix a time and place for hearing the petition. The petitioner shall serve the state registrar with notice of the time and place for hearing and shall include with such notice the petition filed with the court. The petitioner shall give the state registrar notice at least thirty calendar days prior to the date set for the hearing.

. The state registrar, or the state registrar's designee, may present at the hearing any information the state registrar believes will be useful to the court. The state registrar is not required to attend or appear for the hearing, and the court may proceed without the state registrar if the state registrar does not appear at the designated time and place set for hearing in the notice.

. The burden of proof is on the petitioner.

. If the court finds, by clear and convincing evidence, that the individual for whom a delayed report of live birth is sought was born in state, the court shall issue an order requiring the state registrar to establish a delayed record of live birth. This order must include, at a minimum, the following findings:

.. The full name, city and county of live birth, and birth date to be registered of the individual whose live birth is to be registered;

.. The full name, state or country of birth, and date of birth of the individual who gave birth; and

.. A statement of the evidence relied on by the court in making the order.

. The clerk of the court shall forward the order to the state registrar within five business days after the order is entered.

. The state registrar shall register the live birth upon receipt of an order to register a delayed report of live birth from a court of competent jurisdiction, and must include the court case number and the date of the order in the vital record.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%2012[2019 c 148 § 12]; ]

== 70.58A.200 - Reports of death—Filing and registration requirements. (Effective January 1, 2021.)
. [Empty]
.. Reports of death and fetal death must comply with the requirements of this section.

.. For the purposes of this section, "death" includes "fetal death" as defined in RCW 70.58A.010.

. A complete report of death must be filed with the local registrar in the local health jurisdiction where the death occurred for each death that occurs in this state. Except for circumstances covered by subsection (7) of this section, the report must be filed within five calendar days after the death or finding of human remains and prior to final disposition of the human remains as required by this section.

.. If the place of death is unknown and the human remains are found in state prior to final disposition, the death must be filed in state and the place where the human remains were found is the place of death.

.. When death occurs in a moving conveyance within or outside the United States and the human remains are first removed from the conveyance in state, the death must be filed in state and the place of death is the place where the remains were removed from the moving conveyance.

.. In all other cases, the place where death is pronounced is the place where death occurred.

.. An approximate date of death may be used if date of death is unknown. If the date cannot be determined by approximation, the date of death must be the date the human remains were found.

. If the death occurred with medical attendance, a funeral director, funeral establishment, or person having the right to control the disposition of the human remains under RCW 68.50.160 shall:

.. Obtain and enter personal data on the report of death about the decedent from the person best qualified to provide the information;

.. Provide the report of death to the medical certifier within two calendar days after the death or finding of human remains;

.. File the completed report of death with the local registrar; and

.. Obtain a burial-transit permit prior to the disposition of the human remains as required in RCW 70.58A.210.

. The medical certifier shall:

.. Attest to the cause, date, and time of death; and

.. Return the report of death to the funeral director, funeral establishment, or person having the right to control the disposition of the human remains under RCW 68.50.160 within two calendar days.

. The report of death may be completed by another individual qualified to be a medical certifier as defined in RCW 70.58A.010 who has access to the medical history of the decedent when:

.. The medical certifier is absent or unable to attest to the cause, date, and time of death; or

.. The death occurred due to natural causes, and the medical certifier gives approval.

. If the death occurred without medical attendance, the funeral director, funeral establishment, or person having the right to control the disposition of the human remains under RCW 68.50.160 shall provide the report of death to the coroner, medical examiner, or local health officer as allowed by (a) of this subsection.

.. If the death occurred due to natural causes, the coroner, medical examiner, or local health officer shall determine whether to certify the report of death. If the coroner, medical examiner, or local health officer decides to certify the report of death, the person certifying the report shall:

... Attest to the manner, cause, and date of death without holding an inquest or performing an autopsy or postmortem, based on statements of relatives, persons in attendance during the last sickness, persons present at the time of death, or other persons having adequate knowledge of the facts;

... Note that there was no medical attendance at the time of death; and

... Return the report of death to the funeral home within two calendar days.

.. If the death appears to be the result of unlawful or unnatural causes, the coroner or medical examiner shall:

... Attest to the cause, place, and date of death;

... Note that there was no medical attendance at the time of death;

... Note when the cause of death is pending investigation; and

... Return the report of death to the funeral director, funeral establishment, or person having the right to control the disposition of the human remains under RCW 68.50.160 within two calendar days.

. When there is no funeral director, funeral establishment, or person having the right to control the disposition of human remains under chapter 68.50 RCW, the coroner, medical examiner, or local health officer shall file the completed report of death with the local registrar as required by subsection (2) of this section.

. When a coroner or medical examiner determines that there is sufficient circumstantial evidence to indicate that an individual has died in the county or in waters contiguous to the county, and that it is unlikely that the body will be recovered, the coroner or medical examiner shall file a report of death, including the cause, place, and date of death, to the extent possible.

. The coroner or medical examiner in a county in which a decedent was last known to be alive may file a report of death with the local registrar when the county in which the presumed death occurred cannot be determined with certainty. The coroner or medical examiner shall file a report of death, including the cause, place, and date of death, to the extent possible.

. The coroner or medical examiner having jurisdiction may release information contained in a report of death according to RCW 68.50.300.

. The local registrar shall:

.. Review filed reports of death to ensure completion in accordance with this chapter;

.. Request missing information or corrections;

.. Ensure issuance of the burial-transit permit as required under RCW 70.58A.210;

.. Register a report of death with the department if it has been completed and submitted in accordance with this section.

. A medical certifier, coroner, medical examiner, or local health officer shall submit an affidavit of correction to the state registrar to amend the report of death within five calendar days of receipt of an autopsy result or other information that completes or amends the cause of death from that originally filed with the department.

. The department may require a medical certifier, coroner, medical examiner, or local health officer to provide additional or clarifying information to properly code and classify cause of death.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%2013[2019 c 148 § 13]; ]

== 70.58A.210 - Final disposition of human remains—Issuance of burial-transit and disinterment permits. (Effective January 1, 2021.)
. [Empty]
.. Reports of death and fetal death must comply with the requirements of this section.

.. For the purposes of this section, "death" includes "fetal death" as defined in RCW 70.58A.010.

. If a report of death is completed and filed in accordance with this chapter, the local registrar shall issue a burial-transit permit or disinterment permit to the funeral director, funeral establishment, or person having the right to control the disposition of the human remains under RCW 68.50.160.

. A person may not provide for final disposition of human remains until the following have occurred:

.. The report of death has been registered in accordance with RCW 70.58A.200; and

.. The funeral director, funeral establishment, or person having the right to control the disposition of the human remains under RCW 68.50.160 has obtained a burial-transit permit authorizing final disposition.

. A funeral director, funeral establishment, or person having the right to control the disposition of the human remains under RCW 68.50.160 shall:

.. Deliver the burial-transit permit to the person in charge of the funeral establishment licensed under chapter 18.39 RCW, crematory with a permit or endorsement under RCW 68.05.175, or cemetery authority as defined in RCW 68.04.190 before interring the human remains; or

.. Attach the burial-transit permit to the container holding the human remains when shipped by a transportation company.

. Final disposition of human remains must be completed in accordance with chapter 68.50 RCW.

. A person in charge of a funeral establishment licensed under chapter 18.39 RCW or cemetery authority as defined in RCW 68.04.190:

.. May not allow the final disposition of human remains unless accompanied by a burial-transit permit;

.. Shall indicate on the burial-transit permit the date and type of final disposition;

.. Shall return all completed and signed or electronically approved burial-transit permits to the local registrar for the county in which the death occurred within ten days of final disposition;

.. Shall keep a record of all human remains disposed of on the premises, including the:

... Name of the deceased individual;

... Place of death;

... Date of disposition; and

... Name and address of the funeral director, funeral establishment, or other person having the right to control the disposition of the human remains under RCW 68.50.160.

. When there is no person in charge of the place of final disposition, the funeral director, funeral establishment, or person having the right to control the disposition of the human remains under RCW 68.50.160 shall write across the face of the permit the words "no person in charge."

. A funeral director, funeral establishment, or person having the right to control the disposition of the human remains under RCW 68.50.160 must obtain a disinterment permit from the local registrar to disinter human remains or a burial-transit permit from the local registrar to reinter human remains.

. A person may not bring into or transport within this state; inter, deposit in a vault, grave, or tomb; or cremate or otherwise dispose of the human remains of any person whose death occurred outside the state, unless the human remains are accompanied by a burial-transit permit or other document issued in accordance with the laws in force where the death occurred. A burial-transit permit is not required for the spreading of cremated remains in accordance with the laws regulating the scattering of cremated remains in state, federal, and international lands or water.

. A funeral director or funeral establishment licensed under chapter 18.39 RCW, or a funeral establishment licensed in Oregon or Idaho, may remove human remains from the local health jurisdiction where the death occurred to another local health jurisdiction or Oregon or Idaho without having obtained a burial-transit permit if the funeral director or funeral establishment:

.. Has been issued a certificate of removal registration by the director of the department of licensing; and

.. Initiates a report of death with the local registrar where the death occurred.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%2014[2019 c 148 § 14]; ]

== 70.58A.300 - Registration of reports of marriage. (Effective January 1, 2021.)
The state registrar shall register reports of marriage received from a state county auditor pursuant to chapter 26.04 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%2015[2019 c 148 § 15]; ]

== 70.58A.310 - Registration of reports of legal separation, dissolution, and declaration of invalidity of marriage or domestic partnership. (Effective January 1, 2021.)
The state registrar shall register reports of legal separation, dissolution of marriage, dissolution of domestic partnership, declaration of invalidity of marriage, and declaration of invalidity of domestic partnership from the clerk of each state superior court pursuant to chapter 26.09 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%2016[2019 c 148 § 16]; ]

== 70.58A.400 - Adoption—Amendment of birth record or registration of birth—Sealing of original birth record. (Effective January 1, 2021.)
. The state registrar shall amend the birth record of a child born in state to reflect an adoption decree received from a Washington state court of competent jurisdiction upon receipt of:

.. An application to register an adoption;

.. A certified copy of the adoption decree entered pursuant to chapter 26.33 RCW; and

.. Applicable fees established under this chapter and by rule.

. The state registrar shall amend the live birth record of a child born in state to reflect an adoption report from any other state or territory of the United States, and the District of Columbia, upon receipt of:

.. A certified copy of an adoption report, or an application to register an adoption and a certified copy of the adoption decree; and

.. Applicable fees established under this chapter and by rule.

. The state registrar shall register the birth of a child born outside the United States and its territories and adopted after January 1, 1985, in a Washington state court of competent jurisdiction upon receipt of:

.. An application to register an adoption;

.. A certified copy of a decree of adoption entered pursuant to chapter 26.33 RCW; and

.. Applicable fees established under this chapter and by rule.

. The state registrar shall register the birth of a child born outside the United States and its territories and adopted before January 1, 1985, in a Washington state court of competent jurisdiction upon receipt of:

.. An application to register an adoption;

.. A certified copy of a decree of adoption entered pursuant to chapter 26.33 RCW;

.. Documentary evidence as to the child's birthdate and birthplace provided by:

... The original birth certification;

... A certified copy, extract, or translation of the original birth certification; or

... A certified copy of another document essentially equivalent to the original birth certification including, but not limited to, the records of the United States citizenship and immigration services or the United States department of state; and

.. Applicable fees established under this chapter and by rule.

. The state registrar shall retain and seal the original birth record including the adoption report, certified copy of the adoption decree, and other documentary evidence filed pursuant to chapter 26.33 RCW. The sealed record is not subject to public inspection or copying pursuant to chapter 42.56 RCW and may be released only as allowed by RCW 26.33.345.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%2017[2019 c 148 § 17]; ]

== 70.58A.500 - Amendment of vital records—When authorized—Grounds for denial. (Effective January 1, 2021.)
. The state registrar may amend certification items on state vital records.

. The state registrar may amend a live birth record to change the name of a person born in state:

.. Upon receipt of a complete and signed amendment application with applicable fees and a certified copy of an order of a court of competent jurisdiction, including the name of the person as it appears on the current live birth record and the new name to be designated on the amended live birth record, under RCW 4.24.130; or

.. As authorized under 18 U.S.C. Sec. 3521, the federal witness relocation and protection act.

. The state registrar shall seal the original live birth record amended under subsection (2)(b) of this section. The sealed record is not subject to public inspection and copying under chapter 42.56 RCW except upon order of a court of competent jurisdiction.

. The state registrar may amend a vital record to change the sex designation of the subject of the record. The state registrar shall include a nonbinary option for sex designation on the record.

. The state registrar may amend vital records for purposes other than those established in this section.

. The state registrar may deny an application to amend a vital record when:

.. The application is not completed or filed in accordance with this chapter;

.. The state registrar has cause to question the validity or adequacy of the applicant's statements or documentary evidence; or

.. The deficiencies under (a) or (b) of this subsection are not addressed to the satisfaction of the state registrar.

. The state registrar shall provide notice of the denial of an application to amend a vital record and state the reasons for the denial. If the state registrar denies an amendment to a vital record under the provisions of this section, a person may appeal the decision under RCW 70.58A.550.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%2018[2019 c 148 § 18]; ]

== 70.58A.510 - Preservation of vital records—Transfer to state archives. (Effective January 1, 2021.)
. The state registrar shall develop and implement a preservation management policy for the vital records system for permanent preservation while in the custody of the state registrar.

. The state registrar shall transfer the custody of vital records to the state archives in accordance with state archival procedures when:

.. One hundred years have elapsed after the date of live birth or fetal death;

.. Twenty-five years have elapsed after the date of death; and

.. Twenty-five years have elapsed after the date of marriage, divorce, dissolution of marriage, dissolution of domestic partnership, declaration of invalidity of marriage, declaration of invalidity of domestic partnership, or legal separation.

. The state archives may provide noncertified copies of original vital records in the custody of the state archives, due to a transfer under subsection (2) of this section, to the public.

. The state archives may not:

.. Charge the department a fee or pass along costs to transfer the vital records to state archives or maintain the vital records in the state archives, other than those charged through the central services billing model for the cost of operating the state archives; or

.. Alter, amend, or delete certification items on the vital records.

. Sealed records must remain sealed and in the custody of the department.

. In consultation with the state archives, the state registrar shall prescribe the format and method of delivery of vital records transferred to the state archives.

. The department may retain records for the purpose of issuing certifications under RCW 70.58A.530.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%2019[2019 c 148 § 19]; ]

== 70.58A.520 - Disclosure of vital records, data, and vital statistics—When authorized. (Effective January 1, 2021.)
. The department may disclose vital records information for persons named in any birth, death, or fetal death record only as provided under this chapter.

. Proposals for research and public health purposes must be reviewed and approved as to scientific merit and adequacy of confidentiality safeguards in accordance with this section.

. The department may release birth and fetal death record data that includes direct identifiers for research with approval of the state institutional review board and receipt of a signed confidentiality agreement with the department.

. The department may release birth and fetal death record data that includes direct identifiers for nonresearch public health purposes to a government agency upon receipt of a signed written data-sharing agreement with the department.

. The department may release birth and fetal death record data that contains only indirect identifiers to anyone upon receipt of a signed written data-sharing agreement with the department.

. The department may release death record data to anyone upon approval of the department and receipt of a signed written data-sharing agreement with the department.

. A written data-sharing agreement required under subsections (4) through (6) and (14) through (17) of this section must, at a minimum:

.. Include a description of the type of data needed and the purpose for how the data will be used;

.. Include the methods to be used to protect the confidentiality and security of the data;

.. State that ownership of the data provided under this section remains with the department, and is not transferred to those authorized to receive and use the data under the agreement; and

.. Include the applicable fees for use of the data.

. In addition to the conditions required by subsection (7) of this section, the written data-sharing agreement for birth and fetal death record data for public health purposes under subsection (4) of this section must:

.. Prohibit redisclosure of any direct or indirect identifiers without explicit permission from the department; and

.. Prohibit the recipient of the data from contacting or attempting to contact the person whose information is included in the data set or that person's family members without explicit permission from the department.

. In addition to the conditions required by subsection (7) of this section, the written data-sharing agreement for birth or fetal death record data with indirect identifiers under subsection (5) of this section must prohibit the recipient of the data from attempting to determine the identity of persons whose information is included in the data set or use the data in any manner that identifies individuals or their family members.

. The department and the state institutional review board shall apply the most restrictive law governing data release to proposals for research and public health purposes requesting data sets with direct identifiers for linkage to other data sets.

. The department may provide the fewest birth and fetal death record data elements necessary for the purpose described in the proposal for research or public health purposes.

. The department may deny a request for data for cause including, but not limited to, when:

.. Indirect identifiers are sufficient for the purpose described in the proposal for research or public health purposes;

.. The research or public health proposal lacks scientific merit;

.. The department lacks resources or the request would result in an unreasonable use of resources related to data preparation and analysis;

.. The requestor cannot meet the requirements in a data-sharing agreement for protecting the confidentiality of the data; or

.. The requestor is out of compliance with an existing data-sharing agreement.

. The department must provide notice of the denial to the requestor and include a statement of the reasons for the denial. If the state registrar denies a request for data under the provisions of this section, a person may appeal the decision under RCW 70.58A.550.

. The department may release vital records to government agencies in the conduct of official duties upon approval of the state registrar and receipt of a signed written data-sharing agreement with the department that prohibits redisclosure of any direct or indirect identifiers without explicit permission from the department. Vital records information released by the department under this subsection may be limited to only the information necessary to perform the official duties of the agencies to which the information is released. The department may deny requests according to subsection (12) of this section. Government agencies may access records electronically and use of records must be limited to the information needed for official business. The agreement may include cost sharing for support of the electronic system.

. The department shall make available to the department of social and health services, division of child support, the social security numbers of parents listed on birth records as required for establishing child support upon receipt of a signed written data-sharing agreement with the department.

. The department may release vital records to the national center for health statistics to be used solely for national statistics upon approval of the state registrar and receipt of a signed written data-sharing agreement with the department.

. The department may release copies of vital records through an interjurisdictional exchange agreement to offices of vital statistics in states or territories of the United States, the District of Columbia, New York City, or neighboring countries. The records must relate to a resident of, a person born in, or a person who died in the requesting state, territory, the District of Columbia, New York City, or neighboring country.

. The department may release indices of death, marriage, and divorce records annually to the state archives.

. Nothing in this chapter may be construed as giving authority to the state or local registrar, department, government agencies, or data recipients to sell or provide access to lists of individuals when requested for commercial purposes.

. For the purposes of this section:

.. "Data" means a data file containing multiple records.

.. "Direct identifier" means a single data element that identifies an individual person.

.. "Indirect identifier" means a single data element that on its own does not identify an individual person, but when combined with other indirect identifiers can be used to identify an individual person.

.. "Public health purpose" means a purpose that seeks to support or evaluate public health activities which include, but are not limited to, health surveillance; identifying population health trends; health assessments; implementing educational programs; program evaluation; developing and implementing policies; determining needs for access to services and administering services; creating emergency response plans; promoting healthy lifestyles; and preventing, detecting, and responding to infectious diseases, injury, and chronic and inheritable conditions. Public health purpose does not include research as defined in this section.

.. "Research" means a systematic investigation, including research development, testing, and evaluation, designed to develop or contribute to generalizable knowledge. Activities that meet this definition constitute research for purposes of this policy, whether or not they are conducted or supported under a program that is considered research for other purposes.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%2020[2019 c 148 § 20]; ]

== 70.58A.530 - Issuance of certifications and informational copies of vital records. (Effective January 1, 2021.)
. [Empty]
.. A certification issued in accordance with this section is considered for all purposes the same as the original vital record and is prima facie evidence of the facts stated therein.

.. An informational copy is not considered the same as the original vital record and does not serve as prima facie evidence of the facts stated therein.

. The state and local registrar shall issue all certifications registered in the vital records system from the state's central vital records system database upon submission by a qualified applicant of all required information and documentation required either by this chapter or by rule, or both, and shall ensure that all certifications include:

.. The date of registration; and

.. Security features that deter altering, counterfeiting, or simulation without ready detection as required under this chapter.

. A person requesting a certification of birth, death, or fetal death must submit an application, identity documentation, evidence of eligibility, and the applicable fee established in RCW 70.58A.560 to the state or local registrar.

. For a certification of birth, the state or local registrar may release the certification only to:

.. The subject of the record or the subject of the record's spouse or domestic partner, child, parent, stepparent, stepchild, sibling, grandparent, great grandparent, grandchild, legal guardian, legal representative, or authorized representative; or

.. A government agency or court, if the certification will be used in the conduct of the agency's or court's official duties.

. The state registrar may issue an heirloom certification of birth to a qualified applicant consistent with subsection (4) of this section. The heirloom certification of birth must contain the state seal and be signed by the governor.

. The state registrar may issue a certification of a birth record registered as delayed under RCW 70.58A.120 or 70.58A.130 to a qualified applicant consistent with subsection (4) of this section. The certification must:

.. Be marked as delayed; and

.. Include a description of the evidence or court order number used to establish the delayed record.

. The state registrar may issue a certification of a birth record for a person adopted under chapter 26.33 RCW and registered under RCW 70.58A.400 to a qualified applicant consistent with subsection (4) of this section. The certification:

.. Must not include reference to the adoption of the child; and

.. For children born outside of the state, must be issued consistent with the certification standards of this section, unless the court orders otherwise.

. When providing a birth certification to a qualified applicant under this chapter, the state or local registrar shall include information prepared by the department setting forth the advisability of a security freeze under RCW 19.182.230 and the process for acquiring a security freeze.

. For a certification of death, the state or local registrar may release the certification only to:

.. The decedent's spouse or domestic partner, child, parent, stepparent, stepchild, sibling, grandparent, great grandparent, grandchild, legal guardian immediately prior to death, legal representative, authorized representative, or next of kin as specified in RCW 11.28.120;

.. A funeral director, the funeral establishment licensed pursuant to chapter 18.39 RCW, or the person having the right to control the disposition of the human remains under RCW 68.50.160 named on the death record, within twelve months of the date of death; or

.. A government agency or court, if the certification will be used in the conduct of the agency's or court's official duties.

. The state or local registrar may issue a short form certification of death that does not display information relating to cause and manner of death to a qualified applicant. In addition to the qualified applicants listed in subsection (9) of this section, a qualified applicant for a short form certification of death includes:

.. A title insurer or title insurance agent handling a transaction involving real property in which the decedent held some right, title, or interest; or

.. A person that demonstrates that the certified copy is necessary for a determination related to the death or the protection of a personal or property right related to the death.

. For a certification of fetal death, the state or local registrar may release the certification only to:

.. A parent, a parent's legal representative, an authorized representative, a sibling, or a grandparent;

.. The funeral director or funeral establishment licensed pursuant to chapter 18.39 RCW and named on the fetal death record, within twelve months of the date of fetal death; or

.. A government agency or court, if the certification will be used in the conduct of the agency's or court's official duties.

. The state or local registrar shall review the identity documentation and evidence of eligibility to determine if the person requesting the certification is a qualified applicant under this section. The state or local registrar may verify the identity documents and evidence of eligibility to determine the acceptability and authenticity of identity documentation and evidence of eligibility.

. The state or local registrar may not issue a certification of birth or fetal death that includes information from the confidential section of the birth or fetal death record, except as provided in subsection (14) of this section.

. The state registrar may release information contained in the confidential section of the birth record only to the following persons:

.. The individual who is the subject of the birth record, upon confirmation of documentation and evidence of identity of the requestor in a manner approved by the state board of health and the department. The state registrar must limit the confidential information provided to the individual who is the subject of the birth record's information, and may not include the parent's confidential information; or

.. A member of the public, upon order of a court of competent jurisdiction.

. A person requesting a certification of marriage, dissolution of marriage, or dissolution of domestic partnership currently held by the department must submit an application and the applicable fee established in RCW 70.58A.560 to the state registrar.

. The state registrar may mark deceased on a birth certification when that birth record is matched to a death record under RCW 70.58A.060.

. The state or local registrar must issue an informational copy from the central vital records system to anyone. Informational copies must contain only the information allowed by rule. Informational copies of death records must not display information related to cause and manner of death.

. A person requesting an informational copy must submit an application and the applicable fee established in RCW 70.58A.560 to the state or local registrar.

. If no record is identified as matching the information provided in the application, the state or local registrar shall issue a document indicating that a search of the vital records system was made and no matching record was identified.

. All government agencies or courts to whom certifications or informational copies are issued must pay the applicable fee for certifications established in RCW 70.58A.560.

. The state or local registrar must comply with the requirements of this chapter when issuing a certification or informational copy of a vital life event.

. The department may issue, through electronic means and processes determined by the department, verifications of information contained on birth or death records filed with the department when a verification is requested by a government agency, insurance company, hospital, or any other organization in the conduct of its official duties for fraud prevention and good governance purposes as determined by the department. The department shall charge a fee for a search under this subsection.

. For the purposes of this section, a "qualified applicant" means a person who is eligible to receive a certification of a vital record based on the standards established by this chapter and department rule.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%2021[2019 c 148 § 21]; ]

== 70.58A.540 - Vital records not subject to public disclosure—Exceptions. (Effective January 1, 2021.)
. All or part of any vital records, reports, supporting documentation, vital statistics, data, or information contained therein are not subject to public inspection and copying under chapter 42.56 RCW.

. With the exception of certifications and informational copies issued under RCW 70.58A.530, or unless otherwise authorized by this chapter, no person may permit the inspection of, disclose data or information contained in, or copy or issue a copy of all or part of any vital records, reports, supporting documentation, vital statistics, data, or information contained therein.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%2022[2019 c 148 § 22]; ]

== 70.58A.550 - Adjudicative proceedings. (Effective January 1, 2021.)
. This section governs any case in which the state registrar takes one of the following adverse actions:

.. Denies or revokes registration of a report or application for an amendment;

.. Withholds or denies issuance of a certification under this chapter; or

.. Denies a request for data under RCW 70.58A.520.

. This section does not govern denied applications for delayed birth registration under RCW 70.58A.120, or amendments due to legal name change, adoption, or parentage, which require court orders.

. RCW 43.70.115 does not govern adjudications under this chapter.

. The department shall give written notice to the applicant when it denies or revokes registration of a report or application for certification, or withholds issuance of a certification. The written notice must state the reasons for the action and be served on the applicant or person to whom the record pertains. "Service" means posting in the United States mail, delivery to a commercial parcel delivery company, or personal service. Service by mail is complete upon deposit of the notice in the United States mail. Service by a commercial parcel delivery company is complete upon delivery to the commercial parcel delivery company, properly addressed, with charges prepaid.

. Except as otherwise provided in this subsection and in subsection (7) of this section, only revocation is effective twenty-eight days after service of the notice. The department may make the date the action is effective sooner than twenty-eight days after service when necessary to protect public health, safety, or welfare, or when deemed necessary by the state registrar for the security of the vital record. When the department does so, it shall state the effective date and the reasons supporting the effective date in the notice.

. Except as otherwise provided in subsection (7) of this section, denial of the registration of a report or application for an amendment under subsection (1)(a) of this section, and actions under subsection (1)(b) and (c) of this section, are effective immediately upon service of the notice.

. An applicant has the right to an adjudicative proceeding. The proceeding is governed by the administrative procedure act, chapter 34.05 RCW. The request for an adjudicative proceeding must be in writing, state the basis for contesting the adverse action, include a copy of the adverse notice, be served on and received by the department within twenty-eight days of service of the adverse notice, and be served in a manner that shows proof of receipt.

. If the department gives an applicant twenty-eight days' notice of revocation and the applicant or person to whom the record pertains files an appeal before its effective date, the department shall not implement the adverse action until the final order has been entered. The presiding or reviewing officer may permit the department to implement part or all of the adverse action while the proceedings are pending if the appellant causes an unreasonable delay in the proceeding, if the circumstances change so that implementation is in the public interest, or for other good cause.

. If the department gives an applicant less than twenty-eight days' notice of revocation and the applicant or person to whom the record pertains timely files a sufficient appeal, the department may implement the adverse action on the effective date stated in the notice. The presiding or reviewing officer may order the department to stay implementation of part or all of the adverse action while the proceedings are pending if staying implementation is in the public interest or for other good cause.

. The department is authorized to adopt a brief adjudicative proceeding for proceedings under this chapter, in accordance with chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%2023[2019 c 148 § 23]; ]

== 70.58A.560 - Fees for certifications or informational copies of vital records—Exceptions. (Effective January 1, 2021.)
. The department and local registrars shall charge a fee of twenty-five dollars for a certification or informational copy of a vital record or for a search of the vital records system when no matching record was identified, except as provided in subsection (2) of this section.

. The department and local registrars may not charge a fee for issuing a certification of:

.. A vital record for use in connection with a claim for compensation or pension pending before the veterans administration;

.. The death of a sex offender, for use by a law enforcement agency in maintaining a registered sex offender database; or

.. The death of any offender, requested by a county clerk or court in the state for purposes of extinguishing the offender's legal financial obligation.

. The department may not charge a fee for issuing a birth certification for homeless persons as defined in RCW 43.185C.010 living in state.

. The department and local registrars may charge an electronic payment fee, in addition to the twenty-five dollar fee for certification and informational copy of vital records or for a search of the vital records system, in cases where payment is made by credit card, charge card, debit card, smart card, stored value card, federal wire, automatic clearinghouse system, or other electronic communication.

. Local registrars shall keep a true and correct account of all fees received under this section for the issuance of certifications and informational copies.

. A portion of the twenty-five dollar fee collected by the local registrars must be transmitted to the state treasurer on a monthly basis as follows:

.. Thirteen dollars for each birth certification and birth informational copy issued;

.. Thirteen dollars for each first copy of a death certification and death informational copy; and

.. Twenty dollars for each additional death certification and death informational copy.

. For each fee turned over to the state treasurer by the local registrars, the state treasurer shall:

.. Pay the department two dollars of each fee for birth certifications and birth informational copies and first copies of death certifications and death informational copies;

.. Pay the department nine dollars of each fee for additional death certifications and death informational copies; and

.. Hold eleven dollars of each fee in the death investigations account established under RCW 43.79.445, except for an heirloom birth certification issued under RCW 70.58A.530.

. Eleven dollars of the twenty-five dollar fee collected by the department for certifications and informational copies issued by the department must be transmitted to the state treasurer for the death investigations account established under RCW 43.79.445.

. The department of children, youth, and families shall set a fee for an heirloom birth certification established under RCW 70.58A.530 for the children's trust fund established under RCW 43.121.100. The department shall collect the fee established under this subsection when issuing an heirloom birth certification and transmit the fees collected to the state treasurer for credit to the children's trust fund.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%2024[2019 c 148 § 24]; ]

== 70.58A.570 - Duty of local registrar to submit monthly reports—Duty of state registrar to periodically test and audit fraud prevention procedures. (Effective January 1, 2021.)
. The local registrar shall, on a monthly basis, submit the following to the state registrar:

.. A summary of the number of certifications and informational copies issued by vital life event type in a format provided by the state registrar;

.. A log of all numbered paper certifications issued and destroyed in a format provided by the state registrar; and

.. A copy of the accounting of fees required by RCW 70.58A.560.

. The state registrar shall periodically test and audit local registrar fraud prevention procedures and products, and may share the results of such tests and audits with the local registrar.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%2025[2019 c 148 § 25]; ]

== 70.58A.580 - Enforcement—Duties of local registrars—Investigations. (Effective January 1, 2021.)
. All requirements of this chapter must be uniformly complied with by all local registrars in state.

. Local registrars are charged with the strict and thorough enforcement of the provisions of this chapter in their health jurisdictions, under the supervision and direction of the state registrar, and:

.. Shall immediately report observed or suspected violations of this chapter to the state registrar;

.. Shall aid the state registrar, upon request, in investigations initiated under this section; and

.. May not issue a certification for a record that is currently under investigation under this section, or subject to an action under RCW 70.58A.550, until such time as the state registrar allows for the issuance of such certification.

. The state registrar may investigate cases of irregularity or violation of this chapter. In cases where the state registrar finds reasonable cause to suspect fraud or misrepresentation, the state registrar shall:

.. Retain the application and evidence; and

.. Notify the appropriate authorities.

. The state registrar may only release the application and evidence under subsection (3)(a) of this section upon order of a court of competent jurisdiction.

. When the state registrar deems it necessary, the state registrar shall report cases of violation of any of the provisions of this chapter to the prosecuting attorney of the proper county with a statement of the facts and circumstances.

. Prosecuting attorneys, or officials acting in such capacity, shall initiate and promptly follow up the necessary court proceedings against the parties responsible for the alleged violations of law reported to them by the state registrar.

. The state registrar may, during the pendency of an investigation under subsection (3) of this section, or at the conclusion of an investigation under subsection (3) of this section, take any action permitted by this chapter with respect to the affected certification or record including, but not limited to, denial of issuance or revocation of the affected certification or record.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%2026[2019 c 148 § 26]; ]

== 70.58A.590 - Penalties. (Effective January 1, 2021.)
. Every person who violates or willfully fails, neglects, or refuses to comply with any provisions of this chapter is guilty of a misdemeanor.

. Every person who willfully furnishes false information or who makes any false statement to establish a vital record or obtain a certification required by this chapter is guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%2027[2019 c 148 § 27]; ]

== 70.58A.900 - Applicability—2019 c 148. (Effective January 1, 2021.)
. This act applies to all causes of action commenced on or after January 1, 2021, regardless of when the cause of action arose.

. The requirements of this act apply to all records covered by this act that are held by the department or state registrar, regardless of the date the record was created or modified.

. In all other respects not specifically indicated in this section, this chapter applies prospectively.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%2028[2019 c 148 § 28]; ]

== 70.58A.901 - Effective date—2019 c 148.
Except for sections 3 and 43 of this act, this act takes effect January 1, 2021.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%2042[2019 c 148 § 42]; ]

== 70.58A.902 - Rule-making authority—2019 c 148.
The secretary and state board of health may adopt rules as authorized by this act to ensure that the sections in this act are implemented on their effective dates.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%2043[2019 c 148 § 43]; ]

