= 70.83C - Alcohol and drug use treatment associated with pregnancy—Fetal alcohol syndrome.
:toc:

== 70.83C.005 - Intent.
The legislature recognizes that the use of alcohol and other drugs during pregnancy can cause medical, psychological, and social problems for women and infants. The legislature further recognizes that communities are increasingly concerned about this problem and the associated costs to the mothers, infants, and society as a whole. The legislature recognizes that the department of health and other agencies are focusing on primary prevention activities to reduce the use of alcohol or drugs during pregnancy but few efforts have focused on secondary prevention efforts aimed at intervening in the lives of women already involved in the use of alcohol or other drugs during pregnancy. The legislature recognizes that the best way to prevent problems for chemically dependent pregnant women and their resulting children is to engage the women in alcohol or drug treatment. The legislature acknowledges that treatment professionals find pretreatment services to clients to be important in engaging women in alcohol or drug treatment. The legislature further recognizes that pretreatment services should be provided at locations where chemically dependent women are likely to be found, including public health clinics and domestic violence or homeless shelters. Therefore the legislature intends to prevent the detrimental effects of alcohol or other drug use to women and their resulting infants by promoting the establishment of local programs to help facilitate a woman's entry into alcohol or other drug treatment. These programs shall provide secondary prevention services and provision of opportunities for immediate treatment so that women who seek help are welcomed rather than ostracized.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2026-S.SL.pdf?cite=1993%20c%20422%20§%203[1993 c 422 § 3]; ]

== 70.83C.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Alcoholism" means a disease, characterized by a dependency on alcoholic beverages, loss of control over the amount and circumstances of alcohol use, symptoms of tolerance, physiological or psychological withdrawal, or both, if use is reduced or discontinued, and impairment of health or disruption of social or economic functioning.

. "Approved treatment program" means a discrete program of chemical dependency treatment provided by a treatment program certified by the department of social and health services as meeting standards adopted under this chapter.

. "Assessment" means an interview with an individual to determine if he or she is chemically dependent and in need of referral to an approved treatment program.

. "Chemically dependent individual" means someone suffering from alcoholism or drug addiction, or dependence on alcohol or one or more other psychoactive chemicals.

. "Department" means the department of social and health services.

. "Domestic violence" is a categorization of offenses, as defined in RCW 10.99.020.

. "Domestic violence program" means a shelter or other program which provides services to victims of domestic violence.

. "Drug addiction" means a disease characterized by a dependency on psychoactive chemicals, loss of control over the amount and circumstances of use, symptoms of tolerance, physiological or psychological withdrawal, or both, if use is reduced or discontinued, and impairment of health or disruptions of social or economic functioning.

. "Pretreatment" means the period of time prior to an individual's enrollment in alcohol or drug treatment.

. "Pretreatment services" means activities taking place prior to treatment that include identification of individuals using alcohol or drugs, education, assessment of their use, evaluation of need for treatment, referral to an approved treatment program, and advocacy on a client's behalf with social service agencies or others to ensure and coordinate a client's entry into treatment.

. "Primary prevention" means providing information about the effects of alcohol or drug use to individuals so they will avoid using these substances.

. "Secondary prevention" means identifying and obtaining an assessment on individuals using alcohol or other drugs for referral to treatment when indicated.

. "Secretary" means the secretary of the department of social and health services.

. "Treatment" means the broad range of emergency detoxification, residential, and outpatient services and care, including diagnostic evaluation, chemical dependency education and counseling, medical, psychiatric, psychological, and social service care, vocational rehabilitation, and career counseling, that may be extended to chemically dependent individuals and their families.

. "Treatment program" means an organization, institution, or corporation, public or private, engaged in the care, treatment, or rehabilitation of chemically dependent individuals.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2473-S.SL.pdf?cite=2020%20c%2029%20§%2016[2020 c 29 § 16]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2026-S.SL.pdf?cite=1993%20c%20422%20§%204[1993 c 422 § 4]; ]

== 70.83C.020 - Prevention strategies.
The secretary shall develop and promote statewide secondary prevention strategies designed to increase the use of alcohol and drug treatment services by women of childbearing age, before, during, and immediately after pregnancy. These efforts are conducted through the division of alcohol and substance abuse. The secretary shall:

. Promote development of three pilot demonstration projects in the state to be called pretreatment projects for women of childbearing age.

. Ensure that two of the projects are located in public health department clinics that provide maternity services and one is located with a domestic violence program.

. Hire three certified chemical dependency counselors to work as substance abuse educators in each of the three demonstration projects. The counselors may rotate between more than one clinic or domestic violence program. The chemical dependency counselor for the domestic violence program shall also be trained in domestic violence issues.

. Ensure that the duties and activities of the certified chemical dependency counselors include, at a minimum, the following:

.. Identifying substance-using pregnant women in the health clinics and domestic violence programs;

.. Educating the women and agency staff on the effects of alcohol or drugs on health, pregnancy, and unborn children;

.. Determining the extent of the women's substance use;

.. Evaluating the women's need for treatment;

.. Making referrals for chemical dependency treatment if indicated;

.. Facilitating the women's entry into treatment; and

.. Advocating on the client's behalf with other social service agencies or others to ensure and coordinate clients into treatment.

. Ensure that administrative costs of the department are limited to ten percent of the funds appropriated for the project.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2026-S.SL.pdf?cite=1993%20c%20422%20§%205[1993 c 422 § 5]; ]

