= 70.15 - Uniform emergency volunteer health practitioners act.
:toc:

== 70.15.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Department" means the department of health.

. "Disaster relief organization" means an entity that provides emergency or disaster relief services that include health or veterinary services provided by volunteer health practitioners and that:

.. Is designated or recognized as a provider of those services pursuant to a disaster response and recovery plan adopted by an agency of the federal government or the department; or

.. Regularly plans and conducts its activities in coordination with an agency of the federal government or the department.

. "Emergency" means an event or condition that is an emergency, disaster, or public health emergency under chapter 38.52 RCW.

. "Emergency declaration" means a proclamation of a state of emergency issued by the governor under RCW 43.06.010.

. "Emergency management assistance compact" means the interstate compact approved by congress by P.L. 104-321, 110 Stat. 3877, RCW 38.10.010.

. "Entity" means a person other than an individual.

. "Health facility" means an entity licensed under the laws of this or another state to provide health or veterinary services.

. "Health practitioner" means an individual licensed under the laws of this or another state to provide health or veterinary services.

. "Health services" means the provision of treatment, care, advice or guidance, or other services, or supplies, related to the health or death of individuals or human populations, to the extent necessary to respond to an emergency, including:

.. The following, concerning the physical or mental condition or functional status of an individual or affecting the structure or function of the body:

... Preventive, diagnostic, therapeutic, rehabilitative, maintenance, or palliative care; and

... Counseling, assessment, procedures, or other services;

.. Sale or dispensing of a drug, a device, equipment, or another item to an individual in accordance with a prescription; and

.. Funeral, cremation, alkaline hydrolysis, natural organic reduction as defined in RCW 68.04.310, cemetery, or other mortuary services.

. "Host entity" means an entity operating in this state which uses volunteer health practitioners to respond to an emergency.

. "License" means authorization by a state to engage in health or veterinary services that are unlawful without the authorization. The term includes authorization under the laws of this state to an individual to provide health or veterinary services based upon a national certification issued by a public or private entity.

. "Person" means an individual, corporation, business trust, trust, partnership, limited liability company, association, joint venture, public corporation, government or governmental subdivision, agency, or instrumentality, or any other legal or commercial entity.

. "Scope of practice" means the extent of the authorization to provide health or veterinary services granted to a health practitioner by a license issued to the practitioner in the state in which the principal part of the practitioner's services are rendered, including any conditions imposed by the licensing authority.

. "State" means a state of the United States, the District of Columbia, Puerto Rico, the United States Virgin Islands, or any territory or insular possession subject to the jurisdiction of the United States.

. "Veterinary services" means the provision of treatment, care, advice or guidance, or other services, or supplies, related to the health or death of an animal or to animal populations, to the extent necessary to respond to an emergency, including:

.. Diagnosis, treatment, or prevention of an animal disease, injury, or other physical or mental condition by the prescription, administration, or dispensing of vaccine, medicine, surgery, or therapy;

.. Use of a procedure for reproductive management; and

.. Monitoring and treatment of animal populations for diseases that have spread or demonstrate the potential to spread to humans.

. "Volunteer health practitioner" means a health practitioner who provides health or veterinary services, whether or not the practitioner receives compensation for those services. The term does not include a practitioner who receives compensation pursuant to a preexisting employment relationship with a host entity or affiliate which requires the practitioner to provide health services in this state, unless the practitioner is not a resident of this state and is employed by a disaster relief organization providing services in this state while an emergency declaration is in effect.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5001-S.SL.pdf?cite=2019%20c%20432%20§%2029[2019 c 432 § 29]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5990-S.SL.pdf?cite=2018%20c%20184%20§%202[2018 c 184 § 2]; ]

== 70.15.020 - Applicability to volunteer health practitioners.
This chapter applies to volunteer health practitioners registered with a registration system that complies with RCW 70.15.040 and who provide health or veterinary services in this state for a host entity while an emergency declaration is in effect.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5990-S.SL.pdf?cite=2018%20c%20184%20§%203[2018 c 184 § 3]; ]

== 70.15.030 - Regulation of services during emergency by department—Orders—Host entity duties.
. While an emergency declaration is in effect, the department may limit, restrict, or otherwise regulate:

.. The duration of practice by volunteer health practitioners;

.. The geographical areas in which volunteer health practitioners may practice;

.. The types of volunteer health practitioners who may practice; and

.. Any other matters necessary to coordinate effectively the provision of health or veterinary services during the emergency.

. An order issued pursuant to subsection (1) of this section may take effect immediately, without prior notice or comment, and is not a rule within the meaning of the administrative procedure act, chapter 34.05 RCW.

. A host entity that uses volunteer health practitioners to provide health or veterinary services in this state shall:

.. Consult and coordinate its activities with the department to the extent practicable to provide for the efficient and effective use of volunteer health practitioners; and

.. Comply with any laws other than this chapter relating to the management of emergency health or veterinary services.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5990-S.SL.pdf?cite=2018%20c%20184%20§%204[2018 c 184 § 4]; ]

== 70.15.040 - Volunteer health practitioner registration systems—Requirements.
. To qualify as a volunteer health practitioner registration system, a system must:

.. Accept applications for the registration of volunteer health practitioners before or during an emergency;

.. Include information about the licensure and good standing of health practitioners which is accessible by authorized persons;

.. Be capable of confirming the accuracy of information concerning whether a health practitioner is licensed and in good standing before health services or veterinary services are provided under this chapter; and

.. Meet one of the following conditions:

... Be an emergency system for advance registration of volunteer health care practitioners established by a state and funded through the United States department of health and human services under section 319I of the public health services act, 42 U.S.C. Sec. 247d-7b, as it existed on June 7, 2018, or such subsequent date as may be provided by the department by rule, consistent with the purposes of this section;

... Be a local unit consisting of trained and equipped emergency response, public health, and medical personnel formed pursuant to section 2801 of the public health services act, 42 U.S.C. Sec. 300hh, as it existed on June 7, 2018, or such subsequent date as may be provided by the department by rule, consistent with the purposes of this section;

... Be operated by a:

(A) Disaster relief organization;

(B) Licensing board;

(C) National or regional association of licensing boards or health practitioners;

(D) Health facility that provides comprehensive inpatient and outpatient health care services, including a tertiary care, teaching hospital, or acute care facility; or

(E) Governmental entity; or

... Be designated by the department as a registration system for purposes of this chapter.

. While an emergency declaration is in effect, the department, a person authorized to act on behalf of the department, or a host entity may confirm whether volunteer health practitioners utilized in this state are registered with a registration system that complies with subsection (1) of this section. Confirmation is limited to obtaining identities of the practitioners from the system and determining whether the system indicates that the practitioners are licensed and in good standing.

. Upon request of a person in this state authorized under subsection (2) of this section, or a similarly authorized person in another state, a registration system located in this state shall notify the person of the identities of volunteer health practitioners and whether the practitioners are licensed and in good standing.

. A host entity is not required to use the services of a volunteer health practitioner even if the practitioner is registered with a registration system that indicates that the practitioner is licensed and in good standing.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5990-S.SL.pdf?cite=2018%20c%20184%20§%205[2018 c 184 § 5]; ]

== 70.15.050 - Recognition of volunteer health practitioners licensed in other states.
. While an emergency declaration is in effect, a volunteer health practitioner, registered with a registration system that complies with RCW 70.15.040 and licensed and in good standing in the state upon which the practitioner's registration is based, may practice in this state to the extent authorized by this chapter as if the practitioner were licensed in this state.

. A volunteer health practitioner qualified under subsection (1) of this section is not entitled to the protections of this chapter if the practitioner is licensed in more than one state and any license of the practitioner is suspended, revoked, or subject to an agency order limiting or restricting practice privileges, or has been voluntarily terminated under threat of sanction.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5990-S.SL.pdf?cite=2018%20c%20184%20§%206[2018 c 184 § 6]; ]

== 70.15.060 - No effect on health facility credentialing and privileging standards.
. As used in this section:

.. "Credentialing" means obtaining, verifying, and assessing the qualifications of a health practitioner to provide treatment, care, or services in or for a health facility.

.. "Privileging" means the authorizing by an appropriate authority, such as a governing body, of a health practitioner to provide specific treatment, care, or services at a health facility subject to limits based on factors that include license, education, training, experience, competence, health status, and specialized skill.

. This chapter does not affect credentialing or privileging standards of a health facility and does not preclude a health facility from waiving or modifying those standards while an emergency declaration is in effect.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5990-S.SL.pdf?cite=2018%20c%20184%20§%207[2018 c 184 § 7]; ]

== 70.15.070 - Provision of volunteer health or veterinary services—Scope of practice—Modifications or restrictions—Unauthorized practice—Administrative sanctions.
. Subject to subsections (2) and (3) of this section, a volunteer health practitioner shall adhere to the scope of practice for a similarly licensed practitioner established by the licensing provisions, practice acts, or other laws of this state.

. Except as otherwise provided in subsection (3) of this section, this chapter does not authorize a volunteer health practitioner to provide services that are outside the practitioner's scope of practice, even if a similarly licensed practitioner in this state would be permitted to provide the services.

. The department may modify or restrict the health or veterinary services that volunteer health practitioners may provide pursuant to this chapter. An order under this subsection may take effect immediately, without prior notice or comment, and is not a rule within the meaning of the administrative procedure act, chapter 34.05 RCW.

. A host entity may restrict the health or veterinary services that a volunteer health practitioner may provide pursuant to this chapter.

. A volunteer health practitioner does not engage in unauthorized practice unless the practitioner has reason to know of any limitation, modification, or restriction under this section or that a similarly licensed practitioner in this state would not be permitted to provide the services. A volunteer health practitioner has reason to know of a limitation, modification, or restriction or that a similarly licensed practitioner in this state would not be permitted to provide a service if:

.. The practitioner knows the limitation, modification, or restriction exists or that a similarly licensed practitioner in this state would not be permitted to provide the service; or

.. From all the facts and circumstances known to the practitioner at the relevant time, a reasonable person would conclude that the limitation, modification, or restriction exists or that a similarly licensed practitioner in this state would not be permitted to provide the service.

. In addition to the authority granted by law of this state other than this chapter to regulate the conduct of health practitioners, a licensing board or other disciplinary authority in this state:

.. May impose administrative sanctions upon a health practitioner licensed in this state for conduct outside of this state in response to an out-of-state emergency;

.. May impose administrative sanctions upon a practitioner not licensed in this state for conduct in this state in response to an in-state emergency; and

.. Shall report any administrative sanctions imposed upon a practitioner licensed in another state to the appropriate licensing board or other disciplinary authority in any other state in which the practitioner is known to be licensed.

. In determining whether to impose administrative sanctions under subsection (6) of this section, a licensing board or other disciplinary authority shall consider the circumstances in which the conduct took place, including any exigent circumstances, and the practitioner's scope of practice, education, training, experience, and specialized skill.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5990-S.SL.pdf?cite=2018%20c%20184%20§%208[2018 c 184 § 8]; ]

== 70.15.080 - Relation to other laws—Emergency management assistance compact—Pacific Northwest emergency management arrangement.
. This chapter does not limit rights, privileges, or immunities provided to volunteer health practitioners by laws other than this chapter. Except as otherwise provided in subsection (2) of this section, this chapter does not affect requirements for the use of health practitioners pursuant to the emergency management assistance compact or the Pacific Northwest emergency management arrangement approved by congress by P.L. 105-381, 112 Stat. 3402.

. The department, pursuant to the emergency management assistance compact or the Pacific Northwest emergency management arrangement approved by congress by P.L. 105-381, 112 Stat. 3402, may incorporate into the emergency forces of this state volunteer health practitioners who are not officers or employees of this state, a political subdivision of this state, or a municipality or other local government within this state.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5990-S.SL.pdf?cite=2018%20c%20184%20§%209[2018 c 184 § 9]; ]

== 70.15.090 - Rules—Consultation with state military department and other agencies.
The department may promulgate rules to implement this chapter. In doing so, the department shall consult with and consider the recommendations of the state military department as the agency established to carry out the state's program for emergency management, and coordinate the implementation of the emergency management assistance compact with the state military department to ensure conformity with the state's program for emergency management and the coordination of all response activities through the state's emergency operations center during a state of emergency. The department shall also consult with and consider rules promulgated by similarly empowered agencies in other states to promote uniformity of application of this chapter and make the emergency response systems in the various states reasonably compatible.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5990-S.SL.pdf?cite=2018%20c%20184%20§%2010[2018 c 184 § 10]; ]

== 70.15.100 - Volunteer health practitioners—Workers' compensation coverage—Rules.
. A volunteer health practitioner who dies or is injured as the result of providing health or veterinary services pursuant to this chapter is deemed to be an employee of this state for the purpose of receiving benefits for the death or injury under the workers' compensation law of this state, Title 51 RCW, if:

.. The practitioner is not otherwise eligible for such benefits for the injury or death under the law of this or another state; and

.. The practitioner, or in the case of death the practitioner's personal representative, elects coverage under the workers' compensation law of this state, Title 51 RCW, by making a claim under that law.

. The department in consultation with the department of labor and industries shall adopt rules, enter into agreements with other states, or take other measures to facilitate the receipt of benefits for injury or death under the workers' compensation law of this state, Title 51 RCW, by volunteer health practitioners who reside in other states, and may waive or modify requirements for filing, processing, and paying claims that unreasonably burden the practitioners. To promote uniformity of application of this chapter with other states that enact similar legislation, the department shall consult with and consider the practices for filing, processing, and paying claims by agencies with similar authority in other states.

. For the purposes of this section, "injury" means a physical or mental injury or disease for which an employee of this state who is injured or contracts the disease in the course of the employee's employment would be entitled to benefits under the workers' compensation law of this state, Title 51 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5990-S.SL.pdf?cite=2018%20c%20184%20§%2011[2018 c 184 § 11]; ]

== 70.15.110 - Liability—Volunteer health practitioners—Operation, use, reliance upon volunteer health practitioner registration system.
. No act or omission, except those acts or omissions constituting gross negligence or willful or wanton misconduct, by a volunteer health practitioner registered and providing services within the provisions of this chapter shall impose any liability for civil damages resulting from such an act or omission upon:

.. The volunteer health practitioner;

.. The supervisor or supervisors of the volunteer health practitioner;

.. Any facility or their officers or employees;

.. The employer of the volunteer health practitioner;

.. The owner of the property or vehicle where the act or omission may have occurred;

.. Any organization that registered the volunteer health practitioner under the provisions of this chapter;

.. The state or any state or local governmental entity; or

.. Any professional or trade association of the volunteer health practitioner.

. A person that, pursuant to this chapter, operates, uses, or relies upon information provided by a volunteer health practitioner registration system is not liable for damages for an act or omission relating to that operation, use, or reliance unless the act or omission constitutes gross negligence, an intentional tort, or willful or wanton misconduct.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1091-S.SL.pdf?cite=2019%20c%2064%20§%2023[2019 c 64 § 23]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5990-S.SL.pdf?cite=2018%20c%20184%20§%2012[2018 c 184 § 12]; ]

== 70.15.900 - Short title.
This chapter may be known and cited as the uniform emergency volunteer health practitioners act.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5990-S.SL.pdf?cite=2018%20c%20184%20§%201[2018 c 184 § 1]; ]

== 70.15.901 - Uniformity of application and construction.
In applying and construing this uniform act, consideration must be given to the need to promote uniformity of the law with respect to its subject matter among states that enact it.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5990-S.SL.pdf?cite=2018%20c%20184%20§%2013[2018 c 184 § 13]; ]

