= 70.40 - Hospital and medical facilities survey and construction act.
:toc:

== 70.40.005 - Transfer of duties to the department of health.
The powers and duties of the department of social and health services and the secretary of social and health services under this chapter shall be performed by the department of health and the secretary of health.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20248[1989 1st ex.s. c 9 § 248]; ]

== 70.40.010 - Short title.
This chapter may be cited as the "Washington Hospital and Medical Facilities Survey and Construction Act."

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c252.pdf?cite=1959%20c%20252%20§%201[1959 c 252 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c197.pdf?cite=1949%20c%20197%20§%201[1949 c 197 § 1]; Rem. Supp. 1949 § 6090-60; ]

== 70.40.020 - Definitions.
As used in this chapter:

. "Secretary" means the secretary of the state department of health;

. "The federal act" means Title VI of the public health service act, as amended, or as hereafter amended by congress;

. "The surgeon general" means the surgeon general of the public health service of the United States;

. "Hospital" includes public health centers and general, tuberculosis, mental, chronic disease, and other types of hospitals, and related facilities, such as laboratories, outpatient departments, nurses' home and training facilities, and central service facilities operated in connection with hospitals;

. "Public health center" means a publicly owned facility for the provision of public health services, including related facilities such as laboratories, clinics, and administrative offices operated in connection with public health centers;

. "Nonprofit hospital" and "nonprofit medical facility" means any hospital or medical facility owned and operated by a corporation or association, no part of the net earnings of which inures, or may lawfully inure, to the benefit of any private shareholder or individual;

. "Medical facilities" means diagnostic or diagnostic and treatment centers, rehabilitation facilities and nursing homes as those terms are defined in the federal act.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20331[1991 c 3 § 331]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%2096[1979 c 141 § 96]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c252.pdf?cite=1959%20c%20252%20§%202[1959 c 252 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c197.pdf?cite=1949%20c%20197%20§%202[1949 c 197 § 2]; Rem. Supp. 1949 § 6090-61; ]

== 70.40.030 - Section of hospital and medical facility survey and construction established—Duties.
There is hereby established in the state department of health a "section of hospital and medical facility survey and construction" which shall be administered by a full time salaried head under the supervision and direction of the secretary. The state department of health, through such section, shall constitute the sole agency of the state for the purpose of:

. Making an inventory of existing hospitals and medical facilities, surveying the need for construction of hospitals and medical facilities, and developing a program of hospital and medical facility construction; and

. Developing and administering a state plan for the construction of public and other nonprofit hospitals and medical facilities as provided in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20332[1991 c 3 § 332]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%2097[1979 c 141 § 97]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c252.pdf?cite=1959%20c%20252%20§%203[1959 c 252 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c197.pdf?cite=1949%20c%20197%20§%203[1949 c 197 § 3]; Rem. Supp. 1949 § 6090-62; ]

== 70.40.040 - General duties of the secretary.
In carrying out the purposes of the chapter the secretary is authorized and directed:

. To require such reports, make such inspections and investigations, and prescribe such regulations as he or she deems necessary;

. To provide such methods of administration, appoint a head and other personnel of the section, and take such other action as may be necessary to comply with the requirements of the federal act and the regulations thereunder;

. To procure in his or her discretion the temporary or intermittent services of experts or consultants or organizations thereof, by contract, when such services are to be performed on a part time or fee-for-service basis and do not involve the performance of administrative duties;

. To the extent that he or she considers desirable to effectuate the purposes of this chapter, to enter into agreements for the utilization of the facilities and services of other departments, agencies, and institutions public or private;

. To accept on behalf of the state and to deposit with the state treasurer, any grant, gift, or contribution made to assist in meeting the cost of carrying out the purposes of this chapter, and to expend the same for such purpose; and

. To make an annual report to the governor on activities pursuant to this chapter, including recommendations for such additional legislation as the secretary considers appropriate to furnish adequate hospital and medical facilities to the people of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20375[2012 c 117 § 375]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%2098[1979 c 141 § 98]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977c75.pdf?cite=1977%20c%2075%20§%2083[1977 c 75 § 83]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c252.pdf?cite=1959%20c%20252%20§%204[1959 c 252 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c197.pdf?cite=1949%20c%20197%20§%204[1949 c 197 § 4]; Rem. Supp. 1949 § 6090-63; ]

== 70.40.060 - Development of program for construction of facilities needed.
The secretary is authorized and directed to make an inventory of existing hospitals and medical facilities, including public nonprofit and proprietary hospitals and medical facilities, to survey the need for construction of hospitals and medical facilities, and, on the basis of such inventory and survey, to develop a program for the construction of such public and other nonprofit hospitals and medical facilities as will, in conjunction with existing facilities, afford the necessary physical facilities for furnishing adequate hospital and medical facility services to all the people of the state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%2099[1979 c 141 § 99]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c252.pdf?cite=1959%20c%20252%20§%206[1959 c 252 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c197.pdf?cite=1949%20c%20197%20§%206[1949 c 197 § 6]; Rem. Supp. 1949 § 6090-65; ]

== 70.40.070 - Distribution of facilities.
The construction program shall provide, in accordance with regulations prescribed under the federal act, for adequate hospital and medical facilities for the people residing in this state and insofar as possible shall provide for their distribution throughout the state in such manner as to make all types of hospital and medical facility service reasonably accessible to all persons in the state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c252.pdf?cite=1959%20c%20252%20§%207[1959 c 252 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c197.pdf?cite=1949%20c%20197%20§%207[1949 c 197 § 7]; Rem. Supp. 1949 § 6090-66; ]

== 70.40.080 - Federal funds—Application for—Deposit, use.
The secretary is authorized to make application to the surgeon general for federal funds to assist in carrying out the survey and planning activities herein provided. Such funds shall be deposited with the state treasurer and shall be available to the secretary for expenditure in carrying out the purposes of this part. Any such funds received and not expended for such purposes shall be repaid to the treasurer of the United States.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20100[1979 c 141 § 100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c197.pdf?cite=1949%20c%20197%20§%208[1949 c 197 § 8]; Rem. Supp. 1949 § 6090-67; ]

== 70.40.090 - State plan—Publication—Hearing—Approval by surgeon general—Modifications.
The secretary shall prepare and submit to the surgeon general a state plan which shall include the hospital and medical facility construction program developed under this chapter and which shall provide for the establishment, administration, and operation of hospital and medical facility construction activities in accordance with the requirements of the federal act and the regulations thereunder. The secretary shall, prior to the submission of such plan to the surgeon general, give adequate publicity to a general description of all the provisions proposed to be included therein, and hold a public hearing at which all persons or organizations with a legitimate interest in such plan may be given an opportunity to express their views. After approval of the plan by the surgeon general, the secretary shall publish a general description of the provisions thereof in at least one newspaper having general circulation in the state, and shall make the plan, or a copy thereof, available upon request to all interested persons or organizations. The secretary shall from time to time review the hospital and medical facility construction program and submit to the surgeon general any modifications thereof which he or she may find necessary and may submit to the surgeon general such modifications of the state plan, not inconsistent with the requirements of the federal act, as he or she may deem advisable.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20376[2012 c 117 § 376]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20101[1979 c 141 § 101]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c252.pdf?cite=1959%20c%20252%20§%208[1959 c 252 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c197.pdf?cite=1949%20c%20197%20§%209[1949 c 197 § 9]; Rem. Supp. 1949 § 6090-68; ]

== 70.40.100 - Plan shall provide for construction in order of relative needs.
The state plan shall set forth the relative need for the several projects included in the construction program determined in accordance with regulations prescribed pursuant to the federal act, and provide for the construction, insofar as financial resources available therefor and for maintenance and operations make possible, in the order of such relative need.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c197.pdf?cite=1949%20c%20197%20§%2011[1949 c 197 § 11]; Rem. Supp. 1949 § 6090-70; ]

== 70.40.110 - Minimum standards for maintenance and operation.
The secretary shall by regulation prescribe minimum standards for the maintenance and operation of hospitals and medical facilities which receive federal aid for construction under the state plan.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20102[1979 c 141 § 102]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c252.pdf?cite=1959%20c%20252%20§%209[1959 c 252 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c197.pdf?cite=1949%20c%20197%20§%2010[1949 c 197 § 10]; Rem. Supp. 1949 § 6090-69; ]

== 70.40.120 - Applications for construction projects—Diagnostic, treatment centers.
Applications for hospital and medical facility construction projects for which federal funds are requested shall be submitted to the secretary and may be submitted by the state or any political subdivision thereof or by any public or nonprofit agency authorized to construct and operate a hospital or medical facility: PROVIDED, That except as may be permitted by federal law no application for a diagnostic or treatment center shall be approved unless the applicant is (1) a state, political subdivision, or public agency, or (2) a corporation or association which owns and operates a nonprofit hospital. Each application for a construction project shall conform to federal and state requirements.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20103[1979 c 141 § 103]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c252.pdf?cite=1959%20c%20252%20§%2010[1959 c 252 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c197.pdf?cite=1949%20c%20197%20§%2012[1949 c 197 § 12]; Rem. Supp. 1949 § 6090-71; ]

== 70.40.130 - Hearing—Approval.
The secretary shall afford to every applicant for a construction project an opportunity for a fair hearing. If the secretary, after affording reasonable opportunity for development and presentation of applications in the order of relative need, finds that a project application complies with the requirements of RCW 70.40.120 and is otherwise in conformity with the state plan, he or she shall approve such application and shall recommend and forward it to the surgeon general.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20377[2012 c 117 § 377]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20104[1979 c 141 § 104]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c197.pdf?cite=1949%20c%20197%20§%2013[1949 c 197 § 13]; Rem. Supp. 1949 § 6090-72; ]

== 70.40.140 - Inspection of project under construction—Certification as to federal funds due.
From time to time the secretary shall inspect each construction project approved by the surgeon general, and, if the inspection so warrants, the secretary shall certify to the surgeon general that work has been performed upon the project, or purchases have been made, in accordance with the approved plans and specifications, and that payment of an installment of federal funds is due to the applicant.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20105[1979 c 141 § 105]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c197.pdf?cite=1949%20c%20197%20§%2014[1949 c 197 § 14]; Rem. Supp. 1949 § 6090-73; ]

== 70.40.150 - Hospital and medical facility construction fund—Deposits, use.
The secretary is hereby authorized to receive federal funds in behalf of, and transmit them to, such applicants or to approve applicants for federal funds and authorize the payment of such funds directly to such applicants as may be allowed by federal law. To achieve that end there is hereby established, separate and apart from all public moneys and funds of this state, a trust fund to be known as the "hospital and medical facility construction fund", of which the state treasurer shall ex officio be custodian. Moneys received from the federal government for construction projects approved by the surgeon general shall be deposited to the credit of this fund, shall be used solely for payments due applicants for work performed, or purchases made, in carrying out approved projects. Vouchers covering all payments from the hospital and medical facility construction fund shall be prepared by the department of health and shall bear the signature of the secretary or his or her duly authorized agent for such purpose, and warrants therefor shall be signed by the state treasurer.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20333[1991 c 3 § 333]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c106.pdf?cite=1973%20c%20106%20§%2031[1973 c 106 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c252.pdf?cite=1959%20c%20252%20§%2011[1959 c 252 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c197.pdf?cite=1949%20c%20197%20§%2015[1949 c 197 § 15]; Rem. Supp. 1949 § 6090-74; ]

