= 70.22 - Mosquito control.
:toc:

== 70.22.010 - Declaration of purpose.
The purpose of this chapter is to establish a statewide program for the control or elimination of mosquitoes as a health hazard.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c283.pdf?cite=1961%20c%20283%20§%201[1961 c 283 § 1]; ]

== 70.22.020 - Secretary may make inspections, investigations, and determinations and provide for control.
The secretary of health is hereby authorized and empowered to make or cause to be made such inspections, investigations, studies and determinations as he or she may from time to time deem advisable in order to ascertain the effect of mosquitoes as a health hazard, and, to the extent to which funds are available, to provide for the control or elimination thereof in any or all parts of the state.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20317[1991 c 3 § 317]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%2088[1979 c 141 § 88]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c283.pdf?cite=1961%20c%20283%20§%202[1961 c 283 § 2]; ]

== 70.22.030 - Secretary to coordinate plans.
The secretary of health shall coordinate plans for mosquito control work which may be projected by any county, city or town, municipal corporation, taxing district, state department or agency, federal government agency, or any person, group or organization, and arrange for cooperation between any such districts, departments, agencies, persons, groups or organizations.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20318[1991 c 3 § 318]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%2089[1979 c 141 § 89]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c283.pdf?cite=1961%20c%20283%20§%203[1961 c 283 § 3]; ]

== 70.22.040 - Secretary may contract with, receive funds from entities and individuals—Authorization for governmental entities to contract, grant funds, levy taxes.
The secretary of health is authorized and empowered to receive funds from any county, city or town, municipal corporation, taxing district, the federal government, or any person, group or organization to carry out the purpose of this chapter. In connection therewith the secretary is authorized and empowered to contract with any such county, city, or town, municipal corporation, taxing district, the federal government, person, group or organization with respect to the construction and maintenance of facilities and other work for the purpose of effecting mosquito control or elimination, and any such county, city or town, municipal corporation, or taxing district obligated to carry out the provisions of any such contract entered into with the secretary is authorized, empowered and directed to appropriate, and if necessary, to levy taxes for and pay over such funds as its contract with the secretary may from time to time require.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20319[1991 c 3 § 319]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%2090[1979 c 141 § 90]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c283.pdf?cite=1961%20c%20283%20§%204[1961 c 283 § 4]; ]

== 70.22.050 - Powers and duties of secretary.
To carry out the purpose of this chapter, the secretary of health may:

. Abate as nuisances breeding places for mosquitoes as defined in RCW 17.28.170;

. Acquire by gift, devise, bequest, lease, or purchase, real and personal property necessary or convenient for carrying out the purpose of this chapter;

. Make contracts, employ engineers, health officers, sanitarians, physicians, laboratory personnel, attorneys, and other technical or professional assistants;

. Publish information or literature; and

. Do any and all other things necessary to carry out the purpose of this chapter: PROVIDED, That no program shall be permitted nor any action taken in pursuance thereof which may be injurious to the life or health of game or fish.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20320[1991 c 3 § 320]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c11.pdf?cite=1989%20c%2011%20§%2025[1989 c 11 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%2091[1979 c 141 § 91]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c283.pdf?cite=1961%20c%20283%20§%205[1961 c 283 § 5]; ]

== 70.22.060 - Governmental entities to cooperate with secretary.
Each state department, agency, and political subdivision shall cooperate with the secretary of health in carrying out the purposes of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20321[1991 c 3 § 321]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%2092[1979 c 141 § 92]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c283.pdf?cite=1961%20c%20283%20§%206[1961 c 283 § 6]; ]

