= 70.41 - Hospital licensing and regulation.
:toc:

== 70.41.005 - Transfer of duties to the department of health.
The powers and duties of the department of social and health services under this chapter shall be performed by the department of health.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20249[1989 1st ex.s. c 9 § 249]; ]

== 70.41.010 - Declaration of purpose.
The primary purpose of this chapter is to promote safe and adequate care of individuals in hospitals through the development, establishment and enforcement of minimum hospital standards for maintenance and operation. To accomplish these purposes, this chapter provides for:

. The licensing and inspection of hospitals;

. The establishment of a Washington state hospital advisory council;

. The establishment by the department of standards, rules and regulations for the construction, maintenance and operation of hospitals;

. The enforcement by the department of the standards, rules, and regulations established under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c213.pdf?cite=1985%20c%20213%20§%2015[1985 c 213 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20106[1979 c 141 § 106]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c267.pdf?cite=1955%20c%20267%20§%201[1955 c 267 § 1]; ]

== 70.41.020 - Definitions.
Unless the context clearly indicates otherwise, the following terms, whenever used in this chapter, shall be deemed to have the following meanings:

. "Aftercare" means the assistance provided by a lay caregiver to a patient under this chapter after the patient's discharge from a hospital. The assistance may include, but is not limited to, assistance with activities of daily living, wound care, medication assistance, and the operation of medical equipment. "Aftercare" includes assistance only for conditions that were present at the time of the patient's discharge from the hospital. "Aftercare" does not include:

.. Assistance related to conditions for which the patient did not receive medical care, treatment, or observation in the hospital; or

.. Tasks the performance of which requires licensure as a health care provider.

. "Department" means the Washington state department of health.

. "Discharge" means a patient's release from a hospital following the patient's admission to the hospital.

. "Distant site" means the site at which a physician or other licensed provider, delivering a professional service, is physically located at the time the service is provided through telemedicine.

. "Emergency care to victims of sexual assault" means medical examinations, procedures, and services provided by a hospital emergency room to a victim of sexual assault following an alleged sexual assault.

. "Emergency contraception" means any health care treatment approved by the food and drug administration that prevents pregnancy, including but not limited to administering two increased doses of certain oral contraceptive pills within seventy-two hours of sexual contact.

. "Hospital" means any institution, place, building, or agency which provides accommodations, facilities and services over a continuous period of twenty-four hours or more, for observation, diagnosis, or care, of two or more individuals not related to the operator who are suffering from illness, injury, deformity, or abnormality, or from any other condition for which obstetrical, medical, or surgical services would be appropriate for care or diagnosis. "Hospital" as used in this chapter does not include hotels, or similar places furnishing only food and lodging, or simply domiciliary care; nor does it include clinics, or physician's offices where patients are not regularly kept as bed patients for twenty-four hours or more; nor does it include nursing homes, as defined and which come within the scope of chapter 18.51 RCW; nor does it include birthing centers, which come within the scope of chapter 18.46 RCW; nor does it include psychiatric hospitals, which come within the scope of chapter 71.12 RCW; nor any other hospital, or institution specifically intended for use in the diagnosis and care of those suffering from mental illness, intellectual disability, convulsive disorders, or other abnormal mental condition. Furthermore, nothing in this chapter or the rules adopted pursuant thereto shall be construed as authorizing the supervision, regulation, or control of the remedial care or treatment of residents or patients in any hospital conducted for those who rely primarily upon treatment by prayer or spiritual means in accordance with the creed or tenets of any well recognized church or religious denominations.

. "Lay caregiver" means any individual designated as such by a patient under this chapter who provides aftercare assistance to a patient in the patient's residence. "Lay caregiver" does not include a long-term care worker as defined in RCW 74.39A.009.

. "Originating site" means the physical location of a patient receiving health care services through telemedicine.

. "Person" means any individual, firm, partnership, corporation, company, association, or joint stock association, and the legal successor thereof.

. "Secretary" means the secretary of health.

. "Sexual assault" has the same meaning as in RCW 70.125.030.

. "Telemedicine" means the delivery of health care services through the use of interactive audio and video technology, permitting real-time communication between the patient at the originating site and the provider, for the purpose of diagnosis, consultation, or treatment. "Telemedicine" does not include the use of audio-only telephone, facsimile, or email.

. "Victim of sexual assault" means a person who alleges or is alleged to have been sexually assaulted and who presents as a patient.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6327-S.SL.pdf?cite=2016%20c%20226%20§%201[2016 c 226 § 1]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5175-S.SL.pdf?cite=2015%20c%2023%20§%205[2015 c 23 § 5]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2490.SL.pdf?cite=2010%20c%2094%20§%2017[2010 c 94 § 17]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6537-S.SL.pdf?cite=2002%20c%20116%20§%202[2002 c 116 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20334[1991 c 3 § 334]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c213.pdf?cite=1985%20c%20213%20§%2016[1985 c 213 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c189.pdf?cite=1971%20ex.s.%20c%20189%20§%208[1971 ex.s. c 189 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c267.pdf?cite=1955%20c%20267%20§%202[1955 c 267 § 2]; ]

== 70.41.030 - Standards and rules.
The department shall establish and adopt such minimum standards and rules pertaining to the construction, maintenance, and operation of hospitals, and rescind, amend, or modify such rules from time to time, as are necessary in the public interest, and particularly for the establishment and maintenance of standards of hospitalization required for the safe and adequate care and treatment of patients. To the extent possible, the department shall endeavor to make such minimum standards and rules consistent in format and general content with the applicable hospital survey standards of the joint commission on the accreditation of health care organizations. The department shall adopt standards that are at least equal to recognized applicable national standards pertaining to medical gas piping systems.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1445.SL.pdf?cite=1995%20c%20282%20§%201[1995 c 282 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%20127[1989 c 175 § 127]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c213.pdf?cite=1985%20c%20213%20§%2017[1985 c 213 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c189.pdf?cite=1971%20ex.s.%20c%20189%20§%209[1971 ex.s. c 189 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c267.pdf?cite=1955%20c%20267%20§%203[1955 c 267 § 3]; ]

== 70.41.040 - Enforcement of chapter—Personnel—Merit system.
The enforcement of the provisions of this chapter and the standards, rules and regulations established under this chapter, shall be the responsibility of the department which shall cooperate with the joint commission on the accreditation of health care organizations. The department shall advise on the employment of personnel and the personnel shall be under the merit system or its successor.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1445.SL.pdf?cite=1995%20c%20282%20§%203[1995 c 282 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c213.pdf?cite=1985%20c%20213%20§%2018[1985 c 213 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c267.pdf?cite=1955%20c%20267%20§%204[1955 c 267 § 4]; ]

== 70.41.045 - Hospital surveys or audits—Frequent problems to be posted on agency web sites—Hospital evaluation of survey or audit, form—Notice.
. Unless the context clearly requires otherwise, the definitions in this subsection apply throughout this section.

.. "Agency" means a department of state government created under RCW 43.17.010 and the office of the state auditor.

.. "Audit" means an examination of records or financial accounts to evaluate accuracy and monitor compliance with statutory or regulatory requirements.

.. "Hospital" means a hospital licensed under chapter 70.41 RCW.

.. "Survey" means an inspection, examination, or site visit conducted by an agency to evaluate and monitor the compliance of a hospital or hospital services or facilities with statutory or regulatory requirements.

. By July 1, 2004, each state agency which conducts hospital surveys or audits shall post to its agency web site a list of the most frequent problems identified in its hospital surveys or audits along with information on how to avoid or address the identified problems, and a person within the agency that a hospital may contact with questions or for further assistance.

. By July 1, 2004, the department of health, in cooperation with other state agencies which conduct hospital surveys or audits, shall develop an instrument, to be provided to every hospital upon completion of a state survey or audit, which allows the hospital to anonymously evaluate the survey or audit process in terms of quality, efficacy, and the extent to which it supported improved patient care and compliance with state law without placing an unnecessary administrative burden on the hospital. The evaluation may be returned to the department of health for distribution to the appropriate agency.

. Except when responding to complaints or immediate public health and safety concerns or when such prior notice would conflict with other state or federal law, any state agency that provides notice of a hospital survey or audit must provide such notice to the hospital no less than four weeks prior to the date of the survey or audit.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2883.SL.pdf?cite=2016%20c%20197%20§%207[2016 c 197 § 7]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6485.SL.pdf?cite=2004%20c%20261%20§%202[2004 c 261 § 2]; ]

== 70.41.080 - Fire protection.
Standards for fire protection and the enforcement thereof, with respect to all hospitals to be licensed hereunder shall be the responsibility of the chief of the Washington state patrol, through the director of fire protection, who shall adopt, after approval by the department, the recognized standards applicable to hospitals for the protection of life against the cause and spread of fire and fire hazards adopted by the federal centers for medicare and medicaid services for hospitals that care for medicare or medicaid beneficiaries. The standards used for an inspection of an existing hospital, or existing portion thereof, shall be standards for existing buildings and not standards for new construction. The department upon receipt of an application for a license, shall submit to the director of fire protection in writing, a request for an inspection, giving the applicant's name and the location of the premises to be licensed. Upon receipt of such a request, the chief of the Washington state patrol, through the director of fire protection, or his or her deputy, shall make an inspection of the hospital to be licensed during the department's inspection. If it is found that the premises do not comply with the required safety standards and fire regulations as adopted pursuant to this chapter, the director of fire protection, or his or her deputy, shall promptly make a written report to the department listing the corrective actions required. The department shall incorporate the written report into the department's final inspection report. The applicant or licensee shall submit corrections to comply with the fire protection standards along with any other licensing inspection corrections to the department. The department shall submit the section of the statement of corrections from the applicant or licensee regarding fire protection standards to the director of fire protection. If extensive and serious corrections are required, the director of fire protection, or his or her deputy, may reinspect the premises. The director of fire protection, or his or her deputy, shall utilize the scope and severity matrix developed by the centers for medicare and medicaid services when determining what corrections will require a reinspection. Whenever the hospital to be licensed meets with the approval of the chief of the Washington state patrol, through the director of fire protection, he or she shall submit to the department, in a timely manner so the license will not be delayed, a written report approving the hospital with respect to fire protection, and such report is required before a full license can be issued. The chief of the Washington state patrol, through the director of fire protection, shall make or cause to be made inspections of such hospitals on average at least once every eighteen months. Inspections conducted by the joint commission on hospitals accredited by it shall be deemed equivalent to an inspection by the chief of the Washington state patrol, through the director of fire protection, for purposes of meeting the requirements for the inspections specified in this section.

The director of fire protection shall designate one lead deputy state fire marshal on a regional basis to provide consistency with each of the department's survey teams for the purpose of conducting the fire protection inspection during the department's licensing inspection. The director of fire protection shall ensure deputy state fire marshals are provided orientation with the department on the unique environment of hospitals before they conduct fire protection inspections in hospitals. The orientation shall include, but not be limited to: Clinical environment of hospitals; operating room environment; fire protection practices in hospitals; full participation in a complete licensing inspection of at least one urban hospital; and full participation in a complete licensing inspection of at least one rural hospital.

In cities which have in force a comprehensive building code, the provisions of which are determined by the chief of the Washington state patrol, through the director of fire protection, to be equal to the minimum standards of the code for hospitals adopted by the chief of the Washington state patrol, through the director of fire protection, the chief of the fire department, provided the latter is a paid chief of a paid fire department, shall make the inspection with the chief of the Washington state patrol, through the director of fire protection, or his or her deputy and they shall jointly approve the premises before a full license can be issued.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6710-S.SL.pdf?cite=2008%20c%20155%20§%201[2008 c 155 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6485.SL.pdf?cite=2004%20c%20261%20§%203[2004 c 261 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2040[1995 c 369 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2094[1986 c 266 § 94]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c213.pdf?cite=1985%20c%20213%20§%2019[1985 c 213 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c267.pdf?cite=1955%20c%20267%20§%208[1955 c 267 § 8]; ]

== 70.41.090 - Hospital license required—Certificate of need required—Participation in Washington rural health access preservation pilot.
. No person or governmental unit of the state of Washington, acting separately or jointly with any other person or governmental unit, shall establish, maintain, or conduct a hospital in this state, or use the word "hospital" to describe or identify an institution, without a license under this chapter: PROVIDED, That the provisions of this section shall not apply to state mental institutions and psychiatric hospitals which come within the scope of chapter 71.12 RCW.

. After June 30, 1989, no hospital shall initiate a tertiary health service as defined in RCW 70.38.025(14) unless it has received a certificate of need as provided in RCW 70.38.105 and 70.38.115.

. A rural health care facility licensed under RCW 70.175.100 formerly licensed as a hospital under this chapter may, within three years of the effective date of the rural health care facility license, apply to the department for a hospital license and not be required to meet certificate of need requirements under chapter 70.38 RCW as a new health care facility and not be required to meet new construction requirements as a new hospital under this chapter. These exceptions are subject to the following: The facility at the time of initial conversion was considered by the department to be in compliance with the hospital licensing rules and the condition of the physical plant and equipment is equal to or exceeds the level of compliance that existed at the time of conversion to a rural health care facility. The department shall inspect and determine compliance with the hospital rules prior to reissuing a hospital license.

. A rural hospital, as defined by the department, reducing the number of licensed beds to become a rural primary care hospital under the provisions of Part A Title XVIII of the Social Security Act Section 1820, 42 U.S.C., 1395c et seq. may, within three years of the reduction of licensed beds, increase the number of beds licensed under this chapter to no more than the previously licensed number of beds without being subject to the provisions of chapter 70.38 RCW and without being required to meet new construction requirements under this chapter. These exceptions are subject to the following: The facility at the time of the reduction in licensed beds was considered by the department to be in compliance with the hospital licensing rules and the condition of the physical plant and equipment is equal to or exceeds the level of compliance that existed at the time of the reduction in licensed beds. The department may inspect and determine compliance with the hospital rules prior to increasing the hospital license.

. If a rural hospital is determined to no longer meet critical access hospital status for state law purposes as a result of participation in the Washington rural health access preservation pilot identified by the state office of rural health, the rural hospital may renew its license by applying to the department for a hospital license and the previously licensed number of beds without being subject to the provisions of chapter 70.38 RCW and without being required to meet new construction review requirements under this chapter. These exceptions are subject to the following: The hospital, at the time it began participation in the pilot, was considered by the department to be in compliance with the hospital licensing rules, and the condition of the physical plant and equipment is equal to or exceeds the level of compliance that existed at the time of the reduction in licensed beds. The department may inspect and determine compliance with the hospital licensing rules. If all or part of a formerly licensed rural hospital is sold, purchased, or leased during the period the rural hospital does not meet critical access hospital status as a result of participation in the Washington rural health access preservation pilot and the new owner or lessor applies to renew the rural hospital's license, then the sale, purchase, or lease of part or all of the rural hospital is subject to the provisions of chapter 70.38 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2450-S.SL.pdf?cite=2016%20sp.s.%20c%2031%20§%203[2016 sp.s. c 31 § 3]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6076-S.SL.pdf?cite=1992%20c%2027%20§%203[1992 c 27 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20611[1989 1st ex.s. c 9 § 611]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c267.pdf?cite=1955%20c%20267%20§%209[1955 c 267 § 9]; ]

== 70.41.100 - Applications for licenses and renewals—Fees.
An application for license shall be made to the department upon forms provided by it and shall contain such information as the department reasonably requires which may include affirmative evidence of ability to comply with the standards, rules, and regulations as are lawfully prescribed hereunder. An application for renewal of license shall be made to the department upon forms provided by it and submitted thirty days prior to the date of expiration of the license. Each application for a license or renewal thereof by a hospital as defined by this chapter shall be accompanied by a fee as established by the department under RCW 43.20B.110.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c75.pdf?cite=1987%20c%2075%20§%208[1987 c 75 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c201.pdf?cite=1982%20c%20201%20§%209[1982 c 201 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c267.pdf?cite=1955%20c%20267%20§%2010[1955 c 267 § 10]; ]

== 70.41.110 - Licenses, provisional licenses—Issuance, duration, assignment, posting.
Upon receipt of an application for license and the license fee, the department shall issue a license or a provisional license if the applicant and the hospital facilities meet the requirements of this chapter and the standards, rules and regulations established by the department. All licenses issued under the provisions of this chapter shall expire on a date to be set by the department: PROVIDED, That no license issued pursuant to this chapter shall exceed thirty-six months in duration. Each license shall be issued only for the premises and persons named in the application, and no license shall be transferable or assignable except with the written approval of the department. Licenses shall be posted in a conspicuous place on the licensed premises.

If there be a failure to comply with the provisions of this chapter or the standards, rules and regulations promulgated pursuant thereto, the department may in its discretion issue to an applicant for a license, or for the renewal of a license, a provisional license which will permit the operation of the hospital for a period to be determined by the department.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c213.pdf?cite=1985%20c%20213%20§%2020[1985 c 213 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c201.pdf?cite=1982%20c%20201%20§%2012[1982 c 201 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c247.pdf?cite=1971%20ex.s.%20c%20247%20§%203[1971 ex.s. c 247 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c267.pdf?cite=1955%20c%20267%20§%2011[1955 c 267 § 11]; ]

== 70.41.115 - Specialty hospitals—Licenses—Exemptions.
. The definitions in this subsection apply throughout this section unless the context clearly requires otherwise.

.. "Emergency services" means health care services medically necessary to evaluate and treat a medical condition that manifests itself by the acute onset of a symptom or symptoms, including severe pain, that would lead a prudent layperson acting reasonably to believe that a health condition exists that requires immediate medical attention, and that the absence of immediate medical attention could reasonably be expected to result in serious impairment to bodily functions or serious dysfunction of an organ or part of the body, or would place the person's health, or in the case of a pregnant woman, the health of the woman or her unborn child, in serious jeopardy.

.. "General hospital" means a hospital that provides general acute care services, including emergency services.

.. "Specialty hospital" means a subclass of hospital that is primarily or exclusively engaged in the care and treatment of one of the following categories: (i) Patients with a cardiac condition; (ii) patients with an orthopedic condition; (iii) patients receiving a surgical procedure; and (iv) any other specialized category of services that the secretary of health and human services designates as a specialty hospital.

.. "Transfer agreement" means a written agreement providing an effective process for the transfer of a patient requiring emergency services to a general hospital providing emergency services and for continuity of care for that patient.

.. "Health service area" has the same meaning as in RCW 70.38.025.

. To be licensed under this chapter, a specialty hospital shall:

.. Be significantly engaged in providing inpatient care;

.. Comply with all standards and rules adopted by the department for hospitals;

.. Provide appropriate discharge planning;

.. Provide staff proficient in resuscitation and respiration maintenance twenty-four hours per day, seven days per week;

.. Participate in the medicare and medicaid programs and provide at least the same percentage of services to medicare and medicaid beneficiaries, as a percent of gross revenues, as the lowest percentage of services provided to medicare and medicaid beneficiaries by a general hospital in the same health service area. The lowest percentage of services provided to medicare and medicaid beneficiaries shall be determined by the department in consultation with the general hospitals in the health service area but shall not be the percentage of medicare and medicaid services of a hospital that serves primarily members of a particular health plan or government sponsor;

.. Provide at least the same percentage of charity care, as a percent of gross revenues, as the lowest percentage of charity care provided by a general hospital in the same health service area. The lowest percentage of charity care shall be determined by the department in consultation with the general hospitals in the health service area but shall not be the percentage of charity care of a hospital that serves primarily members of a particular health plan or government sponsor;

.. Require any physician owner to: (i) In accordance with chapter 19.68 RCW, disclose a financial interest in the specialty hospital and provide a list of alternative hospitals before referring a patient to the specialty hospital; and (ii) if the specialty hospital does not have an intensive care unit, notify the patient that if intensive care services are required, the patient will be transferred to another hospital;

.. Provide emergency services twenty-four hours per day, seven days per week in a designated area of the hospital, and comply with requirements for emergency facilities that are established by the department;

.. Establish procedures to stabilize a patient with an emergency medical condition until the patient is transported or transferred to another hospital if emergency services cannot be provided at the specialty hospital to meet the needs of the patient in an emergency, and maintain a transfer agreement with a general hospital in the same health service area that establishes a process for patient transfers in a situation in which the specialty hospital cannot provide continuing care for a patient because of the specialty hospital's scope of services and for the transfer of patients; and

.. Accept the transfer of patients from general hospitals when the patients require the category of care or treatment provided by the specialty hospital.

. This section does not apply to:

.. A specialty hospital that provides only psychiatric, pediatric, long-term acute care, cancer, or rehabilitative services; or

.. A hospital that was licensed under this chapter before January 1, 2007.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5398.SL.pdf?cite=2007%20c%20102%20§%202[2007 c 102 § 2]; ]

== 70.41.120 - Inspection of hospitals—Final report—Alterations or additions, new facilities—Coordination with state and local agencies—Notice of inspection.
. The department shall make or cause to be made an unannounced inspection of all hospitals on average at least every eighteen months. Every inspection of a hospital may include an inspection of every part of the premises. The department may make an examination of all phases of the hospital operation necessary to determine compliance with the law and the standards, rules and regulations adopted thereunder.

. The department shall not issue its final report regarding an unannounced inspection by the department until: (a) The hospital is given at least two weeks following the inspection to provide any information or documentation requested by the department during the unannounced inspection that was not available at the time of the request; and (b) at least one person from the department conducting the inspection meets personally with the chief administrator or executive officer of the hospital following the inspection or the chief administrator or executive officer declines such a meeting.

. Any licensee or applicant desiring to make alterations or additions to its facilities or to construct new facilities shall, before commencing such alteration, addition or new construction, comply with the regulations prescribed by the department.

. No hospital licensed pursuant to the provisions of this chapter shall be required to be inspected or licensed under other state laws or rules and regulations promulgated thereunder, or local ordinances, relative to hotels, restaurants, lodging houses, boarding houses, places of refreshment, nursing homes, maternity homes, or psychiatric hospitals.

. To avoid unnecessary duplication in inspections, the department shall coordinate with the department of social and health services, the office of the state fire marshal, and local agencies when inspecting facilities over which each agency has jurisdiction, the facilities including but not necessarily being limited to hospitals with both acute care and skilled nursing or psychiatric nursing functions. The department shall notify the office of the state fire marshal and the relevant local agency at least four weeks prior to any inspection conducted under this section and invite their attendance at the inspection, and shall provide a copy of its inspection report to each agency upon completion.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1021-S2.SL.pdf?cite=2009%20c%20242%20§%201[2009 c 242 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1533.SL.pdf?cite=2005%20c%20447%20§%201[2005 c 447 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6485.SL.pdf?cite=2004%20c%20261%20§%204[2004 c 261 § 4]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1445.SL.pdf?cite=1995%20c%20282%20§%204[1995 c 282 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c213.pdf?cite=1985%20c%20213%20§%2021[1985 c 213 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c267.pdf?cite=1955%20c%20267%20§%2012[1955 c 267 § 12]; ]

== 70.41.122 - Exemption from RCW  70.41.120 for hospitals accredited by other entities.
Surveys conducted on hospitals by the joint commission on the accreditation of health care organizations, the American osteopathic association, or Det Norske Veritas shall be deemed equivalent to a department survey for purposes of meeting the requirements for the survey specified in RCW 70.41.120 if the department determines that the applicable survey standards are substantially equivalent to its own.

. Hospitals so surveyed shall provide to the department within thirty days of learning the result of a survey documentary evidence that the hospital has been certified as a result of a survey and the date of the survey.

. Hospitals shall make available to department surveyors the written reports of such surveys during department surveys, upon request.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1021-S2.SL.pdf?cite=2009%20c%20242%20§%202[2009 c 242 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1533.SL.pdf?cite=2005%20c%20447%20§%202[2005 c 447 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5114.SL.pdf?cite=1999%20c%2041%20§%201[1999 c 41 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1445.SL.pdf?cite=1995%20c%20282%20§%206[1995 c 282 § 6]; ]

== 70.41.125 - Hospital construction review process—Coordination with state and local agencies.
. The department shall coordinate its hospital construction review process with other state and local agencies having similar review responsibilities, including the department of labor and industries, the office of the state fire marshal, and local building and fire officials. Inconsistencies or conflicts among the agencies shall be identified and eliminated. The department shall provide local agencies with relevant information derived from its construction review process.

. By September 1, 2004, the department shall report to the legislature regarding its implementation of subsection (1) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6485.SL.pdf?cite=2004%20c%20261%20§%205[2004 c 261 § 5]; ]

== 70.41.130 - Denial, suspension, revocation, modification of license—Procedure.
The department is authorized to deny, suspend, revoke, or modify a license or provisional license in any case in which it finds that there has been a failure or refusal to comply with the requirements of this chapter or the standards or rules adopted under this chapter or the requirements of RCW 71.34.375. RCW 43.70.115 governs notice of a license denial, revocation, suspension, or modification and provides the right to an adjudicative proceeding.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5187-S.SL.pdf?cite=2011%20c%20302%20§%203[2011 c 302 § 3]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20335[1991 c 3 § 335]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%20128[1989 c 175 § 128]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c213.pdf?cite=1985%20c%20213%20§%2022[1985 c 213 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c267.pdf?cite=1955%20c%20267%20§%2013[1955 c 267 § 13]; ]

== 70.41.150 - Denial, suspension, revocation of license—Disclosure of information.
Information received by the department through filed reports, inspection, or as otherwise authorized under this chapter, may be disclosed publicly, as permitted under chapter 42.56 RCW, subject to the following provisions:

. Licensing inspections, or complaint investigations regardless of findings, shall, as requested, be disclosed no sooner than three business days after the hospital has received the resulting assessment report;

. Information regarding administrative action against the license shall, as requested, be disclosed after the hospital has received the documents initiating the administrative action;

. Information about complaints that did not warrant an investigation shall not be disclosed except to notify the hospital and the complainant that the complaint did not warrant an investigation. If requested, the individual complainant shall receive information on other like complaints that have been reported against the hospital; and

. Information disclosed pursuant to this section shall not disclose individual names.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20333[2005 c 274 § 333]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1711.SL.pdf?cite=2000%20c%206%20§%201[2000 c 6 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c213.pdf?cite=1985%20c%20213%20§%2024[1985 c 213 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c267.pdf?cite=1955%20c%20267%20§%2015[1955 c 267 § 15]; ]

== 70.41.155 - Duty to investigate patient well-being.
Any complaint against a hospital and event notification required by the department that concerns patient well-being shall be investigated.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1711.SL.pdf?cite=2000%20c%206%20§%202[2000 c 6 § 2]; ]

== 70.41.160 - Remedies available to department—Duty of attorney general.
Notwithstanding the existence or pursuit of any other remedy, the department may, in the manner provided by law, upon the advice of the attorney general who shall represent the department in the proceedings, maintain an action in the name of the state for an injunction or other process against any person or governmental unit to restrain or prevent the establishment, conduct, or operation of a hospital without a license under this law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c213.pdf?cite=1985%20c%20213%20§%2025[1985 c 213 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c267.pdf?cite=1955%20c%20267%20§%2016[1955 c 267 § 16]; ]

== 70.41.170 - Operating or maintaining unlicensed hospital or unapproved tertiary health service—Penalty.
Any person operating or maintaining a hospital without a license under this chapter, or, after June 30, 1989, initiating a tertiary health service as defined in RCW 70.38.025(14) that is not approved under RCW 70.38.105 and 70.38.115, shall be guilty of a misdemeanor, and each day of operation of an unlicensed hospital or unapproved tertiary health service, shall constitute a separate offense.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20612[1989 1st ex.s. c 9 § 612]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c267.pdf?cite=1955%20c%20267%20§%2017[1955 c 267 § 17]; ]

== 70.41.180 - Physicians' services.
Nothing contained in this chapter shall in any way authorize the department to establish standards, rules and regulations governing the professional services rendered by any physician.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c213.pdf?cite=1985%20c%20213%20§%2026[1985 c 213 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c267.pdf?cite=1955%20c%20267%20§%2018[1955 c 267 § 18]; ]

== 70.41.190 - Medical records of patients—Retention and preservation.
Unless specified otherwise by the department, a hospital shall retain and preserve all medical records which relate directly to the care and treatment of a patient for a period of no less than ten years following the most recent discharge of the patient; except the records of minors, which shall be retained and preserved for a period of no less than three years following attainment of the age of eighteen years, or ten years following such discharge, whichever is longer.

If a hospital ceases operations, it shall make immediate arrangements, as approved by the department, for preservation of its records.

The department shall by regulation define the type of records and the information required to be included in the medical records to be retained and preserved under this section; which records may be retained in photographic form pursuant to chapter 5.46 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c213.pdf?cite=1985%20c%20213%20§%2027[1985 c 213 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c175.pdf?cite=1975%201st%20ex.s.%20c%20175%20§%201[1975 1st ex.s. c 175 § 1]; ]

== 70.41.200 - Quality improvement and medical malpractice prevention program—Quality improvement committee—Sanction and grievance procedures—Information collection, reporting, and sharing.
. Every hospital shall maintain a coordinated quality improvement program for the improvement of the quality of health care services rendered to patients and the identification and prevention of medical malpractice. The program shall include at least the following:

.. The establishment of one or more quality improvement committees with the responsibility to review the services rendered in the hospital, both retrospectively and prospectively, in order to improve the quality of medical care of patients and to prevent medical malpractice. Different quality improvement committees may be established as a part of a quality improvement program to review different health care services. Such committees shall oversee and coordinate the quality improvement and medical malpractice prevention program and shall ensure that information gathered pursuant to the program is used to review and to revise hospital policies and procedures;

.. A process, including a medical staff privileges sanction procedure which must be conducted substantially in accordance with medical staff bylaws and applicable rules, regulations, or policies of the medical staff through which credentials, physical and mental capacity, professional conduct, and competence in delivering health care services are periodically reviewed as part of an evaluation of staff privileges;

.. A process for the periodic review of the credentials, physical and mental capacity, professional conduct, and competence in delivering health care services of all other health care providers who are employed or associated with the hospital;

.. A procedure for the prompt resolution of grievances by patients or their representatives related to accidents, injuries, treatment, and other events that may result in claims of medical malpractice;

.. The maintenance and continuous collection of information concerning the hospital's experience with negative health care outcomes and incidents injurious to patients including health care-associated infections as defined in RCW 43.70.056, patient grievances, professional liability premiums, settlements, awards, costs incurred by the hospital for patient injury prevention, and safety improvement activities;

.. The maintenance of relevant and appropriate information gathered pursuant to (a) through (e) of this subsection concerning individual physicians within the physician's personnel or credential file maintained by the hospital;

.. Education programs dealing with quality improvement, patient safety, medication errors, injury prevention, infection control, staff responsibility to report professional misconduct, the legal aspects of patient care, improved communication with patients, and causes of malpractice claims for staff personnel engaged in patient care activities; and

.. Policies to ensure compliance with the reporting requirements of this section.

. Any person who, in substantial good faith, provides information to further the purposes of the quality improvement and medical malpractice prevention program or who, in substantial good faith, participates on the quality improvement committee shall not be subject to an action for civil damages or other relief as a result of such activity. Any person or entity participating in a coordinated quality improvement program that, in substantial good faith, shares information or documents with one or more other programs, committees, or boards under subsection (8) of this section is not subject to an action for civil damages or other relief as a result of the activity. For the purposes of this section, sharing information is presumed to be in substantial good faith. However, the presumption may be rebutted upon a showing of clear, cogent, and convincing evidence that the information shared was knowingly false or deliberately misleading.

. Information and documents, including complaints and incident reports, created specifically for, and collected and maintained by, a quality improvement committee are not subject to review or disclosure, except as provided in this section, or discovery or introduction into evidence in any civil action, and no person who was in attendance at a meeting of such committee or who participated in the creation, collection, or maintenance of information or documents specifically for the committee shall be permitted or required to testify in any civil action as to the content of such proceedings or the documents and information prepared specifically for the committee. This subsection does not preclude: (a) In any civil action, the discovery of the identity of persons involved in the medical care that is the basis of the civil action whose involvement was independent of any quality improvement activity; (b) in any civil action, the testimony of any person concerning the facts which form the basis for the institution of such proceedings of which the person had personal knowledge acquired independently of such proceedings; (c) in any civil action by a health care provider regarding the restriction or revocation of that individual's clinical or staff privileges, introduction into evidence information collected and maintained by quality improvement committees regarding such health care provider; (d) in any civil action, disclosure of the fact that staff privileges were terminated or restricted, including the specific restrictions imposed, if any and the reasons for the restrictions; or (e) in any civil action, discovery and introduction into evidence of the patient's medical records required by regulation of the department of health to be made regarding the care and treatment received.

. Each quality improvement committee shall, on at least a semiannual basis, report to the governing board of the hospital in which the committee is located. The report shall review the quality improvement activities conducted by the committee, and any actions taken as a result of those activities.

. The department of health shall adopt such rules as are deemed appropriate to effectuate the purposes of this section.

. The Washington medical commission or the board of osteopathic medicine and surgery, as appropriate, may review and audit the records of committee decisions in which a physician's privileges are terminated or restricted. Each hospital shall produce and make accessible to the commission or board the appropriate records and otherwise facilitate the review and audit. Information so gained shall not be subject to the discovery process and confidentiality shall be respected as required by subsection (3) of this section. Failure of a hospital to comply with this subsection is punishable by a civil penalty not to exceed two hundred fifty dollars.

. The department, the joint commission on accreditation of health care organizations, and any other accrediting organization may review and audit the records of a quality improvement committee or peer review committee in connection with their inspection and review of hospitals. Information so obtained shall not be subject to the discovery process, and confidentiality shall be respected as required by subsection (3) of this section. Each hospital shall produce and make accessible to the department the appropriate records and otherwise facilitate the review and audit.

. A coordinated quality improvement program may share information and documents, including complaints and incident reports, created specifically for, and collected and maintained by, a quality improvement committee or a peer review committee under RCW 4.24.250 with one or more other coordinated quality improvement programs maintained in accordance with this section or RCW 43.70.510, a coordinated quality improvement committee maintained by an ambulatory surgical facility under RCW 70.230.070, a quality assurance committee maintained in accordance with RCW 18.20.390 or 74.42.640, or a peer review committee under RCW 4.24.250, for the improvement of the quality of health care services rendered to patients and the identification and prevention of medical malpractice. The privacy protections of chapter 70.02 RCW and the federal health insurance portability and accountability act of 1996 and its implementing regulations apply to the sharing of individually identifiable patient information held by a coordinated quality improvement program. Any rules necessary to implement this section shall meet the requirements of applicable federal and state privacy laws. Information and documents disclosed by one coordinated quality improvement program to another coordinated quality improvement program or a peer review committee under RCW 4.24.250 and any information and documents created or maintained as a result of the sharing of information and documents shall not be subject to the discovery process and confidentiality shall be respected as required by subsection (3) of this section, RCW 18.20.390 (6) and (8), 74.42.640 (7) and (9), and 4.24.250.

. A hospital that operates a nursing home as defined in RCW 18.51.010 may conduct quality improvement activities for both the hospital and the nursing home through a quality improvement committee under this section, and such activities shall be subject to the provisions of subsections (2) through (8) of this section.

. Violation of this section shall not be considered negligence per se.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5764.SL.pdf?cite=2019%20c%2055%20§%2014[2019 c 55 § 14]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5666.SL.pdf?cite=2013%20c%20301%20§%202[2013 c 301 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1414-S.SL.pdf?cite=2007%20c%20273%20§%2022[2007 c 273 § 22]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1106-S2.SL.pdf?cite=2007%20c%20261%20§%203[2007 c 261 § 3]; prior:  2005 c 291 § 3; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1569-S.SL.pdf?cite=2005%20c%2033%20§%207[2005 c 33 § 7]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6210-S.SL.pdf?cite=2004%20c%20145%20§%203[2004 c 145 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1711.SL.pdf?cite=2000%20c%206%20§%203[2000 c 6 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20742[1994 sp.s. c 9 § 742]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20415[1993 c 492 § 415]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20336[1991 c 3 § 336]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c269.pdf?cite=1987%20c%20269%20§%205[1987 c 269 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c300.pdf?cite=1986%20c%20300%20§%204[1986 c 300 § 4]; ]

== 70.41.205 - Public hospitals—Review of hospital privileges and quality improvement committee reports—Confidentiality.
. All meetings, proceedings, and deliberations of the governing body, its staff or agents, concerning the granting, denial, revocation, restriction, or other consideration of the status of the clinical or staff privileges of a physician or other health care provider as defined in RCW 7.70.020, if such other providers at the discretion of the governing body are considered for such privileges, must be confidential and may be conducted in executive session; however, the final action of the governing body as to the denial, revocation, or restriction of clinical or staff privileges of a physician or other health care provider as defined in RCW 7.70.020 must be done in public session.

. All meetings, proceedings, and deliberations of a quality improvement committee established under RCW 4.24.250, 43.70.510, or 70.41.200 and all meetings, proceedings, and deliberations of the governing body, its staff or agents, to review the report or the activities of a quality improvement committee established under RCW 4.24.250, 43.70.510, or 70.41.200 may, at the discretion of the quality improvement committee or the governing body, be confidential and may be conducted in executive session. Any review conducted by the governing body or quality improvement committee, or their staff or agents, must be subject to the same protections, limitations, and exemptions that apply to quality improvement committee activities under RCW 4.24.240, 4.24.250, 43.70.510, and 70.41.200. However, any final action of the governing body on the report of the quality improvement committee must be done in public session.

. For the purposes of this section:

.. "Governing body" means the board or committee of a public hospital with authority to make final decisions concerning the granting, denial, revocation, restriction, or other consideration of the clinical or staff privileges of a physician or other health care provider, as defined in RCW 7.70.020; and

.. "Public hospital" means any hospital owned or operated by the state or any of its subdivisions, including the University of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1239-S.SL.pdf?cite=2019%20c%20162%20§%201[2019 c 162 § 1]; ]

== 70.41.210 - Duty to report restrictions on health care practitioners' privileges based on unprofessional conduct—Penalty. (Effective until July 1, 2022.)
. The chief administrator or executive officer of a hospital shall report to the department when the practice of a health care practitioner as defined in subsection (2) of this section is restricted, suspended, limited, or terminated based upon a conviction, determination, or finding by the hospital that the health care practitioner has committed an action defined as unprofessional conduct under RCW 18.130.180. The chief administrator or executive officer shall also report any voluntary restriction or termination of the practice of a health care practitioner as defined in subsection (2) of this section while the practitioner is under investigation or the subject of a proceeding by the hospital regarding unprofessional conduct, or in return for the hospital not conducting such an investigation or proceeding or not taking action. The department will forward the report to the appropriate disciplining authority.

. The reporting requirements apply to the following health care practitioners: Pharmacists as defined in chapter 18.64 RCW; advanced registered nurse practitioners as defined in chapter 18.79 RCW; dentists as defined in chapter 18.32 RCW; naturopaths as defined in chapter 18.36A RCW; optometrists as defined in chapter 18.53 RCW; osteopathic physicians and surgeons as defined in chapter 18.57 RCW; osteopathic physicians' assistants as defined in chapter 18.57A RCW; physicians as defined in chapter 18.71 RCW; physician assistants as defined in chapter 18.71A RCW; podiatric physicians and surgeons as defined in chapter 18.22 RCW; and psychologists as defined in chapter 18.83 RCW.

. Reports made under subsection (1) of this section shall be made within fifteen days of the date: (a) A conviction, determination, or finding is made by the hospital that the health care practitioner has committed an action defined as unprofessional conduct under RCW 18.130.180; or (b) the voluntary restriction or termination of the practice of a health care practitioner, including his or her voluntary resignation, while under investigation or the subject of proceedings regarding unprofessional conduct under RCW 18.130.180 is accepted by the hospital.

. Failure of a hospital to comply with this section is punishable by a civil penalty not to exceed five hundred dollars.

. A hospital, its chief administrator, or its executive officer who files a report under this section is immune from suit, whether direct or derivative, in any civil action related to the filing or contents of the report, unless the conviction, determination, or finding on which the report and its content are based is proven to not have been made in good faith. The prevailing party in any action brought alleging the conviction, determination, finding, or report was not made in good faith, shall be entitled to recover the costs of litigation, including reasonable attorneys' fees.

. The department shall forward reports made under subsection (1) of this section to the appropriate disciplining authority designated under Title 18 RCW within fifteen days of the date the report is received by the department. The department shall notify a hospital that has made a report under subsection (1) of this section of the results of the disciplining authority's case disposition decision within fifteen days after the case disposition. Case disposition is the decision whether to issue a statement of charges, take informal action, or close the complaint without action against a practitioner. In its biennial report to the legislature under RCW 18.130.310, the department shall specifically identify the case dispositions of reports made by hospitals under subsection (1) of this section.

. The department shall not increase hospital license fees to carry out this section before July 1, 2008.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1103-S4.SL.pdf?cite=2008%20c%20134%20§%2014[2008 c 134 § 14]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5492-S.SL.pdf?cite=2005%20c%20470%20§%201[2005 c 470 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20743[1994 sp.s. c 9 § 743]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c300.pdf?cite=1986%20c%20300%20§%207[1986 c 300 § 7]; ]

== 70.41.220 - Duty to keep records of restrictions on practitioners' privileges—Penalty.
Each hospital shall keep written records of decisions to restrict or terminate privileges of practitioners. Copies of such records shall be made available to the board within thirty days of a request and all information so gained shall remain confidential in accordance with RCW 70.41.200 and 70.41.230 and shall be protected from the discovery process. Failure of a hospital to comply with this section is punishable by [a] civil penalty not to exceed two hundred fifty dollars.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c300.pdf?cite=1986%20c%20300%20§%208[1986 c 300 § 8]; ]

== 70.41.230 - Duty of hospital to request information on physicians, physician assistants, or advanced registered nurse practitioners granted privileges.
. Except as provided in subsection (3) of this section, prior to granting or renewing clinical privileges or association of any physician, physician assistant, or advanced registered nurse practitioner or hiring a physician, physician assistant, or advanced registered nurse practitioner who will provide clinical care under his or her license, a hospital or facility approved pursuant to this chapter shall request from the physician, physician assistant, or advanced registered nurse practitioner and the physician, physician assistant, or advanced registered nurse practitioner shall provide the following information:

.. The name of any hospital or facility with or at which the physician, physician assistant, or advanced registered nurse practitioner had or has any association, employment, privileges, or practice during the prior five years: PROVIDED, That the hospital may request additional information going back further than five years, and the physician, physician assistant, or advanced registered nurse practitioner shall use his or her best efforts to comply with such a request for additional information;

.. Whether the physician, physician assistant, or advanced registered nurse practitioner has ever been or is in the process of being denied, revoked, terminated, suspended, restricted, reduced, limited, sanctioned, placed on probation, monitored, or not renewed for any professional activity listed in (b)(i) through (x) of this subsection, or has ever voluntarily or involuntarily relinquished, withdrawn, or failed to proceed with an application for any professional activity listed in (b)(i) through (x) of this subsection in order to avoid an adverse action or to preclude an investigation or while under investigation relating to professional competence or conduct:

... License to practice any profession in any jurisdiction;

... Other professional registration or certification in any jurisdiction;

... Specialty or subspecialty board certification;

... Membership on any hospital medical staff;

.. Clinical privileges at any facility, including hospitals, ambulatory surgical centers, or skilled nursing facilities;

.. Medicare, medicaid, the food and drug administration, the national institute of health (office of human research protection), governmental, national, or international regulatory agency, or any public program;

.. Professional society membership or fellowship;

.. Participation or membership in a health maintenance organization, preferred provider organization, independent practice association, physician-hospital organization, or other entity;

... Academic appointment;

.. Authority to prescribe controlled substances (drug enforcement agency or other authority);

.. Any pending professional medical misconduct proceedings or any pending medical malpractice actions in this state or another state, the substance of the allegations in the proceedings or actions, and any additional information concerning the proceedings or actions as the physician, physician assistant, or advanced registered nurse practitioner deems appropriate;

.. The substance of the findings in the actions or proceedings and any additional information concerning the actions or proceedings as the physician, physician assistant, or advanced registered nurse practitioner deems appropriate;

.. A waiver by the physician, physician assistant, or advanced registered nurse practitioner of any confidentiality provisions concerning the information required to be provided to hospitals pursuant to this subsection; and

.. A verification by the physician, physician assistant, or advanced registered nurse practitioner that the information provided by the physician, physician assistant, or advanced registered nurse practitioner is accurate and complete.

. Except as provided in subsection (3) of this section, prior to granting privileges or association to any physician, physician assistant, or advanced registered nurse practitioner or hiring a physician, physician assistant, or advanced registered nurse practitioner who will provide clinical care under his or her license, a hospital or facility approved pursuant to this chapter shall request from any hospital with or at which the physician, physician assistant, or advanced registered nurse practitioner had or has privileges, was associated, or was employed, during the preceding five years, the following information concerning the physician, physician assistant, or advanced registered nurse practitioner:

.. Any pending professional medical misconduct proceedings or any pending medical malpractice actions, in this state or another state;

.. Any judgment or settlement of a medical malpractice action and any finding of professional misconduct in this state or another state by a licensing or disciplinary board; and

.. Any information required to be reported by hospitals pursuant to RCW 18.71.0195.

. In lieu of the requirements of subsections (1) and (2) of this section, when granting or renewing credentials and privileges or association of any physician, physician assistant, or advanced registered nurse practitioner providing telemedicine or store and forward services, an originating site hospital may rely on a distant site hospital's decision to grant or renew credentials and clinical privileges or association of the physician, physician assistant, or advanced registered nurse practitioner if the originating site hospital obtains reasonable assurances, through a written agreement with the distant site hospital, that all of the following provisions are met:

.. The distant site hospital providing the telemedicine or store and forward services is a medicare participating hospital;

.. Any physician, physician assistant, or advanced registered nurse practitioner providing telemedicine or store and forward services at the distant site hospital will be fully credentialed and privileged to provide such services by the distant site hospital;

.. Any physician, physician assistant, or advanced registered nurse practitioner providing telemedicine or store and forward services will hold and maintain a valid license to perform such services issued or recognized by the state of Washington; and

.. With respect to any distant site physician, physician assistant, or advanced registered nurse practitioner who holds current credentials and privileges at the originating site hospital whose patients are receiving the telemedicine or store and forward services, the originating site hospital has evidence of an internal review of the distant site physician's, physician assistant's, or advanced registered nurse practitioner's performance of these credentials and privileges and sends the distant site hospital such performance information for use in the periodic appraisal of the distant site physician, physician assistant, or advanced registered nurse practitioner. At a minimum, this information must include all adverse events, as defined in RCW 70.56.010, that result from the telemedicine or store and forward services provided by the distant site physician, physician assistant, or advanced registered nurse practitioner to the originating site hospital's patients and all complaints the originating site hospital has received about the distant site physician, physician assistant, or advanced registered nurse practitioner.

. [Empty]
.. The Washington medical commission or the board of osteopathic medicine and surgery shall be advised within thirty days of the name of any physician or physician assistant denied staff privileges, association, or employment on the basis of adverse findings under subsection (1) of this section.

.. The nursing care quality assurance commission shall be advised within thirty days of the name of any advanced registered nurse practitioner denied staff privileges, association, or employment on the basis of adverse findings under subsection (1) of this section.

. A hospital or facility that receives a request for information from another hospital or facility pursuant to subsections (1) through (3) of this section shall provide such information concerning the physician, physician assistant, or advanced registered nurse practitioner in question to the extent such information is known to the hospital or facility receiving such a request, including the reasons for suspension, termination, or curtailment of employment or privileges at the hospital or facility. A hospital, facility, or other person providing such information in good faith is not liable in any civil action for the release of such information.

. Information and documents, including complaints and incident reports, created specifically for, and collected, and maintained by a quality improvement committee are not subject to discovery or introduction into evidence in any civil action, and no person who was in attendance at a meeting of such committee or who participated in the creation, collection, or maintenance of information or documents specifically for the committee shall be permitted or required to testify in any civil action as to the content of such proceedings or the documents and information prepared specifically for the committee. This subsection does not preclude: (a) In any civil action, the discovery of the identity of persons involved in the medical care that is the basis of the civil action whose involvement was independent of any quality improvement activity; (b) in any civil action, the testimony of any person concerning the facts which form the basis for the institution of such proceedings of which the person had personal knowledge acquired independently of such proceedings; (c) in any civil action by a health care provider regarding the restriction or revocation of that individual's clinical or staff privileges, introduction into evidence information collected and maintained by quality improvement committees regarding such health care provider; (d) in any civil action, disclosure of the fact that staff privileges were terminated or restricted, including the specific restrictions imposed, if any and the reasons for the restrictions; or (e) in any civil action, discovery and introduction into evidence of the patient's medical records required by regulation of the department of health to be made regarding the care and treatment received.

. Hospitals shall be granted access to information held by the Washington medical commission, the board of osteopathic medicine and surgery, and the nursing care quality assurance commission pertinent to decisions of the hospital regarding credentialing and recredentialing of practitioners.

. Violation of this section shall not be considered negligence per se.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1432.SL.pdf?cite=2019%20c%20104%20§%201[2019 c 104 § 1]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5764.SL.pdf?cite=2019%20c%2055%20§%2015[2019 c 55 § 15]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2019%20c%2049%20§%201[2019 c 49 § 1]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6519-S.SL.pdf?cite=2016%20c%2068%20§%206[2016 c 68 § 6]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5175-S.SL.pdf?cite=2015%20c%2023%20§%206[2015 c 23 § 6]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5666.SL.pdf?cite=2013%20c%20301%20§%203[2013 c 301 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20744[1994 sp.s. c 9 § 744]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20416[1993 c 492 § 416]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20337[1991 c 3 § 337]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c269.pdf?cite=1987%20c%20269%20§%206[1987 c 269 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c300.pdf?cite=1986%20c%20300%20§%2011[1986 c 300 § 11]; ]

== 70.41.235 - Doctor of osteopathic medicine and surgery—Discrimination based on board certification is prohibited.
A hospital that provides health care services to the general public may not discriminate against a qualified doctor of osteopathic medicine and surgery licensed under chapter 18.57 RCW, who has applied to practice with the hospital, solely because that practitioner was board certified or eligible under an approved osteopathic certifying board instead of board certified or eligible respectively under an approved medical certifying board.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1360.SL.pdf?cite=1995%20c%2064%20§%203[1995 c 64 § 3]; ]

== 70.41.240 - Information regarding conversion of hospitals to nonhospital health care facilities.
The department of health shall compile and make available to the public information regarding medicare health care facility certification options available to hospitals licensed under this title that desire to convert to nonhospital health care facilities. The information provided shall include standards and requirements for certification and procedures for acquiring certification.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20338[1991 c 3 § 338]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c207.pdf?cite=1988%20c%20207%20§%203[1988 c 207 § 3]; ]

== 70.41.250 - Cost disclosure to health care providers.
. The legislature finds that the spiraling costs of health care continue to surmount efforts to contain them, increasing at approximately twice the inflationary rate. The causes of this phenomenon are complex. By making physicians and other health care providers with hospital admitting privileges more aware of the cost consequences of health care services for consumers, these providers may be inclined to exercise more restraint in providing only the most relevant and cost-beneficial hospital services, with a potential for reducing the utilization of those services. The requirement of the hospital to inform physicians and other health care providers of the charges of the health care services that they order may have a positive effect on containing health costs. Further, the option of the physician or other health care provider to inform the patient of these charges may strengthen the necessary dialogue in the provider-patient relationship that tends to be diminished by intervening third-party payers.

. The chief executive officer of a hospital licensed under this chapter and the superintendent of a state hospital shall establish and maintain a procedure for disclosing to physicians and other health care providers with admitting privileges the charges of all health care services ordered for their patients. Copies of hospital charges shall be made available to any physician and/or other health care provider ordering care in hospital inpatient/outpatient services. The physician and/or other health care provider may inform the patient of these charges and may specifically review them. Hospitals are also directed to study methods for making daily charges available to prescribing physicians through the use of interactive software and/or computerized information thereby allowing physicians and other health care providers to review not only the costs of present and past services but also future contemplated costs for additional diagnostic studies and therapeutic medications.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20265[1993 c 492 § 265]; ]

== 70.41.300 - Long-term care—Definitions.
"Cost-effective care" and "long-term care services," where used in RCW 70.41.310 and 70.41.320, shall have the same meaning as that given in *RCW 74.39A.008.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1908-S2.SL.pdf?cite=1995%201st%20sp.s.%20c%2018%20§%204[1995 1st sp.s. c 18 § 4]; ]

== 70.41.310 - Long-term care—Program information to be provided to hospitals—Information on options to be provided to patients.
. [Empty]
.. The department of social and health services, in consultation with hospitals and acute care facilities, shall promote the most appropriate and cost-effective use of long-term care services by developing and distributing to hospitals and other appropriate health care settings information on the various chronic long-term care programs that it administers directly or through contract. The information developed by the department of social and health services shall, at a minimum, include the following:

... An identification and detailed description of each long-term care service available in the state;

... Functional, cognitive, and medicaid eligibility criteria that may be required for placement or admission to each long-term care service; and

... A long-term care services resource manual for each hospital, that identifies the long-term care services operating within each hospital's patient service area. The long-term care services resource manual shall, at a minimum, identify the name, address, and telephone number of each entity known to be providing long-term care services; a brief description of the programs or services provided by each of the identified entities; and the name or names of a person or persons who may be contacted for further information or assistance in accessing the programs or services at each of the identified entities.

.. The information required in (a) of this subsection shall be periodically updated and distributed to hospitals by the department of social and health services so that the information reflects current long-term care service options available within each hospital's patient service area.

. To the extent that a patient will have continuing care needs, once discharged from the hospital setting, hospitals shall, during the course of the patient's hospital stay, promote each patient's family member's and/or legal representative's understanding of available long-term care service discharge options by, at a minimum:

.. Discussing the various and relevant long-term care services available, including eligibility criteria;

.. Making available, to patients, their family members, and/or legal representative, a copy of the most current long-term care services resource manual;

.. Responding to long-term care questions posed by patients, their family members, and/or legal representative;

.. Assisting the patient, their family members, and/or legal representative in contacting appropriate persons or entities to respond to the question or questions posed; and

.. Linking the patient and family to the local, state-designated aging and long-term care network to ensure effective transitions to appropriate levels of care and ongoing support.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1908-S2.SL.pdf?cite=1995%201st%20sp.s.%20c%2018%20§%203[1995 1st sp.s. c 18 § 3]; ]

== 70.41.320 - Long-term care—Patient discharge requirements for hospitals and acute care facilities—Pilot projects.
. Hospitals and acute care facilities shall:

.. Work cooperatively with the department of social and health services, area agencies on aging, and local long-term care information and assistance organizations in the planning and implementation of patient discharges to long-term care services.

.. Establish and maintain a system for discharge planning and designate a person responsible for system management and implementation.

.. Establish written policies and procedures to:

... Identify patients needing further nursing, therapy, or supportive care following discharge from the hospital;

... Subject to RCW 70.41.322, develop a documented discharge plan for each identified patient, including relevant patient history, specific care requirements, and date such follow-up care is to be initiated;

... Coordinate with patient, family, caregiver, lay caregiver as provided in RCW 70.41.322, and appropriate members of the health care team which may include a long-term care worker or a home and community-based service provider. For the purposes of this subsection (1)(c)(iii), long-term care worker has the meaning provided in RCW 74.39A.009 and home and community-based service provider includes an adult family home as defined in RCW 70.128.010, an assisted living facility as defined in RCW 18.20.020, or a home care agency as defined in RCW 70.127.010;

... Provide any patient, regardless of income status, written information and verbal consultation regarding the array of long-term care options available in the community, including the relative cost, eligibility criteria, location, and contact persons;

.. Promote an informed choice of long-term care services on the part of patients, family members, and legal representatives;

.. Coordinate with the department and specialized case management agencies, including area agencies on aging and other appropriate long-term care providers, as necessary, to ensure timely transition to appropriate home, community residential, or nursing facility care; and

.. Inform the patient or his or her surrogate decision maker designated under RCW 7.70.065 if it is necessary to complete a valid disclosure authorization as required by state and federal laws governing health information privacy and security, including chapter 70.02 RCW and the federal health insurance portability and accountability act of 1996 and related regulations, in order to allow disclosure of health care information, including the discharge plan, to an individual or entity that will be involved in the patient's care upon discharge, including a lay caregiver as defined in RCW 70.41.020, a long-term care worker as defined in RCW 74.39A.009, a home and community-based service provider such as an adult family home as defined in RCW 70.128.010, an assisted living facility as defined in RCW 18.20.020, or a home care agency as defined in RCW 70.127.010. If a valid disclosure authorization is obtained, the hospital may release information as designated by the patient for care coordination or other specified purposes.

.. Work in cooperation with the department which is responsible for ensuring that patients eligible for medicaid long-term care receive prompt assessment and appropriate service authorization.

. In partnership with selected hospitals, the department of social and health services shall develop and implement pilot projects in up to three areas of the state with the goal of providing information about appropriate in-home and community services to individuals and their families early during the individual's hospital stay.

The department shall not delay hospital discharges but shall assist and support the activities of hospital discharge planners. The department also shall coordinate with home health and hospice agencies whenever appropriate. The role of the department is to assist the hospital and to assist patients and their families in making informed choices by providing information regarding home and community options.

In conducting the pilot projects, the department shall:

.. Assess and offer information regarding appropriate in-home and community services to individuals who are medicaid clients or applicants; and

.. Offer assessment and information regarding appropriate in-home and community services to individuals who are reasonably expected to become medicaid recipients within one hundred eighty days of admission to a nursing facility.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6327-S.SL.pdf?cite=2016%20c%20226%20§%205[2016 c 226 § 5]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%20127[1998 c 245 § 127]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1908-S2.SL.pdf?cite=1995%201st%20sp.s.%20c%2018%20§%205[1995 1st sp.s. c 18 § 5]; ]

== 70.41.322 - Discharge planning—Requirements—Lay caregivers.
. In addition to the requirements in RCW 70.41.320, hospital discharge policies must ensure that the discharge plan is appropriate for the patient's physical condition, emotional and social needs, and, if a lay caregiver is designated takes into consideration, to the extent possible, the lay caregiver's abilities as disclosed to the hospital.

. As part of a patient's individualized treatment plan, discharge criteria must include, but not be limited to, the following components:

.. The details of the discharge plan;

.. Hospital staff assessment of the patient's ability for self-care after discharge;

.. An opportunity for the patient to designate a lay caregiver;

.. Documentation of any designated lay caregiver's contact information;

.. A description of aftercare tasks necessary to promote the patient's ability to stay at home;

.. An opportunity for the patient and, if designated, the patient's lay caregiver to participate in the discharge planning;

.. Instruction or training provided to the patient and, if designated, the patient's lay caregiver, prior to discharge, to perform aftercare tasks. Instruction or training may include education and counseling about the patient's medications, including dosing and proper use of medication delivery devices when applicable; and

.. Notification to a lay caregiver, if designated, of the patient's discharge or transfer.

. In the event that a hospital is unable to contact a designated lay caregiver, the lack of contact may not interfere with, delay, or otherwise affect the medical care provided to the patient, or an appropriate discharge of the patient.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6327-S.SL.pdf?cite=2016%20c%20226%20§%202[2016 c 226 § 2]; ]

== 70.41.324 - Discharge planning—Certain policies and criteria not required.
RCW 70.41.322 does not require a hospital to adopt discharge policies or criteria that:

. Delay a patient's discharge or transfer to another facility or to home; or

. Require the disclosure of protected health information to a lay caregiver without obtaining a patient's consent as required by state and federal laws governing health information privacy and security, including chapter 70.02 RCW and the federal health insurance portability and accountability act of 1996 and related regulations.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6327-S.SL.pdf?cite=2016%20c%20226%20§%203[2016 c 226 § 3]; ]

== 70.41.326 - Discharge planning—Construction—Liability.
Nothing in RCW 70.41.322 may be construed to:

. Interfere with the rights or duties of an agent operating under a valid health care directive under RCW 70.122.030;

. Interfere with designations made by a patient pursuant to a physician order for life-sustaining treatment under RCW 43.70.480;

. Interfere with the rights or duties of an authorized surrogate decision maker under RCW 7.70.065;

. Establish a new requirement to reimburse or otherwise pay for services performed by the lay caregiver for aftercare;

. Create a private right of action against a hospital or any of its directors, trustees, officers, employees, or agents, or any contractors with whom the hospital has a contractual relationship;

. Hold liable, in any way, a hospital, hospital employee, or any consultants or contractors with whom the hospital has a contractual relationship for the services rendered or not rendered by the lay caregiver to the patient at the patient's residence;

. Obligate a designated lay caregiver to perform any aftercare tasks for any patient;

. Require a patient to designate any individual as a lay caregiver as defined in RCW 70.41.020;

. Obviate the obligation of a health carrier as defined in RCW 48.43.005 or any other entity issuing health benefit plans to provide coverage required under a health benefit plan; and

. Impact, impede, or otherwise disrupt or reduce the reimbursement obligations of a health carrier or any other entity issuing health benefit plans.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6327-S.SL.pdf?cite=2016%20c%20226%20§%204[2016 c 226 § 4]; ]

== 70.41.330 - Hospital complaint toll-free telephone number.
Every hospital shall post in conspicuous locations a notice of the department's hospital complaint toll-free telephone number. The form of the notice shall be approved by the department.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1711.SL.pdf?cite=2000%20c%206%20§%204[2000 c 6 § 4]; ]

== 70.41.340 - Investigation of hospital complaints—Rules.
The department is authorized to adopt rules necessary to implement RCW 70.41.150, 70.41.155, and 70.41.330.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1711.SL.pdf?cite=2000%20c%206%20§%206[2000 c 6 § 6]; ]

== 70.41.350 - Emergency care provided to victims of sexual assault—Development of informational materials on emergency contraception—Rules.
. Every hospital providing emergency care to a victim of sexual assault shall:

.. Provide the victim with medically and factually accurate and unbiased written and oral information about emergency contraception;

.. Orally inform each victim of sexual assault of her option to be provided emergency contraception at the hospital; and

.. If not medically contraindicated, provide emergency contraception immediately at the hospital to each victim of sexual assault who requests it.

. The secretary, in collaboration with community sexual assault programs and other relevant stakeholders, shall develop, prepare, and produce informational materials relating to emergency contraception for the prevention of pregnancy in rape victims for distribution to and use in all emergency rooms in the state, in quantities sufficient to comply with the requirements of this section. The secretary, in collaboration with community sexual assault programs and other relevant stakeholders, may also approve informational materials from other sources for the purposes of this section. The informational materials must be clearly written and readily comprehensible in a culturally competent manner, as the secretary, in collaboration with community sexual assault programs and other relevant stakeholders, deems necessary to inform victims of sexual assault. The materials must explain the nature of emergency contraception, including that it is effective in preventing pregnancy, treatment options, and where they can be obtained.

. The secretary shall adopt rules necessary to implement this section.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6537-S.SL.pdf?cite=2002%20c%20116%20§%203[2002 c 116 § 3]; ]

== 70.41.360 - Emergency care provided to victims of sexual assault—Department to respond to violations—Task force.
The department must respond to complaints of violations of RCW 70.41.350. The department shall convene a task force, composed of representatives from community sexual assault programs and other relevant stakeholders including advocacy agencies, medical agencies, and hospital associations, to provide input into the development and evaluation of the education materials and rule development. The task force shall expire on January 1, 2004.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6537-S.SL.pdf?cite=2002%20c%20116%20§%204[2002 c 116 § 4]; ]

== 70.41.365 - Statewide sexual assault kit tracking system—Participation by hospitals.
Hospitals licensed under this chapter shall participate in the statewide sexual assault kit tracking system established in RCW 43.43.545 for the purpose of tracking the status of all sexual assault kits collected by or in the custody of hospitals and other entities contracting with hospitals. Hospitals shall begin full participation in the system according to the implementation schedule established by the Washington state patrol.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2530-S2.SL.pdf?cite=2016%20c%20173%20§%206[2016 c 173 § 6]; ]

== 70.41.367 - Sexual assault evidence kit collection—Availability, plan, and notice requirements.
. By July 1, 2020, any hospital that does not provide sexual assault evidence kit collection, or does not have appropriate providers available to provide sexual assault evidence kit collection at all times, shall develop a plan, in consultation with the local community sexual assault agency, to assist individuals with obtaining sexual assault evidence kit collection at a facility that provides such collection.

. Beginning July 1, 2020:

.. If a hospital does not perform sexual assault evidence kit collection or does not have appropriate providers available, the hospital shall, within two hours of a request, provide notice to every individual who presents in the emergency department of the hospital and requests a sexual assault evidence kit collection that the hospital does not perform such collection or does not have appropriate providers available; and

.. Pursuant to the plan required in subsection (1) of this section, if the hospital does not perform sexual assault evidence kit collection or does not have appropriate providers available, hospital staff must coordinate care with the local community sexual assault agency and assist the patient in finding a facility with an appropriate provider available.

. A hospital must notify individuals upon arrival who present in the emergency department of the hospital and request a sexual assault evidence kit collection that they may file a complaint with the department if the hospital fails to comply with subsection (2)(a) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1016.SL.pdf?cite=2019%20c%20250%20§%201[2019 c 250 § 1]; ]

== 70.41.370 - Investigation of complaints of violations concerning nursing technicians.
The department shall investigate complaints of violations of RCW 18.79.350 and 18.79.360 by an employer. The department shall maintain records of all employers that have violated RCW 18.79.350 and 18.79.360.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5829-S.SL.pdf?cite=2003%20c%20258%20§%208[2003 c 258 § 8]; ]

== 70.41.380 - Notice of unanticipated outcomes.
Hospitals shall have in place policies to assure that, when appropriate, information about unanticipated outcomes is provided to patients or their families or any surrogate decision makers identified pursuant to RCW 7.70.065. Notifications of unanticipated outcomes under this section do not constitute an acknowledgment or admission of liability, nor can the fact of notification, the content disclosed, or any and all statements, affirmations, gestures, or conduct expressing apology be introduced as evidence in a civil action.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5065-S.SL.pdf?cite=2005%20c%20118%20§%201[2005 c 118 § 1]; ]

== 70.41.390 - Safe patient handling.
. The definitions in this subsection apply throughout this section unless the context clearly requires otherwise.

.. "Lift team" means hospital employees specially trained to conduct patient lifts, transfers, and repositioning using lifting equipment when appropriate.

.. "Safe patient handling" means the use of engineering controls, lifting and transfer aids, or assistive devices, by lift teams or other staff, instead of manual lifting to perform the acts of lifting, transferring, and repositioning health care patients and residents.

.. "Musculoskeletal disorders" means conditions that involve the nerves, tendons, muscles, and supporting structures of the body.

. By February 1, 2007, each hospital must establish a safe patient handling committee either by creating a new committee or assigning the functions of a safe patient handling committee to an existing committee. The purpose of the committee is to design and recommend the process for implementing a safe patient handling program. At least half of the members of the safe patient handling committee shall be frontline nonmanagerial employees who provide direct care to patients unless doing so will adversely affect patient care.

. By December 1, 2007, each hospital must establish a safe patient handling program. As part of this program, a hospital must:

.. Implement a safe patient handling policy for all shifts and units of the hospital. Implementation of the safe patient handling policy may be phased-in with the acquisition of equipment under subsection (4) of this section;

.. Conduct a patient handling hazard assessment. This assessment should consider such variables as patient-handling tasks, types of nursing units, patient populations, and the physical environment of patient care areas;

.. Develop a process to identify the appropriate use of the safe patient handling policy based on the patient's physical and medical condition and the availability of lifting equipment or lift teams. The policy shall include a means to address circumstances under which it would be medically contraindicated to use lifting or transfer aids or assistive devices for particular patients;

.. Conduct an annual performance evaluation of the program to determine its effectiveness, with the results of the evaluation reported to the safe patient handling committee. The evaluation shall determine the extent to which implementation of the program has resulted in a reduction in musculoskeletal disorder claims and days of lost work attributable to musculoskeletal disorder caused by patient handling, and include recommendations to increase the program's effectiveness; and

.. When developing architectural plans for constructing or remodeling a hospital or a unit of a hospital in which patient handling and movement occurs, consider the feasibility of incorporating patient handling equipment or the physical space and construction design needed to incorporate that equipment at a later date.

. By January 30, 2010, each hospital must complete, at a minimum, acquisition of their choice of: (a) One readily available lift per acute care unit on the same floor unless the safe patient handling committee determines a lift is unnecessary in the unit; (b) one lift for every ten acute care available inpatient beds; or (c) equipment for use by lift teams. Hospitals must train staff on policies, equipment, and devices at least annually.

. Nothing in this section precludes lift team members from performing other duties as assigned during their shift.

. A hospital shall develop procedures for hospital employees to refuse to perform or be involved in patient handling or movement that the hospital employee believes in good faith will expose a patient or a hospital employee to an unacceptable risk of injury. A hospital employee who in good faith follows the procedure developed by the hospital in accordance with this subsection shall not be the subject of disciplinary action by the hospital for the refusal to perform or be involved in the patient handling or movement.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1672-S.SL.pdf?cite=2006%20c%20165%20§%202[2006 c 165 § 2]; ]

== 70.41.400 - Patient billing—Written statement describing who may be billing the patient required—Contact phone numbers—Exceptions.
. Prior to or upon discharge, a hospital must furnish each patient receiving inpatient services a written statement providing a list of physician groups and other professional partners that commonly provide care for patients at the hospital and from whom the patient may receive a bill, along with contact phone numbers for those groups. The statement must prominently display a phone number that a patient can call for assistance if the patient has any questions about any of the bills they receive after discharge that relate to their hospital stay.

. This section does not apply to any hospital owned or operated by a health maintenance organization under chapter 48.46 RCW when providing prepaid health care services to enrollees of the health maintenance organization or any of its wholly owned subsidiary carriers.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6189-S.SL.pdf?cite=2006%20c%2060%20§%202[2006 c 60 § 2]; ]

== 70.41.410 - Nurse staffing committee—Definitions.
The definitions in this section apply throughout this section and RCW 70.41.420 unless the context clearly requires otherwise.

. "Hospital" has the same meaning as defined in RCW 70.41.020, and also includes state hospitals as defined in RCW 72.23.010.

. "Intensity" means the level of patient need for nursing care, as determined by the nursing assessment.

. "Nursing personnel" means registered nurses, licensed practical nurses, and unlicensed assistive nursing personnel providing direct patient care.

. "Nurse staffing committee" means the committee established by a hospital under RCW 70.41.420.

. "Patient care unit" means any unit or area of the hospital that provides patient care by registered nurses.

. "Skill mix" means the number and relative percentages of registered nurses, licensed practical nurses, and unlicensed assistive personnel among the total number of nursing personnel.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3123-S2.SL.pdf?cite=2008%20c%2047%20§%202[2008 c 47 § 2]; ]

== 70.41.420 - Nurse staffing committee. (Effective until June 1, 2023.)
. By September 1, 2008, each hospital shall establish a nurse staffing committee, either by creating a new committee or assigning the functions of a nurse staffing committee to an existing committee. At least one-half of the members of the nurse staffing committee shall be registered nurses currently providing direct patient care and up to one-half of the members shall be determined by the hospital administration. The selection of the registered nurses providing direct patient care shall be according to the collective bargaining agreement if there is one in effect at the hospital. If there is no applicable collective bargaining agreement, the members of the nurse staffing committee who are registered nurses providing direct patient care shall be selected by their peers.

. Participation in the nurse staffing committee by a hospital employee shall be on scheduled work time and compensated at the appropriate rate of pay. Nurse staffing committee members shall be relieved of all other work duties during meetings of the committee.

. Primary responsibilities of the nurse staffing committee shall include:

.. Development and oversight of an annual patient care unit and shift-based nurse staffing plan, based on the needs of patients, to be used as the primary component of the staffing budget. Factors to be considered in the development of the plan should include, but are not limited to:

... Census, including total numbers of patients on the unit on each shift and activity such as patient discharges, admissions, and transfers;

... Level of intensity of all patients and nature of the care to be delivered on each shift;

... Skill mix;

... Level of experience and specialty certification or training of nursing personnel providing care;

.. The need for specialized or intensive equipment;

.. The architecture and geography of the patient care unit, including but not limited to placement of patient rooms, treatment areas, nursing stations, medication preparation areas, and equipment;

.. Staffing guidelines adopted or published by national nursing professional associations, specialty nursing organizations, and other health professional organizations;

.. Availability of other personnel supporting nursing services on the unit; and

... Strategies to enable registered nurses to take meal and rest breaks as required by law or the terms of an applicable collective bargaining agreement, if any, between the hospital and a representative of the nursing staff;

.. Semiannual review of the staffing plan against patient need and known evidence-based staffing information, including the nursing sensitive quality indicators collected by the hospital;

.. Review, assessment, and response to staffing variations or concerns presented to the committee.

. In addition to the factors listed in subsection (3)(a) of this section, hospital finances and resources must be taken into account in the development of the nurse staffing plan.

. The staffing plan must not diminish other standards contained in state or federal law and rules, or the terms of an applicable collective bargaining agreement, if any, between the hospital and a representative of the nursing staff.

. The committee will produce the hospital's annual nurse staffing plan. If this staffing plan is not adopted by the hospital, the chief executive officer shall provide a written explanation of the reasons why the plan was not adopted to the committee. The chief executive officer must then either: (a) Identify those elements of the proposed plan being changed prior to adoption of the plan by the hospital or (b) prepare an alternate annual staffing plan that must be adopted by the hospital. Beginning January 1, 2019, each hospital shall submit its staffing plan to the department and thereafter on an annual basis and at any time in between that the plan is updated.

. Beginning January 1, 2019, each hospital shall implement the staffing plan and assign nursing personnel to each patient care unit in accordance with the plan.

.. A registered nurse may report to the staffing committee any variations where the nurse personnel assignment in a patient care unit is not in accordance with the adopted staffing plan and may make a complaint to the committee based on the variations.

.. Shift-to-shift adjustments in staffing levels required by the plan may be made by the appropriate hospital personnel overseeing patient care operations. If a registered nurse on a patient care unit objects to a shift-to-shift adjustment, the registered nurse may submit the complaint to the staffing committee.

.. Staffing committees shall develop a process to examine and respond to data submitted under (a) and (b) of this subsection, including the ability to determine if a specific complaint is resolved or dismissing a complaint based on unsubstantiated data.

. Each hospital shall post, in a public area on each patient care unit, the nurse staffing plan and the nurse staffing schedule for that shift on that unit, as well as the relevant clinical staffing for that shift. The staffing plan and current staffing levels must also be made available to patients and visitors upon request.

. A hospital may not retaliate against or engage in any form of intimidation of:

.. An employee for performing any duties or responsibilities in connection with the nurse staffing committee; or

.. An employee, patient, or other individual who notifies the nurse staffing committee or the hospital administration of his or her concerns on nurse staffing.

. This section is not intended to create unreasonable burdens on critical access hospitals under 42 U.S.C. Sec. 1395i-4. Critical access hospitals may develop flexible approaches to accomplish the requirements of this section that may include but are not limited to having nurse staffing committees work by telephone or email.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1714-S.SL.pdf?cite=2017%20c%20249%20§%202[2017 c 249 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3123-S2.SL.pdf?cite=2008%20c%2047%20§%203[2008 c 47 § 3]; ]

== 70.41.425 - Nurse staffing—Department investigations. (Expires June 1, 2023.)
. [Empty]
.. The department shall investigate a complaint submitted under this section for violation of RCW 70.41.420 following receipt of a complaint with documented evidence of failure to:

... Form or establish a staffing committee;

... Conduct a semiannual review of a nurse staffing plan;

... Submit a nurse staffing plan on an annual basis and any updates; or

...(A) Follow the nursing personnel assignments in a patient care unit in violation of RCW 70.41.420(7)(a) or shift-to-shift adjustments in staffing levels in violation of RCW 70.41.420(7)(b).

(B) The department may only investigate a complaint under this subsection (1)(a)(iv) after making an assessment that the submitted evidence indicates a continuing pattern of unresolved violations of RCW 70.41.420(7) (a) or (b), that were submitted to the nurse staffing committee excluding complaints determined by the nurse staffing committee to be resolved or dismissed. The submitted evidence must include the aggregate data contained in the complaints submitted to the hospital's nurse staffing committee that indicate a continuing pattern of unresolved violations for a minimum sixty-day continuous period leading up to receipt of the complaint by the department.

(C) The department may not investigate a complaint under this subsection (1)(a)(iv) in the event of unforeseeable emergency circumstances or if the hospital, after consultation with the nurse staffing committee, documents it has made reasonable efforts to obtain staffing to meet required assignments but has been unable to do so.

.. After an investigation conducted under (a) of this subsection, if the department determines that there has been a violation, the department shall require the hospital to submit a corrective plan of action within forty-five days of the presentation of findings from the department to the hospital.

. In the event that a hospital fails to submit or submits but fails to follow such a corrective plan of action in response to a violation or violations found by the department based on a complaint filed pursuant to subsection (1) of this section, the department may impose, for all violations asserted against a hospital at any time, a civil penalty of one hundred dollars per day until the hospital submits or begins to follow a corrective plan of action or takes other action agreed to by the department.

. The department shall maintain for public inspection records of any civil penalties, administrative actions, or license suspensions or revocations imposed on hospitals under this section.

. For purposes of this section, "unforeseeable emergency circumstance" means:

.. Any unforeseen national, state, or municipal emergency;

.. When a hospital disaster plan is activated;

.. Any unforeseen disaster or other catastrophic event that substantially affects or increases the need for health care services; or

.. When a hospital is diverting patients to another hospital or hospitals for treatment or the hospital is receiving patients who are from another hospital or hospitals.

. Nothing in this section shall be construed to preclude the ability to otherwise submit a complaint to the department for failure to follow RCW 70.41.420.

. The department shall submit a report to the legislature on December 31, 2020. This report shall include the number of complaints submitted to the department under this section, the disposition of these complaints, the number of investigations conducted, the associated costs for complaint investigations, and recommendations for any needed statutory changes. The department shall also project, based on experience, the impact, if any, on hospital licensing fees over the next four years. Prior to the submission of the report, the secretary shall convene a stakeholder group consisting of the Washington state hospital association, the Washington state nurses association, service employees international union healthcare 1199NW, and united food and commercial workers 21. The stakeholder group shall review the report prior to its submission to review findings and jointly develop any legislative recommendations to be included in the report.

. No fees shall be increased to implement chapter 249, Laws of 2017 prior to July 1, 2021.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1714-S.SL.pdf?cite=2017%20c%20249%20§%203[2017 c 249 § 3]; ]

== 70.41.430 - Licensed hospitals must adopt a policy regarding methicillin-resistant staphylococcus aureus (MRSA)—Elements.
. Each hospital licensed under this chapter shall, by January 1, 2010, adopt a policy regarding methicillin-resistant staphylococcus aureus. The policy shall, at a minimum, contain the following elements:

.. A requirement to test any patient for methicillin-resistant staphylococcus aureus who is a member of a patient population identified as appropriate to test based on the hospital's risk assessment for methicillin-resistant staphylococcus aureus;

.. A requirement that a patient in the hospital's adult or pediatric, but not neonatal, intensive care unit be tested for methicillin-resistant staphylococcus aureus within twenty-four hours of admission unless the patient has been previously tested during that hospital stay or has a known history of methicillin-resistant staphylococcus aureus;

.. Appropriate procedures to help prevent patients who test positive for methicillin-resistant staphylococcus aureus from transmitting to other patients. For purposes of this subsection, "appropriate procedures" include, but are not limited to, isolation or cohorting of patients colonized or infected with methicillin-resistant staphylococcus aureus. In a hospital where patients, whose methicillin-resistant staphylococcus aureus status is either unknown or uncolonized, may be roomed with colonized or infected patients, patients must be notified they may be roomed with patients who have tested positive for methicillin-resistant staphylococcus aureus; and

.. A requirement that every patient who has a methicillin-resistant staphylococcus aureus infection receive oral and written instructions regarding aftercare and precautions to prevent the spread of the infection to others.

. A hospital that has identified a hospitalized patient who has a diagnosis of methicillin-resistant staphylococcus aureus shall report the infection to the department using the department's comprehensive hospital abstract reporting system. When making its report, the hospital shall use codes used by the United States centers for medicare and medicaid services, when available.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1123-S.SL.pdf?cite=2009%20c%20244%20§%201[2009 c 244 § 1]; ]

== 70.41.440 - Duty to report violent injuries—Preservation of evidence—Immunity—Privilege.
. A hospital shall report to a local law enforcement authority as soon as reasonably possible, taking into consideration a patient's emergency care needs, when the hospital provides treatment for a bullet wound, gunshot wound, or stab wound to a patient. A hospital shall establish a written policy to identify the person or persons responsible for making the report.

. The report required under subsection (1) of this section must include the following information, if known:

.. The name, residence, sex, and age of the patient;

.. Whether the patient has received a bullet wound, gunshot wound, or stab wound; and

.. The name of the health care provider providing treatment for the bullet wound, gunshot wound, or stab wound.

. Nothing in this section shall limit a person's duty to report under RCW 26.44.030 or 74.34.035.

. Any bullets, clothing, or other foreign objects that are removed from a patient for whom a hospital is required to make a report pursuant to subsection (1) of this section shall be preserved and kept in custody in such a way that the identity and integrity thereof are reasonably maintained until the bullets, clothing, or other foreign objects are taken into possession by a law enforcement authority or the hospital's normal period for retention of such items expires, whichever occurs first.

. Any hospital or person who in good faith, and without gross negligence or willful or wanton misconduct, makes a report required by this section, cooperates in an investigation or criminal or judicial proceeding related to such report, or maintains bullets, clothing, or other foreign objects, or provides such items to a law enforcement authority as described in subsection (4) of this section, is immune from civil or criminal liability or professional licensure action arising out of or related to the report and its contents or the absence of information in the report, cooperation in an investigation or criminal or judicial proceeding, and the maintenance or provision to a law enforcement authority of bullets, clothing, or other foreign objects under subsection (4) of this section.

. The physician-patient privilege described in RCW 5.60.060(4), the registered nurse-patient privilege described in RCW 5.62.020, and any other health care provider-patient privilege created or recognized by law are not a basis for excluding as evidence in any criminal proceeding any report, or information contained in a report made under this section.

. All reporting, preservation, or other requirements of this section are secondary to patient care needs and may be delayed or compromised without penalty to the hospital or person required to fulfill the requirements of this section.

. If the patient states his or her injury is the result of domestic violence, the hospital shall follow its established processes to inform the patient of resources to assure the safety of the patient and his or her family.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5305.SL.pdf?cite=2013%20c%20252%20§%201[2013 c 252 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5056-S.SL.pdf?cite=2009%20c%20359%20§%202[2009 c 359 § 2]; ]

== 70.41.450 - Estimated charges of hospital services—Notice.
Hospitals licensed under this chapter shall post a sign in patient registration areas containing at least the following language: "Information about the estimated charges of your hospital services is available upon request. Please do not hesitate to ask for information."

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1869-S.SL.pdf?cite=2009%20c%20529%20§%202[2009 c 529 § 2]; ]

== 70.41.460 - Contract with department of corrections.
As a condition of licensure, a hospital must contract with the department of corrections pursuant to RCW 72.10.030.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2803.SL.pdf?cite=2012%20c%20237%20§%203[2012 c 237 § 3]; ]

== 70.41.470 - Information to be made widely available by certain hospitals—Community health needs assessment—Description of community served—Community benefit implementation strategy.
. As of January 1, 2013, each hospital that is recognized by the internal revenue service as a 501(c)(3) nonprofit entity must make its federally required community health needs assessment widely available to the public within fifteen days of submission to the internal revenue service. Following completion of the initial community health needs assessment, each hospital in accordance with the internal revenue service, shall complete and make widely available to the public an assessment once every three years.

. Unless contained in the community health needs assessment under subsection (1) of this section, a hospital subject to the requirements under subsection (1) of this section shall make public a description of the community served by the hospital, including both a geographic description and a description of the general population served by the hospital; and demographic information such as leading causes of death, levels of chronic illness, and descriptions of the medically underserved, low-income, and minority, or chronically ill populations in the community.

. [Empty]
.. Each hospital subject to the requirements of subsection (1) of this section shall make widely available to the public a community benefit implementation strategy within one year of completing its community health needs assessment. In developing the implementation strategy, hospitals shall consult with community-based organizations and stakeholders, and local public health jurisdictions, as well as any additional consultations the hospital decides to undertake. Unless contained in the implementation strategy under this subsection (3)(a), the hospital must provide a brief explanation for not accepting recommendations for community benefit proposals identified in the assessment through the stakeholder consultation process, such as excessive expense to implement or infeasibility of implementation of the proposal.

.. Implementation strategies must be evidence-based, when available; or development and implementation of innovative programs and practices should be supported by evaluation measures.

. For the purposes of this section, the term "widely available to the public" has the same meaning as in the internal revenue service guidelines.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2341-S.SL.pdf?cite=2012%20c%20103%20§%201[2012 c 103 § 1]; ]

== 70.41.480 - Findings—Intent—Authority to prescribe prepackaged emergency medications—Definitions.
. The legislature finds that high quality, safe, and compassionate health care services for patients of Washington state must be available at all times. The legislature further finds that there is a need for patients being released from hospital emergency departments to maintain access to emergency medications when community or hospital pharmacy services are not available, including medication for opioid overdose reversal and for the treatment for opioid use disorder as appropriate. It is the intent of the legislature to accomplish this objective by allowing practitioners with prescriptive authority to prescribe limited amounts of prepackaged emergency medications to patients being discharged from hospital emergency departments when access to community or outpatient hospital pharmacy services is not otherwise available.

. A hospital may allow a practitioner to prescribe prepackaged emergency medications and allow a practitioner or a registered nurse licensed under chapter 18.79 RCW to distribute prepackaged emergency medications to patients being discharged from a hospital emergency department in the following circumstances:

.. During times when community or outpatient hospital pharmacy services are not available within fifteen miles by road;

.. When, in the judgment of the practitioner and consistent with hospital policies and procedures, a patient has no reasonable ability to reach the local community or outpatient pharmacy; or

.. When, in the judgment of the practitioner and consistent with hospital policies and procedures, a patient is at risk of opioid overdose and the prepackaged emergency medication being distributed is an opioid overdose reversal medication. The labeling requirements of RCW 69.41.050 and 18.64.246 do not apply to opioid overdose reversal medications dispensed, distributed, or delivered pursuant to a prescription, collaborative drug therapy agreement, standing order, or protocol issued in accordance with this section. The individual or entity that dispenses, distributes, or delivers an opioid overdose reversal medication as authorized by this section must ensure that directions for use are provided.

. A hospital may only allow this practice if: The director of the hospital pharmacy, in collaboration with appropriate hospital medical staff, develops policies and procedures regarding the following:

.. Development of a list, preapproved by the pharmacy director, of the types of emergency medications to be prepackaged and distributed;

.. Assurances that emergency medications to be prepackaged pursuant to this section are prepared by a pharmacist or under the supervision of a pharmacist licensed under chapter 18.64 RCW;

.. Development of specific criteria under which emergency prepackaged medications may be prescribed and distributed consistent with the limitations of this section;

.. Assurances that any practitioner authorized to prescribe prepackaged emergency medication or any nurse authorized to distribute prepackaged emergency medication is trained on the types of medications available and the circumstances under which they may be distributed;

.. Procedures to require practitioners intending to prescribe prepackaged emergency medications pursuant to this section to maintain a valid prescription either in writing or electronically in the patient's records prior to a medication being distributed to a patient;

.. Establishment of a limit of no more than a forty-eight hour supply of emergency medication as the maximum to be dispensed to a patient, except when community or hospital pharmacy services will not be available within forty-eight hours. In no case may the policy allow a supply exceeding ninety-six hours be dispensed;

.. Assurances that prepackaged emergency medications will be kept in a secure location in or near the emergency department in such a manner as to preclude the necessity for entry into the pharmacy; and

.. Assurances that nurses or practitioners will distribute prepackaged emergency medications to patients only after a practitioner has counseled the patient on the medication.

. The delivery of a single dose of medication for immediate administration to the patient is not subject to the requirements of this section.

. Nothing in this section restricts the authority of a practitioner in a hospital emergency department to distribute opioid overdose reversal medication under RCW 69.41.095.

. For purposes of this section:

.. "Emergency medication" means any medication commonly prescribed to emergency department patients, including those drugs, substances or immediate precursors listed in schedules II through V of the uniform controlled substances act, chapter 69.50 RCW, as now or hereafter amended.

.. "Distribute" means the delivery of a drug or device other than by administering or dispensing.

.. "Practitioner" means any person duly authorized by law or rule in the state of Washington to prescribe drugs as defined in RCW 18.64.011(29).

.. "Nurse" means a registered nurse as defined in RCW 18.79.020.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5380-S.SL.pdf?cite=2019%20c%20314%20§%2018[2019 c 314 § 18]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5460-S.SL.pdf?cite=2015%20c%20234%20§%201[2015 c 234 § 1]; ]

== 70.41.490 - Authorization for certain transfers of drugs between hospitals and their affiliated companies.
. The legislature recognizes that in order for hospitals to ensure drugs are accessible to patients and the public to meet hospital and community health care needs, certain transfers of drugs must be authorized between hospitals and their affiliated or related companies under common ownership and control of the corporate entity and for emergency medical reasons.

. A licensed hospital pharmacy is permitted, without a wholesaler license, to:

.. Engage in intracompany sales, being defined as any transaction or transfer between any division, subsidiary, parent company, affiliated company, or related company under common ownership and control of the corporate entity, unless the transfer occurs between a wholesale distributor and a health care entity or practitioner; and

.. Sell, purchase, or trade a drug or offer to sell, purchase, or trade a drug for emergency medical reasons. For the purposes of this subsection, "emergency medical reasons" includes transfers of prescription drugs to alleviate a temporary shortage, except that the gross dollar value of the transfers may not exceed five percent of the total prescription drug sale revenue of either the transferor or transferee pharmacy during any twelve consecutive month period.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5460-S.SL.pdf?cite=2015%20c%20234%20§%202[2015 c 234 § 2]; ]

== 70.41.500 - Down syndrome—Parent information.
A hospital that provides a parent with a positive prenatal or postnatal diagnosis of Down syndrome shall provide the parent with the information prepared by the department under RCW 43.70.738 at the time the hospital provides the parent with the Down syndrome diagnosis.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2403.SL.pdf?cite=2016%20c%2070%20§%209[2016 c 70 § 9]; ]

== 70.41.510 - Pattern of balance billing protection act violations by hospital—Fines and disciplinary action.
If the insurance commissioner reports to the department that he or she has cause to believe that a hospital has engaged in a pattern of violations of RCW 48.49.020 or 48.49.030, and the report is substantiated after investigation, the department may levy a fine upon the hospital in an amount not to exceed one thousand dollars per violation and take other formal or informal disciplinary action as permitted under the authority of the department.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1065-S2.SL.pdf?cite=2019%20c%20427%20§%2018[2019 c 427 § 18]; ]

== 70.41.520 - Access to care policies for admission, nondiscrimination, and reproductive health care—Requirement to submit, post on web site, and use department-created form.
. By September 1, 2019, every hospital must submit to the department its policies related to access to care regarding:

.. Admission;

.. Nondiscrimination; and

.. Reproductive health care.

. The department shall post a copy of the policies received under subsection (1) of this section on its web site.

. If a hospital makes changes to any of the policies listed under subsection (1) of this section, it must submit a copy of the changed policy to the department within thirty days after the hospital approves the changes.

. A hospital must post a copy of the policies provided to the department under subsection (1) of this section and the form required under subsection (5) of this section to the hospital's own web site in a location where the policies are readily accessible to the public without a required login or other restriction.

. By September 1, 2019, the department shall, in consultation with stakeholders including a hospital association and patient advocacy groups, develop a simple and clear form to be submitted by hospitals along with the policies required in subsection (1) of this section. The form must provide the public with specific information about which reproductive health care services are and are not generally available at each hospital. The form must include contact information for the hospital in case patients have specific questions about services available at the hospital.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5602-S2.SL.pdf?cite=2019%20c%20399%20§%204[2019 c 399 § 4]; ]

== 70.41.900 - Severability—1955 c 267.
If any part, or parts, of this chapter shall be held unconstitutional, the remaining provisions shall be given full force and effect, as completely as if the part held unconstitutional had not been included herein, if any such remaining part can then be administered for the purpose of establishing and maintaining standards for hospitals.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c267.pdf?cite=1955%20c%20267%20§%2021[1955 c 267 § 21]; ]

