= 70.50 - State otologist.
:toc:

== 70.50.010 - Appointment—Salary.
The secretary of health shall appoint and employ an otologist skilled in diagnosis of diseases of the ear and defects in hearing, especially for school children with an impaired sense of hearing, and shall fix the salary of such otologist in a sum not exceeding the salary of the secretary.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20340[1991 c 3 § 340]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%20108[1979 c 141 § 108]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c23.pdf?cite=1945%20c%2023%20§%201[1945 c 23 § 1]; Rem. Supp. 1945 § 6010-10; ]

== 70.50.020 - Duties.
The otologist shall cooperate with the state department of public instruction, and with the state, county, and city health officers, seeking for the children in the schools who are hard of hearing, or have an impaired sense of hearing, and making otological inspections and examinations of children referred to him or her by such departments and officers. Where necessary or proper, he or she shall make recommendations to parents or guardians of such children, and urge them to submit such recommendations to physicians to be selected by such parents or guardians.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20381[2012 c 117 § 381]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c23.pdf?cite=1945%20c%2023%20§%202[1945 c 23 § 2]; Rem. Supp. 1945 § 6010-11; ]

