= 70.48 - City and county jails act.
:toc:

== 70.48.020 - Definitions.
As used in this chapter the words and phrases in this section shall have the meanings indicated unless the context clearly requires otherwise.

. "Administration" means the direct application of a drug whether by ingestion or inhalation, to the body of an inmate by a practitioner or nonpractitioner jail personnel.

. "Correctional facility" means a facility operated by a governing unit primarily designed, staffed, and used for the housing of adult persons serving terms not exceeding one year for the purposes of punishment, correction, and rehabilitation following conviction of a criminal offense.

. "Deliver" or "delivery" means the actual, constructive, or attempted transfer from one person to another of medication whether or not there is an agency relationship.

. "Detention facility" means a facility operated by a governing unit primarily designed, staffed, and used for the temporary housing of adult persons charged with a criminal offense prior to trial or sentencing and for the housing of adult persons for purposes of punishment and correction after sentencing or persons serving terms not to exceed ninety days.

. "Drug" and "legend drug" have the same meanings as provided in RCW 69.41.010.

. "Governing unit" means the city and/or county or any combinations of cities and/or counties responsible for the operation, supervision, and maintenance of a jail.

. "Health care" means preventive, diagnostic, and rehabilitative services provided by licensed health care professionals and/or facilities; such care to include providing prescription drugs where indicated.

. "Holding facility" means a facility operated by a governing unit primarily designed, staffed, and used for the temporary housing of adult persons charged with a criminal offense prior to trial or sentencing and for the temporary housing of such persons during or after trial and/or sentencing, but in no instance shall the housing exceed thirty days.

. "Jail" means any holding, detention, special detention, or correctional facility as defined in this section.

. "Labor" means the period of time before a birth during which contractions are of sufficient frequency, intensity, and duration to bring about effacement and progressive dilation of the cervix.

. "Major urban" means a county or combination of counties which has a city having a population greater than twenty-six thousand based on the 1978 projections of the office of financial management.

. "Medication" means a drug, legend drug, or controlled substance requiring a prescription or an over-the-counter or nonprescription drug.

. "Medication assistance" means assistance rendered by nonpractitioner jail personnel to an inmate residing in a jail to facilitate the individual's self-administration of a legend drug or controlled substance or nonprescription medication. "Medication assistance" includes reminding or coaching the individual, handing the medication container to the individual, opening the individual's medication container, using an enabler, or placing the medication in the individual's hand.

. "Medium urban" means a county or combination of counties which has a city having a population equal to or greater than ten thousand but less than twenty-six thousand based on the 1978 projections of the office of financial management.

. "Nonpractitioner jail personnel" means appropriately trained staff who are authorized to manage, deliver, or administer prescription and nonprescription medication under RCW 70.48.490.

. "Office" means the office of financial management.

. "Physical restraint" means the use of any bodily force or physical intervention to control an offender or limit an offender's freedom of movement in a way that does not involve a mechanical restraint. Physical restraint does not include momentary periods of minimal physical restriction by direct person-to-person contact, without the aid of mechanical restraint, accomplished with limited force and designed to:

.. Prevent an offender from completing an act that would result in potential bodily harm to self or others or damage property;

.. Remove a disruptive offender who is unwilling to leave the area voluntarily; or

.. Guide an offender from one location to another.

. "Postpartum recovery" means (a) the entire period a woman or youth is in the hospital, birthing center, or clinic after giving birth and (b) an additional time period, if any, a treating physician determines is necessary for healing after the woman or youth leaves the hospital, birthing center, or clinic.

. "Practitioner" has the same meaning as provided in RCW 69.41.010.

. "Restraints" means anything used to control the movement of a person's body or limbs and includes:

.. Physical restraint; or

.. Mechanical device including but not limited to: Metal handcuffs, plastic ties, ankle restraints, leather cuffs, other hospital-type restraints, tasers, or batons.

. "Rural" means a county or combination of counties which has a city having a population less than ten thousand based on the 1978 projections of the office of financial management.

. "Special detention facility" means a minimum security facility operated by a governing unit primarily designed, staffed, and used for the housing of special populations of sentenced persons who do not require the level of security normally provided in detention and correctional facilities including, but not necessarily limited to, persons convicted of offenses under RCW 46.61.502 or 46.61.504.

. "Transportation" means the conveying, by any means, of an incarcerated pregnant woman or youth from the correctional facility or any facility covered by this chapter to another location from the moment she leaves the correctional facility or any facility covered by this chapter to the time of arrival at the other location, and includes the escorting of the pregnant incarcerated woman or youth from the correctional facility or facility covered by this chapter to a transport vehicle and from the vehicle to the other location.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2747-S.SL.pdf?cite=2010%20c%20181%20§%204[2010 c 181 § 4]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5252-S.SL.pdf?cite=2009%20c%20411%20§%203[2009 c 411 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c462.pdf?cite=1987%20c%20462%20§%206[1987 c 462 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c118.pdf?cite=1986%20c%20118%20§%201[1986 c 118 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c165.pdf?cite=1983%20c%20165%20§%2034[1983 c 165 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c136.pdf?cite=1981%20c%20136%20§%2025[1981 c 136 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c232.pdf?cite=1979%20ex.s.%20c%20232%20§%2011[1979 ex.s. c 232 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c316.pdf?cite=1977%20ex.s.%20c%20316%20§%202[1977 ex.s. c 316 § 2]; ]

== 70.48.071 - Standards for operation—Adoption by units of local government.
All units of local government that own or operate adult correctional facilities shall, individually or collectively, adopt standards for the operation of those facilities no later than January 1, 1988. Cities and towns shall adopt the standards after considering guidelines established collectively by the cities and towns of the state; counties shall adopt the standards after considering guidelines established collectively by the counties of the state. These standards shall be the minimums necessary to meet federal and state constitutional requirements relating to health, safety, and welfare of inmates and staff, and specific state and federal statutory requirements, and to provide for the public's health, safety, and welfare. Local correctional facilities shall be operated in accordance with these standards.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c462.pdf?cite=1987%20c%20462%20§%2017[1987 c 462 § 17]; ]

== 70.48.090 - Interlocal contracts for jail services—Neighboring states—Responsibility for operation of jail—City or county departments of corrections authorized.
. Contracts for jail services may be made between a county and a city, and among counties and cities. The contracts shall: Be in writing, give one governing unit the responsibility for the operation of the jails, specify the responsibilities of each governing unit involved, and include the applicable charges for custody of the prisoners as well as the basis for adjustments in the charges. The contracts may be terminated only by ninety days written notice to the governing units involved and to the office. The notice shall state the grounds for termination and the specific plans for accommodating the affected jail population.

. A city or county may contract for jail services with an adjacent county, or city in an adjacent county, in a neighboring state. A person convicted in the courts of this state and sentenced to a term of confinement in a city or county jail may be transported to a jail in the adjacent county to be confined until: (a) The term of confinement is completed; or (b) that person is returned to be confined in a city or county jail in this state.

. The contract authorized in subsection (1) of this section shall be for a minimum term of ten years when state funds are provided to construct or remodel a jail in one governing unit that will be used to house prisoners of other governing units. The contract may not be terminated prior to the end of the term without the office's approval. If the contract is terminated, or upon the expiration and nonrenewal of the contract, the governing unit whose jail facility was built or remodeled to hold the prisoners of other governing units shall pay to the state treasurer the amount set by the *corrections standards board or office when it authorized disbursal of state funds for the remodeling or construction under **RCW 70.48.120. This amount shall be deposited in the local jail improvement and construction account and shall fairly represent the construction costs incurred in order to house prisoners from other governing units. The office may pay the funds to the governing units which had previously contracted for jail services under rules which the office may adopt. The acceptance of state funds for constructing or remodeling consolidated jail facilities constitutes agreement to the proportionate amounts set by the office. Notice of the proportionate amounts shall be given to all governing units involved. This subsection shall not apply to interlocal agreements under RCW 39.34.180(6).

. A city or county primarily responsible for the operation of a jail or jails may create a department of corrections to be in charge of such jail and of all persons confined therein by law, subject to the authority of the governing unit. If such department is created, it shall have charge of jails and persons confined therein. If no such department of corrections is created, the chief law enforcement officer of the city or county primarily responsible for the operation of said jail shall have charge of the jail and of all persons confined therein.

. A city or county may enter into an interlocal agreement for the sharing of costs for sanctions imposed by a jurisdiction hosting probation supervision services pursuant to an interlocal agreement under RCW 39.34.180(6).

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1294-S.SL.pdf?cite=2021%20c%2041%20§%203[2021 c 41 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5625-S.SL.pdf?cite=2007%20c%2013%20§%201[2007 c 13 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2541-S.SL.pdf?cite=2002%20c%20125%20§%201[2002 c 125 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c462.pdf?cite=1987%20c%20462%20§%207[1987 c 462 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c118.pdf?cite=1986%20c%20118%20§%206[1986 c 118 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c232.pdf?cite=1979%20ex.s.%20c%20232%20§%2015[1979 ex.s. c 232 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c316.pdf?cite=1977%20ex.s.%20c%20316%20§%209[1977 ex.s. c 316 § 9]; ]

== 70.48.095 - Regional jails.
. Regional jails may be created and operated between two or more local governments, or one or more local governments and the state, and may be governed by representatives from multiple jurisdictions.

. A jurisdiction that confines persons prior to conviction in a regional jail in another county is responsible for providing private telephone, videoconferencing, or in-person contact between the defendant and his or her public defense counsel.

. The creation and operation of any regional jail must comply with the interlocal cooperation act described in chapter 39.34 RCW.

. Nothing in this section prevents counties and cities from contracting for jail services as described in RCW 70.48.090.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2407.SL.pdf?cite=2002%20c%20124%20§%201[2002 c 124 § 1]; ]

== 70.48.100 - Jail register, open to the public—Records confidential—Exception.
. A department of corrections or chief law enforcement officer responsible for the operation of a jail shall maintain a jail register, open to the public, into which shall be entered in a timely basis:

.. The name of each person confined in the jail with the hour, date and cause of the confinement; and

.. The hour, date and manner of each person's discharge.

. Except as provided in subsections (3) and (4) of this section, the records of a person confined in jail shall be held in confidence and shall be made available only to criminal justice agencies as defined in RCW 43.43.705; or

.. For use in inspections made pursuant to *RCW 70.48.070;

.. In jail certification proceedings;

.. For use in court proceedings upon the written order of the court in which the proceedings are conducted;

.. To the Washington association of sheriffs and police chiefs;

.. To the Washington institute for public policy, research and data analysis division of the department of social and health services, higher education institutions of Washington state, Washington state health care authority, state auditor's office, caseload forecast council, office of financial management, or the successor entities of these organizations, for the purpose of research in the public interest. Data disclosed for research purposes must comply with relevant state and federal statutes;

.. To federal, state, or local agencies to determine eligibility for services such as medical, mental health, chemical dependency treatment, or veterans' services, and to allow for the provision of treatment to inmates during their stay or after release. Records disclosed for eligibility determination or treatment services must be held in confidence by the receiving agency, and the receiving agency must comply with all relevant state and federal statutes regarding the privacy of the disclosed records; or

.. Upon the written permission of the person.

. The records of a person confined in jail may be made available to a managed health care system, including managed care organizations and behavioral health administrative services organizations as defined in RCW 71.24.025, for the purpose of care coordination activities. The receiving system or organization must hold records in confidence and comply with all relevant state and federal statutes regarding privacy of disclosed records.

. [Empty]
.. Law enforcement may use booking photographs of a person arrested or confined in a local or state penal institution to assist them in conducting investigations of crimes.

.. Photographs and information concerning a person convicted of a sex offense as defined in RCW 9.94A.030 may be disseminated as provided in RCW 4.24.550, 9A.44.130, 9A.44.140, 10.01.200, 43.43.540, 43.43.745, 46.20.187, 70.48.470, 72.09.330, and **section 401, chapter 3, Laws of 1990.

. Any jail that provides inmate records in accordance with subsection (2) or (3) of this section is not responsible for any unlawful secondary dissemination of the provided inmate records.

. For purposes of this section:

.. "Managed care organization" and "behavioral health administrative services organization" have the same meaning as in RCW 71.24.025.

.. "Managed health care system" has the same meaning as in RCW 74.09.522.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2545.SL.pdf?cite=2020%20c%20282%20§%201[2020 c 282 § 1]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6430-S.SL.pdf?cite=2016%20c%20154%20§%206[2016 c 154 § 6]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6312-S2.SL.pdf?cite=2014%20c%20225%20§%20105[2014 c 225 § 105]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%20130[1990 c 3 § 130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c316.pdf?cite=1977%20ex.s.%20c%20316%20§%2010[1977 ex.s. c 316 § 10]; ]

== 70.48.130 - Emergency or necessary medical and health care for confined persons—Reimbursement procedures—Conditions—Limitations.
. It is the intent of the legislature that all jail inmates receive appropriate and cost-effective emergency and necessary medical care. Governing units, the health care authority, and medical care providers shall cooperate to achieve the best rates consistent with adequate care.

. Payment for emergency or necessary health care shall be by the governing unit, except that the health care authority shall directly reimburse the provider pursuant to chapter 74.09 RCW, in accordance with the rates and benefits established by the authority, if the confined person is eligible under the authority's medical care programs as authorized under chapter 74.09 RCW. After payment by the authority, the financial responsibility for any remaining balance, including unpaid client liabilities that are a condition of eligibility or participation under chapter 74.09 RCW, shall be borne by the medical care provider and the governing unit as may be mutually agreed upon between the medical care provider and the governing unit. In the absence of mutual agreement between the medical care provider and the governing unit, the financial responsibility for any remaining balance shall be borne equally between the medical care provider and the governing unit. Total payments from all sources to providers for care rendered to confined persons eligible under chapter 74.09 RCW shall not exceed the amounts that would be paid by the authority for similar services provided under Title XIX medicaid, unless additional resources are obtained from the confined person.

. For inpatient, outpatient, and ancillary services for confined persons that are not paid by the medicaid program pursuant to subsection (2) of this section, unless other rates are agreed to by the governing unit and the hospital, providers of hospital services that are hospitals licensed under chapter 70.41 RCW must accept as payment in full by the governing units the applicable facility's percent of allowed charges rate or fee schedule as determined, maintained, and posted by the Washington state department of labor and industries pursuant to chapter 51.04 RCW.

. As part of the screening process upon booking or preparation of an inmate into jail, general information concerning the inmate's ability to pay for medical care shall be identified, including insurance or other medical benefits or resources to which an inmate is entitled. The inmate may also be evaluated for medicaid eligibility and, if deemed potentially eligible, enrolled in medicaid. This information shall be made available to the authority, the governing unit, and any provider of health care services. To the extent that federal law allows, a jail or the jail's designee is authorized to act on behalf of a confined person for purposes of applying for medicaid.

. The governing unit or provider may obtain reimbursement from the confined person for the cost of health care services not provided under chapter 74.09 RCW, including reimbursement from any insurance program or from other medical benefit programs available to the confined person. Nothing in this chapter precludes civil or criminal remedies to recover the costs of medical care provided jail inmates or paid for on behalf of inmates by the governing unit. As part of a judgment and sentence, the courts are authorized to order defendants to repay all or part of the medical costs incurred by the governing unit or provider during confinement.

. To the extent that a confined person is unable to be financially responsible for medical care and is ineligible for the authority's medical care programs under chapter 74.09 RCW, or for coverage from private sources, and in the absence of an interlocal agreement or other contracts to the contrary, the governing unit may obtain reimbursement for the cost of such medical services from the unit of government whose law enforcement officers initiated the charges on which the person is being held in the jail: PROVIDED, That reimbursement for the cost of such services shall be by the state for state prisoners being held in a jail who are accused of either escaping from a state facility or of committing an offense in a state facility.

. There shall be no right of reimbursement to the governing unit from units of government whose law enforcement officers initiated the charges for which a person is being held in the jail for care provided after the charges are disposed of by sentencing or otherwise, unless by intergovernmental agreement pursuant to chapter 39.34 RCW.

. Under no circumstance shall necessary medical services be denied or delayed because of disputes over the cost of medical care or a determination of financial responsibility for payment of the costs of medical care provided to confined persons.

. Nothing in this section shall limit any existing right of any party, governing unit, or unit of government against the person receiving the care for the cost of the care provided.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5593-S.SL.pdf?cite=2015%20c%20267%20§%208[2015 c 267 § 8]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1738-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2015%20§%2085[2011 1st sp.s. c 15 § 85]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1469-S.SL.pdf?cite=1993%20c%20409%20§%201[1993 c 409 § 1]; 2007 c 259 § 66; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c118.pdf?cite=1986%20c%20118%20§%209[1986 c 118 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c316.pdf?cite=1977%20ex.s.%20c%20316%20§%2013[1977 ex.s. c 316 § 13]; ]

== 70.48.135 - Pregnant inmates—Midwifery or doula services—Reasonable accommodations.
. Jails must make reasonable accommodations for the provision of available midwifery or doula services to inmates who are pregnant or who have given birth in the last six weeks. Persons providing midwifery or doula services must be granted appropriate facility access, must be allowed to attend and provide assistance during labor and childbirth where feasible, and must have access to the inmate's relevant health care information, as defined in RCW 70.02.010, if the inmate authorizes disclosure.

. For purposes of this section, the following definitions apply:

.. "Doula services" are services provided by a trained doula and designed to provide physical, emotional, or informational support to a pregnant woman before, during, and after delivery of a child. Doula services may include, but are not limited to: Support and assistance during labor and childbirth; prenatal and postpartum education; breastfeeding assistance; parenting education; and support in the event that a woman has been or will become separated from her child.

.. "Midwifery services" means medical aid rendered by a midwife to a woman during prenatal, intrapartum, or postpartum stages or to a woman's newborn up to two weeks of age.

.. "Midwife" means a midwife licensed under chapter 18.50 RCW or an advanced registered nurse practitioner licensed under chapter 18.79 RCW.

. Nothing in this section requires governing units to establish or provide funding for midwifery or doula services, or prevents the adoption of policy guidelines for the delivery of midwifery or doula services to inmates. Services provided under this section may not supplant health care services routinely provided to the inmate.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2016-S.SL.pdf?cite=2018%20c%2041%20§%202[2018 c 41 § 2]; ]

== 70.48.140 - Confinement pursuant to authority of the United States.
A person having charge of a jail shall receive and keep in such jail, when room is available, all persons confined or committed thereto by process or order issued under authority of the United States until discharged according to law, the same as if such persons had been committed under process issued under authority of the state, if provision is made by the United States for the support of such persons confined, and for any additional personnel required.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c316.pdf?cite=1977%20ex.s.%20c%20316%20§%2014[1977 ex.s. c 316 § 14]; ]

== 70.48.160 - Post-approval limitation on funding.
Having received approval pursuant to *RCW 70.48.060, a governing unit shall not be eligible for further funding for physical plant standards for a period of ten years from the date of the completion of the approved project. A jail shall not be closed for noncompliance to physical plant standards within this same ten year period. This section does not apply if:

. The state elects to fund phased components of a jail project for which a governing unit has applied. In that instance, initially funded components do not constitute full funding within the meaning of *RCW 70.48.060(1) and ** 70.48.070(2) and the state may fund subsequent phases of the jail project;

. There is destruction of the facility because of an act of God or the result of a negligent and/or criminal act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c462.pdf?cite=1987%20c%20462%20§%209[1987 c 462 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c118.pdf?cite=1986%20c%20118%20§%2010[1986 c 118 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c276.pdf?cite=1981%20c%20276%20§%203[1981 c 276 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c316.pdf?cite=1977%20ex.s.%20c%20316%20§%2016[1977 ex.s. c 316 § 16]; ]

== 70.48.170 - Short title.
This chapter shall be known and may be cited as the City and County Jails Act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c316.pdf?cite=1977%20ex.s.%20c%20316%20§%2017[1977 ex.s. c 316 § 17]; ]

== 70.48.180 - Authority to locate and operate jail facilities—Counties.
Counties may acquire, build, operate, and maintain holding, detention, special detention, and correctional facilities as defined in RCW 70.48.020 at any place designated by the county legislative authority within the territorial limits of the county. The facilities shall comply with chapter 70.48 RCW and the rules adopted thereunder.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c165.pdf?cite=1983%20c%20165%20§%2037[1983 c 165 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c232.pdf?cite=1979%20ex.s.%20c%20232%20§%2016[1979 ex.s. c 232 § 16]; ]

== 70.48.190 - Authority to locate and operate jail facilities—Cities and towns.
Cities and towns may acquire, build, operate, and maintain holding, detention, special detention, and correctional facilities as defined in RCW 70.48.020 at any place within the territorial limits of the county in which the city or town is situated, as may be selected by the legislative authority of the municipality. The facilities comply with the provisions of chapter 70.48 RCW and rules adopted thereunder.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c165.pdf?cite=1983%20c%20165%20§%2038[1983 c 165 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c316.pdf?cite=1977%20ex.s.%20c%20316%20§%2019[1977 ex.s. c 316 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c7.pdf?cite=1965%20c%207%20§%2035.21.330[1965 c 7 § 35.21.330]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c103.pdf?cite=1917%20c%20103%20§%201[1917 c 103 § 1]; RRS § 10204; ]

== 70.48.210 - Farms, camps, work release programs, and special detention facilities.
. All cities and counties are authorized to establish and maintain farms, camps, and work release programs and facilities, as well as special detention facilities. The facilities shall meet the requirements of chapter 70.48 RCW and any rules adopted thereunder.

. Farms and camps may be established either inside or outside the territorial limits of a city or county. A sentence of confinement in a city or county jail may include placement in a farm or camp. Unless directed otherwise by court order, the chief law enforcement officer or department of corrections, may transfer the prisoner to a farm or camp. The sentencing court, chief law enforcement officer, or department of corrections may not transfer to a farm or camp a greater number of prisoners than can be furnished with constructive employment and can be reasonably accommodated.

. The city or county may establish a city or county work release program and housing facilities for the prisoners in the program. In such regard, factors such as employment conditions and the condition of jail facilities should be considered. When a work release program is established the following provisions apply:

.. A person convicted of a felony and placed in a city or county jail is eligible for the work release program. A person sentenced to a city or county jail is eligible for the work release program. The program may be used as a condition of probation for a criminal offense. Good conduct is a condition of participation in the program.

.. The court may permit a person who is currently, regularly employed to continue his or her employment. The chief law enforcement officer or department of corrections shall make all necessary arrangements if possible. The court may authorize the person to seek suitable employment and may authorize the chief law enforcement officer or department of corrections to make reasonable efforts to find suitable employment for the person. A person participating in the work release program may not work in an establishment where there is a labor dispute.

.. The work release prisoner shall be confined in a work release facility or jail unless authorized to be absent from the facility for program-related purposes, unless the court directs otherwise.

.. Each work release prisoner's earnings may be collected by the chief law enforcement officer or a designee. The chief law enforcement officer or a designee may deduct from the earnings moneys for the payments for the prisoner's board, personal expenses inside and outside the jail, a share of the administrative expenses of this section, court-ordered victim compensation, and court-ordered restitution. Support payments for the prisoner's dependents, if any, shall be made as directed by the court. With the prisoner's consent, the remaining funds may be used to pay the prisoner's preexisting debts. Any remaining balance shall be returned to the prisoner.

.. The prisoner's sentence may be reduced by earned early release time in accordance with procedures that shall be developed and promulgated by the work release facility. The earned early release time shall be for good behavior and good performance as determined by the facility. The facility shall not credit the offender with earned early release credits in advance of the offender actually earning the credits. In the case of an offender convicted of a serious violent offense or a sex offense that is a class A felony committed on or after July 1, 1990, the aggregate earned early release time may not exceed fifteen percent of the sentence. In no other case may the aggregate earned early release time exceed one-third of the total sentence.

.. If the work release prisoner violates the conditions of custody or employment, the prisoner shall be returned to the sentencing court. The sentencing court may require the prisoner to spend the remainder of the sentence in actual confinement and may cancel any earned reduction of the sentence.

. A special detention facility may be operated by a noncorrectional agency or by noncorrectional personnel by contract with the governing unit. The employees shall meet the standards of training and education established by the criminal justice training commission as authorized by RCW 43.101.080. The special detention facility may use combinations of features including, but not limited to, low-security or honor prisoner status, work farm, work release, community review, prisoner facility maintenance and food preparation, training programs, or alcohol or drug rehabilitation programs. Special detention facilities may establish a reasonable fee schedule to cover the cost of facility housing and programs. The schedule shall be on a sliding basis that reflects the person's ability to pay.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%20203[1990 c 3 § 203]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c248.pdf?cite=1989%20c%20248%20§%203[1989 c 248 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c298.pdf?cite=1985%20c%20298%20§%201[1985 c 298 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c165.pdf?cite=1983%20c%20165%20§%2039[1983 c 165 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c232.pdf?cite=1979%20ex.s.%20c%20232%20§%2017[1979 ex.s. c 232 § 17]; ]

== 70.48.215 - Booking patients of state hospitals.
A jail may not refuse to book a patient of a state hospital solely based on the patient's status as a state hospital patient, but may consider other relevant factors that apply to the individual circumstances in each case.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6492-S.SL.pdf?cite=2012%20c%20256%20§%2011[2012 c 256 § 11]; ]

== 70.48.220 - Confinement may be wherever jail services are contracted—Defendant contact with defense counsel.
A person confined for an offense punishable by imprisonment in a city or county jail may be confined in the jail of any city or county contracting with the prosecuting city or county for jail services.

A jurisdiction that confines persons prior to conviction in a jail in another county is responsible for providing private telephone, videoconferencing, or in-person contact between the defendant and his or her public defense counsel.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2541-S.SL.pdf?cite=2002%20c%20125%20§%202[2002 c 125 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c232.pdf?cite=1979%20ex.s.%20c%20232%20§%2019[1979 ex.s. c 232 § 19]; ]

== 70.48.230 - Transportation and temporary confinement of prisoners.
The jurisdiction having immediate authority over a prisoner is responsible for the transportation expenses. The transporting officer shall have custody of the prisoner within any Washington county while being transported. Any jail within the state may be used for the temporary confinement of the prisoner with the only charge being for the reasonable cost of board.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c232.pdf?cite=1979%20ex.s.%20c%20232%20§%2018[1979 ex.s. c 232 § 18]; ]

== 70.48.240 - Transfer of felons from jail to state institution—Time limit.
A person imprisoned in a jail and sentenced to a state institution for a felony conviction shall be transferred to a state institution before the forty-first day from the date of sentencing.

This section does not apply to persons sentenced for a felony who are held in the facility as a condition of probation or who are specifically sentenced to confinement in the facility.

Payment for persons sentenced to state institutions and remaining in a jail from the eighth through the fortieth days following sentencing shall be in accordance with the procedure prescribed under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c235.pdf?cite=1984%20c%20235%20§%208[1984 c 235 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c232.pdf?cite=1979%20ex.s.%20c%20232%20§%2020[1979 ex.s. c 232 § 20]; ]

== 70.48.245 - Transfer of persons with developmental disabilities or traumatic brain injuries from jail to department of corrections facility.
When a jail has determined that a person in custody has or may have a developmental disability as defined in RCW 71A.10.020 or a traumatic brain injury, upon transfer of the person to a department of corrections facility or other jail facility, every reasonable effort shall be made by the transferring jail staff to communicate to receiving staff the nature of the disability, as determined by the jail and any necessary accommodation for the person as identified by the transferring jail staff.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1718-S.SL.pdf?cite=2011%20c%20236%20§%202[2011 c 236 § 2]; ]

== 70.48.380 - Special detention facilities—Fees for cost of housing.
The legislative authority of a county or city that establishes a special detention facility as defined in RCW 70.48.020 for persons convicted of violating RCW 46.61.502 or 46.61.504 may establish a reasonable fee schedule to cover the cost of housing in the facility. The schedule shall be on a sliding basis that reflects the person's ability to pay.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c165.pdf?cite=1983%20c%20165%20§%2036[1983 c 165 § 36]; ]

== 70.48.390 - Fee payable by person being booked.
A governing unit may require that each person who is booked at a city, county, or regional jail pay a fee based on the jail's actual booking costs or one hundred dollars, whichever is less, to the sheriff's department of the county or police chief of the city in which the jail is located. The fee is payable immediately from any money then possessed by the person being booked, or any money deposited with the sheriff's department or city jail administration on the person's behalf. If the person has no funds at the time of booking or during the period of incarceration, the sheriff or police chief may notify the court in the county or city where the charges related to the booking are pending, and may request the assessment of the fee. Unless the person is held on other criminal matters, if the person is not charged, is acquitted, or if all charges are dismissed, the sheriff or police chief shall return the fee to the person at the last known address listed in the booking records.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1232-S.SL.pdf?cite=2003%20c%2099%20§%201[2003 c 99 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1143-S2.SL.pdf?cite=1999%20c%20325%20§%203[1999 c 325 § 3]; ]

== 70.48.400 - Sentences to be served in state institutions—When—Sentences that may be served in jail—Financial responsibility of city or county.
Persons sentenced to felony terms or a combination of terms of more than three hundred sixty-five days of incarceration shall be committed to state institutions under the authority of the department of corrections. Persons serving sentences of three hundred sixty-five consecutive days or less may be sentenced to a jail as defined in RCW 70.48.020. All persons convicted of felonies or misdemeanors and sentenced to jail shall be the financial responsibility of the city or county.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c462.pdf?cite=1987%20c%20462%20§%2011[1987 c 462 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c235.pdf?cite=1984%20c%20235%20§%201[1984 c 235 § 1]; ]

== 70.48.410 - Financial responsibility for convicted felons.
Persons convicted of a felony as defined by chapter 9A.20 RCW and committed to the care and custody of the department of corrections shall be the financial responsibility of the department of corrections not later than the eighth day, excluding weekends and holidays, following sentencing for the felony and notification that the prisoner is available for movement to a state correctional institution. However, if good cause is shown, a superior court judge may order the prisoner detained in the jail beyond the eight-day period for an additional period not to exceed ten days. If a superior court orders a convicted felon to be detained beyond the eighth day following sentencing, the county or city shall retain financial responsibility for that ten-day period or portion thereof ordered by the court.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c235.pdf?cite=1984%20c%20235%20§%202[1984 c 235 § 2]; ]

== 70.48.420 - Financial responsibility for persons detained on parole hold.
A person detained in jail solely by reason of a parole hold is the financial responsibility of the city or the county detaining the person until the sixteenth day, at which time the person shall become the financial responsibility of the department of corrections. Persons who are detained in a jail on a parole hold and for whom the prosecutor has filed a felony charge remain the responsibility of the city or county.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c235.pdf?cite=1984%20c%20235%20§%203[1984 c 235 § 3]; ]

== 70.48.430 - Financial responsibility for work release inmates detained in jail.
Inmates, as defined by *RCW 72.09.020, who reside in a work release facility and who are detained in a city or county jail are the financial responsibility of the department of corrections.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c235.pdf?cite=1984%20c%20235%20§%204[1984 c 235 § 4]; ]

== 70.48.440 - Office of financial management to establish reimbursement rate for cities and counties—Rate until June 30, 1985—Reestablishment of rates.
The office of financial management shall establish a uniform equitable rate for reimbursing cities and counties for the care of sentenced felons who are the financial responsibility of the department of corrections and are detained or incarcerated in a city or county jail.

Until June 30, 1985, the rate for the care of sentenced felons who are the financial responsibility of the department of corrections shall be ten dollars per day. Cost of extraordinary emergency medical care incurred by prisoners who are the financial responsibility of the department of corrections under this chapter shall be reimbursed. The department of corrections shall be advised as far in advance as practicable by competent medical authority of the nature and course of treatment required to ensure the most efficient use of state resources to address the medical needs of the offender. In the event emergency medical care is needed, the department of corrections shall be advised as soon as practicable after the offender is treated.

Prior to June 30, 1985, the office of financial management shall meet with the *corrections standards board to establish criteria to determine equitable rates regarding variable costs for sentenced felons who are the financial responsibility of the department of corrections after June 30, 1985. The office of financial management shall reestablish these rates each even-numbered year beginning in 1986.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c235.pdf?cite=1984%20c%20235%20§%205[1984 c 235 § 5]; ]

== 70.48.450 - Local jail reporting form—Information to be provided by city or county requesting payment for prisoners from state.
The department of corrections is responsible for developing a reporting form for the local jails. The form shall require sufficient information to identify the person, type of state responsibility, method of notification for availability for movement, and the number of days for which the state is financially responsible. The information shall be provided by the city or county requesting payment for prisoners who are the financial responsibility of the department of corrections.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c235.pdf?cite=1984%20c%20235%20§%206[1984 c 235 § 6]; ]

== 70.48.460 - Contracts for incarceration services for prisoners not covered by RCW  70.48.400 through  70.48.450.
Nothing in RCW 70.48.400 through 70.48.450 precludes the establishment of mutually agreeable contracts between the department of corrections and counties for incarceration services of prisoners not covered by RCW 70.48.400 through 70.48.450.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c235.pdf?cite=1984%20c%20235%20§%207[1984 c 235 § 7]; ]

== 70.48.470 - Sex, kidnapping offenders—Notices to offenders, law enforcement officials.
. A person having charge of a jail shall notify in writing any confined person who is in the custody of the jail for a conviction of a sex offense or a kidnapping offense as defined in RCW 9A.44.128 of the registration requirements of RCW 9A.44.130 at the time of the inmate's release from confinement, and shall obtain written acknowledgment of such notification. The person shall also obtain from the inmate the county of the inmate's residence upon release from jail and, where applicable, the city.

. When a sex offender or kidnapping offender under local government jurisdiction will reside in a county other than the county of conviction upon discharge or release, the chief law enforcement officer of the jail or his or her designee shall give notice of the inmate's discharge or release to the sheriff of the county and, where applicable, to the police chief of the city where the offender will reside.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6414-S.SL.pdf?cite=2010%20c%20267%20§%2014[2010 c 267 § 14]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2424.SL.pdf?cite=2000%20c%2091%20§%204[2000 c 91 § 4]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5759-S.SL.pdf?cite=1997%20c%20364%20§%203[1997 c 364 § 3]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5621-S.SL.pdf?cite=1997%20c%20113%20§%207[1997 c 113 § 7]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2545-S.SL.pdf?cite=1996%20c%20215%20§%202[1996 c 215 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%20406[1990 c 3 § 406]; ]

== 70.48.475 - Release of offender or defendant subject to a discharge review—Required notifications.
. A person having charge of a jail, or that person's designee, shall notify the designated crisis responder seventy-two hours prior to the release to the community of an offender or defendant who was subject to a discharge review under RCW 71.05.232. If the person having charge of the jail does not receive seventy-two hours notice of the release, the notification to the designated crisis responder shall be made as soon as reasonably possible, but not later than the actual release to the community of the defendant or offender.

. When a person having charge of a jail, or that person's designee, releases an offender or defendant who was the subject of a discharge review under RCW 71.05.232, the person having charge of a jail, or that person's designee, shall notify the state hospital from which the offender or defendant was released.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1713-S3.SL.pdf?cite=2016%20sp.s.%20c%2029%20§%20418[2016 sp.s. c 29 § 418]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6358-S2.SL.pdf?cite=2004%20c%20166%20§%2014[2004 c 166 § 14]; ]

== 70.48.480 - Communicable disease prevention guidelines.
. Local jail administrators shall develop and implement policies and procedures for the uniform distribution of communicable disease prevention guidelines to all jail staff who, in the course of their regularly assigned job responsibilities, may come within close physical proximity to offenders or detainees with communicable diseases.

. The guidelines shall identify special precautions necessary to reduce the risk of transmission of communicable diseases.

. For the purposes of this section, "communicable disease" means a sexually transmitted disease, as defined in RCW 70.24.017, diseases caused by blood-borne pathogens, or any other illness caused by an infectious agent that can be transmitted from one person, animal, or object to another person by direct or indirect means including transmission via an intermediate host or vector, food, water, or air.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1605-S.SL.pdf?cite=1997%20c%20345%20§%205[1997 c 345 § 5]; ]

== 70.48.490 - Delivery and administration of medications and medication assistance by nonpractitioner jail personnel—Conditions.
Jails may provide for the delivery and administration of medications and medication assistance for inmates in their custody by nonpractitioner jail personnel, subject to the following conditions:

. The jail administrator or his or her designee, or chief law enforcement executive or his or her designee, shall enter into an agreement between the jail and a licensed pharmacist, pharmacy, or other licensed practitioner or health care facility to ensure access to pharmaceutical services on a twenty-four hour a day basis, including consultation and dispensing services.

. The jail administrator or chief law enforcement executive shall adopt policies which address the designation and training of nonpractitioner jail personnel who may deliver and administer medications or provide medication assistance to inmates as provided in this chapter. The policies must address the administration of prescriptions from licensed practitioners prescribing within the scope of their prescriptive authority, the identification of medication to be delivered and administered or administered through medication assistance, the means of securing medication with attention to the safeguarding of legend drugs, and the means of maintaining a record of the delivery, administration, self-administration, or medication assistance of all medication. The jail administrator or chief law enforcement executive shall designate a physician licensed under chapter 18.71 RCW, or a registered nurse or advanced registered nurse practitioner licensed under chapter 18.79 RCW, to train the designated nonpractitioner jail personnel in proper medication procedures and monitor their compliance with the procedures.

. The jail administrator or chief law enforcement executive shall consult with one or more pharmacists, and one or more licensed physicians or nurses, in the course of developing the policies described in subsections (1) and (2) of this section. A jail shall provide the Washington association of sheriffs and police chiefs with a copy of the jail's current policies regarding medication management.

. The practitioner or nonpractitioner jail personnel delivering, administering, or providing medication assistance is in receipt of (a) for prescription drugs, a written, current, and unexpired prescription, and instructions for administration from a licensed practitioner prescribing within the scope of his or her prescriptive authority for administration of the prescription drug; (b) for nonprescription drugs, a written, current, and unexpired instruction from a licensed practitioner regarding the administration of the nonprescription drug; and (c) for minors under the age of eighteen, a written, current consent from the minor's parent, legal guardian, or custodian consenting to the administration of the medication.

. Nonpractitioner jail personnel may help in the preparation of legend drugs or controlled substances for self-administration where a practitioner has determined and communicated orally or by written direction that the medication preparation assistance is necessary and appropriate. Medication assistance shall not include assistance with intravenous medications or injectable medications.

. Nonpractitioner jail personnel shall not include inmates.

. All medication is delivered and administered and all medication assistance is provided by a practitioner or nonpractitioner jail personnel pursuant to the policies adopted in this section, and in compliance with the prescription of a practitioner prescribing within the scope of his or her prescriptive authority, or the written instructions as provided in this section.

. The jail administrator or the chief law enforcement executive shall ensure that all nonpractitioner jail personnel authorized to deliver, administer, and provide medication assistance are trained pursuant to the policies adopted in this section prior to being permitted to deliver, administer, or provide medication assistance to an inmate.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5252-S.SL.pdf?cite=2009%20c%20411%20§%204[2009 c 411 § 4]; ]

== 70.48.500 - Use of restraints on pregnant women or youth in custody—Allowed in extraordinary circumstances.
. Except in extraordinary circumstances no restraints of any kind may be used on any pregnant woman or youth incarcerated in a correctional facility or any facility covered by this chapter during transportation to and from visits to medical providers and court proceedings during the third trimester of her pregnancy, or during postpartum recovery. For purposes of this section, "extraordinary circumstances" exist where a corrections officer or employee of the correctional facility or any facility covered by this chapter makes an individualized determination that restraints are necessary to prevent an incarcerated pregnant woman or youth from escaping, or from injuring herself, medical or correctional personnel, or others. In the event the corrections officer or employee of the correctional facility or any facility covered by this chapter determines that extraordinary circumstances exist and restraints are used, the corrections officer or employee must fully document in writing the reasons that he or she determined such extraordinary circumstances existed such that restraints were used. As part of this documentation, the corrections officer or employee must also include the kind of restraints used and the reasons those restraints were considered the least restrictive available and the most reasonable under the circumstances.

. While the pregnant woman or youth is in labor or in childbirth no restraints of any kind may be used. Nothing in this section affects the use of hospital restraints requested for the medical safety of a patient by treating physicians licensed under Title 18 RCW.

. Anytime restraints are permitted to be used on a pregnant woman or youth, the restraints must be the least restrictive available and the most reasonable under the circumstances, but in no case shall leg irons or waist chains be used on any woman or youth known to be pregnant.

. No correctional personnel or employee of the correctional facility or any facility covered by this chapter shall be present in the room during the pregnant woman's or youth's labor or childbirth, unless specifically requested by medical personnel. If the employee's presence is requested by medical personnel, the employee should be female, if practicable.

. If the doctor, nurse, or other health professional treating the pregnant woman or youth requests that restraints not be used, the corrections officer or employee accompanying the pregnant woman or youth shall immediately remove all restraints.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2747-S.SL.pdf?cite=2010%20c%20181%20§%205[2010 c 181 § 5]; ]

== 70.48.501 - Use of restraints on pregnant women or youth in custody—Provision of information to staff, women, or youth of childbearing age in custody.
. The jail administrator or his or her designee or chief law enforcement executive or his or her designee shall provide notice of the requirements of chapter 181, Laws of 2010 to the appropriate staff at a correctional facility or a facility covered by this chapter. Appropriate staff shall include all medical staff and staff who are involved in the transportation of pregnant women and youth as well as such other staff deemed appropriate.

. The jail administrator or his or her designee or chief law enforcement executive or his or her designee shall cause the requirements of chapter 181, Laws of 2010 to be provided to all women and youth of childbearing age at intake. In addition, the jail administrator or his or her designee or chief law enforcement executive or his or her designee shall cause a notice containing the requirements of chapter 181, Laws of 2010 to be posted in locations in which medical care is provided within the facilities.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2747-S.SL.pdf?cite=2010%20c%20181%20§%206[2010 c 181 § 6]; ]

== 70.48.502 - Use of restraints on pregnant women or youth in custody—Limited immunity from liability.
No civil liability may be imposed by any court on the county or its jail officers or employees under RCW 70.48.500 and 70.48.501 except upon proof of gross negligence.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2747-S.SL.pdf?cite=2010%20c%20181%20§%2014[2010 c 181 § 14]; ]

== 70.48.510 - Unexpected fatality review—Records—Discovery.
. [Empty]
.. A city or county department of corrections or chief law enforcement officer responsible for the operation of a jail shall conduct an unexpected fatality review in any case in which the death of an individual confined in the jail is unexpected.

.. The city or county department of corrections or chief law enforcement officer shall convene an unexpected fatality review team and determine the membership of the review team. The team shall comprise of individuals with appropriate expertise including, but not limited to, individuals whose professional expertise is pertinent to the dynamics of the case. The city or county department of corrections or chief law enforcement officer shall ensure that the unexpected fatality review team is made up of individuals who had no previous involvement in the case.

.. The primary purpose of the unexpected fatality review shall be the development of recommendations to the governing unit with primary responsibility for the operation of the jail and legislature regarding changes in practices or policies to prevent fatalities and strengthen safety and health protections for individuals in custody.

.. Upon conclusion of an unexpected fatality review required pursuant to this section, the city or county department of corrections or chief law enforcement officer shall, within 120 days following the fatality, issue a report on the results of the review, unless an extension has been granted by the chief executive or, if appropriate, the county legislative authority of the governing unit with primary responsibility for the operation of the jail. Reports must be distributed to the governing unit with primary responsibility for the operation of the jail and appropriate committees of the legislature, and the department of health shall create a public website where all unexpected fatality review reports required under this section must be posted and maintained. An unexpected fatality review report completed pursuant to this section is subject to public disclosure and must be posted on the department of health public website, except that confidential information may be redacted by the city or county department of corrections or chief law enforcement officer consistent with the requirements of applicable state and federal laws.

.. The city or county department of corrections or chief law enforcement officer shall develop and implement procedures to carry out the requirements of this section.

. In any review of an unexpected fatality, the city or county department of corrections or chief law enforcement officer and the unexpected fatality review team shall have access to all records and files regarding the person or otherwise relevant to the review that have been produced or retained by the agency.

. [Empty]
.. An unexpected fatality review completed pursuant to this section is subject to discovery in a civil or administrative proceeding, but may not be admitted into evidence or otherwise used in a civil or administrative proceeding except pursuant to this section.

.. An employee of a city or county department of corrections or law enforcement employee responsible for conducting an unexpected fatality review, or member of an unexpected fatality review team, may not be examined in a civil or administrative proceeding regarding: (i) The work of the unexpected fatality review team; (ii) the incident under review; (iii) his or her statements, deliberations, thoughts, analyses, or impressions relating to the work of the unexpected fatality review team or the incident under review; or (iv) the statements, deliberations, thoughts, analyses, or impressions of any other member of the unexpected fatality review team, or any person who provided information to the unexpected fatality review team relating to the work of the unexpected fatality review team or the incident under review.

.. Documents prepared by or for an unexpected fatality review team are inadmissible and may not be used in a civil or administrative proceeding, except that any document that exists before its use or consideration in an unexpected fatality review, or that is created independently of such review, does not become inadmissible merely because it is reviewed or used by an unexpected fatality review team. A person is not unavailable as a witness merely because the person has been interviewed by, or has provided a statement for, an unexpected fatality review, but if the person is called as a witness, the person may not be examined regarding the person's interactions with the unexpected fatality review including, without limitation, whether the person was interviewed during such review, the questions that were asked during such review, and the answers that the person provided during such review. This section may not be construed as restricting the person from testifying fully in any proceeding regarding his or her knowledge of the incident under review.

.. The restrictions set forth in this section do not apply in a licensing or disciplinary proceeding arising from an agency's effort to revoke or suspend the license of any licensed professional based in whole or in part upon allegations of wrongdoing in connection with an unexpected fatality reviewed by an unexpected fatality review team.

. No provision of this section may be interpreted to require a jail to disclose any information in a report that would, as determined by the jail, reveal security information about the jail.

. For the purposes of this section:

.. "City or county department of corrections" means a department of corrections created by a city or county to be in charge of the jail and all persons confined in the jail pursuant to RCW 70.48.090.

.. "Chief law enforcement officer" means the chief law enforcement officer who is in charge of the jail and all persons confined in the jail if no department of corrections was created by a city or county pursuant to RCW 70.48.090.

.. "Unexpected fatality review" means a review of any death that was not the result of a diagnosed or documented terminal illness or other debilitating or deteriorating illness or condition where the death was anticipated, and includes the death of any person under the care and custody of the city or county department of corrections or chief local enforcement officer, regardless of where the death actually occurred. A review must include an analysis of the root cause or causes of the unexpected fatality, and an associated corrective action plan for the jail to address identified root causes and recommendations made by the unexpected fatality review team under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5119-S.SL.pdf?cite=2021%20c%20139%20§%203[2021 c 139 § 3]; ]

== 70.48.520 - Collaboration with managed care organizations.
A department of corrections or chief law enforcement officer responsible for the operation of a jail shall make reasonable efforts to collaborate with managed care organizations, as defined in RCW 71.24.025, for the purposes of care coordination activities and improving health care delivery and release planning for persons confined in the jail.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1348-S.SL.pdf?cite=2021%20c%20166%20§%203[2021 c 166 § 3]; ]

== 70.48.800 - Use of restraints on pregnant women or youth in custody—Informational packet.
The Washington association of sheriffs and police chiefs, the department of corrections, the department of social and health services, juvenile rehabilitation administration, and the criminal justice training commission shall jointly develop an informational packet on the requirements of chapter 181, Laws of 2010. The packet shall be ready for distribution no later than September 1, 2010.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2747-S.SL.pdf?cite=2010%20c%20181%20§%2013[2010 c 181 § 13]; ]

== 70.48.801 - Jail standards task force.
. A joint legislative task force on jail standards is established, with members as provided in this subsection.

.. The president of the senate shall appoint one member from each of the two largest caucuses of the senate.

.. The speaker of the house of representatives shall appoint one member from each of the two largest caucuses of the house of representatives.

.. The president of the senate and the speaker of the house of representatives jointly shall appoint 13 members representing the interests of: Prosecutors, defense attorneys, law enforcement, counties, cities, jail administrators, superior courts, district and municipal courts, a state designated protection and advocacy agency, medical and mental health service providers, a statewide civil legal aid organization, persons with lived experience, and other entities involved with or interested in the operation of local jails.

. The legislative membership shall convene the initial meeting of the task force. The task force shall choose its chair from among its legislative membership.

. Staff support for the task force must be provided by the office of the attorney general.

. [Empty]
.. Legislative members of the task force may be reimbursed for travel expenses in accordance with RCW 44.04.120. Except as provided in (b) of this subsection, nonlegislative members are not entitled to be reimbursed for travel expenses if they are elected officials or are participating on behalf of an employer, governmental entity, or other organization. Any reimbursement for other nonlegislative members is subject to chapter 43.03 RCW.

.. Nonlegislative members of the task force who demonstrate financial hardship must be reimbursed for travel expenses as provided in RCW 43.03.050 and 43.03.060, as well as other expenses as needed for each day a nonlegislative task force member attends a task force meeting to provide consultative assistance.

. The expenses of the task force must be paid jointly by the senate and the house of representatives. Task force expenditures are subject to approval by the senate facilities and operations committee and the house executive rules committee, or their successor committees.

. The task force shall review the following issues:

.. The adequacy of standards adopted and used by jails including, but not limited to, standards for conditions and operations, inspections, enforcement, and oversight;

.. Current data on jails in the state including, but not limited to, square footage of living space per individual, jail capacity, average daily population over the previous five years, medical and dental services, mental health services, treatment programming options, accreditation status, use of force incidents over the previous five years, and in-custody deaths and the causes of those deaths;

.. How the jails in the state compare to jail standards and practices in other states regarding safety and physical conditions; health and welfare; access to medical, mental health, dental care, and substance use disorder treatment; food quality and quantity; use of force; use of solitary confinement; and recreational activities and programming;

.. The revenue sources and funding mechanisms used by other states to pay for local jails and the kinds of services that are provided to inmates in jails in other states, including identifying the entity that is responsible for financing those services;

.. Inmate's access to jail telecommunication, electronic media, and commissary services, including the rates and fees charged by the jail for these services that are often borne by families of incarcerated individuals; and

.. Other issues the task force deems relevant to the conditions of jails.

. The task force shall make recommendations regarding:

.. Statewide minimum jail standards, oversight, or other policy changes to ensure jail conditions meet state and federal constitutional and statutory standards and include adequate safety and welfare safeguards for incarcerated persons and staff; and

.. Restoration of a statewide authority to set mandatory minimum jail standards and conduct inspections of jails for compliance and enforcement of those standards.

. The task force shall consult with organizations and entities with interest or experience in jail standards and operations including, but not limited to, treatment providers, victims' advocates, inmate advocates, organizations representing jail employees and officers, and other community organizations.

. The Washington association of sheriffs and police chiefs and representatives from county, city, and regional jails must provide any data or information that is requested by the task force to perform its duties under this section.

. The task force shall report findings and recommendations to the governor and the appropriate committees of the legislature by June 30, 2023.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5092-S.SL.pdf?cite=2021%20c%20334%20§%20957[2021 c 334 § 957]; ]

