= 70.43 - Hospital staff membership or privileges.
:toc:

== 70.43.010 - Applications for membership or privileges—Standards and procedures.
Within one hundred eighty days of June 11, 1986, the governing body of every hospital licensed under chapter 70.41 RCW shall set standards and procedures to be applied by the hospital and its medical staff in considering and acting upon applications for staff membership or professional privileges.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c205.pdf?cite=1986%20c%20205%20§%201[1986 c 205 § 1]; ]

== 70.43.020 - Applications for membership or privileges—Discrimination based on type of license prohibited—Exception.
The governing body of any hospital, except any hospital which employs its medical staff, in considering and acting upon applications for staff membership or professional privileges within the scope of the applicants' respective licenses, shall not discriminate against a qualified person solely on the basis of whether such person is licensed under chapters 18.71, 18.57, or 18.22 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c205.pdf?cite=1986%20c%20205%20§%202[1986 c 205 § 2]; ]

== 70.43.030 - Violations of RCW  70.43.010 or  70.43.020—Injunctive relief.
Any person may apply to superior court for a preliminary or permanent injunction restraining a violation of RCW 70.43.010 or 70.43.020. This action is an additional remedy not dependent on the adequacy of the remedy at law. Nothing in this chapter shall require a hospital to grant staff membership or professional privileges until a final determination is made upon the merits by the hospital governing body.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c205.pdf?cite=1986%20c%20205%20§%203[1986 c 205 § 3]; ]

