= 70.46 - Health districts.
:toc:

== 70.46.020 - Districts of two or more counties—Health board—Membership—Chair.
Health districts consisting of two or more counties may be created whenever two or more boards of county commissioners shall by resolution establish a district for such purpose. Such a district shall consist of all the area of the combined counties. The district board of health of such a district shall consist of not less than five members for districts of two counties and seven members for districts of more than two counties, including two representatives from each county who are members of the board of county commissioners and who are appointed by the board of county commissioners of each county within the district, and shall have a jurisdiction coextensive with the combined boundaries. The boards of county commissioners may by resolution or ordinance provide for elected officials from cities and towns and persons other than elected officials as members of the district board of health so long as persons other than elected officials do not constitute a majority. A resolution or ordinance adopted under this section must specify the provisions for the appointment, term, and compensation, or reimbursement of expenses. Any multicounty health district existing on *the effective date of this act shall continue in existence unless and until changed by affirmative action of all boards of county commissioners or one or more counties withdraws [withdraw] pursuant to RCW 70.46.090.

At the first meeting of a district board of health the members shall elect a chair to serve for a period of one year.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5253-S.SL.pdf?cite=1995%20c%2043%20§%2010[1995 c 43 § 10]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20247[1993 c 492 § 247]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c51.pdf?cite=1967%20ex.s.%20c%2051%20§%206[1967 ex.s. c 51 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c183.pdf?cite=1945%20c%20183%20§%202[1945 c 183 § 2]; Rem. Supp. 1945 § 6099-11; ]

== 70.46.031 - Districts of one county—Health board—Membership.
A health district to consist of one county may be created whenever the county legislative authority of the county shall pass a resolution or ordinance to organize such a health district under chapter 70.05 RCW and this chapter.

The resolution or ordinance may specify the membership, representation on the district health board, or other matters relative to the formation or operation of the health district. The county legislative authority may appoint elected officials from cities and towns and persons other than elected officials as members of the health district board so long as persons other than elected officials do not constitute a majority.

Any single county health district existing on *the effective date of this act shall continue in existence unless and until changed by affirmative action of the county legislative authority.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5253-S.SL.pdf?cite=1995%20c%2043%20§%2011[1995 c 43 § 11]; ]

== 70.46.060 - District health board—Powers and duties.
The district board of health shall constitute the local board of health for all the territory included in the health district, and shall supersede and exercise all the powers and perform all the duties by law vested in the county board of health of any county included in the health district.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20248[1993 c 492 § 248]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c51.pdf?cite=1967%20ex.s.%20c%2051%20§%2011[1967 ex.s. c 51 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c183.pdf?cite=1945%20c%20183%20§%206[1945 c 183 § 6]; Rem. Supp. 1945 § 6099-15; ]

== 70.46.080 - District health funds.
Each health district shall establish a fund to be designated as the "district health fund", in which shall be placed all sums received by the district from any source, and out of which shall be expended all sums disbursed by the district. In a district composed of more than one county the county treasurer of the county having the largest population shall be the custodian of the fund, and the county auditor of said county shall keep the record of the receipts and disbursements, and shall draw and the county treasurer shall honor and pay all warrants, which shall be approved before issuance and payment as directed by the board.

Each county which is included in the district shall contribute such sums towards the expense for maintaining and operating the district as shall be agreed upon between it and the local board of health in accordance with guidelines established by the state board of health.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20249[1993 c 492 § 249]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c85.pdf?cite=1971%20ex.s.%20c%2085%20§%2010[1971 ex.s. c 85 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c51.pdf?cite=1967%20ex.s.%20c%2051%20§%2019[1967 ex.s. c 51 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c183.pdf?cite=1945%20c%20183%20§%208[1945 c 183 § 8]; Rem. Supp. 1945 § 6099-17; ]

== 70.46.082 - District health funds—Health district as custodian.
. A health district, with the consent of the county legislative authority, the county treasurer, the county auditor, and the health district board, may act as custodian of funds, may keep the record of the receipts and disbursements, and may draw and may honor and pay all warrants or checks, which shall be approved before issuance and payment as directed by the board.

. The county may not charge a health district that does not utilize the option in subsection (1) of this section for those services provided.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5458.SL.pdf?cite=2016%20sp.s.%20c%203%20§%201[2016 sp.s. c 3 § 1]; ]

== 70.46.085 - County to bear expense of providing public health services.
The expense of providing public health services shall be borne by each county within the health district.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20250[1993 c 492 § 250]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c51.pdf?cite=1967%20ex.s.%20c%2051%20§%2020[1967 ex.s. c 51 § 20]; ]

== 70.46.090 - Withdrawal of county.
Any county may withdraw from membership in said health district any time after it has been within the district for a period of two years, but no withdrawal shall be effective except at the end of the calendar year in which the county gives at least six months' notice of its intention to withdraw at the end of the calendar year. No withdrawal shall entitle any member to a refund of any moneys paid to the district nor relieve it of any obligations to pay to the district all sums for which it obligated itself due and owing by it to the district for the year at the end of which the withdrawal is to be effective. Any county which withdraws from membership in said health district shall immediately establish a health department or provide health services which shall meet the standards for health services promulgated by the state board of health. No local health department may be deemed to provide adequate public health services unless there is at least one full time professionally trained and qualified physician as set forth in RCW 70.05.050.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20251[1993 c 492 § 251]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c51.pdf?cite=1967%20ex.s.%20c%2051%20§%2021[1967 ex.s. c 51 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c183.pdf?cite=1945%20c%20183%20§%209[1945 c 183 § 9]; Rem. Supp. 1945 § 6099-18; ]

== 70.46.100 - Power to acquire, maintain, or dispose of property—Contracts.
In addition to all other powers and duties, a health district shall have the power to own, construct, purchase, lease, add to, and maintain any real and personal property or property rights necessary for the conduct of the affairs of the district. A health district may sell, lease, convey or otherwise dispose of any district real or personal property no longer necessary for the conduct of the affairs of the district. A health district may enter into contracts to carry out the provisions of this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c100.pdf?cite=1957%20c%20100%20§%202[1957 c 100 § 2]; ]

== 70.46.120 - License or permit fees.
In addition to all other powers and duties, health districts shall have the power to charge fees in connection with the issuance or renewal of a license or permit required by law: PROVIDED, That the fees charged shall not exceed the actual cost involved in issuing or renewing the license or permit.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20252[1993 c 492 § 252]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c121.pdf?cite=1963%20c%20121%20§%201[1963 c 121 § 1]; ]

