= 70.97 - Enhanced services facilities.
:toc:

== 70.97.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Behavioral health disorder" means either a mental disorder, a substance use disorder, or co-occurring mental disorder and substance use disorder.

. "Department" means the department of social and health services.

. "Detention" or "detain" means the lawful confinement of an individual under chapter 71.05 RCW.

. "Discharge" means a transfer to another facility or setting.

. "Enhanced services facility" means a facility that provides support and services to persons for whom acute inpatient treatment is not medically necessary.

. "Expanded community services program" means a nonsecure program of enhanced behavioral and residential support provided to long-term and residential care providers serving specifically eligible clients who would otherwise be at risk for hospitalization at state hospital geriatric units.

. "Facility" means an enhanced services facility.

. "Mental disorder" means any organic, mental, or emotional impairment that has substantial adverse effects on an individual's cognitive or volitional functions.

. "Mental health professional" means a psychiatrist, psychologist, psychiatric nurse, or social worker, and such other mental health professionals as may be defined by rules adopted by the secretary under the authority of chapter 71.05 RCW.

. "Professional person" means a mental health professional and also includes a physician, registered nurse, and such others as may be defined in rules adopted by the secretary pursuant to the provisions of this chapter.

. "Psychiatrist" means a person having a license as a physician and surgeon in this state who has in addition completed three years of graduate training in psychiatry in a program approved by the American medical association or the American osteopathic association and is certified or eligible to be certified by the American board of psychiatry and neurology.

. "Psychologist" means a person who has been licensed as a psychologist under chapter 18.83 RCW.

. "Resident" means a person admitted to an enhanced services facility.

. "Secretary" means the secretary of the department or the secretary's designee.

. "Social worker" means a person with a master's or further advanced degree from a social work educational program accredited and approved as provided in RCW 18.320.010.

. "Substance use disorder" means a cluster of cognitive, behavioral, and physiological symptoms indicating that an individual continues using the substance despite significant substance-related problems. The diagnosis of a substance use disorder is based on a pathological pattern of behaviors related to the use of the substances.

. "Substance use disorder professional" means a person certified as a substance use disorder professional by the department of health under chapter 18.205 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2448-S.SL.pdf?cite=2020%20c%20278%20§%201[2020 c 278 § 1]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1768-S.SL.pdf?cite=2019%20c%20444%20§%2014[2019 c 444 § 14]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5432-S2.SL.pdf?cite=2019%20c%20325%20§%205022[2019 c 325 § 5022]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1713-S3.SL.pdf?cite=2016%20sp.s.%20c%2029%20§%20419[2016 sp.s. c 29 § 419]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6312-S2.SL.pdf?cite=2014%20c%20225%20§%2078[2014 c 225 § 78]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5020-S.SL.pdf?cite=2011%20c%2089%20§%2011[2011 c 89 § 11]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5763-S2.SL.pdf?cite=2005%20c%20504%20§%20403[2005 c 504 § 403]; ]

== 70.97.020 - Advance directives.
A facility shall honor an advance directive that was validly executed pursuant to chapter 70.122 RCW and a mental health advance directive that was validly executed pursuant to chapter 71.32 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5763-S2.SL.pdf?cite=2005%20c%20504%20§%20404[2005 c 504 § 404]; ]

== 70.97.030 - Admission criteria.
A person, eighteen years old or older, may be admitted to an enhanced services facility if he or she meets the criteria in subsections (1) through (4) of this section:

. The person requires: (a) Daily care by or under the supervision of a mental health professional or nurse; and (b) assistance with three or more activities of daily living; and

. The person has: (a) A behavioral health disorder; (b) an organic or traumatic brain injury; or (c) a cognitive impairment that results in symptoms or behaviors requiring supervision and support services;

. The person has been assessed by the department to need the services provided in an enhanced services facility; and

. The person has been assessed as medically and psychiatrically stable and two or more of the following apply:

.. Is currently residing in a state mental hospital or psychiatric unit of a hospital and the hospital has found the person to be ready for discharge;

.. Has a history of an inability to remain medically or psychiatrically stable for more than six months;

.. Has exhibited serious challenging behaviors within the last year;

.. Has complex medication needs and an inability to manage these medications, which has affected their ability to live in the community;

.. Has a history of or likelihood of unsuccessful placements in other licensed long-term care facilities or a history of rejected applications for admission to other licensed facilities based on the person's behaviors, history, or needs;

.. Has a history of frequent or prolonged behavioral health disorder-related hospitalizations; or

.. Requires caregiving staff with training in providing behavioral supports to adults with challenging behaviors.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2448-S.SL.pdf?cite=2020%20c%20278%20§%202[2020 c 278 § 2]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1768-S.SL.pdf?cite=2019%20c%20444%20§%2015[2019 c 444 § 15]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5763-S2.SL.pdf?cite=2005%20c%20504%20§%20405[2005 c 504 § 405]; ]

== 70.97.040 - Rights of residents (as amended by 2020 c 278).
(((1)(a) Every person who is a resident of an enhanced services facility shall be entitled to all the rights set forth in this chapter, and chapters 71.05 and 70.96A RCW, and shall retain all rights not denied him or her under these chapters.

.. No person shall be presumed incompetent as a consequence of receiving an evaluation or voluntary or involuntary treatment for a mental disorder, chemical dependency disorder, or both, under this chapter, or chapter 71.05 or 70.96A RCW, or any prior laws of this state dealing with mental illness. Competency shall not be determined or withdrawn except under the provisions of chapter 10.77 or 11.88 RCW.

.. At the time of his or her treatment planning meeting, every resident of an enhanced services facility shall be given a written statement setting forth the substance of this section. The department shall by rule develop a statement and process for informing residents of their rights in a manner that is likely to be understood by the resident.

. Every resident of an enhanced services facility shall have the right to adequate care and individualized treatment.

. The provisions of this chapter shall not be construed to deny to any person treatment by spiritual means through prayer in accordance with the tenets and practices of a church or religious denomination.

. Persons receiving evaluation or treatment under this chapter shall be given a reasonable choice of an available physician or other professional person qualified to provide such services.

. The physician-patient privilege or the psychologist-client privilege shall be deemed waived in proceedings under this chapter relating to the administration of antipsychotic medications. As to other proceedings under chapter 10.77, 70.96A, or 71.05 RCW, the privileges shall be waived when a court of competent jurisdiction in its discretion determines that such waiver is necessary to protect either the detained person or the public.

. Insofar as danger to the person or others is not created, each resident of an enhanced services facility shall have, in addition to other rights not specifically withheld by law, the following rights, a list of which shall be prominently posted in all facilities, institutions, and hospitals providing such services:

.. To wear his or her own clothes and to keep and use his or her own personal possessions, except when deprivation of same is essential to protect the safety of the resident or other persons;

.. To keep and be allowed to spend a reasonable sum of his or her own money for canteen expenses and small purchases;

.. To have access to individual storage space for his or her private use;

.. To have visitors at reasonable times;

.. To have reasonable access to a telephone, both to make and receive confidential calls, consistent with an effective treatment program;

.. To have ready access to letter writing materials, including stamps, and to send and receive uncensored correspondence through the mails;

.. Not to consent to the administration of antipsychotic medications beyond the hearing conducted pursuant to RCW 71.05.215 or 71.05.217, or the performance of electroconvulsant therapy, or surgery, except emergency lifesaving surgery, unless ordered by a court under RCW 71.05.217;

.. To discuss and actively participate in treatment plans and decisions with professional persons;

.. Not to have psychosurgery performed on him or her under any circumstances;

.. To dispose of property and sign contracts unless such person has been adjudicated an incompetent in a court proceeding directed to that particular issue; and

.. To complain about rights violations or conditions and request the assistance of a mental health ombuds or representative of Washington protection and advocacy. The facility may not prohibit or interfere with a resident's decision to consult with an advocate of his or her choice.

. Nothing contained in this chapter shall prohibit a resident from petitioning by writ of habeas corpus for release.

. Nothing in this section permits any person to knowingly violate a no-contact order or a condition of an active judgment and sentence or active supervision by the department of corrections.

. A person has a right to refuse placement, except where subject to commitment, in an enhanced services facility. No person shall be denied other department services solely on the grounds that he or she has made such a refusal.

. A person has a right to appeal the decision of the department that he or she is eligible for placement at an enhanced services facility, and shall be given notice of the right to appeal in a format that is accessible to the person with instructions regarding what to do if the person wants to appeal.))Every person who is a resident of an enhanced services facility shall be entitled to all of the rights set forth in chapter 70.129 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2448-S.SL.pdf?cite=2020%20c%20278%20§%203[2020 c 278 § 3]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20179[2013 c 23 § 179]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5763-S2.SL.pdf?cite=2005%20c%20504%20§%20406[2005 c 504 § 406]; ]

== 70.97.050 - Right to refuse antipsychotic medication.
An individual served in a facility has a right to refuse antipsychotic medication.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2448-S.SL.pdf?cite=2020%20c%20278%20§%204[2020 c 278 § 4]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5763-S2.SL.pdf?cite=2005%20c%20504%20§%20407[2005 c 504 § 407]; ]

== 70.97.060 - Capacity—Supervision—Licensing—Application of state and local rules.
. [Empty]
.. The department shall not license an enhanced services facility that serves any residents under sixty-five years of age for a capacity to exceed sixteen residents.

.. The department may contract for services for the operation of enhanced services facilities only to the extent that funds are specifically provided for that purpose.

. The facility shall provide an appropriate level of supervision for the characteristics, behaviors, and legal status of the residents.

. An enhanced services facility may hold only one license but, to the extent permitted under state and federal law and medicaid requirements, a facility may be located in the same building as another licensed facility, provided that:

.. The enhanced services facility is in a location that is totally separate and discrete from the other licensed facility; and

.. The two facilities maintain separate staffing, unless an exception to this is permitted by the department in rule.

. Nursing homes under chapter 18.51 RCW, assisted living facilities under chapter 18.20 RCW, or adult family homes under chapter 70.128 RCW, that become licensed as facilities under this chapter shall be deemed to meet the applicable state and local rules, regulations, permits, and code requirements. All other facilities are required to meet all applicable state and local rules, regulations, permits, and code requirements.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2448-S.SL.pdf?cite=2020%20c%20278%20§%205[2020 c 278 § 5]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2056-S.SL.pdf?cite=2012%20c%2010%20§%2051[2012 c 10 § 51]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5763-S2.SL.pdf?cite=2005%20c%20504%20§%20408[2005 c 504 § 408]; ]

== 70.97.070 - Comprehensive assessments—Individualized behavior support plan.
. The enhanced services facility shall complete a comprehensive assessment for each resident within fourteen days of admission, and the assessments shall be repeated upon a significant change in the resident's condition or, at a minimum, every one hundred eighty days if there is no significant change in condition.

. The enhanced services facility shall develop an individualized behavior support plan for each resident based on the comprehensive assessment and any other information in the person's record. The plan shall be updated as necessary, and shall include a plan for appropriate transfer or discharge and reintegration into the community. Where the person is under the supervision of the department of corrections, the facility shall collaborate with the department of corrections to maximize treatment outcomes and reduce the likelihood of reoffense.

. The plan shall maximize the opportunities for independence, recovery, employment, the resident's participation in service planning decisions, and collaboration with peer-supported services, and provide for care and services in the least restrictive manner appropriate to the individual resident, and, where relevant, to any court orders with which the resident must comply.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2448-S.SL.pdf?cite=2020%20c%20278%20§%206[2020 c 278 § 6]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5763-S2.SL.pdf?cite=2005%20c%20504%20§%20409[2005 c 504 § 409]; ]

== 70.97.080 - Staffing levels—Staff credentials and training—Background checks.
. An enhanced services facility must have sufficient numbers of staff with the appropriate credentials and training to provide residents with the following appropriate care and disorder support:

.. Behavioral health support;

.. Medication services;

.. Assistance with the activities of daily living;

.. Skilled nursing and support to acquire medical and behavioral health disorder services from local community providers;

.. Dietary services; and

.. Supervision.

. Where an enhanced services facility specializes in medically fragile persons with behavioral health conditions, the on-site staff must include at least one licensed nurse twenty-four hours per day. The nurse must be a registered nurse for at least sixteen hours per day. If the nurse is not a registered nurse, a registered nurse or a doctor must be on call during the remaining eight hours.

. Any employee or other individual who will have unsupervised access to vulnerable adults must successfully pass a background inquiry check.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2448-S.SL.pdf?cite=2020%20c%20278%20§%207[2020 c 278 § 7]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5763-S2.SL.pdf?cite=2005%20c%20504%20§%20410[2005 c 504 § 410]; ]

== 70.97.090 - Facilities exempted.
This chapter does not apply to the following residential facilities:

. Nursing homes licensed under chapter 18.51 RCW;

. Assisted living facilities licensed under chapter 18.20 RCW;

. Adult family homes licensed under chapter 70.128 RCW;

. Facilities approved and certified under chapter 71A.22 RCW;

. Residential treatment facilities licensed under chapter 71.12 RCW; and

. Hospitals licensed under chapter 70.41 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2056-S.SL.pdf?cite=2012%20c%2010%20§%2052[2012 c 10 § 52]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5763-S2.SL.pdf?cite=2005%20c%20504%20§%20411[2005 c 504 § 411]; ]

== 70.97.100 - Licensing requirements—Information available to public, residents, families.
. The department shall establish licensing rules for enhanced services facilities to serve the populations defined in this chapter.

. No person or public or private agency may operate or maintain an enhanced services facility without a license, which must be renewed annually.

. A licensee shall have the following readily accessible and available for review by the department, residents, families of residents, and the public:

.. Its license to operate and a copy of the department's most recent inspection report and any recent complaint investigation reports issued by the department;

.. Its written policies and procedures for all care and services provided directly or indirectly by the facility; and

.. The department's toll-free complaint number, which shall also be posted in a clearly visible place and manner.

. Enhanced services facilities shall maintain a grievance procedure that meets the requirements of rules established by the department.

. No facility shall discriminate or retaliate in any manner against a resident or employee because the resident, employee, or any other person made a complaint or provided information to the department, the long-term care ombuds, Washington protection and advocacy system, or a behavioral health ombuds.

. Each enhanced services facility will post in a prominent place in a common area a notice by the Washington protection and advocacy system providing contact information.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2448-S.SL.pdf?cite=2020%20c%20278%20§%208[2020 c 278 § 8]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20180[2013 c 23 § 180]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5763-S2.SL.pdf?cite=2005%20c%20504%20§%20412[2005 c 504 § 412]; ]

== 70.97.110 - Enforcement authority—Penalties, sanctions.
. In any case in which the department finds that a licensee of a facility, or any partner, officer, director, owner of five percent or more of the assets of the facility, or managing employee failed or refused to comply with the requirements of this chapter or the rules established under them, the department may take any or all of the following actions:

.. Suspend, revoke, or refuse to issue or renew a license;

.. Order stop placement; or

.. Assess civil monetary penalties.

. The department may suspend, revoke, or refuse to renew a license, assess civil monetary penalties, or both, in any case in which it finds that the licensee of a facility, or any partner, officer, director, owner of five percent or more of the assets of the facility, or managing employee:

.. Operated a facility without a license or under a revoked or suspended license;

.. Knowingly or with reason to know made a false statement of a material fact in the license application or any data attached thereto, or in any matter under investigation by the department;

.. Refused to allow representatives or agents of the department to inspect all books, records, and files required to be maintained or any portion of the premises of the facility;

.. Willfully prevented, interfered with, or attempted to impede in any way the work of any duly authorized representative of the department and the lawful enforcement of any provision of this chapter;

.. Willfully prevented or interfered with any representative of the department in the preservation of evidence of any violation of any of the provisions of this chapter or of the rules adopted under it; or

.. Failed to pay any civil monetary penalty assessed by the department under this chapter within ten days after the assessment becomes final.

. [Empty]
.. Civil penalties collected under this chapter shall be deposited into a special fund administered by the department.

.. Civil monetary penalties, if imposed, may be assessed and collected, with interest, for each day the facility is or was out of compliance. Civil monetary penalties shall not exceed three thousand dollars per day. Each day upon which the same or a substantially similar action occurs is a separate violation subject to the assessment of a separate penalty.

. The department may use the civil penalty monetary fund for the protection of the health or property of residents of facilities found to be deficient including:

.. Payment for the cost of relocation of residents to other facilities;

.. Payment to maintain operation of a facility pending correction of deficiencies or closure; and

.. Reimbursement of a resident for personal funds or property loss.

. [Empty]
.. The department may issue a stop placement order on a facility, effective upon oral or written notice, when the department determines:

... The facility no longer substantially meets the requirements of this chapter; and

... The deficiency or deficiencies in the facility:

(A) Jeopardizes the health and safety of the residents; or

(B) Seriously limits the facility's capacity to provide adequate care.

.. When the department has ordered a stop placement, the department may approve a readmission to the facility from a hospital, residential treatment facility, or crisis intervention facility when the department determines the readmission would be in the best interest of the individual seeking readmission.

. If the department determines that an emergency exists and resident health and safety is immediately jeopardized as a result of a facility's failure or refusal to comply with this chapter, the department may summarily suspend the facility's license and order the immediate closure of the facility, or the immediate transfer of residents, or both.

. If the department determines that the health or safety of the residents is immediately jeopardized as a result of a facility's failure or refusal to comply with requirements of this chapter, the department may appoint temporary management to:

.. Oversee the operation of the facility; and

.. Ensure the health and safety of the facility's residents while:

... Orderly closure of the facility occurs; or

... The deficiencies necessitating temporary management are corrected.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5763-S2.SL.pdf?cite=2005%20c%20504%20§%20413[2005 c 504 § 413]; ]

== 70.97.120 - Enforcement orders—Hearings.
. All orders of the department denying, suspending, or revoking the license or assessing a monetary penalty shall become final twenty days after the same has been served upon the applicant or licensee unless a hearing is requested.

. All orders of the department imposing stop placement, temporary management, emergency closure, emergency transfer, or summary license suspension shall be effective immediately upon notice, pending any hearing.

. Subject to the requirements of subsection (2) of this section, all hearings under this chapter and judicial review of such determinations shall be in accordance with the administrative procedure act, chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5763-S2.SL.pdf?cite=2005%20c%20504%20§%20414[2005 c 504 § 414]; ]

== 70.97.130 - Unlicensed operation—Application of consumer protection act.
Operation of a facility without a license in violation of this chapter and discrimination against medicaid recipients is a matter vitally affecting the public interest for the purpose of applying the consumer protection act, chapter 19.86 RCW. Operation of an enhanced services facility without a license in violation of this chapter is not reasonable in relation to the development and preservation of business. Such a violation is an unfair or deceptive act in trade or commerce and an unfair method of competition for the purpose of applying the consumer protection act, chapter 19.86 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5763-S2.SL.pdf?cite=2005%20c%20504%20§%20415[2005 c 504 § 415]; ]

== 70.97.140 - Unlicensed operation—Criminal penalty.
A person operating or maintaining a facility without a license under this chapter is guilty of a misdemeanor and each day of a continuing violation after conviction shall be considered a separate offense.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5763-S2.SL.pdf?cite=2005%20c%20504%20§%20416[2005 c 504 § 416]; ]

== 70.97.150 - Unlicensed operation—Injunction or other remedies.
Notwithstanding the existence or use of any other remedy, the department may, in the manner provided by law, maintain an action in the name of the state for an injunction, civil penalty, or other process against a person to restrain or prevent the operation or maintenance of a facility without a license issued under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5763-S2.SL.pdf?cite=2005%20c%20504%20§%20417[2005 c 504 § 417]; ]

== 70.97.160 - Inspections.
. The department shall make or cause to be made at least one inspection of each facility prior to licensure and an unannounced full inspection of facilities at least once every eighteen months. The statewide average interval between full facility inspections must be fifteen months.

. Any duly authorized officer, employee, or agent of the department may enter and inspect any facility at any time to determine that the facility is in compliance with this chapter and applicable rules, and to enforce any provision of this chapter. Complaint inspections shall be unannounced and conducted in such a manner as to ensure maximum effectiveness. No advance notice shall be given of any inspection unless authorized or required by federal law.

. During inspections, the facility must give the department access to areas, materials, and equipment used to provide care or support to residents, including resident and staff records, accounts, and the physical premises, including the buildings, grounds, and equipment. The department has the authority to privately interview the provider, staff, residents, and other individuals familiar with resident care and service plans.

. Any public employee giving advance notice of an inspection in violation of this section shall be suspended from all duties without pay for a period of not less than five nor more than fifteen days.

. The department shall prepare a written report describing the violations found during an inspection, and shall provide a copy of the inspection report to the facility.

. The facility shall develop a written plan of correction for any violations identified by the department and provide a plan of correction to the department within ten working days from the receipt of the inspection report.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2448-S.SL.pdf?cite=2020%20c%20278%20§%209[2020 c 278 § 9]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5763-S2.SL.pdf?cite=2005%20c%20504%20§%20418[2005 c 504 § 418]; ]

== 70.97.170 - Persons eligible for admittance.
The facility shall only admit individuals:

. Who are over the age of eighteen;

. Who meet the resident eligibility requirements described in RCW 70.97.030; and

. Whose needs the facility can safely and appropriately meet through qualified and trained staff, services, equipment, security, and building design.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5763-S2.SL.pdf?cite=2005%20c%20504%20§%20419[2005 c 504 § 419]; ]

== 70.97.180 - Services of qualified professional.
If the facility does not employ a qualified professional able to furnish needed services, the facility must have a written contract with a qualified professional or agency outside the facility to furnish the needed services.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5763-S2.SL.pdf?cite=2005%20c%20504%20§%20420[2005 c 504 § 420]; ]

== 70.97.190 - Notice of change of ownership or management.
At least sixty days before the effective date of any change of ownership, or change of management of a facility, the current operating entity must provide written notification about the proposed change separately and in writing, to the department, each resident of the facility, or the resident's guardian or representative.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5763-S2.SL.pdf?cite=2005%20c%20504%20§%20421[2005 c 504 § 421]; ]

== 70.97.200 - Recordkeeping—Compliance with state, federal regulations—Health care information releases.
The facility shall:

. Maintain adequate resident records to enable the provision of necessary behavior support, care, and services and to respond appropriately in emergency situations;

. Comply with all state and federal requirements related to documentation, confidentiality, and information sharing, including chapters 10.77, 70.02, 70.24, and 71.05 RCW; and

. Where possible, obtain signed releases of information designating the department, the facility, and the department of corrections where the person is under its supervision, as recipients of health care information.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2448-S.SL.pdf?cite=2020%20c%20278%20§%2010[2020 c 278 § 10]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5763-S2.SL.pdf?cite=2005%20c%20504%20§%20422[2005 c 504 § 422]; ]

== 70.97.210 - Standards for fire protection.
. Standards for fire protection and the enforcement thereof, with respect to all facilities licensed under this chapter, are the responsibility of the chief of the Washington state patrol, through the director of fire protection, who must adopt recognized standards as applicable to facilities for the protection of life against the cause and spread of fire and fire hazards. If the facility to be licensed meets with the approval of the chief of the Washington state patrol, through the director of fire protection, the director of fire protection must submit to the department a written report approving the facility with respect to fire protection before a full license can be issued. The chief of the Washington state patrol, through the director of fire protection, shall conduct an unannounced full inspection of facilities at least once every eighteen months. The statewide average interval between full facility inspections must be fifteen months.

. Inspections of facilities by local authorities must be consistent with the requirements adopted by the chief of the Washington state patrol, through the director of fire protection. Findings of a serious nature must be coordinated with the department and the chief of the Washington state patrol, through the director of fire protection, for determination of appropriate actions to ensure a safe environment for residents. The chief of the Washington state patrol, through the director of fire protection, has exclusive authority to determine appropriate corrective action under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5763-S2.SL.pdf?cite=2005%20c%20504%20§%20423[2005 c 504 § 423]; ]

== 70.97.220 - Exemption from liability.
No facility providing care and behavior support for individuals placed in a facility, or agency licensing or placing residents in a facility, acting in the course of its duties, shall be civilly or criminally liable for performing its duties under this chapter, provided that such duties were performed in good faith and without gross negligence.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2448-S.SL.pdf?cite=2020%20c%20278%20§%2011[2020 c 278 § 11]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5763-S2.SL.pdf?cite=2005%20c%20504%20§%20424[2005 c 504 § 424]; ]

== 70.97.230 - Rules for implementation of chapter.
. The secretary shall adopt rules to implement this chapter.

. Such rules shall at the minimum: (a) Promote safe treatment and necessary care of individuals residing in the facility and provide for safe and clean conditions; (b) establish licensee qualifications, licensing and enforcement, and license fees sufficient to cover the cost of licensing and enforcement.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5763-S2.SL.pdf?cite=2005%20c%20504%20§%20425[2005 c 504 § 425]; ]

== 70.97.800 - Request for proposal.
To the extent that funds are specifically appropriated for this purpose, the department must issue a request for a proposal for enhanced services facility services by June 1, 2014, and complete the procurement process by January 1, 2015.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5732-S2.SL.pdf?cite=2013%20c%20338%20§%203[2013 c 338 § 3]; ]

