= 70.185 - Rural and underserved areas—Health care professional recruitment and retention.
:toc:

== 70.185.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Department" means the department of health.

. "Health care professional recruitment and retention strategic plan" means a plan developed by the participant and includes identification of health care personnel needs of the community, how these professionals will be recruited and retained in the community following recruitment.

. "Institutions of higher education" means educational institutions as defined in RCW 28B.10.016.

. "Local administrator" means an individual or organization representing the participant who may enter into legal agreements on behalf of the participant.

. "Participant" means communities, counties, and regions that serve as a health care catchment area where the project site is located.

. "Project" means the community-based retention and recruitment project.

. "Project site" means a site selected to participate in the project.

. "Secretary" means the secretary of health.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1960-S.SL.pdf?cite=1991%20c%20332%20§%207[1991 c 332 § 7]; ]

== 70.185.020 - Statewide recruitment and retention clearinghouse.
The department, in consultation with appropriate private and public entities, shall establish a health professional recruitment and retention clearinghouse. The clearinghouse shall:

. Inventory and classify the current public and private health professional recruitment and retention efforts;

. Identify recruitment and retention program models having the greatest success rates;

. Identify recruitment and retention program gaps;

. Work with existing recruitment and retention programs to better coordinate statewide activities and to make such services more widely known and broadly available;

. Provide general information to communities, health care facilities, and others about existing available programs;

. Work in cooperation with private and public entities to develop new recruitment and retention programs;

. Identify needed recruitment and retention programming for state institutions, county public health departments and districts, county human service agencies, and other entities serving substantial numbers of public pay and charity care patients, and may provide to these entities when they have been selected as participants necessary recruitment and retention assistance including:

.. Assistance in establishing or enhancing recruitment of health care professionals;

.. Recruitment on behalf of sites unable to establish their own recruitment program; and

.. Assistance with retention activities when practitioners of the health professional loan repayment and scholarship program authorized by *chapter 18.150 RCW are present in the practice setting.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1960-S.SL.pdf?cite=1991%20c%20332%20§%208[1991 c 332 § 8]; ]

== 70.185.030 - Community-based recruitment and retention projects—Duties of department.
. The department may, subject to funding, establish community-based recruitment and retention project sites to provide financial and technical assistance to participating communities. The goal of the project is to help assure the availability of health care providers in rural and underserved urban areas of Washington state.

. Administrative costs necessary to implement this project shall be kept at a minimum to insure the maximum availability of funds for participants.

. The secretary may contract with third parties for services necessary to carry out activities to implement this chapter where this will promote economy, avoid duplication of effort, and make the best use of available expertise.

. The secretary may apply for, receive, and accept gifts and other payments, including property and service, from any governmental or other public or private entity or person, and may make arrangements as to the use of these receipts, including the undertaking of special studies and other projects related to the delivery of health care in rural areas.

. In designing and implementing the project the secretary shall coordinate and avoid duplication with similar federal programs and with the Washington rural health system project as authorized under chapter 70.175 RCW to consolidate administrative duties and reduce costs.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20273[1993 c 492 § 273]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1960-S.SL.pdf?cite=1991%20c%20332%20§%209[1991 c 332 § 9]; ]

== 70.185.040 - Rules.
The department shall adopt rules consistent with this chapter to carry out the purpose of this chapter. All rules shall be adopted in accordance with chapter 34.05 RCW. All rules and procedures adopted by the department shall minimize paperwork and compliance requirements for participants and should not be complex in nature so as to serve as a barrier or disincentive for prospective participants applying for the project.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1960-S.SL.pdf?cite=1991%20c%20332%20§%2010[1991 c 332 § 10]; ]

== 70.185.050 - Secretary's powers and duties.
The secretary shall have the following powers and duties:

. To design the project application and selection process, including a program to advertise the project to rural communities and encourage prospective applicants to apply. Subject to funding, project sites shall be selected that are eligible to receive funding. Funding shall be used to hire consultants and perform other activities necessary to meet participant requirements under this chapter. The secretary shall require at least fifty percent matching funds or in-kind contributions from participants. In considering selection of participants eligible for seed grant funding, the secretary should consider project sites where (a) existing access to health care is severely inadequate, (b) recruitment and retention problems have been chronic, (c) the community is in need of primary care practitioners, or (d) the community has unmet health care needs for specific target populations;

. To design acceptable health care professional recruitment and retention strategic plans, and to serve as a general resource to participants in the planning, administration, and evaluation of project sites;

. To assess and approve strategic plans developed by participants, including an assessment of the technical and financial feasibility of implementing the plan and whether adequate local support for the plan is demonstrated;

. To identify existing private and public resources that may serve as eligible consultants, identify technical assistance resources for communities in the project, create a register of public and private technical resource services available, and provide the register to participants. The secretary shall screen consultants to determine their qualifications prior to including them on the register;

. To work with other state agencies, institutions of higher education, and other public and private organizations to coordinate technical assistance services for participants;

. To administer available funds for community use while participating in the project and establish procedures to assure accountability in the use of seed grant funds by participants;

. To define data and other minimum requirements for adequate evaluation of projects and to develop and implement an overall monitoring and evaluation mechanism for the projects;

. To act as facilitator for multiple applicants and entrants to the project;

. To report to the appropriate legislative committees and others from time to time on the progress of the projects including the identification of statutory and regulatory barriers to successful completion of rural health care delivery goals and an ongoing evaluation of the project.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1960-S.SL.pdf?cite=1991%20c%20332%20§%2011[1991 c 332 § 11]; ]

== 70.185.060 - Duties and responsibilities of participating communities.
The duties and responsibilities of participating communities shall include:

. To involve major health care providers, businesses, public officials, and other community leaders in project design, administration, and oversight;

. To identify an individual or organization to serve as the local administrator of the project. The secretary may require the local administrator to maintain acceptable accountability of seed grant funding;

. To coordinate and avoid duplication of public health and other health care services;

. To assess and analyze community health care professional needs;

. To write a health care professional recruitment and retention strategic plan;

. To screen and contract with consultants for technical assistance if the project site was selected to receive funding and assistance is needed;

. To monitor and evaluate the project in an ongoing manner;

. To provide data and comply with other requirements of the administrator that are intended to evaluate the effectiveness of the projects;

. To assure that specific populations with unmet health care needs have access to services.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1960-S.SL.pdf?cite=1991%20c%20332%20§%2012[1991 c 332 § 12]; ]

== 70.185.070 - Cooperation of state agencies.
. The secretary may call upon other agencies of the state to provide available information to assist the secretary in meeting the responsibilities under this chapter. This information shall be supplied as promptly as circumstances permit.

. The secretary may call upon other state agencies including institutions of higher education as authorized under Titles 28A and 28B RCW to identify and coordinate the delivery of technical assistance services to participants in meeting the responsibilities of this chapter. The state agencies, vocational-technical institutions, and institutions of higher education shall cooperate and provide technical assistance to the secretary to the extent that current funding for these entities permits.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1960-S.SL.pdf?cite=1991%20c%20332%20§%2013[1991 c 332 § 13]; ]

== 70.185.080 - Participants authorized to contract—Penalty—Secretary and state exempt from liability.
. Participants are authorized to use funding granted to them by the secretary for the purpose of contracting for technical assistance services. Participants shall use only consultants identified by the secretary for consulting services unless the participant can show that an alternative consultant is qualified to provide technical assistance and is approved by the secretary. Adequate records shall be kept by the participant showing project site expenditures from grant moneys. Inappropriate use of grant funding is a gross misdemeanor and shall incur the penalties under chapter 9A.20 RCW.

. In providing a list of qualified consultants the secretary and the state shall not be held responsible for assuring qualifications of consultants and shall be held harmless for the actions of consultants. Furthermore, the secretary and the state shall not be held liable for the failure of participants to meet contractual obligations established in connection with project participation.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1960-S.SL.pdf?cite=1991%20c%20332%20§%2014[1991 c 332 § 14]; ]

== 70.185.090 - Community contracted student educational positions. (Effective until July 1, 2022.)
. The department may develop a mechanism for underserved rural or urban communities to contract with education and training programs for student positions above the full time equivalent lids. The goal of this program is to provide additional capacity, educating students who will practice in underserved communities.

. Eligible education and training programs are those programs approved by the department that lead to eligibility for a credential as a credentialed health care professional. Eligible professions are those licensed under chapters 18.36A, 18.57, 18.57A, 18.71, and 18.71A RCW and advanced registered nurse practitioners and certified nurse midwives licensed under *chapter 18.88 RCW, and may include other providers identified as needed in the health personnel resource plan.

. Students participating in the community contracted educational positions shall meet all applicable educational program requirements and provide assurances, acceptable to the community, that they will practice in the sponsoring community following completion of education and necessary licensure.

. Participants in the program incur an obligation to repay any contracted funds with interest set by state law, unless they serve at least three years in the sponsoring community.

. The department may provide funds to communities for use in contracting.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20274[1993 c 492 § 274]; ]

== 70.185.100 - Contracts with area health education centers.
The secretary may establish and contract with area health education centers in the eastern and western parts of the state. Consistent with the recruitment and retention objectives of this chapter, the centers shall provide or facilitate the provision of health professional educational and continuing education programs that strengthen the delivery of primary health care services in rural and medically underserved urban areas of the state. The center shall assist in the development and operation of health personnel recruitment and retention programs that are consistent with activities authorized under this chapter. The centers shall further provide technical expertise in the development of well managed health care delivery systems in rural Washington consistent with the goals and objectives of chapter 492, Laws of 1993.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20275[1993 c 492 § 275]; ]

== 70.185.900 - Application to scope of practice—Captions not law—1991 c 332.
See notes following RCW 18.130.010.

[ ]

