= 70.125 - Victims of sexual assault act.
:toc:

== 70.125.010 - Short title.
This chapter may be known and cited as the Victims of Sexual Assault Act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c219.pdf?cite=1979%20ex.s.%20c%20219%20§%201[1979 ex.s. c 219 § 1]; ]

== 70.125.020 - Findings.
The legislature hereby finds and declares that:

. Sexual assault is a serious crime in society, affecting a large number of children, women, and men each year;

. Efforts over many years to distribute information and collect data have demonstrated the incidence of sexual assault that continues to impact communities, families, and individuals;

. Over the past three decades, law enforcement, prosecutors, medical professionals, educators, mental health providers, public health professionals, and victim advocates have benefited from a commitment to training and learning regarding appropriate responses to and services for victims of sexual assault;

. This same effort has resulted in increased public awareness of sexual assault and its impact on communities, families, and individuals;

. Law enforcement, prosecutors, medical professionals, educators, mental health providers, public health professionals, and victim advocates should continue to work closely and collaboratively to improve responses to and services for victims of sexual assault;

. The physical, emotional, financial, and psychological needs of victims and their families are particularly well-served by timely and effective services provided in local communities; and

. Persons who are victims of sexual assault benefit directly from continued public awareness and education, prosecutions of offenders, a criminal justice system which treats them in a humane manner, and access to victim-centered, culturally relevant services.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6100-S.SL.pdf?cite=2012%20c%2029%20§%209[2012 c 29 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c219.pdf?cite=1979%20ex.s.%20c%20219%20§%202[1979 ex.s. c 219 § 2]; ]

== 70.125.030 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Community sexual assault program" means a community-based social service agency that is qualified to provide and provides core services to victims of sexual assault.

. "Core services" means those services that are victim-centered community-based advocacy responses to alleviate the impact of sexual assault, as delineated in the Washington state sexual assault services plan of 1995 and its subsequent revisions.

. "Department" means the department of commerce.

. "Law enforcement agencies" means police and sheriff's departments and tribal law enforcement departments or agencies of this state.

. "Personal representative" means a friend, relative, attorney, or employee or volunteer from a community sexual assault program or specialized treatment service provider.

. "Services for underserved populations" means culturally relevant victim-centered community-based advocacy responses to alleviate the impact of sexual assault, as delineated in the Washington state sexual assault services plan of 1995 and its subsequent revisions.

. "Sexual assault" means one or more of the following:

.. Rape or rape of a child;

.. Assault with intent to commit rape or rape of a child;

.. Incest or indecent liberties;

.. Child molestation;

.. Sexual misconduct with a minor;

.. Custodial sexual misconduct;

.. Crimes with a sexual motivation;

.. Sexual exploitation or commercial sex abuse of a minor;

.. Promoting prostitution; or

.. An attempt to commit any of the aforementioned offenses.

. "Specialized services" means those services intended to alleviate the impact of sexual assault, as delineated in the Washington state sexual assault services plan of 1995 and its subsequent revisions.

. "Victim" means any person who suffers physical, emotional, financial, and psychological impact as a proximate result of a sexual assault.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6100-S.SL.pdf?cite=2012%20c%2029%20§%2010[2012 c 29 § 10]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2009%20c%20565%20§%2050[2009 c 565 § 50]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2750.SL.pdf?cite=2000%20c%2054%20§%201[2000 c 54 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5234-S.SL.pdf?cite=1999%20c%2045%20§%206[1999 c 45 § 6]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2579-S.SL.pdf?cite=1996%20c%20123%20§%206[1996 c 123 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c145.pdf?cite=1988%20c%20145%20§%2019[1988 c 145 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c219.pdf?cite=1979%20ex.s.%20c%20219%20§%203[1979 ex.s. c 219 § 3]; ]

== 70.125.060 - Personal representative may accompany victim during treatment or proceedings.
If the victim of a sexual assault so desires, a personal representative of the victim's choice may accompany the victim to the hospital or other health care facility, and to proceedings concerning the alleged assault, including police and prosecution interviews and court proceedings.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c219.pdf?cite=1979%20ex.s.%20c%20219%20§%206[1979 ex.s. c 219 § 6]; ]

== 70.125.065 - Records of community sexual assault program and underserved populations provider not available as part of discovery—Exceptions.
Records maintained by a community sexual assault program and underserved populations provider shall not be made available to any defense attorney as part of discovery in a sexual assault case unless:

. A written pretrial motion is made by the defendant to the court stating that the defendant is requesting discovery of the community sexual assault program or underserved populations provider records;

. The written motion is accompanied by an affidavit or affidavits setting forth specifically the reasons why the defendant is requesting discovery of the community sexual assault program or underserved populations provider records;

. The court reviews the community sexual assault program or underserved populations provider records in camera to determine whether the community sexual assault program or underserved populations provider records are relevant and whether the probative value of the records is outweighed by the victim's privacy interest in the confidentiality of such records taking into account the further trauma that may be inflicted upon the victim by the disclosure of the records to the defendant; and

. The court enters an order stating whether the records or any part of the records are discoverable and setting forth the basis for the court's findings.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6100-S.SL.pdf?cite=2012%20c%2029%20§%2011[2012 c 29 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c145.pdf?cite=1981%20c%20145%20§%209[1981 c 145 § 9]; ]

== 70.125.110 - Rights of sexual assault survivors.
. In addition to all other rights provided in law, a sexual assault survivor has the right to:

.. Receive a medical forensic examination at no cost;

.. Consult with a sexual assault survivor's advocate during any medical evidentiary examination and during any interview by law enforcement officers, prosecuting attorneys, or defense attorneys, unless an advocate cannot be summoned in a timely manner, and regardless of whether a survivor has waived the right in a previous examination or interview;

.. Be informed, upon the request of a survivor, of when the forensic analysis of his or her sexual assault kit and other related physical evidence will be or was completed, the results of the forensic analysis, and whether the analysis yielded a DNA profile and match, provided that the disclosure is made at an appropriate time so as to not impede or compromise an ongoing investigation;

.. Receive notice prior to the destruction or disposal of his or her sexual assault kit;

.. Receive a copy of the police report related to the investigation without charge; and

.. Review his or her statement before law enforcement refers a case to the prosecuting attorney.

. A sexual assault survivor retains all the rights of this section regardless of whether the survivor agrees to participate in the criminal justice system and regardless of whether the survivor agrees to receive a forensic examination to collect evidence.

. If a survivor is denied any right enumerated in subsection (1) of this section, he or she may seek an order directing compliance by the relevant party or parties by filing a petition in the superior court in the county in which the sexual assault occurred and providing notice of such petition to the relevant party or parties. Compliance with the right is the sole remedy available to the survivor. The court shall expedite consideration of a petition filed under this subsection.

. Nothing contained in this section may be construed to provide grounds for error in favor of a criminal defendant in a criminal proceeding. Except in the circumstances as provided in subsection (3) of this section, this section does not grant a new cause of action or remedy against the state, its political subdivisions, law enforcement agencies, or prosecuting attorneys. The failure of a person to make a reasonable effort to protect or adhere to the rights enumerated in this section may not result in civil liability against that person. This section does not limit other civil remedies or defenses of the sexual assault survivor or the offender.

. For the purposes of this section:

.. "Law enforcement officer" means a general authority Washington peace officer, as defined in RCW 10.93.020, or any person employed by a private police agency at a public school as described in RCW 28A.150.010 or an institution of higher education, as defined in RCW 28B.10.016.

.. "Sexual assault survivor" means any person who is a victim, as defined in RCW 7.69.020, of sexual assault. However, if a victim is incapacitated, deceased, or a minor, sexual assault survivor also includes any lawful representative of the victim, including a parent, guardian, spouse, or other designated representative, unless the person is an alleged perpetrator or suspect.

.. "Sexual assault survivor's advocate" means any person who is defined in RCW 5.60.060 as a sexual assault advocate, or a crime victim advocate.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1166-S2.SL.pdf?cite=2019%20c%2093%20§%209[2019 c 93 § 9]; ]

