= 70.170 - Health data and charity care.
:toc:

== 70.170.010 - Intent.
. The legislature finds and declares that there is a need for health care information that helps the general public understand health care issues and how they can be better consumers and that is useful to purchasers, payers, and providers in making health care choices and negotiating payments. It is the purpose and intent of this chapter to establish a hospital data collection, storage, and retrieval system which supports these data needs and which also provides public officials and others engaged in the development of state health policy the information necessary for the analysis of health care issues.

. The legislature finds that rising health care costs and access to health care services are of vital concern to the people of this state. It is, therefore, essential that strategies be explored that moderate health care costs and promote access to health care services.

. The legislature further finds that access to health care is among the state's goals and the provision of such care should be among the purposes of health care providers and facilities. Therefore, the legislature intends that charity care requirements and related enforcement provisions for hospitals be explicitly established.

. The lack of reliable statistical information about the delivery of charity care is a particular concern that should be addressed. It is the purpose and intent of this chapter to require hospitals to provide, and report to the state, charity care to persons with acute care needs, and to have a state agency both monitor and report on the relative commitment of hospitals to the delivery of charity care services, as well as the relative commitment of public and private purchasers or payers to charity care funding.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20501[1989 1st ex.s. c 9 § 501]; ]

== 70.170.020 - Definitions.
As used in this chapter:

. "Department" means department of health.

. "Hospital" means any health care institution which is required to qualify for a license under *RCW 70.41.020(7); or as a psychiatric hospital under chapter 71.12 RCW.

. "Secretary" means secretary of health.

. "Charity care" means medically necessary hospital health care rendered to indigent persons when third-party coverage, if any, has been exhausted, to the extent that the persons are unable to pay for the care or to pay deductibles or coinsurance amounts required by a third-party payer, as determined by the department.

. "Third-party coverage" means an obligation on the part of an insurance company, health care service contractor, health maintenance organization, group health plan, government program, tribal health benefits, or health care sharing ministry as defined in 26 U.S.C. Sec. 5000A to pay for the care of covered patients and services, and may include settlements, judgments, or awards actually received related to the negligent acts of others which have resulted in the medical condition for which the patient has received hospital health care service. The pendency of such settlements, judgments, or awards must not stay hospital obligations to consider an eligible patient for charity care.

. "Sliding fee schedule" means a hospital-determined, publicly available schedule of discounts to charges for persons deemed eligible for charity care; such schedules shall be established after consideration of guidelines developed by the department.

. "Special studies" means studies which have not been funded through the department's biennial or other legislative appropriations.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6273-S.SL.pdf?cite=2018%20c%20263%20§%201[2018 c 263 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1107-S.SL.pdf?cite=1995%20c%20269%20§%202203[1995 c 269 § 2203]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20502[1989 1st ex.s. c 9 § 502]; ]

== 70.170.050 - Requested studies—Costs.
The department shall have the authority to respond to requests of others for special studies or analysis. The department may require such sponsors to pay any or all of the reasonable costs associated with such requests that might be approved, but in no event may costs directly associated with any such special study be charged against the funds generated by the assessment authorized under RCW 70.170.080.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20505[1989 1st ex.s. c 9 § 505]; ]

== 70.170.060 - Charity care—Prohibited and required hospital practices and policies—Rules—Notice of charity care availability—Department to monitor and report.
. No hospital or its medical staff shall adopt or maintain admission practices or policies which result in:

.. A significant reduction in the proportion of patients who have no third-party coverage and who are unable to pay for hospital services;

.. A significant reduction in the proportion of individuals admitted for inpatient hospital services for which payment is, or is likely to be, less than the anticipated charges for or costs of such services; or

.. The refusal to admit patients who would be expected to require unusually costly or prolonged treatment for reasons other than those related to the appropriateness of the care available at the hospital.

. No hospital shall adopt or maintain practices or policies which would deny access to emergency care based on ability to pay. No hospital which maintains an emergency department shall transfer a patient with an emergency medical condition or who is in active labor unless the transfer is performed at the request of the patient or is due to the limited medical resources of the transferring hospital. Hospitals must follow reasonable procedures in making transfers to other hospitals including confirmation of acceptance of the transfer by the receiving hospital.

. The department shall develop definitions by rule, as appropriate, for subsection (1) of this section and, with reference to federal requirements, subsection (2) of this section. The department shall monitor hospital compliance with subsections (1) and (2) of this section. The department shall report individual instances of possible noncompliance to the state attorney general or the appropriate federal agency.

. The department shall establish and maintain by rule, consistent with the definition of charity care in RCW 70.170.020, the following:

.. Uniform procedures, data requirements, and criteria for identifying patients receiving charity care;

.. A definition of residual bad debt including reasonable and uniform standards for collection procedures to be used in efforts to collect the unpaid portions of hospital charges that are the patient's responsibility.

. For the purpose of providing charity care, each hospital shall develop, implement, and maintain a charity care policy which, consistent with subsection (1) of this section, shall enable people below the federal poverty level access to appropriate hospital-based medical services, and a sliding fee schedule for determination of discounts from charges for persons who qualify for such discounts by January 1, 1990. The department shall develop specific guidelines to assist hospitals in setting sliding fee schedules required by this section. All persons with family income below one hundred percent of the federal poverty standard shall be deemed charity care patients for the full amount of hospital charges, except to the extent the patient has third-party coverage for those charges.

. Each hospital shall post and prominently display notice of charity care availability. Notice must be posted in all languages spoken by more than ten percent of the population of the hospital service area. Notice must be displayed in at least the following locations:

.. Areas where patients are admitted or registered;

.. Emergency departments, if any; and

.. Financial service or billing areas where accessible to patients.

. Current versions of the hospital's charity care policy, a plain language summary of the hospital's charity care policy, and the hospital's charity care application form must be available on the hospital's website. The summary and application form must be available in all languages spoken by more than ten percent of the population of the hospital service area.

. [Empty]
.. All hospital billing statements and other written communications concerning billing or collection of a hospital bill by a hospital must include the following or a substantially similar statement prominently displayed on the first page of the statement in both English and the second most spoken language in the hospital's service area:

You may qualify for free care or a discount on your hospital bill, whether or not you have insurance. Please contact our financial assistance office at [website] and [phone number].

.. Nothing in (a) of this subsection requires any hospital to alter any preprinted hospital billing statements existing as of October 1, 2018.

. Hospital obligations under federal and state laws to provide meaningful access for limited English proficiency and non-English-speaking patients apply to information regarding billing and charity care. Hospitals shall develop standardized training programs on the hospital's charity care policy and use of interpreter services, and provide regular training for appropriate staff, including the relevant and appropriate staff who perform functions relating to registration, admissions, or billing.

. Each hospital shall make every reasonable effort to determine:

.. The existence or nonexistence of private or public sponsorship which might cover in full or part the charges for care rendered by the hospital to a patient;

.. The annual family income of the patient as classified under federal poverty income guidelines as of the time the health care services were provided, or at the time of application for charity care if the application is made within two years of the time of service, the patient has been making good faith efforts towards payment of health care services rendered, and the patient demonstrates eligibility for charity care; and

.. The eligibility of the patient for charity care as defined in this chapter and in accordance with hospital policy. An initial determination of sponsorship status shall precede collection efforts directed at the patient.

. At the hospital's discretion, a hospital may consider applications for charity care at any time, including any time there is a change in a patient's financial circumstances.

. The department shall monitor the distribution of charity care among hospitals, with reference to factors such as relative need for charity care in hospital service areas and trends in private and public health coverage. The department shall prepare reports that identify any problems in distribution which are in contradiction of the intent of this chapter. The report shall include an assessment of the effects of the provisions of this chapter on access to hospital and health care services, as well as an evaluation of the contribution of all purchasers of care to hospital charity care.

. The department shall issue a report on the subjects addressed in this section at least annually, with the first report due on July 1, 1990.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6273-S.SL.pdf?cite=2018%20c%20263%20§%202[2018 c 263 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%20118[1998 c 245 § 118]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20506[1989 1st ex.s. c 9 § 506]; ]

== 70.170.070 - Penalties.
. Every person who shall violate or knowingly aid and abet the violation of RCW * 70.170.060 (5) or (6), 70.170.080, or ** 70.170.100, or any valid orders or rules adopted pursuant to these sections, or who fails to perform any act which it is herein made his or her duty to perform, shall be guilty of a misdemeanor. Following official notice to the accused by the department of the existence of an alleged violation, each day of noncompliance upon which a violation occurs shall constitute a separate violation. Any person violating the provisions of this chapter may be enjoined from continuing such violation. The department has authority to levy civil penalties not exceeding one thousand dollars for violations of this chapter and determined pursuant to this section.

. Every person who shall violate or knowingly aid and abet the violation of RCW 70.170.060 (1) or (2), or any valid orders or rules adopted pursuant to such section, or who fails to perform any act which it is herein made his or her duty to perform, shall be subject to the following criminal and civil penalties:

.. For any initial violations: The violating person shall be guilty of a misdemeanor, and the department may impose a civil penalty not to exceed one thousand dollars as determined pursuant to this section.

.. For a subsequent violation of RCW 70.170.060 (1) or (2) within five years following a conviction: The violating person shall be guilty of a misdemeanor, and the department may impose a penalty not to exceed three thousand dollars as determined pursuant to this section.

.. For a subsequent violation with intent to violate RCW 70.170.060 (1) or (2) within five years following a conviction: The criminal and civil penalties enumerated in (a) of this subsection; plus up to a three-year prohibition against the issuance of tax exempt bonds under the authority of the Washington health care facilities authority; and up to a three-year prohibition from applying for and receiving a certificate of need.

.. For a violation of RCW 70.170.060 (1) or (2) within five years of a conviction under (c) of this subsection: The criminal and civil penalties and prohibition enumerated in (a) and (b) of this subsection; plus up to a one-year prohibition from participation in the state medical assistance or medical care services authorized under chapter 74.09 RCW.

. The provisions of chapter 34.05 RCW shall apply to all noncriminal actions undertaken by the department of health, the department of social and health services, and the Washington health care facilities authority pursuant to chapter 9, Laws of 1989 1st ex. sess.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20507[1989 1st ex.s. c 9 § 507]; ]

== 70.170.080 - Assessments—Costs.
The basic expenses for the hospital data collection and reporting activities of this chapter shall be financed by an assessment against hospitals of no more than four one-hundredths of one percent of each hospital's gross operating costs, to be levied and collected from and after that date, upon which the similar assessment levied under *chapter 70.39 RCW is terminated, for the provision of hospital services for its last fiscal year ending on or before June 30th of the preceding calendar year. Budgetary requirements in excess of that limit must be financed by a general fund appropriation by the legislature. All moneys collected under this section shall be deposited by the state treasurer in the hospital data collection account which is hereby created in the state treasury. The department may also charge, receive, and dispense funds or authorize any contractor or outside sponsor to charge for and reimburse the costs associated with special studies as specified in RCW 70.170.050.

During the 1993-1995 fiscal biennium, moneys in the hospital data collection account may be expended, pursuant to appropriation, for hospital data analysis and the administration of the health information program.

Any amounts raised by the collection of assessments from hospitals provided for in this section which are not required to meet appropriations in the budget act for the current fiscal year shall be available to the department in succeeding years.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5968-S.SL.pdf?cite=1993%20sp.s.%20c%2024%20§%20925[1993 sp.s. c 24 § 925]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1058-S.SL.pdf?cite=1991%20sp.s.%20c%2013%20§%2071[1991 sp.s. c 13 § 71]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20508[1989 1st ex.s. c 9 § 508]; ]

== 70.170.090 - Confidentiality.
The department and any of its contractors or agents shall maintain the confidentiality of any information which may, in any manner, identify individual patients.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20509[1989 1st ex.s. c 9 § 509]; ]

