= 70.110 - Flammable fabrics—Children's sleepwear.
:toc:

== 70.110.010 - Short title.
This chapter may be known and cited as the "Flammable Fabrics Act".

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c211.pdf?cite=1973%201st%20ex.s.%20c%20211%20§%201[1973 1st ex.s. c 211 § 1]; ]

== 70.110.020 - Legislative finding.
The legislature hereby finds and declares that fabric related burns from children's sleepwear present an immediate and serious danger to the infants and children of this state. The legislature therefore declares it to be in the public interest, and for the protection of the health, property, and welfare of the residents of this state to herein provide for flammability standards for children's sleepwear.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c211.pdf?cite=1973%201st%20ex.s.%20c%20211%20§%202[1973 1st ex.s. c 211 § 2]; ]

== 70.110.030 - Definitions.
As used in this chapter the following words and phrases shall have the following meanings unless the context clearly requires otherwise:

. "Person" means an individual, partnership, corporation, association, or any other form of business enterprise, and every officer thereof.

. "Children's sleepwear" means any product of wearing apparel from infant size up to and including size fourteen which is sold or intended for sale for the primary use of sleeping or activities related to sleeping, such as nightgowns, pajamas, and similar or related items such as robes, but excluding diapers and underwear.

. "Fabric" means any material (except fiber, filament, or yarn for other than retail sale) woven, knitted, felted, or otherwise produced from or in combination with any material or synthetic fiber, film, or substitute therefor which is intended for use, or which may reasonably be expected to be used, in children's sleepwear.

. The term "infant size up to and including size six-x" means the sizes defined as infant through and including six-x in Department of Commerce Voluntary Standards, Commercial Standard 151-50, "Body Measurements for the Sizing of Apparel for Infants, Babies, Toddlers, and Children", Commercial Standard 153, "Body Measurements for the Sizing of Apparel for Girls", and Commercial Standard 155, "Body Measurements for the Sizing of Boys' Apparel".

. "Fabric related burns" means burns that would not have been incurred but for the fact that sleepwear worn at the time of the burns did not comply with commercial standards promulgated by the secretary of commerce of the United States in March, 1971, identified as Standard for the Flammability of Children's Sleepwear (DOC FF 3-71) 36 F.R. 14062 and by the Flammable Fabrics Act 15 U.S.C. 1193.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c211.pdf?cite=1973%201st%20ex.s.%20c%20211%20§%203[1973 1st ex.s. c 211 § 3]; ]

== 70.110.040 - Compliance required.
. It shall be unlawful to manufacture for sale, sell, or offer for sale any new and unused article of children's sleepwear which does not comply with the standards established in the Standard for the Flammability of Children's Sleepwear (DOC FF 3-71), 36 F.R. 14062 and the Flammable Fabrics Act, 15 U.S.C. 1191-1204.

. A violation of this section is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20360[2003 c 53 § 360]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c211.pdf?cite=1973%201st%20ex.s.%20c%20211%20§%204[1973 1st ex.s. c 211 § 4]; ]

== 70.110.050 - Attorney general or prosecuting attorneys authorized to bring actions to restrain or prevent violations.
The attorney general or the prosecuting attorney of any county within the state may bring an action in the name of the state against any person to restrain and prevent any violation of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c211.pdf?cite=1973%201st%20ex.s.%20c%20211%20§%205[1973 1st ex.s. c 211 § 5]; ]

== 70.110.070 - Strict liability.
Any person who violates RCW 70.110.040 shall be strictly liable for fabric-related burns.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c211.pdf?cite=1973%201st%20ex.s.%20c%20211%20§%207[1973 1st ex.s. c 211 § 7]; ]

== 70.110.080 - Personal service of process—Jurisdiction of courts.
Personal service of any process in an action under this chapter may be made upon any person outside the state if such person has violated any provision of this chapter. Such person shall be deemed to have thereby submitted himself or herself to the jurisdiction of the courts of this state within the meaning of RCW 4.28.180 and 4.28.185, as now or hereafter amended.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20425[2012 c 117 § 425]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c211.pdf?cite=1973%201st%20ex.s.%20c%20211%20§%208[1973 1st ex.s. c 211 § 8]; ]

== 70.110.900 - Provisions additional.
The provisions of this chapter shall be in addition to and not a substitution for or limitation of any other law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c211.pdf?cite=1973%201st%20ex.s.%20c%20211%20§%209[1973 1st ex.s. c 211 § 9]; ]

