= 70.111 - Infant crib safety act.
:toc:

== 70.111.010 - Findings—Purpose—Intent.
. The legislature finds all of the following:

.. The disability and death of infants resulting from injuries sustained in crib accidents are a serious threat to the public health, welfare, and safety of the people of this state.

.. Infants are an especially vulnerable class of people.

.. The design and construction of a baby crib must ensure that it is safe to leave an infant unattended for extended periods of time. A parent or caregiver has a right to believe that the crib in use is a safe place to leave an infant.

.. Over thirteen thousand infants are injured in unsafe cribs every year.

.. In the past decade, six hundred twenty-two infants died (a rate of sixty-two infants each year) from injuries sustained in unsafe cribs.

.. The United States consumer product safety commission estimates that the cost to society resulting from injuries and death due to unsafe cribs is two hundred thirty-five million dollars per year.

.. Secondhand, hand-me-down, and heirloom cribs pose a special problem. There were four million infants born in this country last year, but only one million new cribs sold. As many as three out of four infants are placed in secondhand, hand-me-down, or heirloom cribs.

.. Most injuries and deaths occur in secondhand, hand-me-down, or heirloom cribs.

.. Existing state and federal legislation is inadequate to deal with this hazard.

.. Prohibiting the remanufacture, retrofit, sale, contracting to sell or resell, leasing, or subletting of unsafe cribs, particularly unsafe secondhand, hand-me-down, or heirloom cribs, will prevent injuries and deaths caused by cribs.

. The purpose of this chapter is to prevent the occurrence of injuries and deaths to infants as a result of unsafe cribs by making it illegal to remanufacture, retrofit, sell, contract to sell or resell, lease, sublet, or otherwise place in the stream of commerce, after June 6, 1996, any full-size or nonfull-size crib that is unsafe for any infant using the crib.

. It is the intent of the legislature to encourage public and private collaboration in disseminating materials relative to the safety of baby cribs to parents, child care providers, and those who would be likely to place unsafe cribs in the stream of commerce. The legislature also intends that informational materials regarding baby crib safety be available to consumers through the department of health.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6229-S.SL.pdf?cite=1996%20c%20158%20§%201[1996 c 158 § 1]; ]

== 70.111.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Infant" means any person less than thirty-five inches tall and less than three years of age.

. "Crib" means a bed or containment designed to accommodate an infant.

. "Full-size crib" means a full-size crib as defined in Section 1508.3 of Title 16 of the Code of Federal Regulations regarding the requirements for full-size cribs.

. "Nonfull-size crib" means a nonfull-size crib as defined in Section 1509.2(b) of Title 16 of the Code of the Federal Regulations regarding the requirements for nonfull-size cribs.

. "Person" means any natural person, firm, corporation, association, or agent or employee thereof.

. "Commercial user" means any person who deals in full-size or nonfull-size cribs of the kind governed by this chapter or who otherwise by one's occupation holds oneself out as having knowledge or skill peculiar to the full-size or nonfull-size cribs governed by this chapter, including child care facilities and family child care homes licensed by the department of social and health services under chapter 74.15 RCW, or any person who is in the business of remanufacturing, retrofitting, selling, leasing, subletting, or otherwise placing in the stream of commerce full-size or nonfull-size cribs.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6229-S.SL.pdf?cite=1996%20c%20158%20§%203[1996 c 158 § 3]; ]

== 70.111.030 - Unsafe cribs—Prohibition—Definition—Penalty.
. No commercial user may remanufacture, retrofit, sell, contract to sell or resell, lease, sublet, or otherwise place in the stream of commerce, on or after June 6, 1996, a full-size or nonfull-size crib that is unsafe for any infant using the crib.

. A crib is presumed to be unsafe pursuant to this chapter if it does not conform to all of the following:

.. Part 1508 (commencing with Section 1508.1) of Title 16 of the Code of Federal Regulations;

.. Part 1509 (commencing with Section 1509.1) of Title 16 of the Code of Federal Regulations;

.. Part 1303 (commencing with Section 1303.1) of Title 16 of the Code of Federal Regulations;

.. American Society for Testing Materials Voluntary Standards F966-90;

.. American Society for Testing Materials Voluntary Standards F1169.88;

.. Any regulations that are adopted in order to amend or supplement the regulations described in (a) through (e) of this subsection.

. Cribs that are unsafe or fail to perform as expected pursuant to subsection (2) of this section include, but are not limited to, cribs that have any of the following dangerous features or characteristics:

.. Corner posts that extend more than one-sixteenth of an inch;

.. Spaces between side slats more than two and three-eighths inches;

.. Mattress support than can be easily dislodged from any point of the crib. A mattress segment can be easily dislodged if it cannot withstand at least a twenty-five pound upward force from underneath the crib;

.. Cutout designs on the end panels;

.. Rail height dimensions that do not conform to the following:

... The height of the rail and end panel as measured from the top of the rail or panel in its lowest position to the top of the mattress support in its highest position is at least nine inches;

... The height of the rail and end panel as measured from the top of the rail or panel in its highest position to the top of the mattress support in its lowest position is at least twenty-six inches;

.. Any screws, bolts, or hardware that are loose and not secured;

.. Sharp edges, points, or rough surfaces, or any wood surfaces that are not smooth and free from splinters, splits, or cracks;

.. Nonfull-size cribs with tears in mesh or fabric sides.

. On or after January 1, 1997, any commercial user who willfully and knowingly violates this section is guilty of a misdemeanor, punishable by a fine not exceeding one thousand dollars. Hotels, motels, and similar transient lodging, child care facilities, and family child care homes are not subject to this section until January 1, 1999.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20361[2003 c 53 § 361]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6229-S.SL.pdf?cite=1996%20c%20158%20§%204[1996 c 158 § 4]; ]

== 70.111.040 - Exemption.
Any crib that is clearly not intended for use by an infant is exempt from the provisions of this chapter, provided that it is accompanied at the time of remanufacturing, retrofitting, selling, leasing, subletting, or otherwise placing in the stream of commerce, by a notice to be furnished by the commercial user declaring that it is not intended to be used for an infant and is dangerous to use for an infant. The commercial user is further exempt from claims for liability resulting from use of a crib contrary to the notice required in this section.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6229-S.SL.pdf?cite=1996%20c%20158%20§%205[1996 c 158 § 5]; ]

== 70.111.060 - Civil actions.
Any person may maintain an action against any commercial user who violates RCW 70.111.030 to enjoin the remanufacture, retrofit, sale, contract to sell, contract to resell, lease, or subletting of a full-size or nonfull-size crib that is unsafe for any infant using the crib, and for reasonable attorneys' fees and costs. This section does not apply to hotels, motels, and similar transient lodging, child care facilities, and family child care homes until January 1, 1999.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6229-S.SL.pdf?cite=1996%20c%20158%20§%207[1996 c 158 § 7]; ]

== 70.111.070 - Remedies.
Remedies available under this chapter are in addition to any other remedies or procedures under any other provision of law that may be available to an aggrieved party.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6229-S.SL.pdf?cite=1996%20c%20158%20§%208[1996 c 158 § 8]; ]

== 70.111.900 - Short title.
This chapter may be known and cited as the infant crib safety act.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6229-S.SL.pdf?cite=1996%20c%20158%20§%202[1996 c 158 § 2]; ]

