= 70.122 - Natural death act.
:toc:

== 70.122.010 - Legislative findings.
The legislature finds that adult persons have the fundamental right to control the decisions relating to the rendering of their own health care, including the decision to have life-sustaining treatment withheld or withdrawn in instances of a terminal condition or permanent unconscious condition.

The legislature further finds that modern medical technology has made possible the artificial prolongation of human life beyond natural limits.

The legislature further finds that, in the interest of protecting individual autonomy, such prolongation of the process of dying for persons with a terminal condition or permanent unconscious condition may cause loss of patient dignity, and unnecessary pain and suffering, while providing nothing medically necessary or beneficial to the patient. The legislature further believes that physicians and nurses should not withhold or unreasonably diminish pain medication for patients in a terminal condition where the primary intent of providing such medication is to alleviate pain and maintain or increase the patient's comfort.

The legislature further finds that there exists considerable uncertainty in the medical and legal professions as to the legality of terminating the use or application of life-sustaining treatment where the patient having the capacity to make health care decisions has voluntarily evidenced a desire that such treatment be withheld or withdrawn.

In recognition of the dignity and privacy which patients have a right to expect, the legislature hereby declares that the laws of the state of Washington shall recognize the right of an adult person to make a written directive instructing such person's physician to withhold or withdraw life-sustaining treatment in the event of a terminal condition or permanent unconscious condition. The legislature also recognizes that a person's right to control his or her health care may be exercised by an authorized representative who validly holds the person's durable power of attorney for health care.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1481-S.SL.pdf?cite=1992%20c%2098%20§%201[1992 c 98 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c112.pdf?cite=1979%20c%20112%20§%202[1979 c 112 § 2]; ]

== 70.122.020 - Definitions.
Unless the context clearly requires otherwise, the definitions contained in this section shall apply throughout this chapter.

. "Adult person" means a person who has attained the age of majority as defined in RCW 26.28.010 and 26.28.015, and who has the capacity to make health care decisions.

. "Attending physician" means the physician selected by, or assigned to, the patient who has primary responsibility for the treatment and care of the patient.

. "Directive" means a written document voluntarily executed by the declarer generally consistent with the guidelines of RCW 70.122.030.

. "Health facility" means a hospital as defined in *RCW 70.41.020(4) or a nursing home as defined in RCW 18.51.010, a home health agency or hospice agency as defined in RCW 70.126.010, or an assisted living facility as defined in RCW 18.20.020.

. "Life-sustaining treatment" means any medical or surgical intervention that uses mechanical or other artificial means, including artificially provided nutrition and hydration, to sustain, restore, or replace a vital function, which, when applied to a qualified patient, would serve only to prolong the process of dying. "Life-sustaining treatment" shall not include the administration of medication or the performance of any medical or surgical intervention deemed necessary solely to alleviate pain.

. "Permanent unconscious condition" means an incurable and irreversible condition in which the patient is medically assessed within reasonable medical judgment as having no reasonable probability of recovery from an irreversible coma or a persistent vegetative state.

. "Physician" means a person licensed under chapters 18.71 or 18.57 RCW.

. "Qualified patient" means an adult person who is a patient diagnosed in writing to have a terminal condition by the patient's attending physician, who has personally examined the patient, or a patient who is diagnosed in writing to be in a permanent unconscious condition in accordance with accepted medical standards by two physicians, one of whom is the patient's attending physician, and both of whom have personally examined the patient.

. "Terminal condition" means an incurable and irreversible condition caused by injury, disease, or illness, that, within reasonable medical judgment, will cause death within a reasonable period of time in accordance with accepted medical standards, and where the application of life-sustaining treatment serves only to prolong the process of dying.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2056-S.SL.pdf?cite=2012%20c%2010%20§%2053[2012 c 10 § 53]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1481-S.SL.pdf?cite=1992%20c%2098%20§%202[1992 c 98 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c112.pdf?cite=1979%20c%20112%20§%203[1979 c 112 § 3]; ]

== 70.122.030 - Directive to withhold or withdraw life-sustaining treatment.
. Any adult person may execute a directive directing the withholding or withdrawal of life-sustaining treatment in a terminal condition or permanent unconscious condition. The directive shall be signed by the declarer and acknowledged before a notary public or other individual authorized by law to take acknowledgments or signed by the declarer in the presence of two witnesses not related to the declarer by blood or marriage and who would not be entitled to any portion of the estate of the declarer upon declarer's decease under any will of the declarer or codicil thereto then existing or, at the time of the directive, by operation of law then existing. In addition, a witness to a directive shall not be the attending physician, an employee of the attending physician or a health facility in which the declarer is a patient, or any person who has a claim against any portion of the estate of the declarer upon declarer's decease at the time of the execution of the directive. The directive, or a copy thereof, shall be made part of the patient's medical records retained by the attending physician, a copy of which shall be forwarded by the custodian of the records to the health facility when the withholding or withdrawal of life-support treatment is contemplated. The directive may be in the following form and may include a notarial certificate for an acknowledgment in an individual capacity in short form as permitted by state law, but in addition may include other specific directions:

Health Care Directive

Directive made this . . . . day of . . . . . . (month, year).

I . . . . . ., having the capacity to make health care decisions, willfully, and voluntarily make known my desire that my dying shall not be artificially prolonged under the circumstances set forth below, and do hereby declare that:

.. If at any time I should be diagnosed in writing to be in a terminal condition by the attending physician, or in a permanent unconscious condition by two physicians, and where the application of life-sustaining treatment would serve only to artificially prolong the process of my dying, I direct that such treatment be withheld or withdrawn, and that I be permitted to die naturally. I understand by using this form that a terminal condition means an incurable and irreversible condition caused by injury, disease, or illness, that would within reasonable medical judgment cause death within a reasonable period of time in accordance with accepted medical standards, and where the application of life-sustaining treatment would serve only to prolong the process of dying. I further understand in using this form that a permanent unconscious condition means an incurable and irreversible condition in which I am medically assessed within reasonable medical judgment as having no reasonable probability of recovery from an irreversible coma or a persistent vegetative state.

.. In the absence of my ability to give directions regarding the use of such life-sustaining treatment, it is my intention that this directive shall be honored by my family and physician(s) as the final expression of my legal right to refuse medical or surgical treatment and I accept the consequences of such refusal. If another person is appointed to make these decisions for me, whether through a durable power of attorney or otherwise, I request that the person be guided by this directive and any other clear expressions of my desires.

.. If I am diagnosed to be in a terminal condition or in a permanent unconscious condition (check one):

I DO want to have artificially provided nutrition and hydration.

I DO NOT want to have artificially provided nutrition and hydration.

.. If I have been diagnosed as pregnant and that diagnosis is known to my physician, this directive shall have no force or effect during the course of my pregnancy.

.. I understand the full import of this directive and I am emotionally and mentally capable to make the health care decisions contained in this directive.

.. I understand that before I sign this directive, I can add to or delete from or otherwise change the wording of this directive and that I may add to or delete from this directive at any time and that any changes shall be consistent with Washington state law or federal constitutional law to be legally valid.

.. It is my wish that every part of this directive be fully implemented. If for any reason any part is held invalid it is my wish that the remainder of my directive be implemented.

 Signed . . . .

 

Signed . . . .

City, County, and State of Residence

The declarer has been personally known to me or has provided proof of identity and I believe him or her to be capable of making health care decisions.

 Witness . . . . Witness . . . .

 

Witness . . . .

 

Witness . . . .

. Prior to withholding or withdrawing life-sustaining treatment, the diagnosis of a terminal condition by the attending physician or the diagnosis of a permanent unconscious state by two physicians shall be entered in writing and made a permanent part of the patient's medical records.

. A directive executed in another political jurisdiction is valid to the extent permitted by Washington state law and federal constitutional law.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1175.SL.pdf?cite=2019%20c%20209%20§%202[2019 c 209 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1481-S.SL.pdf?cite=1992%20c%2098%20§%203[1992 c 98 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c112.pdf?cite=1979%20c%20112%20§%204[1979 c 112 § 4]; ]

== 70.122.040 - Revocation of directive.
. A directive may be revoked at any time by the declarer, without regard to the declarer's mental state or competency, by any of the following methods:

.. By being canceled, defaced, obliterated, burned, torn, or otherwise destroyed by the declarer or by some person in the declarer's presence and by the declarer's direction.

.. By a written revocation of the declarer expressing his or her intent to revoke, signed, and dated by the declarer. Such revocation shall become effective only upon communication to the attending physician by the declarer or by a person acting on behalf of the declarer. The attending physician shall record in the patient's medical record the time and date when the physician received notification of the written revocation.

.. By a verbal expression by the declarer of his or her intent to revoke the directive. Such revocation shall become effective only upon communication to the attending physician by the declarer or by a person acting on behalf of the declarer. The attending physician shall record in the patient's medical record the time, date, and place of the revocation and the time, date, and place, if different, of when the physician received notification of the revocation.

.. In the case of a directive that is stored in the health care declarations registry under RCW 70.122.130, by an online method established by the department of health. Failure to use this method of revocation for a directive that is stored in the registry does not invalidate a revocation that is made by another method described under this section.

. There shall be no criminal or civil liability on the part of any person for failure to act upon a revocation made pursuant to this section unless that person has actual or constructive knowledge of the revocation except as provided in RCW 70.122.051(4).

. If the declarer becomes comatose or is rendered incapable of communicating with the attending physician, the directive shall remain in effect for the duration of the comatose condition or until such time as the declarer's condition renders the declarer able to communicate with the attending physician.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2342-S2.SL.pdf?cite=2006%20c%20108%20§%204[2006 c 108 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c112.pdf?cite=1979%20c%20112%20§%205[1979 c 112 § 5]; ]

== 70.122.051 - Liability of health care provider.
. For the purposes of this section, "provider" means a physician, advanced registered nurse practitioner, health care provider acting under the direction of a physician or an advanced registered nurse practitioner, or health care facility, as defined in this chapter or in chapter 71.32 RCW, and its personnel.

. Any provider who participates in good faith in the withholding or withdrawal of life-sustaining treatment from a qualified patient in accordance with the requirements of this chapter, shall be immune from legal liability, including civil, criminal, or professional conduct sanctions, unless otherwise negligent.

. The establishment of a health care declarations registry does not create any new or distinct obligation for a provider to determine whether a patient has a health care declaration.

. A provider is not subject to civil or criminal liability or sanctions for unprofessional conduct under the uniform disciplinary act, chapter 18.130 RCW, when in good faith and without negligence:

.. The provider provides, does not provide, withdraws, or withholds treatment to a patient in the absence of actual knowledge of the existence of a health care declaration stored in the health care declarations registry established in RCW 70.122.130;

.. The provider provides, does not provide, withdraws, or withholds treatment pursuant to a health care declaration stored in the health care declarations registry established in RCW 70.122.130 in the absence of actual knowledge of the revocation of the declaration;

.. The provider provides, does not provide, withdraws, or withholds treatment according to a health care declaration stored in the health care declarations registry established in RCW 70.122.130 in good faith reliance upon the validity of the health care declaration and the declaration is subsequently found to be invalid; or

.. The provider provides, does not provide, withdraws, or withholds treatment according to the patient's health care declaration stored in the health care declarations registry established in RCW 70.122.130.

. Except for acts of gross negligence, willful misconduct, or intentional wrongdoing, the department of health is not subject to civil liability for any claims or demands arising out of the administration or operation of the health care declarations registry established in RCW 70.122.130.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2342-S2.SL.pdf?cite=2006%20c%20108%20§%206[2006 c 108 § 6]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1481-S.SL.pdf?cite=1992%20c%2098%20§%205[1992 c 98 § 5]; ]

== 70.122.060 - Procedures by physician—Health care facility or personnel may refuse to participate.
. Prior to the withholding or withdrawal of life-sustaining treatment from a qualified patient pursuant to the directive, the attending physician shall make a reasonable effort to determine that the directive complies with RCW 70.122.030 and, if the patient is capable of making health care decisions, that the directive and all steps proposed by the attending physician to be undertaken are currently in accord with the desires of the qualified patient.

. The attending physician or health facility shall inform a patient or patient's authorized representative of the existence of any policy or practice that would preclude the honoring of the patient's directive at the time the physician or facility becomes aware of the existence of such a directive. If the patient, after being informed of such policy or directive, chooses to retain the physician or facility, the physician or facility with the patient or the patient's representative shall prepare a written plan to be filed with the patient's directive that sets forth the physician's or facilities' intended actions should the patient's medical status change so that the directive would become operative. The physician or facility under this subsection has no obligation to honor the patient's directive if they have complied with the requirements of this subsection, including compliance with the written plan required under this subsection.

. The directive shall be conclusively presumed, unless revoked, to be the directions of the patient regarding the withholding or withdrawal of life-sustaining treatment. No physician, health facility, or health personnel acting in good faith with the directive or in accordance with the written plan in subsection (2) of this section shall be criminally or civilly liable for failing to effectuate the directive of the qualified patient pursuant to this subsection. 

. No nurse, physician, or other health care practitioner may be required by law or contract in any circumstances to participate in the withholding or withdrawal of life-sustaining treatment if such person objects to so doing. No person may be discriminated against in employment or professional privileges because of the person's participation or refusal to participate in the withholding or withdrawal of life-sustaining treatment.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1481-S.SL.pdf?cite=1992%20c%2098%20§%206[1992 c 98 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c112.pdf?cite=1979%20c%20112%20§%207[1979 c 112 § 7]; ]

== 70.122.070 - Effects of carrying out directive—Insurance.
. The withholding or withdrawal of life-sustaining treatment from a qualified patient pursuant to the patient's directive in accordance with the provisions of this chapter shall not, for any purpose, constitute a suicide or a homicide.

. The making of a directive pursuant to RCW 70.122.030 shall not restrict, inhibit, or impair in any manner the sale, procurement, or issuance of any policy of life insurance, nor shall it be deemed to modify the terms of an existing policy of life insurance. No policy of life insurance shall be legally impaired or invalidated in any manner by the withholding or withdrawal of life-sustaining treatment from an insured qualified patient, notwithstanding any term of the policy to the contrary.

. No physician, health facility, or other health provider, and no health care service plan, insurer issuing disability insurance, self-insured employee welfare benefit plan, or nonprofit hospital service plan, shall require any person to execute a directive as a condition for being insured for, or receiving, health care services.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1481-S.SL.pdf?cite=1992%20c%2098%20§%207[1992 c 98 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c112.pdf?cite=1979%20c%20112%20§%208[1979 c 112 § 8]; ]

== 70.122.080 - Effects of carrying out directive on cause of death.
The act of withholding or withdrawing life-sustaining treatment, when done pursuant to a directive described in RCW 70.122.030 and which results in the death of the declarer, shall not be construed to be an intervening force or to affect the chain of proximate cause between the conduct of anyone that placed the declarer in a terminal condition or a permanent unconscious condition and the death of the declarer.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1481-S.SL.pdf?cite=1992%20c%2098%20§%208[1992 c 98 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c112.pdf?cite=1979%20c%20112%20§%2010[1979 c 112 § 10]; ]

== 70.122.090 - Criminal conduct—Penalties.
. Any person who willfully conceals, cancels, defaces, obliterates, or damages the directive of another without such declarer's consent is guilty of a gross misdemeanor.

. Any person who falsifies or forges the directive of another, or willfully conceals or withholds personal knowledge of a revocation as provided in RCW 70.122.040 with the intent to cause a withholding or withdrawal of life-sustaining treatment contrary to the wishes of the declarer, and thereby, because of any such act, directly causes life-sustaining treatment to be withheld or withdrawn and death to thereby be hastened, shall be subject to prosecution for murder in the first degree as defined in RCW 9A.32.030.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20362[2003 c 53 § 362]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1481-S.SL.pdf?cite=1992%20c%2098%20§%209[1992 c 98 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c112.pdf?cite=1979%20c%20112%20§%209[1979 c 112 § 9]; ]

== 70.122.100 - Mercy killing, lethal injection, or active euthanasia not authorized.
Nothing in this chapter shall be construed to condone, authorize, or approve mercy killing, lethal injection, or active euthanasia.

[ 2009 c 1 § 25 (Initiative Measure No. 1000, approved November 4, 2008); http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1481-S.SL.pdf?cite=1992%20c%2098%20§%2010[1992 c 98 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c112.pdf?cite=1979%20c%20112%20§%2011[1979 c 112 § 11]; ]

== 70.122.110 - Discharge so that patient may die at home.
If a qualified patient capable of making health care decisions indicates that he or she wishes to die at home, the patient shall be discharged as soon as reasonably possible. The health care provider or facility has an obligation to explain the medical risks of an immediate discharge to the qualified patient. If the provider or facility complies with the obligation to explain the medical risks of an immediate discharge to a qualified patient, there shall be no civil or criminal liability for claims arising from such discharge.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1481-S.SL.pdf?cite=1992%20c%2098%20§%204[1992 c 98 § 4]; ]

== 70.122.120 - Directive's validity assumed.
Any person or health facility may assume that a directive complies with this chapter and is valid.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1481-S.SL.pdf?cite=1992%20c%2098%20§%2012[1992 c 98 § 12]; ]

== 70.122.130 - Health care declarations registry—Rules—Report.
. The department of health shall establish and maintain a statewide health care declarations registry containing the health care declarations identified in subsection (2) of this section as submitted by residents of Washington. The department shall digitally reproduce and store health care declarations in the registry. The department may establish standards for individuals to submit digitally reproduced health care declarations directly to the registry, but is not required to review the health care declarations that it receives to ensure they comply with the particular statutory requirements applicable to the document. The department may contract with an organization that meets the standards identified in this section.

. [Empty]
.. An individual may submit any of the following health care declarations to the department of health to be digitally reproduced and stored in the registry:

... A directive, as defined by this chapter;

... A durable power of attorney for health care, as authorized in chapter 11.125 RCW;

... A mental health advance directive, as defined by chapter 71.32 RCW; or

... A form adopted pursuant to the department of health's authority in RCW 43.70.480.

.. Failure to submit a health care declaration to the department of health does not affect the validity of the declaration.

.. Failure to notify the department of health of a valid revocation of a health care declaration does not affect the validity of the revocation.

.. The entry of a health care directive in the registry under this section does not:

... Affect the validity of the document;

... Take the place of any requirements in law necessary to make the submitted document legal; or

... Create a presumption regarding the validity of the document.

. The department of health shall prescribe a procedure for an individual to revoke a health care declaration contained in the registry.

. The registry must:

.. Be maintained in a secure database that is accessible through a website maintained by the department of health;

.. Send annual electronic messages to individuals that have submitted health care declarations to request that they review the registry materials to ensure that it is current;

.. Provide individuals who have submitted one or more health care declarations with access to their documents and the ability to revoke their documents at all times; and

.. Provide the personal representatives of individuals who have submitted one or more health care declarations to the registry, attending physicians, advanced registered nurse practitioners, health care providers licensed by a disciplining authority identified in RCW 18.130.040 who is acting under the direction of a physician or an advanced registered nurse practitioner, and health care facilities, as defined in this chapter or in chapter 71.32 RCW, access to the registry at all times.

. In designing the registry and website, the department of health shall ensure compliance with state and federal requirements related to patient confidentiality.

. The department shall provide information to health care providers and health care facilities on the registry website regarding the different federal and Washington state requirements to ascertain and document whether a patient has an advance directive.

. The department of health may accept donations, grants, gifts, or other forms of voluntary contributions to support activities related to the creation and maintenance of the health care declarations registry and statewide public education campaigns related to the existence of the registry. All receipts from donations made under this section, and other contributions and appropriations specifically made for the purposes of creating and maintaining the registry established under this section and statewide public education campaigns related to the existence of the registry, shall be deposited into the general fund. These moneys in the general fund may be spent only after appropriation.

. The department of health may adopt rules as necessary to implement chapter 108, Laws of 2006.

. By December 1, 2008, the department shall report to the house and senate committees on health care the following information:

.. Number of participants in the registry;

.. Number of health care declarations submitted by type of declaration as defined in this section;

.. Number of health care declarations revoked and the method of revocation;

.. Number of providers and facilities, by type, that have been provided access to the registry;

.. Actual costs of operation of the registry.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5635-S.SL.pdf?cite=2016%20c%20209%20§%20406[2016 c 209 § 406]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5287-S.SL.pdf?cite=2013%20c%20251%20§%2012[2013 c 251 § 12]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2342-S2.SL.pdf?cite=2006%20c%20108%20§%202[2006 c 108 § 2]; ]

== 70.122.900 - Short title—1979 c 112.
This act shall be known and may be cited as the "Natural Death Act".

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c112.pdf?cite=1979%20c%20112%20§%201[1979 c 112 § 1]; ]

== 70.122.910 - Construction.
This chapter shall not be construed as providing the exclusive means by which individuals may make decisions regarding their health treatment, including but not limited to, the withholding or withdrawal of life-sustaining treatment, nor limiting the means provided by case law more expansive than chapter 98, Laws of 1992.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1481-S.SL.pdf?cite=1992%20c%2098%20§%2011[1992 c 98 § 11]; ]

== 70.122.915 - Application—1992 c 98.
A directive executed anytime before June 11, 1992, which generally complies with chapter 98, Laws of 1992 is effective under chapter 98, Laws of 1992.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1481-S.SL.pdf?cite=1992%20c%2098%20§%2013[1992 c 98 § 13]; ]

== 70.122.925 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%20154[2009 c 521 § 154]; ]

