= 70.157 - National uniform tobacco settlement—Nonparticipating tobacco product manufacturers.
:toc:

== 70.157.005 - Findings and purpose.
.. Cigarette smoking presents serious public health concerns to the State and to the citizens of the State. The Surgeon General has determined that smoking causes lung cancer, heart disease and other serious diseases, and that there are hundreds of thousands of tobacco-related deaths in the United States each year. These diseases most often do not appear until many years after the person in question begins smoking.

.. Cigarette smoking also presents serious financial concerns for the State. Under certain health-care programs, the State may have a legal obligation to provide medical assistance to eligible persons for health conditions associated with cigarette smoking, and those persons may have a legal entitlement to receive such medical assistance.

.. Under these programs, the State pays millions of dollars each year to provide medical assistance for these persons for health conditions associated with cigarette smoking.

.. It is the policy of the State that financial burdens imposed on the State by cigarette smoking be borne by tobacco product manufacturers rather than by the State to the extent that such manufacturers either determine to enter into a settlement with the State or are found culpable by the courts.

.. On November 23, 1998, leading United States tobacco product manufacturers entered into a settlement agreement, entitled the "Master Settlement Agreement," with the State. The Master Settlement Agreement obligates these manufacturers, in return for a release of past, present and certain future claims against them as described therein, to pay substantial sums to the State (tied in part to their volume of sales); to fund a national foundation devoted to the interests of public health; and to make substantial changes in their advertising and marketing practices and corporate culture, with the intention of reducing underage smoking.

.. It would be contrary to the policy of the State if tobacco product manufacturers who determine not to enter into such a settlement could use a resulting cost advantage to derive large, short-term profits in the years before liability may arise without ensuring that the State will have an eventual source of recovery from them if they are proven to have acted culpably. It is thus in the interest of the State to require that such manufacturers establish a reserve fund to guarantee a source of compensation and to prevent such manufacturers from deriving large, short-term profits and then becoming judgment-proof before liability may arise.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5485.SL.pdf?cite=1999%20c%20393%20§%201[1999 c 393 § 1]; ]

== 70.157.010 - Definitions.
.. "Adjusted for inflation" means increased in accordance with the formula for inflation adjustment set forth in Exhibit C to the Master Settlement Agreement.

.. "Affiliate" means a person who directly or indirectly owns or controls, is owned or controlled by, or is under common ownership or control with, another person. Solely for purposes of this definition, the terms "owns," "is owned" and "ownership" mean ownership of an equity interest, or the equivalent thereof, of ten percent or more, and the term "person" means an individual, partnership, committee, association, corporation or any other organization or group of persons.

.. "Allocable share" means Allocable Share as that term is defined in the Master Settlement Agreement.

.. "Cigarette" means any product that contains nicotine, is intended to be burned or heated under ordinary conditions of use, and consists of or contains (1) any roll of tobacco wrapped in paper or in any substance not containing tobacco; or (2) tobacco, in any form, that is functional in the product, which, because of its appearance, the type of tobacco used in the filler, or its packaging and labeling, is likely to be offered to, or purchased by, consumers as a cigarette; or (3) any roll of tobacco wrapped in any substance containing tobacco which, because of its appearance, the type of tobacco used in the filler, or its packaging and labeling, is likely to be offered to, or purchased by, consumers as a cigarette described in clause (1) of this definition. The term "cigarette" includes "roll-your-own" (i.e., any tobacco which, because of its appearance, type, packaging, or labeling is suitable for use and likely to be offered to, or purchased by, consumers as tobacco for making cigarettes). For purposes of this definition of "cigarette," 0.09 ounces of "roll-your-own" tobacco shall constitute one individual "cigarette".

.. "Master Settlement Agreement" means the settlement agreement (and related documents) entered into on November 23, 1998 by the State and leading United States tobacco product manufacturers.

.. "Qualified escrow fund" means an escrow arrangement with a federally or State chartered financial institution having no affiliation with any tobacco product manufacturer and having assets of at least $1,000,000,000 where such arrangement requires that such financial institution hold the escrowed funds' principal for the benefit of releasing parties and prohibits the tobacco product manufacturer placing the funds into escrow from using, accessing or directing the use of the funds' principal except as consistent with RCW 70.157.020(b).

.. "Released claims" means Released Claims as that term is defined in the Master Settlement Agreement.

.. "Releasing parties" means Releasing Parties as that term is defined in the Master Settlement Agreement.

.. "Tobacco Product Manufacturer" means an entity that after the date of enactment of this Act directly (and not exclusively through any affiliate):

. manufactures cigarettes anywhere that such manufacturer intends to be sold in the United States, including cigarettes intended to be sold in the United States through an importer (except where such importer is an original participating manufacturer (as that term is defined in the Master Settlement Agreement) that will be responsible for the payments under the Master Settlement Agreement with respect to such cigarettes as a result of the provisions of subsections II(mm) of the Master Settlement Agreement and that pays the taxes specified in subsection II(z) of the Master Settlement Agreement, and provided that the manufacturer of such cigarettes does not market or advertise such cigarettes in the United States);

. is the first purchaser anywhere for resale in the United States of cigarettes manufactured anywhere that the manufacturer does not intend to be sold in the United States; or

. becomes a successor of an entity described in paragraph (1) or (2).

The term "Tobacco Product Manufacturer" shall not include an affiliate of a tobacco product manufacturer unless such affiliate itself falls within any of (1)-(3) above.

.. "Units sold" means the number of individual cigarettes sold in the State by the applicable tobacco product manufacturer (whether directly or through a distributor, retailer or similar intermediary or intermediaries) during the year in question, as measured by excise taxes collected by the State on packs bearing the excise tax stamp of the State or "roll-your-own" tobacco containers. The department of revenue shall promulgate such regulations as are necessary to ascertain the amount of State excise tax paid on the cigarettes of such tobacco product manufacturer for each year.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5485.SL.pdf?cite=1999%20c%20393%20§%202[1999 c 393 § 2]; ]

== 70.157.020 - Requirements. (Contingent expiration date.)
Any tobacco product manufacturer selling cigarettes to consumers within the State (whether directly or through a distributor, retailer or similar intermediary or intermediaries) after May 18, 1999, shall do one of the following:

.. become a participating manufacturer (as that term is defined in section II(jj) of the Master Settlement Agreement) and generally perform its financial obligations under the Master Settlement Agreement; or

.. [Empty]
. place into a qualified escrow fund by April 15 of the year following the year in question the following amounts (as such amounts are adjusted for inflation)—

1999: $.0094241 per unit sold after May 18, 1999;

2000: $.0104712 per unit sold;

for each of 2001 and 2002: $.0136125 per unit sold;

for each of 2003 through 2006: $.0167539 per unit sold;

for each of 2007 and each year thereafter: $.0188482 per unit sold.

. A tobacco product manufacturer that places funds into escrow pursuant to paragraph (1) shall receive the interest or other appreciation on such funds as earned. Such funds themselves shall be released from escrow only under the following circumstances—

(A) to pay a judgment or settlement on any released claim brought against such tobacco product manufacturer by the State or any releasing party located or residing in the State. Funds shall be released from escrow under this subparagraph (i) in the order in which they were placed into escrow and (ii) only to the extent and at the time necessary to make payments required under such judgment or settlement;

(B) to the extent that a tobacco product manufacturer establishes that the amount it was required to place into escrow on account of units sold in the state in a particular year was greater than the Master Settlement Agreement payments, as determined pursuant to section IX(i) of that Agreement including after final determination of all adjustments, that such manufacturer would have been required to make on account of such units sold, had it been a Participating Manufacturer, the excess shall be released from escrow and revert back to such tobacco product manufacturer; or

(C) to the extent not released from escrow under subparagraphs (A) or (B), funds shall be released from escrow and revert back to such tobacco product manufacturer twenty-five years after the date on which they were placed into escrow.

. Each tobacco product manufacturer that elects to place funds into escrow pursuant to this subsection shall annually certify to the Attorney General that it is in compliance with this subsection. The Attorney General may bring a civil action on behalf of the State against any tobacco product manufacturer that fails to place into escrow the funds required under this section. Any tobacco product manufacturer that fails in any year to place into escrow the funds required under this section shall—

(A) be required within 15 days to place such funds into escrow as shall bring it into compliance with this section. The court, upon a finding of a violation of this subsection, may impose a civil penalty to be paid to the general fund of the state in an amount not to exceed 5 percent of the amount improperly withheld from escrow per day of the violation and in a total amount not to exceed 100 percent of the original amount improperly withheld from escrow;

(B) in the case of a knowing violation, be required within 15 days to place such funds into escrow as shall bring it into compliance with this section. The court, upon a finding of a knowing violation of this subsection, may impose a civil penalty to be paid to the general fund of the state in an amount not to exceed 15 percent of the amount improperly withheld from escrow per day of the violation and in a total amount not to exceed 300 percent of the original amount improperly withheld from escrow; and

(C) in the case of a second knowing violation, be prohibited from selling cigarettes to consumers within the State (whether directly or through a distributor, retailer or similar intermediary) for a period not to exceed 2 years.

Each failure to make an annual deposit required under this section shall constitute a separate violation. The violator shall also pay the State's costs and attorney's fees incurred during a successful prosecution under this paragraph (3).

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2038-S.SL.pdf?cite=2003%20c%20342%20§%201[2003 c 342 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5485.SL.pdf?cite=1999%20c%20393%20§%203[1999 c 393 § 3]; ]

== 70.157.030 - Contingent expiration date—Court action.
If chapter 342, Laws of 2003 is held by a court of competent jurisdiction to be unconstitutional, then RCW 70.157.020(b)(2)(B) shall be repealed in its entirety. If RCW 70.157.020(b)(2) shall thereafter be held by a court of competent jurisdiction to be unconstitutional, then chapter 342, Laws of 2003 shall be repealed, and RCW 70.157.020(b)(2)(B) be restored as if no amendments had been made. Neither any holding of unconstitutionality nor the repeal of RCW 70.157.020(b)(2)(B) shall affect, impair, or invalidate any other portion of RCW 70.157.020 or the application of that section to any other person or circumstance, and the remaining portions of RCW 70.157.020 shall at all times continue in full force and effect.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2038-S.SL.pdf?cite=2003%20c%20342%20§%202[2003 c 342 § 2]; ]

