= 70.190 - Family policy council.
:toc:

== 70.190.030 - Proposals to facilitate services at the community level.
The council shall annually solicit from community networks proposals to facilitate greater flexibility, coordination, and responsiveness of services at the community level. The council shall consider such proposals only if:

. A comprehensive plan has been prepared by the community networks;

. The community network has identified and agreed to contribute matching funds as specified in *RCW 70.190.010;

. An interagency agreement has been prepared by the council and the participating local service and support agencies that governs the use of funds, specifies the relationship of the project to the principles listed in RCW 74.14A.025, and identifies specific outcomes and indicators; and

. The community network has designed into its comprehensive plan standards for accountability. Accountability standards include, but are not limited to, the public hearing process eliciting public comment about the appropriateness of the proposed comprehensive plan. The community network must submit reports to the council outlining the public response regarding the appropriateness and effectiveness of the comprehensive plan.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=1994%20sp.s.%20c%207%20§%20316[1994 sp.s. c 7 § 316]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6428-S.SL.pdf?cite=1992%20c%20198%20§%205[1992 c 198 § 5]; ]

== 70.190.050 - Community networks—Outcome evaluation.
. The Washington state institute for public policy shall conduct or contract for monitoring and tracking of the implementation of chapter 7, Laws of 1994 sp. sess. to determine whether these efforts result in a measurable reduction of violence. The institute shall also conduct or contract for an evaluation of the effectiveness of the community public health and safety networks in reducing the rate of at-risk youth through reducing risk factors and increasing protective factors. The evaluation plan shall result in statistically valid evaluation at both statewide and community levels.

. Starting five years after the initial grant to a community network, if the community network fails to meet the outcome standards and goals in any two consecutive years, the institute shall make recommendations to the legislature concerning whether the funds received by that community network should revert back to the originating agency. In making this determination, the institute shall consider the adequacy of the level of intervention relative to the risk factors in the community and any external events having a significant impact on risk factors or outcomes.

. The outcomes required under this chapter and social development standards and measures established by the department of health under RCW 43.70.555 shall be used in conducting the outcome evaluation of the community networks.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%20122[1998 c 245 § 122]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=1994%20sp.s.%20c%207%20§%20207[1994 sp.s. c 7 § 207]; ]

== 70.190.060 - Community networks—Legislative intent—Membership—Open meetings.
. The legislature authorizes community public health and safety networks to reconnect parents and other citizens with children, youth, families, and community institutions which support health and safety. The networks have only those powers and duties expressly authorized under this chapter. The networks should empower parents and other citizens by being a means of expressing their attitudes, spirit, and perspectives regarding safe and healthy family and community life. The legislature intends that parent and other citizen perspectives exercise a controlling influence over policy and program operations of professional organizations concerned with children and family issues within networks in a manner consistent with the Constitution and state law. It is not the intent of the legislature that health, social service, or educational professionals dominate community public health and safety network processes or programs, but rather that these professionals use their skills to lend support to parents and other citizens in expressing their values as parents and other citizens identify community needs and establish community priorities. To this end, the legislature intends full participation of parents and other citizens in community public health and safety networks. The intent is that local community values are reflected in the operations of the network.

. A group of persons described in subsection (3) of this section may apply to be a community public health and safety network.

. Each community public health and safety network shall be composed of twenty-three people, thirteen of whom shall be citizens who live within the network boundary with no fiduciary interest. In selecting these members, first priority shall be given to members of community mobilization advisory boards, city or county children's services commissions, human services advisory boards, or other such organizations. The thirteen persons shall be selected as follows: Three by chambers of commerce, three by school board members, three by county legislative authorities, three by city legislative authorities, and one high school student, selected by student organizations. The remaining ten members shall live or work within the network boundary and shall include local representation selected by the following groups and entities: Cities; counties; federally recognized Indian tribes; parks and recreation programs; law enforcement agencies; state children's service workers; employment assistance workers; private social service providers, broad-based nonsecular organizations, or health service providers; and public education.

. Each of the twenty-three people who are members of each community public health and safety network must sign an annual declaration under penalty of perjury or a notarized statement that clearly, in plain and understandable language, states whether or not he or she has a fiduciary interest. If a member has a fiduciary interest, the nature of that interest must be made clear, in plain understandable language, on the signed statement.

. Members of the network shall serve terms of three years.

The terms of the initial members of each network shall be as follows: (a) One-third shall serve for one year; (b) one-third shall serve for two years; and (c) one-third shall serve for three years. Initial members may agree which shall serve fewer than three years or the decision may be made by lot. Any vacancy occurring during the term may be filled by the chair for the balance of the unexpired term.

. Not less than sixty days before the expiration of a network member's term, the chair shall submit the name of a nominee to the network for its approval. The network shall comply with subsection (3) of this section.

. Networks are subject to the open public meetings act under chapter 42.30 RCW and the public records provisions of chapter 42.56 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20345[2005 c 274 § 345]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2556-S.SL.pdf?cite=1998%20c%20314%20§%2012[1998 c 314 § 12]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5258-S2.SL.pdf?cite=1996%20c%20132%20§%203[1996 c 132 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=1994%20sp.s.%20c%207%20§%20303[1994 sp.s. c 7 § 303]; ]

== 70.190.065 - Member's authorization of expenditures—Limitation.
No network member may vote to authorize, or attempt to influence the authorization of, any expenditure in which the member's immediate family has a fiduciary interest. For the purpose of this section "immediate family" means a spouse, parent, grandparent, adult child, brother, or sister.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5258-S2.SL.pdf?cite=1996%20c%20132%20§%205[1996 c 132 § 5]; ]

== 70.190.070 - Community networks—Duties.
The community public health and safety networks shall:

. Review state and local public health data and analysis relating to risk factors, protective factors, and at-risk children and youth;

. Prioritize the risk factors and protective factors to reduce the likelihood of their children and youth being at risk. The priorities shall be based upon public health data and assessment and policy development standards provided by the department of health under RCW 43.70.555;

. Develop long-term comprehensive plans to reduce the rate of at-risk children and youth; set definitive, measurable goals, based upon the department of health standards; and project their desired outcomes;

. Distribute funds to local programs that reflect the locally established priorities and as provided in *RCW 70.190.140;

. Comply with outcome-based standards;

. Cooperate with the department of health and local boards of health to provide data and determine outcomes; and

. Coordinate its efforts with anti-drug use efforts and organizations and maintain a high priority for combatting drug use by at-risk youth.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=1994%20sp.s.%20c%207%20§%20304[1994 sp.s. c 7 § 304]; ]

== 70.190.075 - Lead fiscal agent.
. Each network shall contract with a public entity as its lead fiscal agent. The contract shall grant the agent authority to perform fiscal, accounting, contract administration, legal, and other administrative duties, including the provision of liability insurance. Any contract under this subsection shall be submitted to the council by the network for approval prior to its execution. The council shall review the contract to determine whether the administrative costs will be held to no more than ten percent.

. The lead agent shall maintain a system of accounting for network funds consistent with the budgeting, accounting, and reporting systems and standards adopted or approved by the state auditor.

. The lead agent may contract with another public or private entity to perform duties other than fiscal or accounting duties.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5258-S2.SL.pdf?cite=1996%20c%20132%20§%204[1996 c 132 § 4]; ]

== 70.190.080 - Community networks—Programs and plans.
. The community network's plan may include a program to provide postsecondary scholarships to at-risk students who: (a) Are community role models under criteria established by the community network; (b) successfully complete high school; and (c) maintain at least a 2.5 grade point average throughout high school. Funding for the scholarships may include public and private sources.

. The community network's plan may also include funding of community-based home visitor programs which are designed to reduce the incidence of child abuse and neglect within the network. Parents shall sign a voluntary authorization for services, which may be withdrawn at any time. The program may provide parents with education and support either in parents' homes or in other locations comfortable for parents, beginning with the birth of their first baby. The program may make the following services available to the families:

.. Visits for all expectant or new parents, either at the parent's home or another location with which the parent is comfortable;

.. Screening before or soon after the birth of a child to assess the family's strengths and goals and define areas of concern in consultation with the family;

.. Parenting education and skills development;

.. Parenting and family support information and referral;

.. Parent support groups; and

.. Service coordination for individual families, and assistance with accessing services, provided in a manner that ensures that individual families have only one individual or agency to which they look for service coordination. Where appropriate for a family, service coordination may be conducted through interdisciplinary or interagency teams.

These programs are intended to be voluntary for the parents involved.

. In developing long-term comprehensive plans to reduce the rate of at-risk children and youth, the community networks shall consider increasing employment and job training opportunities in recognition that they constitute an effective network strategy and strong protective factor. The networks shall consider and may include funding of:

.. At-risk youth job placement and training programs. The programs shall:

... Identify and recruit at-risk youth for local job opportunities;

... Provide skills and needs assessments for each youth recruited;

... Provide career and occupational counseling to each youth recruited;

... Identify businesses willing to provide employment and training opportunities for at-risk youth;

.. Match each youth recruited with a business that meets his or her skills and training needs;

.. Provide employment and training opportunities that prepare the individual for demand occupations; and

.. Include, to the extent possible, collaboration of business, labor, education and training, community organizations, and local government;

.. Employment assistance, including job development, school-to-work placement, employment readiness training, basic skills, apprenticeships, job mentoring, and private sector and community service employment;

.. Education assistance, including tutoring, mentoring, interactions with role models, entrepreneurial education and projects, violence prevention training, safe school strategies, and employment reentry assistance services.

. The community network may include funding of:

.. Peer-to-peer, group, and individual counseling, including crisis intervention, for at-risk youth and their parents;

.. Youth coalitions that provide opportunities to develop leadership skills and gain appropriate respect, recognition, and rewards for their positive contribution to their community;

.. Technical assistance to applicants to increase their organizational capacity and to improve the likelihood of a successful application; and

.. Technical assistance and training resources to successful applicants.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5258-S2.SL.pdf?cite=1996%20c%20132%20§%206[1996 c 132 § 6]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=1994%20sp.s.%20c%207%20§%20305[1994 sp.s. c 7 § 305]; ]

== 70.190.085 - Community networks—Sexual abstinence and activity campaign.
The community network's plan may include funding for a student designed media and community campaign promoting sexual abstinence and addressing the importance of delaying sexual activity and pregnancy or male parenting until individuals are ready to nurture and support their children. Under the campaign, which shall be substantially designed and produced by students, the same messages shall be distributed in schools, through the media, and in the community where the campaign is targeted. The campaign shall require local private sector matching funds equal to state funds. Local private sector funds may include in-kind contributions of technical or other assistance from consultants or firms involved in public relations, advertising, broadcasting, and graphics or video production or other related fields. The campaign shall be evaluated using the outcomes required of community networks under this chapter, in particular reductions in the number or rate of teen pregnancies and teen male parentage over a three to five year period.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2798-S2.SL.pdf?cite=1994%20c%20299%20§%205[1994 c 299 § 5]; ]

== 70.190.090 - Community networks—Planning grants and contracts—Distribution of funds—Reports.
. A network shall, upon application to the council, be eligible to receive planning grants and technical assistance from the council. However, during the 1999-01 fiscal biennium, a network that has not finalized its membership shall be eligible to receive such grants and assistance. Planning grants may be funded through available federal funds for family preservation services. After receiving the planning grant the network has up to one year to submit the long-term comprehensive plan.

. The council shall enter into biennial contracts with networks as part of the grant process. The contracts shall be consistent with available resources, and shall be distributed in accordance with the distribution formula developed pursuant to *RCW 43.41.195, subject to the applicable matching fund requirement.

. No later than February 1 of each odd-numbered year following the initial contract between the council and a network, the council shall request from the network its plan for the upcoming biennial contract period.

. The council shall notify the networks of their allocation of available resources at least sixty days prior to the start of a new biennial contract period.

. The networks shall, by contract, distribute funds (a) appropriated for plan implementation by the legislature, and (b) obtained from nonstate or federal sources. In distributing funds, the networks shall ensure that administrative costs are held to a maximum of ten percent. However, during the 1999-01 fiscal biennium, administrative costs shall be held to a maximum of ten percent or twenty thousand dollars, whichever is greater, exclusive of costs associated with procurement, payroll processing, personnel functions, management, maintenance and operation of space and property, data processing and computer services, indirect costs, and organizational planning, consultation, coordination, and training.

. A network shall not provide services or operate programs.

. A network shall file a report with the council by May 1 of each year that includes but is not limited to the following information: Detailed expenditures, programs under way, progress on contracted services and programs, and successes and problems in achieving the outcomes required by **RCW 70.190.130(1)(h) related to reducing the rate of state-funded out-of-home placements and the other three at-risk behaviors covered by the comprehensive plan and approved by the council.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5180-S.SL.pdf?cite=1999%20c%20309%20§%20918[1999 c 309 § 918]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5258-S2.SL.pdf?cite=1996%20c%20132%20§%207[1996 c 132 § 7]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=1994%20sp.s.%20c%207%20§%20306[1994 sp.s. c 7 § 306]; ]

== 70.190.160 - Community networks—Implementation in federal and state plans.
The implementation of community networks shall be included in all federal and state plans affecting the state's children, youth, and families. The plans shall be consistent with the intent and requirements of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=1994%20sp.s.%20c%207%20§%20314[1994 sp.s. c 7 § 314]; ]

== 70.190.170 - Transfer of funds and programs to state agency.
If a community network is unable or unwilling to assume powers and duties authorized under this chapter by June 30, 1998, or the Washington state institute for public policy makes a recommendation under RCW 70.190.050, the governor may transfer all funds and programs available to a community network to a single state agency whose statutory purpose, mission, goals, and operating philosophy most closely supports the principles and purposes of section 101, chapter 7, Laws of 1994 sp. sess. and RCW 74.14A.020, for the purpose of integrating the programs and services.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=1994%20sp.s.%20c%207%20§%20320[1994 sp.s. c 7 § 320]; ]

== 70.190.180 - Community network—Grants for use of school facilities.
A community public health and safety network, based on rules adopted by the department of health, may include in its comprehensive community plans procedures for providing matching grants to school districts to support expanded use of school facilities for after-hours recreational opportunities and day care as authorized under chapter 28A.215 RCW and RCW 28A.620.010.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=1994%20sp.s.%20c%207%20§%20604[1994 sp.s. c 7 § 604]; ]

== 70.190.190 - Network members immune from civil liability—Network assets not subject to attachment or execution.
. The network members are immune from all civil liability arising from their actions done in their decision-making capacity as a network member, except for their intentional tortious acts or acts of official misconduct.

. The assets of a network are not subject to attachment or execution in satisfaction of a judgment for the tortious acts or official misconduct of any network member or for the acts of any agency or program to which it provides funds.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5258-S2.SL.pdf?cite=1996%20c%20132%20§%209[1996 c 132 § 9]; ]

== 70.190.930 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%20156[2009 c 521 § 156]; ]

