= 70.198 - Early intervention services—Hearing loss.
:toc:

== 70.198.010 - Findings.
. The legislature finds that children who are deaf or hard of hearing and their families have unique needs specific to the hearing loss. These unique needs reflect the challenges children with hearing loss and their families encounter related to their lack of full access to auditory communication.

. The legislature further finds that early detection of hearing loss in a child and early intervention and treatment have been demonstrated to be highly effective in facilitating a child's healthy development in a manner consistent with the child's age and cognitive ability.

. These combined factors support the need for early intervention services providers with specialized training and expertise, spanning the spectrum of available approaches and educational options, who can address the unique characteristics and needs of each child who is deaf or hard of hearing and that child's family.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2765.SL.pdf?cite=2004%20c%2047%20§%201[2004 c 47 § 1]; ]

== 70.198.020 - Advisory council—Membership.
. There is established an advisory council in the department of social and health services for the purpose of advancing the development of a comprehensive and effective statewide system to provide prompt and effective early interventions for children in the state who are deaf or hard of hearing and their families.

. Members of the advisory council shall have training, experience, or interest in hearing loss in children. Membership shall include, but not be limited to, the following: Pediatricians; audiologists; teachers of the deaf and hard of hearing; parents of children who are deaf or hard of hearing; a representative from the Washington center for deaf and hard of hearing youth; and representatives of the early support for infants and toddlers program in the department of children, youth, and families, the department of health, and the office of the superintendent of public instruction.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1604.SL.pdf?cite=2019%20c%20266%20§%2027[2019 c 266 § 27]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6287.SL.pdf?cite=2018%20c%2058%20§%2012[2018 c 58 § 12]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6593.SL.pdf?cite=2010%20c%20233%20§%202[2010 c 233 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1879-S2.SL.pdf?cite=2009%20c%20381%20§%2033[2009 c 381 § 33]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2765.SL.pdf?cite=2004%20c%2047%20§%202[2004 c 47 § 2]; ]

== 70.198.030 - Development of early intervention service standards.
. The advisory council shall develop statewide standards for early intervention services and early intervention services providers specifically related to children who are deaf or hard of hearing.

. The advisory council shall develop these standards by January 1, 2005.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2765.SL.pdf?cite=2004%20c%2047%20§%203[2004 c 47 § 3]; ]

== 70.198.040 - Hearing loss pamphlet.
. The advisory council shall create a pamphlet to be provided to the parents of a child in the state who is diagnosed with hearing loss by their child's pediatrician or audiologist, as appropriate, upon diagnosis of hearing loss. The pamphlet shall contain, at minimum, information on the following: The variety of interventions and treatments available for children who are deaf or hard of hearing; and resources for parent support, counseling, financing, and education related to hearing loss in children.

. The pamphlet shall be available for distribution by July 1, 2005.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2765.SL.pdf?cite=2004%20c%2047%20§%204[2004 c 47 § 4]; ]

