= 70.225 - Prescription monitoring program.
:toc:

== 70.225.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Controlled substance" has the meaning provided in RCW 69.50.101.

. "Department" means the department of health.

. "Patient" means the person or animal who is the ultimate user of a drug for whom a prescription is issued or for whom a drug is dispensed.

. "Dispenser" means a practitioner or pharmacy that delivers a Schedule II, III, IV, or V controlled substance to the ultimate user, but does not include:

.. A practitioner or other authorized person who administers, as defined in RCW 69.41.010, a controlled substance; or

.. A licensed wholesale distributor or manufacturer, as defined in chapter 18.64 RCW, of a controlled substance.

. "Prescriber" means any person authorized to order or prescribe legend drugs or schedule II, III, IV, or V controlled substances to the ultimate user.

. "Requestor" means any person or entity requesting, accessing, or receiving information from the prescription monitoring program under RCW 70.225.040 (3), (4), or (5).

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5380-S.SL.pdf?cite=2019%20c%20314%20§%2020[2019 c 314 § 20]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5930-S2.SL.pdf?cite=2007%20c%20259%20§%2042[2007 c 259 § 42]; ]

== 70.225.020 - Prescription monitoring program—Subject to funding—Duties of dispensers.
. The department shall establish and maintain a prescription monitoring program to monitor the prescribing and dispensing of all Schedules II, III, IV, and V controlled substances and any additional drugs identified by the pharmacy quality assurance commission as demonstrating a potential for abuse by all professionals licensed to prescribe or dispense such substances in this state. The program shall be designed to improve health care quality and effectiveness by reducing abuse of controlled substances, reducing duplicative prescribing and overprescribing of controlled substances, and improving controlled substance prescribing practices with the intent of eventually establishing an electronic database available in real time to dispensers and prescribers of controlled substances. As much as possible, the department should establish a common database with other states. This program's management and operations shall be funded entirely from the funds in the account established under RCW 74.09.215. Nothing in this chapter prohibits voluntary contributions from private individuals and business entities as defined under Title 23, 23B, 24, or 25 RCW to assist in funding the prescription monitoring program.

. Except as provided in subsection (4) of this section, each dispenser shall submit to the department by electronic means information regarding each prescription dispensed for a drug included under subsection (1) of this section. Drug prescriptions for more than one day use should be reported. The information submitted for each prescription shall include, but not be limited to:

.. Patient identifier;

.. Drug dispensed;

.. Date of dispensing;

.. Quantity dispensed;

.. Prescriber; and

.. Dispenser.

. [Empty]
.. Until January 1, 2021, each dispenser shall submit the information in accordance with transmission methods established by the department, not later than one business day from the date of dispensing or at the interval required by the department in rule, whichever is sooner.

.. Beginning January 1, 2021, each dispenser must submit the information as soon as readily available, but no later than one business day from the date of distributing, and in accordance with transmission methods established by the department.

. The data submission requirements of subsections (1) through (3) of this section do not apply to:

.. Medications provided to patients receiving inpatient services provided at hospitals licensed under chapter 70.41 RCW; or patients of such hospitals receiving services at the clinics, day surgery areas, or other settings within the hospital's license where the medications are administered in single doses;

.. Pharmacies operated by the department of corrections for the purpose of providing medications to offenders in department of corrections institutions who are receiving pharmaceutical services from a department of corrections pharmacy, except that the department of corrections must submit data related to each offender's current prescriptions for controlled substances upon the offender's release from a department of corrections institution; or

.. Veterinarians licensed under chapter 18.92 RCW. The department, in collaboration with the veterinary board of governors, shall establish alternative data reporting requirements for veterinarians that allow veterinarians to report:

... By either electronic or nonelectronic methods;

... Only those data elements that are relevant to veterinary practices and necessary to accomplish the public protection goals of this chapter; and

... No more frequently than once every three months and no less frequently than once every six months.

. The department shall continue to seek federal grants to support the activities described in chapter 259, Laws of 2007. The department may not require a practitioner or a pharmacist to pay a fee or tax specifically dedicated to the operation and management of the system.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5380-S.SL.pdf?cite=2019%20c%20314%20§%2021[2019 c 314 § 21]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1565.SL.pdf?cite=2013%20c%2036%20§%202[2013 c 36 § 2]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1609.SL.pdf?cite=2013%20c%2019%20§%20126[2013 c 19 § 126]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6105-S.SL.pdf?cite=2012%20c%20192%20§%201[2012 c 192 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5930-S2.SL.pdf?cite=2007%20c%20259%20§%2043[2007 c 259 § 43]; ]

== 70.225.025 - Rules.
The department shall adopt rules to implement this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5930-S2.SL.pdf?cite=2007%20c%20259%20§%2047[2007 c 259 § 47]; ]

== 70.225.030 - Enhancement of program—Feasibility study.
To the extent that funding is provided for such purpose through federal or private grants, or is appropriated by the legislature, the health care authority shall study the feasibility of enhancing the prescription monitoring program established in RCW 70.225.020 in order to improve the quality of state purchased health services by reducing legend drug abuse, reducing duplicative and overprescribing of legend drugs, and improving legend drug prescribing practices. The study shall address the steps necessary to expand the program to allow those who prescribe or dispense prescription drugs to perform a web-based inquiry and obtain real time information regarding the legend drug utilization history of persons for whom they are providing medical or pharmaceutical care when such persons are receiving health services through state purchased health care programs.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5930-S2.SL.pdf?cite=2007%20c%20259%20§%2044[2007 c 259 § 44]; ]

== 70.225.040 - Confidentiality and exemption from disclosure of prescription monitoring program information—Procedures—Immunity when acting in good faith. (Effective until July 1, 2022.)
. All information submitted to the prescription monitoring program is confidential, exempt from public inspection, copying, and disclosure under chapter 42.56 RCW, not subject to subpoena or discovery in any civil action, and protected under federal health care information privacy requirements, except as provided in subsections (3) through (6) of this section. Such confidentiality and exemption from disclosure continues whenever information from the prescription monitoring program is provided to a requestor under subsection (3), (4), (5), or (6) of this section except when used in proceedings specifically authorized in subsection (3), (4), or (5) of this section.

. The department must maintain procedures to ensure that the privacy and confidentiality of all information collected, recorded, transmitted, and maintained including, but not limited to, the prescriber, requestor, dispenser, patient, and persons who received prescriptions from dispensers, is not disclosed to persons except as in subsections (3) through (6) of this section.

. The department may provide data in the prescription monitoring program to the following persons:

.. Persons authorized to prescribe or dispense controlled substances or legend drugs, for the purpose of providing medical or pharmaceutical care for their patients;

.. An individual who requests the individual's own prescription monitoring information;

.. A health professional licensing, certification, or regulatory agency or entity in this or another jurisdiction. Consistent with current practice, the data provided may be used in legal proceedings concerning the license;

.. Appropriate law enforcement or prosecutorial officials, including local, state, and federal officials and officials of federally recognized tribes, who are engaged in a bona fide specific investigation involving a designated person;

.. The director or the director's designee within the health care authority regarding medicaid recipients and members of the health care authority self-funded or self-insured health plans;

.. The director or director's designee within the department of labor and industries regarding workers' compensation claimants;

.. The director or the director's designee within the department of corrections regarding offenders committed to the department of corrections;

.. Other entities under grand jury subpoena or court order;

.. Personnel of the department for purposes of:

... Assessing prescribing and treatment practices and morbidity and mortality related to use of controlled substances and developing and implementing initiatives to protect the public health including, but not limited to, initiatives to address opioid use disorder;

... Providing quality improvement feedback to prescribers, including comparison of their respective data to aggregate data for prescribers with the same type of license and same specialty; and

... Administration and enforcement of this chapter or chapter 69.50 RCW;

.. Personnel of a test site that meet the standards under RCW 70.225.070 pursuant to an agreement between the test site and a person identified in (a) of this subsection to provide assistance in determining which medications are being used by an identified patient who is under the care of that person;

.. A health care facility or entity for the purpose of providing medical or pharmaceutical care to the patients of the facility or entity, or for quality improvement purposes if the facility or entity is licensed by the department or is licensed or certified under chapter 71.24, 71.34, or 71.05 RCW or is an entity deemed for purposes of chapter 71.24 RCW to meet state minimum standards as a result of accreditation by a recognized behavioral health accrediting body, or is operated by the federal government or a federally recognized Indian tribe;

.. A health care provider group of five or more prescribers or dispensers for purposes of providing medical or pharmaceutical care to the patients of the provider group, or for quality improvement purposes if all the prescribers or dispensers in the provider group are licensed by the department or the provider group is operated by the federal government or a federally recognized Indian tribe;

.. The local health officer of a local health jurisdiction for the purposes of patient follow-up and care coordination following a controlled substance overdose event. For the purposes of this subsection "local health officer" has the same meaning as in RCW 70.05.010; and

.. The coordinated care electronic tracking program developed in response to section 213, chapter 7, Laws of 2012 2nd sp. sess., commonly referred to as the seven best practices in emergency medicine, for the purposes of providing:

... Prescription monitoring program data to emergency department personnel when the patient registers in the emergency department; and

... Notice to local health officers who have made opioid-related overdose a notifiable condition under RCW 70.05.070 as authorized by rules adopted under RCW 43.20.050, providers, appropriate care coordination staff, and prescribers listed in the patient's prescription monitoring program record that the patient has experienced a controlled substance overdose event. The department shall determine the content and format of the notice in consultation with the Washington state hospital association, Washington state medical association, and Washington state health care authority, and the notice may be modified as necessary to reflect current needs and best practices.

. The department shall, on at least a quarterly basis, and pursuant to a schedule determined by the department, provide a facility or entity identified under subsection (3)(k) of this section or a provider group identified under subsection (3)(l) of this section with facility or entity and individual prescriber information if the facility, entity, or provider group:

.. Uses the information only for internal quality improvement and individual prescriber quality improvement feedback purposes and does not use the information as the sole basis for any medical staff sanction or adverse employment action; and

.. Provides to the department a standardized list of current prescribers of the facility, entity, or provider group. The specific facility, entity, or provider group information provided pursuant to this subsection and the requirements under this subsection must be determined by the department in consultation with the Washington state hospital association, Washington state medical association, and Washington state health care authority, and may be modified as necessary to reflect current needs and best practices.

. [Empty]
.. The department may publish or provide data to public or private entities for statistical, research, or educational purposes after removing information that could be used directly or indirectly to identify individual patients, requestors, dispensers, prescribers, and persons who received prescriptions from dispensers. Direct and indirect patient identifiers may be provided for research that has been approved by the Washington state institutional review board and by the department through a data-sharing agreement.

.. [Empty]
... The department may provide dispenser and prescriber data and data that includes indirect patient identifiers to the Washington state hospital association for use solely in connection with its coordinated quality improvement program maintained under RCW 43.70.510 after entering into a data use agreement as specified in *RCW 43.70.052(8) with the association. The department may provide dispenser and prescriber data and data that includes indirect patient identifiers to the Washington state medical association for use solely in connection with its coordinated quality improvement program maintained under RCW 43.70.510 after entering into a data use agreement with the association.

... The department may provide data including direct and indirect patient identifiers to the department of social and health services office of research and data analysis, the department of labor and industries, and the health care authority for research that has been approved by the Washington state institutional review board and, with a data-sharing agreement approved by the department, for public health purposes to improve the prevention or treatment of substance use disorders.

... The department may provide a prescriber feedback report to the largest health professional association representing each of the prescribing professions. The health professional associations must distribute the feedback report to prescribers engaged in the professions represented by the associations for quality improvement purposes, so long as the reports contain no direct patient identifiers that could be used to identify individual patients, dispensers, and persons who received prescriptions from dispensers, and the association enters into a written data-sharing agreement with the department. However, reports may include indirect patient identifiers as agreed to by the department and the association in a written data-sharing agreement.

.. For the purposes of this subsection:

... "Indirect patient identifiers" means data that may include: Hospital or provider identifiers, a five-digit zip code, county, state, and country of resident; dates that include month and year; age in years; and race and ethnicity; but does not include the patient's first name; middle name; last name; social security number; control or medical record number; zip code plus four digits; dates that include day, month, and year; or admission and discharge date in combination; and

... "Prescribing professions" include:

(A) Allopathic physicians and physician assistants;

(B) Osteopathic physicians and physician assistants;

(C) Podiatric physicians;

(D) Dentists; and

(E) Advanced registered nurse practitioners.

. The department may enter into agreements to exchange prescription monitoring program data with established prescription monitoring programs in other jurisdictions. Under these agreements, the department may share prescription monitoring system data containing direct and indirect patient identifiers with other jurisdictions through a clearinghouse or prescription monitoring program data exchange that meets federal health care information privacy requirements. Data the department receives from other jurisdictions must be retained, used, protected, and destroyed as provided by the agreements to the extent consistent with the laws in this state.

. Persons authorized in subsections (3) through (6) of this section to receive data in the prescription monitoring program from the department, acting in good faith, are immune from any civil, criminal, disciplinary, or administrative liability that might otherwise be incurred or imposed for acting under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5380-S.SL.pdf?cite=2019%20c%20314%20§%2023[2019 c 314 § 23]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1427-S.SL.pdf?cite=2017%20c%20297%20§%209[2017 c 297 § 9]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2730-S.SL.pdf?cite=2016%20c%20104%20§%201[2016 c 104 § 1]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5027-S.SL.pdf?cite=2015%20c%20259%20§%201[2015 c 259 § 1]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1637.SL.pdf?cite=2015%20c%2049%20§%201[2015 c 49 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1738-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2015%20§%2087[2011 1st sp.s. c 15 § 87]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5930-S2.SL.pdf?cite=2007%20c%20259%20§%2045[2007 c 259 § 45]; ]

== 70.225.045 - Annual report.
Beginning November 15, 2017, the department shall annually report to the governor and the appropriate committees of the legislature on the number of facilities, entities, or provider groups identified in *RCW 70.225.040(3) (l) and (m) that have integrated their federally certified electronic health records with the prescription monitoring program utilizing the state health information exchange.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1427-S.SL.pdf?cite=2017%20c%20297%20§%2010[2017 c 297 § 10]; ]

== 70.225.050 - Department may contract for operation of program.
The department may contract with another agency of this state or with a private vendor, as necessary, to ensure the effective operation of the prescription monitoring program. Any contractor is bound to comply with the provisions regarding confidentiality of prescription information in RCW 70.225.040 and is subject to the penalties specified in RCW 70.225.060 for unlawful acts.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5930-S2.SL.pdf?cite=2007%20c%20259%20§%2046[2007 c 259 § 46]; ]

== 70.225.060 - Violations—Penalties—Disclosure exemption for health care providers.
. A dispenser who knowingly fails to submit prescription monitoring information to the department as required by this chapter or knowingly submits incorrect prescription information is subject to disciplinary action under chapter 18.130 RCW.

. A person authorized to have prescription monitoring information under this chapter who knowingly discloses such information in violation of this chapter is subject to civil penalty.

. A person authorized to have prescription monitoring information under this chapter who uses such information in a manner or for a purpose in violation of this chapter is subject to civil penalty.

. In accordance with chapter 70.02 RCW and federal health care information privacy requirements, any physician or pharmacist authorized to access a patient's prescription monitoring may discuss or release that information to other health care providers involved with the patient in order to provide safe and appropriate care coordination.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5930-S2.SL.pdf?cite=2007%20c%20259%20§%2048[2007 c 259 § 48]; ]

== 70.225.070 - Requirements for test sites in the prescription monitoring program.
. Test sites that may receive access to data in the prescription monitoring program under RCW 70.225.040 must be:

.. Licensed by the department as a test site under chapter 70.42 RCW; and

.. Certified as a drug testing laboratory by the United States department of health and human services, substance abuse and mental health services administration.

. Test sites may not:

.. Charge a fee for accessing the prescription monitoring program;

.. Store data accessed from the prescription drug monitoring program in any form, including, but not limited to, hard copies, electronic copies, or web/digital based copies of any kind. Such data may be used only to transmit to those entities listed in *RCW 70.255.040(3)(a).

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5027-S.SL.pdf?cite=2015%20c%20259%20§%202[2015 c 259 § 2]; ]

== 70.225.080 - Access to data in the qualifying laboratory.
. Access to data in the qualifying laboratory must be under the supervision of the responsible person as designated by the United States department of health and human services, substance abuse and mental health services administration certification program.

. Such data cannot be gathered, shared, sold, or used in any manner other than as designated under RCW * 70.255.040, RCW 70.225.070, or this section.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5027-S.SL.pdf?cite=2015%20c%20259%20§%203[2015 c 259 § 3]; ]

== 70.225.090 - Integration with certified electronic health record technologies.
. In order to expand integration of prescription monitoring program data into certified electronic health record technologies, the department must collaborate with health professional and facility associations, vendors, and others to:

.. Conduct an assessment of the current status of integration;

.. Provide recommendations for improving integration among small and rural health care facilities, offices, and clinics;

.. Comply with federal prescription drug monitoring program qualification requirements under 42 U.S.C. Sec. 1396w-3a to facilitate eligibility for federal grants and establish a program to provide financial assistance to small and rural health care facilities and clinics with integration as funding is available, especially under federal programs;

.. Conduct security assessments of other commonly used platforms for integrating prescription monitoring program data with certified electronic health records for possible use in Washington; and

.. Assess improvements to the prescription monitoring program to establish a modality to identify patients that do not wish to receive opioid medications in a manner that allows an ordering or prescribing physician to be able to use the prescription monitoring program to identify patients who do not wish to receive opioids or patients that have had an opioid-related overdose.

. [Empty]
.. By January 1, 2021, a facility, entity, office, or provider group identified in RCW 70.225.040 with ten or more prescribers that is not a critical access hospital as defined in RCW 74.60.010 that uses a federally certified electronic health records system must demonstrate that the facility's or entity's federally certified electronic health record is able to fully integrate data to and from the prescription monitoring program using a mechanism approved by the department under subsection (3) of this section.

.. The department must develop a waiver process for the requirements of (a) of this subsection for facilities, entities, offices, or provider groups due to economic hardship, technological limitations that are not reasonably in the control of the facility, entity, office, or provider group, or other exceptional circumstance demonstrated by the facility, entity, office, or provider group. The waiver must be limited to one year or less, or for any other specified time frame set by the department.

. Electronic health record system vendors who are fully integrated with the prescription monitoring program in Washington state may not charge an ongoing fee or a fee based on the number of transactions or providers. Total costs of connection must not impose unreasonable costs on any facility, entity, office, or provider group using the electronic health record and must be consistent with current industry pricing structures. For the purposes of this subsection, "fully integrated" means that the electronic health records system must:

.. Send information to the prescription monitoring program without provider intervention using a mechanism approved by the department;

.. Make current information from the prescription monitoring program available to a provider within the workflow of the electronic health records system; and

.. Make information available in a way that is unlikely to interfere with, prevent, or materially discourage access, exchange, or use of electronic health information, in accordance with the information blocking provisions of the federal twenty-first century cures act, P.L. 114-255.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5380-S.SL.pdf?cite=2019%20c%20314%20§%2022[2019 c 314 § 22]; ]

== 70.225.900 - Severability—Subheadings not law—2007 c 259.
See notes following RCW 41.05.033.

[ ]

