= 70.255 - Novelty lighters.
:toc:

== 70.255.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Authority having jurisdiction" means the local organization, office, or individual responsible for enforcing the requirements of the state fire code.

. "Director" means the director of fire protection appointed under RCW 43.43.938.

. "Distribute" means to do any of the following:

.. Sell novelty lighters or deliver novelty lighters for sale by another person to consumers;

.. Sell or accept orders for novelty lighters that are to be transported from a point outside this state to a consumer within this state;

.. Buy novelty lighters directly from a manufacturer or wholesale dealer for resale in this state;

.. Give novelty lighters as a sample, prize, gift, or other promotion.

. "Manufacturer" means:

.. An entity that produces, or causes the production of, novelty lighters for sale in this state;

.. An importer or first purchaser of novelty lighters that intends to resell within this state novelty lighters that were produced for sale outside this state; or

.. A successor to an entity, importer, or first purchaser described in (a) or (b) of this subsection.

. [Empty]
.. "Novelty lighter" means a lighter that can operate on any fuel, including butane or liquid fuel. Novelty lighters have features that are attractive to children, including but not limited to visual effects, flashing lights, musical sounds, and toylike designs. The term considers the shape of the lighter to be the most important characteristic when determining whether a lighter can be considered a novelty lighter.

.. "Novelty lighter" does not include disposable cigarette lighters or lighters that are printed or decorated with logos, decals, artwork, or heat shrinkable sleeves.

. "Retail dealer" means an entity at one location, other than a manufacturer or wholesale dealer, that engages in distributing novelty lighters.

. "Sell" means to transfer, or agree to transfer, title or possession for a monetary or nonmonetary consideration.

. "Wholesale dealer" means an entity that distributes novelty lighters to a retail dealer or other person for resale.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5011-S.SL.pdf?cite=2009%20c%20273%20§%201[2009 c 273 § 1]; ]

== 70.255.020 - Prohibition on the distribution or offer to sell novelty lighters.
. A person may not distribute or offer to sell a novelty lighter within this state if the director determines the novelty lighter is prohibited for sale or distribution under this chapter.

. This section does not apply if the novelty lighters are in interstate commerce and not intended for distribution in this state.

. The authority having jurisdiction shall enforce the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5011-S.SL.pdf?cite=2009%20c%20273%20§%202[2009 c 273 § 2]; ]

== 70.255.030 - Civil penalty—Jurisdiction.
. The authority having jurisdiction may impose a civil penalty for a violation of this chapter. The civil penalty may not exceed:

.. For a wholesale dealer that distributes or offers to sell novelty lighters to retail dealers or consumers, a written warning for the first violation and a monetary penalty of five hundred dollars for each subsequent violation.

.. For a retail dealer that distributes or offers to sell novelty lighters to consumers, a written warning for the first violation and a monetary penalty of two hundred fifty dollars for each subsequent violation.

. The authority having jurisdiction may bring an action seeking:

.. Injunctive relief to prevent or end a violation of this chapter;

.. To recover civil penalties imposed under subsection (1) of this section; or

.. To recover attorneys' fees and other enforcement costs and disbursements.

. Penalties under this section must be deposited in an account designated by the authority having jurisdiction.

. A district court has jurisdiction over all proceedings brought under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5011-S.SL.pdf?cite=2009%20c%20273%20§%203[2009 c 273 § 3]; ]

== 70.255.040 - Manufacturers must cease sale or distribution.
. On July 26, 2009, manufacturers must immediately cease the sale or distribution of novelty lighters in this state.

. On July 26, 2009, wholesalers and retail dealers have a maximum of ninety days to reduce their current inventory of novelty lighters. In no instance may wholesalers and retail dealers sell or distribute a novelty lighter in this state after ninety days from July 26, 2009.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5011-S.SL.pdf?cite=2009%20c%20273%20§%204[2009 c 273 § 4]; ]

