= 70.230 - Ambulatory surgical facilities.
:toc:

== 70.230.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Ambulatory surgical facility" means any distinct entity that operates for the primary purpose of providing specialty or multispecialty outpatient surgical services in which patients are admitted to and discharged from the facility within twenty-four hours and do not require inpatient hospitalization, whether or not the facility is certified under Title XVIII of the federal social security act. An ambulatory surgical facility includes one or more surgical suites that are adjacent to and within the same building as, but not in, the office of a practitioner in an individual or group practice, if the primary purpose of the one or more surgical suites is to provide specialty or multispecialty outpatient surgical services, irrespective of the type of anesthesia administered in the one or more surgical suites. An ambulatory surgical facility that is adjacent to and within the same building as the office of a practitioner in an individual or group practice may include a surgical suite that shares a reception area, restroom, waiting room, or wall with the office of the practitioner in an individual or group practice.

. "Department" means the department of health.

. "General anesthesia" means a state of unconsciousness intentionally produced by anesthetic agents, with absence of pain sensation over the entire body, in which the patient is without protective reflexes and is unable to maintain an airway.

. "Person" means an individual, firm, partnership, corporation, company, association, joint stock association, and the legal successor thereof.

. "Practitioner" means any physician or surgeon licensed under chapter 18.71 RCW, an osteopathic physician or surgeon licensed under chapter 18.57 RCW, or a podiatric physician or surgeon licensed under chapter 18.22 RCW.

. "Secretary" means the secretary of health.

. "Surgical services" means invasive medical procedures that:

.. Utilize a knife, laser, cautery, cryogenics, or chemicals; and

.. Remove, correct, or facilitate the diagnosis or cure of a disease, process, or injury through that branch of medicine that treats diseases, injuries, and deformities by manual or operative methods by a practitioner.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1575-S.SL.pdf?cite=2011%20c%2076%20§%201[2011 c 76 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1414-S.SL.pdf?cite=2007%20c%20273%20§%201[2007 c 273 § 1]; ]

== 70.230.020 - Duties of secretary—Rules.
The secretary shall:

. Issue a license to any ambulatory surgical facility that:

.. Submits payment of the fee established in RCW 43.70.110 and 43.70.250;

.. Submits a completed application that demonstrates the ability to comply with the standards established for operating and maintaining an ambulatory surgical facility in statute and rule. An ambulatory surgical facility shall be deemed to have met the standards if it submits proof of certification as a medicare ambulatory surgical facility or accreditation by an organization that the secretary has determined to have substantially equivalent standards to those of the department; and

.. Successfully completes the survey requirements established in RCW 70.230.100;

. Develop an application form for applicants for a license to operate an ambulatory surgical facility;

. Initiate investigations and enforcement actions for complaints or other information regarding failure to comply with this chapter or the standards and rules adopted under this chapter;

. Conduct surveys of facilities, including reviews of medical records and documents required to be maintained under this chapter or rules adopted under this chapter;

. By March 1, 2008, determine which accreditation organizations have substantially equivalent standards for purposes of deeming specific licensing requirements required in statute and rule as having met the state's standards; and

. Adopt any rules necessary to implement this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5778-S.SL.pdf?cite=2016%20c%20146%20§%202[2016 c 146 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1414-S.SL.pdf?cite=2007%20c%20273%20§%202[2007 c 273 § 2]; ]

== 70.230.030 - Operating without a license.
Except as provided in RCW 70.230.040, after June 30, 2009, no person or governmental unit of the state of Washington, acting separately or jointly with any other person or governmental unit, shall establish, maintain, or conduct an ambulatory surgical facility in this state or advertise by using the term "ambulatory surgical facility," "day surgery center," "licensed surgical center," or other words conveying similar meaning without a license issued by the department under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1414-S.SL.pdf?cite=2007%20c%20273%20§%203[2007 c 273 § 3]; ]

== 70.230.040 - Exclusions from chapter.
Nothing in this chapter:

. Applies to an ambulatory surgical facility that is maintained and operated by a hospital licensed under chapter 70.41 RCW;

. Applies to an office maintained for the practice of dentistry;

. Applies to outpatient specialty or multispecialty surgical services routinely and customarily performed in the office of a practitioner in an individual or group practice, where the primary purpose of the office is not as set forth in RCW 70.230.010(1), provided that any surgical services in which general anesthesia is a planned event must be performed only in an ambulatory surgical facility as defined in this chapter or in a hospital or hospital-associated surgical center licensed under chapter 70.41 RCW; or

. Limits an ambulatory surgical facility to performing only surgical services.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1575-S.SL.pdf?cite=2011%20c%2076%20§%202[2011 c 76 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1414-S.SL.pdf?cite=2007%20c%20273%20§%204[2007 c 273 § 4]; ]

== 70.230.050 - Licenses—Applicants—Renewal.
. An applicant for a license to operate an ambulatory surgical facility must demonstrate the ability to comply with the standards established for operating and maintaining an ambulatory surgical facility in statute and rule, including:

.. Submitting a written application to the department providing all necessary information on a form provided by the department, including a list of surgical specialties offered;

.. Submitting building plans for review and approval by the department for new construction, alterations other than minor alterations, and additions to existing facilities, prior to obtaining a license and occupying the building;

.. Demonstrating the ability to comply with this chapter and any rules adopted under this chapter;

.. Cooperating with the department during on-site surveys prior to obtaining an initial license or renewing an existing license;

.. Providing such proof as the department may require concerning the ownership and management of the ambulatory surgical facility, including information about the organization and governance of the facility and the identity of the applicant, officers, directors, partners, managing employees, or owners of ten percent or more of the applicant's assets;

.. Submitting proof of operation of a coordinated quality improvement program in accordance with RCW 70.230.080;

.. Submitting a copy of the facility safety and emergency training program established under RCW 70.230.060;

.. Paying any fees established by the secretary under RCW 43.70.110 and 43.70.250; and

.. Providing any other information that the department may reasonably require.

. A license is valid for three years, after which an ambulatory surgical facility must submit an application for renewal of license upon forms provided by the department and the renewal fee as established in RCW 43.70.110 and 43.70.250. The applicant must demonstrate the ability to comply with the standards established for operating and maintaining an ambulatory surgical facility in statutes, standards, and rules. The applicant must submit the license renewal document no later than thirty days prior to the date of expiration of the license.

. The applicant may demonstrate compliance with any of the requirements of subsection (1) of this section by providing satisfactory documentation to the secretary that it has met the standards of an accreditation organization or federal agency that the secretary has determined to have substantially equivalent standards as the statutes and rules of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5778-S.SL.pdf?cite=2016%20c%20146%20§%203[2016 c 146 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1414-S.SL.pdf?cite=2007%20c%20273%20§%205[2007 c 273 § 5]; ]

== 70.230.060 - Facility safety and emergency training.
An ambulatory surgical facility shall have a facility safety and emergency training program. The program shall include:

. On-site equipment, medication, and trained personnel to facilitate handling of services sought or provided and to facilitate the management of any medical emergency that may arise in connection with services sought or provided;

. Written transfer agreements with local hospitals licensed under chapter 70.41 RCW, approved by the ambulatory surgical facility's medical staff; and

. A procedural plan for handling medical emergencies that shall be available for review during surveys and inspections.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1414-S.SL.pdf?cite=2007%20c%20273%20§%206[2007 c 273 § 6]; ]

== 70.230.070 - Denial, suspension, or revocation of license—Investigating complaints—Penalties.
. The secretary may deny, suspend, or revoke the license of any ambulatory surgical facility in any case in which he or she finds the applicant or registered entity knowingly made a false statement of material fact in the application for the license or any supporting data in any record required by this chapter or matter under investigation by the department.

. The secretary shall investigate complaints concerning operation of an ambulatory surgical facility without a license. The secretary may issue a notice of intention to issue a cease and desist order to any person whom the secretary has reason to believe is engaged in the unlicensed operation of an ambulatory surgical facility. If the secretary makes a written finding of fact that the public interest will be irreparably harmed by delay in issuing an order, the secretary may issue a temporary cease and desist order. The person receiving a temporary cease and desist order shall be provided an opportunity for a prompt hearing. The temporary cease and desist order shall remain in effect until further order of the secretary. Any person operating an ambulatory surgical facility under this chapter without a license is guilty of a misdemeanor, and each day of operation of an unlicensed ambulatory surgical facility constitutes a separate offense.

. The secretary is authorized to deny, suspend, revoke, or modify a license or provisional license in any case in which it finds that there has been a failure or refusal to comply with the requirements of this chapter or the standards or rules adopted under this chapter. RCW 43.70.115 governs notice of a license denial, revocation, suspension, or modification and provides the right to an adjudicative proceeding.

. Pursuant to chapter 34.05 RCW, the secretary may assess monetary penalties of a civil nature not to exceed one thousand dollars per violation.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1414-S.SL.pdf?cite=2007%20c%20273%20§%208[2007 c 273 § 8]; ]

== 70.230.080 - Coordinated quality improvement—Rules.
. Every ambulatory surgical facility shall maintain a coordinated quality improvement program for the improvement of the quality of health care services rendered to patients and the identification and prevention of medical malpractice. The program shall include at least the following:

.. The establishment of one or more quality improvement committees with the responsibility to review the services rendered in the ambulatory surgical facility, both retrospectively and prospectively, in order to improve the quality of medical care of patients and to prevent medical malpractice. Different quality improvement committees may be established as a part of the quality improvement program to review different health care services. Such committees shall oversee and coordinate the quality improvement and medical malpractice prevention program and shall ensure that information gathered pursuant to the program is used to review and to revise the policies and procedures of the ambulatory surgical facility;

.. A process, including a medical staff privileges sanction procedure which must be conducted substantially in accordance with medical staff bylaws and applicable rules, regulations, or policies of the medical staff through which credentials, physical and mental capacity, professional conduct, and competence in delivering health care services are periodically reviewed as part of an evaluation of staff privileges;

.. The periodic review of the credentials, physical and mental capacity, and competence in delivering health care services of all persons who are employed or associated with the ambulatory surgical facility;

.. A procedure for the prompt resolution of grievances by patients or their representatives related to accidents, injuries, treatment, and other events that may result in claims of medical malpractice;

.. The maintenance and continuous collection of information concerning the ambulatory surgical facility's experience with negative health care outcomes and incidents injurious to patients, patient grievances, professional liability premiums, settlements, awards, costs incurred by the ambulatory surgical facility for patient injury prevention, and safety improvement activities;

.. The maintenance of relevant and appropriate information gathered pursuant to (a) through (e) of this subsection concerning individual practitioners within the practitioner's personnel or credential file maintained by the ambulatory surgical facility;

.. Education programs dealing with quality improvement, patient safety, medication errors, injury prevention, staff responsibility to report professional misconduct, the legal aspects of patient care, improved communication with patients, and causes of malpractice claims for staff personnel engaged in patient care activities; and

.. Policies to ensure compliance with the reporting requirements of this section.

. Any person who, in substantial good faith, provides information to further the purposes of the quality improvement and medical malpractice prevention program or who, in substantial good faith, participates on the quality improvement committee is not subject to an action for civil damages or other relief as a result of such activity. Any person or entity participating in a coordinated quality improvement program that, in substantial good faith, shares information or documents with one or more other programs, committees, or boards under subsection (8) of this section is not subject to an action for civil damages or other relief as a result of the activity. For the purposes of this section, sharing information is presumed to be in substantial good faith. However, the presumption may be rebutted upon a showing of clear, cogent, and convincing evidence that the information shared was knowingly false or deliberately misleading.

. Information and documents, including complaints and incident reports, created specifically for, and collected and maintained by, a quality improvement committee are not subject to review or disclosure, except as provided in this section, or discovery or introduction into evidence in any civil action, and no person who was in attendance at a meeting of such committee or who participated in the creation, collection, or maintenance of information or documents specifically for the committee shall be permitted or required to testify in any civil action as to the content of such proceedings or the documents and information prepared specifically for the committee. This subsection does not preclude: (a) In any civil action, the discovery of the identity of persons involved in the medical care that is the basis of the civil action whose involvement was independent of any quality improvement activity; (b) in any civil action, the testimony of any person concerning the facts which form the basis for the institution of such proceedings of which the person had personal knowledge acquired independently of such proceedings; (c) in any civil action by a health care provider regarding the restriction or revocation of that individual's clinical or staff privileges, introduction into evidence of information collected and maintained by quality improvement committees regarding such health care provider; (d) in any civil action, disclosure of the fact that staff privileges were terminated or restricted, including the specific restrictions imposed, if any, and the reasons for the restrictions; or (e) in any civil action, discovery and introduction into evidence of the patient's medical records required by rule of the department to be made regarding the care and treatment received.

. Each quality improvement committee shall, on at least a semiannual basis, report to the management of the ambulatory surgical facility, as identified in the facility's application, in which the committee is located. The report shall review the quality improvement activities conducted by the committee, and any actions taken as a result of those activities.

. The department shall adopt such rules as are deemed appropriate to effectuate the purposes of this section.

. The Washington medical commission, the board of osteopathic medicine and surgery, or the podiatric medical board, as appropriate, may review and audit the records of committee decisions in which a practitioner's privileges are terminated or restricted. Each ambulatory surgical facility shall produce and make accessible to the commission or board the appropriate records and otherwise facilitate the review and audit. Information so gained is not subject to the discovery process and confidentiality shall be respected as required by subsection (3) of this section. Failure of an ambulatory surgical facility to comply with this subsection is punishable by a civil penalty not to exceed two hundred fifty dollars.

. The department and any accrediting organization may review and audit the records of a quality improvement committee or peer review committee in connection with their inspection and review of the ambulatory surgical facility. Information so obtained is not subject to the discovery process, and confidentiality shall be respected as required by subsection (3) of this section. Each ambulatory surgical facility shall produce and make accessible to the department the appropriate records and otherwise facilitate the review and audit.

. A coordinated quality improvement program may share information and documents, including complaints and incident reports, created specifically for, and collected and maintained by, a quality improvement committee or a peer review committee under RCW 4.24.250 with one or more other coordinated quality improvement programs maintained in accordance with this section or RCW 43.70.510 or 70.41.200, a quality assurance committee maintained in accordance with RCW 18.20.390 or 74.42.640, or a peer review committee under RCW 4.24.250, for the improvement of the quality of health care services rendered to patients and the identification and prevention of medical malpractice. The privacy protections of chapter 70.02 RCW and the federal health insurance portability and accountability act of 1996 and its implementing regulations apply to the sharing of individually identifiable patient information held by a coordinated quality improvement program. Any rules necessary to implement this section shall meet the requirements of applicable federal and state privacy laws. Information and documents disclosed by one coordinated quality improvement program to another coordinated quality improvement program or a peer review committee under RCW 4.24.250 and any information and documents created or maintained as a result of the sharing of information and documents are not subject to the discovery process and confidentiality shall be respected as required by subsection (3) of this section, RCW 18.20.390 (6) and (8), 70.41.200(3), 74.42.640 (7) and (9), and 4.24.250.

. An ambulatory surgical facility that participates in a coordinated quality improvement program under RCW 43.70.510 shall be deemed to have met the requirements of this section.

. Violation of this section shall not be considered negligence per se.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5764.SL.pdf?cite=2019%20c%2055%20§%2016[2019 c 55 § 16]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5666.SL.pdf?cite=2013%20c%20301%20§%204[2013 c 301 § 4]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1414-S.SL.pdf?cite=2007%20c%20273%20§%209[2007 c 273 § 9]; ]

== 70.230.090 - Ambulatory surgical facilities—Construction, maintenance, and operation—Minimum standards and rules.
The department shall establish and adopt such minimum standards and rules pertaining to the construction, maintenance, and operation of ambulatory surgical facilities and rescind, amend, or modify such rules, as are necessary in the public interest, and particularly for the establishment and maintenance of standards of patient care required for the safe and adequate care and treatment of patients. In establishing the format and content of these standards and rules, the department shall give consideration to maintaining consistency with such minimum standards and rules applicable to ambulatory surgical facilities in the survey standards of accrediting organizations or federal agencies that the secretary has determined to have substantially equivalent standards as the statutes and rules of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1414-S.SL.pdf?cite=2007%20c%20273%20§%2010[2007 c 273 § 10]; ]

== 70.230.100 - Ambulatory surgical facilities—Surveys.
. The department shall make or cause to be made a survey of all ambulatory surgical facilities according to the following frequency:

.. Except as provided in (b) of this subsection, an ambulatory surgical facility must be surveyed by the department no more than once every eighteen months.

.. An ambulatory surgical facility must be surveyed by the department no more than once every thirty-six months if the ambulatory surgical facility:

... Has had, within eighteen months of a department survey, a survey in connection with its certification by the centers for medicare and medicaid services or accreditation by an accreditation organization approved by the department under RCW 70.230.020(5);

... Has maintained certification by the centers for medicare and medicaid services or accreditation by an accreditation organization approved by the department under RCW 70.230.020(5) since the survey in connection with its certification or accreditation pursuant to (b)(i) of this subsection; and

... As soon as practicable after a survey in connection with its certification or accreditation pursuant to (b)(i) of this subsection, provides the department with documentary evidence that the ambulatory surgical facility is certified or accredited and that the survey has occurred, including the date that the survey occurred.

. Every survey of an ambulatory surgical facility may include an inspection of every part of the surgical facility. The department may make an examination of all phases of the ambulatory surgical facility operation necessary to determine compliance with all applicable statutes, rules, and regulations. In the event that the department is unable to make a survey or cause a survey to be made during the three years of the term of the license, the license of the ambulatory surgical facility shall remain in effect until the state conducts a survey or a substitute survey is performed if the ambulatory surgical facility is in compliance with all other licensing requirements.

. Ambulatory surgical facilities shall make the written reports of surveys conducted pursuant to medicare certification procedures or by an approved accrediting organization available to department surveyors during any department surveys or upon request.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5778-S.SL.pdf?cite=2016%20c%20146%20§%204[2016 c 146 § 4]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1414-S.SL.pdf?cite=2007%20c%20273%20§%2011[2007 c 273 § 11]; ]

== 70.230.110 - Ambulatory surgical facilities—Submission of data related to the quality of patient care.
The department shall require ambulatory surgical facilities to submit data related to the quality of patient care for review by the department. The data shall be submitted every eighteen months. The department shall consider the reporting standards of other public and private organizations that measure quality in order to maintain consistency in reporting and minimize the burden on the ambulatory surgical facility. The department shall review the data to determine the maintenance of quality patient care at the facility. If the department determines that the care offered at the facility may present a risk to the health and safety of patients, the department may conduct an inspection of the facility and initiate appropriate actions to protect the public. Information submitted to the department pursuant to this section shall be exempt from disclosure under chapter 42.56 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1414-S.SL.pdf?cite=2007%20c%20273%20§%2012[2007 c 273 § 12]; ]

== 70.230.120 - Reports—Discipline of a health care provider for unprofessional conduct—Penalties.
. The chief administrator or executive officer of an ambulatory surgical facility shall report to the department when the practice of a health care provider licensed by a disciplining authority under RCW 18.130.040 is restricted, suspended, limited, or terminated based upon a conviction, determination, or finding by the ambulatory surgical facility that the provider has committed an action defined as unprofessional conduct under RCW 18.130.180. The chief administrator or executive officer shall also report any voluntary restriction or termination of the practice of a health care provider licensed by a disciplining authority under RCW 18.130.040 while the provider is under investigation or the subject of a proceeding by the ambulatory surgical facility regarding unprofessional conduct, or in return for the ambulatory surgical facility not conducting such an investigation or proceeding or not taking action. The department shall forward the report to the appropriate disciplining authority.

. Reports made under subsection (1) of this section must be made within fifteen days of the date of: (a) A conviction, determination, or finding by the ambulatory surgical facility that the health care provider has committed an action defined as unprofessional conduct under RCW 18.130.180; or (b) acceptance by the ambulatory surgical facility of the voluntary restriction or termination of the practice of a health care provider, including his or her voluntary resignation, while under investigation or the subject of proceedings regarding unprofessional conduct under RCW 18.130.180.

. Failure of an ambulatory surgical facility to comply with this section is punishable by a civil penalty not to exceed two hundred fifty dollars.

. An ambulatory surgical facility, its chief administrator, or its executive officer who files a report under this section is immune from suit, whether direct or derivative, in any civil action related to the filing or contents of the report, unless the conviction, determination, or finding on which the report and its content are based is proven to not have been made in good faith. The prevailing party in any action brought alleging that the conviction, determination, finding, or report was not made in good faith is entitled to recover the costs of litigation, including reasonable attorneys' fees.

. The department shall forward reports made under subsection (1) of this section to the appropriate disciplining authority designated under Title 18 RCW within fifteen days of the date the report is received by the department. The department shall notify an ambulatory surgical facility that has made a report under subsection (1) of this section of the results of the disciplining authority's case disposition decision within fifteen days after the case disposition. Case disposition is the decision whether to issue a statement of charges, take informal action, or close the complaint without action against a provider. In its biennial report to the legislature under RCW 18.130.310, the department shall specifically identify the case dispositions of reports made by ambulatory surgical facilities under subsection (1) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1414-S.SL.pdf?cite=2007%20c%20273%20§%2013[2007 c 273 § 13]; ]

== 70.230.130 - Written records—Decisions to restrict or terminate privileges of practitioners—Penalties.
Each ambulatory surgical facility shall keep written records of decisions to restrict or terminate privileges of practitioners. Copies of such records shall be made available to the Washington medical commission, the board of osteopathic medicine and surgery, or the podiatric medical board, within thirty days of a request, and all information so gained remains confidential in accordance with RCW 70.230.080 and 70.230.120 and is protected from the discovery process. Failure of an ambulatory surgical facility to comply with this section is punishable by a civil penalty not to exceed two hundred fifty dollars.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5764.SL.pdf?cite=2019%20c%2055%20§%2017[2019 c 55 § 17]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1414-S.SL.pdf?cite=2007%20c%20273%20§%2014[2007 c 273 § 14]; ]

== 70.230.140 - Information concerning practitioners—Disclosure.
. Prior to granting or renewing clinical privileges or association of any practitioner or hiring a practitioner, an ambulatory surgical facility approved pursuant to this chapter shall request from the practitioner and the practitioner shall provide the following information:

.. The name of any hospital, ambulatory surgical facility, or other facility with or at which the practitioner had or has any association, employment, privileges, or practice during the prior five years: PROVIDED, That the ambulatory surgical facility may request additional information going back further than five years, and the physician shall use his or her best efforts to comply with such a request for additional information;

.. Whether the physician has ever been or is in the process of being denied, revoked, terminated, suspended, restricted, reduced, limited, sanctioned, placed on probation, monitored, or not renewed for any professional activity listed in (b)(i) through (x) of this subsection, or has ever voluntarily or involuntarily relinquished, withdrawn, or failed to proceed with an application for any professional activity listed in (b)(i) through (x) of this subsection in order to avoid an adverse action or to preclude an investigation or while under investigation relating to professional competence or conduct:

... License to practice any profession in any jurisdiction;

... Other professional registration or certification in any jurisdiction;

... Specialty or subspecialty board certification;

... Membership on any hospital medical staff;

.. Clinical privileges at any facility, including hospitals, ambulatory surgical centers, or skilled nursing facilities;

.. Medicare, medicaid, the food and drug administration, the national institute of health (office of human research protection), governmental, national, or international regulatory agency, or any public program;

.. Professional society membership or fellowship;

.. Participation or membership in a health maintenance organization, preferred provider organization, independent practice association, physician-hospital organization, or other entity;

... Academic appointment;

.. Authority to prescribe controlled substances (drug enforcement agency or other authority);

.. Any pending professional medical misconduct proceedings or any pending medical malpractice actions in this state or another state, the substance of the allegations in the proceedings or actions, and any additional information concerning the proceedings or actions as the practitioner deems appropriate;

.. The substance of the findings in the actions or proceedings and any additional information concerning the actions or proceedings as the practitioner deems appropriate;

.. A waiver by the practitioner of any confidentiality provisions concerning the information required to be provided to ambulatory surgical facilities pursuant to this subsection; and

.. A verification by the practitioner that the information provided by the practitioner is accurate and complete.

. Prior to granting privileges or association to any practitioner or hiring a practitioner, an ambulatory surgical facility approved under this chapter shall request from any hospital or ambulatory surgical facility with or at which the practitioner had or has privileges, was associated, or was employed, during the preceding five years, the following information concerning the practitioner:

.. Any pending professional medical misconduct proceedings or any pending medical malpractice actions, in this state or another state;

.. Any judgment or settlement of a medical malpractice action and any finding of professional misconduct in this state or another state by a licensing or disciplinary board; and

.. Any information required to be reported by hospitals or ambulatory surgical facilities pursuant to RCW 18.130.070.

. The Washington medical commission, board of osteopathic medicine and surgery, podiatric medical board, or dental quality assurance commission, as appropriate, shall be advised within thirty days of the name of any practitioner denied staff privileges, association, or employment on the basis of adverse findings under subsection (1) of this section.

. A hospital, ambulatory surgical facility, or other facility that receives a request for information from another hospital, ambulatory surgical facility, or other facility pursuant to subsections (1) and (2) of this section shall provide such information concerning the physician in question to the extent such information is known to the hospital, ambulatory surgical facility, or other facility receiving such a request, including the reasons for suspension, termination, or curtailment of employment or privileges at the hospital, ambulatory surgical facility, or facility. A hospital, ambulatory surgical facility, other facility, or other person providing such information in good faith is not liable in any civil action for the release of such information.

. Information and documents, including complaints and incident reports, created specifically for, and collected and maintained by, a quality improvement committee are not subject to discovery or introduction into evidence in any civil action, and no person who was in attendance at a meeting of such committee or who participated in the creation, collection, or maintenance of information or documents specifically for the committee shall be permitted or required to testify in any civil action as to the content of such proceedings or the documents and information prepared specifically for the committee. This subsection does not preclude: (a) In any civil action, the discovery of the identity of persons involved in the medical care that is the basis of the civil action whose involvement was independent of any quality improvement activity; (b) in any civil action, the testimony of any person concerning the facts which form the basis for the institution of such proceedings of which the person had personal knowledge acquired independently of such proceedings; (c) in any civil action by a health care provider regarding the restriction or revocation of that individual's clinical or staff privileges, introduction into evidence information collected and maintained by quality improvement committees regarding such health care provider; (d) in any civil action, disclosure of the fact that staff privileges were terminated or restricted, including the specific restrictions imposed, if any, and the reasons for the restrictions; or (e) in any civil action, discovery and introduction into evidence of the patient's medical records required by rule of the department to be made regarding the care and treatment received.

. Ambulatory surgical facilities shall be granted access to information held by the Washington medical commission, board of osteopathic medicine and surgery, or podiatric medical board pertinent to decisions of the ambulatory surgical facility regarding credentialing and recredentialing of practitioners.

. Violation of this section shall not be considered negligence per se.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5764.SL.pdf?cite=2019%20c%2055%20§%2018[2019 c 55 § 18]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5666.SL.pdf?cite=2013%20c%20301%20§%205[2013 c 301 § 5]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1414-S.SL.pdf?cite=2007%20c%20273%20§%2015[2007 c 273 § 15]; ]

== 70.230.150 - Unanticipated outcomes—Notification.
Ambulatory surgical facilities shall have in place policies to assure that, when appropriate, information about unanticipated outcomes is provided to patients or their families or any surrogate decision makers identified pursuant to RCW 7.70.065. Notifications of unanticipated outcomes under this section do not constitute an acknowledgment or admission of liability, nor may the fact of notification, the content disclosed, or any and all statements, affirmations, gestures, or conduct expressing apology be introduced as evidence in a civil action.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1414-S.SL.pdf?cite=2007%20c%20273%20§%2016[2007 c 273 § 16]; ]

== 70.230.160 - Complaint toll-free telephone number—Notice.
Every ambulatory surgical facility shall post in conspicuous locations a notice of the department's ambulatory surgical facility complaint toll-free telephone number. The form of the notice shall be approved by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1414-S.SL.pdf?cite=2007%20c%20273%20§%2017[2007 c 273 § 17]; ]

== 70.230.170 - Information received by department—Disclosure.
Information received by the department through filed reports, inspection, or as otherwise authorized under this chapter may be disclosed publicly, as permitted under chapter 42.56 RCW, subject to the following provisions:

. Licensing inspections, or complaint investigations regardless of findings, shall, as requested, be disclosed no sooner than three business days after the ambulatory surgical facility has received the resulting assessment report;

. Information regarding administrative action against the license [licensee] shall, as requested, be disclosed after the ambulatory surgical facility has received the documents initiating the administrative action;

. Information about complaints that did not warrant an investigation shall not be disclosed except to notify the ambulatory surgical facility and the complainant that the complaint did not warrant an investigation; and

. Information disclosed under this section shall not disclose individual names.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1414-S.SL.pdf?cite=2007%20c%20273%20§%2018[2007 c 273 § 18]; ]

== 70.230.190 - Certain ambulatory surgical facilities deemed to have complied with survey requirements of RCW  70.230.100.
Any entity that meets the definition of an ambulatory surgical facility in RCW 70.230.010 that had been issued a license on or after July 1, 2009, that was later declared void by a department determination that the entity did not meet the definition of an ambulatory surgical facility shall be deemed to have complied with the survey requirements of RCW 70.230.100 for its initial license application.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1575-S.SL.pdf?cite=2011%20c%2076%20§%203[2011 c 76 § 3]; ]

== 70.230.210 - Pattern of balance billing protection act violations by ambulatory surgical facility—Fines and disciplinary action.
If the insurance commissioner reports to the department that he or she has cause to believe that an ambulatory surgical facility has engaged in a pattern of violations of RCW 48.49.020 or 48.49.030, and the report is substantiated after investigation, the department may levy a fine upon the ambulatory surgical facility in an amount not to exceed one thousand dollars per violation and take other formal or informal disciplinary action as permitted under the authority of the department.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1065-S2.SL.pdf?cite=2019%20c%20427%20§%2019[2019 c 427 § 19]; ]

== 70.230.900 - Effective date—2007 c 273.
Except for section 7 of this act, this act takes effect July 1, 2009.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1414-S.SL.pdf?cite=2007%20c%20273%20§%2029[2007 c 273 § 29]; ]

== 70.230.901 - Implementation—2007 c 273.
The secretary of health may take the necessary steps to ensure that this act is implemented on its effective date.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1414-S.SL.pdf?cite=2007%20c%20273%20§%2030[2007 c 273 § 30]; ]

