= 70.385 - Peer support services.
:toc:

== 70.385.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Authority" means the Washington state health care authority.

. "Peer support services" means services authorized under RCW 71.24.385 which are delivered by individuals who have common life experiences with the people they are serving.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1907-S2.SL.pdf?cite=2019%20c%20446%20§%2048[2019 c 446 § 48]; ]

== 70.385.020 - Peer counselor certification program—Education and training for substance use disorder peers—Reimbursement for services.
. The authority shall administer a peer counselor certification program to support the delivery of peer support services in Washington state.

. By July 1, 2019, the authority shall incorporate education and training for substance use disorder peers in its peer counselor certification program.

. By July 1, 2019, the authority must include reimbursement for peer support services by substance use disorder peers in its behavioral health capitation rates and allow for federal matching funds, consistent with the directive enacted in section 213(5)(ss), chapter 299, Laws of 2018 (ESSB 6032).

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1907-S2.SL.pdf?cite=2019%20c%20446%20§%2049[2019 c 446 § 49]; ]

== 70.385.030 - Specialized peer training for peer counselor certification.
To ensure an adequate workforce of peer counselors, the authority must approve entities to perform specialized peer training for peer counselor certification using the state curriculum upon request if the entity meets qualifications to perform the training as determined by the authority.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1907-S2.SL.pdf?cite=2019%20c%20446%20§%2050[2019 c 446 § 50]; ]

== 70.385.900 - Effective date—2019 c 446 §§ 48-53.
Sections 48 through 53 of this act are necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and take effect July 1, 2019.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1907-S2.SL.pdf?cite=2019%20c%20446%20§%2054[2019 c 446 § 54]; ]

