= 70.385 - Peer support services.
:toc:

== 70.385.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Authority" means the Washington state health care authority.

. "Peer support services" means services authorized under RCW 71.24.385 which are delivered by individuals who have common life experiences with the people they are serving.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1907-S2.SL.pdf?cite=2019%20c%20446%20§%2048[2019 c 446 § 48]; ]

== 70.385.020 - Peer counselor certification program—Education and training for substance use disorder peers—Reimbursement for services.
. The authority shall administer a peer counselor certification program to support the delivery of peer support services in Washington state.

. By July 1, 2019, the authority shall incorporate education and training for substance use disorder peers in its peer counselor certification program.

. By July 1, 2019, the authority must include reimbursement for peer support services by substance use disorder peers in its behavioral health capitation rates and allow for federal matching funds, consistent with the directive enacted in section 213(5)(ss), chapter 299, Laws of 2018 (ESSB 6032).

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1907-S2.SL.pdf?cite=2019%20c%20446%20§%2049[2019 c 446 § 49]; ]

== 70.385.030 - Specialized peer training for peer counselor certification.
To ensure an adequate workforce of peer counselors, the authority must approve entities to perform specialized peer training for peer counselor certification using the state curriculum upon request if the entity meets qualifications to perform the training as determined by the authority.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1907-S2.SL.pdf?cite=2019%20c%20446%20§%2050[2019 c 446 § 50]; ]

== 70.385.800 - Sunrise review—Transfer of peer support counselor certification program to department of health—Creation of advanced peer support specialist credential. (Expires June 30, 2021.)
. The department of health shall conduct a sunrise review under chapter 18.120 RCW to evaluate transfer of the peer support counselor certification program under this chapter to the department of health with modifications to allow the program to become a license or certification under the oversight of the department of health subject to oversight, structure, discipline, and continuing education requirements typical of other programs related to behavioral health administered by the department of health. The plan for modification of the program must allow for grandfathering of current individuals who hold the peer support counselor certification. The sunrise review must evaluate the effect of these modifications on professionalism, portability, scope of practice, approved practice locations, workforce, bidirectional integration, and appropriate deployment of peer support services throughout the health system.

. The department of health shall conduct a sunrise review under chapter 18.120 RCW to evaluate the need for creation of an advanced peer support specialist credential to provide a license to perform peer support services in the areas of mental health, substance use disorders, and forensic behavioral health. The requirements for this credential must be accessible to persons in recovery and:

.. Integrate with and complement the attributes of the peer counselor certification program administered by the Washington state health care authority under RCW 70.385.010;

.. Provide education, experience, and training requirements that are more stringent than the requirements for the peer counselor certification program but less extensive than the requirements for licensure or certification under other credentials related to behavioral health which are administered by the department of health;

.. Provide oversight, structure, discipline, and continuing education requirements typical for other professional licenses and certifications;

.. Allow advanced peer support specialists to maximize the scope of practice suitable to their skills, lived experience, education, and training;

.. Allow advanced peer support specialists to practice and receive reimbursement in behavioral health capitation rates in the full range of settings in which clients receive behavioral health services which are appropriate for their participation;

.. Provide a path for career progression to more advanced credentials for those who are interested in pursuing them; and

.. Incorporate consideration of common barriers to certification and licensure related to criminal history and recovery from behavioral health disorders experienced by peers and accommodate applicants who have these lived experiences to the greatest extent consistent with prudence and client safety.

. This section expires June 30, 2021.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1907-S2.SL.pdf?cite=2019%20c%20446%20§%2052[2019 c 446 § 52]; ]

== 70.385.801 - Sunrise review—Cooperation between the authority and the department of health. (Expires June 30, 2021.)
. The authority shall cooperate with the department of health to complete the sunrise review required under RCW 70.385.800.

. This section expires June 30, 2021.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1907-S2.SL.pdf?cite=2019%20c%20446%20§%2051[2019 c 446 § 51]; ]

== 70.385.900 - Effective date—2019 c 446 §§ 48-53.
Sections 48 through 53 of this act are necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and take effect July 1, 2019.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1907-S2.SL.pdf?cite=2019%20c%20446%20§%2054[2019 c 446 § 54]; ]

