= 70.345 - Vapor products.
:toc:

== 70.345.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Board" means the Washington state liquor and cannabis board.

. "Business" means any trade, occupation, activity, or enterprise engaged in for the purpose of selling or distributing vapor products in this state.

. "Child care facility" has the same meaning as provided in *RCW 70.140.020.

. "Closed system nicotine container" means a sealed, prefilled, and disposable container of nicotine in a solution or other form in which such container is inserted directly into an electronic cigarette, electronic nicotine delivery system, or other similar product, if the nicotine in the container is inaccessible through customary or reasonably foreseeable handling or use, including reasonably foreseeable ingestion or other contact by children.

. "Delivery sale" means any sale of a vapor product to a purchaser in this state where either:

.. The purchaser submits the order for such sale by means of a telephonic or other method of voice transmission, the mails or any other delivery service, or the internet or other online service; or

.. The vapor product is delivered by use of the mails or of a delivery service. The foregoing sales of vapor products constitute a delivery sale regardless of whether the seller is located within or without this state. "Delivery sale" does not include a sale of any vapor product not for personal consumption to a retailer.

. "Delivery seller" means a person who makes delivery sales.

. "Distributor" has the same meaning as in RCW 82.25.005.

. "Liquid nicotine container" means a package from which nicotine in a solution or other form is accessible through normal and foreseeable use by a consumer and that is used to hold soluble nicotine in any concentration. "Liquid nicotine container" does not include closed system nicotine containers.

. "Manufacturer" means a person who manufactures and sells vapor products.

. "Person" means any individual, receiver, administrator, executor, assignee, trustee in bankruptcy, trust, estate, firm, copartnership, joint venture, club, company, joint stock company, business trust, municipal corporation, the state and its departments and institutions, political subdivision of the state of Washington, corporation, limited liability company, association, society, any group of individuals acting as a unit, whether mutual, cooperative, fraternal, nonprofit, or otherwise.

. "Place of business" means any place where vapor products are sold or where vapor products are manufactured, stored, or kept for the purpose of sale.

. "Playground" means any public improved area designed, equipped, and set aside for play of six or more children which is not intended for use as an athletic playing field or athletic court, including but not limited to any play equipment, surfacing, fencing, signs, internal pathways, internal land forms, vegetation, and related structures.

. "Retail outlet" means each place of business from which vapor products are sold to consumers.

. "Retailer" means any person engaged in the business of selling vapor products to ultimate consumers.

. [Empty]
.. "Sale" means any transfer, exchange, or barter, in any manner or by any means whatsoever, for a consideration, and includes and means all sales made by any person.

.. The term "sale" includes a gift by a person engaged in the business of selling vapor products, for advertising, promoting, or as a means of evading the provisions of this chapter.

. "School" has the same meaning as provided in *RCW 70.140.020.

. "Self-service display" means a display that contains vapor products and is located in an area that is openly accessible to customers and from which customers can readily access such products without the assistance of a salesperson. A display case that holds vapor products behind locked doors does not constitute a self-service display.

. "Vapor product" means any noncombustible product that may contain nicotine and that employs a heating element, power source, electronic circuit, or other electronic, chemical, or mechanical means, regardless of shape or size, that can be used to produce vapor or aerosol from a solution or other substance.

.. "Vapor product" includes any electronic cigarette, electronic cigar, electronic cigarillo, electronic pipe, or similar product or device and any vapor cartridge or other container that may contain nicotine in a solution or other form that is intended to be used with or in an electronic cigarette, electronic cigar, electronic cigarillo, electronic pipe, or similar product or device.

.. "Vapor product" does not include any product that meets the definition of marijuana, useable marijuana, marijuana concentrates, marijuana-infused products, cigarette, or tobacco products.

.. For purposes of this subsection (18), "marijuana," "useable marijuana," "marijuana concentrates," and "marijuana-infused products" have the same meaning as provided in RCW 69.50.101.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20210[2019 c 445 § 210]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1074.SL.pdf?cite=2019%20c%2015%20§%204[2019 c 15 § 4]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=2016%20sp.s.%20c%2038%20§%204[2016 sp.s. c 38 § 4]; ]

== 70.345.020 - Types of licenses—Applications—License expiration and display.
. The licenses issuable by the board under this chapter are as follows:

.. A vapor product retailer's license;

.. A vapor product distributor's license; and

.. A vapor product delivery sale license.

. Application for the licenses must be made through the business licensing system under chapter 19.02 RCW. The board may adopt rules regarding the regulation of the licenses. The board may refuse to issue any license under this chapter if the board has reasonable cause to believe that the applicant has willfully withheld information requested for the purpose of determining the eligibility of the applicant to receive a license, or if the board has reasonable cause to believe that information submitted in the application is false or misleading or is not made in good faith. In addition, for the purpose of reviewing an application for a distributor's license, retailer's license, or delivery seller's license, and for considering the denial, suspension, or revocation of any such license, the board may consider criminal conduct of the applicant, including an administrative violation history record with the board and a criminal history record information check within the previous five years, in any state, tribal, or federal jurisdiction in the United States, its territories, or possessions, and the provisions of RCW 9.95.240 and chapter 9.96A RCW do not apply to such cases. The board may, in its discretion, issue or refuse to issue the retailer's license, distributor's license, and delivery sale license subject to the provisions of RCW 70.155.100.

. The application processes for the retailer license and the distributor license, and any forms used for such processes, must allow the applicant to simultaneously apply for a delivery sale license without requiring the applicant to undergo a separate licensing application process in order to be licensed to conduct delivery sales. However, a delivery sale license obtained in conjunction with a retailer or distributor license under this subsection remains a separate license subject to the delivery sale licensing fee established under this chapter.

. No person may qualify for a retailer's license, distributor's license, or delivery sale license under this section without first undergoing a criminal background check. The background check must be performed by the board and must disclose any criminal conduct within the previous five years in any state, tribal, or federal jurisdiction in the United States, its territories, or possessions. If the applicant or licensee also has a license issued under chapter 66.24, 69.50, 82.24, or 82.26 RCW, the background check done under the authority of chapter 66.24, 69.50, 82.24, or 82.26 RCW satisfies the requirements of this subsection.

. Each license issued under this chapter expires on the business license expiration date. The license must be continued annually if the licensee has paid the required fee and complied with all the provisions of this chapter and the rules of the board adopted pursuant to this chapter.

. Each license and any other evidence of the license required under this chapter must be exhibited in each place of business for which it is issued and in the manner required for the display of a business license.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=2016%20sp.s.%20c%2038%20§%205[2016 sp.s. c 38 § 5]; ]

== 70.345.030 - License required—Must allow inspections—Sale of certain substances prohibited—Penalties.
. [Empty]
.. No person may engage in or conduct business as a retailer, distributor, or delivery seller in this state without a valid license issued under this chapter, except as otherwise provided by law. Any person who sells vapor products to ultimate consumers by a means other than delivery sales must obtain a retailer's license under this chapter. Any person who meets the definition of distributor under this chapter must obtain a distributor's license under this chapter. Any person who conducts delivery sales of vapor products must obtain a delivery sale license.

.. A violation of this subsection is punishable as a class C felony according to chapter 9A.20 RCW.

. No person engaged in or conducting business as a retailer, distributor, or delivery seller in this state may refuse to allow the enforcement officers of the board, on demand, to make full inspection of any place of business or vehicle where any of the vapor products regulated under this chapter are sold, stored, transported, or handled, or otherwise hinder or prevent such inspection. A person who violates this subsection is guilty of a gross misdemeanor.

. Any person licensed under this chapter as a distributor, any person licensed under this chapter as a retailer, and any person licensed under this chapter as a delivery seller may not operate in any other capacity unless the additional appropriate license is first secured, except as otherwise provided by law. A violation of this subsection is a misdemeanor.

. No person engaged in or conducting business as a retailer, distributor, or delivery seller in this state may sell or give, or permit to sell or give, a product that contains any amount of any cannabinoid, synthetic cannabinoid, cathinone, or methcathinone, unless otherwise provided by law. A violation of this subsection (4) is punishable according to RCW 69.50.401.

. The penalties provided in this section are in addition to any other penalties provided by law for violating the provisions of this chapter or the rules adopted under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20211[2019 c 445 § 211]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=2016%20sp.s.%20c%2038%20§%206[2016 sp.s. c 38 § 6]; ]

== 70.345.040 - Licensing fee—Distributors.
A fee of one hundred fifty dollars must accompany each vapor product distributor's license application or license renewal application under RCW 70.345.020. If a distributor sells or intends to sell vapor products at two or more places of business, whether established or temporary, a separate license with a license fee of one hundred dollars is required for each additional place of business.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=2016%20sp.s.%20c%2038%20§%207[2016 sp.s. c 38 § 7]; ]

== 70.345.050 - Licensing fee—Retailers.
. A fee of one hundred seventy-five dollars must accompany each vapor product retailer's license application or license renewal application under RCW 70.345.020. A separate license is required for each separate location at which the retailer operates.

. A retailer applying for, or renewing, both a vapor products retailer's license under RCW 70.345.020 and retailer's license under RCW 82.24.510 may pay a combined application fee of two hundred fifty dollars for both licenses.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=2016%20sp.s.%20c%2038%20§%208[2016 sp.s. c 38 § 8]; ]

== 70.345.060 - Licensing fee—Delivery sales.
A fee of two hundred fifty dollars must accompany each vapor product delivery sale license application or license renewal application under RCW 70.345.020.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=2016%20sp.s.%20c%2038%20§%2010[2016 sp.s. c 38 § 10]; ]

== 70.345.070 - Retail signage.
. Except as provided in subsection (2) of this section, a person who holds a retailer's license issued under this chapter must display a sign concerning the prohibition of vapor product sales to persons under the age of twenty-one. Such sign must:

.. Be posted so that it is clearly visible to anyone purchasing vapor products from the licensee;

.. Be designed and produced by the department of health to read: "The sale of vapor products to persons under age twenty-one is strictly prohibited by state law. Photo id required upon request;" and

.. Be provided free of charge by the department of health.

. For persons also licensed under RCW 82.24.510 or 82.26.150, the board may issue a sign to read: "The sale of tobacco or vapor products to persons under age twenty-one is strictly prohibited by state law. Photo id required upon request." The sign must be provided free of charge by the board.

. A person who holds a license issued under this chapter must display the license or a copy in a prominent location at the outlet for which the license is issued.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1074.SL.pdf?cite=2019%20c%2015%20§%206[2019 c 15 § 6]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=2016%20sp.s.%20c%2038%20§%2012[2016 sp.s. c 38 § 12]; ]

== 70.345.075 - Product labeling. (Contingent expiration date.)
. A manufacturer or distributor that sells, offers for sale, or distributes liquid nicotine containers shall label the vapor product with a: (a) Warning regarding the harmful effects of nicotine; (b) warning to keep the vapor product away from children; (c) warning that vaping is illegal for those under the legal age to use the product; and (d) except as provided in subsection (2) of this section, the amount of nicotine in milligrams per milliliter of liquid along with the total volume of the liquid contents of the product expressed in milliliters.

. For closed system nicotine containers as defined in RCW 70.345.010, a manufacturer that sells, offers for sale, or distributes vapor products in this state must annually provide the department of health with a disclosure of the nicotine content of such vapor product based on measurement standards to be established by the department of health.

. [Empty]
.. This section expires on the effective date of the final regulations issued by the United States food and drug administration or by any other federal agency, when such regulations mandate warning or advertisement requirements for vapor products.

.. The board must provide notice of the expiration date of this section to affected parties, the chief clerk of the house of representatives, the secretary of the senate, the office of the code reviser, and others as deemed appropriate by the board.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=2016%20sp.s.%20c%2038%20§%2013[2016 sp.s. c 38 § 13]; ]

== 70.345.080 - Vendor assistance required for sales—Exception.
. No person may offer a vapor product for sale in an open, unsecured display that is accessible to the public without the intervention of a store employee.

. It is unlawful to sell or distribute vapor products from self-service displays.

. Retail establishments are exempt from subsections (1) and (2) of this section if persons under the age of twenty-one are not allowed in the store and such prohibition is posted clearly on all entrances.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1074.SL.pdf?cite=2019%20c%2015%20§%209[2019 c 15 § 9]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2038.SL.pdf?cite=2017%20c%20210%20§%201[2017 c 210 § 1]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=2016%20sp.s.%20c%2038%20§%2016[2016 sp.s. c 38 § 16]; ]

== 70.345.090 - Mail and internet sales—License required—Age and identity verification—Penalties—Enforcement—Application of consumer protection act—Rules.
. No person may conduct a delivery sale or otherwise ship or transport, or cause to be shipped or transported, any vapor product ordered or purchased by mail or through the internet to any person unless such seller has a valid delivery sale license as required under this chapter.

. No person may conduct a delivery sale or otherwise ship or transport, or cause to be shipped or transported, any vapor product ordered or purchased by mail or through the internet to any person under the minimum age required for the legal sale of vapor products as provided under RCW 70.345.140.

. A delivery sale licensee must provide notice on its mail order or internet sales forms of the minimum age required for the legal sale of vapor products in Washington state as provided by RCW 70.345.140.

. A delivery sale licensee must not accept a purchase or order from any person without first obtaining the full name, birthdate, and residential address of that person and verifying this information through an independently operated third-party database or aggregate of databases, which includes data from government sources, that are regularly used by government and businesses for the purpose of age and identity verification and authentication.

. A delivery sale licensee must accept payment only through a credit or debit card issued in the purchaser's own name. The licensee must verify that the card is issued to the same person identified through identity and age verification procedures in subsection (4) of this section.

. Before a delivery sale licensee delivers an initial purchase to any person, the licensee must verify the identity and delivery address of the purchaser by mailing or shipping to the purchaser a notice of sale and certification form confirming that the addressee is in fact the person placing the order. The purchaser must return the signed certification form to the licensee before the initial shipment of product. Certification forms are not required for repeat customers. In the alternative, before a seller delivers an initial purchase to any person, the seller must first obtain from the prospective customer an electronic certification, such as by email, that includes a declaration that, at a minimum, the prospective customer is over the minimum age required for the legal sale of a vapor product, and the credit or debit card used for payment has been issued in the purchaser's name.

. A delivery sale licensee must include on shipping documents a clear and conspicuous statement which includes, at a minimum, that the package contains vapor products, Washington law prohibits sales to those under the minimum age established by this chapter, and violations may result in sanctions to both the licensee and the purchaser.

. For purposes of this subsection (8) [this section], "vapor products" has the same meaning as provided in RCW 82.25.005.

. A person who knowingly violates this section is guilty of a class C felony, except that the maximum fine that may be imposed is five thousand dollars.

. In addition to or in lieu of any other civil or criminal remedy provided by law, a person who has violated this section is subject to a civil penalty of up to five thousand dollars for each violation. The attorney general, acting in the name of the state, may seek recovery of the penalty in a civil action in superior court.

. The attorney general may seek an injunction in superior court to restrain a threatened or actual violation of this section and to compel compliance with this section.

. Any violation of this section is not reasonable in relation to the development and preservation of business and is an unfair and deceptive act or practice and an unfair method of competition in the conduct of trade or commerce in violation of RCW 19.86.020. Standing to bring an action to enforce RCW 19.86.020 for violation of this section lies solely with the attorney general. Remedies provided by chapter 19.86 RCW are cumulative and not exclusive.

. [Empty]
.. In any action brought under this section, the state is entitled to recover, in addition to other relief, the costs of investigation, expert witness fees, costs of the action, and reasonable attorneys' fees.

.. If a court determines that a person has violated this section, the court shall order any profits, gain, gross receipts, or other benefit from the violation to be disgorged and paid to the state treasurer for deposit in the general fund.

. Unless otherwise expressly provided, the penalties or remedies, or both, under this section are in addition to any other penalties and remedies available under any other law of this state.

. A licensee who violates this section is subject to license suspension or revocation by the board.

. The board may adopt by rule additional requirements for mail or internet sales.

. The board must not adopt rules prohibiting internet sales.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20212[2019 c 445 § 212]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=2016%20sp.s.%20c%2038%20§%2017[2016 sp.s. c 38 § 17]; ]

== 70.345.100 - Product tastings—Requirements—Penalty.
. No person may offer a tasting of vapor products to the general public unless:

.. The person is a licensed retailer under RCW 70.345.020;

.. The tastings are offered only within the licensed premises operated by the licensee and the products tasted are not removed from within the licensed premises by the customer;

.. Entry into the licensed premises is restricted to persons twenty-one years of age or older;

.. The vapor product being offered for tasting contains zero milligrams per milliliter of nicotine or the customer explicitly consents to a tasting of a vapor product that contains nicotine; and

.. If the customer is tasting from a vapor device owned and maintained by the retailer, a disposable mouthpiece tip is attached to the vapor product being used by the customer for tasting or the vapor device is disposed of after each tasting.

. A violation of this section is a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1074.SL.pdf?cite=2019%20c%2015%20§%207[2019 c 15 § 7]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=2016%20sp.s.%20c%2038%20§%2019[2016 sp.s. c 38 § 19]; ]

== 70.345.110 - Coupons for free of charge products.
. No person may give or distribute vapor products to a person free of charge by coupon, unless the vapor product was provided to the person as a contingency of prior or the same purchase as part of an in-person transaction or delivery sale.

. This section does not prohibit the use of coupons to receive a discount on a vapor product as part of an in-person transaction or delivery sale.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=2016%20sp.s.%20c%2038%20§%2020[2016 sp.s. c 38 § 20]; ]

== 70.345.120 - Verification of age—Permitted forms of identification—Defense.
. When there may be a question of a person's right to purchase or obtain vapor products by reason of age, the retailer or agent thereof, must require the purchaser to present any one of the following officially issued forms of identification that shows the purchaser's age and bears his or her signature and photograph: (a) Liquor control authority card of identification of a state or province of Canada; (b) driver's license, instruction permit, or identification card of a state or province of Canada; (c) "identicard" issued by the Washington state department of licensing under chapter 46.20 RCW; (d) United States military identification; (e) passport; (f) enrollment card, issued by the governing authority of a federally recognized Indian tribe located in Washington, that incorporates security features comparable to those implemented by the department of licensing for Washington drivers' licenses. At least ninety days prior to implementation of an enrollment card under this subsection, the appropriate tribal authority must give notice to the board. The board must publish and communicate to licensees regarding the implementation of each new enrollment card; or (g) merchant marine identification card issued by the United States coast guard.

. It is a defense to a prosecution under RCW 26.28.080 that the person making a sale reasonably relied on any of the officially issued identification as defined in subsection (1) of this section. The board must waive the suspension or revocation of a license if the licensee clearly establishes that he or she acted in good faith to prevent violations and a violation occurred despite the licensee's exercise of due diligence.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=2016%20sp.s.%20c%2038%20§%2015[2016 sp.s. c 38 § 15]; ]

== 70.345.130 - Child-resistant packaging required—Penalty.
. Any liquid nicotine container that is sold at retail shall be packaged in accordance with the child-resistant effectiveness standards set forth in 16 C.F.R. Sec. 1700.15, as in effect on June 28, 2016, as determined through testing in accordance with the method described in 16 C.F.R. Sec. 1700.20, as in effect on June 28, 2016.

 (2) Any person that engages in retail sales of liquid nicotine containers in violation of this section is guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=2016%20sp.s.%20c%2038%20§%2018[2016 sp.s. c 38 § 18]; ]

== 70.345.140 - Purchase or possession by persons under eighteen—Penalty—Jurisdiction.
. A person under the age of eighteen who purchases or attempts to purchase, possesses, or obtains or attempts to obtain vapor products commits a class 3 civil infraction under chapter 7.80 RCW and is subject to a fine as set out in chapter 7.80 RCW or participation in up to four hours of community restitution, or both. The court may also require participation in a smoking cessation program. This provision does not apply if a person under the age of eighteen, with parental authorization, is participating in a controlled purchase as part of a board, law enforcement, or local health department activity.

. Municipal and district courts within the state have jurisdiction for enforcement of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=2016%20sp.s.%20c%2038%20§%2014[2016 sp.s. c 38 § 14]; ]

== 70.345.150 - Use of products in public places—When prohibited.
. Indoor areas.

.. The use of vapor products is prohibited in the following indoor areas:

... Inside a child care facility, provided that a child care facility that is home-based is excluded from this paragraph when children enrolled in such child care facility are not present;

... Schools;

... Within five hundred feet of schools;

... Schools buses; and

.. Elevators.

.. The use of vapor products is permitted for tasting and sampling in indoor areas of retail outlets.

. Outdoor areas. The use of vapor products is prohibited in the following outdoor areas:

.. Real property that is under the control of a child care facility and upon which the child care facility is located, provided that a child care facility that is home-based is excluded from this paragraph when children enrolled in such child care facility are not present;

.. Real property that is under the control of a school and upon which the school is located; and

.. Playgrounds, during the hours between sunrise and sunset, when one or more persons under twelve years of age are present at such playground.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=2016%20sp.s.%20c%2038%20§%2021[2016 sp.s. c 38 § 21]; ]

== 70.345.160 - Enforcement—Authority of liquor and cannabis board—Detention to determine identity and age—Inspections—Products injurious to health.
. The board must have, in addition to the board's other powers and authorities, the authority to enforce the provisions of this chapter.

. The board and the board's authorized agents or employees have full power and authority to enter any place of business where vapor products are sold for the purpose of enforcing the provisions of this chapter.

. For the purpose of enforcing the provisions of this chapter, a peace officer or enforcement officer of the board who has reasonable grounds to believe a person observed by the officer purchasing, attempting to purchase, or in possession of vapor products is under eighteen years of age, may detain such person for a reasonable period of time and in such a reasonable manner as is necessary to determine the person's true identity and date of birth. Further, vapor products possessed by persons under eighteen years of age are considered contraband and may be seized by a peace officer or enforcement officer of the board.

. The board may work with local county health departments or districts and local law enforcement agencies to conduct random, unannounced, inspections to assure compliance.

. Upon a determination by the secretary of health or a local health jurisdiction that a vapor product may be injurious to human health or poses a significant risk to public health:

.. The board, in consultation with the department of health and local county health jurisdictions, may cause a vapor product substance or solution sample, purchased or obtained from any vapor product retailer, distributor, or delivery sale licensee, to be analyzed by an analyst appointed or designated by the board;

.. If the analyzed vapor product contains an ingredient, substance, or solution present in quantities injurious to human health or posing a significant risk to public health, as determined by the secretary of health or a local health jurisdiction, the board may suspend the license of the retailer or delivery sale licensee unless the retailer or delivery sale licensee agrees to remove the product from sales; and

.. If upon a finding from the secretary of health or local health jurisdiction that the vapor product poses an injurious risk to public health or significant public health risk, the retailer or delivery sale licensee does not remove the product from sale, the secretary of health or local health officer may file for an injunction in superior court prohibiting the sale or distribution of that specific vapor product substance or solution.

. Nothing in subsection (5) of this section permits a total ban on the sale or use of vapor products.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=2016%20sp.s.%20c%2038%20§%2024[2016 sp.s. c 38 § 24]; ]

== 70.345.170 - Enforcement—License suspension and revocation—Appeal.
. The board, or its enforcement officers, has the authority to enforce provisions of this chapter.

. The board may revoke or suspend a retailer's, distributor's, or delivery seller's license issued under this chapter upon sufficient cause showing a violation of this chapter.

. A license may not be suspended or revoked except upon notice to the licensee and after a hearing as prescribed by the board.

. Any retailer's licenses issued under chapter 82.24 or 82.26 RCW to a person whose vapor product retailer's license or licenses have been suspended or revoked for violating RCW 26.28.080 must also be suspended or revoked during the period of suspension or revocation under this section.

. Any person whose license or licenses have been revoked under this section may reapply to the board at the expiration of two years of the license or licenses, unless the license was revoked pursuant to RCW 70.345.180(2)(e). The license or licenses may be approved by the board if it appears to the satisfaction of the board that the licensee will comply with the provisions of this chapter.

. A person whose license has been suspended or revoked may not sell vapor products or permit vapor products to be sold during the period of suspension or revocation on the premises occupied by the person or upon other premises controlled by the person or others or in any other manner or form.

. Any determination and order by the board, and any order of suspension or revocation by the board of the license or licenses issued under this chapter, or refusal to reinstate a license or licenses after revocation is reviewable by an appeal to the superior court of Thurston county. The superior court must review the order or ruling of the board and may hear the matter de novo, having due regard to the provisions of this chapter and the duties imposed upon the board.

. If the board makes an initial decision to deny a license or renewal, or suspend or revoke a license, the applicant may request a hearing subject to the applicable provisions under Title 34 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=2016%20sp.s.%20c%2038%20§%2011[2016 sp.s. c 38 § 11]; ]

== 70.345.180 - Enforcement—Penalties, sanctions, and actions against licensees.
. The board may impose a monetary penalty as set forth in subsection (2) of this section, if the board finds that the licensee has violated RCW 26.28.080 or any other provision of this chapter.

. Subject to subsection (3) of this section, the sanctions that the board may impose against a person licensed under this chapter based upon one or more findings under subsection (1) of this section may not exceed the following:

.. A monetary penalty of two hundred dollars for the first violation within any three-year period;

.. A monetary penalty of six hundred dollars for the second violation within any three-year period;

.. A monetary penalty of two thousand dollars for the third violation within any three-year period and suspension of the license for a period of six months for the third violation of RCW 26.28.080 within any three-year period;

.. A monetary penalty of three thousand dollars for the fourth or subsequent violation within any three-year period and suspension of the license for a period of twelve months for the fourth violation of RCW 26.28.080 within any three-year period;

.. Revocation of the license with no possibility of reinstatement for a period of five years for the fifth or more violation within any three-year period.

. If the board finds that a person licensed under this chapter and chapter 82.24 or 82.26 RCW has violated RCW 26.28.080, each subsequent violation of either of the person's licenses counts as an additional violation within that three-year period.

. Any retailer's licenses issued under chapter 82.24 or 82.26 RCW to a person whose vapor product retailer's license or licenses have been suspended or revoked for violating RCW 26.28.080 must also be suspended or revoked during the period of suspension or revocation under this section.

. The board may impose a monetary penalty upon any person other than a licensed retailer if the board finds that the person has violated RCW 26.28.080.

. The monetary penalty that the board may impose based upon one or more findings under subsection (5) of this section may not exceed fifty dollars for the first violation and one hundred dollars for each subsequent violation.

. The board may develop and offer a class for retail clerks and use this class in lieu of a monetary penalty for the clerk's first violation.

. The board may issue a cease and desist order to any person who is found by the board to have violated or intending [intends] to violate the provisions of this chapter or RCW 26.28.080, requiring such person to cease specified conduct that is in violation. The issuance of a cease and desist order does not preclude the imposition of other sanctions authorized by this statute or any other provision of law.

. The board may seek injunctive relief to enforce the provisions of RCW 26.28.080 or this chapter. The board may initiate legal action to collect civil penalties imposed under this chapter if the same have not been paid within thirty days after imposition of such penalties. In any action filed by the board under this chapter, the court may, in addition to any other relief, award the board reasonable attorneys' fees and costs.

. All proceedings under subsections (1) through (8) of this section must be conducted in accordance with chapter 34.05 RCW.

. The board may reduce or waive either the penalties or the suspension or revocation of a license, or both, as set forth in this chapter where the elements of proof are inadequate or where there are mitigating circumstances. Mitigating circumstances may include, but are not limited to, an exercise of due diligence by a retailer. Further, the board may exceed penalties set forth in this chapter based on aggravating circumstances.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=2016%20sp.s.%20c%2038%20§%2022[2016 sp.s. c 38 § 22]; ]

== 70.345.190 - Disposition of license fees and monetary penalties.
All license fees collected and funds collected by the board from the imposition of monetary penalties pursuant to this chapter must be deposited into the youth tobacco and vapor products prevention account created in RCW 70.155.120.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=2016%20sp.s.%20c%2038%20§%2025[2016 sp.s. c 38 § 25]; ]

== 70.345.200 - Exemptions.
This chapter does not apply to a motor carrier or a freight forwarder as defined in 49 U.S.C. Sec. 13102 or an air carrier as defined in 49 U.S.C. Sec. 40102.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=2016%20sp.s.%20c%2038%20§%2026[2016 sp.s. c 38 § 26]; ]

== 70.345.210 - State preemption—Exceptions.
. This chapter preempts political subdivisions from adopting or enforcing requirements for the licensure and regulation of vapor product promotions and sales at retail. No political subdivision may impose fees or license requirements on retail outlets for possessing or selling vapor products, other than general business taxes or license fees not primarily levied on such products.

. No political subdivision may regulate the use of vapor products in outdoor public places, unless the public place is an area where children congregate, such as schools, playgrounds, and parks.

. Subject to RCW 70.345.150, political subdivisions may regulate the use of vapor products in indoor public places.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=2016%20sp.s.%20c%2038%20§%203[2016 sp.s. c 38 § 3]; ]

