= 70.305 - Adverse childhood experiences.
:toc:

== 70.305.005 - Finding—Purpose.
The legislature finds that adverse childhood experiences are a powerful common determinant of a child's ability to be successful at school and, as an adult, to be successful at work, to avoid behavioral and chronic physical health conditions, and to build healthy relationships. The purpose of this chapter is to identify the primary causes of adverse childhood experiences in communities and to mobilize broad public and private support to prevent harm to young children and reduce the accumulated harm of adverse experiences throughout childhood. A focused effort is needed to: (1) Identify and promote the use of innovative strategies based on evidence-based and research-based approaches and practices; and (2) align public and private policies and funding with approaches and strategies which have demonstrated effectiveness.

The legislature recognizes that many community public health and safety networks across the state have knowledge and expertise regarding the reduction of adverse childhood experiences and can provide leadership on this initiative in their communities. In addition, a broad range of community coalitions involved with early learning, child abuse prevention, and community mobilization have coalesced in many communities. The adverse childhood experiences initiative should coordinate and assemble the strongest components of these networks and coalitions to effectively respond to the challenge of reducing and preventing adverse childhood experiences while providing flexibility for communities to design responses that are appropriate for their community.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1965-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2032%20§%201[2011 1st sp.s. c 32 § 1]; ]

== 70.305.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Adverse childhood experiences" means the following indicators of severe childhood stressors and family dysfunction that, when experienced in the first eighteen years of life and taken together, are proven by public health research to be powerful determinants of physical, mental, social, and behavioral health across the lifespan: Child physical abuse; child sexual abuse; child emotional abuse; child emotional or physical neglect; alcohol or other substance abuse in the home; mental illness, depression, or suicidal behaviors in the home; incarceration of a family member; witnessing intimate partner violence; and parental divorce or separation. Adverse childhood experiences have been demonstrated to affect the development of the brain and other major body systems.

. "Community public health and safety networks" or "networks" means the organizations authorized under RCW 70.190.060.

. "Department" means the department of social and health services.

. "Evidence-based" has the same meaning as in RCW 43.216.157.

. "Research-based" has the same meaning as in RCW 43.216.157.

. "Secretary" means the secretary of social and health services.

. "Secretary of children, youth, and families" means the secretary of the department of children, youth, and families.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1091-S.SL.pdf?cite=2019%20c%2064%20§%2024[2019 c 64 § 24]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6287.SL.pdf?cite=2018%20c%2058%20§%2011[2018 c 58 § 11]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1965-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2032%20§%202[2011 1st sp.s. c 32 § 2]; ]

== 70.305.020 - Preventing and mitigating the effects of adverse childhood experiences—Planning group—Report to the legislature—Secretary's authority.
. [Empty]
.. The secretary of the department of social and health services and the secretary of the department of children, youth, and families shall actively participate in the development of a nongovernmental private-public initiative focused on coordinating government and philanthropic organizations' investments in the positive development of children and preventing and mitigating the effects of adverse childhood experiences. The secretaries shall convene a planning group to work with interested private partners to: (i) Develop a process by which the goals identified in RCW 70.305.005 shall be met; and (ii) develop recommendations for inclusive and diverse governance to advance the adverse childhood experiences initiative.

.. The secretaries shall select no more than twelve to fifteen persons as members of the planning group. The members selected must represent a diversity of interests including: Early learning coalitions, community public health and safety networks, organizations that work to prevent and address child abuse and neglect, tribes, representatives of public agency agencies involved with interventions in or prevention of adverse childhood experiences, philanthropic organizations, and organizations focused on community mobilization.

.. The secretaries shall cochair the planning group meetings and shall convene the first meeting.

. In addition to other powers granted to the secretary of the department of social and health services, the secretary of the department of social and health services may:

.. Enter into contracts on behalf of the department of social and health services to carry out the purposes of this chapter;

.. Provide funding to communities or any governance entity that is created as a result of the partnership; and

.. Accept gifts, grants, or other funds for the purposes of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6287.SL.pdf?cite=2018%20c%2058%20§%2010[2018 c 58 § 10]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1965-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2032%20§%203[2011 1st sp.s. c 32 § 3]; ]

