= 70.390 - Health care cost transparency board.
:toc:

== 70.390.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Authority" means the health care authority.

. "Board" means the health care cost transparency board.

. "Health care" means items, services, and supplies intended to improve or maintain human function or treat or ameliorate pain, disease, condition, or injury including, but not limited to, the following types of services:

.. Medical;

.. Behavioral;

.. Substance use disorder;

.. Mental health;

.. Surgical;

.. Optometric;

.. Dental;

.. Podiatric;

.. Chiropractic;

.. Psychiatric;

.. Pharmaceutical;

.. Therapeutic;

.. Preventive;

.. Rehabilitative;

.. Supportive;

.. Geriatric; or

.. Long-term care.

. "Health care cost growth" means the annual percentage change in total health care expenditures in the state.

. "Health care cost growth benchmark" means the target percentage for health care cost growth.

. "Health care coverage" means policies, contracts, certificates, and agreements issued or offered by a payer.

. "Health care provider" means a person or entity that is licensed, certified, registered, or otherwise authorized by the law of this state to provide health care in the ordinary course of business or practice of a profession.

. "Net cost of private health care coverage" means the difference in premiums received by a payer and the claims for the cost of health care paid by the payer under a policy or certificate of health care coverage.

. "Payer" means:

.. A health carrier as defined in RCW 48.43.005;

.. A publicly funded health care program, including medicaid, medicare, the state children's health insurance program, and public and school employee benefit programs administered under chapter 41.05 RCW;

.. A third-party administrator; and

.. Any other public or private entity, other than an individual, that pays or reimburses the cost for the provision of health care.

. "Total health care expenditures" means all health care expenditures in this state by public and private sources, including:

.. All payments on health care providers' claims for reimbursement for the cost of health care provided;

.. All payments to health care providers other than payments described in (a) of this subsection;

.. All cost-sharing paid by residents of this state, including copayments, deductibles, and coinsurance; and

.. The net cost of private health care coverage.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2457-S2.SL.pdf?cite=2020%20c%20340%20§%201[2020 c 340 § 1]; ]

== 70.390.020 - Health care cost transparency board—Duties.
The authority shall establish a board to be known as the health care cost transparency board. The board is responsible for the analysis of total health care expenditures in Washington, identifying trends in health care cost growth, and establishing a health care cost growth benchmark. The board shall provide analysis of the factors impacting these trends in health care cost growth and, after review and consultation with identified entities, shall identify those health care providers and payers that are exceeding the health care cost growth benchmark.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2457-S2.SL.pdf?cite=2020%20c%20340%20§%202[2020 c 340 § 2]; ]

== 70.390.030 - Health care cost transparency board—Appointment—Terms—Conflicts—Reimbursement—Liability.
. The board shall consist of fourteen members who shall be appointed as follows:

.. The insurance commissioner, or the commissioner's designee;

.. The administrator [director] of the health care authority, or the administrator's [director's] designee;

.. The director of labor and industries, or the director's designee;

.. The chief executive officer of the health benefit exchange, or the chief executive officer's designee;

.. One member representing local governments that purchase health care for their employees;

.. Two members representing consumers;

.. One member representing Taft-Hartley health benefit plans;

.. Two members representing large employers, at least one of which is a self-funded group health plan;

.. One member representing small businesses;

.. One member who is an actuary or an expert in health care economics;

.. One member who is an expert in health care financing; and

.. One nonvoting member who is a member of the advisory committee of health care providers and carriers and has operational experience in health care delivery.

. The governor:

.. Shall appoint the members of the board. Each of the two largest caucuses in both the house of representatives and the senate shall submit to the governor a list of five nominees. The nominees must be for members of the board identified in subsection (1)(f) through (k) of this section, may not be legislators, and, except for the members of the board identified in subsection (1)(j) and (k) of this section, the nominees may not be employees of the state or its political subdivisions. No caucus may submit the same nominee. The caucus nominations must reflect diversity in geography, gender, and ethnicity;

.. May reject a nominee and request a new submission from a caucus if a nominee does not meet the requirements of this section; and

.. Must choose at least one nominee from each caucus.

. The governor shall appoint the chair of the board.

. [Empty]
.. Initial members of the board shall serve staggered terms not to exceed four years. Members appointed thereafter shall serve two-year terms.

.. A member of the board whose term has expired or who otherwise leaves the board shall be replaced by gubernatorial appointment. Upon the expiration of a member's term, the member shall continue to serve until a successor has been appointed and has assumed office. When the person leaving was nominated by one of the caucuses of the house of representatives or the senate, his or her replacement shall be appointed from a list of five nominees submitted by that caucus within thirty days after the person leaves. If the member to be replaced is the chair, the governor shall appoint a new chair within thirty days after the vacancy occurs. A person appointed to replace a member who leaves the board prior to the expiration of his or her term shall serve only the duration of the unexpired term. Members of the board may be reappointed to multiple terms.

. No member of the board may be appointed if the member's participation in the decisions of the board could benefit the member's own financial interests or the financial interests of an entity the member represents. A board member who develops such a conflict of interest shall resign or be removed from the board.

. Members of the board must be reimbursed for their travel expenses while on official business in accordance with RCW 43.03.050 and 43.03.060. The board shall prescribe rules for the conduct of its business. Meetings of the board are subject to the call of the chair.

. The board and its subcommittees are subject to the provisions of chapter 42.30 RCW, the open public meetings act, and chapter 42.56 RCW, the public records act. The board and its subcommittees may not disclose any health care information that identifies or could reasonably identify the patient or consumer who is the subject of the health care information.

. Members of the board are not civilly or criminally liable and may not have any penalty or cause of action of any nature arise against them for any action taken or not taken, including any discretionary decision or failure to make a discretionary decision, when the action or inaction is done in good faith and in the performance of the powers and duties under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2457-S2.SL.pdf?cite=2020%20c%20340%20§%203[2020 c 340 § 3]; ]

== 70.390.040 - Advisory committees—Appointment.
. The board shall establish an advisory committee on data issues and an advisory committee of health care providers and carriers. The board may establish other advisory committees as it finds necessary.

. Appointments to the advisory committee on data issues shall be made by the board. Members of the committee must have expertise in health data collection and reporting, health care claims data analysis, health care economic analysis, and actuarial analysis.

. Appointments to the advisory committee of health care providers and carriers shall be made by the board and must include the following membership:

.. One member representing hospitals and hospital systems, selected from a list of three nominees submitted by the Washington state hospital association;

.. One member representing federally qualified health centers, selected from a list of three nominees submitted by the Washington association for community health;

.. One physician, selected from a list of three nominees submitted by the Washington state medical association;

.. One primary care physician, selected from a list of three nominees submitted by the Washington academy of family physicians;

.. One member representing behavioral health providers, selected from a list of three nominees submitted by the Washington council for behavioral health;

.. One member representing pharmacists and pharmacies, selected from a list of three nominees submitted by the Washington state pharmacy association;

.. One member representing advanced registered nurse practitioners, selected from a list of three nominees submitted by ARNPs united of Washington state;

.. One member representing tribal health providers, selected from a list of three nominees submitted by the American Indian health commission;

.. One member representing a health maintenance organization, selected from a list of three nominees submitted by the association of Washington health care plans;

.. One member representing a managed care organization that contracts with the authority to serve medical assistance enrollees, selected from a list of three nominees submitted by the association of Washington health care plans;

.. One member representing a health care service contractor, selected from a list of three nominees submitted by the association of Washington health care plans;

.. One member representing an ambulatory surgery center selected from a list of three nominees submitted by the ambulatory surgery center association; and

.. Three members, at least one of whom represents a disability insurer, selected from a list of six nominees submitted by America's health insurance plans.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2457-S2.SL.pdf?cite=2020%20c%20340%20§%204[2020 c 340 § 4]; ]

== 70.390.050 - Authority to establish advisory committees—Duties.
. The board has the authority to establish and appoint advisory committees, in accordance with the requirements of RCW 70.390.040, and seek input and recommendations from the advisory committees on topics relevant to the work of the board.

. The board shall:

.. Determine the types and sources of data necessary to annually calculate total health care expenditures and health care cost growth, and to establish the health care cost growth benchmark, including execution of any necessary access and data security agreements with the custodians of the data. The board shall first identify existing data sources, such as the statewide health care claims database established in chapter 43.371 RCW and prescription drug data collected under chapter 43.71C RCW, and primarily rely on these sources when possible in order to minimize the creation of new reporting requirements;

.. Determine the means and methods for gathering data to annually calculate total health care expenditures and health care cost growth, and to establish the health care cost growth benchmark. The board must select an appropriate economic indicator to use when establishing the health care cost growth benchmark. The activities may include selecting methodologies and determining sources of data. The board shall accept recommendations from the advisory committee on data issues and the advisory committee of health care providers and carriers regarding the value and feasibility of reporting various categories of information under (c) of this subsection, such as urban and rural, public sector and private sector, and major categories of health services, including prescription drugs, inpatient treatment, and outpatient treatment;

.. Annually calculate total health care expenditures and health care cost growth:

... Statewide and by geographic rating area;

... For each health care provider or provider system and each payer, taking into account the health status of the patients of the health care provider or the enrollees of the payer, utilization by the patients of the health care provider or the enrollees of the payer, intensity of services provided to the patients of the health care provider or the enrollees of the payer, and regional differences in input prices. The board must develop an implementation plan for reporting information about health care providers, provider systems, and payers;

... By market segment;

... Per capita; and

.. For other categories, as recommended by the advisory committees in (b) of this subsection, and approved by the board;

.. Annually establish the health care cost growth benchmark for increases in total health expenditures. The board, in determining the health care cost growth benchmark, shall begin with an initial implementation that applies to the highest cost drivers in the health care system and develop a phased plan to include other components of the health system for subsequent years;

.. Beginning in 2023, analyze the impacts of cost drivers to health care and incorporate this analysis into determining the annual total health care expenditures and establishing the annual health care cost growth benchmark. The cost drivers may include, to the extent such data is available:

... Labor, including but not limited to, wages, benefits, and salaries;

... Capital costs, including but not limited to new technology;

... Supply costs, including but not limited to prescription drug costs;

... Uncompensated care;

.. Administrative and compliance costs;

.. Federal, state, and local taxes;

.. Capacity, funding, and access to postacute care, long-term services and supports, and housing; and

.. Regional differences in input prices; and

.. Release reports in accordance with RCW 70.390.070.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2457-S2.SL.pdf?cite=2020%20c%20340%20§%205[2020 c 340 § 5]; ]

== 70.390.060 - Contracting for administration—Funding.
. The authority may contract with a private nonprofit entity to administer the board and provide support to the board to carry out its responsibilities under this chapter. The authority may not contract with a private nonprofit entity that has a financial interest that may create a potential conflict of interest or introduce bias into the board's deliberations.

. The authority or the contracted entity shall actively solicit federal and private funding and in-kind contributions necessary to complete its work in a timely fashion. The contracted entity shall not accept private funds if receipt of such funding could present a potential conflict of interest or introduce bias into the board's deliberations.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2457-S2.SL.pdf?cite=2020%20c%20340%20§%206[2020 c 340 § 6]; ]

== 70.390.070 - Reporting.
. By August 1, 2021, the board shall submit a preliminary report to the governor and each chamber of the legislature. The preliminary report shall address the progress toward establishment of the board and advisory committees and the establishment of total health care expenditures, health care cost growth, and the health care cost growth benchmark for the state, including proposed methodologies for determining each of these calculations. The preliminary report shall include a discussion of any obstacles related to conducting the board's work including any deficiencies in data necessary to perform its responsibilities under RCW 70.390.050 and any supplemental data needs.

. Beginning August 1, 2022, the board shall submit annual reports to the governor and each chamber of the legislature. The first annual report shall determine the total health care expenditures for the most recent year for which data is available and shall establish the health care cost growth benchmark for the following year. The annual reports may include policy recommendations applicable to the board's activities and analysis of its work, including any recommendations related to lowering health care costs, focusing on private sector purchasers, and the establishment of a rating system of health care providers and payers.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2457-S2.SL.pdf?cite=2020%20c%20340%20§%207[2020 c 340 § 7]; ]

