= 70.335 - Blood establishments.
:toc:

== 70.335.010 - Findings—Intent.
The legislature finds that maintaining public trust and confidence in the safety of the community blood supply is important to the health care system. Patients in Washington needing lifesaving transfusions rightly expect safe blood and blood donors in Washington rightly expect their contributions will be managed with diligent care and compliance with all regulatory standards and expectations so their donation will benefit patients in need. The United States food and drug administration establishes regulations, good manufacturing practices, and guidance that defines the minimum standards for blood establishments and, in cases of repeated violations and noncompliance by licensed blood establishments, may impose measures that include fines, judicial consent decrees, and suspension or revocation of licensure. It is therefore the intent of the legislature that blood-collecting or distributing establishments be registered with the department of health to help ensure public transparency.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2580-S.SL.pdf?cite=2016%20c%2047%20§%201[2016 c 47 § 1]; ]

== 70.335.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Blood-collecting or distributing establishment" or "establishment" means any organization that collects or distributes blood for allogeneic transfusion in Washington. This chapter does not apply to a hospital licensed under chapter 70.41 or 71.12 RCW unless the hospital collects blood directly from donors for the purpose of allogeneic transfusions. For the purposes of this chapter, "blood-collecting or distributing establishment" or "establishment" does not include organizations that collect source plasma for the production of plasma derivatives by fractionation.

. "Change in standing" means that a blood-collecting or distributing establishment is the subject of titled letters, fines, suspensions, or revocations of its United States food and drug administration license, or judicial consent decrees.

. "Department" means the Washington state department of health.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2580-S.SL.pdf?cite=2016%20c%2047%20§%202[2016 c 47 § 2]; ]

== 70.335.030 - Registration required—Applications for registration—Criteria—Suspension—Expiration—Fees.
. A blood-collecting or distributing establishment may not collect or distribute blood for transfusion in Washington, unless it is registered by the department.

. A blood-collecting or distributing establishment shall submit an application for registration to the department on a form prescribed by the department. The application must, at a minimum, contain the following information:

.. The name, address, and telephone number of the blood-collecting or distributing establishment;

.. A copy of the establishment's United States food and drug administration license, unless the applicant is a hospital that meets the criteria in RCW 70.335.020(1);

.. A list of the establishment's clients in Washington;

.. Any of the following issued upon, or active against, the establishment in the two years prior to the application:

... Titled letters, fines, or license suspensions or revocations issued by the United States food and drug administration; or

... Judicial consent decrees; and

.. Any other information required by the department.

. The department shall register a blood-collecting or distributing establishment if it holds a license issued by the United States food and drug administration, or if the applicant is a hospital that meets the criteria in RCW 70.335.020(1), and submits an application and fees as required by this section.

. The department shall deny or revoke the registration of an establishment upon a determination that it no longer holds a license issued by the United States food and drug administration.

. The department shall issue a summary suspension of the registration if the blood-collecting or distributing establishment no longer holds a license issued by the United States food and drug administration. The summary suspension remains in effect until proceedings under RCW 43.70.115 have been completed by the department. The issue in the proceedings is limited to whether the blood-collecting or distributing establishment is qualified to hold a registration under this section.

. A registration expires annually on the date specified on the registration. The department shall establish the administrative procedures and requirements for registration renewals, including a requirement that the establishment update the information provided under subsection (2) of this section both annually and within fourteen days of a change in standing of the establishment's United States food and drug administration license.

. An establishment applying for or renewing a registration under this section shall pay a fee in an amount set by the department in rule. In no case may the fee exceed the amount necessary to defray the costs of administering this chapter.

. This section does not apply in the case of individual patient medical need, as determined by a qualified provider.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2580-S.SL.pdf?cite=2016%20c%2047%20§%203[2016 c 47 § 3]; ]

== 70.335.040 - Public registry—Notification of changes.
. The department shall create and maintain an online public registry of all registered blood-collecting or distributing establishments that supply blood products for transfusion in Washington.

. The department shall, within fourteen days of receipt, publish in the public registry the information received from each registered blood-collecting or distributing establishment under RCW 70.335.030, including changes in the standing of the establishment's United States food and drug administration license.

. The department shall notify all of a blood-collecting or distributing establishment's Washington clients within fourteen days of receiving notice under RCW 70.335.030 that the establishment has experienced a change in standing in its United States food and drug administration license or no longer holds a license issued by the United States food and drug administration.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2580-S.SL.pdf?cite=2016%20c%2047%20§%204[2016 c 47 § 4]; ]

== 70.335.050 - Enforcement.
The department may, in the manner provided by law and upon the advice of the attorney general, who shall represent the department in the proceedings, maintain an action in the name of the state for an injunction or other process against any blood-collecting or distributing establishment to restrain or prevent the operation of the establishment without a registration issued under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2580-S.SL.pdf?cite=2016%20c%2047%20§%205[2016 c 47 § 5]; ]

