= 13.22 - Juvenile solitary confinement.
:toc:

== 13.22.005 - Finding—Intent—2020 c 333.
. The legislature finds that prolonged isolation for juveniles may cause harm. Prolonged solitary confinement has also been shown as ineffective at reducing behavioral incidents and may increase anxiety and anger in youth.

. Creating alternative solutions to solitary confinement for juveniles will further protect the well-being of juveniles in all detention facilities and institutions and enhance the rehabilitative goals of Washington's juvenile justice system. Chapter 333, Laws of 2020 seeks to end the use of solitary confinement in juvenile facilities when used as a form of punishment or retaliation. Chapter 333, Laws of 2020 also seeks to limit placement in isolation, except in the circumstances outlined in RCW 13.22.020. Juvenile institutions and detention facilities must implement a system of graduated interventions to avoid the use of solitary confinement. Less restrictive forms of confinement should be used to regulate the behavior of juveniles in institutions and detention facilities.

. The legislature intends to prevent the use of solitary confinement and, in the limited instances of isolation, ensure that the use advances the rehabilitative goals of Washington's juvenile justice system, and that it is not used as a punitive measure.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2277-S2.SL.pdf?cite=2020%20c%20333%20§%201[2020 c 333 § 1]; ]

== 13.22.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Department" means the department of children, youth, and families.

. "Detention facility" means:

.. Any detention facility as defined under RCW 13.40.020; and

.. Any juvenile correctional facility under alternative administration operated by a consortium of counties under RCW 13.04.035.

. "Imminent harm" means immediate and impending threat of a person causing bodily injury to self or others.

. "Institution" has the same meaning as in RCW 13.40.020.

. "Isolation" means confinement that occurs (a) when a youth is separated from the youth population and placed in a room for longer than fifteen minutes for the purpose of discipline, behavior modification, or due to an imminent threat to the safety of the youth or others; and (b) in a room other than the room assigned to the youth for sleeping. Juveniles are in isolation from the moment they are separated from others until they have rejoined the population. Juveniles who are pregnant shall not be put into isolation. Maintaining appropriate gender separation does not constitute isolation.

. "Juvenile" means:

.. Any individual who is under the chronological age of eighteen years; and

.. Any individual under the chronological age of twenty-five years who is confined in an institution, including an individual confined in an institution under RCW 72.01.410.

. "Juvenile court administrator" means an administrator appointed pursuant to RCW 13.04.035.

. "Room confinement" means a juvenile is separated from the youth population and placed in a room or cell that the juvenile is assigned to for sleeping, other than during normal sleeping hours or interim rest hours. "Room confinement" does not include time a youth requests to spend in his or her room or rest periods in between facility programming. Juveniles are in room confinement from the moment they are separated from others until they are permitted to rejoin the population.

. "Solitary confinement" means a youth is involuntarily separated from the youth population and placed in a room or cell other than the room assigned to the youth for sleeping for longer than fifteen minutes for punitive purposes. Different terminology does not exempt practice from being "solitary confinement."

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2277-S2.SL.pdf?cite=2020%20c%20333%20§%202[2020 c 333 § 2]; ]

== 13.22.020 - Juvenile solitary confinement prohibited—Exceptions.
. The use of solitary confinement for juveniles in a detention facility or institution is prohibited.

. A juvenile may only be placed in isolation or room confinement in a detention facility or institution as authorized in this section.

.. [Empty]
... Total isolation and room confinement of a juvenile shall be limited in duration to no more than four hours in any twenty-four hour period. Detention facilities and institutions can exceed those four hours, including if the extension is necessary due to subsequent or multiple incidents, if the following requirements are met:

(A) The reason for isolation or room confinement is documented, including the basis for the extension, the date and time the juvenile was first placed in isolation or room confinement, and when the juvenile is eventually released from isolation or room confinement;

(B) An individualized plan that includes the goals and objectives to be met in order to reintegrate the juvenile to the general population is developed;

(C) The detention facility or institution superintendent or his or her designee provides documented authorization every four hours thereafter.

... A medical and mental health assessment may occur after the juvenile's release so as not to extend his or her time in isolation or confinement.

... If the total isolation or room confinement exceeds twenty-four hours, then the secretary, or his or her designee, of the department or the juvenile court administrator must provide documented authorization.

.. Each juvenile placed in isolation or room confinement shall be visually checked at least every fifteen minutes, and staff shall attend to the needs of the juvenile at that time. Staff shall attempt to communicate with an awake juvenile during required checks to evaluate and encourage the juvenile on the goals and objectives the juvenile needs to achieve in order to be released from isolation or room confinement.

.. Every instance of isolation and room confinement shall be documented in accordance with RCW 13.22.040 or 13.22.050.

.. When a juvenile is placed in isolation or under room confinement, the juvenile must have access to:

... Clothing;

... Mattress and bedding;

... Medication under staff supervision;

... A toilet and sink at least hourly;

.. A bath or shower at least daily;

.. Necessary mental health services; and

.. Reading material, paper, writing material, envelopes, and treatment material, unless precluded by suicide precaution level or the items would hinder staff efforts to resolve the problems that caused isolation or room confinement.

.. Staff must remove the juvenile from isolation and room confinement when one of the following requirements is met:

... The purpose of the confinement is met;

... The desired behavior is evident; or

... The juvenile has been evaluated by a professional who has determined the juvenile is no longer an imminent risk to self, staff, or the general population. The institution or detention facility may designate who counts as a professional.

.. Isolation can be used when:

... Isolation is necessary to prevent imminent harm based on the juvenile's behavior, and less restrictive alternatives were unsuccessful;

... The juvenile needs to be held in isolation awaiting transfer of facilities;

... The juvenile needs to be placed in isolation overnight due to disruptive behavior that prevents the nighttime routine of other juvenile residents; or

... It is necessary to respond to an escape attempt.

.. Room confinement can be used when it is necessary to prevent behavior that causes disruption of the detention facility or institution, but the behavior does not rise to the level of imminent harm including, but not limited to, behavior that may constitute a violation of law.

. Nothing in this section requires that juveniles be placed with adults while in custody.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2277-S2.SL.pdf?cite=2020%20c%20333%20§%203[2020 c 333 § 3]; ]

== 13.22.030 - Model policy.
. The department shall, by July 1, 2021, adopt a model policy prohibiting the use of solitary confinement of juveniles in detention facilities and institutions, with the goal of also limiting the use and duration of isolation and room confinement. In determining the model policy, the department must consult with appropriate stakeholders including, but not limited to, juvenile court administrators, impacted youth, and representatives of staff. At a minimum, the model policy must include:

.. Isolation. Isolation may only be used as a last resort when less restrictive methods have not been effective. Where needed, medical professionals must assess or evaluate any juvenile in isolation as soon as possible after the juvenile is placed in isolation, and qualified mental health professionals must evaluate and develop a care plan for juveniles placed in isolation to prevent self-harm as soon as possible after the juvenile is placed in isolation. The model policy must include measures to prevent the use of isolation, while protecting the safety and security of incarcerated juveniles and their peers, the staff of the detention facilities and institutions, other persons who work in the detention facilities and institutions, and visitors.

.. Room confinement. Room confinement is the preferred option for maladaptive or negative behavior. Staff will use the least amount of time to meet the purpose of the intervention. The model policy must include measures to prevent the use of room confinement, while protecting the safety and security of incarcerated juveniles and their peers, the staff of the detention facilities and institutions, other persons who work in the detention facilities and institutions, and visitors.

. By December 1, 2021, the detention facility or institution shall review and either (a) adopt the model policy established in this section or (b) notify the department of the reasons the detention facility or institution will not adopt the model policy, including how the detention facility or institution's policies and procedures differ from the model policy.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2277-S2.SL.pdf?cite=2020%20c%20333%20§%204[2020 c 333 § 4]; ]

== 13.22.040 - Reporting requirements for the department.
. The department must compile, on a monthly basis until November 1, 2022, the following information with respect to juveniles confined in all state institutions and facilities used for juvenile rehabilitation for whom isolation or room confinement was used in excess of one hour:

.. The number of times isolation and room confinement were used;

.. The circumstances leading to the use of isolation and room confinement;

.. The duration of each use of isolation and whether, for each instance of isolation, the use of isolation lasted more than four hours within a twenty-four hour period;

.. Whether or not supervisory review occurred and was documented for each instance of isolation and room confinement;

.. The race and age of the juvenile for each instance of isolation and room confinement;

.. Whether or not a medical assessment or review and a mental health assessment or review were conducted and documented for each instance of isolation; and

.. If the affected juvenile was not afforded access to medication, meals, and reading material during the term of confinement for each instance of isolation and room confinement.

. Until November 1, 2022, information collected under subsection (1) of this section must be compiled into a report and submitted in compliance with RCW 13.22.060(1).

. After November 1, 2022, the department must annually compile the information collected under subsection (1) of this section. The information collected must be posted on the department's website.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2277-S2.SL.pdf?cite=2020%20c%20333%20§%205[2020 c 333 § 5]; ]

== 13.22.050 - Reporting requirements for a county.
. A county operating a detention facility must compile, on a monthly basis until November 1, 2022, the following information with respect to the detention facility for whom isolation or room confinement was used in excess of one hour:

.. The number of times isolation and room confinement were used;

.. The circumstances leading to the use of isolation and room confinement;

.. The duration of each use of isolation and whether, for each instance of isolation, the use of isolation lasted more or less than four hours within a twenty-four hour period, and, for instances lasting more than four hours, the length of time the juvenile remained in isolation;

.. Whether or not supervisory review occurred and was documented for each instance of isolation and room confinement;

.. The race and age of the juvenile for each instance of isolation and room confinement;

.. Whether or not a medical assessment or review and a mental health assessment or review were conducted and documented for each instance of isolation; and

.. If the affected juvenile was not afforded access to medication, meals, and reading material during the term of confinement for each instance of isolation and room confinement.

. Until November 1, 2022, information collected under subsection (1) of this section must be compiled into a report and submitted in compliance with RCW 13.22.060(1).

. After November 1, 2022, a county operating a detention facility must annually compile the information collected under subsection (1) of this section. The information collected must be posted on the detention facility's website.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2277-S2.SL.pdf?cite=2020%20c%20333%20§%206[2020 c 333 § 6]; ]

== 13.22.060 - Information reporting—Data report to the legislature.
. Information collected under RCW 13.22.040(2), 13.22.050(2), and 13.04.116(1)(c) must be reported to the department of children, youth, and families by December 1, 2021, and an updated report must be submitted to the department by November 1, 2022. The department must compile the reported data and, in compliance with RCW 43.01.036, provide a data report to the appropriate committees of the legislature by December 1, 2022.

. Beginning in January 2023, the department shall conduct periodic reviews of policies, procedures, and use of solitary confinement, isolation, and room confinement in juvenile detention facilities and institutions. Every three years, the department shall prepare a report to the legislature summarizing its reviews.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2277-S2.SL.pdf?cite=2020%20c%20333%20§%207[2020 c 333 § 7]; ]

== 13.22.900 - Conflict with federal requirements—2020 c 333.
If any part of this act is found to be in conflict with federal requirements that are a prescribed condition to the allocation of federal funds to the state, the conflicting part of this act is inoperative solely to the extent of the conflict and with respect to the agencies directly affected, and this finding does not affect the operation of the remainder of this act in its application to the agencies concerned. Rules adopted under this act must meet federal requirements that are a necessary condition to the receipt of federal funds by the state.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2277-S2.SL.pdf?cite=2020%20c%20333%20§%209[2020 c 333 § 9]; ]

