= 13.64 - Emancipation of minors.
:toc:

== 13.64.010 - Declaration of emancipation.
Any minor who is sixteen years of age or older and who is a resident of this state may petition in the superior court for a declaration of emancipation.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1157-S.SL.pdf?cite=1993%20c%20294%20§%201[1993 c 294 § 1]; ]

== 13.64.020 - Petition for emancipation—Filing fees.
. A petition for emancipation shall be signed and verified by the petitioner, and shall include the following information: (a) The full name of the petitioner, the petitioner's birthdate, and the state and county of birth; (b) a certified copy of the petitioner's birth certificate; (c) the name and last known address of the petitioner's parent or parents, guardian, or custodian; (d) the petitioner's present address, and length of residence at that address; (e) a declaration by the petitioner indicating that he or she has the ability to manage his or her financial affairs, including any supporting information; and (f) a declaration by the petitioner indicating that he or she has the ability to manage his or her personal, social, educational, and nonfinancial affairs, including any supporting information.

. Fees for this section are set under RCW 36.18.014.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1692-S.SL.pdf?cite=1995%20c%20292%20§%207[1995 c 292 § 7]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1157-S.SL.pdf?cite=1993%20c%20294%20§%202[1993 c 294 § 2]; ]

== 13.64.030 - Service of petition—Notice—Date of hearing.
The petitioner shall serve a copy of the filed petition and notice of hearing on the petitioner's parent or parents, guardian, or custodian at least fifteen days before the emancipation hearing. No summons shall be required. Service shall be waived if proof is made to the court that the address of the parent or parents, guardian, or custodian is unavailable or unascertainable. The petitioner shall also serve notice of the hearing on the department of children, youth, and families if the petitioner is subject to dependency disposition order under RCW 13.34.130. The hearing shall be held no later than sixty days after the date on which the petition is filed.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20317[2017 3rd sp.s. c 6 § 317]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1157-S.SL.pdf?cite=1993%20c%20294%20§%203[1993 c 294 § 3]; ]

== 13.64.040 - Hearing on petition.
. The hearing on the petition shall be before a judicial officer, sitting without a jury. Prior to the presentation of proof the judicial officer shall determine whether: (a) The petitioning minor understands the consequences of the petition regarding his or her legal rights and responsibilities; (b) a guardian ad litem should be appointed to investigate the allegations of the petition and file a report with the court.

. For the purposes of this section, the term "judicial officer" means: (a) A judge; (b) a superior court commissioner of a unified family court if the county operates a unified family court; or (c) any superior court commissioner if the county does not operate a unified family court. The term does not include a judge pro tempore.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5392.SL.pdf?cite=2001%20c%20161%20§%201[2001 c 161 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1157-S.SL.pdf?cite=1993%20c%20294%20§%204[1993 c 294 § 4]; ]

== 13.64.050 - Emancipation decree—Certified copy—Notation of emancipated status.
. The court shall grant the petition for emancipation, except as provided in subsection (2) of this section, if the petitioner proves the following facts by clear and convincing evidence: (a) That the petitioner is sixteen years of age or older; (b) that the petitioner is a resident of the state; (c) that the petitioner has the ability to manage his or her financial affairs; and (d) that the petitioner has the ability to manage his or her personal, social, educational, and nonfinancial affairs.

. A parent, guardian, custodian, or in the case of a dependent minor, the department of children, youth, and families, may oppose the petition for emancipation. The court shall deny the petition unless it finds, by clear and convincing evidence, that denial of the grant of emancipation would be detrimental to the interests of the minor.

. Upon entry of a decree of emancipation by the court the petitioner shall be given a certified copy of the decree. The decree shall instruct the petitioner to obtain a Washington driver's license or a Washington identification card and direct the department of licensing make a notation of the emancipated status on the license or identification card.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20318[2017 3rd sp.s. c 6 § 318]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1157-S.SL.pdf?cite=1993%20c%20294%20§%205[1993 c 294 § 5]; ]

== 13.64.060 - Power and capacity of emancipated minor.
. An emancipated minor shall be considered to have the power and capacity of an adult, except as provided in subsection (2) of this section. A minor shall be considered emancipated for the purposes of, but not limited to:

.. The termination of parental obligations of financial support, care, supervision, and any other obligation the parent may have by virtue of the parent-child relationship, including obligations imposed because of marital dissolution;

.. The right to sue or be sued in his or her own name;

.. The right to retain his or her own earnings;

.. The right to establish a separate residence or domicile;

.. The right to enter into nonvoidable contracts;

.. The right to act autonomously, and with the power and capacity of an adult, in all business relationships, including but not limited to property transactions;

.. The right to work, and earn a living, subject only to the health and safety regulations designed to protect those under age of majority regardless of their legal status; and

.. The right to give informed consent for receiving health care services.

. An emancipated minor shall not be considered an adult for: (a) The purposes of the adult criminal laws of the state unless the decline of jurisdiction procedures contained in RCW 13.40.110 are used or the minor is tried in criminal court pursuant to *RCW 13.04.030(1)(e)(iv); (b) the criminal laws of the state when the emancipated minor is a victim and the age of the victim is an element of the offense; or (c) those specific constitutional and statutory age requirements regarding voting, use of alcoholic beverages, possession of firearms, and other health and safety regulations relevant to the minor because of the minor's age.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=1994%20sp.s.%20c%207%20§%20436[1994 sp.s. c 7 § 436]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1157-S.SL.pdf?cite=1993%20c%20294%20§%206[1993 c 294 § 6]; ]

== 13.64.070 - Declaration of emancipation—Voidable.
A declaration of emancipation obtained by fraud is voidable. The voiding of any such declaration shall not affect any obligations, rights, or interests that arose during the period the declaration was in effect.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1157-S.SL.pdf?cite=1993%20c%20294%20§%207[1993 c 294 § 7]; ]

== 13.64.080 - Forms to initiate petition of emancipation.
The administrative office of the courts shall prepare and distribute to the county court clerks appropriate forms for minors seeking to initiate a petition of emancipation.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1668.SL.pdf?cite=2005%20c%20282%20§%2028[2005 c 282 § 28]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1157-S.SL.pdf?cite=1993%20c%20294%20§%208[1993 c 294 § 8]; ]

== 13.64.900 - Effective date—1993 c 294.
This act shall take effect January 1, 1994.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1157-S.SL.pdf?cite=1993%20c%20294%20§%2011[1993 c 294 § 11]; ]

== 13.64.901 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%2044[2009 c 521 § 44]; ]

