= 13.90 - Vulnerable youth guardianship program.
:toc:

== 13.90.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Department" means the department of children, youth, and families.

. "Guardian" means a person who has been appointed by the court as the guardian of a vulnerable youth in a legal proceeding under this chapter. The term "guardian" does not include a "dependency guardian" appointed pursuant to a proceeding under chapter 13.34 RCW for the purpose of assisting the court in supervising the dependency. The term "guardian" does not include a "guardian" appointed pursuant to a proceeding under chapter 13.36 RCW or a "dependency guardian" appointed pursuant to a proceeding under chapter 13.34 RCW.

. "Juvenile court" or "court" means the juvenile division of the superior court.

. "Relative" means a person related to the child in the following ways:

.. Any parent, or blood relative, including those of half-blood, and including first cousins, second cousins, nephews or nieces, and persons of preceding generations as denoted by prefixes of grand, great, or great-great;

.. A stepfather, stepmother, stepbrother, and stepsister;

.. A person who legally adopts a child or the child's parent as well as the natural and other legally adopted children of such persons, and other relatives of the adoptive parents in accordance with state law;

.. Spouses of any persons named in (a) through (c) of this subsection (4), even after the marriage is terminated;

.. Relatives, as described in (a) through (d) of this subsection (4), of any half-sibling of the child.

. [Empty]
.. "Suitable person" means a nonrelative who has completed all required criminal history background checks as specified in (b) of this subsection and otherwise appears to be suitable and competent to provide care for the youth.

.. The criminal background checks required in (a) of this subsection are those set out in *RCW 26.10.135 (1) and (2)(b), but apply only to the guardian and not to other adult members of the household.

. "Vulnerable youth" is an individual who has turned eighteen years old, but who is not yet twenty-one years old and who is eligible for classification under 8 U.S.C. Sec. 1101(a)(27)(J). A youth who remains in a vulnerable youth guardianship under this chapter shall not be considered a "child" under any other state statute or for any other purpose. A vulnerable youth is one who is not also a nonminor dependent who is participating in extended foster care services authorized under RCW 74.13.031.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6287.SL.pdf?cite=2018%20c%2058%20§%2075[2018 c 58 § 75]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1988-S.SL.pdf?cite=2017%20c%20279%20§%203[2017 c 279 § 3]; ]

== 13.90.020 - Petition for guardianship—Requirements.
. A vulnerable youth may petition the court that a vulnerable youth guardianship be established for him or her by filing a petition in juvenile court under this chapter. The proposed guardian must agree to join in the petition, and must receive notice of the petition.

. To be designated as a proposed guardian in a petition under this chapter, a person must be age twenty-one or over, suitable, and capable of performing the duties of guardian under RCW 13.90.040, including but not limited to parents, licensed foster parents, relatives, and suitable persons.

. The petition must allege and show that:

.. Both the petitioner and the proposed guardian agree to the establishment of a guardianship;

.. The youth is between the ages of eighteen and twenty-one years;

.. The youth is prima facie eligible to apply for classification under 8 U.S.C. Sec. 1101(a)(27)(J);

.. The youth requests the support of a responsible adult; and

.. The proposed guardian agrees to serve as guardian, and is a suitable adult over twenty-one years old who is capable of performing the duties of a guardian as stated in RCW 13.90.040.

. There must be no fee associated with the filing of a vulnerable youth guardianship petition by or for a vulnerable youth under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1988-S.SL.pdf?cite=2017%20c%20279%20§%204[2017 c 279 § 4]; ]

== 13.90.030 - Petition for guardianship—Hearing.
. At the hearing on a vulnerable youth guardianship petition, both parties, the vulnerable youth and the proposed guardian, have the right to present evidence and cross-examine witnesses. The rules of evidence apply to the conduct of the hearing.

. A vulnerable youth guardianship must be established if the court finds by a preponderance of the evidence that:

.. The allegations in the petition are true;

.. It is in the vulnerable youth's best interest to establish a vulnerable youth guardianship; and

.. The vulnerable youth consents in writing to the appointment of a guardian.

. A guardianship established under subsection (2) of this section remains in effect as provided in RCW 13.90.060.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1988-S.SL.pdf?cite=2017%20c%20279%20§%205[2017 c 279 § 5]; ]

== 13.90.040 - Order establishing guardianship.
. If the court has made the findings required under RCW 13.90.030, the court shall issue an order establishing a vulnerable youth guardianship for the vulnerable youth. The order shall:

.. Appoint a person to be the guardian for the vulnerable youth;

.. Provide that the guardian shall ensure that the legal rights of the vulnerable youth are not violated, and may specify the guardian's other rights and responsibilities concerning the care, custody, and nurturing of the vulnerable youth;

.. Specify that the guardian shall not have possession of any identity documents belonging to the vulnerable youth; and

.. Specify the need for and scope of continued oversight by the court, if any.

. Unless specifically ordered by the court, the standards and requirements for relocation in chapter 26.09 RCW do not apply to vulnerable youth guardianships established under this chapter.

. The court shall provide a certified copy of the vulnerable youth guardianship order to the vulnerable youth and the guardian.

. For an unrepresented vulnerable youth whose vulnerable youth guardian is a suitable person, as defined in RCW 13.90.010, the court shall provide a list of service providers and available resources for survivors of human trafficking, such as any relevant lists or materials created by the Washington state task force against the trafficking of persons under RCW 7.68.350.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1988-S.SL.pdf?cite=2017%20c%20279%20§%206[2017 c 279 § 6]; ]

== 13.90.050 - Motion for modification—Motion for appointment of a new guardian.
. The youth may move the court to modify the provisions of a vulnerable youth guardianship order at any time by: (a) Filing with the court a motion for modification and an affidavit setting forth facts supporting the requested modification; and (b) providing notice and a copy of the motion and affidavit to the other party. The nonmoving party may file and serve opposing affidavits.

. The youth may move the court to appoint a new guardian at any time by: (a) Filing with the court a motion for appointment of a new guardian and an affidavit setting forth facts supporting the requested appointment; and (b) providing notice and a copy of the motion and affidavit to the other party.

. The youth may move the court to substitute a new guardian, provided that the proposed new guardian is a suitable adult over twenty-one years old who is capable of performing the duties of a guardian as stated in RCW 13.90.040. The substitution of a new guardian must be permitted without termination of the vulnerable youth guardianship and the youth is not required to file a new vulnerable youth guardianship petition to substitute a guardian.

. If a party other than the youth moves the court to modify the provisions of a vulnerable youth guardianship order, the modification is subject to the youth's agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1988-S.SL.pdf?cite=2017%20c%20279%20§%207[2017 c 279 § 7]; ]

== 13.90.060 - Termination of guardianship.
. The vulnerable youth guardianship terminates on the vulnerable youth's twenty-first birthday.

. The vulnerable youth may request the termination of the vulnerable youth guardianship at any time. The court shall terminate the vulnerable youth guardianship upon the request of the vulnerable youth. The vulnerable youth may also withdraw consent to the vulnerable youth guardianship at any time.

. The guardian may request termination of the vulnerable youth guardianship by filing a petition and supporting affidavit alleging a substantial change has occurred in the circumstances of the vulnerable youth or the guardian and that the termination is necessary to serve the best interests of the vulnerable youth. The petition and affidavit must be served on both parties to the vulnerable youth guardianship.

. Except as provided in subsection (2) of this section, the court shall not terminate a vulnerable youth guardianship unless it finds, upon the basis of facts that have arisen since the vulnerable youth guardianship was established or that were unknown to the court at the time the vulnerable youth guardianship was established, that a substantial change has occurred in the circumstances of the vulnerable youth or the guardian and that termination of the vulnerable youth guardianship is necessary to serve the best interests of the vulnerable youth. The effect of a guardian's duties while serving in the military potentially impacting vulnerable youth guardianship functions is not, by itself, a substantial change of circumstances justifying termination of a vulnerable youth guardianship.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1988-S.SL.pdf?cite=2017%20c%20279%20§%208[2017 c 279 § 8]; ]

== 13.90.070 - Right to counsel.
In all proceedings under this chapter to establish, modify, or terminate a vulnerable youth guardianship order, the vulnerable youth and the guardian or prospective guardian have the right to be represented by counsel of their choosing and at their own expense.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1988-S.SL.pdf?cite=2017%20c%20279%20§%209[2017 c 279 § 9]; ]

== 13.90.900 - Purpose.
Existing federal law, 8 U.S.C. Sec. 1101(a)(27)(J), establishes a procedure for classification of abandoned, abused, or neglected youth as special immigrants who have been declared dependent on a juvenile court or legally committed to or placed in the custody of a state agency or department, or placed under the custody of an individual or entity appointed by a state or juvenile court, and authorizes those youth to apply for an adjustment of status to that of a lawful permanent resident within the United States. A youth is age-eligible if the youth is under twenty-one years old. Existing state law already provides that superior courts have jurisdiction to make judicial determinations regarding the custody and care of juveniles.

This chapter authorizes a court to appoint a guardian for a vulnerable youth from eighteen to twenty-one years old, who is not participating in extended foster care services authorized under RCW 74.13.031, and who is eligible for classification under 8 U.S.C. Sec. 1101(a)(27)(J) with the consent of the proposed ward. This chapter also provides that a vulnerable youth guardianship of the person terminates on the youth's twenty-first birthday unless the youth requests termination prior to that date. Opening court doors for the provision of a vulnerable youth guardianship serves the state's interest in eliminating human trafficking, preventing further victimization of youth, decreasing reliance on public resources, reducing youth homelessness, and offering protection for youth who may otherwise be targets for traffickers.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1988-S.SL.pdf?cite=2017%20c%20279%20§%201[2017 c 279 § 1]; ]

== 13.90.901 - Findings—Intent—2017 c 279.
. The legislature finds and declares the following:

.. Washington law grants the superior courts jurisdiction to make judicial determinations regarding the custody and care of youth within the meaning of the federal immigration and nationality act. Pursuant to 8 U.S.C. Sec. 1101(b), the term "child" means an unmarried person under twenty-one years of age. Superior courts are empowered to make the findings necessary for a youth to petition the United States citizenship and immigration services for classification under 8 U.S.C. Sec. 1101(a)(27)(J).

.. 8 U.S.C. Sec. 1101(a)(27)(J) offers interim relief from deportation to undocumented, unmarried immigrant youth under twenty-one years old, if a state court with jurisdiction over juveniles has made specific findings.

.. The findings necessary for a youth to petition for classification under 8 U.S.C. Sec. 1101(a)(27)(J) include, among others, a finding that reunification with one or both parents is not viable due to abuse, neglect, abandonment, or a similar basis under state law, and a finding that it is not in the youth's best interest to be returned to the youth's country of origin.

.. Misalignment between state and federal law continues to exist. Federal law allows a person under twenty-one years old, who otherwise meets the requirements for eligibility under 8 U.S.C. Sec. 1101(a)(27)(J), to file for relief. In Washington, however, vulnerable youth who are between eighteen and twenty-one years old have largely been unable to obtain the findings from the superior court necessary to seek classification under 8 U.S.C. Sec. 1101(a)(27)(J) and the relief that it was intended to afford them, solely because superior courts cannot take jurisdiction of these vulnerable youth under current law. This is true despite the fact that many vulnerable youth between eighteen and twenty-one years old face circumstances identical to those faced by their younger counterparts.

.. Given the recent influx of vulnerable youth arriving to the United States, many of whom have been released to family members and other adults in Washington, and who have experienced parental abuse, neglect, or abandonment, it is necessary to provide an avenue for these vulnerable youth to petition the superior courts to appoint a guardian of the person, even if the youth is over eighteen years old. This is particularly necessary in light of the vulnerability of this class of youth, and their need for a custodial relationship with a responsible adult as they adjust to a new cultural context, language, and education system, and recover from the trauma of abuse, neglect, or abandonment. These custodial arrangements promote the long-term well-being and stability of vulnerable youth present in the United States who have experienced abuse, neglect, or abandonment by one or both parents.

.. The legislature has an interest in combating human trafficking throughout Washington state. In 2003, Washington became the first state to enact a law making human trafficking a crime and has since continued its efforts to provide support services for victims of human trafficking while also raising awareness of human trafficking. Vulnerable youth who have been subject to parental abuse, neglect, or abandonment are particularly susceptible to becoming victims of human trafficking. By creating an avenue for a vulnerable youth guardianship for certain eligible individuals between eighteen and twenty-one years old, the legislature will provide such youth with the possibility for additional support and protection that a guardian can offer, which will make these youth less likely to become targets for human traffickers. Guardians can support vulnerable youth by providing them stable housing and caring for their basic necessities, which may help alleviate many of the risk factors that make such youth prime targets for trafficking and exploitation.

.. Vulnerable youth guardianships of the person may be necessary and appropriate for these individuals, even between eighteen and twenty-one years old, although a vulnerable youth for whom a guardian has been appointed retains the rights of an adult under Washington law.

. It is the intent of the legislature to give the juvenile division of superior courts jurisdiction to appoint a guardian for a consenting vulnerable youth between eighteen, up to the age of twenty-one who has been abandoned, neglected, or abused by one or both parents, or for whom the court determines that a guardian is otherwise necessary as one or both parents cannot adequately provide for the youth such that the youth risks physical or psychological harm if returned to the youth's home. The juvenile court will have jurisdiction to make the findings necessary for a vulnerable youth to petition for classification under 8 U.S.C. Sec. 1101(a)(27)(J). It is further the intent of the legislature to provide an avenue for a person between eighteen and twenty-one years old to have a guardian of the person appointed beyond eighteen years old if the youth so requests or consents to the appointment of a guardian as provided in RCW 13.90.030.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1988-S.SL.pdf?cite=2017%20c%20279%20§%202[2017 c 279 § 2]; ]

