= 24.03 - Washington nonprofit corporation act.
:toc:

== 24.03.005 - Definitions. (Effective until January 1, 2022.)
As used in this chapter, unless the context otherwise requires, the term:

. "An officer of the corporation" means, in connection with the execution of records submitted for filing with the secretary of state, the president, a vice president, the secretary, or the treasurer of the corporation.

. "Articles of incorporation" and "articles" mean the original articles of incorporation and all amendments thereto, and includes articles of merger and restated articles.

. "Board of directors" means the group of persons vested with the management of the affairs of the corporation irrespective of the name by which such group is designated in the articles or bylaws.

. "Bylaws" means the code or codes of rules adopted for the regulation or management of the affairs of the corporation irrespective of the name or names by which such rules are designated.

. "Conforms to law," as used in connection with duties of the secretary of state in reviewing records for filing under this chapter, means the secretary of state has determined that the record complies as to form with the applicable requirements of this chapter and Article 2 of chapter 23.95 RCW.

. "Corporation" or "domestic corporation" means a corporation not for profit subject to the provisions of this chapter, except a foreign corporation.

. "Deliver" means: (a) Mailing; (b) transmission by facsimile equipment, for purposes of delivering a demand, consent, notice, or waiver to the corporation or one of its officers, directors, or members; (c) electronic transmission, in accordance with the officer's, director's, or member's consent, for purposes of delivering a demand, consent, notice, or waiver to the corporation or one of its officers, directors, or members under RCW 24.03.009; and (d) as prescribed by the secretary of state for purposes of submitting a record for filing with the secretary of state.

. "Effective date" means, in connection with a record filing made by the secretary of state, the date on which the filing becomes effective under RCW 23.95.210.

. "Electronic transmission" means an electronic communication (a) not directly involving the physical transfer of a record in a tangible medium and (b) that may be retained, retrieved, and reviewed by the sender and the recipient thereof, and that may be directly reproduced in a tangible medium by a sender and recipient.

. "Electronically transmitted" means the initiation of an electronic transmission.

. "Execute," "executes," or "executed" means with present intent to authenticate or adopt a record:

.. To sign or adopt a tangible symbol;

.. To attach to or logically associate with the record an electronic symbol, sound, or process; or

.. Filed in compliance with the standards for filing with the office of the secretary of state as prescribed by the secretary of state, with respect to a record to be filed with the secretary of state.

. "Executed by an officer of the corporation," or words of similar import, means that any record executed by such person shall be and is executed by that person under penalties of perjury and in an official and authorized capacity on behalf of the corporation or person making the record submission with the secretary of state and, for the purpose of records filed electronically with the secretary of state, in compliance with the rules adopted by the secretary of state for electronic filing.

. "Foreign corporation" means a corporation not for profit organized under laws other than the laws of this state.

. "Insolvent" means inability of a corporation to pay debts as they become due in the usual course of its affairs.

. "Member" means an individual or entity having membership rights in a corporation in accordance with the provisions of its articles of incorporation or bylaws.

. "Not for profit corporation" or "nonprofit corporation" means a corporation no part of the income of which is distributable to its members, directors or officers.

. "Public benefit not for profit corporation" or "public benefit nonprofit corporation" means a corporation no part of the income of which is distributable to its members, directors, or officers and that holds a current tax exempt status as provided under 26 U.S.C. Sec. 501(c)(3) or is specifically exempted from the requirement to apply for its tax exempt status under 26 U.S.C. Sec. 501(c)(3).

. "Record" means information that is inscribed on a tangible medium or that is stored in an electronic or other medium and is retrievable in perceivable form.

. "Registered office" means the address of the corporation's registered agent.

. "Tangible medium" means a writing, copy of a writing, facsimile, or a physical reproduction, each on paper or on other tangible material.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2080[2020 c 57 § 80]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203101[2015 c 176 § 3101]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%201[2004 c 265 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2313.SL.pdf?cite=2002%20c%2074%20§%204[2002 c 74 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c291.pdf?cite=1989%20c%20291%20§%203[1989 c 291 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%201[1986 c 240 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2072[1982 c 35 § 72]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%202[1967 c 235 § 2]; ]

== 24.03.009 - Notice by electronic transmission—Consent required—When effective. (Effective until January 1, 2022.)
. A notice to be provided by electronic transmission must be electronically transmitted.

. Notice to members and directors in an electronic transmission that otherwise complies with the requirements of this chapter is effective only with respect to members and directors who have consented, in the form of a record, to receive electronically transmitted notices under this chapter.

.. Notice to members and directors includes material that this chapter requires or permits to accompany the notice.

.. A member or director who provides consent, in the form of a record, to receipt of electronically transmitted notices shall designate in the consent the message format accessible to the recipient, and the address, location, or system to which these notices may be electronically transmitted.

.. A member or director who has consented to receipt of electronically transmitted notices may revoke the consent by delivering a revocation to the corporation in the form of a record.

.. The consent of any member or director is revoked if the corporation is unable to electronically transmit two consecutive notices given by the corporation in accordance with the consent, and this inability becomes known to the secretary of the corporation or other person responsible for giving the notice. The inadvertent failure by the corporation to treat this inability as a revocation does not invalidate any meeting or other action.

. Notice to members or directors who have consented to receipt of electronically transmitted notices may be provided notice by posting the notice on an electronic network and delivering to the member or director a separate record of the posting, together with comprehensible instructions regarding how to obtain access to this posting on the electronic network.

. Notice provided in an electronic transmission is effective when it: (a) Is electronically transmitted to an address, location, or system designated by the recipient for that purpose, and is made pursuant to the consent provided by the recipient; or (b) has been posted on an electronic network and a separate record of the posting has been delivered to the recipient together with comprehensible instructions regarding how to obtain access to the posting on the electronic network.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%204[2004 c 265 § 4]; ]

== 24.03.010 - Applicability. (Effective until January 1, 2022.)
The provisions of this chapter relating to domestic corporations shall apply to:

. All corporations organized hereunder; and

. All not for profit corporations heretofore organized under any act hereby repealed, for a purpose or purposes for which a corporation might be organized under this chapter; and

. Any corporation to which this chapter does not otherwise apply, which is authorized to elect, and does elect, in accordance with the provisions of this chapter, as now or hereafter amended, to have the provisions of this chapter apply to it.

The provisions of this chapter relating to foreign corporations shall apply to all foreign not for profit corporations conducting affairs in this state for a purpose or purposes for which a corporation might be organized under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c53.pdf?cite=1971%20ex.s.%20c%2053%20§%201[1971 ex.s. c 53 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%203[1967 c 235 § 3]; ]

== 24.03.015 - Purposes. (Effective until January 1, 2022.)
Corporations may be organized under this chapter for any lawful purpose or purposes, including, without being limited to, any one or more of the following purposes: Charitable; benevolent; eleemosynary; educational; civic; patriotic; political; religious; social; fraternal; literary; cultural; athletic; scientific; agricultural; horticultural; animal husbandry; and professional, commercial, industrial or trade association; but labor unions, cooperative organizations, and organizations subject to any of the provisions of the banking or insurance laws of this state may not be organized under this chapter: PROVIDED, That any not for profit corporation heretofore organized under any act hereby repealed and existing for the purpose of providing health care services as defined in *RCW 48.44.010(1) or 48.46.020(1), as now or hereafter amended, shall continue to be organized under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%202[1986 c 240 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c106.pdf?cite=1983%20c%20106%20§%2022[1983 c 106 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%204[1967 c 235 § 4]; ]

== 24.03.017 - Corporation may elect to have chapter apply to it—Procedure. (Effective until January 1, 2022.)
Any corporation organized under any act of the state of Washington for any one or more of the purposes for which a corporation may be organized under this chapter and for no purpose other than those permitted by this chapter, and to which this chapter does not otherwise apply, may elect to have this chapter and the provisions thereof apply to such corporation. Such corporation may so elect by having a resolution to do so adopted by the governing body of such corporation and by delivering to the secretary of state a statement of election in accordance with this section. Such statement of election shall be executed by the corporation by an officer of the corporation, and shall set forth:

. The name of the corporation;

. The act which created the corporation or pursuant to which it was organized;

. That the governing body of the corporation has elected to have this chapter and the provisions thereof apply to the corporation.

The statement of election shall be delivered to the secretary of state for filing in accordance with Article 2 of chapter 23.95 RCW. Upon the filing of the statement of elective coverage, the provisions of this chapter shall apply to the corporation which thereafter shall be subject to and shall have the benefits of this chapter and the provisions thereof as they exist on the date of filing such statement of election and as they may be amended from time to time thereafter, including, without limiting the generality of the foregoing, the power to amend its charter or articles of incorporation, whether or not created by special act of the legislature, delete provisions therefrom and add provisions thereto in any manner and to any extent it may choose to do from time to time so long as its amended articles shall not be inconsistent with the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203102[2015 c 176 § 3102]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%205[2004 c 265 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2073[1982 c 35 § 73]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c53.pdf?cite=1971%20ex.s.%20c%2053%20§%202[1971 ex.s. c 53 § 2]; ]

== 24.03.020 - Incorporators. (Effective until January 1, 2022.)
One or more persons of the age of eighteen years or more, or a domestic or foreign, profit or nonprofit, corporation, may act as incorporator or incorporators of a corporation by executing and delivering to the secretary of state articles of incorporation for such corporation.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%206[2004 c 265 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%203[1986 c 240 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2074[1982 c 35 § 74]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%205[1967 c 235 § 5]; ]

== 24.03.025 - Articles of incorporation. (Effective until January 1, 2022.)
The articles of incorporation shall set forth:

. The name of the corporation.

. The period of duration, which may be perpetual or for a stated number of years.

. The purpose or purposes for which the corporation is organized.

. Any provisions, not inconsistent with law, which the incorporators elect to set forth in the articles of incorporation for the regulation of the internal affairs of the corporation, including provisions regarding:

.. Distribution of assets on dissolution or final liquidation;

.. The definition, limitation, and regulation of the powers of the corporation, the directors, and the members, if any;

.. Eliminating or limiting the personal liability of a director to the corporation or its members, if any, for monetary damages for conduct as a director: PROVIDED, That such provision shall not eliminate or limit the liability of a director for acts or omissions that involve intentional misconduct by a director or a knowing violation of law by a director, or for any transaction from which the director will personally receive a benefit in money, property, or services to which the director is not legally entitled. No such provision may eliminate or limit the liability of a director for any act or omission occurring before the date when such provision becomes effective; and

.. Any provision which under this title is required or permitted to be set forth in the bylaws.

. The address of its initial registered office, including street and number, and the name of its initial registered agent at such address.

. The number of directors constituting the initial board of directors, and the names and addresses of the persons who are to serve as the initial directors.

. The name and address of each incorporator.

. The name of any person or corporations to whom net assets are to be distributed in the event the corporation is dissolved.

It shall not be necessary to set forth in the articles of incorporation any of the corporate powers enumerated in this chapter.

Unless the articles of incorporation provide that a change in the number of directors shall be made only by amendment to the articles of incorporation, a change in the number of directors made by amendment to the bylaws shall be controlling. In all other cases, whenever a provision of the articles of incorporation is inconsistent with a bylaw, the provision of the articles of incorporation shall be controlling.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c212.pdf?cite=1987%20c%20212%20§%20703[1987 c 212 § 703]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2075[1982 c 35 § 75]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%206[1967 c 235 § 6]; ]

== 24.03.027 - Filing false statements—Penalty. (Effective until January 1, 2022.)
See RCW 43.07.210.

[ ]

== 24.03.030 - Limitations. (Effective until January 1, 2022.)
A corporation subject to this chapter:

. Shall not have or issue shares of stock;

. Shall not make any disbursement of income to its members, directors or officers;

. Shall not loan money or credit to its officers or directors;

. May pay compensation in a reasonable amount to its members, directors or officers for services rendered;

. May confer benefits upon its members in conformity with its purposes; and

. Upon dissolution or final liquidation may make distributions to its members as permitted by this chapter, and no such payment, benefit or distribution shall be deemed to be a dividend or a distribution of income.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%204[1986 c 240 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%207[1967 c 235 § 7]; ]

== 24.03.035 - General powers. (Effective until January 1, 2022.)
Each corporation shall have power:

. To have perpetual succession by its corporate name unless a limited period of duration is stated in its articles of incorporation.

. To sue and be sued, complain and defend, in its corporate name.

. To have a corporate seal which may be altered at pleasure, and to use the same by causing it, or a facsimile thereof, to be impressed or affixed or in any other manner reproduced.

. To purchase, take, receive, lease, take by gift, devise or bequest, or otherwise acquire, own, hold, improve, use and otherwise deal in and with real or personal property, or any interest therein, wherever situated.

. To sell, convey, mortgage, pledge, lease, exchange, transfer and otherwise dispose of all or any part of its property and assets.

. To lend money or credit to its employees other than its officers and directors.

. To purchase, take, receive, subscribe for, or otherwise acquire, own, hold, vote, use, employ, sell, mortgage, lend, pledge, or otherwise dispose of, and otherwise use and deal in and with, shares or other interests in, or obligations of, other domestic or foreign corporations, whether for profit or not for profit, associations, partnerships or individuals, or direct or indirect obligations of the United States, or of any other government, state, territory, governmental district or municipality or of any instrumentality thereof.

. To make contracts and incur liabilities, borrow money at such rates of interest as the corporation may determine, issue its notes, bonds, and other obligations, and secure any of its obligations by mortgage or pledge of all or any of its property, franchises and income.

. To lend money for its corporate purposes, invest and reinvest its funds, and take and hold real and personal property as security for the payment of funds so loaned or invested.

. To conduct its affairs, carry on its operations, and have offices and exercise the powers granted by this chapter in any state, territory, district, or possession of the United States, or in any foreign country.

. To elect or appoint officers and agents of the corporation, and define their duties and fix their compensation.

. To make and alter bylaws, not inconsistent with its articles of incorporation or with the laws of this state, for the administration and regulation of the affairs of the corporation.

. Unless otherwise provided in the articles of incorporation, to make donations for the public welfare or for charitable, scientific or educational purposes; and in time of war to make donations in aid of war activities.

. To indemnify any director or officer or former director or officer or other person in the manner and to the extent provided in RCW 23B.08.500 through 23B.08.600, as now existing or hereafter amended.

. To make guarantees respecting the contracts, securities, or obligations of any person (including, but not limited to, any member, any affiliated or unaffiliated individual, domestic or foreign, profit or not for profit, corporation, partnership, association, joint venture or trust) if such guarantee may reasonably be expected to benefit, directly or indirectly, the guarantor corporation. As to the enforceability of the guarantee, the decision of the board of directors that the guarantee may be reasonably expected to benefit, directly or indirectly, the guarantor corporation shall be binding in respect to the issue of benefit to the guarantor corporation.

. To pay pensions and establish pension plans, pension trusts, and other benefit plans for any or all of its directors, officers, and employees.

. To be a promoter, partner, member, associate or manager of any partnership, joint venture, trust or other enterprise.

. To be a trustee of a charitable trust, to administer a charitable trust and to act as executor in relation to any charitable bequest or devise to the corporation. This subsection shall not be construed as conferring authority to engage in the general business of trusts nor in the business of trust banking.

. To cease its corporate activities and surrender its corporate franchise.

. To have and exercise all powers necessary or convenient to effect any or all of the purposes for which the corporation is organized.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=1991%20c%2072%20§%2042[1991 c 72 § 42]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%205[1986 c 240 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%208[1967 c 235 § 8]; ]

== 24.03.040 - Defense of ultra vires. (Effective until January 1, 2022.)
No act of a corporation and no conveyance or transfer of real or personal property to or by a corporation shall be invalid by reason of the fact that the corporation was without capacity or power to do such act or to make or receive such conveyance or transfer, but such lack of capacity or power may be asserted:

. In a proceeding by a member or a director against the corporation to enjoin the doing or continuation of unauthorized acts, or the transfer of real or personal property by or to the corporation. If the unauthorized acts or transfer sought to be enjoined are being, or are to be, performed pursuant to any contract to which the corporation is a party, the court may, if all of the parties to the contract are parties to the proceeding and if it deems the same to be equitable, set aside and enjoin the performance of such contract, and in so doing may allow to the corporation or the other parties to the contract, as the case may be, compensation for the loss or damage sustained by either of them which may result from the action of the court in setting aside and enjoining the performance of such contract, but anticipated profits to be derived from the performance of the contract shall not be awarded by the court as a loss or damage sustained.

. In a proceeding by the corporation, whether acting directly or through a receiver, trustee, or other legal representative, or through members in a representative suit, against the officers or directors of the corporation for exceeding their authority.

. In a proceeding by the attorney general, as provided in this chapter, to dissolve the corporation, or in a proceeding by the attorney general to enjoin the corporation from performing unauthorized acts, or in any other proceeding by the attorney general.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%209[1967 c 235 § 9]; ]

== 24.03.043 - Indemnification of agents of any corporation authorized. (Effective until January 1, 2022.)
See RCW 23B.17.030.

[ ]

== 24.03.045 - Corporate name. (Effective until January 1, 2022.)
The corporate name must comply with the provisions of Article 3 of chapter 23.95 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203103[2015 c 176 § 3103]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%207[2004 c 265 § 7]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1253-S.SL.pdf?cite=1998%20c%20102%20§%203[1998 c 102 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1235-S2.SL.pdf?cite=1994%20c%20211%20§%201305[1994 c 211 § 1305]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c291.pdf?cite=1989%20c%20291%20§%2010[1989 c 291 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c55.pdf?cite=1987%20c%2055%20§%2039[1987 c 55 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%206[1986 c 240 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2076[1982 c 35 § 76]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2010[1967 c 235 § 10]; ]

== 24.03.046 - Reservation of exclusive right to use a corporate name. (Effective until January 1, 2022.)
A person may reserve the exclusive right to the use of a corporate name in accordance with RCW 23.95.310.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203104[2015 c 176 § 3104]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5471-S.SL.pdf?cite=1993%20c%20356%20§%201[1993 c 356 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2077[1982 c 35 § 77]; ]

== 24.03.047 - Registration of corporate name. (Effective until January 1, 2022.)
Any corporation organized and existing under the laws of any state or territory of the United States may register its corporate name in accordance with RCW 23.95.315.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203105[2015 c 176 § 3105]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1235-S2.SL.pdf?cite=1994%20c%20211%20§%201306[1994 c 211 § 1306]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5471-S.SL.pdf?cite=1993%20c%20356%20§%202[1993 c 356 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c55.pdf?cite=1987%20c%2055%20§%2040[1987 c 55 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%207[1986 c 240 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2078[1982 c 35 § 78]; ]

== 24.03.048 - Renewal of registration of corporate name. (Effective until January 1, 2022.)
A corporation which has in effect a registration of its corporate name may renew such registration in accordance with RCW 23.95.315.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203106[2015 c 176 § 3106]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%208[1986 c 240 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2079[1982 c 35 § 79]; ]

== 24.03.050 - Registered agent. (Effective until January 1, 2022.)
Each corporation shall have and continuously maintain in this state a registered agent in accordance with Article 4 of chapter 23.95 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203107[2015 c 176 § 3107]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=2009%20c%20202%20§%201[2009 c 202 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%208[2004 c 265 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%209[1986 c 240 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2080[1982 c 35 § 80]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c163.pdf?cite=1969%20ex.s.%20c%20163%20§%201[1969 ex.s. c 163 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2011[1967 c 235 § 11]; ]

== 24.03.055 - Change of registered agent. (Effective until January 1, 2022.)
A corporation may change its registered agent by filing in the office of the secretary of state a statement of change in accordance with RCW 23.95.430.

Any registered agent of a corporation may resign as such agent upon filing a notice thereof, in the form of a record, with the secretary of state in accordance with RCW 23.95.445.

A registered agent may change its information on file with the secretary of state in accordance with RCW 23.95.435 or 23.95.440.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203108[2015 c 176 § 3108]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%209[2004 c 265 § 9]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5471-S.SL.pdf?cite=1993%20c%20356%20§%203[1993 c 356 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2010[1986 c 240 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2081[1982 c 35 § 81]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2012[1967 c 235 § 12]; ]

== 24.03.060 - Service of process on corporation. (Effective until January 1, 2022.)
Service of process, notice, or demand required or permitted by law to be served upon the corporation may be made in accordance with RCW 23.95.450.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203109[2015 c 176 § 3109]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2011[1986 c 240 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2082[1982 c 35 § 82]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2013[1967 c 235 § 13]; ]

== 24.03.065 - Members—Member committees. (Effective until January 1, 2022.)
. A corporation may have one or more classes of members or may have no members. If the corporation has one or more classes of members, the designation of the class or classes, the manner of election or appointment and the qualifications and rights of the members of each class must be set forth in the articles of incorporation or the bylaws. Unless otherwise specified in the articles of incorporation or the bylaws, an individual, domestic or foreign profit or nonprofit corporation, a general or limited partnership, an association or other entity may be a member of a corporation. If the corporation has no members, that fact must be set forth in the articles of incorporation or the bylaws. A corporation may issue certificates evidencing membership therein.

. A corporation may have one or more member committees. The creation, makeup, authority, and operating procedures of any member committee or committees must be addressed in the corporation's articles of incorporation or bylaws.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2577.SL.pdf?cite=2004%20c%2098%20§%201[2004 c 98 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2012[1986 c 240 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2014[1967 c 235 § 14]; ]

== 24.03.070 - Bylaws. (Effective until January 1, 2022.)
The initial bylaws of a corporation shall be adopted by its board of directors. The power to alter, amend or repeal the bylaws or adopt new bylaws shall be vested in the board of directors unless otherwise provided in the articles of incorporation or the bylaws. The bylaws may contain any provisions for the regulation and management of the affairs of a corporation not inconsistent with law or the articles of incorporation. The board may adopt emergency bylaws in the manner provided by RCW 23B.02.070.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=1991%20c%2072%20§%2043[1991 c 72 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2013[1986 c 240 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2015[1967 c 235 § 15]; ]

== 24.03.075 - Meetings of members and committees of members. (Effective until January 1, 2022.)
Meetings of members and committees of members may be held at such place, either within or without this state, as stated in or fixed in accordance with the bylaws. In the absence of any such provision, all meetings must be held at the registered office of the corporation in this state.

An annual meeting of the members must be held at the time stated in or fixed in accordance with the bylaws. Failure to hold the annual meeting at the designated time does not work a forfeiture or dissolution of the corporation.

Special meetings of the members may be called by the president or by the board of directors. Special meetings of the members may also be called by other officers or persons or number or proportion of members as provided in the articles of incorporation or the bylaws. In the absence of a provision fixing the number or proportion of members entitled to call a meeting, a special meeting of members may be called by members having one-twentieth of the votes entitled to be cast at the meeting.

Except as otherwise restricted by the articles of incorporation or the bylaws, members and any committee of members of the corporation may participate in a meeting by conference telephone or similar communications equipment so that all persons participating in the meeting can hear each other at the same time. Participation by that method constitutes presence in person at a meeting.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2577.SL.pdf?cite=2004%20c%2098%20§%202[2004 c 98 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2014[1986 c 240 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2016[1967 c 235 § 16]; ]

== 24.03.080 - Notice of members' meetings. (Effective until January 1, 2022.)
 (1) Notice, in the form of a record, in a tangible medium, or in an electronic transmission, stating the place, day, and hour of the annual meeting and, in case of a special meeting, the purpose or purposes for which the meeting is called, shall be delivered not less than ten nor more than fifty days before the date of the meeting, by or at the direction of the president, or the secretary, or the officers or persons calling the meeting, to each member entitled to vote at such meeting. Notice of regular meetings other than annual shall be made by providing each member with the adopted schedule of regular meetings for the ensuing year at any time after the annual meeting and ten days prior to the next succeeding regular meeting and at any time when requested by a member or by such other notice as may be prescribed by the bylaws.

. If notice is provided in a tangible medium, it may be transmitted by: Mail, private carrier, or personal delivery; telegraph or teletype; or telephone, wire, or wireless equipment that transmits a facsimile of the notice. If mailed, such notice shall be deemed to be delivered when deposited in the United States mail addressed to the member at his or her address as it appears on the records of the corporation, with postage thereon prepaid. Other forms of notice in a tangible medium described in this subsection are effective when received.

. If notice is provided in an electronic transmission, it must satisfy the requirements of RCW 24.03.009.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2010[2004 c 265 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c115.pdf?cite=1969%20ex.s.%20c%20115%20§%201[1969 ex.s. c 115 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2017[1967 c 235 § 17]; ]

== 24.03.085 - Voting. (Effective until January 1, 2022.)
. The right of the members, or any class or classes of members, to vote may be limited, enlarged or denied to the extent specified in the articles of incorporation or the bylaws. Unless so limited, enlarged or denied, each member, regardless of class, shall be entitled to one vote on each matter submitted to a vote of members.

. A member may vote in person or, if so authorized by the articles of incorporation or the bylaws, may vote by mail, by electronic transmission, or by proxy in the form of a record executed by the member or a duly authorized attorney-in-fact. No proxy shall be valid after eleven months from the date of its execution, unless otherwise provided in the proxy.

. If specifically permitted by the articles of incorporation or bylaws, whenever proposals or directors or officers are to be elected by members, the vote may be taken by mail or by electronic transmission if the name of each candidate and the text of each proposal to be voted upon are set forth in a record accompanying or contained in the notice of meeting. If the bylaws provide, an election may be conducted by electronic transmission if the corporation has designated an address, location, or system to which the ballot may be electronically transmitted and the ballot is electronically transmitted to the designated address, location, or system, in an executed electronically transmitted record. Members voting by mail or electronic transmission are present for all purposes of quorum, count of votes, and percentages of total voting power present.

. The articles of incorporation or the bylaws may provide that in all elections for directors every member entitled to vote shall have the right to cumulate his [or her] vote and to give one candidate a number of votes equal to his [or her] vote multiplied by the number of directors to be elected, or by distributing such votes on the same principle among any number of such candidates.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2011[2004 c 265 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c115.pdf?cite=1969%20ex.s.%20c%20115%20§%202[1969 ex.s. c 115 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2018[1967 c 235 § 18]; ]

== 24.03.090 - Quorum. (Effective until January 1, 2022.)
The bylaws may provide the number or percentage of members entitled to vote represented in person or by proxy, or the number or percentage of votes represented in person or by proxy, which shall constitute a quorum at a meeting of members. In the absence of any such provision, members holding one-tenth of the votes entitled to be cast represented in person or by proxy shall constitute a quorum. The vote of a majority of the votes entitled to be cast by the members present or represented by proxy at a meeting at which a quorum is present, shall be necessary for the adoption of any matter voted upon by the members, unless a greater proportion is required by this chapter, the articles of incorporation or the bylaws.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2019[1967 c 235 § 19]; ]

== 24.03.095 - Board of directors. (Effective until January 1, 2022.)
The affairs of a corporation shall be managed by a board of directors. Directors need not be residents of this state or members of the corporation unless the articles of incorporation or the bylaws so require. The articles of incorporation or the bylaws may prescribe other qualifications for directors.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2020[1967 c 235 § 20]; ]

== 24.03.100 - Number and election or appointment of directors. (Effective until January 1, 2022.)
The board of directors of a corporation shall consist of one or more individuals. The number of directors shall be fixed by or in the manner provided in the articles of incorporation or the bylaws, except as to the number constituting the initial board of directors, which number shall be fixed by the articles of incorporation. The number of directors may be increased or decreased from time to time by amendment to or in the manner provided in the articles of incorporation or the bylaws, but a decrease shall not have the effect of shortening the term of any incumbent director. In the absence of a bylaw providing for the number of directors, the number shall be the same as that provided for in the articles of incorporation. The names and addresses of the members of the first board of directors shall be stated in the articles of incorporation. Such persons shall hold office until the first annual election of directors or for such other period as may be specified in the articles of incorporation or the bylaws. Thereafter, directors shall be elected or appointed in the manner and for the terms provided in the articles of incorporation or the bylaws. Directors may be divided into classes and the terms of office and manner of election or appointment need not be uniform. Each director shall hold office for the term for which the director is elected or appointed and until the director's successor shall have been selected and qualified.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2015[1986 c 240 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2021[1967 c 235 § 21]; ]

== 24.03.103 - Removal of directors. (Effective until January 1, 2022.)
The bylaws or articles of incorporation may contain a procedure for removal of directors. If the articles of incorporation or bylaws provide for the election of any director or directors by members, then in the absence of any provision regarding removal of directors:

. Any director elected by members may be removed, with or without cause, by two-thirds of the votes cast by members having voting rights with regard to the election of any director, represented in person or by proxy at a meeting of members at which a quorum is present;

. In the case of a corporation having cumulative voting, if less than the entire board is to be removed, no one of the directors may be removed if the votes cast against that director's removal would be sufficient to elect that director if then cumulatively voted at an election of the entire board of directors, or, if there be classes of directors, at an election of the class of directors of which he or she is a part; and

. Whenever the members of any class are entitled to elect one or more directors by the provisions of the articles of incorporation, the provisions of this section shall apply, in respect to the removal of a director or directors so elected, to the vote of the members of that class and not to the vote of the members as a whole.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2016[1986 c 240 § 16]; ]

== 24.03.1031 - Judicial removal of directors. (Effective until January 1, 2022.)
. The superior court of the county where a corporation's principal office, or, if none in this state, its registered office, is located may remove a director of the corporation from office in a proceeding commenced by the corporation if the court finds that (a) the director engaged in fraudulent or dishonest conduct with respect to the corporation, and (b) removal is in the best interest of the corporation.

. The court that removes a director may bar the director from reelection for a period prescribed by the court.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1139.SL.pdf?cite=1999%20c%2032%20§%201[1999 c 32 § 1]; ]

== 24.03.105 - Vacancies. (Effective until January 1, 2022.)
Any vacancy occurring in the board of directors and any directorship to be filled by reason of an increase in the number of directors may be filled by the affirmative vote of a majority of the remaining board of directors even though less than a quorum is present unless the articles of incorporation or the bylaws provide that a vacancy or directorship so created shall be filled in some other manner, in which case such provision shall control. A director elected or appointed, as the case may be, to fill a vacancy shall be elected or appointed for the unexpired term of his or her predecessor in office.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20655[2011 c 336 § 655]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2017[1986 c 240 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2022[1967 c 235 § 22]; ]

== 24.03.110 - Quorum of directors. (Effective until January 1, 2022.)
A majority of the number of directors fixed by, or in the manner provided in the bylaws, or in the absence of a bylaw fixing or providing for the number of directors, then of the number fixed by or in the manner provided in the articles of incorporation, shall constitute a quorum for the transaction of business, unless otherwise provided in the articles of incorporation or the bylaws; but in no event shall a quorum consist of less than one-third of the number of directors so fixed or stated. The act of the majority of the directors present at a meeting at which a quorum is present shall be the act of the board of directors, unless the act of a greater number is required by this chapter, the articles of incorporation or the bylaws.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2018[1986 c 240 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2023[1967 c 235 § 23]; ]

== 24.03.113 - Assent presumed—Procedures for dissent or abstention. (Effective until January 1, 2022.)
A director of a corporation who is present at a meeting of its board of directors at which action on any corporate matter is taken shall be presumed to have assented to the action taken unless the director's dissent or abstention shall be entered in the minutes of the meeting or unless the director shall deliver his or her dissent or abstention to such action to the person acting as the secretary of the meeting before the adjournment thereof, or shall deliver such dissent or abstention to the secretary of the corporation immediately after the adjournment of the meeting which dissent or abstention must be in the form of a record. Such right to dissent or abstain shall not apply to a director who voted in favor of such action.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2012[2004 c 265 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2019[1986 c 240 § 19]; ]

== 24.03.115 - Committees. (Effective until January 1, 2022.)
If the articles of incorporation or the bylaws so provide, the board of directors, by resolution adopted by a majority of the directors in office, may designate and appoint one or more committees each of which shall consist of two or more directors, which committees, to the extent provided in such resolution, in the articles of incorporation or in the bylaws of the corporation, shall have and exercise the authority of the board of directors in the management of the corporation: PROVIDED, That no such committee shall have the authority of the board of directors in reference to amending, altering, or repealing the bylaws; electing, appointing, or removing any member of any such committee or any director or officer of the corporation; amending the articles of incorporation; adopting a plan of merger or adopting a plan of consolidation with another corporation; authorizing the sale, lease, or exchange of all or substantially all of the property and assets of the corporation not in the ordinary course of business; authorizing the voluntary dissolution of the corporation or revoking proceedings therefor; adopting a plan for the distribution of the assets of the corporation; or amending, altering, or repealing any resolution of the board of directors which by its terms provides that it shall not be amended, altered, or repealed by such committee. The designation and appointment of any such committee and the delegation thereto of authority shall not operate to relieve the board of directors, or any individual director of any responsibility imposed upon it or him or her by law.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20656[2011 c 336 § 656]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2020[1986 c 240 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2024[1967 c 235 § 24]; ]

== 24.03.120 - Place and notice of directors' meetings. (Effective until January 1, 2022.)
Meetings of the board of directors, regular or special, may be held either within or without this state.

Regular meetings of the board of directors or of any committee designated by the board of directors may be held with or without notice as prescribed in the bylaws. Special meeting of the board of directors or any committee designated by the board of directors shall be held upon such notice as is prescribed in the bylaws. Attendance of a director or a committee member at a meeting shall constitute a waiver of notice of such meeting, except where a director or a committee member attends a meeting for the express purpose of objecting to the transaction of any business because the meeting is not lawfully called or convened. Neither the business to be transacted at, nor the purpose of, any regular or special meeting of the board of directors or any committee designated by the board of directors need be specified in the notice or waiver of notice of such meeting unless required by the bylaws. If notice of regular or special meetings is provided by electronic transmission, it must satisfy the requirements of RCW 24.03.009.

Except as may be otherwise restricted by the articles of incorporation or bylaws, members of the board of directors or any committee designated by the board of directors may participate in a meeting of such board or committee by means of a conference telephone or similar communications equipment by means of which all persons participating in the meeting can hear each other at the same time and participation by such means shall constitute presence in person at a meeting.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2013[2004 c 265 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2021[1986 c 240 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2025[1967 c 235 § 25]; ]

== 24.03.125 - Officers. (Effective until January 1, 2022.)
The officers of a corporation shall consist of a president, one or more vice presidents, a secretary, and a treasurer, each of whom shall be elected or appointed at such time and in such manner and for such terms as may be prescribed in the articles of incorporation or the bylaws. In the absence of any such provision, all officers shall be elected or appointed annually by the board of directors. If the articles or bylaws so provide, any two or more offices may be held by the same person, except the offices of president and secretary. Such other officers and assistant officers or agents as may be deemed necessary may be elected or appointed by the board of directors or chosen in such other manner as may be prescribed by the articles or bylaws.

The articles of incorporation or the bylaws may provide that any one or more officers of the corporation shall be ex officio members of the board of directors.

The officers of a corporation may be designated by such additional titles as may be provided in the articles of incorporation or the bylaws.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2022[1986 c 240 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2026[1967 c 235 § 26]; ]

== 24.03.127 - Duties of a director. (Effective until January 1, 2022.)
A director shall perform the duties of a director, including the duties as a member of any committee of the board upon which the director may serve, in good faith, in a manner such director believes to be in the best interests of the corporation, and with such care, including reasonable inquiry, as an ordinarily prudent person in a like position would use under similar circumstances.

In performing the duties of a director, a director shall be entitled to rely on information, opinions, reports, or statements, including financial statements and other financial data, in each case prepared or presented by:

. One or more officers or employees of the corporation whom the director believes to be reliable and competent in the matter presented;

. Counsel, public accountants, or other persons as to matters which the director believes to be within such person's professional or expert competence; or

. A committee of the board upon which the director does not serve, duly designated in accordance with a provision in the articles of incorporation or bylaws, as to matters within its designated authority, which committee the director believes to merit confidence; so long as, in any such case, the director acts in good faith, after reasonable inquiry when the need therefor is indicated by the circumstances and without knowledge that would cause such reliance to be unwarranted.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2023[1986 c 240 § 23]; ]

== 24.03.130 - Removal of officers. (Effective until January 1, 2022.)
Any officer elected or appointed may be removed by the persons authorized to elect or appoint such officer whenever in their judgment the best interests of the corporation will be served thereby. The removal of an officer shall be without prejudice to the contract rights, if any, of the officer so removed. Election or appointment of an officer or agent shall not of itself create contract rights.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2027[1967 c 235 § 27]; ]

== 24.03.135 - Required documents in the form of a record—Inspection—Copying. (Effective until January 1, 2022.)
Each corporation shall keep at its registered office, its principal office in this state, or at its secretary's office if in this state, the following documents in the form of a record:

. Current articles and bylaws;

. A list of members, including names, addresses, and classes of membership, if any;

. Correct and adequate statements of accounts and finances;

. A list of officers' and directors' names and addresses;

. Minutes of the proceedings of the members, if any, the board, and any minutes which may be maintained by committees of the board.

The corporate records shall be open at any reasonable time to inspection by any member of more than three months standing or a representative of more than five percent of the membership.

Cost of inspecting or copying shall be borne by such member except for costs for copies of articles or bylaws. Any such member must have a purpose for inspection reasonably related to membership interests. Use or sale of members' lists by such member if obtained by inspection is prohibited.

The superior court of the corporation's or such member's residence may order inspection and may appoint independent inspectors. Such member shall pay inspection costs unless the court orders otherwise.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2014[2004 c 265 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2024[1986 c 240 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2028[1967 c 235 § 28]; ]

== 24.03.140 - Loans to directors and officers prohibited. (Effective until January 1, 2022.)
No loans shall be made by a corporation to its directors or officers. The directors of a corporation who vote for or assent to the making of a loan to a director or officer of the corporation, and any officer or officers participating in the making of such loan, shall be jointly and severally liable to the corporation for the amount of such loan until the repayment thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2029[1967 c 235 § 29]; ]

== 24.03.145 - Filing of articles of incorporation. (Effective until January 1, 2022.)
The articles of incorporation shall be delivered to the secretary of state for filing in accordance with Article 2 of chapter 23.95 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203110[2015 c 176 § 3110]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2313.SL.pdf?cite=2002%20c%2074%20§%207[2002 c 74 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2083[1982 c 35 § 83]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2030[1967 c 235 § 30]; ]

== 24.03.150 - Effect of filing the articles of incorporation. (Effective until January 1, 2022.)
Upon the filing of the articles of incorporation, the corporate existence shall begin, and the certificate of incorporation shall be conclusive evidence that all conditions precedent required to be performed by the incorporators have been complied with and that the corporation has been incorporated under this chapter, except as against the state in a proceeding to cancel or revoke the certificate of incorporation or for involuntary or administrative dissolution.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2025[1986 c 240 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2084[1982 c 35 § 84]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2031[1967 c 235 § 31]; ]

== 24.03.155 - Organization meetings. (Effective until January 1, 2022.)
After the issuance of the certificate of incorporation an organization meeting of the board of directors named in the articles of incorporation shall be held, either within or without this state, at the call of a majority of the directors named in the articles of incorporation, for the purpose of adopting bylaws, electing officers and the transaction of such other business as may come before the meeting. The directors calling the meeting shall give at least three days' notice thereof by mail, facsimile transmission, or electronic transmission to each director so named, which notice shall be in the form of a record and shall state the time and place of the meeting. If notice is provided by electronic transmission, it must satisfy the requirements of RCW 24.03.009. Any action permitted to be taken at the organization meeting of the directors may be taken without a meeting if each director executes a record stating the action so taken.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2015[2004 c 265 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2026[1986 c 240 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2032[1967 c 235 § 32]; ]

== 24.03.160 - Right to amend articles of incorporation. (Effective until January 1, 2022.)
A corporation may amend its articles of incorporation, from time to time, in any and as many respects as may be desired, so long as its articles of incorporation as amended contain only such provisions as are lawful under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2033[1967 c 235 § 33]; ]

== 24.03.165 - Procedure to amend articles of incorporation. (Effective until January 1, 2022.)
Amendments to the articles of incorporation shall be made in the following manner:

. Where there are members having voting rights, with regard to the question, the board of directors shall adopt a resolution setting forth the proposed amendment and directing that it be submitted to a vote at a meeting of members having voting rights, which may be either an annual or a special meeting. Notice in the form of a record setting forth the proposed amendment or a summary of the changes to be effected thereby shall be given to each member entitled to vote at such meeting within the time and in the manner provided in this chapter for the giving of notice of meetings of members. The proposed amendment shall be adopted upon receiving at least two-thirds of the votes which members present at such meeting or represented by proxy are entitled to cast.

. Where there are no members, or no members having voting rights, with regard to the question, an amendment shall be adopted at a meeting of the board of directors upon receiving the vote of a majority of the directors in office.

Any number of amendments may be submitted and voted upon at any one meeting.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2016[2004 c 265 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2027[1986 c 240 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2034[1967 c 235 § 34]; ]

== 24.03.170 - Articles of amendment. (Effective until January 1, 2022.)
The articles of amendment shall be executed by the corporation by an officer of the corporation, and shall set forth:

. The name of the corporation.

. The amendment so adopted.

. Where there are members having voting rights, (a) a statement setting forth the date of the meeting of members at which the amendment was adopted, that a quorum was present at such meeting, and that such amendment received at least two-thirds of the votes which members present at such meeting or represented by proxy were entitled to cast, or (b) a statement that such amendment was adopted by a consent in the form of a record executed by all members entitled to vote with respect thereto.

. Where there are no members, or no members having voting rights, a statement of such fact, the date of the meeting of the board of directors at which the amendment was adopted, and a statement of the fact that such amendment received the vote of a majority of the directors in office.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2017[2004 c 265 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2085[1982 c 35 § 85]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2035[1967 c 235 § 35]; ]

== 24.03.175 - Filing of articles of amendment. (Effective until January 1, 2022.)
The articles of amendment shall be delivered to the secretary of state for filing in accordance with Article 2 of chapter 23.95 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203111[2015 c 176 § 3111]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2313.SL.pdf?cite=2002%20c%2074%20§%208[2002 c 74 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2086[1982 c 35 § 86]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2036[1967 c 235 § 36]; ]

== 24.03.180 - Effect of filing of articles of amendment. (Effective until January 1, 2022.)
Articles of amendment are effective as provided in RCW 23.95.210 and may state a delayed effective date in accordance with RCW 23.95.210.

No amendment shall affect any existing cause of action in favor of or against such corporation, or any pending action to which such corporation shall be a party, or the existing rights of persons other than members; and, in the event the corporate name shall be changed by amendment, no action brought by or against such corporation under its former name shall abate for that reason.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203112[2015 c 176 § 3112]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2028[1986 c 240 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2087[1982 c 35 § 87]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2037[1967 c 235 § 37]; ]

== 24.03.183 - Restated articles of incorporation. (Effective until January 1, 2022.)
A domestic corporation may at any time restate its articles of incorporation by a resolution adopted by the board of directors. A corporation may amend and restate in one resolution, but may not present the amendments and restatement for filing by the secretary in a single record. Separate articles of amendment, under RCW 24.03.165 and articles of restatement, under this section, must be presented notwithstanding the corporation's adoption of a single resolution of amendment and restatement.

Upon the adoption of the resolution, restated articles of incorporation shall be executed by the corporation by one of its officers. The restated articles shall set forth all of the operative provisions of the articles of incorporation together with a statement that the restated articles of incorporation correctly set forth without change the provisions of the articles of incorporation as amended and that the restated articles of incorporation supersede the original articles of incorporation and all amendments thereto.

The restated articles of incorporation shall be delivered to the secretary of state for filing in accordance with Article 2 of chapter 23.95 RCW.

Upon the filing of the restated articles of incorporation by the secretary of state, the restated articles of incorporation shall become effective and shall supersede the original articles of incorporation and all amendments thereto.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203113[2015 c 176 § 3113]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2018[2004 c 265 § 18]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2313.SL.pdf?cite=2002%20c%2074%20§%209[2002 c 74 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2029[1986 c 240 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2088[1982 c 35 § 88]; ]

== 24.03.185 - Procedure for merger. (Effective until January 1, 2022.)
Any two or more domestic corporations subject to this chapter may merge into one of such corporations pursuant to a plan of merger approved in the manner provided in this chapter.

Each corporation shall adopt a plan of merger setting forth:

. The names of the corporations proposing to merge, and the name of the corporation into which they propose to merge, which is hereinafter designated as the surviving corporation.

. The terms and conditions of the proposed merger.

. A statement of any changes in the articles of incorporation of the surviving corporation to be effected by such merger.

. Such other provisions with respect to the proposed merger as are deemed necessary or desirable.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2030[1986 c 240 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2038[1967 c 235 § 38]; ]

== 24.03.190 - Procedure for consolidation. (Effective until January 1, 2022.)
Any two or more domestic corporations subject to this chapter may consolidate into a new corporation pursuant to a plan of consolidation approved in the manner provided in this chapter.

Each corporation shall adopt a plan of consolidation setting forth:

. The names of the corporations proposing to consolidate, and the name of the new corporation into which they propose to consolidate, which is hereinafter designated as the new corporation.

. The terms and conditions of the proposed consolidation.

. With respect to the new corporation, all of the statements required to be set forth in articles of incorporation for corporations organized under this chapter.

. Such other provisions with respect to the proposed consolidation as are deemed necessary or desirable.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2031[1986 c 240 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2039[1967 c 235 § 39]; ]

== 24.03.195 - Approval of merger or consolidation. (Effective until January 1, 2022.)
A plan of merger or consolidation shall be adopted in the following manner:

. Where the members of any merging or consolidating corporation have voting rights with regard to the question, the board of directors of such corporation shall adopt a resolution approving the proposed plan and directing that it be submitted to a vote at a meeting of members having voting rights, which may be either an annual or a special meeting. Notice in the form of a record setting forth the proposed plan or a summary thereof shall be given to each member entitled to vote at such meeting within the time and in the manner provided in this chapter for the giving of notice of meetings of members. The proposed plan shall be adopted upon receiving at least two-thirds of the votes which members present at each such meeting or represented by proxy are entitled to cast.

. Where any merging or consolidating corporation has no members, or no members having voting rights with regard to the question, a plan of merger or consolidation shall be adopted at a meeting of the board of directors of such corporation upon receiving the vote of a majority of the directors in office.

After such approval, and at any time prior to the filing of the articles of merger or consolidation, the merger or consolidation may be abandoned pursuant to provisions therefor, if any, set forth in the plan of merger or consolidation.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2019[2004 c 265 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2032[1986 c 240 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2040[1967 c 235 § 40]; ]

== 24.03.200 - Articles of merger or consolidation. (Effective until January 1, 2022.)
. Upon such approval, articles of merger or articles of consolidation shall be executed by each corporation by an officer of each corporation, and shall set forth:

.. The plan of merger or the plan of consolidation;

.. Where the members of any merging or consolidating corporation have voting rights, then as to each such corporation (i) a statement setting forth the date of the meeting of members at which the plan was adopted, that a quorum was present at such meeting, and that such plan received at least two-thirds of the votes which members present at such meeting or represented by proxy were entitled to cast, or (ii) a statement that such amendment was adopted by a consent in the form of a record executed by all members entitled to vote with respect thereto;

.. Where any merging or consolidating corporation has no members, or no members having voting rights, then as to each such corporation a statement of such fact, the date of the meeting of the board of directors at which the plan was adopted and a statement of the fact that such plan received the vote of a majority of the directors in office.

. The articles of merger or articles of consolidation shall be delivered to the secretary of state for filing in accordance with Article 2 of chapter 23.95 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203114[2015 c 176 § 3114]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2020[2004 c 265 § 20]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2313.SL.pdf?cite=2002%20c%2074%20§%2010[2002 c 74 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2033[1986 c 240 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2089[1982 c 35 § 89]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2041[1967 c 235 § 41]; ]

== 24.03.205 - Merger or consolidation—When effective. (Effective until January 1, 2022.)
A merger or consolidation shall become effective upon the filing of the articles of merger or articles of consolidation with the secretary of state as provided in RCW 23.95.210, and may state a delayed effective date as provided in RCW 23.95.210.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203115[2015 c 176 § 3115]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2034[1986 c 240 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2090[1982 c 35 § 90]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2042[1967 c 235 § 42]; ]

== 24.03.207 - Merger or consolidation of domestic and foreign corporation. (Effective until January 1, 2022.)
One or more foreign corporations and one or more domestic corporations may be merged or consolidated in the following manner, if such merger or consolidation is permitted by the laws of the state under which each such foreign corporation is organized:

. Each domestic corporation shall comply with the provisions of this title with respect to the merger or consolidation as the case may be, of domestic corporations and each foreign corporation shall comply with the applicable provisions of the laws of the state under which it is organized.

. If the surviving or new corporation in a merger or consolidation is to be governed by the laws of any state other than this state, it shall comply with the provisions of this title and Article 5 of chapter 23.95 RCW with respect to foreign corporations if it is to transact business in this state, and in every case it shall file with the secretary of state of this state an agreement that it may be served with process in accordance with RCW 23.95.450 in any proceeding for the enforcement of any obligation of any domestic corporation which is a party to the merger or consolidation and in any proceeding for the enforcement of the rights, if any, of a member of any such domestic corporation against the surviving or new corporation.

The effect of the merger or consolidation shall be the same as in the case of the merger or consolidation of domestic corporations, if the surviving or new corporation is to be governed by the laws of this state. If the surviving or new corporation is to be governed by the laws of any state other than this state, the effect of the merger or consolidation shall be the same as in the case of the merger or consolidation of domestic corporations except as the laws of the other state provide otherwise.

. At any time prior to the effective date of the articles of merger or consolidation, the merger or consolidation may be abandoned pursuant to provision therefor, if any, set forth in the plan of merger or consolidation. In the event the merger or consolidation is abandoned, the parties thereto shall execute a notice of abandonment executed by an officer for each corporation executing the notice, which must be in the form of a record, and deliver the notice to the secretary of state for filing in accordance with Article 2 of chapter 23.95 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203116[2015 c 176 § 3116]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2021[2004 c 265 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2035[1986 c 240 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2091[1982 c 35 § 91]; ]

== 24.03.210 - Effect of merger or consolidation. (Effective until January 1, 2022.)
When such merger or consolidation has been affected:

. The several corporations parties to the plan of merger or consolidation shall be a single corporation, which, in the case of a merger, shall be that corporation designated in the plan of merger as the surviving corporation, and, in the case of a consolidation, shall be the new corporation provided for in the plan of consolidation.

. The separate existence of all corporations parties to the plan of merger or consolidation, except the surviving or new corporation, shall cease.

. Such surviving or new corporation shall have all the rights, privileges, immunities and powers and shall be subject to all the duties and liabilities of a corporation organized under this chapter.

. Such surviving or new corporation shall thereupon and thereafter possess all the rights, privileges, immunities, and franchises, as well of a public as of a private nature, of each of the merging or consolidating corporations; and all property, real, personal and mixed, and all debts due on whatever account, and all other choses in action, and all and every other interest, of or belonging to or due to each of the corporations so merged or consolidated, shall be taken and deemed to be transferred to and vested in such single corporation without further act or deed; and the title to any real estate, or any interest therein, vested in any of such corporations shall not revert or be in any way impaired by reason of such merger or consolidation.

. Such surviving or new corporation shall thenceforth be responsible and liable for all the liabilities and obligations of each of the corporations so merged or consolidated; and any claim existing or action or proceeding pending by or against any of such corporations may be prosecuted as if such merger or consolidation had not taken place, or such surviving or new corporation may be substituted in its place. Neither the rights of creditors nor any liens upon the property of any such corporation shall be impaired by such merger or consolidation.

. In the case of a merger, the articles of incorporation of the surviving corporation shall be deemed to be amended to the extent, if any, that changes in its articles of incorporation are stated in the plan of merger; and, in the case of a consolidation, the statements set forth in the articles of consolidation and which are required or permitted to be set forth in the articles of incorporation of corporations organized under this chapter shall be deemed to be the articles of incorporation of the new corporation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2043[1967 c 235 § 43]; ]

== 24.03.215 - Sale, lease, exchange, or other disposition of assets not in the ordinary course of business. (Effective until January 1, 2022.)
A sale, lease, exchange, or other disposition of all, or substantially all, the property and assets of a corporation, if not in the ordinary course of business, may be made upon such terms and conditions and for such consideration, which may consist in whole or in part of money or property, real or personal, including shares of any corporation for profit, domestic or foreign, as may be authorized in the following manner:

. Where there are members having voting rights with regard to the question, the board of directors shall adopt a resolution recommending such sale, lease, exchange, or other disposition and directing that it be submitted to a vote at a meeting of members having voting rights, which may be either an annual or a special meeting. Notice in the form of a record stating that the purpose, or one of the purposes, of such meeting is to consider the sale, lease, exchange, or other disposition of all, or substantially all, the property and assets of the corporation shall be given to each member entitled to vote at such meeting, within the time and in the manner provided by this chapter for the giving of notice of meetings of members. At such meeting the members may authorize such sale, lease, exchange, or other disposition and may fix, or may authorize the board of directors to fix, any or all of the terms and conditions thereof and the consideration to be received by the corporation therefor. Such authorization shall require at least two-thirds of the votes which members present at such meeting or represented by proxy are entitled to cast. After such authorization by a vote of members, the board of directors, nevertheless, in its discretion, may abandon such sale, lease, exchange, or other disposition of assets, subject to the rights of third parties under any contracts relating thereto, without further action or approval by members.

. Where there are no members, or no members having voting rights with regard to the question, a sale, lease, exchange, or other disposition of all, or substantially all, the property and assets of a corporation shall be authorized upon receiving the vote of a majority of the directors in office.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2022[2004 c 265 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2036[1986 c 240 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2044[1967 c 235 § 44]; ]

== 24.03.217 - Sale, lease, exchange, or disposition of assets in course of business—Mortgage and pledge of assets. (Effective until January 1, 2022.)
The sale, lease, exchange or other disposition of all, or substantially all, the property and assets of a corporation in the usual and regular course of its business and the mortgage or pledge of any or all property and assets of a corporation whether or not in the usual course of business may be made upon such terms and conditions and for such consideration, which may consist in whole or in part of money or property, real or personal, including shares, obligations, or other securities of any other corporation, domestic or foreign, as shall be authorized by its board of directors. In any such case, no other authorization or consent of any member shall be required.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2037[1986 c 240 § 37]; ]

== 24.03.220 - Voluntary dissolution. (Effective until January 1, 2022.)
A corporation may dissolve and wind up its affairs in the following manner:

. Where there are members having voting rights with regard to the question, the board of directors shall adopt a resolution recommending that the corporation be dissolved, and directing that the question of such dissolution be submitted to a vote at a meeting of members having such voting rights, which may be either an annual or a special meeting. Notice in the form of a record stating that the purpose, or one of the purposes, of such meeting is to consider the advisability of dissolving the corporation, shall be given to each member entitled to vote at such meeting, within the time and in the manner provided in this chapter for the giving of notice of meetings of members. A resolution to dissolve the corporation shall be adopted upon receiving at least two-thirds of the votes which members present at such meeting or represented by proxy are entitled to cast.

. Where there are no members, or no members having voting rights with regard to the question, the dissolution of the corporation shall be authorized at a meeting of the board of directors upon the adoption of a resolution to dissolve by the vote of a majority of the directors in office.

Upon the adoption of such resolution by the members, or by the board of directors where there are no members or no members having voting rights, the corporation shall cease to conduct its affairs except in so far as may be necessary for the winding up thereof, shall immediately cause a notice of the proposed dissolution to be mailed to each known creditor of the corporation, to the attorney general with respect to assets subject to RCW 24.03.225(3), and to the department of revenue, and shall proceed to collect its assets and apply and distribute them as provided in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2023[2004 c 265 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2038[1986 c 240 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2092[1982 c 35 § 92]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2045[1967 c 235 § 45]; ]

== 24.03.225 - Distribution of assets. (Effective until January 1, 2022.)
The assets of a corporation in the process of dissolution shall be applied and distributed as follows:

. All liabilities and obligations of the corporation shall be paid, satisfied and discharged, or adequate provision shall be made therefor;

. Assets held by the corporation upon condition requiring return, transfer or conveyance, which condition occurs by reason of the dissolution, shall be returned, transferred or conveyed in accordance with such requirements;

. Assets received and held by the corporation subject to limitations permitting their use only for charitable, religious, eleemosynary, benevolent, educational or similar purposes, but not held upon a condition requiring return, transfer or conveyance by reason of the dissolution, shall be transferred or conveyed to one or more domestic or foreign corporations, societies or organizations engaged in activities substantially similar to those of the dissolving corporation, pursuant to a plan of distribution adopted as provided in this chapter;

. Other assets, if any, shall be distributed in accordance with the provisions of the articles of incorporation or the bylaws to the extent that the articles of incorporation or bylaws determine the distributive rights of members, or any class or classes of members, or provide for distribution to others;

. Any remaining assets may be distributed to such persons, societies, organizations or domestic or foreign corporations, whether for profit or not for profit, as may be specified in a plan of distribution adopted as provided in this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2046[1967 c 235 § 46]; ]

== 24.03.230 - Plan of distribution. (Effective until January 1, 2022.)
A plan providing for the distribution of assets, not inconsistent with the provisions of this chapter, may be adopted by a corporation in the process of dissolution and shall be adopted by a corporation for the purpose of authorizing any transfer or conveyance of assets for which this chapter requires a plan of distribution, in the following manner:

. Where there are members having voting rights, the board of directors shall adopt a resolution recommending a plan of distribution and directing the submission thereof to a vote at a meeting of members having voting rights, which may be either an annual or a special meeting. Notice in the form of a record setting forth the proposed plan of distribution or a summary thereof shall be given to each member entitled to vote at such meeting, within the time and in the manner provided in this chapter for the giving of notice of meetings of members. Such plan of distribution shall be adopted upon receiving at least two-thirds of the votes which members present at such meeting or represented by proxy are entitled to cast.

. Where there are no members, or no members having voting rights, a plan of distribution shall be adopted at a meeting of the board of directors upon receiving a vote of a majority of the directors in office.

If the plan of distribution includes assets received and held by the corporation subject to limitations described in subsection (3) of RCW 24.03.225, notice of the adoption of the proposed plan shall be submitted to the attorney general by registered or certified mail directed to him or her at his or her office in Olympia, at least twenty days prior to the meeting at which the proposed plan is to be adopted. No plan for the distribution of such assets may be adopted without the approval of the attorney general, or the approval of a court of competent jurisdiction in a proceeding to which the attorney general is made a party. In the event that an objection is not filed within twenty days after the date of mailing, his or her approval shall be deemed to have been given.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20657[2011 c 336 § 657]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2024[2004 c 265 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c115.pdf?cite=1969%20ex.s.%20c%20115%20§%203[1969 ex.s. c 115 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2047[1967 c 235 § 47]; ]

== 24.03.235 - Revocation of voluntary dissolution proceedings. (Effective until January 1, 2022.)
A corporation may, at any time prior to the issuance of a certificate of dissolution by the secretary of state, revoke the action theretofore taken to dissolve the corporation, in the following manner:

. Where there are members having voting rights, the board of directors shall adopt a resolution recommending that the voluntary dissolution proceedings be revoked, and directing that the question of such revocation be submitted to a vote at a meeting of members having voting rights, which may be either an annual or a special meeting. Notice in the form of a record stating that the purpose, or one of the purposes, of such meeting is to consider the advisability of revoking the voluntary dissolution proceedings, shall be given to each member entitled to vote at such meeting, within the time and in the manner provided in this chapter for the giving of notice of meetings of members. A resolution to revoke the voluntary dissolution proceedings shall be adopted upon receiving at least two-thirds of the votes which members present at such meeting or represented by proxy are entitled to cast.

. Where there are no members, or no members having voting rights, a resolution to revoke the voluntary dissolution proceedings shall be adopted at a meeting of the board of directors upon receiving the vote of a majority of the directors in office.

Upon the adoption of such resolution by the members, or by the board of directors where there are no members or no members having voting rights, the corporation may thereupon again conduct its affairs.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2025[2004 c 265 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2048[1967 c 235 § 48]; ]

== 24.03.240 - Articles of dissolution. (Effective until January 1, 2022.)
If voluntary dissolution proceedings have not been revoked, then when all debts, liabilities and obligations of the corporation shall have been paid and discharged, or adequate provision shall have been made therefor, and all of the remaining property and assets of the corporation shall have been transferred, conveyed or distributed in accordance with the provisions of this chapter, articles of dissolution shall be executed by the corporation by an officer of the corporation and shall set forth:

. The name of the corporation.

. Where there are members having voting rights, (a) a statement setting forth the date of the meeting of members at which the resolution to dissolve was adopted, that a quorum was present at such meeting, and that such resolution received at least two-thirds of the votes which members present at such meeting or represented by proxy were entitled to cast, or (b) a statement that such resolution was adopted by a consent in the form of a record executed by all members entitled to vote with respect thereto.

. Where there are no members, or no members having voting rights, a statement of such fact, the date of the meeting of the board of directors at which the resolution to dissolve was adopted and a statement of the fact that such resolution received the vote of a majority of the directors in office.

. That all debts, obligations, and liabilities of the corporation have been paid and discharged or that adequate provision has been made therefor.

. A copy of a revenue clearance certificate issued pursuant to chapter 82.32 RCW.

. That all the remaining property and assets of the corporation have been transferred, conveyed or distributed in accordance with the provisions of this chapter.

. That there are no suits pending against the corporation in any court, or that adequate provision has been made for the satisfaction of any judgment, order or decree which may be entered against it in any pending suit.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2026[2004 c 265 § 26]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5471-S.SL.pdf?cite=1993%20c%20356%20§%204[1993 c 356 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2093[1982 c 35 § 93]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2049[1967 c 235 § 49]; ]

== 24.03.245 - Filing of articles of dissolution. (Effective until January 1, 2022.)
Articles of dissolution shall be delivered to the secretary of state for filing in accordance with Article 2 of chapter 23.95 RCW. Upon the filing of such articles of dissolution the existence of the corporation shall cease, except for the purpose of suits, other proceedings and appropriate corporate action by members, directors, and officers as provided in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203117[2015 c 176 § 3117]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2313.SL.pdf?cite=2002%20c%2074%20§%2011[2002 c 74 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2094[1982 c 35 § 94]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2050[1967 c 235 § 50]; ]

== 24.03.250 - Involuntary dissolution. (Effective until January 1, 2022.)
A corporation may be dissolved involuntarily by a decree of the superior court in an action filed by the attorney general when it is established that:

. The corporation procured its articles of incorporation through fraud; or

. The corporation has continued to exceed or abuse the authority conferred upon it by law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c163.pdf?cite=1969%20ex.s.%20c%20163%20§%202[1969 ex.s. c 163 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2051[1967 c 235 § 51]; ]

== 24.03.255 - Notification to attorney general. (Effective until January 1, 2022.)
The secretary of state shall certify, from time to time, the names of all corporations which have given cause for dissolution as provided in RCW 24.03.250, together with the facts pertinent thereto. Whenever the secretary of state shall certify the name of a corporation to the attorney general as having given any cause for dissolution, the secretary of state shall concurrently mail to the corporation at its registered office a notice that such certification has been made. Upon the receipt of such certification, the attorney general shall file an action in the name of the state against such corporation for its dissolution.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2095[1982 c 35 § 95]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c163.pdf?cite=1969%20ex.s.%20c%20163%20§%203[1969 ex.s. c 163 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2052[1967 c 235 § 52]; ]

== 24.03.260 - Venue and process. (Effective until January 1, 2022.)
Every action for the involuntary dissolution of a corporation shall be commenced by the attorney general either in the superior court of the county in which the registered office of the corporation is situated, or in the superior court of Thurston county. Summons shall issue and be served as in other civil actions. If process is returned not found, the attorney general shall cause publication to be made as in other civil cases in some newspaper published in the county where the registered office of the corporation is situated, containing a notice of the pendency of such action, the title of the court, the title of the action, and the date on or after which default may be entered. The attorney general may include in one notice the names of any number of corporations against which actions are then pending in the same court. The attorney general shall cause a copy of such notice to be mailed to the corporation at its registered office within ten days after the first publication thereof. The certificate of the attorney general of the mailing of such notice shall be prima facie evidence thereof. Such notice shall be published at least once each week for two successive weeks, and the first publication thereof may begin at any time after the summons has been returned. Unless a corporation shall have been served with summons, no default shall be taken against it earlier than thirty days after the first publication of such notice.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2053[1967 c 235 § 53]; ]

== 24.03.266 - Dissolution of a nonprofit corporation—Superior courts. (Effective until January 1, 2022.)
Superior courts may dissolve a nonprofit corporation:

. Except as provided in the articles of incorporation or bylaws, in a proceeding by fifty members or members holding at least five percent of the voting power, whichever is less, by one or more directors, or by the attorney general if it is established that:

.. The directors are deadlocked in the management of the corporate affairs, the members, if any, are unable to break the deadlock, and irreparable injury to the corporation or its mission is threatened or being suffered because of the deadlock;

.. The directors or those in control of the corporation have acted, are acting, or will act in a manner that is illegal, oppressive, or fraudulent;

.. The members are deadlocked in voting power and have failed, for a period that includes at least two consecutive annual meeting dates, to elect successors to directors whose terms have, or otherwise would have, expired;

.. The corporate assets are being misapplied or wasted; or

.. The corporation has insufficient assets to continue its activities and it is no longer able to assemble a quorum of directors or members;

. In a proceeding by a creditor, if it is established that:

.. The creditor's claim has been reduced to judgment, the execution on the judgment returned unsatisfied, and the corporation is insolvent; or

.. The corporation has admitted in a record that the creditor's claim is due and owing and the corporation is insolvent; or

. In a proceeding by the corporation to have its voluntary dissolution continued under court supervision.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/3046-S.SL.pdf?cite=2010%20c%20212%20§%201[2010 c 212 § 1]; ]

== 24.03.271 - Dissolution of a nonprofit corporation—Venue—Proceedings—Court's authority—Distribution of assets. (Effective until January 1, 2022.)
. Venue for a proceeding brought by the attorney general to dissolve a corporation pursuant to RCW 24.03.266 lies in the court specified in RCW 24.03.260. Venue for a proceeding brought by any other party named in RCW 24.03.266 lies in the county where a corporation's principal office (or, if none in this state, its registered office) is or was last located.

. It is not necessary to make directors or members parties to a proceeding to dissolve a nonprofit corporation unless relief is sought against them individually.

. A court in a proceeding brought to dissolve a nonprofit corporation may issue injunctions, appoint a general or custodial receiver with all powers and duties the court directs, take other action required to preserve the corporate assets wherever located, and carry on the activities of the corporation until a full hearing can be held.

. A court in a judicial proceeding brought to dissolve a nonprofit corporation may appoint one or more general receivers to wind up and liquidate, or one or more custodial receivers to manage, the affairs of the corporation. The court shall hold a hearing, after giving notice to all parties to the proceeding and any interested persons designated by the court, before appointing a general or custodial receiver. The court appointing a general or custodial receiver has exclusive jurisdiction over the corporation and all of its property wherever located.

. The court may require the general or custodial receiver to post bond, with or without sureties, in an amount the court directs.

. The court shall describe the powers and duties of the general or custodial receiver in its appointing order, which may be amended from time to time. Among other powers:

.. The general receiver:

... May dispose of all or any part of the assets of the nonprofit corporation wherever located, at a public or private sale, if authorized by the court; and

... May sue and defend in his or her own name as general receiver of the corporation in all courts of this state;

.. The custodial receiver may exercise all of the powers of the corporation, through or in place of its board of directors, to the extent necessary to manage the affairs of the corporation consistent with its mission and in the best interests of the corporation, and its creditors.

. During a general receivership, the court may redesignate the general receiver a custodial receiver, and during a custodial receivership may redesignate the custodial receiver a general receiver, if doing so is consistent with the mission of the nonprofit corporation and in the best interests of the corporation and its creditors.

. The court from time to time during the general or custodial receivership may order compensation paid and expense disbursements or reimbursements made to the general or custodial receiver and counsel from the assets of the nonprofit corporation or proceeds from the sale of the assets.

. The assets of the corporation or the proceeds resulting from the sale, conveyance, or other disposition thereof shall be applied and distributed as follows:

.. All costs and expenses of the court proceedings and all liabilities and obligations of the corporation shall be paid, satisfied, and discharged, or adequate provision shall be made therefor;

.. Assets held by the corporation upon condition requiring return, transfer, or conveyance, which condition occurs by reason of the dissolution or liquidation, shall be returned, transferred, or conveyed in accordance with such requirements;

.. Assets received and held by the corporation subject to limitations permitting their use only for charitable, religious, eleemosynary, benevolent, educational, or similar purposes, but not held upon a condition requiring return, transfer, or conveyance by reason of the dissolution or liquidation, shall be transferred or conveyed to one or more domestic or foreign corporations, societies, or organizations engaged in activities substantially similar to those of the dissolving or liquidating corporation as the court may direct;

.. Other assets, if any, shall be distributed in accordance with the provisions of the articles of incorporation or the bylaws to the extent that the articles of incorporation or bylaws determine the distributive rights of members, or any class or classes of members, or provide for distribution to others;

.. Any remaining assets may be distributed to such persons, societies, organizations, or domestic or foreign corporations, whether for profit or not for profit, specified in the plan of distribution adopted as provided in this chapter, or where no plan of distribution has been adopted, as the court may direct.

. Subsections (4) through (8) of this section do not apply to a church or its integrated auxiliaries.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/3046-S.SL.pdf?cite=2010%20c%20212%20§%202[2010 c 212 § 2]; ]

== 24.03.276 - Dissolution of a nonprofit corporation—Decree. (Effective until January 1, 2022.)
. If after a hearing the court determines that one or more grounds for judicial dissolution described in RCW 24.03.266 exist, it may enter a decree dissolving the nonprofit corporation and specifying the effective date of the dissolution, and the clerk of the court shall deliver a certified copy of the decree to the secretary of state, who shall file it.

. After entering the decree of dissolution, the court shall direct the winding up and liquidation of the nonprofit corporation's affairs in accordance with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/3046-S.SL.pdf?cite=2010%20c%20212%20§%203[2010 c 212 § 3]; ]

== 24.03.295 - Filing of decree of dissolution. (Effective until January 1, 2022.)
In case the court shall enter a decree dissolving a corporation, it shall be the duty of the clerk of such court to cause a certified copy of the decree to be filed with the secretary of state. No fee shall be charged by the clerk for issuance or by the secretary of state for the filing thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2040[1986 c 240 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2060[1967 c 235 § 60]; ]

== 24.03.300 - Survival of remedy after dissolution—Extension of duration of corporation. (Effective until January 1, 2022.)
The dissolution of a corporation either (1) by the filing and issuance of a certificate of dissolution, voluntary or administrative, by the secretary of state, or (2) by a decree of court when the court has not liquidated the assets and affairs of the corporation as provided in this chapter, or (3) by expiration of its period of duration, shall not take away or impair any remedy available to or against such corporation, its directors, officers, or members, for any right or claim existing, or any liability incurred, prior to such dissolution if action or other proceeding thereon is commenced within two years after the date of such dissolution. Any such action or proceeding by or against the corporation may be prosecuted or defended by the corporation in its corporate name. The members, directors and officers shall have power to take such corporate or other action as shall be appropriate to protect such remedy, right or claim. If such corporation was dissolved by the expiration of its period of duration, such corporation may amend its articles of incorporation at any time during such period of two years after expiration so as to extend its period of duration. If, during the period of dissolution, another person or corporation has reserved or adopted a corporate name which is identical to or deceptively similar to the dissolved corporation's name, the corporation extending its period of duration shall be required to adopt another name consistent with the requirements of Article 3 of chapter 23.95 RCW and to amend its articles of incorporation accordingly. The corporation shall also pay to the state all fees and penalties which would otherwise have been due if the corporate charter had not expired, plus a reinstatement fee as established by the secretary of state under RCW 23.95.260.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203118[2015 c 176 § 3118]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2041[1986 c 240 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2096[1982 c 35 § 96]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2061[1967 c 235 § 61]; ]

== 24.03.302 - Administrative dissolution—Reinstatement—Survival of actions. (Effective until January 1, 2022.)
A corporation shall be administratively dissolved by the secretary of state under the circumstances and procedures provided in Article 6 of chapter 23.95 RCW.

A corporation which has been administratively dissolved under RCW 23.95.610 may apply to the secretary of state for reinstatement in accordance with RCW 23.95.615.

When a corporation has been administratively dissolved under RCW 23.95.610, remedies available to or against it shall survive in the manner provided in RCW 24.03.300 and the directors of the corporation shall hold the title to the property of the corporation as trustees for the benefit of its creditors and members.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203119[2015 c 176 § 3119]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6230-S.SL.pdf?cite=1994%20c%20287%20§%208[1994 c 287 § 8]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5471-S.SL.pdf?cite=1993%20c%20356%20§%205[1993 c 356 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c117.pdf?cite=1987%20c%20117%20§%203[1987 c 117 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2042[1986 c 240 § 42]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2097[1982 c 35 § 97]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c128.pdf?cite=1971%20ex.s.%20c%20128%20§%201[1971 ex.s. c 128 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c163.pdf?cite=1969%20ex.s.%20c%20163%20§%209[1969 ex.s. c 163 § 9]; ]

== 24.03.305 - Registration of foreign corporation—Authority to conduct affairs. (Effective until January 1, 2022.)
. A foreign corporation shall not conduct affairs in this state until it registers with the secretary of state in accordance with Article 5 of chapter 23.95 RCW.

. A nonexhaustive list of activities that do not constitute conducting affairs in this state is provided in RCW 23.95.520.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203120[2015 c 176 § 3120]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1497-S.SL.pdf?cite=1993%20c%20181%20§%2012[1993 c 181 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2043[1986 c 240 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2062[1967 c 235 § 62]; ]

== 24.03.310 - Powers of foreign corporation—Effect of registration—Governing law. (Effective until January 1, 2022.)
A foreign corporation that registers to conduct affairs in this state is subject to RCW 23.95.500 relating to the effect of registration and the governing law for registered foreign corporations.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203121[2015 c 176 § 3121]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2063[1967 c 235 § 63]; ]

== 24.03.315 - Corporate name of foreign corporation—Fictitious name. (Effective until January 1, 2022.)
The corporate name of a foreign corporation registered in this state must comply with the provisions of RCW 23.95.525 and Article 3 of chapter 23.95 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203122[2015 c 176 § 3122]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%2098[1982 c 35 § 98]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2064[1967 c 235 § 64]; ]

== 24.03.325 - Foreign registration statement. (Effective until January 1, 2022.)
A foreign corporation may register to conduct affairs in this state by delivering to the secretary of state for filing a foreign registration statement in accordance with RCW 23.95.510. The statement must be executed by the corporation by one of its officers.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203123[2015 c 176 § 3123]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2313.SL.pdf?cite=2002%20c%2074%20§%2012[2002 c 74 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2045[1986 c 240 § 45]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2066[1967 c 235 § 66]; ]

== 24.03.332 - Certificate of authority as insurance company—Filing of records. (Effective until January 1, 2022.)
For those corporations that have a certificate of authority, are applying for, or intend to apply for a certificate of authority from the insurance commissioner as an insurance company under chapter 48.05 RCW, whenever under this chapter corporate records are required to be filed with the secretary of state, the records shall be filed with the insurance commissioner rather than the secretary of state.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2028[2004 c 265 § 28]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1065-S2.SL.pdf?cite=1998%20c%2023%20§%2012[1998 c 23 § 12]; ]

== 24.03.334 - Certificate of authority as insurance company—Registration or reservation of name. (Effective until January 1, 2022.)
For those corporations that intend to apply for a certificate of authority from the insurance commissioner as an insurance company under chapter 48.05 RCW, whenever under this chapter a corporation may register or reserve a corporate name, the registration or reservation shall be filed with the insurance commissioner rather than the secretary of state. The secretary of state and insurance commissioner shall cooperate with each other in registering or reserving a corporate name so that there is no duplication of the name.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1065-S2.SL.pdf?cite=1998%20c%2023%20§%2013[1998 c 23 § 13]; ]

== 24.03.335 - Effect of foreign registration statement—Right of state to terminate registration. (Effective until January 1, 2022.)
Upon the filing of the foreign registration statement by the secretary of state, the corporation shall be authorized to conduct affairs in this state for those purposes set forth in its application, subject, however, to the right of this state to terminate the registration as provided in RCW 23.95.550.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203124[2015 c 176 § 3124]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%20100[1982 c 35 § 100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2068[1967 c 235 § 68]; ]

== 24.03.340 - Registered agent of foreign corporation. (Effective until January 1, 2022.)
Each foreign corporation registered to conduct affairs in this state shall have and continuously maintain in this state a registered agent in accordance with Article 4 of chapter 23.95 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203125[2015 c 176 § 3125]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2029[2004 c 265 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%20101[1982 c 35 § 101]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2069[1967 c 235 § 69]; ]

== 24.03.345 - Change of registered agent of foreign corporation. (Effective until January 1, 2022.)
A foreign corporation registered to conduct affairs in this state may change its registered agent by delivering to the secretary of state for filing a statement of change in accordance with RCW 23.95.430. The statement shall be executed by the corporation by an officer of the corporation.

Any registered agent in this state appointed by a foreign corporation may resign as such agent by executing and delivering to the secretary of state for filing a statement of resignation in accordance with RCW 23.95.445.

A registered agent of a foreign corporation may change its information on file with the secretary of state in accordance with RCW 23.95.435 or 23.95.440.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203126[2015 c 176 § 3126]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2030[2004 c 265 § 30]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5471-S.SL.pdf?cite=1993%20c%20356%20§%206[1993 c 356 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2047[1986 c 240 § 47]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%20102[1982 c 35 § 102]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2070[1967 c 235 § 70]; ]

== 24.03.350 - Service on foreign corporation. (Effective until January 1, 2022.)
Service of any process, notice, or demand required or permitted by law to be served upon the corporation may be made in accordance with RCW 23.95.450.

Nothing herein contained shall limit or affect the right to serve any process, notice, or demand, required or permitted by law to be served upon a corporation in any other manner now or hereafter permitted by law.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203127[2015 c 176 § 3127]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20658[2011 c 336 § 658]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2048[1986 c 240 § 48]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%20103[1982 c 35 § 103]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2071[1967 c 235 § 71]; ]

== 24.03.360 - Merger of foreign corporation authorized to conduct affairs in this state. (Effective until January 1, 2022.)
Whenever a foreign corporation authorized to conduct affairs in this state shall be a party to a statutory merger permitted by the laws of the state or country under the laws of which it is incorporated, and such corporation shall be the surviving corporation, it shall not be necessary for such corporation to procure either a new or amended certificate of authority to conduct affairs in this state unless the name of such corporation be changed thereby or unless the corporation desires to pursue in this state other or additional purposes than those which it is then authorized to pursue in this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2049[1986 c 240 § 49]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2073[1967 c 235 § 73]; ]

== 24.03.365 - Amended foreign registration statement. (Effective until January 1, 2022.)
A foreign corporation registered to conduct affairs in this state shall amend its foreign registration statement under the circumstances specified in RCW 23.95.515.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203128[2015 c 176 § 3128]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2031[2004 c 265 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2074[1967 c 235 § 74]; ]

== 24.03.370 - Withdrawal of foreign corporation. (Effective until January 1, 2022.)
A foreign corporation registered to conduct affairs in this state may withdraw from this state by delivering a statement of withdrawal to the secretary of state for filing in accordance with RCW 23.95.530.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203129[2015 c 176 § 3129]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5471-S.SL.pdf?cite=1993%20c%20356%20§%207[1993 c 356 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%20104[1982 c 35 § 104]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2075[1967 c 235 § 75]; ]

== 24.03.380 - Termination of registration. (Effective until January 1, 2022.)
. The registration of a foreign corporation to conduct affairs in this state may be terminated by the secretary of state in accordance with RCW 23.95.550.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203130[2015 c 176 § 3130]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2032[2004 c 265 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2050[1986 c 240 § 50]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%20106[1982 c 35 § 106]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2077[1967 c 235 § 77]; ]

== 24.03.390 - Conducting affairs without registering. (Effective until January 1, 2022.)
A foreign corporation which is conducting affairs in this state without registering with the secretary of state is subject to RCW 23.95.505.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203131[2015 c 176 § 3131]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2052[1986 c 240 § 52]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2079[1967 c 235 § 79]; ]

== 24.03.395 - Annual report of domestic and foreign corporations. (Effective until January 1, 2022.)
Each domestic corporation, and each foreign corporation registered to conduct affairs in this state, shall deliver an annual report to the secretary of state in accordance with RCW 23.95.255.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203132[2015 c 176 § 3132]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5471-S.SL.pdf?cite=1993%20c%20356%20§%2010[1993 c 356 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c291.pdf?cite=1989%20c%20291%20§%202[1989 c 291 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c117.pdf?cite=1987%20c%20117%20§%204[1987 c 117 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2053[1986 c 240 § 53]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%20108[1982 c 35 § 108]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2080[1967 c 235 § 80]; ]

== 24.03.405 - Applicable fees, charges, and penalties. (Effective until January 1, 2022.)
Nonprofit corporations are subject to the applicable fees, charges, and penalties established by the secretary of state under RCW 23.95.260 and 43.07.120.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203133[2015 c 176 § 3133]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2576-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%2029%20§%203[2010 1st sp.s. c 29 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5492-S.SL.pdf?cite=1993%20c%20269%20§%205[1993 c 269 § 5]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1853.SL.pdf?cite=1991%20c%20223%20§%201[1991 c 223 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c117.pdf?cite=1987%20c%20117%20§%205[1987 c 117 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2055[1986 c 240 § 55]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%20110[1982 c 35 § 110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c230.pdf?cite=1981%20c%20230%20§%205[1981 c 230 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c163.pdf?cite=1969%20ex.s.%20c%20163%20§%205[1969 ex.s. c 163 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2082[1967 c 235 § 82]; ]

== 24.03.417 - Fees for services by secretary of state. (Effective until January 1, 2022.)
See RCW 43.07.120.

[ ]

== 24.03.420 - Penalties imposed upon corporation. (Effective until January 1, 2022.)
Each corporation, domestic or foreign, that fails or refuses to answer truthfully and fully within the time prescribed by this chapter interrogatories propounded by the secretary of state in accordance with the provisions of this chapter, shall be deemed to be guilty of a misdemeanor and upon conviction thereof may be fined in any amount not exceeding five hundred dollars.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c163.pdf?cite=1969%20ex.s.%20c%20163%20§%207[1969 ex.s. c 163 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2085[1967 c 235 § 85]; ]

== 24.03.425 - Penalties imposed upon directors and officers. (Effective until January 1, 2022.)
Each director and officer of a corporation, domestic or foreign, who fails or refuses within the time prescribed by this chapter to answer truthfully and fully interrogatories propounded to him or her by the secretary of state in accordance with the provisions of this chapter shall be deemed to be guilty of a misdemeanor, and upon conviction thereof may be fined in any amount not exceeding five hundred dollars.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203134[2015 c 176 § 3134]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2034[2004 c 265 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2086[1967 c 235 § 86]; ]

== 24.03.430 - Interrogatories by secretary of state. (Effective until January 1, 2022.)
The secretary of state may propound to any corporation, domestic or foreign, subject to the provisions of this chapter, and to any officer or director thereof, such interrogatories as may be reasonably necessary and proper to enable the secretary of state to ascertain whether such corporation has complied with all the provisions of this chapter applicable to such corporation. Such interrogatories shall be answered within thirty days after the mailing thereof, or within such additional time as shall be fixed by the secretary of state, and the answers thereto shall be full and complete and shall be made in writing and under oath. If such interrogatories be directed to an individual they shall be answered by that individual, and if directed to a corporation they shall be answered by the president, vice president, secretary or assistant secretary thereof. The secretary of state need not file any record to which such interrogatories relate until such interrogatories be answered as herein provided, and not then if the answers thereto disclose that such record is not in conformity with the provisions of this chapter. The secretary of state shall certify to the attorney general, for such action as the attorney general may deem appropriate, all interrogatories and answers thereto which disclose a violation of any of the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2035[2004 c 265 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%20112[1982 c 35 § 112]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2087[1967 c 235 § 87]; ]

== 24.03.435 - Confidential nature of information disclosed by interrogatories. (Effective until January 1, 2022.)
Interrogatories propounded by the secretary of state and the answers thereto shall not be open to public inspection nor shall the secretary of state disclose any facts or information obtained therefrom except in so far as the secretary of state's official duty may require the same to be made public or in the event such interrogatories or the answers thereto are required for evidence in any criminal proceedings or in any other action by this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%20113[1982 c 35 § 113]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2088[1967 c 235 § 88]; ]

== 24.03.440 - Power and authority of secretary of state. (Effective until January 1, 2022.)
The secretary of state shall have the power and authority reasonably necessary for the efficient and effective administration of this chapter, including the adoption of rules under chapter 34.05 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%20114[1982 c 35 § 114]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2089[1967 c 235 § 89]; ]

== 24.03.445 - Duty of secretary of state to file—Review of refusal to file. (Effective until January 1, 2022.)
RCW 23.95.225 governs the secretary of state's duty to file records delivered to the secretary of state for filing, the manner and effect of filing, and procedures that apply when the secretary of state refuses to file a record.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%203135[2015 c 176 § 3135]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2036[2004 c 265 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c240.pdf?cite=1986%20c%20240%20§%2056[1986 c 240 § 56]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%20115[1982 c 35 § 115]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2090[1967 c 235 § 90]; ]

== 24.03.455 - Greater voting requirements. (Effective until January 1, 2022.)
Whenever, with respect to any action to be taken by the members or directors of a corporation, the articles of incorporation require the vote or concurrence of a greater proportion of the members or directors, as the case may be, than required by this chapter with respect to such action, the provisions of the articles of incorporation shall control.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2092[1967 c 235 § 92]; ]

== 24.03.460 - Waiver of notice. (Effective until January 1, 2022.)
Whenever any notice is required to be given to any member or director of a corporation under the provisions of this chapter or under the provisions of the articles of incorporation or bylaws of the corporation, a waiver in the form of a record executed by the person or persons entitled to such notice, whether before or after the time stated therein, shall be equivalent to the giving of such notice.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2038[2004 c 265 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2093[1967 c 235 § 93]; ]

== 24.03.465 - Action by members or directors without a meeting. (Effective until January 1, 2022.)
Any action required by this chapter to be taken at a meeting of the members or directors of a corporation, or any action which may be taken at a meeting of the members or directors, may be taken without a meeting if a consent in the form of a record, setting forth the action so taken, shall be executed by all of the members entitled to vote with respect to the subject matter thereof, or all of the directors, as the case may be.

Such consent shall have the same force and effect as a unanimous vote, and may be stated as such in any articles or record filed with the secretary of state under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6188.SL.pdf?cite=2004%20c%20265%20§%2039[2004 c 265 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2094[1967 c 235 § 94]; ]

== 24.03.470 - Unauthorized assumption of corporate powers. (Effective until January 1, 2022.)
All persons who assume to act as a corporation without authority so to do shall be jointly and severally liable for all debts and liabilities incurred or arising as a result thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2095[1967 c 235 § 95]; ]

== 24.03.480 - Postsecondary education loans—Interest rates. (Effective until January 1, 2022.)
A nonprofit corporation may charge interest upon any loan made under a program to finance postsecondary education at any rate or rates of interest which are permitted by state or federal law to be charged by any state or federally chartered bank, savings and loan association, or credit union.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c166.pdf?cite=1989%20c%20166%20§%201[1989 c 166 § 1]; ]

== 24.03.490 - Public benefit nonprofit corporation designation established. (Effective until January 1, 2022.)
There is hereby established the special designation "public benefit not for profit corporation" or "public benefit nonprofit corporation." A corporation may be designated as a public benefit nonprofit corporation if it meets the following requirements:

. The corporation complies with the provisions of this chapter; and

. The corporation holds a current tax exempt status as provided under 26 U.S.C. Sec. 501(c)(3) or is not required to apply for its tax exempt status under 26 U.S.C. Sec. 501(c)(3).

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c291.pdf?cite=1989%20c%20291%20§%204[1989 c 291 § 4]; ]

== 24.03.500 - Public benefit nonprofit corporations—Temporary designation. (Effective until January 1, 2022.)
A temporary designation as a public benefit nonprofit corporation may be provided to a corporation that has applied for tax exempt status under 26 U.S.C. Sec. 501(c)(3). The temporary designation is valid for up to one year and may be renewed at the discretion of the secretary.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c291.pdf?cite=1989%20c%20291%20§%205[1989 c 291 § 5]; ]

== 24.03.510 - Public benefit nonprofit corporations—Application. (Effective until January 1, 2022.)
The secretary shall develop an application process for new and existing corporations to apply for public benefit nonprofit corporation status.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c291.pdf?cite=1989%20c%20291%20§%206[1989 c 291 § 6]; ]

== 24.03.520 - Public benefit nonprofit corporations—Renewal. (Effective until January 1, 2022.)
The designation "public benefit nonprofit corporation" shall be renewed annually. The secretary may schedule renewals in conjunction with existing corporate renewals.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c291.pdf?cite=1989%20c%20291%20§%207[1989 c 291 § 7]; ]

== 24.03.530 - Public benefit nonprofit corporations—Fees. (Effective until January 1, 2022.)
The secretary may establish fees to cover the cost of renewals.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c291.pdf?cite=1989%20c%20291%20§%208[1989 c 291 § 8]; ]

== 24.03.540 - Public benefit nonprofit corporations—Removal of status. (Effective until January 1, 2022.)
The secretary may remove a corporation's public benefit nonprofit corporation designation if it does not comply with the provisions of this chapter or does not maintain its exempt status under 26 U.S.C. Sec. 501(c)(3). The secretary in removing a corporation's public benefit nonprofit corporation status shall comply with administrative procedures provided by this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c291.pdf?cite=1989%20c%20291%20§%209[1989 c 291 § 9]; ]

== 24.03.550 - Host home programs—Registration. (Effective until January 1, 2022.)
. Host home programs have the same meaning as described in RCW 74.15.020.

. Host home programs shall register with the secretary of state's office. This registration may occur when the host home program files articles of incorporation or registers as a nonprofit organization under this chapter.

. The host home program registration must include a notarized statement by the host home program that it meets all of the statutory requirements as provided for in RCW 74.15.020.

. The secretary of state has no duty to confirm that a host home program is meeting its statutory requirements.

. Any filing under this section does not imply an endorsement by the secretary of state.

. The secretary of state may adopt rules as necessary to carry out its duties under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2440-S.SL.pdf?cite=2016%20c%20166%20§%203[2016 c 166 § 3]; ]

== 24.03.900 - Short title. (Effective until January 1, 2022.)
This chapter shall be known and may be cited as the "Washington nonprofit corporation act."

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%201[1967 c 235 § 1]; ]

== 24.03.905 - Savings—1967 c 235. (Effective until January 1, 2022.)
Any corporation existing on the date when this chapter takes effect shall continue to exist as a corporation despite any provision of this chapter changing the requirements for forming a corporation or repealing or amending the law under which it was formed. The provisions of this chapter shall, however, apply prospectively to the fullest extent permitted by the Constitutions of the United States and the state of Washington to all existing corporations organized under any general act of the territory or the state of Washington providing for the organization of corporations for a purpose or purposes for which a corporation might be organized under this chapter. The repeal of any prior act or part thereof by this chapter shall not affect any right accrued or any liability or penalty incurred, under the provisions of such act, prior to the repeal thereof. The repeal of a prior act or acts by this chapter shall not affect any existing corporation organized for a purpose or purposes other than those for which a corporation might be organized under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2096[1967 c 235 § 96]; ]

== 24.03.915 - Notice to existing corporations. (Effective until January 1, 2022.)
. The secretary of state shall notify all existing nonprofit corporations thirty days prior to the effective date of this chapter, that in the event they fail to appoint a registered agent as provided in chapter 163, Laws of 1969 ex. sess. within ninety days following the effective date of chapter 163, Laws of 1969 ex. sess., they shall thereupon cease to exist.

. If the notification provided under subsection (1) of this section, from the secretary of state to any corporation was or has been returned unclaimed or undeliverable, the secretary of state shall proceed to dissolve the corporation by striking the name of such corporation from the records of active corporations.

. Corporations dissolved under subsection (2) of this section may be reinstated at any time within three years of the dissolution action by the secretary of state. The corporation shall be reinstated by filing a request for reinstatement, by appointment of a registered agent and designation of a registered office as required by this chapter, and by filing an annual report for the reinstatement year. No fees may be charged for reinstatements under this section. If, during the period of dissolution, another person or corporation has reserved or adopted a corporate name which is identical to or deceptively similar to the dissolved corporation's name, the corporation seeking reinstatement shall be required to adopt another name consistent with the requirements of this chapter and to amend its articles of incorporation accordingly.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c35.pdf?cite=1982%20c%2035%20§%20117[1982 c 35 § 117]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c163.pdf?cite=1969%20ex.s.%20c%20163%20§%208[1969 ex.s. c 163 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2098[1967 c 235 § 98]; ]

== 24.03.920 - Repealer—Exception. (Effective until January 1, 2022.)
The following acts or parts of acts, except insofar as may be applicable to the rights, powers and duties of persons and corporations not subject to the provisions of this chapter, are hereby repealed:

. Chapter 110, Laws of 1961;

. Section 6, chapter 12, Laws of 1959;

. Section 3, chapter 263, Laws of 1959;

. Chapter 32, Laws of 1955;

. Chapter 121, Laws of 1953;

. Chapter 249, Laws of 1947;

. Chapter 122, Laws of 1943;

. Chapter 89, Laws of 1933;

. Section 2, chapter 63, Laws of 1925 extraordinary session;

. Chapter 8, Laws of 1923;

. Chapter 75, Laws of 1907;

. Chapter 134, Laws of 1907;

. Chapter 125, Laws of 1905;

. Page 24, chapter XIX (19), Laws of 1895;

. Page 348, chapter CXXXV (135), Laws of 1895;

. Chapter CLVIII (158), Laws of 1895;

. Section 1, page 86, Laws of 1886;

. Sections 2450 through 2454, Code of 1881;

. Pages 409 through 411, Laws of 1873;

. Pages 341 and 342, Laws of 1869;

. Pages 67 and 68, Laws of 1866; and

. RCW sections 24.01.010, 24.04.010 through 24.04.170, 24.08.010 through 24.08.900, and 24.16.010 through 24.16.140.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%20100[1967 c 235 § 100]; ]

== 24.03.925 - Effective date—1967 c 235. (Effective until January 1, 2022.)
This chapter shall become effective July 1, 1969.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c235.pdf?cite=1967%20c%20235%20§%2099[1967 c 235 § 99]; ]

