= 24.34 - Agricultural processing and marketing associations.
:toc:

== 24.34.010 - Who may organize—Purposes—Limitations.
Persons engaged in the production of agricultural products as farmers, planters, ranchers, dairy farmers, nut growers, or fruit growers may act together in associations, corporate or otherwise, with or without capital stock, in collectively processing, preparing for market, handling, and marketing in intrastate commerce, such products of persons so engaged. Such associations may have marketing agencies in common; and such associations and their members may make the necessary contracts and agreements to effect such purposes: PROVIDED, That such associations are operated for the mutual benefit of the members thereof, as such producers, and conform to one or both of the following requirements:

First. That no member of the association is allowed more than one vote because of the amount of stock or membership capital he or she may own therein, or,

Second. That the association does not pay dividends on stock or membership capital in excess of eight percent per annum.

And in any case to the following:

Third. That the association shall not deal in the products of nonmembers to an amount greater in value than such as are handled by it for members.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%2040[2013 c 23 § 40]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20674[2011 c 336 § 674]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c187.pdf?cite=1967%20c%20187%20§%201[1967 c 187 § 1]; ]

== 24.34.020 - Monopoly or restraint of trade—Complaint—Procedure.
If the attorney general has reason to believe that any such association as provided for in RCW 24.34.010 monopolizes or restrains trade to such an extent that the price of any agricultural product is unduly enhanced by reason thereof, he or she shall serve upon such association a complaint stating his or her charge in that respect, to which complaint shall be attached, or contained therein, a notice of hearing, specifying a day and place not less than thirty days after the service thereof, requiring the association to show cause why an order should not be made directing it to cease and desist from monopolization or restraint of trade.

Such hearing, and any appeal which may be made from such hearing, shall be conducted and held subject to and in conformance with the provisions for adjudicative proceedings and judicial review in chapter 34.05 RCW, the administrative procedure act.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20675[2011 c 336 § 675]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%2075[1989 c 175 § 75]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c187.pdf?cite=1967%20c%20187%20§%202[1967 c 187 § 2]; ]

