= 24.36 - Fish marketing act.
:toc:

== 24.36.010 - Short title.
This chapter may be cited as "The Fish Marketing Act".

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%201[1959 c 312 § 1]; ]

== 24.36.020 - Declaration of purpose.
The purpose of this chapter is to promote, foster, and encourage the intelligent and orderly marketing of fish and fishery products through cooperation; to eliminate speculation and waste; to make the distribution of fish and fishery products between producer and consumer as direct as can be efficiently done; and to stabilize the marketing of fish and fishery products.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%202[1959 c 312 § 2]; ]

== 24.36.030 - Definitions.
As used in this chapter:

. "Fishery products" includes fish, crustaceans, mollusks, and marine products for human consumption.

. "Member" includes members of associations without capital stock and holders of common stock in associations organized with shares of stock.

. "Association" means any corporation organized under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%203[1959 c 312 § 3]; ]

== 24.36.040 - Associations deemed nonprofit.
Associations shall be deemed "nonprofit", inasmuch as they are not organized to make profit for themselves, as such, or for their members, as such, but only for their members as producers of fishery products.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%204[1959 c 312 § 4]; ]

== 24.36.050 - General laws relating to corporations for profit applicable.
The provisions of Title 23B RCW and all powers and rights thereunder, apply to associations, except where such provisions are in conflict with or inconsistent with the express provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=1991%20c%2072%20§%2045[1991 c 72 § 45]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%205[1959 c 312 § 5]; ]

== 24.36.055 - Fees for services by secretary of state.
See RCW 43.07.120.

[ ]

== 24.36.060 - Securities act inapplicable.
No association is subject in any manner to the terms of chapter 21.20 RCW and all associations may issue their membership certificates or stock or other securities as provided in this division without the necessity of any permit from the director of licenses.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%2027[1983 c 3 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%206[1959 c 312 § 6]; ]

== 24.36.070 - Associations deemed not a conspiracy, in restraint of trade, etc.—Contracts not illegal.
An association shall be deemed not to be a conspiracy, nor a combination in restraint of trade nor an illegal monopoly; nor an attempt to lessen competition or to fix prices arbitrarily or to create a combination or pool in violation of any law of the state; and the marketing contracts and agreements between the association and its members and any agreements authorized in this chapter shall be considered not to be illegal nor in restraint of trade nor contrary to the provisions of any statute enacted against pooling or combinations.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%207[1959 c 312 § 7]; ]

== 24.36.080 - Conflicting laws not applicable—Exemptions apply.
Any provisions of law which are in conflict with this chapter shall not be construed as applying to associations. Any exemptions under any laws applying to fishery products in the possession or under the control of the individual producer shall apply similarly and completely to such fishery products delivered by its members, in the possession or under the control of the association.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%208[1959 c 312 § 8]; ]

== 24.36.090 - Merger, consolidation of associations authorized—Procedure.
Any two or more associations may be merged into one such constituent association or consolidated into a new association. Such merger or consolidation shall be made in the manner prescribed by RCW 23B.07.050 and chapter 23B.11 RCW for domestic corporations.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=1991%20c%2072%20§%2046[1991 c 72 § 46]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%2028[1983 c 3 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%209[1959 c 312 § 9]; ]

== 24.36.100 - Stock associations—Statement in articles.
If the association is organized with shares of stock, the articles shall state the number of shares which may be issued and if the shares are to have a par value, the par value of each share, and the aggregate par value of all shares; and if the shares are to be without par value it shall be so stated.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2010[1959 c 312 § 10]; ]

== 24.36.110 - Stock associations—Classified shares—Statement in articles.
If the shares are to be classified, the articles shall contain a description of the classes of shares and a statement of the number of shares of each kind or class and the nature and extent of the preferences, rights, privileges and restrictions granted to or imposed upon the holders of the respective classes of stock.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2011[1959 c 312 § 11]; ]

== 24.36.120 - Nonstock associations—Statement in articles.
If the association is organized without shares of stock, the articles shall state whether the voting power and the property rights and interest of each member are equal or unequal; and if unequal the general rule or rules applicable to all members by which the voting power and the property rights and interests, respectively, of each member may be and are determined and fixed; and shall also provide for the admission of new members who shall be entitled to vote and to share in the property of the association with the old members, in accordance with such general rule or rules.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2012[1959 c 312 § 12]; ]

== 24.36.130 - Bylaws of association.
Each association shall within thirty days after its incorporation, adopt for its government and management, a code of bylaws, not inconsistent with this chapter. A majority vote of the members or shares of stock issued and outstanding and entitled to vote, or the written assent of a majority of the members or of stockholders representing a majority of all the shares of stock issued and outstanding and entitled to vote, is necessary to adopt such bylaws and is effectual to repeal or amend any bylaws or to adopt additional bylaws. The power to repeal and amend the bylaws, and adopt new bylaws, may, by a similar vote, or similar written assent, be delegated to the board of directors, which authority may, by a similar vote, or similar written assent, be revoked.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2013[1959 c 312 § 13]; ]

== 24.36.140 - Bylaws of association—Transfer of stock, membership certificates limited.
The bylaws shall prohibit the transfer of the common stock or membership certificates of the associations to persons not engaged in the production of the products handled by the association.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2014[1959 c 312 § 14]; ]

== 24.36.150 - Bylaws of association—Quorum, voting, directors, penalties.
The bylaws may provide:

. The number of members constituting a quorum.

. The right of members to vote by proxy or by mail or both, and the conditions, manner, form and effects of such votes; the right of members to cumulate their votes and the prohibition, if desired, of cumulative voting.

. The number of directors constituting a quorum.

. The qualifications, compensation and duties and term of office of directors and officers and the time of their election.

. Penalties for violations of the bylaws.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2015[1959 c 312 § 15]; ]

== 24.36.160 - Bylaws of association—Fees, charges, marketing contract, dividends.
The bylaws may provide:

. The amount of entrance, organization, and membership fees, if any; the manner and method of collection of the same; and the purposes for which they may be used.

. The amount which each member shall be required to pay annually, or from time to time, if at all, to carry on the business of the association; the charge, if any, to be paid by each member for services rendered by the association to him or her and the time of payment and the manner of collection; and the marketing contract between the association and its members which every member may be required to sign.

. The amount of any dividends which may be declared on the stock or membership capital, which dividends shall not exceed eight percent per annum and which dividends shall be in the nature of interest and shall not affect the nonprofit character of any association organized hereunder.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20676[2011 c 336 § 676]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2016[1959 c 312 § 16]; ]

== 24.36.170 - Bylaws of association—Membership.
The bylaws may provide:

. The number and qualification of members of the association and the conditions precedent to membership or ownership of common stock.

. The method, time, and manner of permitting members to withdraw or the holders of common stock to transfer their stock.

. The manner of assignment and transfer of the interest of members and of the shares of common stock.

. The conditions upon which and time when membership of any member shall cease.

. For the automatic suspension of the rights of a member when he or she ceases to be eligible to membership in the association; and the mode, manner, and effect of the expulsion of a member.

. The manner of determining the value of a member's interest and provision for its purchase by the association upon the death or withdrawal of a member or upon the expulsion of a member or forfeiture of his or her membership, or at the option of the association, the purchase at a price fixed by conclusive appraisal by the board of directors; and the conditions and terms for the repurchase by the corporation from its stockholders of their stock upon their disqualification as stockholders.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20677[2011 c 336 § 677]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2017[1959 c 312 § 17]; ]

== 24.36.180 - Bylaws of association—Meetings.
The bylaws may provide for the time, place, and manner of calling and conducting meetings of the association.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2018[1959 c 312 § 18]; ]

== 24.36.190 - Bylaws of association—Direct election of directors from districts of territory.
The bylaws may provide that the territory in which the association has members shall be divided into districts and that directors shall be elected from the several districts. In such case, the bylaws shall specify the number of directors to be elected by each district, the manner and method of reapportioning the directors and of redistricting the territory covered by the association.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2019[1959 c 312 § 19]; ]

== 24.36.200 - Bylaws of association—Election of directors by representatives or advisers from districts of territory.
The bylaws may provide that the territory in which the association has members shall be divided into districts, and that the directors shall be elected by representatives or advisers, who themselves have been elected by the members from the several territorial districts. In such case, the bylaws shall specify the number of representatives or advisers to be elected by each district, the manner and method of reapportioning the representatives or advisers and of redistricting the territory covered by the association.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2020[1959 c 312 § 20]; ]

== 24.36.210 - Bylaws of association—Primary elections to nominate directors.
The bylaws may provide that primary elections shall be held to nominate directors. Where the bylaws provide that the territory in which the association has members shall be divided into districts, the bylaws may also provide that the results of the primary elections in the various districts shall be final and shall be ratified at the annual meeting of the association.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2021[1959 c 312 § 21]; ]

== 24.36.220 - Bylaws of association—Nomination of directors by public officials or other directors—Limitation.
The bylaws may provide that one or more directors may be nominated by any public official or commission or by the other directors selected by the members. Such directors shall represent primarily the interest of the general public in such associations. The directors so nominated need not be members of the association, but shall have the same powers and rights as other directors. Such directors shall not number more than one-fifth of the entire number of directors.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2022[1959 c 312 § 22]; ]

== 24.36.230 - Bylaws of association—Terms of directors—Staggering.
The bylaws may provide that directors shall be elected for terms of from one to five years: PROVIDED, That at each annual election the same fraction of the total number of directors shall be elected as one year bears to the number of years of the term of office.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2023[1959 c 312 § 23]; ]

== 24.36.240 - Bylaws of association—Executive committee.
The bylaws may provide for an executive committee and may allot to such committee all the functions and powers of the board of directors, subject to the general direction and control of the board.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2024[1959 c 312 § 24]; ]

== 24.36.250 - Qualifications of members, stockholders.
. Under the terms and conditions prescribed in the bylaws, an association may admit as members, or issue common stock to, only such persons as are engaged in the production of fishery products to be handled by or through the association, including the lessees and tenants of boats and equipment used for the production of such fishery products and any lessors and landlords who receive as rent all or part of the fish produced by such leased equipment.

. If a member of a nonstock association is other than a natural person, such member may be represented by any individual duly authorized in writing.

. One association may become a member or stockholder of any other association.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2025[1959 c 312 § 25]; ]

== 24.36.260 - Certificate of membership in nonstock associations.
When a member of an association established without shares of stock has paid his or her membership fee in full, he or she shall receive a certificate of membership.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20678[2011 c 336 § 678]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2026[1959 c 312 § 26]; ]

== 24.36.270 - Liability of member for association's debts.
No member shall be liable for the debts of the association to an amount exceeding the sum remaining unpaid on his or her membership fee or his or her subscription to the capital stock, including any unpaid balance on any promissory note given in payment thereof.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20679[2011 c 336 § 679]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2027[1959 c 312 § 27]; ]

== 24.36.280 - Place of membership meetings.
Meetings of members shall be held at the place as provided in the bylaws; and if no provision is made, in the city where the principal place of business is located at a place designated by the board of directors.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2028[1959 c 312 § 28]; ]

== 24.36.290 - Appraisal of expelled member's property—Payment.
In case of the expulsion of a member, and where the bylaws do not provide any procedure or penalty, the board of directors shall equitably and conclusively appraise his or her property interest in the association and shall fix the amount thereof in money, which shall be paid to him or her within one year after such expulsion.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20680[2011 c 336 § 680]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2029[1959 c 312 § 29]; ]

== 24.36.300 - Powers of association—General scope of activities.
An association may:

Engage in any activity in connection with the marketing, selling, preserving, harvesting, drying, processing, manufacturing, canning, packing, grading, storing, handling, or utilization of any fishery products produced or delivered to it by its members; or the manufacturing or marketing of the by-products thereof; or any activity in connection with the purchase, hiring, or use by its members of supplies, machinery, or equipment, or in the financing of any such activities.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2030[1959 c 312 § 30]; ]

== 24.36.310 - Powers of association—Incurring indebtedness—Advances to members.
An association may borrow without limitation as to amount of corporate indebtedness or liability and may make advances to members.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2031[1959 c 312 § 31]; ]

== 24.36.320 - Association as agent for member.
An association may act as the agent or representative of any member or members in any of the two next preceding sections.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2032[1959 c 312 § 32]; ]

== 24.36.330 - Reserves—Investments.
An association may establish reserves and invest the funds thereof in bonds or in such other property as may be provided in the bylaws.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2033[1959 c 312 § 33]; ]

== 24.36.340 - Powers relating to capital stock or bonds of other corporations or associations.
An association may purchase or otherwise acquire, hold, own, and exercise all rights of ownership in, sell, transfer, pledge, or guarantee the payment of dividends or interest on, or the retirement or redemption of, shares of the capital stock or bonds of any corporation or association engaged in any related activity or in the warehousing or handling or marketing or packing or manufacturing or processing or preparing for market of any of the fishery products handled by the association.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2034[1959 c 312 § 34]; ]

== 24.36.350 - Powers relating to real or personal property.
An association may buy, hold and exercise all privileges or ownership, over such real or personal property as may be necessary or convenient for the conduct and operation of any of the business of the association, or incidental thereto.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2035[1959 c 312 § 35]; ]

== 24.36.360 - Levy of assessments.
An association may levy assessments in the manner and in the amount provided in its bylaws.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2036[1959 c 312 § 36]; ]

== 24.36.370 - General powers, rights, privileges of association.
An association may do each and every thing necessary, suitable or proper for the accomplishment of any one of the purposes or the attainment of any one or more of the objects enumerated in this chapter; or conducive to or expedient for the interest or benefit of the association; and contract accordingly; and in addition exercise and possess all powers, rights and privileges necessary or incidental to the purposes for which the association is organized or to the activities in which it is engaged; and, in addition, any other rights, powers and privileges granted by the laws of this state to ordinary corporations, except such as are inconsistent with the express provisions of this chapter; and do any such thing anywhere.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2037[1959 c 312 § 37]; ]

== 24.36.380 - Use of association's facilities—Disposition of proceeds.
An association may use or employ any of its facilities for any purpose: PROVIDED, That the proceeds arising from such use and employment go to reduce the cost of operation for its members; but the fishery products of nonmembers shall not be dealt in to an amount greater in value than such as are handled by it for its members.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2038[1959 c 312 § 38]; ]

== 24.36.390 - Power of association to form, control, own stock in or be member of another corporation or association—Warehouse receipts.
An association may organize, form, operate, own, control, have an interest in, own stock of, or be a member of any other corporation or corporations, with or without capital stock and engaged in preserving, drying, processing, canning, packing, storing, handling, shipping, utilizing, manufacturing, marketing, or selling of the fishery products handled by the association, or the by-products thereof.

If such corporations are warehousing corporations, they may issue legal warehouse receipts to the association against the commodities delivered by it, or to any other person and such legal warehouse receipts shall be considered as adequate collateral to the extent of the usual and current value of the commodity represented thereby. In case such warehouse is licensed or licensed and bonded under the laws of this state or the United States, its warehouse receipt delivered to the association on commodities of the association or its members, or delivered by the association or its members, shall not be challenged or discriminated against because of ownership or control, wholly or in part, by the association.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2039[1959 c 312 § 39]; ]

== 24.36.400 - Contracts and agreements with other corporations or associations—Joint operations.
Any association may, upon resolution adopted by its board of directors, enter into all necessary and proper contracts and agreements and make all necessary and proper stipulations, agreements and contracts and arrangements with any other cooperative or other corporation, association, or associations, formed in this or in any other state, for the cooperative and more economical carrying on of its business or any part or parts thereof. Any two or more associations may, by agreement between them, unite in employing and using or may separately employ and use the same personnel, methods, means, and agencies for carrying on and conducting their respective business.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2040[1959 c 312 § 40]; ]

== 24.36.410 - Marketing contracts with members.
An association and its members may make and execute marketing contracts, requiring the members to sell, for any period of time, not over fifteen years, all or any specified part of their fishery products or specified commodities exclusively to or through the association or any facilities to be created by the association.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2041[1959 c 312 § 41]; ]

== 24.36.420 - When title passes on sale by member to association.
If the members contract a sale to the association, it shall be conclusively held that title to the products passes absolutely and unreservedly, except for recorded liens, to the association upon delivery or at any other time expressly and definitely specified in the contract.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2042[1959 c 312 § 42]; ]

== 24.36.430 - Association may sell products without taking title—Powers and duties.
The contract may provide that the association may sell or resell the fishery products delivered by its members, with or without taking title thereto; and pay over to its members the resale price, after deducting all necessary selling, overhead, and other costs and expenses, including interest on preferred stock, not exceeding eight percent per annum, and reserves for retiring the stock, if any; and other proper reserves; and interest not exceeding eight percent per annum upon common stock.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2043[1959 c 312 § 43]; ]

== 24.36.440 - Liability of member for breach of marketing contract.
The marketing contract may fix, as liquidated damages, specific sums to be paid by the member to the association upon the breach by him or her of any provision of the marketing contract regarding the sale or delivery or withholding of fishery products; and may further provide that the member will pay all costs, premiums for bonds, expenses, and fees, in case any action is brought upon the contract by the association; and any such provisions shall be valid and enforceable in the courts of this state; and such clauses providing for liquidated damages shall be enforceable as such and shall not be regarded as penalties.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20681[2011 c 336 § 681]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2044[1959 c 312 § 44]; ]

== 24.36.450 - Injunctions, specific performance if breach or threatened breach by member.
In the event of any such breach or threatened breach of such marketing contract by a member the association shall be entitled to an injunction to prevent the further breach of the contract and to a decree of specific performance thereof. Pending the adjudication of such an action and upon filing a verified complaint showing the breach or threatened breach, and upon filing sufficient bond, the association shall be entitled to a temporary restraining order and preliminary injunction against the member.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2045[1959 c 312 § 45]; ]

== 24.36.460 - Presumption that landlord or lessor can control delivery—Remedies for nondelivery or breach.
In any action upon such marketing agreements, it shall be conclusively presumed that a landlord or lessor is able to control the delivery of fishery products produced by his or her equipment by tenants, or others, whose tenancy or possession or work on such equipment or the terms of whose tenancy or possession or labor thereon were created or changed after execution by the landlord or lessor, of such a marketing agreement; and in such actions, the foregoing remedies for nondelivery or breach shall lie and be enforceable against such landlord or lessor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20682[2011 c 336 § 682]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2046[1959 c 312 § 46]; ]

== 24.36.470 - Enforcement by association to secure delivery by member.
A contract entered into by a member of an association, providing for the delivery to such association of products produced or acquired by the member, may be specifically enforced by the association to secure the delivery to it of such fishery products, any provisions of law to the contrary notwithstanding.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c312.pdf?cite=1959%20c%20312%20§%2047[1959 c 312 § 47]; ]

