= 15.36 - Milk and milk products.
:toc:

== 15.36.002 - Intent.
This chapter is intended to enact state legislation that safeguards the public health and promotes public welfare by: (1) Protecting the consuming public from milk or milk products that are: (a) Unsafe; (b) produced under unsanitary conditions; (c) do not meet bacterial standards under the PMO; or (d) below the quality standards under Title 21 C.F.R. or administrative rules and orders adopted under this chapter; and (2) requiring licensing of all aspects of the dairy production and processing industry.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6096-S.SL.pdf?cite=1994%20c%20143%20§%20101[1994 c 143 § 101]; ]

== 15.36.012 - Definitions.
For the purpose of this chapter:

"Adulterated milk" means milk that is deemed adulterated under appendix L of the PMO.

"Colostrum milk" means milk produced within ten days before or until practically colostrum free after parturition.

"DMO" means supplement I, the recommended sanitation ordinance for grade A condensed and dry milk products and condensed and dry whey, to the PMO published by the United States public health service, food and drug administration.

"Dairy farm" means a place or premises where one or more cows, goats, or other mammals are kept, a part or all of the milk or milk products from which is sold or offered for sale.

"Dairy technician" means any person who takes samples of milk or cream or fluid derivatives thereof, on which sample tests are to be made as a basis of payment, or who grades, weighs, or measures milk or cream or the fluid derivatives thereof, the grade, weight, or measure to be used as a basis of payment, or who operates equipment wherein milk or products thereof are pasteurized.

"Degrade" means the lowering in grade from grade A to grade C.

"Department" means the state department of agriculture.

"Director" means the director of agriculture of the state of Washington or the director's duly authorized representative.

"Grade A milk processing plant" means any milk processing plant that meets all of the standards of the PMO to process grade A pasteurized milk or milk products.

"Grade A pasteurized milk" means grade A raw milk that has been pasteurized.

"Grade A raw milk" means raw milk produced upon dairy farms conforming with all of the items of sanitation contained in the PMO, in which the bacterial plate count does not exceed twenty thousand per milliliter and the coliform count does not exceed ten per milliliter as determined in accordance with RCW 15.36.201.

"Grade A raw milk for pasteurization" means raw milk produced upon dairy farms conforming with all of the same items of sanitation contained in the PMO of grade A raw milk, and the bacterial plate count, as delivered from the farm, does not exceed eighty thousand per milliliter as determined in accordance with RCW 15.36.201.

"Grade C milk" is milk that violates any of the requirements for grade A milk but that is not deemed to be adulterated.

"Milk" means the lacteal secretion, practically free of colostrum, obtained by the complete milking of one or more healthy cows, goats, or other mammals.

"Milk hauler" means a person who transports milk or milk products in bulk to or from a milk processing plant, receiving station, or transfer station.

"Milk processing" means the handling, preparing, packaging, or processing of milk in any manner in preparation for sale as food, as defined in chapter 15.130 RCW. Milk processing does not include milking or producing milk on a dairy farm that is shipped to a milk processing plant for further processing.

"Milk processing plant" means a place, premises, or establishment where milk or milk products are collected, handled, processed, stored, bottled, pasteurized, aseptically processed, bottled, or prepared for distribution, except an establishment that merely receives the processed milk products and serves them or sells them at retail.

"Milk products" means the product of a milk manufacturing process.

"Misbranded milk" means milk or milk products that carries a grade label unless such grade label has been awarded by the director and not revoked, or that fails to conform in any other respect with the statements on the label.

"Official laboratory" means a biological, chemical, or physical laboratory that is under the direct supervision of the state or a local regulatory agency.

"Officially designated laboratory" means a commercial laboratory authorized to do official work by the department, or a milk industry laboratory officially designated by the department for the examination of grade A raw milk for pasteurization and commingled milk tank truck samples of raw milk for antibiotic residues and bacterial limits.

"PMO" means the grade "A" pasteurized milk ordinance published by the United States public health service, food and drug administration.

"Pasteurized" means the process of heating every particle of milk or milk product in properly designed and operated equipment to the temperature and time standards specified in the PMO.

"Person" means an individual, partnership, firm, corporation, company, trustee, or association.

"Producer" means a person or organization who operates a dairy farm and provides, sells, or offers milk for sale.

"Receiving station" means a place, premises, or establishment where raw milk is received, collected, handled, stored, or cooled and prepared for further transporting.

"Sale" means selling, offering for sale, holding for sale, preparing for sale, distributing, dispensing, delivering, supplying, trading, bartering, offering a gift as an inducement for sale of, and advertising for sale in any media.

"Transfer station" means any place, premises, or establishment where milk or milk products are transferred directly from one milk tank truck to another.

"Wash station" means a place, facility, or establishment where milk tanker trucks are cleaned in accordance with the standards of the PMO.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20702[2018 c 236 § 702]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6377-S.SL.pdf?cite=2006%20c%20157%20§%202[2006 c 157 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%201[1999 c 291 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5315-S.SL.pdf?cite=1995%20c%20374%20§%201[1995 c 374 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6096-S.SL.pdf?cite=1994%20c%20143%20§%20102[1994 c 143 § 102]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%201[1989 c 354 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.32.010[1961 c 11 § 15.32.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c238.pdf?cite=1955%20c%20238%20§%2071[1955 c 238 § 71]; prior:  1943 c 90 § 1, part; 1933 c 188 § 1, part; 1929 c 213 § 1, part; 1927 c 192 § 1, part; 1919 c 192 § 1, part; Rem. Supp. 1943 § 6164, part.  1929 c 213 § 6, part; 1927 c 192 § 16, part; 1921 c 104 § 3, part; 1919 c 192 § 41, part; RRS § 6203, part; ]

== 15.36.021 - Milk and milk products—Rule-making authority—Grade A pasteurized and raw milk—Grade C milk and milk products.
The director of agriculture is authorized to:

. Adopt rules necessary to carry out the purposes of chapter 15.36 RCW, which includes rules governing the farm storage tank and bulk milk tanker requirements, however the rules may not restrict the display or promotion of products covered under this section.

. By rule, establish, amend, or both, definitions and standards for milk and milk products. Such definitions and standards established by the director shall conform, insofar as practicable, with the definitions and standards for milk and milk products adopted by the federal food and drug administration.

. By rule, adopt the PMO, DMO, and supplemental documents by reference to establish requirements for grade A pasteurized and grade A raw milk.

. Adopt rules establishing standards for grade A pasteurized and grade A raw milk that are more stringent than the PMO based upon current industry or public health information for the enforcement of this chapter whenever he or she determines that any such rules are necessary to carry out the purposes of this section and RCW 15.36.481.

. By rule, certify an officially designated laboratory to analyze milk for standard of quality, adulteration, contamination, and unwholesomeness.

. Adopt rules setting standards and requirements for the production of grade C milk and milk products.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%202[1999 c 291 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2132.SL.pdf?cite=1996%20c%20188%20§%203[1996 c 188 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6096-S.SL.pdf?cite=1994%20c%20143%20§%20103[1994 c 143 § 103]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2013[1989 c 354 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c102.pdf?cite=1969%20ex.s.%20c%20102%20§%201[1969 ex.s. c 102 § 1]; ]

== 15.36.025 - Application of chapter  34.05 RCW.
Chapter 34.05 RCW governs the rights, remedies, and procedures respecting the administration of this chapter, including rule making, assessment of civil penalties, emergency actions, and license suspension, revocation, or denial.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%203[1999 c 291 § 3]; ]

== 15.36.041 - Milk producer's license.
Every milk producer must obtain a milk producer's license to operate as a milk producer as defined in this chapter. A milk producer's license is not transferable with respect to persons or locations or both. The license, issued by the director upon approval of an application for the license and compliance with the provisions of this chapter, shall contain the license number, name, residence, and place of business, if any, of the licensee.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6096-S.SL.pdf?cite=1994%20c%20143%20§%20202[1994 c 143 § 202]; ]

== 15.36.051 - Milk processing plant license—Fee waiver.
. A milk processing plant must obtain an annual milk processing plant license from the department, which shall expire on June 30th of each year. A milk processing plant may choose to process: (a) Grade A milk and milk products; or (b) other milk products that are not classified grade A.

. Only one license may be required to process milk; however, milk processing plants must obtain the necessary endorsements from the department in order to process products as defined for each type of milk or milk product processing. Application for a license shall be on a form prescribed by the director and accompanied by a two hundred fifty dollar annual license fee beginning July 1, 2015. The applicant shall include on the application the full name of the applicant for the license and the location of the milk processing plant he or she intends to operate and any other necessary information. Upon the approval of the application by the director and compliance with the provisions of this chapter, including the applicable rules adopted under this chapter by the department, the applicant shall be issued a license or a renewal of a license.

. Licenses shall be issued to cover only those products, processes, and operations specified in the license application and approved for licensing. If a license holder wishes to engage in processing a type of milk product that is different than the type specified on the application supporting the licensee's existing license and processing that type of food product would require a major addition to or modification of the licensee's processing facilities, the licensee shall submit an amendment to the current license application. In such a case, the licensee may engage in processing the new type of milk product only after the amendment has been approved by the department.

. A licensee under this section shall not be required to obtain a food processing plant license under chapter 69.07 RCW to process milk or milk products.

. The director shall waive the fee for a food processing license under chapter 69.07 RCW for persons who are also licensed as a milk processing plant.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2128-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2027%20§%202[2015 3rd sp.s. c 27 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5039.SL.pdf?cite=2005%20c%20414%20§%201[2005 c 414 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%204[1999 c 291 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6096-S.SL.pdf?cite=1994%20c%20143%20§%20203[1994 c 143 § 203]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=1991%20c%20109%20§%202[1991 c 109 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.32.110[1961 c 11 § 15.32.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c192.pdf?cite=1927%20c%20192%20§%2011[1927 c 192 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c27.pdf?cite=1923%20c%2027%20§%208[1923 c 27 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c192.pdf?cite=1919%20c%20192%20§%2029[1919 c 192 § 29]; RRS § 6192.   1919 c 192 § 33; RRS § 6195; ]

== 15.36.071 - Milk hauler's license—Endorsements.
A milk hauler must obtain a milk hauler's license to conduct the operation under this chapter. A milk hauler's license is not transferable with respect to persons or locations or both. The license, issued by the director upon approval of an application for the license and compliance with the provisions of this chapter, shall contain the license number, name, residence, and place of business, if any, of the licensee. A milk hauler's license shall also contain endorsements for individual milk transport vehicles. The license plate number and registration number for each milk transport vehicle shall be listed on the endorsement.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5315-S.SL.pdf?cite=1995%20c%20374%20§%202[1995 c 374 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6096-S.SL.pdf?cite=1994%20c%20143%20§%20205[1994 c 143 § 205]; ]

== 15.36.081 - Dairy technician's license—Application—Renewal—Fees.
. A dairy technician must obtain a dairy technician's license to conduct operations under this chapter. Such license shall be limited to those functions which the licensee has been found qualified to perform. Before issuing the license the director shall assess the applicant's qualifications and may test the applicant for the functions for which application has been made.

. Application for a license as a dairy technician shall be made upon forms provided by the director, and shall be filed with the department. The director may issue a temporary license to the applicant for such period as may be prescribed and stated in the license, not to exceed sixty days, but the license may not be renewed to extend the period beyond sixty days.

. The initial application and renewal for a dairy technician's license must be accompanied by a license fee of twenty-five dollars beginning July 1, 2015. All dairy technicians' licenses shall expire on December 31st of odd-numbered years.

. The initial application for any endorsement beyond a dairy technician's license must be accompanied by an endorsement fee of twenty-five dollars beginning July 1, 2015.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2128-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2027%20§%203[2015 3rd sp.s. c 27 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%205[1999 c 291 § 5]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6096-S.SL.pdf?cite=1994%20c%20143%20§%20206[1994 c 143 § 206]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c58.pdf?cite=1963%20c%2058%20§%206[1963 c 58 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.32.580[1961 c 11 § 15.32.580]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c90.pdf?cite=1943%20c%2090%20§%204[1943 c 90 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c192.pdf?cite=1927%20c%20192%20§%208[1927 c 192 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c27.pdf?cite=1923%20c%2027%20§%207[1923 c 27 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c192.pdf?cite=1919%20c%20192%20§%2026[1919 c 192 § 26]; Rem. Supp. 1943 § 6189; ]

== 15.36.091 - Dairy technician's license—Records—Inspection of.
Licensed dairy technicians shall personally take all samples, conduct all tests, and determine all weights and grades of milk and milk products bought, sold, or delivered upon the basis of weight or grade or on the basis of the milk fat, nonfat milk solids, or other components contained therein. Each licensee shall keep a copy of every original report of each test, weight, or grade made by him or her for a period of two months after making the report. No unfair, fraudulent, or manipulated sample shall be taken or delivered for analysis.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6096-S.SL.pdf?cite=1994%20c%20143%20§%20207[1994 c 143 § 207]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c58.pdf?cite=1963%20c%2058%20§%209[1963 c 58 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.32.590[1961 c 11 § 15.32.590]; 1927 c 192 § 7, part; 1923 c 27 § 6, part; 1919 c 192 § 25, part; RRS § 6188, part; ]

== 15.36.101 - Milk wash station license.
A wash station operator must obtain a milk wash station license to conduct the operation under this chapter for all wash stations separate from a milk processing plant. A milk wash station license is not transferable with respect to persons or locations or both. The license, issued by the director upon approval of an application for such license and compliance with the provisions of this chapter, shall contain the license number, name, residence, and place of business, if any, of the licensee.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6096-S.SL.pdf?cite=1994%20c%20143%20§%20208[1994 c 143 § 208]; ]

== 15.36.111 - Inspection of dairy farms and milk processing plants—Violations—Director's access.
. The director shall inspect all dairy farms and all milk processing plants prior to issuance of a license under this chapter and at a frequency determined by the director by rule: PROVIDED, That the director may accept the results of periodic industry inspections of producer dairies if such inspections have been officially checked periodically and found satisfactory. In case the director discovers the violation of any item of grade requirement, he or she shall make a second inspection after a lapse of such time as he or she deems necessary for the defect to be remedied, but not before the lapse of three days, and the second inspection shall be used in determining compliance with the grade requirements of this chapter. Whenever there is any violation of the same requirement of this chapter on the second inspection, the director may initiate proceedings to degrade, suspend the license, or assess a civil penalty.

. One copy of the inspection report detailing the grade requirement violations shall be posted by the director in a conspicuous place upon an inside wall of the milk tank room or a mutually agreed upon location on a dairy farm or given to an operator of the milk processing plant, and said inspection report shall not be defaced or removed by any person except the director. Another copy of the inspection report shall be filed with the records of the director.

. Every milk producer and milk processing plant shall permit the director access to all parts of the establishment during the working hours of the producer or milk processing plant, which shall at a minimum include the hours from 8 a.m. to 5 p.m., and every milk processing plant shall furnish the director, upon his or her request, for official use only, samples of any milk product for laboratory analysis, and a true statement of the actual quantities of milk and milk products of each grade purchased and sold.

. The director shall have access to all parts of a dairy farm or facility that is not licensed as a milk producer or milk processing plant if the director has information that the dairy farm or facility is engaged in activities that require a license under this chapter. The director shall have access during the working hours of the dairy farm or facility, which shall at a minimum include the hours from 8 a.m. to 5 p.m. The director shall have the authority to take samples of milk or any milk products and water and environmental samples for laboratory analysis. For all establishments subject to this subsection and subsection (3) of this section, the director shall have access to records including, but not limited to, customer lists, milk production records, temperature records, and records of inspections and tests.

. If the director is denied access to a dairy farm or milk processing plant, the director may apply to a court of competent jurisdiction for a search warrant authorizing access to the property and facilities for purposes of conducting tests and inspections, taking samples, and examining records. To show that access is denied, the director shall file with the court an affidavit or declaration containing a description of his or her attempts to notify and locate the owner or the owner's agent and to secure consent. Upon application, the court may issue a search warrant for the purposes requested.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6377-S.SL.pdf?cite=2006%20c%20157%20§%203[2006 c 157 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%206[1999 c 291 § 6]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2134.SL.pdf?cite=1996%20c%20189%20§%201[1996 c 189 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6096-S.SL.pdf?cite=1994%20c%20143%20§%20209[1994 c 143 § 209]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.36.100[1961 c 11 § 15.36.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c168.pdf?cite=1949%20c%20168%20§%205[1949 c 168 § 5]; Rem. Supp. 1949 § 6266-34; ]

== 15.36.131 - Sale of out-of-state grade A milk and milk products.
Grade A milk and milk products from outside the state may not be sold in the state of Washington unless produced and/or pasteurized under provisions equivalent to the requirements of this chapter and the PMO: PROVIDED, That the director shall satisfy himself or herself that the authority having jurisdiction over the production and processing is properly enforcing such provisions.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6096-S.SL.pdf?cite=1994%20c%20143%20§%20211[1994 c 143 § 211]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.36.500[1961 c 11 § 15.36.500]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c168.pdf?cite=1949%20c%20168%20§%2011[1949 c 168 § 11]; Rem. Supp. 1949 § 6266-39; ]

== 15.36.141 - Grading of milk and milk products.
Grades of milk and milk products as defined in this chapter shall be based on the respectively applicable standards contained in this chapter, with the grading of milk products being identical with the grading of milk, except that bacterial standards are omitted in the case of cultured milk products. Vitamin D milk shall be only of grade A, certified pasteurized, or certified raw quality. The grade of a milk product shall be that of the lowest grade milk or milk product used in its preparation.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6096-S.SL.pdf?cite=1994%20c%20143%20§%20510[1994 c 143 § 510]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c226.pdf?cite=1984%20c%20226%20§%203[1984 c 226 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c297.pdf?cite=1981%20c%20297%20§%202[1981 c 297 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.36.120[1961 c 11 § 15.36.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c238.pdf?cite=1955%20c%20238%20§%2012[1955 c 238 § 12]; prior: 1949 c 168 § 7, part; Rem. Supp. 1949 § 6266-36, part; ]

== 15.36.151 - Unlawful to sell, offer for sale, or deliver certain products—Diseased animals—Colostrum—Exceptions.
It is unlawful to sell, offer for sale, or deliver:

. Milk or products produced from milk from cows, goats, or other mammals affected with disease or of which the owner thereof has refused official examination and tests for disease; or

. Colostrum milk for consumption by humans, except that this prohibition regarding colostrum milk does not apply to:

.. Colostrum milk made or to be made available to persons having multiple sclerosis, or other persons acting on their behalf, who, at the time of the initial sale, present a form, signed by a licensed physician, certifying that the intended user has multiple sclerosis and that the user releases the provider of the milk from liability resulting from the consumption of the milk; or

.. Colostrum milk processed or to be processed by a licensed food processing facility or a milk processing plant as a nutritional supplement in accordance with the federal dietary supplement health and education act. Colostrum milk used for this purpose must be pasteurized or otherwise subjected to a heat process or other treatment sufficient to kill harmful organisms.

Colostrum milk described in subsection (2)(a) or (b) of this section is exempt from the prohibition provided by subsection (2) of this section if it comes from a licensed producer. Such colostrum milk is also exempt from meeting the standards for grade A raw milk required by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2628-S.SL.pdf?cite=2000%20c%2097%20§%201[2000 c 97 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%207[1999 c 291 § 7]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6096-S.SL.pdf?cite=1994%20c%20143%20§%20303[1994 c 143 § 303]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c321.pdf?cite=1981%20c%20321%20§%201[1981 c 321 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.32.160[1961 c 11 § 15.32.160]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c213.pdf?cite=1929%20c%20213%20§%209[1929 c 213 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c192.pdf?cite=1919%20c%20192%20§%2049[1919 c 192 § 49]; RRS § 6211; ]

== 15.36.161 - Cows, goats, and other mammals—Animal health requirements.
. All milking cows, goats, and other mammals must meet the animal health requirements established by the state veterinarian under the authority of chapter 16.36 RCW.

. Milk or milk products from cows, goats, and other mammals intended for consumption in the raw state must be from a herd which is tested negative within the previous twelve months for brucellosis, tuberculosis, and any other disease the director may designate by rule. Additions to the herd must be tested negative for the diseases within the previous thirty days before introduction into the herd. The state veterinarian shall direct all testing procedures in accordance with state and national standards for animal disease eradication.

. Cows, goats, and other mammals showing chronic mastitis, whether producing abnormal milk or not, shall be permanently excluded from the milking herd. Cows, goats, and other mammals producing bloody, stringy, or otherwise abnormal milk, but with only slight inflammation of the udder shall be excluded from the herd until reexamination shows that the milk has become normal.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%208[1999 c 291 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c131.pdf?cite=1982%20c%20131%20§%202[1982 c 131 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.36.150[1961 c 11 § 15.36.150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c238.pdf?cite=1955%20c%20238%20§%2015[1955 c 238 § 15]; prior: 1949 c 168 § 7, part; Rem. Supp. 1949 § 6266-36, part; ]

== 15.36.171 - Grades of milk and milk products that may be sold.
The director may revoke the license of any milk processing plant or producer whose product fails to qualify as grade A pasteurized or grade A raw, or in lieu thereof may degrade the product to grade C and permit its sale as other than fluid milk or grade A milk products during a period not exceeding thirty days. In the event of an emergency, the director may permit the sale of grade C milk for more than thirty days.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%209[1999 c 291 § 9]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5315-S.SL.pdf?cite=1995%20c%20374%20§%203[1995 c 374 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6096-S.SL.pdf?cite=1994%20c%20143%20§%20301[1994 c 143 § 301]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2022[1989 c 354 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.36.470[1961 c 11 § 15.36.470]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c168.pdf?cite=1949%20c%20168%20§%208[1949 c 168 § 8]; Rem. Supp. 1949 § 6266-37; ]

== 15.36.181 - Sale of adulterated or misbranded milk or milk products prohibited—Possession restricted.
No person shall produce, sell, offer, or expose for sale, or have in possession with intent to sell, any milk or milk product which is adulterated or misbranded. It is unlawful for any person, elsewhere than in a private home, to have in possession any adulterated or misbranded milk or milk products.

Adulterated or misbranded milk or milk products may be impounded and disposed of by the director.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%2010[1999 c 291 § 10]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6096-S.SL.pdf?cite=1994%20c%20143%20§%20302[1994 c 143 § 302]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.36.070[1961 c 11 § 15.36.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c168.pdf?cite=1949%20c%20168%20§%202[1949 c 168 § 2]; Rem. Supp. 1949 § 6266-31; ]

== 15.36.191 - Milk or milk product analysis—Report of violative results.
After obtaining a sample of milk or milk product for analysis, the department shall, within ten days of obtaining the result of the analysis, send any violative results to the person from whom the sample was taken or to the person responsible for the condition of the milk.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%2011[1999 c 291 § 11]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6096-S.SL.pdf?cite=1994%20c%20143%20§%20304[1994 c 143 § 304]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2011[1989 c 354 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.32.530[1961 c 11 § 15.32.530]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c234.pdf?cite=1907%20c%20234%20§%2012[1907 c 234 § 12]; RRS § 6278; ]

== 15.36.201 - Examination of milk and milk products—Violations—Director's options—Penalty.
. During any consecutive six-month period, at least four samples of: (a) Either raw milk or raw milk for pasteurization, or both, from each milk producer; or (b)(i) raw milk for pasteurization after receipt by the milk processing plant and prior to pasteurization; (ii) heat-treated milk products; and (iii) pasteurized milk and milk products from each milk processing plant shall be collected and examined in an official laboratory to determine compliance with bacteriological or cooling temperature standards for milk or milk products established in this chapter and rules adopted under this chapter. However, in the case of raw milk for pasteurization, the director may accept the results of an officially designated laboratory.

. If a bacterial count, somatic cell count, coliform determination, or cooling temperature exceeds the standard, the director shall send written notice to the milk producer or milk processor. The director may initiate proceedings to degrade or suspend the milk producer's license or milk processing plant license and may assess a civil penalty whenever the standard is again violated.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5139.SL.pdf?cite=2013%20c%207%20§%201[2013 c 7 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%2012[1999 c 291 § 12]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6096-S.SL.pdf?cite=1994%20c%20143%20§%20401[1994 c 143 § 401]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6463-S.SL.pdf?cite=1994%20c%2046%20§%2011[1994 c 46 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2017[1989 c 354 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c297.pdf?cite=1981%20c%20297%20§%201[1981 c 297 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.36.110[1961 c 11 § 15.36.110]; prior:  1955 c 238 § 10; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c168.pdf?cite=1949%20c%20168%20§%206[1949 c 168 § 6]; Rem. Supp. 1949 § 6266-35; ]

== 15.36.206 - Source of milk and milk products—Seller's disclosure.
Any person selling milk or milk products shall furnish the director, upon request, with the name of all milk processing plants or distributors from whom their milk and milk products are obtained.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%2013[1999 c 291 § 13]; ]

== 15.36.221 - Grade A raw milk—Cooling.
Milk and milk products for consumption in the raw state or for pasteurization shall be cooled within two hours of completion of milking to forty degrees Fahrenheit or less and maintained at that temperature until picked up, in accordance with RCW 15.36.201, so long as the blend temperature after the first and following milkings does not exceed fifty degrees Fahrenheit.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5315-S.SL.pdf?cite=1995%20c%20374%20§%204[1995 c 374 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c226.pdf?cite=1984%20c%20226%20§%205[1984 c 226 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.36.260[1961 c 11 § 15.36.260]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c238.pdf?cite=1955%20c%20238%20§%2037[1955 c 238 § 37]; prior: 1949 c 168 § 7, part; Rem. Supp. 1949 § 6266-36, part; ]

== 15.36.231 - Raw milk or milk products—Bottling and capping—Packaging—Labeling.
. Milk and milk products for consumption in the raw state shall be bottled or packaged on the farm where produced. Bottling and capping shall be done in a sanitary manner by means of approved equipment and operations. Caps or cap stock shall be purchased in sanitary containers and kept therein in a clean dry place until used.

. All containers enclosing raw milk or any raw milk product shall be plainly labeled or marked with the word "raw" and the name of the producer or packager. The label or mark shall be in letters of a size, kind, and color approved by the director and shall contain no marks or words which are misleading.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5039.SL.pdf?cite=2005%20c%20414%20§%202[2005 c 414 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%2014[1999 c 291 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.36.265[1961 c 11 § 15.36.265]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c238.pdf?cite=1955%20c%20238%20§%2038[1955 c 238 § 38]; prior: 1949 c 168 § 7, part; Rem. Supp. 1949 § 6266-36, part; ]

== 15.36.241 - Capping of milk or milk products.
Capping of milk or milk products shall be done in a sanitary manner by means of approved equipment and operations. The cap or cover shall cover the pouring lip to at least its largest diameter.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5039.SL.pdf?cite=2005%20c%20414%20§%203[2005 c 414 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.36.420[1961 c 11 § 15.36.420]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c238.pdf?cite=1955%20c%20238%20§%2064[1955 c 238 § 64]; prior: 1949 c 168 § 7, part; Rem. Supp. 1949 § 6266-36, part; ]

== 15.36.261 - Butter or cheese—Pasteurization of milk or cream.
All milk or cream used in the manufacture of pasteurized butter or cheese shall be pasteurized only in the plant where the butter or cheese is manufactured.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.32.410[1961 c 11 § 15.32.410]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c192.pdf?cite=1919%20c%20192%20§%2012[1919 c 192 § 12]; RRS § 6175; ]

== 15.36.271 - "Pasteurized"—Use of word regulated.
No person shall use the word "pasteurized" in connection with the sale, designation, advertising, labeling, or billing of milk, cream, or any milk product unless the same and all milk products used in the manufacture thereof consist exclusively of milk, skimmed milk, or cream that has been pasteurized in its final form.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%207[1989 c 354 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.32.420[1961 c 11 § 15.32.420]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c192.pdf?cite=1919%20c%20192%20§%2071[1919 c 192 § 71]; RRS § 6233; ]

== 15.36.281 - Unlawful use of containers—Seizure authorized.
. It shall be unlawful for a person other than the owner, to possess for sale or barter or to use a container that is used to distribute packaged milk or milk products and that bears the name or trademark of an owner that has been properly registered.

. A person receiving packaged dairy products in containers bearing the registered name or trademark of the owner shall return the containers to the owner.

. When such a container is in the possession of a person other than the owner, the director may seize and hold it until it is established to the director's satisfaction that such possession is lawful. The director may seize such containers and return them to the owner, in which case the owner shall pay the expenses thereof. Neither the director nor a person who returns such containers shall be liable for containers lost in transportation.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6096-S.SL.pdf?cite=1994%20c%20143%20§%20508[1994 c 143 § 508]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.32.450[1961 c 11 § 15.32.450]; 1927 c 192 § 22, part; 1923 c 27 § 12, part; 1919 c 192 § 86, part; 1915 c 101 § 1, part; RRS § 6259, part.   1915 c 101 § 3; RRS § 6261. (iii)  1927 c 192 § 22a; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c101.pdf?cite=1915%20c%20101%20§%204[1915 c 101 § 4]; RRS § 6262. (iv)  1927 c 192 § 22b; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c101.pdf?cite=1915%20c%20101%20§%205[1915 c 101 § 5]; RRS § 6263; ]

== 15.36.401 - Licenses—Denial, suspension, revocation—Reasons.
. A license issued under this chapter may be denied, suspended, or revoked by the director when a person:

.. Fails to comply with the provisions of this chapter or the rules adopted under this chapter;

.. Refuses the department access to a portion or area of a facility regulated under this chapter, for the purpose of carrying out the provisions of this chapter;

.. Fails to comply with an order of the director;

.. Refuses to make available to the department records required to be kept under the provisions of this chapter;

.. Fails to comply with the applicable provisions of chapter 15.130 RCW, *Washington intrastate commerce in food, drugs, and cosmetics act, or rules adopted under that chapter;

.. Interferes with the director in the performance of his or her duties; or

.. Exhibits negligence, misconduct, or lack of qualification in the discharge of his or her functions.

Upon notice by the director to deny, revoke, or suspend a license, a person may request a hearing under chapter 34.05 RCW.

. Whenever a milk transport vehicle is found in violation of this chapter or rules adopted under this chapter, the endorsement for that milk transport vehicle contained on a milk hauler's license may be suspended or revoked. The suspension or revocation does not apply to any other milk transport vehicle operated by the milk hauler.

. A license may be revoked by the director upon serious or repeated violations or after a license suspension or degrade for thirty continuous days without correction of the items causing the suspension or degrade.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20703[2018 c 236 § 703]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%2015[1999 c 291 § 15]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6096-S.SL.pdf?cite=1994%20c%20143%20§%20501[1994 c 143 § 501]; ]

== 15.36.412 - Issuance of cease and desist order.
The director may issue a cease and desist order to any person whom the director has reason to believe is engaged in an activity for which a license is required by this chapter. The person to whom such notice is issued may request an adjudicative proceeding to contest the order.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6377-S.SL.pdf?cite=2006%20c%20157%20§%205[2006 c 157 § 5]; ]

== 15.36.421 - Milk processing plant or producer—License suspension.
. If the director finds a milk processing plant or producer operating under conditions that constitute an immediate danger to public health, safety, or welfare or if the licensee or an employee of the licensee actively prevents the director or the director's representative, during an on-site inspection, from determining whether such a condition exists, the director may summarily suspend a license provided for in this chapter.

. If a license is summarily suspended, the holder of the license shall be notified in writing that the license is, upon service of the notice, immediately suspended and that prompt opportunity for a hearing will be provided.

. If a license is summarily suspended, processing and shipping operations shall immediately cease. However, the director may reinstate the license if the condition that caused the suspension has been abated to the director's satisfaction.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%2016[1999 c 291 § 16]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6096-S.SL.pdf?cite=1994%20c%20143%20§%20503[1994 c 143 § 503]; ]

== 15.36.451 - Regrading of milk or milk products—Reinstatement of license.
Any producer or milk processing plant whose milk has been degraded by the director, or whose license has been suspended may at any time make application for the regrading of his or her products or the reinstatement of his or her license.

In case the lowered grade or the license suspension was the result of violation of the bacteriological or cooling temperature standards, the director may take further samples of the applicant's output, at a rate of not more than two samples per week. The director shall regrade the milk or milk products upward or reinstate the license on compliance with grade requirements as determined in accordance with the provisions of RCW 15.36.201.

In case the lowered grade of the applicant's product or the license suspension was due to a violation of an item other than bacteriological standard or cooling temperature, the said application must be accompanied by a statement signed by the applicant to the effect that the violated item of the specifications had been conformed with. Within one week of the receipt of such an application and statement the director shall make a reinspection of the applicant's establishment and thereafter as many additional reinspections as he or she may deem necessary to assure himself or herself that the applicant is again complying with the higher grade requirements. The higher grade or license shall be reinstated upon confirmation that all violated items are corrected and any period for reduction in grade or license suspensions as ordered by the director has been completed.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5139.SL.pdf?cite=2013%20c%207%20§%202[2013 c 7 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%2017[1999 c 291 § 17]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2134.SL.pdf?cite=1996%20c%20189%20§%202[1996 c 189 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6096-S.SL.pdf?cite=1994%20c%20143%20§%20506[1994 c 143 § 506]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.36.480[1961 c 11 § 15.36.480]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c168.pdf?cite=1949%20c%20168%20§%209[1949 c 168 § 9]; Rem. Supp. 1949 § 6266-37a; ]

== 15.36.454 - Failure to comply with chapter or rules—Civil penalties.
. Any person who fails to comply with this chapter or the rules adopted under this chapter may be subject to a civil penalty in an amount of not more than one thousand dollars per violation per day.

. The director may adopt by rule a penalty matrix that establishes procedures for civil penalties assessed under this chapter.

. Whenever the results of an antibiotic, pesticide, or other drug residue test on a producer's milk are above the actionable level established in the PMO, the producer is subject to a civil penalty under this section in addition to any other action taken under this chapter.

. The director may impose a civil penalty under this section for violations of the standards for component parts of fluid dairy products that are established in this chapter or rules adopted under this chapter.

. Each violation is a separate and distinct offense. The director shall impose the civil penalty in accordance with chapter 34.05 RCW. Moneys collected under this section shall be remitted to the department and deposited into the revolving fund of the Washington state dairy products commission.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5139.SL.pdf?cite=2013%20c%207%20§%203[2013 c 7 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%2018[1999 c 291 § 18]; ]

== 15.36.455 - Violations—Notice, orders, damages.
. When the director has probable cause to believe that milk or milk products are being sold, distributed, stored, or transported in violation of this chapter or rules adopted under this chapter, the director may issue and serve upon the owner or custodian of the milk or milk products a written notice of embargo and order prohibiting the sale of the milk or milk products. If the owner or custodian is not available for service, the director may attach the notice of embargo and order prohibiting sale to the container holding the milk or milk products. The milk or milk products shall not be sold, used, or removed until this chapter has been complied with and the milk or milk products have been released from embargo under conditions specified by the director in writing.

. The department may issue a destruction and disposal order covering any embargoed milk or milk products. The destruction and disposal shall occur at the cost of the owner or custodian.

. The person to whom the notice of embargo and order prohibiting sale was issued or the person to whom a destruction or disposal order was issued may request an adjudicative proceeding to contest the order.

. A state court shall not allow the recovery of damages from an administrative action under this section if the court finds there was probable cause for the action.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6377-S.SL.pdf?cite=2006%20c%20157%20§%206[2006 c 157 § 6]; ]

== 15.36.473 - Failure to comply with chapter or rules—Criminal penalties.
. It is unlawful for any person to sell raw milk from a dairy farm that is not licensed as a milk producer or a milk processing plant under this chapter.

. The sale of raw milk from a dairy farm that is not licensed as a milk producer and a milk processing plant under this chapter constitutes:

.. For the first offense, a misdemeanor; and

.. For the second and subsequent offenses, a gross misdemeanor punishable according to chapter 9A.20 RCW.

. Neither the issuance of a cease and desist order nor payment of a civil penalty relieves the person so selling raw milk from criminal prosecution, but the remedy of a cease and desist order or civil penalty is in addition to any criminal liability.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6377-S.SL.pdf?cite=2006%20c%20157%20§%207[2006 c 157 § 7]; ]

== 15.36.475 - Laboratory tests—Admission as evidence.
Tests performed by an official laboratory or an officially designated laboratory of a milk sample drawn by a department official or a licensed dairy technician shall be admitted as prima facie evidence of a violation in any proceeding to enforce this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%2021[1999 c 291 § 21]; ]

== 15.36.481 - Violations may be enjoined.
The director may bring an action to enjoin the violation of any provision of this chapter or any rule adopted under this chapter in the superior court of the county in which the defendant resides or maintains his or her principal place of business or Thurston county.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%2022[1999 c 291 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c102.pdf?cite=1969%20ex.s.%20c%20102%20§%204[1969 ex.s. c 102 § 4]; ]

== 15.36.491 - Licenses—Money deposited in the agricultural local fund.
All moneys received for licenses under this chapter shall be deposited in the agricultural local fund established under RCW 43.23.230.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2128-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2027%20§%204[2015 3rd sp.s. c 27 § 4]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5039.SL.pdf?cite=2005%20c%20414%20§%204[2005 c 414 § 4]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%2023[1999 c 291 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.32.710[1961 c 11 § 15.32.710]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1899c43.pdf?cite=1899%20c%2043%20§%2027[1899 c 43 § 27]; RRS § 6249; ]

== 15.36.511 - Unlawful actions.
. It is unlawful for any person to:

.. Interfere with or obstruct any person in the performance of official duties under this chapter;

.. Employ a tester, sampler, weigher, grader, or pasteurizer who is not licensed as a dairy technician;

.. Alter or tamper with a seal placed by the director;

.. Alter or tamper with a sample of milk or milk products taken or sealed by the director; or

.. Operate as a milk producer or milk processing plant without obtaining a license from the director.

. Except as provided under RCW 15.36.131, it is unlawful for a milk processing plant to accept milk from a person not licensed as a producer or milk processor.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6377-S.SL.pdf?cite=2006%20c%20157%20§%204[2006 c 157 § 4]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%2024[1999 c 291 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.32.730[1961 c 11 § 15.32.730]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c192.pdf?cite=1919%20c%20192%20§%2076[1919 c 192 § 76]; RRS § 6238; ]

== 15.36.525 - Sanitary certificates—Rules—Fee for issuance.
The department may issue sanitary certificates to milk processing plants under this chapter subject to such requirements as it may establish by rule. The fee for issuance is seventy-five dollars per certificate beginning July 1, 2015. Fees collected under this section shall be deposited in the agricultural local fund.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2128-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2027%20§%205[2015 3rd sp.s. c 27 § 5]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%2025[1999 c 291 § 25]; ]

== 15.36.531 - Declaration of police power.
It is hereby declared that this chapter is enacted as an exercise of the police power of the state of Washington for the preservation of the public health and each and every section thereof shall be construed as having been intended to effect such purpose and not as having been intended to affect any regulation or restraint of commerce between the several states which may by the Constitution of the United States of America have been reserved to the congress thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.32.900[1961 c 11 § 15.32.900]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c192.pdf?cite=1919%20c%20192%20§%2083[1919 c 192 § 83]; RRS § 6245; ]

== 15.36.541 - Chapter cumulative.
Nothing in this chapter shall be construed as affecting or being intended to effect a repeal of chapter 15.130 RCW or RCW 69.40.010 through 69.40.025, or of any of such sections, or of any part or provision of any such sections, and if any section or part of a section in this chapter shall be found to contain, cover or effect any matter, topic or thing which is also contained in, covered in or effected by said sections, or by any of them, or by any part thereof, the prohibitions, mandates, directions, and regulations hereof, and the penalties, powers and duties herein prescribed shall be construed to be additional to those prescribed in such sections and not in substitution therefor. And nothing in this chapter shall be construed to forbid the importation, transportation, manufacture, sale, or possession of any article of food which is not prohibited from interstate commerce by the laws of the United States or rules or regulations lawfully made thereunder, if there be a standard of quality, purity and strength therefor authorized by any law of this state, and such article comply therewith and be not misbranded.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20704[2018 c 236 § 704]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.32.910[1961 c 11 § 15.32.910]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c192.pdf?cite=1919%20c%20192%20§%2088[1919 c 192 § 88]; RRS § 6266; ]

== 15.36.551 - Dairy inspection program—Assessment. (Expires June 30, 2025.)
There is levied on all milk processed in this state an assessment not to exceed fifty-four one-hundredths of one cent per hundredweight. The director shall determine, by rule, an assessment, that with contribution from the general fund, will support an inspection program to maintain compliance with the provisions of the pasteurized milk ordinance of the national conference on interstate milk shipment. All assessments shall be levied on the operator of the first milk processing plant receiving the milk for processing. This shall include milk processing plants that produce their own milk for processing and milk processing plants that receive milk from other sources. Milk processing plants whose monthly assessment for receipt of milk totals less than twenty dollars in any given month are exempted from paying this assessment for that month. All moneys collected under this section shall be paid to the director by the twentieth day of the succeeding month for the previous month's assessments. The director shall deposit the funds into the dairy inspection account hereby created within the agricultural local fund established in RCW 43.23.230. The funds shall be used only to provide inspection services to the dairy industry. If the operator of a milk processing plant fails to remit any assessments, that sum shall be a lien on any property owned by him or her, and shall be reported by the director and collected in the manner and with the same priority over other creditors as prescribed for the collection of delinquent taxes under chapters 84.60 and 84.64 RCW.

This section expires June 30, 2025.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1429.SL.pdf?cite=2019%20c%20115%20§%201[2019 c 115 § 1]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5015.SL.pdf?cite=2015%201st%20sp.s.%20c%205%20§%201[2015 1st sp.s. c 5 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6229.SL.pdf?cite=2010%20c%2017%20§%201[2010 c 17 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6465.SL.pdf?cite=2004%20c%20132%20§%201[2004 c 132 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%2026[1999 c 291 § 26]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1706.SL.pdf?cite=1995%20c%2015%20§%201[1995 c 15 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6098-S.SL.pdf?cite=1994%20c%2034%20§%201[1994 c 34 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5983.SL.pdf?cite=1993%20sp.s.%20c%2019%20§%201[1993 sp.s. c 19 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6393-S.SL.pdf?cite=1992%20c%20160%20§%201[1992 c 160 § 1]; ]

== 15.36.561 - Dairy inspection program—Advisory committee—Purpose—Terms.
. There is created a dairy inspection program advisory committee. The committee shall consist of eleven members appointed by the director. The director shall solicit nominations for members of the committee from Washington dairy producer organizations and milk processors. The committee shall consist of four members who are producers or their representatives, four members who are milk processors or their representatives, one member who is a producer processor, one member who is a milk hauler, and one member who is a milk equipment dealer.

. The purpose of this advisory committee is to advise the director in the administration of the dairy inspection program and regarding policy issues related to this chapter.

. The terms of the members of the committee shall be staggered and the members shall serve a term of three years until their successor has been appointed and qualified. In the event a committee member resigns, is disqualified, or vacates a position on the committee for any reason the vacancy may be filled by the director under the provisions of this section governing appointments. The director may remove a member for cause.

. The committee shall elect one of its members as chair. The committee shall meet by the call of the director, chair, or a majority of the committee. Members of the committee shall serve without compensation.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1151.SL.pdf?cite=1999%20c%20291%20§%2027[1999 c 291 § 27]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6096-S.SL.pdf?cite=1994%20c%20143%20§%20507[1994 c 143 § 507]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6098-S.SL.pdf?cite=1994%20c%2034%20§%202[1994 c 34 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6393-S.SL.pdf?cite=1992%20c%20160%20§%202[1992 c 160 § 2]; ]

== 15.36.571 - Department authorized to assess inspection fee on certain manufacturing facilities.
The department may, upon inspection, assess an inspection fee on any manufacturing facility that is required to be inspected under the PMO and does not satisfy the definition of "milk processing plant" as defined in this chapter, "food processing plant" as defined in RCW 69.07.010, or "food storage warehouse" as defined in RCW 69.10.005.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2128-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2027%20§%206[2015 3rd sp.s. c 27 § 6]; ]

