= 15.86 - Organic products.
:toc:

== 15.86.010 - Purpose.
The legislature recognizes a public benefit in:

. Establishing standards governing the labeling and advertising of agricultural products and commodities as organic products or transitional products;

. Providing certification under the national organic program for agricultural products marketed and labeled using the term "organic" or a derivative of the term "organic;"

. Providing access for Washington producers, processors, and handlers to domestic and international markets for organic products; 

. Establishing a state organic program or obtaining federal accreditation as a certifying agent under the national organic program; and

. Establishing a brand name materials list for registration of inputs that comply with national, international, or other organic standards.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2460.SL.pdf?cite=2010%20c%20109%20§%201[2010 c 109 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2397.SL.pdf?cite=2002%20c%20220%20§%201[2002 c 220 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2502-S.SL.pdf?cite=1992%20c%2071%20§%201[1992 c 71 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c247.pdf?cite=1985%20c%20247%20§%201[1985 c 247 § 1]; ]

== 15.86.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Certification" or "certified" means a determination documented by a certificate of organic operation made by a certifying agent that a production or handling operation is in compliance with the national organic program or with international standards.

. "Compost" means the product of a managed process through which microorganisms break down plant and animal materials into more available forms suitable for application to the soil.

. "Crop production aid" means any substance, material, structure, or device that is used to aid a producer of an agricultural product except for fertilizers and pesticides.

. "Department" means the state department of agriculture.

. "Director" means the director of the department of agriculture or the director's designee.

. "Fertilizer" means a single or blended substance containing one or more recognized plant nutrients which is used primarily for its plant nutrient content and which is designed for use or claimed to have value in promoting plant growth.

. "Handler" means any person who sells, distributes, or packs organic or transitional products.

. "Label" means a display of written, printed, or graphic material on the immediate container of an agricultural product or any such material affixed to any agricultural product or affixed to a bulk container containing an agricultural product, except for package liners or a display of written, printed, or graphic material which contains only information about the weight of the product.

. "Labeling" includes all written, printed, or graphic material accompanying an agricultural product at any time or written, printed, or graphic material about the agricultural product displayed at retail stores about the product.

. "Livestock production aid" means any substance, material, structure, or device that is used to aid a producer in the production of livestock such as parasiticides, medicines, and feed additives.

. "Manufacturer" means a person that compounds, produces, granulates, mixes, blends, repackages, or otherwise alters the composition of materials.

. "Material" means any substance or mixture of substances that is intended to be used in agricultural production, processing, or handling.

. "National organic program" means the program administered by the United States department of agriculture pursuant to 7 C.F.R. Part 205, which implements the federal organic food production act of 1990 (7 U.S.C. Sec. 6501 et seq.).

. "Organic certifying agent" means any third-party certification organization that is recognized by the director as being one which imposes, for certification, standards consistent with this chapter.

. "Organic product" means any agricultural product, in whole or in part, including meat, dairy, and beverage, that is marketed using the term organic or any derivative of organic and that is produced, handled, and processed in accordance with this chapter.

. "Organic waste-derived material" means grass clippings, leaves, weeds, bark, plantings, prunings, and other vegetative wastes, uncontaminated wood waste from logging and milling operations, food wastes, food processing wastes, and materials derived from these wastes through composting. "Organic waste-derived material" does not include products that contain biosolids as defined in *chapter 70.95J RCW.

. "Person" means any natural person, firm, partnership, exchange, association, trustee, receiver, corporation, and any member, officer, or employee thereof or assignee for the benefit of creditors.

. "Pesticide" means, but is not limited to:

.. Any substance or mixture of substances intended to prevent, destroy, control, repel, or mitigate any insect, rodent, nematode, mollusk, fungus, weed, and any other form of plant or animal life or virus, except a virus on or in a living human being or other animal, which is normally considered to be a pest or which the director may declare to be a pest;

.. Any substance or mixture of substances intended to be used as a plant regulator, defoliant, or desiccant;

.. Any substance or mixture of substances intended to be used as a spray adjuvant; and

.. Any other substances intended for such use as may be named by the director by rule.

. "Postharvest material" means any substance, material, structure, or device that is used in the postharvest handling of agricultural products.

. "Processing aid" means a substance that is added to a food:

.. During processing, but is removed in some manner from the food before it is packaged in its finished form;

.. During processing, is converted into constituents normally present in the food, and does not significantly increase the amount of the constituents naturally found in the food; and

.. For its technical or functional effect in the processing but is present in the finished food at insignificant levels and does not have any technical or functional effect in that food.

. "Processor" means any person engaged in the canning, freezing, drying, dehydrating, cooking, pressing, powdering, packaging, baking, heating, mixing, grinding, churning, separating, extracting, cutting, fermenting, eviscerating, preserving, jarring, or otherwise processing of an organic or transitional product.

. "Producer" means any person or organization who or which grows, raises, or produces an agricultural product.

. "Registrant" means the person registering a material on the brand name materials list under the provisions of this chapter.

. "Represent" means to hold out as or to advertise.

. "Sale" means selling, offering for sale, holding for sale, preparing for sale, trading, bartering, offering a gift as an inducement for sale of, and advertising for sale in any media.

. "Soil amendment" means any substance that is intended to improve the physical characteristics of the soil, except for fertilizers and pesticides.

. "Spray adjuvant" means any product intended to be used with a pesticide as an aid to the application or to the effect of the pesticide and that is in a package or container separate from the pesticide. "Spray adjuvant" includes, but is not limited to, wetting agents, spreading agents, deposit builders, adhesives, emulsifying agents, deflocculating agents, and water modifiers or similar agent with or without toxic properties of its own intended to be used with any other pesticide as an aid to its application or to its effect. "Spray adjuvant" does not include products that are only intended to mark the location where a pesticide is applied.

. "Transitional product" means any agricultural product that meets requirements for organic certification, except that the organic production areas have not been free of prohibited substances for thirty-six months. Use of prohibited substances must have ceased for at least twelve months prior to the harvest of a transitional product.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2460.SL.pdf?cite=2010%20c%20109%20§%202[2010 c 109 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2397.SL.pdf?cite=2002%20c%20220%20§%202[2002 c 220 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2502-S.SL.pdf?cite=1992%20c%2071%20§%202[1992 c 71 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2032[1989 c 354 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c247.pdf?cite=1985%20c%20247%20§%202[1985 c 247 § 2]; ]

== 15.86.030 - Marketing of organic products—Standards—Restrictions—Evaluations to verify compliance.
. To be labeled, sold, or represented as an organic product, a product must be produced under standards established in this chapter or rules adopted pursuant to this chapter. A producer, processor, or handler shall not represent, sell, or offer for sale any agricultural product with the representation that the product is organic if the producer, processor, or handler knows, or has reason to know, that the product has not been produced, processed, or handled in accordance with standards established in this chapter or rules adopted pursuant to this chapter.

. The department may conduct evaluations in retail establishments to verify compliance with organic labeling and advertising requirements of this chapter, rules adopted pursuant to this chapter, and the national organic program.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2460.SL.pdf?cite=2010%20c%20109%20§%203[2010 c 109 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2397.SL.pdf?cite=2002%20c%20220%20§%203[2002 c 220 § 3]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2502-S.SL.pdf?cite=1992%20c%2071%20§%203[1992 c 71 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2030[1989 c 354 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c247.pdf?cite=1985%20c%20247%20§%203[1985 c 247 § 3]; ]

== 15.86.060 - Rules—National organic program—Violations—Penalties.
. The director shall adopt rules, in conformity with chapter 34.05 RCW, as the director believes are appropriate for the adoption of the national organic program and for the proper administration of this chapter.

. [Empty]
.. The director shall issue orders to producers, processors, or handlers whom the director finds are violating RCW 15.86.030 or 15.86.090 or rules adopted pursuant to this chapter, to cease their violations and desist from future violations.

.. Whenever the director finds that a producer, processor, or handler has committed a violation, the director shall impose on and collect from the violator a civil fine not exceeding the total of:

... The state's estimated costs of investigating and taking appropriate administrative and enforcement actions in respect to the violation; and

... One thousand dollars.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2460.SL.pdf?cite=2010%20c%20109%20§%204[2010 c 109 § 4]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2397.SL.pdf?cite=2002%20c%20220%20§%204[2002 c 220 § 4]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2502-S.SL.pdf?cite=1992%20c%2071%20§%207[1992 c 71 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c247.pdf?cite=1985%20c%20247%20§%206[1985 c 247 § 6]; ]

== 15.86.065 - State organic program—Authority of department and director—Rules.
. The department is authorized to take such actions, conduct proceedings, and enter orders as permitted or contemplated for a state organic program or certifying agent under the national organic program.

. The director may deny, suspend, or revoke a certification provided for in this chapter if the director determines that an applicant or certified person has violated this chapter or rules adopted pursuant to this chapter.

. The program shall not be inconsistent with the requirements of the national organic program.

. The department shall adopt rules necessary to implement this section.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2460.SL.pdf?cite=2010%20c%20109%20§%205[2010 c 109 § 5]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2397.SL.pdf?cite=2002%20c%20220%20§%207[2002 c 220 § 7]; ]

== 15.86.070 - Rules—Certification program—Fees.
. The director may adopt rules establishing a program for certifying producers, processors, and handlers as meeting state, national, or international standards for organic or transitional products.

. The rules:

.. May govern, but are not limited to governing:

... The number and scheduling of on-site visits, both announced and unannounced, by certification personnel;

... Recordkeeping requirements; and

... The submission of product samples for chemical analysis; and

.. Shall include a fee schedule that will provide for the recovery of the full cost of the program.

. All fees collected under this chapter shall be deposited in an account within the agricultural local fund. The revenue from such fees shall be used solely for carrying out the provisions of this chapter, and no appropriation is required for disbursement from the fund.

. The director may employ such personnel as are necessary to carry out the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2460.SL.pdf?cite=2010%20c%20109%20§%206[2010 c 109 § 6]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2397.SL.pdf?cite=2002%20c%20220%20§%205[2002 c 220 § 5]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5514.SL.pdf?cite=1997%20c%20303%20§%204[1997 c 303 § 4]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2502-S.SL.pdf?cite=1992%20c%2071%20§%2010[1992 c 71 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2034[1989 c 354 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c393.pdf?cite=1987%20c%20393%20§%2012[1987 c 393 § 12]; ]

== 15.86.090 - Mandatory certification—Exceptions.
. It is unlawful for any person to sell, offer for sale, or process any agricultural product within this state with an organic label unless that person is certified under this chapter by the department or a recognized organic certifying agent.

. Subsection (1) of this section shall not apply to:

.. Final retailers of organic products that do not process organic products; or

.. Producers who sell no more than five thousand dollars annually in value of agricultural products directly to consumers.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2460.SL.pdf?cite=2010%20c%20109%20§%207[2010 c 109 § 7]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2397.SL.pdf?cite=2002%20c%20220%20§%206[2002 c 220 § 6]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2502-S.SL.pdf?cite=1992%20c%2071%20§%208[1992 c 71 § 8]; ]

== 15.86.110 - Confidentiality of business related information.
. Except as provided in subsection (2) of this section, the department shall keep confidential any business related information obtained under this chapter concerning an entity certified under this chapter or an applicant for such certification and such information shall be exempt from public inspection and copying under chapter 42.56 RCW.

. Applications for certification under this chapter and laboratory analyses pertaining to that certification shall be available for public inspection and copying.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20218[2005 c 274 § 218]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2502-S.SL.pdf?cite=1992%20c%2071%20§%2011[1992 c 71 § 11]; ]

== 15.86.120 - Transitional product—Standards—Fees—Evaluations to verify compliance.
. To be labeled, sold, or represented as transitional products, agricultural products must comply with transitional product standards specified in this chapter and rules adopted pursuant to this chapter, including no application of substances prohibited under the national organic program within one year immediately preceding harvest.

. A producer, processor, or handler may not represent, sell, or offer for sale any agricultural product as a transitional product if the producer, processor, or handler knows or has reason to know that the product does not comply with transitional product standards specified in this chapter or rules adopted pursuant to this chapter.

. [Empty]
.. The department may set and collect transitional certification fees, including fees for application for transitional certification, renewal of transitional certification, inspections, and sampling. Collected fees are subject to provisions specified in RCW 15.86.070.

.. The fee for application for transitional certification is fifty dollars per site in addition to any organic certification application fees established under this chapter. The department may increase this fee by rule as necessary to cover costs of provision of services.

. The department may conduct evaluations in retail establishments to verify compliance with transitional labeling and advertising requirements of this chapter, rules adopted pursuant to this chapter, and the national organic program.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2460.SL.pdf?cite=2010%20c%20109%20§%208[2010 c 109 § 8]; ]

== 15.86.130 - Brand name materials list of registered materials—Application for registration—Right to enter premises—Rules—Denial/suspension/revocation of a registration, grounds.
. The department may establish a brand name materials list of registered materials that are approved for use in organic production, processing, or handling in accordance with the national organic program or international standards. Registration of a material on the brand name materials list is voluntary. While registration is not required for a material to be used or sold in this state, registration is necessary for a material to be included on the brand name materials list.

. [Empty]
.. Manufacturers of materials may submit an application to the department for registration of a material on the brand name materials list. Applications must be made on a form designated by the department, and must include:

... The name and address of the manufacturer;

... The name and address of the manufacturer's representative making the representations in the application;

... The brand name that the material is sold under;

... A copy of the labeling accompanying the material and a statement of all claims to be made for it, including the directions and precautions for use;

.. The complete formula of the material, including the active and inert ingredients;

.. A description of the manufacturing process, including all materials used for the extraction and synthesis of the material, if appropriate;

.. The intended uses of the product;

.. The source or supplier of all ingredients;

... The required fee for registration or renewal; and

.. Any additional information required by rule.

.. If any change to the information provided in an application occurs at any time after an application is submitted, the registrant must immediately submit corrected information to the department for review. Failure by the registrant to provide corrections to information provided in the application may result in suspension or revocation of the registration.

.. By submitting an application for registration on the brand name materials list, the applicant expressly consents to jurisdiction of the state of Washington in all matters related to the registration.

.. Applications for registration on the brand name materials list are governed by chapter 34.05 RCW.

. [Empty]
.. By applying for registration on the brand name materials list, the registrant expressly grants to the department or other organic certifying agent or inspection agent approved by the national organic program the right to enter the registrant's premises during normal business hours or at other reasonable times to:

... Inspect the portion of the premises where the material, inputs, or ingredients are stored, produced, manufactured, packaged, or labeled;

... Inspect records related to the sales, storage, production, manufacture, packaging, or labeling of the material, inputs, or ingredients; and

... Obtain samples of materials, inputs, and ingredients.

.. Should the registrant refuse to allow inspection of the premises or records or fail to provide samples, the registration on the brand name materials list is canceled. The department shall deny applications for registration where the registrant refuses to allow the inspection of the premises or records or fails to provide samples as provided in this section.

.. Required inspections may be conducted by department personnel, by an organic certifying agent, or by another inspection agent approved by the national organic program. The department may establish by rule evaluation criteria for review of inspection reports conducted by an organic certifying agent or inspection agent approved by the national organic program.

. The director may adopt rules necessary to implement the brand name materials list, including but not limited to:

.. Fees related to registration;

.. The number and scheduling of inspections, both announced and unannounced;

.. Recordkeeping requirements;

.. Additional application requirements;

.. Labeling of registered materials; and

.. Chemical analysis of material samples.

. [Empty]
.. The department may establish a brand name materials list to register materials approved for use under:

... National organic program standards; or

... International or additional organic standards.

.. The director may review materials registered on the brand name materials list as approved for use under the national organic program for compliance with specific international or additional organic standards as designated by rule. A registered material that complies with a specific international or additional organic standard may also be registered as approved under that standard.

. Registration of a material on the brand name materials list under this chapter does not guarantee acceptance for use in organic production or processing by organic certifying agents other than the department. The department is not liable for any losses or damage that occurs as a result of use of a material registered on the brand name materials list.

. The director may deny, suspend, or revoke a registration on the brand name materials list if the director determines that a registrant has:

.. Failed to meet the registration criteria established in this chapter or rules adopted pursuant to this chapter; or

.. Violated any other provision of this chapter or rules adopted pursuant to this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2460.SL.pdf?cite=2010%20c%20109%20§%209[2010 c 109 § 9]; ]

== 15.86.140 - Brand name materials list—Fees.
. The department is authorized to set and collect fees for application for registration, renewal of registration, inspections, and sampling for the brand name materials list. Collected fees are subject to provisions specified in RCW 15.86.070. The department may increase by rule fees established in this section as necessary to cover costs of provision of services.

. [Empty]
.. The application fee for registration of a pesticide, spray adjuvant, processing aid, livestock production aid, or postharvest material is:

... Five hundred dollars per material for an initial registration; and

... Three hundred dollars per material for renewing a registration.

.. The application fee for registration of a fertilizer, soil amendment, organic waste-derived material, compost, animal manure, or crop production aid is:

... Four hundred dollars per material for an initial registration; and

... Two hundred dollars per material for renewing a registration.

. [Empty]
.. Renewal applications postmarked after October 31st must include, in addition to the renewal fee, a late fee of:

... One hundred dollars per material for applications postmarked after October 31st;

... Two hundred dollars per material for applications postmarked after November 30th; and

... Three hundred dollars per material for applications postmarked after December 31st.

.. Renewal applications received after February 2nd will not be accepted, and applicants must reapply as new applicants.

. Inspections and any additional visit that must be arranged must be billed at forty dollars per hour plus travel costs and mileage, charged at the rate established by the office of financial management.

. Chemical analysis of material samples, if required for registration or requested by the applicant, must be billed at a rate established by the laboratory services division of the department of agriculture or at cost for analyses performed by another laboratory.

. Requests for expedited reviews may be submitted and, if approved, must be billed at forty dollars per hour.

. The department may assess compliance with an international or additional organic standard for materials registered on the brand name materials list as approved for use under the national organic program. Requests for additional assessments of materials approved under the national organic program must be billed at a rate of one hundred dollars per product for each standard.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2460.SL.pdf?cite=2010%20c%20109%20§%2010[2010 c 109 § 10]; ]

