= 15.19 - Ginseng.
:toc:

== 15.19.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Department" means the department of agriculture of the state of Washington.

. "Director" means the director of the department or his or her duly authorized representative.

. "Facility" means, but is not limited to, the premises where ginseng is grown, stored, dried, handled, or delivered for sale or transportation, or where records required by rule under this chapter are stored or kept, and all vehicles and equipment, whether aerial or surface, used to transport ginseng.

. "Grower" means a person who grows cultivated, wild simulated, and/or woodsgrown American ginseng and sells it to a dealer.

. "Person" means any individual, firm, partnership, corporation, company, society, or association, and every officer, agent, or employee thereof.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6122.SL.pdf?cite=1998%20c%20154%20§%2021[1998 c 154 § 21]; ]

== 15.19.020 - Enforcement of chapter.
The director shall enforce and carry out the provisions of this chapter and may adopt the necessary rules to carry out its purpose.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6122.SL.pdf?cite=1998%20c%20154%20§%2022[1998 c 154 § 22]; ]

== 15.19.030 - Adoption of rules.
In addition to the powers conferred on the director under this chapter, the director has the power to adopt rules:

. Establishing certification requirements for American ginseng (Panax quinquefolius L.).

Certification factors include:

.. Place of origin;

.. Whether the ginseng is wild or cultivated;

.. Weight; and

.. Date of harvest;

and may include whether the ginseng meets requirements for freedom from infestation by plant pests as required by the importing country;

. Requiring the registration of ginseng growers and of dealers who purchase and/or sell American ginseng for the purpose of foreign export; and

. Requiring that records be maintained by ginseng growers and by dealers who purchase or sell American ginseng for the purpose of foreign export.

The director may adopt any other rules necessary to comply with the requirements of the convention on international trade in endangered species of wild fauna and flora (27 U.S.T. 108); the endangered species act of 1973, as amended (16 U.S.C. Sec. 1531 et seq.); and 50 C.F.R. Part 23 (1995), as they existed on June 6, 1996, or a subsequent date as may be provided by rule, consistent with the purposes of this section.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6122.SL.pdf?cite=1998%20c%20154%20§%2023[1998 c 154 § 23]; ]

== 15.19.040 - Fees established by rule—Deposit—Use—Failure to pay.
. The director shall adopt rules establishing fees to recover the costs of providing ginseng certification activities authorized under this chapter. All moneys collected under this chapter shall be paid to the director, deposited in an account within the agricultural local fund, and used solely for carrying out the purposes of this chapter and rules adopted under this chapter.

. In addition to other penalties, the director may refuse to perform any inspection or certification service authorized under this chapter for any person in arrears unless the person makes payment in full prior to performing the service.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6122.SL.pdf?cite=1998%20c%20154%20§%2024[1998 c 154 § 24]; ]

== 15.19.050 - Inspection of facility—Entry—Samples—Search warrant.
The director may enter at reasonable times as determined by the director and inspect any facility and any records required under this chapter. The director may take for inspection those representative samples of ginseng necessary to determine whether or not this chapter or rules adopted under this chapter have been violated. If the director is denied access to any facility or records, the director may apply to a court of competent jurisdiction for a search warrant authorizing access to the facility or records. The court may upon such application issue a search warrant for the purpose requested.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6122.SL.pdf?cite=1998%20c%20154%20§%2025[1998 c 154 § 25]; ]

== 15.19.060 - Injunctions.
The director may bring an action to enjoin any violation of this chapter or rule adopted under this chapter in the superior court of Thurston county or of any county in which a violation occurs, notwithstanding the existence of other remedies at law.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6122.SL.pdf?cite=1998%20c%20154%20§%2026[1998 c 154 § 26]; ]

== 15.19.070 - Cooperative agency agreements.
The director may cooperate with and enter into agreements with governmental agencies of this state, other states, and agencies of the federal government in order to carry out the purpose and provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6122.SL.pdf?cite=1998%20c%20154%20§%2027[1998 c 154 § 27]; ]

== 15.19.080 - Public disclosure of information—Exemption.
The department shall not disclose information obtained under this chapter regarding the purchases, sales, or production of an individual American ginseng grower or dealer, except for providing reports to the United States fish and wildlife service. This information is exempt from public disclosure required by chapter 42.56 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20211[2005 c 274 § 211]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6122.SL.pdf?cite=1998%20c%20154%20§%2028[1998 c 154 § 28]; ]

== 15.19.090 - Violations of chapter or rules—Unlawful.
It is unlawful for a person to sell, offer for sale, hold for sale, or ship or transport American ginseng for foreign export in violation of this chapter or rules adopted under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6122.SL.pdf?cite=1998%20c%20154%20§%2029[1998 c 154 § 29]; ]

== 15.19.100 - Violations of chapter or rules—Penalties.
Any person who violates the provisions of this chapter or rules adopted under this chapter may be subject to:

. A civil penalty in an amount of not more than one thousand dollars for each violation; and/or

. Denial, revocation, or suspension of any registration or application for registration issued under this chapter. Upon notice by the director to deny, revoke, or suspend a registration or application for registration, a person may request a hearing under chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6122.SL.pdf?cite=1998%20c%20154%20§%2030[1998 c 154 § 30]; ]

== 15.19.110 - Remedies.
The provisions of this chapter are cumulative and nonexclusive and do not affect any other remedy.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6122.SL.pdf?cite=1998%20c%20154%20§%2031[1998 c 154 § 31]; ]

