= 15.28 - Soft tree fruits.
:toc:

== 15.28.010 - Definitions.
As used in this chapter:

. "Commission" means the Washington state fruit commission.

. "Shipment" or "shipped" includes loading in a conveyance to be transported to market for resale, and includes delivery to a processor or processing plant, but does not include movement from the orchard where grown to a packing or storage plant within this state for fresh shipment;

. "Handler" means any person who ships or initiates the shipping operation, whether as owner, agent or otherwise;

. "Dealer" means any person who handles, ships, buys, or sells soft tree fruits other than those grown by him or her, or who acts as sales or purchasing agent, broker, or factor of soft tree fruits;

. "Processor" or "processing plant" includes every person or plant receiving soft tree fruits for the purpose of drying, dehydrating, canning, pressing, powdering, extracting, cooking, quick-freezing, brining, or for use in manufacturing a product;

. "Soft tree fruits" mean Bartlett pears and all varieties of cherries, apricots, prunes, plums, and peaches, which includes all varieties of nectarines. "Bartlett pears" means and includes all standard Bartlett pears and all varieties, strains, subvarieties, and sport varieties of Bartlett pears including Red Bartlett pears, that are harvested and utilized at approximately the same time and approximately in the same manner.

. "Commercial fruit" or "commercial grade" means soft tree fruits meeting the requirements of any established or recognized fresh fruit or processing grade. Fruit bought or sold on orchard run basis and not subject to cull weighback shall be deemed to be "commercial fruit."

. "Cull grade" means fruit of lower than commercial grade except when such fruit included with commercial fruit does not exceed the permissible tolerance permitted in a commercial grade;

. "Producer" means any person who is a grower of any soft tree fruit;

. "District No. 1" or "first district" includes the counties of Chelan, Okanogan, Grant, Douglas, Ferry, Stevens, Pend Oreille, Spokane and Lincoln;

. "District No. 2" or "second district" includes the counties of Kittitas, Yakima, and Benton county north of the Yakima river;

. "District No. 3" or "third district" comprises all of the state not included in the first and second districts;

. "Mail" or "send" for purposes of any notice relating to rule making, referenda, or elections means regular mail or electronic distribution, as provided in RCW 34.05.260 for rule making. "Electronic distribution" or "electronically" means distribution by electronic mail or facsimile mail;

. "Department" means the department of agriculture;

. "Director" means the director of agriculture.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%20104[2002 c 313 § 104]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2027[1989 c 354 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c11.pdf?cite=1973%20c%2011%20§%201[1973 c 11 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c51.pdf?cite=1963%20c%2051%20§%201[1963 c 51 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.010[1961 c 11 § 15.28.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c47.pdf?cite=1955%20c%2047%20§%201[1955 c 47 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%201[1947 c 73 § 1]; Rem. Supp. 1947 § 2909-10; ]

== 15.28.015 - Regulating soft tree fruits—Commission created—Existing comprehensive scheme—Applicable laws.
The history, economy, culture, and the future of Washington state's agriculture involves the production of soft tree fruits. In order to develop and promote Washington's soft tree fruits as part of an existing comprehensive regulatory scheme the legislature declares:

. That the Washington state fruit commission is created;

. That it is vital to the continued economic well-being of the citizens of this state and their general welfare that its soft tree fruits be properly promoted by (a) enabling the soft tree fruit industry to help themselves in establishing orderly, fair, sound, efficient, and unhampered cooperative marketing, grading, and standardizing of soft tree fruits they produce; and (b) working to stabilize the soft tree fruit industry by increasing consumption of soft tree fruits within the state, the nation, and internationally;

. That producers of soft tree fruits operate within a regulatory environment that imposes burdens on them for the benefit of society and the citizens of the state and includes restrictions on marketing autonomy. Those restrictions may impair the producers of soft tree fruits in their ability to compete in local, domestic, and foreign markets;

. That it is in the overriding public interest that support for the soft tree fruit industry be clearly expressed, that adequate protection be given to agricultural commodities, uses, activities, and operations, and that soft tree fruits be promoted individually, and as part of a comprehensive industry to:

.. Enhance the reputation and image of Washington state's agriculture industry;

.. Increase the sale and use of Washington state's soft tree fruits in local, domestic, and foreign markets;

.. Protect the public by educating the public in reference to the quality, care, and methods used in the production of Washington state's soft tree fruits;

.. Increase the knowledge of the health-giving qualities and dietetic value of soft tree fruits;

.. Support and engage in cooperative programs or activities that benefit the production, handling, processing, marketing, and uses of soft tree fruits produced in Washington state;

. That this chapter is enacted in the exercise of the police powers of this state for the purpose of protecting the health, peace, safety, and general welfare of the people of this state and to stabilize and protect the soft tree fruit industry of the state; and

. That the production and marketing of soft tree fruit is a highly regulated industry and that the provisions of this chapter and the rules adopted under it are only one aspect of the regulated industry. Other regulations and restraints applicable to the soft tree fruit industry include:

.. The federal marketing order under 7 C.F.R. Part 922 (apricots);

.. The federal marketing order under 7 C.F.R. Part 923 (sweet cherries);

.. The federal marketing order under 7 C.F.R. Part 924 (prunes);

.. The federal marketing order under 7 C.F.R. Part 930 (tart cherries);

.. The federal marketing order under 7 C.F.R. Part 931 (Bartlett pears);

.. Tree fruit research act under chapter 15.26 RCW;

.. Controlled atmosphere storage of fruits and vegetables under chapter 15.30 RCW;

.. Organic products act under chapter 15.86 RCW;

.. The food safety and security act under chapter 15.130 RCW;

.. Washington food processing act under chapter 69.07 RCW;

.. Washington food storage warehouses act under chapter 69.10 RCW;

.. Weighmasters under chapter 15.80 RCW;

.. Horticultural pests and diseases under chapter 15.08 RCW;

.. Horticultural plants, Christmas trees, and facilities—Inspection and licensing under chapter 15.13 RCW;

.. Planting stock under chapter 15.14 RCW;

.. Standards of grades and packs under chapter 15.17 RCW;

.. Washington pesticide control act under chapter 15.58 RCW;

.. Farm marketing under chapter 15.64 RCW;

.. Insect pests and plant diseases under chapter 17.24 RCW;

.. Weights and measures under chapter 19.94 RCW;

.. Agricultural products—Commission merchants, dealers, brokers, buyers, and agents under chapter 20.01 RCW; and

.. Rules under the Washington Administrative Code, Title 16.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20701[2018 c 236 § 701]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5374-S.SL.pdf?cite=2011%20c%20103%20§%2028[2011 c 103 § 28]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%20103[2002 c 313 § 103]; ]

== 15.28.020 - Commission composition—Voting—Quorum.
The commission is composed of seventeen voting members, as follows: Ten producers, four dealers, and two processors, who are appointed as provided in this chapter. The director, or an authorized representative, shall be a voting member of the commission. Other sections of this chapter that relate to the selection of voting members shall not apply to the director or his or her authorized representative.

A majority of the voting members constitute a quorum for the transaction of any business.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1361.SL.pdf?cite=2003%20c%20396%20§%2013[2003 c 396 § 13]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%20105[2002 c 313 § 105]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c191.pdf?cite=1967%20c%20191%20§%201[1967 c 191 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.020[1961 c 11 § 15.28.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%202[1947 c 73 § 2]; Rem. Supp. 1947 § 2901-11.   1947 c 73 § 9; Rem. Supp. 1947 § 2909-18. (iii) 1947 c 73 § 13, part; Rem. Supp. 1947 § 2909-22, part; ]

== 15.28.023 - Director appoints members—Nominations—Advisory vote.
. The director shall appoint the members of the commission.

. Candidates for positions on the commission shall be nominated under RCW 15.28.060.

. Not less than sixty days nor more than seventy-five days prior to the commencement of a commission member's term, the director shall cause an advisory vote to be held for the director-appointed positions. Advisory ballots shall be mailed to all affected producers and shall be returned to the director not less than thirty days prior to the commencement of the term. The advisory ballot shall be conducted in a manner so that it is a secret ballot. The names of the two candidates receiving the most votes in the advisory vote shall be forwarded to the director for potential appointment to the commission. In the event there are only two candidates nominated for a position, an advisory vote may not be held and the candidates' names shall be forwarded to the director for potential appointment. If only one candidate is nominated for a position, the commission shall select a second candidate whose name will be forwarded to the director.

. Any candidate whose name is forwarded to the director for potential appointment shall submit to the director a letter stating why he or she wishes to be appointed to the commission. The director may select either person for the position.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1361.SL.pdf?cite=2003%20c%20396%20§%2016[2003 c 396 § 16]; ]

== 15.28.024 - Transition to director appointed commission.
To accomplish the transition to a commission structure where the director appoints a majority of commission members, the names of the currently elected commission members shall be forwarded to the director for appointment to the commission within thirty days of May 20, 2003. Thereafter, the director shall appoint commission members pursuant to RCW 15.28.023 as the current commission member terms expire.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1361.SL.pdf?cite=2003%20c%20396%20§%2017[2003 c 396 § 17]; ]

== 15.28.030 - Qualifications of voting members.
All voting members must be citizens and residents of this state. Each producer member must be over the age of twenty-five years, and be, and for five years have been, actively engaged in growing soft tree fruits in this state, and deriving a substantial portion of his or her income therefrom, or have a substantial amount of orchard acreage devoted to soft tree fruit production as an owner, lessee, partner, or a stockholder owning at least ten percent of the voting stock in a corporation engaged in the production of soft tree fruit. He or she cannot be engaged directly in business as a dealer. Each dealer member must be actively engaged, either individually or as an executive officer, employee or sales manager on a management level, or managing agent of an organization, as a dealer. Each processor member must be engaged, either individually or as an executive officer, employee on a management level, sales manager, or managing agent of an organization, as a processor. Only one dealer member may be in the employ of any one person or organization engaged in business as a dealer. Only one processor member may be in the employ of any one person or organization engaged in business as a processor. Said qualifications must continue throughout each member's term of office.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%206037[2010 c 8 § 6037]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c191.pdf?cite=1967%20c%20191%20§%202[1967 c 191 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.030[1961 c 11 § 15.28.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%203[1947 c 73 § 3]; Rem. Supp. 1947 § 2909-12; ]

== 15.28.040 - Appointment of voting members—Positions.
Of the producer members, four shall be appointed from the first district and occupy positions one, two, three and four; four shall be appointed from the second district and occupy positions five, six, seven and eight, and two shall be appointed from the third district and occupy positions nine and ten.

Of the dealer members, two shall be appointed from each of the first and second districts and respectively occupy positions eleven and twelve from the first district and positions thirteen and fourteen from the second district.

The processor members shall be appointed from the state at large and occupy positions fifteen and sixteen. The dealer member position previously referred to as position twelve shall henceforth be position thirteen. The processor member position heretofore referred to as position fourteen shall cease to exist on March 21, 1967. The processor member position heretofore referred to as thirteen shall be known as position sixteen.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1361.SL.pdf?cite=2003%20c%20396%20§%2014[2003 c 396 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c191.pdf?cite=1967%20c%20191%20§%203[1967 c 191 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.040[1961 c 11 § 15.28.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%204[1947 c 73 § 4]; Rem. Supp. 1947 § 2909-13; ]

== 15.28.050 - Terms of office.
The regular term of office of the members of the commission shall be three years commencing on May 1, following the date of appointment and until their successors are appointed and qualified, except, however, that the first term of dealer position twelve in the first district shall be for two years and expire May 1, 1969.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1361.SL.pdf?cite=2003%20c%20396%20§%2015[2003 c 396 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c191.pdf?cite=1967%20c%20191%20§%204[1967 c 191 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.050[1961 c 11 § 15.28.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%205[1947 c 73 § 5]; Rem. Supp. 1947 § 2909-14; ]

== 15.28.055 - Terms of present members.
Present members of the state fruit commission as provided for in RCW 15.28.020 shall serve until the first day of May of the year in which their terms would ordinarily expire and until their successors are elected and qualified.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c191.pdf?cite=1967%20c%20191%20§%208[1967 c 191 § 8]; ]

== 15.28.060 - Nominating meetings—Notice—Appointment—Ballots—Advisory vote—Eligible voters.
The director shall call meetings at times and places concurred upon by the director and the commission for the purpose of nominating producer, dealer or processor members for potential appointment to the commission when such members' terms are about to expire. Notice of such meetings shall be given at least sixty days prior to the time the respective members' term is about to expire. The nominating meetings shall be held at least sixty days prior to the expiration of the respective members' term of office.

Notice shall be given by the commission by mail to all known persons having a right to vote for such respective nominee's potential appointment to the commission.

Further, the commission shall publish notice at least once in a newspaper of general circulation in the district where the nomination is to be held. Such a newspaper may be published daily or weekly. The failure of any person entitled to receive notice of such nominating meeting shall not invalidate such nominating meeting or the appointment of a member nominated at such meeting.

Any person qualified to serve on the commission may be nominated orally at the nomination meetings. Written nominations, signed by five persons qualified to vote for the said nominee, may be made for five days subsequent to the nomination meeting. Such written nominations shall be filed with the commission at its Yakima office.

The director shall cause an advisory vote to be held for commission positions. The advisory vote shall be by secret mail ballot. Persons qualified to vote for members of the commission shall, except as otherwise provided by law or rule or regulation of the commission, vote only in the district in which their activities make them eligible to vote for a potential member of the commission.

A producer to be eligible to vote in the advisory vote for a nominee as a producer member of the commission must be a commercial producer of soft tree fruits paying assessments to the commission.

When a legal entity acting as a producer, dealer, or processor is qualified to vote for a candidate in any district or area to serve in a specified position on the commission, such legal entity may cast only one vote for such candidate, regardless of the number of persons comprising such legal entity or stockholders owning stock therein.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1361.SL.pdf?cite=2003%20c%20396%20§%2018[2003 c 396 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c191.pdf?cite=1967%20c%20191%20§%206[1967 c 191 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c51.pdf?cite=1963%20c%2051%20§%202[1963 c 51 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.060[1961 c 11 § 15.28.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%206[1947 c 73 § 6]; Rem. Supp. 1947 § 2909-15; ]

== 15.28.070 - Establishment of subdistricts—Rules and regulations.
The commission shall have the authority, subject to the provisions of chapter 34.05 RCW (Administrative Procedure Act), for adopting rules and regulations, after public hearing, establishing one or more subdistricts in any one of the three districts. Such subdistricts shall include a substantial portion of the soft tree fruit producing area in the district in which they are formed.

The commission shall, when a subdistrict has been formed within one of the districts as in this section provided for, assign one of the districts' producer positions on the commission to said subdistrict. Such producer position may only be filled by a producer residing in such subdistrict, whether by apportionment or appointment.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1361.SL.pdf?cite=2003%20c%20396%20§%2019[2003 c 396 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c191.pdf?cite=1967%20c%20191%20§%207[1967 c 191 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.070[1961 c 11 § 15.28.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%207[1947 c 73 § 7]; Rem. Supp. 1947 § 2909-16; ]

== 15.28.080 - Vacancies on commission—How filled.
In the event a position becomes vacant due to resignation, disqualification, death, or for any other reason, such position, until the next annual nominating meeting, shall be filled by vote of the remaining members of the commission. Following the next annual nomination meeting, the director shall appoint one of the two nominees selected by advisory ballot to fill the balance of the unexpired term.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1361.SL.pdf?cite=2003%20c%20396%20§%2020[2003 c 396 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.080[1961 c 11 § 15.28.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%208[1947 c 73 § 8]; Rem. Supp. 1947 § 2909-17; ]

== 15.28.090 - Compensation of members—Travel expenses.
Each member of the commission shall be compensated in accordance with RCW 43.03.230 and shall be reimbursed for actual travel expenses incurred in carrying out the provisions of this chapter. Employees of the commission may also be reimbursed for actual travel expenses when out of state on official commission business.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c287.pdf?cite=1984%20c%20287%20§%2014[1984 c 287 § 14]; 1975-'76 2nd ex.s. c 34 § 14; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c191.pdf?cite=1967%20c%20191%20§%205[1967 c 191 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.090[1961 c 11 § 15.28.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%2010[1947 c 73 § 10]; Rem. Supp. 1947 § 2909-19; ]

== 15.28.100 - Powers of commission.
The Washington state fruit commission is hereby declared and created a corporate body. The commission has power:

. To exercise all of the powers of a corporation;

. To elect a chair and such other officers as it may deem advisable;

. To adopt, amend, or repeal, from time to time, necessary and proper rules, regulations, and orders for the performance of its duties, which rules, regulations, and orders shall have the force of laws when not inconsistent with existing laws;

. To employ, and at its pleasure discharge, such attorneys, advertising manager, agents or agencies, clerks and employees, as it deems necessary and fix their compensation;

. To establish offices, and incur such expenses, enter into such contracts, and create such liabilities, as it deems reasonably necessary for the proper administration of this chapter;

. To accept contributions of, or match private, state, or federal funds available for research, and make contributions to persons or state or federal agencies conducting such research;

. To administer and enforce this chapter, and do and perform all acts and exercise all powers deemed reasonably necessary, proper, or advisable to effectuate the purposes of this chapter, and to perpetuate and promote the general welfare of the soft tree fruit industry of this state;

. To sue and be sued.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%206038[2010 c 8 § 6038]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.100[1961 c 11 § 15.28.100]; 1947 c 73 § 13, part; Rem. Supp. 1947 § 2909-22, part.  1947 c 73 § 15, part; Rem. Supp. 1947 § 2909-24, part. (iii) 1947 c 73 § 17, part; Rem. Supp. 1947 § 2909-26, part; ]

== 15.28.103 - Commission's plans, programs, and projects—Director's approval required.
. The commission shall develop and submit to the director for approval any plans, programs, and projects concerning the following:

.. The establishment, issuance, effectuation, and administration of appropriate programs or projects for the advertising and promotion of the affected commodities; and

.. The establishment and effectuation of market research projects, market development projects, or both to the end that the marketing and utilization of the affected commodities may be encouraged, expanded, improved, or made more efficient.

. The director shall review the commission's advertising or promotion program to ensure that no false claims are being made concerning the affected commodities.

. The commission, prior to the beginning of its fiscal year, shall prepare and submit to the director for approval its research plan, its commodity-related education and training plan, and its budget on a fiscal period basis.

. The director shall strive to review and make a determination of all submissions described in this section in a timely manner.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1361.SL.pdf?cite=2003%20c%20396%20§%2021[2003 c 396 § 21]; ]

== 15.28.105 - Commission speaks for state—Director's oversight.
The commission exists primarily for the benefit of the people of the state of Washington and its economy. The legislature hereby charges the commission, with oversight by the director, to speak on behalf of Washington state government with regard to its particular commodities.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1361.SL.pdf?cite=2003%20c%20396%20§%2022[2003 c 396 § 22]; ]

== 15.28.110 - Duties of commission.
The commission's duties are:

. To adopt a commission seal;

. To elect a secretary-manager and a treasurer, and fix their compensation. The same person may be elected to both offices;

. To establish classifications of soft tree fruits;

. To conduct scientific research and develop the healthful, therapeutic, and dietetic value of fruits, and promote the general welfare of the soft tree fruit industry of the state;

. To conduct a comprehensive advertising and educational campaign to effectuate the objects of this chapter;

. To increase the production, and develop and expand the markets, and improve the handling and quality of fruits;

. To keep accurate accounts and records of all of its dealings, which shall be open to inspection and audit by the state auditor;

. To investigate and prosecute violations of this chapter; and

. To serve as an advisory committee to the director with regard to the adoption and enforcement of rules:

.. Governing the grading, packing, and size and dimensions of commercial containers of soft tree fruits; and

.. Fixing commercial grades of soft tree fruits and the issuance of certificates of inspection for those fruits.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%20106[2002 c 313 § 106]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.110[1961 c 11 § 15.28.110]; 1947 c 73 § 13, part; Rem. Supp. 1947 § 2909-22, part.   1947 c 73 § 14; Rem. Supp. 1947 § 2909-23. (iii) 1947 c 73 § 15, part; Rem. Supp. 1947 § 2909-24, part. (iv) 1947 c 73 § 17, part; Rem. Supp. 1947 § 2909-26, part; ]

== 15.28.120 - Copies of records as evidence.
Copies of the commission's proceedings, records, and acts, when certified by the secretary and authenticated by the corporate seal, shall be admissible in all courts as prima facie evidence of the truth of all statements therein.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.120[1961 c 11 § 15.28.120]; 1947 c 73 § 13, part; Rem. Supp. 1947 § 2909-22, part; ]

== 15.28.130 - State, personal, nonliability—Obligations limited by collections—Defense to certain civil or criminal actions.
Neither the state, nor any member, agent, or employee of the commission, is liable for the acts of the commission, or upon its contracts.

All salaries, expenses, costs, obligations, and liabilities of the commission, and claims arising from the administration of this chapter, are payable only from funds collected under this chapter.

In any civil or criminal action or proceeding for violation of any rule of [or] statutory or common law against monopolies or combinations in restraint of trade, including any action under chapter 19.86 RCW, proof that the act complained of was done in compliance with the provisions of this chapter, and in furtherance of the purposes and provisions of this chapter, is a complete defense to such an action or proceeding.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%20107[2002 c 313 § 107]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.130[1961 c 11 § 15.28.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%2016[1947 c 73 § 16]; Rem. Supp. 1947 § 2909-25; ]

== 15.28.140 - District advisory and state commodity committees.
There shall be separate district advisory committees and separate state commodity committees for each of the following soft tree fruits, to wit: Bartlett pears, peaches, apricots, prunes and plums, and cherries. The growers, dealers, or processors of each of the soft tree fruits, at their respective annual district meetings may elect separate district advisory committees for each of the soft tree fruits grown, handled, or processed in their respective districts. The district advisory committee shall consist of five members comprising three growers, one dealer and one processor of the respective soft tree fruit groups. Each state commodity committee shall consist of two members from, and selected by, each district advisory committee for each soft fruit.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.140[1961 c 11 § 15.28.140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%2011[1947 c 73 § 11]; Rem. Supp. 1947 § 2909-20; ]

== 15.28.150 - Committee organization—Duties.
Each district advisory committee and each state commodity committee shall select one of its members as chair. Meetings may be called by the chair or by any two members of any committee by giving reasonable written notice of the meeting to each member of such committee. A majority of the members shall be necessary to constitute a quorum. The district advisory committees and state commodity committees shall consult with and advise the commission on matters pertaining to the soft tree fruits which they respectively represent, and the commission shall give due consideration to their recommendations. Any grower, dealer, or processor, if qualified, may be a member of more than one committee.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%206039[2010 c 8 § 6039]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.150[1961 c 11 § 15.28.150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%2012[1947 c 73 § 12]; Rem. Supp. 1947 § 2909-21; ]

== 15.28.160 - Annual assessment—Exemption—Brined sweet cherries assessable.
An annual assessment is hereby levied upon all commercial soft tree fruits grown in the state or packed as Washington soft tree fruit of fifty cents per two thousand pounds (net weight) of said fruits, when shipped fresh or delivered to processors, whether in bulk, loose in containers, or packaged in any style of package, except, that all sales of five hundred pounds or less of such fruits sold by the producer direct to the consumer shall be exempt from said assessments. Sweet cherries which are brined are deemed to be commercial soft tree fruit and therefore assessable hereunder.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2028[1989 c 354 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c51.pdf?cite=1963%20c%2051%20§%203[1963 c 51 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.160[1961 c 11 § 15.28.160]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%2018[1947 c 73 § 18]; Rem. Supp. 1947 § 2909-27; ]

== 15.28.170 - Research and advertising—Power to increase assessment.
The commission shall investigate the needs of soft tree fruit producers, the condition of the markets, and extent to which the same require advertising and research. If the investigation shows that the revenue from the assessments levied is inadequate to accomplish the objects of this chapter, it shall report its findings to the director, showing the necessities of the industry, the probable cost of the required program, and the probable revenue from the existing levy. It may then increase the assessments to be levied to an amount not exceeding two dollars per each two thousand pounds (net weight) of such fruits so contained or packed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.170[1961 c 11 § 15.28.170]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%2025[1947 c 73 § 25]; Rem. Supp. 1947 § 2909-34; ]

== 15.28.180 - Increase of assessment for specific fruit or classification—Procedure.
. The same assessment shall be made for each soft tree fruit, except that if a two-thirds majority of the state commodity committee of any fruit recommends in writing the levy of an additional assessment on that fruit, or any classification thereof, for any year or years, the commission may levy such assessment for that year or years up to the maximum of eighteen dollars for each two thousand pounds of any fruit except cherries or any classification thereof, as to which the assessment may be increased to a maximum of thirty dollars for each two thousand pounds, and except pears covered by this chapter, as to which the assessment may be increased to a maximum of eighteen dollars for each two thousand pounds: PROVIDED, That no increase in the assessment on pears becomes effective unless the increase is first referred by the commission to a referendum by the Bartlett pear growers of the state and is approved by a majority of the growers voting on the referendum. The method and procedure of conducting the referendum shall be determined by the commission. Any funds so raised shall be expended solely for the purposes provided in this chapter and solely for such fruit, or classification thereof.

The commission has the authority in its discretion to exempt in whole or in part from future assessments under this chapter, during such period as the commission may prescribe, any of the soft tree fruits or any particular strain or classification of them.

. An assessment levied under this chapter may be increased in excess of the fiscal growth factor as determined under chapter 43.135 RCW if the assessment is submitted by referendum to the growers who are subject to the assessment and the increase is approved by a majority of those voting on the referendum. The method and procedure of conducting the referendum shall be determined by the commission.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5514.SL.pdf?cite=1997%20c%20303%20§%203[1997 c 303 § 3]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6212.SL.pdf?cite=1992%20c%2087%20§%201[1992 c 87 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c73.pdf?cite=1983%201st%20ex.s.%20c%2073%20§%201[1983 1st ex.s. c 73 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c8.pdf?cite=1977%20ex.s.%20c%208%20§%201[1977 ex.s. c 8 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c43.pdf?cite=1965%20ex.s.%20c%2043%20§%201[1965 ex.s. c 43 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c51.pdf?cite=1963%20c%2051%20§%204[1963 c 51 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.180[1961 c 11 § 15.28.180]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%2026[1947 c 73 § 26]; Rem. Supp. 1947 § 2909-35; ]

== 15.28.190 - Deposit of funds—Treasurer's bond.
All money collected under the authority of this chapter shall be paid to the treasurer of the commission, deposited by him or her in banks designated by the commission, and disbursed on its order.

The treasurer shall file with the commission a fidelity bond, executed by a surety company authorized to do business in this state, in favor of the state and the commission, jointly and severally, in the sum of fifty thousand dollars, and conditioned upon his or her faithful performance of his or her duties and his or her strict accounting of all funds of the commission.

None of the provisions of RCW 43.01.050 shall apply to money collected under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%206040[2010 c 8 § 6040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.190[1961 c 11 § 15.28.190]; 1947 c 73 § 15, part; Rem. Supp. 1947 § 2909-24, part; ]

== 15.28.200 - Use of funds—Contributions.
All moneys collected from such levy shall be expended exclusively to effectuate the purposes and objects of this chapter. They shall be generally expended on promotion and improvement of the various commodities approximately in the ratio that funds are derived from such commodities, after deducting suitable amounts for general overhead and basic general research, unless a majority of the functioning state commodity committees consent to a larger expenditure on behalf of any commodity or commodities. Any funds contributed to the commission by any special group or raised by an additional levy on any commodity or classification thereof, shall be expended only in connection with such commodity.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.200[1961 c 11 § 15.28.200]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%2019[1947 c 73 § 19]; Rem. Supp. 1947 § 2909-28; ]

== 15.28.210 - Records kept—Preservation—Inspection of.
Every dealer, handler, and processor shall keep a complete and accurate record of all soft tree fruits handled, shipped, or processed by him or her. Such record shall be in simple form and contain such information as the commission shall by rule or regulation prescribe. The records shall be preserved by such handler, dealer, and processor for a period of two years and shall be offered and submitted for inspection at any reasonable time upon written request of the commission or its duly authorized agents.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%206041[2010 c 8 § 6041]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.210[1961 c 11 § 15.28.210]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%2020[1947 c 73 § 20]; Rem. Supp. 1947 § 2909-29; ]

== 15.28.220 - Returns to commission.
Every dealer, handler, and processor shall at such times as the commission may by rule or regulation require, file with the commission a return under oath on forms to be prescribed and furnished by the commission, stating the quantity of soft tree fruits handled, shipped, or processed by him or her during the period or periods of time prescribed by the commission. Such return shall contain such further information as may be necessary to carry out the objects and purposes of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%206042[2010 c 8 § 6042]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.220[1961 c 11 § 15.28.220]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%2021[1947 c 73 § 21]; Rem. Supp. 1947 § 2909-30; ]

== 15.28.230 - Due date of assessments—Delinquent penalty.
All assessments levied and imposed by this chapter shall be due prior to shipment and shall become delinquent if not paid within thirty days after the time established for such payment according to regulations of the commission. A delinquent penalty shall be payable on any such delinquent assessment, calculated as interest on the principal amount due at the rate of ten percent per annum. Any delinquent penalty shall not be charged back against the grower unless he or she caused such delay in payment of the assessment due.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%206043[2010 c 8 § 6043]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.230[1961 c 11 § 15.28.230]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c47.pdf?cite=1955%20c%2047%20§%202[1955 c 47 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%2022[1947 c 73 § 22]; Rem. Supp. 1947 § 2909-31; ]

== 15.28.240 - Collection rules—Use of "stamps."
The commission shall by rule or regulation prescribe the method of collection, and for that purpose may require stamps to be known as "Washington state fruit commission stamps" to be purchased from the commission and fixed or attached to the container, invoices, shipping documents, inspection certificates, releases, or receiving receipts or tickets. Stamps shall be canceled immediately upon being so attached or fixed, and the date of cancellation shall be placed thereon.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.240[1961 c 11 § 15.28.240]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%2023[1947 c 73 § 23]; Rem. Supp. 1947 § 2909-32; ]

== 15.28.250 - Responsibility for payment of assessments—Due upon receipt—Delinquencies—Civil action.
Unless the assessment has been paid by the grower and evidence thereof submitted by him or her, the dealer, handler, or processor is responsible for the payment of all assessments under this chapter on all soft tree fruits handled, shipped, or processed by him or her but he or she shall charge the same against the grower, who shall be primarily responsible for such payment. Assessments are due upon receipt of an invoice for the assessments.

If the assessment becomes delinquent, the department shall cease to provide inspection services under chapter 15.17 RCW to the delinquent party until that party pays all delinquent assessments, interest, and penalties.

Any assessment due and payable under this section constitutes a personal debt of every person so assessed or who otherwise owes the same. In addition, the commission may add to such unpaid assessment or sum an amount not exceeding ten percent of the same to defray the cost of enforcing the collecting of the same. In the event of failure of such person or persons to pay any such due and payable assessment or other such sum, the commission may bring a civil action against such person or persons, together with the specified ten percent thereon, and such action shall be tried and judgment rendered as in any other cause of action for debt due and payable.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%20108[2002 c 313 § 108]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.250[1961 c 11 § 15.28.250]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%2024[1947 c 73 § 24]; Rem. Supp. 1947 § 2909-33; ]

== 15.28.260 - Publications by commission—Subscriptions.
If the commission publishes a bulletin or other publication, or a section in some established trade publication, for the dissemination of information to the soft tree fruit industry in this state, the first two dollars of any assessment paid annually by each grower, handler, dealer, and processor of such fruit shall be applied to the payment of his or her subscription to such bulletin or publication.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%206044[2010 c 8 § 6044]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.260[1961 c 11 § 15.28.260]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%2027[1947 c 73 § 27]; Rem. Supp. 1947 § 2909-36; ]

== 15.28.270 - Violations—Penalty.
Every person shall be guilty of a misdemeanor who:

. Violates or aids in the violation of any provision of this chapter, or

. Violates or aids in the violation of any rule or regulation of the commission.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.270[1961 c 11 § 15.28.270]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%2028[1947 c 73 § 28]; Rem. Supp. 1947 § 2909-37; ]

== 15.28.280 - Venue of actions—Jurisdiction of courts.
Any prosecution brought under this chapter may be instituted or brought in any county in the state in which the defendant or any of the defendants reside, or in which the violation was committed, or in which the defendant or any of the defendants has his or her principal place of business.

The several superior courts of the state are hereby vested with jurisdiction to enforce this chapter and to prevent and restrain violations thereof, or of any rule or regulation promulgated by the commission.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%206045[2010 c 8 § 6045]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.280[1961 c 11 § 15.28.280]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%2029[1947 c 73 § 29]; Rem. Supp. 1947 § 2909-38; ]

== 15.28.290 - Duty to enforce.
It shall be the duty of all state and county law enforcement officers and all employees and agents of the department to aid in the enforcement of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.290[1961 c 11 § 15.28.290]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%2030[1947 c 73 § 30]; Rem. Supp. 1947 § 2909-39; ]

== 15.28.300 - Rules and regulations—Filing—Publication.
Every rule, regulation, or order promulgated by the commission shall be filed with the director, and shall be published in a legal newspaper of general circulation in each of the three districts. All such rules, regulations, or orders shall become effective pursuant to the provisions of RCW 34.05.380.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c469.pdf?cite=1985%20c%20469%20§%207[1985 c 469 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c7.pdf?cite=1975%201st%20ex.s.%20c%207%20§%2038[1975 1st ex.s. c 7 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.300[1961 c 11 § 15.28.300]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%2031[1947 c 73 § 31]; Rem. Supp. 1947 § 2909-40; ]

== 15.28.305 - Rule making—Exemptions.
Rule-making proceedings conducted under this chapter are exempt from compliance with RCW 34.05.310 and the provisions of chapter 19.85 RCW, the regulatory fairness act, when adoption of the rule is determined by a referendum vote of the affected parties.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%20109[2002 c 313 § 109]; ]

== 15.28.310 - Authority to agents of commission to inspect.
Agents of the commission, upon specific written authorization signed by the chair or secretary-manager thereof, shall have the right to inspect the premises, books, records, documents, and all other instruments of any carrier, railroad, truck, boat, grower, handler, dealer, and processor for the purpose of enforcing this chapter and collecting the assessments levied hereunder.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%206046[2010 c 8 § 6046]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.310[1961 c 11 § 15.28.310]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c73.pdf?cite=1947%20c%2073%20§%2032[1947 c 73 § 32]; Rem. Supp. 1947 § 2909-41; ]

== 15.28.315 - Certain records exempt from public disclosure—Exceptions—Actions not prohibited by chapter.
. Under RCW 42.56.380, certain agricultural business records, commission records, and department of agriculture records relating to the commission and producers of agricultural commodities are exempt from public disclosure.

. Financial and commercial information and records submitted to either the department or the commission for the purpose of administering this chapter may be shared between the department and the commission. They may also be used, if required, in any suit or administrative hearing involving any provision of this chapter or a marketing order.

. This chapter does not prohibit:

.. The issuance of general statements based upon the reports of persons subject to this chapter as long as the statements do not identify the information furnished by any person; or

.. The publication by the director or the commission of the name of any person violating this chapter and a statement of the manner of the violation by that person.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20213[2005 c 274 § 213]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%2068[2002 c 313 § 68]; ]

== 15.28.320 - Funding staff support—Rules.
The director may provide by rule for a method to fund staff support for all commodity boards and commissions in accordance with RCW 43.23.033 if a position is not directly funded by the legislature and costs related to the specific activity undertaken on behalf of an individual commodity board or commission. The commission shall provide funds to the department according to the rules adopted by the director.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%2074[2002 c 313 § 74]; ]

== 15.28.325 - Costs of implementing RCW  15.28.103.
The costs incurred by the department of agriculture associated with the implementation of RCW 15.28.103 shall be paid for by the commission.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1361.SL.pdf?cite=2003%20c%20396%20§%2023[2003 c 396 § 23]; ]

== 15.28.910 - Liberal construction.
This chapter shall be liberally construed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.28.910[1961 c 11 § 15.28.910]; 1947 c 73 § 33, part; Rem. Supp. 1947 § 2909-42, part; ]

