= 15.70 - Rural rehabilitation.
:toc:

== 15.70.010 - Director may receive federal funds for rural rehabilitation corporation.
The director of the state department of agriculture is hereby designated as the state official of the state of Washington to make application to and receive from the secretary of agriculture of the United States, or any other proper federal official, pursuant and subject to the provisions of public law 499, 81st congress, approved May 3, 1950, the trust assets, either funds or property, held by the United States as trustee in behalf of the Washington rural rehabilitation corporation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.70.010[1961 c 11 § 15.70.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c169.pdf?cite=1951%20c%20169%20§%201[1951 c 169 § 1]; ]

== 15.70.020 - Director may delegate certain powers to secretary of agriculture.
The director of agriculture is authorized, in his or her discretion, to enter into agreements with the secretary of agriculture of the United States pursuant to section 2(f) of the aforesaid act of the congress of the United States, upon such terms and conditions and for such periods of time as may be mutually agreeable, authorizing the secretary of agriculture of the United States to accept, administer, expend, and use in the state of Washington all or any part of such trust assets or any other funds of the state of Washington which may be appropriated for such uses for carrying out the purposes of titles I and II of the Bankhead-Jones farm tenant act, in accordance with the applicable provisions of title IV thereof, as now or hereafter amended, and to do any and all things necessary to effectuate and carry out the purposes of said agreements.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%206097[2010 c 8 § 6097]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.70.020[1961 c 11 § 15.70.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c169.pdf?cite=1951%20c%20169%20§%202[1951 c 169 § 2]; ]

== 15.70.030 - Deposit and use of funds.
Notwithstanding any other provisions of law, funds and the proceeds of the trust assets which are not authorized to be administered by the secretary of agriculture of the United States under the provisions of RCW 15.70.020 shall be received by the director of agriculture and by him or her deposited with the treasurer of the state. Such funds are hereby appropriated and may be expended or obligated by the director of agriculture for the purposes of RCW 15.70.020 or for use by the director of agriculture for such of the rural rehabilitation purposes permissible under the charter of the now dissolved Washington rural rehabilitation corporation as may from time to time be agreed upon by the director of agriculture and the secretary of agriculture of the United States, subject to the applicable provisions of said public law 499.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%206098[2010 c 8 § 6098]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.70.030[1961 c 11 § 15.70.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c169.pdf?cite=1951%20c%20169%20§%203[1951 c 169 § 3]; ]

== 15.70.040 - Powers of director—In general.
The director of agriculture is authorized and empowered to:

. Collect, compromise, adjust, or cancel claims and obligations arising out of or administered under this chapter or under any mortgage, lease, contract, or agreement entered into or administered pursuant to this chapter and if, in his or her judgment, necessary and advisable, pursue the same to final collection in any court having jurisdiction;

. Bid for and purchase at any execution, foreclosure, or other sale, or otherwise to acquire property upon which the director of agriculture has a lien by reason of judgment or execution, or which is pledged, mortgaged, conveyed, or which otherwise secures any loan or other indebtedness owing to or acquired by the director of agriculture under this chapter; and

. Accept title to any property so purchased or acquired; to operate or lease such property for such period as may be deemed necessary to protect the investment therein; and to sell or otherwise dispose of such property in a manner consistent with the provisions of this chapter.

The authority herein contained may be delegated to the secretary of agriculture of the United States with respect to funds or assets authorized to be administered and used by him or her under agreements entered into pursuant to RCW 15.70.020.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%206099[2010 c 8 § 6099]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.70.040[1961 c 11 § 15.70.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c169.pdf?cite=1951%20c%20169%20§%204[1951 c 169 § 4]; ]

== 15.70.050 - No liability as to United States.
The United States and the secretary of agriculture thereof, shall be held free from liability by virtue of the transfer of the assets to the director of agriculture of the state of Washington pursuant to this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.70.050[1961 c 11 § 15.70.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c169.pdf?cite=1951%20c%20169%20§%205[1951 c 169 § 5]; ]

