= 15.49 - Seeds.
:toc:

== 15.49.005 - Purpose—Rules.
The purpose of this chapter is to provide uniformity and consistency in the packaging of agricultural, vegetable, and flower seeds so as to facilitate the interstate movement of seed, to protect consumers, and to provide a dispute-resolution process. The department of agriculture is hereby authorized to adopt rules in accordance with chapter 34.05 RCW to implement this chapter. To the extent possible, the department shall seek to incorporate into the rules provisions from the recommended uniform state seed law in order to attain consistency with other states.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2070[1989 c 354 § 70]; ]

== 15.49.011 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

.. "Advertisement" means all representations, other than those on the label, disseminated in any manner or by any means, relating to seed within the scope of this chapter.

. "Agricultural seed" includes grass, forage, cereal, oil, fiber, and other kinds of crop seeds commonly recognized within this state as agricultural seeds, lawn seeds, and combinations of such seeds, and may include common and restricted noxious weed seeds but not prohibited noxious weed seeds.

. "Blend" means seed consisting of more than one variety of a kind, each in excess of five percent by weight of the whole.

. "Bulk seed" means seed distributed in a nonpackage form.

. "Business licensing system" means the mechanism established by chapter 19.02 RCW by which business licenses, endorsed for individual state-issued licenses, are issued and renewed using a business license application and a business license expiration date common to each renewable license endorsement.

. "Certifying agency" means (a) an agency authorized under the laws of any state, territory, or possession to certify seed officially and which has standards and procedures approved by the United States secretary of agriculture to assure the genetic purity and identity of the seed certified; or (b) an agency of a foreign country determined by the United States secretary of agriculture to adhere to procedures and standards for seed certification comparable to those adhered to generally by seed-certifying agencies under (a) of this subsection.

. "Coated seed" means seed that has been treated and has received an application of inert material during the treatment process.

. "Conditioning" means drying, cleaning, scarifying, and other operations that could change the purity or germination of the seed and require the seed lot to be retested to determine the label information.

. "Dealer" means any person who distributes.

. "Department" means the department of agriculture of the state of Washington or its duly authorized representative.

. "Director" means the director of the department of agriculture.

. "Distribute" means to import, consign, offer for sale, hold for sale, sell, barter, or otherwise supply seed in this state.

. "Flower seeds" includes seeds of herbaceous plants grown from their blooms, ornamental foliage, or other ornamental parts, and commonly known and sold under the name of flower seeds in this state.

. The terms "foundation seed," "registered seed," and "certified seed" mean seed that has been produced and labeled in compliance with the regulations of the department.

. "Germination" means the emergence and development from the seed embryo of those essential structures which, for the kind of seed in question, are indicative of the ability to produce a normal plant under favorable conditions.

. "Hard seeds" means seeds that remain hard at the end of the prescribed test period because they have not absorbed water due to an impermeable seed coat.

. "Hybrid" means the first generation seed of a cross produced by controlling the pollination and by combining (a) two or more inbred lines; (b) one inbred or a single cross with an open pollinated variety; or (c) two varieties or species, except open-pollinated varieties of corn (Zea mays). The second generation or subsequent generations from such crosses are not regarded as hybrids. Hybrid designations must be treated as variety names.

. "Inert matter" means all matter not seed, that includes broken seeds, sterile florets, chaff, fungus bodies, and stones as determined by methods defined by rule.

. "Inoculant" means a commercial preparation containing nitrogen fixing bacteria applied to the seed.

. "Kind" means one or more related species or subspecies that singly or collectively is known by one common name, for example, corn, oats, alfalfa, and timothy.

. "Label" includes a tag or other device attached to or written, stamped, or printed on any container or accompanying any lot of bulk seeds purporting to set forth the information required on the seed label by this chapter, and it may include any other information relating to the labeled seed.

. "Lot" means a definite quantity of seed identified by a lot number or other mark, every portion or bag of which is uniform within recognized tolerances for the factors that appear in the labeling.

. "Lot number" must identify the producer or dealer and year of production or the year distributed for each lot of seed. This requirement may be satisfied by use of a conditioner's or dealer's code.

. "Mixture," "mix," or "mixed" means seed consisting of more than one kind, each in excess of five percent by weight of the whole.

. "Official sample" means any sample of seed taken and designated as official by the department.

. "Other crop seed" means seed of plants grown as crops, other than the kind or variety included in the pure seed, as determined by methods defined by rule.

. "Person" means an individual, partnership, corporation, company, association, receiver, trustee, or agent.

. "Prohibited (primary) noxious weed seeds" are the seeds of weeds which when established are highly destructive, competitive, and/or difficult to control by cultural or chemical practices.

. "Pure live seed" means the product of the percent of germination plus hard or dormant seed multiplied by the percent of pure seed divided by one hundred. The result is expressed as a whole number.

. "Pure seed" means seed exclusive of inert matter and all other seeds not of the seed being considered as determined by methods defined by rule.

. "Restricted (secondary) noxious weed seeds" are the seeds of weeds which are objectionable in fields, lawns, and gardens of this state, but which can be controlled by cultural or chemical practices.

. "Retail" means to distribute to the ultimate consumer.

. "Screenings" mean chaff, seed, weed seed, inert matter, and other materials removed from seed in cleaning or conditioning.

. "Seed labeling registrant" means a person who has obtained a permit to label seed for distribution in this state.

. "Seeds" mean agricultural or vegetable seeds or other seeds as determined by rules adopted by the department.

. "Stop sale, use, or removal order" means an administrative order restraining the sale, use, disposition, and movement of a specific amount of seed.

. "Treated" means that the seed has received an application of a substance, or that it has been subjected to a process for which a claim is made.

. "Type" means a group of varieties so nearly similar that the individual varieties cannot be clearly differentiated except under special conditions.

. "Variety" means a subdivision of a kind that is distinct, uniform, and stable; "distinct" in the sense that the variety can be differentiated by one or more identifiable morphological, physiological, or other characteristics from all other varieties of public knowledge; "uniform" in the sense that variations in essential and distinctive characteristics are describable; and "stable" in the sense that the variety will remain unchanged in its essential and distinctive characteristics and its uniformity when reproduced or reconstituted as required by the different categories of varieties.

. "Vegetable seeds" includes the seeds of those crops that are grown in gardens and on truck farms and are generally known and sold under the name of vegetable or herb seeds in this state.

. "Weed seeds" include the seeds of all plants generally recognized as weeds within this state, and includes the seeds of prohibited and restricted noxious weeds as determined by regulations adopted by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1568-S.SL.pdf?cite=2013%20c%20144%20§%205[2013 c 144 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2073[1989 c 354 § 73]; ]

== 15.49.021 - Standards and label requirements—Rules.
. The department shall establish by rule standards and label requirements for the following seed types: Agricultural seed (including grass, lawn, and turf seed), flower seed, and vegetable seed.

. The standards and label requirements shall be divided into the following categories:

.. Percentage of kind and variety of each seed component present; and

.. Percentage of weed seed (restricted and common).

. The standards and label requirements developed by the department shall at a minimum include:

.. Amount of inert material;

.. Specifics and warning for treated seed;

.. Specifics for coated seed;

.. Specifics and duration for inoculated seed;

.. Specifics for seed which is below standard;

.. Specifics for seed contained in containers, mats, tapes, or other planting devices;

.. Specifics for seed sold in bulk;

.. Specifics for hybrid seed; and

.. Specifics for seed mixtures.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2071[1989 c 354 § 71]; ]

== 15.49.031 - Labels—Required information.
In addition to the requirements contained in RCW 15.49.021, each seed label shall contain the following:

. The name and address of the person who labeled the seed and who sells, offers, or exposes the seed for sale within the state;

. Lot number identification;

. Seed origin;

. Germination rate and date of germination test or the year for which the seed was packaged for sale.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2072[1989 c 354 § 72]; ]

== 15.49.041 - Violations—Civil penalty.
Every person who fails to comply with this chapter or the rules adopted under it may be subjected to a civil penalty, as determined by the director, in an amount of not more than two thousand dollars for every such violation. Each and every such violation shall be a separate and distinct offense.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2074[1989 c 354 § 74]; ]

== 15.49.051 - Unlawful practices.
. It is unlawful for any person to sell, offer for sale, expose for sale, or transport for sale any agricultural, vegetable, or flower seeds within this state unless the test to determine the percentage of germination is completed within a fifteen-month period prior to sale, provided that germination tests for seed packaged in hermetically sealed containers shall be completed within thirty-six months prior to sale. The department shall establish rules for allowing retesting.

. It is unlawful for any person to sell, offer for sale, expose for sale, or transport for sale any agricultural, vegetable, or flower seed within this state not labeled in accordance with this chapter or having false or misleading labeling or for which there has been false or misleading advertisement.

. It is unlawful to represent seed to be certified unless it has been determined by a seed-certifying agency that such seed conformed to standards of purity and identity or variety in compliance with the rules adopted under this chapter.

. It is unlawful to attach any tags of similar size and format to the official certification tag that could be mistaken for the official certification tag.

. It is unlawful for any person to sell, offer for sale, expose for sale, or transport for sale any agricultural, vegetable, or flower seed within this state labeled with a variety name but not certified by an official seed-certifying agency when it is a variety for which a United States certification of plant variety protection under the plant variety protection act (7 U.S.C. Sec. 2321 et seq.) specifies sale only as a class of certified seed: PROVIDED, That seed from a certified lot may be labeled as to variety name when used in a mixture by, or with the approval of, the owner of the variety.

. It is unlawful for any person within this state:

.. To detach, alter, deface, or destroy any label required by this chapter or its implementing rules or to alter or substitute seed in a manner that may defeat the purpose of this chapter;

.. To disseminate any false or misleading advertisements concerning seeds subject to this chapter in any manner or by any means;

.. To hinder or obstruct in any way, any authorized person in the performance of his or her duties under this chapter;

.. To fail to comply with a "stop sale" order or to move or otherwise handle or dispose of any lot of seed held under a "stop sale" order or tags attached thereto, except with express permission of the enforcing officer, and for the purpose specified thereby;

.. To use the word "trace" as a substitute for any statement that is required; and

.. To use the word "type" in any labeling in connection with the name of any agricultural seed variety.

. It is unlawful for any person to sell, offer for sale, expose for sale, or transport for sale any agricultural, vegetable, or flower seed within this state that consists of or contains: (a) Prohibited noxious weed seeds; or (b) restricted noxious weed seeds in excess of the number declared on the label.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2075[1989 c 354 § 75]; ]

== 15.49.061 - Exceptions.
. The provisions of this chapter do not apply to marijuana seed. For the purposes of this subsection, "marijuana" has the same meaning as defined in RCW 69.50.101.

. The provisions of RCW 15.49.011 through 15.49.051 do not apply:

.. To seed or grain not intended for sowing purposes;

.. To seed in storage by, or being transported or consigned to[,] a conditioning establishment for conditioning if the invoice or labeling accompanying the shipment of such seed bears the statement "seeds for conditioning" and if any labeling or other representation that may be made with respect to the unconditioned seed is subject to this chapter;

.. To any carrier with respect to any seed transported or delivered for transportation in the ordinary course of its business as a carrier if the carrier is not engaged in producing, conditioning, or marketing seeds subject to this chapter; or

.. Seed stored or transported by the grower of the seed.

. No person may be subject to the penalties of this chapter for having sold or offered for sale seeds subject to this chapter that were incorrectly labeled or represented as to kind, species, variety, or type, which seeds cannot be identified by examination thereof, unless he or she has failed to obtain an invoice, genuine grower's declaration, or other labeling information and to take such other precautions as may be reasonable to ensure the identity to be that stated. A genuine grower's declaration of variety shall affirm that the grower holds records of proof concerning parent seed, such as invoice and labels.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6505.SL.pdf?cite=2014%20c%20140%20§%2034[2014 c 140 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2076[1989 c 354 § 76]; ]

== 15.49.071 - Damages—Mediation prerequisite to legal action.
. When a buyer is damaged by the failure of any seed covered by this chapter to produce or perform as represented by the required label, by warranty, or as a result of negligence, the buyer, as a prerequisite to maintaining a legal action against the dealer of such seed, shall have first provided for the mediation of the claim. Any statutory period of limitations with respect to such claim shall be tolled from the date mediation proceedings are instituted until ten days after the date on which the mediation proceedings are concluded. Mediation proceedings are instituted from the date the buyer mails the dealer the buyer's complaint with its request to engage in mediation as provided under RCW 15.49.091.

. Conspicuous language calling attention to the requirement for mediation under this section shall be referenced or included on the analysis label required under this chapter.

. This section applies only to claims, or counterclaims, where the relief sought is, or includes, a monetary amount in excess of five thousand dollars. All claims for five thousand dollars or less may be commenced in either district court or small claims court.

. The mediation provisions under this section apply only to a dealer subject to this state's jurisdiction in relation to the buyer's claims.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5075.SL.pdf?cite=2017%20c%2033%20§%201[2017 c 33 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1054-S.SL.pdf?cite=2005%20c%20433%20§%2036[2005 c 433 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2077[1989 c 354 § 77]; ]

== 15.49.091 - Mediation—Procedure.
. To submit a claim for mediation, the buyer shall make and file a sworn complaint against the dealer alleging the damages sustained. The sworn complaint may take the form of a declaration or affidavit. The buyer shall send a copy of the complaint to the dealer by United States registered mail.

. Within twenty days after receipt of a copy of the complaint, the dealer shall file with the buyer, by United States registered mail, the answer to the complaint. The answer shall agree to participate in mediation under chapter 7.07 RCW or shall state the dealer's grounds for refusing to engage in such mediation. Failure of a dealer to file a timely answer to the complaint and the request to engage in mediation shall be documented for the record supporting the buyer's option to maintain a legal action for its claim against the dealer.

. The parties shall be equally responsible for the mediator's fees unless otherwise agreed between the parties before retaining the mediator.

. The mediator must be selected by mutual agreement of the parties from mediators qualified to conduct mediations under chapter 7.07 RCW. The mediation must take place within the part of the state where the buyer conducts the buyer's operations unless otherwise agreed between the parties.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5075.SL.pdf?cite=2017%20c%2033%20§%202[2017 c 33 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c354.pdf?cite=1989%20c%20354%20§%2079[1989 c 354 § 79]; ]

== 15.49.310 - Department to administer chapter—Rules and regulations—Guidance of federal seed act.
The department shall administer, enforce, and carry out the provisions of this chapter and may adopt regulations necessary to carry out its purpose. The adoption of regulations shall be subject to a public hearing and all other applicable provisions of chapter 34.05 RCW (Administrative Procedure Act), as enacted and hereafter amended.

The department when adopting regulations in respect to the seed industry shall consult with affected parties, such as growers, conditioners, and distributors of seed. Any final regulation adopted shall be based upon the requirements and conditions of the industry and shall be for the purpose of promoting the well-being of the purchasers and users of seed as well as the members of the seed industry.

When seed labeling, terms, methods of sampling and analysis, and tolerances are not specifically stated in this chapter or otherwise designated by the department, the department shall, in order to promote uniformity, be guided by officially recognized associations, or regulations under The Federal Seed Act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c297.pdf?cite=1981%20c%20297%20§%209[1981 c 297 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c63.pdf?cite=1969%20c%2063%20§%2031[1969 c 63 § 31]; ]

== 15.49.330 - Screenings—Removal required—Disposition.
. All screenings, removed in the cleaning or conditioning of seeds, which contain prohibited or restricted noxious weed seeds shall be removed from the seed conditioning plant only under conditions that will prevent weed seeds from being dispersed into the environment.

. The director may by regulation adopt requirements for moving, conditioning, and/or disposing of screenings.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c297.pdf?cite=1981%20c%20297%20§%2011[1981 c 297 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c154.pdf?cite=1979%20c%20154%20§%201[1979 c 154 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c63.pdf?cite=1969%20c%2063%20§%2033[1969 c 63 § 33]; ]

== 15.49.350 - Permit to condition certified seed.
Upon application for a permit to condition certified seed, the department shall inspect the seed conditioning facilities of the applicant to determine that genetic purity and identity of seed conditioned can be maintained. Upon approval, the department shall issue a seed conditioning permit, for each regular place of business, which shall be conspicuously displayed in the office of such business. The permit shall remain in effect as long as the facilities comply with the department's requirements for such permit.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c297.pdf?cite=1981%20c%20297%20§%2013[1981 c 297 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c63.pdf?cite=1969%20c%2063%20§%2035[1969 c 63 § 35]; ]

== 15.49.360 - Records—Maintenance—Availability of records and samples for inspection.
The seed labeling registrant whose name appears on the label shall:

. Keep, for a period of two years after the date of final disposition, complete records of each lot of seed distributed: PROVIDED, That the file sample of each lot of seed distributed need be kept for only one year.

. Make available, during regular working hours, such records and samples for inspection by the department.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c63.pdf?cite=1969%20c%2063%20§%2036[1969 c 63 § 36]; ]

== 15.49.370 - Department's enforcement authority.
The department shall have the authority to:

. Sample, inspect, make analysis of, and test seeds distributed within this state at such time and place and to such extent as it may deem necessary to determine whether such seeds are in compliance with the provisions of this chapter. The methods of sampling and analysis shall be those adopted by the department from officially recognized sources. The department, in determining for administrative purposes whether seeds are in violation of this chapter, shall be guided by records, and by the official sample obtained and analyzed as provided for in this section. Analysis of an official sample, by the department, shall be accepted as prima facie evidence by any court of competent jurisdiction.

. Enter any dealer's or seed labeling registrant's premises at all reasonable times in order to have access to seeds and to records. This includes the determination of the weight of packages and bulk shipments.

. Adopt and enforce regulations for certifying seeds, and shall fix and collect fees for such service. Fees authorized under this subsection may be used for services involving breeder seed, foundation seed, registered seed, and certified seed. The director of the department may appoint persons as agents for the purpose of assisting in the certification of seeds.

. Adopt and enforce regulations for inspecting, grading, and certifying growing crops of seeds; inspect, grade, and issue certificates upon request; and fix and collect fees for such services.

. Make purity, germination and other tests of seed on request, and fix and collect charges for the tests made.

. Establish and maintain seed testing facilities, employ qualified persons, establish by rule special assessments as needed, and incur such expenses as may be necessary to carry out the provisions of this chapter.

. Adopt a list of the prohibited and restricted noxious weed seeds.

. Publish reports of official seed inspections, seed certifications, laboratory statistics, verified violations of this chapter, and other seed branch activities which do not reveal confidential information regarding individual company operations or production.

. Deny, suspend, or revoke licenses, permits and certificates provided for in this chapter subsequent to a hearing, subject to the provisions of chapter 34.05 RCW (Administrative Procedure Act) as enacted or hereafter amended, in any case in which the department finds that there has been a failure or refusal to comply with the provisions of this chapter or regulations adopted hereunder.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6278.SL.pdf?cite=2018%20c%20233%20§%201[2018 c 233 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c297.pdf?cite=1981%20c%20297%20§%2014[1981 c 297 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c63.pdf?cite=1969%20c%2063%20§%2037[1969 c 63 § 37]; ]

== 15.49.380 - Dealer's license to distribute seeds.
. No person may distribute seeds without having obtained a dealer's license for each regular place of business. However, a license is not required of a person who distributes seeds only in sealed packages of eight ounces or less, packed by a seed labeling registrant and bearing the name and address of the registrant. Moreover, a license is not required of any grower selling seeds of his or her own production exclusively. Such seed sold by such grower must be properly labeled as provided in this chapter. Each dealer's license costs one hundred twenty-five dollars, must be issued through the business license [licensing] system, must bear the date of issue, must expire on the business licensing [license] expiration date, and must be prominently displayed in each place of business.

. Persons custom conditioning and/or custom treating seeds for others for remuneration are considered dealers for the purpose of this chapter.

. Application for a license to distribute seed must be through the business licensing system and must include the name and address of the person applying for the license, the name of a person domiciled in this state authorized to receive and accept service or legal notices of all kinds, and any other reasonable and practical information prescribed by the department necessary to carry out the purposes and provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1568-S.SL.pdf?cite=2013%20c%20144%20§%206[2013 c 144 § 6]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5981.SL.pdf?cite=2012%20c%2061%20§%201[2012 c 61 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%206064[2010 c 8 § 6064]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c182.pdf?cite=1982%20c%20182%20§%2024[1982 c 182 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c297.pdf?cite=1981%20c%20297%20§%2015[1981 c 297 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c63.pdf?cite=1969%20c%2063%20§%2038[1969 c 63 § 38]; ]

== 15.49.390 - Renewal of dealer's license.
If an application for renewal of the dealer's license provided for in RCW 15.49.380, is not filed prior to the business license expiration date, the business license delinquency fee must be assessed under chapter 19.02 RCW and must be paid by the applicant before the renewal license is issued.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1568-S.SL.pdf?cite=2013%20c%20144%20§%207[2013 c 144 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c182.pdf?cite=1982%20c%20182%20§%2025[1982 c 182 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c63.pdf?cite=1969%20c%2063%20§%2039[1969 c 63 § 39]; ]

== 15.49.400 - Seed labeling permit.
. No person shall label seed for distribution in this state without having obtained a seed labeling permit. The seed labeling registrant shall be responsible for the label and the seed contents. The application for a seed labeling permit shall be submitted to the department on forms furnished by the department, and shall be accompanied by a fee of twenty dollars per applicant. The application form shall include the name and address of the applicant, a label or label facsimile, and any other reasonable and practical information prescribed by the department. Upon approval, the department shall issue said permit to the applicant. All permits expire on January 31st of each year.

. If an application for renewal of the seed labeling permit provided for in this section is not filed prior to February 1st of any one year, an additional fee of ten dollars shall be assessed and added to the original fee and shall be paid by the applicant before the license shall be issued: PROVIDED, That such additional fee shall not apply if the applicant furnishes an affidavit that he or she has not labeled seed for distribution in this state subsequent to the expiration of his or her prior permit.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%206065[2010 c 8 § 6065]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c63.pdf?cite=1969%20c%2063%20§%2040[1969 c 63 § 40]; ]

== 15.49.410 - "Stop sale, use or removal orders"—Seizure—Condemnation.
. When the department has determined or has probable cause to suspect that any lot of seed or screenings is mislabeled and/or is being distributed in violation of this chapter or regulations adopted hereunder, it may issue and enforce a written or printed "stop sale, use or removal order" warning the distributor not to dispose of the lot of seed or screenings in any manner until written permission is given by the department or a court of competent jurisdiction. The department shall release the lot of seed or screenings so withdrawn when said provisions and regulations have been complied with. If compliance is not obtained, the department may bring proceedings for condemnation.

. Any lot of seed or screenings not in compliance with the provisions of this chapter shall be subject to seizure on complaint of the department to a court of competent jurisdiction in the locality in which the seed or screenings are located. In the event the court finds the seed or screenings to be in violation of this chapter and orders the condemnation of said seed or screenings, such lot of seed or screenings shall be denatured, conditioned, destroyed, relabeled, or otherwise disposed of in compliance with the laws of this state: PROVIDED, That in no instance shall the court order such disposition of said seed or screenings without first having given the claimant an opportunity to apply to the court, within twenty days, for the release of said seed or screenings or for permission to condition or relabel it to bring it into compliance with this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c297.pdf?cite=1981%20c%20297%20§%2016[1981 c 297 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c63.pdf?cite=1969%20c%2063%20§%2041[1969 c 63 § 41]; ]

== 15.49.420 - Damages precluded.
No state court shall allow the recovery of damages from administrative action taken or for stop sales or seizures under RCW 15.49.410 if the court finds that there was probable cause for such action.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c63.pdf?cite=1969%20c%2063%20§%2042[1969 c 63 § 42]; ]

== 15.49.460 - Injunctions.
The department is hereby authorized to apply for, and the court authorized to grant, a temporary or permanent injunction restraining any person from violating or continuing to violate any of the provisions of this chapter or any regulations promulgated under this chapter, notwithstanding the existence of any other remedy at law. Any such injunction shall be issued without bond.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c63.pdf?cite=1969%20c%2063%20§%2046[1969 c 63 § 46]; ]

== 15.49.470 - Moneys, disposition—Fees, fines, penalties and forfeitures of district courts, remittance.
All moneys collected under the provisions of this chapter shall be paid to the director and deposited in an account within the agricultural local fund. Such deposits shall be used only in the administration and enforcement of this chapter. Any residual balance remaining in the seed fund on June 9, 1988, shall be transferred to that account within the agricultural local fund. All fees, fines, forfeitures and penalties collected or assessed by a district court because of the violation of a state law shall be remitted as provided in chapter 3.62 RCW as now exists or is later amended.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c254.pdf?cite=1988%20c%20254%20§%202[1988 c 254 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c202.pdf?cite=1987%20c%20202%20§%20176[1987 c 202 § 176]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c257.pdf?cite=1975%201st%20ex.s.%20c%20257%20§%202[1975 1st ex.s. c 257 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c199.pdf?cite=1969%20ex.s.%20c%20199%20§%2013[1969 ex.s. c 199 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c63.pdf?cite=1969%20c%2063%20§%2047[1969 c 63 § 47]; ]

== 15.49.480 - Cooperation and agreements with other agencies.
The department may cooperate with and enter into agreements with other governmental agencies, whether of this state, other states, or agencies of the federal government, and with private associations, in order to carry out the purposes and provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c63.pdf?cite=1969%20c%2063%20§%2048[1969 c 63 § 48]; ]

== 15.49.900 - Existing liabilities not affected.
The enactment of this chapter shall not have the effect of terminating or in any way modifying any liability, civil or criminal, which shall already be in existence on July 1, 1969.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c63.pdf?cite=1969%20c%2063%20§%2049[1969 c 63 § 49]; ]

== 15.49.930 - Continuation of rules adopted pursuant to repealed sections—Adoption, amendment or repeal.
The repeal of sections 15.48.010 through 15.48.260 and 15.48.900, chapter 11, Laws of 1961 and RCW 15.48.010 through 15.48.260 and 15.48.900 and the enactment of this 1969 act shall not be deemed to have repealed any regulations adopted under the provisions of sections 15.48.010 through 15.48.260 and 15.48.900, chapter 11, Laws of 1961 and RCW 15.48.010 through 15.48.260 and 15.48.900, and in effect immediately prior to such repeal and not inconsistent with the provisions of this 1969 act. For the purpose of this 1969 act, it shall be deemed that such rules have been adopted under the provisions of this 1969 act pursuant to chapter 34.05 RCW, as enacted or hereafter amended concerning the adoption of rules. Any amendment or repeal of such rules after July 1, 1969, shall be subject to the provisions of chapter 34.05 RCW (Administrative Procedure Act) as enacted or hereafter amended, concerning the adoption of rules.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c63.pdf?cite=1969%20c%2063%20§%2052[1969 c 63 § 52]; ]

== 15.49.940 - Short title.
RCW 15.49.020 through * 15.49.950 shall be known as the "Washington State Seed Act."

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c63.pdf?cite=1969%20c%2063%20§%2053[1969 c 63 § 53]; ]

