= 15.62 - Honey bee commission.
:toc:

== 15.62.010 - Purpose and findings.
The purpose of this chapter is to advance the public welfare and education and to promote the interest, products, services, and stabilization of Washington's honey bee industry.

The legislature finds that:

. Increasing the consumption of products of the honey bee industry and promoting the use of its services and stabilizing the honey bee industry within the state and nation is a valid and necessary exercise of the power of the state to protect the public health, to provide for the economic development of the state, and to promote the welfare of the people of the state;

. Honey bee industry products produced and services provided in Washington make an important contribution to the agricultural industry of the state of Washington. The business of researching, marketing, and distributing such products and the promotion of its services is in the public interest;

. It is necessary to enhance the reputation of Washington honey bee industry products and services in domestic and national markets;

. It is necessary to promote and educate the public regarding the value of honey bee industry products and services, and to spread that knowledge throughout the state and nation to increase the awareness and consumption of honey bee products and the use of honey bee services;

. State and national markets for Washington honey bee industry products may benefit from promotion of honey bee products through education and advertising;

. It is necessary to stabilize the Washington honey bee industry, to enlarge its markets, and increase the consumption of Washington honey bee industry products and services to assure the payment of taxes to the state and its subdivisions, to alleviate unemployment, and to provide for higher wage scales for agricultural labor and maintenance of a reasonable standard of living;

. Providing information to the public on the manner, cost, and expense of producing, and the care taken to produce and sell, honey bee industry products and services of the highest quality, the methods and care used in their preparation for market, and the methods of sale and distribution is in the public interest;

. It is necessary to protect the public by educating it on the various benefits of honey bee industry services, the food value of its products, and their industrial and medicinal uses.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%201[1989 c 5 § 1]; ]

== 15.62.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter:

. "Affected person" means an apiarist, manufacturer, processor, first handler, broker, or volunteer who shall pay to the commission the minimum assessments required in RCW 15.62.140.

. "Apiarist" means any person, firm, partnership, association, or corporation who owns, operates, manages, or brokers ten or more honey bee (Apis mellifera) colonies or any volunteer participant having less than ten colonies in the state of Washington.

. "Bee colony" means a natural group of honey bees containing seven thousand or more workers and one or more queens, housed in a man-made hive with movable frames, and operated as a beekeeping unit.

. "Broker" means any person other than an apiarist who, for a fee, places or sets twenty-five or more bee colonies for pollination or buys and sells one thousand dollars or more per year of industry products he or she does not produce or manufacture.

. "Commission" means the Washington state honey bee industry commission or its authorized agents.

. "Department" means the department of agriculture.

. "Director" means the director of the department of agriculture.

. "First handler" means any person in Washington who imports industry products or bee supplies and equipment into Washington for processing, packing, or sale in the state of Washington.

. "Industry products" means queen bees, packaged bees, and items which are made by bees including, but not limited to, honey, pollen, bees wax, and propolis and items manufactured for use in the honey bee industry as enumerated under "manufacturer" in this section.

. "Manufacturer" means any person making bee supplies and equipment such as: Supers (hive boxes), frames, bees wax foundation, smokers, extractors, bee veils, pollen traps, queen rearing equipment, bee cages and packages, queen excluders, and other bee supplies used in the honey bee industry.

. "Person" means any individual, firm, partnership, or corporation engaged in the apiculture industry.

. "Processor" means any person processing, selling, marketing, or distributing bee industry products.

. "Retail sales" means those sales made directly to consumers whether apiarists, brokers, or persons involved in the apiculture industry, or the public.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%202[1989 c 5 § 2]; ]

== 15.62.030 - Commission established by referendum.
The Washington state honey bee commission shall be established following approval of a referendum by a majority of the affected apiarists and brokers, as set forth in RCW 15.62.140(4) for assessment increases.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%203[1989 c 5 § 3]; ]

== 15.62.040 - Powers and duties of commission.
The commission shall have the following powers and duties:

. To elect a chairperson and other officers as it deems advisable;

. To promulgate rules and regulations under the administrative procedure act, chapter 34.05 RCW, and RCW 15.04.200 as necessary to effectuate the purpose and policies of this chapter;

. To administer and enforce the provisions of this chapter and perform all acts and exercise all powers reasonably necessary to fulfill the purpose thereof;

. To employ and discharge advertising agents, attorneys as permitted by the attorney general, agents, and employees as it deems necessary, and to prescribe their duties and powers and fix their compensation;

. To establish offices, hire employees who shall be exempt from chapter 41.06 RCW, incur expenses which shall not exceed revenues, enter into contracts, and create such liabilities as are reasonable and proper for the administration of this chapter;

. To investigate and refer violations of this chapter to local prosecuting attorneys or special prosecutors appointed by the commission and the local prosecuting attorney;

. To contract for scientific research designed to improve production, pollination, management, quality, processing, and distribution and to develop and discover uses for products of the honey bee industry;

. To make in its name advertising contracts and other agreements necessary to promote the industry and bee products and services in state, national, and foreign markets;

. To keep accurate records of all commission dealings, which shall be open to public inspection and audit by authorized state agencies;

. To contract for research to develop more efficient methods of promoting the honey bee industry and its products and services;

. To develop and conduct educational programs for the benefit of industry and to inform the public regarding Washington's honey bee industry;

. To enter into contracts and agreements for purposes consistent with this chapter;

. To publish at least an annual report of its activities and financial status subject to audit by the state auditor;

. To establish an operating monetary reserve and carry over to subsequent fiscal periods any excess funds in the reserve: PROVIDED, That the reserve funds shall not exceed one fiscal period's budget. The reserve funds shall only be used to defray any expenses authorized under this chapter;

. To audit any affected person's records as described in RCW 15.62.200; and

. To consider the assessment of honey or manufactured bee supplies produced or sold in Washington. Assessments shall only be levied after a referendum is conducted and approved by a majority vote, as set forth in RCW 15.62.140(4), of persons engaged in the honey bee industry of Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%2013[1989 c 5 § 13]; ]

== 15.62.050 - Commission compositions—Eleven positions.
The commission shall consist of the following members:

. Apiarist position one shall represent area one, which includes the counties of Whatcom, San Juan[,] Island, Skagit, Snohomish, and King; and

. Apiarist position two shall represent area two, which includes the counties of Pierce, Kitsap, Clallam, Jefferson, Grays Harbor, Mason, Thurston, Pacific, Lewis, Wahkiakum, Cowlitz, Clark, [and] Skamania; and

. Apiarist positions three and four shall represent area three, which includes the counties of Kittitas, Yakima, Klickitat, and Benton; and

. Apiarist position five shall represent area four, which includes the counties of Okanogan, Chelan, and Douglas; and

. Apiarist position six shall represent area five, which includes the counties of Grant, Adams, Franklin, Walla Walla, Columbia, Garfield, Asotin, and Whitman; and

. Apiarist position seven shall represent area six, which includes the counties of Spokane, Lincoln, Ferry, Stevens, and Pend Oreille; [and]

. Position eight, appointed by the director, shall be a manufacturer or broker of industry products representing Washington residents engaged in the apiculture industry; and

. Position nine, appointed by the director, shall be a processor or first handler representing residents engaged in Washington's honey bee industry; and

. Position ten shall be the director of the Washington state department of agriculture, who shall be a nonvoting ex officio member; and

. Position eleven, appointed by the director, may be an affected person representing out-of-state interests who are not Washington residents but are active as affected persons in Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%204[1989 c 5 § 4]; ]

== 15.62.060 - Position qualifications.
. Commission positions one through seven shall be filled by persons who meet the following requirements:

.. Resident of this state;

.. Resident of the area they represent; and

.. Actually engaged in owning, operating, or as a broker of bee colonies for the five years immediately preceding their election.

. Commission positions eight and nine shall be filled by persons who meet the following requirements:

.. Resident of this state; and

.. Actually engaged as a manufacturer, broker of industry products, processor, or first handler for the five years immediately preceding their election.

. Commission members shall be immediately disqualified if they no longer meet the qualifications during their terms of office. The vacancy on the commission shall be filled according to *section 38 of this act.

. Position eleven shall be filled by a person who qualifies under subsection (1)(c) or (2)(b) of this section and is not a resident of Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%205[1989 c 5 § 5]; ]

== 15.62.070 - Terms of office—Vacancies.
. The regular terms of office of each elected member of the commission shall be three years, except that the term of office for the initial members shall be as follows:

.. Positions for areas one, four, and seven - one year.

.. Positions for areas two, five, and eight - two years.

.. Positions for areas three, six, and nine - three years.

.. If filled, position for area eleven - three years.

. No elected member of the board may serve more than two full consecutive three-year terms.

. Terms of office shall end on August 31 of the last year of the elected or appointed term.

. Any vacancies on the commission shall be filled by a person meeting the qualifications established in *section 37 of this act appointed by the other voting members of the commission. The appointee shall hold office for the remainder of the term, at which time an election for that position shall be conducted.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%206[1989 c 5 § 6]; ]

== 15.62.080 - Apiarist members—Election.
. Apiarist members of the commission shall be nominated and elected by the apiarists within the district they are to represent in the year in which a member's term expires. The candidate receiving the largest number of votes cast shall be elected. The election shall be by secret mail ballot and shall be conducted by the director, who shall be reimbursed for actual expenses of conducting the election by the commission.

. The director shall provide forms for the nomination of candidates to each affected person. The nomination form shall provide for the name of the person being nominated and the names of five persons supporting the nomination.

. The persons nominating the candidate shall affirm that the candidate meets the qualifications and is willing to serve by signing the nomination form.

. The nomination forms shall be returned to the director by June 30 of the election year, and the director shall not accept any nomination postmarked later than midnight of that date.

. In the event no nomination is submitted for a position, the director shall nominate at least two, but no more than three, qualified persons and place their names on the election ballot as nominees. Any qualified person may be elected by write-in ballot, even though his or her name was not placed in nomination.

. Ballots for electing commission members shall be mailed by the director to all apiarists and brokers in areas where elections are to be held no later than July 15. Ballots, to be valid, shall be returned to the director postmarked no later than July 31. Elected persons shall take office effective September 1 of the year elected except initial elections shall take place within one hundred twenty days after July 23, 1989.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%207[1989 c 5 § 7]; ]

== 15.62.090 - Notice, elections, referenda—Lists of apiarists, manufacturers, processors, and first handlers.
. [Empty]
.. The director shall cause a list to be prepared of all apiarists, as defined in RCW 15.62.020, from the list of apiarists registered with the department under *RCW 15.60.030. A qualified person may, at any time, have his or her name placed on the list by registering with the department.

.. The director shall cause a list to be prepared of manufacturers, processors, and first handlers. The list shall be prepared from any information the director has at hand or may readily obtain. A qualified person may, at any time, have his or her name placed on the list by notifying the department and providing such information as the department deems necessary to determine whether the person qualifies as a manufacturer, processor, or first handler under RCW 15.62.020.

.. For all purposes of giving notice and conducting elections or referenda, the lists the director has on hand under this section, corrected up to the day next preceding the date for issuing notices or ballots, are, for purposes of this chapter, deemed to be the lists of all persons entitled to notice or to assent or dissent or to vote.

. Any person may file his or her name and address with the commission for the purpose of receiving notices regarding the activities of the commission. Persons who are not Washington residents but are active as affected persons in this state and who wish to be considered for appointment to position eleven on the commission may file their names with the director. A person desiring such consideration must supply such information as the director deems appropriate.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%208[1989 c 5 § 8]; ]

== 15.62.100 - Costs of elections and referendums—Reimbursement.
The commission shall reimburse the director for the actual costs incurred in conducting the elections and referendums, and acquiring lists of affected persons.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%209[1989 c 5 § 9]; ]

== 15.62.110 - Quorum—Travel expenses.
. A majority of the commission members shall constitute a quorum for the transaction of all business of the commission.

. Members of the commission shall be reimbursed for travel expenses, as prescribed by the commission, for each day spent in attendance at, or traveling to and from, commission meetings or when conducting authorized commission business.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%2010[1989 c 5 § 10]; ]

== 15.62.120 - Certified copies of commission's proceedings, records, and acts—Admissible in court.
Copies of the proceedings, records, and acts of the commission, when certified by the secretary, shall be admissible in any court and be evidence of the truth of the statements therein contained.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%2011[1989 c 5 § 11]; ]

== 15.62.130 - Commission officers—Members' fidelity bonds.
The commission may elect an executive secretary who is not a member and fix his or her compensation and may appoint a treasurer who shall sign all vouchers and receipts for moneys received by the commission. The commission shall purchase for each of its members a fidelity bond executed by a surety company authorized to do business in the state, in favor of the state and the commission, in a sum to be determined by the commission.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%2012[1989 c 5 § 12]; ]

== 15.62.140 - Assessments—Minimum—Increase.
. The commission shall collect annual assessments as follows:

.. Twenty-five cents for each colony operated by an apiarist or broker in Washington at any time in a calendar year. Each colony shall be assessed only once per calendar year. There shall be a minimum assessment of ten dollars.

.. The sale of a business enterprise by an apiarist or broker shall not be assessed.

The provisions of this subsection (1) are effective only if the referendum required by RCW 15.62.030 on the creation of the commission is adopted.

. Subject to approval by referendum, the commission shall have the power and duty to increase the amount of the assessments as necessary to fulfill the purposes of this chapter.

. In determining the necessity for an assessment increase, the commission shall consider:

.. The purpose of the commission;

.. The extent and probable cost of required research, promotion, and advertising;

.. The extent of public convenience, interest, and necessity; and

.. The expected revenue from the increased assessment.

. The increase in assessment shall not become effective until approved by a majority of the affected persons voting in a referendum conducted by the commission. The referendum must be approved by:

.. Either fifty-one percent of the apiarists and brokers representing sixty-six percent of the colonies registered in Washington in the twelve months preceding voting; or

.. Sixty-six percent of the apiarists and brokers representing fifty-one percent of the colonies registered in Washington in the twelve months preceding voting; and

.. Either fifty-one percent of manufacturers, processors, and first handlers representing sixty-six percent of industry products sold in Washington by its residents; or

.. Sixty-six percent of manufacturers, processors, and first handlers representing fifty-one percent of industry products sold in Washington by its residents.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%2014[1989 c 5 § 14]; ]

== 15.62.150 - Assessments—Collection—Deposit in local fund—Gifts, grants, and endowments—Failure to remit assessment.
. All assessments shall be collected by the commission on a quarterly basis or as otherwise determined by the commission.

. The commission shall create a local fund in a local financial institution approved by the director and shall deposit therein, each day, all moneys received by the commission except an amount for petty cash as fixed by commission regulations. Moneys in the fund shall only be expended for the purposes of this chapter. Moneys in the fund are not subject to appropriation.

. The commission fund is authorized to receive such gifts, grants, and endowments from public or private sources as may be made from time to time, in trust or otherwise, for the use and benefit of the purposes of the commission and expend the same or any income therefrom according to the terms of the gifts, grants, or endowments.

. If an affected person fails to remit any assessment, such assessment plus interest at the rate of one percent per month from the due date shall constitute a personal debt of the person assessed or who otherwise owes the assessment and shall be due and payable within thirty days from the date it becomes first due the commission. In the event of failure of the person to pay due and payable assessments, the commission may bring civil action against the person in a state court of competent jurisdiction for collection thereof, together with any reasonable costs including attorneys' fees. The action shall be tried and judgment rendered as in any other cause of action for debt due and payable. This provision is in addition to the penalty section contained in RCW 15.62.220.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%2015[1989 c 5 § 15]; ]

== 15.62.160 - Assessment error—Refund.
A person shall be entitled to a refund of assessed money held by the commission fund when it has been determined by the commission that the affected person was assessed and made payment in error.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%2016[1989 c 5 § 16]; ]

== 15.62.170 - Recordkeeping.
. Each apiarist and broker shall keep accurate records of the number of colonies owned or operated during each calendar year.

. Each manufacturer shall keep accurate records of gross sales of industry products or manufactured goods sold in the state of Washington.

. Each processor shall keep accurate records of the pounds of honey sold in the state of Washington.

. Each first-handler shall keep accurate records of the industry products sold in the state of Washington.

. The records shall contain information required by the commission and shall be preserved for a period of five years.

. The records shall be made available for audit upon request of the commission or its agent, as authorized in RCW 15.62.040 and 15.62.200.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%2017[1989 c 5 § 17]; ]

== 15.62.180 - Reporting.
Each affected person shall, as required, file with the commission a return under oath on forms to be furnished by the commission, stating the information requested by the commission regarding the ownership, handling, processing, manufacturing, delivering, shipping, sale, and brokering of various honey bee industry products and activities as defined in RCW 15.62.020. The report shall cover the period or periods of time prescribed by the commission.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%2018[1989 c 5 § 18]; ]

== 15.62.200 - Audit of records of affected persons.
The commission through its agents may audit the records of any affected person for the purpose of enforcing the provisions of this chapter. The commission must first notify the affected person of their intention to audit and may request supporting documents of the affected person regarding reports submitted on commission forms under RCW 15.62.180.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%2020[1989 c 5 § 20]; ]

== 15.62.210 - Nonliability of state—Salaries, expenses, and liabilities.
The state shall not be liable for the acts or on the contracts of the commission, nor shall any member or employee of the commission be liable on its contracts.

All salaries, expenses, and liabilities incurred by persons employed or contracting under this chapter for the commission shall be limited to, and payable only from, the funds collected hereunder.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%2021[1989 c 5 § 21]; ]

== 15.62.220 - Violations—Misdemeanor.
Any person who violates or aids in the violation of any provision of this chapter or any rule or regulation of the commission shall be guilty of a misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%2022[1989 c 5 § 22]; ]

== 15.62.230 - Prosecutions—Superior court jurisdiction—Equitable remedies.
. Any prosecution brought under this chapter may be instituted in any county in which the defendant or any defendant resides, or in which the violation was committed, or in which the defendant or any defendant has his or her principal place of business.

. The commission is hereby vested with the authority to utilize the services of the local prosecuting attorneys or special prosecutors as agreed upon by the commission and the local prosecutor for purposes of carrying out the prosecution of cases brought under this chapter.

. The superior courts are hereby vested with jurisdiction to enforce the provisions of this chapter, and the rules and regulations of the commission issued hereunder, and to prevent and enjoin and restrain violations thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%2023[1989 c 5 § 23]; ]

== 15.62.300 - Termination, suspension, or continuance of commission.
In the seventh year following the inception of the commission, a referendum shall be conducted by the department of agriculture to determine if the commission is still desired by the beekeeping industry in Washington. The commission shall continue if the director finds that affected apiarists and brokers voting in a referendum conducted as for an assessment increase in RCW 15.62.140(4) voted in favor of such continuance, otherwise it shall be terminated or suspended as in RCW 15.62.310.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%2025[1989 c 5 § 25]; ]

== 15.62.310 - Termination or suspension of commission.
The commission shall be terminated or suspended if the director finds that apiarists and brokers voting in a referendum conducted as for an assessment increase in RCW 15.62.140(4) voted in favor of such termination or suspension. A referendum may be called by a majority of the commission or by twenty percent of the resident affected persons representing twenty percent of the colonies and industry products sold in Washington.

Any moneys in the treasury at the time of an affirmative termination or suspension vote shall first be used to effect all acts associated with the termination or suspension procedures and liquidation of the affairs of the commission.

Any residual funds not necessary to defray the expenses of termination or suspension of the commission shall be turned over to Washington State University to be used in conducting research on the honey bee Apis mellifera.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%2026[1989 c 5 § 26]; ]

== 15.62.900 - Liberal construction.
This chapter shall be liberally construed to effectuate the policies and purpose set forth herein.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c5.pdf?cite=1989%20c%205%20§%2024[1989 c 5 § 24]; ]

