= 15.83 - Agricultural marketing and fair practices.
:toc:

== 15.83.005 - Intent.
Agricultural products are produced by many individual farmers and ranchers located throughout the state. The efficient production and marketing of agricultural products by farmers, ranchers, and handlers is of vital concern to the welfare and general economy of the state. It is the purpose of this chapter to establish standards of fair practices required of handlers, producers, and associations of producers, with respect to certain agricultural commodities, to establish the mutual obligation of handlers and accredited associations of producers to negotiate relative to the production or marketing of these agricultural commodities.

It is the intent of the legislature that a workable process be developed through which a fair price and other contract terms can be arrived at through negotiations between processors of agricultural products and an accredited association of producers, and that in developing rules and administering this chapter the director of agriculture shall recognize this intent.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c355.pdf?cite=1989%20c%20355%20§%201[1989 c 355 § 1]; ]

== 15.83.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Accredited association of producers" means an association of producers which is accredited by the director to be the exclusive negotiation agent for all producer members of the association within a negotiating unit.

. "Advance contract" means a contract for purchase and sale of a crop entered into before the crop becomes a growing crop and providing for delivery at or after the harvest of that crop.

. "Agricultural products" as used in this chapter means pears, sweet corn, and potatoes produced for sale from farms in this state.

. "Association of producers" means any association of producers of agricultural products engaged in marketing, negotiating for its members, shipping, or processing as defined in section 15(a) of the federal agriculture marketing act of 1929 or in section 1 of 42 Stat. 388.

. "Director" means the director of the department of agriculture.

. "Handler" means a processor or a person engaged in the business or practice of:

.. Acquiring agricultural products from producers or associations of producers for use by a processor;

.. Processing agricultural products received from producers or associations of producers, provided that a cooperative association owned by producers shall not be a handler except when contracting for crops from producers who are not members of the cooperative association;

.. Contracting or negotiating contracts or other arrangements, written or oral, with or on behalf of producers or associations of producers with respect to the production or marketing of any agricultural product for use by a processor; or

.. Acting as an agent or broker for a handler in the performance of any function or act specified in (a), (b), or (c) of this subsection.

. "Negotiate" means meeting at reasonable times and for reasonable periods of time commencing at least sixty days before the normal planting date for sweet corn and potatoes, or at least sixty days before the normal harvest date for pears, and concluding within thirty days of the normal planting date for sweet corn and potatoes, or within thirty days of the normal harvest date for pears, to make a serious, fair, and reasonable attempt to reach agreement by acknowledging or refuting with reason points brought up by either party with respect to the price, terms of sale, compensation for products produced under contract, or other terms relating to the production or sale of these products: PROVIDED, That neither party shall be required to disclose proprietary business or financial records or information.

. "Negotiating unit" means a negotiating unit approved by the director under RCW 15.83.020.

. "Person" means an individual, partnership, corporation, association, or any other entity.

. "Processor" means any person that purchases agricultural crops from a producer and cans, freezes, dries, dehydrates, cooks, presses, powders, or otherwise processes those crops in any manner for eventual resale. A person who solely cleans, sorts, grades, and packages a farm product for sale without altering the natural condition of the product is not a processor. A person processing any portion of a crop is a processor.

. "Producer" means a person engaged in the production of agricultural products as a farmer or planter, including a grower or farmer furnishing inputs, production management, or facilities for growing or raising agricultural products. A producer who is also a handler shall be considered a handler under this chapter.

. "Qualified commodity" means agricultural products as defined in subsection (3) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2524.SL.pdf?cite=2020%20c%20176%20§%201[2020 c 176 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c355.pdf?cite=1989%20c%20355%20§%202[1989 c 355 § 2]; ]

== 15.83.020 - Negotiating agents—Association of producers—Accreditation.
. An association of producers may file an application with the director:

.. Requesting accreditation to serve as the exclusive negotiating agent on behalf of its producer members who are within a proposed negotiating unit with respect to any qualified commodity;

.. Describing geographical boundaries of the proposed negotiating unit;

.. Specifying the number of producers and the quantity of products included within the proposed negotiating unit;

.. Specifying the number and location of the producers and the quantity of products represented by the association;

.. Agreeing to reimburse the department for all anticipated and uncovered costs incurred by the department for actions necessary to carry out the provisions of this chapter; and

.. Supplying any other information required by the director.

. Within a reasonable time after receiving an application under subsection (1) of this section, the director shall approve or disapprove the application in accordance with this section.

.. The director shall approve the initial application or renewal if the director determines that:

... The association is owned and controlled by producers under the charter documents or bylaws of the association;

... The association has valid and binding contracts with its members empowering the association to sell or negotiate terms of sale of its members' products or to negotiate for compensation for products produced under contract by its members;

... The association represents a sufficient percentage of producers or that its members produce a sufficient percentage of agricultural products to enable it to function as an effective agent for producers in negotiating with a given handler as defined in rules promulgated by the department. In making this finding, the director shall exclude any quantity of the agricultural products contracted by producers with producer-owned and controlled processing cooperatives with its members and any quantity of these products produced by handlers;

... One of the association's functions is to act as principal or agent for its members in negotiations with handlers for prices and other terms of trade with respect to the production, sale, and marketing of the products of its members, or for compensation for products produced by its members under contract;

.. Sufficient resources, including public funds and any funds to be provided by the applicant under reimbursement agreements, will be available to cover department costs for services provided by the department in carrying out the provisions of this chapter, including department costs to defend a decision made by the department under this chapter if such a decision is appealed; and

.. Accreditation would not be contrary to the policies established in RCW 15.83.005.

.. If the director does not approve the application under (a) of this subsection, then the association of producers may file an amended application with the director. The director, within a reasonable time, shall approve the amended application if it meets the requirements set out in (a) of this subsection.

. The department shall provide the association an estimate of expenses that may be incurred prior to the department's provision of services.

. At the discretion of the director, or upon submission of a timely filed petition by an affected handler or an affected association of producers, the association of producers accredited under this section may be required by the director to renew the application for accreditation by providing the information required under subsection (1) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2524.SL.pdf?cite=2020%20c%20176%20§%202[2020 c 176 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c355.pdf?cite=1989%20c%20355%20§%203[1989 c 355 § 3]; ]

== 15.83.030 - Unlawful practices of handlers.
It shall be unlawful for any handler to engage, or permit any employee or agent to engage, in the following practices:

. To refuse to negotiate with an association of producers accredited under RCW 15.83.020 with respect to any qualified commodity: PROVIDED, That the obligation to negotiate does not require either party to agree to a proposal, to make a concession, or to enter into a contract;

. To coerce any producer in the exercise of his or her right to contract with, join, refrain from contracting with or joining, belong to an association of producers, or refuse to deal with any producer because of the exercise of that producer's right to contract with, join, or belong to an association or because of that producer's promotion of legislation on behalf of an association of producers;

. To discriminate against any producer with respect to price, quantity, quality, or other terms of purchase, acquisition, or other handling of agricultural products because of that producer's membership in or contract with an association of producers or because of that producer's promotion of legislation on behalf of an association of producers;

. To coerce or intimidate any producer to enter into, maintain, breach, cancel, or terminate a membership agreement or marketing contract with an association of producers or a contract with a handler;

. To pay or loan money, give anything of value, or offer any other inducement or reward to a producer for refusing or ceasing to belong to an association of producers;

. To make knowingly false reports about the finances, management, or activities of associations of producers or handlers;

. To conspire, agree, or arrange with any other person to do, aid, or abet any act made unlawful by this chapter; or

. To refuse, in the event that an acceptable price cannot be agreed to between a producer and a processor, to meet with a mutually agreed upon third-party mediator to resolve the price dispute. Any fees associated with the third-party mediation must be borne by the producer.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2524.SL.pdf?cite=2020%20c%20176%20§%203[2020 c 176 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c355.pdf?cite=1989%20c%20355%20§%204[1989 c 355 § 4]; ]

== 15.83.040 - Unlawful practices of association of producers or members.
It shall be unlawful for any accredited association of producers or members of such association to engage, or permit any employee or agent to engage, in the following practices:

. To refuse to negotiate with a handler for any qualified commodity for which the association is accredited under RCW 15.83.020;

. To coerce or intimidate a handler to breach, cancel, or terminate a marketing contract with an individual producer, association of producers, or a member of an association;

. To knowingly make or circulate false reports about the finances, management, or activities of an association of producers or a handler;

. To coerce or intimidate a producer to enter into, breach, cancel, or terminate a membership agreement or marketing contract with an association of producers;

. To conspire, agree, or arrange with any other person to do, aid, or abet any practice which is in violation of this chapter; or

. To pay or loan money, give anything of value, or offer any other inducement or reward to a producer for refusing to contract or negotiate with a processor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c355.pdf?cite=1989%20c%20355%20§%205[1989 c 355 § 5]; ]

== 15.83.050 - Violations of chapter—Complaint.
. If any person is charged with violating any provision of this chapter, the director shall investigate the charges. If, upon investigation, the director has reasonable cause to believe that the person charged has violated the provision, the director shall issue and cause to be served upon the person, a complaint stating the charges. A hearing on the charges shall be conducted in accordance with the provisions of chapter 34.05 RCW concerning contested cases.

. No complaint may be issued based upon any act occurring more than six months before the filing of the charge with the director. At the discretion of the director, any other person may be allowed to intervene in the proceeding and to present testimony and other evidence.

. If upon the preponderance of the evidence taken, the director is of the opinion that any person named in the complaint has engaged in or is engaging in any prohibited practice, the director shall make and enter findings of fact and shall issue and cause to be served on that person, an order requiring that person to cease and desist from the practice and to take affirmative action to further the policies of this chapter. The order may also require the person to make reports from time to time showing the extent of compliance with the order. If, upon the preponderance of the testimony and other evidence, the director determines that the person named in the complaint has not engaged in or is not engaging in any prohibited practice, the director shall make and enter findings of fact and an order dismissing the complaint.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c355.pdf?cite=1989%20c%20355%20§%206[1989 c 355 § 6]; ]

== 15.83.060 - Director's authority—Recordkeeping—Cooperation.
If required to carry out the objectives of this chapter, including the conduct of any investigations or hearing:

. The director shall require any person to:

.. Establish and maintain records;

.. Make reports; and

.. Provide other information as may be reasonably required.

. Any person subject to the provisions of this chapter shall provide the information, records, and reports reasonably required by the director, or make such material available to the director for inspection and/or copying at reasonable times and places, except that no person shall be required under this section to provide to the director proprietary business or financial records or information.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c355.pdf?cite=1989%20c%20355%20§%207[1989 c 355 § 7]; ]

== 15.83.070 - Injury due to unlawful practices—Damages.
A person injured in his or her business or property by reason of any violation of or conspiracy to violate RCW 15.83.030 or 15.83.040 may sue in a court of competent jurisdiction of the county in which such violation occurred without respect to the amount in controversy, and shall recover damages sustained, including reasonable attorneys' fees and costs of bringing the suit. Any action to enforce any cause of action under this section shall be forever barred unless commenced not later than two years after the cause of action accrues.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c355.pdf?cite=1989%20c%20355%20§%208[1989 c 355 § 8]; ]

== 15.83.080 - Unlawful practices—Civil penalty.
A person who violates RCW 15.83.030 or 15.83.040 may be assessed a civil penalty by the director of not more than five thousand dollars for each offense. No civil penalty may be assessed unless the person charged has been given notice and opportunity for a hearing pursuant to chapter 34.05 RCW. In determining the amount of the penalty, the director shall consider the size of the business of the person charged, the penalty's affect [effect] on the person's ability to continue in business, and the gravity of the violation. If the director is unable to collect the civil penalty, the director shall refer the collection to the attorney general.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c355.pdf?cite=1989%20c%20355%20§%209[1989 c 355 § 9]; ]

== 15.83.090 - Injunction.
The director or any aggrieved producer, accredited association, or handler may bring an action to enjoin the violation of any provision of this chapter or any regulation made pursuant to this chapter in a court of competent jurisdiction of the county in which such violation occurs or is about to occur.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c355.pdf?cite=1989%20c%20355%20§%2010[1989 c 355 § 10]; ]

== 15.83.100 - Rules.
The director may promulgate such rules in accordance with chapter 34.05 RCW, and orders, as may be necessary to carry out this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c355.pdf?cite=1989%20c%20355%20§%2011[1989 c 355 § 11]; ]

== 15.83.110 - Advisory committee.
The director shall establish an advisory committee consisting of the following persons: Six producers who are producers from names submitted by an association of producers, and six handlers subject to this chapter from names submitted by handlers. The advisory committee shall study and report on all issues related to this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c355.pdf?cite=1989%20c%20355%20§%2012[1989 c 355 § 12]; ]

== 15.83.900 - Short title.
This chapter may be known and cited as the agricultural marketing and fair practices act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c355.pdf?cite=1989%20c%20355%20§%2013[1989 c 355 § 13]; ]

