= 15.44 - Dairy products commission.
:toc:

== 15.44.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Commission" means the Washington state dairy products commission.

. "Current level of assessment" means the level of assessment paid by the producer as set by the commission which cannot exceed the maximum authorized assessment rate.

. "Dealer" means a person doing business in the state of Washington who handles, ships, buys, and sells dairy products, or who acts as sales or purchasing agent, broker, or factor of dairy products.

. "Handler" means a person doing business in the state of Washington who purchases milk, cream, or skimmed milk for processing, manufacturing, sale, or distribution.

. "Mail" or "send" for purposes of any notice relating to rule making, referenda, or elections means regular mail or electronic distribution, as provided in RCW 34.05.260 for rule making. "Electronic distribution" or "electronically" means distribution by electronic mail or facsimile mail.

. "Maximum authorized assessment rate" means the level of assessment most recently approved by a referendum of producers.

. "Person" means an individual, firm, corporation, limited liability company, trust, association, partnership, society, or any other organization of individuals, or any unit or agency of local, state, or federal government.

. "Processor" means a person doing business in the state of Washington who uses milk or cream for canning, drying, manufacturing, preparing, or packaging or for use in producing or manufacturing any product therefrom.

. "Producer" means a person doing business in the state of Washington who produces milk from cows and sells it for human or animal food, or medicinal or industrial uses.

. "Ship" means to deliver or consign milk or cream to a person dealing in, processing, distributing, or manufacturing dairy products for sale, for human consumption, or industrial or medicinal uses.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2367-S.SL.pdf?cite=2012%20c%20107%20§%201[2012 c 107 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%2088[2002 c 313 § 88]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c261.pdf?cite=1985%20c%20261%20§%2017[1985 c 261 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c238.pdf?cite=1979%20ex.s.%20c%20238%20§%201[1979 ex.s. c 238 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.44.010[1961 c 11 § 15.44.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c219.pdf?cite=1939%20c%20219%20§%202[1939 c 219 § 2]; RRS § 6266-2; ]

== 15.44.015 - Regulating dairy products—Commission created—Existing comprehensive scheme—Laws applicable.
The history, economy, culture, and the future of Washington state's agriculture involves the dairy industry. In order to develop and promote Washington's dairy products as part of an existing comprehensive scheme to regulate those products the legislature declares:

. That the Washington state dairy products commission is created. The commission may also take actions under the name "the dairy farmers of Washington";

. That it is vital to the continued economic well-being of the citizens of this state and their general welfare that its dairy products be properly promoted by (a) enabling the dairy industry to help themselves in establishing orderly, fair, sound, efficient, and unhampered marketing, grading, and standardizing of the dairy products they produce; and (b) working to stabilize the dairy industry by increasing consumption of dairy products within the state, the nation, and internationally;

. That dairy producers operate within a regulatory environment that imposes burdens on them for the benefit of society and the citizens of the state and includes restrictions on marketing autonomy. Those restrictions may impair the dairy producer's ability to compete in local, domestic, and foreign markets;

. That it is in the overriding public interest that support for the dairy industry be clearly expressed, that adequate protection be given to agricultural commodities, uses, activities, and operations, and that dairy products be promoted individually, and as part of a comprehensive industry to:

.. Enhance the reputation and image of Washington state's agriculture industry;

.. Increase the sale and use of Washington state's dairy products in local, domestic, and foreign markets;

.. Protect the public by educating the public in reference to the quality, care, and methods used in the production of Washington state's dairy products;

.. Increase the knowledge of the health-giving qualities and dietetic value of dairy products; and

.. Support and engage in programs or activities that benefit the production, handling, processing, marketing, and uses of dairy products produced in Washington state;

. That this chapter is enacted in the exercise of the police powers of this state for the purpose of protecting the health, peace, safety, and general welfare of the people of this state; and

. That the dairy industry is a highly regulated industry and that this chapter and the rules adopted under it are only one aspect of the regulated industry. Other regulations and restraints applicable to the dairy industry include the:

.. Federal marketing order under 7 C.F.R., Part 1124;

.. Dairy promotion program under the dairy and tobacco adjustment act of 1983, Subtitle B;

.. Milk and milk products act under chapter 15.36 RCW and rules, including:

... The national conference of interstate milk shippers pasteurized milk ordinance;

... The national conference of interstate milk shippers dry milk ordinance;

... Standards for the fabrication of single-service containers;

... Procedures governing cooperative state-public health service;

.. Methods of making sanitation ratings of milk supplies;

.. Evaluation and certification of milk laboratories; and

.. Interstate milk shippers;

.. Milk and milk products for animal food act under chapter 15.37 RCW and rules;

.. Organic products act under chapter 15.86 RCW and rules;

.. The food safety and security act under chapter 15.130 RCW;

.. Washington food processing act under chapter 69.07 RCW and rules;

.. Washington food storage warehouses act under chapter 69.10 RCW and rules;

.. Animal health under chapter 16.36 RCW and rules;

.. Weighmasters under chapter 15.80 RCW and rules; and

.. Dairy nutrient management act under chapter 90.64 RCW and rules.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20705[2018 c 236 § 705]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5374-S.SL.pdf?cite=2011%20c%20103%20§%2029[2011 c 103 § 29]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%2087[2002 c 313 § 87]; ]

== 15.44.020 - Commission composition.
The commission shall be composed of producers and at least one dealer. The director shall be a voting member of the commission.

As used in this chapter, "director" means the director of agriculture or his or her authorized representative.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2367-S.SL.pdf?cite=2012%20c%20107%20§%202[2012 c 107 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6284.SL.pdf?cite=2008%20c%2012%20§%201[2008 c 12 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1361.SL.pdf?cite=2003%20c%20396%20§%2024[2003 c 396 § 24]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%2089[2002 c 313 § 89]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c238.pdf?cite=1979%20ex.s.%20c%20238%20§%202[1979 ex.s. c 238 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c136.pdf?cite=1975%201st%20ex.s.%20c%20136%20§%201[1975 1st ex.s. c 136 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c44.pdf?cite=1965%20ex.s.%20c%2044%20§%202[1965 ex.s. c 44 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.44.020[1961 c 11 § 15.44.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c163.pdf?cite=1959%20c%20163%20§%202[1959 c 163 § 2]; prior:  1939 c 219 § 3, part; RRS § 6266-3, part.  1939 c 219 § 4, part; RRS § 6266-4, part; ]

== 15.44.021 - Director appoints members—Nominations—Advisory vote.
. The director shall appoint the members of the commission.

. Candidates for producer member positions on the commission shall be nominated under RCW 15.44.033. The director may select a nominated candidate for a position or may reject all candidates.

. If two candidates are nominated, the director may choose one, reject both, or call for an advisory vote between the two candidates. In the event there are more than two candidates nominated for the producer member positions, the director shall cause an advisory vote to be held. Advisory ballots shall be mailed to all producers in the district or area where a vacancy is about to occur and shall be returned to the director not less than thirty days prior to the commencement of the term. The advisory ballot shall be conducted in a manner so that it is a secret ballot. The names of the two candidates receiving the most votes in the advisory vote shall be forwarded to the director for potential appointment to the commission. 

. The director may request that any candidate whose name is forwarded to the director for potential appointment submit a letter stating why he or she wishes to be appointed to the commission. 

. If the director rejects one or more of the candidates nominated under RCW 15.44.033, the director may request that the commission provide additional qualified nominees for consideration. Upon receipt of the nomination or nominations, the director may select a candidate, cause an advisory vote to be held, or reject the nominees. If the commission does not submit additional nominees to the director within thirty days of the director's request, the director shall nominate additional candidates for an advisory vote.

. The commission may appoint up to three nonvoting members who have expertise in marketing, operations, or other topics relevant to the work of the commission. The term of office for each nonvoting position is one year and may be renewed by the commission.

. The director shall appoint one person to a dealer position, unless the commission adopts rules providing for additional dealer positions on the commission.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2367-S.SL.pdf?cite=2012%20c%20107%20§%203[2012 c 107 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6284.SL.pdf?cite=2008%20c%2012%20§%202[2008 c 12 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1361.SL.pdf?cite=2003%20c%20396%20§%2025[2003 c 396 § 25]; ]

== 15.44.022 - Transition to defined districts and areas.
. To accomplish the transition to the newly defined districts and areas as described in RCW 15.44.027, the initial producer appointments are as follows:

.. The current incumbent representing district one must be appointed to the new district four position with an expiration date of June 30, 2015;

.. The current incumbent representing district two must be appointed to the eastern Washington at large position with an expiration date of June 30, 2015;

.. The current incumbent representing district three must be appointed to the new district one position with an expiration date of June 30, 2013;

.. The current incumbent representing district four must be appointed to the new district three position with an expiration date of June 30, 2013;

.. The current incumbent representing district five must be appointed to the state at large position with an expiration date of June 30, 2014;

.. The current incumbent representing district six must be appointed to the new western Washington at large position with an expiration date of June 30, 2014;

.. The current incumbent representing district seven must be appointed to the new district two position with an expiration date of June 30, 2014; and

.. The current incumbent representing dealers must be appointed to the dealer position with an expiration date of June 30, 2013.

. Thereafter, producer and dealer members are nominated and appointed as provided for under RCW 15.44.021 and 15.44.033.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2367-S.SL.pdf?cite=2012%20c%20107%20§%204[2012 c 107 § 4]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1361.SL.pdf?cite=2003%20c%20396%20§%2028[2003 c 396 § 28]; ]

== 15.44.023 - Associations with same objective—Dual membership—Contracting.
Any board member of the commission may be a member or officer of an association that has the same objectives for which the commission was formed. The commission may contract with the association for services necessary to carry out any purposes authorized under this chapter if an appropriate written contract has been entered into.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%20101[2002 c 313 § 101]; ]

== 15.44.027 - Appointment of producer member—Commission's authority—Reasonably equal producer representation.
. One producer member of the commission must be appointed from each of the following districts or areas:

.. District one, which includes the counties of Whatcom, Skagit, Snohomish, San Juan, Island, and that portion of King county located north of Interstate 90;

.. District two, which includes the counties of Clallam, Jefferson, Grays Harbor, Kitsap, Mason, Thurston, Pierce, Lewis, Wahkiakum, Cowlitz, Clark, Skamania, and that portion of King county located south of Interstate 90;

.. District three, which includes the counties of Yakima, Klickitat, and Benton;

.. District four, which includes the counties of Kittitas, Grant, Franklin, Walla Walla, Columbia, Garfield, Asotin, Whitman, Adams, Lincoln, Spokane, Douglas, Chelan, Okanogan, Ferry, Stevens, and Pend Oreille;

.. Western Washington at large, which includes that portion of the state of Washington located west of the crest of the Cascade mountains;

.. Eastern Washington at large, which includes that portion of the state of Washington located east of the crest of the Cascade mountains; and

.. The state at large, which includes the entire state.

. The commission may adopt rules to eliminate, combine, revise, amend, or otherwise modify commission districts and areas in accordance with the intent and provisions of this chapter. In the event of redistricting, the procedure for transition of appointments to new districts or areas must be set forth in rule. The commission may adopt rules allowing the appointment of additional dealers to the commission.

. The boundaries and numbers of the commission districts or areas shall be maintained in a manner that ensures each producer a representation in the commission which is reasonably equal with the representation afforded all other producers by their commission members and maintains reasonable apportionment for each historical production or marketing area. However, the requirement of this section for reasonable equal representation of each producer on the commission does not require an equality of representation when the commission districts east of the crest of the Cascade mountains are compared to the commission districts west of the crest of the Cascade mountains.

. The commission shall, when requested in accordance with the provisions of the administrative procedure act, chapter 34.05 RCW as enacted or hereafter amended, or on its own initiative, hold hearings to determine if new boundaries for each commission district or area should be established in order to afford each producer a reasonably equal representation in the commission, and if the commission so finds it shall change the boundaries of the commission districts or areas to carry out the proper reapportionment of producer representation on the commission.

. A review of boundaries and areas must be conducted by the commission at least every five years and take into consideration the distribution of producers, the number of head, production levels, and other relevant factors as determined by the commission. If the commission fails to carry out its responsibilities as set forth in this section, the director may upon request by ten producers institute a hearing to determine if there is reasonably equal representation for each producer on the commission. If the director finds that such reasonably equal representation is lacking, he or she then shall realign the district boundaries in a manner which will provide proper representation on the commission for each producer.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2367-S.SL.pdf?cite=2012%20c%20107%20§%205[2012 c 107 § 5]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%206057[2010 c 8 § 6057]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c136.pdf?cite=1975%201st%20ex.s.%20c%20136%20§%207[1975 1st ex.s. c 136 § 7]; ]

== 15.44.030 - Member qualifications.
Each of the producer members of the commission shall:

. Be a citizen and resident of this state and the district or area which he or she represents; and

. Be and for the five years last preceding his or her election have been actually engaged as an owner or shareholder in producing dairy products within this state. These qualifications must continue during each member's term of office.

The dealer member shall be actively engaged as a dealer in dairy products or employed in a dealer capacity as an officer or employee at management level in a dairy products organization.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2367-S.SL.pdf?cite=2012%20c%20107%20§%206[2012 c 107 § 6]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6284.SL.pdf?cite=2008%20c%2012%20§%203[2008 c 12 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c136.pdf?cite=1975%201st%20ex.s.%20c%20136%20§%202[1975 1st ex.s. c 136 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c44.pdf?cite=1965%20ex.s.%20c%2044%20§%204[1965 ex.s. c 44 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.44.030[1961 c 11 § 15.44.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c163.pdf?cite=1959%20c%20163%20§%204[1959 c 163 § 4]; prior: 1939 c 219 § 3, part; RRS § 6266-3, part; ]

== 15.44.032 - Terms—Vacancies.
. Except as provided in this section for initial appointments after redistricting or boundary modification, the term of office of each producer member of the commission shall be three years. Commission members shall continue to serve their terms until new appointments are made.

. Any vacancies that occur on the commission shall be filled by appointment by the director from a list containing the names of a candidate or candidates forwarded to the director by the commission. The director has the discretion to appoint or reject the candidate or candidates and, if the candidate or candidates are rejected, request additional candidates. The appointee shall hold office for the remainder of the term for which he or she is appointed to fill, so that commission memberships shall be on a uniform staggered basis.

. The term of office of each dealer shall be three years or until such time as a successor is duly appointed. Any vacancy for a dealer shall be forthwith filled by the director. The director, in making any dealer appointments, may consider lists of nominees supplied by dealers or producers also acting as dealers.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2367-S.SL.pdf?cite=2012%20c%20107%20§%207[2012 c 107 § 7]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6284.SL.pdf?cite=2008%20c%2012%20§%204[2008 c 12 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c136.pdf?cite=1975%201st%20ex.s.%20c%20136%20§%203[1975 1st ex.s. c 136 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c44.pdf?cite=1965%20ex.s.%20c%2044%20§%205[1965 ex.s. c 44 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.44.032[1961 c 11 § 15.44.032]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c163.pdf?cite=1959%20c%20163%20§%205[1959 c 163 § 5]; ]

== 15.44.033 - Nomination and appointment procedure.
. Producer members of the commission shall be nominated by producers within the district or area that such producer members represent.

. Nomination for candidates to be appointed to the commission shall be conducted by mail by the director. Such nomination forms shall be mailed by the director to each producer in a district or area where a vacancy is about to occur. Such mailing shall be made on or after April 1st, but not later than April 10th of the year the incumbent's term will expire. The nomination form shall provide for the name of the nominee and the names of five other producers nominating such nominee. The producers nominating such nominee shall sign the form and shall further attest that the nominee meets the qualifications for a producer member to serve on the commission and that he or she will be willing to serve on the commission if appointed.

. All nominations as provided for in this section shall be returned to the director by April 30th, and the director shall not accept any nomination postmarked later than midnight April 30th, nor place the candidate thereon on the advisory ballot.

. Advisory vote ballots for appointing nominees to the commission will be mailed by the director to all eligible producers no later than May 15th, in districts or areas where advisory votes are to be held and such ballots to be valid shall be returned postmarked no later than May 31st of the year mailed, to the director in Olympia.

. The director shall determine whether the persons nominated possess the qualifications required by statute for the position.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2367-S.SL.pdf?cite=2012%20c%20107%20§%208[2012 c 107 § 8]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1361.SL.pdf?cite=2003%20c%20396%20§%2026[2003 c 396 § 26]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5315-S.SL.pdf?cite=1995%20c%20374%20§%2059[1995 c 374 § 59]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c240.pdf?cite=1967%20c%20240%20§%2030[1967 c 240 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c44.pdf?cite=1965%20ex.s.%20c%2044%20§%206[1965 ex.s. c 44 § 6]; ]

== 15.44.035 - Producer lists—Each producer responsible for accuracy—Use of lists.
. The commission shall prior to each advisory vote, in sufficient time to satisfy the requirements of RCW 15.44.033, furnish the director with a list of all producers within the district or area for which the advisory vote is being held. The commission shall require each dealer and shipper in addition to the information required under RCW 15.44.110 to furnish the commission with a list of names of producers whose milk they handle.

. Any producer may on his or her own motion file his or her name with the commission for the purpose of receiving notice of the advisory vote.

. It is the responsibility of each producer to ensure that his or her correct address is filed with the commission.

. For all purposes of giving notice, holding referenda, and conducting advisory votes for nominees to the commission, the applicable list of producers corrected up to the day preceding the date the list is certified and mailed to the director is deemed to be the list of all producers or handlers, as applicable, entitled to notice or to vote. The list shall be corrected and brought up-to-date in accordance with evidence and information provided to the commission.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2367-S.SL.pdf?cite=2012%20c%20107%20§%209[2012 c 107 § 9]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1361.SL.pdf?cite=2003%20c%20396%20§%2027[2003 c 396 § 27]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%2090[2002 c 313 § 90]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c44.pdf?cite=1965%20ex.s.%20c%2044%20§%207[1965 ex.s. c 44 § 7]; ]

== 15.44.038 - Quorum—Compensation—Travel expenses.
. A majority of the commission members shall constitute a quorum for the transaction of all business and the performance of all duties of the commission.

. Each member shall be compensated in accordance with RCW 43.03.230. Each member or employee shall be reimbursed for actual travel expenses incurred in carrying out the provisions of this chapter as defined by the commission in rule. Otherwise, if not defined in rule, reimbursement for travel expenses shall be at the rates allowed by RCW 43.03.050 and 43.03.060.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%2092[2002 c 313 § 92]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c287.pdf?cite=1984%20c%20287%20§%2015[1984 c 287 § 15]; 1975-'76 2nd ex.s. c 34 § 15; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c7.pdf?cite=1975%201st%20ex.s.%20c%207%20§%2012[1975 1st ex.s. c 7 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.44.038[1961 c 11 § 15.44.038]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c163.pdf?cite=1959%20c%20163%20§%208[1959 c 163 § 8]; ]

== 15.44.040 - Copies of records as evidence.
Copies of the proceedings, records and acts of the commission, when certified by the secretary, shall be admissible in any court and be prima facie evidence of the truth of the statements therein contained.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.44.040[1961 c 11 § 15.44.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c163.pdf?cite=1959%20c%20163%20§%209[1959 c 163 § 9]; prior: 1939 c 219 § 4, part; RRS § 6266-4, part; ]

== 15.44.050 - Manager—Secretary-treasurer—Treasurer's bond.
The commission shall elect a manager, who is not a member, and fix his or her compensation; and shall appoint a secretary-treasurer, who shall sign all vouchers and receipts for all moneys received by the commission. The treasurer shall file with the commission a fidelity bond in the sum of one hundred thousand dollars, executed by a surety company authorized to do business in the state, in favor of the state and the commission, conditioned for the faithful performance of his or her duties and strict accounting of all funds to the commission.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%206058[2010 c 8 § 6058]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c238.pdf?cite=1979%20ex.s.%20c%20238%20§%203[1979 ex.s. c 238 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.44.050[1961 c 11 § 15.44.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c219.pdf?cite=1939%20c%20219%20§%205[1939 c 219 § 5]; RRS § 6266-5.   1939 c 219 § 6; RRS § 6266-6; ]

== 15.44.055 - Members—Removal from commission—Process.
If a commission member fails or refuses to perform his or her duties due to excessive absence or abandonment of his or her position or engages in any acts of dishonesty or willful misconduct, the commission may recommend to the director that the commission member be removed from his or her position on the commission. Upon receiving such a recommendation, the director shall review the matter, including any statement from the commission member who is the subject of the recommendation, and determine whether adequate cause for removal is present. If the director finds that adequate cause for removal exists, the director shall remove the member from his or her commission position. The position shall then be declared vacant and will be filled pursuant to the provisions of this chapter for filling vacancies.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6284.SL.pdf?cite=2008%20c%2012%20§%205[2008 c 12 § 5]; ]

== 15.44.060 - Powers and duties.
The commission shall have the power and duty to:

. Elect a chair and such other officers as it deems advisable, and adopt, rescind, and amend rules, regulations, and orders for the exercise of its powers, which shall have the effect of law when not inconsistent with existing laws;

. Administer and enforce the provisions of this chapter and perform all acts and exercise all powers reasonably necessary to effectuate the purpose hereof;

. Employ and discharge advertising counsel, advertising agents, and such attorneys, agents, and employees as it deems necessary, and prescribe their duties and powers and fix their compensation;

. Establish offices, incur expenses, enter into contracts, and create such liabilities as are reasonable and proper for the proper administration of this chapter;

. Investigate and prosecute violations of this chapter;

. Conduct scientific research designed to improve milk production, quality, transportation, processing, and distribution and to develop and discover uses for products of milk and its derivatives;

. Make in its name such contracts and other agreements as are necessary to build demand and promote the sale of dairy products on either a state, national, or foreign basis;

. Keep accurate records of all its dealings, which shall be open to public inspection and audit by the regular agencies of the state;

. Conduct the necessary research to develop more efficient and equitable methods of marketing dairy products, and enter upon, singly or in participation with others, the promotion and development of state, national, or foreign markets;

. Participate in federal and state agency hearings, meetings, and other proceedings relating to the regulation of the production, manufacture, distribution, sale, or use of dairy products, to provide educational meetings and seminars for the dairy industry on such matters, and to expend commission funds for such activities;

. Retain the services of private legal counsel to conduct legal actions, on behalf of the commission. The retention of a private attorney is subject to the review of the office of the attorney general;

. Work cooperatively with other local, state, and federal agencies, universities, and national organizations for the purposes of this chapter;

. Accept and expend or retain any gifts, bequests, contributions, or grants from private persons or private and public agencies to carry out the purposes of this chapter;

. Engage in appropriate fund-raising activities for the purpose of supporting activities of the commission authorized by this chapter;

. Expend funds for commodity-related education, training, and leadership programs as the commission deems appropriate;

. Work cooperatively with nonprofit and other organizations to carry out the purposes of this chapter; and

. Conduct research and education related to economic uses of nutrients produced by dairy farms.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2634.SL.pdf?cite=2016%20c%20101%20§%201[2016 c 101 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%206059[2010 c 8 § 6059]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%2093[2002 c 313 § 93]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1432.SL.pdf?cite=1999%20c%20300%20§%201[1999 c 300 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c238.pdf?cite=1979%20ex.s.%20c%20238%20§%204[1979 ex.s. c 238 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.44.060[1961 c 11 § 15.44.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c163.pdf?cite=1959%20c%20163%20§%2013[1959 c 163 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c219.pdf?cite=1939%20c%20219%20§%208[1939 c 219 § 8]; RRS § 6266-8; ]

== 15.44.061 - Commission's plans, programs, and projects—Director's approval required.
. The commission shall develop and submit to the director for approval any plans, programs, and projects concerning the following:

.. The establishment, issuance, effectuation, and administration of appropriate programs or projects for the advertising, promotion, and education of the affected commodities; and

.. The establishment and effectuation of market research projects, market development projects, or both to the end that the marketing and utilization of the affected commodities may be encouraged, expanded, improved, or made more efficient.

. The director shall review the commission's advertising or promotion program to ensure that no false claims are being made concerning the affected commodities.

. The commission, prior to the beginning of its fiscal year, shall prepare and submit to the director for approval its research plan, its commodity-related education, training and leadership plan, and its budget on a fiscal period basis.

. The director shall strive to review and make a determination of all submissions described in this section in a timely manner.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1361.SL.pdf?cite=2003%20c%20396%20§%2029[2003 c 396 § 29]; ]

== 15.44.062 - Commission speaks for state—Director's oversight.
The commission exists primarily for the benefit of the people of the state of Washington and its economy. The legislature hereby charges the commission, with oversight by the director, to speak on behalf of Washington state government with regard to its particular commodities.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1361.SL.pdf?cite=2003%20c%20396%20§%2030[2003 c 396 § 30]; ]

== 15.44.063 - Reimbursement for costs.
. The commission shall reimburse the director for necessary costs for services conducted on behalf of the commission under this chapter.

. The commission may enter into an agreement with the director to administer this chapter or chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%2091[2002 c 313 § 91]; ]

== 15.44.065 - Commission may establish foundations.
The commission may establish foundations using commission funds as grant money when the foundation benefits the dairy products industry. Commission funds may only be used for the purposes authorized in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%20100[2002 c 313 § 100]; ]

== 15.44.070 - Rules or orders to be filed and published—Rule-making exemptions.
. Every rule or order made by the commission shall be filed with the director and published in two legal newspapers, one east and one west of the Cascade mountains, within ten days after it is adopted, and is effective as set forth under RCW 34.05.380.

. Rule-making proceedings conducted under this chapter are exempt from compliance with RCW 34.05.310, the provisions of chapter 19.85 RCW, the regulatory fairness act, and the provisions of RCW 43.135.055 when adoption of the rule is determined by a referendum vote of the affected parties.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%2094[2002 c 313 § 94]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c7.pdf?cite=1975%201st%20ex.s.%20c%207%20§%2039[1975 1st ex.s. c 7 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.44.070[1961 c 11 § 15.44.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c219.pdf?cite=1939%20c%20219%20§%2018[1939 c 219 § 18]; RRS § 6266-18; ]

== 15.44.080 - Assessments on milk and cream—Amounts—Increases—Producer referendum.
. There is hereby levied upon all milk produced in this state an assessment of:

.. 0.75 percent of class I price for 3.5 percent butter fat milk as established in any market area by a market order in effect in that area or by the state department of agriculture in case there is no market order for that area; or

.. While the federal dairy and tobacco adjustment act of 1983, Title I, Subtitle B-dairy promotion program, is in effect:

... An assessment rate not to exceed the rate approved at the most recent referendum that would achieve a ten cent per hundredweight credit to local, state, or regional promotion organizations provided by Title I, Subtitle B of the federal dairy and tobacco adjustment act of 1983; and

... An additional assessment of 0.625 of one cent per hundredweight.

. Subject to approval by a producer referendum as provided in this section, the commission shall have the further power and duty to increase the amount of the maximum authorized assessment rate to be levied upon either milk or cream according to the necessities required to effectuate the stated purpose of the commission.

In determining such necessities, the commission shall consider one or more of the following:

.. The necessities of:

... Developing better and more efficient methods of marketing milk and related dairy products;

... Aiding dairy producers in preventing economic waste in the marketing of their commodities;

... Developing and engaging in research for developing better and more efficient production, marketing, and utilization of agricultural products;

... Establishing orderly marketing of dairy products;

.. Providing for uniform grading and proper preparation of dairy products for market;

.. Providing methods and means including but not limited to public relations and promotion, for the maintenance of present markets, for development of new or larger markets, both domestic and foreign, for dairy products produced within this state, and for the prevention, modification, or elimination of trade barriers which obstruct the free flow of such agricultural commodities to market;

.. Restoring and maintaining adequate purchasing power for dairy producers of this state; and

.. Protecting the interest of consumers by assuring a sufficient pure and wholesome supply of milk and cream of good quality;

.. The extent and probable cost of required research and market promotion and advertising;

.. The extent of public convenience, interest, and necessity; and

.. The probable revenue from the assessment as a consequence of its being revised.

. [Empty]
.. This section shall apply where milk or cream is marketed either in bulk or package. However, this section shall not apply to milk or cream used upon the farm or in the household where produced.

.. The increase in the maximum authorized assessment rate to be charged producers on milk and cream provided for in this section shall not become effective until approved by fifty-one percent of the producers voting in a referendum conducted by the commission.

The referendum for approval of any increase in the maximum authorized assessment rate provided for in this section shall be by secret mail ballot furnished to all producers paying assessments to the commission. The commission shall furnish ballots to producers at least ten days in advance of the day it has set for concluding the referendum and counting the ballots. Any interested producer may be present at such time the commission counts the ballots.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%2095[2002 c 313 § 95]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c261.pdf?cite=1985%20c%20261%20§%2018[1985 c 261 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c41.pdf?cite=1973%201st%20ex.s.%20c%2041%20§%201[1973 1st ex.s. c 41 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c60.pdf?cite=1969%20c%2060%20§%201[1969 c 60 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c44.pdf?cite=1965%20ex.s.%20c%2044%20§%201[1965 ex.s. c 44 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.44.080[1961 c 11 § 15.44.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c163.pdf?cite=1959%20c%20163%20§%2011[1959 c 163 § 11]; prior: 1949 c 185 § 1, part; 1939 c 219 § 9, part; Rem. Supp. 1949 § 6266-9, part; ]

== 15.44.085 - Assessments on class I or class II milk.
There is hereby levied on every hundredweight of class I or class II milk, as defined in RCW 15.44.087, sold by a dealer, including any milk sold by a producer who acts as a dealer, an assessment of:

. Five-eighths of one cent per hundredweight. Such assessment shall be in addition to the producer assessment paid by any producer who also acts as a dealer.

. Any additional assessment, within the power and duty of the commission to levy, such that the total assessment shall not exceed one cent per hundredweight, as required to effectuate the purpose of this section.

Such assessment may be increased by approval of dealers and producers who also act as dealers, subject to the standards set forth in chapter 15.44 RCW for increasing or decreasing assessments. The funds derived from such assessment shall be used for educational programs and the sum of such funds derived annually from said dealers and producers who act as dealers shall be matched by assessments derived from producers for the purpose of funding the educational purposes by an amount not less than the moneys collected from dealers and producers who act as dealers.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%2096[2002 c 313 § 96]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c238.pdf?cite=1979%20ex.s.%20c%20238%20§%205[1979 ex.s. c 238 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c136.pdf?cite=1975%201st%20ex.s.%20c%20136%20§%205[1975 1st ex.s. c 136 § 5]; ]

== 15.44.087 - Class I and class II milk defined.
For the purpose of RCW 15.44.085, class I and class II milk sold means milk from cows produced by a producer as defined in RCW 15.44.010 and utilized as follows:

. Class I milk shall be all skim milk and butterfat:

.. Sold in the form of fluid milk product subject to the following limitations and exceptions:

... Any products fortified with added nonfat milk solids shall be class I in an amount equal only to the weight of an equal volume of like unmodified product of the same butterfat content.

... Fluid milk products in concentrated form shall be class I in an amount equal to the skim milk and butterfat used to produce the quantity of such products sold.

... Products classified as class II pursuant to subsection (2) of this section are excepted.

.. Packaged fluid milk products in inventory at the end of the month.

. Class II milk shall be all skim milk and butterfat:

.. Used to produce ice cream, ice cream mix, frozen desserts, aerated cream products, plastic cream, soured cream dressing, yogurt, eggnog, cottage cheese, pot cheese, bakers cheese, cream cheese, neufchatel cheese, or starter; or

.. Any milk or milk product, sterilized and either (i) packaged in hermetically sealed metal, plastic, foil, paper, or glass containers and used to produce condensed milk and condensed skim milk, or (ii) in fluid milk products disposed of in bulk to commercial food processing establishments or producer milk sold to a commercial food processing establishment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c238.pdf?cite=1979%20ex.s.%20c%20238%20§%206[1979 ex.s. c 238 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c136.pdf?cite=1975%201st%20ex.s.%20c%20136%20§%206[1975 1st ex.s. c 136 § 6]; ]

== 15.44.090 - Collection of assessments—Lien.
All assessments shall be collected by the first dealer and deducted from the amount due the producer, and all moneys so collected shall be paid to the treasurer of the commission on or before the twentieth day of the succeeding month for the previous month's collections, and deposited by him or her in banks designated by the commission to the credit of the commission fund. If a dealer or a producer who acts as a dealer fails to remit any assessments, or fails to make deductions for assessments, such sum shall, in addition to penalties provided in this chapter, be a lien on any property owned by him or her, and shall be reported to the county auditor by the commission, supported by proper and conclusive evidence, and collected in the manner and with the same priority over other creditors as prescribed for the collection of delinquent taxes.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%206060[2010 c 8 § 6060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c238.pdf?cite=1979%20ex.s.%20c%20238%20§%207[1979 ex.s. c 238 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c136.pdf?cite=1975%201st%20ex.s.%20c%20136%20§%204[1975 1st ex.s. c 136 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.44.090[1961 c 11 § 15.44.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c163.pdf?cite=1959%20c%20163%20§%2012[1959 c 163 § 12]; prior: 1949 c 185 § 1, part; 1939 c 219 § 9, part; Rem. Supp. 1949 § 6266-9, part; ]

== 15.44.100 - Records of dealers, shippers—Preservation—Inspection.
Each dealer or shipper shall keep a complete and accurate record of all milk or cream handled by him or her. The record shall be in such form and contain such information as the commission shall prescribe, and shall be preserved for a period of two years, and be submitted for inspection at any time upon request of the commission or its agent.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%206061[2010 c 8 § 6061]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.44.100[1961 c 11 § 15.44.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c163.pdf?cite=1959%20c%20163%20§%2014[1959 c 163 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c219.pdf?cite=1939%20c%20219%20§%2010[1939 c 219 § 10]; RRS § 6266-10; ]

== 15.44.110 - Reports of dealers and shippers to commission—Subpoenas.
. Each dealer and shipper shall at such times as by rule required file with the commission a return under oath on forms to be furnished by the commission, stating the quantity of dairy products handled, processed, manufactured, delivered, and shipped, and the quantity of all milk and cream delivered to or purchased by such person from the various producers of dairy products or their agents in the state during the period or periods prescribed by the commission.

. The commission has the authority to issue subpoenas for the production of books, records, documents, and other writings of any kind and may issue subpoenas to witnesses to give testimony.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%2097[2002 c 313 § 97]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.44.110[1961 c 11 § 15.44.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c163.pdf?cite=1959%20c%20163%20§%2015[1959 c 163 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c219.pdf?cite=1939%20c%20219%20§%2011[1939 c 219 § 11]; RRS § 6266-11; ]

== 15.44.130 - Research, advertising, educational campaign—Increase or decrease of assessments—Procedure.
. In order to adequately advertise and market Washington dairy products in the domestic, national and foreign markets, and to make such advertising and marketing research and development as extensive as public interest and necessity require, and to put into force and effect the policy of this chapter 15.44 RCW, the commission shall provide for and conduct a comprehensive and extensive research, advertising and educational campaign, and keep such research, advertising and education as continuous as the production, sales, and market conditions reasonably require.

. The commission shall investigate and ascertain the needs of dairy products and producers, the conditions of the markets, and the extent to which public convenience and necessity require advertising and research to be conducted.

. [Empty]
.. The commission may decrease or increase the current level of assessment provided for in RCW 15.44.080 following a hearing conducted in accordance with the Administrative Procedure Act, chapter 34.05 RCW: PROVIDED, That the current level of assessment established in this manner shall not exceed the maximum authorized assessment rate established by producers in the most recent referendum.

.. Upon receipt of a petition bearing the names of twenty percent of the producers requesting a reduction in the current level of assessment, the commission shall hold a hearing in accordance with chapter 34.05 RCW to receive producer testimony. After considering the testimony of the producer, the commission may adjust the current level of assessment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c261.pdf?cite=1985%20c%20261%20§%2019[1985 c 261 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c60.pdf?cite=1969%20c%2060%20§%202[1969 c 60 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.44.130[1961 c 11 § 15.44.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c163.pdf?cite=1959%20c%20163%20§%2017[1959 c 163 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c185.pdf?cite=1949%20c%20185%20§%202[1949 c 185 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c219.pdf?cite=1939%20c%20219%20§%2013[1939 c 219 § 13]; Rem. Supp. 1949 § 6266-13; ]

== 15.44.133 - Promotional hosting expenditures—Rules.
The commission is authorized to adopt rules governing promotional hosting expenditures by commission employees, agents, or board members under RCW 15.04.200.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%2099[2002 c 313 § 99]; ]

== 15.44.140 - Authority to inspect premises and records—Subpoenas.
. The commission through its agents may inspect the premises and records of any carrier, handler, dealer, manufacturer, processor, or distributor of dairy products for the purpose of enforcing this chapter.

. The commission has the authority to issue subpoenas for the production of books, records, documents, and other writings of any kind for any carrier, handler, dealer, manufacturer, processor, or distributor of dairy products for the purpose of enforcing this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%2098[2002 c 313 § 98]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.44.140[1961 c 11 § 15.44.140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c219.pdf?cite=1939%20c%20219%20§%2019[1939 c 219 § 19]; RRS § 6266-19; ]

== 15.44.150 - Action against commission enforced as if a corporation—Liability—Limitations.
Any action by the commission administrator, member, employee, or agent thereof pertaining to the performance or nonperformance or misperformance of any matters or things authorized, required, or permitted by this chapter, and any other liabilities, debts, or claims against the commission shall be enforced in the same manner as if the commission were a corporation. No liability for the debts or actions of the commission shall exist against the state of Washington or any subdivision or instrumentality thereof. Liability for the debts or actions of the commission's administrator, member, employee, or agent incurred in their official capacity under this chapter does not exist either against the administrator, members, employees, and agents in their individual capacity or the state of Washington. The administrator, its members, and its agents and employees are not responsible individually in any way whatsoever to any person for errors in judgment, mistakes, or other acts, either of commission or omission, as principal, agent, person, or employee, except for their own individual acts of dishonesty or crime.

All persons employed or contracting under this chapter shall be limited to, and all salaries, expenses, and liabilities incurred by the commission shall be payable only from the funds collected under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1361.SL.pdf?cite=2003%20c%20396%20§%2032[2003 c 396 § 32]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%20102[2002 c 313 § 102]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.44.150[1961 c 11 § 15.44.150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c219.pdf?cite=1939%20c%20219%20§%207[1939 c 219 § 7]; RRS § 6266-7; ]

== 15.44.160 - Enforcement of chapter.
All state and county law enforcement officers and all employees and agents of the department shall enforce this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.44.160[1961 c 11 § 15.44.160]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c219.pdf?cite=1939%20c%20219%20§%2016[1939 c 219 § 16]; RRS § 6266-16; ]

== 15.44.170 - Penalty.
Whoever violates or aids in the violation of the provisions of this chapter shall be guilty of a gross misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.44.170[1961 c 11 § 15.44.170]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c219.pdf?cite=1939%20c%20219%20§%2014[1939 c 219 § 14]; RRS § 6266-14; ]

== 15.44.180 - Jurisdiction of courts.
The superior courts are hereby vested with jurisdiction to enforce this chapter and to prevent and restrain violations thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.44.180[1961 c 11 § 15.44.180]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c219.pdf?cite=1939%20c%20219%20§%2015[1939 c 219 § 15]; RRS § 6266-15; ]

== 15.44.185 - Certain records exempt from public disclosure—Exceptions—Actions not prohibited by chapter.
. Under RCW 42.56.380, certain agricultural business records, commission records, and department of agriculture records relating to the commission and producers of agricultural commodities are exempt from public disclosure.

. Financial and commercial information and records submitted to either the department or the commission for the purpose of administering this chapter may be shared between the department and the commission. They may also be used, if required, in any suit or administrative hearing involving any provision of this chapter or a marketing order.

. This chapter does not prohibit:

.. The issuance of general statements based upon the reports of persons subject to this chapter as long as the statements do not identify the information furnished by any person; or

.. The publication by the director or the commission of the name of any person violating this chapter and a statement of the manner of the violation by that person.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20214[2005 c 274 § 214]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%2069[2002 c 313 § 69]; ]

== 15.44.190 - Funding staff support—Rules.
The director may provide by rule for a method to fund staff support for all commodity boards and commissions in accordance with RCW 43.23.033 if a position is not directly funded by the legislature and costs related to the specific activity undertaken on behalf of an individual commodity board or commission. The commission shall provide funds to the department according to the rules adopted by the director.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2688-S.SL.pdf?cite=2002%20c%20313%20§%2075[2002 c 313 § 75]; ]

== 15.44.195 - Costs of implementing RCW  15.44.061.
The costs incurred by the department of agriculture associated with the implementation of RCW 15.44.061 shall be paid for by the commission.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1361.SL.pdf?cite=2003%20c%20396%20§%2031[2003 c 396 § 31]; ]

== 15.44.910 - Liberal construction.
This chapter shall be liberally construed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c11.pdf?cite=1961%20c%2011%20§%2015.44.910[1961 c 11 § 15.44.910]; 1939 c 219 § 17, part; RRS § 6266-17, part; ]

