= 15.125 - Marijuana and marijuana products.
:toc:

== 15.125.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Board" means the state liquor and cannabis board.

. "Licensee facilities" means any premises regulated by the board for producing, processing, or retailing marijuana or marijuana products.

. "Marijuana" has the meaning provided in RCW 69.50.101.

. "Marijuana processor" has the meaning provided in RCW 69.50.101.

. "Marijuana producer" has the meaning provided in RCW 69.50.101.

. "Marijuana products" has the meaning provided in RCW 69.50.101.

. "Marijuana retailer" has the meaning provided in RCW 69.50.101.

. "Person" means any natural person, firm, partnership, association, private or public corporation, governmental entity, or other business entity.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5131-S.SL.pdf?cite=2017%20c%20317%20§%2018[2017 c 317 § 18]; ]

== 15.125.020 - Rule-making authority.
. The department may adopt rules establishing:

.. Standards for marijuana and marijuana products produced and processed in a manner consistent with, to the extent practicable, 7 C.F.R. Part 205;

.. A self-sustaining program for certifying marijuana producers and marijuana processors as meeting the standards established under (a) of this subsection; and

.. Other rules as necessary for administration of this chapter.

. To the extent practicable, the program must be consistent with the program established by the director under chapter 15.86 RCW.

. The rules must include a fee schedule that will provide for the recovery of the full cost of the program including, but not limited to, application processing, inspections, sampling and testing, notifications, public awareness programs, and enforcement.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5131-S.SL.pdf?cite=2017%20c%20317%20§%2019[2017 c 317 § 19]; ]

== 15.125.030 - Marijuana and marijuana products—Production and processing.
. No marijuana or marijuana product may be labeled, sold, or represented as produced or processed under the standards established under this chapter unless produced or processed by a person certified by the department under the program established under this chapter.

. No person may represent, sell, or offer for sale any marijuana or marijuana products as produced or processed under standards adopted under this chapter if the person knows, or has reason to know, that the marijuana or marijuana product has not been produced or processed in conformance with the standards established under this chapter.

. No person may represent, sell, or offer for sale any marijuana or marijuana products as "organic products" as that term has meaning under chapter 15.86 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5131-S.SL.pdf?cite=2017%20c%20317%20§%2020[2017 c 317 § 20]; ]

== 15.125.040 - Licensee facilities—Department may inspect—Certification—Fines—Enforcement actions.
. The department may inspect licensee facilities to verify compliance with this chapter and rules adopted under it.

. The department may deny, suspend, or revoke a certification provided for in this chapter if the department determines that an applicant or certified person has violated this chapter or rules adopted under it.

. The department may impose on and collect from any person who has violated this chapter or rules adopted under it a civil fine not exceeding the total of:

.. The state's estimated costs of investigating and taking appropriate administrative and enforcement actions for the violation; and

.. One thousand dollars.

. The board may take enforcement actions against a marijuana producer, marijuana processor, or marijuana retailer license issued by the board, including suspension or revocation of the license, when a licensee continues to violate this chapter after revocation of its certification or, if uncertified, receiving written notice from the department of certification requirements.

. The provisions of this chapter are cumulative and nonexclusive and do not affect any other remedy at law.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5131-S.SL.pdf?cite=2017%20c%20317%20§%2021[2017 c 317 § 21]; ]

== 15.125.050 - Marijuana producer, processor, and retailer information—Exemption from public inspection and copying.
Information about marijuana producers, marijuana processors, and marijuana retailers otherwise exempt from public inspection and copying under chapter 42.56 RCW is also exempt from public inspection and copying if submitted to or used by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5131-S.SL.pdf?cite=2017%20c%20317%20§%2022[2017 c 317 § 22]; ]

== 15.125.060 - Deposit of fees into account within agricultural local fund—Revenue from fees—Appropriation not required for disbursement.
All fees collected under this chapter must be deposited in an account within the agricultural local fund. The revenue from the fees must be used solely for carrying out the provisions of this chapter, and no appropriation is required for disbursement from the fund.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5131-S.SL.pdf?cite=2017%20c%20317%20§%2023[2017 c 317 § 23]; ]

