= 15.105 - From the heart of Washington program.
:toc:

== 15.105.005 - Findings.
The legislature finds that the support of Washington's agriculture industry and its family farms by the citizens of the state of Washington is beneficial to the economy of the state. The legislature also finds that Washington farmers produce a variety of wholesome, quality products and are good stewards of the land.

The legislature also finds that the from the heart of Washington program, developed by the Washington state department of agriculture with one-time federal grant moneys, is a valuable tool to convey important messages about Washington agriculture and to encourage Washington citizens to buy Washington-grown and Washington-processed food and agricultural products. With the exhaustion of the one-time federal grant funding, the legislature finds that the program would benefit from a new governance structure that will allow the necessary operational flexibility to enable the program to expand and to encourage private investment in the program, and that the continuance of the program as a private, nonprofit corporation is the best method to achieve these goals.

The legislature further finds that the continuation of the from the heart of Washington program will provide both direct and indirect economic benefits to the people of the state of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2366-S.SL.pdf?cite=2004%20c%2026%20§%201[2004 c 26 § 1]; ]

== 15.105.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "From the heart of Washington" or "program" means that program created by the department to encourage Washington citizens to purchase Washington food and agricultural products and to promote the value of agriculture and family farms to Washington state.

. "Successor organization" means a private, nonprofit corporation created specifically to assume responsibility for carrying out the from the heart of Washington program that is now part of the department. The private, nonprofit corporation must qualify as a tax-exempt, nonprofit corporation under section 501(c) of the federal internal revenue code; the majority of members on its board of directors must be from Washington commodity commissions, nonprofit associations organized for the promotion of Washington agricultural products, and other agricultural industry groups; and the corporation must carry forward with the work of the current program.

. "Department" means the Washington state department of agriculture.

. "Director" means the director of the Washington state department of agriculture.

. "Fiscal agent" means the Washington state fruit commission, as a contractor of the department.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2366-S.SL.pdf?cite=2004%20c%2026%20§%202[2004 c 26 § 2]; ]

== 15.105.020 - Establishing a private, nonprofit corporation—Duties of successor organization—Debts and other liabilities.
. The department may cooperate with other agencies, boards, commissions, and associations in the state of Washington to establish a private, nonprofit corporation for the purpose of carrying out the program. The nonprofit corporation must be organized under chapter 24.03 RCW and has the powers granted under that chapter. However, this chapter does not prohibit the department or other agencies, boards, commissions, and associations from separately continuing to promote Washington products under their existing authorities.

. The department may contract with the successor organization to carry out the program. The contract must require the successor organization to aggressively seek to fund its continued operation from nonstate funding sources.

. The successor organization must report to the department each January 1st on the amounts it has secured from both nonstate and state funding sources, its operations, and its programs.

. Debts and other liabilities of the successor organization are successor organization debts and liabilities only and may be satisfied only from the resources of the successor organization. The state of Washington is not liable for the debts or liabilities of the successor organization.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2366-S.SL.pdf?cite=2004%20c%2026%20§%203[2004 c 26 § 3]; ]

== 15.105.030 - Actions by department to establish a successor organization.
In order to accomplish the establishment of a successor organization, the department and its fiscal agent may take all necessary and proper steps, including:

. Transferring any equipment, software, database, other assets except the logo of the program, or contracts for services to the successor organization under appropriate terms and conditions, including reasonable compensation deemed appropriate by the department. The department shall retain the right to repossess any property transferred to the successor organization in the event that the successor organization dissolves, becomes bankrupt, insolvent, or is otherwise unable to carry out the program, or if the successor organization fails to comply with any contract with the department. In the event that the department exercises its right to repossess under this section, any property returned to the department becomes the property of the state and is administered by the department;

. Unless otherwise provided by agreement, assigning any contracts and other duties and responsibilities to the successor organization related to the program; and

. Providing necessary support services to the successor organization under contract for up to a two-year period after the effective date of a contract between a successor organization and the department for the delivery of program services. The successor organization shall provide full reimbursement for all costs of services contracted for under this subsection.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2366-S.SL.pdf?cite=2004%20c%2026%20§%204[2004 c 26 § 4]; ]

== 15.105.040 - Board of directors of the successor organization—State membership.
. The department shall designate one or more persons to serve in the capacity of a member of the board of directors of the successor organization. The state is not liable under any circumstances for the acts of the successor organization, any member of its board of directors, or its employees.

. The department may pay an annual membership fee to the successor organization not to exceed the value of services received.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2366-S.SL.pdf?cite=2004%20c%2026%20§%205[2004 c 26 § 5]; ]

== 15.105.050 - Program logo.
The logo of the program is the property of the department. The department may license the use of the logo to the successor organization and others, as it deems appropriate. The department retains the right to cancel any license to use the logo.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2366-S.SL.pdf?cite=2004%20c%2026%20§%206[2004 c 26 § 6]; ]

== 15.105.060 - Gifts, grants, or endowments.
The department may receive gifts, grants, or endowments from private or public sources that are made from time to time, in trust or otherwise, for the use and benefit of the purposes of the program. The department may spend or contract with the successor organization to spend the gifts, grants, or endowments or income from the private or public sources according to their terms.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2366-S.SL.pdf?cite=2004%20c%2026%20§%207[2004 c 26 § 7]; ]

== 15.105.901 - Effective date—2004 c 26.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and takes effect immediately [March 19, 2004].

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2366-S.SL.pdf?cite=2004%20c%2026%20§%2010[2004 c 26 § 10]; ]

