= 15.140 - Hemp production.
:toc:

== 15.140.010 - Intent.
The legislature intends to:

. Authorize and establish a new licensing and regulatory program for hemp production in this state in accordance with the agriculture improvement act of 2018;

. Replace the industrial hemp research program in *chapter 15.120 RCW, with the new licensing and regulatory program established in this chapter, and enable hemp growers licensed under the industrial hemp research program on the effective date of rules implementing this chapter and regulating hemp production, to transfer into the program created in this chapter; and

. Authorize the growing of hemp as a legal, agricultural activity in this state. Hemp is an agricultural product that may be legally grown, produced, processed, possessed, transferred, commercially sold, and traded. Hemp and processed hemp produced in accordance with this chapter or produced lawfully under the laws of another state, tribe, or country may be transferred and sold within the state, outside of this state, and internationally. Nothing in this chapter is intended to prevent or restrain commerce in this state involving hemp or hemp products produced lawfully under the laws of another state, tribe, or country.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5276-S2.SL.pdf?cite=2019%20c%20158%20§%201[2019 c 158 § 1]; ]

== 15.140.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Agriculture improvement act of 2018" means sections 7605, 10113, 10114, and 12619 of the agriculture improvement act of 2018, P.L. 115-334.

. "Crop" means hemp grown as an agricultural commodity.

. "Cultivar" means a variation of the plant Cannabis sativa L. that has been developed through cultivation by selective breeding.

. "Department" means the Washington state department of agriculture.

. "Hemp" means the plant Cannabis sativa L. and any part of that plant, including the seeds thereof and all derivatives, extracts, cannabinoids, isomers, acids, salts, and salts of isomers, whether growing or not, with a delta-9 tetrahydrocannabinol concentration of not more than 0.3 percent on a dry weight basis.

. [Empty]
.. "Industrial hemp" means all parts and varieties of the genera Cannabis, cultivated or possessed by a grower, whether growing or not, that contain a tetrahydrocannabinol concentration of 0.3 percent or less by dry weight that was grown under the industrial hemp research program as it existed on December 31, 2019.

.. "Industrial hemp" does not include plants of the genera Cannabis that meet the definition of "marijuana" as defined in RCW 69.50.101.

. "Postharvest test" means a test of delta-9 tetrahydrocannabinol concentration levels of hemp after being harvested based on:

.. Ground whole plant samples without heat applied; or

.. Other approved testing methods.

. "Process" means the processing, compounding, or conversion of hemp into hemp commodities or products.

. "Produce" or "production" means the planting, cultivation, growing, or harvesting of hemp including hemp seed.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5276-S2.SL.pdf?cite=2019%20c%20158%20§%202[2019 c 158 § 2]; ]

== 15.140.030 - Agricultural commodity program—Rule-making authority.
. The department must develop an agricultural commodity program to replace the industrial hemp research pilot program in *chapter 15.120 RCW, in accordance with the agriculture improvement act of 2018.

. The department has sole regulatory authority over the production of hemp and may adopt rules to implement this chapter. All rules relating to hemp, including any testing of hemp, are outside of the control and authority of the liquor and cannabis board.

. If the department adopts rules implementing this chapter that are effective by June 1, 2019, persons licensed to grow hemp under *chapter 15.120 RCW may transfer into the regulatory program established in this chapter, and continue hemp production under this chapter. If the department adopts rules implementing this chapter that are effective after June 1, 2019, people licensed to grow hemp under *chapter 15.120 RCW may continue hemp production under this chapter as of the effective date of the rules.

. Immediately upon April 26, 2019, and before the adoption of rules implementing this chapter, persons licensed to grow hemp under *chapter 15.120 RCW may produce hemp in a manner otherwise consistent with the provisions of this chapter and the agriculture improvement act of 2018.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5276-S2.SL.pdf?cite=2019%20c%20158%20§%203[2019 c 158 § 3]; ]

== 15.140.040 - State's hemp plan.
. The department must develop the state's hemp plan to conform to the agriculture improvement act of 2018, to include consultation with the governor and the attorney general and the plan elements required in the agriculture improvement act of 2018.

. Consistent with subsection (1) of this section, the state's hemp plan must include the following elements:

.. A practice for hemp producers to maintain relevant information regarding land on which hemp is produced, including a legal description of the land, for a period of not less than three calendar years;

.. A procedure for testing, using postdecarboxylation or other similarly reliable methods, delta-9 tetrahydrocannabinol concentration levels of hemp, without the application of heat;

.. A procedure for the effective disposal of plants, whether growing or not, that are produced in violation of this chapter, and products derived from such plants;

.. A procedure for enforcement of violations of the plan and for corrective action plans for licensees as required under the agriculture improvement act of 2018;

.. A procedure for conducting annual inspections of, at a minimum, a random sample of hemp producers to verify hemp is not produced in violation of this chapter; and

.. A certification that the state has the resources and personnel to carry out the practices and procedures described in this section.

. The proposal for the state's plan may include any other practice or procedure established to the extent the practice or procedure is consistent with the agriculture improvement act of 2018.

. Hemp and processed hemp produced in accordance with this chapter or produced lawfully under the laws of another state, tribe, or country may be transferred and sold within this state, outside of this state, and internationally.

. The whole hemp plant may be used as food. The department shall regulate the processing of hemp for food products, that are allowable under federal law, in the same manner as other food processing under chapters 15.130 and 69.07 RCW and may adopt rules as necessary to properly regulate the processing of hemp for food products including, but not limited to, establishing standards for creating hemp extracts used for food.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5276-S2.SL.pdf?cite=2019%20c%20158%20§%204[2019 c 158 § 4]; ]

== 15.140.050 - Postharvest test protocol.
The department must develop a postharvest test protocol for testing hemp under this chapter that includes testing of whole plant samples or other testing protocol identified in regulations established by the United States department of agriculture, including the testing procedures for delta-9 tetrahydrocannabinol concentration levels of hemp produced by producers under the state plan.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5276-S2.SL.pdf?cite=2019%20c%20158%20§%205[2019 c 158 § 5]; ]

== 15.140.060 - Hemp producer license—Rules—Fees.
. The department must issue hemp producer licenses to applicants qualified under this chapter and the agriculture improvement act of 2018. The department may adopt rules pursuant to this chapter and chapter 34.05 RCW as necessary to license persons to grow hemp under a commercial hemp program.

. The plan must identify qualifications for license applicants, to include adults and corporate persons and to exclude persons with felony convictions as required under the agriculture improvement act of 2018.

. The department must establish license fees in an amount that will fund the implementation of this chapter and sustain the hemp program. The department may adopt rules establishing fees for tetrahydrocannabinol testing, inspections, and additional services required by the United States department of agriculture. License fees and any money received by the department under this chapter must be deposited in the hemp regulatory account created in RCW 15.140.080.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5276-S2.SL.pdf?cite=2019%20c%20158%20§%206[2019 c 158 § 6]; ]

== 15.140.070 - Source of hemp seeds or clones.
A person producing hemp pursuant to this chapter must notify the department of the source of the hemp seed or clones solely for the purpose of maintaining a record of the sources of seeds and clones being used or having been used for hemp production in this state. Hemp seed is an agricultural seed.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5276-S2.SL.pdf?cite=2019%20c%20158%20§%207[2019 c 158 § 7]; ]

== 15.140.080 - Hemp regulatory account.
The hemp regulatory account is created in the custody of the state treasurer. All receipts from fees established under this chapter must be deposited into the account. Expenditures from the account may be used only for implementing this chapter. Only the director of the state department of agriculture or the director's designee may authorize expenditures from the account. The account is subject to allotment procedures under chapter 43.88 RCW, but an appropriation is not required for expenditures.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5276-S2.SL.pdf?cite=2019%20c%20158%20§%208[2019 c 158 § 8]; ]

== 15.140.090 - Internet-based application.
Washington State University may, within existing resources, develop and make accessible an internet-based application designed to assist hemp producers by providing regional communications concerning recommended planting times for hemp crops in this state.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5276-S2.SL.pdf?cite=2019%20c%20158%20§%209[2019 c 158 § 9]; ]

== 15.140.100 - Cross-pollination—Hemp plants and marijuana plants.
. There is no distance requirement, limitation, or buffer zone between any licensed hemp producer or hemp processing facility licensed or authorized under this chapter and any marijuana producer or marijuana processor licensed under chapter 69.50 RCW. No rule may establish such a distance requirement, limitation, or buffer zone without the evaluation of sufficient data showing impacts to either crop as a result of cross-pollination.

. Notwithstanding subsection (1) of this section, in an effort to prevent cross-pollination between hemp plants produced under this chapter and marijuana plants produced under chapter 69.50 RCW, the department, in consultation with the liquor and cannabis board, must review the state's policy regarding cross-pollination and pollen capture to ensure an appropriate policy is in place, and must modify policies or establish new policies as appropriate. Under any such policy, when a documented conflict involving cross-pollination exists between two farms or production facilities growing or producing hemp or marijuana, the farm or production facility operating first in time shall have the right to continue operating and the farm or production facility operating second in time must cease growing or producing hemp or marijuana, as applicable.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5276-S2.SL.pdf?cite=2019%20c%20158%20§%2010[2019 c 158 § 10]; ]

== 15.140.110 - Expedited rule making to adopt the state hemp plan.
. The department must use expedited rule making to adopt the state hemp plan submitted to the United States department of agriculture. As allowed under this section, rule making by the department to adopt the approved hemp plan qualifies as expedited rule making under RCW 34.05.353. Upon the submittal of the plan to the United States department of agriculture, the department may conduct initial expedited rule making under RCW 34.05.353 to establish rules to allow hemp licenses to be issued without delay.

. On the effective date of rules adopted by the department regulating hemp production under chapter 15.140 RCW, a licensed hemp producer under this chapter may immediately produce hemp pursuant to chapter 15.140 RCW with all the privileges of a hemp producer licensed under chapter 15.140 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5276-S2.SL.pdf?cite=2019%20c%20158%20§%2011[2019 c 158 § 11]; ]

== 15.140.120 - Limitation of enforcement of certain laws and rules.
Beginning on April 26, 2019:

. No law or rule related to certified or interstate hemp seeds applies to or may be enforced against a person with a license to produce or process hemp issued under this chapter or *chapter 15.120 RCW; and

. No department or other state agency rule may establish or enforce a buffer zone or distance requirement between a person with a license or authorization to produce or process hemp under this chapter or *chapter 15.120 RCW and a person with a license to produce or process marijuana issued under chapter 69.50 RCW. The department may not adopt rules without the evaluation of sufficient data showing impacts to either crop as a result of cross-pollination.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5276-S2.SL.pdf?cite=2019%20c%20158%20§%2016[2019 c 158 § 16]; ]

== 15.140.900 - Effective date—2019 c 158.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and takes effect immediately [April 26, 2019].

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5276-S2.SL.pdf?cite=2019%20c%20158%20§%2019[2019 c 158 § 19]; ]

