= 30A.38 - Interstate banking.
:toc:

== 30A.38.005 - Definitions.
As used in this chapter, unless a different meaning is required by the context, the following words and phrases have the following meanings:

. "Bank" means any national bank, state bank, and district bank, as those terms are defined in 12 U.S.C. Sec. 1813(a), and any savings association, as defined in 12 U.S.C. Sec. 1813(b).

. "Bank holding company" has the meaning set forth in 12 U.S.C. Sec. 1841(a)(1), and also means a savings and loan holding company, as defined in 12 U.S.C. Sec. 1467a.

. "Bank supervisory agency" means:

.. Any agency of another state with primary responsibility for chartering and supervising banks; and

.. The office of the comptroller of the currency, the federal deposit insurance corporation, the board of governors of the federal reserve system, and any successor to these agencies.

. "Control" shall be construed consistently with the provisions of 12 U.S.C. Sec. 1841(a)(2).

. "Home state" means with respect to a:

.. State bank, the state by which the bank is chartered; or

.. Federally chartered bank, the state in which the main office of the bank is located under federal law.

. "Home state regulator" means, with respect to an out-of-state state bank, the bank supervisory agency of the state in which the bank is chartered.

. "Host state" means a state, other than the home state of a bank, in which the bank maintains, or seeks to establish and maintain a branch.

. "Interstate combination" means the:

.. Merger or consolidation of banks with different home states, and the conversion of branches of any bank involved in the merger or consolidation into branches of the resulting bank; or

.. Purchase of all or substantially all of the assets, including all or substantially all of the branches, of a bank whose home state is different from the home state of the acquiring bank.

. "Out-of-state bank" means a bank whose home state is a state other than Washington.

. "Out-of-state state bank" means a bank chartered under the laws of any state other than Washington.

. "Resulting bank" means a bank that has resulted from an interstate combination under this chapter.

. "State" means any state of the United States, the District of Columbia, any territory of the United States, Puerto Rico, Guam, American Samoa, the Trust Territory of the Pacific Islands, the Virgin Islands, and the Northern Mariana Islands.

. "Washington bank" means a bank whose home state is Washington.

. "Washington state bank" means a bank organized under Washington banking law.

. "Branch" means an office of a bank through which it receives deposits, other than its principal office. Any of the functions or services authorized to be engaged in by a bank may be carried out in an authorized branch office.

. "De novo branch" means a branch of a bank located in a host state which:

.. Is originally established by the bank as a branch; and

.. Does not become a branch of the bank as a result of:

... The acquisition of another bank or a branch of another bank; or

... A merger, consolidation, or conversion involving any such bank or branch.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=2005%20c%20348%20§%201[2005 c 348 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2125-S.SL.pdf?cite=1996%20c%202%20§%2010[1996 c 2 § 10]; ]

== 30A.38.010 - Out-of-state bank may engage in banking in this state—Conditions—Director's approval of interstate combination.
. An out-of-state bank may engage in banking in this state without violating RCW 30A.04.280 only if the conditions and filing requirements of this chapter are met and the bank was lawfully engaged in banking in this state on July 22, 2010, or the bank's in-state banking activities:

.. Resulted from an interstate combination pursuant to RCW 30A.49.125 or 32.32.500;

.. Resulted from a relocation of a head office of a state bank pursuant to 12 U.S.C. Sec. 30 and RCW 30A.04.215(3);

.. Resulted from a relocation of a main office of a national bank pursuant to 12 U.S.C. Sec. 30;

.. Resulted from the establishment of a branch of a savings bank in compliance with RCW 32.04.030(6); or

.. Resulted from interstate branching under RCW 30A.38.015.

Nothing in this section affects the authorities of alien banks as defined by RCW 30A.42.020 to engage in banking within this state.

. The director, consistent with 12 U.S.C. Sec. 1831u(b)(2)(D), may approve an interstate combination if the standard on which the approval is based does not discriminate against out-of-state banks, out-of-state bank holding companies, or subsidiaries of those banks or holding companies.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20208[2014 c 37 § 208]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1325-S.SL.pdf?cite=2013%20c%2076%20§%2012[2013 c 76 § 12]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=2005%20c%20348%20§%202[2005 c 348 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2125-S.SL.pdf?cite=1996%20c%202%20§%2011[1996 c 2 § 11]; ]

== 30A.38.015 - Out-of-state bank without a branch in this state—Options—Director's approval required, conditions.
. An out-of-state bank that does not have a branch in Washington may, under this chapter, establish and maintain:

.. A de novo branch in this state; or

.. A branch in this state through the acquisition of a branch.

. An out-of-state bank desiring to establish and maintain a de novo branch or to acquire a branch in this state shall provide written application of the proposed transaction to the director, accompanied by the fee prescribed by the director, not later than three days after the date of filing with the responsible federal bank supervisory agency for approval to establish or acquire the branch.

. Subject to the conditions of this chapter, the director shall approve an application under subsection (2) of this section if the out-of-state bank would be permitted to establish or acquire a branch in Washington state if it were a bank chartered in Washington state.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1325-S.SL.pdf?cite=2013%20c%2076%20§%2013[2013 c 76 § 13]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=2005%20c%20348%20§%203[2005 c 348 § 3]; ]

== 30A.38.020 - Out-of-state bank with host branches—Relocation of head office—Reincorporation—Application—Director's approval required.
An out-of-state bank with host branches in this state may relocate its head office in Washington and reincorporate as a Washington state bank if the director finds that the bank meets the standards as to capital structures, operations, business experience, and character of officers and directors, and the bank follows the procedures specified in this section.

The bank shall file with the director on a form prescribed by the director, an application to relocate its head office to Washington. Within six months upon acceptance of a complete application, the director shall notify the bank to file, in triplicate, an executed and acknowledged certificate of reincorporation signed by a majority of the entire board of directors that at least two-thirds of each class of voting stock of the bank entitled to vote thereon has approved the: (1) Head office relocation; (2) change to a Washington state bank; and (3) new articles of incorporation.

Within thirty days after receipt of the certificate and articles, the director shall endorse upon each of the triplicate copies, over the director's official signature, the word "approved" or the word "refused," with the date of the endorsement. In case of refusal the director shall immediately return one of the triplicates, so endorsed, together with a statement explaining the reason for refusal to the bank from whom the certificate and articles were received. The refusal shall be conclusive, unless the bank, within ten days of the issuance of the notice of refusal, requests a hearing under chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2125-S.SL.pdf?cite=1996%20c%202%20§%2012[1996 c 2 § 12]; ]

== 30A.38.030 - Out-of-state bank may maintain and operate branches—Powers and authorities.
. If authorized to engage in banking in this state under RCW 30A.38.010, an out-of-state bank may maintain and operate the branches in Washington of a Washington bank with which the out-of-state bank or its predecessors engaged in an interstate combination.

. The out-of-state bank may establish or acquire and operate additional branches in Washington to the same extent that any Washington bank may establish or acquire and operate a branch in Washington under applicable federal and state law.

. The out-of-state state bank may, at such branches, unless otherwise limited by the bank's home state law, exercise any powers and authorities that are authorized under the laws of this state for Washington state banks.

. The out-of-state state bank may, at these branches, exercise additional powers and authorities that are authorized under the laws of its home state, only if the director determines in writing that the exercise of the additional powers and authorities in this state will not threaten the safety and soundness of banks in this state and serves the convenience and needs of Washington consumers. Washington state banks also may exercise the powers and authorities under RCW * 30A.08.140(16) or ** 32.08.140(15).

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20209[2014 c 37 § 209]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2125-S.SL.pdf?cite=1996%20c%202%20§%2013[1996 c 2 § 13]; ]

== 30A.38.040 - Examinations of any branch of an out-of-state state bank—Reporting requirements for any branch of an out-of-state bank—Supervisory agreements—Joint examinations or enforcement actions—Assessments.
. The director may make examinations of any branch in this state of an out-of-state state bank as the director deems necessary to determine whether the branch is being operated in compliance with the laws of this state or is conducting its activities in accordance with safe and sound banking practices. The provisions applicable to examinations and sharing of information of Washington state banks shall apply to these examinations.

. The director may prescribe requirements for reports regarding any branches of an out-of-state bank that operates a branch in Washington pursuant to this chapter. The required reports shall be provided by the bank or by the bank supervisory agency having primary responsibility for the bank. Any reporting requirements prescribed by the director under this subsection shall be consistent with the reporting requirements applicable to Washington state banks and appropriate for the purpose of enabling the director to carry out his or her responsibilities under this chapter.

. The director may enter into supervisory agreements with any bank supervisory agency that has concurrent jurisdiction over a Washington state bank or an out-of-state state bank operating a branch in this state pursuant to this chapter to engage the services of that agency's examiners at a reasonable rate of compensation, or to provide the services of the director's examiners to that agency at a reasonable rate of compensation. These contracts are exempt from the requirements of *chapter 39.29 RCW. The director also may enter into supervisory agreements with other appropriate bank supervisory agencies and the bank to prescribe the applicable laws governing powers and authorities, including but not limited to corporate governance and operational matters, of Washington branches of an out-of-state bank chartered by another state or out-of-state branches of a Washington state bank. The supervisory agreement may resolve conflict of laws among home and host states and specify the manner in which the examination, supervision, and application processes shall be coordinated among the home and host states.

. The director may enter into joint examinations or joint enforcement actions with other bank supervisory agencies having concurrent jurisdiction over any branch in Washington of an out-of-state state bank or any branch of a Washington state bank in any host state. The director also may at any time take action independently if the director deems it necessary or appropriate to carry out his or her responsibilities under this chapter or to ensure compliance with the laws of this state. However, in the case of an out-of-state state bank, the director shall recognize the exclusive authority of the home state regulator over corporate governance and operational matters and the primary responsibility of the home state regulator with respect to safety and soundness matters, unless otherwise specified in the supervisory agreement executed pursuant to this section.

. Each out-of-state state bank that maintains one or more branches in this state may be assessed and, if assessed, shall pay supervisory and examination fees in accordance with the laws of this state and rules of the director. The director is authorized to enter into agreements to share fees with other bank supervisory agencies or any organization affiliated with or representing one or more bank supervisory agencies.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2125-S.SL.pdf?cite=1996%20c%202%20§%2014[1996 c 2 § 14]; ]

== 30A.38.050 - Branch of out-of-state state bank—Violations—Unsafe and unsound operations—Enforcement actions—Notice to home state regulator.
If the director determines that a branch maintained by an out-of-state state bank in this state is being operated in violation of the laws of this state, or that the branch is being operated in an unsafe and unsound manner, the director has the authority to take all enforcement actions he or she would be empowered to take if the branch were a Washington state bank. However, the director shall promptly give notice to the home state regulator of each enforcement action taken against an out-of-state state bank and, to the extent practicable, shall consult and cooperate with the home state regulator in pursuing and resolving the enforcement action.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2125-S.SL.pdf?cite=1996%20c%202%20§%2015[1996 c 2 § 15]; ]

== 30A.38.060 - Rules.
The director may adopt those rules necessary to implement chapter 2, Laws of 1996.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2125-S.SL.pdf?cite=1996%20c%202%20§%2016[1996 c 2 § 16]; ]

== 30A.38.070 - Out-of-state state bank becomes resulting bank—Branches in this state—RCW  30A.49.125(5) does not apply—When established and maintained—Notice to director.
. Any out-of-state state bank that will be the resulting bank pursuant to an interstate combination involving any bank with branches in Washington, if RCW 30A.49.125(5) does not apply, shall notify the director of the proposed combination not later than three days after the date of filing of an application for the combination with the responsible federal bank supervisory agency, and shall submit a copy of the application to the director and pay applicable application fees, if any, required by the director. In lieu of notice from the out-of-state state bank the director may accept notice from the bank's home state regulator. The director has the authority to waive any procedures required by Washington merger laws if the director finds that the provision is in conflict with the applicable federal law or in conflict with the applicable law of the state of the resulting bank.

. An out-of-state state bank that has established and maintains a branch in this state pursuant to this chapter shall give at least thirty days' prior written notice or, in the case of an emergency transaction, shorter notice as is consistent with the applicable state or federal law, to the director of any transaction that would cause a change of control with respect to the bank or any bank holding company that controls the bank, with the result that an application would be required to be filed pursuant to the federal change in bank control act of 1978, as amended, 12 U.S.C. Sec. 1817(j), or the federal bank holding company act of 1956, as amended, 12 U.S.C. Sec. 1841 et seq., or any successor statutes. In lieu of notice from the out-of-state state bank the director may accept notice from the bank's home state regulator.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20210[2014 c 37 § 210]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2125-S.SL.pdf?cite=1996%20c%202%20§%2017[1996 c 2 § 17]; ]

== 30A.38.080 - Application of Washington laws—Declaration of invalidity.
. The laws of Washington applicable to Washington state banks regarding community reinvestment, consumer protection, fair lending, and the establishment of intrastate branches apply to any branch in Washington of an out-of-state national bank or out-of-state state bank to the same extent as Washington laws apply to a Washington state bank. In lieu of taking action directly against an out-of-state state bank to enforce compliance with these Washington laws on host state branches, the director may refer action to the home state regulator, but the director retains enforcement powers to ensure that compliance is satisfactory to the director.

. Any host state branch of a Washington state bank shall comply with all applicable host state laws concerning community reinvestment, consumer protection, fair lending, and the establishment of intrastate branches.

. In the event that the responsible federal chartering authority, pursuant to applicable federal law, or in the event a court of competent jurisdiction declares that any Washington state law is invalid with respect to an out-of-state or national bank, that Washington state law is also invalid with respect to Washington state banks and to host branches of out-of-state state banks to that same extent. The director may, from time to time, publish by rule Washington state laws that have been found invalidated pursuant to federal law and procedures. This subsection does not impair, in any manner, the authority of the state attorney general to enforce antitrust laws applicable to banks, bank holding companies, or affiliates of those banks or bank holding companies.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2125-S.SL.pdf?cite=1996%20c%202%20§%2018[1996 c 2 § 18]; ]

