= 30A.04 - General provisions.
:toc:

== 30A.04.002 - Short title.
This title may be known and cited as the Washington commercial bank act.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20101[2014 c 37 § 101]; ]

== 30A.04.005 - Legislative declarations.
The legislature declares that:

. Banking institutions and trust companies provide essential and valuable fiduciary management services to consumers, businesses, and nonprofit organizations in the state of Washington;

. There is a critical public need to encourage and promote the revitalization and growth of the state's financial sector and realize its potential as an alternative global financial services hub;

. The fulfillment of this potential can best be achieved by taking measures to:

.. Clarify prudential standards of professional fiduciary management to provide assurances to state, national, and international owners and managers of wealth;

.. Promote flexibility in the management of asset portfolios to respond to ever changing global conditions; and

.. Provide certainty and clear expectations for owners of wealth, asset managers, and their respective advisors;

. Banking institutions and nondepositary trust companies in the state of Washington will be better prepared to continue providing professional fiduciary management services effectively if laws of the state's banking institutions and nondepositary trust companies are modernized, clarified, reorganized and, with respect to some situations, amended;

. There is a need for improved services and reduced costs for trust institution clients and customers and other consumers in this state through modernization of state law to clarify and thereby promote the delegation by trust institutions of fiduciary functions to qualified third-party professionals, to authorize clients to designate any trust institution to act for them, and to protect the public from excessive fees or undisclosed conflicts of interest of trust institutions and their affiliates;

. Properly capitalized and professionally managed trusts and trust companies serving only family members and their affiliated entities, which operate privately and do not hold themselves out to, nor provide services to, the general public, should continue to operate without the necessity of being chartered or regulated by the department of financial institutions;

. The authority of the department of financial institutions needs to be clarified, preserved, and assured as the primary instrument of assuring the safety and soundness of banking institutions and nondepositary trust companies acting as fiduciaries and engaging in trust business in this state;

. Nondepository trust companies should continue to act as fiduciaries and otherwise engage in trust business in this state, so long as they are properly capitalized, competently managed by persons of integrity, and supervised by the department of financial institutions so as to ensure that such trust companies are operated in compliance with law, in a safe and sound manner, and in a manner which protects trust settlors, trust beneficiaries, and the general public in this state; and

. The creation of a comprehensive trust institutions act serves the convenience and advantage of Washington state trust settlors and trust beneficiaries, and the state's general public, and preserves and maintains the fairness of competition and parity between Washington state-chartered banking institutions and trust companies, and federally chartered and out-of-state state-chartered banking institutions and trust companies.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%201[2014 c 37 § 1]; ]

== 30A.04.007 - Notice—Use of internet—Rules.
. Notwithstanding any provisions of this title, wherever notice by publication is required by a bank, such notice may be undertaken by internet publication upon terms and conditions that the director may adopt by rule.

. Notice to shareholders required under this title may be undertaken by electronic means in the same manner as permitted for general business corporations under RCW 23B.01.410.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20149[2014 c 37 § 149]; ]

== 30A.04.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this title.

. "Adequately capitalized," "critically undercapitalized," "significantly undercapitalized," "undercapitalized," and "well-capitalized," respectively, have meanings consistent with the definitions these same terms have under the prompt corrective action provisions of the federal deposit insurance act, 12 U.S.C. Sec. 1831o, and applicable enabling rules of the federal deposit insurance corporation.

. "Bank," unless a different meaning appears from the context, means any corporation organized under the laws of this state engaged in banking, other than a trust company, savings association, or a mutual savings bank.

. "Bank holding company" means a bank holding company under authority of the federal bank holding company act.

. "Banking" includes the soliciting, receiving or accepting of money or its equivalent on deposit as a regular business.

. "Branch" means any established office of deposit, domestic or otherwise, maintained by any bank other than its head office. "Branch" does not mean a machine permitting customers to leave funds in storage or communicate with bank employees who are not located at the site of the machine, unless employees of the bank at the site of the machine take deposits on a regular basis. An office or facility of an entity other than the bank shall not be deemed to be established by the bank, regardless of any affiliation, accommodation arrangement, or other relationship between the other entity and the bank.

. "Corporation," in reference to a bank authorized under this title, means either a corporation operating as a bank authorized under this title or a limited liability company operating as a bank under this title pursuant to the requirements of RCW 30A.08.025.

. "Department" means the Washington state department of financial institutions.

. "Director" means the director of the department.

. "Financial holding company" means a financial services holding company under authority of the federal bank holding company act.

. "Foreign bank" and "foreign banker" includes:

.. Every corporation not organized under the laws of the territory or state of Washington doing a banking business, except a national bank;

.. Every unincorporated company, partnership or association of two or more individuals organized under the laws of another state or country, doing a banking business;

.. Every other unincorporated company, partnership or association of two or more individuals, doing a banking business, if the members thereof owning a majority interest therein or entitled to more than one-half of the net assets thereof are not residents of this state; or

.. Every nonresident of this state doing a banking business in his or her own name and right only.

. "Holding company" means a bank holding company or financial holding company of a bank organized under chapter 30A.08 RCW or converted to a state bank under chapter 30A.49 RCW.

. "Law firm" means a partnership, professional limited liability corporation, professional limited liability partnership, or similar entity whose partners, members, or shareholders are exclusively attorneys-at-law.

. "Person" means an individual or an entity including, but not limited to, a sole proprietorship, firm, association, general partnership or joint venture, limited liability company, limited liability partnership, trust, or corporation, or the plural thereof, whether resident, nonresident, citizen, or not.

. The term "trust business," in relation to a bank, shall include the business of doing any or all of the things specified in *RCW 30B.08.080(1) (b) through (k), together with any other activity authorized for a state trust company by the director pursuant to *RCW 30B.08.080(1)(q) that the director designates as trust business.

. "Trust company," unless a different meaning appears from the context, means any corporation or limited liability company, other than a bank, savings bank, or savings association, organized and chartered as a trust company under Title 30B RCW for the purpose of engaging in trust business.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20102[2014 c 37 § 102]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1325-S.SL.pdf?cite=2013%20c%2076%20§%201[2013 c 76 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2831.SL.pdf?cite=2010%20c%2088%20§%203[2010 c 88 § 3]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1300.SL.pdf?cite=1997%20c%20101%20§%203[1997 c 101 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2125-S.SL.pdf?cite=1996%20c%202%20§%202[1996 c 2 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%207[1994 c 92 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c106.pdf?cite=1959%20c%20106%20§%201[1959 c 106 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.04.010[1955 c 33 § 30.04.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c42.pdf?cite=1933%20c%2042%20§%202[1933 c 42 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c80.pdf?cite=1917%20c%2080%20§%2014[1917 c 80 § 14]; RRS § 3221; ]

== 30A.04.017 - Director's subpoenas—Unauthorized banking activity.
. The director or authorized assistants may apply for and obtain a superior court order approving and authorizing a subpoena in advance of its issuance. The application may be made in the county where the subpoenaed person resides or is found, or the county where the subpoenaed documents, records, or evidence are located, or in Thurston county. The application must:

.. State that an order is sought under this section;

.. Adequately specify the documents, records, evidence, or testimony; and

.. Include a declaration made under oath that an investigation is being conducted for a lawfully authorized purpose related to an investigation within the department's authority and that the subpoenaed documents, records, evidence, or testimony are reasonably related to an investigation within the department's authority.

. When an application under this section is made to the satisfaction of the court, the court must issue an order approving the subpoena. An order under this subsection constitutes authority of law for the agency to subpoena the documents, records, evidence, or testimony.

. The director or authorized assistants may seek approval and a court may issue an order under this section without prior notice to any person, including the person to whom the subpoena is directed and the person who is the subject of an investigation. An application for court approval is subject to the fee and process set forth in RCW 36.18.012(3).

. Subsections (1) through (3) of this section are applicable to the director's enforcement authority under this title against persons engaged in unauthorized banking activity and persons, other than a bank authorized under this title, whom the director has reason to believe are in violation of this title. This section does not limit the authority of the director to investigate or examine a bank authorized under this title without applying for or obtaining a superior court order or issuing a subpoena pursuant to this section.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20261[2014 c 37 § 261]; ]

== 30A.04.020 - Use of words indicating bank or trust company—Penalty.
. The name of every bank shall contain the word "bank" and the name of every trust company shall contain the word "trust," or the word "bank." Except as provided in RCW 33.08.030 or as otherwise authorized by this section or approved by the director, only a national bank, federal savings bank, a bank or trust company, savings bank under Title 32 RCW, bank holding company or financial holding company, a holding company authorized by this title or Title 32 RCW, or a foreign or alien corporation or other legal person authorized by this title to do so, shall:

.. Use as a part of his or her or its name or other business designation, as a prominent syllable within a word comprising all or a portion of its name or other business designation, or in any manner as if connected with his or her or its business or place of business any of the following words or the plural thereof, to wit: "bank," "banking," "banker," "bancorporation," "bancorp," or "trust," or any foreign language designations thereof, including, by way of example, "banco" or "banque."

.. Use any sign, logo, or marketing message, in any media, or use any letterhead, billhead, note, receipt, certificate, blank, form, or any written, printed, electronic or internet-based instrument or material representation whatsoever, directly or indirectly indicating that the business of such person is that of a bank or trust company.

. A foreign corporation or other foreign domiciled legal person, whose name contains the words "bank," "banker," "banking," "bancorporation," "bancorp," or "trust," or the foreign language equivalent thereof, or whose articles of incorporation empower it to engage in banking or to engage in a trust business, may not engage in banking or in a trust business in this state unless the corporation or other legal person (a) is expressly authorized to do so under this title, under federal law, or by the director, and (b) complies with all applicable requirements of Washington state law regarding foreign corporations and other foreign legal persons. If an activity would not constitute "transacting business" within the meaning of RCW 23B.15.010(1) or chapter 23B.18 RCW, then the activity shall not constitute banking or engaging in a trust business. Nothing in this subsection shall prevent operations by an alien bank in compliance with chapter 30A.42 RCW.

. This section shall not prevent a lender approved by the United States secretary of housing and urban development for participation in any mortgage insurance program under the National Housing Act from using the words "mortgage banker" or "mortgage banking" in the conduct of its business, but only if both words are used together in either of the forms which appear in quotations in this sentence.

. Any individual or legal person, or director, officer, or manager of such legal person, who knowingly violates any provision of this section shall be guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20103[2014 c 37 § 103]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2831.SL.pdf?cite=2010%20c%2088%20§%204[2010 c 88 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6285.SL.pdf?cite=1994%20c%20256%20§%2032[1994 c 256 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c284.pdf?cite=1986%20c%20284%20§%2015[1986 c 284 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c42.pdf?cite=1983%20c%2042%20§%202[1983 c 42 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c88.pdf?cite=1981%20c%2088%20§%201[1981 c 88 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.04.020[1955 c 33 § 30.04.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c114.pdf?cite=1925%20ex.s.%20c%20114%20§%201[1925 ex.s. c 114 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c80.pdf?cite=1917%20c%2080%20§%2018[1917 c 80 § 18]; RRS § 3225; ]

== 30A.04.025 - Financial institutions—Loan charges—Out-of-state national banks.
Notwithstanding any restrictions, limitations, requirements, or other provisions of law, a financial institution, as defined in RCW 30A.22.040(8), may charge, take, receive, or reserve interest, discount or other points, finance charges, or other similar charges on any loan or other extension of credit, at a rate or amount that is equal to, or less than, the maximum rate or amount of interest, discount or other points, finance charges, or other similar charges that national banks located in any other state or states may charge, take, receive, or reserve, under 12 U.S.C. Sec. 85, on loans or other extensions of credit to residents of this state. However, this section does not authorize any subsidiary of a bank, of a savings bank, of a savings and loan association, or of a credit union to charge, take, receive, or reserve interest, discount or other points, finance charges, or other similar charges on any loan or other extension of credit, unless the subsidiary is itself a bank, savings bank, savings and loan association, or credit union.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20104[2014 c 37 § 104]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1759-S.SL.pdf?cite=2003%20c%2024%20§%203[2003 c 24 § 3]; ]

== 30A.04.030 - Rules—Administration and interpretation of title.
. The director shall have power to adopt uniform rules in accordance with the administrative procedure act, chapter 34.05 RCW, to govern examinations and reports of banks, trust companies, and holding companies and the form in which they shall report their assets, liabilities, and reserves, charge off bad debts and otherwise keep their records and accounts, and otherwise to govern the administration of this title.

. The director shall have the power, and broad administrative discretion, to administer and interpret the provisions of this title to facilitate the delivery of financial services to the citizens of the state of Washington by the banks, trust companies, and holding companies subject to this title.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20105[2014 c 37 § 105]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2831.SL.pdf?cite=2010%20c%2088%20§%205[2010 c 88 § 5]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%208[1994 c 92 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%201[1986 c 279 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.04.030[1955 c 33 § 30.04.030]; 1917 c 80 § 58, part; RRS § 3265, part; ]

== 30A.04.045 - Director—Powers under chapter  19.144 RCW.
The director or the director's designee may take such action as provided for in this title to enforce, investigate, or examine persons covered by chapter 19.144 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2770-S.SL.pdf?cite=2008%20c%20108%20§%2015[2008 c 108 § 15]; ]

== 30A.04.050 - Duty to comply—Violations—Penalty.
. Each bank and its directors, officers, employees, and agents, shall comply with:

.. This title and Title 30B RCW as applicable to each of them;

.. The rules adopted by the department with respect to banks and trust companies;

.. Any lawful direction or order of the director;

.. Any lawful supervisory agreement with the director; and

.. The applicable statutes, rules, and regulations administered by the board of governors of the federal reserve system, the federal deposit insurance corporation, or their successor agencies, with respect to banks or trust companies.

. Each holding company, and its directors, officers, employees, and agents, shall comply with:

.. The provisions of this title that are applicable to each of them;

.. The rules adopted by the department with respect to holding companies;

.. Any lawful direction or order of the director;

.. Any lawful supervisory agreement with the director; and

.. The applicable statutes, rules, and regulations administered by the board of governors of the federal reserve system, or its successor agency, with respect to holding companies, the violation of which would result in an unsafe and unsound practice or material violation of law with respect to the subsidiary bank of the holding company.

. The violation of any supervisory agreement, direction, order, statute, rule, or regulation referenced in this section, in addition to any other penalty provided in this title, shall, at the option of the director, subject the offender to a penalty of up to ten thousand dollars for each offense, payable upon issuance of any order or directive of the director, which may be recovered by the attorney general in a civil action in the name of the department.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20106[2014 c 37 § 106]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2831.SL.pdf?cite=2010%20c%2088%20§%206[2010 c 88 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.04.050[1955 c 33 § 30.04.050]; 1917 c 80 § 58, part; RRS § 3265, part; ]

== 30A.04.060 - Examinations directed—Cooperative agreements and actions.
. The director, assistant director, program manager, or an examiner shall visit each bank at least once every eighteen months, and oftener if necessary, or as otherwise required by the rules and interpretations of applicable federal banking examination authorities, for the purpose of making a full investigation into the condition of such corporation, and for that purpose they are hereby empowered to administer oaths and to examine under oath any director, officer, employee, or agent of such corporation.

. The director may make such other full or partial examinations as deemed necessary and may examine any bank holding company that owns any portion of a bank chartered by the state of Washington and obtain reports of condition for any bank holding company that owns any portion of a bank chartered by the state of Washington.

. The director may visit and examine into the affairs of any nonpublicly held corporation in which the bank or bank holding company has an investment or any publicly held corporation the capital stock of which is controlled by the bank or bank holding company; may appraise and revalue such corporations' investments and securities; and shall have full access to all the books, records, papers, securities, correspondence, bank accounts, and other papers of such corporations for such purposes.

. The director may, in his or her discretion, accept in lieu of the examinations required in this section the examinations conducted at the direction of the federal reserve board or the federal deposit insurance corporation.

. Any willful false swearing in any examination is perjury in the second degree.

. The director may enter into cooperative and reciprocal agreements with the bank regulatory authorities of the United States, any state, the District of Columbia, or any trust territory of the United States for the periodic examination of domestic bank holding companies owning banking institutions in other states, the District of Columbia, or trust territories, and subsidiaries of such domestic bank holding companies, or of out-of-state bank holding companies owning a bank the principal operations of which are conducted in this state. The director may accept reports of examination and other records from such authorities in lieu of conducting his or her own examinations. The director may enter into joint actions with other regulatory bodies having concurrent jurisdiction or may enter into such actions independently to carry out his or her responsibilities under this title and assure compliance with the laws of this state.

. Copies from the records, books, and accounts of a bank or holding company shall be competent evidence in all cases, equal with originals thereof, if there is annexed to such copies an affidavit taken before a notary public or clerk of a court under seal, stating that the affiant is the officer of the bank or holding company having charge of the original records, and that the copy is true and correct and is full so far as the same relates to the subject matter therein mentioned.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20107[2014 c 37 § 107]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2831.SL.pdf?cite=2010%20c%2088%20§%207[2010 c 88 § 7]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%209[1994 c 92 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c180.pdf?cite=1989%20c%20180%20§%201[1989 c 180 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c305.pdf?cite=1985%20c%20305%20§%203[1985 c 305 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c157.pdf?cite=1983%20c%20157%20§%203[1983 c 157 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c196.pdf?cite=1982%20c%20196%20§%206[1982 c 196 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.04.060[1955 c 33 § 30.04.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c48.pdf?cite=1937%20c%2048%20§%201[1937 c 48 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c209.pdf?cite=1919%20c%20209%20§%205[1919 c 209 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c80.pdf?cite=1917%20c%2080%20§%207[1917 c 80 § 7]; RRS § 3214; ]

== 30A.04.070 - Costs of examination, filing, and other service fees—Nondirect expenses.
. In order to cover the costs of the operation of the department's division of banks and to establish and maintain a reasonable reserve for the division of banks, the department may charge and collect the costs of examination, filing and other service fees, and semiannual charges for recoupment of nondirect expenses related to the examination of financial institutions regulated by the department, as provided for in this section.

. The director shall collect from each bank, savings bank, trust company, savings association, holding company under this title, holding company under Title 32 RCW, business development company under chapter 31.24 RCW, agricultural lender under chapter 31.35 RCW, and small business lender under chapter 31.40 RCW:

.. For each examination of its condition the estimated actual cost of such examination; and

.. For services in relation to required filings, applications, requests for waiver, investigations, approvals, determinations, certifications, agreements, actions, directives, and orders made by or to the director.

. In addition to collecting the estimated actual cost of examination and other fees authorized by subsection (2) of this section, the director may collect a semiannual charge for recoupment of nondirect expenses related to the examination of a bank under this title, a trust company, a savings bank under Title 32 RCW, and a savings association under Title 33 RCW, based upon the assets of the bank, savings bank, or savings association, or assets under management of the trust company, which shall be computed upon the asset value reflected in the institution's most recent report of condition. The rate must be the same for banks, savings banks, and savings associations, and there may be a separate rate for trust companies that must be the same for all trust companies.

. Every bank or trust company, savings bank, savings association, holding company, business development company, state agricultural lender, or state small business lender shall also pay to the secretary of state for filing any instrument the same fees as are required of general corporations for filing corresponding instruments, and also the same license fees as are required of general corporations.

. The director shall establish, set, and adjust by rule the amount of all fees and charges authorized by subsections (2) and (3) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20108[2014 c 37 § 108]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1325-S.SL.pdf?cite=2013%20c%2076%20§%202[2013 c 76 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2831.SL.pdf?cite=2010%20c%2088%20§%208[2010 c 88 § 8]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2010[1994 c 92 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.04.070[1955 c 33 § 30.04.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c73.pdf?cite=1929%20c%2073%20§%201[1929 c 73 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c172.pdf?cite=1923%20c%20172%20§%2016[1923 c 172 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c73.pdf?cite=1921%20c%2073%20§%201[1921 c 73 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c80.pdf?cite=1917%20c%2080%20§%208[1917 c 80 § 8]; RRS § 3215; ]

== 30A.04.075 - Examination reports and information—Confidentiality—Disclosure—Penalty.
. All examination reports and all information obtained by the director and the director's staff in conducting examinations of banks, trust companies, or alien banks, and information obtained by the director and the director's staff from other state or federal bank regulatory authorities with whom the director has entered into agreements pursuant to RCW 30A.04.060(6), and information obtained by the director and the director's staff relating to examination and supervision of bank holding companies owning a bank in this state or subsidiaries of such holding companies, is confidential and privileged information and shall not be made public or otherwise disclosed to any person, firm, corporation, agency, association, governmental body, or other entity.

. Subsection (1) of this section notwithstanding, the director may furnish all or any part of examination reports, work papers, supervisory agreements or directives, orders, or other information obtained in the conduct of an examination or investigation prepared by the director's office to:

.. Federal agencies empowered to examine state banks, trust companies, or alien banks;

.. Bank regulatory authorities with whom the director has entered into agreements pursuant to RCW 30A.04.060(6), and other bank regulatory authorities who are the primary regulatory authority or insurer of accounts for a bank holding company owning a bank, trust company, or national banking association the principal operations of which are conducted in this state or a subsidiary of such holding company; provided that the director shall first find that the reports of examination to be furnished shall receive protection from disclosure comparable to that accorded by this section;

.. Officials empowered to investigate criminal charges subject to legal process, valid search warrant, or subpoena. If the director furnishes any examination report to officials empowered to investigate criminal charges, the director may only furnish that part of the report which is necessary and pertinent to the investigation, and the director may do this only after notifying the affected bank, trust company, or alien bank and any customer of the bank, trust company, or alien bank who is named in that part of the examination or report ordered to be furnished unless the officials requesting the report first obtain a waiver of the notice requirement from a court of competent jurisdiction for good cause;

.. The examined bank, trust company, or alien bank, or holding company thereof;

.. The attorney general in his or her role as legal advisor to the director;

.. Liquidating agents of a distressed bank, trust company, or alien bank;

.. A person or organization officially connected with the bank as officer, director, attorney, auditor, or independent attorney or independent auditor;

.. The Washington public deposit protection commission as provided by RCW 39.58.105;

.. Organizations insuring or guaranteeing the shares of, or deposits in, the bank or trust company; or

.. Other persons as the director may determine necessary to protect the public interest and confidence.

. All examination reports, work papers, supervisory agreements or directives, orders, and other information obtained in the conduct of an examination or investigation furnished under subsections (2) and (4) of this section shall remain the property of the department of financial institutions, and be confidential and no person, agency, or authority to whom reports are furnished or any officer, director, or employee thereof shall disclose or make public any of the reports or any information contained therein except in published statistical material that does not disclose the affairs of any individual or corporation: PROVIDED, That nothing herein shall prevent the use in a criminal prosecution of reports furnished under subsection (2) of this section.

. The examination report made by the department of financial institutions is designed for use in the supervision of the bank, trust company, or alien bank. The report shall remain the property of the director and will be furnished to the bank, trust company, or alien bank solely for its confidential use. Under no circumstances shall the bank, trust company, or alien bank or any of its directors, officers, or employees disclose or make public in any manner the report or any portion thereof, to any person or organization not connected with the bank as officer, director, employee, attorney, auditor, or candidate for executive office with the bank. The bank may also, after execution of an agreement not to disclose information in the report, disclose the report or relevant portions thereof to a party proposing to acquire or merge with the bank.

. Examination reports and information obtained by the director and the director's staff in conducting examinations, or obtained from other state and federal bank regulatory authorities with whom the director has entered into agreements pursuant to RCW 30A.04.060(6), or relating to examination and supervision of bank holding companies owning a bank, trust company, or national banking association the principal operations of which are conducted in this state or a subsidiary of such holding company, or information obtained as a result of applications or investigations pursuant to RCW 30A.04.230, shall not be subject to public disclosure under chapter 42.56 RCW.

. In any civil action in which the reports are sought to be discovered or used as evidence, any party may, upon notice to the director, petition the court for an in camera review of the report. The court may permit discovery and introduction of only those portions of the report which are relevant and otherwise unobtainable by the requesting party. This subsection shall not apply to an action brought or defended by the director.

. This section shall not apply to investigation reports prepared by the director and the director's staff concerning an application for a new bank or trust company or an application for a branch of a bank, trust company, or alien bank: PROVIDED, That the director may adopt rules making confidential portions of the reports if in the director's opinion the public disclosure of the portions of the report would impair the ability to obtain the information which the director considers necessary to fully evaluate the application.

. Notwithstanding any other provision of this section or other applicable law, a bank, trust company, alien bank, or holding company is not in violation of this section on account of its compliance with required reporting to the federal securities and exchange commission, including the disclosure of any order of the director.

. Every person who violates any provision of this section shall be guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20109[2014 c 37 § 109]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2831.SL.pdf?cite=2010%20c%2088%20§%209[2010 c 88 § 9]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20251[2005 c 274 § 251]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2011[1994 c 92 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c180.pdf?cite=1989%20c%20180%20§%202[1989 c 180 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%202[1986 c 279 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c245.pdf?cite=1977%20ex.s.%20c%20245%20§%201[1977 ex.s. c 245 § 1]; ]

== 30A.04.111 - Limit on loans and extensions of credit to one person—Exceptions—Definitions—Rules—Nonconforming loans and extensions of credit.
. The total loans and extensions of credit by a bank to a person outstanding at any one time shall not exceed twenty percent of the capital and surplus of such bank. A loan or extension of credit made by a bank does not violate this section if the loan or extension of credit would qualify for an exception to the lending limit for a national bank under rules adopted by the United States office of the comptroller of the currency, or successor federal agency with authority over national banks and federal savings associations.

. For the purposes of this section, the terms "borrower," "capital and surplus," "derivative transaction," "loans and extensions of credit," and "person" shall have the same meaning as those terms are defined in section 32.2 of Title 12 of the United States Code of Federal Regulations, 12 C.F.R. Sec. 32.2, except that "loans and extensions of credit" also includes repurchase agreements, reverse repurchase agreements, securities lending transactions, or securities borrowing transactions between a bank and a borrower if the federal deposit insurance corporation requires such treatment for a state insured bank or the board of governors of the federal reserve system requires such treatment for member state banks.

. The director may prescribe rules to administer and carry out the purposes of this section, including without limitation rules (a) to define or further define terms used in this section, (b) to establish limits or requirements other than those specified in this section for particular classes or categories of loans and extensions of credit, (c) to determine when a loan putatively made to a person shall, for purposes of this section, be attributed to another person, (d) to set standards for computation of time in relation to determining limits on loans and extensions of credit, and (e) to implement and incorporate other changes in limits on loans and extensions of credit necessary to conform to federal statute and rule required or otherwise authorized by this section. In adopting the rules, the director shall be guided by rulings of the United States comptroller of the currency, or successor federal banking regulator, that govern limits on loans and extensions of credit applicable to national banks and federal savings associations. In lieu of the adoption by the department of a rule applicable to specific types of transactions, a bank, unless otherwise approved by the director, shall conform to all applicable rulings of the comptroller of the currency, or successor federal banking regulator, which (i) relate to national banks and federal savings associations, (ii) govern such specific types of transactions or circumstances, and (iii) are consistent with this section and the department's adopted rules.

. [Empty]
.. A loan or extension of credit that was within the limit on loans and extensions of credit when made is not a violation but will be treated as nonconforming if the loan or extension of credit is no longer in conformity with the bank's limit on loans and extensions of credit because:

... The bank's capital has declined, borrowers have subsequently merged or formed a common enterprise, lenders have merged, or the limit on loans and extensions of credit or capital rules have changed; or

... Collateral securing the loan or extension of credit, in order to satisfy the requirements of an exception to the limit, has declined in value.

.. A bank shall make reasonable efforts to bring a loan or extension of credit that is nonconforming under (a)(i) of this subsection into conformity with the bank's limit on loans and extensions of credit unless to do so would be inconsistent with safe and sound banking practices.

.. A bank must bring a loan or extension of credit that is nonconforming under (a)(ii) of this subsection into conformity with the bank's limit on loans and extensions of credit within thirty calendar days, except when judicial proceedings, regulatory actions, or other extraordinary circumstances beyond the bank's control prevent the bank or trust company from taking action.

.. Notwithstanding any provision of this subsection (4), the director may by rule or interpretation prescribe standards for treatment of nonconforming extensions of credit that are derivatives transactions, repurchase agreements, reverse repurchase agreements, securities lending transactions, or securities borrowing transactions, and may, if required for state insured banks or member state banks, rely upon rules or interpretations of the federal deposit insurance corporation or the board of governors of the federal reserve system, as applicable.

. Notwithstanding any provision of this section to the contrary, in the event that a bank's capital declines sufficiently to seriously impair the bank's ability to effectively operate in its marketplace or serve the needs of its customers or the community in which it is located, the director may, upon written application and in the exercise of the director's discretion, grant the bank temporary permission to fund loans and extensions of credit in excess of the bank's limit on loans and extensions of credit under this section. In the exercise of discretion, the director may further specify conditions for granting such emergency exception and may limit emergency lending authority under this section to particular types or classes of loans and extensions of credit.

. Notwithstanding any provision of this section to the contrary, the director, in the exercise of discretion, may grant an exception to the limit on loans and extensions of credit otherwise required by this section, based on extenuating facts and circumstances. In deciding whether to grant an exception under this subsection, the director shall consider:

.. The proposed transaction for which the exception is sought;

.. How the requested exception would affect the capital adequacy and safety and soundness of the requesting bank if the exception is not granted or, if the exception is granted, if the proposed borrower should ultimately default;

.. How the requested exception would affect the loan portfolio diversification of the requesting bank;

.. The competency of management to handle the proposed transaction and any resulting safety and soundness issues;

.. The marketability and value of the proposed collateral; and

.. The extenuating facts and circumstances that warrant an exception in light of the purpose of limit on loans and extensions of credit set forth in this section.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20110[2014 c 37 § 110]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1325-S.SL.pdf?cite=2013%20c%2076%20§%203[2013 c 76 § 3]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2831.SL.pdf?cite=2010%20c%2088%20§%2010[2010 c 88 § 10]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5931.SL.pdf?cite=1995%20c%20344%20§%201[1995 c 344 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2012[1994 c 92 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%203[1986 c 279 § 3]; ]

== 30A.04.112 - "Loans or obligations" and "liabilities" limited for purposes of RCW  30.04.111.
Sales of federal reserve funds with a maturity of one business day or under a continuing contract are not "loans or obligations" or "liabilities" for the purposes of the loan limits established by *RCW 30.04.111. However, sales of federal reserve funds with a maturity of more than one business day are subject to those limits.

For the purposes of this section, "sale of federal reserve funds" means any transaction among depository institutions involving the disposal of immediately available funds resulting from credits to deposit balances at federal reserve banks or from credits to new or existing deposit balances due from a correspondent depository institution.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c220.pdf?cite=1989%20c%20220%20§%201[1989 c 220 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c157.pdf?cite=1983%20c%20157%20§%202[1983 c 157 § 2]; ]

== 30A.04.120 - Loans on own stock prohibited—Shares of other corporations.
The shares of stock of every bank shall be deemed personal property. No such corporation shall hereafter make any loan or discount on the security of its own capital stock, nor be the purchaser or holder of any such shares, unless such security or purchase shall be necessary to prevent loss upon a debt previously contracted in good faith; in which case the stocks so purchased or acquired shall be sold at public or private sale, or otherwise disposed of, within six months from the time of its purchase or acquisition. Except as hereinafter provided or otherwise permitted by law, nothing herein contained shall authorize the purchase by any such bank for its own account of any shares of stock of any corporation, except a federal reserve bank of which such corporation shall become a member, and then only to the extent required by such federal reserve bank: PROVIDED, That any bank may purchase, acquire and hold shares of stock in any other corporation which shares have been previously pledged as security to any loan or discount made in good faith and such purchase shall be necessary to prevent loss upon a debt previously contracted in good faith and stock so purchased or acquired shall be sold at public or private sale or otherwise disposed of within two years from the time of its purchase or acquisition. Any time limit imposed in this section may be extended by the director upon cause shown. Banks are authorized to make loans on the security of the capital stock of a bank other than the lending corporation.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20111[2014 c 37 § 111]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2013[1994 c 92 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%204[1986 c 279 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c104.pdf?cite=1973%201st%20ex.s.%20c%20104%20§%201[1973 1st ex.s. c 104 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.04.120[1955 c 33 § 30.04.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c187.pdf?cite=1943%20c%20187%20§%201[1943 c 187 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c42.pdf?cite=1933%20c%2042%20§%209[1933 c 42 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c73.pdf?cite=1929%20c%2073%20§%205[1929 c 73 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c80.pdf?cite=1917%20c%2080%20§%2036[1917 c 80 § 36]; Rem. Supp. 1943 § 3243; ]

== 30A.04.125 - Investment in corporations—Authorized businesses.
Unless otherwise prohibited by law, any state bank may invest in the capital stock of corporations organized to conduct the following businesses:

. A safe deposit business: PROVIDED, That the amount of investment does not exceed fifteen percent of its capital stock and surplus, without the approval of the director;

. A corporation holding the premises of the bank or its branches: PROVIDED, That without the approval of the director, the investment of such stock shall not exceed, together with all loans made to the corporation by the bank, a sum equal to the amount permitted to be invested in the premises by RCW 30A.04.210;

. Stock in a small business investment company licensed and regulated by the United States as authorized by the small business act, Public Law 85-536, 72 Statutes at Large 384, in an amount not to exceed five percent of its capital and surplus without the approval of the director;

. Capital stock of a banking service corporation or corporations. The total amount that a bank may invest in the shares of such corporation may not exceed ten percent of its capital and surplus without the approval of the director. A bank service corporation may not engage in any activity other than those permitted by the bank service corporation act, 12 U.S.C. Sec. 1861, et seq., as subsequently amended and in effect on December 31, 1993. The performance of any service, and any records maintained by any such corporation for a bank, shall be subject to regulation and examination by the director and appropriate federal agencies to the same extent as if the services or records were being performed or maintained by the bank on its own premises;

. Capital stock of a federal reserve bank to the extent required by such federal reserve bank;

. A corporation engaging in business activities that have been determined by the board of governors of the federal reserve system or by the United States congress to be closely related to the business of banking, as of December 31, 1993;

. A governmentally sponsored corporation engaged in secondary marketing of loans and the stock of which must be owned in order to participate in its marketing activities;

. A corporation in which all of the voting stock is owned by the bank and that engages exclusively in nondeposit-taking activities that are authorized to be engaged in by the bank or trust company;

. A bank may purchase for its own account shares of stock of a bank or a holding company that owns or controls a bank if the stock of the bank or company is owned exclusively, except to the extent directly qualifying shares are required by law, by depository institutions and the bank or company and all subsidiaries thereof are engaged exclusively in providing services for other depository institutions and their officers, directors, and employees. In no event may the total amount of such stock held by a bank in any bank or bank holding company exceed at any time ten percent of its capital stock and paid-in and unimpaired surplus, and in no event may the purchase of such stock result in a bank acquiring more than twenty-five percent of any class of voting securities of such bank or company. Such a bank or bank holding company shall be called a "banker's bank."

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20112[2014 c 37 § 112]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6285.SL.pdf?cite=1994%20c%20256%20§%2033[1994 c 256 § 33]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2014[1994 c 92 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%205[1986 c 279 § 5]; ]

== 30A.04.127 - Formation, incorporation, or investment in corporations or other entities authorized—Approval—Exception.
. A bank, alone or in conjunction with other entities, may form, incorporate, or invest in corporations or other entities, whether or not such other corporation or entity is related to the bank's business. The aggregate amount of funds invested, or used in the formation of corporations or other entities under this section shall not exceed ten percent of the assets or fifty percent of the net worth, whichever is less, of the bank. For purposes of this subsection, "net worth" means the aggregate of capital, surplus, undivided profits, and all capital notes and debentures which are subordinate to the interest of depositors.

. A bank may engage in an activity permitted under this section only with the prior authorization of the director and subject to such requirements, restrictions, or other conditions as the director may adopt by rule, order, directive, standard, policy, memorandum, or other written communication with regard to the activity. In approving or denying a proposed activity, the director shall consider the financial and management strength of the institution, the convenience and needs of the public, and whether the proposed activity should be conducted through a subsidiary or affiliate of the bank. The director may not authorize under this section and no bank may act as an insurance or travel agent unless otherwise authorized by state statute.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20113[2014 c 37 § 113]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2831.SL.pdf?cite=2010%20c%2088%20§%2011[2010 c 88 § 11]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2015[1994 c 92 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c498.pdf?cite=1987%20c%20498%20§%201[1987 c 498 § 1]; ]

== 30A.04.129 - Investment in obligations issued or guaranteed by multilateral development bank.
Any bank may invest in obligations issued or guaranteed by any multilateral development bank in which the United States government formally participates. Such investment in any one multilateral development bank shall not exceed five percent of the bank's paid-in capital and surplus.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20114[2014 c 37 § 114]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c301.pdf?cite=1985%20c%20301%20§%202[1985 c 301 § 2]; ]

== 30A.04.130 - Defaulted debts, judgments to be charged off—Valuation of assets.
Based on examinations directed pursuant to RCW 30A.04.060 or other appropriate information, all assets or portion thereof that the director may have required a bank to charge off shall be charged off. No bank shall enter or at any time carry on its books any of its assets or liabilities at a valuation contrary to generally accepted accounting principles.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20115[2014 c 37 § 115]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6285.SL.pdf?cite=1994%20c%20256%20§%2034[1994 c 256 § 34]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2016[1994 c 92 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%206[1986 c 279 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.04.130[1955 c 33 § 30.04.130]; prior:  1937 c 61 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c209.pdf?cite=1919%20c%20209%20§%2015[1919 c 209 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c80.pdf?cite=1917%20c%2080%20§%2047[1917 c 80 § 47]; RRS § 3254; ]

== 30A.04.140 - Pledge of securities or assets prohibited—Exceptions.
No bank shall pledge or hypothecate any of its securities or assets to any depositor, except that it may qualify as depositary for United States deposits, or other public funds, or funds held in trust and deposited by any public officer by virtue of his or her office, or as a depository for the money of estates under the statutes of the United States pertaining to bankruptcy or funds deposited by a trustee or receiver in bankruptcy appointed by any court of the United States or any referee thereof, or funds held by the United States or the state of Washington, or any officer thereof in trust, or for funds of corporations owned or controlled by the United States, and may give such security for such deposits as are required by law or by the officer making the same; and it may give security to its trust department for deposits with itself which represent trust funds invested in savings accounts or which represent fiduciary funds awaiting investment or distribution.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20116[2014 c 37 § 116]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20744[2011 c 336 § 744]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%207[1986 c 279 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c157.pdf?cite=1983%20c%20157%20§%206[1983 c 157 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c133.pdf?cite=1967%20c%20133%20§%202[1967 c 133 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.04.140[1955 c 33 § 30.04.140]; 1933 c 42 § 24, part; 1917 c 80 § 54, part; RRS § 3261, part; ]

== 30A.04.180 - Dividends.
No bank shall declare or pay any dividend to an amount greater than its retained earnings, without approval from the director. The director shall in his or her discretion have the power to require any bank to suspend the payment of any and all dividends until all requirements that may have been made by the director shall have been complied with; and upon such notice to suspend dividends no bank shall thereafter declare or pay any dividends until such notice has been rescinded in writing. A dividend is payable in cash, property, or capital stock, but the restrictions on the payment of a dividend (other than restrictions imposed by the director pursuant to his or her authority to require the suspension of the payment of any or all dividends) do not apply to a dividend payable by the bank solely in its own capital stock. For purposes of this section, "retained earnings" shall be determined by generally accepted accounting principles.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20117[2014 c 37 § 117]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6285.SL.pdf?cite=1994%20c%20256%20§%2035[1994 c 256 § 35]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2017[1994 c 92 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%208[1986 c 279 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c89.pdf?cite=1981%20c%2089%20§%201[1981 c 89 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c136.pdf?cite=1969%20c%20136%20§%202[1969 c 136 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.04.180[1955 c 33 § 30.04.180]; prior:  1933 c 42 § 7; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1931c11.pdf?cite=1931%20c%2011%20§%201[1931 c 11 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c80.pdf?cite=1917%20c%2080%20§%2033[1917 c 80 § 33]; RRS § 3240; ]

== 30A.04.210 - Real estate holdings.
A bank may purchase, hold, and convey real estate for the following purposes:

. Such as shall be necessary for the convenient transaction of its business, including with its banking offices other space in the same building to rent as a source of income: PROVIDED, That any bank shall not invest for such purposes more than the greater of: (a) Fifty percent of its capital, surplus, and undivided profits; or (b) one hundred twenty-five percent of its capital stock without the approval of the director.

. Such as shall be purchased or conveyed to it in satisfaction, or on account of, debts previously contracted in the course of its business.

. Such as it shall purchase at sale under judgments, decrees, liens, or mortgage foreclosures, from debts owed to it.

. Such as a trust company receives in trust or acquires pursuant to the terms or authority of any trust.

. Such as it may take title to or for the purpose of investing in real estate conditional sales contracts.

. Such as shall be purchased, held, or conveyed in accordance with RCW 30A.04.212 granting banks the power to invest directly or indirectly in unimproved or improved real estate.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20118[2014 c 37 § 118]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6285.SL.pdf?cite=1994%20c%20256%20§%2036[1994 c 256 § 36]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2018[1994 c 92 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%209[1986 c 279 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c329.pdf?cite=1985%20c%20329%20§%204[1985 c 329 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c142.pdf?cite=1979%20c%20142%20§%201[1979 c 142 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c104.pdf?cite=1973%201st%20ex.s.%20c%20104%20§%202[1973 1st ex.s. c 104 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.04.210[1955 c 33 § 30.04.210]; prior:  1947 c 149 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c80.pdf?cite=1917%20c%2080%20§%2037[1917 c 80 § 37]; Rem. Supp. 1947 § 3244; ]

== 30A.04.212 - Real property and improvements thereon.
. In addition to the powers granted under RCW 30A.04.210 and subject to the limitations and restrictions contained in this section and in RCW 30A.60.010 and 30A.60.020, a bank:

.. May acquire any interest in unimproved or improved real property;

.. May construct, alter, and manage improvements of any description on real estate in which it holds a substantial equity interest.

. The powers granted under subsection (1) of this section do not include, and a bank may not:

.. Manage any real property in which the bank does not own a substantial equity interest;

.. Engage in activities of selling, leasing, or otherwise dealing in real property as an agent or broker; or

.. Acquire any equity interest in any one to four-family dwelling that is used as a principal residence by the owner of the dwelling; however, this shall not prohibit a bank from making loans secured by such dwelling where all or part of the bank's anticipated compensation results from the appreciation and sale of such dwelling.

. The aggregate amount of funds invested under this section shall not exceed two percent of a bank's capital, surplus, and undivided profits. Such percentage amount shall be increased based upon the most recent community reinvestment rating assigned to a bank by the director in accordance with RCW 30A.60.010, as follows:

.. Excellent performance: Increase to 10%

.. Good performance: Increase to 8%

.. Satisfactory performance: Increase to 6%

.. Inadequate performance: Increase to 3%

.. Poor performance: No increase

. For purposes of this section only, each bank will be deemed to have been assigned a community reinvestment rating of "1" for the period beginning with January 1, 1986, and ending December 31, 1986. Thereafter, each bank will be assigned an annual rating in accordance with RCW 30A.60.010, which rating shall remain in effect for the next succeeding year and until the director has conducted a new investigation and assigned a new rating for the next succeeding year, the process repeating on an annual basis.

. No bank may at any time be required to dispose of any investment made in accordance with this section due to the fact that the bank is not then authorized to acquire such investment, if such investment was lawfully acquired by the bank at the time of acquisition.

. The director shall limit the amount that may be invested in a single project or investment and may adopt any rule necessary to the safe and sound exercise of powers granted by this section.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20119[2014 c 37 § 119]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2019[1994 c 92 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c329.pdf?cite=1985%20c%20329%20§%205[1985 c 329 § 5]; ]

== 30A.04.214 - Qualifying community investments.
. An amount equal to ten percent of the aggregate amount invested in real estate in accordance with RCW 30A.04.212 shall be placed in qualifying community investments as defined in subsection (2) of this section.

. "Qualifying community investment" means any direct or indirect investment or extension of credit made by a bank in projects or programs designed to develop or redevelop areas in which persons with low or moderate incomes reside, designed to meet the credit needs of such low or moderate-income areas, or that primarily benefits low and moderate-income residents of such areas. The term includes, but is not limited to, any of the following within the state of Washington:

.. Investments in governmentally insured, guaranteed, subsidized, or otherwise sponsored programs for housing, small farms, or businesses that address the needs of the low and moderate-income areas.

.. Investments in residential mortgage loans, home improvements loans, housing rehabilitation loans, and small business or small farm loans originated in low and moderate-income areas, or the purchase of such loans originated in low and moderate-income areas.

.. Investments for the preservation or revitalization of urban or rural communities in low and moderate-income areas.

The term does not include personal installment loans, loans made to purchase, or loans secured by an automobile.

. A qualifying community investment made by an entity that wholly owns a bank, is wholly owned by a bank, or is wholly owned by an entity that wholly owns the bank is deemed to have been made by a bank to satisfy the requirements of subsection (1) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20120[2014 c 37 § 120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c329.pdf?cite=1985%20c%20329%20§%206[1985 c 329 § 6]; ]

== 30A.04.215 - Engaging in other business activities.
. Notwithstanding any other provisions of law, in addition to all powers enumerated by this title, and those necessarily implied therefrom, a bank may engage in other business activities that have been determined by the board of governors of the federal reserve system or by the United States Congress to be closely related to the business of banking, as of July 28, 2013.

. A bank that desires to perform an activity that is not expressly authorized by subsection (1) of this section shall first apply to the director for authorization to conduct such activity. Within thirty days of the receipt of this application, the director shall determine whether the activity is closely related to the business of banking, whether the public convenience and advantage will be promoted, whether the activity is apt to create an unsafe and unsound practice by the bank and whether the applicant is capable of performing such an activity. If the director finds the activity to be closely related to the business of banking and the bank is otherwise qualified, he or she shall immediately inform the applicant that the activity is authorized. If the director determines that such activity is not closely related to the business of banking or that the bank is not otherwise qualified, he or she shall promptly inform the applicant in writing. The applicant shall have the right to appeal from an unfavorable determination in accordance with the procedures of the Administrative Procedure Act, chapter 34.05 RCW. In determining whether a particular activity is closely related to the business of banking, the director shall be guided by the rulings of the board of governors of the federal reserve system and the comptroller of the currency in making determinations in connection with the powers exercisable by bank holding companies, and the activities performed by other commercial banks or their holding companies.

. Notwithstanding any restrictions, limitations, and requirements of law, in addition to all powers, express or implied, that a bank has under the laws of this state, a bank shall have the powers and authorities conferred as of July 28, 1985, or as of any subsequent date not later than July 28, 2013, upon any federally chartered bank doing business in this state. A bank may exercise the powers and authorities conferred on a federally chartered bank after July 28, 2013, only if the director finds that the exercise of such powers and authorities:

.. Serves the convenience and advantage of depositors, borrowers, or the general public; and

.. Maintains the fairness of competition and parity between state-chartered banks and federally chartered banks.

. Notwithstanding any other provisions of law, a bank has the powers and authorities that an out-of-state state bank operating a branch in Washington has if the director finds that the exercise of such powers and authorities serves the convenience and advantage of depositors and borrowers, or the general public, and maintains the fairness of competition and parity between state-chartered banks and out-of-state state banks.

. As used in this section, "powers and authorities" include without limitation powers and authorities in corporate governance and operational matters.

. The restrictions, limitations, and requirements applicable to specific powers and authorities of federally chartered banks and out-of-state state banks, as applicable, shall apply to banks exercising those powers and authorities permitted under this section but only insofar as the restrictions, limitations, and requirements relate to exercising the powers and authorities granted banks solely under this section.

. The director may require a bank to provide notice to the director prior to implementation of a plan to develop, improve, or continue holding real estate, including capitalized and operating leases, acquired through any means in full or partial satisfaction of a debt previously contracted, under circumstances which a national bank would be required to provide notice to the comptroller of the currency prior to implementation of such a plan. The director may adopt rules or issue orders, directives, standards, policies, memoranda, or other official communications to specify guidance with regard to the exercise of the powers and authorities to expend such funds as are needed to enable a bank to recover its total investment to the fullest extent authorized for a national bank under the national bank act, 12 U.S.C. Sec. 29.

. Any activity which may be performed by a bank, except the taking of deposits, may be performed by (a) a corporation or (b) another entity approved by the director, which in either case is owned in whole or in part by the bank.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20121[2014 c 37 § 121]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1325-S.SL.pdf?cite=2013%20c%2076%20§%204[2013 c 76 § 4]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2831.SL.pdf?cite=2010%20c%2088%20§%2012[2010 c 88 § 12]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1759-S.SL.pdf?cite=2003%20c%2024%20§%202[2003 c 24 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5931.SL.pdf?cite=1995%20c%20344%20§%202[1995 c 344 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1015.SL.pdf?cite=1995%20c%20134%20§%202[1995 c 134 § 2]; prior:  1994 c 256 § 37; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2020[1994 c 92 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2010[1986 c 279 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c157.pdf?cite=1983%20c%20157%20§%208[1983 c 157 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c136.pdf?cite=1969%20c%20136%20§%207[1969 c 136 § 7]; ]

== 30A.04.217 - Additional powers of a bank—Powers and authorities of savings bank—Definition—Restrictions.
. Notwithstanding any other provisions of law, in addition to all powers, express or implied, that a bank has under the laws of this state, a bank shall have the powers and authorities conferred upon a savings bank under Title 32 RCW.

. As used in this section, "powers and authorities" include without limitation powers and authorities in corporate governance and operational matters.

. The restrictions, limitations, and requirements applicable to specific powers and authorities of savings banks shall apply to banks exercising those powers and authorities permitted under this section but only insofar as the restrictions, limitations, and requirements relate to exercising the powers and authorities granted banks solely under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1325-S.SL.pdf?cite=2013%20c%2076%20§%205[2013 c 76 § 5]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2831.SL.pdf?cite=2010%20c%2088%20§%2013[2010 c 88 § 13]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1759-S.SL.pdf?cite=2003%20c%2024%20§%201[2003 c 24 § 1]; ]

== 30A.04.220 - Corporations existing under former laws.
Every corporation, which on March 10, 1917, was actually and publicly engaged in banking or trust business in this state in full compliance with the laws hereof, which were in force immediately prior to March 10, 1917, may, if it otherwise complies with the provisions of this title, continue its said business, subject to the terms and regulations hereof and without amending its articles of incorporation, although its name and the amount of its capital stock, the number or length of terms of its directors or the form of its articles of incorporation do not comply with the requirements of this title: PROVIDED,

. That any such bank, which was by the director lawfully permitted to operate, although its capital stock was not fully paid in, shall pay in the balance of its capital stock at such times and in such amounts as the director may require;

. That, except with written permission of the director, any bank which shall amend its articles of incorporation must in such event comply with all the requirements of this title.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20122[2014 c 37 § 122]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2021[1994 c 92 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.04.220[1955 c 33 § 30.04.220]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c31.pdf?cite=1937%20c%2031%20§%201[1937 c 31 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c80.pdf?cite=1917%20c%2080%20§%2078[1917 c 80 § 78]; RRS § 3285; ]

== 30A.04.225 - Contributions and gifts.
In the absence of an express prohibition in its articles of incorporation, the making of contributions or gifts for the public welfare, or for charitable, scientific, or educational purposes by a state bank is within its powers and shall be deemed to inure to the benefit of the bank.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20123[2014 c 37 § 123]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2011[1986 c 279 § 11]; ]

== 30A.04.230 - Authority of corporation or association to acquire stock of bank or national banking association.
. A corporation or association organized under the laws of this state or licensed to transact business in the state may acquire any or all shares of stock of any bank or national banking association. Nothing in this section shall be construed to prohibit the merger, consolidation, or reorganization of a bank in accordance with this title.

. Unless the terms of this section or RCW 30A.04.232 are complied with, an out-of-state bank holding company shall not acquire more than five percent of the shares of the voting stock or all or substantially all of the assets of a bank or national banking association the principal operations of which are conducted within this state.

. As used in this section a "bank holding company" means a company that is a bank holding company as defined by the Bank Holding Company Act of 1956, as amended (12 U.S.C. Sec. 1841 et seq.). An "out-of-state bank holding company" is a bank holding company that principally conducts its operations outside this state, as measured by total deposits held or controlled by its bank subsidiaries on the date on which it became a holding company. A "domestic bank holding company" is a bank holding company that principally conducts its operations within this state, as measured by total deposits held or controlled by its bank subsidiaries on the date on which it became a bank holding company.

. Any such acquisition referred to under subsection (2) of this section by an out-of-state bank holding company requires the express written approval of the director. Approval shall not be granted unless and until the following conditions are met:

.. An out-of-state bank holding company desiring to make an acquisition referred to under subsection (2) of this section and the bank, national banking association, or domestic bank holding company parent thereof, if any, proposed to be acquired shall file an application in writing with the director. The director shall by rule establish the fee schedule to be collected from the applicant in connection with the application. The fee shall not exceed the cost of processing the application. The application shall contain such information as the director may prescribe by rule as necessary or appropriate for the purpose of making a determination under this section. The application and supporting information and all examination reports and information obtained by the director and the director's staff in conducting its investigation shall be confidential and privileged and not subject to public disclosure under chapter 42.56 RCW. The application and information may be disclosed to federal bank regulatory agencies and to officials empowered to investigate criminal charges, subject to legal process, valid search warrant, or subpoena. In any civil action in which such application or information is sought to be discovered or used as evidence, any party may, upon notice to the director and other parties, petition for an in camera review. The court may permit discovery and introduction of only those portions that are relevant and otherwise unobtainable by the requesting party. The application and information shall be discoverable in any judicial action challenging the approval of an acquisition by the director as arbitrary and capricious or unlawful.

.. The director shall find that:

... The bank or national banking association that is proposed to be acquired or the domestic bank holding company controlling such bank or national banking association is in such a liquidity or financial condition as to be in danger of closing, failing, or insolvency. In making any such determination the director shall be guided by the criteria developed by the federal regulatory agencies with respect to emergency acquisitions under the provisions of 12 U.S.C. Sec. 1828(c);

... There is no state bank or national banking association doing business in the state of Washington or domestic bank holding company with sufficient resources willing to acquire the entire bank or national banking association on at least as favorable terms as the out-of-state bank holding company is willing to acquire it;

... The applicant out-of-state bank holding company has provided all information and documents requested by the director in relation to the application; and

... The applicant out-of-state bank holding company has demonstrated an acceptable record of meeting the credit needs of its entire community, including low and moderate-income neighborhoods, consistent with the safe and sound operation of such institution.

.. The director shall consider:

... The financial institution structure of this state; and

... The convenience and needs of the public of this state.

. Nothing in this section may be construed to prohibit, limit, restrict, or subject to further regulation the ownership by a bank of the stock of a bank service corporation or a banker's bank.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20124[2014 c 37 § 124]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20252[2005 c 274 § 252]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2022[1994 c 92 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c420.pdf?cite=1987%20c%20420%20§%202[1987 c 420 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c310.pdf?cite=1985%20c%20310%20§%202[1985 c 310 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c305.pdf?cite=1985%20c%20305%20§%204[1985 c 305 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c157.pdf?cite=1983%20c%20157%20§%209[1983 c 157 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c196.pdf?cite=1982%20c%20196%20§%207[1982 c 196 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c89.pdf?cite=1981%20c%2089%20§%202[1981 c 89 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c92.pdf?cite=1973%201st%20ex.s.%20c%2092%20§%201[1973 1st ex.s. c 92 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c69.pdf?cite=1961%20c%2069%20§%201[1961 c 69 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.04.230[1955 c 33 § 30.04.230]; prior:  1933 c 42 § 10; RRS § 3243-1; ]

== 30A.04.232 - Additional authority of out-of-state holding company to acquire stock or assets of bank or national banking association.
. In addition to an acquisition pursuant to RCW 30A.04.230, an out-of-state bank holding company may acquire more than five percent of the voting stock or all or substantially all of the assets of a bank or national banking association, the principal operations of which are conducted within this state, if the bank or national banking association or its predecessor, the voting stock of which is to be acquired, shall have been conducting business for a period of not less than five years.

. The director, consistent with 12 U.S.C. Sec. 1842(d)(2)(D), may approve an acquisition if the standard on which the approval is based does not discriminate against out-of-state banks, out-of-state bank holding companies, or subsidiaries of those banks or holding companies.

. As used in this section, the terms "bank holding company," "domestic bank holding company," and "out-of-state bank holding company" shall have the meanings provided in RCW 30A.04.230.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20125[2014 c 37 § 125]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2125-S.SL.pdf?cite=1996%20c%202%20§%203[1996 c 2 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2023[1994 c 92 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c310.pdf?cite=1985%20c%20310%20§%201[1985 c 310 § 1]; ]

== 30A.04.238 - Purchase of own capital stock authorized.
. Notwithstanding any other provision of this title, a bank, with the prior approval of the director, may purchase shares of its own capital stock.

. When a bank purchases such shares, its capital accounts shall be reduced appropriately. The shares shall be held as authorized but unissued shares.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2024[1994 c 92 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2012[1986 c 279 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c305.pdf?cite=1985%20c%20305%20§%201[1985 c 305 § 1]; ]

== 30A.04.240 - Trust business to be kept separate—Authorized deposit of securities.
. A person authorized under this title or Title 30B RCW to engage in a trust business shall maintain in its office a trust department in which it shall keep books and accounts of its trust business, separate and apart from its other business. Such books and accounts shall specify the cash, securities and other properties, real and personal, held in each trust, and such securities and properties shall be at all times segregated from all other securities and properties except as otherwise provided in this section.

. Any person connected with a bank who shall, contrary to this section or any other provision of law, commingle any funds or securities of any kind held by such corporation in trust, for safekeeping or as agent for another, with the funds or assets of the corporation is guilty of a class B felony punishable according to chapter 9A.20 RCW.

. Notwithstanding any other provisions of law, any fiduciary holding securities in its fiduciary capacity or any state bank or national bank holding securities as fiduciary or as custodian for a fiduciary is authorized to deposit or arrange for the deposit of such securities: (a) In a clearing corporation (as defined in Article 8 of the Uniform Commercial Code, chapter 62A.8 RCW); (b) within another state bank, national bank, or trust company having trust power whether located inside or outside of this state; or (c) within itself. When such securities are so deposited, certificates representing securities of the same class of the same issuer may be merged and held in bulk in the name of the nominee of such clearing corporation or state bank, national bank, or trust company holding the securities as the depository, with any other such securities deposited in such clearing corporation or depository by any person, regardless of the ownership of such securities, and certificates of small denomination may be merged into one or more certificates of larger denomination. The records of such fiduciary and the records of such state bank, national bank, or trust company as a fiduciary or as custodian for a fiduciary shall at all times show the name of the party for whose account the securities are so deposited. Ownership of, and other interests in, such securities may be transferred by bookkeeping entries on the books of such clearing corporation, state bank, national bank, or trust company without physical delivery or alteration of certificates representing such securities. A state bank, national bank, or trust company so depositing securities pursuant to this section shall be subject to such rules and regulations as, in the case of state-chartered banks, the director and, in the case of national banking associations, the comptroller of the currency may from time to time issue. A state bank or national bank acting as custodian for a fiduciary shall, on demand by the fiduciary, certify in writing to the fiduciary the securities so deposited by such state bank or national bank in such clearing corporation or state bank, national bank, or trust company acting as such depository for the account of such fiduciary. A fiduciary shall, on demand by any party to a judicial proceeding for the settlement of such fiduciary's account or on demand by the attorney for such party, certify in writing to such party the securities deposited by such fiduciary in such clearing corporation or state bank, national bank, or trust company acting as such depository for its account as such fiduciary.

This subsection shall apply to any fiduciary holding securities in its fiduciary capacity, and to any state bank or national bank holding securities as a custodian, managing agent, or custodian for a fiduciary, acting on March 14, 1973 or who thereafter may act regardless of the date of the agreement, instrument, or court order by which it is appointed and regardless of whether or not such fiduciary, custodian, managing agent, or custodian for a fiduciary owns capital stock of such clearing corporation.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20126[2014 c 37 § 126]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1325-S.SL.pdf?cite=2013%20c%2076%20§%206[2013 c 76 § 6]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20184[2003 c 53 § 184]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2025[1994 c 92 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c45.pdf?cite=1979%20c%2045%20§%201[1979 c 45 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c99.pdf?cite=1973%20c%2099%20§%201[1973 c 99 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.04.240[1955 c 33 § 30.04.240]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c209.pdf?cite=1919%20c%20209%20§%2016[1919 c 209 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c80.pdf?cite=1917%20c%2080%20§%2049[1917 c 80 § 49]; RRS § 3256; ]

== 30A.04.260 - Legal services, advertising of—Penalty.
. No person, other than an attorney-at-law or law firm as permitted by other law, which advertises that it will furnish legal advice, construct or prepare wills, or do other legal work for its customers, shall be permitted to act as executor, administrator, or guardian; and such person whose officers or agents shall solicit legal business shall be ineligible for a period of one year thereafter to be appointed executor, administrator, or guardian in any of the courts of this state.

. Any person authorized under this title or Title 30B RCW to engage in a trust business, which advertises that it will furnish legal advice, construct or prepare wills, or do other legal work for its customers, and any officer, agent, or employee of such person who shall solicit legal business is guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20127[2014 c 37 § 127]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1325-S.SL.pdf?cite=2013%20c%2076%20§%207[2013 c 76 § 7]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20185[2003 c 53 § 185]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c117.pdf?cite=1974%20ex.s.%20c%20117%20§%2043[1974 ex.s. c 117 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.04.260[1955 c 33 § 30.04.260]; 1929 c 72 § 4, part; 1923 c 115 § 6, part; 1921 c 94 § 1, part; 1917 c 80 § 24, part; RRS § 3231, part; ]

== 30A.04.280 - Compliance enjoined—Banking, trust business, branches—Director's authority—Rules.
. [Empty]
.. No person shall engage in banking except in compliance with and subject to the provisions of this title, unless it is a national bank or except insofar as it may be authorized so to do by the laws of this state relating to savings banks or savings and loan associations.

.. A person shall not engage in a trust business except in compliance with and subject to the provisions of this title. This subsection (1)(b) does not apply to: (i) An individual, sole proprietor, general partnership, or joint venture composed of individuals; (ii) a person conducting business as an attorney-at-law or law firm; or (iii) a court-appointed guardian, conservator, trustee, or receiver.

.. A bank shall not engage in a trust business except as authorized under this title.

.. A bank or trust company shall not establish any branch except in accordance with the provisions of this title.

.. Except as authorized by federal law or by another law of this state, a nondepositary trust company incorporated under the laws of another state shall not be permitted to engage in a trust business in this state on more favorable terms and conditions than the terms and conditions on which trust companies incorporated under this chapter and savings banks engaged in trust business under RCW 32.08.140, 32.08.142, 32.08.210, and 32.08.215 are permitted to engage in trust business in such other state.

. Notwithstanding any other provision of this section, the director may by rule or order prohibit any person from engaging in a trust business in this state contrary to the requirements of this title if the conduct of the trust business in this state by such person harms or is likely to harm the general public, or if it adversely affects the business of trust companies operating in this state. The director may issue a temporary cease and desist order against such person in the manner provided for in *RCW 30.04.455 if the general public or trust companies are likely to be substantially injured by delay in issuing a cease and desist order. An order or rule made by the director pursuant to this subsection may require that any applicable person obtain a trust company charter under this title as a condition of continuing to engage in a trust business in this state, subject to meeting all qualifications for grant of a trust company charter under this title. This subsection does not apply to a person conducting business as an attorney-at-law or law firm or to a court-appointed guardian, conservator, trustee, or receiver.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1325-S.SL.pdf?cite=2013%20c%2076%20§%208[2013 c 76 § 8]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2560-S.SL.pdf?cite=1998%20c%2045%20§%201[1998 c 45 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2125-S.SL.pdf?cite=1996%20c%202%20§%204[1996 c 2 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.04.280[1955 c 33 § 30.04.280]; 1933 c 42 § 3, part; 1919 c 209 § 7, part; 1917 c 80 § 15, part; RRS § 3222, part; ]

== 30A.04.285 - Director's approval of a branch—Satisfactory financial condition—Affiliated commercial locations.
. The director's approval of a branch within the United States or any territory of the United States or in any foreign country shall be conditioned on a finding by the director that the bank has a satisfactory record of compliance with applicable laws and has a satisfactory financial condition. A bank chartered under this title may exercise any powers and authorities at any branch outside Washington that are permissible for a bank operating in that state where the branch is located, except to the extent those activities are expressly prohibited by the laws of this state or by any rule or order of the director applicable to the state bank. However, the director may waive any limitation in writing with respect to powers and authorities that the director determines do not threaten the safety or soundness of the state bank.

. An out-of-state bank may acquire, establish, or maintain a branch in Washington within one mile of an affiliate commercial location only to the same extent permitted for a Washington bank under applicable state and federal law. For purposes of this subsection, "bank" means any national bank, state bank, and district bank, as defined in 12 U.S.C. Sec. 1813(a); "out-of-state bank" means a bank whose home state is a state other than Washington; and "Washington bank" means a bank whose home state is Washington. "Home state" has the same meaning as defined in RCW 30A.38.005.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20128[2014 c 37 § 128]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2286-S.SL.pdf?cite=2007%20c%20167%20§%201[2007 c 167 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2125-S.SL.pdf?cite=1996%20c%202%20§%206[1996 c 2 § 6]; ]

== 30A.04.295 - Agency agreements—Written notice to director.
On or before the date on which a bank enters into any agency agreement authorizing another entity, as agent of the bank, to receive deposits or renew time deposits, the bank shall give written notice to the director of the existence of that agency arrangement. The notice is not effective until it has been delivered to the office of the director.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2125-S.SL.pdf?cite=1996%20c%202%20§%207[1996 c 2 § 7]; ]

== 30A.04.300 - Foreign branch banks.
A branch of any foreign bank or banker actually and publicly engaged in banking in this state on March 10, 1917, in full compliance with the laws hereof, which were in force immediately prior to March 10, 1917, and which branch has a capital not less in amount than that required for the organization of a state bank as provided in this title at the time and place when and where such branch was established, may continue its said business, subject to all of the regulations and supervision provided for banks. The amount upon which it pays taxes shall be prima facie evidence of the amount and existence of such capital. No such bank or banker shall set forth on its or his or her stationery or in any manner advertise in this state a greater capital, surplus and undivided profits than are actually maintained at such branch. Every foreign corporation, bank and banker, and every officer, agent, and employee thereof who violates any provision of this section or which violates the terms of the resolution filed as required by *RCW 30.04.290 shall for each violation forfeit and pay to the state of Washington the sum of one thousand dollars. A civil action for the recovery of any such sum may be brought by the attorney general in the name of the state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20745[2011 c 336 § 745]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.04.300[1955 c 33 § 30.04.300]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c80.pdf?cite=1917%20c%2080%20§%2041[1917 c 80 § 41]; RRS § 3248; ]

== 30A.04.330 - Saturday closing authorized.
Any bank, which term for the purpose of this section shall include but not be limited to any state bank, national bank or association, mutual savings bank, savings and loan association, federal reserve bank, federal home loan bank, and federal savings and loan association, federal credit union, and state credit union doing business in this state, may remain closed on Saturdays and any Saturday on which a bank remains closed shall be, with respect to such bank, a holiday and not a business day. Any act, authorized, required or permitted to be performed at or by or with respect to any bank, as herein defined, on a Saturday, may be performed on the next succeeding business day, and no liability or loss of rights of any kind shall result from such closing.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20129[2014 c 37 § 129]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.04.330[1955 c 33 § 30.04.330]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c221.pdf?cite=1947%20c%20221%20§%201[1947 c 221 § 1]; Rem. Supp. 1947 § 3292a; ]

== 30A.04.375 - Investment in stock, participation certificates, and other evidences of participation.
Any bank may invest in the stock or participation certificates of production credit associations, federal intermediate credit banks and the stock or other evidences of participation of federal land banks in amounts consistent with safe and sound practice in conducting the business of the bank.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20130[2014 c 37 § 130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c86.pdf?cite=1982%20c%2086%20§%201[1982 c 86 § 1]; ]

== 30A.04.380 - Investment in paid-in capital stock and surplus of banks or corporations engaged in international or foreign banking.
Any bank may invest an amount not exceeding ten per centum of its paid-in capital stock and surplus in the stock of one or more banks or corporations chartered under the laws of the United States, or of any state thereof, and principally engaged in international or foreign banking, or banking in a dependency or insular possession of the United States, either directly or through the agency, ownership or control of local institutions in foreign countries, or in such dependencies or insular possessions.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20131[2014 c 37 § 131]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2013[1986 c 279 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c104.pdf?cite=1973%201st%20ex.s.%20c%20104%20§%209[1973 1st ex.s. c 104 § 9]; ]

== 30A.04.390 - Acquisition of stock of banks organized under laws of foreign country, etc.
Any bank may acquire and hold, directly or indirectly, stock or other evidence of indebtedness or ownership in one or more banks organized under the law of a foreign country or a dependency or insular possession of the United States.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20132[2014 c 37 § 132]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2014[1986 c 279 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c104.pdf?cite=1973%201st%20ex.s.%20c%20104%20§%2010[1973 1st ex.s. c 104 § 10]; ]

== 30A.04.395 - Continuing authority for investments.
Any investment by a bank other than a loan, if legal and authorized when made, may continue to be held by the bank notwithstanding a change in circumstances or change in the law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2016[1986 c 279 § 16]; ]

== 30A.04.400 - Bank acquisition or control—Definitions.
As used in RCW 30A.04.400 through 30A.04.410, the following words shall have the following meanings:

. "Control" means directly or indirectly alone or in concert with others to own, control, or hold the power to vote twenty-five percent or more of the outstanding stock or voting power of the "controlled" entity;

. "Acquiring party" means the person acquiring control of a bank through the purchase of stock; and

. "Person" means any individual, corporation, partnership, association, business trust, or other organization.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20133[2014 c 37 § 133]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c246.pdf?cite=1977%20ex.s.%20c%20246%20§%201[1977 ex.s. c 246 § 1]; ]

== 30A.04.405 - Bank acquisition or control—Notice or application—Registration statement—Violations—Penalties.
. It is unlawful for any person to acquire control of a bank until thirty days after filing with the director a copy of the notice of change of control required to be filed with the federal deposit insurance corporation or a completed application. The notice or application shall be under oath and contain substantially all of the following information plus any additional information that the director may prescribe as necessary or appropriate in the particular instance for the protection of bank depositors, borrowers, or shareholders and the public interest:

.. The identity, banking and business experience of each person by whom or on whose behalf acquisition is to be made;

.. The financial and managerial resources and future prospects of each person involved in the acquisition;

.. The terms and conditions of any proposed acquisition and the manner in which the acquisition is to be made;

.. The source and amount of the funds or other consideration used or to be used in making the acquisition, and a description of the transaction and the names of the parties if any part of these funds or other consideration has been or is to be borrowed or otherwise obtained for the purpose of making the acquisition;

.. Any plan or proposal which any person making the acquisition may have to liquidate the bank, to sell its assets, to merge it with any other bank, or to make any other major change in its business or corporate structure for management;

.. The identification of any person employed, retained, or to be compensated by the acquiring party, or by any person on its behalf, who makes solicitations or recommendations to shareholders for the purpose of assisting in the acquisition and a brief description of the terms of the employment, retainer, or arrangement for compensation; and

.. Copies of all invitations for tenders or advertisements making a tender offer to shareholders for the purchase of their stock to be used in connection with the proposed acquisition.

. Notwithstanding any other provision of this section, a bank or domestic bank holding company as defined in RCW 30A.04.230 need only notify the director of an intent to acquire control and the date of the proposed acquisition of control at least thirty days before the date of the acquisition of control.

. When a person, other than an individual or corporation, is required to file an application under this section, the director may require that the information required by subsection (1)(a), (b), and (f) of this section be given with respect to each person, as defined in RCW 30A.04.400(3), who has an interest in or controls a person filing an application under this subsection.

. When a corporation is required to file an application under this section, the director may require that information required by subsection (1)(a), (b), and (f) of this section be given for the corporation, each officer and director of the corporation, and each person who is directly or indirectly the beneficial owner of twenty-five percent or more of the outstanding voting securities of the corporation.

. If any tender offer, request, or invitation for tenders or other agreements to acquire control is proposed to be made by means of a registration statement under the Securities Act of 1933 (48 Stat. 74, 15 U.S.C., Sec. 77(a)), as amended, or in circumstances requiring the disclosure of similar information under the Securities Exchange Act of 1934 (48 Stat. 881, 15 U.S.C., Sec. 78(a)), as amended, the registration statement or application may be filed with the director in lieu of the requirements of this section.

. Any acquiring party shall also deliver a copy of any notice or application required by this section to the bank proposed to be acquired within two days after the notice or application is filed with the director.

. Any acquisition of control in violation of this section shall be ineffective and void.

. Any person who willfully or intentionally violates this section or any rule adopted pursuant thereto is guilty of a gross misdemeanor pursuant to chapter 9A.20 RCW. Each day's violation shall be considered a separate violation, and any person shall upon conviction be fined not more than one thousand dollars for each day the violation continues.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20134[2014 c 37 § 134]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2029[1994 c 92 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2015[1986 c 279 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c305.pdf?cite=1985%20c%20305%20§%205[1985 c 305 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c246.pdf?cite=1977%20ex.s.%20c%20246%20§%202[1977 ex.s. c 246 § 2]; ]

== 30A.04.410 - Bank acquisition or control—Disapproval by director—Change of officers.
. The director may disapprove the acquisition of a bank within thirty days after the filing of a complete application pursuant to RCW 30A.04.405 or an extended period not exceeding an additional fifteen days if:

.. The poor financial condition of any acquiring party might jeopardize the financial stability of the bank or might prejudice the interests of the bank depositors, borrowers, or shareholders;

.. The plan or proposal of the acquiring party to liquidate the bank, to sell its assets, to merge it with any person, or to make any other major change in its business or corporate structure or management is not fair and reasonable to the bank's depositors, borrowers, or stockholders or is not in the public interest;

.. The banking and business experience and integrity of any acquiring party who would control the operation of the bank indicates that approval would not be in the interest of the bank's depositors, borrowers, or shareholders;

.. The information provided by the application is insufficient for the director to make a determination or there has been insufficient time to verify the information provided and conduct an examination of the qualification of the acquiring party; or

.. The acquisition would not be in the public interest.

. An acquisition may be made prior to expiration of the disapproval period if the director issues written notice of intent not to disapprove the action.

. The director shall set forth the basis for disapproval of any proposed acquisition in writing and shall provide a copy of such findings and order to the applicants and to the bank involved. Such findings and order shall not be disclosed to any other party and shall not be subject to public disclosure under chapter 42.56 RCW unless the findings and/or order are appealed pursuant to chapter 34.05 RCW.

. Whenever such a change in control occurs, each party to the transaction shall report promptly to the director any changes or replacement of its chief executive officer, or of any director, that occurs in the next twelve-month period, including in its report a statement of the past and present business and professional affiliations of the new chief executive officer or directors.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20135[2014 c 37 § 135]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20253[2005 c 274 § 253]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2030[1994 c 92 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c180.pdf?cite=1989%20c%20180%20§%203[1989 c 180 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c246.pdf?cite=1977%20ex.s.%20c%20246%20§%203[1977 ex.s. c 246 § 3]; ]

== 30A.04.450 - Notice of charges—Reasons for issuance—Contents—Hearing—Cease and desist order.
. The director may issue and serve a notice of charges upon a bank when in the opinion of the director:

.. It has engaged in an unsafe and unsound practice related to the conduct of business of the bank;

.. It has violated any provision of RCW 30A.04.050; or

.. It is planning, attempting, or currently conducting any act prohibited in (a) or (b) of this subsection.

. The director may issue and serve a notice of charges upon a holding company when, in the opinion of the director:

.. The holding company has committed a violation of RCW 30A.04.050(2);

.. The conduct of the holding company has resulted in an unsafe and unsound practice at the bank or a violation of any provision of RCW 30A.04.050 by the bank; or

.. The holding company is planning, attempting, or currently conducting any act prohibited in (a) or (b) of this subsection.

. The notice shall contain a statement of the facts constituting the alleged violation or violations or the practice or practices and shall fix a time and place at which a hearing will be held to determine whether an order to cease and desist should issue against the bank or holding company. The hearing shall be set not earlier than ten days or later than thirty days after service of the notice unless a later date is set by the director at the request of the bank or holding company.

. Unless the bank or holding company shall appear at the hearing by a duly authorized representative it shall be deemed to have consented to the issuance of the cease and desist order. In the event of this consent or if upon the record made at the hearing the director finds that any violation or practice specified in the notice of charges has been established, the director may issue and serve upon the bank or holding company an order to cease and desist from the violation or practice. The order may require the bank or holding company, and its directors, officers, employees, and agents to cease and desist from the violation or practice and may require the bank or holding company to take affirmative action to correct the conditions resulting from the violation or practice.

. A cease and desist order shall become effective at the expiration of ten days after the service of the order upon the bank concerned except that a cease and desist order issued upon consent shall become effective at the time specified in the order and shall remain effective as provided therein unless it is stayed, modified, terminated, or set aside by action of the director or a reviewing court.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20136[2014 c 37 § 136]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2831.SL.pdf?cite=2010%20c%2088%20§%2015[2010 c 88 § 15]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2031[1994 c 92 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c178.pdf?cite=1977%20ex.s.%20c%20178%20§%201[1977 ex.s. c 178 § 1]; ]

== 30A.04.455 - Temporary cease and desist order—Reasons for issuance.
. The director may also issue a temporary order requiring a bank or its holding company, or both, to cease and desist from any action or omission, as specified in RCW 30A.04.450, or its continuation, which the director has determined:

.. Constitutes an unsafe and unsound practice or a material violation of RCW 30A.04.050 affecting the bank;

.. Has resulted in the bank being less than adequately capitalized; or

.. Is likely to cause insolvency or substantial dissipation of assets or earnings of the bank or to otherwise seriously prejudice the interests of its depositors or trust beneficiaries.

. The order is effective upon service on the bank or holding company, and remains in effect unless set aside, limited, or suspended by the superior court in proceedings under RCW 30A.04.460 pending the completion of the administrative proceedings under the notice and until such time as the director dismisses the charges specified in the notice or until the effective date of a cease and desist order issued against the bank or holding company under RCW 30A.04.450.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20137[2014 c 37 § 137]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2831.SL.pdf?cite=2010%20c%2088%20§%2016[2010 c 88 § 16]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2032[1994 c 92 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c178.pdf?cite=1977%20ex.s.%20c%20178%20§%202[1977 ex.s. c 178 § 2]; ]

== 30A.04.460 - Temporary cease and desist order—Injunction to set aside, limit, or suspend temporary order.
. Within ten days after a bank or holding company has been served with a temporary cease and desist order, the bank or holding company may apply to the superior court in the county of its principal place of business for an injunction setting aside, limiting, or suspending the order pending the completion of the administrative proceedings pursuant to the notice served under RCW 30A.04.455.

. The superior court shall have jurisdiction to issue the injunction.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20138[2014 c 37 § 138]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2831.SL.pdf?cite=2010%20c%2088%20§%2017[2010 c 88 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c178.pdf?cite=1977%20ex.s.%20c%20178%20§%203[1977 ex.s. c 178 § 3]; ]

== 30A.04.465 - Violations or unsafe or unsound practices—Injunction to enforce temporary order.
In the case of a violation or threatened violation of a temporary cease and desist order issued under RCW 30A.04.455, the director may apply to the superior court of the county of the principal place of business of the bank for an injunction to enforce the order, and the court shall issue an injunction if it determines that there has been a violation or threatened violation.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20139[2014 c 37 § 139]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2033[1994 c 92 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c178.pdf?cite=1977%20ex.s.%20c%20178%20§%204[1977 ex.s. c 178 § 4]; ]

== 30A.04.470 - Order to refrain from violations or practices—Administrative hearing or judicial review.
. Any administrative hearing provided in RCW 30A.04.450 or 30A.12.042 must be conducted in accordance with chapter 34.05 RCW and held at the place designated by the director, and may be conducted by the department. The hearing shall be private unless the director determines that a public hearing is necessary to protect the public interest after fully considering the views of the party afforded the hearing.

. Within sixty days after the hearing, the director shall render a decision which shall include findings of fact upon which the decision is based and shall issue and serve upon each party to the proceeding an order or orders consistent with RCW 30A.04.450 or 30A.12.042, as the case may be.

. Unless a petition for review is timely filed in the superior court of the county of the principal place of business of the affected bank under subsection (5) of this section and until the record in the proceeding has been filed as therein provided, the director may at any time modify, terminate, or set aside any order upon such notice and in such manner as he or she shall deem proper. Upon filing the record, the director may modify, terminate, or set aside any order only with permission of the court.

. The judicial review provided in this section is exclusive for orders issued under RCW 30A.04.450 and 30A.12.042.

. Any party to the proceeding or any person required by an order issued under RCW 30A.04.450, 30A.04.455, 30A.04.465, or 30A.12.042 to refrain from any of the violations or practices stated therein may obtain a review of any order served under subsection (1) of this section other than one issued upon consent by filing in the superior court of the county of the principal place of business of the affected bank within ten days after the date of service of the order a written petition praying that the order of the director be modified, terminated, or set aside. A copy of the petition shall be immediately served upon the director and the director shall then file in the court the record of the proceeding. The court shall have jurisdiction upon the filing of the petition, which jurisdiction shall become exclusive upon the filing of the record to affirm, modify, terminate, or set aside in whole or in part the order of the director except that the director may modify, terminate, or set aside an order with the permission of the court. The judgment and decree of the court shall be final, except that it shall be subject to appellate review under the rules of court.

. The commencement of proceedings for judicial review under subsection (5) of this section shall not operate as a stay of any order issued by the director unless specifically ordered by the court.

. Service of any notice or order required to be served under RCW 30A.04.450, 30A.04.455, 30A.12.040, or 30A.12.042 shall be accomplished in the same manner as required for the service of process in civil actions in superior courts of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20140[2014 c 37 § 140]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2831.SL.pdf?cite=2010%20c%2088%20§%2018[2010 c 88 § 18]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2034[1994 c 92 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c178.pdf?cite=1977%20ex.s.%20c%20178%20§%208[1977 ex.s. c 178 § 8]; ]

== 30A.04.475 - Order to refrain from violations or practices—Jurisdiction of courts in enforcement or issuance of orders, injunctions, or judicial review.
. The director may apply to the superior court of the county of the principal place of business of the bank affected for the enforcement of any effective and outstanding order issued under RCW 30A.04.450, 30A.04.455, 30A.04.465, or 30A.12.042, and the court shall have jurisdiction to order compliance therewith.

. No court shall have jurisdiction to affect by injunction or otherwise the issuance or enforcement of any order or to review, modify, suspend, terminate, or set aside any order except as provided in RCW 30A.04.460, 30A.04.465, and 30A.04.470.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20141[2014 c 37 § 141]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2831.SL.pdf?cite=2010%20c%2088%20§%2019[2010 c 88 § 19]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2035[1994 c 92 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c178.pdf?cite=1977%20ex.s.%20c%20178%20§%209[1977 ex.s. c 178 § 9]; ]

== 30A.04.500 - Fairness in lending act—Short title.
RCW 30A.04.505 through 30A.04.515 shall be known and may be cited as the "fairness in lending act".

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20142[2014 c 37 § 142]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c301.pdf?cite=1977%20ex.s.%20c%20301%20§%2010[1977 ex.s. c 301 § 10]; ]

== 30A.04.505 - Fairness in lending act—Definitions.
As used in RCW 30A.04.505 through 30A.04.515:

. "Financial institution" means any bank, savings bank, credit union, mortgage company, or savings and loan association which operates or has a place of business in this state whether regulated by the state or federal government.

. "Particular type of loan" refers to a class of loans which is substantially similar with respect to the following:

.. FHA, VA, or conventional loans;

.. Uniform or nonuniform payment;

.. Uniform or nonuniform rate of interest;

.. Purpose; and

.. The location of the real estate offered as security for the loan as being inside or outside of that financial institution's lending area.

. "Varying the terms of a loan" includes, but is not limited to the following practices:

.. Requiring a greater down payment than is usual for the particular type of a loan involved;

.. Requiring a shorter period of amortization than is usual for the particular type of loan involved;

.. Charging a higher interest rate than is usual for the particular type of loan involved;

.. A deliberate underappraisal of the value of the property offered as security.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20143[2014 c 37 § 143]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c301.pdf?cite=1977%20ex.s.%20c%20301%20§%2011[1977 ex.s. c 301 § 11]; ]

== 30A.04.510 - Fairness in lending act—Unlawful practices.
Subject to RCW 30A.04.515, it shall be unlawful for any financial institution, in processing any application for a loan to be secured by a single-family residence to:

. Deny or vary the terms of a loan on the basis that a specific parcel of real estate offered as security is located in a specific geographical area, unless building, remodeling, or continued habitation in such specific geographical area is prohibited or restricted by any local, state, or federal law or rules or regulations promulgated thereunder.

. Utilize lending standards that have no economic basis.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20144[2014 c 37 § 144]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c301.pdf?cite=1977%20ex.s.%20c%20301%20§%2012[1977 ex.s. c 301 § 12]; ]

== 30A.04.515 - Fairness in lending act—Sound underwriting practices not precluded.
Nothing contained in RCW 30A.04.505 through [and] 30A.04.510 shall preclude a financial institution from considering sound underwriting practices in processing any application for a loan to any person. Such practices shall include the following:

. The willingness and the financial ability of the borrower to repay the loan.

. The market value of any real estate and of any other item of property proposed as security for any loan.

. Diversification of the financial institution's investment portfolio.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20145[2014 c 37 § 145]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c301.pdf?cite=1977%20ex.s.%20c%20301%20§%2013[1977 ex.s. c 301 § 13]; ]

== 30A.04.550 - Reorganization as subsidiary of bank holding company—Authority.
A state banking corporation may, with the approval of the director and the affirmative vote of the shareholders of such corporation owning at least two-thirds of each class of shares entitled to vote under the terms of such shares, be reorganized to become a subsidiary of a bank holding company or a company that will, upon consummation of such reorganization, become a bank holding company, as defined in the federal bank holding company act of 1956, as amended.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2036[1994 c 92 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2040[1986 c 279 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c196.pdf?cite=1982%20c%20196%20§%201[1982 c 196 § 1]; ]

== 30A.04.555 - Reorganization as subsidiary of bank holding company—Procedure.
A reorganization authorized under RCW 30A.04.550 shall be carried out in the following manner:

. A plan of reorganization specifying the manner in which the reorganization shall be carried out must be approved by a majority of the entire board of directors of the banking corporation. The plan shall specify the name of the acquiring corporation, the amount of cash, securities of the bank holding company, other consideration, or any combination thereof to be paid to the shareholders of the reorganizing corporation in exchange for their shares of the stock of the corporation. The plan shall also specify the exchange date or the manner in which such exchange date shall be determined, the manner in which the exchange shall be carried out, and such other matters, not inconsistent with this chapter, as shall be determined by the board of directors of the corporation.

. The plan of reorganization shall be submitted to the shareholders of the reorganizing corporation at a meeting to be held on the call of the directors. Notice of the meeting of shareholders at which the plan shall be considered shall be given by prepaid first-class mail at least twenty days before the date of the meeting, to each stockholder of record of the banking corporation. The notice shall state that dissenting shareholders will be entitled to payment of the value of only those shares which are voted against approval of the plan.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20146[2014 c 37 § 146]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6285.SL.pdf?cite=1994%20c%20256%20§%2038[1994 c 256 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2041[1986 c 279 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c196.pdf?cite=1982%20c%20196%20§%202[1982 c 196 § 2]; ]

== 30A.04.560 - Reorganization as subsidiary of bank holding company—Dissenter's rights—Conditions.
If the shareholders approve the reorganization by a two-thirds vote of each class of shares entitled to vote under the terms of such shares, and if it is thereafter approved by the director and consummated, any shareholder of the banking corporation who has voted shares against such reorganization at such meeting or has given notice in writing at or prior to such meeting to the banking corporation that he or she dissents from the plan of reorganization and has not voted in favor of the reorganization, shall be entitled to receive the value of the shares determined as provided in RCW 30A.04.565. Such dissenter's rights must be exercised by making written demand which shall be delivered to the corporation at any time within thirty days after the date of shareholder approval, accompanied by the surrender of the appropriate stock certificates.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20147[2014 c 37 § 147]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2037[1994 c 92 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2042[1986 c 279 § 42]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c196.pdf?cite=1982%20c%20196%20§%203[1982 c 196 § 3]; ]

== 30A.04.565 - Reorganization as subsidiary of bank holding company—Valuation of shares of dissenting shareholders.
The value of the shares of a dissenting shareholder who has properly perfected dissenter's rights shall be ascertained as of the day prior to the date of the shareholder action approving such reorganization by three appraisers, one to be selected by the owners of two-thirds of the dissenting shares, one by the board of directors of the acquiring bank holding company, and the third by the two so chosen. The valuation agreed upon by any two appraisers shall govern. The dissenting shareholders shall bear, on a pro rata basis based on the number of dissenting shares owned, the cost of their appraisal and one-half of the cost of the third appraisal, and the acquiring bank holding company shall bear the cost of its appraisal and one-half of the cost of the third appraisal. If the appraisal is not completed within ninety days after the effective date of the reorganization, the director shall cause an appraisal to be made which shall be final and binding upon all parties. The cost of such appraisal shall be borne equally by the dissenting shareholders and the acquiring bank holding company. The dissenting shareholders shall share their half of the cost on a pro rata basis based on the number of dissenting shares owned.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6285.SL.pdf?cite=1994%20c%20256%20§%2039[1994 c 256 § 39]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2038[1994 c 92 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c196.pdf?cite=1982%20c%20196%20§%204[1982 c 196 § 4]; ]

== 30A.04.570 - Reorganization as subsidiary of bank holding company—Approval of director—Certificate of reorganization—Exchange of shares.
The reorganization and exchange authorized by RCW 30A.04.550 through 30A.04.570 shall become effective as follows:

. If the board of directors and shareholders of the state banking corporation and the board of directors of the acquiring corporation approve the plan of reorganization, then both corporations shall apply for the approval of the director, providing such information as the director by rule may prescribe.

. If the director approves the reorganization, the director shall issue a certificate of reorganization to the state banking corporation.

. Upon the issuance of a certificate of reorganization by the director, or on such later date as shall be provided for in the plan of reorganization, the shares of the state banking corporation shall be deemed to be exchanged in accordance with the plan of reorganization, subject to the rights of dissenters under RCW 30A.04.560 and 30A.04.565.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20148[2014 c 37 § 148]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2039[1994 c 92 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c196.pdf?cite=1982%20c%20196%20§%205[1982 c 196 § 5]; ]

== 30A.04.575 - Public hearing prior to approval of reorganization—Request.
Prior to the approval of the reorganization, the director, upon request of the board of directors of the bank, or not less than ten percent of its shareholders, shall hold a public hearing at which bank shareholders and other interested parties may appear. Notice of the public hearing shall be sent to each shareholder by prepaid first-class mail.

The approval of the reorganization by the director shall be conditioned on a finding that the terms of the reorganization are fair to the shareholders and other interested parties.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6285.SL.pdf?cite=1994%20c%20256%20§%2040[1994 c 256 § 40]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2040[1994 c 92 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2044[1986 c 279 § 44]; ]

== 30A.04.600 - Shareholders—Actions authorized without meetings—Written consent.
Any action required by this title to be taken at a meeting of the shareholders of a corporation, or any action that may be taken at a meeting of the shareholders, may be taken without a meeting if a consent in writing, setting forth the action so taken, is signed by all of the shareholders entitled to vote with respect to the subject matter thereof.

The consent shall have the same force and effect as a unanimous vote of shareholders and may be stated as such in any articles or documents filed under this title.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2046[1986 c 279 § 46]; ]

== 30A.04.605 - Directors, committees—Actions authorized without meetings—Written consent.
Unless otherwise provided by the articles of incorporation or bylaws, any action required by this title to be taken at a meeting of the directors of a bank or trust company, or any action which may be taken at any meeting of the directors or of a committee, may be taken without a meeting if a consent in writing, setting forth the action so taken, shall be signed by all of the directors, or all of the members of the committee, as the case may be. Such consent shall have the same effect as a unanimous vote.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2047[1986 c 279 § 47]; ]

== 30A.04.610 - Directors, committees—Meetings authorized by conference telephone or similar communications equipment.
Except as may be otherwise restricted by the articles of incorporation or bylaws, members of the board of directors or any committee designated by the board of directors may participate in a meeting of the board or committee by means of a conference telephone or similar communications equipment by means of which all persons participating in the meeting can hear each other at the same time. Participation by such means shall constitute presence, in person, at a meeting.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2048[1986 c 279 § 48]; ]

== 30A.04.650 - Automated teller machines and night depositories security.
Chapter 19.174 RCW applies to automated teller machines and night depositories regulated under this title.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1849-S.SL.pdf?cite=1993%20c%20324%20§%2010[1993 c 324 § 10]; ]

== 30A.04.902 - Effective date—2014 c 37.
This act takes effect January 5, 2015. The director of financial institutions may immediately take such steps as are necessary to ensure that this act is implemented on its effective date.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%205[2014 c 37 § 5]; ]

