= 30A.08 - Organization and powers.
:toc:

== 30A.08.010 - Incorporators—Paid-in capital stock, surplus, and undivided profits—Requirements.
When authorized by the director, as hereinafter provided, one or more natural persons, citizens of the United States, may incorporate a bank in the manner herein prescribed. No bank shall incorporate for less amount nor commence business unless it has a paid-in capital stock, surplus and undivided profits in the amount as may be determined by the director after consideration of the proposed location, management, and the population and economic characteristics for the area, the nature of the proposed activities and operation of the bank, and other factors deemed pertinent by the director. Each bank shall before commencing business have subscribed and paid into it in the same manner as is required for capital stock, an amount equal to at least ten percent of the capital stock above required, that shall be carried in the undivided profit account and may be used to defray organization and operating expenses of the company. Any sum not so used shall be transferred to the surplus fund of the company before any dividend shall be declared to the stockholders.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20150[2014 c 37 § 150]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6285.SL.pdf?cite=1994%20c%20256%20§%2041[1994 c 256 § 41]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2042[1994 c 92 § 42]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2017[1986 c 279 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c104.pdf?cite=1973%201st%20ex.s.%20c%20104%20§%203[1973 1st ex.s. c 104 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c136.pdf?cite=1969%20c%20136%20§%203[1969 c 136 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.08.010[1955 c 33 § 30.08.010]; prior:  1947 c 131 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c72.pdf?cite=1929%20c%2072%20§%204[1929 c 72 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c115.pdf?cite=1923%20c%20115%20§%202[1923 c 115 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c80.pdf?cite=1917%20c%2080%20§%2019[1917 c 80 § 19]; Rem. Supp. 1947 § 3226; ]

== 30A.08.020 - Notice of intention to organize—Proposed articles of incorporation—Contents.
Persons desiring to incorporate a bank shall file with the director a notice of their intention to organize a bank in such form and containing such information as the director shall prescribe by rule, together with proposed articles of incorporation, which shall be submitted for examination to the director at his or her office.

The proposed articles of incorporation shall state:

. The name of such bank.

. The city, village or locality and county where the head office of such corporation is to be located.

. The nature of its business.

. The amount of its capital stock, which shall be divided into shares of a par or no par value as may be provided in the articles of incorporation.

. The names and places of residence and mailing addresses of the persons who as directors are to manage the corporation until the first annual meeting of its stockholders.

. If there is to be preferred or special classes of stock, a statement of preferences, voting rights, if any, limitations and relative rights in respect of the shares of each class; or a statement that the shares of each class shall have the attributes as shall be determined by the bank's board of directors from time to time with the approval of the director.

. Any provision granting the shareholders the preemptive right to acquire additional shares of the bank and any provision granting shareholders the right to cumulate their votes.

. Any provision, not inconsistent with law, which the incorporators elect to set forth in the articles of incorporation for the regulation of the affairs of the corporation, including any provision restricting the transfer of shares, any provision which under this title is required or permitted to be set forth in the bylaws, and any provision permitted by RCW 23B.17.030.

. Any provision the incorporators elect to so set forth, not inconsistent with law or the purposes for which the bank is organized, or any provision limiting any of the powers granted in this title.

It shall not be necessary to set forth in the articles of incorporation any of the corporate powers granted in this title. The articles of incorporation shall be signed by all of the incorporators.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20151[2014 c 37 § 151]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5058-S.SL.pdf?cite=1999%20c%2014%20§%2011[1999 c 14 § 11]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1015.SL.pdf?cite=1995%20c%20134%20§%203[1995 c 134 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6285.SL.pdf?cite=1994%20c%20256%20§%2042[1994 c 256 § 42]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2043[1994 c 92 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2018[1986 c 279 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c73.pdf?cite=1981%20c%2073%20§%201[1981 c 73 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c104.pdf?cite=1973%201st%20ex.s.%20c%20104%20§%204[1973 1st ex.s. c 104 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c118.pdf?cite=1959%20c%20118%20§%201[1959 c 118 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c248.pdf?cite=1957%20c%20248%20§%201[1957 c 248 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.08.020[1955 c 33 § 30.08.020]; prior:   1923 c 115 § 3; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c80.pdf?cite=1917%20c%2080%20§%2020[1917 c 80 § 20]; RRS § 3227.   1929 c 174 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c115.pdf?cite=1923%20c%20115%20§%204[1923 c 115 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c80.pdf?cite=1917%20c%2080%20§%2021[1917 c 80 § 21]; RRS § 3228; ]

== 30A.08.025 - Limited liability company—Organization or conversion—Approval of director—Conditions—Application of chapter  25.15 RCW—Definitions.
. Notwithstanding any other provision of this title, if the conditions of this section are met, a bank or a holding company of a bank may be organized as, or convert to, a limited liability company under the Washington limited liability company act, chapter 25.15 RCW. As used in this section, "bank" includes an applicant to become a bank or holding company of a bank and "holding company" means a holding company of a bank.

. [Empty]
.. Before a bank or holding company may organize as, or convert to, a limited liability company, the bank or holding company must obtain approval of the director.

.. [Empty]
... To obtain approval under this section from the director, the bank or holding company must file a request for approval with the director at least ninety days before the day on which the bank or holding company becomes a limited liability company.

... If the director does not disapprove the request for approval within ninety days from the day on which the director receives the request, the request is considered approved.

... When taking action on a request for approval filed under this section, the director may:

(A) Approve the request;

(B) Approve the request subject to terms and conditions the director considers necessary; or

(C) Disapprove the request.

. To approve a request for approval, the director must find that the bank or holding company:

.. Will operate in a safe and sound manner; and

.. Has the following characteristics:

... The certificate of formation and limited liability company require or set forth that the duration of the limited liability company is perpetual;

... The bank or holding company is not otherwise subject to automatic termination, dissolution, or suspension upon the happening of some event other than the passage of time;

... The exclusive authority to manage the bank, trust company, or holding company is vested in a board of managers or directors that:

(A) Is elected or appointed by the owners;

(B) Is not required to have owners of the bank, trust company, or holding company included on the board;

(C) Possesses adequate independence and authority to supervise the operation of the bank, trust company, or holding company; and

(D) Operates with substantially the same rights, powers, privileges, duties, and responsibilities as the board of directors of a corporation;

... Neither state law, nor the bank's or holding company's operating agreement, bylaws, or other organizational documents provide that an owner of the bank or holding company is liable for the debts, liabilities, and obligations of the bank or holding company in excess of the amount of the owner's investment;

.. Neither state law, nor the bank's or holding company's operating agreement, bylaws, or other organizational documents require the consent of any other owner of the bank or holding company in order for any owner to transfer an ownership interest in the bank or holding company, including voting rights;

.. The bank or holding company is able to obtain new investment funding if needed to maintain adequate capital;

.. The bank or holding company is able to comply with all legal and regulatory requirements for a federally insured depository bank or holding company of a federally insured depository bank, under applicable federal and state law; and

.. A bank or holding company that is organized as a limited liability company shall maintain the characteristics listed in this subsection (3)(b) during such time as it is authorized to conduct business under this title as a limited liability company.

. [Empty]
.. All rights, privileges, powers, duties, and obligations of a bank or holding company, that is organized as a limited liability company, and its members and managers are governed by the Washington limited liability company act, chapter 25.15 RCW, except:

... To the extent chapter 25.15 RCW is in conflict with federal law or regulation respecting the organization of a federally insured depository institution as a limited liability company, such federal law or regulation supersedes the conflicting provisions contained in chapter 25.15 RCW in relation to a bank or holding company organized as a limited liability company pursuant to this section; and

... Without limitation, the following are inapplicable to a bank or holding company organized as a limited liability company:

(A) Permitting automatic dissolution or suspension of a limited liability company as set forth in RCW 25.15.265(1), pursuant to a statement of limited duration which, though impermissible under subsection (3)(b)(i) of this section, has been provided for in a certificate of formation;

(B) Permitting automatic dissolution or suspension of a limited liability company, pursuant to the limited liability company agreement, as set forth in RCW 25.15.265(2);

(C) Permitting dissolution of the limited liability company agreement based upon agreement of all the members, as set forth in RCW 25.15.265(3);

(D) Permitting dissociation of all the members of the limited liability company, as set forth in RCW 25.15.265(4); and

(E) Permitting automatic dissolution or suspension of a limited liability company, pursuant to operation of law, as otherwise set forth in chapter 25.15 RCW.

.. Notwithstanding (a) of this subsection:

... For purposes of transferring a member's interests in the bank or holding company, a member's interest in the bank or holding company is treated like a share of stock in a corporation; and

... If a member's interest in the bank or holding company is transferred voluntarily or involuntarily to another person, the person who receives the member's interest obtains the member's entire rights associated with the member's interest in the bank or holding company including all economic rights and all voting rights.

.. A bank or holding company may not by agreement or otherwise change the application of (a) of this subsection to the bank or holding company.

. [Empty]
.. Notwithstanding any provision of chapter 25.15 RCW or this section to the contrary, all voting members remain liable and responsible as fiduciaries of a bank or holding company organized as a limited liability company, regardless of resignation, dissociation, or disqualification, to the same extent that directors of a bank or holding company organized as a corporation would be or remain liable or responsible to the department and applicable federal banking regulators; and

.. If death, incapacity, or disqualification of all members of the limited liability company would result in a complete dissociation of all members, then the bank, holding company, or both, as applicable is deemed nonetheless to remain in existence for purposes of the department or an applicable federal regulator, or both, having standing under RCW 30A.44.270 or applicable federal law, or both, to exercise the powers and authorities of a receiver for the bank or holding company.

. For the purposes of this section, and unless the context clearly requires otherwise, for the purpose of applying chapter 25.15 RCW to a bank or holding company organized as a limited liability company:

.. "Articles of incorporation" includes a limited liability company's certificate of formation, as that term is used in RCW 25.15.006 and 25.15.071, and a limited liability company agreement as that term is used in RCW 25.15.006;

.. "Board of directors" includes one or more persons who have, with respect to a bank or holding company described in subsection (1) of this section, authority that is substantially similar to that of a board of directors of a corporation;

.. "Bylaws" includes a limited liability company agreement as that term is defined in RCW 25.15.006;

.. "Corporation" includes a limited liability company organized under chapter 25.15 RCW;

.. "Director" includes any of the following of a limited liability company:

... A manager;

... A director; or

... Other person who has, with respect to the bank or holding company described in subsection (1) of this section, authority substantially similar to that of a director of a corporation;

.. "Dividend" includes distributions made by a limited liability company under RCW 25.15.211;

.. "Incorporator" includes the person or persons executing the certificate of formation as provided in RCW 25.15.086;

.. "Officer" includes any of the following of a bank or holding company:

.. An officer; or

... Other person who has, with respect to the bank or holding company, authority substantially similar to that of an officer of a corporation;

... "Security," "shares," or "stock" of a corporation includes a membership interest in a limited liability company and any certificate or other evidence of an ownership interest in a limited liability company; and

.. "Stockholder" or "shareholder" includes an owner of an equity interest in a bank or holding company, including a member as defined in RCW 25.15.006 and 25.15.116.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5030-S.SL.pdf?cite=2015%20c%20188%20§%20119[2015 c 188 § 119]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20152[2014 c 37 § 152]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5375.SL.pdf?cite=2011%20c%2052%20§%201[2011 c 52 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6463.SL.pdf?cite=2006%20c%2048%20§%202[2006 c 48 § 2]; ]

== 30A.08.030 - Investigation.
When the notice of intention to organize and proposed articles of incorporation complying with the foregoing requirements have been received by the director, together with the fees required by law, the director shall ascertain from the best source of information at his or her command and by such investigation as he or she may deem necessary, whether the character, responsibility and general fitness of the persons named in such articles are such as to command confidence and warrant belief that the business of the proposed bank will be honestly and efficiently conducted in accordance with the intent and purpose of this title, whether the resources in the neighborhood of such place and in the surrounding country afford a reasonable promise of adequate support for the proposed bank and whether the proposed bank is being formed for other than the legitimate objects covered by this title.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20153[2014 c 37 § 153]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2044[1994 c 92 § 44]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c104.pdf?cite=1973%201st%20ex.s.%20c%20104%20§%205[1973 1st ex.s. c 104 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.08.030[1955 c 33 § 30.08.030]; 1929 c 72 § 3, part; 1923 c 115 § 5, part; 1917 c 80 § 22, part; RRS § 3229, part; ]

== 30A.08.040 - Notice to file articles—Articles approved or refused—Hearing.
After the director is satisfied of the above facts, and, within six months of the date the notice of intention to organize has been received in his or her office, the director shall notify the incorporators to file executed articles of incorporation with the director in triplicate. Unless the director otherwise consents in writing, such articles shall be in the same form and shall contain the same information as the proposed articles and shall be filed with the director within ten days of such notice. Within thirty days after the receipt of such articles of incorporation, the director shall endorse upon each of the triplicates thereof, over his or her official signature, the word "approved," or the word "refused," with the date of such endorsement. In case of refusal the director shall forthwith return one of the triplicates, so endorsed, together with a statement explaining the reason for refusal to the person from whom the articles were received, which refusal shall be conclusive, unless the incorporators, within ten days of the issuance of such notice of refusal, shall request a hearing pursuant to the Administrative Procedure Act, chapter 34.05 RCW, as now or hereafter amended.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1015.SL.pdf?cite=1995%20c%20134%20§%204[1995 c 134 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6285.SL.pdf?cite=1994%20c%20256%20§%2043[1994 c 256 § 43]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2045[1994 c 92 § 45]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c302.pdf?cite=1981%20c%20302%20§%2015[1981 c 302 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c104.pdf?cite=1973%201st%20ex.s.%20c%20104%20§%206[1973 1st ex.s. c 104 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.08.040[1955 c 33 § 30.08.040]; prior: 1929 c 72 § 3, part; 1923 c 115 § 5, part; 1917 c 80 § 22, part; RRS § 3229, part; ]

== 30A.08.050 - Approved articles to be filed and recorded—Organization complete.
In case of approval the director shall forthwith give notice thereof to the proposed incorporators and file one of the triplicate articles of incorporation in his or her own office, and shall transmit another triplicate to the secretary of state, and the last to the incorporators. Upon receipt from the proposed incorporators of the same fees as are required for filing and recording other articles of incorporation the secretary of state shall file such articles and record the same. Upon the filing of articles of incorporation approved as aforesaid by the director, with the secretary of state, all persons named therein and their successors shall become and be a corporation, which shall have the powers and be subject to the duties and obligations prescribed by this title, and whose existence shall continue from the date of the filing of such articles until terminated pursuant to law; but such corporation shall not transact any business except as is necessarily preliminary to its organization until it has received a certificate of authority as provided herein.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2046[1994 c 92 § 46]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2019[1986 c 279 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c302.pdf?cite=1981%20c%20302%20§%2016[1981 c 302 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c248.pdf?cite=1957%20c%20248%20§%202[1957 c 248 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.08.050[1955 c 33 § 30.08.050]; 1929 c 72 § 3, part; 1923 c 115 § 5, part; 1917 c 80 § 22, part; RRS § 3229, part; ]

== 30A.08.055 - Amending articles—Filing with director—Contents.
A bank amending its articles of incorporation shall deliver articles of amendment to the director for filing as required for articles of incorporation. The articles of amendment shall set forth:

. The name of the bank;

. The text of each amendment adopted;

. The date of each amendment's adoption;

. If the amendment was adopted by the incorporators or board of directors without shareholder action, a statement to that effect and that shareholder action was not required; and

. If shareholder action was required, a statement that the amendment was duly approved by the shareholders in accordance with the provisions of RCW 30A.08.090.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20154[2014 c 37 § 154]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6285.SL.pdf?cite=1994%20c%20256%20§%2053[1994 c 256 § 53]; ]

== 30A.08.060 - Certificate of authority—Issuance—Contents.
Before any bank shall be authorized to do business, and within ninety days after approval of the articles of incorporation or such other time as the director may allow, it shall furnish proof satisfactory to the director that such corporation has a paid-in capital in the amount determined by the director, that the requisite surplus or reserve fund has been accumulated or paid in cash, and that it has in good faith complied with all the requirements of law and fulfilled all the conditions precedent to commencing business imposed by this title. If so satisfied, and within thirty days after receipt of such proof, the director shall issue under his or her hand and official seal, in triplicate, a certificate of authority for such corporation. The certificate shall state that the corporation therein named has complied with the requirements of law, that it is authorized to transact the business of a bank: PROVIDED, HOWEVER, That the director may make his or her issuance of the certificate to a bank authorized to accept deposits, conditional upon the granting of deposit insurance by the federal deposit insurance corporation, and in such event, shall set out such condition in a written notice which shall be delivered to the corporation.

One of the triplicate certificates shall be transmitted by the director to the corporation and one of the other two shall be filed by the director in the office of the secretary of state and shall be attached to the articles of incorporation: PROVIDED, HOWEVER, That if the issuance of the certificate is made conditional upon the granting of deposit insurance by the federal deposit insurance corporation, the director shall not transmit or file the certificate until such condition is satisfied.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20155[2014 c 37 § 155]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2047[1994 c 92 § 47]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2020[1986 c 279 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c302.pdf?cite=1981%20c%20302%20§%2017[1981 c 302 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c104.pdf?cite=1973%201st%20ex.s.%20c%20104%20§%207[1973 1st ex.s. c 104 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.08.060[1955 c 33 § 30.08.060]; 1929 c 72 § 3, part; 1923 c 115 § 5, part; 1917 c 80 § 22, part; RRS § 3229, part; ]

== 30A.08.070 - Failure to commence business—Effect—Extension of time.
Every corporation heretofore or hereafter authorized by the laws of this state to do business as a bank, which corporation shall have failed to organize and commence business within six months after certificate of authority to commence business has been issued by the director, shall forfeit its rights and privileges as such corporation, which fact the director shall certify to the secretary of state, and such certificate of forfeiture shall be filed and recorded in the office of the secretary of state in the same manner as the certificate of authority: PROVIDED, That the director may, upon showing of cause satisfactory to him or her, issue an order under his or her hand and seal extending for not more than three months the time within which such organization may be effected and business commenced, such order to be transmitted to the office of the secretary of state and filed and recorded therein.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20156[2014 c 37 § 156]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2048[1994 c 92 § 48]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2021[1986 c 279 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c302.pdf?cite=1981%20c%20302%20§%2018[1981 c 302 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.08.070[1955 c 33 § 30.08.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1931c9.pdf?cite=1931%20c%209%20§%201[1931 c 9 § 1]; RRS § 3229-1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c175.pdf?cite=1915%20c%20175%20§%2041[1915 c 175 § 41]; RRS § 3370; ]

== 30A.08.080 - Extension of existence—Application—Investigation—Certificate—Appeal—Winding up for failure to continue existence.
At any time not less than one year prior to the expiration of the time of the existence of any bank, it may by written application to the director, signed and verified by a majority of its directors and approved in writing by the owners of not less than two-thirds of its capital stock, apply to the director for leave to file amended articles of incorporation, extending its time of existence. Prior to acting upon such application, the director shall make such investigation of the applicant as he or she deems necessary. If the director determines that the applicant is in sound condition, that it is conducting its business in a safe manner and in compliance with law and that no reason exists why it should not be permitted to continue, he or she shall issue to the applicant a certificate authorizing it to file amended articles of incorporation extending the time of its existence until such time as it be dissolved by the act of its shareholders owning not less than two-thirds of its stock, or until its certificate of authority becomes revoked or forfeited by reason of violation of law, or until its affairs be taken over by the director for legal cause and finally wound up by him or her. Otherwise the director shall notify the applicant that he or she refuses to grant such certificate. The applicant may appeal from such refusal in the same manner as in the case of a refusal to grant an original certificate of authority. Otherwise the determination of the director shall be conclusive.

Upon receiving a certificate, as hereinabove provided, the applicant may file amended articles of incorporation, extending the time of its existence for the term authorized, to which shall be attached a copy of the certificate of the director. Such articles shall be filed in the same manner and upon payment of the same fees as for original articles of incorporation.

Should any bank fail to continue its existence in the manner herein provided and be not previously dissolved, the director shall at the end of its original term of existence immediately take possession thereof and wind up the same in the same manner as in the case of insolvency.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20157[2014 c 37 § 157]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5058-S.SL.pdf?cite=1999%20c%2014%20§%2012[1999 c 14 § 12]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2049[1994 c 92 § 49]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c280.pdf?cite=1961%20c%20280%20§%201[1961 c 280 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.08.080[1955 c 33 § 30.08.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c148.pdf?cite=1943%20c%20148%20§%201[1943 c 148 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c80.pdf?cite=1917%20c%2080%20§%2027[1917 c 80 § 27]; Rem. Supp. 1943 § 3234; ]

== 30A.08.081 - Shares—Certificates not required.
. Shares of a bank may, but need not be, represented by certificates. Unless this title expressly provides otherwise, the rights and obligations of shareholders are identical whether or not their shares are represented by certificates. At a minimum, each share certificate must state the information required to be stated and must be signed as provided in RCW 23B.06.250 and/or 23B.06.270 for corporations.

. Unless the articles of incorporation or bylaws provide otherwise, the board of directors of a bank may authorize the issue of some or all of the shares of any or all of its classes or series without certificates. The authorization does not affect shares already represented by certificates until they are surrendered to the bank.

. Within a reasonable time after the issue or transfer of shares without certificates, the bank shall send the shareholder a written statement of the information required to be stated on certificates under subsection (1) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20158[2014 c 37 § 158]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6285.SL.pdf?cite=1994%20c%20256%20§%2052[1994 c 256 § 52]; ]

== 30A.08.082 - Authority to issue preferred or special classes of stock.
. Notwithstanding any other provisions of law and if so authorized by its articles of incorporation or amendments thereto made in the manner provided in the case of a capital increase, any bank may, pursuant to action taken by its board of directors from time to time with the approval of the director, issue shares of preferred or special classes of stock with the attributes and in such amounts and with such par value, if any, as shall be determined by the board of directors from time to time with the approval of the director. No increase of preferred stock shall be valid until the amount thereof shall have been subscribed and actually paid in.

. If provided in its articles of incorporation, a bank may issue shares of preferred or special classes having any one or several of the following provisions:

.. Subjecting the shares to the right of the bank to repurchase or retire any such shares at the price fixed by the articles of incorporation for the repurchase or retirement thereof;

.. Entitling the holders thereof to cumulative, noncumulative, or partially cumulative dividends;

.. Having preference over any other class or classes of shares as to the payment of dividends;

.. Having preference in the assets of the bank over any other class or classes of shares upon the voluntary or involuntary liquidation of the bank;

.. Having voting or nonvoting rights; and

.. Being convertible into shares of any other class or into shares of any series of the same or any other class, except a class having prior or superior rights and preferences as to dividends or distribution of assets upon liquidation.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20159[2014 c 37 § 159]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6285.SL.pdf?cite=1994%20c%20256%20§%2044[1994 c 256 § 44]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2050[1994 c 92 § 50]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2022[1986 c 279 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c89.pdf?cite=1981%20c%2089%20§%204[1981 c 89 § 4]; ]

== 30A.08.083 - Authority to divide classes into series—Rights and preferences—Filing of statement.
. If the articles of incorporation shall expressly vest authority in the board of directors, then, to the extent that the articles of incorporation shall not have established series, and fixed and determined the variations in the relative rights and preferences as between series, the board of directors have authority to divide any or all of the classes into series and, within the limitation set forth in this section and in the articles of incorporation, fix and determine the relative rights and preferences of the shares of any series so established.

. In order for the board of directors to establish a series, where authority to do so is contained in the articles of incorporation, the board of directors shall adopt a resolution setting forth the designation of the series and fixing and determining the relative rights and preferences thereof, or so much thereof as is not fixed and determined by the articles of incorporation.

. Prior to the issue of any shares of a series established by resolution adopted by the board of directors, the corporation shall file and execute in the manner provided in this section a statement setting forth:

.. The name of the bank;

.. A copy of the resolution establishing and designating the series, and fixing and determining the relative rights and preferences thereof;

.. The date of adoption of such resolution; and

.. That the resolution was duly adopted by the board of directors.

. The statement shall be executed in triplicate by the bank by one of its officers and shall be delivered to the director. If the director finds that the statement conforms to law, the director shall, when all fees have been paid as provided in this title:

.. Endorse on each of the triplicate originals the word "Filed," and the effective date of the filing thereof;

.. File two of the originals; and

.. Return the other original to the bank or its representative.

. Upon the filing of the statement by the director with the secretary of state, the resolution establishing and designating the series and fixing and determining the relative rights and preferences thereof shall become effective and shall constitute an amendment of the articles of incorporation.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2051[1994 c 92 § 51]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2023[1986 c 279 § 23]; ]

== 30A.08.084 - Rights of holders of preferred or special classes of stock—Preference in dividends and liquidation.
Notwithstanding any other provisions of law, whether relating to restriction upon the payment of dividends upon capital stock or otherwise, the holders of shares of preferred or special classes of stock shall be entitled to receive such dividends on the purchase price received by the bank for such stock as may be provided by the articles of incorporation or by the board of directors of the bank with the approval of the director.

No dividends shall be declared or paid on common stock until cumulative dividends, if any, on the shares of preferred or special classes of stock shall have been paid in full; and, if the director takes possession of a bank for purposes of liquidation, no payments shall be made to the holders of the common stock until the holders of the shares of preferred or special classes of stock shall have been paid in full such amount as may be provided under the terms of said shares plus all accumulated dividends, if any.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20160[2014 c 37 § 160]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2052[1994 c 92 § 52]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2024[1986 c 279 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c89.pdf?cite=1981%20c%2089%20§%205[1981 c 89 § 5]; ]

== 30A.08.086 - Determination of capital impairment when capital consists of preferred stock.
If any part of the capital of a bank consists of preferred stock, the determination of whether or not the capital of such bank is impaired and the amount of such impairment shall be based on the value of its stock as established at the time it was issued, or its par value, if any, even though the amount which the holders of such preferred stock shall be entitled to receive in the event of retirement or liquidation shall be in excess of the originally established value or the par value of such preferred stock.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20161[2014 c 37 § 161]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2025[1986 c 279 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c89.pdf?cite=1981%20c%2089%20§%206[1981 c 89 § 6]; ]

== 30A.08.087 - Authorized but unissued shares of capital stock—Issuance—Consideration.
Any bank may provide in its articles of incorporation or amendments thereto for authorized but unissued shares of its capital stock. The shares may be issued for such consideration as shall be established by the board from time to time and all consideration received therefor shall be allocated to the capital stock or surplus of the corporation.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20162[2014 c 37 § 162]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6285.SL.pdf?cite=1994%20c%20256%20§%2045[1994 c 256 § 45]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2026[1986 c 279 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c106.pdf?cite=1979%20c%20106%20§%201[1979 c 106 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c140.pdf?cite=1965%20c%20140%20§%201[1965 c 140 § 1]; ]

== 30A.08.088 - Authorized but unissued shares of capital stock—When shares become part of capital stock.
The authorized but unissued shares shall not become a part of the capital stock until they have been issued and paid for.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6285.SL.pdf?cite=1994%20c%20256%20§%2046[1994 c 256 § 46]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2053[1994 c 92 § 53]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2027[1986 c 279 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c106.pdf?cite=1979%20c%20106%20§%202[1979 c 106 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c140.pdf?cite=1965%20c%20140%20§%202[1965 c 140 § 2]; ]

== 30A.08.090 - Amendment of articles—Procedure.
Unless the articles of incorporation provide otherwise, the board of directors of a bank may, by majority vote, amend the bank's articles of incorporation without shareholder action as follows:

. If the bank has only one class of shares outstanding, to provide, change, or eliminate any provision with respect to the par value of any class of shares;

. To delete the name and address of the initial directors;

. If the bank has only one class of shares outstanding, solely to change the number of authorized shares to effectuate a split of, or stock dividend in, the bank's own shares, or solely to do so and to change the number of authorized shares in proportion thereto;

. To change the bank's name; or

. To make any other change expressly permitted by this title to be made without shareholder action.

Other amendments to a bank's articles of incorporation, in a manner not inconsistent with the provisions of this title, require the affirmative vote of the stockholders representing two-thirds of each class of shares entitled to vote under the terms of the shares at a regular meeting, or special meeting duly called for that purpose in the manner prescribed by the bank's bylaws. No amendment shall be made whereby a bank becomes a trust company unless such bank first receives permission from the director.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20163[2014 c 37 § 163]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6285.SL.pdf?cite=1994%20c%20256%20§%2047[1994 c 256 § 47]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2054[1994 c 92 § 54]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c420.pdf?cite=1987%20c%20420%20§%203[1987 c 420 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2028[1986 c 279 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c140.pdf?cite=1965%20c%20140%20§%203[1965 c 140 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.08.090[1955 c 33 § 30.08.090]; prior:  1923 c 115 § 7; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c80.pdf?cite=1917%20c%2080%20§%2026[1917 c 80 § 26]; RRS § 3233; ]

== 30A.08.092 - Increase or decrease of capital stock authorized.
A bank may increase or decrease its capital stock by amendment to its articles of incorporation. No issuance of capital stock shall be valid, until the amount thereof shall have been actually paid in. No reduction of the capital stock shall be made to an amount less than is required for capital by the director.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20164[2014 c 37 § 164]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6285.SL.pdf?cite=1994%20c%20256%20§%2048[1994 c 256 § 48]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2055[1994 c 92 § 55]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c420.pdf?cite=1987%20c%20420%20§%204[1987 c 420 § 4]; ]

== 30A.08.140 - Corporate powers of banks. (Contingent expiration date.)
Upon the issuance of a certificate of authority to a bank, the persons named in the articles of incorporation and their successors shall thereupon become a corporation and shall have power:

. To adopt and use a corporate seal;

. To have perpetual succession;

. To make contracts;

. To sue and be sued, the same as a natural person;

. To elect directors who, subject to the provisions of the corporation's bylaws, shall have power to appoint such officers as may be necessary or convenient, to define their powers and duties and to dismiss them at pleasure, and who shall also have general supervision and control of the affairs of such corporation;

. To make and alter bylaws, not inconsistent with its articles of incorporation or with the laws of this state, for the administration and regulation of its affairs;

. To invest and reinvest its funds in marketable obligations evidencing the indebtedness of any person, copartnership, association, or corporation in the form of bonds, notes, or debentures commonly known as investment securities except as may by regulation be limited by the director;

. To discount and negotiate promissory notes, drafts, bills of exchange and other evidences of debt, to receive deposits of money and commercial paper, to lend money secured or unsecured, to issue all forms of letters of credit, to buy and sell bullion, coins and bills of exchange;

. To take and receive as bailee for hire upon terms and conditions to be prescribed by the corporation, for safekeeping and storage, jewelry, plate, money, specie, bullion, stocks, bonds, mortgages, securities and valuable paper of any kind and other valuable personal property, and to rent vaults, safes, boxes and other receptacles for safekeeping and storage of personal property;

. If the bank be located in a city of not more than five thousand inhabitants, to act as insurance agent. A bank exercising this power may continue to act as an insurance agent notwithstanding a change of the population of the city in which it is located;

. To accept drafts or bills of exchange drawn upon it having not more than six months sight to run, which grow out of transactions involving the importation or exportation of goods; or which grow out of transactions involving the domestic shipment of goods, providing shipping documents conveying or securing title are attached at the time of acceptance; or which are secured at the time of acceptance by a warehouse receipt or other such document conveying or securing title to readily marketable staples. No bank shall accept, either in a foreign or a domestic transaction, for any one person, company, firm or corporation, to an amount equal at any one time in the aggregate to more than ten percent of its paid up and unimpaired capital stock and surplus unless the bank is secured by attached documents or by some other actual security growing out of the same transaction as the acceptance; and no bank shall accept such bills to an amount equal at any time in the aggregate to more than one-half of its paid up and unimpaired capital stock and surplus: PROVIDED, HOWEVER, That the director, under such general regulations applicable to all banks irrespective of the amount of capital or surplus, as the director may prescribe may authorize any bank to accept such bills to an amount not exceeding at any time in the aggregate one hundred percent of its paid up and unimpaired capital stock and surplus: PROVIDED, FURTHER, That the aggregate of acceptances growing out of domestic transactions shall in no event exceed fifty percent of such capital stock and surplus;

. To accept drafts or bills of exchange drawn upon it, having not more than three months sight to run, drawn under regulations to be prescribed by the director by banks or bankers in foreign countries or dependencies or insular possessions of the United States for the purpose of furnishing dollar exchange as required by the usages of trade in the respective countries, dependencies or insular possessions. Such drafts or bills may be acquired by banks in such amounts and subject to such regulations, restrictions and limitations as may be provided by the director: PROVIDED, HOWEVER, That no bank shall accept such drafts or bills of exchange referred to in this subdivision for any one bank to an amount exceeding in the aggregate ten percent of the paid up and unimpaired capital and surplus of the accepting bank unless the draft or bill of exchange is accompanied by documents conveying or securing title or by some other adequate security, and that no such drafts or bills of exchange shall be accepted by any bank in an amount exceeding at any time the aggregate of one-half of its paid up and unimpaired capital and surplus: PROVIDED FURTHER, That compliance by any bank which is a member of the federal reserve system of the United States with the rules, regulations and limitations adopted by the federal reserve board thereof with respect to the acceptance of drafts or bills of exchange by members of such federal reserve system shall be a sufficient compliance with the requirements of this subdivision or paragraph relating to rules, regulations and limitations prescribed by the director;

. To have and exercise all powers necessary or convenient to effect its purposes;

. To serve as custodian of an individual retirement account and pension and profit sharing plans qualified under internal revenue code section 401(a), the assets of which are invested in deposits of the bank or are invested, pursuant to directions from the customer owning the account, in securities traded on a national securities market: PROVIDED, That the bank shall accept no investment responsibilities over the account unless it is granted trust powers by the director;

. To be a limited partner in a limited partnership that engages in only such activities as are authorized for the bank.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20165[2014 c 37 § 165]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1325-S.SL.pdf?cite=2013%20c%2076%20§%209[2013 c 76 § 9]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2125-S.SL.pdf?cite=1996%20c%202%20§%205[1996 c 2 § 5]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2058[1994 c 92 § 58]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c279.pdf?cite=1986%20c%20279%20§%2029[1986 c 279 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c248.pdf?cite=1957%20c%20248%20§%203[1957 c 248 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.08.140[1955 c 33 § 30.08.140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1931c127.pdf?cite=1931%20c%20127%20§%201[1931 c 127 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c209.pdf?cite=1919%20c%20209%20§%208[1919 c 209 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c80.pdf?cite=1917%20c%2080%20§%2023[1917 c 80 § 23]; RRS § 3230; ]

== 30A.08.150 - Banks engaged in trust business.
. Upon the issuance of a certificate of authority to a bank, the persons named in the articles of incorporation and their successors shall have the power to engage in trust business and other business the same as a state trust company as set forth in *RCW 30B.08.080(1) (b) through (q).

. Notwithstanding the powers of a trust business set forth in *RCW 30B.08.080(1) (b) through (k) and as the director may designate by rule pursuant to *RCW 30B.08.080(1)(q), a bank shall notify the director prior to commencing trust business, and comply with additional preconditions as may be required by the board of governors of the federal reserve system, the federal deposit insurance corporation, or by rule adopted by the director.

. A bank under this title is deemed to be a trust company for purposes of authorization to be a personal representative under RCW 11.36.010.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20167[2014 c 37 § 167]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20746[2011 c 336 § 746]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c154.pdf?cite=1973%201st%20ex.s.%20c%20154%20§%2048[1973 1st ex.s. c 154 § 48]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.08.150[1955 c 33 § 30.08.150]; 1929 c 72 § 4, part; 1923 c 115 § 6, part; 1921 c 94 § 1, part; 1917 c 80 § 24, part; RRS § 3231, part; ]

== 30A.08.180 - Reports of resources and liabilities.
Every bank shall make at least three regular reports each year to the director, as of the dates which he or she shall designate, according to form prescribed by him or her, verified by the president, manager or cashier and attested by at least two directors, which shall exhibit under appropriate heads the resources and liabilities of such corporation. The dates designated by the director shall be the dates designated by the comptroller of the currency of the United States for reports of national banking associations.

Every such corporation shall also make such special reports as the director shall call for.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20168[2014 c 37 § 168]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5931.SL.pdf?cite=1995%20c%20344%20§%203[1995 c 344 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2060[1994 c 92 § 60]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.08.180[1955 c 33 § 30.08.180]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c209.pdf?cite=1919%20c%20209%20§%204[1919 c 209 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c80.pdf?cite=1917%20c%2080%20§%205[1917 c 80 § 5]; RRS § 3212; ]

== 30A.08.190 - Time of filing—Availability—Penalty.
. Every regular report shall be filed with the director within thirty days from the date of issuance of the notice. Every special report shall be filed with the director within such time as shall be specified by him or her in the notice therefor.

. The director shall provide a copy of any regular report free of charge to any person that submits a written request for the report.

. Every bank which fails to file any report, required to be filed under subsection (1) of this section and within the time specified, shall be subject to a penalty of fifty dollars per day for each day's delay. A civil action for the recovery of any such penalty may be brought by the attorney general in the name of the state.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20169[2014 c 37 § 169]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5931.SL.pdf?cite=1995%20c%20344%20§%204[1995 c 344 § 4]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1015.SL.pdf?cite=1995%20c%20134%20§%206[1995 c 134 § 6]; prior:  1994 c 256 § 51; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%2061[1994 c 92 § 61]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977c38.pdf?cite=1977%20c%2038%20§%201[1977 c 38 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.08.190[1955 c 33 § 30.08.190]; prior:  1917 c 80 § 6; RRS § 3213; ]

