= 30A.32 - Dealings with federal loan agencies.
:toc:

== 30A.32.010 - Membership in federal reserve system—Investment in stock of Federal Deposit Insurance Corporation.
Any bank or mutual savings bank may become a member of the federal reserve system of the United States and to that end may comply with all laws of the United States and all rules, regulations and requirements promulgated pursuant thereto, including the investment of its funds in the stock of a federal reserve bank; and any bank or mutual savings bank, whether a member of the federal reserve system or not, may invest its funds in the stock of the Federal Deposit Insurance Corporation created by the act of congress approved June 16, 1933, and may participate in the insurance of bank deposits and obligate itself for the cost of such participation by assessments or otherwise in accordance with the laws of the United States.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20200[2014 c 37 § 200]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.32.010[1955 c 33 § 30.32.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933ex1c9.pdf?cite=1933%20ex.s.%20c%209%20§%201[1933 ex.s. c 9 § 1]; RRS § 3235-1; ]

== 30A.32.020 - Investment in federal home loan bank stock or bonds.
Any savings and loan association, building and loan association, bank, savings bank, or mutual savings bank may become a member of and invest its funds in the bonds and/or the capital stock of a federal home loan bank, and vote such stock in the manner prescribed by its board of directors.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20201[2014 c 37 § 201]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.32.020[1955 c 33 § 30.32.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c105.pdf?cite=1933%20c%20105%20§%201[1933 c 105 § 1]; RRS § 3294-1; ]

== 30A.32.030 - May borrow from home loan bank.
Any such bank, insurance company, or association, may borrow from any home loan bank and as security for borrowing may pledge therewith the notes, mortgages, trust deeds which it holds as shall be required by federal law, and under such rules and regulations as shall be adopted by a federal home loan bank.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20202[2014 c 37 § 202]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.32.030[1955 c 33 § 30.32.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c105.pdf?cite=1933%20c%20105%20§%202[1933 c 105 § 2]; RRS § 3294-2; ]

== 30A.32.040 - Federal home loan bank as depositary.
Any such bank, insurance company, or association, may designate a federal home loan bank as a depositary for its funds.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20203[2014 c 37 § 203]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c33.pdf?cite=1955%20c%2033%20§%2030.32.040[1955 c 33 § 30.32.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c105.pdf?cite=1933%20c%20105%20§%203[1933 c 105 § 3]; RRS § 3294-3; ]

