= 30A.60 - Community credit needs.
:toc:

== 30A.60.010 - Examinations—Investigation and assessment of performance record in meeting community credit needs.
. In conducting an examination of a bank chartered under *Title 30 RCW, the director shall investigate and assess the record of performance of the bank in meeting the credit needs of the bank's entire community, including low and moderate-income neighborhoods. The director shall accept, in lieu of an investigation or part of an investigation required by this section, any report or document that the bank is required to prepare or file with one or more federal agencies by the act of Congress entitled the "Community Reinvestment Act of 1977" and the regulations promulgated in accordance with that act, to the extent such reports or documents assist the director in making an assessment based upon the factors outlined in subsection (2) of this section.

. In making an investigation required under subsection (1) of this section, the director shall consider, independent of any federal determination, the following factors in assessing the bank's record of performance:

.. Activities conducted by the institution to ascertain credit needs of its community, including the extent of the institution's efforts to communicate with members of its community regarding the credit services being provided by the institution;

.. The extent of the institution's marketing and special credit related programs to make members of the community aware of the credit services offered by the institution;

.. The extent of participation by the institution's board of directors in formulating the institution's policies and reviewing its performance with respect to the purposes of the Community Reinvestment Act of 1977;

.. Any practices intended to discourage applications for types of credit set forth in the institution's community reinvestment act statement(s);

.. The geographic distribution of the institution's credit extensions, credit applications, and credit denials;

.. Evidence of prohibited discriminatory or other illegal credit practices;

.. The institution's record of opening and closing offices and providing services at offices;

.. The institution's participation, including investments, in local community and microenterprise development projects;

.. The institution's origination of residential mortgage loans, housing rehabilitation loans, home improvement loans, and small business or small farm loans within its community, or the purchase of such loans originated in its community;

.. The institution's participation in governmentally insured, guaranteed, or subsidized loan programs for housing, small businesses, or small farms;

.. The institution's ability to meet various community credit needs based on its financial condition, size, legal impediments, local economic condition, and other factors;

.. The institution's contribution of cash or in-kind support to local or statewide organizations that provide counseling, training, financing, or other services to small businesses; and

.. Other factors that, in the judgment of the director, reasonably bear upon the extent to which an institution is helping to meet the credit needs of its entire community.

. The director shall include as part of the examination report, a summary of the results of the assessment required under subsection (1) of this section and shall assign annually to each bank a numerical community reinvestment rating based on a one through five scoring system. Such numerical scores shall represent performance assessments as follows:

.. Excellent performance:1(b) Good performance:2(c) Satisfactory performance:3(d) Inadequate performance:4(e) Poor performance:5

.. Excellent performance:

1

.. Good performance:

2

.. Satisfactory performance:

3

.. Inadequate performance:

4

.. Poor performance:

5

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5723-S.SL.pdf?cite=2009%20c%20486%20§%203[2009 c 486 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5651-S.SL.pdf?cite=2008%20c%20240%20§%201[2008 c 240 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20157[1994 c 92 § 157]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c329.pdf?cite=1985%20c%20329%20§%202[1985 c 329 § 2]; ]

== 30A.60.020 - Approval and disapproval of applications—Consideration of performance record in meeting community credit needs.
Whenever the director must approve or disapprove of an application for a new branch or satellite facility; for a purchase of assets, a merger, an acquisition or a conversion not required for solvency reasons; or for authority to engage in a business activity, the director shall consider, among other factors, the record of performance of the applicant in helping to meet the credit needs of the applicant's entire community, including low and moderate-income neighborhoods. Assessment of an applicant's record of performance may be the basis for denying an application.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20158[1994 c 92 § 158]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c329.pdf?cite=1985%20c%20329%20§%203[1985 c 329 § 3]; ]

== 30A.60.030 - Adoption of rules.
The director shall adopt all rules necessary to implement sections 2 through 6, chapter 329, Laws of 1985 by January 1, 1986.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20159[1994 c 92 § 159]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c329.pdf?cite=1985%20c%20329%20§%207[1985 c 329 § 7]; ]

== 30A.60.901 - Effective date—1985 c 329.
This act shall take effect on January 1, 1986, but the director may immediately take such steps as are necessary to ensure that this act is implemented on its effective date.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20160[1994 c 92 § 160]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c329.pdf?cite=1985%20c%20329%20§%2013[1985 c 329 § 13]; ]

