= 77.75 - Compacts and other agreements.
:toc:

== 77.75.010 - Columbia River Compact—Provisions.
There exists between the states of Washington and Oregon a definite compact and agreement as follows:

All laws and regulations now existing or which may be necessary for regulating, protecting or preserving fish in the waters of the Columbia river, or its tributaries, over which the states of Washington and Oregon have concurrent jurisdiction, or which would be affected by said concurrent jurisdiction, shall be made, changed, altered and amended in whole or in part, only with the mutual consent and approbation of both states.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%20149[1983 1st ex.s. c 46 § 149]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c12.pdf?cite=1955%20c%2012%20§%2075.40.010[1955 c 12 § 75.40.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c112.pdf?cite=1949%20c%20112%20§%2080[1949 c 112 § 80]; Rem. Supp. 1949 § 5780-701; ]

== 77.75.020 - Columbia River Compact—Commission to represent state.
The commission may give to the state of Oregon such consent and approbation of the state of Washington as is necessary under the compact set out in RCW 77.75.010. For the purposes of RCW 77.75.010, the states of Washington and Oregon have concurrent jurisdiction in the concurrent waters of the Columbia river.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2086[2000 c 107 § 86]; 1995 1st sp.s. c 2 § 19 (Referendum Bill No. 45, approved November 7, 1995); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%20150[1983 1st ex.s. c 46 § 150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c12.pdf?cite=1955%20c%2012%20§%2075.40.020[1955 c 12 § 75.40.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c112.pdf?cite=1949%20c%20112%20§%2081[1949 c 112 § 81]; Rem. Supp. 1949 § 5780-702; ]

== 77.75.030 - Pacific Marine Fisheries Compact—Provisions.
There exists between the states of Alaska, California, Idaho, Oregon and Washington a definite compact and agreement as follows:

THE PACIFIC MARINE FISHERIES COMPACT

The contracting states do hereby agree as follows:

ARTICLE I.

The purposes of this compact are and shall be to promote the better utilization of fisheries, marine, shell and anadromous, which are of mutual concern, and to develop a joint program of protection and prevention of physical waste of such fisheries in all of those areas of the Pacific Ocean and adjacent waters over which the compacting states jointly or separately now have or may hereafter acquire jurisdiction.

Nothing herein contained shall be construed so as to authorize the compacting states or any of them to limit the production of fish or fish products for the purpose of establishing or fixing the prices thereof or creating and perpetuating a monopoly.

ARTICLE II.

This agreement shall become operative immediately as to those states executing it whenever the compacting states have executed it in the form that is in accordance with the laws of the executing states and the congress has given its consent.

ARTICLE III.

Each state joining herein shall appoint, as determined by state statutes, one or more representatives to a commission hereby constituted and designated as The Pacific Marine Fisheries Commission, of whom one shall be the administrative or other officer of the agency of such state charged with the conservation of the fisheries resources to which this compact pertains. This commission shall be a body with the powers and duties set forth herein.

The term of each commissioner of The Pacific Marine Fisheries Commission shall be four years. A commissioner shall hold office until his successor shall be appointed and qualified but such successor's term shall expire four years from legal date of expiration of the term of his predecessor. Vacancies occurring in the office of such commissioner from any reason or cause shall be filled for the unexpired term, or a commissioner may be removed from office, as provided by the statutes of the state concerned. Each commissioner may delegate in writing from time to time to a deputy the power to be present and participate, including voting as his representative or substitute, at any meeting of or hearing by or other proceeding of the commission.

Voting powers under this compact shall be limited to one vote for each state regardless of the number of representatives.

ARTICLE IV.

The duty of the said commission shall be to make inquiry and ascertain from time to time such methods, practices, circumstances and conditions as may be disclosed for bringing about the conservation and the prevention of the depletion and physical waste of the fisheries, marine, shell, and anadromous in all of those areas of the Pacific Ocean over which the states signatory to this compact jointly or separately now have or may hereafter acquire jurisdiction. The commission shall have power to recommend the coordination of the exercise of the police powers of the several states within their respective jurisdictions and said conservation zones to promote the preservation of those fisheries and their protection against overfishing, waste, depletion or any abuse whatsoever and to assure a continuing yield from the fisheries resources of the signatory parties hereto.

To that end the commission shall draft and, after consultation with the advisory committee hereinafter authorized, recommend to the governors and legislative branches of the various signatory states hereto legislation dealing with the conservation of the marine, shell and anadromous fisheries in all of those areas of the Pacific Ocean and adjacent waters over which the signatory states jointly or separately now have or may hereafter acquire jurisdiction. The commission shall, more than one month prior to any regular meeting of the legislative branch in any state signatory hereto, present to the governor of such state its recommendations relating to enactments by the legislative branch of that state in furthering the intents and purposes of this compact.

The commission shall consult with and advise the pertinent administrative agencies in the signatory states with regard to problems connected with the fisheries and recommend the adoption of such regulations as it deems advisable and which lie within the jurisdiction of such agencies.

The commission shall have power to recommend to the states signatory hereto the stocking of the waters of such states with marine, shell, or anadromous fish and fish eggs or joint stocking by some or all of such states and when two or more of the said states shall jointly stock waters the commission shall act as the coordinating agency for such stocking.

ARTICLE V.

The commission shall elect from its number a chairman and a vice chairman and shall appoint and at its pleasure, remove or discharge such officers and employees as may be required to carry the provisions of this compact into effect and shall fix and determine their duties, qualifications and compensation. Said commission shall adopt rules and regulations for the conduct of its business. It may establish and maintain one or more offices for the transaction of its business and may meet at any time or place within the territorial limits of the signatory states but must meet at least once a year.

ARTICLE VI.

No action shall be taken by the commission except by the affirmative vote of a majority of the whole number of compacting states represented at any meeting. No recommendation shall be made by the commission in regard to any species of fish except by the vote of a majority of the compacting states which have an interest in such species.

ARTICLE VII.

The fisheries research agencies of the signatory states shall act in collaboration as the official research agency of The Pacific Marine Fisheries Commission.

An advisory committee to be representative of the commercial fishermen, commercial fishing industry and such other interests of each state as the commission deems advisable shall be established by the commission as soon as practicable for the purpose of advising the commission upon such recommendations as it may desire to make.

ARTICLE VIII.

Nothing in this compact shall be construed to limit the powers of any state or to repeal or prevent the enactment of any legislation or the enforcement of any requirement by any state imposing additional conditions and restrictions to conserve its fisheries.

ARTICLE IX.

Continued absence of representation or of any representative on the commission from any state party hereto, shall be brought to the attention of the governor thereof.

ARTICLE X.

The states agree to make available annual funds for the support of the commission on the following basis:

Eighty percent of the annual budget shall be shared equally by those member states having as a boundary the Pacific Ocean; not less than five percent of the annual budget shall be contributed by any other member state; the balance of the annual budget shall be shared by those member states, having as a boundary the Pacific Ocean, in proportion to the primary market value of the products of their commercial fisheries on the basis of the latest five-year catch records.

The annual contribution of each member state shall be figured to the nearest one hundred dollars.

This amended article shall become effective upon its enactment by the states of Alaska, California, Idaho, Oregon, and Washington and upon ratification by congress by virtue of the authority vested in it under Article I, section 10 of the Constitution of the United States.

ARTICLE XI.

This compact shall continue in force and remain binding upon each state until renounced by it. Renunciation of this compact must be preceded by sending six months' notice in writing of intention to withdraw from the compact to the other parties hereto.

ARTICLE XII.

The states of Alaska or Hawaii, or any state having rivers or streams tributary to the Pacific Ocean may become a contracting state by enactment of The Pacific Marine Fisheries Compact. Upon admission of any new state to the compact, the purposes of the compact and the duties of the commission shall extend to the development of joint programs for the conservation, protection and prevention of physical waste of fisheries in which the contracting states are mutually concerned and to all waters of the newly admitted state necessary to develop such programs.

This article shall become effective upon its enactment by the states of Alaska, California, Idaho, Oregon and Washington and upon ratification by congress by virtue of the authority vested in it under Article I, section 10, of the Constitution of the United States.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%20151[1983 1st ex.s. c 46 § 151]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c101.pdf?cite=1969%20ex.s.%20c%20101%20§%202[1969 ex.s. c 101 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959ex1c7.pdf?cite=1959%20ex.s.%20c%207%20§%201[1959 ex.s. c 7 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c12.pdf?cite=1955%20c%2012%20§%2075.40.030[1955 c 12 § 75.40.030]; 1949 c 112 § 82; Rem. Supp. 1949 § 5780-703; ]

== 77.75.040 - Pacific Marine Fisheries Compact—Representatives of state on Pacific Marine Fisheries Commission.
A member selected by or a designee of the fish and wildlife commission, ex officio, and two appointees of the governor representing the fishing industry shall act as the representatives of this state on the Pacific Marine Fisheries Commission. The appointees of the governor are subject to confirmation by the state senate.

[ 1995 1st sp.s. c 2 § 20 (Referendum Bill No. 45, approved November 7, 1995); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%20152[1983 1st ex.s. c 46 § 152]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c171.pdf?cite=1963%20c%20171%20§%202[1963 c 171 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c12.pdf?cite=1955%20c%2012%20§%2075.40.040[1955 c 12 § 75.40.040]; 1949 c 112 § 82; Rem. Supp. 1949 § 5780-703; ]

== 77.75.050 - Coastal ecosystems compact authorized.
The state of Washington is authorized to enter into an interstate compact or compacts with all or any of the states of California, Idaho, and Oregon to protect and restore coastal ecosystems of these states to levels that will prevent the need for listing any native salmonid fish species under the federal endangered species act of 1973, as amended, or under any comparable state legislation.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6264-S.SL.pdf?cite=1994%20c%20148%20§%201[1994 c 148 § 1]; ]

== 77.75.060 - Coastal ecosystems cooperative agreements authorized.
Until such time as the agencies in California, Idaho, Oregon, and Washington present a final proposed interstate compact for enactment by their respective legislative bodies, the governor may establish cooperative agreements with the states of California, Idaho, and Oregon that allow the states to coordinate their individual efforts in developing state programs that further the regionwide goals set forth under RCW 77.75.050.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2087[2000 c 107 § 87]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6264-S.SL.pdf?cite=1994%20c%20148%20§%202[1994 c 148 § 2]; ]

== 77.75.070 - Wildlife violator compact—Established.
The wildlife violator compact is hereby established in the form substantially as follows, and the Washington state department of fish and wildlife is authorized to enter into such compact on behalf of the state with all other jurisdictions legally joining therein:

ARTICLE I

FINDINGS, DECLARATION OF

POLICY, AND PURPOSE

.. The party states find that:

. Wildlife resources are managed in trust by the respective states for the benefit of all residents and visitors.

. The protection of their respective wildlife resources can be materially affected by the degree of compliance with state statute, law, regulation, ordinance, or administrative rule relating to the management of those resources.

. The preservation, protection, management, and restoration of wildlife contributes immeasurably to the aesthetic, recreational, and economic aspects of these natural resources.

. Wildlife resources are valuable without regard to political boundaries, therefore, all persons should be required to comply with wildlife preservation, protection, management, and restoration laws, ordinances, and administrative rules and regulations of all party states as a condition precedent to the continuance or issuance of any license to hunt, fish, trap, or possess wildlife.

. Violation of wildlife laws interferes with the management of wildlife resources and may endanger the safety of persons and property.

. The mobility of many wildlife law violators necessitates the maintenance of channels of communications among the various states.

. In most instances, a person who is cited for a wildlife violation in a state other than the person's home state:

... Must post collateral or bond to secure appearance for a trial at a later date; or

... If unable to post collateral or bond, is taken into custody until the collateral or bond is posted; or

... Is taken directly to court for an immediate appearance.

. The purpose of the enforcement practices described in paragraph (7) of this subdivision is to ensure compliance with the terms of a wildlife citation by the person who, if permitted to continue on the person's way after receiving the citation, could return to the person's home state and disregard the person's duty under the terms of the citation.

. In most instances, a person receiving a wildlife citation in the person's home state is permitted to accept the citation from the officer at the scene of the violation and to immediately continue on the person's way after agreeing or being instructed to comply with the terms of the citation.

. The practice described in paragraph (7) of this subdivision causes unnecessary inconvenience and, at times, a hardship for the person who is unable at the time to post collateral, furnish a bond, stand trial, or pay the fine, and thus is compelled to remain in custody until some alternative arrangement can be made.

. The enforcement practices described in paragraph (7) of this subdivision consume an undue amount of law enforcement time.

.. It is the policy of the party states to:

. Promote compliance with the statutes, laws, ordinances, regulations, and administrative rules relating to management of wildlife resources in their respective states.

. Recognize the suspension of wildlife license privileges of any person whose license privileges have been suspended by a party state and treat this suspension as if it had occurred in their state.

. Allow violators to accept a wildlife citation, except as provided in subdivision (b) of Article III, and proceed on the violator's way without delay whether or not the person is a resident in the state in which the citation was issued, provided that the violator's home state is party to this compact.

. Report to the appropriate party state, as provided in the compact manual, any conviction recorded against any person whose home state was not the issuing state.

. Allow the home state to recognize and treat convictions recorded for their residents which occurred in another party state as if they had occurred in the home state.

. Extend cooperation to its fullest extent among the party states for obtaining compliance with the terms of a wildlife citation issued in one party state to a resident of another party state.

. Maximize effective use of law enforcement personnel and information.

. Assist court systems in the efficient disposition of wildlife violations.

.. The purpose of this compact is to:

. Provide a means through which the party states may participate in a reciprocal program to effectuate policies enumerated in subdivision (b) of this article in a uniform and orderly manner.

. Provide for the fair and impartial treatment of wildlife violators operating within party states in recognition of the person's right of due process and the sovereign status of a party state.

ARTICLE II

DEFINITIONS

Unless the context requires otherwise, the definitions in this article apply through this compact and are intended only for the implementation of this compact:

.. "Citation" means any summons, complaint, ticket, penalty assessment, or other official document issued by a wildlife officer or other peace officer for a wildlife violation containing an order which requires the person to respond.

.. "Collateral" means any cash or other security deposited to secure an appearance for trial, in connection with the issuance by a wildlife officer or other peace officer of a citation for a wildlife violation.

.. "Compliance" with respect to a citation means the act of answering the citation through appearance at a court, a tribunal, or payment of fines, costs, and surcharges, if any, or both such appearance and payment.

.. "Conviction" means a conviction, including any court conviction, of any offense related to the preservation, protection, management, or restoration of wildlife which is prohibited by state statute, law, regulation, ordinance, or administrative rule, or a forfeiture of bail, bond, or other security deposited to secure appearance by a person charged with having committed any such offense, or payment of a penalty assessment, or a plea of nolo contendere, or the imposition of a deferred or suspended sentence by the court.

.. "Court" means a court of law, including Magistrate's Court and the Justice of the Peace Court.

.. "Home state" means the state of primary residence of a person.

.. "Issuing state" means the party state which issues a wildlife citation to the violator.

.. "License" means any license, permit, or other public document which conveys to the person to whom it was issued the privilege of pursuing, possessing, or taking any wildlife regulated by statute, law, regulation, ordinance, or administrative rule of a party state.

.. "Licensing authority" means the department or division within each party state which is authorized by law to issue or approve licenses or permits to hunt, fish, trap, or possess wildlife.

.. "Party state" means any state which enacts legislation to become a member of this wildlife compact.

.. "Personal recognizance" means an agreement by a person made at the time of issuance of the wildlife citation that the person will comply with the terms of that citation.

.. "State" means any state, territory, or possession of the United States, the District of Columbia, Commonwealth of Puerto Rico, Provinces of Canada, or other countries.

.. "Suspension" means any revocation, denial, or withdrawal of any or all license privileges, including the privilege to apply for, purchase, or exercise the benefits conferred by any license.

.. "Terms of the citation" means those conditions and options expressly stated upon the citation.

.. "Wildlife" means all species of animals, including but not necessarily limited to mammals, birds, fish, reptiles, amphibians, mollusks, and crustaceans, which are defined as "wildlife" and are protected or otherwise regulated by statute, law, regulation, ordinance, or administrative rule in a party state. "Wildlife" also means food fish and shellfish as defined by statute, law, regulation, ordinance, or administrative rule in a party state. Species included in the definition of "wildlife" vary from state to state and determination of whether a species is "wildlife" for the purposes of this compact shall be based on local law.

.. "Wildlife law" means any statute, law, regulation, ordinance, or administrative rule developed and enacted to manage wildlife resources and the use thereof.

.. "Wildlife officer" means any individual authorized by a party state to issue a citation for a wildlife violation.

.. "Wildlife violation" means any cited violation of a statute, law, regulation, ordinance, or administrative rule developed and enacted to manage wildlife resources and the use thereof.

ARTICLE III

PROCEDURES FOR ISSUING STATE

.. When issuing a citation for a wildlife violation, a wildlife officer shall issue a citation to any person whose primary residence is in a party state in the same manner as if the person were a resident of the home state and shall not require the person to post collateral to secure appearance, subject to the exceptions contained in subdivision (b) of this article, if the officer receives the person's personal recognizance that the person will comply with the terms of the citation.

.. Personal recognizance is acceptable:

. If not prohibited by local law or the compact manual; and

. If the violator provides adequate proof of the violator's identification to the wildlife officer.

.. Upon conviction or failure of a person to comply with the terms of a wildlife citation, the appropriate official shall report the conviction or failure to comply to the licensing authority of the party state in which the wildlife citation was issued. The report shall be made in accordance with procedures specified by the issuing state and shall contain the information specified in the compact manual as minimum requirements for effective processing by the home state.

.. Upon receipt of the report of conviction or noncompliance required by subdivision (c) of this article, the licensing authority of the issuing state shall transmit to the licensing authority in the home state of the violator the information in a form and content as contained in the compact manual.

ARTICLE IV

PROCEDURES FOR HOME STATE

.. Upon receipt of a report of failure to comply with the terms of a citation from the licensing authority of the issuing state, the licensing authority of the home state shall notify the violator, shall initiate a suspension action in accordance with the home state's suspension procedures and shall suspend the violator's license privileges until satisfactory evidence of compliance with the terms of the wildlife citation has been furnished by the issuing state to the home state licensing authority. Due process safeguards will be accorded.

.. Upon receipt of a report of conviction from the licensing authority of the issuing state, the licensing authority of the home state shall enter such conviction in its records and shall treat such conviction as if it occurred in the home state for the purposes of the suspension of license privileges.

.. The licensing authority of the home state shall maintain a record of actions taken and make reports to issuing states as provided in the compact manual.

ARTICLE V

RECIPROCAL RECOGNITION OF SUSPENSION

All party states shall recognize the suspension of license privileges of any person by any state as if the violation on which the suspension is based had in fact occurred in their state and could have been the basis for suspension of license privileges in their state.

ARTICLE VI

APPLICABILITY OF OTHER LAWS

Except as expressly required by provisions of this compact, nothing herein shall be construed to affect the right of any party state to apply any of its laws relating to license privileges to any person or circumstance, or to invalidate or prevent any agreement or other cooperative arrangements between a party state and a nonparty state concerning wildlife law enforcement.

ARTICLE VII

COMPACT ADMINISTRATOR PROCEDURES

.. For the purpose of administering the provisions of this compact and to serve as a governing body for the resolution of all matters relating to the operation of this compact, a board of compact administrators is established. The board shall be composed of one representative from each of the party states to be known as the compact administrator. The compact administrator shall be appointed by the head of the licensing authority of each party state and will serve and be subject to removal in accordance with the laws of the state the administrator represents. A compact administrator may provide for the discharge of the administrator's duties and the performance of the administrator's functions as a board member by an alternate. An alternate may not be entitled to serve unless written notification of the alternate's identity has been given to the board.

.. Each member of the board of compact administrators shall be entitled to one vote. No action of the board shall be binding unless taken at a meeting at which a majority of the total number of votes on the board are cast in favor thereof. Action by the board shall be only at a meeting at which a majority of the party states are represented.

.. The board shall elect annually, from its membership, a chairperson and vice chairperson.

.. The board shall adopt bylaws, not inconsistent with the provisions of this compact or the laws of a party state, for the conduct of its business and shall have the power to amend and rescind its bylaws.

.. The board may accept for any of its purposes and functions under this compact all donations and grants of money, equipment, supplies, materials, and services, conditional or otherwise, from any state, the United States, or any governmental agency, and may receive, utilize, and dispose of the same.

.. The board may contract with or accept services or personnel from any governmental or intergovernmental agency, individual, firm, corporation, or any private nonprofit organization or institution.

.. The board shall formulate all necessary procedures and develop uniform forms and documents for administering the provisions of this compact. All procedures and forms adopted pursuant to board action shall be contained in the compact manual.

ARTICLE VIII

ENTRY INTO COMPACT AND WITHDRAWAL

.. This compact shall become effective when it has been adopted by at least two states.

.. [Empty]
. Entry into the compact shall be made by resolution of ratification executed by the authorized officials of the applying state and submitted to the chairperson of the board.

. The resolution shall be in a form and content as provided in the compact manual and shall include statements that in substance are as follows:

... A citation of the authority by which the state is empowered to become a party to this compact;

... Agreement to comply with the terms and provisions of the compact; and

... That compact entry is with all states then party to the compact and with any state that legally becomes a party to the compact.

. The effective date of entry shall be specified by the applying state, but shall not be less than sixty days after notice has been given by the chairperson of the board of compact administrators or by the secretariat of the board to each party state that the resolution from the applying state has been received.

.. A party state may withdraw from this compact by official written notice to the other party states, but a withdrawal shall not take effect until ninety days after notice of withdrawal is given. The notice shall be directed to the compact administrator of each member state. No withdrawal shall affect the validity of this compact as to the remaining party states.

ARTICLE IX

AMENDMENTS TO THE COMPACT

.. This compact may be amended from time to time. Amendments shall be presented in resolution form to the chairperson of the board of compact administrators and may be initiated by one or more party states.

.. Adoption of an amendment shall require endorsement by all party states and shall become effective thirty days after the date of the last endorsement.

.. Failure of a party state to respond to the compact chairperson within one hundred twenty days after receipt of the proposed amendment shall constitute endorsement.

ARTICLE X

CONSTRUCTION AND SEVERABILITY

This compact shall be liberally construed so as to effectuate the purposes stated herein. The provisions of this compact shall be severable and if any phrase, clause, sentence, or provision of this compact is declared to be contrary to the constitution of any party state or of the United States or the applicability thereof to any government, agency, individual, or circumstance is held invalid, the compact shall not be affected thereby. If this compact shall be held contrary to the constitution of any party state thereto, the compact shall remain in full force and effect as to the remaining states and in full force and effect as to the state affected as to all severable matters.

ARTICLE XI

TITLE

This compact shall be known as the wildlife violator compact.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2590.SL.pdf?cite=1994%20c%20264%20§%2055[1994 c 264 § 55]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1484.SL.pdf?cite=1993%20c%2082%20§%201[1993 c 82 § 1]; ]

== 77.75.080 - Licensing authority defined.
For purposes of Article VII of RCW 77.75.070, the term "licensing authority," with reference to this state, means the department. The director is authorized to appoint a compact administrator.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%20261[2000 c 107 § 261]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2590.SL.pdf?cite=1994%20c%20264%20§%2056[1994 c 264 § 56]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1484.SL.pdf?cite=1993%20c%2082%20§%202[1993 c 82 § 2]; ]

== 77.75.090 - Administration facilitation.
The director shall furnish to the appropriate authorities of the participating states any information or documents reasonably necessary to facilitate the administration of the compact.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2590.SL.pdf?cite=1994%20c%20264%20§%2057[1994 c 264 § 57]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1484.SL.pdf?cite=1993%20c%2082%20§%203[1993 c 82 § 3]; ]

== 77.75.100 - Snake river boundary—Cooperation with Idaho for adoption and enforcement of rules regarding wildlife.
The commission may cooperate with the Idaho fish and game commission in the adoption and enforcement of rules regarding wildlife on that portion of the Snake river forming the boundary between Washington and Idaho.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c78.pdf?cite=1980%20c%2078%20§%2062[1980 c 78 § 62]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c62.pdf?cite=1967%20c%2062%20§%201[1967 c 62 § 1]; ]

== 77.75.110 - Snake river boundary—Concurrent jurisdiction of Idaho and Washington courts and law enforcement officers.
To enforce RCW 77.75.120 and 77.75.130, courts in the counties contiguous to the boundary waters, fish and wildlife officers, and ex officio fish and wildlife officers have jurisdiction over the boundary waters to the furthermost shoreline. This jurisdiction is concurrent with the courts and law enforcement officers of Idaho.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%20222[2000 c 107 § 222]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c78.pdf?cite=1980%20c%2078%20§%2063[1980 c 78 § 63]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c62.pdf?cite=1967%20c%2062%20§%203[1967 c 62 § 3]; ]

== 77.75.120 - Snake river boundary—Honoring licenses to take wildlife of either state.
The taking of wildlife from the boundary waters or islands of the Snake river shall be in accordance with the wildlife laws of the respective states. Fish and wildlife officers and ex officio fish and wildlife officers shall honor the license of either state and the right of the holder to take wildlife from the boundary waters and islands in accordance with the laws of the state issuing the license.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%20223[2000 c 107 § 223]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c78.pdf?cite=1980%20c%2078%20§%2064[1980 c 78 § 64]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c62.pdf?cite=1967%20c%2062%20§%204[1967 c 62 § 4]; ]

== 77.75.130 - Snake river boundary—Purpose—Restrictions.
The purpose of RCW 77.75.100 through 77.75.130 is to avoid the conflict, confusion, and difficulty of locating the state boundary in or on the boundary waters and islands of the Snake river. These sections do not allow the holder of a Washington license to fish or hunt on the shoreline, sloughs, or tributaries on the Idaho side, nor allow the holder of an Idaho license to fish or hunt on the shoreline, sloughs, or tributaries on the Washington side.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%20224[2000 c 107 § 224]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c78.pdf?cite=1980%20c%2078%20§%2065[1980 c 78 § 65]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c62.pdf?cite=1967%20c%2062%20§%205[1967 c 62 § 5]; ]

== 77.75.140 - Treaty between United States and Canada concerning Pacific salmon.
The commission may adopt and enforce the provisions of the treaty between the government of the United States and the government of Canada concerning Pacific salmon, treaty document number 99-2, entered into force March 18, 1985, at Quebec City, Canada, and the regulations of the commission adopted under authority of the treaty.

[ 1995 1st sp.s. c 2 § 21 (Referendum Bill No. 45, approved November 7, 1995); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c130.pdf?cite=1989%20c%20130%20§%202[1989 c 130 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%20153[1983 1st ex.s. c 46 § 153]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c12.pdf?cite=1955%20c%2012%20§%2075.40.060[1955 c 12 § 75.40.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c112.pdf?cite=1949%20c%20112%20§%2083[1949 c 112 § 83]; Rem. Supp. 1949 § 5780-704; ]

== 77.75.150 - Wildlife restoration—Federal act.
The state assents to the act of congress entitled: "An Act to provide that the United States shall aid the states in wildlife restoration projects, and for other purposes," (50 Stat. 917; 16 U.S.C. Sec. 669). The department shall establish and conduct cooperative wildlife restoration projects, as defined in the act, and shall comply with the act and related rules adopted by the secretary of agriculture.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c78.pdf?cite=1980%20c%2078%20§%2060[1980 c 78 § 60]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c36.pdf?cite=1955%20c%2036%20§%2077.12.430[1955 c 36 § 77.12.430]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c140.pdf?cite=1939%20c%20140%20§%201[1939 c 140 § 1]; RRS § 5855-12; ]

== 77.75.160 - Fish restoration and management projects—Federal act.
The state assents to the act of congress entitled: "An Act to provide that the United States shall aid the states in fish restoration and management projects, and for other purposes," (64 Stat. 430; 16 U.S.C. Sec. 777). The department shall establish, conduct, and maintain fish restoration and management projects, as defined in the act, and shall comply with the act and related rules adopted by the secretary of the interior.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2055-S.SL.pdf?cite=1993%20sp.s.%20c%202%20§%2069[1993 sp.s. c 2 § 69]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c506.pdf?cite=1987%20c%20506%20§%2047[1987 c 506 § 47]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c26.pdf?cite=1982%20c%2026%20§%202[1982 c 26 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c78.pdf?cite=1980%20c%2078%20§%2061[1980 c 78 § 61]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c36.pdf?cite=1955%20c%2036%20§%2077.12.440[1955 c 36 § 77.12.440]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c124.pdf?cite=1951%20c%20124%20§%201[1951 c 124 § 1]; ]

