= 77.18 - Game fish mitigation.
:toc:

== 77.18.050 - Planting privately produced trout.
The legislature finds that it is beneficial to improve opportunities for trout fishing in order to satisfy the public's demand for recreational fishing during a time of declining opportunities to catch anadromous salmon and steelhead trout.

Fish farmers can produce trout in a triploid genetic configuration for the purpose of certifying that the fish are sterile and that they cannot interbreed with wild trout. These fish are ideally suited to planting into public lakes and ponds to provide immediate recreational fishing at a reasonable cost. The fish continue to grow throughout their life cycle and have the potential to grow to trophy size.

Planting of these catchable trout can provide increased angler participation, increased fishing license sales, increased tourism activities, and a boost to local economies.

The department of fish and wildlife is authorized to purchase these privately produced fish to supplement existing department trout hatchery production. The planting of these catchable trout in water bodies with water quality sufficient to support fish life must not have an adverse impact on the wild trout population.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1681-S2.SL.pdf?cite=1999%20c%20363%20§%201[1999 c 363 § 1]; ]

== 77.18.060 - Determination of appropriate waters.
The fish and wildlife commission in consultation with the department is authorized to determine which waters of the state are appropriate for this use. In making this determination, the commission shall seek geographic distribution to assure opportunity to fishers statewide.

The commission in consultation with the department will determine the maximum number of fish that may be planted into state waters so as not to compete with the wild populations of fish species in the water body.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5869.SL.pdf?cite=2005%20c%2087%20§%201[2005 c 87 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1681-S2.SL.pdf?cite=1999%20c%20363%20§%202[1999 c 363 § 2]; ]

