= 77.65 - Food fish and shellfish—Commercial licenses.
:toc:

== 77.65.010 - Required licenses—Exemption.
. Except as otherwise provided by this title, a person must have a license issued by the director in order to engage in any of the following activities:

.. Commercially fish for or take food fish or shellfish;

.. Deliver from a commercial fishing vessel food fish or shellfish taken for commercial purposes in offshore waters. As used in this subsection, "deliver" means arrival at a place or port, and includes arrivals from offshore waters to waters within the state and arrivals from state or offshore waters;

.. Operate a charter boat or commercial fishing vessel engaged in a fishery;

.. Engage in wholesale buying, selling, dealing, processing, or brokering of raw or frozen fish or shellfish;

.. Sell his or her commercially harvested catch of fish or shellfish to anyone other than a licensed wholesale fish buyer within or outside the state; or

.. Act as a food fish guide or game fish guide for personal use, except that a charter boat license is required to operate a vessel from which a person may for a fee fish for food fish in state waters listed in RCW 77.65.150(4)(b).

. No person may engage in the activities described in subsection (1) of this section unless the licenses required by this title are in the person's possession, and the person is the named license holder or an alternate operator designated on the license and the person's license is not suspended.

. A valid Oregon license that is equivalent to a license under this title is valid in the concurrent waters of the Columbia river if the state of Oregon recognizes as valid the equivalent Washington license. The director may identify by rule what Oregon licenses are equivalent.

. No license is required for the production or harvesting of private sector cultured aquatic products as defined in RCW 15.85.020 or for the delivery, processing, or wholesaling of such aquatic products. However, if a means of identifying such products is required by rules adopted under RCW 15.85.060, the exemption from licensing requirements established by this subsection applies only if the aquatic products are identified in conformance with those rules.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2016[2017 3rd sp.s. c 8 § 16]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5824-S.SL.pdf?cite=2015%20c%2097%20§%203[2015 c 97 § 3]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1778-S.SL.pdf?cite=2009%20c%20333%20§%207[2009 c 333 § 7]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1214-S.SL.pdf?cite=2005%20c%2020%20§%201[2005 c 20 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=1998%20c%20190%20§%2093[1998 c 190 § 93]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20883[1997 c 58 § 883]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5124.SL.pdf?cite=1993%20c%20340%20§%202[1993 c 340 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5082-S.SL.pdf?cite=1991%20c%20362%20§%201[1991 c 362 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c457.pdf?cite=1985%20c%20457%20§%2018[1985 c 457 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%20101[1983 1st ex.s. c 46 § 101]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c309.pdf?cite=1959%20c%20309%20§%202[1959 c 309 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c12.pdf?cite=1955%20c%2012%20§%2075.28.010[1955 c 12 § 75.28.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c112.pdf?cite=1949%20c%20112%20§%2073[1949 c 112 § 73]; Rem. Supp. 1949 § 5780-511; ]

== 77.65.020 - Transfer of licenses—Restrictions—Fees—Inheritability.
. Unless otherwise provided in this title, a license issued under this chapter is not transferable from the license holder to any other person. This may not be deemed to prohibit the granting or enforcement of a security interest in any such license.

. The following restrictions apply to transfers of commercial fishery licenses, salmon delivery licenses, and salmon charter licenses that are transferable between license holders:

.. The license holder shall surrender the previously issued license to the department.

.. The department shall complete no more than one transfer of the license in any seven-day period.

.. The fee to transfer a license from one license holder to another is:

... The same as the license renewal fee if the license is not limited under chapter 77.70 RCW;

... Three and one-half times the renewal fee if the license is not a commercial salmon license and the license is limited under chapter 77.70 RCW;

... Fifty dollars if the license is a commercial salmon license and is limited under chapter 77.70 RCW; or

... Five hundred dollars if the license is a Dungeness crab-coastal fishery license.

.. In addition to the fees under (c) of this subsection, an application fee of one hundred five dollars applies to all commercial license transfers.

. A commercial license that is transferable under this title survives the death of the holder. Though such licenses are not personal property, they shall be treated as analogous to personal property for purposes of inheritance, intestacy, and enforcement of security interests pursuant to Title 62A RCW. Such licenses are subject to state laws governing wills, trusts, estates, intestate succession, and community property, except that such licenses are exempt from tax liens. The surviving spouse, estate, or beneficiary of the estate may apply for a renewal of the license. There is no fee for transfer of a license from a license holder to the license holder's surviving spouse or estate, or to a beneficiary of the estate.

. Transfer of a license under this section is subject to the approval of the department according to any rules the department may adopt. Any transfer of a license issued under this chapter without the written consent of each person holding a security interest in the license is void.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1062.SL.pdf?cite=2019%20c%20200%20§%202[2019 c 200 § 2]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2017[2017 3rd sp.s. c 8 § 17]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5385-S.SL.pdf?cite=2011%20c%20339%20§%2015[2011 c 339 § 15]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2028[2000 c 107 § 28]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1770-S.SL.pdf?cite=1997%20c%20418%20§%201[1997 c 418 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5012-S.SL.pdf?cite=1995%20c%20228%20§%201[1995 c 228 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5980-S.SL.pdf?cite=1993%20sp.s.%20c%2017%20§%2034[1993 sp.s. c 17 § 34]; ]

== 77.65.030 - Commercial licenses and permits—Application deadline—Exception.
The application deadline for a commercial license or permit established in this chapter is December 31st of the calendar year for which the license or permit is sought. The department shall accept no license or permit applications after December 31st of the calendar year for which the license or permit is sought. The application deadline in this section does not apply to a license or permit that has not been renewed because of the death or incapacity of the license or permit holder. The license or permit holder's surviving spouse, estate, estate beneficiary, attorney-in-fact, or guardian must be given an additional one hundred eighty days to renew the license or permit.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1057-S.SL.pdf?cite=2003%20c%20386%20§%205[2003 c 386 § 5]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5443-S.SL.pdf?cite=2001%20c%20244%20§%202[2001 c 244 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5124.SL.pdf?cite=1993%20c%20340%20§%203[1993 c 340 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c198.pdf?cite=1986%20c%20198%20§%208[1986 c 198 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%20103[1983 1st ex.s. c 46 § 103]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c201.pdf?cite=1981%20c%20201%20§%201[1981 c 201 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c57.pdf?cite=1965%20ex.s.%20c%2057%20§%201[1965 ex.s. c 57 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c309.pdf?cite=1959%20c%20309%20§%204[1959 c 309 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c171.pdf?cite=1957%20c%20171%20§%203[1957 c 171 § 3]; ]

== 77.65.040 - Commercial licenses—Qualifications—Limited-entry license—Nonsalmon delivery license.
. Except as otherwise provided in this title, a person may hold a commercial license established by this chapter.

. Except as otherwise provided in this title, an individual may hold a commercial license only if the individual is sixteen years of age or older and a bona fide resident of the United States.

. A corporation may hold a commercial license only if it is authorized to do business in this state.

. No person may hold a limited-entry license unless the person meets the qualifications that this title establishes for the license.

. The residency requirements in subsection (2) of this section do not apply to holders of nonsalmon delivery licenses.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2029[2000 c 107 § 29]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2849.SL.pdf?cite=1994%20c%20244%20§%201[1994 c 244 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5124.SL.pdf?cite=1993%20c%20340%20§%204[1993 c 340 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c47.pdf?cite=1989%20c%2047%20§%201[1989 c 47 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%20104[1983 1st ex.s. c 46 § 104]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c171.pdf?cite=1963%20c%20171%20§%201[1963 c 171 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c12.pdf?cite=1955%20c%2012%20§%2075.28.020[1955 c 12 § 75.28.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c207.pdf?cite=1953%20c%20207%20§%209[1953 c 207 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c112.pdf?cite=1949%20c%20112%20§%2063[1949 c 112 § 63]; Rem. Supp. 1949 § 5780-501; ]

== 77.65.050 - Application for commercial licenses and permits—Replacement.
. Except as otherwise provided in this title, the director shall issue commercial licenses and permits to a qualified person upon receiving a completed application accompanied by the required fee.

. An application submitted to the department under this chapter shall contain the name and address of the applicant and any other information required by the department or this title. An applicant for a commercial fishery license or delivery license may designate a vessel to be used with the license. An applicant for a commercial fishery license or delivery license may also designate up to two alternate operators.

. An application submitted to the department under this chapter shall contain the applicant's declaration under penalty of perjury that the information on the application is true and correct.

. Upon issuing a commercial license under this chapter, the director shall assign the license a unique number that the license shall retain upon renewal. The department shall use the number to record any commercial catch under the license. This does not preclude the department from using other, additional, catch record methods.

. The fee to replace a license that has been lost or destroyed is twenty dollars.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6341-S.SL.pdf?cite=1998%20c%20267%20§%201[1998 c 267 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5980-S.SL.pdf?cite=1993%20sp.s.%20c%2017%20§%2044[1993 sp.s. c 17 § 44]; 1993 c 340 § 5; 1993 sp.s. c 17 § 47; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%20105[1983 1st ex.s. c 46 § 105]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c309.pdf?cite=1959%20c%20309%20§%207[1959 c 309 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c12.pdf?cite=1955%20c%2012%20§%2075.28.030[1955 c 12 § 75.28.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c207.pdf?cite=1953%20c%20207%20§%202[1953 c 207 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c112.pdf?cite=1949%20c%20112%20§%2065[1949 c 112 § 65]; Rem. Supp. 1949 § 5780-503; ]

== 77.65.060 - No commercial fishery during year—License requirement waived or license fees refunded.
If, for any reason, the department does not allow any opportunity for a commercial fishery during a calendar year, the director shall either: (1) Waive the requirement to obtain a license for that commercial fishery for that year; or (2) refund applicable license fees upon return of the license.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2030[2000 c 107 § 30]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5017-S.SL.pdf?cite=1995%20c%20227%20§%201[1995 c 227 § 1]; ]

== 77.65.070 - Licensees subject to statute and rules—Expiration and renewal of licenses.
. A commercial license issued under this chapter permits the license holder to engage in the activity for which the license is issued in accordance with this title and the rules of the department.

. Unless otherwise provided in this title or rules of the department, commercial licenses and permits issued under this chapter expire at midnight on December 31st of the calendar year for which they are issued. In accordance with this title, licenses may be renewed annually upon application and payment of the prescribed license fees. In accordance with RCW 77.65.030, the department must provide a license or permit holder's surviving spouse, estate, or estate beneficiary a reasonable opportunity to renew the license or permit.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1062.SL.pdf?cite=2019%20c%20200%20§%201[2019 c 200 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5443-S.SL.pdf?cite=2001%20c%20244%20§%203[2001 c 244 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2793-S.SL.pdf?cite=1996%20c%20267%20§%2027[1996 c 267 § 27]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5124.SL.pdf?cite=1993%20c%20340%20§%206[1993 c 340 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%20108[1983 1st ex.s. c 46 § 108]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c212.pdf?cite=1955%20c%20212%20§%202[1955 c 212 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c12.pdf?cite=1955%20c%2012%20§%2075.28.040[1955 c 12 § 75.28.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c112.pdf?cite=1949%20c%20112%20§%2064[1949 c 112 § 64]; Rem. Supp. 1949 § 5780-502; ]

== 77.65.080 - License suspension—Noncompliance with support order—Reissuance.
. The department shall immediately suspend the license of a person who has been certified pursuant to RCW 74.20A.320 by the department of social and health services as a person who is not in compliance with a support order.

. A listing on the department of licensing's database that an individual's license is currently suspended pursuant to RCW 46.20.291(8) shall be prima facie evidence that the individual is in noncompliance with a support order. Presentation of a written release issued by the department of social and health services or a court stating that the person is in compliance with an order shall serve as proof of compliance.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2031[2000 c 107 § 31]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20882[1997 c 58 § 882]; ]

== 77.65.090 - Vessel substitution—Fees.
This section applies to all commercial fishery licenses, delivery licenses, and charter licenses, except for emergency salmon delivery licenses.

. The holder of a license subject to this section may substitute the vessel designated on the license or designate a vessel if none has previously been designated if the license holder:

.. Surrenders the previously issued license to the department;

.. Submits to the department an application that identifies the currently designated vessel, the vessel proposed to be designated, and any other information required by the department; and

.. Pays to the department a fee of thirty-five dollars and an application fee of one hundred five dollars.

. Unless the license holder owns all vessels identified on the application described in subsection (1)(b) of this section or unless the vessel is designated on a Dungeness crab-coastal fishery license, the following restrictions apply to changes in vessel designation:

.. The department shall change the vessel designation on the license no more than four times per calendar year.

.. The department shall change the vessel designation on the license no more than once in any seven-day period.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2018[2017 3rd sp.s. c 8 § 18]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5385-S.SL.pdf?cite=2011%20c%20339%20§%2016[2011 c 339 § 16]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1471-S.SL.pdf?cite=1994%20c%20260%20§%2011[1994 c 260 § 11]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5980-S.SL.pdf?cite=1993%20sp.s.%20c%2017%20§%2045[1993 sp.s. c 17 § 45]; ]

== 77.65.100 - Vessel designation.
. This section applies to all commercial fishery licenses, delivery licenses, and charter licenses.

. An applicant for a license subject to this section may designate a vessel to be used with the license. Except for emergency salmon delivery licenses, the director may issue a license regardless of whether the applicant designates a vessel. An applicant may designate no more than one vessel on a license subject to this section.

. A license for a fishery that requires a vessel authorizes no taking or delivery of food fish or shellfish unless a vessel is designated on the license. A delivery license authorizes no delivery of food fish or shellfish unless a vessel is designated on the license.

. No vessel may be designated on more than one commercial fishery license unless the licenses are for different fisheries, except:

.. The same vessel may be designated on two of the following licenses, provided the licenses are owned by the same licensee:

... Shrimp pot-Puget Sound fishery license;

... Sea cucumber dive fishery license; and

... Sea urchin dive fishery license.

.. Subject to the provisions of RCW 77.65.130, the same vessel may be designated on three Puget Sound Dungeness crab fishery licenses issued pursuant to RCW 77.70.110.

. No vessel may be designated on more than one delivery license, on more than one salmon charter license, or on more than one nonsalmon charter license.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1075-S.SL.pdf?cite=2013%20c%20288%20§%201[2013 c 288 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5765-S.SL.pdf?cite=2005%20c%2082%20§%201[2005 c 82 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5531.SL.pdf?cite=2001%20c%20105%20§%203[2001 c 105 § 3]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=1998%20c%20190%20§%2094[1998 c 190 § 94]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5124.SL.pdf?cite=1993%20c%20340%20§%207[1993 c 340 § 7]; ]

== 77.65.110 - Alternate operator designation—Fees.
This section applies to all commercial fishery licenses and delivery licenses.

. A person designated as an alternate operator must possess an alternate operator license issued under RCW 77.65.130, and be designated on the fishery license prior to engaging in the activities authorized by the license. The holder of the commercial fishery license or delivery license may designate up to two alternate operators for the license, except:

.. Whiting—Puget Sound fishery licensees may not designate alternate operators;

.. Emergency salmon delivery licensees may not designate alternate operators;

.. Shrimp pot-Puget Sound fishery licensees may designate no more than one alternate operator at a time; and

.. Shrimp trawl-Puget Sound fishery licensees may designate no more than one alternate operator at a time.

. The fee to change the alternate operator designation is twenty-two dollars in addition to the application fee of one hundred five dollars.

. An alternate operator license is not required for an individual to operate a vessel designated as a charter boat under a charter boat license.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2019[2017 3rd sp.s. c 8 § 19]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5385-S.SL.pdf?cite=2011%20c%20339%20§%2017[2011 c 339 § 17]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5531.SL.pdf?cite=2001%20c%20105%20§%204[2001 c 105 § 4]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2032[2000 c 107 § 32]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6341-S.SL.pdf?cite=1998%20c%20267%20§%202[1998 c 267 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1471-S.SL.pdf?cite=1994%20c%20260%20§%2012[1994 c 260 § 12]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5124.SL.pdf?cite=1993%20c%20340%20§%209[1993 c 340 § 9]; ]

== 77.65.120 - Sale or delivery of fish or shellfish by fishery license holder and alternate operators—Conditions—License with a limited fish seller endorsement.
. Only the fishery license holder and any alternate operators designated on the license may sell or deliver fish or shellfish under a commercial fishery license or delivery license. A commercial fishery license or delivery license authorizes no taking or delivery of fish or shellfish unless the license holder or an alternate operator designated on the license is present or aboard the vessel.

. Only the fishery license holder and any alternate operator designated on a license with a limited fish seller endorsement under RCW 77.65.510 may sell the licensee's commercially harvested catch directly to consumers at retail.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2020[2017 3rd sp.s. c 8 § 20]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2033[2000 c 107 § 33]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6341-S.SL.pdf?cite=1998%20c%20267%20§%203[1998 c 267 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5124.SL.pdf?cite=1993%20c%20340%20§%2010[1993 c 340 § 10]; ]

== 77.65.130 - Vessel operation—License designation—Alternate operator license required.
. A person who holds a commercial fishery license or a delivery license may operate the vessel designated on the license. A person who is not the license holder may operate the vessel designated on the license only if:

.. The person holds an alternate operator license issued by the director; and

.. The person is designated as an alternate operator on the underlying commercial fishery license or delivery license under RCW 77.65.110.

. Only an individual at least sixteen years of age may hold an alternate operator license.

. No individual may hold more than one alternate operator license. An individual who holds an alternate operator license may be designated as an alternate operator on an unlimited number of commercial fishery licenses or delivery licenses under RCW 77.65.110.

. An individual who holds multiple Dungeness crab—Puget Sound fishery licenses issued pursuant to RCW 77.70.110 may operate the licenses on one vessel if the license holder or alternate operator is on the vessel. The department shall allow a license holder to operate up to one hundred crab pots for each license.

. Two persons owning separate Dungeness crab—Puget Sound fishery licenses may operate their licenses on one vessel if the license holders or their alternate operators are on the vessel.

. As used in this section, to "operate" means to control the deployment or removal of fishing gear from state waters while aboard a vessel or to operate a vessel delivering food fish or shellfish taken in offshore waters to a port within the state.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1075-S.SL.pdf?cite=2013%20c%20288%20§%202[2013 c 288 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5765-S.SL.pdf?cite=2005%20c%2082%20§%202[2005 c 82 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2034[2000 c 107 § 34]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6341-S.SL.pdf?cite=1998%20c%20267%20§%204[1998 c 267 § 4]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2149-S.SL.pdf?cite=1997%20c%20233%20§%202[1997 c 233 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5124.SL.pdf?cite=1993%20c%20340%20§%2025[1993 c 340 § 25]; ]

== 77.65.140 - Alternate operators—Increase for certain licenses.
The director may, by rule, increase the number of alternate operators beyond the level authorized by RCW 77.65.050 and 77.65.110 for a commercial fishery license, delivery license, or charter license.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2035[2000 c 107 § 35]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5103-S.SL.pdf?cite=1997%20c%20421%20§%201[1997 c 421 § 1]; ]

== 77.65.150 - Licenses and permits—Fees—"Charter boat" defined—Oregon charter boats—Salmon charter license renewal.
. The licenses and permits and their annual license fees, application fees, and surcharges are:

 LicenseorPermitAnnual Fee(RCW 77.95.090 Surcharge)(RCW 77.12.702 Surcharge)Appli-cation FeeGoverningSection  ResidentNonresident  (a)Non-salmon charter$375(plus $35 for RCW 77.12.702 Surcharge)$760(plus $35 for RCW 77.12.702 Surcharge)$ 70 (b)Salmon charter$460(plus $100)(plus $35 for RCW 77.12.702 Surcharge)$845(plus $100)(plus $35 for RCW 77.12.702 Surcharge)$105RCW 77.70.050(c)Salmon angler$ 0$ 0$ 0RCW 77.70.060

 

License

or

Permit

Annual Fee

(RCW 77.95.090 Surcharge)

(RCW 77.12.702 Surcharge)

Appli-cation Fee

Governing

Section

 

 

Resident

Nonresident

 

 

..

Non-salmon charter

$375

(plus $35 for RCW 77.12.702 Surcharge)

$760

(plus $35 for RCW 77.12.702 Surcharge)

$ 70

 

..

Salmon charter

$460

(plus $100)

(plus $35 for RCW 77.12.702 Surcharge)

$845

(plus $100)

(plus $35 for RCW 77.12.702 Surcharge)

$105

RCW 77.70.050

..

Salmon angler

$ 0

$ 0

$ 0

RCW 77.70.060

. A salmon charter license designating a vessel is required to operate a charter boat from which persons may, for a fee, fish for salmon, other fish, and shellfish. The director may issue a salmon charter license only to a person who meets the qualifications of RCW 77.70.050.

. A nonsalmon charter license designating a vessel is required to operate a charter boat from which persons may, for a fee, fish for shellfish and fish other than salmon or albacore tuna.

. [Empty]
.. "Charter boat" means a vessel from which persons may, for a fee, fish for food fish or shellfish for personal use in those state waters set forth in (b) of this subsection. "Charter boat" also means a vessel from which persons may, for a fee, fish for fish or shellfish for personal use in offshore waters or in the waters of other states. The director may specify by rule when a vessel is a "charter boat" within this definition.

.. A person may not operate a vessel from which persons may, for a fee, fish for food fish or shellfish in Puget Sound, Grays Harbor, Willapa Bay, Pacific Ocean waters, Lake Washington, or the Columbia river below the bridge at Longview unless the vessel is designated on a charter boat license.

. A charter boat licensed in Oregon may fish without a Washington charter license under the same rules as Washington charter boat operators in ocean waters within the jurisdiction of Washington state from the southern border of the state of Washington to Leadbetter Point, as long as the Oregon vessel does not take on or discharge passengers for any purpose from any Washington port, the Washington shore, or a dock, landing, or other point in Washington. The provisions of this subsection shall be in effect as long as the state of Oregon has reciprocal laws and regulations.

. A salmon charter license under subsection (1)(b) of this section may be renewed if the license holder notifies the department by May 1st of that year that he or she will not participate in the fishery during that calendar year. The license holder must pay the one hundred dollar enhancement surcharge, a thirty-five dollar surcharge to be deposited in the rockfish research account created in RCW 77.12.702, plus a one hundred five dollar application fee, in order to be considered a valid renewal and eligible to renew the license the following year.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6317-S.SL.pdf?cite=2018%20c%20235%20§%201[2018 c 235 § 1]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2021[2017 3rd sp.s. c 8 § 21]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5385-S.SL.pdf?cite=2011%20c%20339%20§%2018[2011 c 339 § 18]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1476.SL.pdf?cite=2007%20c%20442%20§%203[2007 c 442 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6401-S.SL.pdf?cite=2006%20c%20186%20§%201[2006 c 186 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2036[2000 c 107 § 36]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=1998%20c%20190%20§%2095[1998 c 190 § 95]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5360-S.SL.pdf?cite=1997%20c%2076%20§%202[1997 c 76 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1226.SL.pdf?cite=1995%20c%20104%20§%201[1995 c 104 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5980-S.SL.pdf?cite=1993%20sp.s.%20c%2017%20§%2041[1993 sp.s. c 17 § 41]; 1993 c 340 § 21; 1993 sp.s. c 17 § 47; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c316.pdf?cite=1989%20c%20316%20§%202[1989 c 316 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c147.pdf?cite=1989%20c%20147%20§%201[1989 c 147 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c47.pdf?cite=1989%20c%2047%20§%202[1989 c 47 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c9.pdf?cite=1988%20c%209%20§%201[1988 c 9 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%20112[1983 1st ex.s. c 46 § 112]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c60.pdf?cite=1979%20c%2060%20§%201[1979 c 60 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c327.pdf?cite=1977%20ex.s.%20c%20327%20§%205[1977 ex.s. c 327 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c283.pdf?cite=1971%20ex.s.%20c%20283%20§%2015[1971 ex.s. c 283 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c90.pdf?cite=1969%20c%2090%20§%201[1969 c 90 § 1]; ]

== 77.65.160 - Commercial salmon fishery licenses—Gear and geographic designations—Fees.
. The following commercial salmon fishery licenses are required for the license holder to use the specified gear to fish for salmon in state waters. Only a person who meets the qualifications of RCW 77.70.090 may hold a license listed in this subsection. The licenses and their annual license fees, application fees, and surcharges under RCW 77.95.090 are:

 FisheryLicenseResidentFeeNonresidentFeeSurchargeApplication Fee(a)Salmon Gill Net—Grays Harbor-Columbia river$380$765plus $100$105(b)Salmon Gill Net—Puget Sound$380$765plus $100$105(c)Salmon Gill Net—Willapa Bay-Columbia river$380$765plus $100$105(d)Salmon purse seine$545$930plus $100$105(e)Salmon reef net$380$765plus $100$105(f)Salmon troll$380$765plus $100$105

 

Fishery

License

Resident

Fee

Nonresident

Fee

Surcharge

Application Fee

..

Salmon Gill Net—Grays Harbor-Columbia river

$380

$765

plus $100

$105

..

Salmon Gill Net—Puget Sound

$380

$765

plus $100

$105

..

Salmon Gill Net—Willapa Bay-Columbia river

$380

$765

plus $100

$105

..

Salmon purse seine

$545

$930

plus $100

$105

..

Salmon reef net

$380

$765

plus $100

$105

..

Salmon troll

$380

$765

plus $100

$105

. A license issued under this section authorizes no taking or delivery of salmon or other food fish unless a vessel is designated under RCW 77.65.100.

. Holders of commercial salmon fishery licenses may retain incidentally caught food fish other than salmon, subject to rules of the department.

. A salmon troll license includes a salmon delivery license.

. A salmon gill net license authorizes the taking of salmon only in the geographical area for which the license is issued. The geographical designations in subsection (1) of this section have the following meanings:

.. "Puget Sound" includes waters of the Strait of Juan de Fuca, Georgia Strait, Puget Sound and all bays, inlets, canals, coves, sounds, and estuaries lying easterly and southerly of the international boundary line and a line at the entrance to the Strait of Juan de Fuca projected northerly from Cape Flattery to the lighthouse on Tatoosh Island and then to Bonilla Point on Vancouver Island.

.. "Grays Harbor-Columbia river" includes waters of Grays Harbor and tributary estuaries lying easterly of a line projected northerly from Point Chehalis Light to Point Brown and those waters of the Columbia river and tributary sloughs and estuaries easterly of a line at the entrance to the Columbia river projected southerly from the most westerly point of the North jetty to the most westerly point of the South jetty.

.. "Willapa Bay-Columbia river" includes waters of Willapa Bay and tributary estuaries and easterly of a line projected northerly from Leadbetter Point to the Cape Shoalwater tower and those waters of the Columbia river and tributary sloughs described in (b) of this subsection.

. A commercial salmon troll fishery license may be renewed under this section if the license holder notifies the department by May 1st of that year that he or she will not participate in the fishery during that calendar year. A commercial salmon gill net, reef net, or seine fishery license may be renewed under this section if the license holder notifies the department before the third Monday in September of that year that he or she will not participate in the fishery during that calendar year. The license holder must pay the one hundred dollar enhancement surcharge, plus a one hundred five dollar application fee before the third Monday in September, in order to be considered a valid renewal and eligible to renew the license the following year.

. Notwithstanding the annual license fees and surcharges established in subsection (1) of this section, a person who holds a resident commercial salmon fishery license shall pay an annual license fee of one hundred dollars plus the surcharge and application fee if all of the following conditions are met:

.. The license holder is at least seventy-five years of age;

.. The license holder owns a fishing vessel and has fished with a resident commercial salmon fishery license for at least thirty years; and

.. The commercial salmon fishery license is for a geographical area other than the Puget Sound.

An alternate operator may not be designated for a license renewed at the one hundred dollar annual fee under this subsection (7).

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6317-S.SL.pdf?cite=2018%20c%20235%20§%202[2018 c 235 § 2]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2022[2017 3rd sp.s. c 8 § 22]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5385-S.SL.pdf?cite=2011%20c%20339%20§%2019[2011 c 339 § 19]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5443-S.SL.pdf?cite=2001%20c%20244%20§%201[2001 c 244 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2037[2000 c 107 § 37]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5360-S.SL.pdf?cite=1997%20c%2076%20§%201[1997 c 76 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2793-S.SL.pdf?cite=1996%20c%20267%20§%2028[1996 c 267 § 28]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5980-S.SL.pdf?cite=1993%20sp.s.%20c%2017%20§%2035[1993 sp.s. c 17 § 35]; 1993 c 340 § 12; 1993 sp.s. c 17 § 47; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c316.pdf?cite=1989%20c%20316%20§%203[1989 c 316 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c107.pdf?cite=1985%20c%20107%20§%201[1985 c 107 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%20113[1983 1st ex.s. c 46 § 113]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c73.pdf?cite=1965%20ex.s.%20c%2073%20§%202[1965 ex.s. c 73 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c309.pdf?cite=1959%20c%20309%20§%2010[1959 c 309 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c12.pdf?cite=1955%20c%2012%20§%2075.28.110[1955 c 12 § 75.28.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c271.pdf?cite=1951%20c%20271%20§%209[1951 c 271 § 9]; 1949 c 112 § 69; Rem. Supp. 1949 § 5780-507; ]

== 77.65.170 - Salmon delivery license—Fees—Restrictions—Revocation.
. A salmon delivery license is required for a commercial fishing vessel to deliver salmon taken for commercial purposes in offshore waters to a place or port in the state. As used in this section, "deliver" and "delivery" mean arrival at a place or port, and include arrivals from offshore waters to waters within the state and arrivals ashore from offshore waters. The annual fee for a salmon delivery license is four hundred thirty dollars for residents and eight hundred fifteen dollars for nonresidents. The application fee for a salmon delivery license is one hundred five dollars. The annual surcharge under RCW 77.95.090 is one hundred dollars for each license. Holders of nonlimited entry delivery licenses issued under RCW 77.65.210 may apply the nonlimited entry delivery license fee against the salmon delivery license fee.

. Only a person who meets the qualifications established in RCW 77.70.090 may hold a salmon delivery license issued under this section.

. A salmon delivery license authorizes no taking of salmon or other fish or shellfish from the waters of the state.

. If the director determines that the operation of a vessel under a salmon delivery license results in the depletion or destruction of the state's salmon resource or the delivery into this state of salmon products prohibited by law, the director may revoke the license under the procedures of chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6317-S.SL.pdf?cite=2018%20c%20235%20§%203[2018 c 235 § 3]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2023[2017 3rd sp.s. c 8 § 23]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5385-S.SL.pdf?cite=2011%20c%20339%20§%2020[2011 c 339 § 20]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1214-S.SL.pdf?cite=2005%20c%2020%20§%202[2005 c 20 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2038[2000 c 107 § 38]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=1998%20c%20190%20§%2096[1998 c 190 § 96]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1471-S.SL.pdf?cite=1994%20c%20260%20§%2022[1994 c 260 § 22]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5980-S.SL.pdf?cite=1993%20sp.s.%20c%2017%20§%2036[1993 sp.s. c 17 § 36]; 1993 c 340 § 13; 1993 sp.s. c 17 § 47; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c316.pdf?cite=1989%20c%20316%20§%204[1989 c 316 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%20115[1983 1st ex.s. c 46 § 115]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c327.pdf?cite=1977%20ex.s.%20c%20327%20§%203[1977 ex.s. c 327 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c283.pdf?cite=1971%20ex.s.%20c%20283%20§%201[1971 ex.s. c 283 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c12.pdf?cite=1955%20c%2012%20§%2075.18.080[1955 c 12 § 75.18.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c147.pdf?cite=1953%20c%20147%20§%209[1953 c 147 § 9]; ]

== 77.65.180 - Oregon, California harvested salmon—Landing in Washington ports encouraged.
. The legislature finds that landing salmon into the ports of Washington state, regardless of where such salmon have been harvested, is economically beneficial to those ports as well as to the citizens of the state of Washington. It is therefore the intent of the legislature to encourage this practice.

. Notwithstanding the provisions of RCW 77.65.010(1)(b) and 77.65.170, a Washington citizen who holds a valid Oregon or California salmon troll license may land salmon taken during lawful seasons in Oregon and California into Washington ports without obtaining a salmon delivery license. This exception is valid only when the salmon were taken in offshore waters south of Cape Falcon.

. The department shall adopt rules necessary to implement this section, including rules identifying the appropriate methods for verifying that salmon were in fact taken south of Cape Falcon.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2039[2000 c 107 § 39]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1490-S.SL.pdf?cite=1999%20c%20103%20§%201[1999 c 103 § 1]; ]

== 77.65.190 - Emergency salmon delivery license—Fees—Nontransferable, nonrenewable.
A person who does not qualify for a license under RCW 77.70.090 shall obtain a nontransferable emergency salmon delivery license to make one delivery from a commercial fishing vessel of salmon taken for commercial purposes in offshore waters. As used in this section, "delivery" means arrival at a place or port, and include arrivals from offshore waters to waters within the state and arrivals ashore from offshore waters. The director shall not issue an emergency salmon delivery license unless, as determined by the director, a bona fide emergency exists. The license fee is two hundred seventy-five dollars for residents and six hundred sixty dollars for nonresidents. The application fee is one hundred five dollars. An applicant for an emergency salmon delivery license shall designate no more than one vessel that will be used with the license. Alternate operator licenses are not required of persons delivering salmon under an emergency salmon delivery license. Emergency salmon delivery licenses are not renewable.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6317-S.SL.pdf?cite=2018%20c%20235%20§%204[2018 c 235 § 4]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2024[2017 3rd sp.s. c 8 § 24]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5385-S.SL.pdf?cite=2011%20c%20339%20§%2021[2011 c 339 § 21]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1214-S.SL.pdf?cite=2005%20c%2020%20§%203[2005 c 20 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2040[2000 c 107 § 40]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5980-S.SL.pdf?cite=1993%20sp.s.%20c%2017%20§%2037[1993 sp.s. c 17 § 37]; 1993 c 340 § 14; 1993 sp.s. c 17 § 47; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c316.pdf?cite=1989%20c%20316%20§%205[1989 c 316 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c80.pdf?cite=1984%20c%2080%20§%201[1984 c 80 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%20116[1983 1st ex.s. c 46 § 116]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c297.pdf?cite=1983%20c%20297%20§%201[1983 c 297 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c327.pdf?cite=1977%20ex.s.%20c%20327%20§%204[1977 ex.s. c 327 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c184.pdf?cite=1974%20ex.s.%20c%20184%20§%203[1974 ex.s. c 184 § 3]; ]

== 77.65.200 - Commercial fishery licenses for food fish fisheries—Fees—Rules for species, gear, and areas.
. This section establishes commercial fishery licenses required for food fish fisheries and the annual fees for those licenses. As used in this section, "food fish" does not include salmon. The director may issue a limited-entry commercial fishery license only to a person who meets the qualifications established in applicable governing sections of this title.

Fishery(Governing section(s))Annual FeeApplication FeeVesselRequired?LimitedEntry? ResidentNonresident   (a) Baitfish Lampara$335$720$ 70YesNo(b) Baitfish purse seine$380$765$ 70YesNo(c) Bottom fish jig$180$565$ 70YesNo(d) Bottom fish pot$180$565$ 70YesNo(e) Bottom fish troll$180$565$ 70YesNo(f) Carp$180$565$ 70NoNo(g) Columbia river smelt$430$815$ 70NoNo(h) Emerging commercial fishery (RCW 77.70.160 and 77.65.400)$335$720$105Determined by ruleDetermined by rule(i) Food fish drag seine$180$565$ 70YesNo(j) Food fish set line$180$565$ 70YesNo(k) Herring dip bag net$325$710$ 70YesYes(RCW 77.70.120)     (l) Herring drag seine$325$710$ 70YesYes(RCW 77.70.120)     (m) Herring gill net$325$710$105YesYes(RCW 77.70.120)     (n) Herring Lampara$325$710$ 70YesYes(RCW 77.70.120)     (o) Herring purse seine$325$710$105YesYes(RCW 77.70.120)     (p) Herring spawn-on-kelp (RCW 77.70.210)N/AN/AN/AYesYes(q) Sardine purse seine (RCW 77.70.480)$335$720$105YesYes(r) Sardine purse seine temporary (RCW 77.70.480)$335$720$105YesNo(s) Smelt dip bag net$180$565$ 70NoNo(t) Smelt gill net$430$815$ 70YesNo(u) Whiting-Puget Sound (RCW 77.70.130)$345$730$105YesYes

Fishery

(Governing section(s))

Annual Fee

Application Fee

Vessel

Required?

Limited

Entry?

 

Resident

Nonresident

 

 

 

.. Baitfish Lampara

$335

$720

$ 70

Yes

No

.. Baitfish purse seine

$380

$765

$ 70

Yes

No

.. Bottom fish jig

$180

$565

$ 70

Yes

No

.. Bottom fish pot

$180

$565

$ 70

Yes

No

.. Bottom fish troll

$180

$565

$ 70

Yes

No

.. Carp

$180

$565

$ 70

No

No

.. Columbia river smelt

$430

$815

$ 70

No

No

.. Emerging commercial fishery (RCW 77.70.160 and 77.65.400)

$335

$720

$105

Determined by rule

Determined by rule

.. Food fish drag seine

$180

$565

$ 70

Yes

No

.. Food fish set line

$180

$565

$ 70

Yes

No

.. Herring dip bag net

$325

$710

$ 70

Yes

Yes

(RCW 77.70.120)

 

 

 

 

 

.. Herring drag seine

$325

$710

$ 70

Yes

Yes

(RCW 77.70.120)

 

 

 

 

 

.. Herring gill net

$325

$710

$105

Yes

Yes

(RCW 77.70.120)

 

 

 

 

 

.. Herring Lampara

$325

$710

$ 70

Yes

Yes

(RCW 77.70.120)

 

 

 

 

 

.. Herring purse seine

$325

$710

$105

Yes

Yes

(RCW 77.70.120)

 

 

 

 

 

.. Herring spawn-on-kelp (RCW 77.70.210)

N/A

N/A

N/A

Yes

Yes

.. Sardine purse seine (RCW 77.70.480)

$335

$720

$105

Yes

Yes

.. Sardine purse seine temporary (RCW 77.70.480)

$335

$720

$105

Yes

No

.. Smelt dip bag net

$180

$565

$ 70

No

No

.. Smelt gill net

$430

$815

$ 70

Yes

No

.. Whiting-Puget Sound (RCW 77.70.130)

$345

$730



$105

Yes



Yes

. The director may by rule determine the species of food fish that may be taken with the commercial fishery licenses established in this section, the gear that may be used with the licenses, and the areas or waters in which the licenses may be used. Where a fishery license has been established for a particular species, gear, geographical area, or combination thereof, a more general fishery license may not be used to take food fish in that fishery.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6317-S.SL.pdf?cite=2018%20c%20235%20§%205[2018 c 235 § 5]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2025[2017 3rd sp.s. c 8 § 25]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5385-S.SL.pdf?cite=2011%20c%20339%20§%2022[2011 c 339 § 22]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1326-S.SL.pdf?cite=2009%20c%20331%20§%204[2009 c 331 § 4]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2041[2000 c 107 § 41]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5980-S.SL.pdf?cite=1993%20sp.s.%20c%2017%20§%2038[1993 sp.s. c 17 § 38]; 1993 c 340 § 15; 1993 sp.s. c 17 § 47; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c316.pdf?cite=1989%20c%20316%20§%206[1989 c 316 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%20117[1983 1st ex.s. c 46 § 117]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c73.pdf?cite=1965%20ex.s.%20c%2073%20§%203[1965 ex.s. c 73 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c309.pdf?cite=1959%20c%20309%20§%2011[1959 c 309 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c12.pdf?cite=1955%20c%2012%20§%2075.28.120[1955 c 12 § 75.28.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c271.pdf?cite=1951%20c%20271%20§%2010[1951 c 271 § 10]; 1949 c 112 § 69; Rem. Supp. 1949 § 5780-507; ]

== 77.65.210 - Nonlimited entry delivery license—Exceptions—Fees.
. Except as provided in subsection (2) of this section, a person may not use a commercial fishing vessel to deliver food fish or shellfish taken for commercial purposes in offshore waters to a port in the state without a nonlimited entry delivery license. As used in this section, "deliver" and "delivery" mean arrival at a place or port, and include arrivals from offshore waters to waters within the state and arrivals ashore from offshore waters. As used in this section, "food fish" does not include salmon. As used in this section, "shellfish" does not include ocean pink shrimp, coastal crab, coastal spot shrimp, or fish or shellfish taken under an emerging commercial fisheries license if taken from offshore waters. The annual license fee for a nonlimited entry delivery license is two hundred sixty dollars for residents and six hundred forty-five dollars for nonresidents, and an additional thirty-five dollar surcharge for both residents and nonresidents to be deposited in the rockfish research account created in RCW 77.12.702. The application fee for a nonlimited entry delivery license is one hundred five dollars.

. Holders of the following licenses may deliver food fish or shellfish taken in offshore waters without a nonlimited entry delivery license: Salmon troll fishery licenses issued under RCW 77.65.160; salmon delivery licenses issued under RCW 77.65.170; crab pot fishery licenses issued under RCW 77.65.220; food fish trawl—Non-Puget Sound fishery licenses, and emerging commercial fishery licenses issued under RCW 77.65.200; Dungeness crab—coastal fishery licenses; ocean pink shrimp delivery licenses; Washington coastal spot shrimp pot fishery licenses issued under chapter 77.70 RCW; and emerging commercial fishery licenses issued under RCW 77.65.220.

. A nonlimited entry delivery license authorizes no taking of fish or shellfish from state waters.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6317-S.SL.pdf?cite=2018%20c%20235%20§%206[2018 c 235 § 6]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2026[2017 3rd sp.s. c 8 § 26]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5385-S.SL.pdf?cite=2011%20c%20339%20§%2023[2011 c 339 § 23]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1148-S.SL.pdf?cite=2011%20c%20147%20§%203[2011 c 147 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1476.SL.pdf?cite=2007%20c%20442%20§%204[2007 c 442 § 4]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1214-S.SL.pdf?cite=2005%20c%2020%20§%204[2005 c 20 § 4]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2042[2000 c 107 § 42]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=1998%20c%20190%20§%2097[1998 c 190 § 97]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1471-S.SL.pdf?cite=1994%20c%20260%20§%2021[1994 c 260 § 21]; prior:  1993 sp.s. c 17 § 39; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1350-S.SL.pdf?cite=1993%20c%20376%20§%203[1993 c 376 § 3]; 1993 c 340 § 16; 1993 sp.s. c 17 § 47; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c316.pdf?cite=1989%20c%20316%20§%207[1989 c 316 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%20119[1983 1st ex.s. c 46 § 119]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c283.pdf?cite=1971%20ex.s.%20c%20283%20§%205[1971 ex.s. c 283 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c73.pdf?cite=1965%20ex.s.%20c%2073%20§%201[1965 ex.s. c 73 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c309.pdf?cite=1959%20c%20309%20§%205[1959 c 309 § 5]; ]

== 77.65.220 - Commercial fishery licenses for shellfish fisheries—Fees—Rules for species, gear, and areas.
. This section establishes commercial fishery licenses required for shellfish fisheries and the annual fees for those licenses. The director may issue a limited-entry commercial fishery license only to a person who meets the qualifications established in applicable governing sections of this title.

Fishery(Governing section(s))Annual FeeApplication FeeVesselRequired?LimitedEntry? ResidentNonresident   (a) Burrowing shrimp$235$620$105YesNo(b) Crab ring net-$180$565$ 70YesNoPuget Sound     (c) Dungeness crab-coastal (RCW 77.70.280)$345$730$105YesYes(d) Dungeness crab-$180$565$105YesYesPuget Sound     (RCW 77.70.110)     (e) Emerging commercial fishery (RCW 77.70.160 and 77.65.400)$335$720$105Determinedby ruleDeterminedby rule(f) Geoduck (RCW$ 0$ 0$ 70YesYes77.70.220)     (g) Hardshell clam$580$965$ 70YesNomechanicalharvester     (RCW 77.65.250)     (h) Oyster reserve$180$565$ 70NoNo(RCW 77.65.260)     (i) Razor clam$180$565$105NoNo(j) Sea cucumber dive$280$665$105YesYes(RCW 77.70.190)     (k) Sea urchin dive$280$665$105YesYes(RCW 77.70.150)     (l) Shellfish dive$180$565$ 70YesNo(m) Shellfish pot$180$565$ 70YesNo(n) Shrimp pot-$335$720$105YesYesPuget Sound     (RCW 77.70.410)     (o) Shrimp trawl-$335$720$105YesYesPuget Sound     (RCW 77.70.420)     (p) Spot shrimp-coastal$335$720$ 70YesYes(q) Squid$335$720$ 70YesNo

Fishery

(Governing section(s))

Annual Fee

Application Fee

Vessel

Required?

Limited

Entry?

 

Resident

Nonresident

 

 

 

.. Burrowing shrimp

$235

$620

$105

Yes

No

.. Crab ring net-

$180

$565

$ 70

Yes

No

Puget Sound

 

 

 

 

 

.. Dungeness crab-coastal (RCW 77.70.280)

$345

$730

$105

Yes

Yes

.. Dungeness crab-

$180

$565

$105

Yes

Yes

Puget Sound

 

 

 

 

 

(RCW 77.70.110)

 

 

 

 

 

.. Emerging commercial fishery (RCW 77.70.160 and 77.65.400)

$335

$720

$105

Determined

by rule

Determined

by rule

.. Geoduck (RCW

$ 0

$ 0

$ 70

Yes

Yes

77.70.220)

 

 

 

 

 

.. Hardshell clam

$580

$965

$ 70

Yes

No

mechanical

harvester

 

 

 

 

 

(RCW 77.65.250)

 

 

 

 

 

.. Oyster reserve

$180

$565

$ 70

No

No

(RCW 77.65.260)

 

 

 

 

 

.. Razor clam

$180

$565

$105

No

No

.. Sea cucumber dive

$280

$665

$105

Yes

Yes

(RCW 77.70.190)

 

 

 

 

 

.. Sea urchin dive

$280

$665

$105

Yes

Yes

(RCW 77.70.150)

 

 

 

 

 

.. Shellfish dive

$180

$565

$ 70

Yes

No

.. Shellfish pot

$180

$565

$ 70

Yes

No

.. Shrimp pot-

$335

$720

$105

Yes

Yes

Puget Sound

 

 

 

 

 

(RCW 77.70.410)

 

 

 

 

 

.. Shrimp trawl-

$335

$720

$105

Yes

Yes

Puget Sound

 

 

 

 

 

(RCW 77.70.420)

 

 

 

 

 

.. Spot shrimp-coastal

$335

$720

$ 70

Yes

Yes

.. Squid

$335

$720

$ 70

Yes

No

. The director may by rule determine the species of shellfish that may be taken with the commercial fishery licenses established in this section, the gear that may be used with the licenses, and the areas or waters in which the licenses may be used. Where a fishery license has been established for a particular species, gear, geographical area, or combination thereof, a more general fishery license may not be used to take shellfish in that fishery.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6317-S.SL.pdf?cite=2018%20c%20235%20§%207[2018 c 235 § 7]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2027[2017 3rd sp.s. c 8 § 27]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5385-S.SL.pdf?cite=2011%20c%20339%20§%2024[2011 c 339 § 24]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1148-S.SL.pdf?cite=2011%20c%20147%20§%204[2011 c 147 § 4]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2043[2000 c 107 § 43]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2107-S.SL.pdf?cite=1999%20c%20239%20§%202[1999 c 239 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1471-S.SL.pdf?cite=1994%20c%20260%20§%2014[1994 c 260 § 14]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5980-S.SL.pdf?cite=1993%20sp.s.%20c%2017%20§%2040[1993 sp.s. c 17 § 40]; 1993 c 340 § 17; 1993 sp.s. c 17 § 47; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c316.pdf?cite=1989%20c%20316%20§%208[1989 c 316 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%20120[1983 1st ex.s. c 46 § 120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c327.pdf?cite=1977%20ex.s.%20c%20327%20§%206[1977 ex.s. c 327 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c283.pdf?cite=1971%20ex.s.%20c%20283%20§%207[1971 ex.s. c 283 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c73.pdf?cite=1965%20ex.s.%20c%2073%20§%204[1965 ex.s. c 73 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c309.pdf?cite=1959%20c%20309%20§%2012[1959 c 309 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c12.pdf?cite=1955%20c%2012%20§%2075.28.130[1955 c 12 § 75.28.130]; prior:  1951 c 271 § 11; 1949 c 112 § 69(3); Rem. Supp. 1949 § 5780-507(3); ]

== 77.65.240 - Surcharge on Dungeness crab-coastal fishery license.
A surcharge of one hundred twenty dollars shall be collected with each Dungeness crab-coastal fishery license issued under RCW 77.65.220. Moneys collected under this section shall be placed in the coastal crab account created under RCW 77.70.320.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2028[2017 3rd sp.s. c 8 § 28]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2045[2000 c 107 § 45]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1770-S.SL.pdf?cite=1997%20c%20418%20§%205[1997 c 418 § 5]; ]

== 77.65.250 - Hardshell clam mechanical harvester fishery license.
A hardshell clam mechanical harvester fishery license is required to operate a mechanical or hydraulic device for commercially harvesting clams, other than geoduck clams, unless the requirements of RCW 77.55.021 are fulfilled for the proposed activity.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1346-S2.SL.pdf?cite=2005%20c%20146%20§%201005[2005 c 146 § 1005]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2046[2000 c 107 § 46]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5124.SL.pdf?cite=1993%20c%20340%20§%2019[1993 c 340 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c316.pdf?cite=1989%20c%20316%20§%2012[1989 c 316 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c457.pdf?cite=1985%20c%20457%20§%2019[1985 c 457 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%20125[1983 1st ex.s. c 46 § 125]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c141.pdf?cite=1979%20ex.s.%20c%20141%20§%203[1979 ex.s. c 141 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c253.pdf?cite=1969%20ex.s.%20c%20253%20§%203[1969 ex.s. c 253 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c212.pdf?cite=1955%20c%20212%20§%208[1955 c 212 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c12.pdf?cite=1955%20c%2012%20§%2075.28.280[1955 c 12 § 75.28.280]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c271.pdf?cite=1951%20c%20271%20§%2026[1951 c 271 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c112.pdf?cite=1949%20c%20112%20§%2070[1949 c 112 § 70]; Rem. Supp. 1949 § 5780-508; ]

== 77.65.260 - State oyster reserves—Oyster reserve fishery license.
A person who commercially takes shellfish from state oyster reserves under RCW 77.60.050 must have an oyster reserve fishery license.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2047[2000 c 107 § 47]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5124.SL.pdf?cite=1993%20c%20340%20§%2020[1993 c 340 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c316.pdf?cite=1989%20c%20316%20§%2014[1989 c 316 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%20131[1983 1st ex.s. c 46 § 131]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c91.pdf?cite=1969%20ex.s.%20c%2091%20§%202[1969 ex.s. c 91 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c12.pdf?cite=1955%20c%2012%20§%2075.28.290[1955 c 12 § 75.28.290]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c271.pdf?cite=1951%20c%20271%20§%2027[1951 c 271 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c112.pdf?cite=1949%20c%20112%20§%2071[1949 c 112 § 71]; Rem. Supp. 1949 § 5780-509; ]

== 77.65.270 - Oyster cultch permit.
An oyster cultch permit is required for commercial cultching of oysters on state oyster reserves. The director shall require that ten percent of the cultch bags or other collecting materials be provided to the state after the oysters have set, for the purposes of increasing the supply of oysters on state oyster reserves and enhancing oyster supplies on public beaches.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c316.pdf?cite=1989%20c%20316%20§%2015[1989 c 316 § 15]; ]

== 77.65.280 - Fish dealer license—Exemption—Fees.
. A fish dealer license is required for a person in the state who:

.. Takes possession of raw or frozen fish or shellfish, in whole or in parts, to prepare, repackage, process, or preserve. This includes, but is not limited to:

... Canning or processing of fish or shellfish for payment, whether the fish or shellfish is commercially harvested or taken for personal use; and

... The commercial manufacture or preparation of fertilizer, oil, meal, caviar, fish bait, or any other by-products from fish or shellfish;

.. Engages in the wholesale selling, buying, or brokering of raw or frozen fish or shellfish. Certain buyers may be additionally required to obtain a wholesale fish buyer endorsement as specified in RCW 77.65.340.

. A fish dealer license is not required for:

.. Licensed commercial fish or shellfish harvesters who either sell only to licensed wholesale fish buyers or who possess a limited fish seller endorsement;

.. Retail businesses that purchase exclusively from Washington licensed wholesale fish buyers or from limited fish sellers for sale to end consumers.

. A business engaged in any activity requiring a fish dealer license only needs to purchase one fish dealer license to cover the actions of all employees.

. The annual license fee for a resident fish dealer is four hundred dollars. The fee for a nonresident fish dealer license is seven hundred eighty-five dollars. The application fee for both resident and nonresident licenses is one hundred five dollars.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6317-S.SL.pdf?cite=2018%20c%20235%20§%208[2018 c 235 § 8]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2029[2017 3rd sp.s. c 8 § 29]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6041-S.SL.pdf?cite=2014%20c%2048%20§%2027[2014 c 48 § 27]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20244[2013 c 23 § 244]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5385-S.SL.pdf?cite=2011%20c%20339%20§%2025[2011 c 339 § 25]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2323-S.SL.pdf?cite=2002%20c%20301%20§%205[2002 c 301 § 5]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2048[2000 c 107 § 48]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5980-S.SL.pdf?cite=1993%20sp.s.%20c%2017%20§%2043[1993 sp.s. c 17 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c316.pdf?cite=1989%20c%20316%20§%2016[1989 c 316 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c457.pdf?cite=1985%20c%20457%20§%2020[1985 c 457 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c248.pdf?cite=1985%20c%20248%20§%201[1985 c 248 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%20132[1983 1st ex.s. c 46 § 132]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c66.pdf?cite=1979%20c%2066%20§%201[1979 c 66 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c28.pdf?cite=1965%20ex.s.%20c%2028%20§%201[1965 ex.s. c 28 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c212.pdf?cite=1955%20c%20212%20§%2011[1955 c 212 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c12.pdf?cite=1955%20c%2012%20§%2075.28.300[1955 c 12 § 75.28.300]; prior:  1951 c 271 § 28; 1949 c 112 § 72; Rem. Supp. 1949 § 5780-510; ]

== 77.65.310 - Wholesale fish buyers and limited fish sellers—Documentation of commercial harvest.
Wholesale fish buyers and limited fish sellers are required to document the commercial harvest of fish and shellfish according to the rules of the department.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2030[2017 3rd sp.s. c 8 § 30]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2793-S.SL.pdf?cite=1996%20c%20267%20§%2029[1996 c 267 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c248.pdf?cite=1985%20c%20248%20§%204[1985 c 248 § 4]; ]

== 77.65.320 - Wholesale fish buyers/limited fish seller—Performance bond.
. A wholesale fish buyer or limited fish seller must deposit with the department an acceptable performance bond on forms prescribed and furnished by the department before engaging in fish selling or buying activities. This performance bond shall be a corporate surety bond executed in favor of the department by a corporation authorized to do business in the state of Washington under chapter 48.28 RCW and approved by the department.

.. For wholesale fish buyers, the bond shall be filed and maintained in an amount equal to two thousand dollars. For each additional buyer engaged by the wholesale business, the bond must be increased an additional one thousand dollars.

.. For limited fish sellers, the bond shall be filed and maintained in an amount equal to one thousand dollars.

.. The department may increase the bond amount for persons who have violated rules relating to the accounting of commercial harvest.

. The director may suspend and refuse to reissue a wholesale fish buyer endorsement of a person who has taken possession of fish or shellfish without an acceptable performance bond on deposit with the department.

. The director may suspend and refuse to reissue a limited fish seller endorsement to a commercial fisher who has sold fish or shellfish without an acceptable performance bond on deposit with the department.

. The bond shall be conditioned upon the compliance with the requirements of this chapter and rules of the department relating to the payment of fines for violations of rules for the accounting of the commercial harvest of fish or shellfish. In lieu of the surety bond required by this section, the wholesale fish buyer or limited fish seller may file with the department a cash deposit, negotiable securities acceptable to the department, or an assignment of a savings account or of a savings certificate in a Washington bank on an assignment form prescribed by the department.

. Liability under the bond may be released only upon written notification from the department. Notification shall be given upon acceptance by the department of a substitute bond or forty-five days after the expiration of the wholesale fish buyer or limited fish seller annual endorsement. In no event shall the liability of the surety exceed the amount of the surety bond required under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2031[2017 3rd sp.s. c 8 § 31]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2049[2000 c 107 § 49]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2793-S.SL.pdf?cite=1996%20c%20267%20§%2030[1996 c 267 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c248.pdf?cite=1985%20c%20248%20§%206[1985 c 248 § 6]; ]

== 77.65.330 - Wholesale fish buyer/limited fish seller—Notification by director of a violation of rules relating to the accounting of commercial harvest—Payment of liability.
The director shall promptly notify by order a wholesale fish buyer or limited fish seller and the appropriate surety when a violation of rules relating to the accounting of commercial harvest has occurred. The notification shall specify the type of violation, the liability to be imposed for damages caused by the violation, and a notice that the amount of liability is due and payable to the department by the wholesale fish buyer or limited fish seller and the surety.

If the amount specified in the order is not paid within thirty days after receipt of the notice, the prosecuting attorney for any county in which the persons to whom the order is directed do business, or the attorney general upon request of the department, may bring an action on behalf of the state in the superior court for Thurston county or any county in which the persons to whom the order is directed do business to recover the amount specified in the final order of the department. The surety shall be liable to the state to the extent of the bond.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2032[2017 3rd sp.s. c 8 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c248.pdf?cite=1985%20c%20248%20§%207[1985 c 248 § 7]; ]

== 77.65.340 - Wholesale fish buyer endorsement—Fees.
. A wholesale fish buyer endorsement is required for a licensed fish dealer:

.. To take first possession or ownership of fish or shellfish directly from a commercial fisher that is landed into the state of Washington;

.. To take first possession or ownership of raw or frozen fish or shellfish in the state of Washington from interstate or foreign commerce; or

.. To engage in the wholesale buying or selling of fish or shellfish harvested by Indian fishers lawfully exercising fishing rights reserved by federal statute, treaty, or executive order, and the dealer is also responsible for documenting the commercial harvest and sales according to the rules of the department.

. A business licensed as a fish dealer must purchase at least one wholesale fish buyer endorsement to engage in the activities in subsection (1) of this section, which allows the business to buy or sell on its premises and which allows one named employee to buy and sell off premises. A business must obtain an additional wholesale fish buyer endorsement for each additional employee who buys and sells fish or shellfish off premises.

. The annual fee for a resident wholesale fish buyer's endorsement for business operations with only one fish buyer is fifty dollars. The annual fee for a resident wholesale fish buyer's endorsement for business operations with two or more employees is two hundred forty-five dollars. The annual fee for a nonresident wholesale fish buyer's endorsement is six hundred thirty dollars. The application fee for both resident and nonresident endorsements is one hundred five dollars.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6317-S.SL.pdf?cite=2018%20c%20235%20§%209[2018 c 235 § 9]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2033[2017 3rd sp.s. c 8 § 33]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6041-S.SL.pdf?cite=2014%20c%2048%20§%2028[2014 c 48 § 28]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20245[2013 c 23 § 245]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5385-S.SL.pdf?cite=2011%20c%20339%20§%2026[2011 c 339 § 26]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2050[2000 c 107 § 50]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5980-S.SL.pdf?cite=1993%20sp.s.%20c%2017%20§%2046[1993 sp.s. c 17 § 46]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c316.pdf?cite=1989%20c%20316%20§%2017[1989 c 316 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c248.pdf?cite=1985%20c%20248%20§%202[1985 c 248 § 2]; ]

== 77.65.350 - Salmon roe—Sale by crewmember on a boat designated on a salmon charter license—Requirements.
. Crewmembers on a boat designated on a salmon charter license may sell salmon roe subject to rules of the department as long as:

.. The salmon is taken by an angler fishing on the charter boat and recorded on the angler's catch record card;

.. The roe is the property of the angler until the roe is given to the crewmember. The crewmember shall notify the charter boat's passengers of this fact;

.. The crewmember sells the roe to a licensed wholesale fish buyer; and

.. The crewmember is employed on a salmon charter boat designated on a valid license at the time of the sale.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2034[2017 3rd sp.s. c 8 § 34]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2793-S.SL.pdf?cite=1996%20c%20267%20§%2031[1996 c 267 § 31]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5124.SL.pdf?cite=1993%20c%20340%20§%2022[1993 c 340 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c316.pdf?cite=1989%20c%20316%20§%2018[1989 c 316 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%20137[1983 1st ex.s. c 46 § 137]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c227.pdf?cite=1981%20c%20227%20§%202[1981 c 227 § 2]; ]

== 77.65.370 - Food fish guide license—Game fish guide license.
. A person shall not offer or perform the services of a food fish guide without a food fish guide license in the taking of food fish for personal use, except that a charter boat license is required to operate a vessel from which a person may for a fee fish for food fish in state waters listed in RCW 77.65.150(4)(b).

. A person shall not offer or perform the services of a game fish guide without a game fish guide license in the taking of game fish for personal use.

. Only an individual at least sixteen years of age may hold a food fish guide or game fish guide license. No individual may hold more than one food fish guide or game fish guide license.

. An application for a food fish guide or game fish guide license must include the information required in RCW 77.65.560.

. A food fish guide license purchased by a person, firm, or business on behalf of an employee is subject to RCW 77.65.600.

. A food fish guide, a game fish guide, or a combination guide may sell recreational one-day temporary combination fishing licenses as described in RCW 77.32.470.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2035[2017 3rd sp.s. c 8 § 35]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1232.SL.pdf?cite=2015%20c%20103%20§%202[2015 c 103 § 2]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5824-S.SL.pdf?cite=2015%20c%2097%20§%204[2015 c 97 § 4]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5786-S.SL.pdf?cite=2013%20c%20314%20§%203[2013 c 314 § 3]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1778-S.SL.pdf?cite=2009%20c%20333%20§%208[2009 c 333 § 8]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=1998%20c%20190%20§%2098[1998 c 190 § 98]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5124.SL.pdf?cite=1993%20c%20340%20§%2026[1993 c 340 § 26]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5082-S.SL.pdf?cite=1991%20c%20362%20§%202[1991 c 362 § 2]; ]

== 77.65.380 - Ocean pink shrimp—Defined.
Unless the context clearly requires otherwise, as used in this chapter "ocean pink shrimp" means the species Pandalus jordani.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1350-S.SL.pdf?cite=1993%20c%20376%20§%202[1993 c 376 § 2]; ]

== 77.65.390 - Ocean pink shrimp—Delivery license—Fees.
An ocean pink shrimp delivery license is required for a commercial fishing vessel to deliver ocean pink shrimp taken for commercial purposes in offshore waters and delivered to a port in the state. As used in this section, "deliver" and "delivery" mean arrival at a place or port, and include arrivals from offshore waters to waters within the state and arrivals from state or offshore waters. The annual license fee is three hundred dollars for residents and six hundred eighty-five dollars for nonresidents. The application fee is one hundred five dollars. Ocean pink shrimp delivery licenses are transferable.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6317-S.SL.pdf?cite=2018%20c%20235%20§%2010[2018 c 235 § 10]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2036[2017 3rd sp.s. c 8 § 36]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5385-S.SL.pdf?cite=2011%20c%20339%20§%2027[2011 c 339 § 27]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1214-S.SL.pdf?cite=2005%20c%2020%20§%205[2005 c 20 § 5]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2051[2000 c 107 § 51]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1350-S.SL.pdf?cite=1993%20c%20376%20§%204[1993 c 376 § 4]; ]

== 77.65.400 - Emerging commercial fishery—Trial or experimental fishery—Licenses and permits.
. The director may by rule designate a fishery as an emerging commercial fishery. The director shall include in the designation whether the fishery is one that requires a vessel.

. "Emerging commercial fishery" means the commercial taking of a newly classified species of food fish or shellfish, the commercial taking of a classified species with gear not previously used for that species, or the commercial taking of a classified species in an area from which that species has not previously been commercially taken. Any species of food fish or shellfish commercially harvested in Washington state as of June 7, 1990, may be designated as a species in an emerging commercial fishery, except that no fishery subject to a license limitation program in chapter 77.70 RCW may be designated as an emerging commercial fishery.

. A person shall not take food fish or shellfish in a fishery designated as an emerging commercial fishery without an emerging commercial fishery license and a permit from the director. The director shall issue two types of permits to accompany emerging commercial fishery licenses: Trial fishery permits and experimental fishery permits. Trial fishery permits are governed by subsection (4) of this section. Experimental fishery permits are governed by RCW 77.70.160.

. The director shall issue trial fishery permits for a fishery designated as an emerging commercial fishery unless the director determines there is a need to limit the number of participants under RCW 77.70.160. A person who meets the qualifications of RCW 77.65.040 may hold a trial fishery permit. The holder of a trial fishery permit shall comply with the terms of the permit. Trial fishery permits are not transferable from the permit holder to any other person.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2052[2000 c 107 § 52]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=1998%20c%20190%20§%2099[1998 c 190 § 99]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5124.SL.pdf?cite=1993%20c%20340%20§%2018[1993 c 340 § 18]; ]

== 77.65.410 - Geoduck diver license—Fee—Expiration—Safety program.
. [Empty]
.. Every diver engaged in the commercial harvest of subtidal geoduck clams shall obtain a geoduck diver license. An individual may only own one license and all geoduck harvesting performed under the license must be done personally by the actual license holder.

.. The licensing requirement created in this section does not apply to divers engaged in activities related to the cultivation of geoduck clams as private sector cultured aquatic products as defined in RCW 15.85.020.

.. The geoduck diver license is a nontransferable license.

. Beginning January 1, 2015, the director may not issue more than seventy-seven geoduck diver licenses in any one year.

. The annual geoduck diver license fee is as provided in RCW 77.65.440.

. A geoduck diver license expires on December 31st of each year. Prior to the license's expiration, a license holder may apply to renew the license holder's geoduck diver license only if the license holder is included on a department of natural resources' geoduck harvest agreement plan of operation during the applicable current calendar year.

. Beginning January 1, 2015, each person applying for or renewing a geoduck diver license under this section must complete the geoduck diver safety program established in RCW 43.30.560 prior to being issued a license.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1764-S2.SL.pdf?cite=2013%20c%20204%20§%201[2013 c 204 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5124.SL.pdf?cite=1993%20c%20340%20§%2024[1993 c 340 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c163.pdf?cite=1990%20c%20163%20§%206[1990 c 163 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c316.pdf?cite=1989%20c%20316%20§%2013[1989 c 316 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%20130[1983 1st ex.s. c 46 § 130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c141.pdf?cite=1979%20ex.s.%20c%20141%20§%204[1979 ex.s. c 141 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c253.pdf?cite=1969%20ex.s.%20c%20253%20§%204[1969 ex.s. c 253 § 4]; ]

== 77.65.420 - Wild salmonid policy—Establishment.
By July 1, 1994, the commission jointly with the appropriate Indian tribes, shall each establish a wild salmonid policy. The policy shall ensure that department actions and programs are consistent with the goals of rebuilding wild stock populations to levels that permit commercial and recreational fishing opportunities.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2053[2000 c 107 § 53]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1309-S.SL.pdf?cite=1993%20sp.s.%20c%204%20§%202[1993 sp.s. c 4 § 2]; ]

== 77.65.430 - Wild salmonid policy—Management strategies and gear types.
The director shall evaluate and recommend, in consultation with the Indian tribes, salmon fishery management strategies and gear types, as well as a schedule for implementation, that will minimize the impact of commercial and recreational fishing in the mixed stock fishery on critical and depressed wild stocks of salmonids. As part of this evaluation, the director, in conjunction with the commercial and recreational fishing industries, shall evaluate commercial and recreational salmon fishing gear types developed by these industries.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2054[2000 c 107 § 54]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%20153[1998 c 245 § 153]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2590.SL.pdf?cite=1994%20c%20264%20§%2046[1994 c 264 § 46]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1309-S.SL.pdf?cite=1993%20sp.s.%20c%204%20§%204[1993 sp.s. c 4 § 4]; ]

== 77.65.440 - Alternate operator—Geoduck diver—Food fish guide—Fees.
The director shall issue the personal licenses listed in this section according to the requirements of this title. The licenses and their annual fees are:

PersonalLicenseAnnual Fee(RCW 77.95.090 Surcharge)Applica-tion FeeGoverningSection ResidentNonresident  (1) AlternateOperator$185$570$ 70RCW 77.65.130(2) Geoduck Diver$355$740$ 70RCW 77.65.410(3) Food Fish Guide$210$595$ 70RCW 77.65.370  (plus $20)(plus$100)  

Personal

License

Annual Fee

(RCW 77.95.090 Surcharge)

Applica-tion Fee

Governing

Section

 

Resident

Nonresident

 

 

. Alternate

Operator

$185

$570

$ 70

RCW 77.65.130

. Geoduck Diver

$355

$740

$ 70

RCW 77.65.410

. Food Fish Guide

$210

$595

$ 70

RCW 77.65.370

 

 

(plus $20)

(plus

$100)

 

 

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6317-S.SL.pdf?cite=2018%20c%20235%20§%2011[2018 c 235 § 11]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2037[2017 3rd sp.s. c 8 § 37]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5385-S.SL.pdf?cite=2011%20c%20339%20§%2028[2011 c 339 § 28]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1778-S.SL.pdf?cite=2009%20c%20333%20§%209[2009 c 333 § 9]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2055[2000 c 107 § 55]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5980-S.SL.pdf?cite=1993%20sp.s.%20c%2017%20§%2042[1993 sp.s. c 17 § 42]; ]

== 77.65.450 - Trapper's license—Fees.
A state trapping license allows the holder to trap fur-bearing animals throughout the state. However, a trapper may not place traps on private property without permission of the owner, lessee, or tenant where the land is improved and apparently used, or where the land is fenced or enclosed in a manner designed to exclude intruders or to indicate a property boundary line, or where notice is given by posting in a conspicuous manner. A state trapping license is void on April 1st following the date of issuance. The fee for this license is thirty-six dollars for residents sixteen years of age or older, fifteen dollars for residents under sixteen years of age, and one hundred eighty dollars for nonresidents. The application fee is one hundred five dollars.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5385-S.SL.pdf?cite=2011%20c%20339%20§%2029[2011 c 339 § 29]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2235.SL.pdf?cite=1991%20sp.s.%20c%207%20§%203[1991 sp.s. c 7 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c372.pdf?cite=1987%20c%20372%20§%203[1987 c 372 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c464.pdf?cite=1985%20c%20464%20§%204[1985 c 464 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c310.pdf?cite=1981%20c%20310%20§%2023[1981 c 310 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c78.pdf?cite=1980%20c%2078%20§%20113[1980 c 78 § 113]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c24.pdf?cite=1980%20c%2024%20§%202[1980 c 24 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c15.pdf?cite=1975%201st%20ex.s.%20c%2015%20§%2028[1975 1st ex.s. c 15 § 28]; ]

== 77.65.460 - Trapper's license—Training program or examination requisite for issuance to initial licensee.
Persons purchasing a state trapping license for the first time shall present certification of completion of a course of instruction in safe, humane, and proper trapping techniques or pass an examination to establish that the applicant has the requisite knowledge.

The director shall establish a program for training persons in trapping techniques and responsibilities, including the use of trapping devices designed to painlessly capture or instantly kill. The director shall cooperate with national and state animal, humane, hunter education, and trapping organizations in the development of a curriculum. Upon successful completion of the course, trainees shall receive a trapper's training certificate signed by an authorized instructor. This certificate is evidence of compliance with this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c506.pdf?cite=1987%20c%20506%20§%2082[1987 c 506 § 82]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c310.pdf?cite=1981%20c%20310%20§%2024[1981 c 310 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c78.pdf?cite=1980%20c%2078%20§%20114[1980 c 78 § 114]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977c43.pdf?cite=1977%20c%2043%20§%201[1977 c 43 § 1]; ]

== 77.65.480 - Taxidermist, fur dealer, game fish guide, and game farm—Licenses—Fees—Game fish stocking permit—Fees—Fishing or field trial permit—Fees.
. A taxidermy license allows the holder to practice taxidermy for commercial purposes, as that term is defined in RCW 77.15.110. The fee for this license is one hundred eighty dollars. The application fee is seventy dollars.

. A fur dealer's license allows the holder to purchase, receive, or resell raw furs for commercial purposes, as that term is defined in RCW 77.15.110. The fee for this license is one hundred eighty dollars. The application fee is seventy dollars.

. [Empty]
.. A game fish guide license allows the holder to offer or perform the services of a game fish guide in the taking of game fish. The fee for this license is three hundred five dollars for a resident and six hundred ninety dollars for a nonresident. The application fee is seventy dollars. An application for a game fish guide license must include the information required in RCW 77.65.560.

.. A game fish guide license purchased by a person, firm, or business on behalf of an employee is subject to RCW 77.65.600.

. A game farm license allows the holder to operate a game farm to acquire, breed, grow, keep, and sell wildlife under conditions prescribed by the rules adopted pursuant to this title. The fee for this license is seventy-two dollars for the first year and forty-eight dollars for each following year. The application fee is seventy dollars.

. A game fish stocking permit allows the holder to release game fish into the waters of the state as prescribed by rule of the commission. The fee for this permit is twenty-four dollars. The application fee is seventy dollars.

. A fishing or field trial permit allows the holder to promote, conduct, hold, or sponsor a fishing or field trial contest in accordance with rules of the commission. The fee for a fishing contest permit is twenty-four dollars. The fee for a field trial contest permit is twenty-four dollars. The application fee is seventy dollars.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6317-S.SL.pdf?cite=2018%20c%20235%20§%2012[2018 c 235 § 12]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2038[2017 3rd sp.s. c 8 § 38]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1232.SL.pdf?cite=2015%20c%20103%20§%203[2015 c 103 § 3]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5786-S.SL.pdf?cite=2013%20c%20314%20§%202[2013 c 314 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5385-S.SL.pdf?cite=2011%20c%20339%20§%2030[2011 c 339 § 30]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1778-S.SL.pdf?cite=2009%20c%20333%20§%2011[2009 c 333 § 11]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2235.SL.pdf?cite=1991%20sp.s.%20c%207%20§%204[1991 sp.s. c 7 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c506.pdf?cite=1987%20c%20506%20§%2083[1987 c 506 § 83]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c464.pdf?cite=1985%20c%20464%20§%205[1985 c 464 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c284.pdf?cite=1983%20c%20284%20§%203[1983 c 284 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c310.pdf?cite=1981%20c%20310%20§%2025[1981 c 310 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c78.pdf?cite=1980%20c%2078%20§%20115[1980 c 78 § 115]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c15.pdf?cite=1975%201st%20ex.s.%20c%2015%20§%2030[1975 1st ex.s. c 15 § 30]; ]

== 77.65.490 - Activities requiring license/permit.
. A license issued by the director is required to:

.. Practice taxidermy for commercial purposes;

.. Deal in raw furs for commercial purposes;

.. Act as a fishing guide; or

.. Operate a game farm.

. A permit issued by the director is required to:

.. Conduct, hold, or sponsor hunting or fishing contests or competitive field trials using live wildlife;

.. Collect wild animals, wild birds, game fish, food fish, shellfish, or protected wildlife for research or display;

.. Stock game fish; or

.. Conduct commercial activities on department-owned or controlled lands.

. Aquaculture as defined in RCW 15.85.020 is exempt from the requirements of this section, except when being stocked in public waters under contract with the department.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2039[2017 3rd sp.s. c 8 § 39]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5961-S.SL.pdf?cite=2001%20c%20253%20§%2056[2001 c 253 § 56]; ]

== 77.65.500 - Reports required from persons with licenses or permits under RCW  77.65.480.
Licensed taxidermists, fur dealers, fishing guides, game farmers, and persons stocking game fish or conducting a hunting, fishing, or field trial contest shall make reports as required by rules of the director.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2040[2017 3rd sp.s. c 8 § 40]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5824-S.SL.pdf?cite=2015%20c%2097%20§%209[2015 c 97 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c506.pdf?cite=1987%20c%20506%20§%2084[1987 c 506 § 84]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c284.pdf?cite=1983%20c%20284%20§%204[1983 c 284 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c310.pdf?cite=1981%20c%20310%20§%2026[1981 c 310 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c78.pdf?cite=1980%20c%2078%20§%20116[1980 c 78 § 116]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c36.pdf?cite=1955%20c%2036%20§%2077.32.220[1955 c 36 § 77.32.220]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c275.pdf?cite=1947%20c%20275%20§%20111[1947 c 275 § 111]; Rem. Supp. 1947 § 5992-120; ]

== 77.65.510 - Limited fish seller endorsement—Food safety requirements—Fees—Other provisions.
. The limited fish seller endorsement permits a license holder or alternate operator to clean, dress, and sell his or her commercially harvested catch directly to consumers at retail. The limited fish seller endorsement may be issued as an optional addition to all holders of a commercial fishing license issued by the department and may be purchased at the time of the underlying license sale or any time thereafter.

. The holder of a limited fish seller endorsement selling their own catch directly to consumers is exempt from the permitting requirements of chapter 246-215 WAC. To ensure food safety for consumers, the holder of a limited fish seller endorsement must follow these requirements: (a) Only sell fresh, whole fish or fresh fish that has been cleaned and dressed; (b) use ice from a commercial source to hold the fish; and (c) provide the buyer with a receipt stating the date of purchase, Washington fish-receiving ticket number documenting the original delivery, name, address, and phone number of the holder of the limited fish seller endorsement from whom the fish or shellfish was purchased, and the species and weight or number of fish or shellfish sold. Failure to satisfy these food safety requirements is punishable as an infraction under RCW 77.15.160. A licensed commercial fisher holding a limited fish seller endorsement may allow a designated alternate to sell under the authority of that endorsement.

. An individual need only add one limited fish seller endorsement to his or her license portfolio. If a limited fish seller endorsement is selected by an individual holding more than one commercial fishing license issued by the department, an endorsement is considered to be added to all commercial fishing licenses held by that individual, and is the only endorsement required for the individual to sell at retail any species permitted by any of the underlying endorsed licenses.

. The fee for a resident limited fish seller endorsement is seventy dollars. The fee for a nonresident limited fish seller endorsement is four hundred fifty-five dollars. The application fee for both a resident and nonresident endorsement is one hundred five dollars.

. The holder of a limited fish seller endorsement is responsible for documenting the commercial harvest and sales according to the rules of the department.

. The limited fish seller endorsement is to be held by a natural person and is not transferable or assignable. If the endorsed license is transferred, the limited fish seller endorsement immediately becomes void, and the transferor is not eligible for a full or prorated reimbursement of the annual fee paid for the limited fish seller endorsement. Upon becoming void, the holder of a limited fish seller endorsement must surrender the physical endorsement to the department.

. The holder of a qualifying commercial fishing license or an alternate operator designated on such a license, must either possess a limited fish seller endorsement or a wholesale fish buyer endorsement provided for in RCW 77.65.340 in order to lawfully sell their catch or harvest in the state to anyone other than a licensed wholesale fish buyer.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6317-S.SL.pdf?cite=2018%20c%20235%20§%2013[2018 c 235 § 13]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2041[2017 3rd sp.s. c 8 § 41]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5385-S.SL.pdf?cite=2011%20c%20339%20§%2031[2011 c 339 § 31]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5356.SL.pdf?cite=2009%20c%20195%20§%201[2009 c 195 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1127-S.SL.pdf?cite=2003%20c%20387%20§%202[2003 c 387 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2323-S.SL.pdf?cite=2002%20c%20301%20§%202[2002 c 301 § 2]; ]

== 77.65.530 - Washington-coastal spot shrimp pot fishery license.
. A Washington-coastal spot shrimp pot fishery license is required to:

.. Use spot shrimp pot gear to fish for spot shrimp;

.. Possess spot shrimp; and

.. Deliver spot shrimp.

. Washington-coastal spot shrimp pot fishery licenses require vessel designation under RCW 77.65.100.

. A violation of this section is punishable under RCW 77.15.500.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1148-S.SL.pdf?cite=2011%20c%20147%20§%201[2011 c 147 § 1]; ]

== 77.65.550 - Revocation of geoduck diver license.
The department must revoke a geoduck diver license issued under RCW 77.65.410, and the licensee must surrender the license, if the licensee is found in violation of a department of natural resources' geoduck harvest agreement two or more times. The person surrendering the geoduck diver license may not hold another geoduck diver license for a period of one calendar year from the date the license is surrendered.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1764-S2.SL.pdf?cite=2013%20c%20204%20§%203[2013 c 204 § 3]; ]

== 77.65.560 - Application for food fish guide license/game fish guide license—Required information.
. Any application for a food fish guide license or game fish guide license under RCW 77.65.480 must include:

.. The applicant's driver's license or other government-issued identification card number and the jurisdiction of issuance;

.. The applicant's unified business identifier number under a business license issued under RCW 19.02.070;

.. Proof of current certification in first aid and cardiopulmonary resuscitation;

.. A certificate of insurance demonstrating that the applicant has commercial liability coverage of at least three hundred thousand dollars;

.. If applicable, an original or notarized copy of a valid license issued by the United States coast guard to the applicant that authorizes the holder to carry passengers for hire; and

.. A sworn declaration requiring the applicant to certify whether the area of operations will include federally recognized navigable waters with a motorized vessel.

. The requirements of this section related to licensure by the United States coast guard apply only to applicants intending to carry passengers for hire with a motorized vessel on federally recognized navigable waters. The license issued by the United States coast guard must be valid in the waters where the game fish guide or food fish guide license applicant will be carrying passengers for hire in a motorized vessel.

. The requirements in this section are in addition to the requirements of RCW 77.65.050.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5824-S.SL.pdf?cite=2015%20c%2097%20§%2010[2015 c 97 § 10]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5786-S.SL.pdf?cite=2013%20c%20314%20§%201[2013 c 314 § 1]; ]

== 77.65.570 - Suspension of charter boat, food fish guide, or game fish guide license—Appeal.
. In addition to other license suspension provisions provided in this title, the department may suspend a charter boat license, food fish guide license, or game fish guide license if, within a twelve-month period, a person is convicted of two or more violations of any rule of the commission or director regarding seasons, bag limits, species, size, sex, or other possession restrictions while engaged in charter boat, food fish guide, or game fish guide activities. The department may suspend only the specific type of license or licenses related to the activity or activities for which the person is convicted.

. A person who has a food fish guide or game fish guide license suspended under this section may file an appeal with the department pursuant to chapter 34.05 RCW. An appeal must be filed within twenty days of notice of license suspension. If a timely appeal is filed, the suspension issued by the department does not take effect until twenty-one days after the department has delivered an opinion affirming the suspension. If no appeal is filed within twenty days of notice of license suspension, the right to an appeal is waived, and the suspension takes effect twenty-one days following the notice of suspension.

. License suspension under this section is in addition to any statutory penalties assigned to the underlying violation.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5824-S.SL.pdf?cite=2015%20c%2097%20§%202[2015 c 97 § 2]; ]

== 77.65.580 - Vessel registration number decal and identifying decal for food fish guides, game fish guides, and charter boat operators.
. The department must issue a department vessel registration number decal and an identifying decal to all food fish guides, game fish guides, and charter boat operators licensed under RCW 77.65.010.

. Any person who acts or offers to act as a food fish guide, game fish guide, or charter boat operator must display both decals on vessels in a location easily visible to customers and adjacent vessels.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2043[2017 3rd sp.s. c 8 § 43]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5824-S.SL.pdf?cite=2015%20c%2097%20§%205[2015 c 97 § 5]; ]

== 77.65.590 - Fish guide combination license—Rule making—Fee.
. A fish guide combination license allows the holder to offer or perform the services of a food fish guide and game fish guide.

. The commission must adopt rules to create and sell a fish guide combination license. The cost of the fish guide combination license or licenses must be below a fee equal to the total cost of the individual licenses contained within the combination.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2044[2017 3rd sp.s. c 8 § 44]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5824-S.SL.pdf?cite=2015%20c%2097%20§%207[2015 c 97 § 7]; ]

== 77.65.600 - Return of certain licenses upon termination of employment relationship.
. Upon termination of the employment relationship by an employee or by an employing person, firm, or business, the employee shall return to the person, firm, or business who purchased the license on the employee's behalf any license described in subsection (2) of this section that the employee possesses.

. This section applies to the following types of licenses if the following types of licenses are purchased by a person, firm, or business on behalf of an employee of that person, firm, or business:

.. A food fish guide license issued under RCW 77.65.370; and

.. A game fish guide license issued under RCW 77.65.480.

. Any license described in subsection (2) of this section that is returned to the person, firm, or business who purchased the license pursuant to this section is transferable to another employee of the person, firm, or business who qualifies for a license under RCW 77.65.050 and 77.65.560.

. [Empty]
.. An employee who fails to return a license as provided in this section shall pay to the person, firm, or business who purchased the license on the employee's behalf an amount equal to the full amount of the license fee and any application fee paid.

.. A license possessed by an employee who fails to return the license as provided in this section or to pay the person, firm, or business who purchased the license on the employee's behalf as provided in (a) of this subsection is invalidated.

. For the purposes of this section, "purchased" means the payment of the full amount of the license fee and any application fee applicable to the license.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1232.SL.pdf?cite=2015%20c%20103%20§%201[2015 c 103 § 1]; ]

== 77.65.610 - Crewmember license—Requirements—Rule making—Fee—Exemptions.
. [Empty]
.. An individual age sixteen and older who works on board any vessel while operating in a commercial fishery regulated by the state must obtain a crewmember license from the department. However, an individual on the vessel designated as the primary or alternate operator on the commercial fishing license and an individual on the vessel licensed and working as a geoduck diver or geoduck tender do not also need a crewmember license. Crewmembers working for licensed charters or guides are not required to have a crewmember license.

.. A crewmember license is required for each individual who participates in the operation of the vessel or the harvest. For the purposes of this section, the term "harvest" includes participation in tending, deploying, retrieving, or baiting fishing gear, harvesting, or placing fish or shellfish in holds.

.. Each individual required to have a crewmember license as set forth in this section must have in their possession at least one piece of identifying documentation as specified in RCW 46.20.035(1) (a) through (f) that contains the signature and a photograph of the individual and produce the documentation at the request of a fish and wildlife officer or ex officio fish and wildlife officer.

.. An albacore tuna crewmember license satisfies the requirements specified in (a) and (b) of this subsection on vessels fishing for albacore tuna or baitfish lampara.

. A crewmember license must be purchased in the name of the individual working as the crewmember. The license holder may use the license aboard any commercial fishing vessel, except an albacore tuna crewmember license is only valid for participating in the albacore tuna fishery or baitfish lampara fishery. A crewmember license purchased by a crewmember may not be transferred to another individual.

. Up to two crewmember licenses may be purchased and held by a commercial fishing license holder for use by any individual working on the vessel named in the commercial fishing license, as long as the individual is not prohibited from obtaining a crewmember license. Each crewmember license held by a commercial fishing license holder covers one crewmember per trip, but the same crewmember license may be used to authorize a different individual to act as a crewmember on a subsequent trip. The commission may adopt fishery specific rules that:

.. Increase the number of crewmember licenses that may be held by a commercial fishing license holder;

.. Pertain to the issuance, period of validity, use, possession, and display of the licenses.

. The fee for an annual crewmember license is thirty-five dollars for residents and one hundred ten dollars for nonresidents. The fee for an annual albacore tuna crewmember license is thirty-five dollars for residents and nonresidents. Additional application fees and surcharges do not apply except that if the license is purchased through the automated licensing system the fees authorized in RCW 77.32.050 apply.

. The licenses must be available through the automated licensing system and transaction fees and dealer fees apply, except as provided in subsection (4) of this section. The annual crewmember license is valid for a calendar year.

. Family members of the commercial license holder or alternate operators are exempt from the requirements of this section. For purposes of this section, family members include children, grandchildren, spouse, parents, or siblings of the commercial license holder.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1437.SL.pdf?cite=2021%20c%2046%20§%201[2021 c 46 § 1]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2015[2017 3rd sp.s. c 8 § 15]; ]

== 77.65.615 - Commercial whale watching business license—Commercial whale watching operator license—Commercial whale watching kayak guide license—Fees—Definitions.
. A commercial whale watching business license is required for commercial whale watching businesses. The annual fee for a commercial whale watching business license is two hundred dollars in addition to the annual application fee of seventy-five dollars.

. The annual fees for a commercial whale watching business license as described in subsection (1) of this section must include fees for each motorized or sailing vessel or vessels as follows:

.. One to twenty-four passengers, three hundred twenty-five dollars;

.. Twenty-five to fifty passengers, five hundred twenty-five dollars;

.. Fifty-one to one hundred passengers, eight hundred twenty-five dollars;

.. One hundred one to one hundred fifty passengers, one thousand eight hundred twenty-five dollars; and

.. One hundred fifty-one passengers or greater, two thousand dollars.

. The holder of a commercial whale watching business license for motorized or sailing vessels required under subsection (2) of this section may substitute the vessel designated on the license, or designate a vessel if none has previously been designated, if the license holder:

.. Surrenders the previously issued license to the department;

.. Submits to the department an application that identifies the currently designated vessel, the vessel proposed to be designated, and any other information required by the department; and

.. Pays to the department a fee of thirty-five dollars and an application fee of one hundred five dollars.

. Unless the business license holder owns all vessels identified on the application described in subsection (3)(b) of this section, the department may not change the vessel designation on the license more than once per calendar year.

. A commercial whale watching operator license is required for commercial whale watching operators. A person may operate a motorized or sailing commercial whale watching vessel designated on a commercial whale watching business license only if:

.. The person holds a commercial whale watching operator license issued by the director; and

.. The person is designated as an operator on the underlying commercial whale watching business license.

. No individual may hold more than one commercial whale watching operator license. An individual who holds an operator license may be designated as an operator on an unlimited number of commercial whale watching business licenses.

. The annual fee for a commercial whale watching operator license is one hundred dollars in addition to an annual application fee of seventy-five dollars.

. A person may conduct commercial whale watching via guided kayak tours only if:

.. The person holds a kayak guide license issued by the director; and

.. The person is designated as a kayak guide on the underlying commercial whale watching business license.

. No individual may hold more than one kayak guide license. An individual who holds a kayak guide license may be designated on an unlimited number of commercial whale watching business licenses.

. The annual fee for a kayak guide license is $25 in addition to an annual application fee of $25.

. The definitions in this subsection apply throughout this section unless the context clearly requires otherwise.

.. "Commercial whale watching" means the act of taking, or offering to take, passengers aboard a vessel or guided kayak tour in order to view marine mammals in their natural habitat for a fee.

.. "Commercial whale watching business" means a business that engages in the activity of commercial whale watching.

.. "Commercial whale watching business license" means a department-issued license to operate a commercial whale watching business.

.. "Commercial whale watching license" means a commercial whale watching business license, a commercial whale watching operator license, or a kayak guide license as defined in this section.

.. "Commercial whale watching operator" means a person who operates a motorized or sailing vessel engaged in the business of whale watching.

.. "Commercial whale watching operator license" means a department-issued license to operate a commercial motorized or sailing vessel on behalf of a commercial whale watching business.

.. "Commercial whale watching vessel" means any vessel that is being used as a means of transportation for individuals to engage in commercial whale watching.

.. "Kayak guide" means a person who conducts guided kayak tours on behalf of a commercial whale watching business.

.. "Kayak guide license" means a department-issued license to conduct commercial guided kayak tours on behalf of a commercial whale watching business.

. The residency and business requirements of RCW 77.65.040 (2) and (3) do not apply to Canadian individuals or corporations applying for and holding Washington commercial whale watching licenses defined in this section.

. The license and application fees in this section are waived for calendar years 2021 and 2022.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5330.SL.pdf?cite=2021%20c%20284%20§%201[2021 c 284 § 1]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5577-S2.SL.pdf?cite=2019%20c%20291%20§%202[2019 c 291 § 2]; ]

== 77.65.620 - Commercial whale watching license—Adoption of rules—Analysis and report to the governor and the legislature—Definitions.
. The department must adopt rules for holders of a commercial whale watching license established in RCW 77.65.615 for the viewing of southern resident orca whales for the inland waters of Washington by January 1, 2021. The rules must be designed to reduce the daily and cumulative impacts on southern resident orca whales and consider the economic viability of license holders. The department shall at a minimum consider protections for southern resident orca whales by establishing limitations on:

.. The number of commercial whale watching operators that may view southern resident orca whales at one time;

.. The number of days and hours that commercial whale watching operators can operate;

.. The duration spent in the vicinity of southern resident orca whales; and

.. The areas in which commercial whale watching operators may operate.

. The department may phase in requirements, but must adopt rules to implement this section. The department may consider the use of an automatic identification system to enable effective monitoring and compliance.

. The department may phase in requirements, but must adopt rules pursuant to chapter 34.05 RCW to implement this section including public, industry, and interested party involvement.

. Before January 1, 2021, the department shall convene an independent panel of scientists to review the current body of best available science regarding impacts to southern resident orcas by small vessels and commercial whale watching due to disturbance and noise. The department must use the best available science in the establishment of the southern resident orca whale watching rules and continue to adaptively manage the program using the most current and best available science.

. The department shall complete an analysis and report to the governor and the legislature on the effectiveness of and any recommendations for changes to the whale watching rules, license fee structure, and approach distance rules by November 30, 2022, and every two years thereafter until 2026. This report must be in compliance with RCW 43.01.036.

. The definitions in this subsection apply throughout this section unless the context clearly requires otherwise.

.. "Commercial whale watching" has the same meaning as defined in RCW 77.65.615.

.. "Commercial whale watching operators" has the same meaning as defined in RCW 77.65.615.

.. "Inland waters of Washington" means Puget Sound and related inland marine waters, including all salt waters of the state of Washington inside the international boundary line between Washington and British Columbia, and lying east of the junction of the Pacific Ocean and the Strait of Juan de Fuca, and the rivers and streams draining to Puget Sound as mapped by water resource inventory areas 1 through 19 in WAC 173-500-040 as it exists on July 1, 2007.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5577-S2.SL.pdf?cite=2019%20c%20291%20§%203[2019 c 291 § 3]; ]

