= 77.95 - Salmon enhancement program.
:toc:

== 77.95.010 - Legislative findings.
Currently, many of the salmon stocks of Washington state are critically reduced from their sustainable level. The best interests of all fishing groups and the citizens as a whole are served by a stable and productive salmon resource. Immediate action is needed to reverse the severe decline of the resource and to insure its very survival. The legislature finds a state of emergency exists and that immediate action is required to restore its fishery.

Disagreement and strife have dominated the salmon fisheries for many years. Conflicts among the various fishing interests have only served to erode the resource. It is time for the state of Washington to make a major commitment to increasing productivity of the resource and to move forward with an effective rehabilitation and enhancement program. The commission is directed to dedicate its efforts and the efforts of the department to seek resolution to the many conflicts that involve the resource.

Success of the enhancement program can only occur if projects efficiently produce salmon or restore habitat. The expectation of the program is to optimize the efficient use of funding on projects that will increase artificially and naturally produced salmon, restore and improve habitat, or identify ways to increase the survival of salmon. The full utilization of state resources and cooperative efforts with interested groups are essential to the success of the program.

[ 1995 1st sp.s. c 2 § 33 (Referendum Bill No. 45, approved November 7, 1995); http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2055-S.SL.pdf?cite=1993%20sp.s.%20c%202%20§%2045[1993 sp.s. c 2 § 45]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c458.pdf?cite=1985%20c%20458%20§%201[1985 c 458 § 1]; ]

== 77.95.020 - Long-term regional policy statements.
. The commission shall develop long-term regional policy statements regarding the salmon fishery resources before December 1, 1985. The commission shall consider the following in formulating and updating regional policy statements:

.. Existing resource needs;

.. Potential for creation of new resources;

.. Successful existing programs, both within and outside the state;

.. Balanced utilization of natural and hatchery production;

.. Desires of the fishing interest;

.. Need for additional data or research;

.. Federal court orders; and

.. Salmon advisory council recommendations.

. The commission shall review and update each policy statement at least once each year.

[ 1995 1st sp.s. c 2 § 34 (Referendum Bill No. 45, approved November 7, 1995); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c458.pdf?cite=1985%20c%20458%20§%202[1985 c 458 § 2]; ]

== 77.95.030 - Salmon enhancement plan—Enhancement projects.
. The commission shall develop a detailed salmon enhancement plan with proposed enhancement projects. The plan and the regional policy statements shall be submitted to the secretary of the senate and chief clerk of the house of representatives for legislative distribution by June 30, 1986. The enhancement plan and regional policy statements shall be provided by June 30, 1986, to the natural resources committees of the house of representatives and the senate. The commission shall provide a maximum opportunity for the public to participate in the development of the salmon enhancement plan. To insure full participation by all interested parties, the commission shall solicit and consider enhancement project proposals from Indian tribes, sports fishers, commercial fishers, private aquaculturists, and other interested groups or individuals for potential inclusion in the salmon enhancement plan. Joint or cooperative enhancement projects shall be considered for funding.

. The following criteria shall be used by the commission in formulating the project proposals:

.. Compatibility with the long-term policy statement;

.. Benefit/cost analysis;

.. Needs of all fishing interests;

.. Compatibility with regional plans, including harvest management plans;

.. Likely increase in resource productivity;

.. Direct applicability of any research;

.. Salmon advisory council recommendations;

.. Compatibility with federal court orders;

.. Coordination with the salmon and steelhead advisory commission program;

.. Economic impact to the state;

.. Technical feasibility; and

.. Preservation of native salmon runs.

. The commission shall not approve projects that serve as replacement funding for projects that exist prior to May 21, 1985, unless no other sources of funds are available.

. The commission shall prioritize various projects and establish a recommended implementation time schedule.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20246[2013 c 23 § 246]; 1995 1st sp.s. c 2 § 35 (Referendum Bill No. 45, approved November 7, 1995); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c458.pdf?cite=1985%20c%20458%20§%203[1985 c 458 § 3]; ]

== 77.95.040 - Commission to monitor enhancement projects and enhancement plan.
Upon approval by the legislature of funds for its implementation, the commission shall monitor the progress of projects detailed in the salmon enhancement plan.

The commission shall be responsible for establishing criteria which shall be used to measure the success of each project in the salmon enhancement plan.

[ 1995 1st sp.s. c 2 § 36 (Referendum Bill No. 45, approved November 7, 1995); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c458.pdf?cite=1985%20c%20458%20§%204[1985 c 458 § 4]; ]

== 77.95.050 - "Enhancement project" defined.
As used in this chapter, "enhancement project" means salmon propagation activities including, but not limited to, hatcheries, spawning channels, rearing ponds, egg boxes, fishways, fish screens, stream bed clearing, erosion control, habitat restoration, net pens, applied research projects, and any equipment, real property, or other interest necessary to the proper operation thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c458.pdf?cite=1985%20c%20458%20§%206[1985 c 458 § 6]; ]

== 77.95.060 - Regional fisheries enhancement group authorized.
The legislature finds that it is in the best interest of the salmon resource of the state to encourage the development of regional fisheries enhancement groups. The accomplishments of one existing group, the Grays Harbor fisheries enhancement task force, have been widely recognized as being exemplary. The legislature recognizes the potential benefits to the state that would occur if each region of the state had a similar group of dedicated citizens working to enhance the salmon resource.

The legislature authorizes the formation of regional fisheries enhancement groups. These groups shall be eligible for state financial support and shall be actively supported by the commission and the department. The regional groups shall be operated on a strictly nonprofit basis, and shall seek to maximize the efforts of volunteer and private donations to improve the salmon resource for all citizens of the state.

[ 1995 1st sp.s. c 2 § 38 (Referendum Bill No. 45, approved November 7, 1995); http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2055-S.SL.pdf?cite=1993%20sp.s.%20c%202%20§%2046[1993 sp.s. c 2 § 46]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c426.pdf?cite=1989%20c%20426%20§%201[1989 c 426 § 1]; ]

== 77.95.070 - Regional fisheries enhancement groups—Goals.
Regional fisheries enhancement groups, consistent with the long-term regional policy statements developed under RCW 77.95.020, shall seek to:

. Enhance the salmon and steelhead resources of the state;

. Maximize volunteer efforts and private donations to improve the salmon and steelhead resources for all citizens;

. Assist the department in achieving the goal to double the statewide salmon and steelhead catch by the year 2000; and

. Develop projects designed to supplement the fishery enhancement capability of the department.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%20105[2000 c 107 § 105]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5886-S2.SL.pdf?cite=1997%20c%20389%20§%205[1997 c 389 § 5]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2055-S.SL.pdf?cite=1993%20sp.s.%20c%202%20§%2047[1993 sp.s. c 2 § 47]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c426.pdf?cite=1989%20c%20426%20§%204[1989 c 426 § 4]; ]

== 77.95.080 - Regional fisheries enhancement groups—Incorporation prerequisites.
Each regional fisheries enhancement group shall be incorporated pursuant to Title 24 RCW. Any interested person or group shall be permitted to join. It is desirable for the group to have representation from all categories of fishers and other parties that have interest in salmon within the region, as well as the general public.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c58.pdf?cite=1990%20c%2058%20§%202[1990 c 58 § 2]; ]

== 77.95.090 - Regional fisheries enhancement group account—Revenue sources, uses, and limitations.
The dedicated regional fisheries enhancement group account is created in the custody of the state treasurer. Only the commission or the commission's designee may authorize expenditures from the account. The account is subject to allotment procedures under chapter 43.88 RCW, but no appropriation is required for expenditures.

A portion of each recreational fishing license fee shall be used as provided in RCW 77.32.440. A surcharge of one hundred dollars shall be collected on each commercial salmon fishery license, each salmon delivery license, and each salmon charter license sold in the state. All receipts shall be placed in the regional fisheries enhancement group account and shall be used exclusively for regional fisheries enhancement group projects for the purposes of *RCW 77.95.110. Except as provided in RCW 77.95.320, funds from the regional fisheries enhancement group account shall not serve as replacement funding for department operated salmon projects that exist on January 1, 1991.

All revenue from the department's sale of salmon carcasses and eggs that return to group facilities shall be deposited in the regional fisheries enhancement group account for use by the regional fisheries enhancement group that produced the surplus. The commission shall adopt rules to implement this section pursuant to chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1951-S2.SL.pdf?cite=2009%20c%20340%20§%204[2009 c 340 § 4]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%20106[2000 c 107 § 106]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%20155[1998 c 245 § 155]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6330-S2.SL.pdf?cite=1998%20c%20191%20§%2027[1998 c 191 § 27]; 1995 1st sp.s. c 2 § 39 (Referendum Bill No. 45, approved November 7, 1995); prior:  1993 sp.s. c 17 § 11; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5124.SL.pdf?cite=1993%20c%20340%20§%2053[1993 c 340 § 53]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c58.pdf?cite=1990%20c%2058%20§%203[1990 c 58 § 3]; ]

== 77.95.100 - Regional fisheries enhancement groups—Start-up funds.
The department may provide start-up funds to regional fisheries enhancement groups for costs associated with any enhancement project. The commission shall develop guidelines for providing funds to the regional fisheries enhancement groups.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2617-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%207%20§%2082[2010 1st sp.s. c 7 § 82]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%20107[2000 c 107 § 107]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5886-S2.SL.pdf?cite=1997%20c%20389%20§%202[1997 c 389 § 2]; ]

== 77.95.130 - Regional fisheries enhancement salmonid recovery account—Created.
The regional fisheries enhancement salmonid recovery account is created in the state treasury. All receipts from federal sources and moneys from state sources specified by law must be deposited into the account. Moneys in the account may be spent only after appropriation. Expenditures from the account may be used for the sole purpose of fisheries enhancement and habitat restoration by regional fisheries enhancement groups.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5886-S2.SL.pdf?cite=1997%20c%20389%20§%203[1997 c 389 § 3]; ]

== 77.95.140 - Skagit river salmon recovery plan.
The commission shall prepare a salmon recovery plan for the Skagit river. The plan shall include strategies for employing displaced timber workers to conduct salmon restoration and other tasks identified in the plan. The plan shall incorporate the best available technology in order to achieve maximum restoration of depressed salmon stocks. The plan must encourage the restoration of natural spawning areas and natural rearing of salmon but must not preclude the development of an active hatchery program.

[ 1995 1st sp.s. c 2 § 41 (Referendum Bill No. 45, approved November 7, 1995); http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2055-S.SL.pdf?cite=1993%20sp.s.%20c%202%20§%2048[1993 sp.s. c 2 § 48]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5675.SL.pdf?cite=1992%20c%2088%20§%201[1992 c 88 § 1]; ]

== 77.95.150 - Coordination with regional enhancement groups—Findings.
The legislature finds that:

. Regional enhancement groups are a valuable resource for anadromous fish recovery. They improve critical fish habitat and directly contribute to anadromous fish populations through fish restoration technology.

. Due to a decrease in recreational and commercial salmon license sales, regional enhancement groups are receiving fewer financial resources at a time when recovery efforts are needed most.

. To maintain regional enhancement groups as an effective enhancement resource, technical assets of state agencies must be coordinated and utilized to maximize the financial resources of regional enhancement groups and overall fish recovery efforts.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5064-S2.SL.pdf?cite=1995%20c%20367%20§%201[1995 c 367 § 1]; ]

== 77.95.160 - Fish passage barrier removal board—Membership—Duties.
. The department shall maintain a fish passage barrier removal board. The board must be composed of a representative from the department, the department of transportation, cities, counties, the governor's salmon recovery office, tribal governments, and the department of natural resources. The representative of the department must serve as chair of the board and may expand the membership of the board to representatives of other governments, stakeholders, and interested entities.

. [Empty]
.. The duty of the board is to identify and expedite the removal of human-made or caused impediments to anadromous fish passage in the most efficient manner practical through the development of a coordinated approach and schedule that identifies and prioritizes the projects necessary to eliminate fish passage barriers caused by state and local roads and highways and barriers owned by private parties.

.. The coordinated approach must address fish passage barrier removals in all areas of the state in a manner that is consistent with a recognition that scheduling and prioritization is necessary.

.. The board must coordinate and mutually share information, when appropriate, with:

... Other fish passage correction programs, including local salmon recovery plan implementation efforts through the governor's salmon recovery office;

... The applicable conservation districts when developing schedules and priorities within set geographic areas or counties; and

... The recreation and conservation office to ensure that barrier removal methodologies are consistent with, and maximizing the value of, other salmon recovery efforts and habitat improvements that are not primarily based on the removal of barriers.

.. Recommendations must include proposed funding mechanisms and other necessary mechanisms and methodologies to coordinate state, tribal, local, and volunteer barrier removal efforts within each water resource inventory area and satisfy the principles of RCW 77.95.180. To the degree practicable, the board must utilize the database created in RCW 77.95.170 and information on fish barriers developed by conservation districts to guide methodology development. The board may consider recommendations by interested entities from the private sector and regional fisheries enhancement groups.

.. When developing a prioritization methodology under this section, the board shall consider:

... Projects benefiting depressed, threatened, and endangered stocks;

... Projects providing access to available and high quality spawning and rearing habitat;

... Correcting the lowest barriers within the stream first;

... Whether an existing culvert is a full or partial barrier;

.. Projects that are coordinated with other adjacent barrier removal projects; and

.. Projects that address replacement of infrastructure associated with flooding, erosion, or other environmental damage. (f) The board may not make decisions on fish passage standards or categorize as impassible culverts or other infrastructure developments that have been deemed passable by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2251-S2.SL.pdf?cite=2014%20c%20120%20§%204[2014 c 120 § 4]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%20110[2000 c 107 § 110]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5886-S2.SL.pdf?cite=1997%20c%20389%20§%206[1997 c 389 § 6]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5064-S2.SL.pdf?cite=1995%20c%20367%20§%202[1995 c 367 § 2]; ]

== 77.95.170 - Salmonid fish passage—Removing impediments—Grant program—Administration—Database directory.
. The department may coordinate with the recreation and conservation office in the administration of all state grant programs specifically designed to assist state agencies, private landowners, tribes, organizations, and volunteer groups in identifying and removing impediments to salmonid fish passage. The transportation improvement board may administer all grant programs specifically designed to assist cities, counties, and other units of local governments with fish passage barrier corrections associated with transportation projects. All grant programs must be administered and be consistent with the following:

.. Salmonid-related corrective projects, inventory, assessment, and prioritization efforts;

.. Salmonid projects subject to a competitive application process; and

.. A minimum dollar match rate that is consistent with the funding authority's criteria. If no funding match is specified, a match amount of at least twenty-five percent per project is required. For local, private, and volunteer projects, in-kind contributions may be counted toward the match requirement.

. Priority shall be given to projects that match the principles provided in RCW 77.95.180.

. All projects subject to this section shall be reviewed and approved by the fish passage barrier removal board created in RCW 77.95.160 or an alternative oversight committee designated by the state legislature.

. Other agencies that administer natural resource-based grant programs shall use fish passage selection criteria that are consistent with this section when those programs are addressing fish passage barrier removal projects.

. [Empty]
.. The department shall establish a centralized database directory of all fish passage barrier information. The database directory must include, but is not limited to, existing fish passage inventories, fish passage projects, grant program applications, and other databases. These data must be used to coordinate and assist in habitat recovery and project mitigation projects.

.. The department must develop a barrier inventory training program that qualifies participants to perform barrier inventories and develop data that enhance the centralized database. The department may decide the qualifications for participation. However, employees and volunteers of conservation districts and regional salmon recovery groups must be given priority consideration.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2251-S2.SL.pdf?cite=2014%20c%20120%20§%203[2014 c 120 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2239-S.SL.pdf?cite=1999%20c%20242%20§%204[1999 c 242 § 4]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2879-S2.SL.pdf?cite=1998%20c%20249%20§%2016[1998 c 249 § 16]; ]

== 77.95.180 - Fish passage barrier removal program.
. [Empty]
.. To maximize available state resources, the department and the department of transportation must work in partnership to identify and complete projects to eliminate fish passage barriers caused by state roads and highways.

.. The partnership between the department and the department of transportation must be based on the principle of maximizing habitat recovery through a coordinated investment strategy that, to the maximum extent practical and allowable, prioritizes opportunities: To correct multiple fish barriers in whole streams rather than through individual, isolated projects; to coordinate with other entities sponsoring barrier removals, such as regional fisheries enhancement groups incorporated under this chapter, in a manner that achieves the greatest cost savings to all parties; and to correct barriers located furthest downstream in a stream system. Examples of this principle include:

... Coordinating with all relevant state agencies and local governments to maximize the habitat recovery value of the investments made by the state to correct fish passage barriers;

... Maximizing the habitat recovery value of investments made by public and private forestland owners through the road maintenance and abandonment planning process outlined in the forest practices rules, as that term is defined in RCW 76.09.020;

... Recognizing that many of the barriers owned by the state are located in the same stream systems as barriers that are owned by cities and counties with limited financial resources for correction and that state-local partnership opportunities should be sought to address these barriers; and

... Recognizing the need to continue investments in the family forest fish passage program created pursuant to RCW 76.13.150 and other efforts to address fish passage barriers owned by private parties that are in the same stream systems as barriers owned by public entities.

. The department shall also provide engineering and other technical services to assist nonstate barrier owners with fish passage barrier removal projects, provided that the barrier removal projects have been identified as a priority by the department and the department has received an appropriation to continue that component of a fish barrier removal program.

. Nothing in this section is intended to:

.. Alter the process and prioritization methods used in the implementation of the forest practices rules, as that term is defined in RCW 76.09.020, or the family forest fish passage program, created pursuant to RCW 76.13.150, that provides public cost assistance to small forestland owners associated with the road maintenance and abandonment processes; or

.. Prohibit or delay fish barrier projects undertaken by the department of transportation or another state agency that are a component of an overall transportation improvement project or that are being undertaken as a direct result of state law, federal law, or a court order. However, the department of transportation or another state agency is required to work in partnership with the fish passage barrier removal board created in RCW 77.95.160 to ensure that the scheduling, staging, and implementation of these projects are, to [the] maximum extent practicable, consistent with the coordinated and prioritized approach adopted by the fish passage barrier removal board.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2251-S2.SL.pdf?cite=2014%20c%20120%20§%202[2014 c 120 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2617-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%207%20§%2083[2010 1st sp.s. c 7 § 83]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5064-S2.SL.pdf?cite=1995%20c%20367%20§%203[1995 c 367 § 3]; ]

== 77.95.185 - Local fish passage barrier removal—Compensatory mitigation preference—Mitigation framework for off-site and out-of-kind barriers—In lieu fee program.
. The department of transportation, the department of ecology, and the department of fish and wildlife must use their existing authorities and guidance to provide a preference for the removal of existing fish passage barriers owned by cities and counties as compensatory mitigation for environmental impacts of transportation projects where appropriate.

. [Empty]
.. The department of transportation, the department of ecology, and the department of fish and wildlife must consult with other relevant entities to develop a framework for encouraging off-site and out-of-kind local fish passage barrier mitigation that provides results that are consistent with habitat protection priorities and are ecologically preferable to on-site mitigation.

.. The implementation of this framework must:

... Not delay transportation project delivery;

... Not be additive to the amount or cost of mitigation required under existing regulations;

... Not preclude on-site or off-site and in-kind mitigation when that is the most ecologically appropriate means to address project impacts;

... Not alter the mitigation sequencing principles of first avoidance and then minimization of impacts before compensatory mitigation;

.. Provide for a mechanism that identifies whether environmental impacts from projects are appropriate for local fish passage barrier mitigation;

.. Provide a mechanism for affected parties, including tribes, to determine when and how to use off-site and out-of-kind mitigation to address fish passage barriers in particular watersheds;

.. Consult the statewide fish passage barrier removal strategy developed by the fish passage barrier removal board created in RCW 77.95.160 and information provided by affected tribes, salmon recovery regional organizations, and local entities to identify specific priority locations where removal of local barriers would provide a net resource gain; and

.. Consistent with existing mitigation regulations and guidelines, provide a preference, where appropriate, for investment in local fish passage barrier removal where greater environmental benefit can be achieved with off-site and out-of-kind mitigation.

.. In addition to the framework developed in (b) of this subsection, the department of transportation, the department of ecology, and the department of fish and wildlife must develop and implement an umbrella statewide in lieu fee program or other formal means to provide a streamlined mechanism to undertake priority local fish passage barrier corrections throughout the watersheds of the state as a preferred means of compensatory mitigation where appropriate for state transportation that is consistent with the principles in (a) and (b) of this subsection.

. Nothing in this section is intended to create or expand the state's obligation for fish passage barrier correction according to existing law or court ruling. Nothing in this section is intended to decrease funding or otherwise impede the state's efforts to meet its obligation for fish passage barrier correction according to existing law or court ruling.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5996-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2017%20§%2010[2015 3rd sp.s. c 17 § 10]; ]

== 77.95.190 - Field testing of remote site incubators.
The department shall field test coho and chinook salmon remote site incubators. The purpose of field testing efforts shall be to gather conclusive scientific data on the effectiveness of coho and chinook remote site incubators.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2617-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%207%20§%2084[2010 1st sp.s. c 7 § 84]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5064-S2.SL.pdf?cite=1995%20c%20367%20§%2010[1995 c 367 § 10]; ]

== 77.95.200 - Remote site incubator program—Reports to the fish and wildlife commission.
. The department shall develop and implement a program utilizing remote site incubators in Washington state. The program shall identify sites in tributaries that are suitable for reestablishing self-sustaining, locally adapted populations of coho, chum, or chinook salmon. The initial selection of sites shall be updated annually.

. The department may only approve a remote site incubator project if the department deems it is consistent with the conservation of wild salmon and trout. The department shall only utilize appropriate salmonid eggs in remote site incubators, and may acquire eggs by gift or purchase.

. The department shall depend chiefly upon volunteer efforts to implement the remote site incubator program through volunteer cooperative projects and the regional fisheries enhancement groups. The department may prioritize remote site incubator projects within regional enhancement areas.

. The department may purchase remote site incubators and may use agency employees to construct remote site incubators. 

. The department shall investigate the use of the remote site incubator technology for the production of warm water fish.

. Annual reports on the progress of the program shall be provided to the fish and wildlife commission.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1778-S.SL.pdf?cite=2009%20c%20333%20§%2029[2009 c 333 § 29]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6324-S.SL.pdf?cite=1998%20c%20251%20§%202[1998 c 251 § 2]; ]

== 77.95.210 - Sale of surplus salmon eggs—Order of priority.
. Except as provided in subsection (2) of this section, the department may supply, at a reasonable charge, surplus salmon eggs to a person for use in the cultivation of salmon. The department shall not intentionally create a surplus of salmon to provide eggs for sale. The department shall only sell salmon eggs from stocks that are not suitable for salmon population rehabilitation or enhancement in state waters in Washington after the salmon harvest on surplus salmon has been first maximized by both commercial and recreational fishers.

. The department shall not destroy hatchery origin salmon for the purposes of destroying viable eggs that would otherwise be useful for propagation or salmon recovery purposes, as determined by the department and Indian tribes with treaty fishing rights in a collaborative manner, for replenishing fish runs. Eggs deemed surplus by the state must be provided, in the following order of priority, to:

.. Voluntary cooperative salmon culture programs under the supervision of the department under chapter 77.100 RCW;

.. Regional fisheries enhancement group salmon culture programs under the supervision of the department under this chapter;

.. Salmon culture programs requested by lead entities and approved by the salmon funding recovery board under chapter 77.85 RCW;

.. Hatcheries of federally approved tribes in Washington to whom eggs are moved, not sold, under the interlocal cooperation act, chapter 39.34 RCW; and

.. Governmental hatcheries in Washington, Oregon, and Idaho.

The order of priority established in this subsection for distributing surplus eggs does not apply when there is a shortfall in the supply of eggs.

. All sales, provisions, distributions, or transfers shall be consistent with the department's egg transfer and aquaculture disease control regulations as now existing or hereafter amended. Prior to department determination that eggs of a salmon stock are surplus and available for sale, the department shall assess the productivity of each watershed that is suitable for receiving eggs.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1286-S.SL.pdf?cite=2001%20c%20337%20§%201[2001 c 337 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2011[2000 c 107 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c115.pdf?cite=1988%20c%20115%20§%201[1988 c 115 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%2025[1983 1st ex.s. c 46 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c23.pdf?cite=1974%20ex.s.%20c%2023%20§%201[1974 ex.s. c 23 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c35.pdf?cite=1971%20c%2035%20§%204[1971 c 35 § 4]; ]

== 77.95.220 - Legislative finding.
The legislature finds that:

. The fishery resources of Washington are critical to the social and economic needs of the citizens of the state;

. Salmon production is dependent on both wild and artificial production;

. The department is directed to enhance Washington's salmon runs; and

. Full utilization of the state's salmon rearing facilities is necessary to enhance commercial and recreational fisheries.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2055-S.SL.pdf?cite=1993%20sp.s.%20c%202%20§%2024[1993 sp.s. c 2 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c336.pdf?cite=1989%20c%20336%20§%201[1989 c 336 § 1]; ]

== 77.95.230 - Director's determination of salmon production costs.
The director shall determine the cost of operating all state-funded salmon production facilities at full capacity and shall provide this information with the department's biennial budget request.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c336.pdf?cite=1989%20c%20336%20§%202[1989 c 336 § 2]; ]

== 77.95.240 - State purchase of private salmon smolts.
The director may contract with cooperatives or private aquaculturists for the purchase of quality salmon smolts for release into public waters if all department fish rearing facilities are operating at full capacity. The intent of cooperative and private sector contracting is to explore the opportunities of cooperatively producing more salmon for the public fisheries without incurring additional capital expense for the department.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c336.pdf?cite=1989%20c%20336%20§%203[1989 c 336 § 3]; ]

== 77.95.250 - State purchase of private salmon smolts—Bids.
If the director elects to contract with cooperatives or private aquaculturists for the purpose of purchasing quality salmon smolts, contracting shall be done by a competitive bid process. In awarding contracts to private contractors, the director shall give preference to nonprofit corporations. The director shall establish the criteria for the contract, which shall include but not be limited to species, size of smolt, stock composition, quantity, quality, rearing location, release location, and other pertinent factors.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c336.pdf?cite=1989%20c%20336%20§%204[1989 c 336 § 4]; ]

== 77.95.260 - State purchase of private salmon smolts—Private ocean ranching not authorized.
Nothing in chapter 336, Laws of 1989 shall authorize the practice of private ocean ranching. Privately contracted smolts become the property of the state at the time of release.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c336.pdf?cite=1989%20c%20336%20§%205[1989 c 336 § 5]; ]

== 77.95.270 - State purchase of private salmon smolts—Availability of excess salmon eggs.
Except as provided in RCW 77.95.210, the department may make available to private contractors salmon eggs in excess of department hatchery needs for the purpose of contract rearing to release the smolts into public waters. However, providing salmon eggs as specified in RCW 77.95.210(2) has the highest priority. The priority of providing eggs surplus after meeting the requirements of RCW 77.95.210(2) to contract rearing is a higher priority than providing eggs to aquaculture purposes that are not destined for release into Washington public waters.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1286-S.SL.pdf?cite=2001%20c%20337%20§%202[2001 c 337 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c336.pdf?cite=1989%20c%20336%20§%206[1989 c 336 § 6]; ]

== 77.95.280 - Chinook and coho salmon—External marking of hatchery-produced fish—Findings.
The legislature declares that the state has a vital interest in the continuation of recreational fisheries for chinook salmon and coho salmon in mixed stock areas, and that the harvest of hatchery origin salmon should be encouraged while wild salmon should be afforded additional protection when required. A program of selective harvest shall be developed utilizing hatchery salmon that are externally marked in a conspicuous manner, regulations that promote the unharmed release of unmarked fish, when and where appropriate, and a public information program that educates the public about the need to protect depressed stocks of wild salmon.

The legislature further declares that the establishment of other incentives for commercial fishing and fish processing in Washington will complement the program of selective harvest in mixed stock fisheries anticipated by this legislation.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5157-S2.SL.pdf?cite=1995%20c%20372%20§%201[1995 c 372 § 1]; ]

== 77.95.290 - Chinook and coho salmon—External marking of hatchery-produced fish—Program.
The department shall mark appropriate coho salmon that are released from department operated hatcheries and rearing ponds in such a manner that the fish are externally recognizable as hatchery origin salmon by fishers for the purpose of maximized catch while sustaining wild and hatchery reproduction.

The department shall mark all appropriate chinook salmon targeted for contribution to the Washington catch that are released from department operated hatcheries and rearing ponds in such a manner that the fish are externally recognizable as hatchery origin salmon by fishers.

The goal of the marking program is: (1) The annual marking by June 30, 1997, of all appropriate hatchery origin coho salmon produced by the department with marking to begin with the 1994 Puget Sound coho brood; and (2) the annual marking by June 30, 1999, of all appropriate hatchery origin chinook salmon produced by the department with marking to begin with the 1998 chinook brood. The department may experiment with different methods for marking hatchery salmon with the primary objective of maximum survival of hatchery marked fish, maximum contribution to fisheries, and minimum cost consistent with the other goals.

The department shall coordinate with other entities that are producing hatchery chinook and coho salmon for release into public waters to enable the broadest application of the marking program to all hatchery produced chinook and coho salmon. The department shall work with the treaty Indian tribes in order to reach mutual agreement on the implementation of the mass marking program. The ultimate goal of the program is the coast-wide marking of appropriate hatchery origin chinook and coho salmon, and the protection of all wild chinook and coho salmon, where appropriate.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5915.SL.pdf?cite=1999%20c%20372%20§%2015[1999 c 372 § 15]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6264-S2.SL.pdf?cite=1998%20c%20250%20§%202[1998 c 250 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5157-S2.SL.pdf?cite=1995%20c%20372%20§%202[1995 c 372 § 2]; ]

== 77.95.300 - Chinook and coho salmon—External marking of hatchery-produced fish—Rules.
The department shall adopt rules to control the mixed stock chinook and coho fisheries of the state so as to sustain healthy stocks of wild salmon, allow the maximum survival of wild salmon, allow for spatially separated fisheries that target on hatchery stocks, foster the best techniques for releasing wild chinook and coho salmon, and contribute to the economic viability of the fishing businesses of the state.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5157-S2.SL.pdf?cite=1995%20c%20372%20§%203[1995 c 372 § 3]; ]

== 77.95.310 - Report identifying total salmon and steelhead harvest.
. The department shall maintain a report identifying total salmon and steelhead harvest. This report shall include the final commercial harvests and recreational harvests. At a minimum, the report shall clearly identify:

.. The total treaty tribal and nontribal harvests by species and by management unit;

.. Where and why the nontribal harvest does not meet the full allocation allowed under United States v. Washington, 384 F. Supp. 312 (1974) (Boldt I) including a summary of the key policies within the management plan that result in a less than full nontribal allocation; and

.. The location and quantity of salmon and steelhead harvested under the wastage provisions of United States v. Washington, 384 F. Supp. 312 (1974).

. Upon request, the department shall present the report required to be maintained under this section to the appropriate committees of the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1778-S.SL.pdf?cite=2009%20c%20333%20§%2030[2009 c 333 § 30]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1485-S.SL.pdf?cite=1997%20c%20414%20§%201[1997 c 414 § 1]; ]

== 77.95.320 - Program utilizing department-partnership agreements to operate and manage certain hatcheries—Selection of partners—Partnership agreements.
. The department shall establish a program that utilizes department-partner agreements for the resumption or continued operation and management of state-owned salmonid hatcheries that are located in the Hood Canal basin. To implement the program, the department shall accept and review applications to determine the appropriateness of the partner to manage and operate selected salmonid hatcheries. The department shall accelerate the application process relating to any hatchery currently in operation to avoid cessation of ongoing salmon production.

. [Empty]
.. To select a partner, the department shall develop and apply criteria identifying the appropriateness of a potential partner. The criteria must seek to ensure that the partner has a long-range business plan, which may include the sale of hatchery surplus salmon, including eggs and carcasses, to ensure the long-range future solvency of the partnership. The business plan may also allow the partner to harvest hatchery chum salmon in a designated area through persons under contract with the partner as provided under a permit from the department or by rule of the commission. All chum salmon harvested must be sold at prices commensurate with the current market and all funds must be utilized by the partner to operate the hatchery.

.. Partners under this section must be:

... Qualified under section 501(c)(3) of the internal revenue code;

... A for-profit private entity; or

... A federally recognized tribe.

. The department shall place a higher priority on applications from partners that provide for the maximum resumption or continuation of existing hatchery production in a manner consistent with the mandate contained in RCW 77.04.012 to maintain the economic well-being and stability of the fishing industry.

. [Empty]
.. Agreements entered into with partners under this section must be consistent with existing federally recognized tribal rights, state laws, agency rules, collective bargaining agreements, hatchery management policy involving species listed under the federal endangered species act, or, in the case of a tribal partner, any applicable tribal hatchery management policy or recreational and commercial harvest policy.

.. Agreements under this section must also require that partners give preference to retaining classified employees whenever possible. In circumstances where it is not possible, partners conducting hatchery operations must maintain staff with comparable qualifications to those identified in the class specifications for the department's fish hatchery personnel.

. All partnership agreements entered into under this section must contain a provision that requires the partner to hold harmless the department and the state for any civil liability arising from the partner's participation in the agreement or activities at the subject hatchery or hatcheries.

. All partnership agreements entered into under this section must identify any maintenance or improvements to be made to the hatchery facility, and the source of funding for such maintenance or improvements. If funding for the maintenance or improvements is to come from state funds or revenue sources previously received by the department, the work must be performed either by employees in the classified service or in compliance with the contracting procedures set forth in RCW 41.06.142.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1071-S.SL.pdf?cite=2013%20c%2093%20§%201[2013 c 93 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1951-S2.SL.pdf?cite=2009%20c%20340%20§%202[2009 c 340 § 2]; ]

== 77.95.330 - Powers and authorities conferred by chapter to be construed as in addition and supplemental.
The powers and authority conferred by this chapter must be construed as in addition and supplemental to powers or authority conferred by any other law and nothing contained in this chapter may be construed as limiting any other powers or authority of the department.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1951-S2.SL.pdf?cite=2009%20c%20340%20§%203[2009 c 340 § 3]; ]

== 77.95.340 - Identification and removal of impediments to fish passage.
The department may contract with cities and counties to assist in the identification and removal of impediments to fish passage.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2251-S2.SL.pdf?cite=2014%20c%20120%20§%206[2014 c 120 § 6]; ]

