= 77.50 - Limitations on certain commercial fisheries.
:toc:

== 77.50.010 - Limitations on commercial fishing for salmon in Puget Sound waters.
. The commission may authorize commercial fishing for sockeye salmon within the waters described in subsection (2) of this section only during the period June 10th to July 25th and for other salmon only from the second Monday of September through November 30th, except during the hours between 4:00 p.m. of Friday and 4:00 p.m. of the following Sunday.

. All waters east and south of a line commencing at a concrete monument on Angeles Point in Clallam county near the mouth of the Elwha River on which is inscribed "Angeles Point Monument" (latitude 48° 9' 3" north, longitude 123° 33' 01" west of Greenwich Meridian); thence running east on a line 81° 30' true across the flashlight and bell buoy off Partridge Point and thence continued to longitude 122° 40' west; thence north to the southerly shore of Sinclair Island; thence along the southerly shore of the island to the most easterly point of the island; thence 46° true to Carter Point, the most southerly point of Lummi Island; thence northwesterly along the westerly shore line of Lummi Island to where the shore line intersects line of longitude 122° 40' west; thence north to the mainland, including: The southerly portion of Hale Passage, Bellingham Bay, Padilla Bay, Fidalgo Bay, Guemes Channel, Skagit Bay, Similk Bay, Saratoga Passage, Holmes Harbor, Possession Sound, Admiralty Inlet, Hood Canal, Puget Sound, and their inlets, passages, waters, waterways, and tributaries.

. The commission may authorize commercial fishing for salmon with gill net, purse seine, and other lawful gear prior to the second Monday in September within the waters of Hale Passage, Bellingham Bay, Samish Bay, Padilla Bay, Fidalgo Bay, Guemes Channel, Skagit Bay, and Similk Bay, to wit: Those waters northerly and easterly of a line commencing at Stanwood, thence along the south shore of Skagit Bay to Rocky Point on Camano Island; thence northerly to Polnell Point on Whidbey Island.

. Whenever the commission determines that a stock or run of salmon cannot be harvested in the usual manner, and that the stock or run of salmon may be in danger of being wasted and surplus to natural or artificial spawning requirements, the commission may authorize units of gill net and purse seine gear in any number or equivalents, by time and area, to fully utilize the harvestable portions of these salmon runs for the economic well being of the citizens of this state. Gill net and purse seine gear other than emergency and test gear authorized by the director shall not be used in Lake Washington.

. The commission may authorize commercial fishing for pink salmon in each odd-numbered year from August 1st through September 1st in the waters lying inside of a line commencing at the most easterly point of Dungeness Spit and thence projected to Point Partridge on Whidbey Island and a line commencing at Olele Point and thence projected easterly to Bush Point on Whidbey Island.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2625.SL.pdf?cite=2002%20c%20311%20§%202[2002 c 311 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=1998%20c%20190%20§%2075[1998 c 190 § 75]; 1995 1st sp.s. c 2 § 25 (Referendum Bill No. 45, approved November 7, 1995); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%2046[1983 1st ex.s. c 46 § 46]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c220.pdf?cite=1973%201st%20ex.s.%20c%20220%20§%202[1973 1st ex.s. c 220 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c283.pdf?cite=1971%20ex.s.%20c%20283%20§%2013[1971 ex.s. c 283 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c12.pdf?cite=1955%20c%2012%20§%2075.12.010[1955 c 12 § 75.12.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c112.pdf?cite=1949%20c%20112%20§%2028[1949 c 112 § 28]; Rem. Supp. 1949 § 5780-301; ]

== 77.50.020 - Limitations on commercial fishing for chinook or coho salmon in Pacific Ocean and Straits of Juan de Fuca.
. The commission may authorize commercial fishing for coho salmon in the Pacific Ocean and the Straits of Juan de Fuca only from June 16th through October 31st.

. The commission may authorize commercial fishing for chinook salmon in the Pacific Ocean and the Straits of Juan de Fuca only from March 15th through October 31st.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=1998%20c%20190%20§%2076[1998 c 190 § 76]; 1995 1st sp.s. c 2 § 26 (Referendum Bill No. 45, approved November 7, 1995); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%2048[1983 1st ex.s. c 46 § 48]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c12.pdf?cite=1955%20c%2012%20§%2075.18.020[1955 c 12 § 75.18.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c147.pdf?cite=1953%20c%20147%20§%203[1953 c 147 § 3]; ]

== 77.50.030 - Salmon fishing gear.
. A person shall not use, operate, or maintain a gill net which exceeds one thousand five hundred feet in length or a drag seine in the waters of the Columbia river for catching salmon.

. A person shall not construct, install, use, operate, or maintain within state waters a pound net, round haul net, lampara net, fish trap, fish wheel, scow fish wheel, set net, weir, or fixed appliance for catching salmon or steelhead except under the authority of a trial or experimental fishery permit, when an emerging commercial fishery has been designated allowing use of one or more of these gear types. The director must consult with the commercial fishing interests that would be affected by the trial or experimental fishery permit. The director may authorize the use of this gear for scientific investigations.

. The department, in coordination with the Oregon department of fish and wildlife, shall adopt rules to regulate the use of monofilament in gill net webbing on the Columbia river.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5442-S.SL.pdf?cite=2001%20c%20163%20§%202[2001 c 163 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=1998%20c%20190%20§%2077[1998 c 190 § 77]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2055-S.SL.pdf?cite=1993%20sp.s.%20c%202%20§%2027[1993 sp.s. c 2 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c147.pdf?cite=1985%20c%20147%20§%201[1985 c 147 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%2052[1983 1st ex.s. c 46 § 52]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c12.pdf?cite=1955%20c%2012%20§%2075.12.040[1955 c 12 § 75.12.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c112.pdf?cite=1949%20c%20112%20§%2029[1949 c 112 § 29]; Rem. Supp. 1949 § 5780-303; ]

== 77.50.040 - Commercial net fishing for salmon in tributaries of Columbia river—Boundaries defined.
. The commission shall adopt rules defining geographical boundaries of the following Columbia river tributaries and sloughs:

.. Washougal river;

.. Camas slough;

.. Lewis river;

.. Kalama river;

.. Cowlitz river;

.. Elokomin river;

.. Elokomin sloughs;

.. Skamokawa sloughs;

.. Grays river;

.. Deep river;

.. Grays bay.

. The commission may authorize commercial net fishing for salmon in the tributaries and sloughs from September 1st to November 30th only, if the time, areas, and level of effort are regulated in order to maximize the recreational fishing opportunity while minimizing excess returns of fish to hatcheries. The commission shall not authorize commercial net fishing if a significant catch of steelhead would occur.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=1998%20c%20190%20§%2078[1998 c 190 § 78]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c80.pdf?cite=1984%20c%2080%20§%205[1984 c 80 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c245.pdf?cite=1983%20c%20245%20§%201[1983 c 245 § 1]; ]

== 77.50.050 - Reef net salmon fishing gear—Reef net areas specified.
The commission shall not authorize use of reef net fishing gear except in the reef net areas described in this section.

. Point Roberts reef net fishing area includes those waters within 250 feet on each side of a line projected 129° true from a point at longitude 123° 01' 15" W. latitude 48° 58' 38" N. to a point one mile distant, as such description is shown upon the United States Coast and Geodetic Survey map numbered 6300, published September, 1941, in Washington, D.C., eleventh edition.

. Cherry Point reef net fishing area includes those waters inland and inside the 10-fathom line between lines projected 205° true from points on the mainland at longitude 122° 44' 54" latitude 48° 51' 48" and longitude 122° 44' 18" latitude 48° 51' 33", a [as] such descriptions are shown upon the United States Coast and Geodetic Survey map numbered 6380, published March, 1947, in Washington, D.C., eighth edition.

. Lummi Island reef net fishing area includes those waters inland and inside a line projected from Village Point 208° true to a point 900 yards distant, thence 129° true to the point of intersection with a line projected 259° true from the shore of Lummi Island 122° 40' 42" latitude 48° 41' 32", as such descriptions are shown upon the United States Coast and Geodetic Survey map numbered 6380, published March, 1947, in Washington, D.C., eighth edition, revised 11-25-57, save and except that there shall be excluded therefrom all waters lying inside of a line projected 259° true from a point at 122° 40' 42" latitude 48° 41' 32" to a point 300 yards distant from high tide, thence in a northerly direction to the United States Coast and Geodetic Survey reference mark number 2, 1941-1950, located on that point on Lummi Island known as Lovers Point, as such descriptions are shown upon the United States Coast and Geodetic Survey map number 6380 as aforesaid. The term "Village Point" as used herein shall be construed to mean a point of location on Village Point, Lummi Island, at the mean high tide line on a true bearing of 43° 53' a distance of 457 feet to the center of the chimney of a wood frame house on the east side of the county road. Said chimney and house being described as Village Point Chimney on page 612 of the United States Coast and Geodetic Survey list of geographic positions No. G-5455, Rosario Strait.

. Sinclair Island reef net fishing area includes those waters inland and inside a line projected from the northern point of Sinclair Island to Boulder reef, thence 200° true to the northwesterly point of Sinclair Island, as such descriptions are shown upon the United States Coast and Geodetic Survey map numbered 6380, published March, 1947, in Washington, D.C., eighth edition.

. Flat Point reef net fishing area includes those waters within a radius of 175 feet of a point off Lopez Island located at longitude 122° 55' 24" latitude 48° 32' 33", as such description is shown upon the United States Coast and Geodetic Survey map numbered 6380, published March, 1947, in Washington, D.C., eighth edition.

. Lopez Island reef net fishing area includes those waters within 400 yards of shore between lines projected true west from points on the shore of Lopez Island at longitude 122° 55' 04" latitude 48° 31' 59" and longitude 122° 55' 54" latitude 48° 30' 55", as such descriptions are shown upon the United States Coast and Geodetic Survey map numbered 6380, published March, 1947, in Washington, D.C., eighth edition.

. Iceberg Point reef net fishing area includes those waters inland and inside a line projected from Davis Point on Lopez Island to the west point of Long Island, thence to the southern point of Hall Island, thence to the eastern point at the entrance to Jones Bay, and thence to the southern point at the entrance to Mackaye Harbor on Lopez Island; and those waters inland and inside a line projected 320° from Iceberg Point light on Lopez Island, a distance of 400 feet, thence easterly to the point on Lopez Island at longitude 122° 53' 00" latitude 48° 25' 39", as such descriptions are shown upon the United States Coast and Geodetic Survey map numbered 6380, published March, 1947, in Washington, D.C., eighth edition.

. Aleck Bay reef net fishing area includes those waters inland and inside a line projected from the southwestern point at the entrance to Aleck Bay on Lopez Island at longitude 122° 51' 11" latitude 48° 25' 14" southeasterly 800 yards to the submerged rock shown on U.S.G.S. map number 6380, thence northerly to the cove on Lopez Island at longitude 122° 50' 49" latitude 48° 25' 42", as such descriptions are shown upon the United States Coast and Geodetic Survey map numbered 6380, published March, 1947, in Washington, D.C., eighth edition.

. Shaw Island reef net fishing area number 1 includes those waters within 300 yards of shore between lines projected true south from points on Shaw Island at longitude 122° 56' 14" latitude 48° 33' 28" and longitude 122° 57' 29" latitude 48° 32' 58", as such descriptions are shown upon the United States Coast and Geodetic Survey map numbered 6380, published March, 1947, in Washington, D.C., eighth edition.

. Shaw Island reef net fishing area number 2 includes those waters inland and inside a line projected from Point George on Shaw Island to the westerly point of Neck Point on Shaw Island, as such description is shown upon the United States Coast and Geodetic Survey map numbered 6380, published March, 1947, in Washington, D.C., eighth edition.

. Stuart Island reef net fishing area number 1 includes those waters within 600 feet of the shore of Stuart Island between lines projected true east from points at longitude 123° 10' 47" latitude 48° 39' 47" and longitude 123° 10' 47" latitude 48° 39' 33", as such descriptions are shown upon the United States Coast and Geodetic Survey map numbered 6380, published March, 1947, in Washington, D.C., eighth edition.

. Stuart Island reef net fishing area number 2 includes those waters within 250 feet of Gossip Island, also known as Happy Island, as such description is shown upon the United States Coast and Geodetic Survey map numbered 6380, published March, 1947, in Washington, D.C., eighth edition.

. Johns Island reef net fishing area includes those waters inland and inside a line projected from the eastern point of Johns Island to the northwestern point of Little Cactus Island, thence northwesterly to a point on Johns Island at longitude 123° 09' 24" latitude 48° 39' 59", as such descriptions are shown upon the United States Coast and Geodetic Survey map numbered 6380, published March, 1947, in Washington, D.C., eighth edition.

. Battleship Island reef net fishing area includes those waters lying within 350 feet of Battleship Island, as such description is shown upon the United States Coast and Geodetic Survey map numbered 6380, published March, 1947, in Washington, D.C., eighth edition.

. Open Bay reef net fishing area includes those waters lying within 150 feet of shore between lines projected true east from a point on Henry Island at longitude 123° 11' 34 1/2" latitude 48° 35' 27 1/2" at a point 250 feet south, as such descriptions are shown upon the United States Coast and Geodetic Survey map numbered 6380, published March, 1947, in Washington, D.C., eighth edition.

. Mitchell Reef net fishing area includes those waters within a line beginning at the rock shown on U.S.G.S. map number 6380 at longitude 123° 10' 56" latitude 48° 34' 49 1/2", and projected 50 feet northwesterly, thence southwesterly 250 feet, thence southeasterly 300 feet, thence northeasterly 250 feet, thence to the point of beginning, as such descriptions are shown upon the United States Coast and Geodetic Survey map numbered 6380, published March, 1947, in Washington, D.C., eighth edition.

. Smugglers Cove reef fishing area includes those waters within 200 feet of shore between lines projected true west from points on the shore of San Juan Island at longitude 123° 10' 29" latitude 48° 33' 50" and longitude 123° 10' 31" latitude 48° 33' 45", as such descriptions are shown upon the United States Coast and Geodetic Survey map numbered 6380, published March, 1947, in Washington, D.C., eighth edition.

. Andrews Bay reef net fishing area includes those waters lying within 300 feet of the shore of San Juan Island between a line projected true south from a point at the northern entrance of Andrews Bay at longitude 123° 09' 53 1/2" latitude 48° 33' 00" and the cable crossing sign in Andrews Bay, at longitude 123° 09' 45" latitude 48° 33' 04", as such descriptions are shown upon the United States Coast and Geodetic Survey map numbered 6380, published March, 1947, in Washington, D.C., eighth edition.

. Orcas Island reef net fishing area includes those waters inland and inside a line projected true west a distance of 1,000 yards from the shore of Orcas Island at longitude 122° 57' 40" latitude 48° 41' 06" thence northeasterly to a point 500 feet true west of Point Doughty, then true east to Point Doughty, as such descriptions are shown upon the United States Coast and Geodetic Survey map numbered 6380, published March, 1947, in Washington, D.C., eighth edition.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=1998%20c%20190%20§%2079[1998 c 190 § 79]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%2059[1983 1st ex.s. c 46 § 59]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c64.pdf?cite=1965%20c%2064%20§%201[1965 c 64 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c236.pdf?cite=1961%20c%20236%20§%201[1961 c 236 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c309.pdf?cite=1959%20c%20309%20§%201[1959 c 309 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c276.pdf?cite=1955%20c%20276%20§%202[1955 c 276 § 2]; ]

== 77.50.060 - Unauthorized fishing vessels entering state waters.
In order to protect the welfare of the citizens of the state of Washington by protecting the natural resources of the state from illegal fishing in state waters, commercial fishing vessels which are not authorized by law to fish for salmon in Washington state waters cannot enter Washington state waters unless all salmon fishing gear is stowed below deck or placed in a position so that it is not readily available for fishing.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c262.pdf?cite=1987%20c%20262%20§%201[1987 c 262 § 1]; ]

== 77.50.070 - Limitation on salmon fishing gear in Pacific Ocean.
. Except as provided in subsection (2) of this section, the commission shall not authorize gear other than troll gear or angling gear for taking salmon within the offshore waters or the waters of the Pacific Ocean over which the state has jurisdiction lying west of the following line: Commencing at the point of intersection of the international boundary line in the Strait of Juan de Fuca and a line drawn between the lighthouse on Tatoosh Island in Clallam County and Bonilla Point on Vancouver Island; thence southerly to the lighthouse on Tatoosh Island; thence southerly to the most westerly point of Cape Flattery; thence southerly along the state shoreline of the Pacific Ocean, crossing any river mouths at their most westerly points of land, to Point Brown at the entrance to Grays Harbor; thence southerly to Point Chehalis Light on Point Chehalis; thence southerly from Point Chehalis along the state shoreline of the Pacific Ocean to the Cape Shoalwater tower at the entrance to Willapa Bay; thence southerly to Leadbetter Point; thence southerly along the state shoreline of the Pacific Ocean to the inshore end of the North jetty at the entrance to the Columbia River; thence southerly to the knuckle of the South jetty at the entrance to said river.

. The commission may authorize the use of nets for taking salmon in the waters described in subsection (1) of this section for scientific investigations.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=1998%20c%20190%20§%2080[1998 c 190 § 80]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5126.SL.pdf?cite=1993%20c%2020%20§%202[1993 c 20 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%2060[1983 1st ex.s. c 46 § 60]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c108.pdf?cite=1957%20c%20108%20§%203[1957 c 108 § 3]; ]

== 77.50.080 - Possession or transportation in Pacific Ocean of salmon taken by other than troll lines or angling gear.
Within the waters described in RCW 77.50.070, a person shall not transport or possess salmon on board a vessel carrying fishing gear of a type other than troll lines or angling gear, unless accompanied by a certificate issued by a state or country showing that the salmon have been lawfully taken within the territorial waters of the state or country.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%2013[2000 c 107 § 13]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=1998%20c%20190%20§%2081[1998 c 190 § 81]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%2061[1983 1st ex.s. c 46 § 61]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c234.pdf?cite=1963%20c%20234%20§%202[1963 c 234 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c108.pdf?cite=1957%20c%20108%20§%205[1957 c 108 § 5]; ]

== 77.50.090 - Bottom trawling not authorized—Areas specified.
The commission shall not authorize commercial bottom trawling for food fish and shellfish in all areas of Hood Canal south of a line projected from Tala Point to Foulweather Bluff and in Puget Sound south of a line projected from Foulweather Bluff to Double Bluff and including all marine waters east of Whidbey Island and Camano Island.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=1998%20c%20190%20§%2082[1998 c 190 § 82]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c172.pdf?cite=1989%20c%20172%20§%201[1989 c 172 § 1]; ]

== 77.50.100 - Hood Canal shrimp—Limitation on number of shrimp pots.
The commission shall not authorize any commercial fisher to use more than fifty shrimp pots while commercially fishing for shrimp in that portion of Hood Canal lying south of the Hood Canal floating bridge.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=1998%20c%20190%20§%2083[1998 c 190 § 83]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5124.SL.pdf?cite=1993%20c%20340%20§%2050[1993 c 340 § 50]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c316.pdf?cite=1989%20c%20316%20§%209[1989 c 316 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c31.pdf?cite=1983%201st%20ex.s.%20c%2031%20§%202[1983 1st ex.s. c 31 § 2]; ]

== 77.50.110 - Commercial salmon fishing—Unauthorized gear.
The commission shall not authorize angling gear or other personal use gear for commercial salmon fishing.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=1998%20c%20190%20§%2084[1998 c 190 § 84]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2793-S.SL.pdf?cite=1996%20c%20267%20§%2024[1996 c 267 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%2069[1983 1st ex.s. c 46 § 69]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c23.pdf?cite=1969%20ex.s.%20c%2023%20§%201[1969 ex.s. c 23 § 1]; ]

== 77.50.120 - Maintaining consistent salmon harvest levels.
It is the intent of the legislature to ensure that a sustainable level of salmon is made available for harvest for commercial fishers in the state. Maintaining consistent harvest levels has become increasingly difficult with the listing of salmonid species under the federal endangered species act. Without a stable level of harvest, fishers cannot develop niche markets that maximize the economic value of the harvest. New tools and approaches are needed by fish managers to bring increased stability to the fishing industry.

In the short term, it is the legislature's intent to provide managers with tools to assure that commercial harvest of targeted stocks can continue and expand under the constraints of the federal endangered species act. There are experimental types of commercial fishing gear that could allow fishers to stabilize harvest levels by selectively targeting healthy salmon stocks.

For the longer term, the department of fish and wildlife shall proceed with changes to the operation of certain hatcheries in order to stabilize harvest levels by allowing naturally spawning and hatchery origin fish to be managed as a single run. Scientific information from such hatcheries would guide the department's approach to reducing the need to mass mark hatchery origin salmon where appropriate.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5442-S.SL.pdf?cite=2001%20c%20163%20§%201[2001 c 163 § 1]; ]

