= 77.36 - Wildlife damage.
:toc:

== 77.36.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Claim" means an application to the department for compensation under this chapter.

. "Commercial crop" means a horticultural or agricultural product, including the growing or harvested product. For the purposes of this chapter all parts of horticultural trees shall be considered a commercial crop and shall be eligible for claims.

. "Compensation" means a cash payment, materials, or service.

. "Damage" means economic losses caused by wildlife interactions.

. "Immediate family member" means spouse, state registered domestic partner, brother, sister, grandparent, parent, child, or grandchild.

. "Livestock" means cattle, sheep, and horses.

. "Owner" means a person who has a legal right to commercial crops, livestock, or other property that was damaged during a wildlife interaction.

. "Wildlife interaction" means the negative interaction and the resultant damage between wildlife and commercial crops, livestock, or other property.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5193-S2.SL.pdf?cite=2013%20c%20329%20§%201[2013 c 329 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%20184[2009 c 521 § 184]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1778-S.SL.pdf?cite=2009%20c%20333%20§%2054[2009 c 333 § 54]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6146-S2.SL.pdf?cite=1996%20c%2054%20§%202[1996 c 54 § 2]; 2001 c 274 § 2; ]

== 77.36.030 - Trapping or killing wildlife threatening human safety or causing property damage—Limitations and conditions—Rules.
. Subject to limitations and conditions established by the commission, the owner, the owner's immediate family member, the owner's documented employee, or a tenant of real property may trap, consistent with RCW 77.15.194, or kill wildlife that is threatening human safety or causing property damage on that property, without the licenses required under RCW 77.32.010 or authorization from the director under RCW 77.12.240.

. The commission shall establish the limitations and conditions of this section by rule. The rules must include:

.. Appropriate protection for threatened or endangered species;

.. Instances when verbal or written permission is required to kill wildlife;

.. Species that may be killed under this section; and

.. Requirements for the disposal of wildlife trapped or killed under this section.

. In establishing the limitations and conditions of this section, the commission shall take into consideration the recommendations of the Washington state wolf conservation and management plan.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1778-S.SL.pdf?cite=2009%20c%20333%20§%2061[2009 c 333 § 61]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6146-S2.SL.pdf?cite=1996%20c%2054%20§%204[1996 c 54 § 4]; ]

== 77.36.070 - Limit on total claims from the fish, wildlife, and conservation account per fiscal year.
The department may pay no more than one hundred twenty thousand dollars per fiscal year from the fish, wildlife, and conservation account created in RCW 77.12.170(3) for claims and assessment costs for damage to commercial crops caused by wild deer or elk submitted under RCW 77.36.100.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6072-S.SL.pdf?cite=2020%20c%20148%20§%2023[2020 c 148 § 23]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1778-S.SL.pdf?cite=2009%20c%20333%20§%2059[2009 c 333 § 59]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6146-S2.SL.pdf?cite=1996%20c%2054%20§%208[1996 c 54 § 8]; ]

== 77.36.080 - Limit on total claims from general fund per fiscal year—Emergency exceptions.
. Unless the legislature declares an emergency under this section, the department may pay no more than thirty thousand dollars per fiscal year from the general fund for claims and assessment costs for damage to commercial crops caused by wild deer or elk submitted under RCW 77.36.100.

. [Empty]
.. The legislature may declare an emergency if weather, fire, or other natural events result in deer or elk causing excessive damage to commercial crops. 

.. After an emergency declaration, the department may pay as much as may be subsequently appropriated, in addition to the funds authorized under subsection (1) of this section, for claims and assessment costs under RCW 77.36.100. Such money shall be used to pay wildlife interaction claims only if the claim meets the conditions of RCW 77.36.100 and the department has expended all funds authorized under RCW 77.36.070 or subsection (1) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1778-S.SL.pdf?cite=2009%20c%20333%20§%2060[2009 c 333 § 60]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6146-S2.SL.pdf?cite=1996%20c%2054%20§%209[1996 c 54 § 9]; 2001 c 274 § 3; ]

== 77.36.100 - Payment of claims for damage to commercial crops or livestock—Noncash compensation—Offer of materials or services to offset or prevent wildlife interactions—Appeal of decisions—Adoption of rules.
. [Empty]
.. Except as limited by RCW 77.36.070, 77.36.080, 77.36.170, and 77.36.180, the department shall offer to distribute money appropriated to pay claims to the owner of commercial crops for damage caused by wild deer or elk or to the owners of livestock that has been killed by bears, wolves, or cougars, or injured by bears, wolves, or cougars to such a degree that the market value of the livestock has been diminished. Payments for claims for damage to livestock are not subject to the limitations of RCW 77.36.070 and 77.36.080, but may not, except as provided in RCW 77.36.170 and 77.36.180, exceed the total amount specifically appropriated therefor.

.. Owners of commercial crops or livestock are only eligible for a claim under this subsection if:

... The commercial crop owner satisfies the definition of "eligible farmer" in RCW 82.08.855;

... The conditions of RCW 77.36.110 have been satisfied; and

... The damage caused to the commercial crop or livestock satisfies the criteria for damage established by the commission under (c) of this subsection.

.. The commission shall adopt and maintain by rule criteria that clarifies the damage to commercial crops and livestock qualifying for compensation under this subsection. An owner of a commercial crop or livestock must satisfy the criteria prior to receiving compensation under this subsection. The criteria for damage adopted under this subsection must include, but not be limited to, a required minimum economic loss to the owner of the commercial crop or livestock, which may not be set at a value of less than five hundred dollars.

. [Empty]
.. Subject to the availability of nonstate funds, nonstate resources other than cash, or amounts appropriated for this specific purpose, the department may offer to provide compensation to offset wildlife interactions to a person who applies to the department for compensation for damage to property other than commercial crops or livestock that is the result of a mammalian or avian species of wildlife on a case-specific basis if the conditions of RCW 77.36.110 have been satisfied and if the damage satisfies the criteria for damage established by the commission under (b) of this subsection.

.. The commission shall adopt and maintain by rule criteria for damage to property other than a commercial crop or livestock that is damaged by wildlife and may be eligible for compensation under this subsection, including criteria for filing a claim for compensation under this subsection.

. [Empty]
.. To prevent or offset wildlife interactions, the department may offer materials or services to a person who applies to the department for assistance in providing mitigating actions designed to reduce wildlife interactions if the actions are designed to address damage that satisfies the criteria for damage established by the commission under this section.

.. The commission shall adopt and maintain by rule criteria for mitigating actions designed to address wildlife interactions that may be eligible for materials and services under this section, including criteria for submitting an application under this section.

. An owner who files a claim under this section may appeal the decision of the department pursuant to rules adopted by the commission if the claim:

.. Is denied; or

.. Is disputed by the owner and the owner disagrees with the amount of compensation determined by the department.

. The commission shall adopt rules setting limits and conditions for the department's expenditures on claims and assessments for commercial crops, livestock, other property, and mitigating actions.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5193-S2.SL.pdf?cite=2013%20c%20329%20§%204[2013 c 329 § 4]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1778-S.SL.pdf?cite=2009%20c%20333%20§%2055[2009 c 333 § 55]; ]

== 77.36.110 - Eligibility for compensation under this chapter—Adoption of rules.
. No owner may receive compensation for wildlife interactions under this chapter unless the owner has, as determined by the department, first:

.. Utilized applicable legal and practicable self-help preventive measures available to prevent the damage, including the use of nonlethal methods and department-provided materials and services when available under RCW 77.36.100; and

.. Exhausted all available compensation options available from nonprofit organizations that provide compensation to private property owners due to financial losses caused by wildlife interactions.

. In determining if the requirements of this section have been satisfied, the department may recognize and consider the following:

.. Property losses may occur without future or anticipated knowledge of potential problems resulting in an owner being unable to take preemptive measures.

.. Normal agricultural practices, animal husbandry practices, recognized standard management techniques, and other industry-recognized management practices may represent adequate preventative efforts.

.. Under certain circumstances, as determined by the department, wildlife may not logistically or practicably be managed by nonlethal efforts.

.. Not all available legal preventative efforts are cost-effective for the owner to practicably employ.

.. There are certain effective preventative control options not available due to federal or state restrictions.

.. Under certain circumstances, as determined by the department, permitting public hunting may not be a practicable self-help method due to the size and nature of the property, the property's setting, or the ability of the landowner to accommodate public access.

. An owner is not eligible to receive compensation if the damages are covered by insurance.

. The commission shall adopt rules implementing this section, including requirements that owners document nonlethal preventive efforts undertaken and all permits issued by the department under RCW 77.12.240 and 77.12.150.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1778-S.SL.pdf?cite=2009%20c%20333%20§%2056[2009 c 333 § 56]; ]

== 77.36.120 - Department's duties.
The department shall establish:

. The form of affidavits or proof required to accompany all claims under this chapter;

. The process, time, and methods used to identify and assess damage, including the anticipated timeline for the initiation and conclusion of department action;

. How claims will be prioritized when available funds for reimbursement are limited;

. Timelines after the discovery of damage by which an owner must file a claim or notify the department;

. Protocols for an owner to follow if the owner wishes to undertake activities that would complicate the determination of damages, such as harvesting damaged crops;

. The process for determining damage assessments, including the role and selection of professional damage assessors and the responsibility for reimbursing third-party assessors for their services;

. Timelines for a claimant to accept, reject, or appeal a determination made by the department; 

. The identification of instances when an owner would be ineligible for compensation; 

. An appeals process for an owner eligible for compensation under RCW 77.36.100 who is denied a claim or feels the compensation is insufficient; and

. Other policies necessary for administering this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1778-S.SL.pdf?cite=2009%20c%20333%20§%2057[2009 c 333 § 57]; ]

== 77.36.130 - Limit on cash compensation—Burden of proof.
. Except as otherwise provided in this section and as limited by RCW 77.36.100, 77.36.070, 77.36.080, 77.36.170, and 77.36.180, the cash compensation portion of each claim by the department under this chapter is limited to the lesser of:

.. The value of the damage to the property by wildlife, reduced by the amount of compensation provided to the claimant by any nonprofit organizations that provide compensation to private property owners due to financial losses caused by wildlife interactions. The value of killed or injured livestock may be no more than the market value of the lost livestock subject to the conditions and criteria established by rule of the commission; or

.. Ten thousand dollars.

. The department may offer to pay a claim for an amount in excess of ten thousand dollars to the owners of commercial crops or livestock filing a claim under RCW 77.36.100 only if the outcome of an appeal filed by the claimant under RCW 77.36.100 determines a payment higher than ten thousand dollars.

. All payments of claims by the department under this chapter must be paid to the owner of the damaged property and may not be assigned to a third party.

. The burden of proving all property damage, including damage to commercial crops and livestock, belongs to the claimant.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5193-S2.SL.pdf?cite=2013%20c%20329%20§%205[2013 c 329 § 5]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1778-S.SL.pdf?cite=2009%20c%20333%20§%2058[2009 c 333 § 58]; ]

== 77.36.140 - Chapter represents exclusive remedy.
This chapter represents the exclusive remedy against the state for damage caused by wildlife interactions.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1778-S.SL.pdf?cite=2009%20c%20333%20§%2062[2009 c 333 § 62]; ]

== 77.36.160 - Request for relocating beaver.
. Whenever the department receives a request for relocating beaver, the department must inform the requesting party of locations, if available, of surplus beaver available for capture and relocation. The department may identify nuisance beaver or areas with thriving beaver populations as a source population for capturing and relocating beaver.

. The department shall post on the agency's website quarterly reports of nuisance beaver activity, beaver trapping, and beaver relocations reported to the department.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2349-S.SL.pdf?cite=2012%20c%20167%20§%203[2012 c 167 § 3]; ]

== 77.36.170 - Limit on amount paid for injury or loss of livestock caused by wolves—Exceptions.
. The department may pay no more than fifty thousand dollars per fiscal year from the limited fish and wildlife account created in RCW 77.12.170(1) for claims and assessment costs for injury or loss of livestock caused by wolves submitted under RCW 77.36.100.

. Notwithstanding other provisions of this chapter, the department may also accept and expend money from other sources to address injury or loss of livestock or other property caused by wolves consistent with the requirements on that source of funding.

. If any wildlife account expenditures authorized under subsection (1) of this section are unspent as of June 30th of a fiscal year, the state treasurer shall transfer the unspent amount to the wolf-livestock conflict account created in RCW 77.36.180.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5058.SL.pdf?cite=2021%20c%2014%20§%201[2021 c 14 § 1]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6072-S.SL.pdf?cite=2020%20c%20148%20§%2024[2020 c 148 § 24]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6002-S.SL.pdf?cite=2014%20c%20221%20§%20922[2014 c 221 § 922]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5193-S2.SL.pdf?cite=2013%20c%20329%20§%202[2013 c 329 § 2]; ]

== 77.36.180 - Wolf-livestock conflict account.
. The wolf-livestock conflict account is created in the custody of the state treasurer. Any transfers under RCW 77.36.170 must be deposited in the account. The department may also deposit into the account any grants, gifts, or donations to the state for the purposes of providing compensation for injury or loss of livestock caused by wolves. Consistent with this chapter, expenditures from the account may be used only for mitigation, assessment, and payments for injury or loss of livestock caused by wolves. Only the director or the director's designee may authorize expenditures from the account. The account is subject to allotment procedures under chapter 43.88 RCW, but an appropriation is not required for expenditures.

. [Empty]
.. The department must maintain a list of claims submitted under RCW 77.36.100, organized chronologically by the date wolf predation is confirmed, for injury or loss of livestock caused by wolves that have been approved for payment but not yet been fully paid by the department. As funding becomes available to the department under this section, RCW 77.36.170, or any other source, the department must pay claims in the chronologic order they appear on the list. The department must maintain, and is authorized to pay, claims that appear on the list due to injury or loss that occurred in a previous fiscal biennium.

.. The payment of a claim included on the list maintained by the department under this section is conditional on the availability of specific funding for this purpose and is not a guarantee of reimbursement.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5193-S2.SL.pdf?cite=2013%20c%20329%20§%203[2013 c 329 § 3]; ]

== 77.36.200 - Wolf-livestock conflict—Staff resources in Ferry and Stevens counties.
The department shall maintain sufficient staff resources in Ferry and Stevens counties for response to wolf-livestock conflict on an ongoing basis and for coordination with livestock producers on the continued implementation of proactive nonlethal deterrents.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2097-S.SL.pdf?cite=2019%20c%20450%20§%203[2019 c 450 § 3]; ]

