= 77.100 - Volunteer fish and wildlife enhancement program.
:toc:

== 77.100.010 - Legislative findings—Department to administer cooperative enhancement program.
The fish and wildlife resources of the state benefit by the contribution of volunteer recreational and commercial fishing organizations, schools, and other volunteer groups in cooperative projects under agreement with the department. These projects provide educational opportunities, improve the communication between the natural resources agencies and the public, and increase the fish and game resources of the state. In an effort to increase these benefits and realize the full potential of cooperative projects, the department shall administer a cooperative fish and wildlife enhancement program and enter agreements with volunteer groups relating to the operation of cooperative projects.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2055-S.SL.pdf?cite=1993%20sp.s.%20c%202%20§%2049[1993 sp.s. c 2 § 49]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c36.pdf?cite=1988%20c%2036%20§%2041[1988 c 36 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c72.pdf?cite=1984%20c%2072%20§%201[1984 c 72 § 1]; ]

== 77.100.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Volunteer group" means any person or group of persons interested in or party to an agreement with the department relating to a cooperative fish or wildlife project.

. "Cooperative project" means a project conducted by a volunteer group that will benefit the fish, shellfish, game bird, nongame wildlife, or game animal resources of the state and for which the benefits of the project, including fish and wildlife reared and released, are available to all citizens of the state. Indian tribes may elect to participate in cooperative fish and wildlife projects with the department.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%20111[2000 c 107 § 111]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2055-S.SL.pdf?cite=1993%20sp.s.%20c%202%20§%2050[1993 sp.s. c 2 § 50]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c36.pdf?cite=1988%20c%2036%20§%2042[1988 c 36 § 42]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c72.pdf?cite=1984%20c%2072%20§%202[1984 c 72 § 2]; ]

== 77.100.030 - Cooperative projects—Types.
The department shall encourage and support the development and operation of cooperative projects of the following types:

. Cooperative food fish and game fish rearing projects, including but not limited to egg planting, egg boxes, juvenile planting, pen rearing, pond rearing, raceway rearing, and egg taking;

. Cooperative fish habitat improvement projects, including but not limited to fish migration improvement, spawning bed rehabilitation, habitat restoration, reef construction, lake fertilization, pond construction, pollution abatement, and endangered stock protection;

. Cooperative fish or game research projects if the project is clearly of a research nature and if the results are readily available to the public;

. Cooperative game bird and game animal projects, including but not limited to habitat improvement and restoration, replanting and transplanting, nest box installation, pen rearing, game protection, and supplemental feeding;

. Cooperative nongame wildlife projects, including but not limited to habitat improvement and restoration, nest box installation, establishment of wildlife interpretive areas or facilities, pollution abatement, supplemental feeding, and endangered species preservation and enhancement; and

. Cooperative information and education projects, including but not limited to landowner relations, outdoor ethics, natural history of Washington's fish, shellfish, and wildlife, and outdoor survival.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c72.pdf?cite=1984%20c%2072%20§%203[1984 c 72 § 3]; ]

== 77.100.040 - Cooperative projects—Sale of surplus salmon eggs and carcasses.
The department may authorize the sale of surplus salmon eggs and carcasses by permitted cooperative projects for the purposes of defraying the expenses of the cooperative project. In no instance shall the department allow a profit to be realized through such sales. The department shall adopt rules to implement this section pursuant to chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2055-S.SL.pdf?cite=1993%20sp.s.%20c%202%20§%2051[1993 sp.s. c 2 § 51]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c48.pdf?cite=1987%20c%2048%20§%201[1987 c 48 § 1]; ]

== 77.100.050 - Duties of department.
. The department shall:

.. Encourage and support the establishment of cooperative agreements for the development and operation of cooperative food fish, shellfish, game fish, game bird, game animal, and nongame wildlife projects, and projects which provide an opportunity for volunteer groups to become involved in resource and habitat-oriented activities. All cooperative projects shall be fairly considered in the approval of cooperative agreements;

.. Identify regions and species or activities that would be particularly suitable for cooperative projects providing benefits compatible with department goals;

.. Determine the availability of rearing space at operating facilities or of net pens, egg boxes, portable rearing containers, incubators, and any other rearing facilities for use in cooperative projects, and allocate them to volunteer groups as fairly as possible;

.. Make viable eggs available for replenishing fish runs, and salmon carcasses for nutrient enhancement of streams. If a regional fisheries enhancement group, lead entity, volunteer cooperative group, federally approved tribe in Washington, or a governmental hatchery in Washington, Oregon, or Idaho requests the department for viable eggs, the department must include the request within the brood stock document prepared for review by the regional offices. The eggs shall be distributed in accordance with the priority established in RCW 77.95.210 if they are available. A request for viable eggs may only be denied if the eggs would not be useful for propagation or salmon recovery purposes, as determined under RCW 77.95.210;

.. Exempt volunteer groups from payment of fees to the department for activities related to the project;

.. Publicize the cooperative program;

.. Not substitute a new cooperative project for any part of the department's program unless mutually agreeable to the department and volunteer group;

.. Not approve agreements that are incompatible with legally existing land, water, or property rights.

. The department may, when requested, provide to volunteer groups its available professional expertise and assist the volunteer group to evaluate its project. The department must conduct annual workshops in each administrative region of the department that has fish stocks listed as threatened or endangered under the federal endangered species act, 16 U.S.C. Sec. 1531 et seq., in order to assist volunteer groups with egg rearing, share information on successful salmon recovery projects accomplished by volunteers within the state, and provide basic training on monitoring efforts that can be accomplished by volunteers in order to help determine if their efforts are successful.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1286-S.SL.pdf?cite=2001%20c%20337%20§%203[2001 c 337 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c505.pdf?cite=1987%20c%20505%20§%2073[1987 c 505 § 73]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c72.pdf?cite=1984%20c%2072%20§%204[1984 c 72 § 4]; ]

== 77.100.060 - Commission to establish rules—Subjects.
The commission shall establish by rule:

. The procedure for entering a cooperative agreement and the application forms for a permit to release fish or wildlife required by *RCW 77.12.457. The procedure shall indicate the information required from the volunteer group as well as the process of review by the department. The process of review shall include the means to coordinate with other agencies and Indian tribes when appropriate and to coordinate the review of any necessary hydraulic permit approval applications.

. The procedure for providing within forty-five days of receipt of a proposal a written response to the volunteer group indicating the date by which an acceptance or rejection of the proposal can be expected, the reason why the date was selected, and a written summary of the process of review. The response should also include any suggested modifications to the proposal which would increase its likelihood of approval and the date by which such modified proposal could be expected to be accepted. If the proposal is rejected, the department must provide in writing the reasons for rejection. The volunteer group may request the director or the director's designee to review information provided in the response.

. The priority of the uses to which eggs, seed, juveniles, or brood stock are put. Use by cooperative projects shall be second in priority only to the needs of programs of the department or of other public agencies within the territorial boundaries of the state. Sales of eggs, seed, juveniles, or brood stock have a lower priority than use for cooperative projects. The rules must identify and implement appropriate protocols for brood stock handling, including the outplanting of adult fish, spawning, incubation, rearing, and release and establish a prioritized schedule for implementation of chapter 337, Laws of 2001, and shall include directives for allowing more hatchery salmon to spawn naturally in areas where progeny of hatchery fish have spawned, including the outplanting of adult fish, in order to increase the number of viable salmon eggs and restore healthy numbers of fish within the state.

. The procedure for the director to notify a volunteer group that the agreement for the project is being revoked for cause and the procedure for revocation. Revocation shall be documented in writing to the volunteer group. Cause for revocation may include: (a) The unavailability of adequate biological or financial resources; (b) the development of unacceptable biological or resource management conflicts; or (c) a violation of agreement provisions. Notice of cause to revoke for a violation of agreement provisions may specify a reasonable period of time within which the volunteer group must comply with any violated provisions of the agreement.

. An appropriate method of distributing among volunteer groups fish, bird, or animal food or other supplies available for the program.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1286-S.SL.pdf?cite=2001%20c%20337%20§%204[2001 c 337 § 4]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%20112[2000 c 107 § 112]; 1995 1st sp.s. c 2 § 42 (Referendum Bill No. 45, approved November 7, 1995); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c72.pdf?cite=1984%20c%2072%20§%205[1984 c 72 § 5]; ]

== 77.100.070 - Agreements for cooperative projects—Duration.
Agreements under this chapter may be for up to five years, with the department attempting to maximize the duration of each cooperative agreement. The duration of the agreement should reflect the financial and volunteer commitment and the stability of the volunteer group as well as the department's expectation of resource availability and project contributions to the resource.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c72.pdf?cite=1984%20c%2072%20§%206[1984 c 72 § 6]; ]

== 77.100.080 - Duties of volunteer group.
. The volunteer group shall:

.. Provide care and diligence in conducting the cooperative project; and

.. Maintain accurately the required records of the project on forms provided by the department.

. The volunteer group shall acknowledge that fish and game reared in cooperative projects are public property and must be handled and released for the benefit of all citizens of the state. The fish and game are to remain public property until reduced to private ownership under rules of the commission.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%20113[2000 c 107 § 113]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c72.pdf?cite=1984%20c%2072%20§%207[1984 c 72 § 7]; ]

== 77.100.090 - Application of chapter.
This chapter applies to cooperative projects which were in existence on June 7, 1984, or which require no further funding. Implementation of this chapter for new projects requiring funding shall be to the extent that funds are available from the aquatic land enhancement account.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c72.pdf?cite=1984%20c%2072%20§%208[1984 c 72 § 8]; ]

== 77.100.100 - Cedar river spawning channel.
A salmon spawning channel shall be constructed on the Cedar river with the assistance and cooperation of the department. The department shall use existing personnel and the volunteer fisheries enhancement program outlined under chapter 77.100 RCW to assist in the planning, construction, and operation of the spawning channel.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%20114[2000 c 107 § 114]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2055-S.SL.pdf?cite=1993%20sp.s.%20c%202%20§%2052[1993 sp.s. c 2 § 52]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c85.pdf?cite=1989%20c%2085%20§%203[1989 c 85 § 3]; ]

== 77.100.110 - Cedar river spawning channel—Technical committee—Policy committee.
The department shall chair a technical committee, which shall review the preparation of enhancement plans and construction designs for a Cedar river sockeye spawning channel. The technical committee shall consist of not more than eight members: One representative each from the department, national marine fisheries service, United States fish and wildlife service, and Muckleshoot Indian tribe; and four representatives from the public utility described in RCW 77.100.130. The technical committee will be guided by a policy committee, also to be chaired by the department, which shall consist of not more than six members: One representative from the department, one from the Muckleshoot Indian tribe, and one from either the national marine fisheries service or the United States fish and wildlife service; and three representatives from the public utility described in RCW 77.100.130. The policy committee shall oversee the operation and evaluation of the spawning channel. The policy committee will continue its oversight until the policy committee concludes that the channel is meeting the production goals specified in RCW 77.100.120.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%20115[2000 c 107 § 115]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%20156[1998 c 245 § 156]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2055-S.SL.pdf?cite=1993%20sp.s.%20c%202%20§%2053[1993 sp.s. c 2 § 53]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c85.pdf?cite=1989%20c%2085%20§%204[1989 c 85 § 4]; ]

== 77.100.120 - Cedar river spawning channel—Specifications.
The channel shall be designed to produce, at a minimum, fry comparable in quality to those produced in the Cedar river and equal in number to what could be produced naturally by the estimated two hundred sixty-two thousand adults that could have spawned upstream of the Landsburg diversion. Construction of the spawning channel shall commence no later than September 1, 1990. Initial construction size shall be adequate to produce fifty percent or more of the production goal specified in this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c85.pdf?cite=1989%20c%2085%20§%205[1989 c 85 § 5]; ]

== 77.100.130 - Cedar river spawning channel—Funding.
The legislature recognizes that, if funding for planning, design, evaluation, construction, and operating expenses is provided by a public utility that diverts water for beneficial public use, and if the performance of the spawning channel meets the production goals described in RCW 77.100.120, the spawning channel project will serve, at a minimum, as compensation for lost sockeye salmon spawning habitat upstream of the Landsburg diversion. The amount of funding to be supplied by the utility will fully fund the total cost of planning, design, evaluation, and construction of the spawning channel.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%20116[2000 c 107 § 116]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c85.pdf?cite=1989%20c%2085%20§%206[1989 c 85 § 6]; ]

== 77.100.150 - Cedar river spawning channel—Legislative declaration.
The legislature hereby declares that the construction of the Cedar river sockeye spawning channel is in the best interests of the state of Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c85.pdf?cite=1989%20c%2085%20§%209[1989 c 85 § 9]; ]

== 77.100.160 - Cedar river spawning channel—Mitigation of water diversion projects.
Should the requirements of RCW 77.100.100 through 77.100.160 not be met, the department shall seek immediate legal clarification of the steps which must be taken to fully mitigate water diversion projects on the Cedar river.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%20118[2000 c 107 § 118]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2055-S.SL.pdf?cite=1993%20sp.s.%20c%202%20§%2054[1993 sp.s. c 2 § 54]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c85.pdf?cite=1989%20c%2085%20§%2010[1989 c 85 § 10]; ]

== 77.100.170 - Fish hatcheries—Volunteer group projects.
The manager of a state fish hatchery operated by the department of fish and wildlife may allow nonprofit volunteer groups affiliated with the hatchery to undertake projects to raise donations, gifts, and grants that enhance support for the hatchery or activities in the surrounding watershed that benefit the hatchery. The manager may provide agency personnel and services, if available, to assist in the projects and may allow the volunteer groups to conduct activities on the grounds of the hatchery.

The director of the department of fish and wildlife shall encourage and facilitate arrangements between hatchery managers and nonprofit volunteer groups and may establish guidelines for such arrangements.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5718.SL.pdf?cite=1995%20c%20224%20§%201[1995 c 224 § 1]; ]

