= 77.115 - Aquaculture disease control.
:toc:

== 77.115.010 - Disease inspection and control for aquatic farmers—Development of program—Elements—Rules—Violations.
. The director of agriculture and the director shall jointly develop a program of disease inspection and control for aquatic farmers as defined in RCW 15.85.020. The program shall be administered by the department under rules established under this section. The purpose of the program is to protect the aquaculture industry and wildstock fisheries from a loss of productivity due to aquatic diseases or maladies. As used in this section "diseases" means, in addition to its ordinary meaning, infestations of parasites or pests. The disease program may include, but is not limited to, the following elements:

.. Disease diagnosis;

.. Import and transfer requirements;

.. Provision for certification of stocks;

.. Classification of diseases by severity;

.. Provision for treatment of selected high-risk diseases;

.. Provision for containment and eradication of high-risk diseases;

.. Provision for destruction of diseased cultured aquatic products;

.. Provision for quarantine of diseased cultured aquatic products;

.. Provision for coordination with state and federal agencies;

.. Provision for development of preventative or control measures;

.. Provision for cooperative consultation service to aquatic farmers; and

.. Provision for disease history records.

. The commission shall adopt rules implementing this section. However, such rules shall have the prior approval of the director of agriculture and shall provide therein that the director of agriculture has provided such approval. The director of agriculture or the director's designee shall attend the rule-making hearings conducted under chapter 34.05 RCW and shall assist in conducting those hearings. The authorities granted the department by these rules and by RCW 77.12.047(1)(g), 77.60.060, 77.60.080, 77.65.210, 77.115.030, and 77.115.040 constitute the only authorities of the department to regulate private sector cultured aquatic products and aquatic farmers as defined in RCW 15.85.020. Except as provided in subsection (3) of this section, no action may be taken against any person to enforce these rules unless the department has first provided the person an opportunity for a hearing. In such a case, if the hearing is requested, no enforcement action may be taken before the conclusion of that hearing.

. The rules adopted under this section shall specify the emergency enforcement actions that may be taken by the department, and the circumstances under which they may be taken, without first providing the affected party with an opportunity for a hearing. Neither the provisions of this subsection nor the provisions of subsection (2) of this section shall preclude the department from requesting the initiation of criminal proceedings for violations of the disease inspection and control rules.

. A person shall not violate the rules adopted under subsection (2) or (3) of this section or violate RCW 77.115.040.

. In administering the program established under this section, the department shall use the services of a pathologist licensed to practice veterinary medicine.

. The director in administering the program shall not place constraints on or take enforcement actions in respect to the aquaculture industry that are more rigorous than those placed on the department or other fish-rearing entities.

. The department must implement this section consistent with RCW 77.125.050.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2957.SL.pdf?cite=2018%20c%20179%20§%206[2018 c 179 § 6]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%20122[2000 c 107 § 122]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=1998%20c%20190%20§%20110[1998 c 190 § 110]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2055-S.SL.pdf?cite=1993%20sp.s.%20c%202%20§%2055[1993 sp.s. c 2 § 55]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c36.pdf?cite=1988%20c%2036%20§%2043[1988 c 36 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c457.pdf?cite=1985%20c%20457%20§%208[1985 c 457 § 8]; ]

== 77.115.030 - Consultation required—Agreements for diagnostic field services authorized—Roster of biologists.
. The director shall consult regarding the disease inspection and control program established under RCW 77.115.010 with federal agencies and Indian tribes to assure protection of state, federal, and tribal aquatic resources and to protect private sector cultured aquatic products from disease that could originate from waters or facilities managed by those agencies.

. With regard to the program, the director may enter into contracts or interagency agreements for diagnostic field services with government agencies and institutions of higher education and private industry.

. The director shall provide for the creation and distribution of a roster of biologists having a specialty in the diagnosis or treatment of diseases of fish or shellfish. The director shall adopt rules specifying the qualifications which a person must have in order to be placed on the roster.

. The department must implement this section consistent with RCW 77.125.050.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2957.SL.pdf?cite=2018%20c%20179%20§%207[2018 c 179 § 7]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%20124[2000 c 107 § 124]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2055-S.SL.pdf?cite=1993%20sp.s.%20c%202%20§%2057[1993 sp.s. c 2 § 57]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c36.pdf?cite=1988%20c%2036%20§%2044[1988 c 36 § 44]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c457.pdf?cite=1985%20c%20457%20§%2010[1985 c 457 § 10]; ]

== 77.115.040 - Registration of aquatic farmers—Fee.
. All aquatic farmers, as defined in RCW 15.85.020, shall register with the department. The application fee is one hundred five dollars. The director shall assign each aquatic farm a unique registration number and develop and maintain in an electronic database a registration list of all aquaculture farms. The department shall establish procedures to annually update the aquatic farmer information contained in the registration list. The department shall coordinate with the department of health using shellfish growing area certification data when updating the registration list.

. Registered aquaculture farms shall provide the department with the following information:

.. The name of the aquatic farmer;

.. The address of the aquatic farmer;

.. Contact information such as telephone, fax, web site, and email address, if available;

.. The number and location of acres under cultivation, including a map displaying the location of the cultivated acres;

.. The name of the landowner of the property being cultivated or otherwise used in the aquatic farming operation;

.. The private sector cultured aquatic product being propagated, farmed, or cultivated; and

.. Statistical production data.

. The state veterinarian shall be provided with registration and statistical data by the department.

. The department must implement this section consistent with RCW 77.125.050.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2957.SL.pdf?cite=2018%20c%20179%20§%208[2018 c 179 § 8]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5385-S.SL.pdf?cite=2011%20c%20339%20§%2037[2011 c 339 § 37]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2220-S2.SL.pdf?cite=2007%20c%20216%20§%206[2007 c 216 § 6]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2055-S.SL.pdf?cite=1993%20sp.s.%20c%202%20§%2058[1993 sp.s. c 2 § 58]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c36.pdf?cite=1988%20c%2036%20§%2045[1988 c 36 § 45]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c457.pdf?cite=1985%20c%20457%20§%2011[1985 c 457 § 11]; ]

