= 77.120 - Ballast water management.
:toc:

== 77.120.005 - Findings.
The legislature finds that some nonindigenous species have the potential to cause economic and environmental damage to the state and that current efforts to stop the introduction of nonindigenous species from shipping vessels do not adequately reduce the risk of new introductions into Washington waters.

The legislature recognizes the international ramifications and the rapidly changing dimensions of this issue, the lack of currently available treatment technologies, and the difficulty that any one state has in either legally or practically managing this issue. Recognizing the possible limits of state jurisdiction over international issues, the state declares its support for the international maritime organization and United States coast guard efforts, and the state intends to complement, to the extent its powers allow it, the United States coast guard's ballast water management program.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6329-S.SL.pdf?cite=2004%20c%20227%20§%201[2004 c 227 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2466-S.SL.pdf?cite=2000%20c%20108%20§%201[2000 c 108 § 1]; ]

== 77.120.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Ballast tank" means any tank or hold on a vessel used for carrying ballast water, whether or not the tank or hold was designed for that purpose.

. "Ballast water" means any water and matter taken on board a vessel to control or maintain trim, draft, stability, or stresses of the vessel, without regard to the manner in which it is carried.

. "Biofouling" means the accumulation of aquatic organisms on a vessel such as attached or associated mobile microorganisms, plants, and animals on surfaces and structures immersed in or exposed to the aquatic environment.

. "Empty/refill exchange" means to pump out, until the tank is empty or as close to empty as the master or operator determines is safe, the ballast water taken on in ports, estuarine, or territorial waters, and then refilling the tank with open sea waters.

. "Exchange" means to replace the water in a ballast tank using either flow through exchange, empty/refill exchange, or other exchange methodology recommended or required by the United States coast guard.

. "Flow through exchange" means to flush out ballast water by pumping in midocean water at the bottom of the tank and continuously overflowing the tank from the top until three full volumes of water have been changed to minimize the number of original organisms remaining in the tank.

. "Nonindigenous species" means any species or other viable biological material that enters an ecosystem beyond its natural range.

. "Open sea exchange" means an exchange that occurs fifty or more nautical miles offshore. If the United States coast guard requires a vessel to conduct an exchange further offshore, then that distance is the required distance for purposes of compliance with this chapter.

. "Recognized marine trade association" means those trade associations in Washington state that promote improved ballast water management practices by educating their members on the provisions of this chapter, participating in regional ballast water coordination through the Pacific ballast water group, assisting the department in the collection of ballast water exchange forms, and the monitoring of ballast water. This includes members of the Puget Sound marine committee for Puget Sound and the Columbia river steamship operators association for the Columbia river.

. "Sediments" means any matter settled out of ballast water within a vessel.

. "Untreated ballast water" includes exchanged or unexchanged ballast water that has not undergone treatment.

. "Vessel" means a ship, boat, barge, or other floating craft of three hundred gross tons or more, United States and foreign, carrying, or capable of carrying, ballast water into the coastal waters of the state after operating outside of the coastal waters of the state, except those vessels described in RCW 77.120.020.

. "Voyage" means any transit by a vessel destined for any Washington port.

. "Waters of the state" means any surface waters, including internal waters contiguous to state shorelines within the boundaries of the state.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5303-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%2017%20§%20307[2017 3rd sp.s. c 17 § 307]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5923-S2.SL.pdf?cite=2007%20c%20350%20§%208[2007 c 350 § 8]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2466-S.SL.pdf?cite=2000%20c%20108%20§%202[2000 c 108 § 2]; ]

== 77.120.020 - Application of chapter.
. This chapter applies to all vessels transiting into the waters of the state from a voyage, except:

.. A vessel of the United States department of defense or United States coast guard subject to the requirements of section 1103 of the national invasive species act of 1996, or any vessel of the armed forces, as defined in 33 U.S.C. Sec. 1322(a)(14), that is subject to the uniform national discharge standards for vessels of the armed forces under 33 U.S.C. Sec. 1322(n);

.. A vessel that discharges ballast water or sediments only at the location where the ballast water or sediments originated, if the ballast water or sediments do not mix with ballast water or sediments from areas other than open sea waters; and

.. A vessel in innocent passage, merely traversing the territorial sea of the United States and not entering or departing a United States port, or not navigating the internal waters of the United States, and that does not discharge ballast water into the waters of the state.

. This chapter does not authorize the discharge of oil or noxious liquid substances in a manner prohibited by state, federal, or international laws or regulations. Ballast water containing oil, noxious liquid substances, or any other pollutant shall be discharged in accordance with the applicable requirements.

. The master or operator in charge of a vessel is responsible for the safety of the vessel, its crew, and its passengers. Nothing in this chapter relieves the master or operator in charge of a vessel of the responsibility for ensuring the safety and stability of the vessel or the safety of the crew and passengers.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5923-S2.SL.pdf?cite=2007%20c%20350%20§%209[2007 c 350 § 9]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2466-S.SL.pdf?cite=2000%20c%20108%20§%203[2000 c 108 § 3]; ]

== 77.120.030 - Authorized ballast water discharge—Adoption of standards by rule.
. The owner or operator in charge of any vessel covered by this chapter is required to ensure that the vessel under their ownership or control does not discharge ballast water into the waters of the state except as authorized by this section.

. Discharge of ballast water into waters of the state is authorized only if there has been an open sea exchange, or if the vessel has treated its ballast water, to meet standards set by the department consistent with applicable state and federal laws.

. The department, in consultation with a collaborative forum, shall adopt by rule standards for the discharge of ballast water into the waters of the state and their implementation timelines. The standards are intended to ensure that the discharge of ballast water poses minimal risk of introducing nonindigenous species. In developing these standards, the department shall consider the extent to which the requirement is technologically and practically feasible. Where practical and appropriate, the standards must be compatible with standards set by the United States coast guard, the federal clean water act (33 U.S.C. Sec. 1251-1387), or the international maritime organization.

. The master, operator, or person in charge of a vessel is not required to conduct an open sea exchange or treatment of ballast water if the master, operator, or person in charge of a vessel determines that the operation would threaten the safety of the vessel, its crew, or its passengers, because of adverse weather, vessel design limitations, equipment failure, or any other extraordinary conditions. A master, operator, or person in charge of a vessel who relies on this exemption must file documentation defined by the department, subject to: (a) Payment of a fee not to exceed five thousand dollars; (b) discharging only the minimal amount of ballast water operationally necessary; (c) ensuring that ballast water records accurately reflect any reasons for not complying with the mandatory requirements; and (d) any other requirements identified by the department by rule as provided in subsections (3) and (6) of this section.

. For treatment technologies requiring shipyard modification, the department may enter into a compliance plan with the vessel owner. The compliance plan must include a timeline consistent with drydock and shipyard schedules for completion of the modification. The department shall adopt rules for compliance plans under this subsection.

. For an exemption claimed in subsection (4) of this section, the department shall adopt rules for defining exemption conditions, requirements, compliance plans, or alternative ballast water management strategies to meet the intent of this section.

. The department shall make every effort to align ballast water standards with adopted international and federal standards while ensuring that the goals of this chapter are met.

. The requirements of this section do not apply to a vessel discharging ballast water or sediments that originated solely within the waters of Washington, the Columbia river system, or the internal waters of British Columbia south of latitude fifty degrees north, including the waters of the Straits of Georgia and Juan de Fuca.

. Open sea exchange is an exchange that occurs fifty or more nautical miles offshore. If the United States coast guard requires a vessel to conduct an exchange further offshore, then that distance is the required distance for purposes of compliance with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1778-S.SL.pdf?cite=2009%20c%20333%20§%2026[2009 c 333 § 26]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5923-S2.SL.pdf?cite=2007%20c%20350%20§%2010[2007 c 350 § 10]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6329-S.SL.pdf?cite=2004%20c%20227%20§%203[2004 c 227 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6538.SL.pdf?cite=2002%20c%20282%20§%202[2002 c 282 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2466-S.SL.pdf?cite=2000%20c%20108%20§%204[2000 c 108 § 4]; ]

== 77.120.040 - Reporting and sampling requirements.
The owner or operator in charge of any vessel covered by this chapter is required to ensure that the vessel under their ownership or control complies with the reporting and sampling requirements of this section.

. Vessels covered by this chapter must report ballast water management information to the department using ballast water management forms that are acceptable to the United States coast guard. The frequency, manner, and form of such reporting shall be established by the department by rule. Any vessel may rely on a recognized marine trade association to collect and forward this information to the department.

. In order to monitor the effectiveness of national and international efforts to prevent the introduction of nonindigenous species, all vessels covered by this chapter must submit nonindigenous species ballast water monitoring data. The monitoring, sampling, testing protocols, and methods of identifying nonindigenous species in ballast water shall be determined by the department by rule. A vessel covered by this chapter may contract with a recognized marine trade association to randomly sample vessels within that association's membership, and provide data to the department.

. Vessels that do not belong to a recognized marine trade association must submit individual ballast tank sample data to the department for each voyage.

. All data submitted to the department under subsection (2) of this section shall be consistent with sampling and testing protocols as adopted by the department by rule.

. The department shall adopt rules to implement this section. The rules and recommendations shall be developed in consultation with advisors from regulated industries and the potentially affected parties, including but not limited to shipping interests, ports, shellfish growers, fisheries, environmental interests, interested citizens who have knowledge of the issues, and appropriate governmental representatives including the United States coast guard. In recognition of the need to have a coordinated response to ballast water management for the Columbia river system, the department must consider rules adopted by the state of Oregon when adopting rules under this section for ballast water management in the navigable waters of the Columbia river system.

.. The department shall set standards for the discharge of treated ballast water into the waters of the state. The rules are intended to ensure that the discharge of treated ballast water poses minimal risk of introducing nonindigenous species. In developing this standard, the department shall consider the extent to which the requirement is technologically and practically feasible. Where practical and appropriate, the standards shall be compatible with standards set by the United States coast guard and shall be developed in consultation with federal and state agencies to ensure consistency with the federal clean water act, 33 U.S.C. Sec. 1251-1387.

.. The department shall adopt ballast water sampling and testing protocols for monitoring the biological components of ballast water that may be discharged into the waters of the state under this chapter. Monitoring data is intended to assist the department in evaluating the risk of new, nonindigenous species introductions from the discharge of ballast water, and to evaluate the accuracy of ballast water exchange practices. The sampling and testing protocols must consist of cost-effective, scientifically verifiable methods that, to the extent practical and without compromising the purposes of this chapter, utilize easily measured indices, such as salinity, or check for species that indicate the potential presence of nonindigenous species or pathogenic species. The department shall specify appropriate quality assurance and quality control for the sampling and testing protocols.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6538.SL.pdf?cite=2002%20c%20282%20§%203[2002 c 282 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2466-S.SL.pdf?cite=2000%20c%20108%20§%205[2000 c 108 § 5]; ]

== 77.120.050 - Pilot project—Private sector ballast water treatment operation.
The shipping vessel industry, the public ports, and the department shall promote the creation of a pilot project to establish a private sector ballast water treatment operation that is capable of servicing vessels at all Washington ports. Federal and state agencies and private industries shall be invited to participate. The project will develop equipment or methods to treat ballast water and establish operational methods that do not increase the cost of ballast water treatment at smaller ports. The legislature intends that the cost of treatment required by this chapter is substantially equivalent among large and small ports in Washington.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2466-S.SL.pdf?cite=2000%20c%20108%20§%206[2000 c 108 § 6]; ]

== 77.120.070 - Violation of chapter—Penalties—Rules.
. The department may establish by rule schedules for any penalty allowed in this chapter. The schedules may provide for the incremental assessment of a penalty based on criteria established by rule.

. The director or the director's designee may impose a civil penalty or warning for a violation of the requirements of this chapter on the owner or operator in charge of a vessel who fails to comply with the requirements imposed under this chapter. The penalty shall not exceed twenty-seven thousand five hundred dollars for each day of a continuing violation. In determining the amount of a civil penalty, the department shall set standards by rule that consider if the violation was intentional, negligent, or without any fault, and shall consider the quality and nature of risks created by the violation. The owner or operator subject to such a penalty may contest the determination by requesting an adjudicative proceeding within twenty days. Any determination not timely contested is final and may be reduced to a judgment enforceable in any court with jurisdiction. If the department prevails using any judicial process to collect a penalty under this section, the department shall also be awarded its costs and reasonable attorneys' fees.

. The department, in cooperation with the United States coast guard, may enforce the requirements of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5303-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%2017%20§%20304[2017 3rd sp.s. c 17 § 304]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5923-S2.SL.pdf?cite=2007%20c%20350%20§%2012[2007 c 350 § 12]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2466-S.SL.pdf?cite=2000%20c%20108%20§%208[2000 c 108 § 8]; ]

== 77.120.100 - Department may assess fee for exemptions—Rules.
The department may assess a fee for any exemptions allowed under this chapter. Such a fee may not exceed five thousand dollars. The department may establish by rule schedules for any fee allowed in this chapter. The schedules may provide for the incremental assessment of a penalty based on criteria established by rule.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5923-S2.SL.pdf?cite=2007%20c%20350%20§%2013[2007 c 350 § 13]; ]

== 77.120.110 - Ballast water and biofouling management account.
. The ballast water and biofouling management account is created in the state treasury. All receipts from legislative appropriations, gifts, grants, donations, penalties, and fees received under this chapter must be deposited into the account.

. Expenditures from the account may be used only to carry out the purposes of this chapter. However, penalties may not be used for the salaries of permanent department employees.

. Moneys in the account may be spent only after appropriation.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5303-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%2017%20§%20106[2017 3rd sp.s. c 17 § 106]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1778-S.SL.pdf?cite=2009%20c%20333%20§%2027[2009 c 333 § 27]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5923-S2.SL.pdf?cite=2007%20c%20350%20§%2014[2007 c 350 § 14]; ]

== 77.120.120 - Special operating authorization—Rules.
The department may issue a special operating authorization for passenger vessels conducting or assisting in research and testing activities to determine the presence of invasive species in ballast water collected in the waters of southeast Alaska north of latitude fifty-four degrees thirty minutes north to sixty-one degrees ten minutes north, extending to longitude one hundred forty-nine degrees thirty minutes west.  The department may adopt rules for defining special operating authorization conditions, requirements, limitations, and fees as necessary to implement this section, consistent with the intent of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1778-S.SL.pdf?cite=2009%20c%20333%20§%2028[2009 c 333 § 28]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5923-S2.SL.pdf?cite=2007%20c%20350%20§%2015[2007 c 350 § 15]; ]

== 77.120.130 - Department's authority to enter into partnerships, contracts, or other agreements.
The department may enter into partnerships, contracts, or any other form of agreements with other entities to carry out the intent of this chapter. The department shall ensure that any such entity is registered and licensed to do business in Washington. All agreements must be consistent with existing state laws, agency rules, state water quality standards, and collective bargaining agreements.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5303-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%2017%20§%20204[2017 3rd sp.s. c 17 § 204]; ]

== 77.120.140 - Biofouling—Agency rule-making authority.
. The owner or operator of a vessel covered by this chapter is required to ensure that the vessel under their ownership or control does not release biofouling into waters of the state except as authorized by this section.

. The department may adopt by rule standards and requirements governing the release of biofouling on vessels arriving or moored at a Washington port.

. The department shall adopt rules under subsection (2) of this section for adoption in consultation with a collaborative forum with advisors from regulated industries and the potentially affected parties including shipping interests, ports, shellfish growers, fisheries, environmental interests, interested citizens who have knowledge of the issues, and appropriate governmental representatives including the United States coast guard and the United States environmental protection agency. The rules must:

.. Ensure that biofouling management poses minimal risk of release of nonindigenous species;

.. Be based on the best available technology that is economically achievable; and

.. Where practical and appropriate, be compatible with standards and requirements set by the United States coast guard, the United States environmental protection agency, or the international maritime organization.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5303-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%2017%20§%20301[2017 3rd sp.s. c 17 § 301]; ]

