= 77.140 - Seafood labeling requirements.
:toc:

== 77.140.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Commercially caught" means wild or hatchery-raised salmon harvested in the wild by commercial fishers. The term does not apply to farmed fish raised exclusively by private sector aquaculture.

. "Fish" means fresh or saltwater finfish and other forms of aquatic animal life other than crustaceans, mollusks, birds, and mammals where the animal life is intended for human consumption.

. "Salmon" means all species of the genus Oncorhynchus, except those classified as game fish in RCW 77.08.020, and includes:

SCIENTIFIC NAMECOMMON NAMEOncorhynchus tshawytschaChinook salmon or king salmonOncorhynchus kisutchCoho salmon or silver salmonOncorhynchus ketaChum or "keta" salmonOncorhynchus gorbuschaPink salmonOncorhynchus nerkaSockeye or "red" salmonSalmo salar (in other thanAtlantic salmon its landlocked form) 

SCIENTIFIC NAME

COMMON NAME

Oncorhynchus tshawytscha

Chinook salmon or king salmon

Oncorhynchus kisutch

Coho salmon or silver salmon

Oncorhynchus keta

Chum or "keta" salmon

Oncorhynchus gorbuscha

Pink salmon

Oncorhynchus nerka

Sockeye or "red" salmon

Salmo salar (in other than

Atlantic salmon

 

its landlocked form)

 

. "Shellfish" means crustaceans and all mollusks where the animal life is intended for human consumption.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20607[2018 c 236 § 607]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1200-S.SL.pdf?cite=2013%20c%20290%20§%203[2013 c 290 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5260.SL.pdf?cite=1993%20c%20282%20§%202[1993 c 282 § 2]; ]

== 77.140.020 - Seafood labeling requirements—Pamphlet.
The department of may:

. Develop a pamphlet that generally describes the labeling requirements for seafood as set forth in this chapter; and

. Make the pamphlet available to holders of any license associated with buying and selling fish or shellfish under chapter 77.65 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20606[2018 c 236 § 606]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1200-S.SL.pdf?cite=2013%20c%20290%20§%202[2013 c 290 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2323-S.SL.pdf?cite=2002%20c%20301%20§%2011[2002 c 301 § 11]; ]

== 77.140.030 - Fish and shellfish labeling—Identification of species—Exceptions—Penalty.
. It is unlawful to knowingly sell or offer for sale at wholesale or retail any fresh, frozen, or processed fish or shellfish without identifying for the buyer at the point of sale the species of fish or shellfish by its common name, such that the buyer can make an informed purchasing decision for his or her protection, health, and safety.

. It is unlawful to knowingly label or offer for sale any fish designated as halibut, with or without additional descriptive words, unless the fish product is Hippoglossus hippoglossus or Hippoglossus stenolepsis.

. This section does not apply to salmon that is minced, pulverized, coated with batter, or breaded.

. This section does not apply to a commercial fisher properly licensed under chapter 77.65 or 77.70 RCW and engaged in sales of fish to a wholesale fish buyer.

. A violation of this section constitutes misbranding under RCW 77.140.060 and is punishable as a misdemeanor, gross misdemeanor, or felony depending on the fair market value of the fish or shellfish involved in the violation.

. [Empty]
.. The common names for salmon species are as listed in RCW 77.140.010.

.. The common names for all other fish and shellfish are the common names for fish and shellfish species as defined by rule of the department. If the common name for a species is not defined by rule of the department, then the common name is the acceptable market name or common name as provided in the United States food and drug administration's publication "Seafood list - FDA's guide to acceptable market names for seafood sold in interstate commerce," as the publication existed on July 28, 2013.

. For the purposes of this section, "processed" means fish or shellfish processed by heat for human consumption, such as fish or shellfish that is kippered, smoked, boiled, canned, cleaned, portioned, or prepared for sale or attempted sale for human consumption.

. Nothing in this section precludes using additional descriptive language or trade names to describe fish or shellfish as long as the labeling requirements in this section are met.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20608[2018 c 236 § 608]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%206[2017 3rd sp.s. c 8 § 6]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1200-S.SL.pdf?cite=2013%20c%20290%20§%204[2013 c 290 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5260.SL.pdf?cite=1993%20c%20282%20§%203[1993 c 282 § 3]; ]

== 77.140.040 - Salmon labeling—Identification as farm-raised or commercially caught—Exceptions—Penalty.
. It is unlawful to knowingly sell or offer for sale at wholesale or retail any fresh, frozen, or processed salmon without identifying private sector cultured aquatic salmon or salmon products as farm-raised salmon, or identifying commercially caught salmon or salmon products as commercially caught salmon.

. Identification of the products under subsection (1) of this section must be made to the buyer at the point of sale such that the buyer can make an informed purchasing decision for his or her protection, health, and safety.

. A violation of this section constitutes misbranding under RCW 77.140.060 and is punishable as a misdemeanor, gross misdemeanor, or felony depending on the fair market value of the fish or shellfish involved in the violation.

. This section does not apply to salmon that is minced, pulverized, coated with batter, or breaded.

. This section does not apply to a commercial fisher properly licensed under chapter 77.65 or 77.70 RCW and lawfully engaged in the sale of fish to a wholesale fish buyer.

. Nothing in this section precludes using additional descriptive language or trade names to describe fish or shellfish as long as the labeling requirements of this section are met.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20609[2018 c 236 § 609]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%207[2017 3rd sp.s. c 8 § 7]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1200-S.SL.pdf?cite=2013%20c%20290%20§%205[2013 c 290 § 5]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5172.SL.pdf?cite=2003%20c%2039%20§%2029[2003 c 39 § 29]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5260.SL.pdf?cite=1993%20c%20282%20§%204[1993 c 282 § 4]; ]

== 77.140.050 - Fish and shellfish—Rules for identification and labeling.
To promote honesty and fair dealing for consumers and to protect public health and safety, the director, may adopt rules as necessary to:

. Establish and implement a reasonable definition and identification standard for species of fish and shellfish that are sold for human consumption;

. Provide procedures for enforcing this chapter's fish and shellfish labeling requirements and misbranding prohibitions.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20610[2018 c 236 § 610]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1200-S.SL.pdf?cite=2013%20c%20290%20§%206[2013 c 290 § 6]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2590.SL.pdf?cite=1994%20c%20264%20§%2039[1994 c 264 § 39]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5260.SL.pdf?cite=1993%20c%20282%20§%205[1993 c 282 § 5]; ]

== 77.140.060 - Misbranding of fish or shellfish—Penalties.
. A person is guilty of unlawful misbranding of fish or shellfish in the third degree if the person commits an act that violates RCW 77.140.030 or 77.140.040, and the misbranding involves fish or shellfish with a fair market value up to five hundred dollars. Unlawful misbranding of fish or shellfish in the third degree is a misdemeanor.

. A person is guilty of unlawful misbranding of fish or shellfish in the second degree if the person commits an act that violates RCW 77.140.030 or 77.140.040, and the misbranding involves fish or shellfish with a fair market value of five hundred dollars or more, up to five thousand dollars. Unlawful misbranding of fish or shellfish in the second degree is a gross misdemeanor.

. A person is guilty of unlawful misbranding of fish or shellfish in the first degree if the person commits an act that violates RCW 77.140.030 or 77.140.040, and the misbranding involves fish or shellfish with a fair market value of five thousand dollars or more. Unlawful misbranding of fish or shellfish in the first degree is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20611[2018 c 236 § 611]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1200-S.SL.pdf?cite=2013%20c%20290%20§%207[2013 c 290 § 7]; ]

