= 77.105 - Recreational salmon and marine fish enhancement program.
:toc:

== 77.105.005 - Findings—Intent.
. The legislature finds the sheltered waters of Puget Sound (waters east of the Sekiu river) have historically provided the citizens of the state with the safest and most convenient access to productive marine recreational fishing.

. The legislature further recognizes the economic value in restoring and rebuilding the recreational fishing opportunities in Puget Sound for salmon and marine bottomfish, and that these opportunities have declined in the past two decades. Investments made in recreational fishing programs will repay the people of the state many times over in increased economic activity and in an improved quality of life.

. It is the intent of the legislature to improve recreational fishing opportunities in Puget Sound and Lake Washington from current levels and increase the economic benefits from the fishery, particularly recognizing the unique recreational experience provided by the winter salmon fishery. In addition, the legislature has determined that the number of angler trips expended in these waters is the measure of fishing opportunity.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1698.SL.pdf?cite=2011%20c%20266%20§%201[2011 c 266 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2055-S.SL.pdf?cite=1993%20sp.s.%20c%202%20§%2082[1993 sp.s. c 2 § 82]; ]

== 77.105.010 - Program created—Coordinator.
There is created within the department of fish and wildlife the Puget Sound recreational salmon and marine fish enhancement program. The department of fish and wildlife shall identify a coordinator for the program who shall act as spokesperson for the program and shall:

. Coordinate the activities of the Puget Sound recreational salmon and marine fish enhancement program, including the Lake Washington salmon fishery; and

. Work within and outside of the department to achieve the goals stated in this chapter, including coordinating with the Puget Sound recreational fisheries enhancement oversight committee established in RCW 77.105.160.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5062-S.SL.pdf?cite=2003%20c%20173%20§%201[2003 c 173 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%20157[1998 c 245 § 157]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2055-S.SL.pdf?cite=1993%20sp.s.%20c%202%20§%2083[1993 sp.s. c 2 § 83]; ]

== 77.105.020 - Department responsibilities—Report to the legislature.
. Consistent with available revenue, commission policies, tribal comanager agreements, and limitations of the endangered species act, the department, in consultation with the oversight committee created in RCW 77.105.160, shall adaptively manage the Puget Sound recreational salmon and marine fish enhancement program to maximize the benefits to the Puget Sound recreational fishery.

. The department has the following duties:

.. The department shall utilize a program of hatchery-based salmon enhancement and solicit support from cooperative projects, regional enhancement groups, and other supporting organizations to improve recreational salmon fishing in Puget Sound.

.. The department may conduct comprehensive research on resident and migratory salmon production opportunities on marine bottomfish production limitations, and on methods for artificial propagation of depleted marine bottomfish.

.. The program must facilitate continued and improved recreational fishing opportunities in Puget Sound and Lake Washington as measured by increased angler trips of participation. The coordinator, as identified in RCW 77.105.010, shall assist the oversight committee with development of recommendations for outcome-based goals and objectives to assess the effectiveness of the program.

.. The director shall meet with the oversight committee each year to review and approve these goals and objectives.

.. The director and oversight committee shall report annually to the commission on the goals of the program and the effectiveness of the program in meeting those goals. Objectives include, but are not limited to, an increase in salmon and bottomfish angler trips.

.. The department and the oversight committee shall seek to reach consensus regarding program activities and expenditures. The department shall provide the oversight committee with a written explanation when the department expends funds from the recreational fisheries enhancement account that differs substantially from oversight committee recommendations.

.. Consistent with RCW 43.01.036, the department and oversight committee shall make a joint report to the legislature on the effectiveness of this program in biennial reports. Reports must include the goals and objectives of the previous biennium and a determination of whether the goals and objectives were met and an explanation if the department did not meet these specific objectives.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1698.SL.pdf?cite=2011%20c%20266%20§%202[2011 c 266 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2055-S.SL.pdf?cite=1993%20sp.s.%20c%202%20§%2084[1993 sp.s. c 2 § 84]; ]

== 77.105.030 - Planning and operation of programs—Assistance from nondepartmental sources.
The department may seek recommendations from persons who are expert on the planning and operation of programs for enhancement of recreational fisheries. The department may use the expertise of the University of Washington school of aquatic and fishery sciences and the sea grant program to develop research and enhancement programs.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1698.SL.pdf?cite=2011%20c%20266%20§%203[2011 c 266 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2055-S.SL.pdf?cite=1993%20sp.s.%20c%202%20§%2085[1993 sp.s. c 2 § 85]; ]

== 77.105.050 - Marine bottomfish species—Research, methods, and programs for artificial rearing.
The department may conduct research, develop methods, and implement programs for the artificial rearing and release of marine bottomfish species. Marine bottomfish species of importance in the recreational fishery are the primary emphasis. The department may use artificial habitats to restore and mitigate for degraded rockfish habitats and enhance recreational opportunities.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1698.SL.pdf?cite=2011%20c%20266%20§%205[2011 c 266 § 5]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2055-S.SL.pdf?cite=1993%20sp.s.%20c%202%20§%2087[1993 sp.s. c 2 § 87]; ]

== 77.105.140 - Saltwater, combination fishing license—Disposition of fee.
As provided in RCW 77.32.440, a portion of each saltwater and combination fishing license fee shall be deposited in the recreational fisheries enhancement account created in RCW 77.105.150.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%20119[2000 c 107 § 119]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6330-S2.SL.pdf?cite=1998%20c%20191%20§%2028[1998 c 191 § 28]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5102-S.SL.pdf?cite=1997%20c%20197%20§%201[1997 c 197 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2055-S.SL.pdf?cite=1993%20sp.s.%20c%202%20§%2097[1993 sp.s. c 2 § 97]; ]

== 77.105.150 - Recreational fisheries enhancement account.
The recreational fisheries enhancement account is created in the state treasury. All receipts from RCW 77.105.140 shall be deposited into the account. Moneys in the account may be spent only after appropriation. Expenditures from the account may be used only for recreational fisheries enhancement programs identified in this chapter. Under no circumstances may moneys from the account be used to backfill shortfalls in other state funding sources.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5062-S.SL.pdf?cite=2003%20c%20173%20§%203[2003 c 173 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2078-S.SL.pdf?cite=2000%20c%20107%20§%20120[2000 c 107 § 120]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2055-S.SL.pdf?cite=1993%20sp.s.%20c%202%20§%2098[1993 sp.s. c 2 § 98]; ]

== 77.105.160 - Puget Sound recreational fisheries enhancement oversight committee—Created—Duties—Report to the legislature.
. The Puget Sound recreational fisheries enhancement oversight committee is created. The director shall appoint at least seven members representing sport fishing interests to the committee from a list of applicants, ensuring broad representation from the sport fishing community. Each member shall serve for a term of two years, and may be reappointed for subsequent two-year terms at the discretion of the director. Members of the committee serve without compensation.

. The Puget Sound recreational fisheries enhancement oversight committee has the following duties:

.. Advise the department on all aspects of the Puget Sound recreational fisheries enhancement program;

.. Develop recommendations, with assistance from the coordinator, for outcome-based goals and objectives to assess the effectiveness of the program;

.. Meet with the director each year to review these goals and objectives;

.. Report annually with the director to the commission on the goals of the program and the effectiveness of the program in meeting those goals;

.. Review and provide guidance on the annual budget for the recreational fisheries enhancement account;

.. Select a chair of the committee. It is the chair's duty to coordinate with the department on all issues related to the Puget Sound recreational fisheries enhancement program;

.. Meet at least quarterly with the department's coordinator as identified in RCW 77.105.010 of the Puget Sound recreational fisheries enhancement program;

.. Review and comment on program documents and proposed production of salmon and other species;

.. Address other issues related to the purposes of the Puget Sound recreational fisheries enhancement program that are of interest to recreational fishers in Puget Sound; and

.. Consistent with RCW 43.01.036, make a joint report with the department to the legislature each biennium on the status of the program.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1698.SL.pdf?cite=2011%20c%20266%20§%206[2011 c 266 § 6]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5062-S.SL.pdf?cite=2003%20c%20173%20§%202[2003 c 173 § 2]; ]

== 77.105.170 - Managing salmon to increase recreational angling opportunities in Puget Sound.
The department shall utilize artificial rearing of salmon to improve recreational salmon fishing in Puget Sound. In managing salmon, the department shall seek to develop and implement methods that will increase recreational angling opportunities. These methods may include, but are not limited to, the following tools:

. Utilization of salmon artificial rearing techniques that contribute to the recreational fisheries in Puget Sound, especially winter salmon fishing.

. Optimum use of hatchery salmon through expanded recreational mark-selective fisheries.

. Utilization of recreational salmon and marine fish enhancement program funds for catch monitoring when required to increase recreational mark-selective fisheries.

. Consideration of new catch and release recreational fisheries utilizing gear and methods known to minimize hooking mortality.

. Providing public information regarding angling opportunities and fishing methods.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1698.SL.pdf?cite=2011%20c%20266%20§%204[2011 c 266 § 4]; ]

