= 50.01 - General provisions.
:toc:

== 50.01.005 - Short title.
This title shall be known and may be cited as the "Employment Security Act."

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953ex1c8.pdf?cite=1953%20ex.s.%20c%208%20§%2024[1953 ex.s. c 8 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c35.pdf?cite=1945%20c%2035%20§%201[1945 c 35 § 1]; Rem. Supp. 1945 § 9998-140; ]

== 50.01.010 - Preamble.
Whereas, economic insecurity due to unemployment is a serious menace to the health, morals, and welfare of the people of this state; involuntary unemployment is, therefore, a subject of general interest and concern which requires appropriate action by the legislature to prevent its spread and to lighten its burden which now so often falls with crushing force upon the unemployed worker and his or her family. Social security requires protection against this greatest hazard of our economic life. This can be provided only by application of the insurance principle of sharing the risks, and by the systematic accumulation of funds during periods of employment to provide benefits for periods of unemployment, thus maintaining purchasing powers and limiting the serious social consequences of relief assistance. The state of Washington, therefore, exercising herein its police and sovereign power endeavors by this title to remedy any widespread unemployment situation which may occur and to set up safeguards to prevent its recurrence in the years to come. The legislature, therefore, declares that in its considered judgment the public good, and the general welfare of the citizens of this state require the enactment of this measure, under the police powers of the state, for the compulsory setting aside of unemployment reserves to be used for the benefit of persons unemployed through no fault of their own, and that this title shall be liberally construed for the purpose of reducing involuntary unemployment and the suffering caused thereby to the minimum.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%2013001[2010 c 8 § 13001]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2255.SL.pdf?cite=2005%20c%20133%20§%202[2005 c 133 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6097.SL.pdf?cite=2003%202nd%20sp.s.%20c%204%20§%201[2003 2nd sp.s. c 4 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c35.pdf?cite=1945%20c%2035%20§%202[1945 c 35 § 2]; Rem. Supp. 1945 § 9998-141; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c162.pdf?cite=1937%20c%20162%20§%202[1937 c 162 § 2]; ]

