= 50.40 - Miscellaneous provisions.
:toc:

== 50.40.010 - Waiver of rights void.
. Any agreement by an individual to waive, release, or commute his or her rights to benefits or any other rights under this title shall be void.

. Any agreement by an individual in the employ of any person or concern to pay all or any portion of an employer's contributions, required under this title from such employer, shall be void.

. No employer shall directly or indirectly make or require or accept any deduction from remuneration for services to finance the employer's contributions required from him or her, or require or accept any waiver of any right hereunder by any individual in his or her employ.

. A person violating this section is guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20281[2003 c 53 § 281]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c35.pdf?cite=1945%20c%2035%20§%20182[1945 c 35 § 182]; Rem. Supp. 1945 § 9998-321; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c127.pdf?cite=1943%20c%20127%20§%2011[1943 c 127 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c253.pdf?cite=1941%20c%20253%20§%2012[1941 c 253 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c214.pdf?cite=1939%20c%20214%20§%2013[1939 c 214 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c162.pdf?cite=1937%20c%20162%20§%2015[1937 c 162 § 15]; ]

== 50.40.020 - Exemption of benefits.
Any assignment, pledge, or encumbrance of any right to benefits which are or may become due or payable under this title shall be void. Such rights to benefits shall be exempt from levy, execution, attachment, or any other remedy whatsoever provided for the collection of debts, except as provided in RCW 50.40.050. Benefits received by any individual, so long as they are not commingled with other funds of the recipient, shall be exempt from any remedy whatsoever for collection of all debts except debts incurred for necessaries furnished such individual or his or her spouse or dependents during the time when such individual was unemployed. Any waiver of any exemption provided for in this section shall be void.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%2013041[2010 c 8 § 13041]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c18.pdf?cite=1982%201st%20ex.s.%20c%2018%20§%2010[1982 1st ex.s. c 18 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c201.pdf?cite=1982%20c%20201%20§%207[1982 c 201 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c35.pdf?cite=1945%20c%2035%20§%20183[1945 c 35 § 183]; Rem. Supp. 1945 § 9998-322; prior:  1943 c 127 § 11; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c253.pdf?cite=1941%20c%20253%20§%2012[1941 c 253 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c214.pdf?cite=1939%20c%20214%20§%2013[1939 c 214 § 13]; 1937 c 162 § 15. Formerly codified in RCW  50.40.020, part and  50.40.030, part; ]

== 50.40.040 - No vested rights.
The legislature reserves the right to amend or repeal all or any part of this title at any time; and there shall be no vested private right of any kind against such amendment or repeal. All the rights, privileges, or immunities conferred by this title or by acts done pursuant thereto shall exist subject to the power of the legislature to amend or repeal this title at any time.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c35.pdf?cite=1945%20c%2035%20§%20187[1945 c 35 § 187]; no RRS; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c253.pdf?cite=1941%20c%20253%20§%201[1941 c 253 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c214.pdf?cite=1939%20c%20214%20§%201[1939 c 214 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c162.pdf?cite=1937%20c%20162%20§%203[1937 c 162 § 3]; ]

== 50.40.050 - Child support obligations.
. An individual filing a new claim for unemployment compensation shall, at the time of filing the claim, disclose whether or not the individual owes child support obligations as defined under subsection (7) of this section. If the individual discloses that he or she owes child support obligations and is determined to be eligible for unemployment compensation, the commissioner shall notify the state or local child support enforcement agency enforcing those obligations that the individual has been determined to be eligible for unemployment compensation.

. The commissioner shall deduct and withhold from any unemployment compensation payable to an individual who owes child support obligations as defined under subsection (7) of this section:

.. The amount specified by the individual to the commissioner to be deducted and withheld under this subsection, if neither (b) nor (c) of this subsection is applicable;

.. The amount (if any) determined pursuant to an agreement submitted to the commissioner under section 454(20)(B)(i) of the Social Security Act by the state or local child support enforcement agency, unless (c) of this subsection is applicable; or

.. Any amount otherwise required to be so deducted and withheld from such unemployment compensation pursuant to legal process, as that term is defined in section 462(e) of the Social Security Act, properly served upon the commissioner.

. Any amount deducted and withheld under subsection (2) of this section shall be paid by the commissioner to the appropriate state or local child support enforcement agency.

. Any amount deducted and withheld under subsection (2) of this section shall be treated for all purposes as if it were paid to the individual as unemployment compensation and paid by that individual to the state or local child support enforcement agency in satisfaction of the individual's child support obligations.

. For the purposes of this section, "unemployment compensation" means any compensation payable under this chapter including amounts payable by the commissioner under an agreement under any federal law providing for compensation, assistance, or allowances with respect to unemployment.

. This section applies only if appropriate arrangements have been made for reimbursement by the state or local child support enforcement agency for the administrative costs incurred by the commissioner under this section which are attributable to child support obligations being enforced by the state or local child support enforcement agency.

. "Child support obligations" as used in this section means only those obligations which are being enforced pursuant to a plan described in section 454 of the Social Security Act which has been approved by the secretary of health and human services under part D of Title IV of the Social Security Act.

. "State or local child support enforcement agency" as used in this section means any agency of this state or a political subdivision thereof operating pursuant to a plan described in subsection (7) of this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c18.pdf?cite=1982%201st%20ex.s.%20c%2018%20§%2011[1982 1st ex.s. c 18 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c201.pdf?cite=1982%20c%20201%20§%203[1982 c 201 § 3]; ]

== 50.40.071 - Accessible communities account—Creation.
. The accessible communities account is created in the custody of the state treasurer. One hundred dollars of the assessment imposed under RCW 46.19.050 (2), (3), and (4) must be deposited into the account. Any reduction in the penalty or fine and assessment imposed under section 6, chapter 215, Laws of 2010 shall be applied proportionally between the penalty or fine and the assessment.

. The account is subject to the allotment procedures under chapter 43.88 RCW, but an appropriation is not required for expenditures. Only the commissioner may authorize expenditures from the account.

. Expenditures from the account may be used for promoting greater awareness of disability issues and improved access for and inclusion and acceptance of persons with disabilities in communities in the state of Washington, including:

.. Reimbursing travel, per diem, and reasonable accommodation for county accessible community advisory committee meetings and committee sponsored activities including, but not limited to, supporting the involvement of people with disabilities and disability organizations in emergency planning and emergency preparedness activities;

.. Establishing and maintaining an accessible communities web site;

.. Providing training or technical assistance for county accessible community advisory committees;

.. A grant program for funding proposals developed and submitted by county accessible community advisory committees to promote greater awareness of disability issues and acceptance, inclusion, and access for persons with disabilities within the community;

.. Reimbursing the state agency that provides administrative support to the governor's committee on disability issues and employment for costs associated with implementing chapter 215, Laws of 2010; and

.. Programming changes to the judicial information system accounting module required for disbursement of funds to this account.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%20105[2011 c 171 § 105]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5902-S.SL.pdf?cite=2010%20c%20215%20§%202[2010 c 215 § 2]; ]

== 50.40.073 - Accessible communities account—Use of funds—Rules.
. To the extent allowed by funds available from the accessible communities account created in RCW 50.40.071, the governor's committee on disability issues and employment shall:

.. Determine eligibility of accessible community advisory committees for reimbursement or for grant funding according to RCW 36.01.310; and

.. Solicit proposals from active accessible community advisory committees for projects to improve disability awareness and access for persons with disabilities, and shall select projects for funding from moneys available in the accessible communities account.

. The commissioner shall adopt rules to administer this section.

. To the extent allowed by funds available from the accessible communities account created in RCW 50.40.071, the governor's committee on disability issues and employment shall establish an accessible communities web site to provide the following information: Guidance, technical assistance, reference materials, and resource identification for local governments, accessible community advisory committees, and public accommodations; examples of best practices for local initiatives and activities to promote greater awareness of disability issues and access for persons with disabilities within the community; and a searchable listing of local public accommodations that have taken steps to be more disability friendly, including information on the specific access features provided.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5902-S.SL.pdf?cite=2010%20c%20215%20§%203[2010 c 215 § 3]; ]

