= 50.65 - Washington service corps.
:toc:

== 50.65.010 - Legislative findings.
The legislature finds that:

. The unemployment rate in the state of Washington is the highest since the great depression, with a significantly higher rate among Washington youth.

. The policy of the state is to conserve and protect its natural and urban resources, scenic beauty, and historical and cultural sites.

. It is in the public interest to target employment projects to those activities which have the greatest benefit to the local economy.

. There are many unemployed young adults without hope or opportunities for entrance into the labor force who are unable to afford higher education and who create a serious strain on tax revenues in community services.

. The severe cutbacks in community and human services funding leave many local community service agencies without the resources to provide necessary services to those in need.

. The talent and energy of Washington's unemployed young adults are an untapped resource which should be challenged to meet the serious shortage in community services and promote and conserve the valuable resources of the state.

Therefore, the legislature finds it necessary and in the public interest to enact the Washington youth employment and conservation act. As part of this chapter, the Washington service corps is established as an operating program of the employment security department. The legislature desires to facilitate the potential of youth to obtain available job opportunities in both public and private agencies.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c167.pdf?cite=1987%20c%20167%20§%201[1987 c 167 § 1]; 1983 1st ex.s. c 50  § 1; ]

== 50.65.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Commissioner" means the commissioner of the employment security department.

. "Department" means the employment security department.

. "Enrollees" means those persons who have completed enrollment forms, completed a work agreement, and who have entered into the Washington service corps following the approval of the director of the supervising agency.

. "Corps" means the Washington service corps.

. "Work agreement" means the written agreement between the department, the enrollee and the supervising agency under this chapter for a period of up to eighteen months.

. "Supervising agencies" means those private or public agencies which develop and implement full-time service projects in which enrollees agree to participate.

. "Matching funds" means funding that is provided to the employment security department by agencies or individuals as financial support for a portion of the stipend or wage and benefits paid to the enrollee.

. "Financial support" means any thing of value contributed by agencies or individuals to the department for a youth employment project which is reasonably calculated to support directly the development and expansion of a particular program under this chapter and which represents an addition to any financial support previously or customarily provided by the individual or agency. "Financial support" includes, but is not limited to funds, equipment, facilities, and training.

. "Director" means the individual who shall serve as the director of the exchange.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c167.pdf?cite=1987%20c%20167%20§%202[1987 c 167 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c50.pdf?cite=1983%201st%20ex.s.%20c%2050%20§%202[1983 1st ex.s. c 50 § 2]; ]

== 50.65.030 - Washington service corps established—Commissioner's duties.
The Washington service corps is established within the employment security department. The commissioner shall:

. Appoint a director and other personnel as necessary to carry out the purposes of this chapter;

. Coordinate youth employment and training efforts under the department's jurisdiction and cooperate with other agencies or departments providing youth services to ensure that funds appropriated for the purposes of this chapter will not be expended to duplicate existing services, but will increase the services of youth to the state;

. The employment security department is authorized to place subgrants with other federal, state, and local governmental agencies and private agencies to provide youth employment projects and to increase the numbers of youth employed;

. Determine appropriate financial support levels by private business, community groups, foundations, public agencies, and individuals which will provide matching funds for enrollees in service projects under work agreements. The matching funds requirement may be waived for public agencies or reduced for private agencies;

. Recruit enrollees who are residents of the state unemployed at the time of application and are at least eighteen years of age but have not reached their twenty-sixth birthday;

. Recruit supervising agencies to host the enrollees in full-time service activities which shall not exceed eleven months' duration;

. Assist supervising agencies in the development of scholarships and matching funds from private and public agencies, individuals, and foundations in order to support a portion of the enrollee's stipend and benefits;

. Develop general employment guidelines for placement of enrollees in supervising agencies to establish appropriate authority for hiring, firing, grievance procedures, and employment standards which are consistent with state and federal law;

. Match enrollees with appropriate public agencies and available service projects;

. Monitor enrollee activities for compliance with this chapter and compliance with work agreements;

. Assist enrollees in transition to employment upon termination from the programs, including such activities as orientation to the labor market, on-the-job training, and placement in the private sector;

. Establish a program for providing incentives to encourage successful completion of terms of enrollment in the service corps and the continuation of educational pursuits. Such incentives shall be in the form of educational assistance equivalent to two years of community or technical college tuition for eleven months of service. Educational assistance funding shall only be used for tuition, fees, and course-related books and supplies. Enrollees who receive educational assistance funding shall start using it within one year of their service completion and shall finish using it within four years of their service completion;

. Enter into agreements with the state's community and technical college system and other educational institutions or independent nonprofit agencies to provide special education in basic skills, including reading, writing, and mathematics for those participants who may benefit by participation in such classes. Participation is not mandatory but shall be strongly encouraged.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1307-S.SL.pdf?cite=1993%20c%20302%20§%201[1993 c 302 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c167.pdf?cite=1987%20c%20167%20§%203[1987 c 167 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c50.pdf?cite=1983%201st%20ex.s.%20c%2050%20§%203[1983 1st ex.s. c 50 § 3]; ]

== 50.65.040 - Washington service corps—Criteria for enrollment.
The commissioner may select and enroll in the Washington service corps program any person who is at least eighteen years of age but has not reached their twenty-sixth birthday, is a resident of the state, and who is not for medical, legal, or psychological reasons incapable of service. Efforts shall be made to enroll youths who are economically, socially, physically, or educationally disadvantaged. The commissioner may prescribe such additional standards and procedures in consultation with supervising agencies as may be necessary in conformance with this chapter. In addition, the commissioner may select and enroll youth fourteen to seventeen years of age on special projects during the summer and at other times during the school year that may complement and support their school curriculum or that link and support service with learning.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1307-S.SL.pdf?cite=1993%20c%20302%20§%202[1993 c 302 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c167.pdf?cite=1987%20c%20167%20§%204[1987 c 167 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c50.pdf?cite=1983%201st%20ex.s.%20c%2050%20§%204[1983 1st ex.s. c 50 § 4]; ]

== 50.65.050 - Washington service corps—List of local youth employment opportunities.
The commissioner shall use existing local offices of the employment security department or contract with independent, private nonprofit agencies in a local community to establish the Washington service corps program and to insure coverage of the program statewide. Each local office shall maintain a list of available youth employment opportunities in the jurisdiction covered by the local office and the appropriate forms or work agreements to enable the youths to apply for employment in private or public supervising agencies.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c167.pdf?cite=1987%20c%20167%20§%205[1987 c 167 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c50.pdf?cite=1983%201st%20ex.s.%20c%2050%20§%205[1983 1st ex.s. c 50 § 5]; ]

== 50.65.060 - Washington service corps—Placement under work agreements.
Placements in the Washington service corps shall be made in supervising agencies under work agreements as provided under this chapter and shall include those assignments which provide for addressing community needs and conservation problems and will assist the community in economic development efforts. Each work agreement shall:

. Demonstrate that the service project is appropriate for the enrollee's interests, skills, and abilities and that the project is designed to meet unmet community needs;

. Include a requirement of regular performance evaluation. This shall include clear work performance standards set by the supervising agency and procedures for identifying strengths, recommended improvement areas and conditions for probation or dismissal of the enrollee; and

. Include a commitment for partial financial support for the enrollee from private industry, public agencies, community groups, or foundations. The commissioner may establish additional standards for the development of placements for enrollees with supervising agencies and assure that the work agreements comply with those standards. This section shall not apply to conservation corps programs established by chapter 43.220 RCW.

Agencies of the state may use the Washington service corps for the purpose of employing youth qualifying under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1307-S.SL.pdf?cite=1993%20c%20302%20§%203[1993 c 302 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c167.pdf?cite=1987%20c%20167%20§%206[1987 c 167 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c50.pdf?cite=1983%201st%20ex.s.%20c%2050%20§%206[1983 1st ex.s. c 50 § 6]; ]

== 50.65.065 - Work agreements—Requirements.
For each enrollee, the work agreements, or combination of work agreements, developed under RCW 50.65.060 shall:

. Include a variety of experiences consisting of: Indoor activities; outdoor activities; and volunteer activities;

. Provide time for participation in a core training program common to all participants.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1307-S.SL.pdf?cite=1993%20c%20302%20§%204[1993 c 302 § 4]; ]

== 50.65.070 - Enrollees not to displace current workers.
The assignment of enrollees shall not result in the displacement of currently employed workers, including partial displacement such as reduction in hours of nonovertime work, wages, or other employment benefits. Supervising agencies that participate in the program may not terminate, lay-off, or reduce the working hours of any employee for the purpose of utilizing an enrollee with funds available. In circumstances where substantial efficiencies or a public purpose may result, supervising agencies may utilize enrollees to carry out essential agency work or contractual functions without displacing current employees.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c50.pdf?cite=1983%201st%20ex.s.%20c%2050%20§%207[1983 1st ex.s. c 50 § 7]; ]

== 50.65.080 - Commissioner to seek assistance for Washington service corps.
The commissioner shall seek and may accept, on behalf of the Washington service corps, charitable donations of cash and other assistance including, but not limited to, equipment and materials if the donations are available for appropriate use for the purposes set forth in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1307-S.SL.pdf?cite=1993%20c%20302%20§%206[1993 c 302 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c50.pdf?cite=1983%201st%20ex.s.%20c%2050%20§%208[1983 1st ex.s. c 50 § 8]; ]

== 50.65.090 - Authority for income-generating projects—Disposition of income.
The commissioner may enter into income-generating projects with public or private organizations to further the purposes of this chapter. Moneys received from contractual projects qualifying under this chapter shall be deposited in the state general fund. This section does not apply to conservation corps programs established by chapter 43.220 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c50.pdf?cite=1983%201st%20ex.s.%20c%2050%20§%209[1983 1st ex.s. c 50 § 9]; ]

== 50.65.100 - Work agreements—Nondiscrimination.
All parties entering into work agreements under this chapter shall agree that they will not discriminate in the providing of any service on the basis of race, creed, ethnic origin, sex, age, or political affiliation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c50.pdf?cite=1983%201st%20ex.s.%20c%2050%20§%2010[1983 1st ex.s. c 50 § 10]; ]

== 50.65.110 - Enrollees—Training and subsistence allowance—Medical insurance and medical aid—Notice of coverage.
The compensation received shall be considered a training and subsistence allowance. Comprehensive medical insurance, and medical aid shall be paid for the enrollees in the service corps by the commissioner in accordance with the standards and limitations of the appropriation provided for this chapter. The department shall give notice of coverage to the director of labor and industries after enrollment. The department shall not be deemed an employer of an enrollee for any other purpose.

Other provisions of law relating to civil service, hours of work, rate of compensation, sick leave, unemployment compensation, old age health and survivor's insurance, state retirement plans, and vacation leave do not apply to enrollees.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c167.pdf?cite=1987%20c%20167%20§%207[1987 c 167 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c230.pdf?cite=1985%20c%20230%20§%206[1985 c 230 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c50.pdf?cite=1983%201st%20ex.s.%20c%2050%20§%2011[1983 1st ex.s. c 50 § 11]; ]

== 50.65.120 - Exemption of enrollees from unemployment compensation coverage.
The services of enrollees placed with supervising agencies described in chapter 50.44 RCW are exempt from unemployment compensation coverage under *RCW 50.44.040(5) and the enrollees shall be so advised by the department.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c50.pdf?cite=1983%201st%20ex.s.%20c%2050%20§%2012[1983 1st ex.s. c 50 § 12]; ]

== 50.65.130 - Federal and private sector funds and grants.
In addition to any other power, duty, or function described by law or rule, the employment security department, through the program established under this chapter, may accept federal or private sector funds and grants and implement such programs relating to community services or employment programs and may enter into contracts respecting such funds or grants. The department may also use funds appropriated for the purposes of this chapter as matching funds for federal or private source funds to accomplish the purposes of this chapter. The Washington service corps shall be the sole recipient of federal funds for youth employment and conservation corps programs.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c167.pdf?cite=1987%20c%20167%20§%208[1987 c 167 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c50.pdf?cite=1983%201st%20ex.s.%20c%2050%20§%2013[1983 1st ex.s. c 50 § 13]; ]

== 50.65.138 - Use of funds for enrollees and projects in distressed areas—Service corps.
Sixty percent of the general funds available to the service corps program shall be for enrollees from distressed areas and for projects in distressed areas. A distressed area shall mean:

. A county which has an unemployment rate which is twenty percent above the state average for the immediately preceding three years;

. A community which has experienced sudden and severe loss of employment; or

. An area within a county which area:

.. Is composed of contiguous census tracts;

.. Has a minimum population of five thousand persons;

.. The median household income is at least thirty-five percent below the county's median household income, as determined from data collected for the preceding United States ten-year census; and

.. Has an unemployment rate which is at least forty percent higher than the county's unemployment rate. For purposes of this definition, "families and unrelated individuals" has the same meaning that is ascribed to that term by the federal department of housing and urban development in its regulations authorizing action grants for economic development and neighborhood revitalization projects.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c167.pdf?cite=1987%20c%20167%20§%2010[1987 c 167 § 10]; ]

== 50.65.143 - Limitation on use of funds for administration—Service corps.
. Not more than fifteen percent of the funds available for the service corps shall be expended for administrative costs. For the purposes of this chapter, "administrative costs" include, but are not limited to, program planning and evaluation, budget development and monitoring, personnel management, contract administration, administrative payroll, development of program reports, and administrative office space costs and utilities.

. The fifteen percent limitation does not include costs for any of the following: Program support activities such as direct supervision of enrollees and corpsmembers, counseling, education and job training, equipment, advisory board expenses, and extraordinary recruitment and placement procedures necessary to fill project positions.

. The total for all items included under subsection (1) of this section and excluded under subsection (2) of this section shall not: (a) Exceed thirty percent of the appropriated funds available during a fiscal biennium for the service and conservation corps programs; or (b) result in an average cost per enrollee or corpsmember from general funds exceeding seven thousand dollars in the 1987-89 biennium and in succeeding biennia as adjusted by inflation factors established by the office of financial management for state budgeting purposes. The test included in (a) and (b) of this subsection are in the alternative, and it is only required that one of the tests be satisfied.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c167.pdf?cite=1987%20c%20167%20§%2011[1987 c 167 § 11]; ]

== 50.65.200 - Washington serves—Findings—Declaration.
The legislature finds that:

. Budget constraints are causing severe gaps and reductions in vital services to local communities and citizens. Some of these gaps in services can be filled by citizen volunteers through an organized program to recruit and place volunteers and to expand opportunities for volunteers to serve their communities;

. The federal government is proposing expansion of national services programs. These programs may require significant matching resources from states. State funds supporting the Washington serves program can serve as a required matching source to leverage additional federal national service resources;

. Washington state has, through the Washington service corps, successfully offered service opportunities and meaningful work experience to young adults between the ages of eighteen and twenty-five years;

. The need exists to expand full-time volunteer opportunities to citizens age twenty-one and over, to encourage senior citizens, college graduates, professional and technically skilled persons, and other adult citizens, to contribute their critical expertise, experience, labor, and commitment to meeting the needs of their communities;

. It is appropriate and in the public's interest for Washington state to create opportunities for citizens to engage in full-time, meaningful volunteer service in governmental or private nonprofit agencies, institutions, programs, or activities that address the social, economic, educational, civic, cultural, or environmental needs of local communities;

. Through volunteer service, citizens apply their skills and knowledge to the resolution of critical problems or meeting unmet needs, gain valuable experience, refine or develop new skills, and instill a sense of civic pride and commitment to their community;

. There is a need to coordinate state and federally funded volunteer service programs that provide living allowances and other benefits to volunteers to maximize the benefits to volunteers and the organizations in which they serve.

It is therefore the legislature's desire to expand full-time volunteer opportunities for citizens age twenty-one and over and to provide appropriate incentives to those who serve. Such a program should be implemented statewide and coordinated across programs.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1969-S.SL.pdf?cite=1993%20sp.s.%20c%207%20§%201[1993 sp.s. c 7 § 1]; ]

== 50.65.210 - Washington serves—Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Commissioner" means the commissioner of the employment security department.

. "*Council" means the Washington council on volunteerism and citizen service authorized by chapter 43.150 RCW.

. "Department" means the employment security department.

. "Volunteer" means a person at least twenty-one years of age who, upon application and acceptance into the program, is placed in a governmental or private, nonprofit organization to perform full-time service for the benefit of the community, and who receives a living allowance and other benefits as authorized under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1969-S.SL.pdf?cite=1993%20sp.s.%20c%207%20§%202[1993 sp.s. c 7 § 2]; ]

== 50.65.220 - Washington serves—Program—Created—Procedure—Intent.
There is hereby created within the employment security department a program for full-time community service that shall be known and referred to as the Washington serves program. The department shall recruit, train, place, and evaluate applicants to the program. The department may accept applications and enter into agreements or contracts with any governmental or private nonprofit organization appropriate for placement of volunteers under this program. The commissioner, after consultation with the council, may adopt rules as needed to carry out the intent and purposes of this program. It is the intent of the legislature that the commissioner coordinate this program with all volunteer service programs, whether funded with state or federal dollars, in order to maximize the benefits to volunteers and the communities served under the program. It is also the legislature's intent that to the extent that state funds are paid directly to persons that participate in the program, whether to reimburse, support, assist, or provide other direct payment, no volunteer may have such reimbursement, support, assistance, or other payment reduced or withheld for having served in the program.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1969-S.SL.pdf?cite=1993%20sp.s.%20c%207%20§%203[1993 sp.s. c 7 § 3]; ]

== 50.65.230 - Washington serves—Applicants—Eligibility.
. Applicants to the Washington serves program shall be at least twenty-one years of age and a resident of Washington state.

. Applicants may apply to serve for a period of service of one year, except that volunteers may serve for periods of service of less than one year if it is determined by the commissioner, on an individual basis, that a period of service of less than one year is necessary to meet a critical scarce skill or necessary to enable a person or organization to participate in the program.

. Volunteers may reapply for periods of service totaling not more than two additional years.

. Applicants to the program shall be committed to providing full-time service to the community.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1969-S.SL.pdf?cite=1993%20sp.s.%20c%207%20§%204[1993 sp.s. c 7 § 4]; ]

== 50.65.240 - Washington serves—Disqualification for Washington service corps participation.
No individual may participate in the Washington serves program created by chapter 7, Laws of 1993 sp. sess., if the person has previously participated for six months or longer in the Washington service corps within the last three years.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1307-S.SL.pdf?cite=1993%20c%20302%20§%2010[1993 c 302 § 10]; ]

== 50.65.250 - Washington serves—Volunteers—Selection—Placement.
. Program volunteers shall be selected from among qualified individuals submitting applications for full-time service at such time, in such form, and containing such information as may be necessary to evaluate the suitability of each individual for service, and available placements. The commissioner or the commissioner's designee shall review the application of each individual who applies in conformance with selection criteria established by the commissioner after consultation with the council, and who, on the basis of the information provided in the application, is determined to be suitable to serve as a volunteer under the Washington serves program. 

. Within available funds, volunteers may be placed with any public or private nonprofit organization, program, or project that qualifies to accept program volunteers according to the rules and application procedures established by the commissioner. Work shall benefit the community or state at large and may include but is not limited to programs, projects, or activities that:

.. Address the problems of jobless, homeless, hungry, illiterate, or functionally illiterate persons, and low-income youths;

.. Provide support and a special focus on those project activities that address the needs of the unemployed and those in need of job training or retraining;

.. Address significant health care problems, including services to homeless individuals and other low-income persons, especially children, through prevention and treatment;

.. Meet the health, education, welfare, or related needs of low-income persons, particularly children and low-income minority communities;

.. Provide care or rehabilitation services to the mentally ill, developmentally disabled, or other persons with disabilities;

.. Address the educational and education-related needs of children, youth, families, and young adults within public educational institutions or related programs;

.. Address alcohol and drug abuse prevention, education, and related activities; and

.. Seek to enhance, improve, or restore the environment or that educate or advocate for a sustainable environment.

. Every reasonable effort shall be made to place participants in programs, projects, or activities of their choice if the agencies, programs, or activities are consistent with the intent and purposes of the Washington serves program, if there is mutual agreement between the agency, program, or activity and the volunteer, and if the volunteer's service is consistent with the intent and purpose of the program and would benefit the community or the state as a whole.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1969-S.SL.pdf?cite=1993%20sp.s.%20c%207%20§%205[1993 sp.s. c 7 § 5]; ]

== 50.65.260 - Washington serves—Volunteers—Support.
. Volunteers accepted into the Washington serves program and placed in an approved agency, program, or activity, shall be provided a monthly subsistence allowance in an amount determined by the commissioner taking into consideration the allowance given to VISTA, Washington service corps, and other similar service programs. For those persons who qualify and are granted a deferment of federal student loan payments while serving in the program, the rate of compensation shall be equal to but not greater than the monthly subsistence allowance granted Volunteers In Service To America (VISTA) serving in this state, as determined by the national ACTION agency or its successor, in accordance with section 105(b)(2) of the Domestic Volunteer Service Act of 1973, P.L. 93-113, as amended.

. The commissioner or the commissioner's designee shall, within available funds, ensure that each volunteer has available support to enable the volunteer to perform the work to which the volunteer is assigned. Such support may include, but is not limited to, reimbursement for travel expenses, payment for education and training expenses, including preservice and on-the-job training necessary for the performance of duties, technical assistance, and other support deemed necessary and appropriate. 

. At the end of each volunteer's period of service of not less than one year, each volunteer may receive a postservice stipend for each month of completed service in an amount determined by the commissioner. The postservice stipend for those persons who qualify and are granted a deferment of federal student loan payments while serving in this program shall be an amount equal to but not greater than the amount or rate determined by the national ACTION agency or its successor, in accordance with section 105(b)(2) of the Domestic Volunteer Service Act of 1973, P.L. 93-113 as amended, for Volunteers In Service To America (VISTA), who are providing services in this state. Volunteers under the Washington serves program may accrue the stipend for each month of their service period of not less than one year, including any month during which they were in training. The commissioner or the commissioner's designee may, on an individual basis, make an exception to provide a stipend to a volunteer who has served less than one year.

. Stipends shall be payable to the volunteer only upon completion of the period of service. Under circumstances determined by the commissioner, the stipend may be paid on behalf of the volunteer to members of the volunteer's family or others designated by the volunteer.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1969-S.SL.pdf?cite=1993%20sp.s.%20c%207%20§%206[1993 sp.s. c 7 § 6]; ]

== 50.65.270 - Washington serves—Volunteers—Medical benefits—Benefit limits.
Within available funds, medical aid coverage under chapter 51.36 RCW and medical insurance shall be provided to all volunteers under this program. The department shall give notice of medical aid coverage to the director of labor and industries upon acceptance of the volunteer into the program. The department shall not be deemed an employer of any volunteer under the Washington serves program for any other purpose. Other provisions of law relating to civil service, hours of work, rate of compensation, sick leave, unemployment compensation, old age, health and survivor's insurance, state retirement plans, and vacation leave do not apply to volunteers under this program.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1969-S.SL.pdf?cite=1993%20sp.s.%20c%207%20§%207[1993 sp.s. c 7 § 7]; ]

== 50.65.280 - Washington serves—Displacement of current workers prohibited.
The assignment of volunteers under the Washington serves program shall not result in the displacement of currently employed workers, including partial displacement such as would result from a reduction in hours of nonovertime work, wages, or other employment benefits. Participating agencies, programs, or activities may not terminate, lay off, or reduce the working hours of any employee for the purpose of using volunteers under the Washington serves program. In circumstances where substantial efficiencies or a public purpose may result, participating agencies may use volunteers to carry out essential agency work or contractual functions without displacing current employees.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1969-S.SL.pdf?cite=1993%20sp.s.%20c%207%20§%208[1993 sp.s. c 7 § 8]; ]

== 50.65.290 - Washington serves—Volunteers—Unemployment compensation coverage limited.
The services of volunteers placed with participating agencies described in chapter 50.44 RCW are not eligible for unemployment compensation coverage. Each volunteer shall be so advised by the commissioner or the commissioner's designee.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1969-S.SL.pdf?cite=1993%20sp.s.%20c%207%20§%209[1993 sp.s. c 7 § 9]; ]

== 50.65.300 - Washington serves—Volunteers—Assistance to defer student loan payments.
The commissioner or the commissioner's designee may assist any volunteer serving full-time under the Washington serves program in obtaining a service deferment of federally funded student loan payments during his or her period of service.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1969-S.SL.pdf?cite=1993%20sp.s.%20c%207%20§%2010[1993 sp.s. c 7 § 10]; ]

== 50.65.310 - Washington serves—Volunteers—Subsequent development of skills and experience—Recognition.
The commissioner or the commissioner's designee may provide or arrange for educational, vocational, or job counseling for program volunteers at the end of their period of service to (1) encourage volunteers to use the skills and experience which they have derived from their training and service, and (2) promote the development of appropriate opportunities for the use of such skills and experience, and the placement therein of such volunteers. The commissioner or the commissioner's designee may also assist volunteers in developing a plan for gainful employment.

The commissioner shall provide for an appropriate means of recognition or certification of volunteer service.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1969-S.SL.pdf?cite=1993%20sp.s.%20c%207%20§%2011[1993 sp.s. c 7 § 11]; ]

== 50.65.320 - Washington serves—Service placement—Work agreements—Contracts—Rules for agencies—Financial support for organizations.
The executive administrator of the Washington serves program shall recruit and develop service placements and may enter into work agreements or contracts as needed to implement the Washington serves program. The commissioner, after consultation with the council, may adopt rules for participating agencies which rules may include, but are not limited to: Supervision of volunteers, reasonable work space or other working environment conditions, ongoing training, the handling of grievances or disputes, performance evaluations, frequency of agency contacts, and liability insurance coverage. The commissioner shall determine financial support levels for organizations receiving volunteer placements that will provide matching funds for enrollees in service projects under work agreements.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1969-S.SL.pdf?cite=1993%20sp.s.%20c%207%20§%2012[1993 sp.s. c 7 § 12]; ]

== 50.65.330 - Washington serves—Gifts, grants, endowments—Matching funds.
The department may receive such gifts, grants, and endowments from private or public sources that may be made from time to time, in trust or otherwise, for the use and benefit of the Washington serves program and spend the same or any income therefrom according to the terms of the gifts, grants, or endowments. 

The department may also use funds appropriated for the purposes of this chapter as matching funds for federal or private source funds to accomplish the purposes of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1969-S.SL.pdf?cite=1993%20sp.s.%20c%207%20§%2013[1993 sp.s. c 7 § 13]; ]

== 50.65.901 - Conflict with federal requirements—1983 1st ex.s. c 50.
If any part of this act is found to be in conflict with federal requirements which are a prescribed condition to the allocation of federal funds to the state, such conflicting part of this act is declared to be inoperative solely to the extent of the conflict, and such finding or determination shall not affect the operation of the remainder of this act. The rules under this act shall meet federal requirements which are a necessary condition to the receipt of federal funds by the state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c50.pdf?cite=1983%201st%20ex.s.%20c%2050%20§%2016[1983 1st ex.s. c 50 § 16]; ]

== 50.65.903 - Conflict with federal requirements—1987 c 167.
If any part of this chapter is found to be in conflict with federal requirements which are a prescribed condition to the allocation of federal funds to the state, such conflicting part of this chapter is declared to be inoperative solely to the extent of the conflict, and such finding or determination shall not affect the operation of the remainder of this chapter. The rules under this chapter shall meet federal requirements which are a necessary condition to the receipt of federal funds by the state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c167.pdf?cite=1987%20c%20167%20§%2012[1987 c 167 § 12]; ]

== 50.65.906 - Conflict with federal requirements—1993 sp.s. c 7.
If any part of this act is found to be in conflict with federal requirements which are prescribed conditions to the receipt of federal funds or participation in any federal program, such conflicting part of this act is declared to be inoperative solely to the extent of the conflict, and such finding or determination shall not affect the operation of the remainder of the act. Rules adopted pursuant to this act shall meet federal requirements which are a necessary condition to the receipt of federal funds by the state.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1969-S.SL.pdf?cite=1993%20sp.s.%20c%207%20§%2014[1993 sp.s. c 7 § 14]; ]

== 50.65.907 - Short title—1993 sp.s. c 7.
Sections 1 through 13 of this act may be known and cited as the Washington serves act.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1969-S.SL.pdf?cite=1993%20sp.s.%20c%207%20§%2015[1993 sp.s. c 7 § 15]; ]

