= 50.70 - Programs for dislocated forest products workers.
:toc:

== 50.70.030 - Employment opportunities—Benefits.
. Employment opportunities under the program shall consist of activities that improve the value of state lands and waters. These activities may include, but are not limited to, thinning and precommercial thinning, pruning, slash removal, reforestation, fire suppression, trail maintenance, maintenance of recreational facilities, dike repair, development and maintenance of tourist facilities, and stream enhancement.

. Enrollees in the program shall receive medical and dental benefits as provided under chapter 41.05 RCW, but are exempt from the provisions of chapter 41.06 RCW. Each week, enrollees shall not work more than thirty-two hours in this program and must participate in eight hours of career orientation as established in RCW 50.70.040. Participation in the program is limited to six months.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5555-S.SL.pdf?cite=1991%20c%20315%20§%207[1991 c 315 § 7]; ]

== 50.70.040 - Recruitment—Career orientation services—Career counseling.
. The department shall recruit program applicants and provide employment opportunities by:

.. Notifying dislocated forest products workers who are receiving unemployment benefits, or dislocated forest products workers who have exhausted unemployment benefits, of their eligibility for the program.

.. Establishing procedures for dislocated forest products workers to apply to the program.

.. Developing a pool of workers eligible to enroll in the program.

.. Contracting with the department of natural resources to provide employment opportunities for not less than two hundred eligible enrollees.

. The department shall provide career orientation services to enrollees in the program. The career orientation services shall include, but are not limited to, counseling on employment options and assistance in accessing retraining programs, and assistance in accessing social service programs.

. The department shall provide at least eight hours of career counseling each week for program enrollees.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5555-S.SL.pdf?cite=1991%20c%20315%20§%208[1991 c 315 § 8]; ]

== 50.70.050 - Department of natural resources duties.
. The department of natural resources shall enroll candidates in the program from a pool of eligible workers developed by the department.

. The department of natural resources shall provide compensation for enrollees.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5555-S.SL.pdf?cite=1991%20c%20315%20§%209[1991 c 315 § 9]; ]

== 50.70.901 - Conflict with federal requirements—1991 c 315.
If any part of this act is found to be in conflict with federal requirements which are a prescribed condition to the allocation of federal funds to the state or the eligibility of employers in this state for federal unemployment tax credits, the conflicting part of this act is hereby declared to be inoperative solely to the extent of the conflict, and such finding or determination shall not affect the operation of the remainder of this act. The rules under this act shall meet federal requirements which are a necessary condition to the receipt of federal funds by the state or the granting of federal unemployment tax credits to employers in this state.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5555-S.SL.pdf?cite=1991%20c%20315%20§%2032[1991 c 315 § 32]; ]

