= 50.72 - Youthbuild program.
:toc:

== 50.72.010 - Legislative findings.
. The legislature finds that there is a need to:

.. Expand the supply of permanent affordable housing for homeless individuals, low and very low-income persons, and special need populations by utilizing the energies and talents of economically disadvantaged youth;

.. Provide economically disadvantaged youth with opportunities for meaningful work and service to their communities in helping to meet the housing needs of homeless individuals, low and very low-income persons, and special need populations;

.. Enable economically disadvantaged youth to obtain the education and employment skills necessary to achieve economic self-sufficiency; and

.. Foster the development of leadership skills and commitment to community development among youth in designated community empowerment zones.

. The legislature declares that the purpose of the Washington youthbuild program is to:

.. Help disadvantaged youth who have dropped out of school to obtain the education and employment skills necessary to achieve economic self-sufficiency and develop leadership skills and a commitment to community development in designated community empowerment zones; and

.. Provide funding assistance to entities implementing programs that provide comprehensive education and skills training programs designed to lead to self-sufficiency for economically disadvantaged youth.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2699-S.SL.pdf?cite=1994%20sp.s.%20c%203%20§%201[1994 sp.s. c 3 § 1]; ]

== 50.72.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Applicant" means a public or private nonprofit organization agency eligible to provide education and employment training under federal or state employment training programs.

. "Commissioner" means the commissioner of employment security.

. "Department" means the employment security department.

. "Low income" has the same meaning as in RCW 43.185A.010.

. "Participant" means an individual that:

.. Is sixteen to twenty-four years of age, inclusive;

.. Is or is a member of a very low-income household; and

.. Is neither attending any school nor subject to a compulsory attendance law and who has not received a secondary school diploma or a certificate of equivalency for such diploma.

. "Very low income" means a person or household whose income is at or below fifty percent of the median family income, adjusted for household size, for the county where the household is located.

. "Youthbuild" means any program that provides disadvantaged youth with opportunities for employment, education, leadership development, entrepreneurial skills development, and training in the construction or rehabilitation of housing for special need populations, very low-income households, or low-income households.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2699-S.SL.pdf?cite=1994%20sp.s.%20c%203%20§%202[1994 sp.s. c 3 § 2]; ]

== 50.72.030 - Commissioner's duties—Education and employment training grants.
The Washington youthbuild program is established within the department. The commissioner, in cooperation and consultation with the director of the *department of community, trade, and economic development, shall:

. Make grants, up to the lesser of three hundred thousand dollars or twenty-five percent of the total costs of the youthbuild activities, to applicants eligible to provide education and employment training under federal or state employment training programs, for the purpose of carrying out a wide range of multidisciplinary activities and services to assist economically disadvantaged youth under the federal opportunities for youth: Youthbuild program (106 Stat. 3723; 42 U.S.C. Sec. 8011), or locally developed youthbuild-type programs for economically disadvantaged youth; and

. Coordinate youth employment and training efforts under the department's jurisdiction and cooperate with other agencies and departments providing youth services to ensure that funds appropriated for the purposes of this chapter will be used to supplement funding from federal, state, local, or private sources.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2699-S.SL.pdf?cite=1994%20sp.s.%20c%203%20§%203[1994 sp.s. c 3 § 3]; ]

== 50.72.040 - Education and employment training grants—Eligible activities.
. Grants made under this chapter shall be used to fund an applicant's activities to implement a comprehensive education and employment skills training program.

. Activities eligible for assistance under this chapter include:

.. Education and job skills training services and activities that include:

... Work experience and skills training, coordinated to the maximum extent feasible, with preapprenticeship and apprenticeship programs in construction and rehabilitation trades;

... Services and activities designed to meet the educational needs of participants, including basic skills instruction and remedial education, bilingual education for participants with limited English proficiency, secondary education services and activities designed to lead to the attainment of a high school diploma or its equivalent, and counseling and assistance in attaining postsecondary education and required financial aid;

.. Counseling services and related activities;

.. Activities designed to develop employment and leadership skills;

.. Support services and need-based stipends necessary to enable the participant to participate in the program and to assist participants through support services in retaining employment;

.. Wage stipends and benefits provided to participants; and

.. Administrative costs of the applicant, not to exceed five percent of the amount of assistance provided under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2699-S.SL.pdf?cite=1994%20sp.s.%20c%203%20§%204[1994 sp.s. c 3 § 4]; ]

== 50.72.050 - Participation time limits—Educational services and activities requirement.
. An individual selected as a participant in the youthbuild program under this chapter may be offered full-time participation for a period of not less than six months and not more than twenty-four months.

. An applicant's program that is selected for funding under this chapter shall be structured so that fifty percent of the time spent by the participants in the youthbuild program is devoted to educational services and activities, such as those outlined in RCW 50.72.040.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2699-S.SL.pdf?cite=1994%20sp.s.%20c%203%20§%205[1994 sp.s. c 3 § 5]; ]

== 50.72.060 - Grant applications—Requirements.
. An application for a grant under this chapter shall be submitted by the applicant in such form and in accordance with the requirements as determined by the commissioner.

. The application for a grant under this chapter shall contain at a minimum:

.. The amount of the grant request and its proposed use;

.. A description of the applicant and a statement of its qualifications, including a description of the applicant's past experience with housing rehabilitation or construction with youth and youth education and employment training programs, and its relationship with local unions and apprenticeship programs and other community groups;

.. A description of the proposed site for the program;

.. A description of the educational and job training activities, work opportunities, and other services that will be provided to participants;

.. A description of the proposed construction or rehabilitation activities to be undertaken and the anticipated schedule for carrying out such activities;

.. A description of the manner in which eligible participants will be recruited and selected, including a description of arrangements which will be made with federal or state agencies, community-based organizations, local school districts, the courts of jurisdiction for status and youth offenders, shelters for homeless individuals and other agencies that serve homeless youth, foster care agencies, and other appropriate public and private agencies;

.. A description of the special outreach efforts that will be undertaken to recruit eligible young women, including young women with dependent children;

.. A description of how the proposed program will be coordinated with other federal, state, local, and private resources and programs, including vocational, adult, and bilingual education programs, and job training programs;

.. Assurances that there will be a sufficient number of adequately trained supervisory personnel in the program who have attained journey level status or have served an apprenticeship through the Washington state apprenticeship training council;

.. A description of the applicant's relationship with building contractor groups and trade unions regarding their involvement in training, and the relationship of the youthbuild program with established apprenticeship and training programs;

.. A description of activities that will be undertaken to develop the leadership skills of the participants;

.. A description of the commitments for any additional resources to be made available to the local program from the applicant, from recipients of other federal, state, local, or private sources; and

.. Other factors the commissioner deems necessary.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%2013045[2010 c 8 § 13045]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2699-S.SL.pdf?cite=1994%20sp.s.%20c%203%20§%206[1994 sp.s. c 3 § 6]; ]

== 50.72.070 - Grant applicants—Information required—Evaluation reports.
. An applicant selected for funding under this chapter shall provide the department information on program and participant accomplishments. The information shall be provided in progress and final reports as requested by the department.

. A final evaluation report shall be prepared on individual programs at the time of their completion. The final evaluation report shall include, but is not limited to, information on the effectiveness of the program, the status of program participants, and recommendations on program administration at the state and local level.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%20103[1998 c 245 § 103]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2699-S.SL.pdf?cite=1994%20sp.s.%20c%203%20§%207[1994 sp.s. c 3 § 7]; ]

