= 50A.50 - Appeals.
:toc:

== 50A.50.010 - Generally.
. Any aggrieved party may file an appeal from any determination or redetermination with the commissioner within thirty days after the date of notification or mailing, whichever is earlier, of such determination or redetermination to the party's last known address. If an appeal with respect to any determination is pending as of the date when a redetermination is issued, such appeal, unless withdrawn, shall be treated as an appeal from such redetermination.

. Any appeal from a determination of denial of benefits shall be deemed to be an appeal as to all weeks subsequent to the effective date of the denial for which benefits have already been denied. If no appeal is taken from any determination, or redetermination, within the time allowed by the provisions of this section for appeal, the determination or redetermination, as the case may be, shall be conclusively deemed to be correct except as provided in respect to reconsideration by the commissioner of any determination.

. Upon receipt of a notice of appeal, the commissioner shall request the assignment of an administrative law judge under chapter 34.12 RCW to conduct a hearing in accordance with chapter 34.05 RCW and issue a proposed order.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2614-S.SL.pdf?cite=2020%20c%20125%20§%2014[2020 c 125 § 14]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2702.SL.pdf?cite=2018%20c%20141%20§%203[2018 c 141 § 3]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2034[2017 3rd sp.s. c 5 § 34]; ]

== 50A.50.020 - Assessments.
. When an order and notice of assessment has been served upon or mailed to a delinquent employer, the employer may within thirty days file an appeal with the department, stating that the assessment is unjust or incorrect and requesting a hearing. The appeal must set forth the reasons why the assessment is objected to and the amount of premiums, if any, which the employer admits to be due. If no appeal is filed, the assessment shall be conclusively deemed to be just and correct except that in such case, and in cases where payment of premiums, interest, or penalties has been made pursuant to a jeopardy assessment, the commissioner may properly entertain a subsequent application for refund. The filing of an appeal on a disputed assessment with the administrative law judge stays the distraint and sale proceeding provided for in this title until a final decision has been made, but the filing of an appeal shall not affect the right of the commissioner to perfect a lien, as provided by this title, upon the property of the employer. The filing of a petition on a disputed assessment stays the accrual of interest and penalties on the disputed premiums until a final decision is made.

. Within thirty days after notice of denial of refund or adjustment has been mailed or delivered, whichever is the earlier, to an employer, the employer may file an appeal with the department for a hearing unless assessments have been appealed from and have become final. The employer shall set forth the reasons why such hearing should be granted and the amount which the employer believes should be adjusted or refunded. If no appeal is filed within said thirty days, the determination of the commissioner as stated in the notice shall be final.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1399-S.SL.pdf?cite=2019%20c%2013%20§%2044[2019 c 13 § 44]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2036[2017 3rd sp.s. c 5 § 36]; ]

== 50A.50.030 - Benefit redeterminations.
. A determination of amount of benefits potentially payable under this title is not a basis for appeal. However, the determination is subject to request by the employee on family and medical leave for redetermination by the commissioner at any time within one year from the date of delivery or mailing of such determination, or any redetermination thereof. A redetermination shall be furnished to the employee in writing and provide the basis for appeal.

. A determination of denial of benefits becomes final, in the absence of timely appeal therefrom. The commissioner may redetermine such determinations at any time within one year from delivery or mailing to correct an error in identity, omission of fact, or misapplication of law with respect to the facts.

. A determination of allowance of benefits becomes final, in the absence of a timely appeal therefrom. The commissioner may redetermine such allowance at any time within two years following the eligibility period in which such allowance was made in order to recover any benefits for which recovery is provided under this title.

. A redetermination may be made at any time: (a) To conform to a final court decision applicable to either an initial determination or a determination of denial or allowance of benefits; (b) in the event of a back pay award or settlement affecting the allowance of benefits; or (c) in the case of misrepresentation or willful failure to report a material fact. Written notice of any such redetermination shall be promptly given by mail or delivered to such interested parties as were notified of the initial determination or determination of denial or allowance of benefits and any new interested party or parties who, pursuant to such rule as the commissioner may adopt, would be an interested party.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1399-S.SL.pdf?cite=2019%20c%2013%20§%2045[2019 c 13 § 45]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2053[2017 3rd sp.s. c 5 § 53]; ]

== 50A.50.040 - When deemed filed and received.
The appeal or petition from a determination, redetermination, order and notice of assessment, appeals decision, or commissioner's decision is deemed filed and received if properly addressed and with sufficient postage:

. If transmitted through the United States mail, on the date shown by the United States postal service cancellation mark;

. If mailed but not received by the addressee, or where received and the United States postal service cancellation mark is illegible, erroneous, or omitted, on the date it was mailed, if the sender establishes by competent evidence that the appeal or petition was deposited in the United States mail on or before the date due for filing; or

. In the case of a metered cancellation mark by the sender and a United States postal service cancellation mark on the same envelope or other wrapper, the latter shall control.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2035[2017 3rd sp.s. c 5 § 35]; ]

== 50A.50.050 - Assessments—Procedure.
In any proceeding before an administrative law judge involving an appeal from a disputed order and notice of assessment or a disputed denial of refund or adjustment, the administrative law judge, after affording the parties a reasonable opportunity for hearing, shall affirm, modify, or set aside the notice of assessment or denial of refund. The parties shall be duly notified of such decision together with the reasons, which shall be deemed to be the final decision unless within thirty days after the date of notification or mailing, whichever is the earlier, of such decision, further appeal is perfected pursuant to the provisions of this title relating to review by the commissioner.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1399-S.SL.pdf?cite=2019%20c%2013%20§%2046[2019 c 13 § 46]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2038[2017 3rd sp.s. c 5 § 38]; ]

== 50A.50.060 - Benefits—Procedure.
. In any proceeding before an administrative law judge involving a dispute of an employee's initial determination, claim for waiting period credit or claim for benefits, all matters and provisions of this title relating to the employee's initial determination, or right to receive such credit or benefits for the period in question, shall be deemed to be in issue irrespective of the particular ground or grounds set forth in the notice of appeal in single employee cases.

. In any proceeding before an administrative law judge involving an employee's right to benefits, all parties shall be afforded an opportunity for hearing after not less than seven days' notice in accordance with RCW 34.05.434.

. In any proceeding involving an appeal relating to benefit determinations or benefit claims, the administrative law judge, after affording the parties reasonable opportunity for fair hearing, shall render its decision affirming, modifying, or setting aside the determination or decisions of the department. The parties shall be duly notified of such decision together with the reasons, which shall be deemed to be the final decision unless, within thirty days after the date of notification or mailing, whichever is the earlier, of such decision, further appeal is perfected pursuant to RCW 50A.50.080.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1399-S.SL.pdf?cite=2019%20c%2013%20§%2047[2019 c 13 § 47]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2702.SL.pdf?cite=2018%20c%20141%20§%204[2018 c 141 § 4]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2037[2017 3rd sp.s. c 5 § 37]; ]

== 50A.50.070 - Hearing procedures.
The manner in which any dispute is presented to the administrative law judge, and the conduct of hearings and appeals, shall be in accordance with rules adopted by the commissioner. A full and complete record shall be kept of all administrative law judge proceedings. All testimony at any appeal hearing shall be recorded, but need not be transcribed unless further appeal is taken.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2039[2017 3rd sp.s. c 5 § 39]; ]

== 50A.50.080 - Commissioner review—Initiation.
Within thirty days from the date of notification or mailing, whichever is the earlier, of any decision of an administrative law judge, the commissioner on the commissioner's own order may, or upon petition of any interested party shall, take jurisdiction of the proceedings for the purpose of review. Appeal from any decision of an administrative law judge may be perfected so as to prevent finality of such decision if, within thirty days from the date of notification or mailing of the decision, whichever is the earlier, a petition in writing for review by the commissioner is received by the commissioner or by such representative of the commissioner as the commissioner by rule shall prescribe. The commissioner may also prevent finality of any decision of an administrative law judge and take jurisdiction of the proceedings for his or her review by entering an order so providing on his or her own motion and mailing a copy thereof to the interested parties within the same period allowed for receipt of a petition for review. The time limit provided for the commissioner's assumption of jurisdiction on his or her own motion for review shall be deemed to be jurisdictional.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2040[2017 3rd sp.s. c 5 § 40]; ]

== 50A.50.090 - Commissioner review—Procedure.
After having acquired jurisdiction for review, the commissioner shall review the proceedings in question. Prior to rendering a decision, the commissioner may order the taking of additional evidence by an administrative law judge to be made a part of the record in the case. Upon the basis of evidence submitted to the administrative law judge and such additional evidence as the commissioner may order to be taken, the commissioner shall render a decision in writing affirming, modifying, or setting aside the decision of the administrative law judge. Alternatively, the commissioner may order further proceedings to be held before the administrative law judge, upon completion of which the administrative law judge shall issue a new decision in writing affirming, modifying, or setting aside the previous decision of the administrative law judge. The new decision of the administrative law judge may be appealed as provided under RCW 50A.50.080. The commissioner shall mail the decision of the commissioner to the interested parties at their last known addresses.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1399-S.SL.pdf?cite=2019%20c%2013%20§%2048[2019 c 13 § 48]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2702.SL.pdf?cite=2018%20c%20141%20§%205[2018 c 141 § 5]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2042[2017 3rd sp.s. c 5 § 42]; ]

== 50A.50.100 - Commissioner review—When final—Commissioner as party.
Any decision of the commissioner involving a review of an administrative law judge decision, in the absence of a petition as provided in chapter 34.05 RCW, becomes final thirty days after notification or mailing, whichever is earlier. The commissioner shall be deemed to be a party to any judicial action involving any such decision and shall be represented in any such judicial action by the attorney general.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2043[2017 3rd sp.s. c 5 § 43]; ]

== 50A.50.110 - Applicability of findings, determinations, etc. to other actions.
Any finding, determination, conclusion, declaration, or final order made by the commissioner, or his or her representative or delegate, or by an appeal tribunal, administrative law judge, reviewing officer, or other agent of the department for the purposes of this title, shall not be conclusive, nor binding, nor admissible as evidence in any separate action outside the scope of this title between an employee and the employee's present or prior employer before an arbitrator, court, or judge of this state or the United States, regardless of whether the prior action was between the same or related parties or involved the same facts or was reviewed pursuant to RCW 50A.50.140.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1399-S.SL.pdf?cite=2019%20c%2013%20§%2049[2019 c 13 § 49]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2048[2017 3rd sp.s. c 5 § 48]; ]

== 50A.50.120 - Waiver of time limitations.
For good cause shown the administrative law judge or the commissioner may waive the time limitations for administrative appeals or petitions set forth in this title.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1399-S.SL.pdf?cite=2019%20c%2013%20§%2050[2019 c 13 § 50]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2041[2017 3rd sp.s. c 5 § 41]; ]

== 50A.50.130 - Judicial review.
. In all court proceedings under or pursuant to this title the decision of the commissioner shall be prima facie correct, and the burden of proof shall be upon the party attacking the decision.

. If the court determines that the commissioner has acted within the commissioner's power and has correctly construed the law, the decision of the commissioner shall be confirmed; otherwise, the decision shall be reversed or modified. In case of a modification or reversal the superior court shall refer the decision to the commissioner with an order directing the commissioner to proceed in accordance with the findings of the court.

. Whenever any order and notice of assessment shall have become final in accordance with the provisions of this title, the court shall upon application of the commissioner enter a judgment in the amount provided for in the order and notice of assessment, and the judgment shall have and be given the same effect as if entered pursuant to a civil action instituted in the court.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1399-S.SL.pdf?cite=2019%20c%2013%20§%2051[2019 c 13 § 51]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2047[2017 3rd sp.s. c 5 § 47]; ]

== 50A.50.140 - Judicial review—Procedure.
Judicial review of a decision of the commissioner involving the review of a decision of an administrative law judge under this title may be had only in accordance with the procedural requirements of RCW 34.05.452.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1399-S.SL.pdf?cite=2019%20c%2013%20§%2052[2019 c 13 § 52]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2702.SL.pdf?cite=2018%20c%20141%20§%206[2018 c 141 § 6]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2044[2017 3rd sp.s. c 5 § 44]; ]

== 50A.50.150 - Judicial review—Bond—Stay.
. A bond of any kind shall not be required of any employee seeking judicial review from a commissioner's decision affecting such employee's application for initial determination or claim for waiting period credit or for benefits.

. A commissioner's decision shall not be stayed by a petition for judicial review unless the petitioning employer shall first deposit an undertaking in an amount deemed by the commissioner to be due, if any, from the petitioning employer, together with interest thereon, if any, with the commissioner or in the registry of the court.

. This section does not authorize a stay in the payment of benefits to an employee when such employee has been held entitled thereto by a decision of the commissioner which decision either affirms, reverses, or modifies a decision of an appeals tribunal.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2045[2017 3rd sp.s. c 5 § 45]; ]

== 50A.50.160 - Judicial review—Interstate petitions.
RCW 34.05.514 to the contrary notwithstanding, petitions to the superior court from decisions of the commissioner dealing with the applications or claims relating to benefit payments that were filed outside of this state with an authorized representative of the commissioner shall be filed with the superior court of Thurston county that shall have the original venue of such appeals.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2046[2017 3rd sp.s. c 5 § 46]; ]

== 50A.50.170 - Fees.
An individual shall not be charged fees of any kind in any proceeding involving the employee's application for initial determination, or claim for waiting period credit, or claim for benefits, under this title by the commissioner or his or her representatives, or by an appeal tribunal, or any court, or any officer thereof. Any employee in any such proceeding before the commissioner or any appeal tribunal may be represented by counsel or other duly authorized agent who shall neither charge nor receive a fee for such services in excess of an amount found reasonable by the officer conducting such proceeding.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1399-S.SL.pdf?cite=2019%20c%2013%20§%2053[2019 c 13 § 53]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2049[2017 3rd sp.s. c 5 § 49]; ]

== 50A.50.180 - Attorneys' fees—Court.
It shall be unlawful for any attorney engaged in any appeal to the courts on behalf of an employee involving the employee's application for initial determination or claim for benefits to charge or receive any fee in excess of a reasonable fee to be fixed by the superior court in respect to the services performed in connection with the appeal taken and to be fixed by the supreme court or the court of appeals in the event of appellate review, and if the decision of the commissioner shall be reversed or modified, such fee and the costs shall be payable out of the family and medical leave enforcement account.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2050[2017 3rd sp.s. c 5 § 50]; ]

== 50A.50.190 - Commissioner's expenses.
. Whenever any appeal is taken from any decision of the commissioner to any court, all expenses and costs incurred by the commissioner, including court reporter costs and attorneys' fees and all costs taxed against such commissioner, shall be paid out of the family and medical leave enforcement account.

. Neither the commissioner nor the state shall be charged any fee for any service rendered in connection with litigation under this title by the clerk of any court.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1399-S.SL.pdf?cite=2019%20c%2013%20§%2054[2019 c 13 § 54]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2052[2017 3rd sp.s. c 5 § 52]; ]

== 50A.50.200 - Remedies exclusive.
The remedies provided in this title for determining the justness or correctness of assessments, refunds, adjustments, or claims shall be exclusive and no court shall entertain any action to enjoin an assessment or require a refund or adjustment except in accordance with the provisions of this title. Matters which may be determined by the procedures set out in this title shall not be the subject of any declaratory judgment.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1399-S.SL.pdf?cite=2019%20c%2013%20§%2055[2019 c 13 § 55]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2051[2017 3rd sp.s. c 5 § 51]; ]

