= 50A.35 - Employment protections.
:toc:

== 50A.35.010 - Employment protection.
. Except as provided in RCW 50A.30.010(5) and subsection (6) of this section, any employee who takes family or medical leave under this title is entitled, on return from the leave:

.. To be restored by the employer to the position of employment held by the employee when the leave commenced; or

.. To be restored by the employer to an equivalent position with equivalent employment benefits, pay, and other terms and conditions of employment.

. The taking of leave under this title may not result in the loss of any employment benefits accrued before the date on which the leave commenced.

. Nothing in this section shall be construed to entitle any restored employee to:

.. The accrual of any seniority or employment benefits during any period of leave; or

.. Any right, benefit, or position of employment other than any right, benefit, or position to which the employee would have been entitled had the employee not taken the leave.

. As a condition of restoration under subsection (1) of this section for an employee who has taken medical leave, the employer may have a uniformly applied practice or policy that requires each such employee to receive certification from the employee's health care provider that the employee is able to resume work.

. Nothing in this section shall be construed to prohibit an employer from requiring an employee on leave to report periodically to the employer on the status and intention of the employee to return to work.

. [Empty]
.. This section does not apply unless the employee: (i) Works for an employer with fifty or more employees; (ii) has been employed by the current employer for twelve months or more; and (iii) has worked for the current employer for at least one thousand two hundred fifty hours during the twelve months immediately preceding the date on which leave will commence. For the purposes of this subsection, an employer shall be considered to employ fifty or more employees if the employer employs fifty or more employees for each working day during each of twenty or more calendar workweeks in the current or preceding calendar year.

.. An employer may deny restoration under this section to any salaried employee who is among the highest paid ten percent of the employees employed by the employer within seventy-five miles of the facility at which the employee is employed if:

... Denial is necessary to prevent substantial and grievous economic injury to the operations of the employer;

... The employer notifies the employee of the intent of the employer to deny restoration on such basis at the time the employer determines that the injury would occur; and

... The leave has commenced and the employee elects not to return to employment after receiving the notice.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1399-S.SL.pdf?cite=2019%20c%2013%20§%204[2019 c 13 § 4]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2031[2017 3rd sp.s. c 5 § 31]; ]

== 50A.35.020 - Continuation of health benefits.
If required by the federal family and medical leave act, as it existed on October 19, 2017, during any period of family or medical leave taken under this title, the employer shall maintain any existing health benefits of the employee in force for the duration of such leave as if the employee had continued to work from the date the employee commenced family or medical leave until the date the employee returns to employment. If the employer and employee share the cost of the existing health benefits, the employee remains responsible for the employee's share of the cost. This section does not apply to an employee who is not in employment for an employer at the time of filing an application for benefits.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1399-S.SL.pdf?cite=2019%20c%2013%20§%2039[2019 c 13 § 39]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2070[2017 3rd sp.s. c 5 § 70]; ]

== 50A.35.030 - Employer supplementation—Rights not subject to waiver or diminishment.
. Nothing in this title shall be construed to discourage employers from:

.. Adopting or retaining leave policies more generous than any policies that comply with the requirements under this title; or

.. Making supplemental benefit payments as provided under RCW 50A.15.060 to an employee on paid family or medical leave.

. Any agreement by an individual to waive, release, or commute his or her rights under this title is void as against public policy.

. After January 1, 2020, subject to RCW 50A.05.090, an employee's rights under this title may not be diminished by a collective bargaining agreement or employer policy.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1399-S.SL.pdf?cite=2019%20c%2013%20§%2042[2019 c 13 § 42]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2078[2017 3rd sp.s. c 5 § 78]; ]

