= 50A.40 - Unlawful acts.
:toc:

== 50A.40.010 - Employers.
. It is unlawful for any employer to:

.. Interfere with, restrain, or deny the exercise of, or the attempt to exercise, any valid right provided under this title; or

.. Discharge or in any other manner discriminate against any employee for opposing any practice made unlawful by this title.

. It is unlawful for any person to discharge or in any other manner discriminate against any employee because the employee has:

.. Filed any complaint, or has instituted or caused to be instituted any proceeding, under or related to this title;

.. Given, or is about to give, any information in connection with any inquiry or proceeding relating to any right provided under this title; or

.. Testified, or is about to testify, in any inquiry or proceeding relating to any right provided under this title.

. As provided in RCW 50A.40.020 and 50A.40.030, the department will investigate allegations of unlawful acts and determine damages, as necessary.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2614-S.SL.pdf?cite=2020%20c%20125%20§%2011[2020 c 125 § 11]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1399-S.SL.pdf?cite=2019%20c%2013%20§%2015[2019 c 13 § 15]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2072[2017 3rd sp.s. c 5 § 72]; ]

== 50A.40.020 - Employee complaints—Commissioner investigation, determination.
. An employee who alleges one or more unlawful acts under RCW 50A.40.010 have occurred may file a complaint with the department. The department may not investigate any alleged violation of RCW 50A.40.010 that occurred more than three years before the date the employee filed the complaint.

. Upon receipt of a complaint under subsection (1) of this section, the commissioner shall investigate to determine if a violation occurred and the amount of any liquidated damages, unless the employee terminates the complaint under *RCW 50A.40.035.

. Upon completing an investigation, the commissioner shall issue a determination, unless the complaint is otherwise resolved upon agreement by all parties and in compliance with *RCW 50A.40.035(6) or withdrawn under *RCW 50A.40.035(5). If the department determines a violation occurred, the department may order the employer to pay liquidated damages under RCW 50A.40.030.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2614-S.SL.pdf?cite=2020%20c%20125%20§%2012[2020 c 125 § 12]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1399-S.SL.pdf?cite=2019%20c%2013%20§%2017[2019 c 13 § 17]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2073[2017 3rd sp.s. c 5 § 73]; ]

== 50A.40.030 - Damages.
. Any employer who violates RCW 50A.40.010 is liable for damages.

. Damages are owed to the employee and must be paid by the employer to the employee directly.

. [Empty]
.. Damages include:

... Any wages, salary, employment benefits, or other compensation denied or lost to such employee by reason of the violation; or

... In a case in which wages, salary, employment benefits, or other compensation have not been denied or lost to the employee, any actual monetary losses sustained by the employee as a direct result of the violation, such as the cost of providing care, up to a sum equal to wages or salary for the employee for up to sixteen weeks, or eighteen weeks if the employee experiences a serious health condition with a pregnancy that results in incapacity.

.. Any employer who violates RCW 50A.40.010 is also liable for interest accrued on the damages assessed in this subsection.

. For a willful violation, the employer is also liable for an additional amount as liquidated damages equal to the sum of the amount described in subsection (3)(a) of this section and the interest described in subsection (3)(b) of this section. For purposes of this section, "willful" means a knowing and intentional action that is neither accidental nor the result of a bona fide dispute. All liquidated damages are owed to the employee and must be paid to the employee directly.

. Interest in this section is calculated at the prevailing rate.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2614-S.SL.pdf?cite=2020%20c%20125%20§%2013[2020 c 125 § 13]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1399-S.SL.pdf?cite=2019%20c%2013%20§%2018[2019 c 13 § 18]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2074[2017 3rd sp.s. c 5 § 74]; ]

== 50A.40.035 - Damages—Liquidated damages—Collection.
. If the department issues a determination under RCW 50A.40.020 that an employer owes liquidated damages, the employer must, within thirty calendar days, either pay all damages owed or file an appeal as provided in this title. Thereafter, all parties owed moneys may initiate collection action against the employer by filing a warrant with the clerk of any county within the state.

.. The warrant may include all damages awarded to the employee plus reasonable attorneys' fees for the collection action, reasonable expert witness fees, and other reasonable costs of the action.

.. For purposes of this section, thirty calendar days begins the day the determination is issued.

. The department is not responsible for collection action against an employer that has defaulted the payment of an award established under RCW 50A.40.030.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2614-S.SL.pdf?cite=2020%20c%20125%20§%2016[2020 c 125 § 16]; ]

== 50A.40.040 - Damages—Recovery—Private right of action—Complaint withdrawal, resolution—Termination of department's administrative action.
. A private action to recover damages under RCW 50A.40.030 may be brought against any employer by any one or more employees for and on behalf of:

.. The employee or employees; or

.. The employees and other employees similarly situated.

. Any action under subsection (1) of this section must be filed with a court of competent jurisdiction within the state. Any private action for an alleged violation of RCW 50A.40.010 must be commenced within three years of the date of the alleged violation.

. In an action under subsection (1) of this section the court shall, in addition to any judgment awarded to a prevailing plaintiff, award reasonable attorneys' fees, reasonable expert witness fees, and other costs of the action to be paid by the defendant.

. A private right of action is only available to an employee who either has not filed a complaint with the department, has withdrawn a filed complaint under subsection (5) of this section, or has resolved a complaint under subsection (6) of this section.

. An employee who has filed a complaint with the department under RCW 50A.40.020 may elect to withdraw the complaint by providing written notice to the department within ten business days after filing the complaint with the department. Withdrawing a complaint terminates the department's administrative action.

. A complaint may be resolved upon agreement by all parties. Resolution of a complaint must be communicated to the department prior to the department's issuance of a determination. Resolution of a complaint terminates the department's administrative action.

. In the event the department's administrative action is terminated under subsection (5) or (6) of this section:

.. The department will immediately discontinue its investigation and any action against the employer; and

.. The determination, if already issued, along with any related findings of fact and conclusions of law, and any payments or offers of payment made by the employer including interest, are not admissible in any court action or other judicial or administrative proceeding.

. Nothing in this section shall be construed to limit or affect:

.. Except as provided in subsection (4) of this section, the right of any employee to pursue any judicial, administrative, or other action available with respect to an employer;

.. The right of the department to pursue any judicial, administrative, or other action available with respect to an employee that is identified as a result of a complaint under RCW 50A.40.020; or

.. The right of the department to pursue any judicial, administrative, or other action available with respect to an employer in the absence of a complaint.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2614-S.SL.pdf?cite=2020%20c%20125%20§%2017[2020 c 125 § 17]; ]

