= 50A.24 - Small business assistance.
:toc:

== 50A.24.010 - Grants.
. The legislature recognizes that while family leave and medical leave benefit both employees and employers, there may be costs that disproportionately impact small businesses. To equitably balance the risks among employers, the legislature intends to assist small businesses with the costs of an employee's use of family or medical leave.

. Employers with one hundred fifty or fewer employees and employers with fifty or fewer employees who are assessed all premiums under RCW 50A.10.030(5)(b) may apply to the department for a grant under this section.

. [Empty]
.. An employer may receive a grant of three thousand dollars if the employer hires a temporary worker to replace an employee on family or medical leave for a period of seven days or more.

.. For an employee's family or medical leave, an employer may receive a grant of up to one thousand dollars as reimbursement for significant additional wage-related costs due to the employee's leave.

.. An employer may receive a grant under (a) or (b) of this subsection, but not both, except that an employer who received a grant under (b) of this subsection may receive a grant of the difference between the grant awarded under (b) of this subsection and three thousand dollars if the employee on leave extended the leave beyond the leave initially planned and the employer hired a temporary worker for the employee on leave.

. An employer may apply for a grant no more than ten times per calendar year and no more than once for each employee on leave.

. To be eligible for a grant, the employer must provide the department written documentation showing the temporary worker hired or significant wage-related costs incurred are due to an employee's use of family or medical leave.

. The department must assess an employer with fewer than fifty employees who receives a grant under this section for all premiums for three years from the date of receipt of a grant.

. The grants under this section shall be funded from the family and medical leave insurance account.

. The commissioner shall adopt rules as necessary to implement this section.

. For the purposes of this section, the number of employees must be calculated as provided in RCW 50A.10.030.

. An employer who has an approved voluntary plan is not eligible to receive a grant under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1399-S.SL.pdf?cite=2019%20c%2013%20ยง%2036[2019 c 13 ยง 36]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20ยง%2084[2017 3rd sp.s. c 5 ยง 84]; ]

