= 50A.10 - Premiums.
:toc:

== 50A.10.010 - Elective coverage—Self-employed.
. For benefits payable beginning January 1, 2020, any self-employed person, including a sole proprietor, independent contractor, partner, or joint venturer, may elect coverage under this title for an initial period of not less than three years and subsequent periods of not less than one year immediately following a period of coverage. Those electing coverage under this section must elect coverage for both family leave and medical leave and are responsible for payment of one hundred percent of all premiums assessed to an employee under RCW 50A.10.030. The self-employed person must file a notice of election in writing with the department, in a manner as required by the department in rule. The self-employed person is eligible for family and medical leave benefits after working eight hundred twenty hours in the state during the qualifying period following the date of filing the notice.

. A self-employed person who has elected coverage may withdraw from coverage within thirty days after the end of each period of coverage, or at such other times as the commissioner may adopt by rule, by filing a notice of withdrawal in writing with the commissioner, such withdrawal to take effect not sooner than thirty days after filing the notice with the commissioner.

. The department may cancel elective coverage if the self-employed person fails to make required payments or file reports. The department may collect due and unpaid premiums and may levy an additional premium for the remainder of the period of coverage. The cancellation shall be effective no later than thirty days from the date of the notice in writing advising the self-employed person of the cancellation.

. Those electing coverage are considered employers or employees where the context so dictates.

. For the purposes of this section, "independent contractor" means an individual excluded from employment under RCW 50A.05.010(8)(b) (iii) and (iv).

. In developing and implementing the requirements of this section, the department shall adopt government efficiencies to improve administration and reduce costs. These efficiencies may include, but are not limited to, requiring that payments be made in a manner and at intervals unique to the elective coverage program.

. The department shall adopt rules for determining the hours worked and the wages of individuals who elect coverage under this section and rules for enforcement of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2614-S.SL.pdf?cite=2020%20c%20125%20§%202[2020 c 125 § 2]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1399-S.SL.pdf?cite=2019%20c%2013%20§%2019[2019 c 13 § 19]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2010[2017 3rd sp.s. c 5 § 10]; ]

== 50A.10.020 - Elective coverage—Tribes.
A federally recognized tribe may elect coverage under RCW 50A.10.010. The department shall adopt rules to implement this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1399-S.SL.pdf?cite=2019%20c%2013%20§%2020[2019 c 13 § 20]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2702.SL.pdf?cite=2018%20c%20141%20§%202[2018 c 141 § 2]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2011[2017 3rd sp.s. c 5 § 11]; ]

== 50A.10.030 - Premiums—Solvency surcharge—Limitation on local regulation.
. [Empty]
.. Beginning January 1, 2019, the department shall assess for each individual in employment with an employer and for each individual electing coverage a premium based on the amount of the individual's wages subject to subsection (4) of this section.

.. The premium rate for family leave benefits shall be equal to one-third of the total premium rate.

.. The premium rate for medical leave benefits shall be equal to two-thirds of the total premium rate.

. For calendar year 2022 and thereafter, the commissioner shall determine the percentage of paid claims related to family leave benefits and the percentage of paid claims related to medical leave benefits and adjust the premium rates set in subsection (1)(b) and (c) of this section by the proportional share of paid claims.

. [Empty]
.. Beginning January 1, 2019, and ending December 31, 2020, the total premium rate shall be four-tenths of one percent of the individual's wages subject to subsection (4) of this section.

.. For family leave premiums, an employer may deduct from the wages of each employee up to the full amount of the premium required.

.. For medical leave premiums, an employer may deduct from the wages of each employee up to forty-five percent of the full amount of the premium required.

.. An employer may elect to pay all or any portion of the employee's share of the premium for family leave or medical leave benefits, or both.

. The commissioner must annually set a maximum limit on the amount of wages that is subject to a premium assessment under this section that is equal to the maximum wages subject to taxation for social security as determined by the social security administration.

. [Empty]
.. Employers with fewer than fifty employees employed in the state are not required to pay the employer portion of premiums for family and medical leave.

.. If an employer with fewer than fifty employees elects to pay the premiums, the employer is then eligible for assistance under RCW 50A.24.010.

. For calendar year 2021 and thereafter, the total premium rate shall be based on the family and medical leave insurance account balance ratio as of September 30th of the previous year. The commissioner shall calculate the account balance ratio by dividing the balance of the family and medical leave insurance account by total covered wages paid by employers and those electing coverage. The division shall be carried to the fourth decimal place with the remaining fraction disregarded unless it amounts to five hundred-thousandths or more, in which case the fourth decimal place shall be rounded to the next higher digit. If the account balance ratio is:

.. Zero to nine hundredths of one percent, the premium is six tenths of one percent of the individual's wages;

.. One tenth of one percent to nineteen hundredths of one percent, the premium is five tenths of one percent of the individual's wages;

.. Two tenths of one percent to twenty-nine hundredths of one percent, the premium is four tenths of one percent of the individual's wages;

.. Three tenths of one percent to thirty-nine hundredths of one percent, the premium is three tenths of one percent of the individual's wages;

.. Four tenths of one percent to forty-nine hundredths of one percent, the premium is two tenths of one percent of the individual's wages; or

.. Five tenths of one percent or greater, the premium is one tenth of one percent of the individual's wages.

. Beginning January 1, 2021, if the account balance ratio calculated in subsection (6) of this section is below five hundredths of one percent, the commissioner must assess a solvency surcharge at the lowest rate necessary to provide revenue to pay for the administrative and benefit costs of family and medical leave, for the calendar year, as determined by the commissioner. The solvency surcharge shall be at least one-tenth of one percent and no more than six-tenths of one percent and be added to the total premium rate for family and medical leave benefits.

. [Empty]
.. The employer must collect from the employees the premiums and any surcharges provided under this section through payroll deductions and remit the amounts collected to the department.

.. In collecting employee premiums through payroll deductions, the employer shall act as the agent of the employees and shall remit the amounts to the department as required by this title.

.. On September 30th of each year, the department shall average the number of employees reported by an employer over the last four completed calendar quarters to determine the size of the employer for the next calendar year for the purposes of this section and RCW 50A.24.010.

. Premiums shall be collected in the manner and at such intervals as provided in this title and directed by the department.

. Premiums collected under this section are placed in trust for the employees and employers that the program is intended to assist.

. A city, code city, town, county, or political subdivision may not enact a charter, ordinance, regulation, rule, or resolution:

.. Creating a paid family or medical leave insurance program that alters or amends the requirements of this title for any private employer;

.. Providing for local enforcement of the provisions of this title; or

.. Requiring private employers to supplement duration of leave or amount of wage replacement benefits provided under this title.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1399-S.SL.pdf?cite=2019%20c%2013%20§%2021[2019 c 13 § 21]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%208[2017 3rd sp.s. c 5 § 8]; ]

== 50A.10.040 - Out-of-state employees—Premium waiver.
. An employer may file an application with the department for a conditional waiver for the payment of family and medical leave premiums, assessed under RCW 50A.10.030, for any employee who:

.. Primarily performs work outside of the state;

.. Is employed in the state on a limited or temporary work schedule; and

.. Is not expected to be employed in the state for eight hundred twenty hours or more in a period of four consecutive completed calendar quarters.

. Both the employee and employer must sign the application verifying their belief that the conditions in subsection (1) of this section will be met.

. If the department finds any of the conditions in subsection (1) of this section are no longer satisfied, or were not satisfied at any point after a conditional waiver was approved and is in effect, the department will consider the conditional waiver expired and the employer and employee will be responsible for their shares of all premiums that would have been paid during this period had the waiver not been granted. Upon payment of the missed premiums, the employee will be credited for the hours worked and will be eligible for benefits under this title as if the premiums were originally paid.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2614-S.SL.pdf?cite=2020%20c%20125%20§%203[2020 c 125 § 3]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1399-S.SL.pdf?cite=2019%20c%2013%20§%2022[2019 c 13 § 22]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%209[2017 3rd sp.s. c 5 § 9]; ]

== 50A.10.050 - Termination or disposal of business—Premium payment—Successor liability.
Whenever any employer quits business, or sells out, exchanges, or otherwise disposes of the employer's business or stock of goods, any premiums payable under this title shall become immediately due and payable, and the employer shall, within ten days, make a return and pay the premiums due; and any person who becomes a successor to such business shall become liable for the full amount of the premiums and withhold from the purchase price a sum sufficient to pay any premiums due from the employer until such time as the employer produces a receipt from the employment security department showing payment in full of any premiums due or a certificate that no premium is due and, if such premium is not paid by the employer within ten days from the date of such sale, exchange, or disposal, the successor shall become liable for the payment of the full amount of premiums, and the payment thereof by such successor shall, to the extent thereof, be deemed a payment upon the purchase price, and if such payment is greater in amount than the purchase price the amount of the difference shall become a debt due such successor from the employer. A successor may not be liable for any premiums due from the person from whom that person has acquired a business or stock of goods if that person gives written notice to the employment security department of such acquisition and no assessment is issued by the department within one hundred eighty days of receipt of such notice against the former operator of the business and a copy thereof mailed to such successor.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1399-S.SL.pdf?cite=2019%20c%2013%20§%2023[2019 c 13 § 23]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2067[2017 3rd sp.s. c 5 § 67]; ]

