= 48.25A - Life insurance—Profit-sharing, charter, founders, and coupon policies.
:toc:

== 48.25A.010 - Definitions.
As used in this chapter:

. "Profit-sharing policy" means:

.. A life insurance policy which by its terms expressly provides that the policyholder will participate in the distribution of earnings or surplus other than earnings or surplus attributable, by reasonable and nondiscriminatory standards, to the participating policies of the company and allocated to the policyholder on reasonable and nondiscriminatory standards; or

.. A life insurance policy the provisions of which, through sales material or oral presentations, are interpreted by the company to prospective policyholders as entitling the policyholder to the benefits described in subsection (a) of this section.

. "Charter policy" or "founders policy" means:

.. A life insurance policy which by its terms expressly provides that the policyholder will receive some preferential or discriminatory advantage or benefit not available to persons who purchase insurance from the company at future dates or under other circumstances; or

.. A life insurance policy the provisions of which, through sales material or oral presentations, are interpreted by the company to prospective policyholders as entitling the policyholder to the benefits described in subsection (a) of this section.

. "Coupon policy" means a life insurance policy which provides a series of pure endowments maturing periodically in amounts not exceeding the gross annual policy premiums. The term "pure endowment" or "endowment" is used in its accepted actuarial sense, meaning a benefit becoming payable at a specific future date if the insured person is then living.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c95.pdf?cite=1967%20ex.s.%20c%2095%20§%205[1967 ex.s. c 95 § 5]; ]

== 48.25A.020 - Certain policies not to be issued or delivered after September 1, 1967.
No profit-sharing, charter, or founders policy shall be issued or delivered in this state after September 1, 1967.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c95.pdf?cite=1967%20ex.s.%20c%2095%20§%206[1967 ex.s. c 95 § 6]; ]

== 48.25A.030 - Coupon policies—Approval by commissioner.
No coupon policy shall be issued or delivered in this state until the form of the same has been filed with and approved by the commissioner.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c95.pdf?cite=1967%20ex.s.%20c%2095%20§%207[1967 ex.s. c 95 § 7]; ]

== 48.25A.040 - Coupon policies—Requirements.
Coupon policies issued or delivered in this state shall be subject to the following provisions:

. No detachable coupons or certificates or passbooks may be used. No other device may be used which tends to emphasize the periodic endowment benefits or which tends to create the impression that the endowments represent interest earnings or anything other than benefits which have been purchased by part of the policyholder's premium payments.

. Each endowment benefit must have a fixed maturity date and payment of the endowment benefit shall not be contingent upon the payment of any premium becoming due on or after such maturity date.

. The endowment benefits must be expressed in dollar amounts rather than as percentages of other quantities or in other ways, both in the policy itself and in the sale thereof.

. A separate premium for the periodic endowment benefits must be shown in the policy adjacent to the rest of the policy premium information and must be given the same emphasis in the policy and in the sale thereof as that given the rest of the policy premium information. This premium shall be calculated with mortality, interest and expense factors which are consistent with those for the basic policy premium.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c95.pdf?cite=1967%20ex.s.%20c%2095%20§%208[1967 ex.s. c 95 § 8]; ]

== 48.25A.050 - Revocation of certificates of authority and licenses for violation of chapter.
The commissioner may revoke all certificates of authority and licenses granted to any insurance company, its officers or agents violating any provision of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c95.pdf?cite=1967%20ex.s.%20c%2095%20§%209[1967 ex.s. c 95 § 9]; ]

