= 48.94 - Reinsurance intermediary act.
:toc:

== 48.94.005 - Definitions.
The definitions set forth in this section apply throughout this chapter:

. "Actuary" means a person who is a member in good standing of the American academy of actuaries.

. "Controlling person" means a person, firm, association, or corporation who directly or indirectly has the power to direct or cause to be directed, the management, control, or activities of the reinsurance intermediary.

. "Insurer" means insurer as defined in RCW 48.01.050.

. "Licensed producer" means an insurance producer or reinsurance intermediary licensed under the applicable provisions of this title.

. "Reinsurance intermediary" means a reinsurance intermediary-broker or a reinsurance intermediary-manager as these terms are defined in subsections (6) and (7) of this section.

. "Reinsurance intermediary-broker" means a person, other than an officer or employee of the ceding insurer, firm, association, or corporation who solicits, negotiates, or places reinsurance cessions or retrocessions on behalf of a ceding insurer without the authority or power to bind reinsurance on behalf of the insurer.

. "Reinsurance intermediary-manager" means a person, firm, association, or corporation who has authority to bind or manages all or part of the assumed reinsurance business of a reinsurer, including the management of a separate division, department, or underwriting office, and acts as an insurance producer for the reinsurer whether known as a reinsurance intermediary-manager, manager, or other similar term. Notwithstanding this subsection, the following persons are not considered a reinsurance intermediary-manager, with respect to such reinsurer, for the purposes of this chapter:

.. An employee of the reinsurer;

.. A United States manager of the United States branch of an alien reinsurer;

.. An underwriting manager who, pursuant to contract, manages all the reinsurance operations of the reinsurer, is under common control with the reinsurer, subject to the insurer holding company act, chapter 48.31B RCW, and whose compensation is not based on the volume of premiums written;

.. The manager of a group, association, pool, or organization of insurers that engages in joint underwriting or joint reinsurance and that are subject to examination by the insurance commissioner of the state in which the manager's principal business office is located.

. "Reinsurer" means a person, firm, association, or corporation licensed in this state under this title as an insurer with the authority to assume reinsurance.

. "To be in violation" means that the reinsurance intermediary, insurer, or reinsurer for whom the reinsurance intermediary was acting failed to substantially comply with this chapter.

. "Qualified United States financial institution" means an institution that:

.. Is organized or, in the case of a United States office of a foreign banking organization, licensed, under the laws of the United States or any state thereof;

.. Is regulated, supervised, and examined by United States federal or state authorities having regulatory authority over banks and trust companies; and

.. Has been determined by either the commissioner, or the securities valuation office of the National Association of Insurance Commissioners, to meet such standards of financial condition and standing as are considered necessary and appropriate to regulate the quality of financial institutions whose letters of credit will be acceptable to the commissioner.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6591.SL.pdf?cite=2008%20c%20217%20§%2073[2008 c 217 § 73]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1855-S.SL.pdf?cite=1993%20c%20462%20§%2023[1993 c 462 § 23]; ]

== 48.94.010 - Acting as a reinsurance intermediary-broker or reinsurance intermediary-manager—Commissioner's powers—Licenses—Attorney exemption.
. No person, firm, association, or corporation may act as a reinsurance intermediary-broker in this state if the person, firm, association, or corporation maintains an office either directly or as a member or employee of a firm or association, or an officer, director, or employee of a corporation:

.. In this state, unless the person, firm, association, or corporation is a licensed reinsurance intermediary-broker in this state; or

.. In another state, unless the person, firm, association, or corporation is a licensed reinsurance intermediary-broker in this state or another state having a regulatory scheme substantially similar to this chapter.

. No person, firm, association, or corporation may act as a reinsurance intermediary-manager:

.. For a reinsurer domiciled in this state, unless the person, firm, association, or corporation is a licensed reinsurance intermediary-manager in this state;

.. In this state, if the person, firm, association, or corporation maintains an office either directly or as a member or employee of a firm or association, or an officer, director, or employee of a corporation in this state, unless the person, firm, association, or corporation is a licensed reinsurance intermediary-manager in this state;

.. In another state for a nondomestic reinsurer, unless the person, firm, association, or corporation is a licensed reinsurance intermediary-manager in this state or another state having a substantially similar regulatory scheme.

. The commissioner may require a reinsurance intermediary-manager subject to subsection (2) of this section to:

.. File a bond in an amount and from an insurer acceptable to the commissioner for the protection of the reinsurer; and

.. Maintain an errors and omissions policy in an amount acceptable to the commissioner.

. The commissioner may issue a reinsurance intermediary license to a person, firm, association, or corporation who has complied with the requirements of this chapter. Any such license issued to a firm or association authorizes all the members of the firm or association and any designated employees to act as reinsurance intermediaries under the license, and all such persons may be named in the application and any supplements to it. Any such license issued to a corporation authorizes all of the officers, and any designated employees and directors of it, to act as reinsurance intermediaries on behalf of the corporation, and all such persons must be named in the application and any supplements to it.

. [Empty]
.. Each licensed nonresident reinsurance intermediary must appoint the commissioner as the reinsurance intermediary's attorney to receive service of legal process issued against the reinsurance intermediary in this state upon causes of action arising within this state. Service upon the commissioner as attorney constitutes effective legal service upon the reinsurance intermediary.

.. With the appointment the reinsurance intermediary must designate the person to whom the commissioner must forward legal process so served upon him or her.

.. The appointment is irrevocable, binds any successor in interest or to the assets or liabilities of the reinsurance intermediary, and remains in effect for as long as there could be any cause of action against the reinsurance intermediary arising out of the reinsurance intermediary's insurance transactions in this state.

.. The service of process must be accomplished and processed in the manner prescribed under RCW 48.02.200.

. The commissioner may refuse to issue a reinsurance intermediary license if, in his or her judgment, the applicant, anyone named on the application, or a member, principal, officer, or director of the applicant, is not trustworthy, or that a controlling person of the applicant is not trustworthy to act as a reinsurance intermediary, or that any of the foregoing has given cause for revocation or suspension of the license, or has failed to comply with a prerequisite for the issuance of such license. Upon written request, the commissioner will furnish a summary of the basis for refusal to issue a license, which document is privileged and not subject to chapter 42.56 RCW.

. Licensed attorneys-at-law of this state when acting in their professional capacity as such are exempt from this section.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5213.SL.pdf?cite=2011%20c%2047%20§%2013[2011 c 47 § 13]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20317[2005 c 274 § 317]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1855-S.SL.pdf?cite=1993%20c%20462%20§%2024[1993 c 462 § 24]; ]

== 48.94.015 - Written authorization required between a reinsurance intermediary-broker and an insurer—Minimum provisions.
Brokers transactions between a reinsurance intermediary-broker and the insurer it represents in such capacity may be entered into only under a written authorization, specifying the responsibilities of each party. The authorization must, at a minimum, provide that:

. The insurer may terminate the reinsurance intermediary-broker's authority at any time.

. The reinsurance intermediary-broker shall render accounts to the insurer accurately detailing all material transactions, including information necessary to support all commissions, charges, and other fees received by, or owing, to the reinsurance intermediary-broker, and remit all funds due to the insurer within thirty days of receipt.

. All funds collected for the insurer's account must be held by the reinsurance intermediary-broker in a fiduciary capacity in a bank that is a qualified United States financial institution as defined in this chapter.

. The reinsurance intermediary-broker will comply with RCW 48.94.020.

. The reinsurance intermediary-broker will comply with the written standards established by the insurer for the cession or retrocession of all risks.

. The reinsurance intermediary-broker will disclose to the insurer any relationship with any reinsurer to which business will be ceded or retroceded.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1855-S.SL.pdf?cite=1993%20c%20462%20§%2025[1993 c 462 § 25]; ]

== 48.94.020 - Accounts and records maintained by reinsurance intermediary-broker—Access by insurer.
. For at least ten years after expiration of each contract of reinsurance transacted by the reinsurance intermediary-broker, the reinsurance intermediary-broker shall keep a complete record for each transaction showing:

.. The type of contract, limits, underwriting restrictions, classes, or risks and territory;

.. Period of coverage, including effective and expiration dates, cancellation provisions, and notice required of cancellation;

.. Reporting and settlement requirements of balances;

.. Rate used to compute the reinsurance premium;

.. Names and addresses of assuming reinsurers;

.. Rates of all reinsurance commissions, including the commissions on any retrocessions handled by the reinsurance intermediary-broker;

.. Related correspondence and memoranda;

.. Proof of placement;

.. Details regarding retrocessions handled by the reinsurance intermediary-broker including the identity of retrocessionaires and percentage of each contract assumed or ceded;

.. Financial records, including but not limited to, premium and loss accounts; and

.. When the reinsurance intermediary-broker procures a reinsurance contract on behalf of a licensed ceding insurer:

... Directly from any assuming reinsurer, written evidence that the assuming reinsurer has agreed to assume the risk; or

... If placed through a representative of the assuming reinsurer, other than an employee, written evidence that the reinsurer has delegated binding authority to the representative.

. The insurer has access and the right to copy and audit all accounts and records maintained by the reinsurance intermediary-broker related to its business in a form usable by the insurer.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1855-S.SL.pdf?cite=1993%20c%20462%20§%2026[1993 c 462 § 26]; ]

== 48.94.025 - Restrictions on insurer—Obtaining services—Employees—Financial condition of reinsurance intermediary.
. An insurer may not engage the services of a person, firm, association, or corporation to act as a reinsurance intermediary-broker on its behalf unless the person is licensed as required by RCW 48.94.010(1).

. An insurer may not employ an individual who is employed by a reinsurance intermediary-broker with which it transacts business, unless the reinsurance intermediary-broker is under common control with the insurer and subject to the insurer holding company act, chapter 48.31B RCW.

. The insurer shall annually obtain a copy of statements of the financial condition of each reinsurance intermediary-broker with which it transacts business.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1855-S.SL.pdf?cite=1993%20c%20462%20§%2027[1993 c 462 § 27]; ]

== 48.94.030 - Contract required between a reinsurance intermediary-manager and a reinsurer—Minimum provisions.
Transactions between a reinsurance intermediary-manager and the reinsurer it represents in such capacity may be entered into only under a written contract, specifying the responsibilities of each party, which shall be approved by the reinsurer's board of directors. At least thirty days before the reinsurer assumes or cedes business through the reinsurance intermediary-manager, a true copy of the approved contract must be filed with the commissioner for approval. The contract must, at a minimum, provide that:

. The reinsurer may terminate the contract for cause upon written notice to the reinsurance intermediary-manager. The reinsurer may immediately suspend the authority of the reinsurance intermediary-manager to assume or cede business during the pendency of a dispute regarding the cause for termination.

. The reinsurance intermediary-manager shall render accounts to the reinsurer accurately detailing all material transactions, including information necessary to support all commissions, charges, and other fees received by, or owing to, the reinsurance intermediary-manager, and remit all funds due under the contract to the reinsurer on not less than a monthly basis.

. All funds collected for the reinsurer's account must be held by the reinsurance intermediary-manager in a fiduciary capacity in a bank that is a qualified United States financial institution. The reinsurance intermediary-manager may retain no more than three months' estimated claims payments and allocated loss adjustment expenses. The reinsurance intermediary-manager shall maintain a separate bank account for each reinsurer that it represents.

. For at least ten years after expiration of each contract of reinsurance transacted by the reinsurance intermediary-manager, the reinsurance intermediary-manager shall keep a complete record for each transaction showing:

.. The type of contract, limits, underwriting restrictions, classes, or risks and territory;

.. Period of coverage, including effective and expiration dates, cancellation provisions, and notice required of cancellation, and disposition of outstanding reserves on covered risks;

.. Reporting and settlement requirements of balances;

.. Rate used to compute the reinsurance premium;

.. Names and addresses of reinsurers;

.. Rates of all reinsurance commissions, including the commissions on any retrocessions handled by the reinsurance intermediary-manager;

.. Related correspondence and memoranda;

.. Proof of placement;

.. Details regarding retrocessions handled by the reinsurance intermediary-manager, as permitted by RCW 48.94.040(4), including the identity of retrocessionaires and percentage of each contract assumed or ceded;

.. Financial records, including but not limited to, premium and loss accounts; and

.. When the reinsurance intermediary-manager places a reinsurance contract on behalf of a ceding insurer:

... Directly from an assuming reinsurer, written evidence that the assuming reinsurer has agreed to assume the risk; or

... If placed through a representative of the assuming reinsurer, other than an employee, written evidence that the reinsurer has delegated binding authority to the representative.

. The reinsurer has access and the right to copy all accounts and records maintained by the reinsurance intermediary-manager related to its business in a form usable by the reinsurer.

. The reinsurance intermediary-manager may not assign the contract in whole or in part.

. The reinsurance intermediary-manager shall comply with the written underwriting and rating standards established by the insurer for the acceptance, rejection, or cession of all risks.

. The rates, terms, and purposes of commissions, charges, and other fees that the reinsurance intermediary-manager may levy against the reinsurer are clearly specified.

. If the contract permits the reinsurance intermediary-manager to settle claims on behalf of the reinsurer:

.. All claims will be reported to the reinsurer in a timely manner;

.. A copy of the claim file will be sent to the reinsurer at its request or as soon as it becomes known that the claim:

... Has the potential to exceed the lesser of an amount determined by the commissioner or the limit set by the reinsurer;

... Involves a coverage dispute;

... May exceed the reinsurance intermediary-manager's claims settlement authority;

... Is open for more than six months; or

.. Is closed by payment of the lesser of an amount set by the commissioner or an amount set by the reinsurer;

.. All claim files are the joint property of the reinsurer and reinsurance intermediary-manager. However, upon an order of liquidation of the reinsurer, the files become the sole property of the reinsurer or its estate; the reinsurance intermediary-manager has reasonable access to and the right to copy the files on a timely basis;

.. Settlement authority granted to the reinsurance intermediary-manager may be terminated for cause upon the reinsurer's written notice to the reinsurance intermediary-manager or upon the termination of the contract. The reinsurer may suspend the settlement authority during the pendency of a dispute regarding the cause of termination.

. If the contract provides for a sharing of interim profits by the reinsurance intermediary-manager, such interim profits will not be paid until one year after the end of each underwriting period for property business and five years after the end of each underwriting period for casualty business, or a later period set by the commissioner for specified lines of insurance, and not until the adequacy of reserves on remaining claims has been verified under RCW 48.94.040(3).

. The reinsurance intermediary-manager shall annually provide the reinsurer with a statement of its financial condition prepared by an independent certified accountant.

. The reinsurer shall periodically, at least semiannually, conduct an on-site review of the underwriting and claims processing operations of the reinsurance intermediary-manager.

. The reinsurance intermediary-manager shall disclose to the reinsurer any relationship it has with an insurer before ceding or assuming any business with the insurer under this contract.

. Within the scope of its actual or apparent authority the acts of the reinsurance intermediary-manager are deemed to be the acts of the reinsurer on whose behalf it is acting.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1855-S.SL.pdf?cite=1993%20c%20462%20§%2028[1993 c 462 § 28]; ]

== 48.94.035 - Restrictions on reinsurance intermediary-manager—Retrocessions—Syndicates—Licenses—Employees.
The reinsurance intermediary-manager may not:

. Cede retrocessions on behalf of the reinsurer, except that the reinsurance intermediary-manager may cede facultative retrocessions under obligatory automatic agreements if the contract with the reinsurer contains reinsurance underwriting guidelines for the retrocessions. The guidelines must include a list of reinsurers with which the automatic agreements are in effect, and for each such reinsurer, the coverages and amounts or percentages that may be reinsured, and commission schedules.

. Commit the reinsurer to participate in reinsurance syndicates.

. Appoint a reinsurance intermediary without assuring that the reinsurance intermediary is lawfully licensed to transact the type of reinsurance for which he or she is appointed.

. Without prior approval of the reinsurer, pay or commit the reinsurer to pay a claim, net of retrocessions, that exceeds the lesser of an amount specified by the reinsurer or one percent of the reinsurer's policyholder's surplus as of December 31st of the last complete calendar year.

. Collect a payment from a retrocessionaire or commit the reinsurer to a claim settlement with a retrocessionaire, without prior approval of the reinsurer. If prior approval is given, a report must be promptly forwarded to the reinsurer.

. Jointly employ an individual who is employed by the reinsurer unless the reinsurance intermediary-manager is under common control with the reinsurer subject to the insurer holding company act, chapter 48.31B RCW.

. Appoint a subreinsurance intermediary-manager.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1855-S.SL.pdf?cite=1993%20c%20462%20§%2029[1993 c 462 § 29]; ]

== 48.94.040 - Restrictions on reinsurer—Financial condition of reinsurance intermediary-manager—Loss reserves—Retrocessions—Termination of contract—Board of directors.
. A reinsurer may not engage the services of a person, firm, association, or corporation to act as a reinsurance intermediary-manager on its behalf unless the person is licensed as required by RCW 48.94.010(2).

. The reinsurer shall annually obtain a copy of statements of the financial condition of each reinsurance intermediary-manager that the reinsurer has had prepared by an independent certified accountant in a form acceptable to the commissioner.

. If a reinsurance intermediary-manager establishes loss reserves, the reinsurer shall annually obtain the opinion of an actuary attesting to the adequacy of loss reserves established for losses incurred and outstanding on business produced by the reinsurance intermediary-manager. This opinion is in addition to any other required loss reserve certification.

. Binding authority for all retrocessional contracts or participation in reinsurance syndicates must rest with an officer of the reinsurer who is not affiliated with the reinsurance intermediary-manager.

. Within thirty days of termination of a contract with a reinsurance intermediary-manager, the reinsurer shall provide written notification of the termination to the commissioner.

. A reinsurer may not appoint to its board of directors an officer, director, employee, controlling shareholder, or subproducer of its reinsurance intermediary-manager. This subsection does not apply to relationships governed by the insurer holding company act, chapter 48.31B RCW, or, if applicable, the producer-controlled property and casualty insurer act, chapter 48.97 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6591.SL.pdf?cite=2008%20c%20217%20§%2074[2008 c 217 § 74]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1855-S.SL.pdf?cite=1993%20c%20462%20§%2030[1993 c 462 § 30]; ]

== 48.94.045 - Examination by commissioner.
. A reinsurance intermediary is subject to examination by the commissioner. The commissioner has access to all books, bank accounts, and records of the reinsurance intermediary in a form usable to the commissioner.

. A reinsurance intermediary-manager may be examined as if it were the reinsurer.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1855-S.SL.pdf?cite=1993%20c%20462%20§%2031[1993 c 462 § 31]; ]

== 48.94.050 - Violations of chapter—Penalties—Judicial review.
. A reinsurance intermediary, insurer, or reinsurer found by the commissioner, after a hearing conducted in accordance with chapters 48.17 and 34.05 RCW, to be in violation of any provision of this chapter, shall:

.. For each separate violation, pay a penalty in an amount not exceeding five thousand dollars;

.. Be subject to revocation or suspension of its license; and

.. If a violation was committed by the reinsurance intermediary, make restitution to the insurer, reinsurer, rehabilitator, or liquidator of the insurer or reinsurer for the net losses incurred by the insurer or reinsurer attributable to the violation.

. The decision, determination, or order of the commissioner under subsection (1) of this section is subject to judicial review under this title and chapter 34.05 RCW.

. Nothing contained in this section affects the right of the commissioner to impose any other penalties provided in this title.

. Nothing contained in this chapter is intended to or in any manner limits or restricts the rights of policyholders, claimants, creditors, or other third parties or confer any rights to those persons.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1855-S.SL.pdf?cite=1993%20c%20462%20§%2032[1993 c 462 § 32]; ]

== 48.94.055 - Rule making.
The commissioner may adopt reasonable rules for the implementation and administration of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1855-S.SL.pdf?cite=1993%20c%20462%20§%2033[1993 c 462 § 33]; ]

== 48.94.900 - Short title.
This chapter may be known and cited as the reinsurance intermediary act.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1855-S.SL.pdf?cite=1993%20c%20462%20§%2022[1993 c 462 § 22]; ]

== 48.94.901 - Severability—Implementation—1993 c 462.
See RCW 48.31B.901 and 48.31B.902.

[ ]

