= 48.11 - Insuring powers.
:toc:

== 48.11.020 - "Life insurance" defined.
"Life insurance" is insurance on human lives and insurances appertaining thereto or connected therewith. For the purposes of this code the transacting of life insurance includes the granting of annuities and endowment benefits; additional benefits in event of death by accident; additional benefits in event of the total and permanent disability of the insured; and optional modes of settlement of proceeds.

[ 1947 c 79 § .11.02; Rem. Supp. 1947 § 45.11.02; ]

== 48.11.030 - "Disability insurance" defined—"Stop loss insurance" defined.
"Disability insurance" is insurance against bodily injury, disablement or death by accident, against disablement resulting from sickness, and every insurance appertaining thereto including stop loss insurance. "Stop loss insurance" is insurance against the risk of economic loss assumed under a self-funded employee disability benefit plan.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6193-S.SL.pdf?cite=1992%20c%20226%20§%201[1992 c 226 § 1]; 1947 c 79 § .11.03; Rem. Supp. 1947 § 45.11.03; ]

== 48.11.040 - "Property insurance" defined.
"Property insurance" is insurance against loss of or damage to real or personal property of every kind and any interest therein, from any or all hazard or cause, and against loss consequential upon such loss or damage.

[ 1947 c 79 § .11.04; Rem. Supp. 1947 § 45.11.04; ]

== 48.11.050 - "Marine and transportation insurance" defined.
"Marine and transportation insurance" is:

. Insurance against loss of or damage to:

.. Vessels, craft, aircraft, vehicles, goods, freights, cargoes, merchandise, effects, disbursements, profits, moneys, securities, choses in action, evidences of debt, valuable papers, bottomry, and respondentia interests and all other kinds of property and interests therein, in respect to, appertaining to or in connection with any and all risks or perils of navigation, transit or transportation, or while being assembled, packed, crated, baled, compressed or similarly prepared for shipment or while awaiting shipment, or during any delays, storage, transshipment, or reshipment incident thereto, including war risks, marine builder's risks, and all personal property floater risks.

.. Person or property in connection with or appertaining to a marine, transit or transportation insurance, including liability for loss of or damage to either incident to the construction, repair, operation, maintenance or use of the subject matter of such insurance (but not including life insurance or surety bonds nor insurance against loss by reason of bodily injury to any person arising out of the ownership, maintenance, or use of automobiles).

.. Precious stones, jewels, jewelry, precious metals, whether in course of transportation or otherwise.

.. Bridges, tunnels and other instrumentalities of transportation and communication (excluding buildings, their furniture and furnishings, fixed contents and supplies held in storage); piers, wharves, docks and slips, and other aids to navigation and transportation, including dry docks and marine railways, dams and appurtenant facilities for the control of waterways.

. "Marine protection and indemnity insurance," meaning insurance against, or against legal liability of the insured for, loss, damage, or expense incident to ownership, operation, chartering, maintenance, use, repair or construction of any vessel, craft or instrumentality in use in ocean or inland waterways, including liability of the insured for personal injury, illness or death or for loss of or damage to the property of another person.

[ 1947 c 79 § .11.05; Rem. Supp. 1947 § 45.11.05; ]

== 48.11.060 - "Vehicle insurance" defined.
. "Vehicle insurance" is insurance against loss or damage to any land vehicle or aircraft or any draft or riding animal or to property while contained therein or thereon or being loaded or unloaded therein or therefrom, and against any loss or liability resulting from or incident to ownership, maintenance, or use of any such vehicle or aircraft or animal.

. Insurance against accidental death or accidental injury to individuals while in, entering, alighting from, adjusting, repairing, cranking, or caused by being struck by a vehicle, aircraft, or draft or riding animal, if such insurance is issued as part of insurance on the vehicle, aircraft, or draft or riding animal, shall be deemed to be vehicle insurance.

[ 1947 c 79 § .11.06; Rem. Supp. 1947 § 45.11.06; ]

== 48.11.070 - "General casualty insurance" defined.
"General casualty insurance" includes vehicle insurance as defined in RCW 48.11.060, and in addition is insurance:

. Against legal liability for the death, injury, or disability of any human being, or for damage to property.

. Of medical, hospital, surgical and funeral benefits to persons injured, irrespective of legal liability of the insured, when issued with or supplemental to insurance against legal liability for the death, injury or disability of human beings.

. Of the obligations accepted by, imposed upon, or assumed by employers under law for workers' compensation.

. Against loss or damage by burglary, theft, larceny, robbery, forgery, fraud, vandalism, malicious mischief, confiscation or wrongful conversion, disposal or concealment, or from any attempt of any of the foregoing; also insurance against loss of or damage to moneys, coins, bullion, securities, notes, drafts, acceptances or any other valuable papers or documents, resulting from any cause, except while in the custody or possession of and being transported by any carrier for hire or in the mail.

. Upon personal effects against loss or damage from any cause.

. Against loss or damage to glass, including its lettering, ornamentation and fittings.

. Against any liability and loss or damage to property resulting from accidents to or explosions of boilers, pipes, pressure containers, machinery, or apparatus and to make inspection of and issue certificates of inspection upon elevators, boilers, machinery, and apparatus of any kind.

. Against loss or damage to any property caused by the breakage or leakage of sprinklers, water pipes and containers, or by water entering through leaks or openings in buildings.

. Against loss or damage resulting from failure of debtors to pay their obligations to the insured (credit insurance).

. Against any other kind of loss, damage, or liability properly the subject of insurance and not within any other kind or kinds of insurance as defined in this chapter, if such insurance is not contrary to law or public policy.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c185.pdf?cite=1987%20c%20185%20§%2018[1987 c 185 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c197.pdf?cite=1953%20c%20197%20§%205[1953 c 197 § 5]; 1947 c 79 § .11.07; Rem. Supp. 1947 § 45.11.07; ]

== 48.11.080 - "Surety insurance" defined.
"Surety insurance" includes:

. Credit insurance as defined in subdivision (9) of RCW 48.11.070.

. Bail bond insurance.

. Fidelity insurance, which is insurance guaranteeing the fidelity of persons holding positions of public or private trust.

. Guaranteeing the performance of contracts, other than insurance policies, and guaranteeing and executing bonds, undertakings, and contracts of suretyship.

. Indemnifying banks, bankers, brokers, financial or moneyed corporations or associations against loss resulting from any cause of bills of exchange, notes, bonds, securities, evidence of debts, deeds, mortgages, warehouse receipts, or other valuable papers, documents, money, precious metals and articles made therefrom, jewelry, watches, necklaces, bracelets, gems, precious and semiprecious stones, including any loss while the same are being transported in armored motor vehicles, or by messenger, but not including any other risks of transportation or navigation; also against loss or damage to such an insured's premises, or to his or her furnishings, fixtures, equipment, safes and vaults therein, caused by burglary, robbery, theft, vandalism or malicious mischief, or any attempt thereat.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%207051[2009 c 549 § 7051]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c150.pdf?cite=1967%20c%20150%20§%208[1967 c 150 § 8]; 1947 c 79 § .11.08; Rem. Supp. 1947 § 45.11.08; ]

== 48.11.100 - "Title insurance" defined.
"Title insurance" is insurance of owners of property or others having an interest in real property, against loss by encumbrance, or defective titles, or adverse claim to title, and associated services.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1197-S.SL.pdf?cite=2005%20c%20223%20§%203[2005 c 223 § 3]; 1947 c 79 § .11.10; Rem. Supp. 1947 § 45.11.10; ]

== 48.11.105 - "Ocean marine and foreign trade insurances" defined.
For the purposes of this code other than as to chapter 48.19 RCW "ocean marine and foreign trade insurances" shall include only:

. Insurances upon vessels, crafts, hulls, and of interests therein or with relation thereto;

. Insurance of marine builders' risks, marine war risks, and contracts of marine protection and indemnity insurance;

. Insurance of freights and disbursements pertaining to a subject of insurance coming within this definition;

. Insurance of personal property and interests therein, in course of exportation from or importation into any country, or in course of transportation coastwise, including transportation by land, water, or air from point of origin to final destination, in respect to, appertaining to, or in connection with, any and all risks or perils of navigation, transit, or transportation, and while being prepared for and while awaiting shipment, and during any delays, storage, transshipment, or reshipment incident thereto.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5042.SL.pdf?cite=2007%20c%2080%20§%205[2007 c 80 § 5]; ]

== 48.11.130 - Reinsurance powers.
A domestic mutual assessment insurer shall not have authority to accept reinsurance. Any other domestic insurer may accept reinsurance only of such kinds of insurance as it is authorized to transact direct.

[ 1947 c 79 § .11.13; Rem. Supp. 1947 § 45.11.13; ]

== 48.11.140 - Limitation of single risk.
. An insurer may not retain any risk on any one subject of insurance, whether located or to be performed in this state or elsewhere, in an amount exceeding ten percent of its surplus to policyholders.

. For the purposes of this section, a "subject of insurance" as to insurance against fire includes all properties insured by the same insurer that are reasonably subject to loss or damage from the same fire.

. Reinsurance in an alien reinsurer not qualified under *RCW 48.12.166 may not be deducted in determining risk retained for the purposes of this section.

. In the case of surety insurance, the net retention shall be computed after deduction of reinsurances, the amount assumed by any co-surety, the value of any security deposited, pledged, or held subject to the consent of the surety and for the protection of the surety.

. This section does not apply to life insurance, disability insurance, title insurance, or insurance of marine risks or marine protection and indemnity risks.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1197-S.SL.pdf?cite=2005%20c%20223%20§%204[2005 c 223 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1855-S.SL.pdf?cite=1993%20c%20462%20§%2053[1993 c 462 § 53]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%20149[1983 c 3 § 149]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c225.pdf?cite=1959%20c%20225%20§%202[1959 c 225 § 2]; 1947 c 79 § .11.14; Rem. Supp. 1947 § 45.11.14; ]

