= 48.42 - Personal coverage, general authority.
:toc:

== 48.42.010 - Personal coverage, authority of commissioner—Definition.
. Notwithstanding any other provision of law, and except as provided in this chapter, any person or other entity which provides coverage in this state for life insurance, annuities, loss of time, medical, surgical, chiropractic, physical therapy, speech pathology, audiology, professional mental health, dental, hospital, or optometric expenses, whether the coverage is by direct payment, reimbursement, the providing of services, or otherwise, shall be subject to the authority of the state insurance commissioner, unless the person or other entity shows that while providing the services it is subject to the jurisdiction and regulation of another agency of this state, any subdivisions thereof, or the federal government.

. "Another agency of this state, any subdivision thereof, or the federal government" does not include the Washington health benefit exchange under chapter 43.71 RCW or P.L. 111-148 of 2010, as amended.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=2012%20c%2087%20§%2010[2012 c 87 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c264.pdf?cite=1985%20c%20264%20§%2015[1985 c 264 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c36.pdf?cite=1983%20c%2036%20§%201[1983 c 36 § 1]; ]

== 48.42.020 - Showing regulation by other agency, how done—Definition.
. A person or entity may show that it is subject to the jurisdiction and regulation of another agency of this state, any subdivision thereof, or the federal government, by providing to the insurance commissioner the appropriate certificate, license, or other document issued by the other governmental agency which permits or qualifies it to provide the coverage as defined in RCW 48.42.010.

. "Another agency of this state, any subdivision thereof, or the federal government" does not include the Washington health benefit exchange under chapter 43.71 RCW or P.L. 111-148 of 2010, as amended.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=2012%20c%2087%20§%2011[2012 c 87 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c36.pdf?cite=1983%20c%2036%20§%202[1983 c 36 § 2]; ]

== 48.42.030 - Examination by commissioner—When required, scope of.
Any person or entity which is unable to show under RCW 48.42.020 that it is subject to the jurisdiction and regulation of another agency of this state, any subdivision thereof, or the federal government, shall submit to an examination by the insurance commissioner to determine the organization and solvency of the person or the entity, and to determine whether or not such person or entity complies with the applicable provisions of this title.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c36.pdf?cite=1983%20c%2036%20§%203[1983 c 36 § 3]; ]

== 48.42.040 - Application of this title to otherwise unregulated entities.
Any person or entity unable to show that it is subject to the jurisdiction and regulation of another agency of this state, any subdivision thereof, or the federal government, shall be subject to all appropriate provisions of this title regarding the conduct of its business including, but not limited to, RCW 48.43.300 through 48.43.370.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6302-S.SL.pdf?cite=1998%20c%20241%20§%2016[1998 c 241 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c36.pdf?cite=1983%20c%2036%20§%204[1983 c 36 § 4]; ]

== 48.42.050 - Notice to purchasers by uninsured production agency—Notice to production agency by administrator of coverage.
Any production agency or administrator which advertises, sells, transacts, or administers the coverage in this state described in RCW 48.42.010 and which is required to submit to an examination by the insurance commissioner under RCW 48.42.030, shall, if the coverage is not fully insured or otherwise fully covered by an admitted life or disability insurer or health care service contractor or health maintenance organization agreement, advise every purchaser, prospective purchaser, and covered person of the lack of insurance or other coverage.

Any administrator which advertises or administers the coverage in this state described in RCW 48.42.010 and which is subject to an examination by the insurance commissioner under RCW 48.42.030 shall advise any production agency of the elements of the coverage, including the amount of "stop-loss" insurance in effect.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c36.pdf?cite=1983%20c%2036%20§%205[1983 c 36 § 5]; ]

== 48.42.090 - Prenatal testing—Limitation on changes to coverage.
The carrier or provider of any group disability contract, health care services contract or health maintenance agreement shall not cancel, reduce, limit or otherwise alter or change the coverage provided solely on the basis of the result of any prenatal test.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c276.pdf?cite=1988%20c%20276%20§%209[1988 c 276 § 9]; ]

== 48.42.100 - Women's health care services—Duties of health care carriers. (Effective until July 1, 2022.)
. For purposes of this section, health care carriers includes disability insurers regulated under chapter 48.20 or 48.21 RCW, health care services contractors regulated under chapter 48.44 RCW, health maintenance organizations regulated under chapter 48.46 RCW, plans operating under the health care authority under chapter 41.05 RCW, the state health insurance pool operating under chapter 48.41 RCW, and insuring entities regulated under chapter 48.43 RCW.

. For purposes of this section and consistent with their lawful scopes of practice, types of health care practitioners that provide women's health care services shall include, but need not be limited by a health care carrier to, the following: Any generally recognized medical specialty of practitioners licensed under chapter 18.57 or 18.71 RCW who provides women's health care services; practitioners licensed under chapters 18.57A and 18.71A RCW when providing women's health care services; midwives licensed under chapter 18.50 RCW; and advanced registered nurse practitioner specialists in women's health and midwifery under chapter 18.79 RCW.

. For purposes of this section, women's health care services shall include, but need not be limited by a health care carrier to, the following: Maternity care; reproductive health services; gynecological care; general examination; and preventive care as medically appropriate and medically appropriate follow-up visits for the services listed in this subsection.

. Health care carriers shall ensure that enrolled female patients have direct access to timely and appropriate covered women's health care services from the type of health care practitioner of their choice in accordance with subsection (5) of this section.

. [Empty]
.. Health care carrier policies, plans, and programs written, amended, or renewed after July 23, 1995, shall provide women patients with direct access to the type of health care practitioner of their choice for appropriate covered women's health care services without the necessity of prior referral from another type of health care practitioner.

.. Health care carriers may comply with this section by including all the types of health care practitioners listed in this section for women's health care services for women patients.

.. Nothing in this section shall prevent health care carriers from restricting women patients to seeing only health care practitioners who have signed participating provider agreements with the health care carrier.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2031.SL.pdf?cite=2000%20c%207%20§%201[2000 c 7 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5854-S.SL.pdf?cite=1995%20c%20389%20§%201[1995 c 389 § 1]; ]

