= 48.14 - Fees and taxes.
:toc:

== 48.14.010 - Fee schedule.
. The commissioner shall collect in advance the following fees:

..For filing charter documents: (i)Original charter documents, bylaws or record of organization of insurers, or certified copies thereof, required to be filed. . . .$250.00 (ii)Amended charter documents, or certified copy thereof, other than amendments of bylaws. . . .$ 10.00 (iii)No additional charge or fee shall be required for filing any of such documents in the office of the secretary of state. (b)Certificate of authority: (i)Issuance. . . .$ 25.00 (ii)Renewal. . . .$ 25.00(c)Annual statement of insurer, filing. . . .$ 20.00(d)Organization or financing of domestic insurers and affiliated corporations: (i)Application for solicitation permit, filing. . . .$100.00 (ii)Issuance of solicitation permit. . . .$ 25.00(e)Insurance producer licenses: (i)License application. . . .$ 55.00 (ii)License renewal, every two years   . . . .$ 55.00 (iii)Initial appointment and renewal of appointment of each insurance producer, every two years. . . .$ 20.00 (iv)Limited line insurance producer license application and renewal, every two years. . . .$ 20.00(f)Title insurance agent licenses: (i)License application. . . .$ 50.00 (ii)License renewal, every two years. . . .$ 50.00(g)Reinsurance intermediary licenses: (i)Reinsurance intermediary-broker, each year. . . .$ 50.00 (ii)Reinsurance intermediary-manager, each year. . . .$100.00(h)Surplus line broker license application and renewal, every two years. . . .$200.00(i)Adjusters' licenses: (i)Independent adjuster: (A) License application. . . .(B) License renewal, every twoyears. . . .$ 50.00$ 50.00 (ii)Public adjuster: (A) License application. . . .(B) License renewal, every twoyears. . . .$ 50.00$ 50.00 (iii)Crop adjuster: (A) License application. . . .(B) License renewal, every twoyears. . . .$ 50.00$50.00 (j)Managing general agent appointment, every two years. . . .$200.00(k)Examination for license, each examination: All examinations, except examinations   administered by an independent testing service, the fees for which are to be approved by the commissioner and collected directly by and retained by such independent testing service  . . . .$ 20.00 (l)Miscellaneous services: (i)Filing other documents. . . .$ 5.00 (ii)Commissioner's certificate under seal. . . .$ 5.00 (iii)Copy of documents filed in the commissioner's office, reasonable charge therefor as determined by the commissioner. (m)Self-service storage specialty insurance producer license application and renewal: Every two years, $130.00 for an owner with under fifty employees or $375.00 for an owner with fifty or more employees; plus a location fee of $35.00 for each additional location of an owner. 

..

For filing charter documents:

 

...

Original charter documents, bylaws or record of organization of insurers, or certified copies thereof, required to be filed. . . .

$250.00

 

...

Amended charter documents, or certified copy thereof, other than amendments of bylaws. . . .

$ 10.00

 

...

No additional charge or fee shall be required for filing any of such documents in the office of the secretary of state.

 

..

Certificate of authority:

 

...

Issuance. . . .

$ 25.00

 

...

Renewal. . . .

$ 25.00

..

Annual statement of insurer, filing. . . .

$ 20.00

..

Organization or financing of domestic insurers and affiliated corporations:

 

...

Application for solicitation permit, filing. . . .

$100.00

 

...

Issuance of solicitation permit. . . .

$ 25.00

..

Insurance producer licenses:

 

...

License application. . . .

$ 55.00

 

...

License renewal, every two years

 

 

 

. . . .

$ 55.00

 

...

Initial appointment and renewal of appointment of each insurance producer, every two years. . . .

$ 20.00

 

...

Limited line insurance producer license application and renewal, every two years. . . .

$ 20.00

..

Title insurance agent licenses:

 

...

License application. . . .

$ 50.00

 

...

License renewal, every two 

years. . . .

$ 50.00

..

Reinsurance intermediary licenses:

 

...

Reinsurance intermediary-broker, each year. . . .

$ 50.00

 

...

Reinsurance intermediary-

manager, each year. . . .

$100.00

..

Surplus line broker license application and renewal, every two years. . . .

$200.00

..

Adjusters' licenses:

 

...

Independent adjuster: (A) License application. . . .

(B) License renewal, every two

years. . . .



$ 50.00



$ 50.00

 

...

Public adjuster: (A) License application. . . .

(B) License renewal, every two

years. . . .



$ 50.00



$ 50.00

 

...

Crop adjuster: (A) License application. . . .

(B) License renewal, every two

years. . . .



$ 50.00



$50.00

 (j)

Managing general agent appointment, every two years. . . .

$200.00

..

Examination for license, each examination:

 

All examinations, except examinations   administered by an independent testing service, the fees for which are to be approved by the commissioner and collected directly by and retained by such independent testing service

 

 

. . . .

$ 20.00

 (l)

Miscellaneous services:

 

...

Filing other documents. . . .

$ 5.00

 

...

Commissioner's certificate under seal. . . .

$ 5.00

 

...

Copy of documents filed in the commissioner's office, reasonable charge therefor as determined by the commissioner.

 

..

Self-service storage specialty insurance producer license application and renewal:

 

Every two years, $130.00 for an owner with under fifty employees or $375.00 for an owner with fifty or more employees; plus a location fee of $35.00 for each additional location of an owner.

 

. All fees so collected shall be remitted by the commissioner to the state treasurer not later than the first business day following, and shall be placed to the credit of the general fund.

.. Fees for examinations administered by an independent testing service that are approved by the commissioner under subsection (1)(k) of this section shall be collected directly by the independent testing service and retained by it.

.. Fees for copies of documents filed in the commissioner's office shall be remitted by the commissioner to the state treasurer not later than the first business day following, and shall be placed to the credit of the insurance commissioner's regulatory account.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6306-S.SL.pdf?cite=2010%20c%2067%20§%201[2010 c 67 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1568.SL.pdf?cite=2009%20c%20162%20§%202[2009 c 162 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2013-S.SL.pdf?cite=2009%20c%20119%20§%2010[2009 c 119 § 10]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5715-S.SL.pdf?cite=2007%20c%20117%20§%2037[2007 c 117 § 37]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1197-S.SL.pdf?cite=2005%20c%20223%20§%205[2005 c 223 § 5]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2570-S.SL.pdf?cite=1994%20c%20131%20§%202[1994 c 131 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1855-S.SL.pdf?cite=1993%20c%20462%20§%2057[1993 c 462 § 57]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c248.pdf?cite=1988%20c%20248%20§%207[1988 c 248 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c111.pdf?cite=1981%20c%20111%20§%201[1981 c 111 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c269.pdf?cite=1979%20ex.s.%20c%20269%20§%201[1979 ex.s. c 269 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c182.pdf?cite=1977%20ex.s.%20c%20182%20§%201[1977 ex.s. c 182 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c241.pdf?cite=1969%20ex.s.%20c%20241%20§%208[1969 ex.s. c 241 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c150.pdf?cite=1967%20c%20150%20§%2012[1967 c 150 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c303.pdf?cite=1955%20c%20303%20§%204[1955 c 303 § 4]; 1947 c 79 § .14.01; Rem. Supp. 1947 § 45.14.01; ]

== 48.14.020 - Premium taxes.
. Subject to other provisions of this chapter, each authorized insurer except title insurers shall on or before the first day of March of each year pay to the state treasurer through the commissioner's office a tax on premiums. Except as provided in subsection (3) of this section, such tax shall be in the amount of two percent of all premiums, excluding amounts returned to or the amount of reductions in premiums allowed to holders of industrial life policies for payment of premiums directly to an office of the insurer, collected or received by the insurer under RCW 48.14.090 during the preceding calendar year other than ocean marine and foreign trade insurances, after deducting premiums paid to policyholders as returned premiums, upon risks or property resident, situated, or to be performed in this state. For tax purposes, the reporting of premiums shall be on a written basis or on a paid-for basis consistent with the basis required by the annual statement. For the purposes of this section the consideration received by an insurer for the granting of an annuity shall not be deemed to be a premium.

. [Empty]
.. The taxes imposed in this section do not apply to amounts received by any life and disability insurer for health care services included within the definition of practice of dentistry under RCW 18.32.020 except amounts received for pediatric oral services that qualify as coverage for the minimum essential coverage requirement under P.L. 111-148 (2010), as amended, and for stand-alone family dental plans as defined in RCW 43.71.080(4)(a), only when offered in the individual market, as defined in *RCW 48.43.005(27), or to a small group, as defined in *RCW 48.43.005(33).

.. Beginning January 1, 2014, moneys collected for premiums written on qualified health benefit plans and qualified dental plans offered through the health benefit exchange under chapter 43.71 RCW must be deposited in the health benefit exchange account under RCW 43.71.060.

. In the case of insurers which require the payment by their policyholders at the inception of their policies of the entire premium thereon in the form of premiums or premium deposits which are the same in amount, based on the character of the risks, regardless of the length of term for which such policies are written, such tax shall be in the amount of two percent of the gross amount of such premiums and premium deposits upon policies on risks resident, located, or to be performed in this state, in force as of the thirty-first day of December next preceding, less the unused or unabsorbed portion of such premiums and premium deposits computed at the average rate thereof actually paid or credited to policyholders or applied in part payment of any renewal premiums or premium deposits on one-year policies expiring during such year.

. Each authorized insurer shall with respect to all ocean marine and foreign trade insurance contracts written within this state during the preceding calendar year, on or before the first day of March of each year pay to the state treasurer through the commissioner's office a tax of ninety-five one-hundredths of one percent on its gross underwriting profit. Such gross underwriting profit shall be ascertained by deducting from the net premiums (i.e., gross premiums less all return premiums and premiums for reinsurance) on such ocean marine and foreign trade insurance contracts the net losses paid (i.e., gross losses paid less salvage and recoveries on reinsurance ceded) during such calendar year under such contracts. In the case of insurers issuing participating contracts, such gross underwriting profit shall not include, for computation of the tax prescribed by this subsection, the amounts refunded, or paid as participation dividends, by such insurers to the holders of such contracts.

. The state does hereby preempt the field of imposing excise or privilege taxes upon insurers or their appointed insurance producers, other than title insurers, and no county, city, town or other municipal subdivision shall have the right to impose any such taxes upon such insurers or these insurance producers.

. If an authorized insurer collects or receives any such premiums on account of policies in force in this state which were originally issued by another insurer and which other insurer is not authorized to transact insurance in this state on its own account, such collecting insurer shall be liable for and shall pay the tax on such premiums.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2768.SL.pdf?cite=2016%20c%20133%20§%201[2016 c 133 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1947-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%206%20§%206[2013 2nd sp.s. c 6 § 6]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1846-S.SL.pdf?cite=2013%20c%20325%20§%204[2013 c 325 § 4]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1567.SL.pdf?cite=2009%20c%20161%20§%203[2009 c 161 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6591.SL.pdf?cite=2008%20c%20217%20§%206[2008 c 217 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c296.pdf?cite=1986%20c%20296%20§%201[1986 c 296 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex2c3.pdf?cite=1983%202nd%20ex.s.%20c%203%20§%207[1983 2nd ex.s. c 3 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex2c10.pdf?cite=1982%202nd%20ex.s.%20c%2010%20§%201[1982 2nd ex.s. c 10 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c35.pdf?cite=1982%201st%20ex.s.%20c%2035%20§%2015[1982 1st ex.s. c 35 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c233.pdf?cite=1979%20ex.s.%20c%20233%20§%202[1979 ex.s. c 233 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c241.pdf?cite=1969%20ex.s.%20c%20241%20§%209[1969 ex.s. c 241 § 9]; 1947 c 79 § .14.02; Rem. Supp. 1947 § 45.14.02; ]

== 48.14.0201 - Premiums and prepayments tax—Health care services—Exemptions—State preemption.
. As used in this section, "taxpayer" means a health maintenance organization as defined in RCW 48.46.020, a health care service contractor as defined in chapter 48.44 RCW, or a self-funded multiple employer welfare arrangement as defined in RCW 48.125.010.

. Each taxpayer must pay a tax on or before the first day of March of each year to the state treasurer through the insurance commissioner's office. The tax must be equal to the total amount of all premiums and prepayments for health care services collected or received by the taxpayer under RCW 48.14.090 during the preceding calendar year multiplied by the rate of two percent. For tax purposes, the reporting of premiums and prepayments must be on a written basis or on a paid-for basis consistent with the basis required by the annual statement.

. Taxpayers must prepay their tax obligations under this section. The minimum amount of the prepayments is the percentages of the taxpayer's tax obligation for the preceding calendar year recomputed using the rate in effect for the current year. For the prepayment of taxes due during the first calendar year, the minimum amount of the prepayments is the percentages of the taxpayer's tax obligation that would have been due had the tax been in effect during the previous calendar year. The tax prepayments must be paid to the state treasurer through the commissioner's office by the due dates and in the following amounts:

.. On or before June 15, forty-five percent;

.. On or before September 15, twenty-five percent;

.. On or before December 15, twenty-five percent.

. For good cause demonstrated in writing, the commissioner may approve an amount smaller than the preceding calendar year's tax obligation as recomputed for calculating the health maintenance organization's, health care service contractor's, self-funded multiple employer welfare arrangement's, or certified health plan's prepayment obligations for the current tax year.

. [Empty]
.. Except as provided in (b) of this subsection, moneys collected under this section are deposited in the general fund.

.. Beginning January 1, 2014, moneys collected from taxpayers for premiums written on qualified health benefit plans and qualified dental plans offered through the health benefit exchange under chapter 43.71 RCW must be deposited in the health benefit exchange account under RCW 43.71.060.

. The taxes imposed in this section do not apply to:

.. Amounts received by any taxpayer from the United States or any instrumentality thereof as prepayments for health care services provided under Title XVIII (medicare) of the federal social security act.

.. Amounts received by any taxpayer from the state of Washington as prepayments for health care services provided under:

... The medical care services program as provided in RCW 74.09.035; or

... The Washington basic health plan on behalf of subsidized enrollees as provided in chapter 70.47 RCW.

.. Amounts received by any health care service contractor as defined in chapter 48.44 RCW, or any health maintenance organization as defined in chapter 48.46 RCW, as prepayments for health care services included within the definition of practice of dentistry under RCW 18.32.020, except amounts received for pediatric oral services that qualify as coverage for the minimum essential coverage requirement under P.L. 111-148 (2010), as amended, and for stand-alone family dental plans as defined in RCW 43.71.080(4)(a), only when offered in the individual market, as defined in *RCW 48.43.005(27), or to a small group, as defined in *RCW 48.43.005(33).

.. Participant contributions to self-funded multiple employer welfare arrangements that are not taxable in this state.

. Beginning January 1, 2000, the state preempts the field of imposing excise or privilege taxes upon taxpayers and no county, city, town, or other municipal subdivision has the right to impose any such taxes upon such taxpayers. This subsection is limited to premiums and payments for health benefit plans offered by health care service contractors under chapter 48.44 RCW, health maintenance organizations under chapter 48.46 RCW, and self-funded multiple employer welfare arrangements as defined in RCW 48.125.010. The preemption authorized by this subsection must not impair the ability of a county, city, town, or other municipal subdivision to impose excise or privilege taxes upon the health care services directly delivered by the employees of a health maintenance organization under chapter 48.46 RCW.

. [Empty]
.. The taxes imposed by this section apply to a self-funded multiple employer welfare arrangement only in the event that they are not preempted by the employee retirement income security act of 1974, as amended, 29 U.S.C. Sec. 1001 et seq. The arrangements and the commissioner must initially request an advisory opinion from the United States department of labor or obtain a declaratory ruling from a federal court on the legality of imposing state premium taxes on these arrangements. Once the legality of the taxes has been determined, the multiple employer welfare arrangement certified by the insurance commissioner must begin payment of these taxes.

.. If there has not been a final determination of the legality of these taxes, then beginning on the earlier of (i) the date the fourth multiple employer welfare arrangement has been certified by the insurance commissioner, or (ii) April 1, 2006, the arrangement must deposit the taxes imposed by this section into an interest bearing escrow account maintained by the arrangement. Upon a final determination that the taxes are not preempted by the employee retirement income security act of 1974, as amended, 29 U.S.C. Sec. 1001 et seq., all funds in the interest bearing escrow account must be transferred to the state treasurer.

. The effect of transferring contracts for health care services from one taxpayer to another taxpayer is to transfer the tax prepayment obligation with respect to the contracts.

. On or before June 1st of each year, the commissioner must notify each taxpayer required to make prepayments in that year of the amount of each prepayment and must provide remittance forms to be used by the taxpayer. However, a taxpayer's responsibility to make prepayments is not affected by failure of the commissioner to send, or the taxpayer to receive, the notice or forms.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2768.SL.pdf?cite=2016%20c%20133%20§%202[2016 c 133 § 2]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1947-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%206%20§%205[2013 2nd sp.s. c 6 § 5]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1846-S.SL.pdf?cite=2013%20c%20325%20§%203[2013 c 325 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5213.SL.pdf?cite=2011%20c%2047%20§%208[2011 c 47 § 8]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5073-S.SL.pdf?cite=2009%20c%20479%20§%2041[2009 c 479 § 41]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1690.SL.pdf?cite=2005%20c%20405%20§%201[2005 c 405 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1197-S.SL.pdf?cite=2005%20c%20223%20§%206[2005 c 223 § 6]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5957.SL.pdf?cite=2005%20c%207%20§%201[2005 c 7 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6112-S.SL.pdf?cite=2004%20c%20260%20§%2024[2004 c 260 § 24]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3096-S.SL.pdf?cite=1998%20c%20323%20§%201[1998 c 323 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1219-S.SL.pdf?cite=1997%20c%20154%20§%201[1997 c 154 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5967-S.SL.pdf?cite=1993%20sp.s.%20c%2025%20§%20601[1993 sp.s. c 25 § 601]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20301[1993 c 492 § 301]; ]

== 48.14.021 - Reduction of tax—Policies connected with pension, etc., plans exempt or qualified under internal revenue code.
As to premiums received from policies or contracts issued in connection with a pension, annuity or profit-sharing plan exempt or qualified under sections 401, 403(b), 404, 408(b), or 501(a) of the United States internal revenue code, the rate of tax specified in RCW 48.14.020 shall be reduced twelve and one-half percent with respect to the tax payable in 1964, twenty-five percent with respect to the tax payable in 1965, thirty-seven and one-half percent with respect to the tax payable in 1966, fifty percent with respect to the tax payable in 1967, sixty-two and one-half percent with respect to the tax payable in 1968, seventy-five percent with respect to the tax payable in 1969, eighty-seven and one-half percent with respect to the tax payable in 1970, and one hundred percent with respect to the tax payable in 1971 and annually thereafter.

[ 1975-'76 2nd ex.s. c 119 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c132.pdf?cite=1974%20ex.s.%20c%20132%20§%201[1974 ex.s. c 132 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c166.pdf?cite=1963%20c%20166%20§%201[1963 c 166 § 1]; ]

== 48.14.022 - Taxes—Exemptions and deductions.
. The taxes imposed in RCW 48.14.020 and 48.14.0201 do not apply to premiums and prepayments collected or received for policies of insurance issued under RCW 48.41.010 through 48.41.210.

. In computing tax due under RCW 48.14.020 and 48.14.0201, there may be deducted from taxable premiums and prepayments the amount of any assessment against the taxpayer under RCW 48.41.010 through 48.41.210. Any portion of the deduction allowed in this section which cannot be deducted in a tax year without reducing taxable premiums below zero may be carried forward and deducted in successive years until the deduction is exhausted.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1995-S.SL.pdf?cite=1995%20c%20304%20§%201[1995 c 304 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c431.pdf?cite=1987%20c%20431%20§%2023[1987 c 431 § 23]; ]

== 48.14.025 - Prepayment of tax obligations under RCW  48.14.020.
. Every insurer with a tax obligation under RCW 48.14.020 shall make prepayment of the tax obligations under RCW 48.14.020 for the current calendar year's business, if the sum of the tax obligations under RCW 48.14.020 for the preceding calendar year's business is four hundred dollars or more.

. The commissioner shall credit the prepayment toward the appropriate tax obligations of the insurer for the current calendar year under RCW 48.14.020.

. The minimum amounts of the prepayments shall be percentages of the insurer's preceding calendar year's tax obligation recomputed using the rate in effect for the current year and shall be paid to the state treasurer through the commissioner's office by the due dates and in the following amounts:

.. On or before June 15, forty-five percent;

.. On or before September 15, twenty-five percent; and

.. On or before December 15, twenty-five percent.

For good cause demonstrated in writing, the commissioner may approve an amount smaller than the preceding calendar year's tax obligation as recomputed for calculating the insurer's prepayment obligations.

. The effect of transferring policies of insurance from one insurer to another insurer is to transfer the tax prepayment obligation with respect to the policies.

. On or before June 1 of each year, the commissioner shall notify each insurer required to make prepayments in that year of the amount of each prepayment and shall provide remittance forms to be used by the insurer. However, an insurer's responsibility to make prepayments is not affected by failure of the commissioner to send, or the insurer to receive, the notice or forms.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c296.pdf?cite=1986%20c%20296%20§%202[1986 c 296 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c181.pdf?cite=1982%20c%20181%20§%204[1982 c 181 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c6.pdf?cite=1981%20c%206%20§%201[1981 c 6 § 1]; ]

== 48.14.027 - Exemption for state health care premiums before July 1, 1990.
The taxes imposed in RCW 48.14.020 do not apply to premiums collected or received before July 1, 1990, for medical and dental coverage purchased under chapter 41.05 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c107.pdf?cite=1988%20c%20107%20§%2032[1988 c 107 § 32]; ]

== 48.14.030 - Tax statement.
The insurer shall file with the commissioner as part of its annual statement a statement of premiums so collected or received according to such form as shall be prescribed and furnished by the commissioner. In every such statement the reporting of premiums for tax purposes shall be on a written basis or on a paid-for basis consistent with the basis required by the annual statement.

[ 1947 c 79 § .14.03; Rem. Supp. 1947 § 45.14.03; ]

== 48.14.040 - Retaliatory provision.
. If pursuant to the laws of any other state or country, any taxes, licenses, fees, deposits, or other obligations or prohibitions, in the aggregate, or additional to or at a net rate in excess of any such taxes, licenses, fees, deposits or other obligations or prohibitions imposed by the laws of this state upon like foreign or alien insurers and their appointed insurance producers or title insurance agents, are imposed on insurers of this state and their appointed insurance producers or title insurance agents doing business in such other state or country, a like rate, obligation or prohibition may be imposed by the commissioner, as to any item or combination of items involved, upon all insurers of such other state or country and their appointed insurance producers or title insurance agents doing business in this state, so long as such laws remain in force or are so applied.

. For the purposes of this section, an alien insurer may be deemed to be domiciled in the state wherein it has established its principal office or agency in the United States. If no such office or agency has been established, the domicile of the alien insurer shall be deemed to be the country under the laws of which it is formed.

. For the purposes of this section, the regulatory and insurance fraud surcharges imposed by RCW 48.02.190 shall not be included in the calculation of any retaliatory taxes, licenses, fees, deposits, or other obligations or prohibitions imposed under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6049.SL.pdf?cite=2020%20c%20195%20§%203[2020 c 195 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6591.SL.pdf?cite=2008%20c%20217%20§%207[2008 c 217 § 7]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5919-S.SL.pdf?cite=2007%20c%20153%20§%204[2007 c 153 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c248.pdf?cite=1988%20c%20248%20§%208[1988 c 248 § 8]; 1949 c 190 § 21, part; 1947 c 79 § .14.04; Rem. Supp. 1949 § 45.14.04; ]

== 48.14.060 - Failure to pay tax—Penalty.
. Any insurer or taxpayer, as defined in RCW 48.14.0201, failing to file its tax statement and to pay the specified tax or prepayment of tax on premiums and prepayments for health care services by the last day of the month in which the tax becomes due shall be assessed a penalty of five percent of the amount of the tax; and if the tax is not paid within forty-five days after the due date, the insurer will be assessed a total penalty of ten percent of the amount of the tax; and if the tax is not paid within sixty days of the due date, the insurer will be assessed a total penalty of twenty percent of the amount of the tax. The tax may be collected by distraint, and the penalty recovered by any action instituted by the commissioner in any court of competent jurisdiction. The amount of any penalty collected must be paid to the state treasurer and credited to the general fund.

. In addition to the penalties set forth in subsection (1) of this section, interest will accrue on the amount of the unpaid tax or prepayment at the maximum legal rate of interest permitted under RCW 19.52.020 commencing sixty-one days after the tax is due until paid. This interest will not accrue on taxes imposed under RCW 48.15.120.

. The commissioner may revoke the certificate of authority or registration of any delinquent insurer or taxpayer, and the certificate of authority or registration will not be reissued until all taxes, prepayments of tax, interest, and penalties have been fully paid and the insurer or taxpayer has otherwise qualified for the certificate of authority or registration.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2040-S.SL.pdf?cite=2003%20c%20341%20§%201[2003 c 341 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c6.pdf?cite=1981%20c%206%20§%202[1981 c 6 § 2]; 1947 c 79 § .14.06; Rem. Supp. 1947 § 45.14.06; ]

== 48.14.070 - Refunds.
In event any person has paid to the commissioner any tax, license fee or other charge in error or in excess of that which he or she is lawfully obligated to pay, the commissioner shall upon written request made to him or her make a refund thereof. A person may only request a refund of taxes within six years from the date the taxes were paid. A person may only request a refund of fees or charges other than taxes within thirteen months of the date the fees or charges were paid. Refunds may be made either by crediting the amount toward payment of charges due or to become due from such person, or by making a cash refund. To facilitate such cash refunds the commissioner may establish a revolving fund out of funds appropriated by the legislature for his use.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%207056[2009 c 549 § 7056]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c130.pdf?cite=1979%20ex.s.%20c%20130%20§%202[1979 ex.s. c 130 § 2]; 1947 c 79 § .14.07; Rem. Supp. 1947 § 45.14.07; ]

== 48.14.080 - Premium tax in lieu of other forms—Exceptions—Definition.
. As to insurers, other than title insurers and taxpayers under RCW 48.14.0201, the taxes imposed by this title are in lieu of all other taxes, except as otherwise provided in this section.

. Subsection (1) of this section does not apply with respect to:

.. Taxes on real and tangible personal property;

.. Excise taxes on the sale, purchase, use, or possession of (i) real property; (ii) tangible personal property; (iii) extended warranties; (iv) services, including digital automated services as defined in RCW 82.04.192; and (v) digital goods and digital codes as those terms are defined in RCW 82.04.192; and

.. The tax imposed in *RCW 82.04.260(9), regarding public and nonprofit hospitals.

. For the purposes of this section, the term "taxes" includes taxes imposed by the state or any county, city, town, municipal corporation, quasi-municipal corporation, or other political subdivision.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6143-S.SL.pdf?cite=2010%201st%20sp.s.%20c%2023%20§%20520[2010 1st sp.s. c 23 § 520]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2075-S.SL.pdf?cite=2009%20c%20535%20§%201102[2009 c 535 § 1102]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2880-S.SL.pdf?cite=2006%20c%20278%20§%202[2006 c 278 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2335.SL.pdf?cite=1998%20c%20312%20§%201[1998 c 312 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5967-S.SL.pdf?cite=1993%20sp.s.%20c%2025%20§%20602[1993 sp.s. c 25 § 602]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20302[1993 c 492 § 302]; 1949 c 190 § 21, part; Rem. Supp. 1949 § 45.14.08; ]

== 48.14.090 - Determining amount of direct premium taxable in this state.
In determining the amount of direct premium taxable in this state, all such premiums written, procured, or received in this state shall be deemed written upon risks or property resident, situated, or to be performed in this state except such premiums as are properly allocated or apportioned and reported as taxable premiums of any other state or states. For tax purposes, the reporting of premiums shall be on a written basis or on a paid-for basis consistent with the basis required by the annual statement.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1567.SL.pdf?cite=2009%20c%20161%20§%204[2009 c 161 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c195.pdf?cite=1963%20c%20195%20§%2014[1963 c 195 § 14]; ]

== 48.14.095 - Unlawful or delinquent insurers or taxpayers—Computing the tax payable—Risks, exposures, or enrolled participants only partially in state.
. This section applies to any insurer or taxpayer, as defined in RCW 48.14.0201, violating or failing to comply with RCW 48.05.030(1), 48.17.060 , 48.36A.290(1), 48.44.015(1), or 48.46.027(1).

. Except as provided in subsection (7) of this section, RCW 48.14.020, 48.14.0201, and 48.14.060 apply to insurers or taxpayers identified in subsection (1) of this section.

. If an insurance contract, health care services contract, or health maintenance agreement covers risks or exposures, or enrolled participants only partially in this state, the tax payable is computed on the portion of the premium that is properly allocated to a risk or exposure located in this state, or enrolled participants residing in this state.

. In determining the amount of taxable premiums under subsection (3) of this section, all premiums, other than premiums properly allocated or apportioned and reported as taxable premiums of another state, that are written, procured, or received in this state, or that are for a policy or contract negotiated in this state, are considered to be written on risks or property resident, situated, or to be performed in this state, or for health care services to be provided to enrolled participants residing in this state.

. Insurance on risks or property resident, situated, or to be performed in this state, or health coverage for the provision of health care services for residents of this state, is considered to be insurance procured, continued, renewed, or performed in this state, regardless of the location from which the application is made, the negotiations are conducted, or the premiums are remitted.

. Premiums on risks or exposures that are properly allocated to federal waters or international waters or under the jurisdiction of a foreign government are not taxable by this state.

. This section does not apply to premiums on insurance procured by a licensed surplus line broker under chapter 48.15 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6591.SL.pdf?cite=2008%20c%20217%20§%208[2008 c 217 § 8]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2040-S.SL.pdf?cite=2003%20c%20341%20§%203[2003 c 341 § 3]; ]

== 48.14.100 - Foreign or alien insurers, continuing liability for taxes.
Any foreign or alien insurer authorized to do business in this state which hereafter either withdraws from the state or has its certificate of authority suspended or revoked shall continue to pay premium taxes pursuant to this chapter as to policies upon risks or property resident, situated, or to be performed in this state, which policies were issued during the time the insurer was authorized in this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c195.pdf?cite=1963%20c%20195%20§%2015[1963 c 195 § 15]; ]

