= 48.09 - Mutual insurers.
:toc:

== 48.09.010 - Initial qualifications.
. The commissioner shall not issue a certificate of authority to a domestic mutual insurer unless it has fully qualified therefor under this code, and unless it has met the minimum requirements for the kind of insurance it proposes to transact as provided in this chapter.

. All applications for insurance submitted by such an insurer as fulfilling qualification requirements shall be bona fide applications from persons resident in this state covering lives, property, or risks resident or located in this state.

. All qualifying premiums collected and initial surplus funds of such an insurer shall be in cash. Any deposit made by such an insurer in lieu of applications, premiums, and initial surplus funds, shall be in cash or in securities eligible for the investment of the capital of a domestic stock insurer transacting the same kind of insurance.

[ 1947 c 79 § .09.01; Rem. Supp. 1947 § 45.09.01; ]

== 48.09.090 - Additional kinds of insurance.
A domestic mutual insurer may be authorized to transact kinds of insurance in addition to that for which it was originally authorized, if it has otherwise complied with the provisions of this code therefor, and while it possesses and maintains surplus funds in aggregate amount not less than the minimum amount of capital and surplus required under this code of a domestic stock insurer authorized to transact like kinds of insurance pursuant to RCW 48.05.340.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c135.pdf?cite=1980%20c%20135%20§%202[1980 c 135 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c193.pdf?cite=1957%20c%20193%20§%205[1957 c 193 § 5]; 1947 c 79 § .09.09; Rem. Supp. 1947 § 45.09.09; ]

== 48.09.100 - Minimum surplus.
A domestic mutual insurer on the cash premium plan shall at all times have and maintain surplus funds, representing the excess of its assets over its liabilities, in amount not less than the aggregate of

. the amount of any surplus funds deposited by it with the commissioner to qualify for its original certificate of authority, and

. the amount of any additional surplus required of it pursuant to RCW 48.09.090 for authority to transact additional kinds of insurance.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c195.pdf?cite=1963%20c%20195%20§%203[1963 c 195 § 3]; 1947 c 79 § .09.10; Rem. Supp. 1947 § 45.09.10; ]

== 48.09.110 - Membership.
. Each holder of one or more insurance contracts issued by a domestic mutual insurer, other than a contract of reinsurance, is a member of the insurer, with the rights and obligations of such membership, and each insurance contract so issued shall effectively so stipulate.

. Any person, government or governmental agency, state or political subdivision thereof, public or private corporation, board, association, estate, trustee or fiduciary, may be a member of a mutual insurer.

[ 1947 c 79 § .09.11; Rem. Supp. 1947 § 45.09.11; ]

== 48.09.120 - Rights of members.
. A domestic mutual insurer is owned by and shall be operated in the interest of its members.

. Each member is entitled to one vote in the election of directors and on matters coming before corporate meetings of members, subject to such reasonable minimum requirements as to duration of membership and amount of insurance held as may be made in the insurer's bylaws. The person named as the policyholder in any group insurance policy issued by such insurer shall be deemed the member, and shall have but one such vote regardless of the number of individuals insured by such policy.

. With respect to the management, records, and affairs of the insurer, a member shall have the same character of rights and relationship as a stockholder has toward a domestic stock insurer.

[ 1947 c 79 § .09.12; Rem. Supp. 1947 § 45.09.12; ]

== 48.09.130 - Bylaws.
A domestic mutual insurer shall adopt bylaws for the conduct of its affairs. Such bylaws, or any modification thereof, shall forthwith be filed with the commissioner. The commissioner shall disapprove any such bylaws, or as so modified, if he or she finds after a hearing thereon, that it is not in compliance with the laws of this state, and he or she shall forthwith communicate such disapproval to the insurer. No such bylaw, or modification, so disapproved shall be effective during the existence of such disapproval.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%207036[2009 c 549 § 7036]; 1947 c 79 § .09.13; Rem. Supp. 1947 § 45.09.13; ]

== 48.09.140 - Notice of annual meeting.
. Notice of the time and place of the annual meeting of members of a domestic mutual insurer shall be given by imprinting such notice plainly on the policies issued by the insurer.

. Any change of the date or place of the annual meeting shall be made only by an annual meeting of members. Notice of such change may be given:

.. By imprinting such new date or place on all policies which will be in effect as of the date of such changed meeting; or

.. Unless the commissioner otherwise orders, notice of the new date or place need be given only through policies issued after the date of the annual meeting at which such change was made and in premium notices and renewal certificates issued during the twenty-four months immediately following such meeting.

[ 1947 c 79 § .09.14; Rem. Supp. 1947 § 45.09.14; ]

== 48.09.150 - Voting—Proxies.
. A member of a domestic mutual insurer may vote in person or by proxy given another member on any matter coming before a corporate meeting of members.

. An officer of the insurer shall not hold or vote the proxy of any member.

. No such proxy shall be valid beyond the earlier of the following dates:

.. The date of expiration set forth in the proxy; or

.. the date of termination of membership; or

.. five years from the date of execution of the proxy.

. No member's vote upon any proposal to divest the insurer of its business and assets, or the major part thereof, shall be registered or taken except in person or by a proxy newly executed and specific as to the matter to be voted upon.

[ 1947 c 79 § .09.15; Rem. Supp. 1947 § 45.09.15; ]

== 48.09.160 - Directors—Disqualification.
No individual shall be a director of a domestic mutual insurer by reason of his or her holding public office. Adjudication as a bankrupt or taking the benefit of any insolvency law or making a general assignment for the benefit of creditors disqualifies an individual from being or acting as a director.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%207037[2009 c 549 § 7037]; 1947 c 79 § .09.16; Rem. Supp. 1947 § 45.09.16; ]

== 48.09.180 - Limitation of expenses as to property and casualty insurance.
. For any calendar year after its first two full calendar years of operation, no domestic mutual insurer on the cash premium plan, other than one issuing nonassessable policies, shall incur any costs or expense in the writing or administration of property, disability, and casualty insurances (other than boiler and machinery or elevator) transacted by it which, exclusive of losses paid, loss adjustment expenses, investment expenses, dividends, and taxes exceeds the sum of

.. forty percent of the net premium income during that year after deducting therefrom net earned reinsurance premiums for such year, plus

.. all of the reinsurance commissions received on reinsurance ceded by it.

. The bylaws of every domestic mutual property insurer on the assessment premium plan shall impose a reasonable limitation upon its expenses.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c190.pdf?cite=1949%20c%20190%20§%208[1949 c 190 § 8]; 1947 c 79 § .09.18; Rem. Supp. 1949 § 45.09.18; ]

== 48.09.190 - Procedure upon violation of limitation.
The officers and directors of an insurer violating RCW 48.09.180 shall be jointly and severally liable to the insurer for any excess of expenses incurred. If the insurer fails to exercise reasonable diligence or refuses to enforce such liability, the commissioner may prosecute action thereon for the benefit of the insurer. Such failure or refusal constitutes grounds for revocation of the insurer's certificate of authority.

[ 1947 c 79 § .09.19; Rem. Supp. 1947 § 45.09.19; ]

== 48.09.210 - Limitation of action on officer's salary.
No action to recover, or on account of, any salary or other compensation due or claimed to be due any officer or director of a domestic mutual insurer, or on any note or agreement relative thereto, shall be brought against such insurer after twelve months after the date on which such salary or compensation, or any installment thereof, first accrued.

[ 1947 c 79 § .09.21; Rem. Supp. 1947 § 45.09.21; ]

== 48.09.220 - Contingent liability of members.
. Each member of a domestic mutual insurer, except as otherwise provided in this chapter, shall have a contingent liability, pro rata and not one for another, for the discharge of its obligations. The contingent liability shall be in such maximum amount as is stated in the insurer's articles of incorporation, but shall be not less than one, nor more than five, additional premiums for the member's policy at the annual premium rate and for a term of one year.

. Every policy issued by the insurer shall contain a statement of the contingent liability.

. Termination of the policy of any such member shall not relieve the member of contingent liability for his or her proportion of the obligations of the insurer which accrued while the policy was in force.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%207038[2009 c 549 § 7038]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c190.pdf?cite=1949%20c%20190%20§%209[1949 c 190 § 9]; 1947 c 79 § .09.22; Rem. Supp. 1949 § 45.09.22; ]

== 48.09.230 - Assessment of members.
. If at any time the assets of a domestic mutual insurer doing business on the cash premium plan are less than its liabilities and the minimum surplus, if any, required of it by this code as prerequisite for continuance of its certificate of authority, and the deficiency is not cured from other sources, its directors may, if approved by the commissioner, make an assessment only on its members who at any time within the twelve months immediately preceding the date such assessment was authorized by its directors held policies providing for contingent liability.

. Such an assessment shall be for such an amount of money as is required, in the opinion of the commissioner, to render the insurer fully solvent, but not to result in surplus in excess of five percent of the insurer's liabilities as of the date of the assessment.

. A member's proportionate part of any such assessment shall be computed by applying to the premium earned, during the period since the deficiency first appeared, on his or her contingently liable policy or policies the ratio of the total assessment to the total premium earned during such period on all contingently liable policies which are subject to the assessment.

. No member shall have an offset against any assessment for which he or she is liable on account of any claim for unearned premium or losses payable.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%207039[2009 c 549 § 7039]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c190.pdf?cite=1949%20c%20190%20§%2010[1949 c 190 § 10]; 1947 c 79 § .09.23; Rem. Supp. 1949 § 45.09.23; ]

== 48.09.235 - Issuing a capital call—Notice—Insurer's duties—Rules.
. In addition to authority granted by RCW 48.09.220 and 48.09.230, a domestic mutual insurer meeting all the requirements of this section may increase its surplus by issuing a capital call. A capital call requires policyholders or applicants for insurance to pay a sum, in addition to premium, to be eligible to renew a policy or be issued a new policy. A policyholder that does not pay the amount of a call cannot be canceled or denied the benefits of an existing policy.

. Prior to issuing a capital call, the insurer must have:

.. Adopted articles of incorporation or other organizational documents authorizing capital calls; and

.. For any capital call issued on or after January 1, 2006, included information concerning the insurer's authority to issue a capital call in the policy of every policyholder. This information must be provided at least one full policy renewal cycle prior to a capital call.

. The insurer must notify the commissioner of its intent to issue a capital call at least ninety days prior to the capital call. The notice to the commissioner must include:

.. A statement of each of the following:

... The specific purpose or purposes of the capital call;

... The total amount intended to be raised by issuance of the capital call;

... The amount intended to be raised for each stated purpose;

... The grounds relied upon by the insurer in deciding that the capital call is the best option available to the insurer for raising capital; and

.. Each of the alternative methods of raising capital the insurer considered and the reasons the insurer rejected each alternative in favor of the capital call;

.. For the ten years immediately preceding the filing of the notice, a year by year accounting of:

... All rate filings and actions;

... The total of all underwriting losses; and

... The total amount of dividends paid to policyholders; and

.. A complete application for a solicitation permit as required in RCW 48.06.030.

. Before an insurer may issue a capital call, the insurer must:

.. Notify the commissioner and provide information as required in subsection (3) of this section;

.. Provide any and all additional information that the commissioner may determine is useful or necessary in evaluating the merits of the proposed capital call;

.. Receive approval of the policy or insuring instrument from the commissioner; and

.. Receive approval of the commissioner for the capital call and the solicitation permit.

The commissioner may disapprove a capital call if he or she does not believe it is in the best interest of the insurer, the policyholders, or the citizens of the state of Washington. In making this determination, the commissioner may consider the financial health of the insurer, the impact on the marketplace, the possible use of other means to raise capital, the frequency of previous capital calls by the insurer, the effect of raising premiums instead of a capital call, the impact on state revenue, or any other factor the commissioner deems proper.

. The funds raised by an approved capital call are not premiums for the purposes of RCW 48.14.020.

. The commissioner may adopt rules to implement this section.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2838.SL.pdf?cite=2004%20c%2089%20§%202[2004 c 89 § 2]; ]

== 48.09.240 - Contingent liability of members of assessment insurer.
The contingent liability of members of a domestic mutual insurer doing business on the assessment premium plan shall be called upon and enforced by its directors as provided in its bylaws.

[ 1947 c 79 § .09.24; Rem. Supp. 1947 § 45.09.24; ]

== 48.09.250 - Contingent liability as asset.
Any contingent liability of members of a domestic mutual insurer to assessment does not constitute an asset of the insurer in any determination of its financial condition.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c190.pdf?cite=1949%20c%20190%20§%2011[1949 c 190 § 11]; 1947 c 79 § .09.25; Rem. Supp. 1949 § 45.09.25; ]

== 48.09.260 - Liability as lien on policy reserves.
As to life insurance, any portion of an assessment of contingent liability upon a policyholder which remains unpaid following notice of such assessment, demand for payment, and lapse of a reasonable waiting period as specified in such notice, may, if approved by the commissioner, be secured by placing a lien on the reserves held by the insurer to the credit of such policyholder.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c190.pdf?cite=1949%20c%20190%20§%2012[1949 c 190 § 12]; 1947 c 79 § .09.26; Rem. Supp. 1949 § 45.09.26; ]

== 48.09.270 - Nonassessable policies.
. A domestic mutual insurer on the cash premium plan, after it has established a surplus not less in amount than the minimum capital funds required of a domestic stock insurer to transact like kinds of insurance, and for so long as it maintains such surplus, may extinguish the contingent liability of its members to assessment and omit provisions imposing contingent liability in all policies currently issued.

. Any deposit made with the commissioner as a prerequisite to the insurer's certificate of authority may be included as part of the surplus required in this section.

. When the surplus has been so established and the commissioner has so ascertained, he or she shall issue to the insurer, at its request, his or her certificate authorizing the extinguishment of the contingent liability of its members and the issuance of policies free therefrom.

. While it maintains surplus funds in amount not less than the minimum capital required of a domestic stock insurer authorized to transact like kinds of insurance, and subject to the requirements of *RCW 48.05.360 as to special surplus, a foreign or alien mutual insurer on the cash premium plan may, if consistent with its charter and the laws of its domicile, issue nonassessable policies covering subjects located, resident, or to be performed in this state.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%207040[2009 c 549 § 7040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c195.pdf?cite=1963%20c%20195%20§%204[1963 c 195 § 4]; 1947 c 79 § .09.27; Rem. Supp. 1947 § 45.09.27; ]

== 48.09.280 - Qualification on issuance of nonassessable policies.
The commissioner shall not authorize a domestic mutual insurer so to extinguish the contingent liability of any of its members or in any of its policies to be issued, unless it qualifies to and does extinguish such liability of all its members and in all such policies for all kinds of insurance transacted by it. Except, that if required by the laws of another state in which such an insurer is transacting insurance as an authorized insurer, the insurer may issue policies providing for the contingent liability of such of its members as may acquire such policies in such state, and need not extinguish the contingent liability applicable to policies theretofore in force in such state.

[ 1947 c 79 § .09.28; Rem. Supp. 1947 § 45.09.28; ]

== 48.09.290 - Revocation of right to issue nonassessable policies.
. The commissioner shall revoke the authority of a domestic mutual insurer so to extinguish the contingent liability of its members if

.. at any time the insurer's assets are less than the sum of its liabilities and the surplus required for such authority, or

.. the insurer, by resolution of its directors approved by its members, requests that the authority be revoked.

. Upon revocation of such authority for any cause, the insurer shall not thereafter issue any policies without contingent liability, nor renew any policies then in force without written endorsement thereon providing for contingent liability.

[ 1947 c 79 § .09.29; Rem. Supp. 1947 § 45.09.29; ]

== 48.09.300 - Dividends.
. The directors of a domestic mutual insurer on the cash premium plan may from time to time apportion and pay to its members as entitled thereto, dividends only out of that part of its surplus funds which are in excess of its required minimum surplus and which represent net realized savings and net realized earnings from its business.

. Any classification of its participating policies and of risks assumed thereunder which the insurer may make shall be reasonable. No dividend shall be paid which is inequitable, or which unfairly discriminates as between such classifications or as between policies within the same classification.

. No dividend, otherwise earned, shall be made contingent upon the payment of renewal premium on any policy.

[ 1947 c 79 § .09.30; Rem. Supp. 1947 § 45.09.30; ]

== 48.09.310 - Nonparticipating policies.
. If its articles of incorporation so provide, a domestic mutual insurer on the cash premium plan may, while it is authorized to issue policies without contingent liability to assessment, issue policies not entitled to participate in the insurer's savings and earnings.

. Such insurer shall not issue in this state both participating and nonparticipating policies for the same class of risks; except, that both participating and nonparticipating life insurance policies may be issued if the right or absence of the right to participate is reasonably related to the premium charged.

[ 1947 c 79 § .09.31; Rem. Supp. 1947 § 45.09.31; ]

== 48.09.320 - Borrowed capital.
. A domestic mutual insurer may, with the commissioner's advance approval and without the pledge of any of its assets, borrow money to defray the expenses of its organization or for any purpose required by its business, upon an agreement that such money and such fair and reasonable interest thereon as may be agreed upon, shall be repaid only out of the insurer's earned surplus in excess of its required minimum surplus.

. An insurer borrowing funds under this section must comply with the national association of insurance commissioner's - accounting practices and procedures manual which sets forth requirements for borrowed money to be treated as surplus notes for financial accounting purposes.

. The commissioner's approval of such borrowed funds, if granted, shall specify the amount to be borrowed, the purpose for which the money is to be used, the terms and form of the loan agreement, the date by which the loan must be completed, fair and reasonable commissions or promotional expenses to be incurred or to be paid, and such other related matters as the commissioner shall deem proper. If the money is to be borrowed upon multiple agreements, the agreements shall be serially numbered. No loan agreement or series thereof shall have or be given any preferential rights over any other such loan agreement or series.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1654.SL.pdf?cite=2003%20c%20249%20§%201[2003 c 249 § 1]; 1947 c 79 § .09.32; Rem. Supp. 1947 § 45.09.32; ]

== 48.09.330 - Repayment of borrowed capital.
. The insurer may repay any loan received pursuant to RCW 48.09.320, or any part thereof as approved by the commissioner, only out of its funds which represent such loan or realized net earned surplus. No repayment shall be made which reduces the insurer's surplus below the minimum surplus required for the kinds of insurance transacted.

. The insurer shall repay any such loan or the largest possible part thereof when the purposes for which such funds were borrowed have been fulfilled and when the insurer's surplus is adequate to so repay without unreasonable impairment of the insurer's operations.

. No repayment of such loan shall be made unless approved by the commissioner. The insurer shall notify the commissioner in writing not less than sixty days in advance of its intention to repay such loan or any part thereof, and the commissioner shall forthwith ascertain whether the insurer's financial condition is such that the repayment can properly be made.

. Upon dissolution and liquidation of the insurer, after the retirement of all its other outstanding obligations the holders of any such loan agreements then remaining unpaid shall be entitled to payment before any distribution of surplus is made to the insurer's members.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c190.pdf?cite=1949%20c%20190%20§%2013[1949 c 190 § 13]; 1947 c 79 § .09.33; Rem. Supp. 1949 § 45.09.33; ]

== 48.09.340 - Impairment of surplus.
. If the assets of a domestic mutual insurer on the cash premium plan fall below the amount of its liabilities, plus the amount of any surplus required by this code for the kinds of insurance authorized to be transacted, the commissioner shall at once ascertain the amount of the deficiency and serve notice upon the insurer to cure the deficiency within ninety days after such service of notice.

. If the deficiency is not made good in cash or in assets eligible under this code for the investment of the insurer's funds, and proof thereof filed with the commissioner within such ninety-day period, the insurer shall be deemed insolvent and shall be proceeded against as authorized by this code.

. If the deficiency is not made good the insurer shall not issue or deliver any policy after the expiration of such ninety-day period. Any officer or director who violates or knowingly permits the violating of this provision shall be subject to a fine of from fifty dollars to one thousand dollars for each violation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c190.pdf?cite=1949%20c%20190%20§%2014[1949 c 190 § 14]; 1947 c 79 § 09.34; Rem. Supp. 1949 § 45.09.34; ]

== 48.09.350 - Reorganization of mutual as stock insurer—Reinsurance—Approval.
. Upon satisfaction of the requirements applicable to the formation of a domestic stock insurer, a domestic mutual insurer may be reorganized as a stock corporation, pursuant to a plan of reorganization as approved by the commissioner.

. A domestic mutual insurer may be wholly reinsured in and its assets transferred to and its liabilities assumed by another mutual or stock insurer under such terms and conditions as are approved by the commissioner in advance of such reinsurance.

. The commissioner shall not approve any such reorganization plan or reinsurance agreement which does not determine the amount of and make adequate provision for paying to members of such mutual insurer, reasonable compensation for their equities as owners of such insurer, such compensation to be apportioned to members as identified and in the manner prescribed in RCW 48.09.360. The procedure for approval by the commissioner of any such reorganization plan or reinsurance agreement shall be the same as the procedure for approval by the commissioner of a plan of merger or consolidation under RCW 48.31.010.

Approval at a corporate meeting of members by two-thirds of the then members of a domestic mutual insurer who vote on the plan or agreement pursuant to such notice and procedure as was approved by the commissioner shall constitute approval of any such reorganization plan or reinsurance agreement by the insurer's members.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c23.pdf?cite=1984%20c%2023%20§%201[1984 c 23 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c32.pdf?cite=1983%201st%20ex.s.%20c%2032%20§%201[1983 1st ex.s. c 32 § 1]; 1947 c 79 § .09.35; Rem. Supp. 1947 § 45.09.35; ]

== 48.09.360 - Distribution of assets and ownership equities upon liquidation.
. Upon the liquidation of a domestic mutual insurer, its assets remaining after discharge of its indebtedness and policy obligations shall be distributed to its members who were such within the thirty-six months prior to the last termination of its certificate of authority.

. Upon the reorganization of a domestic mutual insurer as a domestic stock insurer under RCW 48.09.350(1) or upon reinsurance of the whole of the liabilities and transfer of all the assets of a domestic mutual insurer under RCW 48.09.350(2), the ownership equities of members of the domestic mutual insurer shall be distributed to its members who were such on an eligibility date stated in the reorganization plan or reinsurance agreement, or who were such within the thirty-six months prior to such eligibility date. Such eligibility date shall be either the date on which the reorganization plan or reinsurance agreement is adopted by resolution of the board of directors of the domestic mutual insurer, or the date on which the reorganization plan or reinsurance agreement is approved by a vote of the members, or the date which ends a calendar quarter during which either of such actions is taken.

. Upon the liquidation of a domestic mutual insurer, the distributive share of each such member shall be in the proportion that the aggregate premiums earned by the insurer on the policies of the member during the thirty-six months before the last termination of the insurer's certificate of authority, bear to the aggregate of all premiums so earned on the policies of all such members during the same thirty-six months.

. Upon the reorganization of a domestic mutual insurer as a domestic stock insurer under RCW 48.09.350(1) or upon reinsurance of the whole of the liabilities and transfer of all the assets of a domestic mutual insurer under RCW 48.09.350(2), the distributive share of each member entitled thereto shall be in the proportion that the aggregate premiums earned by the insurer on the policies in force of that member during the thirty-six months before the eligibility date established under RCW 48.09.360(2) bear to the aggregate of all premiums so earned during the same thirty-six months on all the policies in force of all such members who are entitled to a distributive share.

. If a life insurer, the insurer shall make a reasonable classification of its life insurance policies so held by such members entitled to a distributive share and a formula based upon such classification for determining the equitable distributive share of each such member. Such classification and formula shall be subject to the commissioner's approval.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c23.pdf?cite=1984%20c%2023%20§%202[1984 c 23 § 2]; 1947 c 79 § .09.36; Rem. Supp. 1947 § 45.09.36; ]

