= 48.41 - Health insurance coverage access act.
:toc:

== 48.41.010 - Short title.
This chapter shall be known and may be cited as the "Washington state health insurance coverage access act".

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c431.pdf?cite=1987%20c%20431%20§%201[1987 c 431 § 1]; ]

== 48.41.020 - Intent.
It is the purpose and intent of the legislature to provide access to health insurance coverage to all residents of Washington who are denied health insurance. It is the intent of the Washington state health insurance coverage access act to provide a mechanism to ensure the availability of comprehensive health insurance to persons unable to obtain such insurance coverage on either an individual or group basis directly under any health plan.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6067-S2.SL.pdf?cite=2000%20c%2079%20§%205[2000 c 79 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c431.pdf?cite=1987%20c%20431%20§%202[1987 c 431 § 2]; ]

== 48.41.030 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Accounting year" means a twelve-month period determined by the board for purposes of recordkeeping and accounting. The first accounting year may be more or less than twelve months and, from time to time in subsequent years, the board may order an accounting year of other than twelve months as may be required for orderly management and accounting of the pool.

. "Administrator" means the entity chosen by the board to administer the pool under RCW 48.41.080.

. "Board" means the board of directors of the pool.

. "Commissioner" means the insurance commissioner.

. "Covered person" means any individual resident of this state who is eligible to receive benefits from any member, or other health plan.

. "Health care facility" has the same meaning as in RCW 70.38.025.

. "Health care provider" means any physician, facility, or health care professional, who is licensed in Washington state and entitled to reimbursement for health care services.

. "Health care services" means services for the purpose of preventing, alleviating, curing, or healing human illness or injury.

. "Health carrier" or "carrier" has the same meaning as in RCW 48.43.005.

. "Health coverage" means any group or individual disability insurance policy, health care service contract, and health maintenance agreement, except those contracts entered into for the provision of health care services pursuant to Title XVIII of the Social Security Act, 42 U.S.C. Sec. 1395 et seq. The term does not include short-term care, long-term care, dental, vision, accident, fixed indemnity, disability income contracts, limited benefit or credit insurance, coverage issued as a supplement to liability insurance, insurance arising out of the worker's compensation or similar law, automobile medical payment insurance, or insurance under which benefits are payable with or without regard to fault and which is statutorily required to be contained in any liability insurance policy or equivalent self-insurance.

. "Health plan" means any arrangement by which persons, including dependents or spouses, covered or making application to be covered under this pool, have access to hospital and medical benefits or reimbursement including any group or individual disability insurance policy; health care service contract; health maintenance agreement; uninsured arrangements of group or group-type contracts including employer self-insured, cost-plus, or other benefit methodologies not involving insurance or not governed by Title 48 RCW; coverage under group-type contracts which are not available to the general public and can be obtained only because of connection with a particular organization or group; and coverage by medicare or other governmental benefits. This term includes coverage through "health coverage" as defined under this section, and specifically excludes those types of programs excluded under the definition of "health coverage" in subsection (10) of this section.

. "Medical assistance" means coverage under Title XIX of the federal Social Security Act (42 U.S.C., Sec. 1396 et seq.) and chapter 74.09 RCW.

. "Medicare" means coverage under Title XVIII of the Social Security Act, (42 U.S.C. Sec. 1395 et seq., as amended).

. "Member" means any commercial insurer which provides disability insurance or stop loss insurance, any health care service contractor, any health maintenance organization licensed under Title 48 RCW, and any self-funded multiple employer welfare arrangement as defined in RCW 48.125.010. "Member" also means the Washington state health care authority as issuer of the state uniform medical plan. "Member" shall also mean, as soon as authorized by federal law, employers and other entities, including a self-funding entity and employee welfare benefit plans that provide health plan benefits in this state on or after May 18, 1987. "Member" does not include any insurer, health care service contractor, or health maintenance organization whose products are exclusively dental products or those products excluded from the definition of "health coverage" set forth in subsection (10) of this section.

. "Network provider" means a health care provider who has contracted in writing with the pool administrator or a health carrier contracting with the pool administrator to offer pool coverage to accept payment from and to look solely to the pool or health carrier according to the terms of the pool health plans.

. "Plan of operation" means the pool, including articles, bylaws, and operating rules, adopted by the board pursuant to RCW 48.41.050.

. "Point of service plan" means a benefit plan offered by the pool under which a covered person may elect to receive covered services from network providers, or nonnetwork providers at a reduced rate of benefits.

. "Pool" means the Washington state health insurance pool as created in RCW 48.41.040.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6112-S.SL.pdf?cite=2004%20c%20260%20§%2025[2004 c 260 § 25]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1633.SL.pdf?cite=2001%20c%20196%20§%202[2001 c 196 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6067-S2.SL.pdf?cite=2000%20c%2079%20§%206[2000 c 79 § 6]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2279-S.SL.pdf?cite=1997%20c%20337%20§%206[1997 c 337 § 6]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2018-S.SL.pdf?cite=1997%20c%20231%20§%20210[1997 c 231 § 210]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c121.pdf?cite=1989%20c%20121%20§%201[1989 c 121 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c431.pdf?cite=1987%20c%20431%20§%203[1987 c 431 § 3]; ]

== 48.41.037 - Washington state health insurance pool account.
The Washington state health insurance pool account is created in the custody of the state treasurer. All receipts from moneys specifically appropriated to the account must be deposited in the account. Expenditures from this account shall be used to cover deficits incurred by the Washington state health insurance pool under this chapter in excess of the threshold established in this section. To the extent funds are available in the account, funds shall be expended from the account to offset that portion of the deficit that would otherwise have to be recovered by imposing an assessment on members in excess of a threshold of seventy cents per insured person per month. The commissioner shall authorize expenditures from the account, to the extent that funds are available in the account, upon certification by the pool board that assessments will exceed the threshold level established in this section. The account is subject to the allotment procedures under chapter 43.88 RCW, but an appropriation is not required for expenditures.

Whether the assessment has reached the threshold of seventy cents per insured person per month shall be determined by dividing the total aggregate amount of assessment by the proportion of total assessed members. Thus, stop loss members shall be counted as one-tenth of a whole member in the denominator given that is the amount they are assessed proportionately relative to a fully insured medical member.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5930-S2.SL.pdf?cite=2007%20c%20259%20§%2029[2007 c 259 § 29]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6067-S2.SL.pdf?cite=2000%20c%2079%20§%2036[2000 c 79 § 36]; ]

== 48.41.040 - Health insurance pool—Creation, membership, organization, operation, rules.
. There is created a nonprofit entity to be known as the Washington state health insurance pool. All members in this state on or after May 18, 1987, shall be members of the pool. When authorized by federal law, all self-insured employers shall also be members of the pool.

. Pursuant to chapter 34.05 RCW the commissioner shall, within ninety days after May 18, 1987, give notice to all members of the time and place for the initial organizational meetings of the pool. A board of directors shall be established, which shall be comprised of ten members. The governor shall select one member of the board from each list of three nominees submitted by statewide organizations representing each of the following: (a) Health care providers; (b) health insurance agents; (c) small employers; and (d) large employers. The governor shall select two members of the board from a list of nominees submitted by statewide organizations representing health care consumers. In making these selections, the governor may request additional names from the statewide organizations representing each of the persons to be selected if the governor chooses not to select a member from the list submitted. The remaining four members of the board shall be selected by election from among the members of the pool. The elected members shall, to the extent possible, include at least one representative of health care service contractors, one representative of health maintenance organizations, and one representative of commercial insurers which provides disability insurance. The members of the board shall elect a chair from the voting members of the board. The insurance commissioner shall be a nonvoting, ex officio member. When self-insured organizations other than the Washington state health care authority become eligible for participation in the pool, the membership of the board shall be increased to eleven and at least one member of the board shall represent the self-insurers.

. The original members of the board of directors shall be appointed for intervals of one to three years. Thereafter, all board members shall serve a term of three years. Board members shall receive no compensation, but shall be reimbursed for all travel expenses as provided in RCW 43.03.050 and 43.03.060.

. The board shall submit to the commissioner a plan of operation for the pool and any amendments thereto necessary or suitable to assure the fair, reasonable, and equitable administration of the pool. The commissioner shall, after notice and hearing pursuant to chapter 34.05 RCW, approve the plan of operation if it is determined to assure the fair, reasonable, and equitable administration of the pool and provides for the sharing of pool losses on an equitable, proportionate basis among the members of the pool. The plan of operation shall become effective upon approval in writing by the commissioner consistent with the date on which the coverage under this chapter must be made available. If the board fails to submit a plan of operation within one hundred eighty days after the appointment of the board or any time thereafter fails to submit acceptable amendments to the plan, the commissioner shall, within ninety days after notice and hearing pursuant to chapters 34.05 and 48.04 RCW, adopt such rules as are necessary or advisable to effectuate this chapter. The rules shall continue in force until modified by the commissioner or superseded by a plan submitted by the board and approved by the commissioner.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/3154.SL.pdf?cite=2000%20c%2080%20§%201[2000 c 80 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6067-S2.SL.pdf?cite=2000%20c%2079%20§%207[2000 c 79 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c121.pdf?cite=1989%20c%20121%20§%202[1989 c 121 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c431.pdf?cite=1987%20c%20431%20§%204[1987 c 431 § 4]; ]

== 48.41.050 - Operation plan—Contents.
The plan of operation submitted by the board to the commissioner shall:

. Establish procedures for the handling and accounting of assets and moneys of the pool;

. Establish regular times and places for meetings of the board of directors;

. Establish procedures for records to be kept of all financial transactions and for an annual fiscal reporting to the commissioner;

. Contain additional provisions necessary and proper for the execution of the powers and duties of the pool;

. Establish procedures for the collection of assessments from all members to provide for claims paid under the plan and for administrative expenses incurred or estimated to be incurred during the period for which the assessment is made;

. Establish the amount of assessment pursuant to RCW 48.41.060, which shall occur after March 1st of each calendar year, and which shall be due and payable within thirty days of the receipt of the assessment notice;

. Select an administrator in accordance with RCW 48.41.080; 

. Develop and implement a program to publicize the existence of the plan, the eligibility requirements and procedures for enrollment, and to maintain public awareness of the plan; and

. Establish procedures under which applicants and participants may have grievances reviewed by an impartial body and reported to the board.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c431.pdf?cite=1987%20c%20431%20§%205[1987 c 431 § 5]; ]

== 48.41.060 - Board powers and duties.
. The board shall have the general powers and authority granted under the laws of this state to insurance companies, health care service contractors, and health maintenance organizations, licensed or registered to offer or provide the kinds of health coverage defined under this title. In addition thereto, the board shall:

.. Establish appropriate rates, rate schedules, rate adjustments, expense allowances, claim reserve formulas and any other actuarial functions appropriate to the operation of the pool. Rates shall not be unreasonable in relation to the coverage provided, the risk experience, and expenses of providing the coverage. Rates and rate schedules may be adjusted for appropriate risk factors such as age and area variation in claim costs and shall take into consideration appropriate risk factors in accordance with established actuarial underwriting practices consistent with Washington state individual plan rating requirements under RCW 48.44.022 and 48.46.064;

.. [Empty]
... Assess members of the pool in accordance with the provisions of this chapter, and make advance interim assessments as may be reasonable and necessary for the organizational or interim operating expenses. Any interim assessments will be credited as offsets against any regular assessments due following the close of the year.

... Self-funded multiple employer welfare arrangements are subject to assessment under this subsection only in the event that assessments are not preempted by the employee retirement income security act of 1974, as amended, 29 U.S.C. Sec. 1001 et seq. The arrangements and the commissioner shall initially request an advisory opinion from the United States department of labor or obtain a declaratory ruling from a federal court on the legality of imposing assessments on these arrangements before imposing the assessment. Once the legality of the assessments has been determined, the multiple employer welfare arrangement certified by the insurance commissioner must begin payment of these assessments.

... If there has not been a final determination of the legality of these assessments, then beginning on the earlier of (A) the date the fourth multiple employer welfare arrangement has been certified by the insurance commissioner, or (B) April 1, 2006, the arrangement shall deposit the assessments imposed by this subsection into an interest bearing escrow account maintained by the arrangement. Upon a final determination that the assessments are not preempted by the employee retirement income security act of 1974, as amended, 29 U.S.C. Sec. 1001 et seq., all funds in the interest bearing escrow account shall be transferred to the board;

.. Issue policies of health coverage in accordance with the requirements of this chapter;

.. Establish procedures for the administration of the premium discount provided under RCW 48.41.200(3)(a)(iii);

.. Contract with the Washington state health care authority for the administration of the premium discounts provided under RCW 48.41.200(3)(a) (i) and (ii);

.. Set a reasonable fee to be paid to an insurance producer licensed in Washington state for submitting an acceptable application for enrollment in the pool; and

.. Provide certification to the commissioner when assessments will exceed the threshold level established in RCW 48.41.037.

. In addition thereto, the board may:

.. Enter into contracts as are necessary or proper to carry out the provisions and purposes of this chapter including the authority, with the approval of the commissioner, to enter into contracts with similar pools of other states for the joint performance of common administrative functions, or with persons or other organizations for the performance of administrative functions;

.. Sue or be sued, including taking any legal action as necessary to avoid the payment of improper claims against the pool or the coverage provided by or through the pool;

.. Appoint appropriate legal, actuarial, and other committees as necessary to provide technical assistance in the operation of the pool, policy, and other contract design, and any other function within the authority of the pool; and

.. Conduct periodic audits to assure the general accuracy of the financial data submitted to the pool, and the board shall cause the pool to have an annual audit of its operations by an independent certified public accountant.

. Nothing in this section shall be construed to require or authorize the adoption of rules under chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5449-S.SL.pdf?cite=2013%20c%20279%20§%202[2013 c 279 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5122-S.SL.pdf?cite=2011%20c%20314%20§%2013[2011 c 314 § 13]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5777-S.SL.pdf?cite=2009%20c%20555%20§%202[2009 c 555 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6591.SL.pdf?cite=2008%20c%20217%20§%2047[2008 c 217 § 47]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5957.SL.pdf?cite=2005%20c%207%20§%202[2005 c 7 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6112-S.SL.pdf?cite=2004%20c%20260%20§%2026[2004 c 260 § 26]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6067-S2.SL.pdf?cite=2000%20c%2079%20§%209[2000 c 79 § 9]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2279-S.SL.pdf?cite=1997%20c%20337%20§%205[1997 c 337 § 5]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2018-S.SL.pdf?cite=1997%20c%20231%20§%20211[1997 c 231 § 211]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c121.pdf?cite=1989%20c%20121%20§%203[1989 c 121 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c431.pdf?cite=1987%20c%20431%20§%206[1987 c 431 § 6]; ]

== 48.41.070 - Examination and report.
The pool shall be subject to examination by the commissioner as provided under chapter 48.03 RCW. The board of directors shall submit to the commissioner, not later than one hundred twenty days after the end of each accounting year, a financial report for the year in a form approved by the commissioner.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%2098[1998 c 245 § 98]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c121.pdf?cite=1989%20c%20121%20§%204[1989 c 121 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c431.pdf?cite=1987%20c%20431%20§%207[1987 c 431 § 7]; ]

== 48.41.080 - Pool administrator—Selection, term, duties, pay.
The board shall select an administrator through a competitive bidding process to administer the pool.

. The board shall evaluate bids based upon criteria established by the board, which shall include:

.. The administrator's proven ability to handle health coverage;

.. The efficiency of the administrator's claim-paying procedures;

.. An estimate of the total charges for administering the plan; and

.. The administrator's ability to administer the pool in a cost-effective manner.

. The administrator shall serve for a period of three years subject to removal for cause. At least six months prior to the expiration of each three-year period of service by the administrator, the board shall invite all interested parties, including the current administrator, to submit bids to serve as the administrator for the succeeding three-year period. Selection of the administrator for this succeeding period shall be made at least three months prior to the end of the current three-year period, unless at the time required for submission of bids pursuant to this subsection to the pool will be discontinued before the end of the succeeding thirty-six month period.

. The administrator shall perform such duties as may be assigned by the board including:

.. Administering eligibility and administrative claim payment functions relating to the pool;

.. Establishing a premium billing procedure for collection of premiums from covered persons. Billings shall be made on a periodic basis as determined by the board, which shall not be more frequent than a monthly billing;

.. Performing all necessary functions to assure timely payment of benefits to covered persons under the pool including:

... Making available information relating to the proper manner of submitting a claim for benefits to the pool, and distributing forms upon which submission shall be made;

... Taking steps necessary to offer and administer managed care benefit plans; and

... Evaluating the eligibility of each claim for payment by the pool;

.. Submission of regular reports to the board regarding the operation of the pool. The frequency, content, and form of the report shall be as determined by the board;

.. Following the close of each accounting year, determination of net paid and earned premiums, the expense of administration, and the paid and incurred losses for the year and reporting this information to the board and the commissioner on a form as prescribed by the commissioner.

. The administrator shall be paid as provided in the contract between the board and the administrator for its expenses incurred in the performance of its services.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5122-S.SL.pdf?cite=2011%20c%20314%20§%2014[2011 c 314 § 14]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6067-S2.SL.pdf?cite=2000%20c%2079%20§%2010[2000 c 79 § 10]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2018-S.SL.pdf?cite=1997%20c%20231%20§%20212[1997 c 231 § 212]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c121.pdf?cite=1989%20c%20121%20§%205[1989 c 121 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c431.pdf?cite=1987%20c%20431%20§%208[1987 c 431 § 8]; ]

== 48.41.090 - Financial participation in pool—Computation, deficit assessments.
. Following the close of each accounting year, the pool administrator shall determine the total net cost of pool operation which shall include:

.. Net premium (premiums less administrative expense allowances), the pool expenses of administration, and incurred losses for the year, taking into account investment income and other appropriate gains and losses; and

.. The amount of pool contributions specified in the state omnibus appropriations act for deposit into the health benefit exchange account under RCW 43.71.060, to assist with the transition of enrollees from the pool into the health benefit exchange created by chapter 43.71 RCW.

. [Empty]
.. Each member's proportion of participation in the pool shall be determined annually by the board based on annual statements and other reports deemed necessary by the board and filed by the member with the commissioner; and shall be determined by multiplying the total cost of pool operation by a fraction. The numerator of the fraction equals that member's total number of resident insured persons, including spouse and dependents, covered under all health plans in the state by that member during the preceding calendar year. The denominator of the fraction equals the total number of resident insured persons, including spouses and dependents, covered under all health plans in the state by all pool members during the preceding calendar year.

.. For purposes of calculating the numerator and the denominator under (a) of this subsection:

... All health plans in the state by the state health care authority include only the uniform medical plan;

... Each ten resident insured persons, including spouse and dependents, under a stop loss plan or the uniform medical plan shall count as one resident insured person;

... Health plans serving medical care services program clients under RCW 74.09.035 are exempted from the calculation; and

... Health plans established to serve elderly clients or medicaid clients with disabilities under chapter 74.09 RCW when the plan has been implemented on a demonstration or pilot project basis are exempted from the calculation until July 1, 2009.

.. Except as provided in RCW 48.41.037, any deficit incurred by the pool, including pool contributions for deposit into the health benefit exchange account, shall be recouped by assessments among members apportioned under this subsection pursuant to the formula set forth by the board among members. The monthly per member assessment may not exceed the 2013 assessment level. If the maximum assessment is insufficient to cover a pool deficit the assessment shall be used first to pay all incurred losses and pool administrative expenses, with the remainder being available for deposit in the health benefit exchange account.

. The board may abate or defer, in whole or in part, the assessment of a member if, in the opinion of the board, payment of the assessment would endanger the ability of the member to fulfill its contractual obligations. If an assessment against a member is abated or deferred in whole or in part, the amount by which such assessment is abated or deferred may be assessed against the other members in a manner consistent with the basis for assessments set forth in subsection (2) of this section. The member receiving such abatement or deferment shall remain liable to the pool for the deficiency.

. Subject to the limitation imposed in subsection (2)(c) of this section, the pool administrator shall transfer the assessments for pool contributions for the operation of the health benefit exchange to the treasurer for deposit into the health benefit exchange account with the quarterly assessments for 2014 as specified in the state omnibus appropriations act. If assessments exceed actual losses and administrative expenses of the pool and pool contributions for deposit into the health benefit exchange account, the excess shall be held at interest and used by the board to offset future losses or to reduce pool premiums. As used in this subsection, "future losses" includes reserves for incurred but not reported claims.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1947-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%206%20§%207[2013 2nd sp.s. c 6 § 7]; 2018 c 219 § 4; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1690.SL.pdf?cite=2005%20c%20405%20§%202[2005 c 405 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6067-S2.SL.pdf?cite=2000%20c%2079%20§%2011[2000 c 79 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c121.pdf?cite=1989%20c%20121%20§%206[1989 c 121 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c431.pdf?cite=1987%20c%20431%20§%209[1987 c 431 § 9]; ]

== 48.41.100 - Eligibility for coverage.
. [Empty]
.. The following persons who are residents of this state are eligible for pool coverage:

... Any resident of the state not eligible for medicare coverage or medicaid coverage, and residing in a county where an individual health plan other than a catastrophic health plan as defined in RCW 48.43.005 is not offered to the resident during defined open enrollment or special enrollment periods at the time of application to the pool, whether through the health benefit exchange operated pursuant to chapter 43.71 RCW or in the private insurance market;

... Any resident of the state not eligible for medicare coverage, enrolled in the pool prior to December 31, 2013, shall remain eligible for pool coverage except as provided in subsections (2) and (3) of this section;

... Any person becoming eligible for medicare before August 1, 2009, who provides evidence of (A) a rejection for medical reasons, (B) a requirement of restrictive riders, (C) an up-rated premium, (D) a preexisting conditions limitation, or (E) lack of access to or for a comprehensive medicare supplemental insurance policy under chapter 48.66 RCW, the effect of any of which is to substantially reduce coverage from that received by a person considered a standard risk by at least one member within six months of the date of application; and

... Any person becoming eligible for medicare on or after August 1, 2009, who does not have access to a reasonable choice of comprehensive medicare part C plans, as defined in (b) of this subsection, and who provides evidence of (A) a rejection for medical reasons, (B) a requirement of restrictive riders, (C) an up-rated premium, (D) a preexisting conditions limitation, or (E) lack of access to or for a comprehensive medicare supplemental insurance policy under chapter 48.66 RCW, the effect of any of which is to substantially reduce coverage from that received by a person considered a standard risk by at least one member within six months of the date of application.

.. For purposes of (a)(i) of this subsection, by December 1, 2013, the board shall develop and implement a process to determine an applicant's eligibility based on the criteria specified in (a)(i) of this subsection.

.. For purposes of (a)(iv) of this subsection (1), a person does not have access to a reasonable choice of plans unless the person has a choice of health maintenance organization or preferred provider organization medicare part C plans offered by at least three different carriers that have had provider networks in the person's county of residence for at least five years. The plan options must include coverage at least as comprehensive as a plan F medicare supplement plan combined with medicare parts A and B. The plan options must also provide access to adequate and stable provider networks that make up-to-date provider directories easily accessible on the carrier website, and will provide them in hard copy, if requested. In addition, if no health maintenance organization or preferred provider organization plan includes the health care provider with whom the person has an established care relationship and from whom he or she has received treatment within the past twelve months, the person does not have reasonable access.

. The following persons are not eligible for coverage by the pool:

.. Any person having terminated coverage in the pool unless (i) twelve months have lapsed since termination, or (ii) that person can show continuous other coverage which has been involuntarily terminated for any reason other than nonpayment of premiums. However, these exclusions do not apply to eligible individuals as defined in section 2741(b) of the federal health insurance portability and accountability act of 1996 (42 U.S.C. Sec. 300gg-41(b));

.. Inmates of public institutions and those persons who become eligible for medical assistance after June 30, 2008, as defined in RCW 74.09.010. However, these exclusions do not apply to eligible individuals as defined in section 2741(b) of the federal health insurance portability and accountability act of 1996 (42 U.S.C. Sec. 300gg-41(b)).

. When a carrier or insurer regulated under chapter 48.15 RCW begins to offer an individual health benefit plan in a county where no carrier had been offering an individual health benefit plan:

.. If the health benefit plan offered is other than a catastrophic health plan as defined in RCW 48.43.005, any person enrolled in a pool plan pursuant to subsection (1)(a)(i) of this section in that county shall no longer be eligible for coverage under that plan pursuant to subsection (1)(a)(i) of this section; and

.. The pool administrator shall provide written notice to any person who is no longer eligible for coverage under a pool plan under this subsection (3) within thirty days of the administrator's determination that the person is no longer eligible. The notice shall: (i) Indicate that coverage under the plan will cease ninety days from the date that the notice is dated; (ii) describe any other coverage options, either in or outside of the pool, available to the person; and (iii) describe the enrollment process for the available options outside of the pool.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1096.SL.pdf?cite=2021%20c%2060%20§%201[2021 c 60 § 1]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1338-S2.SL.pdf?cite=2017%20c%20110%20§%202[2017 c 110 § 2]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5449-S.SL.pdf?cite=2013%20c%20279%20§%203[2013 c 279 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5371-S.SL.pdf?cite=2011%20c%20315%20§%205[2011 c 315 § 5]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5122-S.SL.pdf?cite=2011%20c%20314%20§%2015[2011 c 314 § 15]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5777-S.SL.pdf?cite=2009%20c%20555%20§%203[2009 c 555 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5930-S2.SL.pdf?cite=2007%20c%20259%20§%2030[2007 c 259 § 30]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1633.SL.pdf?cite=2001%20c%20196%20§%203[2001 c 196 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6067-S2.SL.pdf?cite=2000%20c%2079%20§%2012[2000 c 79 § 12]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5419-S.SL.pdf?cite=1995%20c%2034%20§%205[1995 c 34 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c121.pdf?cite=1989%20c%20121%20§%207[1989 c 121 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c431.pdf?cite=1987%20c%20431%20§%2010[1987 c 431 § 10]; ]

== 48.41.110 - Policy coverage—Eligible expenses, cost containment, limits—Explanatory brochure.
. The pool shall offer one or more care management plans of coverage. Such plans may, but are not required to, include point of service features that permit participants to receive in-network benefits or out-of-network benefits subject to differential cost shares. The pool may incorporate managed care features into existing plans.

. The administrator shall prepare a brochure outlining the benefits and exclusions of pool policies in plain language. After approval by the board, such brochure shall be made reasonably available to participants or potential participants.

. The health insurance policies issued by the pool shall pay only reasonable amounts for medically necessary eligible health care services rendered or furnished for the diagnosis or treatment of covered illnesses, injuries, and conditions. Eligible expenses are the reasonable amounts for the health care services and items for which benefits are extended under a pool policy.

. The pool shall offer at least two policies, one of which will be a comprehensive policy that must comply with RCW 48.41.120 and must at a minimum include the following services or related items:

.. Hospital services, including charges for the most common semiprivate room, for the most common private room if semiprivate rooms do not exist in the health care facility, or for the private room if medically necessary, including no less than a total of one hundred eighty inpatient days in a calendar year, and no less than thirty days inpatient care for alcohol, drug, or chemical dependency or abuse per calendar year;

.. Professional services including surgery for the treatment of injuries, illnesses, or conditions, other than dental, which are rendered by a health care provider, or at the direction of a health care provider, by a staff of registered or licensed practical nurses, or other health care providers;

.. No less than twenty outpatient professional visits for the diagnosis or treatment of alcohol, drug, or chemical dependency or abuse rendered during a calendar year by a state-certified chemical dependency program approved under *chapter 70.96A RCW, or by one or more physicians, psychologists, or community mental health professionals, or, at the direction of a physician, by other qualified licensed health care practitioners;

.. Drugs and contraceptive devices requiring a prescription;

.. Services of a skilled nursing facility, excluding custodial and convalescent care, for not less than one hundred days in a calendar year as prescribed by a physician;

.. Services of a home health agency;

.. Chemotherapy, radioisotope, radiation, and nuclear medicine therapy;

.. Oxygen;

.. Anesthesia services;

.. Prostheses, other than dental;

.. Durable medical equipment which has no personal use in the absence of the condition for which prescribed;

.. Diagnostic x-rays and laboratory tests;

.. Oral surgery including at least the following: Fractures of facial bones; excisions of mandibular joints, lesions of the mouth, lip, or tongue, tumors, or cysts excluding treatment for temporomandibular joints; incision of accessory sinuses, mouth salivary glands or ducts; dislocations of the jaw; plastic reconstruction or repair of traumatic injuries occurring while covered under the pool; and excision of impacted wisdom teeth;

.. Maternity care services;

.. Services of a physical therapist and services of a speech therapist;

.. Hospice services;

.. Professional ambulance service to the nearest health care facility qualified to treat the illness or injury;

.. Mental health services pursuant to RCW 48.41.220; and

.. Other medical equipment, services, or supplies required by physician's orders and medically necessary and consistent with the diagnosis, treatment, and condition.

. The board shall design and employ cost containment measures and requirements such as, but not limited to, care coordination, provider network limitations, preadmission certification, and concurrent inpatient review which may make the pool more cost-effective.

. The pool benefit policy may contain benefit limitations, exceptions, and cost shares such as copayments, coinsurance, and deductibles that are consistent with managed care products, except that differential cost shares may be adopted by the board for nonnetwork providers under point of service plans. No limitation, exception, or reduction may be used that would exclude coverage for any disease, illness, or injury.

. [Empty]
.. The pool may not reject an individual for health plan coverage based upon preexisting conditions of the individual or deny, exclude, or otherwise limit coverage for an individual's preexisting health conditions; except that it shall impose a six-month benefit waiting period for preexisting conditions for which medical advice was given, for which a health care provider recommended or provided treatment, or for which a prudent layperson would have sought advice or treatment, within six months before the effective date of coverage. The preexisting condition waiting period shall not apply to prenatal care services or benefits for outpatient prescription drugs. The pool may not avoid the requirements of this section through the creation of a new rate classification or the modification of an existing rate classification. Credit against the waiting period shall be as provided in subsection (8) of this section.

.. The pool shall not impose any preexisting condition waiting period for any person under the age of nineteen.

. [Empty]
.. Except as provided in (b) of this subsection, the pool shall credit any preexisting condition waiting period in its plans for a person who was enrolled at any time during the sixty-three day period immediately preceding the date of application for the new pool plan. For the person previously enrolled in a group health benefit plan, the pool must credit the aggregate of all periods of preceding coverage not separated by more than sixty-three days toward the waiting period of the new health plan. For the person previously enrolled in an individual health benefit plan other than a catastrophic health plan, the pool must credit the period of coverage the person was continuously covered under the immediately preceding health plan toward the waiting period of the new health plan. For the purposes of this subsection, a preceding health plan includes an employer-provided self-funded health plan.

.. The pool shall waive any preexisting condition waiting period for a person who is an eligible individual as defined in section 2741(b) of the federal health insurance portability and accountability act of 1996 (42 U.S.C. 300gg-41(b)).

. If an application is made for the pool policy as a result of rejection by a carrier, then the date of application to the carrier, rather than to the pool, should govern for purposes of determining preexisting condition credit.

. The pool shall contract with organizations that provide care management that has been demonstrated to be effective and shall encourage enrollees who are eligible for care management services to participate. The pool may encourage the use of shared decision making and certified decision aids for preference-sensitive care areas.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2523.SL.pdf?cite=2012%20c%20211%20§%2025[2012 c 211 § 25]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5371-S.SL.pdf?cite=2011%20c%20315%20§%206[2011 c 315 § 6]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5930-S2.SL.pdf?cite=2007%20c%20259%20§%2026[2007 c 259 § 26]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1460.SL.pdf?cite=2007%20c%208%20§%205[2007 c 8 § 5]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1633.SL.pdf?cite=2001%20c%20196%20§%204[2001 c 196 § 4]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/3154.SL.pdf?cite=2000%20c%2080%20§%202[2000 c 80 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6067-S2.SL.pdf?cite=2000%20c%2079%20§%2013[2000 c 79 § 13]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2018-S.SL.pdf?cite=1997%20c%20231%20§%20213[1997 c 231 § 213]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c431.pdf?cite=1987%20c%20431%20§%2011[1987 c 431 § 11]; ]

== 48.41.120 - Comprehensive pool policy—Deductibles—Coinsurance—Carryover.
. Subject to the limitation provided in subsection (3) of this section, the comprehensive pool policy offered under RCW 48.41.110(4) shall impose a deductible as provided in this subsection. Deductibles of five hundred dollars and one thousand dollars on a per person per calendar year basis shall initially be offered. The board may authorize deductibles in other amounts. The deductible shall be applied to the first five hundred dollars, one thousand dollars, or other authorized amount of eligible expenses incurred by the covered person.

. Subject to the limitations provided in subsection (3) of this section, a mandatory coinsurance requirement shall be imposed at a rate not to exceed twenty percent of eligible expenses in excess of the mandatory deductible and which supports the efficient delivery of high quality health care services for the medical conditions of pool enrollees.

. The maximum aggregate out-of-pocket payments for eligible expenses by the insured in the form of deductibles and coinsurance under the comprehensive pool policy offered under RCW 48.41.110(4) shall not exceed in a calendar year:

.. One thousand five hundred dollars per individual, or three thousand dollars per family, per calendar year for the five hundred dollar deductible policy;

.. Two thousand five hundred dollars per individual, or five thousand dollars per family per calendar year for the one thousand dollar deductible policy; or

.. An amount authorized by the board for any other deductible policy.

. Except for those enrolled in a high deductible health plan qualified under federal law for use with a health savings account, eligible expenses incurred by a covered person in the last three months of a calendar year, and applied toward a deductible, shall also be applied toward the deductible amount in the next calendar year.

. The board may modify cost-sharing as an incentive for enrollees to participate in care management services and other cost-effective programs and policies.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5930-S2.SL.pdf?cite=2007%20c%20259%20§%2031[2007 c 259 § 31]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6067-S2.SL.pdf?cite=2000%20c%2079%20§%2014[2000 c 79 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c121.pdf?cite=1989%20c%20121%20§%208[1989 c 121 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c431.pdf?cite=1987%20c%20431%20§%2012[1987 c 431 § 12]; ]

== 48.41.130 - Policy forms—Approval required.
All policy forms issued by the pool shall conform in substance to prototype forms developed by the pool, and shall in all other respects conform to the requirements of this chapter, and shall be filed with and approved by the commissioner before they are issued.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6067-S2.SL.pdf?cite=2000%20c%2079%20§%2015[2000 c 79 § 15]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2018-S.SL.pdf?cite=1997%20c%20231%20§%20215[1997 c 231 § 215]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c431.pdf?cite=1987%20c%20431%20§%2013[1987 c 431 § 13]; ]

== 48.41.140 - Coverage for children, dependents.
. Coverage shall provide that health insurance benefits are applicable to children of the person in whose name the policy is issued including adopted and newly born natural children. Coverage shall also include necessary care and treatment of medically diagnosed congenital defects and birth abnormalities. If payment of a specific premium is required to provide coverage for the child, the policy may require that notification of the birth or adoption of a child and payment of the required premium must be furnished to the pool within thirty-one days after the date of birth or adoption in order to have the coverage continued beyond the thirty-one day period. For purposes of this subsection, a child is deemed to be adopted, and benefits are payable, when the child is physically placed for purposes of adoption under the laws of this state with the person in whose name the policy is issued; and, when the person in whose name the policy is issued assumes financial responsibility for the medical expenses of the child. For purposes of this subsection, "newly born" means, and benefits are payable, from the moment of birth.

. A pool policy shall provide that coverage of a dependent person shall terminate when the person becomes twenty-six years of age: PROVIDED, That coverage of such person shall not terminate at age twenty-six while he or she is and continues to be both (a) incapable of self-sustaining employment by reason of developmental or physical disability and (b) chiefly dependent upon the person in whose name the policy is issued for support and maintenance, provided proof of such incapacity and dependency is furnished to the pool by the policyholder within thirty-one days of the dependent's attainment of age twenty-six and subsequently as may be required by the pool but not more frequently than annually after the two-year period following the dependent's attainment of age twenty-six.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2390.SL.pdf?cite=2020%20c%20274%20§%2034[2020 c 274 § 34]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5122-S.SL.pdf?cite=2011%20c%20314%20§%2016[2011 c 314 § 16]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6067-S2.SL.pdf?cite=2000%20c%2079%20§%2016[2000 c 79 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c431.pdf?cite=1987%20c%20431%20§%2014[1987 c 431 § 14]; ]

== 48.41.150 - Medical supplement policy.
. The board shall offer a medical supplement policy for persons receiving medicare parts A and B. The supplement policy shall provide benefits of one hundred percent of the deductible and copayment required under medicare and eighty percent of the charges for covered services under this chapter that are not paid by medicare. The coverage shall include a limitation of one thousand dollars per person on total annual out-of-pocket expenses for the covered services.

. If federal law is adopted that addresses this subject, the board shall offer a policy that is consistent with that federal law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c121.pdf?cite=1989%20c%20121%20§%209[1989 c 121 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c431.pdf?cite=1987%20c%20431%20§%2015[1987 c 431 § 15]; ]

== 48.41.160 - Pool policy requirements—Continued coverage—Rate changes—Continuation—Statement of intent to discontinue pool coverage.
. On or before December 31, 2007, the pool shall cancel all existing pool policies and replace them with policies that are identical to the existing policies except for the inclusion of a provision providing for a guarantee of the continuity of coverage consistent with this section. As a means to minimize the number of policy changes for enrollees, replacement policies provided under this subsection also may include the plan modifications authorized in RCW 48.41.100, 48.41.110, and 48.41.120.

. A pool policy shall contain a guarantee of the individual's right to continued coverage, subject to the provisions of subsections (4), (5), (7), and (8) of this section.

. The guarantee of continuity of coverage required by this section shall not prevent the pool from canceling or nonrenewing a policy for:

.. Nonpayment of premium;

.. Violation of published policies of the pool;

.. Failure of a covered person who becomes eligible for medicare benefits by reason of age to apply for a pool medical supplement plan, or a medicare supplement plan or other similar plan offered by a carrier pursuant to federal laws and regulations;

.. Failure of a covered person to pay any deductible or copayment amount owed to the pool and not the provider of health care services;

.. Covered persons committing fraudulent acts as to the pool;

.. Covered persons materially breaching the pool policy; or

.. Changes adopted to federal or state laws when such changes no longer permit the continued offering of such coverage.

. [Empty]
.. The guarantee of continuity of coverage provided by this section requires that if the pool replaces a plan, it must make the replacement plan available to all individuals in the plan being replaced. The replacement plan must include all of the services covered under the replaced plan, and must not significantly limit access to the kind of services covered under the replacement plan through unreasonable cost-sharing requirements or otherwise. The pool may also allow individuals who are covered by a plan that is being replaced an unrestricted right to transfer to a fully comparable plan.

.. The guarantee of continuity of coverage provided by this section requires that if the pool discontinues offering a plan: (i) The pool must provide notice to each individual of the discontinuation at least ninety days prior to the date of the discontinuation; (ii) the pool must offer to each individual provided coverage under the discontinued plan the option to enroll in any other plan currently offered by the pool for which the individual is otherwise eligible; and (iii) in exercising the option to discontinue a plan and in offering the option of coverage under (b)(ii) of this subsection, the pool must act uniformly without regard to any health status-related factor of enrolled individuals or individuals who may become eligible for this coverage.

.. The pool cannot replace or discontinue a plan under this subsection (4) until it has completed an evaluation of the impact of replacing the plan upon:

... The cost and quality of care to pool enrollees;

... Pool financing and enrollment;

... The board's ability to offer comprehensive and other plans to its enrollees;

... Other items identified by the board.

In its evaluation, the board must request input from the constituents represented by the board members.

.. The guarantee of continuity of coverage provided by this section does not apply if the pool has zero enrollment in a plan.

. The pool may not change the rates for pool policies except on a class basis, with a clear disclosure in the policy of the pool's right to do so.

. A pool policy offered under this chapter shall provide that, upon the death of the individual in whose name the policy is issued, every other individual then covered under the policy may elect, within a period specified in the policy, to continue coverage under the same or a different policy.

. All pool policies issued on or after January 1, 2014, must reflect the new eligibility requirements of RCW 48.41.100.

. Pool policies issued prior to January 1, 2014, shall be modified effective January 1, 2018, consistent with subsection (3)(g) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1096.SL.pdf?cite=2021%20c%2060%20§%202[2021 c 60 § 2]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1338-S2.SL.pdf?cite=2017%20c%20110%20§%203[2017 c 110 § 3]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5449-S.SL.pdf?cite=2013%20c%20279%20§%204[2013 c 279 § 4]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5930-S2.SL.pdf?cite=2007%20c%20259%20§%2027[2007 c 259 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c431.pdf?cite=1987%20c%20431%20§%2016[1987 c 431 § 16]; ]

== 48.41.170 - Required rule making.
The commissioner shall adopt rules pursuant to chapter 34.05 RCW that:

. Provide for disclosure by the member of the availability of insurance coverage from the pool; and

. Implement this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c431.pdf?cite=1987%20c%20431%20§%2017[1987 c 431 § 17]; ]

== 48.41.190 - Civil and criminal immunity.
The pool, members of the pool, board directors of the pool, officers of the pool, employees of the pool, the commissioner, the commissioner's representatives, and the commissioner's employees shall not be civilly or criminally liable and shall not have any penalty or cause of action of any nature arise against them for any action taken or not taken, including any discretionary decision or failure to make a discretionary decision, when the action or inaction is done in good faith and in the performance of the powers and duties under this chapter. Nothing in this section prohibits legal actions against the pool to enforce the pool's statutory or contractual duties or obligations.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5930-S2.SL.pdf?cite=2007%20c%20259%20§%2033[2007 c 259 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c121.pdf?cite=1989%20c%20121%20§%2010[1989 c 121 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c431.pdf?cite=1987%20c%20431%20§%2019[1987 c 431 § 19]; ]

== 48.41.200 - Rates—Standard risk and maximum.
. The pool shall determine the standard risk rate by calculating the average individual standard rate charged for coverage comparable to pool coverage by the five largest members, measured in terms of individual market enrollment, offering such coverages in the state. In the event five members do not offer comparable coverage, the standard risk rate shall be established using reasonable actuarial techniques and shall reflect anticipated experience and expenses for such coverage in the individual market.

. Subject to subsection (3) of this section, maximum rates for pool coverage shall be as follows:

.. Maximum rates for a pool indemnity health plan shall be one hundred fifty percent of the rate calculated under subsection (1) of this section;

.. Maximum rates for a pool care management plan shall be one hundred twenty-five percent of the rate calculated under subsection (1) of this section; and

.. Maximum rates for a person eligible for pool coverage pursuant to RCW 48.41.100(1)(a) who was enrolled at any time during the sixty-three day period immediately prior to the date of application for pool coverage in a group health benefit plan or an individual health benefit plan other than a catastrophic health plan as defined in RCW 48.43.005, where such coverage was continuous for at least eighteen months, shall be:

... For a pool indemnity health plan, one hundred twenty-five percent of the rate calculated under subsection (1) of this section; and

... For a pool care management plan, one hundred ten percent of the rate calculated under subsection (1) of this section.

. [Empty]
.. Subject to (b) and (c) of this subsection:

... The rate for any person whose current gross family income is less than two hundred fifty-one percent of the federal poverty level shall be reduced by thirty percent from what it would otherwise be;

... The rate for any person whose current gross family income is more than two hundred fifty but less than three hundred one percent of the federal poverty level shall be reduced by fifteen percent from what it would otherwise be;

... The rate for any person who has been enrolled in the pool for more than thirty-six months shall be reduced by five percent from what it would otherwise be.

.. In no event shall the rate for any person be less than one hundred ten percent of the rate calculated under subsection (1) of this section.

.. Rate reductions under (a)(i) and (ii) of this subsection shall be available only to the extent that funds are specifically appropriated for this purpose in the omnibus appropriations act.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5930-S2.SL.pdf?cite=2007%20c%20259%20§%2028[2007 c 259 § 28]; 2018 c 219 § 3; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6067-S2.SL.pdf?cite=2000%20c%2079%20§%2017[2000 c 79 § 17]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2018-S.SL.pdf?cite=1997%20c%20231%20§%20214[1997 c 231 § 214]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c431.pdf?cite=1987%20c%20431%20§%2020[1987 c 431 § 20]; ]

== 48.41.210 - Last payor of benefits.
It is the express intent of this chapter that the pool be the last payor of benefits whenever any other benefit is available.

. Benefits otherwise payable under pool coverage shall be reduced by all amounts paid or payable through any other health insurance, or health benefit plans, including but not limited to self-insured plans and by all hospital and medical expense benefits paid or payable under any worker's compensation coverage, automobile medical payment or liability insurance whether provided on the basis of fault or nonfault, and by any hospital or medical benefits paid or payable under or provided pursuant to any state or federal law or program.

. The administrator or the pool shall have a cause of action against an eligible person for the recovery of the amount of benefits paid which are not for covered expenses. Benefits due from the pool may be reduced or refused as a set-off against any amount recoverable under this subsection.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c431.pdf?cite=1987%20c%20431%20§%2021[1987 c 431 § 21]; ]

== 48.41.220 - Mental health services—Definition—Coverage required, when.
. For the purposes of this section, "mental health services" means:

.. For each health insurance policy issued or renewed by the pool before January 1, 2021, medically necessary outpatient and inpatient services provided to treat mental disorders covered by the diagnostic categories listed in the most current version of the diagnostic and statistical manual of mental disorders, published by the American psychiatric association, on June 11, 2020, or such subsequent date as may be provided by the insurance commissioner by rule, consistent with the purposes of chapter 6, Laws of 2005, with the exception of the following categories, codes, and services: (i) Substance related disorders; (ii) life transition problems, currently referred to as "V" codes, and diagnostic codes 302 through 302.9 as found in the diagnostic and statistical manual of mental disorders, 4th edition, published by the American psychiatric association; (iii) skilled nursing facility services, home health care, residential treatment, and custodial care; and (iv) court-ordered treatment unless the insurer's medical director or designee determines the treatment to be medically necessary; and

.. For each health insurance policy issued or renewed by the pool on or after January 1, 2021, medically necessary outpatient and inpatient services provided to treat mental disorders covered by the diagnostic categories listed in the most current version of the diagnostic and statistical manual of mental health and substance use disorders, published by the American psychiatric association, on June 11, 2020, or such subsequent date as may be provided by the insurance commissioner by rule, consistent with the purposes of chapter 6, Laws of 2005.

. Each health insurance policy issued by the pool shall provide coverage for:

.. Mental health services. The copayment or coinsurance for mental health services may be no more than the copayment or coinsurance for medical and surgical services otherwise provided under the policy. Wellness and preventive services that are provided or reimbursed at a lesser copayment, coinsurance, or other cost sharing than other medical and surgical services are excluded from this comparison. If the policy imposes a maximum out-of-pocket limit or stop loss, it shall be a single limit or stop loss for medical, surgical, and mental health services. If the policy imposes any deductible, mental health services shall be included with medical and surgical services for the purpose of meeting the deductible requirement. Treatment limitations or any other financial requirements on coverage for mental health services are only allowed if the same limitations or requirements are imposed on coverage for medical and surgical services; and

.. Prescription drugs intended to treat any of the disorders covered in subsection (1) of this section to the same extent, and under the same terms and conditions, as other prescription drugs covered by the policy.

. This section does not prohibit a requirement that mental health services be medically necessary, if a comparable requirement is applicable to medical and surgical services.

. Nothing in this section shall be construed to prevent the management of mental health services if a comparable requirement is applicable to medical and surgical services.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2338-S.SL.pdf?cite=2020%20c%20228%20§%204[2020 c 228 § 4]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1460.SL.pdf?cite=2007%20c%208%20§%206[2007 c 8 § 6]; ]

== 48.41.240 - Review of populations needing coverage through pool—Analysis and recommendations—Report.
. The board shall review populations that may need ongoing access to coverage through the pool, with specific attention to those persons who may be excluded from or may receive inadequate coverage beginning January 1, 2014, such as persons with end-stage renal disease or HIV/AIDS, or persons not eligible for coverage in the exchange.

. If the review under subsection (1) of this section indicates a continued need for coverage through the pool after December 31, 2013, the board shall submit recommendations regarding any modifications to pool eligibility requirements for new and ongoing enrollment after December 31, 2013. The recommendations must address any needed modifications to the standard health questionnaire or other eligibility screening tool that could be used in a manner consistent with federal law to determine eligibility for enrollment in the pool.

. The board shall complete an analysis of current pool assessment requirements in relation to assessments that will fund the reinsurance program and recommend changes to pool assessments or any credits against assessments that may be considered for the reinsurance program. The analysis shall recommend whether the categories of members paying assessments should be adjusted to make the assessment fair and equitable among all payers.

. The board shall report its recommendations to the governor and the legislature by December 1, 2012.

. The board shall revisit the study of eligibility completed in 2012 with another review of the populations that may need ongoing access to coverage through the pool, to be submitted to the governor and legislature by November 1, 2015. The eligibility study shall include the nonmedicare populations scheduled to lose coverage and medicare populations, and consider whether the enrollees have access to comprehensive coverage alternatives that include appropriate pharmacy coverage. The study shall include recommendations to address any barriers in eligibility that remain in accessing other coverage such as medicare supplemental coverage or comprehensive pharmacy coverage, as well as suggestions for financing changes and recommendations on a future expiration of the pool.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5449-S.SL.pdf?cite=2013%20c%20279%20§%205[2013 c 279 § 5]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=2012%20c%2087%20§%2017[2012 c 87 § 17]; ]

== 48.41.250 - Administration of risk management functions—Contract with commissioner authorized—Recommendations—Report to legislature.
. The pool is authorized to contract with the commissioner to administer risk management functions if necessary, consistent with RCW 48.43.720, and consistent with P.L. 111-148 of 2010, as amended. Prior to entering into a contract, the pool may conduct preoperational and planning activities related to these programs, including defining and implementing an appropriate legal structure or structures to administer and coordinate the reinsurance or risk adjustment programs.

. The reasonable costs incurred by the pool for preoperational and planning activities related to the reinsurance program may be reimbursed from federal funds or from the additional contributions authorized under RCW 48.43.720 to pay the administrative costs of the reinsurance program.

. If the pool contracts to administer and coordinate the reinsurance or risk adjustment program, the board must submit recommendations to the legislature with suggestions for additional consumer representatives or other representative members to the board.

. The pool shall report on these activities to the appropriate committees of the senate and house of representatives by December 15, 2012, and December 15, 2013.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=2012%20c%2087%20§%2018[2012 c 87 § 18]; ]

== 48.41.900 - Federal supremacy.
If any part of this chapter is found to be in conflict with federal requirements which are a prescribed condition to the allocation of federal funds to the state, the conflicting part of this chapter is hereby declared to be inoperative solely to the extent of the conflict and with respect to the agencies directly affected, and such finding or determination shall not affect the operation of the remainder of this chapter in its application to the agencies concerned. The rules under this chapter shall meet federal requirements which are a necessary condition to the receipt of federal funds by the state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c431.pdf?cite=1987%20c%20431%20§%2022[1987 c 431 § 22]; ]

== 48.41.920 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%20124[2009 c 521 § 124]; ]

