= 48.01 - Initial provisions.
:toc:

== 48.01.010 - Short title.
Title 48 RCW constitutes the insurance code.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c266.pdf?cite=1975%201st%20ex.s.%20c%20266%20§%202[1975 1st ex.s. c 266 § 2]; 1947 c 79 § .01.01; Rem. Supp. 1947 § 45.01.01; ]

== 48.01.020 - Scope of code.
All insurance and insurance transactions in this state, or affecting subjects located wholly or in part or to be performed within this state, and all persons having to do therewith are governed by this code.

[ 1947 c 79 § .01.02; Rem. Supp. 1947 § 45.01.02; ]

== 48.01.030 - Public interest.
The business of insurance is one affected by the public interest, requiring that all persons be actuated by good faith, abstain from deception, and practice honesty and equity in all insurance matters. Upon the insurer, the insured, their providers, and their representatives rests the duty of preserving inviolate the integrity of insurance.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1557-S2.SL.pdf?cite=1995%20c%20285%20§%2016[1995 c 285 § 16]; 1947 c 79 § .01.03; Rem. Supp. 1947 § 45.01.03; ]

== 48.01.035 - "Developmental disability" defined.
The term "developmental disability" as used in this title means a disability attributable to intellectual disability, cerebral palsy, epilepsy, autism, or another neurological condition closely related to an intellectual disability or to require treatment similar to that required for persons with intellectual disabilities, which disability originates before such individual attains age eighteen, which has continued or can be expected to continue indefinitely, and which constitutes a substantial limitation to such individual.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2490.SL.pdf?cite=2010%20c%2094%20§%2014[2010 c 94 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c264.pdf?cite=1985%20c%20264%20§%201[1985 c 264 § 1]; ]

== 48.01.040 - "Insurance" defined.
Insurance is a contract whereby one undertakes to indemnify another or pay a specified amount upon determinable contingencies.

[ 1947 c 79 § .01.04; Rem. Supp. 1947 § 45.01.04; ]

== 48.01.050 - "Insurer" defined.
"Insurer" as used in this code includes every person engaged in the business of making contracts of insurance, other than a fraternal benefit society. A reciprocal or interinsurance exchange is an "insurer" as used in this code. Two or more hospitals that join and organize as a mutual corporation pursuant to chapter 24.06 RCW for the purpose of insuring or self-insuring against liability claims, including medical liability, through a contributing trust fund are not an "insurer" under this code. Two or more local governmental entities, under any provision of law, that join together and organize to form an organization for the purpose of jointly self-insuring or self-funding are not an "insurer" under this code. Two or more affordable housing entities that join together and organize to form an organization for the purpose of jointly self-insuring or self-funding under chapter 48.64 RCW are not an "insurer" under this code. Two or more persons engaged in the business of commercial fishing who enter into an arrangement with other such persons for the pooling of funds to pay claims or losses arising out of loss or damage to a vessel or machinery used in the business of commercial fishing and owned by a member of the pool are not an "insurer" under this code. Two or more nonprofit corporations that join together and organize to form an organization for the purpose of jointly self-insuring or self-funding for property and liability risks under chapter 48.180 RCW are not an "insurer" under this code.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5119.SL.pdf?cite=2015%20c%20109%20§%201[2015 c 109 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5665-S.SL.pdf?cite=2009%20c%20314%20§%2019[2009 c 314 § 19]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1083.SL.pdf?cite=2003%20c%20248%20§%201[2003 c 248 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c130.pdf?cite=1990%20c%20130%20§%201[1990 c 130 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c277.pdf?cite=1985%20c%20277%20§%209[1985 c 277 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c256.pdf?cite=1979%20ex.s.%20c%20256%20§%2013[1979 ex.s. c 256 § 13]; 1975-'76 2nd ex.s. c 13 § 1; 1947 c 79 § .01.05; Rem. Supp. 1947 § 45.01.05; ]

== 48.01.053 - "Issuer" defined.
"Issuer" as used in this title and chapter 26.18 RCW means insurer, fraternal benefit society, certified health plan, health maintenance organization, and health care service contractor.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5419-S.SL.pdf?cite=1995%20c%2034%20§%201[1995 c 34 § 1]; ]

== 48.01.060 - "Insurance transaction" defined.
"Insurance transaction" includes any:

. Solicitation.

. Negotiations preliminary to execution.

. Execution of an insurance contract.

. Transaction of matters subsequent to execution of the contract and arising out of it.

. Insuring.

[ 1947 c 79 § .01.06; Rem. Supp. 1947 § 45.01.06; ]

== 48.01.070 - "Person" defined.
"Person" means any individual, company, insurer, association, organization, reciprocal or interinsurance exchange, partnership, business trust, or corporation.

[ 1947 c 79 § .01.07; Rem. Supp. 1947 § 45.01.07; ]

== 48.01.080 - Penalties.
Except as otherwise provided in this code, any person violating any provision of this code is guilty of a gross misdemeanor and will, upon conviction, be fined not less than ten dollars nor more than one thousand dollars, or imprisoned for not more than three hundred sixty-four days, or both, in addition to any other penalty or forfeiture provided herein or otherwise by law.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5168-S.SL.pdf?cite=2011%20c%2096%20§%2037[2011 c 96 § 37]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5641-S.SL.pdf?cite=2003%20c%20250%20§%201[2003 c 250 § 1]; 1947 c 79 § .01.08; Rem. Supp. 1947 § 45.01.08; ]

== 48.01.100 - Existing officers.
Continuation by this code of any office existing under any act repealed herein preserves the tenure of the individual holding the office at the effective date of this code.

[ 1947 c 79 § .01.10; Rem. Supp. 1947 § 45.01.10; ]

== 48.01.110 - Existing licenses.
Every license or certificate of authority in force immediately prior to the effective date of this code and existing under any act herein repealed is valid until its original expiration date, unless earlier terminated in accordance with this code.

[ 1947 c 79 § .01.11; Rem. Supp. 1947 § 45.01.11; ]

== 48.01.120 - Existing insurance forms.
Every form of insurance document in use at the effective date of this code in accordance with the commissioner's approval pursuant to any act herein repealed, may continue to be so used unless the commissioner otherwise prescribes in accordance with this code.

[ 1947 c 79 § .01.12; Rem. Supp. 1947 § 45.01.12; ]

== 48.01.130 - Existing actions, violations.
No action or proceeding commenced, and no violation of law existing, under any act herein repealed is affected by the repeal, but all procedure hereafter taken in reference thereto shall conform to this code as far as possible.

[ 1947 c 79 § .01.13; Rem. Supp. 1947 § 45.01.13; ]

== 48.01.140 - Headings.
The meaning or scope of any provision is not affected by chapter, section, or paragraph headings.

[ 1947 c 79 § .01.14; Rem. Supp. 1947 § 45.01.14; ]

== 48.01.150 - Particular provisions prevail.
Provisions of this code relating to a particular kind of insurance or a particular type of insurer or to a particular matter prevail over provisions relating to insurance in general or insurers in general or to such matter in general.

[ 1947 c 79 § .01.15; Rem. Supp. 1947 § 45.01.15; ]

== 48.01.160 - Repealed acts not revived.
Repeal by this code of any act shall not revive any law heretofore repealed or superseded.

[ 1947 c 79 § .01.16; Rem. Supp. 1947 § 45.01.16; ]

== 48.01.170 - Effective date—1947 c 79.
This code shall become effective on the first day of October, 1947.

[ 1947 c 79 § .01.17; Rem. Supp. 1947 § 45.01.17; ]

== 48.01.180 - Adopted children—Insurance coverage.
. A child of an insured, subscriber, or enrollee shall be considered a dependent child for insurance purposes under this title upon assumption by the insured, subscriber, or enrollee of a legal obligation for total or partial support of a child in anticipation of adoption of the child. Upon the termination of such legal obligations, the child shall not be considered a dependent child for insurance purposes.

. Every policy or contract providing coverage for health benefits to a resident of this state shall provide coverage for dependent children placed for adoption under the same terms and conditions as apply to the natural, dependent children of the insured, subscriber, or enrollee whether or not the adoption has become final.

. No policy or contract may restrict coverage of any dependent child adopted by, or placed for adoption with, an insured, subscriber, or enrollee solely on the basis of a preexisting condition of the child at the time that the child would otherwise become eligible for coverage under the plan if the adoption or placement for adoption occurs while the insured, subscriber, or enrollee is eligible for coverage under the plan.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5419-S.SL.pdf?cite=1995%20c%2034%20§%204[1995 c 34 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c140.pdf?cite=1986%20c%20140%20§%201[1986 c 140 § 1]; ]

== 48.01.190 - Immunity from civil liability.
. Any person who files reports, or furnishes other information, required under Title 48 RCW, required by the commissioner under authority granted by Title 48 RCW, useful to the commissioner in the administration of Title 48 RCW, or furnished to the National Association of Insurance Commissioners at the request of the commissioner or pursuant to Title 48 RCW, shall be immune from liability in any civil action or suit arising from the filing of any such report or furnishing such information to the commissioner or the National Association of Insurance Commissioners, unless actual malice, fraud, or bad faith is shown.

. The commissioner and the National Association of Insurance Commissioners, and the agents and employees of each, are immune from liability in any civil action or suit arising from the publication of any report or bulletin or dissemination of information related to the official activities of the commissioner or the National Association of Insurance Commissioners, unless actual malice, fraud, or bad faith is shown.

. Any licensee under chapter 48.17 RCW and any trade association of the licensees under chapter 48.15 RCW, and any officer, director, employee, agent, or committee of the licensee or association who furnishes information to or for the commissioner or to or for the association regarding unauthorized insurers or regarding attempts by any person to place or actual placement by any person of business with the insurers, whether in compliance with chapter 48.15 RCW or not, shall be immune from each and every kind of liability in any civil action or suit arising in whole or in part from the information or from the furnishing of the information.

. The immunity granted by this section is in addition to any common law or statutory privilege or immunity enjoyed by such person, and nothing in this section is intended to abrogate or modify in any way such common law or statutory privilege or immunity.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1285.SL.pdf?cite=1995%20c%2010%20§%201[1995 c 10 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c51.pdf?cite=1987%20c%2051%20§%201[1987 c 51 § 1]; ]

== 48.01.220 - Behavioral health administrative services organizations—Exemption.
The activities and operations of behavioral health administrative services organizations, as defined in RCW 71.24.025, are exempt from the requirements of this title.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5432-S2.SL.pdf?cite=2019%20c%20325%20§%205017[2019 c 325 § 5017]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6312-S2.SL.pdf?cite=2014%20c%20225%20§%2069[2014 c 225 § 69]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1855-S.SL.pdf?cite=1993%20c%20462%20§%20104[1993 c 462 § 104]; ]

== 48.01.230 - Eligibility for coverage or making payments may not be contingent on eligibility for medical assistance.
An issuer and an employee welfare benefit plan, whether insured or self funded, as defined in the employee retirement income security act of 1974, 29 U.S.C. Sec. 1101 et seq. may not consider the availability of eligibility for medical assistance in this state under medical assistance, RCW 74.09.500, or any other state under 42 U.S.C. Sec. 1396a, section 1902 of the social security act, in considering eligibility for coverage or making payments under its plan for eligible enrollees, subscribers, policyholders, or certificate holders.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5419-S.SL.pdf?cite=1995%20c%2034%20§%202[1995 c 34 § 2]; ]

== 48.01.235 - Enrollment of a child under the health plan of the child's parent—Requirements—Restrictions.
. An issuer and an employee welfare benefit plan, whether insured or self funded, as defined in the employee retirement income security act of 1974, 29 U.S.C. Sec. 1101 et seq. may not deny enrollment of a child under the health plan of the child's parent on the grounds that:

.. The child was born out of wedlock;

.. The child is not claimed as a dependent on the parent's federal tax return; or

.. The child does not reside with the parent or in the issuer's, or insured or self funded employee welfare benefit plan's service area.

. Where a child has health coverage through an issuer, or an insured or self funded employee welfare benefit plan of a noncustodial parent, the issuer, or insured or self funded employee welfare benefit plan, shall:

.. Provide such information to the custodial parent as may be necessary for the child to obtain benefits through that coverage;

.. Permit the provider or the custodial parent to submit claims for covered services without the approval of the noncustodial parent. If the provider submits the claim, the provider will obtain the custodial parent's assignment of insurance benefits or otherwise secure the custodial parent's approval.

For purposes of this subsection the health care authority as the state medicaid agency under RCW 74.09.500 may reassign medical insurance rights to the provider for custodial parents whose children are eligible for services under RCW 74.09.500; and

.. Make payments on claims submitted in accordance with (b) of this subsection directly to the custodial parent, to the provider, or to the health care authority as the state medicaid agency under RCW 74.09.500.

. Where a child does not reside in the issuer's service area, an issuer shall cover no less than urgent and emergent care. Where the issuer offers broader coverage, whether by policy or reciprocal agreement, the issuer shall provide such coverage to any child otherwise covered that does not reside in the issuer's service area.

. Where a parent is required by a court order to provide health coverage for a child, and the parent is eligible for family health coverage, the issuer, or insured or self funded employee welfare benefit plan, shall:

.. Permit the parent to enroll, under the family coverage, a child who is otherwise eligible for the coverage without regard to any enrollment season restrictions;

.. Enroll the child under family coverage upon application of the child's other parent, health care authority as the state medicaid agency under RCW 74.09.500, or child support enforcement program, if the parent is enrolled but fails to make application to obtain coverage for such child; and

.. Not disenroll, or eliminate coverage of, such child who is otherwise eligible for the coverage unless the issuer or insured or self funded employee welfare benefit plan is provided satisfactory written evidence that:

... The court order is no longer in effect; or

... The child is or will be enrolled in comparable health coverage through another issuer, or insured or self funded employee welfare benefit plan, which will take effect not later than the effective date of disenrollment.

. An issuer, or insured or self funded employee welfare benefit plan, that has been assigned the rights of an individual eligible for medical assistance under medicaid and coverage for health benefits from the issuer, or insured or self funded employee welfare benefit plan, may not impose requirements on the health care authority that are different from requirements applicable to an agent or assignee of any other individual so covered.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1738-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2015%20§%2076[2011 1st sp.s. c 15 § 76]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1083.SL.pdf?cite=2003%20c%20248%20§%202[2003 c 248 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5419-S.SL.pdf?cite=1995%20c%2034%20§%203[1995 c 34 § 3]; ]

== 48.01.250 - Assistance or services in exchange for dues, assessments, or periodic or lump sum payments—Certificate of authority required—Certain travel or automobile services excepted—Violations.
. Any person, firm, partnership, corporation, or association promising, in exchange for dues, assessments, or periodic or lump sum payments, to furnish members or subscribers with assistance in matters relating to trip cancellation, bail bond service or any accident, sickness, or death insurance benefit program must:

.. Have a certificate of authority, issued by the insurance commissioner, authorizing the person, firm, partnership, corporation, or association to sell that coverage in this state; or

.. Purchase the service or insurance from a company that holds a certificate of authority, issued by the insurance commissioner, authorizing the company to sell that coverage in this state. If coverage cannot be procured from an authorized insurer holding a certificate of authority issued by the insurance commissioner, insurance may be procured from an unauthorized insurer subject to chapter 48.15 RCW.

. Travel or automobile related products or assistance including but not limited to community traffic safety service, travel and touring service, theft or reward service, map service, towing service, emergency road service, lockout or lost key service, reimbursement of emergency expenses due to a vehicle disabling accident, or legal fee reimbursement service in the defense of traffic offenses shall not be considered to be insurance for the purposes of Title 48 RCW.

. Violation of this section is subject to the enforcement provisions of RCW 48.02.080 and to the hearing and appeal provisions of chapter 48.04 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6746-S.SL.pdf?cite=1998%20c%20303%20§%201[1998 c 303 § 1]; ]

== 48.01.260 - Health benefit plans—Carriers—Clarification.
. Except as required in RCW 48.21.045, 48.44.023, and 48.46.066, nothing in this title shall be construed to require a carrier, as defined in RCW 48.43.005, to offer any health benefit plan for sale.

. Nothing in this title shall prohibit a carrier as defined in RCW 48.43.005 from ceasing sale of any or all health benefit plans to new applicants if the closed plans are closed to all new applicants.

. This section is intended to clarify, and not modify, existing law.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6067-S2.SL.pdf?cite=2000%20c%2079%20§%2040[2000 c 79 § 40]; ]

== 48.01.270 - PACE programs—Exemption.
The activities and operations of PACE programs, as defined in RCW 74.09.523 and as authorized under sections 1894, 1905(a), and 1934 of the social security act, when registered, certified, licensed, or otherwise recognized or designated as a PACE program by the Washington state department of social and health services, are exempt from the requirements of this title.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1099.SL.pdf?cite=2001%20c%20191%20§%203[2001 c 191 § 3]; ]

== 48.01.280 - Private air ambulance service—Subscription service—Exempt when conditions are met.
. A private air ambulance service that solicits membership subscriptions, accepts membership applications, charges membership fees, and provides air ambulance services, to subscription members and designated members of their household is not an insurer under RCW 48.01.050, a health carrier under chapter 48.43 RCW, a health care services contractor under chapter 48.44 RCW, or a health maintenance organization under chapter 48.46 RCW if the private air ambulance service:

.. Is licensed in accordance with RCW 18.73.130;

.. Attains and maintains accreditation by the commission on accreditation of medical transport services or another accrediting organization approved by the department of health as having equivalent requirements as the commission for aeromedical transport;

.. Has been in operation in Washington for at least two years; and

.. Has submitted evidence of its compliance with this section, the licensing requirements of RCW 18.73.130, and accreditation from the commission or another accrediting organization approved by the department of health as having equivalent requirements as the commission for aeromedical transport to the commissioner.

. A subscription service that solicits membership subscriptions, charges membership fees, and provides rescue, evacuation, emergency transport, and crisis management and consulting services related to an emergency while traveling more than one hundred miles away from home, to its members or designated members of a member's household is not an insurer under RCW 48.01.050, a health carrier under chapter 48.43 RCW, a health care services contractor under chapter 48.44 RCW, or a health maintenance organization under chapter 48.46 RCW. Rescue, evacuation, emergency transport, and crisis management and consulting services related to an emergency , include the following:

.. Providing rescue, evacuation, and emergency transport and crisis management services related to the emergency;

.. Locator services for medical and legal professionals;

.. Visa and passport services;

.. Emergency message services;

.. Emergency-related travel and emergency-related services and information;

.. Transport of human remains; and

.. Other services established by rule of the commissioner.

. A subscription service that provides rescue, evacuation, emergency transport, and crisis management and consulting services related to an emergency as described in subsection (2) of this section must satisfy, or contract with a service provider which satisfies, the licensing requirements, if any, of the jurisdiction in which the services are provided. The requirements of subsection (1) of this section must be satisfied when providing air ambulance services within the state of Washington.

. It is not required that a subscription service under subsection (1) or (2) of this section own the vehicles, planes, helicopters, other aircraft, maritime vessels, or other means of transportation that will be used to provide the contracted services.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2188-S.SL.pdf?cite=2012%20c%2093%20§%201[2012 c 93 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6231.SL.pdf?cite=2006%20c%2061%20§%201[2006 c 61 § 1]; ]

