= 48.98 - Managing general agents act.
:toc:

== 48.98.005 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Actuary" means a person who is a member in good standing of the American academy of actuaries.

. "Insurer" means a person having a certificate of authority in this state as an insurance company under RCW 48.01.050.

. "Managing general agent" means:

.. A person who manages all or part of the insurance business of an insurer, including the management of a separate division, department, or underwriting office, and acts as a representative of the insurer whether known as a managing general agent, manager, or other similar term, and who, with or without the authority, either separately or together with affiliates, produces, directly or indirectly, and underwrites an amount of gross direct written premium equal to or more than five percent of the policyholder surplus as reported in the last annual statement of the insurer in any one quarter or year together with one or more of the following activities related to the business produced:

... Adjusts or pays claims in excess of an amount to be determined by the commissioner; or

... Negotiates reinsurance on behalf of the insurer.

.. Notwithstanding (a) of this subsection, the following persons may not be managing general agents for purposes of this chapter:

... An employee of the insurer;

... A United States manager of the United States branch of an alien insurer;

... An underwriting manager who, under a contract, manages all of the insurance operations of the insurer, is under common control with the insurer, subject to the insurer holding company act, chapter 48.31B RCW, and whose compensation is not based on the volume of premiums written; or

... The attorney-in-fact authorized by and acting for the subscribers of a reciprocal insurer or interinsurance exchange under powers of attorney.

. "Underwrite" means to accept or reject risks on behalf of the insurer.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1855-S.SL.pdf?cite=1993%20c%20462%20§%2035[1993 c 462 § 35]; ]

== 48.98.010 - Requirements for managing general agent—License—Bond—Errors and omissions policy.
. No person may act in the capacity of a managing general agent with respect to risks located in this state, for an insurer authorized by this state, unless that person is licensed in this state as an insurance producer, under chapter 48.17 RCW, for the lines of insurance involved and is designated as a managing general agent and appointed as such by the insurer.

. No person may act in the capacity of a managing general agent representing an insurer domiciled in this state with respect to risks located outside this state unless that person is licensed as an insurance producer in this state, under chapter 48.17 RCW, for the lines of insurance involved and is designated as a managing general agent and appointed as such by the insurer.

. The commissioner may require a bond for the protection of each insurer.

. The commissioner may require the managing general agent to maintain an errors and omissions policy.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6591.SL.pdf?cite=2008%20c%20217%20§%2080[2008 c 217 § 80]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1855-S.SL.pdf?cite=1993%20c%20462%20§%2036[1993 c 462 § 36]; ]

== 48.98.015 - Contract required between a managing general agent and an insurer—Minimum provisions.
A managing general agent may not place business with an insurer unless there is in force a written contract between the managing general agent and the insurer that sets forth the responsibilities of each party and, where both parties share responsibility for a particular function, that specifies the division of the responsibilities, and that contains the following minimum provisions:

. The insurer may terminate the contract for cause upon written notice to the managing general agent. The insurer may suspend the underwriting authority of the managing general agent during the pendency of a dispute regarding the cause for termination.

. The managing general agent shall render accounts to the insurer detailing all transactions and remit all funds due under the contract to the insurer on not less than a monthly basis.

. The managing general agent shall hold funds collected for the account of an insurer in a fiduciary capacity in an FDIC insured financial institution. This account must be used for all payments on behalf of the insurer. The managing general agent may retain no more than three months' estimated claims payments and allocated loss adjustment expenses.

. The managing general agent shall maintain separate records of business written for each insurer. The insurer has access to and the right to copy all accounts and records related to its business in a form usable by the insurer, and the commissioner has access to all books, bank accounts, and records of the managing general agent in a form usable to the commissioner. Those records must be retained according to the requirements of this title and rules adopted under it.

. The managing general agent may not assign the contract in whole or part.

. [Empty]
.. Appropriate underwriting guidelines must include at least the following: The maximum annual premium volume; the basis of the rates to be charged; the types of risks that may be written; maximum limits of liability; applicable exclusions; territorial limitations; policy cancellation provisions; and the maximum policy period.

.. The insurer has the right to cancel or not renew any policy of insurance, subject to the applicable laws and rules, including those in chapter 48.18 RCW.

. If the contract permits the managing general agent to settle claims on behalf of the insurer:

.. All claims must be reported to the insurer in a timely manner;

.. A copy of the claim file must be sent to the insurer at its request or as soon as it becomes known that the claim:

... Has the potential to exceed an amount determined by the commissioner, or exceeds the limit set by the insurer, whichever is less;

... Involves a coverage dispute;

... May exceed the managing general agent's claims settlement authority;

... Is open for more than six months; or

.. Is closed by payment in excess of an amount set by the commissioner or an amount set by the insurer, whichever is less;

.. All claim files are the joint property of the insurer and the managing general agent. However, upon an order of liquidation of the insurer, those files become the sole property of the insurer or its liquidator or successor. The managing general agent has reasonable access to and the right to copy the files on a timely basis; and

.. Settlement authority granted to the managing general agent may be terminated for cause upon the insurer's written notice to the managing general agent or upon the termination of the contract. The insurer may suspend the managing general agent's settlement authority during the pendency of a dispute regarding the cause for termination.

. When electronic claims files are in existence, the contract must address the timely transmission of the data.

. If the contract provides for a sharing of interim profits by the managing general agent, and the managing general agent has the authority to determine the amount of the interim profits by establishing loss reserves or controlling claim payments or in any other manner, interim profits may not be paid to the managing general agent until one year after they are earned for property insurance business and five years after they are earned on casualty business and not until the profits have been verified under RCW 48.98.020.

. The managing general agent may not:

.. Bind reinsurance or retrocessions on behalf of the insurer, except that the managing general agent may bind automatic reinsurance contracts under obligatory automatic agreements if the contract with the insurer contains reinsurance underwriting guidelines including, for both reinsurance assumed and ceded, a list of reinsurers with which the automatic agreements are in effect, the coverages and amounts or percentages that may be reinsured, and commission schedules;

.. Commit the insurer to participate in insurance or reinsurance syndicates;

.. Use an insurance producer that is not appointed to represent the insurer in accordance with the requirements of chapter 48.17 RCW;

.. Without prior approval of the insurer, pay or commit the insurer to pay a claim over a specified amount, net of reinsurance, that may not exceed one percent of the insurer's policyholder surplus as of December 31st of the last-completed calendar year;

.. Collect a payment from a reinsurer or commit the insurer to a claim settlement with a reinsurer, without prior approval of the insurer. If prior approval is given, a report must be promptly forwarded to the insurer;

.. Permit an agent appointed by it to serve on the insurer's board of directors;

.. Jointly employ an individual who is employed by the insurer; or

.. Appoint a submanaging general agent.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6591.SL.pdf?cite=2008%20c%20217%20§%2081[2008 c 217 § 81]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1197-S.SL.pdf?cite=2005%20c%20223%20§%2032[2005 c 223 § 32]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1855-S.SL.pdf?cite=1993%20c%20462%20§%2037[1993 c 462 § 37]; ]

== 48.98.020 - Requirements for insurer—Audit, loss reserves, and on-site review of managing general agent—Notice to commissioner—Quarterly review of books and records—Board of director.
. The insurer shall have on file an independent audited financial statement, in a form acceptable to the commissioner, of each managing general agent with which it is doing or has done business.

. If a managing general agent establishes loss reserves, the insurer shall annually obtain the opinion of an actuary attesting to the adequacy of loss reserves established for losses incurred and outstanding on business produced by the managing general agent. This is in addition to any other required loss reserve certification.

. The insurer shall periodically, and no less frequently than semiannually, conduct an on-site review of the underwriting and claims processing operations of the managing general agent.

. Binding authority for all reinsurance contracts or participation in insurance or reinsurance syndicates must rest with an officer of the insurer, who may not be affiliated with the managing general agent.

. Within thirty days of entering into or terminating a contract with a managing general agent, the insurer shall provide written notification of that appointment or termination to the commissioner. Notices of appointment of a managing general agent must include a statement of duties that the managing general agent is expected to perform on behalf of the insurer, the lines of insurance for which the managing general agent is to be authorized to act, and any other information the commissioner may request. This subsection applies to managing general agents operating in this state.

. An insurer shall review its books and records each calendar quarter to determine if any insurance producer has become a managing general agent. If the insurer determines that an insurance producer has become a managing general agent under RCW 48.98.005, the insurer shall promptly notify the insurance producer and the commissioner of that determination, and the insurer and insurance producer shall fully comply with this chapter within thirty days.

. An insurer may not appoint to its board of directors an officer, director, employee, subagent, or controlling shareholder of its managing general agents. This subsection does not apply to relationships governed by the insurer holding company act, chapter 48.31B RCW, or, if applicable, the business transacted with broker-controlled property and casualty insurer act, *chapter 48.97 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6591.SL.pdf?cite=2008%20c%20217%20§%2082[2008 c 217 § 82]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1855-S.SL.pdf?cite=1993%20c%20462%20§%2038[1993 c 462 § 38]; ]

== 48.98.025 - Examinations—Acts of a managing general agent are acts of the insurer.
The acts of the managing general agent are considered to be the acts of the insurer on whose behalf it is acting. A managing general agent may be examined as if it were the insurer, as provided in chapter 48.03 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1855-S.SL.pdf?cite=1993%20c%20462%20§%2039[1993 c 462 § 39]; ]

== 48.98.030 - Violations of chapter—Penalties—Judicial review.
. Subject to a hearing in accordance with chapters 34.05 and 48.04 RCW, upon a finding by the commissioner that any person has violated any provision of this chapter, the commissioner may order:

.. For each separate violation, a penalty in an amount of not more than one thousand dollars;

.. Revocation, or suspension for up to one year, of the managing general agent's license including any insurance producer's licenses held by the managing general agent; and

.. The managing general agent to reimburse the insurer, the rehabilitator, or liquidator of the insurer for losses incurred by the insurer caused by a violation of this chapter committed by the managing general agent.

. The decision, determination, or order of the commissioner under this section is subject to judicial review under chapters 34.05 and 48.04 RCW.

. Nothing contained in this section affects the right of the commissioner to impose any other penalties provided for in this title.

. Nothing contained in this chapter is intended to or in any manner limits or restricts the rights of policyholders, claimants, and auditors.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6591.SL.pdf?cite=2008%20c%20217%20§%2083[2008 c 217 § 83]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1855-S.SL.pdf?cite=1993%20c%20462%20§%2040[1993 c 462 § 40]; ]

== 48.98.035 - Rule making.
The commissioner may adopt rules for the implementation and administration of this chapter, that shall include but are not limited to licensure of managing general agents.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1855-S.SL.pdf?cite=1993%20c%20462%20§%2041[1993 c 462 § 41]; ]

== 48.98.040 - Continued use of a managing general agent—Compliance with chapter.
No insurer may continue to use the services of a managing general agent on and after January 1, 1994, unless that use complies with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1855-S.SL.pdf?cite=1993%20c%20462%20§%2042[1993 c 462 § 42]; ]

== 48.98.900 - Short title.
This chapter may be known and cited as the managing general agents act.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1855-S.SL.pdf?cite=1993%20c%20462%20§%2034[1993 c 462 § 34]; ]

== 48.98.901 - Severability—Implementation—1993 c 462.
See RCW 48.31B.901 and 48.31B.902.

[ ]

