= 48.25 - Industrial life insurance.
:toc:

== 48.25.010 - Scope of chapter.
The provisions of this chapter apply only to industrial life insurance contracts.

[ 1947 c 79 § .25.01; Rem. Supp. 1947 § 45.25.01; ]

== 48.25.020 - Industrial life insurance defined.
"Industrial" life insurance is any life insurance provided by an individual insurance contract issued in face amount of less than one thousand dollars, under which premiums are payable monthly or oftener, and bearing the words "industrial policy" printed upon the policy as a part of the descriptive matter.

[ 1947 c 79 § .25.02; Rem. Supp. 1947 § 45.25.02; ]

== 48.25.030 - Compliance enjoined.
No policy of industrial life insurance shall be delivered or be issued for delivery in this state after January 1, 1948, except in compliance with the provisions of this chapter and with other applicable provisions of this code.

[ 1947 c 79 § .25.03; Rem. Supp. 1947 § 45.25.03; ]

== 48.25.040 - Standard provisions.
No such policy shall be so issued or delivered unless it contains in substance the provisions as required by this chapter, or provisions which in the opinion of the commissioner are more favorable to the policyholder.

[ 1947 c 79 § .25.04; Rem. Supp. 1947 § 45.25.04; ]

== 48.25.050 - Grace period.
There shall be a provision that the insured is entitled to a grace period of four weeks within which the payment of any premium after the first may be made, except that in policies the premiums for which are payable monthly, the period of grace shall be one month but not less than thirty days; and that during the period of grace the policy shall continue in full force, but if during the grace period the policy becomes a claim, then any overdue and unpaid premiums may be deducted from any settlement under the policy.

[ 1947 c 79 § .25.05; Rem. Supp. 1947 § 45.25.05; ]

== 48.25.060 - Entire contract.
There shall be a provision that the policy shall constitute the entire contract between the parties, or, if a copy of the application is endorsed upon or attached to the policy when issued, a provision that the policy and the application therefor shall constitute the entire contract. If the application is so made a part of the contract, the policy shall also provide that all statements made by the applicant in such application shall, in the absence of fraud, be deemed to be representations and not warranties.

[ 1947 c 79 § .25.06; Rem. Supp. 1947 § 45.25.06; ]

== 48.25.070 - Incontestability.
There shall be a provision that the policy shall be incontestable after it has been in force during the lifetime of the insured for a period of two years from its date of issue except for nonpayment of premiums, and except, at the option of the insurer, as to supplemental provisions providing benefits for total and permanent disability or specifically for accidental death.

[ 1947 c 79 § .25.07; Rem. Supp. 1947 § 45.25.07; ]

== 48.25.080 - Misstatement of age.
There shall be a provision that if it is found that the age of the individual insured, or the age of any other individual considered in determining the premium, has been misstated, any amount payable or benefit accruing under the policy shall be such as the premium would have purchased at the correct age or ages.

[ 1947 c 79 § .25.08; Rem. Supp. 1947 § 45.25.08; ]

== 48.25.090 - Dividends.
If a participating policy, there shall be a provision that the insurer shall annually ascertain and apportion any divisible surplus accruing on the policy, and that dividends arising from such apportionment shall be credited annually beginning not later than the fifth contract year. This provision shall not prohibit the payment of additional dividends on default of payment of premiums or termination of the policy.

[ 1947 c 79 § .25.09; Rem. Supp. 1947 § 45.25.09; ]

== 48.25.100 - Nonforfeiture benefits.
There shall be a provision for nonforfeiture benefits as required by chapter 48.76 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%20152[1983 c 3 § 152]; 1947 c 79 § .25.10; Rem. Supp. 1947 § 45.25.10; ]

== 48.25.110 - Cash surrender value.
There shall be a provision for a cash surrender value as required by chapter 48.76 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%20153[1983 c 3 § 153]; 1947 c 79 § .25.11; Rem. Supp. 1947 § 45.25.11; ]

== 48.25.120 - Reinstatement.
There shall be a provision that the policy may be reinstated at any time within two years from the due date of the premium in default unless the cash surrender value has been paid, or the extension period expired, upon the production of evidence of insurability satisfactory to the insurer and the payment of all overdue premiums and payment or reinstatement of any unpaid loans or advances made by the insurer against the policy with interest at a rate not exceeding six percent per annum and payable annually.

[ 1947 c 79 § .25.12; Rem. Supp. 1947 § 45.25.12; ]

== 48.25.130 - Settlement.
There shall be a provision that when the policy becomes a claim by the death of the insured, settlement shall be made upon receipt of due proof of death or after a specified period not exceeding two months after receipt of such proof.

[ 1947 c 79 § .25.13; Rem. Supp. 1947 § 45.25.13; ]

== 48.25.140 - Authority to alter policy.
There shall be a provision that no insurance producer shall have the power or authority to waive, change, or alter any of the terms or conditions of any policy; except that, at the option of the insurer, the terms or conditions may be changed by an endorsement signed by a duly authorized officer of the insurer.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5316.SL.pdf?cite=2017%203rd%20sp.s.%20c%2025%20§%2017[2017 3rd sp.s. c 25 § 17]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6591.SL.pdf?cite=2008%20c%20217%20§%2033[2008 c 217 § 33]; 1947 c 79 § .25.14; Rem. Supp. 1947 § 45.25.14; ]

== 48.25.150 - Beneficiary.
. Each such policy shall have a space on the front or back page of the policy for the name of the beneficiary designated with a reservation of the right to designate or change the beneficiary after the issuance of the policy.

. The policy may also provide that no designation or change of beneficiary shall be binding on the insurer until endorsed on the policy by the insurer, and that the insurer may refuse to endorse the name of any proposed beneficiary who does not appear to the insurer to have an insurable interest in the life of the insured.

[ 1947 c 79 § .25.15; Rem. Supp. 1947 § 45.25.15; ]

== 48.25.160 - Facility of payment clause.
Such a policy may also provide that if the beneficiary designated in the policy does not surrender the policy with due proof of death within the period stated in the policy, which shall not be less than thirty days after the death of the insured, or if the beneficiary is the estate of the insured or is a minor, or dies before the insured or is not legally competent to give a valid release, then the insurer may make payment thereunder to the executor or administrator of the insured, or to any of the insured's relatives by blood or legal adoption or connection by marriage, or to any person appearing to the insurer to be equitably entitled thereto by reason of having been named beneficiary, or by reason of having incurred expense for the maintenance, medical attention or burial of the insured. Such policy may also include a similar provision applicable to any other payment due under the policy.

[ 1947 c 79 § .25.16; Rem. Supp. 1947 § 45.25.16; ]

== 48.25.170 - Payment of premiums direct.
In the case of weekly premium policies, there may be a provision that upon proper notice to the insurer while premiums on the policy are not in default beyond the grace period, of the intention to pay future premiums directly to the insurer at its home office or any office designated by the insurer for the purpose, the insurer will, at the end of each period of a year from the due date of the first premium so paid, for which period such premiums are so paid continuously without default beyond the grace period, refund a stated percentage of the premiums in an amount which fairly represents the savings in collection expense.

[ 1947 c 79 § .25.17; Rem. Supp. 1947 § 45.25.17; ]

== 48.25.180 - Conversion—Weekly premium policies.
There shall be a provision in the case of weekly premium policies granting, upon proper written request and upon presentation of evidence of the insurability of the insured satisfactory to the insurer, the privilege of converting his or her weekly premium industrial insurance to any form of life insurance with less frequent premium payments regularly issued by the insurer, in accordance with terms and conditions agreed upon with the insurer. The privilege of making such conversion need be granted only if the insurer's weekly premium industrial policies on the life insured, in force as premium paying insurance and on which conversion is requested, grant benefits in event of death, exclusive of additional accidental death benefits and exclusive of any dividend additions, in an amount not less than the minimum amount of such insurance with less frequent premium payments issued by the insurer at the age of the insured on the plan of industrial or ordinary insurance desired.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%207115[2009 c 549 § 7115]; 1947 c 79 § .25.18; Rem. Supp. 1947 § 45.25.18; ]

== 48.25.190 - Conversion—Monthly premium policies.
There shall be a provision, in the case of monthly premium industrial policies, granting, upon proper written request and upon presentation of evidence of the insurability of the insured satisfactory to the insurer, the privilege of converting his or her monthly premium industrial insurance to any form of ordinary life insurance regularly issued by the insurer, in accordance with terms and conditions agreed upon with the insurer. The privilege of making such conversions need be granted only if the insurer's monthly premium industrial policies on the life insured, in force as premium paying insurance and on which conversion is requested, grant benefits in event of death, exclusive of additional accidental death benefits and exclusive of any dividend additions, in an amount not less than the minimum amount of ordinary insurance issued by the insurer at the age of the insured on the plan of ordinary insurance desired.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%207116[2009 c 549 § 7116]; 1947 c 79 § .25.19; Rem. Supp. 1947 § 45.25.19; ]

== 48.25.200 - Title on policy.
There shall be a title on the face of each such policy briefly describing its form.

[ 1947 c 79 § .25.20; Rem. Supp. 1947 § 45.25.20; ]

== 48.25.210 - Application to term and specified insurance.
Any of the provisions required by this chapter or any portion thereof which are not applicable to single premium or term policies or to policies issued or granted pursuant to nonforfeiture provisions, shall to that extent not be incorporated therein.

[ 1947 c 79 § .25.21; Rem. Supp. 1947 § 45.25.21; ]

== 48.25.220 - Prohibited provisions.
No such policy shall contain:

. A provision by which the insurer may deny liability under the policy for the reason that the insured has previously obtained other insurance from the same insurer.

. A provision giving the insurer the right to declare the policy void because the insured has had any disease or ailment, whether specified or not, or because the insured has received institutional, hospital, medical or surgical treatment or attention, except a provision which gives the insurer the right to declare the policy void if the insured has, within two years prior to the issuance of the policy, received institutional, hospital, medical or surgical treatment or attention and if the insured or claimant under the policy fails to show that the condition occasioning such treatment or attention was not of a serious nature or was not material to the risk.

. A provision giving the insurer the right to declare the policy void because the insured had been rejected for insurance, unless such right be conditioned upon a showing by the insurer, that knowledge of such rejection would have led to a refusal by the insurer to make such contract.

[ 1947 c 79 § .25.22; Rem. Supp. 1947 § 45.25.22; ]

== 48.25.230 - Limitation of liability.
The insurer may in any such policy limit its liability for the same causes and to the same extent as is provided in RCW 48.23.260 for other life insurance contracts.

[ 1947 c 79 § .25.23; Rem. Supp. 1947 § 45.25.23; ]

== 48.25.900 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%20121[2009 c 521 § 121]; ]

