= 48.83 - Long-term care insurance coverage—Standards.
:toc:

== 48.83.005 - Intent.
The intent of this chapter is to promote the public interest, support the availability of long-term care coverage, establish standards for long-term care coverage, facilitate public understanding and comparison of long-term care contract benefits, protect persons insured under long-term care insurance policies and certificates, protect applicants for long-term care policies from unfair or deceptive sales or enrollment practices, and provide for flexibility and innovation in the development of long-term care insurance coverage.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2666-S.SL.pdf?cite=2008%20c%20145%20§%201[2008 c 145 § 1]; ]

== 48.83.010 - Application.
This chapter applies to all long-term care insurance policies, contracts, or riders delivered or issued for delivery in this state on or after January 1, 2009. This chapter does not supersede the obligations of entities subject to this chapter to comply with other applicable laws to the extent that they do not conflict with this chapter, except that laws and regulations designed and intended to apply to medicare supplement insurance policies shall not be applied to long-term care insurance.

. Coverage advertised, marketed, or offered as long-term care insurance shall comply with the provisions of this chapter. Any coverage, policy, or rider advertised, marketed, or offered as long-term care or nursing home insurance shall comply with the provisions of this chapter.

. Individual and group long-term care contracts issued prior to January 1, 2009, remain governed by chapter 48.84 RCW and rules adopted thereunder.

. This chapter is not intended to prohibit approval of long-term care funded through life insurance.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2666-S.SL.pdf?cite=2008%20c%20145%20§%202[2008 c 145 § 2]; ]

== 48.83.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Applicant" means: (a) In the case of an individual long-term care insurance policy, the person who seeks to contract for benefits; and (b) in the case of a group long-term care insurance policy, the proposed certificate holder.

. "Certificate" includes any certificate issued under a group long-term care insurance policy that has been delivered or issued for delivery in this state.

. "Commissioner" means the insurance commissioner of Washington state.

. "Issuer" includes insurance companies, fraternal benefit societies, health care service contractors, health maintenance organizations, or other entity delivering or issuing for delivery any long-term care insurance policy, contract, or rider.

. "Long-term care insurance" means an insurance policy, contract, or rider that is advertised, marketed, offered, or designed to provide coverage for at least twelve consecutive months for a covered person. Long-term care insurance may be on an expense incurred, indemnity, prepaid, or other basis, for one or more necessary or medically necessary diagnostic, preventive, therapeutic, rehabilitative, maintenance, or personal care services, provided in a setting other than an acute care unit of a hospital. Long-term care insurance includes any policy, contract, or rider that provides for payment of benefits based upon cognitive impairment or the loss of functional capacity.

.. Long-term care insurance includes group and individual annuities and life insurance policies or riders that provide directly or supplement long-term care insurance. However, long-term care insurance does not include life insurance policies that: (i) Accelerate the death benefit specifically for one or more of the qualifying events of terminal illness, medical conditions requiring extraordinary medical intervention, or permanent institutional confinement; (ii) provide the option of a lump sum payment for those benefits; and (iii) do not condition the benefits or the eligibility for the benefits upon the receipt of long-term care.

.. Long-term care insurance also includes qualified long-term care insurance contracts.

.. Long-term care insurance does not include any insurance policy, contract, or rider that is offered primarily to provide coverage for basic medicare supplement, basic hospital expense, basic medical-surgical expense, hospital confinement indemnity, major medical expense, disability income, related income, asset protection, accident only, specified disease, specified accident, or limited benefit health.

. "Group long-term care insurance" means a long-term care insurance policy or contract that is delivered or issued for delivery in this state and is issued to:

.. One or more employers; one or more labor organizations; or a trust or the trustees of a fund established by one or more employers or labor organizations for current or former employees, current or former members of the labor organizations, or a combination of current and former employees or members, or a combination of such employers, labor organizations, trusts, or trustees; or

.. A professional, trade, or occupational association for its members or former or retired members, if the association:

... Is composed of persons who are or were all actively engaged in the same profession, trade, or occupation; and

... Has been maintained in good faith for purposes other than obtaining insurance; or

.. [Empty]
... An association, trust, or the trustees of a fund established, created, or maintained for the benefit of members of one or more associations. Before advertising, marketing, or offering long-term care coverage in this state, the association or associations, or the insurer of the association or associations, must file evidence with the commissioner that the association or associations have at the time of such filing at least one hundred persons who are members and that the association or associations have been organized and maintained in good faith for purposes other than that of obtaining insurance; have been in active existence for at least one year; and have a constitution and bylaws that provide that:

(A) The association or associations hold regular meetings at least annually to further the purposes of the members;

(B) Except for credit unions, the association or associations collect dues or solicit contributions from members; and

(C) The members have voting privileges and representation on the governing board and committees of the association. 

... Thirty days after filing the evidence in accordance with this section, the association or associations will be deemed to have satisfied the organizational requirements, unless the commissioner makes a finding that the association or associations do not satisfy those organizational requirements; [or]

.. A group other than as described in (a), (b), or (c) of this subsection subject to a finding by the commissioner that:

... The issuance of the group policy is not contrary to the best interest of the public;

... The issuance of the group policy would result in economies of acquisition or administration; and

... The benefits are reasonable in relation to the premiums charged.

. "Policy" includes a document such as an insurance policy, contract, subscriber agreement, rider, or endorsement delivered or issued for delivery in this state by an insurer, fraternal benefit society, health care service contractor, health maintenance organization, or any similar entity authorized by the insurance commissioner to transact the business of long-term care insurance.

. "Qualified long-term care insurance contract" or "federally tax-qualified long-term care insurance contract" means:

.. An individual or group insurance contract that meets the requirements of section 7702B(b) of the internal revenue code of 1986, as amended; or

 (b) The portion of a life insurance contract that provides long-term care insurance coverage by rider or as part of the contract and that satisfies the requirements of sections 7702B(b) and (e) of the internal revenue code of 1986, as amended.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2666-S.SL.pdf?cite=2008%20c%20145%20§%203[2008 c 145 § 3]; ]

== 48.83.030 - Out-of-state policy—Restriction.
A group long-term care insurance policy may not be offered to a resident of this state under a group policy issued in another state to a group described in RCW 48.83.020(6)(d), unless this state or another state having statutory and regulatory long-term care insurance requirements substantially similar to those adopted in this state has made a determination that such requirements have been met.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2666-S.SL.pdf?cite=2008%20c%20145%20§%204[2008 c 145 § 4]; ]

== 48.83.040 - Preexisting conditions.
. A long-term care insurance policy or certificate may not define "preexisting condition" more restrictively than as a condition for which medical advice or treatment was recommended by or received from a provider of health care services, within six months preceding the effective date of coverage of an insured person, unless the policy or certificate applies to group long-term care insurance under RCW 48.83.020(6) (a), (b), or (c).

. A long-term care insurance policy or certificate may not exclude coverage for a loss or confinement that is the result of a preexisting condition unless the loss or confinement begins within six months following the effective date of coverage of an insured person, unless the policy or certificate applies to a group as defined in RCW 48.83.020(6)(a).

. The commissioner may extend the limitation periods for specific age group categories in specific policy forms upon finding that the extension is in the best interest of the public.

. An issuer may use an application form designed to elicit the complete health history of an applicant and underwrite in accordance with that issuer's established underwriting standards, based on the answers on that application. Unless otherwise provided in the policy or certificate and regardless of whether it is disclosed on the application, a preexisting condition need not be covered until the waiting period expires.

. A long-term care insurance policy or certificate may not exclude or use waivers or riders to exclude, limit, or reduce coverage or benefits for specifically named or described preexisting diseases or physical conditions beyond the waiting period.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2666-S.SL.pdf?cite=2008%20c%20145%20§%205[2008 c 145 § 5]; ]

== 48.83.050 - Prohibited policy terms and practices—Field-issued, defined.
No long-term care insurance policy may:

. Be canceled, nonrenewed, or otherwise terminated on the grounds of the age or the deterioration of the mental or physical health of the insured individual or certificate holder;

. Contain a provision establishing a new waiting period in the event existing coverage is converted to or replaced by a new or other form within the same company, except with respect to an increase in benefits voluntarily selected by the insured individual or group policyholder;

. Provide coverage for skilled nursing care only or provide significantly more coverage for skilled care in a facility than coverage for lower levels of care;

. Condition eligibility for any benefits on a prior hospitalization requirement;

. Condition eligibility for benefits provided in an institutional care setting on the receipt of a higher level of institutional care;

. Condition eligibility for any benefits other than waiver of premium, postconfinement, postacute care, or recuperative benefits on a prior institutionalization requirement;

. Include a postconfinement, postacute care, or recuperative benefit unless:

.. Such requirement is clearly labeled in a separate paragraph of the policy or certificate entitled "Limitations or Conditions on Eligibility for Benefits"; and

.. Such limitations or conditions specify any required number of days of preconfinement or postconfinement;

. Condition eligibility for noninstitutional benefits on the prior receipt of institutional care;

. A long-term care insurance policy or certificate may be field-issued if the compensation to the field issuer is not based on the number of policies or certificates issued. For purposes of this section, "field-issued" means a policy or certificate issued by a producer or a third-party administrator of the policy pursuant to the underwriting authority by an issuer and using the issuer's underwriting guidelines.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2666-S.SL.pdf?cite=2008%20c%20145%20§%206[2008 c 145 § 6]; ]

== 48.83.060 - Right to return policy or certificate—Refund.
. Long-term care insurance applicants may return a policy or certificate for any reason within thirty days after its delivery and to have the premium refunded.

. All long-term care insurance policies and certificates shall have a notice prominently printed on or attached to the first page of the policy stating that the applicant may return the policy or certificate within thirty days after its delivery and to have the premium refunded.

. Refunds or denials of applications must be made within thirty days of the return or denial.

. This section shall not apply to certificates issued pursuant to a policy issued to a group defined in RCW 48.83.020(6)(a).

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2666-S.SL.pdf?cite=2008%20c%20145%20§%207[2008 c 145 § 7]; ]

== 48.83.070 - Required documents for prospective and approved applicants—Contents—When due.
. An outline of coverage must be delivered to a prospective applicant for long-term care insurance at the time of initial solicitation through means that prominently direct the attention of the recipient to the document and its purpose.

.. The commissioner must prescribe a standard format, including style, arrangement, overall appearance, and the content of an outline of coverage.

.. When an insurance producer makes a solicitation in person, he or she must deliver an outline of coverage before presenting an application or enrollment form.

.. In a direct response solicitation, the outline of coverage must be presented with an application or enrollment form.

.. If a policy is issued to a group as defined in RCW 48.83.020(6)(a), an outline of coverage is not required to be delivered, if the information that the commissioner requires to be included in the outline of coverage is in other materials relating to enrollment. Upon request, any such materials must be made available to the commissioner.

. If an issuer approves an application for a long-term care insurance contract or certificate, the issuer must deliver the contract or certificate of insurance to the applicant within thirty days after the date of approval. A policy summary must be delivered with an individual life insurance policy that provides long-term care benefits within the policy or by rider. In a direct response solicitation, the issuer must deliver the policy summary, upon request, before delivery of the policy, if the applicant requests a summary.

.. The policy summary shall include:

... An explanation of how the long-term care benefit interacts with other components of the policy, including deductions from any applicable death benefits;

... An illustration of the amount of benefits, the length of benefits, and the guaranteed lifetime benefits if any, for each covered person;

... Any exclusions, reductions, and limitations on benefits of long-term care;

... A statement that any long-term care inflation protection option required by RCW 48.83.110 is not available under this policy; and

.. If applicable to the policy type, the summary must also include:

(A) A disclosure of the effects of exercising other rights under the policy;

(B) A disclosure of guarantees related to long-term care costs of insurance charges; and

(C) Current and projected maximum lifetime benefits.

.. The provisions of the policy summary may be incorporated into a basic illustration required under chapter 48.23A RCW, or into the policy summary which is required under rules adopted by the commissioner.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2666-S.SL.pdf?cite=2008%20c%20145%20§%208[2008 c 145 § 8]; ]

== 48.83.080 - Benefit funded through life insurance policy—Acceleration of a death benefit.
If a long-term care benefit funded through a life insurance policy by the acceleration of the death benefit is in benefit payment status, a monthly report must be provided to the policyholder. The report must include:

. A record of all long-term care benefits paid out during the month;

. An explanation of any changes in the policy resulting from paying the long-term care benefits, such as a change in the death benefit or cash values; and

. The amount of long-term care benefits that remain to be paid.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2666-S.SL.pdf?cite=2008%20c%20145%20§%209[2008 c 145 § 9]; ]

== 48.83.090 - Denial of claims—Written explanation.
All long-term care denials must be made within thirty days after receipt of a written request made by a policyholder or certificate holder, or his or her representative. All denials of long-term care claims by the issuer must provide a written explanation of the reasons for the denial and make available to the policyholder or certificate holder all information directly related to the denial.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5216.SL.pdf?cite=2013%20c%208%20§%201[2013 c 8 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2666-S.SL.pdf?cite=2008%20c%20145%20§%2010[2008 c 145 § 10]; ]

== 48.83.100 - Rescission of policy or certificate.
. An issuer may rescind a long-term care insurance policy or certificate or deny an otherwise valid long-term care insurance claim if:

.. A policy or certificate has been in force for less than six months and upon a showing of misrepresentation that is material to the acceptance for coverage; or

.. A policy or certificate that has been in force for at least six months but less than two years, upon a showing of misrepresentation that is both material to the acceptance for coverage and that pertains to the condition for which benefits are sought.

. After a policy or certificate has been in force for two years it is not contestable upon the grounds of misrepresentation alone. Such a policy or certificate may be contested only upon a showing that the insured knowingly and intentionally misrepresented relevant facts relating to the insured's health.

. An issuer's payments for benefits under a long-term care insurance policy or certificate may not be recovered by the issuer if the policy or certificate is rescinded.

. This section does not apply to the remaining death benefit of a life insurance policy that accelerates benefits for long-term care that are governed by RCW 48.23.050 the state's life insurance incontestability clause. In all other situations, this section shall apply to life insurance policies that accelerate benefits for long-term care.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2666-S.SL.pdf?cite=2008%20c%20145%20§%2011[2008 c 145 § 11]; ]

== 48.83.110 - Inflation protection features—Rules.
. The commissioner must establish minimum standards for inflation protection features.

. An issuer must comply with the rules adopted by the commissioner that establish minimum standards for inflation protection features.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2666-S.SL.pdf?cite=2008%20c%20145%20§%2012[2008 c 145 § 12]; ]

== 48.83.120 - Nonforfeiture benefit option—Offer required—Rules.
. Except as provided by this section, a long-term care insurance policy may not be delivered or issued for delivery in this state unless the policyholder or certificate holder has been offered the option of purchasing a policy or certificate that includes a nonforfeiture benefit. The offer of a nonforfeiture benefit may be in the form of a rider that is attached to the policy. If a policyholder or certificate holder declines the nonforfeiture benefit, the issuer must provide a contingent benefit upon lapse that is available for a specified period of time following a substantial increase in premium rates.

. If a group long-term care insurance policy is issued, the offer required in subsection (1) of this section must be made to the group policyholder. However, if the policy is issued as group long-term care insurance as defined in RCW 48.83.020(6)(d) other than to a continuing care retirement community or other similar entity, the offering shall be made to each proposed certificate holder.

. The commissioner must adopt rules specifying the type or types of nonforfeiture benefits to be offered as part of long-term care insurance policies and certificates, the standards for nonforfeiture benefits, and the rules regarding contingent benefit upon lapse, including a determination of the specified period of time during which a contingent benefit upon lapse will be available and the substantial premium rate increase that triggers a contingent benefit upon lapse.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2666-S.SL.pdf?cite=2008%20c%20145%20§%2013[2008 c 145 § 13]; ]

== 48.83.130 - Selling, soliciting, or negotiating coverage—Licensed insurance producers—Training—Issuers duties—Rules.
A person may not sell, solicit, or negotiate long-term care insurance unless he or she is appropriately licensed as an insurance producer and has successfully completed long-term care coverage education that meets the requirements of this section.

. All long-term care education required by this chapter must meet the requirements of chapter 48.17 RCW and rules adopted by the commissioner.

. [Empty]
.. [Empty]
... After January 1, 2009, prior to soliciting, selling, or negotiating long-term care insurance coverage, an insurance producer must successfully complete a one-time education course consisting of no fewer than eight hours on long-term care coverage, long-term care services, state and federal regulations and requirements for long-term care and qualified long-term care insurance coverage, changes or improvements in long-term care services or providers, alternatives to the purchase of long-term care insurance coverage, the effect of inflation on benefits and the importance of inflation protection, and consumer suitability standards and guidelines.

... In order to continue soliciting, selling, or negotiating long-term care coverage in this state, all insurance producers selling, soliciting, or negotiating long-term care insurance coverage prior to January 1, 2009, must successfully complete the eight-hour, one-time long-term care education and training course no later than July 1, 2009.

.. In addition to the one-time education and training requirement set forth in (a) of this subsection, insurance producers who engage in the solicitation, sale, or negotiation of long-term care insurance coverage must successfully complete no fewer than four hours every twenty-four months of continuing education specific to long-term care insurance coverage and issues. Long-term care insurance coverage continuing education shall consist of topics related to long-term care insurance, long-term care services, and, if applicable, qualified state long-term care insurance partnership programs, including, but not limited to, the following:

... State and federal regulations and requirements and the relationship between qualified state long-term care insurance partnership programs and other public and private coverage of long-term care services, including medicaid; 

... Available long-term care services and providers;

... Changes or improvements in long-term care services or providers;

... Alternatives to the purchase of private long-term care insurance;

.. The effect of inflation on benefits and the importance of inflation protection;

.. This chapter and chapters 48.84 and 48.85 RCW; and

.. Consumer suitability standards and guidelines.

. The insurance producer education required by this section shall not include training that is issuer or company product-specific or that includes any sales or marketing information, materials, or training, other than those required by state or federal law.

. Issuers shall obtain verification that an insurance producer receives training required by this section before that producer is permitted to sell, solicit, or otherwise negotiate the issuer's long-term care insurance products.

. Issuers shall maintain records subject to the state's record retention requirements and shall make evidence of that verification available to the commissioner upon request.

. [Empty]
.. Issuers shall maintain records with respect to the training of its producers concerning the distribution of its long-term care partnership policies that will allow the commissioner to provide assurance to the state department of social and health services, medicaid division, that insurance producers engaged in the sale of long-term care insurance contracts have received the training required by this section and any rules adopted by the commissioner, and that producers have demonstrated an understanding of the partnership policies and their relationship to public and private coverage of long-term care, including medicaid, in this state.

.. These records shall be maintained in accordance with the state's record retention requirements and shall be made available to the commissioner upon request. 

. The satisfaction of these training requirements for any state shall be deemed to satisfy the training requirements of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2666-S.SL.pdf?cite=2008%20c%20145%20§%2014[2008 c 145 § 14]; ]

== 48.83.140 - Determining whether coverage is appropriate—Suitability standards—Information protected—Rules.
Issuers and their agents, if any, must determine whether issuing long-term care insurance coverage to a particular person is appropriate, except in the case of a life insurance policy that accelerates benefits for long-term care. 

. An issuer must:

.. Develop and use suitability standards to determine whether the purchase or replacement of long-term care coverage is appropriate for the needs of the applicant or insured;

.. Train its agents in the use of the issuer's suitability standards; and

.. Maintain a copy of its suitability standards and make the standards available for inspection, upon request.

. The following must be considered when determining whether the applicant meets the issuer's suitability standards:

.. The ability of the applicant to pay for the proposed coverage and any other relevant financial information related to the purchase of or payment for coverage;

.. The applicant's goals and needs with respect to long-term care and the advantages and disadvantages of long-term care coverage to meet those goals or needs; and

.. The values, benefits, and costs of the applicant's existing health or long-term care coverage, if any, when compared to the values, benefits, and costs of the recommended purchase or replacement.

. The sale or transfer of any suitability information provided to the issuer or agent by the applicant to any other person or business entity is prohibited.

. [Empty]
.. The commissioner shall adopt, by rule, forms of consumer-friendly personal worksheets that issuers and their agents must use for applications for long-term care coverage.

.. The commissioner may require each issuer to file its current forms of suitability standards and personal worksheets with the commissioner.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2666-S.SL.pdf?cite=2008%20c%20145%20§%2015[2008 c 145 § 15]; ]

== 48.83.150 - Prohibited practices.
A person engaged in the issuance or solicitation of long-term care coverage shall not engage in unfair methods of competition or unfair or deceptive acts or practices, as such methods, acts, or practices are defined in chapter 48.30 RCW, or as defined by the commissioner.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2666-S.SL.pdf?cite=2008%20c%20145%20§%2016[2008 c 145 § 16]; ]

== 48.83.160 - Violations—Fine.
An issuer or an insurance producer who violates a law or rule relating to the regulation of long-term care insurance or its marketing shall be subject to a fine of up to three times the amount of the commission paid for each policy involved in the violation or up to ten thousand dollars, whichever is greater.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2666-S.SL.pdf?cite=2008%20c%20145%20§%2017[2008 c 145 § 17]; ]

== 48.83.170 - Rules, generally.
. The commissioner must adopt rules that include standards for full and fair disclosure setting forth the manner, content, and required disclosures for the sale of long-term care insurance policies, terms of renewability, initial and subsequent conditions of eligibility, nonduplication of coverage provisions, coverage of dependents, preexisting conditions, termination of insurance, continuation or conversion, probationary periods, limitations, exceptions, reductions, elimination periods, requirements for replacement, recurrent conditions, and definitions of terms. The commissioner must adopt rules establishing loss ratio standards for long-term care insurance policies. The commissioner must adopt rules to promote premium adequacy and to protect policyholders in the event of proposed substantial rate increases, and to establish minimum standards for producer education, marketing practices, producer compensation, producer testing, penalties, and reporting practices for long-term care insurance.

. The commissioner must adopt rules establishing standards protecting patient privacy rights, rights to receive confidential health care services, and standards for an issuer's timely review of a claim denial upon request of a covered person.

. The commissioner must adopt by rule prompt payment requirements for long-term care insurance. The rules must include a definition of a "claim" and a definition of "clean claim." In adopting the rules the commissioner must consider the prompt payment requirements in long-term care insurance model acts developed by the national association of insurance commissioners.

. The commissioner may adopt reasonable rules to effectuate any provision of this chapter in accordance with the requirements of chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5216.SL.pdf?cite=2013%20c%208%20§%202[2013 c 8 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2666-S.SL.pdf?cite=2008%20c%20145%20§%2018[2008 c 145 § 18]; ]

== 48.83.901 - Effective date—2008 c 145.
This act takes effect January 1, 2009.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2666-S.SL.pdf?cite=2008%20c%20145%20§%2024[2008 c 145 § 24]; ]

