= 48.38 - Charitable gift annuity business.
:toc:

== 48.38.010 - Certificate of exemption—Qualification for—Application, contents—Minimum unrestricted net assets—"Qualified actuary" defined.
The commissioner may grant a certificate of exemption to any insurer or educational, religious, charitable, or scientific institution conducting a charitable gift annuity business:

. Which is organized and operated exclusively as, or for the purpose of aiding, an educational, religious, charitable, or scientific institution which is organized as a nonprofit organization without profit to any person, firm, partnership, association, corporation, or other entity;

. Which possesses a current tax exempt status under the laws of the United States;

. Which serves such purpose by issuing charitable gift annuity contracts only for the benefit of such educational, religious, charitable, or scientific institution;

. Which appoints the insurance commissioner as its true and lawful attorney upon whom may be served lawful process in any action, suit, or proceeding in any court, which appointment is irrevocable, binds the insurer or institution or any successor in interest, remains in effect as long as there is in force in this state any contract made or issued by the insurer or institution, or any obligation arising therefrom, and must be processed in accordance with RCW 48.05.200;

. Which is fully and legally organized and qualified to do business and has been actively doing business under the laws of the state of its domicile for a period of at least three years prior to its application for a certificate of exemption;

. Which has and maintains minimum unrestricted net assets of five hundred thousand dollars. "Unrestricted net assets" means the excess of total assets over total liabilities that are neither permanently restricted nor temporarily restricted by donor-imposed stipulations;

. Which files with the insurance commissioner its application for a certificate of exemption showing:

.. Its name, location, and organization date;

.. The kinds of charitable annuities it proposes to offer;

.. A statement of the financial condition, management, and affairs of the organization and any affiliate thereof, as that term is defined in RCW 48.31B.005, on a form satisfactory to, or furnished by the insurance commissioner;

.. Other documents, stipulations, or information as the insurance commissioner may reasonably require to evidence compliance with the provisions of this chapter;

. Which subjects itself and any affiliate thereof, as that term is defined in RCW 48.31B.005, to periodic examinations conducted under chapter 48.03 RCW as may be deemed necessary by the insurance commissioner;

. Which files with the insurance commissioner for the commissioner's advance approval a copy of any policy or contract form to be offered or issued to residents of this state. The grounds for disapproval of the policy or contract form are set forth in RCW 48.18.110; and

. Which:

.. Files with the insurance commissioner annually, within sixty days of the end of its fiscal year a report of its current financial condition, management, and affairs, on a form and in a manner prescribed by the commissioner, as well as such other financial material as may be requested, including the annual statement or other such financial materials as may be requested relating to any affiliate, as that term is defined in RCW 48.31B.005;

.. Attaches to the report of its current financial condition the statement of a qualified actuary setting forth the actuary's opinion relating to annuity reserves and other actuarial items for the fiscal year covered by the report. "Qualified actuary" as used in this subsection means a member in good standing of the American academy of actuaries or a person who has otherwise demonstrated actuarial competence to the satisfaction of the insurance regulatory official of the domiciliary state; and

.. On or before March 1st of each year, pays an annual filing fee of twenty-five dollars plus five dollars for each charitable gift annuity contract written for residents of this state during its fiscal year ending on or before December 31st of the previous calendar year.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2523.SL.pdf?cite=2012%20c%20211%20§%205[2012 c 211 § 5]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2585-S.SL.pdf?cite=2010%20c%2027%20§%202[2010 c 27 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2550.SL.pdf?cite=1998%20c%20284%20§%201[1998 c 284 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c130.pdf?cite=1979%20c%20130%20§%206[1979 c 130 § 6]; ]

== 48.38.012 - Minimum unrestricted net assets required.
After June 30, 1998, an insurer or institution which does not have the minimum unrestricted net assets required by RCW 48.38.010(6) may not issue any new charitable gift annuities until the insurer or institution has and maintains the minimum unrestricted net assets required by RCW 48.38.010(6).

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2550.SL.pdf?cite=1998%20c%20284%20§%207[1998 c 284 § 7]; ]

== 48.38.020 - Separate reserve fund—Treatment of assets—Minimum amounts—Purchase of single premium life annuity.
. Upon granting to such insurer or institution under RCW 48.38.010 a certificate of exemption to conduct a charitable gift annuity business, the insurance commissioner shall require it to establish and maintain a separate reserve fund adequate to meet the future payments under its charitable gift annuity contracts.

. The assets of the separate reserve fund:

.. Shall be held legally and physically segregated from the other assets of the certificate of exemption holder;

.. Shall be invested in the same manner that persons of reasonable prudence, discretion, and intelligence exercise in the management of a like enterprise, not in regard to speculating but in regard to the permanent disposition of their funds, considering the probable income as well as the probable safety of their capital. Investments shall be of sufficient value, liquidity, and diversity to assure the insurer or institution's ability to meet its outstanding obligations; and

.. Shall not be liable for any debts of the insurer or institution holding a certificate of exemption under this chapter, other than those incurred pursuant to the issuance of charitable gift annuities.

. The amount of the separate reserve fund shall be:

.. For contracts issued prior to July 1, 1998, not less than an amount computed in accordance with the standard of valuation based on the 1971 individual annuity mortality table with six percent interest for single premium immediate annuity contracts and four percent interest for all other individual annuity contracts;

.. For contracts issued on or after July 1, 1998, in an amount not less than the aggregate reserves calculated according to the standards set forth in RCW 48.74.030 for other annuities with no cash settlement options;

.. Plus a surplus of ten percent of the combined amounts under (a) and (b) of this subsection.

. The general assets of the insurer or institution holding a certificate of exemption under this chapter shall be liable for the payment of annuities to the extent that the separate reserve fund is inadequate.

. If an institution holding a certificate of exemption under RCW 48.38.010 has purchased a single premium life annuity that pays the entire amount stipulated in the gift annuity agreement or agreements from an insurer (a) holding a certificate of authority under chapter 48.05 RCW, (b) licensed in the state in which the institution has its principle office, and (c) licensed in the state in which the single premium life annuity is issued, then in determining the minimum reserve fund that must be maintained under this section, a deduction shall be allowed from the minimum reserve fund in an amount not exceeding the reserve fund amount required for the annuity or annuities for which the single premium life annuity is purchased, subject to the following conditions:

... The institution has filed with the commissioner a copy of the single premium life annuity purchased and specifying which charitable gift annuity or annuities are being insured; and

... The institution has entered into a written agreement with the annuitant and the insurer issuing the single premium life annuity providing that if for any reason the institution is unable to continue making the annuity payments required by its annuity agreements, the annuitants shall receive payments directly from the insurer and the insurer shall be credited with all of these direct payments in the accounts between the insurer and the institution.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2523.SL.pdf?cite=2012%20c%20211%20§%206[2012 c 211 § 6]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2160-S.SL.pdf?cite=2002%20c%20295%20§%201[2002 c 295 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2550.SL.pdf?cite=1998%20c%20284%20§%202[1998 c 284 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c130.pdf?cite=1979%20c%20130%20§%207[1979 c 130 § 7]; ]

== 48.38.030 - Charitable annuity contract or policy form—Contents.
Each charitable annuity contract or policy form must include the following information:

. The value of the property to be transferred;

. The amount of the annuity to be paid to the transferor or the transferor's nominee;

. The manner in which and the intervals at which payment is to be made;

. The age of the person during whose life payment is to be made; and

. The reasonable value as of the date of the agreement of the benefits created. This value may not exceed by more than fifteen percent the net single premium for the benefits, determined according to the standard of valuation set forth in RCW 48.38.020(3).

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1197-S.SL.pdf?cite=2005%20c%20223%20§%2024[2005 c 223 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c130.pdf?cite=1979%20c%20130%20§%208[1979 c 130 § 8]; ]

== 48.38.040 - Certificate holder exempt from certain title provisions—Chapter  48.31 RCW applies.
. An insurer or institution holding a certificate of exemption under this chapter shall be exempt from all other provisions of this title except as specifically enumerated in this chapter by reference.

. An insurer or institution holding a certificate of exemption under this chapter is subject to chapter 48.31 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2550.SL.pdf?cite=1998%20c%20284%20§%203[1998 c 284 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c130.pdf?cite=1979%20c%20130%20§%209[1979 c 130 § 9]; ]

== 48.38.042 - Certificate holder—Variable annuity business prohibited.
An insurer or institution holding a certificate of exemption to issue charitable gift annuities under this chapter shall not transact or be authorized to transact a variable annuity business as described in chapter 48.18A RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2550.SL.pdf?cite=1998%20c%20284%20§%205[1998 c 284 § 5]; ]

== 48.38.050 - Grounds for denial, revocation, or suspension of certificate of exemption—Fine may be levied.
. The insurance commissioner may refuse to grant, or may revoke or suspend, a certificate of exemption if the insurance commissioner finds that the insurer or institution does not meet the requirements of this chapter or if the insurance commissioner finds that the insurer or institution has violated RCW 48.01.030, any provisions of chapter 48.30 RCW, or this chapter, and any applicable provisions of Title 284 WAC, or is found by the insurance commissioner to be in such condition that its further issuance of charitable gift annuities would be hazardous to annuity contract holders and the people of this state.

. After hearing or with the consent of the insurer or institution and in addition to or in lieu of the suspension, revocation, or refusal to renew any certificate of exemption, the commissioner may levy a fine upon the insurer or institution in an amount not more than ten thousand dollars. The order levying such a fine shall specify the period within which the fine shall be fully paid and which period shall not be less than fifteen nor more than thirty days from the date of the order. Upon failure to pay such a fine when due the commissioner may revoke the certificate of exemption of the insurer or institution if not already revoked, and the fine shall be recovered in a civil action brought in behalf of the commissioner by the attorney general. Any fine so collected shall be paid by the commissioner to the state treasurer for the account of the general fund.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2523.SL.pdf?cite=2012%20c%20211%20§%207[2012 c 211 § 7]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2550.SL.pdf?cite=1998%20c%20284%20§%204[1998 c 284 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c130.pdf?cite=1979%20c%20130%20§%2010[1979 c 130 § 10]; ]

== 48.38.060 - Hearings and appeals provisions inapplicable.
For purposes of this chapter, the provisions of chapter 48.04 RCW are applicable.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c130.pdf?cite=1979%20c%20130%20§%2011[1979 c 130 § 11]; ]

== 48.38.070 - Enforcement powers and duties.
For the purposes of this chapter, the insurance commissioner has the same powers and duties of enforcement as are provided in RCW 48.02.080.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c130.pdf?cite=1979%20c%20130%20§%2012[1979 c 130 § 12]; ]

== 48.38.075 - Rules.
The commissioner may adopt rules to implement and administer this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2550.SL.pdf?cite=1998%20c%20284%20§%206[1998 c 284 § 6]; ]

