= 48.34 - Credit life insurance and credit accident and health insurance.
:toc:

== 48.34.010 - Declaration of purpose—Liberal construction.
The purpose of this chapter is to promote the public welfare by regulating credit life insurance and credit accident and health insurance. Nothing in this chapter is intended to prohibit or discourage reasonable competition. The provisions of this chapter shall be liberally construed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c219.pdf?cite=1961%20c%20219%20§%201[1961 c 219 § 1]; ]

== 48.34.020 - Chapter part of insurance code—What insurance subject to chapter.
. This chapter is a part of the insurance code.

. All life insurance and all accident and health insurance in connection with loans or other credit transactions shall be subject to the provisions of this chapter, except such insurance under an individual policy in connection with a loan or other credit transaction of more than ten years duration. Insurance shall not be subject to the provisions of this chapter where its issuance is an isolated transaction on the part of the insurer not related to an agreement or a plan for insuring debtors of the creditor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c241.pdf?cite=1969%20ex.s.%20c%20241%20§%2014[1969 ex.s. c 241 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c219.pdf?cite=1961%20c%20219%20§%202[1961 c 219 § 2]; ]

== 48.34.030 - Definitions.
For the purpose of this chapter: (1) "Credit life insurance" means insurance on the life of a debtor pursuant to or in connection with a specific loan or other credit transaction;

. "Credit accident and health insurance" means insurance on a debtor to provide indemnity for payments becoming due on a specific loan or other credit transaction while the debtor is disabled as defined in the policy;

. "Creditor" means the lender of money or vendor or lessor of goods, services, properties, rights, or privileges, for which payment is arranged through a credit transaction, or any successor to the right, title, or interest of any such lender, vendor, or lessor, and an affiliate, associate, or subsidiary of any of them or a director, officer, or employee of any of them or any other person in any way associated with any of them;

. "Debtor" means a borrower of money or a purchaser or lessee of goods, services, properties, rights, or privileges for which payment is arranged through a credit transaction;

. "Indebtedness" means the total amount payable by a debtor to a creditor in connection with the loan or other credit transaction.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c219.pdf?cite=1961%20c%20219%20§%203[1961 c 219 § 3]; ]

== 48.34.040 - Authorized forms.
Credit life insurance and credit accident and health insurance shall be issued only in the following forms:

. Individual policies of life insurance issued to debtors on the term plan;

. Individual policies of accident and health insurance issued to debtors on a term plan, or disability benefit provisions in individual policies of credit life insurance;

. Group policies of life insurance issued to creditors providing insurance upon the lives of debtors on the term plan;

. Group policies of accident and health insurance issued to creditors on a term plan insuring debtors, or disability benefit provisions in group credit life insurance policies to provide such coverage.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c219.pdf?cite=1961%20c%20219%20§%204[1961 c 219 § 4]; ]

== 48.34.050 - Life—Limitation on amount under individual policy.
The initial amount of credit life insurance under an individual policy shall not exceed the total amount repayable under the contract of indebtedness. Where an indebtedness is repayable in substantially equal installments, the amount of insurance shall at no time exceed the scheduled or actual amount of unpaid indebtedness, whichever is greater.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c219.pdf?cite=1961%20c%20219%20§%205[1961 c 219 § 5]; ]

== 48.34.060 - Life—Limitation on amount repayable under group policy.
The initial amount of credit life insurance under a group policy shall at no time exceed the amount owed by the debtor which is repayable in installments to the creditor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c130.pdf?cite=1987%20c%20130%20§%201[1987 c 130 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c32.pdf?cite=1983%201st%20ex.s.%20c%2032%20§%2023[1983 1st ex.s. c 32 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977c61.pdf?cite=1977%20c%2061%20§%202[1977 c 61 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c82.pdf?cite=1967%20ex.s.%20c%2082%20§%201[1967 ex.s. c 82 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c219.pdf?cite=1961%20c%20219%20§%206[1961 c 219 § 6]; ]

== 48.34.070 - Accident and health—Limitation on amount.
The total amount of periodic indemnity payable by credit accident and health insurance in the event of disability, as defined in the policy, shall not exceed the aggregate of the periodic scheduled unpaid installments of the indebtedness; and the amount of such periodic indemnity payment shall not exceed the original indebtedness divided by the number of periodic installments.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c219.pdf?cite=1961%20c%20219%20§%207[1961 c 219 § 7]; ]

== 48.34.080 - Commencement, termination date of term.
The term of any credit life insurance or credit accident and health insurance shall, subject to acceptance by the insurer, commence on the date when the debtor becomes obligated to the creditor: PROVIDED, That, where a group policy provides coverage with respect to existing obligations, the insurance on a debtor with respect to such indebtedness shall commence on the effective date of the policy. Where evidence of insurability is required and such evidence is furnished more than thirty days after the date when the debtor becomes obligated to the creditor, the term of the insurance may commence on the date on which the insurance company determines the evidence to be satisfactory, and in such event there shall be an appropriate refund or adjustment of any charge to the debtor for insurance. The term of such insurance shall not extend more than fifteen days beyond the scheduled maturity date of indebtedness, except when extended without additional cost to the debtor. If the indebtedness is discharged due to renewal or refinancing prior to the scheduled maturity date, the insurance in force shall be terminated before any new insurance may be issued in connection with renewed or refinanced indebtedness. In all cases of termination prior to scheduled maturity, a refund shall be paid or credited as provided in RCW 48.34.110.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c219.pdf?cite=1961%20c%20219%20§%208[1961 c 219 § 8]; ]

== 48.34.090 - Policy or certificate—Contents—Delivery, copy of application or notice in lieu—Substitute insurer, premium, etc., on rejection.
. All credit life insurance and credit accident and health insurance shall be evidenced by an individual policy, or in the case of group insurance by a certificate of insurance, which individual policy or group certificate of insurance shall be delivered to the debtor.

. Each individual policy or group certificate of credit life insurance, and/or credit accident and health insurance shall, in addition to other requirements of law, set forth the name and home office address of the insurer, the name or names of the debtor or in the case of a certificate under a group policy, the identity by name or otherwise of the debtor, the premium or amount of payment, if any, by the debtor separately for credit life insurance and credit accident and health insurance, a description of the coverage including the amount and term thereof, and any exceptions, limitations and restrictions, and shall state that the benefits shall be paid to the creditor to reduce or extinguish the unpaid indebtedness and, wherever the amount of insurance exceeds the unpaid indebtedness, that any such excess shall be payable to a beneficiary, other than the creditor, named by the debtor or to the debtor's estate. With respect to any policy issued after September 8, 1975, credit life insurance shall not be subject to any exceptions or reductions other than for fraud, or for suicide occurring within two years of the effective date of the insurance.

. The individual policy or group certificate of insurance shall be delivered to the insured debtor at the time the indebtedness is incurred except as provided in subsections (4) and (5).

. If such individual policy or group certificate of insurance is not delivered to the debtor at the time the indebtedness is incurred, a copy of the application for such policy or a notice of proposed insurance, signed by the debtor and setting forth the name and home office address of the insurer; the name or names of the debtor; the premium or amount of payment by the debtor, if any, separately for credit life insurance and credit accident and health insurance; the amount, term and a brief description of the coverage provided, shall be delivered to the debtor at the time such indebtedness is incurred. The copy of the application for, or notice of proposed insurance, shall also refer exclusively to insurance coverage, and shall be separate and apart from the loan, sale or other credit statement of account, instrument, or agreement, or the application for any such loan, sale or credit, unless the information required by this subsection is prominently set forth therein under a descriptive heading which shall be underlined and printed in capital letters. Upon acceptance of the insurance by the insurer and within thirty days of the date upon which the indebtedness is incurred, the insurer shall cause the individual policy or group certificate of insurance to be delivered to the debtor. The application or notice of proposed insurance shall state that upon acceptance by the insurer, the insurance shall become effective as provided in RCW 48.34.080.

. If the named insurer does not accept the risk, then the debtor shall receive a policy or certificate of insurance setting forth the name and home office address of the substituted insurer and the amount of the premium to be charged, and if the amount of premium is less than that set forth in the notice of proposed insurance an appropriate refund shall be made.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c266.pdf?cite=1975%201st%20ex.s.%20c%20266%20§%2013[1975 1st ex.s. c 266 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c219.pdf?cite=1961%20c%20219%20§%209[1961 c 219 § 9]; ]

== 48.34.100 - Filing policies, notices, riders, etc.—Approval by commissioner—Preexisting policies—Forms.
. All policies, certificates of insurance, notices of proposed insurance, applications for insurance, endorsements, and riders delivered or issued for delivery in this state and the schedules of premium rates pertaining thereto shall be filed with the commissioner.

. No such policies, certificates of insurance, notices of proposed insurance, applications for insurance, endorsements, or riders shall be used in this state until approved by the commissioner pursuant to RCW 48.18.100 and 48.18.110. In addition to any grounds for disapproval provided therein, the form shall be disapproved both as to credit life and credit accident and health insurance if the benefits provided therein are not reasonable in relation to the premium charged.

. If a group policy of credit life insurance or credit accident and health insurance has been delivered in this state before midnight, June 7, 1961, on the first anniversary date following such time the terms of the policy as they apply to persons newly insured thereafter shall be rewritten to conform with the provisions of this chapter.

. If a group policy has been or is delivered in another state before or after August 11, 1969, the forms to be filed by the insurer with the commissioner are the group certificates and notices of proposed insurance delivered or issued for delivery in this state. He or she shall approve them if:

.. They provide the information that would be required if the group policy was delivered in this state; and

.. The applicable premium rates or charges do not exceed those established by his or her rules or regulations.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%2011005[2010 c 8 § 11005]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%207143[2009 c 549 § 7143]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c241.pdf?cite=1969%20ex.s.%20c%20241%20§%2015[1969 ex.s. c 241 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c219.pdf?cite=1961%20c%20219%20§%2010[1961 c 219 § 10]; ]

== 48.34.110 - Refunds—Credits—Charges to debtor.
. Each individual policy, or group certificate shall provide that in the event of termination of the insurance prior to the scheduled maturity date of the indebtedness, any refund of an amount paid by the debtor for insurance shall be paid or credited promptly to the person entitled thereto. The formula to be used in computing such refund shall be filed with and approved by the commissioner.

. If a creditor requires a debtor to make any payment for credit life insurance or credit accident and health insurance and an individual policy or group certificate of insurance is not issued, the creditor shall immediately give written notice to such debtor and shall promptly make an appropriate credit to the account.

. The amount charged to a debtor for any credit life or credit accident and health insurance shall not exceed the premiums charged by the insurer, as computed at the time the charge to the debtor is determined.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c219.pdf?cite=1961%20c%20219%20§%2011[1961 c 219 § 11]; ]

== 48.34.120 - Debtor's right to furnish and obtain own insurance.
When the credit life insurance or credit accident and health insurance is required in connection with any credit transaction, the debtor shall, upon request to the creditor, have the option of furnishing the required amount of insurance through existing policies of insurance owned or controlled by him or her or of procuring and furnishing the required coverage through any insurer authorized to transact an insurance business within this state.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%207144[2009 c 549 § 7144]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c219.pdf?cite=1961%20c%20219%20§%2012[1961 c 219 § 12]; ]

