= 48.29 - Title insurers.
:toc:

== 48.29.005 - Administration of chapter—Rules.
The commissioner may adopt rules to implement and administer this chapter, including but not limited to:

. Establishing the information to be included in the report required under RCW 48.29.015;

. Establishing the information required for the filing of rates for title insurance under RCW 48.29.147;

. Establishing standards which title insurance rate filings must satisfy under RCW 48.29.147;

. Establishing a date, which date shall not be earlier than January 1, 2010, by which all title insurers selling policies in this state must file their rates with the commissioner under RCW 48.29.143 and 48.29.147 rather than under RCW 48.29.140 and refile any rates that were in effect prior to the date established by the commissioner;

. Defining what things of value a title insurance insurer or title insurance agent is permitted to give to any person in a position to refer or influence the referral of title insurance business under RCW 48.29.210(2). In adopting rules under this subsection, the commissioner shall work with representatives of the title insurance and real estate industries and consumer groups in developing the rules;

. Establishing the fee for a license as a rating organization under RCW 48.29.410;

. Establishing license requirements that an applicant for a license as a rating organization and a licensee must comply with; and

. Requiring a rating organization to periodically update the title insurance rates, manuals of rules and rates, rating plans, rate schedules, minimum rates, class rates, or rating rules, filed by the rating organization on behalf of its members or subscribers.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2017%20c%20103%20§%2023[2017 c 103 § 23]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6847-S.SL.pdf?cite=2008%20c%20110%20§%209[2008 c 110 § 9]; ]

== 48.29.010 - Scope of chapter—Definitions.
. This chapter relates only to title insurers for real property.

. This code does not apply to persons engaged in the business of preparing and issuing abstracts of title to property and certifying to their correctness so long as the persons do not guarantee or insure the titles.

. For purposes of this chapter, unless the context clearly requires otherwise:

.. "Abstract of title" means a written representation, provided under contract, whether written or oral, intended to be relied upon by the person who has contracted for the receipt of this representation, listing all recorded conveyances, instruments, or documents that, under the laws of the state of Washington, impart constructive notice with respect to the chain of title to the real property described. An abstract of title is not a title policy as defined in this subsection.

.. [Empty]
... "Advisory organization" means a group, association, or other organization of insurers that assists insurers or rating organizations in rate making by the collection and furnishing of loss or expense statistics, or by the submission of recommendations, but that does not make filings under this chapter.

... The term "advisory organization" does not include subscribers' committees provided for in RCW 48.29.430 or the statistical reporting agent provided for in RCW 48.29.017.

.. "Associates of producers" means any person who has one or more of the following relationships with a producer of title insurance business:

... A spouse, parent, or child of a producer;

... A corporation or business entity that controls, is controlled by, or is under common control with a producer;

... An employer, employee, independent contractor, officer, director, partner, franchiser, or franchisee of a producer; or

... Anyone who has an agreement, arrangement, or understanding with a producer, the purpose or substantial effect of which is to enable the person in a position to influence the selection of a title insurer or title insurance agent to benefit financially from the selection of the title insurer or title insurance agent.

.. "Financial interest" means any interest, legal or beneficial, that entitles the holder directly or indirectly to any of the net profits or net worth of the entity in which the interest is held.

.. "Member" means an insurer that participates in or is entitled to participate in the management of a rating organization or an advisory organization.

.. "Preliminary report," "commitment," or "binder" means reports furnished in connection with an application for title insurance and are offers to issue a title policy subject to the stated exceptions in the reports, the conditions and stipulations of the report and the issued policy, and other matters as may be incorporated by reference. The reports are not abstracts of title, nor are any of the rights, duties, or responsibilities applicable to the preparation and issuance of an abstract of title applicable to the issuance of any report. The report is not a representation as to the condition of the title to real property, but is a statement of terms and conditions upon which the issuer is willing to issue its title policy, if the offer is accepted.

.. "Producers of title insurance business" means real estate agents and brokers, lawyers, mortgagees, mortgage loan brokers, financial institutions, escrow agents, persons who lend money for the purchase of real estate or interests therein, building contractors, real estate developers and subdividers, and any other person who is or may be in a position to influence the selection of a title insurer or title insurance agent whether or not the consent or approval of any other person is sought or obtained with respect to the selection of the title insurer or title insurance agent.

.. [Empty]
.. "Rating organization" means an entity, the object or purpose of which is the adoption or making of title insurance forms, including forms of policy, application, rider, and endorsement, and title insurance rates, manuals of rules and rates, rating plans, rate schedules, minimum rates, class rates, and rating rules.

... The term "rating organization" does not include two or more insurers operating under the authority granted in RCW 48.29.440.

... "Subscriber" means an insurer that employs the services of a rating organization for the purpose of making form or rate filings, whether or not the title insurer is a member of such rating organization.

.. "Title policy" means any written instrument, contract, or guarantee by means of which title insurance liability is assumed.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2017%20c%20103%20§%202[2017 c 103 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6847-S.SL.pdf?cite=2008%20c%20110%20§%201[2008 c 110 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1197-S.SL.pdf?cite=2005%20c%20223%20§%2014[2005 c 223 § 14]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1452.SL.pdf?cite=1997%20c%2014%20§%201[1997 c 14 § 1]; 1947 c 79 § .29.01; Rem. Supp. 1947 § 45.29.01; ]

== 48.29.015 - Requirement to maintain records—Report to commissioner.
. A title insurance agent shall maintain records of its title orders sufficient to indicate the source of the title orders.

. Every title insurance agent shall file with the commissioner annually by March 15th of each year for the previous calendar year, unless the commissioner for good cause shown extends the time for filing, a report, on a form prescribed by the commissioner, setting forth:

.. The names and addresses of those persons, if any, who have had a financial interest in the title insurance agent during the calendar year, who are known or reasonably believed by the title insurance agent to be producers of title business or associates of producers; and

.. The percent of title orders originating from each person who owns, or had owned during the preceding calendar year, a financial interest in the title insurance agent.

. Each title insurance agent shall keep current the information required by that portion of the report required by subsection (2)(a) of this section by reporting all changes or additions within fifteen days after the end of the month in which it learns of each change or addition.

. Each title insurance agent shall file that portion of the report required by subsection (2)(a) of this section with its application for a license.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5316.SL.pdf?cite=2017%203rd%20sp.s.%20c%2025%20§%2018[2017 3rd sp.s. c 25 § 18]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6847-S.SL.pdf?cite=2008%20c%20110%20§%202[2008 c 110 § 2]; ]

== 48.29.017 - Statistical reporting agent—Duties—Required reports—Costs—Rules—Information and data exchange.
. The commissioner must designate one statistical reporting agent to assist him or her in gathering information on title insurance policy issuance, business income, and expenses and making compilations thereof. The costs and expenses of the statistical reporting agent must be borne by all the authorized title insurance companies and title insurance agents licensed to conduct the business of title insurance in this state. The commissioner may adopt rules setting forth how the costs and expenses of the statistical reporting agent are to be paid and apportioned among the authorized title insurers and licensed title insurance agents.

. Upon designation of a statistical reporting agent by the commissioner under subsection (1) of this section all authorized title insurance companies and licensed title insurance agents must annually, by May 31st, file a report with the statistical reporting agent of their policy issuance, business income, expenses, and loss experience in this state. The report must be filed with the statistical reporting agent in a manner and form prescribed by the commissioner by rule, which must be consistent with the manner and form adopted by the national association of insurance commissioners.

. The statistical reporting agent must review the information filed with it for completeness, accuracy, and quality within one hundred twenty days of its receipt. All title insurance companies and title insurance agents must cooperate with the statistical reporting agent to verify the completeness, accuracy, and quality of the data that they submitted.

. Within thirty days after completing its review of the information for quality and accuracy, the statistical reporting agent must file the information for each title insurance company and title insurance agent, individually and in the aggregate, with the commissioner with a copy of the aggregate data from such statistical reporting agent provided to each title insurer and title insurance agent.

. The commissioner may adopt rules to implement and administer this section.

. The statistical reporting agent may exchange aggregate information and experience data with title insurance companies and rating organizations in this state in accordance with RCW 48.29.470.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2017%20c%20103%20§%2022[2017 c 103 § 22]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1035.SL.pdf?cite=2013%20c%2065%20§%201[2013 c 65 § 1]; ]

== 48.29.018 - Information filed under RCW  48.29.017—Confidentiality.
. Information filed with the commissioner under RCW 48.29.017 must be kept confidential and is not subject to public disclosure under chapter 42.56 RCW, unless the commissioner finds, after notice and hearing with the affected parties, it is in the public interest to disclose the information.

. The commissioner may share the information in subsection (1) of this section with the national association of insurance commissioners and its affiliates and subsidiaries, regulatory and law enforcement officials of other states and nations, the federal government, and international authorities, provided that the recipient agrees to maintain the confidentiality and privileged status of the information.

. This section does not prohibit the commissioner from sharing or publishing the information in an aggregate form.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1035.SL.pdf?cite=2013%20c%2065%20§%202[2013 c 65 § 2]; ]

== 48.29.020 - Certificate of authority—Qualifications.
A title insurer is not entitled to have a certificate of authority unless:

. It is a stock corporation;

. It owns or leases and maintains a complete set of tract indexes of the county in this state in which its principal office is located; and

. It has and maintains the capital and surplus requirements set forth in RCW 48.05.340.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1197-S.SL.pdf?cite=2005%20c%20223%20§%2015[2005 c 223 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c76.pdf?cite=1990%20c%2076%20§%201[1990 c 76 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c86.pdf?cite=1955%20c%2086%20§%2012[1955 c 86 § 12]; 1947 c 79 § .29.02; Rem. Supp. 1947 § 45.29.02; ]

== 48.29.040 - May do business in two or more counties—Restrictions.
. Subject to the deposit requirements of *RCW 48.29.030, a title insurer having its principal offices in one county may be authorized to transact business in only such additional counties as to which it owns or leases and maintains, or has a duly authorized agent that owns or leases and maintains, a complete set of tract indexes.

. A title insurer not authorized to transact business in a certain county may purchase a title policy on property located therein from another title insurer which is so authorized in that county. The first title insurer may thereafter issue its own policy of title insurance to the owner of such property. The first title insurer may combine the insurance on the title of such property in a single policy which also insures the title of one or more other pieces of property. The first title insurer must pay the full premium based on filed rates for the policy, and must charge the precise same amount to its own customer for the insurance as to the title of such property. A title insurer using the authority granted by this subsection in a transaction must so notify its customer.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c76.pdf?cite=1990%20c%2076%20§%202[1990 c 76 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c193.pdf?cite=1957%20c%20193%20§%2017[1957 c 193 § 17]; 1947 c 79 § .29.04; Rem. Supp. 1947 § 45.29.04; ]

== 48.29.120 - Reserve requirements.
In determining the financial condition of a title insurer doing business under this title, the general provisions of chapter 48.12 RCW requiring the establishment of reserves sufficient to cover all known and unknown liabilities including allocated and unallocated loss adjustment expense apply, except that a title insurer shall establish and maintain:

. A known claim reserve in an amount estimated to be sufficient to cover all unpaid losses, claims, and allocated loss adjustment expenses arising under title insurance policies, guaranteed certificates of title, guaranteed searches, and guaranteed abstracts of title, and all unpaid losses, claims, and allocated loss adjustment expenses for which the title insurer may be liable, and for which the insurer has received notice by or on behalf of the insured, holder of a guarantee or escrow, or security depositor;

. [Empty]
.. A statutory or unearned premium reserve consisting of:

... The amount of the special reserve fund that was required prior to July 24, 2005, which balance must be released in accordance with (b) of this subsection; and

... Additions to the reserve after July 24, 2005, must be made out of total charges for title insurance policies and guarantees written, as set forth in the title insurer's most recent annual statement on file with the commissioner, equal to the sum of the following:

(A) For each title insurance policy on a single risk written or assumed after July 24, 2005, fifteen cents per one thousand dollars of net retained liability for policies under five hundred thousand dollars; and

(B) For each title insurance policy on a single risk written or assumed after July 24, 2005, ten cents per one thousand dollars of net retained liability for policies of five hundred thousand or greater.

.. The aggregate of the amounts set aside in this reserve in any calendar year pursuant to (a) of this subsection must be released from the reserve and restored to net profits over a period of twenty years under the following formula:

... Thirty-five percent of the aggregate sum on July 1st of the year next succeeding the year of addition;

... Fifteen percent of the aggregate sum on July 1st of each of the succeeding two years;

... Ten percent of the aggregate sum on July 1st of the next succeeding year;

... Three percent of the aggregate sum on July 1st of each of the next three succeeding years;

.. Two percent of the aggregate sum on July 1st of each of the next three succeeding years; and

.. One percent of the aggregate sum on July 1st of each of the next succeeding ten years.

.. The insurer shall calculate an adjusted statutory unearned premium reserve as of July 24, 2005. The adjusted reserve is calculated as if (a)(ii) and (b) of this subsection had been in effect for all years beginning twenty years prior to July 24, 2005. For purposes of this calculation, the balance of the reserve as of that date is deemed to be zero. If the adjusted reserve so calculated exceeds the aggregate amount set aside for statutory or unearned premiums in the insurer's annual statement on file with the commissioner on July 24, 2005, the insurer shall, out of total charges for policies of title insurance, increase its statutory or unearned premium reserve by an amount equal to one-sixth of that excess in each of the succeeding six years, commencing with the calendar year that includes July 24, 2005, until the entire excess has been added.

.. The aggregate of the amounts set aside in this reserve in any calendar year as adjustments to the insurer's statutory or unearned premium reserve under (c) of this subsection shall be released from the reserve and restored to net profits, or equity if the additions required by (c) of this subsection reduced equity directly, over a period not exceeding ten years under to the [under the] following table:

Year of AdditionReleaseYear 11Equally over 10 yearsYear 2Equally over 9 yearsYear 3Equally over 8 yearsYear 4Equally over 7 yearsYear 5Equally over 6 yearsYear 6Equally over 5 years

Year of Addition

Release

Year 11

Equally over 10 years

Year 2

Equally over 9 years

Year 3

Equally over 8 years

Year 4

Equally over 7 years

Year 5

Equally over 6 years

Year 6

Equally over 5 years

1(The calendar year following July 24, 2005).

. A supplemental reserve shall be established consisting of any other reserves necessary, when taken in combination with the reserves required by subsections (1) and (2) of this section, to cover the company's liabilities with respect to all losses, claims, and loss adjustment expenses.

. The supplemental reserve required under subsection (3) of this section shall be phased in as follows: Twenty-five percent of the otherwise applicable supplemental reserve is required until December 31, 2006; fifty percent of the otherwise applicable supplemental reserve is required until December 31, 2007; and seventy-five percent of the otherwise applicable supplemental reserve is required until December 31, 2008.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1197-S.SL.pdf?cite=2005%20c%20223%20§%2016[2005 c 223 § 16]; 1947 c 79 § .29.12; Rem. Supp. 1947 § 45.29.12; ]

== 48.29.130 - Investments.
A domestic title insurer shall invest its funds as follows:

. Funds in an amount not less than its reserve required by RCW 48.29.120 must be kept invested in investments eligible for domestic life insurers.

. Other funds may be invested in:

.. The insurer's plant and equipment, up to a maximum of fifty percent of capital plus surplus.

.. Stocks and bonds of abstract companies when approved by the commissioner.

.. Investments eligible for the investment of funds of any domestic insurer.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1197-S.SL.pdf?cite=2005%20c%20223%20§%2017[2005 c 223 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c150.pdf?cite=1967%20c%20150%20§%2030[1967 c 150 § 30]; 1947 c 79 § .29.13; Rem. Supp. 1947 § 45.29.13; ]

== 48.29.140 - Premium rates—Required filings—Transition date set by rule.
. Premium rates for the insuring or guaranteeing of titles shall not be excessive, inadequate, or unfairly discriminatory.

. Each title insurer shall forthwith file with the commissioner a schedule showing the premium rates to be charged by it. Every addition to or modification of such schedule or of any rate therein contained shall likewise be filed with the commissioner, and no such addition or modification shall be effective until expiration of fifteen days after date of such filing.

. The commissioner may order the modification of any premium rate or schedule of premium rates found by him or her after a hearing to be excessive, or inadequate, or unfairly discriminatory. No such order shall require retroactive modification.

. The commissioner shall by rule set a date, which shall not be earlier than January 1, 2010, by which title insurers must file every manual of rules and rates, rating plan, rate schedule, minimum rate, class rate, and rating rule, and every modification of any of these filings, under RCW 48.29.143 and 48.29.147, rather than under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6847-S.SL.pdf?cite=2008%20c%20110%20§%208[2008 c 110 § 8]; 1947 c 79 § .29.14; Rem. Supp. 1947 § 45.29.14; ]

== 48.29.143 - Premium rates—Actuarially sound estimates.
. Premium rates for the insuring or guaranteeing of titles shall not be excessive, inadequate, or unfairly discriminatory.

. A rate is not excessive, inadequate, or unfairly discriminatory if it is an actuarially sound estimate of the expected value of all future costs associated with an individual risk transfer. Such costs include claims, claim settlement expenses, operational and administrative expenses, and the cost of capital.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6847-S.SL.pdf?cite=2008%20c%20110%20§%204[2008 c 110 § 4]; ]

== 48.29.147 - Required filings—Information subject to review—Commissioner's powers—Timing.
. [Empty]
.. Every title insurer shall, before using, file with the commissioner every form, manual of title insurance rules and rates, rating plan, rate schedule, minimum rate, class rate, and rating rule, and every modification of any of the filings under this subsection which it proposes.

.. A rating organization's filing on behalf of its members or subscribers satisfies a title insurer's duty in (a) of this subsection if the title insurer is a member or subscriber of the rating organization.

. Every filing shall be accompanied by sufficient information to permit the commissioner to determine whether the filing meets the requirements of RCW 48.29.143 and this section for rate filings, and RCW 48.18.100 and 48.18.110 for form filings.

. Data used to justify title insurance rates may not include escrow income or expenses. The title insurance company or rating organization shall include a detailed explanation showing how expenses are allocated between the title operations and escrow operations of the insurer or title insurance agent.

. Every such filing shall state its proposed effective date.

. The commissioner shall review a filing as soon as reasonably possible after it is received, to determine whether it meets the requirements of RCW 48.29.143.

. The filing's proposed effective date shall be no earlier than thirty days after the date on which the filing is received by the commissioner. By giving notice to the insurer or rating organization within this thirty days, the commissioner may extend this waiting period for an additional period not to exceed an additional fifteen days. The commissioner may, upon application and for cause shown, waive part or all of the waiting period with respect to a filing the commissioner has not disapproved. If the commissioner does not disapprove the filing during the waiting period, the filing takes effect on its proposed effective date, except as to filings made by a rating organization on behalf of its members or subscribers pursuant to this section.

. If within the waiting period or any extension thereof as provided in subsection (6) of this section, the commissioner finds that a filing does not meet the requirements of RCW 48.29.143 or the requirements of subsections (2) through (4) of this section, the commissioner shall disapprove the filing and shall give notice to the insurer or rating organization that the filing has been disapproved. This notice must specify the respect in which the commissioner finds the filing fails to meet the requirements and must state that the filing does not become effective as proposed.

. [Empty]
.. Except as to filings made by a rating organization on behalf of its members or subscribers pursuant to this section, if a filing is not disapproved by the commissioner within the waiting period or any extension thereof, the filing becomes effective as proposed.

.. Before the commissioner approves a filing by a rating organization, the commissioner shall review all materials contained in the filing, including, as applicable, materials submitted by the rating organization, materials provided by the statistical reporting agent pursuant to RCW 48.29.017, as well as materials concerning any public hearings, market investigations, studies, or other information collected during the review, and determine that the filing complies with the requirements of this chapter.

.. Filings made by a rating organization on behalf of its members or subscribers pursuant to this section may not become effective, notwithstanding expiration of a waiting period, unless the commissioner approves the filings in accordance with (b) of this subsection.

. A filing made under this section is exempt from RCW 48.02.120(3). However, the filing and all supporting information accompanying it is open to public inspection only after the filing becomes effective.

. A title insurer or title insurance agent shall not make or issue a title insurance contract or policy, or use or collect any premium on or after a date set by the commissioner by rule, which date shall not be any earlier than January 1, 2010, except in accordance with rates and rules filed with the commissioner as required by this section or as provided under RCW 48.29.148.

. If at any time subsequent to the applicable review period provided for in subsection (6) of this section, the commissioner has reason to believe that a title insurer's or rating organization's rates do not meet the requirements of RCW 48.29.143 or are otherwise contrary to law, or if any person having an interest in the rates makes a written complaint to the commissioner setting forth specific and reasonable grounds for the complaint and requests a hearing, or if any insurer or rating organization upon notice of the commissioner's disapproval of a filing made under this section requests a hearing, the commissioner shall hold a hearing within thirty days and shall, in advance of it, give written notice of the hearing to all parties in interest. The commissioner may, by issuing an order, confirm, modify, change, or rescind any previous action, if it is warranted by the facts shown at the hearing. The order shall not affect any contract or policy made or issued prior to a reasonable period of time, to be specified in the order, after the order is issued.

. In any hearing regarding rates filed under this chapter the burden is on the title insurer or rating organization to prove by a preponderance of the evidence that the rates comply with RCW 48.29.143.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2017%20c%20103%20§%2021[2017 c 103 § 21]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6847-S.SL.pdf?cite=2008%20c%20110%20§%205[2008 c 110 § 5]; ]

== 48.29.148 - Form and rate filings by rating organization.
If so authorized by an insurer that is a member or subscriber of a rating organization, the commissioner shall accept, in lieu of filings by the insurer, form and rate filings on its behalf made by a rating organization then licensed as provided in this chapter. Rate filings accepted by the commissioner become effective only as provided in RCW 48.29.147. Form filings accepted by the commissioner become effective only as provided in chapter 48.18 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2017%20c%20103%20§%203[2017 c 103 § 3]; ]

== 48.29.149 - Form and rate filings by rating organization—Deviation.
Every member or subscriber to a rating organization shall adhere to the filings made on its behalf by such rating organization. Deviations from the rating organization's filings are permitted only when filed with the commissioner in accordance with this title. A copy of the deviation filing must be sent simultaneously to such rating organization. 

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2017%20c%20103%20§%2014[2017 c 103 § 14]; ]

== 48.29.150 - Taxation of title insurers.
Title insurers and their property shall be taxed by this state in accordance with the general laws relating to taxation, and not otherwise.

[ 1947 c 79 § .29.15; Rem. Supp. 1947 § 45.29.15; ]

== 48.29.155 - Agent license—Financial responsibility—Definitions.
. At the time of filing an application for a title insurance agent license, or any renewal or reinstatement of a title insurance agent license, the applicant shall provide satisfactory evidence to the commissioner of having obtained the following as evidence of financial responsibility:

.. A fidelity bond or fidelity insurance providing coverage in the aggregate amount of two hundred thousand dollars with a deductible no greater than ten thousand dollars covering the applicant and each corporate officer, partner, escrow officer, and employee of the applicant conducting the business of an escrow agent as defined in RCW 18.44.011 and exempt from licensing under *RCW 18.44.021(6), or a guarantee from a licensed title insurance company as authorized by subsection (5) of this section; and

.. A surety bond in the amount of ten thousand dollars executed by the applicant as obligor and by a surety company authorized, or eligible under chapter 48.15 RCW, to do a surety business in this state as surety, or some other security approved by the commissioner, unless the fidelity bond or fidelity insurance obtained by the licensee to satisfy the requirement in (a) of this subsection does not have a deductible. The bond shall run to the state of Washington as obligee, and shall run to the benefit of the state and any person or persons who suffer loss by reason of the applicant's or its employee's violation of this chapter. The bond shall be conditioned that the obligor as licensee will faithfully conform to and abide by this chapter and all rules adopted under this chapter, and shall reimburse all persons who suffer loss by reason of a violation of this chapter or rules adopted under this chapter. The bond shall be continuous and may be canceled by the surety upon the surety giving written notice to the commissioner of its intent to cancel the bond. The cancellation shall be effective thirty days after the notice is received by the commissioner. Whether or not the bond is renewed, continued, reinstated, reissued, or otherwise extended, replaced, or modified, including increases or decreases in the penal sum, it shall be considered one continuous obligation, and the surety upon the bond shall not be liable in an aggregate amount exceeding the penal sum set forth on the face of the bond. In no event shall the penal sum, or any portion thereof, at two or more points in time be added together in determining the surety's liability. The bond is not liable for any penalties imposed on the licensee, including but not limited to any increased damages or attorneys' fees, or both, awarded under RCW 19.86.090.

. For the purposes of this section, a "fidelity bond" means a primary commercial blanket bond or its equivalent satisfactory to the commissioner and written by an insurer authorized, or eligible under chapter 48.15 RCW, to transact this line of business in the state of Washington. The bond shall provide fidelity coverage for any fraudulent or dishonest acts committed by any one or more of the employees, officers, or owners as defined in the bond, acting alone or in collusion with others. The bond shall be for the sole benefit of the title insurance agent and under no circumstances whatsoever shall the bonding company be liable under the bond to any other party. The bond shall name the title insurance agent as obligee and shall protect the obligee against the loss of money or other real or personal property belonging to the obligee, or in which the obligee has a pecuniary interest, or for which the obligee is legally liable or held by the obligee in any capacity, whether the obligee is legally liable therefor or not. The bond may be canceled by the insurer upon delivery of thirty days' written notice to the commissioner and to the title insurance agent.

. For the purposes of this section, "fidelity insurance" means employee dishonesty insurance or its equivalent satisfactory to the commissioner and written by an insurer authorized, or eligible under chapter 48.15 RCW, to transact this line of business in the state of Washington. The insurance shall provide coverage for any fraudulent or dishonest acts committed by any one or more of the employees, officers, or owners as defined in the policy of insurance, acting alone or in collusion with others. The insurance shall be for the sole benefit of the title insurance agent and under no circumstances whatsoever shall the insurance company be liable under the insurance to any other party. The insurance shall name the title insurance agent as the named insured and shall protect the named insured against the loss of money or other real or personal property belonging to the named insured, or in which the named insured has a pecuniary interest, or for which the named insured is legally liable or held by the named insured in any capacity, whether the named insured is legally liable therefor or not. The insurance coverage may be canceled by the insurer upon delivery of thirty days' written notice to the commissioner and to the title insurance agent.

. The fidelity bond or fidelity insurance, and the surety bond or other form of security approved by the commissioner, shall be kept in full force and effect as a condition precedent to the title insurance agent's authority to transact business in this state, and the title insurance agent shall supply the commissioner with satisfactory evidence thereof upon request.

. A title insurance company authorized to do business in Washington under RCW 48.05.030 may provide a guarantee in a form satisfactory to the commissioner accepting financial responsibility, up to the aggregate amount of two hundred thousand dollars, for any fraudulent or dishonest acts committed by any one or more of the employees, officers, or owners of a title insurance agent that is appointed as the title insurance company's agent. A title insurance company providing a guarantee as permitted under this subsection may only do so on behalf of its properly appointed title insurance agents. If the title insurance agent is an agent for two or more title insurance companies, any liability under the guarantee shall be borne by the title insurance company for those escrows for which a title insurance commitment or policy was issued on behalf of that title insurance company. If no commitment or policy was issued regarding the escrow for which moneys were lost, including but not limited to collection escrows, each title insurance company, for which the agent was appointed at the time of the fraudulent or dishonest act, shares in the liability. The liability will be shared proportionally, as follows: The premium the agent remitted to the title insurance company in the year prior to the fraudulent or dishonest act will be compared to the total premium the agent remitted to all title insurance companies, for whom the title insurance agent was appointed, during the same period.

. All title insurance agents licensed on or before July 24, 2005, shall comply with this section within thirty days following July 24, 2005.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2005%20c%20115%20§%201[2005 c 115 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5310-S.SL.pdf?cite=2003%20c%20202%20§%201[2003 c 202 § 1]; ]

== 48.29.160 - Agents—County tract indexes required.
To be licensed as [an] agent of a title insurer, the applicant must own or lease and maintain a complete set of tract indexes of the county or counties in which such agent will do business.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c223.pdf?cite=1981%20c%20223%20§%201[1981 c 223 § 1]; ]

== 48.29.170 - Agents—Separate licenses for individuals not required.
Title insurance agents are exempt from the provisions of *RCW 48.17.180(1) that require that each individual empowered to exercise the authority of a licensed firm or corporation must be separately licensed.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1197-S.SL.pdf?cite=2005%20c%20223%20§%2018[2005 c 223 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c223.pdf?cite=1981%20c%20223%20§%202[1981 c 223 § 2]; ]

== 48.29.180 - Disclosure of energy conservation payment obligations—Informational note—Liability.
The existence of notices of payment obligations in RCW 80.28.065 may be disclosed as an informational note to a preliminary commitment for policy of title insurance. Neither the inclusion nor the exclusion of any such informational note shall create any liability against such title insurer under any preliminary commitment for title insurance, policy or otherwise.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1326-S.SL.pdf?cite=1993%20c%20245%20§%204[1993 c 245 § 4]; ]

== 48.29.190 - Conducting business as escrow agent—Requirements—Violation, penalties.
. Every title insurance company and title insurance agent conducting the business of an escrow agent as defined in RCW 18.44.011 and exempt from licensing under *RCW 18.44.021(6) shall:

.. Keep adequate records, as determined by rule by the insurance commissioner, of all transactions handled by the title insurance company or title insurance agent, including itemization of all receipts and disbursements of each transaction. These records shall be maintained in this state, unless otherwise approved by the insurance commissioner, for a period of six years from completion of the transaction. These records shall be open to inspection by the insurance commissioner or his or her authorized representatives;

.. Keep separate escrow fund account or accounts in a recognized Washington state depositary or depositaries authorized to receive funds, in which shall be kept separate and apart and segregated from the title insurance company or title insurance agent's own funds, all funds or moneys of clients which are being held by the title insurance company or title insurance agent pending the closing of a transaction and such funds shall be deposited not later than the first banking day following receipt thereof; and

.. Not make disbursements on any escrow account without first receiving deposits directly relating to the account in amounts at least equal to the disbursements. A title insurance company or title insurance agent shall not make disbursements until the next business day after the business day on which the funds are deposited unless the deposit is made in cash, by interbank electronic transfer, or in a form that permits conversion of the deposit to cash on the same day the deposit is made. The deposits shall be in one of the following forms:

... Cash;

... Interbank electronic transfers such that the funds are unconditionally received by the title insurance company or the title insurance agent or the title insurance company or title insurance agent's depository;

... Checks, negotiable orders of withdrawal, money orders, cashier's checks, and certified checks that are payable in Washington state and drawn on financial institutions located in Washington state;

... Checks, negotiable orders of withdrawal, money orders, and any other item that has been finally paid as described in RCW 62A.4-213 before any disbursement; or

.. Any depository check, including any cashier's check, certified check, or teller's check, which is governed by the provisions of the federal expedited funds availability act, 12 U.S.C. Sec. 4001 et seq.

. For purposes of this section, "item" means any instrument for the payment of money even though it is not negotiable, but does not include money.

. Violation of this section shall subject a title insurance company or title insurance agent to penalties as prescribed in Title 9A RCW and remedies as provided in chapter 19.86 RCW and shall constitute grounds for suspension or revocation of the certificate of authority of a title insurance company or the license of a title insurance agent. In addition, a violation of this section may subject a title insurance company or a title insurance agent to penalties as prescribed in this title.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1092.SL.pdf?cite=1999%20c%2030%20§%2034[1999 c 30 § 34]; ]

== 48.29.193 - Escrow services—Schedule of fees filed with commissioner.
. Each title insurer and title insurance agent shall immediately file with the commissioner a schedule of its fees for providing escrow services.

. The schedule shall:

.. Be dated to show the date the fees for providing escrow services are to become effective, which date shall be no earlier than fifteen days after the schedule has been filed with the commissioner; and

.. Set forth the total fees for providing escrow services by clearly stating the amounts to be charged for the escrow services, the manner in which the fees for the escrow services are to be determined, and any charges that will be charged to the consumer that are not included in the total escrow fee.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6847-S.SL.pdf?cite=2008%20c%20110%20§%206[2008 c 110 § 6]; ]

== 48.29.195 - Escrow services—Schedule of fees made available to public.
. Each title insurer and title insurance agent shall make available to the public schedules of its currently effective title insurance premiums and fees for providing escrow services.

. The schedules shall:

.. Be dated to show the date the title insurance premiums or fees for providing escrow services became effective;

.. Be made available to the public during normal business hours in each office of the title insurer and its appointed title insurance agents in this state;

.. Be made available on the title insurer's and title insurance agent's web site, if the title insurer or title insurance agent has a web site;

.. Set forth the total title insurance premium charged for the title insurance policy issued by the title insurer either by stating the premium for each title insurance policy in given amounts of coverage, or by stating the charge per unit amount of coverage, or by a combination of the two; and

.. Set forth the total fees for providing escrow services by clearly stating the amounts to be charged for the escrow services, the manner in which the fees for the escrow services are to be determined, and any charges that will be charged to the consumer that are not included in the total escrow fee.

. Each title insurer and title insurance agent shall keep a complete file of its schedules of title insurance premiums and fees for providing escrow services and all changes and amendments to those schedules until at least one year after they have ceased to be in effect.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6847-S.SL.pdf?cite=2008%20c%20110%20§%207[2008 c 110 § 7]; ]

== 48.29.200 - Prohibited practices.
It is a violation of this chapter for any title insurance company and title insurance agent in the conduct of the business of an escrow agent as defined in RCW 18.44.011 and exempt from licensing under *RCW 18.44.021(6) to:

. Directly or indirectly employ any scheme, device, or artifice to defraud or mislead borrowers or lenders or to defraud any person;

. Directly or indirectly engage in any unfair or deceptive act or practice toward any person;

. Directly or indirectly obtain property by fraud or misrepresentation;

. Knowingly make, publish, or disseminate any false, deceptive, or misleading information in the conduct of the business of escrow, or relative to the business of escrow or relative to any person engaged therein;

. Knowingly receive or take possession for personal use of any property of any escrow business, other than in payment authorized by this chapter, and with intent to defraud, omit to make, or cause or direct to be made, a full and true entry thereof in the books and accounts of the title insurance company or title insurance agent;

. Make or concur in making any false entry, or omit or concur in omitting to make any material entry, in its books or accounts;

. Knowingly make or publish, or concur in making or publishing any written report, exhibit, or statement of its affairs or pecuniary condition containing any material statement which is false, or omit or concur in omitting any statement required by law to be contained therein;

. Willfully fail to make any proper entry in the books of the escrow business as required by law;

. Fail to disclose in a timely manner to the other officers, directors, controlling persons, or employees the receipt of service of a notice of an application for an injunction or other legal process affecting the property or business of a title insurance company or title insurance agent conducting an escrow business, including an order to cease and desist or other order of the insurance commissioner; or

. Fail to make any report or statement lawfully required by the insurance commissioner or other public official.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1092.SL.pdf?cite=1999%20c%2030%20§%2035[1999 c 30 § 35]; ]

== 48.29.210 - Business inducements—Prohibited practices.
. A title insurer, title insurance agent, or employee, agent, or other representative of a title insurer or title insurance agent shall not, directly or indirectly, give any fee, kickback, or other thing of value to any person as an inducement, payment, or reward for placing business, referring business, or causing title insurance business to be given to either the title insurer, or title insurance agent, or both.

. A title insurer, title insurance agent, or employee, agent, or other representative of a title insurer or title insurance agent shall not, directly or indirectly, give anything of value to any person in a position to refer or influence the referral of title insurance business to either the title insurance company or title insurance agent, or both, except as permitted under rules adopted by the commissioner.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6847-S.SL.pdf?cite=2008%20c%20110%20§%203[2008 c 110 § 3]; ]

== 48.29.213 - Return on ownership interest—Certain payments authorized.
. RCW 48.29.210, 18.85.053, 18.44.305, or 19.146.103 does not make unlawful the payment by a title insurer or title insurance agent and the receipt by a producer of title insurance business of a return on ownership interest in the title insurer or title insurance agent.

. A return on ownership interest may include:

.. Bona fide dividends, and capital or equity distributions, related to ownership interest or franchise relationship, between entities in an affiliated relationship; and

.. Bona fide business loans, advances, and capital or equity contributions between entities in an affiliate relationship (in any direction), so long as they are for ordinary business purposes and are not fees for the referral of settlement service business or unearned fees.

. A return on ownership interest does not include:

.. Any payment which has a basis of calculation of no apparent business motive other than distinguishing among recipients of payments on the basis of the amount of their actual, estimated, or anticipated referrals;

.. Any payment which varies according to the relative amount of referrals by the different recipients of similar payments; or

.. A payment based on an ownership, partnership, or joint venture share which has been adjusted on the basis of previous relative referrals by recipients of similar payments.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6847-S.SL.pdf?cite=2008%20c%20110%20§%2013[2008 c 110 § 13]; ]

== 48.29.400 - Rating organizations—Intent.
It is the legislature's intent to establish a system by which title insurers may adopt a rating organization's form and rate filings pursuant to this chapter in order to benefit consumers and entities purchasing, selling, or financing real property. It is further the legislature's intent that the system so established under state oversight comply with state and federal law so that title insurers and rating organizations acting in accordance with this chapter may lawfully cooperate in the preparation of title insurance forms and manuals, and the recommendation of rates, subject to approval by the commissioner.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2017%20c%20103%20§%201[2017 c 103 § 1]; ]

== 48.29.405 - Rating organizations—License required.
A rating organization may not do business in this state or make filings with the commissioner unless then licensed by the commissioner as a rating organization.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2017%20c%20103%20§%204[2017 c 103 § 4]; ]

== 48.29.410 - Rating organizations—License applications.
Any person, whether domiciled within or outside this state, except as provided in this section, may make application to the commissioner for a license as a rating organization for title insurance. The application must include:

. A copy of the applicant's constitution, articles of agreement or association, certificate of incorporation, or trust agreement, and of its bylaws, rules, and regulations governing the conduct of its business;

. A list of its members and a list of its subscribers;

. The name and address of a resident of this state upon whom notices or orders of the commissioner or process affecting such rating organization may be served; and

. A statement of its qualifications as a rating organization.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2017%20c%20103%20§%205[2017 c 103 § 5]; ]

== 48.29.415 - Rating organizations—License issuance—Term.
. If the commissioner finds that the applicant for a license as a rating organization is competent, trustworthy, and otherwise qualified to act, and that its constitution, articles of agreement or association, certificate of incorporation, or trust agreement, and its bylaws, rules, and regulations governing the conduct of its business conform to the requirements of law, the commissioner shall, upon payment of a license fee of the amount established by the commissioner pursuant to RCW 48.29.005, issue a license authorizing the applicant to act as a rating organization for title insurance.

. The commissioner shall grant or deny in whole or in part every such application within sixty days of the date of its filing.

. A license issued pursuant to this section remains in effect for three years unless sooner suspended or revoked by the commissioner.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2017%20c%20103%20§%206[2017 c 103 § 6]; ]

== 48.29.420 - Rating organizations—License suspension and revocation.
. The commissioner may, after a hearing, suspend or revoke the license issued to a rating organization for any of the following causes:

.. The commissioner finds that the licensee no longer meets the qualifications for the license.

.. The rating organization fails to comply with an order of the commissioner within the time limited by the order, or any extension thereof which the commissioner may grant.

. The commissioner shall not so suspend or revoke a license for failure to comply with an order until the time prescribed by this code for an appeal from such order to the superior court has expired or if such appeal has been taken, until such order has been affirmed.

. The commissioner may determine when a suspension or revocation of license is effective. A suspension of license remains in effect for the period fixed by the commissioner, unless the commissioner modifies or rescinds the suspension, or until the order, failure to comply with which constituted grounds for the suspension, is modified, rescinded, or reversed.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2017%20c%20103%20§%207[2017 c 103 § 7]; ]

== 48.29.425 - Rating organizations—Commissioner notification.
Every rating organization shall notify the commissioner promptly of every change in:

. Its constitution, its articles of agreement or association, its certificate of incorporation, or trust agreement, and its bylaws, rules, and regulations governing the conduct of its business;

. Its list of members and subscribers; and

. The name and address of the resident of this state designated by it upon whom notices or orders of the commissioner or process affecting such rating organization may be served.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2017%20c%20103%20§%208[2017 c 103 § 8]; ]

== 48.29.430 - Rating organizations—Subscribers.
. Subject to rules and regulations approved by the commissioner as reasonable, each rating organization shall permit any title insurance company, not a member, to subscribe to its rating services.

. Notice of proposed changes to the rules and regulations must be given to each subscriber.

. A title insurer shall not concurrently be a subscriber to the services of more than one rating organization.

. The subscribers of any rating organization may, from time to time, individually or through committees representing various subscribers, consult with the rating organization with respect to matters within this chapter that affect such subscribers.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2017%20c%20103%20§%209[2017 c 103 § 9]; ]

== 48.29.435 - Rating organizations—Review by commissioner.
. The reasonableness of any rule or regulation in its application to subscribers, or the refusal of any rating organization to admit an insurer as a subscriber, shall, at the request of any subscriber or any such insurer, be reviewed by the commissioner at a hearing held upon notice to the rating organization and to the subscriber or insurer.

. If the commissioner finds that a rule or regulation is unreasonable in its application to subscribers, the commissioner shall order that the rule or regulation is not applicable to subscribers that are not members of the rating organization.

. If a rating organization fails to grant or reject an insurer's application for subscribership within thirty days after it was made, the insurer may request a review by the commissioner as if the application had been rejected. If the commissioner finds that the insurer has been refused admittance to the rating organization as a subscriber without justification, the commissioner shall order the rating organization to admit the insurer as a subscriber. If the commissioner finds that the action of the rating organization was justified, the commissioner shall make an order affirming its action.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2017%20c%20103%20§%2010[2017 c 103 § 10]; ]

== 48.29.440 - Rating organizations—Cooperative activities and practices.
. Cooperation among rating organizations or among rating organizations and insurers in rate making or in other matters within the scope of this chapter is hereby authorized and the filings resulting from such cooperation are subject to all the provisions of this title that are applicable to filings generally.

. The commissioner shall review such cooperative activities and practices and if, after a hearing, the commissioner finds that any such activity or practice is inconsistent with the provisions of this code, the commissioner may issue a written order specifying in what respect such activity or practice is so inconsistent, and requiring the discontinuance of such activity or practice.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2017%20c%20103%20§%2011[2017 c 103 § 11]; ]

== 48.29.445 - Rating organizations—Actuarial, technical, and other services.
Any rating organization may subscribe for or purchase actuarial, technical, or other services, and such services must be available to all subscribers without discrimination.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2017%20c%20103%20§%2012[2017 c 103 § 12]; ]

== 48.29.450 - Rating organizations—Records—Commissioner cost recovery rules.
. Each rating organization shall keep an accurate and complete record of all work performed by it, and of all its receipts and disbursements. Such rating organization and its records shall be examined by the commissioner at such times and in such manner as is provided in chapter 48.03 RCW.

. The commissioner may adopt rules to enable the commissioner to recover the costs of the commissioner's examination of a rating organization from the rating organization or the rating organization's members and subscribers.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2017%20c%20103%20§%2013[2017 c 103 § 13]; ]

== 48.29.455 - Rating organizations—Members and subscribers—Appeal to commissioner.
. Any member of or subscriber to a rating organization may appeal to the commissioner from the rating organization's action or decision in approving or rejecting any proposed change in or addition to the rating organization's filings. The commissioner shall, after a hearing on the appeal:

.. Issue an order approving the rating organization's action or decision or directing it to give further consideration to such proposal; or

.. If the appeal is from the rating organization's action or decision in rejecting a proposed addition to its filings, the commissioner may, upon finding that the action or decision was unreasonable, issue an order directing the rating organization to make an addition to its filings, on behalf of its subscribers, in a manner consistent with the commissioner's findings, within a reasonable time after the issuance of such order.

. If such appeal is based upon the rating organization's failure to make a filing on behalf of such subscriber which is based on a system of expense provisions that differs from the system of expense provisions included in a filing made by the rating organization, the commissioner shall, if the appeal is granted, order the rating organization to make the requested filing for use by the appellant.

. In deciding the appeal the commissioner shall apply the standards set forth in RCW 48.29.143 and 48.29.147 for rate filings, and the standards set forth in RCW 48.18.100 and 48.18.110 for form filings.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2017%20c%20103%20§%2015[2017 c 103 § 15]; ]

== 48.29.460 - Rating organizations—Members and subscribers—Discrimination.
. Every rating organization operating in this state shall furnish its services without discrimination as between its members and subscribers.

. This chapter is not intended to and does not govern or affect the membership relation as such between a rating organization and insurers that are its members.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2017%20c%20103%20§%2016[2017 c 103 § 16]; ]

== 48.29.465 - Rating organizations—Membership or subscription not required.
This chapter does not require any insurer to be a member of or subscriber to, or in any other respect affiliated with, any rating organization.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2017%20c%20103%20§%2017[2017 c 103 § 17]; ]

== 48.29.470 - Rating organizations—Aggregate information and experience data—Exchange.
Every rating organization may exchange aggregate information and experience data with insurers, rating organizations in this state, and the statistical reporting agent designated in accordance with RCW 48.29.017, and may consult with insurers and rating organizations in this state with respect to form and rate making and the application of rating systems, except to the extent that an agreement between a rating organization and its member or subscriber prohibits the rating organization from disclosing any information or experience data of such member or subscriber to other insurers, members, subscribers, rating organizations, or the statistical reporting agent.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2017%20c%20103%20§%2018[2017 c 103 § 18]; ]

== 48.29.500 - Advisory organizations—Filings with commissioner.
Every advisory organization before serving as such to any rating organization or insurer doing business in this state must provide the following to the commissioner:

. A copy of its constitution, its articles of agreement or association, or its certificate of incorporation and of its bylaws, rules, and regulations governing its activities;

. A list of its members;

. The name and address of a resident of this state upon whom notices or orders of the commissioner or process issued at his or her direction may be served; and

. An agreement that the commissioner may examine such advisory organization in accordance with the provisions of RCW 48.03.010.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2017%20c%20103%20§%2019[2017 c 103 § 19]; ]

== 48.29.510 - Advisory organizations—Acts and practices inconsistent with chapter.
If, after a hearing, the commissioner finds that the furnishing of information or assistance by an advisory organization involves any act or practice that is inconsistent with the provisions of this code, the commissioner may issue a written order specifying in what respect such act or practice is so inconsistent, and requiring the discontinuance of such act or practice.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2017%20c%20103%20§%2020[2017 c 103 § 20]; ]

== 48.29.901 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%20122[2009 c 521 § 122]; ]

