= 48.35 - Alien insurers.
:toc:

== 48.35.010 - Application—Definition.
This chapter applies to all alien insurers using this state as a state of entry to transact insurance in the United States.

For the purposes of this chapter, "alien insurer" has the definition supplied in RCW 48.05.010.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1971-S.SL.pdf?cite=1991%20c%20268%20§%201[1991 c 268 § 1]; ]

== 48.35.020 - Deposit required—Amount.
. An alien insurer may use this state as a state of entry to transact insurance in the United States by maintaining in this state a deposit of assets in a solvent trust company or other solvent financial institution having trust powers domiciled in this state and so designated by the commissioner. The commissioner's designated depositories are authorized to receive and hold a deposit of assets. A deposit so held is at the expense of the insurer. A solvent financial institution domiciled in this state, the deposits of which are insured by the federal deposit insurance corporation and which is a member of the federal reserve system, may be designated as the commissioner's depository to receive and hold a deposit of assets.

. The deposit, together with other trust deposits of the insurer held in the United States for the same purpose, must be in an amount not less than the higher of deposits required of an alien insurer under RCW 48.05.090 or five hundred thousand dollars and consist of eligible assets as set forth in RCW 48.16.030.

. The deposit may be referred to as "trusteed assets."

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1971-S.SL.pdf?cite=1991%20c%20268%20§%202[1991 c 268 § 2]; ]

== 48.35.030 - Deposit required—Duration.
The deposit required by this chapter must be for the benefit, security, and protection of the policyholders or creditors, or both, of the insurer in the United States. It shall be maintained as long as there is outstanding any liability of the insurer arising out of its insurance transactions in the United States.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1971-S.SL.pdf?cite=1991%20c%20268%20§%204[1991 c 268 § 4]; ]

== 48.35.040 - Trusts created before May 17, 1991.
All trusts of trusteed assets created before May 17, 1991, must be continued under the instruments creating those trusts. If the commissioner determines that the instruments are inconsistent with the provisions of this chapter, the insurer shall correct those inconsistencies within six months of the commissioner's determination.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1971-S.SL.pdf?cite=1991%20c%20268%20§%203[1991 c 268 § 3]; ]

== 48.35.050 - Alien insurer—State authorization required.
An alien insurer proposing to use this state as a state of entry to transact insurance in the United States, must be authorized to transact insurance in this state and may make and execute any trust agreement required by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1971-S.SL.pdf?cite=1991%20c%20268%20§%206[1991 c 268 § 6]; ]

== 48.35.060 - Trusteed assets—Creation—Commissioner's approval of trust agreement.
. The alien insurer shall create the trusteed assets required by this chapter under a written trust agreement between the insurer and the trustee, consistent with the provisions of this chapter, and in such form and manner as the commissioner may designate or approve.

. The agreement is effective when filed with and approved in writing by the commissioner. The commissioner shall not approve any trust agreement not found to be in compliance with state or federal law or the terms of which do not in fact provide reasonably adequate protection for the insurer's policyholders or creditors, or both, in the United States.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1971-S.SL.pdf?cite=1991%20c%20268%20§%205[1991 c 268 § 5]; ]

== 48.35.070 - Trust agreement—Amendment.
A trust agreement may be amended. However, the amendment is not effective until filed with the commissioner and the commissioner finds and states in writing that the amendment is in compliance with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1971-S.SL.pdf?cite=1991%20c%20268%20§%207[1991 c 268 § 7]; ]

== 48.35.080 - Trust agreement—Withdrawal of commissioner's approval.
The commissioner may withdraw his or her approval of a trust agreement, or of an amendment to the agreement, if the commissioner determines that the requisites for the approval no longer exist. The determination shall be made after notice and a hearing as provided in chapter 48.04 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1971-S.SL.pdf?cite=1991%20c%20268%20§%208[1991 c 268 § 8]; ]

== 48.35.090 - Trust agreement—Vesting of trusteed assets.
The trust agreement must provide that title to the trusteed assets vests and remains vested in the trustees and their successors for the purposes of the trust deposit.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1971-S.SL.pdf?cite=1991%20c%20268%20§%209[1991 c 268 § 9]; ]

== 48.35.100 - Trusteed assets—Trustee's records.
The trustee shall keep the trusteed assets separate from other assets and shall maintain a record sufficient to identify the trusteed assets at all times.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1971-S.SL.pdf?cite=1991%20c%20268%20§%2010[1991 c 268 § 10]; ]

== 48.35.110 - Trusteed assets—Trustee's statements—Commissioner's approval.
. The trustee of trusteed assets shall file statements with the commissioner, in a form required by the commissioner, certifying the character and amount of the assets.

. If the trustee fails to file a requested statement after a reasonable time has expired, the commissioner may suspend or revoke the certificate of authority of the insurer required under RCW 48.05.030.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1971-S.SL.pdf?cite=1991%20c%20268%20§%2011[1991 c 268 § 11]; ]

== 48.35.120 - Trusteed assets—Examination—Commissioner's approval of assignment or transfer.
. The commissioner may examine trusteed assets of any insurer at any time in accordance with the same conditions and procedures governing the examination of insurers provided in chapter 48.03 RCW.

. The depositing insurer shall not assign or transfer, voluntarily, involuntarily, or by operation of law, all or a part of its interest in the trusteed assets without the prior written approval of the commissioner, and a transfer or assignment occurring without approval is void. The assignee or transferee of the trusteed assets shall irrevocably and automatically assume all of the obligations and liabilities of the assignor or transferor.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1971-S.SL.pdf?cite=1991%20c%20268%20§%2012[1991 c 268 § 12]; ]

== 48.35.130 - Trusteed assets—Commissioner's approval of withdrawals.
. The trust agreement must provide that the commissioner shall authorize and approve in writing all withdrawals of trusteed assets in advance except as follows:

.. Any or all income, earnings, dividends, or interest accumulations of the trusteed assets may be paid over to the United States manager of the insurer upon request of the insurer or the manager;

.. Withdrawals coincident with substitutions of securities or assets that are at least equal in value to those being withdrawn, if the substituted securities or assets would be eligible for investment by domestic insurers, and the insurer's United States manager requests the withdrawal in writing under a general or specific written authority previously given or delegated by the insurer's board of directors, or other similar governing body, and a copy of such authority has been filed with the trustee;

.. For the purpose of making deposits required by another state in which the insurer is, or becomes, an authorized insurer and for the protection of the insurer's policyholders or creditors, or both, in the state or United States, if the withdrawal does not reduce the insurer's deposit in this state to an amount less than the minimum deposit required. The trustee shall transfer any assets withdrawn and in the amount required to be deposited in the other state, directly to the depositary required to receive the deposit as certified in writing by the public official having supervision of insurance in that state; and

.. For the purpose of transferring the trusteed assets to an official liquidator, conservator, or rehabilitator under an order of a court of competent jurisdiction.

. The commissioner shall authorize a withdrawal of only those assets that are in excess of the amount of assets required to be held in trust, or as may otherwise be consistent with the provisions of this chapter.

. If at any time the insurer becomes insolvent or if its assets held in the United States are less than required as determined by the commissioner, the commissioner shall order in writing the trustee to suspend the withdrawal of assets until a further order of the commissioner releasing the assets.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1971-S.SL.pdf?cite=1991%20c%20268%20§%2013[1991 c 268 § 13]; ]

== 48.35.140 - Trusteed assets—Substitution of trustee.
A new trustee may be substituted for the original trustee of trusteed assets in the event of a vacancy or for other proper cause. Any such substitution is subject to the commissioner's approval.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1971-S.SL.pdf?cite=1991%20c%20268%20§%2014[1991 c 268 § 14]; ]

== 48.35.150 - Trusteed assets—Compensation and expenses of trustees.
The insurer shall provide for the compensation and expenses of the trustees of assets of an alien insurer under this chapter in an amount, or on a basis, as agreed upon by the insurer and the trustees in the trust agreement, subject to the prior approval of the commissioner.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1971-S.SL.pdf?cite=1991%20c%20268%20§%2015[1991 c 268 § 15]; ]

== 48.35.160 - United States manager—Mexican or Canadian insurers.
The provisions of this chapter applicable to a United States manager shall, in the case of insurers domiciled in Mexico or Canada, be deemed to refer to the president, vice president, secretary, or treasurer of the Mexican or Canadian insurer.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1971-S.SL.pdf?cite=1991%20c%20268%20§%2016[1991 c 268 § 16]; ]

== 48.35.170 - Domestication of alien insurer—Commissioner's approval.
. Upon compliance with this chapter, an alien insurer authorized to do business in this state may, with the prior written approval of the commissioner, domesticate its United States branch by entering into an agreement in writing with a domestic insurer providing for the acquisition by the domestic insurer of all of the assets and the assumption of all of the liabilities of the United States branch.

. The acquisition of assets and assumption of liabilities of the United States branch by the domestic insurer is effected by filing with the commissioner an instrument or instruments of transfer and assumption in form satisfactory to the commissioner and executed by the alien insurer and the domestic insurer.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1971-S.SL.pdf?cite=1991%20c%20268%20§%2017[1991 c 268 § 17]; ]

== 48.35.180 - Domestication agreement—Necessary authorization.
. The domestication agreement shall be authorized, adopted, approved, signed, and acknowledged by the alien insurer in accordance with the laws of the country under which it is organized.

. In the case of a domestic insurer, the domestication agreement shall be approved, adopted, and authorized by its board of directors and executed by its president or a vice president and attested by its secretary or assistant secretary under its corporate seal.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1971-S.SL.pdf?cite=1991%20c%20268%20§%2018[1991 c 268 § 18]; ]

== 48.35.190 - Domestication agreement—Commissioner's approval of corporate proceedings.
An executed counterpart of the domestication agreement, together with certified copies of the corporate proceedings of the domestic insurer and the alien insurer, approving, adopting, and authorizing the execution of the domestication agreement, shall be submitted to the commissioner for approval. The commissioner shall thereupon consider the agreement, and, if the commissioner finds that the same is in accordance with the provisions hereof and that the interests of the policyholders of the United States branch of the alien insurer and of the domestic insurer are not materially adversely affected, the commissioner shall approve the domestication agreement and authorize the consummation thereof.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1971-S.SL.pdf?cite=1991%20c%20268%20§%2019[1991 c 268 § 19]; ]

== 48.35.200 - Domestication—When effective—Deposits—Transfer of assets.
. Upon the filing with the commissioner of a certified copy of the instrument of transfer and assumption pursuant to which a domestic company succeeds to the business and assets of the United States branch of an alien insurer and assumes all its liabilities, the domestication of the United States branch is deemed effective; and all the rights, franchises, and interests of the United States branch in and to every species of property and things, in actions thereunder belonging, are deemed as transferred to and vested in the domestic insurer, and simultaneously the domestic insurer is deemed to have assumed all of the liabilities of the United States branch. The domestic insurer is considered as having the age as the oldest of the two parties to the domestication agreement for purposes of laws relating to age of company.

. All deposits of the United States branch held by the commissioner, or by state officers, or other state regulatory agencies pursuant to requirements of state laws, are deemed to be held as security for the satisfaction by the domestic insurer of all liabilities to policyholders within the United States assumed from the United States branch; and the deposits are deemed to be assets of the domestic insurer and are reported as such in the annual financial statements and other reports that the domestic insurer may be required to file. Upon the ultimate release by a state officer or agency of a deposit, the securities and cash constituting the released deposit is delivered and paid over to the domestic insurer as the lawful successor in interest to the United States branch.

. Contemporaneously with the consummation of the domestication of the United States branch, the commissioner shall direct the trustee, if any, of the United States branch's trusteed assets, as set forth in RCW 48.35.020, to transfer and deliver to the domestic insurer all assets, if any, held by such trustee.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1971-S.SL.pdf?cite=1991%20c%20268%20§%2020[1991 c 268 § 20]; ]

