= 48.45 - Rural health care.
:toc:

== 48.45.005 - Findings.
The legislature finds that the residents of rural communities are having difficulties in locating and purchasing affordable health insurance. The legislature further finds that many rural communities have sufficient funds to pay for needed services, but those funds are being expended elsewhere causing insufficient funding of local health services. As part of the solution to this problem, rural communities need to be able to structure the financing of local health services to better serve local residents. The legislature further finds that as rural communities need well financed and organized health care, it is in the interest of residents of rural communities that existing unauthorized entities comply with appropriate fiscal solvency standards and consumer safeguards, and that those entities be given an opportunity to come into compliance with existing state laws.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c271.pdf?cite=1990%20c%20271%20§%2020[1990 c 271 § 20]; ]

== 48.45.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Rural community" means any grouping of consumers, seventy-five percent of whom reside in areas outside of a standard metropolitan statistical area as defined by the United States bureau of census.

. "Consumer" means any person enrolled and eligible to receive benefits in the rural health care arrangement.

. "Rural health care service arrangement" or "arrangement" means any arrangement which is established or maintained for the purpose of offering or providing through the purchase of insurance or otherwise, medical, surgical, or hospital care or benefits in the event of sickness, accident, or disability in a rural community, as defined in this section, that is subject to the jurisdiction of the insurance commissioner but is not now a currently authorized carrier.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c271.pdf?cite=1990%20c%20271%20§%2022[1990 c 271 § 22]; ]

== 48.45.020 - Rural health care service arrangements.
Rural health care service arrangements existing on March 29, 1990, may continue in full operation only so long as they comply with all of the following:

. Within ten days following March 29, 1990, all rural health care service arrangements shall inform the insurance commissioner of their intent to apply for approval to operate as an entity authorized under chapter 48.44 RCW or intend to merge with an entity authorized under Title 48 RCW or merge with an entity defined in this section;

. The arrangement submits an application for approval as an entity authorized under chapter 48.44 RCW by May 1, 1990;

. The arrangement has one hundred thousand dollars on deposit with the insurance commissioner by July 1, 1990;

. The arrangement has one hundred fifty thousand dollars on deposit with the insurance commissioner by September 1, 1990; and

. The arrangement complies with all reasonable requirements of the insurance commissioner excluding the deposit requirement, except as outlined in this section.

If such rural health care service arrangements fail to comply with any of the above requirements, or if during the application process an entity engages in any activities which the insurance commissioner reasonably determines may cause imminent harm to consumers, the entity may be subject to appropriate legal action by the insurance commissioner pursuant to the authority provided in Title 48 RCW.

A rural health care service arrangement which comes into compliance with Title 48 RCW through the method outlined in this chapter shall be subject to all applicable requirements of Title 48 RCW except that the deposit requirements shall not be increased until May 1, 1991.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c271.pdf?cite=1990%20c%20271%20§%2023[1990 c 271 § 23]; ]

== 48.45.030 - Rule making.
The insurance commissioner, pursuant to chapter 34.05 RCW, may promulgate rules to implement RCW 48.45.010 and 48.45.020.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c271.pdf?cite=1990%20c%20271%20§%2024[1990 c 271 § 24]; ]

