= 48.58 - Riot reinsurance reimbursement.
:toc:

== 48.58.010 - Riot reinsurance reimbursement—Assessments.
. The commissioner may reimburse the secretary of the department of housing and urban development under the provisions of Section 1223(a)(1) of the Urban Property Protection and Reinsurance Act of 1968 (Public Law 90-448) for losses reinsured by the secretary of the department of housing and urban development and occurring in this state on or after August 1, 1968. After receipt by the state treasurer of a statement requesting reimbursement from the secretary of the department of housing and urban development and upon certification promptly made by the commissioner of insurance, hereafter referred to as the commissioner, of the correctness of the amount thereof, the commissioner is hereby authorized to provide for an assessment upon insurers authorized to do business in this state in amounts sufficient to pay reimbursement to the secretary of the department of housing and urban development: PROVIDED, That the amount assessed each insurer shall be in the same proportion that the premiums written by each insurer in this state bear to the aggregate premiums written in this state by all insurance companies on those lines for which reinsurance was available in this state from the secretary of the department of housing and urban development during the preceding calendar year.

. In the event any insurer fails, by reason of insolvency, to pay any assessment as provided herein, the amount assessed each insurer, as computed under subsection (1) of this section, shall be immediately recalculated excluding therefrom the insolvent insurer so that its assessment is, in effect, assumed and redistributed among the remaining insurers.

. When assessments as provided herein are made, the individual insurer, after having paid the full amount assessed against the insurer, may deduct from future premium tax liabilities an amount not to exceed twenty percent per annum until such deductions equal the amount of the assessment levied against the insurer.

. This section shall cease to be of any force and effect upon termination of the Urban Property Protection and Reinsurance Act of 1968 (Public Law 90-448), except that obligations incurred pursuant to the provisions of this section shall not be impaired by the expiration of the same.

. Notwithstanding the termination of the Urban Property Protection and Reinsurance Act of 1968 (Public Law 90-448), the commissioner is authorized to continue in force the program developed in response to that act, the Washington essential property insurance inspection and placement program, in order to provide essential property insurance within the state where it cannot be obtained through the normal insurance market.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c128.pdf?cite=1987%20c%20128%20§%201[1987 c 128 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c32.pdf?cite=1980%20c%2032%20§%209[1980 c 32 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c140.pdf?cite=1969%20ex.s.%20c%20140%20§%201[1969 ex.s. c 140 § 1]; ]

