= 48.111 - Home heating fuel service contracts.
:toc:

== 48.111.005 - Findings—Purpose.
The legislature finds that certain service contracts involving providers of home heating fuel and homeowners are in the public interest. The legislature further finds that the existing statutory provisions regulating service contracts are more burdensome than is necessary to safeguard homeowners from the risk that a contract obligor will close or be unable to fulfill their contract obligations. The legislature declares that it is necessary to establish separate standards that will safeguard certain homeowners from possible losses arising from the cessation of business of a home heating fuel company or the mismanagement of funds paid for home heating fuel service contracts. The purpose of this chapter is to create a legal framework within which home heating fuel service contracts may be sold in this state and set forth requirements for conducting a service contract business.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2776-S.SL.pdf?cite=2006%20c%2036%20§%201[2006 c 36 § 1]; ]

== 48.111.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Administrator" means the person who is responsible for the administration of the service contracts or the service contracts plan.

. "Commissioner" means the insurance commissioner of this state.

. "Consumer" means an individual who buys any tangible personal property that is primarily for personal, family, or household use.

. "Home heating fuel service contract" means a contract or agreement for a separately stated consideration for a specific duration to perform the repair, replacement, or maintenance of a customer-owned home heating fuel supply system including the fuel tank and all visible pipes, caps, lines, and associated parts or the indemnification for repair, replacement, or maintenance for operational or structural failure due to a defect in materials or workmanship, or normal wear and tear.

. "Person" means an individual, partnership, corporation, incorporated or unincorporated association, joint stock company, reciprocal insurer, syndicate, or any similar entity or combination of entities acting in concert.

. "Premium" means the consideration paid to an insurer for a reimbursement insurance policy.

. "Provider fee" means the consideration paid by a consumer for a home heating fuel service contract.

. "Reimbursement insurance policy" means a policy of insurance that is issued to a service contract provider to provide reimbursement to the service contract provider or to pay on behalf of the service contract provider all contractual obligations incurred by the service contract provider under the terms of the insured service contracts issued or sold by the service contract provider.

. "Home heating fuel service contract holder" or "contract holder" means a person who is the purchaser or holder of a home heating fuel service contract.

. "Home heating fuel service contract provider" or "contract provider" means a person who is providing home heating fuel delivery services to the customer and is contractually obligated to the home heating fuel service contract holder under the terms of the service contract.

. "Home heating fuel service contract seller" means the person who sells the home heating fuel service contract to the consumer.

. "Warranty" means a warranty made solely by the manufacturer, importer, or seller of property or services without consideration; that is not negotiated or separated from the sale of the product and is incidental to the sale of the product; and that guarantees indemnity for defective parts, mechanical or electrical breakdown, labor, or other remedial measures, such as repair or replacement of the property or repetition of services.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2776-S.SL.pdf?cite=2006%20c%2036%20§%202[2006 c 36 § 2]; ]

== 48.111.020 - Registration required—Application—Required information—Grounds for refusal—Annual renewal.
. A person shall not act as, or offer to act as, or hold himself or herself out to be a home heating fuel service contract provider in this state, nor may a home heating fuel service contract be sold to a consumer in this state, unless the contract provider has a valid registration as a home heating fuel service contract provider issued by the commissioner.

. Applicants to be a home heating fuel service contract provider shall make an application to the commissioner upon a form to be furnished by the commissioner. The application must include or be accompanied by the following information and documents:

.. All basic organizational documents of the home heating fuel service contract provider, including any articles of incorporation, articles of association, partnership agreement, trade name certificate, trust agreement, shareholder agreement, bylaws, and other applicable documents, and all amendments to those documents;

.. The identities of the contract provider's executive officer or officers directly responsible for the contract provider's home heating fuel service contract business;

.. Annual financial statements or other financial reports acceptable to the commissioner for the two most recent years which prove that the applicant is solvent and any information the commissioner may require in order to review the current financial condition of the applicant;

.. An application fee of one hundred dollars, which must be deposited into the general fund; and

.. Any other pertinent information required by the commissioner.

. The commissioner may refuse to issue a registration if the commissioner determines that the home heating fuel service contract provider, or any individual responsible for the conduct of the affairs of the contract provider under subsection (2)(b) of this section, is not competent, trustworthy, or financially responsible.

. A registration issued under this section is valid, unless surrendered, suspended, or revoked by the commissioner, or not renewed for so long as the service contract provider continues in business in this state and remains in compliance with this chapter. A registration is subject to renewal annually on July 1st upon application of the home heating fuel service contract provider and payment of a fee of twenty-five dollars, which must be deposited into the general fund. If not so renewed, the registration expires on June 30th next preceding.

. A home heating fuel service contract provider shall keep current the information required to be disclosed in its registration under this section by reporting all material changes or additions within thirty days after the end of the month in which the change or addition occurs.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5042.SL.pdf?cite=2007%20c%2080%20§%201[2007 c 80 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2776-S.SL.pdf?cite=2006%20c%2036%20§%203[2006 c 36 § 3]; ]

== 48.111.030 - Filing of reports—Investigations—Confidentiality.
. Every registered home heating fuel service contract provider that is assuring its faithful performance of its obligations to its contract holders by complying with RCW 48.111.040(2)(b) shall file an annual report for the preceding calendar year with the commissioner on or before March 1st of each year, or within any extension of time the commissioner for good cause may grant. The report must be in the form and contain those matters as the commissioner prescribes and must be verified by at least two officers of the home heating fuel service contract provider.

. As part of an investigation by the commissioner, the commissioner may require a home heating fuel service contract provider to file monthly financial reports whenever, in the commissioner's discretion, there is a need to more closely monitor the financial activities of the service contract provider. Monthly financial statements must be filed in the commissioner's office no later than the twenty-fifth day of the month following the month for which the financial report is being filed. These monthly financial reports must be the internal financial statements of the service contract provider. The monthly financial reports that are filed with the commissioner constitute information that might be damaging to the service contract provider if made available to its competitors, and therefore shall be kept confidential by the commissioner. This information may not be made public or be subject to subpoena, other than by the commissioner and then only for the purpose of enforcement actions taken by the commissioner.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2776-S.SL.pdf?cite=2006%20c%2036%20§%204[2006 c 36 § 4]; ]

== 48.111.040 - Obligations of contract provider.
. Home heating fuel service contracts may not be issued, sold, or offered for sale in this state or sold to consumers in this state unless the contract provider has:

.. Provided a receipt for, or other written evidence of, the purchase of the home heating fuel service contract to the contract holder; and

.. Provided a copy of the home heating fuel service contract to the service contract holder within a reasonable period of time from the date of purchase.

. In order to assure the faithful performance of a home heating fuel service contract provider's obligations to its contract holders, every home heating fuel service contract provider is responsible for complying with the requirements of one of the following:

.. Insure all home heating fuel service contracts under a reimbursement insurance policy issued by an insurer holding a certificate of authority from the commissioner; or

.. [Empty]
... Maintain a funded reserve account for its obligations under its home heating service contracts issued and outstanding in this state. The reserves may not be less than forty percent of the gross consideration received, less claims paid, on the sale of the home heating fuel service contract for all in-force contracts. The reserve account is subject to examination and review by the insurance commissioner; and

... Place in trust with the commissioner a financial security deposit, having a value of not less than five percent of the gross consideration received, less claims paid, on the sale of the service contract for all service contracts issued and in force, but not less than ten thousand dollars, consisting of one of the following:

(A) A surety bond issued by an insurer holding a certificate of authority from the commissioner;

(B) Securities of the type eligible for deposit by authorized insurers in this state;

(C) Cash;

(D) An evergreen letter of credit issued by a qualified financial institution;

(E) A pledged certificate of deposit issued by a qualified financial institution; or

(F) Another form of security prescribed by rule by the commissioner.

. Home heating fuel service contracts must require the contract provider to permit the contract holder to return the home heating fuel service contract within thirty days of the date the home heating fuel service contract was delivered to the contract holder, or within a longer time period permitted under the home heating fuel service contract. Upon return of the home heating fuel service contract to the contract provider within the applicable period, if no claim has been made under the home heating fuel service contract prior to the return to the contract provider, the home heating fuel service contract is void and the contract provider shall refund to the contract holder, or credit the account of the contract holder with the full purchase price of the home heating fuel service contract. The right to void the home heating fuel service contract provided in this subsection is not transferable and applies only to the original contract purchaser. A ten percent penalty per month must be added to a refund of the purchase price that is not paid or credited within thirty days after return of the home heating fuel service contract to the contract provider.

. Except for home heating fuel service contract providers, persons marketing, selling, or offering to sell home heating service contracts for providers are exempt from the registration requirements of this chapter.

. The marketing, sale, offering for sale, issuance, making, proposing to make, and administration of home heating fuel service contracts by contract providers and related contract sellers, administrators, and other persons complying with this chapter are exempt from the other provisions of this title, except chapter 48.04 RCW and as otherwise provided in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2776-S.SL.pdf?cite=2006%20c%2036%20§%205[2006 c 36 § 5]; ]

== 48.111.050 - Reimbursement insurance policies insuring home heating fuel service contracts.
. Reimbursement insurance policies insuring home heating fuel service contracts issued, sold, or offered for sale in this state or sold to consumers in this state must state that the insurer that issued the reimbursement insurance policy shall reimburse or pay on behalf of the contract provider all sums the contract provider is legally obligated to pay, including but not limited to the refund of the full purchase price of the contract to the contract holder or shall provide the service which the contract provider is legally obligated to perform according to the contract provider's contractual obligations under the home heating fuel service contracts issued or sold by the contract provider.

. The reimbursement insurance policy must fully insure the obligations of the contract provider, rather than partially insure, or insure only in the event of contract provider default.

. The reimbursement insurance policy must state that the contract holder is entitled to apply directly to the reimbursement insurance company.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2776-S.SL.pdf?cite=2006%20c%2036%20§%206[2006 c 36 § 6]; ]

== 48.111.053 - Termination of reimbursement insurance policies.
As applicable, an insurer that issued a reimbursement insurance policy shall not terminate the policy until a notice of termination in accordance with RCW 48.18.290 has been given to the home heating fuel service contract provider and has been delivered to the commissioner. The termination of a reimbursement insurance policy does not reduce the issuer's responsibility for home heating fuel service contracts issued by contract providers prior to the effective date of the termination.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2776-S.SL.pdf?cite=2006%20c%2036%20§%2010[2006 c 36 § 10]; ]

== 48.111.055 - Insurer issuing reimbursement insurance policy—Contract provider is agent.
. Home heating fuel service contract providers are the agent of the insurer that issued the reimbursement insurance policy for purposes of obligating the insurer to contract holders in accordance with the home heating fuel service contract and this chapter. Payment of the provider fee by the consumer to the home heating fuel service contract seller, contract provider, or administrator constitutes payment by the consumer to the home heating fuel service contract provider and to the insurer that issued the reimbursement insurance policy. In cases when a contract provider is acting as an administrator and enlists other contract providers, the contract provider acting as the administrator shall notify the insurer of the existence and identities of the other contract providers.

. This chapter does not prevent or limit the right of an insurer that issued a reimbursement insurance policy to seek indemnification or subrogation against a home heating fuel service contract provider if the issuer pays or is obligated to pay the contract holder sums that the contract provider was obligated to pay under the provisions of the home heating fuel service contract.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2776-S.SL.pdf?cite=2006%20c%2036%20§%2011[2006 c 36 § 11]; ]

== 48.111.060 - Home heating fuel service contracts—Form—Required contents.
. Home heating fuel service contracts marketed, sold, offered for sale, issued, made, proposed to be made, or administered in this state or sold to residents of this state must be written, printed, or typed in clear, understandable language that is easy to read, and disclose the requirements set forth in this section, as applicable.

. Home heating fuel service contracts insured under a reimbursement insurance policy must not be issued, sold, or offered for sale in this state or sold to residents of this state unless the home heating fuel service contract conspicuously contains a statement in substantially the following form: "Obligations of the home heating fuel service contract provider under this contract are insured under a contract reimbursement insurance policy." The home heating fuel service contract must also conspicuously state the name and address of the issuer of the reimbursement insurance policy and state that the contract holder is entitled to apply directly to the reimbursement insurance company.

. Service contracts not insured under a reimbursement insurance policy must contain a statement in substantially the following form: "Obligations of the home heating fuel service contract provider under this contract are backed by the full faith and credit of the home heating fuel service contract provider."

. Home heating fuel service contracts must state the name and address of the contract provider and must identify any administrator if different from the contract provider, the contract seller, and the contract holder to the extent that the name of the contract holder has been furnished by the contract holder. The identities of the parties are not required to be preprinted on the home heating fuel service contract and may be added to the home heating fuel service contract at the time of sale.

. Home heating fuel service contracts must state the purchase price of the contract and the terms under which the home heating fuel service contract is sold. The purchase price is not required to be preprinted on the home heating fuel service contract and may be negotiated at the time of sale.

. Home heating fuel service contracts must state the procedure to obtain service or to file a claim, including but not limited to the procedures for obtaining prior approval for repair work, the toll-free telephone number if prior approval is necessary for service, and the procedure for obtaining emergency repairs performed outside of normal business hours or provide for twenty-four hour telephone assistance.

. Home heating fuel service contracts must state the existence of any deductible amount, if applicable.

. Home heating fuel service contracts must specify the merchandise and services to be provided and any limitations, exceptions, or exclusions.

. Home heating fuel service contracts must state any restrictions governing the transferability of the service contract, if applicable.

. Home heating fuel service contracts must state the terms, restrictions, or conditions governing cancellation of the home heating fuel service contract prior to the termination or expiration date of the home heating fuel service contract by either the contract provider or by the contract holder, which rights can be no more restrictive than provided in RCW 48.111.040. The contract provider of the home heating fuel service contract shall mail a written notice to the contract holder at the last known address of the contract holder contained in the records of the contract provider at least twenty-one days prior to cancellation by the contract provider. The notice must state the effective date of the cancellation and the true and actual reason for the cancellation.

. Home heating fuel service contracts must set forth the obligations and duties of the contract holder, including but not limited to the duty to protect against any further damage and any requirement to follow owner's manual instructions.

. Home heating fuel service contracts must state whether or not the home heating fuel service contract provides for or excludes consequential damages or preexisting conditions.

. Home heating fuel service contracts must not contain a provision that requires that any civil action brought in connection with the home heating fuel service contract must be brought in the courts of a jurisdiction other than this state. Home heating service contracts that authorize binding arbitration to resolve claims or disputes may allow for arbitration proceedings to be held at a location in closest proximity to the contract holder's permanent residence.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2776-S.SL.pdf?cite=2006%20c%2036%20§%207[2006 c 36 § 7]; ]

== 48.111.070 - Name of contract provider—Use of legal name—False or misleading statements—Restrictions on requirement to purchase service contracts.
. A home heating fuel service contract provider shall not use in its name the words insurance, casualty, guaranty, surety, mutual, or any other words descriptive of the insurance, casualty, guaranty, or surety business; or a name deceptively similar to the name or description of any insurance or surety corporation, or to the name of any other home heating fuel service contract provider. This subsection does not apply to a company that was using any of the prohibited language in its name prior to June 7, 2006. However, a company using the prohibited language in its name shall conspicuously disclose in its home heating fuel service contracts the following statement: "This agreement is not an insurance contract."

. Every home heating fuel service contract provider shall conduct its business in its own legal name, unless the commissioner has approved the use of another name.

. A home heating fuel service contract provider or its representative shall not in its contracts or literature make, permit, or cause to be made any false or misleading statement, or deliberately omit any material statement that would be considered misleading if omitted.

. A person, such as a bank, savings and loan association, lending institution, manufacturer, or seller shall not require the purchase of a home heating fuel service contract as a condition of a loan or a condition for the sale of any property.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2776-S.SL.pdf?cite=2006%20c%2036%20§%208[2006 c 36 § 8]; ]

== 48.111.080 - Recordkeeping of contract provider—Requirements—Form.
. The home heating fuel service contract provider shall keep accurate accounts, books, and records concerning transactions regulated under this chapter.

. The contract provider's accounts, books, and records must include the following:

.. Copies of each type of home heating fuel service contract sold;

.. The name and address of each contract holder, to the extent that the name and address have been furnished by the contract holder; and

.. Written claim files that contain at least the dates, amounts, and descriptions of claims related to the service contracts.

. The records required under this chapter may be, but are not required to be, maintained on a computer disk or other recordkeeping technology. If the records are maintained in other than hard copy, the records must be capable of duplication to legible hard copy.

. A home heating fuel service contract provider discontinuing business in this state shall maintain its records until it furnishes the commissioner satisfactory proof that it has discharged all obligations to service contract holders in this state.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2776-S.SL.pdf?cite=2006%20c%2036%20§%209[2006 c 36 § 9]; ]

== 48.111.090 - Commissioner may conduct investigations.
. The commissioner may conduct investigations of home heating fuel service contract providers, administrators, home heating fuel service contract sellers, insurers, and other persons to enforce this chapter and protect home heating fuel service contract holders in this state. Upon request of the commissioner, the contract provider shall make all accounts, books, and records concerning home heating fuel service contracts sold by the contract provider available to the commissioner that are necessary to enable the commissioner to determine compliance or noncompliance with this chapter.

. The commissioner may take actions under RCW 48.02.080 or 48.04.050 that are necessary or appropriate to enforce this chapter and the commissioner's rules and orders, and to protect home heating fuel service contract holders in this state.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2776-S.SL.pdf?cite=2006%20c%2036%20§%2012[2006 c 36 § 12]; ]

== 48.111.100 - Denial, suspension, or revocation of registration—Immediate suspension without notice or hearing—Fine.
. The commissioner may, subject to chapter 48.04 RCW, deny, suspend, or revoke the registration of a home heating fuel service contract provider if the commissioner finds that the contract provider:

.. Has violated this chapter or the commissioner's rules and orders;

.. Has refused to be investigated or to produce its accounts, records, and files for investigation, or if any of its officers have refused to give information with respect to its affairs or refused to perform any other legal obligation as to an investigation, when required by the commissioner;

.. Has, without just cause, refused to pay proper claims or perform services arising under its contracts or has, without just cause, caused home heating fuel service contract holders to accept less than the amount due them or caused home heating fuel service contract holders to employ attorneys or bring suit against the contract provider to secure full payment or settlement of claims;

.. Is affiliated with or under the same general management or interlocking directorate or ownership as another home heating fuel service contract provider that unlawfully transacts business in this state without having a registration;

.. At any time fails to meet any qualification for which issuance of the registration could have been refused had that failure then existed and been known to the commissioner;

.. Is under suspension or revocation in another state with respect to its home heating fuel service contract business;

.. Has made a material misstatement in its application for registration;

.. Has obtained or attempted to obtain a registration through misrepresentation or fraud;

.. Has, in the transaction of business under its registration, used fraudulent, coercive, or dishonest practices; 

.. Has failed to pay any judgment rendered against it in this state regarding a home heating fuel service contract within sixty days after the judgment has become final; or

.. Has been convicted of, or has entered a plea of guilty or nolo contendere to, a property or finance-related felony.

. The commissioner may, without advance notice or hearing thereon, immediately suspend the registration of a home heating fuel service contract provider if the commissioner finds that any of the following circumstances exist:

.. The provider is insolvent;

.. A proceeding for receivership, conservatorship, rehabilitation, or other delinquency proceeding regarding the home heating fuel service contract provider has been commenced in any state; or

.. The financial condition or business practices of the home heating fuel service contract provider otherwise pose an imminent threat to the public health, safety, or welfare of the residents of this state.

. If the commissioner finds that grounds exist for the suspension or revocation of a registration issued under this chapter, the commissioner may, in lieu of suspension or revocation, impose a fine upon the home heating fuel service contract provider in an amount not more than one thousand dollars per violation.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2776-S.SL.pdf?cite=2006%20c%2036%20§%2013[2006 c 36 § 13]; ]

== 48.111.110 - Rules.
The commissioner may adopt rules to implement and administer this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2776-S.SL.pdf?cite=2006%20c%2036%20§%2014[2006 c 36 § 14]; ]

== 48.111.900 - Application.
This chapter applies to all home heating fuel service contracts sold or offered for sale after October 1, 2006.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2776-S.SL.pdf?cite=2006%20c%2036%20§%2015[2006 c 36 § 15]; ]

