= 48.180 - Nonprofit corporations—Joint self-insurance programs.
:toc:

== 48.180.005 - Intent—Liberal construction.
This chapter is intended to provide authority for two or more nonprofit corporations to participate in a joint self-insurance program covering property or liability risks. This chapter provides nonprofit corporations with the authority to jointly self-insure property and liability risks, jointly purchase insurance or reinsurance, and contract for risk management, claims, and administrative services with other nonprofit corporations. This chapter must be liberally construed to grant nonprofit corporations maximum flexibility in jointly self-insuring to the extent the self-insurance programs are operated in a safe and sound manner. This chapter is intended to require prior approval for the establishment of every joint self-insurance program. In addition, this chapter is intended to require every joint self-insurance program for nonprofit corporations established under this chapter to notify the state of the existence of the program and to comply with the regulatory and statutory standards governing the management and operation of the programs as provided in this chapter. This chapter is not intended to authorize or regulate self-insurance of unemployment compensation under chapter 50.44 RCW or industrial insurance under chapter 51.14 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5119.SL.pdf?cite=2015%20c%20109%20§%205[2015 c 109 § 5]; ]

== 48.180.010 - Definitions. (Effective until January 1, 2022.)
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Nonprofit corporation" or "corporation" has the same meaning as defined in RCW 24.03.005.

. "Property and liability risks" includes the risk of property damage or loss sustained by a nonprofit corporation and the risk of claims arising from the tortious or negligent conduct or any error or omission of the entity, its officers, employees, agents, or volunteers as a result of a claim that may be made against the entity.

. "Self-insurance" means a formal program of advance funding and management of entity financial exposure to a risk of loss that is not transferred through the purchase of an insurance policy or contract.

. "State risk manager" means the risk manager of the office of risk management within the department of enterprise services.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5119.SL.pdf?cite=2015%20c%20109%20§%206[2015 c 109 § 6]; ]

== 48.180.015 - Agreement to form joint self-insurance program—Authorized activities—State risk manager as attorney for receipt of service.
. The governing body of a nonprofit corporation may join or form a self-insurance program together with one or more other nonprofit corporations, and may jointly purchase insurance or reinsurance with one or more other nonprofit corporations for property and liability risks only as permitted under this chapter. Nonprofit corporations may contract for or hire personnel to provide risk management, claims, and administrative services in accordance with this chapter.

. The agreement to form a joint self-insurance program may include the organization of a separate legal or administrative entity with powers delegated to the entity. The entity may include or create a nonprofit corporation as defined in RCW 48.62.021.

. If provided for in the organizational documents, a joint self-insurance program may, in conformance with this chapter:

.. Contract or otherwise provide for risk management and loss control services;

.. Contract or otherwise provide legal counsel for the defense of claims and other legal services;

.. Consult with the state insurance commissioner and the state risk manager;

.. Jointly purchase insurance and reinsurance coverage in a form and amount as provided for in the organizational documents;

.. Obligate the program's participants to pledge funds or revenues to secure the obligations or pay the expenses of the program, including the establishment of a reserve fund for coverage, including an additional assessment if the reserve fund or the program's revenue or assets are insufficient to cover the program's liabilities; and

.. Possess any other powers and perform all other functions reasonably necessary to carry out the purposes of this chapter.

. Every joint self-insurance program governed by this chapter must appoint the state risk manager as its attorney to receive service of, and upon whom must be served, all legal process issued against the program in this state upon causes of action arising in this state.

.. Service upon the state risk manager as attorney constitutes service upon the program. Service upon joint self-insurance programs subject to this chapter may only occur by service upon the state risk manager. At the time of service, the plaintiff shall pay to the state risk manager a fee to be set by the state risk manager, taxable as costs in the action.

.. With the initial filing for approval with the state risk manager, each joint self-insurance program must designate by name and address the person to whom the state risk manager must forward legal process that is served upon him or her. The joint self-insurance program may change this person by filing a new designation.

.. The appointment of the state risk manager as attorney is irrevocable, binds any successor in interest or to the assets or liabilities of the joint self-insurance program, and remains in effect as long as there is in force in this state any contract made by the joint self-insurance program or liabilities or duties arising from the contract.

.. The state risk manager shall keep a record of the day and hour of service upon him or her of all legal process. A copy of the process, by registered mail with return receipt requested, must be sent by the state risk manager to the person designated to receive legal process by the joint self-insurance program in its most recent designation filed with the state risk manager. Proceedings may not commence against the joint self-insurance program, and the program is not required to appear, plead, or answer, until the expiration of forty days after the date of service upon the state risk manager.

.. For any legal process issued against the program for causes of action arising outside of this state, the program shall provide the state risk manager a copy of such claim.

. A nonprofit joint self-insurance program previously established under chapter 48.62 RCW may continue its operations without interruption. All previously approved operating documents under chapter 48.62 RCW including, but not limited to, applications, state-granted authorities, approvals to operate, certificates of incorporation, articles of incorporation, membership documents, executed contracts, and other applicable items or authorities remain in effect without reapproval.

. A nonprofit joint self-insurance program previously established under and governed by chapter 48.62 RCW is not required to reapply for authority to operate as previously approved by the state risk manager in its original application.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5119.SL.pdf?cite=2015%20c%20109%20§%207[2015 c 109 § 7]; ]

== 48.180.020 - When chapter does not apply.
This chapter does not apply to a nonprofit corporation that:

. Individually self-insures for property and liability risks;

. Participates in a risk pooling arrangement, including a risk retention group or a risk purchasing group, regulated under chapter 48.92 RCW, or is a captive insurer authorized in its state of domicile;

. Comprises only units of local government or is a group that comprises local governments joined by an interlocal agreement authorized by chapter 39.34 RCW; or

. Is a hospital licensed under chapter 70.41 RCW, or an entity owned, operated, controlled by, or affiliated with such a hospital that participates in a self-insurance risk pool or other risk pooling arrangement.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5119.SL.pdf?cite=2015%20c%20109%20§%208[2015 c 109 § 8]; ]

== 48.180.025 - Rules by state risk manager—Requirements.
The state risk manager shall adopt rules governing the management and operation of joint self-insurance programs for nonprofit corporations that cover property or liability risks. All rules must be appropriate for the type of program and class of risk covered. The state risk manager's rules must include:

. Standards for the management, operation, and solvency of joint self-insurance programs, including the necessity and frequency of actuarial analyses and claims audits;

. Standards for claims management procedures;

. Standards for contracts between joint self-insurance programs and private businesses, including standards for contracts between third-party administrators and programs; and

. Standards requiring pool verification of each member's nonprofit status in their state of domicile.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5119.SL.pdf?cite=2015%20c%20109%20§%209[2015 c 109 § 9]; ]

== 48.180.030 - Program approval required from state risk manager—Management and operations plan—Contents of plan.
Before the establishment of a joint self-insurance program covering property or liability risks by nonprofit corporations, the entities must obtain the approval of the state risk manager. The entities proposing the creation of a joint self-insurance program requiring prior approval shall submit a plan of management and operation to the state risk manager that provides at least the following information:

. The risk or risks to be covered, including any coverage definitions, terms, conditions, and limitations;

. The amount and method of funding the covered risks, including the initial capital and proposed rates and projected premiums;

. The proposed claim reserving practices;

. The proposed purchase and maintenance of insurance or reinsurance in excess of the amounts retained by the joint self-insurance program;

. The legal form of the program including, but not limited to, any articles of incorporation, bylaws, charter, or trust agreement or other agreement among the participating entities;

. The agreements with participants in the program defining the responsibilities and benefits of each participant and management;

. The proposed accounting, depositing, and investment practices of the program;

. The proposed time when actuarial analysis will be first conducted and the frequency of future actuarial analysis;

. A designation of the individual to whom service of process must be forwarded by the state risk manager on behalf of the program;

. All contracts between the program and private persons providing risk management, claims, or other administrative services;

. A professional analysis of the feasibility of the creation and maintenance of the program;

. A legal analysis or an internal revenue service opinion on the federal income tax exposure or liability of the program; and

. Any other information required by rule of the state risk manager that is necessary to determine the probable financial and management success of the program or that is necessary to determine compliance with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5119.SL.pdf?cite=2015%20c%20109%20§%2010[2015 c 109 § 10]; ]

== 48.180.035 - Participation by nonprofit corporations from other states—Requirements.
A nonprofit corporation may participate in a joint self-insurance program covering property or liability risks with similar nonprofit corporations from other states if the program satisfies the following requirements:

. An ownership interest in the program is limited to some or all of the nonprofit corporations of this state and nonprofit corporations of other states that are provided insurance by the program;

. The nonprofit corporations of this state and other states shall elect a board of directors to manage the program, all of whom must be affiliated with one or more of the participating nonprofit corporations;

. The program must provide coverage through the delivery to each participating nonprofit corporation of one or more written policies affecting insurance of covered risks;

. The program must be financed, including the payment of premiums and the contribution of initial capital, in accordance with the plan of management and operation submitted to the state risk manager in accordance with this chapter;

. The financial statements of the program must be audited by a certified public accountant, and these audited financial statements must be delivered to the state risk manager not more than one hundred twenty days after the end of each fiscal year of the program;

. The investments of the program must be initiated only with financial institutions or broker-dealers, or both, doing business in those states in which participating nonprofit corporations are located, and these investments must be audited annually by the certified public accountants for the program;

. The treasurer of a multistate joint self-insurance program must be designated by resolution of the program and the treasurer must be located in the state of one of the participating entities; and

. The program must obtain approval from the state risk manager in accordance with this chapter and must remain in compliance with this chapter, unless exempt from application for reapproval, as granted under RCW 48.180.015.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5119.SL.pdf?cite=2015%20c%20109%20§%2011[2015 c 109 § 11]; ]

== 48.180.040 - Approval or disapproval by state risk manager—Within one hundred twenty days—Risk manager's powers and duties—Program's obligations.
. Within one hundred twenty days of receipt of a plan of management and operation, the state risk manager shall either approve or disapprove of the formation of the joint self-insurance program after reviewing the plan to determine whether the proposed program complies with this chapter and all rules adopted in accordance with this chapter.

. If the state risk manager denies a request for approval, the state risk manager shall specify in detail the reasons for denial and the manner in which the program fails to meet the requirements of this chapter or any rules adopted in accordance with this chapter.

. If the state risk manager determines that a joint self-insurance program covering property or liability risks is in violation of this chapter or is operating in an unsafe financial condition, the state risk manager may issue and serve upon the program an order to cease and desist from the violation or practice.

.. The state risk manager shall deliver the order to the appropriate entity or entities directly or mail it to the appropriate entity or entities by certified mail with return receipt requested.

.. If the program violates the order or has not taken steps to comply with the order after the expiration of twenty days after the cease and desist order has been received by the program, the program is deemed to be operating in violation of this chapter, and the state risk manager shall notify the attorney general of the violation.

.. After hearing, or with the consent of a program governed under this chapter, and in addition to or in lieu of a continuation of the cease and desist order, the state risk manager may levy a fine upon the program in an amount not less than three hundred dollars and not more than ten thousand dollars. The order levying the fine must specify the period within which the fine must be fully paid. The period within which the fines must be paid must be not less than fifteen and not more than thirty days from the date of the order. Upon failure to pay the fine when due, the state risk manager shall request the attorney general to bring a civil action on the state risk manager's behalf to collect the fine. The state risk manager shall pay any fine collected to the state treasurer for deposit into the general fund.

. Each joint self-insurance program approved by the state risk manager shall annually file a report with the state risk manager providing:

.. Details of any changes in the articles of incorporation, bylaws, charter, trust agreement, or other agreement among the participating nonprofit corporations;

.. Copies of all the insurance coverage documents;

.. A description of the program structure, including participants' retention, program retention, and excess insurance limits and attachment point;

.. An actuarial analysis;

.. A list of contractors and service providers;

.. The financial and loss experience of the program; and

.. Other information as required by rule of the state risk manager.

. A joint self-insurance program requiring the state risk manager's approval may not engage in an act or practice that in any respect significantly differs from the management and operation plan that formed the basis for the state risk manager's approval of the program unless the program first notifies the state risk manager in writing and obtains the state risk manager's approval. The state risk manager shall approve or disapprove the proposed change within sixty days of receipt of the notice. If the state risk manager denies a requested change, the state risk manager shall specify in detail the reasons for the denial and the manner in which the program would fail to meet the requirements of this chapter or any rules adopted in accordance with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5119.SL.pdf?cite=2015%20c%20109%20§%2012[2015 c 109 § 12]; ]

== 48.180.045 - Treasurer may be designated by resolution—Bond—Program's interest and earnings.
. A joint self-insurance program may by resolution of the program designate a person having experience with investments or financial matters as treasurer of the program. The program must require a bond obtained from a surety company in an amount and under the terms and conditions that the program finds will protect against loss arising from mismanagement or malfeasance in investing and managing program funds. The program may pay the premium on the bond.

. All interest and earnings collected on joint self-insurance program funds belong to the program and must be deposited to the program's credit in the proper program account.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5119.SL.pdf?cite=2015%20c%20109%20§%2013[2015 c 109 § 13]; ]

== 48.180.050 - Prohibition on receiving anything of value for services rendered.
. An employee or official of a participating nonprofit corporation in a joint self-insurance program may not directly or indirectly receive anything of value for services rendered in connection with the operation and management of a self-insurance program other than the salary and benefits provided by his or her employer or the reimbursement of expenses reasonably incurred in furtherance of the operation or management of the program. An employee or official of a participating nonprofit corporation in a joint self-insurance program may not accept or solicit anything of value for personal benefit or for the benefit of others under circumstances in which it can be reasonably inferred that the employee's or official's independence of judgment is impaired with respect to the management and operation of the program.

. RCW 48.30.140, 48.30.150, and 48.30.157 apply to the use of insurance producers and surplus line brokers by a joint self-insurance program.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5119.SL.pdf?cite=2015%20c%20109%20§%2014[2015 c 109 § 14]; ]

== 48.180.055 - Program exempt from certain taxes and fees.
A joint self-insurance program approved in accordance with this chapter is exempt from insurance premium taxes, fees assessed under chapters 48.02, 48.32, and 48.32A RCW, business and occupation taxes imposed under chapter 82.04 RCW, and any assigned risk plan or joint underwriting association otherwise required by law. This section does not apply to or provide exemptions for insurance companies issuing policies to cover program risks and third-party administrators or insurance producers serving the joint self-insurance program.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5119.SL.pdf?cite=2015%20c%20109%20§%2015[2015 c 109 § 15]; ]

== 48.180.060 - Investigation fee—Use—Failure to pay.
. The state risk manager shall establish and charge an investigation fee in an amount necessary to cover the costs for the initial review and approval of a joint self-insurance program. The fee must accompany the initial submission of the plan of operation and management.

. The costs of subsequent reviews and investigations must be charged to the joint self-insurance program being reviewed or investigated in accordance with the actual time and expenses incurred in the review or investigation.

. Any program failing to remit its assessment when due is subject to denial of permission to operate or to a cease and desist order until the assessment is paid.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5119.SL.pdf?cite=2015%20c%20109%20§%2016[2015 c 109 § 16]; ]

== 48.180.065 - Immunity from liability—Person who files, reports, or furnishes information—State risk manager and agents or employees.
. Any person who files, reports, or furnishes other information required under this title, required by the state risk manager under the authority granted under this title, or which is useful to the state risk manager in the administration of this title is immune from liability in any civil action or suit arising from the filing of any such report or furnishing such information to the state risk manager, unless actual malice, fraud, or bad faith is shown.

. The state risk manager and his or her agents and employees are immune from liability in any civil action or suit arising from the publication of any report or bulletin or from dissemination of information related to the official activities of the state risk manager unless actual malice, fraud, or bad faith is shown.

. The immunity granted under this section is in addition to any common law or statutory privilege or immunity enjoyed by such person. This section is not intended to abrogate or modify in any way such common law or statutory privilege or immunity.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5119.SL.pdf?cite=2015%20c%20109%20§%2017[2015 c 109 § 17]; ]

