= 48.155 - Health care discount plan organization act.
:toc:

== 48.155.001 - Short title.
This chapter may be known and cited as the Washington health care discount plan organization act.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5480-S.SL.pdf?cite=2009%20c%20175%20§%201[2009 c 175 § 1]; ]

== 48.155.003 - Purpose.
The purposes of this chapter are to promote the public interest by establishing standards for discount plan organizations, to protect consumers from unfair or deceptive marketing, sales, or enrollment practices, and to facilitate consumer understanding of the role and function of discount plan organizations in providing discounts on charges for health care services.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5480-S.SL.pdf?cite=2009%20c%20175%20§%202[2009 c 175 § 2]; ]

== 48.155.007 - Rules.
The commissioner may adopt rules to implement this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5480-S.SL.pdf?cite=2009%20c%20175%20§%2018[2009 c 175 § 18]; ]

== 48.155.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Affiliate" means a person that directly, or indirectly through one or more intermediaries, controls, or is controlled by, or is under common control with, the person specified.

. "Commissioner" means the Washington state insurance commissioner.

. [Empty]
.. "Control" or "controlled by" or "under common control with" means the possession, direct or indirect, of the power to direct or cause the direction of the management and policies of a person, whether through the ownership of voting securities, by contract other than a commercial contract for goods or nonmanagement services, or otherwise, unless the power is the result of an official position with or corporate office held by the person.

.. Control exists when any person, directly or indirectly, owns, controls, holds with the power to vote, or holds proxies representing ten percent or more of the voting securities of any other person. A presumption of control may be rebutted by a showing made in the manner provided by RCW 48.31B.005(3) and 48.31B.025(11) that control does not exist in fact. The commissioner may determine, after furnishing all persons in interest notice and opportunity to be heard and making specific findings of fact to support the determination, that control exists in fact, notwithstanding the absence of a presumption to that effect.

. [Empty]
.. "Discount plan" means a business arrangement or contract in which a person or organization, in exchange for fees, dues, charges, or other consideration, provides or purports to provide discounts to its members on charges by providers for health care services.

.. "Discount plan" does not include:

... A plan that does not charge a membership or other fee to use the plan's discount card;

... A patient access program as defined in this chapter;

... A medicare prescription drug plan as defined in this chapter; or

... A discount plan offered by a health carrier authorized under chapter 48.20, 48.21, 48.44, or 48.46 RCW.

. [Empty]
.. "Discount plan organization" means a person that, in exchange for fees, dues, charges, or other consideration, provides or purports to provide access to discounts to its members on charges by providers for health care services. "Discount plan organization" also means a person or organization that contracts with providers, provider networks, or other discount plan organizations to offer discounts on health care services to its members. This term also includes all persons that determine the charge to or other consideration paid by members.

.. "Discount plan organization" does not mean:

... Pharmacy benefit managers;

... Health care provider networks, when the network's only involvement in discount plans is contracting with the plan to provide discounts to the plan's members;

... Marketers who market the discount plans of discount plan organizations which are licensed under this chapter as long as all written communications of the marketer in connection with a discount plan clearly identify the licensed discount plan organization as the responsible entity; or

... Health carriers, if the discount on health care services is offered by a health carrier authorized under chapter 48.20, 48.21, 48.44, or 48.46 RCW.

. "Health care facility" or "facility" has the same meaning as in *RCW 48.43.005(22).

. "Health care provider" or "provider" has the same meaning as in *RCW 48.43.005(23).

. "Health care provider network," "provider network," or "network" means any network of health care providers, including any person or entity that negotiates directly or indirectly with a discount plan organization on behalf of more than one provider to provide health care services to members.

. "Health care services" has the same meaning as in *RCW 48.43.005(24).

. "Health carrier" or "carrier" has the same meaning as in *RCW 48.43.005(25).

. "Marketer" means a person or entity that markets, promotes, sells, or distributes a discount plan, including a contracted marketing organization and a private label entity that places its name on and markets or distributes a discount plan pursuant to a marketing agreement with a discount plan organization.

. "Medicare prescription drug plan" means a plan that provides a medicare part D prescription drug benefit in accordance with the requirements of the federal medicare prescription drug improvement and modernization act of 2003.

. "Member" means any individual who pays fees, dues, charges, or other consideration for the right to receive the benefits of a discount plan, but does not include any individual who enrolls in a patient access program.

. "Patient access program" means a voluntary program sponsored by a pharmaceutical manufacturer, or a consortium of pharmaceutical manufacturers, that provides free or discounted health care products for no additional consideration directly to low-income or uninsured individuals either through a discount card or direct shipment.

. "Person" means an individual, a corporation, a governmental entity, a partnership, an association, a joint venture, a joint stock company, a trust, an unincorporated organization, any similar entity, or any combination of the persons listed in this subsection.

. [Empty]
.. "Pharmacy benefit manager" means a person that performs pharmacy benefit management for a covered entity.

.. For purposes of this subsection, a "covered entity" means an insurer, a health care service contractor, a health maintenance organization, or a multiple employer welfare arrangement licensed, certified, or registered under the provisions of this title. "Covered entity" also means a health program administered by the state as a provider of health coverage, a single employer that provides health coverage to its employees, or a labor union that provides health coverage to its members as part of a collective bargaining agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5717.SL.pdf?cite=2015%20c%20122%20§%2019[2015 c 122 § 19]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2585-S.SL.pdf?cite=2010%20c%2027%20§%204[2010 c 27 § 4]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5480-S.SL.pdf?cite=2009%20c%20175%20§%203[2009 c 175 § 3]; ]

== 48.155.015 - Application of chapter.
. This chapter applies to all discount plans and all discount plan organizations doing business in or from this state or that affect subjects located wholly or in part or to be performed within this state, and all persons having to do with this business.

. A discount plan organization that is a health carrier, as defined under RCW 48.43.005, with a license, certificate of authority, or registration:

.. Is not required to obtain a license under RCW 48.155.020, except that any of its affiliates that operate as a discount plan organization in this state must obtain a license under RCW 48.155.020 and comply with all other provisions of this chapter;

.. Is required to comply with RCW 48.155.060 through 48.155.090 and report, in the form and manner as the commissioner may require, any of the information described in RCW 48.155.110(2) (b), (c), or (d) that is not otherwise already reported; and

.. Is subject to RCW 48.155.130 and 48.155.140.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5717.SL.pdf?cite=2015%20c%20122%20§%2020[2015 c 122 § 20]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5480-S.SL.pdf?cite=2009%20c%20175%20§%204[2009 c 175 § 4]; ]

== 48.155.020 - License required—Application—Review—Annual renewal—Required disclosures.
. Before conducting discount plan business to which this chapter applies, a person must obtain a license from the commissioner to operate as a discount plan organization.

. Except as provided in subsection (4) of this section, each application for a license to operate as a discount plan organization:

.. Must be in a form prescribed by the commissioner and verified by an officer or authorized representative of the applicant; and

.. Must demonstrate, set forth, or be accompanied by the following:

... The two hundred fifty dollar application fee, which must be deposited into the general fund;

... A copy of the organization documents of the applicant, such as the articles of incorporation, including all amendments;

... A copy of the applicant's bylaws or other enabling documents that establish organizational structure;

... The applicant's federal identification number, business address, and mailing address;

..(A) A list of names, addresses, official positions, and biographical information of the individuals who are responsible for conducting the applicant's affairs, including all members of the board of directors, board of trustees, executive committee, or other governing board or committee, the officers, contracted management company personnel, and any person or entity owning or having the right to acquire ten percent or more of the voting securities of the applicant; and

(B) A disclosure in the listing of the extent and nature of any contracts or arrangements between any individual who is responsible for conducting the applicant's affairs and the discount plan organization, including all possible conflicts of interest;

.. A complete biographical statement, on forms prescribed by the commissioner, with respect to each individual identified under (b)(v) of this subsection;

.. A statement generally describing the applicant, its facilities and personnel, and the health care services for which a discount will be made available under the discount plan;

.. A copy of the form of all contracts made or to be made between the applicant and any health care providers or health care provider networks regarding the provision of health care services to members and discounts to be made available to members;

... A copy of the form of any contract made or arrangement to be made between the applicant and any individual listed in (b)(v) of this subsection;

.. A list identifying by name, address, telephone number, and email address all persons who will market each discount plan offered by the applicant. If the person who will market a discount plan is an entity, only the entity must be identified. This list must be maintained and updated within sixty days of any change in the information. An updated list must be sent to the commissioner as part of the discount plan organization's renewal application under (b)(vii) of this subsection;

.. A copy of the form of any contract made or to be made between the applicant and any person, corporation, partnership, or other entity for the performance on the applicant's behalf of any function, including marketing, administration, enrollment, and subcontracting for the provision of health care services to members and discounts to be made available to members;

.. A copy of the applicant's most recent financial statements audited by an independent certified public accountant, except that, subject to the approval of the commissioner, an applicant that is an affiliate of a parent entity that is publicly traded and that prepares audited financial statements reflecting the consolidated operations of the parent entity may submit the audited financial statement of the parent entity and a written guaranty that the minimum capital requirements required under RCW 48.155.030 will be met by the parent entity instead of the audited financial statement of the applicant;

.. A description of the proposed methods of marketing including, but not limited to, describing the use of marketers, use of the internet, sales by telephone, electronic mail, or facsimile machine, and use of salespersons to market the discount plan benefits;

.. A description of the member complaint procedures which must be established and maintained by the applicant;

.. If domiciled in this state, the name and address of the applicant's Washington statutory agent for service of process, notice, or demand; and

.. Any other information the commissioner may reasonably require.

. [Empty]
.. If the applicant is not domiciled in this state, the applicant must appoint the commissioner as the discount plan organization's attorney to receive service of legal process issued against the discount plan organization in this state upon causes of action arising within this state. Service upon the commissioner as attorney constitutes effective legal service upon the discount plan organization.

.. With the appointment the discount plan organization must designate by name, email address, and address the person to whom the commissioner must forward legal process so served upon him or her. The discount plan organization may change the person by filing a new designation.

.. The discount plan organization must keep the designation, address, and email address filed with the commissioner current.

.. The appointment is irrevocable, binds any successor in interest or to the assets or liabilities of the discount plan organization, and remains in effect for as long as there could be any cause of action against the discount plan organization arising out of the discount plan organization's transactions in this state.

.. The service of process must be accomplished and processed in the manner prescribed under RCW 48.02.200.

. [Empty]
.. Upon application to and approval by the commissioner and payment of the applicable fees, a discount plan organization that holds a current license or other form of authority from another state to operate as a discount plan organization, at the commissioner's discretion, may not be required to submit the information required under subsection (2) of this section in order to obtain a license under this section if the commissioner is satisfied that the other state's requirements, at a minimum, are equivalent to those required under subsection (2) of this section or the commissioner is satisfied that the other state's requirements are sufficient to protect the interests of the residents of this state.

.. Whenever the discount plan organization loses its license or other form of authority in that other state to operate as a discount plan organization, or is the subject of any disciplinary administrative proceeding related to the organization's operating as a discount plan organization in that other state, the discount plan organization must immediately notify the commissioner.

. After the receipt of an application filed under subsection (2) or (4) of this section, the commissioner must review the application and notify the applicant of any deficiencies in the application.

. [Empty]
.. Within ninety days after the date of receipt of a completed application, the commissioner must:

... Issue a license if the commissioner is satisfied that the applicant has met the following:

(A) The applicant has fulfilled the requirements of this section and the minimum capital requirements in accordance with RCW 48.155.030; and

(B) The persons who own, control, and manage the applicant are competent and trustworthy and possess managerial experience that would make the proposed operation of the discount plan organization beneficial to discount plan members; or

... Disapprove the application and state the grounds for disapproval.

.. In making a determination under (a) of this subsection, the commissioner may consider, for example, whether the applicant or an officer or manager of the applicant: (i) Is not financially responsible; (ii) does not have adequate expertise or experience to operate a medical discount plan organization; or (iii) is not of good character. Among the factors that the commissioner may consider in making the determination is whether the applicant or an affiliate or a business formerly owned or managed by the applicant or an officer or manager of the applicant has had a previous application for a license, or other authority, to operate as any entity regulated by the commissioner denied, revoked, suspended, or terminated for cause, or is under investigation for or has been found in violation of a statute or regulation in another jurisdiction within the previous five years.

. Prior to licensure by the commissioner, each discount plan organization must establish an internet website in order to conform to the requirements of RCW 48.155.070(2).

. [Empty]
.. A license is effective for up to one year, unless prior to its expiration the license is renewed in accordance with this subsection or suspended or revoked in accordance with subsection (9) of this section. Licenses issued or renewed on or after July 1, 2010, will be subject to renewal annually on July 1st. If not so renewed, the license will automatically expire on the renewal date.

.. At least ninety days before a license expires, the discount plan organization must submit:

... A renewal application form; and

... A two hundred dollar renewal application fee for deposit into the general fund.

.. The commissioner must renew the license of each holder that meets the requirements of this chapter and pays the appropriate renewal fee required.

. [Empty]
.. The commissioner may suspend the authority of a discount plan organization to enroll new members or refuse to renew or revoke a discount plan organization's license if the commissioner finds that any of the following conditions exist:

... The discount plan organization is not operating in compliance with this chapter;

... The discount plan organization does not have the minimum net worth as required under RCW 48.155.030;

... The discount plan organization has advertised, merchandised, or attempted to merchandise its services in such a manner as to misrepresent its services or capacity for service or has engaged in deceptive, misleading, or unfair practices with respect to advertising or merchandising;

... The discount plan organization is not fulfilling its obligations as a discount plan organization; or

.. The continued operation of the discount plan organization would be hazardous to its members.

.. If the commissioner has cause to believe that grounds for the nonrenewal, suspension, or revocation of a license exists, the commissioner must notify the discount plan organization in writing specifically stating the grounds for the refusal to renew or suspension or revocation and may also pursue a hearing on the matter under chapter 48.04 RCW.

.. When the license of a discount plan organization is nonrenewed, surrendered, or revoked, the discount plan organization must immediately upon the effective date of the order of revocation or, in the case of a nonrenewal, the date of expiration of the license, stop any further advertising, solicitation, collecting of fees, or renewal of contracts, and proceed to wind up its affairs transacted under the license.

.. [Empty]
... When the commissioner suspends a discount plan organization's authority to enroll new members, the suspension order must specify the period during which the suspension is to be in effect and the conditions, if any, that must be met by the discount plan organization prior to reinstatement of its license to enroll members.

... The commissioner may rescind or modify the order of suspension prior to the expiration of the suspension period.

... The license of a discount plan organization may not be reinstated unless requested by the discount plan organization. The commissioner may not grant the request for reinstatement if the commissioner finds that the circumstances for which the suspension occurred still exist or are likely to recur.

. Each licensed discount plan organization must notify the commissioner immediately whenever the discount plan organization's license, or other form of authority to operate as a discount plan organization in another state, is suspended, revoked, or nonrenewed in that state.

. A health care provider who provides discounts to his or her own patients without any cost or fee of any kind to the patient is not required to obtain and maintain a license under this chapter as a discount plan organization.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5213.SL.pdf?cite=2011%20c%2047%20§%2018[2011 c 47 § 18]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2585-S.SL.pdf?cite=2010%20c%2027%20§%206[2010 c 27 § 6]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5480-S.SL.pdf?cite=2009%20c%20175%20§%205[2009 c 175 § 5]; ]

== 48.155.030 - Minimum net worth.
. Except under subsection (3) of this section, before the commissioner issues a license to any person required to obtain a license under RCW 48.155.020, the person seeking to operate a discount plan organization must have a net worth of at least one hundred fifty thousand dollars.

. At all times, except under subsection (3) of this section, each discount plan organization must maintain a net worth of at least one hundred fifty thousand dollars.

. By rule of the commissioner, the amounts in subsections (1) and (2) of this section may be adjusted annually for inflation.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5480-S.SL.pdf?cite=2009%20c%20175%20§%206[2009 c 175 § 6]; ]

== 48.155.040 - Surety bond—Deposit in lieu of bond.
. Each licensed discount plan organization shall continuously maintain in force a surety bond in its own name in an amount not less than thirty-five thousand dollars to be used in the discretion of the commissioner to protect the financial interest of Washington members. The bond must be issued by an insurance company licensed to do business in this state.

. In lieu of the bond specified in subsection (1) of this section, a licensed discount plan organization may deposit and maintain deposited with the commissioner, or at the discretion of the commissioner, with any organization or trustee acceptable to the commissioner through which a custodial or controlled account is utilized, cash, securities, or any combination of these or other measures that are acceptable to the commissioner which always have a market value of not less than thirty-five thousand dollars.

. All income from a deposit made under subsection (2) of this section is an asset of the discount plan organization.

. Except for the commissioner, the assets or securities held in this state as a deposit under subsection (1) or (2) of this section are not subject to levy by a judgment creditor or other claimant of the discount plan organization.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5480-S.SL.pdf?cite=2009%20c%20175%20§%207[2009 c 175 § 7]; ]

== 48.155.050 - Investigations by commissioner—Organization must maintain detailed books and records.
. The commissioner may conduct investigations to determine whether any person has violated any provision of this chapter and may, if the commissioner has a reason to believe that the discount plan organization is not complying with the requirements of this chapter, examine the business and affairs of any discount plan organization.

. An examination conducted under subsection (1) of this section must be performed in accordance with chapter 48.03 RCW, except that RCW 48.03.060 (1) and (2) shall not be applicable to the examination of persons registered under this chapter.

. The commissioner may:

.. Order any discount plan organization or applicant that operates a discount plan organization to produce any records, books, files, advertising, and solicitation materials or other information; and

.. Gather evidence and take statements under oath to determine whether the discount plan organization or applicant is in violation of the law or is acting contrary to the public interest.

. The discount plan organization or applicant that is the subject of the examination or investigation shall pay the expenses incurred in conducting the examination or investigation. Failure by the discount plan organization or applicant to pay the expenses is grounds for denial or revocation of a license to operate as a discount plan organization.

. All discount plan organizations or applicants that are subject to examinations, investigations, or annual reporting requirements under this chapter shall maintain detailed books and records of the following:

.. Records documenting all Washington transactions, showing all funds received and all funds disbursed to Washington members, prospective members, providers, and provider networks;

.. All contracts or agreements with providers of the services under a discount plan offered in Washington or sold to Washington residents; and

.. Telephone scripts for marketing activities to which this chapter applies.

The discount plan organization shall maintain the books and records described in this section, in addition to the books and records required to be maintained under RCW 48.155.070, for a period of at least two years.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5480-S.SL.pdf?cite=2009%20c%20175%20§%208[2009 c 175 § 8]; ]

== 48.155.060 - Charges and fees—When writing is required—Cancellation.
. A discount plan organization may charge a periodic charge as well as a reasonable one-time processing fee of no more than thirty dollars for a discount plan, or such other amount as established by rule, but may not require payment of these or any other charges or fees by direct debit from a banking, credit, or debit card account unless that method of payment is clearly and conspicuously disclosed to the prospective member. All charges and fees must be provided in writing to the member when the member first joins the plan.

. When a marketer or discount plan organization solicits a discount plan in conjunction with any other product, all charges that a member or prospective member must pay for each discount plan must be provided in writing as a separate item to the member or prospective member, unless the entire amount of the periodic charge which includes the periodic discount plan charge will be refunded if the member cancels his or her membership in the discount plan organization within the first thirty days after the date of receipt of the written documents for the discount plan as provided in subsection (3) of this section.

. [Empty]
.. [Empty]
... If a member cancels his or her membership in the discount plan organization within the first thirty days after the date of receipt of the written documents for the discount plan described in RCW 48.155.090(4), the member must receive a reimbursement of all periodic charges upon return of the discount plan card to the discount plan organization.

...(A) Cancellation occurs when notice of cancellation is given to the discount plan organization.

(B) Notice of cancellation is given when delivered by hand or deposited in a mailbox, properly addressed and postage prepaid to the mailing address of the discount plan organization, or emailed to the email address of the discount plan organization.

... A discount plan organization shall return in full any periodic charge charged or collected after the member has given the discount plan organization notice of cancellation.

.. If the discount plan organization cancels a membership for any reason other than nonpayment of charges by the member, the discount plan organization shall make a pro rata reimbursement of all periodic charges to the member.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5480-S.SL.pdf?cite=2009%20c%20175%20§%209[2009 c 175 § 9]; ]

== 48.155.070 - Written health care provider agreements required—Terms—Internet website.
. [Empty]
.. A discount plan organization shall have a written health care provider agreement with all health care providers for whose health care services it provides access to a discount to its members. The written health care provider agreement may be entered into directly with the health care provider or indirectly with a health care provider network to which the health care provider belongs.

.. A health care provider agreement between a discount plan organization and a health care provider must provide the following:

... A list of the health care services and products to be provided at a discount;

... The amount or amounts of the discounts or, alternatively, a fee schedule that reflects the health care provider's discounted rates; and

... That the health care provider may not charge members more than the discounted rates.

.. A health care provider agreement between a discount plan organization and a health care provider network must require that the health care provider network have written agreements with its health care providers that:

... Contain the provisions described in (b) of this subsection;

... Authorize the health care provider network to contract with the discount plan organization on behalf of the health care provider; and

... Require the health care provider network to maintain an up-to-date list of its contracted health care providers and to provide the list on a monthly basis to the discount plan organization.

.. A health care provider agreement between a discount plan organization and an entity that contracts with a health care provider network must require that the entity, in its contract with the health care provider network, require the health care provider network to have written agreements with its health care providers that comply with (c) of this subsection.

.. The discount plan organization shall maintain a copy of each health care provider agreement into which it has entered and shall promptly furnish a copy of each agreement to the commissioner when requested.

. [Empty]
.. Each discount plan organization shall maintain on an internet website a list of the names and addresses of the health care providers with which it has a current provider agreement directly or through a health care provider network. This list must be updated every thirty days. The internet website address must be prominently displayed on all of its advertisements, marketing materials, brochures, and discount plan cards.

.. This subsection applies to those health care providers with which the discount plan organization has a current provider agreement directly as well as those health care providers that are members of a health care provider network with which the discount plan organization has a current provider agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5480-S.SL.pdf?cite=2009%20c%20175%20§%2010[2009 c 175 § 10]; ]

== 48.155.080 - Marketing products—Directly to consumers—By contract with marketers.
. A discount plan organization may market its products directly to consumers or contract with marketers for the distribution of its discount plans.

. [Empty]
.. The discount plan organization shall have an executed written agreement with a marketer prior to the marketer's marketing, promoting, selling, or distributing the discount plan organization's discount plans.

.. The agreement between the discount plan organization and the marketer must prohibit the marketer from using advertising, marketing materials, brochures, and discount plan cards without first having the discount plan organization's approval in writing.

.. The discount plan organization is bound by and responsible for the activities of a marketer that are within the scope of the marketer's agency relationship with the organization.

. A discount plan organization shall approve in writing all advertisements, marketing materials, brochures, and discount cards used by marketers to market, promote, sell, or distribute the discount plan prior to their use.

. Upon request, a discount plan organization shall submit to the commissioner all advertising, marketing materials, and brochures used or to be used in connection with the organization's discount plans.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5480-S.SL.pdf?cite=2009%20c%20175%20§%2011[2009 c 175 § 11]; ]

== 48.155.090 - Communications with regulators and consumers—Restrictions—Required general disclosures.
. [Empty]
.. All advertisements, marketing efforts, promotions, marketing materials, discount plan documents, brochures, discount plan cards, and any other communications of a discount plan organization provided to prospective members and members must be truthful and not misleading in fact or in implication.

.. Any advertisement, marketing material, discount plan document, brochure, discount plan card, or other communication is misleading in fact or in implication if it has a capacity or tendency to mislead or deceive based on the overall impression that it may reasonably be expected to create within the segment of the public to which it is directed.

.. A discount plan organization shall conduct its business in its own legal name and all written communications from a discount plan to regulators and consumers must prominently display the discount plan organization's full legal name.

. A discount plan organization shall not:

.. Except as otherwise provided in this chapter or as a disclaimer of any relationship between discount plan benefits and insurance, or as a description of an insurance product connected with a discount plan, use in its advertisements, marketing efforts, promotions, marketing materials, discount plan documents, brochures, and discount plan cards the term "insurance";

.. Describe or characterize the discount plan as being insurance whenever a discount plan is bundled with an insured product and the insurance benefits are incidental to the discount plan benefits;

.. Use in its advertisements, marketing efforts, promotions, marketing materials, discount plan documents, brochures, and discount plan cards words or phrases that are commonly associated with the business of insurance, such as the terms "health plan," "coverage," "copay," "copayments," "deductible," "preexisting conditions," "guaranteed issue," "premium," "PPO," "preferred provider organization," or similar terms, in a manner that could reasonably mislead an individual into believing that the discount plan is health insurance;

.. Use language in its advertisements, marketing efforts, promotions, marketing material, discount plan documents, brochures, and discount plan cards with respect to being licensed by the insurance commissioner's office in a manner that could reasonably mislead an individual into believing that the discount plan is insurance or has been endorsed by the insurance commissioner's office;

.. Make misleading, deceptive, or fraudulent representations regarding the discount or range of discounts offered by the discount plan or the access to any range of discounts offered by the discount plan;

.. Have restrictions on access to discount plan providers including, except for hospital services, waiting periods and notification periods; or

.. Pay health care providers any fees for health care services or collect or accept money from a member to pay a health care provider for health care services provided under the discount plan, unless the discount plan organization has an active certificate of authority or registration in Washington.

. [Empty]
.. Each discount plan organization shall make the following general disclosures in not less than twelve-point type on the first content page of any advertisements, marketing materials, or brochures made available to the public relating to a discount plan, along with any enrollment forms given to a prospective member:

... That the plan is a discount plan and is not insurance coverage;

... If true, that the range of discounts for health care services provided under the plan will vary depending on the type of health care provider and health care service received;

... That the discount plan organization does not make payments to providers for the health care services received under the discount plan, unless the discount plan organization has an active certificate of authority or registration, as described in subsection (2)(g) of this section;

... That the plan member is obligated to pay for all health care services, but will receive the stated discount from those health care providers that have a current provider agreement with the discount plan organization; and

.. The toll-free telephone number and internet website address for the licensed discount plan organization for prospective members and members to obtain additional information about and assistance with the discount plan and up-to-date lists of health care providers participating in the discount plan.

.. If the initial contact with a prospective member is by telephone, the disclosures required under (a) of this subsection must be made orally and included in the initial written materials that describe the benefits under the discount plan provided to the prospective or new member.

. [Empty]
.. In addition to the general disclosures required under subsection (3) of this section, each discount plan organization shall send to:

... Each prospective member, at their request, information that describes the terms and conditions of the discount plan, including any limitations or restrictions on the refund of any processing fees or periodic charges associated with the discount plan. The written materials presented must not be dependent upon the requestor first making any form of payment or enrolling in the plan; and

... Each new member, within fourteen calendar days of enrollment, written documents that contain all terms and conditions of the discount plan.

.. The written documents required under (a)(ii) of this subsection must be clear and include the following information:

... The name of the member;

... The benefits to be provided under the discount plan;

... Any processing fees and periodic charges associated with the discount plan, including any limitations or restrictions on the refund of any processing fees and periodic charges;

... The mode of payment of any processing fees and periodic charges, such as monthly or quarterly, and procedures for changing the mode of payment;

.. Any limitations, exclusions, or exceptions regarding the receipt of discount plan benefits;

.. Any waiting periods for receiving discounts on hospital services under the discount plan;

.. Procedures for obtaining discounts under the discount plan, such as requiring members to contact the discount plan organization to make an appointment with a health care provider on the member's behalf;

.. Cancellation procedures, including information on the member's thirty-day cancellation rights and refund requirements and procedures for obtaining refunds;

... Renewal, termination, and cancellation terms and conditions; 

.. Procedures for adding new members to a family discount plan, if applicable;

.. Procedures for filing complaints under the discount plan organization's complaint system and information that, if the member remains dissatisfied after completing the organization's complaint system, the plan member may contact the office of the insurance commissioner; and

.. The name, telephone number, internet website address, and mailing address of the licensed discount plan organization or other entity where the member can make inquiries about the plan, or send cancellation notices and file complaints.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5480-S.SL.pdf?cite=2009%20c%20175%20§%2012[2009 c 175 § 12]; ]

== 48.155.100 - Organization changes require notice to commissioner.
Each discount plan organization shall provide the commissioner at least thirty days' advance notice of any change in the discount plan organization's name, address, principal business address, mailing address, toll-free telephone number, or internet website address.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5480-S.SL.pdf?cite=2009%20c%20175%20§%2013[2009 c 175 § 13]; ]

== 48.155.110 - Annual report required—Fee—Contents—Failure to file.
. If the information required in subsection (2) of this section is not provided at the time of renewal of a license under RCW 48.155.020, a discount plan organization shall file an annual report with the commissioner in the form prescribed by the commissioner no later than March 31st of the following year.

. The annual report must be filed with the commissioner, accompanied by the twenty dollar annual reporting fee to be deposited into the general fund. The annual report must include:

.. Audited financial statements prepared in accordance with generally accepted accounting principles certified by an independent certified public accountant, including the organization's balance sheet, income statement, and statement of changes in cash flow for the preceding year. However, subject to the approval of the commissioner, an organization that is an affiliate of a parent entity that is publicly traded and that prepares audited financial statements reflecting the consolidated operations of the parent entity may submit the audited financial statement of the parent entity and a written guaranty that the minimum capital requirements required under RCW 48.155.030 will be met by the parent entity instead of the audited financial statement of the organization;

.. If different from the initial application for a license, or at the time of renewal of a license, or the last annual report, as appropriate, a list of the names and residence addresses of all persons responsible for the conduct of the organization's affairs, together with a disclosure of the extent and nature of any contracts or arrangements with these persons and the discount plan organization, including any possible conflicts of interest;

.. The number of current members the discount plan organization has in the state; and

.. Any other information relating to the performance of the discount plan organization that may be required by the commissioner.

. Any discount plan organization that fails to file an annual report in the form and within the time required by this section is subject to the following:

.. Monetary penalties of:

... Up to five hundred dollars each day for the first ten days during which the violation continues; and

... Up to one thousand dollars each day after the first ten days during which the violation continues; and

.. Upon notice by the commissioner, loss, suspension, or revocation of its license and authority to enroll new members or to do business in this state while the violation continues.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5480-S.SL.pdf?cite=2009%20c%20175%20§%2014[2009 c 175 § 14]; ]

== 48.155.120 - Designation of compliance officer.
Each discount plan organization shall designate and provide the commissioner with the name, address, and telephone number of the organization's compliance officer responsible for ensuring compliance with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5480-S.SL.pdf?cite=2009%20c%20175%20§%2015[2009 c 175 § 15]; ]

== 48.155.130 - Violation of chapter—Commissioner's authority—Penalties—Criminal sanctions—Civil action for recovery of damages.
. In lieu of or in addition to suspending or revoking a discount plan organization's license under *RCW 48.155.020(8), whenever the commissioner has cause to believe that any person is violating or is about to violate any provision of this chapter or any rules adopted under this chapter or any order of the commissioner, the commissioner may:

.. Issue a cease and desist order; and

.. After hearing or with the consent of the discount plan organization and in addition to or in lieu of the suspension, revocation, or refusal to renew any license, impose a monetary penalty of not less than one hundred dollars for each violation and not more than ten thousand dollars for each violation.

. A person that willfully operates as or aids and abets another operating as a discount plan organization in violation of RCW 48.155.020(1) commits insurance fraud and is subject to RCW 48.15.020 and 48.15.023, as if the unlicensed discount plan organization were an unauthorized insurer, and the fees, dues, charges, or other consideration collected from the members by the unlicensed discount plan organization or marketer were insurance premiums.

. A person that collects fees for purported membership in a discount plan but willfully fails to provide the promised benefits commits a theft and upon conviction is subject to the provisions of Title 9A RCW. In addition, upon conviction, the person shall pay restitution to persons aggrieved by the violation of this chapter.

. Any person damaged by acts that violate this chapter may maintain an action for the recovery of damages caused by that act or acts.

.. An action for violation of this section may be brought:

... In the county where the plaintiff resides;

... In the county where the plaintiff conducts business; or

... In the county where the discount plan was sold, marketed, promoted, advertised, or otherwise distributed.

.. The acceptance or use of any discount plan or discount plan card does not operate as a waiver of any civil, criminal, or administrative claim that may be asserted under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5480-S.SL.pdf?cite=2009%20c%20175%20§%2016[2009 c 175 § 16]; ]

== 48.155.140 - Temporary and permanent injunctive relief—When authorized.
. [Empty]
.. In addition to the penalties and other enforcement provisions of this chapter, the commissioner may seek both temporary and permanent injunctive relief when:

... A discount plan is being operated by a person or entity that is not licensed under this chapter; or

... Any person, entity, or discount plan organization has engaged in any activity prohibited by this chapter or any rule adopted under this chapter.

.. The venue for any court proceeding brought under this section is Thurston county.

. The commissioner's authority to seek injunctive relief is not conditioned on having conducted any proceeding under chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5480-S.SL.pdf?cite=2009%20c%20175%20§%2017[2009 c 175 § 17]; ]

