= 48.175 - Personal vehicle sharing programs.
:toc:

== 48.175.005 - Definitions.
For the purposes of this chapter, unless the context otherwise requires:

. "Owner's insurance policy" means an automobile liability insurance policy, as defined in RCW 48.22.005, that includes:

.. All coverage necessary to comply with the requirements of chapter 46.30 RCW; and

.. Any optional coverage selected by the registered owner, including:

... Personal injury protection coverage as defined in RCW 48.22.005;

... Underinsured coverage as defined in RCW 48.22.030;

... Comprehensive property damage coverage for the vehicle; and

... Collision property damage coverage for the vehicle.

. "Personal vehicle sharing" means the operation and use of a private passenger motor vehicle, by persons other than the vehicle's registered owner in connection with a personal vehicle sharing program.

. "Personal vehicle sharing program" or "program" means a legal entity qualified to do business in this state engaged in the business of facilitating the sharing of private passenger motor vehicles for noncommercial use by individuals within this state. For the purposes of this subsection, "noncommercial use" means use other than that for a "commercial vehicle" as defined in RCW 46.04.140.

. "Private passenger motor vehicle" means a four-wheel passenger motor vehicle insured under an automobile liability insurance policy covering a single individual or individuals residing in the same household as the named insured.

. "Program insurance policy" means an automobile liability insurance policy that is obtained by the personal vehicle sharing program and that:

.. Includes all coverage needed to comply with the requirements of chapter 46.30 RCW;

.. Includes the following optional coverages:

... Comprehensive property damage coverage for the vehicle; and

... Collision property damage coverage for the vehicle;

.. Offers to the named insured on the program policy underinsured coverage as defined in RCW 48.22.030;

.. Offers to the named insured on the program policy *underinsured coverage as defined in RCW 48.22.005; and

.. Does not include any other optional coverage selected by the owner of the vehicle and included in the owner's insurance policy.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2384-S.SL.pdf?cite=2012%20c%20108%20§%201[2012 c 108 § 1]; ]

== 48.175.010 - Requirements of program.
For each vehicle that the program facilitates the use of, a program must:

. Provide a program insurance policy with coverage for the vehicle and all persons who, with the consent of the program, use the motor vehicle insured while in control of the vehicle in the program. The limits for any coverage included in the program insurance policy may not provide liability coverage that is less than three times the limits specified in chapter 46.30 RCW and may not provide collision or comprehensive coverage that is less than the actual cash value of the vehicle;

. Prior to the first use of a vehicle in a program, and upon renewal, cancellation, or change in insurance by the program, provide the vehicle's registered owner with a proof of compliance with the insurance requirements of this section and the requirements of chapter 46.30 RCW, underinsured motorist coverage elections made by the sharing program under RCW 48.22.030 and personal injury protection coverage elections made by the sharing program under RCW 48.22.085. A copy of the proof of compliance must be maintained in the vehicle by the vehicle's registered owner at all times when the vehicle is operated by any person other than the vehicle's registered owner pursuant to the program;

. Collect, maintain, and make available to the vehicle's registered owner, the vehicle's registered owner's primary automobile liability insurer, and any government agency as required by law, at the cost of the program, the following:

.. Verifiable records that identify the date and duration that the vehicle is under the control of a person other than the vehicle's registered owner pursuant to the program. For vehicles with an electronic tracking device, verifiable electronic records of the time, initial and final locations of the vehicle, and miles driven when the vehicle is under the control of a person other than the vehicle's registered owner pursuant to the program; and

.. In instances where an insurance claim has been filed, any and all information, including payments to the registered owner by the program, concerning accidents, damages, or injuries arising out of personal vehicle sharing pursuant to the program;

. Not knowingly permit the vehicle to be operated as a commercial vehicle by a personal vehicle sharing user while engaged in personal vehicle sharing. For the purposes of this subsection, "commercial vehicle" has the meaning given that term in RCW 46.04.140;

. Ensure that the vehicle is a private passenger motor vehicle;

. Facilitate the installation, operation, and maintenance of its own signage and computer hardware and software, if and when requested by the vehicle owner, necessary for the vehicle to be used in the program;

. Indemnify and hold harmless the vehicle's registered owner for the cost of damage or theft of equipment installed by the program under subsection (6) of this section and any damage caused to the vehicle by the installation, operation, or maintenance of the equipment;

. [Empty]
.. Prior to the first use of a vehicle in a program, and upon renewal, cancellation, or change in insurance by the program, provide the vehicle's registered owner and any person operating the vehicle pursuant to the program with a disclosure that contains:

... Information explaining the requirements of this section;

... Full and clear disclosure of the coverages and coverage limits provided under the program insurance policy;

... Notice that the vehicle owner's insurer has no duty to defend or indemnify any person or organization for liability for any loss that occurs during use of the vehicle pursuant to a program; and

... Notice that the vehicle owner or any person operating the vehicle pursuant to the program may have liability for claims that exceed the limits of the program insurance policy.

.. The information in (a) of this subsection must be made available to the vehicle owner's insurer upon the insurer's request.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2384-S.SL.pdf?cite=2012%20c%20108%20§%202[2012 c 108 § 2]; ]

== 48.175.020 - Program's liabilities—Owner's insurance policy.
. Notwithstanding any provision in the owner's insurance policy and notwithstanding chapter 46.29 RCW, in the event of any loss or injury that occurs at any time when the vehicle is under the operation or control of a person, other than the vehicle's registered owner, pursuant to a program, or is otherwise under the control of a program, the program shall assume all liability of the vehicle owner and shall be considered the vehicle owner for all purposes.

. Nothing in subsection (1) of this section:

.. Limits the liability of a program for any acts or omissions by the program that result in injury to any persons as a result of the use or operation of the program; or

.. Limits the ability of the program to, by contract, seek indemnification from the vehicle's registered owner for any claims paid by the program for any loss or injury resulting from fraud or material intentional misrepresentation by the vehicle's registered owner, provided that the vehicle sharing program disclose in the contract that:

... The program is entitled to seek indemnification in these circumstances; and

... The registered owner's insurance policy does not provide defense or indemnification for any loss or injury resulting from fraud or material intentional misrepresentation.

. A program continues to be liable under subsection (1) of this section until:

.. The vehicle is returned to a location designated by the program, as set forth in the contract between the registered owner and the program; and

.. [Empty]
... The expiration of the time period established for the vehicle occurs;

... The intent to terminate the vehicle's personal vehicle sharing use is verifiably communicated to the program, as set forth in the contract between the registered owner and the program; or

... The vehicle's registered owner takes possession and control of the vehicle.

. [Empty]
.. A program shall assume liability, including the costs of defense and indemnification, for a claim in which a dispute exists as to who was in control of a private passenger motor vehicle when the loss giving rise to the claim occurred.

.. The insurer of the vehicle shall indemnify the program to the extent of the insurer's obligation under the owner's insurance policy, if it is determined that the vehicle's registered owner was in control of the vehicle at the time of the loss.

. If a private passenger motor vehicle's registered owner is named as a defendant in a civil action for any loss or injury that occurs at any time when the vehicle is under the operation or control of a person, other than the vehicle's registered owner, pursuant to a program, or is otherwise under the control of a program, the program shall have the duty to defend and indemnify the vehicle's registered owner.

. [Empty]
.. Notwithstanding any provision in the owner's insurance policy, while the vehicle is under the operation or control of a person, other than the vehicle's registered owner, pursuant to a program, or is otherwise under the control of a program:

... The insurer providing coverage to the owner of a private passenger motor vehicle may exclude any and all coverage afforded under the owner's insurance policy; and

... A primary or excess insurer of the vehicle owner may notify an insured that the insurer has no duty to defend or indemnify any person or organization for liability for any loss that occurs during use of the vehicle pursuant to a program;

.. In order to exclude such coverage, the exclusion allowed in (a)(i) of this subsection and the notification required in (a)(ii) of this subsection are not required for a policy that otherwise does not provide such coverages.

. An owner's insurance policy for a private passenger motor vehicle may not be canceled, voided, terminated, rescinded, or nonrenewed solely on the basis that the vehicle has been made available for personal vehicle sharing pursuant to a program that is in compliance with the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2384-S.SL.pdf?cite=2012%20c%20108%20§%203[2012 c 108 § 3]; ]

== 48.175.030 - Private passenger motor vehicle not a commercial or for-hire motor vehicle—Criteria.
A private passenger motor vehicle insured by the vehicle's registered owner under an owner's insurance policy may not be classified as a commercial motor vehicle or for-hire motor vehicle solely because the vehicle's registered owner allows the vehicle to be used for personal vehicle sharing if:

. The personal vehicle sharing is conducted under a program;

. The annual revenue received by the vehicle's registered owner that was generated by the personal vehicle sharing does not exceed the annual expenses of owning and operating the vehicle, including depreciation, interest, lease payments, motor vehicle loan payments, insurance, maintenance, parking, fuel, cleaning, automobile repair and costs associated with personal vehicle sharing, including but not limited to the installation, operation, and maintenance of computer hardware and software, signage identifying the vehicle as a personal vehicle sharing vehicle, and any fees charged by a program.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2384-S.SL.pdf?cite=2012%20c%20108%20§%204[2012 c 108 § 4]; ]

== 48.175.900 - Application—2012 c 108.
This act applies to automobile liability insurance policies issued or renewed on or after January 1, 2013.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2384-S.SL.pdf?cite=2012%20c%20108%20§%206[2012 c 108 § 6]; ]

