= 48.170 - Self-service storage insurance producers.
:toc:

== 48.170.005 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Commissioner" means the insurance commissioner of this state.

. "Occupant" means a person, or his or her sublessee, successor, or assign, who is entitled to the use of the storage space at a self-service storage facility under a rental agreement, to the exclusion of others.

. "Owner" means the owner, operator, property management company, lessor, or sublessor of a self-service storage facility. "Owner" does not mean an occupant.

. "Personal property" means movable property not affixed to land, and includes, but is not limited to, goods, merchandise, furniture, and household items.

. "Self-service storage facility" or "facility" means any real property designed and used for the purpose of renting or leasing individual storage space to occupants who are to have access to the space for the purpose of storing and removing personal property on a self-service basis, but does not include a garage or other storage area in a private residence.

. "Self-service storage insurance" is insurance that in connection with and incidental to the rental of space at a facility provides coverage to occupants at the facility for the loss of or damage to stored personal property that occurs at that facility.

. "Self-service storage insurance producer" means any owner of a facility that is licensed as a specialty lines insurance producer under chapter 48.17 RCW to offer, sell, or solicit self-service storage insurance under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2013-S.SL.pdf?cite=2009%20c%20119%20§%201[2009 c 119 § 1]; ]

== 48.170.007 - Rules.
The commissioner may adopt rules necessary to implement and administer this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2013-S.SL.pdf?cite=2009%20c%20119%20§%209[2009 c 119 § 9]; ]

== 48.170.010 - License required.
. An owner; or officer, director, or employee of an owner; may not offer, sell, or solicit the purchase of self-service storage insurance unless that person is:

.. Licensed as an insurance producer with a property line of authority under chapter 48.17 RCW; or

.. Licensed as a self-service storage insurance producer under chapter 48.17 RCW and is in compliance with this chapter.

. If the owner is licensed as a self-service storage insurance producer under chapter 48.17 RCW and is in compliance with this chapter, then an employee of the owner who is in compliance with RCW 48.170.070(1) is not required to be individually licensed.

. The commissioner may issue a specialty line insurance producer license to an owner that is in compliance with this chapter authorizing the owner to act as a self-service storage insurance producer under this chapter, in connection with and incidental to rental agreements, on behalf of any insurer authorized to write self-service storage insurance in this state.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2013-S.SL.pdf?cite=2009%20c%20119%20§%202[2009 c 119 § 2]; ]

== 48.170.020 - Application for a license—Requirements.
An owner may apply to be licensed as a self-service storage insurance producer under, and if in compliance with, this chapter by filing the following documents with the commissioner:

. A written application for licensure, signed by the applicant or by an officer of the applicant, in the form prescribed by the commissioner that includes a listing of all locations at which the owner intends to offer, sell, or solicit self-service storage insurance; and

. [Empty]
.. A certificate by the insurer that is to be named in self-service storage insurance producer license, stating that the insurer:

... Has satisfied itself that the named applicant is trustworthy and competent to act as its self-service storage insurance producer, limited to this purpose;

... Has reviewed the employee training and education program required by RCW 48.170.070(1)(c) and that it satisfies the statutory requirements; and

... Will appoint the applicant to act as its self-service storage insurance producer to offer, sell, or solicit self-service storage insurance, if the license for which the applicant is applying is issued by the commissioner.

.. The certification shall be subscribed by an authorized representative of the insurer on a form prescribed by the commissioner.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2013-S.SL.pdf?cite=2009%20c%20119%20§%203[2009 c 119 § 3]; ]

== 48.170.030 - Licensee exempt from continuing education requirements.
An owner issued a self-service storage insurance producer license under this chapter is not subject to the prelicensure or continuing education requirements in chapter 48.17 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2013-S.SL.pdf?cite=2009%20c%20119%20§%204[2009 c 119 § 4]; ]

== 48.170.040 - Authority conveyed by license.
. A self-service storage insurance producer license authorizes a self-service storage insurance producer and its employees to offer and sell to, enroll in, and bill and collect premiums from occupants for insurance covering the loss of or damage to personal property stored at a facility on a master, corporate, group, or individual policy basis.

. A self-service storage insurance producer is not required to treat moneys collected from occupants purchasing insurance under this chapter as funds received in a fiduciary capacity, if:

.. The insurer represented by the self-service storage insurance producer has consented in writing, signed by an officer of the insurer, that the premiums need not be segregated from funds received by the self-service storage insurance producer; and

.. The charges for insurance coverage are itemized and ancillary to the rental agreement.

. An owner is not required to be licensed pursuant to this section merely to display and make available to prospective occupants brochures and other promotional materials created by or on behalf of an authorized insurer, provided that either the owner or its employees, or both, are not paid a commission or other consideration.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2013-S.SL.pdf?cite=2009%20c%20119%20§%205[2009 c 119 § 5]; ]

== 48.170.050 - Preconditions to soliciting insurance.
A self-service storage insurance producer may not solicit insurance under RCW 48.170.010 unless:

. At every location where occupants are enrolled in self-service storage insurance programs, written disclosure material regarding the program is made available to prospective occupants; and

. All employees who offer and sell to, enroll in, and bill and collect premiums from occupants for insurance have completed a training program for employees of the licensed self-service storage insurance producer as approved by the commissioner.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2013-S.SL.pdf?cite=2009%20c%20119%20§%206[2009 c 119 § 6]; ]

== 48.170.060 - Required written disclosure material—Contents.
The written disclosure material required in RCW 48.170.050(1) must:

. Summarize the material terms of insurance coverage offered to occupants, including the name, address, telephone number of the insurer, price, benefits, exclusions, and conditions;

. Prominently and conspicuously disclose that the policies offered by the self-service storage insurance producer may provide a duplication of coverage already provided by an occupant's homeowner's insurance policy, renter's insurance policy, vehicle insurance policy, watercraft insurance policy, or other source of property insurance coverage;

. State that if self-service storage insurance is required as a condition of rental, the requirement may be satisfied by the occupant purchasing the insurance being offered to the occupant by the owner or by presenting evidence of other applicable insurance coverage;

. Describe the process for filing a claim;

. State in writing all costs related to the insurance; and

. Disclose any other information required by rule by the commissioner.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2013-S.SL.pdf?cite=2009%20c%20119%20§%207[2009 c 119 § 7]; ]

== 48.170.070 - Employee acting under authority of license—Conditions—Limitations.
. An employee of a self-service storage insurance producer may be authorized to offer, sell, or solicit self-service storage insurance under the authority of the self-service storage insurance producer's license, if all of the following conditions have been satisfied:

.. The employee is eighteen years of age or older;

.. The employee is a trustworthy person and has not committed any act set forth in RCW 48.17.530;

.. The employee has completed a training and education program;

.. The self-service storage insurance producer, at the time it submits its self-service storage insurance producer license application, also submits a list of the names of all employees to its self-service storage insurance producer license on forms prescribed by the commissioner. The list shall be submitted to the commissioner annually and kept current by reporting all changes, deletions, or additions within thirty days after the change, deletion, or addition occurred. Each list shall be retained by the self-service storage insurance producer for a period of three years from submission; and

.. The self-service storage insurance producer submits to the commissioner with its initial self-service storage insurance producer license application, and annually thereafter, a certification subscribed by an officer of the self-service storage insurance producer on a form prescribed by the commissioner, stating all of the following:

... No person other than an employee offers, sells, or solicits self-service storage insurance on its behalf or while working as an employee of the self-service storage insurance producer; and

... All employees have completed the training and education program under subsection (4) of this section.

. A self-service storage insurance producer's employee may only act on behalf of the self-service storage insurance producer in the offer, sale, or solicitation of self-service storage insurance. A self-service storage insurance producer is responsible for, and must supervise, all actions of its employees related to the offering, sale, or solicitation of self-service storage insurance. The conduct of an employee is the same as the conduct of the self-service storage insurance producer for purposes of this chapter.

. The manager at each location of a self-service storage insurance producer, or the direct supervisor of the self-service storage insurance producer's employees at each location, must be an employee of that self-service storage insurance producer and is responsible for the supervision of each additional employee at that location. Each self-service storage insurance producer shall identify the employee who is the manager or direct supervisor at each location in the employee list that it submits under subsection (1)(d) of this section.

. Each self-service storage insurance producer shall provide a training and education program for each employee prior to allowing an employee to offer, sell, or solicit self-service storage insurance. Details of the program must be submitted to the commissioner, along with the license application, for approval prior to use, and resubmitted for approval of any changes prior to use. This training program shall meet the following minimum standards:

.. Each employee shall receive instruction about the insurance authorized under this chapter that may be offered for sale to prospective occupants; and

.. Each employee shall receive training about the requirements and limitations imposed on self-service storage insurance producer and employees under this chapter. The training must include specific instruction that the employee is prohibited by law from making any statement or engaging in any conduct express or implied, that would lead a consumer to believe that the:

... Occupant does not have insurance policies in place that already provide the coverage being offered by the self-service storage producer under this chapter; or

... Employee is qualified to evaluate the adequacy of the occupant's existing insurance coverages.

. The training and education program submitted to the commissioner is approved if no action is taken within thirty days of its submission.

. An employee's authorization to offer, sell, or solicit self-service storage insurance expires when the employee's employment with the self-service storage insurance producer is terminated.

. The self-service storage insurance producer shall retain for a period of one year from the date of each transaction records which enable it to identify the name of the employee involved in each rental transaction when an occupant purchases self-service storage insurance.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2013-S.SL.pdf?cite=2009%20c%20119%20§%208[2009 c 119 § 8]; ]

== 48.170.900 - Effective date—2009 c 119.
This act takes effect July 1, 2010.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2013-S.SL.pdf?cite=2009%20c%20119%20§%2013[2009 c 119 § 13]; ]

