= 48.120 - Specialty producer licenses—Portable electronics or services.
:toc:

== 48.120.005 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Appointing insurer" means the insurer appointing the vendor as its agent under a specialty producer license.

. "Customer" means a person that enters into a portable electronics transaction with a vendor.

. "Federal securities law" means the securities act of 1933, the securities exchange act of 1934, and the investment company act of 1940.

. "Location" means any physical locale in this state and any website, call center site, or similar site directed to residents of this state.

. "Portable electronics" means personal, self-contained, easily carried by an individual, battery-operated electronic communication, viewing, listening, recording, gaming, computing or global positioning devices and other similar devices and their accessories, and service related to the use of such devices.

. "Portable electronics insurance program" means an insurance program as described in RCW 48.120.015.

. "Portable electronics transaction" means the sale or lease of portable electronics or the sale of a service related to the use of portable electronics by a vendor to a customer.

. "Specialty producer license" means a license issued under RCW 48.120.010 that authorizes a vendor to offer or sell insurance as provided in RCW 48.120.015.

. "Supervising person" means a licensed insurer or an appointed insurance producer licensed under RCW 48.17.090 who provides training as described in RCW 48.120.020 and is appointed by an insurer to supervise the administration of a portable electronics insurance program.

. "Vendor" means a person in the business of, directly or indirectly, engaging in portable electronics transactions.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6242-S.SL.pdf?cite=2012%20c%20154%20§%201[2012 c 154 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6591.SL.pdf?cite=2008%20c%20217%20§%2094[2008 c 217 § 94]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2224-S.SL.pdf?cite=2002%20c%20357%20§%201[2002 c 357 § 1]; ]

== 48.120.010 - License required—Application.
. A vendor that intends to offer insurance under RCW 48.120.015 must file a specialty producer license application with the commissioner. Before the commissioner issues such a license, the vendor must be appointed as the insurance producer of one or more authorized appointing insurers under a vendor's specialty producer license.

. Upon receipt of an application, if the commissioner is satisfied that the application is complete, the commissioner may issue a specialty producer license to the vendor.

. An application for licensure pursuant to this section must conform to the requirements of chapter 48.17 RCW. However, information with respect to an applicant's officers, directors, and shareholders of record having beneficial ownership of ten percent or more of any class of securities registered under federal securities law may only be required if the vendor derives more than fifty percent of its revenue from the sale of portable electronics insurance.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6242-S.SL.pdf?cite=2012%20c%20154%20§%202[2012 c 154 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6591.SL.pdf?cite=2008%20c%20217%20§%2095[2008 c 217 § 95]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2224-S.SL.pdf?cite=2002%20c%20357%20§%202[2002 c 357 § 2]; ]

== 48.120.015 - Scope of license—Authorization—Portable electronics.
. A specialty producer license authorizes a vendor and its employees and authorized representatives to offer and sell to, enroll in, and bill and collect premiums from customers for insurance covering portable electronics on a master, corporate, group commercial inland marine policy, or on an individual policy basis on a month-to-month or other periodic basis at each location at which the vendor engages in portable electronics transactions. However:

.. The supervising person must maintain a list of a vendor's locations that are authorized to sell or solicit portable electronics insurance coverage; and

.. The list under (a) of this subsection must be provided to the commissioner within ten days of a request by the commissioner.

. An employee or authorized representative of a vendor may sell or offer portable electronics insurance to the vendor's customers without being individually licensed as an insurance producer if the vendor is licensed under this chapter and is acting in compliance with this chapter and any rules adopted by the commissioner.

. A vendor billing and collecting premiums from customers for portable electronics insurance coverage is not required to maintain these funds in a segregated account if the vendor:

.. Is authorized by the insurer to hold the funds in an alternative manner; and

.. Remits the funds to the supervising person within sixty days of receipt.

. All funds received by a vendor from an enrolled customer for the sale of portable electronics insurance are considered funds held in trust by the vendor in a fiduciary capacity for the benefit of the insurer.

. Any charge to the enrolled customer for coverage that is not included in the cost associated with the purchase or lease of portable electronics or related services must be separately itemized on the enrolled customer's bill.

. If portable electronics insurance coverage is included with the purchase or lease of portable electronics or related services, the vendor must clearly and conspicuously disclose to the enrolled customer that the portable electronics insurance coverage is included with the portable electronics or related services.

. Vendors may receive compensation for billing and collection services.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5008-S.SL.pdf?cite=2013%20c%20152%20§%204[2013 c 152 § 4]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6242-S.SL.pdf?cite=2012%20c%20154%20§%203[2012 c 154 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2224-S.SL.pdf?cite=2002%20c%20357%20§%203[2002 c 357 § 3]; ]

== 48.120.020 - Issuance of insurance—Restrictions—Portable electronics—Conduct of employees and authorized representatives.
. A vendor issued a specialty producer license may not issue insurance under RCW 48.120.015 unless:

.. At every location where customers are enrolled in portable electronics insurance programs, written material regarding the program is made available to prospective customers that:

... Discloses that portable electronics insurance may provide a duplication of coverage already provided by a customer's homeowner's insurance policy, renter's insurance policy, or other source of coverage;

... States that the enrollment by the customer in a portable electronics insurance program is not required in order to purchase or lease portable electronics or services;

... Summarizes the material terms of the insurance coverage, including the identity of the insurer, the identity of the supervising person, the amount of any applicable deductible and how it is to be paid, benefits of the coverage, and key terms and conditions of coverage, such as whether portable electronics may be replaced with a similar make and model or reconditioned make and model or repaired with nonoriginal manufacturer parts or equipment;

... Summarizes the process for filing a claim, including a description of how to return portable electronics and the maximum fee applicable in the event the customer fails to comply with any equipment return requirements;

.. States that an enrolled customer may cancel enrollment for coverage under a portable electronics insurance policy at any time and the person paying the premium will receive a refund or credit of any applicable unearned premium; and

.. Discloses with specificity under what circumstances and subject to what limitations an insurer may cancel, terminate, modify, or otherwise change the terms and conditions of a policy of portable electronics insurance; and

.. The portable electronics insurance program is operated with the participation of a supervising person who, with authorization and approval from the appointing insurer, supervises a training program for employees of the licensed vendor. The training must comply with the following:

... The training must be delivered to employees and authorized representatives of vendors who are directly engaged in the activity of selling or offering portable electronics insurance;

... The training may be provided in electronic form. However, if conducted in an electronic form, the supervising person must implement a supplemental education program regarding the portable electronics insurance product that is conducted and overseen by licensed employees of the supervising person; and

... Each employee and authorized representative must receive basic instruction about the portable electronics insurance offered to customers and the disclosures required under this section.

. No employee or authorized representative of a vendor of portable electronics may advertise, represent, or otherwise hold himself or herself out as a nonlimited lines licensed insurance producer.

. Employees and authorized representatives of a vendor issued a specialty producer license may only act on behalf of the vendor in the offer, sale, solicitation, or enrollment of customers in a portable electronics insurance program. The conduct of these employees and authorized representatives within the scope of their employment or agency is the same as conduct of the vendor for purposes of this title.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5008-S.SL.pdf?cite=2013%20c%20152%20§%206[2013 c 152 § 6]; 2013 c 152 § 5; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6242-S.SL.pdf?cite=2012%20c%20154%20§%204[2012 c 154 § 4]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2224-S.SL.pdf?cite=2002%20c%20357%20§%204[2002 c 357 § 4]; ]

== 48.120.025 - Statutes governing vendor misconduct—Rules necessary to implement chapter.
. A vendor issued a specialty producer license under this chapter is subject to RCW 48.17.530 through 48.17.560.

. The commissioner may adopt rules necessary for the implementation of this chapter , including, but not limited to, rules governing:

.. The specialty producer license application process, including any forms required to be used;

.. The standards for approval and the required content of written materials required under RCW 48.120.020(1)(a);

.. The approval and required content of training materials required under RCW 48.120.020(1)(c);

.. Establishing license fees to defray the cost of administering the specialty producer licensure program;

.. Establishing requirements for the remittance of premium funds to the supervising agent under authority from the program insurer; and

.. Determining the applicability or nonapplicability of other provisions of this title to this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5008-S.SL.pdf?cite=2013%20c%20152%20§%207[2013 c 152 § 7]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2224-S.SL.pdf?cite=2002%20c%20357%20§%205[2002 c 357 § 5]; ]

