= 48.165 - Uniform administrative procedures—Health care services.
:toc:

== 48.165.005 - Findings—Intent.
The legislature finds that:

. The health care system in the nation and in Washington state costs nearly twice as much per capita as other industrialized nations.

. The fragmentation and variation in administrative processes prevalent in our health care system contribute to the high cost of health care, putting it increasingly beyond the reach of small businesses and individuals in Washington.

. In 2006, the legislature's blue ribbon commission on health care costs and access requested the office of the insurance commissioner to conduct a study of administrative costs and recommendations to reduce those costs. Findings in the report included:

.. In Washington state approximately thirty cents of every dollar received by hospitals and doctors' offices is consumed by the administrative expenses of public and private payors and the providers;

.. Before the doctors and hospitals receive the funds for delivering the care, approximately fourteen percent of the insurance premium has already been consumed by payor administration. The payor's portion of expense totals approximately four hundred fifty dollars per insurance member per year in Washington state;

.. Over thirteen percent of every dollar received by a physician's office is devoted to interactions between the provider and payor;

.. Between 1997 and 2005, billing and insurance related costs for hospitals in Washington grew at an average pace of nineteen percent per year; and

.. The greatest opportunity for improved efficiency and administrative cost reduction in our health care system would involve standardizing and streamlining activities between providers and payors.

. To address these inefficiencies, constrain health care inflation, and make health care more affordable for Washingtonians, the legislature seeks to establish streamlined and uniform procedures for payors and providers of health care services in the state. It is the intent of the legislature to foster a continuous quality improvement cycle to simplify health care administration. This process should involve leadership in the health care industry and health care purchasers, with regulatory oversight from the office of the insurance commissioner.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5346-S2.SL.pdf?cite=2009%20c%20298%20§%201[2009 c 298 § 1]; ]

== 48.165.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Commissioner" means the insurance commissioner as established under chapter 48.02 RCW.

. "Health care provider" or "provider" has the same meaning as in RCW 48.43.005 and, for the purposes of chapter 298, Laws of 2009, shall include facilities licensed under chapter 70.41 RCW.

. "Lead organization" means a private sector organization or organizations designated by the commissioner to lead development of processes, guidelines, and standards to streamline health care administration and to be adopted by payors and providers of health care services operating in the state.

. "Medical management" means administrative activities established by the payor to manage the utilization of services through preservice or postservice reviews. "Medical management" includes, but is not limited to:

.. Prior authorization or preauthorization of services;

.. Precertification of services;

.. Postservice review;

.. Medical necessity review; and

.. Benefits advisory.

. "Payor" means public purchasers, as defined in this section, carriers licensed under chapters 48.20, 48.21, 48.44, 48.46, and 48.62 RCW, and the Washington state health insurance pool established in chapter 48.41 RCW.

. "Public purchaser" means the department of social and health services, the department of labor and industries, and the health care authority.

. "Secretary" means the secretary of the department of health.

. "Third-party payor" has the same meaning as in RCW 70.02.010.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5346-S2.SL.pdf?cite=2009%20c%20298%20§%202[2009 c 298 § 2]; ]

== 48.165.030 - Designation of lead organizations—Coordination responsibility—Qualifications—Lead organization's duties—Commissioner's duties.
. The commissioner shall designate one or more lead organizations to coordinate development of processes, guidelines, and standards to streamline health care administration and to be adopted by payors and providers of health care services operating in the state. The lead organization designated by the commissioner for chapter 298, Laws of 2009 shall:

.. Be representative of providers and payors across the state;

.. Have expertise and knowledge in the major disciplines related to health care administration; and

.. Be able to support the costs of its work without recourse to public funding.

. The lead organization shall:

.. In collaboration with the commissioner, identify and convene work groups, as needed, to define the processes, guidelines, and standards required in RCW 48.165.035, 18.122.165, and 48.165.040 through 48.165.050;

.. In collaboration with the commissioner, promote the participation of representatives of health care providers, payors of health care services, and others whose expertise would contribute to streamlining health care administration;

.. Conduct outreach and communication efforts to maximize adoption of the guidelines, standards, and processes developed by the lead organization;

.. Submit regular updates to the commissioner on the progress implementing the requirements of chapter 298, Laws of 2009; and

.. With the commissioner, report to the legislature annually through December 1, 2012, on progress made, the time necessary for completing tasks, and identification of future tasks that should be prioritized for the next improvement cycle.

. The commissioner shall:

.. Participate in and review the work and progress of the lead organization, including the establishment and operation of work groups for chapter 298, Laws of 2009;

.. Adopt into rule, or submit as proposed legislation, the guidelines, standards, and processes set forth in chapter 298, Laws of 2009 if:

... The lead organization fails to timely develop or implement the guidelines, standards, and processes set forth in RCW 48.165.035, 18.122.165, and 48.165.040 through 48.165.050; or

... It is unlikely that there will be widespread adoption of the guidelines, standards, and processes developed under chapter 298, Laws of 2009;

.. Consult with the office of the attorney general to determine whether an antitrust safe harbor is necessary to enable licensed carriers and providers to develop common rules and standards; and, if necessary, take steps, such as implementing rules or requesting legislation, to establish such safe harbor; and

.. Convene an executive level work group with broad payor and provider representation to advise the commissioner regarding the goals and progress of implementation of the requirements of chapter 298, Laws of 2009.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5346-S2.SL.pdf?cite=2009%20c%20298%20§%205[2009 c 298 § 5]; ]

== 48.165.0301 - Prior authorization requirements—Lead organization and work group to develop recommendations—Rules.
. The insurance commissioner must reauthorize the efforts with the lead organization established in RCW 48.165.030, and establish a new work group to develop recommendations for prior authorization requirements. The focus of the prior authorization efforts must include the full scope of health care services including pharmacy issues. The work group must submit recommendations to the commissioner by October 31, 2014.

. The lead organization and work group established to review prior authorization requirements must consider the following areas in their efforts:

.. Requiring carriers and pharmacy benefit managers to provide a listing of prior authorization requirements electronically on a website. The listing of requirements for any procedure, supply, or service requiring preauthorization must include criteria needed by the carrier specific to that medical or procedural code, to allow a provider's office to submit all information needed on the initial request for prior authorization, along with instructions for submitting that information;

.. Requiring a carrier or pharmacy benefit manager to issue an acknowledgment of receipt or reference number for prior authorization within a specified time frame, such as two business days of receipt of a prior authorization request from a provider;

.. Recommendations for the best practices for exchanging information, including alternatives to fax requests;

.. Recommendations for the best practices if the acknowledgment has not been received by the provider or pharmacy benefit manager within the specified time frame, such as two business days;

.. Recommendations if the carrier or pharmacy benefit manager fails to approve, deny, or respond to the request for authorization within the specified time frame and options for deeming approval;

.. Recommendations to refine the time frames in current rule; and

.. Recommendations specific to pharmacy services, including communication between the pharmacy to the carrier or pharmacy benefit manager, communications between the carrier or pharmacy benefit manager with the provider's office, communication of the authorization number, posting of the criteria for pharmacy related prior authorization on a website and other recommended alternatives; and options for prior authorizations involving urgent and emergent care with short-term prescription fill, such as a three-day supply, while the authorization is obtained.

. In preparing the recommendations, the work group must consider the opportunities to align with national mandates and regulatory guidance in the health insurance portability and accountability act and the patient protection and affordable care act, and use information technologies and electronic health records to increase efficiencies in health care and reengineer and automate age-old practices to improve business functions and ensure timely access to care for patients. 

. The commissioner shall adopt rules implementing the recommendations of the work group. The rules adopted under this subsection may only implement, and may not expand or limit, the recommendations of the work group.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6511-S.SL.pdf?cite=2014%20c%20141%20§%201[2014 c 141 § 1]; ]

== 48.165.035 - Lead organization tasks—Uniform electronic process.
By December 31, 2010, the lead organization shall:

. Develop a uniform electronic process for collecting and transmitting the necessary provider-supplied data to support credentialing, admitting privileges, and other related processes that:

.. Reduces the administrative burden on providers;

.. Improves the quality and timeliness of information for hospitals and payors;

.. Is interoperable with other relevant systems;

.. Enables use of the data by authorized participants for other related applications; and

.. Serves as the sole source of credentialing information required by hospitals and payors from providers for data elements included in the electronic process, except this shall not prohibit:

... A hospital, payor, or other credentialing entity subject to the requirements of this section from seeking clarification of information obtained through use of the uniform electronic process, if such clarification is reasonably necessary to complete the credentialing process; or

... A hospital, payor, other credentialing entity, or a university from using information not provided by the uniform process for the purpose of credentialing, admitting privileges, or faculty appointment of providers, including peer review and coordinated quality improvement information, that is obtained from sources other than the provider;

. Promote widespread adoption of such process by payors and hospitals, their delegates, and subcontractors in the state that credential health professionals and by such health professionals as soon as possible thereafter; and

. Work with the secretary to assure that data used in the uniform electronic process can be electronically exchanged with the department of health professional licensing process under chapter 18.122 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5346-S2.SL.pdf?cite=2009%20c%20298%20§%206[2009 c 298 § 6]; ]

== 48.165.040 - Lead organization tasks—Uniform standard companion document and data set.
The lead organization shall:

. Establish a uniform standard companion document and data set for electronic eligibility and coverage verification. Such a companion guide will:

.. Be based on nationally accepted ANSI X12 270/271 standards for eligibility inquiry and response and, wherever possible, be consistent with the standards adopted by nationally recognized organizations, such as the centers for medicare and medicaid services;

.. Enable providers and payors to exchange eligibility requests and responses on a system-to-system basis or using a payor supported web browser;

.. Provide reasonably detailed information on a consumer's eligibility for health care coverage, scope of benefits, limitations and exclusions provided under that coverage, cost-sharing requirements for specific services at the specific time of the inquiry, current deductible amounts, accumulated or limited benefits, out-of-pocket maximums, any maximum policy amounts, and other information required for the provider to collect the patient's portion of the bill; and

.. Reflect the necessary limitations imposed on payors by the originator of the eligibility and benefits information;

. Recommend a standard or common process to the commissioner to protect providers and hospitals from the costs of, and payors from claims for, services to patients who are ineligible for insurance coverage in circumstances where a payor provides eligibility verification based on best information available to the payor at the date of the request; and

. Complete, disseminate, and promote widespread adoption by payors of such document and data set by December 31, 2010.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5346-S2.SL.pdf?cite=2009%20c%20298%20§%208[2009 c 298 § 8]; ]

== 48.165.045 - Lead organization tasks—Implementation guidelines—Code development and standardization—Denial review process.
. By December 31, 2010, the lead organization shall develop implementation guidelines and promote widespread adoption of such guidelines for:

.. The use of the national correct coding initiative code edit policy by payors and providers in the state;

.. Publishing any variations from component codes, mutually exclusive codes, and status b codes by payors in a manner that makes for simple retrieval and implementation by providers;

.. Use of health insurance portability and accountability act standard group codes, reason codes, and remark codes by payors in electronic remittances sent to providers;

.. The processing of corrections to claims by providers and payors; and

.. A standard payor denial review process for providers when they request a reconsideration of a denial of a claim that results from differences in clinical edits where no single, common standards body or process exists and multiple conflicting sources are in use by payors and providers.

. By October 31, 2010, the lead organization shall develop a proposed set of goals and work plan for additional code standardization efforts for 2011 and 2012.

. Nothing in this section or in the guidelines developed by the lead organization shall inhibit an individual payor's ability to employ, and not disclose to providers, temporary code edits for the purpose of detecting and deterring fraudulent billing activities. Though such temporary code edits are not required to be disclosed to providers, the guidelines shall require that:

.. Each payor disclose to the provider its adjudication decision on a claim that was denied or adjusted based on the application of such an edit; and

.. The provider have access to the payor's review and appeal process to challenge the payor's adjudication decision, provided that nothing in this subsection (3)(b) shall be construed to modify the rights or obligations of payors or providers with respect to procedures relating to the investigation, reporting, appeal, or prosecution under applicable law of potentially fraudulent billing activities.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5346-S2.SL.pdf?cite=2009%20c%20298%20§%209[2009 c 298 § 9]; ]

== 48.165.050 - Lead organization tasks—Develop and promote uniform practices—Medical management protocols.
. By December 31, 2010, the lead organization shall:

.. Develop and promote widespread adoption by payors and providers of guidelines to:

... Ensure payors do not automatically deny claims for services when extenuating circumstances make it impossible for the provider to: (A) Obtain a preauthorization before services are performed; or (B) notify a payor within twenty-four hours of a patient's admission; and

... Require payors to use common and consistent time frames when responding to provider requests for medical management approvals. Whenever possible, such time frames shall be consistent with those established by leading national organizations and be based upon the acuity of the patient's need for care or treatment;

.. Develop, maintain, and promote widespread adoption of a single common website where providers can obtain payors' preauthorization, benefits advisory, and preadmission requirements;

.. Establish guidelines for payors to develop and maintain a website that providers can employ to:

... Request a preauthorization, including a prospective clinical necessity review;

... Receive an authorization number; and

... Transmit an admission notification.

. By October 31, 2010, the lead organization shall propose to the commissioner a set of goals and work plan for the development of medical management protocols, including whether to develop evidence-based medical management practices addressing specific clinical conditions and make its recommendation to the commissioner, who shall report the lead organization's findings and recommendations to the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5346-S2.SL.pdf?cite=2009%20c%20298%20§%2010[2009 c 298 § 10]; ]

