= 43.99X - Financing for appropriations—2011-2013 biennium.
:toc:

== 43.99X.010 - General obligation bonds for capital and operating appropriations acts.
For the purpose of providing funds to finance the projects described and authorized by the legislature in the capital and operating appropriations acts for the 2009-2011 and 2011-2013 fiscal bienniums, and all costs incidental thereto, the state finance committee is authorized to issue general obligation bonds of the state of Washington in the sum of one billion one hundred twenty-two million dollars, or as much thereof as may be required, to finance these projects and all costs incidental thereto. Bonds authorized in this section may be sold at such price as the state finance committee shall determine. No bonds authorized in this section may be offered for sale without prior legislative appropriation of the net proceeds of the sale of the bonds.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2020-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2049%20§%207001[2011 1st sp.s. c 49 § 7001]; ]

== 43.99X.020 - Conditions and limitations.
. The proceeds from the sale of the bonds authorized in RCW 43.99X.010 shall be deposited in the state building construction account created by RCW 43.83.020. The proceeds shall be transferred as follows:

.. One billion seven million dollars to remain in the state building construction account created by RCW 43.83.020;

.. Twenty million two hundred thousand dollars to the outdoor recreation account created by RCW 79A.25.060;

.. Twenty million two hundred thousand dollars to the habitat conservation account created by RCW 79A.15.020;

.. Eight hundred thousand dollars to the riparian protection account created by RCW 79A.15.120;

.. Eight hundred thousand dollars to the farmlands preservation account created by *RCW 79A.15.130;

.. Fifty-one million dollars to the state taxable building construction account. All receipts from taxable bond issues are to be deposited into the account. If the state finance committee deems it necessary or advantageous to issue more than the amount specified in this subsection (1)(f) as taxable bonds in order to comply with federal internal revenue service rules and regulations pertaining to the use of nontaxable bond proceeds or in order to reduce the total financing costs for bonds issued, the proceeds of such additional taxable bonds shall be transferred to the state taxable building construction account in lieu of any transfer otherwise provided by this section. If the state finance committee determines that a portion of the amount specified in this subsection (1)(f) as taxable bonds may be issued as nontaxable bonds in compliance with federal internal revenue service rules and regulations pertaining to the use of nontaxable bond proceeds, then such bond proceeds shall be transferred to the state building construction account in lieu of the transfer to the state taxable building construction account otherwise provided by this subsection (1)(f). The state treasurer shall submit written notice to the director of financial management if it is determined that any such additional transfer to the state taxable building construction account is necessary or that a transfer from the state taxable building construction account to the state building construction account may be made. Moneys in the account may be spent only after appropriation.

. These proceeds shall be used exclusively for the purposes specified in this section and for the payment of expenses incurred in the issuance and sale of the bonds issued for the purposes of this section, and shall be administered by the office of financial management subject to legislative appropriation.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2020-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2049%20§%207002[2011 1st sp.s. c 49 § 7002]; ]

== 43.99X.030 - Retirement of bonds—Reimbursement of general fund from debt-limit general fund bond retirement account.
. The debt-limit general fund bond retirement account shall be used for the payment of the principal of and interest on the bonds authorized in RCW 43.99X.020(1) (a) through (f).

. The state finance committee shall, on or before June 30th of each year, certify to the state treasurer the amount needed in the ensuing twelve months to meet the bond retirement and interest requirements on the bonds authorized in RCW 43.99X.020(1) (a) through (f).

. On each date on which any interest or principal and interest payment is due on bonds issued for the purposes of RCW 43.99X.020(1) (a) through (f), the state treasurer shall withdraw from any general state revenues received in the state treasury and deposit in the debt-limit general fund bond retirement account an amount equal to the amount certified by the state finance committee to be due on the payment date.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2020-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2049%20§%207003[2011 1st sp.s. c 49 § 7003]; ]

== 43.99X.040 - Pledge and promise—Remedies.
. Bonds issued under RCW 43.99X.010 through 43.99X.030 shall state that they are a general obligation of the state of Washington, shall pledge the full faith and credit of the state to the payment of the principal thereof and the interest thereon, and shall contain an unconditional promise to pay the principal and interest as the same shall become due.

. The owner and holder of each of the bonds or the trustee for the owner and holder of any of the bonds may by mandamus or other appropriate proceeding require the transfer and payment of funds as directed in this section.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2020-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2049%20§%207004[2011 1st sp.s. c 49 § 7004]; ]

== 43.99X.050 - Payment of principal and interest—Additional means for raising money.
The legislature may provide additional means for raising moneys for the payment of the principal of and interest on the bonds authorized in RCW 43.99X.010, and RCW 43.99X.020 and 43.99X.030 shall not be deemed to provide an exclusive method for the payment.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2020-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2049%20§%207005[2011 1st sp.s. c 49 § 7005]; ]

== 43.99X.100 - Short title—2012 2nd sp.s. c 1.
This act shall be known as the 2012 jobs now act.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5127.SL.pdf?cite=2012%202nd%20sp.s.%20c%201%20§%20101[2012 2nd sp.s. c 1 § 101]; ]

== 43.99X.110 - General obligation bonds for capital and operating appropriations acts.
For the purpose of providing funds to finance the projects described and authorized by the legislature in the capital and operating appropriations acts for the 2011-2013 fiscal biennium, and all costs incidental thereto, the state finance committee is authorized to issue general obligation bonds of the state of Washington in the sum of five hundred five million four hundred sixty-six thousand dollars, or as much thereof as may be required, to finance these projects and all costs incidental thereto. Bonds authorized in this section may be sold at such price as the state finance committee shall determine. No bonds authorized in this section may be offered for sale without prior legislative appropriation of the net proceeds of the sale of the bonds.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5127.SL.pdf?cite=2012%202nd%20sp.s.%20c%201%20§%20201[2012 2nd sp.s. c 1 § 201]; ]

== 43.99X.120 - Conditions and limitations.
. The proceeds from the sale of the bonds authorized in RCW 43.99X.110 shall be deposited in the state building construction account created by RCW 43.83.020. The proceeds shall be transferred as follows:

.. Four hundred eighty million forty-five thousand dollars to remain in the state building construction account created by RCW 43.83.020;

.. Twenty million four hundred sixteen thousand dollars to the state taxable building construction account. All receipts from taxable bond issues are to be deposited into the account. If the state finance committee deems it necessary or advantageous to issue more than the amount specified in this subsection [(1)](b) as taxable bonds in order to comply with federal internal revenue service rules and regulations pertaining to the use of nontaxable bond proceeds or in order to reduce the total financing costs for bonds issued, the proceeds of such additional taxable bonds shall be transferred to the state taxable building construction account in lieu of any transfer otherwise provided by this section. If the state finance committee determines that a portion of the amount specified in this subsection [(1)](b) as taxable bonds may be issued as nontaxable bonds in compliance with federal internal revenue service rules and regulations pertaining to the use of nontaxable bond proceeds, then such bond proceeds shall be transferred to the state building construction account in lieu of the transfer to the state taxable building construction account otherwise provided by this subsection [(1)](b). The state treasurer shall submit written notice to the director of financial management if it is determined that any such additional transfer to the state taxable building construction account is necessary or that a transfer from the state taxable building construction account to the state building construction account may be made. Moneys in the account may be spent only after appropriation.

. These proceeds shall be used exclusively for the purposes specified in this section and for the payment of expenses incurred in the issuance and sale of the bonds issued for the purposes of this section, and shall be administered by the office of financial management subject to legislative appropriation.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5127.SL.pdf?cite=2012%202nd%20sp.s.%20c%201%20§%20202[2012 2nd sp.s. c 1 § 202]; ]

== 43.99X.130 - Retirement of bonds—Reimbursement of general fund from debt-limit general fund bond retirement account.
. The debt-limit general fund bond retirement account shall be used for the payment of the principal of and interest on the bonds authorized in RCW 43.99X.120(1).

. The state finance committee shall, on or before June 30th of each year, certify to the state treasurer the amount needed in the ensuing twelve months to meet the bond retirement and interest requirements on the bonds authorized in RCW 43.99X.120(1).

. On each date on which any interest or principal and interest payment is due on bonds issued for the purposes of RCW 43.99X.120(1), the state treasurer shall withdraw from any general state revenues received in the state treasury and deposit in the debt-limit general fund bond retirement account an amount equal to the amount certified by the state finance committee to be due on the payment date.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5127.SL.pdf?cite=2012%202nd%20sp.s.%20c%201%20§%20203[2012 2nd sp.s. c 1 § 203]; ]

== 43.99X.140 - Pledge and promise—Remedies.
. Bonds issued under RCW 43.99X.110 through 43.99X.130 shall state that they are a general obligation of the state of Washington, shall pledge the full faith and credit of the state to the payment of the principal thereof and the interest thereon, and shall contain an unconditional promise to pay the principal and interest as the same shall become due.

. The owner and holder of each of the bonds or the trustee for the owner and holder of any of the bonds may by mandamus or other appropriate proceeding require the transfer and payment of funds as directed in this section.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5127.SL.pdf?cite=2012%202nd%20sp.s.%20c%201%20§%20204[2012 2nd sp.s. c 1 § 204]; ]

== 43.99X.150 - Payment of principal and interest—Additional means for raising money authorized.
The legislature may provide additional means for raising moneys for the payment of the principal of and interest on the bonds authorized in RCW 43.99X.110, and RCW 43.99X.120 and 43.99X.130 shall not be deemed to provide an exclusive method for the payment.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5127.SL.pdf?cite=2012%202nd%20sp.s.%20c%201%20§%20205[2012 2nd sp.s. c 1 § 205]; ]

== 43.99X.160 - Effective date—2012 2nd sp.s. c 1.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and takes effect immediately [April 23, 2012].

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5127.SL.pdf?cite=2012%202nd%20sp.s.%20c%201%20§%20708[2012 2nd sp.s. c 1 § 708]; ]

