= 43.71C - Prescription drug costs.
:toc:

== 43.71C.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Authority" means the health care authority.

. "Covered drug" means any prescription drug that:

.. A covered manufacturer intends to introduce to the market at a wholesale acquisition cost of ten thousand dollars or more for a course of treatment lasting less than one month or a thirty-day supply, whichever period is longer; or

.. Is currently on the market, is manufactured by a covered manufacturer, and has a wholesale acquisition cost of more than one hundred dollars for a course of treatment lasting less than one month or a thirty-day supply, and, taking into account only price increases that take effect after July 28, 2019, the manufacturer increases the wholesale acquisition cost at least:

... Twenty percent, including the proposed increase and the cumulative increase over one calendar year prior to the date of the proposed increase; or

... Fifty percent, including the proposed increase and the cumulative increase over three calendar years prior to the date of the proposed increase.

. "Covered manufacturer" means a person, corporation, or other entity engaged in the manufacture of prescription drugs sold in or into Washington state. "Covered manufacturer" does not include a private label distributor or retail pharmacy that sells a drug under the retail pharmacy's store, or a prescription drug repackager.

. "Health care provider," "health plan," "health carrier," and "carrier" mean the same as in RCW 48.43.005.

. "Pharmacy benefit manager" means the same as in *RCW 19.340.010.

. "Pharmacy services administrative organization" means an entity that contracts with a pharmacy to act as the pharmacy's agent with respect to matters involving a pharmacy benefit manager, third-party payor, or other entities, including negotiating, executing, or administering contracts with the pharmacy benefit manager, third-party payor, or other entities and provides administrative services to pharmacies.

. "Prescription drug" means a drug regulated under chapter 69.41 or 69.50 RCW, including generic, brand name, specialty drugs, and biological products that are prescribed for outpatient use and distributed in a retail setting.

. "Qualifying price increase" means a price increase described in subsection (2)(b) of this section.

. "Wholesale acquisition cost" or "price" means, with respect to a prescription drug, the manufacturer's list price for the drug to wholesalers or direct purchasers in the United States, excluding any discounts, rebates, or reductions in price, for the most recent month for which the information is available, as reported in wholesale price guides or other publications of prescription drug pricing.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1224-S2.SL.pdf?cite=2019%20c%20334%20§%202[2019 c 334 § 2]; ]

== 43.71C.020 - Health carriers—Cost and utilization data reporting.
Beginning October 1, 2019, and on a yearly basis thereafter, a health carrier must submit to the authority the following prescription drug cost and utilization data for the previous calendar year for each health plan it offers in the state:

. The twenty-five prescription drugs most frequently prescribed by health care providers participating in the plan's network;

. The twenty-five costliest prescription drugs expressed as a percentage of total plan prescription drug spending, and the plan's total spending for each of these prescription drugs;

. The twenty-five drugs with the highest year-over-year increase in wholesale acquisition cost, excluding drugs made available for the first time that plan year, and the percentages of the increases for each of these prescription drugs;

. The portion of the premium that is attributable to each of the following categories of covered prescription drugs, after accounting for all rebates and discounts:

.. Brand name drugs;

.. Generic drugs; and

.. Specialty drugs;

. The year-over-year increase, calculated on a per member, per month basis and expressed as a percentage, in the total annual cost of each category of covered drugs listed in subsection (4) of this section, after accounting for all rebates and discounts;

. A comparison, calculated on a per member, per month basis, of the year-over-year increase in the cost of covered drugs to the year-over-year increase in the costs of other contributors to premiums, after accounting for all rebates and discounts;

. The name of each covered specialty drug; and

. The names of the twenty-five most frequently prescribed drugs for which the health plan received rebates from pharmaceutical manufacturers.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1224-S2.SL.pdf?cite=2019%20c%20334%20§%203[2019 c 334 § 3]; ]

== 43.71C.030 - Pharmacy benefit managers—Data reporting.
. By March 1st of each year, a pharmacy benefit manager must submit to the authority the following data from the previous calendar year:

.. All discounts, including the total dollar amount and percentage discount, and all rebates received from a manufacturer for each drug on the pharmacy benefit manager's formularies;

.. The total dollar amount of all discounts and rebates that are retained by the pharmacy benefit manager for each drug on the pharmacy benefit manager's formularies;

.. Actual total reimbursement amounts for each drug the pharmacy benefit manager pays retail pharmacies after all direct and indirect administrative and other fees that have been retrospectively charged to the pharmacies are applied;

.. The negotiated price health plans pay the pharmacy benefit manager for each drug on the pharmacy benefit manager's formularies;

.. The amount, terms, and conditions relating to copayments, reimbursement options, and other payments or fees associated with a prescription drug benefit plan;

.. Disclosure of any ownership interest the pharmacy benefit manager has in a pharmacy or health plan with which it conducts business; and

.. The results of any appeal filed pursuant to *RCW 19.340.100(3).

. The information collected pursuant to this section is not subject to public disclosure under chapter 42.56 RCW.

. The authority may examine or audit the financial records of a pharmacy benefit manager for purposes of ensuring the information submitted under this section is accurate. Information the authority acquires in an examination of financial records pursuant to this subsection is proprietary and confidential.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1224-S2.SL.pdf?cite=2019%20c%20334%20§%204[2019 c 334 § 4]; ]

== 43.71C.040 - Pharmacy benefit managers—Compliance.
. No later than March 1st of each calendar year, each pharmacy benefit manager must file with the authority, in the form and detail as required by the authority, a report for the preceding calendar year stating that the pharmacy benefit manager is in compliance with this chapter.

. A pharmacy benefit manager may not cause or knowingly permit the use of any advertisement, promotion, solicitation, representation, proposal, or offer that is untrue, deceptive, or misleading.

. An employer-sponsored self-funded health plan or a Taft-Hartley trust health plan may voluntarily provide the data described in subsection (1) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1224-S2.SL.pdf?cite=2019%20c%20334%20§%205[2019 c 334 § 5]; ]

== 43.71C.050 - Manufacturers—Data reporting.
. Beginning October 1, 2019, a covered manufacturer must submit to the authority the following data for each covered drug:

.. A description of the specific financial and nonfinancial factors used to make the decision to set or increase the wholesale acquisition cost of the drug. In the event of a price increase, a covered manufacturer must also submit the amount of the increase and an explanation of how these factors explain the increase in the wholesale acquisition cost of the drug;

.. The patent expiration date of the drug if it is under patent;

.. Whether the drug is a multiple source drug, an innovator multiple source drug, a noninnovator multiple source drug, or a single source drug;

.. The itemized cost for production and sales, including the annual manufacturing costs, annual marketing and advertising costs, total research and development costs, total costs of clinical trials and regulation, and total cost for acquisition of the drug; and

.. The total financial assistance given by the manufacturer through assistance programs, rebates, and coupons.

. For all qualifying price increases of existing drugs, a manufacturer must submit the year the drug was introduced to market and the wholesale acquisition cost of the drug at the time of introduction.

. If a manufacturer increases the price of an existing drug it has manufactured for the previous five years or more, it must submit a schedule of wholesale acquisition cost increases for the drug for the previous five years.

. If a manufacturer acquired the drug within the previous five years, it must submit:

.. The wholesale acquisition cost of the drug at the time of acquisition and in the calendar year prior to acquisition; and

.. The name of the company from which the drug was acquired, the date acquired, and the purchase price.

. Except as provided in subsection (6) of this section, a covered manufacturer must submit the information required by this section:

.. At least sixty days in advance of a qualifying price increase for a covered drug; and

.. Within thirty days of release of a new covered drug to the market.

. For any drug approved under section 505(j) of the federal food, drug, and cosmetic act, as it existed on July 28, 2019, or a biosimilar approved under section 351(k) of the federal public health service act, as it existed on July 28, 2019, if submitting data in accordance with subsection (5)(a) of this section is not possible sixty days before the price increase, that submission must be made as soon as known but not later than the date of the price increase.

. The information submitted pursuant to this section is not subject to public disclosure under chapter 42.56 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1224-S2.SL.pdf?cite=2019%20c%20334%20§%206[2019 c 334 § 6]; ]

== 43.71C.060 - Manufacturers—Notice of new drug applications.
. Beginning October 1, 2019, a manufacturer must submit written notice, in a form and manner specified by the authority, informing the authority that the manufacturer has filed with the FDA:

.. A new drug application or biologics license application for a pipeline drug; or

.. A biologics license application for a biological product.

. The notice must be filed within sixty days of the manufacturer receiving the applicable FDA approval date.

. Upon receipt of the notice, the authority may request from the manufacturer the following information if it believes the drug will have a significant impact on state expenditures:

.. The primary disease, condition, or therapeutic area studied in connection with the new drug, and whether the drug is therapeutically indicated for such disease, condition, or therapeutic area;

.. Each route of administration studied for the drug;

.. Clinical trial comparators for the drug;

.. The date at which the FDA must complete its review of the drug application pursuant to the federal prescription drug user fee act of 1992 (106 Stat. 4491; P.L. 102-571);

.. Whether the FDA has designated the drug an orphan drug, a fast track product, or a breakthrough therapy; and

.. Whether the FDA has designated the drug for accelerated approval, priority review, or if the drug contains a new molecular entity.

. A manufacturer may limit the information reported pursuant to this section to that which is otherwise in the public domain or publicly reported.

. The information collected pursuant to this section is not subject to public disclosure under chapter 42.56 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1224-S2.SL.pdf?cite=2019%20c%20334%20§%207[2019 c 334 § 7]; ]

== 43.71C.070 - Manufacturers—Notice of price increases.
. Beginning October 1, 2019, a manufacturer of a covered drug must notify the authority of a qualifying price increase in writing at least sixty days prior to the planned effective date of the increase. The notice must include:

.. The date of the increase, the current wholesale acquisition cost of the prescription drug, and the dollar amount of the future increase in the wholesale acquisition cost of the prescription drug; and

.. A statement regarding whether a change or improvement in the drug necessitates the price increase. If so, the manufacturer shall describe the change or improvement.

. For any drug approved under section 505(j) of the federal food, drug, and cosmetic act, as it existed on July 28, 2019, or a biosimilar approved under section 351(k) of the federal public health service act, as it existed on July 28, 2019, if notification is not possible sixty days before the price increase, that submission must be made as soon as known but not later than the date of the price increase.

. The information submitted pursuant to this section is not subject to public disclosure under chapter 42.56 RCW.

. By December 1, 2020, the authority must provide recommendations on how to provide advance notice of price increases to purchasers consistent with state and federal law.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1224-S2.SL.pdf?cite=2019%20c%20334%20§%208[2019 c 334 § 8]; ]

== 43.71C.080 - Pharmacy services administrative organizations—Data reporting.
. Beginning October 1, 2019, and on a yearly basis thereafter, a pharmacy services administrative organization representing a pharmacy or pharmacy chain in the state must submit to the authority the following data from the previous calendar year:

.. The negotiated reimbursement rate of the twenty-five prescription drugs with the highest reimbursement rate;

.. The twenty-five prescription drugs with the largest year-to-year change in reimbursement rate, expressed as a percentage and dollar amount; and

.. The schedule of fees charged to pharmacies for the services provided by the pharmacy services administrative organization.

. Any pharmacy services administrative organization whose revenue is generated from flat service fees not connected to drug prices or volume, and paid by the pharmacy, is exempt from reporting.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1224-S2.SL.pdf?cite=2019%20c%20334%20§%209[2019 c 334 § 9]; ]

== 43.71C.090 - Enforcement.
The authority may assess a fine of up to one thousand dollars per day for failure to comply with the requirements of RCW 43.71C.020 through 43.71C.080. The assessment of a fine under this section is subject to review under the administrative procedure act, chapter 34.05 RCW. Fines collected under this section must be deposited in the medicaid fraud penalty account created in RCW 74.09.215.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1224-S2.SL.pdf?cite=2019%20c%20334%20§%2011[2019 c 334 § 11]; ]

== 43.71C.100 - Annual report—Data confidentiality.
. The authority shall compile and analyze the data submitted by health carriers, pharmacy benefit managers, manufacturers, and pharmacy services administrative organizations pursuant to this chapter and prepare an annual report for the public and the legislature synthesizing the data to demonstrate the overall impact that drug costs, rebates, and other discounts have on health care premiums.

. The data in the report must be aggregated and must not reveal information specific to individual health carriers, pharmacy benefit managers, pharmacy services administrative organizations, individual prescription drugs, individual classes of prescription drugs, individual manufacturers, or discount amounts paid in connection with individual prescription drugs.

. Beginning January 1, 2021, and by each January 1st thereafter, the authority must publish the report on its web site.

. Except for the report, and as provided in subsection (5) of this section, the authority shall keep confidential all data submitted pursuant to RCW 43.71C.020 through 43.71C.080.

. For purposes of public policy, upon request of a legislator, the authority must provide all data provided pursuant to RCW 43.71C.020 through 43.71C.080 and any analysis prepared by the authority. Any information provided pursuant to this subsection must be kept confidential within the legislature and may not be publicly released.

. The data collected pursuant to this chapter is not subject to public disclosure under chapter 42.56 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1224-S2.SL.pdf?cite=2019%20c%20334%20§%2010[2019 c 334 § 10]; ]

== 43.71C.110 - Rule making.
The authority may adopt any rules necessary to implement the requirements of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1224-S2.SL.pdf?cite=2019%20c%20334%20§%2013[2019 c 334 § 13]; ]

== 43.71C.800 - Joint state strategies—Development and implementation recommendations.
The authority must contact the California office of statewide health planning and development and the Oregon department of consumer and business services to develop strategies to reduce prescription drug costs and increase prescription drug cost transparency. The authority must make recommendations to the legislature for implementing joint state strategies, which may include a joint purchasing agreement, by January 1, 2020.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1224-S2.SL.pdf?cite=2019%20c%20334%20§%2012[2019 c 334 § 12]; ]

== 43.71C.900 - Findings—2019 c 334.
The legislature finds that the state of Washington has substantial public interest in the following:

. The price and cost of prescription drugs. Washington state is a major purchaser through the department of corrections, the health care authority, and other entities acting on behalf of a state purchaser;

. Enacting this chapter to provide notice and disclosure of information relating to the cost and pricing of prescription drugs in order to provide accountability to the state for prescription drug pricing;

. Rising drug costs and consumer ability to access prescription drugs; and

. Containing prescription drug costs. It is essential to understand the drivers and impacts of these costs, as transparency is typically the first step toward cost containment and greater consumer access to needed prescription drugs.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1224-S2.SL.pdf?cite=2019%20c%20334%20§%201[2019 c 334 § 1]; ]

