= 43.19A - Recycled product procurement.
:toc:

== 43.19A.005 - Purpose.
It is the purpose of this chapter to:

. Substantially increase the procurement of recycled content products by all local and state governmental agencies and public schools, and provide a model to encourage a comparable commitment by Washington state citizens and businesses in their purchasing practices;

. Target government procurement policies and goals toward those recycled products for which there are significant market development needs or that may substantially contribute to solutions to the state's waste management problem;

. Provide standards for recycled products for use in procurement programs by all governmental agencies;

. Provide the authority for all governmental agencies to adopt preferential purchasing policies for recycled products;

. Direct state agencies to develop strategies to increase recycled product purchases, and to provide specific goals for procurement of recycled paper products and organic recovered materials; and

. Provide guidance and direction for local governments and other public agencies to develop plans for increasing the procurement of recycled content products.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5143-S2.SL.pdf?cite=1991%20c%20297%20§%201[1991 c 297 § 1]; ]

== 43.19A.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Biosolids" means municipal sewage sludge or septic tank septage sludge that meets the requirements of *chapter 70.95J RCW.

. "Compost products" means mulch, soil amendments, ground cover, or other landscaping material derived from the biological or mechanical conversion of biosolids or cellulose-containing waste materials.

. "Department" means the department of enterprise services.

. "Director" means the director of the department of enterprise services.

. "Local government" means a city, town, county, special purpose district, school district, or other municipal corporation.

. "Lubricating oil" means petroleum-based oils for reducing friction in engine parts and other mechanical parts.

. "Mixed waste paper" means assorted low-value grades of paper that have not been separated into individual grades of paper at the point of collection.

. "Municipal sewage sludge" means a semisolid substance consisting of settled sewage solids combined with varying amounts of water and dissolved materials generated from a publicly owned wastewater treatment plant.

. "Paper and paper products" means all items manufactured from paper or paperboard.

. "Postconsumer waste" means a material or product that has served its intended use and has been discarded for disposal or recovery by a final consumer.

. "Procurement officer" means the person that has the primary responsibility for procurement of materials or products.

. "Recycled content product" or "recycled product" means a product containing recycled materials.

. "Recycled materials" means waste materials and by-products that have been recovered or diverted from solid waste and that can be utilized in place of a raw or virgin material in manufacturing a product and consists of materials derived from postconsumer waste, manufacturing waste, industrial scrap, agricultural wastes, and other items, all of which can be used in the manufacture of new or recycled products.

. "Re-refined oils" means used lubricating oils from which the physical and chemical contaminants acquired through previous use have been removed through a refining process. Re-refining may include distillation, hydrotreating, or treatments employing acid, caustic, solvent, clay, or other chemicals, or other physical treatments other than those used in reclaiming.

. "State agency" means all units of state government, including divisions of the governor's office, the legislature, the judiciary, state agencies and departments, correctional institutions, vocational technical institutions, and universities and colleges.

. "USEPA product standards" means the product standards of the United States environmental protection agency for recycled content published in the Code of Federal Regulations.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5931-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2043%20§%20250[2011 1st sp.s. c 43 § 250]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2640-S.SL.pdf?cite=1992%20c%20174%20§%2012[1992 c 174 § 12]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5143-S2.SL.pdf?cite=1991%20c%20297%20§%202[1991 c 297 § 2]; ]

== 43.19A.020 - Recycled product purchasing—Federal product standards.
. The federal product standards, adopted under 42 U.S.C. Sec. 6962(e) as it exists on July 1, 2001, are adopted as the minimum standards for the state of Washington. These standards shall be implemented for at least the products listed in this subsection, unless the director finds that a different standard would significantly increase recycled product availability or competition.

.. Organic recovered materials;

.. Latex paint products;

.. Products for lower value uses containing recycled plastics;

.. Retread and remanufactured tires;

.. Lubricating oils;

.. Automotive batteries;

.. Building products and materials;

.. Panelboard; and

.. Compost products.

. By July 1, 2001, the director shall adopt product standards for strawboard manufactured using as an ingredient straw that is produced as a by-product in the production of cereal grain or turf or grass seed and product standards for products made from strawboard.

. The standards required by this section shall be applied to recycled product purchasing by the department, other state agencies, and state postsecondary educational institutions. The standards may be adopted or applied by any other local government in product procurement. The standards shall provide for exceptions under appropriate circumstances to allow purchases of recycled products that do not meet the minimum content requirements of the standards.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2287-S.SL.pdf?cite=2009%20c%20356%20§%203[2009 c 356 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1136-S.SL.pdf?cite=2001%20c%2077%20§%201[2001 c 77 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1231-S.SL.pdf?cite=1996%20c%20198%20§%201[1996 c 198 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1107-S.SL.pdf?cite=1995%20c%20269%20§%201406[1995 c 269 § 1406]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5143-S2.SL.pdf?cite=1991%20c%20297%20§%203[1991 c 297 § 3]; ]

== 43.19A.022 - Recycled content paper for printers and copiers—Purchasing priority.
. All state agencies shall purchase one hundred percent recycled content white cut sheet bond paper used in office printers and copiers. State agencies are encouraged to give priority to purchasing from companies that produce paper in facilities that generate energy from a renewable energy source.

. State agencies that utilize office printers and copiers that, after reasonable attempts, cannot be calibrated to utilize such paper referenced in subsection (1) of this section, must for those models of equipment:

.. Purchase paper at the highest recycled content that can be utilized efficiently by the copier or printer;

.. At the time of lease renewal or at the end of the life cycle, either lease or purchase a model that will efficiently utilize one hundred percent recycled content white cut sheet bond paper.

. Printed projects that require the use of high volume production inserters or high-speed digital devices, such as those used by the department of enterprise services, are not required to meet the one hundred percent recycled content white cut sheet bond paper standard, but must utilize the highest recycled content that can be utilized efficiently by such equipment and not impede the business of agencies.

. The department of enterprise services shall identify for use by agencies one hundred percent recycled paper products that process efficiently through high-speed production equipment and do not impede the business of agencies.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5024.SL.pdf?cite=2015%20c%20225%20§%2071[2015 c 225 § 71]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5931-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2043%20§%20251[2011 1st sp.s. c 43 § 251]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2287-S.SL.pdf?cite=2009%20c%20356%20§%202[2009 c 356 § 2]; ]

== 43.19A.030 - Local government duties.
. By January 1, 1993, each local government shall review its existing procurement policies and specifications to determine whether recycled products are intentionally or unintentionally excluded. The policies and specifications shall be revised to include such products unless a recycled content product does not meet an established performance standard of the agency.

. By fiscal year 1994, each local government shall adopt a minimum purchasing goal for recycled content as a percentage of the total dollar value of supplies purchased. To assist in achieving this goal each local government shall adopt a strategy by January 1, 1993, and shall submit a description of the strategy to the department. All public agencies shall respond to requests for information from the department for the purpose of its reporting requirements under this section.

. Each local government shall designate a procurement officer who shall serve as the primary contact with the department for compliance with the requirements of this chapter.

. This section shall apply only to local governments with expenditures for supplies exceeding five hundred thousand dollars for fiscal year 1989. Expenditures for capital goods and for electricity, water, or gas for resale shall not be considered a supply expenditure.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%2057[1998 c 245 § 57]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5143-S2.SL.pdf?cite=1991%20c%20297%20§%204[1991 c 297 § 4]; ]

== 43.19A.040 - Local government adoption of preferential purchase policy optional.
. Each local government shall consider the adoption of policies, rules, or ordinances to provide for the preferential purchase of recycled content products. Any local government may adopt the preferential purchasing policy of the department of enterprise services, or portions of such policy, or another policy that provides a preference for recycled content products.

. The department of enterprise services shall prepare one or more model recycled content preferential purchase policies suitable for adoption by local governments. The model policy shall be widely distributed and provided through the technical assistance and workshops under RCW 43.19A.070.

. A local government that is not subject to the purchasing authority of the department of enterprise services, and that adopts the preferential purchase policy or rules of the department, shall not be limited by the percentage price preference included in such policy or rules.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5024.SL.pdf?cite=2015%20c%20225%20§%2072[2015 c 225 § 72]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5143-S2.SL.pdf?cite=1991%20c%20297%20§%206[1991 c 297 § 6]; ]

== 43.19A.050 - Strategy for state agency procurement.
The department shall prepare a strategy to increase purchases of recycled-content products by the department and all state agencies, including higher education institutions. The strategy shall include purchases from public works contracts. The strategy shall address the purchase of plastic products, retread and remanufactured tires, motor vehicle lubricants, latex paint, and lead acid batteries having recycled content. In addition, the strategy shall incorporate actions to achieve the following purchase level goals of compost products:

Compost products as a percentage of the total dollar amount on an annual basis:

. At least forty percent by 1996;

. At least sixty percent by 1997;

. At least eighty percent by 1998.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2287-S.SL.pdf?cite=2009%20c%20356%20§%204[2009 c 356 § 4]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1231-S.SL.pdf?cite=1996%20c%20198%20§%202[1996 c 198 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5143-S2.SL.pdf?cite=1991%20c%20297%20§%207[1991 c 297 § 7]; ]

== 43.19A.060 - Database of products and vendors.
. The department shall develop a database of available products with recycled-content products, and vendors supplying such products. The database shall incorporate information regarding product consistency with the content standards adopted under RCW 43.19A.020. The database shall incorporate information developed through state and local government procurement of recycled-content products.

. By December 1, 1992, the department shall report to the appropriate standing committees of the legislature on the cost of making the database accessible to all state and local governments and to the private sector.

. The department shall compile information on purchases made by the department or pursuant to the department's purchasing authority, and information provided by local governments, regarding:

.. The percentage of recycled content and, if known, the amount of postconsumer waste in the products purchased;

.. Price;

.. Agency experience with the performance of recycled products and the supplier under the terms of the purchase; and

.. Any other information deemed appropriate by the department.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5143-S2.SL.pdf?cite=1991%20c%20297%20§%208[1991 c 297 § 8]; ]

== 43.19A.070 - Education program—Product substitution list—Model procurement guidelines.
. The department shall implement an education program to encourage maximum procurement of recycled products by state and local government entities. The program shall include at least the following:

.. Technical assistance to all state and local governments and their designated procurement officers on the requirements of this chapter, including preparation of model purchase contracts, the preparation of procurement plans, and the availability of recycled products;

.. Two or more workshops annually in which all state and local government entities are invited;

.. Information on intergovernmental agreements to facilitate procurement of recycled products.

. The director shall, in consultation with the department of ecology, make available to the public, local jurisdictions, and the private sector, a comprehensive list of substitutes for extremely hazardous, hazardous, toxic, and nonrecyclable products, and disposable products intended for a single use. The department and all state agencies exercising the purchasing authorities of the department shall include the substitute products on bid notifications, except where the department allows an exception based upon product availability, price, suitability for intended use, or similar reasons.

. The department shall prepare model procurement guidelines for use by local governments.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5143-S2.SL.pdf?cite=1991%20c%20297%20§%209[1991 c 297 § 9]; ]

== 43.19A.080 - Bid notification to state recycled content requirements.
A notification regarding a state or local government's intent to procure products with recycled content must be prominently displayed in the procurement solicitation or invitation to bid including:

. A description of the postconsumer waste content or recycled content requirements; and

. A description of the agency's recycled content preference program.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5143-S2.SL.pdf?cite=1991%20c%20297%20§%2011[1991 c 297 § 11]; ]

== 43.19A.110 - Local road projects—Compost products.
. Each county and city required to prepare a strategy under RCW 43.19A.030 shall adopt specifications for compost products to be used in road projects. The specifications developed by the department of transportation under RCW 47.28.220 may be adopted by the city or county in lieu of developing specifications.

. After July 1, 1992, any contract awarded in whole or in part for applying soils, soil covers, or soil amendments to road rights-of-way shall specify that compost materials be purchased in accordance with the following schedule:

.. For the period July 1, 1992, through June 30, 1994, at least twenty-five percent of the total dollar amount of purchases by the city or county;

.. On and after July 1, 1994, at least fifty percent of the annual total dollar amount of purchases by the city or county.

. The city or county may depart from the schedule in subsection (2) of this section where it determines that no suitable product is available at a reasonable price.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5143-S2.SL.pdf?cite=1991%20c%20297%20§%2017[1991 c 297 § 17]; ]

== 43.19A.120 - Use of compost products in projects.
. When planning government-funded projects or soliciting and reviewing bids for such projects, all state agencies and local governments shall consider whether compost products can be utilized in the project.

. If compost products can be utilized in the project, the state agency or local government must use compost products, except as follows:

.. A state agency or local government is not required to use compost products if:

... Compost products are not available within a reasonable period of time;

... Compost products that are available do not comply with existing purchasing standards;

... Compost products that are available do not comply with federal or state health, quality, and safety standards; and

... Compost purchase prices are not reasonable or competitive; and

.. A state agency is also not required to use compost products in a project if:

... The total cost of using compost is financially prohibitive;

... Application of compost will have detrimental impacts on the physical characteristics and nutrient condition of the soil as it is used for a specific crop;

... The project consists of growing trees in a greenhouse setting, including seed orchard greenhouses; or

... The compost products that are available have not been certified as being free of crop-specific pests and pathogens, including pests and pathogens that could result in the denial of phytosanitary permits for shipping seedlings.

. Before the transportation or application of compost products under this section, composting facilities, state agencies, and local governments must ensure compliance with department of agriculture pest control regulations provided in chapter 16-470 WAC.

. State agencies and local governments are encouraged to give priority to purchasing compost products from companies that produce compost products locally, are certified by a nationally recognized organization, and produce compost products that are derived from municipal solid waste compost programs and meet quality standards adopted by rule by the department of ecology.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2713-S.SL.pdf?cite=2020%20c%20290%20§%202[2020 c 290 § 2]; ]

== 43.19A.130 - Local governments encouraged to enter compost product purchasing agreements.
. Each local government that provides a residential composting service is encouraged to enter into a purchasing agreement with its compost processor to buy back finished compost products for use in government projects or on government land. The local government is encouraged to purchase an amount of finished compost product that is equal to or greater than fifty percent of the amount of organic residuals it delivered to the compost processor. Local governments may enter into collective purchasing agreements if doing so is more cost-effective or efficient. The compost processor should offer a purchase price that is reasonable and competitive for the specific market.

. When purchasing compost products for use in government projects or on government-owned land, local governments are encouraged to purchase compost with at least eight percent food waste, or an amount of food waste that is commensurate with that in the local jurisdiction's curbside collection program.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2713-S.SL.pdf?cite=2020%20c%20290%20§%203[2020 c 290 § 3]; ]

