= 43.88C - Caseload forecast council.
:toc:

== 43.88C.010 - Caseload forecast council—Duties.
. The caseload forecast council is hereby created. The council shall consist of two individuals appointed by the governor and four individuals, one of whom is appointed by the chairperson of each of the two largest political caucuses in the senate and house of representatives. The chair of the council shall be selected from among the four caucus appointees. The council may select such other officers as the members deem necessary.

. The council shall employ a caseload forecast supervisor to supervise the preparation of all caseload forecasts. As used in this chapter, "supervisor" means the caseload forecast supervisor.

. Approval by an affirmative vote of at least five members of the council is required for any decisions regarding employment of the supervisor. Employment of the supervisor shall terminate after each term of three years. At the end of the first year of each three-year term the council shall consider extension of the supervisor's term by one year. The council may fix the compensation of the supervisor. The supervisor shall employ staff sufficient to accomplish the purposes of this section.

. The caseload forecast council shall oversee the preparation of and approve, by an affirmative vote of at least four members, the official state caseload forecasts prepared under RCW 43.88C.020. If the council is unable to approve a forecast before a date required in RCW 43.88C.020, the supervisor shall submit the forecast without approval and the forecast shall have the same effect as if approved by the council.

. A councilmember who does not cast an affirmative vote for approval of the official caseload forecast may request, and the supervisor shall provide, an alternative forecast based on assumptions specified by the member.

. Members of the caseload forecast council shall serve without additional compensation but shall be reimbursed for travel expenses in accordance with RCW 44.04.120 while attending sessions of the council or on official business authorized by the council. Nonlegislative members of the council shall be reimbursed for travel expenses in accordance with RCW 43.03.050 and 43.03.060.

. "Caseload," as used in this chapter, means:

.. The number of persons expected to meet entitlement requirements and require the services of public assistance programs, state correctional institutions, state correctional noninstitutional supervision, state institutions for juvenile offenders, the common school system, long-term care, medical assistance, foster care, and adoption support;

.. The number of students who are eligible for the Washington college bound scholarship program and are expected to attend an institution of higher education as defined in RCW 28B.92.030;

.. The number of students who are eligible for the Washington college grant program under RCW 28B.92.200 and 28B.92.205 and are expected to attend an institution of higher education as defined in RCW 28B.92.030; and

.. The number of children who are eligible, as defined in RCW 43.216.505, to participate in, and the number of children actually served by, the early childhood education and assistance program.

. The caseload forecast council shall forecast the temporary assistance for needy families and the working connections child care programs as a courtesy.

. The caseload forecast council shall present the number of individuals who are assessed as eligible for and have requested a service through the individual and family services waiver and the basic plus waiver administered by the developmental disabilities administration as a courtesy. The caseload forecast council shall be presented with the service request list as defined in RCW 71A.10.020 to aid in development of this information.

. The caseload forecast council shall forecast youth participating in the extended foster care program pursuant to RCW 74.13.031 separately from other children who are residing in foster care and who are under eighteen years of age.

. The caseload forecast council shall forecast the number of youth expected to receive behavioral rehabilitation services while involved in the foster care system and the number of screened in reports of child abuse or neglect.

. Unless the context clearly requires otherwise, the definitions provided in RCW 43.88.020 apply to this chapter.

. During the 2021-2023 fiscal biennium, and beginning with the November 2021 forecast, the caseload forecast council shall produce an unofficial forecast of the long-term caseload for juvenile rehabilitation as a courtesy.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5092-S.SL.pdf?cite=2021%20c%20334%20§%20975[2021 c 334 § 975]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6040-S.SL.pdf?cite=2020%20c%20352%20§%201[2020 c 352 § 1]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2158-S2.SL.pdf?cite=2019%20c%20406%20§%2024[2019 c 406 § 24]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2008.SL.pdf?cite=2018%20c%20208%20§%204[2018 c 208 § 4]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5999-S.SL.pdf?cite=2015%20c%20128%20§%202[2015 c 128 § 2]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5405-S2.SL.pdf?cite=2013%20c%20332%20§%2011[2013 c 332 § 11]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2262.SL.pdf?cite=2012%20c%20217%20§%203[2012 c 217 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5304.SL.pdf?cite=2011%20c%20304%20§%202[2011 c 304 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2344.SL.pdf?cite=2000%20c%2090%20§%201[2000 c 90 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5472-S.SL.pdf?cite=1997%20c%20168%20§%201[1997 c 168 § 1]; ]

== 43.88C.020 - Preparation and submittal of caseload forecasts—Cooperation of state agencies—Official state caseload forecast.
. In consultation with the caseload forecast work group established under RCW 43.88C.030, and subject to the approval of the caseload forecast council under RCW 43.88C.010, the supervisor shall prepare:

.. An official state caseload forecast; and

.. Other caseload forecasts based on alternative assumptions as the council may determine.

. The supervisor shall submit caseload forecasts prepared under this section, along with any unofficial forecasts provided under RCW 43.88C.010, to the governor and the members of the legislative fiscal committees, including one copy to the staff of each of the committees. The forecasts shall be submitted at least three times each year and on such dates as the council determines will facilitate the development of budget proposals by the governor and the legislature.

. All agencies of state government shall provide to the supervisor immediate access to all information relating to caseload forecasts.

. The administrator of the legislative evaluation and accountability program committee may request, and the supervisor shall provide, alternative caseload forecasts based on assumptions specified by the administrator.

. The official state caseload forecast under this section shall be the basis of the governor's budget document as provided in RCW 43.88.030 and utilized by the legislature in the development of the omnibus biennial appropriations act.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5472-S.SL.pdf?cite=1997%20c%20168%20§%202[1997 c 168 § 2]; ]

== 43.88C.030 - Caseload forecast work group—Submittal of data by state agencies—Meetings.
. To promote the free flow of information and to promote legislative and executive input in the development of assumptions and preparation of forecasts, immediate access to all information and statistical models relating to caseload forecasts shall be available to the caseload forecast work group, hereby created. Each state agency affected by caseloads shall submit caseload reports and data to the council as soon as the reports and data are available and shall provide to the council and the supervisor such additional raw, program-level data or information as may be necessary for discharge of their respective duties.

. The caseload forecast work group shall consist of one staff member selected by the executive head or chairperson of each of the following agencies, programs, or committees:

.. Office of financial management;

.. Ways and means committee, or its successor, of the senate;

.. Appropriations committee, or its successor, of the house of representatives;

.. Legislative evaluation and accountability program committee; and

.. Each state program for which the council forecasts the caseload.

. The caseload forecast work group shall provide technical support to the caseload forecast council. Meetings of the caseload forecast work group may be called by any member of the group for the purpose of assisting the council, reviewing forecasts, or for any other purpose that may assist the council.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5472-S.SL.pdf?cite=1997%20c%20168%20§%203[1997 c 168 § 3]; ]

== 43.88C.040 - Sentencing information system—Sentencing manual.
. The caseload forecast council shall develop and maintain a computerized adult and juvenile sentencing information system consisting of offender, offense, history, and sentence information entered from the judgment and sentence forms for all adult felons.

. As part of its duties in maintaining the sentencing information system, the caseload forecast council shall:

.. On an annual basis, publish a statistical summary of adult felony sentencing and juvenile dispositions;

.. Publish and maintain an adult felony sentencing manual; and

.. Publish and maintain a juvenile sentencing manual.

. The sentencing manuals are intended only as a guide to assist practitioners in determining appropriate sentencing ranges. The manuals are not a substitute for the actual statutes, which list the sentencing ranges, or for any other information contained within this chapter. The caseload forecast council is not liable for errors or omissions in the manual, for sentences that may be inappropriately calculated as a result of a practitioner's or court's reliance on the manual, or for any other written or verbal information provided by the caseload forecast council or its staff related to adult or juvenile sentencing.

. In publishing materials required by this section, the caseload forecast council shall make the materials available on its website. The caseload forecast council may charge a reasonable cost for producing and distributing hard copies of any materials.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5891-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2040%20§%2028[2011 1st sp.s. c 40 § 28]; ]

== 43.88C.050 - Research staff.
The caseload forecast council shall appoint a research staff of sufficient size and with sufficient resources to accomplish its duties. The caseload forecast council may request from the administrative office of the courts, the department of children, youth, and families, the department of corrections, the health care authority, the superintendent of public instruction, the Washington student achievement council, the department of social and health services, and other agencies with caseloads forecasted by the council, such data, information, and data processing assistance as it may need to accomplish its duties, and such services shall be provided without cost to the caseload forecast council.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6287.SL.pdf?cite=2018%20c%2058%20§%2015[2018 c 58 § 15]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5999-S.SL.pdf?cite=2015%20c%20128%20§%203[2015 c 128 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5891-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2040%20§%2029[2011 1st sp.s. c 40 § 29]; ]

== 43.88C.900 - Effective date—1997 c 168.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and takes effect July 1, 1997.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5472-S.SL.pdf?cite=1997%20c%20168%20§%208[1997 c 168 § 8]; ]

