= 43.27A - Water resources.
:toc:

== 43.27A.020 - Definitions.
As used in this chapter, and unless the context indicates otherwise, words and phrase shall mean:

"Department" means the department of ecology;

"Director" means the director of ecology;

"State agency" and "state agencies" mean any branch, department or unit of state government, however designated or constituted;

"Water resources" means all waters above, upon, or beneath the surface of the earth, located within the state and over which the state has sole or concurrent jurisdiction.

"Beneficial use" means, but its meaning shall not be limited to: Domestic water supplies; irrigation; fish, shellfish, game, and other aquatic life; recreation; industrial water supplies; generation of hydroelectric power; and navigation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c109.pdf?cite=1987%20c%20109%20§%2031[1987 c 109 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c242.pdf?cite=1967%20c%20242%20§%202[1967 c 242 § 2]; ]

== 43.27A.090 - Powers and duties of department.
The department shall be empowered as follows:

. To represent the state at, and fully participate in, the activities of any basin or regional commission, interagency committee, or any other joint interstate or federal-state agency, committee or commission, or publicly financed entity engaged in the planning, development, administration, management, conservation or preservation of the water resources of the state.

. To prepare the views and recommendations of the state of Washington on any project, plan or program relating to the planning, development, administration, management, conservation and preservation of any waters located in or affecting the state of Washington, including any federal permit or license proposal, and appear on behalf of, and present views and recommendations of the state at any proceeding, negotiation or hearing conducted by the federal government, interstate agency, state or other agency.

. To cooperate with, assist, advise and coordinate plans with the federal government and its officers and agencies, and serve as a state liaison agency with the federal government in matters relating to the use, conservation, preservation, quality, disposal or control of water and activities related thereto.

. To cooperate with appropriate agencies of the federal government and/or agencies of other states, to enter into contracts, and to make appropriate contributions to federal or interstate projects and programs and governmental bodies to carry out the provisions of this chapter.

. To apply for, accept, administer and expend grants, gifts and loans from the federal government or any other entity to carry out the purposes of this chapter and make contracts and do such other acts as are necessary insofar as they are not inconsistent with other provisions hereof.

. To develop and maintain a coordinated and comprehensive state water and water resources related development plan, and adopt, with regard to such plan, such policies as are necessary to insure that the waters of the state are used, conserved and preserved for the best interest of the state. There shall be included in the state plan a description of developmental objectives and a statement of the recommended means of accomplishing these objectives. To the extent the director deems desirable, the plan shall integrate into the state plan, the plans, programs, reports, research and studies of other state agencies.

. To assemble and correlate information relating to water supply, power development, irrigation, watersheds, water use, future possibilities of water use and prospective demands for all purposes served through or affected by water resources development.

. To assemble and correlate state, local and federal laws, regulations, plans, programs and policies affecting the beneficial use, disposal, pollution, control or conservation of water, river basin development, flood prevention, parks, reservations, forests, wildlife refuges, drainage and sanitary systems, waste disposal, waterworks, watershed protection and development, soil conservation, power facilities and area and municipal water supply needs, and recommend suitable legislation or other action to the legislature, the congress of the United States, or any city, municipality, or to responsible state, local or federal executive departments or agencies.

. To cooperate with federal, state, regional, interstate and local public and private agencies in the making of plans for drainage, flood control, use, conservation, allocation and distribution of existing water supplies and the development of new water resource projects.

. To encourage, assist and advise regional, and city and municipal agencies, officials or bodies responsible for planning in relation to water aspects of their programs, and coordinate local water resources activities, programs, and plans.

. To promulgate such rules and regulations as are necessary to carry out the purposes of this chapter.

. To hold public hearings, and make such investigations, studies and surveys as are necessary to carry out the purposes of the chapter.

. To subpoena witnesses, compel their attendance, administer oaths, take the testimony of any person under oath and require the production of any books or papers when the department deems such measures necessary in the exercise of its rule-making power or in determining whether or not any license, certificate, or permit shall be granted or extended.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c127.pdf?cite=1988%20c%20127%20§%2025[1988 c 127 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c242.pdf?cite=1967%20c%20242%20§%209[1967 c 242 § 9]; ]

== 43.27A.130 - Department of ecology to inventory state water resources.
The department of ecology may make complete inventories of the state's water resources and enter into such agreements with the director of the United States geological survey as will insure that investigations and surveys are carried on in an economical manner.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c127.pdf?cite=1988%20c%20127%20§%2026[1988 c 127 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c242.pdf?cite=1967%20c%20242%20§%2015[1967 c 242 § 15]; ]

== 43.27A.190 - Water resource orders.
Notwithstanding and in addition to any other powers granted to the department of ecology, whenever it appears to the department that a person is violating or is about to violate any of the provisions of the following:

. Chapter 90.03 RCW; or

. Chapter 90.44 RCW; or

. Chapter 86.16 RCW; or

. Chapter 70A.10 RCW; or

. Chapter 43.27A RCW; or

. Any other law relating to water resources administered by the department; or

. A rule or regulation adopted, or a directive or order issued by the department relating to subsections (1) through (6) of this section; the department may cause a written regulatory order to be served upon said person either personally, or by registered or certified mail delivered to addressee only with return receipt requested and acknowledged by him or her. The order shall specify the provision of the statute, rule, regulation, directive or order alleged to be or about to be violated, and the facts upon which the conclusion of violating or potential violation is based, and shall order the act constituting the violation or the potential violation to cease and desist or, in appropriate cases, shall order necessary corrective action to be taken with regard to such acts within a specific and reasonable time. The regulation of a headgate or controlling works as provided in RCW 90.03.070, by a watermaster, stream patrol officer, or other person so authorized by the department shall constitute a regulatory order within the meaning of this section. A regulatory order issued hereunder shall become effective immediately upon receipt by the person to whom the order is directed, except for regulations under RCW 90.03.070 which shall become effective when a written notice is attached as provided therein. Any person aggrieved by such order may appeal the order pursuant to RCW 43.21B.310.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201043[2020 c 20 § 1043]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%205111[2009 c 549 § 5111]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c109.pdf?cite=1987%20c%20109%20§%2011[1987 c 109 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c284.pdf?cite=1969%20ex.s.%20c%20284%20§%207[1969 ex.s. c 284 § 7]; ]

== 43.27A.220 - "Person" defined.
Whenever the word "person" is used in RCW 43.27A.190, it shall be construed to include any political subdivision, government agency, municipality, industry, public or private corporation, copartnership, association, firm, individual or any other entity whatsoever.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c127.pdf?cite=1988%20c%20127%20§%2027[1988 c 127 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c284.pdf?cite=1969%20ex.s.%20c%20284%20§%2011[1969 ex.s. c 284 § 11]; ]

== 43.27A.900 - Liberal construction.
The rule of strict construction shall have no application to this chapter, but the same shall be liberally construed, in order to carry out the purposes and objectives for which this chapter is intended.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c242.pdf?cite=1967%20c%20242%20§%2022[1967 c 242 § 22]; ]

