= 43.99H - Financing for appropriations—1989-1991 biennium.
:toc:

== 43.99H.010 - 1989-1991 Fiscal biennium—General obligation bonds for capital and operating appropriations act.
The state finance committee is authorized to issue general obligation bonds of the state of Washington in the sum of one billion four hundred four million dollars, or so much thereof as may be required, to finance the projects described and authorized by the legislature in the capital and operating appropriations acts for the 1989-1991 fiscal biennium and subsequent fiscal biennia, and all costs incidental thereto, and to provide for reimbursement of bond-funded accounts from the 1987-1989 fiscal biennium.

Bonds authorized in this section shall be sold in such manner, at such time or times, in such amounts, and at such price as the state finance committee shall determine. No such bonds may be offered for sale without prior legislative appropriation of the net proceeds of the sale of the bonds. The state finance committee may obtain insurance, letters of credit, or other credit enhancements and may authorize the execution and delivery of agreements, promissory notes, and other obligations for the purpose of insuring the payment or enhancing the marketability of bonds authorized in this section. Promissory notes or other obligations issued pursuant to this section shall not constitute a debt or the contracting of indebtedness under any constitutional or statutory indebtedness limitation if their payment is conditioned upon the failure of the state to pay the principal of or interest on the bonds with respect to which the same relate.

The state finance committee shall consider the issuance of short-term obligations in lieu of long-term obligations for the purposes of more favorable interest rates, lower total interest costs, and increased marketability and for the purpose of retiring the bonds during the life of the project for which they were issued.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c15.pdf?cite=1990%201st%20ex.s.%20c%2015%20§%201[1990 1st ex.s. c 15 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c14.pdf?cite=1989%201st%20ex.s.%20c%2014%20§%201[1989 1st ex.s. c 14 § 1]; ]

== 43.99H.020 - Conditions and limitations.
Bonds issued under RCW 43.99H.010 are subject to the following conditions and limitations:

General obligation bonds of the state of Washington in the sum of one billion four hundred four million dollars, or so much thereof as may be required, shall be issued for the purposes described and authorized by the legislature in the capital and operating appropriations acts for the 1989-91 fiscal biennium and subsequent fiscal biennia, and to provide for the administrative cost of such projects, including costs of bond issuance and retirement, salaries and related costs of officials and employees of the state, costs of insurance or credit enhancement agreements, and other expenses incidental to the administration of capital projects, and to provide for reimbursement of bond-funded accounts from the 1987-89 fiscal biennium. Subject to such changes as may be required in the appropriations acts, the proceeds from the sale of the bonds issued for the purposes of this subsection shall be deposited in the state building construction account created by RCW 43.83.020 and transferred as follows:

. Thirty million dollars to the state and local improvements revolving account—waste disposal facilities, created by RCW 43.83.330, to be used for the purposes described in *RCW 43.83A.020;

. Five million three hundred thousand dollars to the salmon enhancement construction account created by **RCW 75.48.030;

. One hundred twenty million dollars to the state and local improvements revolving account—waste disposal facilities, 1980 created by RCW 43.83.350, to be used for the purposes described in RCW 43.83.350;

. Forty million dollars to the common school construction fund as referenced in RCW 28A.515.320.

. Three million two hundred thousand dollars to the state higher education construction account created by RCW 43.83.300;

. Eight hundred five million dollars to the state building construction account created by RCW 43.83.020;

. Nine hundred fifty thousand dollars to the higher education reimbursable short-term bond account created by RCW 43.83.320;

. Twenty-nine million seven hundred thirty thousand dollars to the outdoor recreation account created by RCW 79A.25.060;

. Sixty million dollars to the state and local improvements revolving account-water supply facilities, created by RCW 43.83.340 to be used for the purposes described in RCW 43.83.340;

. Four million three hundred thousand dollars to the state social and health services construction account created by RCW 43.83.360;

. Two hundred fifty thousand dollars to the fisheries capital projects account created by RCW 43.83.370;

. Four million nine hundred thousand dollars to the state building construction account created by RCW 43.83.020;

. Two million three hundred thousand dollars to the essential rail assistance account created by RCW 47.76.250;

. One million one hundred thousand dollars to the essential rail bank account hereby created in the state treasury;

. Seventy-three million dollars to the east capitol campus construction account hereby created in the state treasury;

. Eight million dollars to the higher education construction account created in RCW 43.83.310;

. Sixty-three million two hundred thousand dollars to the labor and industries construction account hereby created in the state treasury;

. Seventy-five million dollars to the higher education construction account created by RCW 43.83.310;

. Twenty-six million five hundred fifty thousand dollars to the habitat conservation account hereby created in the state treasury; and

. Eight million dollars to the public safety reimbursable bond account hereby created in the state treasury.

These proceeds shall be used exclusively for the purposes specified in this subsection, and for the payment of expenses incurred in the issuance and sale of the bonds issued for the purposes of this section, and shall be administered by the office of financial management, subject to legislative appropriation.

Bonds authorized for the purposes of subsection (17) of this section shall be issued only after the director of the department of labor and industries has certified, based on reasonable estimates, that sufficient revenues will be available from the accident fund created in RCW 51.44.010 and the medical aid fund created in RCW 51.44.020 to meet the requirements of RCW 43.99H.060(4) during the life of the bonds.

Bonds authorized for the purposes of subsection (18) of this section shall be issued only after the board of regents of the University of Washington has certified, based on reasonable estimates, that sufficient revenues will be available from nonappropriated local funds to meet the requirements of RCW 43.99H.060(4) during the life of the bonds.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1859.SL.pdf?cite=2015%201st%20sp.s.%20c%204%20§%2042[2015 1st sp.s. c 4 § 42]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c15.pdf?cite=1990%201st%20ex.s.%20c%2015%20§%202[1990 1st ex.s. c 15 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20582[1990 c 33 § 582]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c14.pdf?cite=1989%201st%20ex.s.%20c%2014%20§%202[1989 1st ex.s. c 14 § 2]; ]

== 43.99H.030 - Retirement of bonds.
Both principal of and interest on the bonds issued for the purposes specified in RCW 43.99H.020 (1) through (3), (5) through (14), and (19) shall be payable from the debt-limit general fund bond retirement account.

The state finance committee shall, on or before June 30th of each year, certify to the state treasurer the amount required to provide for the payment of principal and interest on such bonds during the ensuing fiscal year in accordance with the provisions of the bond proceedings. The state treasurer shall withdraw from any general state revenues received in the state treasury and deposit in the debt-limit general fund bond retirement account such amounts and at such times as are required by the bond proceedings.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6064-S.SL.pdf?cite=1997%20c%20456%20§%2019[1997 c 456 § 19]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1430-S.SL.pdf?cite=1991%20sp.s.%20c%2031%20§%2013[1991 sp.s. c 31 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c15.pdf?cite=1990%201st%20ex.s.%20c%2015%20§%204[1990 1st ex.s. c 15 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c14.pdf?cite=1989%201st%20ex.s.%20c%2014%20§%203[1989 1st ex.s. c 14 § 3]; ]

== 43.99H.040 - Retirement of bonds.
. Both principal of and interest on the bonds issued for the purposes of RCW 43.99H.020(16) shall be payable from the nondebt-limit reimbursable bond retirement account.

The state finance committee shall, on or before June 30th of each year, certify to the state treasurer the amount required to provide for the payment of principal and interest on such bonds during the ensuing fiscal year in accordance with the provisions of the bond proceedings. The state treasurer shall withdraw from any general state revenues received in the state treasury and deposit in the nondebt-limit reimbursable bond retirement account such amounts and at such times as are required by the bond proceedings.

. Both principal of and interest on the bonds issued for the purposes of RCW 43.99H.020(15) shall be payable from the debt-limit reimbursable bond retirement account and nondebt-limit reimbursable bond retirement account as set forth under RCW 43.99H.060(2).

The state finance committee shall, on or before June 30th of each year, certify to the state treasurer the amount required to provide for the payment of principal and interest on such bonds during the ensuing fiscal year in accordance with the provisions of the bond proceedings. The state treasurer shall withdraw from any general state revenues received in the state treasury and deposit in the debt-limit reimbursable bond retirement account and nondebt-limit reimbursable bond retirement account as set forth under RCW 43.99H.060(2) such amounts and at such times as are required by the bond proceedings.

. Both principal of and interest on the bonds issued for the purposes of RCW 43.99H.020(17) shall be payable from the nondebt-limit proprietary appropriated bond retirement account.

The state finance committee shall, on or before June 30th of each year, certify to the state treasurer the amount required to provide for the payment of principal and interest on such bonds during the ensuing fiscal year in accordance with the provisions of the bond proceedings. The state treasurer shall withdraw from any general state revenues received in the state treasury and deposit in the nondebt-limit proprietary appropriated bond retirement account such amounts and at such times as are required by the bond proceedings.

. Both principal of and interest on the bonds issued for the purposes of RCW 43.99H.020(18) shall be payable from the nondebt-limit reimbursable bond retirement account.

The state finance committee shall, on or before June 30th of each year, certify to the state treasurer the amount required to provide for the payment of principal and interest on such bonds during the ensuing fiscal year in accordance with the provisions of the bond proceedings. The state treasurer shall withdraw from any general state revenues received in the state treasury and deposit in the nondebt-limit reimbursable bond retirement account such amounts and at such times as are required by the bond proceedings.

. Both principal of and interest on the bonds issued for the purposes of RCW 43.99H.020(20) shall be payable from the nondebt-limit reimbursable bond retirement account.

The state finance committee shall, on or before June 30th of each year, certify to the state treasurer the amount required to provide for the payment of principal and interest on such bonds during the ensuing fiscal year in accordance with the provisions of the bond proceedings. The state treasurer shall withdraw from any general state revenues received in the state treasury and deposit in the nondebt-limit reimbursable bond retirement account such amounts and at such times as are required by the bond proceedings.

. Both principal of and interest on the bonds issued for the purposes of RCW 43.99H.020(4) shall be payable from the nondebt-limit general fund bond retirement account.

The state finance committee shall, on or before June 30th of each year, certify to the state treasurer the amount required to provide for the payment of principal and interest on such bonds during the ensuing fiscal year in accordance with the provisions of the bond proceedings. The state treasurer shall withdraw from any general state revenues received in the state treasury and deposit in the nondebt-limit general fund bond retirement account such amounts and at such times as are required by the bond proceedings.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6064-S.SL.pdf?cite=1997%20c%20456%20§%2020[1997 c 456 § 20]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1430-S.SL.pdf?cite=1991%20sp.s.%20c%2031%20§%2014[1991 sp.s. c 31 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c15.pdf?cite=1990%201st%20ex.s.%20c%2015%20§%205[1990 1st ex.s. c 15 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c14.pdf?cite=1989%201st%20ex.s.%20c%2014%20§%204[1989 1st ex.s. c 14 § 4]; ]

== 43.99H.050 - Pledge and promise—Remedies.
Bonds issued under RCW 43.99H.010 shall state that they are a general obligation of the state of Washington, shall pledge the full faith and credit of the state to the payment of the principal thereof and the interest thereon, and shall contain an unconditional promise to pay the principal and interest as the same shall become due.

The owner and holder of each of the bonds or the trustee for the owner and holder of any of the bonds may by mandamus or other appropriate proceeding require the transfer and payment of funds as directed in this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c14.pdf?cite=1989%201st%20ex.s.%20c%2014%20§%205[1989 1st ex.s. c 14 § 5]; ]

== 43.99H.060 - Reimbursement of general fund.
. For bonds issued for the purposes of RCW 43.99H.020(16), on each date on which any interest or principal and interest payment is due, the board of regents or the board of trustees of Washington State University shall cause the amount computed in RCW 43.99H.040(1) to be paid out of the appropriate building account or capital projects account to the state treasurer for deposit into the general fund of the state treasury.

. For bonds issued for the purposes of RCW 43.99H.020(15), on each date on which any interest or principal and interest payment is due, the state treasurer shall transfer the amount computed in RCW 43.99H.040(2) from the capitol campus reserve account, hereby created in the state treasury, to the general fund of the state treasury. At the time of sale of the bonds issued for the purposes of RCW 43.99H.020(15), and on or before June 30th of each succeeding year while such bonds remain outstanding, the state finance committee shall determine, based on current balances and estimated receipts and expenditures from the capitol campus reserve account, that portion of principal and interest on such RCW 43.99H.020(15) bonds which will, by virtue of payments from the capitol campus reserve account, be reimbursed from sources other than "general state revenues" as that term is defined in Article VIII, section 1 of the state Constitution.

. For bonds issued for the purposes of RCW 43.99H.020(17), on each date on which any interest or principal and interest payment is due, the director of the department of labor and industries shall cause fifty percent of the amount computed in RCW 43.99H.040(3) to be transferred from the accident fund created in RCW 51.44.010 and fifty percent of the amount computed in RCW 43.99H.040(3) to be transferred from the medical aid fund created in RCW 51.44.020, to the general fund of the state treasury.

. For bonds issued for the purposes of RCW 43.99H.020(18), on each date on which any interest or principal and interest payment is due, the board of regents of the University of Washington shall cause the amount computed in RCW 43.99H.040(4) to be paid out of University of Washington nonappropriated local funds to the state treasurer for deposit into the general fund of the state treasury.

. For bonds issued for the purposes of RCW 43.99H.020(4), on each date on which any interest or principal and interest payment is due, the state treasurer shall transfer from property taxes in the state general fund levied for the support of the common schools under RCW 84.52.065 to the general fund of the state treasury for unrestricted use the amount computed in RCW 43.99H.040(6).

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5537-S.SL.pdf?cite=2009%20c%20500%20§%208[2009 c 500 § 8]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5073-S.SL.pdf?cite=2009%20c%20479%20§%2032[2009 c 479 § 32]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1430-S.SL.pdf?cite=1991%20sp.s.%20c%2031%20§%2015[1991 sp.s. c 31 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c15.pdf?cite=1990%201st%20ex.s.%20c%2015%20§%206[1990 1st ex.s. c 15 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c14.pdf?cite=1989%201st%20ex.s.%20c%2014%20§%206[1989 1st ex.s. c 14 § 6]; ]

== 43.99H.070 - East capitol campus construction account—Additional means of reimbursement.
In addition to any other charges authorized by law and to assist in the reimbursement of principal and interest payments on bonds issued for the purposes of RCW 43.99H.020(15), the following revenues may be collected:

. The director of enterprise services may assess a charge against each state board, commission, agency, office, department, activity, or other occupant of the facility or building constructed with bonds issued for the purposes of RCW 43.99H.020(15) for payment of a proportion of costs for each square foot of floor space assigned to or occupied by the entity. Payment of the amount billed to the entity for such occupancy shall be made quarterly during each fiscal year. The director of enterprise services shall deposit the payment in the capitol campus reserve account.

. The director of enterprise services may pledge a portion of the parking rental income collected by the department of enterprise services from parking space developed as a part of the facility constructed with bonds issued for the purposes of RCW 43.99H.020(15). The pledged portion of this income shall be deposited in the capitol campus reserve account. The unpledged portion of this income shall continue to be deposited in the state vehicle parking account.

. The state treasurer shall transfer four million dollars from the capitol building construction account to the capitol campus reserve account each fiscal year from 1990 to 1995. Beginning in fiscal year 1996, the director of enterprise services, in consultation with the state finance committee, shall determine the necessary amount for the state treasurer to transfer from the capitol building construction account to the capitol campus reserve account for the purpose of repayment of the general fund of the costs of the bonds issued for the purposes of RCW 43.99H.020(15).

. Any remaining balance in the state building and parking bond redemption account after the final debt service payment shall be transferred to the capitol campus reserve account.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5931-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2043%20§%20256[2011 1st sp.s. c 43 § 256]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5084-S.SL.pdf?cite=1995%20c%20215%20§%206[1995 c 215 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c14.pdf?cite=1989%201st%20ex.s.%20c%2014%20§%207[1989 1st ex.s. c 14 § 7]; ]

== 43.99H.080 - 1989-1991 Fiscal biennium general obligation bonds for capital and operating appropriations act—Additional means for payment of principal and interest.
The legislature may provide additional means for raising moneys for the payment of the principal and interest on the bonds authorized in RCW 43.99H.010. RCW 43.99H.030 and 43.99H.040 shall not be deemed to provide an exclusive method for the payment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c15.pdf?cite=1990%201st%20ex.s.%20c%2015%20§%203[1990 1st ex.s. c 15 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c14.pdf?cite=1989%201st%20ex.s.%20c%2014%20§%208[1989 1st ex.s. c 14 § 8]; ]

== 43.99H.090 - 1989-1991 Fiscal biennium general obligation bonds for capital and operating appropriations act—Legal investment.
The bonds authorized in RCW 43.99H.010 shall be a legal investment for all state funds or funds under state control and for all funds of any other public body.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c14.pdf?cite=1989%201st%20ex.s.%20c%2014%20§%209[1989 1st ex.s. c 14 § 9]; ]

== 43.99H.100 - Expiration of authority to issue bonds.
If any bonds authorized in this chapter have not been issued by June 30, 2018, the authority of the state finance committee to issue such remaining unissued bonds expires June 30, 2018.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1080-S2.SL.pdf?cite=2018%20c%203%20§%20303[2018 c 3 § 303]; ]

== 43.99H.901 - Effective dates—1989 1st ex.s. c 14.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and shall take effect July 1, 1989, except for section 18 of this act which shall take effect immediately [June 1, 1989].

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c14.pdf?cite=1989%201st%20ex.s.%20c%2014%20§%2028[1989 1st ex.s. c 14 § 28]; ]

