= 43.46 - Arts commission.
:toc:

== 43.46.005 - Purpose.
The conservation and development of the state's artistic resources is essential to the social, educational, and economic growth of the state of Washington. Artists, works of art, and artistic institutions contribute to the quality of life and the general welfare of the citizens of the state, and are an appropriate matter of concern to the government of the state of Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c317.pdf?cite=1985%20c%20317%20§%201[1985 c 317 § 1]; ]

== 43.46.015 - Washington state arts commission established—Composition.
There is established a Washington state arts commission. The commission consists of nineteen members appointed by the governor and four members of the legislature, one from each caucus in the senate and appointed by the president of the senate and one from each caucus in the house of representatives and appointed by the speaker of the house of representatives. The governor shall appoint citizens representing the various disciplines within the visual, performing and literary arts, and other citizens active in the arts community. The governor shall consider nominations for membership from individuals actively involved in cultural, state or community organizations. The governor shall also consider geographical distribution of the membership in the appointment of new members.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2207.SL.pdf?cite=1999%20c%20241%20§%201[1999 c 241 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c317.pdf?cite=1985%20c%20317%20§%202[1985 c 317 § 2]; ]

== 43.46.030 - Terms—Vacancies.
Members shall serve three year terms. A legislative member shall serve as long as he or she is a member of the legislative body from which he or she was appointed. Each member will continue to serve until a successor is appointed. Vacancies shall be filled by appointment for the remainder of the unexpired term.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c317.pdf?cite=1985%20c%20317%20§%203[1985 c 317 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c125.pdf?cite=1967%20ex.s.%20c%20125%20§%204[1967 ex.s. c 125 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.46.030[1965 c 8 § 43.46.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c301.pdf?cite=1961%20c%20301%20§%203[1961 c 301 § 3]; ]

== 43.46.040 - Compensation—Travel expenses—Organization—Chairperson—Rules—Quorum.
Members of the commission shall serve without compensation. However, nonlegislative members shall be reimbursed for travel expenses as provided in RCW 43.03.050 and 43.03.060 and legislative members shall be reimbursed as provided in RCW 44.04.120. The commission shall organize, elect a chairperson annually, and adopt rules pursuant to chapter 34.05 RCW. A majority of its members constitute a quorum. Any action as defined in RCW 42.30.020(3) shall be taken only at a meeting at which a quorum is present.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c317.pdf?cite=1985%20c%20317%20§%204[1985 c 317 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.46.040[1965 c 8 § 43.46.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c301.pdf?cite=1961%20c%20301%20§%204[1961 c 301 § 4]; ]

== 43.46.045 - Executive director—Employees.
The governor shall select a full time executive director from a list of three names submitted by the commission by September 1, 1988, and anytime thereafter that a vacancy occurs. The executive director shall receive no other salary and shall not be otherwise gainfully employed. Subject to the provisions of chapter 41.06 RCW, the executive director may also employ such clerical and other assistants as may be reasonably required to carry out commission functions. The executive director shall serve at the pleasure of the governor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c81.pdf?cite=1988%20c%2081%20§%2023[1988 c 81 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c317.pdf?cite=1985%20c%20317%20§%205[1985 c 317 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c125.pdf?cite=1967%20ex.s.%20c%20125%20§%202[1967 ex.s. c 125 § 2]; ]

== 43.46.050 - Powers and duties generally.
The commission shall meet, study, plan, and advise the governor, the various departments of the state and the state legislature and shall make such recommendations as it deems proper for the cultural development of the state of Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c317.pdf?cite=1985%20c%20317%20§%206[1985 c 317 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.46.050[1965 c 8 § 43.46.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c301.pdf?cite=1961%20c%20301%20§%205[1961 c 301 § 5]; ]

== 43.46.055 - Development of arts and humanities.
The commission may develop, sponsor, promote and administer any activity, project, or program within or without this state which is related to the growth and development of the arts and humanities in the state of Washington and may assist any person or public or private agency to this end.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c317.pdf?cite=1985%20c%20317%20§%207[1985 c 317 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c125.pdf?cite=1967%20ex.s.%20c%20125%20§%201[1967 ex.s. c 125 § 1]; ]

== 43.46.060 - Gifts and grants.
The commission may accept gifts and grants upon such terms as the commission shall deem proper.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.46.060[1965 c 8 § 43.46.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c301.pdf?cite=1961%20c%20301%20§%206[1961 c 301 § 6]; ]

== 43.46.070 - Biennial report.
The commission shall make a biennial report of its proceedings and recommendations to the governor, which shall contain a full description of program and project activity, including fund sources and expenditures for the biennium covered by the report.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c317.pdf?cite=1985%20c%20317%20§%208[1985 c 317 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.46.070[1965 c 8 § 43.46.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c301.pdf?cite=1961%20c%20301%20§%207[1961 c 301 § 7]; ]

== 43.46.081 - Poet laureate program.
. The Washington state arts commission shall establish and administer the poet laureate program. The poet laureate shall engage in activities to promote and encourage poetry within the state, including but not limited to readings, workshops, lectures, or presentations for Washington educational institutions and communities in geographically diverse areas over a two-year term.

. Selection of a poet laureate shall be made by a committee appointed and coordinated by the commission. The committee may include representatives of the Washington state library, the education community, the Washington commission for the humanities, publishing, and the community of Washington poets.

. The commission and the committee shall establish criteria to be used for the selection of a poet laureate. In addition to other criteria established, the poet laureate must be a published poet, a resident of Washington state, active in the poetry community, and willing and able to promote poetry in the state of Washington throughout the two-year term.

. The recommendation of the poet laureate selection committee shall be forwarded to the commission, which shall appoint the poet laureate with the approval of the governor.

. The poet laureate shall receive compensation at a level determined by the commission. Travel expenses shall be provided in accordance with RCW 43.03.050 and 43.03.060.

. The poet laureate may not serve more than two consecutive two-year terms.

. The commission shall fund the poet laureate program through gifts, grants, or endowments from public or private sources that are made from time to time, in trust or otherwise.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1279-S.SL.pdf?cite=2007%20c%20128%20§%202[2007 c 128 § 2]; ]

== 43.46.085 - Poet laureate account.
The poet laureate account is created in the custody of the state treasurer. All receipts from gifts, grants, or endowments from public or private sources must be deposited into the account. Expenditures from the account may only be used for the poet laureate program. Only the executive director of the commission or the executive director's designee may authorize expenditures from the account. The account is subject to allotment procedures under chapter 43.88 RCW, but an appropriation is not required for expenditures.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1279-S.SL.pdf?cite=2007%20c%20128%20§%203[2007 c 128 § 3]; ]

== 43.46.090 - Commission as reflecting state's responsibility—Acquisition of works of art for public buildings and lands—Visual arts program established.
The legislature recognizes this state's responsibility to foster culture and the arts and its interest in the viable development of the state's artists by the establishment of the Washington state arts commission. The legislature declares it to be a policy of this state that a portion of appropriations for capital expenditures be set aside for the acquisition of works of art to be placed in public buildings or lands. There is hereby established a visual arts program to be administered by the Washington state arts commission.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%205134[2009 c 549 § 5134]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c204.pdf?cite=1983%20c%20204%20§%201[1983 c 204 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c176.pdf?cite=1974%20ex.s.%20c%20176%20§%201[1974 ex.s. c 176 § 1]; ]

== 43.46.095 - State art collection.
All works of art purchased and commissioned under the visual arts program shall become a part of a state art collection developed, administered, and operated by the Washington state arts commission. All works of art previously purchased or commissioned under RCW 43.46.090, 43.17.200, 43.19.455, 28B.10.025, or 28A.335.210 shall be considered a part of the state art collection to be administered by the Washington state arts commission.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20578[1990 c 33 § 578]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c204.pdf?cite=1983%20c%20204%20§%202[1983 c 204 § 2]; ]

== 43.46.100 - Creative districts—Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Commission" means the Washington state arts commission.

. "Coordinator" means the employee of the Washington state arts commission who is responsible for performing the specific tasks under RCW 43.46.115.

. "Creative district" means a land area designated by a local government in accordance with RCW 43.46.105 that contains either a hub of cultural facilities, creative industries, or arts-related businesses, or multiple vacant properties in close proximity that would be suitable for redevelopment as a creative district.

. "Local government" means a city, county, or town.

. "State-certified creative district" means a creative district whose application for certification has been approved by the commission.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1183-S.SL.pdf?cite=2017%20c%20240%20§%202[2017 c 240 § 2]; ]

== 43.46.105 - Creative districts—Designation—Certification.
. A local government may designate a creative district within its territorial boundaries subject to certification as a state-certified creative district by the commission. Two or more local governments may jointly apply for certification of a creative district that extends across a common boundary.

. In order to receive certification as a state-certified creative district, a creative district must:

.. Be a geographically contiguous area;

.. Be distinguished by physical, artistic, or cultural resources that play a vital role in the quality and life of a community, including its economic and cultural development;

.. Be the site of a concentration of artistic or cultural activity, a major arts or cultural institution or facility, arts and entertainment businesses, an area with arts and cultural activities, or artistic or cultural production;

.. Be engaged in the promotional, preservation, and educational aspects of the arts and culture of the community and contribute to the public through interpretive, educational, or recreational uses; and

.. Satisfy any additional criteria required by the commission that in its discretion will further the purposes of RCW 43.46.100 through 43.46.115. Any additional eligibility criteria must be posted by the commission on its public website.

. The commission may grant certification to a creative district that does not qualify for certification under subsection (2) of this section if the land area proposed for certification contains multiple vacant properties in close proximity that would be suitable, as determined by the commission, for redevelopment as a creative district.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1183-S.SL.pdf?cite=2017%20c%20240%20§%203[2017 c 240 § 3]; ]

== 43.46.110 - Creative districts—Applications for certification—Review—Approval, rejection, revocation—Additional powers of commission.
. Subject to the availability of amounts appropriated for this specific purpose, the commission may create a process for review of applications submitted by local governments or federally recognized Indian tribes for certification of state-certified creative districts. The application must be submitted on a standard form developed and approved by the commission.

. After reviewing an application for certification, the commission must approve or reject the application or return it to the applicant with a request for changes or additional information. The commission may request that an applicant provide relevant information supporting an application. Rejected applicants may reapply at any time in coordination with program guidelines.

. Certification must be based upon the criteria specified in RCW 43.46.105.

. If the commission approves an application for certification, it must notify the applicant in writing and must specify the terms and conditions of the commission's approval, including the terms and conditions set forth in the application and as modified by written agreement between the applicant and the commission.

. Upon approval by the commission of an application for certification, a creative district becomes a state-certified creative district with all of the attendant benefits under RCW 43.46.100 through 43.46.115.

. The commission may revoke a certification previously granted for failure by a local government to comply with the requirements of this section or an agreement executed pursuant to this section.

. In addition to any powers explicitly granted to the commission under RCW 43.46.100 through 43.46.115, the commission is granted such additional powers as are necessary to carry out the purposes of RCW 43.46.100 through 43.46.115. Where authorized by law, such powers may include offering incentives to state-certified creative districts to encourage business development, exploring new incentives that are directly related to creative enterprises, facilitating local access to state economic development assistance, enhancing the visibility of state-certified creative districts, providing state-certified creative districts with technical assistance and planning aid, ensuring broad and equitable program benefits, and fostering a supportive climate for the arts and culture within the state.

. The creation of a district under this section may not be used to prohibit any particular business or the development of residential real property within the boundaries of the district or to impose a burden on the operation or use of any particular business or parcel of residential real property located within the boundaries of the district.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1183-S.SL.pdf?cite=2017%20c%20240%20§%204[2017 c 240 § 4]; ]

== 43.46.115 - Creative districts—Coordinator.
Subject to the availability of amounts appropriated for this specific purpose, the commission may appoint a coordinator. The coordinator must:

. Review applications for certification and make a recommendation to the commission for action;

. Administer and promote the application process for the certification of creative districts;

. With the approval of the commission, develop standards and policies for the certification of state-certified creative districts. Any approved standards and policies must be posted on the commission's public website;

. Require periodic written reports from any state-certified creative district for the purpose of reviewing the activities of the district, including the compliance of the district with the policies and standards developed under this section and with the conditions of an approved application for certification;

. Identify available public and private resources, including any applicable economic development incentives and other tools, that support and enhance the development and maintenance of creative districts and, with the assistance of the commission, ensure that such programs and services are accessible to creative districts; and

. With the approval of the commission, develop such additional procedures as may be necessary to administer this section. Any approved procedures must be posted on the commission's public website.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1183-S.SL.pdf?cite=2017%20c%20240%20§%205[2017 c 240 § 5]; ]

== 43.46.900 - Effective date—1985 c 317.
This act is necessary for the immediate preservation of the public peace, health, and safety, the support of the state government and its existing public institutions, and shall take effect June 30, 1985.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c317.pdf?cite=1985%20c%20317%20§%2010[1985 c 317 § 10]; ]

