= 43.06B - Office of the education ombuds.
:toc:

== 43.06B.010 - Office created—Purposes—Appointment—Regional education ombuds.
. There is hereby created the office of the education ombuds within the office of the governor for the purposes of providing information to parents, students, and others regarding their rights and responsibilities with respect to the state's public elementary and secondary education system, and advocating on behalf of elementary and secondary students.

. [Empty]
.. The governor shall appoint an ombuds who shall be a person of recognized judgment, independence, objectivity, and integrity and shall be qualified by training or experience or both in the following areas:

... Public education law and policy in this state;

... Dispute resolution or problem resolution techniques, including mediation and negotiation; and

... Community outreach.

.. The education ombuds may not be an employee of any school district, the office of the superintendent of public instruction, or the state board of education while serving as an education ombuds.

. Before the appointment of the education ombuds, the governor shall share information regarding the appointment to a six-person legislative committee appointed and comprised as follows:

.. The committee shall consist of three senators and three members of the house of representatives from the legislature.

.. The senate members of the committee shall be appointed by the president of the senate. Two members shall represent the majority caucus and one member the minority caucus.

.. The house of representatives members of the committee shall be appointed by the speaker of the house of representatives. Two members shall represent the majority caucus and one member the minority caucus.

. If sufficient appropriations are provided, the education ombuds shall delegate and certify regional education ombuds. The education ombuds shall ensure that the regional ombuds selected are appropriate to the community in which they serve and hold the same qualifications as in subsection (2)(a) of this section. The education ombuds may not contract with the superintendent of public instruction, or any school, school district, or current employee of a school, school district, or the office of the superintendent of public instruction for the provision of regional ombuds services.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%2082[2013 c 23 § 82]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3127-S.SL.pdf?cite=2006%20c%20116%20§%203[2006 c 116 § 3]; ]

== 43.06B.020 - Powers and duties.
The education ombuds shall have the following powers and duties:

. To develop parental involvement materials, including instructional guides developed to inform parents of the essential academic learning requirements required by the superintendent of public instruction. The instructional guides also shall contain actions parents may take to assist their children in meeting the requirements, and should focus on reaching parents who have not previously been involved with their children's education;

. To provide information to students, parents, and interested members of the public regarding this state's public elementary and secondary education system;

. To identify obstacles to greater parent and community involvement in school shared decision-making processes and recommend strategies for helping parents and community members to participate effectively in school shared decision-making processes, including understanding and respecting the roles of school building administrators and staff;

. To identify and recommend strategies for improving the success rates of ethnic and racial student groups and students with disabilities, with disproportionate academic achievement;

. To refer complainants and others to appropriate resources, agencies, or departments;

. To facilitate the resolution of complaints made by parents and students with regard to the state's public elementary and secondary education system;

. To perform such other functions consistent with the purpose of the education ombuds; and

. To consult with representatives of the following organizations and groups regarding the work of the office of the education ombuds, including but not limited to:

.. The state parent teacher association;

.. Certificated and classified school employees;

.. School and school district administrators;

.. Parents of special education students;

.. Parents of English language learners;

.. The Washington state commission on Hispanic affairs;

.. The Washington state commission on African American affairs;

.. The Washington state commission on Asian Pacific American affairs; and

.. The governor's office of Indian affairs.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%2083[2013 c 23 § 83]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3212-S.SL.pdf?cite=2008%20c%20165%20§%202[2008 c 165 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3127-S.SL.pdf?cite=2006%20c%20116%20§%204[2006 c 116 § 4]; ]

== 43.06B.030 - Liability for good faith performance—Privileged communications.
. Neither the education ombuds nor any regional educational ombuds are liable for good faith performance of responsibilities under this chapter.

. No discriminatory, disciplinary, or retaliatory action may be taken against any student or employee of any school district, the office of the superintendent of public instruction, or the state board of education, for any communication made, or information given or disclosed, to aid the education ombuds in carrying out his or her duties and responsibilities, unless the same was done without good faith or maliciously. This subsection is not intended to infringe upon the rights of a school district to supervise, discipline, or terminate an employee for other reasons or to discipline a student for other reasons.

. All communications by the education ombuds or the ombuds's staff or designee, if reasonably related to the education ombuds's duties and responsibilities and done in good faith, are privileged and that privilege shall serve as a defense to any action in libel or slander.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%2084[2013 c 23 § 84]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3127-S.SL.pdf?cite=2006%20c%20116%20§%205[2006 c 116 § 5]; ]

== 43.06B.040 - Confidentiality.
The education ombuds shall treat all matters, including the identities of students, complainants, and individuals from whom information is acquired, as confidential, except as necessary to enable the education ombuds to perform the duties of the office. Upon receipt of information that by law is confidential or privileged, the ombuds shall maintain the confidentiality of such information and shall not further disclose or disseminate the information except as provided by applicable state or federal law.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%2085[2013 c 23 § 85]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3127-S.SL.pdf?cite=2006%20c%20116%20§%206[2006 c 116 § 6]; ]

== 43.06B.050 - Annual reports.
The education ombuds shall report on the work and accomplishment of the office and advise and make recommendations to the governor, the legislature, and the state board of education annually. The initial report to the governor, the legislature, and the state board of education shall be made by September 1, 2007, and there shall be annual reports by September 1st each year thereafter. The annual reports shall provide at least the following information:

. How the education ombuds's services have been used and by whom;

. Methods for the education ombuds to increase and enhance family and community involvement in public education;

. Recommendations to eliminate barriers and obstacles to meaningful family and community involvement in public education; and

. Strategies to improve the educational opportunities for all students in the state, including recommendations from organizations and groups provided in RCW 43.06B.020(8).

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%2086[2013 c 23 § 86]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3127-S.SL.pdf?cite=2006%20c%20116%20§%207[2006 c 116 § 7]; ]

== 43.06B.060 - Public school antiharassment policies and strategies—Lead agency.
In addition to duties assigned under RCW 43.06B.020, the office of the education ombuds shall serve as the lead agency to provide resources and tools to parents and families about public school antiharassment policies and strategies.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%2087[2013 c 23 § 87]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2801-S.SL.pdf?cite=2010%20c%20239%20§%203[2010 c 239 § 3]; ]

== 43.06B.900 - Findings—Intent—2006 c 116.
See note following RCW 28A.300.130.

[ ]

