= 43.99R - Financing for appropriations—2003-2005 biennium.
:toc:

== 43.99R.010 - General obligation bonds for capital and operating appropriations act.
For the purpose of providing funds to finance the projects described and authorized by the legislature in the capital and operating appropriation acts for the 2003-2005 fiscal biennium, and all costs incidental thereto, the state finance committee is authorized to issue general obligation bonds of the state of Washington in the sum of one billion two hundred twelve million dollars, or as much thereof as may be required, to finance these projects and all costs incidental thereto. Bonds authorized in this section may be sold at such price as the state finance committee shall determine. No bonds authorized in this section may be offered for sale without prior legislative appropriation of the net proceeds of the sale of the bonds.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1288-S.SL.pdf?cite=2003%201st%20sp.s.%20c%203%20§%201[2003 1st sp.s. c 3 § 1]; ]

== 43.99R.020 - Conditions and limitations.
The proceeds from the sale of the bonds authorized in RCW 43.99R.010 shall be deposited in the state building construction account created by RCW 43.83.020. The proceeds shall be transferred as follows:

. One billion fifty-one million dollars to remain in the state building construction account created by RCW 43.83.020;

. Twenty-two million five hundred thousand dollars to the outdoor recreation account created by RCW 79A.25.060;

. Twenty-two million five hundred thousand dollars to the habitat conservation account created by RCW 79A.15.020;

. Eighty million dollars to the state taxable building construction account. All receipts from taxable bond issues are to be deposited into the account. If the state finance committee deems it necessary to issue more than the amount specified in this subsection (4) as taxable bonds in order to comply with federal internal revenue service rules and regulations pertaining to the use of nontaxable bond proceeds, the proceeds of such additional taxable bonds shall be transferred to the state taxable building construction account in lieu of any transfer otherwise provided by this section. The state treasurer shall submit written notice to the director of financial management if it is determined that any such additional transfer to the state taxable building construction account is necessary. Moneys in the account may be spent only after appropriation.

These proceeds shall be used exclusively for the purposes specified in this section and for the payment of expenses incurred in the issuance and sale of the bonds issued for the purposes of this section, and shall be administered by the office of financial management subject to legislative appropriation.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1288-S.SL.pdf?cite=2003%201st%20sp.s.%20c%203%20§%202[2003 1st sp.s. c 3 § 2]; ]

== 43.99R.030 - Retirement of bonds—Reimbursement of general fund from debt-limit general fund bond retirement account.
. The debt-limit general fund bond retirement account shall be used for the payment of the principal of and interest on the bonds authorized in RCW 43.99R.020 (1), (2), (3), and (4).

. The state finance committee shall, on or before June 30th of each year, certify to the state treasurer the amount needed in the ensuing twelve months to meet the bond retirement and interest requirements on the bonds authorized in RCW 43.99R.020 (1), (2), (3), and (4).

. On each date on which any interest or principal and interest payment is due on bonds issued for the purposes of RCW 43.99R.020 (1), (2), (3), and (4) the state treasurer shall withdraw from any general state revenues received in the state treasury and deposit in the debt-limit general fund bond retirement account an amount equal to the amount certified by the state finance committee to be due on the payment date.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1288-S.SL.pdf?cite=2003%201st%20sp.s.%20c%203%20§%203[2003 1st sp.s. c 3 § 3]; ]

== 43.99R.040 - Pledge and promise—Remedies.
. Bonds issued under RCW 43.99R.010 through 43.99R.030 shall state that they are a general obligation of the state of Washington, shall pledge the full faith and credit of the state to the payment of the principal thereof and the interest thereon, and shall contain an unconditional promise to pay the principal and interest as the same shall become due.

. The owner and holder of each of the bonds or the trustee for the owner and holder of any of the bonds may by mandamus or other appropriate proceeding require the transfer and payment of funds as directed in this section.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1288-S.SL.pdf?cite=2003%201st%20sp.s.%20c%203%20§%204[2003 1st sp.s. c 3 § 4]; ]

== 43.99R.050 - Payment of principal and interest—Additional means for raising money authorized.
The legislature may provide additional means for raising moneys for the payment of the principal of and interest on the bonds authorized in RCW 43.99R.010, and RCW 43.99R.020 and 43.99R.030 shall not be deemed to provide an exclusive method for the payment.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1288-S.SL.pdf?cite=2003%201st%20sp.s.%20c%203%20§%205[2003 1st sp.s. c 3 § 5]; ]

== 43.99R.901 - Effective date—2003 1st sp.s. c 3.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and takes effect immediately [June 20, 2003].

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1288-S.SL.pdf?cite=2003%201st%20sp.s.%20c%203%20§%208[2003 1st sp.s. c 3 § 8]; ]

