= 43.99T - Financing for appropriations—2007-2009 biennium.
:toc:

== 43.99T.010 - General obligation bonds for capital and operating appropriations acts.
For the purpose of providing funds to finance the projects described and authorized by the legislature in the capital and operating appropriations acts for the 2005-2007 and 2007-2009 fiscal bienniums, and all costs incidental thereto, the state finance committee is authorized to issue general obligation bonds of the state of Washington in the sum of one billion nine hundred seventy-two million dollars, or as much thereof as may be required, to finance these projects and all costs incidental thereto. Bonds authorized in this section may be sold at such price as the state finance committee shall determine. No bonds authorized in this section may be offered for sale without prior legislative appropriation of the net proceeds of the sale of the bonds.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1138-S.SL.pdf?cite=2007%20c%20521%20§%201[2007 c 521 § 1]; ]

== 43.99T.020 - Conditions and limitations.
The proceeds from the sale of the bonds authorized in RCW 43.99T.010 shall be deposited in the state building construction account created by RCW 43.83.020. The proceeds shall be transferred as follows:

. One billion six hundred ninety-three million dollars to remain in the state building construction account created by RCW 43.83.020;

. Thirty-six million dollars to the outdoor recreation account created by RCW 79A.25.060;

. Thirty-six million dollars to the habitat conservation account created by RCW 79A.15.020;

. Nineteen million dollars to the riparian protection account created by RCW 79A.15.120;

. Nine million dollars to the farmlands preservation account created by *RCW 79A.15.130;

. One hundred forty million dollars to the state taxable building construction account. All receipts from taxable bond issues are to be deposited into the account. If the state finance committee deems it necessary to issue more than the amount specified in this subsection (6) as taxable bonds in order to comply with federal internal revenue service rules and regulations pertaining to the use of nontaxable bond proceeds, the proceeds of such additional taxable bonds shall be transferred to the state taxable building construction account in lieu of any transfer otherwise provided by this section. The state treasurer shall submit written notice to the director of financial management if it is determined that any such additional transfer to the state taxable building construction account is necessary. Moneys in the account may be spent only after appropriation.

These proceeds shall be used exclusively for the purposes specified in this section and for the payment of expenses incurred in the issuance and sale of the bonds issued for the purposes of this section, and shall be administered by the office of financial management subject to legislative appropriation.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1138-S.SL.pdf?cite=2007%20c%20521%20§%202[2007 c 521 § 2]; ]

== 43.99T.030 - Retirement of bonds—Reimbursement of general fund from debt-limit general fund bond retirement account.
. The debt-limit general fund bond retirement account shall be used for the payment of the principal of and interest on the bonds authorized in RCW 43.99T.020 (1), (2), (3), (4), (5), and (6).

. The state finance committee shall, on or before June 30th of each year, certify to the state treasurer the amount needed in the ensuing twelve months to meet the bond retirement and interest requirements on the bonds authorized in RCW 43.99T.020 (1), (2), (3), (4), (5), and (6).

. On each date on which any interest or principal and interest payment is due on bonds issued for the purposes of RCW 43.99T.020 (1), (2), (3), (4), (5), and (6) the state treasurer shall withdraw from any general state revenues received in the state treasury and deposit in the debt-limit general fund bond retirement account an amount equal to the amount certified by the state finance committee to be due on the payment date.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1138-S.SL.pdf?cite=2007%20c%20521%20§%203[2007 c 521 § 3]; ]

== 43.99T.040 - Pledge and promise—Remedies.
. Bonds issued under RCW 43.99T.010 through 43.99T.030 shall state that they are a general obligation of the state of Washington, shall pledge the full faith and credit of the state to the payment of the principal thereof and the interest thereon, and shall contain an unconditional promise to pay the principal and interest as the same shall become due.

. The owner and holder of each of the bonds or the trustee for the owner and holder of any of the bonds may by mandamus or other appropriate proceeding require the transfer and payment of funds as directed in this section.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1138-S.SL.pdf?cite=2007%20c%20521%20§%204[2007 c 521 § 4]; ]

== 43.99T.050 - Payment of principal and interest—Additional means for raising money authorized.
The legislature may provide additional means for raising moneys for the payment of the principal of and interest on the bonds authorized in RCW 43.99T.010, and RCW 43.99T.020 and 43.99T.030 shall not be deemed to provide an exclusive method for the payment.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1138-S.SL.pdf?cite=2007%20c%20521%20§%205[2007 c 521 § 5]; ]

== 43.99T.901 - Effective date—2007 c 521.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and takes effect immediately [May 15, 2007].

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1138-S.SL.pdf?cite=2007%20c%20521%20§%208[2007 c 521 § 8]; ]

