= 43.99L - Financing for appropriations—1997-1999 biennium.
:toc:

== 43.99L.010 - General obligation bonds for capital and operating appropriations acts.
For the purpose of providing funds to finance the projects described and authorized by the legislature in the capital and operating appropriations acts for the 1997-99 fiscal biennium only, and all costs incidental thereto, the state finance committee is authorized to issue general obligation bonds of the state of Washington in the sum of nine hundred eighty-nine million dollars, or as much thereof as may be required, to finance these projects and all costs incidental thereto. Bonds authorized in this section may be sold at such price as the state finance committee shall determine. No bonds authorized in this section may be offered for sale without prior legislative appropriation of the net proceeds of the sale of the bonds.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6064-S.SL.pdf?cite=1997%20c%20456%20§%201[1997 c 456 § 1]; ]

== 43.99L.020 - Conditions and limitations.
The proceeds from the sale of the bonds authorized in RCW 43.99L.010 shall be deposited in the state building construction account created by RCW 43.83.020. The proceeds shall be transferred as follows:

. Nine hundred fifteen million dollars to remain in the state building construction account created by RCW 43.83.020;

. One million six hundred thousand dollars to the public safety reimbursable bond account; and

. Forty-four million three hundred thousand dollars to the higher education construction account created by RCW 43.83.310.

These proceeds shall be used exclusively for the purposes specified in this section and for the payment of expenses incurred in the issuance and sale of the bonds issued for the purposes of this section, and shall be administered by the office of financial management subject to legislative appropriation.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1859.SL.pdf?cite=2015%201st%20sp.s.%20c%204%20§%2045[2015 1st sp.s. c 4 § 45]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6064-S.SL.pdf?cite=1997%20c%20456%20§%202[1997 c 456 § 2]; ]

== 43.99L.030 - Retirement of bonds—Reimbursement of general fund from debt-limit general fund bond retirement account.
. The debt-limit general fund bond retirement account shall be used for the payment of the principal of and interest on the bonds authorized in RCW 43.99L.020(1).

. The state finance committee shall, on or before June 30th of each year, certify to the state treasurer the amount needed in the ensuing twelve months to meet the bond retirement and interest requirements on the bonds authorized in RCW 43.99L.020(1).

. On each date on which any interest or principal and interest payment is due on bonds issued for the purpose of RCW 43.99L.020(1), the state treasurer shall withdraw from any general state revenues received in the state treasury and deposit in the debt-limit general fund bond retirement account an amount equal to the amount certified by the state finance committee to be due on the payment date.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6064-S.SL.pdf?cite=1997%20c%20456%20§%203[1997 c 456 § 3]; ]

== 43.99L.040 - Retirement of bonds—Reimbursement of general fund from debt-limit reimbursable bond retirement account.
. The debt-limit reimbursable bond retirement account shall be used for the payment of the principal of and interest on the bonds authorized in RCW 43.99L.020(2).

. The state finance committee shall, on or before June 30th of each year, certify to the state treasurer the amount needed in the ensuing twelve months to meet the bond retirement and interest requirements on the bonds authorized in RCW 43.99L.020(2).

. On each date on which any interest or principal and interest payment is due on bonds issued for the purpose of RCW 43.99L.020(2), the state treasurer shall transfer from the state general fund to the debt-limit reimbursable bond retirement account the amount computed in subsection (2) of this section for the bonds issued for the purpose of RCW 43.99L.020(2).

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5073-S.SL.pdf?cite=2009%20c%20479%20§%2034[2009 c 479 § 34]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6064-S.SL.pdf?cite=1997%20c%20456%20§%204[1997 c 456 § 4]; ]

== 43.99L.050 - Retirement of bonds—Reimbursement of general fund from nondebt-limit reimbursable bond retirement account.
. The nondebt-limit reimbursable bond retirement account shall be used for the payment of the principal of and interest on the bonds authorized in RCW 43.99L.020(3).

. The state finance committee shall, on or before June 30th of each year, certify to the state treasurer the amount needed in the ensuing twelve months to meet the bond retirement and interest requirements on the bonds authorized in RCW 43.99L.020(3).

. On each date on which any interest or principal and interest payment is due on bonds issued for the purposes of RCW 43.99L.020(3), the board of regents of the University of Washington shall cause to be paid out of University of Washington nonappropriated local funds to the state treasurer for deposit into the nondebt-limit reimbursable bond retirement account the amount computed in subsection (2) of this section for bonds issued for the purposes of RCW 43.99L.020(3).

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6064-S.SL.pdf?cite=1997%20c%20456%20§%205[1997 c 456 § 5]; ]

== 43.99L.060 - Pledge and promise—Remedies.
. Bonds issued under RCW 43.99L.010 through 43.99L.050 shall state that they are a general obligation of the state of Washington, shall pledge the full faith and credit of the state to the payment of the principal thereof and the interest thereon, and shall contain an unconditional promise to pay the principal and interest as the same shall become due.

. The owner and holder of each of the bonds or the trustee for the owner and holder of any of the bonds may by mandamus or other appropriate proceeding require the transfer and payment of funds as directed in this section.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6064-S.SL.pdf?cite=1997%20c%20456%20§%206[1997 c 456 § 6]; ]

== 43.99L.070 - Payment of principal and interest—Additional means for raising moneys authorized.
The legislature may provide additional means for raising moneys for the payment of the principal of and interest on the bonds authorized in RCW 43.99L.010, and RCW 43.99L.030 through 43.99L.050 shall not be deemed to provide an exclusive method for the payment.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6064-S.SL.pdf?cite=1997%20c%20456%20§%207[1997 c 456 § 7]; ]

== 43.99L.080 - Legal investment.
The bonds authorized in RCW 43.99L.010 shall be a legal investment for all state funds or funds under state control and for all funds of any other public body.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6064-S.SL.pdf?cite=1997%20c%20456%20§%208[1997 c 456 § 8]; ]

