= 43.44 - State fire protection.
:toc:

== 43.44.010 - Examination of premises.
. The chief of the Washington state patrol, through the director of fire protection or his or her authorized deputy, shall have authority at all times of day and night, in the performance of duties imposed by this chapter, to enter upon and examine any building or premises where any fire has occurred and other buildings and premises adjoining or near thereto.

. The chief of the Washington state patrol, through the director of fire protection or his or her authorized deputy, shall have authority at any reasonable hour to enter into any public building or premises or any building or premises used for public purposes to inspect for fire hazards.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2025[1995 c 369 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2067[1986 c 266 § 67]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c470.pdf?cite=1985%20c%20470%20§%2017[1985 c 470 § 17]; 1947 c 79 § .33.03; Rem. Supp. 1947 § 45.33.03; ]

== 43.44.020 - Standards of safety.
. The chief of the Washington state patrol, through the director of fire protection or his or her authorized deputy, shall have authority to enter upon all premises and into all buildings except private dwellings for the purpose of inspection to ascertain if any fire hazard exists, and to require conformance with minimum standards for the prevention of fire and for the protection of life and property against fire and panic as to use of premises, and may adopt by reference nationally recognized standards applicable to local conditions.

. The chief of the Washington state patrol, through the director of fire protection or his or her authorized deputy, may, upon request by the chief fire official or the local governing body or of taxpayers of such area, assist in the enforcement of any such code.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2026[1995 c 369 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2068[1986 c 266 § 68]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c470.pdf?cite=1985%20c%20470%20§%2018[1985 c 470 § 18]; 1947 c 79 § .33.04; Rem. Supp. 1947 § 45.33.04; ]

== 43.44.030 - Schools—Compliance with standards for fire prevention and safety—Plan reviews and construction inspections.
The director of fire protection shall make or cause to be made plan reviews and construction inspections for all E-1 occupancies as may be necessary to insure compliance with the state building code and standards for schools adopted under chapter 19.27 RCW. Nothing in this section prohibits the director of fire protection from delegating construction inspection authority to any local jurisdiction.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2617-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%207%20§%2049[2010 1st sp.s. c 7 § 49]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5261-S.SL.pdf?cite=1991%20c%20170%20§%202[1991 c 170 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2069[1986 c 266 § 69]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c470.pdf?cite=1985%20c%20470%20§%2019[1985 c 470 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c198.pdf?cite=1981%20c%20198%20§%203[1981 c 198 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c70.pdf?cite=1972%20ex.s.%20c%2070%20§%201[1972 ex.s. c 70 § 1]; ]

== 43.44.040 - Removal of fire hazards—Appeal of order—Penalty.
. If the chief of the Washington state patrol, through the director of fire protection or his or her authorized deputy, finds in any building or premises subject to their inspection under this chapter, any combustible material or flammable conditions or fire hazards dangerous to the safety of the building, premises, or to the public, he or she shall by written order require such condition to be remedied, and such order shall forthwith be complied with by the owner or occupant of the building or premises.

. An owner or occupant aggrieved by any such order made by the chief of the Washington state patrol, through the director of fire protection or his or her deputy, may appeal such order pursuant to chapter 34.05 RCW. If the order is confirmed, the order shall remain in force and be complied with by the owner or occupant.

. Any owner or occupant failing to comply with any such order not appealed from or with any order so confirmed shall be punishable by a fine of not less than ten dollars nor more than fifty dollars for each day such failure exists.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2027[1995 c 369 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2070[1986 c 266 § 70]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c470.pdf?cite=1985%20c%20470%20§%2020[1985 c 470 § 20]; 1947 c 79 § .33.05; Rem. Supp. 1947 § 45.33.05; ]

== 43.44.050 - Reports and investigation of fires—Police powers.
. The responsibility for investigating the origin, cause, circumstances, and extent of loss of all fires shall be assigned as follows:

.. Within any city or town, the chief of the fire department;

.. Within unincorporated areas of a county, the county fire marshal, or other fire official so designated by the county legislative authority.

. No fire marshal, or other person, may enter the scene of an emergency until permitted by the officer in charge of the emergency incident.

. Nothing shall prevent any city, town, county, or fire protection district, or any combination thereof, from entering into interlocal agreements to meet the responsibility required by this section.

. When any fire investigation indicates that the cause of the fire is determined to be suspicious or criminal in nature, the person responsible for the fire investigation shall immediately report the results of said investigation to the local law enforcement agency and the chief of the Washington state patrol, through the state fire marshal.

. In addition to the responsibility imposed by this section, any law enforcement agency, sheriff, or chief of police may assist in the investigation of the origin, cause, circumstances, and extent of loss of all fires within his or her respective jurisdiction.

. The chief of the Washington state patrol, through the director of fire protection or his or her deputy, may investigate any fire for the purpose of determining its cause, origin, and the extent of the loss. The chief of the Washington state patrol, through the director of fire protection or his or her deputy, shall assist in the investigation of those fires of criminal, suspected, or undetermined cause when requested by the reporting agency. In the investigation of any fire of criminal, suspected, or undetermined cause, the chief of the Washington state patrol and the director of fire protection or his or her deputy, are vested with police powers to enforce the laws of this state. To exercise these powers, authorized deputies must receive prior written authorization from the chief of the Washington state patrol, through the director of fire protection, and shall have completed a course of training prescribed by the Washington state criminal justice training commission.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6403.SL.pdf?cite=1996%20c%20161%20§%201[1996 c 161 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2028[1995 c 369 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2071[1986 c 266 § 71]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c470.pdf?cite=1985%20c%20470%20§%2021[1985 c 470 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c104.pdf?cite=1981%20c%20104%20§%201[1981 c 104 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c181.pdf?cite=1980%20c%20181%20§%201[1980 c 181 § 1]; 1947 c 79 § .33.06; Rem. Supp. 1947 § 45.33.06; ]

== 43.44.060 - Statistical information and reports—National fire incident reporting system.
. The chief of each organized fire department, or the sheriff or other designated county official having jurisdiction over areas not within the jurisdiction of any fire department, shall report statistical information and data to the chief of the Washington state patrol, through the director of fire protection, on each fire occurring within the official's jurisdiction and, within two business days, report any death resulting from fire.

. Reports submitted pursuant to subsection (1) of this section shall be consistent with the national fire incident reporting system developed by the United States fire administration and rules established by the chief of the Washington state patrol, through the director of fire protection. Rules established by the chief of the Washington state patrol, through the director of fire protection, must require fire departments to report data on the age of any structure involved in a fire when that information is available through property records or other methods.

. Subject to availability of amounts appropriated for this specific purpose, the chief of the Washington state patrol, through the director of fire protection, shall administer the national fire incident reporting system including, but not limited to, the following responsibilities:

.. Purchasing equipment, including software, needed for the operation of the reporting system;

.. Establishing procedures, standards, and guidelines pertaining to the statistical information and data reported by fire departments through the reporting system;

.. Providing training and education to fire departments pertaining to the reporting system; and

.. Employing staff to administer the reporting system, as needed.

. The chief of the Washington state patrol, through the director of fire protection, and the department of natural resources shall jointly determine the statistical information to be reported on fires on land under the jurisdiction of the department of natural resources.

. The chief of the Washington state patrol, through the director of fire protection, shall analyze the information and data reported, compile a report, and distribute a copy annually by July 1st to each chief fire official in the state. Upon request, the chief of the Washington state patrol, through the director of fire protection, shall also furnish a copy of the report to any other interested person at cost.

. For purposes of this section, "national fire incident reporting system" or "reporting system" means the national fire incident reporting system or the state equivalent as selected by the chief of the Washington state patrol, through the director of fire protection.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1863-S.SL.pdf?cite=2017%20c%20308%20§%201[2017 c 308 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2617-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%207%20§%2050[2010 1st sp.s. c 7 § 50]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1556.SL.pdf?cite=1999%20c%20231%20§%201[1999 c 231 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2029[1995 c 369 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2072[1986 c 266 § 72]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c470.pdf?cite=1985%20c%20470%20§%2022[1985 c 470 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c181.pdf?cite=1980%20c%20181%20§%202[1980 c 181 § 2]; ]

== 43.44.070 - Examination of witnesses.
In the conduct of any investigation into the cause, origin, or loss resulting from any fire, the chief of the Washington state patrol and the director of fire protection shall have the same power and rights relative to securing the attendance of witnesses and the taking of testimony under oath as is conferred upon the insurance commissioner under RCW 48.03.070. False swearing by any such witness shall be deemed to be perjury and shall be subject to punishment as such.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2030[1995 c 369 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2073[1986 c 266 § 73]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c470.pdf?cite=1985%20c%20470%20§%2023[1985 c 470 § 23]; 1947 c 79 § .33.07; Rem. Supp. 1947 § 45.33.07; ]

== 43.44.080 - Criminal prosecutions.
If as the result of any such investigation, or because of any information received, the chief of the Washington state patrol, through the director of fire protection, is of the opinion that there is evidence sufficient to charge any person with any crime, he or she may cause such person to be arrested and charged with such offense, and shall furnish to the prosecuting attorney of the county in which the offense was committed, the names of witnesses and all pertinent and material evidence and testimony within his or her possession relative to the offense.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2031[1995 c 369 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2074[1986 c 266 § 74]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c470.pdf?cite=1985%20c%20470%20§%2024[1985 c 470 § 24]; 1947 c 79 § .33.08; Rem. Supp. 1947 § 45.33.08; ]

== 43.44.090 - Record of fires.
The chief of the Washington state patrol, through the director of fire protection, shall keep on file all reports of fires made to him or her pursuant to this code. Such records shall at all times during business hours be open to public inspection; except, that any testimony taken in a fire investigation may, in the discretion of the chief of the Washington state patrol, through the director of fire protection, be withheld from public scrutiny. The chief of the Washington state patrol, through the director of fire protection, may destroy any such report after five years from its date.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2032[1995 c 369 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2075[1986 c 266 § 75]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c470.pdf?cite=1985%20c%20470%20§%2025[1985 c 470 § 25]; 1947 c 79 § .33.09; Rem. Supp. 1947 § 45.33.09; ]

== 43.44.110 - Smoke detection devices in dwelling units—Penalties.
. Smoke detection devices shall be installed inside all dwelling units:

.. Occupied by persons other than the owner on and after December 31, 1981;

.. Built or manufactured in this state after December 31, 1980; or

.. Sold on or after July 1, 2019.

. The smoke detection devices shall be designed, manufactured, and installed inside dwelling units in conformance with:

.. Nationally accepted standards; and

.. As provided by the administrative procedure act, chapter 34.05 RCW, rules and regulations promulgated by the chief of the Washington state patrol, through the director of fire protection.

. Installation of smoke detection devices shall be the responsibility of the owner. Maintenance of smoke detection devices, including the replacement of batteries where required for the proper operation of the smoke detection device, shall be the responsibility of the tenant, who shall maintain the device as specified by the manufacturer. At the time of a vacancy, the owner shall insure that the smoke detection device is operational prior to the reoccupancy of the dwelling unit.

. [Empty]
.. For any dwelling unit sold on or after July 1, 2019, that does not have at least one smoke detection device, the seller shall provide at least one smoke detection device in the dwelling unit before the buyer or any other person occupies the dwelling unit following such sale. A violation of this subsection does not affect the transfer of the title, ownership, or possession of the dwelling unit.

.. Real estate brokers licensed under chapter 18.85 RCW are not liable in any civil, administrative, or other proceeding for the failure of any seller or other property owner to comply with the requirements of this section.

.. Any person or entity that assists the buyer of a dwelling [unit] with installing a smoke detection device, whether they are voluntarily doing so or as a nonprofit, is not liable in any civil, administrative, or other proceeding relating to the installation of the smoke detection device.

.. Interconnection of smoke detection devices is not required where not already present in buildings undergoing repairs undertaken solely as a condition of sale.

. [Empty]
.. Except as provided in (b) of this subsection (5), any owner, seller, or tenant failing to comply with this section shall be punished by a fine of not more than two hundred dollars.

.. Any owner failing to comply with this section shall be punished by a fine of five thousand dollars if, after such failure, a fire causes property damage, personal injury, or death to a tenant or a member of a tenant's household. All moneys received pursuant to (a) or (b) of this subsection, except for administrative costs for enforcing the fine, shall be deposited into the smoke detection device awareness account created in RCW 43.44.115. Enforcement shall occur after a fire occurs and when it is evident that the dwelling unit sold on or after July 1, 2019, did not have at least one smoke detection device. The following may enforce this subsection:

... The chief of the fire department if the dwelling unit is located within a city or town; or

... The county fire marshal or other fire official so designated by the county legislative authority if the dwelling unit is located within unincorporated areas of a county.

. For the purposes of this section:

.. "Dwelling unit" means a single unit providing complete, independent living facilities for one or more persons including permanent provisions for living, sleeping, eating, cooking, and sanitation; and

.. "Smoke detection device" means an assembly incorporating in one unit a device which detects visible or invisible particles of combustion, the control equipment, and the alarm-sounding device, operated from a power supply either in the unit or obtained at the point of installation.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5284-S2.SL.pdf?cite=2019%20c%20455%20§%201[2019 c 455 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2034[1995 c 369 § 34]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1096.SL.pdf?cite=1991%20c%20154%20§%201[1991 c 154 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2089[1986 c 266 § 89]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c50.pdf?cite=1980%20c%2050%20§%201[1980 c 50 § 1]; ]

== 43.44.115 - Smoke detection device awareness account.
The smoke detection device awareness account is created in the custody of the state treasurer. All receipts from fines imposed pursuant to RCW 43.44.110(5) must be deposited into the account. Expenditures from the account may be used only for the purposes of raising public awareness of owners and tenants' duties pertaining to smoke detection devices under RCW 43.44.110 and of the danger to life and property resulting from a failure to comply with those duties and for administrative costs related to enforcement of the fine created in RCW 43.44.110(5)(b). Only the Washington state patrol, through the director of fire protection or the director of fire protection's authorized deputy, may authorize expenditures from the account. The account is subject to the allotment procedures under chapter 43.88 RCW, but an appropriation is not required for expenditures.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5284-S2.SL.pdf?cite=2019%20c%20455%20§%202[2019 c 455 § 2]; ]

== 43.44.120 - Premises with guard animals—Registration, posting—Acts permitted firefighters—Liability for injury to firefighters.
. All premises guarded by guard animals, which are animals professionally trained to defend and protect premises or the occupants of the premises, shall be registered with the local fire department. Front entrances to residences and all entrances to business premises shall be posted in a visible location with signs approved by the chief of the Washington state patrol, through the director of fire protection, indicating that guard animals are present.

. A firefighter, who reasonably believes that his or her safety is endangered by the presence of a guard animal, may without liability: (a) Refuse to enter the premises, or (b) take any reasonable action necessary to protect himself or herself from attack by the guard animal.

. If the person responsible for the guard animal being on the premises does not comply with subsection (1) of this section, that person may be held liable for any injury to the firefighter caused by the presence of the guard animal.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5093-S.SL.pdf?cite=1995%20c%20369%20§%2035[1995 c 369 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2090[1986 c 266 § 90]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c258.pdf?cite=1983%20c%20258%20§%201[1983 c 258 § 1]; ]

== 43.44.130 - Hazardous liquid and gas pipeline accidents—Preparedness of local first responders.
. The chief of the Washington state patrol, through the director of fire protection or his or her authorized deputy, shall, in consultation with the emergency management program within the state military department, the department of ecology, the utilities and transportation commission, and local emergency services organizations:

.. Evaluate the preparedness of local first responders in meeting emergency management demands under subsection (2) of this section; and

.. Conduct an assessment of the equipment and personnel needed by local first responders to meet emergency management demands related to pipelines.

. The chief of the Washington state patrol, through the director of fire protection or his or her deputy, shall develop curricula for training local first responders to deal with hazardous liquid and gas pipeline accidents. The curricula shall be developed in conjunction with pipeline companies and local first responders, and shall include a timetable and costs for providing training as defined in the curricula to all communities housing pipelines. Separate curricula shall be developed for hazardous liquid and gas pipelines so that the differences between pipelines may be recognized and appropriate accident responses provided. The need for a training program for regional incident management teams shall also be evaluated.

. In consultation with other relevant agencies, the chief of the Washington state patrol, through the director of fire protection or his or her deputy, shall identify the need and means for achieving consistent application of the national interagency incident management system.

. For the purposes of this section, "local first responders" means police, fire, emergency medical staff, and volunteers.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2420-S2.SL.pdf?cite=2000%20c%20191%20§%2020[2000 c 191 § 20]; ]

