= 43.72 - Health system reform—Health services commission.
:toc:

== 43.72.011 - Definitions.
As used in this chapter, "health carrier," "health care provider," "provider," "health plan," and "health care facility" have the same meaning as provided in RCW 48.43.005.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2264-S.SL.pdf?cite=1997%20c%20274%20§%205[1997 c 274 § 5]; ]

== 43.72.090 - Uniform or supplemental benefits—Provision by certified health plan only—Uniform benefits package as minimum.
. On and after December 31, 1995, no person or entity in this state shall provide the uniform benefits package and supplemental benefits as defined in *RCW 43.72.010 without being certified as a certified health plan by the insurance commissioner.

. On and after December 31, 1995, no certified health plan may offer less than the uniform benefits package to residents of this state and no registered employer health plan may provide less than the uniform benefits package to its employees and their dependents.

. The health services commission may authorize renewal or continuation until December 31, 1996, of health care service contracts, disability group insurance, or health maintenance policies in effect on December 31, 1995.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=1995%20c%202%20§%201[1995 c 2 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20427[1993 c 492 § 427]; ]

== 43.72.180 - Legislative approval—Uniform benefits package and medical risk adjustment mechanisms.
The legislature may disapprove of the uniform benefits package developed under *RCW 43.72.130 and medical risk adjustment mechanisms developed under **RCW 43.72.040(7) by an act of law at any time prior to the last day of the following regular legislative session. If such disapproval action is taken, the commission shall resubmit a modified package to the legislature within fifteen days of the disapproval. If the legislature does not disapprove or modify the package by an act of law by the end of that regular session, the package is deemed approved.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=1995%20c%202%20§%202[1995 c 2 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20454[1993 c 492 § 454]; ]

== 43.72.300 - Managed competition—Findings and intent.
. The legislature recognizes that competition among health care providers, facilities, payers, and purchasers will yield the best allocation of health care resources, the lowest prices for health care services, and the highest quality of health care when there exists a large number of buyers and sellers, easily comparable health plans and services, minimal barriers to entry and exit into the health care market, and adequate information for buyers and sellers to base purchasing and production decisions. However, the legislature finds that purchasers of health care services and health care coverage do not have adequate information upon which to base purchasing decisions; that health care facilities and providers of health care services face legal and market disincentives to develop economies of scale or to provide the most cost-efficient and efficacious service; that health insurers, contractors, and health maintenance organizations face market disincentives in providing health care coverage to those Washington residents with the most need for health care coverage; and that potential competitors in the provision of health care coverage bear unequal burdens in entering the market for health care coverage.

. The legislature therefore intends to exempt from state anti-trust laws, and to provide immunity from federal anti-trust laws through the state action doctrine for activities approved under this chapter that might otherwise be constrained by such laws and intends to displace competition in the health care market: To contain the aggregate cost of health care services; to promote the development of comprehensive, integrated, and cost-effective health care delivery systems through cooperative activities among health care providers and facilities; to promote comparability of health care coverage; to improve the cost-effectiveness in providing health care coverage relative to health promotion, disease prevention, and the amelioration or cure of illness; to assure universal access to a publicly determined, uniform package of health care benefits; and to create reasonable equity in the distribution of funds, treatment, and medical risk among purchasers of health care coverage, payers of health care services, providers of health care services, health care facilities, and Washington residents. To these ends, any lawful action taken pursuant to chapter 492, Laws of 1993 by any person or entity created or regulated by chapter 492, Laws of 1993 are declared to be taken pursuant to state statute and in furtherance of the public purposes of the state of Washington.

. The legislature does not intend and unless explicitly permitted in accordance with RCW 43.72.310 or under rules adopted pursuant to chapter 492, Laws of 1993, does not authorize any person or entity to engage in activities or to conspire to engage in activities that would constitute per se violations of state and federal anti-trust laws including but not limited to conspiracies or agreements:

.. Among competing health care providers not to grant discounts, not to provide services, or to fix the price of their services;

.. Among health carriers as to the price or level of reimbursement for health care services;

.. Among health carriers to boycott a group or class of health care service providers;

.. Among purchasers of health plan coverage to boycott a particular plan or class of plans;

.. Among health carriers to divide the market for health care coverage; or

.. Among health carriers and purchasers to attract or discourage enrollment of any Washington resident or groups of residents in a health plan based upon the perceived or actual risk of loss in including such resident or group of residents in a health plan or purchasing group.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2264-S.SL.pdf?cite=1997%20c%20274%20§%206[1997 c 274 § 6]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20447[1993 c 492 § 447]; ]

== 43.72.310 - Managed competition—Competitive oversight—Attorney general duties—Anti-trust immunity—Fees.
. A health carrier, health care facility, health care provider, or other person involved in the development, delivery, or marketing of health care or health plans may request, in writing, that the department of health obtain an informal opinion from the attorney general as to whether particular conduct is authorized by chapter 492, Laws of 1993. Trade secret or proprietary information contained in a request for informal opinion shall be identified as such and shall not be disclosed other than to an authorized employee of the department of health or attorney general without the consent of the party making the request, except that information in summary or aggregate form and market share data may be contained in the informal opinion issued by the attorney general. The attorney general shall issue such opinion within thirty days of receipt of a written request for an opinion or within thirty days of receipt of any additional information requested by the attorney general necessary for rendering an opinion unless extended by the attorney general for good cause shown. If the attorney general concludes that such conduct is not authorized by chapter 492, Laws of 1993, the person or organization making the request may petition the department of health for review and approval of such conduct in accordance with subsection (3) of this section.

. After obtaining the written opinion of the attorney general and consistent with such opinion, the department of health:

.. May authorize conduct by a health carrier, health care facility, health care provider, or any other person that could tend to lessen competition in the relevant market upon a strong showing that the conduct is likely to achieve the policy goals of chapter 492, Laws of 1993 and a more competitive alternative is impractical;

.. Shall adopt rules governing conduct among providers, health care facilities, and health carriers including rules governing provider and facility contracts with health carriers, rules governing the use of "most favored nation" clauses and exclusive dealing clauses in such contracts, and rules providing that health carriers in rural areas contract with a sufficient number and type of health care providers and facilities to ensure consumer access to local health care services;

.. Shall adopt rules permitting health care providers within the service area of a plan to collectively negotiate the terms and conditions of contracts with a health carrier including the ability of providers to meet and communicate for the purposes of these negotiations;

.. Shall adopt rules governing cooperative activities among health care facilities and providers; and

.. Effective July 1, 1997, in addition to the rule-making authority granted to the department under this section, the department shall have the authority to enforce and administer rules previously adopted by the health services commission and the health care policy board pursuant to RCW 43.72.310.

. A health carrier, health care facility, health care provider, or any other person involved in the development, delivery, and marketing of health care services or health plans may file a written petition with the department of health requesting approval of conduct that could tend to lessen competition in the relevant market. Such petition shall be filed in a form and manner prescribed by rule of the department of health.

The department of health shall issue a written decision approving or denying a petition filed under this section within ninety days of receipt of a properly completed written petition unless extended by the department of health for good cause shown. The decision shall set forth findings as to benefits and disadvantages and conclusions as to whether the benefits outweigh the disadvantages.

. In authorizing conduct and adopting rules of conduct under this section, the department of health with the advice of the attorney general, shall consider the benefits of such conduct in furthering the goals of health care reform including but not limited to:

.. Enhancement of the quality of health services to consumers;

.. Gains in cost efficiency of health services;

.. Improvements in utilization of health services and equipment;

.. Avoidance of duplication of health services resources; or

.. And as to (b) and (c) of this subsection: (i) Facilitates the exchange of information relating to performance expectations; (ii) simplifies the negotiation of delivery arrangements and relationships; and (iii) reduces the transactions costs on the part of health carriers and providers in negotiating more cost-effective delivery arrangements.

These benefits must outweigh disadvantages including and not limited to:

... Reduced competition among health carriers, health care providers, or health care facilities;

... Adverse impact on quality, availability, or price of health care services to consumers; or

... The availability of arrangements less restrictive to competition that achieve the same benefits.

. Conduct authorized by the department of health shall be deemed taken pursuant to state statute and in the furtherance of the public purposes of the state of Washington.

. With the assistance of the attorney general's office, the department of health shall actively supervise any conduct authorized under this section to determine whether such conduct or rules permitting certain conduct should be continued and whether a more competitive alternative is practical. The department of health shall periodically review petitioned conduct through, at least, annual progress reports from petitioners, annual or more frequent reviews by the department of health that evaluate whether the conduct is consistent with the petition, and whether the benefits continue to outweigh any disadvantages. If the department of health determines that the likely benefits of any conduct approved through rule, petition, or otherwise by the department of health no longer outweigh the disadvantages attributable to potential reduction in competition, the department of health shall order a modification or discontinuance of such conduct. Conduct ordered discontinued by the department of health shall no longer be deemed to be taken pursuant to state statute and in the furtherance of the public purposes of the state of Washington.

. Nothing contained in chapter 492, Laws of 1993 is intended to in any way limit the ability of rural hospital districts to enter into cooperative agreements and contracts pursuant to RCW 70.44.450 and chapter 39.34 RCW.

. The secretary of health shall from time to time establish fees to accompany the filing of a petition or a written request to the department to obtain an opinion from the attorney general under this section and for the active supervision of conduct approved under this section. Such fees may vary according to the size of the transaction proposed in the petition or under active supervision. In setting such fees, the secretary shall consider that consumers and the public benefit when activities meeting the standards of this section are permitted to proceed; the importance of assuring that persons sponsoring beneficial activities are not foreclosed from filing a petition under this section because of the fee; and the necessity to avoid a conflict, or the appearance of a conflict, between the interests of the department and the public. The total fee for a petition under this section, a written request to the department to obtain an opinion from the attorney general, or a combination of both regarding the same conduct shall not exceed the level that will defray the reasonable costs the department and attorney general incur in considering a petition and in no event shall be greater than twenty-five thousand dollars. The fee for review of approved conduct shall not exceed the level that will defray the reasonable costs the department and attorney general incur in conducting such a review and in no event shall be greater than ten thousand dollars per annum. The fees shall be fixed by rule adopted in accordance with the provisions of the administrative procedure act, chapter 34.05 RCW, and shall be deposited in the health professions account established in accordance with RCW 43.70.320.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2264-S.SL.pdf?cite=1997%20c%20274%20§%207[1997 c 274 § 7]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1589-S.SL.pdf?cite=1995%20c%20267%20§%208[1995 c 267 § 8]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20448[1993 c 492 § 448]; ]

== 43.72.860 - Managed care pilot projects.
. The department of labor and industries, in consultation with the workers' compensation advisory committee, may conduct pilot projects to purchase medical services for injured workers through managed care arrangements. The projects shall assess the effects of managed care on the cost and quality of, and employer and employee satisfaction with, medical services provided to injured workers.

. The pilot projects may be limited to specific employers. The implementation of a pilot project shall be conditioned upon a participating employer and a majority of its employees, or, if the employees are represented for collective bargaining purposes, the exclusive bargaining representative, voluntarily agreeing to the terms of the pilot. Unless the project is terminated by the department, both the employer and employees are bound by the project agreements for the duration of the project.

. Solely for the purpose and duration of a pilot project, the specific requirements of Title 51 RCW that are identified by the department as otherwise prohibiting implementation of the pilot project shall not apply to the participating employers and employees to the extent necessary for conducting the project. Managed care arrangements for the pilot projects may include the designation of doctors responsible for the care delivered to injured workers participating in the projects.

. The projects shall conclude no later than January 1, 1997.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%2079[1998 c 245 § 79]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5401.SL.pdf?cite=1995%20c%2081%20§%202[1995 c 81 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20486[1993 c 492 § 486]; ]

== 43.72.902 - Public health services account.
The public health services account is created in the state treasury. Moneys in the account may be spent only after appropriation. Moneys in the account may be expended only for maintaining and improving the health of Washington residents through the public health system. For purposes of this section, the public health system shall consist of the state board of health, the state department of health, and local health departments and districts. During the 2001-2003 biennium, moneys in the fund may also be used for costs associated with hepatitis C testing and treatment in correctional facilities.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6153-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%207%20§%20916[2001 2nd sp.s. c 7 § 916]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2487.SL.pdf?cite=2000%202nd%20sp.s.%20c%201%20§%20913[2000 2nd sp.s. c 1 § 913]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5253-S.SL.pdf?cite=1995%20c%2043%20§%2012[1995 c 43 § 12]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20470[1993 c 492 § 470]; ]

== 43.72.910 - Short title—1993 c 492.
This act may be known and cited as the Washington health services act of 1993.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20487[1993 c 492 § 487]; ]

== 43.72.912 - Savings—1993 c 492.
The enactment of this act does not have the effect of terminating, or in any way modifying, any obligation or any liability, civil or criminal, which was already in existence on the effective date of this act.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20491[1993 c 492 § 491]; ]

== 43.72.914 - Reservation of legislative power—1993 c 492.
The legislature reserves the right to amend or repeal all or any part of this act at any time and there shall be no vested private right of any kind against such amendment or repeal. All the rights, privileges, or immunities conferred by this act or any acts done pursuant thereto shall exist subject to the power of the legislature to amend or repeal this act at any time.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20494[1993 c 492 § 494]; ]

== 43.72.915 - Effective dates—1993 c 492.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and shall take effect July 1, 1993, except for:

. Sections 234 through 243, 245 through 254, and 257 of this act, which shall take effect January 1, 1996, or January 1, 1998, if funding is not provided as set forth in section 17(4) of this act; and

. Sections 301 through 303 of this act, which shall take effect January 1, 1994.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5253-S.SL.pdf?cite=1995%20c%2043%20§%2015[1995 c 43 § 15]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5967-S.SL.pdf?cite=1993%20sp.s.%20c%2025%20§%20603[1993 sp.s. c 25 § 603]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20495[1993 c 492 § 495]; ]

== 43.72.916 - Effective date—1993 c 494.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and shall take effect July 1, 1993.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5076.SL.pdf?cite=1993%20c%20494%20§%208[1993 c 494 § 8]; ]

