= 43.56 - Uniform law commission.
:toc:

== 43.56.010 - Appointment of qualified persons.
. The governor shall appoint three qualified persons to serve on the Washington state uniform law commission for the promotion of uniformity of legislation in the United States. A qualified person is a resident of the state of Washington and a member of the state bar association of this or another state, who is or has been a judge, law professor, legislator, or practicing attorney.

. In addition to the members of the commission appointed pursuant to subsection (1) of this section, the governor may appoint to the commission any person who has served at least twenty years on the commission and who is a life member in the national conference of commissioners on uniform state laws or its successor.

. In addition to the members of the commission appointed pursuant to subsections (1) and (2) of this section, the code reviser shall serve as a member of the commission.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1120.SL.pdf?cite=2009%20c%20218%20§%201[2009 c 218 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.56.010[1965 c 8 § 43.56.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1905c59.pdf?cite=1905%20c%2059%20§%201[1905 c 59 § 1]; RRS § 8204; ]

== 43.56.020 - Duties of commission.
. The commission shall identify areas of the law in which (a) uniformity in the laws among the states and other jurisdictions is desirable and practicable and (b)(i) the congress of the United States lacks jurisdiction to act or (ii) it is preferable that the several states enact the laws.

. The commissioners, at the national conference of commissioners on uniform state laws or its successor, shall confer upon these matters with the commissioners appointed by other states for the same purpose and shall consider and draft uniform laws to be submitted for approval and adoption by the several states.

. The commission shall propose to the legislature for approval and adoption the uniform acts developed with the other commissioners and generally devise and recommend such other and further courses of action as shall accomplish such uniformity.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1120.SL.pdf?cite=2009%20c%20218%20§%202[2009 c 218 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.56.020[1965 c 8 § 43.56.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1905c59.pdf?cite=1905%20c%2059%20§%202[1905 c 59 § 2]; RRS § 8205; ]

== 43.56.040 - Travel expenses of members.
No member of the commission shall receive any compensation for services, but each member shall be paid travel expenses incurred in the discharge of official duty in accordance with RCW 43.03.050 and 43.03.060, after the account thereof has been audited by the commission.

The commission shall keep a full account of its expenditures and shall report it in each report. The commission shall allow expenses for only one meeting of the commission within this state each year, and shall allow expenses for the members to attend, no more than once in each year, any conference of the national conference of commissioners on uniform state laws, or its successor, outside of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1120.SL.pdf?cite=2009%20c%20218%20§%203[2009 c 218 § 3]; 1975-'76 2nd ex.s. c 34 § 118; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.56.040[1965 c 8 § 43.56.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c91.pdf?cite=1955%20c%2091%20§%201[1955 c 91 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1905c59.pdf?cite=1905%20c%2059%20§%204[1905 c 59 § 4]; RRS § 8207; ]

== 43.56.900 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%20108[2009 c 521 § 108]; ]

