= 43.30 - Department of natural resources.
:toc:

== 43.30.010 - Purpose.
The purpose of this chapter is to provide for more effective and efficient management of the forest and land resources in the state by consolidating into a department of natural resources certain powers, duties and functions of the division of forestry of the department of conservation and development, the board of state land commissioners, the state forest board, all state sustained yield forest committees, director of conservation and development, state capitol committee, director of licensing, secretary of state, director of revenue, and commissioner of public lands.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c107.pdf?cite=1979%20c%20107%20§%204[1979 c 107 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.30.010[1965 c 8 § 43.30.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c38.pdf?cite=1957%20c%2038%20§%201[1957 c 38 § 1]; ]

== 43.30.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Administrator" means the administrator of the department of natural resources.

. "Agency" and "state agency" means any branch, department, or unit of the state government, however designated or constituted.

. "Board" means the board of natural resources.

. "Commissioner" means the commissioner of public lands.

. "Department" means the department of natural resources.

. "Supervisor" means the supervisor of natural resources.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2481-S2.SL.pdf?cite=2010%20c%20126%20§%207[2010 c 126 § 7]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2165.SL.pdf?cite=2009%20c%20163%20§%206[2009 c 163 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.30.020[1965 c 8 § 43.30.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c38.pdf?cite=1957%20c%2038%20§%202[1957 c 38 § 2]; ]

== 43.30.030 - Department created.
The department of natural resources is hereby created, to consist of a board of natural resources, an administrator and a supervisor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.30.030[1965 c 8 § 43.30.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c38.pdf?cite=1957%20c%2038%20§%203[1957 c 38 § 3]; ]

== 43.30.035 - Environmental justice obligations of the department of natural resources.
The department must apply and comply with the substantive and procedural requirements of chapter 70A.02 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5141-S2.SL.pdf?cite=2021%20c%20314%20§%207[2021 c 314 § 7]; ]

== 43.30.055 - Employees—Applicability of merit system.
All employees of the department shall be governed by any merit system which is now or may hereafter be enacted by law governing such employment.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20119[2003 c 334 § 119]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.30.270[1965 c 8 § 43.30.270]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c38.pdf?cite=1957%20c%2038%20§%2027[1957 c 38 § 27]; ]

== 43.30.105 - Administrator of department.
The commissioner of public lands shall be the administrator of the department.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.30.050[1965 c 8 § 43.30.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c38.pdf?cite=1957%20c%2038%20§%205[1957 c 38 § 5]; ]

== 43.30.111 - Local wildland fire liaison.
. The commissioner must appoint a local wildland fire liaison that reports directly to the commissioner or the supervisor and generally represents the interests and concerns of landowners and the general public during any fire suppression activities of the department.

. The role of the local wildland fire liaison is to:

.. Provide advice to the commissioner on issues such as access to land during fire suppression activities, the availability of local fire suppression assets, environmental concerns, and landowner interests; and

.. Fulfill other duties as assigned by the commissioner or the legislature, including the recruitment of local wildland fire suppression contractors as provided in RCW 76.04.181.

. In appointing the local wildland fire liaison, the commissioner must consult with county legislative authorities either directly or through an organization that represents the interests of county legislative authorities.

. All requirements in this section are subject to the availability of amounts appropriated for the specific purposes described.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1489-S.SL.pdf?cite=2017%20c%20104%20§%202[2017 c 104 § 2]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2093-S.SL.pdf?cite=2015%20c%20182%20§%201[2015 c 182 § 1]; ]

== 43.30.155 - Supervisor of natural resources—Appointment.
The supervisor shall be appointed by the administrator with the advice and consent of the board. The supervisor shall serve at the pleasure of the administrator.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20105[2003 c 334 § 105]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.30.060[1965 c 8 § 43.30.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c38.pdf?cite=1957%20c%2038%20§%206[1957 c 38 § 6]; ]

== 43.30.205 - Board of natural resources—Composition.
. The board shall consist of six members:

.. The governor or the governor's designee;

.. The superintendent of public instruction;

.. The commissioner;

.. The director of the University of Washington school of forest resources;

.. The dean of the Washington State University college of agricultural, human, and natural resource sciences; and

.. A representative of those counties that contain state forestlands acquired or transferred under RCW 79.22.010, 79.22.040, and 79.22.020.

. [Empty]
.. The county representative on the board shall be selected by the legislative authorities of those counties that contain state forestlands acquired or transferred under RCW 79.22.010, 79.22.040, and 79.22.020. In the selection of the county representative, each participating county shall have one vote. The Washington state association of counties shall convene a meeting for the purpose of making the selection and shall notify the board of the selection.

.. The county representative must be a duly elected member of a county legislative authority who shall serve a term of four years unless the representative should leave office for any reason. The initial term shall begin on July 1, 1986.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2503-S.SL.pdf?cite=2010%20c%20189%20§%201[2010 c 189 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20104[2003 c 334 § 104]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c227.pdf?cite=1986%20c%20227%20§%201[1986 c 227 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c57.pdf?cite=1979%20ex.s.%20c%2057%20§%209[1979 ex.s. c 57 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.30.040[1965 c 8 § 43.30.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c38.pdf?cite=1957%20c%2038%20§%204[1957 c 38 § 4]; ]

== 43.30.215 - Powers and duties of board.
The board shall:

. Perform duties relating to appraisal, appeal, approval, and hearing functions as provided by law;

. Establish policies to ensure that the acquisition, management, and disposition of all lands and resources within the department's jurisdiction are based on sound principles designed to achieve the maximum effective development and use of such lands and resources consistent with laws applicable thereto;

. Constitute the board of appraisers provided for in Article 16, section 2 of the state Constitution;

. Constitute the commission on harbor lines provided for in Article 15, section 1 of the state Constitution as amended;

. Constitute the board on geographic names as provided for in RCW 43.30.291 through 43.30.295; and

. Adopt and enforce rules as may be deemed necessary and proper for carrying out the powers, duties, and functions imposed upon it by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1084-S.SL.pdf?cite=2011%20c%20355%20§%201[2011 c 355 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20112[2003 c 334 § 112]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c128.pdf?cite=1988%20c%20128%20§%2010[1988 c 128 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c227.pdf?cite=1986%20c%20227%20§%202[1986 c 227 § 2]; 1975-'76 2nd ex.s. c 34 § 107; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.30.150[1965 c 8 § 43.30.150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c38.pdf?cite=1957%20c%2038%20§%2015[1957 c 38 § 15]; ]

== 43.30.225 - Board's duties—Meetings—Organization.
The board shall:

. Hold regular monthly meetings at such times as it may determine, and such special meetings as may be called by the chair or majority of the board membership upon written notice to all members. However, the board may dispense with any regular meetings, except that the board shall not dispense with two consecutive regular meetings;

. Employ and fix the compensation of technical, clerical, and other personnel as deemed necessary for the performance of its duties;

. Appoint such advisory committees as deemed appropriate to advise and assist it to more effectively discharge its responsibilities. The members of such committees shall receive no compensation, but are entitled to reimbursement for travel expenses in attending committee meetings in accordance with RCW 43.03.050 and 43.03.060;

. Meet and organize on the third Tuesday of each January following a state general election at which the elected ex officio members of the board are elected. The board shall select its own chair. The commissioner of public lands shall be the secretary of the board. The board may select a vice chair from among its members. In the absence of the chair and vice chair at a meeting of the board, the members shall elect a chair pro tem. No action shall be taken by the board except by the agreement of at least four members. The department and the board shall maintain its principal office at the capital;

. Be entitled to reimbursement individually for travel expenses incurred in the discharge of their official duties in accordance with RCW 43.03.050 and 43.03.060.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20113[2003 c 334 § 113]; ]

== 43.30.235 - Records—Rules.
. The board shall keep its records in the office of the commissioner, and shall keep a full and complete record of its proceedings relating to the appraisal of lands granted for educational purposes.

. Records for all forestlands acquired by the state and any lands owned by the state and designated as such by the department must be maintained by the department as provided in RCW 79.22.030.

. The board shall have the power, from time to time, to make and enforce rules for carrying out the provisions of this title relating to its duties not inconsistent with law.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20304[2003 c 334 § 304]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c128.pdf?cite=1988%20c%20128%20§%2051[1988 c 128 § 51]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c21.pdf?cite=1982%201st%20ex.s.%20c%2021%20§%20149[1982 1st ex.s. c 21 § 149]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c255.pdf?cite=1927%20c%20255%20§%2013[1927 c 255 § 13]; RRS § 7797-13; ]

== 43.30.291 - Board on geographic names—Created—Duties.
The board on geographic names is created to establish a procedure for the retention and formal recognition of existing geographic names; to standardize the procedures for naming or renaming geographical features within the state of Washington; to identify one body as the responsible agency to coordinate this important activity between local, state, and federal agencies; to identify the responsible agency for the purpose of serving the public interest; to avoid the duplication of names for similar features whenever possible; and as far as possible, to retain the significance, spelling, and color of names associated with the early history of Washington.

The board on geographic names has the following duties:

. Establish the official names for the lakes, mountains, streams, places, towns, and other geographic features within the state and the spellings thereof except when a name is specified by law. For the purposes of this subsection, geographic features do not include human-made features or administrative areas such as parks, game reserves, and dams, but do include human-made lakes;

. Assign names to lakes, mountains, streams, places, towns, and other geographic features in the state for which no generally accepted name has been in use;

. Cooperate with county commissions, state departments, agencies, the state legislature, and the United States board on geographic names to establish, change, or determine the appropriate names of lakes, mountains, streams, places, towns, and other geographic features for the purposes of eliminating, as far as possible, duplications of place names within the state;

. Serve as a state of Washington liaison with the United States board on geographic names;

. Periodically issue a list of names approved by the board on geographic names; and

. Establish policies to carry out the purposes of this section and RCW 43.30.292 through 43.30.294.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1084-S.SL.pdf?cite=2011%20c%20355%20§%202[2011 c 355 § 2]; ]

== 43.30.292 - Board on geographic names—Committee on geographic names—Committee membership.
. The board on geographic names shall establish a committee on geographic names to assist the board in performing its duties and to provide broader contextual, public, and tribal participation in naming geographic features in the state. The committee shall report to the board on geographic names and shall consist of:

.. The commissioner or representative;

.. The state librarian or the librarian's designee;

.. The director of the department of archaeology and historic preservation or the director's designee;

.. A representative of the Washington state tribes, to be appointed by the commissioner from nominations made by Washington's recognized tribal governments. The tribal representative serves a three-year term; and

.. Three members from the public to be appointed by the commissioner. Initial appointments of the public members appointed under this subsection shall be as follows: One member for a one-year term, one member for a two-year term, and one member for a three-year term. Thereafter, each public member shall be appointed for a three-year term.

. Each member of the committee shall continue in office until a successor is appointed. The commissioner shall serve as chair of the board.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1084-S.SL.pdf?cite=2011%20c%20355%20§%203[2011 c 355 § 3]; ]

== 43.30.293 - Committee on geographic names—Meetings—Rules—Reports and recommendations.
. The committee on geographic names shall hold at least two meetings each year, and may hold special meetings as called by the chair or a majority of the members of the committee. All meetings must be open to the public.

.. Notice of all committee meetings shall be as provided in RCW 42.30.080. The notice must include the names to be considered by the committee and the names to be adopted by the board on geographic names.

.. Four committee members shall constitute a quorum.

. The committee shall establish rules for the conduct of its affairs and to carry out the duties of this section.

. The committee shall cooperate with the United States board on geographic names.

. The committee shall make reports and recommendations to the board on geographic names following each meeting of the committee. Recommendations regarding adoption of names may only be made following consideration at two committee meetings.

. In considering the names and spellings of geographic place names, the committee's recommendations to the board on geographic names may only be made after careful deliberation of all available information relating to such names, including the recommendations of the United States board on geographic names.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1084-S.SL.pdf?cite=2011%20c%20355%20§%204[2011 c 355 § 4]; ]

== 43.30.294 - Board on geographic names—Adoption of names—Publication in the Washington State Register—Official names.
. The board on geographic names shall consider the recommendations made by the committee on geographic names for adoption of names. The board on geographic names must either adopt the name as recommended, or refer the matter back to the committee on geographic names for further review.

. All geographic names adopted by the board on geographic names shall be published in the Washington State Register.

. Whenever the board on geographic names has given a name to any lake, stream, place, or other geographic feature within the state, the name must be used in all maps, records, documents, and other publications issued by the state or any of its departments and political subdivisions, and that name is the official name of the geographic feature.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1084-S.SL.pdf?cite=2011%20c%20355%20§%205[2011 c 355 § 5]; ]

== 43.30.295 - Board on geographic names—Administrative services—Custodian of records.
The department of natural resources shall provide secretarial and administrative services for the board on geographic names and shall serve as custodian of the records.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1084-S.SL.pdf?cite=2011%20c%20355%20§%206[2011 c 355 § 6]; ]

== 43.30.305 - Natural resources equipment fund—Authorized—Purposes—Expenditure.
A revolving fund in the custody of the state treasurer, to be known as the natural resources equipment fund, is hereby created to be expended by the department without appropriation solely for the purchase of equipment, machinery, and supplies for the use of the department and for the payment of the costs of repair and maintenance of such equipment, machinery, and supplies. During the 2007-2009 fiscal biennium the legislature may transfer such amounts as represent the excess balance of the fund to the state general fund.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1244-S.SL.pdf?cite=2009%20c%20564%20§%201809[2009 c 564 § 1809]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6090-S.SL.pdf?cite=2005%20c%20518%20§%20928[2005 c 518 § 928]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20120[2003 c 334 § 120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.30.280[1965 c 8 § 43.30.280]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c141.pdf?cite=1963%20c%20141%20§%201[1963 c 141 § 1]; ]

== 43.30.315 - Natural resources equipment fund—Reimbursement.
The natural resources equipment fund shall be reimbursed by the department for all moneys expended from it. Reimbursement may be prorated over the useful life of the equipment, machinery, and supplies purchased by moneys from the fund. Reimbursement may be made from moneys appropriated or otherwise available to the department for the purchase, repair, and maintenance of equipment, machinery, and supplies and shall be prorated on the basis of relative benefit to the programs. For the purpose of making reimbursement, all existing and hereafter acquired equipment, machinery, and supplies of the department shall be deemed to have been purchased from the natural resources equipment fund.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20121[2003 c 334 § 121]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.30.290[1965 c 8 § 43.30.290]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c141.pdf?cite=1963%20c%20141%20§%202[1963 c 141 § 2]; ]

== 43.30.325 - Deposit of money and fees—Natural resources deposit fund—Repayments.
. The department shall deposit daily all moneys and fees collected or received by the commissioner and the department in the discharge of official duties as follows:

.. The department shall pay moneys received as advance payments, deposits, and security from successful bidders under RCW 79.15.100 and 79.11.150 to the state treasurer for deposit under (b) of this subsection. Moneys received from unsuccessful bidders shall be returned as provided in RCW 79.11.150;

.. The department shall pay all moneys received on behalf of a trust fund or account to the state treasurer for deposit in the trust fund or account after making the deduction authorized under RCW 79.64.110, 79.22.050, 79.64.040, and 79.15.520, except as provided in RCW 79.64.130;

.. The natural resources deposit fund is hereby created. The state treasurer is the custodian of the fund. All moneys or sums which remain in the custody of the commissioner of public lands awaiting disposition or where the final disposition is not known shall be deposited into the natural resources deposit fund. Disbursement from the fund shall be on the authorization of the commissioner or the commissioner's designee, without necessity of appropriation;

.. If it is required by law that the department repay moneys disbursed under (a) and (b) of this subsection the state treasurer shall transfer such moneys, without necessity of appropriation, to the department upon demand by the department from those trusts and accounts originally receiving the moneys.

. Money shall not be deemed to have been paid to the state upon any sale or lease of land until it has been paid to the state treasurer.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1711-S2.SL.pdf?cite=2017%20c%20248%20§%204[2017 c 248 § 4]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20125[2003 c 334 § 125]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5074-S2.SL.pdf?cite=2003%20c%20313%20§%209[2003 c 313 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981ex2c4.pdf?cite=1981%202nd%20ex.s.%20c%204%20§%201[1981 2nd ex.s. c 4 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.85.130[1965 c 8 § 43.85.130]; prior:   1911 c 51 § 1; RRS § 5555.  1909 c 133 § 1, part; 1907 c 96 § 1, part; RRS § 5501, part; ]

== 43.30.340 - Federal funds for management and protection of forests, forest and range lands.
The department is authorized to receive funds from the federal government for cooperative work in management and protection of forests and forest and range lands as may be authorized by any act of Congress which is now, or may hereafter be, adopted for such purposes.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20202[2003 c 334 § 202]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c128.pdf?cite=1988%20c%20128%20§%2013[1988 c 128 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c78.pdf?cite=1957%20c%2078%20§%201[1957 c 78 § 1]; ]

== 43.30.345 - Federal funds for management and protection of forests, forest and range lands—Disbursement of funds.
The department is authorized to disburse such funds, together with any funds which may be appropriated or contributed from any source for such purposes, on management and protection of forests and forest and range lands.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20203[2003 c 334 § 203]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c128.pdf?cite=1988%20c%20128%20§%2014[1988 c 128 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c78.pdf?cite=1957%20c%2078%20§%202[1957 c 78 § 2]; ]

== 43.30.360 - Clarke-McNary fund.
The department and Washington State University may each receive funds from the federal government in connection with cooperative work with the United States department of agriculture, authorized by sections 4 and 5 of the Clarke-McNary act of congress, approved June 7, 1924, providing for the procurement, protection, and distribution of forestry seed and plants for the purpose of establishing windbreaks, shelter belts, and farm wood lots and to assist the owners of farms in establishing, improving, and renewing wood lots, shelter belts, and windbreaks; and are authorized to disburse such funds as needed. During the 2001-2003 fiscal biennium, the legislature may transfer from the Clarke-McNary fund to the state general fund such amounts as reflect the excess fund balance of the Clarke-McNary fund.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6387-S.SL.pdf?cite=2002%20c%20371%20§%20908[2002 c 371 § 908]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c100.pdf?cite=1986%20c%20100%20§%2046[1986 c 100 § 46]; ]

== 43.30.370 - Cooperative farm forestry funds.
The department and Washington State University may each receive funds from the federal government for cooperative work, as authorized by the cooperative forest management act of congress, approved May 18, 1937, and as subsequently authorized by any amendments to or substitutions for that act, for all purposes authorized by those acts, and to disburse the funds in cooperation with the federal government in accordance therewith.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c100.pdf?cite=1986%20c%20100%20§%2047[1986 c 100 § 47]; ]

== 43.30.385 - Parkland trust revolving fund.
. The parkland trust revolving fund is to be utilized by the department for the purpose of acquiring real property, including all reasonable costs associated with these acquisitions, as a replacement for the property transferred to the state parks and recreation commission, as directed by the legislature in order to maintain the land base of the affected trusts or under RCW 79.22.060 and to receive voluntary contributions for the purpose of operating and maintaining public use and recreation facilities, including trails, managed by the department.

. [Empty]
.. Proceeds from transfers of real property to the state parks and recreation commission or other proceeds identified from transfers of real property as directed by the legislature shall be deposited in the parkland trust revolving fund.

.. Except as otherwise provided in this subsection, the proceeds from real property transferred or disposed under RCW 79.22.060 must be used solely to purchase replacement forestland, that must be actively managed as a working forest, within the same county as the property transferred or disposed. If the real property was transferred under RCW 79.22.060 (1)(c) and (2)(c) from within a county participating in the state forestland pool created under RCW 79.22.140, replacement forestland may be located within any county participating in the land pool.

.. Disbursement from the parkland trust revolving fund to acquire replacement property and for operating and maintaining public use and recreation facilities shall be on the authorization of the department.

.. The proceeds from the recreation access pass account created in RCW 79A.80.090 must be solely used for the purpose of operating and maintaining public use and recreation facilities, including trails, managed by the department.

. In order to maintain an effective expenditure and revenue control, the parkland trust revolving fund is subject in all respects to chapter 43.88 RCW, but no appropriation is required to permit expenditures and payment of obligations from the fund.

. The department is authorized to solicit and receive voluntary contributions for the purpose of operating and maintaining public use and recreation facilities, including trails, managed by the department. The department may seek voluntary contributions from individuals and organizations for this purpose. Voluntary contributions will be deposited into the parkland trust revolving fund and used solely for the purpose of public use and recreation facilities operations and maintenance. Voluntary contributions are not considered a fee for use of these facilities.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5973-S2.SL.pdf?cite=2014%20c%2032%20§%202[2014 c 32 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2329.SL.pdf?cite=2012%20c%20166%20§%208[2012 c 166 § 8]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5622-S2.SL.pdf?cite=2011%20c%20320%20§%2021[2011 c 320 § 21]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1421-S.SL.pdf?cite=2011%20c%20216%20§%2014[2011 c 216 § 14]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1484-S2.SL.pdf?cite=2009%20c%20354%20§%209[2009 c 354 § 9]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2454.SL.pdf?cite=2004%20c%20103%20§%201[2004 c 103 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20106[2003 c 334 § 106]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6149-S.SL.pdf?cite=2000%20c%20148%20§%204[2000 c 148 § 4]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1342-S.SL.pdf?cite=1995%20c%20211%20§%205[1995 c 211 § 5]; ]

== 43.30.411 - Department to exercise powers and duties—Indemnification of private parties.
. The department shall exercise all of the powers, duties, and functions now vested in the commissioner of public lands and such powers, duties, and functions are hereby transferred to the department. However, nothing contained in this section shall effect the commissioner's ex officio membership on any committee provided by law.

. [Empty]
.. Except as provided in (b) of this subsection, and subject to the limitations of RCW 4.24.115, the department, in the exercise of any of its powers, may include in any authorized contract a provision for indemnifying the other contracting party against loss or damages.

.. When executing a right-of-way or easement contract over private land that involves forest management activities, the department shall indemnify the private landowner if the landowner does not receive a direct benefit from the contract.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20108[2003 c 334 § 108]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5042.SL.pdf?cite=2003%20c%20312%20§%201[2003 c 312 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.30.130[1965 c 8 § 43.30.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c38.pdf?cite=1957%20c%2038%20§%2013[1957 c 38 § 13]; ]

== 43.30.421 - Administrator.
The administrator shall have responsibility for performance of all the powers, duties, and functions of the department except those specifically assigned to the board. In the performance of these powers, duties, and functions, the administrator shall conform to policies established by the board, and may employ and fix the compensation of such personnel as may be required to perform the duties of this office.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20114[2003 c 334 § 114]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.30.160[1965 c 8 § 43.30.160]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c38.pdf?cite=1957%20c%2038%20§%2016[1957 c 38 § 16]; ]

== 43.30.430 - Supervisor.
The supervisor shall:

. Be charged with the direct supervision of the department's activities as delegated by the administrator;

. Perform his or her duties in conformance with the policies established by the board;

. Organize the department, with approval of the administrator, into such subordinate divisions as the supervisor deems appropriate for the conduct of its operations;

. Employ and fix the compensation of such technical, clerical, and other personnel as may be required to carry on activities under his or her supervision;

. Delegate by order any assigned powers, duties, and functions to one or more deputies or assistants, as desired;

. Furnish before entering upon the duties of this position a surety bond payable to the state in such amount as may be determined by the board, conditioned for the faithful performance of duties and for accounting of all moneys and property of the state that may come into possession of or under the control of this position.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20115[2003 c 334 § 115]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.30.170[1965 c 8 § 43.30.170]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c38.pdf?cite=1957%20c%2038%20§%2017[1957 c 38 § 17]; ]

== 43.30.440 - Oaths may be administered by supervisor and deputies.
The supervisor and duly authorized deputies may administer oaths.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20116[2003 c 334 § 116]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.30.180[1965 c 8 § 43.30.180]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c38.pdf?cite=1957%20c%2038%20§%2018[1957 c 38 § 18]; ]

== 43.30.450 - Right of entry in course of duty by representatives of department.
Any authorized assistants, employees, agents, appointees, or representatives of the department may, in the course of their inspection and enforcement duties as provided for in chapters 76.04, 76.06, 76.09, and 76.36 RCW, enter upon any lands, real estate, waters, or premises except the dwelling house or appurtenant buildings in this state whether public or private and remain thereon while performing such duties. Similar entry by the department may be made for the purpose of making examinations, locations, surveys, and/or appraisals of all lands under the management and jurisdiction of the department; or for making examinations, appraisals and, after five days' written notice to the landowner, making surveys for the purpose of possible acquisition of property to provide public access to public lands. In no event other than an emergency such as firefighting shall motor vehicles be used to cross a field customarily cultivated, without prior consent of the owner. None of the entries herein provided for shall constitute trespass, but nothing contained herein shall limit or diminish any liability which would otherwise exist as a result of the acts or omissions of the department or its representatives.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20204[2003 c 334 § 204]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%201[2000 c 11 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%20194[1983 c 3 § 194]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c49.pdf?cite=1971%20ex.s.%20c%2049%20§%201[1971 ex.s. c 49 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c100.pdf?cite=1963%20c%20100%20§%201[1963 c 100 § 1]; ]

== 43.30.460 - Department to participate in and administer federal Safe Drinking Water Act in conjunction with other departments.
See RCW 43.21A.445.

[ ]

== 43.30.480 - Watershed restoration projects—Permit processing.
A permit required by the department for a watershed restoration project as defined in RCW 89.08.460 shall be processed in compliance with RCW 89.08.450 through 89.08.510.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5616-S.SL.pdf?cite=1995%20c%20378%20§%2013[1995 c 378 § 13]; ]

== 43.30.490 - Cost-reimbursement agreements.
. The department may enter into a written cost-reimbursement agreement with a permit or lease applicant or project proponent to recover from the applicant or proponent the reasonable costs incurred by the department in carrying out the requirements of this chapter, as well as the requirements of other relevant laws, as they relate to permit coordination, environmental review, application review, technical studies, establishment of development units and approval or establishment of pooling agreements under chapter 78.52 RCW, including necessary technical studies, permit or lease processing, and monitoring for permit compliance.

. The cost-reimbursement agreement shall identify the tasks and costs for work to be conducted under the agreement. The agreement must include a schedule that states:

.. The estimated number of weeks for initial review of the permit application;

.. The estimated number of revision cycles;

.. The estimated number of weeks for review of subsequent revision submittals;

.. The estimated number of billable hours of employee time;

.. The rate per hour; and

.. A date for revision of the agreement if necessary.

. The written cost-reimbursement agreement shall be negotiated with the permit or lease applicant or project proponent. Under the provisions of a cost-reimbursement agreement, funds from the applicant or proponent shall be used by the department to contract with an independent consultant to carry out the work covered by the cost-reimbursement agreement. The department may also use funds provided under a cost-reimbursement agreement to hire temporary employees, to assign current staff to review the work of the consultant, to provide necessary technical assistance when an independent consultant with comparable technical skills is unavailable, and to recover reasonable and necessary direct and indirect costs that arise from processing the permit or lease. The department shall, in developing the agreement, ensure that final decisions that involve policy matters are made by the agency and not by the consultant. The department shall make an estimate of the number of permanent staff hours to process the permits or leases, and shall contract with consultants or hire temporary employees to replace the time and functions committed by these permanent staff to the project. The billing process shall provide for accurate time and cost accounting and may include a billing cycle that provides for progress payments. 

. The cost-reimbursement agreement must not negatively impact the processing of other permit applications. In order to maintain permit processing capacity, the agency may hire outside consultants, temporary employees, or make internal administrative changes. Consultants or temporary employees hired as part of a cost-reimbursement agreement or to maintain agency capacity are hired as agents of the state not of the permit applicant. The restrictions of chapter 42.52 RCW apply to any cost-reimbursement agreement, and to any person hired as a result of a cost-reimbursement agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1730-S.SL.pdf?cite=2009%20c%2097%20§%209[2009 c 97 § 9]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5445-S.SL.pdf?cite=2007%20c%20188%20§%201[2007 c 188 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5122-S2.SL.pdf?cite=2007%20c%2094%20§%2011[2007 c 94 § 11]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1526.SL.pdf?cite=2003%20c%2070%20§%202[2003 c 70 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6277-S.SL.pdf?cite=2000%20c%20251%20§%203[2000 c 251 § 3]; ]

== 43.30.510 - Administrator may designate substitute for member of board, commission, etc.
When any officer, member, or employee of an agency abolished by provisions of this chapter is, under provisions of existing law, designated as a member ex officio of another board, commission, committee, or other agency, and no provision is made in this chapter with respect to a substitute, the administrator shall designate the officer or other person to serve hereafter in that capacity.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.30.210[1965 c 8 § 43.30.210]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c38.pdf?cite=1957%20c%2038%20§%2021[1957 c 38 § 21]; ]

== 43.30.520 - Property transactions, restrictive conveyances, highway purpose—Existing law to continue.
Nothing in this chapter shall be interpreted as changing existing law with respect to:

. Property given to a state agency on restrictive conveyance with provision for reversion to the grantor or for the vesting of title in another if and when such property is not used by the agency concerned for the stipulated purposes;

. Land or other property acquired by any state agency for highway purposes.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.30.250[1965 c 8 § 43.30.250]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c38.pdf?cite=1957%20c%2038%20§%2025[1957 c 38 § 25]; ]

== 43.30.530 - Real property—Services and facilities available to other state agencies, cost.
Upon request by any state agency vested by law with the authority to acquire or manage real property, the department shall make available to such agency the facilities and services of the department with respect to such acquisition or management, upon condition that such agency reimburse the department for the costs of such services.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20117[2003 c 334 § 117]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.30.260[1965 c 8 § 43.30.260]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c38.pdf?cite=1957%20c%2038%20§%2026[1957 c 38 § 26]; ]

== 43.30.540 - Acting as harbor line commission.
The board acting as the harbor line commission shall keep a full and complete record of its proceedings relating to the establishment of harbor lines and the determination of harbor areas. The board shall have the power from time to time to make and enforce rules for the carrying out of the provisions of chapters 79.105 through 79.140 RCW relating to its duties not inconsistent with law.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1491-S.SL.pdf?cite=2005%20c%20155%20§%20103[2005 c 155 § 103]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c21.pdf?cite=1982%201st%20ex.s.%20c%2021%20§%2014[1982 1st ex.s. c 21 § 14]; ]

== 43.30.545 - Washington conservation corps.
The department shall cooperate, when appropriate, as a partner in the Washington conservation corps established in chapter 43.220 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1294-S.SL.pdf?cite=2011%20c%2020%20§%2012[2011 c 20 § 12]; ]

== 43.30.550 - Department to make examples of forest practices applications and resulting approvals available to the public.
. By December 31, 2013, the department must make examples of complete, high quality forest practices applications and the resulting approvals readily available to the public on its internet site, as well as the internet site of the office of regulatory assistance established in RCW 43.42.010. The department must maximize assistance to the public and interested parties by seeking to make readily available examples from forest practices that generate significant permitting activity or frequent questions.

. The department must regularly review and update the examples required to be made available on the internet under subsection (1) of this section.

. The department must obtain the written permission of an applicant before making publicly available that applicant's application or approval under this section and must work cooperatively with the applicant to ensure that no personal or proprietary information is made available.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6406-S.SL.pdf?cite=2012%201st%20sp.s.%20c%201%20§%20208[2012 1st sp.s. c 1 § 208]; ]

== 43.30.555 - Geoduck harvest safety committee.
. The department shall establish a geoduck harvest safety committee. The geoduck harvest safety committee consists of one representative from the department, one representative from the department's geoduck diver advisory committee, one representative from an organization representing the interests of geoduck harvesters, and one representative from an organization representing the interests of geoduck divers. Each representative must be appointed by the administrator.

. The geoduck harvest safety committee must meet at least quarterly. By December 1, 2013, the committee must submit a recommendation to the department regarding the establishment of a geoduck diver safety program and safety requirements for geoduck divers licensed under RCW 77.65.410.

. Upon the establishment of the geoduck diver safety program under RCW 43.30.560, the geoduck harvest safety committee must continue to review and evaluate the safety program's success and effectiveness and recommend to the department appropriate changes to improve the geoduck diver safety program.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1764-S2.SL.pdf?cite=2013%20c%20204%20§%204[2013 c 204 § 4]; ]

== 43.30.560 - Geoduck diver safety program—Rule-making authority—Limitation on civil suit or action.
. By December 1, 2014, the department must, by rule, create a geoduck diver safety program and establish safety requirements for geoduck divers licensed under RCW 77.65.410. The department must adopt rules based on the recommendation of the geoduck harvest safety committee established in RCW 43.30.555.

. The department may adopt, amend, or repeal rules as needed to ensure the success and effectiveness of the geoduck diver safety program created under subsection (1) of this section. The department must consider the recommendations provided by the geoduck harvest safety committee under RCW 43.30.555(3).

. The department may not adopt rules in conflict with commercial diving safety standards and regulations promulgated and implemented by the federal occupational safety and health administration established under the federal occupational safety and health act of 1970 (84 Stat. 1590 et seq.; 29 U.S.C. Sec. 651 et seq.).

. A civil suit or action may not be commenced or prosecuted against the administrator, department, or any other government officer or entity by reason of any actions taken in connection with the adoption or enforcement of the geoduck diver safety program and safety requirements established under subsections (1) and (2) of this section. The state of Washington does not waive its sovereign immunity with respect to any actions taken by the department under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1764-S2.SL.pdf?cite=2013%20c%20204%20§%205[2013 c 204 § 5]; ]

== 43.30.565 - Transfer of ownership of department-owned vessel—Review of vessel's physical condition.
. Prior to transferring ownership of a department-owned vessel, the department shall conduct a thorough review of the physical condition of the vessel, the vessel's operating capability, and any containers and other materials that are not fixed to the vessel.

. If the department determines that the vessel is in a state of advanced deterioration or poses a reasonably imminent threat to human health or safety, including a threat of environmental contamination, the department may: (a) Not transfer the vessel until the conditions identified under this subsection have been corrected; or (b) permanently dispose of the vessel by landfill, deconstruction, or other related method.

. Vessels taken into custody under chapter 79.100 RCW are not subject to this section or RCW 43.30.570.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1245-S.SL.pdf?cite=2013%20c%20291%20§%207[2013 c 291 § 7]; ]

== 43.30.570 - Transfer of ownership of department-owned vessel—Further requirements.
. Following the inspection required under RCW 43.30.565 and prior to transferring ownership of a department-owned vessel, the department shall obtain the following from the transferee:

.. The purposes for which the transferee intends to use the vessel; and

.. Information demonstrating the prospective owner's intent to obtain legal moorage following the transfer, in the manner determined by the department.

. [Empty]
.. The department shall remove any containers or other materials that are not fixed to the vessel and contain hazardous substances, as defined under RCW 70A.305.020.

.. However, the department may transfer a vessel with:

... Those containers or materials described under (a) of this subsection where the transferee demonstrates to the department's satisfaction that the container's or material's presence is consistent with the anticipated use of the vessel; and

... A reasonable amount of fuel as determined by the department, based on factors including the vessel's size, condition, and anticipated use of the vessel, including initial destination following transfer.

.. The department may consult with the department of ecology in carrying out the requirements of this subsection.

. Prior to sale, and unless the vessel has a title or valid marine document, the department is required to apply for a certificate of title for the vessel under RCW 88.02.510 and register the vessel under RCW 88.02.550.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1192.SL.pdf?cite=2021%20c%2065%20§%2042[2021 c 65 § 42]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1245-S.SL.pdf?cite=2013%20c%20291%20§%208[2013 c 291 § 8]; ]

== 43.30.575 - Wildfire areas—Funding wildfire risk reduction in certain counties.
Subject to the availability of amounts appropriated for this specific purpose, in order to prevent homelessness in any county located east of the crest of the Cascade mountain range that shares a common border with Canada and has a population of one hundred thousand or less, the department shall, to strengthen the local capacity for controlling risk to life and property that may result from wildfires, administer to these counties, funding for radio communication equipment; and fire protection service providers within these counties to provide residential wildfire risk reduction activities, including education and outreach, technical assistance, fuel mitigation and other residential risk reduction measures. For the purposes of this section, fire protection service providers include fire departments, fire districts, emergency management services, and regional fire protection service authorities. The department must prioritize funding to counties authorized in this section serving a disproportionately higher percentage of low-income residents, as defined in RCW 84.36.042, that are located in areas of higher wildfire risk, and whose fire protection service providers have a shortage of reliable equipment and resources.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2010-S.SL.pdf?cite=2017%20c%20280%20§%201[2017 c 280 § 1]; ]

== 43.30.580 - Wildland urban interface areas—Grant program.
. The department shall, to the extent practical within existing resources, establish a program of technical assistance to counties, cities, and towns for the development of findings of fact and maps establishing the wildland urban interface areas of jurisdictions in accordance with the requirements of the International Wildland Urban Interface Code as adopted by reference in RCW 19.27.560.

. The department shall develop and administer a grant program, subject to funding provided for this purpose, to provide direct financial assistance to counties, cities, and towns for the development of findings of fact and maps establishing wildland urban interface areas. Applications for grant funds must be submitted by counties, cities, and towns in accordance with regulations adopted by the department. The department is authorized to make and administer grants on the basis of applications, within appropriations authorized by the legislature, to any county, city, or town for the purpose of developing findings of fact and maps establishing wildland urban interface areas.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6109-S.SL.pdf?cite=2018%20c%20189%20§%203[2018 c 189 § 3]; ]

== 43.30.582 - Marbled murrelet conservation strategy—Reports. (Contingent expiration date.)
. [Empty]
.. By December 1, 2018, and each December 1st until the year after the United States fish and wildlife service issues an incidental take permit on the state trust land habitat conservation plan for the long-term conservation strategy for the marbled murrelet, the department must provide a report to the legislature, consistent with RCW 43.01.036, as required in this section.

.. No fewer than ninety days before submitting the report to the legislature as described in this section, the department must first submit a draft of the report for review and comment to the chair and ranking member of the committees of the house of representatives and senate with jurisdiction over state trust lands management.

.. Each regular legislative session, the standing committee with jurisdiction over state trust land management from the house of representatives and senate must each hold a meeting, which may be held as a joint meeting, on the report required in this section and the habitat conservation plan update process.

. The report required in this section must annually include an economic analysis of potential losses or gains from any proposed marbled murrelet long-term conservation strategy selected by the board of natural resources, forwarded to or approved by the United States fish and wildlife service, and subsequently adopted by the board.

. The initial report required under this section must also include recommendations relating to the following, to be updated as appropriate in subsequent reports:

.. Actions that support maintaining or increasing family-wage timber and related jobs in the affected rural communities, taking into account, as appropriate, the role of other market factors;

.. Strategies to ensure no net loss of revenues to the trust beneficiaries due to the implementation of additional marbled murrelet conservation measures;

.. Additional means of financing county services; and

.. Additional reasonable, incentive-based, nonregulatory conservation measures for the marbled murrelet that also provide economic benefits to rural communities.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2285-S.SL.pdf?cite=2018%20c%20255%20§%202[2018 c 255 § 2]; ]

== 43.30.583 - Marbled murrelet advisory committee. (Contingent expiration date.)
. To assist the department in developing and providing the report to the legislature required in RCW 43.30.582, the commissioner must appoint a marbled murrelet advisory committee.

. The marbled murrelet advisory committee may include one or more representatives from the following categories:

.. State trust lands beneficiaries;

.. Impacted state forestlands beneficiaries, including counties;

.. Junior taxing districts;

.. Environmental organizations;

.. Local governments or an association representing local governments;

.. Milling interests or an association representing milling interests;

.. Private forestland owners or a statewide association representing private forestland owners; and

.. Local public interest groups.

. The advisory committee required under this section may consult with relevant state and federal agencies and tribes.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2285-S.SL.pdf?cite=2018%20c%20255%20§%203[2018 c 255 § 3]; ]

== 43.30.600 - State geological survey.
The department shall assume full charge and supervision of the state geological survey and perform such other duties as may be prescribed by law.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20107[2003 c 334 § 107]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c127.pdf?cite=1988%20c%20127%20§%203[1988 c 127 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.21.050[1965 c 8 § 43.21.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c7.pdf?cite=1921%20c%207%20§%2069[1921 c 7 § 69]; RRS § 10827; ]

== 43.30.610 - Mining.
The department shall:

. Collect, compile, publish, and disseminate statistics and information relating to mining, milling, and metallurgy;

. Make special studies of the mineral resources and industries of the state;

. Collect and assemble an exhibit of mineral specimens, both metallic and nonmetallic, especially those of economic and commercial importance; such collection to constitute the museum of mining and mineral development;

. Collect and assemble a library pertaining to mining, milling, and metallurgy of books, reports, drawings, tracings, and maps and other information relating to the mineral industry and the arts and sciences of mining and metallurgy;

. Make a collection of models, drawings, and descriptions of the mechanical appliances used in mining and metallurgical processes;

. Issue bulletins and reports with illustrations and maps with detailed description of the natural mineral resources of the state;

. Preserve and maintain such collections and library open to the public for reference and examination and maintain a bureau of general information concerning the mineral and mining industry of the state, and issue from time to time at cost of publication and distribution such bulletins as may be deemed advisable relating to the statistics and technology of minerals and the mining industry;

. Make determinative examinations of ores and minerals, and consider other scientific and economical problems relating to mining and metallurgy;

. Cooperate with all departments of the state government, state educational institutions, the United States geological survey, and the United States bureau of mines. All departments of the state government and educational institutions shall render full cooperation to the department in compiling useful and scientific information relating to the mineral industry within and without the state, without cost to the department.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20109[2003 c 334 § 109]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c127.pdf?cite=1988%20c%20127%20§%204[1988 c 127 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.21.070[1965 c 8 § 43.21.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c142.pdf?cite=1935%20c%20142%20§%202[1935 c 142 § 2]; RRS § 8614-2; ]

== 43.30.630 - Sealing of open holes and mine shafts.
The department shall work with federal officials and private mine owners to ensure the prompt sealing of open holes and mine shafts that constitute a threat to safety.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20101[2003 c 334 § 101]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c459.pdf?cite=1985%20c%20459%20§%207[1985 c 459 § 7]; ]

== 43.30.640 - Mine owners—Maps of property surface and underground workings—Filing.
The owner of each mine shall make a map of the surface of the property. The owner of each active mine shall make a map of the underground workings. All maps shall be filed with the department. The department shall establish by rule the scale and contents required for the maps.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20102[2003 c 334 § 102]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c459.pdf?cite=1985%20c%20459%20§%208[1985 c 459 § 8]; ]

== 43.30.650 - Gifts and bequests relating to mining.
The department may receive on behalf of the state, for the benefit of mining and mineral development, gifts, bequests, devises, and legacies of real or personal property and use them in accordance with the wishes of the donors and manage, use, and dispose of them for the best interests of mining and mineral development.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20110[2003 c 334 § 110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c127.pdf?cite=1988%20c%20127%20§%205[1988 c 127 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.21.080[1965 c 8 § 43.21.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c142.pdf?cite=1935%20c%20142%20§%203[1935 c 142 § 3]; RRS § 8614-3; ]

== 43.30.660 - Collection of minerals for exhibition.
The department may, from time to time, prepare special collections of ores and minerals representative of the mineral industry of the state to be displayed or used at any world fair, exposition, mining congress, or state exhibition, in order to promote information relating to the mineral wealth of the state.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1252.SL.pdf?cite=2003%20c%20334%20§%20111[2003 c 334 § 111]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c127.pdf?cite=1988%20c%20127%20§%206[1988 c 127 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.21.090[1965 c 8 § 43.21.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c142.pdf?cite=1935%20c%20142%20§%204[1935 c 142 § 4]; RRS § 8614-4; ]

== 43.30.700 - Powers of department—Forested lands.
. The department may:

.. Inquire into the production, quality, and quantity of second growth timber to ascertain conditions for reforestation; and

.. Publish information pertaining to forestry and forest products which it considers of benefit to the people of the state.

. The department shall:

.. Collect information through investigation by its employees, on forestlands owned by the state, including:

... Condition of the lands;

... Forest fire damage;

... Illegal cutting, trespassing, or thefts; and

... The number of acres and the value of the timber that is cut and removed each year, to determine which state lands are valuable chiefly for growing timber;

.. Prepare maps of each timbered county showing state land therein; and

.. Protect forested public land, as defined in RCW 79.02.010, as much as is practical and feasible from fire, trespass, theft, and the illegal cutting of timber.

. When the department considers it to be in the best interest of the state, it may cooperate with any agency of another state, the United States or any agency thereof, the Dominion of Canada or any agency or province thereof, and any county, town, corporation, individual, or Indian tribe within the state of Washington in:

.. Forest surveys;

.. Forest studies;

.. Forest products studies; and

.. Preparation of plans for the protection, management, and replacement of trees, wood lots, and timber tracts.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2321-S.SL.pdf?cite=2004%20c%20199%20§%20101[2004 c 199 § 101]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c100.pdf?cite=1986%20c%20100%20§%2050[1986 c 100 § 50]; ]

== 43.30.710 - Sale or exchange of tree seedling stock and tree seed—Provision of stock or seed to local governments or nonprofit organizations.
The department is authorized to sell to or exchange with persons intending to restock forest areas, tree seedling stock and tree seed produced at the state nursery.

The department may provide at cost, stock or seed to local governments or nonprofit organizations for urban tree planting programs consistent with the *community and urban forestry program.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5159-S.SL.pdf?cite=1993%20c%20204%20§%207[1993 c 204 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c128.pdf?cite=1988%20c%20128%20§%2035[1988 c 128 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c67.pdf?cite=1947%20c%2067%20§%201[1947 c 67 § 1]; Rem. Supp. 1947 § 5823-40; ]

== 43.30.720 - Use of proceeds specified.
All receipts from the sale of stock or seed shall be deposited in a state forest nursery revolving fund to be maintained by the department, which is hereby authorized to use all money in said fund for the maintenance of the state tree nursery or the planting of denuded state owned lands.

During the 2011-2013 fiscal biennium, the legislature may transfer from the state forest nursery revolving fund to the state general fund such amounts as reflect the excess fund balance of the fund.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2127-S.SL.pdf?cite=2012%202nd%20sp.s.%20c%207%20§%20918[2012 2nd sp.s. c 7 § 918]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5404-S.SL.pdf?cite=2003%201st%20sp.s.%20c%2025%20§%20938[2003 1st sp.s. c 25 § 938]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c128.pdf?cite=1988%20c%20128%20§%2036[1988 c 128 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c67.pdf?cite=1947%20c%2067%20§%202[1947 c 67 § 2]; RRS § 5823-41; ]

== 43.30.800 - Olympic natural resources center—Finding, intent.
The legislature finds that conflicts over the use of natural resources essential to the state's residents, especially forest and ocean resources, have increased dramatically. There are growing demands that these resources be fully utilized for their commodity values, while simultaneously there are increased demands for protection and preservation of these same resources. While these competing demands are most often viewed as mutually exclusive, recent research has suggested that commodity production and ecological values can be integrated. It is the intent of the legislature to foster and support the research and education necessary to provide sound scientific information on which to base sustainable forest and marine industries, and at the same time sustain the ecological values demanded by much of the public.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1877-S.SL.pdf?cite=1991%20c%20316%20§%201[1991 c 316 § 1]; ]

== 43.30.810 - Olympic natural resources center—Purpose, programs.
. The Olympic natural resources center is hereby created at the University of Washington in the school of environmental and forest sciences and the school of aquatic and fishery sciences.

. The Olympic natural resources center shall maintain facilities and programs in the western portion of the Olympic Peninsula. The purpose of the center is to demonstrate innovative management methods which successfully integrate environmental, energy, marine, and economic interests into pragmatic management of forest and ocean resources. The center shall combine research and educational opportunities with experimental forestry, oceans management, and traditional management knowledge into an overall program which demonstrates that management based on sound economic principles is made superior when combined with new methods of management based on ecological principles. The programs developed by the center shall include the following:

.. Research and education on a broad range of ocean resources problems and opportunities in the region, such as estuarine processes, ocean and coastal management, renewable energy production, offshore development, fisheries and shellfish enhancement, and coastal business development, tourism, and recreation. In developing this component of the center's program, the center shall collaborate with coastal educational institutions such as Grays Harbor community college and Peninsula community college;

.. Research and education on forest resources management issues on the landscape, ecosystem, or regional level, including issues that cross legal and administrative boundaries;

.. Research and education that broadly integrates marine and terrestrial issues, including interactions of marine, aquatic, and terrestrial ecosystems, and that identifies options and opportunities to integrate the production of commodities with the preservation of ecological values. Where appropriate, programs shall address issues and opportunities that cross legal and administrative boundaries;

.. Research and education on natural resources and their social and economic implications, and on alternative economic and social bases for sustainable, healthy, resource-based communities;

.. Educational opportunities such as workshops, short courses, and continuing education for resource professionals, policy forums, information exchanges including international exchanges where appropriate, conferences, student research, and public education; and

.. Creation of a neutral forum where parties with diverse interests are encouraged to address and resolve their conflicts.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=2012%20c%20243%20§%202[2012 c 243 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1877-S.SL.pdf?cite=1991%20c%20316%20§%202[1991 c 316 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c424.pdf?cite=1989%20c%20424%20§%204[1989 c 424 § 4]; ]

== 43.30.820 - Olympic natural resources center—Administration—Policy advisory board.
. The Olympic natural resources center shall operate under the authority of the board of regents of the University of Washington. It shall be administered by a director appointed jointly by the directors of the school of environmental and forest sciences and the school of aquatic and fishery sciences. The director of the center shall be a member of the faculty of one of those schools. The director of the center shall appoint and maintain a scientific or technical committee, and other committees as necessary, to advise the director on the efficiency, effectiveness, and quality of the center's activities.

. The governor must appoint a policy advisory board consisting of eleven members, who serve at the pleasure of the governor, to advise the directors of the school of environmental and forest sciences, the school of aquatic and fishery sciences, and the Olympic natural resources center on policies for the center that are consistent with its purposes. Membership on the policy advisory board must broadly represent the various interests concerned with the purposes of the center, including the Washington state department of natural resources and state and federal government, environmental, local community, timber industry, and tribal interests. Policy advisory board members shall serve four-year terms and are eligible for reappointment.

. Service on boards and committees of the Olympic natural resources center is without compensation but actual travel expenses incurred in connection with service to the center may be reimbursed from appropriated funds in accordance with RCW 43.03.050 and 43.03.060.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=2012%20c%20243%20§%201[2012 c 243 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2617-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%207%20§%2074[2010 1st sp.s. c 7 § 74]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1877-S.SL.pdf?cite=1991%20c%20316%20§%203[1991 c 316 § 3]; ]

== 43.30.830 - Olympic natural resources center—Funding—Contracts.
The center may solicit gifts, grants, conveyances, bequests, and devises, whether real or personal property, or both, in trust or otherwise, to be directed to the center for carrying out the purposes of the center. The center may solicit contracts for work, financial and in-kind contributions, and support from private industries, interest groups, federal and state sources, and other sources. It may also use separately appropriated funds of the University of Washington for the center's activities.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1877-S.SL.pdf?cite=1991%20c%20316%20§%204[1991 c 316 § 4]; ]

== 43.30.835 - Forest biomass demonstration projects.
. The department may develop and implement forest biomass energy demonstration projects, one east of the crest of the Cascade mountains and one west of the crest of the Cascade mountains. The demonstration projects must be designed to:

.. Reveal the utility of Washington's public and private forest biomass feedstock;

.. Create green jobs and generate renewable energy;

.. Generate revenues or improve asset values for beneficiaries of state lands and state forestlands;

.. Improve forest health, reduce pollution, and restore ecological function; and

.. Avoid interfering with the current working area for forest biomass collection surrounding an existing fixed location biomass energy production site.

. To develop and implement the forest biomass energy demonstration projects, the department may form forest biomass energy partnerships or cooperatives.

. The forest biomass energy partnerships or cooperatives are encouraged to be public-private partnerships focused on convening the entities necessary to grow, harvest, process, transport, and utilize forest biomass to generate renewable energy. Particular focus must be given to recruiting and employing emerging technologies that can locally process forest biomass feedstock to create local green jobs and reduce transportation costs.

. The forest biomass energy partnerships or cooperatives may include, but are not limited to: Entrepreneurs or organizations developing and operating emerging technology to process forest biomass; industrial electricity producers; contractors capable of providing the local labor needed to collect, process, and transport forest biomass feedstocks; tribes; federal land management agencies; county, city, and other local governments; the *department of community, trade, and economic development; state trust land managers; an organization dedicated to protecting and strengthening the jobs, rights, and working conditions of Washington's working families; accredited research institution representatives; an industrial timberland manager; a small forestland owner; and a not-for-profit conservation organization.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2165.SL.pdf?cite=2009%20c%20163%20§%202[2009 c 163 § 2]; ]

== 43.30.840 - Grants or financing.
For the purposes of implementing chapter 163, Law of 2009, the department may seek grants or financing from the federal government, industry, or philanthropists.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2165.SL.pdf?cite=2009%20c%20163%20§%204[2009 c 163 § 4]; ]

