= 43.52A - Electric power and conservation planning council—State's members.
:toc:

== 43.52A.010 - State agreement to participate in Pacific Northwest Electric Power and Conservation Planning Council.
The state of Washington agrees to participate in the Pacific Northwest Electric Power and Conservation Planning Council pursuant to the Pacific Northwest Electric Power Planning and Conservation Act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c14.pdf?cite=1981%20c%2014%20§%201[1981 c 14 § 1]; ]

== 43.52A.020 - Definitions.
As used in this chapter:

. The term "the act" means the Pacific Northwest Electric Power Planning and Conservation Act.

. The term "council" means the Pacific Northwest Electric Power and Conservation Planning Council.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c14.pdf?cite=1981%20c%2014%20§%202[1981 c 14 § 2]; ]

== 43.52A.030 - Appointment of members.
The governor, with the consent of the senate, shall appoint two residents of Washington state to the council pursuant to the act. These persons shall undertake the functions and duties of members of the council as specified in the act and in appropriate state law. Upon appointment by the governor to the council, the nominee shall make available to the senate such disclosure information as is requested for the confirmation process, including that required in RCW 42.17A.710.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1048-S.SL.pdf?cite=2011%20c%2060%20§%2036[2011 c 60 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c34.pdf?cite=1984%20c%2034%20§%208[1984 c 34 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c14.pdf?cite=1981%20c%2014%20§%203[1981 c 14 § 3]; ]

== 43.52A.040 - Terms of members—Vacancies—Residence of members.
. Unless removed at the governor's pleasure, councilmembers shall serve a term ending January 15 of the third year following appointment except that, with respect to members initially appointed, the governor shall designate one member to serve a term ending January 15 of the second year following appointment. Initial appointments to the council shall be made within thirty days of March 9, 1981.

. Each member shall serve until a successor is appointed, but if a successor is not appointed within sixty days of the beginning of a new term, the member shall be considered reappointed, subject to the consent of the senate.

. A vacancy on the council shall be filled for the unexpired term by the governor, with the consent of the senate.

. For the first available appointment and at all times thereafter, one member of Washington's delegation to the council shall reside east of the crest of the Cascade Mountains and one member shall reside west of the crest of the Cascade Mountains, except as follows: Both members may reside on the same side of the Cascade Mountains as long as this deviation does not exceed 12 months in any 10-year period.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5126-S2.SL.pdf?cite=2021%20c%20316%20§%2043[2021 c 316 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c223.pdf?cite=1984%20c%20223%20§%201[1984 c 223 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c14.pdf?cite=1981%20c%2014%20§%204[1981 c 14 § 4]; ]

== 43.52A.050 - Sufficient time on council activities required—Technical assistance—Reimbursement—Liaison—Report—Compensation—Travel expenses.
. Councilmembers shall spend sufficient time on council activities to fully represent the state of Washington in carrying out the purposes of the act.

. State agencies shall provide technical assistance to councilmembers upon request. The councilmembers shall request that the council request the administrator of the Bonneville Power Administration to reimburse the state for the expenses associated with such assistance as provided in the act.

. The members of the council shall maintain liaison with the governor or his or her designees and the committees on energy and utilities, or their successor entities, of the senate and house of representatives.

. The members of the council shall submit to the governor and legislature an annual report describing the activities and plans of the council.

. Each member of the council shall receive compensation to be determined by the governor and applicable federal law and shall be reimbursed for travel expenses under RCW 43.03.050 and 43.03.060, as now or hereafter amended.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%205139[2009 c 549 § 5139]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c14.pdf?cite=1981%20c%2014%20§%205[1981 c 14 § 5]; ]

