= 43.71 - Washington health benefit exchange.
:toc:

== 43.71.005 - Finding—Intent.
. The legislature finds that the affordable care act requires the establishment of health benefit exchanges. The legislature intends to establish an exchange, including a governance structure. There are many policy decisions associated with establishing an exchange that need to be made that will take a great deal of effort and expertise. It is therefore the intent of the legislature to establish a process through which these policy decisions can be made by the legislature and the governor by the deadline established in the affordable care act.

. The exchange is intended to:

.. Increase access to quality affordable health care coverage, reduce the number of uninsured persons in Washington state, and increase the availability of health care coverage through the private health insurance market to qualified individuals and small employers;

.. Provide consumer choice and portability of health insurance, regardless of employment status;

.. Create an organized, transparent, and accountable health insurance marketplace for Washingtonians to purchase affordable, quality health care coverage, to claim available federal refundable premium tax credits and cost-sharing subsidies, and to meet the personal responsibility requirements for minimum essential coverage as provided under the federal affordable care act;

.. Promote consumer literacy and empower consumers to compare plans and make informed decisions about their health care and coverage;

.. Effectively and efficiently administer health care subsidies and determination of eligibility for participation in publicly subsidized health care programs, including the exchange;

.. Create a health insurance market that competes on the basis of price, quality, service, and other innovative efforts;

.. Operate in a manner compatible with efforts to improve quality, contain costs, and promote innovation;

.. Recognize the need for a private health insurance market to exist outside of the exchange; and

.. Recognize that the regulation of the health insurance market, both inside and outside the exchange, should continue to be performed by the insurance commissioner.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5445-S.SL.pdf?cite=2011%20c%20317%20§%201[2011 c 317 § 1]; ]

== 43.71.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise. Terms and phrases used in this chapter that are not defined in this section must be defined as consistent with implementation of a state health benefit exchange pursuant to applicable federal law.

. "Authority" means the Washington state health care authority, established under chapter 41.05 RCW.

. "Board" means the governing board established in RCW 43.71.020.

. "Commissioner" means the insurance commissioner, established in Title 48 RCW.

. "Exchange" means the Washington health benefit exchange established in RCW 43.71.020.

. "Self-sustaining" means capable of operating with revenue attributable to the operations of the exchange. Self-sustaining sources include, but are not limited to, federal grants, federal premium tax subsidies and credits, charges to health carriers, premiums paid by enrollees, and premium taxes under RCW 48.14.0201(5)(b) and 48.14.020(2).

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2516-S.SL.pdf?cite=2018%20c%2044%20§%201[2018 c 44 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1947-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%206%20§%201[2013 2nd sp.s. c 6 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=2012%20c%2087%20§%202[2012 c 87 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5445-S.SL.pdf?cite=2011%20c%20317%20§%202[2011 c 317 § 2]; ]

== 43.71.020 - Washington health benefit exchange.
. The Washington health benefit exchange is established and constitutes a self-sustaining public-private partnership separate and distinct from the state, exercising functions delineated in chapter 317, Laws of 2011. By January 1, 2014, the exchange shall operate consistent with applicable federal law subject to statutory authorization. The exchange shall have a governing board consisting of persons with expertise in the Washington health care system and private and public health care coverage. The membership of the board shall be appointed as follows:

.. Each of the two largest caucuses in both the house of representatives and the senate shall submit to the governor a list of five nominees who are not legislators or employees of the state or its political subdivisions, with no caucus submitting the same nominee.

... The nominations from the largest caucus in the house of representatives must include at least one employee benefit specialist;

... The nominations from the second largest caucus in the house of representatives must include at least one health economist or actuary;

... The nominations from the largest caucus in the senate must include at least one representative of health consumer advocates;

... The nominations from the second largest caucus in the senate must include at least one representative of small business;

.. The remaining nominees must have demonstrated and acknowledged expertise in at least one of the following areas: Individual health care coverage, small employer health care coverage, health benefit plan administration, health care finance and economics, actuarial science, or administering a public or private health care delivery system.

.. The governor shall appoint two members from each list submitted by the caucuses under (a) of this subsection. The appointments made under this subsection (1)(b) must include at least one employee benefits specialist, one health economist or actuary, one representative of small business, and one representative of health consumer advocates. The remaining four members must have a demonstrated and acknowledged expertise in at least one of the following areas: Individual health care coverage, small employer health care coverage, health benefit plan administration, health care finance and economics, actuarial science, or administering a public or private health care delivery system.

.. The governor shall appoint a ninth member to serve as chair. The chair may not be an employee of the state or its political subdivisions. The chair shall serve as a nonvoting member except in the case of a tie.

.. The following members shall serve as nonvoting, ex officio members of the board:

... The insurance commissioner or his or her designee; and

... The administrator of the health care authority, or his or her designee.

. Initial members of the board shall serve staggered terms not to exceed four years. Members appointed thereafter shall serve two-year terms.

. A member of the board whose term has expired or who otherwise leaves the board shall be replaced by gubernatorial appointment. Upon the expiration of a member's term, the member shall continue to serve until a successor has been appointed and has assumed office. When the person leaving was nominated by one of the caucuses of the house of representatives or the senate, his or her replacement shall be appointed from a list of five nominees submitted by that caucus within thirty days after the person leaves. If the member to be replaced is the chair, the governor shall appoint a new chair within thirty days after the vacancy occurs. A person appointed to replace a member who leaves the board prior to the expiration of his or her term shall serve only the duration of the unexpired term. Members of the board may be reappointed to multiple terms.

. No board member may be appointed if his or her participation in the decisions of the board could benefit his or her own financial interests or the financial interests of an entity he or she represents. A board member who develops such a conflict of interest shall resign or be removed from the board.

. Members of the board must be reimbursed for their travel expenses while on official business in accordance with RCW 43.03.050 and 43.03.060. The board shall prescribe rules for the conduct of its business. Meetings of the board are at the call of the chair.

. The exchange and the board are subject only to the provisions of chapter 42.30 RCW, the open public meetings act, and chapter 42.56 RCW, the public records act, and not to any other law or regulation generally applicable to state agencies. Consistent with the open public meetings act, the board may hold executive sessions to consider proprietary or confidential nonpublished information.

. [Empty]
.. The board shall establish an advisory committee to allow for the views of the health care industry and other stakeholders to be heard in the operation of the health benefit exchange.

.. The board may establish technical advisory committees or seek the advice of technical experts when necessary to execute the powers and duties included in chapter 317, Laws of 2011.

. Members of the board are not civilly or criminally liable and may not have any penalty or cause of action of any nature arise against them for any action taken or not taken, including any discretionary decision or failure to make a discretionary decision, when the action or inaction is done in good faith and in the performance of the powers and duties under chapter 317, Laws of 2011. Nothing in this section prohibits legal actions against the board to enforce the board's statutory or contractual duties or obligations.

. In recognition of the government-to-government relationship between the state of Washington and the federally recognized tribes in the state of Washington, the board shall consult with the American Indian health commission.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2516-S.SL.pdf?cite=2018%20c%2044%20§%202[2018 c 44 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=2012%20c%2087%20§%203[2012 c 87 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5445-S.SL.pdf?cite=2011%20c%20317%20§%203[2011 c 317 § 3]; ]

== 43.71.030 - Exchange—Powers and duties—Annual report and plan.
. The exchange has the authority to:

.. Provide an application and enrollment portal for individual and small group health and dental insurance and state and federal health care programs;

.. Certify qualified health and dental plans to be offered for enrollment through the exchange;

.. Provide consumer education and assistance regarding cost and coverage of certified plans, plan selection, eligibility for subsidies, and health insurance literacy, which must include, but not be limited to, a web site, toll-free call center, and consumer assistance by navigators and insurance producers;

.. Determine eligibility for premium tax credits, cost-sharing reductions, other available subsidies, and enrollment in state and federal health care programs consistent with applicable federal law; and

.. Provide data and assistance necessary to facilitate payments of premium tax credits and other subsidies.

. The exchange may, in exercising its authority consistent with the purposes of this chapter: (a) Sue and be sued in its own name; (b) make and execute agreements, contracts, and other instruments, with any public or private person or entity; (c) employ, contract with, or engage personnel; (d) pay administrative costs; (e) accept grants, donations, loans of funds, and contributions in money, services, materials or otherwise, from the United States or any of its agencies, from the state of Washington and its agencies or from any other source, and use or expend those moneys, services, materials, or other contributions; (f) aggregate or delegate the aggregation of funds that comprise the premium for a health plan; and (g) perform other duties necessary for enrollment in health coverage through the exchange.

. The board shall develop and implement a methodology to ensure the exchange is self-sustaining. The board shall seek input from health carriers to develop funding mechanisms that fairly and equitably apportion among carriers the reasonable administrative costs and expenses incurred to implement the provisions of this chapter.

. The board shall establish policies that permit city and county governments, Indian tribes, tribal organizations, urban Indian organizations, private foundations, and other entities to pay premiums and cost sharing on behalf of qualified individuals.

. The employees of the exchange may participate in the public employees' retirement system under chapter 41.40 RCW and the public employees' benefits board under chapter 41.05 RCW.

. Qualified employers may access coverage for their employees through the exchange for small groups under applicable federal law. The exchange shall enable any qualified employer to specify a level of coverage so that any of its employees may enroll in any qualified health plan offered through the small group exchange at the specified level of coverage. The exchange may offer information to consumers and small businesses about qualified small employer health reimbursement arrangements.

. The exchange shall report its activities and status to the governor and the legislature as requested, and no less often than annually.

. By January 1st of each year, the exchange must submit to the legislature, the governor's office, and the board an annual financial report that identifies the annual cost of operating the exchange. The report must identify specific reductions in spending in the following areas: Call center, information technology, and staffing. The report must include:

.. A report of all expenses;

.. Beginning and ending fund balances, by fund source;

.. Any contracts or contract amendments signed by the exchange;

.. An accounting of staff required to operate the exchange broken out by full-time equivalent positions, contracted employees, temporary staff, and any other relevant designation that indicates the staffing level of the exchange; and

.. A per member per month metric, per qualified health plan enrollee and apple health enrollee, calculated by dividing funds allocated for the exchange over the 2015-2017 biennium by the number of enrollees in both qualified health plans and apple health during the year.

. [Empty]
.. The exchange shall prepare and annually update a strategic plan for the development, maintenance, and improvement of exchange operations for the purpose of assisting the exchange in establishing priorities to better serve the needs of its specific constituency and the public in general. The strategic plan is the exchange's process for defining its methodology for achieving optimal outcomes, for complying with applicable state and federal statutes, rules, regulations, and mandatory policies, and for guaranteeing an appropriate level of transparency in its dealings. The strategic plan must include, but is not limited to:

... Comprehensive five-year and ten-year plans for the exchange's direction with clearly defined outcomes and goals;

... Concrete plans for achieving or surpassing desired outcomes and goals;

... Strategy for achieving enrollment and reenrollment targets;

... Detailed stakeholder and external communication plans; and

.. Identification of funding sources, and a plan for how it will fund and allocate resources to pursue desired goals and outcomes.

.. The strategic plan and its updates must be submitted to the authority, the appropriate committees of the legislature, and the board by September 30th of each year.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2516-S.SL.pdf?cite=2018%20c%2044%20§%203[2018 c 44 § 3]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6089.SL.pdf?cite=2015%203rd%20sp.s.%20c%2033%20§%201[2015 3rd sp.s. c 33 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=2012%20c%2087%20§%204[2012 c 87 § 4]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5445-S.SL.pdf?cite=2011%20c%20317%20§%204[2011 c 317 § 4]; ]

== 43.71.060 - Health benefit exchange account.
. The health benefit exchange account is created in the state treasury. Moneys in the account may be spent only after appropriation. Expenditures from the account may only be used to fund the operation of the exchange and identification, collection, and distribution of premium taxes collected under RCW 48.14.0201(5)(b) and 48.14.020(2).

. The following funds must be deposited in the account:

.. Premium taxes collected under RCW 48.14.0201(5)(b) and 48.14.020(2);

.. Assessments authorized under RCW 43.71.080; and

.. Amounts transferred by the pool administrator as specified in the state omnibus appropriations act pursuant to RCW 48.41.090.

. All receipts from federal grants received may be deposited into the account. Expenditures from the account may be used only for purposes consistent with the grants.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2516-S.SL.pdf?cite=2018%20c%2044%20§%204[2018 c 44 § 4]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1947-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%206%20§%202[2013 2nd sp.s. c 6 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=2012%20c%2087%20§%205[2012 c 87 § 5]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5445-S.SL.pdf?cite=2011%20c%20317%20§%207[2011 c 317 § 7]; ]

== 43.71.065 - Qualified health plans—Certification—Criteria stand-alone dental plans—Direct primary care medical home plans—Appeals.
. The board shall certify a plan as a qualified health plan to be offered through the exchange if the plan is determined by the:

.. Insurance commissioner to meet the requirements of Title 48 RCW and rules adopted by the commissioner pursuant to chapter 34.05 RCW to implement the requirements of Title 48 RCW;

.. Board to meet the requirements of applicable federal law for certification as a qualified health plan; and

.. Board to include tribal clinics and urban Indian clinics as essential community providers in the plan's provider network consistent with federal law. If consistent with federal law, integrated delivery systems shall be exempt from the requirement to include essential community providers in the provider network.

. Consistent with applicable federal law, the board shall allow stand-alone dental plans to offer coverage in the exchange beginning January 1, 2014. Dental benefits offered in the exchange must be offered and priced separately to assure transparency for consumers.

. The board may permit direct primary care medical home plans, consistent with applicable federal law, to be offered in the exchange.

. Upon request by the board, a state agency shall provide information to the board for its use in determining if the requirements under subsection (1)(b) or (c) of this section have been met. Unless the agency and the board agree to a later date, the agency shall provide the information within sixty days of the request. The exchange shall reimburse the agency for the cost of compiling and providing the requested information within one hundred eighty days of its receipt.

. A decision by the board denying a request to certify or recertify a plan as a qualified health plan may be appealed according to procedures adopted by the board.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2516-S.SL.pdf?cite=2018%20c%2044%20§%205[2018 c 44 § 5]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=2012%20c%2087%20§%208[2012 c 87 § 8]; ]

== 43.71.067 - Qualified health plans—Prohibited marketing practices or benefit designs—Rules.
. For qualified health plans, an issue [issuer] offering a qualified health plan may not employ marketing practices or benefit designs that have the effect of discouraging enrollment in the plan by individuals with significant health needs.

. Unless preempted by federal law, the commissioner shall adopt any rules necessary to implement this section, consistent with federal rules and guidance in effect on January 1, 2017, implementing the patient protection and affordable care act.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1870-S.SL.pdf?cite=2019%20c%2033%20§%2016[2019 c 33 § 16]; ]

== 43.71.070 - Rating system—Rating factors.
The board shall establish a rating system consistent with applicable federal law, for qualified health plans to assist consumers in evaluating plan choices in the exchange. Rating factors established by the board may include, but are not limited to:

. Affordability with respect to premiums, deductibles, and point-of-service cost-sharing;

. Enrollee satisfaction;

. Provider reimbursement methods that incentivize health homes or chronic care management or care coordination for enrollees with complex, high-cost, or multiple chronic conditions;

. Promotion of appropriate primary care and preventive services utilization;

. High standards for provider network adequacy, including consumer choice of providers and service locations and robust provider participation intended to improve access to underserved populations through participation of essential community providers, family planning providers and pediatric providers;

. High standards for covered services, including languages spoken or transportation assistance; and

. Coverage of benefits for spiritual care services that are deductible under section 213(d) of the internal revenue code.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2516-S.SL.pdf?cite=2018%20c%2044%20§%206[2018 c 44 § 6]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=2012%20c%2087%20§%209[2012 c 87 § 9]; ]

== 43.71.075 - Navigator not soliciting or negotiating insurance—Health care information—Protection—Disclosure—Notification.
. A person or entity functioning as a navigator shall not be considered soliciting or negotiating insurance as stated under chapter 48.17 RCW.

. [Empty]
.. A person or entity functioning as a navigator may only request health care information that is relevant to the specific assessment and recommendation of health plan options. Any health care information received by a navigator may not be disclosed to any third party that is not part of the enrollment process and must be destroyed after enrollment has been completed.

.. If a person's health care information is received and disclosed to a third party in violation of (a) of this subsection, the navigator must notify the person of the breach. The exchange must develop a policy to establish a reasonable notification period and what information must be included in the notice. This policy and information on the exchange's confidentiality policies must be made available on the exchange's web site.

. For the purposes of this section:

.. "Health care information" has the meaning provided in RCW 70.02.010.

.. "Navigator" means a person or entity certified by the exchange to provide culturally and linguistically appropriate education and assistance and facilitate enrollment in qualified health plans and federal and state health care programs, in a manner consistent with applicable federal law.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2516-S.SL.pdf?cite=2018%20c%2044%20§%207[2018 c 44 § 7]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6265-S.SL.pdf?cite=2014%20c%20220%20§%203[2014 c 220 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=2012%20c%2087%20§%2025[2012 c 87 § 25]; ]

== 43.71.080 - Assessment to fund exchange—Generally—Stand-alone dental plans.
. [Empty]
.. Beginning January 1, 2015, the exchange may require each issuer writing premiums for qualified health benefit plans or stand-alone pediatric dental plans offered through the exchange to pay an assessment in an amount necessary to fund the operations of the exchange, applicable to operational costs incurred beginning January 1, 2015.

.. The assessment is an exchange user fee. Assessments of issuers may be made only if the amount of expected premium taxes, as provided under RCW 48.14.0201(5)(b) and 48.14.020(2), and other funds deposited in the health benefit exchange account in the current calendar year (excluding premium taxes on stand-alone family dental plans and the assessment received under subsection (3) of this section applicable to stand-alone family dental plans) are insufficient to fund exchange operations in the following calendar year at the level authorized by the legislature for that purpose in the omnibus appropriations act plus three months of additional operating costs.

.. A health benefit plan or stand-alone dental plan may identify the amount of the assessment to enrollees, but must not bill the enrollee for the amount of the assessment separately from the premium.

. The board, in collaboration with the issuers, the health care authority, and the commissioner, must establish a fair and transparent process for calculating the assessment amount. The process must meet the following requirements:

.. The assessment only applies to issuers that offer coverage in the exchange and only for those market segments offered and must be based on the number of enrollees in qualified health plans and stand-alone dental plans in the exchange for a calendar year;

.. The assessment must be established on a flat dollar and cents amount per member per month, and the assessment for stand-alone pediatric dental plans must be proportional to the premiums paid for stand-alone dental plans in the exchange;

.. Issuers must be notified of the assessment amount by the exchange on a timely basis;

.. An appropriate assessment reconciliation process must be established by the exchange that is administratively efficient;

.. Issuers must remit the assessment due to the exchange in quarterly installments after receiving notification from the exchange of the due dates of the quarterly installments;

.. A procedure must be established to allow issuers subject to assessments under this section to have grievances reviewed by an impartial body and reported to the board; and

.. A procedure for enforcement must be established if an issuer fails to remit its assessment amount to the exchange within ten business days of the quarterly installment due date.

. [Empty]
.. The exchange may require each issuer writing premiums for stand-alone family dental plans offered through the exchange to pay an assessment in an amount necessary to fund the operational costs of offering family dental plans in the exchange, applicable to operational costs incurred beginning January 1, 2017.

.. The assessment is an exchange user fee. Assessments of issuers may be made only if the amount of expected premium tax received from stand-alone family dental plans, as provided under RCW 48.14.0201(5)(b) and 48.14.020(2), in the current year is insufficient to fund the operational costs estimated to be attributable to offering such stand-alone family dental plans in the exchange, including an allocation of costs to proportionately cover overall exchange operational costs, in the following calendar year, plus three months of additional operating costs.

.. If the exchange is charging an assessment, the exchange shall display the amount of the assessment per member per month for enrollees. A stand-alone family dental plan may identify the amount of the assessment to enrollees, but must not bill the enrollee for the amount of the assessment separately from the premium.

.. The board, in collaboration with the family dental issuers and the commissioner, must establish a fair and transparent process for calculating the assessment amount, including the allocation of overall exchange operational costs. The process must meet the following requirements:

... The assessment only applies to issuers that offer stand-alone family dental plans in the exchange and must be based on the number of enrollees in such plans in the exchange for a calendar year;

... The assessment must be established on a flat dollar and cents amount per member per month;

... The requirements included in subsection (2)(c) through (g) of this section shall apply to the assessment described in this subsection (3).

.. The board, in collaboration with issuers, shall annually assess the viability of offering stand-alone family dental plans on the exchange.

. For purposes of this section:

.. "Stand-alone family dental plan" means coverage for limited scope dental benefits meeting the requirements of section 9832(c)(2)(A) of the internal revenue code of 1986 and providing pediatric oral services that qualify as coverage for the minimum essential coverage requirement under applicable federal and state law.

.. "Stand-alone pediatric dental plan" means coverage only for pediatric oral services that qualify as coverage for the minimum essential coverage requirement under applicable federal and state law.

. The exchange shall deposit proceeds from the assessments in the health benefit exchange account under RCW 43.71.060.

. The assessment described in this section shall be considered a special purpose obligation or assessment in connection with coverage described in this section for the purpose of funding the operations of the exchange, and may not be applied by issuers to vary premium rates at the plan level.

. This section does not prohibit an enrollee of a qualified health plan in the exchange from purchasing a plan that offers dental benefits outside the exchange.

. This section does not prohibit an issuer from offering a plan that covers dental benefits that do not meet the requirements of a stand-alone family dental plan outside the exchange.

. The exchange shall monitor enrollment and provide periodic reports which must be available on its web site.

. The board shall offer all qualified health plans through the exchange, and the exchange shall not add criteria for certification of qualified health plans beyond those set out in RCW 43.71.065 without specific statutory direction. Nothing shall be construed to limit duties, obligations, and authority otherwise legislatively delegated or granted to the exchange.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2516-S.SL.pdf?cite=2018%20c%2044%20§%208[2018 c 44 § 8]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2768.SL.pdf?cite=2016%20c%20133%20§%203[2016 c 133 § 3]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1947-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%206%20§%203[2013 2nd sp.s. c 6 § 3]; ]

== 43.71.095 - Standardized health plans.
. The exchange, in consultation with the commissioner, the authority, an independent actuary, and other stakeholders, must establish up to three standardized health plans for each of the bronze, silver, and gold levels.

.. The standardized health plans must be designed to reduce deductibles, make more services available before the deductible, provide predictable cost sharing, maximize subsidies, limit adverse premium impacts, reduce barriers to maintaining and improving health, and encourage choice based on value, while limiting increases in health plan premium rates.

.. The exchange may update the standardized health plans annually.

.. The exchange must provide a notice and public comment period before finalizing each year's standardized health plans.

.. The exchange must provide written notice of the standardized health plans to licensed health carriers by January 31st before the year in which the health plans are to be offered on the exchange. The exchange may make modifications to the standardized plans after January 31st to comply with changes to state or federal law or regulations.

. [Empty]
.. Beginning January 1, 2021, any health carrier offering a qualified health plan on the exchange must offer one silver standardized health plan and one gold standardized health plan on the exchange. If a health carrier offers a bronze health plan on the exchange, it must offer one bronze standardized health plan on the exchange.

.. [Empty]
... A health plan offering a standardized health plan under this section may also offer nonstandardized health plans on the exchange.

... The exchange, in consultation with the office of the insurance commissioner, shall analyze the impact to exchange consumers of offering only standard plans beginning in 2025 and submit a report to the appropriate committees of the legislature by December 1, 2023. The report must include an analysis of how plan choice and affordability will be impacted for exchange consumers across the state.

... The actuarial value of nonstandardized silver health plans offered on the exchange may not be less than the actuarial value of the standardized silver health plan with the lowest actuarial value.

.. A health carrier offering a standardized health plan on the exchange under this section must continue to meet all requirements for qualified health plan certification under RCW 43.71.065 including, but not limited to, requirements relating to rate review and network adequacy.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5526-S.SL.pdf?cite=2019%20c%20364%20§%201[2019 c 364 § 1]; ]

== 43.71.100 - Access to information about exclusion of mandated benefits from qualified health plans—Exchange's duties.
. Beginning November 1, 2021, the exchange shall provide individuals seeking to enroll in coverage on its web site with access to the information a health carrier must provide under RCW 48.43.725 for any qualified health plan the health carrier offers that excludes, under state or federal law, any benefit required or mandated by Title 48 RCW or rules adopted by the commissioner.

. The exchange may provide the access required under this section directly on its web site, through a link to an external web site, or in any other manner that allows consumers to easily access the information.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2554-S.SL.pdf?cite=2020%20c%20283%20§%202[2020 c 283 § 2]; ]

== 43.71.900 - Conflict with federal requirements—2011 c 317.
If any part of this act is found to be in conflict with federal requirements that are a prescribed condition to the allocation of federal funds to the state, the conflicting part of this act is inoperative solely to the extent of the conflict and with respect to the agencies directly affected, and this finding does not affect the operation of the remainder of this act in its application to the agencies concerned. Rules adopted under this act must meet federal requirements that are a necessary condition to the receipt of federal funds by the state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5445-S.SL.pdf?cite=2011%20c%20317%20§%209[2011 c 317 § 9]; ]

== 43.71.901 - Spiritual care services—2012 c 87.
Nothing in chapter 87, Laws of 2012 prohibits the offering of benefits for spiritual care services deductible under section 213(d) of the internal revenue code in health plans inside and outside of the exchange.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=2012%20c%2087%20§%2014[2012 c 87 § 14]; ]

