= 43.17 - Administrative departments and agencies—General provisions.
:toc:

== 43.17.010 - Departments created.
There shall be departments of the state government which shall be known as (1) the department of social and health services, (2) the department of ecology, (3) the department of labor and industries, (4) the department of agriculture, (5) the department of fish and wildlife, (6) the department of transportation, (7) the department of licensing, (8) the department of enterprise services, (9) the department of commerce, (10) the department of veterans affairs, (11) the department of revenue, (12) the department of retirement systems, (13) the department of corrections, (14) the department of health, (15) the department of financial institutions, (16) the department of archaeology and historic preservation, (17) the department of children, youth, and families, and (18) the Puget Sound partnership, which shall be charged with the execution, enforcement, and administration of such laws, and invested with such powers and required to perform such duties, as the legislature may provide.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20109[2017 3rd sp.s. c 6 § 109]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5931-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2043%20§%20107[2011 1st sp.s. c 43 § 107]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2009%20c%20565%20§%2025[2009 c 565 § 25]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5372-S.SL.pdf?cite=2007%20c%20341%20§%2046[2007 c 341 § 46]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2964-S2.SL.pdf?cite=2006%20c%20265%20§%20111[2006 c 265 § 111]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5056-S2.SL.pdf?cite=2005%20c%20333%20§%2010[2005 c 333 § 10]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2055-S.SL.pdf?cite=1993%20sp.s.%20c%202%20§%2016[1993 sp.s. c 2 § 16]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=1993%20c%20472%20§%2017[1993 c 472 § 17]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5868-S.SL.pdf?cite=1993%20c%20280%20§%2018[1993 c 280 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20810[1989 1st ex.s. c 9 § 810]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c506.pdf?cite=1987%20c%20506%20§%202[1987 c 506 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c466.pdf?cite=1985%20c%20466%20§%2047[1985 c 466 § 47]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c125.pdf?cite=1984%20c%20125%20§%2012[1984 c 125 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c136.pdf?cite=1981%20c%20136%20§%2061[1981 c 136 § 61]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c10.pdf?cite=1979%20c%2010%20§%201[1979 c 10 § 1]; prior:  1977 ex.s. c 334 § 5; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c151.pdf?cite=1977%20ex.s.%20c%20151%20§%2020[1977 ex.s. c 151 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977c7.pdf?cite=1977%20c%207%20§%201[1977 c 7 § 1]; prior: 1975-'76 2nd ex.s. c 115 § 19; 1975-'76 2nd ex.s. c 105 § 24; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c11.pdf?cite=1971%20c%2011%20§%201[1971 c 11 § 1]; prior:  1970 ex.s. c 62 § 28; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c18.pdf?cite=1970%20ex.s.%20c%2018%20§%2050[1970 ex.s. c 18 § 50]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c32.pdf?cite=1969%20c%2032%20§%201[1969 c 32 § 1]; prior:  1967 ex.s. c 26 § 12; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c242.pdf?cite=1967%20c%20242%20§%2012[1967 c 242 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c156.pdf?cite=1965%20c%20156%20§%2020[1965 c 156 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.17.010[1965 c 8 § 43.17.010]; prior:  1957 c 215 § 19; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c285.pdf?cite=1955%20c%20285%20§%202[1955 c 285 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c174.pdf?cite=1953%20c%20174%20§%201[1953 c 174 § 1]; prior:  1937 c 111 § 1, part; RRS § 10760-2, part.   1935 c 176 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c3.pdf?cite=1933%20c%203%20§%201[1933 c 3 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c115.pdf?cite=1929%20c%20115%20§%201[1929 c 115 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c7.pdf?cite=1921%20c%207%20§%202[1921 c 7 § 2]; RRS § 10760. (iii) 1945 c 267 § 1, part; Rem. Supp. 1945 § 10459-1, part. (iv)  1947 c 114 § 5; Rem. Supp. 1947 § 10786-10c; ]

== 43.17.020 - Chief executive officers—Appointment.
There shall be a chief executive officer of each department to be known as: (1) The secretary of social and health services, (2) the director of ecology, (3) the director of labor and industries, (4) the director of agriculture, (5) the director of fish and wildlife, (6) the secretary of transportation, (7) the director of licensing, (8) the director of enterprise services, (9) the director of commerce, (10) the director of veterans affairs, (11) the director of revenue, (12) the director of retirement systems, (13) the secretary of corrections, (14) the secretary of health, (15) the director of financial institutions, (16) the director of the department of archaeology and historic preservation, (17) the secretary of children, youth, and families, and (18) the executive director of the Puget Sound partnership.

Such officers, except the director of fish and wildlife, shall be appointed by the governor, with the consent of the senate, and hold office at the pleasure of the governor. The director of fish and wildlife shall be appointed by the fish and wildlife commission as prescribed by RCW 77.04.055.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20110[2017 3rd sp.s. c 6 § 110]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5931-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2043%20§%20108[2011 1st sp.s. c 43 § 108]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2009%20c%20565%20§%2026[2009 c 565 § 26]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5372-S.SL.pdf?cite=2007%20c%20341%20§%2047[2007 c 341 § 47]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2964-S2.SL.pdf?cite=2006%20c%20265%20§%20112[2006 c 265 § 112]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5056-S2.SL.pdf?cite=2005%20c%20333%20§%2011[2005 c 333 § 11]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5513.SL.pdf?cite=2005%20c%20319%20§%202[2005 c 319 § 2]; 1995 1st sp.s. c 2 § 2 (Referendum Bill No. 45, approved November 7, 1995); prior:  1993 sp.s. c 2 § 17; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=1993%20c%20472%20§%2018[1993 c 472 § 18]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5868-S.SL.pdf?cite=1993%20c%20280%20§%2019[1993 c 280 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20811[1989 1st ex.s. c 9 § 811]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c506.pdf?cite=1987%20c%20506%20§%203[1987 c 506 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c466.pdf?cite=1985%20c%20466%20§%2048[1985 c 466 § 48]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c125.pdf?cite=1984%20c%20125%20§%2013[1984 c 125 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c136.pdf?cite=1981%20c%20136%20§%2062[1981 c 136 § 62]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c10.pdf?cite=1979%20c%2010%20§%202[1979 c 10 § 2]; prior:  1977 ex.s. c 334 § 6; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c151.pdf?cite=1977%20ex.s.%20c%20151%20§%2021[1977 ex.s. c 151 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977c7.pdf?cite=1977%20c%207%20§%202[1977 c 7 § 2]; prior: 1975-'76 2nd ex.s. c 115 § 20; 1975-'76 2nd ex.s. c 105 § 25; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c11.pdf?cite=1971%20c%2011%20§%202[1971 c 11 § 2]; prior:  1970 ex.s. c 62 § 29; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c18.pdf?cite=1970%20ex.s.%20c%2018%20§%2051[1970 ex.s. c 18 § 51]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c32.pdf?cite=1969%20c%2032%20§%202[1969 c 32 § 2]; prior:  1967 ex.s. c 26 § 13; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c242.pdf?cite=1967%20c%20242%20§%2013[1967 c 242 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c156.pdf?cite=1965%20c%20156%20§%2021[1965 c 156 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.17.020[1965 c 8 § 43.17.020]; prior:  1957 c 215 § 20; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c285.pdf?cite=1955%20c%20285%20§%203[1955 c 285 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c174.pdf?cite=1953%20c%20174%20§%202[1953 c 174 § 2]; prior:   1935 c 176 § 2; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c3.pdf?cite=1933%20c%203%20§%202[1933 c 3 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c115.pdf?cite=1929%20c%20115%20§%202[1929 c 115 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c7.pdf?cite=1921%20c%207%20§%203[1921 c 7 § 3]; RRS § 10761.  1937 c 111 § 1, part; RRS § 10760. (iii) 1945 c 267 § 1, part; Rem. Supp. 1945 § 10459-1, part; ]

== 43.17.030 - Powers and duties—Oath.
The directors of the several departments shall exercise such powers and perform such executive and administrative duties as are provided by law.

Each appointive officer before entering upon the duties of his or her office shall take and subscribe the oath of office prescribed by law for elective state officers, and file the same in the office of the secretary of state.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%205058[2009 c 549 § 5058]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.17.030[1965 c 8 § 43.17.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c7.pdf?cite=1921%20c%207%20§%2018[1921 c 7 § 18]; RRS § 10776; ]

== 43.17.040 - Chief assistant director—Powers.
The director of each department may, from time to time, designate and deputize one of the assistant directors of his or her department to act as the chief assistant director, who shall have charge and general supervision of the department in the absence or disability of the director, and who, in case a vacancy occurs in the office of director, shall continue in charge of the department until a director is appointed and qualified, or the governor appoints an acting director.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%205059[2009 c 549 § 5059]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.17.040[1965 c 8 § 43.17.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c7.pdf?cite=1921%20c%207%20§%20118[1921 c 7 § 118]; RRS § 10876; ]

== 43.17.050 - Office at capital—Branch offices.
Each department shall maintain its principal office at the state capital. The director of each department may, with the approval of the governor, establish and maintain branch offices at other places than the state capital for the conduct of one or more of the functions of his or her department.

The governor, in his or her discretion, may require all administrative departments of the state and the appointive officers thereof, other than those created by this chapter, to maintain their principal offices at the state capital in rooms to be furnished by the director of enterprise services.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5024.SL.pdf?cite=2015%20c%20225%20§%2062[2015 c 225 § 62]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%205060[2009 c 549 § 5060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.17.050[1965 c 8 § 43.17.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c7.pdf?cite=1921%20c%207%20§%2020[1921 c 7 § 20]; RRS § 10778.   1921 c 7 § 134; RRS § 10892; ]

== 43.17.060 - Departmental rules and regulations.
The director of each department may prescribe rules and regulations, not inconsistent with law, for the government of his or her department, the conduct of its subordinate officers and employees, the disposition and performance of its business, and the custody, use, and preservation of the records, papers, books, documents, and property pertaining thereto.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%205061[2009 c 549 § 5061]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.17.060[1965 c 8 § 43.17.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c7.pdf?cite=1921%20c%207%20§%2019[1921 c 7 § 19]; RRS § 10777; ]

== 43.17.070 - Administrative committees.
There shall be administrative committees of the state government, which shall be known as: (1) The state finance committee and (2) the state capitol committee.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c40.pdf?cite=1982%20c%2040%20§%208[1982 c 40 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.17.070[1965 c 8 § 43.17.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c115.pdf?cite=1929%20c%20115%20§%203[1929 c 115 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c7.pdf?cite=1921%20c%207%20§%204[1921 c 7 § 4]; RRS § 10762; ]

== 43.17.095 - Option to submit document, form, or payment electronically—Requirements.
. In any instance where a state agency requires that a business submit a document, form, or payment of a fee in paper format, the state agency must provide the business an option to submit such requirement electronically.

. A business may authorize a second party to meet the requirements imposed by a state agency under subsection (1) of this section on its behalf.

. The director of a state agency or the director's designee may exempt a document, form, or payment of a fee from the requirements of this section if:

.. [Empty]
... There is a legal requirement for such materials to be submitted in paper format; or

... It is not technically or fiscally feasible or practical, or in the best interest of businesses for such materials to be submitted electronically; and

.. Within existing resources, the director or the director's designee establishes and maintains a process to notify the public regarding such exemptions.

. Agencies must add the capability to submit existing documents, forms, and fees electronically as part of their normal operations. New documents, forms, and fees required of a business must be capable of electronic submission within a reasonable time following either their creation or the implementation of the new requirement.

. Agencies must document how they plan to transition from paper to electronic forms.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6354-S.SL.pdf?cite=2012%20c%20127%20§%201[2012 c 127 § 1]; ]

== 43.17.100 - Surety bonds for appointive state officers and employees.
Every appointive state officer and employee of the state shall give a surety bond, payable to the state in such sum as shall be deemed necessary by the director of the department of enterprise services, conditioned for the honesty of the officer or employee and for the accounting of all property of the state that shall come into his or her possession by virtue of his or her office or employment, which bond shall be approved as to form by the attorney general and shall be filed in the office of the secretary of state.

The director of enterprise services may purchase one or more blanket surety bonds for the coverage required in this section.

Any bond required by this section shall not be considered an official bond and shall not be subject to chapter 42.08 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5024.SL.pdf?cite=2015%20c%20225%20§%2063[2015 c 225 § 63]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%205062[2009 c 549 § 5062]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c270.pdf?cite=1977%20ex.s.%20c%20270%20§%207[1977 ex.s. c 270 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c40.pdf?cite=1975%20c%2040%20§%206[1975 c 40 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.17.100[1965 c 8 § 43.17.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c7.pdf?cite=1921%20c%207%20§%2016[1921 c 7 § 16]; RRS § 10774; ]

== 43.17.110 - Data, information, interdepartmental assistance.
Where power is vested in a department or officer to inspect, examine, secure data or information from, or procure assistance from, another department or officer, such other department or officer shall submit to such inspection or examination, and furnish the data, information, or assistance required.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.17.110[1965 c 8 § 43.17.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c7.pdf?cite=1921%20c%207%20§%20128[1921 c 7 § 128]; RRS § 10886; ]

== 43.17.120 - Designation of agency to carry out federal social security disability program.
Such state agency as the governor may designate is hereby authorized to enter into an agreement on behalf of the state with the Secretary of Health, Education and Welfare to carry out the provisions of the federal social security act, as amended, relating to the making of determinations of disability under title II of such act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.17.120[1965 c 8 § 43.17.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c200.pdf?cite=1955%20c%20200%20§%201[1955 c 200 § 1]; ]

== 43.17.130 - Designation of agency to carry out federal social security disability program—Appointment of personnel.
The state agency entering into such agreement shall appoint such professional personnel and other assistants and employees as may be reasonably necessary to carry out the provisions of RCW 43.17.120 and 43.17.130.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.17.130[1965 c 8 § 43.17.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c200.pdf?cite=1955%20c%20200%20§%202[1955 c 200 § 2]; ]

== 43.17.150 - Receipt of property or money from United States attorney general—Use, expenditure—Deposit.
. Each state agency is authorized to receive property or money made available by the attorney general of the United States under section 881(e) of Title 21 of the United States Code and, except as required to the contrary under subsection (2) of this section, to use the property or spend the money for such purposes as are permitted under both federal law and the state law specifying the powers and duties of the agency.

. Unless precluded by federal law, all funds received by a state agency under section 881(e) of Title 21 of the United States Code shall be promptly deposited into the state general fund.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5073-S.SL.pdf?cite=2009%20c%20479%20§%2027[2009 c 479 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c246.pdf?cite=1986%20c%20246%20§%201[1986 c 246 § 1]; ]

== 43.17.200 - Allocation of moneys for acquisition of works of art—Expenditure by arts commission—Conditions.
. All state agencies including all state departments, boards, councils, commissions, and quasi public corporations shall allocate, as a nondeductible item, out of any moneys appropriated for the original construction of any public building, an amount of one-half of one percent of the appropriation to be expended by the Washington state arts commission for the acquisition of works of art.

. For projects funded in the capital budget, a state agency, working with the Washington state arts commission, may expend up to ten percent of the projected art allocation for a project during the design phase in order to select an artist and design art to be integrated in the building design. The one-half of one percent to be expended by the Washington state arts commission must be adjusted downward by the amount expended by a state agency during the design phase of the capital project.

. The works of art may be placed on public lands, integral to or attached to a public building or structure, detached within or outside a public building or structure, part of a portable exhibition or collection, part of a temporary exhibition, or loaned or exhibited in other public facilities.

. In addition to the cost of the works of art, the one-half of one percent of the appropriation as provided herein shall be used to provide for the administration of the visual arts program, including conservation of the state art collection, by the Washington state arts commission and all costs for installation of the works of art. For the purpose of this section building shall not include highway construction sheds, warehouses, or other buildings of a temporary nature.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1318.SL.pdf?cite=2019%20c%20240%20§%202[2019 c 240 § 2]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6095-S.SL.pdf?cite=2018%20c%20298%20§%207016[2018 c 298 § 7016]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2188.SL.pdf?cite=2005%20c%2036%20§%204[2005 c 36 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c204.pdf?cite=1983%20c%20204%20§%204[1983 c 204 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c176.pdf?cite=1974%20ex.s.%20c%20176%20§%202[1974 ex.s. c 176 § 2]; ]

== 43.17.205 - Purchase of works of art—Interagency reimbursement for expenditure by visual arts program.
The funds allocated under RCW 43.17.200, 28A.335.210, and 28B.10.025 shall be subject to interagency reimbursement for expenditure by the visual arts program of the Washington state arts commission when the particular law providing for the appropriation becomes effective. For appropriations which are dependent upon the sale of bonds, the amount or proportionate amount of the moneys under RCW 43.17.200, 28A.335.210, and 28B.10.025 shall be subject to interagency reimbursement for expenditure by the visual arts program of the Washington state arts commission thirty days after the sale of a bond or bonds.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20574[1990 c 33 § 574]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c204.pdf?cite=1983%20c%20204%20§%203[1983 c 204 § 3]; ]

== 43.17.210 - Purchase of works of art—Procedure.
The Washington state arts commission shall determine the amount to be made available for the purchase of art in consultation with the agency, except where another person or agency is specified under RCW 43.19.455, 28A.335.210, or 28B.10.025, and payments therefor shall be made in accordance with law. The designation of projects and sites, selection, contracting, purchase, commissioning, reviewing of design, execution and placement, acceptance, maintenance, and sale, exchange, or disposition of works of art shall be the responsibility of the Washington state arts commission in consultation with the directors of the state agencies.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2188.SL.pdf?cite=2005%20c%2036%20§%205[2005 c 36 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20575[1990 c 33 § 575]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c204.pdf?cite=1983%20c%20204%20§%205[1983 c 204 § 5]; ]

== 43.17.230 - Emergency information telephone services—Accessibility from all phones required—Charges.
. The legislature finds that when the state provides emergency information by telephone to citizens that is of a critical nature, such as road or weather hazards, the information should be accessible from all residential, commercial, and coin-operated telephones. Information such as road and weather conditions should be available to all persons traveling within the state whether they own a telephone in this state or not.

. If an agency or department of the state makes emergency information services available by telephone, the agency or department shall ensure that the telephone line is accessible from all coin-operated telephones in this state by both the use of coins and the use of a telephone credit card.

. A state agency that provides an emergency information service by telephone may establish charges to recover the cost of those services. However, an agency charging for the service shall not price it at a profit to create excess revenue for the agency. The agency shall do a total cost-benefit analysis of the available methods of providing the service and shall adopt the method that provides the service at the lowest cost to the user and the agency.

. "Emergency information services," as used in this section, includes information on road and weather conditions.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c45.pdf?cite=1986%20c%2045%20§%201[1986 c 45 § 1]; ]

== 43.17.240 - Debts owed to the state—Interest rate.
Interest at the rate of one percent per month, or fraction thereof, shall accrue on debts owed to the state, starting on the date the debts become past due. This section does not apply to: (1) Any instance where such interest rate would conflict with the provisions of a contract or with the provisions of any other law; or (2) debts to be paid by other governmental units. The office of financial management may adopt rules specifying circumstances under which state agencies may waive interest, such as when assessment or collection of interest would not be cost-effective. This section does not affect any authority of the state to charge or collect interest under any other law on a debt owed to the state by a governmental unit. This section applies only to debts which become due on or after July 28, 1991.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1228.SL.pdf?cite=1991%20c%2085%20§%202[1991 c 85 § 2]; ]

== 43.17.250 - Countywide planning policy.
. Whenever a state agency is considering awarding grants or loans for a county, city, or town planning under RCW 36.70A.040 to finance public facilities, it shall consider whether the county, city, or town requesting the grant or loan has adopted a comprehensive plan and development regulations as required by RCW 36.70A.040.

. If a comprehensive plan, development regulation, or amendment thereto adopted by a county, city, or town has been appealed to the growth management hearings board under RCW 36.70A.280, the county, city, or town may not be determined to be ineligible or otherwise penalized in the acceptance of applications or the awarding of state agency grants or loans during the pendency of the appeal before the board or subsequent judicial appeals. This subsection (2) applies only to counties, cities, and towns that have: (a) Delayed the initial effective date of the action subject to the petition before the board until after the board issues a final determination; or (b) within thirty days of receiving notice of a petition for review by the board, delayed or suspended the effective date of the action subject to the petition before the board until after the board issues a final determination.

. When reviewing competing requests from counties, cities, or towns planning under RCW 36.70A.040, a state agency considering awarding grants or loans for public facilities shall accord additional preference to those counties, cities, or towns that have adopted a comprehensive plan and development regulations as required by RCW 36.70A.040. For the purposes of the preference accorded in this section, a county, city, or town planning under RCW 36.70A.040 is deemed to have satisfied the requirements for adopting a comprehensive plan and development regulations specified in RCW 36.70A.040 if the county, city, or town:

.. Adopts or has adopted a comprehensive plan and development regulations within the time periods specified in RCW 36.70A.040;

.. Adopts or has adopted a comprehensive plan and development regulations before the state agency makes a decision regarding award recipients of the grants or loans if the county, city, or town failed to adopt a comprehensive plan and/or development regulations within the time periods specified in RCW 36.70A.040; or

.. Demonstrates substantial progress toward adopting a comprehensive plan or development regulations within the time periods specified in RCW 36.70A.040. A county, city, or town that is more than six months out of compliance with the time periods specified in RCW 36.70A.040 shall not be deemed to demonstrate substantial progress for purposes of this section.

. The preference specified in subsection (3) of this section applies only to competing requests for grants or loans from counties, cities, or towns planning under RCW 36.70A.040. A request from a county, city, or town planning under RCW 36.70A.040 shall be accorded no additional preference based on subsection (3) of this section over a request from a county, city, or town not planning under RCW 36.70A.040.

. Whenever a state agency is considering awarding grants or loans for public facilities to a special district requesting funding for a proposed facility located in a county, city, or town planning under RCW 36.70A.040, it shall consider whether the county, city, or town in whose planning jurisdiction the proposed facility is located has adopted a comprehensive plan and development regulations as required by RCW 36.70A.040 and shall apply the standards in subsection (2) of this section and the preference specified in subsection (3) of this section and restricted in subsection (4) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5399-S.SL.pdf?cite=2013%20c%20275%20§%202[2013 c 275 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5594-S2.SL.pdf?cite=1999%20c%20164%20§%20601[1999 c 164 § 601]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1025-S.SL.pdf?cite=1991%20sp.s.%20c%2032%20§%2025[1991 sp.s. c 32 § 25]; ]

== 43.17.310 - Businesses—Rules coordinator to provide list of rules.
The rules coordinator under RCW 34.05.310 shall be knowledgeable regarding the agency's rules that affect businesses. The rules coordinator shall provide a list of agency rules applicable at the time of the request to a specific class or line of business, which are limited to that specific class or line as opposed to generic rules applicable to most businesses, to the *business assistance center when so requested by the *business assistance center for the specific class or line of business.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2498-S.SL.pdf?cite=1992%20c%20197%20§%205[1992 c 197 § 5]; ]

== 43.17.320 - Interagency disputes—Alternative dispute resolution—Definitions.
For purposes of RCW 43.17.320 through 43.17.340, "state agency" means:

. Any agency for which the executive officer is listed in RCW 42.17A.705(1); and

. The office of the secretary of state; the office of the state treasurer; the office of the state auditor; the department of natural resources; the office of the insurance commissioner; and the office of the superintendent of public instruction.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1048-S.SL.pdf?cite=2011%20c%2060%20§%2035[2011 c 60 § 35]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5634-S.SL.pdf?cite=1993%20c%20279%20§%202[1993 c 279 § 2]; ]

== 43.17.330 - Interagency disputes—Alternative dispute resolution—Methods.
Whenever a dispute arises between state agencies, agencies shall employ every effort to resolve the dispute themselves without resorting to litigation. These efforts shall involve alternative dispute resolution methods. If a dispute cannot be resolved by the agencies involved, any one of the disputing agencies may request the governor to assist in the resolution of the dispute. The governor shall employ whatever dispute resolution methods that the governor deems appropriate in resolving the dispute. Such methods may include, but are not limited to, the appointment by the governor of a mediator, acceptable to the disputing agencies, to assist in the resolution of the dispute. The governor may also request assistance from the attorney general to advise the mediator and the disputing agencies.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5634-S.SL.pdf?cite=1993%20c%20279%20§%203[1993 c 279 § 3]; ]

== 43.17.340 - Interagency disputes—Alternative dispute resolution—Exception.
RCW 43.17.320 and 43.17.330 shall not apply to any state agency that is a party to a lawsuit, which: (1) Impleads another state agency into the lawsuit when necessary for the administration of justice; or (2) files a notice of appeal, petitions for review, or makes other filings subject to time limits, in order to preserve legal rights and remedies.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5634-S.SL.pdf?cite=1993%20c%20279%20§%204[1993 c 279 § 4]; ]

== 43.17.350 - Health-related state agencies—Professional health services—Fee schedules.
For the purpose of accurately describing professional health services purchased by the state, health-related state agencies may develop fee schedules based on billing codes and service descriptions published by the American medical association or the United States federal health care financing administration, or develop agency unique codes and service descriptions.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1566-S2.SL.pdf?cite=1995%201st%20sp.s.%20c%206%20§%2020[1995 1st sp.s. c 6 § 20]; ]

== 43.17.360 - Lease of real property—Term of a lease—Use of proceeds—Retroactive application.
. The department of social and health services and other state agencies may lease real property and improvements thereon to a consortium of three or more counties in order for the counties to construct or otherwise acquire correctional facilities for juveniles or adults.

. A lease governed by subsection (1) of this section shall not charge more than one dollar per year for the land value and facilities value, during the initial term of the lease, but the lease may include provisions for payment of any reasonable operation and maintenance expenses incurred by the state.

The initial term of a lease governed by subsection (1) of this section shall not exceed twenty years, except as provided in subsection (4) of this section. A lease renewed under subsection (1) of this section after the initial term shall charge the fair rental value for the land and improvements other than those improvements paid for by a contracting consortium. The renewed lease may also include provisions for payment of any reasonable operation and maintenance expenses incurred by the state. For the purposes of this subsection, fair rental value shall be determined by the commissioner of public lands in consultation with the department and shall not include the value of any improvements paid for by a contracting consortium.

. The net proceeds generated from any lease entered or renewed under subsection (1) of this section involving land and facilities on the grounds of eastern state hospital shall be used solely for the benefit of eastern state hospital programs for the long-term care needs of patients with mental disorders. These proceeds shall not supplant or replace funding from traditional sources for the normal operations and maintenance or capital budget projects. It is the intent of this subsection to ensure that eastern state hospital receives the full benefit intended by this section, and that such effect will not be diminished by budget adjustments inconsistent with this intent.

. The initial term of a lease under subsection (1) of this section entered into after January 1, 1996, and involving the grounds of eastern state hospital, shall not exceed fifty years. This subsection applies retroactively, and the department shall modify any existing leases to comply with the terms of this subsection. No other terms of a lease modified by this subsection may be modified unless both parties agree.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1433-S.SL.pdf?cite=1997%20c%20349%20§%201[1997 c 349 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2720-S.SL.pdf?cite=1996%20c%20261%20§%202[1996 c 261 § 2]; ]

== 43.17.370 - Prerelease copy of report or study to local government.
. An agency, prior to releasing a final report or study regarding management by a county, city, town, special purpose district, or other unit of local government of a program delegated to the local government by the agency or for which the agency has regulatory responsibility, shall provide copies of a draft of the report or study at least two weeks in advance of the release of the final report or study to the legislative body of the local government. The agency shall, at the request of a local government legislative body, meet with the legislative body before the release of a final report or study regarding the management of such a program.

. For purposes of this section, "agency" means an office, department, board, commission, or other unit of state government, other than a unit of state government headed by a separately elected official.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1032-S2.SL.pdf?cite=1997%20c%20409%20§%20603[1997 c 409 § 603]; ]

== 43.17.380 - Quality management, accountability, and performance system—Definitions.
As used in RCW 43.17.385 and 43.17.390:

. "State agency" or "agency" means a state agency, department, office, officer, board, commission, bureau, division, institution, or institution of higher education, and all offices of executive branch state government-elected officials, except agricultural commissions under Title 15 RCW.

. "Quality management, accountability, and performance system" means a nationally recognized integrated, interdisciplinary system of measures, tools, and reports used to improve the performance of a work unit or organization.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1970-S2.SL.pdf?cite=2005%20c%20384%20§%202[2005 c 384 § 2]; ]

== 43.17.385 - Quality management, accountability, and performance system.
. Each state agency shall, within available funds, develop and implement a quality management, accountability, and performance system to improve the public services it provides.

. Each agency shall ensure that managers and staff at all levels, including those who directly deliver services, are engaged in the system and shall provide managers and staff with the training necessary for successful implementation.

. Each agency shall, within available funds, ensure that its quality management, accountability, and performance system:

.. Uses strategic business planning to establish goals, objectives, and activities consistent with the priorities of government, as provided in statute;

.. Engages stakeholders and customers in establishing service requirements and improving service delivery systems;

.. Includes clear, relevant, and easy-to-understand measures for each activity;

.. Gathers, monitors, and analyzes activity data;

.. Uses the data to evaluate the effectiveness of programs to manage process performance, improve efficiency, and reduce costs;

.. Establishes performance goals and expectations for employees that reflect the organization's objectives; and provides for regular assessments of employee performance;

.. Uses activity measures to report progress toward agency objectives to the agency director at least quarterly;

.. Where performance is not meeting intended objectives, holds regular problem-solving sessions to develop and implement a plan for addressing gaps; and

.. Allocates resources based on strategies to improve performance.

. Each agency shall conduct a yearly assessment of its quality management, accountability, and performance system.

. State agencies whose chief executives are appointed by the governor shall report to the governor on agency performance at least quarterly. The reports shall be included on the agencies', the governor's, and the office of financial management's web sites.

. The governor shall report annually to citizens on the performance of state agency programs. The governor's report shall include:

.. Progress made toward the priorities of government as a result of agency activities; and

.. Improvements in agency quality management systems, fiscal efficiency, process efficiency, asset management, personnel management, statutory and regulatory compliance, and management of technology systems.

. Each state agency shall integrate efforts made under this section with other management, accountability, and performance systems, including procedures implemented under chapter 43.42A RCW, undertaken under executive order or other authority.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2192-S2.SL.pdf?cite=2014%20c%2068%20§%206[2014 c 68 § 6]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1970-S2.SL.pdf?cite=2005%20c%20384%20§%203[2005 c 384 § 3]; ]

== 43.17.390 - Quality management, accountability, and performance system—Independent assessment.
Starting in 2012, and at least once every three years thereafter, each agency shall apply to the Washington state quality award, or similar organization, for an independent assessment of its quality management, accountability, and performance system. The assessment shall evaluate the effectiveness of all elements of its management, accountability, and performance system, including: Leadership, strategic planning, customer focus, analysis and information, employee performance management, and process improvement. The purpose of the assessment is to recognize best practice and identify improvement opportunities.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1244-S.SL.pdf?cite=2009%20c%20564%20§%20931[2009 c 564 § 931]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1970-S2.SL.pdf?cite=2005%20c%20384%20§%204[2005 c 384 § 4]; ]

== 43.17.400 - Disposition of state-owned land—Notice to governmental entities—Right of first refusal.
. Before any state agency may dispose of surplus state-owned real property to a private or any nongovernmental party, the agency must provide written notice to the following governmental entities at least sixty days before entering into any proposed disposition agreement:

.. All other state agencies;

.. Each federal agency operating within the state; and

.. The governing authority of each county, city, town, special purpose district, and federally recognized Indian tribe in which the land is located.

. The state agency must dispose of the property, for continued public benefit as defined in RCW 39.33.015, to any governmental entity responding within the notification period, upon mutual agreement reached within a reasonable time period after the response is received. Priority must be given to state agencies. The disposition may be for any terms and conditions agreed upon by the proper authorities of each party, in accordance with RCW 39.33.010, except where the disposition at fair market value is required by law.

. The requirements of this section are in addition and supplemental to other requirements of the laws of this state.

. For purposes of this section, "disposition" means the sale, exchange, or other action resulting in a transfer of ownership.

. The requirements of this section do not apply to the department of transportation.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2382-S3.SL.pdf?cite=2018%20c%20217%20§%202[2018 c 217 § 2]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5024.SL.pdf?cite=2015%20c%20225%20§%2064[2015 c 225 § 64]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1940.SL.pdf?cite=2007%20c%2062%20§%202[2007 c 62 § 2]; ]

== 43.17.410 - Sensitive personal information of vulnerable individuals or in-home caregivers for vulnerable populations—Release of information prohibited.
. To protect vulnerable individuals and their children from identity crimes and other forms of victimization, neither the state nor any of its agencies shall release sensitive personal information of vulnerable individuals or sensitive personal information of in-home caregivers for vulnerable populations, as those terms are defined in RCW 42.56.640.

[ 2017 c 4 § 10 (Initiative Measure No. 1501, approved November 8, 2016); ]

== 43.17.420 - Immigration and citizenship status—Definitions.
The definitions in this section apply throughout this section and RCW 43.330.510, 43.10.310, 43.17.425, 10.93.160, and 43.10.315, and sections 8 and 9, chapter 440, Laws of 2019 unless the context clearly requires otherwise.

. "Civil immigration warrant" means any warrant for a violation of federal civil immigration law issued by a federal immigration authority. A "civil immigration warrant" includes, but is not limited to, administrative warrants issued on forms I-200 or I-203, or their successors, and civil immigration warrants entered in the national crime information center database.

. "Court order" means a directive issued by a judge or magistrate under the authority of Article III of the United States Constitution or Article IV of the Washington Constitution. A "court order" includes but is not limited to warrants and subpoenas.

. "Federal immigration authority" means any officer, employee, or person otherwise paid by or acting as an agent of the United States department of homeland security including but not limited to its subagencies, immigration and customs enforcement and customs and border protection, and any present or future divisions thereof, charged with immigration enforcement.

. "Health facility" has the same meaning as the term "health care facility" provided in RCW 70.175.020, and includes substance abuse treatment facilities.

. "Hold request" or "immigration detainer request" means a request from a federal immigration authority, without a court order, that a state or local law enforcement agency maintain custody of an individual currently in its custody beyond the time he or she would otherwise be eligible for release in order to facilitate transfer to a federal immigration authority. A "hold request" or "immigration detainer request" includes, but is not limited to, department of homeland security form I-247A or prior or subsequent versions of form I-247.

. "Immigration detention agreement" means any contract, agreement, intergovernmental service agreement, or memorandum of understanding that permits a state or local law enforcement agency to house or detain individuals for federal civil immigration violations.

. "Immigration or citizenship status" means as such status has been established to such individual under the immigration and nationality act.

. "Language services" includes but is not limited to translation, interpretation, training, or classes. Translation means written communication from one language to another while preserving the intent and essential meaning of the original text. Interpretation means transfer of an oral communication from one language to another.

. "Local government" means any governmental entity other than the state, federal agencies, or an operating system established under chapter 43.52 RCW. It includes, but is not limited to, cities, counties, school districts, and special purpose districts.

. "Local law enforcement agency" means any agency of a city, county, special district, or other political subdivision of the state that is a general authority Washington law enforcement agency, as defined by RCW 10.93.020, or that is authorized to operate jails or to maintain custody of individuals in jails; or to operate juvenile detention facilities or to maintain custody of individuals in juvenile detention facilities; or to monitor compliance with probation or parole conditions.

. "Notification request" means a request from a federal immigration authority that a state or local law enforcement agency inform a federal immigration authority of the release date and time in advance of the release of an individual in its custody. "Notification request" includes, but is not limited to, the department of homeland security's form I-247A, form I-247N, or prior or subsequent versions of such forms.

. "Physical custody of the department of corrections" means only those individuals detained in a state correctional facility but does not include minors detained pursuant to chapter 13.40 RCW, or individuals in community custody as defined in RCW 9.94A.030.

. "Public schools" means all public elementary and secondary schools under the jurisdiction of local governing boards or a charter school board and all institutions of higher education as defined in RCW 28B.10.016.

. "School resource officer" means a commissioned law enforcement officer in the state of Washington with sworn authority to uphold the law and assigned by the employing police department or sheriff's office to work in schools to ensure school safety. By building relationships with students, school resource officers work alongside school administrators and staff to help students make good choices. School resource officers are encouraged to focus on keeping students out of the criminal justice system when possible and not impose criminal sanctions in matters that are more appropriately handled within the educational system.

. "State agency" has the same meaning as provided in RCW 42.56.010.

. "State law enforcement agency" means any agency of the state of Washington that:

.. Is a general authority Washington law enforcement agency as defined by RCW 10.93.020;

.. Is authorized to operate prisons or to maintain custody of individuals in prisons; or

.. Is authorized to operate juvenile detention facilities or to maintain custody of individuals in juvenile detention facilities.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5497-S2.SL.pdf?cite=2019%20c%20440%20§%202[2019 c 440 § 2]; ]

== 43.17.425 - Immigration and citizenship status—State agency restrictions.
. Except as provided in subsection (3) of this section, no state agency, including law enforcement, may use agency funds, facilities, property, equipment, or personnel to investigate, enforce, cooperate with, or assist in the investigation or enforcement of any federal registration or surveillance programs or any other laws, rules, or policies that target Washington residents solely on the basis of race, religion, immigration, or citizenship status, or national or ethnic origin. This subsection does not apply to any program with the primary purpose of providing persons with services or benefits, or to RCW 9.94A.685.

. Except as provided in subsection (3) of this section, the state agencies listed in subsections (5) and (6) of this section shall review their policies and identify and make any changes necessary to ensure that:

.. Information collected from individuals is limited to the minimum necessary to comply with subsection (3) of this section;

.. Information collected from individuals is not disclosed except as necessary to comply with subsection (3) of this section or as permitted by state or federal law;

.. Agency employees may not condition services or request information or proof regarding a person's immigration status, citizenship status, or place of birth; and

.. Public services are available to, and agency employees shall serve, all Washington residents without regard to immigration or citizenship status.

. Nothing in subsection (1) or (2) of this section prohibits the collection, use, or disclosure of information that is:

.. Required to comply with state or federal law;

.. In response to a lawfully issued court order;

.. Necessary to perform agency duties, functions, or other business, as permitted by statute or rule, conducted by the agency that is not related to immigration enforcement;

.. Required to comply with policies, grants, waivers, or other requirements necessary to maintain funding; or

.. In the form of deidentified or aggregated data, including census data.

. Any changes to agency policies required by this section must be made as expeditiously as possible, consistent with agency procedures. Final policies must be published.

. The following state agencies shall begin implementation of this section within twelve months after May 21, 2019, and demonstrate full compliance by December 1, 2021:

.. Department of licensing;

.. Department of labor and industries;

.. Employment security department;

.. Department of revenue;

.. Department of health;

.. Health care authority;

.. Department of social and health services;

.. Department of children, youth, and families;

.. Office of the superintendent of public instruction;

.. State patrol.

. The following state agencies may begin implementation of this section by December 1, 2021, and must demonstrate full compliance by December 1, 2023:

.. Department of agriculture;

.. Department of financial institutions;

.. Department of fish and wildlife;

.. Department of natural resources;

.. Department of retirement systems;

.. Department of services for the blind;

.. Department of transportation.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5497-S2.SL.pdf?cite=2019%20c%20440%20§%205[2019 c 440 § 5]; ]

