= 43.04 - Use of state seal.
:toc:

== 43.04.010 - Legislative findings.
The legislature finds that the seal of the state of Washington is a symbol of the authority and sovereignty of the state and is a valuable asset of its people. It is the intent of the legislature to ensure that appropriate uses are made of the state seal and to assist the secretary of state in the performance of the secretary's constitutional duty as custodian of the seal.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c120.pdf?cite=1988%20c%20120%20§%201[1988 c 120 § 1]; ]

== 43.04.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "State seal" means the seal of the state as described in Article XVIII, section 1 of the state Constitution and in RCW 1.20.080.

. "Secretary" means the secretary of state and any designee of the secretary of state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c120.pdf?cite=1988%20c%20120%20§%202[1988 c 120 § 2]; ]

== 43.04.030 - Use of state seal—Official purposes.
Except as otherwise provided in this chapter, the state seal shall be used for official purposes only.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c120.pdf?cite=1988%20c%20120%20§%203[1988 c 120 § 3]; ]

== 43.04.040 - Use of state seal—Commemorative and souvenir items—Historical, educational, and civil purposes—Application—Fee—Licensing agreements—Rules.
. The secretary of state may authorize the use of the state seal on commemorative and souvenir items, and for historical, educational, and civic purposes. Such authorization shall be in writing.

. Application for such authorization shall be in writing and shall be accompanied by a filing fee, the amount of which shall be determined by the secretary of state. The secretary shall set the fee at a level adequate to cover the administrative costs of processing the applications.

. If the secretary determines that a permitted use of the seal could financially benefit the state, the secretary may condition authorization upon a licensing agreement to secure those benefits for the state.

. The secretary of state shall adopt rules under chapter 34.05 RCW to govern the use of the seal in a manner consistent with this chapter. Any rule governing the use of the seal shall be designed to prevent inappropriate or misleading use of the seal and to assure tasteful and high quality reproduction of the seal. The rules shall also prescribe the circumstances when a licensing arrangement shall be required and the method for determining licensing fees.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c120.pdf?cite=1988%20c%20120%20§%204[1988 c 120 § 4]; ]

== 43.04.050 - Use of state seal—Prohibitions—Imitations.
. Except as otherwise provided in RCW 43.04.040, the state seal shall not be used on or in connection with any advertising or promotion for any product, business, organization, service, or article whether offered for sale for profit or offered without charge.

. The state seal shall never be used in a political campaign to assist or defeat any candidate for elective office.

. It is a violation of this chapter to use any symbol that imitates the seal or that is deceptively similar in appearance to the seal, in any manner that would be an improper use of the official seal itself.

. Nothing in this chapter shall prohibit the reproduction of the state seal for illustrative purposes by the news media if the reproduction by the news media is incidental to the publication or the broadcast. Nothing in this chapter shall prohibit a characterization of the state seal from being used in political cartoons.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c120.pdf?cite=1988%20c%20120%20§%205[1988 c 120 § 5]; ]

== 43.04.060 - Endorsements prohibited.
No use of the state seal may operate or be construed to operate in any way as an endorsement of any business, organization, product, service, or article.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c120.pdf?cite=1988%20c%20120%20§%206[1988 c 120 § 6]; ]

== 43.04.070 - Civil penalties—Injunctions.
Any person who violates RCW 43.04.050 (1) or (3) by using the state seal or an imitative or deceptively similar seal on or in connection with any product, business, organization, service, or article shall be liable for damages in a suit brought by the attorney general. The damages shall be equal to the gross monetary amount gained by the misuse of the state seal or the use of the imitative or deceptively similar seal, plus attorney's fees and other costs of the state in bringing the suit. The "gross monetary amount" is the total of the gross receipts that can be reasonably attributed to the misuse of the seal or the use of an imitative or deceptively similar seal. In addition to the damages, the violator is subject to a civil penalty imposed by the court in an amount not to exceed five thousand dollars. In imposing this penalty, the court shall consider the need to deter further violations of this chapter.

The attorney general may seek and shall be granted such injunctive relief as is appropriate to stop or prevent violations of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c120.pdf?cite=1988%20c%20120%20§%207[1988 c 120 § 7]; ]

== 43.04.080 - Investigations—Enforcement.
The secretary of state shall conduct investigations for violations of this chapter and may request enforcement by the attorney general.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c120.pdf?cite=1988%20c%20120%20§%208[1988 c 120 § 8]; ]

== 43.04.090 - Criminal penalty.
Any person who wilfully violates this chapter is guilty of a misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c120.pdf?cite=1988%20c%20120%20§%209[1988 c 120 § 9]; ]

== 43.04.100 - Deposit of fees, penalties, and damages—Use.
All fees, penalties, and damages received under this chapter shall be paid to the secretary of state and with the exception of the filing fee authorized in RCW 43.04.040(2) shall be deposited by the secretary into the capitol furnishings preservation committee account created in RCW 27.48.040.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1896-S2.SL.pdf?cite=2007%20c%20453%20§%204[2007 c 453 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c120.pdf?cite=1988%20c%20120%20§%2010[1988 c 120 § 10]; ]

