= 43.88D - Higher education capital project strategic planning.
:toc:

== 43.88D.010 - Capital budget projects—Objective analysis and scoring—Prioritized lists.
. By October 1st of each even-numbered year, the office of financial management shall complete an objective analysis and scoring of all capital budget projects proposed by the public four-year institutions of higher education and submit the results of the scoring process to the legislative fiscal committees and the four-year institutions. Each project must be reviewed and scored within one of the following categories, according to the project's principal purpose. Each project may be scored in only one category. The categories are:

.. Access-related projects to accommodate enrollment growth at all campuses, at existing or new university centers, or through distance learning. Growth projects should provide significant additional student capacity. Proposed projects must demonstrate that they are based on solid enrollment demand projections, more cost-effectively provide enrollment access than alternatives such as university centers and distance learning, and make cost-effective use of existing and proposed new space;

.. Projects that replace failing permanent buildings. Facilities that cannot be economically renovated are considered replacement projects. New space may be programmed for the same or a different use than the space being replaced and may include additions to improve access and enhance the relationship of program or support space;

.. Projects that renovate facilities to restore building life and upgrade space to meet current program requirements. Renovation projects should represent a complete renovation of a total facility or an isolated wing of a facility. A reasonable renovation project should cost between sixty to eighty percent of current replacement value and restore the renovated area to at least twenty-five years of useful life. New space may be programmed for the same or a different use than the space being renovated and may include additions to improve access and enhance the relationship of program or support space;

.. Major stand-alone campus infrastructure projects;

.. Projects that promote economic growth and innovation through expanded research activity. The acquisition and installation of specialized equipment is authorized under this category; and

.. Other project categories as determined by the office of financial management in consultation with the legislative fiscal committees.

. The office of financial management, in consultation with the legislative fiscal committees, shall establish a scoring system and process for each four-year project category that is based on the framework used in the community and technical college system of prioritization. Staff from the state board for community and technical colleges and the four-year institutions shall provide technical assistance on the development of a scoring system and process.

. The office of financial management shall consult with the legislative fiscal committees in the scoring of four-year institution project proposals, and may also solicit participation by independent experts.

.. For each four-year project category, the scoring system must, at a minimum, include an evaluation of enrollment trends, reasonableness of cost, the ability of the project to enhance specific strategic master plan goals, age and condition of the facility if applicable, and impact on space utilization.

.. Each four-year project category may include projects at the predesign, design, or construction funding phase.

.. To the extent possible, the objective analysis and scoring system of all capital budget projects shall occur within the context of any and all performance agreements between the office of financial management and the governing board of a public, four-year institution of higher education that aligns goals, priorities, desired outcomes, flexibility, institutional mission, accountability, and levels of resources.

. In evaluating and scoring four-year institution projects, the office of financial management shall take into consideration project schedules that result in realistic, balanced, and predictable expenditure patterns over the ensuing three biennia.

. The office of financial management shall distribute common definitions, the scoring system, and other information required for the project proposal and scoring process as part of its biennial budget instructions. The office of financial management, in consultation with the legislative fiscal committees, shall develop common definitions that four-year institutions must use in developing their project proposals and lists under this section.

. In developing any scoring system for capital projects proposed by the four-year institutions, the office of financial management:

.. Shall be provided with all required information by the four-year institutions as deemed necessary by the office of financial management;

.. May utilize independent services to verify, sample, or evaluate information provided to the office of financial management by the four-year institutions; and

.. Shall have full access to all data maintained by the joint legislative audit and review committee concerning the condition of higher education facilities.

. By August 1st of each even-numbered year each public four-year higher education institution shall prepare and submit prioritized lists of the individual projects proposed by the institution for the ensuing six-year period in each category. The lists must be submitted to the office of financial management and the legislative fiscal committees. The four-year institutions may aggregate minor works project proposals by primary purpose for ranking purposes. Proposed minor works projects must be prioritized within the aggregated proposal, and supporting documentation, including project descriptions and cost estimates, must be provided to the office of financial management and the legislative fiscal committees.

. For the 2019-2021 fiscal biennium and the 2021-2023 fiscal biennium, pursuant to subsection (1) of this section, by November 1, 2022, the office of financial management must score higher education capital project criteria with a rating scale that assesses how well a particular project satisfies those criteria. The office of financial management may not use a rating scale that weighs the importance of those criteria.

. For the 2019-2021 fiscal biennium and the 2021-2023 fiscal biennium, pursuant to subsection (6)(a) of this section and in lieu of the requirements of subsection (7) of this section, by August 15, 2022, the institutions of higher education shall prepare and submit or resubmit to the office of financial management and the legislative fiscal committees:

.. Individual project proposals developed pursuant to subsection (1) of this section;

.. Individual project proposals scored in prior biennia pursuant to subsection (1) of this section; and

.. A prioritized list of up to five project proposals submitted pursuant to (a) and (b) of this subsection.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1080-S.SL.pdf?cite=2021%20c%20332%20§%207034[2021 c 332 § 7034]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1102-S.SL.pdf?cite=2019%20c%20413%20§%207032[2019 c 413 § 7032]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6095-S.SL.pdf?cite=2018%20c%20298%20§%207013[2018 c 298 § 7013]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1107.SL.pdf?cite=2017%20c%2052%20§%2015[2017 c 52 § 15]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20821[2012 c 229 § 821]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6355-S.SL.pdf?cite=2010%20c%20245%20§%209[2010 c 245 § 9]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3329-S.SL.pdf?cite=2008%20c%20205%20§%202[2008 c 205 § 2]; ]

