= 43.06C - Office of the corrections ombuds.
:toc:

== 43.06C.005 - Intent.
The legislature intends to create an independent and impartial office of the corrections ombuds to assist in strengthening procedures and practices that lessen the possibility of actions occurring within the department of corrections that may adversely impact the health, safety, welfare, and rehabilitation of offenders, and that will effectively reduce the exposure of the department to litigation.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1889-S2.SL.pdf?cite=2018%20c%20270%20§%201[2018 c 270 § 1]; ]

== 43.06C.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Abuse" means any act or failure to act by a department employee, subcontractor, or volunteer which was performed, or which was failed to be performed, knowingly, recklessly, or intentionally, and which caused, or may have caused, injury or death to an inmate.

. "Corrections ombuds" or "ombuds" means the corrections ombuds, staff of the corrections ombuds, and volunteers with the office of the corrections ombuds.

. "Department" means the department of corrections.

. "Inmate" means a person committed to the physical custody of the department, including persons residing in a correctional institution or facility and persons received from another state, another state agency, a county, or the federal government.

. "Neglect" means a negligent act or omission by any department employee, subcontractor, or volunteer which caused, or may have caused, injury or death to an inmate.

. "Office" means the office of the corrections ombuds.

. "Secretary" means the secretary of the department of corrections.

. "Statewide family council" means the family council maintained by the department that is comprised of representatives from local family councils.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1889-S2.SL.pdf?cite=2018%20c%20270%20§%203[2018 c 270 § 3]; ]

== 43.06C.020 - Office created—Purpose.
Subject to the availability of amounts appropriated for this specific purpose, there is hereby created an office of corrections ombuds within the office of the governor for the purpose of providing information to inmates and their families; promoting public awareness and understanding of the rights and responsibilities of inmates; identifying system issues and responses for the governor and the legislature to act upon; and ensuring compliance with relevant statutes, rules, and policies pertaining to corrections facilities, services, and treatment of inmates under the jurisdiction of the department.

The ombuds reports directly to the governor and exercises his or her powers and duties independently of the secretary.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1889-S2.SL.pdf?cite=2018%20c%20270%20§%202[2018 c 270 § 2]; ]

== 43.06C.030 - Appointment of ombuds—Term—Other employees.
. Subject to the availability of amounts appropriated for this specific purpose, the governor shall appoint an ombuds who must be a person of recognized judgment, independence, objectivity, and integrity, and be qualified by training or experience in corrections law and policy. Prior to the appointment, the governor shall consult with, and may receive recommendations from, the appropriate committees of the legislature, delegates of the statewide family council as selected by the members of the council, and other relevant stakeholders, regarding the selection of the ombuds.

. The person appointed ombuds holds office for a term of three years and continues to hold office until reappointed or until his or her successor is appointed. The governor may remove the ombuds only for neglect of duty, misconduct, or the inability to perform duties. Any vacancy must be filled by similar appointment for the remainder of the unexpired term.

. The ombuds may employ technical experts and other employees to complete the purposes of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1889-S2.SL.pdf?cite=2018%20c%20270%20§%204[2018 c 270 § 4]; ]

== 43.06C.040 - Duties—Investigations—Complaints.
. The ombuds shall:

.. Establish priorities for use of the limited resources available to the ombuds;

.. Maintain a statewide toll-free telephone number, a collect telephone number, a web site, and a mailing address for the receipt of complaints and inquiries;

.. Provide information, as appropriate, to inmates, family members, representatives of inmates, department employees, and others regarding the rights of inmates;

.. Provide technical assistance to support inmate participation in self-advocacy;

.. Monitor department compliance with applicable federal, state, and local laws, rules, regulations, and policies as related to the health, safety, welfare, and rehabilitation of inmates;

.. Monitor and participate in legislative and policy developments affecting correctional facilities;

.. Establish a statewide uniform reporting system to collect and analyze data related to complaints received by the ombuds regarding the department;

.. Establish procedures to receive, investigate, and resolve complaints;

.. Establish procedures to gather stakeholder input into the ombuds' activities and priorities, which must include at a minimum quarterly public meetings;

.. Submit annually to the governor's office, the legislature, and the statewide family council, by November 1st of each year, a report that includes, at a minimum, the following information:

... The budget and expenditures of the ombuds;

... The number of complaints received and resolved by the ombuds;

... A description of significant systemic or individual investigations or outcomes achieved by the ombuds during the prior year;

... Any outstanding or unresolved concerns or recommendations of the ombuds; and

.. Input and comments from stakeholders, including the statewide family council, regarding the ombuds' activities during the prior year; and

.. Adopt and comply with rules, policies, and procedures necessary to implement this chapter.

. [Empty]
.. The ombuds may initiate and attempt to resolve an investigation upon his or her own initiative, or upon receipt of a complaint from an inmate, a family member, a representative of an inmate, a department employee, or others, regarding any of the following that may adversely affect the health, safety, welfare, and rights of inmates:

... Abuse or neglect;

... Department decisions or administrative actions;

... Inactions or omissions;

... Policies, rules, or procedures; or

.. Alleged violations of law by the department that may adversely affect the health, safety, welfare, and rights of inmates.

.. Prior to filing a complaint with the ombuds, a person shall have reasonably pursued resolution of the complaint through the internal grievance, administrative, or appellate procedures with the department. However, in no event may an inmate be prevented from filing a complaint more than ninety business days after filing an internal grievance, regardless of whether the department has completed the grievance process. This subsection (2)(b) does not apply to complaints related to threats of bodily harm including, but not limited to, sexual or physical assaults or the denial of necessary medical treatment.

.. The ombuds may decline to investigate any complaint as provided by the rules adopted under this chapter.

.. If the ombuds does not investigate a complaint, the ombuds shall notify the complainant of the decision not to investigate and the reasons for the decision.

.. The ombuds may not investigate any complaints relating to an inmate's underlying criminal conviction.

.. The ombuds may not investigate a complaint from a department employee that relates to the employee's employment relationship with the department or the administration of the department, unless the complaint is related to the health, safety, welfare, and rehabilitation of inmates.

.. The ombuds must attempt to resolve any complaint at the lowest possible level.

.. The ombuds may refer complainants and others to appropriate resources, agencies, or departments.

.. The ombuds may not levy any fees for the submission or investigation of complaints.

.. The ombuds must remain neutral and impartial and may not act as an advocate for the complainant or for the department.

.. At the conclusion of an investigation of a complaint, the ombuds must render a public decision on the merits of each complaint, except that the documents supporting the decision are subject to the confidentiality provisions of RCW 43.06C.060. The ombuds must communicate the decision to the inmate, if any, and to the department. The ombuds must state its recommendations and reasoning if, in the ombuds' opinion, the department or any employee thereof should:

... Consider the matter further;

... Modify or cancel any action;

... Alter a rule, practice, or ruling;

... Explain in detail the administrative action in question; or

.. Rectify an omission.

.. If the ombuds so requests, the department must, within the time specified, inform the ombuds about any action taken on the recommendations or the reasons for not complying with the recommendations.

.. If the ombuds believes, based on the investigation, that there has been or continues to be a significant inmate health, safety, welfare, or rehabilitation issue, the ombuds must report the finding to the governor and the appropriate committees of the legislature.

.. Before announcing a conclusion or recommendation that expressly, or by implication, criticizes a person or the department, the ombuds shall consult with that person or the department. The ombuds may request to be notified by the department, within a specified time, of any action taken on any recommendation presented. The ombuds must notify the inmate, if any, of the actions taken by the department in response to the ombuds' recommendations.

. This chapter does not require inmates to file a complaint with the ombuds in order to exhaust available administrative remedies for purposes of the prison litigation reform act of 1995, P.L. 104-134.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1889-S2.SL.pdf?cite=2018%20c%20270%20§%205[2018 c 270 § 5]; ]

== 43.06C.050 - Access to facilities, inmates, records.
. The ombuds must have reasonable access to correctional facilities at all times necessary to conduct a full investigation of an incident of abuse or neglect. This authority includes the opportunity to interview any inmate, department employee, or other person, including the person thought to be the victim of such abuse, who might be reasonably believed by the facility to have knowledge of the incident under investigation. Such access must be afforded, upon request by the ombuds, when:

.. An incident is reported or a complaint is made to the office;

.. The ombuds determines there is probable cause to believe that an incident has or may have occurred; or

.. The ombuds determines that there is or may be imminent danger of serious abuse or neglect of an inmate.

. The ombuds must have reasonable access to department facilities, including all areas which are used by inmates, all areas which are accessible to inmates, and to programs for inmates at reasonable times, which at a minimum must include normal working hours and visiting hours. This access is for the purpose of:

.. Providing information about individual rights and the services available from the office, including the name, address, and telephone number of the office;

.. Monitoring compliance with respect to the rights and safety of inmates; and

.. Inspecting, viewing, photographing, and video recording all areas of the facility which are used by inmates or are accessible to inmates.

. Access to inmates includes the opportunity to meet and communicate privately and confidentially with individuals regularly, both formally and informally, by telephone, mail, and in person.

. The ombuds has the right to access, inspect, and copy all relevant information, records, or documents in the possession or control of the department that the ombuds considers necessary in an investigation of a complaint filed under this chapter, and the department must assist the ombuds in obtaining the necessary releases for those documents which are specifically restricted or privileged for use by the ombuds.

. Following notification from the ombuds with a written demand for access to agency records, the delegated department staff must provide the ombuds with access to the requested documentation not later than twenty business days after the ombuds' written request for the records. Where the records requested by the ombuds pertain to an inmate death, threats of bodily harm including, but not limited to, sexual or physical assaults, or the denial of necessary medical treatment, the records shall be provided within five days unless the ombuds consents to an extension of that time frame.

. Upon notice and a request by the ombuds, a state or local government agency or entity that has records that are relevant to a complaint or an investigation conducted by the ombuds must provide the ombuds with access to such records.

. The ombuds must work with the department to minimize disruption to the operations of the department due to ombuds activities and must comply with the department's security clearance processes, provided those processes do not impede the activities outlined in this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1889-S2.SL.pdf?cite=2018%20c%20270%20§%206[2018 c 270 § 6]; ]

== 43.06C.060 - Confidentiality of correspondence, communications, investigations.
. Correspondence and communication with the office is confidential and must be protected as privileged correspondence in the same manner as legal correspondence or communication.

. The office shall establish confidentiality rules and procedures for all information maintained by the office.

. The ombuds shall treat all matters under investigation, including the identities of recipients of ombuds services, complainants, and individuals from whom information is acquired, as confidential, except as far as disclosures may be necessary to enable the ombuds to perform the duties of the office and to support any recommendations resulting from an investigation. Upon receipt of information that by law is confidential or privileged, the ombuds shall maintain the confidentiality of such information and shall not further disclose or disseminate the information except as provided by applicable state or federal law or as authorized by subsection (4) of this section. All records exchanged and communications between the office of the corrections ombuds and the department to include the investigative record are confidential and are exempt from public disclosure under chapter 42.56 RCW.

. To the extent the ombuds reasonably believes necessary, the ombuds:

.. Must reveal information obtained in the course of providing ombuds services to prevent reasonably certain death or substantial bodily harm; and

.. May reveal information obtained in the course of providing ombuds services to prevent the commission of a crime.

. If the ombuds believes it is necessary to reveal investigative records for any of the reasons outlined in *section 4 of this act, the ombuds shall provide a copy of what they intend to disclose to the department for review and application of legal exemptions prior to releasing to any other persons. If the ombuds receives personally identifying information about individual corrections staff during the course of an investigation that the ombuds determines is unrelated or unnecessary to the subject of the investigation or recommendation for action, the ombuds will not further disclose such information. If the ombuds determines that such disclosure is necessary to an investigation or recommendation, the ombuds will contact the staff member as well as the bargaining unit representative before any disclosure.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1889-S2.SL.pdf?cite=2018%20c%20270%20§%207[2018 c 270 § 7]; ]

== 43.06C.070 - Civil immunity—Retaliatory actions.
. A civil action may not be brought against any employee of the office for good faith performance of responsibilities under this chapter.

. No discriminatory, disciplinary, or retaliatory action may be taken against a department employee, subcontractor, or volunteer, an inmate, or a family member or representative of an inmate for any communication made, or information given or disclosed, to aid the office in carrying out its responsibilities, unless the communication or information is made, given, or disclosed maliciously or without good faith.

. This section is not intended to infringe on the rights of an employer to supervise, discipline, or terminate an employee for other reasons.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1889-S2.SL.pdf?cite=2018%20c%20270%20§%208[2018 c 270 § 8]; ]

