= 43.06A - Office of the family and children's ombuds.
:toc:

== 43.06A.010 - Office created—Purpose.
There is hereby created an office of the family and children's ombuds within the office of the governor for the purpose of promoting public awareness and understanding of family and children services, identifying system issues and responses for the governor and the legislature to act upon, and monitoring and ensuring compliance with administrative acts, relevant statutes, rules, and policies pertaining to family and children's services and the placement, supervision, and treatment of children in the state's care or in state-licensed facilities or residences. The ombuds shall report directly to the governor and shall exercise his or her powers and duties independently of the secretary.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%2071[2013 c 23 § 71]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2856-S2.SL.pdf?cite=1996%20c%20131%20§%202[1996 c 131 § 2]; ]

== 43.06A.020 - Ombuds—Appointment, term of office.
. Subject to confirmation by the senate, the governor shall appoint an ombuds who shall be a person of recognized judgment, independence, objectivity, and integrity, and shall be qualified by training or experience, or both, in family and children's services law and policy. Prior to the appointment, the governor shall consult with, and may receive recommendations from the committee, regarding the selection of the ombuds.

. The person appointed ombuds shall hold office for a term of three years and shall continue to hold office until reappointed or until his or her successor is appointed. The governor may remove the ombuds only for neglect of duty, misconduct, or inability to perform duties. Any vacancy shall be filled by similar appointment for the remainder of the unexpired term.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%2072[2013 c 23 § 72]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3041.SL.pdf?cite=1998%20c%20288%20§%207[1998 c 288 § 7]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2856-S2.SL.pdf?cite=1996%20c%20131%20§%203[1996 c 131 § 3]; ]

== 43.06A.030 - Duties.
The ombuds shall perform the following duties:

. Provide information as appropriate on the rights and responsibilities of individuals receiving family and children's services, juvenile justice, juvenile rehabilitation, and child early learning, and on the procedures for providing these services;

. Investigate, upon his or her own initiative or upon receipt of a complaint, an administrative act alleged to be contrary to law, rule, or policy, imposed without an adequate statement of reason, or based on irrelevant, immaterial, or erroneous grounds; however, the ombuds may decline to investigate any complaint as provided by rules adopted under this chapter;

. Monitor the procedures as established, implemented, and practiced by the department of children, youth, and families to carry out its responsibilities in delivering family and children's services with a view toward appropriate preservation of families and ensuring children's health and safety;

. Review periodically the facilities and procedures of state institutions serving children, youth, and families, and state-licensed facilities or residences;

. Recommend changes in the procedures for addressing the needs of children, youth, and families;

. Submit annually to the oversight board for children, youth, and families created in RCW 43.216.015 and to the governor by November 1st a report analyzing the work of the department of children, youth, and families, including recommendations;

. Grant the oversight board for children, youth, and families access to all relevant records in the possession of the ombuds unless prohibited by law; and

. Adopt rules necessary to implement this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6287.SL.pdf?cite=2018%20c%2058%20§%2077[2018 c 58 § 77]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20112[2017 3rd sp.s. c 6 § 112]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%2073[2013 c 23 § 73]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2856-S2.SL.pdf?cite=1996%20c%20131%20§%204[1996 c 131 § 4]; ]

== 43.06A.050 - Confidentiality.
The ombuds shall treat all matters under investigation, including the identities of service recipients, complainants, and individuals from whom information is acquired, as confidential, except as far as disclosures may be necessary to enable the ombuds to perform the duties of the office and to support any recommendations resulting from an investigation. Upon receipt of information that by law is confidential or privileged, the ombuds shall maintain the confidentiality of such information and shall not further disclose or disseminate the information except as provided by applicable state or federal law. Investigative records of the office of the ombuds are confidential and are exempt from public disclosure under chapter 42.56 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%2074[2013 c 23 § 74]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20294[2005 c 274 § 294]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2856-S2.SL.pdf?cite=1996%20c%20131%20§%206[1996 c 131 § 6]; ]

== 43.06A.060 - Admissibility of evidence—Testimony regarding official duties.
Neither the ombuds nor the ombuds's staff may be compelled, in any judicial or administrative proceeding, to testify or to produce evidence regarding the exercise of the official duties of the ombuds or of the ombuds's staff. All related memoranda, work product, notes, and case files of the ombuds's office are confidential, are not subject to discovery, judicial or administrative subpoena, or other method of legal compulsion, and are not admissible in evidence in a judicial or administrative proceeding. This section shall not apply to the oversight board for children, youth, and families.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20812[2017 3rd sp.s. c 6 § 812]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%2075[2013 c 23 § 75]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3041.SL.pdf?cite=1998%20c%20288%20§%201[1998 c 288 § 1]; ]

== 43.06A.070 - Release of identifying information.
Identifying information about complainants or witnesses shall not be subject to any method of legal compulsion, nor shall such information be revealed to the oversight board for children, youth, and families or the governor except under the following circumstances: (1) The complainant or witness waives confidentiality; (2) under a legislative subpoena when there is a legislative investigation for neglect of duty or misconduct by the ombuds or ombuds's office when the identifying information is necessary to the investigation of the ombuds's acts; or (3) under an investigation or inquiry by the governor as to neglect of duty or misconduct by the ombuds or ombuds's office when the identifying information is necessary to the investigation of the ombuds's acts.

For the purposes of this section, "identifying information" includes the complainant's or witness's name, location, telephone number, likeness, social security number or other identification number, or identification of immediate family members.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20813[2017 3rd sp.s. c 6 § 813]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%2076[2013 c 23 § 76]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3041.SL.pdf?cite=1998%20c%20288%20§%202[1998 c 288 § 2]; ]

== 43.06A.080 - Inapplicability of privilege in RCW  43.06A.060.
The privilege described in RCW 43.06A.060 does not apply when:

. The ombuds or ombuds's staff member has direct knowledge of an alleged crime, and the testimony, evidence, or discovery sought is relevant to that allegation;

. The ombuds or a member of the ombuds's staff has received a threat of, or becomes aware of a risk of, imminent serious harm to any person, and the testimony, evidence, or discovery sought is relevant to that threat or risk;

. The ombuds has been asked to provide general information regarding the general operation of, or the general processes employed at, the ombuds's office; or

. The ombuds or ombuds's staff member has direct knowledge of a failure by any person specified in RCW 26.44.030, including the state family and children's ombuds or any volunteer in the ombuds's office, to comply with RCW 26.44.030.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%2077[2013 c 23 § 77]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3041.SL.pdf?cite=1998%20c%20288%20§%203[1998 c 288 § 3]; ]

== 43.06A.085 - Liability for good faith performance—Privileged communications.
. An employee of the office of the family and children's ombuds is not liable for good faith performance of responsibilities under this chapter.

. No discriminatory, disciplinary, or retaliatory action may be taken against an employee of the department, an employee of a contracting agency of the department, a foster parent, or a recipient of family and children's services for any communication made, or information given or disclosed, to aid the office of the family and children's ombuds in carrying out its responsibilities, unless the communication or information is made, given, or disclosed maliciously or without good faith. This subsection is not intended to infringe on the rights of the employer to supervise, discipline, or terminate an employee for other reasons.

. All communications by an ombuds, if reasonably related to the requirements of that individual's responsibilities under this chapter and done in good faith, are privileged and that privilege shall serve as a defense in any action in libel or slander.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%2078[2013 c 23 § 78]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5147.SL.pdf?cite=2009%20c%2088%20§%202[2009 c 88 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6001-S.SL.pdf?cite=1999%20c%20390%20§%207[1999 c 390 § 7]; ]

== 43.06A.090 - Report of conduct warranting criminal or disciplinary proceedings.
When the ombuds or ombuds's staff member has reasonable cause to believe that any public official, employee, or other person has acted in a manner warranting criminal or disciplinary proceedings, the ombuds or ombuds's staff member shall report the matter, or cause a report to be made, to the appropriate authorities.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%2079[2013 c 23 § 79]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3041.SL.pdf?cite=1998%20c%20288%20§%204[1998 c 288 § 4]; ]

== 43.06A.100 - Communication with children in custody of department of children, youth, and families or part of a fatality investigation by the department of children, youth, and families—Access to information in possession or control of department of children, youth, and families or state institutions—Limitation on duty of office.
. The department of children, youth, and families shall:

.. Allow the ombuds or the ombuds's designee to communicate privately with any child in the custody of the department of children, youth, and families, or any child who is part of a near fatality investigation by the department of children, youth, and families, for the purposes of carrying out its duties under this chapter;

.. Permit the ombuds or the ombuds designee physical access to state institutions serving children, and state licensed facilities or residences for the purpose of carrying out its duties under this chapter;

.. Upon the ombuds's request, grant the ombuds or the ombuds's designee the right to access, inspect, and copy all relevant information, records, or documents in the possession or control of the department of children, youth, and families that the ombuds considers necessary in an investigation; and

.. Grant the office of the family and children's ombuds unrestricted online access to the child welfare case management information system and the department of children, youth, and families data information system for the purpose of carrying out its duties under this chapter.

. For the purposes of this section, "near fatality" means an act that, as certified by a physician, places the child in serious or critical condition.

. Nothing in this section creates a duty for the office of the family and children's ombuds under RCW 43.06A.030 as related to children in the care of an early learning program described in RCW 43.216.500 through 43.216.550, a licensed child care center, or a licensed child care home.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20810[2017 3rd sp.s. c 6 § 810]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1126-S.SL.pdf?cite=2015%20c%20199%20§%202[2015 c 199 § 2]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%2080[2013 c 23 § 80]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6206-S2.SL.pdf?cite=2008%20c%20211%20§%203[2008 c 211 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6001-S.SL.pdf?cite=1999%20c%20390%20§%205[1999 c 390 § 5]; ]

== 43.06A.110 - Child fatality review recommendations—Annual report.
The office of the family and children's ombuds shall issue an annual report to the legislature on the status of the implementation of child fatality review recommendations.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%2081[2013 c 23 § 81]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6206-S2.SL.pdf?cite=2008%20c%20211%20§%202[2008 c 211 § 2]; ]

== 43.06A.900 - Construction.
Nothing in this chapter shall be construed to conflict with the duty to report specified in RCW 26.44.030.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3041.SL.pdf?cite=1998%20c%20288%20§%205[1998 c 288 § 5]; ]

