= 43.33A - State investment board.
:toc:

== 43.33A.010 - General powers and duties.
Unless otherwise prescribed by law, the state investment board shall exercise all the powers and perform all duties with respect to the investment of public trust and retirement funds.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2620.SL.pdf?cite=2012%20c%20187%20§%201[2012 c 187 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c3.pdf?cite=1981%20c%203%20§%201[1981 c 3 § 1]; ]

== 43.33A.020 - Board created—Membership—Terms—Vacancies—Removal.
There is hereby created the state investment board to consist of fifteen members to be appointed as provided in this section.

. One member who is an active member of the public employees' retirement system and has been an active member for at least five years. This member shall be appointed by the governor, subject to confirmation by the senate, from a list of nominations submitted by organizations representing active members of the system. The initial term of appointment shall be one year.

. One member who is an active member of the law enforcement officers' and firefighters' retirement system and has been an active member for at least five years. This member shall be appointed by the governor, subject to confirmation by the senate, from a list of nominations submitted by organizations representing active members of the system. The initial term of appointment shall be two years.

. One member who is an active member of the teachers' retirement system and has been an active member for at least five years. This member shall be appointed by the superintendent of public instruction subject to confirmation by the senate. The initial term of appointment shall be three years.

. The state treasurer or the assistant state treasurer if designated by the state treasurer.

. A member of the state house of representatives. This member shall be appointed by the speaker of the house of representatives.

. A member of the state senate. This member shall be appointed by the president of the senate.

. One member who is a retired member of a state retirement system shall be appointed by the governor, subject to confirmation by the senate. The initial term of appointment shall be three years.

. The director of the department of labor and industries.

. The director of the department of retirement systems.

. One member who is an active member of the school employees' retirement system and has at least five years of service credit. This member shall be appointed by the superintendent of public instruction subject to confirmation by the senate. The initial term of appointment shall be three years.

. Five nonvoting members appointed by the state investment board who are considered experienced and qualified in the field of investments.

The legislative members shall serve terms of two years. The initial legislative members appointed to the board shall be appointed no sooner than January 10, 1983. The position of a legislative member on the board shall become vacant at the end of that member's term on the board or whenever the member ceases to be a member of the senate or house of representatives from which the member was appointed.

After the initial term of appointment, all other members of the state investment board, except ex officio members, shall serve terms of three years and shall hold office until successors are appointed. Members' terms, except for ex officio members, shall commence on January 1 of the year in which the appointments are made.

Members may be reappointed for additional terms. Appointments for vacancies shall be made for the unexpired terms in the same manner as the original appointments. Any member may be removed from the board for cause by the member's respective appointing authority.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2365.SL.pdf?cite=2002%20c%20303%20§%201[2002 c 303 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c195.pdf?cite=1985%20c%20195%20§%201[1985 c 195 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c219.pdf?cite=1981%20c%20219%20§%201[1981 c 219 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c3.pdf?cite=1981%20c%203%20§%202[1981 c 3 § 2]; ]

== 43.33A.025 - Criminal history record checks for board staff finalist candidates.
. Notwithstanding any provision of RCW 43.43.700 through 43.43.815, the state investment board shall require a criminal history record check for conviction records through the Washington state patrol criminal identification system, and through the federal bureau of investigation, for the purpose of conducting preemployment evaluations of each finalist candidate for a board staff position exempt from the provisions of chapter 41.06 RCW, or for any other position in which the employee will have authority for or access to: (a) Funds under the jurisdiction or responsibility of the investment board; or (b) data or security systems of the investment board or designs for such systems. The record check shall include a fingerprint check using a complete Washington state criminal identification fingerprint card, which shall be forwarded by the state patrol to the federal bureau of investigation.

. Information received by the investment board pursuant to this section shall be made available by the investment board only to board employees involved in the selection, hiring, background investigation, or job assignment of the person who is the subject of the record check, or to that subject person, and it shall be used only for the purposes of making, supporting, or defending decisions regarding the appointment or hiring of persons for these positions, or securing any necessary bonds or other requirements for such employment. Otherwise, the reports, and information contained therein, shall remain confidential and shall not be subject to the disclosure requirements of chapter 42.56 RCW.

. Fees charged by the Washington state patrol, or the federal bureau of investigation, for conducting these investigations and providing these reports shall be paid by the investment board.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20297[2005 c 274 § 297]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2660.SL.pdf?cite=2000%20c%20188%20§%201[2000 c 188 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1420.SL.pdf?cite=1999%20c%20226%20§%201[1999 c 226 § 1]; ]

== 43.33A.030 - Trusteeship of funds—Contracts—Delegation of powers and duties.
Trusteeship of those funds under the authority of the board is vested in the voting members of the board. The nonvoting members of the board shall advise the voting members on matters of investment policy and practices.

The board may enter into contracts necessary to carry out its powers and duties. The board may delegate any of its powers and duties to its executive director as deemed necessary for efficient administration and when consistent with the purposes of chapter 3, Laws of 1981.

Subject to guidelines established by the board, the board's executive director may delegate to board staff any of the executive director's powers and duties including, but not limited to, the power to make investment decisions and to execute investment and other contracts on behalf of the board.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1585-S.SL.pdf?cite=1997%20c%20161%20§%201[1997 c 161 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c3.pdf?cite=1981%20c%203%20§%203[1981 c 3 § 3]; ]

== 43.33A.035 - Delegation of authority—Investments or investment properties.
The board or its executive director may delegate by contract to private sector or other external advisors or managers the discretionary authority, as fiduciaries, to purchase or otherwise acquire, sell, or otherwise dispose of or manage investments or investment properties on behalf of the board, subject to investment or management criteria established by the board or its executive director. Such criteria relevant to particular investments or class of investment applicable under the board's contract with an advisor or manager must be incorporated by reference into the contract.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1585-S.SL.pdf?cite=1997%20c%20161%20§%202[1997 c 161 § 2]; ]

== 43.33A.040 - Quorum—Meetings—Chairperson—Vice chairperson.
. A quorum to conduct the business of the state investment board consists of at least six voting members. No action may be taken by the board without the affirmative vote of six members.

. The state investment board shall meet at least quarterly at such times as it may fix. The board shall elect a chairperson and vice chairperson annually: PROVIDED, That the legislative members are not eligible to serve as chairperson.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2365.SL.pdf?cite=2002%20c%20303%20§%202[2002 c 303 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c219.pdf?cite=1981%20c%20219%20§%202[1981 c 219 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c3.pdf?cite=1981%20c%203%20§%204[1981 c 3 § 4]; ]

== 43.33A.050 - Compensation of members—Travel expenses.
Members of the state investment board who are public employees shall serve without compensation but shall suffer no loss because of absence from their regular employment. Members of the board who are not public employees shall be compensated in accordance with RCW 43.03.240. Members of the board who are not legislators shall be reimbursed for travel expenses incurred in the performance of their duties as provided in RCW 43.03.050 and 43.03.060. Legislative members shall receive allowances provided for in RCW 44.04.120.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c287.pdf?cite=1984%20c%20287%20§%2080[1984 c 287 § 80]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c3.pdf?cite=1981%20c%203%20§%205[1981 c 3 § 5]; ]

== 43.33A.060 - Employment restrictions.
No member during the term of appointment may be employed by any investment brokerage or mortgage servicing firm doing business with the state investment board. A trust department of a commercial bank or trust company organized under federal or state law is not considered a mortgage servicing firm for purposes of this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c3.pdf?cite=1981%20c%203%20§%206[1981 c 3 § 6]; ]

== 43.33A.070 - Liability of members.
No member of the state investment board is liable for the negligence, default, or failure of any other person or other member of the board to perform the duties of the member's office and no member of the board shall be considered or held to be an insurer of the funds or assets of any of the trust and retirement funds nor is any nonvoting member liable for actions performed with the exercise of reasonable diligence within the scope of the member's authorized activities as a member of the board.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c3.pdf?cite=1981%20c%203%20§%207[1981 c 3 § 7]; ]

== 43.33A.080 - Investment of funds in farm, soil, water conservation loans and in Washington land bank.
The state investment board may invest those funds which are not under constitutional prohibition in: (1) Farm ownership and soil and water conservation loans fully guaranteed as to principal and interest under the Bankhead-Jones farm tenant act administered by the United States department of agriculture; and (2) the Washington land bank established by *chapter 31.30 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c29.pdf?cite=1987%20c%2029%20§%202[1987 c 29 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c3.pdf?cite=1981%20c%203%20§%208[1981 c 3 § 8]; ]

== 43.33A.090 - Records.
The state investment board shall keep a full and complete public record of its proceedings in appropriate books of record. Within sixty days of July 1, 1981, the state investment board shall assume physical custody of all investment accounts, files, and other records of each fund placed under the investment authority of the board.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c3.pdf?cite=1981%20c%203%20§%209[1981 c 3 § 9]; ]

== 43.33A.100 - Offices—Personnel—Officers—Compensation—Transfer of employees—Existing contracts and obligations.
The state investment board shall maintain appropriate offices and employ such personnel as may be necessary to perform its duties. Employment by the investment board shall include but not be limited to an executive director, investment officers, and a confidential secretary, which positions are exempt from classified service under chapter 41.06 RCW. Employment of the executive director by the board shall be for a term of three years, and such employment shall be subject to confirmation of the state finance committee: PROVIDED, That nothing shall prevent the board from dismissing the director for cause before the expiration of the term nor shall anything prohibit the board, with the confirmation of the state finance committee, from employing the same individual as director in succeeding terms. Compensation levels for the executive director, a confidential secretary, and all investment officers, including the deputy director for investment management, employed by the investment board shall be established by the state investment board. The investment board is authorized to maintain a retention pool within the state investment board expense account under RCW 43.33A.160, from the earnings of the funds managed by the board, pursuant to a performance management and compensation program developed by the investment board, in order to address recruitment and retention problems and to reward performance. The compensation levels and incentive compensation for investment officers shall be limited to the average of total compensation provided by state or other public funds of similar size, based upon a biennial survey conducted by the investment board, with review and comment by the joint legislative audit and review committee. However, in any fiscal year the incentive compensation granted by the investment board from the retention pool to investment officers pursuant to this section may not exceed thirty percent. Disbursements from the retention pool shall be from legislative appropriations and shall be on authorization of the board's executive director or the director's designee.

The investment board shall provide notice to the director of financial management and the chairs of the house of representatives and senate fiscal committees of proposed changes to the compensation levels for the positions. The notice shall be provided not less than sixty days prior to the effective date of the proposed changes.

As of July 1, 1981, all employees classified under chapter 41.06 RCW and engaged in duties assumed by the state investment board on July 1, 1981, are assigned to the state investment board. The transfer shall not diminish any rights granted these employees under chapter 41.06 RCW nor exempt the employees from any action which may occur thereafter in accordance with chapter 41.06 RCW.

All existing contracts and obligations pertaining to the functions transferred to the state investment board in chapter 3, Laws of 1981 shall remain in full force and effect, and shall be performed by the board. None of the transfers directed by chapter 3, Laws of 1981 shall affect the validity of any act performed by a state entity or by any official or employee thereof prior to July 1, 1981.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5931-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2043%20§%20457[2011 1st sp.s. c 43 § 457]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3149-S.SL.pdf?cite=2008%20c%20236%20§%201[2008 c 236 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5988-S.SL.pdf?cite=2001%20c%20302%20§%201[2001 c 302 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2054-S.SL.pdf?cite=1993%20c%20281%20§%2050[1993 c 281 § 50]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c219.pdf?cite=1981%20c%20219%20§%203[1981 c 219 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c3.pdf?cite=1981%20c%203%20§%2010[1981 c 3 § 10]; ]

== 43.33A.110 - Rules and regulations—Investment policies and procedures.
The state investment board may make appropriate rules and regulations for the performance of its duties. The board shall establish investment policies and procedures designed exclusively to maximize return at a prudent level of risk. However, in the case of the department of labor and industries' accident, medical aid, and reserve funds, the board shall establish investment policies and procedures designed to attempt to limit fluctuations in industrial insurance premiums and, subject to this purpose, to maximize return at a prudent level of risk. The board shall adopt rules to ensure that its members perform their functions in compliance with chapter 42.52 RCW. Rules adopted by the board shall be adopted pursuant to chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6111-S.SL.pdf?cite=1994%20c%20154%20§%20310[1994 c 154 § 310]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c179.pdf?cite=1989%20c%20179%20§%201[1989 c 179 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c130.pdf?cite=1988%20c%20130%20§%201[1988 c 130 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c219.pdf?cite=1981%20c%20219%20§%204[1981 c 219 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c3.pdf?cite=1981%20c%203%20§%2011[1981 c 3 § 11]; ]

== 43.33A.120 - Examination of accounts, files, and other records.
All accounts, files, and other records of the state investment board which pertain to each retirement system are subject at any time or from time to time to such reasonable periodic, special, or other examinations by the department of retirement systems as the director of the department of retirement systems deems necessary or appropriate.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c3.pdf?cite=1981%20c%203%20§%2012[1981 c 3 § 12]; ]

== 43.33A.130 - Securities—State treasurer may cause same to be registered in the name of the nominee.
The state treasurer may cause any securities in which the state investment board deals to be registered in the name of a nominee without mention of any fiduciary relationship, except that adequate records shall be maintained to identify the actual owner of the security so registered. The securities so registered shall be held in the physical custody of the state treasurer, the federal reserve system, the designee of the state treasurer, or, at the election of the designee and upon approval of the state treasurer, the Depository Trust Company of New York City or its designees.

With respect to the securities, the nominee shall act only upon the order of the state investment board. All rights to the dividends, interest, and sale proceeds from the securities and all voting rights of the securities are vested in the actual owners of the securities, and not in the nominee.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1422.SL.pdf?cite=1999%20c%20228%20§%201[1999 c 228 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c3.pdf?cite=1981%20c%203%20§%2013[1981 c 3 § 13]; ]

== 43.33A.135 - Investment policy—Investment options.
The state investment board has the full power to establish investment policy, develop participant investment options, and manage investment funds for the college savings program, if the committee on advanced tuition payment and college savings selects the state investment board as the investment manager pursuant to RCW 28B.95.032, and for the state deferred compensation plan, consistent with the provisions of RCW 41.50.770 and 41.50.780. The board may continue to offer the investment options provided as of June 11, 1998, until the board establishes a deferred compensation plan investment policy and adopts new investment options after considering the recommendations of the department of retirement systems.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6601-S2.SL.pdf?cite=2016%20c%2069%20§%2019[2016 c 69 § 19]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2617-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%207%20§%2036[2010 1st sp.s. c 7 § 36]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2922-S.SL.pdf?cite=1998%20c%20116%20§%2013[1998 c 116 § 13]; ]

== 43.33A.140 - Investments—Standard of investment and management.
The state investment board shall invest and manage the assets entrusted to it with reasonable care, skill, prudence, and diligence under circumstances then prevailing which a prudent person acting in a like capacity and familiar with such matters would use in the conduct of an activity of like character and purpose.

The board shall:

. Consider investments not in isolation, but in the context of the investment of the particular fund as a whole and as part of an overall investment strategy, which should incorporate risk and return objectives reasonably suited for that fund; and

. Diversify the investments of the particular fund unless, because of special circumstances, the board reasonably determines that the purposes of that fund are better served without diversifying. However, no corporate fixed-income issue or common stock holding may exceed three percent of the cost or six percent of the market value of the assets of that fund.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6192.SL.pdf?cite=1998%20c%2014%20§%201[1998 c 14 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c3.pdf?cite=1981%20c%203%20§%2014[1981 c 3 § 14]; ]

== 43.33A.150 - Reports of investment activities.
. The state investment board shall prepare written reports at least quarterly summarizing the investment activities of the state investment board, which reports shall be sent to the governor, the senate ways and means committee, the house appropriations committee, the department of retirement systems, and other agencies having a direct financial interest in the investment of funds by the board, and to other persons on written request. The state investment board shall provide information to the department of retirement systems necessary for the preparation of monthly reports.

. At least annually, the board shall report on the board's investment activities for the department of labor and industries' accident, medical aid, and reserve funds to the senate financial institutions and insurance committee, the senate economic development and labor committee, and the house commerce and labor committee, or appropriate successor committees.

. At least annually, the board shall report on the board's investment activities for the higher education permanent funds to the house capital budget committee and the senate ways and means committee.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1784-S.SL.pdf?cite=2007%20c%20215%20§%204[2007 c 215 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c179.pdf?cite=1989%20c%20179%20§%202[1989 c 179 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c3.pdf?cite=1981%20c%203%20§%2015[1981 c 3 § 15]; ]

== 43.33A.160 - Funding of board—State investment board expense account.
. The state investment board shall be funded from the earnings of the funds managed by the state investment board, proportional to the value of the assets of each fund, subject to legislative appropriation.

. There is established in the state treasury a state investment board expense account from which shall be paid the operating expenses of the state investment board. Prior to November 1 of each even-numbered year, the state investment board shall determine and certify to the state treasurer and the office of financial management the value of the various funds managed by the investment board in order to determine the proportional liability of the funds for the operating expenses of the state investment board. Pursuant to appropriation, the state treasurer is authorized to transfer such moneys from the various funds managed by the investment board to the state investment board expense account as are necessary to pay the operating expenses of the investment board.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1058-S.SL.pdf?cite=1991%20sp.s.%20c%2013%20§%2032[1991 sp.s. c 13 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c57.pdf?cite=1985%20c%2057%20§%2032[1985 c 57 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c10.pdf?cite=1982%20c%2010%20§%2010[1982 c 10 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c242.pdf?cite=1981%20c%20242%20§%201[1981 c 242 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c219.pdf?cite=1981%20c%20219%20§%205[1981 c 219 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c3.pdf?cite=1981%20c%203%20§%2016[1981 c 3 § 16]; ]

== 43.33A.170 - Commingled trust funds—Participation of funds in investments of board.
The state investment board is authorized to establish commingled trust funds in the state treasury for the implementation of specific investment programs for any combination of funds under its jurisdiction. At the discretion of the state investment board, the funds under the jurisdiction of the board may participate in the investments made by the board through state investment board commingled trust funds. The state investment board may establish accounts within any such commingled trust fund as necessary for the implementation of specific investment programs. The combining of moneys from funds located outside the state treasury with moneys from funds located within the state treasury for investment under this section shall not affect the nature, character, or purpose of a participating fund.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1421.SL.pdf?cite=1999%20c%20227%20§%201[1999 c 227 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c58.pdf?cite=1982%20c%2058%20§%201[1982 c 58 § 1]; ]

== 43.33A.180 - Investment accounting—Transfer of functions and duties from state treasurer's office.
The state investment board shall account for and report on the investments authorized by this chapter in the manner prescribed by the office of financial management under chapter 43.88 RCW.

After approval of the director of financial management, all positions, reports, documents, and office equipment along with any appropriation necessary for carrying out the functions and duties transferred shall, on July 1, 1992, be transferred from the state treasurer's office to the state investment board. All employees assigned to such classified positions to be transferred, are assigned, without any loss of rights, to the state investment board.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2470-S.SL.pdf?cite=1992%20c%20232%20§%20905[1992 c 232 § 905]; ]

== 43.33A.190 - Self-directed investment—Board's duties (as amended by 2016 c 39).
Pursuant to RCW 41.34.130 and 43.330.464, the state investment board shall invest all self-directed investment moneys under teachers' retirement system plan 3, the school employees' retirement system plan 3, ((and)) the public employees' retirement system plan 3, and the Washington achieving a better life experience program with full power to establish investment policy, develop investment options, and manage self-directed investment funds.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2323-S.SL.pdf?cite=2016%20c%2039%20§%208[2016 c 39 § 8]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6530-S.SL.pdf?cite=2000%20c%20247%20§%20701[2000 c 247 § 701]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6306-S.SL.pdf?cite=1998%20c%20341%20§%20707[1998 c 341 § 707]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1206-S.SL.pdf?cite=1995%20c%20239%20§%20321[1995 c 239 § 321]; ]

== 43.33A.200 - Creation of entities for investment purposes—Liability—Tax status.
. The board is authorized to create corporations under Title 23B RCW, limited liability companies under chapter 25.15 RCW, and limited partnerships under chapter 25.10 RCW, of which it may or may not be the general partner, for the purposes of transferring, acquiring, holding, overseeing, operating, or disposing of real estate or other investment assets that are not publicly traded on a daily basis or on an organized exchange. The liability of each entity created by the board is limited to the assets or properties of that entity. No creditor or other person has any right of action against the board, its members or employees, or the state of Washington on account of any debts, obligations, or liabilities of the entity. Entities created under this section may be authorized by the board to make any investment that the board may make, including but not limited to the acquisition of: Equity interests in operating companies, the indebtedness of operating companies, and real estate.

. Directors, officers, and other principals of entities created under this section must be board members, board staff, or principals or employees of an advisor or manager engaged by contract by the board or the entity to manage real estate or other investment assets of the entity. Directors of entities created under this section must be appointed by the board. Officers and other principals of entities created under this section are appointed by the directors.

. A public corporation, limited liability company, or limited partnership created under this section has the same immunity or exemption from taxation as that of the state. The entity shall pay an amount equal to the amounts that would be paid for taxes otherwise levied upon real property and personal property to the public official charged with the collection of such real property and personal property taxes as if the property were in private ownership. The proceeds of such payments must be allocated as though the property were in private ownership.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=1997%20c%20359%20§%201[1997 c 359 § 1]; ]

== 43.33A.210 - Assets not publicly traded—Treatment of rent and income—Management accounts—Application of this chapter and chapter  39.58 RCW.
Rent and other income from real estate or other investment assets that are not publicly traded on a daily basis or on an organized exchange that are acquired and being held for investment by the board or by an entity created under RCW 43.33A.200 by the board, and being managed by an external advisor or other property manager under contract, shall not be deemed income or state funds for the purposes of chapter 39.58 RCW and this title, until distributions are made to the board of such income from the advisor or manager. Bank and other accounts established by the advisor or property manager for the purpose of the management of such investment assets shall not be deemed accounts established by the state for the purpose of chapter 39.58 RCW and this title.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5270-S.SL.pdf?cite=1997%20c%20359%20§%202[1997 c 359 § 2]; ]

