= 43.99M - Bond retirement accounts.
:toc:

== 43.99M.005 - Findings.
. The legislature declares that it is in the best interest of the state and the owners and holders of the bonds issued by the state and its political subdivisions that the accounts used by the treasurer for debt service retirement are accurately designated and named in statute.

. It is the intent of the legislature in this chapter and sections 10 through 37, chapter 456, Laws of 1997 to create and change the names of funds and accounts to accomplish the declaration under subsection (1) of this section. The legislature does not intend to diminish in any way the current obligations of the state or its political subdivisions or diminish in any way the rights of bond owners and holders.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6064-S.SL.pdf?cite=1997%20c%20456%20§%209[1997 c 456 § 9]; ]

== 43.99M.010 - Debt-limit general fund bond retirement account.
The debt-limit general fund bond retirement account is created in the state treasury. This account shall be exclusively devoted to the payment of principal and interest on and retirement of the bonds authorized by the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6064-S.SL.pdf?cite=1997%20c%20456%20§%2030[1997 c 456 § 30]; ]

== 43.99M.020 - Debt-limit reimbursable bond retirement account.
The debt-limit reimbursable bond retirement account is created in the state treasury. This account shall be exclusively devoted to the payment of principal and interest on and retirement of the bonds authorized by the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6064-S.SL.pdf?cite=1997%20c%20456%20§%2031[1997 c 456 § 31]; ]

== 43.99M.030 - Nondebt-limit general fund bond retirement account.
The nondebt-limit general fund bond retirement account is created in the state treasury. This account shall be exclusively devoted to the payment of principal and interest on and retirement of the bonds authorized by the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6064-S.SL.pdf?cite=1997%20c%20456%20§%2032[1997 c 456 § 32]; ]

== 43.99M.040 - Nondebt-limit reimbursable bond retirement account.
The nondebt-limit reimbursable bond retirement account is created in the state treasury. This account shall be exclusively devoted to the payment of principal and interest on and retirement of the bonds authorized by the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6064-S.SL.pdf?cite=1997%20c%20456%20§%2033[1997 c 456 § 33]; ]

== 43.99M.050 - Nondebt-limit proprietary appropriated bond retirement account.
The nondebt-limit proprietary appropriated bond retirement account is created in the state treasury. This account shall be exclusively devoted to the payment of principal and interest on and retirement of the bonds authorized by the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6064-S.SL.pdf?cite=1997%20c%20456%20§%2034[1997 c 456 § 34]; ]

== 43.99M.060 - Nondebt-limit proprietary nonappropriated bond retirement account.
The nondebt-limit proprietary nonappropriated bond retirement account is created in the state treasury. This account shall be exclusively devoted to the payment of principal and interest on and retirement of the bonds authorized by the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6064-S.SL.pdf?cite=1997%20c%20456%20§%2035[1997 c 456 § 35]; ]

== 43.99M.070 - Nondebt-limit revenue bond retirement account.
The nondebt-limit revenue bond retirement account is created in the state treasury. This account shall be exclusively devoted to the payment of principal and interest on and retirement of the bonds authorized by the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6064-S.SL.pdf?cite=1997%20c%20456%20§%2036[1997 c 456 § 36]; ]

== 43.99M.080 - Transportation improvement board bond retirement account.
The transportation improvement board bond retirement account is created in the state treasury. This account shall be exclusively devoted to the payment of principal and interest on and retirement of the bonds authorized by the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6064-S.SL.pdf?cite=1997%20c%20456%20§%2037[1997 c 456 § 37]; ]

== 43.99M.901 - Effective date—1997 c 456 §§ 9-43.
Sections 9 through 43 of this act are necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and take effect immediately [May 20, 1997].

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6064-S.SL.pdf?cite=1997%20c%20456%20§%2047[1997 c 456 § 47]; ]

