= 43.71A - Pacific Island citizens—Health care premium assistance.
:toc:

== 43.71A.005 - Findings—Intent.
. The legislature finds that:

.. The compact of free association (COFA) islands, which consists of the Republic of Palau, the Republic of the Marshall Islands, and the Federated States of Micronesia, has had a long-standing relationship with the United States;

.. The relationship between the COFA islands and the United States includes economic development and a military presence in the islands;

.. The region served as a testing ground for atmospheric nuclear weapons between 1946 and 1957, which resulted in past and current inhabitants being exposed to nuclear fallout;

.. Residents of the COFA islands are allowed to enter the United States without work permits or visas where they live, study, work, serve in the military, and pay state and federal taxes, but are ineligible for federal health programs like medicaid and medicare; and

.. This ineligibility for federal health programs has exacerbated barriers to health care access for this population, which has led to poorer health outcomes and increased, long-term costs on the health care system as a whole.

. The legislature therefore intends to increase access to health care services for COFA islanders residing in Washington by providing premium and cost-sharing assistance for health coverage purchased through the health benefit exchange.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5683-S.SL.pdf?cite=2018%20c%20161%20§%201[2018 c 161 § 1]; ]

== 43.71A.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Advance premium tax credit" means the premium assistance amount determined in accordance with the affordable care act.

. "Affordable care act" means the federal patient protection and affordable care act, P.L. 111-148, as amended by the federal health care and education reconciliation act of 2010, P.L. 111-152, or federal regulations or guidance issued under the affordable care act.

. "Authority" means the Washington state health care authority.

. "COFA citizen" means a person who is a citizen of:

.. The Republic of the Marshall Islands;

.. The Federated States of Micronesia; or

.. The Republic of Palau.

. "Health benefit exchange" or "exchange" means the Washington health benefit exchange established in chapter 43.71 RCW.

. "Income" means the modified adjusted gross income attributed to an individual for purposes of determining his or her eligibility for advance premium tax credits.

. "In-network provider" means a health care provider or group of providers that directly contracts with an insurer to provide health benefits covered by a health benefit plan offered by an insurer.

. "Open enrollment period" means the period during which a person may enroll in a qualified health plan.

. "Out-of-pocket costs" means copayments, coinsurance, deductibles, and other cost-sharing requirements imposed under a qualified health plan for services, pharmaceuticals, devices, and other health benefits that are covered by the plan and rendered by in-network providers.

. "Premium cost" means an individual's premium for a qualified health plan less the amount of the individual's advance premium tax credit.

. "Qualified health plan" means a health benefit plan sold through the health benefit exchange.

. "Resident" means a person who is domiciled in this state.

. "Special enrollment period" means a period during which a person who has not done so during the open enrollment period may enroll in a qualified health plan through the exchange if the person meets specified requirements.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5683-S.SL.pdf?cite=2018%20c%20161%20§%202[2018 c 161 § 2]; ]

== 43.71A.020 - Eligibility—Costs to be paid—Disqualification—Establishment of procedures.
. An individual is eligible for the COFA premium assistance program if the individual:

.. Is a resident;

.. Is a COFA citizen;

.. Enrolls in a silver qualified health plan;

.. Has income that is less than one hundred thirty-three percent of the federal poverty level; and

.. Is ineligible for a federal or state medical assistance program administered by the authority under chapter 74.09 RCW.

. Subject to the availability of amounts appropriated for this specific purpose, the authority shall pay the premium cost for a qualified health plan and the out-of-pocket costs for the coverage provided by the plan for an individual who is eligible for the premium assistance program under subsection (1) of this section.

. The authority may disqualify a participant from the program if the participant:

.. No longer meets the eligibility criteria in subsection (1) of this section;

.. Fails, without good cause, to comply with procedural or documentation requirements established by the authority in accordance with subsection (4) of this section;

.. Fails, without good cause, to notify the authority of a change of address in a timely manner;

.. Withdraws the participant's application or requests termination of coverage; or

.. Performs an act, practice, or omission that constitutes fraud, and, as a result, an insurer rescinds the participant's policy for the qualified health plan.

. The authority shall establish:

.. Application, enrollment, and renewal processes for the COFA premium assistance program;

.. The qualified health plans that are eligible for reimbursement under the program;

.. Procedural requirements for continued participation in the program, including participant documentation requirements that are necessary for the authority to administer the program; and

.. Open enrollment periods and special enrollment periods consistent with the enrollment periods for the health benefit exchange.

. The first open enrollment period for the COFA premium assistance program must begin no later than November 1, 2018.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5274.SL.pdf?cite=2019%20c%20311%20§%202[2019 c 311 § 2]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5683-S.SL.pdf?cite=2018%20c%20161%20§%203[2018 c 161 § 3]; ]

== 43.71A.030 - Education and outreach program.
The authority, in consultation with the Washington state commission on Asian Pacific American affairs, shall establish an annual comprehensive community education and outreach program to COFA citizens, including contracting with a Washington organization that has multilingual language capacity, and working with stakeholder and community organizations, to facilitate applications for, and enrollment in, the COFA premium assistance and dental care programs. Subject to the availability of amounts appropriated for this specific purpose, the education and outreach program shall provide culturally and linguistically accessible information to facilitate participation in the programs, including but not limited to enrollment procedures, benefit utilization, and patient responsibilities.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5274.SL.pdf?cite=2019%20c%20311%20§%203[2019 c 311 § 3]; ]

== 43.71A.800 - Advisory committee.
The authority shall appoint an advisory committee that includes, but is not limited to, insurers and representatives of communities of COFA citizens. The committee shall advise the authority in the development, implementation, and operation of the COFA premium assistance program established in this chapter and the COFA islander dental care program established in RCW 74.09.719. The advisory committee must exist until at least December 31, 2021. Advisory committee members may be reimbursed for transportation and travel expenses related to serving on the committee, as needed.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5274.SL.pdf?cite=2019%20c%20311%20§%205[2019 c 311 § 5]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5683-S.SL.pdf?cite=2018%20c%20161%20§%204[2018 c 161 § 4]; ]

== 43.71A.900 - Effective date—2018 c 161.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and takes effect immediately [March 22, 2018].

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5683-S.SL.pdf?cite=2018%20c%20161%20§%206[2018 c 161 § 6]; ]

