= 43.31C - Community empowerment zones.
:toc:

== 43.31C.005 - Findings—Declaration.
. The legislature finds that:

.. There are geographic areas within communities that are characterized by a lack of employment opportunities, an average income level that is below the median income level for the surrounding community, a lack of affordable housing, deteriorating infrastructure, and a lack of facilities for community services, job training, and education;

.. Strategies to encourage reinvestment in these areas by assisting local businesses to become stronger and area residents to gain economic power involve a variety of activities and partnerships;

.. Reinvestment in these areas cannot be accomplished with only governmental resources and require a comprehensive approach that integrates various incentives, programs, and initiatives to meet the economic, physical, and social needs of the area;

.. Successful reinvestment depends on a local government's ability to coordinate public resources in a cohesive, comprehensive strategy that is designed to leverage long-term private investment in an area;

.. Reinvestment can strengthen the overall tax base through increased tax revenue from expanded and new business activities and physical property improvement;

.. Local governments, in cooperation with area residents, can provide leadership as well as planning and coordination of resources and necessary supportive services to address reinvestment in the area; and

.. It is in the public interest to adopt a targeted approach to revitalization and enlist the resources of all levels of government, the private sector, community-based organizations, and community residents to revitalize an area.

. The legislature declares that the purposes of the community empowerment zone act are to:

.. Encourage reinvestment through strong partnerships and cooperation between all levels of government, community-based organizations, area residents, and the private sector;

.. Involve the private sector and stimulate private reinvestment through the judicious use of public resources;

.. Target governmental resources to those areas of greatest need; and

.. Include all levels of government, community individuals, organizations, and the private sector in the policy-making process.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2460-S.SL.pdf?cite=2000%20c%20212%20§%201[2000 c 212 § 1]; ]

== 43.31C.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Area" means a geographic area within a local government that is described by a close perimeter boundary.

. "Community empowerment zone" means an area meeting the requirements of RCW 43.31C.020 and officially designated by the director.

. "Department" means the department of commerce.

. "Director" means the director of the department of commerce.

. "Local government" means a city, code city, town, or county.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2009%20c%20565%20§%2031[2009 c 565 § 31]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2460-S.SL.pdf?cite=2000%20c%20212%20§%202[2000 c 212 § 2]; ]

== 43.31C.020 - Community empowerment zone—Application.
. The department, in cooperation with the department of revenue, the employment security department, and the office of financial management, may approve applications submitted by local governments for an area's designation as a community empowerment zone under this chapter. The application for designation shall be in the form and manner and contain such information as the department may prescribe, provided that the application shall:

.. Contain information sufficient for the director to determine if the criteria established in RCW 43.31C.030 have been met;

.. Be submitted on behalf of the local government by its chief elected official, or, if none, by the governing body of the local government;

.. Contain a five-year community empowerment plan that meets the requirements of RCW 43.31C.040; and

.. Certify that area residents were given the opportunity to participate in the development of the five-year community empowerment strategy required under RCW 43.31C.040.

. No local government shall submit more than two areas to the department for possible designation as a community empowerment zone under this chapter.

. [Empty]
.. The director may designate up to six community empowerment zones, statewide, from among the applications submitted for designation as a community empowerment zone.

.. The director shall make determinations of designated community empowerment zones on the basis of the following factors:

... The strength and quality of the local government commitments to meet the needs identified in the five-year community empowerment plan required under RCW 43.31C.040.

... The level of private sector commitment of additional resources and contribution to the community empowerment zone.

... The potential for revitalization of the area as a result of designation as a community empowerment zone.

... Other factors the director deems necessary.

.. The determination of the director as to the areas designated as community empowerment zones shall be final.

. Except as provided in RCW 43.31C.050, an area that was designated a community empowerment zone before January 1, 1996, under this section, automatically and without additional action by the local government continues its designation under this chapter.

. The department may not designate additional community empowerment zones after January 1, 2004, but may amend or rescind designation of community empowerment zones in accordance with RCW 43.31C.050.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2460-S.SL.pdf?cite=2000%20c%20212%20§%203[2000 c 212 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=1994%20sp.s.%20c%207%20§%20702[1994 sp.s. c 7 § 702]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5967-S.SL.pdf?cite=1993%20sp.s.%20c%2025%20§%20401[1993 sp.s. c 25 § 401]; ]

== 43.31C.030 - Community empowerment zone—Requirements.
. The director may not designate an area as a community empowerment zone unless that area meets the following requirements:

.. The area must be designated by the legislative authority of the local government as an area to receive federal, state, and local assistance designed to increase economic, physical, or social activity in the area;

.. The area must have at least fifty-one percent of the households in the area with incomes at or below eighty percent of the county's median income, adjusted for household size;

.. The average unemployment rate for the area, for the most recent twelve-month period for which data is available must be at least one hundred twenty percent of the average unemployment rate of the county; and

.. A five-year community empowerment plan for the area that meets the requirements of RCW 43.31C.040 must be adopted.

. The director may establish, by rule, such other requirements as the director may reasonably determine necessary and appropriate to assure that the purposes of this chapter are satisfied.

. In determining if an area meets the requirements of this section, the director may consider data provided by the United States bureau of the census from the most recent census or any other reliable data that the director determines to be acceptable for the purposes for which the data is used.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2460-S.SL.pdf?cite=2000%20c%20212%20§%204[2000 c 212 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=1994%20sp.s.%20c%207%20§%20703[1994 sp.s. c 7 § 703]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5967-S.SL.pdf?cite=1993%20sp.s.%20c%2025%20§%20402[1993 sp.s. c 25 § 402]; ]

== 43.31C.040 - Community empowerment plan—Requirements—Annual progress report.
. The five-year community empowerment plan required under RCW 43.31C.020 shall contain information that describes the community development needs of the proposed community empowerment zone and present a strategy for meeting those needs. The plan shall address the following categories:

.. Housing needs for all economic segments of the proposed community empowerment zone;

.. Public infrastructure needs, such as transportation, water, sanitation, energy, and drainage and flood control;

.. Other public facilities needs, such as neighborhood facilities or facilities for the provision of health, education, recreation, public safety, and other services;

.. Community economic development needs, such as commercial and industrial revitalization, job creation and retention considering the unemployment and underemployment of area residents, accessibility to financial resources by area residents and businesses, investment within the area, and other related components of community economic development; and

.. Social service needs of residents in the proposed community empowerment zone.

. The local government must provide a description of its strategy for meeting the needs identified in subsection (1) of this section. As part of the community empowerment zone strategy, the local government must identify the needs for which specific plans are currently in place and the source of funds expected to be used. For the balance of the area's needs, the local government must identify the source of funds expected to become available during the next two-year period and actions the local government will take to acquire those funds.

. The local government must submit an annual progress report to the department that details the extent to which the local government is working to meet the needs identified in the five-year community empowerment plan. If applicable, the progress report must also contain a discussion on the impediments to meeting the needs outlined in the five-year community empowerment plan. The department must determine the date the annual progress reports are due from each local government.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2460-S.SL.pdf?cite=2000%20c%20212%20§%205[2000 c 212 § 5]; ]

== 43.31C.050 - Community empowerment zones—Amendment—Termination.
. The terms or conditions of a community empowerment zone approved under this chapter may be amended to:

.. Alter the boundaries of the community empowerment zone; or

.. Terminate the designation of a community empowerment zone.

. [Empty]
.. A request for an amendment under subsection (1)(a) of this section may not be in effect until the department issues an amended designation for the community empowerment zone that approves the requested amendment. The local government must promptly file with the department a request for approval that contains information the department deems necessary to evaluate the proposed changes and its impact on the area's designation as a community empowerment zone under RCW 43.31C.030. The local government must hold at least two public hearings on the proposed changes and include the information in its request for an amendment to its community empowerment zone.

.. The department shall approve or disapprove a proposed amendment to a community empowerment zone within sixty days of its receipt of a request under subsection (1)(a) of this section. The department may not approve changes to a community empowerment zone that are not in conformity with this chapter.

. [Empty]
.. The termination of an area's designation as a community empowerment zone under subsection (1)(b) of this section is not effective until the department issues a finding stating the reasons for the termination, which may include lack of commitment of resources to activities in the community empowerment zone by the public, private, and community-based sectors. The local government may file an appeal to the department's findings within sixty days of the notice to terminate the area's designation. The department must notify the local government of the results within thirty days of the filing of the appeal.

.. A termination of an area's designation as a community empowerment zone has no effect on benefits previously extended to individual businesses. The local government may not commit benefits to a business after the effective date of the termination of an area's designation as a community empowerment zone.

. The department may request applications from local governments for designation as community empowerment zones under this chapter as a result of a termination of an area's designation as a community empowerment zone under this section.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2460-S.SL.pdf?cite=2000%20c%20212%20§%206[2000 c 212 § 6]; ]

== 43.31C.060 - Administration of chapter—Powers and duties of department.
The department must administer this chapter and has the following powers and duties:

. To monitor the implementation of chapter 212, Laws of 2000 and submit reports evaluating the effectiveness of the program and any suggestions for legislative changes to the governor and legislature by December 1, 2000;

. To develop evaluation and performance measures for local governments to measure the effectiveness of the program at the local level on meeting the objectives of this chapter;

. To provide information and appropriate assistance to persons desiring to locate and operate a business in a community empowerment zone;

. To work with appropriate state agencies to coordinate the delivery of programs, including but not limited to housing, community and economic development, small business assistance, social service, and employment and training programs which are carried on in a community empowerment zone; and

. To develop rules necessary for the administration of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2460-S.SL.pdf?cite=2000%20c%20212%20§%207[2000 c 212 § 7]; ]

== 43.31C.070 - Administration of community empowerment zone—Jurisdiction of local government—Community empowerment zone administrator.
The administration of a community empowerment zone is under the jurisdiction of the local government. Each local government must, by ordinance, designate a community empowerment zone administrator for the area designated as a community empowerment zone that is within its jurisdiction. A community empowerment zone administrator must be an officer or employee of the local government. The community empowerment zone administrator is the liaison between the local government, the department, the business community, and labor and community-based organizations within the community empowerment zone.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2460-S.SL.pdf?cite=2000%20c%20212%20§%208[2000 c 212 § 8]; ]

== 43.31C.900 - Short title.
This chapter may be known and cited as the Washington community empowerment zone act.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2460-S.SL.pdf?cite=2000%20c%20212%20§%209[2000 c 212 § 9]; ]

== 43.31C.901 - Conflict with federal requirements—2000 c 212.
If any part of this act is found to be in conflict with federal requirements that are a prescribed condition to the allocation of federal funds to the state, the conflicting part of this act is inoperative solely to the extent of the conflict and with respect to the agencies directly affected, and this finding does not affect the operation of the remainder of this act in its application to the agencies concerned. Rules adopted under this act must meet federal requirements that are a necessary condition to the receipt of federal funds by the state.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2460-S.SL.pdf?cite=2000%20c%20212%20§%2012[2000 c 212 § 12]; ]

