= 43.21I - Oil spill prevention program.
:toc:

== 43.21I.010 - Program created—Powers and duties—Definitions.
. There is hereby created within the department of ecology an oil spill prevention program. For the program, the department shall be vested with all powers and duties transferred to it from the *office of marine safety and such other powers and duties as may be authorized by law. The main administrative office for the program shall be located in the city of Olympia. The director may establish administrative facilities in other locations, if deemed necessary for the efficient operation of the program, and if consistent with the principles set forth in subsection (2) of this section.

. The oil spill prevention program shall be organized consistent with the goals of providing state government with a focus in marine transportation and serving the people of this state. The legislature recognizes that the director needs sufficient organizational flexibility to carry out the program's various duties. To the extent practical, the director shall consider the following organizational principles:

.. Clear lines of authority which avoid functional duplication within and between subelements of the program;

.. A clear and simplified organizational design promoting accessibility, responsiveness, and accountability to the legislature, the consumer, and the general public; and

.. Maximum span of control without jeopardizing adequate supervision.

. The department, through the program, shall provide leadership and coordination in identifying and resolving threats to the safety of marine transportation and the impact of marine transportation on the environment:

.. Working with other state agencies and local governments to strengthen the state and local governmental partnership in providing public protection;

.. Providing expert advice to the executive and legislative branches of state government;

.. Providing active and fair enforcement of rules;

.. Working with other federal, state, and local agencies and facilitating their involvement in planning and implementing marine safety measures;

.. Providing information to the public; and

.. Carrying out such other related actions as may be appropriate to this purpose.

. In accordance with the administrative procedure act, chapter 34.05 RCW, the department shall ensure an opportunity for consultation, review, and comment before the adoption of standards, guidelines, and rules.

. Consistent with the principles set forth in subsection (2) of this section, the director may create such administrative divisions, offices, bureaus, and programs within the program as the director deems necessary. The director shall have complete charge of and supervisory powers over the program, except where the director's authority is specifically limited by law.

. The director shall appoint such personnel as are necessary to carry out the duties of the program. In addition to exemptions set forth in RCW 41.06.070, up to four professional staff members shall be exempt from the provisions of chapter 41.06 RCW. All other employees of the program shall be subject to the provisions of chapter 41.06 RCW.

. The definitions in this section apply throughout this chapter.

.. "Department" means the department of ecology.

.. "Director" means the director of the department.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6210-S.SL.pdf?cite=2000%20c%2069%20§%2027[2000 c 69 § 27]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2389-S.SL.pdf?cite=1992%20c%2073%20§%204[1992 c 73 § 4]; 1995 2nd sp.s. c 14 § 515; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1027-S.SL.pdf?cite=1991%20c%20200%20§%20402[1991 c 200 § 402]; ]

== 43.21I.030 - Director's powers.
In addition to any other powers granted the director, the director may:

. Adopt, in accordance with chapter 34.05 RCW, rules necessary to carry out the provisions of this chapter and chapter 88.46 RCW;

. Appoint such advisory committees as may be necessary to carry out the provisions of this chapter and chapter 88.46 RCW. Members of such advisory committees are authorized to receive travel expenses in accordance with RCW 43.03.050 and 43.03.060. The director shall review each advisory committee within the jurisdiction of the program and each statutory advisory committee on a biennial basis to determine if such advisory committee is needed. The criteria specified in *RCW 43.131.070 shall be used to determine whether or not each advisory committee shall be continued;

. Undertake studies, research, and analysis necessary to carry out the provisions of this chapter and chapter 88.46 RCW;

. Delegate powers, duties, and functions of the program to employees of the department as the director deems necessary to carry out the provisions of this chapter and chapter 88.46 RCW;

. Enter into contracts on behalf of the department to carry out the purposes of this chapter and chapter 88.46 RCW;

. Act for the state in the initiation of, or the participation in, any intergovernmental program for the purposes of this chapter and chapter 88.46 RCW; or

. Accept gifts, grants, or other funds.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6210-S.SL.pdf?cite=2000%20c%2069%20§%2028[2000 c 69 § 28]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2389-S.SL.pdf?cite=1992%20c%2073%20§%2011[1992 c 73 § 11]; 1995 2nd sp.s. c 14 § 516; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1027-S.SL.pdf?cite=1991%20c%20200%20§%20405[1991 c 200 § 405]; ]

== 43.21I.040 - Authority to administer oaths and issue subpoenas.
. The director shall have full authority to administer oaths and take testimony thereunder, to issue subpoenas requiring the attendance of witnesses before the director together with all books, memoranda, papers, and other documents, articles or instruments, and to compel the disclosure by such witnesses of all facts known to them relative to the matters under investigation.

. Subpoenas issued in adjudicative proceedings shall be governed by chapter 34.05 RCW.

. Subpoenas issued in the conduct of investigations required or authorized by other statutory provisions or necessary in the enforcement of other statutory provisions shall be governed by chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6210-S.SL.pdf?cite=2000%20c%2069%20§%2029[2000 c 69 § 29]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1027-S.SL.pdf?cite=1991%20c%20200%20§%20407[1991 c 200 § 407]; 1995 2nd sp.s. c 14 § 517; ]

== 43.21I.900 - Effective dates—1991 c 200.
See RCW 90.56.901.

[ ]

