= 43.21H - State economic policy.
:toc:

== 43.21H.010 - Purpose.
The purpose of this chapter is to assert that it is the intent of the legislature that economic values are given appropriate consideration along with environmental, social, health, and safety considerations in the promulgation of rules by state and local government.

[ 1975-'76 2nd ex.s. c 117 § 1; ]

== 43.21H.020 - State and local authorities to insure that economic impacts and values be given appropriate consideration in rule-making process.
The legislature finds that agency and local government decisions can have negative economic consequences for businesses, particularly small businesses, as well as for employees of those businesses. All state agencies and local government entities with rule-making authority under state law or local ordinance must adopt methods and procedures which will insure that economic impacts and values will be given appropriate consideration in the rule-making process along with environmental, social, health, and safety considerations.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5500.SL.pdf?cite=2011%20c%20249%20§%201[2011 c 249 § 1]; 1975-'76 2nd ex.s. c 117 § 2; ]

== 43.21H.030 - Statutory obligations of agencies not affected.
Nothing in this chapter shall in any way affect the specific statutory obligations of any agency:

. To comply with environmental, social, health, safety, or other standards prescribed by law;

. To coordinate or consult with any other public agency; or

. To act, or refrain from acting, where required by law, upon the recommendations or certification of another public agency.

[ 1975-'76 2nd ex.s. c 117 § 3; ]

