= 43.185A - Affordable housing program.
:toc:

== 43.185A.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Affordable housing" means residential housing for rental occupancy which, as long as the same is occupied by low-income households, requires payment of monthly housing costs, including utilities other than telephone, of no more than thirty percent of the family's income. The department must adopt policies for residential homeownership housing, occupied by low-income households, which specify the percentage of family income that may be spent on monthly housing costs, including utilities other than telephone, to qualify as affordable housing.

. "Contracted amount" has the same meaning as provided in RCW 43.185.020.

. "Department" means the department of commerce.

. "Director" means the director of the department of commerce.

. "First-time home buyer" means an individual or his or her spouse or domestic partner who have not owned a home during the three-year period prior to purchase of a home.

. "Low-income household" means a single person, family or unrelated persons living together whose adjusted income is less than eighty percent of the median family income, adjusted for household size, for the county where the project is located.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1617-S.SL.pdf?cite=2013%20c%20145%20§%204[2013 c 145 § 4]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2009%20c%20565%20§%2038[2009 c 565 § 38]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%20301[2008 c 6 § 301]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6663-S.SL.pdf?cite=2000%20c%20255%20§%209[2000 c 255 § 9]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%20102[1995 c 399 § 102]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1624-S.SL.pdf?cite=1991%20c%20356%20§%2010[1991 c 356 § 10]; ]

== 43.185A.020 - Affordable housing program—Purpose—Input.
The affordable housing program is created in the department for the purpose of developing and coordinating public and private resources targeted to meet the affordable housing needs of low-income households in the state of Washington. The program shall be developed and administered by the department with advice and input from the affordable housing advisory board established in RCW 43.185B.020.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%20103[1995 c 399 § 103]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5584.SL.pdf?cite=1993%20c%20478%20§%2016[1993 c 478 § 16]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1624-S.SL.pdf?cite=1991%20c%20356%20§%2011[1991 c 356 § 11]; ]

== 43.185A.030 - Activities eligible for assistance.
. Using moneys specifically appropriated for such purpose, the department shall finance in whole or in part projects that will provide housing for low-income households.

. Activities eligible for assistance include, but are not limited to:

.. New construction, rehabilitation, or acquisition of housing for low-income households;

.. Rent subsidies in new construction or rehabilitated multifamily units;

.. Down payment or closing costs assistance for first-time home buyers;

.. Mortgage subsidies for new construction or rehabilitation of eligible multifamily units; and

.. Mortgage insurance guarantee or payments for eligible projects.

. Legislative appropriations from capital bond proceeds may be used only for the costs of projects authorized under subsection (2)(a), (c), (d), and (e) of this section, and not for the administrative costs of the department.

. Moneys from repayment of loans from appropriations from capital bond proceeds may be used for all activities necessary for the proper functioning of the affordable housing program except for activities authorized under subsection (2)(b) of this section.

. Administrative costs associated with application, distribution, and project development activities of the department may not exceed three percent of the annual funds available for the affordable housing program. Reappropriations must not be included in the calculation of the annual funds available for determining the administrative costs.

. Administrative costs associated with compliance and monitoring activities of the department may not exceed one-quarter of one percent annually of the contracted amount of state investment in the affordable housing program.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1617-S.SL.pdf?cite=2013%20c%20145%20§%205[2013 c 145 § 5]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1087-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2050%20§%20954[2011 1st sp.s. c 50 § 954]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6090-S.SL.pdf?cite=2005%20c%20518%20§%201803[2005 c 518 § 1803]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1074.SL.pdf?cite=2005%20c%20219%20§%203[2005 c 219 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2190.SL.pdf?cite=1994%20c%20160%20§%203[1994 c 160 § 3]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1624-S.SL.pdf?cite=1991%20c%20356%20§%2012[1991 c 356 § 12]; ]

== 43.185A.040 - Eligible organizations.
Organizations that may receive assistance from the department under this chapter are local governments, local housing authorities, nonprofit community or neighborhood-based organizations, federally recognized Indian tribes in the state of Washington, and regional or statewide nonprofit housing assistance organizations.

Eligibility for assistance from the department under this chapter also requires compliance with the revenue and taxation laws, as applicable to the recipient, at the time the grant is made.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2190.SL.pdf?cite=1994%20c%20160%20§%204[1994 c 160 § 4]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1624-S.SL.pdf?cite=1991%20c%20356%20§%2013[1991 c 356 § 13]; ]

== 43.185A.050 - Grant and loan application process—Report.
. During each calendar year in which funds are available for use by the department for the affordable housing program, the department must announce to all known interested parties, and through major media throughout the state, a grant and loan application period of at least ninety days' duration. This announcement must be made as often as the director deems appropriate for proper utilization of resources. The department must then promptly grant as many applications as will utilize available funds less appropriate administrative costs of the department as provided in RCW 43.185A.030.

. Until June 30, 2013, for applications submitted for funding under RCW 43.185A.030(2)(a), the department must consider total cost and per-unit cost of each project compared to similar housing projects constructed or renovated within the same geographic area.

. The department must develop, with advice and input from the affordable housing advisory board established in RCW 43.185B.020, or a subcommittee of the affordable housing advisory board:

.. Additional criteria to evaluate applications for assistance under this chapter; and

.. Recommendations for awarding funds under RCW 43.185A.030(2)(a) in a cost-effective manner, including an implementation plan, timeline, and any other items the department identifies as important to consider. The department must submit a report with the recommendations to the legislature by December 1, 2012.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1617-S.SL.pdf?cite=2013%20c%20145%20§%206[2013 c 145 § 6]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2640-S.SL.pdf?cite=2012%20c%20235%20§%202[2012 c 235 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1624-S.SL.pdf?cite=1991%20c%20356%20§%2014[1991 c 356 § 14]; ]

== 43.185A.060 - Protection of state interest.
The department shall adopt policies to ensure that the state's interest will be protected upon either the sale or change of use of projects financed in whole or in part under RCW 43.185A.030(2) (a), (b), (c), (d), and (e). These policies may include, but are not limited to: (1) Requiring a share of the appreciation in the project in proportion to the state's contribution to the project; (2) requiring a lump-sum repayment of the loan or grant upon the sale or change of use of the project; or (3) requiring a deferred payment of principal or principal and interest on loans after a specified time period.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1624-S.SL.pdf?cite=1991%20c%20356%20§%2015[1991 c 356 § 15]; ]

== 43.185A.070 - Monitor recipient activities.
The director shall monitor the activities of recipients of grants and loans under this chapter to determine compliance with the terms and conditions set forth in its application or stated by the department in connection with the grant or loan.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1624-S.SL.pdf?cite=1991%20c%20356%20§%2016[1991 c 356 § 16]; ]

== 43.185A.080 - Rules.
The department shall have the authority to promulgate rules pursuant to chapter 34.05 RCW, regarding the grant and loan process, and the substance of eligible projects, consistent with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1624-S.SL.pdf?cite=1991%20c%20356%20§%2017[1991 c 356 § 17]; ]

== 43.185A.090 - Application process—Distribution procedure.
The application process and distribution procedure for the allocation of funds are the same as the competitive application process and distribution procedure described in RCW 43.185.130.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2418-S2.SL.pdf?cite=2006%20c%20349%20§%204[2006 c 349 § 4]; ]

== 43.185A.100 - Housing programs and services—Review of reporting requirements—Report to the legislature.
The department, the housing finance commission, the affordable housing advisory board, and all local governments, housing authorities, and other nonprofits receiving state housing funds or financing through the housing finance commission shall, by December 31, 2006, and annually thereafter, review current housing reporting requirements related to housing programs and services and give recommendations to streamline and simplify all planning and reporting requirements to the *department of community, trade, and economic development, which will compile and present the recommendations annually to the legislature. The entities listed in this section shall also give recommendations for additional legislative actions that could promote affordable housing and end homelessness.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2418-S2.SL.pdf?cite=2006%20c%20349%20§%2011[2006 c 349 § 11]; ]

== 43.185A.110 - Affordable housing land acquisition revolving loan fund program.
. The affordable housing land acquisition revolving loan fund program is created in the department to assist eligible organizations, described under RCW 43.185A.040, to purchase land for affordable housing development. The department shall contract with the Washington state housing finance commission to administer the affordable housing land acquisition revolving loan fund program. Within this program, the Washington state housing finance commission shall establish and administer the Washington state housing finance commission land acquisition revolving loan fund.

. As used in this chapter, "market rate" means the current average market interest rate that is determined at the time any individual loan is closed upon using a widely recognized current market interest rate measurement to be selected for use by the Washington state housing finance commission with the department's approval. This interest rate must be noted in an attachment to the closing documents for each loan.

. Under the affordable housing land acquisition revolving loan fund program:

.. Loans may be made to purchase vacant or improved land on which to develop affordable housing. In addition to affordable housing, facilities intended to provide supportive services to affordable housing residents and low-income households in the nearby community may be developed on the land.

.. Eligible organizations applying for a loan must include in the loan application a proposed affordable housing development plan indicating the number of affordable housing units planned, a description of any other facilities being considered for the property, and an estimated timeline for completion of the development. The Washington state housing finance commission may require additional information from loan applicants and may consider the efficient use of land, project readiness, organizational capacity, and other factors as criteria in awarding loans.

.. Forty percent of the loans shall go to eligible applicants operating homeownership programs for low-income households in which the households participate in the construction of their homes. Sixty percent of loans shall go to other eligible organizations. If the entire forty percent for applicants operating self-help homeownership programs cannot be lent to these types of applicants, the remainder shall be lent to other eligible organizations.

.. Within five years of receiving a loan, a loan recipient must present the Washington state housing finance commission with an updated development plan, including a proposed development design, committed and anticipated additional financial resources to be dedicated to the development, and an estimated development schedule, which indicates completion of the development within eight years of loan receipt. This updated development plan must be substantially consistent with the development plan submitted as part of the original loan application as required in (b) of this subsection.

.. Within eight years of receiving a loan, a loan recipient must develop affordable housing on the property for which the loan was made and place the affordable housing into service.

.. A loan recipient must preserve the affordable rental housing developed on the property acquired under this section as affordable housing for a minimum of thirty years.

. If a loan recipient does not place affordable housing into service on a property for which a loan has been received under this section within the eight-year period specified in subsection (3)(e) of this section, or if a loan recipient fails to use the property for the intended affordable housing purpose consistent with the loan recipient's original affordable housing development plan, then the loan recipient must pay to the Washington state housing finance commission an amount consisting of the principal of the original loan plus compounded interest calculated at the current market rate. The Washington state housing finance commission shall develop guidelines for the time period in which this repayment must take place, which must be noted in the original loan agreement. The Washington state housing finance commission may grant a partial or total exemption from this repayment requirement if it determines that a development is substantially complete or that the property has been substantially used in keeping with the original affordable housing purpose of the loan. Any repayment funds received as a result of noncompliance with loan requirements shall be deposited into the Washington state housing finance commission land acquisition revolving loan fund for the purposes of the affordable housing land acquisition revolving loan fund program.

. The Washington state housing finance commission, with approval from the department, may adopt guidelines and requirements that are necessary to administer the affordable housing land acquisition revolving loan fund program.

. Interest rates on property loans granted under this section may not exceed one percent. All loan repayment moneys received shall be deposited into the Washington state housing finance commission affordable housing land acquisition revolving loan fund for the purposes of the affordable housing land acquisition revolving loan fund program.

. The Washington state housing finance commission must develop performance measures for the program, which must be approved by the department, including, at a minimum, measures related to:

.. The ability of eligible organizations to access land for affordable housing development;

.. The total number of dwelling units by housing type and the total number of low-income households and persons served; and

.. The financial efficiency of the program as demonstrated by factors, including the cost per unit developed for affordable housing units in different areas of the state and a measure of the effective use of funds to produce the greatest number of units for low-income households.

. By December 1st of each year, beginning in 2007, the Washington state housing finance commission shall report to the department and the appropriate committees of the legislature using, at a minimum, the performance measures developed under subsection (7) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1616.SL.pdf?cite=2017%20c%20274%20§%201[2017 c 274 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3142.SL.pdf?cite=2008%20c%20112%20§%201[2008 c 112 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1401-S2.SL.pdf?cite=2007%20c%20428%20§%202[2007 c 428 § 2]; ]

== 43.185A.120 - Affordable housing and community facilities rapid response loan program.
. The affordable housing and community facilities rapid response loan program is created in the department to assist eligible organizations, described under RCW 43.185A.040, to purchase land or real property for affordable housing and community facilities preservation or development in rapidly gentrifying neighborhoods or communities with a significant low-income population that is threatened with displacement by such gentrification. The department shall contract with the Washington state housing finance commission to establish and administer the program.

. Loans or grants may be made through the affordable housing and community facilities rapid response loan program to purchase land or real property for the preservation or development of affordable housing or community facilities, including reasonable costs and fees.

. The Washington state housing finance commission, with approval from the department, may adopt guidelines and requirements that are necessary to administer the affordable housing and community facilities rapid response loan program.

. A loan or grant recipient must preserve affordable rental housing acquired or developed under this section as affordable housing for a minimum of thirty years.

. Interest rates on loans made under this section may be as low as zero percent but may not exceed three percent. All loan repayment moneys received must be deposited into a program account established by the Washington state housing finance commission for the purpose of making new loans and grants under this section.

. By December 1st of each year, beginning in 2008, the Washington state housing finance commission shall report to the department and the appropriate committees of the legislature: The number of loans and grants that were made in the program; for what purposes the loans and grants were made; to whom the loans and grants were made; and when the loans are expected to be paid back.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3142.SL.pdf?cite=2008%20c%20112%20§%202[2008 c 112 § 2]; ]

== 43.185A.900 - Short title.
This chapter may be known and cited as the affordable housing act.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1624-S.SL.pdf?cite=1991%20c%20356%20§%209[1991 c 356 § 9]; ]

== 43.185A.902 - Conflict with federal requirements—1991 c 356.
If any part of this act is found to be in conflict with federal requirements which are a prescribed condition to the allocation of federal funds to the state, the conflicting part of this act is inoperative solely to the extent of the conflict and with respect to the agencies directly affected, and this finding does not affect the operation of the remainder of this act in its application to the agencies concerned. The rules under this act shall meet federal requirements which are a necessary condition to the receipt of federal funds by the state.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1624-S.SL.pdf?cite=1991%20c%20356%20§%2019[1991 c 356 § 19]; ]

