= 43.102 - Office of independent investigations.
:toc:

== 43.102.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Advisory board" means the office of independent investigations advisory board.

. "Deadly force" has the meaning provided in RCW 9A.16.010.

. "Director" means the director of the office of independent investigations.

. "Great bodily harm" has the meaning provided in RCW 9A.04.110.

. "In-custody" refers to a person who is under the physical control of a general authority Washington law enforcement agency or a limited authority Washington law enforcement agency as defined in RCW 10.93.020 or a city, county, or regional adult or juvenile institution, correctional, jail, holding, or detention facility as defined in RCW 70.48.020, 72.09.015, or 13.40.020.

. "Independent investigation team" means a team of qualified and certified peace officer investigators, civilian crime scene specialists, and other representatives who operate independently of any involved agency to conduct investigations of police deadly force incidents. An independent investigation team may be comprised of multiple law enforcement agencies who jointly investigate police use of force incidents in their geographical regions or may be a single law enforcement agency, provided it is not the involved agency.

. "Involved agency" means a general authority Washington law enforcement agency or limited authority Washington law enforcement agency, as defined in RCW 10.93.020, that employs or supervises the officer or officers who are an involved officer as defined in this section, or an agency responsible for a city, county, or regional adult or juvenile institution, correctional, jail, holding, or detention facility as defined in RCW 70.48.020, 72.09.015, or 13.40.020.

. "Involved officer" means one of the following persons who is involved in an incident as an actor or custodial officer in which the act or omission by the individual is within the scope of the jurisdiction of the office as defined in this chapter:

.. A general authority Washington peace officer, specially commissioned Washington peace officer, or limited authority Washington peace officer, as defined in RCW 10.93.020, whether on or off duty if he or she is exercising his or her authority as a peace officer; or

.. An individual while employed in a city, county, or regional adult or juvenile institution, correctional, jail, holding, or detention facility as defined in RCW 70.48.020, 72.09.015, or 13.40.020.

. "Office" means the office of independent investigations.

. "Substantial bodily harm" has the same meaning as in RCW 9A.04.110.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1267-S.SL.pdf?cite=2021%20c%20318%20§%20201[2021 c 318 § 201]; ]

== 43.102.020 - Creation.
. The office of independent investigations is hereby established within the office of the governor for the purpose of conducting fair, thorough, transparent, and competent investigations as authorized under this chapter.

. The office of independent investigations is an investigative law enforcement agency, including for the purposes of the public records act, chapter 42.56 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1267-S.SL.pdf?cite=2021%20c%20318%20§%20301[2021 c 318 § 301]; ]

== 43.102.030 - Powers and duties.
In addition to other responsibilities set forth in this chapter, the office shall:

. Conduct fair, thorough, transparent, and competent investigations of police use of force and other incidents involving law enforcement as authorized in this chapter and shall prioritize investigations conducted by the office based on resources and other criteria developed in consultation with the advisory board. The office shall commence investigations as follows:

.. Beginning no later than July 1, 2022, the office is authorized to conduct investigations of deadly force cases occurring after July 1, 2022, including any incident involving use of deadly force by an involved officer against or upon a person who is in-custody or out-of-custody; and

.. Beginning no later than July 1, 2023, the office is authorized to review, and may investigate, prior investigations of deadly force by an involved officer if new evidence is brought forth that was not included in the initial investigation;

. Analyze data available to the office and provide reports and recommendations as appropriate based on the data regarding issues, trends, and other relevant areas;

. Provide reports on activities of the office as authorized under this chapter; and

. Carry out such other responsibilities as may be consistent with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1267-S.SL.pdf?cite=2021%20c%20318%20§%20302[2021 c 318 § 302]; ]

== 43.102.040 - Director.
. [Empty]
.. The governor shall appoint the director of the office and determine the director's compensation. The governor shall select the director from a list of three candidates recommended by the advisory board unless the governor declines to select any of the candidates provided. If the governor declines to select a candidate proposed by the advisory board, the governor may request the advisory board to provide additional qualified nominees for consideration or may offer an alternative candidate who may be appointed following approval by a majority of the advisory board.

.. Prior to selecting the director, the governor shall consider the results of a background check, including an assessment of criminal history, and research of social media and affiliations to check for racial bias and conflicts of interest.

. The director shall hold office for a term of three years and continue to hold office until reappointed or until his or her successor is appointed. The governor may remove the director prior to the expiration of the director's term for neglect of duty, misconduct, or inability to perform duties.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1267-S.SL.pdf?cite=2021%20c%20318%20§%20303[2021 c 318 § 303]; ]

== 43.102.050 - Director—Duties—Review of prior investigations.
. The director shall:

.. Oversee the duties and functions of the office and investigations conducted by the office pursuant to this chapter;

.. Hire or contract with investigators and other personnel as the director considers necessary to perform investigations conducted by the office, and other duties as required, under this chapter;

.. Plan and provide trainings for office personnel, including contracted investigators, that promote recognition of and respect for, the diverse races, ethnicities, and cultures of the state;

.. Plan and provide training for advisory board members including training to utilize an antiracist lens in their duties as advisory board members;

.. Publish reports of investigations conducted under this chapter;

.. Enter into contracts and memoranda of understanding as necessary to implement the responsibilities of the office under this chapter;

.. Adopt rules in accordance with chapter 34.05 RCW and perform all other functions necessary and proper to carry out the purposes of this chapter;

.. Develop the nondisclosure agreement required in RCW 43.102.130; and

.. Perform the duties and exercise the powers that are set out in this chapter, as well as any additional duties and powers that may be prescribed.

. No later than February 1, 2022, in consultation with the advisory board, the director shall develop a plan to implement:

.. Regional investigation teams and a system for promptly responding to incidents of deadly force under the jurisdiction of the office. The regional investigation teams should:

... Allow for prompt response to the incident requiring investigation; and

... Include positions for team members who are not required to be designated as limited authority Washington peace officers;

.. A system and requirements for involved agencies to notify the office of any incident under the jurisdiction of the office, which must include direction to agencies as to what incidents of force and injuries and other circumstances must be reported to the office, including the timing of such reports, provided that any incident involving substantial bodily harm, great bodily harm, or death is reported to the office immediately in accordance with RCW 43.102.120;

.. The process to conduct investigations of cases under the jurisdiction of the office including, but not limited to:

... The office intake process following notification of an incident by an involved agency;

... The assessment and response to the notification of the incident by the office, including direction to and coordination with the independent investigation team;

... Determination and deployment of necessary resources for the regional investigation teams to conduct the investigations;

... Determination of any conflicts with office investigators or others involved in the investigation to ensure no investigator has an existing conflict with an assigned case;

.. Protocol and direction to the involved agency;

.. Protocol and direction to the independent investigation team;

.. Protocol and guidelines for contacts and engagement with the involved agency; and

.. Protocol for finalizing the completed investigation and referral to the entity responsible for the prosecutorial decision, including communication with the family and public regarding the completion of the investigation;

.. A plan for the office's interaction, communications, and responsibilities to: The involved officer; the individual who is the subject of the action by the involved officer that is the basis of the case under investigation, and their families; the public; and other interested parties or stakeholders. The plan must consider the following:

... A process for consultation, notifications, and communications with the person, family, or representative of any person who is the subject of the action by the involved officer that is the basis of the case under investigation;

... Translation services which may be utilized through employees or contracted services;

... Support to access assistance or services to the extent possible; and

... A process for situations in which a tribal member is involved in the case that ensures consultation with the federally recognized tribe, and notification of the governor's office of Indian affairs within 24 hours in cases of deadly use of force;

.. Training for employees and contractors of the office to begin prior to July 1, 2022; and

.. Prioritization of cases for investigation.

. No later than December 1, 2023, in consultation with the advisory board, the director shall develop a proposal for training individuals who are nonlaw enforcement officers to conduct competent, thorough investigations of cases under the jurisdiction of the office. The proposal must establish a training plan with an objective that within five years of the date the office begins investigating deadly force cases the cases will be investigated by nonlaw enforcement officers. The director shall report such proposal to the governor and legislature by December 1, 2023. Any proposal offered by the director must ensure investigations are high quality, thorough, and competent.

. The director, in consultation with the advisory board, shall implement a plan to review prior investigations of deadly force by an involved officer if new evidence is brought forth that was not included in the initial investigation and investigate if determined appropriate based on the review. The director must prioritize the review or investigation of cases occurring prior to July 1, 2022, based on resources and other cases under investigation with the office.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1267-S.SL.pdf?cite=2021%20c%20318%20§%20304[2021 c 318 § 304]; ]

== 43.102.060 - Personnel.
. The director may employ, or enter into contracts with, personnel as he or she determines necessary for the proper discharge of his or her duties. The director must request input from the advisory board on the hiring process and hiring goals, including diversity.

. The director may employ, or enter into contracts with, investigators to conduct investigations of cases under the jurisdiction of the office.

.. The director shall consider the relevant experience and qualifications of the candidate including the extent to which he or she demonstrates experience or understanding of the following areas:

... Extensive experience with criminal investigations, including homicide investigations;

... Behavioral health issues;

... Youth cognitive development;

... Trauma-informed interviewing;

.. De-escalation techniques and utilization; and

.. Knowledge of Washington practices, including laws, policies, and procedures related to criminal law, criminal investigations, and policing.

.. The director shall consider the following prior to employing an investigator:

... The investigators should not be commissioned law enforcement officers employed with any law enforcement agency as a peace officer at the time of application with the office.

(A) If the individual considered for a position as an investigator was a prior law enforcement officer, the director must conduct a review of prior disciplinary actions or complaints related to bias.

(B) The individual should not have been a commissioned law enforcement officer within 24 months of the date of the application for service as an investigator; and

... The results of a background check that includes research of social media and affiliations to check for racial bias and conflicts of interest.

.. Investigators employed or contracted with the office are prohibited from being simultaneously employed, commissioned, or have any business relationship, other than through the work of the office, with a general authority or limited authority Washington law enforcement agency, or county or city corrections agency.

.. The director may not employ an individual who was a previously commissioned law enforcement officer who does not meet the criteria of this section without the approval of a majority of the advisory board.

. The director may employ or enter into contracts for services to provide additional personnel as needed to conduct investigations of cases under the jurisdiction of the office including, but not limited to, the following:

.. Forensic services and crime scene investigators;

.. Liaisons for community, family, and relations with a federally recognized tribe;

.. Analysts, including analysts to conduct evaluations on use of force data;

.. Mental health experts;

.. Bilingual staff, translators, or interpreters;

.. Other experts as needed; and

.. All staffing and other needs for the office.

. The director shall ensure the following training is provided to staff and that there is a regular schedule for additional trainings during the course of employment:

.. The director shall ensure that the director and staff involved in investigations, including any contracted investigators, engage in trainings that include the following areas. A training may include more than one of the following areas per training. A separate training course is not required for each topic.

... History of racism in policing, including tribal sovereignty and history of Native Americans within the justice system;

... Implicit and explicit bias training;

... Intercultural competency;

... The use of a racial equity lens in conducting the work of the office;

.. Antiracism training; and

.. Undoing institutional racism.

.. The director shall ensure that investigators engage in the following training. A training may include more than one of the following areas per training. A separate training course is not required for each topic.

... Criminal investigations, including homicide investigations as appropriate for the assigned positions;

... Washington practices, including Washington laws and policies, as well as relevant policing practices as appropriate;

... Interviewing techniques; and

... Other relevant trainings as needed.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1267-S.SL.pdf?cite=2021%20c%20318%20§%20305[2021 c 318 § 305]; ]

== 43.102.070 - Investigators.
. The director shall designate investigator positions that are limited authority Washington peace officers as defined in RCW 10.93.020. The investigators designated as limited authority Washington peace officers have the authority to investigate any case within the jurisdiction of the office and any criminal activity related to, or discovered in the course of, the investigation of the case under the jurisdiction of the incident that has a relationship to the investigation.

. Any investigator employed or contracted with the office for the purpose of conducting investigations may participate in the investigations of a case under the jurisdiction of the office. Only investigators who are limited authority Washington peace officers may be designated a lead investigator on any criminal investigation conducted by the office pursuant to this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1267-S.SL.pdf?cite=2021%20c%20318%20§%20306[2021 c 318 § 306]; ]

== 43.102.080 - Investigations—Duties and powers.
. The office has jurisdiction over, and is authorized to conduct investigations of, all cases and incidents as established within this section.

. [Empty]
.. The director may cause an investigation to be conducted into any incident:

... Of a use of deadly force by an involved officer occurring after July 1, 2022, including any incident involving use of deadly force by an involved officer against or upon a person who is in-custody or out-of-custody; or

... Involving prior investigations of deadly force by an involved officer if new evidence is brought forth that was not included in the initial investigation.

.. This section applies only if, at the time of the incident:

... The involved officer was on duty; or

... The involved officer was off duty but:

(A) Engaged in the investigation, pursuit, detention, or arrest of a person or otherwise exercising the powers of a general authority or limited authority Washington peace officer; or

(B) The incident involved equipment or other property issued to the official in relation to his or her duties.

. The director shall determine prioritization of investigations based on resources and other criteria which may be established in consultation with the advisory board. The director shall ensure that incidents occurring after the date the office begins investigating cases receive the highest priority for investigation.

. The investigation should include a review of the entire incident, including but not limited to events immediately preceding the incident that may have contributed to or influenced the outcome of the incident that are directly related to the incident under investigation.

. Upon receiving notification required in RCW 43.102.120 of an incident under the jurisdiction of the office, the director:

.. May cause the incident to be investigated in accordance with this chapter;

.. May determine investigation is not appropriate for reasons including, but not limited to, the case not being in the category of prioritized cases; or

.. If the director determines that the incident is not within the office's jurisdiction to investigate, the director shall decline to investigate, and shall give notice of the fact to the involved agency.

. If the director determines the case is to be investigated the director will communicate the decision to investigate to the involved agency and will thereafter be the lead investigative body in the case and have priority over any other state or local agency investigating the incident or a case that is under the jurisdiction of the office. The director will implement the process developed pursuant to RCW 43.102.050 and conduct the appropriate investigation in accordance with the process.

. In conducting the investigation the office shall have access to reports and information necessary or related to the investigation in the custody and control of the involved agency and any law enforcement agency responding to the scene of the incident including, but not limited to, voice or video recordings, body camera recordings, and officer notes, as well as disciplinary and administrative records except those that might be statements conducted as part of an administrative investigation related to the incident.

. The investigation shall be concluded within 120 days of acceptance of the case for investigation. If the office is not able to complete the investigation within 120 days, the director shall report to the advisory board the reasons for the delay.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1267-S.SL.pdf?cite=2021%20c%20318%20§%20308[2021 c 318 § 308]; ]

== 43.102.090 - Criminal justice training commission—Collaboration—Trainings.
. The criminal justice training commission shall collaborate with the office to ensure office investigators receive sufficient training to attain the necessary requirements to conduct investigations under the jurisdiction of the office.

. The investigators of the office shall receive priority registration to criminal justice training commission trainings necessary to conduct investigations as required by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1267-S.SL.pdf?cite=2021%20c%20318%20§%20309[2021 c 318 § 309]; ]

== 43.102.100 - Analysis of data—Reports.
The office will conduct analysis of use of force and other data to the extent such data is available to the office. The director is authorized to enter into contracts or memoranda of understanding to access data as needed. If data is available, the office should, at a minimum, analyze and report annually: Analysis and research regarding any identified trends, patterns, or other situations identified by the data; and recommendations for improvements. After July 1, 2024, the office should also annually report recommendations, if any, for expanding the scope of investigations or jurisdiction of the office based on trends, data, or reports received by the agency.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1267-S.SL.pdf?cite=2021%20c%20318%20§%20310[2021 c 318 § 310]; ]

== 43.102.110 - Liability.
No action or other proceeding may be instituted against the director, an investigator, or an employee or contractor in the office or a person exercising powers or performing duties at the direction of the director for any act done in good faith in the execution or intended execution of the person's duty or for any alleged neglect or default in the execution in good faith of the person's duty.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1267-S.SL.pdf?cite=2021%20c%20318%20§%20311[2021 c 318 § 311]; ]

== 43.102.120 - Investigations—Notification of director—Securing the scene—Control by investigation team.
. Following notification by the director that the office will accept investigations of cases under its jurisdiction after July 1, 2022, an involved agency shall notify the office of any incident by an involved officer in accordance with the requirements under RCW 43.102.050 and pursuant to this section.

.. If the incident involves use of deadly force by an involved officer that results in death, substantial bodily harm, or great bodily harm the involved agency must immediately contact the office pursuant to the procedure established by the director once the involved agency personnel and other first responders have rendered the scene safe and provided or facilitated lifesaving first aid to persons at the scene who have life-threatening injuries. This requirement does not affect the duty of law enforcement under RCW 36.28A.445.

.. In all other cases, the involved agency must notify the office of the incident pursuant to the procedure established by the director.

. [Empty]
.. In any case that requires notice to the director under this section, the involved agency shall ensure that any officers or employees over which the involved agency has authority who are at the scene of the incident take all lawful measures necessary for the purposes of protecting, obtaining, or preserving evidence relating to the incident until an office investigator, or independent investigation team at the request of the office, takes charge of the scene.

.. The primary focus of the involved agency must be the protection and preservation of evidence in order to maintain the integrity of the scene until the office investigator or independent investigation team arrives or otherwise provides direction regarding activities at the scene. The involved agency should ensure that evidence, including but not limited to the following is protected and preserved:

... Physical evidence that is at risk of being destroyed or disappearing and cannot be easily reconstructed, including evidence which may be degraded or tainted by human or environmental factors if left unprotected or unpreserved;

... Identification and contact information for witnesses to the incident; and

... Photographs and other methods of documenting the location of physical evidence and location and perspective of witnesses.

. [Empty]
.. When the office investigator, or independent investigation team acting at the request of the office, arrives at the scene of an incident under the jurisdiction of the office, the involved agency will relinquish control of the scene to the office investigator or independent investigation team upon the request of the office investigator. The involved agency has a duty to comply with the requests of the office related to the investigation conducted pursuant to this chapter.

.. Once the scene is relinquished, no member of the involved agency may participate in any way in the investigation, with the exception of the use of specialized equipment that is necessary for the investigation and where no alternative exists. If there is any equipment of the involved agency used in the investigation, steps must be taken to appropriately limit the role of any involved agency personnel in facilitating the use of that equipment or their engagement with the investigation.

. If an independent investigation team takes control of the scene at the request of the office, the independent investigation team shall relinquish control of the scene and investigation at the request of the office when the office is on the scene or otherwise provides notice that the office is taking control of the scene. The independent investigation team may continue to engage in the investigation conducted at the scene if requested to do so by the lead office investigator, director, or the director's designee. The involvement of the independent investigation team is limited to activities requested by the office and must terminate following the securing of the scene and any evidence preservation or other actions as determined necessary by the office at the scene. The independent investigation team may not continue to participate in the ongoing investigation.

. No information about the ongoing independent investigation under the jurisdiction of the office may be shared with any member of the involved agency, except limited briefings given to the chief or sheriff of the involved agency about the progress of the investigation.

. If the office declines to investigate a case, the authority and duty to investigate remains with the independent investigation team or local law enforcement authority with jurisdiction over the incident.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1267-S.SL.pdf?cite=2021%20c%20318%20§%20402[2021 c 318 § 402]; ]

== 43.102.130 - Office of independent investigations advisory board.
. [Empty]
.. There is created the office of independent investigations advisory board. The advisory board shall consist of the following 11 members, appointed by the governor, one of whom the governor shall designate as chair:

... Three members of the general public representing the community who are not current or former law enforcement, with preference given to individuals representing diverse communities;

... One member of the general public representing a family impacted by an incident of the nature under the jurisdiction of the office, who is not current or former law enforcement;

... One member representing a federally recognized tribe in Washington, who is not current or former law enforcement;

... One defense attorney representative;

.. One prosecuting attorney representative;

.. One representative of a police officer labor association with experience in homicide investigations;

.. One sheriff or police chief who is also a member of an independent investigation team;

.. One credentialed mental health expert who is not current or former law enforcement; and

... One member of the criminal justice training commission.

.. The members of the advisory board appointed by the governor shall be appointed for terms of three years and until their successors are appointed and confirmed. The governor shall stagger the initial appointment terms of the advisory board members with the terms of five members being for two years from the date of appointment and six members being for three years from the date of appointment. The governor shall designate the appointees who will serve the two-year and three-year terms. The members of the advisory board serve without compensation, but must be reimbursed for travel expenses as provided in RCW 43.03.050 and 43.03.060.

.. The governor, when making appointments to the advisory board, shall make appointments that reflect the cultural diversity of the state of Washington.

. The purpose of the advisory board is to provide input to the office and shall:

.. Provide input to the governor on the selection of the director, including providing candidates for consideration for appointment for the position of director. If the governor requests additional candidates for consideration, the advisory board shall provide additional candidates to the governor. If the governor provides an alternative candidate, the advisory board must consider the candidate provided by the governor and vote on the approval or rejection of the candidate.

... The advisory board shall recommend candidates to the governor who they find are individuals with sound judgment, independence, objectivity, and integrity who will be viewed as a trustworthy director.

... The director must have experience either in conducting criminal investigations or prosecutions. The advisory board shall consider the relevant experience and qualifications of the candidate including the extent to which they demonstrate experience or demonstrated understanding of the following areas:

(A) Criminal investigations;

(B) Organizational leadership;

(C) Mental health issues;

(D) Trauma-informed interviewing;

(E) Community leadership;

(F) Legal experience or background;

(G) Antioppression and antiracist analysis and addressing systemic inequities; and

(H) Working with black, indigenous, and communities of color;

.. Provide input to the director on the plans required to be developed for the office including the regional investigation teams; staffing; training for personnel; procedures for engagement with individuals involved in any case under the jurisdiction of the office, as well as families and the community; recommendations to the legislature; and other input as requested by the governor or director;

.. Participate in employment interviews as requested by the governor or director; and

.. Receive briefings or reports from the director relating to data, trends, and other relevant issues, as well as cases under investigation to the extent permitted by law.

. Advisory board members have a duty to maintain the confidentiality of the information they receive during the course of their work on the advisory board. Each advisory board member shall agree in writing to not disclose any information they receive or otherwise access related to an investigation, including information about individuals involved in the investigation as involved officers, individuals who are the subject of police action, witnesses, and investigators.

. Advisory board members must complete training to utilize an antiracist lens in their duties as advisory board members.

. The office shall provide administrative and clerical assistance to the advisory board.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1267-S.SL.pdf?cite=2021%20c%20318%20§%20501[2021 c 318 § 501]; ]

== 43.102.800 - Assessment of jurisdiction of office—Report. (Expires July 1, 2024.)
. In consultation with the director, the advisory board shall assess whether the jurisdiction of the office should be expanded to conduct investigations of other types of incidents committed by involved officers, including but not limited to other types of in-custody deaths not involving use of force but otherwise involving criminal acts committed by involved officers as well as sexual assaults committed by involved officers, subject to the same standard under RCW 43.102.080(2)(b). The advisory board must consider available data and information on other types of in custody deaths not involving use of force but otherwise involving criminal acts committed by involved officers as well as other types of incidents, the capacity and resources of the office, and any modifications or additions to procedures and processes necessary for the office to conduct investigations of those incidents. The advisory board must consider the recommendations and counsel of the director when conducting the assessment under this section.

. At the request of the advisory board, the office shall conduct analysis of available data, including identified trends and patterns, and other information relevant to in-custody deaths involving criminal acts committed by involved officers, sexual assaults committed by involved officers, and other types of incidents as requested by the advisory board.

. The advisory board shall submit a report with related recommendations to the legislature and governor by November 1, 2023.

. For the purposes of this section, "in-custody death" means a death of an individual while under physical control of a general authority Washington law enforcement agency or a limited authority Washington law enforcement agency as defined in RCW 10.93.020 or a city, county, or regional adult or juvenile institution, correctional, jail, holding, or detention facility as defined in RCW 70.48.020, 72.09.015, or 13.40.020.

. This section expires July 1, 2024.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1267-S.SL.pdf?cite=2021%20c%20318%20§%20502[2021 c 318 § 502]; ]

