= 43.147 - Pacific Northwest economic region agreement.
:toc:

== 43.147.010 - Terms of agreement.
The Pacific Northwest Economic Region is hereby enacted into law and entered into by the state of Washington as a party, and is in full force and effect in accordance with the terms of this agreement.

THE PACIFIC NORTHWEST ECONOMIC REGION

ARTICLE I—Policy and Purpose

States and provinces participating in the Pacific Northwest Economic Region shall seek to develop and establish policies that: Promote greater regional collaboration among the seven entities; enhance the overall competitiveness of the region in international and domestic markets; increase the economic well-being of all citizens in the region; and improve the quality of life of the citizens of the Pacific Northwest.

States and provinces recognize that there are many public policy areas in which cooperation and joint efforts would be mutually beneficial. These areas include, but are not limited to: International trade; economic development; human resources; the environment and natural resources; energy; and education. Parties to this agreement shall work diligently to establish collaborative activity in these and other appropriate policy areas where such cooperation is deemed worthwhile and of benefit to the participating entities. Participating states and provinces also agree that there are areas in which cooperation may not be feasible.

The substantive actions of the Pacific Northwest Economic Region may take the form of uniform legislation enacted by two or more states and/or provinces or policy initiatives endorsed as appropriate by participating entities. It shall not be necessary for all states and provinces to participate in each initiative.

ARTICLE II—Eligible Parties and Effective Date

Each of the following states and provinces is eligible to become a party to this agreement: Alaska, Alberta, British Columbia, Idaho, Montana, Oregon, and Washington. This agreement establishing the Pacific Northwest Economic Region shall become effective when it is executed by one state, one province, and one additional state and/or province in a form deemed appropriate by each entity. This agreement shall continue in force and remain binding upon each state and province until renounced by it. Renunciation of this agreement must be preceded by sending one year's notice in writing of intention to withdraw from the agreement to the other parties to the agreement.

ARTICLE III—Organizational Structure

Each state and province participating in this agreement shall appoint representatives to the Pacific Northwest Economic Region. The organizational structure of the Pacific Northwest Economic Region shall consist of the following: A delegate council consisting of four legislators and the governor or governor's designee from each participating state and four representatives and the premier or the premier's designee from each participating province and an executive committee consisting of one legislator from each participating state and/or province who is a member of the delegate council and four of the seven governors/premiers or their designees who are members of the delegate council. The legislator members of the executive committee from each state or province shall be chosen by the legislator members of that state or province. The four governor or premier members of the executive committee shall be chosen by the governors and premiers from among the governors and premiers on the delegate council. At least one of four members representing the governors and premiers on the executive committee must be the premier of a Canadian province. Policy committees may be established to carry out further duties and responsibilities of the Pacific Northwest Economic Region.

ARTICLE IV—Duties and Responsibilities

The delegate council shall have the following duties and responsibilities: Facilitate the involvement of other government officials in the development and implementation of specific collaborative initiatives; work with policy-making committees in the development and implementation of specific initiatives; approve general organizational policies developed by the executive committee; provide final approval of the annual budget and staffing structure for the Pacific Northwest Economic Region developed by the executive committee; and other duties and responsibilities as may be established in the rules and regulations of the Pacific Northwest Economic Region. The executive committee shall perform the following duties and responsibilities: Elect the president and vice president of the Pacific Northwest Economic Region; approve and implement general organizational policies; develop the annual budget; devise the annual action plan; act as liaison with other public and private sector entities; review the availability of, and if appropriate apply for, (1) tax exempt status under the laws and regulations of the United States or any state or subdivision thereof and (2) similar status under the laws and regulations of Canada or any province or subdivision thereof, and approve such rules, regulations, organizational policies, and staffing structure for the Pacific Northwest Economic Region and take such further actions on behalf of the Pacific Northwest Economic Region as may be deemed by the executive committee to be necessary or appropriate to qualify for and maintain such tax exempt or similar status under the applicable laws or regulations; and other duties and responsibilities established in the rules and regulations of the Pacific Northwest Economic Region. The rules and regulations of the Pacific Northwest Economic Region shall establish the procedure for voting.

ARTICLE V—Membership of Policy Committees

Policy committees dealing with specific subject matter may be established by the executive committee.

Each participating state and province shall appoint legislators and governors or premiers to sit on these committees in accordance with its own rules and regulations concerning such appointments.

ARTICLE VI—General Provisions

This agreement shall not be construed to limit the powers of any state or province or to amend or repeal or prevent the enactment of any legislation.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5699-S.SL.pdf?cite=1993%20c%20108%20§%201[1993 c 108 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5008-S.SL.pdf?cite=1991%20c%20251%20§%202[1991 c 251 § 2]; ]

== 43.147.020 - Finding.
The legislature finds that there is a new emerging global economy in which countries and regions located in specific areas of the world are forging new cooperative arrangements.

The legislature finds that these new cooperative arrangements are increasing the competitiveness of the participating countries and regions, thus increasing the economic benefits and the overall quality of life for the citizens of the individual countries and regions.

The legislature also finds that the Pacific Northwest states of Alaska, Idaho, Montana, Oregon, and Washington and the Canadian provinces of Alberta and British Columbia are in a strategic position to act together, as a region, thus increasing the overall competitiveness of the individual states and provinces that will provide substantial economic benefits for all of their citizens.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5008-S.SL.pdf?cite=1991%20c%20251%20§%201[1991 c 251 § 1]; ]

== 43.147.030 - Cooperative activities encouraged.
It is the intent of chapter 251, Laws of 1991 to direct and encourage the establishment of cooperative activities between the seven legislative bodies of the region. The state representatives to the Pacific Northwest Economic Region shall work through appropriate channels to advance consideration of proposals developed by this body.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5008-S.SL.pdf?cite=1991%20c%20251%20§%203[1991 c 251 § 3]; ]

== 43.147.040 - Interlibrary sharing—Finding.
In chapter 251, Laws of 1991, the legislature enacted into law the Pacific Northwest economic region agreement and made the state of Washington a party along with member states Alaska, Idaho, Montana, and Oregon, and member Canadian provinces Alberta and British Columbia. The legislature recognized that the member states and provinces of the Pacific Northwest economic region are in a strategic position to act together, as a region, thus increasing the overall competitiveness of the members and providing substantial economic benefits for all of their citizens.

For those reasons, in chapter 251, Laws of 1991, the legislature also encouraged the establishment of cooperative activities between the seven legislative bodies of the Pacific Northwest economic region. The member states and provinces now desire to engage in such cooperation by electronically sharing twenty-two million volumes from certain of their respective universities. The member states and provinces have determined that such interlibrary sharing will provide substantial economic benefit for their citizens. The legislature agrees, specifically also finding that such interlibrary sharing furthers a major component of education strategy in the 1990's and twenty-first century, namely providing increased access to knowledge via technology.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5745.SL.pdf?cite=1993%20c%20485%20§%201[1993 c 485 § 1]; ]

== 43.147.050 - Interlibrary sharing—Definition—Member libraries.
Unless the context clearly requires otherwise, as used in RCW 43.147.040 through 43.147.080 "PNWER-Net" means the technology network to be created by the member states and provinces of the Pacific Northwest economic region that will be capable of electronically linking the following undergraduate university libraries of the member states and provinces:

. Alaska:

.. University of Alaska, Anchorage;

.. University of Alaska, Juneau;

. Alberta:

.. University of Alberta, Calgary;

.. University of Alberta, Edmonton;

. British Columbia:

.. University of British Columbia, Vancouver;

.. University of Victoria, Victoria;

. Idaho:

.. Boise State University, Boise;

.. University of Idaho, Moscow;

. Montana:

.. Montana State University, Bozeman;

.. University of Montana, Missoula;

. Oregon:

.. Oregon State University, Corvallis;

.. University of Oregon, Eugene;

. Washington:

.. University of Washington, Seattle; and

.. Washington State University, Pullman.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5745.SL.pdf?cite=1993%20c%20485%20§%202[1993 c 485 § 2]; ]

== 43.147.060 - PNWER-Net working subgroup—Generally.
. The PNWER-Net working subgroup is hereby created for the member state of Washington. The working subgroup shall be composed of seven members as follows: Two members of the senate, one from each of the major caucuses, appointed by the president of the senate; two members of the house of representatives, appointed by the speaker of the house of representatives; the state librarian; and the primary undergraduate academic librarian from each of the state's two research institutions of higher education.

. The staff support shall be provided by the senate committee services and, to the extent authorized by the chief clerk of the house of representatives, by the house of representatives office of program research as mutually agreed by the legislators on the working group.

. Legislative members shall be reimbursed for expenses in accordance with RCW 44.04.120. Nonlegislative members shall be reimbursed for expenses in accordance with RCW 43.03.050 and 43.03.060.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5745.SL.pdf?cite=1993%20c%20485%20§%203[1993 c 485 § 3]; ]

== 43.147.070 - PNWER-Net working subgroup—Duties.
The PNWER-Net working subgroup shall have the following duties:

. To work with working subgroups from other member states and provinces in an entity known as the PNWER-Net working group to develop PNWER-Net; and

. To assist the PNWER-Net working group in developing criteria to ensure that designated member libraries use existing telecommunications infrastructure including the internet.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%2049[1998 c 245 § 49]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5745.SL.pdf?cite=1993%20c%20485%20§%204[1993 c 485 § 4]; ]

== 43.147.080 - PNWER-Net working subgroup—Gifts, grants, donations.
The PNWER-Net working group may accept gifts, grants, and donations from private individuals and entities made for the purposes of RCW 43.147.040 through 43.147.070.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5745.SL.pdf?cite=1993%20c%20485%20§%205[1993 c 485 § 5]; ]

