= 43.114 - LGBTQ commission.
:toc:

== 43.114.005 - Legislative declaration.
The legislature declares that the public policy of this state is to ensure equal opportunity for all Washingtonians. The legislature believes that the state is responsible for improving its interface with the LGBTQ community, identifying the needs of its members, and ensuring that there is an effective means of advocating for LGBTQ equity in all aspects of state government. Therefore, the legislature deems it necessary to create a commission to carry out the purposes of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5356-S2.SL.pdf?cite=2019%20c%20395%20§%201[2019 c 395 § 1]; ]

== 43.114.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Commission" means the Washington state LGBTQ commission.

. "LGBTQ" includes lesbian, gay, bisexual, transgender, and queer communities.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5356-S2.SL.pdf?cite=2019%20c%20395%20§%202[2019 c 395 § 2]; ]

== 43.114.020 - Commission established.
Subject to the availability of amounts appropriated for this specific purpose, the Washington state LGBTQ commission is established in the office of the governor. The commission shall be administered by an executive director, who shall be appointed by, and serve at the pleasure of, the governor. The governor shall set the salary of the executive director. The executive director shall employ the staff of the commission.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5356-S2.SL.pdf?cite=2019%20c%20395%20§%203[2019 c 395 § 3]; ]

== 43.114.030 - Membership—Terms—Vacancies—Expenses—Quorum.
. The commission consists of fifteen members appointed by the governor.

. The governor shall consider nominations for membership based upon maintaining a balanced and diverse distribution of race and ethnic, geographic, gender identity, sexual orientation, age, socioeconomic status, and occupational representation, where practicable.

. All commission members serve at the pleasure of the governor, but in no case may any member serve more than three years without formal reappointment by the governor. Of the persons initially appointed by the governor to the commission, five must be appointed to serve one year, five to serve two years, and five to serve three years. Upon expiration of such terms, subsequent appointments are for three years. Any vacancies occurring in the membership of the commission must be filled for the remainder of the unexpired term in the same manner as the original appointments.

. Two members of the senate, one from each of the two major political parties, appointed by the president of the senate, and two members of the house of representatives, one from each of the two major political parties, appointed by the speaker of the house of representatives, who support the legislative intent of the commission shall serve as advisory members. The legislative advisory members are nonvoting members and are not eligible to serve as a chair of the commission. All legislative advisory members shall serve for a two-year term and the position of any legislative advisory member shall be deemed vacated whenever such member ceases to be a member of the house from which the member was appointed.

. [Empty]
.. Nonlegislative members must be reimbursed for expenses incurred in the performance of their duties in accordance with RCW 43.03.050 and 43.03.060.

.. Legislative members shall be reimbursed for expenses incurred in the performance of their duties in accordance with RCW 44.04.120.

. A simple majority of the commission's membership constitutes a quorum for the purpose of conducting business. Legislative advisory members are not included in determining a quorum.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5356-S2.SL.pdf?cite=2019%20c%20395%20§%204[2019 c 395 § 4]; ]

== 43.114.040 - Executive director—Duties.
The executive director of the commission shall:

. Monitor state legislation affecting LGBTQ people;

. Work with state agencies to assess programs and policies that affect LGBTQ people;

. Coordinate with the minority commissions, women's commission, and human rights commission to address issues of mutual concern; and

. Work as a liaison between the public and private sector to eliminate barriers to economic and health equity for LGBTQ people.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5356-S2.SL.pdf?cite=2019%20c%20395%20§%205[2019 c 395 § 5]; ]

== 43.114.050 - Duties of commission—State agencies to give assistance.
. The commission shall have the following duties:

.. Actively recruit and maintain a list of names of qualified LGBTQ people to fill vacancies on various boards and commissions;

.. Provide a clearinghouse for information regarding both state and federal legislation as it relates to the purpose of this chapter;

.. Identify and define specific needs of LGBTQ:

... People of color;

... People with developmental disabilities;

... Seniors;

... People experiencing homelessness;

.. Economic and small business development; and

.. Veterans, their spouses, and dependents;

.. Consult with state agencies regarding the effect of agency policies, procedures, practices, laws, and administrative rules on the unique problems and needs of LGBTQ people. The commission shall also provide any data, input, and recommendations to state agencies on proposed agency rules and the development and implementation of comprehensive and coordinated policies, plans, and programs focusing on those problems and needs;

.. Provide resource and referral information to agencies and the public. The commission may gather data and disseminate information to the public in order to implement the purposes of this chapter;

.. Consult with nonprofit organizations;

.. Hold public hearings to gather input on issues related to the unique problems and needs of LGBTQ people;

.. Advocate for removal of barriers for LGBTQ people; and

.. Review best practices for discrimination and harassment policies and training and provide recommendations to state agencies as they update their discrimination and harassment policies. The commission shall also maintain a file of discrimination and harassment policies that meet high quality standards and make these files available for agency use.

. The commission must submit a report to the appropriate committees of the legislature and the governor every two years detailing the commission's activities. The report submitted must be in electronic format pursuant to RCW 43.01.036, and include, at minimum:

.. Recommendations for addressing the needs identified under subsection (1)(c) of this section;

.. Input received during public hearings and recommendations for addressing the problems and needs discussed at the public hearings; and

.. Recommendations regarding preserving the memory and contributions of LGBTQ members lost to HIV/AIDS in Washington state.

. State agencies must provide appropriate and reasonable assistance to the commission as needed, including providing notice of agency proposed rule making and gathering data and information, including but not limited to voluntary demographics, economic disparity studies, and other collectable data by state agencies, in order for the commission to carry out the purpose of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5356-S2.SL.pdf?cite=2019%20c%20395%20§%206[2019 c 395 § 6]; ]

== 43.114.060 - Powers of commission.
. The commission has the power to receive gifts, grants, and endowments from public or private sources that are made for the use or benefit of the commission and to expend the same or any income therefrom according to their terms and the purpose of this chapter. The commission's executive director shall make a report of such funds received from private sources to the office of financial management on a regular basis. Such funds received from private sources must not be applied to reduce or substitute for the commission's budget as appropriated by the legislature, but must be applied and expended toward projects and functions authorized by this chapter that were not funded by the legislature.

. In carrying out its duties, the commission may establish such relationships with public and private institutions, local governments, private industry, community organizations, and other segments of the general public as may be needed to promote equal opportunity for LGBTQ people in government, education, economic security, employment, and services.

. The commission may adopt rules and regulations pursuant to chapter 34.05 RCW as are necessary to implement the purpose of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5356-S2.SL.pdf?cite=2019%20c%20395%20§%207[2019 c 395 § 7]; ]

== 43.114.070 - LGBTQ pride month.
The legislature declares that:

. June of each year will be known as LGBTQ pride month;

. The fourth week in June is designated as a time for people of this state to celebrate the contributions to the state by LGBTQ people in the arts, sciences, commerce, and education; and

. Educational institutions, public entities, and private organizations are encouraged to designate time for appropriate activities in commemoration of the lives, history, achievements, and contributions of LGBTQ people.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5356-S2.SL.pdf?cite=2019%20c%20395%20§%208[2019 c 395 § 8]; ]

