= 43.185B - Washington housing policy act.
:toc:

== 43.185B.005 - Finding.
. The legislature finds that:

.. Housing is of vital statewide importance to the health, safety, and welfare of the residents of the state;

.. Reducing homelessness and moving individuals and families toward stable, affordable housing is of vital statewide importance;

.. Safe, affordable housing is an essential factor in stabilizing communities;

.. Residents must have a choice of housing opportunities within the community where they choose to live;

.. Housing markets are linked to a healthy economy and can contribute to the state's economy;

.. Land supply is a major contributor to the cost of housing;

.. Housing must be an integral component of any comprehensive community and economic development strategy;

.. State and local government must continue working cooperatively toward the enhancement of increased housing units by reviewing, updating, and removing conflicting regulatory language;

.. State and local government should work together in developing creative ways to reduce the shortage of housing;

.. The lack of a coordinated state housing policy inhibits the effective delivery of housing for some of the state's most vulnerable citizens and those with limited incomes; and

.. It is in the public interest to adopt a statement of housing policy objectives.

. The legislature declares that the purposes of the Washington housing policy act are to:

.. Provide policy direction to the public and private sectors in their attempt to meet the shelter needs of Washington residents;

.. Reevaluate housing and housing-related programs and policies in order to ensure proper coordination of those programs and policies to meet the housing needs of Washington residents;

.. Improve the delivery of state services and assistance to very low-income and low-income households and special needs populations;

.. Strengthen partnerships among all levels of government, and the public and private sectors, including for-profit and nonprofit organizations, in the production and operation of housing to targeted populations including low-income and moderate-income households;

.. Increase the supply of housing for persons with special needs;

.. Encourage collaborative planning with social service providers;

.. Encourage financial institutions to increase residential mortgage lending; and

.. Coordinate housing into comprehensive community and economic development strategies at the state and local level.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2163-S2.SL.pdf?cite=2005%20c%20484%20§%2022[2005 c 484 § 22]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5584.SL.pdf?cite=1993%20c%20478%20§%201[1993 c 478 § 1]; ]

== 43.185B.007 - Goal.
It is the goal of the state of Washington to coordinate, encourage, and direct, when necessary, the efforts of the public and private sectors of the state and to cooperate and participate, when necessary, in the attainment of a decent home in a healthy, safe environment for every resident of the state. The legislature declares that attainment of that goal is a state priority.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5584.SL.pdf?cite=1993%20c%20478%20§%202[1993 c 478 § 2]; ]

== 43.185B.009 - Objectives.
The objectives of the Washington housing policy act shall be to attain the state's goal of a decent home in a healthy, safe environment for every resident of the state by strengthening public and private institutions that are able to:

. Develop an adequate and affordable supply of housing for all economic segments of the population, including the destitute;

. Identify and reduce the causal factors preventing the state from reaching its goal;

. Assist very low-income and special needs households who cannot obtain affordable, safe, and adequate housing in the private market;

. Encourage and maintain homeownership opportunities;

. Reduce life-cycle housing costs while preserving public health and safety;

. Preserve the supply of existing affordable housing;

. Provide housing for special needs populations;

. Ensure fair and equal access to the housing market;

. Increase the availability of mortgage credit at low interest rates; and

. Coordinate and be consistent with the goals, objectives, and required housing element of the comprehensive plan in the state's growth management act in RCW 36.70A.070.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2163-S2.SL.pdf?cite=2005%20c%20484%20§%2023[2005 c 484 § 23]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5584.SL.pdf?cite=1993%20c%20478%20§%203[1993 c 478 § 3]; ]

== 43.185B.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Affordable housing" means residential housing that is rented or owned by a person or household whose monthly housing costs, including utilities other than telephone, do not exceed thirty percent of the household's monthly income.

. "Department" means the department of commerce.

. "Director" means the director of commerce.

. "Nonprofit organization" means any public or private nonprofit organization that: (a) Is organized under federal, state, or local laws; (b) has no part of its net earnings inuring to the benefit of any member, founder, contributor, or individual; and (c) has among its purposes significant activities related to the provision of decent housing that is affordable to very low-income, low-income, or moderate-income households and special needs populations.

. "Regulatory barriers to affordable housing" and "regulatory barriers" mean any public policies (including those embodied in statutes, ordinances, regulations, or administrative procedures or processes) required to be identified by the state or local government in connection with its strategy under section 105(b)(4) of the Cranston-Gonzalez national affordable housing act (42 U.S.C. 12701 et seq.).

. "Tenant-based organization" means a nonprofit organization whose governing body includes a majority of members who reside in the housing development and are considered low-income households.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2009%20c%20565%20§%2039[2009 c 565 § 39]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%20104[1995 c 399 § 104]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5584.SL.pdf?cite=1993%20c%20478%20§%204[1993 c 478 § 4]; ]

== 43.185B.020 - Affordable housing advisory board—Generally.
. The department shall establish the affordable housing advisory board to consist of twenty-two members.

.. The following nineteen members shall be appointed by the governor:

... Two representatives of the residential construction industry;

... Two representatives of the home mortgage lending profession;

... One representative of the real estate sales profession;

... One representative of the apartment management and operation industry;

.. One representative of the for-profit housing development industry;

.. One representative of for-profit rental housing owners;

.. One representative of the nonprofit housing development industry;

.. One representative of homeless shelter operators;

... One representative of lower-income persons;

.. One representative of special needs populations;

.. One representative of public housing authorities as created under chapter 35.82 RCW;

.. Two representatives of the Washington association of counties, one representative shall be from a county that is located east of the crest of the Cascade mountains;

.. Two representatives of the association of Washington cities, one representative shall be from a city that is located east of the crest of the Cascade mountains;

.. One representative to serve as chair of the affordable housing advisory board;

.. One representative at large.

.. The following three members shall serve as ex officio, nonvoting members:

... The director or the director's designee;

... The executive director of the Washington state housing finance commission or the executive director's designee; and

... The secretary of social and health services or the secretary's designee.

. [Empty]
.. The members of the affordable housing advisory board appointed by the governor shall be appointed for four-year terms, except that the chair shall be appointed to serve a two-year term. The terms of five of the initial appointees shall be for two years from the date of appointment and the terms of six of the initial appointees shall be for three years from the date of appointment. The governor shall designate the appointees who will serve the two-year and three-year terms. The members of the advisory board shall serve without compensation, but shall be reimbursed for travel expenses as provided in RCW 43.03.050 and 43.03.060.

.. The governor, when making appointments to the affordable housing advisory board, shall make appointments that reflect the cultural diversity of the state of Washington.

. The affordable housing advisory board shall serve as the department's principal advisory body on housing and housing-related issues, and replaces the department's existing boards and task forces on housing and housing-related issues.

. The affordable housing advisory board shall meet regularly and may appoint technical advisory committees, which may include members of the affordable housing advisory board, as needed to address specific issues and concerns.

. The department, in conjunction with the Washington state housing finance commission and the department of social and health services, shall supply such information and assistance as are deemed necessary for the advisory board to carry out its duties under this section.

. The department shall provide administrative and clerical assistance to the affordable housing advisory board.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5224.SL.pdf?cite=2003%20c%2040%20§%201[2003 c 40 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5584.SL.pdf?cite=1993%20c%20478%20§%205[1993 c 478 § 5]; ]

== 43.185B.030 - Affordable housing advisory board—Duties.
The affordable housing advisory board shall:

. Analyze those solutions and programs that could begin to address the state's need for housing that is affordable for all economic segments of the state, and special needs populations, including but not limited to programs or proposals which provide for:

.. Financing for the acquisition, rehabilitation, preservation, or construction of housing;

.. Use of publicly owned land and buildings as sites for affordable housing;

.. Coordination of state initiatives with federal initiatives and financing programs that are referenced in the Cranston-Gonzalez national affordable housing act (42 U.S.C. Sec. 12701 et seq.), as amended, and development of an approved housing strategy as required in the Cranston-Gonzalez national affordable housing act (42 U.S.C. Sec. 12701 et seq.), as amended;

.. Identification and removal, where appropriate and not detrimental to the public health and safety, or environment, of state and local regulatory barriers to the development and placement of affordable housing;

.. Stimulating public and private sector cooperation in the development of affordable housing; and

.. Development of solutions and programs affecting housing, including the equitable geographic distribution of housing for all economic segments, as the advisory board deems necessary;

. Consider both homeownership and rental housing as viable options for the provision of housing. The advisory board shall give consideration to various types of residential construction and innovative housing options, including but not limited to manufactured housing;

. Review, evaluate, and make recommendations regarding existing and proposed housing programs and initiatives including but not limited to tax policies, land use policies, and financing programs. The advisory board shall provide recommendations to the director, along with the department's response in the annual housing report to the legislature required in RCW 43.185B.040; and

. Prepare and submit to the director, by each December 1st, beginning December 1, 1993, a report detailing its findings and make specific program, legislative, and funding recommendations and any other recommendations it deems appropriate.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5584.SL.pdf?cite=1993%20c%20478%20§%206[1993 c 478 § 6]; ]

== 43.185B.040 - Housing advisory plan—Report to legislature.
. The department shall, in consultation with the affordable housing advisory board created in RCW 43.185B.020, prepare and from time to time amend a five-year housing advisory plan. The purpose of the plan is to document the need for affordable housing in the state and the extent to which that need is being met through public and private sector programs, to facilitate planning to meet the affordable housing needs of the state, and to enable the development of sound strategies and programs for affordable housing. The information in the five-year housing advisory plan must include:

.. An assessment of the state's housing market trends;

.. An assessment of the housing needs for all economic segments of the state and special needs populations;

.. An inventory of the supply and geographic distribution of affordable housing units made available through public and private sector programs;

.. A status report on the degree of progress made by the public and private sector toward meeting the housing needs of the state;

.. An identification of state and local regulatory barriers to affordable housing and proposed regulatory and administrative techniques designed to remove barriers to the development and placement of affordable housing; and

.. Specific recommendations, policies, or proposals for meeting the affordable housing needs of the state.

. [Empty]
.. The five-year housing advisory plan required under subsection (1) of this section must be submitted to the legislature on or before February 1, 1994, and subsequent plans must be submitted every five years thereafter.

.. Each February 1st, beginning February 1, 1995, the department shall submit an annual progress report, to the legislature, detailing the extent to which the state's affordable housing needs were met during the preceding year and recommendations for meeting those needs.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5584.SL.pdf?cite=1993%20c%20478%20§%2012[1993 c 478 § 12]; ]

== 43.185B.900 - Short title.
This chapter may be known and cited as the "Washington housing policy act."

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5584.SL.pdf?cite=1993%20c%20478%20§%2024[1993 c 478 § 24]; ]

