= 43.115 - State commission on Hispanic affairs.
:toc:

== 43.115.010 - Legislative declaration.
The legislature declares that the public policy of this state is to insure equal opportunity for all of its citizens. The legislature believes that it is the duty of the state to improve the well-being of Hispanics by enabling them to participate fully in all fields of endeavor and assisting them in obtaining governmental services. The legislature further finds that the development of public policy and the delivery of governmental services to meet the special needs of Hispanics can be improved by establishing a focal point in state government for the interests of Hispanics. Therefore the legislature deems it necessary to create a commission to carry out the purposes of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1948-S.SL.pdf?cite=1993%20c%20261%20§%201[1993 c 261 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c249.pdf?cite=1987%20c%20249%20§%201[1987 c 249 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c34.pdf?cite=1971%20ex.s.%20c%2034%20§%201[1971 ex.s. c 34 § 1]; ]

== 43.115.020 - Commission created.
There is created a Washington state commission on Hispanic affairs.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c249.pdf?cite=1987%20c%20249%20§%202[1987 c 249 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c34.pdf?cite=1971%20ex.s.%20c%2034%20§%202[1971 ex.s. c 34 § 2]; ]

== 43.115.030 - Membership—Terms—Vacancies—Travel expenses—Quorum.
. The commission shall consist of eleven members of Hispanic origin appointed by the governor. To the extent practicable, appointments to the commission shall be made to achieve a balanced representation based on the Hispanic population distribution within the state, geographic considerations, sex, age, and occupation. Members shall serve three-year terms. No member shall serve more than two full consecutive terms. Vacancies shall be filled in the same manner as the original appointments.

. Members shall receive reimbursement for travel expenses incurred in the performance of their duties in accordance with RCW 43.03.050 and 43.03.060 as now existing or hereafter amended.

. Six members of the commission shall constitute a quorum for the purpose of conducting business.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1948-S.SL.pdf?cite=1993%20c%20261%20§%202[1993 c 261 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c249.pdf?cite=1987%20c%20249%20§%203[1987 c 249 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c338.pdf?cite=1981%20c%20338%20§%2015[1981 c 338 § 15]; 1975-'76 2nd ex.s. c 34 § 130; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c34.pdf?cite=1971%20ex.s.%20c%2034%20§%203[1971 ex.s. c 34 § 3]; ]

== 43.115.040 - Officers and employees—Rules and regulations.
The commission shall have the following powers and duties:

. Elect one of its members to serve as chair;

. Adopt rules and regulations pursuant to chapter 34.05 RCW;

. Examine and define issues pertaining to the rights and needs of Hispanics, and make recommendations to the governor and state agencies for changes in programs and laws;

. Advise the governor and state agencies on the development and implementation of policies, plans, and programs that relate to the special needs of Hispanics;

. Advise the legislature on issues of concern to the Hispanic community;

. Establish relationships with state agencies, local governments, and private sector organizations that promote equal opportunity and benefits for Hispanics; and

. Receive gifts, grants, and endowments from public or private sources that are made for the use or benefit of the commission and expend, without appropriation, the same or any income from the gifts, grants, or endowments according to their terms.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%205170[2009 c 549 § 5170]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1948-S.SL.pdf?cite=1993%20c%20261%20§%203[1993 c 261 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c249.pdf?cite=1987%20c%20249%20§%204[1987 c 249 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c34.pdf?cite=1971%20ex.s.%20c%2034%20§%204[1971 ex.s. c 34 § 4]; ]

== 43.115.045 - Executive director.
. The commission shall be administered by an executive director, who shall be appointed by and serve at the pleasure of the governor. The governor shall base the appointment of the executive director on recommendations of the commission. The salary of the executive director shall be set by the governor.

. The executive director shall employ a staff, who shall be state employees pursuant to Title 41 RCW. The executive director shall prescribe the duties of the staff as may be necessary to implement the purposes of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1948-S.SL.pdf?cite=1993%20c%20261%20§%204[1993 c 261 § 4]; ]

== 43.115.060 - Relationships with local government and private industry.
In carrying out its duties the commission may establish such relationships with local governments and private industry as may be needed to promote equal opportunity for Hispanics in government, education and employment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c249.pdf?cite=1987%20c%20249%20§%206[1987 c 249 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c34.pdf?cite=1971%20ex.s.%20c%2034%20§%206[1971 ex.s. c 34 § 6]; ]

== 43.115.900 - Severability—1971 ex.s. c 34.
If any provision of this act, or its application to any person or circumstance is held invalid, the remainder of the act, or the application of the provision to other persons or circumstances is not affected.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c34.pdf?cite=1971%20ex.s.%20c%2034%20§%207[1971 ex.s. c 34 § 7]; ]

