= 43.143 - Ocean resources management act.
:toc:

== 43.143.005 - Legislative findings.
. Washington's coastal waters, seabed, and shorelines are among the most valuable and fragile of its natural resources.

. Ocean and marine-based industries and activities, such as fishing, aquaculture, tourism, and marine transportation have played a major role in the history of the state and will continue to be important in the future.

. Washington's coastal waters, seabed, and shorelines are faced with conflicting use demands. Some uses may pose unacceptable environmental or social risks at certain times.

. The state of Washington has primary jurisdiction over the management of coastal and ocean natural resources within three miles of its coastline. From three miles seaward to the boundary of the two hundred mile exclusive economic zone, the United States federal government has primary jurisdiction. Since protection, conservation, and development of the natural resources in the exclusive economic zone directly affect Washington's economy and environment, the state has an inherent interest in how these resources are managed.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1189.SL.pdf?cite=1997%20c%20152%20§%201[1997 c 152 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c2.pdf?cite=1989%201st%20ex.s.%20c%202%20§%208[1989 1st ex.s. c 2 § 8]; ]

== 43.143.010 - Legislative policy and intent—Moratorium on leases for oil and gas exploration, development, or production—Appeals from regulation of recreational uses—Participation in federal ocean and marine resource decisions.
. The purpose of this chapter is to articulate policies and establish guidelines for the exercise of state and local management authority over Washington's coastal waters, seabed, and shorelines.

. There shall be no leasing of Washington's tidal or submerged lands extending from mean high tide seaward three miles along the Washington coast from Cape Flattery south to Cape Disappointment, nor in Grays Harbor, Willapa Bay, and the Columbia river downstream from the Longview bridge, for purposes of oil or gas exploration, development, or production.

. When conflicts arise among uses and activities, priority shall be given to resource uses and activities that will not adversely impact renewable resources over uses which are likely to have an adverse impact on renewable resources.

. It is the policy of the state of Washington to actively encourage the conservation of liquid fossil fuels, and to explore available methods of encouraging such conservation.

. It is not currently the intent of the legislature to include recreational uses or currently existing commercial uses involving fishing or other renewable marine or ocean resources within the uses and activities which must meet the planning and review criteria set forth in RCW 43.143.030. It is not the intent of the legislature, however, to permanently exclude these uses from the requirements of RCW 43.143.030. If information becomes available which indicates that such uses should reasonably be covered by the requirements of RCW 43.143.030, the permitting government or agency may require compliance with those requirements, and appeals of that decision shall be handled through the established appeals procedure for that permit or approval.

. The state shall participate in federal ocean and marine resource decisions to the fullest extent possible to ensure that the decisions are consistent with the state's policy concerning the use of those resources.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1189.SL.pdf?cite=1997%20c%20152%20§%202[1997 c 152 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5544.SL.pdf?cite=1995%20c%20339%20§%201[1995 c 339 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c2.pdf?cite=1989%201st%20ex.s.%20c%202%20§%209[1989 1st ex.s. c 2 § 9]; ]

== 43.143.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter:

. "Coastal counties" means Clallam, Jefferson, Grays Harbor, and Pacific counties.

. "Coastal waters" means the waters of the Pacific Ocean seaward from Cape Flattery south to Cape Disappointment, from mean high tide seaward two hundred miles.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c2.pdf?cite=1989%201st%20ex.s.%20c%202%20§%2010[1989 1st ex.s. c 2 § 10]; ]

== 43.143.030 - Planning and project review criteria.
. When the state of Washington and local governments develop plans for the management, conservation, use, or development of natural resources in Washington's coastal waters, the policies in RCW 43.143.010 shall guide the decision-making process.

. Uses or activities that require federal, state, or local government permits or other approvals and that will adversely impact renewable resources, marine life, fishing, aquaculture, recreation, navigation, air or water quality, or other existing ocean or coastal uses, may be permitted only if the criteria below are met or exceeded:

.. There is a demonstrated significant local, state, or national need for the proposed use or activity;

.. There is no reasonable alternative to meet the public need for the proposed use or activity;

.. There will be no likely long-term significant adverse impacts to coastal or marine resources or uses;

.. All reasonable steps are taken to avoid and minimize adverse environmental impacts, with special protection provided for the marine life and resources of the Columbia river, Willapa Bay and Grays Harbor estuaries, and Olympic national park;

.. All reasonable steps are taken to avoid and minimize adverse social and economic impacts, including impacts on aquaculture, recreation, tourism, navigation, air quality, and recreational, commercial, and tribal fishing;

.. Compensation is provided to mitigate adverse impacts to coastal resources or uses;

.. Plans and sufficient performance bonding are provided to ensure that the site will be rehabilitated after the use or activity is completed; and

.. The use or activity complies with all applicable local, state, and federal laws and regulations.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c2.pdf?cite=1989%201st%20ex.s.%20c%202%20§%2011[1989 1st ex.s. c 2 § 11]; ]

== 43.143.050 - Washington coastal marine advisory council.
. The Washington coastal marine advisory council is established in the executive office of the governor to fulfill the duties outlined in RCW 43.143.060.

. [Empty]
.. Voting members of the Washington coastal marine advisory council shall be appointed by the governor or the governor's designee. The council consists of the following voting members:

... The governor or the governor's designee;

... The director or commissioner, or the director's or commissioner's designee, of the following agencies:

(A) The department of ecology;

(B) The department of natural resources;

(C) The department of fish and wildlife;

(D) The state parks and recreation commission;

(E) The department of commerce; and

(F) Washington sea grant;

... The following members of the Washington coastal marine advisory council established by the department of ecology and as existing on January 15, 2013:

(A) One citizen from a coastal community;

(B) Two persons representing coastal commercial fishing;

(C) One representative from a coastal conservation group;

(D) One representative from a coastal economic development group;

(E) One representative from an educational institution;

(F) Two representatives from energy industries or organizations, one of which must be from the coast;

(G) One person representing coastal recreation;

(H) One person representing coastal recreational fishing;

(I) One person representing coastal shellfish aquaculture;

(J) One representative from the coastal shipping industry;

(K) One representative from a science organization;

(L) One representative from the coastal Washington sustainable salmon partnership;

(M) One representative from a coastal port; and

(N) One representative from each outer coast marine resources committee, to be selected by the marine resources committee.

.. The Washington coastal marine advisory council shall adopt bylaws and operating procedures that may be modified from time to time by the council.

. The Washington coastal marine advisory council may invite state, tribal, local governments, federal agencies, scientific experts, and others with responsibility for the study and management of coastal and ocean resources or regulation of coastal and ocean activities to designate a liaison to the council to attend council meetings, respond to council requests for technical and policy information, perform collaborative research, and review any draft materials prepared by the council. The council may also invite representatives from other coastal states or Canadian provinces to participate, when appropriate, as nonvoting members.

. The chair of the Washington coastal marine advisory council must be nominated and elected by a majority of councilmembers. The term of the chair is one year, and the position is eligible for reelection. The agenda for each meeting must be developed as a collaborative process by councilmembers.

. The term of office of each member appointed by the governor is four years. Members are eligible for reappointment.

. The Washington coastal marine advisory council shall utilize a consensus approach to decision making. The council may put a decision to a vote among councilmembers, in the event that consensus cannot be reached. The council must include in its bylaws guidelines describing how consensus works and when a lack of consensus among councilmembers will trigger a vote.

. Consistent with available resources, the Washington coastal marine advisory council may hire a neutral convener to assist in the performance of the council's duties, including but not limited to the dissemination of information to all parties, facilitating selected tasks as requested by the councilmembers, and facilitation of setting meeting agendas.

. The department of ecology shall provide administrative and primary staff support for the Washington coastal marine advisory council.

. The Washington coastal marine advisory council must meet at least twice each year or as needed.

. A majority of the members of the Washington coastal marine advisory council constitutes a quorum for the transaction of business.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5603.SL.pdf?cite=2013%20c%20318%20§%201[2013 c 318 § 1]; ]

== 43.143.060 - Washington coastal marine advisory council—Duties.
. The duties of the Washington coastal marine advisory council established in RCW 43.143.050 are to:

.. Serve as a forum for communication concerning coastal waters issues, including issues related to: Resource management; shellfish aquaculture; marine and coastal hazards; ocean energy; open ocean aquaculture; coastal waters research; education; and other coastal marine-related issues.

.. Serve as a point of contact for, and collaborate with, the federal government, regional entities, and other state governments regarding coastal waters issues.

.. Provide a forum to discuss coastal waters resource policy, planning, and management issues; provide either recommendations or modifications, or both, of principles, and, when appropriate, mediate disagreements.

.. Serve as an interagency resource to respond to issues facing coastal communities and coastal waters resources in a collaborative manner.

.. Identify and pursue public and private funding opportunities for the programs and activities of the council and for relevant programs and activities of member entities.

.. Provide recommendations to the governor, the legislature, and state and local agencies on specific coastal waters resource management issues, including:

... Annual recommendations regarding coastal marine spatial planning expenditures and projects, including uses of the marine resources stewardship trust account created in RCW 43.372.070;

... Principles and standards required for emerging new coastal uses;

... Data gaps and opportunities for scientific research addressing coastal waters resource management issues;

... Implementation of Washington's ocean action plan 2006;

.. Development and implementation of coast-wide goals and strategies, including marine spatial planning; and

.. A coastal perspective regarding cross-boundary coastal issues.

. In making recommendations under this section, the Washington coastal marine advisory council shall consider:

.. The principles and policies articulated in Washington's ocean action plan; and

.. The protection and preservation of existing sustainable uses for current and future generations, including economic stakeholders reliant on marine waters to stabilize the vitality of the coastal economy.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5603.SL.pdf?cite=2013%20c%20318%20§%202[2013 c 318 § 2]; ]

== 43.143.901 - Short title.
Sections 8 through 12 of this act shall constitute a new chapter in Title 43 RCW and may be known and cited as the ocean resources management act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c2.pdf?cite=1989%201st%20ex.s.%20c%202%20§%2019[1989 1st ex.s. c 2 § 19]; ]

