= 43.119 - Women's commission.
:toc:

== 43.119.005 - Legislative declaration.
The legislature finds that it is important to achieve equal opportunity for all of its citizens. The legislature finds that women face unique problems and needs. For economic, social, and historical reasons, a disproportionate number of women find themselves disadvantaged or isolated from the benefits of equal opportunity. It is the purpose of this chapter to improve the well-being of women, by enabling them to participate fully in all fields of endeavor, assisting them in obtaining governmental services, and promoting equal compensation and fairness in employment for women. The legislature also believes that addressing women's issues and improving the well-being of women will have a positive impact on larger societal issues. The legislature further finds that the development of public policy and the efficient delivery of governmental services to meet the needs of women can be improved by establishing a focal point in state government for the interests of women. Therefore, the legislature deems it necessary to establish in statute the Washington state women's commission to further these purposes. The commission shall address issues relevant to the problems and needs of women, such as domestic violence, child care, child support, sexual discrimination, sexual harassment, equal compensation and job pathways opportunities in employment, and the specific needs of women of color.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2759.SL.pdf?cite=2018%20c%2098%20§%201[2018 c 98 § 1]; ]

== 43.119.010 - Commission established.
The Washington state women's commission is established in the office of the governor. The commission shall be administered by an executive director, who shall be appointed by, and serve at the pleasure of, the governor. The governor shall set the salary of the executive director. The executive director shall employ the staff of the commission.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2759.SL.pdf?cite=2018%20c%2098%20§%202[2018 c 98 § 2]; ]

== 43.119.020 - Membership—Terms—Vacancies—Expenses—Quorum.
. The Washington state women's commission shall consist of nine members appointed by the governor with the advice and consent of the senate.

. The governor shall consider nominations for membership based upon maintaining a balanced and diverse distribution of ethnic, geographic, gender, sexual orientation, age, socioeconomic status, and occupational representation, where practicable.

. All commission members shall serve at the pleasure of the governor, but in no case may any member serve more than three years without formal reappointment by the governor. All legislative advisory members shall serve for a two-year term and the position of any legislative advisory member shall be deemed vacated whenever such member ceases to be a member of the house from which the member was appointed. Of the persons initially appointed by the governor to the commission, three shall be appointed to serve one year, three to serve two years, and three to serve three years. Upon expiration of such terms, subsequent appointments shall be for three years. Any vacancies occurring in the membership of the commission shall be filled for the remainder of the unexpired term in the same manner as the original appointments.

. Two members of the senate, one from each of the two major political parties, appointed by the president of the senate, and two members of the house of representatives, one from each of the two major political parties, appointed by the speaker of the house of representatives, shall serve as advisory members.

. [Empty]
.. Nonlegislative members shall be reimbursed for expenses incurred in the performance of their duties in accordance with RCW 43.03.050 and 43.03.060.

.. Legislative members shall be reimbursed for expenses incurred in the performance of their duties in accordance with RCW 44.04.120.

. A simple majority of the commission's membership constitutes a quorum for the purpose of conducting business.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2759.SL.pdf?cite=2018%20c%2098%20§%203[2018 c 98 § 3]; ]

== 43.119.030 - Executive director—Duties.
The [executive] director of the Washington state women's commission shall:

. Monitor state legislation and advocate for legislation affecting women;

. Work with state agencies to assess programs and policies that affect women;

. Coordinate with the minority commissions and human rights commission to address issues of mutual concern; and

. Work as a liaison between the public and private sector to eliminate barriers to women's economic equity.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2759.SL.pdf?cite=2018%20c%2098%20§%204[2018 c 98 § 4]; ]

== 43.119.040 - Duties of commission—State agencies to give assistance.
. The Washington state women's commission shall have the following duties:

.. Actively recruit and maintain a list of names of qualified women to fill vacancies on various boards and commissions;

.. Provide a clearinghouse for information regarding both state and federal legislation as it relates to the purpose of this chapter;

.. Identify and define specific needs of women of color and provide recommendations for addressing those needs in the biennial report to the legislature and governor under (j) of this subsection;

.. Consult with state agencies regarding the effect of agency policies, procedures, practices, laws, and administrative rules on the unique problems and needs of women. The commission shall also advise such state agencies on the development and implementation of comprehensive and coordinated policies, plans, and programs focusing on those problems and needs;

.. Provide resource and referral information to agencies and the public. The commission may gather data and disseminate information to the public in order to implement the purposes of this chapter;

.. Hold public hearings to gather input on issues related to the unique problems and needs of women. The commission must include in the biennial report submitted under (j) of this subsection the input received and recommendations for addressing the problems and needs discussed at the public hearings;

.. Advocate for removal of legal and social barriers for women;

.. Review best practices for sexual harassment policies and training and provide recommendations to state agencies as they update their sexual harassment policies. The commission shall also maintain a file of sexual harassment policies that meet high quality standards and make these files available for agency use;

.. Review and make recommendations to the legislature on strategies to increase the number of women serving on for-profit corporate boards with gross income of five million dollars or more; and

.. Submit a report to the appropriate committees of the legislature and the governor every two years detailing the commission's activities. The report submitted must be in electronic format pursuant to RCW 43.01.036.

. State agencies must provide appropriate and reasonable assistance to the commission as needed, including gathering data and information, in order for the commission to carry out the purpose of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2759.SL.pdf?cite=2018%20c%2098%20§%205[2018 c 98 § 5]; ]

== 43.119.050 - Powers of commission.
The Washington state women's commission shall have the following powers:

. Receive gifts, grants, and endowments from public or private sources that are made for the use or benefit of the commission and to expend the same or any income therefrom according to their terms and the purpose of this chapter. The commission's executive director shall make a report of such funds received from private sources to the office of financial management on a regular basis. Such funds received from private sources shall not be applied to reduce or substitute for the commission's budget as appropriated by the legislature, but shall be applied and expended toward projects and functions authorized by this chapter that were not funded by the legislature.

. In carrying out its duties, the commission may establish such relationships with public and private institutions, local governments, private industry, community organizations, and other segments of the general public as may be needed to promote equal opportunity for women in government, education, economic security, employment, and services.

. The commission may adopt rules and regulations pursuant to chapter 34.05 RCW as shall be necessary to implement the purpose of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2759.SL.pdf?cite=2018%20c%2098%20§%206[2018 c 98 § 6]; ]

== 43.119.060 - Interagency committee of state employed women—Staffing support.
The Washington state women's commission must provide staffing support to the interagency committee of state employed women, a volunteer organization that aims to better the lives of state employees by advising the governor and agencies on policies that affect state-employed women.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2759.SL.pdf?cite=2018%20c%2098%20§%207[2018 c 98 § 7]; ]

== 43.119.800 - Nineteenth Amendment centennial commemoration. (Expires July 1, 2021.)
. The women's commission must, subject to the availability of amounts appropriated for this specific purpose, work with the Washington women's history consortium to:

.. Provide leadership for statewide commemoration from 2018 through 2020 of the centennial pertaining to the passage by congress of the Nineteenth Amendment and its subsequent ratification by three-fourths of the state legislatures in August 1920;

.. Immediately begin preparations for this statewide commemoration, to include but not be limited to:

... Consulting with a wide variety of organizations, institutions, public agencies, educational agencies and institutions, tourism organizations, and the general public about the content and conduct of this statewide commemoration;

... Developing and encouraging others to develop a broad range of widely available educational opportunities for Washingtonians generally, students, and visitors, including significant online educational resources, to:

(A) Learn about the importance of voting in the context of women gaining the right to vote;

(B) Consider the subsequent long-term impacts of women gaining the right to vote;

(C) Learn about the active leadership role of Washingtonians in achieving the nationwide right to vote for women;

(D) Honor the countless participants in the women's suffrage movement; and

(E) Inspire future generations to treasure their right to vote;

... Planning, coordinating, and publicizing events and informational materials for Washingtonians and visitors throughout the state commemorating this centennial;

.. Create and distribute a portfolio of public humanities programs, and encourage others to do so, to engage Washingtonians and visitors with important aspects of the women's right to vote movement;

.. Encourage private organizations, schools, institutions of higher education, public agencies, and local governments to organize and participate in activities commemorating the centennial of the Nineteenth Amendment to the United States Constitution;

.. Coordinate with the regional and national organizations and agencies with respect to their commemorative work;

.. Coordinate with the national collaborative for women's history sites by contributing a Washington component to the development of a nationwide votes for women trail; and

.. Administer a grant program for public agencies, educational institutions, and organizations exempt from taxation under Title 26 U.S.C. Sec. 501(c)(3) of the federal internal revenue code to assist with their commemoration activities.

. The women's commission has the following powers and may exercise them as necessary to carry out its duties under subsection (1) of this section:

.. Appoint task forces and advisory committees;

.. Work with staff appointed by the Washington state historical society; and

.. Enter into agreements or contracts.

. Legislative members serving on any task force or advisory committee created under this section must be reimbursed for travel expenses in accordance with RCW 44.04.120.

. Representatives of state and local governments serving on any task force or advisory committee created under this section must be reimbursed pursuant to the reimbursement policies of their respective entity.

. Nonlegislative members serving on any task force or advisory committee created under this section are not entitled to be reimbursed for travel expenses if they are elected officials or are participating on behalf of an employer, governmental entity, or other organization. Any reimbursement for other nonlegislative members is subject to chapter 43.03 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2759.SL.pdf?cite=2018%20c%2098%20§%209[2018 c 98 § 9]; ]

