= 43.133 - Washington sunrise act.
:toc:

== 43.133.010 - Legislative declaration.
Because of the proliferation of boards and special purpose districts, the legislature recognizes the necessity of developing a uniform and coordinated procedure for determining the need for these new units of government.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c342.pdf?cite=1987%20c%20342%20§%201[1987 c 342 § 1]; ]

== 43.133.020 - Definitions.
. For purposes of this chapter, "special purpose district" means any unit of local government other than a city, town, county, or school district.

. For purposes of this chapter, "board" means a board, commission, council, committee or task force.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c342.pdf?cite=1987%20c%20342%20§%202[1987 c 342 § 2]; ]

== 43.133.030 - Sunrise notes—Procedure.
The office of financial management and the *department of community, trade, and economic development shall, in cooperation with appropriate legislative committees and legislative staff, establish a procedure for the provision of sunrise notes on the expected impact of bills and resolutions that authorize the creation of new boards and new types of special purpose districts.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%2081[1995 c 399 § 81]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c342.pdf?cite=1987%20c%20342%20§%203[1987 c 342 § 3]; ]

== 43.133.040 - Sunrise notes—Contents.
Sunrise notes shall include:

. The purpose and expected impact of the new board or special purpose district;

. The powers and duties of the new board or special purpose district;

. The direct or potential duplication of the powers and duties of existing boards or special purpose districts; and

. Other information relevant to the need for the new board or special purpose district.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c342.pdf?cite=1987%20c%20342%20§%204[1987 c 342 § 4]; ]

== 43.133.050 - Sunrise notes—Preparation.
. The office of financial management shall prepare sunrise notes for legislation concerning the creation of new boards. The *department of community, trade, and economic development shall prepare sunrise notes for legislation creating new types of special purpose districts.

. A sunrise note shall be prepared for all executive and agency request legislation that creates a board or special purpose district.

. The office of financial management or the *department of community, trade, and economic development shall also provide a sunrise note at the request of any committee of the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%2082[1995 c 399 § 82]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c342.pdf?cite=1987%20c%20342%20§%205[1987 c 342 § 5]; ]

== 43.133.060 - Sunrise notes—Filing.
Sunrise notes shall be filed with:

. The committee to which the bill or resolution was referred upon introduction in the house of origin;

. The senate committee on ways and means or its successor;

. The house of representatives committee on ways and means or its successor;

. The senate governmental operations committee or its successor; and

. The house of representatives state government committee or its successor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c342.pdf?cite=1987%20c%20342%20§%206[1987 c 342 § 6]; ]

== 43.133.070 - Forwarding of notification and sunrise note to committees when standing committee votes out bill creating board or special purpose district.
Legislative standing committees shall forward notification and the sunrise note, if available, to the senate or house of representatives ways and means committee and the senate governmental operations committee or the house of representatives state government committee whenever a bill providing for the creation of a new board or special purpose district is voted out of the standing committee.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c342.pdf?cite=1987%20c%20342%20§%207[1987 c 342 § 7]; ]

== 43.133.080 - Effect of chapter on validity of legislative action.
Nothing in this chapter prevents either house of the legislature from acting on any bill or resolution before it as otherwise provided by the state Constitution, by law, and by the rules and joint rules of the senate and house of representatives, nor shall the lack of any sunrise note as provided in this chapter or any error in the accuracy thereof affect the validity of any measure otherwise duly passed by the legislature.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c342.pdf?cite=1987%20c%20342%20§%208[1987 c 342 § 8]; ]

== 43.133.900 - Short title.
This chapter shall be known as the Washington sunrise act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c342.pdf?cite=1987%20c%20342%20§%209[1987 c 342 § 9]; ]

