= 43.270 - Community mobilization against substance abuse.
:toc:

== 43.270.010 - Intent.
The legislature recognizes that statewide efforts aimed at reducing the incidence of substance abuse, including alcohol, tobacco, or other drug abuse, or violence must be increased. The legislature further recognizes that the most effective strategy for reducing the impact of alcohol, tobacco, other drug abuse, and violence is through the collaborative efforts of educators, law enforcement, local government officials, local treatment providers, and concerned community and citizens' groups.

The legislature intends to support the development and activities of community mobilization strategies against alcohol, tobacco, or other drug abuse, and violence, through the following efforts:

. Providing funding support for prevention, treatment, and enforcement activities identified by communities that have brought together education, treatment, local government, law enforcement, and other key elements of the community;

. Providing technical assistance and support to help communities develop and carry out effective activities; and

. Providing communities with opportunities to share suggestions for state program operations and budget priorities.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5367.SL.pdf?cite=2001%20c%2048%20§%201[2001 c 48 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20315[1989 c 271 § 315]; ]

== 43.270.020 - Grant program—Application—Activities funded.
. There is established in the *department of community, trade, and economic development a grant program to provide incentive for and support for communities to develop targeted and coordinated strategies to reduce the incidence and impact of alcohol, tobacco, or other drug abuse, or violence.

. The *department of community, trade, and economic development shall make awards, subject to funds appropriated by the legislature, under the following terms:

.. Starting July 1, 2001, funds will be available to countywide programs through a formula developed by the *department of community, trade, and economic development in consultation with program contractors, which will take into consideration county population size.

.. In order to be eligible for consideration, applicants must demonstrate, at a minimum:

... That the community has developed and is committed to carrying out a coordinated strategy of prevention, treatment, and law enforcement activities;

... That the community has considered research-based theory when developing its strategy;

... That proposals submitted for funding are based on a local assessment of need and address specific objectives contained in a coordinated strategy of prevention, treatment, and law enforcement against alcohol, tobacco, or other drug abuse, or violence;

... Evidence of active participation in preparation of the proposal and specific commitments to implementing the community-wide agenda by leadership from education, law enforcement, local government, tribal government, and treatment entities in the community, and the opportunity for meaningful involvement from others such as neighborhood and citizen groups, businesses, human service, health and job training organizations, and other key elements of the community, particularly those whose responsibilities in law enforcement, treatment, prevention, education, or other community efforts provide direct, ongoing contact with substance abusers or those who exhibit violent behavior, or those at risk for alcohol, tobacco, or other drug abuse, or violent behavior;

.. Evidence of additional local resources committed to the applicant's strategy totaling at least twenty-five percent of funds awarded under this section. These resources may consist of public or private funds, donated goods or services, and other measurable commitments, including in-kind contributions such as volunteer services, materials, supplies, physical facilities, or a combination thereof; and

.. That the funds applied for, if received, will not be used to replace funding for existing activities.

.. At a minimum, grant applications must include the following:

... A definition of geographic area;

... A needs assessment describing the extent and impact of alcohol, tobacco, or other drug abuse, and violence in the community, including an explanation of those who are most severely impacted and those most at risk of substance abuse or violent behavior;

... An explanation of the community-wide strategy for prevention, treatment, and law enforcement activities related to alcohol, tobacco, or other drug abuse, or violence, with particular attention to those who are most severely impacted and/or those most at risk of alcohol, tobacco, or other drug abuse, or violent behavior;

... An explanation of who was involved in development of the strategy and what specific commitments have been made to carry it out;

.. Identification of existing prevention, education, treatment, and law enforcement resources committed by the applicant, including financial and other support, and an explanation of how the applicant's strategy involves and builds on the efforts of existing organizations or coalitions that have been carrying out community efforts against alcohol, tobacco, or other drug abuse, or violence;

.. Identification of activities that address specific objectives in the strategy for which additional resources are needed;

.. Identification of additional local resources, including public or private funds, donated goods or services, and other measurable commitments, that have been committed to the activities identified in (c)(vi) of this subsection;

.. Identification of activities that address specific objectives in the strategy for which funding is requested;

... For each activity for which funding is requested, an explanation in sufficient detail to demonstrate:

(A) Feasibility through deliberative design, specific objectives, and a realistic plan for implementation;

(B) A rationale for how this activity will achieve measurable results and how it will be evaluated;

(C) That funds requested are necessary and appropriate to effectively carry out the activity; and

.. Identification of a contracting agent meeting state requirements for each activity proposed for funding.

Each contracting agent must execute a written agreement with its local community mobilization advisory board that reflects the duties and powers of each party.

. Activities that may be funded through this grant program include those that:

.. Prevent alcohol, tobacco, or other drug abuse, or violence through educational efforts, development of positive alternatives, intervention with high-risk groups, and other prevention strategies;

.. Support effective treatment by increasing access to and availability of treatment opportunities, particularly for underserved or highly impacted populations, developing aftercare and support mechanisms, and other strategies to increase the availability and effectiveness of treatment;

.. Provide meaningful consequences for participation in illegal activity and promote safe and healthy communities through support of law enforcement strategies;

.. Create or build on efforts by existing community programs, coordinate their efforts, and develop cooperative efforts or other initiatives to make most effective use of resources to carry out the community's strategy against alcohol, tobacco, or other drug abuse, or violence; and

.. Other activities that demonstrate both feasibility and a rationale for how the activity will achieve measurable results in the strategy against alcohol, tobacco, or other drug abuse, or violence.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5367.SL.pdf?cite=2001%20c%2048%20§%202[2001 c 48 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20316[1989 c 271 § 316]; ]

== 43.270.040 - Coordinated strategies.
This grant program will be available to communities of any geographic size but will encourage and reward communities which develop coordinated or complimentary strategies within geographic areas such as county areas or groups of county areas which correspond to units of government with significant responsibilities in the area of substance abuse, existing coalitions, or other entities important to the success of a community's strategy against substance abuse.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20318[1989 c 271 § 318]; ]

== 43.270.070 - Community suggestions.
The *department of community, trade, and economic development shall ask communities for suggestions on state practices, policies, and priorities that would help communities implement their strategies against alcohol, tobacco, or other drug abuse, or violence. The *department of community, trade, and economic development shall review and respond to those suggestions making necessary changes where feasible, making recommendations to the legislature where appropriate, and providing an explanation as to why suggested changes cannot be accomplished, if the suggestions cannot be acted upon.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5367.SL.pdf?cite=2001%20c%2048%20§%203[2001 c 48 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20321[1989 c 271 § 321]; ]

== 43.270.080 - Gifts, grants, and endowments.
The *department of community, trade, and economic development may receive such gifts, grants, and endowments from public or private sources as may be made from time to time, in trust or otherwise, for the use and benefit of the purposes of RCW 43.270.010 through 43.270.080 and expend the same or any income therefrom according to the terms of the gifts, grants, or endowments.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5367.SL.pdf?cite=2001%20c%2048%20§%204[2001 c 48 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20322[1989 c 271 § 322]; ]

