= 43.280 - Community treatment services for victims of sexual assault.
:toc:

== 43.280.010 - Intent.
The legislature recognizes the need to increase the services available to the victims of sexual assault. The legislature also recognizes that these services are most effectively planned and provided at the local level through the combined efforts of concerned community and citizens groups, treatment providers, and local government officials. The legislature further recognizes that adequate services for victims is not only a matter of justice for the victim, but also a method by which additional abuse can be prevented.

The legislature intends to enhance the community-based services available to the victims of sexual assault by:

. Providing consolidated funding support for local programs which provide services to victims of sexual assault, as defined in RCW 70.125.030;

. Providing technical assistance and support to help communities plan for and provide victim services;

. Providing sexual assault services with a victim-focused mission, and consistent standards, policies, and granting and reporting requirements; and

. Providing communities and local victim service providers with opportunities to share information about successful prevention and treatment programs.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6100-S.SL.pdf?cite=2012%20c%2029%20§%201[2012 c 29 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2579-S.SL.pdf?cite=1996%20c%20123%20§%202[1996 c 123 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%201201[1990 c 3 § 1201]; ]

== 43.280.011 - Intent—Approval of committee recommendations.
The Washington state sexual assault services advisory committee issued a report to the department of commerce and the department of social and health services in June of 1995. The committee made several recommendations to improve the delivery of services to victims of sexual assault: (1) Consolidate the administration and funding of sexual assault and abuse services in one agency instead of splitting those functions between the department of social and health services and the department of commerce; (2) adopt a funding allocation plan to pool all funds for sexual assault services and to distribute them across the state to ensure the delivery of core and specialized services; (3) establish service, data collection, and management standards and outcome measurements for recipients of grants; and (4) create a data collection system to gather pertinent data concerning the delivery of sexual assault services to victims.

The legislature approves the recommendations of the advisory committee and consolidates the functions and funding for sexual assault services in the department of commerce to implement the advisory committee's recommendations.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6100-S.SL.pdf?cite=2012%20c%2029%20§%202[2012 c 29 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2579-S.SL.pdf?cite=1996%20c%20123%20§%201[1996 c 123 § 1]; ]

== 43.280.020 - Grant program—Funding.
. The department of commerce is authorized to distribute funds that have been allocated to the grant program that it administers for serving victims of sexual assault.

. Activities that can be funded through this grant program are limited to those that:

.. Provide effective services to victims of sexual assault;

.. Increase access to and availability of services for victims of sexual assault, particularly if from underserved populations; and

.. Create or build on efforts by existing community programs, coordinate those efforts, or develop cooperative efforts or other initiatives to make the most effective use of resources to provide treatment services to these victims.

. Funding for core, specialized, and underserved populations services, as defined in RCW 70.125.030, must be distributed through a funding formula to those applicants that emphasize providing stable, victim-centered sexual assault services and possess the qualifications to provide those services.

. The department of commerce shall ensure that grant recipients assist victims to utilize private insurance and crime victims' compensation benefits first before grant funds are used for therapy services.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6100-S.SL.pdf?cite=2012%20c%2029%20§%203[2012 c 29 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2579-S.SL.pdf?cite=1996%20c%20123%20§%203[1996 c 123 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%20113[1995 c 399 § 113]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%201203[1990 c 3 § 1203]; ]

== 43.280.040 - Organizations eligible.
Local governments, nonprofit community groups, and nonprofit treatment providers including organizations which provide services, such as emergency housing, counseling, and crisis intervention shall, among others, be eligible for grants under the program established in RCW 43.280.020.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%201205[1990 c 3 § 1205]; ]

== 43.280.050 - Applications—Minimum requirements.
. At a minimum, grant applications for specialized and underserved services must include the following:

.. The geographic area from which the victims to be served are expected to come;

.. A description of the extent and effect of the needs of these victims within the relevant geographic area;

.. A proposed budget and an explanation of how the funds will be used, their relationship to existing services available within the community, and the need that they will fulfill;

.. An explanation of what community organizations were involved in the community coordination that resulted in the development of the proposal; and

.. Documentation of the applicant's capacity to provide specialized services and services for underserved populations, as defined in this chapter, and a description of how the applicant intends to comply with service standards and data collection as established by the department.

. At a minimum, grant applications for core services must include the following:

.. The geographic area from which the victims to be served are expected to come;

.. Assurance of the applicant's compliance with service standards, data collection, and management standards established by the department; and

.. Documentation of the applicant's capacity to provide core services, as defined in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6100-S.SL.pdf?cite=2012%20c%2029%20§%204[2012 c 29 § 4]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2579-S.SL.pdf?cite=1996%20c%20123%20§%204[1996 c 123 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%201206[1990 c 3 § 1206]; ]

== 43.280.060 - Awarding of grants.
. Subject to funds appropriated by the legislature, the department of commerce shall make awards under the grant program established by RCW 43.280.020.

. Activities funded under this section may be considered for funding in future years, but shall be considered under the same terms and criteria as new activities. Funding under this chapter shall not constitute an obligation by the state of Washington to provide ongoing funding.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6100-S.SL.pdf?cite=2012%20c%2029%20§%205[2012 c 29 § 5]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2579-S.SL.pdf?cite=1996%20c%20123%20§%205[1996 c 123 § 5]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%20114[1995 c 399 § 114]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%201207[1990 c 3 § 1207]; ]

== 43.280.070 - Gifts, grants, and endowments.
The department of commerce may receive such gifts, grants, and endowments from public or private sources as may be made from time to time, in trust or otherwise, for the use and benefit of the purposes of this chapter and expend the same or any income therefrom according to the terms of the gifts, grants, or endowments.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6100-S.SL.pdf?cite=2012%20c%2029%20§%206[2012 c 29 § 6]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%20115[1995 c 399 § 115]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c3.pdf?cite=1990%20c%203%20§%201208[1990 c 3 § 1208]; ]

== 43.280.080 - Office of crime victims advocacy.
The office of crime victims advocacy is established in the department of commerce. The office shall assist communities in planning and implementing services for crime victims, advocate on behalf of crime victims in obtaining needed services and resources, and advise local and state governments on practices, policies, and priorities that impact crime victims. In addition, the office shall administer grant programs for services to victims of crime and prevention activities as authorized by state or federal legislation, budget, or executive order. The department shall seek, receive, and make use of any funds which may be available from federal or other sources to augment state funds appropriated for the purpose of this section, and shall make every effort to qualify for federal funding.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6100-S.SL.pdf?cite=2012%20c%2029%20§%207[2012 c 29 § 7]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1858.SL.pdf?cite=1995%20c%20241%20§%201[1995 c 241 § 1]; ]

== 43.280.090 - Office of crime victims advocacy—Ad hoc advisory committees.
The director of the department of commerce may establish ad hoc advisory committees, as necessary, to obtain advice and guidance regarding the office of crime victims advocacy program.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6100-S.SL.pdf?cite=2012%20c%2029%20§%208[2012 c 29 § 8]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1107-S.SL.pdf?cite=1995%20c%20269%20§%202102[1995 c 269 § 2102]; ]

== 43.280.091 - Statewide coordinating committee on sex trafficking.
. The statewide coordinating committee on sex trafficking is established to address the issues of sex trafficking, to examine the practices of local and regional entities involved in addressing sex trafficking, and to develop a statewide plan to address sex trafficking.

. The committee is administered by the department of commerce and consists of the following members:

.. Two members of the house of representatives, one from each caucus, and two members of the senate, one from each caucus, to be appointed by the speaker of the house of representatives and the president of the senate, respectively;

.. A representative of the Washington attorney general's office;

.. The president or corporate executive officer of the center for children and youth justice or his or her designee;

.. The secretary of the children's administration or his or her designee;

.. The secretary of the juvenile rehabilitation administration or his or her designee;

.. The superintendent of public instruction or his or her designee;

.. A representative of the administrative office of the courts appointed by the administrative office of the courts;

.. The executive director of the Washington association of sheriffs and police chiefs or his or her designee;

.. The executive director of the Washington state criminal justice training commission or his or her designee;

.. Representatives of community advocacy groups that work to address the issues of human trafficking, to be appointed by the department of commerce's office of crime victims advocacy;

.. A representative of the Washington association of prosecuting attorneys appointed by the association;

.. Representatives of community service providers that serve victims of human trafficking, to be appointed by the department of commerce's office of crime victims advocacy;

.. The executive director of Washington engage or his or her designee;

.. A representative from shared hope international or his or her designee;

.. The executive director of the Washington coalition of crime victim advocates or his or her designee;

.. The executive director of the Washington coalition of sexual assault programs or his or her designee;

.. The executive director of the Washington state coalition against domestic violence or his or her designee;

.. The executive director of the Washington association of cities or his or her designee;

.. The executive director of the Washington association of counties or his or her designee; and

.. The director or a representative from the crime victims compensation program.

. The duties of the committee include, but are not limited to:

.. Gathering and assessing service practices from diverse sources regarding service demand and delivery;

.. Analyzing data regarding the implementation of sex trafficking legislation passed in recent years by the legislature, including reports submitted to the department of commerce pursuant to RCW 9.68A.105, 9A.88.120, and 9A.88.140, and assessing the efficacy of such legislation in addressing sex trafficking, as well as any obstacles to the impact of legislation on the commercial sex trade;

.. Receiving and reviewing reports, recommendations, and statewide protocols as implemented in the pilot sites selected by the center for children and youth justice regarding commercially sexually exploited youth submitted to the committee by organizations that coordinate local community response practices and regional entities concerned with commercially sexually exploited youth; and

.. Gathering and reviewing existing data, research, and literature to help shape a plan of action to address human trafficking in Washington to include:

... Strategies for Washington to undertake to end sex trafficking; and

... Necessary data collection improvements.

. The committee shall meet twice and, by December 2014, produce a report on its activities, together with a statewide plan to address sex trafficking in Washington, to the governor's office and the legislature.

. All expenses of the committee shall come from the prostitution prevention and intervention account created in RCW 43.63A.740.

. The members of the committee shall serve without compensation, but shall be reimbursed for travel expenses as provided in RCW 43.03.050 and 43.03.060, within available resources.

. The committee expires June 30, 2015.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1291-S.SL.pdf?cite=2013%20c%20121%20§%202[2013 c 121 § 2]; ]

== 43.280.095 - Statewide training on Washington's human trafficking laws—Training entity—Report.
. The office of crime victims advocacy shall establish a statewide training program on Washington's human trafficking laws for criminal justice personnel.

. The training shall be provided where possible by an entity that has experience in developing coalitions, training, programs, and policy on human trafficking in Washington.

. The entity will provide or coordinate training for law enforcement personnel, prosecutors, and court personnel covering Washington's state antitrafficking laws, the investigation of sex trafficking cases, and the adjudication of sex trafficking cases. The training shall encourage interdisciplinary coordination among criminal justice personnel, build cultural competency, and develop understanding of diverse victim populations including children, youth, and adults.

. The office shall provide a biennial report to the appropriate policy committees of the legislature on the statewide training program, with a focus on the effectiveness of the training.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5933-S.SL.pdf?cite=2015%20c%20101%20§%202[2015 c 101 § 2]; ]

== 43.280.100 - Revenue collection under RCW  9.68A.105,  9A.88.120, or  9A.88.140—Expenditure of revenue—Conditions—Report.
. The department of commerce shall prepare and submit an annual report to the legislature on the amount of revenue collected by local jurisdictions under RCW 9.68A.105, 9A.88.120, or 9A.88.140 and the expenditure of that revenue.

. Any funds remitted to the department of commerce pursuant to RCW 9.68A.105, 9A.88.120, or 9A.88.140 shall be spent on the fulfillment of the duties described in subsection (1) of this section. Any remaining funds may be spent on the administration of grants for services for victims of the commercial sex trade, consistent with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1291-S.SL.pdf?cite=2013%20c%20121%20§%207[2013 c 121 § 7]; ]

== 43.280.110 - Public restrooms—Model notice on human trafficking—Voluntary posting—Report to legislature.
. Every establishment that maintains restrooms for use by the public may voluntarily, upon availability of the model notice as described in subsection (2) of this section, post a notice that complies with the requirements of this section in a conspicuous place within all restrooms of the establishment in clear view of the public and employees. The office of crime victims advocacy may work with businesses and other establishments and with human trafficking victim advocates to adopt policies for the placement of such notices.

. [Empty]
.. The model notice that may be voluntarily posted pursuant to subsection (1) of this section may be in a variety of languages and include toll-free telephone numbers a person may call for assistance, including the number for the national human trafficking resource center and the number for the Washington state office of crime victims advocacy.

.. The office of crime victims advocacy shall review and approve the initial form and content of the model notice to ensure the notice is appropriate for public display and likely to be an effective communication to reach human trafficking victims. The office of crime victims advocacy shall review the model notice on a yearly basis to ensure the information provided remains accurate.

. The cost of production, printing, and posting of the model notices shall be paid by a participating nonprofit at no cost to the state.

. The office of crime victims advocacy must provide a report to the appropriate committees of the legislature no later than December 31, 2016, regarding the voluntary participation in this effort.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5884-S.SL.pdf?cite=2015%20c%20273%20§%205[2015 c 273 § 5]; ]

