= 43.235 - Domestic violence fatality review panels.
:toc:

== 43.235.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Department" means the department of social and health services.

. "Domestic violence fatality" means a homicide or suicide under any of the following circumstances:

.. The alleged perpetrator and victim resided together at any time;

.. The alleged perpetrator and victim have a child in common;

.. The alleged perpetrator and victim were married, divorced, separated, or had a dating relationship;

.. The alleged perpetrator had been stalking the victim;

.. The homicide victim lived in the same household, was present at the workplace of, was in proximity of, or was related by blood or affinity to a victim who experienced or was threatened with domestic abuse by the alleged perpetrator; or

.. The victim or perpetrator was a child of a person in a relationship that is described within this subsection.

This subsection should be interpreted broadly to give the domestic violence fatality review panels discretion to review fatalities that have occurred directly to domestic relationships.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2588-S2.SL.pdf?cite=2000%20c%2050%20§%201[2000 c 50 § 1]; ]

== 43.235.020 - Department authorized to make available grants awarded on a contract basis—Coordination of review—Authority of coordinating entity—Regional and statewide domestic violence fatality review panels—Citizen requests.
. The department is authorized, subject to the availability of state funds, to make available grants awarded on a contract basis to an entity with expertise in domestic violence policy and education and with a statewide perspective to gather and maintain data relating to and coordinate review of domestic violence fatalities.

. The coordinating entity shall be authorized to:

.. Convene regional review panels;

.. Convene statewide issue-specific review panels;

.. Gather information for use of regional or statewide issue-specific review panels;

.. Provide training and technical assistance to regional or statewide issue-specific review panels;

.. Compile information and issue reports with recommendations; and

.. Establish a protocol that may be used as a guideline for identifying domestic violence related fatalities, forming review panels, convening reviews, and selecting which cases to review. The coordinating entity may also establish protocols for data collection and preservation of confidentiality.

. [Empty]
.. The coordinating entity may convene a regional or statewide issue-specific domestic violence fatality review panel to review any domestic violence fatality.

.. Private citizens may request a review of a particular death by submitting a written request to the coordinating entity within two years of the death. Of these, the appropriate regional review panel may review those cases which fit the criteria set forth in the protocol for the project.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5631-S.SL.pdf?cite=2015%20c%20275%20§%2012[2015 c 275 § 12]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5395.SL.pdf?cite=2011%20c%20105%20§%201[2011 c 105 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2588-S2.SL.pdf?cite=2000%20c%2050%20§%202[2000 c 50 § 2]; ]

== 43.235.030 - Domestic violence fatality review panels—Composition—Reports.
. Regional domestic violence fatality review panels may include, as appropriate, the following:

.. Medical personnel with expertise in domestic violence abuse;

.. Coroners or medical examiners or others experienced in the field of forensic pathology, if available;

.. County prosecuting attorneys or municipal attorneys;

.. Domestic violence shelter service staff or domestic violence victims' advocates;

.. Law enforcement personnel;

.. Local health department staff;

.. Child protective services workers;

.. Community corrections professionals;

.. Perpetrator treatment program provider;

.. School teachers, guidance counselors, or student health services staff; and

.. Judges, court administrators, and/or their representatives.

. Regional domestic violence fatality review panels may also invite other relevant persons to serve on an ad hoc basis and participate as full members of the review panel for a particular review. These persons may include, but are not limited to:

.. Individuals with particular expertise helpful to the regional review panel;

.. Representatives of organizations or agencies that had contact with or provided services to the homicide victim or to the alleged perpetrator.

. The regional review panels shall make periodic reports to the coordinating entity and shall make a final report to the coordinating entity with regard to every fatality that is reviewed.

. Statewide issue-specific panels must include persons with particular subject matter expertise helpful to the panel. The statewide issue-specific review panels must make periodic reports to the coordinating entity and must make a final report to the coordinating entity for every fatality that is reviewed.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5395.SL.pdf?cite=2011%20c%20105%20§%202[2011 c 105 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2588-S2.SL.pdf?cite=2000%20c%2050%20§%203[2000 c 50 § 3]; ]

== 43.235.040 - Confidentiality—Access to information.
. An oral or written communication or a document shared with the coordinating entity or within or produced by a domestic violence fatality review panel related to a domestic violence fatality review is confidential and not subject to disclosure or discoverable by a third party. An oral or written communication or a document provided by a third party to the coordinating entity or a domestic violence fatality review panel, or between a third party and a domestic violence fatality review panel, related to a domestic violence fatality review is confidential and not subject to disclosure or discovery by a third party. Notwithstanding the foregoing, recommendations from the domestic violence fatality review panel and the coordinating entity generally may be disclosed minus personal identifiers.

. The coordinating entity and review panels, only to the extent otherwise permitted by law or court rule, shall have access to information and records regarding the domestic violence victims and perpetrators under review held by domestic violence perpetrators' treatment providers; dental care providers; hospitals, medical providers, and pathologists; coroners and medical examiners; mental health providers; lawyers; the state and local governments; the courts; and employers. The coordinating entity and the review panels shall maintain the confidentiality of such information to the extent required by any applicable law.

. The coordinating entity or review panels shall review, only to the extent otherwise permitted by law or court rule when determined to be relevant and necessary to an investigation, guardian ad litem reports, parenting evaluations, and victim impact statements; probation information; mental health evaluations done for court; presentence interviews and reports, and any recommendations made regarding bail and release on own recognizance; child protection services, welfare, and other information held by the department; any law enforcement incident documentation, such as incident reports, dispatch records, victim, witness, and suspect statements, and any supplemental reports, probable cause statements, and 911 call taker's reports; corrections and postsentence supervision reports; and any other information determined to be relevant to the review. The coordinating entity and the review panels shall maintain the confidentiality of such information to the extent required by any applicable law.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5631-S.SL.pdf?cite=2015%20c%20275%20§%2013[2015 c 275 § 13]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2363-S.SL.pdf?cite=2012%20c%20223%20§%206[2012 c 223 § 6]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2588-S2.SL.pdf?cite=2000%20c%2050%20§%204[2000 c 50 § 4]; ]

== 43.235.050 - Immunity from liability.
If acting in good faith, without malice, and within the parameters of this chapter and the protocols established, representatives of the coordinating entity and the statewide and regional domestic violence fatality review panels are immune from civil liability for an activity related to reviews of particular fatalities.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2363-S.SL.pdf?cite=2012%20c%20223%20§%207[2012 c 223 § 7]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2588-S2.SL.pdf?cite=2000%20c%2050%20§%205[2000 c 50 § 5]; ]

== 43.235.060 - Data collection and analysis.
Within available funds, data regarding each domestic violence fatality review shall be collected on standard forms created by the coordinating entity. Data collected on reviewed fatalities shall be compiled and analyzed for the purposes of identifying points at which the system response to domestic violence could be improved and identifying patterns in domestic violence fatalities.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2588-S2.SL.pdf?cite=2000%20c%2050%20§%206[2000 c 50 § 6]; ]

== 43.235.800 - Statewide report.
A biennial statewide report shall be issued by the coordinating entity in December of even-numbered years, ending in 2010. The coordinating entity may subsequently issue periodic reports containing recommendations on policy changes that would improve program performance, and issues identified through the work of the regional panels. Copies of this report shall be distributed to the governor, to the appropriate legislative committees, and to those agencies involved in the regional domestic violence fatality review panels.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5395.SL.pdf?cite=2011%20c%20105%20§%203[2011 c 105 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2588-S2.SL.pdf?cite=2000%20c%2050%20§%207[2000 c 50 § 7]; ]

== 43.235.900 - Conflict with federal requirements—2000 c 50.
If any part of this act is found to be in conflict with federal requirements that are a prescribed condition to the allocation of federal funds to the state, the conflicting part of this act is inoperative solely to the extent of the conflict and with respect to the agencies directly affected, and this finding does not affect the operation of the remainder of this act in its application to the agencies concerned. Rules adopted under this act must meet federal requirements that are a necessary condition to the receipt of federal funds by the state.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2588-S2.SL.pdf?cite=2000%20c%2050%20§%209[2000 c 50 § 9]; ]

== 43.235.901 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%20111[2009 c 521 § 111]; ]

