= 43.210 - Small business export finance assistance center.
:toc:

== 43.210.010 - Findings.
The legislature finds:

. The exporting of goods and services from Washington to international markets is an important economic stimulus to the growth, development, and stability of the state's businesses in both urban and rural areas, and that these economic activities create needed jobs for Washingtonians.

. Impediments to the entry of many small and medium-sized businesses into export markets have restricted growth in exports from the state.

. Particularly significant impediments for many small and medium-sized businesses are the lack of easily accessible information about export opportunities and financing alternatives.

. There is a need for a small business export finance assistance center which will specialize in providing export assistance to small and medium-sized businesses throughout the state in acquiring information about export opportunities and financial alternatives for exporting.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c17.pdf?cite=1990%201st%20ex.s.%20c%2017%20§%2065[1990 1st ex.s. c 17 § 65]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c231.pdf?cite=1985%20c%20231%20§%201[1985 c 231 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c20.pdf?cite=1983%201st%20ex.s.%20c%2020%20§%201[1983 1st ex.s. c 20 § 1]; ]

== 43.210.020 - Small business export finance assistance center authorized—Purposes.
A nonprofit corporation, to be known as the small business export finance assistance center, and branches subject to its authority, may be formed under chapter 24.03 RCW for the following public purposes:

. To assist small and medium-sized businesses in both urban and rural areas in the financing of export transactions.

. To provide, singly or in conjunction with other organizations, information and assistance to these businesses about export opportunities and financing alternatives.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2529-S.SL.pdf?cite=1998%20c%20109%20§%201[1998 c 109 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c17.pdf?cite=1990%201st%20ex.s.%20c%2017%20§%2066[1990 1st ex.s. c 17 § 66]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c231.pdf?cite=1985%20c%20231%20§%202[1985 c 231 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c20.pdf?cite=1983%201st%20ex.s.%20c%2020%20§%202[1983 1st ex.s. c 20 § 2]; ]

== 43.210.030 - Board of directors—Membership—Terms—Vacancies.
The small business export finance assistance center and its branches shall be governed and managed by a board of seven directors appointed by the governor, with the advice of the board, and confirmed by the senate. The directors shall serve terms of four years following the terms of service established by the initial appointments after June 11, 1998. Three appointees, including directors on June 11, 1998, who are reappointed, must serve initial terms of two years and, if a director is reappointed that director may serve a consecutive four-year term. Four appointees, including directors on June 11, 1998, who are reappointed, must serve initial terms of four years and, if a director is reappointed that director may serve a consecutive four-year term. After the initial appointments, directors may serve two consecutive terms. The directors may provide for the payment of their expenses. The directors shall include the *director of community, trade, and economic development or the director's designee; representatives of a large financial institution engaged in financing export transactions in the state of Washington; a small financial institution engaged in financing export transactions in the state of Washington; a large exporting company domiciled in the state of Washington; a small exporting company in the state of Washington; organized labor in a trade involved in international commerce; and a representative at large. To the extent possible, appointments to the board shall reflect geographical balance and the diversity of the state population. Any vacancies on the board due to the expiration of a term or for any other reason shall be filled by appointment by the governor for the unexpired term.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2529-S.SL.pdf?cite=1998%20c%20109%20§%202[1998 c 109 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%20106[1995 c 399 § 106]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1341-S.SL.pdf?cite=1991%20c%20314%20§%2015[1991 c 314 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c231.pdf?cite=1985%20c%20231%20§%203[1985 c 231 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c20.pdf?cite=1983%201st%20ex.s.%20c%2020%20§%203[1983 1st ex.s. c 20 § 3]; ]

== 43.210.040 - Powers and duties.
. The small business export finance assistance center formed under RCW 43.210.020 and 43.210.030 has the powers granted under chapter 24.03 RCW. In exercising such powers, the center may:

.. Solicit and accept grants, contributions, and any other financial assistance from the federal government, federal agencies, and any other sources to carry out its purposes;

.. Make loans or provide loan guarantees on loans made by financial institutions to Washington businesses with annual sales of two hundred million dollars or less for the purpose of financing exports of goods or services by those businesses to buyers in foreign countries and for the purpose of financing business growth to accommodate increased export sales. Loans or loan guarantees made under the authority of this section may only be considered upon a financial institution's assurance that such loan or loan guarantee is otherwise not available;

.. Provide assistance to businesses with annual sales of two hundred million dollars or less in obtaining loans and guarantees of loans made by financial institutions for the purpose of financing export of goods or services from the state of Washington;

.. Provide export finance and risk mitigation counseling to Washington exporters with annual sales of two hundred million dollars or less, provided that such counseling is not practicably available from a Washington for-profit business. For such counseling, the center may charge reasonable fees as it determines are necessary;

.. Provide assistance in obtaining export credit insurance or alternate forms of foreign risk mitigation to facilitate the export of goods and services from the state of Washington;

.. Be available as a teaching resource to both public and private sponsors of workshops and programs relating to the financing and risk mitigation aspects of exporting products and services from the state of Washington;

.. Develop a comprehensive inventory of export-financing resources, both public and private, including information on resource applicability to specific countries and payment terms;

.. Contract with the federal government and its agencies to become a program administrator for federally provided loan guarantee and export credit insurance programs; and

.. Take whatever action may be necessary to accomplish the purposes set forth in this chapter.

. The center may not use any Washington state funds or funds which come from the public treasury of the state of Washington to make loans or to make any payment under a loan guarantee agreement. Under no circumstances may the center use any funds received under RCW 43.210.050 to make or assist in making any loan or to pay or assist in paying any amount under a loan guarantee agreement. Debts of the center shall be center debts only and may be satisfied only from the resources of the center. The state of Washington shall not in any way be liable for such debts.

. The small business export finance assistance center shall make every effort to seek nonstate funds for its continued operation.

. The small business export finance assistance center may receive such gifts, grants, and endowments from public or private sources as may be made from time to time, in trust or otherwise, for the use and benefit of the purposes of the small business export finance assistance center and expend the same or any income therefrom according to the terms of the gifts, grants, or endowments.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6679-S2.SL.pdf?cite=2010%20c%20166%20§%201[2010 c 166 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2529-S.SL.pdf?cite=1998%20c%20109%20§%203[1998 c 109 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c505.pdf?cite=1987%20c%20505%20§%2043[1987 c 505 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c231.pdf?cite=1985%20c%20231%20§%204[1985 c 231 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c20.pdf?cite=1983%201st%20ex.s.%20c%2020%20§%204[1983 1st ex.s. c 20 § 4]; ]

== 43.210.050 - Export assistance services contract with department of commerce.
. The small business export finance assistance center formed under RCW 43.210.020 and 43.210.030 must enter into a contract under this chapter with the department of commerce or its statutory successor.

. The contract under subsection (1) of this section must:

.. Require the center to provide export assistance services;

.. Have a duration of two years;

.. Require the center to aggressively seek to fund its continued operation from nonstate funds; and

.. Require the center to report annually to the department on its success in obtaining nonstate funding.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6679-S2.SL.pdf?cite=2010%20c%20166%20§%202[2010 c 166 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%2084[1998 c 245 § 84]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%20107[1995 c 399 § 107]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1341-S.SL.pdf?cite=1991%20c%20314%20§%2016[1991 c 314 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c466.pdf?cite=1985%20c%20466%20§%2064[1985 c 466 § 64]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c231.pdf?cite=1985%20c%20231%20§%205[1985 c 231 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c20.pdf?cite=1983%201st%20ex.s.%20c%2020%20§%205[1983 1st ex.s. c 20 § 5]; ]

== 43.210.060 - Rule-making authority.
The *department of community, trade, and economic development or its statutory successor shall adopt rules under chapter 34.05 RCW as necessary to carry out the purposes of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%20108[1995 c 399 § 108]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c466.pdf?cite=1985%20c%20466%20§%2065[1985 c 466 § 65]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c20.pdf?cite=1983%201st%20ex.s.%20c%2020%20§%206[1983 1st ex.s. c 20 § 6]; ]

== 43.210.080 - Rural manufacturer export outreach program—Export loan or loan guarantee programs.
Subject to the availability of amounts appropriated for this specific purpose, the small business export finance assistance center must:

. Develop a rural manufacturer export outreach program in conjunction with impact Washington. The program must provide outreach services to rural manufacturers in Washington to inform them of the importance of and opportunities in international trade, and to inform them of the export assistance programs available to assist these businesses to become exporters; and

. Develop export loan or loan guarantee programs in conjunction with the Washington economic development finance authority and the appropriate federal and private entities.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6679-S2.SL.pdf?cite=2010%20c%20166%20§%203[2010 c 166 § 3]; ]

== 43.210.130 - Minority business export outreach program.
The small business export finance assistance center shall develop a minority business export outreach program. The program shall provide outreach services to minority-owned businesses in Washington to inform them of the importance of and opportunities in international trade, and to inform them of the export assistance programs available to assist these businesses to become exporters.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1493-S.SL.pdf?cite=1993%20c%20512%20§%205[1993 c 512 § 5]; ]

