= 43.220 - Washington conservation corps.
:toc:

== 43.220.020 - Conservation corps created—Puget Sound corps created.
. The Washington conservation corps is created. The department of ecology must administer the corps as a partnership with the departments of natural resources and fish and wildlife, the state parks and recreation commission, and when appropriate, other agencies and nonprofit organizations to advance the program goals outlined in RCW 43.220.045.

. The Puget Sound corps is created as a distinct program within the Washington conservation corps focused on the implementation of the specific program goals outlined in RCW 43.220.045.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1294-S.SL.pdf?cite=2011%20c%2020%20§%202[2011 c 20 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5255.SL.pdf?cite=1999%20c%20280%20§%201[1999 c 280 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2590.SL.pdf?cite=1994%20c%20264%20§%2032[1994 c 264 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c36.pdf?cite=1988%20c%2036%20§%2023[1988 c 36 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c40.pdf?cite=1983%201st%20ex.s.%20c%2040%20§%201[1983 1st ex.s. c 40 § 1]; ]

== 43.220.040 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Agency administrative costs" means indirect expenses such as personnel, payroll, contract administration, fiscal services, and other overhead costs.

. "Corps" means the Washington conservation corps, including the Puget Sound corps.

. "Corps member" means an individual enrolled in the Washington conservation corps.

. "Corps member leaders" or "specialists" means members of the corps who serve in leadership or training capacities or who provide specialized services other than or in addition to the types of work and services that are performed by the corps members in general.

. "Crew supervisor" means temporary, project, or permanent state employees who supervise corps members and coordinate work project design and completion.

(6 "Department" means the department of ecology.

. "Program support costs" include, but are not limited to, program planning, development of reports, job and career training, uniforms and equipment, and standard office space and utilities. Program support costs do not include direct scheduling and supervision of corps members.

. "Public lands" means any lands or waters, or interests therein, owned or administered by any agency or instrumentality of the state, federal, or local government.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1294-S.SL.pdf?cite=2011%20c%2020%20§%204[2011 c 20 § 4]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5255.SL.pdf?cite=1999%20c%20280%20§%203[1999 c 280 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1251-S.SL.pdf?cite=1999%20c%20151%20§%201301[1999 c 151 § 1301]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c367.pdf?cite=1987%20c%20367%20§%202[1987 c 367 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c40.pdf?cite=1983%201st%20ex.s.%20c%2040%20§%204[1983 1st ex.s. c 40 § 4]; ]

== 43.220.045 - Project goals—Recovery of Puget Sound ecosystem—Priorities.
. The corps shall be organized and managed to complete projects with fee-for-service work crews that meet goals associated with the protection, promotion, enhancement, or rehabilitation of the following:

.. Public lands;

.. State natural resources;

.. Water quality;

.. Watershed health;

.. Fish and wildlife;

.. Habitat;

.. Outdoor recreation;

.. Forest health;

.. Wildfire risk reduction; and

.. State historic sites.

. In addition to the project goals outlined in subsection (1) of this section, the Puget Sound corps shall seek to deploy corps members with the specific goal of participating in the recovery of the Puget Sound ecosystem. The resources of the Puget Sound corps must be prioritized, when practicable, to focus on the following when located within the Puget Sound basin:

.. Projects identified in, or consistent with, the action agenda developed by the Puget Sound partnership in chapter 90.71 RCW;

.. Projects located on public lands;

.. Habitat enhancement and rehabilitation projects; and

.. Education and stewardship projects.

. Both the corps and the Puget Sound corps shall give preference to projects that satisfy the goals identified in this section and that:

.. Will provide long-term benefits to the public;

.. Will provide productive training and work experiences to the corps members involved;

.. Expands or integrates training programs or career development opportunities for corps members;

.. May result in payments to the state for services performed; and

.. Can be promptly completed.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1294-S.SL.pdf?cite=2011%20c%2020%20§%205[2011 c 20 § 5]; ]

== 43.220.060 - Powers and duties—Partnering with other entities—Effect on employed workers—Use of facilities, supplies, instruments, and tools of supervising agency.
. The department shall have the following powers and duties as necessary to administer the Washington conservation corps:

.. Recruiting and employing staff, corps members, corps member leaders, and specialists consistent with RCW 43.220.070;

.. Serving as the corps' central application recipient for grants from federal service projects and service organizations;

.. Executing agreements for furnishing the services of the corps to carry out conservation corps programs to any federal, state, or local public agency, any local organization as specified in this chapter that operates consistent with the overall objectives of the conservation corps;

.. Applying for and accepting grants or contributions of funds from the federal government, other public sources, or private funding sources for conservation corps projects and, when possible, other projects specifically targeted at Puget Sound recovery that can be accomplished with fee-for-service labor from the Puget Sound corps. Application priority must be given to funding sources only available to state agencies;

.. Establishing consistent work standards and placement and evaluation procedures of corps programs; and

.. Selecting, reviewing, approving, and evaluating the success of corps projects.

. The department may partner with any other state agencies, local institutions, nonprofit organizations, or nonprofit service corps organizations in the administration of the corps. However, when partnering with the Washington department of veterans affairs, participation criteria and other administrative decisions affecting participants in the veterans conservation corps created under chapter 43.60A RCW are to be determined by the Washington department of veterans affairs. Other state agencies may maintain a coordinator for the purposes of partnering with the department and the corps.

. If deemed practicable, the department shall work with the state board for community and technical colleges created in RCW 28B.50.050 to align the conservation corps program with optional career pathways for participants that may provide instruction in basic skills in addition to the appropriate technical training.

. The assignment of corps members shall not result in the displacement of currently employed workers, including partial displacement such as reduction in hours of nonovertime work, wages, or other employment benefits. Agencies that participate in the program may not terminate, lay-off, or reduce the working hours of any employee for the purpose of using a corps member with available funds. In circumstances where substantial efficiencies or a public purpose may result, participating agencies may use corps members to carry out essential agency work or contractual functions without displacing current employees.

. Facilities, supplies, motor vehicles, instruments, and tools of participating agencies shall be made available for use by the conservation corps to the extent that such use does not conflict with the normal duties of the agency. The agency may purchase, rent, or otherwise acquire other necessary tools, facilities, supplies, and instruments.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1294-S.SL.pdf?cite=2011%20c%2020%20§%206[2011 c 20 § 6]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5255.SL.pdf?cite=1999%20c%20280%20§%204[1999 c 280 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c505.pdf?cite=1987%20c%20505%20§%2044[1987 c 505 § 44]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c40.pdf?cite=1983%201st%20ex.s.%20c%2040%20§%206[1983 1st ex.s. c 40 § 6]; ]

== 43.220.070 - Corps membership—Eligibility—Coordination of recruitment activities—Enrollment period.
. [Empty]
.. Except as otherwise provided in this section, conservation corps members must be unemployed or underemployed residents of the state between eighteen and twenty-five years of age at the time of enrollment who are citizens or lawful permanent residents of the United States.

.. The age requirements may be waived for corps leaders, veterans, specialists with special leadership or occupational skills, and participants with a disability.

. The recruitment of conservation corps members is the primary responsibility of the department. However, to the degree practicable, recruitment activities must be coordinated with the following entities:

.. The department of natural resources;

.. The department of fish and wildlife;

.. The state parks and recreation commission;

.. The Washington department of veterans affairs;

.. The employment security department;

.. Community and technical colleges; and

.. Any other interested postsecondary educational institutions.

. Recruitment efforts must be targeted to, but not limited to, residents of the state who meet the participation eligibility requirements provided in this section and are either:

.. A student enrolled at a community or technical college, private career college, or a four-year college or university;

.. A minority or disadvantaged youth residing in an urban or rural area of the state; or

.. Military veterans.

. Corps members shall not be considered state employees. Other provisions of law relating to civil service, hours of work, rate of compensation, sick leave, unemployment compensation, state retirement plans, and vacation leave do not apply to the Washington conservation corps except for the crew supervisors, who shall be project employees, and the administrative and supervisory personnel.

. Except as otherwise provided in this section, participation as a corps member is for an initial period of three months. The enrollment period may be extended for additional three-month periods by mutual agreement of the department and the corps member, not to exceed two years.

. [Empty]
.. Corps members are to be available at all times for emergency response services coordinated through the department or other public agency. Duties may include sandbagging and flood cleanup, oil spill response, wildfire suppression, search and rescue, and other functions in response to emergencies.

.. Corps members may be assigned to longer-term specialized crews not subject to the temporal limitations of service otherwise imposed by this section when longer-term commitments satisfy the specialized needs of the department, an agency partner, or other service contractee.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2390.SL.pdf?cite=2020%20c%20274%20§%2027[2020 c 274 § 27]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1294-S.SL.pdf?cite=2011%20c%2020%20§%207[2011 c 20 § 7]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5255.SL.pdf?cite=1999%20c%20280%20§%205[1999 c 280 § 5]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%20112[1995 c 399 § 112]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c71.pdf?cite=1990%20c%2071%20§%202[1990 c 71 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c78.pdf?cite=1988%20c%2078%20§%201[1988 c 78 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2048[1986 c 266 § 48]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c230.pdf?cite=1985%20c%20230%20§%207[1985 c 230 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%20110[1985 c 7 § 110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c40.pdf?cite=1983%201st%20ex.s.%20c%2040%20§%207[1983 1st ex.s. c 40 § 7]; ]

== 43.220.075 - Annual meeting—Forum for partner agencies—Work plan.
. The director of the department of ecology and the commissioner of public lands shall jointly host an annual meeting with other corps program participants to serve as a forum for the partner agencies to provide guidance and feedback concerning the management and function of the corps.

. At a minimum, representatives of the following must be invited to participate at the annual meeting: The department of fish and wildlife; the state parks and recreation commission; the Puget Sound partnership; the department of veterans affairs; the employment security department; the Washington commission for national and community service; conservation districts; the state conservation commission; the salmon recovery funding board; the recreation and conservation office; the department of commerce; the department of health; or any similar successor organizations and any appropriate nonprofit organizations, including those engaged in service corps projects.

. Annual meeting participants shall, at a minimum:

.. Review the conservation corps projects completed in the previous year, including an analysis of successes and opportunities for improvement; and

.. Establish a work plan for the coming year, including the setting of annual priorities or criteria consistent with this chapter to guide crew development and the development of plans to pursue funding from various sources to expand the conservation corps.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1294-S.SL.pdf?cite=2011%20c%2020%20§%2011[2011 c 20 § 11]; ]

== 43.220.170 - Exemption from unemployment compensation coverage.
The services of corps members are exempt from unemployment compensation coverage under RCW 50.44.040(4) and the enrollees shall be so advised by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1294-S.SL.pdf?cite=2011%20c%2020%20§%208[2011 c 20 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c40.pdf?cite=1983%201st%20ex.s.%20c%2040%20§%2017[1983 1st ex.s. c 40 § 17]; ]

== 43.220.231 - Limitation on use of funds.
. An amount not to exceed five percent of the funds available for the Washington conservation corps may be expended on agency administrative costs.

. An amount not to exceed twenty percent of the funds available for the Washington conservation corps may be expended for costs included in subsection (1) of this section and program support costs.

. A minimum of eighty percent of the funds available for the Washington conservation corps shall be expended for corps member salaries and benefits and for direct supervision of corps members.

. Consistent with any fund source requirements, any state agency using federal funds to sponsor fee-for-service Washington conservation corps crews must contract with the Washington department of veterans affairs for at least five percent of the federal funding to sponsor veteran conservation corps crews operating under RCW 43.60A.150. This requirement applies statewide.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1294-S.SL.pdf?cite=2011%20c%2020%20§%209[2011 c 20 § 9]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5255.SL.pdf?cite=1999%20c%20280%20§%207[1999 c 280 § 7]; ]

== 43.220.250 - Reimbursement of nonprofit corporations for certain services.
A nonprofit corporation which contracts with the department to provide a specific service, appropriate for the administration of this chapter which the department cannot otherwise provide, may be reimbursed at the discretion of the department for the reasonable costs the department would absorb for providing those services.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1294-S.SL.pdf?cite=2011%20c%2020%20§%2010[2011 c 20 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c230.pdf?cite=1985%20c%20230%20§%205[1985 c 230 § 5]; ]

== 43.220.260 - Removal of noxious weeds—Planting of plants to provide forage for pollinators.
Any corps project that involves the removal of noxious weeds must, when deemed appropriate for the project goals by the project sponsor, include the planting of pollen-rich and nectar-rich native plants to provide forage for all pollinators, including honey bees.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2478.SL.pdf?cite=2016%20c%2044%20§%203[2016 c 44 § 3]; ]

== 43.220.904 - Effective date—1999 c 280.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and takes effect immediately [May 13, 1999].

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5255.SL.pdf?cite=1999%20c%20280%20§%209[1999 c 280 § 9]; ]

== 43.220.905 - Intent—Application—2011 c 20.
It is the intent of this act to centralize the administration of the Washington conservation corps, which was previously administered by the departments of ecology, natural resources, and fish and wildlife and the state parks and recreation commission, into the department of ecology. This act is prospective only, and any grant awards or conservation corps crew or individual placements finalized by other agencies or partners prior to July 22, 2011, remain unaffected by this act.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1294-S.SL.pdf?cite=2011%20c%2020%20§%203[2011 c 20 § 3]; ]

