= 43.290 - Office of international relations and protocol.
:toc:

== 43.290.005 - Finding—Purpose.
The legislature finds that it is in the public interest to create an office of international relations and protocol in order to: Make international relations and protocol a broad-based, focused, and functional part of state government; develop and promote state policies that increase international literacy and cross-cultural understanding among Washington state's citizens; expand Washington state's international cooperation role in such areas as the environment, education, science, culture, and sports; establish coordinated methods for responding to the increasing number of inquiries by foreign governments and institutions seeking cooperative activities within Washington state; provide leadership in state government on international relations and assistance to the legislature and state elected officials on international issues affecting the state; assist with multistate international efforts; and coordinate and improve communication and resource sharing among various state offices, agencies, and educational institutions with international programs.

It is the purpose of this chapter to bring these functions together in a new office under the office of the governor in order to establish a visible, coordinated, and comprehensive approach to international relations and protocol.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1800-S.SL.pdf?cite=1991%20c%2024%20§%201[1991 c 24 § 1]; ]

== 43.290.010 - Office created.
The office of international relations and protocol is created under the office of the governor. The office shall serve as the state's official liaison and protocol office with foreign governments. The governor shall appoint a director of the office of international relations and protocol, who shall serve at the pleasure of the governor. Because of the diplomatic character of this office, the director and staff will be exempt from the provisions of chapter 41.06 RCW. The director will be paid a salary to be fixed by the governor in accordance with the provisions of RCW 43.03.040. The director may hire such personnel as may be necessary for the general administration of the office. To the extent permitted by law, state agencies may temporarily loan staff to the office of international relations and protocol to assist in carrying out the office's duties and responsibilities under this chapter. An arrangement to temporarily loan staff must have the approval of the staff members to be loaned and the directors of the office and the agencies involved in the loan.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1800-S.SL.pdf?cite=1991%20c%2024%20§%202[1991 c 24 § 2]; ]

== 43.290.020 - Authority of office.
The office of international relations and protocol may:

. Create temporary advisory committees as necessary to deal with specific international issues. Advisory committee representation may include external organizations such as the Seattle consular corps, world affairs councils, public ports, world trade organizations, private nonprofit organizations dealing with international education or international environmental issues, organizations concerned with international understanding, businesses with experience in international relations, or other organizations deemed appropriate by the director.

. Accept or request grants or gifts from citizens and other private sources to be used to defray the costs of appropriate hosting of foreign dignitaries, including appropriate gift-giving and reciprocal gift-giving, or other activities of the office. The office shall open and maintain a bank account into which it shall deposit all money received under this subsection. Such money and the interest accruing thereon shall not constitute public funds, shall be kept segregated and apart from funds of the state, and shall not be subject to appropriation or allotment by the state or subject to chapter 43.88 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1800-S.SL.pdf?cite=1991%20c%2024%20§%204[1991 c 24 § 4]; ]

== 43.290.900 - Effective date—1991 c 24.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and shall take effect July 1, 1991.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1800-S.SL.pdf?cite=1991%20c%2024%20§%2015[1991 c 24 § 15]; ]

