= 43.250 - Investment of local government funds—Separately managed accounts.
:toc:

== 43.250.010 - Purpose.
The purpose of this chapter is to enable eligible governmental entities, including community and technical college districts, the state board for community and technical colleges as established in chapter 28B.50 RCW, public four-year institutions of higher education, qualifying federally recognized tribes or federally recognized political subdivisions thereof, and other governmental entities to participate with the state in providing maximum opportunities for the investment of surplus public funds consistent with the safety and protection of such funds. The legislature finds and declares that the public interest is found in providing maximum prudent investment of surplus funds, thereby reducing the need for additional taxation. The legislature also recognizes that not all eligible governmental entities are able to maximize the return on their temporary surplus funds. The legislature therefore provides in this chapter a mechanism whereby eligible governmental entities may, at their option, utilize the resources of the state treasurer's office to maximize the potential of surplus funds while ensuring the safety of those funds.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6221.SL.pdf?cite=2010%201st%20sp.s.%20c%2010%20§%201[2010 1st sp.s. c 10 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1623.SL.pdf?cite=2001%20c%2031%20§%201[2001 c 31 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2811.SL.pdf?cite=1996%20c%20268%20§%201[1996 c 268 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c294.pdf?cite=1986%20c%20294%20§%201[1986 c 294 § 1]; ]

== 43.250.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section shall apply throughout this chapter.

. "Authorized tribal official" means any officer or employee of a qualifying federally recognized tribe who has been expressly designated by tribal constitution, ordinance, or resolution as the officer having the authority to invest the funds of the qualifying federally recognized tribe or federally recognized political subdivisions thereof.

. "Eligible governmental entity" means any county, city, town, municipal corporation, quasi-municipal corporation, public corporation, political subdivision, or special purpose taxing district in the state, an instrumentality of any of the foregoing governmental entities created under chapter 39.34 RCW, any agency of state government, any entity issuing or executing and delivering bonds or certificates of participation with respect to financing contracts approved by the state finance committee under RCW 39.94.040, and any qualifying federally recognized tribe or federally recognized political subdivisions thereof.

. "Financial officer" means the board-appointed treasurer of a community or technical college district, the state board for community and technical colleges, or a public four-year institution of higher education.

. "Funds" means:

.. Funds of an eligible governmental entity under the control of or in the custody of any government finance official or local funds, as defined by the office of financial management publication "Policies, Regulations and Procedures," under the control of or in the custody of a financial officer by virtue of the official's authority that are not immediately required to meet current demands; and

.. Tribal funds under the control of or in the custody of any qualifying federally recognized tribe or federally recognized political subdivisions thereof, where the tribe warrants that the use or disposition of the funds are either not subject to, or are used and deposited with federal approval, and where the tribe warrants that the funds are not immediately required to meet current demands.

. "Government finance official" means any officer or employee of an eligible governmental entity who has been designated by statute or by local charter, ordinance, resolution, or other appropriate official action, as the officer having the authority to invest the funds of the eligible governmental entity. However, the county treasurer shall be deemed the only government finance official for all public agencies for which the county treasurer has exclusive statutory authority to invest the funds thereof.

. "Public funds investment account" or "investment pool" means the aggregate of all funds as defined in subsection (4) of this section that are placed in the custody of the state treasurer for pooled investment and reinvestment.

. "Qualifying federally recognized tribe or federally recognized political subdivisions thereof" means any federally recognized tribe, located in the state of Washington, authorized and empowered by its constitution or ordinance to invest its surplus funds pursuant to this section, and whose authorized tribal official has executed a deposit agreement with the office of the treasurer.

. "Separately managed accounts" means both the separately managed public funds investment account and the separately managed state agency investment account.

. "Separately managed public funds investment account" means the aggregate of all funds defined in subsection (4) of this section, except those that are remitted by state agencies, that are placed in the custody of the state treasurer for investment and reinvestment in separate portfolios.

. "Separately managed state agency investment account" means the aggregate of all funds defined in subsection (4) of this section that are remitted by state agencies and that are placed in the custody of the state treasurer for investment and reinvestment in separate portfolios.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1284-S.SL.pdf?cite=2019%20c%20163%20§%201[2019 c 163 § 1]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6349.SL.pdf?cite=2016%20c%20152%20§%2019[2016 c 152 § 19]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6221.SL.pdf?cite=2010%201st%20sp.s.%20c%2010%20§%202[2010 1st sp.s. c 10 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1623.SL.pdf?cite=2001%20c%2031%20§%202[2001 c 31 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2811.SL.pdf?cite=1996%20c%20268%20§%202[1996 c 268 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c106.pdf?cite=1990%20c%20106%20§%201[1990 c 106 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c294.pdf?cite=1986%20c%20294%20§%202[1986 c 294 § 2]; ]

== 43.250.030 - Public funds investment account.
There is created a trust fund to be known as the public funds investment account. The account is to be separately accounted for and invested by the state treasurer. All moneys remitted for pooled investment under this chapter shall be deposited in this account. All earnings on any balances in the public funds investment account, less moneys for administration pursuant to RCW 43.250.060, shall be credited to the public funds investment account.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1284-S.SL.pdf?cite=2019%20c%20163%20§%202[2019 c 163 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1058-S.SL.pdf?cite=1991%20sp.s.%20c%2013%20§%2086[1991 sp.s. c 13 § 86]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c106.pdf?cite=1990%20c%20106%20§%202[1990 c 106 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c294.pdf?cite=1986%20c%20294%20§%203[1986 c 294 § 3]; ]

== 43.250.040 - Investment pool—Investment of funds by state treasurer—Degree of judgment and care required.
If authorized by statute, local ordinance, resolution, or other appropriate official action, the state treasurer, a government finance official or financial officer or his or her designee, or authorized tribal official, may place funds into the public funds investment account for investment and reinvestment by the state treasurer in those securities and investments set forth in RCW 43.84.080 and chapter 39.58 RCW. The state treasurer shall invest the funds in such manner as to effectively maximize the yield to the investment pool. In investing and reinvesting moneys in the public funds investment account and in acquiring, retaining, managing, and disposing of investments of the investment pool, there shall be exercised the judgment and care under the circumstances then prevailing which persons of prudence, discretion, and intelligence exercise in the management of their own affairs, not in regard to speculation but in regard to the permanent disposition of the funds considering the probable income as well as the probable safety of the capital.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6221.SL.pdf?cite=2010%201st%20sp.s.%20c%2010%20§%203[2010 1st sp.s. c 10 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1623.SL.pdf?cite=2001%20c%2031%20§%203[2001 c 31 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2811.SL.pdf?cite=1996%20c%20268%20§%203[1996 c 268 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c294.pdf?cite=1986%20c%20294%20§%204[1986 c 294 § 4]; ]

== 43.250.050 - Investment pool—Employment of personnel.
The state treasurer's office is authorized to employ such personnel as are necessary to administer the public funds investment account. The bond of the state treasurer as required by law shall be made to include the faithful performance of all functions relating to the investment pool.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c294.pdf?cite=1986%20c%20294%20§%205[1986 c 294 § 5]; ]

== 43.250.060 - Investment pool—Generally.
The state treasurer shall by rule prescribe the time periods for investments in the investment pool and the procedure for withdrawal of funds from the investment pool. The state treasurer shall promulgate such other rules as are deemed necessary for the efficient operation of the investment pool. The rules shall also provide for the administrative expenses of the investment pool, including repayment of the initial administrative costs financed out of the appropriation included in chapter 294, Laws of 1986, to be paid from the pool's earnings and for the interest earnings in excess of the expenses to be credited or paid to participants in the pool. The state treasurer may deduct the amounts necessary to reimburse the treasurer's office for the actual expenses the office incurs and to repay any funds appropriated and expended for the initial administrative costs of the pool. Any credits or payments to the participants shall be calculated and made in a manner which equitably reflects the differing amounts of the participants' respective deposits in the investment pool fund and the differing periods of time for which the amounts were placed in the investment pool.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c106.pdf?cite=1990%20c%20106%20§%203[1990 c 106 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c294.pdf?cite=1986%20c%20294%20§%206[1986 c 294 § 6]; ]

== 43.250.070 - Investment pool—Separate accounts for participants—Monthly status report.
The state treasurer shall keep a separate account for each participant having funds in the investment pool. Each separate account shall record the individual amounts deposited in the investment pool, the date of withdrawals, and the earnings credited or paid. The state treasurer shall report monthly the status of the respective account to each participant having funds in the pool during the previous month.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c106.pdf?cite=1990%20c%20106%20§%204[1990 c 106 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c294.pdf?cite=1986%20c%20294%20§%207[1986 c 294 § 7]; ]

== 43.250.080 - Investment pool—Annual summary of activity.
At the end of each fiscal year, the state treasurer shall submit to the governor, the state auditor, and the joint legislative audit and review committee a summary of the activity of the investment pool. The summary shall indicate the quantity of funds deposited; the earnings of the pool; the investments purchased, sold, or exchanged; the administrative expenses of the investment pool; and such other information as the state treasurer deems relevant.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2222-S2.SL.pdf?cite=1996%20c%20288%20§%2048[1996 c 288 § 48]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c294.pdf?cite=1986%20c%20294%20§%208[1986 c 294 § 8]; ]

== 43.250.150 - Separately managed public funds investment account.
There is created a trust fund to be known as the separately managed public funds investment account. The account is to be separately accounted for and invested by the state treasurer. All moneys remitted for investment in separate portfolios under this chapter, except those remitted by state agencies, shall be deposited in this account. All earnings on any balances in the separately managed public funds investment account, less amounts charged by the office of the state treasurer, shall be credited to the separately managed public funds investment account.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1284-S.SL.pdf?cite=2019%20c%20163%20§%204[2019 c 163 § 4]; ]

== 43.250.160 - Separately managed state agency investment account.
There is created a trust fund to be known as the separately managed state agency investment account. The account is to be separately accounted for and invested by the state treasurer. All moneys remitted by state agencies for investment in separate portfolios under this chapter shall be deposited in this account. All earnings on any balances in the separately managed state agency investment account, less amounts charged by the office of the state treasurer, shall be credited to the separately managed state agency investment account.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1284-S.SL.pdf?cite=2019%20c%20163%20§%205[2019 c 163 § 5]; ]

== 43.250.170 - Separately managed state treasurer's service account.
A separately managed state treasurer's service account is created in the custody of the state treasurer. The account is not subject to appropriation or allotment procedures. All moneys received from separately managed accounts for payment to the office of the state treasurer must be deposited into the separately managed state treasurer's service account. Expenditures from the separately managed state treasurer's service account may be made solely for the operation of the separately managed accounts investment program. Only the treasurer or the treasurer's designee may authorize expenditures from the separately managed state treasurer's service account.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1284-S.SL.pdf?cite=2019%20c%20163%20§%206[2019 c 163 § 6]; ]

== 43.250.180 - Separately managed accounts—Agreements—Rule making.
If the office of the state treasurer enters into an agreement with an eligible governmental entity for a separately managed account, the agreement must provide for service charges at rates to allow for operation of the program at no cost to the state and for accumulation of reserves the state treasurer deems necessary for the prudent management of the separately managed account. The agreement must at minimum include the payment for services, time periods for investments, and provisions for orderly withdrawal of funds. The state treasurer may promulgate such rules as are deemed necessary for the efficient operation of the separately managed account.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1284-S.SL.pdf?cite=2019%20c%20163%20§%203[2019 c 163 § 3]; ]

== 43.250.190 - Separately managed accounts—Investment of funds by state treasurer—Degree of judgment and care required.
Funds placed in separately managed accounts pursuant to agreements between the office of the state treasurer and eligible governmental entities shall be invested and reinvested by the state treasurer so as to effectively maximize the yield to the separately managed account portfolios. In investing and reinvesting moneys in the separately managed accounts and in acquiring, retaining, managing, and disposing of investments of the separately managed accounts, there shall be exercised the judgment and care under the circumstances then prevailing which persons of prudence, discretion, and intelligence exercise in the management of their own affairs, not in regard to speculation but in regard to the permanent disposition of the funds considering the probable income as well as the probable safety of the capital. The state treasurer shall also consider the public policies of Washington and the values of its citizens when making investment-related decisions.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1284-S.SL.pdf?cite=2019%20c%20163%20§%207[2019 c 163 § 7]; ]

== 43.250.200 - Separately managed accounts—Employment of personnel.
The state treasurer's office is authorized to employ such personnel as are necessary to administer the separately managed accounts. The bond of the state treasurer as required by law shall be made to include the faithful performance of all functions relating to the separately managed accounts.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1284-S.SL.pdf?cite=2019%20c%20163%20§%208[2019 c 163 § 8]; ]

