= 43.376 - Government-to-government relationship with Indian tribes.
:toc:

== 43.376.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Indian tribe" means any federally recognized Indian tribe whose traditional lands and territories included parts of Washington.

. "State agency" means an agency, department, office, or the office of a statewide elected official, of the state of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6175.SL.pdf?cite=2012%20c%20122%20§%201[2012 c 122 § 1]; ]

== 43.376.020 - Government-to-government relationships—State agency duties.
In establishing a government-to-government relationship with Indian tribes, state agencies must:

. Make reasonable efforts to collaborate with Indian tribes in the development of policies, agreements, and program implementation that directly affect Indian tribes and develop a consultation process that is used by the agency for issues involving specific Indian tribes;

. Designate a tribal liaison who reports directly to the head of the state agency;

. Ensure that tribal liaisons who interact with Indian tribes and the executive directors of state agencies receive training as described in RCW 43.376.040; and

. Submit an annual report to the governor on activities of the state agency involving Indian tribes and on implementation of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6175.SL.pdf?cite=2012%20c%20122%20§%202[2012 c 122 § 2]; ]

== 43.376.030 - State agency tribal liaison.
The position of tribal liaison within a state agency is responsible for:

. Assisting the state agency in developing and implementing state and agency policies that promote effective communication and collaboration between the state agency and tribal governments;

. Serving as a contact person with tribal governments and maintaining communication between the state agency and affected tribal governments; and

. Coordinating training of state agency employees in government-to-government relations.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6175.SL.pdf?cite=2012%20c%20122%20§%203[2012 c 122 § 3]; ]

== 43.376.040 - Training requirement.
Training required under RCW 43.376.020 for state agency employees must include at a minimum:

. Effective communication and collaboration between state agencies and Indian tribes;

. Cultural competency in providing effective services to tribal governments and tribal members; and

. Use of training services such as those provided through the governor's office of Indian affairs.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6175.SL.pdf?cite=2012%20c%20122%20§%204[2012 c 122 § 4]; ]

== 43.376.050 - Meetings with statewide elected officials and tribal leaders—List of contact information.
. At least once a year, the governor and other statewide elected officials must meet with leaders of Indian tribes to address issues of mutual concern.

. The governor must maintain for public reference an updated list of the names and contact information for the individuals designated as tribal liaisons and the names and contact information for tribal leadership as submitted by an Indian tribe.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6175.SL.pdf?cite=2012%20c%20122%20§%205[2012 c 122 § 5]; ]

== 43.376.060 - Right of action or right of review not conferred.
Nothing in this chapter creates a right of action against a state agency or a right of review of an action by a state agency.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6175.SL.pdf?cite=2012%20c%20122%20§%206[2012 c 122 § 6]; ]

