= 43.382 - Developmental disabilities ombuds.
:toc:

== 43.382.005 - Developmental disabilities ombuds—Office creation.
. There is created an office of the developmental disabilities ombuds. The department of commerce shall contract with a private, independent nonprofit organization to provide developmental disability ombuds services. The department of commerce shall designate, by a competitive bidding process, the nonprofit organization that will contract to operate the ombuds. The selection process must include consultation of stakeholders in the development of the request for proposals and evaluation of bids. The selected organization must have experience and the capacity to effectively communicate regarding developmental disabilities issues with policymakers, stakeholders, and the general public and must be prepared and able to provide all program and staff support necessary, directly or through subcontracts, to carry out all duties of the office. 

. The contracting organization and its subcontractors, if any, are not state agencies or departments, but instead are private, independent entities operating under contract with the state.

. The governor or state may not revoke the designation of the organization contracted to provide the services of the ombuds except upon a showing of neglect of duty, misconduct, or inability to perform duties.

. The department of commerce shall ensure that the ombuds staff has access to sufficient training or experience with issues relating to persons with developmental disabilities and the program and staff support necessary to enable the ombuds to effectively protect the interests of persons with developmental disabilities. The office of the developmental disabilities ombuds shall have the powers and duties to do the following:

.. Provide information as appropriate on the rights and responsibilities of persons receiving developmental disability [disabilities] administration services or other state services, and on the procedures for providing these services;

.. Investigate, upon its own initiative or upon receipt of a complaint, an administrative act related to a person with developmental disabilities alleged to be contrary to law, rule, or policy, imposed without an adequate statement of reason, or based on irrelevant, immaterial, or erroneous grounds; however, the ombuds may decline to investigate any complaint;

.. Monitor the procedures as established, implemented, and practiced by the department to carry out its responsibilities in the delivery of services to a person with developmental disabilities, with a view toward appropriate preservation of families and ensuring health and safety;

.. Review periodically the facilities and procedures of state institutions which serve persons with developmental disabilities and state-licensed facilities or residences;

.. Recommend changes in the procedures for addressing the needs of persons with developmental disabilities;

.. Submit annually, by November 1st, to the governor and appropriate committees of the legislature a report analyzing the work of the office, including recommendations;

.. Establish procedures to protect the confidentiality of records and sensitive information to ensure that the identity of any complainant or person with developmental disabilities will not be disclosed without the written consent of the complainant or person, or upon court order;

.. Maintain independence and authority within the bounds of the duties prescribed by this chapter, insofar as this independence and authority is exercised in good faith and within the scope of contract; and

.. Carry out such other activities as determined by the department of commerce within the scope of this chapter.

. The developmental disabilities ombuds must consult with stakeholders to develop a plan for future expansion of the ombuds into a model of individual ombuds services akin to the operations of the long-term care ombuds. The developmental disabilities ombuds shall report its progress and recommendations related to this subsection to the governor and appropriate committees of the legislature by November 1, 2019.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6564-S2.SL.pdf?cite=2016%20c%20172%20§%205[2016 c 172 § 5]; ]

== 43.382.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Administration" means the developmental disabilities administration of the department of social and health services.

. "Department" means the department of social and health services.

. "Ombuds" means the office of the developmental disabilities ombuds.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6564-S2.SL.pdf?cite=2016%20c%20172%20§%206[2016 c 172 § 6]; ]

== 43.382.020 - Memoranda of agreement—Authority—Overlap with other agencies.
The ombuds shall collaborate and have a memoranda of agreement with the office of the state long-term care ombuds, the office of the family and children's ombuds, Washington protection and advocacy system, the mental health ombuds, and the office of the education ombuds to clarify authority in those situations where their mandates overlap.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6564-S2.SL.pdf?cite=2016%20c%20172%20§%207[2016 c 172 § 7]; ]

== 43.382.030 - Developmental disabilities ombuds—Prohibited acts.
. A developmental disabilities ombuds shall not have participated in the paid provision of services to any person with developmental disabilities within the past year.

. A developmental disabilities ombuds shall not have been employed in a governmental position with direct involvement in the licensing, certification, or regulation of a paid developmental disabilities service provider within the past year.

. No developmental disabilities ombuds or any member of his or her immediate family may have, or have had within the past year, any significant ownership or investment interest in a paid provider of services to persons with developmental disabilities.

. A developmental disabilities ombuds shall not be assigned to investigate a facility or provider of services which provides care or services to a member of that ombuds' immediate family.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6564-S2.SL.pdf?cite=2016%20c%20172%20§%208[2016 c 172 § 8]; ]

== 43.382.040 - Confidentiality—Public disclosure exemption.
The ombuds shall treat all matters under investigation, including the identities of service recipients, complainants, and individuals from whom information is acquired, as confidential, except as far as disclosures may be necessary to enable the ombuds to perform the duties of the office and to support any recommendations resulting from an investigation. Upon receipt of information that by law is confidential or privileged, the ombuds shall maintain the confidentiality of such information and shall not further disclose or disseminate the information except as provided by applicable state or federal law. Investigative records of the office of the ombuds are confidential and are exempt from public disclosure under chapter 42.56 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6564-S2.SL.pdf?cite=2016%20c%20172%20§%209[2016 c 172 § 9]; ]

== 43.382.050 - Identifying information—Disclosure.
. Identifying information about complainants or witnesses is not subject to any method of legal compulsion and may not be revealed to the legislature or the governor except under the following circumstances: (a) The complainant or witness waives confidentiality; (b) under a legislative subpoena when there is a legislative investigation for neglect of duty or misconduct by the ombuds or ombuds' office when the identifying information is necessary to the investigation of the ombuds' acts; or (c) under an investigation or inquiry by the governor as to neglect of duty or misconduct by the ombuds or ombuds' office when the identifying information is necessary to the investigation of the ombuds' acts. Consistently with this section, the ombuds must act to protect sensitive client information.

. For the purposes of this section, "identifying information" includes the complainant's or witness's name, location, telephone number, likeness, social security number or other identification number, or identification of immediate family members.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6564-S2.SL.pdf?cite=2016%20c%20172%20§%2010[2016 c 172 § 10]; ]

== 43.382.060 - Privilege—Exceptions.
The privilege described in RCW 43.382.050 does not apply when:

. The ombuds or ombuds' staff member has direct knowledge of an alleged crime, and the testimony, evidence, or discovery sought is relevant to that allegation;

. The ombuds or a member of the ombuds' staff has received a threat of, or becomes aware of a risk of, imminent serious harm to any person, and the testimony, evidence, or discovery sought is relevant to that threat or risk; or

. The ombuds has been asked to provide general information regarding the general operation of, or the general processes employed at, the ombuds' office.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6564-S2.SL.pdf?cite=2016%20c%20172%20§%2011[2016 c 172 § 11]; ]

== 43.382.070 - Immunity from liability.
. An employee of the office of the developmental disabilities ombuds is not liable for good faith performance of responsibilities under this chapter.

. No discriminatory, disciplinary, or retaliatory action may be taken against an employee of the department, an employee of the department of commerce, an employee of a contracting agency of the department, a provider of developmental disabilities services, or a recipient of department services for any communication made, or information given or disclosed, to aid the office of the developmental disabilities ombuds in carrying out its responsibilities, unless the communication or information is made, given, or disclosed maliciously or without good faith. This subsection is not intended to infringe on the rights of the employer to supervise, discipline, or terminate an employee for other reasons.

. All communications by an ombuds, if reasonably related to the requirements of that individual's responsibilities under this chapter and done in good faith, are privileged and that privilege serves as a defense in any action in libel or slander.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6564-S2.SL.pdf?cite=2016%20c%20172%20§%2012[2016 c 172 § 12]; ]

== 43.382.080 - Mandatory reporting—Behavior warranting criminal or disciplinary proceedings.
When the ombuds or ombuds' staff member has reasonable cause to believe that any public official, employee, or other person has acted in a manner warranting criminal or disciplinary proceedings, the ombuds or ombuds' staff member shall report the matter, or cause a report to be made, to the appropriate authorities.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6564-S2.SL.pdf?cite=2016%20c%20172%20§%2013[2016 c 172 § 13]; ]

== 43.382.090 - Department of social and health services—Department of health—Duties.
The department and the department of health shall:

. Allow the ombuds or the ombuds' designee to communicate privately with any person receiving services from the department, or any person who is part of a fatality or near fatality investigation involving a person with developmental disabilities, for the purposes of carrying out its duties under this chapter;

. Permit the ombuds or the ombuds' designee physical access to state institutions serving persons with developmental disabilities and information in the possession of the department concerning state-licensed facilities or residences for the purpose of carrying out its duties under this chapter;

. Upon the ombuds' request, grant the ombuds or the ombuds' designee the right to access, inspect, and copy all relevant information, records, or documents in the possession or control of the department or the department of health that the ombuds considers necessary in an investigation.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6564-S2.SL.pdf?cite=2016%20c%20172%20§%2014[2016 c 172 § 14]; ]

