= 43.329 - Skilled worker outreach, recruitment, and career awareness grant program.
:toc:

== 43.329.010 - Definitions. (Expires July 1, 2022.)
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Department" means the department of commerce.

. "Eligible applicant" means any government entity or any nongovernment entity, association, or organization that is not a private vocational school, that:

.. Offers, or plans to offer, a skilled worker awareness program; and

.. Has partnered with industry to either offer or fund a skilled worker awareness program.

. "Grant program" means the skilled worker outreach, recruitment, and career awareness grant program.

. "Grant review committee" means the skilled worker outreach, recruitment, and career awareness grant program review committee created in RCW 43.329.050.

. "Matching grant" means a grant funded by the state to match funding provided by an eligible applicant to support efforts to increase the state's skilled workforce.

. "Skilled worker awareness program" means a program designed to increase awareness of, and enrollment in, accredited educational, occupational, state-approved preapprenticeship, apprenticeship, and similar training programs that: (a) Train individuals to perform skills needed in the workforce; and (b) award industry or state-recognized certificates, credentials, associate degrees, professional licenses, or similar evidence of achievement but not including bachelor's or higher degrees.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=2017%20c%20225%20§%201[2017 c 225 § 1]; ]

== 43.329.020 - Skilled worker outreach, recruitment, and career awareness grant program. (Expires July 1, 2022.)
. Subject to availability of amounts appropriated for this specific purpose, the skilled worker outreach, recruitment, and career awareness grant program is created. The purpose of the grant program is to increase the state's skilled workforce by raising awareness of the state's worker training programs.

. [Empty]
.. Under the grant program, the department must award matching grants to eligible applicants that will engage in outreach and recruiting efforts to increase enrollment in and completion of worker training programs.

.. Recipients of the grant must provide matching cash funding. The recipient's match must be two dollars for each one dollar of the grant. The recipient's match may not be in the form of in-kind contributions.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=2017%20c%20225%20§%202[2017 c 225 § 2]; ]

== 43.329.030 - Program administration—Grant applications. (Expires July 1, 2022.)
. The department shall administer the grant program and establish a process for accepting grant applications, including application guidelines and deadlines.

. By January 1, 2018, and annually no later than January 1st thereafter, the department shall start accepting grant applications.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=2017%20c%20225%20§%203[2017 c 225 § 3]; ]

== 43.329.040 - Matching grants—Eligibility—Transmittal to grant review committee for consideration. (Expires July 1, 2022.)
. To be considered for a matching grant, an eligible applicant must include, at a minimum, the following information in its application:

.. A description of how the matching grant will be used to provide outreach, education, and recruitment for training programs;

.. A description of the training programs the applicant plans to promote, the particular skills taught by that training program, and the number of years the training program has been in operation;

.. Past, current, and projected enrollment in the training program the applicant plans to promote and the estimated increases in enrollment, if the training program has been in existence;

.. If the applicant is promoting an existing training program, a comparison of the number of participants who enroll in the training program and the number of participants who complete the program over a five-year period, if available;

.. Specific industry needs or gaps in the workforce that the training program will or does address;

.. A description of intended or existing partnerships with industry members, including those where training program participants will have the opportunity to earn income or credit hours;

.. Costs or the anticipated costs to implement the skilled worker awareness program;

.. Resources that the eligible applicant will commit in matching dollars and, if the applicant already has a skilled worker awareness program, existing resources that the applicant has invested in recruiting, outreach, and funding of its skilled worker awareness program; and

.. Any other information the department requires.

. Upon receipt of an application that satisfies the requirements in this section, the department must send the application to the grant review committee for its consideration.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=2017%20c%20225%20§%204[2017 c 225 § 4]; ]

== 43.329.050 - Grant review committee—Criteria for awarding matching grants—Award of matching grants by department. (Expires July 1, 2022.)
. The department must establish a grant review committee to review grant applications and make recommendations on who should receive a matching grant and the amount. The grant review committee must consist of eleven members with representatives from the following:

.. The department of labor and industries;

.. The employment security department;

.. The department of enterprise services;

.. The workforce training and education coordinating board;

.. The state board for community and technical colleges;

.. Two representatives from business;

.. Two representatives from labor; and

.. Two representatives from the Washington apprenticeship and training council.

. The grant review committee shall designate a chair to oversee the committee's meetings.

. The grant review committee shall establish criteria for ranking eligible applicants for matching grant awards. The grant review committee shall consider and rank eligible applicants based on which applicants currently are able to or have the best potential to:

.. Reach a broad diverse audience, including populations with barriers as identified in the state's comprehensive workforce training and education plan, through their recruitment and outreach efforts;

.. Collaborate with and utilize centers of excellence within the community and technical college system;

.. Significantly increase enrollment and completion of the training program the applicant plans to promote;

.. Fill existing needs for skilled workers in the market; and

.. Demonstrate the following, prioritized in the following order:

... That the eligible applicant will provide monetary contributions from its own resources; and

... That the eligible applicant has secured:

(A) An industry partner; or

(B) Monetary contributions from an industry partner, conditional job placement guarantees, or articulation agreements.

. The grant review committee shall submit its recommendations to the director of the department, who shall determine to whom and in what amounts to award matching grants. Matching grants must be awarded no later than April 1st each year following the application submittal deadline.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=2017%20c%20225%20§%205[2017 c 225 § 5]; ]

== 43.329.060 - Matching grants—Restrictions. (Expires July 1, 2022.)
Grant recipients may not use matching grants for tuition subsidies or to reduce tuition for any training program.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=2017%20c%20225%20§%206[2017 c 225 § 6]; ]

== 43.329.070 - Grant recipient reporting—Reports by grant review committee. (Expires July 1, 2022.)
. Each eligible applicant that receives a matching grant shall submit a quarterly report and an annual report to the grant review committee on the outcomes achieved. The grant recipient shall include in the report at least the following measurable outcomes:

.. The manner in which the grant recipient has used the matching grant for outreach and recruitment;

.. The number of participants enrolled in and the number of participants who completed the training program being promoted, both before the matching grant was awarded and since the matching grant was received;

.. The number of participants who obtained employment in an industry for which the participant was trained under the training program promoted by the recipient, including information about the industry in which the participants are employed;

.. The number of participants recruited; and

.. Any other information the grant review committee determines appropriate.

. By December 1, 2019, and by each December 1st thereafter, the grant review committee shall submit an annual report to the governor and appropriate committees of the legislature in accordance with the reporting requirements in RCW 43.01.036. The report must include:

.. The number of matching grants awarded in the prior year, including the amount, recipient, and duration of each matching grant;

.. The number of individuals who enrolled in and completed training programs promoted by each grant recipient;

.. The number of individuals who obtained employment in a position that uses the skills for which they were trained through a training program promoted by a grant recipient; and

.. Other information obtained from grant recipients' reports under subsection (1) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=2017%20c%20225%20§%207[2017 c 225 § 7]; ]

== 43.329.080 - Coordination with workforce training and education coordinating board and workforce training customer advisory committee. (Expires July 1, 2022.)
To assist with implementation of the grant program, the department, in coordination with the workforce training and education coordinating board and the workforce training customer advisory committee, shall coordinate skilled worker awareness programs throughout the state. The coordination must include:

. Partnering with industry associations, labor-management programs, and businesses to assess and determine their workforce needs; and

. Coordinating with training program providers on skill sets being developed and the quality of students being trained.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=2017%20c%20225%20§%208[2017 c 225 § 8]; ]

== 43.329.090 - Skilled worker outreach, recruitment, and career awareness grant program account. (Expires July 1, 2022.)
The skilled worker outreach, recruitment, and career awareness grant program account is created in the custody of the state treasurer. The department shall deposit in the account all money received for the program. The account shall be self-sustaining and consist of funds appropriated by the legislature for the skilled worker outreach, recruitment, and career awareness grant program and private contributions to the program. Expenditures from the account shall only be used for matching grants provided to grant recipients. Only the director of the department or the director's designee may authorize expenditures from the account. The account is subject to the allotment procedures under chapter 43.88 RCW, but an appropriation is not required for expenditures.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=2017%20c%20225%20§%209[2017 c 225 § 9]; ]

== 43.329.900 - Expiration of chapter.
This chapter expires July 1, 2022.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5713-S.SL.pdf?cite=2017%20c%20225%20§%2010[2017 c 225 § 10]; ]

