= 43.330A - Office of firearm safety and violence prevention.
:toc:

== 43.330A.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Department" means the department of commerce.

. "Office" means the Washington office of firearm safety and violence prevention.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6288-S.SL.pdf?cite=2020%20c%20313%20§%202[2020 c 313 § 2]; ]

== 43.330A.020 - Created—Duties—Reports.
. The Washington office of firearm safety and violence prevention is created within the department for the purposes of coordinating and promoting effective state and local efforts to reduce firearm violence.

. The duties of the office include, but are not limited to:

.. Working with law enforcement agencies, county prosecutors, researchers, and public health agencies throughout the state to identify and improve upon available data sources, data collection methods, and data-sharing mechanisms. The office will also identify gaps in available data needed for ongoing analysis, policy development, and the implementation of evidence-based firearm violence intervention and prevention strategies;

.. Researching, identifying, and recommending legislative policy options to promote the implementation of statewide evidence-based firearm violence intervention and prevention strategies;

.. Researching, identifying, and applying for nonstate funding to aid in the research, analysis, and implementation of statewide firearm violence intervention and prevention strategies;

.. Working with the office of crime victim[s] advocacy to identify opportunities to better support victims of firearm violence, a population that is currently underrepresented among recipients of victim services;

.. Contract [Contracting] for a statewide helpline, counseling, and referral services for victims, friends, and family members impacted by gun violence and community professionals and providers who engage with them;

.. Contract [Contracting] with the University of Washington to develop a best practice guide for therapy for gun violence victims;

.. Administering the Washington firearm violence intervention and prevention grant program as outlined in RCW 43.330A.050.

. The office shall report to the appropriate legislative policy committees by December 1st every odd-numbered year on its progress and findings in analyzing data, developing strategies to prevent firearm violence, and recommendations for additional legislative policy options. The first report must be submitted by December 1, 2021.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6288-S.SL.pdf?cite=2020%20c%20313%20§%203[2020 c 313 § 3]; ]

== 43.330A.030 - Statewide helpline, counseling, and referral service.
Subject to the availability of amounts appropriated for this specific purpose, the office shall contract with a level one trauma center in the state of Washington to provide a statewide helpline, counseling, and referral service for victims, friends, and family members impacted by gun violence and community professionals, legal practitioners, health providers, and others who engage with them. The service must be developed in consultation with the office of crime victims advocacy established in RCW 43.280.080, and include the opportunity for brief clinical encounters, problem solving, and referral to the best statewide resources available to meet their needs. The service must become conversant with providers across the state that are trained in evidence-based trauma therapy and establish relationships to ensure specific knowledge of available resources. The office of crime victims advocacy established in RCW 43.280.080 must provide consultation within existing resources.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6288-S.SL.pdf?cite=2020%20c%20313%20§%204[2020 c 313 § 4]; ]

== 43.330A.040 - Best practice guide for therapy for gun violence victims.
The office shall contract with the University of Washington department of psychiatry and behavioral sciences to develop a best practice guide for therapy for gun violence victims in collaboration with the Harborview center for sexual assault and traumatic stress. The guide must summarize the state of the knowledge in this area and provide recommendations for areas of focus and action that are meaningful and practical for different constituencies. The guide must be made available to the public online and disseminated across the state to appropriate entities including but not limited to medical examiner's offices, prosecuting attorneys, level one and level two trauma centers, and victim support organizations.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6288-S.SL.pdf?cite=2020%20c%20313%20§%205[2020 c 313 § 5]; ]

== 43.330A.050 - Firearm violence intervention and prevention grant program.
. The Washington firearm violence intervention and prevention grant program is created to be administered by the office. The purpose of the program is to improve public health and safety by supporting effective firearm violence reduction initiatives in communities that are disproportionately affected by firearm violence including suicides.

. Program grants shall be used to support, expand, and replicate evidence-based violence reduction initiatives, including hospital-based violence intervention programs, evidence-based street outreach programs, and focused deterrence strategies, that seek to interrupt the cycles of violence, victimization, and retaliation in order to reduce the incidence of firearm violence. These initiatives must be primarily focused on providing violence intervention services to the small segment of the population that is identified as having the highest risk of perpetrating or being victimized by firearm violence.

. Program grants shall be made on a competitive basis to cities that are disproportionately impacted by violence, to law enforcement agencies in those cities, and to community-based organizations that serve the residents of those cities. Where appropriate, two or more cities may submit joint applications to better address regional problems.

. An applicant for a program grant shall submit a proposal, in a form prescribed by the office, which must include, but not be limited to, all of the following:

.. Clearly defined and measurable objectives for the grant;

.. A statement describing how the applicant proposes to use the grant to implement an evidence-based firearm violence reduction initiative in accordance with this section;

.. A statement describing how the applicant proposes to use the grant to enhance coordination of existing violence prevention and intervention programs and minimize duplication of services; and

.. Evidence indicating that the proposed firearm violence reduction initiative would likely reduce the incidence of firearm violence.

. In awarding program grants, the office shall give preference to applicants whose grant proposals demonstrate the greatest likelihood of reducing firearm violence in the applicant's community, without contributing to mass incarceration.

. Each city that receives a program grant shall distribute no less than fifty percent of the grant funds to one or more of any of the following types of entities:

.. Community-based organizations;

.. Indian tribes and tribal organizations; and

.. Public agencies or departments that are primarily dedicated to community safety or firearm violence prevention.

. The office shall form a grant selection advisory committee including, without limitation, persons who have been impacted by violence, formerly incarcerated persons, and persons with direct experience in implementing evidence-based violence reduction initiatives, including initiatives that incorporate public health and community-based approaches.

. Each grantee shall report to the office, in a form and at intervals prescribed by the office, the grantee's progress in achieving the grant objectives.

. The office may contract with an independent entity with expertise in evaluating community-based grant-funded programs to evaluate the grant program's effectiveness.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6288-S.SL.pdf?cite=2020%20c%20313%20§%206[2020 c 313 § 6]; ]

