= 43.310 - Youth gangs.
:toc:

== 43.310.005 - Finding.
The legislature finds and declares that:

. The number of youth who are members and associates of gangs and commit gang violence has significantly increased throughout the entire greater Puget Sound, Spokane, and other areas of the state;

. Youth gang violence has caused a tremendous strain on the progress of the communities impacted. The loss of life, property, and positive opportunity for growth caused by youth gang violence has reached intolerable levels. Increased youth gang activity has seriously strained the budgets of many local jurisdictions, as well as threatened the ability of the educational system to educate our youth;

. Among youth gang members the high school dropout rate is significantly higher than among nongang members. Since the economic future of our state depends on a highly educated and skilled workforce, this high school dropout rate threatens the economic welfare of our future workforce, as well as the future economic growth of our state;

. The unemployment rate among youth gang members is higher than that among the general youth population. The unusual unemployment rate, lack of education and skills, and the increased criminal activity could significantly impact our future prison population;

. Most youth gangs are subcultural. This implies that gangs provide the nurturing, discipline, and guidance to gang youth and potential gang youth that is generally provided by communities and other social systems. The subcultural designation means that youth gang participation and violence can be effectively reduced in Washington communities and schools through the involvement of community, educational, criminal justice, and employment systems working in a unified manner with parents and individuals who have a firsthand knowledge of youth gangs and at-risk youth; and

. A strong unified effort among parents and community, educational, criminal justice, and employment systems would facilitate: (a) The learning process; (b) the control and reduction of gang violence; (c) the prevention of youth joining negative gangs; and (d) the intervention into youth gangs.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1333-S.SL.pdf?cite=1993%20c%20497%20§%201[1993 c 497 § 1]; ]

== 43.310.007 - Intent—Prevention and intervention pilot programs.
It is the intent of the legislature to cause the development of positive prevention and intervention pilot programs for elementary and secondary age youth through cooperation between individual schools, local organizations, and government. It is also the intent of the legislature that if the prevention and intervention pilot programs are determined to be effective in reducing problems associated with youth gang violence, that other counties in the state be eligible to receive special state funding to establish similar positive prevention and intervention programs.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1333-S.SL.pdf?cite=1993%20c%20497%20§%202[1993 c 497 § 2]; ]

== 43.310.010 - Definitions.
Unless the context otherwise requires, the following definitions shall apply throughout RCW 43.310.005 through 43.310.040 and *sections 5 and 7 through 10, chapter 497, Laws of 1993:

. "School" means any public school within a school district any portion of which is in a county with a population of over one hundred ninety thousand.

. "Community organization" means any organization recognized by a city or county as such, as well as private, nonprofit organizations registered with the secretary of state.

. "Gang risk prevention and intervention pilot program" means a community-based positive prevention and intervention program for gang members, potential gang members, at-risk youth, and elementary through high school-aged youth directed at all of the following:

.. Reducing the probability of youth involvement in gang activities and consequent violence.

.. Establishing ties, at an early age, between youth and community organizations.

.. Committing local business and community resources to positive programming for youth.

.. Committing state resources to assist in creating the gang risk prevention and intervention pilot programs.

. "Cultural awareness retreat" means a program that temporarily relocates at-risk youth or gang members and their parents from their usual social environment to a different social environment, with the specific purpose of having them performing activities which will enhance or increase their positive behavior and potential life successes.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1333-S.SL.pdf?cite=1993%20c%20497%20§%203[1993 c 497 § 3]; ]

== 43.310.020 - Gang risk prevention and intervention pilot programs—Request for proposals.
. The *department of community, trade, and economic development may recommend existing programs or contract with either school districts or community organizations, or both, through a request for proposal process for the development, administration, and implementation in the county of community-based gang risk prevention and intervention pilot programs.

. Proposals by the school district for gang risk prevention and intervention pilot program grant funding shall begin with school years no sooner than the 1994-95 session, and last for a duration of two years.

. The school district or community organization proposal shall include:

.. A description of the program goals, activities, and curriculum. The description of the program goals shall include a list of measurable objectives for the purpose of evaluation by the *department of community, trade, and economic development. To the extent possible, proposals shall contain empirical data on current problems, such as dropout rates and occurrences of violence on and off campus by school-age individuals.

.. A description of the individual school or schools and the geographic area to be affected by the program.

.. A demonstration of broad-based support for the program from business and community organizations.

.. A clear description of the experience, expertise, and other qualifications of the community organizations to conduct an effective prevention and intervention program in cooperation with a school or a group of schools.

.. A proposed budget for expenditure of the grant.

. Grants awarded under this section may not be used for the administrative costs of the school district or the individual school.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%20116[1995 c 399 § 116]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1333-S.SL.pdf?cite=1993%20c%20497%20§%204[1993 c 497 § 4]; ]

== 43.310.030 - Gang risk prevention and intervention pilot programs—Scope.
Gang risk prevention and intervention pilot programs shall include, but are not limited to:

. Counseling for targeted at-risk students, parents, and families, individually and collectively.

. Exposure to positive sports and cultural activities, promoting affiliations between youth and the local community.

. Job training, which may include apprentice programs in coordination with local businesses, job skills development at the school, or information about vocational opportunities in the community.

. Positive interaction with local law enforcement personnel.

. The use of local organizations to provide job search training skills.

. Cultural awareness retreats.

. The use of specified state resources, as requested.

. Full service schools under *section 9 of this act.

. Community service such as volunteerism and citizenship.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1333-S.SL.pdf?cite=1993%20c%20497%20§%206[1993 c 497 § 6]; ]

== 43.310.040 - Cultural awareness retreats.
Cultural awareness retreats shall include but are not limited to the following programs:

. To develop positive attitudes and self-esteem.

. To develop youth decision-making ability.

. To assist with career development and educational development.

. To help develop respect for the community, and ethnic origin.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1333-S.SL.pdf?cite=1993%20c%20497%20§%2011[1993 c 497 § 11]; ]

