= 43.386 - Facial recognition.
:toc:

== 43.386.010 - Definitions. (Effective July 1, 2021.)
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Accountability report" means a report developed in accordance with RCW 43.386.020.

. "Enroll," "enrolled," or "enrolling" means the process by which a facial recognition service creates a facial template from one or more images of an individual and adds the facial template to a gallery used by the facial recognition service for recognition or persistent tracking of individuals. It also includes the act of adding an existing facial template directly into a gallery used by a facial recognition service.

. [Empty]
.. "Facial recognition service" means technology that analyzes facial features and is used by a state or local government agency for the identification, verification, or persistent tracking of individuals in still or video images.

.. "Facial recognition service" does not include: (i) The analysis of facial features to grant or deny access to an electronic device; or (ii) the use of an automated or semiautomated process for the purpose of redacting a recording for release or disclosure outside the law enforcement agency to protect the privacy of a subject depicted in the recording, if the process does not generate or result in the retention of any biometric data or surveillance information.

. "Facial template" means the machine-interpretable pattern of facial features that is extracted from one or more images of an individual by a facial recognition service.

. "Identification" means the use of a facial recognition service by a state or local government agency to determine whether an unknown individual matches any individual whose identity is known to the state or local government agency and who has been enrolled by reference to that identity in a gallery used by the facial recognition service.

. "Legislative authority" means the respective city, county, or other local governmental agency's council, commission, or other body in which legislative powers are vested. For a port district, the legislative authority refers to the port district's port commission. For an airport established pursuant to chapter 14.08 RCW and operated by a board, the legislative authority refers to the airport's board. For a state agency, "legislative authority" refers to the technology services board created in RCW 43.105.285.

. "Meaningful human review" means review or oversight by one or more individuals who are trained in accordance with RCW 43.386.060 and who have the authority to alter the decision under review.

. "Nonidentifying demographic data" means data that is not linked or reasonably linkable to an identified or identifiable individual, and includes, at a minimum, information about gender, race or ethnicity, age, and location.

. "Ongoing surveillance" means using a facial recognition service to track the physical movements of a specified individual through one or more public places over time, whether in real time or through application of a facial recognition service to historical records. It does not include a single recognition or attempted recognition of an individual, if no attempt is made to subsequently track that individual's movement over time after they have been recognized.

. "Persistent tracking" means the use of a facial recognition service by a state or local government agency to track the movements of an individual on a persistent basis without identification or verification of that individual. Such tracking becomes persistent as soon as:

.. The facial template that permits the tracking is maintained for more than forty-eight hours after first enrolling that template; or

.. Data created by the facial recognition service is linked to any other data such that the individual who has been tracked is identified or identifiable.

. "Recognition" means the use of a facial recognition service by a state or local government agency to determine whether an unknown individual matches:

.. Any individual who has been enrolled in a gallery used by the facial recognition service; or

.. A specific individual who has been enrolled in a gallery used by the facial recognition service.

. "Verification" means the use of a facial recognition service by a state or local government agency to determine whether an individual is a specific individual whose identity is known to the state or local government agency and who has been enrolled by reference to that identity in a gallery used by the facial recognition service.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6280-S.SL.pdf?cite=2020%20c%20257%20§%202[2020 c 257 § 2]; ]

== 43.386.020 - Notice of intent—Accountability report. (Effective July 1, 2021.)
. A state or local government agency using or intending to develop, procure, or use a facial recognition service must file with a legislative authority a notice of intent to develop, procure, or use a facial recognition service and specify a purpose for which the technology is to be used. A state or local government agency may commence the accountability report once it files the notice of intent by the legislative authority.

. Prior to developing, procuring, or using a facial recognition service, a state or local government agency must produce an accountability report for that service. Each accountability report must include, at minimum, clear and understandable statements of the following:

.. [Empty]
... The name of the facial recognition service, vendor, and version; and (ii) a description of its general capabilities and limitations, including reasonably foreseeable capabilities outside the scope of the proposed use of the agency;

.. [Empty]
... The type or types of data inputs that the technology uses; (ii) how that data is generated, collected, and processed; and (iii) the type or types of data the system is reasonably likely to generate;

.. [Empty]
... A description of the purpose and proposed use of the facial recognition service, including what decision or decisions will be used to make or support it; (ii) whether it is a final or support decision system; and (iii) its intended benefits, including any data or research demonstrating those benefits;

.. A clear use and data management policy, including protocols for the following:

... How and when the facial recognition service will be deployed or used and by whom including, but not limited to, the factors that will be used to determine where, when, and how the technology is deployed, and other relevant information, such as whether the technology will be operated continuously or used only under specific circumstances. If the facial recognition service will be operated or used by another entity on the agency's behalf, the facial recognition service accountability report must explicitly include a description of the other entity's access and any applicable protocols;

... Any measures taken to minimize inadvertent collection of additional data beyond the amount necessary for the specific purpose or purposes for which the facial recognition service will be used;

... Data integrity and retention policies applicable to the data collected using the facial recognition service, including how the agency will maintain and update records used in connection with the service, how long the agency will keep the data, and the processes by which data will be deleted;

... Any additional rules that will govern use of the facial recognition service and what processes will be required prior to each use of the facial recognition service;

.. Data security measures applicable to the facial recognition service including how data collected using the facial recognition service will be securely stored and accessed, if and why an agency intends to share access to the facial recognition service or the data from that facial recognition service with any other entity, and the rules and procedures by which an agency sharing data with any other entity will ensure that such entities comply with the sharing agency's use and data management policy as part of the data sharing agreement;

.. How the facial recognition service provider intends to fulfill security breach notification requirements pursuant to chapter 19.255 RCW and how the agency intends to fulfill security breach notification requirements pursuant to RCW 42.56.590; and

.. The agency's training procedures, including those implemented in accordance with RCW 43.386.060, and how the agency will ensure that all personnel who operate the facial recognition service or access its data are knowledgeable about and able to ensure compliance with the use and data management policy prior to use of the facial recognition service;

.. The agency's testing procedures, including its processes for periodically undertaking operational tests of the facial recognition service in accordance with RCW 43.386.040;

.. Information on the facial recognition service's rate of false matches, potential impacts on protected subpopulations, and how the agency will address error rates, determined independently, greater than one percent;

.. A description of any potential impacts of the facial recognition service on civil rights and liberties, including potential impacts to privacy and potential disparate impacts on marginalized communities, and the specific steps the agency will take to mitigate the potential impacts and prevent unauthorized use of the facial recognition service; and

.. The agency's procedures for receiving feedback, including the channels for receiving feedback from individuals affected by the use of the facial recognition service and from the community at large, as well as the procedures for responding to feedback.

. Prior to finalizing the accountability report, the agency must:

.. Allow for a public review and comment period;

.. Hold at least three community consultation meetings; and

.. Consider the issues raised by the public through the public review and comment period and the community consultation meetings.

. The final accountability report must be updated every two years and submitted to a legislative authority.

. The final adopted accountability report must be clearly communicated to the public at least ninety days prior to the agency putting the facial recognition service into operational use, posted on the agency's public web site, and submitted to a legislative authority. The legislative authority must post each submitted accountability report on its public web site.

. A state or local government agency seeking to procure a facial recognition service must require vendors to disclose any complaints or reports of bias regarding the service.

. An agency seeking to use a facial recognition service for a purpose not disclosed in the agency's existing accountability report must first seek public comment and community consultation on the proposed new use and adopt an updated accountability report pursuant to the requirements contained in this section.

. This section does not apply to a facial recognition service under contract as of July 1, 2021. An agency must fulfill the requirements of this section upon renewal or extension of the contract.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6280-S.SL.pdf?cite=2020%20c%20257%20§%203[2020 c 257 § 3]; ]

== 43.386.030 - Meaningful human review—When required. (Effective July 1, 2021.)
A state or local government agency using a facial recognition service to make decisions that produce legal effects concerning individuals or similarly significant effects concerning individuals must ensure that those decisions are subject to meaningful human review. Decisions that produce legal effects concerning individuals or similarly significant effects concerning individuals means decisions that result in the provision or denial of financial and lending services, housing, insurance, education enrollment, criminal justice, employment opportunities, health care services, or access to basic necessities such as food and water, or that impact civil rights of individuals.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6280-S.SL.pdf?cite=2020%20c%20257%20§%204[2020 c 257 § 4]; ]

== 43.386.040 - Testing—When required. (Effective July 1, 2021.)
Prior to deploying a facial recognition service in the context in which it will be used, a state or local government agency using a facial recognition service to make decisions that produce legal effects on individuals or similarly significant effects on individuals must test the facial recognition service in operational conditions. An agency must take reasonable steps to ensure best quality results by following all guidance provided by the developer of the facial recognition service.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6280-S.SL.pdf?cite=2020%20c%20257%20§%205[2020 c 257 § 5]; ]

== 43.386.050 - Performance differences across subpopulations—Testing and mitigation. (Effective July 1, 2021.)
. [Empty]
.. A state or local government agency that deploys a facial recognition service must require a facial recognition service provider to make available an application programming interface or other technical capability, chosen by the provider, to enable legitimate, independent, and reasonable tests of those facial recognition services for accuracy and unfair performance differences across distinct subpopulations. Such subpopulations are defined by visually detectable characteristics such as: (i) Race, skin tone, ethnicity, gender, age, or disability status; or (ii) other protected characteristics that are objectively determinable or self-identified by the individuals portrayed in the testing dataset. If the results of the independent testing identify material unfair performance differences across subpopulations, the provider must develop and implement a plan to mitigate the identified performance differences within ninety days of receipt of such results. For purposes of mitigating the identified performance differences, the methodology and data used in the independent testing must be disclosed to the provider in a manner that allows full reproduction.

.. Making an application programming interface or other technical capability does not require providers to do so in a manner that would increase the risk of cyberattacks or to disclose proprietary data. Providers bear the burden of minimizing these risks when making an application programming interface or other technical capability available for testing.

. Nothing in this section requires a state or local government agency to collect or provide data to a facial recognition service provider to satisfy the requirements in subsection (1) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6280-S.SL.pdf?cite=2020%20c%20257%20§%206[2020 c 257 § 6]; ]

== 43.386.060 - Training. (Effective July 1, 2021.)
A state or local government agency using a facial recognition service must conduct periodic training of all individuals who operate a facial recognition service or who process personal data obtained from the use of a facial recognition service. The training must include, but not be limited to, coverage of:

. The capabilities and limitations of the facial recognition service;

. Procedures to interpret and act on the output of the facial recognition service; and

. To the extent applicable to the deployment context, the meaningful human review requirement for decisions that produce legal effects concerning individuals or similarly significant effects concerning individuals.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6280-S.SL.pdf?cite=2020%20c%20257%20§%207[2020 c 257 § 7]; ]

== 43.386.070 - Disclosure to criminal defendants—Retention of records—Reporting of surveillance warrants. (Effective July 1, 2021.)
. A state or local government agency must disclose their use of a facial recognition service on a criminal defendant to that defendant in a timely manner prior to trial.

. A state or local government agency using a facial recognition service shall maintain records of its use of the service that are sufficient to facilitate public reporting and auditing of compliance with the agency's facial recognition policies.

. In January of each year, any judge who has issued a warrant for the use of a facial recognition service to engage in any surveillance, or an extension thereof, as described in RCW 43.386.080, that expired during the preceding year, or who has denied approval of such a warrant during that year shall report to the administrator for the courts:

.. The fact that a warrant or extension was applied for;

.. The fact that the warrant or extension was granted as applied for, was modified, or was denied;

.. The period of surveillance authorized by the warrant and the number and duration of any extensions of the warrant;

.. The identity of the applying investigative or law enforcement officer and agency making the application and the person authorizing the application; and

.. The nature of the public spaces where the surveillance was conducted.

. In January of each year, any state or local government agency that has applied for a warrant, or an extension thereof, for the use of a facial recognition service to engage in any surveillance as described in RCW 43.386.080 shall provide to a legislative authority a report summarizing nonidentifying demographic data of individuals named in warrant applications as subjects of surveillance with the use of a facial recognition service.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6280-S.SL.pdf?cite=2020%20c%20257%20§%208[2020 c 257 § 8]; ]

== 43.386.080 - Use for surveillance, real-time identification, or persistent tracking—When permitted—Restrictions on law enforcement use. (Effective July 1, 2021.)
. A state or local government agency may not use a facial recognition service to engage in ongoing surveillance, conduct real-time or near real-time identification, or start persistent tracking unless:

.. A warrant is obtained authorizing the use of the service for those purposes;

.. Exigent circumstances exist; or

.. A court order is obtained authorizing the use of the service for the sole purpose of locating or identifying a missing person, or identifying a deceased person. A court may issue an ex parte order under this subsection (1)(c) if a law enforcement officer certifies and the court finds that the information likely to be obtained is relevant to locating or identifying a missing person, or identifying a deceased person.

. A state or local government agency may not apply a facial recognition service to any individual based on their religious, political, or social views or activities, participation in a particular noncriminal organization or lawful event, or actual or perceived race, ethnicity, citizenship, place of origin, immigration status, age, disability, gender, gender identity, sexual orientation, or other characteristic protected by law. This subsection does not condone profiling including, but not limited to, predictive law enforcement tools.

. A state or local government agency may not use a facial recognition service to create a record describing any individual's exercise of rights guaranteed by the First Amendment of the United States Constitution and by Article I, section 5 of the state Constitution.

. A law enforcement agency that utilizes body worn camera recordings shall comply with the provisions of RCW 42.56.240(14).

. A state or local law enforcement agency may not use the results of a facial recognition service as the sole basis to establish probable cause in a criminal investigation. The results of a facial recognition service may be used in conjunction with other information and evidence lawfully obtained by a law enforcement officer to establish probable cause in a criminal investigation.

. A state or local law enforcement agency may not use a facial recognition service to identify an individual based on a sketch or other manually produced image.

. A state or local law enforcement agency may not substantively manipulate an image for use in a facial recognition service in a manner not consistent with the facial recognition service provider's intended use and training.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6280-S.SL.pdf?cite=2020%20c%20257%20§%2011[2020 c 257 § 11]; ]

== 43.386.090 - Exemption—Federal regulations and orders—Airports and seaports. (Effective July 1, 2021.)
. This chapter does not apply to a state or local government agency that: (a) Is mandated to use a specific facial recognition service pursuant to a federal regulation or order, or that are undertaken through partnership with a federal agency to fulfill a congressional mandate; or (b) uses a facial recognition service in association with a federal agency to verify the identity of individuals presenting themselves for travel at an airport or seaport.

. A state or local government agency must report to a legislative authority the use of a facial recognition service pursuant to subsection (1) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6280-S.SL.pdf?cite=2020%20c%20257%20§%209[2020 c 257 § 9]; ]

== 43.386.100 - Exemption—Department of licensing—Drivers' licenses, permits, and identicards. (Effective July 1, 2021.)
Nothing in this chapter applies to the use of a facial recognition matching system by the department of licensing pursuant to RCW 46.20.037.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6280-S.SL.pdf?cite=2020%20c%20257%20§%2012[2020 c 257 § 12]; ]

== 43.386.900 - Findings—2020 c 257. (Effective July 1, 2021.)
The legislature finds that:

. Unconstrained use of facial recognition services by state and local government agencies poses broad social ramifications that should be considered and addressed. Accordingly, legislation is required to establish safeguards that will allow state and local government agencies to use facial recognition services in a manner that benefits society while prohibiting uses that threaten our democratic freedoms and put our civil liberties at risk.

. However, state and local government agencies may use facial recognition services to locate or identify missing persons, and identify deceased persons, including missing or murdered indigenous women, subjects of Amber alerts and silver alerts, and other possible crime victims, for the purposes of keeping the public safe.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6280-S.SL.pdf?cite=2020%20c%20257%20§%201[2020 c 257 § 1]; ]

== 43.386.901 - Effective date—2020 c 257.
Sections 1 through 9 and 11 through 13 of this act take effect July 1, 2021.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6280-S.SL.pdf?cite=2020%20c%20257%20§%2014[2020 c 257 § 14]; ]

