= 43.332 - Office of the Washington state trade representative.
:toc:

== 43.332.005 - Findings—Purpose.
. The legislature finds that:

.. The expansion of international trade is vital to the overall growth of Washington's economy;

.. On a per capita basis, Washington state is the most international trade dependent state in the nation;

.. The North American free trade agreement (NAFTA) and the general agreement on tariffs and trade (GATT) highlight the increased importance of international trade opportunities to the United States and the state of Washington;

.. The passage of NAFTA and GATT will have a major impact on the state's agriculture, aerospace, computer software, and textiles and apparel sectors;

.. There is a need to strengthen and coordinate the state's activities in promoting and developing its agricultural, manufacturing, and service industries overseas, especially for small and medium-sized businesses, and minority and women-owned business enterprises; and

.. The importance of having a coherent vision for advancing Washington state's interest in the global economy has rarely been so consequential as it is now.

. The legislature declares that the purpose of the office of the Washington state trade representative is to:

.. Strengthen and expand the state's activities in marketing its goods and services overseas;

.. Review and analyze proposed international trade agreements to assess their impact on goods and services produced by Washington businesses; and

.. Inform the legislature about ongoing trade negotiations, trade development, and the possible impacts on Washington's economy.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1173-S.SL.pdf?cite=2003%20c%20346%20§%201[2003 c 346 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1123-S.SL.pdf?cite=1995%20c%20350%20§%201[1995 c 350 § 1]; ]

== 43.332.010 - Office created—Duties.
. The office of the Washington state trade representative is created in the office of the governor. The office shall serve as the state's official liaison with foreign governments on trade matters.

. The office shall:

.. Work with the *department of community, trade, and economic development, the department of agriculture, and other appropriate state agencies, and within the agencies' existing resources, review and analyze proposed and enacted international trade agreements and provide an assessment of the impact of the proposed or enacted agreement on Washington's businesses and firms;

.. Provide input to the office of the United States trade representative in the development of international trade, commodity, and direct investment policies that reflect the concerns of the state of Washington;

.. Serve as liaison to the legislature on matters of trade policy oversight including, but not limited to, updates to the legislature regarding the status of trade negotiations, trade litigation, and the impacts of trade policy on Washington state businesses;

.. Work with the international trade division of the *department of community, trade, and economic development and the international marketing program of the Washington state department of agriculture to develop a statewide strategy designed to increase the export of Washington goods and services, particularly goods and services from small and medium-sized businesses; and

.. Conduct other activities the governor deems necessary to promote international trade and foreign investment within the state.

. The office shall prepare and submit an annual report on its activities under subsection (2) of this section to the governor and appropriate committees of the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1173-S.SL.pdf?cite=2003%20c%20346%20§%202[2003 c 346 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1123-S.SL.pdf?cite=1995%20c%20350%20§%202[1995 c 350 § 2]; ]

== 43.332.020 - Gifts, grants—Bank account.
The office of the Washington state trade representative may accept or request grants or gifts from citizens and other private sources to be used to defray the costs of appropriate hosting of foreign dignitaries, including appropriate gift-giving and reciprocal gift-giving, or other activities of the office. The office shall open and maintain a bank account into which it shall deposit all money received under this section. Such money and the interest accruing thereon shall not constitute public funds, shall be kept segregated and apart from funds of the state, and shall not be subject to appropriation or allotment by the state or subject to chapter 43.88 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1173-S.SL.pdf?cite=2003%20c%20346%20§%203[2003 c 346 § 3]; ]

