= 43.380 - Washington statewide reentry council.
:toc:

== 43.380.005 - Finding—Intent.
The legislature finds that the cycle of recidivism warrants a closer examination of our criminal justice system, correctional systems, and community services in Washington. Over ninety-five percent of persons in prison will return to the community, and more than half of those persons will reoffend and be reincarcerated in today's system. This high rate of recidivism results in more crimes, more victims, more prisons, and more trauma within families and communities. We can do better for the people of Washington.

The legislature intends to establish the Washington statewide reentry council to develop collaborative and cooperative relationships between the criminal justice system, victims and their families, impacted individuals and their families, and service providers, with the purpose of improving public safety and outcomes for people reentering the community from incarceration.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2791-S2.SL.pdf?cite=2016%20c%20188%20§%201[2016 c 188 § 1]; ]

== 43.380.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Council" means the Washington statewide reentry council.

. "Department" means the department of commerce.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2791-S2.SL.pdf?cite=2016%20c%20188%20§%202[2016 c 188 § 2]; ]

== 43.380.020 - Washington statewide reentry council—Created—Executive director.
. Subject to the availability of amounts appropriated for this specific purpose, the Washington statewide reentry council is created and located within the department for the purpose of promoting successful reentry of offenders after incarceration.

. Through the executive director that may be appointed by the council, the department shall administer the council by:

.. Providing the council and its executive director use of the department's facilities; and

.. Managing grants and other funds received, used, and disbursed by the council.

. Except during the 2019-2021 fiscal biennium, the department may not designate additional full-time staff to the administration of the council beyond the executive director.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1109-S.SL.pdf?cite=2019%20c%20415%20§%20976[2019 c 415 § 976]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2791-S2.SL.pdf?cite=2016%20c%20188%20§%203[2016 c 188 § 3]; ]

== 43.380.030 - Council—Membership.
. The council comprises fifteen members appointed by the governor.

. The governor must create a membership that includes:

.. [Empty]
... Representatives of: The department of corrections; the juvenile rehabilitation administration; a statewide organization representing community and technical colleges; a statewide organization representing law enforcement interests; a statewide organization representing the interests of crime victims; a statewide organization representing prosecutors; a statewide organization representing public defenders; a statewide or local organization representing businesses and employers; housing providers; and faith-based organizations or communities;

... At least two persons with experience reentering the community after incarceration; and

... Two other community leaders.

.. At least one position of the council must be reserved for an invited person with a background in tribal affairs, and such position has all of the same voting and other powers of other members.

. When making appointments, the governor shall consider:

.. The racial and ethnic background of applicants in order for the membership to reflect the diversity of racial and ethnic backgrounds of all those who are incarcerated in the state;

.. The gender of applicants in order for the membership to reflect the gender diversity of all those who are incarcerated in the state;

.. The geographic location of all applicants in order for the membership to represent the different geographic regions of the state; and

.. The experiences and background of all applicants relating to the incarcerated population.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2791-S2.SL.pdf?cite=2016%20c%20188%20§%204[2016 c 188 § 4]; ]

== 43.380.040 - Council—Initial appointments—Terms—Selection committee—Cochairs.
. The governor shall make initial appointments to the council. Initial appointments are for staggered terms from the date of appointment according to the following: Four members have four-year terms; four members have three-year terms; and five members have two-year terms. The governor shall designate the appointees who will serve the staggered terms.

. Except for initial appointments under subsection (1) of this section, all appointments are for two years from the date of appointment. Any member may be reappointed for additional terms. Any member of the council may be removed by the governor for misfeasance, malfeasance, or willful neglect of duty after notice and a public hearing, unless such notice and hearing is expressly waived in writing by the affected member. In the event of a vacancy due to death, resignation, or removal, or upon the expiration of a term, the governor shall appoint a successor for the remainder of the unexpired term according to the procedures in subsection (3) of this section. Vacancies must be filled within ninety days.

. The council shall create a selection committee to recruit, review, and recommend future members. Prior to thirty days before the expiration of a term or within sixty days of a vacancy due to death, resignation, or removal, the selection committee shall submit a recommendation of possible appointees. The governor shall consider the recommendations of the committee when making appointments.

. The council shall elect cochairs from among its membership. Cochairs are elected for two-year terms from the date of election. Any former or current cochair may be reelected for an additional term.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2791-S2.SL.pdf?cite=2016%20c%20188%20§%205[2016 c 188 § 5]; ]

== 43.380.050 - Council powers and duties—Selection of executive director—Stakeholder participation—Reports.
. In addition to other powers and duties prescribed in this chapter, the council is empowered to:

.. Meet at such times and places as necessary;

.. Advise the legislature and the governor on issues relating to reentry and reintegration of offenders;

.. Review, study, and make policy and funding recommendations on issues directly and indirectly related to reentry and reintegration of offenders in Washington state, including, but not limited to: Correctional programming and other issues in state and local correctional facilities; housing; employment; education; treatment; and other issues contributing to recidivism;

.. Apply for, receive, use, and leverage public and private grants as well as specifically appropriated funds to establish, manage, and promote initiatives and programs related to successful reentry and reintegration of offenders;

.. Contract for services as it deems necessary in order to carry out initiatives and programs;

.. Adopt policies and procedures to facilitate the orderly administration of initiatives and programs;

.. Create committees and subcommittees of the council as is necessary for the council to conduct its business; and

.. Create and consult with advisory groups comprising nonmembers. Advisory groups are not eligible for reimbursement under RCW 43.380.060.

. Subject to the availability of amounts appropriated for this specific purpose, the council may select an executive director to administer the business of the council.

.. The council may delegate to the executive director by resolution all duties necessary to efficiently carry on the business of the council. Approval by a majority vote of the council is required for any decisions regarding employment of the executive director.

.. The executive director may not be a member of the council while serving as executive director.

.. Employment of the executive director must be confirmed by the senate and terminates after a term of three years. At the end of a term, the council may consider hiring the executive director for an additional three-year term or an extension of a specified period less than three years. The council may fix the compensation of the executive director.

.. Subject to the availability of amounts appropriated for this specific purpose, the executive director shall reside in and be funded by the department.

. In conducting its business, the council shall solicit input and participation from stakeholders interested in reducing recidivism, promoting public safety, and improving community conditions for people reentering the community from incarceration. The council shall consult: The two largest caucuses in the house of representatives; the two largest caucuses in the senate; the governor; local governments; educators; behavioral health providers; behavioral health administrative services organizations; managed care organizations; city and county jails; the department of corrections; specialty courts; persons with expertise in evidence-based and research-based reentry practices; and persons with criminal histories and their families.

. The council shall submit to the governor and appropriate committees of the legislature a preliminary report of its activities and recommendations by December 1st of its first year of operation, and every two years thereafter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5432-S2.SL.pdf?cite=2019%20c%20325%20§%205016[2019 c 325 § 5016]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2791-S2.SL.pdf?cite=2016%20c%20188%20§%206[2016 c 188 § 6]; ]

== 43.380.060 - Council reimbursement.
The members of the council shall serve without compensation, but are entitled to be reimbursed for travel expenses as provided in RCW 43.03.050 and 43.03.060.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2791-S2.SL.pdf?cite=2016%20c%20188%20§%207[2016 c 188 § 7]; ]

== 43.380.070 - Meetings.
. Meetings of the council must be held in accordance with the open public meetings act, chapter 42.30 RCW, and at the call of the cochairs or when a majority of the council membership so requests. Members may participate in a meeting of the council by means of a conference telephone or similar communication equipment as described in RCW 23B.08.200.

. Seven members of the council constitute a quorum.

. Once operational, the council must convene on a regular schedule at least four times during each year.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2791-S2.SL.pdf?cite=2016%20c%20188%20§%208[2016 c 188 § 8]; ]

== 43.380.080 - Performance audits.
. The joint legislative audit and review committee shall conduct a performance audit of the council every six years.

. Each audit must include but not be limited to:

.. A determination of the extent to which funds expended by the council or provided in biennial budget acts expressly for implementing the duties of the council have contributed toward reducing recidivism in Washington;

.. A determination of the efficiency and effectiveness of the council, based upon the achievement of the objectives and benchmarks established by this chapter and any applicable biennial budget acts; and

.. Any recommendations for changes to the council's performance and structure necessary to ensure or improve accountability.

. The council may use the audits as the basis for developing changes to its policies and programs.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2791-S2.SL.pdf?cite=2016%20c%20188%20§%209[2016 c 188 § 9]; ]

