= 4.14 - Removal of certain actions to superior court.
:toc:

== 4.14.010 - Removal of certain actions from justice court to superior court authorized—Grounds—Joint claims or actions—Exceptions.
Whenever the removal of such action to superior court is required in order to acquire jurisdiction over a third party defendant, who is or may be liable to the defendant for all or part of the judgment and resides outside the county wherein the action was commenced, any civil action which could have been brought in superior court may, if commenced in district court, be removed by the defendant or defendants to the superior court for the county where such action is pending if the district court determines that there are reasonable grounds to believe that a third party may be liable to the plaintiff and issues an order so stating.

Whenever a separate or independent claim or cause of action which would be removable if sued upon alone is joined with one or more otherwise nonremovable claims or causes of action, the entire case may be removed and the superior court may determine all issues therein, or, in its discretion, may remand all matters not otherwise within its original jurisdiction.

This section does not apply to cases originally filed in the small claims department of a district court, or transferred to the small claims department pursuant to RCW 12.40.025, except as set forth in RCW 12.40.027.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5295-S.SL.pdf?cite=1997%20c%20352%20§%206[1997 c 352 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c46.pdf?cite=1967%20ex.s.%20c%2046%20§%204[1967 ex.s. c 46 § 4]; ]

== 4.14.020 - Petition for removal—Contents—Filing—Notice.
. A defendant or defendants desiring to remove any civil action from a justice court as authorized by RCW 4.14.010 shall file in the superior court in the county where such action is pending, a verified petition containing a short and plain statement of the facts which entitle him, her, or them to removal together with a copy of all process, pleadings and orders served upon him, her, or them in such action.

. The petition for removal of a civil action or proceeding shall be filed within twenty days after the receipt by the defendant, through service or otherwise, of a copy of the initial pleading setting forth the claim for relief upon which such action or proceeding is based.

If the case stated by the initial pleading is not removable, a petition for removal may be filed within twenty days after receipt by the defendant, through service or otherwise, of a copy of an amended pleading, motion, order, or other paper, including the defendant's answer, from which it may first be ascertained that the case is or has become removable.

. Promptly after the filing of such petition the defendant or defendants shall give written notice thereof to all adverse parties and shall file a copy of the petition with the justice court, which shall effect the removal and the justice court shall proceed no further unless and until the case is remanded.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%2081[2011 c 336 § 81]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c46.pdf?cite=1967%20ex.s.%20c%2046%20§%205[1967 ex.s. c 46 § 5]; ]

== 4.14.030 - Orders and process upon removal—Remand of cases improvidently removed.
In any case removed from justice court under the provisions of this chapter, the superior court may issue all necessary orders and process to bring before it all proper parties whether served by process issued by the justice court or otherwise.

If at any time before final judgment it appears that the case was removed improvidently and without jurisdiction, the superior court shall remand the case, and may order the payment of just costs. A certified copy of the order of remand shall be mailed by the clerk of the superior court to the justice court. The justice court may thereupon proceed with such case.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c46.pdf?cite=1967%20ex.s.%20c%2046%20§%206[1967 ex.s. c 46 § 6]; ]

== 4.14.040 - Attached property—Custody.
Whenever any action is removed from a justice court to a superior court under the provisions of this chapter, any attachment or sequestration of the property of the defendant in such action in the justice court shall remain in the custody of the sheriff to answer the final judgment or decree in the same manner as would have been held to answer had the cause been brought in the superior court originally.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c46.pdf?cite=1967%20ex.s.%20c%2046%20§%207[1967 ex.s. c 46 § 7]; ]

