= 4.44 - Trial.
:toc:

== 4.44.020 - Notice of trial—Note of issue.
At any time after the issues of fact are completed in any case by the service of complaint and answer or reply when necessary, as herein provided, either party may cause the issues of fact to be brought on for trial, by serving upon the opposite party a notice of trial at least three days before any day provided by rules of court for setting causes for trial, which notice shall give the title of the cause as in the pleadings, and notify the opposite party that the issues in such action will be brought on for trial at the time set by the court; and the party giving such notice of trial shall, at least five days before the day of setting such causes for trial file with the clerk of the court a note of issue containing the title of the action, the names of the attorneys and the date when the last pleading was served; and the clerk shall thereupon enter the cause upon the trial docket according to the date of the issue.

In case an issue of law raised upon the pleadings is desired to be brought on for argument, either party shall, at least five days before the day set apart by the court under its rules for hearing issues of law, serve upon the opposite party a like notice of trial and furnish the clerk of the court with a note of issue as above provided, which note of issue shall specify that the issue to be tried is an issue of law; and the clerk of the court shall thereupon enter such action upon the motion docket of the court.

When a cause has once been placed upon either docket of the court, if not tried or argued at the time for which notice was given, it need not be noticed for a subsequent session or day, but shall remain upon the docket from session to session or from law day to law day until final disposition or stricken off by the court. The party upon whom notice of trial is served may file the note of issue and cause the action to be placed upon the calendar without further notice.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%201[2003 c 406 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c127.pdf?cite=1893%20c%20127%20§%2035[1893 c 127 § 35]; RRS § 319; ]

== 4.44.025 - Priority permitted for aged or ill parties in civil cases.
When setting civil cases for trial, unless otherwise provided by statute, upon motion of a party, the court may give priority to cases in which a party is frail and over seventy years of age, a party is afflicted with a terminal illness, or other good cause is shown for an expedited trial date.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%202[2003 c 406 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1675.SL.pdf?cite=1991%20c%20197%20§%201[1991 c 197 § 1]; ]

== 4.44.060 - Proceedings in trial by court—Findings deemed verdict.
The order of proceedings on a trial by the court shall be the same as provided in trials by jury. The finding of the court upon the facts shall be deemed a verdict, and may be set aside in the same manner and for the same reason as far as applicable, and a new trial granted.

[ Code 1881 § 247; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2051%20§%20251[1877 p 51 § 251]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2060%20§%20251[1869 p 60 § 251]; RRS § 368; ]

== 4.44.070 - Findings and conclusions, how made.
In any case tried upon the facts without a jury or with an advisory jury, any party may, when the evidence is closed, submit distinct and concise proposed findings of fact and conclusions of law. They may be written and handed to the court, or at the option of the court, oral, and entered in the record.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%203[2003 c 406 § 3]; Code 1881 § 222; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2047%20§%20226[1877 p 47 § 226]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2056%20§%20226[1869 p 56 § 226]; RRS § 341; ]

== 4.44.080 - Questions of law to be decided by court.
All questions of law including the admissibility of testimony, the facts preliminary to such admission, and the construction of statutes and other writings, and other rules of evidence, are to be decided by the court, and all discussions of law addressed to it.

[ Code 1881 § 223; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2047%20§%20227[1877 p 47 § 227]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2056%20§%20227[1869 p 56 § 227]; RRS § 342; ]

== 4.44.090 - Questions of fact for jury.
All questions of fact other than those mentioned in RCW 4.44.080, shall be decided by the jury, and all evidence thereon addressed to them.

[ Code 1881 § 224; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2047%20§%20228[1877 p 47 § 228]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2056%20§%20228[1869 p 56 § 228]; RRS § 343; ]

== 4.44.110 - Jury fee part of taxable costs.
The jury fee paid by the party demanding a trial by jury shall be a part of the taxable costs in such action.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c304.pdf?cite=1961%20c%20304%20§%203[1961 c 304 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c43.pdf?cite=1903%20c%2043%20§%202[1903 c 43 § 2]; RRS § 317; ]

== 4.44.120 - Impanelling jury—Voir dire, challenge for cause—Number.
When the action is called for trial, a panel of potential jurors shall be selected at random from the citizens summoned for jury service who have appeared and have not been excused. A voir dire examination of the panel shall be conducted for the purpose of discovering any basis for challenge for cause and to permit the intelligent exercise of peremptory challenges. Any necessary additions to the panel shall be selected at random from the list of qualified jurors. The jury shall consist of six persons, unless the parties in their written demand for jury demand that the jury be twelve in number or consent to a less number. The parties may consent to a jury less than six in number but not less than three, and such consent shall be entered in the record.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%204[2003 c 406 § 4]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2259.SL.pdf?cite=1996%20c%2040%20§%201[1996 c 40 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c57.pdf?cite=1972%20ex.s.%20c%2057%20§%203[1972 ex.s. c 57 § 3]; Code 1881 § 206; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2043%20§%20210[1877 p 43 § 210]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2051%20§%20210[1869 p 51 § 210]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20164%20§%20185[1854 p 164 § 185]; RRS § 323; ]

== 4.44.130 - Challenges—Kind and number.
Either party may challenge the jurors. The challenge shall be to individual jurors, and be peremptory or for cause. Each party shall be entitled to three peremptory challenges. When there is more than one party on either side, the parties need not join in a challenge for cause; but, they shall join in a peremptory challenge before it can be made. If the court finds that there is a conflict of interests between parties on the same side, the court may allow each conflicting party up to three peremptory challenges.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c37.pdf?cite=1969%20ex.s.%20c%2037%20§%201[1969 ex.s. c 37 § 1]; Code 1881 § 207; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2043%20§%20211[1877 p 43 § 211]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20165%20§%20186[1854 p 165 § 186]; RRS § 324; ]

== 4.44.140 - Peremptory challenges defined.
A peremptory challenge is an objection to a juror for which no reason need be given, but upon which the court shall exclude the juror.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%205[2003 c 406 § 5]; Code 1881 § 208; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2043%20§%20212[1877 p 43 § 212]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2051%20§%20212[1869 p 51 § 212]; RRS § 325; ]

== 4.44.150 - Challenges for cause defined.
A challenge for cause is an objection to a juror, and may be either:

. General; that the juror is disqualified from serving in any action; or

. Particular; that the juror is disqualified from serving in the action on trial.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%206[2003 c 406 § 6]; Code 1881 § 209; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2043%20§%20213[1877 p 43 § 213]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2051%20§%20213[1869 p 51 § 213]; RRS § 326; ]

== 4.44.160 - General causes of challenge.
General causes of challenge are:

. A want of any of the qualifications prescribed for a juror, as set out in RCW 2.36.070.

. Unsoundness of mind, or such defect in the faculties of the mind, or organs of the body, as renders him or her incapable of performing the duties of a juror in any action.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2394-S.SL.pdf?cite=1992%20c%2093%20§%206[1992 c 93 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c203.pdf?cite=1975%201st%20ex.s.%20c%20203%20§%202[1975 1st ex.s. c 203 § 2]; Code 1881 § 210; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2044%20§%20214[1877 p 44 § 214]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2052%20§%20214[1869 p 52 § 214]; RRS § 327; ]

== 4.44.170 - Particular causes of challenge.
Particular causes of challenge are of three kinds:

. For such a bias as when the existence of the facts is ascertained, in judgment of law disqualifies the juror, and which is known in this code as implied bias.

. For the existence of a state of mind on the part of the juror in reference to the action, or to either party, which satisfies the court that the challenged person cannot try the issue impartially and without prejudice to the substantial rights of the party challenging, and which is known in this code as actual bias.

. For the existence of a defect in the functions or organs of the body which satisfies the court that the challenged person is incapable of performing the duties of a juror in the particular action without prejudice to the substantial rights of the party challenging.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c203.pdf?cite=1975%201st%20ex.s.%20c%20203%20§%203[1975 1st ex.s. c 203 § 3]; Code 1881 § 211; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2044%20§%20215[1877 p 44 § 215]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2052%20§%20215[1869 p 52 § 215]; RRS § 329; ]

== 4.44.180 - Implied bias defined.
A challenge for implied bias may be taken for any or all of the following causes, and not otherwise:

. Consanguinity or affinity within the fourth degree to either party.

. Standing in the relation of guardian and ward, attorney and client, master and servant or landlord and tenant, to a party; or being a member of the family of, or a partner in business with, or in the employment for wages, of a party, or being surety or bail in the action called for trial, or otherwise, for a party.

. Having served as a juror on a previous trial in the same action, or in another action between the same parties for the same cause of action, or in a criminal action by the state against either party, upon substantially the same facts or transaction.

. Interest on the part of the juror in the event of the action, or the principal question involved therein, excepting always, the interest of the juror as a member or citizen of the county or municipal corporation.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%207[2003 c 406 § 7]; Code 1881 § 212; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2044%20§%20216[1877 p 44 § 216]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2052%20§%20216[1869 p 52 § 216]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20165%20§%20187[1854 p 165 § 187]; RRS § 330; ]

== 4.44.190 - Challenge for actual bias.
A challenge for actual bias may be taken for the cause mentioned in RCW 4.44.170(2). But on the trial of such challenge, although it should appear that the juror challenged has formed or expressed an opinion upon what he or she may have heard or read, such opinion shall not of itself be sufficient to sustain the challenge, but the court must be satisfied, from all the circumstances, that the juror cannot disregard such opinion and try the issue impartially.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%208[2003 c 406 § 8]; Code 1881 § 213; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2044%20§%20217[1877 p 44 § 217]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2053%20§%20217[1869 p 53 § 217]; RRS § 331; ]

== 4.44.210 - Peremptory challenges, how taken.
The jurors having been examined as to their qualifications, first by the plaintiff and then by the defendant, and passed for cause, the peremptory challenges shall be conducted as follows, to wit:

The plaintiff may challenge one, and then the defendant may challenge one, and so alternately until the peremptory challenges shall be exhausted. During this alternating process, if one of the parties declines to exercise a peremptory challenge, then that party may no longer peremptorily challenge any of the jurors in the group for which challenges are then being considered and may only peremptorily challenge any jurors later added to that group. A refusal to challenge by either party in the said order of alternation shall not prevent the adverse party from using the full number of challenges.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%209[2003 c 406 § 9]; Code 1881 § 215; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2045%20§%20219[1877 p 45 § 219]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2053%20§%20219[1869 p 53 § 219]; RRS § 333; ]

== 4.44.220 - Order of taking challenges.
The challenges of either party shall be taken separately in the following order, including in each challenge all the causes of challenge belonging to the same class:

. Challenges for cause.

. Peremptory challenges.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%2010[2003 c 406 § 10]; Code 1881 § 216; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2045%20§%20220[1877 p 45 § 220]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2053%20§%20220[1869 p 53 § 220]; RRS § 334; ]

== 4.44.230 - Exceptions to challenges—Determination.
The challenge may be excepted to by the adverse party for insufficiency, and if so, the court shall determine the sufficiency thereof, assuming the facts alleged therein to be true. The challenge may be denied by the adverse party, and if so, the court shall determine the facts and decide the issue.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%2011[2003 c 406 § 11]; Code 1881 § 217; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2045%20§%20221[1877 p 45 § 221]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2053%20§%20221[1869 p 53 § 221]; RRS § 335; ]

== 4.44.240 - Challenge determination.
When facts are determined under RCW 4.44.230, the rules of evidence applicable to testimony offered upon the trial of an ordinary issue of fact shall govern. The juror challenged, or any other person otherwise competent may be examined as a witness by either party. If the challenge is sustained, the juror shall be dismissed from the case; otherwise, the juror shall be retained.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%2012[2003 c 406 § 12]; Code 1881 § 218; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2045%20§%20222[1877 p 45 § 222]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2054%20§%20222[1869 p 54 § 222]; RRS § 336; ]

== 4.44.250 - Challenge, exception, denial may be oral.
The challenge, the exception, and the denial may be made orally. The judge shall enter the same upon the record, along with the substance of the testimony on either side.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%2013[2003 c 406 § 13]; Code 1881 § 219; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2045%20§%20223[1877 p 45 § 223]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2054%20§%20223[1869 p 54 § 223]; RRS § 337; ]

== 4.44.260 - Oath of jurors.
When the jury has been selected, an oath or affirmation shall be administered to the jurors, in substance that they and each of them, will well, and truly try, the matter in issue between the plaintiff and defendant, and a true verdict give, according to the law and evidence as given them on the trial.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%2014[2003 c 406 § 14]; Code 1881 § 220; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2046%20§%20224[1877 p 46 § 224]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2054%20§%20224[1869 p 54 § 224]; RRS § 338; ]

== 4.44.270 - View of premises by jury.
Whenever in the opinion of the court it is proper that the jury should have a view of real property which is the subject of litigation, or of the place in which any material fact occurred, it may order the jury to be conducted in a body, in the custody of a proper officer, to the place which shall be shown to them by the judge or by a person appointed by the court for that purpose. While the jury are thus absent no person other than the judge, or person so appointed, shall speak to them on any subject connected with the trial.

[ Code 1881 § 225; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2047%20§%20229[1877 p 47 § 229]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2056%20§%20229[1869 p 56 § 229]; RRS § 344; ]

== 4.44.280 - Admonitions to jurors.
The court may admonish the jurors that they must not discuss among themselves any subject connected with the trial until they begin their deliberations. The court may also admonish the jurors that they must not discuss with nonjurors any subject connected with the trial until the jurors have been dismissed from the case.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%2015[2003 c 406 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c7.pdf?cite=1957%20c%207%20§%205[1957 c 7 § 5]; Code 1881 § 226; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2047%20§%20230[1877 p 47 § 230]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2056%20§%20230[1869 p 56 § 230]; RRS § 345; ]

== 4.44.290 - Replacement juror procedure.
If after the formation of the jury, and before verdict, a juror becomes unable to perform his or her duty, the court may discharge the juror. In that case, unless the parties agree to proceed with the other jurors: (1) An alternate juror may replace the discharged juror and the jury instructed to start their deliberations anew; (2) a new juror may be sworn and the trial begin anew; or (3) the jury may be discharged and a new jury then or afterwards formed.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%2016[2003 c 406 § 16]; Code 1881 § 227; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2048%20§%20231[1877 p 48 § 231]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2056%20§%20231[1869 p 56 § 231]; RRS § 347; ]

== 4.44.300 - Care of jury while deliberating.
During deliberations, the jury may be allowed to separate unless good cause is shown, on the record, for sequestration of the jury. Unless the members of a deliberating jury are allowed to separate, they must be kept together in a room provided for them, or some other convenient place under the charge of one or more officers, until they agree upon their verdict, or are discharged by the court. The officer shall, to the best of his or her ability, keep the jury separate from other persons. The officer shall not allow any communication to be made to them, nor make any himself or herself, unless by order of the court, except to ask them if they have agreed upon their verdict, and the officer shall not, before the verdict is rendered, communicate to any person the state of their deliberations or the verdict agreed on.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%2017[2003 c 406 § 17]; Code 1881 § 229; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2048%20§%20233[1877 p 48 § 233]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2057%20§%20233[1869 p 57 § 233]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20166%20§%20194[1854 p 166 § 194]; RRS § 349; ]

== 4.44.310 - Expense of keeping jury.
If, while the jury are kept together, either during the progress of the trial or after their retirement for deliberation, the court orders them to be provided with suitable and sufficient food and lodging, they shall be so provided at the expense of the county.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%2018[2003 c 406 § 18]; Code 1881 § 230; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2048%20§%20234[1877 p 48 § 234]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2057%20§%20234[1869 p 57 § 234]; RRS § 350; ]

== 4.44.330 - Discharge of jury without verdict.
The jury may be discharged by the court on account of the sickness of a juror, or other accident or calamity requiring their discharge, or by consent of both parties, or after they have been kept together until it satisfactorily appears that there is no probability of their agreeing.

[ Code 1881 § 233; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2048%20§%20237[1877 p 48 § 237]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2058%20§%20237[1869 p 58 § 237]; RRS § 353; ]

== 4.44.340 - Effect of discharge of jury.
In all cases where a jury are discharged or prevented from giving a verdict, by reason of accident or other cause, during the progress of the trial or after the cause is submitted to them, the action shall thereafter be for trial anew.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c60.pdf?cite=1891%20c%2060%20§%202[1891 c 60 § 2]; Code 1881 § 234; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2049%20§%20238[1877 p 49 § 238]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2058%20§%20238[1869 p 58 § 238]; RRS § 354; ]

== 4.44.350 - Court recess while jury is out.
While the jury is absent the court may adjourn from time to time, in respect to other business, but it is nevertheless to be deemed open for every purpose connected with the cause submitted to the jury until a verdict is rendered or the jury discharged.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c9.pdf?cite=1957%20c%209%20§%202[1957 c 9 § 2]; Code 1881 § 235; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2049%20§%20239[1877 p 49 § 239]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2058%20§%20239[1869 p 58 § 239]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20166%20§%20197[1854 p 166 § 197]; RRS § 355; ]

== 4.44.360 - Proceedings when jury have agreed.
When the jury have agreed upon their verdict they shall be conducted into court by the officer having them in charge.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%2019[2003 c 406 § 19]; Code 1881 § 236; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2049%20§%20240[1877 p 49 § 240]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2058%20§%20240[1869 p 58 § 240]; RRS § 356; ]

== 4.44.370 - Manner of giving verdict.
The jurors shall be asked by the court or the clerk whether they have agreed upon their verdict, and if the presiding juror answers in the affirmative, the presiding juror shall submit the verdict to the court.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%2020[2003 c 406 § 20]; Code 1881 § 237; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2049%20§%20241[1877 p 49 § 241]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2058%20§%20241[1869 p 58 § 241]; RRS § 357; ]

== 4.44.380 - Number of jurors required to render verdict.
In all trials by juries of six in the superior court, except criminal trials, when five of the jurors agree upon a verdict, the verdict so agreed upon shall be signed by the presiding juror, and the verdict shall stand as the verdict of the whole jury, and have all the force and effect of a verdict agreed to by six jurors. In cases where the jury is twelve in number, a verdict reached by ten shall have the same force and effect as described above, and the same procedures shall be followed.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%2021[2003 c 406 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c57.pdf?cite=1972%20ex.s.%20c%2057%20§%204[1972 ex.s. c 57 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c36.pdf?cite=1895%20c%2036%20§%201[1895 c 36 § 1]; RRS § 358; ]

== 4.44.390 - Jury may be polled.
After the verdict is announced, but before it is filed, the jury may be polled at the request of either party. Each juror may be asked whether the verdict is his or her individual verdict and whether the verdict is the jury's collective verdict. If it appears that the verdict is insufficient because the required number of jurors have not reached agreement, the jurors may be returned to the jury room for further deliberation.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%2022[2003 c 406 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c57.pdf?cite=1972%20ex.s.%20c%2057%20§%206[1972 ex.s. c 57 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c36.pdf?cite=1895%20c%2036%20§%202[1895 c 36 § 2]; RRS § 359; ]

== 4.44.410 - General or special verdicts.
The verdict of a jury is either general or special.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c76.pdf?cite=1984%20c%2076%20§%204[1984 c 76 § 4]; Code 1881 § 240; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2049%20§%20244[1877 p 49 § 244]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2059%20§%20244[1869 p 59 § 244]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20167%20§%20198[1854 p 167 § 198]; RRS § 362; ]

== 4.44.420 - Verdict in action for specific personal property.
In an action for the recovery of specific personal property, if the property has not been delivered to the plaintiff, or the defendant by his or her answer claims a return thereof, the jury shall assess the value of the property if their verdict be in favor of the plaintiff, or if they find in favor of the defendant and that the defendant is entitled to a return thereof, they may at the same time assess the damages, if any are claimed in the complaint or answer, which the prevailing party has sustained by reason of the detention or taking and withholding such property.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%2023[2003 c 406 § 23]; Code 1881 § 241; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2050%20§%20245[1877 p 50 § 245]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2059%20§%20245[1869 p 59 § 245]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20167%20§%20199[1854 p 167 § 199]; RRS § 363; ]

== 4.44.440 - Inconsistency between special findings of fact and general verdict.
When special findings of fact are inconsistent with the general verdict, the judge may enter judgment consistent with the findings of fact, may return the jurors to the jury room for further deliberations, or may order a new trial.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%2024[2003 c 406 § 24]; Code 1881 § 243; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2050%20§%20247[1877 p 50 § 247]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2060%20§%20247[1869 p 60 § 247]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20167%20§%20201[1854 p 167 § 201]; RRS § 365; ]

== 4.44.450 - Jury to assess amount of recovery.
When a verdict is found for the plaintiff in an action for the recovery of money, or for the defendant when a setoff for the recovery of money is established beyond the amount of the plaintiff's claim as established, the jury shall also assess the amount of the recovery; they may also, under the direction of the court, assess the amount of the recovery when the court gives judgment for a party on the pleadings.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%2025[2003 c 406 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c60.pdf?cite=1891%20c%2060%20§%203[1891 c 60 § 3]; Code 1881 § 244; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2050%20§%20248[1877 p 50 § 248]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2060%20§%20248[1869 p 60 § 248]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20167%20§%20202[1854 p 167 § 202]; RRS § 366; ]

== 4.44.460 - Receiving verdict and discharging jury.
If the court determines that the verdict meets the requirements contained in this chapter and in court rules, the clerk shall file the verdict. The verdict is then complete and the jury shall be discharged from the case. The verdict shall be in writing, and under the direction of the court shall be substantially entered in the record as of the day's proceedings on which it was given.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%2026[2003 c 406 § 26]; Code 1881 § 239; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2049%20§%20243[1877 p 49 § 243]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2059%20§%20243[1869 p 59 § 243]; RRS § 361; ]

== 4.44.470 - Court may fix amount of bond in civil actions.
Whenever by statute a bond or other security is required for any purpose in an action or other proceeding in a court of record and if the party shall apply therefor, the court shall have power to prescribe the amount of the bond or other security notwithstanding any requirement of the statute; and in every such case money in an amount prescribed by the court may be deposited with the clerk in lieu of a bond. After a bond or other security shall have been given, the court in its discretion may require additional security either on its own motion or upon motion of an interested party or person. The courts shall exercise care to require adequate though not excessive security in every instance.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c272.pdf?cite=1927%20c%20272%20§%201[1927 c 272 § 1]; RRS § 958-4; ]

== 4.44.480 - Deposits in court—Order.
When it is admitted by the pleading or examination of a party, that the party possesses or has control of any money, or other thing capable of delivery, which being the subject of the litigation, is held by him or her as trustee for another party, or which belongs or is due to another party, the court may order the same to be deposited in court, or delivered to such party, with or without security, subject to the further direction of the court.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1675-S.SL.pdf?cite=2003%20c%20406%20§%2027[2003 c 406 § 27]; Code 1881 § 195; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2041%20§%20199[1877 p 41 § 199]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2049%20§%20203[1869 p 49 § 203]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20163%20§%20174[1854 p 163 § 174]; RRS § 745; ]

== 4.44.490 - Deposits in court—Enforcement of order.
Whenever, in the exercise of its authority, a court shall have ordered the deposit or delivery of money or other thing, and the order is disobeyed, the court, besides punishing the disobedience as for contempt, may make an order requiring the sheriff to take the money or thing, and deposit or deliver it, in conformity with the direction of the court.

[ Code 1881 § 196; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2041%20§%20200[1877 p 41 § 200]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2049%20§%20200[1869 p 49 § 200]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20163%20§%20175[1854 p 163 § 175]; RRS § 746; ]

== 4.44.500 - Deposits in court—Custody of money deposited.
Money deposited, or paid into a court in an action, shall not be loaned out, unless, with the consent of all parties having an interest in, or making claim to the same.

[ Code 1881 § 197; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2041%20§%20201[1877 p 41 § 201]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2049%20§%20201[1869 p 49 § 201]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20163%20§%20176[1854 p 163 § 176]; RRS § 747; ]

