= 4.60 - Judgment by confession.
:toc:

== 4.60.010 - Judgment on confession authorized.
On the confession of the defendant, with the assent of the plaintiff or his or her attorney, judgment may be given against the defendant in any action before or after answer, for any amount or relief not exceeding or different from that demanded in the complaint.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20111[2011 c 336 § 111]; Code 1881 § 291; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2060%20§%20295[1877 p 60 § 295]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2072%20§%20293[1869 p 72 § 293]; 1854 p 172 §§ 226-228; RRS § 413; ]

== 4.60.020 - Confession by public and private corporations and minors.
When the action is against the state, a county or other public corporation therein, or a private corporation, or a minor, the confession shall be made by the person who at the time sustains the relation to such state, corporation, county or minor, as would authorize the service of a notice summons upon him or her; or in the case of a minor, if a guardian for the action has been appointed, then by such guardian; in all other cases the confession shall be made by the defendant in person.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20112[2011 c 336 § 112]; Code 1881 § 292; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2060%20§%20296[1877 p 60 § 296]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2072%20§%20294[1869 p 72 § 294]; RRS § 414; ]

== 4.60.030 - Confession by person jointly liable.
When the action is upon a contract and against one or more defendants jointly liable, judgment may be given on the confession of one or more defendants, against all the defendants thus jointly liable, whether such defendants have been served or not, to be enforced only against their joint property and against the joint and separate property of the defendant making the confession.

[ Code 1881 § 293; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2060%20§%20297[1877 p 60 § 297]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2072%20§%20295[1869 p 72 § 295]; RRS § 415; ]

== 4.60.040 - Confession, how made.
The confession and assent thereto shall be in writing and subscribed by the parties making the same, and acknowledged by each before some officer authorized to take acknowledgments of deeds.

[ Code 1881 § 294; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2060%20§%20298[1877 p 60 § 298]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2072%20§%20296[1869 p 72 § 296]; RRS § 416; ]

== 4.60.050 - Judgment by confession without suit.
A judgment by confession may be entered without action, either for money due or to become due, or to secure any person against contingent liability on behalf of the defendant, or both, in the manner prescribed by this chapter.

[ Code 1881 § 295; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2060%20§%20299[1877 p 60 § 299]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2073%20§%20297[1869 p 73 § 297]; RRS § 417; ]

== 4.60.060 - Statement in writing—Requisites.
A statement in writing shall be made, signed by the defendant and verified by his or her oath, to the following effect:

. It shall authorize the entry of judgment for a specified sum.

. If it be for money due or to become due, it shall state concisely the facts out of which the indebtedness arose, and shall show that the sum confessed to be due, is justly due or to become due.

. If it be for the purpose of securing the plaintiff against a contingent liability, it shall state concisely the facts constituting the liability, and show that the sum confessed therefor does not exceed the same.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20113[2011 c 336 § 113]; Code 1881 § 296; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2061%20§%20300[1877 p 61 § 300]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2073%20§%20298[1869 p 73 § 298]; RRS § 418; ]

== 4.60.070 - Judgment on confession—Entry—Execution.
The statement must be presented to the superior court or a judge thereof, and if the same be found sufficient, the court or judge shall indorse thereon an order that judgment be entered by the clerk; whereupon it may be filed in the office of the clerk, who shall enter a judgment for the amount confessed, with costs. Execution may be issued and enforced thereon in the same manner as upon judgments in other cases.

[ Code 1881 § 297; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2061%20§%20301[1877 p 61 § 301]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2073%20§%20299[1869 p 73 § 299]; RRS § 419; ]

