= 4.68 - Procedure to bind joint debtor.
:toc:

== 4.68.010 - Summons after judgment.
When a judgment is recorded against one or more of several persons jointly indebted upon an obligation by proceeding as provided by the court by rule, such defendants who were not originally served with the summons, and did not appear to the action, may be summoned to show cause why they should not be bound by the judgment, in the same manner as though they had been originally served with the summons.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c76.pdf?cite=1984%20c%2076%20§%206[1984 c 76 § 6]; Code 1881 § 314; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2064%20§%20318[1877 p 64 § 318]; RRS § 436; ]

== 4.68.020 - Contents of summons.
The summons, as provided in RCW 4.68.010, must describe the judgment, and require the person summoned to show cause why he or she should not be bound by it, and must be served in the same manner and returnable within the same time, as the original summons. It is not necessary to file a new complaint.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20114[2011 c 336 § 114]; Code 1881 § 315; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2064%20§%20319[1877 p 64 § 319]; RRS § 437; ]

== 4.68.030 - Affidavit must accompany summons.
The summons must be accompanied by an affidavit of the plaintiff, his or her agent, representative, or attorney, that the judgment, or some part thereof, remains unsatisfied, and must specify the amount due thereon.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20115[2011 c 336 § 115]; Code 1881 § 316; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2065%20§%20320[1877 p 65 § 320]; RRS § 438; ]

== 4.68.040 - Defenses.
Upon the service of such summons and affidavit, the defendant may answer within the time specified therein, denying the judgment, or setting up any defense which may have arisen subsequently to the taking of the judgment, or he or she may deny his or her liability on the obligation upon which the judgment was rendered, except a discharge from such liability by the statute of limitations.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20116[2011 c 336 § 116]; Code 1881 § 317; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2065%20§%20321[1877 p 65 § 321]; RRS § 439; ]

== 4.68.050 - Pleadings.
If the defendant in his or her answer, deny the judgment, or set up any defense which may have arisen subsequently, the summons, with the affidavit annexed, and the answer, constitute the written allegations in the case; if he or she deny his or her liability on the obligation upon which the judgment was rendered, a copy of the original complaint and judgment, the summons with the affidavit annexed, and the answer constitute such written allegations.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20117[2011 c 336 § 117]; Code 1881 § 318; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2065%20§%20322[1877 p 65 § 322]; RRS § 440; ]

== 4.68.060 - Trial.
The issue formed may be tried as in other cases, but when the defendant denies in his or her answer any liability on the obligation upon which the judgment was rendered, if a verdict be found against him or her, it must not exceed the amount remaining unsatisfied on such original judgment, with interest thereon.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20118[2011 c 336 § 118]; Code 1881 § 319; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2065%20§%20323[1877 p 65 § 323]; RRS § 441; ]

