= 81.64 - Street railways.
:toc:

== 81.64.010 - Grant of franchise.
The legislative authority of the city or town having control of any public street or road, or where such street or road is not within the limits of any incorporated city or town, then the board of county commissioners wherein such road or street is situated, may grant authority for the construction, maintenance and operation of electric railroads or railways, motor railroads or railways and railroads and railways of which the motive power is any power other than steam, together with such poles, wires and other appurtenances upon, over, along and across any such public street or road and in granting such authority the legislative authority of such city or town or the board of county commissioners, as the case may be, may prescribe the terms and conditions on which such railroads or railways and their appurtenances shall be constructed, maintained and operated upon, over, along and across such road or street, and the grade or elevation at which the same shall be maintained and operated.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.64.010[1961 c 14 § 81.64.010]; 1907 c 99 § 1, part; 1903 c 175 § 1, part; RRS § 11082, part; ]

== 81.64.020 - Application to county legislative authority—Notice—Hearing—Order.
On application being made to the county legislative authority for such authority, the county legislative authority shall fix a time and place for hearing the same, and shall cause the county auditor to give public notice thereof at the expense of the applicant, by posting written or printed notices in three public places in the county seat of the county, and in at least one conspicuous place on the road or street or part thereof, for which application is made, at least thirty days before the day fixed for the hearing, and by publishing a like notice once a week for two consecutive weeks in the official county newspaper, the last publication to be at least five days before the day fixed for the hearing, which notice shall state the name or names of the applicant or applicants, a description of the roads or streets or parts thereof for which the application is made, and the time and place fixed for the hearing. The hearing may be adjourned from time to time by order of the county legislative authority. If, after the hearing, the county legislative authority shall deem it to be for the public interest to grant the authority in whole or in part, it may make and enter the proper order granting the authority applied for or such part thereof as it deems to be for the public interest, and shall require such railroad or railway and its appurtenances to be placed in such location on or along the road or street as it finds will cause the least interference with other uses of the road or street.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c469.pdf?cite=1985%20c%20469%20§%2063[1985 c 469 § 63]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.64.020[1961 c 14 § 81.64.020]; 1907 c 99 § 1, part; 1903 c 175 § 1, part; RRS § 11082, part; ]

== 81.64.030 - May cross public road.
In case any such railroad or railway, is or shall be located in part on private right-of-way, the owner thereof shall have the right to construct and operate the same across any county road or county street which intersects such private right-of-way, if such crossing is so constructed and maintained as to do no unnecessary damage: PROVIDED, That any person or corporation constructing such crossing or operating such railroad or railway on or along such county road or public street shall be liable to the county for all necessary expense incurred in restoring such county road or public street to a suitable condition for travel.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.64.030[1961 c 14 § 81.64.030]; 1907 c 99 § 1, part; 1903 c 175 § 1, part; RRS § 11082, part; ]

== 81.64.040 - Eminent domain.
Every corporation incorporated or that may hereafter be incorporated under the laws of this state, or of any other state or territory of the United States and doing business in this state for the purpose of operating railroads or railways by electric power, shall have the right to appropriate real estate and other property for right-of-way or for any corporate purpose, in the same manner and under the same procedure as now is or may hereafter be provided by law in the case of ordinary railroad corporations authorized by the laws of this state to exercise the right of eminent domain: PROVIDED, That such right of eminent domain shall not be exercised with respect to any public road or street until the location of the electric railroad or railway thereon has been authorized in accordance with RCW 81.64.010 through 81.64.030.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.64.040[1961 c 14 § 81.64.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c175.pdf?cite=1903%20c%20175%20§%202[1903 c 175 § 2]; RRS § 11083; ]

== 81.64.050 - Right of entry.
Every such corporation shall have the right to enter upon any land between the termini of the proposed lines for the purpose of examining, locating and surveying such lines, doing no unnecessary damage thereby.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.64.050[1961 c 14 § 81.64.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1899c94.pdf?cite=1899%20c%2094%20§%202[1899 c 94 § 2]; RRS § 11085; ]

== 81.64.060 - Purchase or lease of street railway property.
Any corporation incorporated or that may hereafter be incorporated under the laws of this state or any state or territory of the United States, for the purpose of constructing, owning or operating railroads or railways by electric power, may lease or purchase and operate (except in cases where such lease or purchase is prohibited by the Constitution of this state) the whole or any part of the electric railroad or electric railway, of any other corporation heretofore or hereafter constructed, together with the franchises, powers, immunities and all other property or appurtenances appertaining thereto: PROVIDED, That such lease or purchase has been or shall be consented to by stockholders of record holding at least two-thirds in amount of the capital stock of the lessor or grantor corporation; and all such leases and purchases made or entered into prior to the effective date of chapter 175, Laws of 1903, by consent of stockholders as aforesaid are for all intents and purposes hereby ratified and confirmed, saving, however, any vested rights of private parties.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.64.060[1961 c 14 § 81.64.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c175.pdf?cite=1903%20c%20175%20§%203[1903 c 175 § 3]; RRS § 11084; ]

== 81.64.070 - Consolidation of companies.
With the consent of the majority in interest of their shareholders, two or more corporations operating street railway lines within or in the suburbs of the same municipality, may amalgamate their businesses and properties by consolidation, sale, lease, or other appropriate means, and either by conveyance to a third corporation or one to the other.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.64.070[1961 c 14 § 81.64.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c170.pdf?cite=1917%20c%20170%20§%201[1917 c 170 § 1]; RRS § 11086; ]

== 81.64.080 - Fares and transfers.
No street railroad company shall charge, demand or collect more than five cents for one continuous ride within the corporate limits of any city or town: PROVIDED, That such rate may be exceeded or lowered as to any municipally owned street railroad when the corporate authorities of the municipality owning such railroad shall, by an ordinance duly passed, authorize the collection of a higher or lower rate of fare, to be specified in such ordinance, and as to any other street railroad company, such rate may be exceeded or lowered with the permission or upon the order of the commission after the filing of a tariff or a complaint by such street railroad company and a hearing thereon as provided in this title. Every street railroad company shall, upon such terms as shall be just and reasonable, furnish to its passengers transfers entitling such passenger to one continuous trip over and upon portions of its lines within the said city or town not reached by the originating car.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.64.080[1961 c 14 § 81.64.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c33.pdf?cite=1919%20c%2033%20§%201[1919 c 33 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%2025[1911 c 117 § 25]; RRS § 10361; ]

== 81.64.090 - Competent employees required—"Competent" defined—Penalty.
. Street railway or streetcar companies, or streetcar corporations, shall employ none but competent persons to operate or assist as conductors, motor operators, or grip operators upon any street railway, or streetcar line in this state.

. A person shall be deemed competent to operate or assist in operating cars or (dummies) usually used by street railway or streetcar companies, or corporations, only after first having served at least three days under personal instruction of a regularly employed conductor, motor operator, or grip operator on a car or dummy in actual service on the particular street railway or streetcar line for which the service of an additional person or additional persons may be required: PROVIDED, That during a strike on the streetcar lines the railway companies may employ competent persons who have not worked three days on the particular streetcar line.

. Any violation of this section by the president, secretary, manager, superintendent, assistant superintendent, stockholder, or other officer or employee of any company or corporation owning or operating any street railway or streetcar line or any receiver of street railway or streetcar company, or street railway or streetcar corporations appointed by any court within this state to operate such car line is a misdemeanor punishable by a fine in any amount not less than fifty dollars nor more than two hundred dollars, or imprisonment in the county jail for a term of thirty days, or both such fine and imprisonment at the discretion of the court.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%201032[2009 c 549 § 1032]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20396[2003 c 53 § 396]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.64.090[1961 c 14 § 81.64.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1901c103.pdf?cite=1901%20c%20103%20§%201[1901 c 103 § 1]; RRS § 11073; ]

== 81.64.120 - Car equipment specified.
Every streetcar run or used on any streetcar line in the state of Washington shall be provided with good and substantial aprons, pilots or fenders, and which shall be so constructed as to prevent any person from being thrown down and run over or caught beneath or under such car.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.64.120[1961 c 14 § 81.64.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c94.pdf?cite=1897%20c%2094%20§%201[1897 c 94 § 1]; RRS § 11076. FORMER PART OF SECTION: 1911 c 117 § 66, part now codified in RCW  81.44.040; ]

== 81.64.130 - Penalty.
The owners or managers operating any streetcar line failing to comply with the provisions of RCW 81.64.120 shall forfeit and pay to the state of Washington a penalty of not less than twenty-five dollars for each and every violation of RCW 81.64.120 and each car run shall be considered a separate violation of RCW 81.64.120 and every period of five days shall be deemed a separate violation of RCW 81.64.120.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.64.130[1961 c 14 § 81.64.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c94.pdf?cite=1897%20c%2094%20§%202[1897 c 94 § 2]; RRS § 11077; ]

== 81.64.140 - Weather guards.
All corporations, companies or individuals owning, managing or operating any street railway or line in the state of Washington, shall provide, during the rain or winter season, all cars run or used on its or their respective roads with good, substantial and sufficient vestibules, or weather guards, for the protection of the employees of such corporation, company or individual.

The vestibules or weather guards shall be so constructed as to protect the employees of such company, corporation or individual from the wind, rain or snow.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.64.140[1961 c 14 § 81.64.140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c144.pdf?cite=1895%20c%20144%20§%201[1895 c 144 § 1]; RRS § 11078.   1895 c 144 § 2; RRS § 11079; ]

== 81.64.150 - Penalty.
Any such street railway company, corporation or individual, as mentioned in RCW 81.64.140, failing to comply with the provisions of RCW 81.64.140, shall forfeit and pay to the state of Washington a penalty of not less than fifty dollars nor more than two hundred and fifty dollars for each and every violation of RCW 81.64.140, and each period of ten days that any such company, corporation or individual shall fail to comply with the provisions of RCW 81.64.140, or for each car used by such corporation, company, or individual not in conformity with RCW 81.64.140, shall be taken and deemed to be a separate violation of RCW 81.64.140.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.64.150[1961 c 14 § 81.64.150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c144.pdf?cite=1895%20c%20144%20§%203[1895 c 144 § 3]; RRS § 11080; ]

== 81.64.160 - Hours of labor—Penalty.
. No person, agent, officer, manager, or superintendent or receiver of any corporation or owner of streetcars shall require his, her, or its grip operators, motor operators, drivers, or conductors to work more than ten hours in any twenty-four hours.

. Any person, agent, officer, manager, superintendent, or receiver of any corporation, or owner of streetcar or cars, violating this section is guilty of a misdemeanor, and shall be fined in any sum not less than twenty-five dollars nor more than one hundred dollars for each day in which such grip operator, motor operator, driver, or conductor in the employ of such person, agent, officer, manager, superintendent, or receiver of such corporation or owner is required to work more than ten hours during each twenty-four hours, as provided in this section.

. It is the duty of the prosecuting attorney of each county of this state to institute the necessary proceedings to enforce the provisions of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20306[2013 c 23 § 306]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20397[2003 c 53 § 397]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.64.160[1961 c 14 § 81.64.160]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c100.pdf?cite=1895%20c%20100%20§%201[1895 c 100 § 1]; RRS § 7648; ]

