= 81.08 - Securities.
:toc:

== 81.08.010 - Definition.
"Public service company," as used in this chapter, means every common carrier subject to regulation as to rates and service by the utilities and transportation commission under this title, except any "household goods carrier" subject to chapter 81.80 RCW or any "solid waste collection company" subject to chapter 81.77 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2018[2007 c 234 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c13.pdf?cite=1981%20c%2013%20§%203[1981 c 13 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c105.pdf?cite=1965%20ex.s.%20c%20105%20§%203[1965 ex.s. c 105 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.08.010[1961 c 14 § 81.08.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c248.pdf?cite=1959%20c%20248%20§%203[1959 c 248 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c205.pdf?cite=1957%20c%20205%20§%202[1957 c 205 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c95.pdf?cite=1953%20c%2095%20§%209[1953 c 95 § 9]; prior: 1933 c 151 § 1, part; RRS § 10439-1, part; ]

== 81.08.012 - "Evidence of indebtedness"—Limitation of term.
The term "evidence of indebtedness," as used in this chapter, shall not include conditional sales contracts or purchase money chattel mortgages.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.08.012[1961 c 14 § 81.08.012]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c227.pdf?cite=1951%20c%20227%20§%202[1951 c 227 § 2]; ]

== 81.08.020 - Control vested in state.
The power of public service companies to issue stocks and stock certificates or other evidence of interest or ownership, and bonds, notes and other evidences of indebtedness and to create liens on their property situated within this state is a special privilege, the right of supervision, regulation, restriction, and control of which is and shall continue to be vested in the state, and such power shall be exercised as provided by law and under such rules and regulations as the commission may prescribe.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.08.020[1961 c 14 § 81.08.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c151.pdf?cite=1933%20c%20151%20§%202[1933 c 151 § 2]; RRS § 10439-2; ]

== 81.08.030 - Authority to issue.
A public service company may issue stock and stock certificates or other evidence of interest or ownership, or bonds, notes or other evidence of indebtedness payable on demand or at periods of more than twelve months after the date thereof, for the following purposes only: The acquisition of property, or the construction, completion, extension, or improvement of its facilities, or the improvement or maintenance of its service, or the issuance of stock dividends, or the discharge or refunding of its obligations, or the reimbursement of moneys actually expended from income or from any other moneys in the treasury of the company not secured by or obtained from the issue of stock or stock certificates or other evidence of interest or ownership, or bonds, notes or other evidence of indebtedness of the company for any of the aforesaid purposes except maintenance of service, in cases where the applicant keeps its accounts and vouchers for such expenditures in such manner as to enable the commission to ascertain the amount of money so expended and the purpose for which the expenditure was made.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.08.030[1961 c 14 § 81.08.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c95.pdf?cite=1953%20c%2095%20§%2010[1953 c 95 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c30.pdf?cite=1937%20c%2030%20§%201[1937 c 30 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c151.pdf?cite=1933%20c%20151%20§%203[1933 c 151 § 3]; RRS § 10439-3; ]

== 81.08.040 - Prior to issuance—Filing required—Contents.
Any public service company that undertakes to issue stocks, stock certificates, other evidence of interest or ownership, bonds, notes, or other evidences of indebtedness shall file with the commission before such issuance:

. A description of the purposes for which the issuance is made, including a certification by an officer authorized to do so that the proceeds from any such financing is for one or more of the purposes allowed by this chapter;

. A description of the proposed issuance including the terms of financing; and

. A statement as to why the transaction is in the public interest.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2558.SL.pdf?cite=1994%20c%20251%20§%208[1994 c 251 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.08.040[1961 c 14 § 81.08.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c151.pdf?cite=1933%20c%20151%20§%204[1933 c 151 § 4]; RRS § 10439-4; ]

== 81.08.080 - Capitalization of franchise or merger contract prohibited.
The commission shall have no power to authorize the capitalization of the right to be a corporation, or to authorize the capitalization of any franchise or permit whatsoever or the right to own, operate or enjoy any such franchise or permit in excess of the amount (exclusive of any tax or annual charge) actually paid to the state or to a political subdivision thereof as the consideration for the grant of such franchise, permit or right; nor shall any contract for consolidation or lease be capitalized, nor shall any public service company hereafter issue any bonds, notes or other evidences of indebtedness against or as a lien upon any contract for consolidation or merger.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.08.080[1961 c 14 § 81.08.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c151.pdf?cite=1933%20c%20151%20§%207[1933 c 151 § 7]; RRS § 10439-7; ]

== 81.08.090 - Accounting for disposition of proceeds.
The commission shall have the power to require public service companies to account for the disposition of the proceeds of all sales of stocks and stock certificates or other evidence of interest or ownership, and bonds, notes and other evidences of indebtedness, in such form and detail as it may deem advisable, and to establish such rules and regulations as it may deem reasonable and necessary to insure the disposition of such proceeds for the purpose or purposes specified in its order.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.08.090[1961 c 14 § 81.08.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c151.pdf?cite=1933%20c%20151%20§%208[1933 c 151 § 8]; RRS § 10439-8; ]

== 81.08.100 - Issuance made contrary to this chapter—Penalties.
If a public service company issues any stock, stock certificate, or other evidence of interest or ownership, bond, note, or other evidence of indebtedness, contrary to the provisions of this chapter, the company may be subject to penalty under RCW 81.08.110 and 81.08.120.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2558.SL.pdf?cite=1994%20c%20251%20§%209[1994 c 251 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.08.100[1961 c 14 § 81.08.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c151.pdf?cite=1933%20c%20151%20§%209[1933 c 151 § 9]; RRS § 10439-9; ]

== 81.08.110 - Penalty against company.
Every public service company which, directly or indirectly, issues or causes to be issued, any stock or stock certificate or other evidence of interest or ownership, or bond, note, or other evidence of indebtedness, in nonconformity with the provisions of this chapter, or which applies the proceeds from the sale thereof, or any part thereof, to any purpose other than the purpose or purposes allowed by this chapter shall be subject to a penalty of not more than one thousand dollars for each offense. Every violation of any such order, rules, direction, demand, or requirement of the department, or of any provision of this chapter, shall be a separate and distinct offense and in case of a continuing violation every day's continuance thereof shall be deemed to be a separate and distinct offense.

The act, omission, or failure of any officer, agent, or employee of any public service company acting within the scope of his or her official duties or employment, shall in every case be deemed to be the act, omission, or failure of such public service company.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20293[2013 c 23 § 293]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2558.SL.pdf?cite=1994%20c%20251%20§%2010[1994 c 251 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.08.110[1961 c 14 § 81.08.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c151.pdf?cite=1933%20c%20151%20§%2011[1933 c 151 § 11]; RRS § 10439-11; ]

== 81.08.120 - Penalty against individual.
Every officer, agent, or employee of a public service company, and every other person who knowingly authorizes, directs, aids in, issues or executes, or causes to be issued or executed, any stock or stock certificate or other evidence of interest or ownership, or bond, note or other evidence of indebtedness contrary to the provisions of this chapter, or who knowingly makes any false statement or representation or with knowledge of its falsity files or causes to be filed with the commission any false statement or representation or causes or assists to be applied the proceeds or any part thereof, from the sale of any stock or stock certificate or other evidence of interest or ownership, or bond, note or other evidence of indebtedness, to any purpose not allowed by this chapter or who, with knowledge that any stock or stock certificate or other evidence of interest or ownership, or bond, note or other evidence of indebtedness, has been issued or executed in violation of any of the provisions of this chapter negotiates, or causes the same to be negotiated, shall be guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2558.SL.pdf?cite=1994%20c%20251%20§%2011[1994 c 251 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.08.120[1961 c 14 § 81.08.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c151.pdf?cite=1933%20c%20151%20§%2012[1933 c 151 § 12]; RRS § 10439-12; ]

== 81.08.130 - Assumption of obligation or liability—Compliance with filing requirements.
Any public service company that assumes any obligation or liability as guarantor, indorser, surety or otherwise in respect to the securities of any other person, firm or corporation, when such securities are payable at periods of more than twelve months after the date thereof, shall comply with the filing requirements of RCW 81.08.040.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2558.SL.pdf?cite=1994%20c%20251%20§%2012[1994 c 251 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.08.130[1961 c 14 § 81.08.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c151.pdf?cite=1933%20c%20151%20§%2013[1933 c 151 § 13]; RRS § 10439-13; ]

== 81.08.140 - State not obligated.
No provision of this chapter, and no deed or act done or performed under or in connection therewith, shall be held or construed to obligate the state of Washington to pay or guarantee, in any manner whatsoever, any stock or stock certificate or other evidence of interest or ownership, or bond, note or other evidence of indebtedness, authorized, issued or executed under the provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.08.140[1961 c 14 § 81.08.140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c151.pdf?cite=1933%20c%20151%20§%2014[1933 c 151 § 14]; RRS § 10439-14; ]

== 81.08.150 - Authority of commission—Not affected by requirements of this chapter.
No action by a public service company in compliance with nor by the commission in conformance with the requirements of this chapter may in any way affect the authority of the commission over rates, service, accounts, valuations, estimates, or determinations of costs, or any matters whatsoever that may come before it.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2558.SL.pdf?cite=1994%20c%20251%20§%2013[1994 c 251 § 13]; ]

