= 81.75 - Transportation centers.
:toc:

== 81.75.010 - Authorization to own and operate—Purpose.
It is desirable to a transportation system that convenient and comfortable terminals be established and maintained with the services of all modes of public transportation available to the public at such a center to the extent feasible. It is proper that cities, towns, counties, public transportation benefit area authorities, and municipal corporations of this state be authorized to own and operate transportation centers.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c217.pdf?cite=1977%20ex.s.%20c%20217%20§%201[1977 ex.s. c 217 § 1]; ]

== 81.75.020 - Method of acquisition and operation prescribed—Grants—Consolidation of activities.
Through its council or other legislative body, any city, town, county, public transportation benefit area authority, or other municipal corporation, authorized to operate public transportation services, may construct or otherwise acquire intermodal transportation centers by donation, lease, or purchase and may operate or let for purposes of leasing space at fair market value for the services set forth in RCW 81.75.030, and to perform other functions permitted by law, the centers or portions of the centers, for public or private purposes or for compensation or rental upon such conditions as its council or other legislative body shall from time to time prescribe. The city, town, county, public transportation benefit area authority, or municipal corporation, may apply for and receive grants from the federal government for purposes of funding a transportation center and may consolidate a transportation center with other lawful city or town activities.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c217.pdf?cite=1977%20ex.s.%20c%20217%20§%202[1977 ex.s. c 217 § 2]; ]

== 81.75.030 - Services available—Terms of usage.
To the extent feasible, the services available to the public at any transportation center may include taxi, auto rental, passenger trains, motor buses, travel agents, restrooms, food, telegraph, baggage handling, transfer and delivery of light freight and packages, commercial airlines, air charter, place of temporary rest for citizens and travelers (but not overnight), mail, private auto parking for users of public transportation through the transportation center, local transit, limousine, and any other use necessary to the foregoing.

Any city, town, county, public transportation benefit area authority, or municipal corporation, which elects to operate a transportation center shall operate the center for the general public good. The operator may establish the terms of usage for the various modes of transportation and for others that utilize its facilities, may make reasonable rules concerning public and private use, and may exclude all persons therefrom who refuse to comply with the terms or rules of use. The operator may own, operate, maintain, and manage a transportation center, but shall not engage in providing a transportation or other related service at the center unless otherwise authorized by law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c217.pdf?cite=1977%20ex.s.%20c%20217%20§%203[1977 ex.s. c 217 § 3]; ]

