= 81.60 - Railroads—Railroad police and regulations.
:toc:

== 81.60.010 - Criminal justice training commission may appoint railroad police officers.
The criminal justice training commission shall have the power to and may in its discretion appoint and commission railroad police officers at the request of any railroad corporation and may revoke any appointment at its pleasure.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1067.SL.pdf?cite=2001%20c%2072%20§%201[2001 c 72 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.60.010[1961 c 14 § 81.60.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c118.pdf?cite=1915%20c%20118%20§%201[1915 c 118 § 1]; RRS § 10542; ]

== 81.60.020 - Application for appointment.
Any railroad corporation desiring the appointment of any of its officers, agents, or servants not exceeding twenty-five in number for any one division of any railroad operating in this state as railroad police officers shall file a request with the criminal justice training commission on an approved application form. The application shall be signed by the president or some managing officer of the railroad corporation and shall be accompanied by an affidavit stating that the officer is acquainted with the person whose appointment is sought, that the officer believes the person to be of good moral character, and that the person is of such character and experience that he or she can be safely entrusted with the powers of a police officer.

For the purposes of this section, "division" means the part of any railroad or railroads under the jurisdiction of any one division superintendent.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1067.SL.pdf?cite=2001%20c%2072%20§%202[2001 c 72 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.60.020[1961 c 14 § 81.60.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c99.pdf?cite=1955%20c%2099%20§%201[1955 c 99 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c118.pdf?cite=1915%20c%20118%20§%202[1915 c 118 § 2]; RRS § 10543; ]

== 81.60.030 - Oath.
Before receiving a commission each person appointed under the provisions of RCW 81.60.010 through 81.60.060 shall successfully complete a course of training prescribed or approved by the criminal justice training commission, and shall take, subscribe, and file with the commission an oath to support the Constitution of the United States and the Constitution and laws of the state of Washington, and to faithfully perform the duties of the office. The corporation requesting appointment of a railroad police officer shall bear the full cost of training.

Railroad police officers appointed and commissioned under RCW 81.60.010 through 81.60.060 are subject to rules and regulations adopted by the commission.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1067.SL.pdf?cite=2001%20c%2072%20§%203[2001 c 72 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.60.030[1961 c 14 § 81.60.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c118.pdf?cite=1915%20c%20118%20§%203[1915 c 118 § 3]; RRS § 10544; ]

== 81.60.040 - Duties.
Every police officer appointed and commissioned under the provisions of RCW 81.60.010 through 81.60.060 shall when on duty have the power and authority conferred by law on peace officers, but shall exercise such power only in the protection of the property belonging to or under the control of the corporation at whose instance the officer is appointed and in preventing, and making arrest for, violations of law upon or in connection with such property.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1067.SL.pdf?cite=2001%20c%2072%20§%204[2001 c 72 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.60.040[1961 c 14 § 81.60.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c118.pdf?cite=1915%20c%20118%20§%204[1915 c 118 § 4]; RRS § 10545; ]

== 81.60.050 - Badge.
Every railroad police officer shall, when on duty, wear in plain view a badge bearing the words "railroad police" and the name of the corporation by which the officer is employed, or carry, and present upon request, official credentials identifying the railroad police officer and corporation.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1067.SL.pdf?cite=2001%20c%2072%20§%205[2001 c 72 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.60.050[1961 c 14 § 81.60.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c118.pdf?cite=1915%20c%20118%20§%205[1915 c 118 § 5]; RRS § 10546; ]

== 81.60.060 - Liability for unlawful acts.
The corporation procuring the appointment of any railroad police shall be solely responsible for the compensation for the officer's services and shall be liable civilly for any unlawful act of the officer resulting in damage to any person or corporation.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1067.SL.pdf?cite=2001%20c%2072%20§%206[2001 c 72 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.60.060[1961 c 14 § 81.60.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c118.pdf?cite=1915%20c%20118%20§%206[1915 c 118 § 6]; RRS § 10547; ]

== 81.60.070 - Malicious injury to railroad property.
Every person who, in such manner as might, if not discovered, endanger the safety of any engine, motor, car or train, or any person thereon, shall in any manner interfere or tamper with or obstruct any switch, frog, rail, roadbed, sleeper, viaduct, bridge, trestle, culvert, embankment, structure, or appliance pertaining to or connected with any railway, or any train, engine, motor, or car on such railway, and every person who shall discharge any firearm or throw any dangerous missile at any train, engine, motor, or car on any railway, is guilty of a class B felony and shall be punished by imprisonment in a state correctional facility for not more than ten years.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20394[2003 c 53 § 394]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1544.SL.pdf?cite=1999%20c%20352%20§%204[1999 c 352 § 4]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2263-S.SL.pdf?cite=1992%20c%207%20§%2060[1992 c 7 § 60]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.60.070[1961 c 14 § 81.60.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20398[1909 c 249 § 398]; RRS § 2650; ]

== 81.60.080 - Sabotaging rolling stock—Receiving stolen railroad property.
. Any person or persons who shall willfully or maliciously, with intent to injure or deprive the owner thereof, take, steal, remove, change, add to, alter, or in any manner interfere with any journal bearing, brass, waste, packing, triple valve, pressure cock, brake, air hose, or any other part of the operating mechanism of any locomotive, engine, tender, coach, car, caboose, or motor car used or capable of being used by any railroad or railway company in this state, is guilty of a class C felony, and upon conviction thereof shall be punished by imprisonment in a state correctional facility for not more than five years, or by a fine not exceeding one thousand dollars, or by both such fine and imprisonment.

. Every person who buys or receives any of the property described in subsection (1) of this section, knowing the same to have been stolen, is guilty of a class C felony, and upon conviction thereof shall be punished as provided in subsection (1) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20395[2003 c 53 § 395]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2263-S.SL.pdf?cite=1992%20c%207%20§%2061[1992 c 7 § 61]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.60.080[1961 c 14 § 81.60.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c212.pdf?cite=1941%20c%20212%20§%201[1941 c 212 § 1]; Rem. Supp. 1941 § 2650-1; ]

