= 81.40 - Railroads—Employee requirements and regulations.
:toc:

== 81.40.005 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Class I" means a railroad carrier designated as a class I railroad by the United States surface transportation board and its subsidiaries or is owned and operated by entities whose combined total railroad operational ownership and controlling interest meets the United States surface transportation board designation as a class I railroad carrier.

. "Class III" means a railroad carrier designated as a class III railroad by the United States surface transportation board.

. "Commission" means the utilities and transportation commission created in chapter 80.01 RCW.

. "Crewmember" means a railroad operating craft employee who has been trained and meets the requirements and qualifications as determined by the federal railroad administration for a railroad operating service employee.

. "Other railroad carrier" means a railroad carrier that is not a class I carrier.

. "Railroad carrier" means a carrier of persons or property upon vehicles, other than streetcars, operated upon stationary rails, the route of which is principally outside incorporated cities and towns. "Railroad carrier" includes any officers and agents of the railroad carrier.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1841.SL.pdf?cite=2020%20c%20170%20§%202[2020 c 170 § 2]; ]

== 81.40.015 - Operation and management of trains, switching assignments—Exemption.
. Except as provided in RCW 81.40.025, any person, corporation, company, or officer of the court operating any railroad, railway, or any part of any railroad or railway, in the state of Washington, and engaged, as a common carrier, in the transportation of freight or passengers, shall operate and manage all trains and switching assignments over its road with crews consisting of no less than two crewmembers.

. Class III railroad carriers operating on their roads while at a speed of twenty-five miles per hour or less are exempt from subsection (1) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1841.SL.pdf?cite=2020%20c%20170%20§%203[2020 c 170 § 3]; ]

== 81.40.025 - Train crew size requirement—Automatic waivers—Commission.
. On June 11, 2020, automatic waivers to the train crew size requirement in RCW 81.40.015 shall be granted to other railroad carriers.

. Such automatic waivers will remain in effect until ordered by the commission.

. The commission must act to ensure that railroad carriers supplement trains entering Washington state with the requisite number of train crewmembers pursuant to chapter 170, Laws of 2020, at the closest regular station stop or crew change point located in proximity to and adjacent with either side of the state border, having been established and in use by the carrier on January 1, 2020.

. [Empty]
.. The commission may order railroad carriers to increase the number of railroad employees in areas of increased risk to the public, passengers, railroad employees, or the environment, or on specific trains, routes, or to switch assignments on their road with additional numbers of crewmembers, and may direct the placement of additional crewmembers, if it is determined that such an increase in staffing or the placement of additional crewmembers is necessary to protect the safety, health, and welfare of the public, passengers, or railroad employees, to prevent harm to the environment or to address site specific safety or security hazards.

.. In issuing such an order, the commission may consider relevant factors including, but not limited to, the volatility of the commodities being transported, train volume, risk mitigation measures, environmental and operating factors that impact vulnerabilities, risk exposure to passengers, the general public, railroad employees, communities, or the environment along the train route, security risks including sabotage or terrorism threat levels, a railroad carrier's prior history of accidents, compliance violations, operating practices, infrastructure investments including track and equipment maintenance issues or lack thereof, employee training and support programs, first responder access, and any other relevant factors in the interest of safety.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1841.SL.pdf?cite=2020%20c%20170%20§%204[2020 c 170 § 4]; ]

== 81.40.060 - Purchase of apparel by employees—Penalty.
. It shall be unlawful for any railroad or other transportation company doing business in the state of Washington, or of any officer, agent, or servant of such railroad or other transportation company, to require any conductor, engineer, brake operator, fire tender, purser, or other employee, as a condition of his or her continued employment, or otherwise to require or compel, or attempt to require or compel, any such employees to purchase of any such railroad or other transportation company or of any particular person, firm, or corporation or at any particular place or places, any uniform or other clothing or apparel, required by any such railroad or other transportation company to be used by any such employee in the performance of his or her duties as such; and any such railroad or transportation company or any officer, agent or servant thereof, who shall order or require any conductor, engineer, brake operator, fire tender, purser, or other person in its employ, to purchase any uniform or other clothing or apparel as aforesaid, shall be deemed to have required such purchase as a condition of such employee's continued employment.

. Any railroad or other transportation company doing business in the state of Washington, or any officer, agent, or servant thereof, violating this section is guilty of a misdemeanor and upon conviction thereof shall be punished by a fine in any sum not less than one hundred dollars nor more than five hundred dollars, or by imprisonment in the county jail of the county where the misdemeanor is committed, not exceeding six months.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20296[2013 c 23 § 296]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20388[2003 c 53 § 388]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.40.060[1961 c 14 § 81.40.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c224.pdf?cite=1907%20c%20224%20§%201[1907 c 224 § 1]; RRS § 10504; ]

== 81.40.080 - Employee shelters—Penalty.
. It shall be unlawful for any railroad company, corporation, association or other person owning, controlling or operating any line of railroad in the state of Washington, to build, construct, reconstruct, or repair railroad car equipment or motive power in this state without first erecting and maintaining at every point where five employees or more are regularly employed on such work, a shed over a sufficient portion of the tracks used for such work, so as to provide that all persons regularly employed in such work shall be sheltered and protected from rain and other inclement weather: PROVIDED, That the provisions of this section shall not apply at points where it is necessary to make light repairs only on equipment or motive power, nor to equipment loaded with time or perishable freight, nor to equipment when trains are being held for the movement of equipment, nor to equipment on tracks where trains arrive or depart or are assembled or made up for departure. The term "light repairs," as herein used, shall not include repairs usually made in roundhouse, shop or shed upon well equipped railroads.

. Any railroad company or officer or agent thereof, or any other person, who violates this section by failing or refusing to comply with its provisions is guilty of a misdemeanor, and each day's failure or refusal to comply shall be considered a separate offense.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%201030[2009 c 549 § 1030]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20389[2003 c 53 § 389]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.40.080[1961 c 14 § 81.40.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c238.pdf?cite=1941%20c%20238%20§%201[1941 c 238 § 1]; Rem. Supp. 1941 § 7666-40; ]

== 81.40.095 - Rules and regulations—Railroad employees—Sanitation, shelter.
The utilities and transportation commission shall adopt and enforce rules and regulations relating to sanitation and adequate shelter as it affects the health of all railroad employees, including but not limited to railroad workers, maintenance of way employees, highway crossing watchpersons, clerical, platform, freight house and express employees.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5063.SL.pdf?cite=2007%20c%20218%20§%2082[2007 c 218 § 82]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.40.095[1961 c 14 § 81.40.095]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c71.pdf?cite=1957%20c%2071%20§%201[1957 c 71 § 1]; ]

== 81.40.110 - Flagger must read, write, and speak English.
Any railroad operating within this state, shall not employ or use as flagger any person or persons who cannot read, write, and speak the English language.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20297[2013 c 23 § 297]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.40.110[1961 c 14 § 81.40.110]; 1907 c 138 § 1, part; 1899 c 35 § 1, part; RRS § 10480, part; ]

== 81.40.130 - Cost of records or medical examinations—Unlawful to require employee or applicant to pay—Penalty—Definitions.
. It is unlawful for any employer to require any employee or applicant for employment to pay the cost of a medical examination or the cost of furnishing any records required by the employer as a condition of employment.

. Any employer who violates this section is guilty of a misdemeanor and upon conviction shall be punished by a fine of not more than one hundred dollars. Each violation shall constitute a separate offense.

. As used in this section:

.. "Employer" means any common carrier by rail, doing business in or operating within the state, and any subsidiary thereof.

.. "Employee" means every person who may be permitted, required, or directed by any employer, in consideration of direct or indirect gain or profit, to engage in any employment.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20390[2003 c 53 § 390]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.40.130[1961 c 14 § 81.40.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c228.pdf?cite=1955%20c%20228%20§%202[1955 c 228 § 2]; ]

== 81.40.150 - Safety and protection—Violation—Fines.
. Pursuant to the enforcement of the provisions of chapter 170, Laws of 2020, the highest priority and paramount obligation of the commission must be its duty to ensure the safety and protection of the public, passengers, railroad employees, communities, environment, and areas of cultural significance in the furtherance of the highest degree of safety in railroad transportation.

. Each train or engine run in violation of RCW 81.40.015 constitutes a separate offense. However, RCW 81.40.015 does not apply in the case of disability of one or more members of any train crew while out on the road between division terminals, or assigned to wrecking trains.

. Any person, corporation, company, or officer of the court operating any railroad, or part of any railroad or railway within the state of Washington, and engaged as a common carrier, in the transportation of freight or passengers, who violates any of the provisions of RCW 81.40.015 may be subject to fines of not less than one thousand dollars and not more than one hundred thousand dollars for each offense, as determined by the commission through order.

. The commission may impose fines exceeding the provisions in subsection (3) of this section when a serious injury or fatality occurs involving a carrier's violation of chapter 170, Laws of 2020. All relevant factors may be considered including, but not limited to, the class, assets, profitability, and operational safety record of the carrier, as well as deterrence in ascertaining an appropriate punitive penalty, as determined by the commission through order.

. It is the duty of the commission to enforce this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1841.SL.pdf?cite=2020%20c%20170%20§%205[2020 c 170 § 5]; ]

