= 81.88 - Gas and hazardous liquid pipelines.
:toc:

== 81.88.005 - Intent—Findings.
. The intent of chapter 191, Laws of 2000 is to protect the health and safety of the citizens of the state of Washington and the quality of the state's environment by developing and implementing environmental and public safety measures applicable to persons transporting hazardous liquids and gas by pipeline within the state of Washington. The legislature finds that public safety and the environment may best be protected by adopting standards that are equal to, or more stringent than, those adopted by the federal government, so long as they do not impermissibly interfere with interstate commerce.

. The legislature recognizes that additional federal authority is needed to implement a comprehensive pipeline safety program and by chapter 191, Laws of 2000 and other measures directs the state to seek that authority.

. It is also the intent of the legislature that the governor work with the state congressional delegation in seeking:

.. To amend the federal pipeline safety act to delegate authority to qualified states to adopt and enforce standards equal to or more stringent than federal standards;

.. State authority to administer and enforce federal requirements related to pipeline safety; and

.. Higher levels of funding for state and federal pipeline safety activities and for states to respond to pipeline accident emergencies.

. While the legislature acknowledges that serious accidents have occurred for hazardous liquid and gas pipelines in this nation and elsewhere, it recognizes that there are fundamental differences between hazardous liquid pipelines and gas pipelines and that a different system of safety regulations must be applied for each kind of pipeline.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2420-S2.SL.pdf?cite=2000%20c%20191%20§%201[2000 c 191 § 1]; ]

== 81.88.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Commission" means the utilities and transportation commission.

. "Gas" means natural gas, flammable gas, or toxic or corrosive gas.

. "Gas pipeline" means all parts of a pipeline facility through which gas moves in transportation, including, but not limited to, line pipe, valves, and other appurtenances connected to line pipe, compressor units, metering stations, regulator stations, delivery stations, holders, and fabricated assemblies. "Gas pipeline" does not include any pipeline facilities, other than a master meter system, owned by a consumer or consumers of the gas, located exclusively on the consumer or consumers' property, and none of the gas leaves that property through a pipeline.

. "Gas pipeline company" means a person or entity constructing, owning, or operating a gas pipeline for transporting gas. "Gas pipeline company" includes a person or entity owning or operating a master meter system. "Gas pipeline company" does not include excavation contractors or other contractors that contract with a gas pipeline company.

. "Hazardous liquid" means: (a) Petroleum, petroleum products, or anhydrous ammonia as those terms are defined in 49 C.F.R. Part 195; and (b) carbon dioxide.

. "Hazardous liquid pipeline" means all parts of a pipeline facility through which a hazardous liquid moves in transportation including, but not limited to, line pipe, valves, and other appurtenances connected to line pipe, pumping units, fabricated assemblies associated with pumping units, metering and delivery stations and fabricated assemblies therein, and breakout tanks. "Hazardous liquid pipeline" does not include all parts of a pipeline facility through which a hazardous liquid moves in transportation through refining or manufacturing facilities or storage or in-plant piping systems associated with such facilities, a pipeline subject to safety regulations of the United States coast guard, or a pipeline that serves refining, manufacturing, or truck, rail, or vessel terminal facilities, if the pipeline is less than one mile long, measured outside facility grounds, and does not cross an offshore area or a waterway used for commercial navigation.

. "Hazardous liquid pipeline company" means a person or entity constructing, owning, or operating a hazardous liquid pipeline. "Hazardous liquid pipeline company" does not include excavation contractors or other contractors that contract with a hazardous liquid pipeline company.

. "Line pipe" means a tube, usually cylindrical, through which a hazardous liquid or gas is transported from one point to another.

. "Local government" means a political subdivision of the state.

. "Master meter system" means a pipeline system for distributing gas within, but not limited to, a definable area, such as a mobile home park, housing project, or apartment complex, where the operator purchases metered gas from an outside source for resale through a gas distribution pipeline system. The gas distribution pipeline system supplies the ultimate consumer who either purchases the gas directly through a meter or by any other means, such as by rents.

. "Person" means an individual, partnership, franchise holder, association, corporation, a state, a city, a town, a county, or any other political subdivision or instrumentality of a state, and its employees, agents, or legal representatives.

. "Pipeline company," without further qualification, means a hazardous liquid pipeline company or a gas pipeline company.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5225-S.SL.pdf?cite=2007%20c%20142%20§%201[2007 c 142 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5182-S.SL.pdf?cite=2001%20c%20238%20§%206[2001 c 238 § 6]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2420-S2.SL.pdf?cite=2000%20c%20191%20§%202[2000 c 191 § 2]; ]

== 81.88.020 - Pipeline corporations—Regulation—Eminent domain.
All corporations having for one of their principal purposes the construction, maintenance and operation of pipelines and appurtenances for the conveyance and transportation as common carriers of oils, gas, gasoline and other petroleum products shall be subject to control and regulation by the commission in the same manner and to the same extent as other public service corporations. The power of eminent domain is hereby conferred upon such corporations to be used for acquiring rights-of-way for common carrier pipelines and they shall have the right to condemn and appropriate lands and property and interests therein for their use under the same procedure as is provided for the condemnation and appropriation of private property by railway companies, but no private property shall be taken or damaged until the compensation to be made therefor shall have been ascertained and paid as provided in the case of condemnation and appropriation by railway companies. Any property or interest therein acquired by any corporation under the provisions of this section by the exercise of the right of eminent domain shall be used exclusively for the purposes for which it was acquired. In all actions brought under this section to enforce the right of eminent domain, courts wherein such actions are brought may give such actions preference over all other civil actions in the matter of setting the same for hearing or trial and in hearing the same.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.88.020[1961 c 14 § 81.88.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c94.pdf?cite=1951%20c%2094%20§%202[1951 c 94 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c132.pdf?cite=1915%20c%20132%20§%202[1915 c 132 § 2]; RRS § 9965; ]

== 81.88.030 - Pipeline carriers regulated as common carriers.
Every person, copartnership, corporation or other association now or hereafter engaged in the business of producing from natural deposits and/or carrying or transporting natural gas and/or crude oil or petroleum or the products thereof for hire, by pipelines within this state shall be a common carrier within the meaning and subject to the provisions of this title: PROVIDED, HOWEVER, That the provisions of this section shall not apply to distribution systems owned and operated under franchise for the sale, delivery, or distribution of natural gas at retail.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.88.030[1961 c 14 § 81.88.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933ex1c61.pdf?cite=1933%20ex.s.%20c%2061%20§%201[1933 ex.s. c 61 § 1]; RRS § 9965-1; ]

== 81.88.040 - Violations—Rules—Penalties—Injunctive relief.
. A person, officer, agent, or employee of a pipeline company who, as an individual or acting as an officer, agent, or employee of such a company, violates or fails to comply with this chapter or a rule adopted under RCW 81.88.060 or 81.88.065, or who procures, aids, or abets another person or entity in the violation of or noncompliance with this chapter or a rule adopted under RCW 81.88.060 or 81.88.065, is guilty of a gross misdemeanor.

. [Empty]
.. A pipeline company, or any person, officer, agent, or employee of a pipeline company that violates a provision of this chapter, or a rule adopted under RCW 81.88.060 or 81.88.065, is subject to a civil penalty to be assessed by the commission.

.. The commission shall adopt rules: (i) Setting penalty amounts, but may not exceed the penalties specified in the federal pipeline safety laws, 49 U.S.C. Sec. 60101 et seq.; and (ii) establishing procedures for mitigating penalties assessed.

.. In determining the amount of the penalty in a particular instance, the commission shall consider: (i) The appropriateness of the penalty in relation to the position of the person charged with the violation; (ii) the gravity of the violation; and (iii) the good faith of the person or company charged in attempting to achieve compliance after notification of the violation.

.. The amount of the penalty may be recovered in a civil action in the superior court of Thurston county or of some other county in which the violator may do business. In all actions for recovery, the rules of evidence shall be the same as in ordinary civil actions. All penalties recovered under this section must be paid into the state treasury and credited to the pipeline safety account.

. The commission shall adopt rules incorporating by reference other substances designated as hazardous by the secretary of transportation under 49 U.S.C. Sec. 60101(a)(4).

. The commission may seek injunctive relief to enforce the provisions of this chapter.

. Nothing in this section duplicates the authority of the energy facility site evaluation council under chapter 80.50 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5225-S.SL.pdf?cite=2007%20c%20142%20§%202[2007 c 142 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2420-S2.SL.pdf?cite=2000%20c%20191%20§%203[2000 c 191 § 3]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6358-S.SL.pdf?cite=1998%20c%20123%20§%201[1998 c 123 § 1]; ]

== 81.88.050 - Pipeline safety account.
The pipeline safety account is created in the custody of the state treasurer. All fees received by the commission for the pipeline safety program according to RCW 80.24.060 and 81.24.090 and all receipts from the federal office of pipeline safety and any other state or federal funds provided for pipeline safety shall be deposited in the account. Any penalties collected under this chapter, or otherwise designated to this account must be deposited in the account. Moneys in the account may be spent only after appropriation. Expenditures from the account may be used only for funding pipeline safety.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5225-S.SL.pdf?cite=2007%20c%20142%20§%203[2007 c 142 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5182-S.SL.pdf?cite=2001%20c%20238%20§%207[2001 c 238 § 7]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2420-S2.SL.pdf?cite=2000%20c%20191%20§%204[2000 c 191 § 4]; ]

== 81.88.060 - Hazardous liquid pipelines—Safety—Commission's duties.
. Each hazardous liquid pipeline company shall design, construct, operate, and maintain its hazardous liquid pipeline so that it is safe and efficient. Each hazardous liquid pipeline company is responsible for the conduct of its contractors regarding compliance with pipeline safety requirements.

. The commission shall develop and administer a comprehensive program of pipeline safety in accordance with this chapter.

. The commission may adopt rules to carry out the purposes of this chapter as long as the rules are compatible with minimum federal requirements.

. The commission shall coordinate information related to hazardous liquid pipeline safety by providing technical assistance to local planning and siting authorities.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5225-S.SL.pdf?cite=2007%20c%20142%20§%204[2007 c 142 § 4]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5182-S.SL.pdf?cite=2001%20c%20238%20§%209[2001 c 238 § 9]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2420-S2.SL.pdf?cite=2000%20c%20191%20§%205[2000 c 191 § 5]; ]

== 81.88.065 - Gas pipelines—Safety—Commission's duties.
. Each gas pipeline company shall design, construct, operate, and maintain its gas pipeline so that it is safe and efficient. Each gas pipeline company is responsible for the conduct of its contractors regarding compliance with pipeline safety requirements.

. The commission shall develop and administer a comprehensive program of gas pipeline safety in accordance with this chapter.

. The commission may adopt rules to carry out the purposes of this chapter as long as the rules are compatible with minimum federal requirements.

. The commission shall coordinate information related to natural gas pipeline safety by providing technical assistance to local planning and siting authorities.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5225-S.SL.pdf?cite=2007%20c%20142%20§%205[2007 c 142 § 5]; ]

== 81.88.070 - Prevention of third-party excavation damage—Development and distribution of training curricula.
. The commission shall develop, in consultation with representatives of hazardous liquid pipeline companies, gas pipeline companies, local governments, and the excavation and construction industries: (a) A curricula aimed at the prevention of third-party excavation damage to hazardous liquid pipelines and gas pipelines; and (b) a plan for distribution of the curricula.

. The curricula shall include training on:

.. Prevention of damage to hazardous liquid and gas pipelines;

.. The danger involved if a hazardous liquid or gas pipeline is damaged;

.. The significance of hazardous liquid or gas pipeline damage that does not cause immediate failure; and

.. The importance of immediately reporting damage to a hazardous liquid or gas pipeline and the importance of immediately repairing a damaged hazardous liquid or gas pipeline.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2420-S2.SL.pdf?cite=2000%20c%20191%20§%206[2000 c 191 § 6]; ]

== 81.88.080 - Pipeline mapping system—Commission specifications and evaluations.
. The commission shall require hazardous liquid pipeline companies, and gas pipeline companies with interstate pipelines, or gas pipelines operating over two hundred fifty pounds per square inch gauge, to provide accurate maps of these pipelines to specifications developed by the commission sufficient to meet the needs of first responders.

. The commission shall evaluate the sufficiency of the maps and consolidate the maps into a statewide geographic information system. The commission shall assist local governments in obtaining hazardous liquid and gas pipeline location information and maps. The maps shall be made available to the one-number locator services as provided in chapter 19.122 RCW. The mapping system shall be consistent with the United States department of transportation national pipeline mapping program.

. The commission shall periodically update the mapping system.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5225-S.SL.pdf?cite=2007%20c%20142%20§%206[2007 c 142 § 6]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2420-S2.SL.pdf?cite=2000%20c%20191%20§%207[2000 c 191 § 7]; ]

== 81.88.090 - Federal certification for pipeline safety program—Commission's duties.
The commission shall maintain federal certification for the state's pipeline safety program. The commission, at a minimum, shall do the following:

. Inspect hazardous liquid pipelines and gas pipelines periodically as specified in the inspection program;

. Collect fees;

. Order and oversee the testing of hazardous liquid pipelines and gas pipelines as authorized by federal law and regulation; and

. File reports with the United States secretary of transportation as required to maintain federal certification.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5225-S.SL.pdf?cite=2007%20c%20142%20§%207[2007 c 142 § 7]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5182-S.SL.pdf?cite=2001%20c%20238%20§%2010[2001 c 238 § 10]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2420-S2.SL.pdf?cite=2000%20c%20191%20§%209[2000 c 191 § 9]; ]

== 81.88.100 - Commission inspection of records, maps, or written procedures.
The commission may inspect any record, map, or written procedure required by federal law to be kept by a pipeline company concerning releases, and the design, construction, testing, or operation and maintenance of pipelines. Nothing in this section affects the commission's access to records under any other provision of law.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5225-S.SL.pdf?cite=2007%20c%20142%20§%208[2007 c 142 § 8]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2420-S2.SL.pdf?cite=2000%20c%20191%20§%2011[2000 c 191 § 11]; ]

== 81.88.110 - Pipeline company duties after notice of excavation.
A pipeline company that has been notified by an excavator that excavation work will occur near a hazardous liquid pipeline shall ensure that the pipeline company's representative consults with the excavator on-site prior to the excavation. The pipeline company has the discretion to require that the pipeline section in the vicinity of the excavation is fully uncovered and examined for damage prior to being reburied.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2420-S2.SL.pdf?cite=2000%20c%20191%20§%2021[2000 c 191 § 21]; ]

== 81.88.140 - Citizens committee on pipeline safety—Duties—Membership.
. The citizens committee on pipeline safety is established to advise the state agencies and other appropriate federal and local government agencies and officials on matters relating to hazardous liquid and gas pipeline safety, routing, construction, operation, and maintenance. The committee shall serve as an advisory committee for the commission on matters relating to the commission's pipeline safety programs and activities. The commission shall consult with and provide periodic reports to the committee on matters related to the commission's pipeline safety programs and activities, including but not limited to the development and regular review of funding elements for pipeline safety programs and activities.

. The committee shall have thirteen total members who shall be appointed by the governor to staggered three-year terms and shall consist of: (a) Nine members representing local government, including elected officials and the public; and (b) four nonvoting members, representing owners and operators of hazardous liquid and gas pipelines. All members of the committee, voting and nonvoting, may participate fully in the committee's meetings, activities, and deliberations and shall timely receive all notices and information related to committee business and decisions.

. The committee shall review and comment on proposed rules and the operation of the state pipeline safety programs.

. The committee may create one or more technical advisory committees comprised of gas and hazardous liquid pipeline owners or operators, agency representatives, natural resource and environmental interests, or other interested parties.

. The committee established in this section constitutes a class one group under RCW 43.03.220. Expenses for this group, as well as staff support, shall be provided by the utilities and transportation commission.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5182-S.SL.pdf?cite=2001%20c%20238%20§%2011[2001 c 238 § 11]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2420-S2.SL.pdf?cite=2000%20c%20191%20§%2014[2000 c 191 § 14]; ]

== 81.88.160 - Gas pipeline company report to the commission—Known leaks in pipelines—Information required—Estimated volume of leaked gas—Provision of information on commission's website—Transmission of information to department of ecology—Certain information exempt from disclosure.
. Beginning March 15, 2021, and on an annual basis thereafter, each gas pipeline company must submit a report to the commission that includes:

.. The total number of known leaks in pipelines owned by the gas pipeline company as of January 1st of the year the report is submitted;

.. The total number of hazardous leaks eliminated or repaired during the previous one-year period ending December 31st;

.. The total number of nonhazardous leaks eliminated or repaired during the previous one-year period ending December 31st;

.. The total number of leaks scheduled for repair in the next one-year period beginning January 1st of the year the report is submitted. The data provided in this subsection (1)(d) does not obligate the gas pipeline company to repair all leaks scheduled for repair, nor does it prevent the gas pipeline company from prioritizing its repair schedule based on new information and newly-identified leaks.

. Natural gas leaks include all confirmed discoveries of unintentional leak events, including leaks from: Corrosion failure; natural force damage; excavation damage; other outside force damage; pipe, weld, or joint failure; equipment failure; or other causes.

. The commission may determine information requirements for the annual reports submitted under subsection (1) of this section including, but not limited to:

.. The approximate date and location of each leak from the gas pipeline system detected by the company during its routine course of inspection;

.. The approximate date and location of each leak caused by third-party excavation or other causes not attributable to the normal operation or inspection practices of the company;

.. Whether the reported leaks are included as part of a filing submitted and approved by the commission under RCW 80.28.420;

.. The volume of each leak, measured in carbon dioxide equivalents and thousands of cubic feet, except that where an exact volume of gas leaked cannot be identified, a gas pipeline company may provide its best approximation;

.. Whether the identified cause of each leak was from: Corrosion failure; natural force damage; excavation damage; other outside force damage; pipe, weld, or joint failure; equipment failure; or other causes;

.. The estimated market value of lost gas and the methodology used to measure the loss of gas; and

.. Any additional information required in an order approved by the commission.

. The commission must use the data reported by gas pipeline companies under this section, as well as other data reported by gas pipeline companies to the commission and to the department of ecology, to estimate the volume of leaked gas and associated greenhouse gas emissions from operational practices in the state. The commission may request additional information by order.

. By March 31, 2021, and on an annual basis thereafter, the commission must provide on its public internet website aggregate data, as submitted by gas pipeline companies under this section, concerning the volume and causes of gas leaks.

. By March 31, 2021, and on an annual basis thereafter, the commission must transmit to the department of ecology information on gas leakage in the state, as submitted by gas pipeline companies under this section.

. Those portions of reports submitted by gas pipeline companies to the commission under this section that contain proprietary data, trade secrets, or if disclosure would adversely affect public safety, are exempt from public inspection and copying under chapter 42.56 RCW.

. For the purposes of this section, "carbon dioxide equivalents" has the same meaning as provided in RCW 70A.45.010.

. Nothing in this section may be construed to preempt the process by which a gas pipeline company is required to petition relevant state or local authorities when seeking to expand the capacity of the company's gas transmission or distribution lines.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1192.SL.pdf?cite=2021%20c%2065%20§%20101[2021 c 65 § 101]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2518-S2.SL.pdf?cite=2020%20c%2032%20§%203[2020 c 32 § 3]; ]

== 81.88.900 - Conflict with federal requirements—2000 c 191.
If any part of this act is found to be in conflict with federal requirements that are a prescribed condition to the allocation of federal funds to the state, the conflicting part of this act is inoperative solely to the extent of the conflict and with respect to the agencies directly affected, and this finding does not affect the operation of the remainder of this act in its application to the agencies concerned. Rules adopted under this act must meet federal requirements that are a necessary condition to the receipt of federal funds by the state.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2420-S2.SL.pdf?cite=2000%20c%20191%20§%2026[2000 c 191 § 26]; ]

== 81.88.901 - Short title—2000 c 191.
This act may be known and cited as the Washington state pipeline safety act.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2420-S2.SL.pdf?cite=2000%20c%20191%20§%2027[2000 c 191 § 27]; ]

== 81.88.902 - Effective date—2000 c 191.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and takes effect immediately [March 28, 2000].

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2420-S2.SL.pdf?cite=2000%20c%20191%20§%2029[2000 c 191 § 29]; ]

