= 81.80 - Motor freight carriers.
:toc:

== 81.80.010 - Definitions.
The definitions set forth in this section apply throughout this chapter.

. "Common carrier" means any person who undertakes to transport property for the general public by motor vehicle for compensation, whether over regular or irregular routes, or regular or irregular schedules, including motor vehicle operations of other carriers by rail or water and of express or forwarding companies. "Common carrier" does not include a personal delivery device or a personal delivery device operator as those terms are defined in RCW 46.75.010.

. "Contract carrier" includes all motor vehicle operators not included under the terms "common carrier" and "private carrier" as defined in this section, and further includes any person who under special and individual contracts or agreements transports property by motor vehicle for compensation.

. "Common carrier" and "contract carrier" includes persons engaged in the business of providing, contracting for, or undertaking to provide transportation of property for compensation over the public highways of the state of Washington as brokers or forwarders.

. "Exempt carrier" means any person operating a vehicle exempted under RCW 81.80.040.

. "Household goods carrier" means a person who transports for compensation, by motor vehicle within this state, or who advertises, solicits, offers, or enters into an agreement to transport household goods as defined by the commission.

. "Motor carrier" includes "common carrier," "contract carrier," "private carrier," and "exempt carrier" as defined in this section.

. "Motor vehicle" means any truck, trailer, semitrailer, tractor, dump truck which uses a hydraulic or mechanical device to dump or discharge its load, or any self-propelled or motor-driven vehicle used upon any public highway of this state for the purpose of transporting property, but not including baggage, mail, and express transported on the vehicles of auto transportation companies carrying passengers.

. "Person" includes an individual, firm, copartnership, corporation, company, or association or their lessees, trustees, or receivers.

. A "private carrier" is a person who transports by his or her own motor vehicle, with or without compensation, property which is owned or is being bought or sold by the person, or property where the person is the seller, purchaser, lessee, or bailee and the transportation is incidental to and in furtherance of some other primary business conducted by the person in good faith.

. "Public highway" means every street, road, or highway in this state.

. "Vehicle" means every device capable of being moved upon a public highway and in, upon, or by which any person or property is or may be transported or drawn upon a public highway, except devices moved by human or animal power or used exclusively upon stationary rail or tracks.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1325-S.SL.pdf?cite=2019%20c%20214%20§%2020[2019 c 214 § 20]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1536.SL.pdf?cite=2009%20c%2094%20§%201[2009 c 94 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2068[2007 c 234 § 68]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c60.pdf?cite=1989%20c%2060%20§%201[1989 c 60 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c31.pdf?cite=1988%20c%2031%20§%201[1988 c 31 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c71.pdf?cite=1982%20c%2071%20§%201[1982 c 71 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c69.pdf?cite=1967%20c%2069%20§%201[1967 c 69 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.010[1961 c 14 § 81.80.010]; prior:  1937 c 166 § 2; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c184.pdf?cite=1935%20c%20184%20§%202[1935 c 184 § 2]; RRS § 6382-2; ]

== 81.80.020 - Declaration of policy.
The business of operating as a motor carrier of freight for compensation along the highways of this state is declared to be a business affected with a public interest. The rapid increase of motor carrier freight traffic and the fact that under the existing law many motor trucks are not effectively regulated have increased the dangers and hazards on public highways and make it imperative that regulation to the fullest extent allowed under 49 U.S.C. Sec. 14501 should be employed to the end that the highways may be rendered safer for the use of the general public; that the wear of such highways may be reduced; that congestion on highways may be minimized; that the shippers of the state may be provided with a stabilized service and rate structure; that sound economic conditions in such transportation and among such carriers may be fostered in the public interest; that adequate, economical, and efficient service by motor carriers, and reasonable charges therefor, without unjust discrimination, undue preferences or advantages, or unfair or destructive competitive practices may be promoted; that the common carriage of commodities by motor carrier may be preserved in the public interest; that the relations between, and transportation by and regulation of, motor carriers and other carriers may be improved and coordinated so that the highways of the state of Washington may be properly developed and preserved, and the public may be assured adequate, complete, dependable, and stable transportation service in all its phases.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2069[2007 c 234 § 69]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.020[1961 c 14 § 81.80.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c166.pdf?cite=1937%20c%20166%20§%201[1937 c 166 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c184.pdf?cite=1935%20c%20184%20§%201[1935 c 184 § 1]; RRS § 6382-1; ]

== 81.80.040 - Exempt vehicles.
. The provisions of this chapter, except where specifically otherwise provided, and except the provisions providing for licenses, shall not apply to:

.. Motor vehicles when operated in transportation exclusively within the corporate limits of any city or town of less than ten thousand population unless contiguous to a city or town of ten thousand population or over, nor between contiguous cities or towns both or all of which are less than ten thousand population;

.. Motor vehicles when operated in transportation wholly within the corporate limits of cities or towns of ten thousand or more but less than thirty thousand population, or between such cities or towns when contiguous, as to which the commission, after investigation and the issuance of an order thereon, has determined that no substantial public interest exists which requires that such transportation be subject to regulation under this chapter;

.. Motor vehicles when transporting exclusively the United States mail or in the transportation of newspapers or periodicals;

.. Motor vehicles owned and operated by the United States, the state of Washington, or any county, city, town, or municipality therein, or by any department of them, or either of them;

.. Motor vehicles specially constructed for towing not more than two disabled, unauthorized, or repossessed motor vehicles, wrecking, or exchanging an operable vehicle for a disabled vehicle and not otherwise used in transporting goods for compensation. For the purposes of this subsection (1)(e), a vehicle is considered to be repossessed only from the time of its actual repossession through the end of its initial tow;

.. Motor vehicles normally owned and operated by farmers in the transportation of their own farm, orchard, or dairy products, including livestock and plant or animal wastes, from point of production to market, or in the infrequent or seasonal transportation by one farmer for another farmer, if their farms are located within twenty miles of each other, of products of the farm, orchard, or dairy, including livestock and plant or animal wastes, or of supplies or commodities to be used on the farm, orchard, or dairy;

.. Motor vehicles when transporting exclusively water in connection with construction projects only;

.. Motor vehicles of less than 8,000 pounds gross vehicle weight when transporting exclusively legal documents, pleadings, process, correspondence, depositions, briefs, medical records, photographs, books or papers, cash or checks, when moving shipments of the documents described at the direction of an attorney as part of providing legal services.

. The exemptions set forth in subsection (1)(a) and (b) of this section do not apply to household goods carriers.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1536.SL.pdf?cite=2009%20c%2094%20§%202[2009 c 94 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5442.SL.pdf?cite=1993%20c%20121%20§%204[1993 c 121 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c171.pdf?cite=1984%20c%20171%20§%201[1984 c 171 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c6.pdf?cite=1979%20ex.s.%20c%206%20§%201[1979 ex.s. c 6 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c59.pdf?cite=1963%20c%2059%20§%207[1963 c 59 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.040[1961 c 14 § 81.80.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c205.pdf?cite=1957%20c%20205%20§%204[1957 c 205 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c133.pdf?cite=1949%20c%20133%20§%201[1949 c 133 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c263.pdf?cite=1947%20c%20263%20§%201[1947 c 263 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c166.pdf?cite=1937%20c%20166%20§%204[1937 c 166 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c184.pdf?cite=1935%20c%20184%20§%203[1935 c 184 § 3]; Rem. Supp. 1949 § 6382-3; ]

== 81.80.045 - Exemption—Freight consolidators.
This chapter does not apply to the operations of a shipper or a group or association of shippers in consolidating or distributing freight for themselves or for their members on a nonprofit basis for the purpose of securing the benefits of carload, truckload, or other volume rates, when the services of a common carrier are used for the transportation of such shipments.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2070[2007 c 234 § 70]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c138.pdf?cite=1979%20ex.s.%20c%20138%20§%201[1979 ex.s. c 138 § 1]; ]

== 81.80.050 - Compliance required.
It shall be unlawful for any person to operate as a "motor carrier" on any public highway of this state except in accordance with the provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.050[1961 c 14 § 81.80.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c184.pdf?cite=1935%20c%20184%20§%204[1935 c 184 § 4]; RRS § 6382-4; ]

== 81.80.060 - Combination of services.
Every person who engages for compensation to perform a combination of services, a substantial portion of which includes transportation of property of others upon the public highways, is subject to the jurisdiction of the commission as to such transportation and shall not engage in such transportation without first having obtained a common carrier or contract carrier permit to do so. A combination of services includes, but is not limited to, the delivery of household appliances for others where the delivering carrier also unpacks or uncrates the appliances and makes the initial installation. Any person engaged in extracting or processing, or both, and, in connection therewith, hauling materials exclusively for the maintenance, construction, or improvement of a public highway is not engaged in performing a combination of services.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2071[2007 c 234 § 71]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c210.pdf?cite=1969%20ex.s.%20c%20210%20§%2017[1969 ex.s. c 210 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c33.pdf?cite=1969%20c%2033%20§%201[1969 c 33 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c145.pdf?cite=1967%20ex.s.%20c%20145%20§%2077[1967 ex.s. c 145 § 77]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c69.pdf?cite=1967%20c%2069%20§%202[1967 c 69 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c170.pdf?cite=1965%20ex.s.%20c%20170%20§%2040[1965 ex.s. c 170 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.060[1961 c 14 § 81.80.060]; prior:  1937 c 166 § 5; RRS § 6382-4a; ]

== 81.80.070 - Common carriers, contract carriers, and temporary carriers—Permit required.
. A common carrier, contract carrier, or temporary carrier shall not operate for the transportation of property for compensation in this state without first obtaining from the commission a permit for such operation.

. The commission shall issue a common carrier permit to any qualified applicant if it is found the applicant is fit, willing, and able to perform the service and conform to the provisions of this chapter and the rules and regulations of the commission.

. Before a permit is issued, the commission shall require the applicant to establish safety fitness and proof of minimum financial responsibility as provided in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1536.SL.pdf?cite=2009%20c%2094%20§%203[2009 c 94 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2072[2007 c 234 § 72]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5191-S.SL.pdf?cite=1999%20c%2079%20§%201[1999 c 79 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c242.pdf?cite=1963%20c%20242%20§%201[1963 c 242 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.070[1961 c 14 § 81.80.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c95.pdf?cite=1953%20c%2095%20§%2017[1953 c 95 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c264.pdf?cite=1947%20c%20264%20§%202[1947 c 264 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c163.pdf?cite=1941%20c%20163%20§%201[1941 c 163 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c166.pdf?cite=1937%20c%20166%20§%206[1937 c 166 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c184.pdf?cite=1935%20c%20184%20§%205[1935 c 184 § 5]; Rem. Supp. 1947 § 6382-5; ]

== 81.80.075 - Household goods carriers—Permit required, penalty, cease and desist orders.
. No person shall engage in business as a household goods carrier without first obtaining a household goods carrier permit from the commission.

. Permits issued to any household goods carrier must be exercised by the carrier to the fullest extent to render reasonable service to the public. Applications for household goods carrier permits or permit extensions must be on file for a period of at least thirty days before issuance unless the commission finds that special conditions require earlier issuance.

. The commission must issue a permit or permit extension to any qualified applicant, authorizing the whole or any part of the operations covered by the application, if it is found that: The applicant is fit, willing, and able to perform the services proposed and conform to this chapter and the requirements, rules, and regulations of the commission; the operations are consistent with the public interest; and, in the case of common carriers, they are required by the present or future public convenience and necessity; otherwise, the application must be denied.

. Any person who engages in business as a household goods carrier in violation of subsection (1) of this section is subject to a penalty of up to five thousand dollars per violation.

.. If the basis for the violation is advertising, each advertisement reproduced, broadcast, or displayed via a particular medium constitutes a separate violation.

.. In deciding the amount of penalty to be imposed per violation, the commission shall consider the following factors:

... The carrier's willingness to comply with the requirements of RCW 81.80.070 and the commission's rules under this chapter; and

... The carrier's history with respect to compliance with this section.

. Any person who engages in business as a household goods carrier in violation of a cease and desist order issued by the commission under RCW 81.04.510 is subject to a penalty of up to ten thousand dollars per violation.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1536.SL.pdf?cite=2009%20c%2094%20§%204[2009 c 94 § 4]; ]

== 81.80.080 - Application for permit.
Application for permits must be made to the commission in writing and must state the ownership, financial condition, equipment to be used and physical property of the applicant, the territory or route or routes in or over which the applicant proposes to operate, the nature of the transportation to be engaged in, and other information as the commission may require.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2073[2007 c 234 § 73]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5221.SL.pdf?cite=1991%20c%2041%20§%201[1991 c 41 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.080[1961 c 14 § 81.80.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c184.pdf?cite=1935%20c%20184%20§%206[1935 c 184 § 6]; RRS § 6382-6; ]

== 81.80.090 - Form of application—Filing fees.
The commission shall prescribe forms of application for permits and for extensions thereof for the use of prospective applicants, and for transfer of permits and for acquisition of control of carriers holding permits, and shall make regulations for the filing thereof. Any such application shall be accompanied by such filing fee as the commission may prescribe by rule: PROVIDED, That such fee shall not exceed five hundred fifty dollars.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1707-S.SL.pdf?cite=1993%20c%2097%20§%205[1993 c 97 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c115.pdf?cite=1973%20c%20115%20§%2010[1973 c 115 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.090[1961 c 14 § 81.80.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c163.pdf?cite=1941%20c%20163%20§%202[1941 c 163 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c166.pdf?cite=1937%20c%20166%20§%207[1937 c 166 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c184.pdf?cite=1935%20c%20184%20§%207[1935 c 184 § 7]; RRS § 6382-7; ]

== 81.80.100 - Form and contents of permit.
Permits granted by the commission shall be in such form as the commission shall prescribe and shall set forth the name and address of the person to whom the permit is granted, the nature of the transportation service to be engaged in and the principal place of operation, termini or route to be used or territory to be served by the operation. No permit holder shall operate except in accordance with the permit issued to him or her.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20308[2013 c 23 § 308]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.100[1961 c 14 § 81.80.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c194.pdf?cite=1935%20c%20194%20§%208[1935 c 194 § 8]; RRS § 6382-8; ]

== 81.80.110 - Limitation on renewal of application.
No person whose application for a permit has been denied after hearing under any of the provisions of this chapter shall be eligible to renew the application for a period of six months from the date of the order denying such application.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.110[1961 c 14 § 81.80.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c264.pdf?cite=1947%20c%20264%20§%203[1947 c 264 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c184.pdf?cite=1935%20c%20184%20§%209[1935 c 184 § 9]; Rem. Supp. 1947 § 6382-9; ]

== 81.80.115 - Fees imposed under this chapter—Procedure for contesting—Rules.
If a person seeks to contest the imposition of a fee imposed under this chapter, the person shall pay the fee and request a refund within six months of the due date for the payment by filing a petition for a refund with the commission. The commission shall establish by rule procedures for handling refund petitions and may delegate the decisions on refund petitions to the secretary of the commission.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1707-S.SL.pdf?cite=1993%20c%2097%20§%206[1993 c 97 § 6]; ]

== 81.80.120 - Classification of carriers.
The commission may from time to time establish such just and reasonable classifications of the groups of carriers included in the terms "common carriers" and "contract carriers" as the special nature of the services performed by such carriers shall require, and such just and reasonable rules, regulations and requirements, consistent with the provisions of this chapter, to be observed by the carriers so classified or grouped, as the commission deems necessary or advisable in the public interest.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.120[1961 c 14 § 81.80.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c166.pdf?cite=1937%20c%20166%20§%208[1937 c 166 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c184.pdf?cite=1935%20c%20184%20§%2010[1935 c 184 § 10]; RRS § 6382-10; ]

== 81.80.130 - Regulatory power over common carriers.
To the extent allowed under 49 U.S.C. Sec. 14501, the commission shall: Supervise and regulate every common carrier in this state; make, fix, alter, and amend, just, fair, reasonable, minimum, maximum, or minimum and maximum, rates, charges, classifications, rules, and regulations for all common carriers; regulate the accounts, service, and safety of operations thereof; require the filing of reports and other data thereby; and supervise and regulate all common carriers in all other matters affecting their relationship with competing carriers of every kind and the shipping and general public. The commission may by order approve rates filed by common carriers in respect to certain designated commodities and services when, in the opinion of the commission, it is impractical for the commission to make, fix, or prescribe rates covering the commodities and services.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2074[2007 c 234 § 74]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.130[1961 c 14 § 81.80.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c205.pdf?cite=1957%20c%20205%20§%205[1957 c 205 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c166.pdf?cite=1937%20c%20166%20§%209[1937 c 166 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c184.pdf?cite=1935%20c%20184%20§%2011[1935 c 184 § 11]; RRS § 6382-11; ]

== 81.80.132 - Common carriers—Estimate of charges for household goods—Penalty.
When a common carrier gives an estimate of charges for services in carrying household goods, the carrier will endeavor to accurately reflect the actual charges. The carrier is subject to a monetary penalty not to exceed one thousand dollars per violation when the actual charges exceed the percentages allowed by the commission.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1907-S.SL.pdf?cite=1993%20c%20392%20§%201[1993 c 392 § 1]; ]

== 81.80.140 - Regulatory power over contract carriers.
To the extent allowed under 49 U.S.C. Sec. 14501, the commission shall: Supervise and regulate every contract carrier in this state; fix, alter, and amend, just, fair, and reasonable classifications, rules, and regulations and minimum rates and charges of each contract carrier; regulate the account, service, and safety of contract carriers' operations; require the filing of reports and of other data thereby; and supervise and regulate contract carriers in all other matters affecting their relationship with both the shipping and the general public.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2075[2007 c 234 § 75]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.140[1961 c 14 § 81.80.140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c166.pdf?cite=1937%20c%20166%20§%2011[1937 c 166 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c184.pdf?cite=1935%20c%20184%20§%2012[1935 c 184 § 12]; RRS § 6382-12; ]

== 81.80.150 - Tariffs to be compiled and sold.
The commission shall make, fix, construct, compile, promulgate, publish, and distribute tariffs containing compilations of rates, charges, classifications, rules, and regulations to be used by all household goods carriers. In compiling these tariffs, the commission shall include within any given tariff compilation the carriers, groups of carriers, commodities, or geographical areas it determines are in the public interest. The compilations and publications may be made by the commission by compiling the rates, charges, classifications, rules, and regulations now in effect, and as they may be amended and altered from time to time after notice and hearing, by issuing and distributing revised pages or supplements to the tariffs or reissues of tariffs in accordance with the orders of the commission. The commission, upon good cause shown, may establish temporary rates, charges, or classification changes which may be made permanent only after publication in an applicable tariff for not less than sixty days and a determination by the commission that the rates, charges, or classifications are just, fair, and reasonable. If a shipper or common carrier, or representative of either, files a protest with the commission, within sixty days from the date of publication, stating that the temporary rates are unjust, unfair, or unreasonable, the commission must hold a hearing to consider the protest. Publication of these temporary rates in the tariff is adequate public notice. The commission may, upon notice and hearing, fix and determine just, fair, and reasonable rates, charges, and classifications. Each common carrier shall purchase from the commission and post tariffs applicable to its authority. The commission shall set fees for the sale, supplements, and corrections of the tariffs at rates to cover all costs of making, fixing, constructing, compiling, promulgating, publishing, and distributing the tariffs. The proper tariff, or tariffs, applicable to a carrier's operations must be available to the public at each agency and office of all common carriers operating within this state. The compilations and publications must be sold by the commission for the established fee. However, copies may be furnished for free to other regulatory bodies and departments of government and to colleges, schools, and libraries. All copies of the compilations, whether sold or given for free, must be issued and distributed under rules fixed by the commission. The commission may by order authorize common carriers to publish and file tariffs with the commission and be governed by the tariffs in respect to certain designated commodities and services when, in the opinion of the commission, it is impractical for the commission to make, fix, construct, compile, publish, and distribute tariffs covering such commodities and services.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2076[2007 c 234 § 76]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1707-S.SL.pdf?cite=1993%20c%2097%20§%204[1993 c 97 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c116.pdf?cite=1981%20c%20116%20§%202[1981 c 116 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c115.pdf?cite=1973%20c%20115%20§%2011[1973 c 115 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.150[1961 c 14 § 81.80.150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c248.pdf?cite=1959%20c%20248%20§%205[1959 c 248 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c205.pdf?cite=1957%20c%20205%20§%206[1957 c 205 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c264.pdf?cite=1947%20c%20264%20§%204[1947 c 264 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c163.pdf?cite=1941%20c%20163%20§%203[1941 c 163 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c166.pdf?cite=1937%20c%20166%20§%2010[1937 c 166 § 10]; Rem. Supp. 1947 § 6382-11a; ]

== 81.80.170 - Temporary permits.
The commission may issue temporary permits to temporary household goods carriers for no more than one hundred eighty days, but only after the commission finds that the issuance of the temporary permits is consistent with the public interest. The commission may prescribe special rules and regulations and impose special terms and conditions as in its judgment are reasonable and necessary in carrying out the provisions of this chapter.

The commission may also issue temporary permits pending the determination of an application filed with the commission for approval of a consolidation or merger of the properties of two or more household goods carriers or of a purchase or lease of one or more household goods carriers.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2077[2007 c 234 § 77]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c242.pdf?cite=1963%20c%20242%20§%202[1963 c 242 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.170[1961 c 14 § 81.80.170]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c95.pdf?cite=1953%20c%2095%20§%2018[1953 c 95 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c264.pdf?cite=1947%20c%20264%20§%205[1947 c 264 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c166.pdf?cite=1937%20c%20166%20§%2012[1937 c 166 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c184.pdf?cite=1935%20c%20184%20§%2014[1935 c 184 § 14]; Rem. Supp. 1947 § 6382-14; ]

== 81.80.190 - Insurance or deposit of security required.
The commission shall, in issuing permits to common carriers and contract carriers under this chapter, require the carriers to either procure and file liability and property damage insurance from a company licensed to write such insurance in the state of Washington, or deposit security, for the limits of liability and on terms and conditions that the commission determines are necessary for the reasonable protection of the public against damage and injury for which the carrier may be liable by reason of the operation of any motor vehicle.

In fixing the amount of the insurance policy or policies, or deposit of security, the commission shall consider the character and amount of traffic and the number of persons affected and the degree of danger that the proposed operation involves.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2078[2007 c 234 § 78]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c191.pdf?cite=1986%20c%20191%20§%205[1986 c 191 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.190[1961 c 14 § 81.80.190]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c184.pdf?cite=1935%20c%20184%20§%2016[1935 c 184 § 16]; RRS § 6382-16; ]

== 81.80.195 - Liability insurance requirements exclusive.
This chapter shall exclusively govern the liability insurance requirements for motor vehicle common and contract carriers. Any motor vehicle that meets the public liability requirements prescribed under RCW 81.80.190 shall not be required to comply with any ordinances of a city or county prescribing insurance requirements.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c264.pdf?cite=1989%20c%20264%20§%202[1989 c 264 § 2]; ]

== 81.80.200 - Conditions may be attached to permits.
The commission is hereby vested with power and authority in issuing permits to any of the carriers classified in accordance with RCW 81.80.120 to attach thereto such terms and conditions and to require such insurance or security as it may deem necessary for the protection of the public highways and to be for the best interest of the shipping and the general public. All such regulations and conditions shall be deemed temporary and may be revoked by the commission upon recommendation of the state or county authorities in charge of highway maintenance or safety when in the judgment of such authorities such revocation is required in order to protect the public or preserve the public highways.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.200[1961 c 14 § 81.80.200]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c166.pdf?cite=1937%20c%20166%20§%2014[1937 c 166 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c184.pdf?cite=1935%20c%20184%20§%2017[1935 c 184 § 17]; RRS § 6382-17; ]

== 81.80.211 - Hours of operators—Rules and regulations.
The commission may adopt rules and regulations relating to the hours of duty of motor carrier drivers and operators.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.211[1961 c 14 § 81.80.211]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c95.pdf?cite=1953%20c%2095%20§%2023[1953 c 95 § 23]; ]

== 81.80.220 - Tariff rates to be charged.
A household goods carrier shall not collect or receive a greater, less, or different remuneration for the transportation of property or for any service in connection therewith than the rates and charges that are either legally established and filed with the commission or are specified in the contract or contracts filed. A household goods carrier shall not refund or remit in any manner or by any device any portion of the rates and charges required to be collected by each tariff or contract or filing with the commission.

The commission may check the records of all carriers under this chapter and of those employing the services of the carrier to discover all discriminations, under or overcharges, and rebates, and may suspend or revoke permits for violations of this section.

The commission may refuse to accept any time schedule, tariff, or contract that, in the opinion of the commission, limits the service of a carrier to profitable trips only or to the carrying of high class commodities in competition with other carriers who give a complete service affording one carrier an unfair advantage over a competitor.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2079[2007 c 234 § 79]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.220[1961 c 14 § 81.80.220]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c166.pdf?cite=1937%20c%20166%20§%2016[1937 c 166 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c184.pdf?cite=1935%20c%20184%20§%2019[1935 c 184 § 19]; RRS § 6382-19; ]

== 81.80.230 - Penalty for rebating, etc.—Procedure for collection.
Any person, whether a household goods carrier subject to this chapter, shipper, or consignee, or any officer, employee, agent, or representative thereof, who: (1) Offers, grants, gives, solicits, accepts, or receives any rebate, concession, or discrimination in violation of this chapter; (2) by means of any false statement or representation, or by the use of any false or fictitious bill, bill of lading, receipt, voucher, roll, account, claim, certificate, affidavit, deposition, lease, or bill of sale, or by any other means or device assists, suffers, or permits any person or persons, natural or artificial, to obtain transportation of property subject to this chapter for less than the applicable rate, fare, or charge; or (3) fraudulently seeks to evade or defeat regulation of motor carriers under this chapter is subject to a civil penalty of not more than one hundred dollars for each violation. Each and every violation is a separate and distinct offense, and in case of a continuing violation every day's continuance is a separate and distinct violation. Every act or omission that procures, aids, or abets in the violation is also a violation under this section and subject to the penalty under this section.

The penalty under this section is due and payable when the person incurring the penalty receives a notice in writing from the commission describing the violation with reasonable particularity and advising the person that the penalty is due. The commission may, upon a written application received within fifteen days, remit or mitigate any penalty under this section or discontinue any prosecution to recover the penalty upon such terms as the commission in its discretion deems proper. The commission may ascertain the facts on all applications. If the penalty is not paid to the commission within fifteen days after receipt of the notice imposing the penalty, or the application for remission or mitigation is not made within fifteen days after the violator has received notice of the disposition of the application, the attorney general shall bring an action in the name of the state of Washington in the superior court of Thurston county or another county where the violator may do business, to recover the penalty. In all such actions, the procedure and rules of evidence are the same as in an ordinary civil action except as otherwise provided in this section. All penalties recovered under this section must be paid into the state treasury and credited to the public service revolving fund.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2080[2007 c 234 § 80]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c132.pdf?cite=1980%20c%20132%20§%202[1980 c 132 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.230[1961 c 14 § 81.80.230]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c264.pdf?cite=1947%20c%20264%20§%206[1947 c 264 § 6]; Rem. Supp. 1947 § 6382-19a; ]

== 81.80.250 - Bond to protect shippers and consignees.
The commission may require any household goods carrier to file a surety bond, or deposit security, in an amount determined by the commission, that is conditioned on the carrier compensating the shippers and consignees for all money belonging to the shippers and consignees, and coming into the possession of the carrier in connection with its transportation service. Any household goods carrier required by law to compensate a shipper or consignee for any loss, damage, or default, for which a connecting common carrier is legally responsible, must be subrogated to the rights of the shipper or consignee under any bond or deposit of security to the extent of the amount paid.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2081[2007 c 234 § 81]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.250[1961 c 14 § 81.80.250]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c184.pdf?cite=1935%20c%20184%20§%2021[1935 c 184 § 21]; RRS § 6382-21; ]

== 81.80.260 - Operation in more than one class.
It is unlawful for any household goods carrier to operate any vehicle at the same time in more than one class of operation, except upon approval of the commission and a finding that the operation is in the public interest.

An exempt carrier shall not transport property for compensation except as provided under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2082[2007 c 234 § 82]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c69.pdf?cite=1967%20c%2069%20§%203[1967 c 69 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.260[1961 c 14 § 81.80.260]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c184.pdf?cite=1935%20c%20184%20§%2022[1935 c 184 § 22]; RRS § 6382-22; ]

== 81.80.270 - Permits—Acquisition of carrier holding permit—Commission approval—Duties on cessation of operation.
Permits issued under this chapter are neither irrevocable nor subject to transfer or assignment except upon a proper showing that property rights might be affected thereby, and then in the discretion of the commission.

Any person, partnership, or corporation, singly or in combination with any other person, partnership, or corporation, whether a household goods carrier holding a permit or otherwise, or any combination of such, shall not acquire control or enter into any agreement or arrangement to acquire control of a household goods carrier holding a permit through ownership of its stock or through purchase, lease, or contract to manage the business, or otherwise, except after and with the approval and authorization of the commission. However, upon the dissolution of a partnership, which holds a permit, because of the death, bankruptcy, or withdrawal of a partner where the partner's interest is transferred to his or her spouse or to one or more remaining partners, or in the case of a corporation which holds a permit, in the case of the death of a shareholder where a shareholder's interest upon death is transferred to his or her spouse or to one or more of the remaining shareholders, the commission shall transfer the permit to the newly organized partnership that is substantially composed of the remaining partners, or continue the corporation's permit without hearing and protest. In all other cases, any transaction either directly or indirectly entered into without approval of the commission is void, and it is unlawful for any person seeking to acquire or divest control of the permit to be a party to the transaction without approval of the commission.

Every carrier who ceases operation and abandons his or her rights under the permits issued to him or her shall notify the commission within thirty days of the cessation or abandonment.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2083[2007 c 234 § 83]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c115.pdf?cite=1973%20c%20115%20§%2012[1973 c 115 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c210.pdf?cite=1969%20ex.s.%20c%20210%20§%2012[1969 ex.s. c 210 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c134.pdf?cite=1965%20ex.s.%20c%20134%20§%201[1965 ex.s. c 134 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c59.pdf?cite=1963%20c%2059%20§%206[1963 c 59 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.270[1961 c 14 § 81.80.270]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c248.pdf?cite=1959%20c%20248%20§%2024[1959 c 248 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c166.pdf?cite=1937%20c%20166%20§%2018[1937 c 166 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c184.pdf?cite=1935%20c%20184%20§%2023[1935 c 184 § 23]; RRS § 6382-23; ]

== 81.80.272 - Transfer of decedent's interest—Temporary continuance of operations.
Except as otherwise provided in RCW 81.80.270, any permit granted or issued to any household goods carrier under this chapter and held by a person alone or in conjunction with others other than as stockholders in a corporation at the time of his or her death is transferable as any other right or interest of the person's estate subject to the following:

. Application for transfer must be made to the commission in a form and contain information prescribed by the commission. The transfer described in the application must be approved if it appears from the application or from any hearing held thereon or from any investigation thereof that the proposed transferee is fit, willing, and able properly to perform the services authorized by the permit to be transferred and to conform to the provisions of this chapter and the requirements, rules, and regulations of the commission, otherwise the application must be denied.

. Temporary continuance of motor carrier operations without prior compliance with this section is recognized as justified by the public interest when the personal representatives, heirs, or surviving spouses of deceased persons desire to continue the operations of the carriers whom they succeed in interest subject to reasonable rules and regulations prescribed by the commission.

In case of temporary continuance under this section, the successor shall immediately procure insurance or deposit security as required by RCW 81.80.190.

Immediately upon any temporary continuance of motor carrier operations and in any event not more than thirty days thereafter, the successor shall give notice of the succession by written notice to the commission containing information prescribed by the commission.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2084[2007 c 234 § 84]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c115.pdf?cite=1973%20c%20115%20§%2013[1973 c 115 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c134.pdf?cite=1965%20ex.s.%20c%20134%20§%202[1965 ex.s. c 134 § 2]; ]

== 81.80.280 - Cancellation, suspension, and alteration of permits—Notice by household goods carriers.
. Permits may be canceled, suspended, altered, or amended by the commission upon complaint by any interested party, or upon the commission's own motion after notice and opportunity for hearing, when the permittee or permittee's agent has repeatedly violated this chapter, the rules and regulations of the commission, or the motor laws of this state or of the United States, or the household goods carrier has made unlawful rebates or has not conducted its operation in accordance with the permit. The commission may enjoin any person from any violation of this chapter, or any order, rule, or regulation made by the commission pursuant to the terms hereof. If the suit is instituted by the commission, a bond is not required as a condition to the issuance of the injunction.

. When the commission has canceled a household goods carrier permit, the carrier must, when directed by the commission, provide notice to every customer that its permit has been canceled, and provide proof of such notice to the commission.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1536.SL.pdf?cite=2009%20c%2094%20§%207[2009 c 94 § 7]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2085[2007 c 234 § 85]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c209.pdf?cite=1987%20c%20209%20§%201[1987 c 209 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.280[1961 c 14 § 81.80.280]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c184.pdf?cite=1935%20c%20184%20§%2024[1935 c 184 § 24]; RRS § 6382-24; ]

== 81.80.290 - Rules and regulations.
The commission shall have power and authority, by general order or otherwise, to prescribe rules and regulations in conformity with this chapter to carry out the purposes thereof, applicable to any and all "motor carriers," or to any persons transporting property by motor vehicle for compensation even though they do not come within the term "motor carrier" as herein defined.

The commission shall mail each holder of a permit under this chapter a copy of such rules and regulations.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.290[1961 c 14 § 81.80.290]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c184.pdf?cite=1935%20c%20184%20§%2025[1935 c 184 § 25]; RRS § 6382-25; ]

== 81.80.305 - Markings required—Exemptions.
. All motor vehicles, other than those exempt under subsection (2) of this section, must display a permanent marking identifying the name or number, or both, on each side of the power units. For a motor vehicle that is a common or contract carrier under permit by the commission as described in subsection (3)(a) of this section, a private carrier under subsection (4) of this section, or a leased carrier as described in subsection (5) of this section, any required identification that is added, modified, or renewed after September 1, 1991, must be displayed on the driver and passenger doors of the power unit. The identification must be in a clearly legible style with letters no less than three inches high and in a color contrasting with the surrounding body panel.

. This section does not apply to (a) vehicles exempt under RCW 81.80.040, and (b) vehicles operated by private carriers that singly or in combination are less than thirty-six thousand pounds gross vehicle weight.

. If the motor vehicle is operated as (a) a common or contract carrier under a permit by the commission, the identification must contain the name of the permittee, or business name, and the permit number, or (b) a common or contract carrier holding both intrastate and interstate authority, the identification may be either the commission permit number or the federal vehicle marking requirement established by the United States department of transportation for interstate motor carriers.

. If the motor vehicle is a private carrier, the identification must contain the name and address of either the business operating the vehicle or the registered owner.

. If the motor vehicle is operated under lease, the vehicle must display either permanent markings or placards on the driver and passenger doors of the power unit. A motor vehicle under lease (a) that is operated as a common or contract carrier under permit by the commission must display identification as provided in subsection (3)(a) of this section, and (b) that is operated as a private carrier must display identification as provided in subsection (4) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2086[2007 c 234 § 86]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5295-S.SL.pdf?cite=1991%20c%20241%20§%201[1991 c 241 § 1]; ]

== 81.80.321 - Regulatory fee—Based on gross income—Legislative intent—Delinquent fee payments—Public service revolving fund.
In addition to all other fees to be paid, a common carrier and contract carrier shall pay a regulatory fee of no more than 0.0025 of its gross income from intrastate operations for the previous calendar year, or such other period as the commission designates by rule. The carrier shall pay the fee no later than four months after the end of the appropriate period and shall include with the payment such information as the commission requires by rule.

The legislature intends that the fees collected under this chapter shall reasonably approximate the cost of supervising and regulating motor carriers subject to this chapter, and to that end the commission may by general order decrease fees provided in this section if it determines that the moneys then in the motor carrier account of the public service revolving fund and the fees currently to be paid will exceed the reasonable cost of supervising and regulating carriers.

Any payment of the fee imposed by this section made after its due date shall include a late fee of two percent of the amount due. Delinquent fees shall accrue interest at the rate of one percent per month.

All fees collected under any other provision of this chapter must be paid to the commission. The commission shall transmit the fees to the state treasurer within thirty days for deposit to the credit of the public service revolving fund.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2338.SL.pdf?cite=1994%20c%2083%20§%204[1994 c 83 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1707-S.SL.pdf?cite=1993%20c%2097%20§%203[1993 c 97 § 3]; ]

== 81.80.330 - Enforcement of chapter.
The commission may administer and enforce all provisions of this chapter and inspect the vehicles, books, and documents of all motor carriers and the books, documents, and records of those using the service of the carriers for the purpose of discovering all discriminations and rebates and other information pertaining to the enforcement of this chapter and shall prosecute violations thereof. The commission shall employ auditors, inspectors, clerks, and assistants necessary for the enforcement of this chapter. The Washington state patrol shall perform all motor carrier safety inspections required by this chapter, including terminal safety audits, except for (1) those carriers subject to the economic regulation of the commission, or (2) a vehicle owned or operated by a carrier affiliated with a solid waste company subject to economic regulation by the commission. The Washington state patrol and the sheriffs of the counties shall make arrests and the county attorneys shall prosecute violations of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2087[2007 c 234 § 87]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1209-S.SL.pdf?cite=1995%20c%20272%20§%205[1995 c 272 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c132.pdf?cite=1980%20c%20132%20§%203[1980 c 132 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.330[1961 c 14 § 81.80.330]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c184.pdf?cite=1935%20c%20184%20§%2029[1935 c 184 § 29]; RRS § 6382-29; ]

== 81.80.345 - Venue—Hearings on applications.
Hearings on applications shall be heard in the county or adjoining county for which authority to operate is being applied. If more than one county is involved, the commission may hold the hearings at a location that will afford the greatest opportunity for testimony by witnesses representing the area for which authority to operate is being applied.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c58.pdf?cite=1988%20c%2058%20§%201[1988 c 58 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c242.pdf?cite=1963%20c%20242%20§%203[1963 c 242 § 3]; ]

== 81.80.355 - Unlawful advertising—Penalty.
Any person not holding a permit authorizing him or her to operate as a common carrier, contract carrier, or temporary carrier for the transportation of property for compensation in this state, or an exempt carrier, who displays on any building, vehicle, billboard, or in any manner, any advertisement of, or by circular, letter, newspaper, magazine, poster, card, or telephone directory, advertises the transportation of property for compensation shall be guilty of a misdemeanor and punishable as such.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20309[2013 c 23 § 309]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.355[1961 c 14 § 81.80.355]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c205.pdf?cite=1957%20c%20205%20§%208[1957 c 205 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c95.pdf?cite=1953%20c%2095%20§%2022[1953 c 95 § 22]; ]

== 81.80.357 - Advertising—Household goods—Permit number required—Penalty.
. No person in the business of transporting household goods as defined by the commission in intrastate commerce shall advertise without listing the carrier's Washington utilities and transportation commission permit number, physical address, and telephone number in the advertisement.

. All advertising, contracts, correspondence, cards, signs, posters, papers, and documents, including websites or other online advertising, which show a household goods carrier name shall also show the carrier's Washington utilities and transportation commission permit number, physical address, and telephone number. The alphabetized listing of household goods carriers appearing in the advertising sections of telephone books or other directories and all advertising that shows the carrier's name or address shall show the carrier's current Washington utilities and transportation commission permit number.

. Radio or television advertising need not contain the carrier's Washington utilities and transportation commission permit number if the carrier provides its permit number, physical address, and telephone number to the person selling the advertisement and it is recorded in the advertising contract.

. No person shall falsify a Washington utilities and transportation commission permit number or use a false or inaccurate Washington utilities and transportation commission permit number in connection with any solicitation or identification as an authorized household goods carrier.

. If, upon investigation, the commission determines that a household goods carrier or person acting in the capacity of a household goods carrier has violated this section, the commission may issue a penalty not to exceed five hundred dollars for every violation.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1536.SL.pdf?cite=2009%20c%2094%20§%206[2009 c 94 § 6]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2494.SL.pdf?cite=1994%20c%20168%20§%201[1994 c 168 § 1]; ]

== 81.80.360 - Procedure—Penalties—General statute invoked.
All applicable provisions of this title, relating to procedure, powers of the department and penalties, shall apply to the operation and regulation of persons under this chapter, except insofar as such provisions may conflict with provisions of this chapter and rules and regulations issued thereunder by the commission.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.360[1961 c 14 § 81.80.360]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c166.pdf?cite=1937%20c%20166%20§%2022[1937 c 166 § 22]; RRS § 6382-31a; ]

== 81.80.370 - Application to interstate and foreign commerce.
This chapter applies to persons and motor vehicles engaged in interstate or foreign commerce to the full extent permitted by the Constitution and laws of the United States.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2088[2007 c 234 § 88]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.80.370[1961 c 14 § 81.80.370]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c184.pdf?cite=1935%20c%20184%20§%2032[1935 c 184 § 32]; RRS § 6382-32; ]

== 81.80.371 - Federal authority and registration for compensatory services.
It is unlawful for any motor carrier to perform a transportation service for compensation upon the public highways of this state without first having secured appropriate federal authority from the United States department of transportation, if the authority is required, and without first having registered with the commission either directly or through a federally authorized uniform registration program.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2089[2007 c 234 § 89]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c59.pdf?cite=1963%20c%2059%20§%209[1963 c 59 § 9]; ]

== 81.80.372 - Rights or privileges for compensatory services.
This chapter does not confer on any person or persons the exclusive right or privilege of transporting property for compensation over the public highways of the state.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1536.SL.pdf?cite=2009%20c%2094%20§%205[2009 c 94 § 5]; ]

== 81.80.430 - Brokers and forwarders.
. A person who provides brokering or forwarding services for the transportation of property in intrastate commerce shall file with the commission and keep in effect, a surety bond or deposit of satisfactory security, in a sum to be determined by the commission, but not less than five thousand dollars, conditioned upon the broker or forwarder compensating shippers, consignees, and carriers for all moneys belonging to them and coming into the broker's or forwarder's possession in connection with the transportation service.

. Failure to file the bond or deposit security is sufficient cause for the commission to refuse to grant the application for a permit or registration. Failure to maintain the bond or the deposit of security is sufficient cause for cancellation of a permit or registration.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2090[2007 c 234 § 90]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2005-S.SL.pdf?cite=1991%20c%20146%20§%201[1991 c 146 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c109.pdf?cite=1990%20c%20109%20§%201[1990 c 109 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c60.pdf?cite=1989%20c%2060%20§%202[1989 c 60 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c31.pdf?cite=1988%20c%2031%20§%202[1988 c 31 § 2]; ]

== 81.80.470 - Recyclable materials collection and transportation—Construction.
. The collection or transportation of recyclable materials from a drop box or recycling buy-back center, or collection or transportation of recyclable materials by or on behalf of a commercial or industrial generator of recyclable materials to a recycler for use or reclamation is subject to regulation under this chapter.

. Nothing in this chapter changes RCW 81.77.010(8), to allow any entity, other than a solid waste collection company authorized by the commission or an entity collecting solid waste from a city or town under chapter 35.21 or 35A.21 RCW, to collect solid waste that may incidentally contain recyclable materials.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2091[2007 c 234 § 91]; ]

== 81.80.900 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%20188[2009 c 521 § 188]; ]

