= 81.72 - Taxicab companies.
:toc:

== 81.72.200 - Legislative intent.
The legislature finds and declares that privately operated taxicab transportation service is a vital part of the transportation system within the state and provides demand-responsive services to state residents, tourists, and out-of-state business people. Consequently, the safety, reliability, and economic viability and stability of privately operated taxicab transportation service are matters of statewide importance. The regulation of privately operated taxicab transportation services is thus an essential governmental function. Therefore, it is the intent of the legislature to permit political subdivisions of the state to regulate taxicab transportation services without liability under federal antitrust laws.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c126.pdf?cite=1984%20c%20126%20§%201[1984 c 126 § 1]; ]

== 81.72.210 - Local regulatory powers listed.
To protect the public health, safety, and welfare, cities, towns, counties, and port districts of the state may license, control, and regulate privately operated taxicab transportation services operating within their respective jurisdictions. The power to regulate includes:

. Regulating entry into the business of providing taxicab transportation services;

. Requiring a license to be purchased as a condition of operating a taxicab and the right to revoke, cancel, or refuse to reissue a license for failure to comply with regulatory requirements;

. Controlling the rates charged for providing taxicab transportation service and the manner in which rates are calculated and collected, including the establishment of zones as the basis for rates;

. Regulating the routes of taxicabs, including restricting access to airports;

. Establishing safety, equipment, and insurance requirements; and

. Any other requirements adopted to ensure safe and reliable taxicab service.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c126.pdf?cite=1984%20c%20126%20§%202[1984 c 126 § 2]; ]

== 81.72.220 - Cooperative agreements—Joint regulation.
A city, town, county, or port district may enter into cooperative agreements with any other city, town, county, or port district for the joint regulation of taxicabs. Cooperative agreements may provide for, but are not limited to, the granting, revocation, and suspension of joint taxicab licenses.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c126.pdf?cite=1984%20c%20126%20§%203[1984 c 126 § 3]; ]

== 81.72.240 - Rate adjustments—Industrial insurance, other costs—Requirement to train for hire operator.
. Any city, town, county, or port district setting the rates charged for taxicab services under this chapter must adjust rates to accommodate changes in the cost of industrial insurance or in other industry-wide costs.

. Any business that as owner leases a taxicab licensed under this chapter to a for hire operator must make a reasonable effort to train the for hire operator in motor vehicle operation and safety requirements and monitor operator compliance. Monitoring operator compliance may include the use of vehicle operator monitoring cameras.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1367-S.SL.pdf?cite=2011%20c%20190%20§%208[2011 c 190 § 8]; ]

