= 81.12 - Transfers of property.
:toc:

== 81.12.010 - Definition.
"Public service company," as used in this chapter, means every common carrier subject to regulation as to rates and service by the utilities and transportation commission under the provisions of this title. It does not include common carriers subject to regulation by the federal energy regulatory commission or the United States department of transportation, household goods carriers subject to chapter 81.80 RCW, or solid waste collection companies subject to chapter 81.77 RCW. This section does not apply to transfers of permits or certificates.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2019[2007 c 234 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c13.pdf?cite=1981%20c%2013%20§%204[1981 c 13 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c210.pdf?cite=1969%20ex.s.%20c%20210%20§%204[1969 ex.s. c 210 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c105.pdf?cite=1965%20ex.s.%20c%20105%20§%204[1965 ex.s. c 105 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c59.pdf?cite=1963%20c%2059%20§%205[1963 c 59 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.12.010[1961 c 14 § 81.12.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c95.pdf?cite=1953%20c%2095%20§%2012[1953 c 95 § 12]; 1941 c 159 § 1, part; Rem. Supp. 1941 § 10440a; ]

== 81.12.020 - Order required to sell, merge, etc.
No public service company shall sell, lease, assign or otherwise dispose of the whole or any part of its franchises, properties or facilities whatsoever, which are necessary or useful in the performance of its duties to the public, and no public service company shall, by any means whatsoever, directly or indirectly, merge or consolidate any of its franchises, properties or facilities with any other public service company, without having secured from the commission an order authorizing it so to do: PROVIDED, That this section shall not apply to any sale, lease, assignment or other disposal of such franchises, properties or facilities to a public utility district.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.12.020[1961 c 14 § 81.12.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c75.pdf?cite=1945%20c%2075%20§%201[1945 c 75 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c159.pdf?cite=1941%20c%20159%20§%202[1941 c 159 § 2]; Rem. Supp. 1945 § 10440b; ]

== 81.12.030 - Disposal without authorization void.
Any such sale, lease, assignment, or other disposition, merger or consolidation made without authority of the commission shall be void.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.12.030[1961 c 14 § 81.12.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c159.pdf?cite=1941%20c%20159%20§%203[1941 c 159 § 3]; Rem. Supp. 1941 § 10440c; ]

== 81.12.040 - Authority required to acquire property or securities of company.
No public service company shall, directly or indirectly, purchase, acquire, or become the owner of any of the franchises, properties, facilities, capital stocks or bonds of any other public service company unless authorized so to do by the commission. Nothing contained in this chapter shall prevent the holding of stocks or other securities heretofore lawfully acquired or prohibit, upon the surrender or exchange of said stocks or other securities pursuant to a reorganization plan, the purchase, acquisition, taking or holding by the owner of a proportionate amount of the stocks or other securities of any new corporation organized to take over at foreclosure or other sale, the property of the corporation the stocks or securities of which have been thus surrendered or exchanged. Any contract by any public service company for the purchase, acquisition, assignment or transfer to it of any of the stocks or other securities of any other public service company, directly or indirectly, without the approval of the commission shall be void and of no effect.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.12.040[1961 c 14 § 81.12.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c159.pdf?cite=1941%20c%20159%20§%204[1941 c 159 § 4]; Rem. Supp. 1941 § 10440d; ]

== 81.12.050 - Rules and regulations.
The commission shall have power to promulgate rules and regulations to make effective the provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.12.050[1961 c 14 § 81.12.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c159.pdf?cite=1941%20c%20159%20§%205[1941 c 159 § 5]; Rem. Supp. 1941 § 10440e; ]

== 81.12.060 - Penalty.
The provisions of RCW 81.04.380 and 81.04.385 as to penalties shall be applicable to public service companies, their officers, agents and employees failing to comply with the provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.12.060[1961 c 14 § 81.12.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c159.pdf?cite=1941%20c%20159%20§%206[1941 c 159 § 6]; Rem. Supp. 1941 § 10440f; ]

