= 81.04 - Regulations—General.
:toc:

== 81.04.010 - Definitions.
As used in this title, unless specially defined otherwise or unless the context indicates otherwise:

. "Commission" means the utilities and transportation commission.

. "Commissioner" means one of the members of such commission.

. "Corporation" includes a corporation, company, association, or joint stock association.

. "Low-level radioactive waste site operating company" includes every corporation, company, association, joint stock association, partnership, and person, their lessees, trustees, or receivers appointed by any court whatsoever, owning, operating, controlling, or managing a low-level radioactive waste disposal site or sites located within the state of Washington.

. "Low-level radioactive waste" means low-level waste as defined by *RCW 43.145.010.

. "Person" includes an individual, a firm, or copartnership.

. "Street railroad" includes every railroad by whatsoever power operated, or any extension or extensions, branch or branches thereof, for public use in the conveyance of persons or property for hire, being mainly upon, along, above, or below any street, avenue, road, highway, bridge, or public place within any one city or town, and includes all equipment, switches, spurs, tracks, bridges, right of trackage, subways, tunnels, stations, terminals, and terminal facilities of every kind used, operated, controlled, or owned by or in connection with any such street railroad, within this state.

. "Street railroad company" includes every corporation, company, association, joint stock association, partnership, and person, their lessees, trustees, or receivers appointed by any court whatsoever, and every city or town, owning, controlling, operating, or managing any street railroad or any cars or other equipment used thereon or in connection therewith within this state.

. "Railroad" includes every railroad, other than street railroad, by whatsoever power operated for public use in the conveyance of persons or property for hire, with all facilities and equipment, used, operated, controlled, or owned by or in connection with any such railroad.

. "Railroad company" includes every corporation, company, association, joint stock association, partnership, or person, their lessees, trustees, or receivers appointed by any court whatsoever, owning, operating, controlling, or managing any railroad or any cars or other equipment used thereon or in connection therewith within this state.

. "Common carrier" includes all railroads, railroad companies, street railroads, street railroad companies, commercial ferries, motor freight carriers, auto transportation companies, charter party carriers and excursion service carriers, private nonprofit transportation providers, solid waste collection companies, household goods carriers, hazardous liquid pipeline companies, and every corporation, company, association, joint stock association, partnership, and person, their lessees, trustees, or receivers appointed by any court whatsoever, and every city or town, owning, operating, managing, or controlling any such agency for public use in the conveyance of persons or property for hire within this state.

. "Vessel" includes every species of watercraft, by whatsoever power operated, for public use in the conveyance of persons or property for hire over and upon the waters within this state, excepting all towboats, tugs, scows, barges, and lighters, and excepting rowboats and sailing boats under twenty gross tons burden, open steam launches of five tons gross and under, and vessels under five tons gross propelled by gas, fluid, naphtha, or electric motors.

. "Commercial ferry" includes every corporation, company, association, joint stock association, partnership, and person, their lessees, trustees, or receivers, appointed by any court whatsoever, owning, controlling, leasing, operating, or managing any vessel over and upon the waters of this state.

. "Transportation of property" includes any service in connection with the receiving, delivery, elevation, transfer in transit, ventilation, refrigeration, icing, storage, and handling of the property transported, and the transmission of credit.

. "Transportation of persons" includes any service in connection with the receiving, carriage, and delivery of persons transported and their baggage and all facilities used, or necessary to be used in connection with the safety, comfort, and convenience of persons transported.

. "Public service company" includes every common carrier.

. The term "service" is used in this title in its broadest and most inclusive sense.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%204[2007 c 234 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1931-S.SL.pdf?cite=1993%20c%20427%20§%209[1993 c 427 § 9]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5756-S.SL.pdf?cite=1991%20c%20272%20§%203[1991 c 272 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c13.pdf?cite=1981%20c%2013%20§%202[1981 c 13 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.010[1961 c 14 § 81.04.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c316.pdf?cite=1955%20c%20316%20§%203[1955 c 316 § 3]; prior: 1929 c 223 § 1, part; 1923 c 116 § 1, part; 1911 c 117 § 8, part; RRS § 10344, part; ]

== 81.04.020 - Procedure before commission and courts.
Each commissioner shall have power to administer oaths, certify to all official acts, and to issue subpoenas for the attendance of witnesses and the production of papers, waybills, books, accounts, documents, and testimony in any inquiry, investigation, hearing, or proceeding in any part of the state.

The superior court of the county in which any such inquiry, investigation, hearing, or proceeding may be had, shall have power to compel the attendance of witnesses and the production of papers, waybills, books, accounts, documents, and testimony as required by such subpoena. The commission or the commissioner before which the testimony is to be given or produced, in case of the refusal of any witness to attend or testify or produce any papers required by the subpoena, shall report to the superior court in and for the county in which the proceeding is pending by petition, setting forth that due notice has been given of the time and place of attendance of said witnesses, or the production of said papers, and that the witness has been summoned in the manner prescribed in this chapter, and that the fees and mileage of the witness have been paid or tendered to the witness for his or her attendance and testimony, and that the witness has failed and refused to attend or produce the papers required by the subpoena, before the commission, in the cause or proceedings named in the notice and subpoena, or has refused to answer questions propounded to him or her in the course of such proceeding, and ask an order of said court, compelling the witness to attend and testify before the commission. The court, upon the petition of the commission, shall enter an order directing the witness to appear before said court at a time and place to be fixed by the court in such order, and then and there show cause why he or she has not responded to said subpoena. A copy of said order shall be served upon said witness. If it shall appear to the court that said subpoena was regularly issued by the commission, the court shall thereupon enter an order that said witness appear before the commission at said time and place as fixed in said order, and testify or produce the required papers, and upon failing to obey said order, said witness shall be dealt with as for contempt of court.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20284[2013 c 23 § 284]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.020[1961 c 14 § 81.04.020]; 1911 c 117 § 75, part; RRS § 10413, part; ]

== 81.04.030 - Number of witnesses may be limited.
In all proceedings before the commission the commission shall have the right, in their discretion, to limit the number of witnesses testifying upon any subject or proceeding to be inquired of before the commission.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.030[1961 c 14 § 81.04.030]; 1911 c 117 § 75, part; RRS § 10413, part; ]

== 81.04.040 - Witness fees and mileage.
Each witness who appears under subpoena shall receive for his or her attendance four dollars per day and ten cents per mile traveled by the nearest practicable route in going to and returning from the place of hearing. No witness shall be entitled to fees or mileage from the state when summoned at the instance of the public service companies affected.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20285[2013 c 23 § 285]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.040[1961 c 14 § 81.04.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c79.pdf?cite=1955%20c%2079%20§%203[1955 c 79 § 3]; 1911 c 117 § 76, part; RRS § 10414, part; ]

== 81.04.050 - Protection against self-incrimination.
The claim by any witness that any testimony sought to be elicited may tend to incriminate him or her shall not excuse such witness from testifying, but such evidence or testimony shall not be used against such person on the trial of any criminal proceeding, excepting in a prosecution for perjury. The commissioner shall have power to compel the attendance of witnesses at any place within the state.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20286[2013 c 23 § 286]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.050[1961 c 14 § 81.04.050]; 1911 c 117 § 76, part; RRS § 10414, part; ]

== 81.04.060 - Deposition—Service of process.
The commission shall have the right to take the testimony of any witness by deposition, and for that purpose the attendance of witnesses and the production of books, waybills, documents, papers and accounts may be enforced in the same manner as in the case of hearings before the commission, or any member thereof. Process issued under the provisions of this chapter shall be served as in civil cases.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.060[1961 c 14 § 81.04.060]; 1911 c 117 § 76, part; RRS § 10414, part; ]

== 81.04.070 - Inspection of books, papers, and documents.
The commission and each commissioner, or any person employed by the commission, shall have the right, at any and all times, to inspect the accounts, books, papers, and documents of any public service company, and the commission, or any commissioner, may examine under oath any officer, agent, or employee of such public service company in relation thereto, and with reference to the affairs of such company: PROVIDED, That any person other than a commissioner who shall make any such demand shall produce his or her authority from the commission to make such inspection.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20287[2013 c 23 § 287]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.070[1961 c 14 § 81.04.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%2077[1911 c 117 § 77]; RRS § 10415; ]

== 81.04.075 - Manner of serving papers.
All notices, applications, complaints, findings of fact, opinions and orders required by this title to be served may be served by mail and service thereof shall be deemed complete when a true copy of such paper or document is deposited in the post office properly addressed and stamped.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.075[1961 c 14 § 81.04.075]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c165.pdf?cite=1933%20c%20165%20§%207[1933 c 165 § 7]; RRS § 10458-1; ]

== 81.04.080 - Annual report—Other reports.
. Every public service company shall annually furnish to the commission a report in such form as the commission may require, and shall specifically answer all questions posed to it by the commission. The commission may prescribe a uniform system of accounts, and the manner in which the accounts must be kept. The detailed report must contain all the required statistics for the period of twelve months ending on the last day of any particular month prescribed by the commission for any public service company. The reports must be made out under oath and filed with the commission at its office in Olympia on a date the commission specifies by rule, unless additional time is granted by the commission.

. Any public service company that fails to file an annual report in the form and within the time required by the commission, including payment of any regulatory fee due, is subject to the following:

.. Monetary penalties of:

... Two hundred fifty dollars for reports filed one to thirty days past the due date;

... Five hundred dollars for reports filed thirty-one to sixty days past the due date;

... One thousand dollars for reports filed sixty-one to ninety days past the due date; or

.. Upon notice by the commission, cancellation or revocation of its operating authority and additional penalties pursuant to RCW 81.04.380 and 81.04.405.

. The commission may waive penalties when a public service company is able to sufficiently demonstrate that its failure to file an annual report in the form and within the time required was due to circumstances beyond its control. Requests for any such waiver must be received within fifteen days of the date a penalty is assessed.

. The commission may require any public service company to file monthly reports of earnings and expenses, and to file periodical or special reports, or both, concerning any matter the commission is authorized or required, by this or any other law, to inquire into or keep itself informed about, or which it is required to enforce, the periodical or special reports to be under oath whenever the commission so requires.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6179.SL.pdf?cite=2018%20c%20104%20§%202[2018 c 104 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%205[2007 c 234 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c107.pdf?cite=1989%20c%20107%20§%202[1989 c 107 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.080[1961 c 14 § 81.04.080]; 1911 c 117 § 78, part; RRS § 10416, part; ]

== 81.04.090 - Forms of records to be prescribed.
The commission may, in its discretion, prescribe the forms of any and all accounts, records and memoranda to be kept by public service companies, including the accounts, records and memoranda of the movement of traffic, sales of its product, the receipts and expenditures of money. The commission shall at all times have access to all accounts, records and memoranda kept by public service companies, and may employ special agents or examiners, who shall have power to administer oaths and authority, under the order of the commission, to examine witnesses and to inspect and examine any and all accounts, records and memoranda kept by such companies. The commission may, in its discretion, prescribe the forms of any and all reports, accounts, records and memoranda to be furnished and kept by any public service company whose line or lines extend beyond the limits of this state, which are operated partly within and partly without the state, so that the same shall show any information required by the commission concerning the traffic movement, receipts and expenditures appertaining to those parts of the line within the state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.090[1961 c 14 § 81.04.090]; 1911 c 117 § 78, part; RRS § 10416, part; ]

== 81.04.100 - Production of out-of-state books and records.
The commission may by order with or without hearing require the production within this state, at such time and place as it may designate, of any books, accounts, papers or records kept by any public service company in any office or place without this state, or at the option of the company verified copies thereof, so that an examination thereof may be made by the commission or under its direction.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.100[1961 c 14 § 81.04.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c165.pdf?cite=1933%20c%20165%20§%202[1933 c 165 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%2079[1911 c 117 § 79]; RRS § 10421; ]

== 81.04.110 - Complaint—Hearing.
Complaint may be made by the commission of its own motion or by any person or corporation, chamber of commerce, board of trade, or any commercial, mercantile, agricultural or manufacturing society, or any body politic or municipal corporation, by petition or complaint in writing, setting forth any act or thing done or omitted to be done by any public service company or any person, persons, or entity acting as a public service company in violation, or claimed to be in violation, of any provision of law or of any order or rule of the commission.

When two or more public service companies or a person, persons, or entity acting as a public service company, (meaning to exclude municipal and other public corporations) are engaged in competition in any locality or localities in the state, either may make complaint against the other or others that the rates, charges, rules, regulations or practices of such other or others with or in respect to which the complainant is in competition, are unreasonable, unremunerative, discriminatory, illegal, unfair or intending or tending to oppress the complainant, to stifle competition, or to create or encourage the creation of monopoly, and upon such complaint or upon complaint of the commission upon its own motion, the commission shall have power, after notice and hearing as in other cases, to, by its order, subject to appeal as in other cases, correct the abuse complained of by establishing such uniform rates, charges, rules, regulations or practices in lieu of those complained of, to be observed by all of such competing public service companies in the locality or localities specified as shall be found reasonable, remunerative, nondiscriminatory, legal, and fair or tending to prevent oppression or monopoly or to encourage competition, and upon any such hearing it shall be proper for the commission to take into consideration the rates, charges, rules, regulations and practices of the public service company or companies complained of in any other locality or localities in the state.

All matters upon which complaint may be founded may be joined in one hearing, and no motion shall be entertained against a complaint for misjoinder of complaints or grievances or misjoinder of parties; and in any review of the courts of orders of the commission the same rule shall apply and pertain with regard to the joinder of complaints and parties as herein provided: PROVIDED, All grievances to be inquired into shall be plainly set forth in the complaint. No complaint shall be dismissed because of the absence of direct damage to the complainant.

Upon the filing of a complaint, the commission shall cause a copy thereof to be served upon the person or company complained of, which shall be accompanied by a notice fixing the time when and place where a hearing will be had upon such complaint. The time fixed for such hearing shall not be less than ten days after the date of the service of such notice and complaint, excepting as herein provided. Rules of practice and procedure not otherwise provided for in this title may be prescribed by the commission.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6215.SL.pdf?cite=1994%20c%2037%20§%202[1994 c 37 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.110[1961 c 14 § 81.04.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c145.pdf?cite=1913%20c%20145%20§%201[1913 c 145 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%2080[1911 c 117 § 80]; RRS § 10422; ]

== 81.04.120 - Hearing—Order—Record.
At the time fixed for the hearing mentioned in RCW 81.04.110, the complainant and the person or corporation complained of shall be entitled to be heard and introduce such evidence as he or she or it may desire. The commission shall issue process to enforce the attendance of all necessary witnesses. At the conclusion of such hearing, the commission shall make and render findings concerning the subject matter and facts inquired into and enter its order based thereon. A copy of such order, certified under the seal of the commission, shall be served upon the person or corporation complained of, or his or her or its attorney, which order shall, of its own force, take effect and become operative twenty days after the service thereof, except as otherwise provided. Where an order cannot, in the judgment of the commission, be complied with within twenty days, the commission may prescribe such additional time as in its judgment is reasonably necessary to comply with the order, and may, on application and for good cause shown, extend the time for compliance fixed in its order. A full and complete record of all proceedings had before the commission, or any member thereof, on any formal hearing had, and all testimony shall be taken down by a stenographer appointed by the commission, and the parties shall be entitled to be heard in person or by attorney. In case of an action to review any order of the commission, a transcript of such testimony, together with all exhibits introduced, and of the record and proceedings in the cause, shall constitute the record of the commission.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20288[2013 c 23 § 288]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.120[1961 c 14 § 81.04.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%2081[1911 c 117 § 81]; RRS § 10423; ]

== 81.04.130 - Suspension of tariff change—Waiver of provisions during state of emergency.
Whenever any public service company, subject to regulation by the commission as to rates and service, files with the commission any schedule, classification, rule, or regulation, the effect of which is to change any rate, fare, charge, rental, or toll previously charged, the commission may, either upon its own motion or upon complaint, upon notice, hold a hearing concerning the proposed change and the reasonableness and justness of it. Pending the hearing and the decision, the commission may suspend the operation of the rate, fare, charge, rental, or toll, if the change is proposed by a common carrier other than a solid waste collection company, for a period not exceeding seven months, and, if proposed by a solid waste collection company, for a period not exceeding ten months from the time the change would otherwise go into effect. After a full hearing the commission may make the order in reference to the change as would be provided in a hearing initiated after the change had become effective.

At any hearing involving any change in any schedule, classification, rule, or regulation the effect of which is to increase any rate, fare, charge, rental, or toll theretofore charged, the burden of proof to show that the increase is just and reasonable is upon the public service company. When any common carrier files any tariff, classification, rule, or regulation the effect of which is to decrease any rate, fare, or charge, the burden of proof to show that such decrease is just and reasonable is upon the common carrier.

During a state of emergency declared under RCW 43.06.010(12), the governor may waive or suspend the operation or enforcement of this section or any portion of this section or under any administrative rule, and issue any orders to facilitate the operation of state or local government or to promote and secure the safety and protection of the civilian population.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6950.SL.pdf?cite=2008%20c%20181%20§%20404[2008 c 181 § 404]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%206[2007 c 234 § 6]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1260-S.SL.pdf?cite=1993%20c%20300%20§%201[1993 c 300 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c143.pdf?cite=1984%20c%20143%20§%201[1984 c 143 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.130[1961 c 14 § 81.04.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c162.pdf?cite=1941%20c%20162%20§%201[1941 c 162 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c169.pdf?cite=1937%20c%20169%20§%202[1937 c 169 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c165.pdf?cite=1933%20c%20165%20§%203[1933 c 165 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c133.pdf?cite=1915%20c%20133%20§%201[1915 c 133 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%2082[1911 c 117 § 82]; Rem. Supp. 1941 § 10424; ]

== 81.04.140 - Order requiring joint action.
Whenever any order of the commission shall require joint action by two or more public service companies, such order shall specify that the same shall be made at their joint cost, and the companies affected shall have thirty days, or such further time, as the commission may prescribe, within which to agree upon the part or division of cost which each shall bear, and costs of operation and maintenance in the future, or the proportion of charges or revenue each shall receive from such joint service and the rules to govern future operations. If at the expiration of such time such companies shall fail to file with the commission a statement that an agreement has been made for the division or apportionment of such cost, the division of costs of operation and maintenance to be incurred in the future and the proportion of charges or revenue each shall receive from such joint service and the rules to govern future operations, the commission shall have authority, after further hearing, to enter a supplemental order fixing the proportion of such cost or expense to be borne by each company, and the manner in which the same shall be paid and secured.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.140[1961 c 14 § 81.04.140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%2083[1911 c 117 § 83]; RRS § 10425; ]

== 81.04.150 - Remunerative rate—Change without authorization prohibited—Waiver of provisions during state of emergency.
Whenever the commission finds, after a hearing upon its own motion or upon complaint as provided in this chapter, that any rate, toll, rental, or charge that has been the subject of complaint and inquiry is sufficiently remunerative to the public service company subject to regulation by the commission as to rates and service affected by it, the commission may order that the rate, toll, rental, or charge must not be changed, altered, abrogated, or discontinued, nor must there be any change in the classification that will change or alter the rate, toll, rental, or charge without first obtaining the consent of the commission authorizing the change to be made.

During a state of emergency declared under RCW 43.06.010(12), the governor may waive or suspend the operation or enforcement of this section or any portion of this section or under any administrative rule, and issue any orders to facilitate the operation of state or local government or to promote and secure the safety and protection of the civilian population.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6950.SL.pdf?cite=2008%20c%20181%20§%20405[2008 c 181 § 405]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%207[2007 c 234 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c143.pdf?cite=1984%20c%20143%20§%202[1984 c 143 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.150[1961 c 14 § 81.04.150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%2084[1911 c 117 § 84]; RRS § 10426; ]

== 81.04.160 - Rules.
The commission may adopt rules that pertain to the comfort and convenience of the public using the services of public service companies that are subject to regulation by the commission as to services provided.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%208[2007 c 234 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.160[1961 c 14 § 81.04.160]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%2085[1911 c 117 § 85]; RRS § 10427; ]

== 81.04.200 - Rehearing before commission.
Any public service company affected by any order of the commission, and deeming itself aggrieved, may, after the expiration of two years from the date of such order taking effect, petition the commission for a rehearing upon the matters involved in such order, setting forth in such petition the grounds and reasons for such rehearing, which grounds and reasons may comprise and consist of changed conditions since the issuance of such order, or by showing a result injuriously affecting the petitioner which was not considered or anticipated at the former hearing, or that the effect of such order has been such as was not contemplated by the commission or the petitioner, or for any good and sufficient cause which for any reason was not considered and determined in such former hearing. Upon the filing of such petition, such proceedings shall be had thereon as are provided for hearings upon complaint, and such orders may be reviewed as are other orders of the commission: PROVIDED, That no order superseding the order of the commission denying such rehearing shall be granted by the court pending the review. In case any order of the commission shall not be reviewed, but shall be complied with by the public service company, such petition for rehearing may be filed within six months from and after the date of the taking effect of such order, and the proceedings thereon shall be as in this section provided. The commission, may, in its discretion, permit the filing of a petition for rehearing at any time. No order of the commission upon a rehearing shall affect any right of action or penalty accruing under the original order unless so ordered by the commission.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.200[1961 c 14 § 81.04.200]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%2089[1911 c 117 § 89]; RRS § 10431; ]

== 81.04.210 - Commission may change orders.
The commission may at any time, upon notice to the public service company affected, and after opportunity to be heard as provided in the case of complaints rescind, alter or amend any order or rule made, issued or promulgated by it, and any order or rule rescinding, altering or amending any prior order or rule shall, when served upon the public service company affected, have the same effect as herein provided for original orders and rules.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.210[1961 c 14 § 81.04.210]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%2090[1911 c 117 § 90]; RRS § 10432; ]

== 81.04.220 - Reparations.
After a complaint is made to the commission concerning the reasonableness of any rate, fare, toll, rental or charge for any service performed by any public service company subject to regulation by the commission as to rates and service, and the complaint is investigated by the commission, and the commission determines both that the public service company has charged an excessive or exorbitant amount for the service and that any party complainant is entitled to an award of damages, the commission shall order the public service company to pay the complainant the excess amount found to have been charged, whether the excess amount was charged and collected before or after the filing of the complaint, with interest from the date of the collection of the excess amount.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%209[2007 c 234 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.220[1961 c 14 § 81.04.220]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c258.pdf?cite=1943%20c%20258%20§%201[1943 c 258 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c29.pdf?cite=1937%20c%2029%20§%201[1937 c 29 § 1]; Rem. Supp. 1943 § 10433; ]

== 81.04.230 - Overcharges—Refund.
When complaint has been made to the commission that any public service company has charged an amount for any service rendered in excess of the lawful rate in force at the time such charge was made, and the same has been investigated and the commission has determined that the overcharge allegation is true, the commission may order that the public service company pay to the complainant the amount of the overcharge so found, whether such overcharge was made before or after the filing of said complaint, with interest from the date of collection of such overcharge.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.230[1961 c 14 § 81.04.230]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c29.pdf?cite=1937%20c%2029%20§%202[1937 c 29 § 2]; RRS § 10433-1; ]

== 81.04.235 - Limitation of actions.
All complaints against public service companies for recovery of overcharges shall be filed with the commission within two years from the time the cause of action accrues, and not after, except as hereinafter provided, and except that if claim for the overcharge has been presented in writing to the public service company within the two-year period of limitation, said period shall be extended to include six months from the time notice in writing is given by the public service company to the claimant of disallowance of the claim, or any part or parts thereof, specified in the notice.

If on or before expiration of the two-year period of limitation for the recovery of overcharges, a public service company begins action under RCW 81.28.270 for recovery of charges in respect of the same transportation service, or, without beginning action, collects charges in respect of that service, said period of limitation shall be extended to include ninety days from the time such action is begun or such charges are collected by the carrier.

All complaints against public service companies for the recovery of damages not based on overcharges shall be filed with the commission within six months from the time the cause of action accrues except as hereinafter provided.

The six-month period of limitation for recovery of damages not based on overcharges shall be extended for a like period and under the same conditions as prescribed for recovery of overcharges. If the six-month period for recovery of damages not based on overcharges has expired at the time action is commenced under RCW 81.28.270 for recovery of charges with respect to the same transportation service, or, without beginning such action, charges are collected with respect to that service, complaints therefor shall be filed with the commission within ninety days from the commencement of such action or the collection of such charges by the carrier.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c59.pdf?cite=1963%20c%2059%20§%204[1963 c 59 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.235[1961 c 14 § 81.04.235]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c79.pdf?cite=1955%20c%2079%20§%205[1955 c 79 § 5]; ]

== 81.04.236 - When cause of action deemed to accrue.
The cause of action for the purposes of RCW 81.04.235, 81.04.240, and 81.28.270 shall be deemed to accrue: (a) In respect of a shipment of property, upon delivery or tender of delivery thereof by the carrier, and not after; (b) in respect of goods or service or services other than a shipment of property, upon the rendering of an invoice or statement of charges by the public service company, and not after.

The provisions of this section shall extend to and embrace cases in which the cause of action has heretofore accrued as well as cases in which the cause of action may hereafter accrue.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.236[1961 c 14 § 81.04.236]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c79.pdf?cite=1955%20c%2079%20§%206[1955 c 79 § 6]; ]

== 81.04.240 - Action in court on reparations and overcharges—Procedure.
If the public service company subject to regulation by the commission as to rates and service does not comply with the order of the commission for the payment of damages or overcharges within the time limited in the order, action may be brought in any superior court where service may be had upon the company to recover the amount of damages or overcharges with interest. The commission shall certify and file its record in the case, including all exhibits, with the clerk of the court within thirty days after the action is started. The action must be heard on the evidence and exhibits introduced before and certified by the commission.

If the complainant prevails in the action, the court shall enter judgment for the amount of damages or overcharges with interest and award the complainant reasonable attorney's fees, and the cost of preparing and certifying the record for the benefit of and to be paid to the commission by complainant, and deposited by the commission in the public service revolving fund, the sums to be fixed and collected as a part of the costs of the action.

If the order of the commission is found contrary to law or erroneous by the rejection of testimony properly offered, the court shall remand the cause to the commission with instructions to receive the testimony so proffered and rejected and enter a new order based upon the evidence theretofore taken and such as it is directed to receive.

The court may remand any action it reverses to the commission for further action.

Appeals to the supreme court shall lie as in other civil cases. Action to recover damages or overcharges must be filed in the superior court within one year from the date of the order of the commission.

The procedure provided in this section is exclusive, and neither the supreme court nor any superior court has jurisdiction except as provided.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2010[2007 c 234 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.240[1961 c 14 § 81.04.240]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c79.pdf?cite=1955%20c%2079%20§%204[1955 c 79 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c258.pdf?cite=1943%20c%20258%20§%202[1943 c 258 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c29.pdf?cite=1937%20c%2029%20§%203[1937 c 29 § 3]; Rem. Supp. 1943 § 10433-2; ]

== 81.04.250 - Determination of rates.
The commission may, upon complaint or upon its own motion, prescribe and authorize just and reasonable rates for the transportation of persons or property for any public service company subject to regulation by the commission as to rates and service, whenever and as often as it deems necessary or proper. The commission shall, before any hearing upon the complaint or motion, notify the complainants and the carrier concerned of the time and place of the hearing by giving at least ten days' written notice thereof, specifying that at the time and place designated a hearing will be held for the purpose of prescribing and authorizing the rates. The notice is sufficient to authorize the commission to inquire into and pass upon the matters designated in this section.

In exercising this power, the commission may use any standard, formula, method, or theory of valuation reasonably calculated to arrive at the objective of prescribing and authorizing just and reasonable rates.

In the exercise of this power, the commission may consider, in addition to other factors, the following:

. The effect of the rates upon movement of traffic by the carriers;

. The public need for adequate transportation facilities, equipment, and service at the lowest level of charges consistent with the provision, maintenance, and renewal of the facilities, equipment, and service; and

. The carrier need for revenue of a level that under honest, efficient, and economical management is sufficient to cover the cost, including all operating expenses, depreciation accruals, rents, and taxes of every kind, of providing adequate transportation service, plus an amount equal to the percentage of that cost as is reasonably necessary for the provision, maintenance, and renewal of the transportation facilities or equipment and a reasonable profit to the carrier. The relation of carrier expenses to carrier revenues may be deemed the proper test of a reasonable profit.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2011[2007 c 234 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c143.pdf?cite=1984%20c%20143%20§%203[1984 c 143 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.250[1961 c 14 § 81.04.250]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c75.pdf?cite=1951%20c%2075%20§%201[1951 c 75 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c165.pdf?cite=1933%20c%20165%20§%204[1933 c 165 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c182.pdf?cite=1913%20c%20182%20§%201[1913 c 182 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%2092[1911 c 117 § 92]; RRS § 10441; ]

== 81.04.260 - Summary proceedings.
Whenever the commission shall be of opinion that any public service company is failing or omitting, or about to fail or omit, to do anything required of it by law, or by order, direction or requirement of the commission, or is doing anything, or about to do anything, or permitting anything, or about to permit anything to be done contrary to or in violation of law or of any order, direction or requirement of the commission authorized by this title, it shall direct the attorney general to commence an action or proceeding in the superior court of the state of Washington for Thurston county, or in the superior court of any county in which such company may do business, in the name of the state of Washington on the relation of the commission, for the purpose of having such violations or threatened violations stopped and prevented, either by mandamus or injunction. The attorney general shall thereupon begin such action or proceeding by petition to such superior court, alleging the violation complained of, and praying for appropriate relief by way of mandamus or injunction. It shall thereupon be the duty of the court to specify a time, not exceeding twenty days after the service of the copy of the petition, within which the public service company complained of must answer the petition. In case of default in answer or after answer, the court shall immediately inquire into the facts and circumstances in such manner as the court shall direct, without other or formal pleadings, and without respect to any technical requirement. Such persons or corporations as the court may deem necessary or proper to be joined as parties, in order to make its judgment, order or writ effective, may be joined as parties. The final judgment in any such action or proceeding shall either dismiss the action or proceeding or direct that the writ of mandamus or injunction, or both, issue as prayed for in the petition, or in such other modified form as the court may determine will afford appropriate relief. Appellate review of the final judgment may be sought in the same manner and with the same effect as review of judgments of the superior court in actions to review orders of the commission. All provisions of this chapter relating to the time of review, the manner of perfecting the same, the filing of briefs, hearings and supersedeas, shall apply to appeals to the supreme court or the court of appeals under the provisions of this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c202.pdf?cite=1988%20c%20202%20§%2064[1988 c 202 § 64]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c81.pdf?cite=1971%20c%2081%20§%20143[1971 c 81 § 143]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.260[1961 c 14 § 81.04.260]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%2093[1911 c 117 § 93]; RRS § 10442; ]

== 81.04.270 - Accounts to be kept separate.
Any public service company, subject to regulation by the commission as to rates and services [service], that engages in the sale of merchandise or appliances or equipment shall keep separate accounts, as prescribed by the commission, of its capital employed in such business and of its revenues therefrom and operating expenses thereof. The capital employed in such business is not a part of the fair value of the company's property for rate making purposes, and the revenues from or operating expenses of such business are not a part of the operating revenues and expenses of the company as a public service company.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2012[2007 c 234 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.270[1961 c 14 § 81.04.270]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c165.pdf?cite=1933%20c%20165%20§%208[1933 c 165 § 8]; RRS § 10458-2; ]

== 81.04.280 - Purchase and sale of stock by employees.
A public service company subject to regulation by the commission as to rates and service shall not: (1) Permit any employee to sell, offer for sale, or solicit the purchase of any security of any other person or corporation during such hours as such employee is engaged to perform any duty of such public service company; (2) by any means or device, require any employee to purchase or contract to purchase any of its securities or those of any other person or corporation; or (3) require any employee to permit the deduction from his or her wages or salary of any sum as a payment or to be applied as a payment of any purchase or contract to purchase any security of such public service company or of any other person or corporation.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20289[2013 c 23 § 289]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2013[2007 c 234 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.280[1961 c 14 § 81.04.280]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c165.pdf?cite=1933%20c%20165%20§%209[1933 c 165 § 9]; RRS § 10458-3; ]

== 81.04.290 - Sale of stock to employees and patrons.
A corporate public service company, either heretofore or hereafter organized under the laws of this state, may sell to its employees and patrons any increase of its capital stock, or part thereof, without first offering it to existing stockholders: PROVIDED, That such sale is approved by the holders of a majority of the capital stock, at a regular or special meeting held after notice given as to the time, place, and object thereof as provided by law and the bylaws of the company. Such sales shall be at prices and in amounts for each purchaser and upon terms and conditions as set forth in the resolution passed at the stockholders' meeting, or in a resolution passed at a subsequent meeting of the board of trustees if the resolution passed at the stockholders' meeting shall authorize the board to determine prices, amounts, terms, and conditions, except that in either event a minimum price for the stock must be fixed in the resolution passed at the stockholders' meeting.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.290[1961 c 14 § 81.04.290]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c79.pdf?cite=1955%20c%2079%20§%207[1955 c 79 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c110.pdf?cite=1923%20c%20110%20§%201[1923 c 110 § 1]; RRS § 10344-1; ]

== 81.04.300 - Budgets to be filed—Supplementary budgets.
The commission may regulate, restrict, and control the budgets of expenditures of public service companies subject to regulation by the commission as to rates and service. The commission may require each company to prepare a budget showing the amount of money which, in its judgment, is needed during the ensuing year for maintenance, operation, and construction, classified by accounts as prescribed by the commission, and shall within ten days of the date it is approved by the company file it with the commission for its investigation and approval or rejection. When a budget has been filed, the commission shall examine into and investigate it to determine whether the expenditures therein proposed are fair and reasonable and not contrary to public interest.

Adjustments or additions to budget expenditures may be made from time to time during the year by filing a supplementary budget with the commission for its investigation and approval or rejection.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2014[2007 c 234 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.300[1961 c 14 § 81.04.300]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c248.pdf?cite=1959%20c%20248%20§%2015[1959 c 248 § 15]; prior: 1933 c 165 § 10, part; RRS § 10458-4, part; ]

== 81.04.310 - Commission's control over expenditures.
The commission may, both as to original and supplementary budgets, prior to the making or contracting for the expenditure of any item therein, and after notice to the company and a hearing thereon, reject any item of the budget. The commission may require any company to furnish further information, data, or detail as to any proposed item of expenditure.

Failure of the commission to object to any item of expenditure within sixty days of the filing of any original budget or within thirty days of the filing of any supplementary budget shall constitute authority to the company to proceed with the making of or contracting for such expenditure, but such authority may be terminated at any time by objection made thereto by the commission prior to the making of or contracting for such expenditure.

Examination, investigation, and determination of the budget by the commission shall not bar or estop it from later determining whether any of the expenditures made thereunder are fair, reasonable, and commensurate with the service, material, supplies, or equipment received.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.310[1961 c 14 § 81.04.310]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c248.pdf?cite=1959%20c%20248%20§%2016[1959 c 248 § 16]; prior: 1933 c 165 § 10, part; RRS § 10458-4, part; ]

== 81.04.320 - Budget rules and regulations.
The commission may prescribe the necessary rules and regulations to place RCW 81.04.300 through 81.04.330 in operation. It may by general order, exempt in whole or in part from the operation thereof companies whose gross operating revenues are less than twenty-five thousand dollars a year. The commission may upon request of any company withhold from publication during such time as the commission may deem advisable, any portion of any original or supplementary budget relating to proposed capital expenditures.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.320[1961 c 14 § 81.04.320]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c248.pdf?cite=1959%20c%20248%20§%2017[1959 c 248 § 17]; prior: 1933 c 165 § 10, part; RRS § 10458-4, part; ]

== 81.04.330 - Effect of unauthorized expenditure—Emergencies.
Any public service company subject to regulation by the commission as to rates and service may make or contract for any rejected item of expenditure, but in such case the rejected item of expenditure shall not be allowed as an operating expense, or as to items of construction, as a part of the fair value of the company's property used and useful in serving the public: PROVIDED, That such items of construction may at any time thereafter be so allowed in whole or in part upon proof that they are used and useful. Any company may upon the happening of any emergency caused by fire, flood, explosion, storm, earthquake, riot, or insurrection, or for the immediate preservation or restoration to condition of usefulness of any of its property, the usefulness of which has been destroyed by accident, make the necessary expenditure therefor free from the operation of RCW 81.04.300 through 81.04.330.

Any finding and order entered by the commission is effective until vacated and set aside in proper proceedings for review thereof.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2015[2007 c 234 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.330[1961 c 14 § 81.04.330]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c248.pdf?cite=1959%20c%20248%20§%2018[1959 c 248 § 18]; prior: 1933 c 165 § 10, part; RRS § 10458-4, part; ]

== 81.04.350 - Depreciation and retirement accounts.
The commission may after hearing require any public service company subject to regulation by the commission as to rates and service to carry proper and adequate depreciation or retirement accounts in accordance with such rules, regulations, and forms of accounts as the commission may prescribe. The commission may from time to time ascertain and by order fix the proper and adequate rates of depreciation or retirement of the several classes of property of each public service company. Each public service company shall conform its depreciation or retirement accounts to the rates so prescribed. In fixing the rate of the annual depreciation or retirement charge, the commission may consider the rate and amount theretofore charged by the company for depreciation or retirement.

The commission may exercise like power and authority over all other reserve accounts of public service companies.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2016[2007 c 234 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.350[1961 c 14 § 81.04.350]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c169.pdf?cite=1937%20c%20169%20§%204[1937 c 169 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c165.pdf?cite=1933%20c%20165%20§%2013[1933 c 165 § 13]; RRS § 10458-7; ]

== 81.04.360 - Excessive earnings to reserve fund.
If any public service company subject to regulation by the commission as to rates and service earns in the period of five consecutive years immediately preceding the commission order fixing rates for such company a net utility operating income in excess of a reasonable rate of return upon the fair value of its property used and useful in the public service, the commission shall take official notice of such fact and of whether any such excess earnings were invested in such company's plant or otherwise used for purposes beneficial to the consumers of such company and may consider such facts in fixing rates for such company.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2017[2007 c 234 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.360[1961 c 14 § 81.04.360]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c285.pdf?cite=1959%20c%20285%20§%203[1959 c 285 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c165.pdf?cite=1933%20c%20165%20§%2014[1933 c 165 § 14]; RRS § 10458-8; ]

== 81.04.380 - Penalties—Violations by public service companies.
Every public service company, and all officers, agents and employees of any public service company, shall obey, observe and comply with every order, rule, direction or requirement made by the commission under authority of this title, so long as the same shall be and remain in force. Any public service company which shall violate or fail to comply with any provision of this title, or which fails, omits or neglects to obey, observe or comply with any order, rule, or any direction, demand or requirement of the commission, shall be subject to a penalty of not to exceed the sum of one thousand dollars for each and every offense. Every violation of any such order, direction or requirement of this title shall be a separate and distinct offense, and in case of a continuing violation every day's continuance thereof shall be and be deemed to be a separate and distinct offense.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.380[1961 c 14 § 81.04.380]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%2094[1911 c 117 § 94]; RRS § 10443; ]

== 81.04.385 - Penalties—Violations by officers, agents, and employees of public service companies and persons or entities acting as public service companies.
Every officer, agent or employee of any public service company or any person, persons, or entity acting as a public service company, who shall violate or fail to comply with, or who procures, aids or abets any violation by any public service company of any provision of this title, or who shall fail to obey, observe or comply with any order of the commission, or any provision of any order of the commission, or who procures, aids or abets any such public service company in its failure to obey, observe and comply with any such order or provision, shall be guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6215.SL.pdf?cite=1994%20c%2037%20§%203[1994 c 37 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.385[1961 c 14 § 81.04.385]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%2095[1911 c 117 § 95]; RRS § 10444; ]

== 81.04.387 - Penalties—Violations by other corporations.
Every corporation, other than a public service company, which shall violate any provision of this title, or which shall fail to obey, observe or comply with any order of the commission under authority of this title, so long as the same shall be and remain in force, shall be subject to a penalty of not to exceed the sum of one thousand dollars for each and every offense. Every such violation shall be a separate and distinct offense, and the penalty shall be recovered in an action as provided in RCW 81.04.400.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.387[1961 c 14 § 81.04.387]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%2096[1911 c 117 § 96]; RRS § 10445; ]

== 81.04.390 - Penalties—Violations by persons.
. Except as provided in subsection (2) of this section, every person who, either individually, or acting as an officer or agent of a corporation other than a public service company, violates any provision of this title, or fails to observe, obey, or comply with any order made by the commission under this title, so long as the same is or remains in force, or who procures, aids, or abets any such corporation in its violation of this title, or in its failure to obey, observe, or comply with any such order, is guilty of a gross misdemeanor.

. A violation pertaining to equipment on motor carriers transporting hazardous material is a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20385[2003 c 53 § 385]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c104.pdf?cite=1980%20c%20104%20§%205[1980 c 104 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.390[1961 c 14 § 81.04.390]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%2097[1911 c 117 § 97]; RRS § 10446; ]

== 81.04.400 - Actions to recover penalties—Disposition of fines, fees, penalties.
Actions to recover penalties under this title shall be brought in the name of the state of Washington in the superior court of Thurston county, or in the superior court of any county in or through which such public service company may do business. In all such actions the procedure and rules of evidence shall be the same as in ordinary civil actions, except as otherwise herein provided. All fines and penalties recovered by the state under this title shall be paid into the treasury of the state and credited to the state general fund or such other fund as provided by law: PROVIDED, That all fees, fines, forfeitures and penalties collected or assessed by a district court because of the violation of a state law shall be remitted as provided in chapter 3.62 RCW as now exists or is later amended.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c202.pdf?cite=1987%20c%20202%20§%20241[1987 c 202 § 241]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c199.pdf?cite=1969%20ex.s.%20c%20199%20§%2038[1969 ex.s. c 199 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.400[1961 c 14 § 81.04.400]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%2098[1911 c 117 § 98]; RRS § 10447; ]

== 81.04.405 - Additional penalties—Violations by public service companies and officers, agents, and employees.
In addition to all other penalties provided by law every public service company subject to the provisions of this title and every officer, agent or employee of any such public service company who violates or who procures, aids or abets in the violation of any provision of this title or any order, rule, regulation or decision of the commission, every person or corporation violating the provisions of any cease and desist order issued pursuant to RCW 81.04.510, and every person or entity found in violation pursuant to a complaint under RCW 81.04.110, shall incur a penalty of one hundred dollars for every such violation. Each and every such violation shall be a separate and distinct offense and in case of a continuing violation every day's continuance shall be and be deemed to be a separate and distinct violation. Every act of commission or omission which procures, aids or abets in the violation shall be considered a violation under the provisions of this section and subject to the penalty herein provided for.

The penalty herein provided for shall become due and payable when the person incurring the same receives a notice in writing from the commission describing such violation with reasonable particularity and advising such person that the penalty is due. The commission may, upon written application therefor, received within fifteen days, remit or mitigate any penalty provided for in this section or discontinue any prosecution to recover the same upon such terms as it in its discretion shall deem proper and shall have authority to ascertain the facts upon all such applications in such manner and under such regulations as it may deem proper. If the amount of such penalty is not paid to the commission within fifteen days after receipt of notice imposing the same or application for remission or mitigation has not been made within fifteen days after violator has received notice of the disposition of such application the attorney general shall bring an action in the name of the state of Washington in the superior court of Thurston county or of some other county in which such violator may do business, to recover such penalty. In all such actions the procedure and rules of evidence shall be the same as an ordinary civil action except as otherwise herein provided. All penalties recovered under this title shall be paid into the state treasury and credited to the public service revolving fund.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6215.SL.pdf?cite=1994%20c%2037%20§%204[1994 c 37 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c115.pdf?cite=1973%20c%20115%20§%202[1973 c 115 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c59.pdf?cite=1963%20c%2059%20§%203[1963 c 59 § 3]; ]

== 81.04.410 - Orders and rules conclusive.
In all actions between private parties and public service companies involving any rule or order of the commission, and in all actions for the recovery of penalties provided for in this title, or for the enforcement of the orders or rules issued and promulgated by the commission, the said orders and rules shall be conclusive unless set aside or annulled in a review as in this title provided.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.410[1961 c 14 § 81.04.410]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%2099[1911 c 117 § 99]; RRS § 10448; ]

== 81.04.420 - Commission intervention where order or rule is involved.
In all court actions involving any rule or order of the commission, where the commission has not been made a party, the commission shall be served with a copy of all pleadings, and shall be entitled to intervene. Where the fact that the action involves a rule or order of the commission does not appear until the time of trial, the court shall immediately direct the clerk to notify the commission of the pendency of such action, and shall permit the commission to intervene in such action.

The failure to comply with the provisions of this section shall render void and of no effect any judgment in such action, where the effect of such judgment is to modify or nullify any rule or order of the commission.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.420[1961 c 14 § 81.04.420]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c67.pdf?cite=1943%20c%2067%20§%201[1943 c 67 § 1]; Rem. Supp. 1943 § 10448-1; ]

== 81.04.430 - Findings of department prima facie correct.
Whenever the commission has issued or promulgated any order or rule, in any writ of review brought by a public service company to determine the reasonableness of such order or rule, the findings of fact made by the commission shall be prima facie correct, and the burden shall be upon said public service company to establish the order or rule to be unreasonable or unlawful.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.430[1961 c 14 § 81.04.430]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%20100[1911 c 117 § 100]; RRS § 10449; ]

== 81.04.440 - Companies liable for damages.
In case any public service company shall do, cause to be done or permit to be done any act, matter or thing prohibited, forbidden or declared to be unlawful, or shall omit to do any act, matter or thing required to be done, either by any law of this state, by this title or by any order or rule of the commission, such public service company shall be liable to the persons or corporations affected thereby for all loss, damage or injury caused thereby or resulting therefrom, and in case of recovery if the court shall find that such act or omission was wilful, it may, in its discretion, fix a reasonable counsel or attorney's fee, which shall be taxed and collected as part of the costs in the case. An action to recover for such loss, damage or injury may be brought in any court of competent jurisdiction by any person or corporation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.440[1961 c 14 § 81.04.440]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%20102[1911 c 117 § 102]; RRS § 10451; ]

== 81.04.450 - Certified copies of orders, rules, etc.—Evidentiary effect.
Upon application of any person the commission shall furnish certified copies of any classification, rate, rule, regulation or order established by such commission, and the printed copies published by authority of the commission, or any certified copy of any such classification, rate, rule, regulation or order, with seal affixed, shall be admissible in evidence in any action or proceeding, and shall be sufficient to establish the fact that the charge, rate, rule, order or classification therein contained is the official act of the commission. When copies of any classification, rate, rule, regulation or order not contained in the printed reports, or copies of papers, accounts or records of public service companies filed with the commission shall be demanded from the commission for proper use, the commission shall charge a reasonable compensation therefor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.450[1961 c 14 § 81.04.450]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%20103[1911 c 117 § 103]; RRS § 10452; ]

== 81.04.460 - Commission to enforce public service laws—Employees as peace officers.
It shall be the duty of the commission to enforce the provisions of this title and all other acts of this state affecting public service companies, the enforcement of which is not specifically vested in some other officer or tribunal. Any employee of the commission may, without a warrant, arrest any person found violating in his or her presence any provision of this title, or any rule or regulation adopted by the commission: PROVIDED, That each such employee shall be first specifically designated in writing by the commission or a member thereof as having been found to be a fit and proper person to exercise such authority. Upon being so designated, such person shall be a peace officer and a police officer for the purposes herein mentioned.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20290[2013 c 23 § 290]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c173.pdf?cite=1961%20c%20173%20§%202[1961 c 173 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.460[1961 c 14 § 81.04.460]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%20101[1911 c 117 § 101]; RRS § 10450; ]

== 81.04.470 - Right of action not released—Penalties cumulative.
This title shall not have the effect to release or waive any right of action by the state or any person for any right, penalty or forfeiture which may have arisen or may hereafter arise under any law of this state; and all penalties accruing under this title shall be cumulative of each other, and a suit for the recovery of one penalty shall not be a bar to the recovery of any other: PROVIDED, That no contract, receipt, rule or regulation shall exempt any corporation engaged in transporting livestock by railway from liability of a common carrier, or carrier of livestock which would exist had no contract, receipt, rule or regulation been made or entered into.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.470[1961 c 14 § 81.04.470]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%20104[1911 c 117 § 104]; RRS § 10453; ]

== 81.04.490 - Application to municipal utilities—Safety regulation of municipal gas and hazardous liquid pipelines.
Nothing in this title shall authorize the commission to make or enforce any order affecting rates, tolls, rentals, contracts or charges or service rendered, or the safety, adequacy or sufficiency of the facilities, equipment, instrumentalities or buildings, or the reasonableness of rules or regulations made, furnished, used, supplied or in force affecting any street railroad owned and operated by any city or town, but all other provisions enumerated herein shall apply to public utilities owned by any city or town. The commission shall regulate the safety of all hazardous liquid and gas pipelines constructed, owned, or operated by any city or town under chapter 81.88 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5225-S.SL.pdf?cite=2007%20c%20142%20§%2010[2007 c 142 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.490[1961 c 14 § 81.04.490]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%20105[1911 c 117 § 105]; RRS § 10454; ]

== 81.04.500 - Duties of attorney general.
It shall be the duty of the attorney general to represent and appear for the people of the state of Washington and the commission in all actions and proceedings involving any question under this title, or under or in reference to any act or order of the commission; and it shall be the duty of the attorney general generally to see that all laws affecting any of the persons or corporations herein enumerated are complied with, and that all laws, the enforcement of which devolves upon the commission, are enforced, and to that end he or she is authorized to institute, prosecute, and defend all necessary actions and proceedings.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20291[2013 c 23 § 291]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.04.500[1961 c 14 § 81.04.500]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c117.pdf?cite=1911%20c%20117%20§%205[1911 c 117 § 5]; RRS § 10341; ]

== 81.04.510 - Engaging in business or operating without approval or authority—Procedure.
Whether or not any person or corporation is conducting business requiring operating authority, or has performed or is performing any act requiring approval of the commission without securing such approval, shall be a question of fact to be determined by the commission. Whenever the commission believes that any person or corporation is engaged in operations without the necessary approval or authority required by any provision of this title, it may institute a special proceeding requiring such person or corporation to appear before the commission at a location convenient for witnesses and the production of evidence and bring with him or her or it books, records, accounts, and other memoranda, and give testimony under oath as to his or her or its operations or acts, and the burden shall rest upon such person or corporation of proving that his or her or its operations or acts are not subject to the provisions of this chapter. The commission may consider any and all facts that may indicate the true nature and extent of the operations or acts and may subpoena such witnesses and documents as it deems necessary.

After having made the investigation herein described, the commission is authorized and directed to issue the necessary order or orders declaring the operations or acts to be subject to, or not subject to, the provisions of this title. In the event the operations or acts are found to be subject to the provisions of this title, the commission is authorized and directed to issue cease and desist orders to all parties involved in the operations or acts.

In proceedings under this section, no person or corporation shall be excused from testifying or from producing any book, waybill, document, paper, or account before the commission when ordered to do so, on the ground that the testimony or evidence, book, waybill, document, paper, or account required of him or her or it may tend to incriminate him or her or it or subject him or her or it to penalty or forfeiture; but no person or corporation shall be prosecuted, punished, or subjected to any penalty or forfeiture for or on account of any account, transaction, matter, or thing concerning which he or she or it shall under oath have testified or produced documentary evidence in proceedings under this section: PROVIDED, That no person so testifying shall be exempt from prosecution or punishment for any perjury committed by him or her in his or her testimony.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20292[2013 c 23 § 292]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c115.pdf?cite=1973%20c%20115%20§%2015[1973 c 115 § 15]; ]

== 81.04.530 - Controlled substances, alcohol.
A person or employer operating as a motor carrier shall comply with the requirements of the United States department of transportation federal motor carrier safety regulations as contained in Title 49 C.F.R. Part 382, controlled substances and alcohol use and testing. A person or employer who begins or conducts commercial motor vehicle operations without having a controlled substance and alcohol testing program that is in compliance with the requirements of Title 49 C.F.R. Part 382 is subject to a penalty, under the process set forth in RCW 81.04.405, of up to one thousand five hundred dollars and up to an additional five hundred dollars for each motor vehicle driver employed by the person or employer who is not in compliance with the motor vehicle driver testing requirements. A person or employer having actual knowledge that a driver has tested positive for controlled substances or alcohol who allows a positively tested person to continue to perform a safety-sensitive function is subject to a penalty, under the process set forth in RCW 81.04.405, of one thousand five hundred dollars.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1971-S.SL.pdf?cite=1999%20c%20351%20§%206[1999 c 351 § 6]; ]

== 81.04.540 - Regulation of common carriers, railroad safety practices.
. The commission shall cooperate with the federal government and the United States department of transportation, or its successor, or any other commission or agency delegated or authorized to regulate interstate or foreign commerce by common carriers, to the end that the transportation of property and passengers by common carriers in interstate or foreign commerce into and through the state of Washington may be regulated and that the laws of the United States and the state of Washington are enforced and administered cooperatively in the public interest.

. In addition to its authority concerning interstate commerce under this title, the commission may regulate common carriers in interstate commerce within the state under the authority of and in accordance with any act of congress that vests in or delegates to the commission such authority as an agency of the United States government or under an agreement with the United States department of transportation, or its successor, or any other commission or agency delegated or authorized to regulate interstate or foreign commerce by common carriers.

. For the purpose of participating with the United States department of transportation in investigation and inspection activities necessary to enforce federal railroad safety regulations, the commission has regulatory jurisdiction over the safety practices for railroad equipment, facilities, rolling stock, and operations in the state.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%202[2007 c 234 § 2]; ]

== 81.04.550 - Railroad safety administration.
The commission shall administer the railroad safety provisions of this title to the fullest extent allowed under 49 U.S.C. Sec. 20106 and state law.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%203[2007 c 234 § 3]; ]

== 81.04.560 - Railroad companies that transport crude oil must submit information relating to the ability to pay damages in the event of a spill or accident—Adoption of rules.
. The commission must require a railroad company that transports crude oil in Washington to submit information to the commission relating to the railroad company's ability to pay damages in the event of a spill or accident involving the transport of crude oil by the railroad company in Washington. The information submitted to the commission must include a statement of whether the railroad has the ability to pay for damages resulting from a reasonable worst case spill of oil, as calculated by multiplying the reasonable per barrel cleanup and damage cost of spilled oil times the reasonable worst case spill volume as measured in barrels. A railroad company must include the information in the annual report submitted to the commission pursuant to RCW 81.04.080.

. The commission may not use the information submitted by a railroad company under this section as a basis for engaging in economic regulation of a railroad company.

. The commission may not use the information submitted by a railroad company under this section as a basis for penalizing a railroad company.

. Nothing in this section may be construed as assigning liability to a railroad company or establishing liquidated damages for a spill or accident involving the transport of crude oil by a railroad company.

. The commission may adopt rules for implementing this section consistent with the requirements of RCW 81.04.080.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1449-S.SL.pdf?cite=2015%20c%20274%20§%2010[2015 c 274 § 10]; ]

