= 81.108 - Low-level radioactive waste sites.
:toc:

== 81.108.010 - Purpose.
State and national policy directs that the management of low-level radioactive waste be accomplished by a system of interstate compacts and the development of regional disposal sites. The Northwest regional compact, comprised of the states of Alaska, Hawaii, Idaho, Montana, Oregon, Utah, and Washington, has as its disposal facility the low-level radioactive waste disposal site located near Richland, Washington. This site is expected to be the sole site for disposal of low-level radioactive waste for compact members effective January 1, 1993. Future closure of this site will require significant financial resources.

Low-level radioactive waste is generated by essential activities and services that benefit the citizens of the state. Washington state's low-level radioactive waste disposal site has been used by the nation and the Northwest compact as a disposal site since 1965. The public has come to rely on access to this site for disposal of low-level radioactive waste, which requires separate handling from other solid and hazardous wastes. The price of disposing of low-level radioactive waste at the Washington state low-level radioactive waste disposal site is anticipated to increase when the federal low-level radioactive waste policy amendments act of 1985 is implemented and waste generated outside the Northwest compact states is excluded.

When these events occur, to protect Washington and other Northwest compact states' businesses and services, such as electrical production, medical and university research, and private industries, upon which the public relies, there will be a need to regulate the rates charged by the operator of Washington's low-level radioactive waste disposal site. This chapter is adopted pursuant to section 8, chapter 21, Laws of 1990.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5756-S.SL.pdf?cite=1991%20c%20272%20§%201[1991 c 272 § 1]; ]

== 81.108.020 - Definitions.
Definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Commission" means the Washington utilities and transportation commission.

. "Effective rate" means the highest permissible rate, calculated as the lowest contract rate plus an administrative fee, if applicable, determined pursuant to RCW 81.108.040.

. "Extraordinary volume" means volumes of low-level radioactive waste delivered to a site caused by nonrecurring events, outside normal operations of a generator, that are in excess of twenty thousand cubic feet or twenty percent of the preceding year's total volume at such site, whichever is less.

. "Extraordinary volume adjustment" means a mechanism that allocates the potential rate reduction benefits of an extraordinary volume between all generators and the generator responsible for such extraordinary volume as described in RCW 81.108.070.

. "Generator" means a person, partnership, association, corporation, or any other entity whatsoever that, as a part of its activities, produces low-level radioactive waste.

. "Inflation adjustment" means a mechanism that adjusts the maximum disposal rate by a percentage equal to the change in price levels in the preceding period, as measured by a common, verifiable price index as determined in RCW 81.108.040.

. "Initial rate proceeding" means the proceeding described in RCW 81.108.040.

. "Maximum disposal rate" means the rate described in RCW 81.108.050.

. "Site" means a location, structure, or property used or to be used for the storage, treatment, or disposal of low-level radioactive waste for compensation within the state of Washington.

. "Site operator" means a low-level radioactive waste site operating company as defined in RCW 81.04.010.

. "Volume adjustment" means a mechanism that adjusts the maximum disposal rate in response to material changes in volumes of waste deposited at the site during the preceding period so as to provide a level of total revenues sufficient to recover the costs to operate and maintain the site.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5756-S.SL.pdf?cite=1991%20c%20272%20§%202[1991 c 272 § 2]; ]

== 81.108.030 - Commission—Powers.
. The commission shall have jurisdiction over the sites and site operators as set forth in this chapter.

. [Empty]
.. The commission shall establish rates to be charged by site operators. In establishing the rates, the commission shall assure that they are fair, just, reasonable, and sufficient considering the value of the site operator's leasehold and license interests, the unique nature of its business operations, the site operator's liability associated with the site, its investment incurred over the term of its operations, and the rate of return equivalent to that earned by comparable enterprises. The rates shall only take effect following a finding that the site operator is a monopoly pursuant to RCW 81.108.100.

.. In exercising the power in this subsection the commission may use any standard, formula, method, or theory of valuation reasonably calculated to arrive at the objective of prescribing and authorizing fair, just, reasonable, and sufficient rates. The relation of site operator expenses to site operator revenues may be deemed the proper test of a reasonable return.

. In all respects in which the commission has power and authority under this chapter, applications and complaints may be made and filed with it, process issued, hearings held, opinions, orders, and decisions made and filed, petitions for rehearing filed and acted upon, and petitions for review to the superior court filed therewith, appeals filed with the appellate courts of this state, considered and disposed of by said courts in the manner, under the conditions, and subject to the limitations, and with the effect specified in this title for public service companies generally.

. At any time after January 1, 1992, the commission may: (a) Prescribe a system of accounts for site operators using as a starting point the existing system used by site operators; (b) audit the books of site operators; (c) obtain books and records from site operators; (d) assess penalties; and (e) require semiannual reports regarding the results of operations for the site.

. The commission may adopt rules necessary to carry out its functions under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5756-S.SL.pdf?cite=1991%20c%20272%20§%204[1991 c 272 § 4]; ]

== 81.108.040 - Rates—Initial determination—Fees.
. On or before March 1, 1992, site operators shall file a request with the commission to establish an initial maximum disposal rate. The filing shall include, at a minimum, testimony, exhibits, workpapers, summaries, annual reports, cost studies, proposed tariffs, and other documents as required by the commission in rate cases generally under its jurisdiction.

. After receipt of a request, the commission shall set the request for a hearing and require the site operator to provide for notice to all known customers that ship or deliver waste to the site. The proceedings before the commission shall be conducted in accordance with chapter 34.05 RCW and rules of procedure established by the commission.

. No later than January 1, 1993, the commission shall establish the initial maximum disposal rates that may be charged by site operators.

. In the initial rate proceeding the commission also shall determine the factors necessary to calculate the inflation, volume, and extraordinary volume adjustments.

. The commission also shall determine the administrative fee, which shall be a percentage or an amount that represents increased administrative costs associated with acceptance of small volumes of waste by a site operator. The administrative fee may be revised by the commission from time to time upon its own motion or upon the petition of an interested person.

. The rates specified in this section shall only take effect following a finding that the site operator is a monopoly pursuant to RCW 81.108.100.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5756-S.SL.pdf?cite=1991%20c%20272%20§%205[1991 c 272 § 5]; ]

== 81.108.050 - Maximum rates—Revisions—Waiver of provisions during state of emergency.
. The maximum disposal rates that a site operator may charge generators shall be determined in accordance with this section. The rates shall include all charges for disposal services at the site.

. Initially, the maximum disposal rates shall be the initial rates established pursuant to RCW 81.108.040.

. Subsequently, the maximum disposal rates shall be adjusted in January of each year to incorporate inflation and volume adjustments. Such adjustments shall take effect thirty days after filing with the commission unless the commission authorizes that the adjustments take effect earlier, or the commission contests the calculation of the adjustments, in which case the commission may suspend the filing. A site operator shall provide notice to its customers concurrent with the filing.

. [Empty]
.. Subsequently, a site operator may also file for revisions to the maximum disposal rates due to:

... Changes in any governmentally imposed fee, surcharge, or tax assessed on a volume or a gross revenue basis against or collected by the site operator, including site closure fees, perpetual care and maintenance fees, business and occupation taxes, site surveillance fees, leasehold excise taxes, commission regulatory fees, municipal taxes, and a tax or payment in lieu of taxes authorized by the state to compensate the county in which a site is located for that county's legitimate costs arising out of the presence of that site within that county; or

... Factors outside the control of the site operator such as a material change in regulatory requirements regarding the physical operation of the site.

.. Revisions to the maximum disposal rate shall take effect thirty days after filing with the commission unless the commission suspends the filing or authorizes the proposed adjustments to take effect earlier.

. Upon establishment of a contract rate pursuant to RCW 81.108.060 for a disposal fee, the site operator may not collect a disposal fee that is greater than the effective rate. The effective rate shall be in effect so long as such contract rate remains in effect. Adjustments to the maximum disposal rates may be made during the time an effective rate is in place. Contracts for disposal of extraordinary volumes pursuant to RCW 81.108.070 shall not be considered in determining the effective rate.

. The site operator may petition the commission for new maximum disposal rates at any time. Upon receipt of such a petition, the commission shall set the matter for hearing and shall issue an order within seven months of the filing of the petition. The petition shall be accompanied by the documents required to accompany the filing for initial rates. The hearing on the petition shall be conducted in accordance with the commission's rules of practice and procedure.

. This section shall only take effect following a finding that the site operator is a monopoly pursuant to RCW 81.108.100.

. During a state of emergency declared under RCW 43.06.010(12), the governor may waive or suspend the operation or enforcement of this section or any portion of this section or under any administrative rule, and issue any orders to facilitate the operation of state or local government or to promote and secure the safety and protection of the civilian population.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6950.SL.pdf?cite=2008%20c%20181%20§%20411[2008 c 181 § 411]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1609.SL.pdf?cite=1997%20c%20243%20§%201[1997 c 243 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5756-S.SL.pdf?cite=1991%20c%20272%20§%206[1991 c 272 § 6]; ]

== 81.108.060 - Contracted disposal rates—Waiver of provisions during state of emergency.
. At any time, a site operator may contract with any person to provide a contract disposal rate lower than the maximum disposal rate.

. A contract or contract amendment shall be submitted to the commission for approval at least thirty days before its effective date. The commission may approve the contract or suspend the contract and set it for hearing. If the commission takes no action within thirty days of filing, the contract or amendment shall go into effect according to its terms. Each contract filing shall be accompanied with documentation to show that the contract does not result in discrimination between generators receiving like and contemporaneous service under substantially similar circumstances and provides for the recovery of all costs associated with the provision of the service.

. This section shall only take effect following a finding that the site operator is a monopoly pursuant to RCW 81.108.100.

. During a state of emergency declared under RCW 43.06.010(12), the governor may waive or suspend the operation or enforcement of this section or any portion of this section or under any administrative rule, and issue any orders to facilitate the operation of state or local government or to promote and secure the safety and protection of the civilian population.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6950.SL.pdf?cite=2008%20c%20181%20§%20412[2008 c 181 § 412]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5756-S.SL.pdf?cite=1991%20c%20272%20§%207[1991 c 272 § 7]; ]

== 81.108.070 - Extraordinary volume adjustment.
. In establishing the extraordinary volume adjustment, unless the site operator and generator of the extraordinary volume agree to a contract disposal rate, one-half of the extraordinary volume delivery shall be priced at the maximum disposal rate and one-half shall be priced at the site operator's incremental cost to receive the delivery. Such incremental cost shall be determined in the initial rate proceeding.

. For purposes of the subsequent calculation of the volume adjustment, one-half of the total extraordinary volume shall be included in the calculation.

. This section shall only take effect following a finding that the site operator is a monopoly pursuant to RCW 81.108.100.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5756-S.SL.pdf?cite=1991%20c%20272%20§%208[1991 c 272 § 8]; ]

== 81.108.080 - Complaint—Hearing.
. At any time, the commission or an interested person may file a complaint against a site operator alleging that the rates established pursuant to RCW 81.108.040 or 81.108.050 are not in conformity with the standards set forth in RCW 81.108.030 or that the site operator is otherwise not acting in conformity with the requirements of this chapter. Upon filing of the complaint, the commission shall cause a copy of the complaint to be served upon the site operator. The complaining party shall have the burden of proving that the maximum disposal rates determined pursuant to RCW 81.108.050 are not just, fair, reasonable, or sufficient. The hearing shall conform to the rules of practice and procedure of the commission for other complaint cases.

. The commission shall encourage alternate forms of dispute resolution to resolve disputes between a site operator and any other person regarding matters covered by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5756-S.SL.pdf?cite=1991%20c%20272%20§%209[1991 c 272 § 9]; ]

== 81.108.090 - Revenue statement—Fees—Delinquent fee payments.
. A site operator shall, on or before May 1, 1992, and each year thereafter, file with the commission a statement showing its gross operating revenue from intrastate operations for the preceding calendar year, or portion thereof, and pay to the commission a fee equal to one percent of the amount of the gross operating revenue, exclusive of site surveillance fees, perpetual care and maintenance fees, site closure fees, and state or federally imposed out-of-region surcharges.

. Fees collected under this chapter shall reasonably approximate the cost of supervising and regulating site operators. The commission may order a decrease in fees by March 1st of any year in which it determines that the moneys then in the radioactive waste disposal companies account of the public service revolving fund and the fees currently to be paid will exceed the reasonable cost of supervising and regulating site operators.

. Fees collected under this section or under any other provision of this chapter shall be paid to the commission and shall be transmitted to the state treasurer within thirty days to be deposited to the credit of the public service revolving fund.

. Any payment of a fee imposed by this chapter made after its due date shall include a late fee of two percent of the amount due. Delinquent fees shall accrue interest at the rate of one percent per month.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2338.SL.pdf?cite=1994%20c%2083%20§%205[1994 c 83 § 5]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5756-S.SL.pdf?cite=1991%20c%20272%20§%2010[1991 c 272 § 10]; ]

== 81.108.100 - Exemptions—Monopolies—Hearings—Rates.
. A low-level waste disposal site operator is exempt as specified in RCW 81.108.030(2)(a), 81.108.040(6), 81.108.050(7), 81.108.060(3), and 81.108.070(3) unless a monopoly situation exists with respect to the site operated by such site operator. A monopoly situation exists if either of the following is present:

.. No disposal facility is available to Northwest compact generators of low-level radioactive waste other than the site or sites operated by such site operator or its affiliates; or

.. Disposal rates at other sites are not reasonable alternatives for Northwest compact generators, considering: Disposal rates at other facilities; current disposal rates charged by the site operator; historic relationships between the site operator's rates and rates at other facilities; and changes in the operator's rates considering changes in waste volumes, taxes, and fees. A monopoly situation does not exist if either of the following facilities operates or is projected to operate after December 31, 1992:

... Any existing low-level radioactive waste disposal site outside the state of Washington, other than facilities operated by affiliates of a site operator, provided that such site or sites do not charge disposal rates that discriminate against Northwest compact generators, except to the extent, through December 31, 1994, such discrimination is authorized by amendment of current federal law.

... An existing facility within the Northwest compact not receiving low-level radioactive waste offers to receive such waste under substantially similar terms and conditions.

. The exemption shall be in effect until such time as the commission finds, after notice and hearing, upon motion by the commission or upon petition by any interested party, that a monopoly situation exists or will exist as of January 1, 1993. The finding shall be based upon application of the criteria set forth in this section. The commission may assess a site operator for all of the commission's costs of supervision and regulation prior to and relative to determining whether the exemption applies to the site operator. If the commission determines that a site operator is not subject to the exemption, it shall collect its costs of supervision and regulation under RCW 81.108.090.

. When an exemption is in effect, any increase in the rates charged by the operator effective January 1, 1993, for services other than the base rate for disposal of solid material in packages of twelve cubic feet or less shall be no more than the percentage increase in the base rate in effect on January 1, 1993.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5756-S.SL.pdf?cite=1991%20c%20272%20§%2011[1991 c 272 § 11]; ]

== 81.108.110 - Competitive companies—Exemptions—Waiver of provisions during state of emergency.
. At any time after this chapter has been implemented with respect to a site operator, such site operator may petition the commission to be classified as competitive. The commission may initiate classification proceedings on its own motion. The commission shall enter its final order with respect to classification within seven months from the date of filing of a company's petition or the commission's motion.

. The commission shall classify a site operator as a competitive company if the commission finds, after notice and hearing, that the disposal services offered are subject to competition because the company's customers have reasonably available alternatives. In determining whether a company is competitive, the commission's consideration shall include, but not be limited to:

.. Whether the system of interstate compacts and regional disposal sites established by federal law has been implemented so that the Northwest compact site located near Richland, Washington is the exclusive site option for disposal by customers within the Northwest compact states;

.. Whether waste generated outside the Northwest compact states is excluded; and

.. The ability of alternative disposal sites to make functionally equivalent services readily available at competitive rates, terms, and conditions.

. The commission may reclassify a competitive site operator if reclassification would protect the public interest as set forth in this section.

. Competitive low-level radioactive waste disposal companies shall be exempt from commission regulation and fees during the time they are so classified.

. During a state of emergency declared under RCW 43.06.010(12), the governor may waive or suspend the operation or enforcement of this section or any portion of this section or under any administrative rule, and issue any orders to facilitate the operation of state or local government or to promote and secure the safety and protection of the civilian population.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6950.SL.pdf?cite=2008%20c%20181%20§%20413[2008 c 181 § 413]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5756-S.SL.pdf?cite=1991%20c%20272%20§%2012[1991 c 272 § 12]; ]

== 81.108.900 - Construction.
Nothing in this chapter shall be construed to affect the jurisdiction of another state agency.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5756-S.SL.pdf?cite=1991%20c%20272%20§%2013[1991 c 272 § 13]; ]

== 81.108.901 - Effective dates—1991 c 272.
. Sections 1 through 15 and 22 of this act are necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions. Sections 1 through 14 and 22 of this act shall take effect July 1, 1991, and section 15 of this act shall take effect immediately [May 20, 1991].

. Sections 16 through 21 and 23 of this act shall take effect January 1, 1993.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5756-S.SL.pdf?cite=1991%20c%20272%20§%2024[1991 c 272 § 24]; ]

