= 81.116 - Marine pilotage tariffs.
:toc:

== 81.116.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Board" means the board of pilotage commissioners.

. "Commission" means the utilities and transportation commission.

. "Person with a substantial interest" means: (a) A pilot or group of pilots licensed under chapter 88.16 RCW; (b) a vessel operator or other person utilizing the services of a licensed pilot and paying pilotage fees and charges for such services or an organization representing such vessel operators or persons; and (c) any other person or business that can show that the requested tariff changes would be likely to have a substantial economic impact on its operations.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6519-S.SL.pdf?cite=2018%20c%20107%20§%207[2018 c 107 § 7]; ]

== 81.116.020 - Pilotage services—Tariffs—Commission shall establish—Duties.
. The commission shall establish in tariffs the rates for pilotage services provided under chapter 88.16 RCW.

. The commission shall maintain a list of persons who have indicated to the commission a desire to be notified of any potential change in pilotage tariffs and in any proposed rules regarding the setting of pilotage tariffs.

. The commission shall ensure that the tariffs provide rates that are fair, just, reasonable, and sufficient for the provision of pilotage services.

. In setting tariffs, the commission may fix extra compensation for extra services to vessels in distress, for awaiting vessels, for all vessels in direct transit to or from a Canadian port where Puget Sound pilotage is required for a portion of the voyage, or for being carried to sea on vessels against the will of the pilot, and for such other services as may be determined by the board. In setting tariffs, the commission must include a tariff surcharge to fund the stipend the board of pilotage commissioners is authorized to pay to pilot trainees and to use in its pilot training program under RCW 88.16.035. As an element of the Puget Sound pilotage district tariff, the commission may consider pilot retirement expenses incurred in the prior year in the Puget Sound pilotage district. However, under no circumstances shall the state be obligated to fund or pay for any portion of retirement payments for pilots or retired pilots.

. In exercising duties under this section, the commission may:

.. Request assistance from the board;

.. Assign an administrative law judge to handle the proceeding and prepare an initial order, which the commission may review pursuant to RCW 34.05.464, or assign an administrative law judge as a facilitator for settlement purposes; and

.. Adopt rules or issue orders to implement the provisions of chapter 107, Laws of 2018.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6519-S.SL.pdf?cite=2018%20c%20107%20§%208[2018 c 107 § 8]; ]

== 81.116.030 - Filing of revised tariff—Requirements—Notice of petition—Effective date—Burden of proof.
. Any person with a substantial interest may file with the commission a revised tariff with an effective date no earlier than thirty days from the date of filing and no earlier than one year following the effective date the tariffs in effect at the time of filing were established.

. The proposed tariff must be accompanied by:

.. The names and contact information of the person or persons requesting the tariff revision;

.. A description of why the existing tariffs are not fair, just, reasonable, and sufficient, along with financial information to demonstrate a need for the tariff revision and information addressing the criteria for approval of tariff revisions set forth in RCW 81.116.020(3);

.. If the petitioner proposes a tariff with an annual or periodic adjustment mechanism, information justifying such a mechanism; and

.. Any other information required by the commission by rule or by order.

. After receipt of a proper petition, the commission shall give notice of the petition to interested persons that have stated a desire to be notified pursuant to RCW 81.116.020(2). Any person with a substantial interest in the proposed tariff revision may submit comments in support or opposition of the petition within twenty days of the notice.

. The filed tariff shall take effect on its stated effective date unless, within thirty days of filing of the tariff, the commission suspends it. The commission may suspend the tariff for a period not exceeding ten months from the time the change would otherwise go into effect. During that time, the commission may set the matter for a hearing pursuant to chapter 34.05 RCW or set the matter for consideration at a subsequent open public meeting.

. The burden of proof to show that the tariff rates are not fair, just, reasonable, and sufficient is upon the person with a substantial interest that files the revised tariff.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6519-S.SL.pdf?cite=2018%20c%20107%20§%209[2018 c 107 § 9]; ]

== 81.116.040 - Dispute resolution.
The commission shall encourage alternative forms of dispute resolution to resolve disputes between an association or group of pilots and any other person regarding matters covered by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6519-S.SL.pdf?cite=2018%20c%20107%20§%2010[2018 c 107 § 10]; ]

== 81.116.050 - Tariffs established shall remain in effect.
The tariffs established by the board prior to July 1, 2019, shall remain in effect and be deemed pilotage tariffs set by the commission until such time as they are changed by the commission pursuant to this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6519-S.SL.pdf?cite=2018%20c%20107%20§%2011[2018 c 107 § 11]; ]

== 81.116.060 - Costs for setting of tariff rates.
The commission may include as part of the tariff for pilotage services provided under chapter 88.16 RCW reasonable costs for the setting of tariff rates under this chapter. The costs of the commission included as part of the tariff must be appropriated from the pilotage account in RCW 88.16.061.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6519-S.SL.pdf?cite=2018%20c%20107%20§%2012[2018 c 107 § 12]; ]

== 81.116.900 - Implementation—2018 c 107.
To ensure that this act is implemented in a timely manner, the utilities and transportation commission may adopt rules under RCW 81.116.020 prior to July 1, 2019, and may accept tariff filings from a person with a substantial interest beginning thirty days after the effective date of these adopted rules. The utilities and transportation commission must suspend a tariff filing made before July 1, 2019, within thirty days of receipt of the filing. Any tariff filings made under this section may not take effect until after June 30, 2019.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6519-S.SL.pdf?cite=2018%20c%20107%20§%2015[2018 c 107 § 15]; ]

