= 6.01 - General provisions.
:toc:

== 6.01.010 - Application of chapters in Title 6 RCW to superior courts and district courts—Definitions.
Except as otherwise expressly provided, the provisions of this chapter and of chapters 6.13, 6.15, 6.17, 6.19, 6.21, 6.25, 6.26, and 6.27 RCW and chapter 6.32 RCW apply to both the superior courts and district courts of this state. If proceedings are before a district court, acts to be performed by the clerk may be performed by a district court judge if there is no clerk. As used in this title, "sheriff" includes deputies, and "execution docket" refers also to the docket of a district court.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c442.pdf?cite=1987%20c%20442%20§%20101[1987 c 442 § 101]; ]

== 6.01.020 - Entry of judgment—Superior court—District court—Small claims.
For purposes of this title and RCW 4.56.190 and 4.56.210, a judgment of a superior court is entered when it is delivered to the clerk's office for filing. A judgment of a district court of this state is entered on the date of the entry of the judgment in the docket of the court. A judgment of a small claims department of a district court of this state is entered on the date of the entry in the docket of that department.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c442.pdf?cite=1987%20c%20442%20§%20102[1987 c 442 § 102]; ]

== 6.01.030 - Direction of writ when sheriff a party.
If the sheriff is a party or otherwise interested in an action in which a writ of execution, attachment, or replevin is to be served, the writ shall be directed to the coroner of the county, or the officer exercising the powers and performing the duties of coroner if there is no coroner, and the person to whom the writ is thus directed shall perform the duties of the sheriff.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c442.pdf?cite=1987%20c%20442%20§%20103[1987 c 442 § 103]; ]

== 6.01.040 - Execution against several persons—Contribution—Repayment.
. When property liable to an execution against several persons is sold on execution, if more than a due proportion of the judgment is levied upon the property of one person, or one of them pays without a sale more than his or her due proportion, that person may compel contribution from the others. When a judgment against several persons is upon an obligation or contract of one of them as security for another, if the surety pays the full amount or any part of the judgment, either by sale of the surety's property or before sale, the surety may compel repayment from the principal.

. In either case covered by subsection (1) of this section, the person or surety so paying shall be entitled to the benefit of the judgment to enforce contribution or repayment, if within thirty days after the payment, notice of the payment and claim to contribution or repayment is filed with the clerk of the court where the judgment was rendered.

. Upon filing such notice, the clerk shall make an entry thereof in the docket where the judgment is entered.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c442.pdf?cite=1987%20c%20442%20§%20104[1987 c 442 § 104]; ]

== 6.01.050 - Writ of attachment or execution against debtor in bankruptcy.
If, before levying under a writ of attachment or execution, a sheriff receives notice that the defendant has become a debtor in a bankruptcy case, the sheriff shall immediately give written notice of that fact to the plaintiff's attorney of record, if any, otherwise to the plaintiff, and shall not be bound to levy under the writ. If, after levying on property under a writ of attachment or execution, a sheriff receives such notice, the sheriff shall give written notice of the attachment or execution, describing the property seized, to the trustee in the bankruptcy case if there is one, otherwise to the bankruptcy court, with a copy to the plaintiff's attorney of record, if any, otherwise to the plaintiff, and shall transfer the property to the trustee on demand or as the bankruptcy court otherwise directs. If no demand is made on the sheriff for surrender of the property and the sheriff thereafter receives notice of the closing of the bankruptcy case, the sheriff shall give written notice by first-class mail to the plaintiff's attorney of record, if any, otherwise to the plaintiff, requiring that the plaintiff release the property or obtain a renewal of the writ from the court, and, if the plaintiff fails to release the property or to apply for a renewal within fourteen days after the mailing of the sheriff's notice, the sheriff shall release the property to the defendant.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c231.pdf?cite=1988%20c%20231%20§%202[1988 c 231 § 2]; ]

== 6.01.060 - Definitions.
The definitions in this section apply throughout this title unless the context clearly requires otherwise.

. "Certified mail" includes, for mailings to a foreign country, any form of mail that requires or permits a return receipt.

. "Consumer debt" means any obligation or alleged obligation of a consumer to pay money arising out of a transaction in which the money, property, insurance, or services which are the subject of the transaction are primarily for personal, family, or household purposes. Consumer debt includes medical debt.

. "Medical debt" has the same meaning as provided in RCW 19.16.100.

. "Private student loan" means any loan not guaranteed by the federal or state government that is used solely for personal use to finance postsecondary education and costs of attendance at an educational institution. A private student loan includes a loan made solely to refinance a private student loan. A private student loan does not include an extension of credit made under an open-end consumer credit plan, a reverse mortgage transaction, a residential mortgage transaction, or any other loan that is secured by real property or a dwelling.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1602-S.SL.pdf?cite=2019%20c%20371%20§%202[2019 c 371 § 2]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1531-S.SL.pdf?cite=2019%20c%20227%20§%201[2019 c 227 § 1]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1169-S3.SL.pdf?cite=2018%20c%20199%20§%20202[2018 c 199 § 202]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c231.pdf?cite=1988%20c%20231%20§%201[1988 c 231 § 1]; ]

