= 6.15 - Personal property exemptions.
:toc:

== 6.15.010 - Exempt property.
. Except as provided in RCW 6.15.050, the following personal property is exempt from execution, attachment, and garnishment:

.. All wearing apparel of every individual and family, but not to exceed three thousand five hundred dollars in value in furs, jewelry, and personal ornaments for any individual.

.. All private libraries including electronic media, which includes audiovisual, entertainment, or reference media in digital or analogue format, of every individual, but not to exceed three thousand five hundred dollars in value, and all family pictures and keepsakes.

.. A cell phone, personal computer, and printer.

.. To each individual or, as to community property of spouses maintaining a single household as against a creditor of the community, to the community:

... The individual's or community's household goods, appliances, furniture, and home and yard equipment, not to exceed six thousand five hundred dollars in value for the individual or thirteen thousand dollars for the community, no single item to exceed seven hundred fifty dollars, said amount to include provisions and fuel for the comfortable maintenance of the individual or community;

... Other personal property, except personal earnings as provided under RCW 6.15.050(1), not to exceed three thousand dollars in value, of which not more than one thousand five hundred dollars in value may consist of cash, and of which not more than:

(A) For all debts except private student loan debt and consumer debt, five hundred dollars in value may consist of bank accounts, savings and loan accounts, stocks, bonds, or other securities. The maximum exemption under this subsection (1)(d)(ii)(A) may not exceed five hundred dollars, regardless of the number of existing separate bank accounts, savings and loan accounts, stocks, bonds, or other securities.

(B) For all private student loan debt, two thousand five hundred dollars in value may consist of bank accounts, savings and loan accounts, stocks, bonds, or other securities. The maximum exemption under this subsection (1)(d)(ii)(B) may not exceed two thousand five hundred dollars, regardless of the number of existing separate bank accounts, savings and loan accounts, stocks, bonds, or other securities.

(C) For all consumer debt, two thousand dollars in value may consist of bank accounts, savings and loan accounts, stocks, bonds, or other securities. The maximum exemption under this subsection (1)(d)(ii)(C) may not exceed two thousand dollars, regardless of the number of existing separate bank accounts, savings and loan accounts, stocks, bonds, or other securities;

... For an individual, a motor vehicle used for personal transportation, not to exceed three thousand two hundred fifty dollars or for a community two motor vehicles used for personal transportation, not to exceed six thousand five hundred dollars in aggregate value;

... Any past due, current, or future child support paid or owed to the debtor, which can be traced;

.. All professionally prescribed health aids for the debtor or a dependent of the debtor; and

.. To any individual, the right to or proceeds of a payment not to exceed twenty thousand dollars on account of personal bodily injury, not including pain and suffering or compensation for actual pecuniary loss, of the debtor or an individual of whom the debtor is a dependent; or the right to or proceeds of a payment in compensation of loss of future earnings of the debtor or an individual of whom the debtor is or was a dependent, to the extent reasonably necessary for the support of the debtor and any dependent of the debtor. The exemption under this subsection (1)(d)(vi) does not apply to the right of the state of Washington, or any agent or assignee of the state, as a lienholder or subrogee under RCW 43.20B.060.

.. To each qualified individual, one of the following exemptions:

... To a farmer, farm trucks, farm stock, farm tools, farm equipment, supplies and seed, not to exceed ten thousand dollars in value;

... To a physician, surgeon, attorney, member of the clergy, or other professional person, the individual's library, office furniture, office equipment and supplies, not to exceed ten thousand dollars in value;

... To any other individual, the tools and instruments and materials used to carry on his or her trade for the support of himself or herself or family, not to exceed ten thousand dollars in value.

.. Tuition units, under chapter 28B.95 RCW, purchased more than two years prior to the date of a bankruptcy filing or court judgment, and contributions to any other qualified tuition program under 26 U.S.C. Sec. 529 of the internal revenue code of 1986, as amended, and to a Coverdell education savings account, also known as an education individual retirement account, under 26 U.S.C. Sec. 530 of the internal revenue code of 1986, as amended, contributed more than two years prior to the date of a bankruptcy filing or court judgment.

. For purposes of this section, "value" means the reasonable market value of the debtor's interest in an article or item at the time it is selected for exemption, exclusive of all liens and encumbrances thereon.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1602-S.SL.pdf?cite=2019%20c%20371%20§%203[2019 c 371 § 3]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1169-S3.SL.pdf?cite=2018%20c%20199%20§%20203[2018 c 199 § 203]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%202[2012 c 117 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1864-S.SL.pdf?cite=2011%20c%20162%20§%202[2011 c 162 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5926.SL.pdf?cite=2005%20c%20272%20§%206[2005 c 272 § 6]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6266.SL.pdf?cite=2002%20c%20265%20§%201[2002 c 265 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1059-S.SL.pdf?cite=1991%20c%20112%20§%201[1991 c 112 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c231.pdf?cite=1988%20c%20231%20§%205[1988 c 231 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c442.pdf?cite=1987%20c%20442%20§%20301[1987 c 442 § 301]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c45.pdf?cite=1983%201st%20ex.s.%20c%2045%20§%208[1983 1st ex.s. c 45 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c65.pdf?cite=1979%20ex.s.%20c%2065%20§%201[1979 ex.s. c 65 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c154.pdf?cite=1973%201st%20ex.s.%20c%20154%20§%2013[1973 1st ex.s. c 154 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c89.pdf?cite=1965%20c%2089%20§%201[1965 c 89 § 1]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1886%20p%2096%20§%201[1886 p 96 § 1]; Code 1881 § 347; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1879%20p%20157%20§%201[1879 p 157 § 1]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2073%20§%20351[1877 p 73 § 351]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2087%20§%20343[1869 p 87 § 343]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20178%20§%20253[1854 p 178 § 253]; RRS § 563; ]

== 6.15.020 - Pension money exempt—Exceptions—Transfer of spouse's interest in employee benefit plan.
. It is the policy of the state of Washington to ensure the well-being of its citizens by protecting retirement income to which they are or may become entitled. For that purpose generally and pursuant to the authority granted to the state of Washington under 11 U.S.C. Sec. 522(b)(2), the exemptions in this section relating to retirement benefits are provided.

. Unless otherwise provided by federal law, any money received by any citizen of the state of Washington as a pension from the government of the United States, whether the same be in the actual possession of such person or be deposited or loaned, shall be exempt from execution, attachment, garnishment, or seizure by or under any legal process whatever, and when a debtor dies, or absconds, and leaves his or her family any money exempted by this subsection, the same shall be exempt to the family as provided in this subsection. This subsection shall not apply to child support collection actions issued under chapter 26.18, 26.23, or 74.20A RCW, if otherwise permitted by federal law.

. The right of a person to a pension, annuity, or retirement allowance or disability allowance, or death benefits, or any optional benefit, or any other right accrued or accruing to any citizen of the state of Washington under any employee benefit plan, and any fund created by such a plan or arrangement, shall be exempt from execution, attachment, garnishment, or seizure by or under any legal process whatever. This subsection shall not apply to child support collection actions issued under chapter 26.18, 26.23, or 74.20A RCW if otherwise permitted by federal law. This subsection shall permit benefits under any such plan or arrangement to be payable to a spouse, former spouse, child, or other dependent of a participant in such plan to the extent expressly provided for in a qualified domestic relations order that meets the requirements for such orders under the plan, or, in the case of benefits payable under a plan described in 26 U.S.C. Sec. 403(b) or 408 of the internal revenue code of 1986, as amended, or section 409 of such code as in effect before January 1, 1984, to the extent provided in any order issued by a court of competent jurisdiction that provides for maintenance or support. This subsection does not prohibit actions against an employee benefit plan, or fund for valid obligations incurred by the plan or fund for the benefit of the plan or fund.

. For the purposes of this section, the term "employee benefit plan" means any plan or arrangement that is described in RCW 49.64.020, including any Keogh plan, whether funded by a trust or by an annuity contract, and in 26 U.S.C. Sec. 401(a) or 403(a) of the internal revenue code of 1986, as amended; or that is a tax-sheltered annuity or a custodial account described in section 403(b) of such code or an individual retirement account or an individual retirement annuity described in section 408 of such code; or a Roth individual retirement account described in section 408A of such code; or a medical savings account or a health savings account described in sections 220 and 223, respectively, of such code; or a retirement bond described in section 409 of such code as in effect before January 1, 1984. The term "employee benefit plan" shall not include any employee benefit plan that is established or maintained for its employees by the government of the United States, by the state of Washington under chapter 2.10, 2.12, 41.26, 41.32, 41.34, 41.35, 41.37, 41.40, or 43.43 RCW or RCW 41.50.770, or by any agency or instrumentality of the government of the United States.

. An employee benefit plan shall be deemed to be a spendthrift trust, regardless of the source of funds, the relationship between the trustee or custodian of the plan and the beneficiary, or the ability of the debtor to withdraw or borrow or otherwise become entitled to benefits from the plan before retirement. This subsection shall not apply to child support collection actions issued under chapter 26.18, 26.23, or 74.20A RCW, if otherwise permitted by federal law. This subsection shall permit benefits under any such plan or arrangement to be payable to a spouse, former spouse, child, or other dependent of a participant in such plan to the extent expressly provided for in a qualified domestic relations order that meets the requirements for such orders under the plan, or, in the case of benefits payable under a plan described in 26 U.S.C. Sec. 403(b) or 408 of the internal revenue code of 1986, as amended, or section 409 of such code as in effect before January 1, 1984, to the extent provided in any order issued by a court of competent jurisdiction that provides for maintenance or support.

. Unless prohibited by federal law, nothing contained in subsection (3), (4), or (5) of this section shall be construed as a termination or limitation of a spouse's community property interest in an employee benefit plan held in the name of or on account of the other spouse, who is the participant or the account holder spouse. Unless prohibited by applicable federal law, at the death of the nonparticipant, nonaccount holder spouse, the nonparticipant, nonaccount holder spouse may transfer or distribute the community property interest of the nonparticipant, nonaccount holder spouse in the participant or account holder spouse's employee benefit plan to the nonparticipant, nonaccount holder spouse's estate, testamentary trust, inter vivos trust, or other successor or successors pursuant to the last will of the nonparticipant, nonaccount holder spouse or the law of intestate succession, and that distributee may, but shall not be required to, obtain an order of a court of competent jurisdiction, including a nonjudicial binding agreement or order entered under chapter 11.96A RCW, to confirm the distribution. For purposes of subsection (3) of this section, the distributee of the nonparticipant, nonaccount holder spouse's community property interest in an employee benefit plan shall be considered a person entitled to the full protection of subsection (3) of this section. The nonparticipant, nonaccount holder spouse's consent to a beneficiary designation by the participant or account holder spouse with respect to an employee benefit plan shall not, absent clear and convincing evidence to the contrary, be deemed a release, gift, relinquishment, termination, limitation, or transfer of the nonparticipant, nonaccount holder spouse's community property interest in an employee benefit plan. For purposes of this subsection, the term "nonparticipant, nonaccount holder spouse" means the spouse of the person who is a participant in an employee benefit plan or in whose name an individual retirement account is maintained. As used in this subsection, an order of a court of competent jurisdiction entered under chapter 11.96A RCW includes an agreement, as that term is used under RCW 11.96A.220.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1864-S.SL.pdf?cite=2011%20c%20162%20§%203[2011 c 162 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5174-S.SL.pdf?cite=2007%20c%20492%20§%201[2007 c 492 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5195-S.SL.pdf?cite=1999%20c%2081%20§%201[1999 c 81 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5196.SL.pdf?cite=1999%20c%2042%20§%20603[1999 c 42 § 603]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5108.SL.pdf?cite=1997%20c%2020%20§%201[1997 c 20 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c237.pdf?cite=1990%20c%20237%20§%201[1990 c 237 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c360.pdf?cite=1989%20c%20360%20§%2021[1989 c 360 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c231.pdf?cite=1988%20c%20231%20§%206[1988 c 231 § 6]; prior:  1987 c 64 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c88.pdf?cite=1890%20p%2088%20§%201[1890 p 88 § 1]; RRS § 566; ]

== 6.15.025 - Exemption of pension or retirement plan benefits from execution for judgment for out-of-state income tax.
Where a judgment is in favor of any state for failure to pay that state's income tax on benefits received while a resident of the state of Washington from a pension or other retirement plan, all property in this state, real or personal, tangible or intangible, of a judgment debtor shall be exempt from execution, attachment, garnishment, or seizure by or under any legal process whatever, and when a debtor dies, or absconds, and leaves his or her spouse and dependents any property exempted by this section, the same shall be exempt to the surviving spouse and dependents.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1105-S.SL.pdf?cite=1991%20c%20123%20§%203[1991 c 123 § 3]; ]

== 6.15.030 - Insurance money on exempt property exempt.
If property, which by the laws of this state is exempt from execution, attachment, or garnishment, is insured and the same is lost, stolen, or destroyed, then the insurance money coming to or belonging to the person thus insured, to an amount equal to the exempt property thus destroyed, shall be exempt from execution, attachment, and garnishment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c442.pdf?cite=1987%20c%20442%20§%20303[1987 c 442 § 303]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c76.pdf?cite=1895%20c%2076%20§%201[1895 c 76 § 1]; RRS § 568; ]

== 6.15.040 - Separate property of spouse exempt.
All real and personal property belonging to any married person at the time of his or her marriage, and all which he or she may have acquired subsequently to such marriage, or to which he or she shall hereafter become entitled in his or her own right, and all his or her personal earnings, and all the issues, rents and profits of such real property, shall be exempt from execution, attachment, and garnishment upon any liability or judgment against the other spouse, so long as he or she or any minor heir of his or her body shall be living: PROVIDED, That the separate property of each spouse shall be liable for debts owing by him or her at the time of marriage.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c442.pdf?cite=1987%20c%20442%20§%20304[1987 c 442 § 304]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c154.pdf?cite=1973%201st%20ex.s.%20c%20154%20§%2014[1973 1st ex.s. c 154 § 14]; Code 1881 § 341; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2071%20§%20345[1877 p 71 § 345]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2085%20§%20337[1869 p 85 § 337]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20178%20§%20252[1854 p 178 § 252]; RRS § 570; ]

== 6.15.050 - Exemptions under RCW  6.15.010—Limitations on exemptions.
. Wages, salary, or other compensation regularly paid for personal services rendered by the debtor claiming the exemption shall not be claimed as exempt under RCW 6.15.010, but the same may be claimed as exempt in any bankruptcy or insolvency proceeding to the same extent as allowed under the statutes relating to garnishments.

. No property may be exempt under RCW 6.15.010 from execution, attachment, or garnishment issued upon a judgment for all or any part of the purchase price of the property.

. No property may be exempt under RCW 6.15.010 from legal process issued upon a judgment for restitution ordered by a court to be paid for the benefit of a victim of a criminal act.

. No property may be exempt under RCW 6.15.010 from legal process issued upon a judgment for any tax levied upon such property.

. Nothing in this chapter shall be so construed as to prevent a debtor from creating a security interest in personal property which might be claimed as exempt, or the enforcement of such security interest against the property.

. Nothing in this chapter shall be construed to exempt personal property of a nonresident of this state or of an individual who has left or is about to leave this state with the intention to defraud his or her creditors.

. Personal property exemptions are waived by failure to claim them prior to sale of exemptible property under execution or, in a garnishment proceeding, within the time specified in RCW 6.27.160.

. Personal property exemptions may not be claimed by one spouse in a bankruptcy case that is not a joint case or a joint administration of the estate with the bankruptcy estate of the other spouse where (a) bankruptcy is filed by both spouses within a six-month period, and (b) one spouse exempts property from property of the estate under the bankruptcy exemption provisions of 11 U.S.C. Sec. 522(d).

. No property may be exempt under RCW 6.15.010 from execution, levy, attachment, or garnishment issued by or on behalf of a child support agency operating under Title IV-D of the federal social security act or by or on behalf of any agent or assignee of the child support agency.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6266.SL.pdf?cite=2002%20c%20265%20§%202[2002 c 265 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c442.pdf?cite=1987%20c%20442%20§%20305[1987 c 442 § 305]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c149.pdf?cite=1981%20c%20149%20§%202[1981 c 149 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c136.pdf?cite=1927%20c%20136%20§%201[1927 c 136 § 1]; Code 1881 § 348; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2074%20§%20352[1877 p 74 § 352]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2088%20§%20344[1869 p 88 § 344]; RRS § 571; ]

== 6.15.060 - Manner of claiming exemptions—Appraisement—Appraiser's fee.
. Except as provided in subsection (2) of this section, property claimed exempt under RCW 6.15.010 shall be selected by the individual entitled to the exemption, or by the husband or wife entitled to a community exemption, in the manner described in subsection (3) of this section.

. If, at the time of seizure under execution or attachment of property exemptible under *RCW 6.15.010(3) (a), (b), or (c), the individual or the husband or wife entitled to claim the exemption is not present, then the sheriff or deputy shall make a selection equal in value to the applicable exemptions and, if no appraisement is required and no objection is made by the creditor as permitted under subsection (4) of this section, the officer shall return the same as exempt by inventory. Any selection made as provided shall be prima facie evidence (a) that the property so selected is exempt from execution and attachment, and (b) that the property so selected is not in excess of the values specified for the exemptions.

. [Empty]
.. A debtor who claims personal property as exempt against execution or attachment shall, at any time before sale, deliver to the officer making the levy a list by separate items of the property claimed as exempt, together with an itemized list of all the personal property owned or claimed by the debtor, including money, bonds, bills, notes, claims and demands, with the residence of the person indebted upon the said bonds, bills, notes, claims and demands, and shall verify such list by affidavit. The officer shall immediately advise the creditor, attorney, or agent of the exemption claim and, if no appraisement is required and no objection is made by the creditor as permitted under subsection (4) of this section, the officer shall return with the process the list of property claimed as exempt.

.. A debtor who claims personal property exempt against garnishment shall proceed as provided in RCW 6.27.160.

.. A debtor who claims as a homestead, under chapter 6.13 RCW, a mobile home that is not yet occupied as a homestead and that is located on land not owned by the debtor shall claim the homestead as against a specific levy by delivering to the sheriff who levied on the mobile home, before sale under the levy, a declaration of homestead that contains (i) a declaration that the debtor owns the mobile home, intends to reside therein, and claims it as a homestead, and (ii) a description of the mobile home, a statement where it is located or was located before the levy, and an estimate of its actual cash value.

.. A debtor who claims as a homestead, under RCW 6.13.040, any other personal property, shall at any time before sale, deliver to the officer making the levy a notice of claim of homestead in a statement that sets forth the following: (i) The debtor owns the personal property; (ii) the debtor resides thereon as a homestead; (iii) the debtor's estimate of the fair market value of the property; and (iv) the debtor's description of the property in sufficient detail for the officer making the levy to identify the same.

. [Empty]
.. Except as provided in (b) of this subsection, a creditor, or the agent or attorney of a creditor, who wishes to object to a claim of exemption shall proceed as provided in RCW 6.27.160 and shall give notice of the objection to the officer not later than seven days after the officer's giving notice of the exemption claim.

.. A creditor, or the agent or attorney of the creditor, who wishes to object to a claim of exemption made to a levying officer, on the ground that the property claimed exceeds exemptible value, may demand appraisement. If the creditor, or the agent or attorney of the creditor, demands an appraisement, two disinterested persons shall be chosen to appraise the property, one by the debtor and the other by the creditor, agent or attorney, and these two, if they cannot agree, shall select a third; but if either party fails to choose an appraiser, or the two fail to select a third, or if one or more of the appraisers fail to act, the court shall appoint one or more as the circumstances require. The appraisers shall forthwith proceed to make a list by separate items, of the personal property selected by the debtor as exempt, which they shall decide as exempt, stating the value of each article, and annexing to the list their affidavit to the following effect: "We solemnly swear that to the best of our judgment the above is a fair cash valuation of the property therein described," which affidavit shall be signed by two appraisers at least, and be certified by the officer administering the oaths. The list shall be delivered to the officer holding the execution or attachment and be annexed to and made part of the return, and the property therein specified shall be exempt from levy and sale, but the other personal estate of the debtor shall remain subject to execution, attachment, or garnishment. Each appraiser shall be entitled to fifteen dollars or such larger fee as shall be fixed by the court, to be paid by the creditor if all the property claimed by the debtor shall be exempt; otherwise to be paid by the debtor.

.. If, within seven days following the giving of notice to a creditor of an exemption claim, the officer has received no notice from the creditor of an objection to the claim or a demand for appraisement, the officer shall release the claimed property to the debtor.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5068-S.SL.pdf?cite=1993%20c%20200%20§%205[1993 c 200 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c231.pdf?cite=1988%20c%20231%20§%207[1988 c 231 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c442.pdf?cite=1987%20c%20442%20§%20306[1987 c 442 § 306]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c154.pdf?cite=1973%201st%20ex.s.%20c%20154%20§%2015[1973 1st ex.s. c 154 § 15]; Code 1881 § 349; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2074%20§%20353[1877 p 74 § 353]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2088%20§%20346[1869 p 88 § 346]; RRS § 572; ]

== 6.15.070 - Procedure if value of property claimed exempt exceeds exemptible value.
If from an appraisal it appears that the value of the property claimed exempt, exclusive of liens and encumbrances, exceeds the exemptible value and the property is indivisible, the property shall be put up for sale on execution, but at the sale no bid may be received unless it exceeds the exempt value. The proceeds of a sale in excess of the exempt value shall be paid, first, to the debtor to the extent of the exempt amount; second, up to the amount of the execution, to the satisfaction of the execution; third, the balance to be paid to the debtor. A judgment creditor who is the successful bidder at the sale must pay the exempt amount in cash.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c442.pdf?cite=1987%20c%20442%20§%20307[1987 c 442 § 307]; ]

== 6.15.900 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%2013[2009 c 521 § 13]; ]

