= 6.19 - Adverse claims to property levied on.
:toc:

== 6.19.010 - Definitions.
The definitions in this section apply throughout this chapter.

. "Adverse claimant" means a person, other than the judgment debtor or defendant, who claims title or right to possession of property levied on.

. "Levying creditor" means the judgment creditor or plaintiff who obtained the writ of execution or attachment under which levy was made.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c442.pdf?cite=1987%20c%20442%20§%20501[1987 c 442 § 501]; ]

== 6.19.020 - Application of chapter—Common law or other remedies not superseded.
An adverse claimant may assert a claim under the procedures provided in this chapter whether the levy was made under a writ of execution or of attachment and whether the writ was issued by a superior court or a district court of this state, but this chapter does not supersede common law or other remedies available to an adverse claimant before or after levy or sale.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c442.pdf?cite=1987%20c%20442%20§%20502[1987 c 442 § 502]; ]

== 6.19.030 - Affidavit of adverse claimant—Bond—Hearing.
. An adverse claimant to property levied on may demand and receive the property from the sheriff who made the levy, upon making and delivering to the sheriff an affidavit that the property is owned by the claimant or that the claimant has a right to the immediate possession thereof, stating on oath the value thereof, and giving to the sheriff a bond, with sureties in double the value of such property. The bond shall be conditioned that the claimant will appear in the court specified in RCW 6.19.050 after the bond is accepted by the sheriff, and make good the claim in the affidavit or will return the property or pay its value to the sheriff.

. Without giving a bond, an adverse claimant who delivers to the sheriff an affidavit as described in subsection (1) of this section may, on motion made within seven days after delivering the affidavit, appear in the court specified in RCW 6.19.050, with notice to the sheriff and to the attorney of record for the levying creditor, if any, otherwise to the levying creditor, and set a hearing at which the probable validity of the claim stated in the affidavit can be considered. If the court, after the hearing, finds that the claim is probably valid, it shall direct the sheriff to release the claimed property to the claimant; otherwise, the court shall direct the sheriff to continue to hold the property unless the claimant gives a bond as provided in subsection (1) of this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c442.pdf?cite=1987%20c%20442%20§%20503[1987 c 442 § 503]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c40.pdf?cite=1891%20c%2040%20§%201[1891 c 40 § 1]; Code 1881 § 350; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2075%20§%20354[1877 p 75 § 354]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2089%20§%20347[1869 p 89 § 347]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20179%20§%20256[1854 p 179 § 256]; RRS § 573; ]

== 6.19.040 - Justification of sureties.
If the adverse claimant posts a bond and the sheriff requires it, the sureties shall justify as in other cases, and in case they do not so justify when required, the sheriff shall retain the property; if the sheriff does not require the sureties to justify, he or she shall stand good for their sufficiency. The sheriff shall date and indorse acceptance upon the bond.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c442.pdf?cite=1987%20c%20442%20§%20504[1987 c 442 § 504]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c8.pdf?cite=1957%20c%208%20§%205[1957 c 8 § 5]; Code 1881 § 351; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2075%20§%20354[1877 p 75 § 354]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2089%20§%20347[1869 p 89 § 347]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20179%20§%20256[1854 p 179 § 256]; RRS § 574; ]

== 6.19.050 - Filing of affidavit by sheriff—Designation of parties—Trial.
The sheriff shall immediately return the affidavit of an adverse claimant and the bond and justification, if any, to the office of the clerk of the court that issued the writ, unless the property was seized in another county, then to the clerk of the superior court of the county in which the property was seized or, if the levy was made under a writ of a district court of this state, then to a district court, to be selected by the sheriff, in the county in which the property was seized, and this case shall stand for trial in said court. The adverse claimant shall be the plaintiff, and the sheriff and the levying creditor shall be the defendants. The sheriff or levying creditor or both of them may respond to the affidavit, but no further pleadings are required, and any party may cause the matter to be noted for trial.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c442.pdf?cite=1987%20c%20442%20§%20505[1987 c 442 § 505]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c40.pdf?cite=1891%20c%2040%20§%202[1891 c 40 § 2]; Code 1881 § 352; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2075%20§%20355[1877 p 75 § 355]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2090%20§%20348[1869 p 90 § 348]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20179%20§%20257[1854 p 179 § 257]; RRS § 575; ]

== 6.19.060 - Judgment—Costs.
If the claimant makes good on all or any part of the claim to title to the property or right to possession, judgment shall be entered for the claimant to the extent the claim has been established. If the claimant has given a bond, the bond shall be canceled or, if the claimant makes good on only a portion of the claim, a like proportion of the bond shall be canceled. If the claimant has not given a bond and the sheriff has retained possession of the property, judgment shall be entered in favor of the claimant for return of the property or its value.

If the claimant does not maintain the claim, judgment shall be rendered against the claimant. If the claimant has retained possession of the property pending trial on the claim, the judgment shall be entered against the claimant and, if the claimant has given a bond, against the sureties for the return of the property or for the value of the property or of the portion of the property for which the claim is not maintained, or for such lesser amount as shall not exceed the amount due on the original execution or attachment.

When the judgment is in favor of the sheriff for the entire property, the claimant shall pay the costs; when the claimant recovers all the property, judgment shall be given in favor of the claimant for costs; when the claimant recovers a portion of the property only, the costs shall be apportioned. When the claimant prevails, the costs may be taxed against the levying creditor or, if the court finds that the sheriff attached or levied upon the property without the exercise of due caution, the court may require the sheriff to pay the costs or any portion thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c442.pdf?cite=1987%20c%20442%20§%20506[1987 c 442 § 506]; Code 1881 § 354; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1877%20p%2076%20§%20357[1877 p 76 § 357]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%2090%20§%20350[1869 p 90 § 350]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20179%20§%20259[1854 p 179 § 259]; RRS § 577; ]

