= 6.32 - Proceedings supplemental to execution.
:toc:

== 6.32.010 - Order for examination of judgment debtor—Plaintiff entitled to costs—Additional fees if debtor fails to answer or appear—When warrants permitted.
. At any time within ten years after entry of a judgment for the sum of twenty-five dollars or over, unless the time is extended in accordance with RCW 6.17.020(3), upon application by the judgment creditor such court or judge may, by an order, require the judgment debtor to appear at a specified time and place before the judge granting the order, or a referee appointed by the judge, to answer concerning the same.

. Except as provided in subsection (4) of this section, the judge to whom application is made under this chapter may, if it is made to appear to him or her by the affidavit of the judgment creditor, his or her agent or attorney that there is danger of the debtor absconding, order the sheriff to arrest the debtor and bring him or her before the judge granting the order. Upon being brought before the judge, he or she may be ordered to enter into a bond, with sufficient sureties, that he or she will attend from time to time before the judge or referee, as shall be directed, during the pendency of the proceedings and until the final termination thereof.

. If the judgment debtor or other persons against whom the special proceedings are instituted has been served with these proceedings, the plaintiff shall be entitled to costs of service, notary fees, and an appearance fee of twenty-five dollars. If the judgment debtor or other persons fail to answer or appear, the plaintiff shall additionally be entitled to reasonable attorney fees. If a plaintiff institutes special proceedings and fails to appear, a judgment debtor or other person against whom the proceeding was instituted who appears is entitled to an appearance fee of twenty-five dollars and reasonable attorney fees.

. A plaintiff may not seek a warrant for the arrest of a judgment debtor for any act or failure to act that arises out of or relates to a judgment for medical debt, unless the act or failure to act constitutes a crime under state law.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1531-S.SL.pdf?cite=2019%20c%20227%20§%202[2019 c 227 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6045-S.SL.pdf?cite=1994%20c%20189%20§%204[1994 c 189 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c215.pdf?cite=1985%20c%20215%20§%201[1985 c 215 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c45.pdf?cite=1983%201st%20ex.s.%20c%2045%20§%206[1983 1st ex.s. c 45 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c105.pdf?cite=1980%20c%20105%20§%205[1980 c 105 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c211.pdf?cite=1971%20ex.s.%20c%20211%20§%201[1971 ex.s. c 211 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c8.pdf?cite=1957%20c%208%20§%207[1957 c 8 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1899c93.pdf?cite=1899%20c%2093%20§%201[1899 c 93 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%201[1893 c 133 § 1]; RRS § 613; ]

== 6.32.015 - Order to require judgment debtor to answer interrogatories.
At any time within ten years after entry of a judgment for a sum of twenty-five dollars or over, unless the time is extended in accordance with RCW 6.17.020(3), upon application by the judgment creditor such court or judge may, by order served on the judgment debtor, require such debtor to answer written interrogatories, under oath, in such form as may be approved by the court. No such creditor shall be required to proceed under this section nor shall he or she waive his or her rights to proceed under RCW 6.32.010 by proceeding under this section.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6045-S.SL.pdf?cite=1994%20c%20189%20§%205[1994 c 189 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c105.pdf?cite=1980%20c%20105%20§%206[1980 c 105 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c211.pdf?cite=1971%20ex.s.%20c%20211%20§%202[1971 ex.s. c 211 § 2]; ]

== 6.32.020 - Warrant, how vacated.
A warrant issued as prescribed in RCW 6.32.010 may be vacated or modified by the judge making the same, or by the court out of which the execution was issued, upon giving three days' notice to the opposite party.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%202[1893 c 133 § 2]; RRS § 614; ]

== 6.32.030 - Third parties may be brought in for examination.
Any person may be made a party to a supplemental proceeding by service of a like order in like manner as that required to be served upon the judgment debtor, and upon proof by affidavit or otherwise, to the satisfaction of the judge, that execution has been issued and return made thereon wholly or partially unsatisfied, and also that any person or corporation has personal property of the judgment debtor of the value of twenty-five dollars or over, or is indebted to him or her in said amount, or is holding the title to real estate for the judgment debtor, or has knowledge concerning the property interests of the judgment debtor, the judge may make an order requiring such person or corporation, or an officer thereof, to appear at a specified time and place before him or her, or a referee appointed by him or her, and answer concerning the same.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20149[2011 c 336 § 149]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c160.pdf?cite=1923%20c%20160%20§%201[1923 c 160 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%203[1893 c 133 § 3]; RRS § 615; ]

== 6.32.040 - Before whom examined.
An order requiring a person to attend and be examined, made pursuant to any provision of this chapter, must require him or her so to attend and be examined either before the judge to whom the order is returnable or before a referee designated therein. Where the examination is taken before a referee, he or she must certify to the judge to whom the order is returnable all of the evidence and other proceedings taken before him or her.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20150[2011 c 336 § 150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%204[1893 c 133 § 4]; RRS § 616; ]

== 6.32.050 - Procedure on examination.
Upon an examination made under this chapter, the answer of the party or witness examined must be under oath. A corporation must attend by and answer under the oath of an officer thereof, and the judge may, in his or her discretion, specify the officer. Either party may be examined as a witness in his or her own behalf, and may produce and examine other witnesses as upon the trial of an action. The judge or referee may adjourn any proceedings under this chapter, from time to time, as he or she thinks proper.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20151[2011 c 336 § 151]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%205[1893 c 133 § 5]; RRS § 617; ]

== 6.32.060 - Referee's oath.
Unless the parties expressly waive the referee's oath, a referee appointed as prescribed in this chapter must, before entering upon an examination or taking testimony, subscribe and take an oath that he or she will faithfully and fairly discharge his or her duty upon the reference, and make a just and true report according to the best of his or her understanding. The oath must be returned to the judge with the report of the testimony.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20152[2011 c 336 § 152]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%206[1893 c 133 § 6]; RRS § 618; ]

== 6.32.070 - Order authorizing payment by debtor of judgment debtor.
At any time after the commencement of a special proceeding authorized by this chapter, and before the appointment of a receiver therein, or the extension of a receivership thereto, the judge by whom the order or warrant was granted or to whom it is made returnable, may in his or her discretion upon proof by affidavit to his or her satisfaction that a person or corporation is indebted to the judgment debtor, and upon such notice given to such person or corporation as he or she deems just, or without notice make an order permitting the person or corporation to pay the sheriff designated in the order a sum on account of the alleged indebtedness not exceeding the sum which will satisfy the execution. A payment thus made is to the extent thereof a discharge of the indebtedness except as against a transferee from the judgment debtor in good faith, and for a valuable consideration, of whose rights the person or corporation had actual or constructive notice when the payment was made.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20153[2011 c 336 § 153]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%207[1893 c 133 § 7]; RRS § 619; ]

== 6.32.080 - Order requiring delivery of money or property to sheriff.
Where it appears from the examination or testimony taken in the special proceedings authorized by this chapter that the judgment debtor has in his or her possession or under his or her control money or other personal property belonging to him or her, or that one or more articles of personal property capable of manual delivery, his or her right to the possession whereof is not substantially disputed, are in the possession or under the control of another person, the judge by whom the order or warrant was granted, or to whom it is returnable, may in his or her discretion, and upon such notice given to such persons as he or she deems just, or without notice, make an order directing the judgment debtor, or other person, immediately to pay the money or deliver the articles of personal property to a sheriff designated in the order, unless a receiver has been appointed or a receivership has been extended to the special proceedings, and in that case to the receiver.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20154[2011 c 336 § 154]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%208[1893 c 133 § 8]; RRS § 620; ]

== 6.32.085 - Order charging partnership interest or directing sale.
If it appears from the examination or testimony taken in the special proceedings authorized by this chapter that the judgment debtor owns an interest in a partnership, the judge who granted the order or warrant or to whom it is returnable may in his or her discretion, upon such notice to other partners as the judge deems just, and to the extent permitted by Title 25 RCW, (1) enter an order charging the partnership interest with payment of the judgment, directing that all or any part of distributions or other amounts becoming due to the judgment debtor, other than earnings as defined in RCW 6.27.010, be paid to a receiver if one has been appointed, otherwise to the clerk of the court that entered the judgment, for application to payment of the judgment in the same manner as proceeds from sale on execution and, in aid of the charging order, the court may make such other orders as a case requires, or (2) enter an order directing sale of the partnership interest in the same manner as personal property is sold on execution.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c442.pdf?cite=1987%20c%20442%20§%201114[1987 c 442 § 1114]; ]

== 6.32.090 - Powers of sheriff.
If the sheriff to whom money is paid or other property is delivered, pursuant to an order made as prescribed in RCW 6.32.080, does not then hold an execution upon the judgment against the property of the judgment debtor, he or she has the same rights and power, and is subject to the same duties and liabilities with respect to the money or property, as if the money had been collected or the property had been levied upon by him or her by virtue of such an execution, except as provided in RCW 6.32.100.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20155[2011 c 336 § 155]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%209[1893 c 133 § 9]; RRS § 621; ]

== 6.32.100 - How money or property applied by sheriff.
Unless a receiver has been appointed or extended with respect to money or property in the hands of the sheriff, the judge may direct the sheriff to apply the money, the property, or the proceeds of the property, upon an execution in favor of the judgment creditor issued either before or after the payment or delivery to the sheriff.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6189-S.SL.pdf?cite=2004%20c%20165%20§%2034[2004 c 165 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%2010[1893 c 133 § 10]; RRS § 622; ]

== 6.32.110 - Disposition of balance after judgment satisfied.
Where money is paid or property is delivered as prescribed in RCW 6.32.070, 6.32.080, 6.32.090, and 6.32.100 and afterwards the special proceeding is discontinued or dismissed, or the judgment is satisfied without resorting to the money or property, or a balance of the money or of the proceeds of the property, or a part of the property remains in the sheriff's or receiver's hands after satisfying the judgment and the costs and expenses of the special proceeding, the judge must make an order directing the sheriff or receiver to pay the money or deliver the property so remaining in his or her hands to the debtor, or to such other person as appears to be entitled thereto, upon payment of his or her fees and all other sums legally chargeable against the same.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20156[2011 c 336 § 156]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%2011[1893 c 133 § 11]; RRS § 623; ]

== 6.32.120 - Transfer of property may be enjoined.
The judge by whom the order or warrant was granted or to whom it is returnable may make an injunction order restraining any person or corporation, whether a party or not a party to the special proceeding, from making or suffering any transfer or other disposition of or interference with the property of the judgment debtor or the property or debt concerning which any person is required to attend and be examined, until further direction in the premises. Such an injunction may be made simultaneously with the order or warrant by which the special proceeding is instituted, and upon the same papers or afterwards, upon an affidavit showing sufficient grounds therefor. The judge or court may, as a condition of granting an application to vacate or modify the injunction order require the applicant to give security in such sum and in such manner as justice requires.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%2012[1893 c 133 § 12]; RRS § 624; ]

== 6.32.130 - Service of orders.
An injunction order or an order requiring a person to attend and be examined made as prescribed in this chapter must be served by delivering to the person to be served a certified copy of the original order and a copy of the affidavit on which it was made. In the case of an order requiring a person to attend and be examined and not imposing injunctive restraints, a noncertified copy may be served if the noncertified copy bears a stamp or notation indicating the name of the judge or commissioner who signed the original order, and a stamp or notation indicating the original order has been filed with the court.

Service upon a corporation is sufficient if made upon an officer, to whom a copy of a summons must be delivered. Where an order is personally served upon a corporation, unless the officer to be served is specially designated in the order, the order may be served upon any person upon whom a summons can be served.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5164-S.SL.pdf?cite=1995%20c%2073%20§%201[1995 c 73 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c38.pdf?cite=1925%20ex.s.%20c%2038%20§%201[1925 ex.s. c 38 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%2013[1893 c 133 § 13]; RRS § 625; ]

== 6.32.140 - Service of warrant.
The sheriff, when he or she arrests a judgment debtor by virtue of a warrant issued as prescribed in this chapter, must deliver to him or her a copy of the warrant and of the affidavit upon which it was granted.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20157[2011 c 336 § 157]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%2014[1893 c 133 § 14]; RRS § 626; ]

== 6.32.150 - Discontinuance or dismissal of proceedings.
A special proceeding instituted as prescribed in this chapter may be discontinued at any time upon such terms as justice requires, by an order of the judge made upon the application of the judgment creditor. Where the judgment creditor unreasonably delays or neglects to proceed, or where it appears that the judgment has been satisfied, the special proceedings may be dismissed upon like terms by a like order made upon the application of the judgment debtor, or of plaintiff in a judgment creditor's action against the debtor, or of a judgment creditor who has instituted either of the special proceedings authorized by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6189-S.SL.pdf?cite=2004%20c%20165%20§%2035[2004 c 165 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%2015[1893 c 133 § 15]; RRS § 627; ]

== 6.32.160 - Costs to judgment creditor.
The judge may make an order allowing to the judgment creditor a fixed sum as costs, consisting of his or her witness fees and referee's fees and other disbursements, and of a sum in addition thereto not exceeding twenty-five dollars, and directing the payment thereof out of any money which has come or may come to the hands of the receiver or of the sheriff within a time specified in the order.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20158[2011 c 336 § 158]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%2016[1893 c 133 § 16]; RRS § 628; ]

== 6.32.170 - Costs to judgment debtor, when.
Where the judgment debtor or other person against whom the special proceeding is instituted has been examined, and property applicable to the payment of the judgment has not been discovered, the judge may make an order allowing him or her a sum, not to exceed twenty-five dollars, as costs, provided that any such sum so allowed the judgment debtor, shall be set off against the amount due the judgment creditor on his or her judgment.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20159[2011 c 336 § 159]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c160.pdf?cite=1923%20c%20160%20§%202[1923 c 160 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%2017[1893 c 133 § 17]; RRS § 629; ]

== 6.32.180 - Disobedience of order punishable as contempt.
A person who refuses, or without sufficient excuse neglects, to obey an order of a judge or referee made pursuant to any of the provisions of this chapter, and duly served upon him or her, or an oral direction given directly to him or her by a judge or referee in the course of the special proceeding, or to attend before a judge or referee according to the command of a subpoena duly served upon him or her, may be punished by the judge of the court out of which the execution issued, as for contempt.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20160[2011 c 336 § 160]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%2018[1893 c 133 § 18]; RRS § 630; ]

== 6.32.190 - Attendance of judgment debtor.
A judgment debtor who resides or does business in the state cannot be compelled to attend pursuant to an order made under the provisions of this chapter at a place without the county where his or her residence or place of business is situated. Where the judgment debtor to be examined under this chapter is a corporation the court may cause such corporation to appear and be examined by making like order or orders as are prescribed in this chapter, directed to any officer or officers thereof.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20161[2011 c 336 § 161]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%2019[1893 c 133 § 19]; RRS § 631; ]

== 6.32.200 - Party or witness not excused from answering.
A party or witness examined in a special proceeding authorized by this chapter is not excused from answering a question on the ground that his or her examination will tend to convict him or her of a commission of a fraud, or to prove that he or she has been a party to or privy to or knowing of a conveyance, assignment, transfer, or other disposition of property for any purpose; or that he, she, or another person claims to be entitled as against the judgment creditor or receiver appointed or to be appointed in the special proceeding to hold property derived from or through the judgment debtor, or to be discharged from the payment of a debt which was due to the judgment debtor or to a person in his or her behalf. But an answer cannot be used as evidence against the person so answering in a criminal action or criminal proceeding.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20162[2011 c 336 § 162]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%2020[1893 c 133 § 20]; RRS § 632; ]

== 6.32.210 - Proceedings in case of joint debtors.
When, in proceedings under this chapter, personal service of the summons in the action was not made on all of the defendants, a debt due to, or other personal property owned by, one or more of the defendants not summoned jointly with the defendants summoned, or with any of them, may be reached by proceedings under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%2021[1893 c 133 § 21]; RRS § 633; ]

== 6.32.220 - Continuances.
A special proceeding under this chapter instituted before one judge may be continued from time to time before another judge of the same court with like effect as if it had been instituted or commenced before the judge who last heard the same.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%2022[1893 c 133 § 22]; RRS § 634; ]

== 6.32.240 - Proceedings, before whom instituted.
Special proceedings under this chapter may be instituted and prosecuted before the superior or district court of the county in which the judgment was entered or any judge thereof, or before the superior or district court of any county to the sheriff of which an execution has been issued or in which a transcript of said judgment has been filed in the office of the clerk of said court or before any judge thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c193.pdf?cite=1981%20c%20193%20§%202[1981 c 193 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1899c93.pdf?cite=1899%20c%2093%20§%202[1899 c 93 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%2024[1893 c 133 § 24]; RRS § 636; ]

== 6.32.250 - Property exempt from seizure.
This chapter does not authorize the seizure of, or other interference with, (1) any property which is expressly exempt by law from levy and sale by virtue of an execution, attachment, or garnishment; or (2) any money, thing in action or other property held in trust for a judgment debtor where the trust has been created by, or the fund so held in trust has proceeded from, a person other than the judgment debtor; or (3) the earnings of the judgment debtor for personal services to the extent they would be exempt against garnishment of the employer under RCW 6.27.150. For purposes of this section, a person shall not be treated as having made a disposition in trust for the use of that person by reason of a lapse of a power of withdrawal over the income or corpus of a trust created by another person. For this purpose, notification to the trustee of the trust of an intent not to exercise the power of withdrawal shall not be treated as a release of the power of withdrawal, but shall be treated as a lapse of the power.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6597-S.SL.pdf?cite=2006%20c%20360%20§%2013[2006 c 360 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c442.pdf?cite=1987%20c%20442%20§%201115[1987 c 442 § 1115]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%2025[1893 c 133 § 25]; RRS § 637; ]

== 6.32.260 - Proceedings to be heard without jury.
Proceedings under this chapter are special proceedings, and shall be heard by the judge or referee before whom the same are returnable without a jury, except as provided in RCW 6.32.270.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c160.pdf?cite=1923%20c%20160%20§%203[1923 c 160 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%2026[1893 c 133 § 26]; RRS § 638; ]

== 6.32.270 - Adjudication of title to property—Jury trial.
In any supplemental proceeding, where it appears to the court that a judgment debtor may have an interest in or title to any real property, and such interest or title is disclaimed by the judgment debtor or disputed by another person, or it appears that the judgment debtor may own or have a right of possession to any personal property, and such ownership or right of possession is substantially disputed by another person, the court may, if the person or persons claiming adversely be a party to the proceeding, adjudicate the respective interests of the parties in such real or personal property, and may determine such property to be wholly or in part the property of the judgment debtor. If the person claiming adversely to the judgment debtor be not a party to the proceeding, the court shall by show cause order or otherwise cause such person to be brought in and made a party thereto, and shall set such proceeding for hearing on the first open date in the trial calendar. Any person so made a party, or any party to the original proceeding, may have such issue determined by a jury upon demand therefor and payment of a jury fee as in other civil actions: PROVIDED, That such person would be entitled to a jury trial if the matter was adjudicated in a separate action.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c160.pdf?cite=1923%20c%20160%20§%204[1923 c 160 § 4]; RRS § 638-1; ]

== 6.32.280 - Fee of referee.
The fees of referees appointed in proceedings under this chapter shall be five dollars per day.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c133.pdf?cite=1893%20c%20133%20§%2027[1893 c 133 § 27]; RRS § 639; ]

