= 6.36 - Uniform enforcement of foreign judgments act.
:toc:

== 6.36.010 - Definitions.
As used in this chapter: (1) "Foreign judgment" means any judgment, decree or order of a court of the United States or of any state or territory which is entitled to full faith and credit in this state.

. "Register" means to file a foreign judgment in a court of this state.

. "Levy" means to take control of or create a lien upon property under any judicial writ or process whereby satisfaction of a judgment may be enforced against such property.

. "Judgment debtor" means the party against whom a foreign judgment has been rendered.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c191.pdf?cite=1953%20c%20191%20§%201[1953 c 191 § 1]; ]

== 6.36.025 - Filing of foreign judgment—Authorized—Effect.
. A copy of any foreign judgment authenticated in accordance with the act of congress or the statutes of this state may be filed in the office of the clerk of any superior court of any county of this state. The clerk shall treat the foreign judgment in the same manner as a judgment of the superior court of this state. A judgment so filed has the same effect and is subject to the same procedures, defenses, set-offs, counterclaims, cross-complaints, and proceedings for reopening, vacating, staying, or extending as a judgment of a superior court of this state and may be enforced, extended, or satisfied in like manner.

. Alternatively, a copy of any foreign judgment (a) authenticated in accordance with the act of congress or the statutes of this state, and (b) within the civil jurisdiction and venue of the district court as provided in RCW 3.66.020, 3.66.030, and 3.66.040, may be filed in the office of the clerk of any district court of this state. The clerk shall treat the foreign judgment in the same manner as a judgment of the district court of this state. A judgment so filed has the same effect and is subject to the same procedures, defenses, set-offs, counterclaims, cross-complaints, and proceedings for reopening, vacating, staying, transcribing, or extending as a judgment of a district court of this state, and may be enforced, transcribed, extended, or satisfied in like manner.

. The lien of any judgment filed under subsection (1) or (2) of this section shall be governed by chapter 4.56 RCW and RCW 6.17.020.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5827-S2.SL.pdf?cite=2002%20c%20261%20§%204[2002 c 261 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5449.SL.pdf?cite=1994%20c%20185%20§%206[1994 c 185 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c45.pdf?cite=1977%20ex.s.%20c%2045%20§%201[1977 ex.s. c 45 § 1]; ]

== 6.36.035 - Affidavit of last address of judgment debtor, creditor—Filing—Notice of filing of judgment—Contents—Effect.
. At the time of the filing of the foreign judgment, the judgment creditor or the judgment creditor's lawyer shall make and file with the clerk of court an affidavit setting forth the name and last known post office address of the judgment debtor, the judgment creditor, and the filing and expiration date of the judgment in the originating jurisdiction.

. Promptly upon the filing of the foreign judgment and the affidavit, the judgment creditor shall mail notice of the filing of the foreign judgment to the judgment debtor at the address given. The notice shall include the name and post office address of the judgment creditor and the judgment creditor's lawyer if any in this state. In addition, the judgment creditor shall file proof of mailing with the clerk. 

. [Empty]
.. No execution or other process for enforcement of a foreign judgment filed in the office of the clerk of a superior court shall be allowed until ten days after the proof of mailing has been filed with the clerk by the judgment creditor.

.. No execution or other process for enforcement of a foreign judgment filed in the office of the clerk of a district court shall be allowed until fourteen days after the proof of mailing has been filed with the clerk by the judgment creditor.

.. Nothing in this section may be interpreted to extend the expiration date of a foreign judgment beyond the expiration date under the laws of the jurisdiction where the judgment originated.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5251-S.SL.pdf?cite=2003%20c%2043%20§%202[2003 c 43 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5144-S.SL.pdf?cite=1997%20c%20358%20§%201[1997 c 358 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5449.SL.pdf?cite=1994%20c%20185%20§%207[1994 c 185 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c97.pdf?cite=1979%20c%2097%20§%201[1979 c 97 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c45.pdf?cite=1977%20ex.s.%20c%2045%20§%202[1977 ex.s. c 45 § 2]; ]

== 6.36.045 - Effect of appeal from or stay of execution of foreign judgment—Grounds for stay of enforcement.
. [Empty]
.. If the judgment debtor shows the superior court of any county that an appeal from the foreign judgment is pending or will be taken, or that a stay of execution has been granted, the court shall stay enforcement of the foreign judgment until the appeal is concluded, the time for appeal expires, or the stay of execution expires or is vacated, upon proof that the judgment debtor has furnished the security for the satisfaction of the judgment required by the state in which it was rendered.

.. If the judgment debtor shows the superior court of any county any ground upon which enforcement of a judgment of a superior court of any county of this state would be stayed, the court shall stay enforcement of the foreign judgment for an appropriate period, upon requiring the same security for satisfaction of the judgment which is required in this state.

. [Empty]
.. If the judgment debtor shows the district court that an appeal from the foreign judgment is pending or will be taken, or that a stay of execution has been granted, the court shall stay enforcement of the foreign judgment until the appeal is concluded, the time for appeal expires, or the stay of execution expires or is vacated, upon proof that the judgment debtor has furnished the security for the satisfaction of the judgment required by the state in which it was rendered.

.. If the judgment debtor shows the district court any ground upon which enforcement of a judgment of a district court of this state would be stayed, the court shall stay enforcement of the foreign judgment for an appropriate period, upon requiring the same security for satisfaction of the judgment which is required in this state.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5449.SL.pdf?cite=1994%20c%20185%20§%208[1994 c 185 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c45.pdf?cite=1977%20ex.s.%20c%2045%20§%203[1977 ex.s. c 45 § 3]; ]

== 6.36.130 - Sale under levy.
Sale under the levy may be held at any time after final judgment, either personal or QUASI IN REM, but not earlier except as otherwise provided by law for sale under levy on perishable goods. Sale and distribution of the proceeds shall be made in accordance with the law of this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c191.pdf?cite=1953%20c%20191%20§%2013[1953 c 191 § 13]; ]

== 6.36.140 - Interest and costs.
When a registered foreign judgment becomes a final judgment of this state, the court shall include as part of the judgment interest payable on the foreign judgment under the law of the state in which it was rendered, and the cost of obtaining the authenticated copy of the original judgment. The court shall include as part of its judgment court costs incidental to the proceeding in accordance with the law of this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c191.pdf?cite=1953%20c%20191%20§%2014[1953 c 191 § 14]; ]

== 6.36.150 - Satisfaction of judgment.
Satisfaction, either partial or complete, of the original judgment or of a judgment entered thereupon in any other state shall operate to the same extent as satisfaction of the judgment in this state, except as to costs authorized by RCW 6.36.140.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c191.pdf?cite=1953%20c%20191%20§%2015[1953 c 191 § 15]; ]

== 6.36.160 - Optional procedure.
The right of a judgment creditor to bring an action to enforce his or her judgment instead of proceeding under this chapter remains unimpaired.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20163[2011 c 336 § 163]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c191.pdf?cite=1953%20c%20191%20§%2016[1953 c 191 § 16]; ]

== 6.36.900 - Construction—1953 c 191.
This chapter shall be so interpreted and construed as to effectuate its general purpose to make uniform the law of those states which enact it.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c191.pdf?cite=1953%20c%20191%20§%2017[1953 c 191 § 17]; ]

== 6.36.910 - Short title.
This chapter may be cited as the "Uniform Enforcement of Foreign Judgments Act."

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c191.pdf?cite=1953%20c%20191%20§%2018[1953 c 191 § 18]; ]

