= 6.40A - Uniform foreign-country money judgments recognition act.
:toc:

== 6.40A.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Foreign country" means a government other than:

.. The United States;

.. A state, district, commonwealth, territory, or insular possession of the United States; or

.. Any other government with regard to which the decision in this state as to whether to recognize a judgment of that government's courts is initially subject to determination under the full faith and credit clause of the United States Constitution.

. "Foreign-country judgment" means a judgment of a court of a foreign country.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5153.SL.pdf?cite=2009%20c%20363%20§%202[2009 c 363 § 2]; ]

== 6.40A.020 - Applicability.
. Except as otherwise provided in subsection (2) of this section, this chapter applies to a foreign-country judgment to the extent that the judgment:

.. Grants or denies recovery of a sum of money; and

.. Under the law of the foreign country where rendered, is final, conclusive, and enforceable.

. This chapter does not apply to a foreign-country judgment, even if the judgment grants or denies recovery of a sum of money, to the extent that the judgment is:

.. A judgment for taxes;

.. A fine or other penalty; or

.. A judgment for divorce, support, or maintenance, or other judgment rendered in connection with domestic relations.

. A party seeking recognition of a foreign-country judgment has the burden of establishing that this chapter applies to the foreign-country judgment.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5153.SL.pdf?cite=2009%20c%20363%20§%203[2009 c 363 § 3]; ]

== 6.40A.030 - Recognition of foreign-country judgments—Grounds for nonrecognition.
. Except as otherwise provided in subsections (2) and (3) of this section, a court of this state shall recognize a foreign-country judgment to which this chapter applies.

. A court of this state may not recognize a foreign-country judgment if:

.. The judgment was rendered under a judicial system that does not provide impartial tribunals or procedures compatible with the requirements of due process of law;

.. The foreign court did not have personal jurisdiction over the defendant; or

.. The foreign court did not have jurisdiction over the subject matter.

. A court of this state need not recognize a foreign-country judgment if:

.. The defendant in the proceeding in the foreign court did not receive notice of the proceeding in sufficient time to enable the defendant to defend;

.. The judgment was obtained by fraud that deprived the losing party of an adequate opportunity to present its case;

.. The judgment or the cause of action on which the judgment is based is repugnant to the public policy of this state or of the United States;

.. The judgment conflicts with another final and conclusive judgment;

.. The proceeding in the foreign court was contrary to an agreement between the parties under which the dispute in question was to be determined otherwise than by proceedings in that foreign court;

.. In the case of jurisdiction based only on personal service, the foreign court was a seriously inconvenient forum for the trial of the action;

.. The judgment was rendered in circumstances that raise substantial doubt about the integrity of the rendering court with respect to the judgment; or

.. The specific proceeding in the foreign court leading to the judgment was not compatible with the requirements of due process of law.

. A party resisting recognition of a foreign-country judgment has the burden of establishing that a ground for nonrecognition stated in subsection (2) or (3) of this section exists.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5153.SL.pdf?cite=2009%20c%20363%20§%204[2009 c 363 § 4]; ]

== 6.40A.040 - Personal jurisdiction.
. A foreign-country judgment may not be refused recognition for lack of personal jurisdiction if:

.. The defendant was served with process personally in the foreign country;

.. The defendant voluntarily appeared in the proceeding, other than for the purpose of protecting property seized or threatened with seizure in the proceeding or of contesting the jurisdiction of the court over the defendant;

.. The defendant, before the commencement of the proceeding, had agreed to submit to the jurisdiction of the foreign court with respect to the subject matter involved;

.. The defendant was domiciled in the foreign country when the proceeding was instituted or was a corporation or other form of business organization that had its principal place of business in, or was organized under the laws of, the foreign country;

.. The defendant had a business office in the foreign country and the proceeding in the foreign court involved a cause of action arising out of business done by the defendant through that office in the foreign country; or

.. The defendant operated a motor vehicle or airplane in the foreign country and the proceeding involved a cause of action arising out of that operation.

. The list of bases for personal jurisdiction in subsection (1) of this section is not exclusive. The courts of this state may recognize bases of personal jurisdiction other than those listed in subsection (1) of this section as sufficient to support a foreign-country judgment.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5153.SL.pdf?cite=2009%20c%20363%20§%205[2009 c 363 § 5]; ]

== 6.40A.050 - Recognition—How raised.
. If recognition of a foreign-country judgment is sought as an original matter, the issue of recognition shall be raised by filing an action seeking recognition of the foreign-country judgment.

. If recognition of a foreign-country judgment is sought in a pending action, the issue of recognition may be raised by counterclaim, cross-claim, or affirmative defense.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5153.SL.pdf?cite=2009%20c%20363%20§%206[2009 c 363 § 6]; ]

== 6.40A.060 - Judgments entitled to recognition—Enforceability.
If the court in a proceeding under RCW 6.40A.050 finds that the foreign-country judgment is entitled to recognition under this chapter then, to the extent that the foreign-country judgment grants or denies recovery of a sum of money, the foreign-country judgment is:

. Conclusive between the parties to the same extent as the judgment of a sister state entitled to full faith and credit in this state would be conclusive; and

. Enforceable in the same manner and to the same extent as a judgment rendered in this state.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5153.SL.pdf?cite=2009%20c%20363%20§%207[2009 c 363 § 7]; ]

== 6.40A.070 - Stay in case of appeal.
If a party establishes that an appeal from a foreign-country judgment is pending or will be taken, the court may stay any proceedings with regard to the foreign-country judgment until the appeal is concluded, the time for appeal expires, or the appellant has had sufficient time to prosecute the appeal and has failed to do so.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5153.SL.pdf?cite=2009%20c%20363%20§%208[2009 c 363 § 8]; ]

== 6.40A.080 - Time limitations for commencement of action.
An action to recognize a foreign-country judgment must be commenced within the earlier of the time during which the foreign-country judgment is effective in the foreign country or fifteen years from the date that the foreign-country judgment became effective in the foreign country.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5153.SL.pdf?cite=2009%20c%20363%20§%209[2009 c 363 § 9]; ]

== 6.40A.090 - Savings clause.
This chapter does not prevent the recognition under principles of comity or otherwise of a foreign-country judgment not within the scope of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5153.SL.pdf?cite=2009%20c%20363%20§%2012[2009 c 363 § 12]; ]

== 6.40A.900 - Uniformity of interpretation.
In applying and construing this uniform act, consideration must be given to the need to promote uniformity of the law with respect to its subject matter among states that enact it.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5153.SL.pdf?cite=2009%20c%20363%20§%2010[2009 c 363 § 10]; ]

== 6.40A.901 - Short title.
This chapter may be known and cited as the uniform foreign-country money judgments recognition act.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5153.SL.pdf?cite=2009%20c%20363%20§%201[2009 c 363 § 1]; ]

== 6.40A.902 - Chapter applies to actions commenced on or after July 26, 2009.
This chapter applies to all actions commenced on or after July 26, 2009, in which the issue of recognition of a foreign-country judgment is raised.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5153.SL.pdf?cite=2009%20c%20363%20§%2011[2009 c 363 § 11]; ]

