= 6.44 - Uniform foreign-money claims act.
:toc:

== 6.44.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter:

. "Action" means a judicial proceeding or arbitration in which a payment in money may be awarded or enforced with respect to a foreign-money claim.

. "Bank-offered spot rate" means the spot rate of exchange at which a bank will sell foreign money at a spot rate.

. "Conversion date" means the banking day next preceding the date on which money, in accordance with this chapter, is:

.. Paid to a claimant in an action or distribution proceeding;

.. Paid to the official designated by law to enforce a judgment or award on behalf of a claimant; or

.. Used to recoup, set off, or counterclaim in different moneys in an action or distribution proceeding.

. "Distribution proceeding" means a judicial or nonjudicial proceeding for the distribution of a fund in which one or more foreign-money claims is asserted and includes an accounting, an assignment for the benefit of creditors, a foreclosure, the liquidation or rehabilitation of a corporation or other entity, and the distribution of an estate, trust, or other fund.

. "Foreign money" means money other than money of the United States of America.

. "Foreign-money claim" means a claim upon an obligation to pay, or a claim for recovery of a loss, expressed in or measured by a foreign money.

. "Money" means a medium of exchange for the payment of obligations or a store of value authorized or adopted by a government or by intergovernmental agreement.

. "Money of the claim" means the money determined as proper pursuant to RCW 6.44.040.

. "Person" means an individual, corporation, government or governmental subdivision or agency, business trust, estate, trust, joint venture, partnership, association, two or more persons having a joint or common interest, or any other legal or commercial entity.

. "Rate of exchange" means the rate at which money of one country may be converted into money of another country in a free financial market convenient to or reasonably usable by a person obligated to pay or to state a rate of conversion. If separate rates of exchange apply to different kinds of transactions, the term means the rate applicable to the particular transaction giving rise to the foreign-money claim.

. "Spot rate" means the rate of exchange at which foreign money is sold by a bank or other dealer in foreign exchange for immediate or next day availability or for settlement by immediate payment in cash or equivalent, by charge to an account, or by an agreed delayed settlement not exceeding two days.

. "State" means a state of the United States, the District of Columbia, the Commonwealth of Puerto Rico, or a territory or insular possession subject to the jurisdiction of the United States.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1091.SL.pdf?cite=1991%20c%20153%20§%201[1991 c 153 § 1]; ]

== 6.44.020 - Scope.
. This chapter applies only to a foreign-money claim in an action or distribution proceeding.

. This chapter applies to foreign-money issues even if other law under the conflict of laws rules of this state applies to other issues in the action or distribution proceeding.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1091.SL.pdf?cite=1991%20c%20153%20§%202[1991 c 153 § 2]; ]

== 6.44.030 - Variation by agreement.
. The effect of this chapter may be varied by agreement of the parties made before or after commencement of an action or distribution proceeding or the entry of judgment.

. Parties to a transaction may agree upon the money to be used in a transaction giving rise to a foreign-money claim and may agree to use different moneys for different aspects of the transaction. Stating the price in a foreign money for one aspect of a transaction does not alone require the use of that money for other aspects of the transaction.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1091.SL.pdf?cite=1991%20c%20153%20§%203[1991 c 153 § 3]; ]

== 6.44.040 - Determining money of the claim.
. The money in which the parties to a transaction have agreed that payment is to be made is the proper money of the claim for payment.

. If the parties to a transaction have not otherwise agreed, the proper money of the claim, as in each case may be appropriate, is the money:

.. Regularly used between the parties as a matter of usage or course of dealing;

.. Used at the time of a transaction in international trade, by trade usage or common practice, for valuing or settling transactions in the particular commodity or service involved; or

.. In which the loss was ultimately felt or will be incurred by the party claimant.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1091.SL.pdf?cite=1991%20c%20153%20§%204[1991 c 153 § 4]; ]

== 6.44.050 - Determining amount of the money of certain contract claims.
. If an amount contracted to be paid in a foreign money is measured by a specified amount of a different money, the amount to be paid is determined on the conversion date.

. If an amount contracted to be paid in a foreign money is to be measured by a different money at the rate of exchange prevailing on a date before default, that rate of exchange applies only to payments made within a reasonable time after default, not exceeding thirty days. Thereafter, conversion is made at the bank-offered spot rate on the conversion date.

. A monetary claim is neither usurious nor unconscionable because the agreement on which it is based provides that the amount of the debtor's obligation to be paid in the debtor's money, when received by the creditor, must equal a specified amount of the foreign money of the country of the creditor. If, because of unexcused delay in payment of a judgment or award, the amount received by the creditor does not equal the amount of the foreign money specified in the agreement, the court or arbitrator shall amend the judgment or award accordingly.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1091.SL.pdf?cite=1991%20c%20153%20§%205[1991 c 153 § 5]; ]

== 6.44.060 - Asserting and defending foreign-money claim.
. A person may assert a claim in a specified foreign money. If a foreign-money claim is not asserted, the claimant makes the claim in United States dollars.

. An opposing party may allege and prove that a claim, in whole or in part, is in a different money than that asserted by the claimant.

. A person may assert a defense, set-off, recoupment, or counterclaim in any money without regard to the money of other claims.

. The determination of the proper money of the claim is a question of law.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1091.SL.pdf?cite=1991%20c%20153%20§%206[1991 c 153 § 6]; ]

== 6.44.070 - Judgments and awards on foreign-money claims—Times of money conversion—Form of judgment.
. Except as provided in subsection (3) of this section, a judgment or award on a foreign-money claim must be stated in an amount of the money of the claim.

. A judgment or award on a foreign-money claim is payable in that foreign money or, at the option of the debtor, in the amount of United States dollars which will purchase that foreign money on the conversion date at a bank-offered spot rate.

. Assessed costs must be entered in United States dollars.

. Each payment in United States dollars must be accepted and credited on a judgment or award on a foreign-money claim in the amount of the foreign money that could be purchased by the dollars at a bank-offered spot rate of exchange at or near the close of business on the conversion date for that payment.

. A judgment or award made in an action or distribution proceeding on both (a) a defense, set-off, recoupment, or counterclaim, and (b) the adverse party's claim, must be netted by converting the money of the smaller into the money of the larger, and by subtracting the smaller from the larger, and specify the rates of exchange used.

. A judgment substantially in the following form complies with subsection (1) of this section:

IT IS ADJUDGED AND ORDERED, that defendant    (insert name)    pay to plaintiff    (insert name)    the sum of    (insert amount in the foreign money)    plus interest on that sum at the rate of    (insert rate—see RCW 6.44.090)    percent a year or, at the option of the judgment debtor, the number of United States dollars which will purchase the    (insert name of foreign money)    with interest due, at a bank-offered spot rate at or near the close of business on the banking day next before the day of payment, together with assessed costs of    (insert amount)    United States dollars.

. If a contract claim is of the type covered by RCW 6.44.050 (a) or (b) [(1) or (2)], the judgment or award must be entered for the amount of money stated to measure the obligation to be paid in the money specified for payment or, at the option of the debtor, the number of United States dollars which will purchase the computed amount of the money of payment on the conversion date at a bank-offered spot rate.

. A judgment must be filed or docketed and indexed in foreign money in the same manner, and has the same effect as a lien, as other judgments. It may be discharged by payment.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1091.SL.pdf?cite=1991%20c%20153%20§%207[1991 c 153 § 7]; ]

== 6.44.080 - Conversions of foreign money in distribution proceeding.
The rate of exchange prevailing at or near the close of business on the day the distribution proceeding is initiated governs all exchanges of foreign money in a distribution proceeding. A foreign-money claimant in a distribution proceeding shall assert its claim in the named foreign money and show the amount of United States dollars resulting from a conversion as of the date the proceeding was initiated.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1091.SL.pdf?cite=1991%20c%20153%20§%208[1991 c 153 § 8]; ]

== 6.44.090 - Prejudgment and judgment interest.
. With respect to a foreign-money claim, recovery of prejudgment or preaward interest and the rate of interest to be applied in the action or distribution proceeding, except as provided in subsection (2) of this section, are matters of the substantive law governing the right to recovery under the conflict of laws rules of this state.

. The court or arbitrator shall increase or decrease the amount of prejudgment or preaward interest otherwise payable in a judgment or award in foreign money to the extent required by the law of this state governing a failure to make or accept an offer of settlement or offer of judgment, or conduct by a party or its attorney causing undue delay or expense.

. A judgment or award on a foreign-money claim bears interest at the rate applicable to judgments of this state.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1091.SL.pdf?cite=1991%20c%20153%20§%209[1991 c 153 § 9]; ]

== 6.44.100 - Enforcement of foreign judgments.
. If an action is brought to enforce a judgment of another jurisdiction expressed in a foreign money and the judgment is recognized in this state as enforceable, the enforcing judgment must be entered as provided in RCW 6.44.070, whether or not the foreign judgment confers an option to pay in an equivalent amount of United States dollars.

. A foreign judgment may be filed or docketed in accordance with any rule or statute of this state providing a procedure for its recognition and enforcement.

. A satisfaction or partial payment made upon the foreign judgment, on proof thereof, must be credited against the amount of foreign money specified in the judgment, notwithstanding the entry of judgment in this state.

. A judgment entered on a foreign-money claim only in United States dollars in another state must be enforced in this state in United States dollars only.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1091.SL.pdf?cite=1991%20c%20153%20§%2010[1991 c 153 § 10]; ]

== 6.44.110 - Determining United States dollar value of foreign-money claims for limited purposes.
. Computations under this section are for the limited purposes of this section and do not affect computation of the United States dollar equivalent of the money of the judgment for the purpose of payment.

. For the limited purpose of facilitating the enforcement of provisional remedies in an action, the value in United States dollars of assets to be seized or restrained pursuant to a writ of attachment, garnishment, execution, or other legal process, the amount of United States dollars at issue for assessing costs, or the amount of United States dollars involved for a surety bond or other court-required undertaking, must be ascertained as provided in subsections (3) and (4) of this section.

. A party seeking process, costs, bond, or other undertaking under subsection (2) of this section, shall compute in United States dollars the amount of the foreign money claimed from a bank-offered spot rate prevailing at or near the close of business on the banking day next preceding the filing of a request or application for the issuance of process or for the determination of costs, or an application for a bond or other court-required undertaking.

. A party seeking the process, costs, bond, or other undertaking under subsection (2) of this section shall file with each request or application an affidavit or certificate executed in good faith by its counsel or a bank officer, stating the market quotation used and how it was obtained, and setting forth the calculation. Affected court officials incur no liability, after a filing of the affidavit or certificate, for acting as if the judgment were in the amount of United States dollars stated in the affidavit or certificate.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1091.SL.pdf?cite=1991%20c%20153%20§%2011[1991 c 153 § 11]; ]

== 6.44.120 - Effect of currency revalorization.
. If, after an obligation is expressed or a loss is incurred in a foreign money, the country issuing or adopting that money substitutes a new money in place of that money, the obligation or the loss is treated as if expressed or incurred in the new money at the rate of conversion the issuing country establishes for the payment of like obligations or losses denominated in the former money.

. If substitution under subsection (1) of this section occurs after a judgment or award is entered on a foreign-money claim, the court or arbitrator shall amend the judgment or award by a like conversion of the former money.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1091.SL.pdf?cite=1991%20c%20153%20§%2012[1991 c 153 § 12]; ]

== 6.44.130 - Supplementary general principles of law.
Unless displaced by particular provisions of this chapter, the principles of law and equity, including the law merchant, and the law relative to capacity to contract, principal and agent, estoppel, fraud, misrepresentation, duress, coercion, mistake, bankruptcy, or other validating or invalidating causes supplement its provisions.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1091.SL.pdf?cite=1991%20c%20153%20§%2013[1991 c 153 § 13]; ]

== 6.44.140 - Uniformity of application and construction.
This chapter shall be applied and construed to effectuate its general purpose to make uniform the law with respect to the subject of this chapter among states enacting it.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1091.SL.pdf?cite=1991%20c%20153%20§%2014[1991 c 153 § 14]; ]

== 6.44.901 - Short title.
This chapter may be cited as the uniform foreign-money claims act.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1091.SL.pdf?cite=1991%20c%20153%20§%2015[1991 c 153 § 15]; ]

== 6.44.902 - Effective date—1991 c 153.
This chapter shall take effect January 1, 1992.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1091.SL.pdf?cite=1991%20c%20153%20§%2016[1991 c 153 § 16]; ]

== 6.44.904 - Prospective application.
This chapter applies prospectively only and not retroactively. It applies only to causes of action which are commenced on or after January 1, 1992.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1091.SL.pdf?cite=1991%20c%20153%20§%2018[1991 c 153 § 18]; ]

