= 44.05 - Washington state redistricting act.
:toc:

== 44.05.010 - Short title.
This act may be cited as the Washington State Redistricting Act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c16.pdf?cite=1983%20c%2016%20§%201[1983 c 16 § 1]; ]

== 44.05.020 - Definitions.
The definitions set forth in this section apply throughout this chapter, unless the context requires otherwise.

. "Chief election officer" means the secretary of state.

. "Federal census" means the decennial census required by federal law to be prepared by the United States bureau of the census in each year ending in zero.

. "Lobbyist" means an individual required to register with the Washington public disclosure commission pursuant to RCW 42.17A.600.

. "Plan" means a plan for legislative and congressional redistricting mandated by Article II, section 43 of the state Constitution.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1048-S.SL.pdf?cite=2011%20c%2060%20§%2041[2011 c 60 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c16.pdf?cite=1983%20c%2016%20§%202[1983 c 16 § 2]; ]

== 44.05.030 - Redistricting commission—Membership—Chairperson—Vacancies.
A redistricting commission shall be established in January of each year ending in one to accomplish state legislative and congressional redistricting. The five-member commission shall be appointed as follows:

. Each legislative leader of the two largest political parties in each house of the legislature shall appoint one voting member to the commission by January 15th of each year ending in one.

. The four legislators appointing commission members pursuant to this section shall certify their appointments to the chief election officer. If an appointing legislator does not certify an appointment by January 15th of each year ending in one, within five days the supreme court shall certify an appointment to the chief election officer.

. No later than January 31st of the year of their selection, the four appointed members, by an affirmative vote of at least three, shall appoint and certify to the chief election officer the nonvoting fifth member who shall act as the commission's chairperson. If by January 31st of the year of their selection three of the four voting members fail to elect a chairperson, the supreme court shall within five days certify an appointment to the chief election officer. A vacancy on the commission shall be filled by the person who made the initial appointment, or their successor, within fifteen days after the vacancy occurs.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c13.pdf?cite=1984%20c%2013%20§%201[1984 c 13 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c16.pdf?cite=1983%20c%2016%20§%203[1983 c 16 § 3]; ]

== 44.05.040 - Oath.
Before serving on the commission every person shall take and subscribe an oath to faithfully perform the duties of that office. The oath shall be filed in the office of the secretary of state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c16.pdf?cite=1983%20c%2016%20§%204[1983 c 16 § 4]; ]

== 44.05.050 - Members—Persons ineligible to serve.
No person may serve on the commission who:

. Is not a registered voter of the state at the time of selection; or

. Is or has within one year prior to selection been a registered lobbyist; or

. Is or has within two years prior to selection been an elected official or elected legislative district, county, or state party officer. The provisions of this subsection do not apply to the office of precinct committeeperson.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c13.pdf?cite=1984%20c%2013%20§%202[1984 c 13 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c16.pdf?cite=1983%20c%2016%20§%205[1983 c 16 § 5]; ]

== 44.05.060 - Members—Political activities prohibited.
No member of the commission may:

. Campaign for elective office while a member of the commission;

. Actively participate in or contribute to any political campaign of any candidate for state or federal elective office while a member of the commission; or

. Hold or campaign for a seat in the state house of representatives, the state senate, or congress for two years after the effective date of the plan.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c13.pdf?cite=1984%20c%2013%20§%203[1984 c 13 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c16.pdf?cite=1983%20c%2016%20§%206[1983 c 16 § 6]; ]

== 44.05.070 - Employment of personnel—Assistance of state officials—Witness expenses—Appropriations—Compensation.
. The commission may employ the services of experts, consultants, and support staff, including attorneys not employed by the attorney general, as necessary to carry out its duties pursuant to this chapter.

. The chief election officer, the treasurer, and the attorney general shall make available to the commission such personnel, facilities, and other assistance as the commission may reasonably request. The chief election officer shall be the official recipient of all provisional and preliminary census data and maps, and shall forward such data and maps, upon request, to the commission.

. The commission, upon written request by a witness and subject to rules promulgated by the commission, may reimburse witnesses for their necessary expenses incurred in appearing before the commission.

. The legislature shall appropriate funds to enable the commission to carry out its duties. Members shall receive one hundred dollars of compensation for each day spent in the performance of their duties. Compensation of employees shall be determined by the commission. The provisions of RCW 43.03.050 and 43.03.060 shall apply to both the members and the employees of the commission.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c16.pdf?cite=1983%20c%2016%20§%207[1983 c 16 § 7]; ]

== 44.05.080 - Duties.
In addition to other duties prescribed by law, the commission shall:

. Adopt rules pursuant to the Administrative Procedure Act, chapter 34.05 RCW, to carry out the provisions of Article II, section 43 of the state Constitution and of this chapter, which rules shall provide that three voting members of the commission constitute a quorum to do business, and that the votes of three of the voting members are required for any official action of the commission;

. Act as the legislature's recipient of the final redistricting data and maps from the United States Bureau of the Census;

. Comply with requirements to disclose and preserve public records as specified in chapters 40.14 and 42.56 RCW;

. Hold open meetings pursuant to the open public meetings act, chapter 42.30 RCW;

. Prepare and disclose its minutes pursuant to RCW 42.30.035;

. Be subject to the provisions of RCW 42.17A.700;

. Prepare and publish a report with the plan; the report will be made available to the public at the time the plan is published. The report will include but will not be limited to: (a) The population and percentage deviation from the average district population for every district; (b) an explanation of the criteria used in developing the plan with a justification of any deviation in a district from the average district population; (c) a map of all the districts; and (d) the estimated cost incurred by the counties for adjusting precinct boundaries;

. Adopt a districting plan for a noncharter county with a population of four hundred thousand or more, pursuant to RCW 36.32.054.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2887-S.SL.pdf?cite=2018%20c%20301%20§%2010[2018 c 301 § 10]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5316.SL.pdf?cite=2017%203rd%20sp.s.%20c%2025%20§%2033[2017 3rd sp.s. c 25 § 33]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1048-S.SL.pdf?cite=2011%20c%2060%20§%2042[2011 c 60 § 42]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20303[2005 c 274 § 303]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c16.pdf?cite=1983%20c%2016%20§%208[1983 c 16 § 8]; ]

== 44.05.090 - Redistricting plan.
In the redistricting plan:

. Districts shall have a population as nearly equal as is practicable, excluding nonresident military personnel, based on the population reported in the federal decennial census as adjusted by RCW 44.05.140.

. To the extent consistent with subsection (1) of this section the commission plan should, insofar as practical, accomplish the following:

.. District lines should be drawn so as to coincide with the boundaries of local political subdivisions and areas recognized as communities of interest. The number of counties and municipalities divided among more than one district should be as small as possible;

.. Districts should be composed of convenient, contiguous, and compact territory. Land areas may be deemed contiguous if they share a common land border or are connected by a ferry, highway, bridge, or tunnel. Areas separated by geographical boundaries or artificial barriers that prevent transportation within a district should not be deemed contiguous; and

.. Whenever practicable, a precinct shall be wholly within a single legislative district.

. The commission's plan and any plan adopted by the supreme court under RCW 44.05.100(4) shall provide for forty-nine legislative districts.

. The house of representatives shall consist of ninety-eight members, two of whom shall be elected from and run at large within each legislative district. The senate shall consist of forty-nine members, one of whom shall be elected from each legislative district.

. The commission shall exercise its powers to provide fair and effective representation and to encourage electoral competition. The commission's plan shall not be drawn purposely to favor or discriminate against any political party or group.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5287-S2.SL.pdf?cite=2019%20c%20456%20§%202[2019 c 456 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c126.pdf?cite=1990%20c%20126%20§%201[1990 c 126 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c16.pdf?cite=1983%20c%2016%20§%209[1983 c 16 § 9]; ]

== 44.05.100 - Submission of plan to legislature—Amendment—Effect—Adoption by supreme court, when.
. Upon approval of a redistricting plan by three of the voting members of the commission, but not later than November 15th of the year ending in one, the commission shall submit the plan to the legislature.

. After submission of the plan by the commission, the legislature shall have the next thirty days during any regular or special session to amend the commission's plan. If the legislature amends the commission's plan the legislature's amendment must be approved by an affirmative vote in each house of two-thirds of the members elected or appointed thereto, and may not include more than two percent of the population of any legislative or congressional district.

. The plan approved by the commission, with any amendment approved by the legislature, shall be final upon approval of such amendment or after expiration of the time provided for legislative amendment by subsection (2) of this section whichever occurs first, and shall constitute the districting law applicable to this state for legislative and congressional elections, beginning with the next elections held in the year ending in two. This plan shall be in force until the effective date of the plan based upon the next succeeding federal decennial census or until a modified plan takes effect as provided in RCW 44.05.120(6).

. If three of the voting members of the commission fail to approve and submit a plan within the time limitations provided in subsection (1) of this section, the supreme court shall adopt a plan by April 30th of the year ending in two. Any such plan approved by the court is final and constitutes the districting law applicable to this state for legislative and congressional elections, beginning with the next election held in the year ending in two. This plan shall be in force until the effective date of the plan based on the next succeeding federal decennial census or until a modified plan takes effect as provided in RCW 44.05.120(6).

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5502-S.SL.pdf?cite=2019%20c%20192%20§%201[2019 c 192 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6296.SL.pdf?cite=2002%20c%204%20§%201[2002 c 4 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5764-S.SL.pdf?cite=1995%20c%2088%20§%201[1995 c 88 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c16.pdf?cite=1983%20c%2016%20§%2010[1983 c 16 § 10]; ]

== 44.05.110 - Cessation of operations—Financial statement—Official record.
. Following the period provided by RCW 44.05.100(1) for the commission's adoption of a plan, the commission shall take all necessary steps to conclude its business and cease operations. The commission shall prepare a financial statement disclosing all expenditures made by the commission. The official record shall contain all relevant information developed by the commission pursuant to carrying out its duties under this chapter, maps, data collected, minutes of meetings, written communications, and other information of a similar nature. Once the commission ceases to exist, the chief election officer shall be the custodian of the official record for purposes of reprecincting and election administration. The chief election officer shall provide for the permanent preservation of this official record pursuant to chapter 42.56 RCW and Title 40 RCW. Once the commission ceases to exist any budget surplus shall revert to the state general fund.

. Except as provided in RCW 44.05.120 for a reconvened commission, the commission shall cease to exist on July 1st of each year ending in two unless the supreme court extends the commission's term.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1048-S.SL.pdf?cite=2011%20c%2060%20§%2043[2011 c 60 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c16.pdf?cite=1983%20c%2016%20§%2011[1983 c 16 § 11]; ]

== 44.05.120 - Reconvening of commission to modify plan.
. If a commission has ceased to exist, the legislature may, upon an affirmative vote in each house of two-thirds of the members elected or appointed thereto, adopt legislation reconvening the commission for the purpose of modifying the redistricting plan.

. RCW 44.05.050 governs the eligibility of persons to serve on the reconvened commission. A vacancy involving a voting member of the reconvened commission shall be filled by the person who made the initial appointment, or their successor, within fifteen days after the effective date of the legislation reconvening the commission. A vacancy involving the nonvoting member of the commission shall be filled by an affirmative vote of at lease [least] three of four voting members, within fifteen days after all other vacancies are filled or, if no other vacancies exist, within fifteen days after the effective date of the legislation reconvening the commission. A subsequent vacancy on a reconvened commission shall be filled by the person or persons who made the initial appointment, or their successor, within fifteen days after the vacancy occurs. If any appointing authority fails to make a required appointment within the time limitations established by this subsection, within five days after that date the supreme court shall make the required appointment.

. The provisions of RCW 44.05.070 and 44.05.080 are applicable if a commission is reconvened under this section.

. The commission shall complete the modification to the redistricting plan as soon as possible, but no later than sixty days after the effective date of the legislation reconvening the commission. At least three of the voting members shall approve the modification to the redistricting plan.

. Following approval of a modification to the redistricting plan by the commission, the legislature has the next thirty days during any regular or special session to amend the commission's modification. Any amendment by the legislature must be approved by an affirmative vote in each house of two-thirds of the members elected or appointed thereto. No amendment by the legislature may include more than two percent of the population of any legislative or congressional district contained in the commission's modification.

. The commission's modification to the redistricting plan, with any amendments approved by the legislature, shall be final upon approval of the amendments or after expiration of the time provided for legislative amendment by subsection (5) of this section, whichever occurs first.

. Following the period provided by subsection (4) of this section for the commission's approval of a modification to the redistricting plan, the commission shall take all necessary steps to conclude its business and cease operations in accordance with RCW 44.05.110(1). A reconvened commission shall cease to exist ninety days after the effective date of the legislation reconvening the commission, unless the supreme court extends the commission's term.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c16.pdf?cite=1983%20c%2016%20§%2012[1983 c 16 § 12]; ]

== 44.05.130 - Challenges to plan.
After the plan takes effect as provided in RCW 44.05.100, any registered voter may file a petition with the supreme court challenging the plan. After a modification to the redistricting plan takes effect as provided in RCW 44.05.120, any registered voter may file a petition with the supreme court challenging the amended plan. The court may consolidate any or all petitions and shall give all such petitions precedence over all other matters.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c16.pdf?cite=1983%20c%2016%20§%2013[1983 c 16 § 13]; ]

== 44.05.140 - Residence of certain individuals—Last known place of residence.
. After April 1st of each year ending in zero, and by July 1st of each year ending in zero, the department of corrections shall furnish to the redistricting commission the following information regarding the last known place of residence of each inmate incarcerated in a state adult correctional facility:

.. A unique identifier, other than the inmate's department of corrections number; and

.. Last known place of residence information sufficiently specific to determine the congressional and state legislative districts in which the inmate's last known place of residence is located.

. After April 1st of each year ending in zero, and by July 1st of each year ending in zero, the department of social and health services shall furnish to the redistricting commission the following information regarding the last known place of residence of each person committed to receive involuntary behavioral health treatment under chapter 71.05 RCW:

.. A unique identifier, other than the person's patient identification number; and

.. Last known place of residence information sufficiently specific to determine the congressional and state legislative districts in which the resident's last known place of residence is located.

. After April 1st of each year ending in zero, and by July 1st of each year ending in zero, the department of children, youth, and families shall furnish to the redistricting commission the following information regarding the last known place of residence of each person residing or placed in a juvenile justice facility:

.. A unique identifier, other than the person's patient identification number; and

.. Last known place of residence information sufficiently specific to determine the congressional and state legislative districts in which the resident's last known place of residence is located.

. The redistricting commission shall:

.. Deem each inmate incarcerated in a state adult correctional facility and person residing or placed in a juvenile justice facility or committed to receive involuntary behavioral health treatment under chapter 71.05 RCW as residing at his or her last known place of residence, rather than at the institution of his or her incarceration, residence, or placement;

.. Regardless of the form in which the information is furnished, refrain from publishing any information regarding a specific inmate's or resident's last known place of residence;

.. Deem an inmate or resident in state custody in Washington whose last known place of residence is outside of Washington or whose last known place of residence cannot be determined to reside at the location of the facility in which the inmate or resident is incarcerated, placed, or committed; and

.. Adjust race and ethnicity data in districts, wards, and precincts in a manner that reflects the inclusion of inmates and residents in the population count of the district, ward, or precinct of their last known place of residence.

. For purposes of this section:

.. "Inmate incarcerated in a state adult correctional facility" includes an inmate who has been transferred to a facility outside of Washington to complete his or her term of incarceration.

.. "Last known place of residence" means the address at which the inmate or resident was last domiciled prior to his or her placement or current term of incarceration, as reported by the inmate or resident.

.. "Person residing or placed in a juvenile justice facility" and "person committed to receive involuntary behavioral health treatment under chapter 71.05 RCW" include a person who has been transferred to a facility outside of Washington.

.. "Resident" means persons residing or placed in a juvenile justice facility or committed to receive involuntary behavioral health treatment under chapter 71.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5287-S2.SL.pdf?cite=2019%20c%20456%20§%201[2019 c 456 § 1]; ]

== 44.05.900 - Contingent effective date—1983 c 16.
This act shall take effect if the proposed amendment to Article II of the state Constitution establishing a commission for state legislative and congressional redistricting is validly submitted to and is approved and ratified by the voters at a general election held in November, 1983. If the proposed amendment is not so approved and ratified, this act shall be null and void in its entirety.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c16.pdf?cite=1983%20c%2016%20§%2018[1983 c 16 § 18]; ]

