= 44.16 - Legislative inquiry.
:toc:

== 44.16.010 - Examination of witnesses—Compulsory process.
Every chair or presiding member of any committee of either the senate or house of representatives, or any joint committee of the senate or house of representatives, which, by the terms of its appointment, shall be authorized to send for persons and papers, shall have power, under the direction of such committee, to issue compulsory process for the attendance of any witness within the state whom the committee may wish to examine.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%206003[2009 c 549 § 6003]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c6.pdf?cite=1895%20c%206%20§%201[1895 c 6 § 1]; RRS § 8178; ]

== 44.16.020 - Service of process.
All process provided for in this chapter may be served in the same manner as is provided by law for the service of process in the superior court; and it shall be the duty of any officer to whom any process may be delivered or issued, to serve the same as directed: PROVIDED, That in the service of process a copy thereof shall be delivered to the witness.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c6.pdf?cite=1895%20c%206%20§%2015[1895 c 6 § 15]; RRS § 8192; ]

== 44.16.030 - Chair to administer oaths.
The chair or presiding member of any committee of either the senate, house of representatives, or any joint committee thereof, shall be authorized to administer oaths to all witnesses coming before such committee for examination; and all witnesses who shall testify in any proceeding provided for in this chapter, shall be under oath or affirmation.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%206004[2009 c 549 § 6004]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c6.pdf?cite=1895%20c%206%20§%202[1895 c 6 § 2]; RRS § 8179; ]

== 44.16.040 - Commission to examine absent witness.
Every such chair or presiding member shall also have power, under the direction of the committee, to issue a commission for the examination of any witness who shall be without the jurisdiction of the state, or if within the state, shall be unable to attend, or who shall, for any reasons, be excused by the committee from attendance.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%206005[2009 c 549 § 6005]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c6.pdf?cite=1895%20c%206%20§%203[1895 c 6 § 3]; RRS § 8180; ]

== 44.16.050 - Commission executed during recess.
Whenever such committee shall obtain authority for that purpose, from the senate or house, or legislature, by which it may be appointed, it may issue such commission to be executed during the recess of the legislature.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c6.pdf?cite=1895%20c%206%20§%204[1895 c 6 § 4]; RRS § 8181; ]

== 44.16.060 - To whom directed—Interrogatories.
Every such commission shall be directed to such magistrate or other person, as the committee may designate, and interrogatories framed by the committee shall be annexed thereto.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c6.pdf?cite=1895%20c%206%20§%205[1895 c 6 § 5]; RRS § 8182; ]

== 44.16.070 - Oath and powers of commissioner.
The person to whom such commission shall be directed, if he or she reside within the state and accept the trust, shall, before entering upon the execution of his or her duties, take the oath of office prescribed in the Constitution. Such commissioner shall have power to issue process to compel the attendance of witnesses, whom he or she shall be required to examine, and shall have power to administer oaths to such witnesses.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%206006[2009 c 549 § 6006]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c6.pdf?cite=1895%20c%206%20§%206[1895 c 6 § 6]; RRS § 8183; ]

== 44.16.080 - Examination to be private.
Unless otherwise directed by the committee, it shall in all cases be the duty of the commissioner to examine, in private, every witness attending before him or her, and not to make public the particulars of such examination, when so made in private, until the same shall be made public by order of the house or legislature appointing the committee.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%206007[2009 c 549 § 6007]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c6.pdf?cite=1895%20c%206%20§%207[1895 c 6 § 7]; RRS § 8184; ]

== 44.16.090 - Testimony reduced to writing.
Every witness so attending shall be examined on oath or affirmation, and his or her testimony shall be reduced to writing by the commissioner, or by some disinterested person in his or her presence and under the direction of said commissioner, and signed by the witness.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%206008[2009 c 549 § 6008]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c6.pdf?cite=1895%20c%206%20§%208[1895 c 6 § 8]; RRS § 8185; ]

== 44.16.100 - Return of depositions.
When a commission shall have been duly executed, the commissioner shall annex thereto the depositions of the witnesses, duly certified by him or her, and shall, without delay, transmit the same by mail, inclosed [enclosed] and under seal, or deliver the same, to the chair of the committee by which the commission shall have been issued, or to such person as by the committee directed.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%206009[2009 c 549 § 6009]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c6.pdf?cite=1895%20c%206%20§%209[1895 c 6 § 9]; RRS § 8186; ]

== 44.16.110 - Fees of commissioner and witnesses.
A person executing any such commission shall be paid, out of the state treasury, the same fees that are allowed by law for the taking of depositions on commissions issued out of the superior courts of this state; and any witness attending before either house of the legislature, or any committee or joint committee thereof, or before any such commissioner, shall be so paid two dollars per day for each day in attendance, and five cents a mile for the distance necessarily traveled in attending as such witness.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c6.pdf?cite=1895%20c%206%20§%2010[1895 c 6 § 10]; RRS § 8187; ]

== 44.16.120 - Punishment of recalcitrant witness.
Any person who shall fail to attend as a witness upon any committee appointed by either the house or senate of the state of Washington, or both, after having been duly subpoenaed as provided in this chapter, or who, being in attendance as a witness before such committee, shall refuse to answer any question or produce any paper or document or book which he or she is required to answer or to produce by such committee, shall be deemed guilty of a misdemeanor, and upon conviction thereof shall be fined in any sum not exceeding five hundred dollars, or by imprisonment in the county jail for a term not longer than six months, or by both such fine and imprisonment.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%206010[2009 c 549 § 6010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1897c33.pdf?cite=1897%20c%2033%20§%201[1897 c 33 § 1]; RRS § 8194; ]

== 44.16.130 - Failure to attend—Contempt.
A person who, being duly summoned to attend as a witness before either house of the legislature, or any committee or joint committee thereof, or commissioner authorized to summon witnesses, refuses or neglects, without lawful excuse, to attend pursuant to such summons, shall be punished as for contempt, as hereinafter provided.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c6.pdf?cite=1895%20c%206%20§%2011[1895 c 6 § 11]; RRS § 8188; ]

== 44.16.140 - Refusal to testify—Contempt.
A person who, being present before either house of the legislature, or any committee or joint committee thereof, or commissioner authorized to summon witnesses, wilfully refuses to be sworn or affirmed, or to answer any material and proper question, or to produce, upon reasonable notice, any material and proper books, papers or documents in his or her possession or under his or her control, shall be punished as for contempt, as hereinafter provided.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%206011[2009 c 549 § 6011]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c6.pdf?cite=1895%20c%206%20§%2012[1895 c 6 § 12]; RRS § 8189; ]

== 44.16.150 - Punishment for contempt.
Any person being in contempt, as hereinbefore provided, shall be punished by fine in any sum not less than fifty dollars and not exceeding one thousand dollars, or by imprisonment in the county jail in the county where such examination is being had, for any period of time not extending beyond the legislative session then being held, or by both such fine and imprisonment, as the legislative body which authorized such examination may order. And in case the contempt arises in a joint proceeding of both houses, or before a joint committee thereof, the senate shall prescribe the penalty.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c6.pdf?cite=1895%20c%206%20§%2013[1895 c 6 § 13]; RRS § 8190; ]

== 44.16.160 - Warrant of imprisonment.
If any fine is imposed against any person for contempt, as hereinbefore provided, he or she shall stand committed to the county jail of the county in which the offense was committed until such fine is paid. The presiding officer of the house, fixing the fine, shall issue a warrant to the sheriff of the county where the offense was committed, commanding him or her to imprison such person in the county jail until such fine is paid, or until he or she has been imprisoned in such jail one day for every three dollars of such fine.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%206012[2009 c 549 § 6012]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c6.pdf?cite=1895%20c%206%20§%2014[1895 c 6 § 14]; RRS § 8191; ]

== 44.16.170 - Record of proceedings.
Every such committee shall keep a record of its proceedings under the provisions of this chapter, which record shall be signed by the chair or presiding officer of the committee, and the same returned to the legislative body by which the committee was appointed, as a part of the report of such committee.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%206013[2009 c 549 § 6013]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c6.pdf?cite=1895%20c%206%20§%2016[1895 c 6 § 16]; RRS § 8193; ]

