= 44.20 - Session laws.
:toc:

== 44.20.010 - Engrossed bills filed with secretary of state.
Whenever any bill shall have passed both houses, the house transmitting the enrolled bill to the governor shall also file with the secretary of state the engrossed bill, together with the history of such bill up to the time of transmission to the governor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c136.pdf?cite=1907%20c%20136%20§%201[1907 c 136 § 1]; RRS § 8196; ]

== 44.20.020 - Chapter numbers—Bill copies certified, delivered—Citation by number and year.
Whenever any bill shall become a law the secretary of state shall number such bill in the order in which it became a law, commencing with each session of the legislature, and shall forthwith certify and deliver three copies of such bill to the statute law committee. Such number shall be in Arabic numerals, and shall be the chapter number of the act when published. A citation to the chapter number and year of the session laws heretofore or hereafter published shall be a sufficient reference to the act so designated.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c6.pdf?cite=1969%20c%206%20§%201[1969 c 6 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c136.pdf?cite=1907%20c%20136%20§%202[1907 c 136 § 2]; RRS § 8197; ]

== 44.20.030 - Session laws—Separate copies to be available.
The statute law committee, after every legislative session, whether regular or special, shall have available, on demand, for temporary use separate copies of each act filed in the office of secretary of state within ten days after the filing thereof.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6208.SL.pdf?cite=2006%20c%2046%20§%201[2006 c 46 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c32.pdf?cite=1982%201st%20ex.s.%20c%2032%20§%203[1982 1st ex.s. c 32 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c6.pdf?cite=1969%20c%206%20§%202[1969 c 6 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c21.pdf?cite=1961%20c%2021%20§%201[1961 c 21 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933ex1c31.pdf?cite=1933%20ex.s.%20c%2031%20§%201[1933 ex.s. c 31 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c27.pdf?cite=1933%20c%2027%20§%201[1933 c 27 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c35.pdf?cite=1925%20ex.s.%20c%2035%20§%201[1925 ex.s. c 35 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c136.pdf?cite=1907%20c%20136%20§%203[1907 c 136 § 3]; RRS § 8198; ]

== 44.20.050 - Publication of session laws—Headings, index.
When all of the acts of any session of the legislature and initiative measures enacted by the people since the next preceding session have been certified to the statute law committee, the code reviser employed by the statute law committee shall make the proper headings and index of such acts or laws and, after such work has been completed, the statute law committee shall have published on the code reviser or legislative web site within seventy-five days after final adjournment of the legislature for that year and publish as many paper sets as deemed necessary by the committee of such acts and laws, with such headings and indexes, and such other matter as may be deemed essential, including a title page showing the session at which such acts were passed, the date of convening and adjournment of the session, and any other matter deemed proper, including a certificate by the secretary of state of such referendum measures as may have been enacted by the people since the next preceding session.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1479.SL.pdf?cite=2011%20c%20156%20§%206[2011 c 156 § 6]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6208.SL.pdf?cite=2006%20c%2046%20§%202[2006 c 46 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c32.pdf?cite=1982%201st%20ex.s.%20c%2032%20§%204[1982 1st ex.s. c 32 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c6.pdf?cite=1969%20c%206%20§%204[1969 c 6 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c157.pdf?cite=1951%20c%20157%20§%2018[1951 c 157 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c27.pdf?cite=1915%20c%2027%20§%201[1915 c 27 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c136.pdf?cite=1907%20c%20136%20§%205[1907 c 136 § 5]; RRS § 8200; ]

== 44.20.060 - Duty of code reviser in arranging laws.
In arranging the laws, memorials and resolutions for publication, the code reviser is hereby authorized to make such corrections in the orthography, clerical errors and punctuation of the same as in his or her judgment shall be deemed essential: PROVIDED, That when any words or clauses shall be inserted, the same shall be inclosed [enclosed] in brackets; and no correction shall be made which changes the intent or meaning of any sentence, section or act of the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%206014[2009 c 549 § 6014]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c6.pdf?cite=1969%20c%206%20§%205[1969 c 6 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c632.pdf?cite=1890%20p%20632%20§%208[1890 p 632 § 8]; RRS § 8203; ]

== 44.20.080 - Private publication restricted.
It shall be unlawful for any person to print and publish for sale the session laws of any session in book form within one year after the adjournment of such session, other than those ordered printed by the statute law committee, or to deliver to anyone other than such committee or upon their order any of the session laws so ordered printed by them: PROVIDED, This section shall not apply to any general compilation of the laws of this state or to a compilation of any special laws or laws on any special subject.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c6.pdf?cite=1969%20c%206%20§%206[1969 c 6 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c136.pdf?cite=1907%20c%20136%20§%206[1907 c 136 § 6]; RRS § 8201; ]

