= 44.82 - Joint select committee on health care oversight.
:toc:

== 44.82.010 - Joint select committee on health care oversight.
. The joint select committee on health care oversight is established in statute, continuing the committee created in Engrossed Substitute Senate Concurrent Resolution No. 8401 passed in 2013.

. The membership of the joint select committee on health care oversight must consist of the following: (a) The chairs of the health care committees of the senate and the house of representatives, who must serve as cochairs; (b) four additional members of the senate, two each appointed by the leadership of the two largest political parties in the senate; and (c) four additional members of the house of representatives, two each appointed by the leadership of the two largest political parties in the house of representatives. The governor must be invited to appoint, as a liaison to the joint select committee, a person who must be a nonvoting member.

. The joint select committee on health care oversight must provide oversight between the health care authority, health benefit exchange, the office of the insurance commissioner, the department of health, and the department of social and health services. The goal must be to ensure that these entities are not duplicating their efforts and are working toward a goal of increased quality of services which will lead to reduced costs to the health care consumer.

. The joint select committee on health care oversight must, as necessary, propose legislation to the health care committees and budget recommendations to the ways and means committees of the legislature that aids in their coordination of activities and that leads to better quality and cost savings.

. The joint select committee on health care oversight expires on December 31, 2022.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2572-S2.SL.pdf?cite=2014%20c%20223%20ยง%203[2014 c 223 ยง 3]; ]

