= 30B.20 - State trust companies—Trust deposits and common trust funds.
:toc:

== 30B.20.005 - General prohibition on deposit taking.
Except as authorized by this chapter or other governing law, a trust company may not take or hold deposits of funds in this state unless:

. It is authorized to do business in this state as a depository institution; and

. Complies with all applicable federal and state laws and regulations respecting the taking and handling of monetary deposits.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20360[2014 c 37 § 360]; ]

== 30B.20.010 - Trust deposits as a client investment—Security fund.
. The director may establish by rule a plan for the safe and sound deposit of trust funds by a state trust company with itself as an investment, if:

.. The investment of the trust deposits is authorized in writing by the settlor or the beneficiary;

.. The state trust company maintains as security for the trust deposits a separate fund of securities, which are permissible for trust investments, under control of a federal reserve bank or a clearing corporation, either in this state or elsewhere;

.. The total market value of the security is at all times at least equal to the amount of the deposit;

.. The separate fund is designated as security for trust deposits;

.. The separate fund is maintained under the control of a bank or government agency; and

.. The state trust company complies with such other terms and conditions as the director may establish by rule in the interest of safety and soundness and protection of the public.

. A state trust company may make periodic withdrawals from or additions to the securities fund required by subsection (1) of this section as long as the required value is maintained.

. Income from the securities in the fund belongs to the state trust company.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20361[2014 c 37 § 361]; ]

== 30B.20.020 - Common trust funds—Collective investment funds.
. Consistent with RCW 11.102.010, a state trust company may establish common trust funds to provide investment to itself as a fiduciary.

. The director may adopt rules to administer and carry out this section and RCW 11.102.010, including but not limited to rules to establish investment and participation limitations, disclosure of fees, audit requirements, limit or expand investment authority for particular classes or categories of securities or other property, advertising, exemptions, and other requirements that may be necessary to carry out this section.

. A state trust company that invests in a collective investment fund shall make investments as required by RCW 30B.24.030 and in conformity with the contents of the state trust company's written statement of principles of trust management, pursuant to RCW 30B.24.040, as adopted by the board and subject to approval of the department. A state trust company shall also comply with RCW 30B.24.020 in avoiding conflicts of interest and self-dealing in relation to a collective investment fund.

. Unless otherwise prescribed by the director by rule, a state trust company shall be required to establish and maintain collective investment funds the same as required for a federally insured state bank with authorized trust powers, taking into account federal rules applicable to a federally insured state bank in relation to a collective trust fund that require a written plan and specific requirements for fund management including, without limitation, provision for proportionate interests, methods and frequency of valuation of all or portions of the fund, admission and withdrawal of accounts, methods of distribution, segregation of investments, audit and financial reports related to the collective investment fund, advertising restrictions, management fees, expenses, and prohibition against certificates.

. Notwithstanding the general use of the term "affiliate" in this title as defined in RCW 30B.04.005, nothing in this chapter shall be construed as exempting or modifying a requirement of a state trust institution with respect to RCW 11.102.010.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=2019%20c%20389%20§%2040[2019 c 389 § 40]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20362[2014 c 37 § 362]; ]

