= 30B.98 - Construction.
:toc:

== 30B.98.001 - Legislative declarations.
See RCW 30A.04.005.

[ ]

== 30B.98.003 - Effective date—2014 c 37.
See RCW 30A.04.902.

[ ]

== 30B.98.005 - Continuation of existing law.
The provisions of this title, insofar as they are substantially the same as statutory provisions repealed by chapter 37, Laws of 2014 and relating to the same subject matter, shall be construed as restatements and continuations, and not as new enactments.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20403[2014 c 37 § 403]; ]

== 30B.98.010 - Title, chapter, section headings not part of law.
Title headings, chapter or subchapter headings, and section or subsection headings as used in this title do not constitute any part of the law.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20404[2014 c 37 § 404]; ]

== 30B.98.020 - Prior investments or transactions not affected.
This title does not affect the legality of investments, made prior to January 5, 2015, or of transactions had before January 5, 2015, pursuant to any provisions of law in force when such investments were made or transactions had.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20406[2014 c 37 § 406]; ]

