= 30B.04 - General provisions.
:toc:

== 30B.04.002 - Short title.
This title may be known and cited as the Washington trust institutions act.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20301[2014 c 37 § 301]; ]

== 30B.04.005 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this title.

The definitions in this section shall be liberally construed to accomplish the purposes of this title. Additional definitions, as applicable, are contained elsewhere in this title. The department may adopt by rule other definitions to accomplish the purposes of this title.

. "Account" means the client relationship established with a trust company involving the transfer of funds or property to the trust company, including a relationship in which the trust company acts as trustee, executor, administrator, guardian, custodian, conservator, bailee, receiver, registrar, or agent, but excluding a relationship in which the trust company acts solely in an advisory capacity.

. "Administer" with respect to real or tangible personal property means, as an agent or in another representative capacity, to possess, purchase, sell, lease, insure, safekeep, or otherwise manage the property.

. "Affiliate" means a company that controls, is controlled by, or is under common control with a trust institution.

. "Agent" has the same meaning as an agent at common law.

. "Authorized trust institution" means a trust institution with authority to engage in trust business in Washington state pursuant to federal or state law.

. "Bank" has the meaning set forth in 12 U.S.C. Sec. 1813(h); provided that the term "bank" does not include any "foreign bank" as defined in 12 U.S.C. Sec. 3101(7), except for any such foreign bank organized under the laws of a territory of the United States, Puerto Rico, Guam, American Samoa, or the Virgin Islands, the deposits of which are insured by the federal deposit insurance corporation.

. "Bank supervisory agency" means:

.. Any agency of another state with primary responsibility for chartering and supervising a trust institution; and

.. The office of the comptroller of the currency, the federal deposit insurance corporation, the board of governors of the federal reserve system, and any successor to these agencies.

. "Capital" has the meaning ascribed to that term by generally accepted accounting principles and applicable rules of the financial accounting standards board, and includes surplus and undivided profits.

. "Charter," "chartered," and "chartering" mean a charter or other certificate of authority issued by a financial services supervisory agency of an applicable governmental entity authorizing a trust institution to engage in business in its home state or other jurisdiction, or the act of granting or having had granted such a charter.

. "Client" means a person to whom a trust institution owes a duty or obligation under a trust or other account administered by the trust institution or as an advisor or agent, regardless of whether the trust institution owes a fiduciary duty to the person. The term includes the noncontingent beneficiaries of an account.

. "Company" includes a bank, trust company, corporation, limited liability company, partnership, association, business trust, or another trust.

. "Conservator" means the director or an agent of the director exercising the powers and duties provided in RCW 30B.46.060.

. "Control," "controls," "controlled," and "controlling," except as defined in RCW 30B.53.005 and as used in RCW 30B.04.040(12), 30B.08.030, 30B.12.020 (1) and (2), and 30B.38.080(1), mean and refer to:

.. The ownership of or ability or power to vote, directly, acting through one or more other persons, or otherwise indirectly, more than fifty percent of the outstanding shares of a class of voting securities of a state trust company or other company;

.. The ability to control the election of a majority of the board of a state trust company or other company;

.. The power to exercise, directly or indirectly, a controlling influence over the management or policies of the state trust company or other company as determined by the director after notice and an opportunity for hearing; or

.. The conditioning of the transfer of more than fifty percent of the outstanding shares or participation shares of a class of voting securities of a state trust company or other company on the transfer of more than fifty percent of the outstanding shares of a class of voting securities of another state trust company or other company.

. "Custodial account" means an account, established by a person with a bank as defined in 26 U.S.C. Sec. 408(n), or with another person approved by the internal revenue service as satisfying the requirements to be a nonbank trustee or a nonbank passive trustee set forth in United States treasury regulations under 26 U.S.C. Sec. 408, that is governed by an instrument concerning the establishment or maintenance, or both, of an individual retirement account, qualified retirement plan, Archer medical savings account, health savings account, Coverdell education savings account, any similar retirement or savings vehicle permitted under the internal revenue code of 1986, or as otherwise defined by the director by rule.

. "Department" means the Washington state department of financial institutions.

. "Depository institution" means any company chartered to act as a fiduciary and included for any purpose within any of the definitions of "insured depository institution" as set forth in 12 U.S.C. Sec. 1813(c)(2) and (3).

. "Director" means the director of the Washington state department of financial institutions.

. "Federal trust institution" means a special purpose national banking association authorized by the office of the comptroller of the currency, pursuant to the national bank act, 12 U.S.C. Sec. 92a, whose charter is granted for the purpose of it engaging primarily or solely in trust or other fiduciary activities.

. "Fiduciary record" means a matter written, transcribed, recorded, received, or otherwise in the possession or control of a trust company, whether in physical or electronic form, that is necessary to preserve information concerning an act or event relevant to an account or a client of a trust company.

. "Foreign bank" means a foreign bank, as defined in section 1(b)(7) of the international banking act of 1978, chartered to act as a fiduciary in a state other than Washington state. As used in this title, "foreign bank" excludes an alien bank authorized to do business in Washington state under chapter 30A.42 RCW.

. "Home state" means:

.. With respect to a federally chartered trust institution and a foreign bank, the state in which such institution maintains its principal office; and

.. With respect to any other trust institution, the state which chartered such institution.

. "Home state regulator" means the trust institutions supervisory agency with primary responsibility for chartering and supervising an out-of-state trust institution.

. "Host state" means a state, other than the home state of a trust institution, or a foreign country in which the trust institution maintains or seeks to acquire or establish an office.

. "Insolvent" means a circumstance or condition in which a state trust company:

.. Has actual cash market value of its assets which are insufficient to pay its liabilities to its creditors;

.. Is unable or lacks the means to meet its current obligations as they come due in the regular and ordinary course of business, even if the value of its assets exceeds its liabilities;

.. Sells or attempts to sell substantially all of its assets other than as provided in RCW 30B.44A.050 or merges or attempts to merge substantially all of its assets or business with another entity other than as provided by chapter 30B.53 RCW; or

.. Attempts to dissolve or liquidate without approval of the director under chapter 30B.44A RCW;

.. After demand in writing by the director, fails to cure any deficiency in its reserves as required by statute or rule;

.. After written demand by the director, the stockholders fail to cure within the time prescribed by the director an impairment of the state trust company's capital or surplus; or

.. Is insolvent within the meaning of the United States bankruptcy code.

. "Instrument" means a revocable or irrevocable trust document created inter vivos or testamentary or any custodial account agreement.

. "Internet trust business" means a trust business that holds itself out as a trustee or fiduciary to the general public of Washington state by means of the internet or other electronic means.

. "Law firm" means a professional service corporation, professional limited liability company, or limited liability partnership, that is duly organized under the laws of Washington state and whose shareholders, members, or partners, respectively, are exclusively attorneys.

. "Limited liability trust company" means an entity organized or reorganized under the provisions of RCW 30B.08.020 to operate as a state trust company in limited liability company form pursuant to the authority of the director under chapter 30B.08 RCW.

. "Loans and extensions of credit" means direct or indirect advances of funds by a state trust company to a person that are conditioned on the obligation of the person to repay the funds or that are repayable from specific property pledged by or on behalf of the person.

. "Manager" means a person elected to the board of a limited liability trust company.

. "Officer" means the presiding officer of the board, the principal executive officer, or another officer appointed by the board of a state trust company or other company, or a person or group of persons acting in a comparable capacity for the state trust company or other company.

. "Out-of-state trust institution" means a trust institution that is not a state trust company under this title.

. "Person" means an individual, a company, or any other legal entity.

. "Principal shareholder" means a person who owns or has the ability or power to vote, directly, acting through one or more other persons, or otherwise indirectly, ten percent or more of the outstanding shares or participation shares of any class of voting securities of a state trust company or other company.

. "Private trust" has the meaning set forth in RCW 30B.64.005.

. "Private trust company" has the meaning set forth in RCW 30B.64.005.

. "Share" means a unit into which a proprietary interest of a trust institution is divided or subdivided by means of class, series, relative rights, or preferences, and includes beneficial interests in a state trust company organized as a corporation or limited liability company.

. "Shareholder" means the holder of a share as defined in this section.

. "State" means a state of the United States, the District of Columbia, a territory of the United States, Puerto Rico, Guam, American Samoa, the Trust Territory of the Pacific Islands, the Virgin Islands, and the Northern Mariana Islands.

. "State bank" means a bank authorized under Title 30A or 32 RCW to engage in trust business or an alien bank chartered or authorized under chapter 30A.42 RCW to exercise trust powers in Washington state.

. "State trust company" means a corporation or a limited liability company organized or reorganized under this title, including a trust company organized under the laws of Washington state before January 5, 2015.

. "State trust institution," as used in chapter 30B.10 RCW, means a state trust company or an out-of-state trust institution engaged in trust business in Washington state.

. "Third-party service provider" includes an independent contractor or other person, which a trust institution has engaged to perform services to facilitate the conduct of its business as a trust institution or affiliate, to perform the following functions:

.. Noninternet-based data storage;

.. Internet-related services, mobile applications, system and software development and maintenance, and security architecture, maintenance, and monitoring;

.. Data processing services;

.. Fiduciary activities or other contracted-for services constituting "trust business" under RCW 30B.04.005;

.. Activities related to the trading of securities, derivatives, and other commodities;

.. Bookkeeping, accounting, or similar functions; or

.. Data analytics with respect to customers or prospective customers, or use of algorithmic technology by the trust institution in the conduct of fiduciary management.

. "Trust business" means the performance of, or holding out by, a person to the public by advertisement, solicitation, or other means that the person is available to perform one or more of the essential functions of trust business set forth in RCW 30B.08.080(1).

. "Trust company" means a state trust company or any other company chartered to act as a fiduciary that is neither a depository institution nor a foreign bank.

. "Trust department" means a division, subdivision, department, or group of officers and employees of a state bank authorized by the board of directors of the state bank to exercise trust powers pursuant to authority of the director granted pursuant to RCW 30A.08.150 or 32.08.210, as applicable.

. "Trust deposits" means the client funds held by a state trust company and authorized to be deposited with itself pending investment, distribution, or payment of debts on behalf of the client.

. "Trust institution" means a depository institution or foreign bank engaged in trust business, or a trust company.

. "Unauthorized trust activity" means to engage in trust business in Washington state without authority or exemption under this title.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=2019%20c%20389%20§%202[2019 c 389 § 2]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20302[2014 c 37 § 302]; ]

== 30B.04.010 - Name of trust institution—Use of trust in name.
. A state trust company or out-of-state trust institution may register any name with the department in connection with establishing an office or otherwise engaged in trust business in Washington state pursuant to this title, except that the director may determine that a name proposed to be registered is potentially misleading to the public and require the registrant to select a name which is not potentially misleading.

. Use of "trust" as part of a person's name or fictitious trade name, or as part of a trademark or service mark in connection with transacting business with the public, or as part of advertising by any person to the public, is subject to the prohibitions and restrictions under RCW 30A.04.020.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=2019%20c%20389%20§%203[2019 c 389 § 3]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20303[2014 c 37 § 303]; ]

== 30B.04.020 - Rules—Administration and interpretation of title.
. The director has the power to adopt rules, as he or she determines necessary and appropriate, to implement the purposes and provisions of this title in accordance with the administrative procedure act, chapter 34.05 RCW.

. The director has the power, and broad administrative discretion, to administer and interpret the provisions of this title to facilitate the delivery of trust business and fiduciary services to the citizens of the state of Washington by trust businesses and other persons.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20304[2014 c 37 § 304]; ]

== 30B.04.030 - Persons authorized to act as a fiduciary.
Subject to the conditions, restrictions, limitations, and requirements of this title, the following persons are authorized trust institutions in Washington state:

. A state trust company with a certificate of authority from the director to exercise the powers of a state trust company pursuant to chapter 30B.08 RCW;

. A state bank under Title 30A RCW exercising trust business powers under the authority of the director;

. A state bank under Title 32 RCW exercising trust business powers under the authority of the director;

. A *state savings association organized under Title 33 RCW exercising trust business powers under authority of Title 33 RCW as permitted by the director;

. A national bank authorized by the comptroller of the currency to act as a fiduciary in this state pursuant to 12 U.S.C. Sec. 92a;

. A federally chartered savings bank or *savings association authorized by the comptroller of the currency to act as a fiduciary in this state;

. An out-of-state state-chartered bank with a branch in this state established or maintained pursuant to and with trust powers under applicable law of a home state;

. An out-of-state trust institution with a trust office authorized by the director pursuant to this title;

. An alien bank under chapter 30A.42 RCW authorized by the director to act as a fiduciary or engage in trust business in this state pursuant to this title;

. A private trust or private trust company exempt from the regulation of the department under chapter 30B.64 RCW; or

. An exempt person under this title pursuant to RCW 30B.04.040.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20305[2014 c 37 § 305]; ]

== 30B.04.040 - Activities not requiring certificate of authority or approval under this title.
A person is exempt from the requirement of a certificate of authority or approval under this title if the person is:

. An individual, sole proprietor, or general partnership or joint venture composed of individuals;

. Engaging in business in Washington state (a) as a national banking association or (b) as a federal mutual savings bank, federal stock savings bank, or federal savings and loan association under authority of the office of the comptroller of the currency;

. Acting in a manner otherwise authorized by law and within the scope of authority as an agent of a trust institution with respect to an activity which is not an unauthorized trust activity;

. Acting as a fiduciary solely by reason of being appointed by a court to perform the duties of a trustee, guardian, conservator, or receiver;

. While holding oneself out to the public as an attorney-at-law, law firm, or limited license legal technician, performing a service customarily performed as an attorney-at-law, law firm, or limited license legal technician in a manner approved and authorized by the supreme court of the state of Washington;

. Acting as an escrow agent pursuant to the escrow agent registration act, chapter 18.44 RCW, or in one's capacity as an authorized title agent under Title 48 RCW;

. Acting as trustee under a deed of trust delivered only as security for the payment of money or for the performance of another act;

. Receiving and distributing rents and proceeds of sale as a licensed real estate broker on behalf of a principal in a manner authorized by the Washington department of licensing;

. Engaging in a commodities or securities transaction or providing an investment advisory service in the capacity of a registered broker-dealer, investment advisor, or registered representative thereof, provided the activity is regulated by the department, the United States commodities futures trading commission, or the United States securities and exchange commission;

. Engaging in the sale and administration of an insurance product by an insurance company or agent licensed by the office of the insurance commissioner to the extent that the activity is regulated by the office of the insurance commissioner;

. Acting as trustee under a voting trust as provided by Washington state law;

. Acting as trustee by a public, private, or independent institution of higher education or a university system authorized under Washington state law, including its affiliated foundations or corporations, with respect to endowment funds or other funds owned, controlled, provided to, or otherwise made available to such institution with respect to its educational or research purposes;

. Acting as a private trust or private trust company to the extent exempt from regulation of the department as set forth in chapter 30B.64 RCW; or

. Engaging in other activities expressly excluded from the application of this title by rule of the director.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=2019%20c%20389%20§%204[2019 c 389 § 4]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20306[2014 c 37 § 306]; ]

== 30B.04.050 - Persons subject to the requirement of a certificate of authority or approval under this title.
. A person may not engage in unauthorized trust activity in this state. 

. As a condition of engaging in trust business in this state, an out-of-state trust institution is required to obtain approval from the director and is subject to all other requirements of chapter 30B.38 RCW.

. As a condition of engaging in trust business in this state, a person, other than an out-of-state trust institution or an exempt person under RCW 30B.04.040, is required to organize and obtain a certificate of authority as a state trust company pursuant to chapter 30B.08 RCW.

. A person who violates the requirements of subsection (2) or (3) of this section, as applicable, engages in unauthorized trust activity and is subject to enforcement by the director as set forth in chapter 30B.10 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20307[2014 c 37 § 307]; ]

== 30B.04.060 - Confidentiality of examination information.
This title does not limit the privileges, immunities, and requirements of RCW 42.56.400(6), 30A.04.075, 32.04.220, and 33.04.110 in relation to trust companies, state banks, and state savings associations.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20308[2014 c 37 § 308]; ]

== 30B.04.070 - Limits on loans to insiders and affiliates—Exceptions.
. A state trust company may not make loans or extensions of credit, nor extend leases, to any person except in relation to nonfiduciary corporate funds and only as set forth in this section.

. Unless authorized by subsection (4) of this section, a state trust company may make loans or leases to insiders only to the extent permitted for state banks under federal reserve board regulation O, 12 C.F.R. Part 215.

. Unless authorized by subsection (4) of this section, a state trust company may make loans or leases to affiliates as may be reasonably determined by the director by rule. In the absence of rule making to the contrary, the director shall be guided by sections 23a and 23b of the federal reserve act, 12 U.S.C. Secs. 371c and 371c-1, and federal reserve board regulation W, 12 C.F.R. Part 223, governing the permissibility of loans and leases to affiliates by state banks that are members of the federal reserve.

. Notwithstanding any other provision of this section, a state trust company may make loans or extensions of credit, or extend leases, in relation to nonfiduciary corporate funds, subject to approval of the director upon written application.

. The director may adopt rules interpreting this section and may impose further conditions and restrictions on loans and extensions of credit by state trust companies not inconsistent with this section.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20309[2014 c 37 § 309]; ]

== 30B.04.080 - Transactions in state trust company shares.
. A state trust company may acquire its own shares if:

.. The amount of its capital is sufficient to fully absorb the acquisition of the shares under regulatory accounting principles; or

.. The state trust company obtains the prior written approval of the director.

. A state trust company may acquire a lien upon its own shares if:

.. The aggregate amount of indebtedness so secured is less than the amount of the state trust company's capital; or

.. The state trust company obtains the prior written approval of the director.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20310[2014 c 37 § 310]; ]

== 30B.04.090 - Investment of corporate funds—Securities.
A state trust company may invest its nonfiduciary corporate funds in investments other than real estate, including securities, that are permissible for state banks under Title 30A RCW, and as may be made applicable for state trust companies by rule of the director.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20311[2014 c 37 § 311]; ]

== 30B.04.100 - Investment in corporations—Subsidiaries.
Except as otherwise provided by this chapter or rules adopted under this chapter, a state trust company may invest in corporations, limited liability companies, and other entities, and may acquire or establish a *subsidiary to conduct any activity that may lawfully be conducted through the form of organization chosen for the *subsidiary, in accordance with that which is permissible for state banks under RCW 30A.04.125 and 30A.04.127.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20312[2014 c 37 § 312]; ]

== 30B.04.110 - Pledge of assets.
A state trust company may not pledge or create a lien on any of its assets except to secure the repayment of money borrowed or as specifically authorized by RCW 30B.20.010, or by rule, or by a finding of the director that such conduct does not violate any other applicable law and serves the convenience of the state trust company and the public. An act, deed, conveyance, pledge, or contract in violation of this section is void.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=2019%20c%20389%20§%205[2019 c 389 § 5]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20313[2014 c 37 § 313]; ]

== 30B.04.120 - Investment in state trust company facilities.
A state trust company may purchase, hold, and convey real estate, including facilities, for the purposes permissible for state banks under RCW 30A.04.210.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20314[2014 c 37 § 314]; ]

== 30B.04.130 - Separation of trust records—Recordkeeping.
. A state trust company shall keep its fiduciary records separate and distinct from other records of the state trust company.

. The fiduciary records must contain all material information relative to each account as appropriate under the circumstances.

. A state trust company shall comply with all other conditions and requirements for state banks engaging in trust business and the deposit of securities as set forth in RCW 30A.04.240.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20315[2014 c 37 § 315]; ]

== 30B.04.140 - Legal services, advertising of—Penalty.
RCW 30A.04.260 applies to this title.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20316[2014 c 37 § 316]; ]

== 30B.04.160 - Choice of law clauses.
When there is a choice of law clause contained in a governing instrument in which a state trust company is a party, the choice of law of any state agreed to by the parties to such instrument shall control the interpretation and enforcement of the trust or custodial agreement comprising such instrument.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20318[2014 c 37 § 318]; ]

== 30B.04.170 - Choice of law when instrument silent.
Except as set forth in RCW 30B.04.160, choice of law is governed by RCW 11.98.005.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20319[2014 c 37 § 319]; ]

== 30B.04.180 - Public notice by electronic means.
. Notwithstanding any provisions of this title, wherever notice by publication is required by a trust institution, such notice may be undertaken by internet publication upon terms and conditions that the director may prescribe by rule.

. Notice to shareholders required under this title may be undertaken by electronic means in the same manner as permitted for general business corporations under RCW 23B.01.410.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20320[2014 c 37 § 320]; ]

