= 61.30 - Real estate contract forfeitures.
:toc:

== 61.30.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Contract" or "real estate contract" means any written agreement for the sale of real property in which legal title to the property is retained by the seller as security for payment of the purchase price. "Contract" or "real estate contract" does not include earnest money agreements and options to purchase.

. "Cure the default" or "cure" means to perform the obligations under the contract which are described in the notice of intent to forfeit and which are in default, to pay the costs and attorneys' fees prescribed in the contract, and, subject to RCW 61.30.090(1), to make all payments of money required of the purchaser by the contract which first become due after the notice of intent to forfeit is given and are due when cure is tendered.

. "Declaration of forfeiture" means the notice described in RCW 61.30.070(2).

. "Forfeit" or "forfeiture" means to cancel the purchaser's rights under a real estate contract and to terminate all right, title, and interest in the property of the purchaser and of persons claiming by or through the purchaser, all to the extent provided in this chapter, because of a breach of one or more of the purchaser's obligations under the contract. A judicial foreclosure of a real estate contract as a mortgage shall not be considered a forfeiture under this chapter.

. "Notice of intent to forfeit" means the notice described in RCW 61.30.070(1).

. "Property" means that portion of the real property which is the subject of a real estate contract, legal title to which has not been conveyed to the purchaser.

. "Purchaser" means the person denominated in a real estate contract as the purchaser of the property or an interest therein or, if applicable, the purchaser's successors or assigns in interest to all or any part of the property, whether by voluntary or involuntary transfer or transfer by operation of law. If the purchaser's interest in the property is subject to a proceeding in probate, a receivership, a guardianship, or a proceeding under the federal bankruptcy laws, "purchaser" means the personal representative, the receiver, the guardian, the trustee in bankruptcy, or the debtor in possession, as applicable. However, "purchaser" does not include an assignee or any other person whose only interest or claim is in the nature of a lien or other security interest.

. "Required notices" means the notice of intent to forfeit and the declaration of forfeiture.

. "Seller" means the person denominated in a real estate contract as the seller of the property or an interest therein or, if applicable, the seller's successors or assigns in interest to all or any part of the property or the contract, whether by voluntary or involuntary transfer or transfer by operation of law. If the seller's interest in the property is subject to a proceeding in probate, a receivership, a guardianship, or a proceeding under the federal bankruptcy laws, "seller" means the personal representative, the receiver, the guardian, the trustee in bankruptcy, or the debtor in possession, as applicable. However, "seller" does not include an assignee or any other person whose only interest or claim is in the nature of a lien or other security interest and does not include an assignee who has not been conveyed legal title to any portion of the property.

. "Time for cure" means the time provided in RCW 61.30.070(1)(e) as it may be extended as provided in this chapter or any longer period agreed to by the seller.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c86.pdf?cite=1988%20c%2086%20§%201[1988 c 86 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c237.pdf?cite=1985%20c%20237%20§%201[1985 c 237 § 1]; ]

== 61.30.020 - Forfeiture or foreclosure—Notices—Other remedies not limited.
. A purchaser's rights under a real estate contract shall not be forfeited except as provided in this chapter. Forfeiture shall be accomplished by giving and recording the required notices as specified in this chapter. This chapter shall not be construed as prohibiting or limiting any remedy which is not governed or restricted by this chapter and which is otherwise available to the seller or the purchaser. At the seller's option, a real estate contract may be foreclosed in the manner and subject to the law applicable to the foreclosure of a mortgage in this state.

. The seller's commencement of an action to foreclose the contract as a mortgage shall not constitute an election of remedies so as to bar the seller from forfeiting the contract under this chapter for the same or different breach. Similarly, the seller's commencement of a forfeiture under this chapter shall not constitute an election of remedies so as to bar the seller from foreclosing the contract as a mortgage. However, the seller shall not maintain concurrently an action to foreclose the contract and a forfeiture under this chapter whether for the same or different breaches. If, after giving or recording a notice of intent to forfeit, the seller elects to foreclose the contract as a mortgage, the seller shall record a notice canceling the notice of intent to forfeit which refers to the notice of intent by its recording number. Not later than ten days after the notice of cancellation is recorded, the seller shall mail or serve copies of the notice of cancellation to each person who was mailed or served the notice of intent to forfeit, and shall post it in a conspicuous place on the property if the notice of intent was posted. The seller need not publish the notice of cancellation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c86.pdf?cite=1988%20c%2086%20§%202[1988 c 86 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c237.pdf?cite=1985%20c%20237%20§%202[1985 c 237 § 2]; ]

== 61.30.030 - Conditions to forfeiture.
It shall be a condition to forfeiture of a real estate contract that:

. The contract being forfeited, or a memorandum thereof, is recorded in each county in which any of the property is located;

. A breach has occurred in one or more of the purchaser's obligations under the contract and the contract provides that as a result of such breach the seller is entitled to forfeit the contract; and

. Except for petitions for the appointment of a receiver, no arbitration or judicial action is pending on a claim made by the seller against the purchaser on any obligation secured by the contract.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c86.pdf?cite=1988%20c%2086%20§%203[1988 c 86 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c237.pdf?cite=1985%20c%20237%20§%203[1985 c 237 § 3]; ]

== 61.30.040 - Notices—Persons required to be notified—Recording.
. The required notices shall be given to each purchaser last known to the seller or the seller's agent or attorney giving the notice and to each person who, at the time the notice of intent to forfeit is recorded, is the last holder of record of a purchaser's interest. Failure to comply with this subsection in any material respect shall render any purported forfeiture based upon the required notices void.

. The required notices shall also be given to each of the following persons whose interest the seller desires to forfeit if the default is not cured:

.. The holders and claimants of record at the time the notice of intent to forfeit is recorded of any interests in or liens upon all or any portion of the property derived through the purchaser or which are otherwise subordinate to the seller's interest in the property; and

.. All persons occupying the property at the time the notice of intent to forfeit is recorded and whose identities are reasonably discoverable by the seller.

Any forfeiture based upon the required notices shall be void as to each person described in this subsection (2) to whom the notices are not given in accordance with this chapter in any material respect.

. The required notices shall also be given to each person who at the time the notice of intent to forfeit is recorded has recorded in each county in which any of the property is located a request to receive the required notices, which request (a) identifies the contract being forfeited by reference to its date, the original parties thereto, and a legal description of the property; (b) contains the name and address for notice of the person making the request; and (c) is executed and acknowledged by the requesting person.

. Except as otherwise provided in the contract or other agreement with the seller and except as otherwise provided in this section, the seller shall not be required to give any required notice to any person whose interest in the property is not of record or if such interest is first acquired after the time the notice of intent to forfeit is recorded. Subject to subsection (5) of this section, all such persons hold their interest subject to the potential forfeiture described in the recorded notice of intent to forfeit and shall be bound by any forfeiture made pursuant thereto as permitted in this chapter as if the required notices were given to them.

. Before the commencement of the time for cure, the notice of intent to forfeit shall be recorded in each county in which any of the property is located. The notice of intent to forfeit shall become ineffective for all purposes one year after the expiration of the time for cure stated in such notice or in any recorded extension thereof executed by the seller or the seller's agent or attorney unless, prior to the end of that year, the declaration of forfeiture based on such notice or a lis pendens incident to an action under this chapter is recorded. The time for cure may not be extended in increments of more than one year each, and extensions stated to be for more than one year or for an unstated or indefinite period shall be deemed to be for one year for the purposes of this subsection. Recording a lis pendens when a notice of intent to forfeit is effective shall cause such notice to continue in effect until the later of one year after the expiration of the time for cure or thirty days after final disposition of the action evidenced by the lis pendens.

. The declaration of forfeiture shall be recorded in each county in which any of the property is located after the time for cure has expired without the default having been cured.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c86.pdf?cite=1988%20c%2086%20§%204[1988 c 86 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c237.pdf?cite=1985%20c%20237%20§%204[1985 c 237 § 4]; ]

== 61.30.050 - Notices—Form—Method of service.
. The required notices shall be given in writing. The notice of intent to forfeit shall be signed by the seller or by the seller's agent or attorney. The declaration of forfeiture shall be signed and sworn to by the seller. The seller may execute the declaration of forfeiture through an agent under a power of attorney which is of record at the time the declaration of forfeiture is recorded, but in so doing the seller shall be subject to liability under RCW 61.30.150 to the same extent as if the seller had personally signed and sworn to the declaration.

. The required notices shall be given:

.. In any manner provided in the contract or other agreement with the seller; and

.. By either personal service in the manner required for civil actions in any county in which any of the property is located or by mailing a copy to the person for whom it is intended, postage prepaid, by certified or registered mail with return receipt requested and by regular first-class mail, addressed to the person at the person's address last known to the seller or the seller's agent or attorney giving the notice. For the purposes of this subsection, the seller or the seller's agent or attorney giving the notice may rely upon the address stated in any recorded document which entitles a person to receive the required notices unless the seller or the seller's agent or attorney giving the notice knows such address to be incorrect.

If the address or identity of a person for whom the required notices are intended is not known to or reasonably discoverable at the time the notice is given by the seller or the seller's agent or attorney giving the notice, the required notices shall be given to such person by posting a copy in a conspicuous place on the property and publishing a copy thereof. The notice shall be directed to the attention of all persons for whom the notice is intended, including the names of the persons, if so known or reasonably discoverable. The publication shall be made in a newspaper approved pursuant to RCW 65.16.040 and published in each county in which any of the property is located or, if no approved newspaper is published in the county, in an adjoining county, and if no approved newspaper is published in the county or adjoining county, then in an approved newspaper published in the capital of the state. The notice of intent to forfeit shall be published once a week for two consecutive weeks. The declaration of forfeiture shall be published once.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c86.pdf?cite=1988%20c%2086%20§%205[1988 c 86 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c237.pdf?cite=1985%20c%20237%20§%205[1985 c 237 § 5]; ]

== 61.30.060 - Notice of intent to forfeit—Declaration of forfeiture—Time limitations.
The notice of intent to forfeit shall be given not later than ten days after it is recorded. The declaration of forfeiture shall be given not later than three days after it is recorded. Either required notice may be given before it is recorded, but the declaration of forfeiture may not be given before the time for cure has expired. Notices which are served or mailed are given for the purposes of this section when served or mailed. Notices which must be posted and published as provided in RCW 61.30.050(2)(b) are given for the purposes of this section when both posted and first published.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c86.pdf?cite=1988%20c%2086%20§%206[1988 c 86 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c237.pdf?cite=1985%20c%20237%20§%206[1985 c 237 § 6]; ]

== 61.30.070 - Notice of intent to forfeit—Declaration of forfeiture—Contents.
. The notice of intent to forfeit shall contain the following:

.. The name, address, and telephone number of the seller and, if any, the seller's agent or attorney giving the notice;

.. A description of the contract, including the names of the original parties to the contract, the date of the contract, and the recording number of the contract or memorandum thereof;

.. A legal description of the property;

.. A description of each default under the contract on which the notice is based;

.. A statement that the contract will be forfeited if all defaults are not cured by a date stated in the notice which is not less than ninety days after the notice of intent to forfeit is recorded or any longer period specified in the contract or other agreement with the seller;

.. A statement of the effect of forfeiture, including, to the extent applicable that: (i) All right, title, and interest in the property of the purchaser and, to the extent elected by the seller, of all persons claiming through the purchaser or whose interests are otherwise subordinate to the seller's interest in the property shall be terminated; (ii) the purchaser's rights under the contract shall be canceled; (iii) all sums previously paid under the contract shall belong to and be retained by the seller or other person to whom paid and entitled thereto; (iv) all of the purchaser's rights in all improvements made to the property and in unharvested crops and timber thereon shall belong to the seller; and (v) the purchaser and all other persons occupying the property whose interests are forfeited shall be required to surrender possession of the property, improvements, and unharvested crops and timber to the seller ten days after the declaration of forfeiture is recorded;

.. An itemized statement or, to the extent not known at the time the notice of intent to forfeit is given or recorded, a reasonable estimate of all payments of money in default and, for defaults not involving the failure to pay money, a statement of the action required to cure the default;

.. An itemized statement of all other payments, charges, fees, and costs, if any, or, to the extent not known at the time the notice of intent is given or recorded, a reasonable estimate thereof, that are or may be required to cure the defaults;

.. A statement that the person to whom the notice is given may have the right to contest the forfeiture, or to seek an extension of time to cure the default if the default does not involve a failure to pay money, or both, by commencing a court action by filing and serving the summons and complaint before the declaration of forfeiture is recorded;

.. A statement that the person to whom the notice is given may have the right to request a court to order a public sale of the property; that such public sale will be ordered only if the court finds that the fair market value of the property substantially exceeds the debt owed under the contract and any other liens having priority over the seller's interest in the property; that the excess, if any, of the highest bid at the sale over the debt owed under the contract will be applied to the liens eliminated by the sale and the balance, if any, paid to the purchaser; that the court will require the person who requests the sale to deposit the anticipated sale costs with the clerk of the court; and that any action to obtain an order for public sale must be commenced by filing and serving the summons and complaint before the declaration of forfeiture is recorded;

.. A statement that the seller is not required to give any person any other notice of default before the declaration which completes the forfeiture is given, or, if the contract or other agreement requires such notice, the identification of such notice and a statement of to whom, when, and how it is required to be given; and

.. Any additional information required by the contract or other agreement with the seller.

. If the default is not cured before the time for cure has expired, the seller may forfeit the contract by giving and recording a declaration of forfeiture which contains the following:

.. The name, address, and telephone number of the seller;

.. A description of the contract, including the names of the original parties to the contract, the date of the contract, and the recording number of the contract or memorandum thereof;

.. A legal description of the property;

.. To the extent applicable, a statement that all the purchaser's rights under the contract are canceled and all right, title, and interest in the property of the purchaser and of all persons claiming an interest in all or any portion of the property through the purchaser or which is otherwise subordinate to the seller's interest in the property are terminated except to the extent otherwise stated in the declaration of forfeiture as to persons or claims named, identified, or described;

.. To the extent applicable, a statement that all persons whose rights in the property have been terminated and who are in or come into possession of any portion of the property (including improvements and unharvested crops and timber) are required to surrender such possession to the seller not later than a specified date, which shall not be less than ten days after the declaration of forfeiture is recorded or such longer period provided in the contract or other agreement with the seller;

.. A statement that the forfeiture was conducted in compliance with all requirements of this chapter in all material respects and applicable provisions of the contract;

.. A statement that the purchaser and any person claiming any interest in the purchaser's rights under the contract or in the property who are given the notice of intent to forfeit and the declaration of forfeiture have the right to commence a court action to set the forfeiture aside by filing and serving the summons and complaint within sixty days after the date the declaration of forfeiture is recorded if the seller did not have the right to forfeit the contract or fails to comply with this chapter in any material respect; and

.. Any additional information required by the contract or other agreement with the seller.

. The seller may include in either or both required notices any additional information the seller elects to include which is consistent with this chapter and with the contract or other agreement with the seller.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c86.pdf?cite=1988%20c%2086%20§%207[1988 c 86 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c237.pdf?cite=1985%20c%20237%20§%207[1985 c 237 § 7]; ]

== 61.30.080 - Failure to give required notices.
. If the seller fails to give any required notice within the time required by this chapter, the seller may record and give a subsequent notice of intent to forfeit or declaration of forfeiture, as applicable. Any such subsequent notice shall (a) include revised dates and information to the extent necessary to conform to this chapter as if the superseded notice had not been given or recorded; (b) state that it supersedes the notice being replaced; and (c) render void the previous notice which it replaces.

. If the seller fails to give the notice of intent to forfeit to all persons whose interests the seller desires to forfeit or to record such notice as required by this chapter, and if the declaration of forfeiture has not been given or recorded, the seller may give and record a new set of notices as required by this chapter. However, the new notices shall contain a statement that they supersede and replace the earlier notices and shall provide a new time for cure.

. If the seller fails to give any required notice to all persons whose interests the seller desires to forfeit or to record such notice as required by this chapter, and if the declaration of forfeiture has been given or recorded, the seller may apply for a court order setting aside the forfeiture previously made, and to the extent such order is entered, the seller may proceed as if no forfeiture had been commenced. However, no such order may be obtained without joinder and service upon the persons who were given the required notices and all other persons whose interests the seller desires to forfeit.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c86.pdf?cite=1988%20c%2086%20§%208[1988 c 86 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c237.pdf?cite=1985%20c%20237%20§%208[1985 c 237 § 8]; ]

== 61.30.090 - Acceleration of payments—Cure of default.
. Even if the contract contains a provision allowing the seller, because of a default in the purchaser's obligations under the contract, to accelerate the due date of some or all payments to be made or other obligations to be performed by the purchaser under the contract, the seller may not require payment of the accelerated payments or performance of the accelerated obligations as a condition to curing the default in order to avoid forfeiture except to the extent the payments or performance would be due without the acceleration. This subsection shall not apply to an acceleration because of a transfer, encumbrance, or conveyance of any or all of the purchaser's interest in any portion or all of the property if the contract being forfeited contains a provision accelerating the unpaid balance because of such transfer, encumbrance, or conveyance and such provision is enforceable under applicable law.

. All persons described in RCW 61.30.040 (1) and (2), regardless of whether given the notice of intent to forfeit, and any guarantor of or any surety for the purchaser's performance may cure the default. These persons may cure the default at any time before expiration of the time for cure and may act alone or in any combination. Any person having a lien of record against the property which would be eliminated in whole or in part by the forfeiture and who cures the purchaser's default pursuant to this section shall have included in its lien all payments made to effect such cure, including interest thereon at the rate specified in or otherwise applicable to the obligations secured by such lien.

. The seller may, but shall not be required to, accept tender of cure after the expiration of the time for cure and before the declaration of forfeiture is recorded. The seller may accept a partial cure. If the tender of such partial cure to the seller or the seller's agent or attorney is not accompanied by a written statement of the person making the tender acknowledging that such payment or other action does not fully cure the default, the seller shall notify such person in writing of the insufficiency and the amount or character thereof, which notice shall include an offer to refund any partial tender of money paid to the seller or the seller's agent or attorney upon written request. The notice of insufficiency may state that, by statute, such request must be made by a specified date, which date may not be less than ninety days after the notice of insufficiency is served or mailed. The request must be made in writing and delivered or mailed to the seller or the person who gave the notice of insufficiency or the notice of intent to forfeit and, if the notice of insufficiency properly specifies a date by which such request must be made, by the date so specified. The seller shall refund such amount promptly following receipt of such written request, if timely made, and the seller shall be liable to the person to whom such amount is due for that person's reasonable attorneys' fees and other costs incurred in an action brought to recover such amount in which such refund or any portion thereof is found to have been improperly withheld. If the seller's written notice of insufficiency is not given to the person making the tender at least ten days before the expiration of the time for cure, then regardless of whether the tender is accepted the time for cure shall be extended for ten days from the date the seller's written notice of insufficiency is given. The seller shall not be required to extend the time for cure more than once even though more than one insufficient tender is made.

. Except as provided in this subsection, a timely tender of cure shall reinstate the contract. If a default that entitles the seller to forfeit the contract is not described in a notice of intent to forfeit previously given and the seller gives a notice of intent to forfeit concerning that default, timely cure of a default described in a previous notice of intent to forfeit shall not limit the effect of the subsequent notice.

. If the default is cured and a fulfillment deed is not given to the purchaser, the seller or the seller's agent or attorney shall sign, acknowledge, record, and deliver or mail to the purchaser and, if different, the person who made the tender a written statement that the contract is no longer subject to forfeiture under the notice of intent to forfeit previously given, referring to the notice of intent to forfeit by its recording number. A seller who fails within thirty days of written demand to give and record the statement required by this subsection, if such demand specifies the penalties in this subsection, is liable to the person who cured the default for the greater of five hundred dollars or actual damages, if any, and for reasonable attorneys' fees and other costs incurred in an action to recover such amount or damages.

. Any person curing or intending to cure any default shall have the right to request any court of competent jurisdiction to determine the reasonableness of any attorneys' fees which are included in the amount required to cure, and in making such determination the court may award the prevailing party its reasonable attorneys' fees and other costs incurred in the action. An action under this subsection shall not forestall any forfeiture or affect its validity.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c86.pdf?cite=1988%20c%2086%20§%209[1988 c 86 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c237.pdf?cite=1985%20c%20237%20§%209[1985 c 237 § 9]; ]

== 61.30.100 - Effect of forfeiture.
. The recorded and sworn declaration of forfeiture shall be prima facie evidence of the extent of the forfeiture and compliance with this chapter and, except as otherwise provided in RCW 61.30.040 (1) and (2), conclusive evidence thereof in favor of bona fide purchasers and encumbrancers for value.

. Except as otherwise provided in this chapter or the contract or other agreement with the seller, forfeiture of a contract under this chapter shall have the following effects:

.. The purchaser, and all persons claiming through the purchaser or whose interests are otherwise subordinate to the seller's interest in the property who were given the required notices pursuant to this chapter, shall have no further rights in the contract or the property and no person shall have any right, by statute or otherwise, to redeem the property;

.. All sums previously paid under the contract by or on behalf of the purchaser shall belong to and be retained by the seller or other person to whom paid; and

.. All of the purchaser's rights in all improvements made to the property and in unharvested crops and timber thereon at the time the declaration of forfeiture is recorded shall be forfeited to the seller.

. The seller shall be entitled to possession of the property ten days after the declaration of forfeiture is recorded or any longer period provided in the contract or any other agreement with the seller. The seller may proceed under chapter 59.12 RCW to obtain such possession. Any person in possession who fails to surrender possession when required shall be liable to the seller for actual damages caused by such failure and for reasonable attorneys' fees and costs of the action.

. After the declaration of forfeiture is recorded, the seller shall have no claim against and the purchaser shall not be liable to the seller for any portion of the purchase price unpaid or for any other breach of the purchaser's obligations under the contract, except for damages caused by waste to the property to the extent such waste results in the fair market value of the property on the date the declaration of forfeiture is recorded being less than the unpaid monetary obligations under the contract and all liens or contracts having priority over the seller's interest in the property.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c86.pdf?cite=1988%20c%2086%20§%2010[1988 c 86 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c237.pdf?cite=1985%20c%20237%20§%2010[1985 c 237 § 10]; ]

== 61.30.110 - Forfeiture may be restrained or enjoined.
. The forfeiture may be restrained or enjoined or the time for cure may be extended by court order only as provided in this section. A certified copy of any restraining order or injunction may be recorded in each county in which any part of the property is located.

. Any person entitled to cure the default may bring or join in an action under this section. No other person may bring such an action without leave of court first given for good cause shown. Any such action shall be commenced by filing and serving the summons and complaint before the declaration of forfeiture is recorded. Service shall be made upon the seller or the seller's agent or attorney, if any, who gave the notice of intent to forfeit. Concurrently with commencement of the action, the person bringing the action shall record a lis pendens in each county in which any part of the property is located. A court may preliminarily enjoin the giving and recording of the declaration of forfeiture upon a prima facie showing of the grounds set forth in this section for a permanent injunction. If the court issues an order restraining or enjoining the forfeiture then until such order expires or is vacated or the court otherwise permits the seller to proceed with the forfeiture, the declaration of forfeiture shall not be given or recorded. However, the commencement of the action shall not of itself extend the time for cure.

. The forfeiture may be permanently enjoined only when the person bringing the action proves that there is no default as claimed in the notice of intent to forfeit or that the purchaser has a claim against the seller which releases, discharges, or excuses the default claimed in the notice of intent to forfeit, including by offset, or that there exists any material noncompliance with this chapter. The time for cure may be extended only when the default alleged is other than the failure to pay money, the nature of the default is such that it cannot practically be cured within the time stated in the notice of intent to forfeit, action has been taken and is diligently being pursued which would cure the default, and any person entitled to cure is ready, willing, and able to timely perform all of the purchaser's other contract obligations.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c86.pdf?cite=1988%20c%2086%20§%2011[1988 c 86 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c237.pdf?cite=1985%20c%20237%20§%2011[1985 c 237 § 11]; ]

== 61.30.120 - Sale of property in lieu of forfeiture.
. Except for a sale ordered incident to foreclosure of the contract as a mortgage, a public sale of the property in lieu of the forfeiture may be ordered by the court only as provided in this section. Any person entitled to cure the default may bring or join in an action seeking an order of public sale in lieu of forfeiture. No other person may bring such an action without leave of court first given for good cause shown.

. An action under this section shall be commenced by filing and serving the summons and complaint before the declaration of forfeiture is recorded. Service shall be made upon the seller or the seller's agent or attorney, if any, who gave the notice of intent to forfeit. Concurrently with commencement of the action, the person bringing the action shall record a lis pendens in each county in which any part of the property is located. After the commencement of an action under this section and before its dismissal, the denial of a request for a public sale, or the vacation or expiration of an order for a public sale, the declaration of forfeiture shall not be given or recorded. However, commencement of the action shall not of itself extend the time for cure.

. If the court finds the then fair market value of the property substantially exceeds the unpaid and unperformed obligations secured by the contract and any other liens having priority over the seller's interest in the property, the court may require the property to be sold after the expiration of the time for cure in whole or in parcels to pay the costs of the sale and satisfy the amount the seller is entitled to be paid from the sale proceeds. Such sale shall be for cash to the highest bidder at a public sale by the sheriff at a courthouse of the county in which the property or any contiguous or noncontiguous portion thereof is located. The order requiring a public sale of the property shall specify the amount which the seller is entitled to be paid from the sale proceeds, which shall include all sums unpaid under the contract, irrespective of the due dates thereof, and such other costs and expenses to which the seller is entitled as a result of the purchaser's default under the contract, subject to any offsets or damages to which the purchaser is entitled. The order shall require any person requesting the sale to deposit with the clerk of the court, or such other person as the court may direct, the amount the court finds will be necessary to pay all of the costs and expenses of advertising and conducting the sale, including the notices to be given under subsections (4) and (5) of this section. The court shall require such deposit to be made within seven days, and if not so made the court shall vacate its order of sale. Except as provided in subsections (6) and (8) of this section, the sale shall eliminate the interests of the persons given the notice of intent to forfeit to the same extent that such interests would have been eliminated had the seller's forfeiture been effected pursuant to such notice.

. The sheriff shall endorse upon the order the time and date when the sheriff receives it and shall forthwith post and publish the notice of sale specified in this subsection and sell the property, or so much thereof as may be necessary to discharge the amount the seller is entitled to be paid as specified in the court's order of sale. The notice of sale shall be printed or typed and contain the following information:

.. A statement that the court has directed the sheriff to sell the property described in the notice of sale and the amount the seller is entitled to be paid from the sale proceeds as specified in the court's order;

.. The caption, cause number, and court in which the order was entered;

.. A legal description of the property to be sold, including the street address if any;

.. The date and recording number of the contract;

.. The scheduled date, time, and place of the sale;

.. If the time for cure has not expired, the date it will expire and that the purchaser and other persons authorized to cure have the right to avoid the sale ordered by the court by curing the defaults specified in the notice of intent to forfeit before the time for cure expires;

.. The right of the purchaser to avoid the sale ordered by the court by paying to the sheriff, at any time before the sale, in cash, the amount which the seller would be entitled to be paid from the proceeds of the sale, as specified in the court's order; and

.. A statement that unless otherwise provided in the contract between seller and purchaser or other agreement with the seller, no person shall have any right to redeem the property sold at the sale.

The notice of sale shall be given by posting a copy thereof for a period of not less than four weeks prior to the date of sale in three public places in each county in which the property or any portion thereof is located, one of which shall be at the front door of the courthouse for the superior court of each such county, and one of which shall be placed in a conspicuous place on the property. Additionally, the notice of sale shall be published once a week for two consecutive weeks in the newspaper or newspapers prescribed for published notices in RCW 61.30.050(2)(b). The sale shall be scheduled to be held not more than seven days after the expiration of (i) the periods during which the notice of sale is required to be posted and published or (ii) the time for cure, whichever is later; however, the seller may, but shall not be required to, permit the sale to be scheduled for a later date. Upon the completion of the sale, the sheriff shall deliver a sheriff's deed to the property sold to the successful bidder.

. Within seven days following the date the notice of sale is posted on the property, the seller shall, by the means described in RCW 61.30.050(2), give a copy of the notice of sale to all persons who were given the notice of intent to forfeit, except the seller need not post or publish the notice of sale.

. Any person may bid at the sale. If the purchaser is the successful bidder, the sale shall not affect any interest in the property which is subordinate to the contract. If the seller is the successful bidder, the seller may offset against the price bid the amount the seller is entitled to be paid as specified in the court's order. Proceeds of such sale shall be first applied to any costs and expenses of sale incurred by the sheriff and the seller in excess of the deposit referred to in subsection (3) of this section, and next to the amount the seller is entitled to be paid as specified in the court's order. Any proceeds in excess of the amount necessary to pay such costs, expenses and amount, less the clerk's filing fee, shall be deposited with the clerk of the superior court of the county in which the sale took place, unless such surplus is less than the clerk's filing fee, in which event such excess shall be paid to the purchaser. The clerk shall index such funds under the name of the purchaser. Interests in or liens or claims of liens against the property eliminated by the sale shall attach to such surplus in the order of priority that they had attached to the property. The clerk shall not disburse the surplus except upon order of the superior court of such county, which order shall not be entered less than ten days following the deposit of the funds with the clerk.

. In addition to the right to cure the default within the time for cure, the purchaser shall have the right to satisfy its obligations under the contract and avoid any public sale ordered by the court by paying to the sheriff, at any time before the sale, in cash, the amount which the seller would be entitled to be paid from the proceeds of the sale as specified in the court's order plus the amount of any costs and expenses of the sale incurred by the sheriff and the seller in excess of the deposit referred to in subsection (3) of this section. If the purchaser satisfies its obligations as provided in this subsection, the seller shall deliver its fulfillment deed to the purchaser.

. Unless otherwise provided in the contract or other agreement with the seller, after the public sale provided in this section no person shall have any right, by statute or otherwise, to redeem the property and, subject to the rights of persons unaffected by the sale, the purchaser at the public sale shall be entitled to possession of the property ten days after the date of the sale and may proceed under chapter 59.12 RCW to obtain such possession.

. A public sale effected under this section shall satisfy the obligations secured by the contract, regardless of the sale price or fair value, and no deficiency decree or other judgment may thereafter be obtained on such obligations.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c86.pdf?cite=1988%20c%2086%20§%2012[1988 c 86 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c237.pdf?cite=1985%20c%20237%20§%2012[1985 c 237 § 12]; ]

== 61.30.130 - Forfeiture may proceed upon expiration of judicial order—Court may award attorneys' fees or impose conditions—Venue.
. If an order restraining or enjoining the forfeiture or an order of sale under RCW 61.30.120 expires or is dissolved or vacated at least ten days before expiration of the time for cure, the seller may proceed with the forfeiture under this chapter if the default is not cured at the end of the time for cure. If any such order expires or is dissolved or vacated or such other final disposition is made at any time later than stated in the first sentence of this subsection, the seller may proceed with the forfeiture under this chapter if the default is not cured, except the time for cure shall be extended for ten days after the final disposition or the expiration of, or entry of the order dissolving or vacating, the order.

. In actions under RCW 61.30.110 and 61.30.120, the court may award reasonable attorneys' fees and costs of the action to the prevailing party, except for such fees and costs incurred by a person requesting a public sale of the property.

. In actions under RCW 61.30.110 and 61.30.120, on the seller's motion the court may (a) require the person commencing the action to provide a bond or other security against all or a portion of the seller's damages and (b) impose other conditions, the failure of which may be cause for entry of an order dismissing the action and dissolving or vacating any restraining order, injunction, or other order previously entered.

. Actions under RCW 61.30.110, 61.30.120, or 61.30.140 shall be brought in the superior court of the county where the property is located or, if the property is located in more than one county, then in any of such counties, regardless of whether the property is contiguous or noncontiguous.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c86.pdf?cite=1988%20c%2086%20§%2013[1988 c 86 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c237.pdf?cite=1985%20c%20237%20§%2013[1985 c 237 § 13]; ]

== 61.30.140 - Action to set aside forfeiture.
. An action to set aside a forfeiture not otherwise void under RCW 61.30.040(1) may be commenced only after the declaration of forfeiture has been recorded and only as provided in this section, and regardless of whether an action was previously commenced under RCW 61.30.110.

. An action to set aside the forfeiture permitted by this section may be commenced only by a person entitled to be given the required notices under RCW 61.30.040 (1) and (2). For all persons given the required notices in accordance with this chapter, such an action shall be commenced by filing and serving the summons and complaint not later than sixty days after the declaration of forfeiture is recorded. Service shall be made upon the seller or the seller's attorney-in-fact, if any, who signed the declaration of forfeiture. Concurrently with commencement of the action, the person bringing the action shall record a lis pendens in each county in which any part of the property is located.

. The court may require that all payments specified in the notice of intent shall be paid to the clerk of the court as a condition to maintaining an action to set aside the forfeiture. All payments falling due during the pendency of the action shall be paid to the clerk of the court when due. These payments shall be calculated without regard to any acceleration provision in the contract (except an acceleration because of a transfer, encumbrance, or conveyance of the purchaser's interest in the property when otherwise enforceable) and without regard to the seller's contention the contract has been duly forfeited and shall not include the seller's costs and fees of the forfeiture. The court may make orders regarding the investment or disbursement of these funds and may authorize payments to third parties instead of the clerk of the court.

. The forfeiture shall not be set aside unless (a) the rights of bona fide purchasers for value and of bona fide encumbrancers for value of the property would not thereby be adversely affected and (b) the person bringing the action establishes that the seller was not entitled to forfeit the contract at the time the seller purported to do so or that the seller did not materially comply with the requirements of this chapter.

. If the purchaser or other person commencing the action establishes a right to set aside the forfeiture, the court shall award the purchaser or other person commencing the action actual damages, if any, and may award the purchaser or other person its reasonable attorneys' fees and costs of the action. If the court finds that the forfeiture was conducted in compliance with this chapter, the court shall award the seller actual damages, if any, and may award the seller its reasonable attorneys' fees and costs of the action.

. The seller is entitled to possession of the property and to the rents, issues, and profits thereof during the pendency of an action to set aside the forfeiture: PROVIDED, That the court may provide that possession of the property be delivered to or retained by the purchaser or some other person and may make other provisions for the rents, issues, and profits.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c86.pdf?cite=1988%20c%2086%20§%2014[1988 c 86 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c237.pdf?cite=1985%20c%20237%20§%2014[1985 c 237 § 14]; ]

== 61.30.150 - False swearing—Penalty—Failure to comply with chapter—Liability.
. Whoever knowingly swears falsely to any statement required by this chapter to be sworn is guilty of perjury and shall be liable for the statutory penalties therefor.

. A seller who records a declaration of forfeiture with actual knowledge or reason to know of a material failure to comply with any requirement of this chapter is liable to any person whose interest in the property or the contract, or both, has been forfeited without material compliance with this chapter for actual damages and actual attorneys' fees and costs of the action and, in the court's discretion, exemplary damages.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c86.pdf?cite=1988%20c%2086%20§%2015[1988 c 86 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c237.pdf?cite=1985%20c%20237%20§%2015[1985 c 237 § 15]; ]

== 61.30.160 - Priority of actions under chapter.
An action brought under RCW 61.30.110, 61.30.120, or 61.30.140 shall take precedence over all other civil actions except those described in RCW 59.12.130.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c237.pdf?cite=1985%20c%20237%20§%2016[1985 c 237 § 16]; ]

== 61.30.900 - Short title.
This chapter may be known and cited as the real estate contract forfeiture act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c237.pdf?cite=1985%20c%20237%20§%2017[1985 c 237 § 17]; ]

== 61.30.910 - Effective date—Application—1985 c 237.
This act shall take effect January 1, 1986, and shall apply to all real estate contract forfeitures initiated on or after that date, regardless of when the real estate contract was made.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c237.pdf?cite=1985%20c%20237%20§%2021[1985 c 237 § 21]; ]

== 61.30.911 - Application—1988 c 86.
This act applies to all real estate contract forfeitures initiated on or after June 9, 1988, regardless of when the real estate contract was made.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c86.pdf?cite=1988%20c%2086%20§%2016[1988 c 86 § 16]; ]

