= 60.16 - Labor liens on orchards and orchard lands.
:toc:

== 60.16.010 - Liens authorized.
Any person or corporation who shall do or cause to be done any labor upon any orchard or orchard lands, in pruning, spraying, cultivating, and caring for the same, at the request of the owner thereof, or his or her agent, shall have a lien upon such orchard and orchard lands for such work and labor so performed.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20134[2012 c 117 § 134]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c110.pdf?cite=1917%20c%20110%20§%201[1917 c 110 § 1]; RRS § 1131-1; ]

== 60.16.020 - Notice of lien—Filing—Contents—Foreclosure.
Any person or corporation claiming the benefit of this chapter, must within forty days after the close of such work or labor for each season during which such work and labor is done, file for record with the county auditor of the county in which said work and labor was performed and in which said land or part thereof is situated, a claim of lien which shall be in substance in accordance with the provisions of *RCW 60.04.060, so far as the same is applicable, which said claim of lien shall be verified as in said section provided, and such lien may be enforced in a civil action in the same manner as near as may be, as provided in *RCW 60.04.120.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c110.pdf?cite=1917%20c%20110%20§%202[1917 c 110 § 2]; RRS § 1131-2; ]

== 60.16.030 - Limitation of action to foreclose—Costs.
Any action to foreclose such claim of lien shall be brought within eight calendar months after the filing of such claim for lien as provided in RCW 60.16.020 and in any such action brought to enforce such lien, the court shall allow as part of the costs the money paid for making, filing and recording such claim of lien and a reasonable attorney's fee.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c110.pdf?cite=1917%20c%20110%20§%203[1917 c 110 § 3]; RRS § 1131-3; ]

