= 60.11 - Crop liens.
:toc:

== 60.11.010 - Definitions.
As used in this chapter, the following terms have the meanings indicated unless the context clearly requires otherwise.

. "Crop" means all products of the soil either growing or cropped, cut, or gathered which require annual planting, harvesting, or cultivating. A crop includes orchard crops, but does not include vegetation produced by the powers of nature alone, nursery stock, or vegetation intended as a permanent enhancement of the land itself.

. "Handler" means a person who prepares an orchard crop for market for the account of, or as agent for, the producer of the orchard crop, which preparation includes, but is not limited to, receiving, storing, packing, marketing, selling, or delivering the orchard crop; and who takes delivery of the orchard crop from the producer of the orchard crop or from another handler. "Handler" does not include a person who solely transports the orchard crop from the producer or another handler to another person.

. "Landlord" means a person who leases or subleases to a tenant real property upon which crops are growing or will be grown.

. "Orchard crop" means cherries, peaches, nectarines, plums or prunes, pears, apricots, and apples.

. "Secured party" and "security interest" have the same meaning as used in the Uniform Commercial Code, Title 62A RCW.

. "Supplier" includes, but is not limited to, a person who furnishes seed, furnishes and/or applies commercial fertilizer, pesticide, fungicide, weed killer, or herbicide, including spraying and dusting, upon the land of the grower or landowner, or furnishes any work or labor upon the land of the grower or landowner including tilling, preparing for the growing of crops, sowing, planting, cultivating, cutting, digging, picking, pulling, or otherwise harvesting any crop grown thereon, or in gathering, securing, or housing any crop grown thereon, or in threshing any grain or hauling to any warehouse any crop, including grain, grown thereon.

. "Lien debtor" means the person who is obligated or owes payment or other performance. If the lien debtor and the owner of the property encumbered by the crop lien or security interest are not the same person, "lien debtor" means the owner of the property encumbered by the crop lien or security interest.

. "Lienholder" means a person who, by statute, has acquired a lien on the property of the lien debtor, or such person's successor in interest.

[ 2000 c 250 § 9A-824; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5628-S.SL.pdf?cite=1991%20c%20286%20§%201[1991 c 286 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c242.pdf?cite=1986%20c%20242%20§%201[1986 c 242 § 1]; ]

== 60.11.020 - Persons entitled to crop liens—Property subject to lien.
. A landlord whose lease or other agreement with the tenant provides for cash rental payment shall have a lien upon all crops grown upon the demised land in which the landlord has an interest for payment of no more than one year's rent, where the last or only payment of such one year's rent is due or will become due within six months following the last day of harvest of the crops encumbered by the crop lien. A landlord with a crop share agreement has an interest in the growing crop which shall not be encumbered by crop liens except as provided in subsections (2) and (3) of this section.

. A supplier shall have a lien upon all crops for which the supplies are used or applied for payment of the purchase price of the supplies and/or services performed: PROVIDED, That the landlord's interest in the crop shall only be subject to the lien for the amount obligated to be paid by the landlord if prior written consent of the landlord is obtained or if the landlord has agreed in writing with the tenant to pay or be responsible for a portion of the supplies and/or services provided by the lienholder.

. A handler shall have a lien on all orchard crops delivered by the lien debtor or another handler to the handler and on all proceeds of the orchard crops for payment of: (a) All customary charges for the ordinary and necessary handling of the orchard crop, including but not limited to charges for transporting, receiving, inspecting, materials and supplies furnished, washing, waxing, sorting, packing, storing, promoting, marketing, selling, advertising, insuring, or otherwise handling the lien debtor's orchard crop; and (b) reasonable cooperative per unit retainages, and for all governmental or quasi-governmental assessments imposed by statute, ordinance, or government regulation. Charges shall not include direct or indirect advances or extensions of credit to a lien debtor.

[ 2000 c 250 § 9A-825; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5628-S.SL.pdf?cite=1991%20c%20286%20§%202[1991 c 286 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c242.pdf?cite=1986%20c%20242%20§%202[1986 c 242 § 2]; ]

== 60.11.030 - Attachment and effectiveness of lien on crops and proceeds—Filing.
. Upon the later of both: (a) Execution of the lease or other agreement, or commencement of delivery of such supplies, and/or of provision of such services giving rise to the crop lien; and (b) filing a financing statement as required by RCW 62A.9A-310 and subsection (3) of this section, the crop liens described in RCW 60.11.020 (1) and (2) shall become effective and attach to the subject crop for all sums then and thereafter due and owing the lienholder under this chapter, and those liens shall continue in all identifiable cash proceeds of the crop.

. Upon the delivery of an orchard crop by the lien debtor or another handler to a handler without the necessity of filing, the crop lien described in RCW 60.11.020(3) shall become effective and attach to and be perfected in the delivered orchard crop for all sums then and thereafter due and owing the lienholder under this chapter, and the lien shall continue and be perfected in all proceeds of the orchard crop.

. Except as provided in RCW 60.11.040(4) with respect to the lien of a landlord, and except for the lien of a handler on orchard crops as provided in RCW 60.11.020(3), the lienholder must file the required financing statement during the period after the commencement of delivery of such supplies and/or of provision of such services, but before the completion of the harvest of the crops for which the lien is claimed, or in the case of a lien for furnishing work or labor, before the end of the fortieth day after the cessation of the work or labor for which the lien is claimed. If the lienholder under the crop liens described in RCW 60.11.020 (1) or (2) is to be allowed costs, disbursements, and attorneys' fees, the lienholder must also mail a copy of such financing statement to the last known address of the debtor by certified mail, return receipt requested, within ten days after filing the financing statement.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5053.SL.pdf?cite=2001%20c%2032%20§%204[2001 c 32 § 4]; 2000 c 250 § 9A-826; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5628-S.SL.pdf?cite=1991%20c%20286%20§%203[1991 c 286 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c242.pdf?cite=1986%20c%20242%20§%203[1986 c 242 § 3]; ]

== 60.11.040 - Statement of lien—Filing—Contents—Duration.
. Within fourteen days of receipt of a written request from the lien debtor, or other person who provides the lienholder authorization from the lien debtor for such statement, the lienholder shall provide that person a statement described in subsection (2) of this section. Failure timely to provide the statement shall cause the lienholder to be liable to the person requesting for the attorneys' fees and costs incurred by that person to obtain the statement, together with damages incurred by that person due to the failure of the lienholder to provide the statement, including in the case of the lien debtor any loss resulting from the lien debtor's inability to obtain financing, or the increased costs thereof.

. The statement shall be in writing, authenticated by the claimant, and shall contain in substance the following information:

.. The name and address of the claimant;

.. The name and address of the debtor;

.. The date of commencement of performance for which the lien is claimed;

.. A description of the labor services, materials, or supplies furnished;

.. A description of the crop and its location to be charged with the lien sufficient for identification; and

.. The signature of the claimant.

. The statement need not be filed with the department of licensing.

. A lien for rent claimed by a landlord pursuant to this chapter shall be effective during the term of the lease for a period of up to five years. A financing statement for a landlord lien covering a lease term longer than five years may be continued in accordance with *RCW 62A.9A-515(4). A landlord who has a right to a share of the crop may place suppliers on notice by filing a financing statement in the same manner as provided for filing a financing statement for a landlord's lien.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1492-S.SL.pdf?cite=2011%20c%2074%20§%20704[2011 c 74 § 704]; 2000 c 250 § 9A-827; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5628-S.SL.pdf?cite=1991%20c%20286%20§%204[1991 c 286 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c229.pdf?cite=1989%20c%20229%20§%201[1989 c 229 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c242.pdf?cite=1986%20c%20242%20§%204[1986 c 242 § 4]; ]

== 60.11.050 - Priorities of liens and security interests.
. Except as provided in subsections (2), (3), (4), and (5) of this section, conflicting liens and security interests in crops and their proceeds shall rank in accordance with the time of filing.

. The lien created in RCW 60.11.020(2) in favor of any person who furnishes any work or labor upon the land of the grower or landowner shall be preferred and prior to any other lien or security interest upon the crops to which they attach including the liens described in subsections (3), (4), and (5) of this section.

. The lien created in RCW 60.11.020(3) in favor of handlers is preferred and prior to a lien or security interest described in subsection (4) or (5) of this section and to any other lien or security interest upon the orchard crops to which they attach except the liens in favor of a person who furnishes work or labor upon the land of the grower or landlord. Whenever more than one handler holds a handler's lien created by RCW 60.11.020(3) in the same orchard crop, unless the affected parties otherwise agree in writing, the later of the liens to attach has priority over all previously attached handlers' liens created by RCW 60.11.020(3).

. A lien or security interest in crops otherwise entitled to priority pursuant to subsection (1) of this section shall be subordinate to a later perfected lien or security interest incurred to produce the crop to the extent that obligations secured by such earlier perfected security interest or lien were not incurred to produce such crops.

. A lien or security interest in crops otherwise entitled to priority pursuant to subsection (1) of this section shall be subordinate to a properly perfected landlord's lien.

[ 2000 c 250 § 9A-828; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5628-S.SL.pdf?cite=1991%20c%20286%20§%205[1991 c 286 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c242.pdf?cite=1986%20c%20242%20§%205[1986 c 242 § 5]; ]

== 60.11.060 - Foreclosure and enforcement of crop lien.
Any lien created by this chapter may be foreclosed or enforced by: (1) An action in the district court having jurisdiction in the district in which the real property on which the crop in question was grown is situated in accordance with RCW 60.11.070, if the value of the claim does not exceed the jurisdictional limit of the district court provided in RCW 3.66.020; or (2) an action in the superior court having jurisdiction in the county in which the real property on which the crop in question was grown is situated in accordance with RCW 60.11.070, if the value of the claim exceeds the jurisdictional limit of the district court provided in RCW 3.66.020; or (3) summary procedure as provided in RCW 60.11.080; or (4) procedures in Part 6 of Article 9A of the Uniform Commercial Code.

[ 2000 c 250 § 9A-829; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1824-S.SL.pdf?cite=1991%20c%2033%20§%204[1991 c 33 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c242.pdf?cite=1986%20c%20242%20§%206[1986 c 242 § 6]; ]

== 60.11.070 - Judicial foreclosure.
The lienholder may proceed upon his or her lien; and if there is a separate obligation in writing to pay the same, secured by the lien, he or she may bring suit upon such separate promise. When he or she proceeds on the promise, if there is a specific agreement therein contained, for the payment of a certain sum or there is a separate obligation for the sum in addition to a decree of sale of lien property, judgment shall be rendered for the amount due upon the promise or other instrument, the payment of which is thereby secured; the decree shall direct the sale of the lien property and if the proceeds of the sale are insufficient under the execution, the sheriff is authorized to levy upon and sell other property of the lien debtor, not exempt from execution, for the sum remaining unsatisfied. In a judicial foreclosure, the court shall allow reasonable attorneys' fees and disbursements for establishing a lien.

[ 2000 c 250 § 9A-830; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c242.pdf?cite=1986%20c%20242%20§%207[1986 c 242 § 7]; ]

== 60.11.080 - Summary foreclosure.
. A lien may be summarily foreclosed by notice and sale as provided in this section. The lienholder may sell or otherwise dispose of the collateral in its existing condition or following any commercially reasonable preparation or processing. The proceeds of disposition shall be applied in the order following to:

.. The reasonable expenses of retaking, holding, preparing for sale, selling and the like, and to the extent provided for in the agreement and not prohibited by law, the reasonable attorneys' fees and legal expenses incurred by the secured party;

.. The satisfaction of indebtedness secured by the lien under which the disposition is made;

.. The satisfaction of indebtedness secured by any subordinate security interest in the collateral if written notification of demand therefor is received before distribution of the proceeds is completed. If requested by the lienholder, the holder of a subordinate security interest must seasonably furnish reasonable proof of his or her interest, and unless he or she does so, the lienholder need not comply with the demand.

. The lienholder shall account to the lien debtor for any surplus, and, unless otherwise agreed, the lien debtor is not liable for any deficiency.

. Disposition of the collateral may be by public or private proceedings and may be made by way of one or more contracts. Sale or other disposition may be as a unit or in parcels and at any time and place and on any terms but every aspect of the disposition including the method, manner, time, place, and terms must be commercially reasonable. Unless collateral is perishable or threatens to decline quickly in value or is of a type customarily sold on a recognized market, reasonable notification of the time after which any private sale or other intended disposition is to be made shall be sent by the lienholder to the lien debtor, and to any other person who has a duly filed crop lien, or who has a security interest in the collateral and has duly filed a financing statement indexed in the name of the lien debtor in this state, or who is known by the lienholder to have a security interest or crop lien in the collateral. The lienholder may buy at any public sale, and if the collateral is of a type customarily sold in a recognized market or is of a type which is the subject of widely distributed standard price quotations the lienholder may buy at private sale.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c242.pdf?cite=1986%20c%20242%20§%208[1986 c 242 § 8]; ]

== 60.11.090 - Rights and interest of purchaser for value.
When a lien is foreclosed in accordance with RCW 60.11.060, the disposition transfers to a purchaser for value all of the lien debtor's right therein and discharges the lien under which it is made and any security interest or lien subordinate thereto. The purchaser takes free of all such rights and interest even though the lienholder fails to comply with the requirements of this chapter or of any judicial proceedings under RCW 60.11.070:

. In the case of a public sale, if the purchaser has no knowledge of any defects in the sale and if he or she does not buy in collusion with the lienholder, other bidders, or the person conducting the sale; or

. In any other case, if the purchaser acts in good faith.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c242.pdf?cite=1986%20c%20242%20§%209[1986 c 242 § 9]; ]

== 60.11.100 - Redemption.
The right of the lien debtor and others to redeem collateral shall be as provided in RCW 62A.9A-623.

[ 2000 c 250 § 9A-831; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c242.pdf?cite=1986%20c%20242%20§%2010[1986 c 242 § 10]; ]

== 60.11.110 - Noncompliance with chapter—Rights of lien debtor.
If the lienholder is not proceeding in accordance with the provisions of this chapter, disposition may be ordered or restrained on appropriate terms and conditions. If the disposition has occurred the lien debtor or any person entitled to notification or whose security interest has been made known to the lienholder prior to the disposition has a right to recover from the lienholder any loss caused by a failure to comply with the provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c242.pdf?cite=1986%20c%20242%20§%2011[1986 c 242 § 11]; ]

== 60.11.120 - "Commercially reasonable."
For purposes of this chapter, "commercially reasonable" has the meaning given and shall be construed in a manner consistent with RCW 62A.9A-627.

[ 2000 c 250 § 9A-832; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c242.pdf?cite=1986%20c%20242%20§%2012[1986 c 242 § 12]; ]

== 60.11.130 - Limitation of action to foreclose.
Judicial foreclosure or summary procedure as provided in RCW 60.11.060 shall be brought within twenty-four calendar months after filing the financing statement for the lien, except: (1) In the case of a landlord lien which shall be twenty-four calendar months from the date of default on the lease, and (2) in the case of a handler's lien on a given orchard crop which shall be twenty-four calendar months from the date of default on payment of the charges described in RCW 60.11.020(3) attributable to that orchard crop. Upon expiration of such time, the claimed lien shall expire.

[ 2000 c 250 § 9A-833; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c242.pdf?cite=1986%20c%20242%20§%2013[1986 c 242 § 13]; ]

== 60.11.140 - Termination statement.
Whenever the total amount of the lien has been fully paid and as otherwise provided in RCW 62A.9A-513 (c) and (d), within twenty days following receipt of an authenticated demand following such full payment of the lien, the lienholder filing a lien shall send to the lien debtor or file with the department of licensing a termination statement for the financing statement. Failure to file a termination statement by the lienholder or the assignee of the lienholder shall cause the lienholder or its assignee to be liable to the debtor for the attorneys' fees and costs incurred by the debtor to have the lien terminated together with damages incurred by the debtor due to the failure of the lienholder to terminate the lien.

[ 2000 c 250 § 9A-834; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5628-S.SL.pdf?cite=1991%20c%20286%20§%206[1991 c 286 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c242.pdf?cite=1986%20c%20242%20§%2014[1986 c 242 § 14]; ]

== 60.11.900 - Savings—Liens created under prior law.
Liens created prior to January 1, 1987, which are based on statutes repealed by *this act, shall remain in effect for the duration provided by the law in effect before January 1, 1987. The department of licensing shall notify persons requesting information for crop liens that, for this transition period, records of crop liens may exist at a county auditor's office as well as at the department of licensing.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c242.pdf?cite=1986%20c%20242%20§%2015[1986 c 242 § 15]; ]

== 60.11.901 - Section captions.
As used in this chapter, section captions constitute no part of the law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c242.pdf?cite=1986%20c%20242%20§%2018[1986 c 242 § 18]; ]

== 60.11.903 - Effective date—1986 c 242.
This act shall take effect January 1, 1987.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c242.pdf?cite=1986%20c%20242%20§%2021[1986 c 242 § 21]; ]

== 60.11.904 - Transition rule for filings made before July 1, 2001.
All statements filed with the department of licensing under this chapter before July 1, 2001, shall satisfy the requirements of RCW 62A.9A-310 and 60.11.030 for filing a financing statement.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5053.SL.pdf?cite=2001%20c%2032%20§%205[2001 c 32 § 5]; 2000 c 250 § 9A-835; ]

