= 60.40 - Lien for attorney's fees.
:toc:

== 60.40.010 - Lien created—Enforcement—Definition—Exception.
. An attorney has a lien for his or her compensation, whether specially agreed upon or implied, as hereinafter provided:

.. Upon the papers of the client, which have come into the attorney's possession in the course of his or her professional employment;

.. Upon money in the attorney's hands belonging to the client;

.. Upon money in the hands of the adverse party in an action or proceeding, in which the attorney was employed, from the time of giving notice of the lien to that party;

.. Upon an action, including one pursued by arbitration or mediation, and its proceeds after the commencement thereof to the extent of the value of any services performed by the attorney in the action, or if the services were rendered under a special agreement, for the sum due under such agreement; and

.. Upon a judgment to the extent of the value of any services performed by the attorney in the action, or if the services were rendered under a special agreement, for the sum due under such agreement, from the time of filing notice of such lien or claim with the clerk of the court in which such judgment is entered, which notice must be filed with the papers in the action in which such judgment was rendered, and an entry made in the execution docket, showing name of claimant, amount claimed and date of filing notice.

. Attorneys have the same right and power over actions to enforce their liens under subsection (1)(d) of this section and over judgments to enforce their liens under subsection (1)(e) of this section as their clients have for the amount due thereon to them.

. The lien created by subsection (1)(d) of this section upon an action and proceeds and the lien created by subsection (1)(e) of this section upon a judgment for money is superior to all other liens.

. The lien created by subsection (1)(d) of this section is not affected by settlement between the parties to the action until the lien of the attorney for fees based thereon is satisfied in full.

. For the purposes of this section, "proceeds" means any monetary sum received in the action. Once proceeds come into the possession of a client, such as through payment by an opposing party or another person or by distribution from the attorney's trust account or registry of the court, the term "proceeds" is limited to identifiable cash proceeds determined in accordance with RCW 62A.9A-315(b)(2). The attorney's lien continues in such identifiable cash proceeds, subject to the rights of a secured party under RCW 62A.9A-327 or a transferee under RCW 62A.9A-332.

. Child support liens are exempt from this section.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6270-S.SL.pdf?cite=2004%20c%2073%20§%202[2004 c 73 § 2]; Code 1881 § 3286; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20406%20§%2012[1863 p 406 § 12]; RRS § 136; ]

== 60.40.020 - Proceedings to compel delivery of money or papers.
When an attorney refuses to deliver over money or papers, to a person from or for whom he or she has received them in the course of professional employment, whether in an action or not, he or she may be required by an order of the court in which an action, if any, was prosecuted, or if no action was prosecuted, then by order of any judge of a court of record, to do so within a specified time, or show cause why he or she should not be punished for a contempt.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20152[2012 c 117 § 152]; Code 1881 § 3287; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20406%20§%2013[1863 p 406 § 13]; RRS § 137; ]

== 60.40.030 - Procedure when lien is claimed.
If, however, the attorney claim a lien, upon the money or papers, under the provisions of *this chapter, the court or judge may: (1) Impose as a condition of making the order, that the client give security in a form and amount to be directed, to satisfy the lien, when determined in an action; (2) summarily to inquire into the facts on which the claim of a lien is founded, and determine the same; or (3) to refer it, and upon the report, determine the same as in other cases.

[ Code 1881 § 3288; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20406%20§%2014[1863 p 406 § 14]; RRS § 138; ]

