= 60.68 - Uniform federal lien registration act.
:toc:

== 60.68.005 - Application of chapter.
This chapter applies only to federal tax liens and to other federal liens, notices of which under any act of congress or any regulation adopted pursuant thereto are required or permitted to be recorded in the same manner as notices of federal tax liens.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c73.pdf?cite=1988%20c%2073%20§%201[1988 c 73 § 1]; ]

== 60.68.015 - Notice of federal liens.
. Notices of liens, certificates, and other notices affecting federal tax liens or other federal liens must be recorded for record in accordance with this chapter.

. Notices of liens upon real property for obligations payable to the United States and certificates and notices affecting the liens shall be recorded in the office of the recorder of the county in which the real property subject to the liens is situated.

. Notices of federal liens upon personal property, whether tangible or intangible, for obligations payable to the United States and certificates and notices affecting the liens shall be filed with the department of licensing.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1185.SL.pdf?cite=1992%20c%20133%20§%201[1992 c 133 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c73.pdf?cite=1988%20c%2073%20§%202[1988 c 73 § 2]; ]

== 60.68.025 - Certification of federal liens.
Certification of notices of liens, certificates, or other notices affecting federal liens by the United States secretary of the treasury or the secretary's delegate, or by an official or entity of the United States responsible for recording or certifying of notice of any other lien, entitles those liens to be recorded and no other attestation, certification, or acknowledgment is necessary.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c73.pdf?cite=1988%20c%2073%20§%203[1988 c 73 § 3]; ]

== 60.68.035 - Fees for recording or filing federal liens.
. The fee for recording a lien on real estate with the county auditor shall be as set forth in RCW 36.18.010.

. The fee for filing liens of personal property with the department of licensing of the state of Washington shall be as determined by the department.

. The recording or filing officer shall bill the district directors of the internal revenue service or other appropriate federal officials on a monthly basis for fees for documents filed for record by them.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1185.SL.pdf?cite=1992%20c%20133%20§%202[1992 c 133 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c73.pdf?cite=1988%20c%2073%20§%204[1988 c 73 § 4]; ]

== 60.68.045 - Tax lien index—Duties of county auditor—Uniform commercial code filing system—Department of licensing.
. When a notice of a tax lien is recorded under RCW 60.68.015(2), the county auditor shall forthwith enter it in the general index showing the name and residence of the taxpayer named in the notice, the collector's serial number of the notice, the date and hour of recording, and the amount of tax and penalty assessed. The auditor shall have the ability to produce a separate tax lien index listing.

. When a notice of a tax lien is filed under RCW 60.68.015(3), the department of licensing shall enter it in the uniform commercial code filing system showing the name and address of the taxpayer as the debtor, and the internal revenue service as a secured party, and include the collector's serial number of the notice, the date and hour of filing, and the amount of tax and penalty assessed.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1647-S.SL.pdf?cite=1999%20c%20233%20§%207[1999 c 233 § 7]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1185.SL.pdf?cite=1992%20c%20133%20§%203[1992 c 133 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c73.pdf?cite=1988%20c%2073%20§%205[1988 c 73 § 5]; ]

== 60.68.900 - Uniform application of chapter.
This chapter shall be applied and construed to effectuate its general purpose to make uniform the law with respect to the subject of this chapter among states enacting it.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c73.pdf?cite=1988%20c%2073%20§%206[1988 c 73 § 6]; ]

== 60.68.901 - Short title.
This chapter may be known and cited as the uniform federal lien registration act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c73.pdf?cite=1988%20c%2073%20§%207[1988 c 73 § 7]; ]

== 60.68.902 - Effective date—1988 c 73.
This chapter shall take effect July 1, 1988.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c73.pdf?cite=1988%20c%2073%20§%2010[1988 c 73 § 10]; ]

== 60.68.903 - Effective date—1992 c 133.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and shall take effect July 1, 1992.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1185.SL.pdf?cite=1992%20c%20133%20§%204[1992 c 133 § 4]; ]

