= 60.70 - Limitations on nonconsensual common law liens.
:toc:

== 60.70.010 - Intent—Definitions.
. It is the intent of this chapter to limit the circumstances in which nonconsensual common law liens shall be recognized in this state.

. For the purposes of this chapter:

.. "Lien" means an encumbrance on property as security for the payment of a debt; 

.. "Nonconsensual common law lien" is a lien that:

... Is not provided for by a specific statute;

... Does not depend upon the consent of the owner of the property affected for its existence; and

... Is not a court-imposed equitable or constructive lien;

.. "State or local official or employee" means an appointed or elected official or any employee of a state agency, board, commission, department in any branch of state government, or institution of higher education; or of a school district, political subdivision, or unit of local government of this state; and

.. "Federal official or employee" means an employee of the government and federal agency as defined for purposes of the federal tort claims act, 28 U.S.C. Sec. 2671.

. Nothing in this chapter is intended to affect:

.. Any lien provided for by statute;

.. Any consensual liens now or hereafter recognized under the common law of this state; or

.. The ability of courts to impose equitable or constructive liens.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5630.SL.pdf?cite=1995%20c%2019%20§%201[1995 c 19 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c181.pdf?cite=1986%20c%20181%20§%201[1986 c 181 § 1]; ]

== 60.70.020 - Real property common law liens unenforceable—Personal property common law liens limited.
Nonconsensual common law liens against real property shall not be recognized or enforceable. Nonconsensual common law liens claimed against any personal property shall not be recognized or enforceable if, at any time the lien is claimed, the claimant fails to retain actual lawfully acquired possession or exclusive control of the property.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c181.pdf?cite=1986%20c%20181%20§%202[1986 c 181 § 2]; ]

== 60.70.030 - No duty to accept filing of common law lien—Filing of a notice of invalid lien.
. No person has a duty to accept for filing or recording any claim of lien unless the lien is authorized by statute or imposed by a court having jurisdiction over property affected by the lien, nor does any person have a duty to reject for filing or recording any claim of lien, except as provided in subsection (2) of this section.

. No person shall be obligated to accept for filing any claim of lien against a federal, state, or local official or employee based on the performance or nonperformance of that official's or employee's duties unless accompanied by a specific order from a court of competent jurisdiction authorizing the filing of such lien.

. If a claim of lien as described in subsection (2) of this section has been accepted for filing, the recording officer shall accept for filing a notice of invalid lien signed and submitted by the assistant United States attorney representing the federal agency of which the individual is an official or employee; the assistant attorney general representing the state agency, board, commission, department, or institution of higher education of which the individual is an official or employee; or the attorney representing the school district, political subdivision, or unit of local government of this state of which the individual is an official or employee. A copy of the notice of invalid lien shall be mailed by the attorney to the person who filed the claim of lien at his or her last known address. No recording officer or county shall be liable for the acceptance for filing of a claim of lien as described in subsection (2) of this section, nor for the acceptance for filing of a notice of invalid lien pursuant to this subsection.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5630.SL.pdf?cite=1995%20c%2019%20§%204[1995 c 19 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c181.pdf?cite=1986%20c%20181%20§%203[1986 c 181 § 3]; ]

== 60.70.040 - No duty to disclose record of common law lien.
No person has a duty to disclose an instrument of record or file that attempts to give notice of a common law lien. This section does not relieve any person of any duty which otherwise may exist to disclose a claim of lien authorized by statute or imposed by order of a court having jurisdiction over property affected by the lien.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c181.pdf?cite=1986%20c%20181%20§%204[1986 c 181 § 4]; ]

== 60.70.050 - Immunity from liability for failure to accept filing or disclose common law lien.
A person is not liable for damages arising from a refusal to record or file or a failure to disclose any claim of a common law lien of record.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c181.pdf?cite=1986%20c%20181%20§%205[1986 c 181 § 5]; ]

== 60.70.060 - Petition for order directing common law lien claimant to appear before court—Service of process—Filing fee—Costs and attorneys' fees.
. Any person whose real or personal property is subject to a recorded claim of common law lien who believes the claim of lien is invalid, may petition the superior court of the county in which the claim of lien has been recorded for an order, which may be granted ex parte, directing the lien claimant to appear before the court at a time no earlier than six nor later than twenty-one days following the date of service of the petition and order on the lien claimant, and show cause, if any, why the claim of lien should not be stricken and other relief provided for by this section should not be granted. The petition shall state the grounds upon which relief is requested, and shall be supported by the affidavit of the petitioner or his or her attorney setting forth a concise statement of the facts upon which the motion is based. The order shall be served upon the lien claimant by personal service, or, where the court determines that service by mail is likely to give actual notice, the court may order that service be made by any person over eighteen years of age, who is competent to be a witness, other than a party, by mailing copies of the petition and order to the lien claimant at his or her last known address or any other address determined by the court to be appropriate. Two copies shall be mailed, postage prepaid, one by ordinary first-class mail and the other by a form of mail requiring a signed receipt showing when and to whom it was delivered. The envelopes must bear the return address of the sender.

. The order shall clearly state that if the lien claimant fails to appear at the time and place noted, the claim of lien shall be stricken and released and that the lien claimant shall be ordered to pay the costs incurred by the petitioner, including reasonable attorneys' fees.

. The clerk of the court shall assign a cause number to the petition and obtain from the petitioner a filing fee pursuant to RCW 36.18.012.

. If, following a hearing on the matter, the court determines that the claim of lien is invalid, the court shall issue an order striking and releasing the claim of lien and awarding costs and reasonable attorneys' fees to the petitioner to be paid by the lien claimant. If the court determines that the claim of lien is valid, the court shall issue an order so stating and may award costs and reasonable attorneys' fees to the lien claimant to be paid by the petitioner.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6670-S.SL.pdf?cite=2006%20c%20192%20§%204[2006 c 192 § 4]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5630.SL.pdf?cite=1995%20c%2019%20§%202[1995 c 19 § 2]; ]

== 60.70.070 - Claim of lien against a federal, state, or local official or employee—Performance of duties—Validity.
Any claim of lien against a federal, state, or local official or employee based on the performance or nonperformance of that official's or employee's duties shall be invalid unless accompanied by a specific order from a court of competent jurisdiction authorizing the filing of such lien or unless a specific statute authorizes the filing of such lien.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5630.SL.pdf?cite=1995%20c%2019%20§%203[1995 c 19 § 3]; ]

