= 33.12 - Powers and restrictions.
:toc:

== 33.12.010 - Powers in general.
An association shall have the same capacity to act as possessed by natural persons. An association has authority to perform such acts as are necessary or proper to accomplish its purposes.

In addition to any other power an association may have, an association has authority:

. To have and alter a corporate seal;

. To continue as an association for the time limited in its articles of incorporation or, if no such time limit is specified, then perpetually;

. To sue or be sued in its corporate name;

. To acquire, hold, sell, dispose of, pledge, mortgage, or encumber property, as its interests and purposes may require;

. To conduct business in this state and elsewhere as may be permitted by law and, to this end, to comply with any law, regulation, or other requirements incident thereto;

. To acquire capital in the form of deposits, shares, or other accounts for fixed, minimum or indefinite periods of time as are authorized by its bylaws, and may issue such passbooks, statements, time certificates of deposit, or other evidence of accounts;

. To pay interest;

. To charge reasonable service fees for services provided as part of its business;

. To borrow money and to pledge, mortgage, or hypothecate its properties and securities in connection therewith;

. To collect or protest promissory notes or bills of exchange owned or held as collateral by the association;

. To let vaults, safes, boxes, or other receptacles for the safekeeping or storage of personal property, subject to the laws and regulations applicable to and with the powers possessed by safe deposit companies; and to act as escrow holder;

. To act as fiscal agent for the United States of America; to purchase, own, vote, or sell stock in, or act as fiscal agent for any federal home loan bank, the federal housing administration, home owners' loan corporation, or other state or federal agency, organized under the authority of the United States or of the state of Washington and authorized to loan to or act as fiscal agent for associations or to insure savings accounts or mortgages; and in the exercise of these powers, to comply with any requirements of law or rules or orders promulgated by such federal or state agency and to execute any contracts and pay any charges in connection therewith;

. To procure insurance of its mortgages and of its accounts from any state or federal corporation or agency authorized to write such insurance and, in the exercise of these powers, to comply with any requirements of law or rules or orders promulgated and to execute any contracts and pay any premiums required in connection therewith;

. To loan money and to sell any of its notes or other evidences of indebtedness, together with the collateral securing the same;

. To make, adopt, and amend bylaws for the management of its property and the conduct of its business;

. To deposit moneys and securities in any other association or any bank or savings bank or other like depository;

. To dissolve and wind up its business;

. To collect or compromise debts due to it and, in so doing, to apply to the indebtedness the accounts of the debtors, and to receive, as collateral or otherwise, other securities, property or property rights of any kind or nature;

. To become a member of, deal with, or make reasonable payments or contribution to any organization to the extent that such organization assists in furthering or facilitating the association's purposes, powers or community responsibilities, and to comply with any reasonable conditions of eligibility;

. To sell money orders, travelers checks and similar instruments as agent for any organization empowered to sell such instruments through agents within this state and to receive money for transmission through a federal home loan bank;

. To service loans and investments for others;

. To sell and to purchase mortgages or other loans, including participating interests therein;

. To use abbreviations, words or symbols in connection with any document of any nature and on checks, proxies, notices and other instruments which abbreviations, words, or symbols shall have the same force and legal effect as though the respective words and phrases for which they stand were set forth in full for the purposes of all statutes of the state and all other purposes;

. To conduct a trust business under rules adopted by the director pursuant to chapter 34.05 RCW; 

. To exercise the powers and authorities of a state commercial bank to engage in trust business under RCW 30A.08.150 upon application to and approval by the director and subject to requirements and conditions that the director may establish by rule; and

. To exercise, by and through its board of directors and duly authorized officers and agents, all such incidental powers as may be necessary to carry on the business of the association.

The powers granted in this section shall not be construed as limiting or enlarging any grant of authority made elsewhere by this title.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20602[2014 c 37 § 602]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20435[1994 c 92 § 435]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c3.pdf?cite=1982%20c%203%20§%2022[1982 c 3 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c107.pdf?cite=1969%20c%20107%20§%203[1969 c 107 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c246.pdf?cite=1963%20c%20246%20§%202[1963 c 246 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c235.pdf?cite=1945%20c%20235%20§%2029[1945 c 235 § 29]; Rem. Supp. 1945 § 3717-148; 1939 c 98 §§ 6, 7; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c171.pdf?cite=1935%20c%20171%20§%201[1935 c 171 § 1]; 1933 c 183 §§ 47, 48, 55, 59; ]

== 33.12.012 - Additional powers of an association—Powers conferred upon federal savings and loan association as of December 31, 1993, or a subsequent date not later than July 28, 2013—Powers of an out-of-state state savings association.
. Notwithstanding any other provision of law, in addition to all powers and authorities, express or implied, that an association has under this title, an association may exercise any of the powers and authorities that a federal savings and loan association had on December 31, 1993, or as of a subsequent date not later than July 28, 2013. As used in this section, "powers and authorities" include without limitation powers and authorities in corporate governance and operational matters.

. Notwithstanding any other provisions of law, a savings association has the powers and authorities that an out-of-state state savings association operating a branch in Washington has if the director finds that the exercise of such powers and authorities serves the convenience and advantage of depositors and borrowers, or the general public, and maintains the fairness of competition and parity between savings associations and out-of-state state savings associations.

. The restrictions, limitations and requirements applicable to specific powers and authorities of federal savings and loan associations or out-of-state state savings associations, as applicable, shall apply to savings associations exercising those powers and authorities permitted under this section but only insofar as the restrictions, limitations, and requirements relate to exercising the powers and authorities granted savings associations solely by this section.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1325-S.SL.pdf?cite=2013%20c%2076%20§%2029[2013 c 76 § 29]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6285.SL.pdf?cite=1994%20c%20256%20§%20119[1994 c 256 § 119]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c3.pdf?cite=1982%20c%203%20§%2023[1982 c 3 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c87.pdf?cite=1981%20c%2087%20§%201[1981 c 87 § 1]; ]

== 33.12.014 - Powers conferred upon federal savings and loan association—Reserve or other requirements—Authority of director to adopt by rule—Conditions.
Notwithstanding any other provision of law, in addition to all powers and authorities, express or implied, that an association has under this title, the director may make reasonable rules authorizing an association to exercise any of the powers and authorities conferred at the time of the adoption of the rules upon a federal savings and loan association doing business in this state, or may modify or reduce reserve or other requirements if an association is insured by the federal savings and loan insurance corporation, if the director finds that the exercise of the power or authorities:

. Serves the convenience and advantage of depositors and borrowers; and

. Maintains the fairness of competition and parity between state-chartered savings and loan associations and federally-chartered savings and loan associations.

As used in this section, "powers and authorities" include without limitation powers and authorities in corporate governance matters.

The restrictions, limitations and requirements applicable to specific powers or authorities of federal savings and loan associations shall apply to associations exercising those powers or authorities permitted under this section but only insofar as the restrictions, limitations, and requirements relate to exercising the powers or authorities granted associations solely by this section.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6285.SL.pdf?cite=1994%20c%20256%20§%20120[1994 c 256 § 120]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20436[1994 c 92 § 436]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c3.pdf?cite=1982%20c%203%20§%2024[1982 c 3 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c87.pdf?cite=1981%20c%2087%20§%202[1981 c 87 § 2]; ]

== 33.12.015 - Safe deposit companies.
See chapter 22.28 RCW.

[ ]

== 33.12.060 - Dealings with directors, officers, agents, employees prohibited—Exception.
An association shall make no loan to or sell to or purchase any real property or securities from any director, officer, agent, or employee of an association except to the extent permitted to or from a director, officer, agent, or employee of a federal savings association.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6285.SL.pdf?cite=1994%20c%20256%20§%20121[1994 c 256 § 121]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20437[1994 c 92 § 437]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c239.pdf?cite=1985%20c%20239%20§%201[1985 c 239 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c3.pdf?cite=1982%20c%203%20§%2025[1982 c 3 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c113.pdf?cite=1979%20c%20113%20§%203[1979 c 113 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c71.pdf?cite=1953%20c%2071%20§%202[1953 c 71 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c257.pdf?cite=1947%20c%20257%20§%203[1947 c 257 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c235.pdf?cite=1945%20c%20235%20§%2035[1945 c 235 § 35]; Rem. Supp. 1947 § 3717-154; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c98.pdf?cite=1939%20c%2098%20§%2010[1939 c 98 § 10]; 1933 c 183 §§ 51, 53; ]

== 33.12.140 - Expense and contingent funds.
Before any association is authorized to receive deposits or transact any business, its incorporators shall create an expense fund, in such amount as the director may determine, from which the expense of organizing the association and its operating expenses may be paid until such time as its earnings are sufficient to pay its operating expenses, and the incorporators shall enter into an undertaking with the director to make such further contributions to the expense fund as may be necessary to pay its operating expenses until such time as it can pay them from its earnings.

Before any mutual association is authorized to receive deposits or transact any business, its incorporators shall create a contingent fund for the protection of its members against investment losses, in an amount to be determined by the director.

The contingent fund shall consist of payments in cash made by the incorporators as provided in this section and of all sums credited thereto from the earnings of the association as hereinafter required.

Prior to the liquidation of any mutual association the contingent fund shall not be encroached upon in any manner except for losses and for the repayment of contributions made by the incorporators.

No repayment of the contribution of incorporators to the contingent fund shall be made until the net balance credited to the contingent fund from earnings of the association, after such repayment, equals five percent of the amount due members.

The incorporators may receive interest upon the amount of their contributions to the contingent fund at the same rate as is paid, from time to time, to savings members.

The amounts contributed to the contingent fund by the incorporators shall not constitute a liability of the association except as hereinafter provided, and any loss sustained by the association in excess of that portion of the contingent fund created from earnings may be charged against such contributions pro rata.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20438[1994 c 92 § 438]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c3.pdf?cite=1982%20c%203%20§%2026[1982 c 3 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c235.pdf?cite=1945%20c%20235%20§%2013[1945 c 235 § 13]; Rem. Supp. 1945 § 3717-132; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c183.pdf?cite=1933%20c%20183%20§%2077[1933 c 183 § 77]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c144.pdf?cite=1925%20ex.s.%20c%20144%20§%207[1925 ex.s. c 144 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c169.pdf?cite=1919%20c%20169%20§%208[1919 c 169 § 8]; 1913 c 110 §§ 13, 14; 1903 c 106 §§ 3, 5; 1890 p 56 §§ 6, 15, 31; ]

== 33.12.150 - Contingent fund as reserve—Members' rights to fund limited.
The contingent fund shall constitute a reserve for the absorption of losses of a mutual association.

Members do not have, individually or collectively, any right or claim to the contingent fund except upon dissolution of the association.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c3.pdf?cite=1982%20c%203%20§%2027[1982 c 3 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c84.pdf?cite=1981%20c%2084%20§%203[1981 c 84 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c246.pdf?cite=1963%20c%20246%20§%204[1963 c 246 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c222.pdf?cite=1961%20c%20222%20§%202[1961 c 222 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c235.pdf?cite=1945%20c%20235%20§%2051[1945 c 235 § 51]; Rem. Supp. 1945 § 3717-170; 1933 c 183 §§ 63, 67; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c144.pdf?cite=1925%20ex.s.%20c%20144%20§%207[1925 ex.s. c 144 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c169.pdf?cite=1919%20c%20169%20§%208[1919 c 169 § 8]; 1913 c 110 §§ 13, 14; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c116.pdf?cite=1903%20c%20116%20§%205[1903 c 116 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c56.pdf?cite=1890%20p%2056%20§%2031[1890 p 56 § 31]; ]

== 33.12.170 - May borrow from home loan bank.
See RCW 30A.32.030.

[ NOTES:; ]

== 33.12.180 - Trustee of retirement plan established under federal act entitled "Self-Employed Individuals Tax Retirement Act of 1962."
A savings and loan association shall have the power to act as trustee under:

A retirement plan established pursuant to the provisions of the act of congress entitled "Self-Employed Individuals Tax Retirement Act of 1962" (76 Stat. 809, 26 U.S.C. Sec. 37), as now constituted or hereafter amended. If a retirement plan, which in the judgment of the savings and loan association, constituted a qualified plan under the provisions of that act at the time accepted by the savings and loan association, is subsequently determined not to be a qualified plan or subsequently ceases to be a qualified plan in whole or in part, the savings and loan association may, nevertheless, continue to act as trustee of any deposits theretofore made under the plan and to dispose of the same in accordance with the directions of the trustor and the beneficiaries thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c93.pdf?cite=1973%201st%20ex.s.%20c%2093%20§%201[1973 1st ex.s. c 93 § 1]; ]

