= 33.28 - Fees and taxes.
:toc:

== 33.28.010 - Filing and copy fees.
The secretary of state shall collect fees of twenty dollars in advance for filing articles of incorporation. The secretary of state shall establish by rule, fees for amendments to articles of incorporation, other certificates required to be filed in his or her office, and for furnishing copies of papers filed in his or her office.

Every association shall also pay to the secretary of state, for filing any instrument with him or her, the same fees as are required of general corporations for filing similar papers.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5492-S.SL.pdf?cite=1993%20c%20269%20§%2013[1993 c 269 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c302.pdf?cite=1981%20c%20302%20§%2033[1981 c 302 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c235.pdf?cite=1945%20c%20235%20§%2076[1945 c 235 § 76]; Rem. Supp. 1945 § 3717-195; ]

== 33.28.020 - Fee for examination and supervision costs.
The director shall collect from each association a fee, the amount of which shall be set by rule, to cover the actual cost of examinations and supervision.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20449[1994 c 92 § 449]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c3.pdf?cite=1982%20c%203%20§%2057[1982 c 3 § 57]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c22.pdf?cite=1974%20ex.s.%20c%2022%20§%201[1974 ex.s. c 22 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c107.pdf?cite=1969%20c%20107%20§%206[1969 c 107 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c222.pdf?cite=1961%20c%20222%20§%204[1961 c 222 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c235.pdf?cite=1945%20c%20235%20§%2077[1945 c 235 § 77]; Rem. Supp. 1945 § 3717-196; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c183.pdf?cite=1933%20c%20183%20§%2082[1933 c 183 § 82]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c169.pdf?cite=1919%20c%20169%20§%2011[1919 c 169 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c110.pdf?cite=1913%20c%20110%20§%2018[1913 c 110 § 18]; ]

== 33.28.040 - Taxation of associations.
The fees provided for in this title shall be in lieu of all other corporation fees, licenses, or excises for the privilege of doing business, except for business and occupation taxes imposed pursuant to chapter 82.04 RCW, and except for license fees or taxes imposed by a city or town under RCW 82.14A.010, notwithstanding any other provisions of this section.

Neither an association nor its members shall be taxed upon its deposit accounts as property, nor shall a domestic association be taxed upon its real and tangible personal property at a rate greater than any federal association doing business in this state.

An association is an institution for deposits and neither it nor its property shall be taxed under any law which shall exempt banks or other savings institutions, state or federal, from taxation.

For all purposes of taxation, the assets represented by the contingent fund, guaranty fund, and other reserves (other than reserves for expenses and specific losses) of an association shall be deemed its only permanent capital and, in computing any tax, whether property, income, or excise, appropriate adjustments shall be made to give effect to the nature of such association.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c3.pdf?cite=1982%20c%203%20§%2058[1982 c 3 § 58]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c134.pdf?cite=1972%20ex.s.%20c%20134%20§%204[1972 ex.s. c 134 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c101.pdf?cite=1970%20ex.s.%20c%20101%20§%201[1970 ex.s. c 101 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c235.pdf?cite=1945%20c%20235%20§%2079[1945 c 235 § 79]; Rem. Supp. 1945 § 3717-198; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c183.pdf?cite=1933%20c%20183%20§%2086[1933 c 183 § 86]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c110.pdf?cite=1913%20c%20110%20§%2017[1913 c 110 § 17]; 1890 p 56 §§ 35, 38; ]

