= 33.36 - Prohibited acts—Penalties.
:toc:

== 33.36.010 - Illegal loans or investments.
Any director, officer, agent, or employee of an association who, on behalf of such association, shall knowingly and wilfully make or participate in making or consent to any loan or investment contrary to the provisions of this title shall be guilty of a gross misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c235.pdf?cite=1945%20c%20235%20§%2087[1945 c 235 § 87]; Rem. Supp. 1945 § 3717-206; 1933 c 183 §§ 53, 62, 102, 111; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c169.pdf?cite=1919%20c%20169%20§%2016[1919 c 169 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c110.pdf?cite=1913%20c%20110%20§%2027[1913 c 110 § 27]; ]

== 33.36.020 - Purchase at discount of accounts or certificates.
Any director, officer, agent, attorney, or employee of an association who, directly or indirectly, shall purchase at a discount any savings account in the association or any certificate or debenture of any segregation corporation holding assets formerly held by the association shall be guilty of a gross misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c235.pdf?cite=1945%20c%20235%20§%2088[1945 c 235 § 88]; Rem. Supp. 1945 § 3717-207; 1933 c 183 §§ 62, 101; ]

== 33.36.030 - Preference in case of insolvency.
Every transfer of its property and assets by any association in this state, made in contemplation of insolvency, or after it becomes insolvent, with a view to the preference of one creditor or member over another, or to prevent the proper distribution of its property and assets among its creditors and members, shall be void.

Every director, officer, agent, or employee making such transfer or assisting therein is guilty of a class C felony as provided in chapter 9A.20 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c3.pdf?cite=1982%20c%203%20§%2062[1982 c 3 § 62]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c235.pdf?cite=1945%20c%20235%20§%2089[1945 c 235 § 89]; Rem. Supp. 1945 § 3717-208; ]

== 33.36.040 - Falsification of books—Exhibiting false document—Making false statement of assets or liabilities.
Every person who subscribes to or knowingly makes or causes to be made any false statement or false entry in the books of any association, or knowingly subscribes to or exhibits any false or fictitious security, document, or paper, with intent to deceive any person authorized to examine into the affairs of any association, or knowingly makes or publishes any false statement of the amount of the assets or liabilities of the association, is guilty of a class C felony as provided in chapter 9A.20 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c3.pdf?cite=1982%20c%203%20§%2063[1982 c 3 § 63]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c235.pdf?cite=1945%20c%20235%20§%2090[1945 c 235 § 90]; Rem. Supp. 1945 § 3717-209; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c183.pdf?cite=1933%20c%20183%20§%20101[1933 c 183 § 101]; 1919 c 169 §§ 12, 18; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c110.pdf?cite=1913%20c%20110%20§%2019[1913 c 110 § 19]; ]

== 33.36.050 - False statement affecting financial standing.
Any person who wilfully instigates, makes, circulates, or transmits to another or others any statement which the person knows to be false concerning the financial condition or affecting the financial standing of any association doing business in this state, or who wilfully counsels, aids, procures or induces another to start, transmit, or circulate any such statement which the person knows to be false, is guilty of a gross misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c3.pdf?cite=1982%20c%203%20§%2064[1982 c 3 § 64]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c235.pdf?cite=1945%20c%20235%20§%2092[1945 c 235 § 92]; Rem. Supp. 1945 § 3717-211; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c183.pdf?cite=1933%20c%20183%20§%20110[1933 c 183 § 110]; ]

== 33.36.060 - Suppressing, secreting, or destroying evidence or records.
Any person who, for the purpose of concealing any material fact, suppresses any evidence or abstract, removes, mutilates, destroys, or secretes any book, paper or record of an association, or of the director, or of anyone connected with the association or the office of the director, is guilty of a class C felony as provided in chapter 9A.20 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20453[1994 c 92 § 453]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c3.pdf?cite=1982%20c%203%20§%2065[1982 c 3 § 65]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c235.pdf?cite=1945%20c%20235%20§%2091[1945 c 235 § 91]; Rem. Supp. 1945 § 3717-210; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c183.pdf?cite=1933%20c%20183%20§%20106[1933 c 183 § 106]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c169.pdf?cite=1919%20c%20169%20§%2019[1919 c 169 § 19]; ]

