= 33.46 - Conversion of savings bank or commercial bank to association.
:toc:

== 33.46.010 - Definitions.
As used in this chapter, unless the context indicates otherwise:

. "Association" means any association organized under the laws of this state or the laws of the United States of America;

. "Director" means a member of the board of directors of an association, savings bank, or commercial bank, as applicable;

. "Bank" means a savings bank or commercial bank organized under the laws of this state; and

. "Trustee" means a member of the managing board of a mutual savings bank.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c3.pdf?cite=1982%20c%203%20§%2080[1982 c 3 § 80]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c83.pdf?cite=1975%201st%20ex.s.%20c%2083%20§%201[1975 1st ex.s. c 83 § 1]; ]

== 33.46.020 - Conversion of bank to association—Procedure.
Any bank may be converted into an association in the following manner:

. The trustees or directors of the bank shall pass, by at least a two-thirds favorable vote of all trustees or directors, a resolution declaring its intention to convert the bank into an association, specifying in such resolution the type of association and whether the association is to be organized under the laws of this state, or is to be organized under the laws of the United States of America. If the association is to be a state association the bank shall apply to the director of financial institutions for authority to convert into an association. The application shall include a proposal which sets forth the method by and extent to which membership or stockholder interests, as the case may be, in the bank are to be converted into membership or shareholder interest, as the case may be, in the association, and the proposal shall allow for any member or stockholder to withdraw the value of his or her interest at any time within sixty days of the completion of the conversion. The proposal is subject to the approval of the director of financial institutions and shall conform to all applicable regulations of the federal deposit insurance corporation, the federal home loan bank board, the federal savings and loan insurance corporation, or other federal regulatory agency.

. The director of financial institutions shall, in the case of an application to convert into a state association, make the same investigation and determine the same questions as he or she would be required by law to make in determining the case of submission to him or her of articles of incorporation of a proposed new state association, and shall also determine whether the proposed conversion would serve the needs and conveniences of the depositors of the bank.

. The director of financial institutions shall grant or deny the application within sixty days of its date of filing and shall immediately notify the secretary of the bank of the decision.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20471[1994 c 92 § 471]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c3.pdf?cite=1982%20c%203%20§%2081[1982 c 3 § 81]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c83.pdf?cite=1975%201st%20ex.s.%20c%2083%20§%202[1975 1st ex.s. c 83 § 2]; ]

== 33.46.030 - Cash contributions to expense fund if becoming domestic mutual association.
If the application to become a domestic mutual association is granted, the director of financial institutions shall require the applicant to enter into an agreement or undertaking with the director, as trustee for the members of the association, to make such cash contributions to an expense fund of the mutual association as in the director's judgment will be necessary then and from time to time thereafter to pay the operating expenses of the association if its earnings should not be sufficient to pay the same in addition to the payment of such dividends as may be declared and credited to members from its earnings.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20472[1994 c 92 § 472]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c3.pdf?cite=1982%20c%203%20§%2082[1982 c 3 § 82]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c83.pdf?cite=1975%201st%20ex.s.%20c%2083%20§%203[1975 1st ex.s. c 83 § 3]; ]

== 33.46.040 - Appeal from denial of application.
If the application is denied by the director of financial institutions, the bank, acting by a two-thirds majority of its trustees or directors, may, within thirty days after receiving notice of such denial, appeal to the superior court of Thurston county pursuant to the provisions of the administrative procedure act, chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20473[1994 c 92 § 473]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c3.pdf?cite=1982%20c%203%20§%2083[1982 c 3 § 83]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c83.pdf?cite=1975%201st%20ex.s.%20c%2083%20§%204[1975 1st ex.s. c 83 § 4]; ]

== 33.46.050 - Certificate of reincorporation—Required—Filing—Contents.
If the application is granted by the director of financial institutions, or by the court, the trustees or directors of the bank shall, within thirty days thereafter, subscribe, acknowledge, and file with the director of financial institutions, in triplicate, a certificate of reincorporation stating:

. The name by which the association is to be known;

. The place where the association is to be located and its business transacted, naming the city or town and the county, which city or town shall be the same as that where the principal place of business of the bank has theretofore been located;

. The name, occupation, residence, and post office address of each signer of the certificate;

. The amount of the assets of the association, the amount of its liabilities, and the amount of its contingent, expense, or guaranty fund, as applicable, as of the first day of the calendar month during which the certificate is filed; and

. A declaration that each signer will accept the responsibilities and faithfully discharge the duties of a director of the association, and is free from all the disqualifications specified in the laws applicable to savings and loan associations.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20474[1994 c 92 § 474]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c3.pdf?cite=1982%20c%203%20§%2084[1982 c 3 § 84]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c302.pdf?cite=1981%20c%20302%20§%2035[1981 c 302 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c83.pdf?cite=1975%201st%20ex.s.%20c%2083%20§%205[1975 1st ex.s. c 83 § 5]; ]

== 33.46.060 - Issuance of authorization certificate—Filing—Completion of conversion—Effect.
Upon filing the certificate in triplicate as provided in RCW 33.46.050, the director of financial institutions shall, within thirty days thereafter, if satisfied that all the provisions of this chapter have been complied with, issue in triplicate an authorization certificate stating that the association has complied with all of the requirements of law, and that it has authority to transact, at the place or places designated in its certificate, the business of an association. The director of financial institutions shall retain one set of the triplicate originals of the certificate of reincorporation and of the certificate of authorization and shall transmit the other two sets to the association, which shall retain one set, and file one set with the secretary of state, paying the required fees. Upon such filings being made, the conversion of the bank to the association shall be deemed complete and consummated, and the association shall thereupon be a corporation having the powers and being subject to the duties and obligations prescribed by the laws of this state applicable to state associations, and the time of existence of such association shall be perpetual, unless sooner terminated.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20475[1994 c 92 § 475]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c3.pdf?cite=1982%20c%203%20§%2085[1982 c 3 § 85]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c302.pdf?cite=1981%20c%20302%20§%2036[1981 c 302 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c83.pdf?cite=1975%201st%20ex.s.%20c%2083%20§%206[1975 1st ex.s. c 83 § 6]; ]

== 33.46.070 - Depositor's interest upon conversion.
Upon the conversion of a bank into an association, every person who was a depositor of the bank at the time of the conversion shall become and be deemed to be a depositor of the association in a sum equal to the value of the deposits of the depositor in the bank as of the day on which the conversion was consummated.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c3.pdf?cite=1982%20c%203%20§%2086[1982 c 3 § 86]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c83.pdf?cite=1975%201st%20ex.s.%20c%2083%20§%207[1975 1st ex.s. c 83 § 7]; ]

== 33.46.080 - Transfer of securities—Conformance to state association laws, when.
All mortgages, notes, and other securities of any bank that has been converted into an association shall, on request of the association, be delivered to it by the director of financial institutions or, under the direction of the director, by any depository having possession thereof. If the association is a state association it shall, as soon as practicable and within such time and by such methods as the director may direct, cause its organization, its securities and investments, the character of its business, and its methods of transacting the same to conform to the laws applicable to state associations.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20476[1994 c 92 § 476]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c3.pdf?cite=1982%20c%203%20§%2087[1982 c 3 § 87]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c83.pdf?cite=1975%201st%20ex.s.%20c%2083%20§%208[1975 1st ex.s. c 83 § 8]; ]

== 33.46.090 - Assets, liabilities, etc., vested in association upon conversion.
Upon a conversion being consummated all assets, rights and properties of the bank shall vest in and be the property of the association and all liabilities, debts, and obligations of the bank shall be the liabilities, debts, and obligations of the association and any right can be enforced by or against the association the same as it could have been enforced by or against the bank if the conversion had not occurred.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c83.pdf?cite=1975%201st%20ex.s.%20c%2083%20§%209[1975 1st ex.s. c 83 § 9]; ]

== 33.46.100 - Initial meeting of shareholders of domestic association—Notice—Proxy voting.
Within twelve months following consummation of the conversion, the directors of a domestic association shall call a meeting of the members for the purpose of electing directors and conducting such other business of the association as is appropriate. Notice of such meeting shall be mailed not less than ten nor more than thirty days in advance of the meeting to the last known address of each member. The notice may also include a proxy form authorizing any one or more persons, who may be directors or officers of the association, selected by the directors, to vote on behalf of any member executing such proxy.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c3.pdf?cite=1982%20c%203%20§%2088[1982 c 3 § 88]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c83.pdf?cite=1975%201st%20ex.s.%20c%2083%20§%2010[1975 1st ex.s. c 83 § 10]; ]

== 33.46.110 - Conversion to federal association—Procedure.
If the bank specifies in the resolution that it intends to become a federal association, it shall proceed to make all filings and do all things which are required by federal laws and regulations to qualify as and become a federal association, and when all such things have been accomplished and a charter has been issued by the appropriate federal agency, the bank shall thereupon cease to be a bank organized under the laws of this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c3.pdf?cite=1982%20c%203%20§%2089[1982 c 3 § 89]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c83.pdf?cite=1975%201st%20ex.s.%20c%2083%20§%2011[1975 1st ex.s. c 83 § 11]; ]

== 33.46.130 - Rules implementing chapter—Standard.
The director of financial institutions shall adopt such rules under the administrative procedure act, chapter 34.05 RCW, as are necessary to implement this chapter in a manner which protects the relative interests of members, depositors, borrowers, stockholders, and creditors.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20477[1994 c 92 § 477]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c3.pdf?cite=1982%20c%203%20§%2090[1982 c 3 § 90]; ]

