= 25.10 - Uniform limited partnership act.
:toc:

== 25.10.006 - Short title.
This chapter may be known and cited as the uniform limited partnership act.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20101[2009 c 188 § 101]; ]

== 25.10.011 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Certificate of limited partnership" means the certificate required by RCW 25.10.201, including the certificate as amended or restated.

. "Contribution," except in the term "right of contribution," means any benefit provided by a person to a limited partnership in order to become a partner or in the person's capacity as a partner.

. "Debtor in bankruptcy" means a person that is the subject of:

.. An order for relief under Title 11 of the United States Code or a comparable order under a successor statute of general application; or

.. A comparable order under federal, state, or foreign law governing insolvency.

. "Designated office" means the principal office indicated in the limited partnership's most recent annual report, or, if the principal office is not located within this state, the office of the limited partnership's registered agent.

. "Distribution" means a transfer of money or other property from a limited partnership to a partner in the partner's capacity as a partner or to a transferee on account of a transferable interest owned by the transferee.

. "Foreign limited liability limited partnership" means a foreign limited partnership whose general partners have limited liability for the obligations of the foreign limited partnership under a provision similar to RCW 25.10.401(3).

. "Foreign limited partnership" means a partnership formed under the laws of a jurisdiction other than this state and required by those laws to have one or more general partners and one or more limited partners. "Foreign limited partnership" includes a foreign limited liability limited partnership.

. "General partner" means:

.. With respect to a limited partnership, a person that:

... Becomes a general partner under RCW 25.10.371; or

... Was a general partner in a limited partnership when the limited partnership became subject to this chapter under RCW 25.10.911 (1) or (2); and

.. With respect to a foreign limited partnership, a person that has rights, powers, and obligations similar to those of a general partner in a limited partnership.

. "Limited liability limited partnership," except in the term "foreign limited liability limited partnership," means a limited partnership whose certificate of limited partnership states that the limited partnership is a limited liability limited partnership.

. "Limited partner" means:

.. With respect to a limited partnership, a person that:

... Becomes a limited partner under RCW 25.10.301; or

... Was a limited partner in a limited partnership when the limited partnership became subject to this chapter under RCW 25.10.911 (1) or (2); and

.. With respect to a foreign limited partnership, a person that has rights, powers, and obligations similar to those of a limited partner in a limited partnership.

. "Limited partnership," except in the terms "foreign limited partnership" and "foreign limited liability limited partnership," means an entity, having one or more general partners and one or more limited partners, that is formed under this chapter by two or more persons or becomes subject to this chapter under article 11 of this chapter or RCW 25.10.911 (1) or (2). "Limited partnership" includes a limited liability limited partnership.

. "Partner" means a limited partner or general partner.

. "Partnership agreement" means the partners' agreement, whether oral, implied, in a record, or in any combination, concerning the limited partnership. "Partnership agreement" includes the agreement as amended.

. "Person" means an individual, corporation, business trust, estate, trust, partnership, limited liability company, association, joint venture, government; governmental subdivision, agency, or instrumentality; public corporation, or any other legal or commercial entity.

. "Person dissociated as a general partner" means a person dissociated as a general partner of a limited partnership.

. "Principal office" means the office where the principal executive office of a limited partnership or foreign limited partnership is located, whether or not the office is located in this state.

. "Record" means information that is inscribed on a tangible medium or that is stored in an electronic or other medium and is retrievable in perceivable form.

. "Required information" means the information that a limited partnership is required to maintain under RCW 25.10.091.

. "Sign" means, with present intent to authenticate or adopt a record:

.. To execute or adopt a tangible symbol;

.. To attach to or logically associate with the record an electronic symbol, sound, or process; or

.. With respect to a record to be filed with the secretary of state, to comply with the standard for filing with the office of the secretary of state as prescribed by the secretary of state.

. "State" means a state of the United States, the District of Columbia, Puerto Rico, the United States Virgin Islands, or any territory or insular possession subject to the jurisdiction of the United States.

. "Tangible medium" means a writing, copy of a writing, facsimile, or a physical reproduction, each on paper or on other tangible material.

. "Transfer" includes an assignment, conveyance, deed, bill of sale, lease, mortgage, security interest, encumbrance, gift, and transfer by operation of law.

. "Transferable interest" means a partner's right to receive distributions.

. "Transferee" means a person to which all or part of a transferable interest has been transferred, whether or not the transferor is a partner.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2081[2020 c 57 § 81]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206101[2015 c 176 § 6101]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20102[2009 c 188 § 102]; ]

== 25.10.016 - Knowledge and notice.
. A person knows a fact if the person has actual knowledge of it.

. A person has notice of a fact if the person:

.. Knows of it;

.. Has received a notification of it;

.. Has reason to know it exists from all of the facts known to the person at the time in question; or

.. Has notice of it under subsection (3) or (4) of this section.

. A certificate of limited partnership on file in the office of the secretary of state is notice that the partnership is a limited partnership and the persons designated in the certificate as general partners are general partners. Except as otherwise provided in subsection (4) of this section, the certificate is not notice of any other fact.

. A person has notice of:

.. Another person's dissociation as a general partner, ninety days after the effective date of an amendment to the certificate of limited partnership that states that the other person has dissociated or ninety days after the effective date of a statement of dissociation pertaining to the other person, whichever occurs first;

.. A limited partnership's dissolution, ninety days after the effective date of an amendment to the certificate of limited partnership stating that the limited partnership is dissolved;

.. A limited partnership's termination, ninety days after the effective date of a statement of termination;

.. A limited partnership's conversion under article 11 of this chapter, ninety days after the effective date of the articles of conversion; or

.. A merger under article 11 of this chapter, ninety days after the effective date of the articles of merger.

. A person notifies or gives a notification to another person by taking steps reasonably required to inform the other person in ordinary course, whether or not the other person learns of it.

. A person receives a notification when the notification:

.. Comes to the person's attention; or

.. Is delivered at the person's place of business or at any other place held out by the person as a place for receiving communications.

. Except as otherwise provided in subsection (8) of this section, a person other than an individual knows, has notice, or receives a notification of a fact for purposes of a particular transaction when the individual conducting the transaction for the person knows, has notice, or receives a notification of the fact, or in any event when the fact would have been brought to the individual's attention if the person had exercised reasonable diligence. A person other than an individual exercises reasonable diligence if it maintains reasonable routines for communicating significant information to the individual conducting the transaction for the person and there is reasonable compliance with the routines. Reasonable diligence does not require an individual acting for the person to communicate information unless the communication is part of the individual's regular duties or the individual has reason to know of the transaction and that the transaction would be materially affected by the information.

. A general partner's knowledge, notice, or receipt of a notification of a fact relating to the limited partnership is effective immediately as knowledge of, notice to, or receipt of a notification by the limited partnership, except in the case of a fraud on the limited partnership committed by or with the consent of the general partner. A limited partner's knowledge, notice, or receipt of a notification of a fact relating to the limited partnership is not effective as knowledge of, notice to, or receipt of a notification by the limited partnership.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20103[2009 c 188 § 103]; ]

== 25.10.021 - Nature, purpose, and duration of entity.
. A limited partnership is an entity distinct from its partners. A limited partnership is the same entity regardless of whether its certificate of limited partnership states that the limited partnership is a limited liability limited partnership.

. A limited partnership may be organized under this chapter for any lawful purpose.

. A limited partnership has a perpetual duration.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20104[2009 c 188 § 104]; ]

== 25.10.031 - Powers.
A limited partnership has the powers to do all things necessary or convenient to carry on its activities, including the power to sue, be sued, and defend in its own name and to maintain an action against a partner for harm caused to the limited partnership by a breach of the partnership agreement or violation of a duty to the partnership.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20105[2009 c 188 § 105]; ]

== 25.10.041 - Governing law.
The law of this state governs relations among the partners of a limited partnership and between the partners and the limited partnership and the liability of partners as partners for an obligation of the limited partnership.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20106[2009 c 188 § 106]; ]

== 25.10.051 - Supplemental principles of law—Rate of interest.
. Unless displaced by particular provisions of this chapter, the principles of law and equity supplement this chapter.

. If an obligation to pay interest arises under this chapter and the rate is not specified, the rate is that specified in RCW 19.52.010(1).

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20107[2009 c 188 § 107]; ]

== 25.10.061 - Name.
The name of a limited partnership must comply with the provisions of Article 3 of chapter 23.95 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206102[2015 c 176 § 6102]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20108[2009 c 188 § 108]; ]

== 25.10.071 - Reservation of name.
A person may reserve the exclusive right to the use of a limited partnership name in accordance with RCW 23.95.310.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206103[2015 c 176 § 6103]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20109[2009 c 188 § 109]; ]

== 25.10.081 - Effect of partnership agreement—Nonwaivable provisions.
. Except as otherwise provided in subsection (2) of this section, the partnership agreement governs relations among the partners and between the partners and the partnership. To the extent the partnership agreement does not otherwise provide, this chapter governs relations among the partners and between the partners and the partnership.

. A partnership agreement may not:

.. Vary a limited partnership's power under RCW 25.10.031 to sue, be sued, and defend in its own name;

.. Vary the law applicable to a limited partnership under RCW 25.10.041;

.. Vary the requirements of RCW 25.10.231;

.. Vary the information required under RCW 25.10.091 or unreasonably restrict the right to information under RCW 25.10.331 or 25.10.431, but the partnership agreement may impose reasonable restrictions on the availability and use of information obtained under those sections and may define appropriate remedies, including liquidated damages, for a breach of any reasonable restriction on use;

.. Eliminate the duty of loyalty under RCW 25.10.441, but the partnership agreement may, if not manifestly unreasonable:

... Identify specific types or categories of activities that do not violate the duty of loyalty; and

... Specify the number or percentage of partners that may authorize or ratify, after full disclosure to all partners of all material facts, a specific act or transaction that otherwise would violate the duty of loyalty;

.. Unreasonably reduce the duty of care under RCW 25.10.441(3);

.. Eliminate the obligation of good faith and fair dealing under RCW 25.10.341(2) and 25.10.441(4), but the partnership agreement may prescribe the standards by which the performance of the obligation is to be measured, if the standards are not manifestly unreasonable;

.. Vary the power of a person to dissociate as a general partner under RCW 25.10.526(1) except to require that the notice under RCW 25.10.521(1) be in a record;

.. Vary the power of a court to decree dissolution in the circumstances specified in RCW 25.10.576;

.. Vary the requirement to wind up the partnership's business as specified in RCW 25.10.581;

.. Unreasonably restrict the right to maintain an action under article 10 of this chapter;

.. Restrict the right of a partner under RCW 25.10.796(1) to approve a conversion or merger or the right of a general partner under RCW 25.10.796(2) to consent to an amendment to the certificate of limited partnership that deletes a statement that the limited partnership is a limited liability limited partnership; or

.. Restrict rights under this chapter of a person other than a partner or a transferee.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20110[2009 c 188 § 110]; ]

== 25.10.091 - Required information.
A limited partnership shall maintain at its designated office the following information:

. A current list showing the full name and last known street and mailing address of each partner, separately identifying the general partners, in alphabetical order, and the limited partners, in alphabetical order;

. A copy of the initial certificate of limited partnership and all amendments to and restatements of the certificate, together with signed copies of any powers of attorney under which any certificate, amendment, or restatement has been signed;

. A copy of any filed articles of conversion or merger;

. A copy of the limited partnership's federal, state, and local tax returns and reports, if any, for the three most recent years;

. A copy of any partnership agreement made in a record and any amendment made in a record to any partnership agreement;

. A copy of any financial statement of the limited partnership for the three most recent years;

. A copy of the three most recent annual reports delivered by the limited partnership to the secretary of state pursuant to RCW 25.10.291;

. A copy of any record made by the limited partnership during the past three years of any consent given by or vote taken of any partner pursuant to this chapter or the partnership agreement; and

. Unless contained in a partnership agreement made in a record, a record stating:

.. The amount of cash, and a description and statement of the agreed value of the other benefits, contributed and agreed to be contributed by each partner;

.. The times at which, or events on the happening of which, any additional contributions agreed to be made by each partner are to be made;

.. For any person that is both a general partner and a limited partner, a specification of what transferable interest the person owns in each capacity; and

.. Any events upon the happening of which the limited partnership is to be dissolved and its activities wound up.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20111[2009 c 188 § 111]; ]

== 25.10.101 - Business transactions of partner with partnership.
A partner may lend money to and transact other business with the limited partnership and has the same rights and obligations with respect to the loan or other transaction as a person that is not a partner.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20112[2009 c 188 § 112]; ]

== 25.10.111 - Dual capacity.
A person may be both a general partner and a limited partner. A person that is both a general and limited partner has the rights, powers, duties, and obligations provided by this chapter and the partnership agreement in each of those capacities. When the person acts as a general partner, the person is subject to the obligations, duties, and restrictions under this chapter and the partnership agreement for general partners. When the person acts as a limited partner, the person is subject to the obligations, duties, and restrictions under this chapter and the partnership agreement for limited partners.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20113[2009 c 188 § 113]; ]

== 25.10.121 - Registered agent—Requirements.
A limited partnership or foreign limited partnership shall designate and continuously maintain in this state a registered agent in accordance with Article 4 of chapter 23.95 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206104[2015 c 176 § 6104]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20114[2009 c 188 § 114]; ]

== 25.10.131 - Change of registered agent for service of process.
A limited partnership or a foreign limited partnership may change its registered agent by delivering to the secretary of state for filing a statement of change in accordance with RCW 23.95.430.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206105[2015 c 176 § 6105]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20115[2009 c 188 § 115]; ]

== 25.10.141 - Resignation of agent for service of process.
A registered agent may resign as an agent for service of process of a limited partnership or foreign limited partnership by delivering to the secretary of state for filing a statement of resignation in accordance with RCW 23.95.445.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206106[2015 c 176 § 6106]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20116[2009 c 188 § 116]; ]

== 25.10.151 - Service of process.
Service of any process, notice, or demand required or permitted by law to be served upon the limited partnership or foreign limited partnership may be made in accordance with RCW 23.95.450.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206107[2015 c 176 § 6107]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20117[2009 c 188 § 117]; ]

== 25.10.161 - Consent and proxies of partners.
Action requiring the consent of partners under this chapter may be taken without a meeting, and a partner may appoint a proxy to consent or otherwise act for the partner by signing an appointment record, either personally or by the partner's attorney-in-fact.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20118[2009 c 188 § 118]; ]

== 25.10.201 - Formation of limited partnership—Certificate of limited partnership.
. In order for a limited partnership to be formed, a certificate of limited partnership must be delivered to the secretary of state for filing in accordance with Article 2 of chapter 23.95 RCW. The certificate of limited partnership must state:

.. The name of the limited partnership, which must comply with Article 3 of chapter 23.95 RCW;

.. The name and street and mailing address of the initial agent for service of process;

.. The name and the street and mailing address of each general partner;

.. Whether the limited partnership is a limited liability limited partnership; and

.. Any additional information required by article 11 of this chapter.

. A certificate of limited partnership may also contain any other matters but may not vary or otherwise affect the provisions specified in RCW 25.10.081(2) in a manner inconsistent with that section.

. If there has been substantial compliance with subsection (1) of this section, subject to RCW 23.95.210, a limited partnership is formed when the secretary of state files the certificate of limited partnership.

. Subject to subsection (2) of this section, if any provision of a partnership agreement is inconsistent with the filed certificate of limited partnership or with a filed statement of dissociation, termination, or change or filed articles of conversion or merger:

.. The partnership agreement prevails as to partners and transferees; and

.. The filed certificate of limited partnership, statement of dissociation, termination, or change or articles of conversion or merger prevails as to persons, other than partners and transferees, that reasonably rely on the filed record to their detriment.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206108[2015 c 176 § 6108]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20201[2009 c 188 § 201]; ]

== 25.10.211 - Amendment or restatement of certificate of limited partnership.
. In order to amend its certificate of limited partnership, a limited partnership must deliver to the secretary of state for filing an amendment or, pursuant to article 11 of this chapter, articles of merger stating:

.. The name of the limited partnership;

.. The date of filing of its initial certificate of limited partnership; and

.. The changes the amendment makes to the certificate of limited partnership as most recently amended or restated.

. A limited partnership shall promptly deliver to the secretary of state for filing an amendment to a certificate of limited partnership to reflect:

.. The admission of a new general partner;

.. The dissociation of a person as a general partner; or

.. The appointment of a person to wind up the limited partnership's activities under RCW 25.10.581 (3) or (4).

. A general partner that knows that any information in a filed certificate of limited partnership was false when the certificate was filed or has become false due to changed circumstances shall promptly:

.. Cause the certificate of limited partnership to be amended; or

.. If appropriate, deliver to the secretary of state for filing a statement of change pursuant to RCW 23.95.430 or a statement of correction pursuant to RCW 23.95.220.

. A certificate of limited partnership may be amended at any time for any other proper purpose as determined by the limited partnership.

. A restated certificate of limited partnership may be delivered to the secretary of state for filing in the same manner as an amendment.

. An amendment or restated certificate of limited partnership is effective when filed by the secretary of state as provided in RCW 23.95.210, and may state a delayed effective date in accordance with RCW 23.95.210.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206109[2015 c 176 § 6109]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20202[2009 c 188 § 202]; ]

== 25.10.221 - Statement of termination.
A dissolved limited partnership that has completed winding up may deliver to the secretary of state for filing a statement of termination that states:

. The name of the limited partnership;

. The date of filing of its initial certificate of limited partnership; and

. Any other information as determined by the general partners filing the statement or by a person appointed pursuant to RCW 25.10.581 (3) or (4).

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20203[2009 c 188 § 203]; ]

== 25.10.231 - Signing of records.
. Each record delivered to the secretary of state for filing pursuant to Article 2 of chapter 23.95 RCW must be signed in the following manner:

.. An initial certificate of limited partnership must be signed by all general partners listed in the certificate.

.. An amendment adding or deleting a statement that the limited partnership is a limited liability limited partnership must be signed by all general partners listed in the certificate.

.. An amendment designating as general partner a person admitted under RCW 25.10.571(3)(b) following the dissociation of a limited partnership's last general partner must be signed by that person.

.. An amendment required by RCW 25.10.581(3) following the appointment of a person to wind up the dissolved limited partnership's activities must be signed by that person.

.. Any other amendment must be signed by:

... At least one general partner listed in the certificate of limited partnership;

... Each other person designated in the amendment as a new general partner; and

... Each person that the amendment indicates has dissociated as a general partner, unless:

(A) The person is deceased or a guardian or general conservator has been appointed for the person and the amendment so states; or

(B) The person has previously delivered to the secretary of state for filing a statement of dissociation.

.. A restated certificate of limited partnership must be signed by at least one general partner listed in the certificate, and, to the extent the restated certificate effects a change under any other subsection of this subsection (1), the certificate must be signed in a manner that satisfies that subsection.

.. A statement of termination must be signed by all general partners listed in the certificate or, if the certificate of a dissolved limited partnership lists no general partners, by the person appointed pursuant to RCW 25.10.581 (3) or (4) to wind up the dissolved limited partnership's activities.

.. Articles of conversion must be signed by each general partner listed in the certificate of limited partnership.

.. Articles of merger must be signed as provided in RCW 25.10.786(1).

.. Any other record delivered on behalf of a limited partnership to the secretary of state for filing must be signed by at least one general partner listed in the certificate of limited partnership.

.. A statement by a person pursuant to RCW 25.10.531(1)(d) stating that the person has dissociated as a general partner must be signed by that person.

.. A statement of withdrawal by a person pursuant to RCW 25.10.351 must be signed by that person.

.. A record delivered on behalf of a foreign limited partnership to the secretary of state for filing must be signed by at least one general partner of the foreign limited partnership.

.. Any other record delivered on behalf of any person to the secretary of state for filing must be signed by that person.

. Any person may sign by an agent any record to be delivered to the secretary of state for filing under Article 2 of chapter 23.95 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206110[2015 c 176 § 6110]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20204[2009 c 188 § 204]; ]

== 25.10.241 - Signing and filing pursuant to judicial order.
If a person required by this chapter to sign a record or deliver a record to the secretary of state for filing does not do so, any other person that is aggrieved may petition the appropriate court under RCW 23.95.245 to order the signing or delivery of the record.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206111[2015 c 176 § 6111]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20205[2009 c 188 § 205]; ]

== 25.10.251 - Delivery to and filing of records by secretary of state—Effective time and date.
. A record authorized or required to be delivered to the secretary of state for filing under this chapter must comply with the requirements of Article 2 of chapter 23.95 RCW. The secretary of state shall:

.. For a statement of dissociation, send:

... A copy of the filed statement and a receipt for the fees to the person that the statement indicates has dissociated as a general partner; and

... A copy of the filed statement and receipt to the limited partnership;

.. For a statement of withdrawal, send:

... A copy of the filed statement and a receipt for the fees to the person on whose behalf the record was filed; and

... If the statement refers to an existing limited partnership, a copy of the filed statement and receipt to the limited partnership; and

.. For all other records, send a copy of the filed record and a receipt for the fees to the person on whose behalf the record was filed.

. A record delivered to the secretary of state for filing under this chapter may specify an effective time and a delayed effective date in accordance with RCW 23.95.210. Except as otherwise provided in this chapter, a record filed by the secretary of state is effective as provided in RCW 23.95.210.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206112[2015 c 176 § 6112]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20206[2009 c 188 § 206]; ]

== 25.10.261 - Correcting filed record.
A limited partnership or foreign limited partnership may correct a record filed by the secretary of state in accordance with RCW 23.95.220.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206113[2015 c 176 § 6113]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20207[2009 c 188 § 207]; ]

== 25.10.271 - Liability for false information in filed record.
. If a record delivered to the secretary of state for filing under this chapter and filed by the secretary of state contains false information, a person that suffers loss by reliance on the information may recover damages for the loss from:

.. A person that signed the record, or caused another to sign it on the person's behalf, and knew the information to be false at the time the record was signed; and

.. A general partner that has notice that the information was false when the record was filed or has become false because of changed circumstances, if the general partner has notice for a reasonably sufficient time before the information is relied upon to enable the general partner to effect an amendment under RCW 25.10.211, file a petition under RCW 25.10.241, or deliver to the secretary of state for filing a statement of change under RCW 23.95.430 or a statement of correction under RCW 23.95.220.

. A person who signs a record authorized or required to be filed under this chapter that such a person knows is false in any material respect with intent that the record be delivered to the secretary of state for filing is subject to a criminal penalty under RCW 23.95.240.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206114[2015 c 176 § 6114]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20208[2009 c 188 § 208]; ]

== 25.10.281 - Certificate of existence or registration.
Any person may apply to the secretary of state under RCW 23.95.235 to furnish a certificate of existence for a domestic limited partnership or a certificate of registration for a foreign limited partnership.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206115[2015 c 176 § 6115]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20209[2009 c 188 § 209]; ]

== 25.10.291 - Annual report for secretary of state.
A limited partnership or a foreign limited partnership authorized to transact business in this state shall deliver to the secretary of state for filing an annual report in accordance with RCW 23.95.255.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206116[2015 c 176 § 6116]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20210[2009 c 188 § 210]; ]

== 25.10.301 - Becoming limited partner.
A person becomes a limited partner:

. As provided in the partnership agreement;

. As the result of a conversion or merger under article 11 of this chapter; or

. With the consent of all the partners.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20301[2009 c 188 § 301]; ]

== 25.10.311 - No right or power as limited partner to bind limited partnership.
A limited partner does not have the right or the power as a limited partner to act for or bind the limited partnership.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20302[2009 c 188 § 302]; ]

== 25.10.321 - No liability as limited partner for limited partnership obligations.
An obligation of a limited partnership, whether arising in contract, tort, or otherwise, is not the obligation of a limited partner. A limited partner is not personally liable, directly or indirectly, by way of contribution or otherwise, for an obligation of the limited partnership solely by reason of being a limited partner, even if the limited partner participates in the management and control of the limited partnership.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20303[2009 c 188 § 303]; ]

== 25.10.331 - Right of limited partner and former limited partner to information.
. On ten days' demand, made in a record received by the limited partnership, a limited partner may inspect and copy required information during regular business hours in the limited partnership's designated office. The limited partner need not have any particular purpose for seeking the information.

. During regular business hours and at a reasonable location specified by the limited partnership, a limited partner may obtain from the limited partnership and inspect and copy true and full information regarding the state of the activities and financial condition of the limited partnership and other information regarding the activities of the limited partnership as is just and reasonable if:

.. The limited partner seeks the information for a purpose reasonably related to the partner's interest as a limited partner;

.. The limited partner makes a demand in a record received by the limited partnership, describing with reasonable particularity the information sought and the purpose for seeking the information; and

.. The information sought is directly connected to the limited partner's purpose.

. Within ten days after receiving a demand pursuant to subsection (2) of this section, the limited partnership in a record shall inform the limited partner that made the demand:

.. What information the limited partnership will provide in response to the demand;

.. When and where the limited partnership will provide the information; and

.. If the limited partnership declines to provide any demanded information, the limited partnership's reasons for declining.

. Subject to subsection (6) of this section, a person dissociated as a limited partner may inspect and copy required information during regular business hours in the limited partnership's designated office if:

.. The information pertains to the period during which the person was a limited partner;

.. The person seeks the information in good faith; and

.. The person meets the requirements of subsection (2) of this section.

. The limited partnership shall respond to a demand made pursuant to subsection (4) of this section in the same manner as provided in subsection (3) of this section.

. If a limited partner dies, RCW 25.10.561 applies.

. The limited partnership may impose reasonable restrictions on the use of information obtained under this section. In a dispute concerning the reasonableness of a restriction under this subsection, the limited partnership has the burden of proving reasonableness.

. A limited partnership may charge a person that makes a demand under this section reasonable costs of copying, limited to the costs of labor and material.

. A limited partner or person dissociated as a limited partner may exercise the rights under this section through an attorney or other agent. Any restriction imposed under subsection (7) of this section or by the partnership agreement applies both to the attorney or other agent and to the limited partner or person dissociated as a limited partner.

. The rights stated in this section do not extend to a person as transferee, but may be exercised by the legal representative of an individual under legal disability who is a limited partner or person dissociated as a limited partner.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20304[2009 c 188 § 304]; ]

== 25.10.341 - Limited duties of limited partners.
. A limited partner does not have any fiduciary duty to the limited partnership or to any other partner solely by reason of being a limited partner.

. A limited partner shall discharge the duties to the partnership and the other partners under this chapter or under the partnership agreement and exercise any rights consistently with the obligation of good faith and fair dealing.

. A limited partner does not violate a duty or obligation under this chapter or under the partnership agreement merely because the limited partner's conduct furthers the limited partner's own interest.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20305[2009 c 188 § 305]; ]

== 25.10.351 - Person erroneously believing self to be limited partner.
. Except as otherwise provided in subsection (2) of this section, a person that makes an investment in a business enterprise, and erroneously but in good faith believes that the person has become a limited partner in the enterprise, is not a general partner and is not liable for the enterprise's obligations by reason of making the investment, receiving distributions from the enterprise, or exercising any rights of or appropriate to a limited partner, if, on ascertaining the mistake, the person:

.. Causes an appropriate certificate of limited partnership, amendment, or statement of correction to be signed and delivered to the secretary of state for filing; or

.. Withdraws from future participation as an owner in the enterprise by signing and delivering to the secretary of state for filing a statement of withdrawal under this section.

. A person that makes an investment described in subsection (1) of this section is liable to the same extent as a general partner to any third party that enters into a transaction with the enterprise, believing in good faith that the person is a general partner, before the secretary of state files a statement of withdrawal, certificate of limited partnership, amendment, or statement of correction to show that the person is not a general partner.

. If a person makes a diligent effort in good faith to comply with subsection (1)(a) of this section and is unable to cause the appropriate certificate of limited partnership, amendment, or statement of correction to be signed and delivered to the secretary of state for filing, the person has the right to withdraw from the enterprise pursuant to subsection (1)(b) of this section even if the withdrawal would otherwise breach an agreement with others that are or have agreed to become co-owners of the enterprise.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20306[2009 c 188 § 306]; ]

== 25.10.371 - Becoming general partner.
A person becomes a general partner:

. As provided in the partnership agreement;

. Under RCW 25.10.571(3)(b) following the dissociation of a limited partnership's last general partner;

. As the result of a conversion or merger under article 11 of this chapter; or

. With the consent of all the partners.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20401[2009 c 188 § 401]; ]

== 25.10.381 - General partner agent of limited partnership.
. Each general partner is an agent of the limited partnership for the purposes of its activities. An act of a general partner, including the signing of a record in the partnership's name, for apparently carrying on in the ordinary course of the limited partnership's activities or activities of the kind carried on by the limited partnership binds the limited partnership, unless the general partner did not have authority to act for the limited partnership in the particular matter and the person with which the general partner was dealing knew, had received a notification, or had notice under RCW 25.10.016(4) that the general partner lacked authority.

. An act of a general partner that is not apparently for carrying on in the ordinary course of the limited partnership's activities or activities of the kind carried on by the limited partnership binds the limited partnership only if the act was actually authorized by all the other partners.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20402[2009 c 188 § 402]; ]

== 25.10.391 - Limited partnership liable for general partner's actionable conduct.
. A limited partnership is liable for loss or injury caused to a person, or for a penalty incurred, as a result of a wrongful act or omission, or other actionable conduct, of a general partner acting in the ordinary course of activities of the limited partnership or with authority of the limited partnership.

. If, in the course of the limited partnership's activities or while acting with authority of the limited partnership, a general partner receives or causes the limited partnership to receive money or property of a person not a partner, and the money or property is misapplied by a general partner, the limited partnership is liable for the loss.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20403[2009 c 188 § 403]; ]

== 25.10.401 - General partner's liability.
. Except as otherwise provided in subsections (2) and (3) of this section, all general partners are liable jointly and severally for all obligations of the limited partnership unless otherwise agreed by the claimant or provided by law.

. A person that becomes a general partner of an existing limited partnership is not personally liable for an obligation of a limited partnership incurred before the person became a general partner.

. An obligation of a limited partnership incurred while the limited partnership is a limited liability limited partnership, whether arising in contract, tort, or otherwise, is solely the obligation of the limited partnership. A general partner is not personally liable, directly or indirectly, by way of contribution or otherwise, for such an obligation solely by reason of being or acting as a general partner. This subsection applies despite anything inconsistent in the partnership agreement that existed immediately before the consent required to become a limited liability limited partnership under RCW 25.10.421(2)(b).

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20404[2009 c 188 § 404]; ]

== 25.10.411 - Actions by and against partnership and partners.
. To the extent not inconsistent with RCW 25.10.401, a general partner may be joined in an action against the limited partnership or named in a separate action.

. A judgment against a limited partnership is not by itself a judgment against a general partner. A judgment against a limited partnership may not be satisfied from a general partner's assets unless there is also a judgment against the general partner.

. A judgment creditor of a general partner may not levy execution against the assets of the general partner to satisfy a judgment based on a claim against the limited partnership, unless the partner is personally liable for the claim under RCW 25.10.401 and:

.. A judgment based on the same claim has been obtained against the limited partnership and a writ of execution on the judgment has been returned unsatisfied in whole or in part;

.. The limited partnership is a debtor in bankruptcy;

.. The general partner has agreed that the creditor need not exhaust limited partnership assets;

.. A court grants permission to the judgment creditor to levy execution against the assets of a general partner based on a finding that limited partnership assets subject to execution are clearly insufficient to satisfy the judgment, that exhaustion of limited partnership assets is excessively burdensome, or that the grant of permission is an appropriate exercise of the court's equitable powers; or

.. Liability is imposed on the general partner by law or contract independent of the existence of the limited partnership.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20405[2009 c 188 § 405]; ]

== 25.10.421 - Management rights of general partner.
. Each general partner has equal rights in the management and conduct of the limited partnership's activities. Except as expressly provided in this chapter, any matter relating to the activities of the limited partnership may be exclusively decided by the general partner or, if there is more than one general partner, by a majority of the general partners.

. The consent of each partner is necessary to:

.. Amend the partnership agreement;

.. Amend the certificate of limited partnership to add or, subject to RCW 25.10.796, delete a statement that the limited partnership is a limited liability limited partnership; and

.. Sell, lease, exchange, or otherwise dispose of all, or substantially all, of the limited partnership's property, with or without the good will, other than in the usual and regular course of the limited partnership's activities.

. A limited partnership shall reimburse a general partner for payments made and indemnify a general partner for liabilities incurred by the general partner in the ordinary course of the activities of the partnership or for the preservation of its activities or property.

. A limited partnership shall reimburse a general partner for an advance to the limited partnership beyond the amount of capital the general partner agreed to contribute.

. A payment or advance made by a general partner that gives rise to an obligation of the limited partnership under subsection (3) or (4) of this section constitutes a loan to the limited partnership that accrues interest from the date of the payment or advance.

. A general partner is not entitled to remuneration for services performed for the partnership.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20406[2009 c 188 § 406]; ]

== 25.10.431 - Right of general partner and former general partner to information.
. A general partner, without having any particular purpose for seeking the information, may inspect and copy during regular business hours:

.. In the limited partnership's designated office, required information; and

.. At a reasonable location specified by the limited partnership, any other records maintained by the limited partnership regarding the limited partnership's activities and financial condition.

. Each general partner and the limited partnership shall furnish to a general partner:

.. Without demand, any information concerning the limited partnership's activities and activities reasonably required for the proper exercise of the general partner's rights and duties under the partnership agreement or this chapter; and

.. On demand, any other information concerning the limited partnership's activities, except to the extent the demand or the information demanded is unreasonable or otherwise improper under the circumstances.

. Subject to subsection (5) of this section, on ten days' demand made in a record received by the limited partnership, a person dissociated as a general partner may have access to the information and records described in subsection (1) of this section at the location specified in subsection (1) of this section if:

.. The information or record pertains to the period during which the person was a general partner;

.. The person seeks the information or record in good faith; and

.. The person satisfies the requirements imposed on a limited partner by RCW 25.10.331(2).

. The limited partnership shall respond to a demand made pursuant to subsection (3) of this section in the same manner as provided in RCW 25.10.331(3).

. If a general partner dies, RCW 25.10.561 applies.

. The limited partnership may impose reasonable restrictions on the use of information under this section. In any dispute concerning the reasonableness of a restriction under this subsection, the limited partnership has the burden of proving reasonableness.

. A limited partnership may charge a person dissociated as a general partner that makes a demand under this section reasonable costs of copying, limited to the costs of labor and material.

. A general partner or person dissociated as a general partner may exercise the rights under this section through an attorney or other agent. Any restriction imposed under subsection (6) of this section or by the partnership agreement applies both to the attorney or other agent and to the general partner or person dissociated as a general partner.

. The rights under this section do not extend to a person as transferee, but the rights under subsection (3) of this section of a person dissociated as a general partner may be exercised by the legal representative of an individual who dissociated as a general partner under RCW 25.10.521(7) (b) or (c).

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20407[2009 c 188 § 407]; ]

== 25.10.441 - General standards of general partner's conduct.
. The only fiduciary duties that a general partner has to the limited partnership and the other partners are the duties of loyalty and care under subsections (2) and (3) of this section.

. A general partner's duty of loyalty to the limited partnership and the other partners is limited to the following:

.. To account to the limited partnership and hold as trustee for it any property, profit, or benefit derived by the general partner in the conduct and winding up of the limited partnership's activities or derived from a use by the general partner of limited partnership property, including the appropriation of a limited partnership opportunity;

.. To refrain from dealing with the limited partnership in the conduct or winding up of the limited partnership's activities as or on behalf of a party having an interest adverse to the limited partnership; and

.. To refrain from competing with the limited partnership in the conduct or winding up of the limited partnership's activities.

. A general partner's duty of care to the limited partnership and the other partners in the conduct and winding up of the limited partnership's activities is limited to refraining from engaging in grossly negligent or reckless conduct, intentional misconduct, or a knowing violation of law.

. A general partner shall discharge the duties to the partnership and the other partners under this chapter or under the partnership agreement and exercise any rights consistently with the obligation of good faith and fair dealing.

. A general partner does not violate a duty or obligation under this chapter or under the partnership agreement merely because the general partner's conduct furthers the general partner's own interest.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20408[2009 c 188 § 408]; ]

== 25.10.461 - Form of contribution.
A contribution of a partner may consist of tangible or intangible property or other benefit to the limited partnership, including money, services performed, promissory notes, other agreements to contribute cash or property, and contracts for services to be performed.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20501[2009 c 188 § 501]; ]

== 25.10.466 - Liability for contribution.
. A partner's obligation to contribute money or other property or other benefit to, or to perform services for, a limited partnership is not excused by the partner's death, disability, or other inability to perform personally.

. If a partner does not make a promised nonmonetary contribution, the partner is obligated at the option of the limited partnership to contribute money equal to that portion of the value, as stated in the required information, of the stated contribution that has not been made.

. The obligation of a partner to make a contribution or return money or other property paid or distributed in violation of this chapter may be compromised only by consent of all partners. A creditor of a limited partnership that extends credit or otherwise acts in reasonable reliance on an obligation described in subsection (1) of this section, without notice of any compromise under this subsection, may enforce the original obligation to the extent that, in extending credit, the creditor reasonably relied on the obligation of a partner to make a contribution.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20502[2009 c 188 § 502]; ]

== 25.10.471 - Sharing of distributions.
A distribution by a limited partnership must be shared among the partners on the basis of the value, as stated in the required records when the limited partnership decides to make the distribution, of the contributions the limited partnership has received from each partner.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20503[2009 c 188 § 503]; ]

== 25.10.476 - Interim distributions.
A partner does not have a right to any distribution before the dissolution and winding up of the limited partnership unless the limited partnership decides to make an interim distribution.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20504[2009 c 188 § 504]; ]

== 25.10.481 - No distribution on account of dissociation.
A person does not have a right to receive a distribution on account of dissociation.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20505[2009 c 188 § 505]; ]

== 25.10.486 - Distribution in kind.
A partner does not have a right to demand or receive any distribution from a limited partnership in any form other than cash. Subject to RCW 25.10.621(2), a limited partnership may distribute an asset in kind to the extent each partner receives a percentage of the asset equal to the partner's share of distributions.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20506[2009 c 188 § 506]; ]

== 25.10.491 - Right to distribution.
When a partner or transferee becomes entitled to receive a distribution, the partner or transferee has the status of, and is entitled to all remedies available to, a creditor of the limited partnership with respect to the distribution. However, the limited partnership's obligation to make a distribution is subject to offset for any amount owed to the limited partnership by the partner or dissociated partner on whose account the distribution is made.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20507[2009 c 188 § 507]; ]

== 25.10.496 - Limitations on distribution.
. A limited partnership may not make a distribution in violation of the partnership agreement.

. A limited partnership may not make a distribution if after the distribution:

.. The limited partnership would not be able to pay its debts as they become due in the ordinary course of the limited partnership's activities; or

.. The limited partnership's total assets would be less than the sum of its total liabilities other than liabilities to partners on account of their partnership interests and liabilities for which recourse of creditors is limited to specified property of the limited partnership, except that the fair value of property that is subject to a liability for which the recourse of creditors is limited shall be included in the assets of the limited partnership only to the extent that the fair value of that property exceeds that liability.

. A limited partnership may base a determination that a distribution is not prohibited under subsection (2) of this section on financial statements prepared on the basis of accounting practices and principles that are reasonable in the circumstances or on a fair valuation or other method that is reasonable in the circumstances.

. Except as otherwise provided in subsection (7) of this section, the effect of a distribution under subsection (2) of this section is measured:

.. In the case of distribution by purchase, redemption, or other acquisition of a transferable interest in the limited partnership, as of the date money or other property is transferred or debt incurred by the limited partnership; and

.. In all other cases, as of the date:

... The distribution is authorized, if the payment occurs within one hundred twenty days after that date; or

... The payment is made, if payment occurs more than one hundred twenty days after the distribution is authorized.

. A limited partnership's indebtedness to a partner incurred by reason of a distribution made in accordance with this section is at parity with the limited partnership's indebtedness to its general, unsecured creditors.

. A limited partnership's indebtedness, including indebtedness issued in connection with or as part of a distribution, is not considered a liability for purposes of subsection (2) of this section if the terms of the indebtedness provide that payment of principal and interest are made only to the extent that a distribution could then be made to partners under this section.

. If indebtedness is issued as a distribution, each payment of principal or interest on the indebtedness is treated as a distribution, the effect of which is measured on the date the payment is made.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20508[2009 c 188 § 508]; ]

== 25.10.501 - Liability for improper distributions.
. A general partner that consents to a distribution made in violation of RCW 25.10.496 is personally liable to the limited partnership for the amount of the distribution that exceeds the amount that could have been distributed without the violation if it is established that in consenting to the distribution the general partner failed to comply with RCW 25.10.441.

. A partner or transferee that received a distribution knowing that the distribution to that partner or transferee was made in violation of RCW 25.10.496 is personally liable to the limited partnership but only to the extent that the distribution received by the partner or transferee exceeded the amount that could have been properly paid under RCW 25.10.496.

. A general partner against which an action is commenced under subsection (1) of this section may:

.. Implead in the action any other person that is liable under subsection (1) of this section and compel contribution from the person; and

.. Implead in the action any person that received a distribution in violation of subsection (2) of this section and compel contribution from the person in the amount the person received in violation of subsection (2) of this section.

. An action under this section is barred if it is not commenced within two years after the distribution.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20509[2009 c 188 § 509]; ]

== 25.10.511 - Dissociation as limited partner.
. A person does not have a right to dissociate as a limited partner before the termination of the limited partnership.

. A person is dissociated from a limited partnership as a limited partner upon the occurrence of any of the following events:

.. The limited partnership's having notice of the person's express will to withdraw as a limited partner or on a later date specified by the person;

.. An event agreed to in the partnership agreement as causing the person's dissociation as a limited partner;

.. The person's expulsion as a limited partner pursuant to the partnership agreement;

.. The person's expulsion as a limited partner by the unanimous consent of the other partners if:

... It is unlawful to carry on the limited partnership's activities with the person as a limited partner;

... There has been a transfer of all of the person's transferable interest in the limited partnership, other than a transfer for security purposes, or a court order charging the person's interest, that has not been foreclosed;

... The person is a corporation and, within ninety days after the limited partnership notifies the person that it will be expelled as a limited partner because it has filed a certificate of dissolution or the equivalent, its charter has been revoked, or its right to conduct business has been suspended by the jurisdiction of its incorporation, there is no revocation of the certificate of dissolution or no reinstatement of its charter or its right to conduct business; or

... The person is a limited liability company or partnership that has been dissolved and whose business is being wound up;

.. On application by the limited partnership, the person's expulsion as a limited partner by judicial order because:

... The person engaged in wrongful conduct that adversely and materially affected the limited partnership's activities;

... The person willfully or persistently committed a material breach of the partnership agreement or of the obligation of good faith and fair dealing under RCW 25.10.341(2); or

... The person engaged in conduct relating to the limited partnership's activities that makes it not reasonably practicable to carry on the activities with the person as limited partner;

.. In the case of a person who is an individual, the person's death;

.. In the case of a person that is a trust or is acting as a limited partner by virtue of being a trustee of a trust, distribution of the trust's entire transferable interest in the limited partnership, but not merely by reason of the substitution of a successor trustee;

.. In the case of a person that is an estate or is acting as a limited partner by virtue of being a personal representative of an estate, distribution of the estate's entire transferable interest in the limited partnership, but not merely by reason of the substitution of a successor personal representative;

.. Termination of a limited partner that is not an individual, partnership, limited liability company, corporation, trust, or estate;

.. The limited partnership's participation in a conversion or merger under article 11 of this chapter, if the limited partnership:

... Is not the converted or surviving entity; or

... Is the converted or surviving entity but, as a result of the conversion or merger, the person ceases to be a limited partner.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20601[2009 c 188 § 601]; ]

== 25.10.516 - Effect of dissociation as limited partner.
. Upon a person's dissociation as a limited partner:

.. Subject to RCW 25.10.561, the person does not have further rights as a limited partner;

.. The person's obligation of good faith and fair dealing as a limited partner under RCW 25.10.341(2) continues only as to matters arising and events occurring before the dissociation; and

.. Subject to RCW 25.10.561 and article 11 of this chapter, any transferable interest owned by the person in the person's capacity as a limited partner immediately before dissociation is owned by the person as a mere transferee.

. A person's dissociation as a limited partner does not of itself discharge the person from any obligation to the limited partnership or the other partners that the person incurred while a limited partner.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20602[2009 c 188 § 602]; ]

== 25.10.521 - Dissociation as general partner.
A person is dissociated from a limited partnership as a general partner upon the occurrence of any of the following events:

. The limited partnership's having notice of the person's express will to withdraw as a general partner or on a later date specified by the person;

. An event agreed to in the partnership agreement as causing the person's dissociation as a general partner;

. The person's expulsion as a general partner pursuant to the partnership agreement;

. The person's expulsion as a general partner by the unanimous consent of the other partners if:

.. It is unlawful to carry on the limited partnership's activities with the person as a general partner;

.. There has been a transfer of all or substantially all of the person's transferable interest in the limited partnership, other than a transfer for security purposes, or a court order charging the person's interest, that has not been foreclosed;

.. The person is a corporation and, within ninety days after the limited partnership notifies the person that it will be expelled as a general partner because it has filed a certificate of dissolution or the equivalent, its charter has been revoked, or its right to conduct business has been suspended by the jurisdiction of its incorporation, there is no revocation of the certificate of dissolution or no reinstatement of its charter or its right to conduct business; or

.. The person is a limited liability company or partnership that has been dissolved and whose business is being wound up;

. On application by the limited partnership, the person's expulsion as a general partner by judicial determination because:

.. The person engaged in wrongful conduct that adversely and materially affected the limited partnership activities;

.. The person willfully or persistently committed a material breach of the partnership agreement or of a duty owed to the partnership or the other partners under RCW 25.10.441; or

.. The person engaged in conduct relating to the limited partnership's activities that makes it not reasonably practicable to carry on the activities of the limited partnership with the person as a general partner;

. The person's:

.. Becoming a debtor in bankruptcy;

.. Execution of an assignment for the benefit of creditors;

.. Seeking, consenting to, or acquiescing in the appointment of a trustee, receiver, or liquidator of the person or of all or substantially all of the person's property; or

.. Failure, within ninety days after the appointment, to have vacated or stayed the appointment of a trustee, receiver, or liquidator of the general partner or of all or substantially all of the person's property obtained without the person's consent or acquiescence, or failing within ninety days after the expiration of a stay to have the appointment vacated;

. In the case of a person who is an individual:

.. The person's death;

.. The appointment of a guardian or general conservator for the person; or

.. A judicial determination that the person has otherwise become incapable of performing the person's duties as a general partner under the partnership agreement;

. In the case of a person that is a trust or is acting as a general partner by virtue of being a trustee of a trust, distribution of the trust's entire transferable interest in the limited partnership, but not merely by reason of the substitution of a successor trustee;

. In the case of a person that is an estate or is acting as a general partner by virtue of being a personal representative of an estate, distribution of the estate's entire transferable interest in the limited partnership, but not merely by reason of the substitution of a successor personal representative;

. Termination of a general partner that is not an individual, partnership, limited liability company, corporation, trust, or estate; or

. The limited partnership's participation in a conversion or merger under article 11 of this chapter, if the limited partnership:

.. Is not the converted or surviving entity; or

.. Is the converted or surviving entity but, as a result of the conversion or merger, the person ceases to be a general partner.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20603[2009 c 188 § 603]; ]

== 25.10.526 - Person's power to dissociate as general partner—Wrongful dissociation.
. A person has the power to dissociate as a general partner at any time, rightfully or wrongfully, by express will pursuant to RCW 25.10.521(1).

. A person's dissociation as a general partner is wrongful only if:

.. It is in breach of an express provision of the partnership agreement; or

.. It occurs before the termination of the limited partnership, and:

... The person withdraws as a general partner by express will;

... The person is expelled as a general partner by judicial determination under RCW 25.10.521(5);

... The person is dissociated as a general partner as a result of an event described in RCW 25.10.521(6); or

... In the case of a person that is not an individual, trust other than a business trust, or estate, the person is expelled or otherwise dissociated as a general partner because it willfully dissolved or terminated.

. A person that wrongfully dissociates as a general partner is liable to the limited partnership and, subject to RCW 25.10.701, to the other partners for damages caused by the dissociation. The liability is in addition to any other obligation of the general partner to the limited partnership or to the other partners.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20604[2009 c 188 § 604]; ]

== 25.10.531 - Effect of dissociation as general partner.
. Upon a person's dissociation as a general partner:

.. The person's right to participate as a general partner in the management and conduct of the partnership's activities terminates;

.. The person's duty of loyalty as a general partner under RCW 25.10.441(2)(c) terminates;

.. The person's duty of loyalty as a general partner under RCW 25.10.441(2) (a) and (b) and duty of care under RCW 25.10.441(3) continue only with regard to matters arising and events occurring before the person's dissociation as a general partner;

.. The person may sign and deliver to the secretary of state for filing a statement of dissociation pertaining to the person and, at the request of the limited partnership, shall sign an amendment to the certificate of limited partnership that states that the person has dissociated; and

.. Subject to RCW 25.10.561 and article 11 of this chapter, any transferable interest owned by the person immediately before dissociation in the person's capacity as a general partner is owned by the person as a mere transferee.

. A person's dissociation as a general partner does not of itself discharge the person from any obligation to the limited partnership or the other partners that the person incurred while a general partner.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20605[2009 c 188 § 605]; ]

== 25.10.536 - Power to bind and liability to limited partnership before dissolution of partnership of person dissociated as general partner.
. After a person is dissociated as a general partner and before the limited partnership is dissolved, converted under article 11 of this chapter, or merged out of existence under article 11 of this chapter, the limited partnership is bound by an act of the person only if:

.. The act would have bound the limited partnership under RCW 25.10.381 before the dissociation; and

.. At the time the other party enters into the transaction:

... Less than two years have passed since the dissociation; and

... The other party does not have notice of the dissociation and reasonably believes that the person is a general partner.

. If a limited partnership is bound under subsection (1) of this section, the person dissociated as a general partner that caused the limited partnership to be bound is liable:

.. To the limited partnership for any damage caused to the limited partnership arising from the obligation incurred under subsection (1) of this section; and

.. If a general partner or another person dissociated as a general partner is liable for the obligation, to the general partner or other person for any damage caused to the general partner or other person arising from the liability.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20606[2009 c 188 § 606]; ]

== 25.10.541 - Liability to other persons of person dissociated as general partner.
. A person's dissociation as a general partner does not of itself discharge the person's liability as a general partner for an obligation of the limited partnership incurred before dissociation. Except as otherwise provided in subsections (2) and (3) of this section, the person is not liable for a limited partnership's obligation incurred after dissociation.

. A person whose dissociation as a general partner resulted in a dissolution and winding up of the limited partnership's activities is liable to the same extent as a general partner under RCW 25.10.401 on an obligation incurred by the limited partnership under RCW 25.10.586.

. A person that has dissociated as a general partner but whose

dissociation did not result in a dissolution and winding up of the limited partnership's activities is liable on a transaction entered into by the limited partnership after the dissociation only if:

.. A general partner would be liable on the transaction; and

.. At the time the other party enters into the transaction:

... Less than two years have passed since the dissociation; and

... The other party does not have notice of the dissociation and reasonably believes that the person is a general partner.

. By agreement with a creditor of a limited partnership and the limited partnership, a person dissociated as a general partner may be released from liability for an obligation of the limited partnership.

. A person dissociated as a general partner is released from liability for an obligation of the limited partnership if the limited partnership's creditor, with notice of the person's dissociation as a general partner but without the person's consent, agrees to a material alteration in the nature or time of payment of the obligation.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20607[2009 c 188 § 607]; ]

== 25.10.546 - Partner's transferable interest.
The only interest of a partner that is transferable is the partner's transferable interest. A transferable interest is personal property.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20701[2009 c 188 § 701]; ]

== 25.10.551 - Transfer of partner's transferable interest.
. A transfer, in whole or in part, of a partner's transferable interest:

.. Is permissible;

.. Does not by itself cause the partner's dissociation or a dissolution and winding up of the limited partnership's activities; and

.. Does not, as against the other partners or the limited partnership, entitle the transferee to participate in the management or conduct of the limited partnership's activities, to require access to information concerning the limited partnership's transactions except as otherwise provided in subsection (3) of this section, or to inspect or copy the required information or the limited partnership's other records.

. A transferee has a right to receive, in accordance with the transfer:

.. Distributions to which the transferor would otherwise be entitled; and

.. Upon the dissolution and winding up of the limited partnership's activities the net amount otherwise distributable to the transferor.

. In a dissolution and winding up, a transferee is entitled to an account of the limited partnership's transactions only from the date of dissolution.

. Upon transfer, the transferor retains the rights of a partner other than the interest in distributions transferred and retains all duties and obligations of a partner.

. A limited partnership need not give effect to a transferee's rights under this section until the limited partnership has notice of the transfer.

. A transfer of a partner's transferable interest in the limited partnership in violation of a restriction on transfer contained in the partnership agreement is ineffective as to a person having notice of the restriction at the time of transfer.

. A transferee that becomes a partner with respect to a transferable interest is liable for the transferor's obligations under RCW 25.10.466 and 25.10.501. However, the transferee is not obligated for liabilities unknown to the transferee at the time the transferee became a partner.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20702[2009 c 188 § 702]; ]

== 25.10.556 - Rights of creditor of partner or transferee.
. On application to a court of competent jurisdiction by any judgment creditor of a partner or transferee, the court may charge the transferable interest of the judgment debtor with payment of the unsatisfied amount of the judgment with interest. To the extent so charged, the judgment creditor has only the rights of a transferee. The court may appoint a receiver of the share of the distributions due or to become due to the judgment debtor in respect of the partnership and make all other orders, directions, accounts, and inquiries the judgment debtor might have made or that the circumstances of the case may require to give effect to the charging order.

. A charging order constitutes a lien on the judgment debtor's transferable interest. The court may order a foreclosure upon the interest subject to the charging order at any time. The purchaser at the foreclosure sale has the rights of a transferee.

. At any time before foreclosure, an interest charged may be redeemed:

.. By the judgment debtor;

.. With property other than limited partnership property, by one or more of the other partners; or

.. With limited partnership property, by the limited partnership with the consent of all partners whose interests are not so charged.

. This chapter does not deprive any partner or transferee of the benefit of any exemption laws applicable to the partner's or transferee's transferable interest.

. This section provides the exclusive remedy by which a judgment creditor of a partner or transferee may satisfy a judgment out of the judgment debtor's transferable interest.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20703[2009 c 188 § 703]; ]

== 25.10.561 - Power of estate of deceased partner.
If a partner dies, the deceased partner's personal representative or other legal representative may exercise the rights of a transferee as provided in RCW 25.10.551 and, for the purposes of settling the estate, may exercise the rights of a current limited partner under RCW 25.10.331.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20704[2009 c 188 § 704]; ]

== 25.10.571 - Nonjudicial dissolution.
Except as otherwise provided in RCW 25.10.576, a limited partnership is dissolved, and its activities must be wound up, only upon the occurrence of any of the following:

. The happening of an event specified in the partnership agreement;

. The consent of all general partners and of limited partners owning a majority of the rights to receive distributions as limited partners at the time the consent is to be effective;

. The passage of ninety days after the dissociation of a person as a general partner if following such dissociation the limited partnership does not have a remaining general partner unless before the end of the period:

.. Consent to continue the activities of the limited partnership and admit at least one general partner is given by limited partners owning a majority of the rights to receive distributions as limited partners at the time the consent is to be effective; and

.. At least one person is admitted as a general partner in accordance with the consent;

. The passage of ninety days after the dissociation of the limited partnership's last limited partner, unless before the end of the period the limited partnership admits at least one limited partner; or

. The signing and filing of a statement of administrative dissolution by the secretary of state under RCW 23.95.610.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206117[2015 c 176 § 6117]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20801[2009 c 188 § 801]; ]

== 25.10.576 - Judicial dissolution.
On application by a partner the Thurston county superior court may order dissolution of a limited partnership if it is not reasonably practicable to carry on the activities of the limited partnership in conformity with the partnership agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20802[2009 c 188 § 802]; ]

== 25.10.581 - Winding up.
. A limited partnership continues after dissolution only for the purpose of winding up its activities.

. In winding up its activities, the limited partnership:

.. May amend its certificate of limited partnership to state that the limited partnership is dissolved, preserve the limited partnership business or property as a going concern for a reasonable time, prosecute and defend actions and proceedings, whether civil, criminal, or administrative, transfer the limited partnership's property, settle disputes by mediation or arbitration, file a statement of termination as provided in RCW 25.10.221, and perform other necessary acts; and

.. Shall discharge the limited partnership's liabilities, settle and close the limited partnership's activities, and marshal and distribute the assets of the partnership.

. If a dissolved limited partnership does not have a general partner, a person to wind up the dissolved limited partnership's activities may be appointed by the consent of limited partners owning a majority of the rights to receive distributions as limited partners at the time the consent is to be effective. A person appointed under this subsection:

.. Has the powers of a general partner under RCW 25.10.586; and

.. Shall promptly amend the certificate of limited partnership to state:

... That the limited partnership does not have a general partner;

... The name of the person that has been appointed to wind up the limited partnership; and

... The street and mailing address of the person.

. On the application of any partner, or, if there are no partners, any transferee of a partner's transferable interest, the Thurston county superior court may order judicial supervision of the winding up, including the appointment of a person to wind up the dissolved limited partnership's activities, if:

.. A limited partnership does not have a general partner and within a reasonable time following the dissolution no person has been appointed pursuant to subsection (3) of this section; or

.. The applicant establishes other good cause.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20803[2009 c 188 § 803]; ]

== 25.10.586 - Power of general partner and person dissociated as general partner to bind partnership after dissolution.
. A limited partnership is bound by a general partner's act after dissolution that:

.. Is appropriate for winding up the limited partnership's activities; or

.. Would have bound the limited partnership under RCW 25.10.381 before dissolution, if, at the time the other party enters into the transaction, the other party does not have notice of the dissolution.

. A person dissociated as a general partner binds a limited partnership through an act occurring after dissolution if:

.. At the time the other party enters into the transaction:

... Less than two years have passed since the dissociation; and

... The other party does not have notice of the dissociation and reasonably believes that the person is a general partner; and

.. The act:

... Is appropriate for winding up the limited partnership's activities; or

... Would have bound the limited partnership under RCW 25.10.381 before dissolution and at the time the other party enters into the transaction the other party does not have notice of the dissolution.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20804[2009 c 188 § 804]; ]

== 25.10.591 - Liability after dissolution of general partner and person dissociated as general partner to limited partnership, other general partners, and persons dissociated as general partner.
. If a general partner having knowledge of the dissolution causes a limited partnership to incur an obligation under RCW 25.10.586(1) by an act that is not appropriate for winding up the partnership's activities, the general partner is liable:

.. To the limited partnership for any damage caused to the limited partnership arising from the obligation; and

.. If another general partner or a person dissociated as a general partner is liable for the obligation, to that other general partner or person for any damage caused to that other general partner or person arising from the liability.

. If a person dissociated as a general partner causes a limited partnership to incur an obligation under RCW 25.10.586(2), the person is liable:

.. To the limited partnership for any damage caused to the limited partnership arising from the obligation; and

.. If a general partner or another person dissociated as a general partner is liable for the obligation, to the general partner or other person for any damage caused to the general partner or other person arising from the liability.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20805[2009 c 188 § 805]; ]

== 25.10.596 - Known claims against dissolved limited partnership.
. A dissolved limited partnership may dispose of the known claims against it by following the procedure described in subsection (2) of this section.

. A dissolved limited partnership may notify its known claimants of the dissolution in a record. The notice must:

.. Specify the information required to be included in a claim;

.. Provide a mailing address to which the claim is to be sent;

.. State the deadline for receipt of the claim, which may not be less than one hundred twenty days after the date the notice is received by the claimant;

.. State that the claim will be barred if not received by the deadline; and

.. Unless the limited partnership has been throughout its existence a limited liability limited partnership, state that the barring of a claim against the limited partnership will also bar any corresponding claim against any general partner or person dissociated as a general partner that is based on RCW 25.10.401.

. A claim against a dissolved limited partnership is barred if the requirements of subsection (2) of this section are met and:

.. The claim is not received by the specified deadline; or

.. In the case of a claim that is timely received but rejected by the dissolved limited partnership, the claimant does not commence an action to enforce the claim against the limited partnership within ninety days after the receipt of the notice of the rejection.

. This section does not apply to a claim based on an event occurring after the effective date of dissolution or a liability that is contingent on that date.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20806[2009 c 188 § 806]; ]

== 25.10.601 - Other claims against dissolved limited partnership.
. A dissolved limited partnership may publish notice of its dissolution and request persons having claims against the limited partnership to present them in accordance with the notice.

. The notice must:

.. Be published at least once in a newspaper of general circulation in the county in which the dissolved limited partnership's principal office is located or, if it has none in this state, in the county in which the limited partnership's designated office is or was last located;

.. Describe the information required to be contained in a claim and provide a mailing address to which the claim is to be sent;

.. State that a claim against the limited partnership is barred unless an action to enforce the claim is commenced within three years after publication of the notice; and

.. Unless the limited partnership has been throughout its existence a limited liability limited partnership, state that the barring of a claim against the limited partnership will also bar any corresponding claim against any general partner or person dissociated as a general partner that is based on RCW 25.10.401.

. If a dissolved limited partnership publishes a notice in accordance with subsection (2) of this section, the claim of each of the following claimants is barred unless the claimant commences an action to enforce the claim against the dissolved limited partnership within three years after the publication date of the notice:

.. A claimant that did not receive notice in a record under RCW 25.10.596;

.. A claimant whose claim was timely sent to the dissolved limited partnership but not acted on; and

.. A claimant whose claim is contingent or based on an event occurring after the effective date of dissolution.

. A claim not barred under this section may be enforced:

.. Against the dissolved limited partnership, to the extent of its undistributed assets;

.. If the assets have been distributed in liquidation, against a partner or transferee to the extent of that person's proportionate share of the claim or the limited partnership's assets distributed to the partner or transferee in liquidation, whichever is less, but a person's total liability for all claims under this subsection (4)(b) does not exceed the total amount of assets distributed to the person as part of the winding up of the dissolved limited partnership; or

.. Against any person liable on the claim under RCW 25.10.401.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20807[2009 c 188 § 807]; ]

== 25.10.606 - Liability of general partner and person dissociated as general partner when claim against limited partnership barred.
If a claim against a dissolved limited partnership is barred under RCW 25.10.596 or 25.10.601, any corresponding claim under RCW 25.10.401 is also barred.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20808[2009 c 188 § 808]; ]

== 25.10.611 - Administrative dissolution.
The secretary of state may dissolve a limited partnership administratively under the circumstances and procedures specified in Article 6 of chapter 23.95 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206118[2015 c 176 § 6118]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20809[2009 c 188 § 809]; ]

== 25.10.616 - Reinstatement following administrative dissolution.
A limited partnership that has been administratively dissolved may apply to the secretary of state for reinstatement in accordance with RCW 23.95.615.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206119[2015 c 176 § 6119]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20810[2009 c 188 § 810]; ]

== 25.10.621 - Disposition of assets—When contributions required.
. In winding up a limited partnership's activities, the assets of the limited partnership, including the contributions required by this section, must be applied to satisfy the limited partnership's obligations to creditors including, to the extent permitted by law, partners that are creditors.

. Any surplus remaining after the limited partnership complies with subsection (1) of this section must be paid in cash as a distribution.

. If a limited partnership's assets are insufficient to satisfy all of its obligations under subsection (1) of this section, with respect to each unsatisfied obligation incurred when the limited partnership was not a limited liability limited partnership, the following rules apply:

.. Each person that was a general partner when the obligation was incurred and that has not been released from the obligation under RCW 25.10.541 shall contribute to the limited partnership for the purpose of enabling the limited partnership to satisfy the obligation. The contribution due from each of those persons is in proportion to the right to receive distributions in the capacity of general partner in effect for each of those persons when the obligation was incurred.

.. If a person does not contribute the full amount required under (a) of this subsection with respect to an unsatisfied obligation of the limited partnership, the other persons required to contribute by (a) of this subsection on account of the obligation shall contribute the additional amount necessary to discharge the obligation. The additional contribution due from each of those other persons is in proportion to the right to receive distributions in the capacity of general partner in effect for each of those other persons when the obligation was incurred.

.. If a person does not make the additional contribution required by (b) of this subsection, further additional contributions are determined and due in the same manner as provided in (b) of this subsection.

. A person that makes an additional contribution under subsection (3)(b) or (c) of this section may recover from any person whose failure to contribute under subsection (3)(a) or (b) of this section necessitated the additional contribution. A person may not recover under this subsection more than the amount additionally contributed. A person's liability under this subsection may not exceed the amount the person failed to contribute.

. The estate of a deceased individual is liable for the person's obligations under this section.

. An assignee for the benefit of creditors of a limited partnership or a partner, or a person appointed by a court to represent creditors of a limited partnership or a partner, may enforce a person's obligation to contribute under subsection (3) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20811[2009 c 188 § 811]; ]

== 25.10.641 - Effect of registration and governing law.
A foreign limited partnership that registers to transact business in this state is subject to RCW 23.95.500 relating to the effect of registration and the governing law for registered foreign limited partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206120[2015 c 176 § 6120]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20901[2009 c 188 § 901]; ]

== 25.10.646 - Registration with the secretary of state.
Before transacting business in this state, a foreign limited partnership shall register with the secretary of state in accordance with Article 5 of chapter 23.95 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206121[2015 c 176 § 6121]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20902[2009 c 188 § 902]; ]

== 25.10.651 - Activities not constituting transacting business.
A nonexhaustive list of activities of a foreign limited partnership that do not constitute transacting business in this state is provided in RCW 23.95.520.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206122[2015 c 176 § 6122]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20903[2009 c 188 § 903]; ]

== 25.10.661 - Name of foreign limited partnership.
The name of a foreign limited partnership registered in this state must comply with the provisions of RCW 23.95.525 and Article 3 of chapter 23.95 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206123[2015 c 176 § 6123]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20905[2009 c 188 § 905]; ]

== 25.10.666 - Termination of registration.
The secretary of state may terminate the registration of a registered foreign limited partnership in accordance with RCW 23.95.550.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206124[2015 c 176 § 6124]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20906[2009 c 188 § 906]; ]

== 25.10.671 - Withdrawal of registration.
In order to withdraw its registration, a foreign limited partnership must deliver to the secretary of state for filing a statement of withdrawal in accordance with RCW 23.95.530.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206125[2015 c 176 § 6125]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%20907[2009 c 188 § 907]; ]

== 25.10.701 - Direct action by partner.
. Subject to subsection (2) of this section, a partner may maintain a direct action against the limited partnership or another partner for legal or equitable relief, with or without an accounting as to the partnership's activities, to enforce the rights and otherwise protect the interests of the partner, including rights and interests under the partnership agreement or this chapter or arising independently of the partnership relationship.

. A partner commencing a direct action under this section is required to plead and prove an actual or threatened injury that is not solely the result of an injury suffered or threatened to be suffered by the limited partnership.

. The accrual of, and any time limitation on, a right of action for a remedy under this section is governed by other law. A right to an accounting upon a dissolution and winding up does not revive a claim barred by law.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201001[2009 c 188 § 1001]; ]

== 25.10.706 - Derivative action.
A partner may maintain a derivative action to enforce a right of a limited partnership if:

. The partner first makes a demand on the general partners, requesting that they cause the limited partnership to bring an action to enforce the right, and the general partners do not bring the action within a reasonable time; or

. A demand would be futile.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201002[2009 c 188 § 1002]; ]

== 25.10.711 - Proper plaintiff.
A derivative action may be maintained only by a person that is a partner at the time the action is commenced and:

. That was a partner when the conduct giving rise to the action occurred; or

. Whose status as a partner devolved upon the person by operation of law or pursuant to the terms of the partnership agreement from a person that was a partner at the time of the conduct.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201003[2009 c 188 § 1003]; ]

== 25.10.716 - Pleading.
In a derivative action, the complaint must state with particularity:

. The date and content of plaintiff's demand and the general partners' response to the demand; or

. Why a demand should be excused as futile.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201004[2009 c 188 § 1004]; ]

== 25.10.721 - Proceeds and expenses.
. Except as otherwise provided in subsection (2) of this section:

.. Any proceeds or other benefits of a derivative action, whether by judgment, compromise, or settlement, belong to the limited partnership and not to the derivative plaintiff;

.. If the derivative plaintiff receives any proceeds, the derivative plaintiff shall immediately remit them to the limited partnership.

. If a derivative action is successful in whole or in part, the court may award the plaintiff reasonable expenses, including reasonable attorneys' fees, from the recovery of the limited partnership.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201005[2009 c 188 § 1005]; ]

== 25.10.751 - Definitions.
In this article:

. "Constituent limited partnership" means a constituent organization that is a limited partnership.

. "Constituent organization" means an organization that is party to a merger.

. "Converted organization" means the organization into which a converting organization converts pursuant to RCW 25.10.756 through 25.10.771.

. "Converting limited partnership" means a converting organization that is a limited partnership.

. "Converting organization" means an organization that converts into another organization pursuant to RCW 25.10.756.

. "General partner" means a general partner of a limited partnership.

. "Governing statute" of an organization means the statute that governs the organization's internal affairs.

. "Organization" means a general partnership, including a limited liability partnership; limited partnership, including a limited liability limited partnership; limited liability company; business trust; corporation; or any other person having a governing statute. The term includes domestic and foreign organizations whether or not organized for profit.

. "Organizational documents" means:

.. For a domestic or foreign general partnership, its partnership agreement;

.. For a limited partnership or foreign limited partnership, its certificate of limited partnership and partnership agreement;

.. For a domestic or foreign limited liability company, its certificate of formation and limited liability company agreement, or comparable records as provided in its governing statute;

.. For a business trust, its agreement of trust and declaration of trust;

.. For a domestic or foreign corporation for profit, its articles of incorporation, bylaws, and other agreements among its shareholders that are authorized by its governing statute, or comparable records as provided in its governing statute; and

.. For any other organization, the basic records that create the organization and determine its internal governance and the relations among the persons that own it, have an interest in it, or are members of it.

. "Personal liability" means personal liability for a debt, liability, or other obligation of an organization that is imposed on a person that co-owns, has an interest in, or is a member of the organization:

.. By the organization's governing statute solely by reason of the person co-owning, having an interest in, or being a member of the organization; or

.. By the organization's organizational documents under a provision of the organization's governing statute authorizing those documents to make one or more specified persons liable for all or specified debts, liabilities, and other obligations of the organization solely by reason of the person or persons co-owning, having an interest in, or being a member of the organization.

. "Surviving organization" means an organization into which one or more other organizations are merged.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201101[2009 c 188 § 1101]; ]

== 25.10.756 - Conversion.
. An organization other than a limited partnership may convert into a limited partnership, and a limited partnership may convert into another organization pursuant to this section and RCW 25.10.761 through 25.10.771 and a plan of conversion, if:

.. The other organization's governing statute authorizes the conversion;

.. The conversion is not prohibited by the law of the jurisdiction that enacted the governing statute; and

.. The other organization complies with its governing statute in effecting the conversion.

. A plan of conversion must be in a record and must include:

.. The name and form of the organization before conversion;

.. The name and form of the organization after conversion;

.. The terms and conditions of the conversion, including the manner and basis for converting interests in the converting organization into any combination of money, interests in the converted organization, and other consideration; and

.. The organizational documents of the converted organization.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201102[2009 c 188 § 1102]; ]

== 25.10.761 - Action on plan of conversion by converting limited partnership.
. Subject to RCW 25.10.796, a plan of conversion must be consented to by all the partners of a converting limited partnership.

. Subject to RCW 25.10.796 and any contractual rights, after a conversion is approved, and at any time before a filing is made under RCW 25.10.766, a converting limited partnership may amend the plan or abandon the planned conversion:

.. As provided in the plan; and

.. Except as prohibited by the plan, by the same consent as was required to approve the plan.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201103[2009 c 188 § 1103]; ]

== 25.10.766 - Filings required for conversion—Effective date.
. After a plan of conversion is approved:

.. A converting limited partnership shall deliver to the secretary of state for filing articles of conversion, which must include:

... A statement that the limited partnership has been converted into another organization;

... The name and form of the organization and the jurisdiction of its governing statute;

... The date the conversion is effective under the governing statute of the converted organization;

... A statement that the conversion was approved as required by this chapter;

.. A statement that the conversion was approved as required by the governing statute of the converted organization; and

.. If the converted organization is a foreign organization not registered to transact business in this state, the street and mailing address of the organization's principal office that may be used for service of process under RCW 23.95.450; and

.. If the converting organization is not a converting limited partnership, the converting organization shall deliver to the secretary of state for filing a certificate of limited partnership, which must include, in addition to the information required by RCW 25.10.201:

... A statement that the limited partnership was converted from another organization;

... The name and form of the organization and the jurisdiction of its governing statute; and

... A statement that the conversion was approved in a manner that complied with the organization's governing statute.

. A conversion becomes effective:

.. If the converted organization is a limited partnership, when the certificate of limited partnership takes effect; and

.. If the converted organization is not a limited partnership, as provided by the governing statute of the converted organization.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206126[2015 c 176 § 6126]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201104[2009 c 188 § 1104]; ]

== 25.10.771 - Effect of conversion.
. An organization that has been converted pursuant to this article is for all purposes the same entity that existed before the conversion.

. When a conversion takes effect:

.. All property owned by the converting organization remains vested in the converted organization;

.. All debts, liabilities, and other obligations of the converting organization continue as obligations of the converted organization;

.. An action or proceeding pending by or against the converting organization may be continued as if the conversion had not occurred;

.. Except as prohibited by other law, all of the rights, privileges, immunities, powers, and purposes of the converting organization remain vested in the converted organization;

.. Except as otherwise provided in the plan of conversion, the terms and conditions of the plan of conversion take effect; and

.. Except as otherwise agreed, the conversion does not dissolve a converting limited partnership for the purposes of article 8 of this chapter.

. A converted organization that is a foreign organization consents to the jurisdiction of the courts of this state to enforce any obligation owed by the converting limited partnership, if before the conversion the converting limited partnership was subject to suit in this state on the obligation. A converted organization that is a foreign organization and not registered to transact business in this state may be served with process pursuant to RCW 23.95.450 for purposes of enforcing an obligation under this subsection.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206127[2015 c 176 § 6127]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201105[2009 c 188 § 1105]; ]

== 25.10.776 - Merger.
. A limited partnership may merge with one or more other constituent organizations pursuant to this section and RCW 25.10.781 through 25.10.791 and a plan of merger, if:

.. The governing statute of each of the other organizations authorizes the merger;

.. The merger is not prohibited by the law of a jurisdiction that enacted any of those governing statutes; and

.. Each of the other organizations complies with its governing statute in effecting the merger.

. A plan of merger must be in a record and must include:

.. The name and form of each constituent organization;

.. The name and form of the surviving organization;

.. The terms and conditions of the merger, including the manner and basis for converting the interests in each constituent organization into any combination of money, interests in the surviving organization, and other consideration; and

.. Any amendments to be made by the merger to the surviving organization's organizational documents.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201106[2009 c 188 § 1106]; ]

== 25.10.781 - Action on plan of merger by constituent limited partnership.
. Subject to RCW 25.10.796, a plan of merger must be consented to by all the partners of a constituent limited partnership.

. Subject to RCW 25.10.796 and any contractual rights, after a merger is approved, and at any time before a filing is made under RCW 25.10.786, a constituent limited partnership may amend the plan or abandon the planned merger:

.. As provided in the plan; and

.. Except as prohibited by the plan, with the same consent as was required to approve the plan.

. If a domestic corporation is a party to the merger, the plan of merger shall be adopted and approved as provided in chapter 23B.11 RCW.

. If a domestic partnership is a party to the merger, the plan of merger shall be approved as provided in RCW 25.05.375.

. If a domestic limited liability company is a party to the merger, the plan of merger shall be approved as provided in RCW 25.15.421.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5030-S.SL.pdf?cite=2015%20c%20188%20§%20118[2015 c 188 § 118]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201107[2009 c 188 § 1107]; ]

== 25.10.786 - Filings required for merger—Effective date.
. After each constituent organization has approved a merger, articles of merger must be signed on behalf of:

.. Each constituent limited partnership, by each general partner listed in the certificate of limited partnership; and

.. Each other constituent organization, by an authorized representative.

. The articles of merger must include:

.. The name and form of each constituent organization and the jurisdiction of its governing statute;

.. The name and form of the surviving organization and the jurisdiction of its governing statute;

.. The date the merger is effective under the governing statute of the surviving organization;

.. Any amendments provided for in the plan of merger for the organizational document that created the surviving organization;

.. A statement as to each constituent organization that the merger was approved as required by the organization's governing statute;

.. If the surviving organization is a foreign organization not registered to transact business in this state, the street and mailing address of the organization's principal office that may be used for service of process under RCW 23.95.450; and

.. Any additional information required by the governing statute of any constituent organization.

. Each constituent limited partnership shall deliver the articles of merger for filing in the office of the secretary of state.

. A merger becomes effective under this article:

.. If the surviving organization is a limited partnership, upon the later of:

... Compliance with subsection (3) of this section; or

... Subject to RCW 25.10.251(2), as specified in the articles of merger; or

.. If the surviving organization is not a limited partnership, as provided by the governing statute of the surviving organization.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206128[2015 c 176 § 6128]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201108[2009 c 188 § 1108]; ]

== 25.10.791 - Effect of merger.
. When a merger becomes effective:

.. The surviving organization continues;

.. Each constituent organization that merges into the surviving organization ceases to exist as a separate entity;

.. All property owned by each constituent organization that ceases to exist vests in the surviving organization;

.. All debts, liabilities, and other obligations of each constituent organization that ceases to exist continue as obligations of the surviving organization;

.. An action or proceeding pending by or against any constituent organization that ceases to exist may be continued as if the merger had not occurred;

.. Except as prohibited by other law, all of the rights, privileges, immunities, powers, and purposes of each constituent organization that ceases to exist vest in the surviving organization;

.. Except as otherwise provided in the plan of merger, the terms and conditions of the plan of merger take effect;

.. Except as otherwise agreed, if a constituent limited partnership ceases to exist, the merger does not dissolve the limited partnership for the purposes of article 8 of this chapter; and

.. Any amendments provided for in the articles of merger for the organizational document that created the surviving organization become effective.

. A surviving organization that is a foreign organization consents to the jurisdiction of the courts of this state to enforce any obligation owed by a constituent organization, if before the merger the constituent organization was subject to suit in this state on the obligation. A surviving organization that is a foreign organization and not registered to transact business in this state may be served with process pursuant to RCW 23.95.450 for the purposes of enforcing an obligation under this subsection.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206129[2015 c 176 § 6129]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201109[2009 c 188 § 1109]; ]

== 25.10.796 - Restrictions on approval of conversions and mergers and on relinquishing LLLP status.
. If a partner of a converting or constituent limited partnership will have personal liability with respect to a converted or surviving organization, approval and amendment of a plan of conversion or merger are ineffective without the consent of the partner, unless:

.. The limited partnership's partnership agreement provides for the approval of the conversion or merger with the consent of fewer than all the partners; and

.. The partner has consented to the provision of the partnership agreement.

. An amendment to a certificate of limited partnership that deletes a statement that the limited partnership is a limited liability limited partnership is ineffective without the consent of each general partner unless:

.. The limited partnership's partnership agreement provides for the amendment with the consent of less than all the general partners; and

.. Each general partner that does not consent to the amendment has consented to the provision of the partnership agreement.

. A partner does not give the consent required by subsection (1) or (2) of this section merely by consenting to a provision of the partnership agreement that permits the partnership agreement to be amended with the consent of fewer than all the partners.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201110[2009 c 188 § 1110]; ]

== 25.10.801 - Liability of general partner after conversion or merger.
. A conversion or merger under this article does not discharge any liability under RCW 25.10.401 and 25.10.541 of a person that was a general partner in or dissociated as a general partner from a converting or constituent limited partnership, but:

.. The provisions of this chapter pertaining to the collection or discharge of the liability continue to apply to the liability;

.. For the purposes of applying those provisions, the converted or surviving organization is deemed to be the converting or constituent limited partnership; and

.. If a person is required to pay any amount under this subsection:

... The person has a right of contribution from each other person that was liable as a general partner under RCW 25.10.401 when the obligation was incurred and has not been released from the obligation under RCW 25.10.541; and

... The contribution due from each of those persons is in proportion to the right to receive distributions in the capacity of general partner in effect for each of those persons when the obligation was incurred.

. In addition to any other liability provided by law:

.. A person that immediately before a conversion or merger became effective was a general partner in a converting or constituent limited partnership that was not a limited liability limited partnership is personally liable for each obligation of the converted or surviving organization arising from a transaction with a third party after the conversion or merger becomes effective, if, at the time the third party enters into the transaction, the third party:

... Does not have notice of the conversion or merger; and

... Reasonably believes that:

(A) The converted or surviving business is the converting or constituent limited partnership;

(B) The converting or constituent limited partnership is not a limited liability limited partnership; and

(C) The person is a general partner in the converting or constituent limited partnership; and

.. A person that was dissociated as a general partner from a converting or constituent limited partnership before the conversion or merger became effective is personally liable for each obligation of the converted or surviving organization arising from a transaction with a third party after the conversion or merger becomes effective, if:

... Immediately before the conversion or merger became effective the converting or surviving limited partnership was not a limited liability limited partnership; and

... At the time the third party enters into the transaction, less than two years have passed since the person dissociated as a general partner and the third party:

(A) Does not have notice of the dissociation;

(B) Does not have notice of the conversion or merger; and

(C) Reasonably believes that the converted or surviving organization is the converting or constituent limited partnership, the converting or constituent limited partnership is not a limited liability limited partnership, and the person is a general partner in the converting or constituent limited partnership.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201111[2009 c 188 § 1111]; ]

== 25.10.806 - Power of general partners and persons dissociated as general partners to bind organization after conversion or merger.
. An act of a person that immediately before a conversion or merger became effective was a general partner in a converting or constituent limited partnership binds the converted or surviving organization after the conversion or merger becomes effective, if:

.. Before the conversion or merger became effective, the act would have bound the converting or constituent limited partnership under RCW 25.10.381; and

.. At the time the third party enters into the transaction, the third party:

... Does not have notice of the conversion or merger; and

... Reasonably believes that the converted or surviving business is the converting or constituent limited partnership and that the person is a general partner in the converting or constituent limited partnership.

. An act of a person that before a conversion or merger became effective was dissociated as a general partner from a converting or constituent limited partnership binds the converted or surviving organization after the conversion or merger becomes effective, if:

.. Before the conversion or merger became effective, the act would have bound the converting or constituent limited partnership under RCW 25.10.381 if the person had been a general partner; and

.. At the time the third party enters into the transaction, less than two years have passed since the person dissociated as a general partner and the third party:

... Does not have notice of the dissociation;

... Does not have notice of the conversion or merger; and

... Reasonably believes that the converted or surviving organization is the converting or constituent limited partnership and that the person is a general partner in the converting or constituent limited partnership.

. If a person having knowledge of the conversion or merger causes a converted or surviving organization to incur an obligation under subsection (1) or (2) of this section, the person is liable:

.. To the converted or surviving organization for any damage caused to the organization arising from the obligation; and

.. If another person is liable for the obligation, to that other person for any damage caused to that other person arising from the liability.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201112[2009 c 188 § 1112]; ]

== 25.10.811 - Article not exclusive.
This article does not preclude an entity from being converted or merged under other law.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201113[2009 c 188 § 1113]; ]

== 25.10.831 - Definitions.
In this article:

. "Dissenter" means a partner who is entitled to dissent from a plan of merger and who exercises that right when and in the manner required by this article.

. "Fair value," with respect to a dissenter's partnership interest, means the value of the partnership interest immediately before the effectuation of the merger to which the dissenter objects, excluding any appreciation or depreciation in anticipation of the merger unless exclusion would be inequitable.

. "Interest" means interest from the effective date of the merger until the date of payment, at the average rate currently paid by the limited partnership on its principal bank loans or, if none, at a rate that is fair and equitable under all the circumstances.

. "Limited partnership" means the domestic limited partnership in which the dissenter holds or held a partnership interest, or the surviving organization, whether foreign or domestic, of that limited partnership.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201201[2009 c 188 § 1201]; ]

== 25.10.836 - Partner—Dissent—Payment of fair value.
. Except as provided in RCW 25.10.846 or 25.10.856(2), a partner of a domestic limited partnership is entitled to dissent from, and obtain payment of, the fair value of the partner's partnership interest in the event of consummation of a plan of merger to which the limited partnership is a party as permitted by RCW 25.10.776.

. A partner entitled to dissent and obtain payment for the partner's partnership interest under this article may not challenge the merger creating the partner's entitlement unless the merger fails to comply with the procedural requirements imposed by this chapter, Title 23B RCW, chapter 25.05 RCW, chapter 25.15 RCW, or the partnership agreement, or is fraudulent with respect to the partner or the limited partnership.

. The right of a dissenting partner to obtain payment of the fair value of the partner's partnership interest shall terminate upon the occurrence of any one of the following events:

.. The proposed merger is abandoned or rescinded;

.. A court having jurisdiction permanently enjoins or sets aside the merger; or

.. The partner's demand for payment is withdrawn with the written consent of the limited partnership.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201202[2009 c 188 § 1202]; ]

== 25.10.841 - Dissenters' rights—Notice—Timing.
. Not less than ten days prior to the approval of a plan of merger, the limited partnership must send a written notice to all partners who are entitled to vote on or approve the plan of merger that they may be entitled to assert dissenters' rights under this article. Such notice shall be accompanied by a copy of this article.

. The limited partnership shall notify in writing all partners not entitled to vote on or approve the plan of merger that the plan of merger was approved, and send them the dissenters' notice as required by RCW 25.10.851.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201203[2009 c 188 § 1203]; ]

== 25.10.846 - Partner—Dissent—Voting restriction.
A partner who is entitled to vote on or approve the plan of merger and who wishes to assert dissenters' rights must not vote in favor of or approve the plan of merger. A partner who does not satisfy the requirements of this section is not entitled to payment for the partner's interest under this article.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201204[2009 c 188 § 1204]; ]

== 25.10.851 - Partners—Dissenters' notice—Requirements.
. If the plan of merger is approved, the limited partnership shall deliver a written dissenters' notice to all partners who satisfied the requirements of RCW 25.10.846.

. The dissenters' notice required by RCW 25.10.841(2) or by subsection (1) of this section must be sent within ten days after the approval of the plan of merger, and must:

.. State where the payment demand must be sent;

.. Inform holders of the partnership interest as to the extent transfer of the partnership interest will be restricted as permitted by RCW 25.10.861 after the payment demand is received;

.. Supply a form for demanding payment;

.. Set a date by which the limited partnership must receive the payment demand, which date may not be fewer than thirty nor more than sixty days after the date the notice under this section is delivered; and

.. Be accompanied by a copy of this article.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201205[2009 c 188 § 1205]; ]

== 25.10.856 - Partner—Payment demand—Entitlement.
. A partner who demands payment retains all other rights of a partner until the proposed merger becomes effective.

. A partner sent a dissenters' notice who does not demand payment by the date set in the dissenters' notice is not entitled to payment for the partner's partnership interest under this article.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201206[2009 c 188 § 1206]; ]

== 25.10.861 - Partnership interests—Transfer restrictions.
The limited partnership may restrict the transfer of partnership interests from the date the demand for their payment is received until the proposed merger becomes effective or the restriction is released under this article.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201207[2009 c 188 § 1207]; ]

== 25.10.866 - Payment of fair value—Requirements for compliance.
. Within thirty days of the later of the date the proposed merger becomes effective, or the payment demand is received, the limited partnership shall pay each dissenter who complied with RCW 25.10.856 the amount the limited partnership estimates to be the fair value of the partnership interest, plus accrued interest.

. The payment must be accompanied by:

.. Copies of any financial statements for the most recent fiscal year maintained as required by RCW 25.10.091;

.. An explanation of how the limited partnership estimated the fair value of the partnership interest;

.. An explanation of how the accrued interest was calculated;

.. A statement of the dissenter's right to demand payment; and

.. A copy of this article.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201208[2009 c 188 § 1208]; ]

== 25.10.871 - Merger—Not effective within sixty days—Transfer restrictions.
. If the proposed merger does not become effective within sixty days after the date set for demanding payment, the limited partnership shall release any transfer restrictions imposed as permitted by RCW 25.10.861.

. If, after releasing transfer restrictions, the proposed merger becomes effective, the limited partnership must send a new dissenters' notice as provided in RCW 25.10.841(2) and 25.10.851 and repeat the payment demand procedure.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201209[2009 c 188 § 1209]; ]

== 25.10.876 - Dissenter's estimate of fair value—Notice.
. A dissenter may notify the limited partnership in writing of the dissenter's own estimate of the fair value of the dissenter's partnership interest and amount of interest due, and demand payment of the dissenter's estimate, less any payment under RCW 25.10.866; if:

.. The dissenter believes that the amount paid is less than the fair value of the dissenter's partnership interest or that the interest due is incorrectly calculated;

.. The limited partnership fails to make payment within sixty days after the date set for demanding payment; or

.. The limited partnership, having failed to effectuate the proposed merger, does not release the transfer restrictions imposed on partnership interests as permitted by RCW 25.10.861 within sixty days after the date set for demanding payment.

. A dissenter waives the right to demand payment under this section unless the dissenter notifies the limited partnership of the dissenter's demand in writing under subsection (1)(a) of this section within thirty days after the limited partnership made payment for the dissenter's partnership interest.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201210[2009 c 188 § 1210]; ]

== 25.10.881 - Unsettled demand for payment—Proceeding—Parties—Appraisers.
. If a demand for payment under RCW 25.10.876 remains unsettled, the limited partnership shall commence a proceeding within sixty days after receiving the payment demand and petition the court to determine the fair value of the partnership interest and accrued interest. If the limited partnership does not commence the proceeding within the sixty-day period, it shall pay each dissenter whose demand remains unsettled the amount demanded.

. The limited partnership shall commence the proceeding in the superior court in the county where its office is or was maintained as required by RCW 25.10.121.

. The limited partnership shall make all dissenters, whether or not residents of this state, whose demands remain unsettled parties to the proceeding as in an action against their partnership interests and all parties must be served with a copy of the petition. Nonresidents may be served by registered or certified mail or by publication as provided by law.

. The limited partnership may join as a party to the proceeding any partner who claims to be a dissenter but who has not, in the opinion of the limited partnership, complied with the provisions of this chapter. If the court determines that such partner has not complied with the provisions of this article, the partner shall be dismissed as a party.

. The jurisdiction of the court in which the proceeding is commenced is plenary and exclusive. The court may appoint one or more persons as appraisers to receive evidence and recommend decisions on the question of fair value. The appraisers have the powers described in the order appointing them or in any amendment to it. The dissenters are entitled to the same discovery rights as parties in other civil proceedings.

. Each dissenter made a party to the proceeding is entitled to judgment for the amount, if any, by which the court finds the fair value of the dissenter's partnership interest, plus interest, exceeds the amount paid by the limited partnership.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201211[2009 c 188 § 1211]; ]

== 25.10.886 - Unsettled demand for payment—Costs, fees, and expenses of counsel.
. The court in a proceeding commenced under RCW 25.10.881 shall determine all costs of the proceeding, including the reasonable compensation and expenses of appraisers appointed by the court. The court shall assess the costs against the limited partnership, except that the court may assess the costs against all or some of the dissenters, in amounts the court finds equitable, to the extent the court finds the dissenters acted arbitrarily, vexatiously, or not in good faith in demanding payment.

. The court may also assess the fees and expenses of counsel and experts for the respective parties, in amounts the court finds equitable:

.. Against the limited partnership and in favor of any or all dissenters if the court finds the limited partnership did not substantially comply with the requirements of this article; or

.. Against either the limited partnership or a dissenter, in favor of any other party, if the court finds that the party against whom the fees and expenses are assessed acted arbitrarily, vexatiously, or not in good faith with respect to the rights provided by this article.

. If the court finds that the services of counsel for any dissenter were of substantial benefit to other dissenters similarly situated, and that the fees for those services should not be assessed against the limited partnership, the court may award to these counsel reasonable fees to be paid out of the amounts awarded the dissenters who were benefited.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201212[2009 c 188 § 1212]; ]

== 25.10.901 - Uniformity of application and construction.
In applying and construing this chapter, consideration must be given to the need to promote uniformity of the law with respect to its subject matter among states that enact it.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201301[2009 c 188 § 1301]; ]

== 25.10.903 - Effective date—2009 c 188.
This chapter takes effect January 1, 2010.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201304[2009 c 188 § 1304]; ]

== 25.10.906 - Relation to electronic signatures in global and national commerce act.
This chapter modifies, limits, or supersedes the federal electronic signatures in global and national commerce act, 15 U.S.C. Sec. 7001 et seq., but this chapter does not modify, limit, or supersede section 101(c) of that chapter or authorize electronic delivery of any of the notices described in section 103(b) of that chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201303[2009 c 188 § 1303]; ]

== 25.10.911 - Application to existing relationships.
. Before July 1, 2010, this chapter governs only:

.. A limited partnership formed on or after January 1, 2010; and

.. Except as otherwise provided in subsections (3) and (4) of this section, a limited partnership formed before January 1, 2010, that elects, in the manner provided in its partnership agreement or by law for amending the partnership agreement, to be subject to this chapter.

. Except as otherwise provided in subsection (3) of this section, on and after July 1, 2010, this chapter governs all limited partnerships.

. With respect to a limited partnership formed before January 1, 2010, the following rules apply except as the partners otherwise elect in the manner provided in the partnership agreement or by law for amending the partnership agreement:

.. RCW 25.10.021(3) does not apply and the limited partnership has whatever duration it had under the law applicable immediately before January 1, 2010.

.. The limited partnership is not required to amend its certificate of limited partnership to comply with RCW 25.10.201(1)(d).

.. RCW 25.10.511 and 25.10.516 do not apply and a limited partner has the same right and power to dissociate from the limited partnership, with the same consequences, as existed immediately before January 1, 2010.

.. RCW 25.10.521(4) does not apply.

.. RCW 25.10.521(5) does not apply and a court has the same power to expel a general partner as the court had immediately before January 1, 2010.

.. RCW 25.10.571(3) does not apply and the connection between a person's dissociation as a general partner and the dissolution of the limited partnership is the same as existed immediately before January 1, 2010.

. With respect to a limited partnership that elects pursuant to subsection (1)(b) of this section to be subject to this chapter, after the election takes effect the provisions of this chapter relating to the liability of the limited partnership's general partners to third parties apply:

.. Before July 1, 2010, to:

... A third party that had not done business with the limited partnership in the year before the election took effect; and

... A third party that had done business with the limited partnership in the year before the election took effect only if the third party knows or has received a notification of the election; and

.. On and after July 1, 2010, to all third parties, but those provisions remain inapplicable to any obligation incurred while those provisions were inapplicable under (a)(ii) of this subsection.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201306[2009 c 188 § 1306]; ]

== 25.10.916 - Applicable fees, charges, and penalties.
Limited partnerships are subject to the applicable fees, charges, and penalties adopted by the secretary of state under RCW 23.95.260 and 43.07.120.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5387.SL.pdf?cite=2015%20c%20176%20§%206130[2015 c 176 § 6130]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201307[2009 c 188 § 1307]; ]

== 25.10.921 - Authority to adopt rules.
The secretary of state has the power and authority reasonably necessary for the efficient and effective administration of this chapter, including the adoption of rules under chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201308[2009 c 188 § 1308]; ]

== 25.10.926 - Savings clause.
This chapter does not affect an action commenced, proceeding brought, or right accrued before January 1, 2010.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1067-S.SL.pdf?cite=2009%20c%20188%20§%201309[2009 c 188 § 1309]; ]

