= 69.07 - Washington food processing act.
:toc:

== 69.07.005 - Legislative declaration.
The processing of food intended for public consumption is important and vital to the health and welfare both immediate and future and is hereby declared to be a business affected with the public interest. The provisions of this chapter [1991 c 137] are enacted to safeguard the consuming public from unsafe, adulterated, or misbranded food by requiring licensing of all food processing plants as defined in this chapter and setting forth the requirements for such licensing.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1957-S.SL.pdf?cite=1991%20c%20137%20§%201[1991 c 137 § 1]; ]

== 69.07.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Board" means the state liquor and cannabis board.

. "Department" means the department of agriculture of the state of Washington.

. "Director" means the director of the department.

. "Food" means any substance used for food or drink by any person, including ice, bottled water, and any ingredient used for components of any such substance regardless of the quantity of such component.

. "Food processing" means the handling or processing of any food in any manner in preparation for sale for human consumption: PROVIDED, That it shall not include fresh fruit or vegetables merely washed or trimmed while being prepared or packaged for sale in their natural state.

. "Food processing plant" includes but is not limited to any premises, plant, establishment, building, room, area, facilities and the appurtenances thereto, in whole or in part, where food is prepared, handled or processed in any manner for distribution or sale for resale by retail outlets, restaurants, and any such other facility selling or distributing to the ultimate consumer: PROVIDED, That, as set forth herein, establishments processing foods in any manner for resale shall be considered a food processing plant as to such processing.

. "Food service establishment" shall mean any fixed or mobile restaurant, coffee shop, cafeteria, short order cafe, luncheonette, grill, tearoom, sandwich shop, soda fountain, tavern, bar, cocktail lounge, night club, roadside stand, industrial-feeding establishment, retail grocery, retail food market, retail meat market, retail bakery, private, public, or nonprofit organization routinely serving food, catering kitchen, commissary or similar place in which food or drink is prepared for sale or for service on the premises or elsewhere, and any other eating or drinking establishment or operation where food is served or provided for the public with or without charge.

For the purpose of this chapter any custom cannery or processing plant where raw food products, food, or food products are processed for the owner thereof, or the food processing facilities are made available to the owners or persons in control of raw food products or food or food products for processing in any manner, shall be considered to be food processing plants.

. "Hemp extract" means a substance or compound intended for human ingestion that is derived from, or made by, processing hemp. The term does not include hemp seeds or hemp seed-derived ingredients that are generally recognized as safe by the United States food and drug administration.

. "Hemp extract certification" means a certification issued by the department to a hemp processor manufacturing hemp extract for export to other states, which certifies the hemp processor's compliance with Washington state's inspection and sanitation requirements.

. "Hemp processor" has same meaning as defined in RCW 15.140.020.

. "Marijuana" has the definition in RCW 69.50.101.

. "Marijuana-infused edible" has the same meaning as "marijuana-infused products" as defined in RCW 69.50.101, but limited to products intended for oral consumption.

. "Marijuana-infused edible processing" means processing, packaging, or making marijuana-infused edibles using marijuana, marijuana extract, or marijuana concentrates as an ingredient. The term does not include preparation of marijuana as an ingredient including, but not limited to, processing marijuana extracts or marijuana concentrates.

. "Marijuana processor" has the definition in RCW 69.50.101.

. "Person" means an individual, partnership, corporation, or association.

. "Sale" means selling, offering for sale, holding for sale, preparing for sale, trading, bartering, offering a gift as an inducement for sale of, and advertising for sale in any media.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5372.SL.pdf?cite=2021%20c%20104%20§%205[2021 c 104 § 5]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1462-S.SL.pdf?cite=2017%20c%20138%20§%201[2017 c 138 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2747-S.SL.pdf?cite=1992%20c%2034%20§%203[1992 c 34 § 3]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1957-S.SL.pdf?cite=1991%20c%20137%20§%202[1991 c 137 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c121.pdf?cite=1967%20ex.s.%20c%20121%20§%201[1967 ex.s. c 121 § 1]; ]

== 69.07.020 - Enforcement—Rules—Adoption—Contents—Standards.
. The department shall enforce and carry out the provisions of this chapter, and may adopt the necessary rules to carry out its purposes.

. Such rules may include:

.. Standards for temperature controls in the storage of foods, so as to provide proper refrigeration.

.. Standards for temperatures at which low acid foods must be processed and the length of time such temperatures must be applied and at what pressure in the processing of such low acid foods.

.. Standards and types of recording devices that must be used in providing records of the processing of low acid foods, and how they shall be made available to the department of agriculture for inspection.

.. Requirements for the keeping of records of the temperatures, times and pressures at which foods were processed, or for the temperatures at which refrigerated products were stored by the licensee and the furnishing of such records to the department.

.. Standards that must be used to establish the temperature and purity of water used in the processing of foods.

. The department may adopt rules specific to marijuana-infused edibles. Such rules must be written and interpreted to be consistent with rules adopted by the board and the department of health.

. The department may adopt rules specific to hemp extract certification to implement RCW 69.07.220.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5372.SL.pdf?cite=2021%20c%20104%20§%207[2021 c 104 § 7]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1462-S.SL.pdf?cite=2017%20c%20138%20§%202[2017 c 138 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c68.pdf?cite=1969%20c%2068%20§%201[1969 c 68 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c121.pdf?cite=1967%20ex.s.%20c%20121%20§%202[1967 ex.s. c 121 § 2]; ]

== 69.07.040 - Food processing license—Waiver if licensed under chapter  15.36 RCW—Expiration date—Application, contents—Fee.
. It is unlawful for any person to operate a food processing plant or process foods in the state without first having obtained an annual license from the department, which shall expire on a date set by rule by the director. License fees shall be prorated where necessary to accommodate staggering of expiration dates. Application for a license shall be on a form prescribed by the director and accompanied by the license fee. The license fee is determined by computing the gross annual sales for the accounting year immediately preceding the license year. If the license is for a new operator, the license fee shall be based on an estimated gross annual sales for the initial license period.

 If gross annual sales are:The license fee is: $0 to $50,000$ 92.00 $50,001 to $500,000$ 147.00 $500,001 to $1,000,000$ 262.00 $1,000,001 to $5,000,000$ 427.00 $5,000,001 to $10,000,000$ 585.00 Greater than $10,000,000$ 862.00

 

If gross annual sales are:

The license fee is:

 

$0 to $50,000

$ 92.00

 

$50,001 to $500,000

$ 147.00

 

$500,001 to $1,000,000

$ 262.00

 

$1,000,001 to $5,000,000

$ 427.00

 

$5,000,001 to $10,000,000

$ 585.00

 

Greater than $10,000,000

$ 862.00

. Applications under this section must include:

.. The full name of the applicant for the license and the location of the food processing plant he or she intends to operate, and if the applicant is an individual, receiver, trustee, firm, partnership, association, or corporation, the full name of each member of the firm or partnership, or names of the officers of the association or corporation;

.. The principal business address of the applicant in the state and elsewhere and the name of a person domiciled in this state authorized to receive and accept service of summons of legal notices of all kinds for the applicant; and

.. The type of food to be processed and the method or nature of processing operation or preservation of that food and any other necessary information.

. Upon the approval of the application by the director and compliance with the provisions of this chapter, including the applicable regulations adopted by the department, the applicant shall be issued a license or renewal.

. Licenses shall be issued to cover only those products, processes, and operations specified in the license application and approved for licensing. Wherever a license holder wishes to engage in processing a type of food product that is different than the type specified on the application supporting the licensee's existing license and processing that type of food product would require a major addition to or modification of the licensee's processing facilities or has a high potential for harm, the licensee must submit an amendment to the current license application. In such a case, the licensee may engage in processing the new type of food product only after the amendment has been approved by the department.

. If upon investigation by the director, it is determined that a person is processing food for retail sale and is not under permit, license, or inspection by a local health authority, then that person may be considered a food processor and subject to the provisions of this chapter.

. The director may waive the licensure requirements of this chapter for a person's operations at a facility if the person has obtained a milk processing plant license under chapter 15.36 RCW to conduct the same or a similar operation at the facility.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2128-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2027%20§%207[2015 3rd sp.s. c 27 § 7]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5315-S.SL.pdf?cite=1995%20c%20374%20§%2021[1995 c 374 § 21]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5983.SL.pdf?cite=1993%20sp.s.%20c%2019%20§%2011[1993 sp.s. c 19 § 11]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5379-S.SL.pdf?cite=1993%20c%20212%20§%202[1993 c 212 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6393-S.SL.pdf?cite=1992%20c%20160%20§%203[1992 c 160 § 3]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1957-S.SL.pdf?cite=1991%20c%20137%20§%203[1991 c 137 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c5.pdf?cite=1988%20c%205%20§%201[1988 c 5 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c68.pdf?cite=1969%20c%2068%20§%202[1969 c 68 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c121.pdf?cite=1967%20ex.s.%20c%20121%20§%204[1967 ex.s. c 121 § 4]; ]

== 69.07.050 - Renewal of license—Additional fee, when.
If the application for renewal of any license provided for under this chapter is not filed prior to the expiration date as established by rule by the director, an additional fee of ten percent of the cost of the license shall be assessed and added to the original fee and shall be paid by the applicant before the renewal license shall be issued: PROVIDED, That such additional fee shall not be charged if the applicant furnishes an affidavit certifying that he or she has not operated a food processing plant or processed foods subsequent to the expiration of his or her license.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6393-S.SL.pdf?cite=1992%20c%20160%20§%204[1992 c 160 § 4]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1957-S.SL.pdf?cite=1991%20c%20137%20§%204[1991 c 137 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c5.pdf?cite=1988%20c%205%20§%202[1988 c 5 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c121.pdf?cite=1967%20ex.s.%20c%20121%20§%205[1967 ex.s. c 121 § 5]; ]

== 69.07.060 - Denial, suspension, or revocation of license—Grounds.
The director may, subsequent to a hearing thereon, deny, suspend, or revoke any license provided for in this chapter if he or she determines that an applicant has committed any of the following acts:

. Refused, neglected, or failed to comply with the provisions of this chapter, the rules and regulations adopted hereunder, or any lawful order of the director.

. Refused, neglected, or failed to keep and maintain records required by this chapter, or to make such records available when requested pursuant to the provisions of this chapter.

. Refused the department access to any portion or area of the food processing plant for the purpose of carrying out the provisions of this chapter.

. Refused the department access to any records required to be kept under the provisions of this chapter.

. Refused, neglected, or failed to comply with any provisions of the food safety and security act under chapter 15.130 RCW, or any rules adopted thereunder.

The provisions of this section requiring that a hearing be conducted before an action may be taken against a license do not apply to an action taken under RCW 69.07.065.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20712[2018 c 236 § 712]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20345[2012 c 117 § 345]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1957-S.SL.pdf?cite=1991%20c%20137%20§%205[1991 c 137 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c154.pdf?cite=1979%20c%20154%20§%2019[1979 c 154 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c121.pdf?cite=1967%20ex.s.%20c%20121%20§%206[1967 ex.s. c 121 § 6]; ]

== 69.07.065 - Suspension of license summarily—Reinstatement.
. Whenever the director finds an establishment operating under conditions that constitute an immediate danger to public health or whenever the licensee or any employee of the licensee actively prevents the director or the director's representative, during an on-site inspection, from determining whether such a condition exists, the director may summarily suspend, pending a hearing, a license provided for in this chapter.

. Whenever a license is summarily suspended, the holder of the license shall be notified in writing that the license is, upon service of the notice, immediately suspended and that prompt opportunity for a hearing will be provided.

. Whenever a license is summarily suspended, food processing operations shall immediately cease. However, the director may reinstate the license when the condition that caused the suspension has been abated to the director's satisfaction.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1957-S.SL.pdf?cite=1991%20c%20137%20§%206[1991 c 137 § 6]; ]

== 69.07.070 - Rules and regulations, hearings subject to Administrative Procedure Act.
The adoption of any rules and regulations under the provisions of this chapter, or the holding of a hearing in regard to a license issued or which may be issued under the provisions of this chapter shall be subject to the applicable provisions of chapter 34.05 RCW, the Administrative Procedure Act, as enacted or hereafter amended.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c121.pdf?cite=1967%20ex.s.%20c%20121%20§%207[1967 ex.s. c 121 § 7]; ]

== 69.07.080 - Inspections by department—Access—When.
For purpose of determining whether the rules adopted pursuant to RCW 69.07.020, as now or hereafter amended are complied with, the department shall have access for inspection purposes to any part, portion or area of a food processing plant, and any records required to be kept under the provisions of this chapter or rules and regulations adopted hereunder. Such inspection shall, when possible, be made during regular business hours or during any working shift of said food processing plant. The department may, however, inspect such food processing plant at any time when it has received information that an emergency affecting the public health has arisen and such food processing plant is or may be involved in the matters causing such emergency.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c68.pdf?cite=1969%20c%2068%20§%203[1969 c 68 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c121.pdf?cite=1967%20ex.s.%20c%20121%20§%208[1967 ex.s. c 121 § 8]; ]

== 69.07.085 - Sanitary certificates—Fee.
The department may issue sanitary certificates to food processors under this chapter subject to such requirements as it may establish by rule. The fee for issuance shall be seventy-five dollars per certificate. Fees collected under this section shall be deposited in the agricultural local fund.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2128-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2027%20§%208[2015 3rd sp.s. c 27 § 8]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5315-S.SL.pdf?cite=1995%20c%20374%20§%2023[1995 c 374 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c254.pdf?cite=1988%20c%20254%20§%209[1988 c 254 § 9]; ]

== 69.07.095 - Authority of director and personnel.
The director or the director's deputies, assistants, and inspectors are authorized to do all acts and things necessary to carry out the provisions of this chapter, including the taking of verified statements. The department personnel are empowered to administer oaths of verification on the statement.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1957-S.SL.pdf?cite=1991%20c%20137%20§%207[1991 c 137 § 7]; ]

== 69.07.100 - Establishments exempted from provisions of chapter.
. The provisions of this chapter shall not apply to establishments issued a permit or licensed under the provisions of:

.. Chapter 69.25 RCW, the Washington wholesome eggs and egg products act;

.. Chapter 69.28 RCW, the Washington state honey act;

.. Chapter 16.49 RCW, the meat inspection act;

.. Chapter 77.65 RCW, relating to the limited fish seller endorsement for wild-caught seafood;

.. Chapter 69.22 RCW, relating to cottage food operations;

.. Title 66 RCW, relating to alcoholic beverage control; and

.. Chapter 69.30 RCW, the sanitary control of shellfish act.

. If any such establishments process foods not specifically provided for in the above entitled acts, the establishments are subject to the provisions of this chapter.

. The provisions of this chapter do not apply to restaurants or food service establishments.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2055[2017 3rd sp.s. c 8 § 55]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5748-S.SL.pdf?cite=2011%20c%20281%20§%2013[2011 c 281 § 13]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2323-S.SL.pdf?cite=2002%20c%20301%20§%2010[2002 c 301 § 10]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5315-S.SL.pdf?cite=1995%20c%20374%20§%2022[1995 c 374 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c5.pdf?cite=1988%20c%205%20§%204[1988 c 5 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%20168[1983 c 3 § 168]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c121.pdf?cite=1967%20ex.s.%20c%20121%20§%2010[1967 ex.s. c 121 § 10]; ]

== 69.07.103 - Poultry—Slaughter, preparation, sale—One thousand or fewer—Special permit—Rules—Fee.
. A special permit issued by the department under this section is required for the slaughter, preparation, and sale of one thousand or fewer poultry in a calendar year by a poultry producer for the sale of whole raw poultry directly to the ultimate consumer at the producer's farm. Activities conducted under the permit are exempt from any other licensing requirements of this chapter.

. [Empty]
.. The department must adopt by rule requirements for the permit. The requirements must be generally patterned after those established by the state board of health for temporary food service establishments, but must be tailored specifically to poultry slaughter, preparation, and sale activities. The requirements must include, but are not limited to, those for: Cooling procedures, when applicable; sanitary facilities, equipment, and utensils; clean water; washing and other hygienic practices; and waste and wastewater disposal.

.. A permit expires December 31st and may be issued for either one or two years as requested by the permit applicant upon payment of the applicable fee in accordance with subsection (4) of this section.

. The department shall conduct such inspections as are reasonably necessary to ensure compliance with permit requirements.

. The fee for a special permit is seventy-five dollars for one year, or one hundred twenty-five dollars for two years.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5350-S.SL.pdf?cite=2009%20c%20114%20§%201[2009 c 114 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1754-S.SL.pdf?cite=2003%20c%20397%20§%202[2003 c 397 § 2]; ]

== 69.07.110 - Enforcement of chapter.
The department may use all the civil remedies provided for in the food safety and security act under chapter 15.130 RCW in carrying out and enforcing the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20713[2018 c 236 § 713]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c121.pdf?cite=1967%20ex.s.%20c%20121%20§%2011[1967 ex.s. c 121 § 11]; ]

== 69.07.120 - Disposition of money into food processing inspection account.
All moneys received by the department under the provisions of this chapter, RCW 15.130.410, and chapter 69.22 RCW shall be paid into the food processing inspection account hereby created within the agricultural local fund established in RCW 43.23.230 and shall be used solely to carry out the provisions of this chapter, RCW 15.130.410, and chapters 69.22 and 15.130 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20714[2018 c 236 § 714]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6388-S.SL.pdf?cite=2014%20c%2098%20§%203[2014 c 98 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5748-S.SL.pdf?cite=2011%20c%20281%20§%2012[2011 c 281 § 12]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6393-S.SL.pdf?cite=1992%20c%20160%20§%205[1992 c 160 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c121.pdf?cite=1967%20ex.s.%20c%20121%20§%2012[1967 ex.s. c 121 § 12]; ]

== 69.07.135 - Unlawful to sell or distribute food from unlicensed processor.
It shall be unlawful to resell, to offer for resale, or to distribute for resale in intrastate commerce any food processed in a food processing plant, which has not obtained a license, as provided for in this chapter, once notification by the director has been given to the person or persons reselling, offering, or distributing food for resale, that said food is from an unlicensed processing operation.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1957-S.SL.pdf?cite=1991%20c%20137%20§%208[1991 c 137 § 8]; ]

== 69.07.140 - Violations—Warning notice.
Nothing in this chapter shall be construed as requiring the department to report for prosecution violations of this chapter when it believes that the public interest will best be served by a suitable notice of warning in writing.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c121.pdf?cite=1967%20ex.s.%20c%20121%20§%2014[1967 ex.s. c 121 § 14]; ]

== 69.07.150 - Violations—Penalties.
. [Empty]
.. Except as provided in (b) of this subsection, any person violating any provision of this chapter or any rule or regulation adopted hereunder is guilty of a misdemeanor.

.. A second or subsequent violation is a gross misdemeanor. Any offense committed more than five years after a previous conviction shall be considered a first offense. 

. Whenever the director finds that a person has committed a violation of any of the provisions of this chapter, and that violation has not been punished pursuant to subsection (1) of this section, the director may impose upon and collect from the violator a civil penalty not exceeding one thousand dollars per violation per day. Each violation shall be a separate and distinct offense.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20316[2003 c 53 § 316]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1957-S.SL.pdf?cite=1991%20c%20137%20§%209[1991 c 137 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c121.pdf?cite=1967%20ex.s.%20c%20121%20§%2015[1967 ex.s. c 121 § 15]; ]

== 69.07.160 - Authority of director and department under the food safety and security act not impaired by this chapter.
The authority granted to the director and to the department under the provisions of the food safety and security act under chapter 15.130 RCW shall not be deemed to be reduced or otherwise impaired as a result of any provision or provisions of the Washington Food Processing Act (chapter 69.07 RCW).

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20715[2018 c 236 § 715]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c68.pdf?cite=1969%20c%2068%20§%204[1969 c 68 § 4]; ]

== 69.07.170 - Definitions.
As used in RCW 69.07.180 and 69.07.190:

. "Artesian water" means bottled water from a well tapping a confined aquifer in which the water level stands above the water table. "Artesian water" shall meet the requirements of "natural water."

. "Bottled water" means water that is placed in a sealed container or package and is offered for sale for human consumption or other consumer uses.

. "Carbonated water" or "sparkling water" means bottled water containing carbon dioxide.

. "Department" means the department of agriculture.

. "Distilled water" means bottled water that has been produced by a process of distillation and meets the definition of purified water in the most recent edition of the United States Pharmacopeia.

. "Drinking water" means bottled water obtained from an approved source that has at minimum undergone treatment consisting of filtration, activated carbon or particulate, and ozonization or an equivalent disinfection process, or that meets the requirements of the federal safe drinking water act of 1974 as amended and complies with all department of health rules regarding drinking water.

. "Mineral water" means bottled water that contains not less than five hundred parts per million total dissolved solids. "Natural mineral water" shall meet the requirements of "natural water."

. "Natural water" means bottled spring, mineral, artesian, or well water that is derived from an underground formation and may be derived from a public water system as defined in RCW 70A.125.010 only if that supply has a single source such as an actual spring, artesian well, or pumped well, and has not undergone any treatment that changes its original chemical makeup except ozonization or an equivalent disinfection process.

. "Plant operator" means a person who owns or operates a bottled water plant.

. "Purified water" means bottled water produced by distillation, deionization, reverse osmosis, or other suitable process and that meets the definition of purified water in the most recent edition of the United States Pharmacopeia. Water that meets this definition and is vaporized, then condensed, may be labeled "distilled water."

. "Spring water" means water derived from an underground formation from which water flows naturally to the surface of the earth. "Spring water" shall meet the requirements of "natural water."

. "Water dealer" means a person who imports bottled water or causes bulk water to be transported for bottling for human consumption or other consumer uses.

. "Well water" means water from a hole bored, drilled, or otherwise constructed in the ground that taps the water of an aquifer. "Well water" shall meet the requirements of "natural water."

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1192.SL.pdf?cite=2021%20c%2065%20§%2063[2021 c 65 § 63]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2747-S.SL.pdf?cite=1992%20c%2034%20§%201[1992 c 34 § 1]; ]

== 69.07.180 - Bottled water labeling standards.
All bottled water must conform to applicable federal and state labeling laws and be labeled in compliance with the following standards:

. Mineral water may be labeled "mineral water." Bottled water to which minerals are added shall be labeled so as to disclose that minerals are added, and may not be labeled "natural mineral water."

. Spring water may be labeled "spring water" or "natural spring water."

. Water containing carbon dioxide that emerges from the source and is bottled directly with its entrapped gas or from which the gas is mechanically separated and later reintroduced at a level not higher than naturally occurring in the water may bear on its label the words "naturally carbonated" or "naturally sparkling."

. Bottled water that contains carbon dioxide other than that naturally occurring in the source of the product shall be labeled with the words "carbonated," "carbonation added," or "sparkling" if the carbonation is obtained from a natural or manufactured source.

. Well water may be labeled "well water" or "natural well water."

. Artesian water may be labeled "artesian water" or "natural artesian water."

. Purified water may be labeled "purified water" and the method of preparation shall be stated on the label, except that purified water produced by distillation may be labeled as "distilled water."

. Drinking water may be labeled "drinking water."

. The use of the word "spring," or any derivative of "spring" other than in a trademark, trade name, or company name, to describe water that is not spring water is prohibited.

. A product meeting more than one of the definitions in RCW 69.07.170 may be identified by any of the applicable product types defined in RCW 69.07.170, except where otherwise specifically prohibited.

. Supplemental printed information and graphics may appear on the label but shall not imply properties of the product or preparation methods that are not factual.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2747-S.SL.pdf?cite=1992%20c%2034%20§%206[1992 c 34 § 6]; ]

== 69.07.190 - Bottled soft drinks, soda, or seltzer exempt from bottled water labeling requirements.
Bottled soft drinks, soda, or seltzer products commonly recognized as soft drinks and identified on the product identity panel with a common or usual name other than one of those specified in RCW 69.07.170 are exempt from the requirements of RCW 69.07.180. Water that is not in compliance with the requirements of RCW 69.07.180 may not be identified, labeled, or advertised as "artesian water," "bottled water," "distilled water," "natural water," "purified water," "spring water," or "well water."

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2747-S.SL.pdf?cite=1992%20c%2034%20§%207[1992 c 34 § 7]; ]

== 69.07.200 - Marijuana-infused edible processing.
. In addition to the requirements administered by the board under chapter 69.50 RCW, the department shall regulate marijuana-infused edible processing the same as other food processing under this chapter, except:

.. The department shall not consider foods containing marijuana to be adulterated when produced in compliance with chapter 69.50 RCW and the rules adopted by the board;

.. Initial issuance and renewal for an annual marijuana-infused edible endorsement in lieu of a food processing license under RCW 69.07.040 must be made through the business licensing system under chapter 19.02 RCW;

.. Renewal of the endorsement must coincide with renewal of the endorsement holder's marijuana processor license;

.. The department shall adopt a penalty schedule specific to marijuana processors, which may have values equivalent to the penalty schedule adopted by the board. Such penalties are in addition to any penalties imposed under the penalty schedule adopted by the board; and

.. The department shall notify the board of violations by marijuana processors under this chapter.

. A marijuana processor that processes, packages, or makes marijuana-infused edibles must obtain an annual marijuana-infused edible endorsement, as provided in this subsection (2).

.. The marijuana processor must apply for issuance and renewal for the endorsement from the department through the business licensing system under chapter 19.02 RCW.

.. The marijuana processor must have a valid marijuana processor license before submitting an application for initial endorsement. The application and initial endorsement fees total eight hundred ninety-five dollars. Applicants for endorsement otherwise must meet the same requirements as applicants for a food processing license under this chapter including, but not limited to, successful completion of inspection by the department.

.. Annual renewal of the endorsement must coincide with renewal of the endorsement holder's marijuana processor license. The endorsement renewal fee is eight hundred ninety-five dollars.

.. A marijuana processor must obtain a separate endorsement for each location at which the marijuana processor intends to process marijuana-infused edibles. Premises used for marijuana-infused edible processing may not be used for processing food that does not use marijuana as an ingredient, with the exception of edibles produced solely for tasting samples or internal product testing.

. The department may deny, suspend, or revoke a marijuana-infused edible endorsement on the same grounds as the department may deny, suspend, or revoke a food processor's license under this chapter.

. Information about processors otherwise exempt from public inspection and copying under chapter 42.56 RCW is also exempt from public inspection and copying if submitted to or used by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1462-S.SL.pdf?cite=2017%20c%20138%20§%204[2017 c 138 § 4]; ]

== 69.07.210 - Marijuana-infused edible processing—Implementation.
The department of agriculture, state liquor and cannabis board, and department of revenue shall take the necessary steps to ensure that RCW 69.07.200 is implemented on its effective date.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1462-S.SL.pdf?cite=2017%20c%20138%20§%205[2017 c 138 § 5]; ]

== 69.07.220 - Hemp extract certification.
. Until such time as hemp extract is federally authorized for use as a food ingredient, hemp extract is not an approved food ingredient in Washington state. A hemp processor who wishes to engage in the production of hemp extract for use as a food ingredient in another state that allows its use as a food ingredient may apply for a hemp extract certification to certify the hemp processor's compliance with Washington's inspection and good manufacturing practices requirements. The department shall regulate hemp extract processing the same as other food processing under chapters 15.130, 69.07, and 69.22 RCW with the exceptions contained in subsections (2) through (6) of this section.

. The department's oversight is limited to certifying a hemp processor's compliance with applicable inspection and good manufacturing practices requirements as adopted by the department under chapter 15.130 RCW.

. The department must issue a hemp extract certification in lieu of a food processing license under RCW 69.07.040 to a hemp processor who meets the application requirements described in subsection (4) of this section. A hemp processor holding a hemp extract certification must apply for renewal of the certification annually.

. The application, initial certification, and renewal fees must be in an amount established by the department. Applicants for certification otherwise must meet the same requirements as applicants for a food processing license under chapter 69.07 RCW including, but not limited to, successful completion of an inspection by the department.

. The department may deny, suspend, or revoke a hemp extract certification on the same grounds as the department may deny, suspend, or revoke a food processor's license under this chapter.

. At such time as federal authorization of hemp extracts as a food ingredient occurs, the department must cease issuance of certifications under this chapter. At renewal, hemp processors certified under this section must apply for a food processor license in accordance with RCW 69.07.040.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5372.SL.pdf?cite=2021%20c%20104%20§%206[2021 c 104 § 6]; ]

== 69.07.900 - Chapter is cumulative and nonexclusive.
The provisions of this chapter shall be cumulative and nonexclusive and shall not affect any other remedy.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c121.pdf?cite=1967%20ex.s.%20c%20121%20§%2016[1967 ex.s. c 121 § 16]; ]

== 69.07.920 - Short title.
This chapter shall be known and designated as the Washington food processing act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c121.pdf?cite=1967%20ex.s.%20c%20121%20§%2018[1967 ex.s. c 121 § 18]; ]

