= 69.04 - Intrastate commerce in drugs and cosmetics.
:toc:

== 69.04.001 - Statement of purpose.
This chapter is intended to enact state legislation (1) which safeguards the public health and promotes the public welfare by protecting the consuming public from (a) potential injury by product use; (b) products that are adulterated; or (c) products that have been produced under unsanitary conditions, and the purchasing public from injury by merchandising deceit flowing from intrastate commerce in food, drugs, devices, and cosmetics; and (2) which is uniform, as provided in this chapter, with the federal food, drug, and cosmetic act; and with the federal trade commission act, to the extent it expressly outlaws the false advertisement of food, drugs, devices, and cosmetics; and (3) which thus promotes uniformity of such law and its administration and enforcement, in and throughout the United States.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1955.SL.pdf?cite=1991%20c%20162%20§%201[1991 c 162 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%202[1945 c 257 § 2]; Rem. Supp. 1945 § 6163-51; ]

== 69.04.002 - Introductory.
For the purposes of this chapter, terms shall apply as herein defined unless the context clearly indicates otherwise.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%203[1945 c 257 § 3]; Rem. Supp. 1945 § 6163-52; ]

== 69.04.003 - "Federal act" defined.
The term "federal act" means the federal food, drug, and cosmetic act, approved on June 25, 1938. (Title 21 U.S.C. 301 et seq.; 52 Stat. 1040 et seq.)

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%204[1945 c 257 § 4]; Rem. Supp. 1945 § 6163-53; ]

== 69.04.004 - "Intrastate commerce."
The term "intrastate commerce" means any and all commerce within the state of Washington and subject to the jurisdiction thereof; and includes the operation of any business or service establishment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%205[1945 c 257 § 5]; Rem. Supp. 1945 § 6163-54; ]

== 69.04.005 - "Sale."
The term "sale" means any and every sale and includes (1) manufacture, processing, packing, canning, bottling, or any other production, preparation, or putting up; (2) exposure, offer, or any other proffer; (3) holding, storing, or any other possessing; (4) dispensing, giving, delivering, serving, or any other supplying; and (5) applying, administering, or any other using.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%206[1945 c 257 § 6]; Rem. Supp. 1945 § 6163-55; ]

== 69.04.006 - "Director."
The term "director" means the director of the department of agriculture of the state of Washington and his or her duly authorized representatives.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20328[2012 c 117 § 328]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%207[1945 c 257 § 7]; Rem. Supp. 1945 § 6163-56; ]

== 69.04.007 - "Person."
The term "person" includes individual, partnership, corporation, and association.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%208[1945 c 257 § 8]; Rem. Supp. 1945 § 6163-57; ]

== 69.04.008 - "Food."
The term "food" means (1) articles used for food or drink for people or other animals, (2) bottled water, (3) chewing gum, and (4) articles used for components of any such article.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2747-S.SL.pdf?cite=1992%20c%2034%20§%202[1992 c 34 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%209[1945 c 257 § 9]; Rem. Supp. 1945 § 6163-58; ]

== 69.04.009 - "Drugs."
The term "drug" means (1) articles recognized in the official United States pharmacopoeia, official homeopathic pharmacopoeia of the United States, or official national formulary, or any supplement to any of them; and (2) articles intended for use in the diagnosis, cure, mitigation, treatment, or prevention of disease in human beings or other animals; and (3) articles (other than food) intended to affect the structure or any function of the body of human beings or other animals; and (4) articles intended for use as a component of any article specified in clause (1), (2), or (3); but does not include devices or their components, parts, or accessories.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%201018[2009 c 549 § 1018]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2010[1945 c 257 § 10]; Rem. Supp. 1945 § 6163-59; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c211.pdf?cite=1907%20c%20211%20§%202[1907 c 211 § 2]; ]

== 69.04.010 - "Device."
The term "device" (except when used in RCW 69.04.016 and in RCW * 69.04.040(10), ** 69.04.270, 69.04.690, and in RCW 69.04.470 as used in the sentence "(as compared with other words, statements, designs, or devices, in the labeling)") means instruments, apparatus, and contrivances, including their components, parts and accessories, intended (1) for use in the diagnosis, cure, mitigation, treatment, or prevention of disease in human beings or other animals; or (2) to affect the structure or any function of the body of human beings or other animals.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%201019[2009 c 549 § 1019]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2011[1945 c 257 § 11]; Rem. Supp. 1945 § 6163-60; ]

== 69.04.011 - "Cosmetic."
The term "cosmetic" means (1) articles intended to be rubbed, poured, sprinkled, or sprayed on, introduced into, or otherwise applied to the human body or any part thereof for cleansing, beautifying, promoting attractiveness, or altering the appearance, and (2) articles intended for use as a component of any such article; except that such term shall not include soap.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2012[1945 c 257 § 12]; Rem. Supp. 1945 § 6163-61; ]

== 69.04.012 - "Official compendium."
The term "official compendium" mean the official United States pharmacopoeia, official homeopathic pharmacopoeia of the United States, official national formulary, or any supplement to any of them.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2013[1945 c 257 § 13]; Rem. Supp. 1945 § 6163-62; ]

== 69.04.013 - "Label."
The term "label" means a display of written, printed, or graphic matter upon the immediate container of any article; and a requirement made by or under authority of this chapter that any word, statement, or other information appear on the label shall not be considered to be complied with unless such word, statement, or other information also appears on the outside container or wrapper, if any there be, of the retail package of such article, or is easily legible through the outside container or wrapper.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2014[1945 c 257 § 14]; Rem. Supp. 1945 § 6163-63; ]

== 69.04.014 - "Immediate container."
The term "immediate container" does not include package liners.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2015[1945 c 257 § 15]; Rem. Supp. 1945 § 6163-64; ]

== 69.04.015 - "Labeling."
The term "labeling" means all labels and other written, printed, or graphic matter (1) upon any article or any of its containers or wrappers, or (2) accompanying such article.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2016[1945 c 257 § 16]; Rem. Supp. 1945 § 6163-65; ]

== 69.04.016 - "Misleading labeling or advertisement," how determined.
If any article is alleged to be misbranded because the labeling is misleading, or if an advertisement is alleged to be false because it is misleading, then in determining whether the labeling or advertisement is misleading there shall be taken into account (among other things) not only representations made or suggested by statement, word, design, device, sound, or any combination thereof, but also the extent to which the labeling or advertisement fails to reveal facts material in the light of such representations or material with respect to consequences which may result from the use of the article to which the labeling or advertisement relates under the conditions of use prescribed in the labeling or advertisement thereof or under such conditions of use as are customary or usual.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2017[1945 c 257 § 17]; Rem. Supp. 1945 § 6163-66; ]

== 69.04.017 - "Antiseptic" as germicide.
The representation of a drug, in its labeling or advertisement, as an antiseptic shall be considered to be a representation that it is a germicide, except in the case of a drug purporting to be, or represented as, an antiseptic for inhibitory use as a wet dressing, ointment, dusting powder, or such other use as involves prolonged contact with the body.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2018[1945 c 257 § 18]; Rem. Supp. 1945 § 6163-67; ]

== 69.04.018 - "New drug" defined.
The term "new drug" means (1) any drug the composition of which is such that such drug is not generally recognized, among experts qualified by scientific training and experience to evaluate the safety of drugs, as safe for use under the conditions prescribed, recommended, or suggested in the labeling thereof; or (2) any drug the composition of which is such that such drug, as a result of investigations to determine its safety for use under such conditions, has become so recognized, but which has not, otherwise than in such investigations, been used to a material extent or for a material time under such conditions: PROVIDED, That no drug in use on the *effective date of this chapter shall be regarded as a new drug.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2019[1945 c 257 § 19]; Rem. Supp. 1945 § 6163-68; ]

== 69.04.019 - "Advertisement."
The term "advertisement" means all representations, other than by labeling, for the purpose of inducing, or which are likely to induce, directly or indirectly, the purchase of food, drugs, devices, or cosmetics.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2020[1945 c 257 § 20]; Rem. Supp. 1945 § 6163-69; ]

== 69.04.020 - "Contaminated with filth."
The term "contaminated with filth" applies to any food, drug, device, or cosmetic not securely protected from dust, dirt, and as far as may be necessary by all reasonable means, from all foreign or injurious contaminations.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2021[1945 c 257 § 21]; Rem. Supp. 1945 § 6163-70; ]

== 69.04.040 - Prohibited acts.
The following acts and the causing thereof are hereby prohibited:

. The sale in intrastate commerce of any drug, device, or cosmetic that is adulterated or misbranded.

. The adulteration or misbranding of any drug, device, or cosmetic in intrastate commerce.

. The receipt in intrastate commerce of any drug, device, or cosmetic that is adulterated or misbranded, and the sale thereof in such commerce for pay or otherwise.

. The introduction or delivery for introduction into intrastate commerce of any new drug in violation of RCW 69.04.570.

. The dissemination within this state, in any manner or by any means or through any medium, of any false advertisement.

. The refusal to permit (a) entry and the taking of a sample or specimen or the making of any investigation or examination as authorized by RCW 69.04.780; or (b) access to or copying of any record as authorized by RCW 69.04.810.

. The refusal to permit entry or inspection as authorized by RCW 69.04.820.

. The removal, mutilation, or violation of an embargo notice as authorized by RCW 69.04.110.

. The giving of a guaranty or undertaking in intrastate commerce, referred to in RCW 69.04.080, that is false.

. The alteration, mutilation, destruction, obliteration, or removal of the whole or any part of the labeling of a drug, device, or cosmetic, or the doing of any other act with respect to a drug, device, or cosmetic, or the labeling or advertisement thereof, which results in a violation of this chapter.

. The using in intrastate commerce, in the labeling or advertisement of any drug, of any representation or suggestion that an application with respect to such drug is effective under section 505 of the federal act or under RCW 69.04.570, or that such drug complies with the provisions of either such section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20601[2018 c 236 § 601]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2022[1945 c 257 § 22]; Rem. Supp. 1945 § 6163-71; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c168.pdf?cite=1917%20c%20168%20§%201[1917 c 168 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c211.pdf?cite=1907%20c%20211%20§%201[1907 c 211 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1901c94.pdf?cite=1901%20c%2094%20§%201[1901 c 94 § 1]; ]

== 69.04.050 - Remedy by injunction.
. In addition to the remedies hereinafter provided the director is hereby authorized to apply to the superior court of Thurston county for, and such court shall have jurisdiction upon prompt hearing and for cause shown to grant, a temporary or permanent injunction restraining any person from violating any provision of RCW 69.04.040; without proof that an adequate remedy at law does not exist.

. Whenever it appears to the satisfaction of the court in the case of a newspaper, magazine, periodical, or other publication, published at regular intervals (a) that restraining the dissemination of a false advertisement in any particular issue of such publication would delay the delivery of such issue after the regular time therefor, and (b) that such delay would be due to the method by which the manufacture and distribution of such publication is customarily conducted by the publisher in accordance with sound business practice, and not to any method or device adopted for the evasion of this section or to prevent or delay the issuance of an injunction or restraining order with respect to such false advertisement or any other advertisement, the court shall exclude such issue from the operation of the restraining order or injunction.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2023[1945 c 257 § 23]; Rem. Supp. 1945 § 6163-72; ]

== 69.04.060 - Criminal penalty for violations.
Except as otherwise provided in this chapter, any person who violates any provision of RCW 69.04.040 is guilty of a misdemeanor and shall on conviction thereof be subject to the following penalties:

. A fine of not more than two hundred dollars; or

. If the violation is committed after a conviction of such person under this section has become final, imprisonment for not more than thirty days, or a fine of not more than five hundred dollars, or both such imprisonment and fine.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1200-S.SL.pdf?cite=2013%20c%20290%20§%201[2013 c 290 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20314[2003 c 53 § 314]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2024[1945 c 257 § 24]; Rem. Supp. 1945 § 6163-73; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c211.pdf?cite=1907%20c%20211%20§%2012[1907 c 211 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1901c94.pdf?cite=1901%20c%2094%20§%2011[1901 c 94 § 11]; ]

== 69.04.070 - Additional penalty.
Notwithstanding the provisions of RCW 69.04.060, a person who violates RCW 69.04.040 with intent to defraud or mislead is guilty of a misdemeanor and the penalty shall be imprisonment for not more than ninety days, or a fine of not more than one thousand dollars, or both such imprisonment and fine.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20315[2003 c 53 § 315]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2025[1945 c 257 § 25]; Rem. Supp. 1945 § 6163-74; ]

== 69.04.080 - Avoidance of penalty.
No person shall be subject to the penalties of RCW 69.04.060:

. For having violated RCW 69.04.040(3), if he or she establishes that he or she received and sold such article in good faith, unless he or she refuses on request of the director to furnish the name and address of the person in the state of Washington from whom he or she received such article and copies of all available documents pertaining to his or her receipt thereof; or

. For having violated RCW 69.04.040 (1), (3), or (4), if he or she establishes a guaranty or undertaking signed by, and containing the name and address of, the person in the state of Washington from whom he or she received such article in good faith, to the effect that such article complies with this chapter; or

. For having violated RCW 69.04.040(5), if he or she establishes a guaranty or undertaking signed by, and containing the name and address of, the person in the state of Washington from whom he or she received such advertisement in good faith, to the effect that such advertisement complies with this chapter; or

. For having violated RCW 69.04.040(9), if he or she establishes that he or she gave such guaranty or undertaking in good faith and in reliance on a guaranty or undertaking to him or her, which guaranty or undertaking was to the same effect and was signed by, and contained the name and address of, a person in the state of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20329[2012 c 117 § 329]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2026[1945 c 257 § 26]; Rem. Supp. 1945 § 6163-75; ]

== 69.04.090 - Liability of disseminator of advertisement.
No publisher, radio broadcast licensee, advertising agency, or agency or medium for the dissemination of an advertisement, except the manufacturer, packer, distributor, or seller of the article to which the advertisement relates, shall be subject to the penalties of RCW 69.04.060 by reason of his or her dissemination of any false advertisement, unless he or she has refused on the request of the director to furnish the name and address of the manufacturer, packer, distributor, seller, or advertising agency in the state of Washington, who caused him or her to disseminate such false advertisement.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20330[2012 c 117 § 330]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2027[1945 c 257 § 27]; Rem. Supp. 1945 § 6163-76; ]

== 69.04.100 - Condemnation of adulterated or misbranded article.
Whenever the director shall find in intrastate commerce an article subject to this chapter which is so adulterated or misbranded that it is unfit or unsafe for human use and its immediate condemnation is required to protect the public health, such article is hereby declared to be a nuisance and the director is hereby authorized forthwith to destroy such article or to render it unsalable for human use.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2028[1945 c 257 § 28]; Rem. Supp. 1945 § 6163-77; ]

== 69.04.110 - Embargo of articles.
Whenever the director shall find, or shall have probable cause to believe, that an article subject to this chapter is in intrastate commerce in violation of this chapter, and that its embargo under this section is required to protect the consuming or purchasing public, due to its being adulterated or misbranded, or to otherwise protect the public from injury, or possible injury, he or she is hereby authorized to affix to such article a notice of its embargo and against its sale in intrastate commerce, without permission given under this chapter. But if, after such article has been so embargoed, the director shall find that such article does not involve a violation of this chapter, such embargo shall be forthwith removed.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1955.SL.pdf?cite=1991%20c%20162%20§%203[1991 c 162 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c7.pdf?cite=1975%201st%20ex.s.%20c%207%20§%2025[1975 1st ex.s. c 7 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2029[1945 c 257 § 29]; Rem. Supp. 1945 § 6163-78; ]

== 69.04.120 - Procedure on embargo.
When the director has embargoed an article, he or she shall, forthwith and without delay and in no event later than thirty days after the affixing of notice of its embargo, petition the superior court for an order affirming the embargo. The court then has jurisdiction, for cause shown and after prompt hearing to any claimant of the embargoed article, to issue an order which directs the removal of the embargo or the destruction or the correction and release of the article. An order for destruction or correction and release shall contain such provision for the payment of pertinent court costs and fees and administrative expenses as is equitable and which the court deems appropriate in the circumstances. An order for correction and release may contain such provision for a bond as the court finds indicated in the circumstances.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1955.SL.pdf?cite=1991%20c%20162%20§%204[1991 c 162 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c95.pdf?cite=1983%20c%2095%20§%208[1983 c 95 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2030[1945 c 257 § 30]; Rem. Supp. 1945 § 6163-79; ]

== 69.04.130 - Petitions may be consolidated.
Two or more petitions under RCW 69.04.120, which pend at the same time and which present the same issue and claimant hereunder, shall be consolidated for simultaneous determination by one court of jurisdiction, upon application to any court of jurisdiction by the director or by such claimant.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2031[1945 c 257 § 31]; Rem. Supp. 1945 § 6163-80; ]

== 69.04.140 - Claimant entitled to sample.
The claimant in any proceeding by petition under RCW 69.04.120 shall be entitled to receive a representative sample of the article subject to such proceeding, upon application to the court of jurisdiction made at any time after such petition and prior to the hearing thereon.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2032[1945 c 257 § 32]; Rem. Supp. 1945 § 6163-81; ]

== 69.04.150 - Damages not recoverable if probable cause existed.
No state court shall allow the recovery of damages from administrative action for condemnation under RCW 69.04.100 or for embargo under RCW 69.04.110, if the court finds that there was probable cause for such action.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2033[1945 c 257 § 33]; Rem. Supp. 1945 § 6163-82; ]

== 69.04.160 - Prosecutions.
. It shall be the duty of each state attorney, county attorney, or city attorney to whom the director reports any violation of this chapter, or regulations promulgated under it, to cause appropriate proceedings to be instituted in the proper courts, without delay, and to be duly prosecuted as prescribed by law.

. Before any violation of this chapter is reported by the director to any such attorney for the institution of a criminal proceeding, the person against whom such proceeding is contemplated shall be given appropriate notice and an opportunity to present his or her views to the director, either orally or in writing, with regard to such contemplated proceeding.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20331[2012 c 117 § 331]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2034[1945 c 257 § 34]; Rem. Supp. 1945 § 6163-83; ]

== 69.04.170 - Minor infractions.
Nothing in this chapter shall be construed as requiring the director to report for the institution of proceedings under this chapter, minor violations of this chapter, whenever he or she believes that the public interest will be adequately served in the circumstances by a suitable written notice or warning.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20332[2012 c 117 § 332]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2035[1945 c 257 § 35]; Rem. Supp. 1945 § 6163-84; ]

== 69.04.180 - Proceedings to be in name of state.
All such proceedings for the enforcement, or to restrain violations, of this chapter shall be by and in the name of the state of Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2036[1945 c 257 § 36]; Rem. Supp. 1945 § 6163-85; ]

== 69.04.370 - Right of access for inspection.
Any officer or employee duly designated by the director shall have access to any factory or establishment, the operator of which holds a permit from the director, for the purpose of ascertaining whether or not the conditions of the permit are being complied with, and denial of access for such inspection shall be ground for suspension of the permit until such access is freely given by the operator.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2055[1945 c 257 § 55]; Rem. Supp. 1945 § 6163-104; ]

== 69.04.410 - Drugs—Adulteration by harmful substances.
A drug or device shall be deemed to be adulterated (1) if it consists in whole or in part of any filthy, putrid, or decomposed substance; or (2) if it has been produced, prepared, packed, or held under insanitary conditions whereby it may have been contaminated with filth, or whereby it may have been rendered injurious to health; or (3) if it is a drug and its container is composed in whole or in part of any poisonous or deleterious substance which may render the contents injurious to health; or (4) if it is a drug and it bears or contains, for purposes of coloring only, a coal tar color other than one that is harmless and suitable for use in drugs for such purposes, as provided by regulations promulgated under section 504 of the federal act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2059[1945 c 257 § 59]; Rem. Supp. 1945 § 6163-108; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c36.pdf?cite=1923%20c%2036%20§%201[1923 c 36 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c211.pdf?cite=1907%20c%20211%20§%203[1907 c 211 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1901c94.pdf?cite=1901%20c%2094%20§%203[1901 c 94 § 3]; ]

== 69.04.420 - Drugs—Adulteration for failure to comply with compendium standard.
If a drug or device purports to be or is represented as a drug the name of which is recognized in an official compendium, and its strength differs from, or its quality or purity falls below, the standard set forth in such compendium, it shall be deemed to be adulterated. Such determination as to strength, quality or purity shall be made in accordance with the tests or methods of assay set forth in such compendium or prescribed by regulations promulgated under section 501(b) of the federal act. No drug defined in an official compendium shall be deemed to be adulterated under this section because it differs from the standard of strength, quality, or purity therefor set forth in such compendium, if its difference in strength, quality, or purity from such standard is plainly stated on its label. Whenever a drug is recognized in both the United States pharmacopoeia and the homeopathic pharmacopoeia of the United States, it shall be subject to the requirements of the United States pharmacopoeia unless it is labeled and offered for sale as a homeopathic drug, in which case it shall be subject to the provisions of the homeopathic pharmacopoeia of the United States and not to those of the United States pharmacopoeia.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2060[1945 c 257 § 60]; Rem. Supp. 1945 § 6163-109; ]

== 69.04.430 - Drugs—Adulteration for lack of represented purity or quality.
If a drug or device is not subject to the provisions of RCW 69.04.420 and its strength differs from, or its purity or quality falls below, that which it purports or is represented to possess, it shall be deemed to be adulterated.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2061[1945 c 257 § 61]; Rem. Supp. 1945 § 6163-110; ]

== 69.04.440 - Drugs—Adulteration by admixture or substitution of ingredients.
A drug shall be deemed to be adulterated if any substance has been (1) mixed or packed therewith so as to reduce its quality or strength or (2) substituted wholly or in part therefor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2062[1945 c 257 § 62]; Rem. Supp. 1945 § 6163-111; ]

== 69.04.450 - Drugs—Misbranding by false labeling.
A drug or device shall be deemed to be misbranded if its labeling is false or misleading in any particular.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2063[1945 c 257 § 63]; Rem. Supp. 1945 § 6163-112; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c36.pdf?cite=1923%20c%2036%20§%202[1923 c 36 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c211.pdf?cite=1907%20c%20211%20§%204[1907 c 211 § 4]; ]

== 69.04.460 - Packaged drugs—Misbranding.
If a drug or device is in package form, it shall be deemed to be misbranded unless it bears a label containing (1) the name and place of business of the manufacturer, packer, or distributor; and (2) an accurate statement of the quantity of the contents in terms of weight, measure, or numerical count: PROVIDED, That under clause (2) of this section reasonable variations shall be permitted, and exemptions as to small packages shall be established, by regulations promulgated by the director.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2064[1945 c 257 § 64]; Rem. Supp. 1945 § 6163-113; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c36.pdf?cite=1923%20c%2036%20§%202[1923 c 36 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c211.pdf?cite=1907%20c%20211%20§%204[1907 c 211 § 4]; ]

== 69.04.470 - Drugs—Misbranding by lack of prominent label.
A drug or device shall be deemed to be misbranded if any word, statement, or other information required by or under authority of this chapter to appear on the label or labeling is not prominently placed thereon with such conspicuousness (as compared with other words, statements, designs, or devices, in the labeling) and in such terms as to render it likely to be read and understood by the ordinary individual under customary conditions of purchase and use.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2065[1945 c 257 § 65]; Rem. Supp. 1945 § 6163-114; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c36.pdf?cite=1923%20c%2036%20§%202[1923 c 36 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c211.pdf?cite=1907%20c%20211%20§%204[1907 c 211 § 4]; ]

== 69.04.480 - Drugs—Misbranding for failure to state content of habit forming drug.
A drug or device shall be deemed to be misbranded if it is for use by human beings and contains any quantity of the narcotic or hypnotic substance alpha eucaine, barbituric acid, beta eucaine, bromal, cannabis, carbromal, chloral, coca, cocaine, codeine, heroin, marijuana, morphine, opium, paraldehyde, peyote, or sulphomethane; or any chemical derivative of such substance, which derivative has been designated as habit forming by regulations promulgated under section 502(d) of the federal act; unless its label bears the name and quantity or proportion of such substance or derivative and in juxtaposition therewith the statement "Warning—May be habit forming."

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%201023[2009 c 549 § 1023]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2066[1945 c 257 § 66]; Rem. Supp. 1945 § 6163-115; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c36.pdf?cite=1923%20c%2036%20§%202[1923 c 36 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c211.pdf?cite=1907%20c%20211%20§%204[1907 c 211 § 4]; ]

== 69.04.490 - Drugs—Misbranding by failure to show usual name and ingredients.
If a drug is not designated solely by a name recognized in an official compendium it shall be deemed to be misbranded unless its label bears (1) the common or usual name of the drug, if such there be; and (2), in case it is fabricated from two or more ingredients, the common or usual name of each active ingredient, including the quantity, kind, and proportion of any alcohol, and also including, whether active or not, the name and quantity or proportion of any bromides, ether, chloroform, acetanilid, acetphenetidin, amidopyrine, antipyrine, atropine, hyoscine, hyoscyamime, arsenic, digitalis, glucosides, mercury, ouabain, strophanthin, strychnine, thyroid, or any derivative or preparation of any such substances, contained therein: PROVIDED, That to the extent that compliance with the requirements of clause (2) of this section is impracticable, exemptions shall be established by regulations promulgated by the director.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2067[1945 c 257 § 67]; Rem. Supp. 1945 § 6163-116; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c36.pdf?cite=1923%20c%2036%20§%202[1923 c 36 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c211.pdf?cite=1907%20c%20211%20§%204[1907 c 211 § 4]; ]

== 69.04.500 - Drugs—Misbranding by failure to give directions for use and warnings.
A drug or device shall be deemed to be misbranded unless its labeling bears (1) adequate directions for use; and (2) such adequate warnings against use in those pathological conditions or by children where its use may be dangerous to health, or against unsafe dosage or methods or duration of administration or application, in such manner and form, as are necessary for the protection of users: PROVIDED, That where any requirement of clause (1) of this section as applied to any drug or device, is not necessary for the protection of the public health, the director shall promulgate regulations exempting such drug or device from such requirements. Such regulations shall include the exemptions prescribed under section 502(f)(1) of the federal act, insofar as such exemptions are applicable hereunder.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2068[1945 c 257 § 68]; Rem. Supp. 1945 § 6163-117; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c36.pdf?cite=1923%20c%2036%20§%202[1923 c 36 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c211.pdf?cite=1907%20c%20211%20§%204[1907 c 211 § 4]; ]

== 69.04.510 - Drugs—Misbranding for improper packaging and labeling.
A drug or device shall be deemed to be misbranded if it purports to be a drug the name of which is recognized in an official compendium, unless it is packaged and labeled as prescribed therein: PROVIDED, That the method of packing may be modified with the consent of the director, as permitted under section 502(g) of the federal act. Whenever a drug is recognized in both the United States pharmacopoeia and the homeopathic pharmacopoeia of the United States, it shall be subject to the requirements of the United States pharmacopoeia with respect to packaging and labeling unless it is labeled and offered for sale as a homeopathic drug, in which case it shall be subject to the provisions of the homeopathic pharmacopoeia of the United States, and not to those of the United States pharmacopoeia.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2069[1945 c 257 § 69]; Rem. Supp. 1945 § 6163-118; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c36.pdf?cite=1923%20c%2036%20§%202[1923 c 36 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c211.pdf?cite=1907%20c%20211%20§%204[1907 c 211 § 4]; ]

== 69.04.520 - Drugs—Misbranding for failure to show possibility of deterioration.
If a drug or device has been found by the secretary of agriculture of the United States to be a drug liable to deterioration, it shall be deemed to be misbranded unless it is packaged in such form and manner, and its label bears a statement of such precautions, as required in an official compendium or by regulations promulgated under section 502(h) of the federal act for the protection of the public health.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2070[1945 c 257 § 70]; Rem. Supp. 1945 § 6163-119; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c36.pdf?cite=1923%20c%2036%20§%202[1923 c 36 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c211.pdf?cite=1907%20c%20211%20§%204[1907 c 211 § 4]; ]

== 69.04.530 - Drugs—Misbranding by misleading representation.
A drug shall be deemed to be misbranded if (1) its container is so made, formed, or filled as to be misleading; or (2) if it is an imitation of another drug; or (3) if it is offered for sale under the name of another drug; or (4) if it is dangerous to health when used in the dosage, or with the frequency or duration prescribed, recommended, or suggested in the labeling thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2071[1945 c 257 § 71]; Rem. Supp. 1945 § 6163-120; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c36.pdf?cite=1923%20c%2036%20§%202[1923 c 36 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c211.pdf?cite=1907%20c%20211%20§%204[1907 c 211 § 4]; ]

== 69.04.540 - Drugs—Misbranding by sale without prescription of drug requiring it.
A drug or device shall be deemed to be misbranded if it is a drug which by label provides, or which the federal act or any applicable law requires by label to provide, in effect, that it shall be used only upon the prescription of a physician, dentist, or veterinarian, unless it is dispensed at retail on a written prescription signed by a physician, dentist, or veterinarian, who is licensed by law to administer such a drug.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2072[1945 c 257 § 72]; Rem. Supp. 1945 § 6163-121; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c36.pdf?cite=1923%20c%2036%20§%202[1923 c 36 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c211.pdf?cite=1907%20c%20211%20§%204[1907 c 211 § 4]; ]

== 69.04.550 - Drugs exempt if in transit for completion purposes.
A drug or device which is, in accordance with the practice of the trade, to be processed, labeled, or repacked in substantial quantities at an establishment other than the establishment where it was originally processed or packed, is exempted from the affirmative labeling and packaging requirements of this chapter, while it is in transit in intrastate commerce from the one establishment to the other, if such transit is made in good faith for such completion purposes only; but it is otherwise subject to all the applicable provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2073[1945 c 257 § 73]; Rem. Supp. 1945 § 6163-122; ]

== 69.04.560 - Dispensing of certain drugs exempt.
A drug dispensed on a written prescription signed by a physician, dentist, or veterinarian (except a drug dispensed in the course of the conduct of a business of dispensing drugs pursuant to diagnosis by mail) shall, if (1) such physician, dentist, or veterinarian is licensed by law to administer such drug, and (2) such drug bears a label containing the name and place of business of the dispenser, the serial number and date of such prescription, and the name of such physician, dentist, or veterinarian, be exempt from the requirements of RCW 69.04.450 through 69.04.540.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2074[1945 c 257 § 74]; Rem. Supp. 1945 § 6163-123; ]

== 69.04.565 - DMSO (dimethyl sulfoxide) authorized.
Notwithstanding any other provision of state law, DMSO (dimethyl sulfoxide) may be introduced into intrastate commerce as long as (1) it is manufactured or distributed by persons licensed pursuant to chapter 18.64 RCW or chapter 18.92 RCW, and (2) it is used, or intended to be used, in the treatment of human beings or animals for any ailment or adverse condition: PROVIDED, That DMSO intended for topical application, consistent with rules governing purity and labeling promulgated by the pharmacy quality assurance commission, shall not be considered a legend drug and may be sold by any retailer.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1609.SL.pdf?cite=2013%20c%2019%20§%2050[2013 c 19 § 50]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c50.pdf?cite=1981%20c%2050%20§%201[1981 c 50 § 1]; ]

== 69.04.570 - Introduction of new drug.
Except as permitted by chapter 69.77 RCW, no person shall introduce or deliver for introduction into intrastate commerce any new drug which is subject to section 505 of the federal act unless an application with respect to such drug has become effective thereunder. No person shall introduce or deliver for introduction into intrastate commerce any new drug which is not subject to section 505 of the federal act, unless (1) it has been found, by appropriate tests, that such drug is not unsafe for use under the conditions prescribed, recommended, or suggested in the labeling thereof; and (2) an application has been filed under this section of this chapter with respect to such drug: PROVIDED, That the requirement of subsection (2) of this section shall not apply to any drug introduced into intrastate commerce at any time prior to the enactment of this chapter or introduced into interstate commerce at any time prior to the enactment of the federal act: PROVIDED FURTHER, That if the director finds that the requirement of subsection (2) of this section as applied to any drug or class of drugs, is not necessary for the protection of the public health, he or she shall promulgate regulations of exemption accordingly.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5035-S.SL.pdf?cite=2017%20c%20212%20§%2010[2017 c 212 § 10]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20338[2012 c 117 § 338]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2075[1945 c 257 § 75]; Rem. Supp. 1945 § 6163-124; ]

== 69.04.580 - Application for introduction.
An application under RCW 69.04.570 shall be filed with the director, and subject to any waiver by the director, shall include (1) full reports of investigations which have been made to show whether or not the drug, subject to the application, is safe for use under the conditions prescribed, recommended, or suggested in the labeling thereof; (2) a full list of the articles used as components of such drug; (3) a full statement of the composition of such drug; (4) a full description of the methods used in, and the facilities and controls used for, the manufacture, processing, and packing of such drug; (5) such samples of such drug and of the articles used as components thereof as the director may require; and (6) specimens of the labeling proposed to be used for such drug.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2076[1945 c 257 § 76]; Rem. Supp. 1945 § 6163-125; ]

== 69.04.590 - Effective date of application.
An application filed under RCW 69.04.570 shall become effective on the sixtieth day after the filing thereof, unless the director (1) makes such application effective prior to such day; or (2) issues an order with respect to such application pursuant to RCW 69.04.600.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2077[1945 c 257 § 77]; Rem. Supp. 1945 § 6163-126; ]

== 69.04.600 - Denial of application.
If the director finds, upon the basis of the information before him or her and after due notice and opportunity for hearing to the applicant, that the drug, subject to the application, is not safe for use under the conditions prescribed, recommended, or suggested in the labeling thereof, he or she shall, prior to such effective date, issue an order refusing to permit such application to become effective and stating the findings upon which it is based.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20339[2012 c 117 § 339]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2078[1945 c 257 § 78]; Rem. Supp. 1945 § 6163-127; ]

== 69.04.610 - Revocation of denial.
An order refusing to permit an application under RCW 69.04.570 to become effective may be suspended or revoked by the director, for cause and by order stating the findings upon which it is based.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2079[1945 c 257 § 79]; Rem. Supp. 1945 § 6163-128; ]

== 69.04.620 - Service of order of denial.
Orders of the director issued under RCW 69.04.600 shall be served (1) in person by a duly authorized representative of the director or (2) by mailing the order by registered mail addressed to the applicant or respondent at his or her address last known to the director.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20340[2012 c 117 § 340]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2080[1945 c 257 § 80]; Rem. Supp. 1945 § 6163-129; ]

== 69.04.630 - Drug for investigational use exempt.
A drug shall be exempt from the operation of RCW 69.04.570 which is intended, and introduced or delivered for introduction into intrastate commerce, solely for investigational use by experts qualified by scientific training and experience to investigate the safety of drugs and which is plainly labeled "For investigational use only."

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2081[1945 c 257 § 81]; Rem. Supp. 1945 § 6163-130; ]

== 69.04.640 - Court review of denial.
The superior court of Thurston county shall have jurisdiction to review and to affirm, modify, or set aside any order issued under RCW 69.04.600, upon petition seasonably made by the person to whom the order is addressed and after prompt hearing upon due notice to both parties.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2082[1945 c 257 § 82]; Rem. Supp. 1945 § 6163-131; ]

== 69.04.650 - Dispensing of certain drugs exempt.
A drug dispensed on a written prescription signed by a physician, dentist, or veterinarian (except a drug dispensed in the course of the conduct of a business of dispensing drugs pursuant to diagnosis by mail) shall, if (1) such physician, dentist, or veterinarian is licensed by law to administer such drug, and (2) such drug bears a label containing the name and place of business of the dispenser, the serial number and date of such prescription, and the name of such physician, dentist, or veterinarian, be exempt from the operation of RCW 69.04.570 through 69.04.640.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2083[1945 c 257 § 83]; Rem. Supp. 1945 § 6163-132; ]

== 69.04.660 - Federally licensed drugs exempt.
The provisions of RCW 69.04.570 shall not apply to any drug which is licensed under the federal virus, serum, and toxin act of July 1, 1902; or under the federal virus, serums, toxins, antitoxins, and analogous products act of March 4, 1913.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2084[1945 c 257 § 84]; Rem. Supp. 1945 § 6163-133; ]

== 69.04.670 - Cosmetics—Adulteration by injurious substances.
A cosmetic shall be deemed to be adulterated (1) if it bears or contains any poisonous or deleterious substance which may render it injurious to users under the conditions of use prescribed in the labeling thereof, or under such conditions of use as are customary or usual: PROVIDED, That this provision shall not apply to coal tar hair dye, the label of which bears the following legend conspicuously displayed thereon: "Caution—This product contains ingredients which may cause skin irritation on certain individuals and a preliminary test according to accompanying direction should first be made. This product must not be used for dyeing the eyelashes or eyebrows; to do so may cause blindness.", and the labeling of which bears adequate directions for such preliminary testing. For the purposes of this paragraph and paragraph (5) the term "hair dye" shall not include eyelash dyes or eyebrow dyes; or (2) if it consists in whole or in part of any filthy, putrid, or decomposed substance; or (3) if it has been produced, prepared, packed, or held under insanitary conditions whereby it may have become contaminated with filth, or whereby it may have been rendered injurious to health; or (4) if its container is composed in whole or in part of any poisonous or deleterious substance which may render the contents injurious to health; or (5) if it is not a hair dye and it bears or contains a coal tar color other than one that is harmless and suitable for use in cosmetics, as provided by regulations promulgated under section 604 of the federal act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2085[1945 c 257 § 85]; Rem. Supp. 1945 § 6163-134; ]

== 69.04.680 - Cosmetics—Misbranding by false label, etc.
A cosmetic shall be deemed to be misbranded (1) if its labeling is false or misleading in any particular; or (2) if in package form, unless it bears a label containing (a) the name and place of business of the manufacturer, packer, or distributor; and (b) an accurate statement of the quantity of the contents in terms of weight, measure, or numerical count: PROVIDED, That under clause (b) of this section reasonable variations shall be permitted, and exemptions as to small packages shall be established, by regulations prescribed by the director.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2086[1945 c 257 § 86]; Rem. Supp. 1945 § 6163-135; ]

== 69.04.690 - Cosmetics—Misbranding by lack of prominent label.
A cosmetic shall be deemed to be misbranded (1) if any word, statement, or other information required by or under authority of this chapter to appear on the label or labeling is not prominently placed thereon with such conspicuousness (as compared with other words, statements, designs, or devices, in the labeling) and in such terms as to render it likely to be read and understood by the ordinary individual under customary conditions of purchase and use; or (2) if its container is so made, formed, or filled as to be misleading.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2087[1945 c 257 § 87]; Rem. Supp. 1945 § 6163-136; ]

== 69.04.700 - Cosmetics exempt if in transit for completion purposes.
A cosmetic which is, in accordance with the practice of the trade, to be processed, labeled, or repacked in substantial quantities at an establishment other than the establishment where it was originally processed or packed, is exempted from the affirmative labeling requirements of this chapter, while it is in transit in intrastate commerce from the one establishment to the other, if such transit is made in good faith for such completion purposes only; but it is otherwise subject to all the applicable provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2088[1945 c 257 § 88]; Rem. Supp. 1945 § 6163-137; ]

== 69.04.710 - Advertisement, when deemed false.
An advertisement of a drug, device, or cosmetic shall be deemed to be false, if it is false or misleading in any particular.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20602[2018 c 236 § 602]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2089[1945 c 257 § 89]; Rem. Supp. 1945 § 6163-138; ]

== 69.04.720 - Advertising of cure of certain diseases deemed false.
The advertisement of a drug or device representing it to have any effect in albuminuria, appendicitis, arteriosclerosis, blood poison, bone disease, Bright's disease, cancer, carbuncles, cholecystitis, diabetes, diphtheria, dropsy, erysipelas, gallstones, heart and vascular diseases, high blood pressure, mastoiditis, measles, meningitis, mumps, nephritis, otitis media, paralysis, pneumonia, poliomyelitis (infantile paralysis), prostate gland disorders, pyelitis, scarlet fever, sexual impotence, sinus infection, smallpox, tuberculosis, tumors, typhoid, uremia, *venereal disease, shall also be deemed to be false; except that no advertisement not in violation of RCW 69.04.710 shall be deemed to be false under this section if it is disseminated only to members of the medical, veterinary, dental, pharmacal, and other legally recognized professions dealing with the healing arts, or appears only in the scientific periodicals of these professions, or is disseminated only for the purpose of public health education by persons not commercially interested, directly or indirectly, in the sale of such drugs or devices: PROVIDED, That whenever the director determines that an advance in medical science has made any type of self-medication safe as to any of the diseases named above, the director shall by regulation authorize the advertisement of drugs having curative or therapeutic effect for such disease, subject to such conditions and restrictions as the director may deem necessary in the interest of public health: PROVIDED FURTHER, That this section shall not be construed as indicating that self-medication for diseases other than those named herein is safe or efficacious.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2090[1945 c 257 § 90]; Rem. Supp. 1945 § 6163-139; ]

== 69.04.730 - Enforcement, where vested—Regulations.
The authority to promulgate regulations for the efficient enforcement of this chapter is hereby vested in the director: PROVIDED, HOWEVER, That the director shall designate the pharmacy quality assurance commission to carry out all the provisions of this chapter pertaining to drugs and cosmetics, with authority to promulgate regulations for the efficient enforcement thereof.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1609.SL.pdf?cite=2013%20c%2019%20§%2051[2013 c 19 § 51]; 1947 c 25 § 91 (passed notwithstanding veto); 1945 c 257 § 91 (vetoed); Rem. Supp. 1947 § 6163-139a; ]

== 69.04.740 - Regulations to conform with federal regulations.
The purpose of this chapter being to promote uniformity of state legislation with the federal act, the director is hereby authorized (1) to adopt, insofar as applicable, the regulations from time to time promulgated under the federal act; and (2) to make the regulations promulgated under this chapter conform, insofar as practicable, with those promulgated under the federal act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2092[1945 c 257 § 92]; Rem. Supp. 1945 § 6163-140; ]

== 69.04.750 - Hearings.
Hearings authorized or required by this chapter shall be conducted by the director or his or her duly authorized representative designated for the purpose.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20341[2012 c 117 § 341]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2093[1945 c 257 § 93]; Rem. Supp. 1945 § 6163-141; ]

== 69.04.761 - Hearing on proposed regulation—Procedure.
The director shall hold a public hearing upon a proposal to promulgate any new or amended regulation under this chapter. The procedure to be followed concerning such hearings shall comply in all respects with chapter 34.05 RCW (Administrative Procedure Act) as now enacted or hereafter amended.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c198.pdf?cite=1963%20c%20198%20§%2013[1963 c 198 § 13]; ]

== 69.04.770 - Review on petition prior to effective date.
The director shall have jurisdiction to review and to affirm, modify, or set aside any order issued under *RCW 69.04.760, promulgating a new or amended regulation under this chapter, upon petition made at any time prior to the effective date of such regulation, by any person adversely affected by such order.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2095[1945 c 257 § 95]; Rem. Supp. 1945 § 6163-143; ]

== 69.04.780 - Investigations—Samples—Right of entry—Verified statements.
The director shall cause the investigation and examination of food, drugs, devices, and cosmetics subject to this chapter. The director shall have the right (1) to take a sample or specimen of any such article, for examination under this chapter, upon tendering the market price therefor to the person having such article in custody; and (2) to enter any place or establishment within this state, at reasonable times, for the purpose of taking a sample or specimen of any such article, for such examination.

The director and the director's deputies, assistants, and inspectors are authorized to do all acts and things necessary to carry out the provisions of this chapter, including the taking of verified statements. Such department personnel are empowered to administer oaths of verification on the statements.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1955.SL.pdf?cite=1991%20c%20162%20§%206[1991 c 162 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2096[1945 c 257 § 96]; Rem. Supp. 1945 § 6163-144; ]

== 69.04.790 - Owner may obtain part of sample.
Where a sample or specimen of any such article is taken for examination under this chapter, the director shall, upon request, provide a part thereof for examination by any person named on the label of such article, or the owner thereof, or his or her attorney or agent; except that the director is authorized, by regulation, to make such reasonable exceptions from, and to impose such reasonable terms and conditions relating to, the operation of this section as he or she finds necessary for the proper administration of the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20342[2012 c 117 § 342]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2097[1945 c 257 § 97]; Rem. Supp. 1945 § 6163-145; ]

== 69.04.800 - Access to records of other agencies.
For the purpose of enforcing the provisions of this chapter, pertinent records of any administrative agency of the state government shall be open to inspection by the director.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2098[1945 c 257 § 98]; Rem. Supp. 1945 § 6163-146; ]

== 69.04.810 - Access to records of intrastate carriers.
For the purpose of enforcing the provisions of this chapter, carriers engaged in intrastate commerce, and persons receiving drugs, devices, or cosmetics in intrastate commerce or holding such articles so received, shall, upon the request of the director, permit the director at reasonable times, to have access to and to copy all records showing the movement in intrastate commerce of any drug, device, or cosmetic, or the holding thereof during or after such movement, and the quantity, shipper, and consignee thereof; and it shall be unlawful for any such carrier or person to fail to permit such access to and the copying of any such records so requested when such request is accompanied by a statement in writing specifying the nature or kind of drug, device, or cosmetic to which such request relates: PROVIDED, That evidence obtained under this section shall not be used in a criminal prosecution of the person from whom obtained: PROVIDED FURTHER, That carriers shall not be subject to the other provisions of this chapter by reason of their receipt, carriage, holding, or delivery of drugs, devices, or cosmetics in the usual course of business as carriers.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20603[2018 c 236 § 603]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c202.pdf?cite=1990%20c%20202%20§%209[1990 c 202 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%2099[1945 c 257 § 99]; Rem. Supp. 1945 § 6163-147; ]

== 69.04.820 - Right of entry to factories, warehouses, vehicles, etc.
For the purpose of enforcing the provisions of this chapter, the director is authorized (1) to enter, at reasonable times, any factory, warehouse, or establishment subject to this chapter, or to enter any vehicle being used to transport or hold drugs, devices, or cosmetics in intrastate commerce; and (2) to inspect, at reasonable times, such factory, warehouse, establishment, or vehicle and all pertinent equipment, finished and unfinished materials, containers, labeling, and advertisements therein.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20604[2018 c 236 § 604]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%20100[1945 c 257 § 100]; Rem. Supp. 1945 § 6163-148; ]

== 69.04.830 - Publication of reports of judgments, orders and decrees.
The director may cause to be published from time to time reports summarizing all judgments, decrees, and court orders which have been rendered under this chapter, including the nature of the charge and the disposition thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%20101[1945 c 257 § 101]; Rem. Supp. 1945 § 6163-149; ]

== 69.04.840 - Dissemination of information.
The director may cause to be disseminated information regarding food, drugs, devices, or cosmetics in situations involving, in the opinion of the director, imminent danger to health or gross deception of, or fraud upon, the consumer. Nothing in this section shall be construed to prohibit the director from collecting, reporting, and illustrating the results of his or her examinations and investigations under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20343[2012 c 117 § 343]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%20102[1945 c 257 § 102]; Rem. Supp. 1945 § 6163-150; ]

== 69.04.850 - Construction—1945 c 257.
This chapter and the rules adopted hereunder shall be so interpreted and construed as to effectuate its general purpose to secure uniformity with federal acts and regulations relating to adulterating, misbranding and false advertising of drugs, devices, and cosmetics.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20605[2018 c 236 § 605]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%20104[1945 c 257 § 104]; Rem. Supp. 1945 § 6163-152; ]

== 69.04.860 - Effective date of chapter—1945 c 257.
This chapter shall take effect ninety days after the date of its enactment, and all state laws or parts of laws in conflict with this chapter are then repealed: PROVIDED, That the provisions of section 91 shall become effective on the enactment of this chapter, and thereafter the director is hereby authorized to conduct hearings and to promulgate regulations which shall become effective on or after the effective date of this chapter as the director shall direct: PROVIDED FURTHER, That all other provisions of this chapter to the extent that they may relate to the enforcement of such sections, shall take effect on the date of the enactment of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c257.pdf?cite=1945%20c%20257%20§%20105[1945 c 257 § 105]; Rem. Supp. 1945 § 6163-153; ]

== 69.04.880 - Civil penalty.
Whenever the director finds that a person has committed a violation of a provision of this chapter, the director may impose upon and collect from the violator a civil penalty not exceeding one thousand dollars per violation per day. Each and every such violation shall be a separate and distinct offense. Imposition of the civil penalty shall be subject to a hearing in conformance with chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1955.SL.pdf?cite=1991%20c%20162%20§%202[1991 c 162 § 2]; ]

