= 69.10 - Food storage warehouses.
:toc:

== 69.10.005 - Definitions.
For the purpose of this chapter:

. "Food storage warehouse" means any premises, establishment, building, room area, facility, or place, in whole or in part, where food is stored, kept, or held for wholesale distribution to other wholesalers or to retail outlets, restaurants, and any such other facility selling or distributing to the ultimate consumer. Food storage warehouses include, but are not limited to, facilities where food is kept or held refrigerated or frozen and include facilities where food is stored to the account of another firm and/or is owned by the food storage warehouse. "Food storage warehouse" does not include grain elevators or fruit and vegetable storage and packing houses that store, pack, and ship fresh fruit and vegetables even though they may use refrigerated or controlled atmosphere storage practices in their operation. However, this chapter applies to multiple food storage operations that also distribute or ripen fruits and vegetables.

. "Department" means the Washington department of agriculture.

. "Director" means the director of the Washington department of agriculture.

. "Food" means the same as defined in the food safety and security act under chapter 15.130 RCW.

. "Independent sanitation consultant" means an individual, partnership, cooperative, or corporation that by reason of education, certification, and experience has satisfactorily demonstrated expertise in food and dairy sanitation and is approved by the director to advise on such areas including, but not limited to: Principles of cleaning and sanitizing food processing plants and equipment; rodent, insect, bird, and other pest control; principles of hazard analysis critical control point; basic food product labeling; principles of proper food storage and protection; proper personnel work practices and attire; sanitary design, construction, and installation of food plant facilities, equipment, and utensils; and other pertinent food safety issues.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20716[2018 c 236 § 716]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5315-S.SL.pdf?cite=1995%20c%20374%20§%208[1995 c 374 § 8]; ]

== 69.10.010 - Inspection of food storage warehouses—Powers of director.
The director or his or her representative may inspect food storage warehouses for compliance with the provisions of chapter 15.130 RCW and the rules adopted under chapter 15.130 RCW as deemed necessary by the director. Any food storage warehouse found to not be in substantial compliance with chapter 15.130 RCW and the rules adopted under chapter 15.130 RCW will be reinspected as deemed necessary by the director to determine compliance. This does not preclude the director from using any other remedies as provided under chapter 15.130 RCW to gain compliance or to embargo products as provided under RCW 15.130.520 to protect the public from adulterated foods.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20717[2018 c 236 § 717]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5315-S.SL.pdf?cite=1995%20c%20374%20§%209[1995 c 374 § 9]; ]

== 69.10.015 - Annual license required—Director's duties—Fee—Application—Renewal.
. Except as provided in this section and RCW 69.10.020, it shall be unlawful for any person to operate a food storage warehouse in the state without first having obtained an annual license from the department, which shall expire on a date set by rule by the director. Application for a license or license renewal shall be on a form prescribed by the director and accompanied by the license fee. The license fee is two hundred dollars.

. For a food storage warehouse that has been inspected on at least an annual basis for compliance with the provisions of the current good manufacturing practices (Title 21 C.F.R. part 110) by a federal agency or by a state agency acting on behalf of and under contract with a federal agency and that is not exempted from licensure by RCW 69.10.020, the annual license fee for the warehouse is twenty-five dollars.

. The application shall include the full name of the applicant for the license and the location of the food storage warehouse he or she intends to operate. If such applicant is an individual, receiver, trustee, firm, partnership, association, or corporation, the full name of each member of the firm or partnership, or names of the officers of the association or corporation must be given on the application. The application shall further state the principal business address of the applicant in the state and elsewhere and the name of a person domiciled in this state authorized to receive and accept service of summons of legal notices of all kinds for the applicant. Upon the approval of the application by the director and compliance with the provisions of this chapter, including the applicable regulations adopted under this chapter by the department, the applicant shall be issued a license or renewal thereof. The director shall waive licensure under this chapter for firms that are licensed under the provisions of chapter 69.07 or 15.36 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2128-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2027%20§%209[2015 3rd sp.s. c 27 § 9]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5315-S.SL.pdf?cite=1995%20c%20374%20§%2010[1995 c 374 § 10]; ]

== 69.10.020 - Exemption from licensure—Independent inspection—Report to department.
. A food storage warehouse that is inspected for compliance with the current good manufacturing practices (Title 21 C.F.R. part 110) on at least an annual basis by an independent sanitation consultant approved by the department is not required to be licensed under this chapter. A report identifying the inspector and the inspecting entity, the date of the inspection, and any violations noted on such inspection shall be forwarded to the department by the food storage warehouse within sixty days of the completion of the inspection. An inspection shall be conducted and an inspection report for a food storage warehouse shall be filed with the department at least once every twelve months or the warehouse shall be licensed under this chapter and inspected by the department for a period of two years.

. A food storage warehouse used to store alcohol beverages manufactured or distributed under a license issued pursuant to chapter 66.24 RCW is not required to be licensed under this chapter, provided alcohol beverages are the only food stored in the warehouse.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2699.SL.pdf?cite=2018%20c%2096%20§%201[2018 c 96 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5315-S.SL.pdf?cite=1995%20c%20374%20§%2011[1995 c 374 § 11]; ]

== 69.10.025 - Application for renewal of license after expiration date—Additional fee.
If the application for renewal of any license provided for under this chapter is not filed prior to the expiration date as established by rule by the director, an additional fee of ten percent of the cost of the license shall be assessed and added to the original fee and must be paid by the applicant before the renewal license is issued.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5315-S.SL.pdf?cite=1995%20c%20374%20§%2012[1995 c 374 § 12]; ]

== 69.10.030 - Director may deny, suspend, or revoke license—Actions by applicant—Hearing required.
The director may, subsequent to a hearing thereon, deny, suspend, or revoke any license provided for in this chapter if he or she determines that an applicant has committed any of the following acts:

. Refused, neglected, or failed to comply with the provisions of this chapter, the rules adopted under this chapter, or any lawful order of the director;

. Refused, neglected, or failed to keep and maintain records required by this chapter, or to make such records available if requested pursuant to the provisions of this chapter;

. Refused the department access to any portion or area of the food storage warehouse for the purpose of carrying out the provisions of this chapter;

. Refused the department access to any records required to be kept under the provisions of this chapter;

. Refused, neglected, or failed to comply with any provisions of the food safety and security act under chapter 15.130 RCW, or any rules adopted under chapter 15.130 RCW.

The provisions of this section requiring that a hearing be conducted before an action may be taken against a license do not apply to an action taken under RCW 69.10.035.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20718[2018 c 236 § 718]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5315-S.SL.pdf?cite=1995%20c%20374%20§%2013[1995 c 374 § 13]; ]

== 69.10.035 - Immediate danger to public health—Summarily suspending license—Written notification—Hearing—Reinstatement of license.
. Whenever the director finds a food storage warehouse operating under conditions that constitute an immediate danger to public health or whenever the licensee or any employee of the licensee actively prevents the director or the director's representative, during an on-site inspection, from determining whether such a condition exists, the director may summarily suspend, pending a hearing, a license provided for in this chapter.

. Whenever a license is summarily suspended, the holder of the license shall be notified in writing that the license is, upon service of the notice, immediately suspended and that prompt opportunity for a hearing will be provided.

. Whenever a license is summarily suspended, food distribution operations shall immediately cease. However, the director may reinstate the license if the condition that caused the suspension has been abated to the director's satisfaction.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5315-S.SL.pdf?cite=1995%20c%20374%20§%2014[1995 c 374 § 14]; ]

== 69.10.040 - Unlicensed food storage warehouse—Unlawful to sell, offer for sale, or distribute in intrastate commerce.
It is unlawful to sell, offer for sale, or distribute in intrastate commerce food from or stored in a food storage warehouse that is required to be licensed under this chapter but that has not obtained a license, once notification by the director has been given to the persons selling, offering, or distributing food for sale, that the food is in or from such an unlicensed food storage warehouse.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5315-S.SL.pdf?cite=1995%20c%20374%20§%2015[1995 c 374 § 15]; ]

== 69.10.045 - Disposition of moneys received under this chapter.
All moneys received by the department under provisions of this chapter, except moneys collected for civil penalties levied under this chapter, shall be paid into an account created in the agricultural local fund established in RCW 43.23.230 and shall be used solely to carry out provisions of this chapter and chapter 15.130 RCW. All moneys collected for civil penalties levied under this chapter shall be deposited in the state general fund.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20719[2018 c 236 § 719]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5315-S.SL.pdf?cite=1995%20c%20374%20§%2016[1995 c 374 § 16]; ]

== 69.10.050 - Civil remedies—Restrictions on civil penalties—Fee limitations for inspections and analyses.
. Except as provided in subsection (2) of this section, the department may use all the civil remedies provided under chapter 15.130 RCW in carrying out and enforcing the provisions of this chapter.

. Civil penalties are intended to be used to obtain compliance and shall not be collected if a warehouse successfully completes a mutually agreed upon compliance agreement with the department. A warehouse that enters into a compliance agreement with the department shall pay only for inspections conducted by the department and any laboratory analyses as required by the inspections as outlined and agreed to in the compliance agreement. In no event shall the fee for these inspections and analyses exceed four hundred dollars per inspection or one thousand dollars in total.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6318-S.SL.pdf?cite=2018%20c%20236%20§%20720[2018 c 236 § 720]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5315-S.SL.pdf?cite=1995%20c%20374%20§%2017[1995 c 374 § 17]; ]

== 69.10.055 - Rules.
. The department shall enforce and carry out the provisions of this chapter and may adopt the necessary rules to carry out its purpose.

. The adoption of rules under the provisions of this chapter are subject to the applicable provisions of chapter 34.05 RCW, the administrative procedure act.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5315-S.SL.pdf?cite=1995%20c%20374%20§%2018[1995 c 374 § 18]; ]

== 69.10.060 - Director and deputies, assistants, and inspectors authorized to act—May take verified statements.
The director or director's deputies, assistants, and inspectors are authorized to do all acts and things necessary to carry out the provisions of this chapter, including the taking of verified statements. The department personnel are empowered to administer oaths of verification on the statement.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5315-S.SL.pdf?cite=1995%20c%20374%20§%2019[1995 c 374 § 19]; ]

== 69.10.900 - Effective date—1995 c 374 §§ 1-47, 50-53, and 59-68.
See note following RCW 15.36.012.

[ ]

