= 69.28 - Honey.
:toc:

== 69.28.020 - Enforcement power and duty of director and agents.
The director is hereby empowered, through his or her duly authorized agents, to enforce all provisions of this chapter. The director shall have the power to define, promulgate, and enforce such reasonable regulations as he or she may deem necessary in carrying out the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20356[2012 c 117 § 356]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2029[1939 c 199 § 29]; RRS § 6163-29. FORMER PART OF SECTION: 1939 c 199 § 44 now codified as RCW  69.28.025; ]

== 69.28.025 - Rules and regulations have force of law.
Any rules or regulations promulgated and published by the director under the provisions of this chapter shall have the force and effect of law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2044[1939 c 199 § 44]; RRS § 6163-44; ]

== 69.28.030 - Rules prescribing standards.
The director is hereby authorized, and it shall be his or her duty, upon the taking effect of this chapter and from time to time thereafter, to adopt, establish, and promulgate reasonable rules and regulations specifying grades or standards of quality governing the sale of honey: PROVIDED, That, in the interest of uniformity, such grades and standards of quality shall conform as nearly to those established by the United States department of agriculture as local conditions will permit.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20357[2012 c 117 § 357]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2024[1939 c 199 § 24]; RRS § 6163-24; ]

== 69.28.040 - Right to enter, inspect, and take samples.
The director or any of his or her duly authorized agents shall have the power to enter and inspect at reasonable times every place, vehicle, plant, or other place where honey is being produced, stored, packed, transported, exposed, or offered for sale, and to inspect all such honey and the containers thereof and to take for inspection such samples of said honey as may be necessary.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20358[2012 c 117 § 358]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2028[1939 c 199 § 28]; RRS § 6163-28; ]

== 69.28.050 - Containers to be labeled.
It shall be unlawful to deliver for shipment, ship, transport, sell, expose or offer for sale any containers or subcontainers of honey within this state unless they shall be conspicuously marked with the name and address of the producer or distributor, the net weight of the honey, the grade of the honey, and, if imported from any foreign country, the name of the country or territory from which the said honey was imported, or if a blend of honey, any part of which is foreign honey, the container must be labeled with the name of the country or territory where such honey was produced and the proportion of each foreign honey used in the blend.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2032[1939 c 199 § 32]; RRS § 6163-32; ]

== 69.28.060 - Requisites of markings.
When any markings are used or required to be used under this chapter on any container of honey to identify the container or describe the contents thereof, such markings must be plainly and conspicuously marked, stamped, stenciled, printed, labeled or branded in the English language, in letters large enough to be discernible by any person, on the front, side or top of any container.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2035[1939 c 199 § 35]; RRS § 6163-35; ]

== 69.28.070 - "Marked" defined—When honey need not be marked.
The term "marked" shall mean printed in the English language on the top, front or side of any container containing honey: PROVIDED, That it shall not be necessary to mark honey sold by the producer thereof to any distributor, packer or manufacturer with the net weight, color or grade if the honey is to be used in the manufacture of honey products or is to be graded and packaged by the distributor or packer for resale.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2021[1939 c 199 § 21]; RRS § 6163-21; ]

== 69.28.080 - Purchaser to be advised of standards—Exceptions.
It shall be unlawful for any person to deliver, sell, offer, or expose for sale any honey for human consumption within the state without notifying the person or persons purchasing or intending to purchase the same, of the exact grade or quality of such honey, according to the standards prescribed by the director, by stamping or printing on the container of any such honey such grade or quality: PROVIDED, This section shall not apply to honey while it is in transit in intrastate commerce from one establishment to the other, to be processed, labeled, or repacked.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c60.pdf?cite=1961%20c%2060%20§%201[1961 c 60 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c103.pdf?cite=1957%20c%20103%20§%201[1957 c 103 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c105.pdf?cite=1949%20c%20105%20§%206[1949 c 105 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2039[1939 c 199 § 39]; Rem. Supp. 1949 § 6163-39; ]

== 69.28.090 - Forgery, simulation, etc., of marks, labels, etc., unlawful.
It shall be unlawful to forge, counterfeit, simulate, falsely represent or alter without proper authority any mark, stamp, tab, label, seal, sticker or other identification device provided by this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c60.pdf?cite=1961%20c%2060%20§%202[1961 c 60 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2040[1939 c 199 § 40]; RRS § 6163-40. FORMER PART OF SECTION: 1939 c 199 § 41 now codified as RCW  69.28.095; ]

== 69.28.095 - Unlawful mutilation or removal of seals, marks, etc., used by director.
It shall be unlawful to mutilate, destroy, obliterate, or remove without proper authority, any mark, stamp, tag, label, seal, sticker or other identification device used by the director under the provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2041[1939 c 199 § 41]; RRS § 6163-41; ]

== 69.28.100 - Marks for "slack-filled" container.
Any slack-filled container shall be conspicuously marked "slack-filled".

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2036[1939 c 199 § 36]; RRS § 6163-36. FORMER PART OF SECTION: 1939 c 199 § 10 now codified as RCW  69.28.270; ]

== 69.28.110 - Use of used containers.
It shall be unlawful to sell, offer, or expose for sale to the consumer any honey in any secondhand or used containers which formerly contained honey, unless all markings as to grade, name and weight have been obliterated, removed or erased.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2037[1939 c 199 § 37]; RRS § 6163-37; ]

== 69.28.120 - Floral source labels.
Any honey which is a blend of two or more floral types of honey shall not be labeled as a honey product from any one particular floral source alone.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2034[1939 c 199 § 34]; RRS § 6163-34; ]

== 69.28.130 - Adulterated honey—Sale or offer unlawful.
It shall be unlawful for any person to sell, offer or intend for sale any adulterated honey as honey.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2026[1939 c 199 § 26]; RRS § 6163-26. FORMER PART OF SECTION: 1939 c 199 §§ 27 and 33 now codified as RCW  69.28.133 and  69.28.135; ]

== 69.28.133 - Nonconforming honey—Sale or offer unlawful.
It shall be unlawful for any person to sell, offer or intend for sale any honey which does not conform to the provisions of this chapter or any regulation promulgated by the director under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2027[1939 c 199 § 27]; RRS § 6163-27; ]

== 69.28.135 - Warning-tagged honey—Movement prohibited.
It shall be unlawful to move any honey or containers of honey to which any warning tag or notice has been affixed except under authority from the director.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2033[1939 c 199 § 33]; RRS § 6163-33; ]

== 69.28.140 - Possession of unlawful honey as evidence.
Possession by any person, of any honey which is sold, exposed or offered for sale in violation of this chapter shall be prima facie evidence that the same is kept or shipped to the said person, in violation of the provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2030[1939 c 199 § 30]; RRS § 6163-30; ]

== 69.28.170 - Inspectors—Prosecutions.
It shall be the duty of the director to enforce this chapter and to appoint and employment [employ] such inspectors as may be necessary therefor. The director shall notify the prosecuting attorneys for the counties of the state of violations of this chapter occurring in their respective counties, and it shall be the duty of the respective prosecuting attorneys immediately to institute and prosecute proceeding in their respective counties and to enforce the penalties provided for by this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2043[1939 c 199 § 43]; RRS § 6163-43; ]

== 69.28.180 - Violation of rules and regulations unlawful.
It shall be unlawful for any person to violate any rule or regulation promulgated by the director under the provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2025[1939 c 199 § 25]; RRS § 6163-25. FORMER PART OF SECTION: 1939 c 199 § 44 now codified in RCW  69.28.185; ]

== 69.28.185 - Penalty.
Any person who violates any of the provisions of this chapter shall be guilty of a misdemeanor, and upon violation thereof shall be punishable by a fine of not more than five hundred dollars or imprisonment in the county jail for a period of not more than six months or by both such fine and imprisonment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2042[1939 c 199 § 42]; RRS § 6163-42; ]

== 69.28.190 - "Director" defined.
The term "director" means the director of agriculture of the state of Washington or his or her duly authorized representative.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20359[2012 c 117 § 359]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%202[1939 c 199 § 2]; RRS § 6163-2; ]

== 69.28.200 - "Container" defined.
The term "container" shall mean any box, crate, chest, carton, barrel, keg, bottle, jar, can or any other receptacle containing honey.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%203[1939 c 199 § 3]; RRS § 6163-3; ]

== 69.28.210 - "Subcontainer" defined.
The term "subcontainer" shall mean any section box or other receptacle used within a container.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%204[1939 c 199 § 4]; RRS § 6163-4; ]

== 69.28.220 - "Section box" defined.
The term "section box" shall mean the wood or other frame in which bees have built a small comb of honey.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%205[1939 c 199 § 5]; RRS § 6163-5; ]

== 69.28.230 - "Clean and sound containers" defined.
The term "clean and sound containers" shall mean containers which are virtually free from rust, stains or leaks.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%206[1939 c 199 § 6]; RRS § 6163-6; ]

== 69.28.240 - "Pack," "packing," or "packed" defined.
The term "pack", "packing", or "packed" shall mean the arrangement of all or part of the subcontainers in any container.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%207[1939 c 199 § 7]; RRS § 6163-7; ]

== 69.28.250 - "Label" defined.
The term "label" shall mean a display of written, printed or graphic matter upon the immediate container of any article.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%208[1939 c 199 § 8]; RRS § 6163-8; ]

== 69.28.260 - "Person" defined.
The term "person" includes individual, partnership, corporation and/or association.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%209[1939 c 199 § 9]; RRS § 6163-9; ]

== 69.28.270 - "Slack-filled" defined.
The term "slack-filled" shall mean that the contents of any container occupy less than ninety-five percent of the volume of the closed container.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2010[1939 c 199 § 10]; RRS § 6163-10; ]

== 69.28.280 - "Deceptive arrangement" defined.
The term "deceptive arrangement" shall mean any lot or load, arrangement or display of honey which has in any exposed surface, honey which is so superior in quality, appearance or condition, or in any other respects, to any of that which is concealed or unexposed as to materially misrepresent any part of the lot, load, arrangement or display.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2011[1939 c 199 § 11]; RRS § 6163-11; ]

== 69.28.290 - "Mislabeled" defined.
The term "mislabeled" shall mean the placing or presence of any false or misleading statement, design or device upon, or in connection with, any container or lot of honey, or upon the label, lining or wrapper of any such container, or any placard used in connection therewith, and having reference to such honey. A statement, design or device is false and misleading when the honey to which it refers does not conform in every respect to such statement.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2012[1939 c 199 § 12]; RRS § 6163-12; ]

== 69.28.300 - "Placard" defined.
The term "placard" means any sign, label or designation, other than an oral designation, used with any honey as a description or identification thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2013[1939 c 199 § 13]; RRS § 6163-13; ]

== 69.28.310 - "Honey" defined.
The term "honey" as used herein is the nectar of floral exudations of plants, gathered and stored in the comb by honey bees (apis mellifica). It is laevo-rotatory, contains not more than twenty-five percent of water, not more than twenty-five one-hundredths of one percent of ash, not more than eight percent of sucrose, its specific gravity is 1.412, its weight not less than eleven pounds twelve ounces per standard gallon of 231 cubic inches at sixty-eight degrees Fahrenheit.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2014[1939 c 199 § 14]; RRS § 6163-14; ]

== 69.28.320 - "Comb-honey" defined.
The term "comb-honey" means honey which has not been extracted from the comb.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2015[1939 c 199 § 15]; RRS § 6163-15; ]

== 69.28.330 - "Extracted honey" defined.
The term "extracted honey" means honey which has been removed from the comb.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2016[1939 c 199 § 16]; RRS § 6163-16; ]

== 69.28.340 - "Crystallized honey" defined.
The term "crystallized honey" means honey which has assumed a solid form due to the crystallization of one or more of the natural sugars therein.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2017[1939 c 199 § 17]; RRS § 6163-17; ]

== 69.28.350 - "Honeydew" defined.
The term "honeydew" is the saccharine exudation of plants, other than nectarous exudations, gathered and stored in the comb by honey bees (apis mellifica) and is dextrorotatory.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2018[1939 c 199 § 18]; RRS § 6163-18; ]

== 69.28.360 - "Foreign material" defined.
The term "foreign material" means pollen, wax particles, insects, or materials not deposited by bees.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c199.pdf?cite=1937%20c%20199%20§%2019[1937 c 199 § 19]; RRS § 6163-19; ]

== 69.28.370 - "Foreign honey" defined.
The term "foreign honey" means any honey not produced within the continental United States.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2020[1939 c 199 § 20]; RRS § 6163-20; ]

== 69.28.380 - "Adulterated honey" defined.
The term "adulterated honey" means any honey to which has been added honeydew, glucose, dextrose, molasses, sugar, sugar syrup, invert sugar, or any other similar product or products, other than the nectar of floral exudations of plants gathered and stored in the comb by honey bees.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2022[1939 c 199 § 22]; RRS § 6163-22; ]

== 69.28.390 - "Serious damage" defined.
The term "serious damage" means any injury or defect that seriously affects the edibility or shipping quality of the honey.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2023[1939 c 199 § 23]; RRS § 6163-23; ]

== 69.28.400 - Labeling requirements for artificial honey or mixtures containing honey.
. No person shall sell, keep for sale, expose or offer for sale, any article or product in imitation or semblance of honey branded exclusively as "honey", "liquid or extracted honey", "strained honey" or "pure honey".

. No person, firm, association, company or corporation shall manufacture, sell, expose or offer for sale, any compound or mixture branded or labeled exclusively as honey which shall be made up of honey mixed with any other substance or ingredient.

. Whenever honey is mixed with any other substance or ingredient and the commodity is to be marketed in imitation or semblance of honey, the product shall be labeled with the word "artificial" or "imitation" in the same type size and style as the word "honey";

. Whenever any substance or commodity is to be marketed in imitation or semblance of honey, but contains no honey, the product shall not be branded or labeled with the word "honey" and/or depict thereon a picture or drawing of a bee, bee hive, or honeycomb;

. Whenever honey is mixed with any other substance or ingredient and the commodity is to be marketed, there shall be printed on the package containing such compound or mixture a statement giving the ingredients of which it is made; if honey is one of such ingredients it shall be so stated in the same size type as are the other ingredients; nor shall such compound or mixture be branded or labeled exclusively with the word "honey" in any form other than as herein provided; nor shall any product in semblance of honey, whether a mixture or not, be sold, exposed or offered for sale as honey, or branded or labeled exclusively with the word "honey", unless such article is pure honey.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c283.pdf?cite=1975%201st%20ex.s.%20c%20283%20§%201[1975 1st ex.s. c 283 § 1]; ]

== 69.28.410 - Embargo on honey or product—Notice by director—Removal.
Whenever the director shall find, or shall have probable cause to believe, that any honey or product subject to the provisions of this chapter, as now or hereafter amended, is in intrastate commerce, which was introduced into such intrastate commerce in violation of the provisions of this chapter, as now or hereafter amended, he or she is hereby authorized to affix to such honey or product a notice placing an embargo on such honey or product, and prohibiting its sale in intrastate commerce, and no person shall move or sell such honey or product without first receiving permission from the director to move or sell such honey or product. But if, after such honey or product has been embargoed, the director shall find that such honey or product does not involve a violation of this chapter, as now or hereafter amended, such embargo shall be forthwith removed.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20360[2012 c 117 § 360]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c283.pdf?cite=1975%201st%20ex.s.%20c%20283%20§%203[1975 1st ex.s. c 283 § 3]; ]

== 69.28.420 - Embargo on honey or product—Court order affirming, required—Order for destruction or correction and release—Bond.
When the director has embargoed any honey or product, he or she shall, no later than twenty days after the affixing of notice of its embargo, petition the superior court for an order affirming such embargo. Such court shall then have jurisdiction, for cause shown and after prompt hearing to any claimant of such honey or product, to issue an order which directs the removal of such embargo or the destruction or the correction and release of such honey or product. An order for destruction or correction and release shall contain such provision for the payment of pertinent court costs and fees and administrative expenses, as is equitable and which the court deems appropriate in the circumstances. An order for correction and release may contain such provision for bond, as the court finds indicated in the circumstances.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20361[2012 c 117 § 361]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c283.pdf?cite=1975%201st%20ex.s.%20c%20283%20§%204[1975 1st ex.s. c 283 § 4]; ]

== 69.28.430 - Consolidation of petitions presenting same issue and claimant.
Two or more petitions under this chapter, as now or hereafter amended, which pend at the same time and which present the same issue and claimant hereunder, shall be consolidated for simultaneous determination by one court of jurisdiction, upon application to any court of jurisdiction by the director or by such claimant.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c283.pdf?cite=1975%201st%20ex.s.%20c%20283%20§%205[1975 1st ex.s. c 283 § 5]; ]

== 69.28.440 - Sample of honey or product may be obtained—Procedure.
The claimant in any proceeding by petition under this chapter, as now or hereafter amended, shall be entitled to receive a representative sample of the honey or product subject to such proceeding, upon application to the court of jurisdiction made at any time after such petition and prior to the hearing thereon.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c283.pdf?cite=1975%201st%20ex.s.%20c%20283%20§%206[1975 1st ex.s. c 283 § 6]; ]

== 69.28.450 - Recovery of damages barred if probable cause for embargo.
No state court shall allow the recovery of damages for embargo under this chapter, as now or hereafter amended, if the court finds that there was probable cause for such action.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c283.pdf?cite=1975%201st%20ex.s.%20c%20283%20§%207[1975 1st ex.s. c 283 § 7]; ]

== 69.28.900 - Severability—1939 c 199.
If any provisions of this chapter, or the application thereof to any person or circumstance, is held invalid, the remainder of the chapter, and the application of such provisions to other persons or circumstances, shall not be affected thereby. If any section, subsection, sentence, clause, or phrase of this chapter is for any reason held to be unconstitutional, such decisions shall not affect the validity of the remaining portions of this chapter. The legislature hereby declares that it would have passed this chapter and each section, subsection, sentence, clause and phrase thereof, irrespective of the fact that any one or more of the other sections, subsections, sentences, clauses and phrases be declared unconstitutional.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%2045[1939 c 199 § 45]; RRS § 6163-45; ]

== 69.28.910 - Short title.
This chapter may be known and cited as the Washington state honey act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c199.pdf?cite=1939%20c%20199%20§%201[1939 c 199 § 1]; RRS § 6163-1; ]

