= 69.30 - Sanitary control of shellfish.
:toc:

== 69.30.005 - Purpose.
The purpose of this chapter is to provide for the sanitary control of shellfish. Protection of the public health requires assurances that commercial shellfish are harvested only from approved growing areas and that processing of shellfish is conducted in a safe and sanitary manner.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c200.pdf?cite=1989%20c%20200%20§%202[1989 c 200 § 2]; ]

== 69.30.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Approved shellfish tag or label" means a tag or label meeting the requirements of the national shellfish sanitation program model ordinance.

. "Commercial quantity" means any quantity exceeding: (a) Forty pounds of mussels; (b) one hundred oysters; (c) fourteen horse clams; (d) six geoducks; (e) fifty pounds of hard or soft shell clams; or (f) fifty pounds of scallops. The poundage in this subsection (2) constitutes weight with the shell.

. "Department" means the state department of health.

. "Establishment" means the buildings, together with the necessary equipment and appurtenances, used for the storage, culling, shucking, packing and/or shipping of shellfish in commercial quantity or for sale for human consumption.

. "Ex officio fish and wildlife officer" means an ex officio fish and wildlife officer as defined in RCW 77.08.010.

. "Fish and wildlife officer" means a fish and wildlife officer as defined in RCW 77.08.010.

. "Person" means any individual, partnership, firm, company, corporation, association, or the authorized agents of any such entities.

. "Sale" means to sell, offer for sale, barter, trade, deliver, consign, hold for sale, consignment, barter, trade, or delivery, and/or possess with intent to sell or dispose of in any commercial manner.

. "Secretary" means the secretary of health or his or her authorized representatives.

. "Shellfish" means all varieties of fresh and frozen oysters, mussels, clams, and scallops, either shucked or in the shell, and any fresh or frozen edible products thereof.

. "Shellfish growing areas" means the lands and waters in and upon which shellfish are grown for harvesting in commercial quantity or for sale for human consumption.

. "Shellstock" means live molluscan shellfish in the shell.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1453-S.SL.pdf?cite=2011%20c%20194%20§%201[2011 c 194 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5961-S.SL.pdf?cite=2001%20c%20253%20§%205[2001 c 253 § 5]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1404-S.SL.pdf?cite=1995%20c%20147%20§%201[1995 c 147 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20303[1991 c 3 § 303]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c200.pdf?cite=1989%20c%20200%20§%201[1989 c 200 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c51.pdf?cite=1985%20c%2051%20§%201[1985 c 51 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%2070[1979 c 141 § 70]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c144.pdf?cite=1955%20c%20144%20§%201[1955 c 144 § 1]; ]

== 69.30.020 - Approved shellfish tag or label—Requirement to sell or offer to sell shellfish.
It is unlawful to sell or offer to sell shellfish in this state unless the shellfish bear an approved shellfish tag or label indicating compliance with the sanitary requirements of this state or a state, territory, province, or country of origin whose requirements are equal or comparable to those established pursuant to this chapter. The department, a fish and wildlife officer, or an ex officio fish and wildlife officer may immediately seize containers of shellfish that are not affixed with an approved shellfish tag or label.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1453-S.SL.pdf?cite=2011%20c%20194%20§%202[2011 c 194 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c144.pdf?cite=1955%20c%20144%20§%202[1955 c 144 § 2]; ]

== 69.30.030 - Rules and regulations—Duties of state board of health.
. The state board of health shall adopt rules governing the sanitation of shellfish, shellfish growing areas, and shellfish plant facilities and operations in order to protect public health and carry out the provisions of this chapter. Such rules and regulations may include reasonable sanitary requirements relative to the quality of shellfish growing waters and areas, boat and barge sanitation, building construction, water supply, sewage and wastewater disposal, lighting and ventilation, insect and rodent control, shell disposal, garbage and waste disposal, cleanliness of establishment, the handling, storage, construction and maintenance of equipment, the handling, storage and refrigeration of shellfish, the identification of containers, and the handling, maintenance, and storage of permits, certificates, and records regarding shellfish taken under this chapter. The state board of health shall adopt rules governing procedures for the disposition of seized shellfish.

. The state board of health shall consider the most recent version of the national shellfish sanitation program model ordinance, adopted by the interstate shellfish sanitation conference, when adopting rules.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1453-S.SL.pdf?cite=2011%20c%20194%20§%203[2011 c 194 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1404-S.SL.pdf?cite=1995%20c%20147%20§%202[1995 c 147 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c144.pdf?cite=1955%20c%20144%20§%203[1955 c 144 § 3]; ]

== 69.30.050 - Shellfish growing areas—Requirements to harvest—Certificates of approval.
. It is unlawful for a person to harvest shellfish from shellfish growing areas in a commercial quantity or for sale for human consumption unless the shellfish growing area:

.. Has a valid certificate of approval; and

.. Meets the requirements of this chapter and the rules adopted under this chapter.

. A person may not remove shellfish in a commercial quantity or for sale for human consumption from a shellfish growing area in the state of Washington unless:

.. The person has received a certificate of approval for the shellfish growing area from the department; and

.. Approved shellfish tags are affixed to each container of shellstock prior to removal from the shellfish growing area, except bulk tagging is permitted as allowed in the national shellfish sanitation program model ordinance. 

. Before issuing a certificate of approval, the department shall inspect the shellfish growing area. The department shall issue a certificate of approval if the area meets the requirements of this chapter and the rules adopted under this chapter.

. A certificate of approval is valid for a period of twelve months. The department may revoke a certificate of approval at any time the area is found out of compliance with the requirements of this chapter or the rules adopted under this chapter.

. It is unlawful to remove shellfish from shellfish growing areas without a certificate of approval in a commercial quantity for purposes other than human consumption, including but not limited to use as bait or seed, unless:

.. The shellfish operation and shellfish growing area is readily available to monitoring and inspections; and

.. The department has determined the shellfish operation is designed to ensure that shellfish harvested from such an area is not diverted for human consumption.

. Nothing in this section prohibits a person from removing shellfish for use as bait or seed from an approved shellfish growing area.

. The department's certificate of approval to harvest shellfish for purposes other than human consumption shall specify:

.. The date or dates and time of harvest;

.. All applicable conditions of harvest;

.. Identification by tagging, dying, or other department-approved means; and

.. Information about the removal method, transportation method, processing technique, sale details, and other factors to ensure that shellfish harvested from such areas are not diverted for human consumption.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1453-S.SL.pdf?cite=2011%20c%20194%20§%204[2011 c 194 § 4]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1404-S.SL.pdf?cite=1995%20c%20147%20§%203[1995 c 147 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c51.pdf?cite=1985%20c%2051%20§%202[1985 c 51 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c144.pdf?cite=1955%20c%20144%20§%205[1955 c 144 § 5]; ]

== 69.30.060 - Certificates of approval—Culling, shucking, packing establishments.
. It is unlawful for a person to cull, shuck, or pack shellfish in the state of Washington in a commercial quantity or for sale for human consumption unless the establishment in which such operations are conducted has been certified by the department as meeting the requirements of the state board of health. 

. A person may not cull, shuck, or pack shellfish within the state of Washington in a commercial quantity or for sale for human consumption, unless the person has received a certificate of approval from the department for the establishment in which such operations will be done.

. Before issuing a certificate of approval, the department shall inspect the establishment, and if the establishment meets the rules of the state board of health, the department shall issue a certificate of approval. Such certificates of approval shall be issued for a period not to exceed twelve months, and may be revoked at any time the establishment or the operations are found not to be in compliance with the rules of the state board of health.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1453-S.SL.pdf?cite=2011%20c%20194%20§%205[2011 c 194 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c51.pdf?cite=1985%20c%2051%20§%203[1985 c 51 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c144.pdf?cite=1955%20c%20144%20§%206[1955 c 144 § 6]; ]

== 69.30.070 - Certificates of approval—Compliance with other laws and rules required.
Any certificate of approval issued under the provisions of this chapter shall not relieve any person from complying with the laws, rules and/or regulations of the department of fish and wildlife, relative to shellfish.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2590.SL.pdf?cite=1994%20c%20264%20§%2040[1994 c 264 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c144.pdf?cite=1955%20c%20144%20§%207[1955 c 144 § 7]; ]

== 69.30.080 - Licenses or certificates of approval—Department may deny, revoke, or suspend.
. The department may deny, revoke, or suspend a person's license or certificate of approval for:

.. Violations of this chapter or the rules adopted under this chapter; or

.. Harassing or threatening an authorized representative of the department during the performance of his or her duties.

. RCW 43.70.115 governs notice of a license denial, revocation, suspension, or modification and provides the right to an adjudicative proceeding.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1453-S.SL.pdf?cite=2011%20c%20194%20§%206[2011 c 194 § 6]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20304[1991 c 3 § 304]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%20125[1989 c 175 § 125]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%2071[1979 c 141 § 71]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c144.pdf?cite=1955%20c%20144%20§%208[1955 c 144 § 8]; ]

== 69.30.085 - License, certificate of approval—Denial, revocation, suspension—Prohibited acts—Penalties.
. A person, or its director or officer, whose license or certificate of approval is denied, revoked, or suspended as a result of violations of this chapter or rules adopted under this chapter may not:

.. Supervise, be employed by, or manage a shellfish operation licensed or certified under this chapter or rules adopted under this chapter;

.. Participate in the harvesting, shucking, packing, or shipping of shellfish in commercial quantities or for sale;

.. Participate in the brokering of shellfish, purchase of shellfish for resale, or retail sale of shellfish; or

.. Engage in any activity associated with selling or offering to sell shellfish.

. Subsections (1)(c) and (d) of this section do not apply to retail purchases of shellfish for personal use.

. Subsection (1) of this section applies to a person only during the period of time in which that person's license or certificate of approval is denied, revoked, or suspended.

. Unlawful operations under subsection (1) of this section when a license or certificate of approval is denied, revoked, or suspended is a class C felony. Upon conviction, the department shall order that the person's license or certificate of approval be revoked for a period of at least five years, or that a person whose application for a license or certificate of approval was denied be ineligible to reapply for a period of at least five years.

. A license or certificate of approval issued under this chapter may not be assigned or transferred in any manner without department approval.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1453-S.SL.pdf?cite=2011%20c%20194%20§%207[2011 c 194 § 7]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2537.SL.pdf?cite=1998%20c%2044%20§%201[1998 c 44 § 1]; ]

== 69.30.110 - Possession or sale in violation of chapter—Enforcement—Seizure—Disposal.
. It is unlawful for any person to possess a commercial quantity of shellfish or to sell or offer to sell shellfish in the state which have not been grown, shucked, packed, or shipped in accordance with the provisions of this chapter. Failure of a shellfish grower to display a certificate of approval, or department-approved equivalent, issued under RCW 69.30.050 to an authorized representative of the department, a fish and wildlife officer, or an ex officio fish and wildlife officer subjects the grower to the penalty provisions of this chapter, as well as seizure and disposition, up to and including disposal, of the shellfish by the representative or officer.

. Failure of a shellfish processor to display a certificate of approval issued under RCW 69.30.060 to an authorized representative of the department, a fish and wildlife officer, or an ex officio fish and wildlife officer subjects the processor to the penalty provisions of this chapter, as well as seizure and disposition, up to and including disposal, of the shellfish by the representative or officer.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1453-S.SL.pdf?cite=2011%20c%20194%20§%208[2011 c 194 § 8]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5961-S.SL.pdf?cite=2001%20c%20253%20§%206[2001 c 253 § 6]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1404-S.SL.pdf?cite=1995%20c%20147%20§%204[1995 c 147 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c51.pdf?cite=1985%20c%2051%20§%204[1985 c 51 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%2074[1979 c 141 § 74]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c144.pdf?cite=1955%20c%20144%20§%2011[1955 c 144 § 11]; ]

== 69.30.120 - Inspection by department—Access to regulated business or entity—Administrative inspection warrant.
The department may enter and inspect any shellfish growing area or establishment for the purposes of determining compliance with this chapter and rules adopted under this chapter. The department may inspect all shellfish, all permits, all certificates of approval and all records.

During such inspections the department shall have free and unimpeded access to all buildings, yards, warehouses, storage and transportation facilities, vehicles, and other places reasonably considered to be or to have been part of the regulated business or entity, to all ledgers, books, accounts, memorandums, or records required to be compiled or maintained under this chapter or under rules adopted pursuant to this chapter, and to any products, components, or other materials reasonably believed to be or to have been used, processed, or produced by or in connection with the regulated business or activity. In connection with such inspections the department may take such samples or specimens as may be reasonably necessary to determine whether there exists a violation of this chapter or rules adopted under this chapter.

Inspection of establishments may be conducted between eight a.m. and five p.m. on any weekday that is not a legal holiday, during any time the regulated business or entity has established as its usual business hours, at any time the regulated business or entity is open for business or is otherwise in operation, and at any other time with the consent of the owner or authorized agent of the regulated business or entity.

The department may apply for an administrative inspection warrant to a court of competent jurisdiction and an administrative inspection warrant may issue where:

. The department has attempted an inspection under this chapter and access to all or part of the regulated business or entity has been actually or constructively denied; or

. There is reasonable cause to believe that a violation of this chapter or of rules adopted under this chapter is occurring or has occurred.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1404-S.SL.pdf?cite=1995%20c%20147%20§%205[1995 c 147 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c51.pdf?cite=1985%20c%2051%20§%205[1985 c 51 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c144.pdf?cite=1955%20c%20144%20§%2012[1955 c 144 § 12]; ]

== 69.30.130 - Water pollution laws and rules applicable.
All existing laws and rules and regulations governing the pollution of waters of the state shall apply in the control of pollution of shellfish growing areas.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c144.pdf?cite=1955%20c%20144%20§%2013[1955 c 144 § 13]; ]

== 69.30.140 - Penalties.
Except as provided in RCW 69.30.085(4), any person convicted of violating any of the provisions of this chapter shall be guilty of a gross misdemeanor. A conviction is an unvacated forfeiture of bail or collateral deposited to secure the defendant's appearance in court, the payment of a fine, a plea of guilty, or a finding of guilt on a violation of this chapter or rules adopted under this chapter, regardless of whether imposition of sentence is deferred or the penalty is suspended, and shall be treated as a conviction for purposes of license revocation and suspension of privileges under *RCW 77.15.700(5).

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1453-S.SL.pdf?cite=2011%20c%20194%20§%209[2011 c 194 § 9]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5961-S.SL.pdf?cite=2001%20c%20253%20§%207[2001 c 253 § 7]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1404-S.SL.pdf?cite=1995%20c%20147%20§%206[1995 c 147 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c51.pdf?cite=1985%20c%2051%20§%206[1985 c 51 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c144.pdf?cite=1955%20c%20144%20§%2014[1955 c 144 § 14]; ]

== 69.30.145 - Civil penalties.
As limited by RCW 69.30.150, the department may impose civil penalties for violations of standards set forth in this chapter or rules adopted under RCW 69.30.030.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c200.pdf?cite=1989%20c%20200%20§%203[1989 c 200 § 3]; ]

== 69.30.150 - Civil penalties—General provisions.
. In addition to any other penalty provided by law, every person who violates standards set forth in this chapter or rules adopted under RCW 69.30.030 is subject to a penalty of not more than five hundred dollars per day for every violation. Every violation is a separate and distinct offense. In case of a continuing violation, every day's continuance is a separate and distinct violation. Every person who, through an act of commission or omission, procures, aids, or abets in the violation is in violation of this section and is subject to the penalty provided in this section.

. The penalty provided for in this section shall be imposed by a notice in writing to the person against whom the civil fine is assessed and shall describe the violation with reasonable particularity. The notice shall be personally served in the manner of service of a summons in a civil action or in a manner which shows proof of receipt. Any penalty imposed by this section shall become due and payable twenty-eight days after receipt of notice unless application for remission or mitigation is made as provided in subsection (3) of this section or unless application for an adjudicative proceeding is filed as provided in subsection (4) of this section.

. Within fourteen days after the notice is received, the person incurring the penalty may apply in writing to the department for the remission or mitigation of the penalty. Upon receipt of the application, the department may remit or mitigate the penalty upon whatever terms the department deems proper, giving consideration to the degree of hazard associated with the violation. The department may only grant a remission or mitigation that it deems to be in the best interests of carrying out the purposes of this chapter. The department may ascertain the facts regarding all such applications in a manner it deems proper. When an application for remission or mitigation is made, any penalty incurred pursuant to this section becomes due and payable twenty-eight days after receipt of the notice setting forth the disposition of the application, unless an application for an adjudicative proceeding to contest the disposition is filed as provided in subsection (4) of this section.

. Within twenty-eight days after notice is received, the person incurring the penalty may file an application for an adjudicative proceeding and may pursue subsequent review as provided in chapter 34.05 RCW and applicable rules of the department or board of health.

. Any penalty imposed by final order following an adjudicative proceeding becomes due and payable upon service of the final order.

. The attorney general may bring an action in the name of the department in the superior court of Thurston county or of any county in which the violator may do business to collect any penalty imposed under this chapter.

. All penalties imposed under this section shall be paid to the state treasury and credited to the general fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c200.pdf?cite=1989%20c%20200%20§%204[1989 c 200 § 4]; ]

