= 69.38 - Poisons—Sales and manufacturing.
:toc:

== 69.38.010 - "Poison" defined.
As used in this chapter "poison" means:

. Arsenic and its preparations;

. Cyanide and its preparations, including hydrocyanic acid;

. Strychnine; and

. Any other substance designated by the pharmacy quality assurance commission which, when introduced into the human body in quantities of sixty grains or less, causes violent sickness or death.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1609.SL.pdf?cite=2013%20c%2019%20§%2052[2013 c 19 § 52]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c34.pdf?cite=1987%20c%2034%20§%201[1987 c 34 § 1]; ]

== 69.38.020 - Exemptions from chapter.
All substances regulated under chapters 15.58, 17.21, 69.04, 69.41, and 69.50 RCW, and chapter 69.45 RCW are exempt from the provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c34.pdf?cite=1987%20c%2034%20§%202[1987 c 34 § 2]; ]

== 69.38.030 - Poison register—Identification of purchaser.
It is unlawful for any person, either on the person's own behalf or while an employee of another, to sell any poison without first recording in ink in a "poison register" kept solely for this purpose the following information:

. The date and hour of the sale;

. The full name and home address of the purchaser;

. The kind and quantity of poison sold; and

. The purpose for which the poison is being purchased.

The purchaser shall present to the seller identification which contains the purchaser's photograph and signature. No sale may be made unless the seller is satisfied that the purchaser's representations are true and that the poison will be used for a lawful purpose. Both the purchaser and the seller shall sign the poison register entry.

If a delivery of a poison will be made outside the confines of the seller's premises, the seller may require the business purchasing the poison to submit a letter of authorization as a substitute for the purchaser's photograph and signature requirements. The letter of authorization shall include the unified business identifier and address of the business, a full description of how the substance will be used, and the signature of the purchaser. Either the seller or the employee of the seller delivering or transferring the poison shall affix his or her signature to the letter as a witness to the signature and identification of the purchaser. The transaction shall be recorded in the poison register as provided in this section. Letters of authorization shall be kept with the poison register and shall be subject to the inspection and preservation requirements contained in RCW 69.38.040.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c197.pdf?cite=1988%20c%20197%20§%201[1988 c 197 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c34.pdf?cite=1987%20c%2034%20§%203[1987 c 34 § 3]; ]

== 69.38.040 - Inspection of poison register—Penalty for failure to maintain register.
Every poison register shall be open for inspection by law enforcement and health officials at all times and shall be preserved for at least two years after the date of the last entry. Any person failing to maintain the poison register as required in this chapter is guilty of a misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c34.pdf?cite=1987%20c%2034%20§%204[1987 c 34 § 4]; ]

== 69.38.050 - False representation—Penalty.
Any person making any false representation to a seller when purchasing a poison is guilty of a gross misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c34.pdf?cite=1987%20c%2034%20§%205[1987 c 34 § 5]; ]

== 69.38.060 - Manufacturers and sellers of poisons—License required—Penalty.
The pharmacy quality assurance commission, after consulting with the department of health, shall require and provide for the annual licensure of every person now or hereafter engaged in manufacturing or selling poisons within this state. Upon a payment of a fee as set by the department, the department shall issue a license in such form as it may prescribe to such manufacturer or seller. Such license shall be displayed in a conspicuous place in such manufacturer's or seller's place of business for which it is issued.

Any person manufacturing or selling poison within this state without a license is guilty of a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1609.SL.pdf?cite=2013%20c%2019%20§%2053[2013 c 19 § 53]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20440[1989 1st ex.s. c 9 § 440]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c34.pdf?cite=1987%20c%2034%20§%206[1987 c 34 § 6]; ]

