= 69.36 - Washington caustic poison act of 1929.
:toc:

== 69.36.010 - Definitions.
In this chapter, unless the context or subject matter otherwise requires:

. The term "dangerous caustic or corrosive substance" means each and all of the acids, alkalis, and substances named below: (a) Hydrochloric acid and any preparation containing free or chemically unneutralized hydrochloric acid (HCl) in a concentration of ten percent or more; (b) sulphuric acid and any preparation containing free or chemically unneutralized sulphuric acid (H2SO4) in concentration of ten percent or more; (c) nitric acid or any preparation containing free or chemically unneutralized nitric acid (HNO3) in a concentration of five percent or more; (d) carbolic acid (C6H5OH), otherwise known as phenol, and any preparation containing carbolic acid in a concentration of five percent or more; (e) oxalic acid and any preparation containing free or chemically unneutralized oxalic acid (H2C2O4) in a concentration of ten percent or more; (f) any salt of oxalic acid and any preparation containing any such salt in a concentration of ten percent or more; (g) acetic acid or any preparation containing free or chemically unneutralized acetic acid (HC2H3O2) in a concentration of twenty percent or more; (h) hypochlorous acid, either free or combined, and any preparation containing the same in a concentration so as to yield ten percent or more by weight of available chlorine, excluding calx chlorinata, bleaching powder, and chloride of lime; (i) potassium hydroxide and any preparation containing free or chemically unneutralized potassium hydroxide (KOH), including caustic potash and Vienna paste, in a concentration of ten percent or more; (j) sodium hydroxide and any preparation containing free or chemically unneutralized sodium hydroxide (NaOH), including caustic soda and lye, in a concentration of ten percent or more; (k) silver nitrate, sometimes known as lunar caustic, and any preparation containing silver nitrate (AgNO3) in a concentration of five percent or more; and (l) ammonia water and any preparation yielding free or chemically uncombined ammonia (NH3), including ammonium hydroxide and "hartshorn", in a concentration of five percent or more.

. The term "misbranded parcel, package, or container" means a retail parcel, package, or container of any dangerous caustic or corrosive substance for household use, not bearing a conspicuous, easily legible label or sticker, containing (a) the name of the article; (b) the name and place of business of the manufacturer, packer, seller, or distributor; (c) the word "POISON," running parallel with the main body of reading matter on said label or sticker, on a clear, plain background of a distinctly contrasting color, in uncondensed gothic capital letters, the letters to be not less than twenty-four point size, unless there is on said label or sticker no other type so large, in which event the type shall be not smaller than the largest type on the label or sticker; and (d) directions for treatment in case of accidental personal injury by the dangerous caustic or corrosive substance; PROVIDED, That such directions need not appear on labels or stickers on parcels, packages, or containers at the time of shipment or of delivery for shipment by manufacturers or wholesalers for other than household use. PROVIDED FURTHER, That this chapter is not to be construed as applying to any substance subject to the chapter, sold at wholesale or retail for use by a retail druggist in filling prescriptions or in dispensing, in pursuance of a prescription by a physician, dentist, or veterinarian; or for use by or under the direction of a physician, dentist, or veterinarian; or for use by a chemist in the practice or teaching of his or her profession; or for any industrial or professional use, or for use in any of the arts and sciences.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20362[2012 c 117 § 362]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c82.pdf?cite=1929%20c%2082%20§%201[1929 c 82 § 1]; RRS § 2508-1; ]

== 69.36.020 - Misbranded sales, etc., prohibited—Exceptions.
No person shall sell, barter, or exchange, or receive, hold, pack, display, or offer for sale, barter, or exchange, in this state any dangerous caustic or corrosive substance in a misbranded parcel, package, or container, said parcel, package, or container being designed for household use; PROVIDED, That household products for cleaning and washing purposes, subject to this chapter and labeled in accordance therewith, may be sold, offered for sale, held for sale, and distributed in this state by any dealer, wholesale or retail; PROVIDED FURTHER, That no person shall be liable to prosecution and conviction under this chapter when he or she establishes a guaranty bearing the signature and address of a vendor residing in the United States from whom he or she purchased the dangerous caustic or corrosive substance, to the effect that such substance is not misbranded within the meaning of this chapter. No person in this state shall give any such guaranty when such dangerous caustic or corrosive substance is in fact misbranded within the meaning of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20363[2012 c 117 § 363]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c82.pdf?cite=1929%20c%2082%20§%202[1929 c 82 § 2]; RRS § 2508-2. FORMER PART OF SECTION: 1929 c 82 § 1 now codified in RCW  69.32.010; ]

== 69.36.030 - Condemnation of misbranded packages.
Any dangerous caustic or corrosive substance in a misbranded parcel, package, or container suitable for household use, that is being sold, bartered, or exchanged, or held, displayed, or offered for sale, barter, or exchange, shall be liable to be proceeded against in any superior court within the jurisdiction of which the same is found and seized for confiscation, and if such substance is condemned as misbranded, by said court, it shall be disposed of by destruction or sale, as the court may direct; and if sold, the proceeds, less the actual costs and charges, shall be paid over to the state treasurer; but such substance shall not be sold contrary to the laws of the state: PROVIDED, HOWEVER, That upon the payment of the costs of such proceedings and the execution and delivery of a good and sufficient bond to the effect that such substance will not be unlawfully sold or otherwise disposed of, the court may by order direct that such substance be delivered to the owner thereof. Such condemnation proceedings shall conform as near as may be to proceedings in the seizure, and condemnation of substances unfit for human consumption.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c82.pdf?cite=1929%20c%2082%20§%203[1929 c 82 § 3]; RRS § 2508-3; ]

== 69.36.040 - Enforcement—Approval of labels.
The director of agriculture shall enforce the provisions of this chapter, and he or she is hereby authorized and empowered to approve and register such brands and labels intended for use under the provisions of this chapter as may be submitted to him or her for that purpose and as may in his or her judgment conform to the requirements of this statute: PROVIDED, HOWEVER, That in any prosecution under this chapter the fact that any brand or label involved in said prosecution has not been submitted to said director for approval, or if submitted, has not been approved by him or her, shall be immaterial.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20364[2012 c 117 § 364]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c82.pdf?cite=1929%20c%2082%20§%205[1929 c 82 § 5]; RRS § 2508-5; ]

== 69.36.050 - Duty to prosecute.
Every prosecuting attorney to whom there is presented, or who in any way procures, satisfactory evidence of any violation of the provisions of this chapter shall cause appropriate proceedings to be commenced and prosecuted in the proper courts, without delay, for the enforcement of the penalties as in such cases herein provided.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c82.pdf?cite=1929%20c%2082%20§%206[1929 c 82 § 6]; RRS § 2508-6; ]

== 69.36.060 - Penalty.
Any person violating the provisions of this chapter shall be guilty of a misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c82.pdf?cite=1929%20c%2082%20§%204[1929 c 82 § 4]; RRS § 2508-4; ]

== 69.36.070 - Short title.
This chapter may be cited as the Washington Caustic Poison Act of 1929.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c82.pdf?cite=1929%20c%2082%20§%207[1929 c 82 § 7]; RRS § 2508-7; ]

