= 69.48 - Drug take-back program.
:toc:

== 69.48.010 - Findings.
. Abuse, fatal overdoses, and poisonings from prescription and over-the-counter medicines used in the home have emerged as an epidemic in recent years. Poisoning is the leading cause of unintentional injury-related death in Washington, and more than ninety percent of poisoning deaths are due to drug overdoses. Poisoning by prescription and over-the-counter medicines is also one of the most common means of suicide and suicide attempts, with poisonings involved in more than twenty-eight thousand suicide attempts between 2004 and 2013.

. Home medicine cabinets are the most common source of prescription drugs that are diverted and misused. Studies find about seventy percent of those who abuse prescription medicines obtain the drugs from family members or friends, usually for free. People who are addicted to heroin often first abused prescription opiate medicines. Unused, unwanted, and expired medicines that accumulate in homes increase risks of drug abuse, overdoses, and preventable poisonings.

. A safe system for the collection and disposal of unused, unwanted, and expired medicines is a key element of a comprehensive strategy to prevent prescription drug abuse, but disposing of medicines by flushing them down the toilet or placing them in the garbage can contaminate groundwater and other bodies of water, contributing to long-term harm to the environment and animal life.

. The legislature therefore finds that it is in the interest of public health to establish a single, uniform, statewide system of regulation for safe and secure collection and disposal of medicines through a uniform drug "take-back" program operated and funded by drug manufacturers.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1047-S.SL.pdf?cite=2018%20c%20196%20§%201[2018 c 196 § 1]; ]

== 69.48.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Administer" means the direct application of a legend drug whether by injection, inhalation, ingestion, or any other means, to the body of the patient or research subject by:

.. A practitioner; or

.. The patient or research subject at the direction of the practitioner.

. "Authorized collector" means any of the following persons or entities that have entered into an agreement with a program operator to collect covered drugs:

.. A person or entity that is registered with the United States drug enforcement administration and that qualifies under federal law to modify its registration to collect controlled substances for the purpose of destruction;

.. A law enforcement agency; or

.. An entity authorized by the department to provide an alternative collection mechanism for certain covered drugs that are not controlled substances, as defined in RCW 69.50.101.

. "Collection site" means the location where an authorized collector operates a secure collection receptacle for collecting covered drugs.

. [Empty]
.. "Covered drug" means a drug from a covered entity that the covered entity no longer wants and that the covered entity has abandoned or discarded or intends to abandon or discard. "Covered drug" includes legend drugs and nonlegend drugs, brand name and generic drugs, drugs for veterinary use for household pets, and drugs in medical devices and combination products.

.. "Covered drug" does not include:

... Vitamins, minerals, or supplements;

... Herbal-based remedies and homeopathic drugs, products, or remedies;

... Controlled substances contained in schedule I of the uniform controlled substances act, chapter 69.50 RCW;

... Cosmetics, shampoos, sunscreens, lip balm, toothpaste, antiperspirants, or other personal care products that are regulated as both cosmetics and nonprescription drugs under the federal food, drug, and cosmetic act, 21 U.S.C. Sec. 301 et seq.;

.. Drugs for which manufacturers provide a pharmaceutical product stewardship or drug take-back program as part of a federal food and drug administration managed risk evaluation and mitigation strategy under 21 U.S.C. Sec. 355-1;

.. Biological drug products, as defined by 21 C.F.R. 600.3 (h) as it exists on June 7, 2018, for which manufacturers provide a pharmaceutical product stewardship or drug take-back program and who provide the department with a report describing the program, including how the drug product is collected and safely disposed and how patients are made aware of the drug take-back program, and who updates the department on changes that substantially alter their drug take-back program;

.. Drugs that are administered in a clinical setting;

.. Emptied injector products or emptied medical devices and their component parts or accessories;

... Exposed needles or sharps, or used drug products that are medical wastes; or

.. Pet pesticide products contained in pet collars, powders, shampoos, topical applications, or other forms.

. "Covered entity" means a state resident or other nonbusiness entity and includes an ultimate user, as defined by regulations adopted by the United States drug enforcement administration. "Covered entity" does not include a business generator of pharmaceutical waste, such as a hospital, clinic, health care provider's office, veterinary clinic, pharmacy, or law enforcement agency.

. "Covered manufacturer" means a person, corporation, or other entity engaged in the manufacture of covered drugs sold in or into Washington state. "Covered manufacturer" does not include:

.. A private label distributor or retail pharmacy that sells a drug under the retail pharmacy's store label if the manufacturer of the drug is identified under RCW 69.48.040;

.. A repackager if the manufacturer of the drug is identified under RCW 69.48.040; or

.. A nonprofit, 501(c)(3) health care corporation that repackages drugs solely for the purpose of supplying a drug to facilities or retail pharmacies operated by the corporation or an affiliate of the corporation if the manufacturer of the drug is identified under RCW 69.48.040.

. "Department" means the department of health.

. (a) "Drug" means:

.. Substances recognized as drugs in the official United States pharmacopoeia, official homeopathic pharmacopoeia of the United States, or official national formulary, or any supplement to any of them;

.. Substances intended for use in the diagnosis, cure, mitigation, treatment, or prevention of disease in human beings or animals;

.. Substances other than food, minerals, or vitamins that are intended to affect the structure or any function of the body of human beings or animals; and

.. Substances intended for use as a component of any article specified in (a), (b), or (c) of this subsection.

. "Drug take-back organization" means an organization designated by a manufacturer or group of manufacturers to act as an agent on behalf of each manufacturer to develop and implement a drug take-back program.

. "Drug take-back program" or "program" means a program implemented by a program operator for the collection, transportation, and disposal of covered drugs.

. "Drug wholesaler" means an entity licensed as a wholesaler under chapter 18.64 RCW.

. "Generic drug" means a drug that is chemically identical or bioequivalent to a brand name drug in dosage form, safety, strength, route of administration, quality, performance characteristics, and intended use. The inactive ingredients in a generic drug need not be identical to the inactive ingredients in the chemically identical or bioequivalent brand name drug.

. "Legend drug" means a drug, including a controlled substance under chapter 69.50 RCW, that is required by any applicable federal or state law or regulation to be dispensed by prescription only or that is restricted to use by practitioners only.

. "Mail-back distribution location" means a facility, such as a town hall or library, that offers prepaid, preaddressed mailing envelopes to covered entities.

. "Mail-back program" means a method of collecting covered drugs from covered entities by using prepaid, preaddressed mailing envelopes.

. "Manufacture" has the same meaning as in RCW 18.64.011.

. "Nonlegend drug" means a drug that may be lawfully sold without a prescription.

. "Pharmacy" means a place licensed as a pharmacy under chapter 18.64 RCW.

. "Private label distributor" means a company that has a valid labeler code under 21 C.F.R. Sec. 207.17 and markets a drug product under its own name, but does not perform any manufacturing.

. "Program operator" means a drug take-back organization, covered manufacturer, or group of covered manufacturers that implements or intends to implement a drug take-back program approved by the department.

. "Repackager" means a person who owns or operates an establishment that repacks and relabels a product or package containing a covered drug for further sale, or for distribution without further transaction.

. "Retail pharmacy" means a place licensed as a pharmacy under chapter 18.64 RCW for the retail sale and dispensing of drugs.

. "Secretary" means the secretary of health.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1047-S.SL.pdf?cite=2018%20c%20196%20§%202[2018 c 196 § 2]; ]

== 69.48.030 - Requirement to participate in a drug take-back program.
A covered manufacturer must establish and implement a drug take-back program that complies with the requirements of this chapter. A manufacturer that becomes a covered manufacturer after June 7, 2018, must, no later than six months after the date on which the manufacturer became a covered manufacturer, participate in an approved drug take-back program or establish and implement a drug take-back program that complies with the requirements of this chapter. A covered manufacturer may establish and implement a drug take-back program independently, as part of a group of covered manufacturers, or through membership in a drug take-back organization.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1047-S.SL.pdf?cite=2018%20c%20196%20§%203[2018 c 196 § 3]; ]

== 69.48.040 - Identification of covered manufacturers.
. No later than ninety days after June 7, 2018, a drug wholesaler that sells a drug in or into Washington must provide a list of drug manufacturers to the department in a form agreed upon with the department. A drug wholesaler must provide an updated list to the department on January 15th of each year.

. No later than ninety days after June 7, 2018, a retail pharmacy, private label distributor, or repackager must provide written notification to the department identifying the drug manufacturer from which the retail pharmacy, private label distributor, or repackager obtains a drug that it sells under its own label.

. A person or entity that receives a letter of inquiry from the department regarding whether or not it is a covered manufacturer under this chapter shall respond in writing no later than sixty days after receipt of the letter. If the person or entity does not believe it is a covered manufacturer for purposes of this chapter, it shall: (a) State the basis for the belief; (b) provide a list of any drugs it sells, distributes, repackages, or otherwise offers for sale within the state; and (c) identify the name and contact information of the manufacturer of the drugs identified under (b) of this subsection.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1047-S.SL.pdf?cite=2018%20c%20196%20§%204[2018 c 196 § 4]; ]

== 69.48.050 - Drug take-back program approval—Program modifications.
. By July 1, 2019, a program operator must submit a proposal for the establishment and implementation of a drug take-back program to the department for approval. The department shall approve a proposed program if the applicant submits a completed application, the proposed program meets the requirements of subsection (2) of this section, and the applicant pays the appropriate fee established by the department under RCW 69.48.120.

. To be approved by the department, a proposed drug take-back program must:

.. Identify and provide contact information for the program operator and each participating covered manufacturer;

.. Identify and provide contact information for the authorized collectors for the proposed program, as well as the reasons for excluding any potential authorized collectors from participation in the program;

.. Provide for a collection system that complies with RCW 69.48.060;

.. Provide for a handling and disposal system that complies with RCW 69.48.080;

.. Identify any transporters and waste disposal facilities that the program will use;

.. Adopt policies and procedures to be followed by persons handling covered drugs collected under the program to ensure safety, security, and compliance with regulations adopted by the United States drug enforcement administration, as well as any applicable laws;

.. Ensure the security of patient information on drug packaging during collection, transportation, recycling, and disposal;

.. Promote the program by providing consumers, pharmacies, and other entities with educational and informational materials as required by RCW 69.48.070;

.. Demonstrate adequate funding for all administrative and operational costs of the drug take-back program, with costs apportioned among participating covered manufacturers;

.. Set long-term and short-term goals with respect to collection amounts and public awareness; and

.. Consider: (i) The use of existing providers of pharmaceutical waste transportation and disposal services; (ii) separation of covered drugs from packaging to reduce transportation and disposal costs; and (iii) recycling of drug packaging.

. [Empty]
.. No later than one hundred twenty days after receipt of a drug take-back program proposal, the department shall either approve or reject the proposal in writing to the applicant. The department may extend the deadline for approval or rejection of a proposal for good cause. If the department rejects the proposal, it shall provide the reason for rejection.

.. No later than ninety days after receipt of a notice of rejection under (a) of this subsection, the applicant shall submit a revised proposal to the department. The department shall either approve or reject the revised proposal in writing to the applicant within ninety days after receipt of the revised proposal, including the reason for rejection, if applicable.

.. If the department rejects a revised proposal, the department may:

... Require the program operator to submit a further revised proposal;

... Develop and impose changes to some or all of the revised proposal to address deficiencies;

... Require the covered manufacturer or covered manufacturers that proposed the rejected revised proposal to participate in a previously approved drug take-back program; or

... Find the covered manufacturer out of compliance with the requirements of this chapter and take enforcement action as provided in RCW 69.48.110.

. The program operator must initiate operation of an approved drug take-back program no later than one hundred eighty days after approval of the proposal by the department.

. [Empty]
.. Proposed changes to an approved drug take-back program that substantially alter program operations must have prior written approval of the department. A program operator must submit to the department such a proposed change in writing at least fifteen days before the change is scheduled to occur. Changes requiring prior approval of the department include changes to participating covered manufacturers, collection methods, achievement of the service convenience goal described in RCW 69.48.060, policies and procedures for handling covered drugs, education and promotion methods, and selection of disposal facilities.

.. For changes to a drug take-back program that do not substantially alter program operations, a program operator must notify the department at least seven days before implementing the change. Changes that do not substantially alter program operations include changes to collection site locations, methods for scheduling and locating periodic collection events, and methods for distributing prepaid, preaddressed mailers.

.. A program operator must notify the department of any changes to the official point of contact for the program no later than fifteen days after the change. A program operator must notify the department of any changes in ownership or contact information for participating covered manufacturers no later than ninety days after such change.

. No later than four years after a drug take-back program initiates operations, and every four years thereafter, the program operator must submit an updated proposal to the department describing any substantive changes to program elements described in subsection (2) of this section. The department shall approve or reject the updated proposal using the process described in subsection (3) of this section.

. The department shall make all proposals submitted under this section available to the public and shall provide an opportunity for written public comment on each proposal.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1047-S.SL.pdf?cite=2018%20c%20196%20§%205[2018 c 196 § 5]; ]

== 69.48.060 - Collection system.
. [Empty]
.. At least one hundred twenty days prior to submitting a proposal under RCW 69.48.050, a program operator must notify potential authorized collectors of the opportunity to serve as an authorized collector for the proposed drug take-back program. A program operator must commence good faith negotiations with a potential authorized collector no later than thirty days after the potential authorized collector expresses interest in participating in a proposed program.

.. A person or entity may serve as an authorized collector for a drug take-back program voluntarily or in exchange for compensation, but nothing in this chapter requires a person or entity to serve as an authorized collector.

.. A drug take-back program must include as an authorized collector any retail pharmacy, hospital or clinic with an on-site pharmacy, or law enforcement agency that offers to participate in the program without compensation and meets the requirements of subsection (2) of this section. Such a pharmacy, hospital, clinic, or law enforcement agency must be included as an authorized collector in the program no later than ninety days after receiving the offer to participate.

.. A drug take-back program may also locate collection sites at:

... A long-term care facility where a pharmacy, or a hospital or clinic with an on-site pharmacy, operates a secure collection receptacle;

... A substance use disorder treatment program, as defined in RCW 71.24.025; or

... Any other authorized collector willing to participate as a collection site and able to meet the requirements of subsection (2) of this section.

. [Empty]
.. A collection site must accept all covered drugs from covered entities during the hours that the authorized collector is normally open for business with the public.

.. A collection site located at a long-term care facility may only accept covered drugs that are in the possession of individuals who reside or have resided at the facility.

.. A collection site must use secure collection receptacles in compliance with state and federal law, including any applicable on-site storage and collection standards adopted by rule pursuant to *chapter 70.95 or 70.105 RCW and United States drug enforcement administration regulations. The program operator must provide a service schedule that meets the needs of each collection site to ensure that each secure collection receptacle is serviced as often as necessary to avoid reaching capacity and that collected covered drugs are transported to final disposal in a timely manner, including a process for additional prompt collection service upon notification from the collection site. Secure collection receptacle signage must prominently display a toll-free telephone number and web site for the program so that members of the public may provide feedback on collection activities.

.. An authorized collector must comply with applicable provisions of *chapters 70.95 and 70.105 RCW, including rules adopted pursuant to those chapters that establish collection and transportation standards, and federal laws and regulations governing the handling of covered drugs, including United States drug enforcement administration regulations.

. [Empty]
.. A drug take-back program's collection system must be safe, secure, and convenient on an ongoing, year-round basis and must provide equitable and reasonably convenient access for residents across the state.

.. In establishing and operating a collection system, a program operator must give preference to locating collection sites at retail pharmacies, hospitals or clinics with on-site pharmacies, and law enforcement agencies.

.. [Empty]
... Each population center must have a minimum of one collection site, plus one additional collection site for every fifty thousand residents of the city or town located within the population center. Collection sites must be geographically distributed to provide reasonably convenient and equitable access to all residents of the population center.

... On islands and in areas outside of population centers, a collection site must be located at the site of each potential authorized collector that is regularly open to the public, unless the program operator demonstrates to the satisfaction of the department that a potential authorized collector is unqualified or unwilling to participate in the drug take-back program, in accordance with the requirements of subsection (1) of this section.

... For purposes of this section, "population center" means a city or town and the unincorporated area within a ten-mile radius from the center of the city or town.

.. A program operator must establish mail-back distribution locations or hold periodic collection events to supplement service to any area of the state that is underserved by collection sites, as determined by the department, in consultation with the local health jurisdiction. The program operator, in consultation with the department, local law enforcement, the local health jurisdiction, and the local community, must determine the number and locations of mail-back distribution locations or the frequency and location of these collections events, to be held at least twice a year, unless otherwise determined through consultation with the local community. The program must arrange any periodic collection events in advance with local law enforcement agencies and conduct periodic collection events in compliance with United States drug enforcement administration regulations and protocols and applicable state laws.

.. Upon request, a drug take-back program must provide a mail-back program free of charge to covered entities and to retail pharmacies that offer to distribute prepaid, preaddressed mailing envelopes for the drug take-back program. A drug take-back program must permit covered entities to request prepaid, preaddressed mailing envelopes through the program's web site, the program's toll-free telephone number, and a request to a pharmacist at a retail pharmacy distributing the program's mailing envelopes.

.. The program operator must provide alternative collection methods for any covered drugs, other than controlled substances, that cannot be accepted or commingled with other covered drugs in secure collection receptacles, through a mail-back program, or at periodic collection events, to the extent permissible under applicable state and federal laws. The department shall review and approve of any alternative collection methods prior to their implementation.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1047-S.SL.pdf?cite=2018%20c%20196%20§%206[2018 c 196 § 6]; ]

== 69.48.070 - Drug take-back program promotion.
. A drug take-back program must develop and provide a system of promotion, education, and public outreach about the safe storage and secure collection of covered drugs. This system may include signage, written materials to be provided at the time of purchase or delivery of covered drugs, and advertising or other promotional materials. At a minimum, each program must:

.. Promote the safe storage of legend drugs and nonlegend drugs by residents before secure disposal through a drug take-back program;

.. Discourage residents from disposing of covered drugs in solid waste collection, sewer, or septic systems;

.. Promote the use of the drug take-back program so that where and how to return covered drugs is widely understood by residents, pharmacists, retail pharmacies, health care facilities and providers, veterinarians, and veterinary hospitals;

.. Establish a toll-free telephone number and web site publicizing collection options and collection sites and discouraging improper disposal practices for covered drugs, such as flushing them or placing them in the garbage;

.. Prepare educational and outreach materials that: Promote safe storage of covered drugs; discourage the disposal of covered drugs in solid waste collection, sewer, or septic systems; and describe how to return covered drugs to the drug take-back program. The materials must use plain language and explanatory images to make collection services and discouraged disposal practices readily understandable to all residents, including residents with limited English proficiency;

.. Disseminate the educational and outreach materials described in (e) of this subsection to pharmacies, health care facilities, and other interested parties for dissemination to covered entities;

.. Work with authorized collectors to develop a readily recognizable, consistent design of collection receptacles, as well as clear, standardized instructions for covered entities on the use of collection receptacles. The department may provide guidance to program operators on the development of the instructions and design; and

.. Annually report on its promotion, outreach, and public education activities in its annual report required by RCW 69.48.100.

. If more than one drug take-back program is approved by the department, the programs must coordinate their promotional activities to ensure that all state residents can easily identify, understand, and access the collection services provided by any drug take-back program. Coordination efforts must include providing residents with a single toll-free telephone number and single web site to access information about collection services for every approved program.

. Pharmacies and other entities that sell medication in the state are encouraged to promote secure disposal of covered drugs through the use of one or more approved drug take-back programs. Upon request, a pharmacy must provide materials explaining the use of approved drug take-back programs to its customers. The program operator must provide pharmacies with these materials upon request and at no cost to the pharmacy.

. The department, the health care authority, the department of social and health services, the department of ecology, and any other state agency that is responsible for health, solid waste management, and wastewater treatment shall, through their standard educational methods, promote safe storage of prescription and nonprescription drugs by covered entities, secure disposal of covered drugs through a drug take-back program, and the toll-free telephone number and web site for approved drug take-back programs. Local health jurisdictions and local government agencies are encouraged to promote approved drug take-back programs.

. The department:

.. Shall conduct a survey of covered entities and a survey of pharmacists, health care providers, and veterinarians who interact with covered entities on the use of medicines after the first full year of operation of the drug take-back program, and again every two years thereafter. Survey questions must: Measure consumer awareness of the drug take-back program; assess the extent to which collection sites and other collection methods are convenient and easy to use; assess knowledge and attitudes about risks of abuse, poisonings, and overdoses from drugs used in the home; and assess covered entities' practices with respect to unused, unwanted, or expired drugs, both currently and prior to implementation of the drug take-back program; and

.. May, upon review of results of public awareness surveys, direct a program operator for an approved drug take-back program to modify the program's promotion and outreach activities to better achieve widespread awareness among Washington state residents and health care professionals about where and how to return covered drugs to the drug take-back program.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1047-S.SL.pdf?cite=2018%20c%20196%20§%207[2018 c 196 § 7]; ]

== 69.48.080 - Disposal and handling of covered drugs.
. Covered drugs collected under a drug take-back program must be disposed of at a permitted hazardous waste disposal facility that meets the requirements of 40 C.F.R. parts 264 and 265, as they exist on June 7, 2018.

. If use of a hazardous waste disposal facility described in subsection (1) of this section is unfeasible based on cost, logistics, or other considerations, the department, in consultation with the department of ecology, may grant approval for a program operator to dispose of some or all collected covered drugs at a permitted large municipal waste combustor facility that meets the requirements of 40 C.F.R. parts 60 and 62, as they exist on June 7, 2018.

. A program operator may petition the department for approval to use final disposal technologies or processes that provide superior environmental and human health protection than that provided by the technologies described in subsections (1) and (2) of this section, or equivalent protection at less cost. In reviewing a petition under this subsection, the department shall take into consideration regulations or guidance issued by the United States environmental protection agency on the disposal of pharmaceutical waste. The department, in consultation with the department of ecology, shall approve a disposal petition under this section if the disposal technology or processes described in the petition provides equivalent or superior protection in each of the following areas:

.. Monitoring of any emissions or waste;

.. Worker health and safety;

.. Air, water, or land emissions contributing to persistent, bioaccumulative, and toxic pollution; and

.. Overall impact to the environment and human health.

. If a drug take-back program encounters a safety or security problem during collection, transportation, or disposal of covered drugs, the program operator must notify the department as soon as practicable after encountering the problem.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1047-S.SL.pdf?cite=2018%20c%20196%20§%208[2018 c 196 § 8]; ]

== 69.48.090 - Program funding.
. A covered manufacturer or group of covered manufacturers must pay all administrative and operational costs associated with establishing and implementing the drug take-back program in which they participate. Such administrative and operational costs include, but are not limited to: Collection and transportation supplies for each collection site; purchase of secure collection receptacles for each collection site; ongoing maintenance or replacement of secure collection receptacles when requested by authorized collectors; prepaid, preaddressed mailers; compensation of authorized collectors, if applicable; operation of periodic collection events, including the cost of law enforcement staff time; transportation of all collected covered drugs to final disposal; environmentally sound disposal of all collected covered drugs in compliance with RCW 69.48.080; and program promotion and outreach.

. A program operator, covered manufacturer, authorized collector, or other person may not charge:

.. A specific point-of-sale fee to consumers to recoup the costs of a drug take-back program; or

.. A specific point-of-collection fee at the time covered drugs are collected from covered entities.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1047-S.SL.pdf?cite=2018%20c%20196%20§%209[2018 c 196 § 9]; ]

== 69.48.100 - Annual program report.
. By July 1st after the first full year of implementation, and each July 1st thereafter, a program operator must submit to the department a report describing implementation of the drug take-back program during the previous calendar year. The report must include:

.. A list of covered manufacturers participating in the drug take-back program;

.. The amount, by weight, of covered drugs collected, including the amount by weight from each collection method used;

.. The following details regarding the program's collection system: A list of collection sites with addresses; the number of mailers provided; locations where mailers were provided, if applicable; dates and locations of collection events held, if applicable; and the transporters and disposal facility or facilities used;

.. Whether any safety or security problems occurred during collection, transportation, or disposal of covered drugs, and if so, completed and anticipated changes to policies, procedures, or tracking mechanisms to address the problem and improve safety and security;

.. A description of the public education, outreach, and evaluation activities implemented;

.. A description of how collected packaging was recycled to the extent feasible;

.. A summary of the program's goals for collection amounts and public awareness, the degree of success in meeting those goals, and if any goals have not been met, what effort will be made to achieve those goals the following year; and

.. The program's annual expenditures, itemized by program category.

. Within thirty days after each annual period of operation of an approved drug take-back program, the program operator shall submit an annual collection amount report to the department that provides the total amount, by weight, of covered drugs collected from each collection site during the prior year.

. The department shall make reports submitted under this section available to the public through the internet.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1047-S.SL.pdf?cite=2018%20c%20196%20§%2010[2018 c 196 § 10]; ]

== 69.48.110 - Enforcement and penalties.
. The department may audit or inspect the activities and records of a drug take-back program to determine compliance with this chapter or investigate a complaint.

. [Empty]
.. The department shall send a written notice to a covered manufacturer that fails to participate in a drug take-back program as required by this chapter. The notice must provide a warning regarding the penalties for violation of this chapter.

.. A covered manufacturer that receives a notice under this subsection (2) may be assessed a penalty if, sixty days after receipt of the notice, the covered manufacturer continues to sell a covered drug in or into the state without participating in a drug take-back program approved under this chapter.

. [Empty]
.. The department may send a program operator a written notice warning of the penalties for noncompliance with this chapter if it determines that the program operator's drug take-back program is in violation of this chapter or does not conform to the proposal approved by the department. The department may assess a penalty on the program operator and participating covered manufacturers if the program does not come into compliance by thirty days after receipt of the notice.

.. The department may immediately suspend operation of a drug take-back program and assess a penalty if it determines that the program is in violation of this chapter and the violation creates a condition that, in the judgment of the department, constitutes an immediate hazard to the public or the environment.

. [Empty]
.. The department shall send a written notice to a drug wholesaler or a retail pharmacy that fails to provide a list of drug manufacturers to the department as required by RCW 69.48.040. The notice must provide a warning regarding the penalties for violation of this chapter.

.. A drug wholesaler or retail pharmacy that receives a notice under this subsection may be assessed a penalty if, sixty days after receipt of the notice, the drug wholesaler or retail pharmacy fails to provide a list of drug manufacturers.

. In enforcing the requirements of this chapter, the department:

.. May require an informal administrative conference;

.. May require a person or entity to engage in or refrain from engaging in certain activities pertaining to this chapter;

.. May, in accordance with RCW 43.70.095, assess a civil fine of up to two thousand dollars. Each day upon which a violation occurs or is permitted to continue constitutes a separate violation. In determining the appropriate amount of the fine, the department shall consider the extent of harm caused by the violation, the nature and persistence of the violation, the frequency of past violations, any action taken to mitigate the violation, and the financial burden to the entity in violation; and

.. May not prohibit a covered manufacturer from selling a drug in or into the state of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1047-S.SL.pdf?cite=2018%20c%20196%20§%2011[2018 c 196 § 11]; ]

== 69.48.120 - Department to set program fee.
. [Empty]
.. By July 1, 2019, the department shall: Determine its costs for the administration, oversight, and enforcement of the requirements of this chapter, including the survey required under RCW 69.48.200; pursuant to RCW 43.70.250, set fees at a level sufficient to recover the costs associated with administration, oversight, and enforcement; and adopt rules establishing requirements for program operator proposals.

.. The department shall not impose any fees in excess of its actual administrative, oversight, and enforcement costs. The fees collected from each program operator in calendar year 2020 and any subsequent year may not exceed ten percent of the program's annual expenditures as reported to the department in the annual report required by RCW 69.48.100 and determined by the department.

.. Adjustments to the department's fees may be made annually and shall not exceed actual administration, oversight, and enforcement costs. Adjustments for inflation may not exceed the percentage change in the consumer price index for all urban consumers in the United States as calculated by the United States department of labor as averaged by city for the twelve-month period ending with June of the previous year.

.. The department shall collect fees from each program operator by October 1, 2019, and annually thereafter.

. All fees collected under this section must be deposited in the secure drug take-back program account established in RCW 69.48.130.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1047-S.SL.pdf?cite=2018%20c%20196%20§%2012[2018 c 196 § 12]; ]

== 69.48.130 - Secure drug take-back program account.
The secure drug take-back program account is created in the state treasury. All receipts received by the department under this chapter must be deposited in the account. Moneys in the account may be spent only after appropriation. Expenditures from the account may be used by the department only for administering and enforcing this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1047-S.SL.pdf?cite=2018%20c%20196%20§%2013[2018 c 196 § 13]; ]

== 69.48.140 - Antitrust immunity.
The activities authorized by this chapter require collaboration among covered manufacturers. These activities will enable safe and secure collection and disposal of covered drugs in Washington state and are therefore in the best interest of the public. The benefits of collaboration, together with active state supervision, outweigh potential adverse impacts. Therefore, the legislature intends to exempt from state antitrust laws, and provide immunity through the state action doctrine from federal antitrust laws, activities that are undertaken, reviewed, and approved by the department pursuant to this chapter that might otherwise be constrained by such laws. The legislature does not intend and does not authorize any person or entity to engage in activities not provided for by this chapter, and the legislature neither exempts nor provides immunity for such activities.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1047-S.SL.pdf?cite=2018%20c%20196%20§%2014[2018 c 196 § 14]; ]

== 69.48.150 - Federal law, effect on this chapter.
This chapter is void if a federal law, or a combination of federal laws, takes effect that establishes a national program for the collection of covered drugs that substantially meets the intent of this chapter, including the creation of a funding mechanism for collection, transportation, and proper disposal of all covered drugs in the United States.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1047-S.SL.pdf?cite=2018%20c%20196%20§%2015[2018 c 196 § 15]; ]

== 69.48.160 - Local ordinances—Grandfathering—Preemption.
. [Empty]
.. For a period of twelve months after a drug take-back program approved under RCW 69.48.050 begins operating, a county may enforce a grandfathered ordinance. During that twelve-month period, if a county determines that a covered manufacturer is in compliance with its grandfathered ordinance, the department shall find the covered manufacturer in compliance with the requirements of this chapter with respect to that county.

.. In any county enforcing a grandfathered ordinance as described in (a) of this subsection, the program operator of an approved drug take-back program must work with the county and the department to incorporate the local program into the approved drug take-back program on or before the end of the twelve-month period.

. After June 7, 2018, a political subdivision may not enact or enforce a local ordinance that requires a retail pharmacy, clinic, hospital, or local law enforcement agency to provide for collection and disposal of covered drugs from covered entities.

. At the end of the twelve-month period provided in subsection (1) of this section, this chapter preempts all existing or future laws enacted by a county, city, town, or other political subdivision of the state regarding a drug take-back program or other program for the collection, transportation, and disposal of covered drugs, or promotion, education, and public outreach relating to such a program.

. For purposes of this section, "grandfathered ordinance" means a pharmaceutical product stewardship or drug take-back ordinance that: (a) Is in effect on June 7, 2018; and (b) the department determines meets or exceeds the requirements of this chapter with respect to safe and secure collection and disposal of unwanted medicines from residents, including the types of drugs covered by the program, the convenience of the collection system for residents, and required promotion of the program.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1047-S.SL.pdf?cite=2018%20c%20196%20§%2016[2018 c 196 § 16]; ]

== 69.48.170 - Public disclosure.
Proprietary information submitted to the department under this chapter is exempt from public disclosure under RCW 42.56.270. The department may use and disclose such information in summary or aggregated form that does not directly or indirectly identify financial, production, or sales data of an individual covered manufacturer or drug take-back organization.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1047-S.SL.pdf?cite=2018%20c%20196%20§%2017[2018 c 196 § 17]; ]

== 69.48.180 - Rule making.
The department shall adopt any rules necessary to implement and enforce this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1047-S.SL.pdf?cite=2018%20c%20196%20§%2018[2018 c 196 § 18]; ]

== 69.48.190 - Report to legislature.
. No later than thirty days after the department first approves a drug take-back program under RCW 69.48.050, the department shall submit an update to the legislature describing rules adopted under this chapter and the approved drug take-back program.

. By November 15th after the first full year of operation of an approved drug take-back program and biennially thereafter, the department shall submit a report to the legislature. The report must:

.. Describe the status of approved drug take-back programs;

.. Evaluate the secure medicine collection and disposal system and the program promotion, education, and public outreach requirements established by this chapter;

.. Evaluate, in conjunction with an academic institution that is not an agency of the state and is qualified to conduct and evaluate research relating to prescription and nonprescription drug use and abuse and environmental impact, to the extent feasible, the impact of approved drug take-back programs on: Awareness and compliance of residents with safe storage of medicines in the home and secure disposal of covered drugs; rates of misuse, abuse, overdoses, and poisonings from prescription and nonprescription drugs; and diversions of covered drugs from sewer, solid waste, and septic systems. To conduct this evaluation, the department and the academic institution may rely on available data sources, including the public awareness surveys required under this chapter, and the prescription drug monitoring program and public health surveys such as the Washington state healthy youth survey. The department and the academic institution may also consult with other state and local agencies and interested stakeholders; and

.. Provide any recommendations for legislation.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1047-S.SL.pdf?cite=2018%20c%20196%20§%2019[2018 c 196 § 19]; ]

== 69.48.200 - Survey. (Expires July 1, 2026.)
. [Empty]
.. The department shall contract with the statewide program of poison and drug information services identified in RCW 18.76.030 to conduct a survey of residents to measure whether the secure medicine collection and disposal system and the program promotion, education, and public outreach requirements established in this chapter have led to statistically significant changes in: (i) Resident attitudes and behavior on safe storage and secure disposal of prescription and nonprescription medications used in the home; and (ii) the rates of abuse or misuse of or accidental exposure to prescription and nonprescription drugs.

.. The survey of residents must include telephone follow-up with users of the program's emergency telephone service. The survey must be conducted before the secure medicine collection and disposal system is implemented and again no earlier than four years after the system is implemented.

. The statewide program of poison and drug information services shall report the survey results to the legislature and the department of health within six months of completion of the survey.

. This section expires July 1, 2026.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1047-S.SL.pdf?cite=2018%20c%20196%20§%2020[2018 c 196 § 20]; ]

