= 69.51A - Medical cannabis.
:toc:

== 69.51A.005 - Purpose and intent.
. The legislature finds that:

.. There is medical evidence that some patients with terminal or debilitating medical conditions may, under their health care professional's care, benefit from the medical use of marijuana. Some of the conditions for which marijuana appears to be beneficial include, but are not limited to:

... Nausea, vomiting, and cachexia associated with cancer, HIV-positive status, AIDS, hepatitis C, anorexia, and their treatments;

... Severe muscle spasms associated with multiple sclerosis, epilepsy, and other seizure and spasticity disorders;

... Acute or chronic glaucoma;

... Crohn's disease; and

.. Some forms of intractable pain.

.. Humanitarian compassion necessitates that the decision to use marijuana by patients with terminal or debilitating medical conditions is a personal, individual decision, based upon their health care professional's professional medical judgment and discretion.

. Therefore, the legislature intends that, so long as such activities are in strict compliance with this chapter:

.. Qualifying patients with terminal or debilitating medical conditions who, in the judgment of their health care professionals, may benefit from the medical use of marijuana, shall not be arrested, prosecuted, or subject to other criminal sanctions or civil consequences under state law based solely on their medical use of marijuana, notwithstanding any other provision of law;

.. Persons who act as designated providers to such patients shall also not be arrested, prosecuted, or subject to other criminal sanctions or civil consequences under state law, notwithstanding any other provision of law, based solely on their assisting with the medical use of marijuana; and

.. Health care professionals shall also not be arrested, prosecuted, or subject to other criminal sanctions or civil consequences under state law for the proper authorization of medical use of marijuana by qualifying patients for whom, in the health care professional's professional judgment, the medical use of marijuana may prove beneficial.

. Nothing in this chapter establishes the medical necessity or medical appropriateness of marijuana for treating terminal or debilitating medical conditions as defined in RCW 69.51A.010.

. Nothing in this chapter diminishes the authority of correctional agencies and departments, including local governments or jails, to establish a procedure for determining when the use of marijuana would impact community safety or the effective supervision of those on active supervision for a criminal conviction, nor does it create the right to any accommodation of any medical use of marijuana in any correctional facility or jail.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5052-S2.SL.pdf?cite=2015%20c%2070%20§%2016[2015 c 70 § 16]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5073-S2.SL.pdf?cite=2011%20c%20181%20§%20102[2011 c 181 § 102]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5798-S.SL.pdf?cite=2010%20c%20284%20§%201[2010 c 284 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6032-S.SL.pdf?cite=2007%20c%20371%20§%202[2007 c 371 § 2]; 1999 c 2 § 2 (Initiative Measure No. 692, approved November 3, 1998); ]

== 69.51A.010 - Definitions. (Effective until July 1, 2022.)
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. [Empty]
.. Until July 1, 2016, "authorization" means:

... A statement signed and dated by a qualifying patient's health care professional written on tamper-resistant paper, which states that, in the health care professional's professional opinion, the patient may benefit from the medical use of marijuana; and

... Proof of identity such as a Washington state driver's license or identicard, as defined in RCW 46.20.035.

.. Beginning July 1, 2016, "authorization" means a form developed by the department that is completed and signed by a qualifying patient's health care professional and printed on tamper-resistant paper.

.. An authorization is not a prescription as defined in RCW 69.50.101.

. "CBD concentration" means the percent of cannabidiol content per dry weight of any part of the plant Cannabis, or per volume or weight of marijuana product.

. "Department" means the department of health.

. "Designated provider" means a person who is twenty-one years of age or older and:

.. [Empty]
... Is the parent or guardian of a qualifying patient who is under the age of eighteen and beginning July 1, 2016, holds a recognition card; or

... Has been designated in writing by a qualifying patient to serve as the designated provider for that patient;

.. [Empty]
... Has an authorization from the qualifying patient's health care professional; or

... Beginning July 1, 2016:

(A) Has been entered into the medical marijuana authorization database as being the designated provider to a qualifying patient; and

(B) Has been provided a recognition card;

.. Is prohibited from consuming marijuana obtained for the personal, medical use of the qualifying patient for whom the individual is acting as designated provider;

.. Provides marijuana to only the qualifying patient that has designated him or her;

.. Is in compliance with the terms and conditions of this chapter; and

.. Is the designated provider to only one patient at any one time.

. "Health care professional," for purposes of this chapter only, means a physician licensed under chapter 18.71 RCW, a physician assistant licensed under chapter 18.71A RCW, an osteopathic physician licensed under chapter 18.57 RCW, an osteopathic physicians' assistant licensed under chapter 18.57A RCW, a naturopath licensed under chapter 18.36A RCW, or an advanced registered nurse practitioner licensed under chapter 18.79 RCW.

. "Housing unit" means a house, an apartment, a mobile home, a group of rooms, or a single room that is occupied as separate living quarters, in which the occupants live and eat separately from any other persons in the building, and which have direct access from the outside of the building or through a common hall.

. "Low THC, high CBD" means products determined by the department to have a low THC, high CBD ratio under RCW 69.50.375. Low THC, high CBD products must be inhalable, ingestible, or absorbable.

. "Marijuana" has the meaning provided in RCW 69.50.101.

. "Marijuana concentrates" has the meaning provided in RCW 69.50.101.

. "Marijuana processor" has the meaning provided in RCW 69.50.101.

. "Marijuana producer" has the meaning provided in RCW 69.50.101.

. "Marijuana retailer" has the meaning provided in RCW 69.50.101.

. "Marijuana retailer with a medical marijuana endorsement" means a marijuana retailer that has been issued a medical marijuana endorsement by the state liquor and cannabis board pursuant to RCW 69.50.375.

. "Marijuana-infused products" has the meaning provided in RCW 69.50.101.

. "Medical marijuana authorization database" means the secure and confidential database established in RCW 69.51A.230.

. "Medical use of marijuana" means the manufacture, production, possession, transportation, delivery, ingestion, application, or administration of marijuana for the exclusive benefit of a qualifying patient in the treatment of his or her terminal or debilitating medical condition.

. "Plant" means a marijuana plant having at least three distinguishable and distinct leaves, each leaf being at least three centimeters in diameter, and a readily observable root formation consisting of at least two separate and distinct roots, each being at least two centimeters in length. Multiple stalks emanating from the same root ball or root system is considered part of the same single plant.

. "Public place" has the meaning provided in RCW 70.160.020.

. "Qualifying patient" means a person who:

.. [Empty]
... Is a patient of a health care professional;

... Has been diagnosed by that health care professional as having a terminal or debilitating medical condition;

... Is a resident of the state of Washington at the time of such diagnosis;

... Has been advised by that health care professional about the risks and benefits of the medical use of marijuana;

.. Has been advised by that health care professional that they may benefit from the medical use of marijuana;

..(A) Has an authorization from his or her health care professional; or

(B) Beginning July 1, 2016, has been entered into the medical marijuana authorization database and has been provided a recognition card; and

.. Is otherwise in compliance with the terms and conditions established in this chapter.

.. "Qualifying patient" does not include a person who is actively being supervised for a criminal conviction by a corrections agency or department that has determined that the terms of this chapter are inconsistent with and contrary to his or her supervision and all related processes and procedures related to that supervision.

. "Recognition card" means a card issued to qualifying patients and designated providers by a marijuana retailer with a medical marijuana endorsement that has entered them into the medical marijuana authorization database.

. "Retail outlet" has the meaning provided in RCW 69.50.101.

. "Secretary" means the secretary of the department of health.

. "Tamper-resistant paper" means paper that meets one or more of the following industry-recognized features:

.. One or more features designed to prevent copying of the paper;

.. One or more features designed to prevent the erasure or modification of information on the paper; or

.. One or more features designed to prevent the use of counterfeit authorization.

. "Terminal or debilitating medical condition" means a condition severe enough to significantly interfere with the patient's activities of daily living and ability to function, which can be objectively assessed and evaluated and limited to the following:

.. Cancer, human immunodeficiency virus (HIV), multiple sclerosis, epilepsy or other seizure disorder, or spasticity disorders;

.. Intractable pain, limited for the purpose of this chapter to mean pain unrelieved by standard medical treatments and medications;

.. Glaucoma, either acute or chronic, limited for the purpose of this chapter to mean increased intraocular pressure unrelieved by standard treatments and medications;

.. Crohn's disease with debilitating symptoms unrelieved by standard treatments or medications;

.. Hepatitis C with debilitating nausea or intractable pain unrelieved by standard treatments or medications;

.. Diseases, including anorexia, which result in nausea, vomiting, wasting, appetite loss, cramping, seizures, muscle spasms, or spasticity, when these symptoms are unrelieved by standard treatments or medications;

.. Posttraumatic stress disorder; or

.. Traumatic brain injury.

. "THC concentration" has the meaning provided in RCW 69.50.101.

. "Useable marijuana" has the meaning provided in RCW 69.50.101.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5052-S2.SL.pdf?cite=2015%20c%2070%20§%2017[2015 c 70 § 17]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5798-S.SL.pdf?cite=2010%20c%20284%20§%202[2010 c 284 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6032-S.SL.pdf?cite=2007%20c%20371%20§%203[2007 c 371 § 3]; 1999 c 2 § 6 (Initiative Measure No. 692, approved November 3, 1998); ]

== 69.51A.030 - Acts not constituting crimes or unprofessional conduct—Health care professionals not subject to penalties or liabilities.
. The following acts do not constitute crimes under state law or unprofessional conduct under chapter 18.130 RCW, and a health care professional may not be arrested, searched, prosecuted, disciplined, or subject to other criminal sanctions or civil consequences or liability under state law, or have real or personal property searched, seized, or forfeited pursuant to state law, notwithstanding any other provision of law as long as the health care professional complies with subsection (2) of this section:

.. Advising a patient about the risks and benefits of medical use of marijuana or that the patient may benefit from the medical use of marijuana; or

.. Providing a patient or designated provider meeting the criteria established under RCW 69.51A.010 with an authorization, based upon the health care professional's assessment of the patient's medical history and current medical condition, if the health care professional has complied with this chapter and he or she determines within a professional standard of care or in the individual health care professional's medical judgment the qualifying patient may benefit from the medical use of marijuana.

. [Empty]
.. A health care professional may provide a qualifying patient or that patient's designated provider with an authorization for the medical use of marijuana in accordance with this section.

.. In order to authorize for the medical use of marijuana under (a) of this subsection, the health care professional must:

... Have a documented relationship with the patient, as a principal care provider or a specialist, relating to the diagnosis and ongoing treatment or monitoring of the patient's terminal or debilitating medical condition;

... Complete an in-person physical examination of the patient or a remote physical examination of the patient if one is determined to be appropriate under (c)(iii) of this subsection;

... Document the terminal or debilitating medical condition of the patient in the patient's medical record and that the patient may benefit from treatment of this condition or its symptoms with medical use of marijuana;

... Inform the patient of other options for treating the terminal or debilitating medical condition and documenting in the patient's medical record that the patient has received this information;

.. Document in the patient's medical record other measures attempted to treat the terminal or debilitating medical condition that do not involve the medical use of marijuana; and

.. Complete an authorization on forms developed by the department, in accordance with subsection (3) of this section.

.. [Empty]
... For a qualifying patient eighteen years of age or older, an authorization expires one year after its issuance. For a qualifying patient less than eighteen years of age, an authorization expires six months after its issuance.

... An authorization may be renewed upon completion of an in-person physical examination or a remote physical examination of the patient if one is determined to be appropriate under (c)(iii) of this subsection and, in compliance with the other requirements of (b) of this subsection.

... Following an in-person physical examination to authorize the use of marijuana for medical purposes, the health care professional may determine and note in the patient's medical record that subsequent physical examinations for the purposes of renewing an authorization may occur through the use of telemedicine technology if the health care professional determines that requiring the qualifying patient to attend a physical examination in person to renew an authorization would likely result in severe hardship to the qualifying patient because of the qualifying patient's physical or emotional condition.

... When renewing a qualifying patient's authorization for the medical use of marijuana on or after July 28, 2019, the health care professional may indicate that the qualifying patient qualifies for a compassionate care renewal of his or her registration in the medical marijuana authorization database and recognition card if the health care professional determines that requiring the qualifying patient to renew a registration in person would likely result in severe hardship to the qualifying patient because of the qualifying patient's physical or emotional condition. A compassionate care renewal of a qualifying patient's registration and recognition card allows the qualifying patient to receive renewals without the need to be physically present at a retailer and without the requirement to have a photograph taken.

.. A health care professional shall not:

... Accept, solicit, or offer any form of pecuniary remuneration from or to a marijuana retailer, marijuana processor, or marijuana producer;

... Offer a discount or any other thing of value to a qualifying patient who is a customer of, or agrees to be a customer of, a particular marijuana retailer;

... Examine or offer to examine a patient for purposes of diagnosing a terminal or debilitating medical condition at a location where marijuana is produced, processed, or sold;

... Have a business or practice which consists primarily of authorizing the medical use of marijuana or authorize the medical use of marijuana at any location other than his or her practice's permanent physical location;

.. Except as provided in RCW 69.51A.280, sell, or provide at no charge, marijuana concentrates, marijuana-infused products, or useable marijuana to a qualifying patient or designated provider; or

.. Hold an economic interest in an enterprise that produces, processes, or sells marijuana if the health care professional authorizes the medical use of marijuana.

. The department shall develop the form for the health care professional to use as an authorization for qualifying patients and designated providers. The form shall include the qualifying patient's or designated provider's name, address, and date of birth; the health care professional's name, address, and license number; the amount of marijuana recommended for the qualifying patient; a telephone number where the authorization can be verified during normal business hours; the dates of issuance and expiration; and a statement that an authorization does not provide protection from arrest unless the qualifying patient or designated provider is also entered in the medical marijuana authorization database and holds a recognition card.

. The appropriate health professions disciplining authority may inspect or request patient records to confirm compliance with this section. The health care professional must provide access to or produce documents, records, or other items that are within his or her possession or control within twenty-one calendar days of service of a request by the health professions disciplining authority. If the twenty-one calendar day limit results in a hardship upon the health care professional, he or she may request, for good cause, an extension not to exceed thirty additional calendar days. Failure to produce the documents, records, or other items shall result in citations and fines issued consistent with RCW 18.130.230. Failure to otherwise comply with the requirements of this section shall be considered unprofessional conduct and subject to sanctions under chapter 18.130 RCW.

. After a health care professional authorizes a qualifying patient for the medical use of marijuana, he or she may discuss with the qualifying patient how to use marijuana and the types of products the qualifying patient should seek from a retail outlet.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1094-S.SL.pdf?cite=2019%20c%20203%20§%201[2019 c 203 § 1]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5052-S2.SL.pdf?cite=2015%20c%2070%20§%2018[2015 c 70 § 18]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5073-S2.SL.pdf?cite=2011%20c%20181%20§%20301[2011 c 181 § 301]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5798-S.SL.pdf?cite=2010%20c%20284%20§%203[2010 c 284 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6032-S.SL.pdf?cite=2007%20c%20371%20§%204[2007 c 371 § 4]; 1999 c 2 § 4 (Initiative Measure No. 692, approved November 3, 1998); ]

== 69.51A.040 - Compliance with chapter—Qualifying patients and designated providers not subject to penalties—Law enforcement not subject to liability.
The medical use of marijuana in accordance with the terms and conditions of this chapter does not constitute a crime and a qualifying patient or designated provider in compliance with the terms and conditions of this chapter may not be arrested, prosecuted, or subject to other criminal sanctions or civil consequences for possession, manufacture, or delivery of, or for possession with intent to manufacture or deliver, marijuana under state law, or have real or personal property seized or forfeited for possession, manufacture, or delivery of, or for possession with intent to manufacture or deliver, marijuana under state law, and investigating law enforcement officers and agencies may not be held civilly liable for failure to seize marijuana in this circumstance, if:

. [Empty]
.. The qualifying patient or designated provider has been entered into the medical marijuana authorization database and holds a valid recognition card and possesses no more than the amount of marijuana concentrates, useable marijuana, plants, or marijuana-infused products authorized under RCW 69.51A.210.

If a person is both a qualifying patient and a designated provider for another qualifying patient, the person may possess no more than twice the amounts described in RCW 69.51A.210 for the qualifying patient and designated provider, whether the plants, marijuana concentrates, useable marijuana, or marijuana-infused products are possessed individually or in combination between the qualifying patient and his or her designated provider;

.. The qualifying patient or designated provider presents his or her recognition card to any law enforcement officer who questions the patient or provider regarding his or her medical use of marijuana;

.. The qualifying patient or designated provider keeps a copy of his or her recognition card and the qualifying patient or designated provider's contact information posted prominently next to any plants, marijuana concentrates, marijuana-infused products, or useable marijuana located at his or her residence;

.. The investigating law enforcement officer does not possess evidence that:

... The designated provider has converted marijuana produced or obtained for the qualifying patient for his or her own personal use or benefit; or

... The qualifying patient sold, donated, or supplied marijuana to another person; and

.. The designated provider has not served as a designated provider to more than one qualifying patient within a fifteen-day period; or

. The qualifying patient or designated provider participates in a cooperative as provided in RCW 69.51A.250.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5052-S2.SL.pdf?cite=2015%20c%2070%20§%2024[2015 c 70 § 24]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5073-S2.SL.pdf?cite=2011%20c%20181%20§%20401[2011 c 181 § 401]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6032-S.SL.pdf?cite=2007%20c%20371%20§%205[2007 c 371 § 5]; 1999 c 2 § 5 (Initiative Measure No. 692, approved November 3, 1998); ]

== 69.51A.043 - Failure to enter into the medical marijuana authorization database—Affirmative defense.
. A qualifying patient or designated provider who has a valid authorization from his or her health care professional, but is not entered in the medical marijuana authorization database and does not have a recognition card may raise the affirmative defense set forth in subsection (2) of this section, if:

.. The qualifying patient or designated provider presents his or her authorization to any law enforcement officer who questions the patient or provider regarding his or her medical use of marijuana;

.. The qualifying patient or designated provider possesses no more marijuana than the limits set forth in RCW 69.51A.210(3);

.. The qualifying patient or designated provider is in compliance with all other terms and conditions of this chapter;

.. The investigating law enforcement officer does not have probable cause to believe that the qualifying patient or designated provider has committed a felony, or is committing a misdemeanor in the officer's presence, that does not relate to the medical use of marijuana; and

.. No outstanding warrant for arrest exists for the qualifying patient or designated provider.

. A qualifying patient or designated provider who is not entered in the medical marijuana authorization database and does not have a recognition card, but who presents his or her authorization to any law enforcement officer who questions the patient or provider regarding his or her medical use of marijuana, may assert an affirmative defense to charges of violations of state law relating to marijuana through proof at trial, by a preponderance of the evidence, that he or she otherwise meets the requirements of RCW 69.51A.040. A qualifying patient or designated provider meeting the conditions of this subsection but possessing more marijuana than the limits set forth in RCW 69.51A.210(3) may, in the investigating law enforcement officer's discretion, be taken into custody and booked into jail in connection with the investigation of the incident.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5052-S2.SL.pdf?cite=2015%20c%2070%20§%2025[2015 c 70 § 25]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5073-S2.SL.pdf?cite=2011%20c%20181%20§%20402[2011 c 181 § 402]; ]

== 69.51A.045 - Possession of plants, marijuana concentrates, useable marijuana, or marijuana-infused products exceeding lawful amount—Affirmative defense.
. A qualifying patient or designated provider in possession of plants, marijuana concentrates, useable marijuana, or marijuana-infused products exceeding the limits set forth in this chapter but otherwise in compliance with all other terms and conditions of this chapter may establish an affirmative defense to charges of violations of state law relating to marijuana through proof at trial, by a preponderance of the evidence, that the qualifying patient's necessary medical use exceeds the amounts set forth in RCW 69.51A.040.

. An investigating law enforcement officer may seize plants, marijuana concentrates, useable marijuana, or marijuana-infused products exceeding the amounts set forth in this chapter. In the case of plants, the qualifying patient or designated provider shall be allowed to select the plants that will remain at the location. The officer and his or her law enforcement agency may not be held civilly liable for failure to seize marijuana in this circumstance.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5052-S2.SL.pdf?cite=2015%20c%2070%20§%2029[2015 c 70 § 29]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5073-S2.SL.pdf?cite=2011%20c%20181%20§%20405[2011 c 181 § 405]; ]

== 69.51A.050 - Medical marijuana, lawful possession—State not liable.
. The lawful possession or manufacture of medical marijuana as authorized by this chapter shall not result in the forfeiture or seizure of any property.

. No person shall be prosecuted for constructive possession, conspiracy, or any other criminal offense solely for being in the presence or vicinity of medical marijuana or its use as authorized by this chapter.

. The state shall not be held liable for any deleterious outcomes from the medical use of marijuana by any qualifying patient.

[ 1999 c 2 § 7 (Initiative Measure No. 692, approved November 3, 1998); ]

== 69.51A.055 - Limitations of chapter—Persons under supervision.
. [Empty]
.. The arrest and prosecution protections established in RCW 69.51A.040 may not be asserted in a supervision revocation or violation hearing by a person who is supervised by a corrections agency or department, including local governments or jails, that has determined that the terms of this section are inconsistent with and contrary to his or her supervision.

.. The affirmative defenses established in RCW 69.51A.043 and 69.51A.045 may not be asserted in a supervision revocation or violation hearing by a person who is supervised by a corrections agency or department, including local governments or jails, that has determined that the terms of this section are inconsistent with and contrary to his or her supervision.

. RCW 69.51A.040 does not apply to a person who is supervised for a criminal conviction by a corrections agency or department, including local governments or jails, that has determined that the terms of this chapter are inconsistent with and contrary to his or her supervision.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5052-S2.SL.pdf?cite=2015%20c%2070%20§%2030[2015 c 70 § 30]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5073-S2.SL.pdf?cite=2011%20c%20181%20§%201105[2011 c 181 § 1105]; ]

== 69.51A.060 - Crimes—Limitations of chapter.
. It shall be a class 3 civil infraction to use or display medical marijuana in a manner or place which is open to the view of the general public.

. Nothing in this chapter establishes a right of care as a covered benefit or requires any state purchased health care as defined in RCW 41.05.011 or other health carrier or health plan as defined in Title 48 RCW to be liable for any claim for reimbursement for the medical use of marijuana. Such entities may enact coverage or noncoverage criteria or related policies for payment or nonpayment of medical marijuana in their sole discretion.

. Nothing in this chapter requires any health care professional to authorize the medical use of marijuana for a patient.

. Nothing in this chapter requires any accommodation of any on-site medical use of marijuana in any place of employment, in any youth center, in any correctional facility, or smoking marijuana in any public place or hotel or motel.

. Nothing in this chapter authorizes the possession or use of marijuana, marijuana concentrates, useable marijuana, or marijuana-infused products on federal property.

. Nothing in this chapter authorizes the use of medical marijuana by any person who is subject to the Washington code of military justice in chapter 38.38 RCW.

. Employers may establish drug-free work policies. Nothing in this chapter requires an accommodation for the medical use of marijuana if an employer has a drug-free workplace.

. No person shall be entitled to claim the protection from arrest and prosecution under RCW 69.51A.040 or the affirmative defense under RCW 69.51A.043 for engaging in the medical use of marijuana in a way that endangers the health or well-being of any person through the use of a motorized vehicle on a street, road, or highway, including violations of RCW 46.61.502 or 46.61.504, or equivalent local ordinances.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1095-S.SL.pdf?cite=2019%20c%20204%20§%203[2019 c 204 § 3]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5052-S2.SL.pdf?cite=2015%20c%2070%20§%2031[2015 c 70 § 31]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5073-S2.SL.pdf?cite=2011%20c%20181%20§%20501[2011 c 181 § 501]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5798-S.SL.pdf?cite=2010%20c%20284%20§%204[2010 c 284 § 4]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6032-S.SL.pdf?cite=2007%20c%20371%20§%206[2007 c 371 § 6]; 1999 c 2 § 8 (Initiative Measure No. 692, approved November 3, 1998); ]

== 69.51A.100 - Qualifying patient's designation of a specific designated provider—Provider's service as designated provider—Termination—Department may adopt rules.
. A qualifying patient may revoke his or her designation of a specific designated provider and designate a different designated provider at any time. A revocation of designation must be in writing, signed and dated, and provided to the designated provider and, if applicable, the medical marijuana authorization database administrator. The protections of this chapter cease to apply to a person who has served as a designated provider to a qualifying patient seventy-two hours after receipt of that patient's revocation of his or her designation.

. A person may stop serving as a designated provider to a given qualifying patient at any time by revoking that designation in writing, signed and dated, and provided to the qualifying patient and, if applicable, the medical marijuana authorization database administrator. However, that person may not begin serving as a designated provider to a different qualifying patient until fifteen days have elapsed from the date the last qualifying patient designated him or her to serve as a [designated] provider.

. The department may adopt rules to implement this section, including a procedure to remove the name of the designated provider from the medical marijuana authorization database upon receipt of a revocation under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5052-S2.SL.pdf?cite=2015%20c%2070%20§%2034[2015 c 70 § 34]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5073-S2.SL.pdf?cite=2011%20c%20181%20§%20404[2011 c 181 § 404]; ]

== 69.51A.110 - Suitability for organ transplant.
A qualifying patient's medical use of cannabis as authorized by a health care professional may not be a sole disqualifying factor in determining the patient's suitability for an organ transplant, unless it is shown that this use poses a significant risk of rejection or organ failure. This section does not preclude a health care professional from requiring that a patient abstain from the medical use of cannabis, for a period of time determined by the health care professional, while waiting for a transplant organ or before the patient undergoes an organ transplant.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5073-S2.SL.pdf?cite=2011%20c%20181%20§%20408[2011 c 181 § 408]; ]

== 69.51A.120 - Parental rights or residential time—Not to be restricted.
A qualifying patient or designated provider may not have his or her parental rights or residential time with a child restricted solely due to his or her medical use of cannabis in compliance with the terms of this chapter absent written findings supported by evidence that such use has resulted in a long-term impairment that interferes with the performance of parenting functions as defined under RCW 26.09.004.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5073-S2.SL.pdf?cite=2011%20c%20181%20§%20409[2011 c 181 § 409]; ]

== 69.51A.130 - State and municipalities—Not subject to liability.
. No civil or criminal liability may be imposed by any court on the state or its officers and employees for actions taken in good faith under this chapter and within the scope of their assigned duties.

. No civil or criminal liability may be imposed by any court on cities, towns, and counties or other municipalities and their officers and employees for actions taken in good faith under this chapter and within the scope of their assigned duties.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5073-S2.SL.pdf?cite=2011%20c%20181%20§%201101[2011 c 181 § 1101]; ]

== 69.51A.210 - Qualifying patients or designated providers—Authorization—Health care professional may include recommendations on amount of marijuana.
As part of authorizing a qualifying patient or designated provider, the health care professional may include recommendations on the amount of marijuana that is likely needed by the qualifying patient for his or her medical needs and in accordance with this section.

. If the health care professional does not include recommendations on the qualifying patient's or designated provider's authorization, the marijuana retailer with a medical marijuana endorsement, when adding the qualifying patient or designated provider to the medical marijuana authorization database, shall enter into the database that the qualifying patient or designated provider may purchase or obtain at a retail outlet holding a medical marijuana endorsement a combination of the following: Forty-eight ounces of marijuana-infused product in solid form; three ounces of useable marijuana; two hundred sixteen ounces of marijuana-infused product in liquid form; or twenty-one grams of marijuana concentrates. The qualifying patient or designated provider may also grow, in his or her domicile, up to six plants for the personal medical use of the qualifying patient and possess up to eight ounces of useable marijuana produced from his or her plants. These amounts shall be specified on the recognition card that is issued to the qualifying patient or designated provider.

. If the health care professional determines that the medical needs of a qualifying patient exceed the amounts provided for in subsection (1) of this section, the health care professional must specify on the authorization that it is recommended that the patient be allowed to grow, in his or her domicile, up to fifteen plants for the personal medical use of the patient. A patient so authorized may possess up to sixteen ounces of useable marijuana in his or her domicile. The number of plants must be entered into the medical marijuana authorization database by the marijuana retailer with a medical marijuana endorsement and specified on the recognition card that is issued to the qualifying patient or designated provider.

. If a qualifying patient or designated provider with an authorization from a health care professional has not been entered into the medical marijuana authorization database, he or she may not receive a recognition card and may only purchase at a retail outlet, whether it holds a medical marijuana endorsement or not, the amounts established in RCW 69.50.360. In addition the qualifying patient or the designated provider may grow, in his or her domicile, up to four plants for the personal medical use of the qualifying patient and possess up to six ounces of useable marijuana in his or her domicile.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5052-S2.SL.pdf?cite=2015%20c%2070%20§%2019[2015 c 70 § 19]; ]

== 69.51A.220 - Health care professionals may authorize medical use of marijuana—Qualifying patients under age eighteen.
. Health care professionals may authorize the medical use of marijuana for qualifying patients who are under the age of eighteen if:

.. The minor's parent or guardian participates in the minor's treatment and agrees to the medical use of marijuana by the minor; and

.. The parent or guardian acts as the designated provider for the minor and has sole control over the minor's marijuana.

. The minor may not grow plants or purchase marijuana-infused products, useable marijuana, or marijuana concentrates from a marijuana retailer with a medical marijuana endorsement.

. Both the minor and the minor's parent or guardian who is acting as the designated provider must be entered in the medical marijuana authorization database and hold a recognition card.

. A health care professional who authorizes the medical use of marijuana by a minor must do so as part of the course of treatment of the minor's terminal or debilitating medical condition. If authorizing a minor for the medical use of marijuana, the health care professional must:

.. Consult with other health care providers involved in the minor's treatment, as medically indicated, before authorization or reauthorization of the medical use of marijuana; and

.. Reexamine the minor at least once every six months or more frequently as medically indicated. The reexamination must:

... Determine that the minor continues to have a terminal or debilitating medical condition and that the condition benefits from the medical use of marijuana; and

... Include a follow-up discussion with the minor's parent or guardian to ensure the parent or guardian continues to participate in the treatment of the minor.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5052-S2.SL.pdf?cite=2015%20c%2070%20§%2020[2015 c 70 § 20]; ]

== 69.51A.225 - Students who qualify for the medical use of marijuana—Consumption of marijuana-infused products on school grounds.
A school district must permit a student who meets the requirements of RCW 69.51A.220 to consume marijuana-infused products on school grounds, aboard a school bus, or while attending a school-sponsored event. The use must be in accordance with school policy relating to medical marijuana use on school grounds, aboard a school bus, or while attending a school-sponsored event, as adopted under RCW 28A.210.325.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1095-S.SL.pdf?cite=2019%20c%20204%20§%202[2019 c 204 § 2]; ]

== 69.51A.230 - Medical marijuana authorization database—Recognition cards.
. The department must contract with an entity to create, administer, and maintain a secure and confidential medical marijuana authorization database that, beginning July 1, 2016, allows:

.. A marijuana retailer with a medical marijuana endorsement to add a qualifying patient or designated provider and include the amount of marijuana concentrates, useable marijuana, marijuana-infused products, or plants for which the qualifying patient is authorized under RCW 69.51A.210;

.. Persons authorized to prescribe or dispense controlled substances to access health care information on their patients for the purpose of providing medical or pharmaceutical care for their patients;

.. A qualifying patient or designated provider to request and receive his or her own health care information or information on any person or entity that has queried their name or information;

.. Appropriate local, state, tribal, and federal law enforcement or prosecutorial officials who are engaged in a bona fide specific investigation of suspected marijuana-related activity that may be illegal under Washington state law to confirm the validity of the recognition card of a qualifying patient or designated provider;

.. A marijuana retailer holding a medical marijuana endorsement to confirm the validity of the recognition card of a qualifying patient or designated provider;

.. The department of revenue to verify tax exemptions under chapters 82.08 and 82.12 RCW;

.. The department and the health care professional's disciplining authorities to monitor authorizations and ensure compliance with this chapter and chapter 18.130 RCW by their licensees; and

.. Authorizations to expire six months or one year after entry into the medical marijuana authorization database, depending on whether the authorization is for a minor or an adult.

. A qualifying patient and his or her designated provider, if any, may be placed in the medical marijuana authorization database at a marijuana retailer with a medical marijuana endorsement. After a qualifying patient or designated provider is placed in the medical marijuana authorization database, he or she must be provided with a recognition card that contains identifiers required in subsection (3) of this section.

. The recognition card requirements must be developed by the department in rule and include:

.. A randomly generated and unique identifying number;

.. For designated providers, the unique identifying number of the qualifying patient whom the provider is assisting;

.. A photograph of the qualifying patient's or designated provider's face taken by an employee of the marijuana retailer with a medical marijuana endorsement at the same time that the qualifying patient or designated provider is being placed in the medical marijuana authorization database in accordance with rules adopted by the department;

.. The amount of marijuana concentrates, useable marijuana, marijuana-infused products, or plants for which the qualifying patient is authorized under RCW 69.51A.210;

.. The effective date and expiration date of the recognition card;

.. The name of the health care professional who authorized the qualifying patient or designated provider; and

.. For the recognition card, additional security features as necessary to ensure its validity.

. [Empty]
.. For qualifying patients who are eighteen years of age or older and their designated providers, recognition cards are valid for one year from the date the health care professional issued the authorization. For qualifying patients who are under the age of eighteen and their designated providers, recognition cards are valid for six months from the date the health care professional issued the authorization. Qualifying patients may not be reentered into the medical marijuana authorization database until they have been reexamined by a health care professional and determined to meet the definition of qualifying patient. After reexamination, a marijuana retailer with a medical marijuana endorsement must reenter the qualifying patient or designated provider into the medical marijuana authorization database and a new recognition card will then be issued in accordance with department rules.

.. Beginning on July 28, 2019, a qualifying patient's registration in the medical marijuana authorization database and his or her recognition card may be renewed by a qualifying patient's designated provider without the physical presence of the qualifying patient at the retailer if the authorization from the health care professional indicates that the qualifying patient qualifies for a compassionate care renewal, as provided in RCW 69.51A.030. A qualifying patient receiving renewals under the compassionate care renewal provisions is exempt from the photograph requirements under subsection (3)(c) of this section.

. If a recognition card is lost or stolen, a marijuana retailer with a medical marijuana endorsement, in conjunction with the database administrator, may issue a new card that will be valid for six months to one year if the patient is reexamined by a health care professional and determined to meet the definition of qualifying patient and depending on whether the patient is under the age of eighteen or eighteen years of age or older as provided in subsection (4) of this section. If a reexamination is not performed, the expiration date of the replacement recognition card must be the same as the lost or stolen recognition card.

. The database administrator must remove qualifying patients and designated providers from the medical marijuana authorization database upon expiration of the recognition card. Qualifying patients and designated providers may request to remove themselves from the medical marijuana authorization database before expiration of a recognition card and health care professionals may request to remove qualifying patients and designated providers from the medical marijuana authorization database if the patient or provider no longer qualifies for the medical use of marijuana. The database administrator must retain database records for at least five calendar years to permit the state liquor and cannabis board and the department of revenue to verify eligibility for tax exemptions.

. During development of the medical marijuana authorization database, the database administrator must consult with the department, stakeholders, and persons with relevant expertise to include, but not be limited to, qualifying patients, designated providers, health care professionals, state and local law enforcement agencies, and the University of Washington computer science and engineering security and privacy research lab or a certified cybersecurity firm, vendor, or service.

. The medical marijuana authorization database must meet the following requirements:

.. Any personally identifiable information included in the database must be nonreversible, pursuant to definitions and standards set forth by the national institute of standards and technology;

.. Any personally identifiable information included in the database must not be susceptible to linkage by use of data external to the database;

.. The database must incorporate current best differential privacy practices, allowing for maximum accuracy of database queries while minimizing the chances of identifying the personally identifiable information included therein; and

.. The database must be upgradable and updated in a timely fashion to keep current with state of the art privacy and security standards and practices.

. [Empty]
.. Personally identifiable information of qualifying patients and designated providers included in the medical marijuana authorization database is confidential and exempt from public disclosure, inspection, or copying under chapter 42.56 RCW.

.. Information contained in the medical marijuana authorization database may be released in aggregate form, with all personally identifiable information redacted, for the purpose of statistical analysis and oversight of agency performance and actions.

.. Information contained in the medical marijuana authorization database shall not be shared with the federal government or its agents unless the particular qualifying patient or designated provider is convicted in state court for violating this chapter or chapter 69.50 RCW.

. The department must charge a one dollar fee for each initial and renewal recognition card issued by a marijuana retailer with a medical marijuana endorsement. The marijuana retailer with a medical marijuana endorsement shall collect the fee from the qualifying patient or designated provider at the time that he or she is entered into the database and issued a recognition card. The department shall establish a schedule for marijuana retailers with a medical marijuana endorsement to remit the fees collected. Fees collected under this subsection shall be deposited into the dedicated marijuana account created under RCW 69.50.530.

. If the database administrator fails to comply with this section, the department may cancel any contracts with the database administrator and contract with another database administrator to continue administration of the database. A database administrator who fails to comply with this section is subject to a fine of up to five thousand dollars in addition to any penalties established in the contract. Fines collected under this section must be deposited into the health professions account created under *RCW 43.70.320.

. The department may adopt rules to implement this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1415-S.SL.pdf?cite=2019%20c%20220%20§%202[2019 c 220 § 2]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1094-S.SL.pdf?cite=2019%20c%20203%20§%202[2019 c 203 § 2]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5052-S2.SL.pdf?cite=2015%20c%2070%20§%2021[2015 c 70 § 21]; ]

== 69.51A.235 - Compassionate care renewals—Rules—Effective date.
The compassionate care renewals permitted in RCW 69.51A.030 and 69.51A.230 take effect November 1, 2019. The department may adopt rules to implement these renewals and to streamline administrative functions. However, the policy established in these sections may not be delayed until the rules are adopted.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1094-S.SL.pdf?cite=2019%20c%20203%20§%203[2019 c 203 § 3]; ]

== 69.51A.240 - Unlawful actions—Criminal penalty.
. It is unlawful for a person to knowingly or intentionally:

.. Access the medical marijuana authorization database for any reason not authorized under RCW 69.51A.230;

.. Disclose any information received from the medical marijuana authorization database in violation of RCW 69.51A.230 including, but not limited to, qualifying patient or designated provider names, addresses, or amount of marijuana for which they are authorized;

.. Produce a recognition card or to tamper with a recognition card for the purpose of having it accepted by a marijuana retailer holding a medical marijuana endorsement in order to purchase marijuana as a qualifying patient or designated provider or to grow marijuana plants in accordance with this chapter;

.. If a person is a designated provider to a qualifying patient, sell, donate, or supply marijuana produced or obtained for the qualifying patient to another person, or use the marijuana produced or obtained for the qualifying patient for the designated provider's own personal use or benefit; or

.. If the person is a qualifying patient, sell, donate, or otherwise supply marijuana produced or obtained by the qualifying patient to another person.

. A person who violates this section is guilty of a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5052-S2.SL.pdf?cite=2015%20c%2070%20§%2023[2015 c 70 § 23]; ]

== 69.51A.250 - Cooperatives—Qualifying patients or designated providers may form—Requirements—Restrictions on locations—State liquor and cannabis board may adopt rules.
. Qualifying patients or designated providers may form a cooperative and share responsibility for acquiring and supplying the resources needed to produce and process marijuana only for the medical use of members of the cooperative. No more than four qualifying patients or designated providers may become members of a cooperative under this section and all members must hold valid recognition cards. All members of the cooperative must be at least twenty-one years old. The designated provider of a qualifying patient who is under twenty-one years old may be a member of a cooperative on the qualifying patient's behalf. All plants grown in the cooperative must be from an immature plant or clone purchased from a licensed marijuana producer as defined in RCW 69.50.101. Cooperatives may also purchase marijuana seeds from a licensed marijuana producer.

. Qualifying patients and designated providers who wish to form a cooperative must register the location with the state liquor and cannabis board and this is the only location where cooperative members may grow or process marijuana. This registration must include the names of all participating members and copies of each participant's recognition card. Only qualifying patients or designated providers registered with the state liquor and cannabis board in association with the location may participate in growing or receive useable marijuana or marijuana-infused products grown at that location.

. No cooperative may be located in any of the following areas:

.. Within one mile of a marijuana retailer;

.. Within the smaller of either:

... One thousand feet of the perimeter of the grounds of any elementary or secondary school, playground, recreation center or facility, child care center, public park, public transit center, library, or any game arcade that admission to which is not restricted to persons aged twenty-one years or older; or

... The area restricted by ordinance, if the cooperative is located in a city, county, or town that has passed an ordinance pursuant to RCW 69.50.331(8); or

.. Where prohibited by a city, town, or county zoning provision.

. The state liquor and cannabis board must deny the registration of any cooperative if the location does not comply with the requirements set forth in subsection (3) of this section.

. If a qualifying patient or designated provider no longer participates in growing at the location, he or she must notify the state liquor and cannabis board within fifteen days of the date the qualifying patient or designated provider ceases participation. The state liquor and cannabis board must remove his or her name from connection to the cooperative. Additional qualifying patients or designated providers may not join the cooperative until sixty days have passed since the date on which the last qualifying patient or designated provider notifies the state liquor and cannabis board that he or she no longer participates in that cooperative.

. Qualifying patients or designated providers who participate in a cooperative under this section:

.. May grow up to the total amount of plants for which each participating member is authorized on their recognition cards, up to a maximum of sixty plants. At the location, the qualifying patients or designated providers may possess the amount of useable marijuana that can be produced with the number of plants permitted under this subsection, but no more than seventy-two ounces;

.. May only participate in one cooperative;

.. May only grow plants in the cooperative and if he or she grows plants in the cooperative may not grow plants elsewhere;

.. Must provide assistance in growing plants. A monetary contribution or donation is not to be considered assistance under this section. Participants must provide nonmonetary resources and labor in order to participate; and

.. May not sell, donate, or otherwise provide marijuana, marijuana concentrates, useable marijuana, or marijuana-infused products to a person who is not participating under this section.

. The location of the cooperative must be the domicile of one of the participants. Only one cooperative may be located per property tax parcel. A copy of each participant's recognition card must be kept at the location at all times.

. The state liquor and cannabis board may adopt rules to implement this section including:

.. Any security requirements necessary to ensure the safety of the cooperative and to reduce the risk of diversion from the cooperative;

.. A seed to sale traceability model that is similar to the seed to sale traceability model used by licensees that will allow the state liquor and cannabis board to track all marijuana grown in a cooperative.

. The state liquor and cannabis board or law enforcement may inspect a cooperative registered under this section to ensure members are in compliance with this section. The state liquor and cannabis board must adopt rules on reasonable inspection hours and reasons for inspections.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5131-S.SL.pdf?cite=2017%20c%20317%20§%208[2017 c 317 § 8]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2520.SL.pdf?cite=2016%20c%20170%20§%202[2016 c 170 § 2]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2136-S2.SL.pdf?cite=2015%202nd%20sp.s.%20c%204%20§%201001[2015 2nd sp.s. c 4 § 1001]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5052-S2.SL.pdf?cite=2015%20c%2070%20§%2026[2015 c 70 § 26]; ]

== 69.51A.260 - Housing unit—No more than fifteen plants may be grown or located—Exception—Civil penalties.
. Notwithstanding any other provision of this chapter and even if multiple qualifying patients or designated providers reside in the same housing unit, no more than fifteen plants may be grown or located in any one housing unit other than a cooperative established pursuant to RCW 69.51A.250.

. Neither the production nor processing of marijuana or marijuana-infused products pursuant to this section nor the storage or growing of plants may occur if any portion of such activity can be readily seen by normal unaided vision or readily smelled from a public place or the private property of another housing unit.

. Cities, towns, counties, and other municipalities may create and enforce civil penalties, including abatement procedures, for the growing or processing of marijuana and for keeping marijuana plants beyond or otherwise not in compliance with this section.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5052-S2.SL.pdf?cite=2015%20c%2070%20§%2027[2015 c 70 § 27]; ]

== 69.51A.270 - Extracting or separating marijuana resin, producing or processing any form of marijuana concentrates or marijuana-infused products—State liquor and cannabis board to adopt rules.
. Once the state liquor and cannabis board adopts rules under subsection (2) of this section, qualifying patients or designated providers may only extract or separate the resin from marijuana or produce or process any form of marijuana concentrates or marijuana-infused products in accordance with those standards.

. The state liquor and cannabis board must adopt rules permitting qualifying patients and designated providers to extract or separate the resin from marijuana using noncombustable methods. The rules must provide the noncombustible methods permitted and any restrictions on this practice.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5052-S2.SL.pdf?cite=2015%20c%2070%20§%2028[2015 c 70 § 28]; ]

== 69.51A.280 - Topical, ingestible products—THC concentration.
Neither this chapter nor chapter 69.50 RCW prohibits a health care professional from selling or donating topical, noningestible products that have a THC concentration of less than .3 percent to qualifying patients.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5052-S2.SL.pdf?cite=2015%20c%2070%20§%2035[2015 c 70 § 35]; ]

== 69.51A.290 - Medical marijuana consultant certificate.
A medical marijuana consultant certificate is hereby established.

. In addition to any other authority provided by law, the secretary of the department may:

.. Adopt rules, in accordance with chapter 34.05 RCW, necessary to implement this chapter;

.. Establish forms and procedures necessary to administer this chapter;

.. Approve training or education programs that meet the requirements of this section and any rules adopted to implement it;

.. Receive criminal history record information that includes nonconviction information data for any purpose associated with initial certification or renewal of certification. The secretary shall require each applicant for initial certification to obtain a state or federal criminal history record information background check through the state patrol or the state patrol and the identification division of the federal bureau of investigation prior to the issuance of any certificate. The secretary shall specify those situations where a state background check is inadequate and an applicant must obtain an electronic fingerprint-based national background check through the state patrol and federal bureau of investigation. Situations where a background check is inadequate may include instances where an applicant has recently lived out-of-state or where the applicant has a criminal record in Washington;

.. Establish administrative procedures, administrative requirements, and fees in accordance with RCW 43.70.110 and 43.70.250; and

.. Maintain the official department record of all applicants and certificate holders.

. A training or education program approved by the secretary must include the following topics:

.. The medical conditions that constitute terminal or debilitating conditions, and the symptoms of those conditions;

.. Short and long-term effects of cannabinoids;

.. Products that may benefit qualifying patients based on the patient's terminal or debilitating medical condition;

.. Risks and benefits of various routes of administration;

.. Safe handling and storage of useable marijuana, marijuana-infused products, and marijuana concentrates, including strategies to reduce access by minors;

.. Demonstrated knowledge of this chapter and the rules adopted to implement it; and

.. Other subjects deemed necessary and appropriate by the secretary to ensure medical marijuana consultant certificate holders are able to provide evidence-based and medically accurate advice on the medical use of marijuana.

. Medical marijuana consultant certificates are subject to annual renewals and continuing education requirements established by the secretary.

. The secretary shall have the power to refuse, suspend, or revoke the certificate of any medical marijuana consultant upon proof that:

.. The certificate was procured through fraud, misrepresentation, or deceit;

.. The certificate holder has committed acts in violation of subsection (6) of this section; or

.. The certificate holder has violated or has permitted any employee or volunteer to violate any of the laws of this state relating to drugs or controlled substances or has been convicted of a felony.

In any case of the refusal, suspension, or revocation of a certificate by the secretary under the provisions of this chapter, appeal may be taken in accordance with chapter 34.05 RCW, the administrative procedure act.

. A medical marijuana consultant may provide the following services when acting as an owner, employee, or volunteer of a retail outlet licensed under RCW 69.50.354 and holding a medical marijuana endorsement under RCW 69.50.375:

.. Assisting a customer with the selection of products sold at the retail outlet that may benefit the qualifying patient's terminal or debilitating medical condition;

.. Describing the risks and benefits of products sold at the retail outlet;

.. Describing the risks and benefits of methods of administration of products sold at the retail outlet;

.. Advising a customer about the safe handling and storage of useable marijuana, marijuana-infused products, and marijuana concentrates, including strategies to reduce access by minors; and

.. Providing instruction and demonstrations to customers about proper use and application of useable marijuana, marijuana-infused products, and marijuana concentrates.

. Nothing in this section authorizes a medical marijuana consultant to:

.. Offer or undertake to diagnose or cure any human disease, ailment, injury, infirmity, deformity, pain, or other condition, physical or mental, real or imaginary, by use of marijuana or any other means or instrumentality; or

.. Recommend or suggest modification or elimination of any course of treatment that does not involve the medical use of marijuana.

. Nothing in this section requires an owner, employee, or volunteer of a retail outlet licensed under RCW 69.50.354 and holding a medical marijuana endorsement under RCW 69.50.375 to obtain a medical marijuana consultant certification.

. Nothing in this section applies to the practice of a health care profession by individuals who are licensed, certified, or registered in a profession listed in RCW 18.130.040(2) and who are performing services within their authorized scope of practice.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5052-S2.SL.pdf?cite=2015%20c%2070%20§%2037[2015 c 70 § 37]; ]

== 69.51A.300 - Continuing education programs for health care providers.
The board of naturopathy, the board of osteopathic medicine and surgery, the Washington medical commission, and the nursing care quality assurance commission shall develop and approve continuing education programs related to the use of marijuana for medical purposes for the health care providers that they each regulate that are based upon practice guidelines that have been adopted by each entity.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5764.SL.pdf?cite=2019%20c%2055%20§%2013[2019 c 55 § 13]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5052-S2.SL.pdf?cite=2015%20c%2070%20§%2038[2015 c 70 § 38]; ]

== 69.51A.310 - Immature plants and clones, marijuana seeds—Qualifying patients and designated providers may purchase.
Qualifying patients and designated providers, who hold a recognition card and have been entered into the medical marijuana authorization database, may purchase immature plants or clones from a licensed marijuana producer as defined in RCW 69.50.101. Qualifying patients and designated providers may also purchase marijuana seeds from a licensed marijuana producer.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5131-S.SL.pdf?cite=2017%20c%20317%20§%2011[2017 c 317 § 11]; ]

== 69.51A.900 - Short title—1999 c 2.
This chapter may be known and cited as the Washington state medical use of cannabis act.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5073-S2.SL.pdf?cite=2011%20c%20181%20§%201106[2011 c 181 § 1106]; 1999 c 2 § 1 (Initiative Measure No. 692, approved November 3, 1998); ]

