= 69.51 - Controlled substances therapeutic research act.
:toc:

== 69.51.010 - Short title.
This chapter may be cited as the Controlled Substances Therapeutic Research Act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c136.pdf?cite=1979%20c%20136%20§%201[1979 c 136 § 1]; ]

== 69.51.020 - Legislative purpose.
The legislature finds that recent research has shown that the use of marijuana may alleviate the nausea and ill effects of cancer chemotherapy and radiology, and, additionally, may alleviate the ill effects of glaucoma. The legislature further finds that there is a need for further research and experimentation regarding the use of marijuana under strictly controlled circumstances. It is for this purpose that the Controlled Substances Therapeutic Research Act is hereby enacted.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c136.pdf?cite=1979%20c%20136%20§%202[1979 c 136 § 2]; ]

== 69.51.030 - Definitions.
As used in this chapter:

. "Commission" means the pharmacy quality assurance commission;

. "Department" means the department of health;

. "Marijuana" means all parts of the plant of the genus Cannabis L., whether growing or not, the seeds thereof, the resin extracted from any part of the plant, and every compound, manufacture, salt, derivative, mixture, or preparation of the plant, its seeds, or resin; and

. "Practitioner" means a physician licensed pursuant to chapter 18.71 or 18.57 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1609.SL.pdf?cite=2013%20c%2019%20§%20113[2013 c 19 § 113]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20438[1989 1st ex.s. c 9 § 438]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c136.pdf?cite=1979%20c%20136%20§%203[1979 c 136 § 3]; ]

== 69.51.040 - Controlled substances therapeutic research program.
. There is established in the commission the controlled substances therapeutic research program. The program shall be administered by the department. The commission shall promulgate rules necessary for the proper administration of the Controlled Substances Therapeutic Research Act. In such promulgation, the commission shall take into consideration those pertinent rules promulgated by the United States drug enforcement agency, the food and drug administration, and the national institute on drug abuse.

. Except as provided in RCW 69.51.050(4), the controlled substances therapeutic research program shall be limited to cancer chemotherapy and radiology patients and glaucoma patients, who are certified to the patient qualification review committee by a practitioner as being involved in a life-threatening or sense-threatening situation. No patient may be admitted to the controlled substances therapeutic research program without full disclosure by the practitioner of the experimental nature of this program and of the possible risks and side effects of the proposed treatment in accordance with the informed consent provisions of chapter 7.70 RCW.

. The commission shall provide by rule for a program of registration with the department of bona fide controlled substance therapeutic research projects.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1609.SL.pdf?cite=2013%20c%2019%20§%20114[2013 c 19 § 114]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20439[1989 1st ex.s. c 9 § 439]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c136.pdf?cite=1979%20c%20136%20§%204[1979 c 136 § 4]; ]

== 69.51.050 - Patient qualification review committee.
. The commission shall appoint a patient qualification review committee to serve at its pleasure. The patient qualification review committee shall be comprised of:

.. A physician licensed to practice medicine in Washington state and specializing in the practice of ophthalmology;

.. A physician licensed to practice medicine in Washington state and specializing in the subspecialty of medical oncology;

.. A physician licensed to practice medicine in Washington state and specializing in the practice of psychiatry; and

.. A physician licensed to practice medicine in Washington state and specializing in the practice of radiology.

Members of the committee shall be compensated at the rate of fifty dollars per day for each day spent in the performance of their official duties, and shall receive reimbursement for their travel expenses as provided in RCW 43.03.050 and 43.03.060.

. The patient qualification review committee shall review all applicants for the controlled substance therapeutic research program and their licensed practitioners and certify their participation in the program.

. The patient qualification review committee and the commission shall insure that the privacy of individuals who participate in the controlled substance therapeutic research program is protected by withholding from all persons not connected with the conduct of the research the names and other identifying characteristics of such individuals. Persons authorized to engage in research under the controlled substance therapeutic research program may not be compelled in any civil, criminal, administrative, legislative, or other proceeding to identify the individuals who are the subjects of research for which the authorization was granted, except to the extent necessary to permit the commission to determine whether the research is being conducted in accordance with the authorization.

. The patient qualification review committee may include other disease groups for participation in the controlled substances therapeutic research program after pertinent medical data have been presented by a practitioner to both the committee and the commission, and after approval for such participation has been granted pursuant to pertinent rules promulgated by the United States drug enforcement agency, the food and drug administration, and the national institute on drug abuse.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1609.SL.pdf?cite=2013%20c%2019%20§%20115[2013 c 19 § 115]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c136.pdf?cite=1979%20c%20136%20§%205[1979 c 136 § 5]; ]

== 69.51.060 - Sources and distribution of marijuana.
. The commission shall obtain marijuana through whatever means it deems most appropriate and consistent with regulations promulgated by the United States food and drug administration, the drug enforcement agency, and the national institute on drug abuse, and pursuant to the provisions of this chapter.

. The commission may use marijuana which has been confiscated by local or state law enforcement agencies and has been determined to be free from contamination.

. The commission shall distribute the analyzed marijuana to approved practitioners and/or institutions in accordance with rules promulgated by the commission.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1609.SL.pdf?cite=2013%20c%2019%20§%20116[2013 c 19 § 116]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c136.pdf?cite=1979%20c%20136%20§%206[1979 c 136 § 6]; ]

== 69.51.080 - Cannabis and related products considered Schedule II substances.
. The enumeration of tetrahydrocannabinols, or a chemical derivative of tetrahydrocannabinols in RCW 69.50.204 as a Schedule I controlled substance does not apply to the use of cannabis, tetrahydrocannabinols, or a chemical derivative of tetrahydrocannabinols by certified patients pursuant to the provisions of this chapter.

. Cannabis, tetrahydrocannabinols, or a chemical derivative of tetrahydrocannabinols shall be considered Schedule II substances as enumerated in RCW 69.50.206 only for the purposes enumerated in this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c136.pdf?cite=1979%20c%20136%20§%208[1979 c 136 § 8]; ]

