= 69.55 - Ammonia.
:toc:

== 69.55.010 - Theft of ammonia.
. A person who, with intent to deprive the owner or owner's agent, wrongfully obtains pressurized ammonia gas or pressurized ammonia gas solution, is guilty of theft of ammonia.

. Theft of ammonia is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6232.SL.pdf?cite=2002%20c%20133%20§%201[2002 c 133 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6255-S2.SL.pdf?cite=2000%20c%20225%20§%201[2000 c 225 § 1]; ]

== 69.55.020 - Unlawful storage of ammonia.
A person is guilty of the crime of unlawful storage of ammonia if the person possesses, transports, or delivers pressurized ammonia gas or pressurized ammonia gas solution in a container that (1) is not approved by the United States department of transportation to hold ammonia, or (2) was not constructed to meet state and federal industrial health and safety standards for holding ammonia. Violation of this section is a class C felony.

This section does not apply to public employees or private contractors authorized to clean up and dispose of hazardous waste or toxic substances under chapter 70A.300 or 70A.305 RCW or to solid waste haulers and their employees who unknowingly possess, transport, or deliver pressurized ammonia gas or pressurized ammonia gas solution during the course of the performance of their duties.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1192.SL.pdf?cite=2021%20c%2065%20§%2066[2021 c 65 § 66]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6232.SL.pdf?cite=2002%20c%20133%20§%202[2002 c 133 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6255-S2.SL.pdf?cite=2000%20c%20225%20§%202[2000 c 225 § 2]; ]

== 69.55.030 - Damages—Liability.
Any damages arising out of the unlawful possession of, storage of, or tampering with pressurized ammonia gas or pressurized ammonia gas solution, or pressurized ammonia gas equipment or pressurized ammonia gas solution equipment, shall be the sole responsibility of the unlawful possessor, storer, or tamperer. In no case shall liability for damages arising out of the unlawful possession of, storage of, or tampering with pressurized ammonia gas or pressurized ammonia gas solution, or pressurized ammonia gas equipment or pressurized ammonia gas solution equipment, extend to the lawful owner, installer, maintainer, designer, manufacturer, possessor, or seller of the pressurized ammonia gas or pressurized ammonia gas solution, or pressurized ammonia gas equipment or pressurized ammonia gas solution equipment, unless such damages arise out of the owner, installer, maintainer, designer, manufacturer, possessor, or seller's acts or omissions that constitute negligent misconduct to abide by the laws regarding pressurized ammonia gas or pressurized ammonia gas solution possession and storage.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6232.SL.pdf?cite=2002%20c%20133%20§%203[2002 c 133 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6255-S2.SL.pdf?cite=2000%20c%20225%20§%203[2000 c 225 § 3]; ]

