= 69.75 - Dextromethorphan.
:toc:

== 69.75.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Common carrier" means any person who holds himself or herself out to the general public as a provider for hire of the transportation by water, land, or air of merchandise, whether or not the person actually operates the vessel, vehicle, or aircraft by which the transportation is provided, between a port or place and a port or place in the United States.

. "Finished drug product" means a drug legally marketed under the federal food, drug, and cosmetic act, 21 U.S.C. 321 et seq., that is in finished dosage form.

. "Proof of age" means any document issued by a governmental agency that contains a description or photograph of the person and gives the person's date of birth, including a passport, military identification card, or driver's license.

. "Unfinished dextromethorphan" means dextromethorphan in any form, compound, mixture, or preparation that is not a drug in finished dosage form.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2163-S2.SL.pdf?cite=2014%20c%2064%20§%201[2014 c 64 § 1]; ]

== 69.75.020 - Retail sales—Proof of age from purchaser—Unlawful acts, exceptions—Penalties.
. A person making a retail sale of a finished drug product containing any quantity of dextromethorphan must require and obtain proof of age from the purchaser before completing the sale, unless from the purchaser's outward appearance the person making the sale would reasonably presume the purchaser to be twenty-five years of age or older.

. It is unlawful for any:

.. Commercial entity to knowingly or willfully sell or trade a finished drug product containing any quantity of dextromethorphan to a person less than eighteen years of age; or

.. Person who is less than eighteen years of age to purchase a finished drug product containing any quantity of dextromethorphan.

. Subsection (2)(a) and (b) of this section do [does] not apply if an individual under eighteen years of age:

.. Supplies proof at the time of sale that such individual is actively enrolled in the military and presents a valid military identification card; or

.. Supplies proof of emancipation.

. [Empty]
.. Any manufacturer, distributor, or retailer whose employee or representative, during the course of the employee's or representative's employment or association with that manufacturer, distributor, or retailer sells or trades dextromethorphan in violation of subsection (2)(a) of this section must be given a written warning by a law enforcement agency for the first offense. For any subsequent offense, the manufacturer, distributor, or retailer is guilty of a class 1 civil infraction as provided in RCW 7.80.120, except for any manufacturer, distributor, or retailer who demonstrates a good faith effort to comply with the requirements of this chapter.

.. Any employee or representative of a manufacturer, distributor, or retailer who, during the course of the employee's or representative's employment or association with that manufacturer, distributor, or retailer sells or trades dextromethorphan in violation of subsection (2)(a) of this section must be given a written warning by a law enforcement agency for the first offense. For any subsequent offense, the employee or representative is guilty of a class 1 civil infraction as provided in RCW 7.80.120.

.. Any person who purchases dextromethorphan in violation of subsection (2)(b) of this section must be given a written warning by a law enforcement agency for the first offense. For any subsequent offense, the person is guilty of a class 1 civil infraction as provided in RCW 7.80.120.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2163-S2.SL.pdf?cite=2014%20c%2064%20§%202[2014 c 64 § 2]; ]

== 69.75.030 - List of products containing dextromethorphan, trade association representing manufacturers to supply.
The trade association representing manufacturers of dextromethorphan shall supply to the pharmacy quality assurance commission and requesting licensed retailers an initial list of products containing dextromethorphan that its members market. This list shall be updated on an annual basis. The trade association representing manufacturers of dextromethorphan shall make other reasonable efforts to communicate the requirements of chapter 64, Laws of 2014.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2163-S2.SL.pdf?cite=2014%20c%2064%20§%203[2014 c 64 § 3]; ]

== 69.75.040 - Construction of chapter.
. Nothing in this chapter is construed to impose any compliance requirement on a retail entity other than manually obtaining and verifying proof of age as a condition of sale, including placement of products in a specific place within a store, other restrictions on consumers' direct access to finished drug products, or the maintenance of transaction records.

. The provisions of this chapter do not apply to medication containing dextromethorphan that is sold pursuant to a valid prescription.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2163-S2.SL.pdf?cite=2014%20c%2064%20§%204[2014 c 64 § 4]; ]

== 69.75.050 - Preemption.
This chapter preempts any ordinance regulating the sale, distribution, receipt, or possession of dextromethorphan enacted by a county, city, town, or other political subdivision of this state, and dextromethorphan is not subject to further regulation by such subdivisions.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2163-S2.SL.pdf?cite=2014%20c%2064%20§%205[2014 c 64 § 5]; ]

== 69.75.900 - Effective date—2014 c 64.
This act takes effect July 1, 2015.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2163-S2.SL.pdf?cite=2014%20c%2064%20§%207[2014 c 64 § 7]; ]

