= 69.70 - Access to prescription drugs.
:toc:

== 69.70.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Department" means the department of health.

. "Drug manufacturer" means a facility licensed by the pharmacy quality assurance commission under chapter 18.64 RCW that engages in the manufacture of drugs or devices.

. "Drug wholesaler" means a facility licensed by the pharmacy quality assurance commission under chapter 18.64 RCW that buys drugs or devices for resale and distribution to corporations, individuals, or entities other than consumers.

. "Medical facility" means a hospital, pharmacy, nursing home, boarding home, adult family home, or medical clinic where the prescription drugs are under the control of a practitioner.

. "Person" means an individual, corporation, business trust, estate, trust, partnership, association, joint venture, government, governmental subdivision or agency, or any other legal or commercial entity.

. "Pharmacist" means a person licensed by the pharmacy quality assurance commission under chapter 18.64 RCW to practice pharmacy.

. "Pharmacy" means a facility licensed by the pharmacy quality assurance commission under chapter 18.64 RCW in which the practice of pharmacy is conducted.

. "Practitioner" has the same meaning as in RCW 69.41.010.

. "Prescribing practitioner" means a person authorized to issue orders or prescriptions for legend drugs as listed in RCW 69.41.030.

. "Prescription drugs" has the same meaning as "legend drugs" as defined in RCW 69.41.010. The term includes cancer drugs and antirejection drugs. The term does not include controlled substances.

. "Supplies" means the supplies necessary to administer prescription drugs that are donated under the prescription drug redistribution program.

. "Time temperature indicator" means a device or smart label that shows the accumulated time-temperature history of a product by providing a nonreversible, accurate record of temperature exposure through the entire supply chain.

. "Uninsured" means a person who:

.. Does not have private or public health insurance; or

.. Has health insurance, but the health insurance does not provide coverage for a particular drug that has been prescribed to the person.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2458-S.SL.pdf?cite=2016%20c%2043%20§%201[2016 c 43 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5148-S.SL.pdf?cite=2013%20c%20260%20§%201[2013 c 260 § 1]; ]

== 69.70.020 - Donations of prescription drugs and supplies—Distribution.
. Any practitioner, pharmacist, medical facility, drug manufacturer, or drug wholesaler may donate prescription drugs and supplies to a pharmacy for redistribution without compensation or the expectation of compensation to individuals who meet the prioritization criteria established in RCW 69.70.040. Donations of prescription drugs and supplies may be made on the premises of a pharmacy that elects to participate in the provisions of this chapter. A pharmacy that receives prescription drugs or supplies may distribute the prescription drugs or supplies to another pharmacy, pharmacist, or prescribing practitioner for use pursuant to the program.

. The person to whom a prescription drug was prescribed, or the person's representative, may donate prescription drugs under subsection (1) of this section if, as determined by the professional judgment of a pharmacist, prescription drugs:

.. Equipped with a time temperature indicator at the point of manufacture were stored under required temperature conditions using the prescription drugs' time temperature indicator information and the person, or the person's representative, has completed and signed a donor form, adopted by the department, to release the prescription drug for distribution under this chapter and certifying that the donated prescription drug has never been opened, used, adulterated, or misbranded; or

.. Not equipped with a time temperature indicator at the point of manufacture, were properly stored and the person, or the person's representative, has completed and signed a donor form, adopted by the department, to release the prescription drugs for distribution under this chapter and certified that the donated prescription drugs have never been opened, used, adulterated, or misbranded. The donor form must require that the person, or the person's representative, attest that the donated prescription drugs have been stored in a manner and location that adheres to the conditions established by the manufacturer.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1765-S.SL.pdf?cite=2017%20c%20205%20§%201[2017 c 205 § 1]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2458-S.SL.pdf?cite=2016%20c%2043%20§%202[2016 c 43 § 2]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5148-S.SL.pdf?cite=2013%20c%20260%20§%202[2013 c 260 § 2]; ]

== 69.70.030 - Immunity—Eligibility.
To be eligible for the immunity in RCW 69.70.070, a person distributing donated prescription drugs under this chapter must:

. Meet all requirements in RCW 69.70.050 and any applicable rules related to the return or exchange of prescription drugs or supplies adopted by the *board of pharmacy;

. Maintain records of any prescription drugs and supplies donated to the pharmacy and subsequently dispensed by the pharmacy; and

. Identify itself to the public as participating in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5148-S.SL.pdf?cite=2013%20c%20260%20§%203[2013 c 260 § 3]; ]

== 69.70.040 - Dispensing of donated prescription drugs and supplies—Priority given to individuals who are uninsured.
Pharmacies, pharmacists, and prescribing practitioners that elect to dispense donated prescription drugs and supplies under this chapter shall give priority to individuals who are uninsured. If an uninsured individual has not been identified as in need of available prescription drugs and supplies, those prescription drugs and supplies may be dispensed to other individuals expressing need.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2458-S.SL.pdf?cite=2016%20c%2043%20§%203[2016 c 43 § 3]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5148-S.SL.pdf?cite=2013%20c%20260%20§%204[2013 c 260 § 4]; ]

== 69.70.050 - Acceptance and dispensing of prescription drugs or supplies—Requirements—Recalls—Reselling—Reimbursement, related dispensing fees—Manufacturer registration.
. Prescription drugs or supplies may be accepted and dispensed under this chapter if all of the following conditions are met:

.. The prescription drug is in:

... Its original sealed and tamper evident packaging; or

... An opened package if it contains single unit doses that remain intact;

.. The prescription drug bears an expiration date that is more than six months after the date the prescription drug was donated;

.. The prescription drug or supplies are inspected before the prescription drug or supplies are dispensed by a pharmacist employed by or under contract with the pharmacy, and the pharmacist determines that the prescription drug or supplies are not adulterated or misbranded;

.. The prescription drug or supplies are prescribed by a practitioner for use by an eligible individual and are dispensed by a pharmacist; and

.. Any other safety precautions established by the department have been satisfied.

. [Empty]
.. If a person who donates prescription drugs or supplies to a pharmacy under this chapter receives a notice that the donated prescription drugs or supplies have been recalled, the person shall notify the pharmacy of the recall.

.. If a pharmacy that receives and distributes donated prescription drugs to another pharmacy, pharmacist, or prescribing practitioner under this chapter receives notice that the donated prescription drugs or supplies have been recalled, the pharmacy shall notify the other pharmacy, pharmacist, or prescribing practitioner of the recall.

.. If a person collecting or distributing donated prescription drugs or supplies under this chapter receives a recall notice from the drug manufacturer or the federal food and drug administration for donated prescription drugs or supplies, the person shall immediately remove all recalled medications from stock and comply with the instructions in the recall notice.

. Prescription drugs and supplies donated under this chapter may not be resold.

. Prescription drugs and supplies dispensed under this chapter shall not be eligible for reimbursement of the prescription drug or any related dispensing fees by any public or private health care payer.

. A prescription drug that can only be dispensed to a patient registered with the manufacturer of that drug, in accordance with the requirements established by the federal food and drug administration, may not be distributed under the program, unless the patient receiving the prescription drug is registered with the manufacturer at the time the drug is dispensed and the amount dispensed does not exceed the duration of the registration period.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2458-S.SL.pdf?cite=2016%20c%2043%20§%204[2016 c 43 § 4]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5148-S.SL.pdf?cite=2013%20c%20260%20§%205[2013 c 260 § 5]; ]

== 69.70.060 - Form—Department to develop.
The department shall develop a form for persons to use when releasing prescription drugs for distribution and certifying the condition of the drugs, as provided in RCW 69.70.020(2).

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2458-S.SL.pdf?cite=2016%20c%2043%20§%205[2016 c 43 § 5]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5148-S.SL.pdf?cite=2013%20c%20260%20§%206[2013 c 260 § 6]; ]

== 69.70.070 - Liability.
. A drug manufacturer acting in good faith may not, in the absence of a finding of gross negligence, be subject to criminal prosecution or liability in tort or other civil action, for injury, death, or loss to person or property for matters relating to the donation, acceptance, or dispensing of any drug manufactured by the drug manufacturer that is donated by any person under the program including, but not limited to:

.. Liability for failure to transfer or communicate product or consumer information or the expiration date of the donated prescription drug; and

.. Liability related to prescription drugs that can only be dispensed to a patient registered with the manufacturer of that drug, in accordance with the requirements established by the federal food and drug administration.

. Any person or entity, other than a drug manufacturer subject to subsection (1) of this section, acting in good faith in donating, accepting, or distributing prescription drugs under this chapter is immune from criminal prosecution, professional discipline, or civil liability of any kind for any injury, death, or loss to any person or property relating to such activities other than acts or omissions constituting gross negligence or willful or wanton misconduct.

. The immunity provided under subsection (1) of this section does not absolve a drug manufacturer of a criminal or civil liability that would have existed but for the donation, nor does such donation increase the liability of the drug manufacturer in such an action.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2458-S.SL.pdf?cite=2016%20c%2043%20§%206[2016 c 43 § 6]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5148-S.SL.pdf?cite=2013%20c%20260%20§%207[2013 c 260 § 7]; ]

== 69.70.080 - Availability of access.
Access to prescription drugs and supplies under this chapter is subject to availability. Nothing in this chapter establishes an entitlement to receive prescription drugs and supplies through the program.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5148-S.SL.pdf?cite=2013%20c%20260%20§%208[2013 c 260 § 8]; ]

== 69.70.090 - Samples.
Nothing in this chapter restricts the use of samples by a practitioner during the course of the practitioner's duties at a medical facility or pharmacy.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5148-S.SL.pdf?cite=2013%20c%20260%20§%209[2013 c 260 § 9]; ]

== 69.70.100 - Resale of prescription drugs not authorized.
Nothing in this chapter authorizes the resale of prescription drugs by any person.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5148-S.SL.pdf?cite=2013%20c%20260%20§%2010[2013 c 260 § 10]; ]

== 69.70.110 - Prescription drug donation—Rules.
The pharmacy quality assurance commission may adopt rules to allow the safe donation of prescription drugs under this chapter including, but not limited to, allowing pharmacy to pharmacy donation of unexpired prescription drug stock.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6526-S.SL.pdf?cite=2020%20c%20264%20§%202[2020 c 264 § 2]; ]

== 69.70.900 - Effective date.
This act takes effect July 1, 2014.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5148-S.SL.pdf?cite=2013%20c%20260%20§%2012[2013 c 260 § 12]; ]

