= 73.40 - Veterans' memorials.
:toc:

== 73.40.010 - Memorial honoring state residents who died or are missing-in-action in southeast Asia.
The secretary of state shall coordinate the design, construction, and placement of a memorial within the state capitol building honoring Washington state residents who died or are "missing-in-action" in the southeast Asia theater of operations.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c81.pdf?cite=1984%20c%2081%20§%201[1984 c 81 § 1]; ]

== 73.40.030 - Memorial honoring state residents who died or are missing-in-action in southeast Asia—Display of individual names.
The memorial authorized by *RCW 40.14.200 through 40.14.210 shall display the individual names of the Washington state residents who died or are "missing-in-action" in the southeast Asia theater of operations.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c81.pdf?cite=1984%20c%2081%20§%203[1984 c 81 § 3]; ]

== 73.40.040 - Memorial honoring state residents who died or are missing-in-action in the Korean conflict.
The director of the department of veterans affairs shall coordinate the design, construction, and placement of a memorial within the state capitol grounds honoring Washington state residents who died or are "missing-in-action" in the Korean conflict.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c235.pdf?cite=1989%20c%20235%20§%201[1989 c 235 § 1]; ]

