= 32.08 - Organization and powers.
:toc:

== 32.08.010 - Authority to organize—Incorporators—Certificate.
When authorized by the director, as hereinafter provided, not less than nine nor more than thirty persons may form a corporation to be known as a "mutual savings bank." Such persons must be citizens of the United States; at least four-fifths of them must be residents of this state, and at least two-thirds of them must be residents of the county where the bank is to be located and its business transacted. They shall subscribe an incorporation certificate in triplicate which shall specifically state:

. The name by which the savings bank is to be known, which name shall include the words "mutual savings bank";

. The place where the bank is to be located, and its business transacted, naming the city or town and county;

. The name, occupation, residence, and post office address of each incorporator;

. The sums which each incorporator will contribute in cash to the initial guaranty fund, and to the expense fund respectively, as provided in RCW 32.08.090 and 32.08.100;

. Any provision the incorporators elect to so set forth which is permitted by RCW 23B.17.030;

. Any other provision the incorporators elect to so set forth which is not inconsistent with this chapter;

. A declaration that each incorporator will accept the responsibilities and faithfully discharge the duties of a trustee of the savings bank, and is free from all the disqualifications specified in RCW 32.16.010.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6285.SL.pdf?cite=1994%20c%20256%20§%2097[1994 c 256 § 97]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20307[1994 c 92 § 307]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.08.010[1955 c 13 § 32.08.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c175.pdf?cite=1915%20c%20175%20§%201[1915 c 175 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1905c129.pdf?cite=1905%20c%20129%20§%202[1905 c 129 § 2]; RRS § 3313; ]

== 32.08.020 - Notice of intention.
At the time of executing the incorporation certificate, the proposed incorporators shall sign a notice of intention to organize the mutual savings bank, which shall specify their names, the name of the proposed corporation, and its location as set forth in the incorporation certificate. The original of such notice shall be filed in the office of the director within sixty days after the date of its execution, and a copy thereof shall be published at least once a week for four successive weeks in a newspaper designated by the director, the publication to be commenced within thirty days after such designation. At least fifteen days before the incorporation certificate is submitted to the director for examination, as provided in RCW 32.08.030, a copy of such notice shall be served upon each savings bank doing business in the city or town named in the incorporation certificate, by mailing such copy (postage prepaid) to such bank.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20308[1994 c 92 § 308]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.08.020[1955 c 13 § 32.08.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c175.pdf?cite=1915%20c%20175%20§%202[1915 c 175 § 2]; RRS § 3314; ]

== 32.08.025 - Limited liability company—Organization or conversion—Approval of director—Conditions—Application of chapter  25.15 RCW—Definitions.
. Notwithstanding any other provision of this title, if the conditions of this section are met, a savings bank, or a holding company of a savings bank, may be organized as, or convert to, a limited liability company under the Washington limited liability company act, chapter 25.15 RCW. As used in this section, "savings bank" includes an applicant to become a savings bank or holding company of a savings bank, and "holding company" means a holding company of a savings bank.

. [Empty]
.. Before a savings bank or holding company may organize as, or convert to, a limited liability company, the savings bank or holding company must obtain approval of the director.

.. [Empty]
... To obtain approval under this section from the director, the savings bank or holding company must file a request for approval with the director at least ninety days before the day on which the savings bank or holding company becomes a limited liability company.

... If the director does not disapprove the request for approval within ninety days from the day on which the director receives the request, the request is considered approved.

... When taking action on a request for approval filed under this section, the director may:

(A) Approve the request;

(B) Approve the request subject to terms and conditions the director considers necessary; or

(C) Disapprove the request.

. To approve a request for approval, the director must find that the savings bank or holding company:

.. Will operate in a safe and sound manner; and

.. Has the following characteristics:

... The certificate of formation and limited liability company require or set forth that the duration of the limited liability company is perpetual;

... The savings bank or holding company is not otherwise subject to automatic termination, dissolution, or suspension upon the happening of some event other than the passage of time;

... The exclusive authority to manage the savings bank or holding company is vested in a board of managers or directors that:

(A) Is elected or appointed by the owners;

(B) Is not required to have owners of the savings bank or holding company included on the board;

(C) Possesses adequate independence and authority to supervise the operation of the savings bank or holding company; and

(D) Operates with substantially the same rights, powers, privileges, duties, and responsibilities as the board of directors of a corporation;

... Neither state law, nor the savings bank's or holding company's operating agreement, bylaws, or other organizational documents provide that an owner of the savings bank or holding company is liable for the debts, liabilities, and obligations of the savings bank or holding company in excess of the amount of the owner's investment;

.. Neither state law, nor the savings bank's or holding company's operating agreement, bylaws, or other organizational documents require the consent of any other owner of the savings bank or holding company in order for any owner to transfer an ownership interest in the savings bank or holding company, including voting rights;

.. The savings bank or holding company is able to obtain new investment funding if needed to maintain adequate capital;

.. The savings bank or holding company is able to comply with all legal and regulatory requirements for a federally insured depository bank, or holding company of a federally insured depository bank, under applicable federal and state law; and

.. A savings bank or holding company that is organized as a limited liability company shall maintain the characteristics listed in this subsection (3)(b) during such time as it is authorized to conduct business under this title as a limited liability company.

. [Empty]
.. All rights, privileges, powers, duties, and obligations of a savings bank or holding company, that is organized as a limited liability company, and its members and managers are governed by the Washington limited liability company act, chapter 25.15 RCW, except:

... To the extent chapter 25.15 RCW is in conflict with federal law or regulation respecting the organization of a federally insured depository institution as a limited liability company, such federal law or regulation supersedes the conflicting provisions contained in chapter 25.15 RCW in relation to a savings bank or holding company organized as a limited liability company pursuant to this section; and

... Without limitation, the following are inapplicable to a savings bank or holding company organized as a limited liability company:

(A) Permitting automatic dissolution or suspension of a limited liability company as set forth in RCW 25.15.265(1), pursuant to a statement of limited duration which, though impermissible under subsection (3)(b)(i) of this section, has been provided for in a certificate of formation;

(B) Permitting automatic dissolution or suspension of a limited liability company, pursuant to the limited liability company agreement, as set forth in RCW 25.15.265(2);

(C) Permitting dissolution of the limited liability company agreement based upon agreement of all the members, as set forth in RCW 25.15.265(3);

(D) Permitting dissociation of all the members of the limited liability company, as set forth in RCW 25.15.265(4); and

(E) Permitting automatic dissolution or suspension of a limited liability company, pursuant to operation of law, as otherwise set forth in chapter 25.15 RCW.

.. Notwithstanding (a) of this subsection:

... For purposes of transferring a member's interests in the savings bank or holding company, a member's interest in the savings bank or holding company is treated like a share of stock in a corporation; and

... If a member's interest in the savings bank or holding company is transferred voluntarily or involuntarily to another person, the person who receives the member's interest obtains the member's entire rights associated with the member's interest in the savings bank or holding company including all economic rights and all voting rights.

.. A savings bank or holding company may not by agreement or otherwise change the application of (a) of this subsection to the savings bank or holding company.

. [Empty]
.. Notwithstanding any provision of chapter 25.15 RCW or this section to the contrary, all voting members remain liable and responsible as fiduciaries of a savings bank or holding company organized as a limited liability company, regardless of resignation, dissociation, or disqualification, to the same extent that directors of a savings bank or holding company organized as a corporation would be or remain liable or responsible to the department and applicable federal banking regulators; and

.. If death, incapacity, or disqualification of all members of the limited liability company would result in a complete dissociation of all members, then the savings bank or holding company, or both, as applicable is deemed nonetheless to remain in existence for purposes of the department or an applicable federal regulator, or both, having standing under RCW 32.24.090 or applicable federal law, or both, to exercise the powers and authorities of a receiver for the savings bank or holding company.

. For the purposes of this section, and unless the context clearly requires otherwise, for the purpose of applying chapter 25.15 RCW to a savings bank or holding company organized as a limited liability company:

.. "Articles of incorporation" includes a limited liability company's certificate of formation, as that term is used in RCW 25.15.006 and 25.15.071, and a limited liability company agreement as that term is used in RCW 25.15.006;

.. "Board of directors" includes one or more persons who have, with respect to a savings bank or holding company described in subsection (1) of this section, authority that is substantially similar to that of a board of directors of a corporation;

.. "Bylaws" includes a limited liability company agreement as that term is defined in RCW 25.15.006;

.. "Corporation" includes a limited liability company organized under chapter 25.15 RCW;

.. "Director" includes any of the following of a limited liability company:

... A manager;

... A director; or

... Other person who has, with respect to the savings bank or holding company described in subsection (1) of this section, authority substantially similar to that of a director of a corporation;

.. "Dividend" includes distributions made by a limited liability company under RCW 25.15.211;

.. "Incorporator" includes the person or persons executing the certificate of formation as provided in RCW 25.15.086;

.. "Officer" includes any of the following of a savings bank or holding company:

.. An officer; or

... Other person who has, with respect to the savings bank or holding company, authority substantially similar to that of an officer of a corporation;

... "Security," "shares," or "stock" of a corporation includes a membership interest in a limited liability company and any certificate or other evidence of an ownership interest in a limited liability company; and

.. "Stockholder" or "shareholder" includes an owner of an equity interest in a savings bank or holding company, including a member as defined in RCW 25.15.006 and 25.15.116.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5030-S.SL.pdf?cite=2015%20c%20188%20§%20120[2015 c 188 § 120]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6463.SL.pdf?cite=2006%20c%2048%20§%203[2006 c 48 § 3]; ]

== 32.08.030 - Submission of certificate—Proof of service of notice.
After the lapse of at least twenty-eight days from the date of the first due publication of the notice of intention to incorporate, and within ten days after the date of the last publication thereof, the incorporation certificate executed in triplicate shall be submitted for examination to the director at his or her office in Olympia, with affidavits showing due publication and service of the notice of intention to organize prescribed in RCW 32.08.020.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20309[1994 c 92 § 309]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.08.030[1955 c 13 § 32.08.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c175.pdf?cite=1915%20c%20175%20§%203[1915 c 175 § 3]; RRS § 3315; ]

== 32.08.040 - Examination and action by director.
When any such certificate has been filed for examination the director shall thereupon ascertain from the best source of information at his or her command, and by such investigation as he or she may deem necessary, whether the character, responsibility, and general fitness of the person or persons named in such certificate are such as to command confidence and warrant belief that the business of the proposed bank will be honestly and efficiently conducted in accordance with the intent and purpose of this title, and whether the public convenience and advantage will be promoted by allowing such proposed bank to be incorporated and engage in business, and whether greater convenience and access to a savings bank would be afforded to any considerable number of depositors by opening a mutual savings bank in the place designated, whether the population in the neighborhood of such place, and in the surrounding country, affords a reasonable promise of adequate support for the proposed bank, and whether the contributions to the initial guaranty fund and expense fund have been paid in cash. After the director has satisfied himself or herself by such investigation whether it is expedient and desirable to permit such proposed bank to be incorporated and engage in business, he or she shall within sixty days after the date of the filing of the certificate for examination indorse upon each of the triplicates thereof over his or her official signature the word "approved" or the word "refused," with the date of such indorsement. In case of refusal he or she shall forthwith return one of the triplicates so indorsed to the proposed incorporators from whom the certificate was received.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20310[1994 c 92 § 310]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.08.040[1955 c 13 § 32.08.040]; 1915 c 175 § 4, part; RRS § 3316, part; ]

== 32.08.050 - Appeal from adverse decision.
From the director's refusal to issue a certificate of authorization, the applicants or a majority of them, may within thirty days from the date of the filing of the certificate of refusal with the secretary of state, appeal to a board of appeal composed of the governor or the governor's designee, the attorney general and the director by filing in the office of the director a notice that they appeal to such board from his or her refusal. The procedure upon the appeal shall be such as the board may prescribe, and its determination shall be certified, filed, and recorded in the same manner as the director's, and shall be final.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20311[1994 c 92 § 311]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c57.pdf?cite=1979%20ex.s.%20c%2057%20§%206[1979 ex.s. c 57 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.08.050[1955 c 13 § 32.08.050]; 1915 c 175 § 4, part; RRS § 3316, part; ]

== 32.08.060 - Procedure upon approval.
In case of approval, the director shall forthwith give notice thereof to the proposed incorporators, and file one of the duplicate certificates in his or her own office, and shall transmit the other to the secretary of state. Upon receipt from the proposed incorporators of the same fees as are required for filing and recording other incorporation certificates, the secretary of state shall file the certificate and record the same. Upon the filing of said incorporation certificate in duplicate approved as aforesaid in the offices of the director and the secretary of state, the persons named therein and their successors shall thereupon become and be a corporation, which corporation shall have the powers and be subject to the duties and obligations prescribed in this title and its corporate existence shall be perpetual, unless sooner terminated pursuant to law, but such corporation shall not receive deposits or engage in business until authorized so to do by the director as provided in RCW 32.08.070.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20312[1994 c 92 § 312]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c302.pdf?cite=1981%20c%20302%20§%2026[1981 c 302 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c80.pdf?cite=1957%20c%2080%20§%201[1957 c 80 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.08.060[1955 c 13 § 32.08.060]; 1915 c 175 § 4, part; RRS § 3316, part; ]

== 32.08.061 - Extension of period of existence—Procedure.
A mutual savings bank may amend its incorporation certificate to extend the period of its corporate existence for a further definite time or perpetually by a resolution adopted by a majority vote of its board of trustees. Duplicate copies of the resolution, subscribed and acknowledged by the president and secretary of such bank, shall be filed in the office of the director within thirty days after its adoption. If the director finds that the resolution conforms to law he or she shall, within sixty days after the date of the filing thereof, endorse upon each of the duplicates thereof, over his or her official signature, his or her approval and forthwith give notice thereof to the bank and shall file one of the certificates in his or her own office and shall transmit the other to the secretary of state. Upon receipt from the mutual savings bank of the same fees as are required of general corporations for filing corresponding instruments, the secretary of state shall file the resolution and record the same. Upon the filing of said resolution in duplicate, approved as aforesaid in the offices of the director and the secretary of state, the corporate existence of said bank shall continue for the period set forth in said resolution unless sooner terminated pursuant to law.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20313[1994 c 92 § 313]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c302.pdf?cite=1981%20c%20302%20§%2027[1981 c 302 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c176.pdf?cite=1963%20c%20176%20§%201[1963 c 176 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c80.pdf?cite=1957%20c%2080%20§%208[1957 c 80 § 8]; ]

== 32.08.070 - Authorization certificate.
Before a mutual savings bank shall be authorized to do any business the director shall be satisfied that the corporation has in good faith complied with all the requirements of law and fulfilled all the conditions precedent to commencing business imposed by this title. If satisfied that the corporation has in good faith complied with all the requirements of law, and fulfilled all the conditions precedent to commencing business imposed by this title, the director shall within six months after the date upon which the proposed organization certificate was filed with him or her for examination, but in no case after the expiration of that period, issue under his or her hand and official seal in triplicate an authorization certificate to such corporation. Such authorization certificate shall state that the corporation therein named has complied with all the requirements of law, that it is authorized to transact at the place designated in its certificate of incorporation, the business of a mutual savings bank. One of the triplicate authorization certificates shall be transmitted by the director to the corporation therein named, and the other two authorization certificates shall be filed by the director in the same public offices where the certificate of incorporation is filed, and shall be attached to said incorporation certificate.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20314[1994 c 92 § 314]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c302.pdf?cite=1981%20c%20302%20§%2028[1981 c 302 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.08.070[1955 c 13 § 32.08.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c175.pdf?cite=1915%20c%20175%20§%205[1915 c 175 § 5]; RRS § 3317; ]

== 32.08.080 - Conditions precedent to reception of deposits.
Before such corporation shall be authorized to receive deposits or transact business other than the completion of its organization, the director shall be satisfied that:

. The incorporators have made the deposit of the initial guaranty fund required by this title;

. The incorporators have made the deposit of the expense fund required by RCW 32.08.090 and if the director shall so require, have entered into the agreement or undertaking with him or her and have filed the same and the security therefor as prescribed in said section;

. The corporation has transmitted to the director the name, residence, and post office address of each officer of the corporation;

. Its certificate of incorporation in triplicate has been filed in the respective public offices designated in this title.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20315[1994 c 92 § 315]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.08.080[1955 c 13 § 32.08.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c175.pdf?cite=1915%20c%20175%20§%206[1915 c 175 § 6]; RRS § 3318; ]

== 32.08.090 - Expense fund—Agreement to contribute further—Security.
Before any mutual savings bank shall be authorized to do business, its incorporators shall create an expense fund from which the expense of organizing such bank and its operating expenses may be paid, until such time as its earnings are sufficient to pay its operating expenses in addition to such dividends as may be declared and credited to its depositors from its earnings. The incorporators shall deposit to the credit of such savings bank in cash as an expense fund the sum of five thousand dollars. They shall also enter into such an agreement or undertaking with the director as trustee for the depositors with the savings bank as he or she may require to make such further contributions in cash to the expense fund as may be necessary to pay its operating expenses until such time as it can pay them from its earnings, in addition to such dividends as may be declared and credited to its depositors. Such agreement or undertaking shall fix the maximum liability assumed thereby which shall be a reasonable amount approved by the director and the same shall be secured to his or her satisfaction, which security in his or her discretion may be by a surety bond executed by a domestic or foreign corporation authorized to transact within this state the business of surety. The agreement or undertaking and security shall be filed in the office of the director. Such agreement or undertaking and such security need not be made or furnished unless the director shall require the same. The amounts contributed to the expense fund of said savings bank by the incorporators or trustees shall not constitute a liability of the savings bank except as hereinafter provided.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20316[1994 c 92 § 316]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.08.090[1955 c 13 § 32.08.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c175.pdf?cite=1915%20c%20175%20§%208[1915 c 175 § 8]; RRS § 3320; ]

== 32.08.100 - Guaranty fund.
Before any mutual savings bank shall be authorized to do business, its incorporators shall create a guaranty fund for the protection of its depositors against loss on its investments, whether arising from depreciation in the market value of its securities or otherwise:

. Such guaranty fund shall consist of payments in cash made by the original incorporators and of all sums credited thereto from the earnings of the savings bank as hereinafter required.

. The incorporators shall deposit to the credit of such savings bank in cash as an initial guaranty fund at least five thousand dollars.

. Prior to the liquidation of any such savings bank such guaranty fund shall not be in any manner encroached upon, except for losses and the repayment of contributions made by incorporators or trustees as hereinafter provided, until such fund together with undivided profits exceeds twenty-five percent of the amount due depositors.

. The amounts contributed to such guaranty fund by the incorporators or trustees shall not constitute a liability of the savings bank, except as hereinafter provided, and any loss sustained by the savings bank in excess of that portion of the guaranty fund created from earnings may be charged against such contributions pro rata.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.08.100[1955 c 13 § 32.08.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c175.pdf?cite=1915%20c%20175%20§%207[1915 c 175 § 7]; RRS § 3319; ]

== 32.08.110 - Guaranty fund—Purpose.
The contributions of the incorporators, or trustees of any such savings bank under the provisions of RCW 32.08.100, and the sums credited thereto from its net earnings under the provisions of RCW 32.08.120, shall constitute a guaranty fund for the security of its depositors, and shall be held to meet any contingency or loss in its business from depreciation of its securities or otherwise, and for no other purpose except as provided in RCW 32.08.130, and RCW 32.12.090(5).

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.08.110[1955 c 13 § 32.08.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c175.pdf?cite=1915%20c%20175%20§%2021[1915 c 175 § 21]; RRS § 3350; ]

== 32.08.115 - Guaranty fund—Payment of interest and dividends—Legislative declaration.
It is hereby recognized that the savings banks of the state of Washington are affected adversely by the uncertainties and ambiguities in the law relating to guaranty funds. It is the express purpose of the legislature in enacting RCW 32.08.116 to clarify that the law permits payment of interest and dividends from the guaranty funds of savings banks and RCW 32.08.116 shall be liberally construed to that end.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c5.pdf?cite=1982%20c%205%20§%201[1982 c 5 § 1]; ]

== 32.08.116 - Guaranty fund—Payment of interest and dividends—When authorized.
A savings bank not having net earnings or undivided profits or other surplus may pay interest and dividends from its guaranty fund upon prior written approval of the director, which approval shall not be withheld unless the director has determined that such payments would place the savings bank in an unsafe and unsound condition.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20317[1994 c 92 § 317]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c5.pdf?cite=1982%20c%205%20§%202[1982 c 5 § 2]; ]

== 32.08.120 - Guaranty fund—Replenishment—Dividends.
. If at the close of any dividend period the guaranty fund of a savings bank is less than ten percent of the amount due to depositors, there shall be deducted from its net earnings and credited to its guaranty fund not less than five percent of its net earnings for such period.

. The balance of its net earnings for such dividend period, plus any earnings from prior accounting periods not previously disbursed and not reserved for losses or other contingencies or required to be maintained in the guaranty fund, shall be available for dividends.

While the trustees of such savings bank are paying its expenses or any portion thereof, the amounts to be credited to its guaranty fund shall be computed at the same percentage upon the total dividends credited to its depositors instead of upon its net earnings. If the guaranty fund accumulated from earnings equals or exceeds ten percent of the amount due to depositors, the minimum dividend shall be four percent, if the net earnings for such period are sufficient therefor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.08.120[1955 c 13 § 32.08.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c15.pdf?cite=1941%20c%2015%20§%204[1941 c 15 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c123.pdf?cite=1929%20c%20123%20§%203[1929 c 123 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c184.pdf?cite=1927%20c%20184%20§%206[1927 c 184 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c175.pdf?cite=1915%20c%20175%20§%2024[1915 c 175 § 24]; Rem. Supp. 1941 § 3353; ]

== 32.08.130 - Reimbursement fund.
When the portion of the guaranty fund created from earnings amounts to not less than five thousand dollars (including in the case of a savings bank converted from a building and loan or savings and loan association or society the amount of the initial guaranty fund), the board of trustees, with the written consent of the director, may establish a reimbursement fund from which to repay contributors to the expense fund and the initial guaranty fund (excepting the initial guaranty fund in the case of a bank converted from a building and loan or savings and loan association or society), and may transfer to the reimbursement fund any unexpended balance of contributions to the expense fund. At the close of each dividend period the trustees may place to the credit of the reimbursement fund not more than one percent of the net earnings of the bank during that period. Payments from the reimbursement fund may be made from time to time in such amounts as the board of trustees shall determine, and shall be made first to the contributors to the expense fund in proportion to their contributions thereto until they shall have been repaid in full, and then shall be made to the contributors to the guaranty fund in proportion to their contributions thereto until they shall have been repaid in full. In case of the liquidation of the savings bank before the contributions to the expense fund and the initial guaranty fund have been fully repaid as above contemplated, any portion of the contributions not needed for the payment of the expenses of liquidation and the payment of depositors in full shall be paid to the contributors to the expense fund in proportion to their contributions thereto until they have been repaid in full, and then shall be paid to the contributors to the guaranty fund in proportion to their contributions thereto until they have been repaid in full.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20318[1994 c 92 § 318]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.08.130[1955 c 13 § 32.08.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c135.pdf?cite=1945%20c%20135%20§%201[1945 c 135 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c178.pdf?cite=1927%20c%20178%20§%201[1927 c 178 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c175.pdf?cite=1915%20c%20175%20§%209[1915 c 175 § 9]; Rem. Supp. 1945 § 3321; ]

== 32.08.140 - Powers of bank. (Contingent expiration date.)
Every savings bank incorporated under this title shall have, subject to the restrictions and limitations contained in this title, the following powers:

. To receive deposits of money, to invest the same in the property and securities prescribed in this title, to declare dividends in the manner prescribed in this title, and to exercise by its board of trustees or duly authorized officers or agents, subject to law, all such incidental powers as shall be necessary to carry on the business of a savings bank;

. To issue transferable certificates showing the amounts contributed by any incorporator or trustee to the guaranty fund of such bank, or for the purpose of paying its expenses. Every such certificate shall show that it does not constitute a liability of the savings bank, except as otherwise provided in this title;

. To purchase, hold and convey real property as prescribed in RCW 32.20.280;

. To pay depositors as hereinafter provided, and when requested, pay them by drafts upon deposits to the credit of the savings bank in any city in the United States, and to charge current rates of exchange for such drafts;

. To borrow money in pursuance of a resolution adopted by a vote of a majority of its board of trustees duly entered upon its minutes whereon shall be recorded by ayes and noes the vote of each trustee, for the purpose of repaying depositors, and to pledge or hypothecate securities as collateral for loans so obtained. Immediate written notice shall be given to the director of all amounts so borrowed, and of all assets so pledged or hypothecated;

. Subject to such regulations and restrictions as the director finds to be necessary and proper, to borrow money in pursuance of a resolution, policy, or other governing document adopted by its board of trustees, for purposes other than that of repaying depositors and to pledge or hypothecate its assets as collateral for any such loans, provided that no amount shall at any time be borrowed by a savings bank pursuant to this subsection (6), if such amount, together with the amount then remaining unpaid upon prior borrowings by such savings bank pursuant to this subsection (6), exceeds thirty percent of the assets of the savings bank.

The sale of securities or loans by a bank subject to an agreement to repurchase the securities or loans shall not be considered a borrowing. Borrowings from federal, state, or municipal governments or agencies or instrumentalities thereof shall not be subject to the limits of this subsection;

. To collect or protest promissory notes or bills of exchange owned by such bank or held by it as collateral, and remit the proceeds of the collections by drafts upon deposits to the credit of the savings bank in any city in the United States, and to charge the usual rates or fees for such collection and remittance for such protest;

. To sell gold or silver received in payment of interest or principal of obligations owned by the savings bank or from depositors in the ordinary course of business;

. To act as insurance agent for the purpose of writing fire insurance on property in which the bank has an insurable interest, the property to be located in the city in which the bank is situated and in the immediate contiguous suburbs, notwithstanding anything in any other statute to the contrary;

. To let vaults, safes, boxes or other receptacles for the safekeeping or storage of personal property, subject to laws and regulations applicable to, and with the powers possessed by, safe deposit companies;

. To elect or appoint in such manner as it may determine all necessary or proper officers, agents, boards, and committees, to fix their compensation, subject to the provisions of this title, and to define their powers and duties, and to remove them at will;

. To make and amend bylaws consistent with law for the management of its property and the conduct of its business;

. To wind up and liquidate its business in accordance with this title;

. To adopt and use a common seal and to alter the same at pleasure;

. To exercise the powers and authorities conferred by *RCW 30.04.215;

. To exercise the powers and authorities that may be carried on by a subsidiary of the savings bank that has been determined to be a prudent investment pursuant to RCW 32.20.380;

. To do all other acts authorized by this title;

. To exercise the powers and authorities that may be exercised by an insured state bank in compliance with 12 U.S.C. Sec. 1831a.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1325-S.SL.pdf?cite=2013%20c%2076%20§%2024[2013 c 76 § 24]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5058-S.SL.pdf?cite=1999%20c%2014%20§%2017[1999 c 14 § 17]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2125-S.SL.pdf?cite=1996%20c%202%20§%2023[1996 c 2 § 23]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20319[1994 c 92 § 319]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c86.pdf?cite=1981%20c%2086%20§%202[1981 c 86 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c104.pdf?cite=1977%20ex.s.%20c%20104%20§%201[1977 ex.s. c 104 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c176.pdf?cite=1963%20c%20176%20§%202[1963 c 176 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c80.pdf?cite=1957%20c%2080%20§%202[1957 c 80 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.08.140[1955 c 13 § 32.08.140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c184.pdf?cite=1927%20c%20184%20§%201[1927 c 184 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c86.pdf?cite=1925%20ex.s.%20c%2086%20§%201[1925 ex.s. c 86 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c175.pdf?cite=1915%20c%20175%20§%2010[1915 c 175 § 10]; RRS § 3322; ]

== 32.08.142 - Additional powers of savings bank—Powers of federal mutual savings bank—Definition—Restrictions.
. Notwithstanding any restrictions, limitations, and requirements of law, in addition to all powers, express or implied, that a savings bank has under the laws of this state, a savings bank shall have the powers and authorities that any federal mutual savings bank had on July 28, 1985, or as of a subsequent date not later than July 28, 2013. As used in this section, "powers and authorities" include without limitation powers and authorities in corporate governance matters.

. A savings bank may exercise the powers and authorities granted, after July 28, 2013, to federal mutual savings banks or their successors under federal law only if the director finds that the exercise of such powers and authorities:

.. Serves the convenience and advantage of depositors and borrowers, or the general public; and

.. Maintains the fairness of competition and parity between state-chartered savings banks and federal savings banks or their successors under federal law.

. Notwithstanding any other provision of law, a savings bank has the powers and authorities that an out-of-state state savings bank or savings association operating a branch in Washington has if the director finds that the exercise of such powers and authorities serves the convenience and advantage of depositors and borrowers, or the general public, and maintains the fairness of competition and parity between savings banks and out-of-state state savings banks and savings associations.

. For the purposes of this section, "powers and authorities" include without limitation powers and authorities in corporate governance matters.

. The restrictions, limitations, and requirements applicable to specific powers and authorities of federal mutual savings banks or out-of-state state savings banks or savings associations, as applicable, shall apply to savings banks exercising those powers and authorities permitted under this section but only insofar as the restrictions, limitations, and requirements relate to exercising the powers and authorities granted savings banks solely under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1325-S.SL.pdf?cite=2013%20c%2076%20§%2026[2013 c 76 § 26]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1759-S.SL.pdf?cite=2003%20c%2024%20§%207[2003 c 24 § 7]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5058-S.SL.pdf?cite=1999%20c%2014%20§%2018[1999 c 14 § 18]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2125-S.SL.pdf?cite=1996%20c%202%20§%2024[1996 c 2 § 24]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6285.SL.pdf?cite=1994%20c%20256%20§%2098[1994 c 256 § 98]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c56.pdf?cite=1985%20c%2056%20§%203[1985 c 56 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c86.pdf?cite=1981%20c%2086%20§%2010[1981 c 86 § 10]; ]

== 32.08.145 - Safe deposit companies.
See chapter 22.28 RCW.

[ ]

== 32.08.148 - Operation of branch outside Washington—Powers and authorities.
In addition to all powers and authorities, express or implied, that a mutual savings bank has under the laws of this state, a mutual savings bank chartered under this title may exercise any powers and authorities at any branch outside Washington that are permissible for a savings bank operating in the jurisdiction where that branch is located, or for a bank, savings association, or similar financial institution operating in the jurisdiction if the laws of the jurisdiction do not provide for the operation of savings banks in the jurisdiction, except to the extent that the exercise of these powers and authorities is expressly prohibited or limited by the laws of this state or by any rule or order of the director applicable to the mutual savings bank. However, the director may waive any limitation in writing with respect to powers and authorities that the director determines do not threaten the safety or soundness of the mutual savings bank.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2125-S.SL.pdf?cite=1996%20c%202%20§%2026[1996 c 2 § 26]; ]

== 32.08.150 - Certificates of deposit.
A mutual savings bank may issue savings certificates of deposit in such form and upon such terms as the bank may determine.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c86.pdf?cite=1981%20c%2086%20§%203[1981 c 86 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c51.pdf?cite=1979%20c%2051%20§%201[1979 c 51 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c15.pdf?cite=1975%20c%2015%20§%201[1975 c 15 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c55.pdf?cite=1969%20c%2055%20§%201[1969 c 55 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c41.pdf?cite=1959%20c%2041%20§%201[1959 c 41 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c14.pdf?cite=1959%20c%2014%20§%201[1959 c 14 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c80.pdf?cite=1957%20c%2080%20§%203[1957 c 80 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.08.150[1955 c 13 § 32.08.150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c175.pdf?cite=1915%20c%20175%20§%2013[1915 c 175 § 13]; RRS § 3342; ]

== 32.08.153 - Additional powers of savings bank—Powers and authorities of national banks on July 28, 1985, or a subsequent date not later than July 28, 2013—Definition—Restrictions.
. Notwithstanding any restrictions, limitations, and requirements of law, in addition to all powers, express or implied, that a savings bank has under the laws of this state, a savings bank shall have the powers and authorities that any national bank had on July 28, 1985, or as of any subsequent date not later than July 28, 2013.

. Notwithstanding any restrictions, limitations, and requirements of law, in addition to all powers, express or implied, that a savings bank has under the laws of this state, a savings bank has the powers and authorities conferred upon a national bank after July 28, 2013, only if the director finds that the exercise of such powers and authorities:

.. Serves the convenience and advantage of depositors and borrowers, or the general public; and

.. Maintains the fairness of competition and parity between savings banks and national banks.

. For the purposes of this section, "powers and authorities" include without limitation powers and authorities in corporate governance and operational matters.

. The restrictions, limitations, and requirements applicable to specific powers and authorities of national banks apply to savings banks exercising those powers and authorities permitted under this section but only insofar as the restrictions, limitations, and requirements relate to exercising the powers or authorities granted savings banks solely under this section. The director may require such a savings bank to provide notice prior to implementation of a plan to develop, improve, or continue holding an individual parcel of real estate, including capitalized and operating leases, acquired through any means in full or partial satisfaction of a debt previously contracted, under circumstances in which a national bank would be required to provide notice to the comptroller of the currency prior to implementation of such a plan. The director may adopt rules, orders, directives, standards, policies, memoranda, or other communications to specify guidance with regard to the exercise of the powers and authorities to expend such funds as are needed to enable such a savings bank to recover its total investment, to the fullest extent authorized for a national bank under the national bank act, 12 U.S.C. Sec. 29.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1325-S.SL.pdf?cite=2013%20c%2076%20§%2027[2013 c 76 § 27]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2831.SL.pdf?cite=2010%20c%2088%20§%2049[2010 c 88 § 49]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1759-S.SL.pdf?cite=2003%20c%2024%20§%204[2003 c 24 § 4]; ]

== 32.08.157 - Additional powers—Powers and authorities of banks.
Notwithstanding any restrictions, limitations, and requirements of law, in addition to all powers, express or implied, that a mutual savings bank has under this title, a mutual savings bank has the powers and authorities that a bank has under *Title 30 RCW. As used in this section, "powers and authorities" include without limitation powers and authorities in corporate governance matters.

The restrictions, limitations, and requirements applicable to specific powers or authorities of banks apply to mutual savings banks exercising those powers or authorities permitted under this section but only insofar as the restrictions, limitations, and requirements relate to exercising the powers or authorities granted mutual savings banks solely under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1759-S.SL.pdf?cite=2003%20c%2024%20§%206[2003 c 24 § 6]; ]

== 32.08.160 - Writing of fire insurance restricted.
When a savings bank is itself acting as an insurance agent, a trustee, officer, or employee of the bank shall not act as an insurance agent to write fire insurance on property in which the bank has an insurable interest, and no part of a room used by a savings bank in the transaction of its business shall be occupied or used by any person other than the bank in the writing of fire insurance.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.08.160[1955 c 13 § 32.08.160]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c86.pdf?cite=1925%20ex.s.%20c%2086%20§%207[1925 ex.s. c 86 § 7]; RRS § 3342a; ]

== 32.08.170 - Effect of failure to organize or commence business.
See RCW 30A.08.070.

[ ]

== 32.08.180 - Extension of existence.
See RCW 30A.08.080.

[ ]

== 32.08.190 - May borrow from home loan bank.
See RCW 30A.32.030.

[ ]

== 32.08.210 - Power to act as trustee—Authorized trusts—Limitations—Application to act as trustee, fee—Approval or refusal of application—Right of appeal—Use of word "trust."
. A savings bank has the powers and authorities to engage in trust business that a state commercial bank authorized under RCW 30A.08.150 and subject also to the requirements and conditions for engaging in trust business set forth in this section.

. A mutual savings bank shall have the power to act as trustee under:

.. A trust established by an inter vivos trust agreement or under the will of a deceased person.

.. A trust established in connection with any collective bargaining agreement or labor negotiation wherein the beneficiaries of the trust include the employees concerned under the agreement or negotiation, or a trust established in connection with any pension, profit sharing, or retirement benefit plan of any corporation, partnership, association, or individual, including but not limited to retirement plans established pursuant to the provisions of the act of congress entitled "Self-Employed Individuals Tax Retirement Act of 1962", as now constituted or hereafter amended, or plans established pursuant to the provisions of the act of congress entitled "Employee Retirement Income Security Act of 1974", as now constituted or hereafter amended.

. A mutual savings bank may be appointed to and accept the appointment of personal representative of the last will and testament, or administrator with will annexed, of the estate of any deceased person and to be appointed and to act as guardian of the estate of minors, incompetent persons, and persons with a disability.

. The restrictions, limitations and requirements in Title 30A RCW shall apply to a mutual savings bank exercising the powers granted under this section insofar as the restrictions, limitations, and requirements relate to exercising the powers granted under this section. The incidental trust powers to act as agent in the management of trust property and the transaction of trust business in Title 30A RCW shall apply to a mutual savings bank exercising the powers granted under this section insofar as the incidental powers relate to exercising the powers granted under this section.

. Before engaging in trust business, a mutual savings bank shall apply to the director on such form as he or she shall determine and pay the same fee as required for a state bank to engage in trust business. In considering such application the director shall ascertain from the best source of information at his or her command and by such investigation as he or she may deem necessary whether the management and personnel of the mutual savings bank are such as to command confidence and warrant belief that the trust business will be adequately and efficiently conducted in accordance with law, whether the resources in the neighborhood of such place and in the surrounding country afford a reasonable promise of adequate support for the proposed trust business and whether the resources of the mutual savings bank are sufficient to support the conduct of such trust business, and that the mutual savings bank has and maintains, in addition to its guaranty fund, undivided profits against which the depositors have no prior claim in an amount not less than would be required of a state bank or trust company, which undivided profits shall be eligible for investment in the same manner as the guaranty fund of a mutual savings bank. Within sixty days after receipt of such application, the director shall either approve or refuse the same and forthwith return to the mutual savings bank a copy of the application upon which his or her decision has been endorsed. The director shall not be required to approve or refuse an application until thirty days after any appropriate approval has been obtained from a federal regulatory agency. The applicant shall have the right to appeal from an unfavorable determination in accordance with the procedures of the administrative procedure act, chapter 34.05 RCW, as now or hereafter amended. A mutual savings bank shall not use the word "trust" in its name, but may use the word "trust" in its business or advertising.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6135.SL.pdf?cite=2014%20c%2037%20§%20502[2014 c 37 § 502]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20320[1994 c 92 § 320]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c265.pdf?cite=1975%201st%20ex.s.%20c%20265%20§%201[1975 1st ex.s. c 265 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c55.pdf?cite=1969%20c%2055%20§%2012[1969 c 55 § 12]; ]

== 32.08.215 - Power to act as trustee for common trust funds under multiple trust agreements—Conditions.
No mutual savings bank or wholly owned subsidiary thereof shall act as trustee for common trust funds established for the benefit of more than one beneficiary under more than one trust agreement, unless the savings bank or subsidiary trust company shall first give written notice to the director, at least sixty days prior to the creation of any such fund.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20321[1994 c 92 § 321]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c56.pdf?cite=1985%20c%2056%20§%204[1985 c 56 § 4]; ]

== 32.08.220 - Findings—Purpose.
The legislature finds that [the] state of Washington needs investment of funds from out of state and from investors in the state of Washington to keep money for real estate and other forms of financing reasonably available for the needs of Washington citizens. Many innovations have taken place in the last several years to aid in the sale of loans or portions thereof to others including the sale of mortgage pass-through certificates, mortgage backed bonds, participation sales with varying rates, terms or priorities to various participants and the like. As the marketing of such investments continues, further innovations can be expected. It will benefit the state if mutual savings banks subject to the laws of this state have the broadest powers possible commensurate with their safety and soundness to take part in such activities. It is the purpose of RCW 32.08.225 and 32.08.230 to grant a broad power.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c86.pdf?cite=1981%20c%2086%20§%2011[1981 c 86 § 11]; ]

== 32.08.225 - Sale, purchase, etc., of interest rate exchange agreements, loans, or interests therein.
Any mutual savings bank may through any device sell, purchase, exchange, issue evidence of a sale or exchange of, or in any manner deal in any form of sale or exchange of interest rate exchange agreements, loans, or any interest therein including but not being limited to mortgage pass-through issues, mortgage backed bond issues, and loan participations and may purchase a subordinated portion thereof, issue letters of credit to insure against losses on a portion thereof, agree to repurchase all or a portion thereof, guarantee all or a portion of the payments thereof, and without any implied limitation by the foregoing or otherwise, do any and all things necessary or convenient to take part in or effectuate any such sales or exchanges by a mutual savings bank itself or by a subsidiary thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c56.pdf?cite=1985%20c%2056%20§%205[1985 c 56 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c86.pdf?cite=1981%20c%2086%20§%2012[1981 c 86 § 12]; ]

== 32.08.230 - Restrictions and requirements by director.
Any mutual savings bank engaging in any activity contemplated in RCW 32.08.225, whereby it holds or purchases subordinated securities, issues letters of credit to secure a portion of any sale or issue of loans sold or exchanged, or in any manner acts as a partial guarantor or insurer or repurchaser of any loans sold or exchanged, shall do so only in accordance with such reasonable restrictions and requirements as the director shall require and shall report and carry such transactions on its books and records in such manner as the director shall require. In establishing any requirements and restrictions hereunder, the director shall consider the effect the transaction and the reporting thereof will have on the safety and soundness of the mutual savings bank engaging in it.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20322[1994 c 92 § 322]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c86.pdf?cite=1981%20c%2086%20§%2013[1981 c 86 § 13]; ]

