= 32.20 - Investments.
:toc:

== 32.20.010 - Definitions.
The words "mutual savings bank" and "savings bank," whenever used in this chapter, shall mean a mutual savings bank organized and existing under the laws of the state of Washington.

The words "its funds," whenever used in this chapter, shall mean and include moneys deposited with or borrowed by a mutual savings bank, sums credited to the guaranty fund of a mutual savings bank, and the income derived from such deposits or fund, or both, and the principal balance of any outstanding capital notes, and capital debentures.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5058-S.SL.pdf?cite=1999%20c%2014%20§%2024[1999 c 14 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c241.pdf?cite=1977%20ex.s.%20c%20241%20§%202[1977 ex.s. c 241 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.20.010[1955 c 13 § 32.20.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c74.pdf?cite=1929%20c%2074%20§%201[1929 c 74 § 1]; RRS § 3381-1; ]

== 32.20.020 - Power to invest funds—Restrictions.
A mutual savings bank shall have the power to invest its funds in the manner set forth in chapter 32.08 RCW and in this chapter and not otherwise.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5058-S.SL.pdf?cite=1999%20c%2014%20§%2025[1999 c 14 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.20.020[1955 c 13 § 32.20.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c74.pdf?cite=1929%20c%2074%20§%202[1929 c 74 § 2]; RRS § 3381-2; ]

== 32.20.030 - Bonds or obligations of United States and Canada.
A mutual savings bank may invest its funds in the bonds or obligations of the United States or the Dominion of Canada or those for which the faith of the United States or the Dominion of Canada is pledged to provide for the payment of the interest and principal, including bonds of the District of Columbia: PROVIDED, That in the case of bonds of the Dominion or those for which its faith is pledged the interest and principal is payable in the United States or with exchange to a city in the United States and in lawful money of the United States or its equivalent.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.20.030[1955 c 13 § 32.20.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c95.pdf?cite=1937%20c%2095%20§%201[1937 c 95 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c74.pdf?cite=1929%20c%2074%20§%203[1929 c 74 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c86.pdf?cite=1925%20ex.s.%20c%2086%20§%202[1925 ex.s. c 86 § 2]; 1921 c 156 §§ 11, 11a; RRS § 3381-3; ]

== 32.20.035 - Investment trusts or companies.
Except as may be limited by the director by rule, a mutual savings bank may invest its funds in obligations of the United States, as authorized by RCW 32.20.030, either directly or in the form of securities of, or other interests in, an open-end or closed-end management type investment company or investment trust registered under the federal investment company act of 1940, as now or hereafter amended, if both of the following conditions are met:

. The portfolio of the investment company or investment trust is limited to obligations of the United States and to repurchase agreements fully collateralized by such obligations; and

. The investment company or investment trust takes delivery of the collateral for any repurchase agreement either directly or through an authorized custodian.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20336[1994 c 92 § 336]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c97.pdf?cite=1989%20c%2097%20§%202[1989 c 97 § 2]; ]

== 32.20.040 - Federally insured or secured loans, securities, etc.
A mutual savings bank may invest its funds:

. In such loans and advances of credit and purchases of obligations representing loans and advances of credit as are eligible for insurance by the Federal Housing Administrator, and may obtain such insurance.

. In such loans secured by mortgage on real property as the Federal Housing Administrator insures or makes a commitment to insure, and may obtain such insurance.

. In such other loans or contracts or advances of credit as are insured or guaranteed or which are covered by a repurchase agreement in whole or in part by the United States or through any corporation, administrator, agency or instrumentality which is or hereafter may be created by the United States, and may obtain such insurance or guarantee.

. In capital stock, notes, bonds, debentures, or other such obligations of any national mortgage association.

. In such loans as are secured by contracts of the United States or any agency or department thereof assigned under the "Assignment of Claims Act of 1940," approved October 9, 1940, and acts amendatory thereof or supplementary thereto, and may participate with others in such loans.

. In notes or bonds secured by mortgages issued under sections 500 to 505, inclusive, of Title III of the Servicemen's Readjustment Act of 1944 (Public Law 346, 78th congress), and any amendments thereto, and the regulations, orders or rulings promulgated thereunder.

No law of this state prescribing the nature, amount, or form of security or requiring security or prescribing or limiting interest rates or prescribing or limiting the term, shall be deemed to apply to loans, contracts, advances of credit or purchases made pursuant to the foregoing subdivisions (1), (2), (3), (4), (5), and (6).

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c176.pdf?cite=1963%20c%20176%20§%205[1963 c 176 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.20.040[1955 c 13 § 32.20.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c228.pdf?cite=1945%20c%20228%20§%201[1945 c 228 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c15.pdf?cite=1941%20c%2015%20§%206[1941 c 15 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c33.pdf?cite=1939%20c%2033%20§%201[1939 c 33 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c10.pdf?cite=1935%20c%2010%20§%201[1935 c 10 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c74.pdf?cite=1929%20c%2074%20§%203a[1929 c 74 § 3a]; Rem. Supp. 1945 § 3381-3a; ]

== 32.20.045 - Obligations of corporations created as federal agency or instrumentality.
A mutual savings bank may invest its funds in capital stock, notes, bonds, debentures, or other such obligations of any corporation which is or hereafter may be created by the United States as a governmental agency or instrumentality: PROVIDED, That the total amount a mutual savings bank may invest pursuant to this section shall not exceed fifteen percent of the funds of such savings bank: PROVIDED FURTHER, That the amounts heretofore or hereafter invested by a mutual savings bank pursuant to any law of this state other than this section, even if such investment might also be authorized under this section, shall not be limited by the provisions of this section and amounts so invested pursuant to any such other law of this state shall not be included in computing the maximum amount which may be invested pursuant to this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c145.pdf?cite=1967%20c%20145%20§%204[1967 c 145 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c80.pdf?cite=1957%20c%2080%20§%2010[1957 c 80 § 10]; ]

== 32.20.047 - Stock of small business investment companies regulated by United States.
A savings bank may purchase and hold for its own investment account stock in small business investment companies licensed and regulated by the United States, as authorized by the Small Business Act, Public Law 85-536, 72 Statutes at Large 384, in an amount not to exceed one percent of the guaranty fund of such mutual savings bank.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c185.pdf?cite=1959%20c%20185%20§%202[1959 c 185 § 2]; ]

== 32.20.050 - Bonds of state of Washington and its agencies.
A mutual savings bank may invest its funds in the bonds or interest bearing obligations of this state, or any agency thereof, issued pursuant to the authority of any law of this state, whether such bonds or interest bearing obligations are general or limited obligations of the state or such agency.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.20.050[1955 c 13 § 32.20.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c238.pdf?cite=1953%20c%20238%20§%204[1953 c 238 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c74.pdf?cite=1929%20c%2074%20§%209[1929 c 74 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c156.pdf?cite=1921%20c%20156%20§%2011b[1921 c 156 § 11b]; RRS § 3381-4; ]

== 32.20.060 - Bonds of other states.
A mutual savings bank may invest its funds in the bonds or obligations of any other state of the United States upon which there is no default.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.20.060[1955 c 13 § 32.20.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c95.pdf?cite=1937%20c%2095%20§%202[1937 c 95 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c74.pdf?cite=1929%20c%2074%20§%205[1929 c 74 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c156.pdf?cite=1921%20c%20156%20§%2011c[1921 c 156 § 11c]; RRS § 3381-5; ]

== 32.20.070 - Bonds and warrants of counties, municipalities, etc., of Washington.
A mutual savings bank may invest its funds in the valid warrants or bonds of any county, city, town, school district, port district, water-sewer district, or other municipal corporation in the state of Washington issued pursuant to law and for the payment of which the faith and credit of such county, municipality, or district is pledged and taxes are leviable upon all taxable property within its limits.

A mutual savings bank may invest its funds in the water revenue, sewer revenue, or electric revenue bonds of any city or public utility district of this state for the payment of which the entire revenue of the city's or district's water system, sewer system, or electric system, less maintenance and operating costs, is irrevocably pledged.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%2026[1999 c 153 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.20.070[1955 c 13 § 32.20.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c15.pdf?cite=1941%20c%2015%20§%207[1941 c 15 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c95.pdf?cite=1937%20c%2095%20§%203[1937 c 95 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c74.pdf?cite=1929%20c%2074%20§%206[1929 c 74 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c86.pdf?cite=1925%20ex.s.%20c%2086%20§%203[1925 ex.s. c 86 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c156.pdf?cite=1921%20c%20156%20§%2011d[1921 c 156 § 11d]; Rem. Supp. 1941 § 3381-6; ]

== 32.20.080 - Municipal bonds in adjoining state.
A mutual savings bank may invest its funds in the valid bonds of any incorporated city having a population in excess of three thousand inhabitants as shown by the last decennial federal census or of any county or school district situated in one of the states of the United States which adjoins the state of Washington: PROVIDED, That the indebtedness of such city or school district, together with the indebtedness of any other district or other municipal corporation or subdivision (except a county) which is wholly or in part included within the boundaries or limits of the city or school district, less its water debt and sinking fund, does not exceed twelve percent, or the indebtedness of the county less its sinking fund does not exceed seven percent, of the valuation thereof for the purposes of taxation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.20.080[1955 c 13 § 32.20.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c95.pdf?cite=1937%20c%2095%20§%204[1937 c 95 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c74.pdf?cite=1929%20c%2074%20§%207[1929 c 74 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c86.pdf?cite=1925%20ex.s.%20c%2086%20§%204[1925 ex.s. c 86 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c156.pdf?cite=1921%20c%20156%20§%2011e[1921 c 156 § 11e]; RRS § 3381-7; ]

== 32.20.090 - Housing and industrial development bonds and municipal obligations in any state.
A mutual savings bank may invest in housing or industrial development bonds or municipal obligations issued by a state, county, parish, borough, city, or district situated in the United States, or by any instrumentality thereof, provided such bonds or obligations at the time of purchase are prudent investments.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c56.pdf?cite=1985%20c%2056%20§%2011[1985 c 56 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.20.090[1955 c 13 § 32.20.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c95.pdf?cite=1937%20c%2095%20§%205[1937 c 95 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c74.pdf?cite=1929%20c%2074%20§%208[1929 c 74 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c156.pdf?cite=1921%20c%20156%20§%2011f[1921 c 156 § 11f]; RRS § 3381-8; ]

== 32.20.100 - Revenue bonds of certain cities in any state.
A mutual savings bank may invest its funds in the water revenue or electric revenue bonds of any incorporated city situated in the United States: PROVIDED, That the city has a population as shown by the last decennial federal census of at least forty-five thousand inhabitants, and the entire revenue of the city's water or electric system less maintenance and operating costs is irrevocably pledged to the payment of the interest and principal of the bonds.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.20.100[1955 c 13 § 32.20.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c15.pdf?cite=1941%20c%2015%20§%208[1941 c 15 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c95.pdf?cite=1937%20c%2095%20§%206[1937 c 95 § 6]; Rem. Supp. 1941 § 3381-8a; ]

== 32.20.110 - District bonds secured by taxing power.
A mutual savings bank may invest its funds in the bonds of any port district, sanitary district, water-sewer district, tunnel district, bridge district, flood control district, park district, or highway district in the United States which has a population as shown by the last decennial federal census of not less than one hundred fifty thousand inhabitants, and has taxable real property with an assessed valuation in excess of two hundred million dollars and has power to levy taxes on the taxable real property therein for the payment of the bonds without limitation of rate or amount.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%2027[1999 c 153 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.20.110[1955 c 13 § 32.20.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c95.pdf?cite=1937%20c%2095%20§%207[1937 c 95 § 7]; RRS § 3381-8b; ]

== 32.20.120 - Local improvement district bonds.
A mutual savings bank may invest not to exceed fifteen percent of its funds in the bonds or warrants of any local improvement district of any city or town of this state (except bonds or warrants issued for an improvement consisting of grading only), unless the total indebtedness of the district after the completion of the improvement for which the bonds or warrants are issued, plus the amount of all other assessments of a local or special nature against the land assessed or liable to be assessed to pay the bonds, exceed fifty percent of the value of the benefited property, exclusive of improvements, at the time the bonds or warrants are purchased or taken by the bank, according to the actual valuation last placed upon the property for general taxation.

Before any such bonds or warrants are purchased or taken as security the condition of the district's affairs shall be ascertained and the property of the district examined by at least two members of the board of investment who shall report in writing their findings and recommendations; and no bonds or warrants shall be taken unless such report is favorable, nor unless the executive committee of the board of trustees after careful investigation is satisfied of the validity of the bonds or warrants and of the validity and sufficiency of the assessment or other means provided for payment thereof: PROVIDED, That, excepting bonds issued by local improvement districts in cities of the first or second class, for improvements ordered after June 7, 1927, no local improvement district bonds falling within the twenty-five percent in amount of any issue last callable for payment, shall be acquired or taken as security.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.20.120[1955 c 13 § 32.20.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c238.pdf?cite=1953%20c%20238%20§%205[1953 c 238 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c74.pdf?cite=1929%20c%2074%20§%209[1929 c 74 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c156.pdf?cite=1921%20c%20156%20§%2011h[1921 c 156 § 11h]; RRS § 3381-9; ]

== 32.20.130 - Bonds of irrigation, diking, drainage districts.
A mutual savings bank may invest not to exceed five percent of its funds in the bonds of any irrigation, diking, drainage, diking improvement, or drainage improvement district of this state, unless the total indebtedness of the district after the completion of the improvement for which the bonds are issued, plus the amount of all other assessments of a local or special nature against the land assessed or liable to be assessed to pay the bonds, exceeds forty percent of the value of the benefited property, exclusive of improvements, at the time the bonds are purchased or taken by the bank, according to the actual valuation last placed upon the property for general taxation.

Before any such bonds are purchased or taken as security the condition of the district's affairs shall be ascertained and the property of the district examined by at least two members of the board of investment of the mutual savings bank, who shall report in writing their findings and recommendations; and no bonds shall be taken unless such report is favorable, nor unless the executive committee of the board of trustees after careful investigation is satisfied of the validity of the bonds and of the sufficiency of the assessment or other means provided for payment thereof: PROVIDED, That no mutual savings bank shall invest a sum greater than three percent of its funds, or, in any event, more than three hundred thousand dollars, in the bonds of any one district described in this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.20.130[1955 c 13 § 32.20.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c74.pdf?cite=1929%20c%2074%20§%2010[1929 c 74 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c156.pdf?cite=1921%20c%20156%20§%2011h[1921 c 156 § 11h]; RRS § 3381-10; ]

== 32.20.210 - Obligations of International Bank for Reconstruction and Development.
A mutual savings bank may invest not to exceed five percent of its funds in interest bearing obligations of the International Bank for Reconstruction and Development.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.20.210[1955 c 13 § 32.20.210]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c119.pdf?cite=1949%20c%20119%20§%203[1949 c 119 § 3]; Rem. Supp. 1949 § 3381-16b; ]

== 32.20.215 - Obligations issued or guaranteed by Inter-American Development Bank.
A mutual savings bank may invest not to exceed five percent of its funds in obligations issued or guaranteed by the Inter-American Development Bank.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c176.pdf?cite=1963%20c%20176%20§%2014[1963 c 176 § 14]; ]

== 32.20.217 - Obligations of Asian Development Bank.
A mutual savings bank may invest not to exceed five percent of its funds in obligations issued or guaranteed by the Asian Development Bank.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c222.pdf?cite=1971%20ex.s.%20c%20222%20§%207[1971 ex.s. c 222 § 7]; ]

== 32.20.219 - Obligations issued or guaranteed by African Development Bank or other multilateral development bank.
A mutual savings bank may invest not to exceed five percent of its funds in obligations issued or guaranteed by the African Development Bank or in obligations issued or guaranteed by any multilateral development bank in which the United States government formally participates.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c301.pdf?cite=1985%20c%20301%20§%201[1985 c 301 § 1]; ]

== 32.20.220 - Bankers' acceptances, bills of exchange, and commercial paper.
A mutual savings bank may invest not to exceed twenty percent of its funds in the following:

. Bankers' acceptances, and bills of exchange made eligible by law for rediscount with federal reserve banks, provided the same are accepted by a bank or trust company which is a member of the federal reserve system and which has a capital and surplus of not less than two million dollars, or commercial paper which is a prudent investment.

. Bills of exchange drawn by the seller on the purchaser of goods and accepted by such purchaser, of the kind made eligible by law for rediscount with federal reserve banks, provided the same are indorsed by a bank or trust company which is a member of the federal reserve system and which has a capital and surplus of not less than two million dollars.

The aggregate amount of the liability of any bank or trust company to any mutual savings bank, whether as principal or indorser, for acceptances held by such savings bank and deposits made with it, shall not exceed twenty-five percent of the paid up capital and surplus of such bank or trust company, and not more than five percent of the funds of any mutual savings bank shall be invested in the acceptances of or deposited with a bank or trust company of which a trustee of such mutual savings bank is a director.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c56.pdf?cite=1985%20c%2056%20§%2012[1985 c 56 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.20.220[1955 c 13 § 32.20.220]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c74.pdf?cite=1929%20c%2074%20§%2017[1929 c 74 § 17]; RRS § 3381-17; ]

== 32.20.230 - Notes secured by investments.
A mutual savings bank may invest its funds in promissory notes payable to the order of the savings bank, secured by the pledge or assignment of investments lawfully purchasable by a savings bank. No such loan shall exceed ninety percent of the cash market value of such investments so pledged. Should any of the investments so held in pledge depreciate in value after the making of such loan, the savings bank shall require an immediate payment of such loan, or of a part thereof, or additional security therefor, so that the amount loaned thereon shall at no time exceed ninety percent of the market value of the investments so pledged for such loan.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c55.pdf?cite=1969%20c%2055%20§%205[1969 c 55 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c176.pdf?cite=1963%20c%20176%20§%206[1963 c 176 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.20.230[1955 c 13 § 32.20.230]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c228.pdf?cite=1945%20c%20228%20§%202[1945 c 228 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c74.pdf?cite=1929%20c%2074%20§%2018[1929 c 74 § 18]; Rem. Supp. 1945 § 3381-18; ]

== 32.20.240 - Notes secured by pledge or assignment of account.
A mutual savings bank may invest its funds in promissory notes made payable to the order of the savings bank, secured by the pledge or assignment of the account of the mutual savings bank as collateral security for the payment thereof. No such loan shall exceed the balance due the holder of such account.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c145.pdf?cite=1967%20c%20145%20§%205[1967 c 145 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.20.240[1955 c 13 § 32.20.240]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c228.pdf?cite=1945%20c%20228%20§%203[1945 c 228 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c74.pdf?cite=1929%20c%2074%20§%2019[1929 c 74 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c156.pdf?cite=1921%20c%20156%20§%2011m[1921 c 156 § 11m]; Rem. Supp. 1945 § 3381-19; ]

== 32.20.253 - Loans secured by real estate, mobile homes, movable buildings.
A mutual savings bank may invest its funds in loans secured by real estate or on the security of mobile homes or other movable buildings or any interest or estate in any of the foregoing. Such loans may be on such terms and conditions and subject to such limitations and restrictions as the board of trustees shall from time to time establish.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c86.pdf?cite=1981%20c%2086%20§%2014[1981 c 86 § 14]; ]

== 32.20.265 - Valuation of property to be mortgaged—Appraiser's opinion.
When, under any provision of this title, a written report is required of members of the board of investment of a mutual savings bank certifying according to their best judgment the value of any property to be mortgaged such value may be determined upon the signed opinion in writing of an appraiser appointed by the board of trustees of such bank.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c80.pdf?cite=1957%20c%2080%20§%209[1957 c 80 § 9]; ]

== 32.20.280 - Investments in real estate.
A mutual savings bank may invest its funds in real estate as follows:

. A tract of land whereon there is or may be erected a building or buildings suitable for the convenient transaction of the business of the savings bank, from portions of which not required for its own use revenue may be derived: PROVIDED, That the cost of the land and building or buildings for the transaction of the business of the savings bank shall in no case exceed fifty percent of the guaranty fund, undivided profits, reserves, and subordinated securities of the savings bank, except with the approval of the director; and before the purchase of such property is made, or the erection of a building or buildings is commenced, the estimate of the cost thereof, and the cost of the completion of the building or buildings, shall be submitted to and approved by the director. "The cost of the land and building or buildings" means the amounts paid or expended therefor less the reasonable depreciation thereof taken by the bank against such improvements during the time they were held by the bank.

. Such lands as shall be conveyed to the savings bank in satisfaction of debts previously contracted in the course of its business.

. Such lands as the savings bank shall purchase at sales under judgments, decrees, or mortgages held by it.

All real estate purchased by any such savings bank, or taken by it in satisfaction of debts due it, under this section, shall be conveyed to it directly by name, or in the name of a corporation all of the stock of which is owned by the bank, or in such other manner as the bank shall determine to be in the best interest of the bank, and the conveyance shall be immediately recorded in the office of the proper recording officer of the county in which such real estate is situated.

. Every parcel of real estate purchased or acquired by a savings bank under subsections (2) and (3) of this section, shall be sold by it within five years from the date on which it was purchased or acquired, or in case it was acquired subject to a right of redemption, within five years from the date on which the right of redemption expires, unless:

.. There is a building thereon occupied by the savings bank and its offices,

.. The director, on application of the board of trustees of the savings bank, extends the time within which such sale shall be made, or

.. The property is held by the bank as an investment under the provisions of RCW 32.20.285, as now or hereafter amended.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2438-S.SL.pdf?cite=1994%20c%2092%20§%20337[1994 c 92 § 337]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c86.pdf?cite=1981%20c%2086%20§%204[1981 c 86 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c31.pdf?cite=1973%201st%20ex.s.%20c%2031%20§%206[1973 1st ex.s. c 31 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c55.pdf?cite=1969%20c%2055%20§%207[1969 c 55 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.20.280[1955 c 13 § 32.20.280]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c74.pdf?cite=1929%20c%2074%20§%2022[1929 c 74 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c156.pdf?cite=1921%20c%20156%20§%20110[1921 c 156 § 110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c175.pdf?cite=1915%20c%20175%20§%2012[1915 c 175 § 12]; RRS § 3381-22; ]

== 32.20.285 - Investments through purchase of real estate—Improvements.
Subject to such requirements, restrictions, or other conditions as the director may adopt by rule, order, directive, standard, policy, memorandum[,] or other communication with regard to the investment, a savings bank may invest its funds in such real estate, improved or unimproved, and its fixtures and equipment, as the savings bank shall purchase either alone or with others or through ownership of interests in entities holding such real estate. The savings bank may improve property which it owns, and rent, lease, sell, and otherwise deal in such property, the same as any other owner thereof. The total amount a savings bank may invest pursuant to this section shall not exceed twenty percent of its funds. No officer or board trustee or director of the savings bank shall own or hold any interest in any property in which the savings bank owns an interest, and in the event the bank owns an interest in property hereunder with or as a part of another entity, no officer or board trustee or director of the savings bank shall own more than two and one-half percent of the equity or stock of any entity involved, and all of the officers and board trustees or directors of the savings bank shall not own more than five percent of the equity or stock of any entity involved.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2831.SL.pdf?cite=2010%20c%2088%20§%2057[2010 c 88 § 57]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c86.pdf?cite=1981%20c%2086%20§%205[1981 c 86 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c55.pdf?cite=1969%20c%2055%20§%2015[1969 c 55 § 15]; ]

== 32.20.300 - Home loan bank as depositary.
See RCW 30A.32.040.

[ ]

== 32.20.310 - Deposit of securities.
A savings bank may deposit securities owned by it, for safekeeping, with any duly designated depositary for the bank's funds. The written statement of the depositary that it holds for safekeeping specified securities of a savings bank may be taken as evidence of the facts therein shown by any public officer or any officer of the bank or committee of its trustees whose duty it is to examine the affairs and assets of the bank.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.20.310[1955 c 13 § 32.20.310]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c74.pdf?cite=1929%20c%2074%20§%2024[1929 c 74 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c184.pdf?cite=1927%20c%20184%20§%204[1927 c 184 § 4]; RRS § 3381-24; ]

== 32.20.320 - Investment of funds.
The trustees of every savings bank shall as soon as practicable invest the moneys deposited with it in the securities prescribed in this title.

The purchase by a savings bank of a negotiable certificate of deposit or similar security issued by a bank need not be considered a deposit if the certificate or security is eligible for investment by a savings bank under any other provision of this title.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c55.pdf?cite=1969%20c%2055%20§%208[1969 c 55 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.20.320[1955 c 13 § 32.20.320]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c74.pdf?cite=1929%20c%2074%20§%2025[1929 c 74 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c86.pdf?cite=1925%20ex.s.%20c%2086%20§%2011[1925 ex.s. c 86 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c175.pdf?cite=1915%20c%20175%20§%2020[1915 c 175 § 20]; RRS § 3381-25; ]

== 32.20.330 - Investments—Loans, preferred stock, or interest-bearing obligations—Restrictions.
A mutual savings bank may invest in loans to sole proprietorships, partnerships, limited liability companies, corporations, or other entities, or in preferred stock or discounted or other interest bearing obligations issued, guaranteed, or assumed by limited liability companies or corporations commonly accepted as industrial corporations or engaged in communications, transportation, agriculture, furnishing utility professional services, manufacturing, construction, mining, fishing, processing or merchandising of goods, food, or information, banking, or commercial or consumer financing, doing business or incorporated under the laws of the United States, or any state thereof, or the District of Columbia, or the Dominion of Canada, or any province thereof, subject to the following conditions:

. Not more than two percent of the bank's funds shall be invested, pursuant to this section, in the aggregate of loans to and preferred stock and obligations of any person, as defined in *RCW 32.32.228(1)(c), and such person's affiliates, as defined in RCW 32.32.025(1), incorporating the definition of control in RCW 32.32.025(8).

. Such loans or securities shall be prudent investments.

. Pursuant to this section, the total amount a savings bank may invest shall not exceed fifty percent of its funds, and not more than fifteen percent of the bank's funds may be invested in such loans to or securities of any industry.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5058-S.SL.pdf?cite=1999%20c%2014%20§%2026[1999 c 14 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c56.pdf?cite=1985%20c%2056%20§%2013[1985 c 56 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c31.pdf?cite=1973%201st%20ex.s.%20c%2031%20§%207[1973 1st ex.s. c 31 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c222.pdf?cite=1971%20ex.s.%20c%20222%20§%206[1971 ex.s. c 222 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c80.pdf?cite=1955%20c%2080%20§%206[1955 c 80 § 6]; ]

== 32.20.335 - Investments—Qualified thrift investments.
A mutual savings bank may invest in loans or securities that are qualified thrift investments for a savings association subject to the limits specified in 12 U.S.C. Sec. 1467a(m).

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5058-S.SL.pdf?cite=1999%20c%2014%20§%2027[1999 c 14 § 27]; ]

== 32.20.340 - Stock or bonds of federal home loan bank.
See RCW 30A.32.020.

[ ]

== 32.20.350 - Stock of federal reserve bank or Federal Deposit Insurance Corporation.
See RCW 30A.32.010.

[ ]

== 32.20.370 - Corporate bonds and other interest-bearing or discounted obligations.
A mutual savings bank may invest its funds in bonds or other interest bearing or discounted obligations of corporations not otherwise eligible for investment by the savings bank which are prudent investments for such bank in the opinion of its board of trustees or of a committee thereof whose action is ratified by such board at its regular meeting next following such investment. The total amount a mutual savings bank may invest pursuant to this section shall not exceed ten percent of its funds.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c104.pdf?cite=1977%20ex.s.%20c%20104%20§%205[1977 ex.s. c 104 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c145.pdf?cite=1967%20c%20145%20§%209[1967 c 145 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c41.pdf?cite=1959%20c%2041%20§%206[1959 c 41 § 6]; ]

== 32.20.380 - Stocks, securities, of corporations not otherwise eligible for investment.
A mutual savings bank may invest its funds in stocks or other securities of corporations not otherwise eligible for investment by the savings bank which are prudent investments for the bank in the opinion of its board of trustees or of a committee thereof whose action is ratified by the board at its regular meeting next following the investment. The total amount a mutual savings bank may invest pursuant to this section shall not exceed fifty percent of the total of its guaranty fund, undivided profits, and unallocated reserves, or five percent of its deposits, whichever is less.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c86.pdf?cite=1981%20c%2086%20§%206[1981 c 86 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c176.pdf?cite=1963%20c%20176%20§%2016[1963 c 176 § 16]; ]

== 32.20.390 - Obligations of corporations or associations federally authorized to insure or market real estate mortgages—Loans, etc., eligible for insurance.
A mutual savings bank may invest its funds:

. In capital stock, notes, bonds, debentures, participating certificates, and other obligations of any corporation or association which is or hereafter may be created pursuant to any law of the United States for the purpose of insuring or marketing real estate mortgages: PROVIDED, That the amount a mutual savings bank may invest in the capital stock of any one such corporation shall not exceed five percent of the funds of the mutual savings bank and the total amount it may invest in capital stock pursuant to this subsection (1) shall not exceed ten percent of the funds of the mutual savings bank.

. In such loans, advances of credit, participating certificates, and purchases of obligations representing loans and advances of credit as are eligible for insurance by any corporation or association which is or hereafter may be created pursuant to any law of the United States for the purpose of insuring real estate mortgages. The bank may do all acts necessary or appropriate to obtain such insurance. No law of this state prescribing the nature, amount, or form of security, or prescribing or limiting the period for which loans or advances of credit may be made shall apply to loans, advances of credit, or purchases made pursuant to this subsection (2).

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c176.pdf?cite=1963%20c%20176%20§%2017[1963 c 176 § 17]; ]

== 32.20.400 - Loans for home or property repairs, alterations, appliances, improvements, additions, furnishings, underground utilities, education or nonbusiness family purposes.
A mutual savings bank may invest not to exceed twenty percent of its funds pursuant to this section in loans for home or property repairs, alterations, appliances, improvements, or additions, home furnishings, for installation of underground utilities, for educational purposes, or for nonbusiness family purposes: PROVIDED, That the application therefor shall state that the proceeds are to be used for one of the above purposes.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5058-S.SL.pdf?cite=1999%20c%2014%20§%2028[1999 c 14 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c86.pdf?cite=1981%20c%2086%20§%207[1981 c 86 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c104.pdf?cite=1977%20ex.s.%20c%20104%20§%206[1977 ex.s. c 104 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c55.pdf?cite=1969%20c%2055%20§%209[1969 c 55 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c145.pdf?cite=1967%20c%20145%20§%2010[1967 c 145 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c176.pdf?cite=1963%20c%20176%20§%2018[1963 c 176 § 18]; ]

== 32.20.410 - Limitation of total investment in certain obligations.
The aggregate total amount a mutual savings bank may invest in the following shall not exceed the sum of eighty-five percent of its funds and one hundred percent of its borrowings as permitted under RCW 32.08.140, as now or hereafter amended and RCW 32.08.190, as now or hereafter amended:

. Mortgages upon real estate and participations therein;

. Contracts for the sale of realty;

. Mortgages upon leasehold estates; and

. Notes secured by pledges or assignments of first mortgages or real estate contracts.

The limitation of this section shall not apply to GNMA certificates, mortgage backed bonds, mortgage pass-through certificates or other similar securities purchased or held by the bank.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c86.pdf?cite=1981%20c%2086%20§%208[1981 c 86 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c104.pdf?cite=1977%20ex.s.%20c%20104%20§%207[1977 ex.s. c 104 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c55.pdf?cite=1969%20c%2055%20§%2010[1969 c 55 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c176.pdf?cite=1963%20c%20176%20§%2019[1963 c 176 § 19]; ]

== 32.20.415 - Limitation on certain secured and unsecured loans.
In addition to all other investments and loans authorized for mutual savings banks in this state, a mutual savings bank may invest not more than twenty percent of its funds in secured or unsecured loans on such terms and conditions as the bank may determine.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c86.pdf?cite=1981%20c%2086%20§%2015[1981 c 86 § 15]; ]

== 32.20.430 - Loans to banks or trust companies.
A mutual savings bank may invest its funds in loans to banks or trust companies which mature on the next business day following the day of making such loan. The loans may be evidenced by any writing or ledger entries deemed adequate by the mutual savings bank and may be secured or unsecured. The loans made hereunder are payable on the same basis as are regular deposits in such banks, and therefore the transactions may be characterized for accounting and statement purposes and carried on the books of the mutual savings bank as either a deposit with or a loan to the bank.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c222.pdf?cite=1971%20ex.s.%20c%20222%20§%203[1971 ex.s. c 222 § 3]; ]

== 32.20.440 - Purchase of United States securities from banks or trust companies.
A mutual savings bank may invest its funds in the purchase of United States government securities from a bank or trust company, subject to the selling bank's or trust company's agreement to repurchase such securities on the business day next following their purchase by the mutual savings bank. The securities may be purchased at par, or at a premium or discount, as the mutual savings bank may agree, and may be characterized for accounting and statement purposes and carried on the books of the mutual savings bank as such securities to the extent of their market value, and as due from such banks or trust companies to the extent that the repurchase price agreed to be paid exceeds such market value.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c222.pdf?cite=1971%20ex.s.%20c%20222%20§%204[1971 ex.s. c 222 § 4]; ]

== 32.20.445 - Stock, other securities, and obligations of federally insured institutions.
A savings bank may invest its funds in the stock and other securities and obligations of a savings or banking institution or holding company thereof if the deposits of the savings or banking institution are insured by the federal deposit insurance corporation or any other federal instrumentalities established to carry on substantially the same functions as such corporations.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5058-S.SL.pdf?cite=1999%20c%2014%20§%2029[1999 c 14 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c180.pdf?cite=1989%20c%20180%20§%208[1989 c 180 § 8]; ]

== 32.20.450 - Low-cost housing—Legislative finding.
The legislature finds there is a shortage of adequate housing in a suitable environment in many parts of this state for people of modest means, which shortage adversely affects the public in general and the mutual savings banks of this state and their depositors. The legislature further finds that the making of loans or investments to alleviate this problem which may provide a less than market rate of return and entail a higher degree of risk than might otherwise be acceptable, will benefit this state, the banks, and their depositors.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c31.pdf?cite=1973%201st%20ex.s.%20c%2031%20§%201[1973 1st ex.s. c 31 § 1]; ]

== 32.20.460 - Low-cost housing—Factory built housing—Mobile homes.
In addition to the portions of its funds permitted to be invested in real estate loans under RCW 32.20.410, a mutual savings bank may invest not to exceed fifteen percent of its funds in loans and investments as follows:

. Loans for the rehabilitation, remodeling, or expansion of existing housing.

. Loans in connection with, or participation in:

.. Housing programs of any agency of federal, state, or local government; and

.. Housing programs of any nonprofit, union, community, public, or quasi-public corporation or entity.

Such housing must be made available to all without regard to race, creed, sex, color, or national origin.

. Loans for purchasing or constructing factory built housing, including but not limited to mobile homes. The bank shall determine the amount, security, and repayment basis which it considers prudent for the loans.

. In mobile home chattel paper which finances the acquisition of inventory by a mobile home dealer if the inventory is to be held for sale in the ordinary course of business by the mobile home dealer, the monetary obligation evidenced by such chattel paper is the obligation of the mobile home dealer and the amount thereof does not exceed the amount allowed to be loaned on such mobile homes under subsection (3) of this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c86.pdf?cite=1981%20c%2086%20§%209[1981 c 86 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c104.pdf?cite=1977%20ex.s.%20c%20104%20§%209[1977 ex.s. c 104 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c31.pdf?cite=1973%201st%20ex.s.%20c%2031%20§%202[1973 1st ex.s. c 31 § 2]; ]

== 32.20.470 - Improvement of private land for public parks and recreation areas.
Subject to the limits hereinafter set forth, a mutual savings bank may expend its funds for the improvement for public use of privately owned land as parks or recreation areas, including but not limited to "vest pocket" parks, provided that the owner of such land will:

. Permit public use thereof for a period of at least eighteen months or for such longer period and subject to such other requirements as the bank may impose; and

. At or before the end of public use, permit the removal of all such improvements which in the bank's judgment reasonably may be accomplished.

As used in this section, "public use" means use without regard to race, creed, sex, color, or national origin. The amount expended hereunder and under RCW 32.12.070(2)(d) in any calendar year shall not exceed one-half of one percent of the net earnings of bank for the preceding year.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c31.pdf?cite=1973%201st%20ex.s.%20c%2031%20§%203[1973 1st ex.s. c 31 § 3]; ]

== 32.20.480 - Loans or investments to provide adequate housing and environmental improvements—Criteria—Restrictions.
Loans or investments made under *this 1973 amendatory act may provide a less than market rate of return and entail a higher degree of risk than might otherwise be acceptable to the general market, so long as the board of trustees of the bank determines the loan or investment may be beneficial to the community where made, without the need to show a direct corporate benefit, and so long as any private individual who benefits is not, and is not related to any person who is, an officer, employee, or trustee of the bank. It is hereby recognized that the mutual savings banks of the state of Washington and their depositors are affected adversely by the absence of adequate low-cost housing and environmental developments and improvements within the communities they serve and the state of Washington.

The amount a mutual savings bank may invest under *this 1973 amendatory act during any twelve-month period at less than a market rate of return shall not exceed two percent of the total principal amount of all real estate loans made by the bank during the preceding twelve months.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c31.pdf?cite=1973%201st%20ex.s.%20c%2031%20§%204[1973 1st ex.s. c 31 § 4]; ]

== 32.20.500 - Construction—1973 1st ex.s. c 31.
The powers granted by *this 1973 amendatory act are in addition to and not in limitation of the powers conferred upon a mutual savings bank by other provisions of law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c31.pdf?cite=1973%201st%20ex.s.%20c%2031%20§%208[1973 1st ex.s. c 31 § 8]; ]

