= 32.98 - Construction.
:toc:

== 32.98.010 - Continuation of existing law.
The provisions of this title insofar as they are substantially the same as statutory provisions repealed by this chapter and relating to the same subject matter, shall be construed as restatements and continuations, and not as new enactments.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.98.010[1955 c 13 § 32.98.010]; ]

== 32.98.020 - Title, chapter, section headings not part of law.
Title headings, chapter headings, and section or subsection headings, as used in this title do not constitute any part of the law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.98.020[1955 c 13 § 32.98.020]; ]

== 32.98.030 - Invalidity of part of title not to affect remainder.
If any provision of this title, or its application to any person or circumstance is held invalid, the remainder of the title, or the application of the provision to other persons or circumstances is not affected.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.98.030[1955 c 13 § 32.98.030]; ]

== 32.98.050 - Repeals and saving.
See 1955 c 13 s 32.98.050.

[ ]

== 32.98.060 - Emergency—1955 c 13.
This act is necessary for the immediate preservation of the public peace, health and safety, the support of the state government and its existing public institutions, and shall take effect immediately.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c13.pdf?cite=1955%20c%2013%20§%2032.98.060[1955 c 13 § 32.98.060]; ]

