= 28A.235 - Food services.
:toc:

== 28A.235.010 - Superintendent of public instruction authorized to receive and disburse federal funds.
The superintendent of public instruction is hereby authorized to receive and disburse federal funds made available by acts of congress for the assistance of private nonprofit organizations in providing food services to children and adults according to the provisions of 20 U.S.C. Sec. 1751 et seq., the national school lunch act as amended, and 20 U.S.C. Sec. 1771, et seq., the child nutrition act of 1966, as amended.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c193.pdf?cite=1987%20c%20193%20§%201[1987 c 193 § 1]; ]

== 28A.235.020 - Payment of costs—Federal food services revolving fund—Disbursements.
All reasonably ascertainable costs of performing the duties assumed and performed under RCW 28A.235.010 through 28A.235.030 and 28A.235.140 by either the superintendent of public instruction or another state or local governmental entity in support of the superintendent of public instruction's duties under RCW 28A.235.010 through 28A.235.030 and 28A.235.140 shall be paid exclusively with federal funds and, if any, private gifts and grants. The federal food services revolving fund is hereby established in the custody of the state treasurer. The office of the superintendent of public instruction shall deposit in the fund federal funds received under RCW 28A.235.010, recoveries of such funds, and gifts or grants made to the revolving fund. Disbursements from the fund shall be on authorization of the superintendent of public instruction or the superintendent's designee. The fund is subject to the allotment procedure provided under chapter 43.88 RCW, but no appropriation is required for disbursements. The superintendent of public instruction is authorized to expend from the federal food services revolving fund such funds as are necessary to implement RCW 28A.235.010 through 28A.235.030 and 28A.235.140.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20242[1990 c 33 § 242]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c193.pdf?cite=1987%20c%20193%20§%202[1987 c 193 § 2]; ]

== 28A.235.030 - Rules.
The superintendent shall have the power to promulgate such rules in accordance with chapter 34.05 RCW as are necessary to implement this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c193.pdf?cite=1987%20c%20193%20§%203[1987 c 193 § 3]; ]

== 28A.235.036 - Condensed compliance reports—Second-class districts.
Any compliance reporting requirements as a result of laws in this chapter that apply to second-class districts may be submitted in accordance with RCW 28A.330.250.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5184-S.SL.pdf?cite=2011%20c%2045%20§%2017[2011 c 45 § 17]; ]

== 28A.235.040 - Acquisition authorized.
Notwithstanding any other provision of law or chapter 39.32 RCW, the state superintendent of public instruction is hereby authorized to purchase, or otherwise acquire from the government of the United States or any property or commodity disposal agency thereof, surplus or donated food commodities for the use by any school district for their hot lunch program.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028A.30.010[1969 ex.s. c 223 § 28A.30.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c92.pdf?cite=1967%20ex.s.%20c%2092%20§%201[1967 ex.s. c 92 § 1]; ]

== 28A.235.050 - Contracts for—Other law applicable to.
The state superintendent of public instruction is hereby authorized to enter into any contract with the United States of America, or any agency thereof, for the purchase of any surplus or donated food commodities, without regard to the provisions of any other law requiring the advertising, giving notice, inviting or receiving bids, or which may require the delivery of purchases before payment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028A.30.020[1969 ex.s. c 223 § 28A.30.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c92.pdf?cite=1967%20ex.s.%20c%2092%20§%207[1967 ex.s. c 92 § 7]; ]

== 28A.235.060 - Advancement of costs from revolving fund moneys—Reimbursement by school district to include transaction expense.
In purchasing or otherwise acquiring surplus or donated commodities on the requisition of a school district the superintendent may advance the purchase price and other cost of acquisition thereof from the surplus and donated food commodities revolving fund and the superintendent shall in due course bill the proper school district for the amount paid by him or her for the commodities plus a reasonable amount to cover the expenses incurred by the superintendent's office in connection with the transaction. All payments received for surplus or donated commodities from school districts shall be deposited by the superintendent in the surplus and donated food commodities revolving fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20243[1990 c 33 § 243]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028A.30.030[1969 ex.s. c 223 § 28A.30.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c92.pdf?cite=1967%20ex.s.%20c%2092%20§%204[1967 ex.s. c 92 § 4]; ]

== 28A.235.070 - Revolving fund created.
There is created in the office of the state superintendent of public instruction a revolving fund to be designated the surplus and donated food commodities revolving fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c341.pdf?cite=1985%20c%20341%20§%2010[1985 c 341 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c20.pdf?cite=1979%20ex.s.%20c%2020%20§%201[1979 ex.s. c 20 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028A.30.040[1969 ex.s. c 223 § 28A.30.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c92.pdf?cite=1967%20ex.s.%20c%2092%20§%202[1967 ex.s. c 92 § 2]; ]

== 28A.235.080 - Revolving fund—Administration of fund—Use—School district requisition as prerequisite.
The surplus and donated food commodities revolving fund shall be administered by the state superintendent of public instruction and be used solely for the purchase or other acquisition, including transportation, storage and other cost, of surplus or donable food commodities from the federal government. The superintendent may purchase or otherwise acquire such commodities only after requisition by a school district requesting such commodities.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028A.30.050[1969 ex.s. c 223 § 28A.30.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c92.pdf?cite=1967%20ex.s.%20c%2092%20§%203[1967 ex.s. c 92 § 3]; ]

== 28A.235.090 - Revolving fund—Depositories for fund, bond or security for—Manner of payments from fund.
The surplus and donated food commodities revolving fund shall be deposited by the superintendent in such banks as he or she may select, but any such depository shall furnish a surety bond executed by a surety company or companies authorized to do business in the state of Washington, or collateral eligible as security for deposit of state funds, in at least the full amount of the deposit in each depository bank. Moneys shall be paid from the surplus and donated food commodities revolving fund by voucher and check in such form and in such manner as shall be prescribed by the superintendent.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20244[1990 c 33 § 244]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028A.30.060[1969 ex.s. c 223 § 28A.30.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c92.pdf?cite=1967%20ex.s.%20c%2092%20§%205[1967 ex.s. c 92 § 5]; ]

== 28A.235.100 - Rules.
The superintendent of public instruction shall have power to adopt rules as may be necessary to effectuate the purposes of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5971-S.SL.pdf?cite=1993%20c%20333%20§%205[1993 c 333 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20245[1990 c 33 § 245]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028A.30.070[1969 ex.s. c 223 § 28A.30.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c92.pdf?cite=1967%20ex.s.%20c%2092%20§%206[1967 ex.s. c 92 § 6]; ]

== 28A.235.110 - Suspension of laws, rules, inconsistent herewith.
Any provision of law, or any resolution, rule or regulation which is inconsistent with the provisions of RCW 28A.235.040 through 28A.235.110 is suspended to the extent such provision is inconsistent herewith.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20246[1990 c 33 § 246]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028A.30.080[1969 ex.s. c 223 § 28A.30.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c92.pdf?cite=1967%20ex.s.%20c%2092%20§%208[1967 ex.s. c 92 § 8]; ]

== 28A.235.120 - Meal programs—Establishment and operation—Personnel—Agreements.
The directors of any school district may establish, equip and operate meal programs in school buildings for pupils; certificated and classified employees; volunteers; public agencies, political subdivisions, or associations that serve public entities while using school facilities; other local, state, or federal child nutrition programs; and for school or employee functions: PROVIDED, That the expenditures for food supplies shall not exceed the estimated revenues from the sale of meals, federal aid, Indian education fund lunch aid, or other anticipated revenue, including donations, to be received for that purpose: PROVIDED FURTHER, That the directors of any school district may provide for the use of kitchens and lunchrooms or other facilities in school buildings to furnish meals to elderly persons at cost as provided in RCW 28A.623.020: PROVIDED, FURTHER, That the directors of any school district may provide for the use of kitchens and lunchrooms or other facilities in school buildings to furnish meals at cost as provided in RCW 28A.623.030 to children who are participating in educational or training or care programs or activities conducted by private, nonprofit organizations and entities and to students who are attending private elementary and secondary schools. Operation for the purposes of this section shall include the employment and discharge for sufficient cause of personnel necessary for preparation of food or supervision of students during lunch periods and fixing their compensation, payable from the district general fund, or entering into agreement with a private agency for the establishment, management and/or operation of a food service program or any part thereof.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6425.SL.pdf?cite=2002%20c%2036%20§%201[2002 c 36 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1288.SL.pdf?cite=1997%20c%2013%20§%204[1997 c 13 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20247[1990 c 33 § 247]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c140.pdf?cite=1979%20ex.s.%20c%20140%20§%203[1979 ex.s. c 140 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c58.pdf?cite=1979%20c%2058%20§%201[1979 c 58 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c107.pdf?cite=1973%20c%20107%20§%202[1973 c 107 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028A.58.136[1969 ex.s. c 223 § 28A.58.136]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c31.pdf?cite=1947%20c%2031%20§%201[1947 c 31 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c51.pdf?cite=1943%20c%2051%20§%201[1943 c 51 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c160.pdf?cite=1939%20c%20160%20§%201[1939 c 160 § 1]; Rem. Supp. 1947 § 4706-1. Formerly RCW  28A.58.136,  28.58.260.   1943 c 51 § 2; Rem. Supp. 1943 § 4706-2; ]

== 28A.235.130 - Milk for children at school expense.
The board of directors of any school district may cause to be furnished free of charge, in a suitable receptacle on each and every school day to such children in attendance desiring or in need of the same, not less than one-half pint of milk. The cost of supplying such milk shall be paid for in the same manner as other items of expense incurred in the conduct and operation of said school, except that available federal or state funds may be used therefor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028A.31.020[1969 ex.s. c 223 § 28A.31.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c15.pdf?cite=1935%20c%2015%20§%201[1935 c 15 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c152.pdf?cite=1923%20c%20152%20§%201[1923 c 152 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c190.pdf?cite=1921%20c%20190%20§%201[1921 c 190 § 1]; RRS § 4806; ]

== 28A.235.140 - School breakfast programs.
. For the purposes of this section:

.. "Free or reduced-price lunches" means lunches served by a school district that qualify for federal reimbursement as free or reduced-price lunches under the national school lunch program.

.. "School breakfast program" means a program meeting federal requirements defined in 42 U.S.C. Sec. 1773.

.. "Severe-need school" means a school that qualifies for a severe-need school reimbursement rate from federal funds for school breakfasts served to children from low-income families.

. School districts shall be required to develop and implement plans for a school breakfast program in severe-need schools, pursuant to the schedule in this section. For the second year prior to the implementation of the district's school breakfast program, and for each subsequent school year, each school district shall submit data enabling the superintendent of public instruction to determine which schools within the district will qualify as severe-need schools. In developing its plan, each school district shall consult with an advisory committee including school staff and community members appointed by the board of directors of the district.

. Using district-wide data on school lunch participation during the 1988-89 school year, the superintendent of public instruction shall adopt a schedule for implementation of school breakfast programs in severe-need schools as follows:

.. School districts where at least forty percent of lunches served to students are free or reduced-price lunches shall submit a plan for implementation of a school breakfast program in severe-need schools to the superintendent of public instruction no later than July 1, 1990. Each such district shall implement a school breakfast program in all severe-need schools no later than the second day of school in the 1990-91 school year and in each school year thereafter.

.. School districts where at least twenty-five but less than forty percent of lunches served to students are free or reduced-price lunches shall submit a plan for implementation of a school breakfast program in severe-need schools to the superintendent of public instruction no later than July 1, 1991. Each such district shall implement a school breakfast program in all severe-need schools no later than the second day of school in the 1991-92 school year and in each school year thereafter.

.. School districts where less than twenty-five percent of lunches served to students are free or reduced-price lunches shall submit a plan for implementation of a school breakfast program in severe-need schools to the superintendent of public instruction no later than July 1, 1992. Each such district shall implement a school breakfast program in all severe-need schools no later than the second day of school in the 1992-93 school year and in each school year thereafter.

.. School districts that did not offer a school lunch program in the 1988-89 school year are encouraged to implement such a program and to provide a school breakfast program in all severe-need schools when eligible.

. The requirements in this section shall lapse if the federal reimbursement rate for breakfasts served in severe-need schools is eliminated.

. Students who do not meet family-income criteria for free breakfasts shall be eligible to participate in the school breakfast programs established under this section, and school districts may charge for the breakfasts served to these students. Requirements that school districts have school breakfast programs under this section shall not create or imply any state funding obligation for these costs. The legislature does not intend to include these programs within the state's obligation for basic education funding under Article IX of the Constitution.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5971-S.SL.pdf?cite=1993%20c%20333%20§%201[1993 c 333 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c239.pdf?cite=1989%20c%20239%20§%202[1989 c 239 § 2]; ]

== 28A.235.145 - School breakfast and lunch programs—Use of state funds.
State funds received by school districts under this chapter for school breakfast and lunch programs shall be used to support the operating costs of the program, including labor, unless specific appropriations for nonoperating costs are provided.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5971-S.SL.pdf?cite=1993%20c%20333%20§%202[1993 c 333 § 2]; ]

== 28A.235.150 - School breakfast and lunch programs—Grants to increase participation—Increased state support.
. [Empty]
.. To the extent funds are appropriated for this specific purpose, the superintendent of public instruction may award grants to school districts to:

... Increase awareness of and participation in school breakfast and lunch programs, including breakfast after the bell programs;

... Improve program quality, including the nutritional content of program food and the promotion of nutritious food choices by students;

... Promote innovative school-based programs, including but not limited to developing gardens that provide produce used in school breakfast or lunch programs; and

... Improve the equipment and facilities used in the programs.

.. If applicable, school districts shall demonstrate that they have applied for applicable federal funds before applying for funds under this subsection.

. To the extent funds are appropriated for this specific purpose, the superintendent of public instruction shall increase the state support for school breakfasts and lunches, including breakfast after the bell programs.

. As used in this section, "breakfast after the bell" has the definition in RCW 28A.235.200.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1508-S.SL.pdf?cite=2018%20c%208%20§%207[2018 c 8 § 7]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5971-S.SL.pdf?cite=1993%20c%20333%20§%203[1993 c 333 § 3]; ]

== 28A.235.155 - Federal summer food service program—Administration of funds—Grants.
. The superintendent of public instruction shall administer funds for the federal summer food service program.

. The superintendent of public instruction may award grants, to the extent funds are appropriated, to eligible organizations to help start new summer food service programs for children or to help expand summer food services for children.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5971-S.SL.pdf?cite=1993%20c%20333%20§%204[1993 c 333 § 4]; ]

== 28A.235.160 - Requirements to implement school breakfast, lunch, and summer food service programs—Exemptions.
. For the purposes of this section:

.. "Free or reduced-price lunch" means a lunch served by a school district participating in the national school lunch program to a student qualifying for national school lunch program benefits based on family size-income criteria.

.. "School lunch program" means a meal program meeting the requirements defined by the superintendent of public instruction under subsection (2)(b) of this section.

.. "School breakfast program" means a program meeting federal requirements defined in 42 U.S.C. Sec. 1773.

.. "Severe-need school" means a school that qualifies for a severe-need school reimbursement rate from federal funds for school breakfasts served to children from low-income families.

.. "Summer food service program" means a meal or snack program meeting the requirements defined by the superintendent of public instruction under subsection (4) of this section.

. School districts shall implement a school lunch program in each public school in the district in which educational services are provided to children in any of the grades kindergarten through four and in which twenty-five percent or more of the enrolled students qualify for a free or reduced-price lunch. In developing and implementing its school lunch program, each school district may consult with an advisory committee including school staff, community members, and others appointed by the board of directors of the district.

.. Applications to determine free or reduced-price lunch eligibility shall be distributed and collected for all households of children in schools containing any of the grades kindergarten through four and in which there are no United States department of agriculture child nutrition programs. The applications that are collected must be reviewed to determine eligibility for free or reduced-price lunches. Nothing in this section shall be construed to require completion or submission of the application by a parent or guardian.

.. Using the most current available school data on free and reduced-price lunch eligibility, the superintendent of public instruction shall adopt a schedule for implementation of school lunch programs at each school required to offer such a program under subsection (2) of this section as follows:

... Schools not offering a school lunch program and in which twenty-five percent or more of the enrolled students are eligible for free or reduced-price lunch shall implement a school lunch program not later than the second day of school in the 2005-06 school year and in each school year thereafter.

... The superintendent shall establish minimum standards defining the lunch meals to be served, and such standards must be sufficient to qualify the meals for any available federal reimbursement.

... Nothing in this section shall be interpreted to prevent a school from implementing a school lunch program earlier than the school is required to do so.

. To [the] extent funds are appropriated for this purpose, each school district shall implement a school breakfast program in each school where more than forty percent of students eligible to participate in the school lunch program qualify for free or reduced-price meal reimbursement by the school year 2005-06. For the second year before the implementation of the district's school breakfast program, and for each subsequent school year, each school district shall submit data enabling the superintendent of public instruction to determine which schools within the district will qualify for this requirement. Schools where lunch programs start after the 2003-04 school year, where forty percent of students qualify for free or reduced-price meals, must begin school breakfast programs the second year following the start of a lunch program.

. Each school district shall implement a summer food service program in each public school in the district in which a summer program of academic, enrichment, or remedial services is provided and in which fifty percent or more of the children enrolled in the school qualify for free or reduced-price lunch. However, the superintendent of public instruction shall develop rules establishing criteria to permit an exemption for a school that can demonstrate availability of an adequate alternative summer feeding program. Sites providing meals should be open to all children in the area, unless a compelling case can be made to limit access to the program. The superintendent of public instruction shall adopt a definition of compelling case and a schedule for implementation as follows:

.. Beginning the summer of 2005 if the school currently offers a school breakfast or lunch program; or

.. Beginning the summer following the school year during which a school implements a school lunch program under subsection (2)(b) of this section.

. Schools not offering a breakfast or lunch program may meet the meal service requirements of subsections (2)(b) and (4) of this section through any of the following:

.. Preparing the meals on-site;

.. Receiving the meals from another school that participates in a United States department of agriculture child nutrition program; or

.. Contracting with a nonschool entity that is a licensed food service establishment under RCW 69.07.010.

. Requirements that school districts have a school lunch, breakfast, or summer nutrition program under this section shall not create or imply any state funding obligation for these costs. The legislature does not intend to include these programs within the state's obligation for basic education funding under Article IX of the state Constitution.

. The requirements in this section shall lapse if the federal reimbursement for any school breakfasts, lunches, or summer food service programs is eliminated.

. School districts may be exempted from the requirements of this section by showing good cause why they cannot comply with the office of the superintendent of public instruction to the extent that such exemption is not in conflict with federal or state law. The process and criteria by which school districts are exempted shall be developed by the office of the superintendent of public instruction in consultation with representatives of school directors, school food service, community-based organizations and the Washington state PTA.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1771.SL.pdf?cite=2005%20c%20287%20§%201[2005 c 287 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6411.SL.pdf?cite=2004%20c%2054%20§%202[2004 c 54 § 2]; ]

== 28A.235.170 - Washington grown fresh fruit and vegetable grant program.
. The Washington grown fresh fruit and vegetable grant program is created in the office of the superintendent of public instruction. The purpose of the program is to facilitate consumption of Washington grown nutritious snacks in order to improve student health and expand the market for locally grown fresh produce.

. For purposes of this section, "fresh fruit and vegetables" includes perishable produce that is unprocessed, minimally processed, frozen, dried, or otherwise prepared, stored, and handled to maintain its fresh nature while providing convenience to the user. Producing minimally processed food involves cleaning, washing, cutting, or portioning.

. The program shall increase the number of school children with access to Washington grown fresh fruits and vegetables and shall be modeled after the United States department of agriculture fresh fruit and vegetable program, as described in 42 U.S.C. Sec. 1769(g). Schools receiving funds under the federal program are not eligible for grants under the Washington grown fresh fruit and vegetable grant program.

. [Empty]
.. To the extent that state funds are appropriated specifically for this purpose, the office of the superintendent of public instruction shall solicit applications, conduct a competitive process, and make one or two-year grants to a mix of urban and rural schools to enable eligible schools to provide free Washington grown fresh fruits and vegetables throughout the school day.

.. When evaluating applications and selecting grantees, the superintendent of public instruction shall consider and prioritize the following factors:

... The applicant's plan for ensuring the use of Washington grown fruits and vegetables within the program;

... The applicant's plan for incorporating nutrition, agricultural stewardship education, and environmental education into the snack program;

... The applicant's plan for establishing partnerships with state, local, and private entities to further the program's objectives, such as helping the school acquire, handle, store, and distribute Washington grown fresh fruits and vegetables.

. [Empty]
.. The office of the superintendent of public instruction shall give funding priority to applicant schools with any of grades kindergarten through eight that: Participate in the national school lunch program and have fifty percent or more of their students eligible for free or reduced-price meals under the federal national school lunch act, 42 U.S.C. Sec. 1751 et seq.

.. If any funds remain after all eligible priority applicant schools have been awarded grants, the office of the superintendent of public instruction may award grants to applicant schools having less than fifty percent of the students eligible for free or reduced-price meals.

. The office of the superintendent of public instruction may adopt rules to carry out the grant program.

. With assistance from the Washington department of agriculture, the office of the superintendent of public instruction shall develop and track specific, quantifiable outcome measures of the grant program such as the number of students served by the program, the dollar value of purchases of Washington grown fruits and vegetables resulting from the program, and development of state, local, and private partnerships that extend beyond the cafeteria.

. As used in this section, "Washington grown" has the definition in RCW 15.64.060.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6483-S2.SL.pdf?cite=2008%20c%20215%20§%203[2008 c 215 § 3]; ]

== 28A.235.180 - Farm-to-school initiatives.
. Subject to the availability of amounts appropriated for this specific purpose, the office of the superintendent of public instruction may coordinate with the department of agriculture to promote and facilitate new and existing regional markets programs, including farm-to-school initiatives established in accordance with RCW 15.64.060, and small farm direct marketing assistance in accordance with RCW 15.64.050. In coordinating with the department of agriculture, the office of the superintendent of public instruction is encouraged to provide technical assistance, including outreach and best practices strategies, to school districts with farm-to-school initiatives.

. Subject to the availability of amounts appropriated for this specific purpose, the regional markets programs of the department of agriculture must be a centralized connection point for schools and other institutions for accessing and sharing information, tools, ideas, and best practices for purchasing Washington-grown food.

.. In accordance with this subsection (2), program staff from the department of agriculture may provide:

... Scale-appropriate information and resources to farms to help them respond to the growing demand for local and direct marketed products; and

... Targeted technical assistance to farmers, food businesses, and buyers, including schools, about business planning, access to markets, product development, distribution infrastructure, and sourcing, procuring, and promoting Washington-grown foods.

.. In accordance with this subsection (2), program staff from the department of agriculture may provide technical assistance to:

... Support new and existing farm businesses;

... Maintain the economic viability of farms;

... Support compliance with applicable federal, state, and local requirements; and

... Support access and preparation efforts for competing in markets that are a good fit for their scale and products, including schools and public institutions, and direct-to-consumer markets that include, but are not limited to, farmers markets, local retailers, restaurants, value-added product developments, and agritourism opportunities.

. Subject to the availability of amounts appropriated for this specific purpose, the regional markets programs of the department of agriculture may support school districts in establishing or expanding farm-to-school initiatives by providing information and guidance to overcome barriers to purchasing Washington-grown food. In accordance with this subsection (3), regional markets program activities may include, but are not limited to:

.. Connecting schools and other institutions with farmers and distribution chains;

.. Overcoming seasonality constraints;

.. Providing budgeting assistance;

.. Navigating procurement requirements; and

.. Developing educational materials that can be used in cafeterias, classrooms, and in other educational environments.

. Subject to the availability of amounts appropriated for this specific purpose, school districts and other institutions may coordinate with the department of agriculture to promote and facilitate new and existing farm-to-school initiatives. School district representatives involved in these initiatives may include, but [are] not limited to, school nutrition staff, purchasing staff, student representatives, and parent organizations.

. Subject to the availability of amounts appropriated for this specific purpose, the office of the superintendent of public instruction may award grants to school districts to collaborate with community-based organizations, food banks, and farms or gardens for reducing high school dropout occurrences through farm engagement projects. Projects established by school districts that receive grants in accordance with this section must:

.. Primarily target low-income and disengaged youth who have dropped out or who are at risk of dropping out of high school; and

.. Provide participating youth with opportunities for:

... Performing community service, including, but not limited to, building food gardens for low-income families, and work-based learning and employment during the school year and summer through farm or garden programs;

... Earning core and elective credits applied toward high school graduation, including but not limited to, science, health, and career and technical education credits;

... Receiving development support and services, including social and emotional learning, counseling, leadership training, and career and college guidance; and

... Improving food security for themselves and their community through the project.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1508-S.SL.pdf?cite=2018%20c%208%20§%208[2018 c 8 § 8]; ]

== 28A.235.200 - Breakfast after the bell program—Definitions.
The definitions in this section apply throughout RCW 28A.235.210 and 28A.235.220 unless the context clearly requires otherwise.

. "Breakfast after the bell" means a breakfast that is offered to students after the beginning of the school day. Examples of breakfast after the bell models include, but are not limited to:

.. "Grab and go," where easy-to-eat breakfast foods are available for students to take at the start of the school day or in between morning classes;

.. "Second chance breakfast," where breakfast foods are available during recess, a nutrition break, or later in the morning, for students who are not hungry first thing in the morning, or who arrive late to school; and

.. "Breakfast in the classroom," where breakfast is served in the classroom, often during homeroom or first period.

. "Eligible for free or reduced-price meals" means a student who is eligible under the national school lunch program or school breakfast program to receive lunch or breakfast at no cost to the student or at a reduced cost to the student.

. "High-needs school" means any public school: (a) That has enrollment of seventy percent or more students eligible for free or reduced-price meals in the prior school year; or (b) that is using provision two of the national school lunch act or the community eligibility provision under section 104(a) of the federal healthy, hunger-free kids act of 2010 to provide universal meals and that has a claiming percentage for free or reduced-price meals of seventy percent or more.

. "Public school" has the same meaning as provided in RCW 28A.150.010.

. "School breakfast program" means a program meeting federal requirements under 42 U.S.C. Sec. 1773.

. "School lunch program" means a program meeting federal requirements under 42 U.S.C. Sec. 1751.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1508-S.SL.pdf?cite=2018%20c%208%20§%202[2018 c 8 § 2]; ]

== 28A.235.210 - Breakfast after the bell program. (Expires June 30, 2028.)
. [Empty]
.. In accordance with RCW 28A.235.230 and except as provided in subsection (2) of this section, beginning in the 2019-20 school year, each high-needs school shall offer breakfast after the bell to each student and provide adequate time for students to consume the offered food.

.. Public schools that are not obligated by this section to offer breakfast after the bell are encouraged to do so. Nothing in this section is intended to prevent a high-needs school from implementing a breakfast after the bell program before the 2019-20 school year.

. High-needs schools with at least seventy percent of free or reduced-price eligible children participating in both school lunch and school breakfast are exempt from the provisions of subsection (1) of this section. The office of the superintendent of public instruction shall evaluate individual participation rates annually, and make the participation rates publicly available.

. Each high-needs school may determine the breakfast after the bell service model that best suits its students. Service models include, but are not limited to, breakfast in the classroom, grab and go breakfast, and second chance breakfast.

. All breakfasts served in a breakfast after the bell program must comply with federal meal patterns and nutrition standards for school breakfast programs under the federal healthy, hunger-free kids act of 2010, (P.L. 111-296) and any federal regulations implementing that act. By December 1, 2018, and as needed thereafter, the office of the superintendent of public instruction must develop and distribute best practices and provide technical assistance to school districts on strategies for selecting food items that are low in added sugar. When choosing foods to serve in a breakfast after the bell program, schools must give preference to foods that are healthful and fresh, and if feasible, give preference to Washington-grown food.

. Subject to the availability of amounts appropriated for this specific purpose, the superintendent of public instruction shall administer one-time start-up allocation grants to each high-needs school implementing a breakfast after the bell program under this section. Grant funds provided under this section must be used for the costs associated with launching a breakfast after the bell program, including but not limited to equipment purchases, training, additional staff costs, and janitorial services.

. The legislature does not intend to include the breakfast after the bell programs under this section, including the provision of breakfast, within the definition or funding of the program of basic education under Article IX of the state Constitution.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1508-S.SL.pdf?cite=2018%20c%208%20§%203[2018 c 8 § 3]; ]

== 28A.235.220 - Breakfast after the bell program—Guidelines and training. (Expires June 30, 2028.)
. Before January 2, 2019, the office of the superintendent of public instruction shall develop and distribute procedures and guidelines for the implementation of RCW 28A.235.210 that comply with federal regulations governing the school breakfast program. The guidelines and procedures must include ways schools and districts can solicit and consider the input of families regarding implementation and continued operation of breakfast after the bell programs. The guidelines and procedures must also include recommendations and best practices for designing, implementing, and operating breakfast after the bell programs that are based upon the implementation and operational experiences of schools of differing sizes and in different geographic regions of the state that have implemented breakfast after the bell programs.

. The office of the superintendent of public instruction shall offer training and technical and marketing assistance to all public schools and school districts related to offering breakfast after the bell, including assistance with various funding options available to high-needs schools such as the community eligibility provision under 42 U.S.C. Sec. 1759a(a)(1), programs under provision two of the national school lunch act, and claims for reimbursement under the school breakfast program.

. In accordance with this section, the office of the superintendent of public instruction shall collaborate with nonprofit organizations knowledgeable about equity, the opportunity gap, hunger and food security issues, and best practices for improving student access to school breakfast. The office shall maintain a list of opportunities for philanthropic support of school breakfast programs and make the list available to schools interested in breakfast after the bell programs.

. The office of the superintendent of public instruction shall incorporate the annual collection of information about breakfast after the bell delivery models into existing data systems and make the information publicly available.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1508-S.SL.pdf?cite=2018%20c%208%20§%204[2018 c 8 § 4]; ]

== 28A.235.230 - Breakfast after the bell program—Funding for implementation. (Expires June 30, 2028.)
The office of the superintendent of public instruction, school districts, and affected schools shall implement sections 2 through 4, chapter 8, Laws of 2018 only in years in which funding is specifically provided for the purposes of chapter 8, Laws of 2018, referencing chapter 8, Laws of 2018 by bill or chapter number or statutory references, in a biennial or supplemental operating budget.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1508-S.SL.pdf?cite=2018%20c%208%20§%206[2018 c 8 § 6]; ]

== 28A.235.240 - Breakfast after the bell program—Analysis.
. The joint legislative audit and review committee shall conduct an analysis of breakfast after the bell programs established in schools in accordance with RCW 28A.235.210. The analysis of the schools establishing breakfast after the bell programs shall include a review of any changes in student:

.. Tardiness and absenteeism;

.. Suspensions;

.. Reported illnesses and visits to nurses' offices;

.. Results on standardized tests; and

.. Graduation rates.

. The analysis shall also include a review of the outcomes of similar programs or efforts in other states.

. The office of the superintendent of public instruction and the education and research data center of the office of financial management shall assist in providing any data required to conduct the analysis. The analysis, including any findings and recommendations, must be completed and submitted to the superintendent of public instruction and, in accordance with RCW 43.01.036, the education committees of the house of representatives and the senate by December 1, 2026.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1508-S.SL.pdf?cite=2018%20c%208%20§%209[2018 c 8 § 9]; ]

== 28A.235.250 - Free or reduced-price meals—Applications.
. [Empty]
.. Except as provided otherwise in subsection (2) of this section, each school that participates in the national school lunch program, the school breakfast program, or both, shall annually distribute and collect an application for all households of children in kindergarten through grade twelve to determine student eligibility for free or reduced-price meals. If a parent or guardian of a student needs assistance with application materials in a language other than English, the school shall offer appropriate assistance to the parent or guardian.

.. If a student who, based on information available to the school, is likely eligible for free or reduced-price meals but has not submitted an application to determine eligibility, the school shall, in accordance with the authority granted under 7 C.F.R. Sec. 245.6(d), complete and submit the application for the student.

. Subsection (1) of this section does not apply to a school that provides free meals to all students in a year in which the school does not collect applications to determine student eligibility for free or reduced-price meals.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2610-S.SL.pdf?cite=2018%20c%20271%20§%201[2018 c 271 § 1]; ]

== 28A.235.260 - Free or reduced-price meals—Student assistance.
If a student has not paid for five or more previous meals, the school shall:

. Determine whether the student is categorically eligible for free meals;

. If no application has been submitted for the student to determine his or her eligibility for free or reduced-price meals, make no fewer than two attempts to contact the student's parent or guardian to have him or her submit an application; and

. Have a principal, assistant principal, or school counselor contact the parent or guardian for the purpose of: (a) Offering assistance with completing an application to determine the student's eligibility for free or reduced-price meals; (b) determining whether there are any household issues that may prevent the student from having sufficient funds for school meals; and (c) offering any appropriate assistance.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2610-S.SL.pdf?cite=2018%20c%20271%20§%203[2018 c 271 § 3]; ]

== 28A.235.270 - Free or reduced-price meals—School prohibitions.
. No school or school district personnel or school volunteer may:

.. Take any action that would publicly identify a student who cannot pay for a school meal or for meals previously served to the student, including but not limited to requiring the student to wear a wristband, hand stamp, or other identifying marker, or by serving the student an alternative meal;

.. Require a student who cannot pay for a school meal or for meals previously served to the student to perform chores or other actions in exchange for a meal or for the reduction or elimination of a school meal debt, unless all students perform similar chores or work;

.. Require a student to dispose of an already served meal because of the student's inability to pay for the meal or because of money owed for meals previously served to the student;

.. Allow any disciplinary action that is taken against a student to result in the denial or delay of a nutritionally adequate meal to the student; or

.. Require a parent or guardian to pay fees or costs in excess of the actual amounts owed for meals previously served to the student.

. Communications from a school or school district about amounts owed for meals previously served to a student under the age of fifteen may only be directed to the student's parent or guardian. Nothing in this subsection prohibits a school or school district from sending a student home with a notification that is addressed to the student's parent or guardian.

. [Empty]
.. A school district shall notify a parent or guardian of the negative balance of a student's school meal account no later than ten days after the student's school meal account has reached a negative balance. Within thirty days of sending this notification, the school district shall exhaust all options to directly certify the student for free or reduced-price meals. Within these thirty days, while the school district is attempting to certify the student for free or reduced-price meals, the student may not be denied access to a school meal unless the school district determines that the student is ineligible for free or reduced-price meals.

.. If the school district is unable to directly certify the student for free or reduced-price meals, the school district shall provide the parent or guardian with a paper copy of or an electronic link to an application for free or reduced-price meals with the notification required by (a) of this subsection and encourage the parent or guardian to submit the application.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2610-S.SL.pdf?cite=2018%20c%20271%20§%204[2018 c 271 § 4]; ]

== 28A.235.280 - Free school meals—Systems to identify students.
. Local liaisons for homeless children and youths designated by districts in accordance with the federal McKinney-Vento homeless assistance act 42 U.S.C. Sec. 11431 et seq. must improve systems to identify homeless students and coordinate with the applicable school nutrition program to ensure that each homeless student has proper access to free school meals and that applicable accountability and reporting requirements are satisfied.

. Schools and school districts shall improve systems to identify students in foster care, runaway students, and migrant students to ensure that each student has proper access to free school meals and that applicable accountability and reporting requirements are satisfied.

. At least monthly, schools and school districts shall directly certify students for free school meals if the students qualify because of enrollment in assistance programs, including but not limited to the supplemental nutrition assistance program, the temporary assistance for needy families, and medicaid.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2610-S.SL.pdf?cite=2018%20c%20271%20§%202[2018 c 271 § 2]; ]

== 28A.235.290 - Department of agriculture community eligibility provision—Plan to increase participation—Reports.
. The office of the superintendent of public instruction shall develop and implement a plan to increase the number of schools participating in the United States department of agriculture community eligibility provision for the 2018-19 school year and subsequent years. The office shall work jointly with community-based organizations and national experts focused on hunger and nutrition and familiar with the community eligibility provision, at least two school representatives who have successfully implemented community eligibility, and the state agency responsible for medicaid direct certification. The plan must describe how the office of the superintendent of public instruction will:

.. Identify and recruit eligible schools to implement the community eligibility provision, with the goal of increasing the participation rate of eligible schools to at least the national average;

.. Provide comprehensive outreach and technical assistance to school districts and schools to implement the community eligibility provision;

.. Support breakfast after the bell programs authorized by the legislature to adopt the community eligibility provision;

.. Work with school districts to group schools in order to maximize the number of schools implementing the community eligibility provision; and

.. Determine the maximum percentage of students eligible for free meals where participation in the community eligibility provision provides the most support for a school, school district, or group of schools.

. Until June 30, 2021, the office of the superintendent of public instruction shall convene the organizations working jointly on the plan monthly to report on the status of the plan and coordinate outreach and technical assistance efforts to schools and school districts. In completing the duties required by this subsection (2), the office of the superintendent of public instruction and the organizations working jointly on the plan shall also, by December 1, 2020, examine the impacts to schools and districts that can result from participation in the community eligibility provision and identify approaches to addressing those impacts.

. Beginning in 2018, the office of the superintendent of public instruction shall report annually the number of schools that have implemented the community eligibility provision to the legislature by December 1st of each year. The report shall identify:

.. Any barriers to implementation;

.. Recommendations on policy and legislative solutions to overcome barriers to implementation;

.. Reasons potentially eligible schools and school districts decide not to adopt the community eligibility provision; and

.. Approaches in other states to adopting the community eligibility provision.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2660-S.SL.pdf?cite=2020%20c%20288%20§%202[2020 c 288 § 2]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1151-S.SL.pdf?cite=2019%20c%20208%20§%202[2019 c 208 § 2]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2610-S.SL.pdf?cite=2018%20c%20271%20§%206[2018 c 271 § 6]; ]

== 28A.235.300 - Department of agriculture community eligibility provision—Required participation—Exemption.
. Except as provided otherwise by this section, each school with students in or below grade eight that has an identified student percentage of at least sixty-two and one-half percent, as determined annually by April 1st, must participate in the United States department of agriculture's community eligibility provision in the subsequent school year and throughout the duration of the community eligibility provision's four-year cycle.

. Schools that, through an arrangement with a local entity, provide meals to all students and at no costs to the students are exempt from the requirements of this section.

. For the purposes of this section, "identified student" means a student who is directly certified for free school meals based on the student's participation in other means-tested assistance programs, and students who are categorically eligible for free school meals without an application and not subject to income verification.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2660-S.SL.pdf?cite=2020%20c%20288%20§%203[2020 c 288 § 3]; ]

