= 28A.190 - Residential education programs.
:toc:

== 28A.190.005 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Institutional education facility" means residential habilitation and child study and treatment centers operated by the department of social and health services, state long-term juvenile institutions operated by the department of children, youth, and families, state-operated community facilities, county juvenile detention centers, and facilities of the department of corrections that incarcerate juveniles committed as adults.

. "Institutional education program" means the program of education that is provided to youth in institutional education facilities as a mandatory component of the program of basic education under RCW 28A.150.200.

. "Institutional education provider" or "provider" means a school district, educational service district, or other entity providing education services to youth in an institutional education facility.

. "Postresident youth" means a person who is under the age of 21 and a former resident of an institutional education facility. A postresident youth may be a public school student or a person who is eligible to be a public school student but who is not enrolled in a school or otherwise receiving basic education services.

. "Residential school" means the following institutional education facilities: Green Hill school, Naselle Youth Camp, Echo Glen, Lakeland Village, Rainier school, Yakima Valley school, Fircrest school, the Child Study and Treatment Center and Secondary School of western state hospital, and other schools, camps, and centers established by the department of social and health services or the department of children, youth, and families for the diagnosis, confinement, and rehabilitation of juveniles committed by the courts or for the care and treatment of persons who are exceptional in their needs by reason of mental or physical deficiency. "Residential school" does not include the state schools for the blind, the Washington state center for childhood deafness and hearing loss, or adult correctional institutions.

. "School district" has the same meaning as in RCW 28A.315.025 and includes any educational service district that has entered into an agreement to provide a program of education for residents at an institutional education facility on behalf of the school district as a cooperative service program pursuant to RCW  28A.310.180.

. "Youth" means a person who is under the age of 21 who is a resident of an institutional education facility. A youth may be a public school student or a person who is eligible to be a public school student but who is not enrolled in a school or otherwise receiving basic education services.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1295-S2.SL.pdf?cite=2021%20c%20164%20§%203[2021 c 164 § 3]; ]

== 28A.190.010 - Educational program for juveniles in detention facilities.
A program of education shall be provided for by the department of social and health services or the department of children, youth, and families and the several school districts of the state for common school-age persons who have been admitted to facilities staffed and maintained or contracted pursuant to RCW 13.40.320 by the department of social and health services or the department of children, youth, and families for the education and treatment of juveniles who have been diverted or who have been found to have committed a juvenile offense. The division of duties, authority, and liabilities of the department of social and health services or the department of children, youth, and families and the several school districts of the state respecting the educational programs shall be the same in all respects as set forth in this chapter respecting programs of education for state residential school residents. For the purposes of this section, the term "residential school" or "schools" as used in this chapter shall be construed to mean a facility staffed and maintained by the department of social and health services or the department of children, youth, and families or a program established under RCW 13.40.320, for the education and treatment of juvenile offenders on probation or parole. Nothing in this section shall prohibit a school district from utilizing the services of an educational service district subject to RCW 28A.310.180.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20720[2017 3rd sp.s. c 6 § 720]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2276.SL.pdf?cite=2014%20c%20157%20§%202[2014 c 157 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2495.SL.pdf?cite=1996%20c%2084%20§%201[1996 c 84 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20170[1990 c 33 § 170]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c98.pdf?cite=1983%20c%2098%20§%203[1983 c 98 § 3]; ]

== 28A.190.030 - Educational programs for residential school residents—School district to conduct—Scope of duties and authority.
Each school district within which there is located a residential school shall, singly or in concert with another school district pursuant to RCW 28A.335.160 and 28A.225.250 or pursuant to chapter 39.34 RCW, conduct a program of education, including related student activities, for residents of the residential school. Except as otherwise provided for by contract pursuant to RCW 28A.190.050, the duties and authority of a school district and its employees to conduct such a program shall be limited to the following:

. The employment, supervision and control of administrators, teachers, specialized personnel and other persons, deemed necessary by the school district for the conduct of the program of education;

. The purchase, lease or rental and provision of textbooks, maps, audiovisual equipment, paper, writing instruments, physical education equipment and other instructional equipment, materials and supplies, deemed necessary by the school district for the conduct of the program of education;

. The development and implementation, in consultation with the superintendent or chief administrator of the residential school or his or her designee, of the curriculum;

. The conduct of a program of education, including related student activities, for residents who are three years of age and less than twenty-one years of age, and have not met high school graduation requirements as now or hereafter established by the state board of education and the school district which includes:

.. Not less than one hundred and eighty school days each school year;

.. Special education pursuant to RCW 28A.155.010 through 28A.155.100, and vocational education, as necessary to address the unique needs and limitations of residents; and

.. Such courses of instruction and school related student activities as are provided by the school district for nonresidential school students to the extent it is practical and judged appropriate for the residents by the school district after consultation with the superintendent or chief administrator of the residential school: PROVIDED, That a preschool special education program may be provided for residential school students with disabilities;

. The control of students while participating in a program of education conducted pursuant to this section and the discipline, suspension or expulsion of students for violation of reasonable rules of conduct adopted by the school district; and

. The expenditure of funds for the direct and indirect costs of maintaining and operating the program of education that are appropriated by the legislature and allocated by the superintendent of public instruction for the exclusive purpose of maintaining and operating residential school programs of education, and funds from federal and private grants, bequests and gifts made for the purpose of maintaining and operating the program of education.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5276.SL.pdf?cite=1995%20c%2077%20§%2019[1995 c 77 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20172[1990 c 33 § 172]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c341.pdf?cite=1985%20c%20341%20§%2013[1985 c 341 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c160.pdf?cite=1984%20c%20160%20§%203[1984 c 160 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c217.pdf?cite=1979%20ex.s.%20c%20217%20§%202[1979 ex.s. c 217 § 2]; ]

== 28A.190.040 - Educational programs for residential school residents—Duties and authority of department of children, youth, and families and residential school superintendent.
The duties and authority of the department of social and health services or the department of children, youth, and families and of each superintendent or chief administrator of a residential school to support each program of education conducted by a school district pursuant to RCW 28A.190.030, shall include the following:

. The provision of transportation for residential school students to and from the sites of the program of education through the purchase, lease or rental of school buses and other vehicles as necessary;

. The provision of safe and healthy building and playground space for the conduct of the program of education through the construction, purchase, lease or rental of such space as necessary;

. The provision of furniture, vocational instruction machines and tools, building and playground fixtures, and other equipment and fixtures for the conduct of the program of education through construction, purchase, lease or rental as necessary;

. The provision of heat, lights, telephones, janitorial services, repair services, and other support services for the vehicles, building and playground spaces, equipment and fixtures provided for in this section;

. The employment, supervision and control of persons to transport students and to maintain the vehicles, building and playground spaces, equipment and fixtures, provided for in this section;

. Clinical and medical evaluation services necessary to a determination by the school district of the educational needs of residential school students; and

. Such other support services and facilities as are reasonably necessary for the conduct of the program of education.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20722[2017 3rd sp.s. c 6 § 722]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20173[1990 c 33 § 173]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c217.pdf?cite=1979%20ex.s.%20c%20217%20§%203[1979 ex.s. c 217 § 3]; ]

== 28A.190.050 - Educational programs for residential school residents—Contracts between school district and department of children, youth, and families—Scope.
Each school district required to conduct a program of education pursuant to RCW 28A.190.030, and the department of social and health services and the department of children, youth, and families shall hereafter negotiate and execute a written contract for each school year or such longer period as may be agreed to which delineates the manner in which their respective duties and authority will be cooperatively performed and exercised, and any disputes and grievances resolved. Any such contract may provide for the performance of duties by a school district in addition to those set forth in RCW 28A.190.030 (1) through (5), including duties imposed upon the department of social and health services and the department of children, youth, and families and their agents pursuant to RCW 28A.190.040: PROVIDED, That funds identified in RCW 28A.190.030(6) and/or funds provided by the department of social and health services and the department of children, youth, and families are available to fully pay the direct and indirect costs of such additional duties and the district is otherwise authorized by law to perform such duties in connection with the maintenance and operation of a school district.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20723[2017 3rd sp.s. c 6 § 723]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20174[1990 c 33 § 174]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c217.pdf?cite=1979%20ex.s.%20c%20217%20§%204[1979 ex.s. c 217 § 4]; ]

== 28A.190.060 - Educational programs for residential school residents—Department of social and health services and department of children, youth, and families to give notice when need for reduction of staff—Liability upon failure.
The department of social and health services and the department of children, youth, and families shall provide written notice on or before April 15th of each school year to the superintendent of each school district conducting a program of education pursuant to this chapter of any foreseeable residential school closure, reduction in the number of residents, or any other cause for a reduction in the school district's staff for the next school year. In the event the department of social and health services and the department of children, youth, and families fail to provide notice as prescribed by this section, the departments shall be liable and responsible for the payment of the salary and employment related costs for the next school year of each school district employee whose contract the school district would have nonrenewed but for the failure of the departments to provide notice.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20724[2017 3rd sp.s. c 6 § 724]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2276.SL.pdf?cite=2014%20c%20157%20§%204[2014 c 157 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20175[1990 c 33 § 175]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c217.pdf?cite=1979%20ex.s.%20c%20217%20§%205[1979 ex.s. c 217 § 5]; ]

== 28A.190.070 - Students in residential schools, detention facilities, and adult correctional facilities—Funding—Procedures for reporting enrollment.
Beginning in the 2021-22 school year, enrollments for students in residential schools as defined in RCW 28A.190.005, for juveniles in detention facilities as identified by RCW 28A.190.010, and for individuals under the age of 18 who are incarcerated in adult correctional facilities may be funded above one full-time equivalent, provided that enrollments above one full-time equivalent allow for participation in dropout reengagement programs as defined in RCW 28A.175.105. State funding for enrollments in dropout reengagement programs in addition to institutional education facility enrollments must be allocated pursuant to RCW 28A.175.110 excluding administrative fees. The office of the superintendent of public instruction shall develop procedures for school districts to report student enrollment in institutional education facilities and dropout reengagement programs.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1295-S2.SL.pdf?cite=2021%20c%20164%20§%206[2021 c 164 § 6]; ]

== 28A.190.080 - Institutional education providers—Professional development.
. Institutional education providers shall annually deliver to all staff providing an institutional education program one day of professional development that builds pedagogical strategies to navigate the intersectionality of factors impacting student learning, including trauma, and physical, mental, and behavioral health in order to achieve academic milestone progression. At a minimum, the professional development must include training on the following topics:

.. The cognitive, psychosocial, and emotional development of adolescents;

.. Mental and behavioral health literacy;

.. The complex needs of students involved in the juvenile justice system, including the trauma associated with incarceration or voluntary or involuntary commitment in a long-term psychiatric inpatient program;

.. Racial literacy and cultural competency, as defined in RCW 28A.410.260; and

.. Working with adolescents with many adverse childhood experiences.

. In addition to the professional learning allocations provided in RCW 28A.150.415, the legislature shall provide and the superintendent of public instruction shall allocate to institutional education providers one professional learning day of funding to provide the professional development required under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1295-S2.SL.pdf?cite=2021%20c%20164%20§%208[2021 c 164 § 8]; ]

== 28A.190.090 - Students in institutional education facilities—Requirements for the department of children, youth, and families.
With respect to students in institutional education facilities governed by this chapter, the department of children, youth, and families must:

. Identify data needed by the department and institutional education facilities to evaluate the facilities' administrative and operational role in providing education to students and supporting students' educational outcomes. This data must include attendance, discipline rates, course and certificate completion rates, and other educational metrics;

. Analyze, and make a plan to resolve, department and institutional education facilities policies and practices that suspend the provision of educational services to a student as a disciplinary action, so that students are never denied the opportunity to engage in educational activities; and

. Review and resolve department and institutional education facility policies and practices that create barriers to students participating in meaningful learning opportunities, for example, career and technical education and postsecondary opportunities, in whatever location and format those opportunities are provided.

. In meeting the requirements of this section, the department of children, youth, and families must seek input from institutional education providers.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1295-S2.SL.pdf?cite=2021%20c%20164%20§%209[2021 c 164 § 9]; ]

== 28A.190.100 - Education of youth in institutional education facilities and postresident youth—Rules.
. The legislature intends to ensure that institutional education facilities include efficient systems to minimize learning loss and maximize credit accrual during transitions for youth and postresident youth. The legislature intends also for the report required by this section to inform its understanding of policy and funding changes that may be necessary to accomplish the objective of improving institutional education programs and outcomes.

. The office of the superintendent of public instruction shall modify or establish requirements and supports for the provision of public education to youth and postresident youth. In meeting the requirements of this section, the office of the superintendent of public instruction shall:

.. Adopt rules requiring institutional education providers at state long-term juvenile institutions and state-operated community facilities to conduct an individualized education program review for each newly admitted youth who either does not have an individualized education program or does not have an individualized education program that has been reviewed in a meeting with the youth, parent or guardian, and applicable school personnel in the previous 12 months;

.. Adopt rules requiring institutional education providers to, upon admission of a youth to an institutional education facility, conduct a review and assessment of needed services for each facility transition the youth experiences within the juvenile justice system. Rules adopted in accordance with this subsection (2)(b) do not apply to institutional education providers at facilities operated by or under the jurisdiction of the department of social and health services; and

.. Adopt, for youth in state long-term juvenile institutions and state-operated community facilities, rules to implement accountability measures for special education services delivered by institutional education providers, including the establishment of mediation and appeals options related to special education services that recognize the unique situation of youth and postresident youth.

. A summary of any adopted or pending rules developed in accordance with this section must be submitted to the appropriate committees of the legislature in accordance with RCW 43.01.036 by November 1, 2021, in time for any needed legislative action during the 2022 regular legislative session.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1295-S2.SL.pdf?cite=2021%20c%20164%20§%2011[2021 c 164 § 11]; ]

== 28A.190.110 - Institutional education programs—Data—Recommendations.
. The office of the superintendent of public instruction shall annually collect and post on its website data related to institutional education programs, disaggregated by gender, race, ethnicity, and age, including data on:

.. Individualized education programs;

.. Access to relevant instruction that is aligned with the youth's high school and beyond plan and any unmet graduation requirements;

.. Student attendance;

.. Metrics of student education status upon the beginning of residency in an institutional education facility;

.. Student education progress during residency in an institutional education facility;

.. Student education attainment during residency in an institutional education facility; and

.. Long-term education and workforce outcomes of youth in and released from institutional education facilities as provided annually by the education data center under RCW 43.41.400.

. [Empty]
.. The office of the superintendent of public instruction shall also annually recommend modifications to the state board of education for changes to annual school improvement plan requirements in WAC 180-16-220 that would allow plans for state long-term juvenile institutions to be formatted for the specific needs and circumstances of institutional settings. In meeting the requirements of this subsection (2)(a), the office of the superintendent of public instruction shall seek input from institutional education providers and the department of children, youth, and families.

.. In meeting the requirements of this section, the office of the superintendent of public instruction may make recommendations to the state board of education for changes to annual school improvement plan requirements based upon data collected under this section, other provisions of law, or both.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1295-S2.SL.pdf?cite=2021%20c%20164%20§%2012[2021 c 164 § 12]; ]

== 28A.190.120 - Institutional education programs—School district board of directors.
The office of the superintendent of public instruction must provide a copy of the disaggregated data provided under RCW 28A.190.110(1) to the board of directors of each school district that provides education services to youth and postresident youth for the purpose of giving the board the opportunity to:

. Review the performance of the institutional education provider; and

. Make changes to annual school improvement plans required by WAC 180-16-220, or other policies and procedures as necessary to improve youth and postresident youth outcomes.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1295-S2.SL.pdf?cite=2021%20c%20164%20§%2013[2021 c 164 § 13]; ]

== 28A.190.130 - Institutional educational system—Recommendations—Designated entity—Advisory group—Report. (Expires June 30, 2023.)
. [Empty]
.. The office of the superintendent of public instruction and the department of children, youth, and families shall jointly develop recommendations for the establishment, implementation, and funding of a reformed institutional education system that successfully meets the education and support needs of persons in and released from secure settings. Recommendations developed under this subsection (1) must be based on the foundational concept that every student can succeed if given the necessary supports. With the exception of funding recommendations required by (a)(ii) of this subsection (1), the recommendations developed under this subsection (1) should be directed toward meeting the education needs of persons who are in or have been released from state long-term juvenile institutions and community facilities operated by the department of children, youth, and families, county juvenile detention centers, and facilities of the department of corrections that incarcerate juveniles committed as adults. The recommendations must address:

... The establishment of an organizational and accountability structure for institutional education that is focused on meeting complex student needs and improving student outcomes;

... The establishment of an equitable, long-term funding model for institutional education that sustainably supports the organizational and accountability structure established under (a)(i) of this subsection (1); and

... The development of a regular and ongoing review of system performance and education outcomes.

.. The recommendations developed under this subsection (1) must also include the following:

... The content and structure of common education, information, and support systems that would include a common, culturally competent curriculum, improve system efficacy, and minimize the negative academic impacts of transitions;

... A coordinated staffing model for institutional education facility and institutional education provider operations and effectiveness in meeting student needs, and a mechanism for developing subsequent recommendations for improvements to the model;

... Practices to ensure that there is a robust program of education advocates for youth in all institutional education facilities;

... Practices for shared data tracking and goal setting for youth progress and learning needs;

.. Promoting the effective delivery of tiered supports in institutional education facilities in coordination with state and county facility operators, institutional education providers, and community-based organizations delivering those services;

.. Promoting the development of an operational safety strategy for safe learning environments for students and staff;

.. Promoting operations that prioritize education delivery;

.. Maximizing youth and postresident youth access to: (A) Career and technical education and postsecondary education pathways that occur at institutional education facilities and at off-site locations; and (B) mastery-based learning that leads to credit accrual and graduation pathways;

... Establishing new or modified requirements and procedures for the successful release of youth from institutional education facilities by recommending an effective team-based transition process with identified preresident and postresident transition services and supports that include, but are not limited to, basic needs, social-emotional support, and academic support;

.. Establishing and supporting youth advisory, leadership, and mentoring programs to ensure pathways for youth and postresident youth involvement and development;

.. Identifying and establishing culturally responsive parent engagement strategies that support the education and well-being of youth and postresident youth and families;

.. Examining and expanding opportunities to include enrichment activities in institutional education programs and offer enrichment opportunities that promote academic and career goals; and

.. Developing partnerships with postsecondary institutions, career and technical education programs, and community-based organizations, and identify ways to incorporate those partnerships into education services delivered by institutional education providers.

.. In developing the recommendations required by this subsection (1), the office of the superintendent of public instruction and the department of children, youth, and families shall consult with the advisory group established in subsection (3) of this section.

. The superintendent of public instruction and the secretary of the department of children, youth, and families shall, by August 15, 2021, jointly designate an entity to facilitate the process of developing recommendations required by subsection (1) of this section, and the advisory group established in subsection (3) of this section. The office of the superintendent of public instruction is responsible for contracts or other agreements necessary to secure the services of the designated entity. The designated entity must: (a) Be a nonprofit and nonpartisan organization with content expertise in improving education for incarcerated young people, including education program delivery, system structure, accountability, and school finance; and (b) have experience facilitating complex cross-agency facilitation.

. [Empty]
.. The institutional education structure and accountability advisory group is established for the purpose of providing advice, assistance, and information to the office of the superintendent of public instruction and the department of children, youth, and families in meeting the requirements of subsection (1) of this section. The advisory group must consist of representatives from the following, but other members may be added by request of the superintendent of public instruction or the secretary of the department of children, youth, and families:

... The state board of education;

... The department of social and health services;

... A statewide organization representing counties;

... The administrative office of the courts;

.. The office of the education ombuds;

.. The educational opportunity gap oversight and accountability committee;

.. A statewide organization representing teachers;

.. A statewide organization representing classified education staff;

... Nonprofit organizations representing the interest of youth and families involved in the juvenile justice system;

.. Persons who are or have been involved in the juvenile justice system and their families; and

.. A statewide organization representing state employees.

.. In recognition of the need to ensure representation on the advisory group, persons serving under (a)(x) of this subsection are eligible for travel expense reimbursement. Other members of the advisory group are not entitled to expense reimbursement.

. Staff support for the advisory group must be provided by the entity selected under subsection (2) of this section.

. [Empty]
.. Recommendations required by this section must, in accordance with RCW 43.01.036, be provided to the governor and the education and fiscal committees of the house of representatives and the senate, by November 1, 2022. The recommendations should include a plan and a phased timeline for their implementation in different types of institutional education facilities, including state long-term juvenile institutions, state-operated community facilities, residential habilitation centers, and county juvenile detention centers.

.. By December 15, 2021, the office of the superintendent of public instruction and the department of children, youth, and families shall, in accordance with RCW 43.01.036, provide an interim report on progress made in achieving the requirements of this section to the governor and the education and fiscal committees of the house of representatives and the senate.

. This section expires June 30, 2023.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1295-S2.SL.pdf?cite=2021%20c%20164%20§%2014[2021 c 164 § 14]; ]

