= 28A.193 - Education programs for juvenile inmates.
:toc:

== 28A.193.005 - Intent—Findings.
The legislature intends to provide for the operation of education programs for the department of corrections' juvenile inmates. School districts, educational service districts, or any combination thereof should be the primary providers of the education programs. However, the legislature does not intend to preclude community and technical colleges, four-year institutions of higher education, or other qualified entities from contracting to provide all or part of these education programs if no school district or educational service district is willing to operate all or part of the education programs.

The legislature finds that this chapter fully satisfies any constitutional duty to provide education programs for juvenile inmates in adult correctional facilities. The legislature further finds that biennial appropriations for education programs under this chapter amply provide for any constitutional duty to educate juvenile inmates in adult correctional facilities.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6600-S.SL.pdf?cite=1998%20c%20244%20§%201[1998 c 244 § 1]; ]

== 28A.193.010 - Operation of program by school district or educational service district.
Any school district or educational service district may operate all or any portion of an education program for juveniles in accordance with this chapter, notwithstanding the fact the services or benefits provided extend beyond the geographic boundaries of the school district or educational service district providing the service.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6600-S.SL.pdf?cite=1998%20c%20244%20§%202[1998 c 244 § 2]; ]

== 28A.193.020 - Solicitation for education provider—Selection of provider—Operation of program by educational service district.
The superintendent of public instruction shall solicit an education provider for the department of corrections' juvenile inmates within sixty days as follows:

. The superintendent of public instruction shall notify and solicit proposals from all interested and capable school districts, educational service districts, institutions of higher education, private contractors, or any combination thereof. The notice shall describe the proposed education program's requirements and the appropriated amount. The selection of an education provider shall be in the following order:

.. The school district where there is an educational site for juveniles in an adult correctional facility maintained by the state department of corrections has first priority to operate an education program for inmates at that site. The district may elect to operate an education program by itself or with another school district, educational service district, institution of higher education, private contractor, or any combination thereof. If the school district elects not to exercise its priority, it shall notify the superintendent of public instruction within thirty calendar days of the day of solicitation.

.. The educational service district where there is an educational site for juveniles in an adult correctional facility maintained by the state department of corrections has second priority to operate an education program for inmates at that site. The educational service district may elect to do so by itself or with a school district, another educational service district, institution of higher education, private contractor, or any combination thereof. If the educational service district elects not to exercise its priority, it shall notify the superintendent of public instruction within forty-five calendar days of the day of solicitation.

.. If neither the school district nor the educational service district chooses to operate an education program for inmates as provided for in (a) and (b) of this subsection, the superintendent of public instruction may contract with an entity, including, but not limited to, school districts, educational service districts, institutions of higher education, private contractors, or any combination thereof, within sixty calendar days of the day of solicitation. The selected entity may operate an education program by itself or with another school district, educational service district, institution of higher education, or private contractor, or any combination thereof.

. If the superintendent of public instruction does not contract with an interested entity within sixty days of the day of solicitation, the educational service district where there is an educational site for juveniles in an adult correctional facility maintained by the state department of corrections shall begin operating the education program for inmates at the site within ninety days from the day of solicitation in subsection (1) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6600-S.SL.pdf?cite=1998%20c%20244%20§%203[1998 c 244 § 3]; ]

== 28A.193.030 - Duties and authority of education provider—Continuation in program by students age eighteen.
Except as otherwise provided for by contract under RCW 28A.193.060, the duties and authority of a school district, educational service district, institution of higher education, or private contractor to provide for education programs under this chapter are limited to the following:

. Employing, supervising, and controlling administrators, teachers, specialized personnel, and other persons necessary to conduct education programs, subject to security clearance by the department of corrections;

. Purchasing, leasing, or renting and providing textbooks, maps, audiovisual equipment, paper, writing instruments, physical education equipment, and other instructional equipment, materials, and supplies deemed necessary by the provider of the education programs;

. Conducting education programs for inmates under the age of eighteen in accordance with program standards established by the superintendent of public instruction. The education provider shall develop the curricula, instructional methods, and educational objectives of the education programs, subject to applicable requirements of state and federal law. The department of corrections shall establish behavior standards that govern inmate participation in education programs, subject to applicable requirements of state and federal law;

. Students age eighteen who have participated in an education program governed by this chapter may continue in the program with the permission of the department of corrections and the education provider, under the rules adopted by the superintendent of public instruction.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6600-S.SL.pdf?cite=1998%20c%20244%20§%204[1998 c 244 § 4]; ]

== 28A.193.040 - Education providers—Additional authority and limitations.
School districts and educational service districts providing an education program to juvenile inmates in an adult corrections [correctional] facility, notwithstanding that their geographical boundaries do not include the facility, may:

. Award appropriate diplomas or certificates to inmates who successfully complete graduation requirements;

. Spend only funds appropriated by the legislature and allocated by the superintendent of public instruction for the exclusive purpose of maintaining and operating education programs under this chapter, including direct and indirect costs of maintaining and operating the education programs, and funds from federal and private grants, bequests, and gifts made for that purpose. School districts may not expend excess tax levy proceeds authorized for school district purposes to pay costs incurred under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6600-S.SL.pdf?cite=1998%20c%20244%20§%205[1998 c 244 § 5]; ]

== 28A.193.050 - Required support of education programs.
To support each education program under this chapter, the department of corrections and each superintendent or chief administrator of a correction facility shall:

. Through construction, lease, or rental of space, provide necessary building and exercise spaces for the education program that is secure, separate, and apart from space occupied by nonstudent inmates;

. Through construction, lease, or rental, provide vocational instruction machines; technology and supporting equipment; tools, building, and exercise facilities; and other equipment and fixtures deemed necessary by the department of corrections to conduct the education program;

. Provide heat, lights, telephone, janitorial services, repair services, and other support services for the building and exercise spaces, equipment, and fixtures provided under this section;

. Employ, supervise, and control security staff to safeguard agents of the education providers and inmates while engaged in educational and related activities conducted under this chapter;

. Provide clinical and medical evaluation services necessary for a determination by the education provider of the educational needs of inmates; and

. Provide such other support services and facilities as are reasonably necessary to conduct the education program.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6600-S.SL.pdf?cite=1998%20c%20244%20§%206[1998 c 244 § 6]; ]

== 28A.193.060 - Contract between education providers and department of corrections.
Each education provider under this chapter and the department of corrections shall negotiate and execute a written contract for each school year or such longer period as may be agreed to that delineates the manner in which their respective duties and authority will be cooperatively performed and exercised, and any disputes and grievances resolved through mediation, and if necessary, arbitration. Any such contract may provide for the performance of duties by an education provider in addition to those set forth in this chapter, including duties imposed upon the department of corrections and its agents under RCW 28A.193.050 if supplemental funding provided by the department of corrections is available to fully pay the direct and indirect costs of these additional duties.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6600-S.SL.pdf?cite=1998%20c%20244%20§%207[1998 c 244 § 7]; ]

== 28A.193.070 - Education site closures or reduction in services—Notice to the superintendent of public instruction and education providers—Liability for failure to provide notice—Alternative dispute resolution.
By April 15th of each school year, the department of corrections shall provide written notice to the superintendent of public instruction and education providers operating programs under this chapter of any reasonably foreseeable education site closures, reductions in the number of inmates or education services, or any other cause for a reduction in certificated or classified staff the next school year. In the event the department of corrections fails to provide notice as required by this section, the department is liable and responsible for the payment of the salary and employment-related costs for the next school year of each employee whose contract would or could have been nonrenewed but for the failure of the department to provide notice. Disputes arising under this section shall be resolved in accordance with the alternative dispute resolution method or methods specified in the contract required by RCW 28A.193.060.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6600-S.SL.pdf?cite=1998%20c%20244%20§%208[1998 c 244 § 8]; ]

== 28A.193.080 - Allocation of money—Accountability requirements—Rules.
The superintendent of public instruction shall:

. Allocate money appropriated by the legislature to administer and provide education programs under this chapter to school districts, educational service districts, and other education providers selected under RCW 28A.193.020 that have assumed the primary responsibility to administer and provide education programs under this chapter. The allocation of moneys to any private contractor is contingent upon and must be in accordance with a contract between the private contractor and the department of corrections; and

. Adopt rules in accordance with chapter 34.05 RCW that establish reporting, program compliance, audit, and such other accountability requirements as are reasonably necessary to implement this chapter and related provisions of the biennial operating act effectively.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6600-S.SL.pdf?cite=1998%20c%20244%20§%209[1998 c 244 § 9]; ]

== 28A.193.900 - Effective date—1998 c 244 §§ 1-9 and 11-15.
Sections 1 through 9 and 11 through 15 of this act are necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and take effect immediately [March 30, 1998].

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6600-S.SL.pdf?cite=1998%20c%20244%20§%2017[1998 c 244 § 17]; ]

