= 28A.170 - Substance abuse awareness program.
:toc:

== 28A.170.050 - Advisory committee—Members—Duties.
The superintendent of public instruction shall appoint a substance abuse advisory committee comprised of: Representatives of certificated and classified staff; administrators; parents; students; school directors; the bureau of alcohol and substance abuse within the department of social and health services; the traffic safety commission; and county coordinators of alcohol and drug treatment. The committee shall advise the superintendent on matters of local program development, coordination, and evaluation.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1288.SL.pdf?cite=1997%20c%2013%20§%203[1997 c 13 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c518.pdf?cite=1987%20c%20518%20§%20209[1987 c 518 § 209]; ]

== 28A.170.075 - Findings—Intent.
. The legislature finds that the provision of drug and alcohol counseling and related prevention and intervention services in schools will enhance the classroom environment for students and teachers, and better enable students to realize their academic and personal potentials.

. The legislature finds that it is essential that resources be made available to school districts to provide early drug and alcohol prevention and intervention services to students and their families; to assist in referrals to treatment providers; and to strengthen the transition back to school for students who have had problems of drug and alcohol abuse.

. Substance abuse awareness programs funded under this chapter do not fall within the definition of basic education for purposes of Article IX of the state Constitution and the state's funding duty thereunder.

. The legislature intends to provide grants for drug and alcohol abuse prevention and intervention in schools, targeted to those schools with the highest concentrations of students at risk.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5169-S.SL.pdf?cite=1995%20c%20335%20§%20204[1995 c 335 § 204]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20156[1990 c 33 § 156]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20310[1989 c 271 § 310]; ]

== 28A.170.080 - Grants—Substance abuse intervention.
. Grants provided under RCW 28A.170.090 may be used solely for services provided by a substance abuse intervention specialist or for dedicated staff time for counseling and intervention services provided by any school district certificated employee who has been trained by and has access to consultation with a substance abuse intervention specialist. Services shall be directed at assisting students in kindergarten through twelfth grade in overcoming problems of drug and alcohol abuse, and in preventing abuse and addiction to such substances, including nicotine. The grants shall require local matching funds so that the grant amounts support a maximum of eighty percent of the costs of the services funded. The services of a substance abuse intervention specialist may be obtained by means of a contract with a state or community services agency or a drug treatment center. Services provided by a substance abuse intervention specialist may include:

.. Individual and family counseling, including preventive counseling;

.. Assessment and referral for treatment;

.. Referral to peer support groups;

.. Aftercare;

.. Development and supervision of student mentor programs;

.. Staff training, including training in the identification of high-risk children and effective interaction with those children in the classroom; and

.. Development and coordination of school drug and alcohol core teams, involving staff, students, parents, and community members.

. For the purposes of this section, "substance abuse intervention specialist" means any one of the following, except that diagnosis and assessment, counseling and aftercare specifically identified with treatment of chemical dependency shall be performed only by personnel who meet the same qualifications as are required of a qualified chemical dependency counselor employed by an alcoholism or drug treatment program approved by the department of social and health services.

.. An educational staff associate employed by a school district or educational service district who holds certification as a school counselor, school psychologist, school nurse, or school social worker under Washington professional educator standards board rules adopted pursuant to RCW 28A.410.210;

.. An individual who meets the definition of a qualified drug or alcohol counselor established by the bureau of alcohol and substance abuse;

.. A qualified professional employed by the department of social and health services;

.. A psychologist licensed under chapter 18.83 RCW; or

.. A children's mental health specialist as defined in RCW 71.34.020.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5020-S.SL.pdf?cite=2011%20c%2089%20§%208[2011 c 89 § 8]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5732-S.SL.pdf?cite=2005%20c%20497%20§%20213[2005 c 497 § 213]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20157[1990 c 33 § 157]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20311[1989 c 271 § 311]; ]

== 28A.170.090 - Selection of grant recipients—Program rules.
. The superintendent of public instruction shall select school districts and cooperatives of school districts to receive grants for drug and alcohol abuse prevention and intervention programs for students in kindergarten through twelfth grade, from funds appropriated by the legislature for this purpose. The minimum annual grant amount per district or cooperative of districts shall be twenty thousand dollars. Factors to be used in selecting proposals for funding and in determining grant awards shall be developed in consultation with the substance abuse advisory committee appointed under RCW 28A.170.050, with the intent of targeting funding to districts with high-risk populations. These factors may include:

.. Characteristics of the school attendance areas to be served, such as the number of students from low-income families, truancy rates, juvenile justice referrals, and social services caseloads;

.. The total number of students who would have access to services; and

.. Participation of community groups and law enforcement agencies in drug and alcohol abuse prevention and intervention activities.

. The application procedures for grants under this section shall include provisions for comprehensive planning, establishment of a school and community substance abuse advisory committee, and documentation of the district's needs assessment. Planning and application for grants under this section may be integrated with the development of other substance abuse awareness programs by school districts. School districts shall, to the maximum extent feasible, coordinate the use of grants provided under this section with other funding available for substance abuse awareness programs. School districts should allocate resources giving emphasis to drug and alcohol abuse intervention services for students in grades five through nine. Grants may be used to provide services for students who are enrolled in approved private schools.

. School districts receiving grants under this section shall be required to establish a means of accessing formal assessment services for determining treatment needs of students with drug and alcohol problems. The grant applications submitted by districts shall identify the districts' plan for meeting this requirement.

. School districts receiving grants under this section shall be required to perform biennial evaluations of their drug and alcohol abuse prevention and intervention programs, and to report on the results of these evaluations to the superintendent of public instruction.

. The superintendent of public instruction may adopt rules to implement RCW 28A.170.080 and 28A.170.090.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5169-S.SL.pdf?cite=1995%20c%20335%20§%20205[1995 c 335 § 205]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20158[1990 c 33 § 158]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20312[1989 c 271 § 312]; ]

== 28A.170.095 - Condensed compliance reports—Second-class districts.
Any compliance reporting requirements as a result of laws in this chapter that apply to second-class districts may be submitted in accordance with RCW 28A.330.250.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5184-S.SL.pdf?cite=2011%20c%2045%20§%207[2011 c 45 § 7]; ]

