= 28A.545 - Payment to high school districts.
:toc:

== 28A.545.010 - School district divisions—High and nonhigh.
For the purposes of this chapter all school districts in the state of Washington shall be and the same are hereby divided into two divisions to be known and designated respectively as high school districts and nonhigh school districts.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%2031[1983 c 3 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028A.44.045[1969 ex.s. c 223 § 28A.44.045]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c21.pdf?cite=1917%20c%2021%20§%201[1917 c 21 § 1]; RRS § 4710; ]

== 28A.545.020 - Reimbursement not a tuition charge.
The reimbursement of a high school district for cost of educating high school pupils for a nonhigh school district, as provided for in this chapter, shall not be deemed a tuition charge as affecting the apportionment of current state school funds.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%2032[1983 c 3 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028A.44.095[1969 ex.s. c 223 § 28A.44.095]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c21.pdf?cite=1917%20c%2021%20§%2011[1917 c 21 § 11]; RRS § 4720; ]

== 28A.545.030 - Purposes.
The purposes of RCW 28A.545.030 through 28A.545.110 and 84.52.0531 are to:

. Simplify the annual process of determining and paying the amounts due by nonhigh school districts to high school districts for educating students residing in a nonhigh school district;

. Provide for a payment schedule that coincides to the extent practicable with the ability of nonhigh school districts to pay and the need of high school districts for payment;

. Establish that the maximum amount due per annual average full-time equivalent student by a nonhigh school district for each school year is the lesser of:

.. The enrichment levy rate per annual average full-time equivalent student levied upon the taxpayers of the high school district; or

.. The enrichment levy rate per annual average full-time equivalent student levied upon the taxpayers of the nonhigh school district;

. If the nonhigh school district has not levied an enrichment levy during the current school year, then the amount due per annual average full-time equivalent student by the nonhigh school district is the enrichment levy rate per annual average full-time equivalent student levied upon the taxpayers of the high school district; and

. Designate the revenue provided to secondary school buildings to ensure dollars are being spent to support secondary school students.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2040.SL.pdf?cite=2020%20c%20225%20§%201[2020 c 225 § 1]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2017%203rd%20sp.s.%20c%2013%20§%201001[2017 3rd sp.s. c 13 § 1001]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20488[1990 c 33 § 488]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c264.pdf?cite=1981%20c%20264%20§%201[1981 c 264 § 1]; ]

== 28A.545.040 - "Student residing in a nonhigh school district" defined.
The term "student residing in a nonhigh school district" and its equivalent as used in RCW 28A.545.030 through 28A.545.110 and 84.52.0531 shall mean any common school-age person with or without disabilities who resides within the boundaries of a nonhigh school district that does not conduct the particular kindergarten through grade twelve grade which the person has not yet successfully completed and is eligible to enroll in, not including students enrolled in an innovation academy cooperative established under RCW 28A.340.080 through 28A.340.090.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2913-S.SL.pdf?cite=2010%20c%2099%20§%207[2010 c 99 § 7]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5276.SL.pdf?cite=1995%20c%2077%20§%2025[1995 c 77 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20489[1990 c 33 § 489]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c264.pdf?cite=1981%20c%20264%20§%202[1981 c 264 § 2]; ]

== 28A.545.050 - Amounts due from nonhigh districts.
Each year at such time as the superintendent of public instruction determines and certifies such maximum allowable amounts of school district levies under RCW 84.52.0531 he or she shall also:

. Determine the extent to which the estimated amounts due by nonhigh school districts for the previous school year exceeded or fell short of the actual amounts due; and

. Determine the estimated amounts due by nonhigh school districts for the current school year and increase or decrease the same to the extent of overpayments or underpayments for the previous school year.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c341.pdf?cite=1985%20c%20341%20§%2011[1985 c 341 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c264.pdf?cite=1981%20c%20264%20§%203[1981 c 264 § 3]; ]

== 28A.545.060 - Enrollment data for computation of amounts due.
The student enrollment data necessary for the computation of the annual amounts due by nonhigh school districts pursuant to RCW 28A.545.030 through 28A.545.110 and 84.52.0531 shall be established as follows:

. On or before July tenth preceding the school year, or such other date as may be established by the superintendent of public instruction, each high school district superintendent shall certify to the superintendent of public instruction:

.. The estimated number of students residing in a nonhigh school district that will be enrolled in the high school district during the school year which estimate has been mutually agreed upon by the high school district superintendent and the superintendent of each nonhigh school district in which one or more of such students resides;

.. The total estimated number of kindergarten through twelfth grade annual average full-time equivalent students, inclusive of nonresident students, that will be enrolled in the high school district during the school year;

.. The actual number of annual average full-time equivalent students provided for in subsections (1)(a) and (b) of this section that were enrolled in the high school district during the regular school term just completed; and

.. The name, address, and the school district and county of residence of each student residing in a nonhigh school district reported pursuant to this subsection (1), to the extent the same can reasonably be established.

. In the event the superintendents of a high school district and a nonhigh school district are unable to reach agreement respecting the estimated number of annual average full-time equivalent students residing in the nonhigh school district that will be enrolled in the high school district during the school year, the estimate shall be established by the superintendent of public instruction.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20490[1990 c 33 § 490]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c264.pdf?cite=1981%20c%20264%20§%204[1981 c 264 § 4]; ]

== 28A.545.070 - Superintendent's annual determination of estimated amount due—Process.
. The superintendent of public instruction shall annually determine the estimated amount due by a nonhigh school district to a high school district for the school year as follows:

.. The total of the high school district's enrichment levy or nonhigh school district's enrichment levy, as determined under RCW 28A.545.030(3), that has been authorized and determined by the superintendent of public instruction to be allowable pursuant to RCW 84.52.0531, as now or hereafter amended, for collection during the next calendar year, shall first be divided by the total estimated number of annual average full-time equivalent students which that district's superintendent or the superintendent of public instruction has certified pursuant to RCW 28A.545.060 will be enrolled in that district during the school year;

.. The result of the calculation provided for in subsection (1)(a) of this section shall then be multiplied by the estimated number of annual average full-time equivalent students residing in the nonhigh school district that will be enrolled in the high school district during the school year which has been established pursuant to RCW 28A.545.060; and

.. The result of the calculation provided for in subsection (1)(b) of this section [(b) of this subsection] shall be adjusted upward to the extent the estimated amount due by a nonhigh school district for the prior school year was less than the actual amount due based upon actual annual average full-time equivalent student enrollments during the previous school year and the actual per annual average full-time equivalent student enrichment levy rate for the current tax collection year, or adjusted downward to the extent the estimated amount due was greater than such actual amount due or greater than such lesser amount as a high school district may have elected to assess pursuant to RCW 28A.545.090.

. The amount arrived at pursuant to subsection (1)(c) of this subsection shall constitute the estimated amount due by a nonhigh school district to a high school district for the school year.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2040.SL.pdf?cite=2020%20c%20225%20§%203[2020 c 225 § 3]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2017%203rd%20sp.s.%20c%2013%20§%201002[2017 3rd sp.s. c 13 § 1002]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20491[1990 c 33 § 491]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c264.pdf?cite=1981%20c%20264%20§%205[1981 c 264 § 5]; ]

== 28A.545.080 - Estimated amount due paid in May and November installments.
The estimated amounts due by nonhigh school districts as determined pursuant to RCW 28A.545.070 shall be paid in two installments. During the month of May of the school year for which the amount is due, each nonhigh school district shall pay to each high school district fifty percent of the total estimated amount due to the high school district for the school year as determined by the superintendent of public instruction pursuant to RCW 28A.545.070. The remaining fifty percent shall be paid by each nonhigh school district to each high school district during the following November.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20492[1990 c 33 § 492]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c264.pdf?cite=1981%20c%20264%20§%206[1981 c 264 § 6]; ]

== 28A.545.090 - Assessing nonhigh school lesser amount—Notice of.
Notwithstanding any provision of RCW 28A.545.050 through 28A.545.080 to the contrary, any high school district board of directors may elect to assess a nonhigh school district an amount which is less than that otherwise established by the superintendent of public instruction pursuant to RCW 28A.545.070 to be due. In the event a high school district elects to do so, it shall notify both the superintendent of public instruction and the nonhigh school district of its election and the lesser amount no later than September first following the school year for which the amount is due. In the absence of such notification, each nonhigh school district shall pay the amount otherwise established by the superintendent of public instruction pursuant to RCW 28A.545.070.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20493[1990 c 33 § 493]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c264.pdf?cite=1981%20c%20264%20§%207[1981 c 264 § 7]; ]

== 28A.545.100 - Amount due reflects cost of education and transportation of students.
Unless otherwise agreed to by the board of directors of a nonhigh school district, the amounts which are established as due by a nonhigh school district pursuant to RCW 28A.545.030 through 28A.545.110 and 84.52.0531, as now or hereafter amended, shall constitute the entire amount which is due by a nonhigh school district for the school year for the education of any and all students with or without disabilities residing in the nonhigh school district who attend a high school district pursuant to RCW 28A.225.210, and for the transportation of such students by a high school district.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5276.SL.pdf?cite=1995%20c%2077%20§%2026[1995 c 77 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20494[1990 c 33 § 494]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c61.pdf?cite=1983%201st%20ex.s.%20c%2061%20§%207[1983 1st ex.s. c 61 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c264.pdf?cite=1981%20c%20264%20§%208[1981 c 264 § 8]; ]

== 28A.545.110 - Rules to effect purposes and implement provisions.
The superintendent of public instruction is hereby empowered to adopt rules pursuant to chapter 34.05 RCW, as now or hereafter amended, deemed necessary or advisable by the superintendent to effect the purposes and implement the provisions of RCW 28A.545.030 through 28A.545.110 and 84.52.0531.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20495[1990 c 33 § 495]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c264.pdf?cite=1981%20c%20264%20§%209[1981 c 264 § 9]; ]

== 28A.545.120 - New programs or grades—Approval—Rules.
. The superintendent of public instruction, with recommendations from the school facilities citizen advisory panel under RCW 28A.525.025, shall adopt rules governing the establishment in any existing nonhigh school district of any secondary program or any new grades in grades nine through twelve. Before any such program or any new grades are established, the district must obtain prior approval of the superintendent of public instruction.

. This section does not apply to innovation academy cooperatives established under RCW 28A.340.080 through 28A.340.090.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2913-S.SL.pdf?cite=2010%20c%2099%20§%208[2010 c 99 § 8]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3098-S2.SL.pdf?cite=2006%20c%20263%20§%20325[2006 c 263 § 325]; ]

== 28A.545.130 - Condensed compliance reports—Second-class districts.
Any compliance reporting requirements as a result of laws in this chapter that apply to second-class districts may be submitted in accordance with RCW 28A.330.250.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5184-S.SL.pdf?cite=2011%20c%2045%20§%2044[2011 c 45 § 44]; ]

== 28A.545.140 - Annual data reports.
Upon a nonhigh school district's request, a host high school district shall provide an annual data report to the nonhigh school district within sixty days of the request. The report must include attendance, grades, discipline, and state assessment data for all nonhigh secondary students sent to the high school district.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2040.SL.pdf?cite=2020%20c%20225%20§%202[2020 c 225 § 2]; ]

