= 28A.527 - School facilities—2008 bond issue.
:toc:

== 28A.527.005 - Findings—Intent—2008 c 179.
The legislature finds that the state's public schools and skill centers are a vital component of the future economic prosperity of our state and provide students with access to high-quality academic and technical skills instruction. Skill centers challenge, motivate, and provide opportunities for students to achieve in basic skills, critical thinking, leadership, and work skills through hands-on education, applied academics, and technology training using a cost-effective delivery model. The legislature further finds that barriers to access exist for students in rural and high-density areas, but the development of satellite and branch campus programs will provide the needed access. The legislature further finds that existing and proposed new skill centers will require facilities and equipment that simulate business and industry. Therefore, it is the intent of the legislature to provide a new source of funding for the critical capital needs of the state's skill centers to enhance access to career and technical education opportunities and to improve the condition of existing facilities. Enhanced capital funding will provide skill centers the ability to fulfill their critical role in maintaining and stimulating the state's economy and expanding quality academic and career and technical education opportunities to more students, especially students who lack access to these programs to date.

In the interest of funding equity and ensuring a commitment to the new development, major renovation, or expansion of skill centers, all school district partners must contribute to the acquisition or major capital costs of skill center projects supported by this act to the greatest extent feasible.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3374-S.SL.pdf?cite=2008%20c%20179%20§%20201[2008 c 179 § 201]; ]

== 28A.527.010 - School construction assistance grants—Capital improvements—Bond issue.
For the purpose of providing school construction assistance grants and needed capital improvements consisting of the predesign, design, acquisition, construction, modification, renovation, expansion, equipping, and other improvements of skill centers facilities, including capital improvements to support satellite or branch campus programs for underserved rural areas or high-density areas, the state finance committee is authorized to issue general obligation bonds of the state of Washington in the sum of one hundred million dollars, or as much thereof as may be required, to finance all or a part of these projects and all costs incidental thereto. Bonds authorized in this section may be sold at such price as the state finance committee shall determine. No bonds authorized in this section may be offered for sale without prior legislative appropriation of the net proceeds of the sale of the bonds. If the state finance committee deems it necessary to issue taxable bonds in order to comply with federal internal revenue service rules and regulations pertaining to the use of nontaxable bond proceeds, the proceeds of such taxable bonds shall be transferred to the state taxable building construction account in lieu of any deposits otherwise provided by this section. The state treasurer shall submit written notice to the director of financial management if it is determined that any such transfer to the state taxable building construction account is necessary.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3374-S.SL.pdf?cite=2008%20c%20179%20§%20202[2008 c 179 § 202]; ]

== 28A.527.020 - Bond proceeds—Use.
This chapter is not intended to limit the legislature's ability to appropriate bond proceeds if the full amount authorized in this chapter has not been appropriated after one biennia, and the authorization to issue bonds contained in this chapter does not expire until the full authorization has been appropriated and issued.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3374-S.SL.pdf?cite=2008%20c%20179%20§%20203[2008 c 179 § 203]; ]

== 28A.527.030 - Proceeds from sale of bonds—Deposit—Use.
. The proceeds from the sale of the bonds authorized in RCW 28A.527.010 shall be deposited in the school construction and skill centers building account created in RCW 28A.527.090.

. The proceeds shall be used exclusively for the purposes stated in RCW 28A.527.010 and for the payment of the expenses incurred in connection with the sale and issuance of the bonds.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3374-S.SL.pdf?cite=2008%20c%20179%20§%20204[2008 c 179 § 204]; ]

== 28A.527.040 - Payment of principal and interest from nondebt-limit reimbursable bond account.
. The nondebt-limit reimbursable bond retirement account must be used for the payment of the principal and interest on the bonds authorized in RCW 28A.527.010.

. [Empty]
.. The state finance committee must, on or before June 30th of each year, certify to the state treasurer the amount needed in the ensuing twelve months to meet the bond retirement and interest requirements on the bonds authorized in RCW 28A.527.010.

.. On or before the date on which any interest or principal and interest is due, the state treasurer shall transfer from that portion of the common school construction fund derived from the interest on the permanent common school fund into the nondebt-limit reimbursable bond retirement account the amount computed in (a) of this subsection for bonds issued for the purposes of RCW 28A.527.010. Any deficiency in such transfer shall be made up as soon as moneys are available for transfer and shall constitute a continuing obligation of that portion of the common school construction fund derived from the interest on the permanent common school fund until all deficiencies are fully paid.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3374-S.SL.pdf?cite=2008%20c%20179%20§%20205[2008 c 179 § 205]; ]

== 28A.527.050 - Pledge and promise—Remedies.
. Bonds issued under RCW 28A.527.010 shall state that they are a general obligation of the state of Washington, shall pledge the full faith and credit of the state to the payment of the principal thereof and the interest thereon, and shall contain an unconditional promise to pay the principal and interest as the same shall become due.

. The owner and holder of each of the bonds or the trustee for the owner and holder of any of the bonds may by mandamus or other appropriate proceeding require the transfer and payment of funds as directed in this section.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3374-S.SL.pdf?cite=2008%20c%20179%20§%20206[2008 c 179 § 206]; ]

== 28A.527.060 - Bonds legal investment for public funds.
The bonds authorized in RCW 28A.527.010 shall be a legal investment for all state funds or funds under state control and for all funds of any other public body.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3374-S.SL.pdf?cite=2008%20c%20179%20§%20207[2008 c 179 § 207]; ]

== 28A.527.070 - Payment of principal and interest—Additional means for raising money authorized.
The legislature may provide additional means for raising moneys for the payment of the principal of and interest on the bonds authorized in RCW 28A.527.010, and *RCW 28A.527.010 shall not be deemed to provide an exclusive method for the payment.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3374-S.SL.pdf?cite=2008%20c%20179%20§%20208[2008 c 179 § 208]; ]

== 28A.527.080 - Chapter supplemental.
This chapter provides a complete, additional, and alternative method for accomplishing the purposes of this chapter and is supplemental and additional to powers conferred by other laws. The issuance of bonds under this chapter shall not be deemed to be the only method to fund projects under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3374-S.SL.pdf?cite=2008%20c%20179%20§%20209[2008 c 179 § 209]; ]

== 28A.527.090 - School construction and skill centers building account.
The school construction and skill centers building account is created in the state treasury. Proceeds from the bonds issued under RCW 28A.527.010 shall be deposited in the account. The account shall be used for purposes stated in RCW 28A.527.010. Moneys in the account may be spent only after appropriation.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3374-S.SL.pdf?cite=2008%20c%20179%20§%20210[2008 c 179 § 210]; ]

== 28A.527.100 - Condensed compliance reports—Second-class districts.
Any compliance reporting requirements as a result of laws in this chapter that apply to second-class districts may be submitted in accordance with RCW 28A.330.250.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5184-S.SL.pdf?cite=2011%20c%2045%20§%2040[2011 c 45 § 40]; ]

== 28A.527.902 - Effective date—2008 c 179.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and takes effect immediately [March 27, 2008].

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3374-S.SL.pdf?cite=2008%20c%20179%20§%20307[2008 c 179 § 307]; ]

