= 28A.540 - Capital fund aid by nonhigh school districts.
:toc:

== 28A.540.010 - High school facilities defined.
High school facilities shall mean buildings for occupancy by grades nine through twelve and equipment and furniture for such buildings and shall include major alteration or major remodeling of buildings and the acquisition of new sites and of additions to existing sites, and improvement of sites but only when included as a part of a general plan for the construction, equipping and furnishing of a building or of an alteration or addition to a building. The term shall also (1) include that portion of any building, alteration, equipment, furniture, site and improvement of site allocated to grade nine when included in a plan for facilities to be occupied by grades seven through nine and (2) includes such facilities for grades seven and eight when included in a plan as aforesaid, if the regional committee on school district organization finds that students of these grades who reside in any nonhigh school districts involved are now attending school in the high school district involved under an arrangement which likely will be continued.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c385.pdf?cite=1985%20c%20385%20§%2031[1985 c 385 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028A.56.005[1969 ex.s. c 223 § 28A.56.005]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c262.pdf?cite=1959%20c%20262%20§%202[1959 c 262 § 2]; ]

== 28A.540.020 - Plan for nonhigh district to provide capital funds in aid of high school district.
Upon receipt of a written request from the board of directors of a high school district or a nonhigh school district that presents to the regional committee on school district organization satisfactory evidence of a need for high school facilities to be located therein and of ability to provide such facilities, the regional committee shall prepare a plan for participation by any nonhigh school district or districts in providing capital funds to pay the costs of such school facilities and equipment to be provided for the education of students residing in the school districts. Prior to submission of the aforesaid request the board of directors of the school district concerned therewith shall determine the nature and extent of the high school facilities proposed to be provided, the approximate amount of local capital funds required to pay the cost thereof, and the site or sites upon which the proposed facilities are to be located, and shall submit a report thereon to the regional committee along with the aforesaid request.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c385.pdf?cite=1985%20c%20385%20§%2032[1985 c 385 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028A.56.010[1969 ex.s. c 223 § 28A.56.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c262.pdf?cite=1959%20c%20262%20§%201[1959 c 262 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c344.pdf?cite=1955%20c%20344%20§%201[1955 c 344 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c229.pdf?cite=1953%20c%20229%20§%201[1953 c 229 § 1]; ]

== 28A.540.030 - Factors to be considered in preparation of plan.
The regional committee on school district organization shall give consideration to:

. The report submitted by the board of directors as stated above;

. The exclusion from the plan of nonhigh school districts because of remoteness or isolation or because they are so situated with respect to location, present and/or clearly foreseeable future population, and other pertinent factors as to warrant the establishment of a high school therein within a period of two years or the inclusion of their territory in some other nonhigh school district within which the establishment of a high school within a period of two years is warranted;

. The assessed valuation of the school districts involved;

. The cash balance, if any, in the capital projects fund of the district submitting the request which is designated for high school building construction purposes, together with the sources of such balance; and

. Any other factors found by the committee to have a bearing on the preparation of an equitable plan.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c385.pdf?cite=1985%20c%20385%20§%2033[1985 c 385 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2091[1985 c 7 § 91]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028A.56.020[1969 ex.s. c 223 § 28A.56.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c262.pdf?cite=1959%20c%20262%20§%203[1959 c 262 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c344.pdf?cite=1955%20c%20344%20§%202[1955 c 344 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c229.pdf?cite=1953%20c%20229%20§%202[1953 c 229 § 2]; ]

== 28A.540.040 - Public hearing—Notice.
The regional committee on school district organization shall also hold a public hearing or hearings on any proposed plan: PROVIDED, That three members of the committee or two members of the committee and the educational service district superintendent, or his or her designee, may be designated by the committee to hold such public hearing or hearings and to submit a report thereof to the regional committee. The regional committee shall cause to be posted, at least ten days prior to the date appointed for any such hearing, a written or printed notice thereof in at least three prominent and public places in the school districts involved and at the place of hearing.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c385.pdf?cite=1985%20c%20385%20§%2034[1985 c 385 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c275.pdf?cite=1975%201st%20ex.s.%20c%20275%20§%2074[1975 1st ex.s. c 275 § 74]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c48.pdf?cite=1971%20c%2048%20§%2021[1971 c 48 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028A.56.030[1969 ex.s. c 223 § 28A.56.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c262.pdf?cite=1959%20c%20262%20§%204[1959 c 262 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c344.pdf?cite=1955%20c%20344%20§%203[1955 c 344 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c229.pdf?cite=1953%20c%20229%20§%203[1953 c 229 § 3]; ]

== 28A.540.050 - Review by superintendent of public instruction—Approval—Revised plan.
Subsequent to the holding of a hearing or hearings as provided in RCW 28A.540.040, the regional committee on school district organization shall determine the nonhigh school districts to be included in the plan and the amount of capital funds to be provided by every school district included therein, and shall submit the proposed plan to the superintendent of public instruction together with such maps and other materials pertaining thereto as the superintendent may require. The superintendent, considering policy recommendations from the school facilities citizen advisory panel under RCW 28A.525.025, shall review such plan, shall approve any plan which in his or her judgment makes adequate and satisfactory provision for participation by the nonhigh school districts in providing capital funds to be used for the purpose above stated, and shall notify the regional committee of such action. Upon receipt by the regional committee of such notification, the educational service district superintendent, or his or her designee, shall notify the board of directors of each school district included in the plan, supplying each board with complete details of the plan and shall state the total amount of funds to be provided and the amount to be provided by each district.

If any such plan submitted by a regional committee is not approved by the superintendent of public instruction, the regional committee shall be so notified, which notification shall contain a statement of reasons therefor and suggestions for revision. Within sixty days thereafter the regional committee shall submit to the superintendent a revised plan which revision shall be subject to approval or disapproval by the superintendent, considering policy recommendations from the school facilities citizen advisory panel, and the procedural requirements and provisions of law applicable to an original plan submitted to the superintendent.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3098-S2.SL.pdf?cite=2006%20c%20263%20§%20324[2006 c 263 § 324]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20485[1990 c 33 § 485]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c385.pdf?cite=1985%20c%20385%20§%2035[1985 c 385 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c275.pdf?cite=1975%201st%20ex.s.%20c%20275%20§%2075[1975 1st ex.s. c 275 § 75]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c48.pdf?cite=1971%20c%2048%20§%2022[1971 c 48 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028A.56.040[1969 ex.s. c 223 § 28A.56.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c262.pdf?cite=1959%20c%20262%20§%205[1959 c 262 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c344.pdf?cite=1955%20c%20344%20§%204[1955 c 344 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c229.pdf?cite=1953%20c%20229%20§%204[1953 c 229 § 4]; ]

== 28A.540.060 - Bond, excess levy, elections—Use of proceeds.
Within sixty days after receipt of the notice of approval from the educational service district superintendent, the board of directors of each school district included in the plan shall submit to the voters thereof a proposal or proposals for providing, through the issuance of bonds and/or the authorization of an excess tax levy, the amount of capital funds that the district is required to provide under the plan. The proceeds of any such bond issue and/or excess tax levy shall be credited to the capital projects fund of the school district in which the proposed high school facilities are to be located and shall be expended to pay the cost of high school facilities for the education of such students residing in the school districts as are included in the plan and not otherwise.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%2092[1985 c 7 § 92]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c275.pdf?cite=1975%201st%20ex.s.%20c%20275%20§%2076[1975 1st ex.s. c 275 § 76]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c48.pdf?cite=1971%20c%2048%20§%2023[1971 c 48 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028A.56.050[1969 ex.s. c 223 § 28A.56.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c262.pdf?cite=1959%20c%20262%20§%206[1959 c 262 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c344.pdf?cite=1955%20c%20344%20§%205[1955 c 344 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c229.pdf?cite=1953%20c%20229%20§%205[1953 c 229 § 5]; ]

== 28A.540.070 - Rejection by voters of nonhigh districts—Additional elections—Revised plan—Annexation proposal.
In the event that a proposal or proposals for providing capital funds as provided in RCW 28A.540.060 is not approved by the voters of a nonhigh school district a second election thereon shall be held within sixty days thereafter. If the vote of the electors of the nonhigh school district is again in the negative, the high school students residing therein shall not be entitled to admission to the high school under the provisions of RCW 28A.225.210, following the close of the school year during which the second election is held: PROVIDED, That in any such case the regional committee on school district organization shall determine within thirty days after the date of the aforesaid election the advisability of initiating a proposal for annexation of such nonhigh school district to the school district in which the proposed facilities are to be located or to some other district where its students can attend high school without undue inconvenience: PROVIDED FURTHER, That pending such determination by the regional committee and action thereon as required by law the board of directors of the high school district shall continue to admit high school students residing in the nonhigh school district. Any proposal for annexation of a nonhigh school district initiated by a regional committee shall be subject to the procedural requirements of this chapter respecting a public hearing and submission to and approval by the superintendent of public instruction, considering policy recommendations from the school facilities citizen advisory panel under RCW 28A.525.025. Upon approval by the superintendent of public instruction of any such proposal, the educational service district superintendent shall make an order , establishing the annexation.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3098-S2.SL.pdf?cite=2006%20c%20263%20§%20329[2006 c 263 § 329]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20486[1990 c 33 § 486]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c385.pdf?cite=1985%20c%20385%20§%2036[1985 c 385 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c275.pdf?cite=1975%201st%20ex.s.%20c%20275%20§%2077[1975 1st ex.s. c 275 § 77]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c48.pdf?cite=1971%20c%2048%20§%2024[1971 c 48 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028A.56.060[1969 ex.s. c 223 § 28A.56.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c262.pdf?cite=1959%20c%20262%20§%207[1959 c 262 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c344.pdf?cite=1955%20c%20344%20§%206[1955 c 344 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c229.pdf?cite=1953%20c%20229%20§%206[1953 c 229 § 6]; ]

== 28A.540.080 - Failure of nonhigh districts to submit proposal to vote within time limits—Annexation procedure.
In case of failure or refusal by a board of directors of a nonhigh school district to submit a proposal or proposals to a vote of the electors within the time limit specified in RCW 28A.540.060 and 28A.540.070, the regional committee on school district reorganization may initiate a proposal for annexation of such nonhigh school district as provided for in RCW 28A.540.070.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20487[1990 c 33 § 487]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c385.pdf?cite=1985%20c%20385%20§%2037[1985 c 385 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028A.56.070[1969 ex.s. c 223 § 28A.56.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c262.pdf?cite=1959%20c%20262%20§%208[1959 c 262 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c344.pdf?cite=1955%20c%20344%20§%207[1955 c 344 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c229.pdf?cite=1953%20c%20229%20§%207[1953 c 229 § 7]; ]

== 28A.540.090 - Nonhigh districts, time of levy and issuance of bonds.
If the voters of a nonhigh school district approve an excess tax levy, the levy shall be made at the earliest time permitted by law. If the voters of a nonhigh school district approve the issuance of bonds, the board of directors of the nonhigh school district shall issue and sell said bonds within ninety days after receiving a copy of a resolution of the board of directors of the high school district that the high school district is ready to proceed with the construction of the high school facilities provided for in the plan and requesting the sale of the bonds.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028A.56.075[1969 ex.s. c 223 § 28A.56.075]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c262.pdf?cite=1959%20c%20262%20§%209[1959 c 262 § 9]; ]

== 28A.540.100 - Validation of proceedings under 1955 act, when.
All proceedings had and taken under chapter 344, Laws of 1955, shall be valid and binding although not in compliance with that act if said proceedings comply with the requirements of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028A.56.170[1969 ex.s. c 223 § 28A.56.170]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c262.pdf?cite=1959%20c%20262%20§%2011[1959 c 262 § 11]; ]

== 28A.540.110 - Designation of high school district nonhigh district students shall attend—Effect when attendance otherwise.
. In cases where high school students resident in a nonhigh school district are to be educated in a high school district, the board of directors of the nonhigh school district shall, by mutual agreement with the serving district(s), designate the serving high school district or districts which its high school students shall attend. A nonhigh school district shall designate a district as a serving high school district when more than thirty-three and one-third percent of the high school students residing within the boundaries of the nonhigh school district are enrolled in the serving district.

. Students residing in a nonhigh school district shall be allowed to attend a high school other than in the designated serving district referred to in subsection (1) of this section, however the nonhigh school board of directors shall not be required to contribute to building programs in any such high school district. Contribution shall be made only to those districts which are designated as serving high school districts at the time the county auditor is requested by the high school district to place a measure on the ballot regarding a proposal or proposals for the issuance of bonds or the authorization of an excess tax levy to provide capital funds for building programs. The nonhigh school district shall be subject to the capital fund aid provisions contained in this chapter with respect to the designated high school serving district(s).

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c321.pdf?cite=1989%20c%20321%20§%204[1989 c 321 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c239.pdf?cite=1981%20c%20239%20§%201[1981 c 239 § 1]; ]

== 28A.540.120 - Condensed compliance reports—Second-class districts.
Any compliance reporting requirements as a result of laws in this chapter that apply to second-class districts may be submitted in accordance with RCW 28A.330.250.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5184-S.SL.pdf?cite=2011%20c%2045%20§%2043[2011 c 45 § 43]; ]

