= 28A.650 - Education technology.
:toc:

== 28A.650.005 - Findings—Intent.
The legislature recognizes that up-to-date tools will help students learn. Workplace technology requirements will continue to change and students should be knowledgeable in the use of technologies.

Furthermore, the legislature finds that the Washington systemic initiative is a broad-based effort to promote widespread public literacy in mathematics, science, and technology. An important component of the systemic initiative is the universal electronic access to information by students. It is the intent of the legislature that components of RCW 28A.650.010 through 28A.650.025 will support the statewide systemic reform effort in mathematics, science, and technology as envisioned by the Washington systemic initiative.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1209-S.SL.pdf?cite=1993%20c%20336%20§%20701[1993 c 336 § 701]; ]

== 28A.650.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Digital citizenship" includes the norms of appropriate, responsible, and healthy behavior related to current technology use, including digital and media literacy, ethics, etiquette, and security. The term also includes the ability to access, analyze, evaluate, develop, produce, and interpret media, as well as internet safety and cyberbullying prevention and response.

. "Education technology" or "technology" means the effective use of electronic and optical tools, including telephones, and electronic and optical pathways in helping students learn.

. "Network" means integrated linking of education technology systems in schools for transmission of voice, data, video, or imaging, or a combination of these.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5449-S.SL.pdf?cite=2017%20c%2090%20§%201[2017 c 90 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1209-S.SL.pdf?cite=1993%20c%20336%20§%20702[1993 c 336 § 702]; ]

== 28A.650.015 - Education technology plan—Educational technology advisory committee.
. The superintendent of public instruction, to the extent funds are appropriated, shall develop and implement a Washington state K-12 education technology plan. The technology plan shall be updated on at least a biennial basis, shall be developed to coordinate and expand the use of education technology in the common schools of the state. The plan shall be consistent with applicable provisions of chapter 43.105 RCW. The plan, at a minimum, shall address:

.. The provision of technical assistance to schools and school districts for the planning, implementation, and training of staff in the use of technology in curricular and administrative functions;

.. The continued development of a network to connect school districts, institutions of higher learning, and other sources of online information; and

.. Methods to equitably increase the use of education technology by students and school personnel throughout the state.

. The superintendent of public instruction shall appoint an educational technology advisory committee to assist in the development and implementation of the technology plan in subsection (1) of this section. The committee shall include, but is not limited to, persons representing: The office of the chief information officer, educational service districts, school directors, school administrators, school principals, teachers, classified staff, higher education faculty, parents, students, business, labor, scientists and mathematicians, the workforce training and education coordinating board, and the state library.

. The plan adopted and implemented under this section may not impose on school districts any requirements that are not specifically required by federal law or regulation, including requirements to maintain eligibility for the federal schools and libraries program of the universal service fund.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5931-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2043%20§%20725[2011 1st sp.s. c 43 § 725]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20133[2011 1st sp.s. c 11 § 133]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5889-S.SL.pdf?cite=2009%20c%20556%20§%2017[2009 c 556 § 17]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3098-S2.SL.pdf?cite=2006%20c%20263%20§%20917[2006 c 263 § 917]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5169-S.SL.pdf?cite=1995%20c%20335%20§%20507[1995 c 335 § 507]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2850-S.SL.pdf?cite=1994%20c%20245%20§%202[1994 c 245 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1209-S.SL.pdf?cite=1993%20c%20336%20§%20703[1993 c 336 § 703]; ]

== 28A.650.020 - Regional educational technology support centers—Advisory councils.
Educational service districts shall establish, subject to available funding, regional educational technology support centers for the purpose of providing ongoing educator training, school district cost-benefit analysis, long-range planning, network planning, distance learning access support, and other technical and programmatic support. Each educational service district shall establish a representative advisory council to advise the educational service district in the expenditure of funds provided to the technology support centers.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1209-S.SL.pdf?cite=1993%20c%20336%20§%20705[1993 c 336 § 705]; ]

== 28A.650.025 - Distribution of funds for regional educational technology support centers.
The superintendent of public instruction, to the extent funds are appropriated, shall distribute funds to educational service districts on a grant basis for the regional educational technology support centers established in RCW 28A.650.020.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1209-S.SL.pdf?cite=1993%20c%20336%20§%20706[1993 c 336 § 706]; ]

== 28A.650.030 - Distribution of funds to expand the education statewide network.
The superintendent of public instruction, to the extent funds are appropriated, shall distribute funds to the Washington school information processing cooperative and to school districts on a grant basis, from moneys appropriated for the purposes of this section, for equipment, networking, and software to expand the current K-12 education statewide network.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1209-S.SL.pdf?cite=1993%20c%20336%20§%20707[1993 c 336 § 707]; ]

== 28A.650.035 - Gifts, grants, and endowments.
The superintendent of public instruction may receive such gifts, grants, and endowments from public or private sources as may be made from time to time, in trust or otherwise, for the use and benefit of the purposes of educational technology and expend the same or any income therefrom according to the terms of the gifts, grants, or endowments.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6572-S.SL.pdf?cite=2010%201st%20sp.s.%20c%209%20§%203[2010 1st sp.s. c 9 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1209-S.SL.pdf?cite=1993%20c%20336%20§%20708[1993 c 336 § 708]; ]

== 28A.650.040 - Rules.
The superintendent of public instruction shall adopt rules as necessary under chapter 34.05 RCW governing the operation and scope of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1209-S.SL.pdf?cite=1993%20c%20336%20§%20709[1993 c 336 § 709]; ]

== 28A.650.045 - Digital citizenship, internet safety, and media literacy—Best practices and recommendations—Annual review—Model policy update and checklist for future updates.
. [Empty]
.. By December 1, 2016, the office of the superintendent of public instruction shall develop best practices and recommendations for instruction in digital citizenship, internet safety, and media literacy, and report to the appropriate committees of the legislature, in accordance with RCW 43.01.036, on strategies to implement the best practices and recommendations statewide. The best practices and recommendations must be developed in consultation with an advisory committee as specified in (b) of this subsection. Best practices and recommendations must include instruction that provides guidance about thoughtful, safe, and strategic uses of online and other media resources, and education on how to apply critical thinking skills when consuming and producing information.

.. The office of the superintendent of public instruction must convene and consult with an advisory committee when developing best practices and recommendations for instruction in digital citizenship, internet safety, and media literacy. The advisory committee must include: Representatives from the Washington state school directors' association; experts in digital citizenship, internet safety, and media literacy; teacher-librarians as defined in RCW 28A.320.240; and other stakeholders, including parent associations, educators, and administrators. Recommendations produced by the committee may include, but are not limited to:

... Revisions to the state learning standards for educational technology, required under RCW 28A.655.075;

... Revisions to the model policy and procedures on electronic resources and internet safety developed by the Washington state school directors' association;

... School district processes necessary to develop customized district policies and procedures on electronic resources and internet safety;

... Best practices, resources, and models for instruction in digital citizenship, internet safety, and media literacy; and

.. Strategies that will support school districts in local implementation of the best practices and recommendations developed by the office of the superintendent of public instruction under (a) of this subsection.

. Beginning in the 2017-18 school year, a school district shall annually review its policy and procedures on electronic resources and internet safety. In reviewing and amending the policy and procedures, a school district must:

.. Involve a representation of students, parents or guardians, teachers, teacher-librarians, other school employees, administrators, and community representatives with experience or expertise in digital citizenship, media literacy, and internet safety issues;

.. Consider customizing the model policy and procedures on electronic resources and internet safety developed by the Washington state school directors' association;

.. Consider existing school district resources; and

.. Consider best practices, resources, and models for instruction in digital citizenship, internet safety, and media literacy, including methods to involve parents.

. [Empty]
.. By December 1, 2017, the Washington state school directors' association shall review and revise its model policy and procedures on electronic resources and internet safety to better support digital citizenship, media literacy, and internet safety in schools. The model policy and procedures must contain provisions requiring that media literacy resources consist of a balance of sources and perspectives.

.. By December 1, 2017, the Washington state school directors' association shall develop a checklist of items for school districts to consider when updating their policy and procedures under subsection (2) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5449-S.SL.pdf?cite=2017%20c%2090%20§%202[2017 c 90 § 2]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6273-S.SL.pdf?cite=2016%20c%2059%20§%202[2016 c 59 § 2]; ]

== 28A.650.050 - Digital citizenship, internet safety, and media literacy—Web-based location with links recommending practices and resources.
. The office of the superintendent of public instruction shall create a web-based location with links to recommended successful practices and resources to support digital citizenship, media literacy, and internet safety for use in the 2017-18 school year. The web-based location must incorporate the information gathered by the survey in section 3, chapter 90, Laws of 2017.

. Thereafter, the office of the superintendent of public instruction shall continue to identify and develop additional open educational resources to support digital citizenship, media literacy, and internet safety in schools for the web-based location.

. Media literacy resources must consist of a balance of sources and perspectives.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5449-S.SL.pdf?cite=2017%20c%2090%20§%204[2017 c 90 § 4]; ]

== 28A.650.900 - Findings—Intent—Part headings not law—1993 c 336.
See notes following RCW 28A.150.210.

[ ]

== 28A.650.901 - Findings—1993 c 336.
See note following RCW 28A.150.210.

[ ]

