= 28A.650 - Education technology.
:toc:

== 28A.650.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Digital citizenship" includes the norms of appropriate, responsible, and healthy behavior related to current technology use, including digital and media literacy, ethics, etiquette, and security. The term also includes the ability to access, analyze, evaluate, develop, produce, and interpret media, as well as internet safety and cyberbullying prevention and response.

. "Learning device" means an internet-accessible computer, tablet, or other device, with an appropriate operating system, software applications, and data security, that can be used to access curricula, educational web applications and websites, and learning management systems, and with telecommunications capabilities sufficient for videoconferencing.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1365-S2.SL.pdf?cite=2021%20c%20301%20§%202[2021 c 301 § 2]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5449-S.SL.pdf?cite=2017%20c%2090%20§%201[2017 c 90 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1209-S.SL.pdf?cite=1993%20c%20336%20§%20702[1993 c 336 § 702]; ]

== 28A.650.035 - Gifts, grants, and endowments.
The superintendent of public instruction may receive such gifts, grants, and endowments from public or private sources as may be made from time to time, in trust or otherwise, for the use and benefit of the purposes of educational technology and expend the same or any income therefrom according to the terms of the gifts, grants, or endowments.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6572-S.SL.pdf?cite=2010%201st%20sp.s.%20c%209%20§%203[2010 1st sp.s. c 9 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1209-S.SL.pdf?cite=1993%20c%20336%20§%20708[1993 c 336 § 708]; ]

== 28A.650.040 - Rules.
The superintendent of public instruction shall adopt rules as necessary under chapter 34.05 RCW governing the operation and scope of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1209-S.SL.pdf?cite=1993%20c%20336%20§%20709[1993 c 336 § 709]; ]

== 28A.650.045 - Digital citizenship, internet safety, and media literacy—Best practices and recommendations—Annual review—Model policy update and checklist for future updates.
. [Empty]
.. By December 1, 2016, the office of the superintendent of public instruction shall develop best practices and recommendations for instruction in digital citizenship, internet safety, and media literacy, and report to the appropriate committees of the legislature, in accordance with RCW 43.01.036, on strategies to implement the best practices and recommendations statewide. The best practices and recommendations must be developed in consultation with an advisory committee as specified in (b) of this subsection. Best practices and recommendations must include instruction that provides guidance about thoughtful, safe, and strategic uses of online and other media resources, and education on how to apply critical thinking skills when consuming and producing information.

.. The office of the superintendent of public instruction must convene and consult with an advisory committee when developing best practices and recommendations for instruction in digital citizenship, internet safety, and media literacy. The advisory committee must include: Representatives from the Washington state school directors' association; experts in digital citizenship, internet safety, and media literacy; teacher-librarians as defined in RCW 28A.320.240; and other stakeholders, including parent associations, educators, and administrators. Recommendations produced by the committee may include, but are not limited to:

... Revisions to the state learning standards for educational technology, required under RCW 28A.655.075;

... Revisions to the model policy and procedures on electronic resources and internet safety developed by the Washington state school directors' association;

... School district processes necessary to develop customized district policies and procedures on electronic resources and internet safety;

... Best practices, resources, and models for instruction in digital citizenship, internet safety, and media literacy; and

.. Strategies that will support school districts in local implementation of the best practices and recommendations developed by the office of the superintendent of public instruction under (a) of this subsection.

. Beginning in the 2017-18 school year, a school district shall annually review its policy and procedures on electronic resources and internet safety. In reviewing and amending the policy and procedures, a school district must:

.. Involve a representation of students, parents or guardians, teachers, teacher-librarians, other school employees, administrators, and community representatives with experience or expertise in digital citizenship, media literacy, and internet safety issues;

.. Consider customizing the model policy and procedures on electronic resources and internet safety developed by the Washington state school directors' association;

.. Consider existing school district resources; and

.. Consider best practices, resources, and models for instruction in digital citizenship, internet safety, and media literacy, including methods to involve parents.

. [Empty]
.. By December 1, 2017, the Washington state school directors' association shall review and revise its model policy and procedures on electronic resources and internet safety to better support digital citizenship, media literacy, and internet safety in schools. The model policy and procedures must contain provisions requiring that media literacy resources consist of a balance of sources and perspectives.

.. By December 1, 2017, the Washington state school directors' association shall develop a checklist of items for school districts to consider when updating their policy and procedures under subsection (2) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5449-S.SL.pdf?cite=2017%20c%2090%20§%202[2017 c 90 § 2]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6273-S.SL.pdf?cite=2016%20c%2059%20§%202[2016 c 59 § 2]; ]

== 28A.650.050 - Digital citizenship, internet safety, and media literacy—Web-based location with links recommending practices and resources.
. The office of the superintendent of public instruction shall create a web-based location with links to recommended successful practices and resources to support digital citizenship, media literacy, and internet safety for use in the 2017-18 school year. The web-based location must incorporate the information gathered by the survey in section 3, chapter 90, Laws of 2017.

. Thereafter, the office of the superintendent of public instruction shall continue to identify and develop additional open educational resources to support digital citizenship, media literacy, and internet safety in schools for the web-based location.

. Media literacy resources must consist of a balance of sources and perspectives.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5449-S.SL.pdf?cite=2017%20c%2090%20§%204[2017 c 90 § 4]; ]

== 28A.650.060 - Technology consultation, procurement, and training.
. Each educational service district shall provide technology consultation, procurement, and training, in consultation with teacher-librarians through school library information and technology programs as defined in RCW 28A.320.240, and as described in this section. An educational service district may meet the requirements of this section in cooperation with one or more other educational service districts.

. Technology consultation involves providing technical assistance and guidance to local school districts related to technology needs and financing, and may include consultation with other entities.

. [Empty]
.. Technology procurement involves negotiating for local school district purchasing and leasing of learning devices and peripheral devices, learning management systems, cybersecurity protection, device insurance, and other technology-related goods and services.

.. When selecting goods and services for procurement, the educational service district must consider a variety of student needs, as well as accessibility, age appropriateness, privacy and security, data storage and transfer capacity, and telecommunications capability.

.. Technology procurement may be performed in consultation and contract with the department of enterprise services under chapter 39.26 RCW.

. Technology training involves developing and offering direct services to local school districts related to staff development and capacity building to provide digital navigation services to students and their families. The educational service districts must seek to consult teacher-librarians and other relevant information technology programs to determine where there is a need and focus for this training. These services may be provided on a fee-for-service basis.

. Technology consultation, procurement, and training under this section must be provided to local public schools, as defined in RCW 28A.150.010, the Washington center for deaf and hard of hearing youth, and the school for the blind, in addition to local school districts. Technology training under this section may also be offered to child care providers.

. The educational service districts must cooperate with the office of the superintendent of public instruction to provide the data required under RCW 28A.650.070(1).

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1365-S2.SL.pdf?cite=2021%20c%20301%20§%203[2021 c 301 § 3]; ]

== 28A.650.065 - Technology grant program.
. Subject to the availability of amounts appropriated for this specific purpose, the office of the superintendent of public instruction shall develop and administer a technology grant program, as described in this section, to advance the following objectives:

.. Attain a universal 1:1 student to learning device ratio;

.. Expand technical support and training of school and district staff in using technology to support student learning; and

.. Develop district-based and school-based capacity to assist students and their families in accessing and using technology to support student learning.

. The following entities, individually or in cooperation, may apply to the office of the superintendent of public instruction for a grant under this section: A public school as defined in RCW 28A.150.010; a school district; an educational service district; the Washington center for deaf and hard of hearing youth; and the state school for the blind.

. At a minimum, grant applications must include:

.. The applicant's technology plan for accomplishing the goals of the grant program, the applicant's student demographics, including the percent of students eligible for free and reduced-price meals, and any specialized technology needs of the applicant's students, such as students with disabilities and English learners who may need adaptive or assistive technologies; and

.. A description of preexisting programs and funding sources used by the applicant to provide learning devices to students, staff, or both.

. When ranking and selecting applicants, the office of the superintendent of public instruction must prioritize both of the following:

.. Applicants without preexisting programs to provide a device for every student and that have 30 percent or more students eligible for free and reduced-price meals; and

.. Applicants with students who have specialized technology needs.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1365-S2.SL.pdf?cite=2021%20c%20301%20§%204[2021 c 301 § 4]; ]

== 28A.650.070 - Technology initiatives—Technology levies—Data—Reports.
. The office of the superintendent of public instruction shall collect and analyze the following data:

.. Demographic, distribution, and other data related to technology initiatives; and

.. Biennial survey data on school and school district progress to accomplish the objectives listed in RCW 28A.650.065(1).

. By November 1, 2022, and by November 1st every even year thereafter, the office of the superintendent of public instruction shall provide a report to the appropriate policy and fiscal committees of the legislature, in accordance with RCW 43.01.036, with:

.. A summary of the technology initiatives data collected under subsection (1) of this section;

.. The status of the state's progress in accomplishing the following: (i) Accelerate student access to learning devices and related goods and services; (ii) expand training programs and technical assistance on using technology to support student learning; and (iii) build the capacity of schools and districts to support digital navigation services for students and their families;

.. Recommendations for improving the administration and oversight of the technology initiatives; and

.. An update on innovative and collaborative activities occurring in communities across the state to support widespread public technology literacy and fluency, as well as student universal access to learning devices.

. By November 1, 2022, the office of the superintendent of public instruction shall survey districts, collect data, and provide a report to the appropriate policy and fiscal committees of the legislature that contains, at a minimum, the following:

.. A list of districts that have a separate technology levy;

.. The total amount of funding generated by the technology levies; and

.. A detailed breakdown on how the funds generated by the technology levies are being used, including, but not limited to, the number of technology devices being purchased with those funds, personnel costs related to servicing and maintaining those devices covered by those funds, and any training or professional development for use of technology provided with those funds.

. For the purposes of this section, "technology initiatives" means the technology grants awarded by the office of the superintendent of public instruction under RCW 28A.650.065, and the provision of technology consultation, procurement, and training by educational service districts under RCW 28A.650.060.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1365-S2.SL.pdf?cite=2021%20c%20301%20§%205[2021 c 301 § 5]; ]

