= 28A.190 - Residential education programs.
:toc:

== 28A.190.010 - Educational program for juveniles in detention facilities.
A program of education shall be provided for by the department of social and health services or the department of children, youth, and families and the several school districts of the state for common school-age persons who have been admitted to facilities staffed and maintained or contracted pursuant to RCW 13.40.320 by the department of social and health services or the department of children, youth, and families for the education and treatment of juveniles who have been diverted or who have been found to have committed a juvenile offense. The division of duties, authority, and liabilities of the department of social and health services or the department of children, youth, and families and the several school districts of the state respecting the educational programs shall be the same in all respects as set forth in this chapter respecting programs of education for state residential school residents. For the purposes of this section, the term "residential school" or "schools" as used in this chapter shall be construed to mean a facility staffed and maintained by the department of social and health services or the department of children, youth, and families or a program established under RCW 13.40.320, for the education and treatment of juvenile offenders on probation or parole. Nothing in this section shall prohibit a school district from utilizing the services of an educational service district subject to RCW 28A.310.180.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20720[2017 3rd sp.s. c 6 § 720]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2276.SL.pdf?cite=2014%20c%20157%20§%202[2014 c 157 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2495.SL.pdf?cite=1996%20c%2084%20§%201[1996 c 84 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20170[1990 c 33 § 170]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c98.pdf?cite=1983%20c%2098%20§%203[1983 c 98 § 3]; ]

== 28A.190.015 - "School district" defined—Application of RCW  13.04.145.
. For the purposes of this chapter, the term "school district" includes any educational service district that has entered into an agreement to provide a program of education for residential school residents or detention facility residents on behalf of the school district as a cooperative service program pursuant to RCW 28A.310.180.

. The provisions of RCW 13.04.145 apply throughout this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2276.SL.pdf?cite=2014%20c%20157%20§%201[2014 c 157 § 1]; ]

== 28A.190.020 - Educational programs for residential school residents—"Residential school" defined.
The term "residential school" as used in this chapter and RCW 72.01.200, 72.05.010, and 72.05.130 means Green Hill school, Naselle Youth Camp, Echo Glen, Lakeland Village, Rainier school, Yakima Valley school, Fircrest school, the Child Study and Treatment Center and Secondary School of western state hospital, and such other schools, camps, and centers as are now or hereafter established by the department of social and health services or the department of children, youth, and families for the diagnosis, confinement and rehabilitation of juveniles committed by the courts or for the care and treatment of persons who are exceptional in their needs by reason of mental and/or physical deficiency: PROVIDED, That the term shall not include the state schools for the deaf and blind or adult correctional institutions.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20721[2017 3rd sp.s. c 6 § 721]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2276.SL.pdf?cite=2014%20c%20157%20§%203[2014 c 157 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20171[1990 c 33 § 171]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c217.pdf?cite=1979%20ex.s.%20c%20217%20§%201[1979 ex.s. c 217 § 1]; ]

== 28A.190.030 - Educational programs for residential school residents—School district to conduct—Scope of duties and authority.
Each school district within which there is located a residential school shall, singly or in concert with another school district pursuant to RCW 28A.335.160 and 28A.225.250 or pursuant to chapter 39.34 RCW, conduct a program of education, including related student activities, for residents of the residential school. Except as otherwise provided for by contract pursuant to RCW 28A.190.050, the duties and authority of a school district and its employees to conduct such a program shall be limited to the following:

. The employment, supervision and control of administrators, teachers, specialized personnel and other persons, deemed necessary by the school district for the conduct of the program of education;

. The purchase, lease or rental and provision of textbooks, maps, audiovisual equipment, paper, writing instruments, physical education equipment and other instructional equipment, materials and supplies, deemed necessary by the school district for the conduct of the program of education;

. The development and implementation, in consultation with the superintendent or chief administrator of the residential school or his or her designee, of the curriculum;

. The conduct of a program of education, including related student activities, for residents who are three years of age and less than twenty-one years of age, and have not met high school graduation requirements as now or hereafter established by the state board of education and the school district which includes:

.. Not less than one hundred and eighty school days each school year;

.. Special education pursuant to RCW 28A.155.010 through 28A.155.100, and vocational education, as necessary to address the unique needs and limitations of residents; and

.. Such courses of instruction and school related student activities as are provided by the school district for nonresidential school students to the extent it is practical and judged appropriate for the residents by the school district after consultation with the superintendent or chief administrator of the residential school: PROVIDED, That a preschool special education program may be provided for residential school students with disabilities;

. The control of students while participating in a program of education conducted pursuant to this section and the discipline, suspension or expulsion of students for violation of reasonable rules of conduct adopted by the school district; and

. The expenditure of funds for the direct and indirect costs of maintaining and operating the program of education that are appropriated by the legislature and allocated by the superintendent of public instruction for the exclusive purpose of maintaining and operating residential school programs of education, and funds from federal and private grants, bequests and gifts made for the purpose of maintaining and operating the program of education.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5276.SL.pdf?cite=1995%20c%2077%20§%2019[1995 c 77 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20172[1990 c 33 § 172]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c341.pdf?cite=1985%20c%20341%20§%2013[1985 c 341 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c160.pdf?cite=1984%20c%20160%20§%203[1984 c 160 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c217.pdf?cite=1979%20ex.s.%20c%20217%20§%202[1979 ex.s. c 217 § 2]; ]

== 28A.190.040 - Educational programs for residential school residents—Duties and authority of department of children, youth, and families and residential school superintendent.
The duties and authority of the department of social and health services or the department of children, youth, and families and of each superintendent or chief administrator of a residential school to support each program of education conducted by a school district pursuant to RCW 28A.190.030, shall include the following:

. The provision of transportation for residential school students to and from the sites of the program of education through the purchase, lease or rental of school buses and other vehicles as necessary;

. The provision of safe and healthy building and playground space for the conduct of the program of education through the construction, purchase, lease or rental of such space as necessary;

. The provision of furniture, vocational instruction machines and tools, building and playground fixtures, and other equipment and fixtures for the conduct of the program of education through construction, purchase, lease or rental as necessary;

. The provision of heat, lights, telephones, janitorial services, repair services, and other support services for the vehicles, building and playground spaces, equipment and fixtures provided for in this section;

. The employment, supervision and control of persons to transport students and to maintain the vehicles, building and playground spaces, equipment and fixtures, provided for in this section;

. Clinical and medical evaluation services necessary to a determination by the school district of the educational needs of residential school students; and

. Such other support services and facilities as are reasonably necessary for the conduct of the program of education.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20722[2017 3rd sp.s. c 6 § 722]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20173[1990 c 33 § 173]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c217.pdf?cite=1979%20ex.s.%20c%20217%20§%203[1979 ex.s. c 217 § 3]; ]

== 28A.190.050 - Educational programs for residential school residents—Contracts between school district and department of children, youth, and families—Scope.
Each school district required to conduct a program of education pursuant to RCW 28A.190.030, and the department of social and health services and the department of children, youth, and families shall hereafter negotiate and execute a written contract for each school year or such longer period as may be agreed to which delineates the manner in which their respective duties and authority will be cooperatively performed and exercised, and any disputes and grievances resolved. Any such contract may provide for the performance of duties by a school district in addition to those set forth in RCW 28A.190.030 (1) through (5), including duties imposed upon the department of social and health services and the department of children, youth, and families and their agents pursuant to RCW 28A.190.040: PROVIDED, That funds identified in RCW 28A.190.030(6) and/or funds provided by the department of social and health services and the department of children, youth, and families are available to fully pay the direct and indirect costs of such additional duties and the district is otherwise authorized by law to perform such duties in connection with the maintenance and operation of a school district.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20723[2017 3rd sp.s. c 6 § 723]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20174[1990 c 33 § 174]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c217.pdf?cite=1979%20ex.s.%20c%20217%20§%204[1979 ex.s. c 217 § 4]; ]

== 28A.190.060 - Educational programs for residential school residents—Department of social and health services and department of children, youth, and families to give notice when need for reduction of staff—Liability upon failure.
The department of social and health services and the department of children, youth, and families shall provide written notice on or before April 15th of each school year to the superintendent of each school district conducting a program of education pursuant to this chapter of any foreseeable residential school closure, reduction in the number of residents, or any other cause for a reduction in the school district's staff for the next school year. In the event the department of social and health services and the department of children, youth, and families fail to provide notice as prescribed by this section, the departments shall be liable and responsible for the payment of the salary and employment related costs for the next school year of each school district employee whose contract the school district would have nonrenewed but for the failure of the departments to provide notice.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20724[2017 3rd sp.s. c 6 § 724]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2276.SL.pdf?cite=2014%20c%20157%20§%204[2014 c 157 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20175[1990 c 33 § 175]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c217.pdf?cite=1979%20ex.s.%20c%20217%20§%205[1979 ex.s. c 217 § 5]; ]

