= 28A.660 - Alternative route teacher certification.
:toc:

== 28A.660.005 - Findings—Declaration.
. The legislature finds and declares:

.. Teacher qualifications and effectiveness are the most important influences on student learning in schools;

.. Preparation of individuals to become well-qualified, effective teachers must be high quality;

.. Teachers who complete high-quality alternative route programs with intensive field-based experience, adequate coursework, and strong mentorship do as well or better than teachers who complete traditional preparation programs;

.. High-quality alternative route programs can provide more flexibility and expedience for individuals to transition from their current career to teaching;

.. High-quality alternative route programs can help school districts fill subject matter shortage areas and areas with shortages due to geographic location;

.. Regardless of route, all candidates for residency teacher certification must meet the high standards required by the state; and

.. Teachers need an adequate background in subject matter content if they are to teach it well, and should hold full, appropriate credentials in those subject areas.

. The legislature recognizes widespread concerns about the potential for teacher shortages and finds that classified instructional staff in public schools, current certificated staff, and unemployed certificate holders represent a great untapped resource for recruiting more teachers in critical shortage areas.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1906-S2.SL.pdf?cite=2007%20c%20396%20§%205[2007 c 396 § 5]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5695-S2.SL.pdf?cite=2001%20c%20158%20§%201[2001 c 158 § 1]; ]

== 28A.660.020 - Program design—Funding—Reports.
. [Empty]
.. Alternative route programs are partnerships between Washington professional educator standards board-approved preparation programs, Washington school districts, and other partners as appropriate. Program design of alternative route programs must evolve over time to reflect innovations and improvements in educator preparation.

.. The Washington professional educator standards board must construct rules that address the competitive grant process and program design.

. As provided in RCW 28A.410.210, it is the duty of the Washington professional educator standards board to establish policies for the approval of nontraditional preparation programs and to provide oversight and accountability related to the quality of these programs. In establishing and amending rules for alternative route programs, the Washington professional educator standards board shall:

.. Uphold design criteria for alternative route programs that are innovative and reflect evidence-based practice;

.. Ensure that approved partnerships reflect district engagement in their resident alternative route program as an integral part of their future workforce development, as well as school and student learning improvement strategies;

.. Issue certificates necessary for student teachers to serve as substitute teachers in classrooms within the residency school for up to ten days per school year;

.. Prioritize program designs tailored to the needs of experienced paraeducators and candidates of high academic attainment in, or with occupational industry experience relevant to, the subject area they intend to teach. In doing so the program designs must take into account school district demand for certain teacher credentials;

.. Expand access and opportunity for individuals to become teachers statewide; and

.. Give preference in admissions to applicants for alternative route programs who are eligible veterans or national guard members and who meet the entry requirements for the alternative route program.

. Beginning December 1, 2017, and by December 1st each odd-numbered year thereafter, the Washington professional educator standards board shall report to the education committees of the house of representatives and the senate the following outcomes as indicators that alternative route programs are meeting legislative intent through the regulation and oversight of the Washington professional educator standards board. In considering administrative rules for, and reporting outcomes of, alternative route programs, the Washington professional educator standards board shall examine the following data on alternative route program participants:

.. The number and percentage hired as certificated teachers;

.. The percentage from underrepresented populations;

.. Three-year and five-year retention rates of participants hired as certificated teachers;

.. The average hiring dates; and

.. The percentage hired by districts in which the participants completed their alternative route programs.

. Subject to the availability of amounts appropriated for this specific purpose, alternative route programs may apply for program funds to pay stipends to trained mentor teachers of interns during the mentored internship. The per intern amount of mentor stipend provided by state funds shall not exceed five hundred dollars.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1139-S2.SL.pdf?cite=2019%20c%20295%20§%20106[2019 c 295 § 106]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1654.SL.pdf?cite=2017%20c%2014%20§%201[2017 c 14 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6696-S2.SL.pdf?cite=2010%20c%20235%20§%20503[2010 c 235 § 503]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3098-S2.SL.pdf?cite=2006%20c%20263%20§%20816[2006 c 263 § 816]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6245-S.SL.pdf?cite=2004%20c%2023%20§%202[2004 c 23 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6052.SL.pdf?cite=2003%20c%20410%20§%201[2003 c 410 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5695-S2.SL.pdf?cite=2001%20c%20158%20§%203[2001 c 158 § 3]; ]

== 28A.660.035 - Partnership programs—Priority assistance in advancing cultural competency skills.
The office of the superintendent of public instruction shall identify school districts that have the most significant academic disparities among subgroups of students and for large numbers of those students, and districts that should receive priority for assistance in advancing cultural competency skills in their workforce. The Washington professional educator standards board shall provide assistance to the identified school districts to develop partnership programs between the districts and teacher preparation programs to provide alternative route programs under RCW 28A.660.020 and to recruit paraeducators and other persons in the local community to become certificated as teachers. An alternative route partnership program proposed by an identified school district shall receive priority eligibility for partnership grants under RCW 28A.660.020. To the maximum extent possible, the board shall coordinate the recruiting Washington teachers program under RCW 28A.415.370 with the alternative route partnership programs under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1139-S2.SL.pdf?cite=2019%20c%20295%20§%20107[2019 c 295 § 107]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1654.SL.pdf?cite=2017%20c%2014%20§%202[2017 c 14 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5973-S2.SL.pdf?cite=2009%20c%20468%20§%206[2009 c 468 § 6]; ]

== 28A.660.060 - Employment of certain personnel not affected.
School districts or approved private schools' ability to employ personnel under certification for emergency or temporary, substitute, or provisional duty as authorized by chapter 28A.410 RCW are not affected by the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5695-S2.SL.pdf?cite=2001%20c%20158%20§%2010[2001 c 158 § 10]; ]

== 28A.660.080 - Application—Conditional scholarship and loan repayment agreements.
Nothing in RCW 28B.102.020, 28B.102.030, 28B.102.045, 28B.102.055, 28B.102.080 through 28B.102.160, 43.79A.040, or sections 210 and 226, chapter 295, Laws of 2019 modifies or otherwise affects conditional scholarship or loan repayment agreements under this chapter or chapter 28B.102 RCW existing before May 8, 2019.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1139-S2.SL.pdf?cite=2019%20c%20295%20§%20228[2019 c 295 § 228]; ]

