= 28A.505 - School districts' budgets.
:toc:

== 28A.505.010 - Definitions.
The following terms when used in this chapter shall have the following meanings, unless where used the context thereof shall clearly indicate to the contrary:

. "Revenue" means an addition to assets of a fund of a school district during a fiscal period that is available to finance the fund's expenditures during the fiscal period. Revenue does not accompany the increase of liabilities or represent refunds of previous disbursements. Revenue may be in the form of cash or in the form of noncash assets such as donated commodities. Revenue for accrual basis expenditure funds is limited to amounts received in cash or noncash donations plus or minus adjustments for revenue accruals.

. "Accrual basis expenditures" mean expenditures incurred during a given fiscal period, whether paid or unpaid.

. "Cash basis expenditures" mean actual disbursements during a given fiscal period except for debt service, regardless of when liabilities are incurred, or the period of incurrence of expenditures.

. "Cash basis revenue" means actual receipt of revenue not adjusted for revenue accruals.

. "Revenue accruals" means those revenues anticipated to be received in cash after the close of the fiscal period that represent reimbursement for expenditures incurred by the end of the fiscal period.

. "Appropriation" means the maximum authorization during a given fiscal period to incur expenditures.

. "Disbursements" mean payments in cash, including but not limited to issuance of warrants.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c59.pdf?cite=1983%20c%2059%20§%201[1983 c 59 § 1]; 1975-'76 2nd ex.s. c 118 § 1; ]

== 28A.505.020 - Districts must utilize methods of revenue and expenditure recognition.
All school districts must utilize the following methods of revenue and expenditure recognition in budgeting, accounting and financial reporting:

. Recognize revenue as defined in RCW 28A.505.010(1) for all funds: PROVIDED, That school districts that elect the cash basis of expenditure recognition under subsection (2) of this section shall recognize revenue on the cash basis.

. Recognition of expenditures for all funds shall be on the accrual basis: PROVIDED, That school districts with under one thousand full time equivalent students for the preceding fiscal year may make a uniform election for all funds, except debt service funds, to be on the cash basis of expenditure recognition. Notification of such election shall be given to the state superintendent of public instruction in the budget of the school district and shall remain in effect for one full fiscal year.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20416[1990 c 33 § 416]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c59.pdf?cite=1983%20c%2059%20§%202[1983 c 59 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c18.pdf?cite=1980%20c%2018%20§%201[1980 c 18 § 1]; 1975-'76 2nd ex.s. c 118 § 2; ]

== 28A.505.030 - District fiscal year.
Beginning September 1, 1977 the fiscal year for all school districts shall be September 1 through August 31.

[ 1975-'76 2nd ex.s. c 118 § 3; ]

== 28A.505.040 - Budget—Four-year budget plan—Notice of completion—Copies—Review by educational service districts.
. On or before the tenth day of July in each year, all school districts shall prepare their budget for the ensuing fiscal year. The annual budget development process shall include the development or update of a four-year budget plan that includes a four-year enrollment projection. The four-year budget plan must include an estimate of funding necessary to maintain the continuing costs of program and service levels and any existing supplemental contract obligations.

. The completed budget must include a summary of the four-year budget plan and set forth the complete financial plan of the district for the ensuing fiscal year.

. [Empty]
.. Upon completion of their budgets, every school district shall electronically publish a notice stating that the district has completed the budget, posted it electronically, placed it on file in the school district administration office, and that a copy of the budget and a summary of the four-year budget plan will be furnished to any person who calls upon the district for it.

.. School districts shall submit one copy of their proposed budget and the four-year budget plan summary to their educational service districts for review and comment by July 10th. The superintendent of public instruction may delay the dates in this section if the state's operating budget is not finally approved by the legislature until after June 1st.

.. The office of the superintendent of public instruction shall consider the information provided under (b) of this subsection when ranking each school district by the financial health of the school district in order to provide information for districts to avoid potential financial difficulty, insolvency, or binding conditions.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1151-S.SL.pdf?cite=2019%20c%20208%20§%203[2019 c 208 § 3]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2017%203rd%20sp.s.%20c%2013%20§%20604[2017 3rd sp.s. c 13 § 604]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5806.SL.pdf?cite=1995%20c%20121%20§%201[1995 c 121 § 1]; 1975-'76 2nd ex.s. c 118 § 4; ]

== 28A.505.050 - Budget—Notice of meeting to adopt.
. Upon completion of their budgets as provided in RCW 28A.505.040, every school district shall publish a notice stating that the board of directors will meet for the purpose of fixing and adopting the budget of the district for the ensuing fiscal year.

. Such notice shall designate the date, time, and place of said meeting which shall occur no later than the thirty-first day of August for first-class school districts, and the first day of August for second-class school districts.

. The notice shall also state that any person may appear at the meeting and be heard for or against any part of such budget, the four-year budget plan, or any proposed changes to uses of enrichment funding under RCW 28A.505.240. The notice shall be electronically published and published at least once each week for two consecutive weeks in a newspaper of general circulation in the district, or, if there be none, in a newspaper of general circulation in the county or counties in which such district is a part. The last notice shall be published no later than seven days immediately prior to the hearing.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2017%203rd%20sp.s.%20c%2013%20§%20605[2017 3rd sp.s. c 13 § 605]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5806.SL.pdf?cite=1995%20c%20121%20§%202[1995 c 121 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20417[1990 c 33 § 417]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c59.pdf?cite=1983%20c%2059%20§%203[1983 c 59 § 3]; 1975-'76 2nd ex.s. c 118 § 5; ]

== 28A.505.060 - Budget—Hearing and adoption of—Copies filed with ESDs.
. On the date given in the notice as provided in RCW 28A.505.050 the school district board of directors shall meet at the time and place designated. Any person may appear at the meeting and be heard for or against any part of such budget, the four-year budget plan, or any proposed changes to uses of enrichment funding under RCW 28A.505.240.

. Such hearing may be continued not to exceed a total of two days: PROVIDED, That the budget must be adopted no later than August 31st in first-class school districts, and not later than August 1st in second-class school districts.

. Upon conclusion of the hearing, the board of directors shall fix and determine the appropriation from each fund contained in the budget separately, and shall by resolution adopt the budget, the four-year budget plan summary, and the four-year enrollment projection and the appropriations as so finally determined, and enter the same in the official minutes of the board: PROVIDED, That first-class school districts shall file copies of their adopted budget with their educational service district no later than September 3rd, and second-class school districts shall forward copies of their adopted budget to their educational service district no later than August 3rd for review, alteration and approval as provided for in RCW 28A.505.070 by the budget review committee.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2017%203rd%20sp.s.%20c%2013%20§%20606[2017 3rd sp.s. c 13 § 606]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20418[1990 c 33 § 418]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c59.pdf?cite=1983%20c%2059%20§%204[1983 c 59 § 4]; 1975-'76 2nd ex.s. c 118 § 6; ]

== 28A.505.070 - Budget review committee—Members—Review of budget, limitations.
The budget review committee shall fix and approve the amount of the appropriation from each fund of the budget of second-class districts not later than August 31st. No budget review committee shall knowingly approve any budget or appropriation that is in violation of this chapter or rules and regulations adopted by the superintendent of public instruction in accordance with RCW 28A.505.140(1). A copy of said budget shall be returned to the local school districts no later than September 10th.

Members of the budget review committee as referred to in this section shall consist of the educational service district superintendent or a representative thereof, a member of the local school district board of directors or a representative thereof, and a representative of the superintendent of public instruction.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20419[1990 c 33 § 419]; 1975-'76 2nd ex.s. c 118 § 7; ]

== 28A.505.080 - Budget—Disposition of copies.
Copies of the budgets for all local school districts, including the four-year budget plan prepared under RCW 28A.505.040, shall be filed with the superintendent of public instruction no later than September 10th. One copy will be retained by the educational service district.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1151-S.SL.pdf?cite=2019%20c%20208%20§%204[2019 c 208 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c128.pdf?cite=1984%20c%20128%20§%208[1984 c 128 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c59.pdf?cite=1983%20c%2059%20§%205[1983 c 59 § 5]; 1975-'76 2nd ex.s. c 118 § 8; ]

== 28A.505.090 - Budget—Format, classifications, mandatory.
Every school district budget shall be prepared, submitted and adopted in the format prescribed by the office of the superintendent of public instruction. The budget classifications contained in said format shall be in accordance with the accounting manual for public school districts, published by the office of the superintendent of public instruction and the office of the state auditor. Budgets prepared and adopted in a format other than that prescribed by the office of the superintendent of public instruction shall not be official and will have no legal effect.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c59.pdf?cite=1983%20c%2059%20§%206[1983 c 59 § 6]; 1975-'76 2nd ex.s. c 118 § 9; ]

== 28A.505.100 - Budget—Contents—Display of salaries.
. The budget must set forth the estimated revenues from all sources for the ensuing fiscal year, the estimated revenues for the fiscal year current at the time of budget preparation, the actual revenues for the last completed fiscal year, and the reserved and unreserved fund balances for each year. The estimated revenues from all sources for the ensuing fiscal year shall not include any revenue not anticipated to be available during that fiscal year. However, school districts, pursuant to RCW 28A.505.110, can be granted permission by the superintendent of public instruction to include as revenues in their budgets, receivables collectible in future fiscal years.

. [Empty]
.. The budget must set forth by detailed items or classes the estimated expenditures for the ensuing fiscal year, the estimated expenditures for the fiscal year current at the time of budget preparation, and the actual expenditures for the last completed fiscal year.

.. The budget must set forth:

... The state-funded basic education salary amounts, locally funded salary amounts, total salary amounts, and full-time equivalency for each individual certificated instructional staff, certificated administrative staff, and classified staff; and

... The high, low, and average annual salaries, which shall be displayed by job classification within each budget classification.

. In districts where negotiations have not been completed, the district may budget the salaries at the current year's rate and restrict fund balance for the amount of anticipated increase in salaries, so long as an explanation is attached to the budget on such restriction of fund balance.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2017%203rd%20sp.s.%20c%2013%20§%20603[2017 3rd sp.s. c 13 § 603]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20420[1990 c 33 § 420]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c59.pdf?cite=1983%20c%2059%20§%207[1983 c 59 § 7]; 1975-'76 2nd ex.s. c 118 § 10; ]

== 28A.505.110 - Budget—Including receivables collectible in future years—Limitations.
When a school district board is unable to prepare a budget or budget extension pursuant to RCW 28A.505.170 or 28A.505.180 in which the estimated revenues for the budgeted fiscal year plus the estimated fund balance at the beginning of the budgeted fiscal year less the ending reserved fund balance for the budgeted fiscal year do not at least equal the estimated expenditures for the budgeted fiscal year, the school district board may deliver a petition in writing, at least twenty days before the budget or budget extension is scheduled for adoption, to the superintendent of public instruction requesting permission to include receivables collectible in future years, in order to balance the budget. If such permission is granted, it shall be in writing, and it shall contain conditions, binding on the district, designed to improve the district's financial condition. Any budget or appropriation adopted by the board of directors without written permission from the superintendent of public instruction that contains estimated expenditures in excess of the total of estimated revenue for the budgeted fiscal year plus estimated fund balance at the beginning of the budgeted fiscal year less ending reserve fund balance for the budgeted fiscal year shall be null and void and shall not be considered an appropriation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20421[1990 c 33 § 421]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c59.pdf?cite=1983%20c%2059%20§%208[1983 c 59 § 8]; 1975-'76 2nd ex.s. c 118 § 11; ]

== 28A.505.120 - Withholding state funds upon district noncompliance—Notice of.
If a local school district fails to comply with any binding restrictions issued by the superintendent of public instruction, the allocation of state funds for support of the local school district may be withheld, pending an investigation of the reason for such noncompliance by the office of the superintendent of public instruction. Written notice of the intent to withhold state funds, with reasons stated for this action, shall be made to the school district by the office of the superintendent of public instruction before any portion of the state allocation is withheld.

[ 1975-'76 2nd ex.s. c 118 § 12; ]

== 28A.505.130 - Budget—Requirements for balancing estimated expenditures.
For each fund contained in the school district budget the estimated expenditures for the budgeted fiscal year must not be greater than the total of the estimated revenues for the budgeted fiscal year, the estimated fund balance at the beginning of the budgeted fiscal year less the estimated reserve fund balance at the end of the budgeted fiscal year, and the projected revenue from receivables collectible on future years as approved by the superintendent of public instruction for inclusion in the budget.

The proceeds of any interfund loan must not be used to balance the budget of the borrowing fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c59.pdf?cite=1983%20c%2059%20§%209[1983 c 59 § 9]; 1975-'76 2nd ex.s. c 118 § 13; ]

== 28A.505.140 - Rules for budgetary procedures—Review by superintendent—Separate accounting of state and local revenues—Notice of irregularity—Budget revisions.
. Notwithstanding any other provision of law, the superintendent of public instruction shall adopt such rules as will ensure proper budgetary procedures and practices, including monthly financial statements consistent with the provisions of RCW 43.09.200, and this chapter. By the 2019-20 school year, the rules must require school districts to provide separate accounting of state and local revenues to expenditures.

. If the superintendent of public instruction determines upon a review of the budget of any district that said budget does not comply with the budget procedures established by this chapter or by rules adopted by the superintendent of public instruction, or the provisions of RCW 43.09.200, the superintendent shall give written notice of this determination to the board of directors of the local school district.

. The local school district, notwithstanding any other provision of law, shall, within thirty days from the date the superintendent of public instruction issues a notice pursuant to subsection (2) of this section, submit a revised budget which meets the requirements of RCW 43.09.200, this chapter, and the rules of the superintendent of public instruction.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2017%203rd%20sp.s.%20c%2013%20§%20602[2017 3rd sp.s. c 13 § 602]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3098-S2.SL.pdf?cite=2006%20c%20263%20§%20202[2006 c 263 § 202]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20422[1990 c 33 § 422]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c59.pdf?cite=1983%20c%2059%20§%2010[1983 c 59 § 10]; 1975-'76 2nd ex.s. c 118 § 14; ]

== 28A.505.150 - Budgeted expenditures as appropriations—Interim expenditures—Transfer between budget classes—Liability for nonbudgeted expenditures.
Total budgeted expenditures for each fund as adopted in the budget of a school district shall constitute the appropriations of the district for the ensuing fiscal year and the board of directors shall be limited in the incurring of expenditures to the grand total of such appropriations. The board of directors shall incur no expenditures for any purpose in excess of the appropriation for each fund: PROVIDED, That no board of directors shall be prohibited from incurring expenditures for the payment of regular employees, for the necessary repairs and upkeep of the school plant, for the purchase of books and supplies, and for their participation in joint purchasing agencies authorized in RCW 28A.320.080 during the interim while the budget is being settled under RCW 28A.505.140: PROVIDED FURTHER, That transfers between budget classes may be made by the school district's chief administrative officer or finance officer, subject to such restrictions as may be imposed by the school district board of directors.

Directors, officers or employees who knowingly or negligently violate or participate in a violation of this section by the incurring of expenditures in excess of any appropriation(s) shall be held civilly liable, jointly and severally, for such expenditures in excess of such appropriation(s), including consequential damages following therefrom, for each such violation. If as a result of any civil or criminal action the violation is found to have been done knowingly, such director, officer, or employee who is found to have participated in such breach shall immediately forfeit his or her office or employment, and the judgment in any such action shall so provide.

Nothing in this section shall be construed to limit the duty of the attorney general to carry out the provisions of RCW 43.09.260, as now or hereafter amended.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20423[1990 c 33 § 423]; 1975-'76 2nd ex.s. c 118 § 15; ]

== 28A.505.160 - Appropriations lapse at end of fiscal year—Exception.
All appropriations for any school district upon which their budget is based shall lapse at the end of the fiscal year. At the expiration of said period all appropriations shall become null and void and any claim presented thereafter against any such appropriation for the fiscal year just closed shall be provided for in the appropriation for the next fiscal year: PROVIDED, That this shall not prevent payments upon incompleted improvements in progress at the close of the fiscal year.

[ 1975-'76 2nd ex.s. c 118 § 16; ]

== 28A.505.170 - First-class school districts—Emergency or additional appropriation resolutions—Procedure.
. Notwithstanding any other provision of this chapter, upon the happening of any emergency in first-class school districts caused by fire, flood, explosion, storm, earthquake, epidemic, riot, insurrection, or for the restoration to a condition of usefulness of any school district property, the usefulness of which has been destroyed by accident, and no provision has been made for such expenditures in the adopted appropriation, the board of directors, upon the adoption by the vote of the majority of all board members of a resolution stating the facts constituting the emergency, may make an appropriation therefor without notice or hearing.

. Notwithstanding any other provision of this chapter, if in first-class districts it becomes necessary to increase the amount of the appropriation, and if the reason is not one of the emergencies specifically enumerated in subsection (1) of this section, the school district board of directors, before incurring expenditures in excess of the appropriation, shall adopt a resolution stating the facts and the estimated amount of appropriation to meet it.

Such resolution shall be voted on at a public meeting, notice to be given in the manner provided in RCW 28A.505.050. Its introduction and passage shall require the vote of a majority of all members of the school district board of directors.

Any person may appear at the meeting at which the appropriation resolution is to be voted on and be heard for or against the adoption thereof.

Copies of all adopted appropriation resolutions shall be filed with the educational service district who shall forward one copy each to the office of the superintendent of public instruction. One copy shall be retained by the educational service district.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20424[1990 c 33 § 424]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c128.pdf?cite=1984%20c%20128%20§%209[1984 c 128 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c59.pdf?cite=1983%20c%2059%20§%2011[1983 c 59 § 11]; 1975-'76 2nd ex.s. c 118 § 17; ]

== 28A.505.180 - Second-class school districts—Additional appropriation resolutions—Procedure.
Notwithstanding any other provision of this chapter, if a second-class school district needs to increase the amount of the appropriation from any fund for any reason, the school district board of directors, before incurring expenditures in excess of appropriation, shall adopt a resolution stating the facts and estimating the amount of additional appropriation needed.

Such resolution shall be voted on at a public meeting, notice to be given in the manner provided by RCW 28A.505.050. Its introduction and passage shall require the vote of a majority of all members of the school district board of directors.

Any person may appear at the meeting at which the appropriation resolution is to be voted on and be heard for or against the adoption thereof.

Upon passage of the appropriation resolution the school district shall petition the superintendent of public instruction for approval to increase the amount of its appropriations in the manner prescribed in rules and regulations for such approval by the superintendent.

Copies of all appropriation resolutions approved by the superintendent of public instruction shall be filed by the office of the superintendent of public instruction with the educational service district.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20425[1990 c 33 § 425]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c128.pdf?cite=1984%20c%20128%20§%2010[1984 c 128 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c59.pdf?cite=1983%20c%2059%20§%2012[1983 c 59 § 12]; 1975-'76 2nd ex.s. c 118 § 18; ]

== 28A.505.200 - Repayment of federal moneys—Federal disallowance determination.
Each school district that receives federal moneys from or through the superintendent of public instruction shall comply with applicable federal requirements and shall repay expenditures subsequently disallowed by the federal government together with such interest as may be assessed by the federal government. Once a federal disallowance determination, decision, or order becomes final respecting federal moneys expended by a school district, the superintendent of public instruction may withhold all or a portion of the annual basic education allocation amounts otherwise due and apportionable to the school district as necessary to facilitate payment of the principal and interest to the federal government. The superintendent of public instruction may pay withheld basic education allocation moneys:

. To the school district before the close of the biennium and following the school district's repayment of moneys due the federal government, or the school district's commitment to an acceptable repayment plan, or both; or

. To the federal government, subject to the reappropriation of the withheld basic education allocation, moneys for the purpose of payment to the federal government.

No withholding of basic education allocation moneys may occur under this subsection until the superintendent of public instruction has first determined that the withholding should not substantially impair the school district's financial ability to provide the basic education program offerings required by statute.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c103.pdf?cite=1990%20c%20103%20§%201[1990 c 103 § 1]; ]

== 28A.505.230 - Condensed compliance reports—Second-class districts.
Any compliance reporting requirements as a result of laws in this chapter that apply to second-class districts may be submitted in accordance with RCW 28A.330.250.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5184-S.SL.pdf?cite=2011%20c%2045%20§%2035[2011 c 45 § 35]; ]

== 28A.505.240 - Enrichment levy spending plans—Preballot approval—Revised spending plan for voter-approved levies.
. As required by RCW 84.52.053(4), before a school district may submit an enrichment levy under RCW 84.52.053 to the voters, it must have received approval from the office of the superintendent of public instruction of an expenditure plan for the district's enrichment levy and other local revenues as defined in RCW 28A.150.276. Within thirty days after receiving the plan the office of the superintendent of public instruction must notify the school district whether the spending plan is approved. If the office of the superintendent of public instruction rejects a district's proposed spending plan, then the district may submit a revised spending plan, and the superintendent must approve or reject the revised submission within thirty days. The office of the superintendent of public instruction may approve a spending plan only if it determines that the enrichment levy and other local revenues as defined in RCW 28A.150.276(1) will be used solely for permitted enrichment activities as provided in RCW 28A.150.276(2).

. [Empty]
.. Except as provided in (b) of this subsection, after a school district has received voter approval for a levy for an enrichment levy under RCW 84.52.053, a school district may change its spending plan for the voter-approved levy by submitting a revised spending plan to the office of the superintendent of public instruction for review and approval. To revise a previously approved spending plan, the district must provide notice and an opportunity for review and comment at an open meeting of the school board, and the board must adopt the revised spending plan by resolution. The board must then submit the plan to the office of the superintendent of public instruction. Within thirty days after receiving the revised spending plan the office must notify the school district whether the revised spending plan is approved. The office of the superintendent of public instruction may approve a revised spending plan only if it determines that the enrichment levy and other local revenues as defined in RCW 28A.150.276(1) will be used solely for permitted enrichment activities as provided in RCW 28A.150.276(2).

.. If the superintendent has approved expenditures for specific purposes under (a) of this subsection, a district may change the relative amounts to be spent for those respective purposes for the same levy in subsequent years without having to first receive approval for the change from the office of the superintendent of public instruction if the district adopts the change as part of its annual budget proposal after a public hearing under RCW 28A.505.060.

. This section applies to taxes levied for collection beginning in calendar year 2020 and thereafter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6362-S2.SL.pdf?cite=2018%20c%20266%20§%20304[2018 c 266 § 304]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2017%203rd%20sp.s.%20c%2013%20§%20204[2017 3rd sp.s. c 13 § 204]; ]

