= 28A.165 - Learning assistance program.
:toc:

== 28A.165.005 - Purpose—Focus on reading literacy.
. This chapter is designed to: (a) Promote the use of data when developing programs to assist students who are not meeting academic standards and reduce disruptive behaviors in the classroom; and (b) guide school districts in providing the most effective and efficient practices when implementing supplemental instruction and services to assist students who are not meeting academic standards and reduce disruptive behaviors in the classroom.

. School districts implementing a learning assistance program shall focus first on addressing the needs of students in grades kindergarten through four who are deficient in reading or reading readiness skills to improve reading literacy.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2017%203rd%20sp.s.%20c%2013%20§%20403[2017 3rd sp.s. c 13 § 403]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5946-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%2018%20§%20201[2013 2nd sp.s. c 18 § 201]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2261-S.SL.pdf?cite=2009%20c%20548%20§%20701[2009 c 548 § 701]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5877-S.SL.pdf?cite=2004%20c%2020%20§%201[2004 c 20 § 1]; ]

== 28A.165.015 - Definitions.
Unless the context clearly indicates otherwise the definitions in this section apply throughout this chapter.

. "Basic skills areas" means reading, writing, and mathematics as well as readiness associated with these skills.

. "Participating student" means a student in kindergarten through grade twelve who scores below standard for his or her grade level using multiple measures of performance, including on the statewide student assessments or other assessments and performance measurement tools administered by the school or district and who is identified by the district to receive services.

. "Statewide student assessments" means one or more of the assessments administered by school districts as required under RCW 28A.655.070.

. "Students who are not meeting academic standards" means students with the greatest academic deficits in basic skills as identified by statewide, school, or district assessments or other performance measurement tools.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2017%203rd%20sp.s.%20c%2013%20§%20404[2017 3rd sp.s. c 13 § 404]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5946-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%2018%20§%20202[2013 2nd sp.s. c 18 § 202]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2261-S.SL.pdf?cite=2009%20c%20548%20§%20702[2009 c 548 § 702]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5877-S.SL.pdf?cite=2004%20c%2020%20§%202[2004 c 20 § 2]; ]

== 28A.165.035 - Program activities—Partnerships with local entities—Development and use of state menus of best practices and strategies.
. Use of best practices that have been demonstrated through research to be associated with increased student achievement magnifies the opportunities for student success. To the extent they are included as a best practice or strategy in one of the state menus or an approved alternative under this section or RCW 28A.655.235, the following are services and activities that may be supported by the learning assistance program:

.. Extended learning time opportunities occurring:

... Before or after the regular school day;

... On Saturday; and

... Beyond the regular school year;

.. Services under RCW 28A.320.190;

.. Professional development for certificated and classified staff that focuses on:

... The needs of a diverse student population;

... Specific literacy and mathematics content and instructional strategies; and

... The use of student work to guide effective instruction and appropriate assistance;

.. Consultant teachers to assist in implementing effective instructional practices by teachers serving participating students;

.. Tutoring support for participating students;

.. Outreach activities and support for parents of participating students, including employing parent and family engagement coordinators; and

.. Up to five percent of a district's learning assistance program allocation may be used for development of partnerships with community-based organizations, educational service districts, and other local agencies to deliver academic and nonacademic supports to participating students who are significantly at risk of not being successful in school to reduce barriers to learning, increase student engagement, and enhance students' readiness to learn. The school board must approve in an open meeting any community-based organization or local agency before learning assistance funds may be expended.

. In addition to the state menu developed under RCW 28A.655.235, the office of the superintendent of public instruction shall convene a panel of experts, including the Washington state institute for public policy, to develop additional state menus of best practices and strategies for use in the learning assistance program to assist struggling students at all grade levels in English language arts and mathematics and reduce disruptive behaviors in the classroom. The office of the superintendent of public instruction shall publish the state menus by July 1, 2015, and update the state menus by each July 1st thereafter.

. [Empty]
.. Beginning in the 2016-17 school year, except as provided in (b) of this subsection, school districts must use a practice or strategy that is on a state menu developed under subsection (2) of this section or RCW 28A.655.235.

.. Beginning in the 2016-17 school year, school districts may use a practice or strategy that is not on a state menu developed under subsection (2) of this section for two school years initially. If the district is able to demonstrate improved outcomes for participating students over the previous two school years at a level commensurate with the best practices and strategies on the state menu, the office of the superintendent of public instruction shall approve use of the alternative practice or strategy by the district for one additional school year. Subsequent annual approval by the superintendent of public instruction to use the alternative practice or strategy is dependent on the district continuing to demonstrate increased improved outcomes for participating students.

.. Beginning in the 2016-17 school year, school districts may enter cooperative agreements with state agencies, local governments, or school districts for administrative or operational costs needed to provide services in accordance with the state menus developed under this section and RCW 28A.655.235.

. School districts are encouraged to implement best practices and strategies from the state menus developed under this section and RCW 28A.655.235 before the use is required.

. School districts may use learning assistance program allocations to meet the screening and intervention requirements of RCW 28A.320.260, even if the student being screened or provided with supports is not eligible to participate in the learning assistance program. The learning assistance program allocations may also be used for school district staff trainings necessary to implement the provisions of RCW 28A.320.260.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6162-S2.SL.pdf?cite=2018%20c%2075%20§%207[2018 c 75 § 7]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1541-S4.SL.pdf?cite=2016%20c%2072%20§%20803[2016 c 72 § 803]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5946-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%2018%20§%20203[2013 2nd sp.s. c 18 § 203]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6673-S2.SL.pdf?cite=2008%20c%20321%20§%204[2008 c 321 § 4]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5877-S.SL.pdf?cite=2004%20c%2020%20§%204[2004 c 20 § 4]; ]

== 28A.165.055 - Funds—Appropriation and distribution.
. The funds for the learning assistance program shall be appropriated in accordance with RCW 28A.150.260 and the omnibus appropriations act. The distribution formula is for school district allocation purposes only, except as provided in RCW 28A.150.260(10)(a)(ii), but all funds appropriated for the learning assistance program must be expended for the purposes of RCW 28A.165.005 through 28A.165.065.

. A district's high poverty-based allocation is generated by its qualifying schools as defined in RCW 28A.150.260(10) and must be expended by the district for those schools. This funding must supplement and not supplant the district's expenditures under this chapter for those schools.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6362-S2.SL.pdf?cite=2018%20c%20266%20§%20104[2018 c 266 § 104]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2017%203rd%20sp.s.%20c%2013%20§%20405[2017 3rd sp.s. c 13 § 405]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5946-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%2018%20§%20205[2013 2nd sp.s. c 18 § 205]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2261-S.SL.pdf?cite=2009%20c%20548%20§%20703[2009 c 548 § 703]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6673-S2.SL.pdf?cite=2008%20c%20321%20§%2010[2008 c 321 § 10]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1066.SL.pdf?cite=2005%20c%20489%20§%201[2005 c 489 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5877-S.SL.pdf?cite=2004%20c%2020%20§%206[2004 c 20 § 6]; ]

== 28A.165.065 - Monitoring.
To ensure that school districts are meeting the requirements of this chapter, the superintendent of public instruction shall monitor learning assistance programs no less than once every four years. The primary purpose of program monitoring is to evaluate the effectiveness of a district's allocation and expenditure of resources and monitor school district fidelity in implementing best practices. The office of the superintendent of public instruction may provide technical assistance to school districts to improve the effectiveness of a learning assistance program.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5946-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%2018%20§%20206[2013 2nd sp.s. c 18 § 206]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5877-S.SL.pdf?cite=2004%20c%2020%20§%207[2004 c 20 § 7]; ]

== 28A.165.075 - Rules.
The superintendent of public instruction shall adopt rules in accordance with chapter 34.05 RCW that are necessary to implement this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5877-S.SL.pdf?cite=2004%20c%2020%20§%208[2004 c 20 § 8]; ]

== 28A.165.085 - Condensed compliance reports—Second-class districts.
Any compliance reporting requirements as a result of laws in this chapter that apply to second-class districts may be submitted in accordance with RCW 28A.330.250.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5184-S.SL.pdf?cite=2011%20c%2045%20§%206[2011 c 45 § 6]; ]

== 28A.165.100 - Entrance and exit performance data—Report by school districts—Report by the office of the superintendent of public instruction.
. School districts shall record in the statewide individual student data system annual entrance and exit performance data for each student participating in the learning assistance program according to specifications established by the office of the superintendent of public instruction.

. By August 1, 2014, and each September 30th thereafter, school districts shall report to the office of the superintendent of public instruction, using a common format prepared by the office:

.. The amount of academic growth gained by students participating in the learning assistance program;

.. The number of students who gain at least one year of academic growth;

.. The specific practices, activities, and programs used by each school building that received learning assistance program funding; and

.. Other data if required by the office of the superintendent of public instruction to demonstrate the efficacy of the learning assistance program expenditures to show student academic growth gains.

. By January 1, 2020, and each January 1st thereafter, the office of the superintendent of public instruction shall compile the school district data reported as required by subsection (2) of this section, and report, in compliance with RCW 43.01.036, to the appropriate committees of the legislature with the annual and longitudinal gains for the specific practices, activities, and programs used by the school districts and schools to show which are the most effective. The data must be disaggregated by student subgroups.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1151-S.SL.pdf?cite=2019%20c%20208%20§%201[2019 c 208 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5946-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%2018%20§%20204[2013 2nd sp.s. c 18 § 204]; ]

