= 28A.500 - Local effort assistance.
:toc:

== 28A.500.010 - Local effort assistance funding—Purpose—Not basic education.
The legislature intends to continue providing local effort assistance funding to school districts. Local effort assistance provides schools in property-poor districts with funding for locally determined activities that enrich the state's program of basic education, thereby enhancing equity in students' access to extracurricular activities and similar enrichments. The purpose of these funds is to mitigate the effect that above average property tax rates might have on the ability of a school district to raise local revenues to supplement the state's basic program of education. These funds serve to equalize the property tax rates that individual taxpayers would pay for such levies and to provide tax relief to taxpayers in high tax rate school districts.

Local effort assistance funding is not part of the state's statutory program of basic education, nor are allocations for it part of the district's basic education allocation. Beginning September 1, 2019, and subject to RCW 28A.150.276, districts may use local effort assistance funding only to enrich the state's statutory program of basic education.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2017%203rd%20sp.s.%20c%2013%20§%20205[2017 3rd sp.s. c 13 § 205]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5298-S.SL.pdf?cite=1999%20c%20317%20§%201[1999 c 317 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2069-S.SL.pdf?cite=1997%20c%20259%20§%204[1997 c 259 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1495.SL.pdf?cite=1993%20c%20410%20§%201[1993 c 410 § 1]; 1993 c 465 § 2; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1932-S.SL.pdf?cite=1992%20c%2049%20§%202[1992 c 49 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987ex1c2.pdf?cite=1987%201st%20ex.s.%20c%202%20§%20102[1987 1st ex.s. c 2 § 102]; ]

== 28A.500.015 - Annual local effort assistance funding—Formulas—Not basic education.
. Beginning in calendar year 2020 and each calendar year thereafter, the state must provide state local effort assistance funding to supplement school district enrichment levies as provided in this section.

. [Empty]
.. For an eligible school district with an actual enrichment levy rate that is less than one dollar and fifty cents per thousand dollars of assessed value in the school district, the annual local effort assistance funding is equal to the school district's maximum local effort assistance multiplied by a fraction equal to the school district's actual enrichment levy rate divided by one dollar and fifty cents per thousand dollars of assessed value in the school district.

.. For an eligible school district with an actual enrichment levy rate that is equal to or greater than one dollar and fifty cents per thousand dollars of assessed value in the school district, the annual local effort assistance funding is equal to the school district's maximum local effort assistance.

.. Beginning in calendar year 2022, for state-tribal education compact schools established under chapter 28A.715 RCW, the annual local effort assistance funding is equal to the actual enrichment levy per student as calculated by the superintendent of public instruction for the previous year for the school district in which the state-tribal education compact school is located, up to a maximum per student amount of one thousand five hundred fifty dollars as increased by inflation from the 2019 calendar year, multiplied by the student enrollment of the state-tribal education compact school in the prior school year.

.. For a school district that meets the criteria in this subsection and is located west of the Cascades in a county that borders another state, the annual local effort assistance funding is equal to the local effort assistance funding authorized under (b) of this subsection and additional local effort assistance funding equal to the following amounts:

... Two hundred forty-six dollars per pupil in the 2019-20 school year for a school district with more than twenty-five thousand annual full-time equivalent students; and

... Two hundred eighty-six dollars per pupil in the 2019-20 school year for a school district with more than twenty thousand annual full-time equivalent enrolled students but fewer than twenty-five thousand annual full-time equivalent enrolled students.

. The state local effort assistance funding provided under this section is not part of the state's program of basic education deemed by the legislature to comply with the requirements of Article IX, section 1 of the state Constitution.

. The definitions in this subsection apply throughout this section unless the context clearly requires otherwise.

.. "Eligible school district" means a school district where the amount generated by a levy of one dollar and fifty cents per thousand dollars of assessed value in the school district, divided by the school district's total student enrollment in the prior school year, is less than the state local effort assistance threshold.

.. For the purpose of this section, "inflation" means, for any school year, the rate of the yearly increase of the previous calendar year's annual average consumer price index for all urban consumers, Seattle area, using the official current base compiled by the bureau of labor statistics, United States department of labor.

.. "Maximum local effort assistance" means the difference between the following:

... The school district's actual prior school year enrollment multiplied by the state local effort assistance threshold; and

... The amount generated by a levy of one dollar and fifty cents per thousand dollars of assessed value in the school district.

.. "Prior school year" means the most recent school year completed prior to the year in which the state local effort assistance funding is to be distributed.

.. "State local effort assistance threshold" means one thousand five hundred fifty dollars per student, increased for inflation beginning in calendar year 2020.

.. "Student enrollment" means the average annual full-time equivalent student enrollment.

. For districts in a high/nonhigh relationship, the enrollments of the nonhigh students attending the high school shall only be counted by the nonhigh school districts for purposes of funding under this section.

. For school districts participating in an innovation academy cooperative established under RCW 28A.340.080, enrollments of students attending the academy shall be adjusted so that each participant district receives its proportional share of student enrollments for purposes of funding under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5313-S.SL.pdf?cite=2019%20c%20410%20§%201[2019 c 410 § 1]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6362-S2.SL.pdf?cite=2018%20c%20266%20§%20303[2018 c 266 § 303]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2017%203rd%20sp.s.%20c%2013%20§%20206[2017 3rd sp.s. c 13 § 206]; ]

== 28A.500.040 - Distribution of funds.
Local effort assistance funds shall be distributed to qualifying districts as follows:

. Thirty percent in April;

. Twenty-three percent in May;

. Two percent in June;

. Seventeen percent in August;

. Nine percent in October;

. Seventeen percent in November; and

. Two percent in December.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5298-S.SL.pdf?cite=1999%20c%20317%20§%204[1999 c 317 § 4]; ]

== 28A.500.060 - Condensed compliance reports—Second-class districts.
Any compliance reporting requirements as a result of laws in this chapter that apply to second-class districts may be submitted in accordance with RCW 28A.330.250.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5184-S.SL.pdf?cite=2011%20c%2045%20§%2034[2011 c 45 § 34]; ]

== 28A.500.900 - Effective date—1999 c 317.
This act takes effect January 1, 2000.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5298-S.SL.pdf?cite=1999%20c%20317%20§%205[1999 c 317 § 5]; ]

