= 28A.640 - Sexual equality.
:toc:

== 28A.640.010 - Purpose—Discrimination prohibited.
Inequality in the educational opportunities afforded women and girls at all levels of the public schools in Washington state is a breach of Article XXXI, section 1, Amendment 61, of the Washington state Constitution, requiring equal treatment of all citizens regardless of sex. This violation of rights has had a deleterious effect on the individuals affected and on society. Recognizing the benefit to our state and nation of equal educational opportunities for all students, discrimination on the basis of sex for any student in grades K-12 of the Washington public schools is prohibited.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c226.pdf?cite=1975%201st%20ex.s.%20c%20226%20§%201[1975 1st ex.s. c 226 § 1]; ]

== 28A.640.020 - Regulations, guidelines to eliminate discrimination—Scope—Sexual harassment policies.
. The superintendent of public instruction shall develop regulations and guidelines to eliminate sex discrimination as it applies to public school employment, counseling and guidance services to students, recreational and athletic activities for students, access to course offerings, and in textbooks and instructional materials used by students.

.. Specifically with respect to public school employment, all schools shall be required to:

... Maintain credential requirements for all personnel without regard to sex;

... Make no differentiation in pay scale on the basis of sex;

... Assign school duties without regard to sex except where such assignment would involve duty in areas or situations, such as but not limited to a shower room, where persons might be disrobed;

... Provide the same opportunities for advancement to males and females; and

.. Make no difference in conditions of employment including, but not limited to, hiring practices, leaves of absence, hours of employment, and assignment of, or pay for, instructional and noninstructional duties, on the basis of sex.

.. Specifically with respect to counseling and guidance services for students, they shall be made available to all students equally. All certificated personnel shall be required to stress access to all career and vocational opportunities to students without regard to sex.

.. Specifically with respect to recreational and athletic activities, they shall be offered to all students without regard to sex. Schools may provide separate teams for each sex. Schools which provide the following shall do so with no disparities based on sex: Equipment and supplies; medical care; services and insurance; transportation and per diem allowances; opportunities to receive coaching and instruction; laundry services; assignment of game officials; opportunities for competition, publicity and awards; scheduling of games and practice times including use of courts, gyms, and pools: PROVIDED, That such scheduling of games and practice times shall be determined by local administrative authorities after consideration of the public and student interest in attending and participating in various recreational and athletic activities. Each school which provides showers, toilets, or training room facilities for athletic purposes shall provide comparable facilities for both sexes. Such facilities may be provided either as separate facilities or shall be scheduled and used separately by each sex.

The superintendent of public instruction shall also be required to develop a student survey to distribute every three years to each local school district in the state to determine student interest for male/female participation in specific sports.

.. Specifically with respect to course offerings, all classes shall be required to be available to all students without regard to sex: PROVIDED, That separation is permitted within any class during sessions on sex education or gym classes.

.. Specifically with respect to textbooks and instructional materials, which shall also include, but not be limited to, reference books and audiovisual materials, they shall be required to adhere to the guidelines developed by the superintendent of public instruction to implement the intent of this chapter: PROVIDED, That this subsection shall not be construed to prohibit the introduction of material deemed appropriate by the instructor for educational purposes.

. [Empty]
.. By December 31, 1994, the superintendent of public instruction shall develop criteria for use by school districts in developing sexual harassment policies as required under (b) of this subsection. The criteria shall address the subjects of grievance procedures, remedies to victims of sexual harassment, disciplinary actions against violators of the policy, and other subjects at the discretion of the superintendent of public instruction. Disciplinary actions must conform with collective bargaining agreements and state and federal laws. The superintendent of public instruction also shall supply sample policies to school districts upon request.

.. By June 30, 1995, every school district shall adopt and implement a written policy concerning sexual harassment. The policy shall apply to all school district employees, volunteers, parents, and students, including, but not limited to, conduct between students.

.. School district policies on sexual harassment shall be reviewed by the superintendent of public instruction considering the criteria established under (a) of this subsection as part of the monitoring process established in RCW 28A.640.030.

.. The school district's sexual harassment policy shall be conspicuously posted throughout each school building, and provided to each employee. A copy of the policy shall appear in any publication of the school or school district setting forth the rules, regulations, procedures, and standards of conduct for the school or school district.

.. Each school shall develop a process for discussing the district's sexual harassment policy. The process shall ensure the discussion addresses the definition of sexual harassment and issues covered in the sexual harassment policy.

.. "Sexual harassment" as used in this section means unwelcome sexual advances, requests for sexual favors, sexually motivated physical contact, or other verbal or physical conduct or communication of a sexual nature if:

... Submission to that conduct or communication is made a term or condition, either explicitly or implicitly, of obtaining an education or employment;

... Submission to or rejection of that conduct or communication by an individual is used as a factor in decisions affecting that individual's education or employment; or

... That conduct or communication has the purpose or effect of substantially interfering with an individual's educational or work performance, or of creating an intimidating, hostile, or offensive educational or work environment.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2153-S.SL.pdf?cite=1994%20c%20213%20§%201[1994 c 213 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c226.pdf?cite=1975%201st%20ex.s.%20c%20226%20§%202[1975 1st ex.s. c 226 § 2]; ]

== 28A.640.030 - Administration.
The office of the superintendent of public instruction shall be required to monitor the compliance by local school districts with this chapter, shall establish a compliance timetable and regulations for enforcement of this chapter, and shall establish guidelines for affirmative action programs to be adopted by all school districts.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c226.pdf?cite=1975%201st%20ex.s.%20c%20226%20§%203[1975 1st ex.s. c 226 § 3]; ]

== 28A.640.040 - Civil relief for violations.
Any person aggrieved by a violation of this chapter, or aggrieved by the violation of any regulation or guideline adopted hereunder, shall have a right of action in superior court for civil damages and such equitable relief as the court shall determine.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c226.pdf?cite=1975%201st%20ex.s.%20c%20226%20§%204[1975 1st ex.s. c 226 § 4]; ]

== 28A.640.050 - Enforcement—Superintendent's orders, scope.
The superintendent of public instruction shall have the power to enforce and obtain compliance with the provisions of this chapter and the regulations and guidelines adopted pursuant thereto by appropriate order made pursuant to chapter 34.05 RCW, which order, by way of illustration, may include, the termination of all or part of state apportionment or categorical moneys to the offending school district, the termination of specified programs in which violations may be flagrant within the offending school district, the institution of a mandatory affirmative action program within the offending school district, and the placement of the offending school district on probation with appropriate sanctions until compliance is achieved.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c226.pdf?cite=1975%201st%20ex.s.%20c%20226%20§%205[1975 1st ex.s. c 226 § 5]; ]

== 28A.640.900 - Chapter supplementary.
This chapter shall be supplementary to, and shall not supersede, existing law and procedures and future amendments thereto relating to unlawful discrimination based on sex.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c226.pdf?cite=1975%201st%20ex.s.%20c%20226%20§%206[1975 1st ex.s. c 226 § 6]; ]

