= 28A.413 - Paraeducators.
:toc:

== 28A.413.005 - Findings.
Paraeducators provide the majority of instruction in programs designed by the legislature to reduce the opportunity gap. By setting common statewide standards, requiring training in the standards, and offering career development for paraeducators, as well as training for teachers and principals who work with paraeducators, students in these programs have a better chance of succeeding.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1115-S.SL.pdf?cite=2017%20c%20237%20§%201[2017 c 237 § 1]; ]

== 28A.413.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Advanced paraeducator certificate" means a credential earned by a paraeducator who may have the following duties: Assisting in highly impacted classrooms, assisting in specialized instructional support and instructional technology applications, mentoring and coaching other paraeducators, and acting as a short-term emergency substitute teacher.

. "Board" means the paraeducator board established in RCW 28A.413.020.

. "English language learner programs" means the English language learners program, the transitional bilingual instruction program, and the federal limited English proficiency program.

. "English language learner certificate" means a credential earned by a paraeducator working with students in English language learner programs.

. "Paraeducator" means a classified public school or school district employee who works under the supervision of a certificated or licensed staff member to support and assist in providing instructional and other services to students and their families. Paraeducators are not considered certificated instructional staff as that term and its meaning are used in this title.

. "Special education certificate" means a credential earned by a paraeducator working with students in special education programs.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1115-S.SL.pdf?cite=2017%20c%20237%20§%202[2017 c 237 § 2]; ]

== 28A.413.020 - Paraeducator board.
. [Empty]
.. The paraeducator board is created, consisting of nine members to be appointed to four-year terms.

.. Vacancies on the board must be filled by appointment or reappointment as described in subsection (2) of this section to terms of four years.

.. No person may serve as a member of the board for more than two consecutive full four-year terms.

.. The governor must biennially appoint the chair of the board. No board member may serve as chair for more than four consecutive years.

. Appointments to the board must be made as follows, subject to confirmation by the senate:

.. The superintendent of public instruction shall appoint a basic education paraeducator, a special education paraeducator, an English language learner paraeducator, a teacher, a principal, and a representative of the office of the superintendent of public instruction;

.. The Washington state parent teacher association shall appoint a parent whose child receives instructional support from a paraeducator;

.. The state board for community and technical colleges shall appoint a representative of the community and technical college system; and

.. The student achievement council shall appoint a representative of a four-year institution of higher education as defined in RCW 28B.10.016.

. The professional educator standards board shall administer the board.

. Each member of the board must be compensated in accordance with RCW 43.03.240 and must be reimbursed for travel expenses incurred in carrying out the duties of the board in accordance with RCW 43.03.050 and 43.03.060.

. Members of the board may create informal advisory groups as needed to inform the board's work.

. The governor may remove a member of the board for neglect of duty, misconduct, malfeasance or misfeasance in office, or for incompetency or unprofessional conduct as defined in chapter 18.130 RCW. In such a case, the governor shall file with the secretary of state a statement of the causes for and the order of removal from the board, and the secretary of state shall send a certified copy of the statement of causes and order of removal to the last known post office address of the member.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1115-S.SL.pdf?cite=2017%20c%20237%20§%203[2017 c 237 § 3]; ]

== 28A.413.030 - Board—Powers and duties—Rules—Superintendent of public instruction as administrator of rules.
. The paraeducator board has the following powers and duties:

.. Based on the recommendations of the paraeducator work group established in chapter 136, Laws of 2014, adopt: (i) Minimum employment requirements for paraeducators, as described in RCW 28A.413.040; and (ii) paraeducator standards of practice, as described in RCW 28A.413.050;

.. Establish requirements and policies for a general paraeducator certificate, as described in RCW 28A.413.070;

.. Based on the recommendations of the paraeducator work group established in chapter 136, Laws of 2014, establish requirements and policies for subject matter certificates in English language learner and special education, as described in RCW 28A.413.080;

.. Based on the recommendations of the paraeducator work group established in chapter 136, Laws of 2014, establish requirements and policies for an advanced paraeducator certificate, as described in RCW 28A.413.090;

.. By September 1, 2018, approve, and develop if necessary, courses required to meet the provisions of this chapter, where the courses are offered in a variety of means that will limit cost and improve access;

.. Make policy recommendations, as necessary, for a paraeducator career ladder that will increase opportunities for paraeducator advancement through advanced education, professional learning, and increased instructional responsibility;

.. Collaborate with the office of the superintendent of public instruction to adapt the electronic educator certification process to include paraeducator certificates; and

.. Adopt rules under chapter 34.05 RCW that are necessary for the effective and efficient implementation of this chapter.

. The superintendent of public instruction shall act as the administrator of any such rules and have the power to issue any paraeducator certificates and revoke the same in accordance with board rules.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1115-S.SL.pdf?cite=2017%20c%20237%20§%204[2017 c 237 § 4]; ]

== 28A.413.040 - Minimum employment requirements.
. [Empty]
.. A person working as a paraeducator for a school district before or during the 2017-18 school year must meet the requirements of subsection (2) of this section by the date of hire for the 2019-20 school year or any subsequent school year.

.. A person who has not previously worked as a paraeducator for a school district must meet the requirements of subsection (2) of this section by the date of hire for the 2018-19 school year or any subsequent school year.

. The minimum employment requirements for paraeducators are as provided in this subsection. A paraeducator must:

.. Be at least eighteen years of age and hold a high school diploma or its equivalent; and

.. [Empty]
... Have received a passing grade on the education testing service paraeducator assessment; or

... Hold an associate of arts degree; or

... Have earned seventy-two quarter credits or forty-eight semester credits at an institution of higher education; or

... Have completed a registered apprenticeship program.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6388-S.SL.pdf?cite=2018%20c%20153%20§%201[2018 c 153 § 1]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1115-S.SL.pdf?cite=2017%20c%20237%20§%205[2017 c 237 § 5]; ]

== 28A.413.050 - Standards of practice.
. The board shall adopt state standards of practice for paraeducators that are based on the recommendations of the paraeducator work group established in chapter 136, Laws of 2014. These standards must include:

.. Supporting instructional opportunities;

.. Demonstrating professionalism and ethical practices;

.. Supporting a positive and safe learning environment;

.. Communicating effectively and participating in the team process; and

.. The standards of practice developed by the Washington professional educator standards board under RCW 28A.410.260.

. By January 1, 2020, in order to ensure that paraeducators can recognize signs of emotional or behavioral distress in students and appropriately refer students for assistance and support, the board shall incorporate into the standards of practice for paraeducators adopted under subsection (1) of this section the social-emotional learning standards, benchmarks, and related competencies described in RCW 28A.410.270.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5044-S.SL.pdf?cite=2021%20c%20197%20§%2012[2021 c 197 § 12]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5082-S2.SL.pdf?cite=2019%20c%20386%20§%205[2019 c 386 § 5]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1115-S.SL.pdf?cite=2017%20c%20237%20§%206[2017 c 237 § 6]; ]

== 28A.413.060 - Fundamental course of study.
. School districts must implement this section only in school years for which state funding is appropriated specifically for the purposes of this section and only for the number of days that are funded by the appropriation.

. School districts must provide a four-day fundamental course of study on the state standards of practice, as defined by the board, to paraeducators who have not completed the course, either in the district or in another district within the state. At least one day of the fundamental course of study must be provided in person. School districts must use best efforts to provide the fundamental course of study before the paraeducator begins to work with students and their families, and at a minimum by the deadlines provided in subsection (3) of this section.

. Except as provided in (b) of this subsection, school districts must provide the fundamental course of study required in subsection (2) of this section by the deadlines provided in (a) of this subsection:

.. [Empty]
... For paraeducators hired on or before September 1st, the first two days of the fundamental course of study must be provided by September 30th of that year and the second two days of the fundamental course of study must be provided within six months of the date of hire, regardless of the size of the district; and

... For paraeducators hired after September 1st:

(A) For districts with ten thousand or more students, the first two days of the fundamental course of study must be provided within four months of the date of hire and the second two days of the fundamental course of study must be provided within six months of the date of hire or by September 1st of the following year, whichever is sooner; and

(B) For districts with fewer than ten thousand students, no later than September 1st of the following year.

.. [Empty]
... For paraeducators hired for the 2018-19 school year, by September 1, 2020; and

... For paraeducators not hired for the 2018-19 school year, but hired for the 2019-20 school year, by September 1, 2021.

. School districts may collaborate with other school districts or educational service districts to meet the requirements of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1658-S.SL.pdf?cite=2019%20c%20268%20§%203[2019 c 268 § 3]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6388-S.SL.pdf?cite=2018%20c%20153%20§%203[2018 c 153 § 3]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1115-S.SL.pdf?cite=2017%20c%20237%20§%207[2017 c 237 § 7]; ]

== 28A.413.070 - General paraeducator certificate.
. [Empty]
.. School districts must implement this section only in school years for which state funding is appropriated specifically for the purposes of this section and only for the number of days that are funded by the appropriation.

.. School districts are encouraged to provide at least one day of the ten days of general courses, as defined by the board, on the state paraeducator standards of practice as a professional learning day, where paraeducators collaborate with certified staff and other classified staff on applicable courses.

. [Empty]
.. Paraeducators may become eligible for a general paraeducator certificate by completing the four-day fundamental course of study, as required under RCW 28A.413.060, and an additional ten days of general courses, as defined by the board, on the state paraeducator standards of practice, described in RCW 28A.413.050.

.. Paraeducators are not required to meet the general paraeducator certificate requirements under this subsection (2) unless the courses necessary to meet the requirements are funded by the state in accordance with subsection (1) of this section and RCW 28A.413.060(1).

. Beginning September 1, 2019, school districts must:

.. Provide paraeducators with general courses on the state paraeducator standards of practice; and

.. Ensure all paraeducators employed by the district meet the general certification requirements of this section within three years of completing the four-day fundamental course of study.

. The general paraeducator certificate does not expire.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1658-S.SL.pdf?cite=2019%20c%20268%20§%204[2019 c 268 § 4]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6388-S.SL.pdf?cite=2018%20c%20153%20§%204[2018 c 153 § 4]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1115-S.SL.pdf?cite=2017%20c%20237%20§%208[2017 c 237 § 8]; ]

== 28A.413.080 - Paraeducator subject matter certificates.
. The board shall adopt requirements and policies for paraeducator subject matter certificates in special education and in English language learner that are based on the recommendations of the paraeducator work group established in chapter 136, Laws of 2014.

. The rules adopted by the board must include the following requirements:

.. A subject matter certificate is not a prerequisite for a paraeducator working in any program;

.. Paraeducators may become eligible for a subject matter certificate by completing twenty hours of professional development in the subject area of the certificate; and

.. Subject matter certificates expire after five years.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1115-S.SL.pdf?cite=2017%20c%20237%20§%209[2017 c 237 § 9]; ]

== 28A.413.090 - Advanced paraeducator certificate.
. The board shall adopt requirements and policies for an advanced paraeducator certificate that are based on the recommendations of the paraeducator work group established in chapter 136, Laws of 2014.

. The rules adopted by the board must include the following requirements:

.. An advanced paraeducator certificate is not a prerequisite for a paraeducator working in any program;

.. Paraeducators may become eligible for an advanced paraeducator certificate by completing seventy-five hours of professional development in topics related to the duties of an advanced paraeducator; and

.. Advanced paraeducator certificates expire after five years.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1115-S.SL.pdf?cite=2017%20c%20237%20§%2010[2017 c 237 § 10]; ]

== 28A.413.100 - Promoting the use of paraeducators.
The paraeducator board must promote the use of paraeducators to meet educator workforce needs by:

. Communicating to school districts and educational service districts the requirements for requesting a limited teaching certificate on behalf of a paraeducator;

. Encouraging and supporting paraeducators to take on the role of teacher under a limited teaching certificate or by enrolling in an alternative route teacher certification program under chapter 28A.660 RCW; and

. Supporting school districts and educational service districts in using paraeducators in teacher roles.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1658-S.SL.pdf?cite=2019%20c%20268%20§%201[2019 c 268 § 1]; ]

