= 28A.180 - Transitional bilingual instruction program.
:toc:

== 28A.180.010 - Short title—Purpose.
RCW 28A.180.010 through 28A.180.080 shall be known and cited as "the transitional bilingual instruction act." The legislature finds that there are large numbers of children who come from homes where the primary language is other than English. The legislature finds that a transitional bilingual education program can meet the needs of these children. Pursuant to the policy of this state to insure equal educational opportunity to every child in this state, it is the purpose of RCW 28A.180.010 through 28A.180.080 to provide for the implementation of transitional bilingual education programs in the public schools.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2261-S.SL.pdf?cite=2009%20c%20548%20§%20704[2009 c 548 § 704]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20163[1990 c 33 § 163]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c124.pdf?cite=1984%20c%20124%20§%201[1984 c 124 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c95.pdf?cite=1979%20c%2095%20§%201[1979 c 95 § 1]; ]

== 28A.180.020 - Annual report by superintendent of public instruction.
The superintendent of public instruction shall review annually the transitional bilingual instruction program and shall submit a report of such review to the legislature on or before February 1st of each year.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5488.SL.pdf?cite=2017%20c%20123%20§%201[2017 c 123 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c124.pdf?cite=1984%20c%20124%20§%208[1984 c 124 § 8]; ]

== 28A.180.030 - Definitions.
As used throughout this chapter, unless the context clearly indicates otherwise:

. "Eligible pupil" means any enrollee of the school district whose primary language is other than English and whose English language skills are sufficiently deficient or absent to impair learning.

. "Exited pupil" means a student previously enrolled in the transitional bilingual instruction program who is no longer eligible for the program based on his or her performance on an English proficiency assessment approved by the superintendent of public instruction.

. "Primary language" means the language most often used by the student for communication in his/her home.

. "Transitional bilingual instruction" means:

.. A system of instruction which uses two languages, one of which is English, as a means of instruction to build upon and expand language skills to enable the pupil to achieve competency in English. Concepts and information are introduced in the primary language and reinforced in the second language: PROVIDED, That the program shall include testing in the subject matter in English; or

.. In those cases in which the use of two languages is not practicable as established by the superintendent of public instruction and unless otherwise prohibited by law, an alternative system of instruction which may include English as a second language and is designed to enable the pupil to achieve competency in English.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2051-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%209%20§%203[2013 2nd sp.s. c 9 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2025-S2.SL.pdf?cite=2001%201st%20sp.s.%20c%206%20§%203[2001 1st sp.s. c 6 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20164[1990 c 33 § 164]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c124.pdf?cite=1984%20c%20124%20§%202[1984 c 124 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c95.pdf?cite=1979%20c%2095%20§%202[1979 c 95 § 2]; ]

== 28A.180.040 - School board duties.
. Every school district board of directors shall:

.. Make available to each eligible pupil transitional bilingual instruction to achieve competency in English, in accord with rules of the superintendent of public instruction;

.. Wherever feasible, ensure that communications to parents emanating from the schools shall be appropriately bilingual for those parents of pupils in the bilingual instruction program;

.. Determine, by administration of an English test approved by the superintendent of public instruction the number of eligible pupils enrolled in the school district at the beginning of a school year and thereafter during the year as necessary in individual cases;

.. Ensure that a student who is a child of a military family in transition and who has been assessed as in need of, or enrolled in, a bilingual instruction program, the receiving school shall initially honor placement of the student into a like program.

... The receiving school shall determine whether the district's program is a like program when compared to the sending school's program; and

... The receiving school may conduct subsequent assessments pursuant to RCW 28A.180.090 to determine appropriate placement and continued enrollment in the program;

.. Before the conclusion of each school year, measure each eligible pupil's improvement in learning the English language by means of a test approved by the superintendent of public instruction;

.. Provide in-service training for teachers, counselors, and other staff, who are involved in the district's transitional bilingual program. Such training shall include appropriate instructional strategies for children of culturally different backgrounds, use of curriculum materials, and program models; and

.. Make available a program of instructional support for up to two years immediately after pupils exit from the program, for exited pupils who need assistance in reaching grade-level performance in academic subjects even though they have achieved English proficiency for purposes of the transitional bilingual instructional program.

. Beginning in the 2019-20 school year, all classroom teachers assigned using funds for the transitional bilingual instruction program to provide supplemental instruction for eligible pupils must hold an endorsement in bilingual education or English language learner, or both.

. The definitions in Article II of RCW 28A.705.010 apply to subsection (1)(d) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1541-S4.SL.pdf?cite=2016%20c%2072%20§%20301[2016 c 72 § 301]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2051-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%209%20§%204[2013 2nd sp.s. c 9 § 4]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5248-S.SL.pdf?cite=2009%20c%20380%20§%205[2009 c 380 § 5]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2025-S2.SL.pdf?cite=2001%201st%20sp.s.%20c%206%20§%204[2001 1st sp.s. c 6 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c124.pdf?cite=1984%20c%20124%20§%203[1984 c 124 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c95.pdf?cite=1979%20c%2095%20§%203[1979 c 95 § 3]; ]

== 28A.180.060 - Guidelines and rules.
The superintendent of public instruction shall:

. Promulgate and issue program development guidelines to assist school districts in preparing their programs;

. Promulgate rules for implementation of RCW 28A.180.010 through 28A.180.080 in accordance with chapter 34.05 RCW. The rules shall be designed to maximize the role of school districts in selecting programs appropriate to meet the needs of eligible students. The rules shall identify the process and criteria to be used to determine when a student is no longer eligible for transitional bilingual instruction pursuant to RCW 28A.180.010 through 28A.180.080.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20165[1990 c 33 § 165]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c124.pdf?cite=1984%20c%20124%20§%205[1984 c 124 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c95.pdf?cite=1979%20c%2095%20§%205[1979 c 95 § 5]; ]

== 28A.180.080 - Allocation of moneys for bilingual instruction program.
Moneys appropriated by the legislature for the purposes of RCW 28A.180.010 through 28A.180.080 shall be allocated by the superintendent of public instruction to school districts for the sole purpose of operating an approved bilingual instruction program.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2261-S.SL.pdf?cite=2009%20c%20548%20§%20705[2009 c 548 § 705]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5169-S.SL.pdf?cite=1995%20c%20335%20§%20601[1995 c 335 § 601]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20167[1990 c 33 § 167]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c95.pdf?cite=1979%20c%2095%20§%206[1979 c 95 § 6]; ]

== 28A.180.090 - Evaluation system—Technical assistance and support.
The superintendent of public instruction shall develop an evaluation system designed to measure increases in the English and academic proficiency of eligible pupils. When developing the system, the superintendent shall:

. Require school districts to assess potentially eligible pupils within ten days of registration using an English proficiency assessment or assessments as specified by the superintendent of public instruction. Results of these assessments shall be made available to both the superintendent of public instruction and the school district;

. Require school districts to annually assess all eligible pupils at the end of the school year using an English proficiency assessment or assessments as specified by the superintendent of public instruction. Results of these assessments shall be made available to both the superintendent of public instruction and the school district;

. Develop a system to evaluate increases in the English and academic proficiency of students who are, or were, eligible pupils. This evaluation shall include students when they are in the program and after they exit the program until they finish their K-12 career or transfer from the school district. The purpose of the evaluation system is to inform schools, school districts, parents, and the state of the effectiveness of the transitional bilingual programs in school and school districts in teaching these students English and other content areas, such as mathematics and writing; and

. Subject to funds appropriated specifically for this purpose, provide school districts with technical assistance and support in selecting research-based program models, instructional materials, and professional development for program staff, including disseminating information about best practices and innovative programs. The information must include research about the differences between conversational language proficiency, academic language proficiency, and subject-specific language proficiency and the implications this research has on instructional practices and evaluation of program effectiveness.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1541-S4.SL.pdf?cite=2016%20c%2072%20§%20401[2016 c 72 § 401]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2025-S2.SL.pdf?cite=2001%201st%20sp.s.%20c%206%20§%202[2001 1st sp.s. c 6 § 2]; ]

== 28A.180.100 - Continuing education plan for older students.
The office of the superintendent of public instruction and the state board for community and technical colleges shall jointly develop a program plan to provide a continuing education option for students who are eligible for the state transitional bilingual instruction program and who need more time to develop language proficiency but who are more age-appropriately suited for a postsecondary learning environment than for a high school. By December 1, 2004, the agencies shall report to the legislative education and fiscal committees with any recommendations for legislative action and any resources necessary to implement the plan.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1599-S2.SL.pdf?cite=2019%20c%20252%20§%20107[2019 c 252 § 107]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2195-S.SL.pdf?cite=2004%20c%2019%20§%20105[2004 c 19 § 105]; ]

== 28A.180.110 - Condensed compliance reports—Second-class districts.
Any compliance reporting requirements as a result of laws in this chapter that apply to second-class districts may be submitted in accordance with RCW 28A.330.250.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5184-S.SL.pdf?cite=2011%20c%2045%20§%209[2011 c 45 § 9]; ]

== 28A.180.120 - Bilingual educator initiative—Pilot projects—Pipeline to college—Conditional loans—Report—Rules.
. The Washington professional educator standards board, beginning in the 2017-2019 biennium, shall administer the bilingual educator initiative, which is a long-term program to recruit, prepare, and mentor bilingual high school students to become future bilingual teachers and counselors.

. Subject to the availability of amounts appropriated for this specific purpose, pilot projects must be implemented in one or two school districts east of the crest of the Cascade mountains and one or two school districts west of the crest of the Cascade mountains, where immigrant students are shown to be rapidly increasing. Districts selected by the Washington professional educator standards board must partner with at least one two-year and one four-year college in planning and implementing the program. The Washington professional educator standards board shall provide oversight.

. Participating school districts must implement programs, including: (a) An outreach plan that exposes the program to middle school students and recruits them to enroll in the program when they begin their ninth grade of high school; (b) activities in ninth and tenth grades that help build student agency, such as self-confidence and awareness, while helping students to develop academic mind-sets needed for high school and college success; the value and benefits of teaching and counseling as careers; and introduction to leadership, civic engagement, and community service; (c) credit-bearing curricula in grades eleven and twelve that include mentoring, shadowing, best practices in teaching in a multicultural world, efficacy and practice of dual language instruction, social and emotional learning, enhanced leadership, civic engagement, and community service activities.

. There must be a pipeline to college using two-year and four-year college faculty and consisting of continuation services for program participants, such as advising, tutoring, mentoring, financial assistance, and leadership.

. High school and college teachers and counselors must be recruited and compensated to serve as mentors and trainers for participating students.

. After obtaining a high school diploma, students qualify to receive conditional loans to cover the full cost of college tuition, fees, and books. To qualify for funds, students must meet program requirements as developed by their local implementation team, which consists of staff from their school district and the partnering two-year and four-year college faculty.

. In order to avoid loan repayment, students must (a) earn their baccalaureate degree and certification needed to serve as a teacher or professional guidance counselor; and (b) teach or serve as a counselor in their educational service district region for at least five years. Students who do not meet the repayment terms in this subsection are subject to repaying all or part of the financial aid they receive for college unless students are recipients of funding provided through programs such as the Washington college grant program or the college bound scholarship program.

. Grantees must work with the Washington professional educator standards board to draft the report required in section 6, chapter 236, Laws of 2017.

. The Washington professional educator standards board must use the findings from the evaluation conducted under RCW 28A.415.370 to revise the bilingual educator initiative as necessary.

. The Washington professional educator standards board may adopt rules to implement this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2158-S2.SL.pdf?cite=2019%20c%20406%20§%2036[2019 c 406 § 36]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1139-S2.SL.pdf?cite=2019%20c%20295%20§%20105[2019 c 295 § 105]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1445-S.SL.pdf?cite=2017%20c%20236%20§%204[2017 c 236 § 4]; ]

