= 28A.715 - State-tribal education compacts authority.
:toc:

== 28A.715.005 - Findings—Intent—Purpose.
. The legislature finds that:

.. American Indian and Alaska Native students make up 2.5 percent of the total student population in the state and twenty-five percent or more of the student population in fifty-seven schools across the state.

.. American Indian students in Washington have the highest annual dropout rate at 9.5 percent, compared to 4.6 percent of all students in each of grades nine through twelve. Of the students expected to graduate in 2010 because they entered the ninth grade in 2006, the American Indian on-time graduation rate was only fifty-eight percent, compared to 76.5 percent of all students.

.. The teaching of American Indian language, culture, and history are [is] important to American Indian people and critical to the educational attainment and achievement of American Indian children.

.. The state-tribal education compacts authorized under this chapter reaffirm the state's important commitment to government-to-government relationships with the tribes that has been recognized by proclamation, and in the centennial accord and the millennium agreement. These state-tribal education compacts build upon the efforts highlighted by the office of the superintendent of public instruction in its 2012 Centennial Accord Agency Highlights, including: The Since Time Immemorial (STI): Tribal Sovereignty in Washington State Curriculum Project that imbeds the history surrounding sovereignty and intergovernmental responsibilities into this state's classrooms; the agency's regular meetings with the superintendents of the seven current tribal schools, as well as the federal bureau of Indian education representatives at the regional and national level on issues relating to student academic achievement, accessing of funding for tribal schools, and connecting tribal schools to the K-20 network; and the recent establishment, in statute, of the office of native education within the office of the superintendent of public instruction.

.. School funding should honor tribal sovereignty and reflect the government-to-government relationship between the state and the tribes, however the current structure that requires negotiation of an interlocal agreement between a school district and a tribal school ignores tribal sovereignty and results in a siphoning of funds for administration that could be better used for teaching and learning.

. The legislature further finds that:

.. There is a preparation gap among entering kindergartners with many children, especially those from low-income homes, arriving at kindergarten without the knowledge, skills, and good health necessary to succeed in school;

.. Upon entry into the K-12 school system, the educational opportunity gap becomes more evident, with children of color and from low-income homes having lower scores on math, reading, and writing standardized tests, as well as lower graduation rates and higher rates of dropping out of school; and

.. Comprehensive, culturally competent early learning and greater collaboration between the early learning and K-12 school systems will ensure appropriate connections and smoother transitions for children, and help eliminate or bridge gaps that might otherwise develop.

. In light of these findings, it is the intent and purpose of the legislature to authorize the superintendent of public instruction to enter into state-tribal education compacts.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1134-S2.SL.pdf?cite=2013%20c%20242%20§%201[2013 c 242 § 1]; ]

== 28A.715.010 - Authority to enter into compacts—Process—Rules—Retirement systems.
. The superintendent of public instruction is authorized to enter into state-tribal education compacts.

. No later than six months after July 28, 2013, the superintendent of public instruction shall establish an application and approval process, procedures, and timelines for the negotiation, approval or disapproval, and execution of state-tribal education compacts.

. The process may be initiated by submission, to the superintendent of public instruction, of a resolution by:

.. The governing body of a tribe in the state of Washington; or

.. The governing body of any of the schools in Washington that are currently funded by the federal bureau of Indian affairs, whether directly or through a contract or compact with an Indian tribe or a tribal consortium.

. The resolution must be accompanied by an application that indicates the grade or grades from kindergarten through twelve that will be offered and that demonstrates that the school will be operated in compliance with all applicable laws, the rules adopted thereunder, and the terms and conditions set forth in the application.

. Within ninety days of receipt of a resolution and application under this section, the superintendent must convene a government-to-government meeting for the purpose of considering the resolution and application and initiating negotiations.

. State-tribal education compacts must include provisions regarding:

.. Compliance;

.. Notices of violation;

.. Dispute resolution, which may include nonjudicial processes such as mediation;

.. Recordkeeping and auditing;

.. The delineation of the respective roles and responsibilities;

.. The term or length of the contract, and whether or not it is renewable; and

.. Provisions for compact termination.

. If a tribal school chooses to participate in the teachers' retirement system, the school employees' retirement system, or both, the state-tribal education compact must also include the following:

.. Acknowledgment by the tribal school that it affirmatively chooses to participate in the teachers' retirement system, the school employees' retirement system, or both;

.. Evidence that the person or persons who sign the compact on behalf of a tribe, dependent Indian community, or subdivision thereof have authority under tribal or community law to bind the tribe or dependent Indian community to all provisions in the compact, including any waiver of sovereign immunity;

.. If the tribal school chooses to participate in the teachers' retirement system:

... Agreement by the tribal school that it meets the definition of an employer as defined in chapter 41.32 RCW;

... Agreement by the tribal school to adhere to all reporting, contribution, and auditing requirements as defined in chapter 41.32 RCW, and all rules adopted under authority of RCW 41.50.050(5);

... Agreement between the superintendent of public instruction and the tribal school that for the duration of the compact the school will be a public school for the purposes of retirement plan membership as defined in chapter 41.32 RCW; and

... Agreement by the tribal school that, at the request of the superintendent of public instruction, the tribal school will make available to the superintendent any records the tribal school has provided to the department of retirement systems as required under the reporting, contribution, and auditing requirements defined in chapter 41.32 RCW, and rules implementing that chapter;

.. If the tribal school chooses to participate in the school employees' retirement system:

... Agreement by the tribal school that it meets the definition of an employer as defined in chapter 41.35 RCW;

... Agreement by the tribal school to adhere to all reporting, contribution, and auditing requirements as defined in chapter 41.35 RCW, and all rules adopted under authority of RCW 41.50.050(5); and

... Agreement by the tribal school that, at the request of the superintendent of public instruction, the tribal school will make available to the superintendent any records the tribal school has provided to the department of retirement systems as required under the reporting, contribution, and auditing requirements defined in chapter 41.35 RCW, and rules implementing that chapter;

.. Agreement by the tribe or, if applicable, the dependent Indian community, to a limited waiver of sovereign immunity and consent to the jurisdiction of the Washington state courts for the purpose of enforcing the reporting, contribution, and auditing requirements defined in chapters 41.32 and 41.35 RCW and all rules adopted under authority of RCW 41.50.050(5);

.. Agreement by the tribal school to dissolution procedures memorialized in the state-tribal education compact so that all parties are aware of their expectations and duties if the compact terminates or the tribal school chooses to no longer participate in the state retirement systems at a future date;

.. Acknowledgment by the tribal school that it has been advised that choosing to no longer participate in the retirement systems may result in federal tax implications for the governing body and its employees that are outside the control of the state of Washington, the department of retirement systems, and the superintendent of public instruction, and that the tribal school is encouraged to seek counsel before agreeing to any dissolution procedures in the compact; and

.. Acknowledgment by both parties that the pension plan participation portions of the state-tribal education compact are null and void if the federal internal revenue service issues guidance stating that any portion of those sections are in conflict with the plan qualification requirements for governmental plans in section 401(a) of the internal revenue code, and the conflict cannot be resolved through administrative action, statutory change, or amendment to the state-tribal education compact.

. For tribal schools that opt out of pension plan participation, such schools' employees shall have no right to earn additional service credit in the plan.

. The superintendent of public instruction shall adopt such rules as are necessary to implement this chapter.

. "Tribal school" for the purposes of this section means any school qualified to participate in a state-tribal education compact under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6210.SL.pdf?cite=2018%20c%20257%20§%201[2018 c 257 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1134-S2.SL.pdf?cite=2013%20c%20242%20§%202[2013 c 242 § 2]; ]

== 28A.715.020 - Operation of schools.
. A school that is the subject of a state-tribal education compact must operate according to the terms of its compact executed in accordance with RCW 28A.715.010.

. Schools that are the subjects of state-tribal education compacts are exempt from all state statutes and rules applicable to school districts and school district boards of directors, except those statutes and rules made applicable under this chapter and in the state-tribal education compact executed under RCW 28A.715.010.

. Each school that is the subject of a state-tribal education compact must:

.. Provide a curriculum and conduct an educational program that satisfies the requirements of RCW 28A.150.200 through 28A.150.240 and 28A.230.010 through 28A.230.195;

.. Employ certificated instructional staff as required in RCW 28A.410.010, however such schools may hire noncertificated instructional staff of unusual competence and in exceptional cases as specified in RCW 28A.150.203(7);

.. Comply with the employee record check requirements in RCW 28A.400.303 and the mandatory termination and notification provisions of RCW 28A.400.320, 28A.400.330, 28A.405.470, and 28A.405.475;

.. Comply with nondiscrimination laws;

.. Adhere to generally accepted accounting principles and be subject to financial examinations and audits as determined by the state auditor, including annual audits for legal and fiscal compliance; and

.. Be subject to and comply with legislation enacted after July 28, 2013, governing the operation and management of schools that are the subject of a state-tribal education compact.

. No such school may engage in any sectarian practices in its educational program, admissions or employment policies, or operations.

. Nothing in this chapter may limit or restrict any enrollment or school choice options otherwise available under Title 28A RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1134-S2.SL.pdf?cite=2013%20c%20242%20§%203[2013 c 242 § 3]; ]

== 28A.715.030 - Tuition—Fees—Admission—Enrollment priorities.
. A school that is the subject of a state-tribal education compact may not charge tuition except to the same extent as school districts may be permitted to do so with respect to out-of-state and adult students pursuant to chapter 28A.225 RCW, but may charge fees for participation in optional extracurricular events and activities.

. Such schools may not limit admission on any basis other than age group, grade level, or capacity and must otherwise enroll all students who apply.

. If capacity is insufficient to enroll all students who apply, a school that is the subject of a state-tribal education compact may prioritize the enrollment of tribal members and siblings of already enrolled students.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1134-S2.SL.pdf?cite=2013%20c%20242%20§%204[2013 c 242 § 4]; ]

== 28A.715.040 - Student enrollment reporting—Funding apportionment and allocations—Retention of moneys in accounts.
. A school that is the subject of a state-tribal education compact must report student enrollment. Reporting must be done in the same manner and use the same definitions of enrolled students and annual average full-time equivalent enrollment as is required of school districts. The reporting requirements in this subsection are required for a school to receive state or federal funding that is allocated based on student characteristics.

. Funding for a school that is the subject of a state-tribal education compact shall be apportioned by the superintendent of public instruction according to the schedule established under RCW 28A.510.250, including general apportionment, special education, categorical, and other nonbasic education moneys. Allocations for certificated instructional staff must be based on the statewide average salary set forth in RCW 28A.150.410, adjusted by the regionalization factor that applies to the school district in which the school is located. Allocations for classified staff and certificated administrative staff must be based on the salary allocations of the school district in which the school is located as set forth in RCW 28A.150.410, adjusted by the regionalization factor that applies to the school district in which the school is located. Nothing in this section requires a school that is the subject of a state-tribal education compact to use the statewide salary allocation schedule. Such a school is eligible to apply for state grants on the same basis as a school district.

. Any moneys received by a school that is the subject of a state-tribal education compact from any source that remain in the school's accounts at the end of any budget year must remain in the school's accounts for use by the school during subsequent budget years.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6362-S2.SL.pdf?cite=2018%20c%20266%20§%20404[2018 c 266 § 404]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1134-S2.SL.pdf?cite=2013%20c%20242%20§%205[2013 c 242 § 5]; ]

== 28A.715.800 - Modifications to school requirements—Pilot project. (Expires September 1, 2023.)
. The office of the superintendent of public instruction shall establish a pilot project for one or more schools that are the subject of a state-tribal education compact, schools also known as "tribal compact schools," to implement modifications to requirements governing school attendance, school year length, and assessments. Tribal compact schools that apply to the office of the superintendent of public instruction to participate in the pilot project must be included in the pilot project.

. The purpose of the pilot project is to grant participating schools flexibility regarding:

.. Accommodating cultural, fisheries, and agricultural events and practices; and

.. Replacing, to the maximum extent permitted by state and federal law, statewide student assessments with locally developed assessments that are culturally relevant, based on community standards, and aligned with the Washington state learning standards.

. Schools participating in the pilot project may:

.. Request a waiver, in accordance with RCW 28A.300.109, to the requirement for a one hundred eighty-day school year established in RCW 28A.150.220. The waiver requested in accordance with this subsection (3)(a) may be for allowing additional instructional days, including an allowance for year-round instruction;

.. Develop curricula that links student learning with engagement in cultural, fisheries, and agricultural programs, and aligns with the Washington state learning standards;

.. Request authorization to consider student participation in cultural, fisheries, or agricultural programs as instructional days for the purposes of RCW 28A.150.220(5);

.. Replace, to the maximum extent permitted by state and federal law, statewide student assessments with locally developed assessments that are culturally relevant, based on community standards, and aligned with the Washington state learning standards; and

.. Consider and implement, to the maximum extent permitted by state and federal law, other modifications to requirements as determined by each participating school.

. The office of native education within the office of the superintendent of public instruction must collaborate with each tribal compact school participating in the pilot project, including providing technical support and assistance, and review any terms of the compact that relate to the school's implementation of the pilot project.

. The office of the superintendent of public instruction, in establishing the pilot project required by this section, shall explore and pursue options for granting flexibility to participating schools from state and federal requirements, including requirements related to assessments, to further the purpose of the pilot project as expressed in subsection (2) of this section.

. If requested by a tribal compact school participating or intending to participate in the pilot project, the superintendent of public instruction shall convene a government-to-government meeting with the tribal compact school for the purpose of revising the compact to reflect the terms of the pilot project. The superintendent of public instruction may also convene a government-to-government meeting on his or her own accord.

. Nothing contained in this section is intended or may be construed to limit the amount of funding allocated to tribal compact schools participating in the pilot project.

. [Empty]
.. Each tribal compact school participating in the pilot project shall submit a report every two years to the appropriate committees of the house of representatives and senate and the office of the superintendent of public instruction, with the first report submitted no later than August 1, 2021.

.. Reports submitted in accordance with this subsection (8) must include:

... Information about student performance on assessments required for state and federal accountability purposes and locally developed assessments under subsection (3)(d) of this section, including differences in student performance between the statewide and locally developed assessments; and

... Recommendations for lessening or removing barriers that may affect either student performance on assessments, the effective administration of assessments, or both.

.. The final report of each participating school must include a recommendation of whether the pilot project should be modified, continued, expanded, or discontinued.

.. Reports submitted to the house of representatives and the senate in accordance with this subsection (8) must comply with RCW 43.01.036.

. The pilot project expires August 1, 2023.

. This section expires September 1, 2023.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6474-S.SL.pdf?cite=2018%20c%20290%20§%201[2018 c 290 § 1]; ]

== 28A.715.810 - Modifications to school requirements—Pilot project—Exemptions. (Expires September 1, 2023.)
. Students in a school that is the subject of a state-tribal education compact and that is participating in the pilot project established in RCW 28A.715.800 are exempt from the obligation to earn:

.. A certificate of academic achievement as a prerequisite for graduating from a public high school under RCW 28A.230.090 and 28A.655.061; or

.. A certificate of individual achievement as a prerequisite for graduating from a public high school under RCW 28A.155.045 and 28A.230.090.

. If a student attends a school that is participating in the pilot project established in RCW 28A.715.800, the statewide high school assessments in English language arts and mathematics that are administered under RCW 28A.655.070 may not be used:

.. To determine whether the student has met the requirements for graduating from a public high school; or

.. For assessing the student's career and college readiness.

. Schools participating in the pilot project established in RCW 28A.715.800 are exempt from the provisions in RCW 28A.230.125 that require standardized high school transcripts to include a notation of whether the student has earned a certificate of individual achievement or certificate of academic achievement.

. This section expires September 1, 2023.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6474-S.SL.pdf?cite=2018%20c%20290%20§%203[2018 c 290 § 3]; ]

