= 28A.415 - Institutes, workshops, and training.
:toc:

== 28A.415.010 - Center for improvement of teaching—Improvement of teaching coordinating council—Teachers' institutes and workshops.
It shall be the responsibility of each educational service district board to establish a center for the improvement of teaching. The center shall administer, coordinate, and act as fiscal agent for such programs related to the recruitment and training of certificated and classified K-12 education personnel as may be delegated to the center by the superintendent of public instruction under RCW 28A.310.470. To assist in these activities, each educational service district board shall establish an improvement of teaching coordinating council to include, at a minimum, representatives as specified in RCW 28A.415.040. An existing in-service training task force, established pursuant to RCW 28A.415.040, may serve as the improvement of teaching coordinating council. The educational service district board shall ensure coordination of programs established pursuant to RCW 28A.415.030, 28A.410.060, and 28A.415.265.

The educational service district board may arrange each year for the holding of one or more teachers' institutes and/or workshops for professional staff preparation and in-service training in such manner and at such time as the board believes will be of benefit to the teachers and other professional staff of school districts within the educational service district and shall comply with rules of the professional educator standards board pursuant to RCW 28A.410.060 or the superintendent of public instruction. The board may provide such additional means of teacher and other professional staff preparation and in-service training as it may deem necessary or appropriate and there shall be a proper charge against the educational service district general expense fund when approved by the educational service district board.

Educational service district boards of contiguous educational service districts, by mutual arrangements, may hold joint institutes and/or workshops, the expenses to be shared in proportion to the numbers of certificated personnel as shown by the last annual reports of the educational service districts holding such joint institutes or workshops.

In local school districts employing more than one hundred teachers and other professional staff, the school district superintendent may hold a teachers' institute of one or more days in such district, said institute when so held by the school district superintendent to be in all respects governed by the provisions of this title and rules relating to teachers' institutes held by educational service district superintendents.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5946-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%2018%20§%20402[2013 2nd sp.s. c 18 § 402]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3098-S2.SL.pdf?cite=2006%20c%20263%20§%20807[2006 c 263 § 807]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1813-S.SL.pdf?cite=1991%20c%20285%20§%201[1991 c 285 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20414[1990 c 33 § 414]; 1975-'76 2nd ex.s. c 15 § 18; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c275.pdf?cite=1975%201st%20ex.s.%20c%20275%20§%20139[1975 1st ex.s. c 275 § 139]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c192.pdf?cite=1975%201st%20ex.s.%20c%20192%20§%202[1975 1st ex.s. c 192 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c282.pdf?cite=1971%20ex.s.%20c%20282%20§%2031[1971 ex.s. c 282 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c176.pdf?cite=1969%20ex.s.%20c%20176%20§%20146[1969 ex.s. c 176 § 146]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028A.71.100[1969 ex.s. c 223 § 28A.71.100]; prior:  1965 c 139 § 21; ]

== 28A.415.025 - Internship clock hours—Rules.
The professional educator standards board shall establish rules for awarding clock hours for participation of certificated personnel in internships with business, industry, or government. To receive clock hours for an internship, the individual must demonstrate that the internship will provide beneficial skills and knowledge in an area directly related to his or her current assignment, or to his or her assignment for the following school year. An individual may not receive more than the equivalent of two college quarter credits for internships during a calendar-year period. The total number of credits for internships that an individual may earn to advance on the salary schedule developed by the legislative evaluation and accountability program committee or its successor agency is limited to the equivalent of fifteen college quarter credits.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3098-S2.SL.pdf?cite=2006%20c%20263%20§%20810[2006 c 263 § 810]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1518-S.SL.pdf?cite=1995%20c%20284%20§%203[1995 c 284 § 3]; ]

== 28A.415.030 - In-Service Training Act of 1977—Purpose.
In order to provide for the improvement of the instructional process in the public schools and maintain and improve the skills of public school certificated and classified personnel, there is hereby adopted an act to be known as the "In-Service Training Act of 1977".

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c189.pdf?cite=1977%20ex.s.%20c%20189%20§%201[1977 ex.s. c 189 § 1]; ]

== 28A.415.040 - In-Service Training Act of 1977—Administration of funds—Rules—Requirements for local districts—In-service training task force.
The superintendent of public instruction is hereby empowered to administer funds now or hereafter appropriated for the conduct of in-service training programs for public school certificated and classified personnel and to supervise the conduct of such programs. The superintendent of public instruction shall adopt rules in accordance with chapter 34.05 RCW that provide for the allocation of such funds to public school district or educational service district applicants on such conditions and for such training programs as he or she deems to be in the best interest of the public school system: PROVIDED, That each district requesting such funds shall have:

. Conducted a district needs assessment, including plans developed at the building level, to be reviewed and updated at least every two years, of certificated and classified personnel to determine identified strengths and weakness of personnel that would be strengthened by such in-service training program;

. Demonstrate that the plans are consistent with the goals of basic education;

. Established an in-service training task force and demonstrated to the superintendent of public instruction that the task force has participated in identifying in-service training needs and goals; and

. Demonstrated to the superintendent of public instruction its intention to implement the recommendations of the needs assessment and thereafter the progress it has made in providing in-service training as identified in the needs assessment.

The task force required by this section shall be composed of representatives from the ranks of administrators, building principals, teachers, classified and support personnel employed by the applicant school district or educational service district, from the public, and from an institution(s) of higher education, in such numbers as shall be established by the school district board of directors or educational service district board of directors.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c525.pdf?cite=1987%20c%20525%20§%20301[1987 c 525 § 301]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c214.pdf?cite=1985%20c%20214%20§%201[1985 c 214 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c149.pdf?cite=1979%20c%20149%20§%2010[1979 c 149 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c189.pdf?cite=1977%20ex.s.%20c%20189%20§%202[1977 ex.s. c 189 § 2]; ]

== 28A.415.060 - Credits for educational staff associates to fulfill continuing education requirements.
The Washington professional educator standards board rules for continuing education shall provide that educational staff associates may use credits or clock hours that satisfy the continuing education requirements for their state professional licensure, if any, to fulfill the continuing education requirements established by the Washington professional educator standards board.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5732-S.SL.pdf?cite=2005%20c%20497%20§%20210[2005 c 497 § 210]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1139.SL.pdf?cite=1991%20c%20155%20§%201[1991 c 155 § 1]; ]

== 28A.415.265 - Beginning educator support team program—Mentors.
. For the purposes of this section, a mentor educator is a teacher, educational staff associate, or principal who:

.. Has successfully completed training in assisting, coaching, and advising beginning principals, beginning educational staff associates, beginning teachers, or student teachers as defined by the office of the superintendent of public instruction;

.. Has been selected using mentor standards developed by the office of the superintendent of public instruction; and

.. Is participating in ongoing mentor skills professional development.

. [Empty]
.. The beginning educator support team program is established to provide professional development and mentoring for beginning principals, beginning educational staff associates, beginning teachers, and candidates in alternative route teacher certification programs under chapter 28A.660 RCW.

.. The superintendent of public instruction shall notify school districts about the beginning educator support team program and encourage districts to apply for program funds.

. Subject to the availability of amounts appropriated for this specific purpose, the office of the superintendent of public instruction shall allocate funds for the beginning educator support team program on a competitive basis to individual school districts, consortia of districts, or state-tribal compact schools. In allocating funds, the office of the superintendent of public instruction shall give priority to:

.. Schools and districts identified for comprehensive or targeted support and improvement as required under the federal elementary and secondary education act;

.. School districts with a large influx of beginning principals, beginning educational staff associates, or beginning classroom teachers; and

.. School districts that demonstrate an understanding of the research-based standards for beginning educator induction developed by the office of the superintendent of public instruction.

. A portion of the appropriated funds may be used for program coordination and provision of statewide or regional professional development through the office of the superintendent of public instruction.

. A beginning educator support team program must include the following components:

.. A paid instructional orientation or individualized assistance before the start of the school year for program participants;

.. A trained and qualified mentor assigned to each program participant for up to three years, with intensive support in the first year and decreasing support in subsequent years;

.. A goal to provide program participants from underrepresented populations with a mentor who has strong ties to underrepresented populations;

.. Ongoing professional development designed to meet the unique needs of each program participant for supplemental training and skill development;

.. Initial and ongoing professional development for mentors;

.. Release time for mentors and program participants to work together, as well as time for program participants to observe accomplished peers;

.. To the extent possible, a school or classroom assignment that is appropriate for a beginning principal, beginning educational staff associate, or beginning teacher;

.. Nonevaluative observations with written feedback for program participants;

.. Support in understanding and participating in the state and district evaluation process and using the instructional framework, leadership framework, or both, to promote growth;

.. Adherence to research-based standards for beginning educator induction developed by the office of the superintendent of public instruction; and

.. A program evaluation that identifies program strengths and gaps using the standards for beginning educator induction, the retention of beginning educators, and positive impact on student growth for program participants.

. The beginning educator support team program components under subsection (5) of this section may be provided for continuous improvement coaching to support educators on probation under RCW 28A.405.100.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1139-S2.SL.pdf?cite=2019%20c%20295%20§%20302[2019 c 295 § 302]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6455-S2.SL.pdf?cite=2016%20c%20233%20§%2011[2016 c 233 § 11]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5946-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%2018%20§%20401[2013 2nd sp.s. c 18 § 401]; ]

== 28A.415.270 - Principal internship support program.
. To the extent funds are appropriated, the Washington state principal internship support program is created beginning in the 1994-95 school year. The purpose of the program is to provide funds to school districts to provide partial release time for district employees who are in a principal preparation program to complete an internship with a mentor principal. Funds may be used in a variety of ways to accommodate flexible implementation in releasing the intern to meet program requirements.

. Participants in the principal internship support program shall be selected as follows:

.. The candidate shall be enrolled in a state board-approved school principal preparation program;

.. The candidate shall apply in writing to his or her local school district;

.. Each school district shall determine which applicants meet its criteria for participation in the principal internship support program;

.. Applicants submit their applications to the office of the superintendent of public instruction's designee; and

.. The office of the superintendent of public instruction's designee, with the assistance of an advisory board, shall select internship participants.

. The maximum amount of state funding for each internship shall not exceed the actual daily rate cost of providing a substitute teacher for the equivalent of forty-five school days.

. Once principal internship participants have been selected, the office of the superintendent of public instruction shall allocate the funds to the appropriate school districts. The funds shall be used to pay for partial release time while the school district employee is completing the principal internship.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1139-S2.SL.pdf?cite=2019%20c%20295%20§%20207[2019 c 295 § 207]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6267-S.SL.pdf?cite=1996%20c%20233%20§%201[1996 c 233 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1209-S.SL.pdf?cite=1993%20c%20336%20§%20404[1993 c 336 § 404]; ]

== 28A.415.280 - Superintendent and program administrator internship support program.
. To the extent funds are appropriated, the Washington state superintendent and program administrator internship support program is created beginning in the 1994-95 school year. The purpose of the program is to provide funds to school districts to provide partial release time for district employees who are in a superintendent or program administrator preparation program to complete an internship with a mentor administrator. Funds may be used in a variety of ways to accommodate flexible implementation in releasing the intern to meet program requirements.

. Participants in the superintendent and program administrator internship support program shall be selected as follows:

.. The candidate shall be enrolled in a state board-approved school district superintendent or program administrator preparation program;

.. The candidate shall apply in writing to his or her local school district;

.. Each school district shall determine which applicants meet its criteria for participation in the internship support program and shall notify its educational service district of the school district's selected applicants. When submitting the names of applicants, the school district shall identify a mentor administrator for each intern applicant and shall agree to provide the internship applicant release time not to exceed the equivalent of forty-five student days by means of this funding source; and

.. Educational service districts, with the assistance of an advisory board, shall select internship participants.

. [Empty]
.. The maximum amount of state funding for each internship shall not exceed the actual daily rate cost of providing a substitute teacher for the equivalent of forty-five school days.

.. Funds appropriated for the internship support program shall be allocated by the superintendent of public instruction to the educational service districts based on the percentage of full-time equivalent public school students enrolled in school districts in each educational service district. 

.. Once internship participants have been selected, the educational service districts shall allocate the funds to the appropriate school districts. The funds shall be used to pay for partial release time while the school district employee is completing the internship.

.. If an educational service district has unfilled superintendent or program administrator internship positions, the positions and unspent funds shall revert to the superintendent of public instruction for supplementary direct disbursement among the educational service districts.

The superintendent of public instruction shall allocate any remaining unfilled positions and unspent funds among the educational service districts that have qualified candidates but not enough positions for them.

This subsection does not preclude the superintendent of public instruction from permitting the affected educational service districts to make the supplementary selections.

.. Educational service districts may be reimbursed for costs associated with implementing the program. Reimbursement rates shall be determined by the superintendent of public instruction.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6267-S.SL.pdf?cite=1996%20c%20233%20§%202[1996 c 233 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1209-S.SL.pdf?cite=1993%20c%20336%20§%20405[1993 c 336 § 405]; ]

== 28A.415.285 - Expanded civics education teacher training program.
. Subject to the availability of amounts appropriated for this specific purpose, an expanded civics education teacher training program is established within the office of the superintendent of public instruction.

. The program must provide for the selection of a team of qualified social studies teachers, and when appropriate, civics education specialists, from across the state who will:

.. Develop teacher training materials using existing open educational resources (OERs) that include civics information on national, state, tribal, and local government, and the civics component of the federally administered naturalization test required of persons seeking to become naturalized United States citizens;

.. Provide teacher training across the state, consistent with provisions in this chapter, and using the tools established by the office of the superintendent of public instruction including the college, career, and civic life (C3) framework and the six proven instructional practices for enhancing civic education; and

.. Provide professional learning opportunities as described in section 2(3), chapter 77, Laws of 2016, which states that professional learning shall incorporate differentiated, coherent, sustained, and evidence-based strategies that improve educator effectiveness and student achievement, including job-embedded coaching or other forms of assistance to support educators' transfer of new knowledge and skills into their practice.

. The program shall assure an increase in the number of:

.. Teachers with the knowledge and skills to effectively engage students in civics education;

.. Students who have a basic understanding of how governments work; and

.. Students from every demographic and socioeconomic group who know their rights and responsibilities within society and are prepared to exercise them.

. The office of the superintendent of public instruction may accept gifts and grants to assist with the establishment and implementation of the program established in this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1896-S2.SL.pdf?cite=2018%20c%20127%20§%203[2018 c 127 § 3]; ]

== 28A.415.300 - Rules.
The superintendent of public instruction shall adopt rules as necessary under chapter 34.05 RCW to administer the principal and superintendent and program administrator internship support programs.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1209-S.SL.pdf?cite=1993%20c%20336%20§%20407[1993 c 336 § 407]; ]

== 28A.415.315 - Classified instructional assistants—Training.
Subject to the availability of amounts appropriated for this purpose, the office of the superintendent of public instruction, in consultation with various groups representing school district classified employees, shall develop and offer a training strand through the summer institutes and the winter conference targeted to classified instructional assistants and designed to help them maximize their effectiveness in improving student achievement.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2343-S.SL.pdf?cite=2009%20c%20539%20§%202[2009 c 539 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2870-S2.SL.pdf?cite=2008%20c%2065%20§%202[2008 c 65 § 2]; ]

== 28A.415.330 - Professional development institutes—Managing disruptive students.
. To the extent funds are appropriated, the superintendent of public instruction shall conduct professional development institutes to provide opportunities for teachers, principals, and other school staff to learn effective research-based strategies for handling disruptive students. The institutes shall be conducted during the summer of 2000. The training institutes shall emphasize methods for handling disruptions in regular classrooms and how to design and implement alternative learning settings and programs that have been proven to be effective in providing for the educational needs of students who exhibit frequent and prolonged disruptive behavior when placed in a regular classroom setting.

. The superintendent may enter into contracts with public or private entities that provide training in effective research-based methods for dealing with disruptive students. In developing the institutes, the superintendent shall work with school staff who have had experience working effectively with disruptive students. The institutes shall be open to teams of teachers, principals, and other school staff from each school district choosing to participate. However, as a condition of participating in the institutes, school district teams shall be required to develop during or immediately following the institute a district plan for carrying out the purposes of this section. Elementary schools and junior high and middle schools in districts that send teams to participate in institutes conducted under this section are encouraged to formulate school building-level plans for addressing the educational needs of disruptive students and the needs of students and teachers in the regular classrooms for an orderly and disciplined environment that is optimally conducive to learning. Individual participants in the institutes shall agree to provide assistance as needed to other school staff in their school building or school district, consistent with their other normal duties.

. Beginning with the 1999-2000 school year, elementary and junior high schools are encouraged to provide staff from both the regular education and special education programs opportunities to work together to share successful practices for managing disruptive students.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2085-S2.SL.pdf?cite=1999%20c%20166%20§%202[1999 c 166 § 2]; ]

== 28A.415.340 - State leadership academy—Public-private partnership—Reports.
. Research supports the value of quality school and school district leadership. Effective leadership is critical to improving student learning and transforming underperforming schools and school districts into world-class learning centers.

. A public-private partnership is established to develop, pilot, and implement the Washington state leadership academy to focus on the development and enhancement of personal leadership characteristics and the teaching of effective practices and skills demonstrated by school and district administrators who are successful managers and instructional leaders. It is the goal of the academy to provide state-of-the-art programs and services across the state.

. Academy partners include the state superintendent and principal professional associations, private nonprofit foundations, institutions of higher education with approved educator preparation programs, the professional educator standards board, the office of the superintendent of public instruction, educational service districts, the state school business officers' association, and other entities identified by the partners. The partners shall designate an independent organization to act as the fiscal agent for the academy and shall establish a board of directors to oversee and direct the academy's finances, services, and programs. The academy shall be supported by a national research institution with demonstrated expertise in educational leadership.

. Initial development of academy course content and activities shall be supported by private funds. Initial tasks of the academy are to:

.. Finalize a comprehensive design of the academy and the development of the curriculum frameworks for a comprehensive leadership development program that includes coursework, practicum, mentoring, and evaluation components;

.. Develop curriculum for individual leadership topics;

.. Pilot the curriculum and all program components; and

.. Modify the comprehensive design, curriculum coursework, practicum, and mentoring programs based on the research results gained from pilot activities.

. The board of directors shall report semiannually to the superintendent of public instruction on the financial contributions provided by foundations and other organizations to support the work of the academy. The board of directors shall report by December 31st each year to the superintendent of public instruction on the programs and services provided, numbers of participants in the various academy activities, evaluation activities regarding program and participant outcomes, and plans for the academy's future development.

. The board of directors shall make recommendations for changes in superintendent and principal preparation programs, the administrator licensure system, and continuing education requirements.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5955-S2.SL.pdf?cite=2007%20c%20402%20§%201[2007 c 402 § 1]; ]

== 28A.415.350 - Professional development learning opportunities—Partnerships.
Subject to the availability of amounts appropriated for this purpose, the office of the superintendent of public instruction shall:

. Create partnerships with the educational service districts or public or private institutions of higher education with approved educator preparation programs to develop and deliver professional development learning opportunities for educators that fulfill the goals and address the activities described in *sections 3 through 6 of this act and RCW 28A.415.360. The partnerships shall:

.. Support school districts by providing professional development leadership, courses, and consultation services to school districts in their implementation of professional development activities, including the activities described in *sections 3 through 6 of this act and RCW 28A.415.360; and

.. Support one another in the delivery of state-level and regional-level professional development activities such as state conferences and regional accountability institutes; and

. Enter into a performance agreement with each educational service district to clearly articulate partner responsibilities and assure fidelity for the delivery of professional development initiatives including job-embedded practices. Components of such performance agreements shall include:

.. Participation in the development of various professional development workshops, programs, and activities;

.. Characteristics and qualifications of professional development staff supported by the program;

.. Methods to ensure consistent delivery of professional development services; and

.. Reporting responsibilities related to services provided, program participation, outcomes, and recommendations for service improvement.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2343-S.SL.pdf?cite=2009%20c%20539%20§%204[2009 c 539 § 4]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5955-S2.SL.pdf?cite=2007%20c%20402%20§%207[2007 c 402 § 7]; ]

== 28A.415.360 - Learning improvement days—Eligibility—Reports.
. Subject to funds appropriated for this purpose, targeted professional development programs, to be known as learning improvement days, are authorized to further the development of outstanding mathematics, science, and reading teaching and learning opportunities in the state of Washington. The intent of this section is to provide guidance for the learning improvement days in the omnibus appropriations act. The learning improvement days authorized in this section shall not be considered part of the definition of basic education.

. A school district is eligible to receive funding for learning improvement days that are limited to specific activities related to student learning that contribute to the following outcomes:

.. Provision of meaningful, targeted professional development for all teachers in mathematics, science, or reading;

.. Increased knowledge and instructional skill for mathematics, science, or reading teachers;

.. Increased use of curriculum materials with supporting diagnostic and supplemental materials that align with state standards;

.. Increased rigor of course offerings especially in mathematics, science, and reading;

.. Increased student opportunities for focused, applied mathematics and science classes;

.. Increased student success on state achievement measures; and

.. Increased student appreciation of the value and uses of mathematics, science, and reading knowledge and exploration of related careers.

. School districts receiving resources under this section shall submit reports to the superintendent of public instruction documenting how the use of the funds contributes to measurable improvement in the outcomes described under subsection (2) of this section; and how other professional development resources and programs authorized in statute or in the omnibus appropriations act contribute to the expected outcomes. The superintendent of public instruction and the office of financial management shall collaborate on required report content and format.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1599-S2.SL.pdf?cite=2019%20c%20252%20§%20117[2019 c 252 § 117]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2261-S.SL.pdf?cite=2009%20c%20548%20§%20403[2009 c 548 § 403]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5955-S2.SL.pdf?cite=2007%20c%20402%20§%209[2007 c 402 § 9]; ]

== 28A.415.370 - Recruiting Washington teachers program.
. [Empty]
.. The recruiting Washington teachers program is established to recruit and provide training and support for high school students to enter the field of education, especially in shortage areas. The program shall be administered by the Washington professional educator standards board.

.. As used in this section, "shortage area" has the definition in RCW 28B.102.020.

. The program shall consist of the following components:

.. Targeted recruitment of diverse high school students including, but not limited to, students from underrepresented groups and multilingual, multicultural students in grades nine through twelve, through outreach and communication strategies. The focus of recruitment efforts shall be on encouraging students to consider and explore careers in the field of education;

.. A high school curriculum that: Provides future educators with opportunities to observe classroom instruction at all grade levels; includes preteaching internships at all grade levels with a focus on shortage areas; and covers such topics as lesson planning, learning styles, student learning data and information, academic disparities among student subgroups, cultural competency, college success and workforce skills, and education policy;

.. Academic and community support services to help students overcome possible barriers to becoming future educators, such as supplemental tutoring; advising on college readiness and college course selection, college applications, and financial aid processes and financial education opportunities; and mentoring. Support services for program participants may continue from high school through the first two years of college; and

.. Future educator camps held on college campuses where high school students can: Acclimate to the campus, resources, and culture; attend workshops; and interact with college faculty, teacher candidates, and certificated teachers.

. As part of its administration of the program, the Washington professional educator standards board shall:

.. Develop the curriculum and program guidelines in consultation with an advisory group of teachers, representatives of teacher preparation programs, teacher candidates, high school students, and representatives of diverse communities;

.. Subject to the availability of amounts appropriated for this specific purpose, allocate grant funds through a competitive process to partnerships of high schools, teacher preparation programs, and community-based organizations to design and deliver programs that include the components under subsection (2) of this section. The board must prioritize grants to partnerships that also have a running start program under chapter 28A.600 RCW; and

.. Conduct periodic evaluations of the effectiveness of current strategies and programs for recruiting educators, especially multilingual, multicultural educators, in Washington and in other states. The board shall use the findings from the evaluation to revise the recruiting Washington teachers program as necessary and make other recommendations to teacher preparation programs or the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1139-S2.SL.pdf?cite=2019%20c%20295%20§%20104[2019 c 295 § 104]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5955-S2.SL.pdf?cite=2007%20c%20402%20§%2010[2007 c 402 § 10]; ]

== 28A.415.380 - Mathematics and science instructional coach program—Evaluation—Reports.
. A mathematics and science instructional coach program is authorized, which shall consist of a coach development institute, coaching seminars, coaching activities in schools, and program evaluation.

. The office of the superintendent of public instruction shall develop a mathematics and science instructional coach program that includes an initial coach development experience for new coaches provided through an institute setting, coaching support seminars, and additional coach development services. The office shall draw upon the experiences of coaches in federally supported elementary literacy programs and other successful programs, research and policy briefs on adult professional development, and research that specifically addresses the instructional environments of middle, junior high, and high schools as well as the unique aspects of the fields of mathematics and science.

. The office of the superintendent of public instruction shall design the application process and select the program participants.

. Schools and school districts participating in the program shall carefully select the individuals to perform the role of mathematics or science instructional coach. Characteristics to be considered for a successful coach include:

.. Expertise in content area;

.. Expertise in various instructional methodologies and personalizing learning;

.. Personal skills that include skilled listening, questioning, trust building, and problem solving;

.. Understanding and appreciation for the differences in adult learners and student learners; and

.. Capacity for strategic planning and quality program implementation.

. The role of the mathematics or science instructional coach is focused on supporting teachers as they apply knowledge, develop skills, polish techniques, and deepen their understanding of content and instructional practices. This work takes a number of forms including: Individualized professional development, department-wide and school-wide professional development, guidance in student data interpretation, and using assessment to guide instruction. Each coach shall be assigned to two schools as part of the program.

. Program participants have the following responsibilities:

.. Mathematics and science coaches shall participate in the coach development institute as well as in coaching support seminars that take place throughout the school year, practice coaching activities as guided by those articulated in the role of the coach in subsection (5) of this section, collect data, and participate in program evaluation activities as requested by the institute pursuant to subsection (7) of this section.

.. School and district administrators in districts in which the mathematics and science coaches are practicing shall participate in program evaluation activities.

. [Empty]
.. The Washington State University social and economic sciences research center shall conduct an evaluation of the mathematics and science instructional coach program in this section. Data shall be collected through various instruments including surveys, program and activity reports, student performance measures, observations, interviews, and other processes. Findings shall include an evaluation of the coach development institute, coaching support seminars, and other coach support activities; recommendations with regard to the characteristics required of the coaches; identification of changes in teacher instruction related to coaching activities; and identification of the satisfaction level with coaching activities as experienced by classroom teachers and administrators.

.. The Washington State University social and economic sciences research center shall report its findings to the governor, the office of the superintendent of public instruction, and the education and fiscal committees of the legislature. An interim report is due November 1, 2008. The final report is due December 1, 2009.

. The mathematics and science instructional coach program in this section shall be implemented to the extent funds are available for that purpose.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6168.SL.pdf?cite=2009%20c%20578%20§%201[2009 c 578 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1906-S2.SL.pdf?cite=2007%20c%20396%20§%204[2007 c 396 § 4]; ]

== 28A.415.390 - Condensed compliance reports—Second-class districts.
Any compliance reporting requirements as a result of laws in this chapter that apply to second-class districts may be submitted in accordance with RCW 28A.330.250.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5184-S.SL.pdf?cite=2011%20c%2045%20§%2033[2011 c 45 § 33]; ]

== 28A.415.400 - Reading instruction and early literacy—Professional development.
. High quality professional development is essential for educators to keep abreast of the important advances in research that are occurring regarding instructional strategies and curriculum. Professional development in early literacy is especially important to support the instruction of young readers since reading proficiency is a crucial element for student academic success.

. Subject to funds appropriated for this specific purpose, the office of the superintendent of public instruction shall create partnerships with the educational service districts and public or private institutions of higher education with approved educator preparation programs to develop and deliver research-based professional development learning opportunities in reading instruction and early literacy for teachers of kindergarten through fourth grade students.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5946-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%2018%20§%20103[2013 2nd sp.s. c 18 § 103]; ]

== 28A.415.410 - Training to support discipline policies under chapter  28A.600 RCW.
. The office of the superintendent of public instruction, subject to the availability of amounts appropriated for this specific purpose, shall develop a training program to support the implementation of discipline policies and procedures under chapter 28A.600 RCW.

. School districts are strongly encouraged to provide the trainings to all school and district staff interacting with students, including instructional staff and noninstructional staff, as well as within a reasonable time following any substantive change to school discipline policies or procedures.

. To the maximum extent feasible, the trainings must incorporate or adapt existing online training or curriculum, including securing materials or curriculum under contract or purchase agreements within available funds.

. The trainings must be developed in modules that allow:

.. Access to material over a reasonable number of training sessions;

.. Delivery in person or online; and

.. Use in a self-directed manner.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1541-S4.SL.pdf?cite=2016%20c%2072%20§%20104[2016 c 72 § 104]; ]

== 28A.415.430 - Professional learning—Defined—Scope.
. The term "professional learning" means a comprehensive, sustained, job-embedded, and collaborative approach to improving teachers' and principals' effectiveness in raising student achievement. Professional learning fosters collective responsibility for improved student performance and must comprise learning that is aligned with student learning needs, educator development needs, and school district , or state improvement goals. Professional learning shall have as its primary focus the improvement of teachers' and school leaders' effectiveness in assisting all students to meet the state learning standards.

. Professional learning is an ongoing process that is measurable by multiple indicators and includes learning experiences that support the acquisition and transfer of learning, knowledge, and skills into the classroom and daily practice.

. Professional learning shall incorporate differentiated, coherent, sustained, and evidence-based strategies that improve educator effectiveness and student achievement, including job-embedded coaching or other forms of assistance to support educators' transfer of new knowledge and skills into their practice.

. Professional learning should include the work of established collaborative teams of teachers, school leaders, and other administrative, instructional, and educational services staff members, who commit to working together on an ongoing basis to accomplish common goals and who are engaged in a continuous cycle of professional improvement that is focused on:

.. Identifying student and educator learning needs using multiple sources of data;

.. Defining a clear set of educator learning goals based on the rigorous analysis of these multiple data sources and the collective and personalized learning needs of teachers and administrators;

.. Continuously assessing the effectiveness of the professional learning in achieving identified learning goals, improving teaching, and assisting all students in meeting state academic learning standards through reflection, observation, and sustained support;

.. Using formative and summative measures to assess the effectiveness of professional learning in achieving educator learning goals;

.. Realizing the three primary purposes for professional learning: (i) Individual improvement aligned with individual goals; (ii) school and team improvement aligned with school and team improvement [goals]; and (iii) program implementation aligned with state, district, and school improvement goals and initiatives.

. Professional learning should be facilitated by well-prepared school and district leaders who incorporate knowledge, skills, and dispositions for leading professional learning of adults and meet the standards described in *RCW 28A.300.602. These facilitators may include but are not limited to: Curriculum specialists, central office administrators, principals, coaches, mentors, master teachers, and other teacher leaders.

. Principals should assist staff with alignment of professional learning tied to curriculum, instruction, and state and local learning goals and assessments.

. Professional learning may be supported by external expert assistance or additional activities that will be held to the same definition and standards as internally supported professional learning, and that:

.. Address defined student and educator learning goals;

.. Include, but are not limited to, courses, workshops, institutes, networks, studio residencies, virtual learning modules, and conferences provided by for-profit and nonprofit entities outside the school such as universities, educational service districts, technical assistance providers, networks of content specialists, and other education organizations and associations; and

.. Advance ongoing school-based professional learning that occurs throughout the year with opportunities for regular practice and feedback while developing new skills.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1345.SL.pdf?cite=2016%20c%2077%20§%202[2016 c 77 § 2]; ]

== 28A.415.432 - Professional learning—Standards.
Standards for professional learning provide guidance on the preparation and delivery of high quality professional learning to those responsible for planning, facilitating, and sponsoring professional learning.

. Content standards. High quality professional learning:

.. Includes clear goals and objectives relevant to desired student outcomes; and

.. Aligns with state, district, school, and educator goals or priorities.

. Process standards. High quality professional learning:

.. Is designed and based upon the analysis of data relevant to the identified goals, objectives, and audience;

.. Is assessed to determine that it is meeting the targeted goals and objectives;

.. Promotes collaboration among educators to encourage sharing of ideas and working together to achieve the identified goals and objectives;

.. Advances an educator's ability to apply acquired knowledge and skills from the professional learning to specific content; and

.. Models good pedagogical practice and applies knowledge of adult learning theory to engage educators.

. Context standards. High quality professional learning:

.. Makes use of relevant resources to ensure the identified goals and objectives are met;

.. Is facilitated by a professional knowledgeable about the identified objectives; and

.. Is designed in such a way that sessions connect and build upon each other to provide a coherent and useful learning experience for educators.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1345.SL.pdf?cite=2016%20c%2077%20§%203[2016 c 77 § 3]; ]

== 28A.415.434 - Professional learning—Definitions.
The definitions in this section apply throughout *RCW 28A.300.600 and 28A.300.602 unless the context clearly requires otherwise.

. "Differentiated" means that professional learning experiences are designed to meet the needs of individual educators based on multiple sources of data such as professional growth plans, observations, and student growth data.

. "Job-embedded" means a sustained series of activities such as workshops and coaching occurring throughout the year that is delivered within the context of an educator's instructional assignments, including both subject and grade level, to support the educator's acquisition and application of the knowledge and skills.

. "Student outcomes" refers to two broad categories of student measures: Academic measures and nonacademic measures. Academic measures refer to student learning, growth, and achievement. Nonacademic measures are indicators such as health, behavioral, or socioemotional factors that support student learning.

. "Sustained" means ongoing professional learning supported throughout the school year occurring several times within and across school years.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1345.SL.pdf?cite=2016%20c%2077%20§%204[2016 c 77 § 4]; ]

== 28A.415.443 - Definitions.
The definitions in this section apply throughout RCW 28A.345.115, 28A.345.120, 28A.410.265, 28A.343.100, 28A.410.260, and 28A.415.445 unless the context clearly requires otherwise.

. "Cultural competency" includes knowledge of student cultural histories and contexts, as well as family norms and values in different cultures; knowledge and skills in accessing community resources and community and parent outreach; and skills in adapting instruction to students' experiences and identifying cultural contexts for individual students.

. "Diversity" describes the presence of similarities and differences within a given setting, collective, or group based on multiple factors including race and ethnicity, gender identity, sexual orientation, disability status, age, educational status, religion, geography, primary language, culture, and other characteristics and experiences.

. "Equity" includes developing, strengthening, and supporting procedural and outcome fairness in systems, procedures, and resource distribution mechanisms to create equitable opportunities for all individuals. The term also includes eliminating barriers that prevent the full participation of individuals and groups.

. "Inclusion" describes intentional efforts and consistent sets of actions to create and sustain a sense of respect, belonging, safety, and attention to individual needs and backgrounds that ensure the full access to engagement and participation in available activities and opportunities.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5044-S.SL.pdf?cite=2021%20c%20197%20§%202[2021 c 197 § 2]; ]

== 28A.415.445 - Professional learning days—Mental health topics—Cultural competency, diversity, equity, and inclusion.
. Beginning in the 2020-21 school year, and every other school year thereafter, school districts must use one of the professional learning days funded under RCW 28A.150.415 to train school district staff in one or more of the following topics: Social-emotional learning, trauma-informed practices, using the model plan developed under RCW 28A.320.1271 related to recognition and response to emotional or behavioral distress, consideration of adverse childhood experiences, mental health literacy, antibullying strategies, or culturally sustaining practices.

. [Empty]
.. In the 2021-22 school year, school districts must use one of the professional learning days funded under RCW 28A.150.415 to train school district staff in one or more of the following topics: Cultural competency, diversity, equity, or inclusion.

.. Beginning in the 2023-24 school year, and every other school year thereafter, school districts must use one of the professional learning days funded under RCW 28A.150.415 to provide to school district staff a variety of opportunities for training, professional development, and professional learning aligned with the cultural competency, equity, diversity, and inclusion standards of practice developed by the Washington professional educator standards board under RCW 28A.410.260. Alignment with the standards of practice must be evaluated using the rubrics developed under RCW 28A.410.260. The opportunities must also include training on multicultural education and principles of English language acquisition.

. For the purposes of this section:

.. "Cultural competency," "diversity," "equity," and "inclusion" have the same meaning as in RCW 28A.415.443.

.. "School district staff" includes classified staff, certificated instructional staff, certificated administrative staff, and superintendents.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5044-S.SL.pdf?cite=2021%20c%20197%20§%208[2021 c 197 § 8]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5903-S2.SL.pdf?cite=2019%20c%20360%20§%203[2019 c 360 § 3]; ]

