= 85.07 - Miscellaneous diking and drainage provisions.
:toc:

== 85.07.010 - Lease of equipment authorized—Disposition of proceeds.
The commissioners of any diking or drainage district organized under the laws of this state, shall have power and authority to rent any machinery, tools or equipment belonging to such district, to any individual or corporation for hire under such conditions regarding the care and maintenance thereof as the commissioners may determine; and all sums of money received for the rent thereof shall be paid into the county treasury, to the credit of the district.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c30.pdf?cite=1979%20ex.s.%20c%2030%20§%2018[1979 ex.s. c 30 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c104.pdf?cite=1917%20c%20104%20§%201[1917 c 104 § 1]; RRS § 4517; ]

== 85.07.040 - Benefit to public road, how paid.
Whenever, upon the trial to fix and assess the benefits and damages resulting from the construction of any diking or drainage system under the laws of this state, the jury shall find by its verdict that any public or county road will be benefited from the construction of such improvement, the clerk of the court in which such trial is had shall, upon the entry of the judgment upon such verdict, certify to the board of county commissioners of the county in which such road is situated the amount of benefits to such road so found and adjudged. The said county commissioners shall, upon the receipt of such certified statement, allow the same as for other road work and shall order the amount thereof to be paid out of the road and bridge fund of the road district in which the road so benefited is situated, and shall direct the auditor of said county to issue a warrant for the amount of such benefits against the road and bridge fund of such road district in favor of the county treasurer of said county. The said county treasurer shall, upon the payment of said warrant, place the proceeds therefrom to the credit of the drainage or diking district from which such benefits resulted.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c194.pdf?cite=1909%20c%20194%20§%201[1909 c 194 § 1]; RRS § 4314; ]

== 85.07.050 - Basis of supplemental assessments.
Any additional assessments for the construction of any diking or drainage system, and also all assessments for the maintenance of same shall be based upon the benefits so found and adjudged, and the proportion of benefits resulting to such public or county road therefrom, on such basis, shall be allowed and paid for by such county in the same manner as in the case of the original construction.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c194.pdf?cite=1909%20c%20194%20§%202[1909 c 194 § 2]; RRS § 4315; ]

== 85.07.060 - Funding bonds—Authority to issue.
. Any board of commissioners of any diking or drainage district may, at any time, without petition and on its own motion, issue bonds of such district for the purpose of funding any outstanding warrants of such district. No bonds so issued shall be sold for less than their par value. They may be sold at public or private sale. Any department or agency of the state of Washington having power to invest funds is hereby authorized and empowered to use the same to buy such bonds.

. Such bonds may be issued and sold in accordance with chapter 39.46 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c167.pdf?cite=1983%20c%20167%20§%20189[1983 c 167 § 189]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c103.pdf?cite=1935%20c%20103%20§%201[1935 c 103 § 1]; RRS § 4459-11; ]

== 85.07.070 - Funding bonds—Form, term, execution, interest.
. Said bonds shall be numbered consecutively from one upwards and shall be in denominations of not less than one hundred dollars nor more than one thousand dollars each. They shall bear the date of issue, shall be made payable in not more than ten years from the date of their issue, and shall bear interest at a rate or rates as authorized by the board of commissioners, payable annually. The bonds may be in any form, including bearer bonds or registered bonds as provided in RCW 39.46.030. The bonds and any coupon shall be signed by the chair of the board of commissioners of each district and shall be attested by the secretary of said board. The seal, if any, of such district shall be affixed to each bond, but it need not be affixed to any coupon.

. Notwithstanding subsection (1) of this section, such bonds may be issued and sold in accordance with chapter 39.46 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20404[2013 c 23 § 404]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c167.pdf?cite=1983%20c%20167%20§%20190[1983 c 167 § 190]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c56.pdf?cite=1970%20ex.s.%20c%2056%20§%2091[1970 ex.s. c 56 § 91]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c232.pdf?cite=1969%20ex.s.%20c%20232%20§%2053[1969 ex.s. c 232 § 53]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c103.pdf?cite=1935%20c%20103%20§%202[1935 c 103 § 2]; RRS § 4459-12; ]

== 85.07.090 - Funding bonds—Outstanding warrants due when sale proceeds received—Call.
All outstanding warrants of such district so sought to be redeemed shall become due and payable immediately upon receipt by the county treasurer of the money from the sale of said bonds; and upon a call of such outstanding warrants or obligations issued by him or her, the same shall cease to draw interest at the end of thirty days after the date of the first publication of such call. The call shall be made by the treasurer by publishing notice thereof for two consecutive weeks in the county paper authorized to do the county printing. The notice shall designate the number of each warrant sought to be redeemed.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20405[2013 c 23 § 405]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c103.pdf?cite=1935%20c%20103%20§%204[1935 c 103 § 4]; RRS § 4459-14; ]

== 85.07.100 - Funding bonds—Exchange for warrants.
Said bonds may be exchanged at not less than their par value for an equal amount of the outstanding warrants of the district issuing such bonds.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c103.pdf?cite=1935%20c%20103%20§%205[1935 c 103 § 5]; RRS § 4459-15; ]

== 85.07.110 - Funding bonds—Assessments for payment—Special fund.
It shall be the duty of the commissioners of such district annually to levy assessments sufficient to pay interest on such bonds as they fall due. They may at any time levy such additional assessment as they deem best to redeem and retire such bonds. Commencing not less than five years before the due date of such bonds, they shall determine the number of equal annual levies necessary to retire such bonds at maturity, and annually thereafter levy an assessment sufficient to liquidate all of said bonds by maturity. Such levies for interest and redemption of the bonds shall be added to the annual cost of the maintenance of the diking or drainage system of said district. Such assessments shall be collected by the county treasurer and kept as a special fund for the sole purpose of paying interest upon and liquidating said bonds.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c167.pdf?cite=1983%20c%20167%20§%20192[1983 c 167 § 192]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c103.pdf?cite=1935%20c%20103%20§%206[1935 c 103 § 6]; RRS § 4459-16; ]

== 85.07.120 - Funding bonds—Call—Payment.
It shall be the duty of the county treasurer of each county in which there may be a district issuing bonds under the provisions of RCW 85.07.060 through 85.07.120, whenever he or she has on hand one thousand dollars over and above interest requirements in the special fund for the payment of said bonds and interest, to advertise in the newspaper doing the county printing, for the presentation to him or her for payment of as many of the bonds issued under the provisions of RCW 85.07.060 through 85.07.120 as he or she may be able to pay with the funds in his or her hands. The bonds shall be redeemed and paid in their numerical order, beginning with bond No. 1 and continuing until all of said bonds are paid. The treasurer's call for presentation and redemption of such bonds shall state the number of the bond or bonds so called. Thirty days after the first publication of said notice of the treasurer calling any of said bonds by their numbers, such bonds shall cease to bear interest, and the notice of call shall so state. If any bond so called is not presented, the treasurer shall hold in said fund until presentation of such bond is made, the amount of money sufficient to redeem the same with interest thereon to the date interest was terminated by such call.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20406[2013 c 23 § 406]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c103.pdf?cite=1935%20c%20103%20§%207[1935 c 103 § 7]; RRS § 4459-17; ]

== 85.07.130 - Civil action to strike land from assessment roll—Costs.
Whenever any piece of land in any diking or drainage district in this state shall cease to be susceptible to benefit from the diking and/or drainage improvement of such district, the owner thereof may bring civil action in the superior court of the county wherein such property is situated, against the board of commissioners of such district in their official capacity, to have such property stricken from the assessment roll for such district. The procedure shall be that of other civil actions, except no judgment for costs shall be entered against such district in such proceedings.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c102.pdf?cite=1935%20c%20102%20§%201[1935 c 102 § 1]; RRS § 4360-1; ]

== 85.07.140 - Civil action to strike land from assessment roll—Court decree—Subsequent restoration to rolls, procedure.
If the court is satisfied that the status of said property has changed so that it is no longer susceptible to benefit from the improvement of such district and should be removed from the assessment roll thereof, and it be established that all benefits assessed against said lands up to the date of trial have been paid, such court may enter a decree striking such land from the assessment roll of said district, and it shall not be subject to future assessment for benefits or maintenance by such district, unless, thereafter, it is again brought into such districts by the proceedings provided by law to extend the district or include benefited property which is not assessed. Nothing herein shall prevent such property from being again brought into said district in the manner provided by law generally for the inclusion of benefited property, if it appear at a future date that said property will receive benefits from the improvement in such district. Upon entry of such decree of the court a certified copy thereof shall be filed in the office of the auditor of such county wherein the property is situated, and upon receipt thereof, he or she shall correct the assessment roll of said district accordingly and strike the property therefrom.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20407[2013 c 23 § 407]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1935c102.pdf?cite=1935%20c%20102%20§%202[1935 c 102 § 2]; RRS § 4360-2; ]

== 85.07.170 - Additional powers relating to diking and drainage works—Duties of department of transportation.
. The commissioners of any drainage or diking district shall have power, on behalf of the district, to acquire, place, repair and maintain, dikes and dams, ditches, drains and outlets therefor, together with right-of-way therefor and access thereto, or obtain rights therein or full or joint use and maintenance thereof, when deemed by them necessary or beneficial for the protection of the district's system or its improvements, by eminent domain, purchase, or contract, with the owners or other districts through their commissioners, or other entities or persons together with power to contract by and with other districts or entities with reference to such matters and their performance.

. If the commissioners of any drainage or diking district determine that repair or maintenance is required on any drainage facilities, including dikes and dams, ditches, and drains and outlets, that are on land owned by or under the jurisdiction of the department of transportation, they may give notice in writing to the department requesting that the department make the necessary repair or maintenance pursuant to the department's obligations under RCW 47.01.260. If the specified repair or maintenance is not conducted by the department within fourteen days upon receipt of the notice, the district commissioners may independently make the repair or maintenance. The department shall then reimburse the district for all reasonable costs incurred by the district associated with the repair or maintenance.

. The provisions of this section shall be construed as cumulative and shall not derogate from any other powers authorized by law for such districts.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6248.SL.pdf?cite=2006%20c%20368%20§%201[2006 c 368 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c96.pdf?cite=1963%20c%2096%20§%201[1963 c 96 § 1]; ]

