= 85.12 - Federal aid to diking, drainage, and sewerage improvement districts.
:toc:

== 85.12.010 - Commissioners may accept federal aid, or contract for work by federal agency—No bond required.
Whenever, under the provisions of any act of the congress of the United States, the corps of engineers of the United States army, or any other agency of the United States, shall be authorized to reconstruct, improve, repair or maintain any system of improvements of any diking, drainage or sewerage improvement district under the laws of the state of Washington, the board of county commissioners of the county in which such district is situated, on behalf of such district may consent to and permit the United States, or any agency thereof, to perform any work or service upon or with regard to such district's system of improvements which shall by the board be found to be for the benefit of such district and the property therein, or, if the enlargement, betterment or other improvement of such district's system of improvements, or the performance of extraordinary maintenance work upon or with respect to its existing system of improvements shall have been authorized, the board may contract, on behalf of said district, upon such terms as may be agreed upon by the United States and the board for the performance of the work so authorized by said corps of engineers, or other agency of the United States. No bond shall be required by the district for any work performed by or under the supervision of said corps of engineers, or other agency of the United States.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c175.pdf?cite=1949%20c%20175%20§%201[1949 c 175 § 1]; RRS § 4459-50; ]

== 85.12.030 - Disposition of federal aid funds.
If at any time, whether prior or subsequent to the making of any contract authorized by the preceding section, there shall be made available and paid to a district fund appropriated by the congress of the United States to pay the costs and expenses of reconstruction, improvement, repair or maintenance of the district's system of improvements or any part thereof, said funds shall be paid into the district's maintenance or construction fund, according as the work is maintenance or new construction, and thereafter used and disbursed upon the order of the board, provided that if the district shall have theretofore issued extraordinary maintenance warrants or maintenance bonds or construction bonds, said funds shall be used to pay and retire said bonds or warrants to the extent of said funds. When all said warrants or bonds have been paid, the assessment levied to pay said warrants or bonds, or those installments of such assessment not then due and payable, shall be canceled. If the funds made available and paid to the district by the United States shall be more than sufficient to pay and retire all then outstanding warrants or bonds issued to pay the cost of the particular work, whether maintenance or new construction, then the excess of such federal aid funds, up to the amount of the total of the assessments to pay for such work theretofore paid, shall be paid by the treasurer to those who have paid such assessment or assessments in the proportion that the total of all such assessments paid by any one bears to the total of all such assessments theretofore paid, and any balance of such federal aid funds remaining shall become and be part of the maintenance fund of the district. Any assessment or installment of assessment not canceled under the provisions hereof, or any balance thereof which when collected shall not be required for the payment of interest or principal of any of said warrants or bonds, shall, after all said warrants or bonds have been paid, be paid into and become part of the maintenance fund of the district.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c175.pdf?cite=1949%20c%20175%20§%202[1949 c 175 § 2]; RRS § 4459-51; ]

