= 87.06 - Delinquent assessments.
:toc:

== 87.06.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Date of delinquency" means the date when the assessment first became delinquent under chapter 87.03 RCW.

. "Description of property" means a legal description, the parcel number, tax number, or other description that sufficiently describes the property or specific parcel of land.

. "Minimum bid sheet" means the informational sheet which is prepared by the treasurer for use at the treasurer's sale and which contains a description of the various properties and the minimum bid required for each.

. "Party in interest" means an occupant of the property, the owner of record, and any other person having a financial interest of record in the property.

. "Treasurer" means the irrigation district treasurer. However, if the county treasurer acts as ex officio district treasurer in accordance with RCW 87.03.440, then "treasurer" means the county treasurer.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c134.pdf?cite=1988%20c%20134%20§%201[1988 c 134 § 1]; ]

== 87.06.020 - Certificates of delinquency—Posting of certificates.
. After thirty-six calendar months from the month of the date of delinquency, or twenty-four months from the month of the date of delinquency with respect to any local improvement district assessment, the treasurer shall prepare certificates of delinquency on the property for the unpaid irrigation district assessments, and for costs and interest. An individual certificate of delinquency may be prepared for each property or the individual certificates may be compiled and issued in one general certificate including all delinquent properties. Each certificate shall contain the following information:

.. Description of the property assessed;

.. Street address of property, if available;

.. Years for which assessed;

.. Amount of delinquent assessments, costs, and interest;

.. Name appearing on the treasurer's most current assessment roll for the property; and

.. A statement that interest will be charged on the amount listed in (d) of this subsection at a rate of twelve percent per year, computed monthly and without compounding, from the date of the issuance of the certificate and that additional costs, incurred as a result of the delinquency, will be imposed, including the costs of a title search.

. The treasurer may provide for the posting of the certificates or other measures designed to advertise the certificates and encourage the payment of the amounts due.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1416-S2.SL.pdf?cite=2013%20c%20177%20§%2010[2013 c 177 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c134.pdf?cite=1988%20c%20134%20§%202[1988 c 134 § 2]; ]

== 87.06.030 - Provision and review of list of delinquent properties subject to foreclosure—Cost comparison, determination not to foreclose.
Before preparing a certificate of delinquency, the treasurer of a district that has designated its own treasurer as provided in RCW 87.03.440 , shall provide to the board of directors a list of properties that may be subject to foreclosure for delinquent assessments. The board of directors shall review the list of delinquent properties. After comparing the amount of the delinquent assessment with the costs of foreclosure, including but not limited to title search, court filing fees, costs of service, and attorneys' fees, the board of directors may determine that it is not in the best interest of the district to commence legal action to foreclose the delinquent assessment liens. Nothing in this section precludes a county treasurer from proceeding with foreclosure on parcels otherwise delinquent and, in those actions, from collecting delinquent assessments due under this title.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1417-S.SL.pdf?cite=2014%20c%202%20§%204[2014 c 2 § 4]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5665-S.SL.pdf?cite=2004%20c%20215%20§%204[2004 c 215 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c134.pdf?cite=1988%20c%20134%20§%203[1988 c 134 § 3]; ]

== 87.06.040 - Commencement of action to foreclose assessment liens—Notice and summons—Recording of notice of lis pendens.
. After the completion of the title searches, the treasurer, in the name of the irrigation district, shall commence legal action to foreclose on the assessment liens. The treasurer shall give notice of application for judgment foreclosing assessment liens and summons to all parties in interest as disclosed by the title search. The treasurer may include in any notice any number of separate properties. Such notice and summons shall contain:

.. A statement that the irrigation district is applying to superior court of the county in which the property is located for a judgment foreclosing the lien against the property for delinquent assessments, costs, and interest;

.. The full name of the superior court in which the district is applying for the judgment; and for each property: The description of the property, the local street address (if any), and the name of each party in interest;

.. A description of the lien amount due, which shall include the amount listed in RCW 87.06.020(1)(d), plus any costs and interest accruing since the date of preparation of the certificate of delinquency;

.. A direction to each party in interest summoning the party to appear within sixty days after service of the notice and summons, exclusive of the day of the service, and defend the action or pay the lien amount due; and when service is made by publication, a direction summoning each party to appear within sixty days after the date of the first publication of the notice and summons, exclusive of the day of first publication, and defend the action or pay the amount due;

.. A notice that, in case of failure to defend or pay the amount due, judgment will be rendered foreclosing the lien of the assessments, costs, and interest against the property; and

.. The date, time, and place of the foreclosure sale as specified in the application for judgment.

. The treasurer shall record in the office of the auditor of the county in which the property is located a notice of lis pendens before commencing the service of the notice and summons.

. The notice and summons shall be served in a manner reasonably calculated to inform each party in interest of the foreclosure action. At a minimum, service shall be accomplished by either (a) personal service upon a party in interest, or (b) publication once in a newspaper of general circulation that is circulated in the area in which the property is located and mailing of notice by certified mail to the party in interest.

. Notice and summons need not be served on holders of easements on the property if the easements are a matter of public record in the auditor's office of the county in which the property is located. Any foreclosure of delinquent assessments on any tract, lot, or parcel of real property subject to such easement or easements, and any treasurer's deed subsequently issued, is subject to such easement or easements that were established of record before the date of the certificate of delinquency for which the delinquent assessment was foreclosed.

. It shall be the duty of the treasurer to mail a copy of the notice and summons, within fifteen days after the first publication or service thereof, to the treasurer of each county, city, or town within which any property involved in an assessment foreclosure is situated, but the treasurer's failure to do so shall not affect the jurisdiction of the court nor the priority of any assessment lien sought to be foreclosed.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5556.SL.pdf?cite=2015%20c%2034%20§%201[2015 c 34 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c134.pdf?cite=1988%20c%20134%20§%204[1988 c 134 § 4]; ]

== 87.06.050 - Payment on certificate of delinquency before foreclosure.
. Any party in interest of property for which a certificate of delinquency has been prepared, but against which a foreclosure judgment has not been entered, may pay to the treasurer, in person or by agent, the total amount of the assessment lien, as listed under RCW 87.06.020(1)(d), plus any additional costs and interest, including any title search costs. If a foreclosure judgment has been entered, then any party in interest may pay to the treasurer, in person or by agent, the lien amount for which the judgment has been rendered, so long as payment is received by the treasurer during regular business hours before the day of the foreclosure sale. The treasurer shall give a receipt for each payment received under this subsection.

. Upon receipt of payment under this section, the district shall abandon any foreclosure proceedings commenced against the property. If a notice of lis pendens has been filed with the county auditor, the treasurer shall record a release of lis pendens with the auditor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c134.pdf?cite=1988%20c%20134%20§%205[1988 c 134 § 5]; ]

== 87.06.060 - Combining foreclosure proceedings—Irregularities or informalities in assessment role not illegal—Correction—Interested party may file written answer—Court's proceedings.
. The proceedings to foreclose the liens against all properties on a general certificate of delinquency or on more than one individual certificate may be brought in one action.

. No assessment, costs, or interest may be considered illegal because of any irregularity in the assessment roll or because the assessment roll has not been made, completed, or returned within the time required by law, or because the property has been charged or listed in the assessment roll without name, or in any other name than that of the owner, and no error or informality in the proceedings of any of the officers connected with the assessment may invalidate or in any other manner affect the assessment thereof. Any irregularities or informality in the assessment roll or in any of the proceedings connected with the assessment or any omission or defective act of any officer or officers connected with the assessment may be, at the discretion of the court corrected, supplied, and made to conform to the law by the court. This subsection does not apply if the court finds that the failure to conform to the law unfairly prejudices a party with an interest in the property.

. A party with an interest in real property subject to foreclosure within the district may file a written answer within the time permitted by RCW 87.06.040(1)(d) asserting an objection or defense to the entry of a foreclosure judgment against the property. However, defenses or objections shall be limited to: (a) The form of pleading; (b) manner of service; (c) invalidity of the assessments claimed delinquent; (d) payment of the assessments claimed delinquent; or (e) that the real property against which foreclosure is sought is not subject to district assessment. No counterclaim shall be permitted. The court shall liberally permit amendment or supplementation of the district's challenged pleading or procedure to cure the claimed defect.

. The court shall determine timely objections or defenses to the district's foreclosure in a summary proceeding based only on the district's pleading and the interested party's answer and shall promptly pronounce judgment granting or denying the foreclosure; or the court may, in its discretion, to provide substantial justice to the parties, continue the case to a later time to hear evidence on the issues raised by the answer. Hearings under this section shall be limited to affidavits or declarations, and shall be expedited.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5665-S.SL.pdf?cite=2004%20c%20215%20§%205[2004 c 215 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c134.pdf?cite=1988%20c%20134%20§%206[1988 c 134 § 6]; ]

== 87.06.070 - Sale of foreclosed property.
. If the court renders a judgment of foreclosure, the court shall direct the treasurer to proceed with the sale of the property and shall specify the minimum sale price below which the property is not to be sold.

. The treasurer shall sell the property to the highest and best bidder. All sales shall be made on Friday between the hours of nine a.m. and five p.m. at a location designated by the treasurer. However, sales not concluded on Friday shall be continued from day to day, Saturdays, Sundays, and holidays excluded, during the same hours until all properties are sold.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c134.pdf?cite=1988%20c%20134%20§%207[1988 c 134 § 7]; ]

== 87.06.080 - Notice of foreclosure sale—Conduct of sale—Remittal of excess moneys.
. The treasurer shall post notice of the foreclosure sale, at least ten days before the sale, at the following locations: At the courthouse of the county in which the property is located, at the district office, and at a public place in the district. The treasurer shall also publish, at least once and not fewer than ten days before the sale, the notice in any daily or weekly legal newspaper of general circulation in the district.

. The notice shall be in substantially the following form:

IRRIGATION ASSESSMENT JUDGMENT SALE

Public notice is hereby given that pursuant to judgment, rendered on . . . . . ., of the superior court of the county of . . . . . . in the state of Washington, that I shall sell the property described below, at a foreclosure sale beginning at . . . . . . (time), on . . . . . . (date), at . . . . . . (location), in the city of . . . . . . . . . . ., and county of . . . . . . . . . . ., state of Washington. This sale is made in order to pay for delinquent assessments, costs, and interest owed to . . . . . . . . . . . The property will be sold to the highest and best bidder but bids will not be accepted for less than the minimum sale price set by the superior court. The minimum sale price is listed on the bid sheet, a copy of which is provided at the treasurer's office. Payment must be made at time of sale and must be by cash, bank cashier's check, or a negotiable instrument of equivalent security.

Description of property: . . . .

Interested parties and members of the public are invited to participate in this sale. This sale will not take place if by . . . . . . (time), on . . . . . . (date), the amount due . . . ., is paid in the manner specified by law.

 . . . . Treasurer for . . . . Irrigation District Date signed: . . . .

 

. . . .

 

Treasurer for . . . .

 

Irrigation District

 

Date signed: . . . .

. The treasurer shall conduct the sale in conformance with the notice and this chapter. If the sale is conducted by the county treasurer, no county or district officer or employee may directly or indirectly be a purchaser. If the irrigation district treasurer conducts the sale, no officer or employee of the district may directly or indirectly be a purchaser.

. If the bid amount paid for the property is in excess of the lien amount for which the judgment has been rendered, plus any additional assessments, costs, and interest which have become due after the date of preparation of the certificate of delinquency and before the date of sale, then the excess shall be remitted, on application therefor, to the record owner of the property. The record owner of the property is the person who held title on the date of issuance of the certificate of delinquency. Assignments of interests, deeds, or other documents executed or recorded after filing the certificate of delinquency shall not affect the payment of excess funds to the record owner. If no claim for the excess is received by the treasurer within three years after the date of the sale, the treasurer, at expiration of the three-year period, shall deposit the excess in the current expense fund of the district.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1972.SL.pdf?cite=2007%20c%2063%20§%201[2007 c 63 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c134.pdf?cite=1988%20c%20134%20§%208[1988 c 134 § 8]; ]

== 87.06.090 - Treasurer's deed—Title free from certain encumbrances.
. The treasurer shall execute a treasurer's deed to any person who purchases property at the foreclosure sale. The deed shall vest title to the property therein described, without further acknowledgment or evidence of such conveyance, in the grantee or his or her heirs and assigns. The treasurer's deed shall be substantially in the following form:

TREASURER'S DEED

State of Washington

County of . . . . . . 

This indenture, made this . . . . . . day of . . . . . . . . . . ., . . . . . . . . . . ., between . . . . . . . . . . ., as treasurer of . . . . . . . . . . . irrigation district, state of Washington, party of the first part, and . . . . . . . . . . ., party of the second part:

Witnesseth, that whereas, at the public sale of real property held on the . . . . . . day of . . . . . . . . . . ., . . . . . . . . . . ., pursuant to an irrigation assessment judgment entered in the superior court in the county of . . . . . . . . . . . on the . . . . . . . . . . . day of . . . . . . . . . . ., . . . . . ., in proceedings to foreclose assessment liens upon real property and an order of sale duly issued by the court, . . . . . . . . . . . duly purchased in compliance with the laws of the state of Washington, for and in consideration of the sum of . . . . . . . . . . . dollars the following described real property, to wit: (Here place description of real property conveyed) and that . . . . . . . . . . . has complied with the laws of the state of Washington necessary to entitle (him, her, or them) to a deed for the real property.

Now, therefore know ye, that, I . . . . . . . . . . ., treasurer of said irrigation district of . . . . . . . . . . ., state of Washington, in consideration of the premises and by virtue of the statutes of the state of Washington, in such cases provided, do hereby grant and convey unto . . . . . . . . . . ., his or her heirs and assigns, forever, the real property hereinbefore described, as fully and completely as said party of the first part can by virtue of the premises convey the same.

Given under my hand and seal of office this . . . . . . day of . . . . . . . . . . ., A.D. . . . . . . . . . . .

 . . . . Treasurer for . . . . Irrigation District

 

. . . .

 

Treasurer for . . . .

 

Irrigation District

. The title shall be free from all encumbrances except for the following taxes and assessments if they are not due at the time of the foreclosure sale: Property taxes, drainage or diking district assessments, drainage or diking improvement district assessments, mosquito district assessments, and irrigation district assessments.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2562.SL.pdf?cite=1994%20c%2024%20§%201[1994 c 24 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c134.pdf?cite=1988%20c%20134%20§%209[1988 c 134 § 9]; ]

== 87.06.100 - Required payments before acquisition at foreclosure sale—Acquisition by irrigation district—District's property stricken from tax rolls—Subsequent purchasers to pay assessments.
. Prior to the treasurer executing and conveying the deed, all persons or entities acquiring property at the foreclosure sale shall be required to pay the full amount of all assessments, costs, and interest for which judgment is rendered; and the full amount of the following if due at the time of the foreclosure sale: Property taxes, drainage or diking district assessments, drainage or diking district improvement assessments, irrigation district assessments, and costs and interests relating to such taxes or assessments. This subsection does not apply to the irrigation district's acquisition of property.

. At all sales of property, if no other bids are received, title to the property shall vest in the irrigation district and the district shall pay to the county any costs that may have been incurred by the county under this chapter for the foreclosure action. The district's acquisition of the title shall be as absolute as if the property had been purchased by an individual under the provisions of this chapter. The deed provided for in RCW 87.06.090 shall be conveyed to the irrigation district.

. All property deeded to the district under the provisions of this chapter shall be stricken from the tax rolls as district property and exempt from taxation and shall not be taxed while property of the district.

. If the irrigation district sells any property it has acquired under this chapter, then it shall not provide a deed to the purchaser until the purchaser pays all drainage or diking district assessments, drainage or diking improvement district assessments, irrigation district assessments, property taxes, costs, and interest that were due at the time the irrigation district acquired title to the property.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c134.pdf?cite=1988%20c%20134%20§%2010[1988 c 134 § 10]; ]

== 87.06.110 - Combined foreclosure for district and county assessments.
The board of directors of the irrigation district and the county treasurer may through the interlocal cooperation agreement act, chapter 39.34 RCW, choose to have one of the treasurers proceed with a combined foreclosure for all property taxes, irrigation assessments, and all costs and interest owing to both entities. Any such agreement shall include a specific statement as to which entity shall assume title if no bids are received equal to or greater than the amount listed on the minimum bid sheet. The agreement shall also clearly specify how any unclaimed excess funds from the sale will be divided between the county and the irrigation district.

With a combined foreclosure for all property taxes, all irrigation district assessments, and all costs and interest owing to both entities, the county treasurer may use the foreclosure procedure under chapter 84.64 RCW or the irrigation district treasurer may use the foreclosure procedure under this chapter. When acting as the treasurer for the irrigation district, the county treasurer may use the foreclosure procedure under chapter 84.64 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5665-S.SL.pdf?cite=2004%20c%20215%20§%206[2004 c 215 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c134.pdf?cite=1988%20c%20134%20§%2011[1988 c 134 § 11]; ]

== 87.06.120 - Application of chapter to properties with assessments delinquent three or more years or acquired by the district under possibly legally defective proceedings.
. Except as provided in subsection (2) of this section, certificates of delinquency shall also be issued, and foreclosure proceedings instituted under this chapter, for properties for which assessments have been delinquent for a period of three or more years, if all or part of such period occurred before June 9, 1988. If foreclosure actions have been commenced but not completed under the law as it existed prior to June 9, 1988, the district shall abandon such actions and proceed against such properties under this chapter.

. Certificates of delinquency shall not be issued under this chapter for properties that have been sold (other than to the irrigation district) under foreclosure proceedings which occurred prior to June 9, 1988. This section does not apply to any foreclosure sale declared to be invalid by a court of competent jurisdiction or if district assessments again become delinquent after the date of sale.

. A certificate of delinquency may be issued, and foreclosure proceedings instituted, under this chapter for property acquired by an irrigation district under foreclosure proceedings which occurred prior to June 9, 1988, and which the district believes might be legally defective. "Acquired" as used in this subsection also includes the district's obtaining a certificate of sale under such foreclosure proceedings.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c134.pdf?cite=1988%20c%20134%20§%2012[1988 c 134 § 12]; ]

