= 36.33A - Equipment rental and revolving fund.
:toc:

== 36.33A.010 - Equipment rental and revolving fund—Establishment—Purposes.
Every county shall establish, by resolution, an "equipment rental and revolving fund", hereinafter referred to as "the fund", in the county treasury to be used as a revolving fund for the purchase, maintenance, and repair of county road department equipment; for the purchase of equipment, materials, supplies, and services required in the administration and operation of the fund; and for the purchase or manufacture of materials and supplies needed by the county road department.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977c67.pdf?cite=1977%20c%2067%20§%201[1977 c 67 § 1]; ]

== 36.33A.020 - Use of fund by other offices, departments or agencies.
The legislative body of any county may authorize, by resolution, the use of the fund by any other office or department of the county government or any other governmental agency for similar purposes.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977c67.pdf?cite=1977%20c%2067%20§%202[1977 c 67 § 2]; ]

== 36.33A.030 - Administration of fund.
With the approval of the county legislative body, the county engineer, or other appointee of the county legislative body, shall administer the fund and shall be responsible for establishing the terms and charges for the sale of any material or supplies which have been purchased, maintained, or manufactured with moneys from the fund. The terms and charges shall be set to cover all costs of purchasing, storing, and distributing the material or supplies, and may be amended as considered necessary.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977c67.pdf?cite=1977%20c%2067%20§%203[1977 c 67 § 3]; ]

== 36.33A.040 - Rates for equipment rental.
Rates for the rental of equipment owned by the fund shall be set to cover all costs of maintenance and repair, material and supplies consumed in operating or maintaining the equipment, and the future replacement thereof. The rates shall be determined by the county engineer or other appointee of the county legislative body and shall be subject to annual review by the legislative body. This section does not restrict the ability of the county road administration board to directly inquire into the process of setting rental rates while performing its statutory oversight responsibility.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1005.SL.pdf?cite=2007%20c%20195%20§%201[2007 c 195 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977c67.pdf?cite=1977%20c%2067%20§%204[1977 c 67 § 4]; ]

== 36.33A.050 - Deposits in fund.
The legislative authority of the county may, from time to time, place moneys in the fund from any source lawfully available to it and may transfer equipment, materials, and supplies of any office or department to the equipment rental and revolving fund with or without charge consistent with RCW 43.09.210. Charges for the rental of equipment and for providing materials, supplies, and services to any county office or department shall be paid monthly into the fund. Proceeds received from other governmental agencies for similar charges and from the sale of equipment or other personal property owned by the equipment rental and revolving fund, which is no longer of any value to or needed by the county, shall be placed in the fund as received.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977c67.pdf?cite=1977%20c%2067%20§%205[1977 c 67 § 5]; ]

== 36.33A.060 - Accumulated moneys.
Moneys accumulated in the equipment rental and revolving fund shall be retained therein from year to year; shall be used only for the purposes stated in this chapter; and shall be subject to the budgetary regulations in chapter 36.40 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977c67.pdf?cite=1977%20c%2067%20§%206[1977 c 67 § 6]; ]

