= 36.53 - Ferries—Privately owned.
:toc:

== 36.53.010 - Grant of license—Term.
The board of county commissioners may grant a license to keep a ferry across any lake or stream within its county, upon being satisfied that a ferry is necessary at the point applied for, which license shall continue in force for a term to be fixed by the commissioners not exceeding five years.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.53.010[1963 c 4 § 36.53.010]; Code 1881 § 3002; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1879%20p%2061%20§%2038[1879 p 61 § 38]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20280%20§%2040[1869 p 280 § 40]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20521%20§%201[1863 p 521 § 1]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20354%20§%201[1854 p 354 § 1]; RRS § 5462; ]

== 36.53.020 - Licensing tax.
The county legislative authority may charge such sum as may be fixed under the authority of RCW 36.32.120(3) for such license, and the person to whom the license is granted shall pay to the appropriate county official the tax for one year in advance.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c91.pdf?cite=1985%20c%2091%20§%202[1985 c 91 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.53.020[1963 c 4 § 36.53.020]; Code 1881 § 3003; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1879%20p%2061%20§%2039[1879 p 61 § 39]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20280%20§%2041[1869 p 280 § 41]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20522%20§%202[1863 p 522 § 2]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20354%20§%202[1854 p 354 § 2]; RRS § 5463; ]

== 36.53.030 - To whom license granted—Notice of intention if nonowner.
No license shall be granted to any person other than the owner of the land embracing or adjoining the lake or stream where the ferry is proposed to be kept, unless the owner neglects to apply therefor. Whenever application for a license is made by any person other than the owner, the board of county commissioners shall not grant it, unless proof is made that the applicant caused notice, in writing, of his or her intention to make such application to be given to such owner, if residing in the county, at least ten days before the session of the board of county commissioners at which application is made.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204086[2009 c 549 § 4086]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.53.030[1963 c 4 § 36.53.030]; Code 1881 § 3004; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1879%20p%2061%20§%2040[1879 p 61 § 40]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20280%20§%2042[1869 p 280 § 42]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20522%20§%203[1863 p 522 § 3]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20354%20§%203[1854 p 354 § 3]; RRS § 5464; ]

== 36.53.040 - Notice of application to be posted.
Every person intending to apply for a license to keep a ferry at any place shall give notice of his or her intention by posting up at least three notices in public places in the neighborhood where the ferry is proposed to be kept, twenty days prior to any regular session of the board of county commissioners at which the application is to be made.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204087[2009 c 549 § 4087]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.53.040[1963 c 4 § 36.53.040]; Code 1881 § 3005; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1879%20p%2061%20§%2041[1879 p 61 § 41]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20281%20§%2043[1869 p 281 § 43]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20522%20§%204[1863 p 522 § 4]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20354%20§%204[1854 p 354 § 4]; RRS § 5465; ]

== 36.53.050 - Bond of licensee.
Every person applying for a license to keep a ferry shall, before the same is issued, enter into a bond with one or more sureties, to be approved by the county auditor, in a sum not less than one hundred nor more than five hundred dollars, conditioned that such person will keep the ferry according to law and that if default at any time is made in the condition of the bond, damages, not exceeding the penalty, may be recovered by any person aggrieved, before any court having jurisdiction.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.53.050[1963 c 4 § 36.53.050]; Code 1881 § 3006; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1879%20p%2062%20§%2042[1879 p 62 § 42]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20281%20§%2044[1869 p 281 § 44]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20522%20§%205[1863 p 522 § 5]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20354%20§%205[1854 p 354 § 5]; RRS § 5466; ]

== 36.53.060 - Duties of licensee.
Every person obtaining a license to keep a ferry shall provide and keep in good and complete repair the necessary boat or boats for the safe conveyance of all persons and property, and furnish such boats at all times with suitable oars, setting poles, and other implements necessary for the service thereof, and shall keep a sufficient number of discreet and skillful men or women ferry workers to attend and manage the same; and he or she shall also at all times keep the place of embarking and landing in good order and repair, by cutting away the bank of the stream so that persons and property may be embarked and landed without danger or unnecessary delay.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204088[2009 c 549 § 4088]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.53.060[1963 c 4 § 36.53.060]; Code 1881 § 3007; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1879%20p%2062%20§%2043[1879 p 62 § 43]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20281%20§%2045[1869 p 281 § 45]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20522%20§%206[1863 p 522 § 6]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20354%20§%206[1854 p 354 § 6]; RRS § 5467; ]

== 36.53.070 - Duties of licensee—Duties as to ferriage—Liability for nonperformance.
Every person obtaining a ferry license shall give constant and diligent attention to such ferry from daylight in the morning until dark in the evening of each day, and shall, moreover, at any hour in the night, if required, except in cases of imminent danger, give passage to all persons requiring the same on the payment of double rate of ferriage allowed to be taken in the daytime.

If the licensee at any time neglects or refuses to give passage to any person or property, the licensee shall forfeit and pay to the party aggrieved for every such offense the sum of five dollars, to be recovered before any district judge having jurisdiction; the licensee shall, moreover, be liable in an action at law for any special damage which such person may have sustained in consequence of such neglect or refusal.

No forfeiture or damages shall be recovered for a failure or refusal to convey any person or property across the stream when it is manifestly hazardous to do so, by reason of any storm, flood, or ice; nor shall any keeper of a ferry be compelled to give passage to any person or property until the fare or toll chargeable by law has been fully paid or tendered.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c202.pdf?cite=1987%20c%20202%20§%20207[1987 c 202 § 207]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.53.070[1963 c 4 § 36.53.070]; Code 1881 § 3008; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1879%20p%2062%20§%2044[1879 p 62 § 44]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20281%20§%2046[1869 p 281 § 46]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20523%20§%207[1863 p 523 § 7]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20355%20§%207[1854 p 355 § 7]; RRS § 5468; ]

== 36.53.080 - Rates of ferriage.
Whenever the board of county commissioners grants a license to keep a ferry across any lake or stream, it shall establish the rates of ferriage which may be lawfully demanded for the transportation of persons and property across the same, having due regard for the breadth and situation of the stream, and the dangers and difficulties incident thereto, and the publicity of the place at which the same is established, and every keeper of a ferry who at any time demands and receives more than the amount so designated for ferrying shall forfeit and pay to the party aggrieved, for every such offense, the sum of five dollars, over and above the amount which has been illegally received, to be recovered before any district judge having jurisdiction.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c202.pdf?cite=1987%20c%20202%20§%20208[1987 c 202 § 208]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.53.080[1963 c 4 § 36.53.080]; Code 1881 § 3009; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1879%20p%2063%20§%2045[1879 p 63 § 45]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20282%20§%2047[1869 p 282 § 47]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20523%20§%208[1863 p 523 § 8]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20355%20§%208[1854 p 355 § 8]; RRS § 5469; ]

== 36.53.090 - Commissioners may fix and alter rates.
The boards of county commissioners may fix, alter, and establish from time to time, the rates of ferriage to be levied and collected at all ferries established by law, within or bordering upon the county lines of any of the counties in this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.53.090[1963 c 4 § 36.53.090]; Code 1881 § 3010; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1879%20p%2063%20§%2046[1879 p 63 § 46]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20282%20§%2048[1869 p 282 § 48]; RRS § 5470; ]

== 36.53.100 - Rates to be posted.
Every person licensed to keep a ferry shall post up, in some conspicuous place near his or her ferry landing a list of the rates of ferriage which are chargeable by law at such ferry, which list of rates shall at all times be plain and legible and posted up so near the place where persons pass across the ferry that it may be easily read. If the keeper neglects or refuses to post and keep up such list, it shall not be lawful to charge or take any ferriage or compensation at the ferry, during the time of such delinquency.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204089[2009 c 549 § 4089]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.53.100[1963 c 4 § 36.53.100]; Code 1881 § 3011; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1879%20p%2063%20§%2047[1879 p 63 § 47]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20283%20§%2049[1869 p 283 § 49]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20523%20§%209[1863 p 523 § 9]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20355%20§%209[1854 p 355 § 9]; RRS § 5471; ]

== 36.53.110 - Order of ferriage—Liability for nonperformance.
All persons shall be received into the ferry boats and conveyed across the stream over which a ferry is established according to their arrival thereat, and if the keeper of a ferry acts contrary to this regulation, the keeper shall forfeit and pay to the party aggrieved the sum of ten dollars for every such offense, to be recovered before any district judge having jurisdiction: PROVIDED, That public officers on urgent business, post riders, couriers, physicians, surgeons, and midwives shall in all cases be first carried over, when all cannot go at the same time.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c202.pdf?cite=1987%20c%20202%20§%20209[1987 c 202 § 209]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.53.110[1963 c 4 § 36.53.110]; Code 1881 § 3012; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1879%20p%2063%20§%2048[1879 p 63 § 48]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20283%20§%2050[1869 p 283 § 50]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20524%20§%2010[1863 p 524 § 10]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20356%20§%2010[1854 p 356 § 10]; RRS § 5472; ]

== 36.53.120 - Grant exclusive.
Every person licensed to keep a ferry under the provisions of RCW 36.53.010 through 36.53.140 shall have the exclusive privilege of transporting all persons and property over and across the stream where the ferry is established, and shall be entitled to all the fare arising by law therefrom: PROVIDED, That any person may cross such stream at the ferry location in his or her own boat, or take in and carry over his or her neighbor, when done without fee or charge, and not with intent to injure the person licensed to keep a ferry.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204090[2009 c 549 § 4090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.53.120[1963 c 4 § 36.53.120]; Code 1881 § 3013; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1879%20p%2063%20§%2049[1879 p 63 § 49]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20283%20§%2051[1869 p 283 § 51]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20524%20§%2011[1863 p 524 § 11]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20356%20§%2011[1854 p 356 § 11]; RRS § 5473; ]

== 36.53.130 - Revocation of license.
If any person licensed to keep a ferry fails to pay the taxes assessed thereon when due, or to provide and keep in good and complete repair the necessary boat or boats, with the oars, setting poles, and other necessary implements for the service thereof, or to employ a sufficient number of skilled and discreet ferry workers within three months from the time license is granted, or if the ferry is not at any time kept in good condition and repair, or if it is abandoned, disused, or unfrequented for the space of six months at any one time, the board of county commissioners, on complaint being made in writing, may summon the person licensed to keep such ferry, to show cause why his or her license should not be revoked. The board may revoke or not according to the testimony adduced and the laws of this state, the decision subject to review by the superior court: PROVIDED, That if disuse resulted because the stream is fordable at certain seasons of the year, or because travel by that route is subject to periodical fluctuations, it shall not work a forfeiture within the meaning of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204091[2009 c 549 § 4091]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.53.130[1963 c 4 § 36.53.130]; Code 1881 § 3014; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1879%20p%2064%20§%2050[1879 p 64 § 50]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20283%20§%2052[1869 p 283 § 52]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20524%20§%2012[1863 p 524 § 12]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20356%20§%2012[1854 p 356 § 12]; RRS § 5474; ]

== 36.53.140 - Penalty for maintaining unlicensed ferry.
Any person who maintains any ferry and receives ferriage without first obtaining a license therefor shall pay a fine of ten dollars for each offense, to be collected for the use of the county, by suit before any district judge having jurisdiction, and any person may bring such suit: PROVIDED, That it shall not be unlawful for any person to transport any other person or property over any stream for hire, when there is no ferry, or the ferry established at such place was not in actual operation at the time, or in sufficient repair to have afforded to such person or property a safe and speedy passage.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c202.pdf?cite=1987%20c%20202%20§%20210[1987 c 202 § 210]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.53.140[1963 c 4 § 36.53.140]; Code 1881 § 3015; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1879%20p%2064%20§%2051[1879 p 64 § 51]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20284%20§%2053[1869 p 284 § 53]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20525%20§%2013[1863 p 525 § 13]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20356%20§%2013[1854 p 356 § 13]; RRS § 5475; ]

== 36.53.150 - Interstate ferry—County may contribute to—Grant of permit to operator.
Whenever the board of county commissioners of any county determines that the construction or maintenance of a ferry in a state adjoining such county or connecting such county with the adjoining state is of necessity or convenience to the citizens of the county, the board may enter into a contract for the construction or maintenance of such ferry, or make such contribution as may be deemed advisable toward the construction or maintenance thereof, and may lease, or grant exclusive permits to use, any wharf or landing owned or leased by the board to any person, firm or corporation furnishing, or agreeing to furnish, ferry service between such county and the adjoining state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.53.150[1963 c 4 § 36.53.150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c165.pdf?cite=1921%20c%20165%20§%201[1921 c 165 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1915c26.pdf?cite=1915%20c%2026%20§%201[1915 c 26 § 1]; RRS § 5478; ]

