= 36.64 - Joint governmental activities.
:toc:

== 36.64.010 - Joint courthouse and city hall.
If the county seat of a county is in an incorporated city, the county and city may contract, one with the other, for the joint purchase, acquisition, leasing, ownership, control, and disposition of land and other property suitable as a site for a county courthouse and city hall and for the joint construction, ownership, control, and disposition of a building or buildings thereon for the use by such county and city as a county courthouse and city hall. Any county or city owning a site or any interest therein, or a site with buildings thereon, may, upon such terms as appear fair and just to the board of county commissioners of such county and to the legislative body of such city, contract with reference to the joint ownership, acquisition, leasing, control, improvement, and occupation of such property.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.64.010[1963 c 4 § 36.64.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c90.pdf?cite=1913%20c%2090%20§%201[1913 c 90 § 1]; RRS § 3992; ]

== 36.64.020 - Joint courthouse and city hall—Terms of contract.
A contract made in pursuance of RCW 36.64.010 shall fully set forth the amount of money to be contributed by each towards acquisition of the site and the improvement thereof and the manner in which such property shall be improved and the character of the building or buildings to be erected thereon. The contract may provide for the amount of money to be contributed annually by each for the upkeep and maintenance of the property and the building or buildings thereon, or it may provide for the relative proportion of such expense which such county and city shall annually pay. The contract shall specify the parts of such building or buildings which shall be set apart for the exclusive use and occupation of each.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.64.020[1963 c 4 § 36.64.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c90.pdf?cite=1913%20c%2090%20§%202[1913 c 90 § 2]; RRS § 3993; ]

== 36.64.030 - Joint courthouse and city hall—Approval of contract.
The contract between a county and a city shall be made only after a proper resolution of the board of county commissioners of the county and a proper ordinance of the city have been passed specifically authorizing it. The contract shall be binding upon the county and the city during the term thereof, or until it is modified or abrogated by mutual consent evidenced by a proper resolution and ordinance of the county and city.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.64.030[1963 c 4 § 36.64.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c90.pdf?cite=1913%20c%2090%20§%204[1913 c 90 § 4]; RRS § 3995; ]

== 36.64.040 - Joint courthouse and city hall—Funds, how provided.
The money to be contributed by a county or a city or both may be raised by a sale of its bonds, or by general taxation. Any county or city possessing funds or having funds available for a county courthouse or city hall from the sale of bonds or otherwise, may contract for the expenditure of such funds.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.64.040[1963 c 4 § 36.64.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c90.pdf?cite=1913%20c%2090%20§%203[1913 c 90 § 3]; RRS § 3994; ]

== 36.64.050 - Joint armory sites.
Any city or county in the state may expend money from its current expense funds in payment in whole or in part for an armory site whenever the legislature has authorized the construction of an armory within such city or county.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.64.050[1963 c 4 § 36.64.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c91.pdf?cite=1913%20c%2091%20§%201[1913 c 91 § 1]; RRS § 3996; ]

== 36.64.060 - Joint canal construction.
Whenever the county legislative authority of a county with a population of one hundred twenty-five thousand or more deems it for the interest of the county to construct or to aid the United States in constructing a canal to connect any bodies of water within the county, such county may construct such canal or aid the United States in constructing it and incur indebtedness for such purpose to an amount not exceeding five hundred thousand dollars and issue its negotiable bonds therefor in the manner and form provided in RCW 36.67.010. Such construction or aid in construction is a county purpose.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1201-S.SL.pdf?cite=1991%20c%20363%20§%2077[1991 c 363 § 77]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%20105[1985 c 7 § 105]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%2078[1983 c 3 § 78]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.64.060[1963 c 4 § 36.64.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1907c158.pdf?cite=1907%20c%20158%20§%201[1907 c 158 § 1]; RRS § 9664.   1907 c 158 § 2; RRS § 9665; ]

== 36.64.070 - Counties with populations of two hundred ten thousand or more—Contracts with cities concerning buildings and related improvements.
Any county with a population of two hundred ten thousand or more may contract with any city or cities within such county for the financing, erection, ownership, use, lease, operation, control or maintenance of any building or buildings, including open spaces, off-street parking facilities for the use of county and city employees and persons doing business with such county or city, plazas and other improvements incident thereto, for county or city, or combined county-city, or other public use. Property for such buildings and related improvements may be acquired by either such county or city or by both by lease, purchase, donation, exchange, and/or gift or by eminent domain in the manner provided by law for the exercise of such power by counties and cities respectively and any property acquired hereunder, together with the improvements thereon, may be sold, exchanged or leased, as the interests of said county, city or cities may from time to time require.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1201-S.SL.pdf?cite=1991%20c%20363%20§%2078[1991 c 363 § 78]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c24.pdf?cite=1965%20c%2024%20§%201[1965 c 24 § 1]; ]

== 36.64.080 - Conferences to study regional and governmental problems—Counties and cities may establish—Subjects—Recommendations.
The boards of county commissioners of any county and any counties contiguous thereto and the governing body of any cities and/or towns within said counties may establish and organize a regional agency hereinafter referred to as a conference, for the purpose of studying regional and governmental problems of mutual interest and concern, including but not limited to, facility studies on highways, transit, airports, ports or harbor development, water supply and distribution, codes and ordinances, governmental finances, flood control, air and water pollution, recommendations of sites for schools and educational institutions, hospitals and health facilities, parks and recreation, public buildings, land use and drainage; and to formulate recommendations for review and action by the member counties and/or cities legislative body.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c84.pdf?cite=1965%20ex.s.%20c%2084%20§%201[1965 ex.s. c 84 § 1]; ]

== 36.64.090 - Conferences to study regional and governmental problems—Articles—Officers—Agents and employees.
The governing bodies of the counties and cities so associated in a conference shall adopt articles of association and bylaws, select a chair and such other officers as they may determine, and may employ and discharge such agents and employees as the officers deem convenient to carry out the purposes of the conference.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204100[2009 c 549 § 4100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c84.pdf?cite=1965%20ex.s.%20c%2084%20§%202[1965 ex.s. c 84 § 2]; ]

== 36.64.100 - Conferences to study regional and governmental problems—Contracts with other governmental agencies—Grants and gifts—Consultants.
The conference is authorized to contract generally and to enter into any contract with the federal government, the state, any municipal corporation and/or other governmental agency for the purpose of conducting the study of regional problems of mutual concern, and shall have the power to receive grants and gifts in furtherance of the program. The conference may retain consultants if deemed advisable.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c84.pdf?cite=1965%20ex.s.%20c%2084%20§%203[1965 ex.s. c 84 § 3]; ]

== 36.64.110 - Conferences to study regional and governmental problems—Public purpose—Contributions to support by municipal corporations.
The formation of the conference is hereby declared to be a public purpose, and any municipal corporation may contribute to the expenses of such conference pursuant to the budgetary laws of the municipal corporations and such bylaws as may be adopted by the conference: PROVIDED, That services and facilities may be provided by a municipal corporation in lieu of assessment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c84.pdf?cite=1965%20ex.s.%20c%2084%20§%204[1965 ex.s. c 84 § 4]; ]

