= 36.87 - Roads and bridges—Vacation.
:toc:

== 36.87.010 - Resolution of intention to vacate.
When a county road or any part thereof is considered useless, the board by resolution entered upon its minutes, may declare its intention to vacate and abandon the same or any portion thereof and shall direct the county road engineer to report upon such vacation and abandonment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c185.pdf?cite=1969%20ex.s.%20c%20185%20§%201[1969 ex.s. c 185 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.87.010[1963 c 4 § 36.87.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c187.pdf?cite=1937%20c%20187%20§%2048[1937 c 187 § 48]; RRS § 6450-48; ]

== 36.87.020 - County road frontage owners' petition—Bond, cash deposit, or fee.
Owners of the majority of the frontage on any county road or portion thereof may petition the county legislative authority to vacate and abandon the same or any portion thereof. The petition must show the land owned by each petitioner and set forth that such county road is useless as part of the county road system and that the public will be benefited by its vacation and abandonment. The legislative authority may (1) require the petitioners to make an appropriate cash deposit or furnish an appropriate bond against which all costs and expenses incurred in the examination, report, and proceedings pertaining to the petition shall be charged; or (2) by ordinance or resolution require the petitioners to pay a fee adequate to cover such costs and expenses.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1201-S.SL.pdf?cite=1991%20c%20363%20§%2089[1991 c 363 § 89]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c369.pdf?cite=1985%20c%20369%20§%204[1985 c 369 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.87.020[1963 c 4 § 36.87.020]; 1937 c 187 § 49, part; RRS § 6450-49, part; ]

== 36.87.030 - County road frontage owners' petition—Action on petition.
On the filing of the petition and bond and on being satisfied that the petition has been signed by petitioners residing in the vicinity of the county road or portion thereof, the board shall direct the county road engineer to report upon such vacation and abandonment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.87.030[1963 c 4 § 36.87.030]; 1937 c 187 § 49, part; RRS § 6450-49, part; ]

== 36.87.040 - Engineer's report.
When directed by the board the county road engineer shall examine any county road or portion thereof proposed to be vacated and abandoned and report his or her opinion as to whether the county road should be vacated and abandoned, whether the same is in use or has been in use, the condition of the road, whether it will be advisable to preserve it for the county road system in the future, whether the public will be benefited by the vacation and abandonment, and all other facts, matters, and things which will be of importance to the board, and also file his or her cost bill.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204139[2009 c 549 § 4139]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.87.040[1963 c 4 § 36.87.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c187.pdf?cite=1937%20c%20187%20§%2050[1937 c 187 § 50]; RRS § 6450-50; ]

== 36.87.050 - Notice of hearing on report.
Notice of hearing upon the report for vacation and abandonment of a county road shall be published at least once a week for two consecutive weeks preceding the date fixed for the hearing, in the county official newspaper and a copy of the notice shall be posted for at least twenty days preceding the date fixed for hearing at each termini of the county road or portion thereof proposed to be vacated or abandoned.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.87.050[1963 c 4 § 36.87.050]; 1937 c 187 § 51, part; RRS § 6450-51, part; ]

== 36.87.060 - Hearing.
. On the day fixed for the hearing, the county legislative authority shall proceed to consider the report of the engineer, together with any evidence for or objection against such vacation and abandonment. If the county road is found useful as a part of the county road system it shall not be vacated, but if it is not useful and the public will be benefited by the vacation, the county legislative authority may vacate the road or any portion thereof. Its decision shall be entered in the minutes of the hearing.

. As an alternative, the county legislative authority may appoint a hearing officer to conduct a public hearing to consider the report of the engineer and to take testimony and evidence relating to the proposed vacation. Following the hearing, the hearing officer shall prepare a record of the proceedings and a recommendation to the county legislative authority concerning the proposed vacation. Their decision shall be made at a regular or special public meeting of the county legislative authority.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c369.pdf?cite=1985%20c%20369%20§%205[1985 c 369 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.87.060[1963 c 4 § 36.87.060]; 1937 c 187 § 51, part; RRS § 6450-51, part; ]

== 36.87.070 - Expense of proceeding.
If the county legislative authority has required the petitioners to make a cash deposit or furnish a bond, upon completion of the hearing, it shall certify all costs and expenses incurred in the proceedings to the county treasurer and, regardless of its final decision, the county legislative authority shall recover all such costs and expenses from the bond or cash deposit and release any balance to the petitioners.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c369.pdf?cite=1985%20c%20369%20§%206[1985 c 369 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.87.070[1963 c 4 § 36.87.070]; 1937 c 187 § 51, part; RRS § 6450-51, part; ]

== 36.87.080 - Majority vote required.
No county road shall be vacated and abandoned except by majority vote of the board properly entered, or by operation of law, or judgment of a court of competent jurisdiction.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c185.pdf?cite=1969%20ex.s.%20c%20185%20§%202[1969 ex.s. c 185 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.87.080[1963 c 4 § 36.87.080]; 1937 c 187 § 51, part; RRS § 6450-51, part; ]

== 36.87.090 - Vacation of road unopened for five years—Exceptions.
Any county road, or part thereof, which remains unopen for public use for a period of five years after the order is made or authority granted for opening it, shall be thereby vacated, and the authority for building it barred by lapse of time: PROVIDED, That this section shall not apply to any highway, road, street, alley, or other public place dedicated as such in any plat, whether the land included in such plat is within or without the limits of an incorporated city or town, or to any land conveyed by deed to the state or to any county, city or town for highways, roads, streets, alleys, or other public places.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.87.090[1963 c 4 § 36.87.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c187.pdf?cite=1937%20c%20187%20§%2052[1937 c 187 § 52]; RRS § 6450-52; ]

== 36.87.100 - Classification of roads for which public expenditures made—Compensation of county.
Any board of county commissioners may, by ordinance, classify all county roads for which public expenditures were made in the acquisition, improvement or maintenance of the same, according to the type and amount of expenditures made and the nature of the county's property interest in the road; and may require persons benefiting from the vacation of county roads within some or all of the said classes to compensate the county as a condition precedent to the vacation thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c185.pdf?cite=1969%20ex.s.%20c%20185%20§%204[1969 ex.s. c 185 § 4]; ]

== 36.87.110 - Classification of roads for which no public expenditures made—Compensation of county.
Any board of county commissioners may, by ordinance, separately classify county roads for which no public expenditures have been made in the acquisition, improvement or maintenance of the same, according to the nature of the county's property interest in the road; and may require persons benefiting from the vacation of county roads within some or all of the said classes to compensate the county as a condition precedent to the vacation thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c185.pdf?cite=1969%20ex.s.%20c%20185%20§%205[1969 ex.s. c 185 § 5]; ]

== 36.87.120 - Appraised value as basis for compensation—Appraisal costs.
Any ordinance adopted pursuant to this chapter may require that compensation for the vacation of county roads within particular classes shall equal all or a percentage of the appraised value of the vacated road as of the effective date of the vacation. In determining the appropriate compensation for the road or right-of-way, the board may adjust the appraised value to reflect the value of the transfer of liability or risk, the increased value to the public in property taxes, the avoided costs for management or maintenance, and any limits on development or future public benefit. Costs of county appraisals of roads pursuant to such ordinances shall be deemed expenses incurred in vacation proceedings, and shall be paid in the manner provided by RCW 36.87.070.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6314-S.SL.pdf?cite=2016%20c%2019%20§%202[2016 c 19 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c185.pdf?cite=1969%20ex.s.%20c%20185%20§%206[1969 ex.s. c 185 § 6]; ]

== 36.87.130 - Vacation of roads abutting bodies of water—When authorized. (Effective until December 31, 2023.)
No county shall vacate a county road or part thereof which abuts on a body of salt or freshwater unless:

. The purpose of the vacation is to enable any public authority to acquire the vacated property for port purposes, boat moorage or launching sites, or for park, viewpoint, recreational, educational, or other public purposes;

. The property is zoned for industrial uses; or

. In a county west of the crest of the Cascade mountains and bordered by the Columbia river with a population over four hundred fifty thousand, the county determines that:

.. The road has been used as an access point to trespass onto private property;

.. Such trespass has caused loss of human life, and that public use of the county road creates an ongoing risk to public safety; and

.. Public access to the same body of water abutting the county road is available at not less than three public access sites within two miles in any direction of the terminus of the road subject to vacation.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5613.SL.pdf?cite=2020%20c%20300%20§%201[2020 c 300 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c185.pdf?cite=1969%20ex.s.%20c%20185%20§%207[1969 ex.s. c 185 § 7]; ]

== 36.87.140 - Retention of easement for public utilities and services.
Whenever a county road or any portion thereof is vacated the legislative body may include in the resolution authorizing the vacation a provision that the county retain an easement in respect to the vacated land for the construction, repair, and maintenance of public utilities and services which at the time the resolution is adopted are authorized or are physically located on a portion of the land being vacated: PROVIDED, That the legislative body shall not convey such easement to any public utility or other entity or person but may convey a permit or franchise to a public utility to effectuate the intent of this section. The term "public utility" as used in this section shall include utilities owned, operated, or maintained by every gas company, electrical company, telephone company, telegraph company, and water company whether or not such company is privately owned or owned by a governmental entity.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c22.pdf?cite=1975%20c%2022%20§%201[1975 c 22 § 1]; ]

