= 36.95 - Television reception improvement districts.
:toc:

== 36.95.010 - Purpose.
The purposes of a television reception improvement district, hereinafter referred to in this chapter as "district", shall be to serve the public interest, convenience, and necessity in the construction, maintenance, and operation of television and FM radio translator stations, including appropriate electric or electronic devices for increasing television program distribution, but said purposes are not meant to include the construction or operation of television cable systems, commonly known and referred to as cable TV systems or CATV.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c76.pdf?cite=1985%20c%2076%20§%201[1985 c 76 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c155.pdf?cite=1971%20ex.s.%20c%20155%20§%201[1971 ex.s. c 155 § 1]; ]

== 36.95.020 - Boundaries—Territory excluded.
A district's boundary may include any part or all of any county and may include any part or all of any incorporated area located within the county. A district's boundary may not include any territory already being served by a cable TV system (CATV) unless on August 9, 1971, there is a translator station retransmitting television signals to such territory.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1201-S.SL.pdf?cite=1991%20c%20363%20§%2098[1991 c 363 § 98]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c155.pdf?cite=1971%20ex.s.%20c%20155%20§%202[1971 ex.s. c 155 § 2]; ]

== 36.95.030 - Petition to form—Contents.
A petition to form a district may be presented to the board of county commissioners and such petition shall include: (1) A description of the purposes of the petition; (2) a description of the purposes and powers of the proposed district; (3) a description of the boundaries of the proposed district; and (4) the signatures of more than fifty percent of the registered voters residing within the boundaries of the proposed district.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c155.pdf?cite=1971%20ex.s.%20c%20155%20§%203[1971 ex.s. c 155 § 3]; ]

== 36.95.040 - Notice of text of petition, meeting where will be considered.
If the board of county commissioners, with the assistance of other appropriate county officers, finds the petition filed under RCW 36.95.030 satisfies the requirements of that section, it shall cause the text of the petition to be published once a week for at least three consecutive weeks in a newspaper of general circulation within the county where the petition is presented. With the publication of the petition there shall be published a notice of the time, date, and place of the public meeting of the county commissioners when the petition will be considered, stating that persons interested may appear and be heard.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c155.pdf?cite=1971%20ex.s.%20c%20155%20§%204[1971 ex.s. c 155 § 4]; ]

== 36.95.050 - Resolution creating district.
If after the public meeting or meetings on the petition, the board of county commissioners finds that creation of the proposed district would serve the public interest, the board shall adopt a resolution granting the petition and creating the district. Prior to adoption however, the board may amend the petition in the interest of carrying out the purposes of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c155.pdf?cite=1971%20ex.s.%20c%20155%20§%205[1971 ex.s. c 155 § 5]; ]

== 36.95.060 - District board—Duties—How constituted—Quorum—Officers—Filling vacancies.
The business of the district shall be conducted by the board of the television reception improvement district, hereinafter referred to as the "board". The board shall be constituted as provided under either subsection (1) or (2) of this section.

. The board of a district having boundaries different from the county's shall have either three, five, seven, or nine members, as determined by the board of county commissioners at the time the district is created. Each member shall reside within the boundaries of the district and shall be appointed by the board of county commissioners for a term of three years, or until his or her successor has qualified, except that the board of county commissioners shall appoint one of the members of the first board to a one-year term and two to two-year terms. There is no limit upon the number of terms to which a member may be reappointed after his or her first appointment. A majority of the members of the board shall constitute a quorum for the transaction of business, but the majority vote of the board members shall be necessary for any action taken by the board. The board shall elect from among its members a chair and such other officers as may be necessary. In the event a seat on the board is vacated prior to the expiration of the term of the member appointed to such seat, the board of county commissioners shall appoint a person to complete the unexpired term.

. Upon the creation of a district having boundaries identical to those of the county (a countywide district), the county commissioners shall be the members of the board of the district and shall have all the powers and duties of the board as provided under the other sections of this chapter. The county commissioners shall be reimbursed pursuant to the provisions of RCW 36.95.070, and shall conduct the business of the district according to the regular rules and procedures applicable to meetings of the board of county commissioners.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204157[2009 c 549 § 4157]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6444.SL.pdf?cite=1992%20c%20150%20§%201[1992 c 150 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c155.pdf?cite=1971%20ex.s.%20c%20155%20§%206[1971 ex.s. c 155 § 6]; ]

== 36.95.070 - District board—Reimbursement of members for expenses.
Members of the board shall receive no compensation for their services, but shall be reimbursed from district funds for any actual and necessary expenses incurred by them in the performance of their official duties.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c155.pdf?cite=1971%20ex.s.%20c%20155%20§%207[1971 ex.s. c 155 § 7]; ]

== 36.95.080 - List of television set owners.
The board shall, on or before the first day of July of any given year, ascertain and prepare a list of all persons believed to own television sets within the district and deliver a copy of such list to the county treasurer.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c222.pdf?cite=1988%20c%20222%20§%201[1988 c 222 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c52.pdf?cite=1981%20c%2052%20§%201[1981 c 52 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c155.pdf?cite=1971%20ex.s.%20c%20155%20§%208[1971 ex.s. c 155 § 8]; ]

== 36.95.090 - County budget provisions applicable to district—Financing budget.
The provisions of chapter 36.40 RCW, relating to budgets, shall apply to the district. The budget of the district shall be financed by an excise tax imposed by the board, and described in RCW 36.95.100.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c155.pdf?cite=1971%20ex.s.%20c%20155%20§%209[1971 ex.s. c 155 § 9]; ]

== 36.95.100 - Tax levied—Maximum—Exemptions.
. The tax provided for in RCW 36.95.090 and this section may not exceed sixty dollars per year per television set within the district. No person may be taxed for more than one television set, except that a motel or hotel or any person owning more than five television sets must pay at a rate of one-fifth of the annual tax rate imposed for each of the first five television sets and one-tenth of the annual tax rate imposed for each additional television set. 

. An owner of a television set within the district is exempt from paying the excise tax on the television set if:

.. The owner's television set does not receive at least a class grade B contour signal retransmitted by the television translator station or other similar device operated by the district, as such class is defined under regulations of the Federal Communications Commission as of August 9, 1971;

.. The owner is currently subscribing to and receiving the services of a community antenna system (CATV) to which the owner's television set is connected; or

.. The owner is currently subscribing to and receiving the services of a satellite carrier, as that term is defined in 17 U.S.C. Sec. 119, as of January 1, 2013.

. To qualify for an exemption specified in subsection (2) of this section, an owner of a television set must file a statement with the board claiming the owner's grounds for an exemption. Space for the statement must be provided in tax notices sent to taxpayers pursuant to RCW 36.95.160.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1068-S.SL.pdf?cite=2013%20c%20191%20§%201[2013 c 191 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204158[2009 c 549 § 4158]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c52.pdf?cite=1981%20c%2052%20§%202[1981 c 52 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975c11.pdf?cite=1975%20c%2011%20§%201[1975 c 11 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c155.pdf?cite=1971%20ex.s.%20c%20155%20§%2010[1971 ex.s. c 155 § 10]; ]

== 36.95.110 - Liability for delinquent tax and costs.
Any person owing the excise tax provided for under this chapter and who fails to pay the same within sixty days after the board or the county treasurer has sent the tax bill to him or her, shall be deemed to be delinquent. Such person shall be liable for all costs to the county or district attributable to collecting the tax but no such excise tax or costs, nor any judgment based thereon, shall be deemed to create a lien against real property.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204159[2009 c 549 § 4159]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c52.pdf?cite=1981%20c%2052%20§%203[1981 c 52 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c155.pdf?cite=1971%20ex.s.%20c%20155%20§%2011[1971 ex.s. c 155 § 11]; ]

== 36.95.120 - Prorating tax.
The board may adopt rules providing for prorating of tax bills for persons who have not owned a television set within the district for a full tax year.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c155.pdf?cite=1971%20ex.s.%20c%20155%20§%2012[1971 ex.s. c 155 § 12]; ]

== 36.95.130 - District board—Powers generally.
In addition to other powers provided for under this chapter, the board has the following powers:

. To perform all acts necessary to assure that the purposes of this chapter will be carried out fairly and efficiently;

. To acquire, build, construct, repair, own, maintain, and operate any necessary stations retransmitting visual and aural signals intended to be received by the general public, relay stations, pickup stations, or any other electrical or electronic system necessary. However, the board has no power to originate programs;

. To make contracts to compensate any owner of land or other property for the use of such property for the purposes of this chapter;

. To make contracts with the United States, or any state, municipality, or any department or agency of those entities for carrying out the general purposes for which the district is formed;

. To acquire by gift, devise, bequest, lease, or purchase real and personal property, tangible or intangible, including lands, rights-of-way, and easements, necessary or convenient for its purposes;

. To make contracts of any lawful nature (including labor contracts or those for employees' benefits), employ engineers, laboratory personnel, attorneys, other technical or professional assistants, and any other assistants or employees necessary to carry out the provisions of this chapter;

. To contract indebtedness or borrow money and to issue warrants or bonds to be paid from district revenues. The bonds, warrants, or other obligations may be in any form, including bearer or registered as provided in RCW 39.46.030. Moreover, such warrants and bonds may be issued and sold in accordance with chapter 39.46 RCW;

. To prescribe excise tax rates for providing services throughout the area in accordance with the provisions of this chapter;

. To assist the county treasurer in sending tax notices to taxpayers pursuant to RCW 36.95.160; and

. To apply for, accept, and be the holder of any permit or license issued by or required under federal or state law.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1068-S.SL.pdf?cite=2013%20c%20191%20§%202[2013 c 191 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c76.pdf?cite=1985%20c%2076%20§%202[1985 c 76 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c167.pdf?cite=1983%20c%20167%20§%20102[1983 c 167 § 102]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c100.pdf?cite=1980%20c%20100%20§%202[1980 c 100 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c155.pdf?cite=1971%20ex.s.%20c%20155%20§%2013[1971 ex.s. c 155 § 13]; ]

== 36.95.140 - Signals district may utilize.
A district may translate or retransmit only those signals which originate from commercial and educational FM radio stations and commercial and educational television stations which directly provide, within some portion of the state of Washington, a class A grade or class B grade contour, as such classes are defined under regulations of the Federal Communications Commission as of August 9, 1971.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c76.pdf?cite=1985%20c%2076%20§%203[1985 c 76 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c155.pdf?cite=1971%20ex.s.%20c%20155%20§%2014[1971 ex.s. c 155 § 14]; ]

== 36.95.150 - Claims against district board—Procedure upon allowance.
Any claim against the district shall be presented to the board. Upon allowance of the claim, the board shall submit a voucher, signed by the chair and one other member of the board, to the county auditor for the issuance of a warrant in payment of said claim. This procedure for payment of claims shall apply to the reimbursement of board members for their actual and necessary expenses incurred by them in the performance of their official duties.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204160[2009 c 549 § 4160]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c155.pdf?cite=1971%20ex.s.%20c%20155%20§%2015[1971 ex.s. c 155 § 15]; ]

== 36.95.160 - District treasurer—Duties—District warrants.
. The treasurer of the county in which a district is located is the treasurer of the district.

. The county treasurer must collect the excise tax provided for under this chapter and send notice of payment due to persons owing the tax. To reduce costs of services performed by the county treasurer, district board members and employees may assist the treasurer in sending tax notices to taxpayers.

. Districts with fewer than twelve hundred persons subject to the excise tax and levying an excise tax of forty dollars or more per television set per year may:

.. Send tax notices bimonthly; and

.. Collect excise tax revenue, which must be forwarded to the county treasurer for deposit in the district account. 

. All district funds must be deposited with the county treasurer. All district payments must be made by the county treasurer from district funds upon warrants issued by the county auditor, except the sums to be paid out of any bond fund for principal and interest payments on bonds. All warrants must be paid in the order of issuance.

. The treasurer must report monthly to the board, in writing, the amount in the district fund or funds.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1068-S.SL.pdf?cite=2013%20c%20191%20§%203[2013 c 191 § 3]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204161[2009 c 549 § 4161]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c167.pdf?cite=1983%20c%20167%20§%20103[1983 c 167 § 103]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c52.pdf?cite=1981%20c%2052%20§%204[1981 c 52 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c155.pdf?cite=1971%20ex.s.%20c%20155%20§%2016[1971 ex.s. c 155 § 16]; ]

== 36.95.180 - Costs of county officers reimbursed.
. The board must reimburse the county auditor, assessor, and treasurer for the actual costs of services performed by them in behalf of the district.

. A district may reduce costs of services performed by the county treasurer by assisting the treasurer in sending tax notices to taxpayers pursuant to RCW 36.95.160.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1068-S.SL.pdf?cite=2013%20c%20191%20§%204[2013 c 191 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c155.pdf?cite=1971%20ex.s.%20c%20155%20§%2018[1971 ex.s. c 155 § 18]; ]

== 36.95.190 - Penalty for false statement as to tax exemption.
Any person who shall knowingly make a false statement for exemption from the tax provided under this chapter shall be guilty of a misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c155.pdf?cite=1971%20ex.s.%20c%20155%20§%2019[1971 ex.s. c 155 § 19]; ]

== 36.95.200 - Dissolution of district by resolution—Disposition of property.
If the board of county commissioners finds, following a public hearing or hearings, that the continued existence of a district would no longer serve the purposes of this chapter, it may by resolution order the district dissolved. If there is any property owned by the district at the time of dissolution, the board of county commissioners shall have such property sold pursuant to the provisions of chapter 36.34 RCW, as now law or hereafter amended. The proceeds from such sale shall be applied to the county current expense fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c155.pdf?cite=1971%20ex.s.%20c%20155%20§%2020[1971 ex.s. c 155 § 20]; ]

== 36.95.210 - District may not be formed to operate certain translator stations.
No television reception improvement district may be formed to operate and maintain any translator station presently or previously owned, operated or maintained by a television broadcaster.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c155.pdf?cite=1971%20ex.s.%20c%20155%20§%2021[1971 ex.s. c 155 § 21]; ]

