= 36.68 - Parks and recreational facilities.
:toc:

== 36.68.010 - Counties may establish park and playground systems—Disposition of surplus park property.
Counties may establish park and playground systems for public recreational purposes and for such purposes shall have the power to acquire lands, buildings and other facilities by gift, purchase, lease, devise, bequest and condemnation. A county may lease or sell any park property, buildings or facilities surplus to its needs, or no longer suitable for park purposes: PROVIDED, That such park property shall be subject to the requirements and provisions of notice, hearing, bid or intergovernmental transfer as provided in chapter 36.34 RCW: PROVIDED FURTHER, That nothing in this section shall be construed as authorizing any county to sell any property which such county acquired by condemnation for park or playground or other public recreational purposes on or after January 1, 1960, until held for five years or more after such acquisition: PROVIDED FURTHER, That funds acquired from the lease or sale of any park property, buildings or facilities shall be placed in the park and recreation fund to be used for capital purposes.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.68.010[1963 c 4 § 36.68.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c92.pdf?cite=1961%20c%2092%20§%201[1961 c 92 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c94.pdf?cite=1949%20c%2094%20§%201[1949 c 94 § 1]; Rem. Supp. 1949 § 3991-14; ]

== 36.68.020 - Programs of public recreation.
Counties may conduct programs of public recreation, and in any such program property or facilities owned by any individual, group or organization, whether public or private, may be utilized by consent of the owner.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.68.020[1963 c 4 § 36.68.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c94.pdf?cite=1949%20c%2094%20§%202[1949 c 94 § 2]; Rem. Supp. 1949 § 3991-15; ]

== 36.68.030 - Park and recreation board—Composition.
Each county may form a county park and recreation board composed of seven members, who shall be appointed by the board of county commissioners to serve without compensation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c176.pdf?cite=1969%20ex.s.%20c%20176%20§%2093[1969 ex.s. c 176 § 93]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.68.030[1963 c 4 § 36.68.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c94.pdf?cite=1949%20c%2094%20§%203[1949 c 94 § 3]; Rem. Supp. 1949 § 3991-16; ]

== 36.68.040 - Park and recreation board—Terms of members.
For the appointive positions on the county park and recreation board the initial terms shall be two years for two positions, four years for two positions, and six years for the remaining positions plus the period in each instance to the next following June 30th; thereafter the term for each appointive position shall be six years and shall end on June 30th.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c176.pdf?cite=1969%20ex.s.%20c%20176%20§%2094[1969 ex.s. c 176 § 94]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.68.040[1963 c 4 § 36.68.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c94.pdf?cite=1949%20c%2094%20§%204[1949 c 94 § 4]; Rem. Supp. 1949 § 3991-17; ]

== 36.68.050 - Park and recreation board—Removal of members—Vacancies.
Any appointed county park and recreation board member may be removed by a majority vote of the board of county commissioners either for cause or upon the joint written recommendation of five members of the county park and recreation board. Vacancies on the county park and recreation board shall be filled by appointment, made by the board of county commissioners for the unexpired portions of the terms vacated.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.68.050[1963 c 4 § 36.68.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c94.pdf?cite=1949%20c%2094%20§%205[1949 c 94 § 5]; Rem. Supp. 1949 § 3991-18; ]

== 36.68.060 - Park and recreation board—Powers and duties.
The county park and recreation board:

. Shall elect its officers, including a chair, vice chair and secretary, and such other officers as it may determine it requires.

. Shall hold regular public meetings at least monthly.

. Shall adopt rules for transaction of business and shall keep a written record of its meetings, resolutions, transactions, findings and determinations, which record shall be a public record.

. Shall initiate, direct, and administer county recreational activities, and shall select and employ a county park and recreation superintendent and such other properly qualified employees as it may deem desirable.

. Shall improve, operate, and maintain parks, playgrounds, and other recreational facilities, together with all structures and equipment useful in connection therewith, and may recommend to the board of county commissioners acquisition of real property.

. Shall promulgate and enforce reasonable rules and regulations deemed necessary in the operation of parks, playgrounds, and other recreational facilities, and may recommend to the board of county commissioners adoption of any rules or regulations requiring enforcement by legal process which relate to parks, playgrounds, or other recreational facilities.

. Shall each year submit to the board of county commissioners for approval a proposed budget for the following year in the manner provided by law for the preparation and submission of budgets by elective or appointive county officials.

. May, subject to the approval of the board of county commissioners, enter into contracts with any other municipal corporation, governmental or private agency for the conduct of park and recreational programs.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204102[2009 c 549 § 4102]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.68.060[1963 c 4 § 36.68.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c94.pdf?cite=1949%20c%2094%20§%206[1949 c 94 § 6]; Rem. Supp. 1949 § 3991-19; ]

== 36.68.070 - Park and recreation fund.
In counties in which county park and recreation boards are formed, a county park and recreation fund shall be established. Into this fund shall be placed the allocation as the board of county commissioners annually appropriates thereto, together with miscellaneous revenues derived from the operation of parks, playgrounds, and other recreational facilities, as well as grants, gifts, and bequests for park or recreational purposes. All expenditures shall be disbursed from this fund by the county park and recreation board, and all balances remaining in this fund at the end of any year shall be carried over in such fund to the succeeding year.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.68.070[1963 c 4 § 36.68.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c94.pdf?cite=1949%20c%2094%20§%207[1949 c 94 § 7]; Rem. Supp. 1949 § 3991-20; ]

== 36.68.080 - Penalty for violations of regulations.
. Except as otherwise provided in this section, any person violating any rules or regulations adopted by the board of county commissioners relating to parks, playgrounds, or other recreational facilities is guilty of a misdemeanor.

. [Empty]
.. Except as provided in (b) of this subsection, violation of such a rule or regulation relating to traffic including parking, standing, stopping, and pedestrian offenses is a traffic infraction.

.. Violation of such a rule or regulation equivalent to those provisions of Title 46 RCW set forth in RCW 46.63.020 remains a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20205[2003 c 53 § 205]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c136.pdf?cite=1979%20ex.s.%20c%20136%20§%2036[1979 ex.s. c 136 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.68.080[1963 c 4 § 36.68.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c94.pdf?cite=1949%20c%2094%20§%208[1949 c 94 § 8]; Rem. Supp. 1949 § 3991-21; ]

== 36.68.090 - Counties authorized to build, improve, operate and maintain, etc., parks, playgrounds, gymnasiums, swimming pools, beaches, stadiums, golf courses, etc., and other recreational facilities—Regulation—Charges for use.
Any county, acting through its board of county commissioners, is empowered to build, construct, care for, control, supervise, improve, operate and maintain parks, playgrounds, gymnasiums, swimming pools, field houses, bathing beaches, stadiums, golf courses, automobile racetracks and drag strips, coliseums for the display of spectator sports, public campgrounds, boat ramps and launching sites, public hunting and fishing areas, arboretums, bicycle and bridle paths, and other recreational facilities, and to that end may make, promulgate and enforce such rules and regulations regarding the use thereof, and make such charges for the use thereof, as may be deemed by said board to be reasonable.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c144.pdf?cite=1967%20ex.s.%20c%20144%20§%2011[1967 ex.s. c 144 § 11]; ]

== 36.68.100 - Moorage facilities—Regulations authorized—Port charges, delinquency—Abandoned vessels, public sale.
See RCW 53.08.310 and 53.08.320.

[ ]

== 36.68.110 - Counties authorized to permit public libraries on land used for park and recreation purposes.
A county, acting through its county legislative authority, is authorized to permit the location of public libraries on land owned by the county that is used for park and recreation purposes, unless a covenant or other binding restriction precludes such uses.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1978-S.SL.pdf?cite=1993%20c%2084%20§%201[1993 c 84 § 1]; ]

== 36.68.120 - Community athletics programs—Sex discrimination prohibited.
The antidiscrimination provisions of RCW 49.60.500 apply to community athletics programs and facilities operated, conducted, or administered by a park and recreation service area.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5967-S.SL.pdf?cite=2009%20c%20467%20§%208[2009 c 467 § 8]; ]

== 36.68.400 - Creation authorized—Purposes—Taxing districts—Powers.
Any county shall have the power to create park and recreation service areas for the purpose of financing, acquiring, constructing, improving, maintaining, or operating any park, senior citizen activities centers, zoos, aquariums, and recreational facilities as defined in RCW 36.69.010 which shall be owned or leased by the county and administered as other county parks or shall be owned or leased and administered by a city or town or shall be owned or leased and administered by the park and recreation service area. A park and recreation service area may purchase athletic equipment and supplies, and provide for the upkeep of park buildings, grounds and facilities, and provide custodial, recreational and park program personnel at any park or recreational facility owned or leased by the service area or a county, city, or town. A park and recreation service area shall be a quasi-municipal corporation, an independent taxing "authority" within the meaning of section 1, Article 7 of the Constitution, and a "taxing district" within the meaning of section 2, Article 7 of the Constitution.

A park and recreation service area shall constitute a body corporate and shall possess all the usual powers of a corporation for public purposes including, but not limited to, the authority to hire employees, staff, and services, to enter into contracts, to accept and expend or use gifts, grants, and donations, and to sue and be sued as well as all other powers that may now or hereafter be specifically conferred by statute.

The members of the county legislative authority, acting ex officio and independently, shall compose the governing body of any park and recreation service area which is created within the county: PROVIDED, That where a park and recreation service area includes an incorporated city or town within the county, the park and recreation service area may be governed as provided in an interlocal agreement adopted pursuant to chapter 39.34 RCW. The voters of a park and recreation service area shall be all registered voters residing within the service area.

A multicounty park and recreation service area shall be governed as provided in an interlocal agreement adopted pursuant to chapter 39.34 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c82.pdf?cite=1988%20c%2082%20§%201[1988 c 82 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c253.pdf?cite=1985%20c%20253%20§%201[1985 c 253 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c210.pdf?cite=1981%20c%20210%20§%201[1981 c 210 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c76.pdf?cite=1965%20ex.s.%20c%2076%20§%201[1965 ex.s. c 76 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c218.pdf?cite=1963%20c%20218%20§%201[1963 c 218 § 1]; ]

== 36.68.410 - May be initiated by resolution or petition.
Park and recreation service areas may be initiated in any unincorporated area of any county by resolution adopted by the county legislative authority or by a petition signed by ten percent of the registered voters within the proposed park and recreation service area. Incorporated areas may be included under RCW 36.68.610 and 36.68.620.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c210.pdf?cite=1981%20c%20210%20§%202[1981 c 210 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c76.pdf?cite=1965%20ex.s.%20c%2076%20§%202[1965 ex.s. c 76 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c218.pdf?cite=1963%20c%20218%20§%202[1963 c 218 § 2]; ]

== 36.68.420 - Resolution or petition—Contents.
Any resolution or petition initiating a proposed park and recreation service area shall set forth the boundaries of the service area with certainty, describe the purpose or purposes for which the service area is to be formed, and contain an estimate of the initial cost of any capital improvements or services to be authorized in the service area.

"Initial costs" as used herein shall include the estimated cost during the first year of operation of:

. Land to be acquired or leased for neighborhood park purposes by the service area to establish a park or park facility specified in the resolution or petition;

. Capital improvements specified in the objectives or purposes of the service area;

. Forming the service area; and

. Personnel, maintenance or operation of any park facility within the service area as specified by the resolution or petition.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c210.pdf?cite=1981%20c%20210%20§%203[1981 c 210 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c218.pdf?cite=1963%20c%20218%20§%203[1963 c 218 § 3]; ]

== 36.68.430 - Petitions—Verification of signatures.
Petitions shall be submitted to the county auditor who shall verify the signatures thereon to determine that the petition has been signed by the requisite number of persons who are registered voters within the proposed service area. If the petition is found not to have the requisite number of signatures, it shall be returned to the petitioners. If the petition is found to be sufficient, the auditor shall so certify and transmit the same to the board of county commissioners.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c218.pdf?cite=1963%20c%20218%20§%204[1963 c 218 § 4]; ]

== 36.68.440 - Feasibility and cost studies—Public hearing—Notice.
Upon accepting a petition to form a park and recreation service area, or upon passage of a resolution to establish such a service area, the county legislative authority shall order a full investigation for the purpose or purposes of the proposed service area to determine the feasibility of forming the same and to determine the estimated initial costs involved in obtaining the objectives set forth in the petition or resolution. The reports on the feasibility and the cost of the proposed service area shall be made available to the county legislative authority, and copies of such reports shall be filed with the clerk of the county legislative authority not more than eighty days after the county legislative authority first directs that the studies and reports be undertaken. The county legislative authority shall also provide by resolution that within twenty days after receiving the reports a public hearing shall be held at the county seat or at some convenient location within the proposed service area. At least five days before the hearing, the county legislative authority shall give notice of the hearing not less than twice in a legal newspaper of general circulation in the county. The notice shall describe the boundaries of the proposed service area, the purpose or purposes of the proposed service area, the estimated initial costs, indicate that the reports and other materials prepared at the order of the county legislative authority are available in the office of the clerk of the county legislative authority for the study and review of any interested party, and set the time, date and place of the hearing.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c210.pdf?cite=1981%20c%20210%20§%204[1981 c 210 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c218.pdf?cite=1963%20c%20218%20§%205[1963 c 218 § 5]; ]

== 36.68.450 - Hearing procedure—Inclusion of property—Examination of reports—Recess.
At the hearing, the county legislative authority shall first provide for an explanation of the objectives of the proposed park and recreation service area and the estimated initial costs thereof. The county legislative authority shall permit any resident or property owner of the proposed service area to appear and be heard, and may permit property owners in contiguous areas to include their property within the proposed service area in the event that they make their request for inclusion in writing. The county legislative authority shall examine all reports on the feasibility of the proposed service area and its initial costs and may, if they deem it necessary, recess the hearing for not more than twenty days to obtain any additional information necessary to arrive at the findings provided for in RCW 36.68.420.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c210.pdf?cite=1981%20c%20210%20§%205[1981 c 210 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c218.pdf?cite=1963%20c%20218%20§%206[1963 c 218 § 6]; ]

== 36.68.460 - Findings of county commissioners—Dismissal of proceedings, limitation on subsequent initiation.
At the conclusion of a hearing, the board of county commissioners shall make the following findings:

. Whether or not the service area's objectives fit within the general framework of the county's comprehensive park plan and general park policies.

. The exact boundaries of the service area: The board shall be empowered to modify the boundaries as originally defined in the petition or resolution initiating the proposed service area: PROVIDED, That the boundaries of the service area may not be enlarged unless the property owners within the area to be added consent to their inclusion in writing; or unless the board gives the property owners of the area to be added, written notice, mailed to their regular permanent residences as shown on the latest records of the county auditor, five days prior to a regular or continued hearing upon the formation of the proposed service area.

. A full definition or explanation of the nature of improvements or services to be financed by the proposed service area.

. Whether or not the objectives of the service area are feasible.

. The number or name of the service area.

If satisfactory findings cannot be made by the board, the petition or resolution shall be dismissed, and no petition or resolution embracing the same area may be accepted or heard for at least two years.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c218.pdf?cite=1963%20c%20218%20§%207[1963 c 218 § 7]; ]

== 36.68.470 - Resolution ordering election—Election procedure—Formation.
. Upon making findings under the provisions of RCW 36.68.460, the county legislative authority shall, by resolution, order an election of the voters of the proposed park and recreation service area to determine if the service area shall be formed. The county legislative authority shall in their resolution direct the county auditor to set the election to be held at the next general election or at a special election held for such purpose; describe the purposes of the proposed service area; set forth the estimated cost of any initial improvements or services to be financed by the service area should it be formed; describe the method of financing the initial improvements or services described in the resolution or petition; and order that notice of election be published in a newspaper of general circulation in the county at least twice prior to the election date.

. A proposition to form a park and recreation service area shall be submitted to the voters of the proposed service area. Upon approval by a majority of the voters voting on the proposition, a park and recreation service area shall be established. The proposition submitted to the voters by the county auditor on the ballot shall be in substantially the following form:

FORMATION OF PARK ANDRECREATION SERVICE AREAShall a park and recreation service area be established for the area described in a resolution of the legislative authority of . . . . . . county, adopted on the . . . . day of . . . . . . (year) . . . ., to provide financing for neighborhood park facilities, improvements, and services?Yes . . . . . .No . . . . . .

FORMATION OF PARK AND

RECREATION SERVICE AREA

Shall a park and recreation service area be established for the area described in a resolution of the legislative authority of . . . . . . county, adopted on the . . . . day of . . . . . . (year) . . . ., to provide financing for neighborhood park facilities, improvements, and services?

Yes . . . . . .

No . . . . . .

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2359-S.SL.pdf?cite=2016%20c%20202%20§%2031[2016 c 202 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c210.pdf?cite=1981%20c%20210%20§%206[1981 c 210 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c218.pdf?cite=1963%20c%20218%20§%208[1963 c 218 § 8]; ]

== 36.68.480 - Property tax levies or bond retirement levies—Election.
If the petition or resolution initiating the formation of the proposed park and recreation service area proposes that the initial capital or operational costs are to be financed by regular property tax levies for a six-year period as authorized by RCW 36.68.525, or an annual excess levy, or that proposed capital costs are to be financed by the issuance of general obligation bonds and bond retirement levies, a proposition or propositions for such purpose or purposes shall be submitted to the voters of the proposed service area at the same election. A proposition or propositions for regular property tax levies for a six-year period as authorized by RCW 36.68.525, an annual excess levy, or the issuance of general obligation bonds and bond retirement levies, may also be submitted to the voters at any general or special election.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c131.pdf?cite=1984%20c%20131%20§%207[1984 c 131 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c210.pdf?cite=1981%20c%20210%20§%207[1981 c 210 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c195.pdf?cite=1973%201st%20ex.s.%20c%20195%20§%2038[1973 1st ex.s. c 195 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c218.pdf?cite=1963%20c%20218%20§%209[1963 c 218 § 9]; ]

== 36.68.490 - Annual excess levy or bond retirement levies—Election procedure—Vote required.
In order for the annual excess tax levy proposition or bond retirement levies proposition to be approved, voters exceeding in number at least sixty percent of the number of voters who cast ballots for the office of county legislative authority within the park and recreation area, or within the proposed service area, in the last preceding general election for that office must cast ballots on the tax levy proposition, and of all the votes cast at the election at least sixty percent of said votes must approve the annual excess tax levy or the bond retirement levies.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c210.pdf?cite=1981%20c%20210%20§%208[1981 c 210 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c218.pdf?cite=1963%20c%20218%20§%2010[1963 c 218 § 10]; ]

== 36.68.500 - Resolution declaring formation—Treasurer—Disbursement procedure.
If the formation of the service area is approved by the voters, the county legislative authority shall by resolution declare the service area to be formed and direct the county treasurer to be the treasurer of the service area. Expenditures of the service area shall be made upon warrants drawn by the county auditor pursuant to vouchers approved by the governing body of the service area.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c210.pdf?cite=1981%20c%20210%20§%209[1981 c 210 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c218.pdf?cite=1963%20c%20218%20§%2011[1963 c 218 § 11]; ]

== 36.68.510 - Local service area fund.
If the service area is formed, there shall be created in the office of the county treasurer a local service area fund with such accounts as the treasurer may find convenient, or as the state auditor may direct, into which shall be deposited all revenues received by the service area from tax levy, from gifts or donations, and from service or admission charges. Such fund shall be designated "(name of county) service area No. . . . . fund." Or "(name of district) service area fund." Special accounts shall be established within the fund for the deposit of the proceeds of each bond issue made for the construction of a specified project or improvement, and there shall also be established special accounts, within the fund for the deposit of revenues raised by special levy or derived from other specific revenues, to be used exclusively for the retirement of an outstanding bond issue or for paying the interest or service charges on any bond issue.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c218.pdf?cite=1963%20c%20218%20§%2012[1963 c 218 § 12]; ]

== 36.68.520 - Annual excess property tax levy—General obligation bonds.
. A park and recreation service area shall have the power to levy annual excess levies upon the property included within the service area if authorized at a special election called for the purpose in the manner prescribed by section 2, Article VII of the Constitution and by RCW 84.52.052 for operating funds, capital outlay funds, and cumulative reserve funds.

. A park and recreation service area may issue general obligation bonds for capital purposes only, not to exceed an amount, together with any outstanding nonvoter approved general obligation indebtedness, equal to three-eighths of one percent of the value of the taxable property within the service area. Additionally, a park and recreation service area may issue general obligation bonds, together with any outstanding voter approved and nonvoter approved general indebtedness, equal to two and one-half percent of the value of the taxable property within the service area, as the term "value of the taxable property" is defined in RCW 39.36.015, when such bonds are approved by the voters of the service area at a special election called for the purpose in accordance with the provisions of Article VIII, section 6 of the Constitution. Such bonds shall be issued and sold in accordance with chapter 39.46 RCW.

Bonds may be retired by excess property tax levies when such levies are approved by the voters at a special election in accordance with the provisions of Article VII, section 2 of the Constitution and RCW 84.52.056.

Any elections shall be held as provided in RCW 39.36.050.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1122-S.SL.pdf?cite=1994%20c%20156%20§%204[1994 c 156 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c186.pdf?cite=1984%20c%20186%20§%2029[1984 c 186 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c131.pdf?cite=1984%20c%20131%20§%208[1984 c 131 § 8]; 1983 c 167 § 271;  1984 c 186 § 70; and; 1984 c 131 § 10; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c167.pdf?cite=1983%20c%20167%20§%2083[1983 c 167 § 83]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c210.pdf?cite=1981%20c%20210%20§%2010[1981 c 210 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c195.pdf?cite=1973%201st%20ex.s.%20c%20195%20§%2039[1973 1st ex.s. c 195 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c42.pdf?cite=1970%20ex.s.%20c%2042%20§%2019[1970 ex.s. c 42 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c218.pdf?cite=1963%20c%20218%20§%2013[1963 c 218 § 13]; ]

== 36.68.525 - Six-year regular property tax levies—Limitations—Election.
A park and recreation service area may impose regular property tax levies in an amount equal to sixty cents or less per thousand dollars of assessed value of property in the service area in each year for six consecutive years when specifically authorized so to do by a majority of at least three-fifths of the voters thereof approving a proposition authorizing the levies submitted not more than twelve months prior to the date on which the proposed initial levy is to be made and not oftener than twice in such twelve-month period, either at a special election or at the regular election of the service area, at which election the number of voters voting "yes" on the proposition must constitute three-fifths of a number equal to forty percent of the number of voters voting in the service area at the last preceding general election when the number of voters voting on the proposition does not exceed forty percent of the number of voters voting in such taxing district in the last preceding general election; or by a majority of at least three-fifths of the voters thereof voting on the proposition if the number of voters voting on the proposition exceeds forty per centum of the number of voters voting in such taxing district in the last preceding general election. A proposition authorizing such tax levies may not be submitted by a park and recreation service area more than twice in any twelve-month period. Ballot propositions must conform with RCW 29A.36.210. If a park and recreation service area is levying property taxes, which in combination with property taxes levied by other taxing districts result in taxes in excess of the limitation provided for in RCW 84.52.043(2), the park and recreation service area property tax levy must be reduced or eliminated as provided in RCW 84.52.010.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1597-S2.SL.pdf?cite=2010%20c%20106%20§%20302[2010 c 106 § 302]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1122-S.SL.pdf?cite=1994%20c%20156%20§%205[1994 c 156 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c131.pdf?cite=1984%20c%20131%20§%209[1984 c 131 § 9]; ]

== 36.68.527 - Community revitalization financing—Public improvements.
In addition to other authority that a park and recreation service area possesses, a park and recreation service area may provide any public improvement as defined under RCW 39.89.020, but this additional authority is limited to participating in the financing of the public improvements as provided under RCW 39.89.050.

This section does not limit the authority of a park and recreation service area to otherwise participate in the public improvements if that authority exists elsewhere.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1418-S.SL.pdf?cite=2001%20c%20212%20§%2014[2001 c 212 § 14]; ]

== 36.68.530 - Budgets—Appropriations—Accumulation of reserves.
The governing body of each park and recreation service area shall annually compile a budget for each service area in a form prescribed by the state auditor for the ensuing calendar year which shall, to the extent that anticipated income is actually realized, constitute the appropriations for the service area. The budget may include an amount to accumulate a reserve for a stated capital purpose. In compiling the budget, all available funds and anticipated income shall be taken into consideration, including contributions or contractual payments from school districts, cities, or towns, county or any other governmental entity, gifts and donations, special tax levy, fees and charges, proceeds of bond issues, and cumulative reserve funds.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1889.SL.pdf?cite=1995%20c%20301%20§%2067[1995 c 301 § 67]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c210.pdf?cite=1981%20c%20210%20§%2011[1981 c 210 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c218.pdf?cite=1963%20c%20218%20§%2014[1963 c 218 § 14]; ]

== 36.68.541 - Employees.
Park and recreation service areas may hire employees and may fund all or a portion of the salaries and benefits of county park employees who perform work on county park and recreation facilities within the service area and may fund all or a portion of the salaries and benefits of city or town park employees who perform work on city or town park and recreation facilities within the service area.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c82.pdf?cite=1988%20c%2082%20§%202[1988 c 82 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c210.pdf?cite=1981%20c%20210%20§%2012[1981 c 210 § 12]; ]

== 36.68.550 - Use and admission fees and charges.
A park and recreation service area may impose and collect use fees or other direct charges on facilities financed, acquired, and operated by the park and recreation service area. The county legislative authority may allow admission fees or other direct charges which are paid by persons using county park facilities located within a park and recreation service area to be transferred to a park and recreation service area. Such direct charges to users may be made for the use of or admission to swimming pools, field houses, tennis and handball courts, bathhouses, swimming beaches, boat launching, storage or moorage facilities, ski lifts, picnic areas and other similar recreation facilities, and for parking lots used in conjunction with such facilities. All funds collected under the provisions of this section shall be deposited to the fund of the service area established in the office of the county treasurer, to be disbursed under the service area budget as approved by the governing body of the park and recreation service area.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c82.pdf?cite=1988%20c%2082%20§%203[1988 c 82 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c210.pdf?cite=1981%20c%20210%20§%2013[1981 c 210 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c218.pdf?cite=1963%20c%20218%20§%2016[1963 c 218 § 16]; ]

== 36.68.555 - Eminent domain.
A park and recreation service area may exercise the power of eminent domain to obtain property for its authorized purposes in a manner consistent with the power of eminent domain of the county in which the park and recreation service area is located.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c82.pdf?cite=1988%20c%2082%20§%208[1988 c 82 § 8]; ]

== 36.68.560 - Concessions.
The county legislative authority may transfer the proceeds from concessions for food and other services accruing to the county from park or park facilities which are located in a park and recreation service area to the fund of the service area in the office of the county treasurer to be disbursed under the service area budget.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c210.pdf?cite=1981%20c%20210%20§%2014[1981 c 210 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c218.pdf?cite=1963%20c%20218%20§%2017[1963 c 218 § 17]; ]

== 36.68.570 - Use of funds—Purchases.
A park and recreation service area may reimburse the county for any charge incurred by the county current expense fund which is properly an expense of the service area, including reasonable administrative costs incurred by the offices of county treasurer and the county auditor in providing accounting, clerical or other services for the benefit of the service area. The county legislative authority may, where a county purchasing department has been established, provide for the purchase of all supplies and equipment for a park and recreation service area through the department. The park and recreation service area may contract with the county to administer purchasing.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c82.pdf?cite=1988%20c%2082%20§%204[1988 c 82 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c210.pdf?cite=1981%20c%20210%20§%2015[1981 c 210 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c218.pdf?cite=1963%20c%20218%20§%2018[1963 c 218 § 18]; ]

== 36.68.580 - Ownership of parks and facilities—Expenditure of funds budgeted for park purposes.
Any park facility or park acquired, improved or otherwise financed in whole or in part by park and recreation service area funds shall be owned by the park service area and/or the county and/or the city or town in which the park or facility is located. The county may make expenditures from its current expense funds budgeted for park purposes for the maintenance, operation or capital improvement of any county park or park facility acquired, improved, or otherwise financed in whole or in part by park and recreation service area funds. Similarly, a city or town may make expenditures for any city or town park or park facility acquired, improved, or otherwise financed in whole or in part by park and recreation service area funds.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c82.pdf?cite=1988%20c%2082%20§%205[1988 c 82 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c210.pdf?cite=1981%20c%20210%20§%2016[1981 c 210 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c218.pdf?cite=1963%20c%20218%20§%2019[1963 c 218 § 19]; ]

== 36.68.590 - Purpose—Level of services—General park programs.
The purpose of RCW 36.68.400 et seq. shall be to provide a higher level of park services and shall not in any way diminish the right of a county to provide a general park program financed from current expense funds.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c218.pdf?cite=1963%20c%20218%20§%2020[1963 c 218 § 20]; ]

== 36.68.600 - Use of park and recreation service area funds in exercise of powers enumerated in chapter  67.20 RCW.
A park and recreation service area may exercise any of the powers enumerated in chapter 67.20 RCW with respect to any park and recreation facility financed in whole or part from park and recreation service area funds.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c82.pdf?cite=1988%20c%2082%20§%206[1988 c 82 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c210.pdf?cite=1981%20c%20210%20§%2017[1981 c 210 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c218.pdf?cite=1963%20c%20218%20§%2021[1963 c 218 § 21]; ]

== 36.68.610 - Area which may be included—Inclusion of area within city or town—Procedure.
A park and recreation service area may include any unincorporated area in the state, and when any part of the proposed district lies within the corporate limits of any city or town said resolution or petition shall be accompanied by a certified copy of a resolution of the governing body of said city or town, approving inclusion of the area within the corporate limits of the city or town.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c65.pdf?cite=1973%20c%2065%20§%201[1973 c 65 § 1]; ]

== 36.68.620 - Enlargement by inclusion of additional area—Procedure.
After a park and recreation service area has been organized, an additional area may be added by the same procedure within the proposed additional area as is provided herein for the organization of a park and recreation service area, and all electors within both the organized park and recreation service area and the proposed additional territory shall vote upon the proposition for enlargement.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c65.pdf?cite=1973%20c%2065%20§%202[1973 c 65 § 2]; ]

