= 36.26 - Public defender.
:toc:

== 36.26.010 - Definitions.
As used in this chapter:

. "County commissioners" or "board of county commissioners" means and includes:

.. Any single board of county commissioners, county council, or other governing body of any county which has neither a board of county commissioners nor a county council denominated as such; and

.. The governing bodies, including any combination or mixture of more than one board of county commissioners, county council, or otherwise denominated governing body of a county, of any two or more contiguous counties electing to participate jointly in the support of any intercounty public defender.

. "District" or "public defender district" means any one or more entire counties electing to employ a public defender; and no county shall be divided in the creation of any public defender district.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c94.pdf?cite=1969%20c%2094%20§%201[1969 c 94 § 1]; ]

== 36.26.020 - Public defender district—Creation—Office of public defender.
The board of county commissioners of any single county or of any two or more territorially contiguous counties or acting in cooperation with the governing authority of any city located within the county or counties may, by resolution or by ordinance, or by concurrent resolutions or concurrent ordinances, constitute such county or counties or counties and cities as a public defender district, and may establish an office of public defender for such district.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c94.pdf?cite=1969%20c%2094%20§%202[1969 c 94 § 2]; ]

== 36.26.030 - Selection committee.
The board of county commissioners of every county electing to become or to join in a public defender district shall appoint a selection committee for the purpose of selecting a full or part time public defender for the public defender district. Such selection committee shall consist of one member of each board of county commissioners, one member of the superior court from each county, and one practicing attorney from each county within the district.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c94.pdf?cite=1969%20c%2094%20§%203[1969 c 94 § 3]; ]

== 36.26.040 - Public defender—Qualifications—Term.
Every public defender and every assistant public defender must be a qualified attorney licensed to practice law in this state; and the term of the public defender shall coincide with the elected term of the prosecuting attorney.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c94.pdf?cite=1969%20c%2094%20§%204[1969 c 94 § 4]; ]

== 36.26.050 - Reports—Records—Costs and expenses.
The public defender shall make an annual report to each board of county commissioners within his or her district. If any public defender district embraces more than one county or a cooperating city, the public defender shall maintain records of expenses allocable to each county or city within the district, and shall charge such expenses only against the county or city for which the services were rendered or the costs incurred. The boards of county commissioners of counties and the governing authority of any city participating jointly in a public defender district are authorized to provide for the sharing of the costs of the district by mutual agreement, for any costs which cannot be specifically apportioned to any particular county or city within the district.

Expenditures by the public defender shall be subject to the provisions of chapter 36.40 RCW and other statutes relating to expenditures by counties or cities.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204041[2009 c 549 § 4041]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c94.pdf?cite=1969%20c%2094%20§%205[1969 c 94 § 5]; ]

== 36.26.060 - Compensation—Office—Assistants, clerks, investigators, etc.
. The board of county commissioners shall:

.. Fix the compensation of the public defender and of any staff appointed to assist him or her in the discharge of his or her duties: PROVIDED, That the compensation of the public defender shall not exceed that of the county prosecutor in those districts which comprise only one county;

.. Provide office space, furniture, equipment and supplies for the use of the public defender suitable for the conduct of his or her office in the discharge of his or her duties, or provide an allowance in lieu of facilities and supplies.

. The public defender may appoint as many assistant attorney public defenders, clerks, investigators, stenographers and other employees as the board of county commissioners considers necessary in the discharge of his or her duties as a public defender.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204042[2009 c 549 § 4042]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c94.pdf?cite=1969%20c%2094%20§%206[1969 c 94 § 6]; ]

== 36.26.070 - Duty to represent indigent defendants.
The public defender must represent, without charge to any accused, every indigent person who is or has been arrested or charged with a crime for which court appointed counsel for indigent defendants is required either under the Constitution of the United States or under the Constitution and laws of the state of Washington:

. If such arrested person or accused, having been apprised of his or her constitutional and statutory rights to counsel, requests the appointment of counsel to represent him or her; and

. If a court, on its own motion or otherwise, does not appoint counsel to represent the accused; and

. Unless the arrested person or accused, having been apprised of his or her right to counsel in open court, affirmatively rejects or intelligently repudiates his or her constitutional and statutory rights to be represented by counsel.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204043[2009 c 549 § 4043]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c76.pdf?cite=1984%20c%2076%20§%2018[1984 c 76 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c94.pdf?cite=1969%20c%2094%20§%207[1969 c 94 § 7]; ]

== 36.26.080 - Duty to counsel, defend, and prosecute appeals.
Whenever the public defender represents any indigent person held in custody without commitment or charged with any criminal offense, he or she must (1) counsel and defend such person, and (2) prosecute any appeals and other remedies, whether before or after conviction, which he or she considers to be in the interests of justice.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204044[2009 c 549 § 4044]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c94.pdf?cite=1969%20c%2094%20§%208[1969 c 94 § 8]; ]

== 36.26.090 - Appointment of attorney other than public defender.
For good cause shown, or in any case involving a crime of widespread notoriety, the court may, upon its own motion or upon application of either the public defender or of the indigent accused, appoint an attorney other than the public defender to represent the accused at any stage of the proceedings or on appeal: PROVIDED, That the public defender may represent an accused, not an indigent, in any case of public notoriety where the court may find that adequate retained counsel is not available. The court shall award, and the county in which the offense is alleged to have been committed shall pay, such attorney reasonable compensation and reimbursement for any expenses reasonably and necessarily incurred in the presentation of the accused's defense or appeal, in accordance with RCW 4.88.330.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c76.pdf?cite=1984%20c%2076%20§%2019[1984 c 76 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%2076[1983 c 3 § 76]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c94.pdf?cite=1969%20c%2094%20§%209[1969 c 94 § 9]; ]

== 36.26.900 - Chapter cumulative and nonexclusive.
The provisions of this chapter shall be cumulative and nonexclusive and shall not affect any other remedy, particularly in counties electing not to create the office of public defender: PROVIDED, That nothing herein shall be construed to prevent the appointment of a full time or part time assigned-counsel administrator for the purpose of maintaining a centrally administered system for the assignment of counsel to represent indigent persons.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c94.pdf?cite=1969%20c%2094%20§%2010[1969 c 94 § 10]; ]

