= 36.28 - County sheriff.
:toc:

== 36.28.010 - General duties.
The sheriff is the chief executive officer and conservator of the peace of the county. In the execution of his or her office, he or she and his or her deputies:

. Shall arrest and commit to prison all persons who break the peace, or attempt to break it, and all persons guilty of public offenses;

. Shall defend the county against those who, by riot or otherwise, endanger the public peace or safety;

. Shall execute the process and orders of the courts of justice or judicial officers, when delivered for that purpose, according to law;

. Shall execute all warrants delivered for that purpose by other public officers, according to the provisions of particular statutes;

. Shall attend the sessions of the courts of record held within the county, and obey their lawful orders or directions;

. Shall keep and preserve the peace in their respective counties, and quiet and suppress all affrays, riots, unlawful assemblies and insurrections, for which purpose, and for the service of process in civil or criminal cases, and in apprehending or securing any person for felony or breach of the peace, they may call to their aid such persons, or power of their county as they may deem necessary.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204050[2009 c 549 § 4050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c92.pdf?cite=1965%20c%2092%20§%201[1965 c 92 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.28.010[1963 c 4 § 36.28.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c45.pdf?cite=1891%20c%2045%20§%201[1891 c 45 § 1]; RRS § 4157.  Code 1881 § 2769; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20557%20§%204[1863 p 557 § 4]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20434%20§%204[1854 p 434 § 4]; RRS § 4168; ]

== 36.28.011 - Duty to make complaint.
In addition to the duties contained in RCW 36.28.010, it shall be the duty of all sheriffs to make complaint of all violations of the criminal law, which shall come to their knowledge, within their respective jurisdictions.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.28.011[1963 c 4 § 36.28.011]; 1955 c 10 § 1. Cf. Code 1881 § 2801, part; 1869 p 264 § 311, part; RRS § 4173, part; ]

== 36.28.020 - Powers of deputies, regular and special.
Every deputy sheriff shall possess all the power, and may perform any of the duties, prescribed by law to be performed by the sheriff, and shall serve or execute, according to law, all process, writs, precepts, and orders, issued by lawful authority.

Persons may also be deputed by the sheriff in writing to do particular acts; including the service of process in civil or criminal cases, and the sheriff shall be responsible on his or her official bond for their default or misconduct.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204051[2009 c 549 § 4051]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.28.020[1963 c 4 § 36.28.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c35.pdf?cite=1961%20c%2035%20§%202[1961 c 35 § 2]; prior:  Code 1881 § 2767, part; 1871 p 110 § 1, part; 1863 p 557 § 2, part; 1854 p 434 § 2, part; RRS § 4160, part.   1886 p 174 § 1; Code 1881 § 2768; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20557%20§%203[1863 p 557 § 3]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20434%20§%203[1854 p 434 § 3]; RRS § 4167; ]

== 36.28.025 - Qualifications.
A person who files a declaration of candidacy for the office of sheriff after September 1, 1979, shall have, within twelve months of assuming office, a certificate of completion of a basic law enforcement training program which complies with standards adopted by the criminal justice training commission pursuant to RCW 43.101.080 and * 43.101.160.

This requirement does not apply to persons holding the office of sheriff in any county on September 1, 1979.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c153.pdf?cite=1979%20ex.s.%20c%20153%20§%206[1979 ex.s. c 153 § 6]; ]

== 36.28.030 - New or additional bond of sheriff.
Whenever the company acting as surety on the official bond of a sheriff is disqualified, insolvent, or the penalty of the bond becomes insufficient on account of recovery had thereon, or otherwise, the sheriff shall submit a new or additional bond for approval to the board of county commissioners, if in session, or, if not in session, for the approval of the chair of such board, and file the same, when approved, in the office of the county clerk of his or her county, and such new or additional bond shall be in a penal sum sufficient in amount to equal the sum specified in the original bond when added to the penalty of any existing bond, so that under one or more bonds there shall always be an enforceable obligation of the surety on the official bond or bonds of the sheriff in a penal sum of not less than the amount of the bond as originally approved.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204052[2009 c 549 § 4052]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.28.030[1963 c 4 § 36.28.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c139.pdf?cite=1943%20c%20139%20§%202[1943 c 139 § 2]; Rem. Supp. 1943 § 4155-1; ]

== 36.28.040 - May demand fees in advance.
No sheriff, deputy sheriff, or coroner shall be liable for any damages for neglecting or refusing to serve any civil process unless his or her legal fees are first tendered him or her.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204053[2009 c 549 § 4053]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.28.040[1963 c 4 § 36.28.040]; 1941 c 237 § 1, part; 1935 c 33 § 1, part; Code 1881 § 2772, part; 1863 p 558 § 7, part; 1854 p 434 § 7, part; Rem. Supp. 1941 § 4172, part; ]

== 36.28.050 - May demand indemnifying bond.
If any property levied upon by virtue of any writ of attachment or execution or other order issued to the sheriff out of any court in this state is claimed by any person other than the defendant, and such person or his or her agent or attorney makes affidavit of his or her title thereto or his or her right to possession thereof, stating the value thereof and the basis of such right or title, the sheriff may release such levy, unless the plaintiff on demand indemnifies the sheriff against such claim by an undertaking executed by a sufficient surety.

No claim to such property by any person other than the defendant shall be valid against the sheriff, unless the supporting affidavit is made. Notwithstanding receipt of a proper claim the sheriff shall retain such property under levy a reasonable time to demand such indemnity.

Any sheriff, or other levying officer, may require an indemnifying bond of the plaintiff in all cases where he or she has to take possession of personal property.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204054[2009 c 549 § 4054]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.28.050[1963 c 4 § 36.28.050]; 1941 c 237 § 1, part; 1935 c 33 § 1, part; Code 1881 § 2772, part; 1863 p 558 § 7, part; 1854 p 434 § 7, part; Rem. Supp. 1941 § 4172, part; ]

== 36.28.060 - Duplicate receipts—Penalties.
. The sheriff shall make duplicate receipts for all payments for his or her services specifying the particular items thereof, at the time of payment, whether paid by virtue of the laws of this state or of the United States. Such duplicate receipts shall be numbered consecutively for each month commencing with number one. One of such receipts shall have written or printed upon it the word "original"; and the other shall have written or printed upon it the word "duplicate."

. At the time of payment of any fees, the sheriff shall deliver to the person making payment, either personally or by mail, the copy of the receipt designated "duplicate."

. The receipts designated "original" for each month shall be attached to the verified statement of fees for the corresponding month and the sheriff shall file with the county treasurer of his or her county all original receipts for each month with such verified statement.

. A sheriff shall not receive his or her salary for the preceding month until the provisions of this section have been complied with.

. Any sheriff violating this section, or failing to perform any of the duties required thereby, is guilty of a misdemeanor and shall be fined in any sum not less than ten dollars nor more than fifty dollars for each offense.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20202[2003 c 53 § 202]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.28.060[1963 c 4 § 36.28.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c105.pdf?cite=1909%20c%20105%20§%201[1909 c 105 § 1]; RRS § 4161.   1909 c 105 § 2; RRS § 4162; ]

== 36.28.090 - Service of process when sheriff disqualified.
When there is no sheriff of a county, or he or she is disqualified from any cause from discharging any particular duty, it shall be lawful for the officer or person commanding or desiring the discharge of that duty to appoint some suitable person, a citizen of the county, to execute the same: PROVIDED, That final process shall in no case be executed by any person other than the legally authorized officer; or in case he or she is disqualified, some suitable person appointed by the court, or judge thereof, out of which the process issues, who shall make such appointment in writing; and before such appointment shall take effect, the person appointed shall give security to the party interested for the faithful performance of his or her duties, which bond of suretyship shall be in writing, approved by the court or judge appointing him or her, and be placed on file with the papers in the case.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204055[2009 c 549 § 4055]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.28.090[1963 c 4 § 36.28.090]; Code 1881 § 745; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20172%20§%20687[1869 p 172 § 687]; RRS § 4170; ]

== 36.28.100 - Employment of prisoners.
The sheriff or director of public safety shall employ all able bodied persons sentenced to imprisonment in the county jail in such manner and at such places within the county as may be directed by the legislative authority of the county.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c154.pdf?cite=1973%201st%20ex.s.%20c%20154%20§%2054[1973 1st ex.s. c 154 § 54]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.28.100[1963 c 4 § 36.28.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%2027[1909 c 249 § 27]; RRS § 2279; ]

== 36.28.110 - Sheriff not to practice law.
No sheriff shall appear or practice as attorney in any court, except in their own defense.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2368.SL.pdf?cite=1992%20c%20225%20§%202[1992 c 225 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.28.110[1963 c 4 § 36.28.110]; 1891 c 45 § 4, part; Code 1881 § 2770, part; 1863 p 558 § 5, part; 1854 p 434 § 5, part; RRS § 4171, part; ]

== 36.28.120 - Duty of retiring sheriffs, constables, and coroners—Successors' duties.
All sheriffs, constables and coroners, upon the completion of their term of office and the qualification of their successors, shall deliver and turn over to their successors all writs and other processes in their possession not wholly executed, and all personal property in their possession or under their control held under such writs or processes, and take receipts therefor in duplicate, one of which shall be filed in the office from which such writ or process issued as a paper in the action, which receipt shall be good and sufficient discharge to such officer of and from further charge of the execution of such writs and processes; and they shall also deliver to their successors all official papers and property in their possession or under their control. The successors shall execute or complete the execution of all such writs and processes, and finish and complete all business turned over to them.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.28.120[1963 c 4 § 36.28.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c17.pdf?cite=1895%20c%2017%20§%201[1895 c 17 § 1]; RRS § 4174; ]

== 36.28.130 - Actions by successors and by officials after expiration of term of office validated.
In all cases where any sheriff, constable or coroner has executed any writ or other process delivered to him or her by his or her predecessor, or has completed any business commenced by his or her predecessor under any writ or process, and has completed any other business commenced by his or her predecessor, and in all cases where any sheriff, constable or coroner has executed any writ or other process, or completed any business connected with his or her office after the expiration of his or her term of office, which writ or process he or she had commenced to execute, or which business he or she had commenced to perform, prior to the expiration of his or her term of office, such action shall be valid and effectual for all purposes.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204056[2009 c 549 § 4056]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.28.130[1963 c 4 § 36.28.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c17.pdf?cite=1895%20c%2017%20§%202[1895 c 17 § 2]; RRS § 4175; ]

== 36.28.150 - Liability for fault or misconduct.
Whenever any sheriff neglects to make due return of any writ or other process delivered to him or her to be executed, or is guilty of any default or misconduct in relation thereto, he or she shall be liable to fine or attachment, or both, at the discretion of the court, subject to appeal, such fine, however, not to exceed two hundred dollars; and also to an action for damages to the party aggrieved.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204057[2009 c 549 § 4057]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.28.150[1963 c 4 § 36.28.150]; Code 1881 § 2771; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20558%20§%206[1863 p 558 § 6]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20434%20§%206[1854 p 434 § 6]; RRS § 4169; ]

== 36.28.160 - Office at county seat.
The sheriff must keep an office at the county seat of the county of which he or she is sheriff.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5233.SL.pdf?cite=2009%20c%20105%20§%203[2009 c 105 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.28.160[1963 c 4 § 36.28.160]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c45.pdf?cite=1891%20c%2045%20§%202[1891 c 45 § 2]; RRS § 4158. SLC-RO-14; ]

== 36.28.170 - Standard uniform for sheriffs and deputies.
The executive secretary of the Washington state association of elected county officials, upon written approval of a majority of the sheriffs in the state, shall file with the secretary of state a description of a standard uniform which may be withdrawn or modified by re-filing in the same manner as originally filed. A uniform of the description so filed shall thereafter be reserved exclusively for the use of sheriffs and their deputies: PROVIDED, That the filing of a standard uniform description shall not make mandatory the adoption of said uniform by any county sheriff or his or her deputies.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204059[2009 c 549 § 4059]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c50.pdf?cite=1963%20c%2050%20§%201[1963 c 50 § 1]; ]

== 36.28.180 - Allowance for clothing and other incidentals.
A county may from available funds provide for an allowance for clothing and other incidentals necessary to the performance of official duties for the sheriff and his or her deputies.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204060[2009 c 549 § 4060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c132.pdf?cite=1979%20c%20132%20§%201[1979 c 132 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c50.pdf?cite=1963%20c%2050%20§%202[1963 c 50 § 2]; ]

== 36.28.190 - City contracts to obtain sheriff's office law enforcement services.
See RCW 41.14.250 through 41.14.280.

[ ]

== 36.28.200 - Statewide sexual assault kit tracking system—Participation by sheriff and deputies.
A sheriff and his or her deputies shall participate in the statewide sexual assault kit tracking system established in RCW 43.43.545 for the purpose of tracking the status of all sexual assault kits in the custody of the department and other entities contracting with the department. A sheriff shall begin full participation in the system according to the implementation schedule established by the Washington state patrol.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2530-S2.SL.pdf?cite=2016%20c%20173%20§%204[2016 c 173 § 4]; ]

