= 36.82 - Roads and bridges—Funds—Budget.
:toc:

== 36.82.010 - "County road fund" created.
There is created in each county of the state a county fund to be known as the "county road fund." Any funds which accrue to any county for use upon county roads, shall be credited to and deposited in the county road fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c182.pdf?cite=1969%20ex.s.%20c%20182%20§%2012[1969 ex.s. c 182 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.82.010[1963 c 4 § 36.82.010]; 1943 c 82 § 2, part; 1937 c 187 § 6, part; Rem. Supp. 1943 § 6450-6, part; ]

== 36.82.020 - County road fund—Limitation upon expenditures.
Any funds accruing to and to be deposited in the county road fund arising from any levy in any road district shall be expended for proper county road purposes.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1201-S.SL.pdf?cite=1991%20c%20363%20§%2087[1991 c 363 § 87]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.82.020[1963 c 4 § 36.82.020]; 1943 c 82 § 2, part; 1937 c 187 § 6, part; Rem. Supp. 1943 § 6450-6, part; ]

== 36.82.040 - General tax levy for road fund—Exceptions.
For the purpose of raising revenue for establishing, laying out, constructing, altering, repairing, improving, and maintaining county roads, bridges, and wharves necessary for vehicle ferriage and for other proper county purposes, the board shall annually at the time of making the levy for general purposes make a uniform tax levy throughout the county, or any road district thereof, of not to exceed two dollars and twenty-five cents per thousand dollars of assessed value of the last assessed valuation of the taxable property in the county, or road district thereof, unless other law of the state requires a lower maximum levy, in which event such lower maximum levy shall control. All funds accruing from such levy shall be credited to and deposited in the county road fund except that revenue diverted under RCW 36.33.220 shall be placed in a separate and identifiable account within the county current expense fund and except that revenue diverted under chapter 39.89 RCW shall be expended as provided under chapter 39.89 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1418-S.SL.pdf?cite=2001%20c%20212%20§%2027[2001 c 212 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c195.pdf?cite=1973%201st%20ex.s.%20c%20195%20§%2041[1973 1st ex.s. c 195 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c25.pdf?cite=1971%20ex.s.%20c%2025%20§%202[1971 ex.s. c 25 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.82.040[1963 c 4 § 36.82.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c187.pdf?cite=1937%20c%20187%20§%207[1937 c 187 § 7]; RRS § 6450-7; ]

== 36.82.050 - Receipts from motor vehicle fund to road fund.
Any funds accruing to the credit of any county from the motor vehicle fund shall be paid monthly to the county treasurer and deposited in the county road fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.82.050[1963 c 4 § 36.82.050]; 1937 c 187 § 8, part; RRS § 6450-8, part; ]

== 36.82.060 - Federal reimbursement to road fund.
Any funds accruing to any county by way of reimbursement by the federal government for expenditures made from the county road fund of such county for any proper county road purpose shall be credited to and deposited in the county road fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.82.060[1963 c 4 § 36.82.060]; 1937 c 187 § 8, part; RRS § 6450-8, part; ]

== 36.82.070 - Purpose for which road fund can be used.
. Any money paid to any county road fund may be used for the construction, alteration, repair, improvement, or maintenance of county roads and bridges thereon and for wharves necessary for ferriage of motor vehicle traffic, and for ferries, and for the acquiring, operating, and maintaining of machinery, equipment, quarries, or pits for the extraction of materials, and for the cost of establishing county roads, acquiring rights-of-way therefor, and expenses for the operation of the county engineering office, and for any of the following programs when directly related to county road purposes: (a) Insurance; (b) self-insurance programs; and (c) risk management programs; and for any other proper county road purpose. Such expenditure may be made either independently or in conjunction with the state or any city, town, or tax district within the county. County road purposes include the construction, maintenance, or improvement of park and ride lots. County road purposes also include the removal of barriers to fish passage related to county roads, and include, but are not limited to, the following activities associated with the removal of these barriers: Engineering and technical services; stream bank stabilization; streambed restoration; the placement of weirs, rock, or woody debris; planting; and channel modification. County road funds may be used beyond the county right-of-way for activities clearly associated with removal of fish passage barriers that are the responsibility of the county. Activities related to the removal of barriers to fish passage performed beyond the county right-of-way must not exceed twenty-five percent of the total cost of activities related to fish barrier removal on any one project, and the total annual cost of activities related to the removal of barriers to fish passage performed beyond the county rights-of-way must not exceed one-half of one percent of a county's annual road construction budget. The use of county road funds beyond the county right-of-way for activities associated with the removal of fish barriers is permissive, and wholly within the discretion of the county legislative authority. The use of county road funds beyond the county right-of-way for such activities does not create or impose a legal duty upon a county for salmon recovery work beyond the county right-of-way.

. For counties that consist entirely of islands, county road purposes also include marine uses relating to navigation and moorage. Such a county may deposit revenue collected under RCW 84.52.043 and 36.82.040, in the amount or percentage determined by the county, into a subaccount within the county road fund to be used for marine facilities, including mooring buoys, docks, and aids to navigation.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1868.SL.pdf?cite=2015%20c%20223%20§%201[2015 c 223 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6209.SL.pdf?cite=2010%20c%2043%20§%201[2010 c 43 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1394.SL.pdf?cite=2001%20c%20221%20§%203[2001 c 221 § 3]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1533.SL.pdf?cite=1997%20c%20189%20§%201[1997 c 189 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.82.070[1963 c 4 § 36.82.070]; 1943 c 82 § 5, part; 1937 c 187 § 53, part; Rem. Supp. 1943 § 6450-53, part; ]

== 36.82.075 - Use of county road funds in cooperative agreement with conservation district.
Whenever a county legislative authority enters into a cooperative agreement with a conservation district as provided in chapter 89.08 RCW, the agreement may specify that the county will participate in the cost of any project which can be anticipated to result in a substantial reduction of the amount of soil deposited in a specifically described roadside ditch normally maintained by the county. The amount of participation by the county through the county road fund shall not exceed fifty percent of the project cost and shall be limited to those engineering and construction costs incurred during the initial construction or reconstruction of the project.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c369.pdf?cite=1985%20c%20369%20§%209[1985 c 369 § 9]; ]

== 36.82.080 - Purpose for which road fund can be used—Payment of bond or warrant interest and principal.
The payment of interest or principal on general obligation county road bonds, or retirement of registered warrants both as to principal and interest when such warrants have been issued for a proper county road purpose, are declared to be a proper county road purpose.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c30.pdf?cite=1979%20ex.s.%20c%2030%20§%204[1979 ex.s. c 30 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.82.080[1963 c 4 § 36.82.080]; 1943 c 82 § 5, part; 1937 c 187 § 53, part; Rem. Supp. 1943 § 6450-53, part; ]

== 36.82.090 - Anticipation warrants against road fund.
The board may expend funds from the county road fund or register warrants against the county road fund in anticipation of funds to be paid to the county from the motor vehicle fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.82.090[1963 c 4 § 36.82.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c82.pdf?cite=1943%20c%2082%20§%206[1943 c 82 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c187.pdf?cite=1937%20c%20187%20§%2054[1937 c 187 § 54]; Rem. Supp. 1943 § 6450-54; ]

== 36.82.100 - Purchases of road material extraction equipment—Sale of surplus materials.
The boards of the several counties may purchase and operate, out of the county road fund, rock crushing, gravel, or other road building material extraction equipment.

Any crushed rock, gravel, or other road building material extracted and not directly used or needed by the county in the construction, alteration, repair, improvement, or maintenance of its roads may be sold at actual cost of production by the board to the state or any other county, city, town, or other political subdivision to be used in the construction, alteration, repair, improvement, or maintenance of any state, county, city, town or other proper highway, road or street purpose: PROVIDED, That in counties of less than twelve thousand five hundred population as determined by the 1950 federal census, the boards of commissioners, during such times as the crushing, loading or mixing equipment is actually in operation, or from stockpiles, may sell at actual cost of production such surplus crushed rock, gravel, or other road building material to any other person for private use where the place of contemplated use of such crushed rock, gravel or other road building material is more than fifteen miles distant from the nearest private source of such materials within the county, distance being computed by the closest traveled route: AND PROVIDED FURTHER, That the purchaser presents, at or before the time of delivery to him or her, a treasurer's receipt for payment for such surplus crushed rock, gravel, or any other road building material.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204138[2009 c 549 § 4138]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.82.100[1963 c 4 § 36.82.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c172.pdf?cite=1953%20c%20172%20§%201[1953 c 172 § 1]; 1937 c 187 § 44, part; RRS § 6450-44, part; ]

== 36.82.110 - Voluntary contributions for improvements to county roads—Standards.
Upon voluntary contribution and payment by any person for the actual cost thereof, such person or legislative authority upon the approval of maps, plans, specifications and guaranty bonds as may be required, may place crushed rock gravel or other road building material or make improvements upon any county road. Such work shall be done in accordance with adopted county standards under the supervision of and direction of the county engineer.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c145.pdf?cite=1982%20c%20145%20§%207[1982 c 145 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.82.110[1963 c 4 § 36.82.110]; 1937 c 187 § 44, part; RRS § 6450-44, part; ]

== 36.82.120 - Purchases of road material extraction equipment—Proceeds to road fund.
All proceeds from the sale or placing of any crushed rock, gravel or other road building material shall be deposited in the county road fund to be expended under the same provisions as are by law imposed upon the funds used to produce the crushed rock, gravel, or other road building material extracted and sold.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.82.120[1963 c 4 § 36.82.120]; 1937 c 187 § 44, part; RRS § 6450-44, part; ]

== 36.82.140 - Forest roads may be maintained from road fund.
The board may maintain any forest roads within its county and expend for the maintenance thereof funds accruing to the county road fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.82.140[1963 c 4 § 36.82.140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c187.pdf?cite=1937%20c%20187%20§%2045[1937 c 187 § 45]; RRS § 6450-45; ]

== 36.82.145 - Bicycle paths, lanes, routes, etc., may be constructed, maintained, or improved from county road fund—Standards.
Any funds deposited in the county road fund may be used for the construction, maintenance, or improvement of bicycle paths, lanes, routes, and roadways, and for improvements to make existing streets and roads more suitable and safe for bicycle traffic. Bicycle facilities constructed or modified after December 31, 2012, shall meet or exceed the standards adopted by the design standards committee under RCW 43.32.020.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1700-S.SL.pdf?cite=2012%20c%2067%20§%205[2012 c 67 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c55.pdf?cite=1982%20c%2055%20§%203[1982 c 55 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c141.pdf?cite=1974%20ex.s.%20c%20141%20§%208[1974 ex.s. c 141 § 8]; ]

== 36.82.148 - Use of street and road funds for pedestrian rights-of-way—Standards.
Any county may use any funds available for street or road construction, maintenance, or improvement for building, improving, and maintaining a pedestrian right-of-way and for improvements to make existing streets and roads more suitable and safe for pedestrian travel. Any such paths, lanes, roadways, routes, or streets for which any such street or road funds are expended must be suitable for pedestrian travel purposes and not solely for recreation purposes. A pedestrian right-of-way constructed or modified after December 31, 2012, must meet or exceed the standards adopted by the design standards committee under RCW 43.32.020.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1700-S.SL.pdf?cite=2012%20c%2067%20§%206[2012 c 67 § 6]; ]

== 36.82.160 - County road budget—Road budget to be prepared—Estimates of expenditures.
Each county legislative authority, with the assistance of the county road engineer, shall prepare and file with the county auditor on or before the second Monday in August in each year, detailed and itemized estimates of all expenditures required in the county for the ensuing fiscal year. In the preparation and adoption of the county road budget the legislative authority shall determine and budget sums to become available for the following county road purposes: (1) Administration; (2) bond and warrant retirement; (3) maintenance; (4) construction; (5) operation of equipment rental and revolving fund; and (6) such other items relating to the county road budget as may be required by the county road administration board; and the respective amounts as adopted for these several items in the final budget for the ensuing calendar year shall not be altered or exceeded except as by law provided.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1201-S.SL.pdf?cite=1991%20c%20363%20§%2088[1991 c 363 § 88]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c182.pdf?cite=1969%20ex.s.%20c%20182%20§%2014[1969 ex.s. c 182 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.82.160[1963 c 4 § 36.82.160]; 1949 c 156 § 6, part; 1943 c 82 § 7, part; 1937 c 187 § 56, part; Rem. Supp. 1949 § 6450-56, part; ]

== 36.82.170 - County road budget—Budget as adopted filed with department of transportation.
Upon the final adoption of the county road budgets of the several counties, the county legislative authorities shall file a copy thereof in the office of the department of transportation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%2036[1984 c 7 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.82.170[1963 c 4 § 36.82.170]; 1949 c 156 § 6, part; 1943 c 82 § 7, part; 1937 c 187 § 56, part; Rem. Supp. 1949 § 6450-56, part; ]

== 36.82.180 - County road budget—Preliminary supplemental budget.
If any funds are paid to any county from the motor vehicle fund in excess of the amount estimated by the department of transportation and the excess funds have not been included by the county legislative authority in the then current county road budget or if funds become available from other sources upon a matching basis or otherwise and it is impracticable to adhere to the provisions of the county road budget, the legislative authority may by unanimous consent, consider and adopt a preliminary supplemental budget covering the excess funds for the remainder of the current fiscal year.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%2037[1984 c 7 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.82.180[1963 c 4 § 36.82.180]; 1949 c 156 § 6, part; 1943 c 82 § 7, part; 1937 c 187 § 56, part; Rem. Supp. 1949 § 6450-56, part; ]

== 36.82.190 - County road budget—Notice of hearing on supplemental budget.
The county legislative authority shall then publish a notice setting day of hearing for the adoption of the final supplemental budget covering the excess funds, designating the time and place of hearing and that anyone may appear thereat and be heard for or against any part of the preliminary supplemental budget. The notice shall be published once a week for two consecutive weeks immediately following the adoption of the preliminary supplemental budget in the official newspaper of the county. The county legislative authority shall provide a sufficient number of copies of the preliminary supplemental budget to meet reasonable public demands and they shall be available not later than two weeks immediately preceding the hearing.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c469.pdf?cite=1985%20c%20469%20§%2050[1985 c 469 § 50]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.82.190[1963 c 4 § 36.82.190]; 1949 c 156 § 6, part; 1943 c 82 § 7, part; 1937 c 187 § 56, part; Rem. Supp. 1949 § 6450-56, part; ]

== 36.82.200 - County road budget—Hearing, adoption, supplemental budget.
The board shall hold such hearing at the time and place designated in the notice, and it may be continued from day to day until concluded but not to exceed a total of five days. Upon the conclusion of the hearing the board shall fix and determine the supplemental budget and by resolution adopt it as finally determined and enter it in detail in the official minutes of the board, a copy of which supplemental budget shall be forwarded to the director.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1889.SL.pdf?cite=1995%20c%20301%20§%2070[1995 c 301 § 70]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.82.200[1963 c 4 § 36.82.200]; 1949 c 156 § 6, part; 1943 c 82 § 7, part; 1937 c 187 § 56, part; Rem. Supp. 1949 § 6450-56, part; ]

== 36.82.210 - Disposition of fines and forfeitures for violations.
All fines and forfeitures collected for violation of any of the provisions of chapters 36.75, and 36.77 to 36.87 RCW, inclusive, when the violation thereof occurred outside of any incorporated city or town shall be distributed and paid into the proper funds for the following purposes: One-half shall be paid into the county road fund of the county in which the violation occurred; one-fourth into the state fund for the support of state parks and parkways; and one-fourth into the highway safety fund: PROVIDED, That all fees, fines, forfeitures and penalties collected or assessed by a district court because of the violation of a state law shall be remitted as provided in chapter 3.62 RCW as now exists or is later amended.

All fines and forfeitures collected for the violation of any of such provisions when the violation thereof occurred inside any incorporated city or town shall be distributed and paid into the proper funds for the following purposes: One-half shall be paid into the city street fund of such incorporated city or town for the construction and maintenance of city streets; one-fourth into the state fund for the support of state parks and parkways; and one-fourth into the highway safety fund: PROVIDED, That all fees, fines, forfeitures and penalties collected or assessed by a district court because of the violation of a state law shall be remitted as provided in chapter 3.62 RCW as now exists or is later amended.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c202.pdf?cite=1987%20c%20202%20§%20211[1987 c 202 § 211]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c199.pdf?cite=1969%20ex.s.%20c%20199%20§%2021[1969 ex.s. c 199 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.82.210[1963 c 4 § 36.82.210]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c75.pdf?cite=1949%20c%2075%20§%202[1949 c 75 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c187.pdf?cite=1937%20c%20187%20§%2067[1937 c 187 § 67]; Rem. Supp. 1949 § 6450-67; ]

