= 36.38 - Admissions tax.
:toc:

== 36.38.010 - Taxes authorized—Exception as to schools.
. Any county may by ordinance enacted by its county legislative authority, levy and fix a tax of not more than one cent on twenty cents or fraction thereof to be paid for county purposes by persons who pay an admission charge to any place, including a tax on persons who are admitted free of charge or at reduced rates to any place for which other persons pay a charge or a regular higher charge for the same or similar privileges or accommodations; and require that one who receives any admission charge to any place must collect and remit the tax to the county treasurer of the county. However, no county may impose such tax on persons paying an admission to any activity of any elementary or secondary school or any public facility of a public facility district under chapter 35.57 or 36.100 RCW for which a tax is imposed under RCW 35.57.100 or 36.100.210.

. As used in this chapter, the term "admission charge" includes a charge made for season tickets or subscriptions, a cover charge, or a charge made for use of seats and tables, reserved or otherwise, and other similar accommodations; a charge made for food and refreshments in any place where any free entertainment, recreation, or amusement is provided; a charge made for rental or use of equipment or facilities for purpose of recreation or amusement, and where the rental of the equipment or facilities is necessary to the enjoyment of a privilege for which a general admission is charged, the combined charges must be considered as the admission charge. Admission charge also includes any automobile parking charge where the amount of such charge is determined according to the number of passengers in any automobile.

. Subject to subsections (4) and (5) of this section, the tax authorized in this section is not exclusive and does not prevent any city or town within the taxing county, when authorized by law, from imposing within its corporate limits a tax of the same or similar kind. However, whenever the same or similar kind of tax is imposed by any such city or town, no such tax may be levied within the corporate limits of such city or town by the county.

. Notwithstanding subsection (3) of this section, the legislative authority of a county with a population of one million or more may exclusively levy taxes on events in baseball stadiums constructed on or after January 1, 1995, that are owned by a public facilities district under chapter 36.100 RCW and that have seating capacities over forty thousand at the rates of:

.. Not more than one cent on twenty cents or fraction thereof, to be used for the purpose of paying the principal and interest payments on bonds issued by a county to construct a baseball stadium as defined in RCW 82.14.0485. If the revenue from the tax exceeds the amount needed for that purpose, the excess must be placed in a contingency fund which must be used exclusively by the public facilities district to fund repair, reequipping, and capital improvement of the baseball stadium; and

.. Not more than one cent on twenty cents or fraction thereof, to be used for the purpose of paying the principal and interest payments on bonds issued by a county to construct a baseball stadium as defined in RCW 82.14.0485. The tax imposed under this subsection (4)(b) expires when the bonds issued for the construction of the baseball stadium are retired, but not later than twenty years after the tax is first collected.

. [Empty]
.. Notwithstanding subsection (3) of this section, the legislative authority of a county that has created a public stadium authority to develop a stadium and exhibition center under RCW 36.102.050 may levy and fix a tax on charges for admission to events in a stadium and exhibition center, as defined in RCW 36.102.010, constructed in the county on or after January 1, 1998, that is owned by a public stadium authority under chapter 36.102 RCW.

.. Except as provided otherwise in (c) of this subsection (5), the tax is exclusive and precludes the city or town within which the stadium and exhibition center is located from imposing a tax of the same or similar kind on charges for admission to events in the stadium and exhibition center, and precludes the imposition of a general county admissions tax on charges for admission to events in the stadium and exhibition center.

.. A city within which the stadium and exhibition center is located has the exclusive right to impose an admissions tax under the authority of RCW 35.21.280 and the county is precluded from imposing an admissions tax, for a sporting event conducted during calendar year 2012 by a state college or university, if such sporting event occurs:

... Due to the temporary closure of any similar facility owned by that college or university; and

... At a facility owned by a public stadium authority located within a city with a population that exceeds five hundred thousand people.

.. For the purposes of this subsection (5), "charges for admission to events" means only the actual admission charge, exclusive of taxes and service charges and the value of any other benefit conferred by the admission.

.. The tax authorized under this subsection (5) is at the rate of not more than one cent on ten cents or fraction thereof.

.. Revenues collected under this subsection (5) must be deposited in the stadium and exhibition center account under RCW 43.99N.060 until the bonds issued under RCW 43.99N.020 for the construction of the stadium and exhibition center are retired. After the bonds issued for the construction of the stadium and exhibition center are retired, the tax authorized under this section is used exclusively to fund repair, reequipping, and capital improvement of the stadium and exhibition center.

.. The tax under this subsection (5) may be levied upon the first use of any part of the stadium and exhibition center but may not be collected at any facility already in operation as of July 17, 1997.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6574-S.SL.pdf?cite=2012%20c%20260%20§%201[2012 c 260 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5834-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2038%20§%202[2011 1st sp.s. c 38 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5452-S2.SL.pdf?cite=1999%20c%20165%20§%2020[1999 c 165 § 20]; 1997 c 220 § 301 (Referendum Bill No. 48, approved June 17, 1997); http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2115.SL.pdf?cite=1995%203rd%20sp.s.%20c%201%20§%20203[1995 3rd sp.s. c 1 § 203]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6049-S.SL.pdf?cite=1995%201st%20sp.s.%20c%2014%20§%209[1995 1st sp.s. c 14 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.38.010[1963 c 4 § 36.38.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c126.pdf?cite=1957%20c%20126%20§%202[1957 c 126 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c34.pdf?cite=1951%20c%2034%20§%201[1951 c 34 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c269.pdf?cite=1943%20c%20269%20§%201[1943 c 269 § 1]; Rem. Supp. 1943 § 11241-10; ]

== 36.38.020 - Optional provisions in ordinance.
In addition to the provisions levying and fixing the amount of tax, the ordinance may contain any or all of the following provisions:

. A provision defining the words and terms used therein;

. A provision requiring the price (exclusive of the tax to be paid by the person paying for admission) at which every admission ticket or card is sold to be conspicuously and indelibly printed or written on the face or back of that part of the ticket which is to be taken up by the management of the place for which an admission charge is exacted, and making the violation of such provision a misdemeanor punishable by fine of not exceeding one hundred dollars;

. Provisions fixing reasonable exemptions from such tax;

. Provisions allowing as an offset against the tax, the amount of like taxes levied, fixed, and collected within their jurisdiction by incorporated cities and towns in the county;

. A provision requiring persons receiving payments for admissions taxed under said ordinance to collect the amount of the tax from the persons making such payments;

. A provision to the effect that the tax imposed by said ordinance shall be deemed to be held in trust by the person required to collect the same until paid to the county treasurer, and making it a misdemeanor for any person receiving payment of the tax and appropriating or converting the same to his or her own use or to any use other than the payment of the tax as provided in said ordinance to the extent that the amount of such tax is not available for payment on the due date for filing returns as provided in said ordinance;

. A provision that in case any person required by the ordinance to collect the tax imposed thereby fails to collect the same, or having collected the tax fails to pay the same to the county treasurer in the manner prescribed by the ordinance, whether such failure is the result of such person's own acts or the result of acts or conditions beyond such person's control, such person shall nevertheless be personally liable to the county for the amount of the tax;

. Provisions fixing the time when the taxes imposed by the ordinance shall be due and payable to the county treasurer; requiring persons receiving payments for admissions to make periodic returns to the county treasurer on such forms and setting forth such information as the county treasurer may specify; requiring such return to show the amount of tax upon admissions for which such person is liable for specified preceding periods, and requiring such person to sign and transmit the same to the county treasurer together with a remittance for the amount;

. A provision requiring taxpayers to file with the county treasurer verified annual returns setting forth such additional information as he or she may deem necessary to determine tax liability correctly;

. A provision to the effect that whenever a certificate of registration, if required by the ordinance, is obtained for operating or conducting temporary places of amusement by persons who are not the owners, lessees, or custodians of the building, lot or place where the amusement is to be conducted, or whenever the business is permitted to be conducted without the procurement of a certificate, the tax imposed shall be returned and paid as provided in the ordinance by such owner, lessee, or custodian, unless paid by the person conducting the place of amusement;

. A provision requiring the applicant for a temporary certificate of registration, if required by the ordinance, to furnish with the application therefor, the name and address of the owner, lessee, or custodian of the premises upon which the amusement is to be conducted, and requiring the county treasurer to notify such owner, lessee, or custodian of the issuance of any such temporary certificate, and of the joint liability for such tax;

. A provision empowering the county treasurer to declare the tax upon temporary or itinerant places of amusement to be immediately due and payable and to collect the same, when he or she believes there is a possibility that the tax imposed under the ordinance will not be otherwise paid;

. Any or all of the applicable general administrative provisions contained in RCW 82.32.010 through 82.32.340 and 82.32.380, and the amendments thereto, except that unless otherwise indicated by the context of said sections, in all provisions so incorporated in such ordinance (a) the term "county treasurer" (of the county enacting said ordinance) shall be substituted for each reference made in said sections to the "department," the "department of revenue," "any employee of the department," or "director of the department of revenue"; (b) the name of the county enacting such ordinance shall be substituted for each reference made in said sections to the "state" or to the "state of Washington"; (c) the term "this ordinance" shall be substituted for each reference made in said sections to "this chapter"; (d) the name of the county enacting said ordinance shall be substituted for each reference made in said sections to "Thurston county"; and (e) the term "board of county commissioners" shall be substituted for each reference made in said sections to the "director of financial management."

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204080[2009 c 549 § 4080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c151.pdf?cite=1979%20c%20151%20§%2038[1979 c 151 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%2021[1975 1st ex.s. c 278 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.38.020[1963 c 4 § 36.38.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c269.pdf?cite=1943%20c%20269%20§%203[1943 c 269 § 3]; Rem. Supp. 1943 § 11241-12; ]

== 36.38.030 - Form of ordinance.
The ordinance levying and fixing the tax shall be headed by a title expressing the subject thereof, and the style of the ordinance shall be: "Be it ordained by the Board of County Commissioners of . . . . . . County, State of Washington." The ordinance shall be enacted by a majority vote of the board at a regular meeting thereof, and only after the form of such ordinance as ultimately enacted has been on file with the clerk of the board and open to public inspection for not less than ten days. The ordinance shall not become effective until thirty days following its enactment, and within five days following its enactment it shall be printed and published in a newspaper of general circulation in the county. The ordinance shall be signed by a majority of the board, attested by the clerk of the board, and shall be duly entered and recorded in the book wherein orders of the board are entered and recorded. The ordinance may be at any time amended or repealed by an ordinance enacted, published, and recorded in the same manner.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.38.030[1963 c 4 § 36.38.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c269.pdf?cite=1943%20c%20269%20§%202[1943 c 269 § 2]; Rem. Supp. 1943 § 11241-11; ]

== 36.38.040 - Vehicle parking charges tax—Parking facility at stadium and exhibition center—Use of revenues before and after issuance of bonds.
The legislative authority of a county that has created a public stadium authority to develop a stadium and exhibition center under RCW 36.102.050 may levy and fix a tax on any vehicle parking charges imposed at any parking facility that is part of a stadium and exhibition center, as defined in RCW 36.102.010. The tax shall be exclusive and shall preclude the city or town within which the stadium and exhibition center is located from imposing within its corporate limits a tax of the same or similar kind on any vehicle parking charges imposed at any parking facility that is part of a stadium and exhibition center. For the purposes of this section, "vehicle parking charges" means only the actual parking charges exclusive of taxes and service charges and the value of any other benefit conferred. The tax authorized under this section shall be at the rate of not more than ten percent. Revenues collected under this section shall be deposited in the stadium and exhibition center account under RCW 43.99N.060 until the bonds issued under RCW 43.99N.020 for the construction of the stadium and exhibition center are retired. After the bonds issued for the construction of the stadium and exhibition center are retired, the tax authorized under this section shall be used exclusively to fund repair, reequipping, and capital improvement of the stadium and exhibition center. The tax under this section may be levied upon the first use of any part of the stadium and exhibition center but shall not be collected at any facility already in operation as of July 17, 1997.

[ 1997 c 220 § 302 (Referendum Bill No. 48, approved June 17, 1997); ]

