= 36.74 - Transportation benefit districts—Assumption by cities and counties.
:toc:

== 36.74.010 - Assumption of rights, powers, functions, and obligations authorized.
Any city or county in which a transportation benefit district has been established pursuant to chapter 36.73 RCW with boundaries coterminous with the boundaries of the city or county may by ordinance or resolution of the city or county legislative authority assume the rights, powers, functions, and obligations of the transportation benefit district in accordance with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5987-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2044%20§%20301[2015 3rd sp.s. c 44 § 301]; ]

== 36.74.020 - Ordinance or resolution of intention to assume rights, powers, functions, and obligations—Adoption—Publication—Hearing.
. The assumption of the rights, powers, functions, and obligations of a transportation benefit district may be initiated by the adoption of an ordinance or a resolution by the city or county legislative authority indicating its intention to conduct a hearing concerning the assumption of such rights, powers, functions, and obligations. If the city or county legislative authority adopts such an ordinance or a resolution of intention, the ordinance or resolution must set a time and place at which the city or county legislative authority will consider the proposed assumption of the rights, powers, functions, and obligations of the transportation benefit district, and must state that all persons interested may appear and be heard. The ordinance or resolution of intention must be published at least two times during the two weeks preceding the scheduled hearing in newspapers of daily general circulation printed or published in the city or county in which the transportation benefit district is to be located.

. At the time scheduled for the hearing in the ordinance or resolution of intention, the city or county legislative authority must consider the assumption of the rights, powers, functions, and obligations of the transportation benefit district and hear those appearing and all protests and objections to it. The city or county legislative authority may continue the hearing from time to time, not exceeding sixty days in all.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5987-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2044%20§%20302[2015 3rd sp.s. c 44 § 302]; ]

== 36.74.030 - Declaration of intention to assume—Abolition of city or county governing body—Transfer of rights, powers, immunities, functions, and obligations to city or county.
. If, after receiving testimony, the city or county legislative authority determines that the public interest or welfare would be satisfied by the city or county assuming the rights, powers, immunities, functions, and obligations of the transportation benefit district, the city or county legislative authority may declare that to be its intent and assume such rights, powers, immunities, functions, and obligations by ordinance or resolution, providing that the city or county is vested with every right, power, immunity, function, and obligation currently granted to or possessed by the transportation benefit district.

. Upon assumption of the rights, powers, immunities, functions, and obligations of the transportation benefit district by the city or county, the governing body established pursuant to RCW 36.73.020 must be abolished and the city or county legislative authority is vested with all rights, powers, immunities, functions, and obligations otherwise vested by law in the governing board of the transportation benefit district.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5987-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2044%20§%20303[2015 3rd sp.s. c 44 § 303]; ]

== 36.74.040 - Existing rights, actions, proceedings, etc., not impaired or altered.
No transfer of any function made pursuant to this chapter may be construed to impair or alter any existing rights acquired under chapter 36.73 RCW or any other provision of law relating to transportation benefit districts, nor as impairing or altering any actions, activities, or proceedings validated thereunder, nor as impairing or altering any civil or criminal proceedings instituted thereunder, nor any rule, regulation, or order promulgated thereunder, nor any administrative action taken thereunder; and neither the assumption of control of any transportation benefit district function by a city or county, nor any transfer of rights, powers, functions, and obligations as provided in this chapter, may impair or alter the validity of any act performed by such transportation benefit district or division thereof or any officer thereof prior to the assumption of such rights, powers, functions, and obligations by any city or county as authorized under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5987-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2044%20§%20304[2015 3rd sp.s. c 44 § 304]; ]

== 36.74.050 - Rules and regulations, pending business, contracts, obligations, validity of official acts.
. All rules and regulations and all pending business before the board of any transportation benefit district transferred pursuant to this chapter must be continued and acted upon by the city or county.

. All existing contracts and obligations of the transferred transportation benefit district remain in full force and effect and must be performed by the city or county. A transfer authorized in this chapter does not affect the validity of any official act performed by any official or employee prior to the transfer authorized pursuant to this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5987-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2044%20§%20305[2015 3rd sp.s. c 44 § 305]; ]

== 36.74.060 - Reports, books, records, etc.—Funds, credits, assets—Appropriations or federal grants.
. All reports, documents, surveys, books, records, files, papers, or other writings relating to the administration of the powers, duties, and functions transferred pursuant to this chapter and available to the transportation benefit district must be made available to the city or county.

. All funds, credits, or other assets held in connection with powers, duties, and functions transferred under this chapter must be assigned to the city or county.

. Any appropriations or federal grant made to the transportation benefit district for the purpose of carrying out the rights, powers, functions, and obligations authorized to be assumed by a city or county pursuant to this chapter, on the effective date of such transfer, must be credited to the city or county for the purpose of carrying out such transferred rights, powers, functions, and obligations.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5987-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2044%20§%20306[2015 3rd sp.s. c 44 § 306]; ]

== 36.74.070 - Debts and obligations.
The city or county must assume and agree to provide for the payment of all of the indebtedness of the transportation benefit district, including the payment and retirement of outstanding general obligation and revenue bonds issued by the transportation benefit district.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5987-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2044%20§%20307[2015 3rd sp.s. c 44 § 307]; ]

