= 36.09 - New county—Liability for debts.
:toc:

== 36.09.010 - Debts and property to be apportioned.
Whenever a new county shall be or shall have been organized out of the territory which was included within the limits of any other county or counties, the new county shall be liable for a reasonable proportion of the debts of the county from which it was taken, and entitled to its proportion of the property of the county.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.09.010[1963 c 4 § 36.09.010]; Code 1881 § 2657; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20538%20§%203[1863 p 538 § 3]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20330%20§%201[1854 p 330 § 1]; RRS § 3986; ]

== 36.09.020 - Procedure to settle amount charged new county—Basis of apportionment.
The auditor of the old county shall give the auditor of the new county reasonable notice to meet him or her on a certain day at the county seat of the old county, or at some other convenient place, to settle upon and fix the amount which the new county shall pay. In doing so, they shall not charge either county with any share of debts arising from the erection of public buildings, or out of the construction of roads or bridges which shall be and remain, after the division, within the limits of the other county, and of the other debts they shall apportion to each county such a share of the indebtedness as may be just and equitable, taking into consideration the population of such portion of territory so forming a part of the said counties while so united, and also the relative advantages, derived from the old county organization.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204004[2009 c 549 § 4004]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.09.020[1963 c 4 § 36.09.020]; Code 1881 § 2658; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20538%20§%204[1863 p 538 § 4]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20330%20§%202[1854 p 330 § 2]; RRS § 3987. FORMER PART OF SECTION: 1909 c 79 § 1, part; Code 1881 § 2662, part; RRS § 3991, part. Now codified in RCW  36.09.050; ]

== 36.09.035 - Procedure to settle amount charged new county—Disagreement between auditors—Determination by third person.
In case the two auditors cannot agree, they shall call a third person, not a citizen of either county, or in any other manner interested, whose decision shall be binding. In case they cannot agree upon such third person, they shall each name one and decide by lot which it shall be.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.09.035[1963 c 4 § 36.09.035]; Code 1881 § 2659; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20539%20§%205[1863 p 539 § 5]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20330%20§%203[1854 p 330 § 3]; RRS § 3988; ]

== 36.09.040 - Payment of indebtedness—Transfer of property.
The auditor of the county indebted upon such decision shall give to the auditor of the other county his or her order upon the treasurer for the amount to be paid out of the proper fund, as in other cases, and also make out a transfer of such property as shall be assigned to either county.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%204005[2009 c 549 § 4005]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.09.040[1963 c 4 § 36.09.040]; Code 1881 § 2660; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20539%20§%206[1863 p 539 § 6]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20330%20§%204[1854 p 330 § 4]; RRS § 3989; ]

== 36.09.050 - Collection of taxes levied—Apportionment.
When a county is divided or the boundary is altered, all taxes levied before the division was made or boundaries changed, must be collected by the officers of the county in which the territory was situated before the division or change. And the auditor or auditors of the county or counties so divided or having boundaries changed, shall apportion the amount of the real property taxes so collected after division or change of boundary to the old county or counties and the new county or counties, in the ratio of the assessed value of such property situated in the territory of each county or counties respectively, and the old county that may have been divided or whose boundaries may have been changed, shall retain all of the personal property taxes on the said tax rolls, as compensation for cost of collection of the entire taxes: PROVIDED, That in such accounting neither county shall be charged with any debt or liability then existing incurred in the purchase of any county property, or in the purchase or construction of any county buildings then in use or under construction, which shall fall within and be retained by the county: PROVIDED FURTHER, That this shall not be construed to affect the rights of creditors: AND PROVIDED FURTHER, That any such county property or buildings shall be the property of and owned by the county wherein the same is situated. In case the auditors of the interested counties are not able to agree upon the proportion to be awarded to each county, the same shall be determined by the judge of the superior court of the district in which all of the interested counties are situated, if they be in one district, and have one common judge, and if not, by the judges sitting en banc of the superior courts of the counties involved. Said auditors shall make said apportionment within sixty days after the creation of any new county or the changing of boundaries of any old county, and if they do not, within said time, agree upon said apportionment, thereafter either or any county affected may petition the judge or judges of any court given jurisdiction by this section, and upon ten days' notice to any other county affected, the same may be brought on for hearing and summarily disposed of by said judge or judges, after allowing each side an opportunity to be heard.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.09.050[1963 c 4 § 36.09.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c79.pdf?cite=1909%20c%2079%20§%201[1909 c 79 § 1]; Code 1881 § 2662; RRS § 3991; ]

