= 36.01 - General provisions.
:toc:

== 36.01.010 - Corporate powers.
The several counties in this state shall have capacity as bodies corporate, to sue and be sued in the manner prescribed by law; to purchase and hold lands; to make such contracts, and to purchase and hold such personal property, as may be necessary to their corporate or administrative powers, and to do all other necessary acts in relation to all the property of the county.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c278.pdf?cite=1986%20c%20278%20§%201[1986 c 278 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.01.010[1963 c 4 § 36.01.010]; Code 1881 § 2653; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20538%20§%201[1863 p 538 § 1]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20329%20§%201[1854 p 329 § 1]; RRS § 3982; ]

== 36.01.020 - Corporate name.
The name of a county, designated by law, is its corporate name, and it must be known and designated thereby in all actions and proceedings touching its corporate rights, property, and duties.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.01.020[1963 c 4 § 36.01.020]; Code 1881 § 2654; RRS § 3983; ]

== 36.01.030 - Powers—How exercised.
Its powers can only be exercised by the county commissioners, or by agents or officers acting under their authority or authority of law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.01.030[1963 c 4 § 36.01.030]; Code 1881 § 2655; RRS § 3984; ]

== 36.01.040 - Conveyances for use of county.
Every conveyance of lands, or transfer of other property, made in any manner for the use of any county, shall have the same force and effect as if made to the county in its proper and corporate name.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.01.040[1963 c 4 § 36.01.040]; Code 1881 § 2656; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20538%20§%202[1863 p 538 § 2]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20329%20§%202[1854 p 329 § 2]; RRS § 3985; ]

== 36.01.050 - Venue of actions by or against counties.
. All actions against any county may be commenced in the superior court of such county, or in the superior court of either of the two nearest judicial districts. All actions by any county shall be commenced in the superior court of the county in which the defendant resides, or in either of the two judicial districts nearest to the county bringing the action.

. The determination of the nearest judicial districts is measured by the travel time between county seats using major surface routes, as determined by the administrative office of the courts.

. Any provision in a public works contract with any county that requires actions arising under the contract to be commenced in the superior court of the county is against public policy and the provision is void and unenforceable. This subsection shall not be construed to void any contract provision requiring a dispute arising under the contract to be submitted to arbitration.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1601.SL.pdf?cite=2015%20c%20138%20§%201[2015 c 138 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1668.SL.pdf?cite=2005%20c%20282%20§%2042[2005 c 282 § 42]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2721-S.SL.pdf?cite=2000%20c%20244%20§%201[2000 c 244 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5831.SL.pdf?cite=1997%20c%20401%20§%201[1997 c 401 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.01.050[1963 c 4 § 36.01.050]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20329%20§%206[1854 p 329 § 6]; No RRS; ]

== 36.01.060 - County liable for certain court costs.
Each county shall be liable to pay the per diem and mileage, or other compensation in lieu thereof, to jurors of the county attending the superior court; the fees of the sheriff for maintaining prisoners charged with crimes, and the sheriff's costs in conveying them to and from the court, as well as their board while there; the per diem and mileage, or such other compensation as is allowed in lieu thereof, of the sheriff of the county, when in criminal cases the sheriff is required to attend or travel to the superior court out of the limits of the sheriff's county; the costs in criminal cases taken from the courts of limited jurisdiction to the superior court; but no such claims shall be paid by the treasurer unless the particular items are approved by the judge and certified by the clerk under the seal of the court. For the time or travel which may be paid by the parties or United States, no payment from the county shall be allowed, and no officer, juror, or witness shall receive from the county double pay as a per diem for the same time, or as traveling expenses or mileage for the same travel, in however many different capacities or in however many different causes they may be summoned, notified, or called upon to testify or attend in.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c202.pdf?cite=1987%20c%20202%20§%20200[1987 c 202 § 200]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c4.pdf?cite=1963%20c%204%20§%2036.01.060[1963 c 4 § 36.01.060]; Code 1881 § 2110; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1869%20p%20420%20§%209[1869 p 420 § 9]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20425%20§%2010[1863 p 425 § 10]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1857%20p%2022%20§%2010[1857 p 22 § 10]; RRS § 508; ]

== 36.01.070 - Probation and parole services.
Notwithstanding the provisions of chapter 72.01 RCW or any other provision of law, counties may engage in probation and parole services and employ personnel therefor under such terms and conditions as any such county shall so determine. If a county elects to assume responsibility for the supervision of superior court misdemeanant offenders placed on probation under RCW 9.92.060 or 9.95.210, the county may contract with other counties to receive or provide such probation services. A county may also enter into partnership agreements with the department of corrections under RCW 72.09.300.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2533-S.SL.pdf?cite=1996%20c%20298%20§%207[1996 c 298 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c200.pdf?cite=1967%20c%20200%20§%209[1967 c 200 § 9]; ]

== 36.01.080 - Parking facilities—Construction, operation and rental charges.
Counties may construct, maintain, operate and collect rentals for parking facilities as a part of a courthouse or combined county-city building facility.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c8.pdf?cite=1969%20ex.s.%20c%208%20§%201[1969 ex.s. c 8 § 1]; ]

== 36.01.085 - Economic development programs.
It shall be in the public purpose for all counties to engage in economic development programs. In addition, counties may contract with nonprofit corporations in furtherance of this and other acts relating to economic development.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c92.pdf?cite=1985%20c%2092%20§%202[1985 c 92 § 2]; ]

== 36.01.090 - Tourist promotion.
See RCW 36.32.450.

[ ]

== 36.01.095 - Emergency medical services—Authorized—Fees.
Any county may establish a system of emergency medical service as defined by *RCW 18.73.030(11). The county legislative authority may adopt by resolution procedures to collect reasonable fees in order to reimburse the county in whole or in part for its costs of providing such service: PROVIDED, That any county which provides emergency medical services supported by an excess levy may waive such charges for service: PROVIDED FURTHER, That whenever the county legislative authority determines that the county or a substantial portion of the county is not adequately served by existing private ambulance service, and existing private ambulance service cannot be encouraged to expand service on a contract basis, the emergency medical service that is established by the county shall not be deemed to compete with any existing private ambulance service as provided for in RCW 36.01.100.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c147.pdf?cite=1975%201st%20ex.s.%20c%20147%20§%201[1975 1st ex.s. c 147 § 1]; ]

== 36.01.100 - Ambulance service authorized—Restriction.
The legislative authority of any county may by appropriate legislation provide for the establishment of a system of ambulance service for the entire county or for portions thereof, and award contracts for ambulance service: PROVIDED, That such legislation may not provide for the establishment of any system which would compete with any existing private system.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c89.pdf?cite=1972%20ex.s.%20c%2089%20§%201[1972 ex.s. c 89 § 1]; ]

== 36.01.104 - Levy for emergency medical care and services.
See RCW 84.52.069.

[ ]

== 36.01.105 - Fire protection, ambulance or other emergency services provided by municipal corporation within county—Financial and other assistance authorized.
See RCW 36.32.470.

[ ]

== 36.01.110 - Federal grants and programs—Powers and authority of counties to participate in—Public corporations, commissions or authorities.
See RCW 35.21.730 through 35.21.755.

[ ]

== 36.01.115 - Nonpolluting power generation by individual—Exemption from regulation—Authorization to contract with utility.
See chapter 80.58 RCW.

[ ]

== 36.01.120 - Foreign trade zones—Legislative finding, intent.
It is the finding of the legislature that foreign trade zones serve an important public purpose by the creation of employment opportunities within the state and that the establishment of zones designed to accomplish this purpose is to be encouraged. It is the further intent of the legislature that the *department of community, trade, and economic development provide assistance to entities planning to apply to the United States for permission to establish such zones.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%2040[1995 c 399 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c466.pdf?cite=1985%20c%20466%20§%2044[1985 c 466 § 44]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c196.pdf?cite=1977%20ex.s.%20c%20196%20§%205[1977 ex.s. c 196 § 5]; ]

== 36.01.125 - Foreign trade zones—Authority to apply for permission to establish, operate and maintain.
A county, as zone sponsor, may apply to the United States for permission to establish, operate, and maintain foreign trade zones: PROVIDED, That nothing herein shall be construed to prevent these zones from being operated and financed by a private corporation(s) on behalf of such county acting as zone sponsor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c196.pdf?cite=1977%20ex.s.%20c%20196%20§%206[1977 ex.s. c 196 § 6]; ]

== 36.01.130 - Controls on rent for residential structures—Prohibited—Exceptions.
The imposition of controls on rent is of statewide significance and is preempted by the state. No county may enact, maintain or enforce ordinances or other provisions which regulate the amount of rent to be charged for single-family or multiple-unit residential rental structures or sites other than properties in public ownership, under public management, or properties providing low-income rental housing under joint public-private agreements for the financing or provision of such low-income rental housing. This section shall not be construed as prohibiting any county from entering into agreements with private persons which regulate or control the amount of rent to be charged for rental properties.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1201-S.SL.pdf?cite=1991%20c%20363%20§%2043[1991 c 363 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c75.pdf?cite=1981%20c%2075%20§%202[1981 c 75 § 2]; ]

== 36.01.150 - Facilitating recovery from Mt. St. Helens eruption—Scope of local government action.
All entities of local government and agencies thereof are authorized to take action as follows to facilitate recovery from the devastation of the eruption of Mt. St. Helens:

. Cooperate with the state, state agencies, and the United States Army Corps of Engineers and other agencies of the federal government in planning dredge site selection and dredge spoils removal;

. Counties and cities may re-zone areas and sites as necessary to facilitate recovery operations;

. Counties may manage and maintain lands involved and the deposited dredge spoils; and

. Local governments may assist the Army Corps of Engineers in the dredging and dredge spoils deposit operations.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c7.pdf?cite=1982%20c%207%20§%203[1982 c 7 § 3]; ]

== 36.01.160 - Penalty for act constituting a crime under state law—Limitation.
Except as limited by the maximum penalty authorized by law, no county may establish a penalty for an act that constitutes a crime under state law that is different from the penalty prescribed for that crime by state statute.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1544-S.SL.pdf?cite=1993%20c%2083%20§%202[1993 c 83 § 2]; ]

== 36.01.170 - Administration of trusts benefiting school districts.
Any county authorized by territorial law to administer moneys held in trust for the benefit of school districts within the county, which moneys were bequeathed for such purposes by testamentary provision, may dissolve any trust, the corpus of which does not exceed fifty thousand dollars, and distribute any moneys remaining in the trust to school districts within the county. Before dissolving the trust, the county must adopt a resolution finding that conditions have changed and it is no longer feasible for the county to administer the trust.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2302.SL.pdf?cite=1998%20c%2065%20§%201[1998 c 65 § 1]; ]

== 36.01.180 - Zoo and aquarium advisory authority—Constitution—Terms.
. For any county in which a proposition authorized by RCW 82.14.400 has been passed, there shall be created a zoo and aquarium advisory authority.

. The initial board of the authority shall be constituted as follows:

.. Three members appointed by the county legislative authority to represent unincorporated areas;

.. Two members appointed by the legislative authority of the city with the largest population within the county; and

.. Two members jointly appointed by the legislative authorities of the remaining cities within the county representing at least sixty percent of the combined populations of those cities.

. Board members shall hold office for whatever terms are determined by their appointing authorities, except that no term may be less than one year nor more than three years, in duration. However, a vacancy may be filled by an appointment for a term less than twelve months in duration.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1547-S.SL.pdf?cite=1999%20c%20104%20§%204[1999 c 104 § 4]; ]

== 36.01.190 - Initial meeting of zoo and aquarium advisory authority—Expenditure of funds—Powers.
. Upon certification by the county auditor or, in the case of a home rule county, upon certification by the chief elections officer, that a proposition authorized under the terms of RCW 82.14.400 has received a majority of votes cast on the proposition, the county legislative authority shall convene an initial meeting of the zoo and aquarium advisory authority.

. Consistent with any agreement between the local governments specified in RCW 82.14.400(1) in requesting an election, the zoo and aquarium advisory authority has authority to expend such funds as it may receive on those purposes set out in RCW 82.14.400(4). In addition, and consistent with any limitation placed on the powers of the authority in such an agreement, the zoo and aquarium advisory authority may exercise the following powers:

.. Acquire by purchase, gift, or grant and lease, construct, add to, improve, replace, repair, maintain, operate, and regulate the use of any zoo, aquarium, and wildlife preservation and display facilities and properties, together with all lands, rights-of-way, property, equipment, and accessories necessary for those facilities;

.. Contract with the United States or any agency thereof, any state or agency thereof, any metropolitan municipal corporation, any other county, city, special district, or governmental agency, and any private person, firm, or corporation for the purpose of receiving gifts or grants or securing loans or advances for preliminary planning and feasibility studies, or for the design, construction, operation, or maintenance of zoo, aquarium, and wildlife preservation and display facilities;

.. Contract with any governmental agency or with a private person, firm, or corporation for the use by either contracting party of all or any part of the facilities, structures, lands, interests in lands, air rights over lands, and rights-of-way of all kinds which are owned, leased, or held by the other party, and for the purpose of planning, constructing, or operating any facility or performing any service related to zoos, aquariums, and wildlife preservation and display facilities;

.. Fix rates and charges for the use of those facilities;

.. Sue and be sued in its corporate capacity in all courts and in all proceedings.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1547-S.SL.pdf?cite=1999%20c%20104%20§%203[1999 c 104 § 3]; ]

== 36.01.200 - Federal funds designated for state schools—Use limited to reduction of outstanding debt obligations of school districts.
The county legislative authority of any county that receives payment in lieu of taxes and payment equal to tax funds from the United States department of energy under section 168 of the federal atomic energy act of 1954 and nuclear waste policy act of 1982 and that has an agreed settlement or a joint stipulation dated before January 1, 1998, which agreed settlement or joint stipulation includes funds designated for state schools, may direct the county treasurer to distribute those designated funds to reduce the outstanding debt of the school districts within the county. Any such funds shall be divided among the school districts based upon the same percentages that each district's current assessed valuation is of the total assessed value for all eligible school districts if the district has outstanding debt that equals or exceeds the amount of its distribution. If the district does not have outstanding debt that equals or exceeds the amount of its distribution, any amount above the outstanding debt shall be reallocated to the remaining eligible districts. Any funds received before January 1, 1999, shall be distributed using the percentages calculated for 1998. The county treasurer shall apply the funds to any outstanding debt obligation selected by the respective school districts.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5567.SL.pdf?cite=1999%20c%2019%20§%201[1999 c 19 § 1]; ]

== 36.01.210 - Rail fixed guideway public transportation system—Safety program plan and security and emergency preparedness plan.
. Each county functioning under chapter 36.56 RCW that owns or operates a rail fixed guideway public transportation system as defined in RCW 81.104.015 shall submit a system safety program plan and a system security and emergency preparedness plan for that guideway to the state department of transportation by September 1, 1999, or at least one hundred eighty calendar days before beginning operations or instituting significant revisions to its plans. These plans must describe the county's procedures for (a) reporting and investigating any reportable incident, accident, or security breach and identifying and resolving hazards or security vulnerabilities discovered during planning, design, construction, testing, or operations, (b) developing and submitting corrective action plans and annual safety and security audit reports, (c) facilitating on-site safety and security reviews by the state department of transportation and the federal transit administration, and (d) addressing passenger and employee safety and security. The plans must, at a minimum, conform to the standards adopted by the state department of transportation as set forth in the most current version of the Washington state rail safety oversight program standard manual as it exists on March 25, 2016, or such subsequent date as may be provided by the department by rule, consistent with the purposes of this section. If required by the department, the county shall revise its plans to incorporate the department's review comments within sixty days after their receipt, and resubmit its revised plans for review.

. Each county functioning under chapter 36.56 RCW shall implement and comply with its system safety program plan and system security and emergency preparedness plan. The county shall perform internal safety and security audits to evaluate its compliance with the plans, and submit its audit schedule to the department of transportation pursuant to the requirements in the most current version of the Washington state rail safety oversight program standard manual as it exists on March 25, 2016, or such subsequent date as may be provided by the department by rule, consistent with the purposes of this section. The county shall prepare an annual report for its internal safety and security audits undertaken in the prior year and submit it to the department no later than February 15th. The department shall establish the requirements for the annual report. The contents of the annual report must include, at a minimum, the dates the audits were conducted, the scope of the audit activity, the audit findings and recommendations, the status of any corrective actions taken as a result of the audit activity, and the results of each audit in terms of the adequacy and effectiveness of the plans.

. Each county shall notify the department of transportation, pursuant to the most current version of the Washington state rail safety oversight program standard manual as it exists on March 25, 2016, or such subsequent date as may be provided by the department by rule, consistent with the purposes of this section, any reportable incident, accident, security breach, hazard, or security vulnerability. The department may adopt rules further defining any reportable incident, accident, security breach, hazard, or security vulnerability. The county shall investigate any reportable incident, accident, security breach, hazard, or security vulnerability and provide a written investigation report to the department as described in the most current version of the Washington state rail safety oversight program standard manual as it exists on March 25, 2016, or such subsequent date as may be provided by the department by rule, consistent with the purposes of this section.

. The system security and emergency preparedness plan required in subsection (1) of this section is exempt from public disclosure under chapter 42.56 RCW. However, the system safety program plan as described in this section is not subject to this exemption.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6358-S.SL.pdf?cite=2016%20c%2033%20§%204[2016 c 33 § 4]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5084.SL.pdf?cite=2007%20c%20422%20§%203[2007 c 422 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20268[2005 c 274 § 268]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1324-S.SL.pdf?cite=1999%20c%20202%20§%203[1999 c 202 § 3]; ]

== 36.01.220 - Mobile home, manufactured home, or park model moving or installing—Copies of permits—Definitions.
. A county shall transmit a copy of any permit issued to a tenant or the tenant's agent for a mobile home, manufactured home, or park model installation in a mobile home park to the landlord.

. A county shall transmit a copy of any permit issued to a person engaged in the business of moving or installing a mobile home, manufactured home, or park model in a mobile home park to the tenant and the landlord.

. As used in this section:

.. "Landlord" has the same meaning as in RCW 59.20.030;

.. "Mobile home park" has the same meaning as in RCW 59.20.030;

.. "Mobile or manufactured home installation" has the same meaning as in *RCW 43.63B.010; and

.. "Tenant" has the same meaning as in RCW 59.20.030.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1378.SL.pdf?cite=1999%20c%20359%20§%2020[1999 c 359 § 20]; ]

== 36.01.225 - Authority to regulate placement or use of homes—Regulation of manufactured homes—Restrictions on location of manufactured/mobile homes and entry or removal of recreational vehicles used as primary residences.
. A county may not adopt an ordinance that has the effect, directly or indirectly, of discriminating against consumers' choices in the placement or use of a home in such a manner that is not equally applicable to all homes. Homes built to 42 U.S.C. Sec. 5401-5403 standards (as amended in 2000) must be regulated for the purposes of siting in the same manner as site built homes, factory built homes, or homes built to any other state construction or local design standard. However, except as provided in subsection (2) of this section, any county may require that:

.. A manufactured home be a new manufactured home;

.. The manufactured home be set upon a permanent foundation, as specified by the manufacturer, and that the space from the bottom of the home to the ground be enclosed by concrete or an approved concrete product which can be either load bearing or decorative;

.. The manufactured home comply with all local design standards applicable to all other homes within the neighborhood in which the manufactured home is to be located;

.. The home is thermally equivalent to the state energy code; and

.. The manufactured home otherwise meets all other requirements for a designated manufactured home as defined in RCW 35.63.160.

. [Empty]
.. A county may not adopt an ordinance that has the effect, directly or indirectly, of restricting the location of manufactured/mobile homes in manufactured/mobile home communities, as defined in RCW 59.20.030, which were legally in existence before June 12, 2008, based exclusively on the age or dimensions of the manufactured/mobile home.

.. A county may not prohibit the siting of a manufactured/mobile home on an existing lot based solely on lack of compliance with existing separation and setback requirements that regulate the distance between homes.

.. A county is not precluded by (a) or (b) of this subsection from restricting the location of a manufactured/mobile home in manufactured/mobile home communities for any other reason including, but not limited to, failure to comply with fire, safety, or other local ordinances or state laws related to manufactured/mobile homes.

. A county may not adopt an ordinance that has the effect, directly or indirectly, of preventing the entry or requiring the removal of a recreational vehicle used as a primary residence in manufactured/mobile home communities, as defined in RCW 59.20.030, unless the recreational vehicle fails to comply with the fire, safety, or other local ordinances or state laws related to recreational vehicles.

. This section does not override any legally recorded covenants or deed restrictions of record.

. This section does not affect the authority granted under chapter 43.22 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5183-S.SL.pdf?cite=2019%20c%20390%20§%2016[2019 c 390 § 16]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1227.SL.pdf?cite=2009%20c%2079%20§%203[2009 c 79 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5524-S.SL.pdf?cite=2008%20c%20117%20§%203[2008 c 117 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6593.SL.pdf?cite=2004%20c%20256%20§%204[2004 c 256 § 4]; ]

== 36.01.230 - Cooperative watershed management.
A county may, acting through the county legislative authority, participate in and expend revenue on cooperative watershed management actions, including watershed management partnerships under RCW 39.34.210 and other intergovernmental agreements, for purposes of water supply, water quality, and water resource and habitat protection and management.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5073.SL.pdf?cite=2003%20c%20327%20§%208[2003 c 327 § 8]; ]

== 36.01.240 - Regulation of financial transactions—Limitations.
A county or governmental entity subject to this title may not regulate the terms, conditions, or disclosures of any lawful financial transaction between a consumer and (1) a business or professional under the jurisdiction of the department of financial institutions, or (2) any financial institution as defined under *RCW 30.22.041.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5266-S.SL.pdf?cite=2005%20c%20338%20§%204[2005 c 338 § 4]; ]

== 36.01.250 - Environmental mitigation activities.
. Any county authorized to acquire and operate utilities or conduct other proprietary or user or ratepayer funded activities may develop and make publicly available a plan for the county to reduce its greenhouse gases emissions or achieve no-net emissions from all sources of greenhouse gases that such county utility or proprietary or user or ratepayer funded activity owns, operates, leases, uses, contracts for, or otherwise controls.

. Any county authorized to acquire and operate utilities or conduct other proprietary or user or ratepayer funded activities may, as part of such utility or activity, reduce or mitigate the environmental impacts, such as greenhouse gases emissions, of such utility and other proprietary or user or ratepayer funded activity. The mitigation may include, but is not limited to, all greenhouse gases mitigation mechanisms recognized by independent, qualified organizations with proven experience in emissions mitigation activities. Mitigation mechanisms may include the purchase, trade, and banking of carbon offsets or credits. Ratepayer funds, fees, or other revenue dedicated to a county utility or other proprietary or user or ratepayer funded activity may be spent to reduce or mitigate the environmental impacts of greenhouse gases emitted as a result of that function. If a state greenhouse gases registry is established, the county that has purchased, traded, or banked greenhouse gases mitigation mechanisms under this section shall receive credit in the registry.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1929-S.SL.pdf?cite=2007%20c%20349%20§%206[2007 c 349 § 6]; ]

== 36.01.260 - Evergreen community ordinances.
. Any county may adopt evergreen community ordinances, as that term is defined in RCW 35.105.010, which the county must apply to new building or land development in the unincorporated portions of the county's urban growth areas, as that term is defined in RCW 36.70A.030, and may apply to other areas of the county as deemed appropriate by the county.

. As an alternative to subsection (1) of this section, a city or town may request that the county in which it is located apply to any new building or land development permit in the unincorporated portions of the urban growth areas, as defined in RCW 36.70A.030, the evergreen community ordinances standards adopted under RCW 35.105.090 by the city or town in the county located closest to the proposed building or development.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2844-S2.SL.pdf?cite=2008%20c%20299%20§%2015[2008 c 299 § 15]; ]

== 36.01.270 - Contractors—Authority of county to verify registration and report violations.
A county that issues a business license to a person required to be registered under chapter 18.27 RCW may verify that the person is registered under chapter 18.27 RCW and report violations to the department of labor and industries.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1555-S.SL.pdf?cite=2009%20c%20432%20§%204[2009 c 432 § 4]; ]

== 36.01.280 - Community athletics programs—Sex discrimination prohibited.
The antidiscrimination provisions of RCW 49.60.500 apply to community athletics programs and facilities operated, conducted, or administered by a county.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5967-S.SL.pdf?cite=2009%20c%20467%20§%207[2009 c 467 § 7]; ]

== 36.01.290 - Hosting the homeless by religious organizations—When authorized—Requirements—Prohibitions on local actions.
. A religious organization may host the homeless on property owned or controlled by the religious organization whether within buildings located on the property or elsewhere on the property outside of buildings.

. Except as provided in subsection (7) of this section, a county may not enact an ordinance or regulation or take any other action that:

.. Imposes conditions other than those necessary to protect public health and safety and that do not substantially burden the decisions or actions of a religious organization regarding the location of housing or shelter, such as an outdoor encampment, indoor overnight shelter, temporary small house on-site, or vehicle resident safe parking, for homeless persons on property owned or controlled by the religious organization;

.. Requires a religious organization to obtain insurance pertaining to the liability of a municipality with respect to homeless persons housed on property owned by a religious organization or otherwise requires the religious organization to indemnify the municipality against such liability;

.. Imposes permit fees in excess of the actual costs associated with the review and approval of permit applications. A county has discretion to reduce or waive permit fees for a religious organization that is hosting the homeless;

.. Specifically limits a religious organization's availability to host an outdoor encampment on its property or property controlled by the religious organization to fewer than six months during any calendar year. However, a county may enact an ordinance or regulation that requires a separation of time of no more than three months between subsequent or established outdoor encampments at a particular site;

.. Specifically limits a religious organization's outdoor encampment hosting term to fewer than four consecutive months;

.. Limits the number of simultaneous religious organization outdoor encampment hostings within the same municipality during any given period of time. Simultaneous and adjacent hostings of outdoor encampments by religious organizations may be limited if located within one thousand feet of another outdoor encampment concurrently hosted by a religious organization;

.. Limits a religious organization's availability to host safe parking efforts at its on-site parking lot, including limitations on any other congregationally sponsored uses and the parking available to support such uses during the hosting, except for limitations that are in accord with the following criteria that would govern if enacted by local ordinance or memorandum of understanding between the host religious organization and the jurisdiction:

... No less than one space may be devoted to safe parking per ten on-site parking spaces;

... Restroom access must be provided either within the buildings on the property or through use of portable facilities, with the provision for proper disposal of waste if recreational vehicles are hosted; and

... Religious organizations providing spaces for safe parking must continue to abide by any existing on-site parking minimum requirement so that the provision of safe parking spaces does not reduce the total number of available parking spaces below the minimum number of spaces required by the county, but a county may enter into a memorandum of understanding with a religious organization that reduces the minimum number of on-site parking spaces required;

.. Limits a religious organization's availability to host an indoor overnight shelter in spaces with at least two accessible exits due to lack of sprinklers or other fire-related concerns, except that:

.. If a county fire official finds that fire-related concerns associated with an indoor overnight shelter pose an imminent danger to persons within the shelter, the county may take action to limit the religious organization's availability to host the indoor overnight shelter; and

... A county may require a host religious organization to enter into a memorandum of understanding for fire safety that includes local fire district inspections, an outline for appropriate emergency procedures, a determination of the most viable means to evacuate occupants from inside the host site with appropriate illuminated exit signage, panic bar exit doors, and a completed fire watch agreement indicating:

(A) Posted safe means of egress;

(B) Operable smoke detectors, carbon monoxide detectors as necessary, and fire extinguishers;

(C) A plan for monitors who spend the night awake and are familiar with emergency protocols, who have suitable communication devices, and who know how to contact the local fire department; or

... Limits a religious organization's ability to host temporary small houses on land owned or controlled by the religious organization, except for recommendations that are in accord with the following criteria:

... A renewable one-year duration agreed to by the host religious organization and local jurisdiction via a memorandum of understanding;

... Maintaining a maximum unit square footage of one hundred twenty square feet, with units set at least six feet apart;

... Electricity and heat, if provided, must be inspected by the local jurisdiction;

... Space heaters, if provided, must be approved by the local fire authority;

.. Doors and windows must be included and be lockable, with a recommendation that the managing agency and host religious organization also possess keys;

.. Each unit must have a fire extinguisher;

.. Adequate restrooms must be provided, including restrooms solely for families if present, along with handwashing and potable running water to be available if not provided within the individual units, including accommodating black water;

.. A recommendation for the host religious organization to partner with regional homeless service providers to develop pathways to permanent housing.

. [Empty]
.. A county may enact an ordinance or regulation or take any other action that requires a host religious organization and a distinct managing agency using the religious organization's property, owned or controlled by the religious organization, for hostings to include outdoor encampments, temporary small houses on-site, indoor overnight shelters, or vehicle resident safe parking to enter into a memorandum of understanding to protect the public health and safety of both the residents of the particular hosting and the residents of the county.

.. At a minimum, the agreement must include information regarding: The right of a resident in an outdoor encampment, vehicle resident safe parking, temporary small house on-site, or indoor overnight shelter to seek public health and safety assistance, the resident's ability to access social services on-site, and the resident's ability to directly interact with the host religious organization, including the ability to express any concerns regarding the managing agency to the religious organization; a written code of conduct agreed to by the managing agency, if any, host religious organization, and all volunteers working with residents of the outdoor encampment, temporary small house on-site, indoor overnight shelter, or vehicle resident safe parking; and when a publicly funded managing agency exists, the ability for the host religious organization to interact with residents of the outdoor encampment, indoor overnight shelter, temporary small house on-site, or vehicle resident safe parking using a release of information.

. If required to do so by the county, any host religious organization performing any hosting of an outdoor encampment, vehicle resident safe parking, or indoor overnight shelter, or the host religious organization's managing agency, must ensure that the county or local law enforcement agency has completed sex offender checks of all adult residents and guests. The host religious organization retains the authority to allow such offenders to remain on the property. A host religious organization or host religious organization's managing agency performing any hosting of vehicle resident safe parking must inform vehicle residents how to comply with laws regarding the legal status of vehicles and drivers, and provide a written code of conduct consistent with area standards.

. Any host religious organization performing any hosting of an outdoor encampment, vehicle resident safe parking, temporary small house on-site, or indoor overnight shelter, with a publicly funded managing agency, must work with the county to utilize Washington's homeless client management information system, as provided for in RCW 43.185C.180. When the religious organization does not partner with a managing agency, the religious organization is encouraged to partner with a local homeless services provider using the Washington homeless client managing information system. Any managing agency receiving any funding from local continuum of care programs must utilize the homeless client management information system. Temporary, overnight, extreme weather shelter provided in religious organization buildings does not need to meet this requirement.

. For the purposes of this section:

.. "Managing agency" means an organization such as a religious organization or other organized entity that has the capacity to organize and manage a homeless outdoor encampment, temporary small houses on-site, indoor overnight shelter, and a vehicle resident safe parking program.

.. "Outdoor encampment" means any temporary tent or structure encampment, or both.

.. "Religious organization" means the federally protected practice of a recognized religious assembly, school, or institution that owns or controls real property.

.. "Temporary" means not affixed to land permanently and not using underground utilities.

. [Empty]
.. Subsection (2) of this section does not affect a county policy, ordinance, memorandum of understanding, or applicable consent decree that regulates religious organizations' hosting of the homeless if such policies, ordinances, memoranda of understanding, or consent decrees:

... Exist prior to June 11, 2020;

... Do not categorically prohibit the hosting of the homeless by religious organizations; and

... Have not been previously ruled by a court to violate the religious land use and institutionalized persons act, 42 U.S.C. Sec. 2000cc.

.. If such policies, ordinances, memoranda of understanding, and consent decrees are amended after June 11, 2020, those amendments are not affected by subsection (2) of this section if those amendments satisfy (a)(ii) and (iii) of this subsection.

. An appointed or elected public official, public employee, or public agency as defined in RCW 4.24.470 is immune from civil liability for (a) damages arising from the permitting decisions for a temporary encampment for the homeless as provided in this section and (b) any conduct or unlawful activity that may occur as a result of the temporary encampment for the homeless as provided in this section.

. A religious organization hosting outdoor encampments, vehicle resident safe parking, or indoor overnight shelters for the homeless that receives funds from any government agency may not refuse to host any resident or prospective resident because of age, sex, marital status, sexual orientation, race, creed, color, national origin, honorably discharged veteran or military status, or the presence of any sensory, mental, or physical disability or the use of a trained dog guide or service animal by a person with a disability, as these terms are defined in RCW 49.60.040.

. [Empty]
.. Prior to the opening of an outdoor encampment, indoor overnight shelter, temporary small house on-site, or vehicle resident safe parking, a religious organization hosting the homeless on property owned or controlled by the religious organization must host a meeting open to the public for the purpose of providing a forum for discussion of related neighborhood concerns, unless the use is in response to a declared emergency. The religious organization must provide written notice of the meeting to the county legislative authority at least one week if possible but no later than ninety-six hours prior to the meeting. The notice must specify the time, place, and purpose of the meeting.

.. A county must provide community notice of the meeting described in (a) of this subsection by taking at least two of the following actions at any time prior to the time of the meeting:

... Delivering to each local newspaper of general circulation and local radio or television station that has on file with the governing body a written request to be notified of special meetings;

... Posting on the county's web site. A county is not required to post a special meeting notice on its web site if it: (A) Does not have a web site; (B) employs fewer than ten full-time equivalent employees; or (C) does not employ personnel whose duty, as defined by a job description or existing contract, is to maintain or update the web site;

... Prominently displaying, on signage at least two feet in height and two feet in width, one or more meeting notices that can be placed on or adjacent to the main arterials in proximity to the location of the meeting; or

... Prominently displaying the notice at the meeting site.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1754-S.SL.pdf?cite=2020%20c%20223%20§%202[2020 c 223 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1956-S.SL.pdf?cite=2010%20c%20175%20§%202[2010 c 175 § 2]; ]

== 36.01.300 - State and federal background checks of license applicants and licensees of occupations under local licensing authority.
. For the purpose of receiving criminal history record information by county officials, counties may:

.. By ordinance, require a state and federal background investigation of license applicants or licensees in occupations specified by ordinance;

.. By ordinance, require a federal background investigation of county employees, applicants for employment, volunteers, vendors, and independent contractors, who, in the course of their work or volunteer activity with the county, may have unsupervised access to children, persons with developmental disabilities, or vulnerable adults;

.. Require a state background investigation of county employees, applicants for employment, volunteers, vendors, and independent contractors, who, in the course of their work or volunteer activity with the county, may have unsupervised access to children, persons with developmental disabilities, or vulnerable adults; and

.. Require a criminal background investigation conducted through a private organization of county employees, applicants for employment, volunteers, vendors, and independent contractors, who, in the course of their work or volunteer activity with the county, may have unsupervised access to children, persons with developmental disabilities, or vulnerable adults.

. The investigation conducted under subsection (1)(a) through (c) of this section shall consist of a background check as allowed through the Washington state criminal records privacy act under RCW 10.97.050, the Washington state patrol criminal identification system under RCW 43.43.832 through 43.43.834, and the federal bureau of investigation.

. The background checks conducted under subsection (1)(a) through (c) of this section must be done through the Washington state patrol identification and criminal history section and may include a national check from the federal bureau of investigation, which shall be through the submission of fingerprints. The Washington state patrol shall serve as the sole source for receipt of fingerprint submissions and the responses to the submissions from the federal bureau of investigation, which must be disseminated to the county.

. For a criminal background check conducted under subsection (1)(a) through (c) of this section, the county shall transmit appropriate fees for a state and national criminal history check to the Washington state patrol, unless alternately arranged. The cost of investigations conducted under this section shall be borne by the county.

. The authority for background checks outlined in this section is in addition to any other authority for such checks provided by law.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1620.SL.pdf?cite=2017%20c%20332%20§%203[2017 c 332 § 3]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6288.SL.pdf?cite=2010%20c%2047%20§%201[2010 c 47 § 1]; ]

== 36.01.310 - Accessible community advisory committees.
. A county has the option to expand the scope of an advisory committee established and maintained under *RCW 29A.46.260 to that of an accessible community advisory committee, or to create an accessible community advisory committee.

. A county that has an active accessible community advisory committee may be reimbursed within available funds from the accessible communities account created in RCW 50.40.071 for travel, per diem, and reasonable accommodation expenses for the participation of that committee's members in committee meetings and sponsored activities.

. A county establishes that it has an active accessible community advisory committee by submitting biennial assurances to the governor's committee on disability issues and employment that:

.. The decision to establish an accessible community advisory committee was made by the county legislative authority, or by agents or officers acting under that authority.

.. If an accessible community advisory committee is established by expanding the advisory committee established and maintained under *RCW 29A.46.260, the county auditor supports that expansion.

.. Committee members include persons with a diverse range of disabilities who are knowledgeable in identifying and eliminating attitudinal, programmatic, communication, and physical barriers encountered by persons with disabilities.

.. The committee is actively involved in the following activities: Advising on addressing the needs of persons with disabilities in emergency plans; advising the county and other local governments within the county on access to programs services and activities, new construction or renovation projects, sidewalks, other pedestrian routes of travel, and disability parking enforcement; and developing local initiatives and activities to promote greater awareness of disability issues, and acceptance, involvement, and access for persons with disabilities within the community.

. Counties may form joint accessible community advisory committees, as long as no more than one of the participating counties has a population greater than seventy thousand.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5902-S.SL.pdf?cite=2010%20c%20215%20§%204[2010 c 215 § 4]; ]

== 36.01.320 - Application for a permit to site an energy plant or alternative energy resource—Written notice to United States department of defense.
. Upon receipt of an application for a permit to site an energy plant or alternative energy resource that is connected to electrical transmission facilities of a nominal voltage of at least one hundred fifteen thousand volts, the county shall notify in writing the United States department of defense. The notification shall include, but not be limited to, the following:

.. A description of the proposed energy plant or alternative energy resource;

.. The location of the site;

.. The number and placement of the energy plant or alternative energy resource on the site;

.. The date and time by which comments must be received by the county; and

.. Contact information of the county permitting authority and the applicant.

. The purpose of the written notification is to provide an opportunity for the United States department of defense to comment upon the application, and to identify potential issues relating to the placement and operations of the energy plant or alternative energy resource, before a permit application is approved. The time period set forth by the county for receipt of such comments shall not extend the time period for the county's processing of the application.

. For the purpose of this section, "alternative energy resource," "energy plant," and "electrical transmission facility" shall each have the meaning set forth in RCW 80.50.020.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1570-S.SL.pdf?cite=2011%20c%20261%20§%202[2011 c 261 § 2]; ]

== 36.01.330 - Failing septic systems—Connection to public sewer systems—Appeals process.
. A county with an ordinance or resolution requiring, upon the failure of an on-site septic system, connection to a public sewer system must, in accordance with this section, provide an administrative appeals process to consider denials of permit applications to repair or replace the septic system. The administrative appeals process required by this section applies only to requests to repair or replace existing, failing on-site septic systems that:

.. Were made for a single-family residence by its owner or owners;

.. Were denied solely because of a law, regulation, or ordinance requiring connection to a public sewer system; and

.. Absent the applicable law, regulation, or ordinance requiring connection to a public sewer system upon which the denial was based, would be approved. 

. If the county has an administrative appeals process, the county may, subject to the requirements of this section, use that process. The administrative appeals process required by this section, however, must be presided over by the legislative body of the county or by an administrative hearings officer.

. The administrative appeals process required by this section must, at a minimum, consider whether:

.. It is cost-prohibitive to require the property owner to connect to the public sewer system. In complying with this subsection (3)(a), the county must consider the estimated cost to repair or replace the on-site septic system compared to the estimated cost to connect to the public sewer system;

.. There are public health or environmental considerations related to allowing the property owner to repair or replace the on-site septic system. In complying with this subsection (3)(b), the county must consider whether the repaired or replaced on-site septic system contributes to the pollution of surface waters or groundwater;

.. There are public sewer system performance or financing considerations related to allowing the property owner to repair or replace the on-site septic system; and

.. There are financial assistance programs or latecomer agreements offered by the county or state that may impact a decision of the property owner to repair or replace the on-site septic system.

. If the county, following the appeals process required by this section, determines that the property owner must connect the residence to the public sewer system, the property owner may, in complying with the determination and subject to approval of appropriate permits, select and hire contractors at his or her own expense to perform the work necessary to connect the residence to the public sewer system.

. Unless otherwise required by law, a county determination requiring the owner of a single-family residence with a failing on-site septic system to connect a residence to a public sewer system is not subject to appeal.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5871.SL.pdf?cite=2015%20c%20297%20§%203[2015 c 297 § 3]; ]

== 36.01.340 - Final determination on state highway permit projects.
A county must comply with the requirements of RCW 47.01.485 in making a final determination on a permit as part of a project on a state highway as defined in RCW 46.04.560.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5994-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2015%20§%205[2015 3rd sp.s. c 15 § 5]; ]

== 36.01.350 - Removal of restrictive covenants—Hearing, notice.
Any county must hold a public hearing upon a proposal to remove, vacate, or extinguish a restrictive covenant from property owned by the county before the action is finalized. The public hearing must allow individuals to provide testimony regarding the proposed action. The county must provide notice of the public hearing at least ten days before the hearing at its usual place of business and issue a press release to local media providing the date, time, location, and reason for the public hearing. The notice must be posted on the county's web site if it is updated for any reason before the hearing. The notice must also identify the property and provide a brief explanation of the restrictive covenant to be removed, vacated, or extinguished. Any member of the public, in person or by counsel, may submit testimony regarding the proposed action at the public hearing.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1959.SL.pdf?cite=2017%20c%20119%20§%205[2017 c 119 § 5]; ]

