= 36.70B - Local project review.
:toc:

== 36.70B.010 - Findings and declaration.
The legislature finds and declares the following:

. As the number of environmental laws and development regulations has increased for land uses and development, so has the number of required local land use permits, each with its own separate approval process.

. The increasing number of local and state land use permits and separate environmental review processes required by agencies has generated continuing potential for conflict, overlap, and duplication between the various permit and review processes.

. This regulatory burden has significantly added to the cost and time needed to obtain local and state land use permits and has made it difficult for the public to know how and when to provide timely comments on land use proposals that require multiple permits and have separate environmental review processes.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1724-S.SL.pdf?cite=1995%20c%20347%20§%20401[1995 c 347 § 401]; ]

== 36.70B.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Closed record appeal" means an administrative appeal on the record to a local government body or officer, including the legislative body, following an open record hearing on a project permit application when the appeal is on the record with no or limited new evidence or information allowed to be submitted and only appeal argument allowed.

. "Local government" means a county, city, or town.

. "Open record hearing" means a hearing, conducted by a single hearing body or officer authorized by the local government to conduct such hearings, that creates the local government's record through testimony and submission of evidence and information, under procedures prescribed by the local government by ordinance or resolution. An open record hearing may be held prior to a local government's decision on a project permit to be known as an "open record predecision hearing." An open record hearing may be held on an appeal, to be known as an "open record appeal hearing," if no open record predecision hearing has been held on the project permit.

. "Project permit" or "project permit application" means any land use or environmental permit or license required from a local government for a project action, including but not limited to building permits, subdivisions, binding site plans, planned unit developments, conditional uses, shoreline substantial development permits, site plan review, permits or approvals required by critical area ordinances, site-specific rezones authorized by a comprehensive plan or subarea plan, but excluding the adoption or amendment of a comprehensive plan, subarea plan, or development regulations except as otherwise specifically included in this subsection.

. "Public meeting" means an informal meeting, hearing, workshop, or other public gathering of people to obtain comments from the public or other agencies on a proposed project permit prior to the local government's decision. A public meeting may include, but is not limited to, a design review or architectural control board meeting, a special review district or community council meeting, or a scoping meeting on a draft environmental impact statement. A public meeting does not include an open record hearing. The proceedings at a public meeting may be recorded and a report or recommendation may be included in the local government's project permit application file.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1724-S.SL.pdf?cite=1995%20c%20347%20§%20402[1995 c 347 § 402]; ]

== 36.70B.030 - Project review—Required elements—Limitations.
. Fundamental land use planning choices made in adopted comprehensive plans and development regulations shall serve as the foundation for project review. The review of a proposed project's consistency with applicable development regulations, or in the absence of applicable regulations the adopted comprehensive plan, under RCW 36.70B.040 shall incorporate the determinations under this section.

. During project review, a local government or any subsequent reviewing body shall determine whether the items listed in this subsection are defined in the development regulations applicable to the proposed project or, in the absence of applicable regulations the adopted comprehensive plan. At a minimum, such applicable regulations or plans shall be determinative of the:

.. Type of land use permitted at the site, including uses that may be allowed under certain circumstances, such as planned unit developments and conditional and special uses, if the criteria for their approval have been satisfied;

.. Density of residential development in urban growth areas; and

.. Availability and adequacy of public facilities identified in the comprehensive plan, if the plan or development regulations provide for funding of these facilities as required by chapter 36.70A RCW.

. During project review, the local government or any subsequent reviewing body shall not reexamine alternatives to or hear appeals on the items identified in subsection (2) of this section, except for issues of code interpretation. As part of its project review process, a local government shall provide a procedure for obtaining a code interpretation as provided in RCW 36.70B.110.

. Pursuant to RCW 43.21C.240, a local government may determine that the requirements for environmental analysis and mitigation measures in development regulations and other applicable laws provide adequate mitigation for some or all of the project's specific adverse environmental impacts to which the requirements apply.

. Nothing in this section limits the authority of a permitting agency to approve, condition, or deny a project as provided in its development regulations adopted under chapter 36.70A RCW and in its policies adopted under RCW 43.21C.060. Project review shall be used to identify specific project design and conditions relating to the character of development, such as the details of site plans, curb cuts, drainage swales, transportation demand management, the payment of impact fees, or other measures to mitigate a proposal's probable adverse environmental impacts, if applicable.

. Subsections (1) through (4) of this section apply only to local governments planning under RCW 36.70A.040.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1724-S.SL.pdf?cite=1995%20c%20347%20§%20404[1995 c 347 § 404]; ]

== 36.70B.040 - Determination of consistency.
. A proposed project's consistency with a local government's development regulations adopted under chapter 36.70A RCW, or, in the absence of applicable development regulations, the appropriate elements of the comprehensive plan adopted under chapter 36.70A RCW shall be decided by the local government during project review by consideration of:

.. The type of land use;

.. The level of development, such as units per acre or other measures of density;

.. Infrastructure, including public facilities and services needed to serve the development; and

.. The characteristics of the development, such as development standards.

. In deciding whether a project is consistent, the determinations made pursuant to RCW 36.70B.030(2) shall be controlling.

. For purposes of this section, the term "consistency" shall include all terms used in this chapter and chapter 36.70A RCW to refer to performance in accordance with this chapter and chapter 36.70A RCW, including but not limited to compliance, conformity, and consistency.

. Nothing in this section requires documentation, dictates an agency's procedures for considering consistency, or limits a city or county from asking more specific or related questions with respect to any of the four main categories listed in subsection (1)(a) through (d) of this section.

. The *department of community, trade, and economic development is authorized to develop and adopt by rule criteria to assist local governments planning under RCW 36.70A.040 to analyze the consistency of project actions. These criteria shall be jointly developed with the department of ecology.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6094.SL.pdf?cite=1997%20c%20429%20§%2046[1997 c 429 § 46]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1724-S.SL.pdf?cite=1995%20c%20347%20§%20405[1995 c 347 § 405]; ]

== 36.70B.050 - Local government review of project permit applications required—Objectives.
Not later than March 31, 1996, each local government shall provide by ordinance or resolution for review of project permit applications to achieve the following objectives:

. Combine the environmental review process, both procedural and substantive, with the procedure for review of project permits; and

. Except for the appeal of a determination of significance as provided in RCW 43.21C.075, provide for no more than one open record hearing and one closed record appeal.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1724-S.SL.pdf?cite=1995%20c%20347%20§%20406[1995 c 347 § 406]; ]

== 36.70B.060 - Local governments planning under the growth management act to establish integrated and consolidated project permit process—Required elements.
Not later than March 31, 1996, each local government planning under RCW 36.70A.040 shall establish by ordinance or resolution an integrated and consolidated project permit process that may be included in its development regulations. In addition to the elements required by RCW 36.70B.050, the process shall include the following elements:

. A determination of completeness to the applicant as required by RCW 36.70B.070;

. A notice of application to the public and agencies with jurisdiction as required by RCW 36.70B.110;

. Except as provided in RCW 36.70B.140, an optional consolidated project permit review process as provided in RCW 36.70B.120. The review process shall provide for no more than one consolidated open record hearing and one closed record appeal. If an open record predecision hearing is provided prior to the decision on a project permit, the process shall not allow a subsequent open record appeal hearing;

. Provision allowing for any public meeting or required open record hearing to be combined with any public meeting or open record hearing that may be held on the project by another local, state, regional, federal, or other agency, in accordance with provisions of RCW * 36.70B.090 and 36.70B.110;

. A single report stating all the decisions made as of the date of the report on all project permits included in the consolidated permit process that do not require an open record predecision hearing and any recommendations on project permits that do not require an open record predecision hearing. The report shall state any mitigation required or proposed under the development regulations or the agency's authority under RCW 43.21C.060. The report may be the local permit. If a threshold determination other than a determination of significance has not been issued previously by the local government, the report shall include or append this determination;

. Except for the appeal of a determination of significance as provided in RCW 43.21C.075, if a local government elects to provide an appeal of its threshold determinations or project permit decisions, the local government shall provide for no more than one consolidated open record hearing on such appeal. The local government need not provide for any further appeal and may provide an appeal for some but not all project permit decisions. If an appeal is provided after the open record hearing, it shall be a closed record appeal before a single decision-making body or officer;

. A notice of decision as required by RCW 36.70B.130 and issued within the time period provided in RCW 36.70B.080 and * 36.70B.090;

. Completion of project review by the local government, including environmental review and public review and any appeals to the local government, within any applicable time periods under *RCW 36.70B.090; and

. Any other provisions not inconsistent with the requirements of this chapter or chapter 43.21C RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1724-S.SL.pdf?cite=1995%20c%20347%20§%20407[1995 c 347 § 407]; ]

== 36.70B.070 - Project permit applications—Determination of completeness—Notice to applicant.
. Within twenty-eight days after receiving a project permit application, a local government planning pursuant to RCW 36.70A.040 shall mail or provide in person a written determination to the applicant, stating either:

.. That the application is complete; or

.. That the application is incomplete and what is necessary to make the application complete.

To the extent known by the local government, the local government shall identify other agencies of local, state, or federal governments that may have jurisdiction over some aspect of the application.

. A project permit application is complete for purposes of this section when it meets the procedural submission requirements of the local government and is sufficient for continued processing even though additional information may be required or project modifications may be undertaken subsequently. The determination of completeness shall not preclude the local government from requesting additional information or studies either at the time of the notice of completeness or subsequently if new information is required or substantial changes in the proposed action occur.

. The determination of completeness may include the following as optional information:

.. A preliminary determination of those development regulations that will be used for project mitigation;

.. A preliminary determination of consistency, as provided under RCW 36.70B.040; or

.. Other information the local government chooses to include.

. [Empty]
.. An application shall be deemed complete under this section if the local government does not provide a written determination to the applicant that the application is incomplete as provided in subsection (1)(b) of this section.

.. Within fourteen days after an applicant has submitted to a local government additional information identified by the local government as being necessary for a complete application, the local government shall notify the applicant whether the application is complete or what additional information is necessary.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1724-S.SL.pdf?cite=1995%20c%20347%20§%20408[1995 c 347 § 408]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6339-S.SL.pdf?cite=1994%20c%20257%20§%204[1994 c 257 § 4]; ]

== 36.70B.080 - Development regulations—Requirements—Report on implementation costs.
. Development regulations adopted pursuant to RCW 36.70A.040 must establish and implement time periods for local government actions for each type of project permit application and provide timely and predictable procedures to determine whether a completed project permit application meets the requirements of those development regulations. The time periods for local government actions for each type of complete project permit application or project type should not exceed one hundred twenty days, unless the local government makes written findings that a specified amount of additional time is needed to process specific complete project permit applications or project types.

The development regulations must, for each type of permit application, specify the contents of a completed project permit application necessary for the complete compliance with the time periods and procedures.

. [Empty]
.. Counties subject to the requirements of RCW 36.70A.215 and the cities within those counties that have populations of at least twenty thousand must, for each type of permit application, identify the total number of project permit applications for which decisions are issued according to the provisions of this chapter. For each type of project permit application identified, these counties and cities must establish and implement a deadline for issuing a notice of final decision as required by subsection (1) of this section and minimum requirements for applications to be deemed complete under RCW 36.70B.070 as required by subsection (1) of this section.

.. Counties and cities subject to the requirements of this subsection also must prepare annual performance reports that include, at a minimum, the following information for each type of project permit application identified in accordance with the requirements of (a) of this subsection:

... Total number of complete applications received during the year;

... Number of complete applications received during the year for which a notice of final decision was issued before the deadline established under this subsection;

... Number of applications received during the year for which a notice of final decision was issued after the deadline established under this subsection;

... Number of applications received during the year for which an extension of time was mutually agreed upon by the applicant and the county or city;

.. Variance of actual performance, excluding applications for which mutually agreed time extensions have occurred, to the deadline established under this subsection during the year; and

.. The mean processing time and the number standard deviation from the mean.

.. Counties and cities subject to the requirements of this subsection must:

... Provide notice of and access to the annual performance reports through the county's or city's website; and

... Post electronic facsimiles of the annual performance reports through the county's or city's website. Postings on a county's or city's website indicating that the reports are available by contacting the appropriate county or city department or official do not comply with the requirements of this subsection.

If a county or city subject to the requirements of this subsection does not maintain a website, notice of the reports must be given by reasonable methods, including but not limited to those methods specified in RCW 36.70B.110(4).

. Nothing in this section prohibits a county or city from extending a deadline for issuing a decision for a specific project permit application for any reasonable period of time mutually agreed upon by the applicant and the local government.

. The *department of community, trade, and economic development shall work with the counties and cities to review the potential implementation costs of the requirements of subsection (2) of this section. The department, in cooperation with the local governments, shall prepare a report summarizing the projected costs, together with recommendations for state funding assistance for implementation costs, and provide the report to the governor and appropriate committees of the senate and house of representatives by January 1, 2005.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2811.SL.pdf?cite=2004%20c%20191%20§%202[2004 c 191 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1458-S.SL.pdf?cite=2001%20c%20322%20§%201[2001 c 322 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1724-S.SL.pdf?cite=1995%20c%20347%20§%20410[1995 c 347 § 410]; 1995 c 347 § 409; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6339-S.SL.pdf?cite=1994%20c%20257%20§%203[1994 c 257 § 3]; ]

== 36.70B.100 - Designation of person or entity to receive determinations and notices.
A local government may require the applicant for a project permit to designate a single person or entity to receive determinations and notices required by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1724-S.SL.pdf?cite=1995%20c%20347%20§%20414[1995 c 347 § 414]; ]

== 36.70B.110 - Notice of application—Required elements—Integration with other review procedures—Administrative appeals (as amended by 1997 c 396).
. Not later than April 1, 1996, a local government planning under RCW 36.70A.040 shall provide a notice of application to the public and the departments and agencies with jurisdiction as provided in this section. If a local government has made a threshold determination ((of significance)) under chapter 43.21C RCW concurrently with the notice of application, the notice of application ((shall)) may be combined with the threshold determination ((of significance)) and the scoping notice for a determination of significance. Nothing in this section prevents a determination of significance and scoping notice from being issued prior to the notice of application.

. The notice of application shall be provided within fourteen days after the determination of completeness as provided in RCW 36.70B.070 and include the following in whatever sequence or format the local government deems appropriate:

.. The date of application, the date of the notice of completion for the application, and the date of the notice of application;

.. A description of the proposed project action and a list of the project permits included in the application and, if applicable, a list of any studies requested under RCW 36.70B.070 or * 36.70B.090;

.. The identification of other permits not included in the application to the extent known by the local government;

.. The identification of existing environmental documents that evaluate the proposed project, and, if not otherwise stated on the document providing the notice of application, such as a city land use bulletin, the location where the application and any studies can be reviewed;

.. A statement of the public comment period, which shall be not less than fourteen nor more than thirty days following the date of notice of application, and statements of the right of any person to comment on the application, receive notice of and participate in any hearings, request a copy of the decision once made, and any appeal rights. A local government may accept public comments at any time prior to the closing of the record of an open record predecision hearing, if any, or, if no open record predecision hearing is provided, prior to the decision on the project permit;

.. The date, time, place, and type of hearing, if applicable and scheduled at the date of notice of the application;

.. A statement of the preliminary determination, if one has been made at the time of notice, of those development regulations that will be used for project mitigation and of consistency as provided in RCW 36.70B.040; and

.. Any other information determined appropriate by the local government.

. If an open record predecision hearing is required for the requested project permits, the notice of application shall be provided at least fifteen days prior to the open record hearing.

. A local government shall use reasonable methods to give the notice of application to the public and agencies with jurisdiction and may use its existing notice procedures. A local government may use different types of notice for different categories of project permits or types of project actions. If a local government by resolution or ordinance does not specify its method of public notice, the local government shall use the methods provided for in (a) and (b) of this subsection. Examples of reasonable methods to inform the public are:

.. Posting the property for site-specific proposals;

.. Publishing notice, including at least the project location, description, type of permit(s) required, comment period dates, and location where the complete application may be reviewed, in the newspaper of general circulation in the general area where the proposal is located or in a local land use newsletter published by the local government;

.. Notifying public or private groups with known interest in a certain proposal or in the type of proposal being considered;

.. Notifying the news media;

.. Placing notices in appropriate regional or neighborhood newspapers or trade journals;

.. Publishing notice in agency newsletters or sending notice to agency mailing lists, either general lists or lists for specific proposals or subject areas; and

.. Mailing to neighboring property owners.

. A notice of application shall not be required for project permits that are categorically exempt under chapter 43.21C RCW, unless a public comment period or an open record predecision hearing is required.

. A local government shall integrate the permit procedures in this section with environmental review under chapter 43.21C RCW as follows:

.. Except for a threshold determination ((of significance)), the local government may not issue ((its threshold determination, or issue)) a decision or a recommendation on a project permit until the expiration of the public comment period on the notice of application.

.. If an open record predecision hearing is required and the local government's threshold determination requires public notice under chapter 43.21C RCW, the local government shall issue its threshold determination at least fifteen days prior to the open record predecision hearing.

.. Comments shall be as specific as possible.

. A local government may combine any hearing on a project permit with any hearing that may be held by another local, state, regional, federal, or other agency provided that the hearing is held within the geographic boundary of the local government. Hearings shall be combined if requested by an applicant, as long as the joint hearing can be held within the time periods specified in *RCW 36.70B.090 or the applicant agrees to the schedule in the event that additional time is needed in order to combine the hearings. All agencies of the state of Washington, including municipal corporations and counties participating in a combined hearing, are hereby authorized to issue joint hearing notices and develop a joint format, select a mutually acceptable hearing body or officer, and take such other actions as may be necessary to hold joint hearings consistent with each of their respective statutory obligations.

. All state and local agencies shall cooperate to the fullest extent possible with the local government in holding a joint hearing if requested to do so, as long as:

.. The agency is not expressly prohibited by statute from doing so;

.. Sufficient notice of the hearing is given to meet each of the agencies' adopted notice requirements as set forth in statute, ordinance, or rule; and

.. The agency has received the necessary information about the proposed project from the applicant to hold its hearing at the same time as the local government hearing.

. A local government is not required to provide for administrative appeals. If provided, an administrative appeal of the project decision, combined with any environmental determinations, shall be filed within fourteen days after the notice of the decision or after other notice that the decision has been made and is appealable. The local government shall extend the appeal period for an additional seven days, if state or local rules adopted pursuant to chapter 43.21C RCW allow public comment on a determination of nonsignificance issued as part of the appealable project permit decision.

. The applicant for a project permit is deemed to be a participant in any comment period, open record hearing, or closed record appeal.

. Each local government planning under RCW 36.70A.040 shall adopt procedures for administrative interpretation of its development regulations.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5462-S.SL.pdf?cite=1997%20c%20396%20§%201[1997 c 396 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1724-S.SL.pdf?cite=1995%20c%20347%20§%20415[1995 c 347 § 415]; ]

== 36.70B.120 - Permit review process.
. Each local government planning under RCW 36.70A.040 shall establish a permit review process that provides for the integrated and consolidated review and decision on two or more project permits relating to a proposed project action, including a single application review and approval process covering all project permits requested by an applicant for all or part of a project action and a designated permit coordinator. If an applicant elects the consolidated permit review process, the determination of completeness, notice of application, and notice of final decision must include all project permits being reviewed through the consolidated permit review process.

. Consolidated permit review may provide different procedures for different categories of project permits, but if a project action requires project permits from more than one category, the local government shall provide for consolidated permit review with a single open record hearing and no more than one closed record appeal as provided in RCW 36.70B.060. Each local government shall determine which project permits are subject to an open record hearing and a closed record appeal. Examples of categories of project permits include but are not limited to:

.. Proposals that are categorically exempt from chapter 43.21C RCW, such as construction permits, that do not require environmental review or public notice;

.. Permits that require environmental review, but no open record predecision hearing; and

.. Permits that require a threshold determination and an open record predecision hearing and may provide for a closed record appeal to a hearing body or officer or to the local government legislative body.

. A local government may provide by ordinance or resolution for the same or a different decision maker or hearing body or officer for different categories of project permits. In the case of consolidated project permit review, the local government shall specify which decision makers shall make the decision or recommendation, conduct the hearing, or decide the appeal to ensure that consolidated permit review occurs as provided in this section. The consolidated permit review may combine an open record predecision hearing on one or more permits with an open record appeal hearing on other permits. In such cases, the local government by ordinance or resolution shall specify which project permits, if any, shall be subject to a closed record appeal.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1724-S.SL.pdf?cite=1995%20c%20347%20§%20416[1995 c 347 § 416]; ]

== 36.70B.130 - Notice of decision—Distribution.
A local government planning under RCW 36.70A.040 shall provide a notice of decision that also includes a statement of any threshold determination made under chapter 43.21C RCW and the procedures for administrative appeal, if any. The notice of decision may be a copy of the report or decision on the project permit application. The notice shall be provided to the applicant and to any person who, prior to the rendering of the decision, requested notice of the decision or submitted substantive comments on the application. The local government shall provide for notice of its decision as provided in RCW 36.70B.110(4), which shall also state that affected property owners may request a change in valuation for property tax purposes notwithstanding any program of revaluation. The local government shall provide notice of decision to the county assessor's office of the county or counties in which the property is situated.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2567.SL.pdf?cite=1996%20c%20254%20§%201[1996 c 254 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1724-S.SL.pdf?cite=1995%20c%20347%20§%20417[1995 c 347 § 417]; ]

== 36.70B.140 - Project permits that may be excluded from review.
. A local government by ordinance or resolution may exclude the following project permits from the provisions of RCW 36.70B.060 through * 36.70B.090 and 36.70B.110 through 36.70B.130: Landmark designations, street vacations, or other approvals relating to the use of public areas or facilities, or other project permits, whether administrative or quasi-judicial, that the local government by ordinance or resolution has determined present special circumstances that warrant a review process different from that provided in RCW 36.70B.060 through * 36.70B.090 and 36.70B.110 through 36.70B.130.

. A local government by ordinance or resolution also may exclude the following project permits from the provisions of RCW 36.70B.060 and 36.70B.110 through 36.70B.130: Lot line or boundary adjustments and building and other construction permits, or similar administrative approvals, categorically exempt from environmental review under chapter 43.21C RCW, or for which environmental review has been completed in connection with other project permits.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1724-S.SL.pdf?cite=1995%20c%20347%20§%20418[1995 c 347 § 418]; ]

== 36.70B.150 - Local governments not planning under the growth management act may use provisions.
A local government not planning under RCW 36.70A.040 may incorporate some or all of the provisions of RCW 36.70B.060 through * 36.70B.090 and 36.70B.110 through 36.70B.130 into its procedures for review of project permits or other project actions.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1724-S.SL.pdf?cite=1995%20c%20347%20§%20419[1995 c 347 § 419]; ]

== 36.70B.160 - Additional project review encouraged—Construction.
. Each local government is encouraged to adopt further project review provisions to provide prompt, coordinated review and ensure accountability to applicants and the public, including expedited review for project permit applications for projects that are consistent with adopted development regulations and within the capacity of systemwide infrastructure improvements.

. Nothing in this chapter is intended or shall be construed to prevent a local government from requiring a preapplication conference or a public meeting by rule, ordinance, or resolution.

. Each local government shall adopt procedures to monitor and enforce permit decisions and conditions.

. Nothing in this chapter modifies any independent statutory authority for a government agency to appeal a project permit issued by a local government.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1724-S.SL.pdf?cite=1995%20c%20347%20§%20420[1995 c 347 § 420]; ]

== 36.70B.170 - Development agreements—Authorized.
. A local government may enter into a development agreement with a person having ownership or control of real property within its jurisdiction. A city may enter into a development agreement for real property outside its boundaries as part of a proposed annexation or a service agreement. A development agreement must set forth the development standards and other provisions that shall apply to and govern and vest the development, use, and mitigation of the development of the real property for the duration specified in the agreement. A development agreement shall be consistent with applicable development regulations adopted by a local government planning under chapter 36.70A RCW.

. RCW 36.70B.170 through 36.70B.190 and section 501, chapter 347, Laws of 1995 do not affect the validity of a contract rezone, concomitant agreement, annexation agreement, or other agreement in existence on July 23, 1995, or adopted under separate authority, that includes some or all of the development standards provided in subsection (3) of this section.

. For the purposes of this section, "development standards" includes, but is not limited to:

.. Project elements such as permitted uses, residential densities, and nonresidential densities and intensities or building sizes;

.. The amount and payment of impact fees imposed or agreed to in accordance with any applicable provisions of state law, any reimbursement provisions, other financial contributions by the property owner, inspection fees, or dedications;

.. Mitigation measures, development conditions, and other requirements under chapter 43.21C RCW;

.. Design standards such as maximum heights, setbacks, drainage and water quality requirements, landscaping, and other development features;

.. Affordable housing;

.. Parks and open space preservation;

.. Phasing;

.. Review procedures and standards for implementing decisions;

.. A build-out or vesting period for applicable standards; and

.. Any other appropriate development requirement or procedure.

. The execution of a development agreement is a proper exercise of county and city police power and contract authority. A development agreement may obligate a party to fund or provide services, infrastructure, or other facilities. A development agreement shall reserve authority to impose new or different regulations to the extent required by a serious threat to public health and safety.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1724-S.SL.pdf?cite=1995%20c%20347%20§%20502[1995 c 347 § 502]; ]

== 36.70B.180 - Development agreements—Effect.
Unless amended or terminated, a development agreement is enforceable during its term by a party to the agreement. A development agreement and the development standards in the agreement govern during the term of the agreement, or for all or that part of the build-out period specified in the agreement, and may not be subject to an amendment to a zoning ordinance or development standard or regulation or a new zoning ordinance or development standard or regulation adopted after the effective date of the agreement. A permit or approval issued by the county or city after the execution of the development agreement must be consistent with the development agreement.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1724-S.SL.pdf?cite=1995%20c%20347%20§%20503[1995 c 347 § 503]; ]

== 36.70B.190 - Development agreements—Recording—Parties and successors bound.
A development agreement shall be recorded with the real property records of the county in which the property is located. During the term of the development agreement, the agreement is binding on the parties and their successors, including a city that assumes jurisdiction through incorporation or annexation of the area covering the property covered by the development agreement.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1724-S.SL.pdf?cite=1995%20c%20347%20§%20504[1995 c 347 § 504]; ]

== 36.70B.200 - Development agreements—Public hearing.
A county or city shall only approve a development agreement by ordinance or resolution after a public hearing. The county or city legislative body or a planning commission, hearing examiner, or other body designated by the legislative body to conduct the public hearing may conduct the hearing. If the development agreement relates to a project permit application, the provisions of chapter 36.70C RCW shall apply to the appeal of the decision on the development agreement.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1724-S.SL.pdf?cite=1995%20c%20347%20§%20505[1995 c 347 § 505]; ]

== 36.70B.210 - Development agreements—Authority to impose fees not extended.
Nothing in RCW 36.70B.170 through 36.70B.200 and section 501, chapter 347, Laws of 1995 is intended to authorize local governments to impose impact fees, inspection fees, or dedications or to require any other financial contributions or mitigation measures except as expressly authorized by other applicable provisions of state law.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1724-S.SL.pdf?cite=1995%20c%20347%20§%20506[1995 c 347 § 506]; ]

== 36.70B.220 - Permit assistance staff.
. Each county and city having populations of ten thousand or more that plan under RCW 36.70A.040 shall designate permit assistance staff whose function it is to assist permit applicants. An existing employee may be designated as the permit assistance staff.

. Permit assistance staff designated under this section shall:

.. Make available to permit applicants all current local government regulations and adopted policies that apply to the subject application. The local government shall provide counter copies thereof and, upon request, provide copies according to chapter 42.56 RCW. The staff shall also publish and keep current one or more handouts containing lists and explanations of all local government regulations and adopted policies;

.. Establish and make known to the public the means of obtaining the handouts and related information; and

.. Provide assistance regarding the application of the local government's regulations in particular cases.

. Permit assistance staff designated under this section may obtain technical assistance and support in the compilation and production of the handouts under subsection (2) of this section from the department of commerce.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2658-S2.SL.pdf?cite=2010%20c%20271%20§%20707[2010 c 271 § 707]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20272[2005 c 274 § 272]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2386-S.SL.pdf?cite=1996%20c%20206%20§%209[1996 c 206 § 9]; ]

== 36.70B.230 - Planning regulations—Copies provided to county assessor.
By July 31, 1997, a local government planning under RCW 36.70A.040 shall provide to the county assessor a copy of the local government's comprehensive plan and development regulations in effect on July 1st of that year and shall thereafter provide any amendments to the plan and regulations that were adopted before July 31st of each following year.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2567.SL.pdf?cite=1996%20c%20254%20§%206[1996 c 254 § 6]; ]

== 36.70B.900 - Finding—Severability—Part headings and table of contents not law—1995 c 347.
See notes following RCW 36.70A.470.

[ ]

