= 36.130 - Affordable housing developments.
:toc:

== 36.130.005 - Intent.
It is the public policy of the state to assist in making affordable housing available throughout the state. The legislature recognizes that despite ongoing efforts there is still a lack of affordable housing in many areas. The legislature also recognizes that some local governments have imposed development requirements on affordable housing developments that are not generally imposed on other housing developments. The intent of this [the] legislature is to prohibit discrimination against affordable housing developments.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2279-S.SL.pdf?cite=2008%20c%20118%20§%201[2008 c 118 § 1]; ]

== 36.130.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Affordable housing development" means a housing development in which at least twenty-five percent of the dwelling units within the development are set aside for or are occupied by low-income households at a sales price or rent amount that is considered affordable by a federal, state, or local government housing program.

. "Dwelling unit" means that part of a housing development that is used as a home, residence, or place to sleep by one person or two or more persons maintaining a common household.

. "Housing development" means a proposed or existing structure that is used as a home, residence, or place to sleep by one or more persons including, but not limited to, single-family residences, manufactured homes, multifamily housing, group homes, and foster care facilities.

. "Low-income household" means a single person, family, or unrelated persons living together whose adjusted income is less than eighty percent of the median family income, adjusted for household size, for the county where the affordable housing development is located.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2279-S.SL.pdf?cite=2008%20c%20118%20§%202[2008 c 118 § 2]; ]

== 36.130.020 - Restrictions on affordable housing development requirements—Preferential treatment—Requirements as conditions.
. A city, county, or other local governmental entity or agency may not adopt, impose, or enforce requirements on an affordable housing development that are different than the requirements imposed on housing developments generally.

. This section does not prohibit any city, county, or other local governmental entity or agency from extending preferential treatment to affordable housing developments intended for including, but not limited to, occupancy by homeless persons, farmworkers, persons with disabilities, senior citizens, or low-income households. Preferential treatment may include, but is not limited to: A reduction or waiver of fees or changes in applicable requirements including, without limitation, architectural requirements, site development requirements, property line requirements, building setback requirements, or vehicle parking requirements; or other treatment that reduces or is likely to reduce the development or operating costs of an affordable housing development.

. A city, county, or other local governmental entity or agency may impose and enforce requirements on affordable housing developments as conditions of loans, grants, financial support, tax benefits, subsidy funds, or sale or lease of public property, or as conditions to eligibility for any affordable housing incentive program under RCW 36.70A.540 or any other program involving bonus density, transfer of development rights, waiver of development regulations or fees, or other development incentives.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2279-S.SL.pdf?cite=2008%20c%20118%20§%203[2008 c 118 § 3]; ]

