= 36.125 - Marine resources committees.
:toc:

== 36.125.005 - Findings—Intent.
. The legislature finds the challenge of developing realistic, effective, and efficient solutions to the conservation and management issues facing Puget Sound and Washington's outer coast requires calling on all available sources of knowledge and creative thinking available in the collective wisdom of Washington's citizens. The legislature further finds that both Puget Sound and the outer coast are dynamic and localized water bodies with unique local challenges and unique local solutions. As such, it is essential for the future management of these ecosystems that citizens, through their local government, have a voice and an opportunity to share their dedication and interest in the well-being of their community's unique marine waters, while providing a valuable contribution to the statewide efforts aimed at restoring the outer coast and Puget Sound as a whole.

. The legislature further finds that federally led efforts to establish marine resources committees have proven to be an exciting vehicle for involving local citizens and community leaders in the future discussions, decisions, and restoration commitments in the waters most important to the community. The existing model of using a community-based, nonregulatory organization to examine issues particular to a community's corner of Puget Sound, applying for grants, and thoroughly and fairly investigating available options and solutions has proved to be a valuable asset to Puget Sound and its communities, and is worthy of replication throughout the Puget Sound basin and the outer coast.

. In this chapter, the legislature intends to establish a structure on which interested local communities can harness the dedication, creativity, and wisdom of their residents in the form of marine resources committees. These committees are intended to complement, and not compete with or undermine, any other governmental efforts to restore and manage the Puget Sound. The legislature further intends that the department of fish and wildlife should apply the lessons learned from Puget Sound to work with county governments on the outer coast to establish marine resources committees.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2049-S.SL.pdf?cite=2007%20c%20344%20§%201[2007 c 344 § 1]; ]

== 36.125.010 - Counties authorized to establish—Purpose—Role.
. [Empty]
.. The legislative authority for each county that borders the marine waters of southern Puget Sound may establish marine resources committees consistent with the procedures outlined in RCW 36.125.020. Counties authorized to establish marine resources committees in the southern Puget Sound are: King, Pierce, Thurston, Kitsap, and Mason counties.

.. The legislative authority for each county bordering the marine waters of the outer coast may develop a marine resources committee consistent with the procedures outlined in RCW 36.125.020. Counties authorized to establish marine resources committees on the outer coast are: Pacific, Grays Harbor, and Wahkiakum counties.

.. Jefferson and Clallam counties may establish a new marine resources committee or a subcommittee of the county's existing marine resources committee, consistent with the procedures outlined in RCW 36.125.020, specifically to address the marine ecosystems for the outer coast or Puget Sound, where appropriate.

. The mission of a marine resources committee created under this section is to address, utilizing sound science, the needs of the marine ecosystem local to the county initiating the marine resources committee.

. A marine resources committee created under this section should review current data and resource conservation and management programs and make prioritized recommendations for additional measures that might be necessary to enhance protection of marine resources.

. The role of a marine resources committee in developing recommendations includes, but is not limited to:

.. Utilizing existing data and, to the extent necessary, helping to gather new data on the health of local marine resources;

.. Making scientifically based recommendations on local candidate sites for marine protected areas;

.. Working closely with local and state officials to help implement recommendations of the marine resources committee;

.. Promoting public outreach and education around marine resource conservation and management issues; and

.. Engaging in any other activities that the initiating county deems appropriate.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2049-S.SL.pdf?cite=2007%20c%20344%20§%202[2007 c 344 § 2]; ]

== 36.125.020 - Administration—Members—Petition.
. A marine resources committee, as described in RCW 36.125.010, may be created by the legislative authority of any county bordering the marine waters of the outer coast or Puget Sound, in cooperation with all appropriate cities and special districts within their boundaries. Adjacent county legislative authorities shall coordinate their efforts whenever there is a mutual interest in creating a marine resources committee.

. A county may delegate the management and oversight of a marine resources committee created by the county under RCW 36.125.010 to a city, or cities, within its jurisdiction, if the city or cities are located on the marine waters of the outer coast or southern Puget Sound and are willing to accept the delegation.

. [Empty]
.. Participating county legislative authorities must select members of the marine resources committee, ensuring balanced representation from: Local government; local residents; scientific experts; affected economic interests; affected recreational interests; and environmental and conservation interests. Additionally, participating county legislative authorities must invite tribal representatives to participate in the marine resources committee.

.. In lieu of creating a new entity, participating county legislative authorities may designate a lead entity created under RCW 77.85.050 to also serve as a marine resources committee. County legislative authorities may only make this designation where the lead entity consents in writing to also serve as a marine resources committee.

.. An initiating county may delegate its appointment authority to a city or cities that have received from the county the delegated responsibilities of managing and overseeing the marine resources committee.

. County residents may petition the county legislative authority to create a marine resources committee. Upon receipt of a petition, the county legislative authority must respond in writing within sixty days as to whether they will authorize the creation of a marine resources committee as well as the reasons for their decision.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6227-S2.SL.pdf?cite=2008%20c%20242%20§%202[2008 c 242 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2049-S.SL.pdf?cite=2007%20c%20344%20§%203[2007 c 344 § 3]; ]

== 36.125.030 - Regional coordinating entities.
. The Puget Sound action team, or its successor organization, shall serve as the regional coordinating entity for marine resources committees created in the southern Puget Sound and the department of fish and wildlife shall serve as the regional coordinating entity for marine resources committees created for the outer coast.

. The regional coordinating entity shall serve as a resource to, at a minimum:

.. Coordinate and pool grant applications and other funding requests for marine resources committees;

.. Coordinate communications and information among marine resources committees;

.. Assist marine resources committees to measure themselves against regional performance benchmarks; 

.. Assist marine resources committees with coordinating local projects to complement regional priorities;

.. Assist marine resources committees to interact with and complement other marine resources committees, and other similar groups, constituted under a different authority; and

.. Coordinate with the Northwest Straits commission on issues common to marine resources committees statewide.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2049-S.SL.pdf?cite=2007%20c%20344%20§%204[2007 c 344 § 4]; ]

== 36.125.040 - Application to committees established under federal law.
Nothing in RCW 36.125.010 or 36.125.020 is intended to expand or limit the authority of local marine resources committees established under the Northwest Straits marine conservation initiative by federal act in San Juan, Whatcom, Skagit, Island, Snohomish, Clallam, and Jefferson counties and existing as of July 22, 2007.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2049-S.SL.pdf?cite=2007%20c%20344%20§%205[2007 c 344 § 5]; ]

== 36.125.050 - Collaborative process for ocean policy development and coastal area management.
Outer coast marine resources committees, in conjunction with their regional coordinating entity, shall meet and consult with key state, federal, local, and tribal governments, and private interest groups to develop a collaborative process to address ocean policy issues. This collaborative process should use Washington's "Ocean Action Plan: Enhancing Management of Washington State's Ocean and Outer Coasts" developed by the Washington ocean policy work group as a guide to begin the work of developing and coordinating state and local ocean policy and providing better management of Washington's coastal areas.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2049-S.SL.pdf?cite=2007%20c%20344%20§%206[2007 c 344 § 6]; ]

== 36.125.060 - Outer coast marine resources committee program—Annual reports.
. The outer coast marine resources committee program is created to provide support for the development, administration, and coordination of outer coast marine resources committees and their projects.

. The director of fish and wildlife is the administrator of the outer coast marine resources committee program. As the administrator of the program, the director of fish and wildlife shall:

.. Provide each outer coast marine resources committee with a coordinator to support the administration and work of the committee; and

.. Distribute grants to outer coast marine resources committees for projects that benefit Washington's coastal marine resources. The director of fish and wildlife shall develop procedures and criteria for allocating funds for projects, which may include annual allocation of funding to each committee.

. Each outer coast marine resources committee shall prepare and deliver an annual report to the director of fish and wildlife by October 31st of each year. The report must include, but is not limited to, a summary of actions taken that year and prioritized recommendations for future action. The director of fish and wildlife shall compile the individual outer coast marine resources committee reports into a consolidated report, and provide the consolidated report to the governor and appropriate committees of the legislature by December 31st of each year.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6227-S2.SL.pdf?cite=2008%20c%20242%20§%203[2008 c 242 § 3]; ]

