= 36.115 - Service agreements.
:toc:

== 36.115.010 - Purpose.
The purpose of chapter 266, Laws of 1994 is to establish a flexible process by which local governments enter into service agreements that will establish which jurisdictions should provide various local government services and facilities within specified geographic areas and how those services and facilities will be financed.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5038-S.SL.pdf?cite=1994%20c%20266%20§%201[1994 c 266 § 1]; ]

== 36.115.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "City" means a city or town, including a city operating under Title 35A RCW.

. "Governmental service" includes a service provided by local government, and any facilities and equipment related to the provision of such services, including but not limited to utility services, health services, social services, law enforcement services, fire prevention and suppression services, community development activities, environmental protection activities, economic development activities, and transportation services and facilities, but shall not include the generation, conservation, or distribution of electrical energy nor maritime shipping activities.

. "Regional service" means a governmental service established by agreement among local governments that delineates the government entity or entities responsible for the service provision and allows for that delivery to extend over jurisdictional boundaries.

. "Local government" means a county, city, or special district.

. "Service agreement" means an agreement among counties, cities, and special districts established pursuant to this chapter.

. "Special district" means a municipal or quasi-municipal corporation in the state, other than a county, city, or school district.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5038-S.SL.pdf?cite=1994%20c%20266%20§%202[1994 c 266 § 2]; ]

== 36.115.030 - Coordination—Consistency.
A service agreement addressing children and family services shall enhance coordination and shall be consistent with the comprehensive plan developed under chapter 7, Laws of 1994 sp. sess.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5038-S.SL.pdf?cite=1994%20c%20266%20§%203[1994 c 266 § 3]; ]

== 36.115.040 - Geographic area covered—Contents—When effective.
. Agreements among local governments concerning one or more governmental service should be established for a designated geographic area as provided in this section.

. A service agreement must describe: (a) The governmental service or services addressed by the agreement; (b) the geographic area covered by the agreement; (c) which local government or local governments are to provide each of the governmental services addressed by the agreement within the geographic area covered by the agreement; and (d) the term of the agreement, if any.

. A service agreement becomes effective when approved by: (a) The county legislative authority of each county that includes territory located within the geographic area covered by the agreement; (b) the governing body or bodies of at least a simple majority of the total number of cities that includes territory located within the geographic area covered by the agreement, which cities include at least seventy-five percent of the total population of all cities that includes territory located within the geographic area covered by the agreement; and (c) for each governmental service addressed by the agreement, the governing body or bodies of at least a simple majority of the special districts that include territory located within the geographic area covered by the agreement and which provide the governmental service within such territory. The participants may agree to use another formula. An agreement pursuant to this section shall be effective upon adoption by the county legislative authority following a public hearing.

. A service agreement may cover a geographic area that includes territory located in more than a single county.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5038-S.SL.pdf?cite=1994%20c%20266%20§%204[1994 c 266 § 4]; ]

== 36.115.050 - Matters included.
A service agreement may include, but is not limited to, any or all of the following matters:

. A dispute resolution arrangement;

. How joint land-use planning and development regulations by the county and a city or cities, or by two or more cities, may be established, made binding, and enforced;

. How common development standards between the county and a city or cities, or between two or more cities, may be established, made binding, and enforced;

. How capital improvement plans of the county, cities, and special districts shall be coordinated;

. How plans and policies adopted under chapter 36.70A RCW will be implemented by the service agreement;

. A transfer of revenues between local governments in relationship to their obligations for providing governmental services;

. The designation of additional area-wide governmental services to be provided by the county.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5038-S.SL.pdf?cite=1994%20c%20266%20§%205[1994 c 266 § 5]; ]

== 36.115.060 - Procedure for establishment—Counties affected.
. The county legislative authority of every county with a population of one hundred fifty thousand or more shall convene a meeting on or before March 1, 1995, to develop a process for the establishment of service agreements. Invitations to attend this meeting shall be sent to the governing body of each city located in the county, and to the governing body of each special district located in the county that provides one or more of the governmental services as defined in RCW 36.115.020(2).

The legislative authorities of counties of less than one hundred fifty thousand population may utilize this chapter by adopting a resolution stating their intent to do so. In that case or in the case of counties whose populations reach one hundred fifty thousand after March 1, 1995, this meeting shall be convened no later than sixty days after the date the county adopts its resolution of intention or was certified by the office of financial management as having a population of one hundred fifty thousand or more.

. On or before January 1, 1997, a service agreement must be adopted in each county under this chapter or a progress report must be submitted to the appropriate committees of the legislature.

. In other counties that choose to utilize this chapter or whose population reaches one hundred fifty thousand, the service agreement must be adopted two years after the initial meeting provided for in subsection (1) of this section is convened or a progress report must be submitted to the appropriate committees of the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5038-S.SL.pdf?cite=1994%20c%20266%20§%206[1994 c 266 § 6]; ]

== 36.115.070 - Legislative intent.
It is the intent of the legislature to permit the creation of a flexible process to establish service agreements and to recognize that local governments possess broad authority to shape a variety of government service agreements to meet their local needs and circumstances. However, it is noted that in general, cities are the unit of local government most appropriate to provide urban governmental services and counties are the unit of local government most appropriate to provide regional governmental services.

The process to establish service agreements should assure that all directly affected local governments, and Indian tribes at their option, are allowed to be heard on issues relevant to them.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5038-S.SL.pdf?cite=1994%20c%20266%20§%207[1994 c 266 § 7]; ]

== 36.115.080 - Duties, requirements, authorities under growth management act not altered.
Nothing contained in this chapter alters the duties, requirements, and authorities of cities and counties contained in chapter 36.70A RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5038-S.SL.pdf?cite=1994%20c%20266%20§%208[1994 c 266 § 8]; ]

