= 36.165 - Commercial property assessed clean energy and resiliency (C-PACER) program.
:toc:

== 36.165.005 - Finding—2020 c 27.
. The legislature finds that the efficiency and resiliency of buildings in Washington is essential for ensuring the health and safety of residents, employees, and tenants; for using water and energy more efficiently; and for economic development of our communities. Buildings in Washington have significant needs for resiliency retrofits, including seismic improvements, stormwater management, flood mitigation, wildfire and wind resistance, and for clean energy and energy efficiency improvements, but these improvements often have high up-front capital costs.

. This chapter authorizes the establishment of a commercial property assessed clean energy and resiliency ("C-PACER") program that jurisdictions can voluntarily implement to ensure that free and willing owners of agricultural, commercial, and industrial properties and of multifamily residential properties with five or more dwelling units can obtain low-cost, long-term financing for qualifying improvements, including energy efficiency, water conservation, renewable energy, and resiliency projects. These improvements are repaid by a voluntary assessment on the property, secured by a county lien, and assigned to a capital provider for all the administrative aspects of billing, collecting, and enforcing the lien and without the accumulation of cost to the county and without the creation of a personal debt obligation to the property owner. The obligation is instead carried by the property and remains with the property until repaid, regardless of any potential transfer of property ownership. After the adoption of a C-PACER program, a county's role is limited to the approval of an assessment and recordation of a C-PACER lien, and administration of the C-PACER program which may be contracted out to a private third party.

. The legislature declares that the establishment and operation of a C-PACER program under this chapter serves important public health and safety interests. A qualified improvement as defined in RCW 36.165.010 provides benefit to the public, either in the form of energy or water resource conservation, reduced public health risk, or reduced public emergency response risk. Accordingly, the governing body of a county is authorized to determine that it is convenient and advantageous to adopt a program under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2405-S2.SL.pdf?cite=2020%20c%2027%20§%201[2020 c 27 § 1]; ]

== 36.165.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Assessment" means the voluntary agreement of a property owner to allow a county to place an annual assessment on their property to repay C-PACER financing.

. "Capital provider" means any private entity, their designee, successor, and assigns that makes or funds C-PACER financing under this chapter.

. "C-PACER financing" means an investment from a capital provider to a property owner to finance or refinance a qualified project as described under this chapter.

. "C-PACER lien" means the lien recorded at the county on the eligible property to secure the voluntary annual assessment, which remains on the property until paid in full.

. "Eligible property" means privately owned commercial, industrial, or agricultural real property or multifamily residential real property with five or more dwelling units. Eligible property may be owned by any type of business, corporation, individual, or nonprofit organization permitted by state law.

. "Financing agreement" means the contract under which a property owner agrees to repay a capital provider for the C-PACER financing including, but not limited to, details of any finance charges, fees, debt servicing, accrual of interest and penalties, and any terms relating to treatment of prepayment and partial payment of the C-PACER financing.

. "Program" means a C-PACER program established under this chapter.

. "Program administrator" means the party designated by a county or the department of commerce to administer a C-PACER program. This may be the department of commerce, the county itself, or a third party, provided that the administration procedures used conform to the requirements of this chapter.

. "Program guidebook" means a comprehensive document that illustrates the applicable region for a program and establishes any appropriate guidelines, specifications, underwriting and approval criteria, and any standard application forms consistent with the administration of a program and not detailed in this chapter.

. "Project application" means an application submitted to a program to demonstrate that a proposed project qualifies for C-PACER financing and for a C-PACER lien.

. "Qualified improvement" means a permanent improvement affixed to real property and intended to: (a) Decrease energy consumption or demand through the use of efficiency technologies, products, or activities that reduce or support the reduction of energy consumption, allow for the reduction in demand, or support the production of clean, renewable energy, including but not limited to a product, device, or interacting group of products or devices on the customer's side of the meter that generates electricity, provides thermal energy, or regulates temperature; (b) decrease water consumption or demand and address safe drinking water through the use of efficiency technologies, products, or activities that reduce or support the reduction of water consumption, allow for the reduction in demand, or reduce or eliminate lead from water which may be used for drinking or cooking; or (c) increase resilience, including but not limited to seismic retrofits, flood mitigation, stormwater management, wildfire and wind resistance, energy storage, and microgrids.

. "Qualified project" means a project approved by the program administrator, involving the installation or modification of a qualified improvement, including new construction or the adaptive reuse of eligible property with a qualified improvement.

. "Region" means a geographical area as determined by a county pursuant to RCW 36.165.030.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2405-S2.SL.pdf?cite=2020%20c%2027%20§%202[2020 c 27 § 2]; ]

== 36.165.020 - Voluntary statewide program—County participation—Program criteria, requirements, and administration.
. [Empty]
.. The department of commerce may establish a voluntary statewide C-PACER program that counties may choose to participate in. A county may establish a separate voluntary countywide C-PACER program, provided that it conforms to the requirements of this chapter.

.. A C-PACER program shall be managed efficiently and transparently, including by:

... Making any services that the program may choose to offer to property owners, such as estimating energy savings, overseeing project development, or evaluating alternative equipment installations, priced separately and open to purchase by the property owner from qualified third-party providers;

... Making any properties participating in the program available to receiving impartial terms from all interested and qualifying third-party capital providers;

... Allowing financial underwriting and evaluation to be performed by capital providers; and

... Working in a collaborative working group process with capital providers and other stakeholders to develop the program guidebook and any other relevant documents or forms.

. The program shall establish uniform criteria for which projects qualify due to their public benefit for participation in C-PACER programs including, but not limited to, criteria for measuring or determining if investments in energy will reduce greenhouse gas emissions; be effective for reducing energy demand or replacing nonrenewable energy with renewable energy; will be appropriate to meet seismic risks for each region of the state and type of structure; will reduce stormwater or pollution to be significant public benefit; or will reduce the risk of wildfire, flooding, or other natural or human-caused disaster, including how to determine if the public benefit in reduced public risk and emergency response qualifies for inclusion in C-PACER programs.

. The program must prepare a program guidebook that must include at minimum:

.. A sample form bilateral or triparty agreement or agreements, as appropriate, between a county, the property owner, and the capital provider which details the agreement between the county and the property owner to have an assessment placed on the qualified property as repayment for C-PACER financing; an agreement by the county to place a lien on the property to secure the obligation to repay; the obligation of the property owner to repay the C-PACER financing to the capital provider; and an assignment of the C-PACER lien by the county to the capital provider;

.. A statement that the period of the financing agreement will not exceed the useful life of the qualified project, or weighted average life if more than one qualified improvement is included in the qualified project, that is the basis for the financing agreement;

.. A description of the application process and eligibility requirements for participation in the program;

.. A statement explaining the lender consent requirement provided in RCW 36.165.070;

.. A statement explaining the review requirement provided by RCW 36.165.030;

.. A description of marketing and participant education services to be provided for the program;

.. A statement specifying that the county has no liability as a result of the agreement; and

.. A program guidebook need not be completed and adopted prior to accepting and approving applications by a program, so long as the program complies with the provisions of this chapter.

. The program administrator must make the program guidebook available for public inspection on the county's or department of commerce's website.

. A county or the department of commerce may contract out the responsibilities of program administration, including the responsibilities of this section, to a public, quasi-public, or private third-party entity.

. Any county program guidebook established prior to a statewide program may subsequently include or incorporate by reference any aspect of a statewide program guidebook; however, upon development of a statewide program guidebook with a form agreement or agreements developed pursuant to subsection (3)(a) of this section, the form agreement or agreements shall be required to be used by all county programs from the time that the first C-PACER lien is recorded under the statewide program, or the department of commerce may incorporate by reference any portion of any county program guidebooks, including a form agreement or agreements, as its program guidebook.

. The department of commerce may provide grants to counties to assist in the design and implementation of C-PACER programs under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2405-S2.SL.pdf?cite=2020%20c%2027%20§%203[2020 c 27 § 3]; ]

== 36.165.030 - Program application and review process.
. A program must establish a C-PACER application and review process to review and evaluate project applications for C-PACER financing, and prescribe the form and manner of the application. At a minimum, an applicant must demonstrate:

.. That the project provides a benefit to the public, in the form of energy or water resource conservation, reduced public health risk, or reduced public emergency response risk;

.. For an existing building: (i) Where energy or water usage improvements are proposed, certification by a licensed professional engineer, or other professional listed in the program guidebook, stating that the proposed qualified improvements will either result in more efficient use or conservation of energy or water, the reduction of greenhouse gas emissions, or the addition of renewable sources of energy or water, or (ii) where resilience improvements are proposed, certification by a licensed professional engineer stating that the qualified improvements will result in improved resilience;

.. For new construction, certification by a licensed professional engineer stating that the proposed qualified improvements will enable the project to exceed the energy efficiency or water efficiency or renewable energy or renewable water or resilience requirements of the current building code.

. The program may charge an application fee to cover the costs of establishing and conducting the application review process.

. Upon the denial of an application, the program administrator must provide an opportunity for an adjudicative proceeding subject to the applicable provisions of chapter 34.05 RCW.

. After an approved project is completed, an applicant must provide the program written verification, as defined in the program guidebook, stating that the qualified project was properly completed and is operating as intended.

. No later than one year after the governing body of a county establishes a program under this chapter, it must begin accepting applications and approving applications.

. The department of commerce may adopt rules to implement the voluntary statewide program.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2405-S2.SL.pdf?cite=2020%20c%2027%20§%204[2020 c 27 § 4]; ]

== 36.165.040 - Program adoption—County requirements.
. To adopt a program under this chapter, the governing body of a county must take the following actions:

.. Adopt a resolution or ordinance that includes:

... A statement that financing qualified projects, repaid by voluntary assessments on property benefited by C-PACER improvements, is in the public interest for safety, health, and other common good reasons;

... A description of the region in which the program is offered, which:

(A) May include the entire county, which may include both unincorporated and incorporated territory; and

(B) Must be located wholly within the county's jurisdiction; and

... A statement of the time and place for a public hearing on the proposed program; and

.. Hold a public hearing at which the public may comment on the proposed program.

. A county may designate more than one region. If multiple regions are designated, the regions may be separate, overlapping, or coterminous.

. The resolution or ordinance adopted by a county under this section may incorporate the department of commerce program guidebook or any amended versions of that program guidebook, as appropriate, by reference.

. A county adopting a C-PACER program pursuant to this chapter may narrow the definition of "qualified improvements" to be consistent with the county's climate goals.

. Any combination of counties may agree to jointly implement a program under this chapter. If two or more counties implement a program jointly, a single public hearing held jointly by the cooperating counties is sufficient to satisfy the requirements of this chapter.

. If a county elects to join the statewide program administered by the department of commerce, it may adopt a resolution or ordinance in accordance with the requirements of the department.

. In lieu of establishing a voluntary statewide program, the department of commerce may produce a program guidebook for reference and use by county programs.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2405-S2.SL.pdf?cite=2020%20c%2027%20§%205[2020 c 27 § 5]; ]

== 36.165.050 - Recording requirements.
. A county shall record each C-PACER lien in the real property records of the county in which the property is located. The lien and release shall be prepared in conformity with chapter 65.04 RCW.

. The recording under subsection (1) of this section must contain:

.. The legal description of the eligible property;

.. The assessor's parcel number of the property;

.. The grantor's name, which must be the same as the property owner on the assessment agreement;

.. The grantee's name, which must be the county in which the property is located;

.. The date on which the lien was created;

.. The principal amount of the lien;

.. The terms and length of the lien; and

.. A copy of the voluntary assessment agreement between the county and the property owner.

. The county shall also record the assignment of the C-PACER lien from the county to the appropriate capital provider.

. The lien holder or assignee will record a release upon discharge of the lien. The lien holder may also record a partial release.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2405-S2.SL.pdf?cite=2020%20c%2027%20§%206[2020 c 27 § 6]; ]

== 36.165.060 - C-PACER liens.
. The C-PACER lien amount plus any interest, penalties, and charges accrued or accruing on the C-PACER lien:

.. Takes precedence over all other liens or encumbrances except a lien for taxes imposed by the state, a local government, or a junior taxing district on real property, which liens for taxes shall have priority over such benefit C-PACER lien, provided existing mortgage holders, if any, have provided written consent described in RCW 36.165.070; and

.. Is a first and prior lien, second only to a lien for taxes imposed by the state, a local government, or a junior taxing district against the real property on which the C-PACER lien is imposed, from the date on which the notice of the C-PACER lien is recorded until the C-PACER lien, interest, penalties, and charges accrued or accruing are paid.

. The C-PACER lien runs with the land, and that portion of the C-PACER lien that has not yet become due is not accelerated or eliminated by foreclosure of the C-PACER lien or any lien for taxes imposed by the state, a local government, or junior taxing district against the real property on which the C-PACER lien is imposed.

. Delinquent installments due on a C-PACER lien incur interest and penalties as specified in the financing agreement.

. After the C-PACER lien is recorded as provided in this section, the voluntary assessment and the C-PACER lien may not be contested on the basis that the improvement is not a qualified improvement or that the project is not a qualified project.

. Collection and enforcement of delinquent C-PACER liens or C-PACER financing installment payments, including foreclosure, shall remain the responsibility of the capital provider.

. The C-PACER lien shall be enforced by the capital provider at any time after one year from the date of delinquency in the same manner that the collection of delinquent real property taxes is enforced by the county under chapter 84.64 RCW, including the provisions of RCW 84.64.040, excepting that a sworn declaration by the capital provider or assignee attesting to the assessment delinquency of at least one year shall be used in lieu of the certificate required under RCW 84.64.050.

. The capital provider may sell or assign, for consideration, any and all liens received from the participating county. The capital provider or their assignee shall have and possess the same powers and rights at law or in equity to enforce the C-PACER lien in the same manner as described in subsection (6) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2405-S2.SL.pdf?cite=2020%20c%2027%20§%207[2020 c 27 § 7]; ]

== 36.165.070 - Financing—Capital providers.
. Before a capital provider may enter into a financing agreement to provide C-PACER financing of a qualified project to a record owner of any eligible property, the capital provider must receive written consent from any holder of a lien, mortgage, or security interest in the real property that the property may participate in the program and that the C-PACER lien will take precedence over all other liens except for a lien for taxes as described in RCW 36.165.060.

. Before a capital provider may enter into a financing agreement to provide C-PACER financing of a qualified project to the record owner of any multifamily residential real property with five or more dwelling units, the program administrator must also receive written consent from any and all holders of affordable housing covenants, restrictions, or regulatory agreements in the real property that the property may participate in the program and that the C-PACER lien will take precedence over all other liens except for a lien for taxes as described in RCW 36.165.060.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2405-S2.SL.pdf?cite=2020%20c%2027%20§%208[2020 c 27 § 8]; ]

== 36.165.080 - Financing—Permitted inclusions.
The C-PACER financing through a program established under this chapter may include:

. The cost of materials and labor necessary for installation or modification of a qualified improvement;

. Permit fees;

. Inspection fees;

. Lender's fees;

. Program application and administrative fees;

. Project development and engineering fees;

. Third-party review fees, including verification review fees;

. Capitalized interest;

. Interest reserves;

. Escrow for prepaid property taxes and insurance; or

. Any other fees or costs that may be incurred by the property owner incident to the installation, modification, or improvement on a specific or pro rata basis.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2405-S2.SL.pdf?cite=2020%20c%2027%20§%209[2020 c 27 § 9]; ]

== 36.165.090 - Financing—Property owner authorizations.
The proposed C-PACER financing for a qualified project may authorize the property owner to:

. Purchase directly the related equipment and materials for the installation or modification of a qualified improvement; and

. Contract directly, including through lease, power purchase agreement, or other service contract, for the installation or modification of a qualified improvement.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2405-S2.SL.pdf?cite=2020%20c%2027%20§%2010[2020 c 27 § 10]; ]

== 36.165.100 - Prohibitions.
A county that adopts a program and designates a program region under this chapter may not:

. Make the issuance of a permit, license, or other authorization from the county to a person who owns property in the region contingent on the person entering into a written contract to repay the financing of a qualified project under this chapter; or

. Otherwise compel a person who owns property in the region to enter into a written contract to repay the financing of a qualified project under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2405-S2.SL.pdf?cite=2020%20c%2027%20§%2011[2020 c 27 § 11]; ]

== 36.165.105 - Exemptions from personal liability.
The members of the governing body of a county, employees of a county, and board members, executives, and employees under this chapter are not personally liable as a result of exercising any rights or responsibilities granted under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2405-S2.SL.pdf?cite=2020%20c%2027%20§%2012[2020 c 27 § 12]; ]

== 36.165.110 - Privately financed debt not enforceable by county.
A county may not enforce any privately financed debt under this chapter. Neither the state nor any county may use public funds to fund or repay any loan between a capital provider and property owner. No section under this chapter shall be interpreted to pledge, offer, or encumber the full faith and credit of a local government, nor shall any local government pledge, offer, or encumber its full faith and credit for any lien amount through a program.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2405-S2.SL.pdf?cite=2020%20c%2027%20§%2013[2020 c 27 § 13]; ]

