= 36.110 - Jail industries program.
:toc:

== 36.110.010 - Finding—Purpose, intent.
Cities and counties have a significant interest in ensuring that inmates in their jails are productive citizens after their release in the community. The legislature finds that there is an expressed need for cities and counties to uniformly develop and coordinate jail industries technical information and program and public safety standards statewide. It further finds that meaningful jail work industries programs that are linked to formal education and adult literacy training can significantly reduce recidivism, the rising costs of corrections, and criminal activities. It is the purpose and intent of the legislature, through this chapter, to establish a statewide jail industries program designed to promote inmate rehabilitation through meaningful work experience and reduce the costs of incarceration. The legislature recognizes that inmates should have the responsibility for contributing to the cost of their crime through the wages earned while working in jail industries programs and that such income shall be used to offset the costs of implementing and maintaining local jail industries programs and the costs of incarceration.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1033.SL.pdf?cite=1993%20c%20285%20§%201[1993 c 285 § 1]; ]

== 36.110.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Board" means the statewide jail industries board of directors.

. "City" means any city, town, or code city.

. "Cost accounting center" means a specific industry program operated under the private sector prison industry enhancement certification program as specified in 18 U.S.C. Sec. 1761.

. "Court-ordered legal financial obligation" means a sum of money that is ordered by a superior, district, or municipal court of the state of Washington for payment of restitution to a victim, a statutorily imposed crime victims compensation fee, court costs, a county or interlocal drug fund, court appointed attorneys' fees and costs of defense, fines, and other legal financial obligations that are assessed as a result of a felony or misdemeanor conviction.

. "Free venture employer model industries" means an agreement between a city or county and a private sector business or industry or nonprofit organization to produce goods or services to both public and private sectors utilizing jail inmates whose compensation and supervision are provided by the private sector business or entity.

"Free venture customer model industries" means an agreement between a city or county and a private sector business or industry, or nonprofit organization to provide Washington state manufacturers or businesses with products or services currently produced, provided, or assembled by out-of-state or foreign suppliers utilizing jail inmates whose compensation and supervision are provided by the incarcerating facility or local jurisdiction.

. "Jail inmate" means a preconviction or postconviction resident of a city or county jail who is determined to be eligible to participate in jail inmate work programs according to the eligibility criteria of the work program.

. "Private sector prison industry enhancement certification program" means that program authorized by the United States justice assistance act of 1984, 18 U.S.C. Sec. 1761.

. "Tax reduction industries" means those industries as designated by a city or county owning and operating such an industry to provide work training and employment opportunities for jail inmates, in total confinement, which reduce public support costs. The goods and services of these industries may be sold to public agencies, nonprofit organizations, and private contractors when the goods purchased will be ultimately used by a public agency or nonprofit organization. Surplus goods from these operations may be donated to government and nonprofit organizations.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1929-S.SL.pdf?cite=1995%20c%20154%20§%201[1995 c 154 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1033.SL.pdf?cite=1993%20c%20285%20§%202[1993 c 285 § 2]; ]

== 36.110.030 - Board of directors established—Membership.
A statewide jail industries board of directors is established. The board shall consist of the following members:

. One sheriff and one police chief, to be selected by the Washington association of sheriffs and police chiefs;

. One county commissioner or one county councilmember to be selected by the Washington state association of counties;

. One city official to be selected by the association of Washington cities;

. Two jail administrators to be selected by the Washington state jail association, one of whom shall be from a county or a city with an established jail industries program;

. One prosecuting attorney to be selected by the Washington association of prosecuting attorneys;

. One administrator from a city or county corrections department to be selected by the Washington correctional association;

. One county clerk to be selected by the Washington association of county clerks;

. Three representatives from labor to be selected by the governor. The representatives may be chosen from a list of nominations provided by statewide labor organizations representing a cross section of trade organizations;

. Three representatives from business to be selected by the governor. The representatives may be chosen from a list of nominations provided by statewide business organizations representing a cross section of businesses, industries, and all sizes of employers;

. The governor's representative from the employment security department;

. One member representing crime victims, to be selected by the governor;

. One member representing online law enforcement officers, to be selected by the governor;

. One member from the *department of community, trade, and economic development to be selected by the governor;

. One member representing higher education, vocational education, or adult basic education to be selected by the governor; and

. The governor's representative from the correctional industries division of the state department of corrections shall be an ex officio member for the purpose of coordination and cooperation between prison and jail industries and to further a positive relationship between state and local government offender programs.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%2045[1995 c 399 § 45]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1033.SL.pdf?cite=1993%20c%20285%20§%203[1993 c 285 § 3]; ]

== 36.110.050 - Local advisory groups.
The board shall require a city or a county that establishes a jail industries program to develop a local advisory group, or to use an existing advisory group of the appropriate composition, to advise and guide jail industries program operations. Such an advisory group shall include an equal number of representatives from labor and business. Representation from a sheltered workshop, as defined in RCW 82.04.385, and a crime victim advocacy group, if existing in the local area, should also be included.

A local advisory group shall have among its tasks the responsibility of ensuring that a jail industry has minimal negative impact on existing private industries or the labor force in the locale where the industry operates and that a jail industry does not negatively affect employment opportunities for people with developmental disabilities contracted through the operation of sheltered workshops as defined in RCW 82.04.385. In the event a conflict arises between the local business community or labor organizations concerning new jail industries programs, products, services, or wages, the city or county must use the arbitration process established pursuant to RCW 36.110.060.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1033.SL.pdf?cite=1993%20c%20285%20§%205[1993 c 285 § 5]; ]

== 36.110.060 - Board of directors—Duties.
The board, in accordance with chapter 34.05 RCW, shall:

. Establish an arbitration process for resolving conflicts arising among the local business community and labor organizations concerning new industries programs, products, services, or wages;

. Encourage the development of the collection and analysis of jail industries program data, including long-term tracking information on offender recidivism;

. Determine, by applying established federal guidelines and criteria, whether a city or a county jail free venture industries program complies with the private sector prison industry enhancement certification program. In so doing, also determine if that industry should be designated as a cost accounting center for the purposes of the federal certification program; and

. Provide technical assistance with product marketing.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1033.SL.pdf?cite=1993%20c%20285%20§%206[1993 c 285 § 6]; ]

== 36.110.070 - Board of directors may receive funds, establish fee schedule.
The board may receive funds from local, county, state, or federal sources and may receive grants to support its activities. The board may establish a reasonable schedule of suggested fees that will support statewide efforts to promote and facilitate jail industries that would be presented to cities and counties that have established jail industries programs.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1033.SL.pdf?cite=1993%20c%20285%20§%207[1993 c 285 § 7]; ]

== 36.110.080 - Board of directors—Meetings—Terms—Compensation.
The board shall initially convene at the call of the representative of the correctional industries division of the state department of corrections, together with the jail administrator selected from a city or a county with an established jail industries program, no later than six months after July 25, 1993. Subsequent meetings of the board shall be at the call of the board chairperson. The board shall meet at least twice a year.

The board shall elect a chairperson and other such officers as it deems appropriate. However, the chairperson may not be the representative of the correctional industries division of the state department of corrections nor any representative from a state executive branch agency.

Members of the board shall serve terms of three years each on a staggered schedule to be established by the first board. For purposes of initiating a staggered schedule of terms, some members of the first board may initially serve two years and some members may initially serve four years.

The members of the board shall serve without compensation but may be reimbursed for travel expenses from funds acquired under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1033.SL.pdf?cite=1993%20c%20285%20§%208[1993 c 285 § 8]; ]

== 36.110.085 - Board of directors—Immunity.
Any member serving in their official capacity on the Washington state jail industries board, in either an appointed or advisory capacity, or either their employer or employers, or other entity that selected the members to serve, are immune from a civil action based upon an act performed in good faith.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1929-S.SL.pdf?cite=1995%20c%20154%20§%205[1995 c 154 § 5]; ]

== 36.110.090 - City or county special revenue funds.
A city or a county that implements a jail industries program may establish a separate fund for the operation of the program. This fund shall be a special revenue fund with continuing authority to receive income and pay expenses associated with the jail industries program.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1033.SL.pdf?cite=1993%20c%20285%20§%209[1993 c 285 § 9]; ]

== 36.110.100 - Comprehensive work programs.
Cities and counties participating in jail industries are authorized to provide for comprehensive work programs using jail inmate workers at worksites within jail facilities or at such places within the city or county as may be directed by the legislative authority of the city or county, as similarly provided under RCW 36.28.100.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1033.SL.pdf?cite=1993%20c%20285%20§%2010[1993 c 285 § 10]; ]

== 36.110.110 - Deductions from offenders' earnings.
When an offender is employed in a jail industries program for which pay is allowed, deductions may be made from these earnings for court-ordered legal financial obligations as directed by the court in reasonable amounts that do not unduly discourage the incentive to work. These deductions shall be disbursed as directed in RCW 9.94A.760.

In addition, inmates working in jail industries programs shall contribute toward costs to develop, implement, and operate jail industries programs. This amount shall be a reasonable amount that does not unduly discourage the incentive to work. The amount so deducted shall be deposited in the jail industries special revenue fund.

Upon request of the offender, family support may also be deducted and disbursed to a designated family member.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1033.SL.pdf?cite=1993%20c%20285%20§%2011[1993 c 285 § 11]; ]

== 36.110.120 - Free venture industries, tax reduction industries—Employment status of inmates—Insurance coverage.
. A jail inmate who works in a free venture industry or a tax reduction industry shall be considered an employee of that industry only for the purpose of the Washington industrial safety and health act, chapter 49.17 RCW, as long as the public safety is not compromised, and for eligibility for industrial insurance benefits under Title 51 RCW, as provided in this section. 

. For jail inmates participating in free venture employer model industries, the private sector business or industry or the nonprofit organization that is party to the agreement, shall provide industrial insurance coverage under Title 51 RCW. Local jurisdictions shall not be responsible for obligations under Title 51 RCW in a free venture employer model industry except as provided in RCW 36.110.130.

. For jail inmates participating in free venture customer model industries, the incarcerating entity or jurisdiction, the private sector business or industry, or the nonprofit organization that is party to the agreement, shall provide industrial insurance coverage under Title 51 RCW dependent upon how the parties to the agreement choose to finalize the agreement.

. For jail inmates incarcerated and participating in tax reduction industries:

.. Local jurisdictions that are self-insured may elect to provide medical aid benefits coverage only under chapter 51.36 RCW through the state fund.

.. Local jurisdictions, to include self-insured jurisdictions, may elect to provide industrial insurance coverage under Title 51 RCW through the state fund.

. If industrial insurance coverage under Title 51 RCW is provided for inmates under this section, eligibility for benefits for either the inmate or the inmate's dependents or beneficiaries for temporary total disability or permanent total disability under RCW 51.32.090 or 51.32.060, respectively, shall not take effect until the inmate is discharged from custody by order of a court of appropriate jurisdiction. Nothing in this section shall be construed to confer eligibility for any industrial insurance benefits to any jail inmate who is not employed in a free venture industry or a tax reduction industry.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1929-S.SL.pdf?cite=1995%20c%20154%20§%202[1995 c 154 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1033.SL.pdf?cite=1993%20c%20285%20§%2012[1993 c 285 § 12]; ]

== 36.110.130 - Free venture industry agreements—Effect of failure.
In the event of a failure such as a bankruptcy or dissolution, of a private sector business, industry, or nonprofit organization engaged in a free venture industry agreement, responsibility for obligations under Title 51 RCW must be borne by the city or county responsible for establishment of the free venture industry agreement, as if the city or county had been the employing agency. To ensure that this obligation can be clearly identified and accomplished, and to provide accountability for purposes of the department of labor and industries, a free venture jail industry agreement entered into by a city or county and private sector business, industry, or nonprofit organization should be filed under a separate business license application in accordance with chapter 19.02 RCW, establishing a new and separate account with the department of labor and industries, and not be reported under an existing account for parties to the free venture industry agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1568-S.SL.pdf?cite=2013%20c%20144%20§%2038[2013 c 144 § 38]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1929-S.SL.pdf?cite=1995%20c%20154%20§%203[1995 c 154 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1033.SL.pdf?cite=1993%20c%20285%20§%2013[1993 c 285 § 13]; ]

== 36.110.140 - Education and training.
To the extent possible, jail industries programs shall be augmented by education and training to improve worker literacy and employability skills. Such education and training may include, but is not limited to, basic adult education, work towards earning a high school equivalency certificate as provided in RCW 28B.50.536, vocational and preemployment work maturity skills training, and apprenticeship classes.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1686-S.SL.pdf?cite=2013%20c%2039%20§%2018[2013 c 39 § 18]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1033.SL.pdf?cite=1993%20c%20285%20§%2014[1993 c 285 § 14]; ]

== 36.110.150 - Department of corrections to provide staff assistance.
Until sufficient funding is secured by the board to adequately provide staffing, basic staff assistance shall be provided, to the extent possible, by the department of corrections.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1033.SL.pdf?cite=1993%20c%20285%20§%2015[1993 c 285 § 15]; ]

== 36.110.160 - Technical training assistance.
Technical training assistance shall be provided to local jurisdictions by the board at the jurisdiction's request. To facilitate and promote the development of local jail industries programs, this training and technical assistance may include the following: (1) Delivery of statewide jail industry implementation workshops for administrators of jail industries programs; (2) development of recruitment and education programs for local business and labor to gain their participation; (3) ongoing staff assistance regarding local jail industries issues, such as sound business management skills, development of a professional business plan, responding to questions regarding risk management, industrial insurance, and similar matters; and (4) provision of guidelines and assistance for the coordination of basic educational programs and jail industries as well as other technical skills required by local jails in the implementation of safe, productive, and effective jail industries programs.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1929-S.SL.pdf?cite=1995%20c%20154%20§%204[1995 c 154 § 4]; ]

