= 36.140 - Electricity generation from biomass energy.
:toc:

== 36.140.010 - Generation of electricity from biomass energy.
. Any county legislative authority of a county where a public utility district owns and operates a plant or system for the generation, transmission, and distribution of electric energy for sale within the county may construct, purchase, acquire, operate, and maintain one facility within the county to generate electricity from biomass energy that is a renewable resource under RCW 19.285.030 or from biomass energy that is produced from lignin in spent pulping liquors or liquors derived from algae and other sources. The county legislative authority has the authority to regulate and control the use, distribution, sale, and price of the electricity produced from the biomass facility authorized under this section.

. For the purposes of this section:

.. "County legislative authority" means the board of county commissioners or the county council; 

.. "Plant" means a natural gas-fueled, combined-cycle combustion turbine capable of generating at least two hundred forty megawatts of electricity; and

.. "Public utility district" means a municipal corporation formed under chapter 54.08 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6692-S.SL.pdf?cite=2010%20c%20167%20ยง%201[2010 c 167 ยง 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5724-S.SL.pdf?cite=2009%20c%20281%20ยง%201[2009 c 281 ยง 1]; ]

