= 36.135 - Local public works assistance funds.
:toc:

== 36.135.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Capital facilities plan" means a capital facilities plan required under chapter 36.70A RCW.

. "Local government" means cities, towns, counties, special purpose districts, and any other municipal corporations or quasi-municipal corporations in the state, excluding school districts and port districts.

. "Public works project" means a project of a local government for the planning, acquisition, construction, repair, reconstruction, replacement, rehabilitation, or improvement of streets and roads, bridges, water systems, or storm and sanitary sewage systems and solid waste facilities, including recycling facilities.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1569.SL.pdf?cite=2009%20c%2045%20§%201[2009 c 45 § 1]; ]

== 36.135.020 - Use—Distribution.
. County legislative authorities may establish local public works assistance funds for the purpose of funding public works projects located wholly or partially within the county. Moneys may be deposited in local public works assistance funds from existing revenue sources of the county.

. Moneys deposited in local public works assistance funds, and interest earned on balances from the funds, may only be used:

.. To make loans to the county and to other local governments for funding public works projects as provided in this chapter; and

.. For costs incurred in the administration of funds.

. No more than fifty percent of the moneys loaned from a fund in a calendar year may be loaned to the county providing local public works assistance funds. At least twenty-five percent of the moneys anticipated to be loaned from a fund in a calendar year must be made available for funding public works projects in cities or towns.

. No more than one percent of the average annual balance of a county's fund, including interest earned on balances from the fund, may be used annually for administrative costs.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1569.SL.pdf?cite=2009%20c%2045%20§%202[2009 c 45 § 2]; ]

== 36.135.030 - Public works projects—Financial assistance for local governments.
. Counties, in consultation with cities and towns within the county, may make loans to local governments from funds established under RCW 36.135.020 for the purpose of assisting local governments in funding public works projects. Counties may require terms and conditions and may charge rates of interest on its loans as they deem necessary or convenient to carry out the purposes of this chapter. Counties may not pledge any amount greater than the sum of money in their local public works assistance fund plus money to be received from the payment of the debt service on loans made from that fund. Money received from local governments in repayment of loans made under this chapter must be paid into the fund of the lending county for uses consistent with this chapter.

. Prior to receiving moneys from a fund established under RCW 36.135.020, a local government applying for financial assistance under this chapter must demonstrate to the lending county:

.. Utilization of all local revenue sources that are reasonably available for funding public works projects;

.. Compliance with applicable requirements of chapter 36.70A RCW; and

.. Consistency between the proposed project and applicable capital facilities plans.

. Counties may not make loans under this chapter prior to completing the initial collaboration and prioritization requirements of RCW 36.135.040(1).

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1569.SL.pdf?cite=2009%20c%2045%20§%203[2009 c 45 § 3]; ]

== 36.135.040 - Public works projects—Prioritization process.
. County legislative authorities utilizing or providing money under this chapter must develop a prioritization process for funding public works projects that gives priority to projects necessary to address public health needs, substantial environmental degradation, or increases existing capacity necessary to accommodate projected population and employment growth. This prioritization process must be:

.. Completed collaboratively with public works directors of local governments within the county;

.. Documented in the form of written findings produced by the county; and

.. Revised periodically according to a schedule developed by the county and the public works directors.

. In addition to the requirements under subsection (1) of this section, legislative authorities providing funding to other local governments under this chapter must consider, through a competitive application process, the following factors in assigning a priority to and funding a project:

.. Whether the local government applying for assistance has experienced severe fiscal distress resulting from natural disaster or emergency public works needs;

.. Whether the project is critical in nature and would affect the health and safety of a great number of citizens;

.. The cost of the project compared to the size of the local government and amount of loan money available;

.. The number of communities served by or funding the project;

.. Whether the project is the acquisition, expansion, improvement, or renovation by a local government of a public water system that is in violation of health and safety standards;

.. The number of additional housing units estimated to be achieved by funding the project;

.. The additional jobs estimated to be achieved by funding the project; and

.. Other criteria the county legislative authority deems appropriate.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1569.SL.pdf?cite=2009%20c%2045%20§%204[2009 c 45 § 4]; ]

== 36.135.050 - Records of accounts—Audit.
County legislative authorities providing funding for public works projects under this chapter must keep proper records of accounts and are subject to audit by the state auditor.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1569.SL.pdf?cite=2009%20c%2045%20§%205[2009 c 45 § 5]; ]

