= 49.08 - Arbitration of disputes.
:toc:

== 49.08.010 - Duty of director—Mediation—Board of arbitration selected—Board's findings final.
It shall be the duty of the chair of the public employment relations commission upon application of any employer or employee having differences, as soon as practicable, to visit the location of such differences and to make a careful inquiry into the cause thereof and to advise the respective parties, what, if anything, ought to be done or submitted to by both to adjust said dispute and should said parties then still fail to agree to a settlement through said chair, then said chair shall endeavor to have said parties consent in writing to submit their differences to a board of arbitrations to be chosen from citizens of the state as follows, to wit: Said employer shall appoint one and said employees acting through a majority, one, and these two shall select a third, these three to constitute the board of arbitration and the findings of said board of arbitration to be final.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%2012001[2010 c 8 § 12001]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c296.pdf?cite=1975%201st%20ex.s.%20c%20296%20§%2036[1975 1st ex.s. c 296 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c58.pdf?cite=1903%20c%2058%20§%201[1903 c 58 § 1]; RRS § 7667; ]

== 49.08.020 - Procedure for arbitration.
The proceedings of said board of arbitration shall be held before the chair of the public employment relations commission who shall act as moderator or chair, without the privilege of voting, and who shall keep a record of the proceedings, issue subpoenas and administer oaths to the members of said board, and any witness said board may deem necessary to summon.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%2012002[2010 c 8 § 12002]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c296.pdf?cite=1975%201st%20ex.s.%20c%20296%20§%2037[1975 1st ex.s. c 296 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c58.pdf?cite=1903%20c%2058%20§%202[1903 c 58 § 2]; RRS § 7668; ]

== 49.08.030 - Service of process.
Any notice or process issued by the board herein created, shall be served by any sheriff, coroner or constable to whom the same may be directed, or in whose hands the same may be placed for service.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c58.pdf?cite=1903%20c%2058%20§%203[1903 c 58 § 3]; RRS § 7669; ]

== 49.08.040 - Compensation and travel expenses of arbitrators.
Such arbitrators shall receive five dollars per day for each day actually engaged in such arbitration and travel expenses in accordance with RCW 43.03.050 and 43.03.060 as now existing or hereafter amended to be paid upon certificates of the director of labor and industries out of the fund appropriated for the purpose or at the disposal of the department of labor and industries applicable to such expenditure.

[ 1975-'76 2nd ex.s. c 34 § 144; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c58.pdf?cite=1903%20c%2058%20§%204[1903 c 58 § 4]; RRS § 7670; ]

== 49.08.050 - Failure to arbitrate—Statement of facts—Publicity.
Upon the failure of the director of labor and industries, in any case, to secure the creation of a board of arbitration, it shall become his or her duty to request a sworn statement from each party to the dispute of the facts upon which their dispute and their reasons for not submitting the same to arbitration are based. Any sworn statement made to the director of labor and industries under this provision shall be for public use and shall be given publicly in such newspapers as desire to use it.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%2012003[2010 c 8 § 12003]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c58.pdf?cite=1903%20c%2058%20§%205[1903 c 58 § 5]; RRS § 7671; ]

== 49.08.060 - Tender on exhaustion of available funds.
There is hereby appropriated out of the state treasury from funds not otherwise appropriated the sum of three thousand dollars, or so much thereof as may be necessary, to carry out the provisions of this chapter. In case the funds herein provided are exhausted and either party to a proposed arbitration shall tender the necessary expenses for conducting said arbitration, then it shall be the duty of the director of labor and industries to request the opposite party to arbitrate such differences in accordance with the provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c58.pdf?cite=1903%20c%2058%20§%206[1903 c 58 § 6]; RRS § 7672; ]

