= 49.19 - Safety—Health care settings.
:toc:

== 49.19.005 - Findings—1999 c 377.
The legislature finds that:

. Violence is an escalating problem in many health care settings in this state and across the nation;

. Based on an analysis of workers' compensation claims, the department of labor and industries reports that health care employees face the highest rate of workplace violence in Washington state;

. The actual incidence of workplace violence in health care settings is likely to be greater than documented because of failure to report or failure to maintain records of incidents that are reported;

. Patients, visitors, and health care employees should be assured a reasonably safe and secure environment in health care settings; and

. Many health care settings have undertaken efforts to assure that patients, visitors, and employees are safe from violence, but additional personnel training and appropriate safeguards may be needed to prevent workplace violence and minimize the risk and dangers affecting people in health care settings.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5312-S.SL.pdf?cite=1999%20c%20377%20§%201[1999 c 377 § 1]; ]

== 49.19.010 - Definitions.
For purposes of this chapter:

. "Health care setting" means:

.. Hospitals as defined in RCW 70.41.020;

.. Home health, hospice, and home care agencies under chapter 70.127 RCW, subject to RCW 49.19.070;

.. Evaluation and treatment facilities as defined in RCW 71.05.020;

.. Behavioral health programs as defined in RCW 71.24.025; and

.. Ambulatory surgical facilities as defined in RCW 70.230.010.

. "Department" means the department of labor and industries.

. "Employee" means an employee as defined in RCW 49.17.020.

. "Workplace violence," "violence," or "violent act" means any physical assault or verbal threat of physical assault against an employee of a health care setting on the property of the health care setting. "Workplace violence," "violence," or "violent act" includes any physical assault or verbal threat of physical assault involving the use of a weapon, including a firearm as defined in RCW 9.41.010, or a common object used as a weapon, regardless of whether the use of a weapon resulted in an injury.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1931-S.SL.pdf?cite=2019%20c%20430%20§%201[2019 c 430 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1217.SL.pdf?cite=2007%20c%20414%20§%203[2007 c 414 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5533-S.SL.pdf?cite=2007%20c%20375%20§%2010[2007 c 375 § 10]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2520.SL.pdf?cite=2000%20c%2094%20§%2018[2000 c 94 § 18]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5312-S.SL.pdf?cite=1999%20c%20377%20§%202[1999 c 377 § 2]; ]

== 49.19.020 - Workplace violence plan—Security and safety assessment.
. Every three years, each health care setting shall develop and implement a plan to prevent and protect employees from violence at the setting. In a health care setting with a safety committee established pursuant to RCW 49.17.050 and related rules, or workplace violence committee that is comprised of employee-elected and employer-selected members where the number of employee-elected members equal or exceed the number of employer-selected members, that committee shall develop, implement, and monitor progress on the plan.

. The plan developed under subsection (1) of this section shall outline strategies aimed at addressing security considerations and factors that may contribute to or prevent the risk of violence, including but not limited to the following:

.. The physical attributes of the health care setting, including security systems, alarms, emergency response, and security personnel available;

.. Staffing, including staffing patterns, patient classifications, and procedures to mitigate employees time spent alone working in areas at high risk for workplace violence;

.. Job design, equipment, and facilities;

.. First aid and emergency procedures;

.. The reporting of violent acts;

.. Employee education and training requirements and implementation strategy;

.. Security risks associated with specific units, areas of the facility with uncontrolled access, late night or early morning shifts, and employee security in areas surrounding the facility such as employee parking areas; and

.. Processes and expected interventions to provide assistance to an employee directly affected by a violent act.

. Each health care setting shall annually review the frequency of incidents of workplace violence including identification of the causes for and consequences of, violent acts at the setting and any emerging issues that contribute to workplace violence. The health care setting shall adjust the plan developed under subsection (1) of this section as necessary based on this annual review.

. In developing the plan required by subsection (1) of this section, the health care setting shall consider any guidelines on violence in the workplace or in health care settings issued by the department of health, the department of social and health services, the department of labor and industries, the federal occupational safety and health administration, medicare, and health care setting accrediting organizations.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1931-S.SL.pdf?cite=2019%20c%20430%20§%202[2019 c 430 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5312-S.SL.pdf?cite=1999%20c%20377%20§%203[1999 c 377 § 3]; ]

== 49.19.030 - Violence prevention training.
. By July 1, 2020, and on a regular basis thereafter, as set forth in the plan developed under RCW 49.19.020, each health care setting shall provide violence prevention training to all applicable employees, volunteers, and contracted security personnel, as determined by the plan.

. The training shall occur within ninety days of the employee's initial hiring date unless he or she is a temporary employee.

. The method and frequency of training may vary according to the information and strategies identified in the plan developed under RCW 49.19.020. Trainings may include, but are not limited to, classes that provide an opportunity for interactive questions and answers, hands on training, video training, brochures, verbal training, or other verbal or written training that is determined to be appropriate under the plan. Trainings must address the following topics, as appropriate to the particular setting and to the duties and responsibilities of the particular employee being trained, based upon the hazards identified in the plan required under RCW 49.19.020:

.. The health care setting's workplace violence prevention plan;

.. General safety procedures;

.. Violence predicting behaviors and factors;

.. The violence escalation cycle;

.. De-escalation techniques to minimize violent behavior;

.. Strategies to prevent physical harm with hands-on practice or role play;

.. Response team processes;

.. Proper application and use of restraints, both physical and chemical restraints;

.. Documentation and reporting incidents;

.. The debrief process for affected employees following violent acts; and

.. Resources available to employees for coping with the effects of violence.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1931-S.SL.pdf?cite=2019%20c%20430%20§%203[2019 c 430 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5312-S.SL.pdf?cite=1999%20c%20377%20§%204[1999 c 377 § 4]; ]

== 49.19.040 - Violent acts—Records.
Each health care setting shall keep a record of any violent act against an employee, a patient, or a visitor occurring at the setting. Each record shall be kept for at least five years following the act reported, during which time it shall be available for inspection by the department upon request. At a minimum, the record shall include:

. The health care setting's name and address;

. The date, time, and specific location at the health care setting where the act occurred;

. The name, job title, department or ward assignment, and staff identification or social security number of the victim if an employee;

. A description of the person against whom the act was committed as:

.. A patient;

.. A visitor;

.. An employee; or

.. Other;

. A description of the person committing the act as:

.. A patient;

.. A visitor;

.. An employee; or

.. Other;

. A description of the type of violent act as a:

.. Threat of assault with no physical contact;

.. Physical assault with contact but no physical injury;

.. Physical assault with mild soreness, surface abrasions, scratches, or small bruises;

.. Physical assault with major soreness, cuts, or large bruises;

.. Physical assault with severe lacerations, a bone fracture, or a head injury; or

.. Physical assault with loss of limb or death;

. An identification of any body part injured;

. A description of any weapon used;

. The number of employees in the vicinity of the act when it occurred; and

. A description of actions taken by employees and the health care setting in response to the act.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1931-S.SL.pdf?cite=2019%20c%20430%20§%204[2019 c 430 § 4]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5312-S.SL.pdf?cite=1999%20c%20377%20§%205[1999 c 377 § 5]; ]

== 49.19.050 - Noncompliance—Penalties.
Failure of a health care setting to comply with this chapter shall subject the setting to citation under chapter 49.17 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5312-S.SL.pdf?cite=1999%20c%20377%20§%206[1999 c 377 § 6]; ]

== 49.19.060 - Health care setting—Assistance.
A health care setting needing assistance to comply with this chapter may contact the federal department of labor or the state department of labor and industries for assistance. The state departments of labor and industries, social and health services, and health shall collaborate with representatives of health care settings to develop technical assistance and training seminars on plan development and implementation, and shall coordinate their assistance to health care settings.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5312-S.SL.pdf?cite=1999%20c%20377%20§%207[1999 c 377 § 7]; ]

== 49.19.070 - Intent—Finding—Enforcement.
It is the intent of the legislature that any violence protection and prevention plan developed under this chapter be appropriate to the setting in which it is to be implemented. To that end, the legislature recognizes that not all professional health care is provided in a facility or other formal setting, such as a hospital. Many services are provided by home health, hospice, and home care agencies. The legislature finds that it is inappropriate and impractical for these agencies to address workplace violence in the same manner as other, facility-based, health care settings. When enforcing this chapter as to home health, hospice, and home care agencies, the department shall allow agencies sufficient flexibility in recognition of the unique circumstances in which these agencies deliver services.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5312-S.SL.pdf?cite=1999%20c%20377%20§%208[1999 c 377 § 8]; ]

