= 49.22 - Safety—Crime prevention.
:toc:

== 49.22.010 - Definitions.
As used in this chapter, the following terms have the meanings indicated unless the context clearly requires otherwise.

. "Department" means the department of labor and industries.

. "Late night retail establishment" means any business or commercial establishment making sales to the public between the hours of eleven o'clock p.m. and six o'clock a.m., except restaurants, hotels, taverns, or any lodging facility.

. "Employer" means the operator, lessee, or franchisee of a late night retail establishment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c357.pdf?cite=1989%20c%20357%20§%201[1989 c 357 § 1]; ]

== 49.22.020 - Late night retail establishments—Duties.
In addition to providing crime prevention training as provided in *section 2 of this act, all employers operating late night retail establishments shall:

. Post a conspicuous sign in the window or door which states that there is a safe on the premises and it is not accessible to the employees on the premises and that the cash register contains only the minimal amount of cash needed to conduct business: PROVIDED, That an employer shall not be subject to penalties under RCW 49.22.030 for having moneys in the cash register in excess of the minimal amount needed to conduct business;

. So arrange all material posted in the window or door so as to provide a clear and unobstructed view of the cash register, provided the cash register is otherwise in a position visible from the street;

. Have a drop-safe, limited access safe, or comparable device on the premises; and

. Operate the outside lights for that portion of the parking area that is necessary to accommodate customers during all night hours the late night retail establishment is open, if the late night retail establishment has a parking area for its customers.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c357.pdf?cite=1989%20c%20357%20§%203[1989 c 357 § 3]; ]

== 49.22.030 - Enforcement.
The requirements of this chapter shall be implemented and enforced, including rules, citations, violations, penalties, appeals, and other administrative procedures by the director of the department of labor and industries pursuant to the Washington industrial safety and health act of 1973, chapter 49.17 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c357.pdf?cite=1989%20c%20357%20§%204[1989 c 357 § 4]; ]

== 49.22.900 - Effective date—Implementation—1989 c 357.
This act shall take effect January 1, 1990. The director of the department of labor and industries may immediately take such steps as are necessary to ensure that this act is implemented on its effective date.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c357.pdf?cite=1989%20c%20357%20§%207[1989 c 357 § 7]; ]

