= 49.24 - Health and safety—Underground workers.
:toc:

== 49.24.010 - Pressure defined.
The term "pressure" means gauge air pressure in pounds per square inch.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c131.pdf?cite=1937%20c%20131%20§%201[1937 c 131 § 1]; RRS § 7666-1; ]

== 49.24.020 - Compressed air safety requirements.
Every employer of persons for work in compressed air shall:

. Connect at least two air pipes with the working chamber and keep such pipes in perfect working condition;

. Attach to the working chamber in accessible positions all instruments necessary to show its pressure and keep such instruments in charge of competent persons, with a period of duty for each such person not exceeding six hours in any twenty-four;

. Place in each shaft a safe ladder extending its entire length;

. Light properly and keep clear such passageway;

. Provide independent lighting systems for the working chamber and shaft leading to it, when electricity is used for lighting;

. Guard lights other than electric lights;

. Protect workers by a shield erected in the working chamber when such chamber is less than ten feet long and is suspended with more than nine feet space between its deck and the bottom of the excavation;

. Provide for and keep accessible to employees working in compressed air a dressing room heated, lighted and ventilated properly and supplied with benches, lockers, sanitary waterclosets, bathing facilities, and hot and cold water;

. Establish and maintain a medical lock properly heated, lighted, ventilated, and supplied with medicines and surgical implements, when the maximum air pressure exceeds seventeen pounds.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%2012021[2010 c 8 § 12021]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c131.pdf?cite=1937%20c%20131%20§%202[1937 c 131 § 2]; RRS § 7666-2; ]

== 49.24.030 - Medical and nursing attendants.
Every employer of persons for work in compressed air shall:

. Keep at the place of work at all necessary times a duly qualified medical officer to care for cases of illness and to administer strictly and enforce RCW 49.24.020 and 49.24.040;

. Keep at a medical lock required by RCW 49.24.020(9) a certified nurse selected by the medical officer required by subdivision (1) of this section and qualified to give temporary relief in cases of illness.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c131.pdf?cite=1937%20c%20131%20§%203[1937 c 131 § 3]; RRS § 7666-3; ]

== 49.24.040 - Examination as to physical fitness.
If an employee is a new employee, an absentee for ten or more successive days, an employee who has worked in compressed air continuously for three months or a beginner in compressed air who has worked but a single shift as required by *RCW 49.24.050, the officer required by RCW 49.24.030(1) shall examine him or her and declare him or her physically fit to work in compressed air before permitting him or her to enter or reenter the working chamber. Excessive users of intoxicants shall not be permitted to work in compressed air.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%2012022[2010 c 8 § 12022]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c131.pdf?cite=1937%20c%20131%20§%204[1937 c 131 § 4]; RRS § 7666-4; ]

== 49.24.060 - Penalty.
Violation of or noncompliance with any provision of *this article by any employer, manager, superintendent, foreman or other person having direction or control of such work shall be a gross misdemeanor punishable by a fine of not less than two hundred and fifty dollars or by imprisonment for up to three hundred sixty-four days or by both such fine and imprisonment.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5168-S.SL.pdf?cite=2011%20c%2096%20§%2041[2011 c 96 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c131.pdf?cite=1937%20c%20131%20§%207[1937 c 131 § 7]; RRS § 7666-7; ]

== 49.24.070 - Enforcement.
The director of labor and industries shall have the power and it shall be the director's duty to enforce the provisions of RCW 49.24.010 through 49.24.070. Any authorized inspector or agent of the department may issue and serve upon the employer or person in charge of such work, an order requiring compliance with a special provision or specific provisions of RCW 49.24.010 through 49.24.070 and directing the discontinuance of any employment of persons in compressed air in connection with such work until such specific provision or provisions have been complied with by such employer to the satisfaction of the department.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2390.SL.pdf?cite=1994%20c%20164%20§%2023[1994 c 164 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c52.pdf?cite=1973%201st%20ex.s.%20c%2052%20§%207[1973 1st ex.s. c 52 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c131.pdf?cite=1937%20c%20131%20§%208[1937 c 131 § 8]; RRS § 7666-8; ]

== 49.24.080 - Requirements for underground labor.
Every person, firm or corporation constructing, building or operating a tunnel, quarry, caisson or subway, excepting in connection with mines, with or without compressed air, shall in the employment of any labor comply with the following safety provisions:

. A safety miner shall be selected by the crew on each shift who shall check the conditions necessary to make the working place safe; such as loose rock, faulty timbers, poor rails, lights, ladders, scaffolds, fan pipes and firing lines.

. Ventilating fans shall be installed from twenty-five to one hundred feet outside the portal.

. No employee shall be allowed to "bar down" without the assistance of another employee.

. No employee shall be permitted to return to the heading until at least thirty minutes after blasting.

. Whenever persons are employed in wet places, the employer shall furnish such persons with rubbers, boots, coats and hats. All boots if worn previously by an employee shall be sterilized before being furnished to another: PROVIDED, That RCW 49.24.080 through 49.24.380 shall not apply to the operation of a railroad except that new construction of tunnels, caissons or subways in connection therewith shall be subject to the provisions of RCW 49.24.080 through 49.24.380: PROVIDED, FURTHER, That in the event of repair work being done in a railroad tunnel, no person shall be compelled to perform labor until the air has been cleared of smoke, gas and fumes.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c154.pdf?cite=1973%201st%20ex.s.%20c%20154%20§%2089[1973 1st ex.s. c 154 § 89]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c144.pdf?cite=1965%20c%20144%20§%201[1965 c 144 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%201[1941 c 194 § 1]; Rem. Supp. 1941 § 7666-9; ]

== 49.24.100 - Lighting appliances.
. All lighting in compressed air chambers shall be by electricity only. Wherever practicable there shall be two independent lighting systems with independent sources of supply.

. The exterior of all lamp sockets shall be entirely nonmetallic.

. All portable incandescent lamps used shall be guarded by a wire cage large enough to enclose both lamp and socket.

. All incandescent lamps shall be so placed that they cannot come in contact with any combustible material.

. Only heavy insulated or armored wire shall be used for light or power.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%203[1941 c 194 § 3]; Rem. Supp. 1941 § 7666-11; ]

== 49.24.110 - Exhaust valves.
Exhaust valves shall be provided, having risers extending to the upper part of chamber, if necessary, and shall be operated at such times as may be required and especially after a blast, and persons shall not be required to resume work after a blast until the gas and smoke have cleared, for at least thirty minutes.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c154.pdf?cite=1973%201st%20ex.s.%20c%20154%20§%2090[1973 1st ex.s. c 154 § 90]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%204[1941 c 194 § 4]; Rem. Supp. 1941 § 7666-12; ]

== 49.24.120 - Fire prevention.
All reasonable precaution shall be taken against fire, and provisions shall be made so that water lines shall be available for use at all times. Fire hose connections with hose connected shall be installed in all power plants and work houses. There shall be fire hose connections within reasonable distance of all caissons. Fire hose shall be connected at either side of a tunnel bulkhead, with at least fifty feet of hose with nozzle connection. Water lines shall extend into each tunnel with hose connections every two hundred feet and shall be kept ready for use at all times.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%205[1941 c 194 § 5]; Rem. Supp. 1941 § 7666-13; ]

== 49.24.130 - Air chambers—Hanging walks.
. Whenever the air pressure in a tunnel heading exceeds twenty-one pounds per square inch above atmospheric pressure, two air chambers shall always be in use, except for such time as may be necessary when headings are being started from shafts; and whenever practicable the pressure in the outer chamber shall not exceed one-half the pressure in the heading;

. In all tunnels sixteen feet in diameter or over, hanging walks shall be provided from working face to nearest lock. An overhead clearance of six feet shall be maintained and suitable ramps provided under all safety screens.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%206[1941 c 194 § 6]; Rem. Supp. 1941 § 7666-14; ]

== 49.24.140 - Locks.
. Each bulkhead in tunnels of twelve feet or more in diameter or equivalent area, shall have at least two locks in perfect working condition, one of which shall be used as an air lock. An additional lock for use in case of emergency shall be held in reserve.

. The air lock shall be large enough so that those using it are not compelled to be in a cramped position, and shall not be less than five feet in height. Emergency locks shall be large enough to hold an entire heading shift.

. All locks used for decompression shall be lighted by electricity and shall contain a pressure gauge, a time piece, a glass "bull's eye" in each door or in each end, and shall also have facilities for heating.

. Valves shall be so arranged that the locks can be operated both from within and from without.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%201013[2009 c 549 § 1013]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%207[1941 c 194 § 7]; Rem. Supp. 1941 § 7666-15; ]

== 49.24.150 - Explosives and detonators.
When locking explosives and detonators into the air chamber, they shall be kept at opposite ends of the lock. While explosives and detonators are being taken through, no persons other than the lock tender and the carriers shall be permitted in the lock.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%201014[2009 c 549 § 1014]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%208[1941 c 194 § 8]; Rem. Supp. 1941 § 7666-16; ]

== 49.24.160 - Air plant—Feed water.
. A good and sufficient air plant for the compression of air shall be provided to meet not only ordinary conditions, but emergencies, and to provide margin for repairs at all times. Provision must be made for storing in tanks at each boiler house enough feed water for twelve hours' supply unless connection can be made with two independent and separately sufficient sources of supply.

. The plant shall be capable of furnishing to each working chamber a sufficient air supply for all pressure to enable work to be done.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%209[1941 c 194 § 9]; Rem. Supp. 1941 § 7666-17; ]

== 49.24.170 - Electric power requirements.
When electric power is used for running compressors supplying air for compressed air tunnel work and such power is purchased from a local central station or power company—

. There shall be two or more sources of power from the power company's stations to the compressor plant. Such power feeders shall each have a capacity large enough to carry the entire compressor plant load and normal overload. The feeders shall preferably run from separate generating plants or substations and be carried to the compressor plant over separate routes and not through the same duct lines and manholes so that the breakdown of one feeder shall not cause an interruption on the other feeder.

. There shall be duplicate feeder bus-bars, and feeder connections to the bus-bars shall be such that either feeder can feed to each separate bus-bar set, individually, or simultaneously to both sets.

. There shall be at least two compressors so connected to the bus-bars that they can be operated from either set of buses. The compressors shall be fed from different bus-bar sets, in such a way that a breakdown of a feeder or bus-bar would interrupt the operation of only part of the compressor plant.

. Duplicate air feed pipes shall be provided from the compressor plant to a point beyond the lock.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%2010[1941 c 194 § 10]; Rem. Supp. 1941 § 7666-18; ]

== 49.24.180 - Inspection.
While work is in progress, the employer shall employ a competent person who shall make a regular inspection at least once every working day of all engines, boilers, steam pipes, drills, air pipes, air gauges, air locks, dynamos, electric wiring, signaling apparatus, brakes, cages, buckets, hoists, cables, ropes, timbers, supports, and all other apparatus and appliances; and he or she shall immediately upon discovery of any defect, report same in writing to the employer, or his or her agent in charge.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%2012023[2010 c 8 § 12023]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%2011[1941 c 194 § 11]; Rem. Supp. 1941 § 7666-19; ]

== 49.24.190 - Cars, cages, buckets—Employees riding or walking.
No employee shall ride on any loaded car, cage, or bucket, nor walk up or down any incline or shaft while any car, cage, or bucket is above him or her.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%2012024[2010 c 8 § 12024]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%2012[1941 c 194 § 12]; Rem. Supp. 1941 § 7666-20; ]

== 49.24.200 - Speed of vehicles.
No vehicle shall be operated underground at a speed greater than five miles an hour, while construction work is going on.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%2013[1941 c 194 § 13]; Rem. Supp. 1941 § 7666-21; ]

== 49.24.210 - Oil supply restricted.
Oil for illumination or power shall not be taken into the underground workings of any tunnel or kept therein in greater quantities than one day's supply.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%2014[1941 c 194 § 14]; Rem. Supp. 1941 § 7666-22; ]

== 49.24.220 - Explosives, use of—Blasting.
. No greater quantity of explosives than that which is required for immediate use shall be taken into the working chamber.

. Explosives shall be conveyed in a suitable covered wooden box.

. Detonators shall be conveyed in a separate covered wooden box.

. Explosives and detonators shall be taken separately into the caissons.

. After blasting is completed, all explosives and detonators shall be returned at once to the magazine.

. No naked light shall be used in the vicinity of open chests or magazines containing explosives, nor near where a charge is being primed.

. No tools or other articles shall be carried with the explosives or with the detonators.

. All power lines and electric light wires shall be disconnected at a point outside the blasting switch before the loading of holes. No current by grounding of power or bonded rails shall be allowed beyond blasting switch after explosives are taken in preparatory to blasting, and under no circumstances shall grounded current be used for exploding blasts.

. Before drilling is commenced on any shift, all remaining holes shall be examined with a wooden stick for unexploded charges or cartridges, and if any are found, same shall be refired before work proceeds.

. No person shall be allowed to deepen holes that have previously contained explosives.

. All wires in broken rock shall be carefully traced and search made for unexploded cartridges.

. Whenever blasting is being done in a tunnel, at points liable to break through to where other persons are at work, the person in charge shall, before any holes are loaded, give warning of danger to all persons that may be working where the blasts may break through, and he or she shall not allow any holes to be charged until warning is acknowledged and persons are removed.

. Blasters when testing circuit through charged holes shall use sufficient leading wires to be at a safe distance and shall use only approved types of galvanometers. No tests of circuits in charged holes shall be made until persons are removed to safe distance.

. No blasts shall be fired with fuse, except electrically ignited fuse, in vertical or steep shafts.

. In shaft sinking where the electric current is used for firing, a separate switch not controlling any electric lights must be used for blasting and proper safeguard similar to those in tunnels must be followed in order to insure against premature firing.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%201015[2009 c 549 § 1015]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%2015[1941 c 194 § 15]; Rem. Supp. 1941 § 7666-23; ]

== 49.24.230 - Firing switch—Warning by blaster.
When firing by electricity from power or lighting wires, a proper switch shall be furnished with lever down when "off".

The switch shall be fixed in a locked box to which no person shall have access except the blaster. There shall be provided flexible leads or connecting wires not less than five feet in length with one end attached to the incoming lines and the other end provided with plugs that can be connected to an effective ground. After blasting, the switch lever shall be pulled out, the wires disconnected and the box locked before any person shall be allowed to return, and shall remain so locked until again ready to blast.

In the working chamber all electric light wires shall be provided with a disconnecting switch, which must be thrown to disconnect all current from the wires in the working chamber before electric light wires are removed or the charge exploded.

Before blasting, the blaster shall cause a sufficient warning to be sounded and shall compel all persons to retreat to a safe shelter, before he or she sets off the blast, and shall permit no one to return until conditions are safe.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%2012025[2010 c 8 § 12025]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%2016[1941 c 194 § 16]; Rem. Supp. 1941 § 7666-24; ]

== 49.24.240 - Inspection after blast.
. After a blast is fired, loosened pieces of rock shall be scaled from the sides of the excavation and after the blasting is completed, the entire working chamber shall be thoroughly scaled.

. The person in charge shall inspect the working chamber and have all loose rock or ground removed and the chamber made safe before proceeding with the work.

. Drilling must not be started until all remaining butts of old holes are examined for unexploded charges.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%2017[1941 c 194 § 17]; Rem. Supp. 1941 § 7666-25; ]

== 49.24.250 - Code of signals.
Any code of signals used shall be printed and copies thereof, in such languages as may be necessary to be understood by all persons affected thereby, shall be kept posted in a conspicuous place near entrances to workplaces and in such other places as may be necessary to bring them to the attention of all persons affected thereby.

Effective and reliable signaling devices shall be maintained at all times to give instant communication between the bottom and top of the shaft.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%2018[1941 c 194 § 18]; Rem. Supp. 1941 § 7666-26; ]

== 49.24.260 - Requirements as to caissons.
All shafting used in pneumatic caissons shall be provided with ladders, which are to be kept clear and in good condition at all times. The distance between the centers of the rungs of a ladder shall not exceed fourteen inches and shall not vary more than one inch in any one piece of shafting. The length of the ladder rungs shall not be less than nine inches. The rungs of the ladder shall in no case be less than three inches from the wall or other obstruction in the shafting or opening in which the ladder shall be used. Under no circumstances shall a ladder inclining backward from the vertical be installed. A suitable ladder shall be provided from the top of all locks to the surface.

All man shafts shall be lighted at a distance of every ten feet with a guarded incandescent lamp.

All outside caisson air locks shall be provided with a platform not less than forty-two inches wide, and provided with a guard rail forty-two inches high.

All caissons in which fifteen or more men are employed shall have two locks, one of which shall be used as a man lock. Man locks and man shafts shall be in charge of a man whose duty it shall be to operate said lock and shaft. All caissons more than ten feet in diameter shall be provided with a separate man shaft, which shall be kept clear and in operating order at all times.

Locks shall be so located that the distance between the bottom door and water level shall be not less than three feet.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%2019[1941 c 194 § 19]; Rem. Supp. 1941 § 7666-27; ]

== 49.24.270 - Shields to be provided.
Wherever, in the prosecution of caisson work in which compressed air is employed, the working chamber is less than twelve feet in length, and when such caissons are at any time suspended or hung while work is in progress, so that the bottom of the excavation is more than nine feet below the deck of the working chamber, a shield shall be erected therein for the protection of the workers.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c12.pdf?cite=1989%20c%2012%20§%2015[1989 c 12 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%2020[1941 c 194 § 20]; Rem. Supp. 1941 § 7666-28; ]

== 49.24.280 - Caissons to be braced.
All caissons shall be properly and adequately braced before loading with concrete or other weight.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%2021[1941 c 194 § 21]; Rem. Supp. 1941 § 7666-29; ]

== 49.24.290 - Cages—Hoisting apparatus.
In all shafts where men are hoisted or lowered, an iron-bonneted cage shall be used for the conveyance of men, but this provision shall not apply to shafts in the process of sinking or during the dismantling of the shaft after work in the tunnel is substantially completed.

Cages shall be provided with bonnets consisting of two steel plates not less than three-sixteenths of an inch in thickness, sloping toward each side and so arranged that they may be readily pushed upward to afford egress to persons therein, and such bonnet shall cover the top of the cage in such manner as to protect persons in the cage from falling objects.

Cages shall be entirely enclosed on two sides with solid partition or wire mesh not less than No. 8 U.S. Standard gauge, no opening in which shall exceed two inches.

Cages shall be provided with hanging chains or other similar devices for hand holds.

Every cage shall be provided with an approved safety catch of sufficient strength to hold the cage with its maximum load at any point in the shaft.

All parts of the hoisting apparatus, cables, brakes, guides and fastenings shall be of the most substantial design and shall be arranged for convenient inspection. The efficiency of all safety devices shall be established by satisfactory tests before the cages are put into service and at least once every three months thereafter and a record thereof kept.

The test of the safety catch shall consist of releasing the cage suddenly in such manner that the safety catches shall have opportunity to grip the guides.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%2022[1941 c 194 § 22]; Rem. Supp. 1941 § 7666-30; ]

== 49.24.300 - Buckets in vertical shafts.
In all vertical shafts in which hoisting is done by means of a bucket, suitable guides shall be provided when the depth exceeds ten times the diameter or width of the shaft, but in no case shall the maximum depth without guides exceed one hundred and fifty feet. In connection with the bucket, there shall be a crosshead traveling between these guides. The height of the crosshead shall be at least two-thirds of its width, but the height in no case shall be less than thirty inches.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%2023[1941 c 194 § 23]; Rem. Supp. 1941 § 7666-31; ]

== 49.24.310 - Telephone system for tunnels.
Where tunnels are driven from shafts more than two hundred and fifty feet deep, a telephone system shall be established and maintained, communicating with the surface at each such shaft, and with a station or stations readily and quickly accessible to the men at the working level.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%2024[1941 c 194 § 24]; Rem. Supp. 1941 § 7666-32; ]

== 49.24.320 - Location of lights.
. While work is in progress, tunnels, stairways, ladderways and all places on the surface where work is being conducted, shall be properly lighted. In shafts more than one hundred feet deep, the shaft below that point shall be lighted.

. All places where hoisting, pumping or other machinery is erected and in the proximity of which persons are working or moving about, shall be so lighted when the machine is in operation that the moving parts of such machine can be clearly distinguished.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%2025[1941 c 194 § 25]; Rem. Supp. 1941 § 7666-33; ]

== 49.24.330 - Generators, transformers, etc., to be grounded.
The frames and bed plates of generators, transformers, compensators, rheostats and motors installed underground shall be effectively grounded. All metallic coverings, armoring of cables, other than trailing cables, and the neutral wire of three-wire systems shall also be so grounded.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%2026[1941 c 194 § 26]; Rem. Supp. 1941 § 7666-34; ]

== 49.24.340 - Electrical voltage.
In electrical systems installed, no higher voltage than low voltage shall be used underground, except for transmission or other application to transformers, motors, generators or other apparatus in which the whole of the medium or high voltage apparatus is stationary.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%2027[1941 c 194 § 27]; Rem. Supp. 1941 § 7666-35; ]

== 49.24.350 - Lamps to be held in reserve.
Lamps or other proper lights shall be kept ready for use in all underground stations where a failure of electric light is likely to cause danger.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%2028[1941 c 194 § 28]; Rem. Supp. 1941 § 7666-36; ]

== 49.24.360 - Insulators required.
. All underground cables and wires, unless provided with grounded metallic covering, shall be supported by efficient insulators. The conductors connecting lamps to the power supply shall in all cases be insulated.

. Cables and wires unprovided with metallic coverings shall not be fixed to walls or timbers by means of uninsulated fastenings.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%2029[1941 c 194 § 29]; Rem. Supp. 1941 § 7666-37; ]

== 49.24.370 - Director to make rules and regulations.
The director of labor and industries shall establish such rules and regulations as he or she deems primarily necessary for the safety of the employees employed in tunnels, quarries, caissons, and subways and shall be guided by the most modern published studies and researches made by persons or institutions into the correction of the evils chargeable to improper safeguards and inspection of the tools, machinery, equipment, and places of work obtaining in the industries covered by RCW 49.24.080 through 49.24.380.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%2012026[2010 c 8 § 12026]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%2032[1941 c 194 § 32]; Rem. Supp. 1941 § 7666-39; ]

== 49.24.380 - Penalty.
Every person violating any of the provisions of RCW 49.24.080 through 49.24.380 shall be guilty of a misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c194.pdf?cite=1941%20c%20194%20§%2031[1941 c 194 § 31]; Rem. Supp. 1941 § 7666-38; ]

