= 49.39 - Symphony musicians.
:toc:

== 49.39.005 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Bargaining representative" means any lawful organization which represents symphony musicians in their employment relations with their employers.

. "Collective bargaining" means the performance of the mutual obligations of the employer and the exclusive bargaining representative to meet at reasonable times, to confer and negotiate in good faith, and to execute a written agreement with respect to grievance procedures and collective negotiations on personnel matters, including wages, hours, and working conditions, which may be peculiar to an appropriate bargaining unit of such employer, except that by such obligation neither party shall be compelled to agree to a proposal or be required to make a concession unless otherwise provided in this chapter.

. "Commission" means the public employment relations commission.

. [Empty]
.. "Employer" means a symphony orchestra with a gross annual revenue of more than three hundred thousand dollars that does not meet the jurisdictional standards of the national labor relations board, and includes any person acting as an agent of an employer, directly or indirectly.

.. In determining whether any person is acting as an "agent" of another person so as to make such other person responsible for his or her acts, the question of whether the specific acts performed were actually authorized or subsequently ratified shall not be controlling.

. "Executive director" means the executive director of the commission.

. "Labor dispute" includes any controversy concerning terms, tenure, or conditions of employment, or concerning the association of representation of persons in negotiating, fixing, maintaining, changing, or seeking to arrange terms or conditions of employment, regardless of whether the disputants stand in the proximate relation of employer and symphony musician employee. In the event of a dispute between an employer and an exclusive bargaining representative over the matters that are terms and conditions of employment, the commission shall decide which items are mandatory subjects for bargaining.

. "Labor organization" means an organization of any kind, or an agency or employee representation committee or plan, in which symphony musicians participate and which exists for the primary purpose of dealing with employers concerning grievances, labor disputes, wages, rates of pay, hours of employment, or conditions of employment.

. "Person" includes one or more individuals, labor organizations, partnerships, associations, corporations, legal representatives, trustees in bankruptcy, or receivers.

. "Unfair labor practice" means any activity listed in RCW 49.39.120 and 49.39.130.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5046-S.SL.pdf?cite=2010%20c%206%20§%201[2010 c 6 § 1]; ]

== 49.39.010 - Collective bargaining rights.
No employer, or other person, shall directly or indirectly interfere with, restrain, coerce, or discriminate against any symphony musician or group of symphony musicians in the free exercise of their right to organize and designate bargaining representatives of their own choosing for the purpose of collective bargaining, or in the free exercise of any other right under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5046-S.SL.pdf?cite=2010%20c%206%20§%202[2010 c 6 § 2]; ]

== 49.39.020 - Selection of bargaining representative.
If an employer and its symphony musician employees are in disagreement as to the selection of a bargaining representative the commission shall be invited to intervene as is provided in RCW 49.39.030 through 49.39.060.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5046-S.SL.pdf?cite=2010%20c%206%20§%203[2010 c 6 § 3]; ]

== 49.39.023 - Application of RCW  41.56.037—Bargaining representative access to new employees.
RCW 41.56.037 applies to this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6229.SL.pdf?cite=2018%20c%20250%20§%207[2018 c 250 § 7]; ]

== 49.39.030 - Certification of exclusive bargaining representative.
The commission, upon reasonable notice, shall decide in each application for certification as an exclusive bargaining representative the unit appropriate for the purpose of collective bargaining. In determining, modifying, or combining the bargaining unit, the commission shall consider the duties, skills, and working conditions of the symphony musicians; the history of collective bargaining by the symphony musicians and their bargaining representatives; the extent of organization among the symphony musicians; and the desire of the symphony musicians. The commission shall determine the bargaining representative by: (1) Comparison of signatures on organization bargaining authorization cards; or (2) conducting an election specifically therefor.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5046-S.SL.pdf?cite=2010%20c%206%20§%204[2010 c 6 § 4]; ]

== 49.39.040 - Election to ascertain exclusive bargaining representative.
If the commission elects to conduct an election to ascertain the exclusive bargaining representative, and upon the request of a prospective bargaining representative showing written proof of at least thirty percent representation of the symphony musicians within the unit, the commission shall hold an election by secret ballot to determine the issue. The ballot shall contain the name of the bargaining representative and of any other bargaining representative showing written proof of at least ten percent representation of the symphony musicians within the unit, together with a choice for any symphony musician to designate that he or she does not desire to be represented by any bargaining agent. Where more than one organization is on the ballot and neither of the three or more choices receives a majority vote of valid ballots cast, a runoff election shall be held. The runoff ballot shall contain the two choices which received the largest and second-largest number of votes. No question concerning representation may be raised within one year of a certification or attempted certification. Where there is a valid collective bargaining agreement in effect, no question of representation may be raised except during the period not more than ninety nor less than sixty days prior to the expiration date of the agreement. Any agreement which contains a provision for automatic renewal or extension of the agreement shall not be a valid agreement; nor shall any agreement be valid if it provides for a term of existence for more than three years.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5046-S.SL.pdf?cite=2010%20c%206%20§%205[2010 c 6 § 5]; ]

== 49.39.050 - Exclusive bargaining representative—Must represent all symphony musicians—Exception.
The bargaining representative which has been determined to represent a majority of the symphony musicians in a bargaining unit shall be certified by the commission as the exclusive bargaining representative of, and shall be required to represent, all the symphony musicians within the unit without regard to membership in the bargaining representative. However, any symphony musician at any time may present his or her grievance to the employer and have such grievance adjusted without the intervention of the exclusive bargaining representative, if the adjustment is not inconsistent with the terms of a collective bargaining agreement then in effect, and if the exclusive bargaining representative has been given reasonable opportunity to be present at any initial meeting called for the resolution of the grievance.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5046-S.SL.pdf?cite=2010%20c%206%20§%206[2010 c 6 § 6]; ]

== 49.39.060 - Rules—Commission.
The commission may adopt rules necessary to administer this chapter in conformity with the intent and purpose of this chapter and consistent with the best standards of labor-management relations.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5046-S.SL.pdf?cite=2010%20c%206%20§%207[2010 c 6 § 7]; ]

== 49.39.065 - Certification of bargaining representative—Cross-check.
If only one employee organization is seeking certification as exclusive bargaining representative of a bargaining unit for which there is no incumbent exclusive bargaining representative, the commission may determine the question concerning representation by conducting a cross-check comparing the employee organization's membership records or bargaining authorization cards against the employment records of the employer. A determination through a cross-check process may be made upon a showing of interest submitted in support of the exclusive bargaining representative by more than fifty percent of the employees. The commission may adopt rules to implement this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1575-S.SL.pdf?cite=2019%20c%20230%20§%2021[2019 c 230 § 21]; ]

== 49.39.070 - Failure to conclude collective bargaining agreement.
An employer may engage in collective bargaining with the exclusive bargaining representative and no employer may refuse to engage in collective bargaining with the exclusive bargaining representative. Upon the failure of the employer and the exclusive bargaining representative to conclude a collective bargaining agreement, any matter in dispute may be submitted by either party to the commission. If an employer implements its last and best offer where there is no contract settlement, allegations that either party is violating the terms of the implemented offer are subject to grievance arbitration procedures if and as such procedures are set forth in the implemented offer, or, if not in the implemented offer, if and as such procedures are set forth in the parties' last contract.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5046-S.SL.pdf?cite=2010%20c%206%20§%208[2010 c 6 § 8]; ]

== 49.39.080 - Employee authorization of membership dues and other payments—Revocation.
. Upon the authorization of an employee within the bargaining unit and after the certification or recognition of the bargaining unit's exclusive bargaining representative, the employer must deduct from the payments to the employee the monthly amount of dues as certified by the secretary of the exclusive bargaining representative and must transmit the same to the treasurer of the exclusive bargaining representative.

. [Empty]
.. An employee's written, electronic, or recorded voice authorization to have the employer deduct membership dues from the employee's salary must be made by the employee to the exclusive bargaining representative. If the employer receives a request for authorization of deductions, the employer shall as soon as practicable forward the request to the exclusive bargaining representative.

.. Upon receiving notice of the employee's authorization from the exclusive bargaining representative, the employer shall deduct from the employee's salary membership dues and remit the amounts to the exclusive bargaining representative.

.. The employee's authorization remains in effect until expressly revoked by the employee in accordance with the terms and conditions of the authorization.

.. An employee's request to revoke authorization for payroll deductions must be in writing and submitted by the employee to the exclusive bargaining representative in accordance with the terms and conditions of the authorization.

.. After the employer receives confirmation from the exclusive bargaining representative that the employee has revoked authorization for deductions, the employer shall end the deduction no later than the second payroll after receipt of the confirmation.

.. The employer shall rely on information provided by the exclusive bargaining representative regarding the authorization and revocation of deductions.

. If the employer and the exclusive bargaining representative of a bargaining unit enter into a collective bargaining agreement that includes requirements for deductions of other payments, the employer must make such deductions upon authorization of the employee.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1575-S.SL.pdf?cite=2019%20c%20230%20§%2022[2019 c 230 § 22]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2751.SL.pdf?cite=2018%20c%20247%20§%206[2018 c 247 § 6]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5046-S.SL.pdf?cite=2010%20c%206%20§%209[2010 c 6 § 9]; ]

== 49.39.090 - Collective bargaining agreement—Binding arbitration.
A collective bargaining agreement may provide for binding arbitration of a labor dispute arising from the application or the interpretation of the matters contained in a collective bargaining agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1575-S.SL.pdf?cite=2019%20c%20230%20§%2023[2019 c 230 § 23]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5046-S.SL.pdf?cite=2010%20c%206%20§%2010[2010 c 6 § 10]; ]

== 49.39.100 - After termination date of collective bargaining agreement.
. After the termination date of a collective bargaining agreement, all of the terms and conditions specified in the collective bargaining agreement remain in effect until the effective date of a subsequent agreement, not to exceed one year from the termination date stated in the agreement. Thereafter, the employer may unilaterally implement according to law.

. This section does not apply to provisions of a collective bargaining agreement which both parties agree to exclude from the provisions of subsection (1) of this section and to provisions within the collective bargaining agreement with separate and specific termination dates.

. This section shall not apply to collective bargaining agreements in effect or being bargained on June 10, 2010.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5046-S.SL.pdf?cite=2010%20c%206%20§%2011[2010 c 6 § 11]; ]

== 49.39.110 - Selection of arbitrators.
In addition to any other method for selecting arbitrators, the parties may request the commission to appoint a qualified person who may be an employee of the commission to act as an arbitrator to assist in the resolution of a labor dispute between the employer and the bargaining representative arising from the application of the matters contained in a collective bargaining agreement. The arbitrator must conduct the arbitration of the dispute in a manner as provided for in the collective bargaining agreement. The commission may not collect any fees or charges from the employer or the bargaining representative for services performed by the commission under this chapter. The provisions of chapter 49.08 RCW do not apply to this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5046-S.SL.pdf?cite=2010%20c%206%20§%2012[2010 c 6 § 12]; ]

== 49.39.120 - Unfair labor practice—Employer.
It is an unfair labor practice for an employer:

. To interfere with, restrain, or coerce symphony musicians in the exercise of their rights guaranteed by this chapter;

. To control, dominate, or interfere with a bargaining representative;

. To discriminate against a symphony musician who has filed an unfair labor practice charge or who has given testimony under this chapter;

. To refuse to engage in collective bargaining.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5046-S.SL.pdf?cite=2010%20c%206%20§%2013[2010 c 6 § 13]; ]

== 49.39.130 - Unfair labor practice—Bargaining representative.
It is an unfair labor practice for a bargaining representative:

. To interfere with, restrain, or coerce employees in the exercise of their rights guaranteed by this chapter;

. To induce the employer to commit an unfair labor practice;

. To discriminate against a symphony musician who has filed an unfair labor practice charge or who has given testimony under this chapter;

. To refuse to engage in collective bargaining.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5046-S.SL.pdf?cite=2010%20c%206%20§%2014[2010 c 6 § 14]; ]

== 49.39.140 - Commission must prevent unfair labor practices.
. The commission must prevent unfair labor practices and issue appropriate remedial orders. However, a complaint may not be processed for an unfair labor practice occurring more than six months before the filing of the complaint with the commission or in superior court.

. If the commission determines that a person has engaged in or is engaging in an unfair labor practice, the commission must issue and serve upon the person an order requiring the person to cease and desist from the unfair labor practice. The commission may take action to carry out the purposes and policy of this chapter, including requiring the person to pay damages and reinstate employees.

. The commission may petition the superior court for the county in which the main office of the employer is located or in which the person who has engaged or is engaging in the unfair labor practice resides or transacts business, for the enforcement of its order and for appropriate temporary relief.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6231.SL.pdf?cite=2018%20c%20252%20§%206[2018 c 252 § 6]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5046-S.SL.pdf?cite=2010%20c%206%20§%2015[2010 c 6 § 15]; ]

== 49.39.150 - Actions by commission subject to chapter  34.05 RCW.
Actions taken by or on behalf of the commission shall be pursuant to chapter 34.05 RCW, or rules adopted in accordance with chapter 34.05 RCW, and the right of judicial review provided by chapter 34.05 RCW is applicable to all actions and rules.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5046-S.SL.pdf?cite=2010%20c%206%20§%2016[2010 c 6 § 16]; ]

