= 49.30 - Agricultural labor.
:toc:

== 49.30.005 - Intent—Duties of department.
It is the intent of the legislature that the department assist agricultural employers in mitigating the costs of the state's unemployment insurance program. The department shall work with members of the agricultural community to: Improve understanding of the program's operation; increase compliance with work-search requirements; provide prompt notification of potential claims against an employer's experience rating; inform employers of their rights; inform employers of the actions necessary to appeal a claim and to protect their rights; and reduce claimant and employer fraud. These efforts shall include:

. Conducting employer workshops and community seminars;

. Developing new educational materials; and

. Developing forms that use lay language.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%2099[1998 c 245 § 99]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1625.SL.pdf?cite=1991%20c%2031%20§%201[1991 c 31 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c245.pdf?cite=1990%20c%20245%20§%2010[1990 c 245 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c380.pdf?cite=1989%20c%20380%20§%2082[1989 c 380 § 82]; ]

== 49.30.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Agricultural employment" or "employment" means employment in agricultural labor as defined in RCW 50.04.150.

. "Department" means the department of labor and industries.

. "Employer" means any person, firm, corporation, partnership, business trust, legal representative, or other business entity that engages in any agricultural activity in this state and employs one or more employees.

. "Employee" means a person employed in agricultural employment, and includes a person who is working under an independent contract the essence of which is personal labor in agricultural employment whether by way of manual labor or otherwise. However, "employee" shall not include immediate family members of the officers of any corporation, partnership, sole proprietorship, or other business entity, or officers of any closely held corporation engaged in agricultural production of crops or livestock.

. "Minor" means an employee who is under the age of eighteen years.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c380.pdf?cite=1989%20c%20380%20§%2083[1989 c 380 § 83]; ]

== 49.30.020 - Hours and pay, recordkeeping.
. Each employer required to keep employment records under RCW 49.46.070, shall retain such records for three years.

. Each employer shall furnish to each employee at the time the employee's wages are paid an itemized statement showing the pay basis in hours or days worked, the rate or rates of pay, the gross pay, and all deductions from the pay for the respective pay period.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c380.pdf?cite=1989%20c%20380%20§%2084[1989 c 380 § 84]; ]

== 49.30.040 - Violation of chapter—Civil infraction.
Any violation of the provisions of this chapter or rules adopted hereunder shall be a class 1 civil infraction. The director shall have the authority to issue and enforce civil infractions according to chapter 7.80 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c380.pdf?cite=1989%20c%20380%20§%2086[1989 c 380 § 86]; ]

== 49.30.901 - Conflict with federal requirements—1989 c 380.
See note following RCW 50.04.150.

[ ]

