= 49.62 - Noncompetition covenants.
:toc:

== 49.62.005 - Findings.
The legislature finds that workforce mobility is important to economic growth and development. Further, the legislature finds that agreements limiting competition or hiring may be contracts of adhesion that may be unreasonable.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1450-S.SL.pdf?cite=2019%20c%20299%20§%201[2019 c 299 § 1]; ]

== 49.62.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Earnings" means the compensation reflected on box one of the employee's United States internal revenue service form W-2 that is paid to an employee over the prior year, or portion thereof for which the employee was employed, annualized and calculated as of the earlier of the date enforcement of the noncompetition covenant is sought or the date of separation from employment. "Earnings" also means payments reported on internal revenue service form 1099-MISC for independent contractors.

. "Employee" and "employer" have the same meanings as in RCW 49.17.020.

. "Franchisor" and "franchisee" have the same meanings as in RCW 19.100.010.

. "Noncompetition covenant" includes every written or oral covenant, agreement, or contract by which an employee or independent contractor is prohibited or restrained from engaging in a lawful profession, trade, or business of any kind. A "noncompetition covenant" does not include: (a) A nonsolicitation agreement; (b) a confidentiality agreement; (c) a covenant prohibiting use or disclosure of trade secrets or inventions; (d) a covenant entered into by a person purchasing or selling the goodwill of a business or otherwise acquiring or disposing of an ownership interest; or (e) a covenant entered into by a franchisee when the franchise sale complies with RCW 19.100.020(1).

. "Nonsolicitation agreement" means an agreement between an employer and employee that prohibits solicitation by an employee, upon termination of employment: (a) Of any employee of the employer to leave the employer; or (b) of any customer of the employer to cease or reduce the extent to which it is doing business with the employer.

. "Party seeking enforcement" means the named plaintiff or claimant in a proceeding to enforce a noncompetition covenant or the defendant in an action for declaratory relief.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1450-S.SL.pdf?cite=2019%20c%20299%20§%202[2019 c 299 § 2]; ]

== 49.62.020 - When void and unenforceable.
. A noncompetition covenant is void and unenforceable against an employee:

.. [Empty]
... Unless the employer discloses the terms of the covenant in writing to the prospective employee no later than the time of the acceptance of the offer of employment and, if the agreement becomes enforceable only at a later date due to changes in the employee's compensation, the employer specifically discloses that the agreement may be enforceable against the employee in the future; or

... If the covenant is entered into after the commencement of employment, unless the employer provides independent consideration for the covenant;

.. Unless the employee's earnings from the party seeking enforcement, when annualized, exceed one hundred thousand dollars per year. This dollar amount must be adjusted annually in accordance with RCW 49.62.040;

.. If the employee is terminated as the result of a layoff, unless enforcement of the noncompetition covenant includes compensation equivalent to the employee's base salary at the time of termination for the period of enforcement minus compensation earned through subsequent employment during the period of enforcement.

. A court or arbitrator must presume that any noncompetition covenant with a duration exceeding eighteen months after termination of employment is unreasonable and unenforceable. A party seeking enforcement may rebut the presumption by proving by clear and convincing evidence that a duration longer than eighteen months is necessary to protect the party's business or goodwill.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1450-S.SL.pdf?cite=2019%20c%20299%20§%203[2019 c 299 § 3]; ]

== 49.62.030 - When void and unenforceable against independent contractors.
. A noncompetition covenant is void and unenforceable against an independent contractor unless the independent contractor's earnings from the party seeking enforcement exceed two hundred fifty thousand dollars per year. This dollar amount must be adjusted annually in accordance with RCW 49.62.040.

. The duration of a noncompetition covenant between a performer and a performance space, or a third party scheduling the performer for a performance space, must not exceed three calendar days.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1450-S.SL.pdf?cite=2019%20c%20299%20§%204[2019 c 299 § 4]; ]

== 49.62.040 - Dollar amounts adjusted.
The dollar amounts specified in RCW 49.62.020 and 49.62.030 must be adjusted annually for inflation. Annually on September 30th the department of labor and industries must adjust the dollar amounts specified in this section by calculating to the nearest cent using the consumer price index for urban wage earners and clerical workers, CPI-W, or a successor index, for the twelve months prior to each September 1st as calculated by the United States department of labor. The adjusted dollar amount calculated under this section takes effect on the following January 1st.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1450-S.SL.pdf?cite=2019%20c%20299%20§%205[2019 c 299 § 5]; ]

== 49.62.050 - Unenforceable provisions.
A provision in a noncompetition covenant signed by an employee or independent contractor who is Washington-based is void and unenforceable:

. If the covenant requires the employee or independent contractor to adjudicate a noncompetition covenant outside of this state; and

. To the extent it deprives the employee or independent contractor of the protections or benefits of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1450-S.SL.pdf?cite=2019%20c%20299%20§%206[2019 c 299 § 6]; ]

== 49.62.060 - Franchisor restrictions.
. No franchisor may restrict, restrain, or prohibit in any way a franchisee from soliciting or hiring any employee of a franchisee of the same franchisor.

. No franchisor may restrict, restrain, or prohibit in any way a franchisee from soliciting or hiring any employee of the franchisor.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1450-S.SL.pdf?cite=2019%20c%20299%20§%207[2019 c 299 § 7]; ]

== 49.62.070 - Employees having an additional job—When authorized.
. Subject to subsection (2) of this section, an employer may not restrict, restrain, or prohibit an employee earning less than twice the applicable state minimum hourly wage from having an additional job, supplementing their income by working for another employer, working as an independent contractor, or being self-employed.

. [Empty]
.. This section shall not apply to any such additional services when the specific services to be offered by the employee raise issues of safety for the employee, coworkers, or the public, or interfere with the reasonable and normal scheduling expectations of the employer.

.. This section does not alter the obligations of an employee to an employer under existing law, including the common law duty of loyalty and laws preventing conflicts of interest and any corresponding policies addressing such obligations.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1450-S.SL.pdf?cite=2019%20c%20299%20§%208[2019 c 299 § 8]; ]

== 49.62.080 - Violation of this chapter—Relief—Remedies.
. Upon a violation of this chapter, the attorney general, on behalf of a person or persons, may pursue any and all relief. A person aggrieved by a noncompetition covenant to which the person is a party may bring a cause of action to pursue any and all relief provided for in subsections (2) and (3) of this section.

. If a court or arbitrator determines that a noncompetition covenant violates this chapter, the violator must pay the aggrieved person the greater of his or her actual damages or a statutory penalty of five thousand dollars, plus reasonable attorneys' fees, expenses, and costs incurred in the proceeding.

. If a court or arbitrator reforms, rewrites, modifies, or only partially enforces any noncompetition covenant, the party seeking enforcement must pay the aggrieved person the greater of his or her actual damages or a statutory penalty of five thousand dollars, plus reasonable attorneys' fees, expenses, and costs incurred in the proceeding.

. A cause of action may not be brought regarding a noncompetition covenant signed prior to January 1, 2020, if the noncompetition covenant is not being enforced.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1450-S.SL.pdf?cite=2019%20c%20299%20§%209[2019 c 299 § 9]; ]

== 49.62.090 - Conflict of laws.
. [Empty]
.. Subject to (b) of this subsection, this chapter displaces conflicting tort, restitutionary, contract, and other laws of this state pertaining to liability for competition by employees or independent contractors with their employers or principals, as appropriate.

.. This chapter does not amend or modify chapter 19.108 RCW.

. Except as otherwise provided in this chapter, this chapter does not revoke, modify, or impede the development of the common law.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1450-S.SL.pdf?cite=2019%20c%20299%20§%2010[2019 c 299 § 10]; ]

== 49.62.100 - Retroactive application.
This chapter applies to all proceedings commenced on or after January 1, 2020, regardless of when the cause of action arose. To this extent, this chapter applies retroactively, but in all other respects it applies prospectively.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1450-S.SL.pdf?cite=2019%20c%20299%20§%2011[2019 c 299 § 11]; ]

== 49.62.110 - Construction.
This chapter is an exercise of the state's police power and shall be construed liberally for the accomplishment of its purposes.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1450-S.SL.pdf?cite=2019%20c%20299%20§%2012[2019 c 299 § 12]; ]

== 49.62.900 - Effective date—2019 c 299.
This act takes effect January 1, 2020.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1450-S.SL.pdf?cite=2019%20c%20299%20§%2013[2019 c 299 § 13]; ]

