= 49.74 - Affirmative action.
:toc:

== 49.74.005 - Legislative findings—Purpose.
Discrimination because of race, creed, color, national origin, age, sex, marital status, or the presence of any disability is contrary to the findings of the legislature and public policy. The legislature finds and declares that racial minorities, women, persons in protected age groups, persons with disabilities, Vietnam-era veterans, and veterans with disabilities are underrepresented in Washington state government employment.

The purpose of this chapter is to provide for enforcement measures for affirmative action within Washington state government employment and institutions of higher education in order to eliminate such underrepresentation.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2390.SL.pdf?cite=2020%20c%20274%20§%2041[2020 c 274 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c365.pdf?cite=1985%20c%20365%20§%207[1985 c 365 § 7]; ]

== 49.74.010 - Commission.
As used in this chapter, "commission" means the Washington state human rights commission.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c365.pdf?cite=1985%20c%20365%20§%208[1985 c 365 § 8]; ]

== 49.74.020 - Affirmative action rules—Noncompliance—Notification—Hearing.
If the commission reasonably believes that a state agency, an institution of higher education, or the state patrol has failed to comply with an affirmative action rule adopted under RCW 41.06.150 or 43.43.340, the commission shall notify the director of the state agency, president of the institution of higher education, or chief of the Washington state patrol of the noncompliance, as well as the director of financial management. The commission shall give the director of the state agency, president of the institution of higher education, or chief of the Washington state patrol an opportunity to be heard on the failure to comply.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5315-S2.SL.pdf?cite=2015%203rd%20sp.s.%20c%201%20§%20324[2015 3rd sp.s. c 1 § 324]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5931-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2043%20§%20463[2011 1st sp.s. c 43 § 463]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2054-S.SL.pdf?cite=1993%20c%20281%20§%2057[1993 c 281 § 57]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c365.pdf?cite=1985%20c%20365%20§%209[1985 c 365 § 9]; ]

== 49.74.030 - Noncompliance—Conciliation—Order.
The commission in conjunction with the department of enterprise services, the office of financial management, or the state patrol, whichever is appropriate, shall attempt to resolve the noncompliance through conciliation. If an agreement is reached for the elimination of noncompliance, the agreement shall be reduced to writing and an order shall be issued by the commission setting forth the terms of the agreement. The noncomplying state agency, institution of higher education, or state patrol shall make a good faith effort to conciliate and make a full commitment to correct the noncompliance with any action that may be necessary to achieve compliance, provided such action is not inconsistent with the rules adopted under RCW 41.06.150(5) and 43.43.340(5), whichever is appropriate.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5931-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2043%20§%20464[2011 1st sp.s. c 43 § 464]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1268-S.SL.pdf?cite=2002%20c%20354%20§%20246[2002 c 354 § 246]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1268-S.SL.pdf?cite=2002%20c%20354%20§%20245[2002 c 354 § 245]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2054-S.SL.pdf?cite=1993%20c%20281%20§%2058[1993 c 281 § 58]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c365.pdf?cite=1985%20c%20365%20§%2010[1985 c 365 § 10]; ]

== 49.74.031 - Referral to administrative law judge for hearing.
If no agreement can be reached under RCW 49.74.030, the commission may refer the matter to the administrative law judge for hearing pursuant to RCW 49.60.250. If the administrative law judge finds that the state agency, institution of higher education, or state patrol has not made a good faith effort to correct the noncompliance, the administrative law judge shall order the state agency, institution of higher education, or state patrol to comply with this chapter. The administrative law judge may order any action that may be necessary to achieve compliance, provided such action is not inconsistent with the rules adopted under RCW 41.06.150(6) and 43.43.340(5), whichever is appropriate.

An order by the administrative law judge may be appealed to superior court.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5024.SL.pdf?cite=2015%20c%20225%20§%20102[2015 c 225 § 102]; ]

== 49.74.050 - Superior court—Remedies.
If the superior court finds that the state agency, institution of higher education, or state patrol has not made a good faith effort to correct the noncompliance, the court, in addition to any other penalties and sanctions prescribed by law, shall order the state agency, institution of higher education, or state patrol to comply with this chapter. The court may require any action deemed appropriate by the court which is consistent with the intent of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c365.pdf?cite=1985%20c%20365%20§%2012[1985 c 365 § 12]; ]

== 49.74.900 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%20132[2009 c 521 § 132]; ]

