= 49.76 - Domestic violence leave.
:toc:

== 49.76.010 - Legislative findings.
. It is in the public interest to reduce domestic violence, sexual assault, and stalking by enabling victims to maintain the financial independence necessary to leave abusive situations, achieve safety, and minimize physical and emotional injuries, and to reduce the devastating economic consequences of domestic violence, sexual assault, and stalking to employers and employees. Victims of domestic violence, sexual assault, and stalking should be able to recover from and cope with the effects of such violence and participate in criminal and civil justice processes without fear of adverse economic consequences. Victims of domestic violence, sexual assault, or stalking should also be able to seek and maintain employment without fear that they will face discrimination.

. One of the best predictors of whether a victim of domestic violence, sexual assault, or stalking will be able to stay away from an abuser is his or her degree of economic independence. However, domestic violence, sexual assault, and stalking often negatively impact victims' ability to maintain employment.

. An employee who is a victim of domestic violence, sexual assault, or stalking, or an employee whose family member is a victim, must often take leave from work due to injuries, court proceedings, or safety concerns requiring legal protection.

. Thus, it is in the public interest to provide reasonable leave from employment for employees who are victims of domestic violence, sexual assault, or stalking, or for employees whose family members are victims, to participate in legal proceedings, receive medical treatment, or obtain other necessary services.

. It is also in the public interest to ensure that victims of domestic violence, sexual assault, or stalking are able to seek and maintain employment without fear of discrimination and to have reasonable safety accommodations in the workplace.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2661.SL.pdf?cite=2018%20c%2047%20§%201[2018 c 47 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2602-S.SL.pdf?cite=2008%20c%20286%20§%201[2008 c 286 § 1]; ]

== 49.76.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Child," "spouse," "parent," "parent-in-law," "grandparent," and "sick leave and other paid time off" have the same meanings as in RCW 49.12.265.

. "Dating relationship" has the same meaning as in RCW 26.50.010.

. "Department," "director," "employer," and "employee" have the same meanings as in RCW 49.12.005.

. "Domestic violence" has the same meaning as in RCW 26.50.010.

. "Family member" means any individual whose relationship to the employee can be classified as a child, spouse, parent, parent-in-law, grandparent, or person with whom the employee has a dating relationship.

. "Intermittent leave" is leave taken in separate blocks of time due to a single qualifying reason.

. "Reduced leave schedule" means a leave schedule that reduces the usual number of hours per workweek, or hours per workday, of an employee.

. "Sexual assault" has the same meaning as in RCW 70.125.030.

. "Stalking" has the same meaning as in RCW 9A.46.110.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2090[2017 3rd sp.s. c 5 § 90]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2602-S.SL.pdf?cite=2008%20c%20286%20§%202[2008 c 286 § 2]; ]

== 49.76.030 - Domestic violence leave—Victims and family members—Purpose.
An employee may take reasonable leave from work, intermittent leave, or leave on a reduced leave schedule, with or without pay, to:

. Seek legal or law enforcement assistance or remedies to ensure the health and safety of the employee or employee's family members including, but not limited to, preparing for, or participating in, any civil or criminal legal proceeding related to or derived from domestic violence, sexual assault, or stalking;

. Seek treatment by a health care provider for physical or mental injuries caused by domestic violence, sexual assault, or stalking, or to attend to health care treatment for a victim who is the employee's family member;

. Obtain, or assist a family member in obtaining, services from a domestic violence shelter, rape crisis center, or other social services program for relief from domestic violence, sexual assault, or stalking;

. Obtain, or assist a family member in obtaining, mental health counseling related to an incident of domestic violence, sexual assault, or stalking, in which the employee or the employee's family member was a victim of domestic violence, sexual assault, or stalking; or

. Participate in safety planning, temporarily or permanently relocate, or take other actions to increase the safety of the employee or employee's family members from future domestic violence, sexual assault, or stalking.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2602-S.SL.pdf?cite=2008%20c%20286%20§%203[2008 c 286 § 3]; ]

== 49.76.040 - Documentation of leave—Notice of purpose—Confidentiality.
. As a condition of taking leave for any purpose described in RCW 49.76.030, an employee shall give an employer advance notice of the employee's intention to take leave. The timing of the notice shall be consistent with the employer's stated policy for requesting such leave, if the employer has such a policy. When advance notice cannot be given because of an emergency or unforeseen circumstances due to domestic violence, sexual assault, or stalking, the employee or his or her designee must give notice to the employer no later than the end of the first day that the employee takes such leave.

. When an employee requests leave under RCW 49.76.030 or requests a reasonable safety accommodation under RCW 49.76.115 the employer may require that the request be supported by verification that:

.. The employee or employee's family member is a victim of domestic violence, sexual assault, or stalking; and

.. The leave taken was for one of the purposes described in RCW 49.76.030 or that the safety accommodation requested under RCW 49.76.115 is for the purpose of protecting the employee from domestic violence, sexual assault, or stalking.

. If an employer requires verification, verification must be provided in a timely manner. In the event that advance notice of the leave cannot be given because of an emergency or unforeseen circumstances due to domestic violence, sexual assault, or stalking, and the employer requires verification, verification must be provided to the employer within a reasonable time period during or after the leave.

. An employee may satisfy the verification requirement of this section by providing the employer with one or more of the following:

.. A police report indicating that the employee or employee's family member was a victim of domestic violence, sexual assault, or stalking;

.. A court order protecting or separating the employee or employee's family member from the perpetrator of the act of domestic violence, sexual assault, or stalking, or other evidence from the court or the prosecuting attorney that the employee or employee's family member appeared, or is scheduled to appear, in court in connection with an incident of domestic violence, sexual assault, or stalking;

.. Documentation that the employee or the employee's family member is a victim of domestic violence, sexual assault, or stalking, from any of the following persons from whom the employee or employee's family member sought assistance in addressing the domestic violence, sexual assault, or stalking: An advocate for victims of domestic violence, sexual assault, or stalking; an attorney; a member of the clergy; or a medical or other professional. The provision of documentation under this section does not waive or diminish the confidential or privileged nature of communications between a victim of domestic violence, sexual assault, or stalking with one or more of the individuals named in this subsection (4)(c) pursuant to RCW 5.60.060, 70.123.075, 70.123.076, or 70.125.065; or

.. An employee's written statement that the employee or the employee's family member is a victim of domestic violence, sexual assault, or stalking and that the leave taken was for one of the purposes described in RCW 49.76.030 or the safety accommodation requested pursuant to RCW 49.76.115 is to protect the employee from domestic violence, sexual assault, or stalking.

. If the victim of domestic violence, sexual assault, or stalking is the employee's family member, verification of the familial relationship between the employee and the victim may include, but is not limited to, a statement from the employee, a birth certificate, a court document, or other similar documentation.

. An employee who is absent from work pursuant to RCW 49.76.030 may elect to use the employee's sick leave and other paid time off, compensatory time, or unpaid leave time.

. An employee is required to provide only the information enumerated in subsection (2) of this section to establish that the employee's leave is protected under this chapter or to establish that the employee's request for a safety accommodation is protected under this chapter. An employee is not required to produce or discuss any information with the employer that is beyond the scope of subsection (2) of this section, or that would compromise the employee's safety or the safety of the employee's family member in any way, and an employer is prohibited from requiring any such disclosure.

. [Empty]
.. Except as provided in (b) of this subsection, an employer shall maintain the confidentiality of all information provided by the employee under this section, including the fact that the employee or employee's family member is a victim of domestic violence, sexual assault, or stalking, that the employee has requested or obtained leave under this chapter, and any written or oral statement, documentation, record, or corroborating evidence provided by the employee.

.. Information given by an employee may be disclosed by an employer only if:

... Requested or consented to by the employee;

... Ordered by a court or administrative agency; or

... Otherwise required by applicable federal or state law.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2661.SL.pdf?cite=2018%20c%2047%20§%203[2018 c 47 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2602-S.SL.pdf?cite=2008%20c%20286%20§%204[2008 c 286 § 4]; ]

== 49.76.050 - Retention of pay or benefits—Exceptions—Health coverage.
. The taking of leave under RCW 49.76.030 may not result in the loss of any pay or benefits to the employee that accrued before the date on which the leave commenced.

. Upon an employee's return, an employer shall either:

.. Restore the employee to the position of employment held by the employee when the leave commenced; or

.. Restore the employee to an equivalent position with equivalent employment benefits, pay, and other terms and conditions of employment.

. [Empty]
.. This section does not apply if the employment from which the individual takes leave is with a staffing company and the individual is assigned on a temporary basis to perform work at or services for another organization to support or supplement the other organization's workforces, or to provide assistance in special work situations such as, but not limited to, employee absences, skill shortages, seasonal workloads, or to perform special assignments or projects, all under the direction and supervision of the organization to which the individual is assigned.

.. This section does not apply if an employee was hired for a specific term or only to perform work on a discrete project, the employment term or project is over, and the employer would not otherwise have continued to employ the employee.

. To the extent allowed by law, an employer shall maintain coverage under any health insurance plan for an employee who takes leave under RCW 49.76.030. The coverage must be maintained for the duration of the leave at the level and under the conditions coverage would have been provided if the employee had not taken the leave.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2602-S.SL.pdf?cite=2008%20c%20286%20§%205[2008 c 286 § 5]; ]

== 49.76.060 - Scope—Application—Expansion of rights.
. The rights provided in this chapter are in addition to any other rights provided by state and federal law.

. Nothing in this chapter shall be construed to discourage employers from adopting policies that provide greater leave rights or greater safety accommodations to employees who are victims of domestic violence, sexual assault, or stalking than those required by this chapter.

. Nothing in this chapter shall be construed to diminish an employer's obligation to comply with any collective bargaining agreement, or any employment benefit program or plan, that provides greater leave rights or greater safety accommodations to employees than the rights provided by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2661.SL.pdf?cite=2018%20c%2047%20§%204[2018 c 47 § 4]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2602-S.SL.pdf?cite=2008%20c%20286%20§%206[2008 c 286 § 6]; ]

== 49.76.070 - Enforcement—Complaint—Investigation—Notice of infraction.
Upon complaint by an employee, the director shall investigate to determine if there has been compliance with this chapter and the rules adopted under this chapter. If the investigation indicates that a violation has occurred, the director shall issue a notice of infraction. Appeal from the director's decision is governed by chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2602-S.SL.pdf?cite=2008%20c%20286%20§%207[2008 c 286 § 7]; ]

== 49.76.080 - Enforcement—Penalty for infraction.
. If an employer is found to have committed an infraction under RCW 49.76.070, the director may impose upon the employer a fine of up to five hundred dollars for the first infraction and a fine of up to one thousand dollars for each subsequent infraction committed within three years of a previous infraction.

. The director may also order an employer found to have committed an infraction under RCW 49.76.070 to comply with RCW 49.76.050(2).

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2602-S.SL.pdf?cite=2008%20c%20286%20§%209[2008 c 286 § 9]; ]

== 49.76.090 - Enforcement—Record confidentiality—Exceptions.
. Except as provided in subsection (2) of this section, information contained in the department's complaint files and records of employees under this chapter is confidential and shall not be open to public inspection.

. Except as limited by state or federal statute or regulations:

.. The information in subsection (1) of this section may be provided to public employees in the performance of their official duties; and

.. A complainant or a representative of a complainant, be it an individual or an organization, may review a complaint file or receive specific information therefrom upon the presentation of the signed authorization of the complainant.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2602-S.SL.pdf?cite=2008%20c%20286%20§%2010[2008 c 286 § 10]; ]

== 49.76.100 - Enforcement—Remedies—Civil actions.
. Any employee or applicant for employment deeming herself or himself injured by any act in violation of this chapter shall have a civil action in a court of competent jurisdiction to enjoin further violations, or to recover the actual damages sustained by the person, or both, together with the cost of suit including reasonable attorneys' fees.

. The remedy provided by this section is in addition to any common law remedy or other remedy that may be available to an employee.

. An employee is not required to exhaust administrative remedies before filing a civil action to enforce this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2661.SL.pdf?cite=2018%20c%2047%20§%205[2018 c 47 § 5]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2602-S.SL.pdf?cite=2008%20c%20286%20§%2012[2008 c 286 § 12]; ]

== 49.76.110 - Effect of administrative findings and conclusions on civil action.
Any finding, determination, conclusion, declaration, or notice of infraction made for the purposes of enforcing this chapter by the director or by an appeal tribunal, administrative law judge, or reviewing officer is neither conclusive nor binding in any civil action filed pursuant to RCW 49.76.100 or in any other common law or civil action, regardless of whether the prior action was between the same or related parties or involved the same facts.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2602-S.SL.pdf?cite=2008%20c%20286%20§%208[2008 c 286 § 8]; ]

== 49.76.115 - Employer conduct—Actual or perceived victim of domestic violence, sexual assault, or stalking.
An employer may not:

. Refuse to hire an otherwise qualified individual because the individual is an actual or perceived victim of domestic violence, sexual assault, or stalking;

. Discharge, threaten to discharge, demote, suspend or in any manner discriminate or retaliate against an individual with regard to promotion, compensation, or other terms, conditions, or privileges of employment because the individual is an actual or perceived victim of domestic violence, sexual assault, or stalking;

. Refuse to make a reasonable safety accommodation requested by an individual who is a victim of domestic violence, sexual assault, or stalking, unless the employer can demonstrate that the accommodation would impose an undue hardship on the operation of the business of the employer. For the purposes of this section, an "undue hardship" means an action requiring significant difficulty or expense. A reasonable safety accommodation may include, but is not limited to, a transfer, reassignment, modified schedule, changed work telephone number, changed work email address, changed workstation, installed lock, implemented safety procedure, or any other adjustment to a job structure, workplace facility, or work requirement in response to actual or threatened domestic violence, sexual assault, or stalking.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2661.SL.pdf?cite=2018%20c%2047%20§%202[2018 c 47 § 2]; ]

== 49.76.120 - Retaliation against employee.
No employer may discharge, threaten to discharge, demote, deny a promotion to, sanction, discipline, retaliate against, harass, or otherwise discriminate against an employee with respect to compensation, terms, conditions, or privileges of employment because the employee:

. Exercised rights under RCW 49.76.030 or 49.76.115;

. Filed or communicated to the employer an intent to file a complaint under RCW 49.76.070 or 49.76.100; or

. Participated or assisted, as a witness or otherwise, in another employee's attempt to exercise rights under RCW 49.76.030, 49.76.115, 49.76.070, or 49.76.100.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2661.SL.pdf?cite=2018%20c%2047%20§%206[2018 c 47 § 6]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2602-S.SL.pdf?cite=2008%20c%20286%20§%2011[2008 c 286 § 11]; ]

== 49.76.130 - Notice to employees—Employment posters—Penalty.
The department shall include notice of the provisions of this chapter in the next reprinting of employment posters. Each employer shall post and keep posted, in conspicuous places on the premises of the employer where notices to employees and applicants for employment are customarily posted, a notice, to be prepared or approved by the director, setting forth excerpts from, or summaries of, the pertinent provisions of this chapter and information pertaining to the filing of a charge. Any employer that willfully violates this section may be subject to a civil penalty of not more than one hundred dollars for each separate offense. Any penalties collected by the department under this section shall be deposited into the family and medical leave enforcement account.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5975-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%205%20§%2091[2017 3rd sp.s. c 5 § 91]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2602-S.SL.pdf?cite=2008%20c%20286%20§%2013[2008 c 286 § 13]; ]

== 49.76.140 - Notice to employees—Prosecutors—Victims' advocates.
Prosecuting attorney and victim/witness offices are encouraged to make information regarding this chapter available for distribution at their offices.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2602-S.SL.pdf?cite=2008%20c%20286%20§%2014[2008 c 286 § 14]; ]

== 49.76.150 - Authority to adopt rules.
The director shall adopt rules as necessary to implement this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2602-S.SL.pdf?cite=2008%20c%20286%20§%2015[2008 c 286 § 15]; ]

== 49.76.900 - Effective date—2008 c 286.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and takes effect immediately [April 1, 2008].

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2602-S.SL.pdf?cite=2008%20c%20286%20§%2018[2008 c 286 § 18]; ]

