= 49.80 - High hazard facilities—Workforce.
:toc:

== 49.80.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Apprenticeable occupation" means an occupation for which an apprenticeship program has been approved by the Washington state apprenticeship and training council pursuant to chapter 49.04 RCW.

. "Department" means the department of labor and industries.

. "On-site work" does not include ship and rail car support activities; environmental inspection and testing; security guard services; work which is performed by an original equipment manufacturer for warranty, repair, or maintenance on the vendor's equipment if required by the original equipment manufacturer's warranty agreement between the original equipment manufacturer and the owner; industrial cleaning not related to construction; safety services requiring professional safety certification; nonconstruction catalyst loading, regeneration, and removal; chemical purging and cleaning; refinery by-product separation and recovery; inspection services not related to construction; and work performed that is not in an apprenticeable occupation.

. "Prevailing hourly wage rate" has the meaning provided for "prevailing rate of wage" in RCW 39.12.010.

. "Registered apprentice" means an apprentice registered in an apprenticeship program approved by the Washington state apprenticeship and training council according to chapter 49.04 RCW.

. "Skilled and trained workforce" means a workforce that meets both of the following criteria:

.. All the workers are either registered apprentices or skilled journeypersons; and

.. The workforce meets the apprenticeship graduation and approved advanced safety training requirements established in RCW 49.80.030.

. "Skilled journeyperson" means a worker who meets all of the following criteria:

.. The worker either graduated from an apprenticeship program for the applicable occupation that was approved by the Washington state apprenticeship and training council according to chapter 49.04 RCW, or has at least as many hours of on-the-job experience in the applicable occupation that would be required to graduate from an apprenticeship program approved by the Washington state apprenticeship and training council according to chapter 49.04 RCW; and

.. The worker is being paid at least a rate commensurate with the wages typically paid for the occupation in the applicable geographic area, subject to the following provisions:

... The prevailing wage rate paid for a worker in the applicable occupation and geographic area on public works projects may be used to determine the appropriate rate of pay, however, this subsection (7)(b) does not require a contractor to pay prevailing wage rates; and

... In no case may the worker be paid at a rate less than an hourly rate consistent with the seventy-fifth percentile in the applicable occupation and geographic area in the most recent occupational employment statistics published by the employment security department.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1817-S.SL.pdf?cite=2019%20c%20306%20§%201[2019 c 306 § 1]; ]

== 49.80.020 - Use of skilled and trained workforce required—Advanced safety curriculum—Application.
. An owner or operator of a stationary source that is engaged in activities described in code 324110 or 325110 of the North American industry classification system, when contracting for the performance of construction, alteration, demolition, installation, repair, or maintenance work at the stationary source, shall require that its contractors and any subcontractors use a skilled and trained workforce to perform all on-site work within an apprenticeable occupation in the building and construction trades. This section shall not apply to oil and gas extraction operations.

. [Empty]
.. The department in consultation with the Washington state apprenticeship and training council shall approve a curriculum of in-person classroom and laboratory instruction for approved advanced safety training for workers at high hazard facilities.

.. The safety training must be provided by a training provider, which may include a registered apprenticeship program, approved by the department. The department must periodically review and revise the curriculum to reflect current best practices.

.. Upon receipt of certification from the approved training provider, the department must issue a certificate to a worker who completes the approved curriculum.

.. The department may accept a certificate or other documentation issued by another state if the department finds that the curriculum and documentation of the other state meets the requirements of this subsection.

. This section applies to work performed under contracts awarded, contract extensions, and contract renewals occurring on or after January 1, 2020. This section shall also apply to work performed under a contract awarded before January 1, 2020, if the work is performed more than one year after January 1, 2020.

. This section does not apply to:

.. The employees of the owner or operator of the stationary source, nor does it prevent the owner or operator of the stationary source from using its own employees to perform any work that has not been assigned to contractors while the employees of the contractor are present and working;

.. A contractor who has requested qualified workers from the local hiring halls or apprenticeship programs that dispatch workers in the apprenticeable occupation and who, due to workforce shortages, is unable to obtain sufficient qualified workers within forty-eight hours of the request, Saturdays, Sundays, and holidays excepted; and

.. Emergencies that make compliance impracticable because they require immediate action to prevent harm to public health or safety or to the environment. This section applies as soon as the emergency is over or it becomes practicable for contractors to obtain a qualified workforce.

. The requirements under subsection (1) of this section apply to each individual contractor's and subcontractor's on-site workforce.

. The requirements of this section do not make the work described in subsection (1) of this section a public work within the meaning of RCW 39.04.010.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1817-S.SL.pdf?cite=2019%20c%20306%20§%202[2019 c 306 § 2]; ]

== 49.80.030 - Implementation schedule.
The following implementation schedule must be complied with to meet the requirements of RCW 49.80.020 for a skilled and trained workforce to perform all on-site work within an apprenticeable occupation in the building and construction trades:

. [Empty]
.. By January 1, 2021, at least twenty percent of the skilled journeypersons must be graduates of an apprenticeship program for the applicable occupation approved by the Washington state apprenticeship and training council under chapter 49.04 RCW;

.. By January 1, 2022, at least thirty-five percent of the skilled journeypersons must be graduates of an apprenticeship program for the applicable occupation approved by the Washington state apprenticeship and training council under chapter 49.04 RCW;

.. By January 1, 2023, at least forty-five percent of the skilled journeypersons must be graduates of an apprenticeship program for the applicable occupation approved by the Washington state apprenticeship and training council according to chapter 49.04 RCW; and

.. By January 1, 2024, at least sixty percent of the skilled journeypersons must be graduates of an apprenticeship program for the applicable occupation approved by the Washington state apprenticeship and training council according to chapter 49.04 RCW; and

. By January 1, 2022, all workers in the skilled and trained workforce must have completed within the past three calendar years at least twenty hours of approved advanced safety training for workers at high hazard facilities.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1817-S.SL.pdf?cite=2019%20c%20306%20§%203[2019 c 306 § 3]; ]

== 49.80.040 - Failure to comply constitutes violation of chapter  49.17 RCW—Wage rate requirements constitute a wage payment requirement.
. Failure to comply with the skilled and trained workforce requirements of this chapter, except the requirement that a worker be paid at a rate commensurate with wages typically paid for the occupation, constitutes a violation of chapter 49.17 RCW.

. The wage rate requirement of RCW 49.80.010(7)(b) constitutes a wage payment requirement as defined in RCW 49.48.082.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1817-S.SL.pdf?cite=2019%20c%20306%20§%204[2019 c 306 § 4]; ]

== 49.80.050 - Consideration of new apprenticeship programs. (Expires December 31, 2023.)
. The department in consultation with the Washington state apprenticeship and training council shall prioritize consideration of new apprenticeship programs for workers in high hazard facilities. The Washington state apprenticeship and training council shall issue a decision within six months of the acceptance of a completed application for consideration of a new state registered apprenticeship program for workers in high hazard facilities.

. This section expires December 31, 2023.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1817-S.SL.pdf?cite=2019%20c%20306%20§%205[2019 c 306 § 5]; ]

== 49.80.060 - Rule-making authority.
The department may adopt rules necessary to implement this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1817-S.SL.pdf?cite=2019%20c%20306%20§%206[2019 c 306 § 6]; ]

== 49.80.900 - Effective date—2019 c 306.
This act takes effect January 1, 2020.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1817-S.SL.pdf?cite=2019%20c%20306%20§%208[2019 c 306 § 8]; ]

