= 49.94 - Job applicants—Criminal records.
:toc:

== 49.94.005 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Criminal record" includes any record about a citation or arrest for criminal conduct, including records relating to probable cause to arrest, and includes any record about a criminal or juvenile case filed with any court, whether or not the case resulted in a finding of guilt.

. "Employer" includes public agencies, private individuals, businesses and corporations, contractors, temporary staffing agencies, training and apprenticeship programs, and job placement, referral, and employment agencies.

. "Otherwise qualified" means that the applicant meets the basic criteria for the position as set out in the advertisement or job description without consideration of a criminal record.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1298-S2.SL.pdf?cite=2018%20c%2038%20§%201[2018 c 38 § 1]; ]

== 49.94.010 - Inquiries about criminal records—Timing—Advertisements—Exceptions.
. An employer may not include any question on any application for employment, inquire either orally or in writing, receive information through a criminal history background check, or otherwise obtain information about an applicant's criminal record until after the employer initially determines that the applicant is otherwise qualified for the position. Once the employer has initially determined that the applicant is otherwise qualified, the employer may inquire into or obtain information about a criminal record.

. An employer may not advertise employment openings in a way that excludes people with criminal records from applying. Ads that state "no felons," "no criminal background," or otherwise convey similar messages are prohibited.

. An employer may not implement any policy or practice that automatically or categorically excludes individuals with a criminal record from consideration prior to an initial determination that the applicant is otherwise qualified for the position. Prohibited policies and practices include rejecting an applicant for failure to disclose a criminal record prior to initially determining the applicant is otherwise qualified for the position.

. This section does not apply to:

.. Any employer hiring a person who will or may have unsupervised access to children under the age of eighteen, a vulnerable adult as defined in chapter 74.34 RCW, or a vulnerable person as defined in RCW 9.96A.060;

.. Any employer, including a financial institution, who is expressly permitted or required under any federal or state law to inquire into, consider, or rely on information about an applicant's or employee's criminal record for employment purposes;

.. Employment by a general or limited authority Washington law enforcement agency as defined in RCW 10.93.020 or by a criminal justice agency as defined in RCW 10.97.030(5)(b);

.. An employer seeking a nonemployee volunteer; or

.. Any entity required to comply with the rules or regulations of a self-regulatory organization, as defined in section 3(a)(26) of the securities and exchange act of 1934, 15 U.S.C. 78c(a)(26).

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1298-S2.SL.pdf?cite=2018%20c%2038%20§%202[2018 c 38 § 2]; ]

== 49.94.020 - Limitations on application of chapter.
. This chapter may not be construed to interfere with, impede, or in any way diminish any provision in a collective bargaining agreement or the right of employees to bargain collectively with their employers through representatives of their own choosing concerning wages, standards, and conditions of employment.

. This chapter may not be interpreted or applied to diminish or conflict with any requirements of state or federal law, including Title VII of the civil rights act of 1964; the federal fair credit reporting act, 15 U.S.C. Sec. 1681; the Washington state fair credit reporting act, chapter 19.182 RCW; and state laws regarding unsupervised access to children or vulnerable persons, RCW 43.43.830 through 43.43.845.

. This chapter may not be interpreted or applied as imposing an obligation on the part of an employer to provide accommodations or job modifications in order to facilitate the employment or continued employment of an applicant or employee with a criminal record or who is facing pending criminal charges.

. This chapter may not be construed to discourage or prohibit an employer from adopting employment policies that are more protective of employees and job applicants than the requirements of this chapter.

. This chapter may not be construed to interfere with local government laws that provide additional protections to applicants or employees with criminal records, nor does it prohibit local governments from enacting greater protections for such applicants or employees in the future. Local government laws that provide lesser protections to job applicants with criminal records than this chapter conflict with this chapter and may not be enforced.

. This chapter may not be construed to create a private right of action to seek damages or remedies of any kind. The exclusive remedy available under this chapter is enforcement described in RCW 49.94.030. This chapter does not create any additional liability for employers beyond that enumerated in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1298-S2.SL.pdf?cite=2018%20c%2038%20§%203[2018 c 38 § 3]; ]

== 49.94.030 - Attorney general's enforcement powers—Penalties.
. The state attorney general's office shall enforce this chapter. Its powers to enforce this chapter include the authority to:

.. Investigate violations of this chapter on its own initiative;

.. Investigate violations of this chapter in response to complaints and seek remedial relief for the complainant;

.. Educate the public about how to comply with this chapter;

.. Issue written civil investigative demands for pertinent documents, answers to written interrogatories, or oral testimony as required to enforce this chapter;

.. Adopt rules implementing this chapter including rules specifying applicable penalties; and

.. Pursue administrative sanctions or a lawsuit in the courts for penalties, costs, and attorneys' fees.

. In exercising its powers, the attorney general's office shall utilize a stepped enforcement approach, by first educating violators, then warning them, then taking legal, including administrative, action. Maximum penalties are as follows: A notice of violation and offer of agency assistance for the first violation; a monetary penalty of up to seven hundred fifty dollars for the second violation; and a monetary penalty of up to one thousand dollars for each subsequent violation.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1298-S2.SL.pdf?cite=2018%20c%2038%20§%204[2018 c 38 § 4]; ]

== 49.94.900 - Conflict with federal requirements—2018 c 38.
If any part of this act is found to be in conflict with federal requirements that are a prescribed condition to the allocation of federal funds to the state, the conflicting part of this act is inoperative solely to the extent of the conflict and with respect to the agencies directly affected, and this finding does not affect the operation of the remainder of this act in its application to the agencies concerned. Rules adopted under this act must meet federal requirements that are a necessary condition to the receipt of federal funds by the state.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1298-S2.SL.pdf?cite=2018%20c%2038%20§%206[2018 c 38 § 6]; ]

== 49.94.901 - Short title—2018 c 38.
This act may be known and cited as the Washington fair chance act.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1298-S2.SL.pdf?cite=2018%20c%2038%20§%208[2018 c 38 § 8]; ]

