= 70A.02 - Environmental justice.
:toc:

== 70A.02.005 - Purpose.
. The purpose of this chapter is to reduce environmental and health disparities in Washington state and improve the health of all Washington state residents. This chapter implements the recommendations of the environmental justice task force established in section 221(48), chapter 415, Laws of 2019 entitled "Report to the Washington state governor and legislature, Environmental Justice Task Force: Recommendations for Prioritizing EJ in Washington State Government (October 2020)."

. As conveyed in the task force report, Washington state studies and national studies found that people of color and low-income people continue to be disproportionately exposed to environmental harms in their communities. As a result, there is a higher risk of adverse health outcomes for those communities. This risk is amplified when overlaid on communities with preexisting social and economic barriers and environmental risks, and creates cumulative environmental health impacts, which chapter 314, Laws of 2021 seeks to prevent and mitigate.

This chapter also seeks to reduce exposure to environmental hazards within Indian country, as defined in 18 U.S.C. Sec. 1151, due to off-reservation activities within the state, and to improve state practices to reduce contamination of traditional foods wherever they occur. Exposure to such hazards can result in generational health and ecological problems, particularly on small reservations where it is impossible to move away from a hazard.

. Accordingly, the state has a compelling interest in preventing and addressing such environmental health disparities in the administration of ongoing and new environmental programs, including allocation of funds, and in administering these programs so as to remedy the effects of past disparate treatment of overburdened communities and vulnerable populations.

. The task force provided recommendations to state agencies for measurable goals and model policies to reduce environmental health inequities in Washington, equitable practices for meaningful community involvement, and how to use the environmental health disparities map to identify and promote the equitable distribution of environmental benefits to overburdened communities. In order for all communities in Washington state to be healthy and thriving, state government should aim to concentrate government actions to benefit communities that currently have the greatest environmental and health burdens.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5141-S2.SL.pdf?cite=2021%20c%20314%20§%201[2021 c 314 § 1]; ]

== 70A.02.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Council" means the environmental justice council established in RCW 70A.02.110.

. "Covered agency" means the departments of ecology, health, natural resources, commerce, agriculture, and transportation, the Puget Sound partnership, and any agency that opts to assume all of the obligations of chapter 314, Laws of 2021 pursuant to RCW 70A.02.030.

. "Cumulative environmental health impact" means the combined, multiple environmental impacts and health impacts on a vulnerable population or overburdened community.

. "Environmental benefits" means activities that:

.. Prevent or reduce existing environmental harms or associated risks that contribute significantly to cumulative environmental health impacts;

.. Prevent or mitigate impacts to overburdened communities or vulnerable populations from, or support community response to, the impacts of environmental harm; or

.. Meet a community need formally identified to a covered agency by an overburdened community or vulnerable population that is consistent with the intent of this chapter.

. "Environmental harm" means the individual or cumulative environmental health impacts and risks to communities caused by historic, current, or projected:

.. Exposure to pollution, conventional or toxic pollutants, environmental hazards, or other contamination in the air, water, and land;

.. Adverse environmental effects, including exposure to contamination, hazardous substances, or pollution that increase the risk of adverse environmental health outcomes or create vulnerabilities to the impacts of climate change;

.. Loss or impairment of ecosystem functions or traditional food resources or loss of access to gather cultural resources or harvest traditional foods; or

.. Health and economic impacts from climate change.

. "Environmental health disparities map" means the data and information developed pursuant to RCW 43.70.815.

. "Environmental impacts" means environmental benefits or environmental harms, or the combination of environmental benefits and harms, resulting or expected to result from a proposed action.

. "Environmental justice" means the fair treatment and meaningful involvement of all people regardless of race, color, national origin, or income with respect to the development, implementation, and enforcement of environmental laws, rules, and policies. Environmental justice includes addressing disproportionate environmental and health impacts in all laws, rules, and policies with environmental impacts by prioritizing vulnerable populations and overburdened communities, the equitable distribution of resources and benefits, and eliminating harm.

. "Equitable distribution" means a fair and just, but not necessarily equal, allocation intended to mitigate disparities in benefits and burdens that are based on current conditions, including existing legacy and cumulative impacts, that are informed by cumulative environmental health impact analysis.

. "Evidence-based" means a process that is conducted by a systematic review of available data based on a well-established and widely used hierarchy of data in current use by other state and national programs, selected by the departments of ecology and health. The environmental justice council may provide input on the development of the process.

. "Overburdened community" means a geographic area where vulnerable populations face combined, multiple environmental harms and health impacts, and includes, but is not limited to, highly impacted communities as defined in RCW 19.405.020.

. "Significant agency action" means the following actions as identified at the beginning of a covered agency's consideration of the significant agency action or at the time when an environmental justice assessment would normally be initiated in conjunction with an agency action:

.. The development and adoption of significant legislative rules as defined in RCW 34.05.328;

.. The development and adoption of any new grant or loan program that a covered agency is explicitly authorized or required by statute to carry out;

.. A capital project, grant, or loan award by a covered agency of at least $12,000,000 or a transportation project, grant, or loan by a covered agency of at least $15,000,000;

.. The submission of agency request legislation to the office of the governor or the office of financial management for approval; and

.. Any other agency actions deemed significant by a covered agency consistent with RCW 70A.02.060.

. "Tribal lands" has the same meaning as "Indian country" as provided in 18 U.S.C. Sec. 1151, and also includes sacred sites, traditional cultural properties, burial grounds, and other tribal sites protected by federal or state law.

. [Empty]
.. "Vulnerable populations" means population groups that are more likely to be at higher risk for poor health outcomes in response to environmental harms, due to: (i) Adverse socioeconomic factors, such as unemployment, high housing and transportation costs relative to income, limited access to nutritious food and adequate health care, linguistic isolation, and other factors that negatively affect health outcomes and increase vulnerability to the effects of environmental harms; and (ii) sensitivity factors, such as low birth weight and higher rates of hospitalization.

.. "Vulnerable populations" includes, but is not limited to:

... Racial or ethnic minorities;

... Low-income populations;

... Populations disproportionately impacted by environmental harms; and

... Populations of workers experiencing environmental harms.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5141-S2.SL.pdf?cite=2021%20c%20314%20§%202[2021 c 314 § 2]; ]

== 70A.02.020 - Environmental justice obligations for all agencies.
Covered agencies are required to comply with all provisions of this chapter. All other state agencies should strive to apply the laws of the state of Washington, and the rules and policies of the agency, in accordance with the policies of this chapter including, to the extent feasible, incorporating the principles of environmental justice assessment processes set forth in RCW 70A.02.060 into agency decisions.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5141-S2.SL.pdf?cite=2021%20c%20314%20§%203[2021 c 314 § 3]; ]

== 70A.02.030 - Authority of other agencies to opt in to environmental justice obligations.
. Any state agency, as the term "agency" is defined in RCW 34.05.010, including the governor's office and the office of the attorney general but excluding local governmental entities, may opt in to assume all of the substantive and procedural requirements of covered agencies under chapter 70A.02 RCW at any time by notifying the council established in RCW 70A.02.110.

. An agency that opts in to assume all of the substantive and procedural requirements of chapter 70A.02 RCW is not subject to the deadlines or timelines established in RCW 70A.02.040, 70A.02.050, 70A.02.060, 70A.02.080, and 70A.02.110.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5141-S2.SL.pdf?cite=2021%20c%20314%20§%2011[2021 c 314 § 11]; ]

== 70A.02.040 - Incorporating environmental justice into agency strategic plans.
. By January 1, 2023, each covered agency shall include an environmental justice implementation plan within its strategic plan. A covered agency may additionally incorporate an environmental justice implementation plan into other significant agency planning documents. The plan must describe how the covered agency plans to apply the principles of environmental justice to the agency's activities and must guide the agency in its implementation of its obligations under this chapter.

. In its environmental justice implementation plan, each covered agency must include:

.. Agency-specific goals and actions to reduce environmental and health disparities and for otherwise achieving environmental justice in the agency's programs;

.. Metrics to track and measure accomplishments of the agency goals and actions;

.. Methods to embed equitable community engagement with, and equitable participation from, members of the public, into agency practices for soliciting and receiving public comment;

.. Strategies to ensure compliance with existing federal and state laws and policies relating to environmental justice, including Title VI of the civil rights act of 1964, 42 U.S.C. Sec. 2000d-2000d-4, Title IX of the Education Amendments of 1972, 20 U.S.C. Sec. 1681-1683, Section 504 of the Rehabilitation Act of 1973, 29 U.S.C. Sec. 794, and the age discrimination act of 1975, 42 U.S.C. Sec. 6101-6107;

.. The plan for community engagement required under RCW 70A.02.050; and

.. Specific plans and timelines for incorporating environmental justice considerations into agency activities as required under this chapter.

. In developing and updating its plan, each covered agency must consider any guidance developed by the council pursuant to RCW 70A.02.110.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5141-S2.SL.pdf?cite=2021%20c%20314%20§%2012[2021 c 314 § 12]; ]

== 70A.02.050 - Equitable community engagement and public participation.
. By July 1, 2022, each covered agency must create and adopt a community engagement plan that describes how it will engage with overburdened communities and vulnerable populations as it evaluates new and existing activities and programs. This plan must describe how the agency plans to facilitate equitable participation and support meaningful and direct involvement of vulnerable populations and overburdened communities. The plan must include:

.. How the covered agency will identify and prioritize overburdened communities for purposes of this chapter;

.. Best practices for outreach and communication to overcome barriers to engagement with overburdened communities and vulnerable populations;

.. Use of special screening tools that integrate environmental, demographic, and health disparities data, such as the environmental health disparities map, to evaluate and understand the nature and needs of the people who the agency expects to be impacted by significant agency actions under RCW 70A.02.060 and processes under RCW 70A.02.080 to overcome barriers to participation;

.. Processes that facilitate and support the inclusion of members of communities affected by agency decision making including, to the extent legal and practicable, but not limited to, child care and reimbursement for travel and other expenses; and

.. Methods for outreach and communication with those who face barriers, language or otherwise, to participation.

. Covered agencies must regularly review their compliance with existing laws and policies that guide community engagement and must comply with the following:

.. Title VI of the civil rights act, prohibiting discrimination based on race, color, or national origin and requiring meaningful access to people with limited English proficiency, and disability;

.. Executive Order 05-03, requiring plain talk when communicating with the public; and

.. Guidance related to Executive Order 13166, requiring meaningful access to agency programs and services for people with limited English proficiency.

. In developing and updating its plan, each covered agency must consider any guidance developed by the council pursuant to RCW 70A.02.110.

. A covered agency may coordinate with the office of equity to identify policy and system barriers to meaningful engagement with communities as conducted by the office under RCW 43.06D.040(1)(b).

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5141-S2.SL.pdf?cite=2021%20c%20314%20§%2013[2021 c 314 § 13]; ]

== 70A.02.060 - Environmental justice assessment.
. [Empty]
.. When considering a significant agency action initiated after July 1, 2023, a covered agency must conduct an environmental justice assessment in accordance with this section to inform and support the agency's consideration of overburdened communities and vulnerable populations when making decisions and to assist the agency with the equitable distribution of environmental benefits, the reduction of environmental harms, and the identification and reduction of environmental and health disparities.

.. A covered agency must aspire to complete the environmental justice assessment for a significant agency action without delaying the completion of the underlying agency action.

. [Empty]
.. Consistent with RCW 70A.02.010(12)(e), for the purpose of preparing environmental justice assessments, a covered agency may deem actions significant that are additional to the significant agency actions identified in RCW 70A.02.010(12) (a) through (d), in iterative consultation with the council and interagency work group established under RCW 70A.02.110. By July 1, 2025, each covered agency must consider their agency's activities and identify and begin applying environmental justice assessments to any actions that the agency identifies as significant that are in addition to the significant agency actions identified in RCW 70A.02.010(12) (a) through (d). Significant agency actions designated by a covered agency under this subsection must be actions that may cause environmental harm or may affect the equitable distribution of environmental benefits to an overburdened community or a vulnerable population.

.. In the identification of significant agency actions, covered agencies shall consider guidance issued by the council established in RCW 70A.02.110. Each covered agency must periodically review and update its identified types of significant agency actions for which an environmental justice assessment is required under this section, and the relevant factors to the agency's environmental justice assessments that result from the unique mission, authorities, and priorities of the agency.

. By July 1, 2023, and periodically thereafter, after an opportunity for public comment on its determinations, each covered agency must:

.. Publish on its website the types of agency actions that the agency has determined are significant agency actions that require an environmental justice assessment under this section, including any significant agency actions identified under subsection (2)(a) of this section;

.. Provide notification of the determination of the types of significant agency actions in the Washington State Register; and

.. Prepare an environmental justice assessment when considering a listed action, after publication of the list of any additional significant agency actions identified under (a) of this subsection.

. The environmental justice assessment obligation of a covered agency for a significant agency action under this section is satisfied by the completion by the covered agency of a checklist developed by the covered agency that functions akin to the environmental checklist developed by the department of ecology pursuant to chapter 43.21C RCW, and that directs the covered agency to at a minimum:

.. Consider guidance prepared by the council under RCW 70A.02.110 relating to best practices on environmental justice assessments and when and how to use cumulative environmental health impact analysis;

.. Where applicable, use cumulative environmental health impact analysis, such as the environmental health disparities map or other data that considers the effects of a proposed action on overburdened communities and vulnerable populations;

.. Identify overburdened communities and vulnerable populations who are expected to be affected by the proposed action and the potential environmental and health impacts;

.. Pursuant to the consultation process in RCW 70A.02.100, identify if the proposed action is expected to have any local or regional impacts to federally reserved tribal rights and resources including, but not limited to, those protected by treaty, executive order, or federal law;

.. Summarize community input and describe how the covered agency can further involve overburdened communities, vulnerable populations, affected tribes, and indigenous populations in development of the proposed action; and

.. Describe options for the agency to reduce, mitigate, or eliminate identified probable impacts on overburdened communities and vulnerable populations, or provide a justification for not reducing, mitigating, or eliminating identified probable impacts.

. [Empty]
.. To obtain information for the purposes of assessments, a covered agency must solicit feedback from members of overburdened communities and vulnerable populations to assist in the accurate assessment of the potential impact of the action and in developing the means to reduce or eliminate the impact on overburdened communities and vulnerable populations.

.. A covered agency may include items in the checklist required under subsection (4) of this section that are not specified in subsection (4) of this section.

.. The completion of an environmental justice checklist under subsection (4) of this section is not required to be a comprehensive or an exhaustive examination of all potential impacts of a significant agency action and does not require a covered agency to conduct novel quantitative or economic analysis of the proposed significant agency action.

. Based on the environmental justice assessment, each covered agency must seek, to the extent legal and feasible and consistent with the underlying statute being implemented, to reduce or eliminate the environmental harms and maximize the environmental benefits created by the significant agency action on overburdened communities and vulnerable populations. Consistent with agency authority, mission, and statutory responsibilities, the covered agency must consider each of the following methods for reducing environmental harms or equitably distributing environmental benefits:

.. Eliminating the disparate impact of environmental harms on overburdened communities and vulnerable populations;

.. Reducing cumulative environmental health impacts on overburdened communities or vulnerable populations;

.. Preventing the action from adding to the cumulative environmental health impacts on overburdened communities or vulnerable populations;

.. Providing equitable participation and meaningful engagement of vulnerable populations and overburdened communities in the development of the significant agency action;

.. Prioritizing equitable distribution of resources and benefits to overburdened communities;

.. Promoting positive workforce and job outcomes for overburdened communities;

.. Meeting community needs identified by the affected overburdened community;

.. Modifying substantive regulatory or policy requirements; and

.. Any other mitigation techniques, including those suggested by the council, the office of equity, or representatives of overburdened communities and vulnerable populations.

. If the covered agency determines it does not have the ability or authority to avoid or reduce any estimated environmental harm of the significant agency action on overburdened communities and vulnerable populations or address the distribution of environmental and health benefits, the agency must provide a clear explanation of why it has made that determination and provide notice of that explanation to members of the public who participated in the process for the significant agency action or the process for the environmental justice assessment and who provided contact information to the agency.

. In developing a process for conducting environmental justice assessments, each covered agency must consider any guidance developed by the council pursuant to RCW 70A.02.110.

. The issuance of forest practices permits under chapter 76.09 RCW or sale of timber from state lands and state forestlands as defined in RCW 79.02.010 do not require an environmental justice assessment under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5141-S2.SL.pdf?cite=2021%20c%20314%20§%2014[2021 c 314 § 14]; ]

== 70A.02.070 - Obligation of a covered agency—Does not trigger chapter  43.21C RCW requirements.
The obligation of a covered agency to conduct an environmental justice assessment pursuant to RCW 70A.02.060 for significant agency actions does not, by itself, trigger requirements in chapter 43.21C RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5141-S2.SL.pdf?cite=2021%20c%20314%20§%2015[2021 c 314 § 15]; ]

== 70A.02.080 - Environmental justice obligations of agencies relating to budgets and funding.
. With consideration of the guidelines issued by the council in RCW 70A.02.110, and in iterative consultation with the council, each covered agency must incorporate environmental justice principles into its decision processes for budget development, making expenditures, and granting or withholding environmental benefits. Through the incorporation of environmental justice principles into its decision processes, including by conducting environmental justice assessments where required under RCW 70A.02.060, each covered agency, to the extent allowed by law and consistent with legislative appropriations, must equitably distribute funding and expenditures related to programs that address or may cause environmental harms or provide environmental benefits towards overburdened communities and vulnerable populations.

. Beginning on or before July 1, 2023, each covered agency must, where practicable, take the following actions when making expenditure decisions or developing budget requests to the office of financial management and the legislature for programs that address or may cause environmental harms or provide environmental benefits:

.. Focus applicable expenditures on creating environmental benefits that are experienced by overburdened communities and vulnerable populations, including reducing or eliminating environmental harms, creating community and population resilience, and improving the quality of life of overburdened communities and vulnerable populations;

.. Create opportunities for overburdened communities and vulnerable populations to meaningfully participate in agency expenditure decisions;

.. Clearly articulate environmental justice goals and performance metrics to communicate the basis for agency expenditures;

.. Consider a broad scope of grants and contracting opportunities that effectuate environmental justice principles, including:

... Community grants to monitor pollution;

... Grants focused on building capacity and providing training for community scientists and other staff;

... Making technical assistance available for communities that may be new to receiving agency grant funding; and

... Education and work readiness youth programs focused on infrastructure or utility-related internships to develop career paths and leadership skills for youth; and

.. Establish a goal of directing 40 percent of grants and expenditures that create environmental benefits to vulnerable populations and overburdened communities.

. A covered agency may adopt rules or guidelines for criteria and procedures applicable to incorporating environmental justice principles in expenditure decisions, granting or withholding benefits, and processes for budget development.

. In incorporating environmental justice principles into its decision processes for budget development, making expenditures, and granting or withholding benefits, each covered agency must consider any guidance developed by the council pursuant to RCW 70A.02.110.

. A covered agency may not take actions or make expenditures under this section that are inconsistent with or conflict with other statutes or with conditions or limitations on the agency's appropriations.

. If a covered agency, due to the breadth of its programs and funding opportunities, determines it is not practicable to take the actions listed in subsection (2) of this section for all applicable expenditure decisions and budget requests developed, the covered agency is encouraged to prioritize taking the actions listed in subsection (2) of this section for those budget requests and expenditure decisions that are primarily directed at addressing environmental impacts. By July 1, 2023, each covered agency must publish on its website the types of decision processes for budget development, making expenditures, and granting or withholding environmental benefits for which the agency will take the actions listed in subsection (2) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5141-S2.SL.pdf?cite=2021%20c%20314%20§%2016[2021 c 314 § 16]; ]

== 70A.02.090 - Reporting requirements.
. By September 1st of each year, each covered agency must annually update the council on the development and implementation of environmental justice in agency strategic plans pursuant to RCW 70A.02.040, budgeting and funding criteria for making budgeting and funding decisions pursuant to RCW 70A.02.080, and community engagement plans pursuant to RCW 70A.02.050.

. [Empty]
.. Beginning in 2024, as part of each covered agency's annual update to the council under subsection (1) of this section, each covered agency must include updates on the agency's implementation status with respect to the environmental justice assessments under RCW 70A.02.060.

.. By September 1st of each year beginning in 2024, each covered agency must publish or update a dashboard report, in a uniform dashboard format on the office of financial management's website, describing the agency's progress on:

... Incorporating environmental justice in its strategic plan;

... The obligations of agencies relating to budgets and funding under RCW 70A.02.080; and

... Its environmental justice assessments of proposed significant agency actions, including logistical metrics related to covered agency completion of environmental justice assessments.

. Each covered agency must file a notice with the office of financial management of significant agency actions for which the agency is initiating an environmental justice assessment under RCW 70A.02.060. The office of financial management must prepare a list of all filings received from covered agencies each week and must post the list on its website and make it available to any interested parties. The list of filings must include a brief description of the significant agency action and the methods for providing public comment for agency consideration as part of the environmental justice assessment.

. Each covered agency must identify overburdened communities, as required by RCW 70A.02.050, in such a way that the performance effectiveness of the duties created by this chapter can be measured, including the effectiveness of environmental justice assessments required by RCW 70A.02.060. Each covered agency may identify and prioritize overburdened communities as needed to accomplish the purposes of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5141-S2.SL.pdf?cite=2021%20c%20314%20§%2017[2021 c 314 § 17]; ]

== 70A.02.100 - Tribal consultation.
. Covered agencies shall develop a consultation framework in coordination with tribal governments that includes best practices, protocols for communication, and collaboration with federally recognized tribes. Consistent with this framework, covered agencies must offer consultation with federally recognized Indian tribes on:

.. The inclusion or updating of an environmental justice implementation plan within the covered agency's strategic plan required under RCW 70A.02.040;

.. The creation and adoption or updating of a community engagement plan required under RCW 70A.02.050; and

.. Significant agency actions under RCW 70A.02.060 that affect federally recognized Indian tribes' rights and interests in their tribal lands.

. The department of health must offer consultation with federally recognized Indian tribes on the development of the environmental health disparities map under RCW 43.70.815.

. The consultation under subsections (1) and (2) of this section must be independent of any public participation process required by state law, or by a state agency, and regardless of whether the agency receives a request for consultation from an Indian tribe.

. Nothing in this chapter is intended to direct, authorize, or encourage covered agencies to collect, maintain, or provide data related to sacred sites, traditional cultural properties, burial grounds, and other tribal sites protected by federal or state law.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5141-S2.SL.pdf?cite=2021%20c%20314%20§%2018[2021 c 314 § 18]; ]

== 70A.02.110 - Environmental justice council.
. The environmental justice council is established to advise covered agencies on incorporating environmental justice into agency activities.

. The council consists of 14 members appointed by the governor. The councilmembers must be persons who are well-informed regarding and committed to the principles of environmental justice and who, to the greatest extent practicable, represent diversity in race, ethnicity, age, and gender, urban and rural areas, and different regions of the state. The members of the council shall elect two members to serve as cochairs for two-year terms. The council must include:

.. Seven community representatives, including one youth representative, the nominations of which are based upon applied and demonstrated work and focus on environmental justice or a related field, such as racial or economic justice, and accountability to vulnerable populations and overburdened communities;

... The youth representative must be between the ages of 18 and 25 at the time of appointment;

... The youth representative serves a two-year term. All other community representatives serve four-year terms, with six representatives initially being appointed to four-year terms and five being initially appointed to two-year terms, after which they will be appointed to four-year terms;

.. Two members representing tribal communities, one from eastern Washington and one from western Washington, appointed by the governor. The governor shall solicit and consider nominees from each of the federally recognized tribes in Washington state. The governor shall collaborate with federally recognized tribes on the selection of tribal representatives. The tribal representatives serve four-year terms. One representative must be initially appointed for a four-year term. The other representative must be initially appointed for a two-year term, after which, that representative must be appointed for a four-year term;

.. Two representatives who are environmental justice practitioners or academics to serve as environmental justice experts, the nominations of which are based upon applied and demonstrated work and focus on environmental justice;

.. [Empty]
... One representative of a business that is regulated by a covered agency and whose ordinary business conditions are significantly affected by the actions of at least one other covered agency; and

... One representative who is a member or officer of a union representing workers in the building and construction trades; and

.. One representative at large, the nomination of which is based upon applied and demonstrated work and focus on environmental justice.

. Covered agencies shall serve as nonvoting, ex officio liaisons to the council. Each covered agency must identify an executive team level staff person to participate on behalf of the agency.

. Nongovernmental members of the council must be compensated and reimbursed in accordance with RCW 43.03.050, 43.03.060, and 43.03.220.

. The department of health must:

.. Hire a manager who is responsible for overseeing all staffing and administrative duties in support of the council; and

.. Provide all administrative and staff support for the council.

. In collaboration with the office of equity, the office of financial management, the council, and covered agencies, the department of health must:

.. Establish standards for the collection, analysis, and reporting of disaggregated data as it pertains to tracking population level outcomes of communities;

.. Create statewide and agency-specific process and outcome measures to show performance:

... Using outcome-based methodology to determine the effectiveness of agency programs and services on reducing environmental disparities; and

... Taking into consideration community feedback from the council on whether the performance measures established accurately measure the effectiveness of covered agency programs and services in the communities served; and

.. Create an online performance dashboard to publish performance measures and outcomes as referenced in RCW 70A.02.090 for the state and each covered agency.

. The department of health must coordinate with the consolidated technology services agency to address cybersecurity and data protection for all data collected by the department.

. [Empty]
.. With input and assistance from the council, the department of health must establish an interagency work group to assist covered agencies in incorporating environmental justice into agency decision making. The work group must include staff from each covered agency directed to implement environmental justice provisions under this chapter and may include members from the council. The department of health shall provide assistance to the interagency work group by:

... Facilitating information sharing among covered agencies on environmental justice issues and between agencies and the council;

... Developing and providing assessment tools for covered agencies to use in the development and evaluation of agency programs, services, policies, and budgets;

... Providing technical assistance and compiling and creating resources for covered agencies to use; and

... Training covered agency staff on effectively using data and tools for environmental justice assessments.

.. The duties of the interagency work group include:

... Providing technical assistance to support agency compliance with the implementation of environmental justice into their strategic plans, environmental justice obligations for budgeting and funding criteria and decisions, environmental justice assessments, and community engagement plans;

... Assisting the council in developing a suggested schedule and timeline for sequencing the types of: (A) Funding and expenditure decisions subject to rules; and (B) criteria incorporating environmental justice principles;

... Identifying other policies, priorities, and projects for the council's review and guidance development;

... Identifying goals and metrics that the council may use to assess agency performance in meeting the requirements of chapter 314, Laws of 2021 for purposes of communicating progress to the public, the governor, and the legislature; and

.. Developing the guidance under subsection (9)(c) of this section in coordination with the council.

. The council has the following powers and duties:

.. To provide a forum for the public to:

... Provide written or oral testimony on their environmental justice concerns;

... Assist the council in understanding environmental justice priorities across the state in order to develop council recommendations to agencies for issues to prioritize; and

... Identify which agencies to contact with their specific environmental justice concerns and questions;

.. [Empty]
... The council shall work in an iterative fashion with the interagency work group to develop guidance for environmental justice implementation into covered agency strategic plans pursuant to RCW 70A.02.040, environmental justice assessments pursuant to RCW 70A.02.060, budgeting and funding criteria for making budgeting and funding decisions pursuant to RCW 70A.02.080, and community engagement plans pursuant to RCW 70A.02.050;

... The council and interagency work group shall regularly update its guidance;

.. In consultation with the interagency work group, the council:

... Shall provide guidance to covered agencies on developing environmental justice assessments pursuant to RCW 70A.02.060 for significant agency actions;

... Shall make recommendations to covered agencies on which agency actions may cause environmental harm or may affect the equitable distribution of environmental benefits to an overburdened community or a vulnerable population and therefore should be considered significant agency actions that require an environmental justice assessment under RCW 70A.02.060;

... Shall make recommendations to covered agencies:

(A) On the identification and prioritization of overburdened communities under this chapter; and

(B) Related to the use by covered agencies of the environmental and health disparities map in agency efforts to identify and prioritize overburdened communities;

... May make recommendations to a covered agency on the timing and sequencing of a covered agencies' efforts to implement RCW 70A.02.040 through 70A.02.080; and

.. May make recommendations to the governor and the legislature regarding ways to improve agency compliance with the requirements of this chapter;

.. By December 1, 2023, and biennially thereafter, and with consideration of the information shared on September 1st each year in covered agencies' annual updates to the council required under RCW 70A.02.090, the council must:

... Evaluate the progress of each agency in applying council guidance, and update guidance as needed; and

... Communicate each covered agency's progress to the public, the governor, and the legislature. This communication is not required to be a report and may take the form of a presentation or other format that communicates the progress of the state and its agencies in meeting the state's environmental justice goals in compliance with chapter 314, Laws of 2021, and summarizing the work of the council pursuant to (a) through (d) of this subsection, and subsection (11) of this section.

. By November 30, 2023, and in compliance with RCW 43.01.036, the council must submit a report to the governor and the appropriate committees of the house of representatives and the senate on:

.. The council's recommendations to covered agencies on the identification of significant agency actions requiring an environmental justice assessment under subsection (9)(c)(ii) of this section;

.. The summary of covered agency progress reports provided to the council under RCW 70A.02.090(1), including the status of agency plans for performing environmental justice assessments required by RCW 70A.02.060; and

.. Guidance for environmental justice implementation into covered agency strategic plans, environmental justice assessments, budgeting and funding criteria, and community engagement plans under subsection (9)(c)(i) of this section.

. The council may:

.. Review incorporation of environmental justice implementation plans into covered agency strategic plans pursuant to RCW 70A.02.040, environmental justice assessments pursuant to RCW 70A.02.060, budgeting and funding criteria for making budgeting and funding decisions pursuant to RCW 70A.02.080, and community engagement plans pursuant to RCW 70A.02.050;

.. Make recommendations for amendments to this chapter or other legislation to promote and achieve the environmental justice goals of the state;

.. Review existing laws and make recommendations for amendments that will further environmental justice;

.. Recommend to specific agencies that they create environmental justice-focused, agency-requested legislation;

.. Provide requested assistance to state agencies other than covered agencies that wish to incorporate environmental justice principles into agency activities; and

.. Recommend funding strategies and allocations to build capacity in vulnerable populations and overburdened communities to address environmental justice.

. The role of the council is purely advisory and council decisions are not binding on an agency, individual, or organization.

. The department of health must convene the first meeting of the council by January 1, 2022.

. All council meetings are subject to the open public meetings requirements of chapter 42.30 RCW and a public comment period must be provided at every meeting of the council.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5141-S2.SL.pdf?cite=2021%20c%20314%20§%2020[2021 c 314 § 20]; ]

== 70A.02.120 - Legal obligations.
. Nothing in chapter 314, Laws of 2021 prevents state agencies that are not covered agencies from adopting environmental justice policies and processes consistent with chapter 314, Laws of 2021.

. The head of a covered agency may, on a case-by-case basis, exempt a significant agency action or decision process from the requirements of RCW 70A.02.060 and 70A.02.080 upon determining that:

.. Any delay in the significant agency action poses a potentially significant threat to human health or the environment, or is likely to cause serious harm to the public interest;

.. An assessment would delay a significant agency decision concerning the assessment, collection, or administration of any tax, tax program, debt, revenue, receipt, a regulated entity's financial filings, or insurance rate or form filing;

.. The requirements of RCW 70A.02.060 and 70A.02.080 are in conflict with:

... Federal law or federal program requirements;

... The requirements for eligibility of employers in this state for federal unemployment tax credits; or

... Constitutional limitations or fiduciary obligations, including those applicable to the management of state lands and state forestlands as defined in RCW 79.02.010.

. A covered agency may not, for the purposes of implementing any of its responsibilities under this chapter, contract with an entity that employs a lobbyist registered under RCW 42.17A.600 that is lobbying on behalf of that entity.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5141-S2.SL.pdf?cite=2021%20c%20314%20§%2021[2021 c 314 § 21]; ]

== 70A.02.130 - Appeals.
. Except as specified in subsection (2) of this section, the actions and duties set forth in chapter 314, Laws of 2021 are not subject to appeal.

. [Empty]
.. Only the following agency actions undertaken pursuant to chapter 314, Laws of 2021 are subject to appeal:

... Decisions related to the designation of significant agency actions pursuant to RCW 70A.02.060(3)(a); and

... Environmental justice assessments prepared pursuant to RCW 70A.02.060, only for environmental justice assessments for which there is an associated agency action that is appealable.

.. Appeals of environmental justice assessments allowed under (a)(ii) of this subsection must be of the environmental justice assessment together with the accompanying agency action, as defined in RCW 34.05.010.

. Nothing in chapter 314, Laws of 2021 may be construed to create a new private right of action, other than as described in this section, on the part of any individual, entity, or agency against any state agency.

. Nothing in chapter 314, Laws of 2021 may be construed to expand, contract, or otherwise modify any rights of appeal, or procedures for appeal, under other laws other than the availability of the appeal process described in this section.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5141-S2.SL.pdf?cite=2021%20c%20314%20§%2022[2021 c 314 § 22]; ]

