= 70A.450 - Labeling of building materials containing asbestos.
:toc:

== 70A.450.010 - Purpose of chapter.
Asbestos is a known human carcinogen that causes painful, premature deaths due to diseases such as asbestosis, mesothelioma, lung and gastrointestinal cancers, and other diseases and cancers. Activities that can lead to the release of asbestos fibers include installation, use, maintenance, repair, removal, and disposal of asbestos-containing building materials.

Many people are unaware that asbestos-containing building materials are still imported, sold, and used in the United States. Because few regulations exist that require the disclosure of asbestos in building materials, people can unknowingly be exposed to asbestos. Asbestos is generally invisible, odorless, very durable, and highly aerodynamic. Exposure can occur well after it has been disturbed and long distances from where the asbestos release occurred.

The purpose of this chapter is to allow people to make informed decisions regarding whether or not they purchase or use building materials containing asbestos. More specifically, building materials that contain asbestos must be clearly labeled as such by manufacturers, wholesalers, and distributors.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5458-S.SL.pdf?cite=2013%20c%2051%20§%201[2013 c 51 § 1]; ]

== 70A.450.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Asbestos" includes the asbestiform varieties of actinolite, amosite (cummingtonite-grunerite), tremolite, chrysotile (serpentine), crocidolite (riebeckite), anthophyllite, and any of these minerals that have been chemically treated or altered. The chemical abstracts service registry number for each is as follows: Asbestos (1332-21-4), actinolite (13768-00-8), amosite (12172-73-5), tremolite (14567-73-8), chrysotile (12001-29-5), crocidolite (12001-28-4), and anthophyllite (17068-78-9).

. "Asbestos-containing building material" means:

.. Until January 1, 2025, any building material to which asbestos is deliberately added in any concentration or that contains more than one percent asbestos by weight or area as determined using the United States environmental protection agency method for the determination of asbestos in building materials, EPA/600/R-93/116, July 1993; and

.. Beginning January 1, 2025, any building material to which asbestos is deliberately added in any concentration or that contains more than one-tenth of one percent asbestos by weight or area as determined using the United States environmental protection agency method for the determination of asbestos in building materials, EPA/600/R-93/116, July 1993.

. "Building material" includes materials designed for, or used in, construction, renovation, repair, or maintenance of institutional, commercial, public, industrial, or residential buildings and structures. The term does not include automobiles, recreational vehicles, boats, or other mobile means of transportation.

. "Consumer" means any person that acquires a building material for direct use or ownership, rather than for resale or use in production and manufacturing.

. "Department" means the department of ecology.

. "Interested party" means any contractor, subcontractor, or worker that performs, or is reasonably expected to perform, work at a facility covered under RCW 70A.450.070 or any organization whose members perform, or are reasonably expected to perform, work at a facility covered under RCW 70A.450.070.

. "Person" means any individual, firm, public or private corporation, association, partnership, political subdivision, municipality, or government agency.

. "Residential construction" means construction, alteration, repair, improvement, or maintenance of single-family dwellings, duplexes, apartments, condominiums, and other residential structures not to exceed four stories in height, including the basement.

. "Retailer" means any person that sells goods or commodities directly to consumers.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6473-S.SL.pdf?cite=2020%20c%20100%20§%202[2020 c 100 § 2]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5458-S.SL.pdf?cite=2013%20c%2051%20§%202[2013 c 51 § 2]; ]

== 70A.450.030 - Labeling requirement for asbestos-containing building materials.
. Effective January 1, 2014, it is unlawful to manufacture, wholesale, or distribute for sale an asbestos-containing building material that is not labeled as required by RCW 70A.450.040 or as required under federal law, 40 C.F.R. part 763, subpart I, Sec. 173.171 (1994). The labeling requirement also applies to stock-on-hand, meaning any asbestos-containing building material in their possession or control after December 31, 2013, must be labeled. Retailers that do not manufacture, wholesale, or distribute asbestos-containing building materials are exempt from this chapter.

. [Empty]
.. Subsection (1) of this section does not apply to asbestos-containing building materials that have already been installed, applied, or used by the consumer.

.. Subsection (1) of this section does not apply to asbestos-containing building materials used solely for United States military purposes.

. Any manufacturer, wholesaler, or distributor may submit a written request for an exemption from the labeling requirements of this chapter, and the department may grant such an exemption if it determines that the labeling requirements are technically infeasible or create an undue economic hardship. Each exemption is in effect for a period not to exceed three years from the date issued and is subject to the terms and conditions prescribed by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201426[2020 c 20 § 1426]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5458-S.SL.pdf?cite=2013%20c%2051%20§%203[2013 c 51 § 3]; ]

== 70A.450.040 - Placement of label—Content of label's notice—Tampering with label unlawful.
. A label must be placed in a prominent location adjacent to the product name or description on the exterior of the wrapping and packaging in which the asbestos-containing building material is placed for storage, shipment, and sale.

. A label must also be placed on the exterior surface of the asbestos-containing building material itself unless it is sold as a liquid or paste, is sand or gravel, or an exemption is granted pursuant to RCW 70A.450.030(3).

. Asbestos-containing building materials must have a legible label that clearly identifies it as containing asbestos. The department may adopt rules regarding the implementation of this chapter. At a minimum, the label must state the following:

CAUTION!

This product contains ASBESTOS which is known to cause cancer and lung disease. Avoid creating dust. Intentionally removing or tampering with this label is a violation of state law.

. It is unlawful for any person to remove, deface, cover, or otherwise obscure or tamper with a label or sticker that has been applied in compliance with this section, unless the asbestos-containing building material is in the possession of the end user.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201427[2020 c 20 § 1427]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5458-S.SL.pdf?cite=2013%20c%2051%20§%204[2013 c 51 § 4]; ]

== 70A.450.050 - Enforcement of chapter—Penalties.
. The provisions of this chapter may be enforced by the department, local air authorities, or their designees.

. A person found in violation of this chapter is subject to the penalties provided under RCW 70A.15.3160.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201428[2020 c 20 § 1428]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5458-S.SL.pdf?cite=2013%20c%2051%20§%205[2013 c 51 § 5]; ]

== 70A.450.060 - Use of asbestos-containing building materials in new construction—Prohibition—Exceptions.
. Except as provided in subsection (2) of this section, the use of asbestos-containing building materials in new construction or renovations is prohibited.

. Subsection (1) of this section does not apply to:

.. The use of asbestos-containing building materials in residential construction;

.. The use of asbestos-containing building materials that are, as of June 11, 2020, already ordered by a contractor or currently in the possession of the contractor; or

.. The use of asbestos-containing building materials if complying with subsection (1) of this section would result in the breach of a contract existing as of June 11, 2020.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6473-S.SL.pdf?cite=2020%20c%20100%20§%201[2020 c 100 § 1]; ]

== 70A.450.070 - Inspection of certain facilities for asbestos-containing building materials—Asbestos management plan—Content—Penalties.
. Every owner of a facility that is engaged in activities described in codes 31 through 33 of the North American industry classification system must:

.. Perform an inspection of the facility to determine whether asbestos-containing building materials are present and, if asbestos-containing building materials are found during the initial inspection, reinspect asbestos-containing building materials every five years thereafter. The inspections must be conducted by persons meeting the accreditation requirements of the federal toxic substances control act, 15 U.S.C. Sec. 2646 (b) or (c); and

.. Develop, maintain, and update an asbestos management plan and keep a copy at the facility. The asbestos management plan must be updated every five years and after any material changes in asbestos-containing building materials in the facility. The asbestos management plan must include:

... The name and address of the facility and whether the facility has asbestos-containing building materials, and the type of asbestos-containing building material;

... The date of the original facility inspection;

... A plan for reinspections;

... A blueprint of the facility that clearly identifies the location of asbestos-containing building materials;

.. A description of any response action or prevention measures taken to reduce asbestos exposure;

.. A copy of the analysis of any building or facility, and the name and address of any laboratory that sampled the material;

.. The name, address, and telephone number of a designated contact to whom the owner has assigned responsibility for ensuring that the duties of the owner are carried out; and

.. A description of steps taken to inform workers about inspections, reinspections, response actions, and periodic surveillance of the asbestos-containing building materials.

. Upon request, the asbestos management plan required under subsection (1)(b) of this section must be made available to the department, the department of labor and industries, local air pollution control authorities in jurisdictions where they have been created under this chapter, and any interested party. In addition to the penalties established by this chapter, failure to create or maintain a required asbestos management plan is a violation of chapter 49.17 RCW and subject to the penalties established under RCW 49.17.180 and 49.17.190.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6473-S.SL.pdf?cite=2020%20c%20100%20§%203[2020 c 100 § 3]; ]

