= 70A.345 - Underground storage tank revolving loan and grant program.
:toc:

== 70A.345.010 - Intent. (Expires July 1, 2030.)
. The legislature intends for the pollution liability insurance agency to establish a revolving loan and grant program to assist owners and operators of petroleum underground storage tank systems to: (a) Remediate past releases; (b) upgrade, replace, or remove petroleum underground storage tank systems to prevent future releases; and (c) install new infrastructure or retrofit existing infrastructure for dispensing or using renewable or alternative energy.

. Furthermore, the legislature intends for the revolving loan and grant program to assist owners and operators of heating oil tanks to: (a) Remediate past releases; or (b) prevent future releases by upgrading, replacing, decommissioning, or removing heating oil systems.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6256-S.SL.pdf?cite=2020%20c%20310%20§%204[2020 c 310 § 4]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2357-S.SL.pdf?cite=2016%20c%20161%20§%201[2016 c 161 § 1]; ]

== 70A.345.020 - Definitions. (Expires July 1, 2030.)
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Agency" means the Washington state pollution liability insurance agency.

. "Heating oil tank" means a tank and its connecting pipes, whether above or below ground, or in a basement, with pipes connected to the tank for space heating of human living or working space on the premises where the tank is located.

. "Local government" means any political subdivision of the state, including a town, city, county, special purpose district, or other municipal corporation.

. "Operator" means any person in control of, or having responsibility for, the daily operation of a petroleum underground storage tank system, including a heating oil tank system.

. "Owner" means any person who owns a petroleum underground storage tank system, including a heating oil tank system.

. "Petroleum underground storage tank system" means an underground storage tank system regulated under chapter 70A.355 RCW or subtitle I of the solid waste disposal act (42 U.S.C. chapter 82, subchapter IX) that is used for storing petroleum.

. "Release" has the same meaning as defined in RCW 70A.305.020.

. "Remedial action" has the same meaning as defined in RCW 70A.305.020.

. "Underground storage tank facility" means the location where one or more underground storage tank systems are installed. A facility encompasses all contiguous real property under common ownership associated with the operation of the underground storage tank system or systems.

. "Underground storage tank system" means an underground storage tank, connected underground piping, underground ancillary equipment, and containment system, if any, and includes any aboveground ancillary equipment connected to the underground storage tank or piping, such as dispensers.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6256-S.SL.pdf?cite=2020%20c%20310%20§%205[2020 c 310 § 5]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201435[2020 c 20 § 1435]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2357-S.SL.pdf?cite=2016%20c%20161%20§%202[2016 c 161 § 2]; ]

== 70A.345.030 - Program established—Purpose—Maximum amount of loans and grants. (Expires July 1, 2030.)
. The agency shall establish an underground storage tank revolving loan and grant program to provide loans or grants to owners or operators to:

.. Conduct remedial actions in accordance with chapter 70A.305 RCW, including investigations and cleanups of any release or threatened release of a hazardous substance at or affecting an underground storage tank facility, provided that at least one of the releases or threatened releases involves petroleum;

.. Upgrade, replace, or permanently close a petroleum underground storage tank system in accordance with chapter 70A.355 RCW or subtitle I of the solid waste disposal act (42 U.S.C., chapter 82, subchapter IX), as applicable;

.. Install new infrastructure or retrofit existing infrastructure at an underground storage tank facility for dispensing or using renewable or alternative energy for motor vehicles, including electric vehicle charging stations, when conducted in conjunction with either (a) or (b) of this subsection;

.. Install and subsequently remove a temporary petroleum aboveground storage tank system in compliance with applicable laws, when conducted in conjunction with either (a) or (b) of this subsection;

.. Conduct remedial actions in accordance with *chapter 70.105D RCW, including investigation and cleanup of any release or threatened releases of petroleum from a heating oil tank; or

.. Prevent future releases by upgrading, replacing, decommissioning, or removing a heating oil tank.

. The maximum amount that may be loaned or granted under this program to an owner or operator for a single underground storage tank facility is two million dollars and for a single heating oil tank seventy-five thousand dollars.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6256-S.SL.pdf?cite=2020%20c%20310%20§%206[2020 c 310 § 6]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201436[2020 c 20 § 1436]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2357-S.SL.pdf?cite=2016%20c%20161%20§%203[2016 c 161 § 3]; ]

== 70A.345.040 - Use of funds—Restrictions. (Expires July 1, 2030.)
. A recipient of a loan or grant may not use these funds to conduct remedial actions of a release or threatened release from a petroleum underground storage tank system requiring financial assurances under chapter 70A.355 RCW or subtitle I of the solid waste disposal act (42 U.S.C., chapter 82, subchapter IX) unless the owner or operator:

.. Agrees to first expend all moneys available under the required financial assurances;

.. Demonstrates that all moneys available under the required financial assurances have been expended; or

.. Demonstrates that a claim has been made under the required financial assurances and the claim has been rejected by the provider.

. A recipient must use a loan or grant for a project that develops and acquires assets that have a useful life of at least thirteen years.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201437[2020 c 20 § 1437]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2357-S.SL.pdf?cite=2016%20c%20161%20§%204[2016 c 161 § 4]; ]

== 70A.345.050 - Program administration—Loan origination fees. (Expires July 1, 2030.)
The agency shall partner and enter into a memorandum of agreement with the department of health to implement the revolving loan and grant program.

. The agency shall approve recipients for loans and grants, structure funding offers to protect applicants with limited economic resources, and manage the work conducted under RCW 70A.345.030(1).

. The department of health shall administer the loans and grants to qualified recipients as determined by the agency.

. The department of health may collect, from persons requesting financial assistance, loan origination fees to cover costs incurred by the department of health in operating the financial assistance program.

. The agency may use the moneys in the pollution liability insurance agency underground storage tank revolving account to fund the department of health's operating costs for the program.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6256-S.SL.pdf?cite=2020%20c%20310%20§%207[2020 c 310 § 7]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201438[2020 c 20 § 1438]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2357-S.SL.pdf?cite=2016%20c%20161%20§%205[2016 c 161 § 5]; ]

== 70A.345.060 - Remedial actions—Release or threatened release of hazardous substance. (Expires July 1, 2030.)
. The agency may conduct remedial actions and investigate or clean up a release or threatened release of a hazardous substance at or affecting an underground storage tank facility if the following conditions are met:

.. The owner or operator received a loan or grant for the underground storage tank facility under the revolving program created in this chapter for two million dollars or less;

.. The remedial actions are conducted in accordance with the rules adopted under chapter 70A.305 RCW;

.. The owner of real property subject to the remedial actions provides consent for the agency to:

... Recover the remedial action costs from the owner; and

... Enter upon the real property to conduct remedial actions limited to those authorized by the owner or operator. Remedial actions must be focused on maintaining the economic vitality of the property. The agency or the agency's authorized representatives shall give reasonable notice before entering property unless an emergency prevents the notice; and

.. The owner of the underground storage tank facility consents to the agency filing a lien on the underground storage tank facility to recover the agency's remedial action costs.

. The agency may conduct the remedial actions authorized under subsection (1) of this section using the moneys in the pollution liability insurance agency underground storage tank revolving account, as required under RCW 70A.345.050. However, for any remedial action where the owner or operator has received a loan or grant, the agency may not expend more than the difference between the amount loaned or granted and two million dollars.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6256-S.SL.pdf?cite=2020%20c%20310%20§%208[2020 c 310 § 8]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201439[2020 c 20 § 1439]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2357-S.SL.pdf?cite=2016%20c%20161%20§%206[2016 c 161 § 6]; ]

== 70A.345.070 - Lien for cost of remedial action—Procedure—Notice. (Expires July 1, 2030.)
. The agency may file a lien against the underground storage tank facility if the agency incurs remedial action costs and those costs are unrecovered by the agency.

.. A lien filed under this section may not exceed the remedial action costs incurred by the agency.

.. A lien filed under this section has priority in rank over all other privileges, liens, monetary encumbrances, or other security interests affecting the real property, whenever incurred, filed, or recorded, except for local and special district property tax assessments.

. Before filing a lien under this section, the agency shall give notice of its intent to file a lien to the owner of the underground storage tank facility on which the lien is to be filed, mortgagees, and lienholders of record.

.. The agency shall send the notice by certified mail to the underground storage tank facility owner and mortgagees of record at the addresses listed in the recorded documents. If the underground storage tank facility owner is unknown or if a mailed notice is returned as undeliverable, the agency shall provide notice by posting a legal notice in the newspaper of largest circulation in the county in which the site is located. The notice must provide:

... A statement of the purpose of the lien;

... A brief description of the real property to be affected by the lien; and

... A statement of the remedial action costs incurred by the agency.

.. If the agency has reason to believe that exigent circumstances require the filing of a lien prior to giving notice under this subsection, the agency may file the lien immediately. Exigent circumstances include, but are not limited to, an imminent bankruptcy filing by the underground storage tank facility owner or the imminent transfer or sale of the real property subject to lien by the underground storage tank facility owner, or both.

. A lien filed under this section is effective when a statement of lien is filed with the county auditor in the county where the underground storage tank facility is located. The statement of lien must include a description of the real property subject to lien and the amount of the lien.

. Unless the agency determines it is in the public interest to remove the lien, the lien continues until the liabilities for the remedial action costs have been satisfied through sale of the real property, foreclosure, or other means agreed to by the agency. Any action for foreclosure of the lien must be brought by the attorney general in a civil action in the court having jurisdiction and in the manner prescribed for judicial foreclosure of a mortgage under chapter 61.24 RCW.

. The agency may not file a lien under this section against an underground storage tank facility owned by a local government.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2357-S.SL.pdf?cite=2016%20c%20161%20§%207[2016 c 161 § 7]; ]

== 70A.345.080 - Pollution liability insurance agency underground storage tank revolving account. (Expires July 1, 2030.)
. The pollution liability insurance agency underground storage tank revolving account is created in the state treasury. All receipts from sources identified under subsection (2) of this section must be deposited into the account. Moneys in the account may be spent only after appropriation. Expenditures from the account may be used only for items identified under subsection (3) of this section.

. The following receipts must be deposited into the account:

.. All moneys appropriated by the legislature to pay for the agency's operating costs to carry out the purposes of this chapter;

.. All moneys appropriated by the legislature to provide loans and grants under RCW 70A.345.030;

.. Any repayment of loans provided under RCW 70A.345.030;

.. All moneys appropriated by the legislature to conduct remedial actions under RCW 70A.345.060;

.. Any recovery of the costs of remedial actions conducted under RCW 70A.345.060;

.. Any grants provided by the federal government to the agency to achieve the purposes of this chapter; and

.. Any other deposits made from a public or private entity to achieve the purposes of this chapter.

. Moneys in the account may be used by the agency only to carry out the purposes of this chapter including, but not limited to:

.. The costs of the agency and department of health to carry out the purposes of this chapter;

.. Loans and grants under RCW 70A.345.030;

.. Remedial actions under RCW 70A.345.060; and

.. State match requirements for grants provided to the agency by the federal government.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201440[2020 c 20 § 1440]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2357-S.SL.pdf?cite=2016%20c%20161%20§%208[2016 c 161 § 8]; ]

== 70A.345.090 - Report on agency activities. (Expires July 1, 2030.)
By September 1st of each even-numbered year, the agency must provide the office of financial management and the appropriate legislative committees a report on the agency's activities supported by expenditures from the pollution liability insurance agency underground storage tank revolving account. The report must at a minimum include:

. The amount of money the legislature appropriated from the pollution liability insurance agency underground storage tank revolving account under RCW 70A.345.080 during the last biennium;

. For the previous biennium, the total number of loans and grants, the amounts loaned or granted, sites cleaned up, petroleum underground storage tank systems or heating oil tanks upgraded, replaced, or permanently closed, and jobs preserved;

. For each loan and grant awarded during the previous biennium, the name of the recipient, the location of the underground storage tank facility, a description of the project and its status, the amount loaned, and the amount repaid. For loans and grants awarded for heating oil tanks, only the general location, status, amount loaned, and the amount repaid must be provided;

. For each underground storage tank facility where the agency conducted remedial actions under RCW 70A.345.060 during the previous biennium, the name and location of the site, the amount of money used to conduct the remedial actions, the status of remedial actions, whether liens were filed against the underground storage tank facility under RCW 70A.345.070, and the amount of money recovered; and

. The operating costs of the agency and department of health to carry out the purposes of this chapter during the last biennium.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6256-S.SL.pdf?cite=2020%20c%20310%20§%209[2020 c 310 § 9]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201441[2020 c 20 § 1441]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2357-S.SL.pdf?cite=2016%20c%20161%20§%209[2016 c 161 § 9]; ]

== 70A.345.100 - Adoption of rules—Memorandum of agreement—Interpretative guidance. (Expires July 1, 2030.)
The agency must adopt rules under chapter 34.05 RCW necessary to carry out the provisions of this chapter. To accelerate remedial actions, the agency shall enter into a memorandum of agreement with the department of health under RCW 70A.345.050 within one year of July 1, 2016. To ensure the adoption of rules will not delay the award of a loan or grant, the agency may implement the underground storage tank revolving program through interpretative guidance pending adoption of rules.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201442[2020 c 20 § 1442]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2357-S.SL.pdf?cite=2016%20c%20161%20§%2010[2016 c 161 § 10]; ]

== 70A.345.110 - Civil liability of state. (Expires July 1, 2030.)
Officers, employees, and authorized representatives of the agency and the department of health, and the state of Washington are immune from civil liability and no cause of action of any nature may arise from any act or omission in exercising powers and duties under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2357-S.SL.pdf?cite=2016%20c%20161%20§%2011[2016 c 161 § 11]; ]

== 70A.345.120 - Applicability of chapter—Authority of the department of ecology. (Expires July 1, 2030.)
Nothing in this chapter limits the authority of the department of ecology under chapter 70A.305 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201443[2020 c 20 § 1443]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2357-S.SL.pdf?cite=2016%20c%20161%20§%2012[2016 c 161 § 12]; ]

== 70A.345.130 - Pollution liability insurance program trust account—Transfers to revolving account.
. On July 1, 2016, if the cash balance amount in the pollution liability insurance program trust account exceeds seven million five hundred thousand dollars after excluding the reserves under RCW 70A.325.020(2), the state treasurer shall transfer the amount exceeding seven million five hundred thousand dollars, up to a transfer of ten million dollars, from the pollution liability insurance program trust account into the pollution liability insurance agency underground storage tank revolving account. If ten million dollars is not available to be transferred on July 1, 2016, then by the end of fiscal year 2017, if the cash balance amount in the pollution liability insurance program trust account exceeds seven million five hundred thousand dollars after excluding the reserves under RCW 70A.325.020(2), the state treasurer shall transfer the amount exceeding seven million five hundred thousand dollars from the pollution liability insurance program trust account into the pollution liability insurance agency underground storage tank revolving account. The total amount transferred in fiscal year 2017 from the pollution liability insurance program trust account into the pollution liability insurance agency underground storage tank revolving account may not exceed ten million dollars.

. Beginning July 1, 2017, during the fiscal biennium and each successive fiscal biennium, if the cash balance amount in the pollution liability insurance program trust account exceeds seven million five hundred thousand dollars, the state treasurer is authorized, upon request of the agency, to transfer the amount exceeding seven million five hundred thousand dollars after excluding the reserves under RCW 70A.325.020(2), up to a transfer of twenty million dollars, from the pollution liability insurance program trust account into the pollution liability insurance agency underground storage tank revolving account. The agency may request transfers only as needed to maximize the amount transferred in a fiscal biennium from the pollution liability insurance program trust account into the pollution liability insurance agency underground storage tank revolving account. The total amount transferred in a fiscal biennium from the pollution liability insurance program trust account into the pollution liability insurance agency underground storage tank revolving account may not exceed twenty million dollars.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6256-S.SL.pdf?cite=2020%20c%20310%20§%2010[2020 c 310 § 10]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201444[2020 c 20 § 1444]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5965-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%204%20§%206015[2017 3rd sp.s. c 4 § 6015]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2357-S.SL.pdf?cite=2016%20c%20161%20§%2021[2016 c 161 § 21]; ]

== 70A.345.900 - Expiration date—Savings clause—Reversion of revolving account funds.
. RCW 70A.345.010 through 70A.345.120 expire July 1, 2030.

. The expiration of RCW 70A.345.010 through 70A.345.120 does not terminate any of the following rights, obligations, authorities or any provision necessary to carry out:

.. The repayment of loans due and payable to the lender or the state of Washington;

.. The resolution of any cost recovery action or the initiation of any action or other collection process to recover defaulted loan moneys due to the state of Washington; and

.. The resolution of any action or the initiation of any action to recover the agency's remedial actions costs under RCW 70A.345.070.

. On July 1, 2030, the pollution liability insurance agency underground storage tank revolving account and all moneys due that account revert to, and accrue to the benefit of, the department of health.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201445[2020 c 20 § 1445]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2357-S.SL.pdf?cite=2016%20c%20161%20§%2013[2016 c 161 § 13]; ]

