= 70A.205 - Solid waste management—Reduction and recycling.
:toc:

== 70A.205.005 - Legislative finding—Priorities—Goals.
The legislature finds:

. Continuing technological changes in methods of manufacture, packaging, and marketing of consumer products, together with the economic and population growth of this state, the rising affluence of its citizens, and its expanding industrial activity have created new and ever-mounting problems involving disposal of garbage, refuse, and solid waste materials resulting from domestic, agricultural, and industrial activities.

. Traditional methods of disposing of solid wastes in this state are no longer adequate to meet the ever-increasing problem. Improper methods and practices of handling and disposal of solid wastes pollute our land, air and water resources, blight our countryside, adversely affect land values, and damage the overall quality of our environment.

. Considerations of natural resource limitations, energy shortages, economics and the environment make necessary the development and implementation of solid waste recovery and/or recycling plans and programs.

. Waste reduction must become a fundamental strategy of solid waste management. It is therefore necessary to change manufacturing and purchasing practices and waste generation behaviors to reduce the amount of waste that becomes a governmental responsibility.

. Source separation of waste must become a fundamental strategy of solid waste management. Collection and handling strategies should have, as an ultimate goal, the source separation of all materials with resource value or environmental hazard.

. [Empty]
.. It should be the goal of every person and business to minimize their production of wastes and to separate recyclable or hazardous materials from mixed waste.

.. It is the responsibility of state, county, and city governments to provide for a waste management infrastructure to fully implement waste reduction and source separation strategies and to process and dispose of remaining wastes in a manner that is environmentally safe and economically sound. It is further the responsibility of state, county, and city governments to monitor the cost-effectiveness and environmental safety of combusting separated waste, processing mixed municipal solid waste, and recycling programs.

.. It is the responsibility of county and city governments to assume primary responsibility for solid waste management and to develop and implement aggressive and effective waste reduction and source separation strategies.

.. It is the responsibility of state government to ensure that local governments are providing adequate source reduction and separation opportunities and incentives to all, including persons in both rural and urban areas, and nonresidential waste generators such as commercial, industrial, and institutional entities, recognizing the need to provide flexibility to accommodate differing population densities, distances to and availability of recycling markets, and collection and disposal costs in each community; and to provide county and city governments with adequate technical resources to accomplish this responsibility.

. Environmental and economic considerations in solving the state's solid waste management problems requires strong consideration by local governments of regional solutions and intergovernmental cooperation.

. The following priorities for the collection, handling, and management of solid waste are necessary and should be followed in descending order as applicable:

.. Waste reduction;

.. Recycling, with source separation of recyclable materials as the preferred method;

.. Energy recovery, incineration, or landfill of separated waste;

.. Energy recovery, incineration, or landfill of mixed municipal solid wastes.

. It is the state's goal to achieve a fifty percent recycling rate by 2007.

. It is the state's goal that programs be established to eliminate residential or commercial yard debris in landfills by 2012 in those areas where alternatives to disposal are readily available and effective.

. Steps should be taken to make recycling at least as affordable and convenient to the ratepayer as mixed waste disposal.

. It is necessary to compile and maintain adequate data on the types and quantities of solid waste that are being generated and to monitor how the various types of solid waste are being managed.

. Vehicle batteries should be recycled and the disposal of vehicle batteries into landfills or incinerators should be discontinued.

. Excessive and nonrecyclable packaging of products should be avoided.

. Comprehensive education should be conducted throughout the state so that people are informed of the need to reduce, source separate, and recycle solid waste.

. All governmental entities in the state should set an example by implementing aggressive waste reduction and recycling programs at their workplaces and by purchasing products that are made from recycled materials and are recyclable.

. To ensure the safe and efficient operations of solid waste disposal facilities, it is necessary for operators and regulators of landfills and incinerators to receive training and certification.

. It is necessary to provide adequate funding to all levels of government so that successful waste reduction and recycling programs can be implemented.

. The development of stable and expanding markets for recyclable materials is critical to the long-term success of the state's recycling goals. Market development must be encouraged on a state, regional, and national basis to maximize its effectiveness. The state shall assume primary responsibility for the development of a multifaceted market development program to carry out the purposes of chapter 431, Laws of 1989.

. There is an imperative need to anticipate, plan for, and accomplish effective storage, control, recovery, and recycling of discarded tires and other problem wastes with the subsequent conservation of resources and energy.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2308-S.SL.pdf?cite=2002%20c%20299%20§%203[2002 c 299 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%201[1989 c 431 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c345.pdf?cite=1985%20c%20345%20§%201[1985 c 345 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c123.pdf?cite=1984%20c%20123%20§%201[1984 c 123 § 1]; 1975-'76 2nd ex.s. c 41 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c134.pdf?cite=1969%20ex.s.%20c%20134%20§%201[1969 ex.s. c 134 § 1]; ]

== 70A.205.010 - Purpose.
The purpose of this chapter is to establish a comprehensive statewide program for solid waste handling, and solid waste recovery and/or recycling which will prevent land, air, and water pollution and conserve the natural, economic, and energy resources of this state. To this end it is the purpose of this chapter:

. To assign primary responsibility for adequate solid waste handling to local government, reserving to the state, however, those functions necessary to assure effective programs throughout the state;

. To provide for adequate planning for solid waste handling by local government;

. To provide for the adoption and enforcement of basic minimum performance standards for solid waste handling, including that all sites where recyclable materials are generated and transported from shall provide a separate container for solid waste;

. To encourage the development and operation of waste recycling facilities needed to accomplish the management priority of waste recycling, to promote consistency in the requirements for such facilities throughout the state, and to ensure that recyclable materials diverted from the waste stream for recycling are routed to facilities in which recycling occurs;

. To provide technical and financial assistance to local governments in the planning, development, and conduct of solid waste handling programs;

. To encourage storage, proper disposal, and recycling of discarded vehicle tires and to stimulate private recycling programs throughout the state; and

. To encourage the development and operation of waste recycling facilities and activities needed to accomplish the management priority of waste recycling and to promote consistency in the permitting requirements for such facilities and activities throughout the state.

It is the intent of the legislature that local governments be encouraged to use the expertise of private industry and to contract with private industry to the fullest extent possible to carry out solid waste recovery and/or recycling programs.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5788-S.SL.pdf?cite=2005%20c%20394%20§%202[2005 c 394 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6203-S.SL.pdf?cite=1998%20c%20156%20§%201[1998 c 156 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2960-S.SL.pdf?cite=1998%20c%2090%20§%201[1998 c 90 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c345.pdf?cite=1985%20c%20345%20§%202[1985 c 345 § 2]; 1975-'76 2nd ex.s. c 41 § 2; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c134.pdf?cite=1969%20ex.s.%20c%20134%20§%202[1969 ex.s. c 134 § 2]; ]

== 70A.205.015 - Definitions.
As used in this chapter, unless the context indicates otherwise:

. "City" means every incorporated city and town.

. "Commission" means the utilities and transportation commission.

. "Composted material" means organic solid waste that has been subjected to controlled aerobic degradation at a solid waste facility in compliance with the requirements of this chapter. Natural decay of organic solid waste under uncontrolled conditions does not result in composted material.

. "Department" means the department of ecology.

. "Director" means the director of the department of ecology.

. "Disposal site" means the location where any final treatment, utilization, processing, or deposit of solid waste occurs.

. "Energy recovery" means a process operating under federal and state environmental laws and regulations for converting solid waste into usable energy and for reducing the volume of solid waste.

. "Functional standards" means criteria for solid waste handling expressed in terms of expected performance or solid waste handling functions.

. "Incineration" means a process of reducing the volume of solid waste operating under federal and state environmental laws and regulations by use of an enclosed device using controlled flame combustion.

. "Inert waste landfill" means a landfill that receives only inert waste, as determined under RCW 70A.205.030, and includes facilities that use inert wastes as a component of fill.

. "Jurisdictional health department" means city, county, city-county, or district public health department.

. "Landfill" means a disposal facility or part of a facility at which solid waste is placed in or on land and which is not a land treatment facility.

. "Local government" means a city, town, or county.

. "Modify" means to substantially change the design or operational plans including, but not limited to, removal of a design element previously set forth in a permit application or the addition of a disposal or processing activity that is not approved in the permit.

. "Multiple-family residence" means any structure housing two or more dwelling units.

. "Person" means individual, firm, association, copartnership, political subdivision, government agency, municipality, industry, public or private corporation, or any other entity whatsoever.

. "Recyclable materials" means those solid wastes that are separated for recycling or reuse, such as papers, metals, and glass, that are identified as recyclable material pursuant to a local comprehensive solid waste plan. Prior to the adoption of the local comprehensive solid waste plan, adopted pursuant to RCW 70A.205.075(2), local governments may identify recyclable materials by ordinance from July 23, 1989.

. "Recycling" means transforming or remanufacturing waste materials into usable or marketable materials for use other than landfill disposal or incineration.

. "Residence" means the regular dwelling place of an individual or individuals.

. "Sewage sludge" means a semisolid substance consisting of settled sewage solids combined with varying amounts of water and dissolved materials, generated from a wastewater treatment system, that does not meet the requirements of chapter 70A.226 RCW.

. "Soil amendment" means any substance that is intended to improve the physical characteristics of the soil, except composted material, commercial fertilizers, agricultural liming agents, unmanipulated animal manures, unmanipulated vegetable manures, food wastes, food processing wastes, and materials exempted by rule of the department, such as biosolids as defined in chapter 70A.226 RCW and wastewater as regulated in chapter 90.48 RCW.

. "Solid waste" or "wastes" means all putrescible and nonputrescible solid and semisolid wastes including, but not limited to, garbage, rubbish, ashes, industrial wastes, swill, sewage sludge, demolition and construction wastes, abandoned vehicles or parts thereof, and recyclable materials.

. "Solid waste handling" means the management, storage, collection, transportation, treatment, utilization, processing, and final disposal of solid wastes, including the recovery and recycling of materials from solid wastes, the recovery of energy resources from solid wastes or the conversion of the energy in solid wastes to more useful forms or combinations thereof.

. "Source separation" means the separation of different kinds of solid waste at the place where the waste originates.

. "Vehicle" includes every device physically capable of being moved upon a public or private highway, road, street, or watercourse and in, upon, or by which any person or property is or may be transported or drawn upon a public or private highway, road, street, or watercourse, except devices moved by human or animal power or used exclusively upon stationary rails or tracks.

. "Waste-derived soil amendment" means any soil amendment as defined in this chapter that is derived from solid waste as defined in this section, but does not include biosolids or biosolids products regulated under chapter 70A.226 RCW or wastewaters regulated under chapter 90.48 RCW.

. "Waste reduction" means reducing the amount or toxicity of waste generated or reusing materials.

. "Yard debris" means plant material commonly created in the course of maintaining yards and gardens, and through horticulture, gardening, landscaping, or similar activities. Yard debris includes but is not limited to grass clippings, leaves, branches, brush, weeds, flowers, roots, windfall fruit, vegetable garden debris, holiday trees, and tree prunings four inches or less in diameter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201161[2020 c 20 § 1161]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2617-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%207%20§%2086[2010 1st sp.s. c 7 § 86]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2308-S.SL.pdf?cite=2004%20c%20101%20§%201[2004 c 101 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2308-S.SL.pdf?cite=2002%20c%20299%20§%204[2002 c 299 § 4]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6474-S.SL.pdf?cite=1998%20c%2036%20§%2017[1998 c 36 § 17]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1419-S.SL.pdf?cite=1997%20c%20213%20§%201[1997 c 213 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2640-S.SL.pdf?cite=1992%20c%20174%20§%2016[1992 c 174 § 16]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5478-S.SL.pdf?cite=1991%20c%20298%20§%202[1991 c 298 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%202[1989 c 431 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c345.pdf?cite=1985%20c%20345%20§%203[1985 c 345 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c123.pdf?cite=1984%20c%20123%20§%202[1984 c 123 § 2]; 1975-'76 2nd ex.s. c 41 § 3; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c62.pdf?cite=1970%20ex.s.%20c%2062%20§%2060[1970 ex.s. c 62 § 60]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c134.pdf?cite=1969%20ex.s.%20c%20134%20§%203[1969 ex.s. c 134 § 3]; ]

== 70A.205.020 - Environmental excellence program agreements—Effect on chapter.
Notwithstanding any other provision of law, any legal requirement under this chapter, including any standard, limitation, rule, or order is superseded and replaced in accordance with the terms and provisions of an environmental excellence program agreement, entered into under chapter 43.21K RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1866-S2.SL.pdf?cite=1997%20c%20381%20§%2022[1997 c 381 § 22]; ]

== 70A.205.025 - Standards for solid waste handling—Areas—Landfill location.
. The department shall adopt rules establishing minimum functional standards for solid waste handling, consistent with the standards specified in this section. The department may classify areas of the state with respect to population density, climate, geology, status under a quarantine as defined in RCW 17.24.007, and other relevant factors bearing on solid waste disposal standards.

. In addition to the minimum functional standards adopted by the department under subsection (1) of this section, each landfill facility whose area at its design capacity will exceed one hundred acres and whose horizontal height at design capacity will average one hundred feet or more above existing site elevations shall comply with the standards of this subsection. This subsection applies only to wholly new solid waste landfill facilities, no part or unit of which has had construction commence before April 27, 1999.

.. No landfill specified in this subsection may be located:

... So that the active area is closer than five miles to any national park or a public or private nonprofit zoological park displaying native animals in their native habitats; or

... Over a sole source aquifer designated under the federal safe drinking water act, if such designation was effective before January 1, 1999.

.. Each landfill specified in this subsection (2) shall be constructed with an impermeable berm around the entire perimeter of the active area of the landfill of such height, thickness, and design as will be sufficient to contain all material disposed in the event of a complete failure of the structural integrity of the landfill.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6605-S.SL.pdf?cite=2016%20c%20119%20§%201[2016 c 119 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5729-S.SL.pdf?cite=1999%20c%20116%20§%201[1999 c 116 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c134.pdf?cite=1969%20ex.s.%20c%20134%20§%206[1969 ex.s. c 134 § 6]; ]

== 70A.205.030 - Inert waste landfills.
. The department shall, as part of the minimum functional standards for solid waste handling required under RCW 70A.205.025, develop specific criteria for the types of solid wastes that are allowed to be received by inert waste landfills that seek to continue operation after February 10, 2003.

. The criteria for inert waste developed under this section must, at a minimum, contain a list of substances that an inert waste landfill located in a county with fewer than forty-five thousand residents is permitted to receive if it was operational before February 10, 2003, and is located at a site with a five-year annual rainfall of twenty-five inches or less. The substances permitted for the inert waste landfills satisfying the criteria listed in this subsection must include the following types of solid waste if the waste has not been tainted, through exposure from chemical, physical, biological, or radiological substances, such that it presents a threat to human health or the environment greater than that inherent to the material:

.. Cured concrete, including any embedded steel reinforcing and wood;

.. Asphaltic materials, including road construction asphalt;

.. Brick and masonry;

.. Ceramic materials produced from fired clay or porcelain;

.. Glass;

.. Stainless steel and aluminum; and

.. Other materials as defined in chapter 173-350 WAC.

. The department shall work with the owner or operators of landfills that do not meet the minimum functional standards for inert waste landfills to explore and implement appropriate means of transition into a limited purpose landfill that is able to accept additional materials as specified in WAC 173-350-400.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201162[2020 c 20 § 1162]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2308-S.SL.pdf?cite=2004%20c%20101%20§%202[2004 c 101 § 2]; ]

== 70A.205.035 - Implementation of standards—Assessment—Analyses—Proposals.
In order to implement the minimum functional standards for solid waste handling, evaluate the effectiveness of the minimum functional standards, evaluate the cost of implementation, and develop a mechanism to finance the implementation, the department shall prepare:

. An assessment of local health agencies' information on all existing permitted landfill sites, including (a) measures taken and facilities installed at each landfill to mitigate surface water and groundwater contamination, (b) proposed measures taken and facilities to be constructed at each landfill to mitigate surface water and groundwater contamination, and (c) the costs of such measures and facilities;

. An analysis of the effectiveness of the minimum functional standards for new landfills in lessening surface water and groundwater contamination, and a comparison with the effectiveness of the prior standards;

. An analysis of the costs of conforming with the new functional standards for new landfills compared with the costs of conforming to the prior standards; and

. Proposals for methods of financing the costs of conforming with the new functional standards.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c81.pdf?cite=1986%20c%2081%20§%201[1986 c 81 § 1]; ]

== 70A.205.040 - County comprehensive solid waste management plan—Joint plans—Requirements when updating—Duties of cities.
. Each county within the state, in cooperation with the various cities located within such county, shall prepare a coordinated, comprehensive solid waste management plan. Such plan may cover two or more counties. The purpose is to plan for solid waste and materials reduction, collection, and handling and management services and programs throughout the state, as designed to meet the unique needs of each county and city in the state. When updating a solid waste management plan developed under this chapter, after June 10, 2010, local comprehensive plans must consider and plan for the following handling methods or services:

.. Source separation of recyclable materials and products, organic materials, and wastes by generators;

.. Collection of source separated materials;

.. Handling and proper preparation of materials for reuse or recycling;

.. Handling and proper preparation of organic materials for composting or anaerobic digestion; and

.. Handling and proper disposal of nonrecyclable wastes.

. When updating a solid waste management plan developed under this chapter, after June 10, 2010, each local comprehensive plan must, at a minimum, consider methods that will be used to address the following:

.. Construction and demolition waste for recycling or reuse;

.. Organic material including yard debris, food waste, and food contaminated paper products for composting or anaerobic digestion;

.. Recoverable paper products for recycling;

.. Metals, glass, and plastics for recycling; and

.. Waste reduction strategies.

. Each city shall:

.. Prepare and deliver to the county auditor of the county in which it is located its plan for its own solid waste management for integration into the comprehensive county plan;

.. Enter into an agreement with the county pursuant to which the city shall participate in preparing a joint city-county plan for solid waste management; or

.. Authorize the county to prepare a plan for the city's solid waste management for inclusion in the comprehensive county plan.

. Two or more cities may prepare a plan for inclusion in the county plan. With prior notification of its home county of its intent, a city in one county may enter into an agreement with a city in an adjoining county, or with an adjoining county, or both, to prepare a joint plan for solid waste management to become part of the comprehensive plan of both counties.

. After consultation with representatives of the cities and counties, the department shall establish a schedule for the development of the comprehensive plans for solid waste management. In preparing such a schedule, the department shall take into account the probable cost of such plans to the cities and counties.

. Local governments shall not be required to include a hazardous waste element in their solid waste management plans.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2539-S2.SL.pdf?cite=2010%20c%20154%20§%202[2010 c 154 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c448.pdf?cite=1985%20c%20448%20§%2017[1985 c 448 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c134.pdf?cite=1969%20ex.s.%20c%20134%20§%208[1969 ex.s. c 134 § 8]; ]

== 70A.205.045 - County and city comprehensive solid waste management plans—Contents.
Each county and city comprehensive solid waste management plan shall include the following:

. A detailed inventory and description of all existing solid waste handling facilities including an inventory of any deficiencies in meeting current solid waste handling needs.

. The estimated long-range needs for solid waste handling facilities projected twenty years into the future.

. A program for the orderly development of solid waste handling facilities in a manner consistent with the plans for the entire county which shall:

.. Meet the minimum functional standards for solid waste handling adopted by the department and all laws and regulations relating to air and water pollution, fire prevention, flood control, and protection of public health;

.. Take into account the comprehensive land use plan of each jurisdiction;

.. Contain a six year construction and capital acquisition program for solid waste handling facilities; and

.. Contain a plan for financing both capital costs and operational expenditures of the proposed solid waste management system.

. A program for surveillance and control.

. A current inventory and description of solid waste collection needs and operations within each respective jurisdiction which shall include:

.. Any franchise for solid waste collection granted by the utilities and transportation commission in the respective jurisdictions including the name of the holder of the franchise and the address of his or her place of business and the area covered by the franchise;

.. Any city solid waste operation within the county and the boundaries of such operation;

.. The population density of each area serviced by a city operation or by a franchised operation within the respective jurisdictions;

.. The projected solid waste collection needs for the respective jurisdictions for the next six years.

. A comprehensive waste reduction and recycling element that, in accordance with the priorities established in RCW 70A.205.005, provides programs that (a) reduce the amount of waste generated, (b) provide incentives and mechanisms for source separation, and (c) establish recycling opportunities for the source separated waste.

. The waste reduction and recycling element shall include the following:

.. Waste reduction strategies, which may include strategies to reduce wasted food and food waste that are designed to achieve the goals established in RCW 70A.205.715(1) and that are consistent with the plan developed in RCW 70A.205.715(3);

.. Source separation strategies, including:

... Programs for the collection of source separated materials from residences in urban and rural areas. In urban areas, these programs shall include collection of source separated recyclable materials from single and multiple-family residences, unless the department approves an alternative program, according to the criteria in the planning guidelines. Such criteria shall include: Anticipated recovery rates and levels of public participation, availability of environmentally sound disposal capacity, access to markets for recyclable materials, unreasonable cost impacts on the ratepayer over the six-year planning period, utilization of environmentally sound waste reduction and recycling technologies, and other factors as appropriate. In rural areas, these programs shall include but not be limited to drop-off boxes, buy-back centers, or a combination of both, at each solid waste transfer, processing, or disposal site, or at locations convenient to the residents of the county. The drop-off boxes and buy-back centers may be owned or operated by public, nonprofit, or private persons;

... Programs to monitor the collection of source separated waste at nonresidential sites where there is sufficient density to sustain a program;

... Programs to collect yard waste and food waste, if the county or city submitting the plan finds that there are adequate markets or capacity for composted yard waste and food waste within or near the service area to consume the majority of the material collected; and

... Programs to educate and promote the concepts of waste reduction and recycling;

.. Recycling strategies, including a description of markets for recyclables, a review of waste generation trends, a description of waste composition, a discussion and description of existing programs and any additional programs needed to assist public and private sector recycling, and an implementation schedule for the designation of specific materials to be collected for recycling, and for the provision of recycling collection services;

.. Other information the county or city submitting the plan determines is necessary.

. An assessment of the plan's impact on the costs of solid waste collection. The assessment shall be prepared in conformance with guidelines established by the utilities and transportation commission. The commission shall cooperate with the Washington state association of counties and the association of Washington cities in establishing such guidelines.

. A review of potential areas that meet the criteria as outlined in RCW 70A.205.110.

. A contamination reduction and outreach plan. The contamination reduction and outreach plan must address reducing contamination in recycling. Except for counties with a population of twenty-five thousand or fewer, by July 1, 2021, a contamination reduction and outreach plan must be included in each solid waste management plan by a plan amendment or included when revising or updating a solid waste management plan developed under this chapter. Jurisdictions may adopt the state's contamination reduction and outreach plan as developed under RCW 70A.205.070 in lieu of creating their own plan. A recycling contamination reduction and outreach plan must include the following:

.. A list of actions for reducing contamination in recycling programs for single-family and multiple-family residences, commercial locations, and drop boxes depending on the jurisdictions system components;

.. A list of key contaminants identified by the jurisdiction or identified by the department;

.. A discussion of problem contaminants and the contaminants' impact on the collection system;

.. An analysis of the costs and other impacts associated with contaminants to the recycling system; and

.. An implementation schedule and details of how outreach is to be conducted. Contamination reduction education methods may include sharing community-wide messaging through newsletters, articles, mailers, social media, websites, or community events, informing recycling drop box customers about contamination, and improving signage.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201163[2020 c 20 § 1163]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1114-S2.SL.pdf?cite=2019%20c%20255%20§%204[2019 c 255 § 4]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1543-S2.SL.pdf?cite=2019%20c%20166%20§%206[2019 c 166 § 6]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5478-S.SL.pdf?cite=1991%20c%20298%20§%203[1991 c 298 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%203[1989 c 431 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c123.pdf?cite=1984%20c%20123%20§%205[1984 c 123 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c293.pdf?cite=1971%20ex.s.%20c%20293%20§%201[1971 ex.s. c 293 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c134.pdf?cite=1969%20ex.s.%20c%20134%20§%209[1969 ex.s. c 134 § 9]; ]

== 70A.205.050 - County and city comprehensive solid waste management plans—Levels of service, reduction and recycling.
Levels of service shall be defined in the waste reduction and recycling element of each local comprehensive solid waste management plan and shall include the services set forth in RCW 70A.205.045. In determining which service level is provided to residential and nonresidential waste generators in each community, counties and cities shall develop clear criteria for designating areas as urban or rural. In designating urban areas, local governments shall consider the planning guidelines adopted by the department, total population, population density, and any applicable land use or utility service plans.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201164[2020 c 20 § 1164]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%204[1989 c 431 § 4]; ]

== 70A.205.055 - County and city comprehensive solid waste management plans—Review and approval process.
. The department and local governments preparing plans are encouraged to work cooperatively during plan development. Each county and city preparing a comprehensive solid waste management plan shall submit a preliminary draft plan to the department for technical review. The department shall review and comment on the draft plan within one hundred twenty days of receipt. The department's comments shall state specific actions or revisions that must be completed for plan approval.

. Each final draft solid waste management plan shall be submitted to the department for approval. The department will limit its comments on the final draft plans to those issues identified during its review of the draft plan and any other changes made between submittal of the preliminary draft and final draft plans. Disapproval of the local comprehensive solid waste management plan shall be supported by specific findings. A final draft plan shall be deemed approved if the department does not disapprove it within forty-five days of receipt.

. If the department disapproves a plan or any plan amendments, the submitting entity may appeal the decision to the pollution control hearings board as provided in RCW 43.21B.230. The appeal shall be limited to review of the specific findings which supported the disapproval under subsection (2) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2935-S.SL.pdf?cite=2010%20c%20210%20§%2017[2010 c 210 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%208[1989 c 431 § 8]; ]

== 70A.205.060 - County and city comprehensive solid waste management plans—Review by department of agriculture.
Upon receipt by the department of a preliminary draft plan as provided in RCW 70A.205.055, the department shall immediately provide a copy of the preliminary draft plan to the department of agriculture. Within forty-five days after receiving the preliminary draft plan, the department of agriculture shall review the preliminary draft plan for compliance with chapter 17.24 RCW and the rules adopted under that chapter. The department of agriculture shall advise the local government submitting the preliminary draft plan and the department of the result of the review.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201165[2020 c 20 § 1165]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6605-S.SL.pdf?cite=2016%20c%20119%20§%203[2016 c 119 § 3]; ]

== 70A.205.065 - Utilities and transportation commission to review local plan's assessment of cost impacts on rates.
Upon receipt, the department shall immediately provide the utilities and transportation commission with a copy of each preliminary draft local comprehensive solid waste management plan. Within forty-five days after receiving a plan, the commission shall have reviewed the plan's assessment of solid waste collection cost impacts on rates charged by solid waste collection companies regulated under chapter 81.77 RCW and shall advise the county or city submitting the plan and the department of the probable effect of the plan's recommendations on those rates.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2012[1989 c 431 § 12]; ]

== 70A.205.070 - Technical assistance for plan preparation—Guidelines—Informational materials and programs.
. The department or the commission, as appropriate, shall provide to counties and cities technical assistance including, but not limited to, planning guidelines, in the preparation, review, and revision of solid waste management plans required by this chapter. Guidelines prepared under this section shall be consistent with the provisions of this chapter. Guidelines for the preparation of the waste reduction and recycling element of the comprehensive solid waste management plan shall be completed by the department by March 15, 1990. These guidelines shall provide recommendations to local government on materials to be considered for designation as recyclable materials. The state solid waste management plan prepared pursuant to RCW 70A.205.210 shall be consistent with these guidelines.

. The department shall be responsible for development and implementation of a comprehensive statewide public information program designed to encourage waste reduction, source separation, and recycling by the public. The department shall operate a toll-free hotline to provide the public information on waste reduction and recycling.

. The department shall provide technical assistance to local governments in the development and dissemination of informational materials and related activities to assure recognition of unique local waste reduction and recycling programs.

. [Empty]
.. The department must create and implement a statewide recycling contamination reduction and outreach plan based on best management practices for recycling, developed with stakeholder input by July 1, 2020. Jurisdictions may use the statewide plan in lieu of developing their own plan.

.. The department must provide technical assistance and create guidance to help local jurisdictions determine the extent of contamination in their regional recycling and to develop contamination reduction and outreach plans. Contamination means any material not included on the local jurisdiction's acceptance list.

.. Contamination reduction education methods may include sharing community-wide messaging through newsletters, articles, mailers, social media, websites, or community events, informing recycling drop box customers about contamination, and improving signage.

.. The department must cite the sources of information that it relied upon, including any peer-reviewed science, in the development of the best management practices for recycling under (a) of this subsection and the guidance developed under (b) of this subsection.

. Local governments shall make all materials and information developed with the assistance grants provided under RCW 70A.205.080 available to the department for potential use in other areas of the state.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201166[2020 c 20 § 1166]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1543-S2.SL.pdf?cite=2019%20c%20166%20§%207[2019 c 166 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%206[1989 c 431 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c123.pdf?cite=1984%20c%20123%20§%206[1984 c 123 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c134.pdf?cite=1969%20ex.s.%20c%20134%20§%2010[1969 ex.s. c 134 § 10]; ]

== 70A.205.075 - Maintenance of plans—Review, revisions—Implementation of source separation programs.
. The comprehensive county solid waste management plans and any comprehensive city solid waste management plans prepared in accordance with RCW 70A.205.040 shall be maintained in a current condition and reviewed and revised periodically by counties and cities as may be required by the department. Upon each review such plans shall be extended to show long-range needs for solid waste handling facilities for twenty years in the future, and a revised construction and capital acquisition program for six years in the future. Each revised solid waste management plan shall be submitted to the department.

Each plan shall be reviewed and revised within five years of July 1, 1984, and thereafter shall be reviewed, and revised if necessary according to the schedule provided in subsection (2) of this section.

. Cities and counties preparing solid waste management plans shall submit the waste reduction and recycling element required in RCW 70A.205.045 and any revisions to other elements of its comprehensive solid waste management plan to the department no later than:

.. July 1, 1991, for class one areas: PROVIDED, That portions relating to multiple-family residences shall be submitted no later than July 1, 1992;

.. July 1, 1992, for class two areas; and

.. July 1, 1994, for class three areas.

Thereafter, each plan shall be reviewed and revised, if necessary, at least every five years. Nothing in chapter 431, Laws of 1989 shall prohibit local governments from submitting a plan prior to the dates listed in this subsection.

. The classes of areas are defined as follows:

.. Class one areas are the counties of Spokane, Snohomish, King, Pierce, and Kitsap and all the cities therein.

.. Class two areas are all other counties located west of the crest of the Cascade mountains and all the cities therein.

.. Class three areas are the counties east of the crest of the Cascade mountains and all the cities therein, except for Spokane county.

. Cities and counties shall begin implementing the programs to collect source separated materials no later than one year following the adoption and approval of the waste reduction and recycling element and these programs shall be fully implemented within two years of approval.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201167[2020 c 20 § 1167]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5478-S.SL.pdf?cite=1991%20c%20298%20§%204[1991 c 298 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%205[1989 c 431 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c123.pdf?cite=1984%20c%20123%20§%207[1984 c 123 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c134.pdf?cite=1969%20ex.s.%20c%20134%20§%2011[1969 ex.s. c 134 § 11]; ]

== 70A.205.080 - Financial aid to counties and cities.
Any county may apply to the department on a form prescribed thereby for financial aid for the preparation and implementation of the comprehensive county plan for solid waste management required by RCW 70A.205.040, including contamination reduction and outreach plans. Any city electing to prepare an independent city plan, a joint city plan, or a joint county-city plan for solid waste management for inclusion in the county comprehensive plan may apply for financial aid for such purpose through the county. Every city application for financial aid for planning shall be filed with the county auditor and shall be included as a part of the county's application for financial aid. Any city preparing an independent plan shall provide for disposal sites wholly within its jurisdiction.

The department shall allocate to the counties and cities applying for financial aid for planning and implementation, including contamination reduction and outreach plan development and implementation, such funds as may be available pursuant to legislative appropriations or from any federal grants for such purpose.

The department shall determine priorities and allocate available funds among the counties and cities applying for aid according to criteria established by regulations of the department considering population, urban development, environmental effects of waste disposal, existing waste handling practices, and the local justification of their proposed expenditures.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201168[2020 c 20 § 1168]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1543-S2.SL.pdf?cite=2019%20c%20166%20§%208[2019 c 166 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c134.pdf?cite=1969%20ex.s.%20c%20134%20§%2013[1969 ex.s. c 134 § 13]; ]

== 70A.205.085 - Matching requirements.
Counties and cities shall match their planning aid allocated by the director by an amount not less than twenty-five percent of the estimated cost of such planning. Any federal planning aid made directly to a county or city shall not be considered either a state or local contribution in determining local matching requirements. Counties and cities may meet their share of planning costs by cash and contributed services.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c134.pdf?cite=1969%20ex.s.%20c%20134%20§%2014[1969 ex.s. c 134 § 14]; ]

== 70A.205.090 - Contracts with counties to assure proper expenditures.
Upon the allocation of planning funds as provided in RCW 70A.205.080, the department shall enter into a contract with each county receiving a planning grant. The contract shall include such provisions as the director may deem necessary to assure the proper expenditure of such funds including allocations made to cities. The sum allocated to a county shall be paid to the treasurer of such county.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201169[2020 c 20 § 1169]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c134.pdf?cite=1969%20ex.s.%20c%20134%20§%2015[1969 ex.s. c 134 § 15]; ]

== 70A.205.100 - Local board of health regulations to implement the comprehensive plan—Section not to be construed to authorize counties to operate system.
Each county, or any city, or jurisdictional board of health shall adopt regulations or ordinances governing solid waste handling implementing the comprehensive solid waste management plan covering storage, collection, transportation, treatment, utilization, processing and final disposal including but not limited to the issuance of permits and the establishment of minimum levels and types of service for any aspect of solid waste handling. County regulations or ordinances adopted regarding levels and types of service shall not apply within the limits of any city where the city has by local ordinance determined that the county shall not exercise such powers within the corporate limits of the city. Such regulations or ordinances shall assure that solid waste storage and disposal facilities are located, maintained, and operated in a manner so as properly to protect the public health, prevent air and water pollution, are consistent with the priorities established in RCW 70A.205.005, and avoid the creation of nuisances. Such regulations or ordinances may be more stringent than the minimum functional standards adopted by the department. Regulations or ordinances adopted by counties, cities, or jurisdictional boards of health shall be filed with the department.

Nothing in this section shall be construed to authorize the operation of a solid waste collection system by counties.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201170[2020 c 20 § 1170]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2010[1989 c 431 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c127.pdf?cite=1988%20c%20127%20§%2029[1988 c 127 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c134.pdf?cite=1969%20ex.s.%20c%20134%20§%2016[1969 ex.s. c 134 § 16]; ]

== 70A.205.105 - Local health departments may contract with the department of ecology.
Any jurisdictional health department and the department of ecology may enter into an agreement providing for the exercise by the department of ecology of any power that is specified in the contract and that is granted to the jurisdictional health department under this chapter. However, the jurisdictional health department shall have the approval of the legislative authority or authorities it serves before entering into any such agreement with the department of ecology.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2016[1989 c 431 § 16]; ]

== 70A.205.110 - Solid waste disposal facility siting—Site review—Local solid waste advisory committees—Membership.
. Each county or city siting a solid waste disposal facility shall review each potential site for conformance with the standards as set by the department for:

.. Geology;

.. Groundwater;

.. Soil;

.. Flooding;

.. Surface water;

.. Slope;

.. Cover material;

.. Capacity;

.. Climatic factors;

.. Land use;

.. Toxic air emissions; and

.. Other factors as determined by the department.

. The standards in subsection (1) of this section shall be designed to use the best available technology to protect the environment and human health, and shall be revised periodically to reflect new technology and information.

. Each county shall establish a local solid waste advisory committee to assist in the development of programs and policies concerning solid waste handling and disposal and to review and comment upon proposed rules, policies, or ordinances prior to their adoption. Such committees shall consist of a minimum of nine members and shall represent a balance of interests including, but not limited to, citizens, public interest groups, business, the waste management industry, agriculture, and local elected public officials. The members shall be appointed by the county legislative authority. A county or city shall not apply for funds from the state and local improvements revolving account, Waste Disposal Facilities, 1980, under RCW 43.83.350, for the preparation, update, or major amendment of a comprehensive solid waste management plan unless the plan or revision has been prepared with the active assistance and participation of a local solid waste advisory committee.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6605-S.SL.pdf?cite=2016%20c%20119%20§%202[2016 c 119 § 2]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1859.SL.pdf?cite=2015%201st%20sp.s.%20c%204%20§%2049[2015 1st sp.s. c 4 § 49]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2011[1989 c 431 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c123.pdf?cite=1984%20c%20123%20§%204[1984 c 123 § 4]; ]

== 70A.205.115 - Private businesses involvement in source separated materials—Local solid waste advisory committee to examine.
. Each local solid waste advisory committee shall conduct one or more meetings for the purpose of determining how local private recycling and solid waste collection businesses may participate in the development and implementation of programs to collect source separated materials from residences, and to process and market materials collected for recycling. The meetings shall include local private recycling businesses, private solid waste collection companies operating within the jurisdiction, and the local solid waste planning agencies. The meetings shall be held during the development of the waste reduction and recycling element or no later than one year prior to the date that a jurisdiction is required to submit the element under RCW 70A.205.075(2).

. The meeting requirement under subsection (1) of this section shall apply whenever a city or county develops or amends the waste reduction and recycling element required under this chapter. Jurisdictions having approved waste reduction and recycling elements or having initiated a process for the selection of a service provider as of May 21, 1991, do not have to comply with the requirements of subsection (1) of this section until the next revisions to the waste reduction and recycling element are made or required.

. After the waste reduction and recycling element is approved by the local legislative authority but before it is submitted to the department for approval, the local solid waste advisory committee shall hold at least one additional meeting to review the element.

. For the purpose of this section, "private recycling business" means any private for-profit or private not-for-profit business that engages in the processing and marketing of recyclable materials.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201171[2020 c 20 § 1171]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5591-S2.SL.pdf?cite=1991%20c%20319%20§%20402[1991 c 319 § 402]; ]

== 70A.205.120 - Permit for solid waste handling facility—Required.
Except as provided otherwise in RCW 70A.205.260, 70A.205.265, 70A.205.270, 70A.205.275, or 70A.205.290, after approval of the comprehensive solid waste plan by the department no solid waste handling facility or facilities shall be maintained, established, or modified until the county, city, or other person operating such site has obtained a permit pursuant to RCW 70A.205.125 or 70A.205.135.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201172[2020 c 20 § 1172]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5797-S.SL.pdf?cite=2009%20c%20178%20§%204[2009 c 178 § 4]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6203-S.SL.pdf?cite=1998%20c%20156%20§%203[1998 c 156 § 3]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1419-S.SL.pdf?cite=1997%20c%20213%20§%202[1997 c 213 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c134.pdf?cite=1969%20ex.s.%20c%20134%20§%2017[1969 ex.s. c 134 § 17]; ]

== 70A.205.125 - Permit for solid waste handling facility—Applications, fee.
. Applications for permits to operate a new or modified solid waste handling facility shall be on forms prescribed by the department and shall contain a description of the proposed facilities and operations at the site, plans and specifications for any new or additional facilities to be constructed, and such other information as the jurisdictional health department may deem necessary in order to determine whether the site and solid waste disposal facilities located thereon will comply with local regulations and state rules.

. Upon receipt of an application for a permit to establish or modify a solid waste handling facility, the jurisdictional health department shall refer one copy of the application to the department which shall report its findings to the jurisdictional health department. When the application is for a permit to establish or modify a solid waste handling facility located in an area that is not under a quarantine, as defined in RCW 17.24.007, and when the facility will receive material for composting from an area under a quarantine, the jurisdictional health department shall also provide a copy of the application to the department of agriculture. The department of agriculture shall review the application to determine whether it contains information demonstrating that the proposed facility presents a risk of spreading disease, plant pathogens, or pests to areas that are not under a quarantine. For the purposes of this subsection, "composting" means the biological degradation and transformation of organic solid waste under controlled conditions designed to promote aerobic decomposition.

. The jurisdictional health department shall investigate every application as may be necessary to determine whether a proposed or modified site and facilities meet all solid waste, air, and other applicable laws and regulations, and conforms with the approved comprehensive solid waste handling plan, and complies with all zoning requirements.

. When the jurisdictional health department finds that the permit should be issued, it shall issue such permit. Every application shall be approved or disapproved within ninety days after its receipt by the jurisdictional health department.

. The jurisdictional board of health may establish reasonable fees for permits and renewal of permits. All permit fees collected by the health department shall be deposited in the treasury and to the account from which the health department's operating expenses are paid.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6605-S.SL.pdf?cite=2016%20c%20119%20§%204[2016 c 119 § 4]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1419-S.SL.pdf?cite=1997%20c%20213%20§%203[1997 c 213 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c127.pdf?cite=1988%20c%20127%20§%2030[1988 c 127 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c134.pdf?cite=1969%20ex.s.%20c%20134%20§%2018[1969 ex.s. c 134 § 18]; ]

== 70A.205.130 - Permit for solid waste disposal site or facilities—Review by department—Appeal of issuance—Validity of permits issued after June 7, 1984.
Every permit issued by a jurisdictional health department under RCW 70A.205.125 shall be reviewed by the department to ensure that the proposed site or facility conforms with:

. All applicable laws and regulations including the minimal functional standards for solid waste handling; and

. The approved comprehensive solid waste management plan.

The department shall review the permit within thirty days after the issuance of the permit by the jurisdictional health department. The department may appeal the issuance of the permit by the jurisdictional health department to the pollution control hearings board, as described in chapter 43.21B RCW, for noncompliance with subsection (1) or (2) of this section.

No permit issued pursuant to RCW 70A.205.125 after June 7, 1984, shall be considered valid unless it has been reviewed by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201173[2020 c 20 § 1173]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c123.pdf?cite=1984%20c%20123%20§%208[1984 c 123 § 8]; ]

== 70A.205.135 - Permit for solid waste handling facility—Renewal—Appeal—Validity of renewal—Review fees.
. Every permit for an existing solid waste handling facility issued pursuant to RCW 70A.205.125 shall be renewed at least every five years on a date established by the jurisdictional health department having jurisdiction of the site and as specified in the permit. If a permit is to be renewed for longer than one year, the local jurisdictional health department may hold a public hearing before making such a decision. Prior to renewing a permit, the health department shall conduct a review as it deems necessary to assure that the solid waste handling facility or facilities located on the site continues to meet minimum functional standards of the department, applicable local regulations, and are not in conflict with the approved solid waste management plan. A jurisdictional health department shall approve or disapprove a permit renewal within forty-five days of conducting its review. The department shall review and may appeal the renewal as set forth for the approval of permits in RCW 70A.205.130.

. The jurisdictional board of health may establish reasonable fees for permits reviewed under this section. All permit fees collected by the health department shall be deposited in the treasury and to the account from which the health department's operating expenses are paid.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201174[2020 c 20 § 1174]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6203-S.SL.pdf?cite=1998%20c%20156%20§%204[1998 c 156 § 4]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1419-S.SL.pdf?cite=1997%20c%20213%20§%204[1997 c 213 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c123.pdf?cite=1984%20c%20123%20§%209[1984 c 123 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c134.pdf?cite=1969%20ex.s.%20c%20134%20§%2019[1969 ex.s. c 134 § 19]; ]

== 70A.205.140 - Permit for solid waste disposal site or facilities—Suspension.
Any permit for a solid waste disposal site issued as provided herein shall be subject to suspension at any time the jurisdictional health department determines that the site or the solid waste disposal facilities located on the site are being operated in violation of this chapter, the regulations of the department, the rules of the department of agriculture, or local laws and regulations.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6605-S.SL.pdf?cite=2016%20c%20119%20§%205[2016 c 119 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c134.pdf?cite=1969%20ex.s.%20c%20134%20§%2020[1969 ex.s. c 134 § 20]; ]

== 70A.205.145 - Exemption from solid waste permit requirements—Waste-derived soil amendments—Application—Revocation of exemption—Appeal.
. Waste-derived soil amendments that meet the standards and criteria in this section may apply for exemption from solid waste permitting as required under RCW 70A.205.120. The application shall be submitted to the department in a format determined by the department or an equivalent format. The application shall include:

.. Analytical data showing that the waste-derived soil amendments meet standards established under RCW 15.54.800; and

.. Other information deemed appropriate by the department to protect human health and the environment.

. After receipt of an application, the department shall review it to determine whether the application is complete, and forward a copy of the complete application to all interested jurisdictional health departments and the department of agriculture for review and comment. Within forty-five days, the jurisdictional health departments and the department of agriculture shall forward their comments and any other information they deem relevant to the department, which shall then give final approval or disapproval of the application. The department of agriculture's comments must be limited to addressing whether approving the application risks spreading disease, plant pathogens, or pests to areas that are not under a quarantine, as defined in RCW 17.24.007. Every complete application shall be approved or disapproved by the department within ninety days after receipt.

. The department, after providing opportunity for comments from the jurisdictional health departments and the department of agriculture, may at any time revoke an exemption granted under this section if the quality or use of the waste-derived soil amendment changes or the management, storage, or end use of the waste-derived soil amendment constitutes a threat to human health or the environment.

. Any aggrieved party may appeal the determination by the department in subsection (2) or (3) of this section to the pollution control hearings board.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201175[2020 c 20 § 1175]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6605-S.SL.pdf?cite=2016%20c%20119%20§%207[2016 c 119 § 7]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6474-S.SL.pdf?cite=1998%20c%2036%20§%2018[1998 c 36 § 18]; ]

== 70A.205.150 - Exemption from solid waste permit requirements—Medication disposal.
An authorized collector regulated under chapter 69.48 RCW is not required to obtain a permit under RCW 70A.205.120 unless the authorized collector is required to obtain a permit under RCW 70A.205.120 as a consequence of activities that are not directly associated with the collection facility's activities under chapter 69.48 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201176[2020 c 20 § 1176]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1047-S.SL.pdf?cite=2018%20c%20196%20§%2024[2018 c 196 § 24]; ]

== 70A.205.155 - Hearing—Appeal—Denial, suspension—When effective.
Whenever the jurisdictional health department denies a permit or suspends a permit for a solid waste disposal site, it shall, upon request of the applicant or holder of the permit, grant a hearing on such denial or suspension within thirty days after the request therefor is made. Notice of the hearing shall be given to all interested parties, including the county or city having jurisdiction over the site and the department. Within thirty days after the hearing, the health officer shall notify the applicant or the holder of the permit in writing of his or her determination and the reasons therefor. Any party aggrieved by such determination may appeal to the pollution control hearings board by filing with the hearings board a notice of appeal within thirty days after receipt of notice of the determination of the health officer. The hearings board shall hold a hearing in accordance with the provisions of the administrative procedure act, chapter 34.05 RCW. If the jurisdictional health department denies a permit renewal or suspends a permit for an operating waste recycling facility that receives waste from more than one city or county, and the applicant or holder of the permit requests a hearing or files an appeal under this section, the permit denial or suspension shall not be effective until the completion of the appeal process under this section, unless the jurisdictional health department declares that continued operation of the waste recycling facility poses a very probable threat to human health and the environment.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20411[2012 c 117 § 411]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2960-S.SL.pdf?cite=1998%20c%2090%20§%203[1998 c 90 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c109.pdf?cite=1987%20c%20109%20§%2021[1987 c 109 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c134.pdf?cite=1969%20ex.s.%20c%20134%20§%2021[1969 ex.s. c 134 § 21]; ]

== 70A.205.160 - Solid waste collection companies—Notice of changes in tipping fees and disposal rate schedules.
To provide solid waste collection companies with sufficient time to prepare and submit tariffs and rate filings for public comment and commission approval, the owner or operator of a transfer station, landfill, or facility used to burn solid waste shall provide seventy-five days' notice to solid waste collection companies of any change in tipping fees and disposal rate schedules. The notice period shall begin on the date individual notice to a collection company is delivered to the company or is postmarked.

A collection company may agree to a shorter notice period: PROVIDED, That such agreement by a company shall not affect the notice requirements for rate filings under RCW 81.28.050.

The owner of a transfer station, landfill or facility used to burn solid waste may agree to provide companies with a longer notice period.

"Solid waste collection companies" as used in this section means the companies regulated by the commission pursuant to chapter 81.77 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1260-S.SL.pdf?cite=1993%20c%20300%20§%203[1993 c 300 § 3]; ]

== 70A.205.165 - Landfill disposal facilities—Reserve accounts required by July 1, 1987—Exception—Rules.
. By July 1, 1987, each holder or applicant of a permit for a landfill disposal facility issued under this chapter shall establish a reserve account to cover the costs of closing the facility in accordance with state and federal regulations. The account shall be designed to ensure that there will be adequate revenue available by the projected date of closure. A landfill disposal facility maintained on private property for the sole use of the entity owning the site and a landfill disposal facility operated and maintained by a government shall not be required to establish a reserve account if, to the satisfaction of the department, the entity or government provides another form of financial assurance adequate to comply with the requirements of this section.

. By July 1, 1986, the department shall adopt rules under chapter 34.05 RCW to implement subsection (1) of this section. The department is not required to adopt rules pertaining to other approved forms of financial assurance to cover the costs of closing a landfill disposal facility. The rules shall include but not be limited to:

.. Methods to estimate closure costs, including postclosure monitoring, pollution prevention measures, and any other procedures required under state and federal regulations;

.. Methods to ensure that reserve accounts receive adequate funds, including:

... Requirements that the reserve account be generated by user fees. However, the department may waive this requirement for existing landfills if user fees would be prohibitively high;

... Requirements that moneys be placed in the reserve account on a regular basis and that the reserve account be kept separate from all other accounts; and

... Procedures for the department to verify that adequate sums are deposited in the reserve account; and

.. Methods to ensure that other types of financial assurance provided in accordance with subsection (1) of this section are adequate to cover the costs of closing the facility.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2670-S.SL.pdf?cite=2000%20c%20114%20§%201[2000 c 114 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c436.pdf?cite=1985%20c%20436%20§%201[1985 c 436 § 1]; ]

== 70A.205.170 - Waste generated outside the state—Findings.
The legislature finds that:

. The state of Washington has responded to the increasing challenges of safe, affordable disposal of solid waste by an ambitious program of waste reduction, recycling and reuse, as well as strict standards to ensure the safe handling, transportation, and disposal of solid waste;

. All communities in Washington participate in these programs through locally available recycling services, increased source separation and material recovery requirements, programs for waste reduction and product reuse, and performance standards that apply to all solid waste disposal facilities in the state;

. New requirements for the siting and performance of disposal facilities have greatly decreased the number of such facilities in Washington, and the state has a significant interest in ensuring adequate disposal capacity within the state;

. The landfilling, incineration, and other disposal of solid waste may adversely impact public health and environmental quality, and the state has a significant interest in decreasing volumes of the waste stream destined for disposal;

. Because of the decreasing number of disposal facilities and other reasons, solid waste is being transported greater distances, often beyond the community where generated and is increasingly being transported between states;

. Washington's waste management priorities and programs are a balanced approach of increased reuse, recycling and waste reduction, the strengthening of markets for recycled content products, and the safe disposal of the remaining waste stream, with the costs of these programs shared equitably by all persons generating waste in the state;

. Those residing in other states who generate waste destined for disposal within Washington should also share the costs of waste diversion and management of Washington's disposal facilities, so that the risks of waste disposal and the costs of mitigating those risks are shared equitably by all waste generators, regardless of their location;

. Because Washington state may not directly regulate waste handling, reduction, and recycling activities beyond its state boundaries, the only reasonable alternative to ensure this equitable treatment of waste being disposed within Washington is to implement a program of reviewing such activities as to waste originating outside of Washington, and to assign the additional costs, when necessary, to ensure that the waste meets standards substantially equivalent to those applicable to waste generated within the state, and, in some cases, to prohibit disposal of waste where its generation and management is not subject to standards substantially equivalent to those applicable to waste generated within the state.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1047-S.SL.pdf?cite=1993%20c%20286%20§%201[1993 c 286 § 1]; ]

== 70A.205.175 - Waste generated outside the state—Solid waste disposal site facility reporting requirements—Fees.
. At least sixty days prior to receiving solid waste generated from outside of the state, the operator of a solid waste disposal site facility shall report to the department the types and quantities of waste to be received from an out-of-state source. The department shall develop guidelines for reporting this information. The guidelines shall provide for less than sixty days notice for shipments of waste made on a short-term or emergency basis. The requirements of this subsection shall take effect upon completion of the guidelines.

. Upon notice under subsection (1) of this section, the department shall identify all activities and costs necessary to ensure that solid waste generated out-of-state meets standards relating to solid waste reduction, recycling, and management substantially equivalent to those required of solid waste generated within the state. The department may assess a fee on the out-of-state waste sufficient to recover the actual costs incurred in ensuring that the out-of-state waste meets equivalent state standards. The department may delegate, to a local health department, authority to implement the activities identified by the department under this subsection. All money received from fees imposed under this subsection shall be deposited into the account used to fund the activities required by this section, and shall be used solely for the activities required by this section.

. The department may prohibit in-state disposal of solid waste generated from outside of the state, unless the generators of the waste meet: (a) Waste reduction and recycling requirements substantially equivalent to those applicable in Washington state; and (b) solid waste handling standards substantially equivalent to those applicable in Washington state.

. The department may adopt rules to implement this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201177[2020 c 20 § 1177]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1047-S.SL.pdf?cite=1993%20c%20286%20§%202[1993 c 286 § 2]; ]

== 70A.205.180 - Financial aid to jurisdictional health departments—Applications—Allocations.
Any jurisdictional health department may apply to the department for financial aid for the enforcement of rules and regulations promulgated under this chapter. Such application shall contain such information, including budget and program description, as may be prescribed by regulations of the department.

After receipt of such applications the department may allocate available funds according to criteria established by regulations of the department considering population, urban development, the number of the disposal sites, and geographical area.

The sum allocated to a jurisdictional health department shall be paid to the treasury from which the operating expenses of the health department are paid, and shall be used exclusively for inspections and administrative expenses necessary to enforce applicable regulations.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c134.pdf?cite=1969%20ex.s.%20c%20134%20§%2022[1969 ex.s. c 134 § 22]; ]

== 70A.205.185 - Financial aid to jurisdictional health departments—Matching funds requirements.
The jurisdictional health department applying for state assistance for the enforcement of this chapter shall match such aid allocated by the department in an amount not less than twenty-five percent of the total amount spent for such enforcement activity during the year. The local share of enforcement costs may be met by cash and contributed services.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c134.pdf?cite=1969%20ex.s.%20c%20134%20§%2023[1969 ex.s. c 134 § 23]; ]

== 70A.205.190 - Diversion of recyclable material—Penalty.
. No person may divert to personal use any recyclable material placed in a container as part of a recycling program, without the consent of the generator of such recyclable material or the solid waste collection company operating under the authority of a town, city, county, or the utilities and transportation commission, and no person may divert to commercial use any recyclable material placed in a container as part of a recycling program, without the consent of the person owning or operating such container.

. A violation of subsection (1) of this section is a class 1 civil infraction under chapter 7.80 RCW. Each violation of this section shall be a separate infraction.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5591-S2.SL.pdf?cite=1991%20c%20319%20§%20407[1991 c 319 § 407]; ]

== 70A.205.195 - Unlawful to dump or deposit solid waste without permit—Penalties—Litter cleanup restitution payment.
. Except as otherwise provided in this section or at a solid waste disposal site for which there is a valid permit, after the adoption of regulations or ordinances by any county, city, or jurisdictional board of health providing for the issuance of permits as provided in RCW 70A.205.100, it is unlawful for any person to dump or deposit or permit the dumping or depositing of any solid waste onto or under the surface of the ground or into the waters of this state.

. This section does not:

.. Prohibit a person from dumping or depositing solid waste resulting from his or her own activities onto or under the surface of ground owned or leased by him or her when such action does not violate statutes or ordinances, or create a nuisance;

.. Apply to a person using a waste-derived soil amendment that has been approved by the department under RCW 70A.205.145; or

.. Apply to the application of commercial fertilizer that has been registered with the department of agriculture as provided in RCW 15.54.325, and that is applied in accordance with the standards established in RCW 15.54.800(3).

. [Empty]
.. It is a class 3 civil infraction as defined in RCW 7.80.120 for a person to litter in an amount less than or equal to one cubic foot.

.. [Empty]
... It is a misdemeanor for a person to litter in an amount greater than one cubic foot but less than one cubic yard.

... A person found to have littered in an amount greater than one cubic foot, but less than one cubic yard, shall also pay a litter cleanup restitution payment. This payment must be the greater of twice the actual cost of removing and properly disposing of the litter, or fifty dollars per cubic foot of litter.

... The court shall distribute one-half of the restitution payment to the landowner where the littering occurred and one-half of the restitution payment to the jurisdictional health department investigating the incident. If the landowner provided written permission authorizing the littering on his or her property or assisted a person with littering on the landowner's property, the landowner is not entitled to any restitution ordered by the court and the full litter cleanup restitution payment must be provided to the jurisdictional health department investigating the incident.

... A jurisdictional health department receiving all or a portion of a litter cleanup restitution payment must use the payment as follows:

(A) One-half of the payment may be used by the jurisdictional health department in the fulfillment of its responsibilities under this chapter; and

(B) One-half of the payment must be used to assist property owners located within the jurisdiction of the health department with the removal and proper disposal of litter in instances when the person responsible for the illegal dumping of the solid waste cannot be determined.

.. The court may, in addition to the litter cleanup restitution payment, order the person to remove and properly dispose of the litter from the property, with prior permission of the legal owner or, in the case of public property, of the agency managing the property. The court may suspend or modify the litter cleanup restitution payment for a first-time offender under this section if the person removes and properly disposes of the litter.

.. [Empty]
... It is a gross misdemeanor for a person to litter in an amount of one cubic yard or more.

... A person found to have littered in an amount greater than one cubic yard shall also pay a litter cleanup restitution payment. This payment must be the greater of twice the actual cost of removing and properly disposing of the litter, or one hundred dollars per cubic foot of litter.

... The court shall distribute one-half of the restitution payment to the landowner where the littering occurred and one-half of the restitution payment to the jurisdictional health department investigating the incident. If the landowner provided written permission authorizing the littering on his or her property or assisted a person with littering on the landowner's property, the landowner is not entitled to any restitution ordered by the court and the full litter cleanup restitution payment must be provided to the jurisdictional health department investigating the incident.

... A jurisdictional health department receiving all or a portion of a litter cleanup restitution payment must use the payment as follows:

(A) One-half of the payment may be used by the jurisdictional health department in the fulfillment of its responsibilities under this chapter; and

(B) One-half of the payment must be used to assist property owners located within the jurisdiction of the health department with the removal and proper disposal of litter in instances when the person responsible for the illegal dumping of the solid waste cannot be determined.

.. The court may, in addition to the litter cleanup restitution payment, order the person to remove and properly dispose of the litter from the property, with prior permission of the legal owner or, in the case of public property, of the agency managing the property. The court may suspend or modify the litter cleanup restitution payment for a first-time offender under this section if the person removes and properly disposes of the litter.

. If a junk vehicle is abandoned in violation of this chapter, RCW 46.55.230 governs the vehicle's removal, disposal, and sale, and the penalties that may be imposed against the person who abandoned the vehicle.

. When enforcing this section, the enforcing authority must take reasonable action to determine and identify the person responsible for illegally dumping solid waste before requiring the owner or lessee of the property where illegal dumping of solid waste has occurred to remove and properly dispose of the litter on the site.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201178[2020 c 20 § 1178]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5350-S.SL.pdf?cite=2011%20c%20279%20§%201[2011 c 279 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1163-S.SL.pdf?cite=2001%20c%20139%20§%202[2001 c 139 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6194-S.SL.pdf?cite=2000%20c%20154%20§%203[2000 c 154 § 3]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6474-S.SL.pdf?cite=1998%20c%2036%20§%2019[1998 c 36 § 19]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5701-S.SL.pdf?cite=1997%20c%20427%20§%204[1997 c 427 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1086-S.SL.pdf?cite=1993%20c%20292%20§%203[1993 c 292 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c134.pdf?cite=1969%20ex.s.%20c%20134%20§%2024[1969 ex.s. c 134 § 24]; ]

== 70A.205.200 - Name appearing on waste material—Presumption.
Whenever solid wastes dumped in violation of RCW 70A.205.195 contain three or more items bearing the name of one individual, there shall be a rebuttable presumption that the individual whose name appears on such items committed the unlawful act of dumping.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201179[2020 c 20 § 1179]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c134.pdf?cite=1969%20ex.s.%20c%20134%20§%2025[1969 ex.s. c 134 § 25]; ]

== 70A.205.205 - Disposal of sewage sludge or septic tank sludge prohibited—Exemptions—Uses of sludge material permitted.
After January 1, 1988, the department of ecology may prohibit disposal of sewage sludge or septic tank sludge (septage) in landfills for final disposal, except on a temporary, emergency basis, if the jurisdictional health department determines that a potentially unhealthful circumstance exists. Beneficial uses of sludge in landfill reclamation is acceptable utilization and not considered disposal.

The department of ecology shall adopt rules that provide exemptions from this section on a case-by-case basis. Exemptions shall be based on the economic infeasibility of using or disposing of the sludge material other than in a landfill.

The department of ecology, in conjunction with the department of health and the department of agriculture, shall adopt rules establishing labeling and notification requirements for sludge material sold commercially or given away to the public. The department shall specify mandatory wording for labels and notification to warn the public against improper use of the material.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2640-S.SL.pdf?cite=1992%20c%20174%20§%2015[1992 c 174 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c297.pdf?cite=1986%20c%20297%20§%201[1986 c 297 § 1]; ]

== 70A.205.210 - Duties of department—State solid waste management plan—Assistance—Coordination—Tire recycling.
The department shall in addition to its other powers and duties:

. Cooperate with the appropriate federal, state, interstate and local units of government and with appropriate private organizations in carrying out the provisions of this chapter.

. Coordinate the development of a solid waste management plan for all areas of the state in cooperation with local government, the *department of community, trade, and economic development, and other appropriate state and regional agencies. The plan shall relate to solid waste management for twenty years in the future and shall be reviewed biennially, revised as necessary, and extended so that perpetually the plan shall look to the future for twenty years as a guide in carrying out a state coordinated solid waste management program. The plan shall be developed into a single integrated document and shall be adopted no later than October 1990. The plan shall be revised regularly after its initial completion so that local governments revising local comprehensive solid waste management plans can take advantage of the data and analysis in the state plan.

. Provide technical assistance to any person as well as to cities, counties, and industries.

. Initiate, conduct, and support research, demonstration projects, and investigations, and coordinate research programs pertaining to solid waste management systems.

. Develop statewide programs to increase public awareness of and participation in tire recycling, and to stimulate and encourage local private tire recycling centers and public participation in tire recycling.

. May, under the provisions of the Administrative Procedure Act, chapter 34.05 RCW, as now or hereafter amended, from time to time promulgate such rules and regulations as are necessary to carry out the purposes of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%20189[1995 c 399 § 189]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%209[1989 c 431 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c345.pdf?cite=1985%20c%20345%20§%208[1985 c 345 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c6.pdf?cite=1985%20c%206%20§%2023[1985 c 6 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c134.pdf?cite=1969%20ex.s.%20c%20134%20§%2026[1969 ex.s. c 134 § 26]; ]

== 70A.205.215 - Additional powers and duties of department.
The department shall in addition to its other duties and powers under this chapter:

. Prepare the following:

.. A management system for recycling waste paper generated by state offices and institutions in cooperation with such offices and institutions;

.. An evaluation of existing and potential systems for recovery of energy and materials from solid waste with recommendations to affected governmental agencies as to those systems which would be the most appropriate for implementation;

.. A data management system to evaluate and assist the progress of state and local jurisdictions and private industry in resource recovery;

.. Identification of potential markets, in cooperation with private industry, for recovered resources and the impact of the distribution of such resources on existing markets;

.. Studies on methods of transportation, collection, reduction, separation, and packaging which will encourage more efficient utilization of existing waste recovery facilities;

.. Recommendations on incentives, including state grants, loans, and other assistance, to local governments which will encourage the recovery and recycling of solid wastes.

. Provide technical information and assistance to state and local jurisdictions, the public, and private industry on solid waste recovery and/or recycling.

. Procure and expend funds available from federal agencies and other sources to assist the implementation by local governments of solid waste recovery and/or recycling programs, and projects.

. Conduct necessary research and studies to carry out the purposes of this chapter.

. Encourage and assist local governments and private industry to develop pilot solid waste recovery and/or recycling projects.

. Monitor, assist with research, and collect data for use in assessing feasibility for others to develop solid waste recovery and/or recycling projects.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%20131[1998 c 245 § 131]; 1975-'76 2nd ex.s. c 41 § 5; ]

== 70A.205.220 - Department to cooperate with public and private departments, agencies, and associations.
The department shall work closely with the department of commerce, the department of enterprise services, and with other state departments and agencies, the Washington state association of counties, the association of Washington cities, and business associations, to carry out the objectives and purposes of chapter 41, Laws of 1975-'76 2nd ex. sess.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5024.SL.pdf?cite=2015%20c%20225%20§%20106[2015 c 225 § 106]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%20190[1995 c 399 § 190]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c466.pdf?cite=1985%20c%20466%20§%2069[1985 c 466 § 69]; 1975-'76 2nd ex.s. c 41 § 6; ]

== 70A.205.225 - Department authorized to disburse referendum 26 (RCW  43.83.330) fund for local government solid waste projects.
The department is authorized to use referendum 26 (RCW 43.83.330) funds of the Washington futures account to disburse to local governments in developing solid waste recovery and/or recycling projects.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1859.SL.pdf?cite=2015%201st%20sp.s.%20c%204%20§%2050[2015 1st sp.s. c 4 § 50]; 1975-'76 2nd ex.s. c 41 § 10; ]

== 70A.205.230 - Department authorized to disburse funds under RCW  43.83.350 for local government solid waste projects.
The department is authorized to use funds under RCW 43.83.350 to disburse to local governments in developing solid waste recovery or recycling projects. Priority shall be given to those projects that use incineration of solid waste to produce energy and to recycling projects.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1859.SL.pdf?cite=2015%201st%20sp.s.%20c%204%20§%2051[2015 1st sp.s. c 4 § 51]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c123.pdf?cite=1984%20c%20123%20§%2010[1984 c 123 § 10]; ]

== 70A.205.235 - Hazardous substance remedial actions—Procedural requirements not applicable.
The procedural requirements of this chapter shall not apply to any person conducting a remedial action at a facility pursuant to a consent decree, order, or agreed order issued pursuant to chapter 70A.305 RCW, or to the department of ecology when it conducts a remedial action under chapter 70A.305 RCW. The department of ecology shall ensure compliance with the substantive requirements of this chapter through the consent decree, order, or agreed order issued pursuant to chapter 70A.305 RCW, or during the department-conducted remedial action, through the procedures developed by the department pursuant to RCW 70A.305.090.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201180[2020 c 20 § 1180]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6339-S.SL.pdf?cite=1994%20c%20257%20§%2016[1994 c 257 § 16]; ]

== 70A.205.240 - Determination of best solid waste management practices—Department to develop method to monitor waste stream—Collectors to report quantity and quality of waste—Confidentiality of proprietary information.
The department of ecology shall determine the best management practices for categories of solid waste in accordance with the priority solid waste management methods established in RCW 70A.205.005. In order to make this determination, the department shall conduct a comprehensive solid waste stream analysis and evaluation. Following establishment of baseline data resulting from an initial in-depth analysis of the waste stream, the department shall develop a less intensive method of monitoring the disposed waste stream including, but not limited to, changes in the amount of waste generated and waste type. The department shall monitor curbside collection programs and other waste segregation and disposal technologies to determine, to the extent possible, the effectiveness of these programs in terms of cost and participation, their applicability to other locations, and their implications regarding rules adopted under this chapter. Persons who collect solid waste shall annually report to the department the types and quantities of solid waste that are collected and where it is delivered. The department shall adopt guidelines for reporting and for keeping proprietary information confidential.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201181[2020 c 20 § 1181]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2013[1989 c 431 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c184.pdf?cite=1988%20c%20184%20§%201[1988 c 184 § 1]; ]

== 70A.205.245 - Solid waste stream analysis.
The comprehensive, statewide solid waste stream analysis under RCW 70A.205.240 shall be based on representative solid waste generation areas and solid waste generation sources within the state. The following information and evaluations shall be included:

. Solid waste generation rates for each category;

. The rate of recycling being achieved within the state for each category of solid waste;

. The current and potential rates of solid waste reduction within the state;

. A technological assessment of current solid waste reduction and recycling methods and systems, including cost/benefit analyses;

. An assessment of the feasibility of segregating solid waste at: (a) The original source, (b) transfer stations, and (c) the point of final disposal;

. A review of methods that will increase the rate of solid waste reduction; and

. An assessment of new and existing technologies that are available for solid waste management including an analysis of the associated environmental risks and costs.

The data required by the analysis under this section shall be kept current and shall be available to local governments and the waste management industry.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201182[2020 c 20 § 1182]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c184.pdf?cite=1988%20c%20184%20§%202[1988 c 184 § 2]; ]

== 70A.205.250 - Solid waste stream evaluation.
. The evaluation of the solid waste stream required in RCW 70A.205.240 shall include the following elements:

.. The department shall determine which management method for each category of solid waste will have the least environmental impact; and

.. The department shall evaluate the costs of various management options for each category of solid waste, including a review of market availability, and shall take into consideration the economic impact on affected parties;

.. Based on the results of (a) and (b) of this subsection, the department shall determine the best management for each category of solid waste. Different management methods for the same categories of waste may be developed for different parts of the state.

. The department shall give priority to evaluating categories of solid waste that, in relation to other categories of solid waste, comprise a large volume of the solid waste stream or present a high potential of harm to human health. At a minimum the following categories of waste shall be evaluated:

.. By January 1, 1989, yard waste and other biodegradable materials, paper products, disposable diapers, and batteries; and

.. By January 1, 1990, metals, glass, plastics, styrofoam or rigid lightweight cellular polystyrene, and tires.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201183[2020 c 20 § 1183]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c184.pdf?cite=1988%20c%20184%20§%203[1988 c 184 § 3]; ]

== 70A.205.255 - Analysis and evaluation to be incorporated in state solid waste management plan.
The department shall incorporate the information from the analysis and evaluation conducted under RCW 70A.205.240 through 70A.205.250 to the state solid waste management plan under RCW 70A.205.210. The plan shall be revised periodically as the evaluation and analysis is updated.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201184[2020 c 20 § 1184]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c184.pdf?cite=1988%20c%20184%20§%204[1988 c 184 § 4]; ]

== 70A.205.260 - Solid waste—Beneficial uses—Permitting requirement exemptions.
. The department may by rule exempt a solid waste from the permitting requirements of this chapter for one or more beneficial uses. In adopting such rules, the department shall specify both the solid waste that is exempted from the permitting requirements and the beneficial use or uses for which the solid waste is so exempted. The department shall consider: (a) Whether the material will be beneficially used or reused; and (b) whether the beneficial use or reuse of the material will present threats to human health or the environment.

. The department may also exempt a solid waste from the permitting requirements of this chapter for one or more beneficial uses by approving an application for such an exemption. The department shall establish by rule procedures under which a person may apply to the department for such an exemption. The rules shall establish criteria for providing such an exemption, which shall include, but not be limited to: (a) The material will be beneficially used or reused; and (b) the beneficial use or reuse of the material will not present threats to human health or the environment. Rules adopted under this subsection shall identify the information that an application shall contain. Persons seeking such an exemption shall apply to the department under the procedures established by the rules adopted under this subsection.

. After receipt of an application filed under rules adopted under subsection (2) of this section, the department shall review the application to determine whether it is complete, and forward a copy of the completed application to all jurisdictional health departments and the department of agriculture for review and comment. Within forty-five days, the jurisdictional health departments and the department of agriculture shall forward to the department their comments and any other information they deem relevant to the department's decision to approve or disapprove the application. The department of agriculture's comments must be limited to addressing whether approving the application risks spreading disease, plant pathogens, or pests to areas that are not under a quarantine, as defined in RCW 17.24.007. Every complete application shall be approved or disapproved by the department within ninety days of receipt. If the application is approved by the department, the solid waste is exempt from the permitting requirements of this chapter when used anywhere in the state in the manner approved by the department. If the composition, use, or reuse of the solid waste is not consistent with the terms and conditions of the department's approval of the application, the use of the solid waste remains subject to the permitting requirements of this chapter.

. The department shall establish procedures by rule for providing to the public and the solid waste industry notice of and an opportunity to comment on each application for an exemption under subsection (2) of this section.

. Any jurisdictional health department or applicant may appeal the decision of the department to approve or disapprove an application under subsection (3) of this section. The appeal shall be made to the pollution control hearings board by filing with the hearings board a notice of appeal within thirty days of the decision of the department. The hearings board's review of the decision shall be made in accordance with chapter 43.21B RCW and any subsequent appeal of a decision of the board shall be made in accordance with RCW 43.21B.180.

. This section shall not be deemed to invalidate the exemptions or determinations of nonapplicability in the department's solid waste rules as they exist on June 11, 1998, which exemptions and determinations are recognized and confirmed subject to the department's continuing authority to modify or revoke those exemptions or determinations by rule.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6605-S.SL.pdf?cite=2016%20c%20119%20§%206[2016 c 119 § 6]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6203-S.SL.pdf?cite=1998%20c%20156%20§%202[1998 c 156 § 2]; ]

== 70A.205.265 - Solid waste handling permit—Exemption from requirements—Application of section—Rules.
. Notwithstanding any other provision of this chapter, the department may by rule exempt from the requirements to obtain a solid waste handling permit any category of solid waste handling facility that it determines to:

.. Present little or no environmental risk; and

.. Meet the environmental protection and performance requirements required for other similar solid waste facilities.

. This section does not apply to any facility or category of facilities that:

.. Receives municipal solid waste destined for final disposal, including but not limited to transfer stations, landfills, and incinerators;

.. Applies putrescible solid waste on land for final disposal purposes;

.. Handles mixed solid wastes that have not been processed to segregate solid waste materials destined for disposal from other solid waste materials destined for a beneficial use or recycling;

.. Receives or processes organic waste materials into compost in volumes that generally far exceed those handled by municipal park departments, master gardening programs, and households; or

.. Receives solid waste destined for recycling or reuse, the operation of which is determined by the department to present risks to human health and the environment.

. Rules adopted under this section shall contain such terms and conditions as the department deems necessary to ensure compliance with applicable statutes and rules. If a facility does not operate in compliance with the terms and conditions established for an exemption under subsection (1) of this section, the facility is subject to the permitting requirements for solid waste handling under this chapter.

. This section shall not be deemed to invalidate the exemptions or determinations of nonapplicability in the department's solid waste rules as they exist on June 11, 1998, which exemptions and determinations are recognized and confirmed subject to the department's continuing authority to modify or revoke those exemptions or determinations by rule.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5788-S.SL.pdf?cite=2005%20c%20394%20§%203[2005 c 394 § 3]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6203-S.SL.pdf?cite=1998%20c%20156%20§%205[1998 c 156 § 5]; ]

== 70A.205.270 - Composting of bovine and equine carcasses—Guidelines—Exemption from solid waste handling rules.
. By July 1, 2005, the department of ecology and the department of agriculture, in consultation with the department of health, shall make available to livestock producers clearly written guidelines for the composting of bovine and equine carcasses for routine animal disposal.

. Composters of bovine and equine carcasses are exempt from the metals testing and permit requirements under the solid waste handling rules for compost that is distributed off-site if the following conditions are met:

.. The carcasses to be composted are not known or suspected to be affected with a prion-protein disease such as bovine spongiform encephalopathy, a spore-forming disease such as anthrax or other diseases designated by the state veterinarian;

.. The composter follows the written guidelines provided for in subsection (1) of this section;

.. The composter does not accept for composting animal mortalities from other sources not directly affiliated with the composter's operation;

.. The composter provides information to the end user that includes the source of the material; the quality of the compost as to its nutrient content, pathogens, and stability; and the restrictions on use of the compost as stated in (f) of this subsection;

.. The composter reports annually to the department the number of bovines and equines and the amounts of other material composted, including the composter's best estimate of the tonnage or yardage involved; and

.. The end user applies the compost only to agricultural lands that are not used for the production of root crops except as prescribed in the guidelines and ensures no compost comes into contact with the crops harvested from the lands where the compost is applied.

. If a compost production facility does not operate in compliance with the terms and conditions established for an exemption in this section, the facility shall be subject to the permitting requirements for solid waste handling under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5602-S.SL.pdf?cite=2005%20c%20510%20§%206[2005 c 510 § 6]; ]

== 70A.205.275 - Rules—Department "deferring" to other permits—Application of section.
. Notwithstanding any other provisions of this chapter, the department shall adopt rules:

.. Describing when a jurisdictional health department may, at its discretion, waive the requirement that a permit be issued for a facility under this chapter if other air, water, or environmental permits are issued for the same facility. As used in this section, a jurisdictional health department's waiving the requirement that a permit be issued for a facility under this chapter based on the issuance of such other permits for the facility is the health department's "deferring" to the other permits; and

.. Allowing deferral only if the applicant and the jurisdictional health department demonstrate that other permits for the facility will provide a comparable level of protection for human health and the environment that would be provided by a solid waste handling permit.

. This section does not apply to any transfer station, landfill, or incinerator that receives municipal solid waste destined for final disposal.

. If, before June 11, 1998, either the department or a jurisdictional health department has deferred solid waste permitting or regulation of a solid waste facility to permitting or regulation under other environmental permits for the same facility, such deferral is valid and shall not be affected by the rules developed under subsection (1) of this section.

. Rules adopted under this section shall contain such terms and conditions as the department deems necessary to ensure compliance with applicable statutes and rules.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6203-S.SL.pdf?cite=1998%20c%20156%20§%206[1998 c 156 § 6]; ]

== 70A.205.280 - Penalty.
. The department may assess a civil penalty in an amount not to exceed one thousand dollars per day per violation to any person exempt from solid waste permitting in accordance with RCW 70A.205.145, 70A.205.260, 70A.205.265, 70A.205.270, or 70A.205.290 who fails to comply with the terms and conditions of the exemption. Each such violation shall be a separate and distinct offense, and in the case of a continuing violation, each day's continuance shall be a separate and distinct violation. The penalty provided in this section shall be imposed pursuant to RCW 43.21B.300.

. If a person violates a provision of any of the sections referenced in subsection (1) of this section, the department may issue an appropriate order to ensure compliance with the conditions of the exemption. The order may be appealed pursuant to RCW 43.21B.310.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201185[2020 c 20 § 1185]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6605-S.SL.pdf?cite=2016%20c%20119%20§%208[2016 c 119 § 8]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5797-S.SL.pdf?cite=2009%20c%20178%20§%205[2009 c 178 § 5]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5602-S.SL.pdf?cite=2005%20c%20510%20§%207[2005 c 510 § 7]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6203-S.SL.pdf?cite=1998%20c%20156%20§%207[1998 c 156 § 7]; ]

== 70A.205.285 - Construction.
Nothing in chapter 156, Laws of 1998 may be construed to affect chapter 81.77 RCW and the authority of the utilities and transportation commission.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6203-S.SL.pdf?cite=1998%20c%20156%20§%209[1998 c 156 § 9]; ]

== 70A.205.290 - Qualified anaerobic digesters exempt from permitting requirements of chapter—Definitions.
. An anaerobic digester that complies with the conditions specified in this section is exempt from the permitting requirements of this chapter. To qualify for the exemption, an anaerobic digester must meet the following conditions:

.. The owner or operator must provide the department or the jurisdictional health department with at least thirty days' notice of intent to operate under the conditions specified in this section and comply with any guidelines issued under subsection (2) of this section;

.. The anaerobic digester must process at least fifty percent livestock manure by volume;

.. The anaerobic digester may process no more than thirty percent imported organic waste-derived material by volume, and must comply with subsection (3) of this section;

.. The anaerobic digester must comply with design and operating standards in the natural resources conservation service's conservation practice standard code 366 in effect as of July 26, 2009;

.. Digestate must:

... Be managed in accordance with a dairy nutrient management plan under chapter 90.64 RCW that includes elements addressing management and use of digestate;

... Meet compost quality standards concerning pathogens, stability, nutrient testing, and metals before it is distributed for off-site use, or be sent to an off-site permitted compost facility for further treatment to meet compost quality standards; or

... Be processed or managed in an alternate manner approved by the department;

.. The owner or operator must allow inspection by the department or jurisdictional health department at reasonable times to verify compliance with the conditions specified in this section; and

.. The owner or operator must submit an annual report to the department or the jurisdictional health department concerning use of nonmanure material in the anaerobic digester and any required compliance testing.

. By August 1, 2009, the department and the department of agriculture, in consultation with the department of health, shall make available to anaerobic digester owners and operators clearly written guidelines for the anaerobic codigestion of livestock manure and organic waste-derived material. The guidelines must explain the steps necessary for an owner or operator to meet the conditions specified in this section for an exemption from the permitting requirements of this chapter.

. Any imported organic waste-derived material must:

.. Be preconsumer in nature;

.. Be fed into the anaerobic digester within thirty-six hours of receipt at the anaerobic digester;

.. If it is likely to contain animal by-products, be previously source-separated at a facility licensed to process food by the United States department of agriculture, the United States food and drug administration, the Washington state department of agriculture, or other applicable regulatory agency;

.. If it contains bovine processing waste, be derived from animals approved by the United States department of agriculture food safety and inspection service and not contain any specified risk material;

.. If it contains sheep carcasses or sheep processing waste, not be fed into the anaerobic digester;

.. Be stored and handled in a manner that protects surface water and groundwater and complies with best management practices;

.. Be received or stored in structures that:

... Comply with the natural resources conservation service's conservation practice standard code 313 in effect as of July 26, 2009;

... Are certified to be effective by a representative of the natural resources conservation service; or

... Meet applicable construction industry standards adopted by the American concrete institute or the American institute of steel construction and in effect as of July 26, 2009; and

.. Be managed to prevent migration of nuisance odors beyond property boundaries and minimize attraction of flies, rodents, and other vectors.

. Digestate that is managed in accordance with a dairy nutrient management plan under chapter 90.64 RCW that includes elements addressing management and use of digestate shall no longer be considered a solid waste. Use of digestate from an anaerobic digester that complies with the conditions specified in this section is exempt from the permitting requirements of this chapter.

. An anaerobic digester that does not comply with the conditions specified in this section may be subject to the permitting requirements of this chapter. In addition, violations of the conditions specified in this section are subject to provisions in RCW 70A.205.280.

. The definitions in this subsection apply throughout this section unless the context clearly requires otherwise:

.. "Anaerobic digester" means a vessel that processes organic material into biogas and digestate using microorganisms in a decomposition process within a closed, oxygen-free container.

.. "Best management practices" means managerial practices that prevent or reduce water pollution.

.. "Digestate" means both solid and liquid substances that remain following anaerobic digestion of organic material in an anaerobic digester.

.. "Imported" means originating off of the farm or other site where the anaerobic digester is being operated.

.. "Organic waste-derived material" has the same meaning as defined in RCW 15.54.270 and any other organic wastes approved by the department, except for organic waste-derived material collected through municipal commercial and residential solid waste collection programs.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201186[2020 c 20 § 1186]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5797-S.SL.pdf?cite=2009%20c%20178%20§%201[2009 c 178 § 1]; ]

== 70A.205.300 - Transporters—Definition—Registration required—Penalties.
. For the purposes of this section and RCW 70A.205.310, "transporter" means any person or entity that transports recyclable materials from commercial or industrial generators over the public highways of the state of Washington for compensation, and who are required to possess a permit to operate from the Washington utilities and transportation commission under chapter 81.80 RCW. "Transporter" includes commercial recycling operations of certificated solid waste collection companies as provided in chapter 81.77 RCW. "Transporter" does not include:

.. Carriers of commercial recyclable materials, when such materials are owned or being bought or sold by the entity or person, and being carried in their own vehicle, when such activity is incidental to the conduct of an entity or person's primary business;

.. Entities or persons hauling their own recyclables or hauling recyclables they generated or purchased and transported in their own vehicles;

.. Nonprofit or charitable organizations collecting and transporting recyclable materials from a buyback center, drop box, or from a commercial or industrial generator of recyclable materials;

.. City municipal solid waste departments or city solid waste contractors; or

.. Common carriers under chapter 81.80 RCW whose primary business is not the transportation of recyclable materials.

. All transporters shall register with the department prior to the transportation of recyclable materials. The department shall supply forms for registration.

. A transporter who transports recyclable materials within the state without a transporter registration required by this section is subject to a civil penalty in an amount up to one thousand dollars per violation.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201187[2020 c 20 § 1187]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5788-S.SL.pdf?cite=2005%20c%20394%20§%204[2005 c 394 § 4]; ]

== 70A.205.310 - Transporters—Delivery of recyclable materials to transfer station or landfill prohibited—Records—Penalty.
. A transporter may not deliver any recyclable materials for disposal to a transfer station or landfill.

. A transporter shall keep records of locations and quantities specifically identified in relation to a generator's name, service date, address, and invoice, documenting where recyclables have been sold, delivered for processing, or otherwise marketed. These records must be retained for two years from the date of collection, and must be made accessible for inspection by the department and the local health department.

. A transporter who violates the provisions of this section is subject to a civil penalty of up to one thousand dollars per violation.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5788-S.SL.pdf?cite=2005%20c%20394%20§%205[2005 c 394 § 5]; ]

== 70A.205.320 - Damages.
Any person damaged by a violation of RCW 70A.205.300 through 70A.205.340 may bring a civil action for such a violation by seeking either injunctive relief or damages, or both, in the superior court of the county in which the violation took place or in Thurston county. The prevailing party in such an action is entitled to reasonable costs and attorneys' fees, including those on appeal.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201188[2020 c 20 § 1188]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5788-S.SL.pdf?cite=2005%20c%20394%20§%206[2005 c 394 § 6]; ]

== 70A.205.330 - Solid waste recyclers—Notice—Report—Penalty.
. All facilities that recycle solid waste, except for those facilities with a current solid waste handling permit issued under RCW 70A.205.120, must notify the department in writing within thirty days prior to operation, or ninety days from July 24, 2005, for existing recycling operations, of the intent to conduct recycling in accordance with this section. Notification must be in writing, and include:

.. Contact information for the person conducting the recycling activity;

.. A general description of the recycling activity;

.. A description of the types of solid waste being recycled; and

.. A general explanation of the recycling processes and methods.

. Each facility that recycles solid waste, except those facilities with a current solid waste handling permit issued under RCW 70A.205.120, shall prepare and submit an annual report to the department by April 1st on forms supplied by the department. The annual report must detail recycling activities during the previous calendar year and include the following information:

.. The name and address of the recycling operation;

.. The calendar year covered by the report;

.. The annual quantities and types of waste received, recycled, and disposed, in tons, for purposes of determining progress towards achieving the goals of waste reduction, waste recycling, and treatment in accordance with RCW 70A.205.005(4); and

.. Any additional information required by written notification of the department that is needed to determine progress towards achieving the goals of waste reduction, waste recycling, and treatment in accordance with RCW 70A.205.005(4).

. Any facility, except for product take-back centers, that recycles solid waste materials within the state without first obtaining a solid waste handling permit under RCW 70A.205.120 or completing a notification under this section is subject to a civil penalty of up to one thousand dollars per violation.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201189[2020 c 20 § 1189]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5788-S.SL.pdf?cite=2005%20c%20394%20§%207[2005 c 394 § 7]; ]

== 70A.205.340 - Financial assurance requirements.
. The department may adopt rules that establish financial assurance requirements for recycling facilities that do not already have financial assurance requirements under this chapter, or are not already specifically exempted from financial assurance requirements under this chapter. The financial assurance requirements must take into consideration the amounts and types of recyclable materials recycled at the facility, and the potential closure and postclosure costs associated with the recycling facility; which assurance may consist of posting of a surety bond in an amount sufficient to meet these requirements or other financial instrument, but in no case less than ten thousand dollars.

. A recycling facility is required to meet financial assurance requirements adopted by the department by rule, unless the facility is already required to provide financial assurance under other provisions of this chapter.

. Facilities that collect, recover, process, or otherwise recycle scrap metal, processed scrap metal, unprocessed home scrap metal, and unprocessed prompt scrap metal are exempt from the requirements of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5788-S.SL.pdf?cite=2005%20c%20394%20§%208[2005 c 394 § 8]; ]

== 70A.205.400 - Disposal of vehicle tires outside designated area prohibited—Penalty—Exemption.
. No person may drop, deposit, discard, or otherwise dispose of vehicle tires on any public property or private property in this state or in the waters of this state whether from a vehicle or otherwise, including, but not limited to, any public highway, public park, beach, campground, forestland, recreational area, trailer park, highway, road, street, or alley unless:

.. The property is designated by the state, or by any of its agencies or political subdivisions, for the disposal of discarded vehicle tires; and

.. The person is authorized to use the property for such purpose.

. A violation of this section is punishable by a civil penalty, which shall not be less than two hundred dollars nor more than two thousand dollars for each offense.

. This section does not apply to the storage or deposit of vehicle tires in quantities deemed exempt under rules adopted by the department of ecology under its functional standards for solid waste.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c345.pdf?cite=1985%20c%20345%20§%204[1985 c 345 § 4]; ]

== 70A.205.405 - Fee on the retail sale of new replacement vehicle tires.
. There is levied a one dollar per tire fee on the retail sale of new replacement vehicle tires. The fee imposed in this section must be paid by the buyer to the seller, and each seller shall collect from the buyer the full amount of the fee. The fee collected from the buyer by the seller less the ten percent amount retained by the seller as provided in RCW 70A.205.430(1) must be paid to the department of revenue in accordance with RCW 82.32.045.

. The department of revenue shall incorporate into the agency's regular audit cycle a reconciliation of the number of tires sold and the amount of revenue collected by the businesses selling new replacement vehicle tires at retail. The department of revenue shall collect on the business excise tax return from the businesses selling new replacement vehicle tires at retail:

.. The number of tires sold; and

.. The fee levied in this section.

. All other applicable provisions of chapter 82.32 RCW have full force and application with respect to the fee imposed under this section. The department of revenue shall administer this section.

. For the purposes of this section, "new replacement vehicle tires" means tires that are newly manufactured for vehicle purposes and does not include retreaded vehicle tires.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201190[2020 c 20 § 1190]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5976.SL.pdf?cite=2009%20c%20261%20§%202[2009 c 261 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2085-S.SL.pdf?cite=2005%20c%20354%20§%202[2005 c 354 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2092[1989 c 431 § 92]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c345.pdf?cite=1985%20c%20345%20§%205[1985 c 345 § 5]; ]

== 70A.205.410 - Fee on the retail sale of new replacement vehicle tires—Failure to collect, pay to department—Penalties.
. The fee required by this chapter, to be collected by the seller, shall be deemed to be held in trust by the seller until paid to the department of revenue, and any seller who appropriates or converts the fee collected to his or her own use or to any use other than the payment of the fee to the extent that the money required to be collected is not available for payment on the due date as prescribed in this chapter is guilty of a gross misdemeanor.

. In case any seller fails to collect the fee imposed in this chapter or, having collected the fee, fails to pay it to the department of revenue in the manner prescribed by this chapter, whether such failure is the result of his or her own acts or the result of acts or conditions beyond his or her control, he or she shall, nevertheless, be personally liable to the state for the amount of the fee.

. The amount of the fee, until paid by the buyer to the seller or to the department of revenue, shall constitute a debt from the buyer to the seller and any seller who fails or refuses to collect the fee as required with intent to violate the provisions of this chapter or to gain some advantage or benefit, either direct or indirect, and any buyer who refuses to pay any fee due under this chapter is guilty of a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2085-S.SL.pdf?cite=2005%20c%20354%20§%204[2005 c 354 § 4]; ]

== 70A.205.415 - Waste tire removal account.
The waste tire removal account is created in the state treasury. Expenditures from the account may be used for the cleanup of unauthorized waste tire piles, measures that prevent future accumulation of unauthorized waste tire piles, and road wear related maintenance on state and local public highways. During the 2007-2009 fiscal biennium, the legislature may transfer from the waste tire removal account to the motor vehicle fund such amounts as reflect the excess fund balance of the waste tire removal account.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5976.SL.pdf?cite=2009%20c%20261%20§%203[2009 c 261 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1094-S.SL.pdf?cite=2007%20c%20518%20§%20708[2007 c 518 § 708]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2085-S.SL.pdf?cite=2005%20c%20354%20§%203[2005 c 354 § 3]; ]

== 70A.205.420 - Waste tire removal account—Use—Information required to be posted to department's website.
. Moneys in the waste tire removal account may be appropriated to the department of ecology:

.. To provide for funding to state and local governments for the removal of discarded vehicle tires from unauthorized tire dump sites; and

.. To accomplish the other purposes of RCW 70A.205.010 as they relate to waste tire cleanup under this chapter.

. In spending funds in the account under this section, the department shall identify communities with the most severe problems with waste tires and provide funds first to those communities to remove accumulations of waste tires.

. The department shall provide on its website a summary of state and local government efforts funded using the waste tire removal account, a list of authorized waste tire storage sites and transporters, and tire recycling and reuse rates in the state for each calendar year.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201191[2020 c 20 § 1191]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2636.SL.pdf?cite=2014%20c%2076%20§%206[2014 c 76 § 6]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5976.SL.pdf?cite=2009%20c%20261%20§%205[2009 c 261 § 5]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2085-S.SL.pdf?cite=2005%20c%20354%20§%205[2005 c 354 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c250.pdf?cite=1988%20c%20250%20§%201[1988 c 250 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c345.pdf?cite=1985%20c%20345%20§%207[1985 c 345 § 7]; ]

== 70A.205.425 - Waste tire removal account—Use of moneys—Transfer of any balance in excess of one million dollars to the motor vehicle account.
. All receipts from tire fees imposed under RCW 70A.205.405, except as provided in subsection (2) of this section, must be deposited in the waste tire removal account created under RCW 70A.205.415. Moneys in the account may be spent only after appropriation. Expenditures from the account may be used for the cleanup of unauthorized waste tire piles and measures that prevent future accumulation of unauthorized waste tire piles.

. On September 1st of odd-numbered years, the state treasurer must transfer any cash balance in excess of one million dollars from the waste tire removal account created under RCW 70A.205.415 to the motor vehicle fund for the purpose of road wear related maintenance on state and local public highways.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201192[2020 c 20 § 1192]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5316.SL.pdf?cite=2017%203rd%20sp.s.%20c%2025%20§%2010[2017 3rd sp.s. c 25 § 10]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6381-S.SL.pdf?cite=2010%20c%20247%20§%20704[2010 c 247 § 704]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5976.SL.pdf?cite=2009%20c%20261%20§%204[2009 c 261 § 4]; ]

== 70A.205.430 - Disposition of fee.
. Every person engaged in making retail sales of new replacement vehicle tires in this state shall retain ten percent of the collected one dollar fee. The moneys retained may be used for costs associated with the proper management of the waste vehicle tires by the retailer.

. The department of ecology will administer the funds for the purposes specified in RCW 70A.205.010(6) including, but not limited to:

.. Making grants to local governments for pilot demonstration projects for on-site shredding and recycling of tires from unauthorized dump sites;

.. Grants to local government for enforcement programs;

.. Implementation of a public information and education program to include posters, signs, and informational materials to be distributed to retail tire sales and tire service outlets;

.. Product marketing studies for recycled tires and alternatives to land disposal.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201193[2020 c 20 § 1193]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2093[1989 c 431 § 93]; ]

== 70A.205.435 - Cooperation with department to aid tire recycling.
To aid in the statewide tire recycling campaign, the legislature strongly encourages various industry organizations which are active in resource recycling efforts to provide active cooperation with the department of ecology so that additional technology can be developed for the tire recycling campaign.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c345.pdf?cite=1985%20c%20345%20§%209[1985 c 345 § 9]; ]

== 70A.205.440 - Waste tires—Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout RCW 70A.205.445 through 70A.205.455.

. "Storage" or "storing" means the placing of more than eight hundred waste tires in a manner that does not constitute final disposal of the waste tires.

. "Transportation" or "transporting" means picking up or transporting waste tires for the purpose of storage or final disposal.

. "Waste tires" means tires that are no longer suitable for their original intended purpose because of wear, damage, or defect.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201194[2020 c 20 § 1194]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c250.pdf?cite=1988%20c%20250%20§%203[1988 c 250 § 3]; ]

== 70A.205.445 - Waste tires—License for transport or storage business—Requirements.
Any person engaged in the business of transporting or storing waste tires shall be licensed by the department. To obtain a license, each applicant must:

. Provide assurances that the applicant is in compliance with this chapter and the rules regarding waste tire storage and transportation;

. Accept liability for and authorize the department to recover any costs incurred in any cleanup of waste tires transported or newly stored by the applicant in violation of this section, or RCW 70A.205.450, 70A.205.410, or 70A.205.460, or rules adopted thereunder, after July 1, 2005;

. After January 1, 2006, for waste tires transported or stored before July 1, 2005, or for waste tires transported or stored after July 1, 2005, post a bond in an amount to be determined by the department sufficient to cover the liability for the cost of cleanup of the transported or stored waste tires, in favor of the state of Washington. In lieu of the bond, the applicant may submit financial assurances acceptable to the department;

. Be registered in the state of Washington as a business and be in compliance with all state laws, rules, and local ordinances;

. Have a federal tax identification number and be in compliance with all applicable federal codes and regulations; and

. Report annually to the department the amount of tires transported and their disposition. Failure to report shall result in revocation of the license.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201195[2020 c 20 § 1195]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5976.SL.pdf?cite=2009%20c%20261%20§%206[2009 c 261 § 6]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2085-S.SL.pdf?cite=2005%20c%20354%20§%206[2005 c 354 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c250.pdf?cite=1988%20c%20250%20§%204[1988 c 250 § 4]; ]

== 70A.205.450 - Waste tires—Violation of RCW  70A.205.445—Penalty.
. Any person who transports or stores waste tires without a license in violation of RCW 70A.205.445 shall be guilty of a gross misdemeanor and upon conviction shall be punished under RCW 9A.20.021(2).

. Any person who transports or stores waste tires without a license in violation of RCW 70A.205.445 is liable for the costs of cleanup of any and all waste tires transported or stored. This subsection does not apply to the storage of waste tires when the storage of the tires occurred before July 1, 2005, and the storage was licensed in accordance with RCW 70A.205.445 at the time the tires were stored.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201196[2020 c 20 § 1196]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2085-S.SL.pdf?cite=2005%20c%20354%20§%207[2005 c 354 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2095[1989 c 431 § 95]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c250.pdf?cite=1988%20c%20250%20§%205[1988 c 250 § 5]; ]

== 70A.205.455 - Waste tires—Contracts with unlicensed persons prohibited.
No business may enter into a contract for:

. Transportation of waste tires with an unlicensed waste tire transporter; or

. Waste tire storage with an unlicensed owner or operator of a waste tire storage site.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c250.pdf?cite=1988%20c%20250%20§%206[1988 c 250 § 6]; ]

== 70A.205.460 - Limitations on liability.
No person or business, having documented proof that it legally transferred possession of waste tires to a validly licensed transporter or storer of waste tires or to a validly permitted recycler, has any further liability related to the waste tires legally transferred.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2085-S.SL.pdf?cite=2005%20c%20354%20§%208[2005 c 354 § 8]; ]

== 70A.205.500 - Educational material promoting household waste reduction and recycling.
The department of ecology, at the request of a local government jurisdiction, may periodically provide educational material promoting household waste reduction and recycling to public and private refuse haulers. The educational material shall be distributed to households receiving refuse collection service by local governments or the refuse hauler providing service. The refuse hauler may distribute the educational material by any means that assures timely delivery.

Reasonable expenses incurred in the distribution of this material shall be considered, for rate-making purposes, as legitimate operating expenses of garbage and refuse haulers regulated under chapter 81.77 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c175.pdf?cite=1988%20c%20175%20§%203[1988 c 175 § 3]; ]

== 70A.205.505 - Battery disposal—Restrictions—Violators subject to fine—"Vehicle battery" defined.
. No person may knowingly dispose of a vehicle battery except by delivery to: A person or entity selling lead acid batteries, a person or entity authorized by the department to accept the battery, or to a secondary lead smelter.

. No owner or operator of a solid waste disposal site shall knowingly accept for disposal used vehicle batteries except when authorized to do so by the department or by the federal government.

. Any person who violates this section shall be subject to a fine of up to one thousand dollars. Each battery will constitute a separate violation. Nothing in this section and RCW 70A.205.510 through 70A.205.530 shall supersede the provisions under chapter 70A.300 RCW.

. For purposes of this section and RCW 70A.205.510 through 70A.205.530, "vehicle battery" means batteries capable for use in any vehicle, having a core consisting of elemental lead, and a capacity of six or more volts.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201197[2020 c 20 § 1197]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2037[1989 c 431 § 37]; ]

== 70A.205.510 - Identification procedure for persons accepting used vehicle batteries.
The department shall establish a procedure to identify, on an annual basis, those persons accepting used vehicle batteries from retail establishments.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2038[1989 c 431 § 38]; ]

== 70A.205.515 - Requirements for accepting used batteries by retailers of vehicle batteries—Notice.
A person selling vehicle batteries at retail in the state shall:

. Accept, at the time of purchase of a replacement battery, in the place where the new batteries are physically transferred to the purchasers, and in a quantity at least equal to the number of new batteries purchased, used vehicle batteries from the purchasers, if offered by the purchasers. When a purchaser fails to provide an equivalent used battery or batteries, the purchaser may reclaim the core charge paid under RCW 70A.205.520 by returning, to the point of purchase within thirty days, a used battery or batteries and a receipt showing proof of purchase from the establishment where the replacement battery or batteries were purchased; and

. Post written notice which must be at least eight and one-half inches by eleven inches in size and must contain the universal recycling symbol and the following language:

.. "It is illegal to put a motor vehicle battery or other vehicle battery in your garbage."

.. "State law requires us to accept used motor vehicle batteries or other vehicle batteries for recycling, in exchange for new batteries purchased."

.. "When you buy a battery, state law also requires us to include a core charge of five dollars or more if you do not return your old battery for exchange."

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201198[2020 c 20 § 1198]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2039[1989 c 431 § 39]; ]

== 70A.205.520 - Retail core charge.
Each retail sale of a vehicle battery shall include, in the price of the battery for sale, a core charge of not less than five dollars. When a purchaser offers the seller a used battery of equivalent size, the seller shall omit the core charge from the price of the battery.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2040[1989 c 431 § 40]; ]

== 70A.205.525 - Vehicle battery wholesalers—Obligations regarding used batteries—Noncompliance procedure.
. A person selling vehicle batteries at wholesale to a retail establishment in this state shall accept, at the time and place of transfer, used vehicle batteries in a quantity at least equal to the number of new batteries purchased, if offered by the purchaser.

. When a battery wholesaler, or agent of the wholesaler, fails to accept used vehicle batteries as provided in this section, a retailer may file a complaint with the department and the department shall investigate any such complaint.

. [Empty]
.. The department shall issue an order suspending any of the provisions of RCW 70A.205.515 through 70A.205.530 whenever it finds that the market price of lead has fallen to the extent that new battery wholesalers' estimated statewide average cost of transporting used batteries to a smelter or other person or entity in the business of purchasing used batteries is clearly greater than the market price paid for used lead batteries by such smelter or person or entity.

.. The order of suspension shall only apply to batteries that are sold at retail during the period in which the suspension order is effective.

.. The department shall limit its suspension order to a definite period not exceeding six months, but shall revoke the order prior to its expiration date should it find that the reasons for its issuance are no longer valid.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201199[2020 c 20 § 1199]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2041[1989 c 431 § 41]; ]

== 70A.205.530 - Department to distribute printed notice—Issuance of warnings and citations—Fines.
The department shall produce, print, and distribute the notices required by RCW 70A.205.515 to all places where vehicle batteries are offered for sale at retail and in performing its duties under this section the department may inspect any place, building, or premise governed by RCW 70A.205.520. Authorized employees of the agency may issue warnings and citations to persons who fail to comply with the requirements of RCW 70A.205.505 through 70A.205.535. Failure to conform to the notice requirements of RCW 70A.205.515 shall subject the violator to a fine imposed by the department not to exceed one thousand dollars. However, no such fine shall be imposed unless the department has issued a warning of infraction for the first offense. Each day that a violator does not comply with the requirements of chapter 431, Laws of 1989 following the issuance of an initial warning of infraction shall constitute a separate offense.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201200[2020 c 20 § 1200]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2042[1989 c 431 § 42]; ]

== 70A.205.535 - Rules.
The department shall adopt rules providing for the implementation and enforcement of RCW 70A.205.505 through 70A.205.530.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201201[2020 c 20 § 1201]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2043[1989 c 431 § 43]; ]

== 70A.205.600 - Solid waste incineration or energy recovery facility—Environmental impact statement requirements.
No solid waste incineration or energy recovery facility shall be operated prior to the completion of an environmental impact statement containing the considerations required under RCW 43.21C.030(2)(c) and prepared pursuant to the procedures of chapter 43.21C RCW. This section does not apply to a facility operated prior to January 1, 1989, as a solid waste incineration facility or energy recovery facility burning solid waste.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2055[1989 c 431 § 55]; ]

== 70A.205.605 - Incineration of medical waste.
Incineration of medical waste shall be conducted under sufficient burning conditions to reduce all combustible material to a form such that no portion of the combustible material is visible in its uncombusted state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2077[1989 c 431 § 77]; ]

== 70A.205.610 - Sharps waste—Drop-off sites—Pharmacy return program.
. A solid waste planning jurisdiction may designate sharps waste container drop-off sites.

. A pharmacy return program shall not be considered a solid waste handling facility and shall not be required to obtain a solid waste permit. A pharmacy return program is required to register, at no cost, with the department. To facilitate designation of sharps waste drop-off sites, the department shall share the name and location of registered pharmacy return programs with jurisdictional health departments and local solid waste management officials.

. A public or private provider of solid waste collection service may provide a program to collect source separated residential sharps waste containers as provided in chapter 70A.228 RCW.

. For the purpose of this section, "sharps waste," "sharps waste container," and "pharmacy return program" shall have the same meanings as provided in RCW 70A.228.010.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201202[2020 c 20 § 1202]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2401-S.SL.pdf?cite=1994%20c%20165%20§%205[1994 c 165 § 5]; ]

== 70A.205.615 - Closure of energy recovery and incineration facilities—Recordkeeping requirements.
The department shall require energy recovery and incineration facilities to retain records of monitoring and operation data for a minimum of ten years after permanent closure of the facility.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c114.pdf?cite=1990%20c%20114%20§%204[1990 c 114 § 4]; ]

== 70A.205.620 - Paper conservation program—Paper recycling program.
By July 1, 2010, each state agency shall develop and implement:

. A paper conservation program. Each state agency shall endeavor to conserve paper by at least thirty percent of their current paper use.

. A paper recycling program to encourage recycling of all paper products with the goal of recycling one hundred percent of all copy and printing paper in all buildings with twenty-five employees or more.

. For the purposes of this section, "state agencies" include, but are not limited to, colleges, universities, offices of elected and appointed officers, the supreme court, court of appeals, and administrative departments of state government.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2287-S.SL.pdf?cite=2009%20c%20356%20§%201[2009 c 356 § 1]; ]

== 70A.205.700 - Develop and establish objectives and strategies for the reuse and recycling of construction aggregate and recycled concrete materials.
. The department of transportation and its implementation partners must collaboratively develop and establish objectives and strategies for the reuse and recycling of construction aggregate and recycled concrete materials. This process must include the development of criteria for the successful and sustainable long-term recycling of construction aggregate and recycled concrete materials in Washington state transportation, roadway, street, highway, and other transportation infrastructure projects.

. The department of transportation must, unless construction aggregate and recycled concrete materials are not readily available and cost-effective, specify and annually use a minimum of twenty-five percent construction aggregate and recycled concrete materials on its cumulative transportation, roadway, street, highway, and other transportation infrastructure projects.

. [Empty]
.. All local governmental entities with a population of one hundred thousand residents or more must, as part of their contracting process, request and accept bids that include the use of construction aggregate and recycled concrete materials for each transportation, roadway, street, highway, or other transportation infrastructure project.

.. Prior to awarding a contract for a transportation, roadway, street, highway, or other transportation infrastructure project, the local governmental entity must compare the lowest responsible bid proposing to use construction aggregate and recycled concrete materials with the lowest responsible bid not proposing to use construction aggregate and recycled concrete materials, and award the contract to the bidder proposing to use the highest percentage of construction aggregate and recycled concrete materials if that bid is the same as, or less than, a bidder not proposing to use construction aggregate and recycled concrete materials or proposing to use a lower percentage of construction aggregate and recycled concrete materials.

. Any local governmental entity with a population of less than one hundred thousand residents must:

.. Review and determine the capacity for recycling and reuse of construction aggregate and recycled concrete materials for roadway, street, highway, and other transportation infrastructure projects in its jurisdiction;

.. Establish practical and applicable strategies to recycle and reuse construction aggregate and recycled concrete materials for roadway, street, highway, and other transportation infrastructure projects in its jurisdiction; and

.. Upon the completion of the review and strategy development, begin implementing the strategies to achieve the recycling and reuse objectives established for its jurisdiction.

. The applications and related specification standards for state and local transportation and infrastructure projects that reuse and recycle construction aggregate and recycled concrete materials to be used in the implementation of this section are outlined in the department of transportation's standard specifications for road, bridge, and municipal construction, section 9-03.21, table 9-03.21(1)E.

. The definitions in this subsection apply throughout this section unless the context clearly requires otherwise.

.. "Construction aggregate and recycled concrete materials" means reclaimed coarse and fine aggregate cement and concrete mixtures as commonly defined by the American public works association, the federal highway administration, and department of transportation specifications.

.. "Implementation partners" means local governmental entities and interested Washington-based associations representing the appropriate sectors of the construction industry.

.. "Local governmental entities" means cities or counties.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1695-S.SL.pdf?cite=2015%20c%20142%20§%202[2015 c 142 § 2]; ]

== 70A.205.710 - Composting food and yard wastes—Grants and study.
. In order to establish the feasibility of composting food and yard wastes, the department shall provide funds, as available, to local governments submitting a proposal to compost such wastes.

. The department, in cooperation with the *department of community, trade, and economic development, may approve an application if the project can demonstrate the essential parameters for successful composting, including, but not limited to, cost-effectiveness, handling and safety requirements, and current and potential markets.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%20132[1998 c 245 § 132]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%20191[1995 c 399 § 191]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2097[1989 c 431 § 97]; ]

== 70A.205.715 - Food waste reduction—Goal—Plan—Definitions.
. A goal is established for the state to reduce by fifty percent the amount of food waste generated annually by 2030, relative to 2015 levels. A subset of this goal must include a prevention goal to reduce the amount of edible food that is wasted.

. The department may estimate 2015 levels of wasted food in Washington using any combination of solid waste reporting data obtained under this chapter and surveys and studies measuring wasted food and food waste in other jurisdictions. For the purposes of measuring progress towards the goal in subsection (1) of this section, the department must adopt standardized metrics and processes for measuring or estimating volumes of wasted food and food waste generated in the state.

. By October 1, 2020, the department, in consultation with the department of agriculture and the department of health, must develop and adopt a state wasted food reduction and food waste diversion plan designed to achieve the goal established in subsection (1) of this section.

.. The wasted food reduction and food waste diversion plan must include strategies, in descending order of priority, to:

... Prevent and reduce the wasting of edible food by residents and businesses;

... Help match and support the capacity for edible food that would otherwise be wasted with food banks and other distributors that will ensure the food reaches those who need it; and

... Support productive uses of inedible food materials, including using it for animal feed, energy production through anaerobic digestion, or other commercial uses, and for off-site or on-site management systems including composting, vermicomposting, or other biological systems.

.. The wasted food reduction and food waste diversion plan must be designed to:

... Recommend a regulatory environment that optimizes activities and processes to rescue safe, nutritious, edible food;

... Recommend a funding environment in which stable, predictable resources are provided to wasted food prevention and rescue and food waste recovery activities in such a way as to allow the development of additional capacity and the use of new technologies;

... Avoid placing burdensome regulations on the hunger relief system, and ensure that organizations involved in wasted food prevention and rescue, and food waste recovery, retain discretion to accept or reject donations of food when appropriate;

... Provide state technical support to wasted food prevention and rescue and food waste recovery organizations;

.. Support the development and distribution of equitable materials to support food waste and wasted food educational and programmatic efforts in K-12 schools, in collaboration with the office of the superintendent of public instruction, and aligned with the Washington state science and social studies learning standards; and

.. Facilitate and encourage restaurants and other retail food establishments to safely donate food to food banks and food assistance programs through education and outreach to retail food establishment operators regarding safe food donation opportunities, practices, and benefits.

.. The wasted food reduction and food waste diversion plan must include suggested best practices that local governments may incorporate into solid waste management plans developed under RCW 70A.205.040.

.. The department must solicit feedback from the public and interested stakeholders throughout the process of developing and adopting the wasted food reduction and food waste diversion plan. To assist with its food waste reduction plan development responsibilities, the department may designate a stakeholder advisory panel. If the department designates a stakeholder advisory panel, it must consist of local government health departments, local government solid waste departments, food banks, hunger-focused nonprofit organizations, waste-focused nonprofit organizations, K-12 public education, and food businesses or food business associations.

.. The department must identify the sources of scientific, economic, or other technical information it relied upon in developing the plan required under this section, including peer-reviewed science.

.. In conjunction with the development of the wasted food reduction and food waste diversion plan, the department and the departments of agriculture and health must consider recommending changes to state law, including changes to food quality, labeling, and inspection requirements under chapter 69.80 RCW and any changes in laws relating to the donation of food waste or wasted food for animals, in order to achieve the goal established in subsection (1) of this section. Any such recommendations must be explained via a report to the legislature submitted consistent with RCW 43.01.036 by December 1, 2020. Prior to any implementation of the plan, for the activities, programs, or policies in the plan that would impose new obligations on state agencies, local governments, businesses, or citizens, the December 1, 2020, report must outline the plan for making regulatory changes identified in the report. This outline must include the department or the appropriate state agency's plan to make recommendations for statutory or administrative rule changes identified. In combination with any identified statutory or administrative rule changes, the department or the appropriate state agency must include expected cost estimates for both government entities and private persons or businesses to comply with any recommended changes.

. In support of the development of the plan in subsection (3) of this section, the department of commerce must contract for an independent evaluation of the state's food waste and wasted food management system.

. The definitions in this subsection apply throughout this section unless the context clearly requires otherwise.

.. [Empty]
... "Food waste" means waste from fruits, vegetables, meats, dairy products, fish, shellfish, nuts, seeds, grains, and similar materials that results from the storage, preparation, cooking, handling, selling, or serving of food for human consumption.

... "Food waste" includes, but is not limited to, excess, spoiled, or unusable food and includes inedible parts commonly associated with food preparation such as pits, shells, bones, and peels. "Food waste" does not include dead animals not intended for human consumption or animal excrement.

.. "Prevention" refers to avoiding the wasting of food in the first place and represents the greatest potential for cost savings and environmental benefits for businesses, governments, and consumers.

.. "Recovery" refers to processing inedible food waste to extract value from it, through composting, anaerobic digestion, or for use as animal feedstock.

.. "Rescue" refers to the redistribution of surplus edible food to other users.

.. "Wasted food" means the edible portion of food waste.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201204[2020 c 20 § 1204]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1114-S2.SL.pdf?cite=2019%20c%20255%20§%202[2019 c 255 § 2]; ]

== 70A.205.900 - Authority and responsibility of utilities and transportation commission not changed.
Nothing in this act shall be deemed to change the authority or responsibility of the Washington utilities and transportation commission to regulate all intrastate carriers.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c134.pdf?cite=1969%20ex.s.%20c%20134%20§%2027[1969 ex.s. c 134 § 27]; ]

== 70A.205.901 - Application of chapter—Collection and transportation of recyclable materials by recycling companies or nonprofit entities—Reuse or reclamation.
Nothing in this chapter shall prevent a recycling company or nonprofit entity from collecting and transporting recyclable materials from a buy-back center, drop-box, or from a commercial or industrial generator of recyclable materials, or upon agreement with a solid waste collection company.

Nothing in this chapter shall be construed as prohibiting a commercial or industrial generator of commercial recyclable materials from selling, conveying, or arranging for transportation of such material to a recycler for reuse or reclamation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2032[1989 c 431 § 32]; ]

== 70A.205.902 - Application of chapter—Steel slag.
Nothing in this chapter is applicable to steel slag that is a primary product of production in the electric arc steel-making process, produced to specification, managed as an item of commercial value, and placed in commerce for general public consumption, provided that such steel slag material is not abandoned, discarded, or placed in the solid waste stream.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2400.SL.pdf?cite=2016%20c%20165%20§%201[2016 c 165 § 1]; ]

