= 70A.515 - Architectural paint stewardship program.
:toc:

== 70A.515.010 - Findings.
The legislature finds that:

. Leftover architectural paints are a waste management issue and present environmental risks and health and safety risks, especially to workers in the solid waste industry. During waste collection and processing, wet paint can create spills and splashes and oil paint containers may rupture, releasing fumes hazardous to workers and the remaining liquids may contribute to leachate problems in landfills. Some local governments are able to devote resources to provide collection sites or events for latex paint in order to provide their residents with at least some disposal options and to keep latex paint out of the solid waste stream. But residents and small businesses need additional and more convenient options for disposal of architectural paint. Drying latex for disposal is difficult for many residents and is wasteful of latex paint that can otherwise be reused or recycled. Local government special and moderate-risk waste collection programs are heavily impacted by the cost of managing unwanted architectural paints and these costs decrease the available funds to address other hazardous and hard-to-handle materials.

. Nationally, an estimated average of ten percent of architectural paint purchased becomes leftover paint. Current programs only collect a fraction of the potential leftover paint for proper reuse, recycling, or disposal. There is not a comprehensive statewide, end-of-life management plan for architectural paint, resulting in significant missed opportunities to reduce, reuse, and recycle paint.

. [Empty]
.. It is in the best interest of Washington for paint manufacturers to assume responsibility for the development and implementation of a cost-effective paint stewardship program that:

... Develops and implements strategies to reduce the generation of leftover paint;

... Promotes the reuse of leftover paint;

... Collects, transports, and processes leftover paint for end-of-life management, including reuse, recycling, energy recovery, and disposal; and

... Provides for transparency under chapter 42.56 RCW, the public records act.

.. A paint stewardship program will follow the paint waste management hierarchy for managing and reducing leftover paint in the order as follows:

... Reduce consumer generation of leftover paint;

... Reuse;

... Recycle; and

... Provide for energy recovery and disposal.

.. The establishment of a comprehensive leftover paint management program that requires paint manufacturers to assume responsibility for the collection, recycling, reuse, transportation, and disposal of leftover paint, and that allows paint retailers to voluntarily participate in the collection of leftover paint, will provide more opportunities for consumers to properly manage their leftover paint, provide fiscal relief for local government in managing leftover paint, keep paint out of the waste stream, and conserve natural resources.

. The legislature further finds that Washington's existing waste collection, recycling, and disposal system leads the nation in innovation and environmentally sound practices. This system has achieved some of the highest overall recycling rates in the nation at fifty-one percent in 2012. The legislature further finds that leftover paint may be a toxic and hard-to-handle waste product that is appropriate for a product stewardship program to increase the safe, convenient, and effective reuse, recycling, and disposal of leftover paint. Product stewardship programs for toxic and hard-to-handle materials, including an architectural paint stewardship program, should integrate with and complement the existing waste collection, recycling, and disposal system.

. This chapter creates an architectural paint stewardship program to be enforced by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1652-S.SL.pdf?cite=2019%20c%20344%20§%201[2019 c 344 § 1]; ]

== 70A.515.020 - Definitions.
The definitions in this section apply throughout this chapter unless the content clearly requires otherwise.

. [Empty]
.. "Architectural paint" or "paint" means interior and exterior architectural coatings, sold in a container of five gallons or less.

.. "Architectural paint" or "paint" does not mean industrial coatings, original equipment coatings, or specialty coatings.

. "Architectural paint stewardship assessment" or "assessment" means the amount determined by a stewardship organization that must be added to the purchase price of architectural paint sold in this state to cover a stewardship organization's costs of administration, education and outreach, collecting, transporting, and processing of the leftover architectural paint managed through a statewide architectural paint stewardship program.

. "Conditionally exempt small quantity generator" means a dangerous waste generator whose dangerous wastes are not subject to regulation under chapter 70A.300 RCW, hazardous waste management, solely because the waste is generated or accumulated in quantities below the threshold for regulation and meets the conditions prescribed in WAC 173-303-171(1), as it existed on July 28, 2019.

. "Conditionally exempt small quantity generator waste" means dangerous waste generated by a conditionally exempt small quantity generator.

. "Consumer" includes any household, nonprofit, small business, or other entity whose leftover paint is eligible under applicable laws and regulations.

. "Covered entity" means any: (a) Household; (b) conditionally exempt small quantity generator of leftover oil-based and latex architectural paint; or (c) generator of dangerous waste as defined in RCW 70A.300.010 that brings leftover architectural latex paint to a paint program collection site operating under an approved Washington state paint stewardship plan.

. "Curbside service" means a waste collection, recycling, and disposal service providing pickup of leftover architectural paint from residential sources, such as single-family households and multifamily housing, or other covered entities in quantities generated from households or conditionally exempt small quantity generators, provided by a solid waste collection company regulated under chapter 81.77 RCW or under a contract for solid waste services with any city or town.

. "Department" means the department of ecology.

. "Distributor" means a person that has a contractual relationship with one or more manufacturers to market and sell architectural paint to retailers in Washington.

. "End-of-life" or "end-of-life management" means activities including, but not limited to, collection, transportation, reuse, recycling, energy recovery, and disposal for leftover architectural paint.

. "Energy recovery" means the recovery of energy in a useable form from mass burning or refuse-derived fuel incineration, pyrolysis, or any other means of using the heat of combustion of solid waste that involves high temperature (above twelve hundred degrees Fahrenheit) processing.

. "Environmentally sound management practices" means practices that comply with all applicable laws and rules to protect workers, public health, and the environment, provide for adequate recordkeeping, tracking and documenting the fate of materials within the state and beyond, and include environmental liability coverage for the stewardship organization.

. "Final disposition" means the point beyond which no further processing takes place and the paint has been transformed for direct use as a feedstock in producing new products or is disposed of, including for energy recovery, in permitted facilities.

. "Household hazardous waste" means waste that exhibits any of the properties of dangerous waste that is exempt from regulation under chapter 70A.300 RCW solely because the waste is generated by households. Household hazardous waste may also include other solid waste identified in the local hazardous waste management plan prepared pursuant to chapter 70A.300 RCW.

. "Leftover paint" or "leftover architectural paint" means architectural paint not used and no longer wanted by a consumer.

. "Moderate risk waste" means solid waste that is limited to conditionally exempt small quantity generator waste and household hazardous waste as defined in this chapter.

. "Paint retailer" means any person that offers architectural paint for sale at retail in Washington.

. "Person" includes any individual, business, manufacturer, transporter, collector, processor, retailer, charity, nonprofit organization, or government agency.

. "Producer" means a manufacturer of architectural paint that is sold, offered for sale, or distributed in Washington under the producer's own name or other brand name.

. "Recycling" means transforming or remanufacturing waste materials into usable or marketable materials for use other than landfill disposal, energy recovery, or incineration. Recycling does not include collection, compacting, repacking, and sorting for the purpose of transport.

. "Reuse" means any operation by which an architectural paint product changes ownership and is used for the same purpose for which it was originally purchased.

. "Sell" or "sale" means any transfer of title for consideration, including remote sales conducted through sales outlets, catalogues, or the internet or any other similar electronic means.

. "Stewardship organization" means a nonprofit organization created by a producer or group of producers to implement a paint stewardship program required under this chapter.

. "Urban cluster" means areas of population density of two thousand five hundred to fifty thousand, as defined by the United States census bureau.

. "Urbanized area" means areas of high population density with populations of fifty thousand or greater, as defined by the United States census bureau.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201458[2020 c 20 § 1458]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1652-S.SL.pdf?cite=2019%20c%20344%20§%202[2019 c 344 § 2]; ]

== 70A.515.030 - Paint stewardship plan.
. All producers of architectural paint selling in or into the state of Washington shall participate in an approved Washington state paint stewardship plan for covered entities through membership in and appropriate funding of a stewardship organization.

. Producers not participating in a stewardship plan may not sell architectural paint in or into Washington state.

. Paint retailers are prohibited from selling architectural paint manufactured or distributed by a producer not in compliance with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1652-S.SL.pdf?cite=2019%20c%20344%20§%203[2019 c 344 § 3]; ]

== 70A.515.040 - Plan for the implementation of a paint stewardship program—Plan components—Funding mechanism—Collection—Promotion of a paint stewardship program—New plan or plan amendment.
. A stewardship organization representing producers shall submit a plan for the implementation of a paint stewardship program to the department for approval by May 30, 2020, or within one year of July 28, 2019, whichever comes later. The plan must include the following components:

.. A description of how the program proposed under the plan will collect, transport, recycle, and process leftover paint from covered entities for end-of-life management, including reuse, recycling, energy recovery, and disposal, using environmentally sound management practices;

.. Stewardship organization contact information and a list of participating brands and producers under the program;

.. A demonstration of sufficient funding for the architectural paint stewardship program as described in the plan. The plan must include a funding mechanism whereby each architectural paint producer remits to the stewardship organization payment of an architectural paint stewardship assessment for each container of architectural paint the producer sells in this state, unless the distributor or paint retailer has negotiated a voluntary agreement with the producer and stewardship organization to remit the architectural paint stewardship assessment directly to the stewardship organization on behalf of the producer for the producer's architectural paint sold by the distributor or paint retailer in the state. The plan must include a proposed budget and a description of the process used to determine the architectural paint stewardship assessment. The architectural paint stewardship assessment must be added to the cost of all architectural paint sold to Washington paint retailers and distributors, unless the distributor or paint retailer has negotiated an agreement voluntarily with the producer and stewardship organization to remit the assessment directly to the stewardship organization on behalf of the producer for the producer's architectural paint sold by the distributor or paint retailer in the state. Each Washington paint retailer or distributor must add the assessment to the purchase price of all architectural paint sold in this state. Manufacturers may not require retailers to opt to participate in a voluntary remittance agreement;

.. The establishment in the plan of a uniform architectural paint stewardship assessment for all architectural paint sold in this state, in order to ensure that the funding mechanism is equitable and sustainable. For purposes of establishing the assessment, the plan must categorize the sizes of paint containers sold at retail and determine a uniform assessment amount that applies to each category of container size. The architectural paint stewardship assessment must be sufficient to recover the costs of the architectural paint stewardship program. With the exception of the annual administration costs paid to the department under RCW 70A.515.060(4), the department may not control or have spending authority related to the funds received by the stewardship organization from the assessment. Funds received by the stewardship organization are not state funds and are not eligible to be transferred for other state purposes in an appropriations act. The plan must require that any surplus funds generated from the funding mechanism that exceed a reserve greater than the most recent year's operating expenditures be put back into the program to either increase and improve program services or reduce the cost of the program and the architectural paint stewardship assessment, or both;

.. A review by an independent financial auditor of the proposed architectural paint stewardship assessment to ensure that any added cost to paint sold in the state as a result of the paint stewardship program does not exceed the costs of the program. In a report to the department, the independent auditor must verify that the amount added to each unit of paint will cover the costs of the paint stewardship program;

.. Assignment to the department of responsibility for the approval of the architectural paint stewardship assessment based on the information provided in the plan and the auditor's report;

.. A description of the educational outreach strategy to reduce the generation of leftover paint, to promote the reuse and recycling of leftover paint, for the overall collection of leftover paint, and for the proper end-of-life management of leftover paint. The strategies may be revised by a stewardship organization based on the information collected annually;

.. A description of the reasonably convenient and available statewide collection system, including:

.. A description of how the program will provide for reasonably convenient and available statewide collection of leftover paint from covered entities in urban and rural areas of the state, including island communities;

... A description of how the program will incorporate existing public and private waste collection services and facilities for activities, which may include, but is not limited to:

(A) The reuse or processing of leftover architectural paint at the permanent collection site; and

(B) The collection, transportation, and recycling or proper disposal of leftover architectural paint;

... A description of how leftover paint will be managed using environmentally sound management practices, including reasonably following the paint waste management hierarchy of: Source reduction; reuse; recycling; energy recovery; and disposal;

.. A description of education and outreach efforts to promote the paint stewardship program. The education and outreach efforts must include strategies for reaching all sectors of the population and describe how the paint stewardship program will evaluate the effectiveness of its education and outreach;

.. A description of collection site procedural manuals for architectural paint products, including training procedures and electronic copies of materials that will be provided to collection sites; and

.. A list of transporters that will be used to manage leftover paint collected by the stewardship organization and a list of potential processors to be used for final disposition.

. [Empty]
.. To ensure adequate collection coverage, the plan must use geographic information modeling and the information required under subsection (1)(h) of this section to determine the number and distribution of collection sites based on the following criteria: At least ninety percent of Washington residents must have a permanent collection site within a fifteen-mile radius; and unless otherwise approved by the department, one additional permanent site must be established for every thirty thousand residents of an urbanized area and for every urban cluster of at least thirty thousand residents distributed to provide convenient and reasonably equitable access for residents within each.

.. For the portion of the population that does not have a permanent collection location within a fifteen-mile radius, the plan must provide residents a reasonable opportunity to drop off leftover paint at collection events. The stewardship organization, in consultation with the department and the local community, will determine a reasonable frequency and location of these collection events, to be held in underserved areas. Special consideration is to be made for providing opportunities to island and geographically isolated populations.

. [Empty]
.. Nothing in subsection (2) of this section prohibits a program plan from identifying an available curbside service for a specific area or population that provides convenient and reasonably equitable access for Washington residents that is at least equivalent to the level of convenience and access that would be provided by a collection site.

.. A fee may not be charged at the time the unwanted paint is delivered or collected for management. However, this subsection (3)(b) does not prohibit collectors providing curbside services from charging customers a fee, as provided by city contract or by the Washington utilities and transportation commission under the authority of chapter 81.77 RCW, for the additional collection cost of providing this service.

. The program plan must utilize the existing public and private waste collection services and facilities where cost-effective and mutually agreeable.

. The program must utilize existing paint retail stores as collection sites where cost-effective and mutually agreeable.

. The plan must provide the collection site name and location of each site statewide in Washington accepting architectural paint under the program.

. A stewardship organization shall promote a paint stewardship program and provide consumers, covered entities, and paint retailers with educational and informational materials describing collection opportunities for leftover paint statewide, the architectural paint stewardship assessment used to finance the program, and promotion of waste prevention, reuse, and recycling. These materials may include, but are not limited to, the following:

.. Signage that is prominently displayed and easily visible to the consumer;

.. Written materials and templates of materials for reproduction by paint retailers to be provided to the consumer at the time of purchase or delivery, or both;

.. Advertising or other promotional materials, or both, that include references to the architectural paint stewardship program; and

.. An explanation that the architectural paint stewardship assessment has been added to the purchase price of architectural paint to fund the paint stewardship program in the state. The architectural paint stewardship assessment may not be described as a department recycling fee at the point of retail.

. A stewardship organization must submit a new plan or plan amendment to the department for approval when there is a change to the amount of the assessment, if required by the department, or every five years, if the department deems it necessary.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201459[2020 c 20 § 1459]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1652-S.SL.pdf?cite=2019%20c%20344%20§%204[2019 c 344 § 4]; ]

== 70A.515.050 - Paint stewardship program plan—Collection site procedural manual—Educational and informational materials—Annual administrative fee.
. Each stewardship organization shall submit a paint stewardship program plan in accordance with RCW 70A.515.040.

. Each stewardship organization shall develop and distribute a collection site procedural manual to collection sites to help ensure proper management of architectural paints at collection locations.

. A stewardship organization shall implement the paint stewardship program plan by November 30, 2020, or within six months after approval of a paint stewardship program plan under RCW 70A.515.040, whichever is later.

. A stewardship organization shall submit an annual report by October 15, 2020, or a later date agreed to by the department, structured to be used as a basis for annual plan review by the department. The report must be based on the requirements outlined in RCW 70A.515.080.

. A stewardship organization shall work with producers, distributors, paint retailers, and local governments to provide consumers with educational and informational materials describing collection opportunities for leftover paint statewide and promotion of waste prevention, reuse, and recycling of leftover paint.

. A stewardship organization shall pay an annual administrative fee, described in RCW 70A.515.060, in an amount sufficient to cover only the department's cost of administering and enforcing a paint stewardship program established under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201460[2020 c 20 § 1460]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1652-S.SL.pdf?cite=2019%20c%20344%20§%205[2019 c 344 § 5]; ]

== 70A.515.060 - Department's review of the plan—Approval/rejection—Public review—Assessment, departmental oversight—Recovery of costs for administering and enforcing chapter—Administrative fee—Penalties—List of producers and brands on the department's website—Rules.
. The department shall review the plan within one hundred twenty days of receipt, and make a determination as to whether or not to approve the plan. The department shall provide a letter of approval for the plan if it provides for the establishment of a paint stewardship program that meets the requirements of RCW 70A.515.040 and 70A.515.050. If a plan is rejected, the department shall provide the reasons for rejecting the plan to the stewardship organization. The stewardship organization must submit a new plan within sixty days after receipt of the letter of disapproval.

. When a plan or an amendment to an approved plan is submitted under this section, the department shall make the proposed plan or amendment available for public review and comment for at least thirty days.

. The department shall provide oversight of a stewardship organization in the determination and implementation of the architectural paint stewardship assessment specified in RCW 70A.515.040(1).

. The department shall identify the costs it incurs under this chapter. The department shall set the fee at an amount that, when paid by every stewardship organization or producer that submits a plan, is adequate to reimburse the department's full costs of administering and enforcing this chapter. The total amount of annual fees collected under this subsection must not exceed the amount necessary to reimburse costs incurred by the department to enforce and administer this chapter.

. A stewardship organization or producer subject to this chapter must pay the department's administrative fee under this subsection on or before June 30, 2020, and annually thereafter. The annual administrative fee may not exceed five percent of the aggregate assessment added to the cost of all architectural paint sold by producers in the state for the preceding calendar year.

. The department shall enforce this chapter.

.. The department may administratively impose a civil penalty on any person who violates this chapter in an amount of up to one thousand dollars per violation per day.

.. The department may administratively impose a civil penalty of up to ten thousand dollars per violation per day on any person who intentionally, knowingly, or negligently violates this chapter.

.. Any person who incurs a penalty under this section may appeal the penalty to the pollution control hearings board established by chapter 43.21B RCW.

. Upon the date the first plan is approved, the department shall post on its website a list of producers and their brands for which the department has approved a plan pursuant to RCW 70A.515.040. The department shall update the list of producers and brands participating under an approved program plan on a monthly basis based on information provided to the department from a stewardship organization.

. Upon a demonstration to the satisfaction of the department that a previously unlisted producer is in compliance with this chapter, within fourteen days the department must add the name of the producer to its website.

. The department shall review each annual report required pursuant to RCW 70A.515.080 within ninety days of its submission to ensure compliance with RCW 70A.515.080(1).

. The department may adopt rules as necessary for the purpose of implementing, administering, and enforcing this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201461[2020 c 20 § 1461]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1652-S.SL.pdf?cite=2019%20c%20344%20§%206[2019 c 344 § 6]; ]

== 70A.515.070 - Required participation in an approved stewardship plan—Information regarding available end-of-life paint management options.
. A producer or paint retailer may not sell or offer for sale to any person in the state architectural paint unless the producer or brand of architectural paint is participating in an approved stewardship plan under this chapter. A retailer complies with the requirements of this section if, on the date the architectural paint was ordered from the producer or its agent, the producer of the paint was listed on the department's website as a producer participating in an approved paint stewardship program plan. However, a retailer may sell any paint purchased prior to July 28, 2019.

. A distributor or a paint retailer that distributes or sells architectural paint shall monitor the department's website to determine if the sale of a producer's architectural paint is in compliance with this chapter.

. At the time of sale to a consumer, a producer, a stewardship organization, or a paint retailer selling or offering architectural paint for sale in Washington shall provide the consumer with information regarding available end-of-life management options for leftover architectural paint collected through a paint stewardship program.

. Neither a paint retailer, nor any other retailer, is required to serve as a leftover paint collection facility.

. No fee may be charged at the time of delivery of leftover paint to a collection site.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1652-S.SL.pdf?cite=2019%20c%20344%20§%207[2019 c 344 § 7]; ]

== 70A.515.080 - Report.
. By October 15, 2020, and annually thereafter, a stewardship organization shall submit to the department a report describing the paint stewardship program that the stewardship organization implemented during the previous fiscal year. The report must include all of the following:

.. A description of the methods the stewardship organization used to reduce, reuse, collect, transport, recycle, and process leftover paint statewide in Washington;

.. The volume of latex and oil-based architectural paint collected by the stewardship organization in the preceding fiscal year in Washington, including any increase in total volume of paint collected each year, and the cost of the paint stewardship program per gallon of paint collected;

.. The volume of latex and oil-based architectural paint collected by method of disposition, including reuse, recycling, energy recovery, and disposal;

.. An estimate of the total weight of all paint containers recycled by the program;

.. A list of all processors through final disposition that are used to manage leftover paint collected by the stewardship organization in the preceding year;

.. A list of all the producers participating in the plan;

.. The total volume of architectural paint sold in Washington during the preceding year based on the architectural paint stewardship assessment collected by the stewardship organization;

.. An independent financial audit of the paint stewardship program implemented by the stewardship organization, including a breakdown of the program's expenses, such as collection, recycling, education, and overhead;

.. The total cost of implementing the paint stewardship program broken out by administrative, collection, transportation and disposition, and communications costs;

.. An evaluation of the effectiveness of the paint stewardship program from year to year, and anticipated steps, if needed, to improve performance throughout the state; and

.. A summary of outreach and education activities undertaken and samples of the educational materials that the stewardship organization provided to consumers of architectural paint during the first year of the program and any changes to those materials in subsequent years.

. The department must make all reports submitted under this section available to the general public through the internet. Consistent with RCW 70A.515.130, valuable commercial information submitted to the department under this chapter is exempt from public disclosure under RCW 42.56.270. However, the department may use and disclose such information in summary or aggregated form as long as the disclosure does not directly or indirectly identify financial, production, or sales data of an individual producer or stewardship organization. The department is not required to notify individual producers prior to making available to the general public the reports submitted under this section or aggregated or summarized information from reports submitted under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201462[2020 c 20 § 1462]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1652-S.SL.pdf?cite=2019%20c%20344%20§%208[2019 c 344 § 8]; ]

== 70A.515.090 - Immunity from certain state laws.
Producers or stewardship organizations acting on behalf of producers that prepare, submit, and implement a paint stewardship program plan pursuant to RCW 70A.515.040 and thereby are subject to regulation by the department are granted immunity from state laws relating to antitrust, restraint of trade, unfair trade practices, and other regulation of trade and commerce, for the limited purpose of planning, reporting, and operating a paint stewardship program and proposing and establishing the architectural paint stewardship assessment required in RCW 70A.515.040(1) (c) and (d).

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201463[2020 c 20 § 1463]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1652-S.SL.pdf?cite=2019%20c%20344%20§%209[2019 c 344 § 9]; ]

== 70A.515.100 - Paint product stewardship account.
The paint product stewardship account is created in the state treasury. All receipts received by the department from stewardship organizations must be deposited in the account. Moneys in the account may be spent only after appropriation. Expenditures from the account may be used by the department only for administering and enforcing paint stewardship programs.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1652-S.SL.pdf?cite=2019%20c%20344%20§%2010[2019 c 344 § 10]; ]

== 70A.515.110 - Chapter void if federal law establishes a national program.
This chapter is void if a federal law, or a combination of federal laws, takes effect that establishes a national program for the collection and recycling of architectural paint that substantially meets the intent of this chapter, including the creation of a funding mechanism for collection, transportation, recycling, and proper disposal of all architectural paint in the United States.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1652-S.SL.pdf?cite=2019%20c%20344%20§%2011[2019 c 344 § 11]; ]

== 70A.515.120 - Authority of utilities and transportation commission.
Nothing in this chapter changes or limits the authority of the Washington utilities and transportation commission to regulate collection of solid waste, including curbside collection of residential recyclable materials, nor does this chapter change or limit the authority of a city or town to provide the service itself or by contract under RCW 81.77.020.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1652-S.SL.pdf?cite=2019%20c%20344%20§%2012[2019 c 344 § 12]; ]

== 70A.515.130 - Protection of certain records from public inspection.
. Except as provided in subsection (3) of this section, records, subject to chapter 42.56 RCW, filed with the department from any person that contain valuable commercial information, including trade secrets, confidential marketing, cost, or financial information, or customer-specific usage information, are not subject to inspection or copying under chapter 42.56 RCW. When providing information to the department, a person shall designate which records or portions of records contain valuable commercial information.

. Upon receipt of a request to disclose valuable commercial information submitted under this chapter, the department must provide notice to the person or persons whose information is subject to possible inspection or copying under chapter 42.56 RCW.

. Upon the notice provided under subsection (2) of this section of the possible inspection or copying of valuable commercial information pursuant to chapter 42.56 RCW, a person may petition the superior court for an order protecting the records as confidential. The superior court must determine that the records are confidential and are not subject to inspection or copying if disclosure would result in private loss, including an unfair competitive disadvantage. If a person does not obtain an order protecting submitted records as confidential within ten days of receiving a notice from the department under subsection (2) of this section, the department may make the records available for public inspection and copying pursuant to chapter 42.56 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1652-S.SL.pdf?cite=2019%20c%20344%20§%2013[2019 c 344 § 13]; ]

