= 70A.222 - Packages containing metals and toxic chemicals.
:toc:

== 70A.222.005 - Finding.
The legislature finds and declares that:

. The management of solid waste can pose a wide range of hazards to public health and safety and to the environment;

. Packaging comprises a significant percentage of the overall solid waste stream;

. The presence of heavy metals in packaging is a part of the total concern in light of their likely presence in emissions or ash when packaging is incinerated, or in leachate when packaging is landfilled;

. Lead, mercury, cadmium, and hexavalent chromium, on the basis of available scientific and medical evidence, are of particular concern;

. The intent of this chapter is to achieve a reduction in toxicity without impeding or discouraging the expanded use of postconsumer materials in the production of packaging and its components.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5591-S2.SL.pdf?cite=1991%20c%20319%20§%20106[1991 c 319 § 106]; ]

== 70A.222.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Food package" means a package or packaging component that is intended for direct food contact and is comprised, in substantial part, of paper, paperboard, or other materials originally derived from plant fibers.

. "Manufacturer" means a person, firm, partnership, organization, joint venture, or corporation that applies a package to a product for distribution or sale.

. "Package" means a container providing a means of marketing, protecting, or handling a product and shall include a unit package, an intermediate package, and a shipping container. "Package" also means and includes unsealed receptacles such as carrying cases, crates, cups, pails, rigid foil and other trays, wrappers and wrapping films, bags, and tubs.

. "Packaging component" means an individual assembled part of a package such as, but not limited to, any interior or exterior blocking, bracing, cushioning, weatherproofing, exterior strapping, coatings, closures, inks, and labels.

. "Perfluoroalkyl and polyfluoroalkyl substances" or "PFAS chemicals" means, for the purposes of food packaging, a class of fluorinated organic chemicals containing at least one fully fluorinated carbon atom.

. "Safer alternative" means an alternative substance or chemical, demonstrated by an alternatives assessment, that meets improved hazard and exposure considerations and can be practicably and economically substituted for the original chemical.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2658-S.SL.pdf?cite=2018%20c%20138%20§%201[2018 c 138 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5591-S2.SL.pdf?cite=1991%20c%20319%20§%20107[1991 c 319 § 107]; ]

== 70A.222.020 - Concentration levels.
The sum of the concentration levels of lead, cadmium, mercury, and hexavalent chromium present in any package or packaging component shall not exceed the following:

. Six hundred parts per million by weight effective July 1, 1993;

. Two hundred fifty parts per million by weight effective July 1, 1994; and

. One hundred parts per million by weight effective July 1, 1995.

This section shall apply only to lead, cadmium, mercury, and hexavalent chromium that has been intentionally introduced as an element during manufacturing or distribution.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6357.SL.pdf?cite=1992%20c%20131%20§%201[1992 c 131 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5591-S2.SL.pdf?cite=1991%20c%20319%20§%20108[1991 c 319 § 108]; ]

== 70A.222.030 - Exemptions.
All packages and packaging components shall be subject to this chapter except the following:

. Those packages or package components with a code indicating date of manufacture that were manufactured prior to May 21, 1991;

. Those packages or packaging components that have been purchased by, delivered to, or are possessed by a retailer on or before twenty-four months following May 21, 1991, to permit opportunity to clear existing inventory of the proscribed packaging material;

. Those packages or packaging components to which lead, cadmium, mercury, or hexavalent chromium have been added in the manufacturing, forming, printing, or distribution process in order to comply with health or safety requirements of federal law or for which there is no feasible alternative; or

. Those packages and packaging components that would not exceed the maximum contaminant levels set forth in RCW 70A.222.020(1) but for the addition of postconsumer materials; and provided that the exemption for this subsection shall expire six years after May 21, 1991.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201230[2020 c 20 § 1230]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5591-S2.SL.pdf?cite=1991%20c%20319%20§%20109[1991 c 319 § 109]; ]

== 70A.222.040 - Certificate of compliance.
A certificate of compliance stating that a package or packaging component is in compliance with the requirements of this chapter shall be developed by its manufacturer. For food packaging, a manufacturer shall develop a compliance certificate by the date of a prohibition taking effect under RCW 70A.222.070. If compliance is achieved under the exemption or exemptions provided in RCW 70A.222.030, the certificate shall state the specific basis upon which the exemption is claimed. The certificate of compliance shall be signed by an authorized official of the manufacturing company. The certificate of compliance shall be kept on file by the manufacturer for as long as the package or packaging component is in use, and for three years from the date of the last sale or distribution by the manufacturer. Certificates of compliance, or copies thereof, shall be furnished to the department of ecology upon request within sixty days. If manufacturers are required under any other state statute to provide a certificate of compliance, one certificate may be developed containing all required information.

If the manufacturer or supplier of the package or packaging component reformulates or creates a new package or packaging component, the manufacturer shall develop an amended or new certificate of compliance for the reformulated or new package or packaging component.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201231[2020 c 20 § 1231]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2658-S.SL.pdf?cite=2018%20c%20138%20§%203[2018 c 138 § 3]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5591-S2.SL.pdf?cite=1991%20c%20319%20§%20110[1991 c 319 § 110]; ]

== 70A.222.050 - Certificate of compliance—Public access.
Requests from a member of the public for any certificate of compliance shall be:

. Made in writing to the department of ecology;

. Made specific as to package or packaging component information requested; and

. Responded to by the department of ecology within ninety days.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5591-S2.SL.pdf?cite=1991%20c%20319%20§%20111[1991 c 319 § 111]; ]

== 70A.222.060 - Prohibition of sale of package.
The department of ecology may prohibit the sale of any package for which a manufacturer has failed to respond to a request by the department for a certificate of compliance within the allotted period of time pursuant to RCW 70A.222.040.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201232[2020 c 20 § 1232]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5591-S2.SL.pdf?cite=1991%20c%20319%20§%20112[1991 c 319 § 112]; ]

== 70A.222.070 - Prohibition on the manufacture, sale, or distribution of certain food packaging—Safer alternatives assessment by department of ecology—Publication of findings—Report to legislature—Prohibition effective date contingent on findings.
. Beginning January 1, 2022, no person may manufacture, knowingly sell, offer for sale, distribute for sale, or distribute for use in this state food packaging to which PFAS chemicals have been intentionally added in any amount. This prohibition may not take effect until the department of ecology completes the following: (a) Identifies that safer alternatives are available, and the safer alternative determination is supported by feedback from an external peer review of the department's alternatives assessment; and (b) publishes findings, as required under subsection (3) of this section.

. To determine whether safer alternatives to PFAS chemicals exist, the department of ecology must conduct an alternatives assessment as part of the PFAS chemical action plan that:

.. Evaluates less toxic chemicals and nonchemical alternatives to replace the use of a chemical;

.. Follows the guidelines for alternatives assessments issued by the interstate chemicals clearinghouse; and

.. Includes, at a minimum, an evaluation of chemical hazards, exposure, performance, cost, and availability.

. By January 1, 2020, the department of ecology must publish its findings in the Washington State Register on whether safer alternatives to PFAS chemicals in specific applications of food packaging are available for each assessed application and submit a report with the findings and the feedback from the peer review of the department's alternatives assessment to the appropriate committees of the legislature. In order to determine that safer alternatives are available, the safer alternatives must be readily available in sufficient quantity and at a comparable cost, and perform as well as or better than PFAS chemicals in a specific food packaging application. If an alternative is a chemical, it must have previously been approved for food contact by the United States food and drug administration, such as through the issuance of a determination that the chemical has a reasonable certainty of causing no harm.

. The prohibition on the use of PFAS chemicals in food packaging:

.. Becomes effective January 1, 2022, if the report required under subsection (3) of this section finds that safer alternatives are available for specific food packaging applications;

.. Does not take effect January 1, 2022, if the report required under subsection (3) of this section does not find that safer alternatives are available for specific food packaging applications.

. If the department of ecology does not find that a safer alternative is available for some or all categories of food packaging applications, beginning January 1, 2021, and each year following, the department of ecology must review and report on alternatives as described in subsection (2) of this section. The prohibition in this section for specific food packaging applications takes effect two years after a report submitted to the legislature required under subsection (3) of this section finds that safer alternatives are available.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2658-S.SL.pdf?cite=2018%20c%20138%20§%202[2018 c 138 § 2]; ]

