= 70A.05 - Integrated climate change response strategy.
:toc:

== 70A.05.010 - Development of strategy—Central clearinghouse—Collaboration.
. The departments of ecology, agriculture, *community, trade, and economic development, fish and wildlife, natural resources, and transportation shall develop an integrated climate change response strategy to better enable state and local agencies, public and private businesses, nongovernmental organizations, and individuals to prepare for, address, and adapt to the impacts of climate change. The integrated climate change response strategy should be developed, where feasible and consistent with the direction of the strategy, in collaboration with local government agencies with climate change preparation and adaptation plans.

. The department of ecology shall serve as a central clearinghouse for relevant scientific and technical information about the impacts of climate change on Washington's ecology, economy, and society, as well as serve as a central convener for the development of vital programs and necessary policies to help the state adapt to a rapidly changing climate.

. The department of ecology shall consult and collaborate with the departments of fish and wildlife, agriculture, *community, trade, and economic development, natural resources, and transportation in developing an integrated climate change response strategy and plans of action to prepare for and adapt to climate change impacts.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5560-S2.SL.pdf?cite=2009%20c%20519%20§%2010[2009 c 519 § 10]; ]

== 70A.05.020 - Requirements of strategy—Initial climate change response strategy.
. The integrated climate change response strategy should address the impact of and adaptation to climate change, as well as the regional capacity to undertake actions, existing ecosystem and resource management concerns, and health and economic risks. In addition, the departments of ecology, agriculture, *community, trade, and economic development, fish and wildlife, natural resources, and transportation should include a range of scenarios for the purposes of planning in order to assess project vulnerability and, to the extent feasible, reduce expected risks and increase resiliency to the impacts of climate change.

. [Empty]
.. By December 1, 2011, the department of ecology shall compile an initial climate change response strategy, including information and data from the departments of fish and wildlife, agriculture, *community, trade, and economic development, natural resources, and transportation that: Summarizes the best known science on climate change impacts to Washington; assesses Washington's vulnerability to the identified climate change impacts; prioritizes solutions that can be implemented within and across state agencies; and identifies recommended funding mechanisms and technical and other essential resources for implementing solutions.

.. The initial strategy must include: 

... Efforts to identify priority planning areas for action, based on vulnerability and risk assessments;

... Barriers challenging state and local governments to take action, such as laws, policies, regulations, rules, and procedures that require revision to adequately address adaptation to climate change;

... Opportunities to integrate climate science and projected impacts into planning and decision making; and

... Methods to increase public awareness of climate change, its projected impacts on the community, and to build support for meaningful adaptation policies and strategies.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5560-S2.SL.pdf?cite=2009%20c%20519%20§%2011[2009 c 519 § 11]; ]

== 70A.05.030 - Assistance with developing strategy.
The departments of ecology, agriculture, *community, trade, and economic development, fish and wildlife, natural resources, and transportation may consult with qualified nonpartisan experts from the scientific community as needed to assist with developing an integrated climate change response strategy. The qualified nonpartisan experts from the scientific community may assist the department of ecology on the following components: 

. Identifying the timing and extent of impacts from climate change;

. Assessing the effects of climate variability and change in the context of multiple interacting stressors or impacts;

. Developing forecasting models;

. Determining the resilience of the environment, natural systems, communities, and organizations to deal with potential or actual impacts of climate change and the vulnerability to which a natural or social system is susceptible to sustaining damage from climate change impacts; and

. Identifying other issues, as determined by the department of ecology, necessary to develop policies and actions for the integrated climate change response strategy.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5560-S2.SL.pdf?cite=2009%20c%20519%20§%2012[2009 c 519 § 12]; ]

== 70A.05.040 - Incorporation of adaptation plans of action by state agencies.
State agencies shall strive to incorporate adaptation plans of action as priority activities when planning or designing agency policies and programs. Agencies shall consider: The integrated climate change response strategy when designing, planning, and funding infrastructure projects; and incorporating natural resource adaptation actions and alternative energy sources when designing and planning infrastructure projects.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5560-S2.SL.pdf?cite=2009%20c%20519%20§%2013[2009 c 519 § 13]; ]

== 70A.05.900 - Findings—2009 c 519.
The legislature finds that in chapter 14, Laws of 2008, the legislature established greenhouse gas emission reduction limits for Washington state, including a reduction of overall emissions by 2020 to emission levels in 1990, a reduction by 2035 to levels twenty-five percent below 1990 levels, and by 2050 a further reduction below 1990 levels. Based upon estimated 2006 emission levels in Washington, this will require a reduction from present emission levels of over twenty-five percent in the next eleven years. The legislature further finds that state government activities are a significant source of emissions, and that state government should meet targets for reducing emissions from its buildings, vehicles, and all operations that demonstrate that these reductions are achievable, cost-effective, and will help to promote innovative energy efficiency technologies and practices.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5560-S2.SL.pdf?cite=2009%20c%20519%20§%201[2009 c 519 § 1]; ]

