= 70A.405 - Polybrominated diphenyl ethers—Flame retardants.
:toc:

== 70A.405.005 - Findings.
Polybrominated diphenyl ethers (PBDEs) have been used extensively as flame retardants in a large number of common household products for the past thirty years. Studies on animals show that PBDEs can impact the developing brain, affecting behavior and learning after birth and into adulthood, making exposure to fetuses and children a particular concern. Levels of PBDEs are increasing in people, and in the environment, particularly in North America. Because people can be exposed to these chemicals through house dust and indoor air as well as through food, it is important to phase out their use in common household products, provided that effective flame retardants that are safer and technically feasible are available at a reasonable cost.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1024-S.SL.pdf?cite=2007%20c%2065%20§%201[2007 c 65 § 1]; ]

== 70A.405.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Comestible" means edible.

. "Commercial decabromo diphenyl ether" or "commercial deca-bde" means the chemical mixture of decabromo diphenyl ether, including associated polybrominated diphenyl ether impurities not intentionally added.

. "Department" means the department of ecology.

. "Electronic enclosure" means the plastic housing that encloses the components of electronic products, including but not limited to televisions and computers.

. "Manufacturer" means any person, firm, association, partnership, corporation, governmental entity, organization, or joint venture that produces a product containing polybrominated diphenyl ethers or an importer or domestic distributor of a noncomestible product containing polybrominated diphenyl ethers. A manufacturer does not include a retailer who:

.. Adds a private label brand or cobrands a product for sale; or

.. Assembles components to create a single noncomestible product based on an individual consumer preference.

. "Mattress" has the same meaning as defined by the United States consumer product safety commission in 16 C.F.R. Part 1633 (2007) as it existed on July 22, 2007, and includes mattress sets, box springs, futons, crib mattresses, and youth mattresses. "Mattress" includes mattress pads.

. "Medical device" means an instrument, machine, implant, or diagnostic test used to help diagnose a disease or other condition or to cure, treat, or prevent disease.

. "Polybrominated diphenyl ethers" or "PBDEs" means chemical forms that consist of diphenyl ethers bound with bromine atoms. Polybrominated diphenyl ethers include, but are not limited to, the three primary forms of the commercial mixtures known as pentabromo diphenyl ether (penta-bde), octabromo diphenyl ether (octa-bde), and decabromo diphenyl ether (deca-bde).

. "Residential upholstered furniture" means residential seating products intended for indoor use in a home or other dwelling intended for residential occupancy that consists in whole or in part of resilient cushioning materials enclosed within a covering consisting of fabric or related materials, if the resilient cushioning materials are sold with the item of upholstered furniture and the upholstered furniture is constructed with a contiguous upholstered seat and back that may include arms.

. "Retailer" means a person who offers a product for sale at retail through any means including, but not limited to, remote offerings such as sales outlets, catalogs, or the internet, but does not include a sale that is a wholesale transaction with a distributor or a retailer. A retailer does not include a person, firm, association, partnership, corporation, governmental entity, organization, or joint venture that both manufactures and sells a product at retail.

. "Technically feasible" means an alternative that is available at a cost and in sufficient quantity to permit the manufacturer to produce an economically viable product.

. "Transportation vehicle" means a mechanized vehicle that is used to transport goods or people including, but not limited to, airplanes, automobiles, motorcycles, trucks, buses, trains, boats, ships, streetcars, or monorail cars.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1024-S.SL.pdf?cite=2007%20c%2065%20§%202[2007 c 65 § 2]; ]

== 70A.405.020 - Manufacture, sale, or distribution of noncomestible products containing PBDEs—Exemptions.
After January 1, 2008, no person may manufacture, knowingly sell, offer for sale, distribute for sale, or distribute for use in this state noncomestible products containing PBDEs. Exemptions from the prohibition in this section are limited to the following:

. Products containing deca-bde, except as provided in RCW 70A.405.030;

. The sale or distribution of any used transportation vehicle manufactured before January 1, 2008, with component parts containing PBDEs;

. The sale or distribution of any used transportation vehicle parts or new transportation vehicle parts manufactured before January 1, 2008, that contain PBDEs;

. The manufacture, sale, repair, distribution, maintenance, refurbishment, or modification of equipment containing PBDEs and used primarily for military or federally funded space program applications. The exemption in this subsection (4) does not cover consumer-based goods with broad applicability;

. Federal aviation administration fire worthiness requirements and recommendations;

. The manufacture, sale, repair, distribution, maintenance, refurbishment, or modification of any new raw material or component part used in a transportation vehicle with component parts, including original spare parts, containing deca-bde;

. The use of commercial deca-bde in the maintenance, refurbishment, or modification of transportation equipment;

. The sale or distribution of any product containing PBDEs that has been previously owned, purchased, or sold in commerce, provided it was manufactured before the effective date of the prohibition;

. The manufacture, sale, or distribution of any new product or product component consisting of recycled or used materials containing deca-bde;

. The sale or purchase of any previously owned product containing PBDEs made in casual or isolated sales as defined in RCW 82.04.040 and to sales by nonprofit organizations;

. The manufacture, sale, or distribution of new carpet cushion made from recycled foam containing less than one-tenth of one percent penta-bde; and

. Medical devices.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201069[2020 c 20 § 1069]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1024-S.SL.pdf?cite=2007%20c%2065%20§%203[2007 c 65 § 3]; ]

== 70A.405.030 - Manufacture, sale, or distribution of products containing commercial deca-bde—Departments review of commercial deca-bde alternatives—Effective date of prohibitions.
. Except as provided in RCW 70A.405.090, no person may manufacture, knowingly sell, offer for sale, distribute for sale, or distribute for use in this state mattresses containing commercial deca-bde after January 1, 2008.

. Except as provided in RCW 70A.405.090, no person may manufacture, knowingly sell, offer for sale, distribute for sale, or distribute for use in this state residential upholstered furniture that contains commercial deca-bde, or any television or computer that has an electronic enclosure that contains commercial deca-bde after the effective date established in subsection (3) of this section. This prohibition may not take effect until the department and the department of health identify that a safer and technically feasible alternative is available, and the fire safety committee, created in RCW 70A.405.040, determines that the identified alternative meets applicable fire safety standards. The effective date of the prohibition must be established according to the following process:

.. The department and the department of health shall review risk assessments, scientific studies, and other relevant findings regarding alternatives to the use of commercial deca-bde in residential upholstered furniture, televisions, and computers.

.. If the department and the department of health jointly find that safer and technically feasible alternatives are available for any of these uses, the department shall convene the fire safety committee created in RCW 70A.405.040 to determine whether the identified alternatives meet applicable fire safety standards.

.. By majority vote, the fire safety committee created in RCW 70A.405.040 shall make a finding whether an alternative identified under (b) of this subsection meets applicable fire safety standards. The fire safety committee shall report their finding to the state fire marshal. After reviewing the finding of the fire safety committee, the state fire marshal shall determine whether an alternative identified under (b) of this subsection meets applicable fire safety standards. The determination of the fire marshal must be based upon the finding of the fire safety committee. The state fire marshal shall report the determination to the department.

.. The department shall seek public input on their findings, the findings of the fire safety committee, and the determination by the state fire marshal. The department shall publish these findings in the Washington State Register, and submit them in a report to the appropriate committees of the legislature. The department shall initially report these findings by December 31, 2008.

. The effective date of the prohibition is as follows:

.. If the December 31, 2008, report required in subsection (2)(d) of this section finds that a safer and technically feasible alternative that meets applicable fire safety standards is available, the prohibition takes effect January 1, 2011;

.. If the December 31, 2008, report required in subsection (2)(d) of this section does not find that a safer and technically feasible alternative that meets applicable fire safety standards is available, the prohibition does not take effect January 1, 2011. Beginning in 2009, by December 31st of each year, the department shall review and report on alternatives as described in subsection (2) of this section. The prohibition in subsection (2) of this section takes effect two years after a report submitted to the legislature required under subsection (2)(d) of this section finds that a safer and technically feasible alternative that meets applicable fire safety standards is available.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201070[2020 c 20 § 1070]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1024-S.SL.pdf?cite=2007%20c%2065%20§%204[2007 c 65 § 4]; ]

== 70A.405.040 - Fire safety committee.
. The fire safety committee is created for the exclusive purpose of finding whether an alternative identified under RCW 70A.405.030(2)(b) meets applicable fire safety standards.

. A majority vote of the members of the fire safety committee constitutes a finding that an alternative meets applicable fire safety standards.

. The fire safety committee consists of the following members:

.. A representative from the department, who shall chair the fire safety committee, and serve as an ex officio nonvoting member.

.. Five voting members, appointed by the governor, as follows:

... A representative of the office of the state fire marshal;

... A representative of a statewide association representing the interests of fire chiefs;

... A representative of a statewide association representing the interests of fire commissioners;

... A representative of a recognized statewide council, affiliated with an international association representing the interests of firefighters; and

.. A representative of a statewide association representing the interests of volunteer firefighters.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201071[2020 c 20 § 1071]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1024-S.SL.pdf?cite=2007%20c%2065%20§%205[2007 c 65 § 5]; ]

== 70A.405.050 - Departments review of commercial deca-bde alternatives and effects of PBDEs in waste stream—Publication.
The department and the department of health shall review risk assessments, scientific studies, and other relevant findings regarding alternatives to the use of commercial deca-bde in products not directly addressed in this chapter. If a flame retardant that is safer and technically feasible becomes available, the department shall convene the fire safety committee created in RCW 70A.405.040. The fire safety committee and the state fire marshal shall proceed as required in RCW 70A.405.030(2)(c) to determine if the identified alternative meets applicable fire safety standards. The department and the department of health shall also review risk assessments, scientific studies, and other findings regarding the potential effect of PBDEs in the waste stream. By December 31st of the year in which the finding is made, the department must publish the information required by this section in the Washington State Register and present it in a report to the appropriate committees of the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201072[2020 c 20 § 1072]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1024-S.SL.pdf?cite=2007%20c%2065%20§%206[2007 c 65 § 6]; ]

== 70A.405.060 - Exclusions from chapter—Transportation and storage.
Nothing in this chapter restricts the ability of a manufacturer, importer, or distributor from transporting products containing PBDEs through the state or storing the products in the state for later distribution outside the state.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1024-S.SL.pdf?cite=2007%20c%2065%20§%207[2007 c 65 § 7]; ]

== 70A.405.070 - Notification to sellers.
A manufacturer of products containing PBDEs that are restricted under this chapter must notify persons that sell the manufacturer's products in this state about the provisions of this chapter no less than ninety days prior to the effective date of the restrictions.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1024-S.SL.pdf?cite=2007%20c%2065%20§%208[2007 c 65 § 8]; ]

== 70A.405.080 - Assistance to state agencies.
The department shall assist state agencies to give priority and preference to the purchase of equipment, supplies, and other products that do not contain PBDEs.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1024-S.SL.pdf?cite=2007%20c%2065%20§%209[2007 c 65 § 9]; ]

== 70A.405.090 - Retailers—Liability—Existing stock.
. Retailers who unknowingly sell products prohibited under RCW 70A.405.020 or 70A.405.030 are not liable under this chapter.

. In-state retailers in possession of products on the date that restrictions on the sale of the products become effective under RCW 70A.405.020 or 70A.405.030 may exhaust their existing stock through sales to the public.

. The department must assist in-state retailers in identifying potential products containing PBDEs.

. If a retailer unknowingly possesses products that are prohibited for sale under RCW 70A.405.020 or 70A.405.030 and the manufacturer does not recall the products as required under RCW 70A.405.100(2), the retailer may exhaust its existing stock through sales to the public. However, no additional prohibited stock may be sold or offered for sale.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201073[2020 c 20 § 1073]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1024-S.SL.pdf?cite=2007%20c%2065%20§%2010[2007 c 65 § 10]; ]

== 70A.405.100 - Enforcement—Achieving compliance with chapter—Enforcement sequence—Recall—Penalties.
. Enforcement of this chapter must rely on notification and information exchange between the department and manufacturers. The department must achieve compliance with this chapter using the following enforcement sequence:

.. Before the effective date of the product prohibition in RCW 70A.405.020 or 70A.405.030, the department must prepare and distribute information to in-state manufacturers and out-of-state manufacturers, to the maximum extent practicable, to assist them in identifying products prohibited for manufacture, sale, or distribution under this chapter.

.. The department may request a certificate of compliance from a manufacturer. A certificate of compliance attests that a manufacturer's product or products meets the requirements of this chapter.

.. The department may issue a warning letter to a manufacturer that produces, sells, or distributes prohibited products in violation of this chapter. The department must offer information or other appropriate assistance to the manufacturer in complying with this chapter. If, after one year, compliance is not achieved, penalties may be assessed under subsection (3) of this section.

. A manufacturer that knowingly produces, sells, or distributes a product prohibited from manufacture, sale, or distribution in this state under this chapter must recall the product and reimburse the retailer or any other purchaser for the product and any applicable shipping and handling for returning the products.

. A manufacturer of products containing PBDEs in violation of this chapter is subject to a civil penalty not to exceed one thousand dollars for each violation in the case of a first offense. Manufacturers who are repeat violators are subject to a civil penalty not to exceed five thousand dollars for each repeat offense. Penalties collected under this section must be deposited in the model toxics control operating account created in RCW 70A.305.180.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201074[2020 c 20 § 1074]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5993-S.SL.pdf?cite=2019%20c%20422%20§%20404[2019 c 422 § 404]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1024-S.SL.pdf?cite=2007%20c%2065%20§%2011[2007 c 65 § 11]; ]

== 70A.405.110 - Rules.
The department may adopt rules to fully implement this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1024-S.SL.pdf?cite=2007%20c%2065%20§%2012[2007 c 65 § 12]; ]

