= 70A.415 - Hazardous substance information.
:toc:

== 70A.415.010 - Definitions.
Unless the context clearly indicates otherwise, the definitions in this section shall apply throughout this chapter.

. "Agency" means any state agency or local government entity.

. "Hazardous household substances" means those substances identified by the department as hazardous household substances in the guidelines developed by the department.

. "Department" means the department of ecology.

. "Director" means the director of the department.

. "Hazardous substances" or "hazardous materials" means those substances or materials identified as such under regulations adopted pursuant to the federal hazardous materials transportation act, the toxic substances control act, the resource recovery and conservation act, the comprehensive environmental response compensation and liability act, the federal insecticide, fungicide, and rodenticide act, the occupational safety and health act hazardous communications standards, and the state hazardous waste act.

. "Moderate risk waste" means any waste that exhibits any of the properties of dangerous waste but is exempt from regulation under this chapter solely because the waste is generated in quantities below the threshold for regulation and any household wastes that are generated from the disposal of substances identified by the department as hazardous household substances.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c410.pdf?cite=1985%20c%20410%20§%202[1985 c 410 § 2]; ]

== 70A.415.020 - Hazardous substance information and education office—Duties.
There is hereby created the hazardous substance information and education office. Through this office the department shall:

. Facilitate access to existing information on hazardous substances within a community;

. Request and obtain information about hazardous substances at specified locations and facilities from agencies that regulate those locations and facilities. The department shall review, approve, and provide confidentiality as provided by statute. Upon request of the department, each agency shall provide the information within forty-five days;

. At the request of citizens or public health or public safety organizations, compile existing information about hazardous substance use at specified locations and facilities. This information shall include but not be limited to:

.. Point and nonpoint air and water emissions;

.. Extremely hazardous, moderate risk wastes and dangerous wastes as defined in chapter 70A.300 RCW produced, used, stored, transported from, or disposed of by any facility;

.. A list of the hazardous substances present at a given site and data on their acute and chronic health and environmental effects;

.. Data on governmental pesticide use at a given site;

.. Data on commercial pesticide use at a given site if such data is only given to individuals who are chemically sensitive; and

.. Compliance history of any facility.

. Provide education to the public on the proper production, use, storage, and disposal of hazardous substances, including but not limited to:

.. A technical resource center on hazardous substance management for industry and the public;

.. Programs, in cooperation with local government, to educate generators of moderate risk waste, and provide information regarding the potential hazards to human health and the environment resulting from improper use and disposal of the waste and proper methods of handling, reducing, recycling, and disposing of the waste;

.. Public information and education relating to the safe handling and disposal of hazardous household substances; and

.. Guidelines to aid counties in developing and implementing a hazardous household substances program.

Requests for information from the hazardous substance information and education office may be made by letter or by a toll-free telephone line, if one is established by the department. Requests shall be responded to in accordance with chapter 42.56 RCW.

This section shall not require any agency to compile information that is not required by existing laws or rules.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201271[2020 c 20 § 1271]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20339[2005 c 274 § 339]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c410.pdf?cite=1985%20c%20410%20§%201[1985 c 410 § 1]; ]

