= 70A.115 - Large on-site sewage disposal systems.
:toc:

== 70A.115.005 - Findings.
The legislature finds that:

. Protection of the environment and public health requires properly designed, operated, and maintained on-site sewage systems. Failure of those systems can pose certain health and environmental hazards if sewage leaks above ground or if untreated sewage reaches surface or groundwater.

. Chapter 70A.110 RCW provides a framework for ongoing management of on-site sewage systems located in marine recovery areas and regulated by local health jurisdictions under state board of health rules. This chapter will provide a framework for comprehensive management of large on-site sewage systems statewide.

. The primary purpose of this chapter is to establish, in a single state agency, comprehensive regulation of the design, operation, and maintenance of large on-site sewage systems, and their operators, that provides both public health and environmental protection. To accomplish these purposes, this chapter provides for:

.. The permitting and continuing oversight of large on-site sewage systems;

.. The establishment by the department of standards and rules for the siting, design, construction, installation, operation, maintenance, and repair of large on-site sewage systems; and

.. The enforcement by the department of the standards and rules established under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201340[2020 c 20 § 1340]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5894-S.SL.pdf?cite=2007%20c%20343%20§%201[2007 c 343 § 1]; ]

== 70A.115.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Department" means the state department of health.

. "Industrial wastewater" means the water or liquid carried waste from an industrial process. These wastes may result from any process or activity of industry, manufacture, trade, or business, from the development of any natural resource, or from animal operations such as feedlots, poultry houses, or dairies. The term includes contaminated stormwater and leachate from solid waste facilities.

. "Large on-site sewage system" means an on-site sewage system with design flows of between three thousand five hundred gallons per day and one hundred thousand gallons per day.

. "On-site sewage system" means an integrated system of components, located on or nearby the property it serves, that conveys, stores, treats, and provides subsurface soil treatment and disposal of domestic sewage. It consists of a collection system, a treatment component or treatment sequence, and a subsurface soil disposal component. It may or may not include a mechanical treatment system. An on-site sewage system also refers to a holding tank sewage system or other system that does not have a soil dispersal component. A holding tank that discharges to a sewer is not included in the definition of on-site sewage system. A system into which stormwater or industrial wastewater is discharged is not included in the definition of on-site sewage system.

. "Person" means any individual, corporation, company, association, firm, partnership, governmental agency, or any other entity whatsoever, and the authorized agents of any such entities.

. "Secretary" means the secretary of health.

. "Waters of the state" has the same meaning as defined in RCW 90.48.020.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5894-S.SL.pdf?cite=2007%20c%20343%20§%202[2007 c 343 § 2]; ]

== 70A.115.020 - Comprehensive regulation—Department duties.
. For the protection of human health and the environment the department shall:

.. Establish and provide for the comprehensive regulation of large on-site sewage systems including, but not limited to, system siting, design, construction, installation, operation, maintenance, and repair;

.. Control and prevent pollution of streams, lakes, rivers, ponds, inland waters, salt waters, water courses, and other surface and underground waters of the state of Washington, except to the extent authorized by permits issued under this chapter;

.. Issue annual operating permits for large on-site sewage systems based on the system's ability to function properly in compliance with the applicable comprehensive regulatory requirements; and

.. Enforce the large on-site sewage system requirements.

. Large on-site sewage systems permitted by the department may not be used for treatment and disposal of industrial wastewater or combined sanitary sewer and stormwater systems.

. The work group convened under RCW 70A.110.080(4) to make recommendations to the appropriate committees of the legislature for the development of certification or licensing of maintenance specialists shall include recommendations for the development of certification or licensing of large on-site sewage system operators.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201341[2020 c 20 § 1341]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5894-S.SL.pdf?cite=2007%20c%20343%20§%203[2007 c 343 § 3]; ]

== 70A.115.030 - Operating permits required—Application.
. A person may not install or operate a large on-site sewage system without an operating permit as provided in this chapter after July 1, 2009. The owner of the system is responsible for obtaining a permit.

. The department shall issue operating permits in accordance with the rules adopted under RCW 70A.115.040.

. The department shall ensure the system meets all applicable siting, design, construction, and installation requirements prior to issuing an initial operating permit. Prior to renewing an operating permit, the department may review the performance of the system to determine compliance with rules and any permit conditions.

. At the time of initial permit application or at the time of permit renewal the department shall impose those permit conditions, requirements for system improvements, and compliance schedules as it determines are reasonable and necessary to ensure that the system will be operated and maintained properly. Each application must be accompanied by a fee as established in rules adopted by the department.

. Operating permits shall be issued for a term of one year, and shall be renewed annually, unless the operator fails to apply for a new permit or the department finds good cause to deny the application for renewal.

. Each permit may be issued only for the site and owner named in the application. Permits are not transferable or assignable except with the written approval of the department.

. The department may deny an application for a permit or modify, suspend, or revoke a permit in any case in which it finds that the permit was obtained by fraud or there is or has been a failure, refusal, or inability to comply with the requirements of this chapter or the standards or rules adopted under this chapter. RCW 43.70.115 governs notice of denial, revocation, suspension, or modification and provides the right to an adjudicative proceeding to the permit applicant or permittee.

. For systems with design flows of more than fourteen thousand five hundred gallons per day, the department shall adopt rules to ensure adequate public notice and opportunity for review and comment on initial large on-site sewage system permit applications and subsequent permit applications to increase the volume of waste disposal or change effluent characteristics. The rules must include provisions for notice of final decisions. Methods for providing notice may include email, posting on the department's internet site, publication in a local newspaper, press releases, mailings, or other means of notification the department determines appropriate.

. A person aggrieved by the issuance of an initial permit, or by the issuance of a subsequent permit to increase the volume of waste disposal or to change effluent characteristics, for systems with design flows of more than fourteen thousand five hundred gallons per day, has the right to an adjudicative proceeding. The application for an adjudicative proceeding must be in writing, state the basis for contesting the action, include a copy of the decision, be served on and received by the department within twenty-eight days of receipt of notice of the final decision, and be served in a manner that shows proof of receipt. An adjudicative proceeding conducted under this subsection is governed by chapter 34.05 RCW.

. Any permit issued by the department of ecology for a large on-site sewage system under chapter 90.48 RCW is valid until it first expires after July 22, 2007. The system owner shall apply for an operating permit at least one hundred twenty days prior to expiration of the department of ecology permit.

. Systems required to meet operator certification requirements under chapter 70A.212 RCW must continue to meet those requirements as a condition of the department operating permit.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201342[2020 c 20 § 1342]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5894-S.SL.pdf?cite=2007%20c%20343%20§%204[2007 c 343 § 4]; ]

== 70A.115.040 - Rules.
. For the protection of human health and the environment, the secretary shall adopt rules for the comprehensive regulation of large on-site sewage systems, which includes, but is not limited to, the siting, design, construction, installation, maintenance, repair, and permitting of the systems.

. In adopting the rules, the secretary shall, in consultation with the department of ecology, require that large on-site sewage systems comply with the applicable sections of chapter 90.48 RCW regarding control and prevention of pollution of waters of the state, including but not limited to:

.. Surface and groundwater standards established under RCW 90.48.035; and 

.. Those provisions requiring all known, available, and reasonable methods of treatment.

. In adopting the rules, the secretary shall ensure that requirements for large on-site sewage systems are consistent with the requirements of any comprehensive plans or development regulations adopted under chapter 36.70A RCW or any other applicable comprehensive plan, land use plan, or development regulation adopted by a city, town, or county.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5894-S.SL.pdf?cite=2007%20c%20343%20§%205[2007 c 343 § 5]; ]

== 70A.115.050 - Violations—Civil penalties.
. A person who violates a law or rule regulating large on-site sewage systems administered by the department is subject to a penalty of not more than ten thousand dollars per day for every violation. Every violation is a separate and distinct offense. In case of a continuing violation, each day's continuing violation is a separate and distinct violation. The penalty assessed must reflect the significance of the violation and the previous record of compliance on the part of the person responsible for compliance with large on-site sewage system requirements.

. Every person who, through an act of commission or omission, procures, aids, or abets a violation is considered to have violated the provisions of this section and is subject to the penalty provided in this section.

. The penalty provided for in this section must be imposed by a notice in writing to the person against whom the civil penalty is assessed and must describe the violation. The notice must be personally served in the manner of service of a summons in a civil action or in a manner that shows proof of receipt. A penalty imposed by this section is due twenty-eight days after receipt of notice unless application for an adjudicative proceeding is filed as provided in subsection (4) of this section.

. Within twenty-eight days after notice is received, the person incurring the penalty may file an application for an adjudicative proceeding and may pursue subsequent review as provided in chapter 34.05 RCW and applicable rules.

. A penalty imposed by a final administrative order is due upon service of the final administrative order. A person who fails to pay a penalty assessed by a final administrative order within thirty days of service of the final administrative order shall pay, in addition to the amount of the penalty, interest at the rate of one percent of the unpaid balance of the assessed penalty for each month or part of a month that the penalty remains unpaid, commencing with the month in which the notice of penalty was served, and reasonable attorneys' fees as are incurred if civil enforcement of the final administrative order is required to collect the penalty.

. A person who institutes proceedings for judicial review of a final administrative order assessing a civil penalty under this chapter shall place the full amount of the penalty in an interest-bearing account in the registry of the reviewing court. At the conclusion of the proceeding the court shall, as appropriate, enter a judgment on behalf of the department and order that the judgment be satisfied to the extent possible from moneys paid into the registry of the court or shall enter a judgment in favor of the person appealing the penalty assessment and order return of the moneys paid into the registry of the court together with accrued interest to the person appealing. The judgment may award reasonable attorneys' fees for the cost of the attorney general's office in representing the department.

. If no appeal is taken from a final administrative order assessing a civil penalty under this chapter, the department may file a certified copy of the final administrative order with the clerk of the superior court in which the large on-site sewage system is located or in Thurston county, and the clerk shall enter judgment in the name of the department and in the amount of the penalty assessed in the final administrative order.

. A judgment entered under subsection (6) or (7) of this section has the same force and effect as, and is subject to all of the provisions of law relating to, a judgment in a civil action, and may be enforced in the same manner as any other judgment of the court in which it is entered.

. The large on-site sewage systems account is created in the custody of the state treasurer. All receipts from penalties imposed under this section shall be deposited into the account. Expenditures from the account shall be used by the department to provide training and technical assistance to large on-site sewage system owners and operators. Only the secretary or the secretary's designee may authorize expenditures from the account. The account is subject to allotment procedures under chapter 43.88 RCW, but an appropriation is not required for expenditures.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5894-S.SL.pdf?cite=2007%20c%20343%20§%206[2007 c 343 § 6]; ]

== 70A.115.060 - Injunctions.
Notwithstanding the existence or use of any other remedy, the department may bring an action to enjoin a violation or threatened violation of this chapter or rules adopted under this chapter. The department may bring the action in the superior court of the county in which the large on-site sewage system is located or in the superior court of Thurston county.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5894-S.SL.pdf?cite=2007%20c%20343%20§%207[2007 c 343 § 7]; ]

== 70A.115.070 - Authority and duties.
The authority and duties created in this chapter are in addition to any authority and duties already provided in law. Nothing in this chapter limits the powers of the state or any political subdivision to exercise such authority.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5894-S.SL.pdf?cite=2007%20c%20343%20§%208[2007 c 343 § 8]; ]

