= 70A.10 - Weather modification.
:toc:

== 70A.10.010 - Definitions.
As used in this chapter, unless the context requires otherwise:

. "Department" means the department of ecology;

. "Operation" means the performance of weather modification and control activities pursuant to a single contract entered into for the purpose of producing or attempting to produce, a certain modifying effect within one geographical area over one continuing time interval not exceeding one year; or, in case the performance of weather modification and control activities is to be undertaken individually or jointly by a person or persons to be benefited and not undertaken pursuant to a contract, "operation" means the performance of weather modification and control activities entered into for the purpose of producing, or attempting to produce, a certain modifying effect within one geographical area over one continuing time interval not exceeding one year;

. "Research and development" means theoretical analysis exploration and experimentation, and the extension of investigative findings and theories of a scientific or technical nature into practical application for experimental and demonstration purposes, including the experimental production and testing of models, devices, equipment, materials, and processes;

. "Weather modification and control" means changing or controlling, or attempting to change or control, by artificial methods, the natural development of any or all atmospheric cloud forms or precipitation forms which occur in the troposphere.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c64.pdf?cite=1973%20c%2064%20§%201[1973 c 64 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.37.010[1965 c 8 § 43.37.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c245.pdf?cite=1957%20c%20245%20§%201[1957 c 245 § 1]; ]

== 70A.10.020 - Powers and duties.
In the performance of its functions the department may, in addition to any other acts authorized by law:

. Establish advisory committees to advise with and make recommendations to the department concerning legislation, policies, administration, research, and other matters;

. Establish by regulation or order such standards and instructions to govern the carrying out of research or projects in weather modification and control as the department may deem necessary or desirable to minimize danger to health or property; and make such rules and regulations as are necessary in the performance of its powers and duties;

. Make such studies, investigations, obtain such information, and hold such hearings as the department may deem necessary or proper to assist it in exercising its authority or in the administration or enforcement of this chapter or any regulations or orders issued thereunder;

. Appoint and fix the compensation of such personnel, including specialists and consultants, as are necessary to perform its duties and functions;

. Acquire, in the manner provided by law, such materials, equipment, and facilities as are necessary to perform its duties and functions;

. Cooperate with public or private agencies in the performance of the department's functions or duties and in furtherance of the purposes of this chapter;

. Represent the state in any and all matters pertaining to plans, procedures, or negotiations for interstate compacts relating to weather modification and control.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c64.pdf?cite=1973%20c%2064%20§%202[1973 c 64 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.37.030[1965 c 8 § 43.37.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c245.pdf?cite=1957%20c%20245%20§%203[1957 c 245 § 3]; ]

== 70A.10.030 - Promotion of research and development activities—Contracts and agreements.
The department shall exercise its powers in such manner as to promote the continued conduct of research and development activities in the fields specified below by private or public institutions or persons and to assist in the acquisition of an expanding fund of theoretical and practical knowledge in such fields. To this end the department may conduct, and make arrangements, including contracts and agreements, for the conduct of, research and development activities relating to:

. The theory and development of methods of weather modification and control, including processes, materials, and devices related thereto;

. Utilization of weather modification and control for agricultural, industrial, commercial, and other purposes;

. The protection of life and property during research and operational activities.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c64.pdf?cite=1973%20c%2064%20§%203[1973 c 64 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.37.040[1965 c 8 § 43.37.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c245.pdf?cite=1957%20c%20245%20§%204[1957 c 245 § 4]; ]

== 70A.10.040 - Hearing procedure.
In the case of hearings pursuant to RCW 70A.10.160 the department shall, and in other cases may, cause a record of the proceedings to be taken and filed with the department, together with its findings and conclusions. For any hearing, the director of the department or a representative designated by him or her is authorized to administer oaths and affirmations, examine witnesses, and issue, in the name of the department, notice of the hearing or subpoenas requiring any person to appear and testify, or to appear and produce documents, or both, at any designated place.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201044[2020 c 20 § 1044]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%205113[2009 c 549 § 5113]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c64.pdf?cite=1973%20c%2064%20§%204[1973 c 64 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.37.050[1965 c 8 § 43.37.050]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c245.pdf?cite=1957%20c%20245%20§%205[1957 c 245 § 5]; ]

== 70A.10.050 - Acceptance of gifts, donations, etc.
. The department may, subject to any limitations otherwise imposed by law, receive and accept for and in the name of the state any funds which may be offered or become available from federal grants or appropriations, private gifts, donations, or bequests, or any other source, and may expend such funds, subject to any limitations otherwise provided by law, for the encouragement of research and development by a state, public, or private agency, either by direct grant, by contract or other cooperative means.

. All license and permit fees paid to the department shall be deposited in the state general fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c64.pdf?cite=1973%20c%2064%20§%205[1973 c 64 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.37.060[1965 c 8 § 43.37.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c245.pdf?cite=1957%20c%20245%20§%206[1957 c 245 § 6]; ]

== 70A.10.060 - License and permit required.
Except as provided in RCW 70A.10.070, no person shall engage in activities for weather modification and control except under and in accordance with a license and a permit issued by the department authorizing such activities.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201045[2020 c 20 § 1045]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c64.pdf?cite=1973%20c%2064%20§%206[1973 c 64 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.37.080[1965 c 8 § 43.37.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c245.pdf?cite=1957%20c%20245%20§%208[1957 c 245 § 8]; ]

== 70A.10.070 - Exemptions.
The department, to the extent it deems practical, shall provide by regulation for exempting from license, permit, and liability requirements, (1) research and development and experiments by state and federal agencies, institutions of higher learning, and bona fide nonprofit research organizations; (2) laboratory research and experiments; (3) activities of an emergent character for protection against fire, frost, sleet, or fog; and (4) activities normally engaged in for purposes other than those of inducing, increasing, decreasing, or preventing precipitation or hail.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c64.pdf?cite=1973%20c%2064%20§%207[1973 c 64 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.37.090[1965 c 8 § 43.37.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c245.pdf?cite=1957%20c%20245%20§%209[1957 c 245 § 9]; ]

== 70A.10.080 - Licenses—Requirements, duration, renewal, fees.
. Licenses to engage in activities for weather modification and control shall be issued to applicants therefor who pay the license fee required and who demonstrate competence in the field of meteorology to the satisfaction of the department, reasonably necessary to engage in activities for weather modification and control. If the applicant is an organization, these requirements must be met by the individual or individuals who will be in control and in charge of the operation for the applicant.

. The department shall issue licenses in accordance with such procedures and subject to such conditions as it may by regulation establish to effectuate the provisions of this chapter. Each license shall be issued for a period to expire at the end of the calendar year in which it is issued and, if the licensee possesses the qualifications necessary for the issuance of a new license, shall upon application be renewed at the expiration of such period. A license shall be issued or renewed only upon the payment to the department of one hundred dollars for the license or renewal thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c64.pdf?cite=1973%20c%2064%20§%208[1973 c 64 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.37.100[1965 c 8 § 43.37.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c245.pdf?cite=1957%20c%20245%20§%2010[1957 c 245 § 10]; ]

== 70A.10.090 - Permits—Requirements—Hearing as to issuance.
The department shall issue permits in accordance with such procedures and subject to such conditions as it may by regulation establish to effectuate the provisions of this chapter only:

. If the applicant is licensed pursuant to this chapter;

. If a sufficient notice of intention is published and proof of publication is filed as required by RCW 70A.10.120;

. If the applicant furnishes proof of financial responsibility, as provided in RCW 70A.10.130, in an amount to be determined by the department but not to exceed twenty thousand dollars;

. If the fee for a permit is paid as required by RCW 70A.10.140;

. If the weather modification and control activities to be conducted under authority of the permit are determined by the department to be for the general welfare and public good;

. If the department has held an open public hearing in Olympia as to such issuance.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201046[2020 c 20 § 1046]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c64.pdf?cite=1973%20c%2064%20§%209[1973 c 64 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.37.110[1965 c 8 § 43.37.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c154.pdf?cite=1961%20c%20154%20§%202[1961 c 154 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c245.pdf?cite=1957%20c%20245%20§%2011[1957 c 245 § 11]; ]

== 70A.10.100 - Separate permit for each operation—Filing and publishing notice of intention—Activities restricted by permit and notice.
A separate permit shall be issued for each operation. Prior to undertaking any weather modification and control activities the licensee shall file with the department and also cause to be published a notice of intention. The licensee, if a permit is issued, shall confine his or her activities for the permitted operation within the time and area limits set forth in the notice of intention, unless modified by the department; and his or her activities shall also conform to any conditions imposed by the department upon the issuance of the permit or to the terms of the permit as modified after issuance.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%205114[2009 c 549 § 5114]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c64.pdf?cite=1973%20c%2064%20§%2010[1973 c 64 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.37.120[1965 c 8 § 43.37.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c154.pdf?cite=1961%20c%20154%20§%203[1961 c 154 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c245.pdf?cite=1957%20c%20245%20§%2012[1957 c 245 § 12]; ]

== 70A.10.110 - Notice of intention—Contents.
The notice of intention shall set forth at least all the following:

. The name and address of the licensee;

. The nature and object of the intended operation and the person or organization on whose behalf it is to be conducted;

. The area in which and the approximate time during which the operation will be conducted;

. The area which is intended to be affected by the operation;

. The materials and methods to be used in conducting the operation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.37.130[1965 c 8 § 43.37.130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c245.pdf?cite=1957%20c%20245%20§%2013[1957 c 245 § 13]; ]

== 70A.10.120 - Notice of intention—Publication.
. The applicant shall cause the notice of intention, or that portion thereof including the items specified in RCW 70A.10.110, to be published at least once a week for three consecutive weeks in a legal newspaper having a general circulation and published within any county in which the operation is to be conducted and in which the affected area is located, or, if the operation is to be conducted in more than one county or if the affected area is located in more than one county or is located in a county other than the one in which the operation is to be conducted, then in a legal newspaper having a general circulation and published within each of such counties. In case there is no legal newspaper published within the appropriate county, publication shall be made in a legal newspaper having a general circulation within the county;

. Proof of publication, made in the manner provided by law, shall be filed by the licensee with the department within fifteen days from the date of the last publication of the notice.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201047[2020 c 20 § 1047]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c64.pdf?cite=1973%20c%2064%20§%2011[1973 c 64 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.37.140[1965 c 8 § 43.37.140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c154.pdf?cite=1961%20c%20154%20§%204[1961 c 154 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c245.pdf?cite=1957%20c%20245%20§%2014[1957 c 245 § 14]; ]

== 70A.10.130 - Financial responsibility.
Proof of financial responsibility may be furnished by an applicant by his or her showing, to the satisfaction of the department, his or her ability to respond in damages for liability which might reasonably be attached to or result from his or her weather modification and control activities in connection with the operation for which he or she seeks a permit.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%205115[2009 c 549 § 5115]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c64.pdf?cite=1973%20c%2064%20§%2012[1973 c 64 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.37.150[1965 c 8 § 43.37.150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c245.pdf?cite=1957%20c%20245%20§%2015[1957 c 245 § 15]; ]

== 70A.10.140 - Fees—Sanctions for failure to pay.
The fee to be paid by each applicant for a permit shall be equivalent to one and one-half percent of the estimated cost of such operation, the estimated cost to be computed by the department from the evidence available to it. The fee is due and payable to the department as of the date of the issuance of the permit; however, if the applicant is able to give to the department satisfactory security for the payment of the balance, he or she may be permitted to commence the operation, and a permit may be issued therefor, upon the payment of not less than fifty percent of the fee. The balance due shall be paid within three months from the date of the termination of the operation as prescribed in the permit. Failure to pay a permit fee as required shall be grounds for suspension or revocation of the license of the delinquent permit holder and grounds for refusal to renew his or her license or to issue any further permits to such person.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%205116[2009 c 549 § 5116]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c64.pdf?cite=1973%20c%2064%20§%2013[1973 c 64 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.37.160[1965 c 8 § 43.37.160]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c245.pdf?cite=1957%20c%20245%20§%2016[1957 c 245 § 16]; ]

== 70A.10.150 - Records and reports—Open to public examination.
. Every licensee shall keep and maintain a record of all operations conducted by him or her pursuant to his or her license and each permit, showing the method employed, the type of equipment used, materials and amounts thereof used, the times and places of operation of the equipment, the name and post office address of each individual participating or assisting in the operation other than the licensee, and such other general information as may be required by the department and shall report the same to the department at the time and in the manner required.

. The department shall require written reports in such manner as it provides but not inconsistent with the provisions of this chapter, covering each operation for which a permit is issued. Further, the department shall require written reports from such organizations as are exempted from license, permit, and liability requirements as provided in RCW 70A.10.070.

. The reports and records in the custody of the department shall be open for public examination.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201048[2020 c 20 § 1048]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%205117[2009 c 549 § 5117]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c64.pdf?cite=1973%20c%2064%20§%2014[1973 c 64 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.37.170[1965 c 8 § 43.37.170]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c245.pdf?cite=1957%20c%20245%20§%2017[1957 c 245 § 17]; ]

== 70A.10.160 - Revocation, suspension, modification of license or permit.
. The department may suspend or revoke any license or permit issued if it appears that the licensee no longer possesses the qualifications necessary for the issuance of a new license or permit. The department may suspend or revoke any license or permit if it appears that the licensee has violated any of the provisions of this chapter. Such suspension or revocation shall occur only after notice to the licensee and a reasonable opportunity granted such licensee to be heard respecting the grounds of the proposed suspension or revocation. The department may refuse to renew the license of, or to issue another permit to, any applicant who has failed to comply with any provision of this chapter.

. The department may modify the terms of a permit after issuance thereof if the licensee is first given notice and a reasonable opportunity for a hearing respecting the grounds for the proposed modification and if it appears to the department that it is necessary for the protection of the health or the property of any person to make the modification proposed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c64.pdf?cite=1973%20c%2064%20§%2015[1973 c 64 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.37.180[1965 c 8 § 43.37.180]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c245.pdf?cite=1957%20c%20245%20§%2018[1957 c 245 § 18]; ]

== 70A.10.170 - Liability of state denied—Legal rights of private persons not affected.
Nothing in this chapter shall be construed to impose or accept any liability or responsibility on the part of the state, the department, or any state officials or employees for any weather modification and control activities of any private person or group, nor to affect in any way any contractual, tortious, or other legal rights, duties, or liabilities between any private persons or groups.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c64.pdf?cite=1973%20c%2064%20§%2016[1973 c 64 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.37.190[1965 c 8 § 43.37.190]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c245.pdf?cite=1957%20c%20245%20§%2019[1957 c 245 § 19]; ]

== 70A.10.180 - Penalty.
Any person violating any of the provisions of this chapter or any lawful regulation or order issued pursuant thereto, shall be guilty of a misdemeanor; and a continuing violation is punishable as a separate offense for each day during which it occurs.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c8.pdf?cite=1965%20c%208%20§%2043.37.200[1965 c 8 § 43.37.200]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c245.pdf?cite=1957%20c%20245%20§%2020[1957 c 245 § 20]; ]

== 70A.10.190 - Legislative declaration.
The legislature finds and declares that when prolonged lack of precipitation or shortages of water supply in the state cause severe hardships affecting the health, safety, and welfare of the people of the state, a program to increase precipitation is occasionally needed for the generation of hydroelectric power, for domestic purposes, and to alleviate hardships created by the threat of forest fires and shortages of water for agriculture. Cloud seeding has been demonstrated to be such a program of weather modification with increasing scientific certainty.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c278.pdf?cite=1981%20c%20278%20§%201[1981 c 278 § 1]; ]

== 70A.10.200 - Program of emergency cloud seeding authorized.
The director of ecology may establish by rule under chapter 34.05 RCW a program of emergency cloud seeding. The director may include in these rules standards and guidelines for determining the situations which warrant cloud seeding and the means to be used for cloud seeding.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c278.pdf?cite=1981%20c%20278%20§%202[1981 c 278 § 2]; ]

== 70A.10.210 - Exemption of licensee from certain requirements.
Upon a proclamation of a state of emergency, related to a lack of precipitation or a shortage of water supply, by the governor under RCW 43.06.210, the department shall exempt a licensee from the requirements of RCW 70A.10.090 (2) and (6) and 70A.10.120.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201049[2020 c 20 § 1049]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c278.pdf?cite=1981%20c%20278%20§%203[1981 c 278 § 3]; ]

== 70A.10.900 - Effective date—1973 c 64.
The effective date of this 1973 amendatory act shall be July 1, 1973.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c64.pdf?cite=1973%20c%2064%20§%2018[1973 c 64 § 18]; ]

