= 70A.130 - Chemical contaminants and water quality.
:toc:

== 70A.130.010 - Establishment of standards for chemical contaminants in drinking water by state board of health.
. In order to protect public health from chemical contaminants in drinking water, the state board of health shall conduct public hearings and, where technical data allow, establish by rule standards for allowable concentrations. For purposes of this chapter, the words "chemical contaminants" are limited to synthetic organic chemical contaminants and to any other contaminants which in the opinion of the board constitute a threat to public health. If adequate data to support setting of a standard is available, the state board of health shall adopt by rule a maximum contaminant level for water provided to consumers' taps. Standards set for contaminants known to be toxic shall consider both short-term and chronic toxicity. Standards set for contaminants known to be carcinogenic shall be consistent with risk levels established by the state board of health.

. The board shall consider the best available scientific information in establishing the standards. The board may review and revise the standards. State and local standards for chemical contaminants may be more strict than the federal standards.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c187.pdf?cite=1984%20c%20187%20§%201[1984 c 187 § 1]; ]

== 70A.130.020 - Establishment of monitoring requirements for chemical contaminants in public water supplies by state board of health.
The state board of health shall conduct public hearings and establish by rule monitoring requirements for chemical contaminants in public water supplies. Results of tests conducted pursuant to such requirements shall be submitted to the department of health and to the local health department. The state board of health may review and revise monitoring requirements for chemical contaminants.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20374[1991 c 3 § 374]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c187.pdf?cite=1984%20c%20187%20§%202[1984 c 187 § 2]; ]

== 70A.130.030 - Monitoring requirements—Considerations.
The state board of health in determining monitoring requirements for public water supply systems shall take into consideration economic impacts as well as public health risks.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c187.pdf?cite=1984%20c%20187%20§%205[1984 c 187 § 5]; ]

== 70A.130.040 - Establishment of water quality standards by local health department in large counties.
Each local health department serving a county with a population of one hundred twenty-five thousand or more may establish water quality standards for its jurisdiction more stringent than standards established by the state board of health. Each local health department establishing such standards shall base the standards on the best available scientific information.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1201-S.SL.pdf?cite=1991%20c%20363%20§%20145[1991 c 363 § 145]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c187.pdf?cite=1984%20c%20187%20§%203[1984 c 187 § 3]; ]

== 70A.130.050 - Noncomplying public water supply systems—Submission of corrective plan—Notification to system's customers.
Public water supply systems as defined by RCW 70A.120.020 that the state board of health or local health department determines do not comply with the water quality standards applicable to the system shall immediately initiate preparation of a corrective plan designed to meet or exceed the minimum standards for submission to the department of health. The owner of such system shall within one year take any action required to bring the water into full compliance with the standards. The department of health may require compliance as promptly as necessary to abate an immediate public health threat or may extend the period of compliance if substantial new construction is required: PROVIDED FURTHER, That the extension shall be granted only upon a determination by the department, after a public hearing, that the extension will not pose an imminent threat to public health. Each such system shall include a notice identifying the water quality standards exceeded, and the amount by which the water tested exceeded the standards, in all customer bills mailed after such determination. The notification shall continue until water quality tests conducted in accordance with this chapter establish that the system meets or exceeds the minimum standards.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201377[2020 c 20 § 1377]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=1991%20c%203%20§%20375[1991 c 3 § 375]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c187.pdf?cite=1984%20c%20187%20§%204[1984 c 187 § 4]; ]

