= 70A.20 - Noise control.
:toc:

== 70A.20.010 - Purpose.
The legislature finds that inadequately controlled noise adversely affects the health, safety and welfare of the people, the value of property, and the quality of the environment. Antinoise measures of the past have not adequately protected against the invasion of these interests by noise. There is a need, therefore, for an expansion of efforts statewide directed toward the abatement and control of noise, considering the social and economic impact upon the community and the state. The purpose of this chapter is to provide authority for such an expansion of efforts, supplementing existing programs in the field.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c183.pdf?cite=1974%20ex.s.%20c%20183%20§%201[1974 ex.s. c 183 § 1]; ]

== 70A.20.020 - Definitions.
As used in this chapter, unless the context clearly indicates otherwise:

. "Department" means the department of ecology.

. "Director" means director of the department of ecology.

. "Local government" means county or city government or any combination of the two.

. "Noise" means the intensity, duration and character of sounds from any and all sources.

. "Person" means any individual, corporation, partnership, association, governmental body, state, or other entity whatsoever.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c183.pdf?cite=1974%20ex.s.%20c%20183%20§%202[1974 ex.s. c 183 § 2]; ]

== 70A.20.030 - Powers and duties of department.
The department is empowered as follows:

. The department, after consultation with state agencies expressing an interest therein, shall adopt, by rule, maximum noise levels permissible in identified environments in order to protect against adverse affects of noise on the health, safety and welfare of the people, the value of property, and the quality of environment: PROVIDED, That in so doing the department shall take also into account the economic and practical benefits to be derived from the use of various products in each such environment, whether the source of the noise or the use of such products in each environment is permanent or temporary in nature, and the state of technology relative to the control of noise generated by all such sources of the noise or the products.

. At any time after the adoption of maximum noise levels under subsection (1) of this section the department shall, in consultation with state agencies and local governments expressing an interest therein, adopt rules, consistent with the Federal Noise Control Act of 1972 (86 Stat. 1234; 42 U.S.C. Sec. 4901-4918 and 49 U.S.C. Sec. 1431), for noise abatement and control in the state designed to achieve compliance with the noise level adopted in subsection (1) of this section, including reasonable implementation schedules where appropriate, to insure that the maximum noise levels are not exceeded and that application of the best practicable noise control technology and practice is provided. These rules may include, but shall not be limited to:

.. Performance standards setting allowable noise limits for the operation of products which produce noise;

.. Use standards regulating, as to time and place, the operation of individual products which produce noise above specified levels considering frequency spectrum and duration: PROVIDED, The rules shall provide for temporarily exceeding those standards for stated purposes; and

.. Public information requirements dealing with disclosure of levels and characteristics of noise produced by products.

. The department may, as desirable in the performance of its duties under this chapter, conduct surveys, studies and public education programs, and enter into contracts.

. The department is authorized to apply for and accept moneys from the federal government and other sources to assist in the implementation of this chapter.

. The legislature recognizes that the operation of motor vehicles on public highways as defined in RCW 46.09.310 contributes significantly to environmental noise levels and directs the department, in exercising the rule-making authority under the provisions of this section, to give first priority to the adoption of motor vehicle noise performance standards.

. Noise levels and rules adopted by the department pursuant to this chapter shall not be effective prior to March 31, 1975.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%20107[2011 c 171 § 107]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c183.pdf?cite=1974%20ex.s.%20c%20183%20§%203[1974 ex.s. c 183 § 3]; ]

== 70A.20.040 - Technical advisory committee.
The director shall name a technical advisory committee to assist the department in the implementation of this chapter. Committee members shall be entitled to reimbursement for travel expenses as provided in RCW 43.03.050 and 43.03.060, as now existing or hereafter amended.

[ 1975-'76 2nd ex.s. c 34 § 164; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c183.pdf?cite=1974%20ex.s.%20c%20183%20§%204[1974 ex.s. c 183 § 4]; ]

== 70A.20.050 - Civil penalties.
. Any person who violates any rule adopted by the department under this chapter shall be subject to a civil penalty not to exceed one hundred dollars imposed by local government pursuant to this section. An action under this section shall not preclude enforcement of any provisions of the local government noise ordinance.

Penalties shall become due and payable thirty days from the date of receipt of a notice of penalty unless within such time said notice is appealed in accordance with the administrative procedures of the local government, or if it has no such administrative appeal, to the pollution control hearings board pursuant to the provisions of chapter 43.21B RCW and procedural rules adopted thereunder. In cases in which appeals are timely filed, penalties sustained by the local administrative agency or the pollution control hearings board shall become due and payable on the issuance of said agency or board's final order in the appeal.

. Whenever penalties incurred pursuant to this section have become due and payable but remain unpaid, the attorney for the local government may bring an action in the superior court of the county in which the violation occurred for recovery of penalties incurred. In all such actions the procedures and rules of evidence shall be the same as in any other civil action.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c103.pdf?cite=1987%20c%20103%20§%202[1987 c 103 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c183.pdf?cite=1974%20ex.s.%20c%20183%20§%205[1974 ex.s. c 183 § 5]; ]

== 70A.20.060 - Other rights, remedies, powers, duties and functions—Local regulation—Approval—Procedure.
. Nothing in this chapter shall be construed to deny, abridge or alter alternative rights of action or remedies in equity or under common law or statutory law, criminal or civil.

. Nothing in this chapter shall deny, abridge or alter any powers, duties and functions relating to noise abatement and control now or hereafter vested in any state agency, nor shall this chapter be construed as granting jurisdiction over the industrial safety and health of employees in workplaces of the state, as now or hereafter vested in the department of labor and industries.

. Standards and other control measures adopted by the department under this chapter shall be exclusive except as hereinafter provided. A local government may impose limits or control sources differing from those adopted or controlled by the department upon a finding that such requirements are necessitated by special conditions. Noise limiting requirements of local government which differ from those adopted or controlled by the department shall be invalid unless first approved by the department. If the department of ecology fails to approve or disapprove standards submitted by local governmental jurisdictions within ninety days of submittal, such standards shall be deemed approved. If disapproved, the local government may appeal the decision to the pollution control hearings board which shall decide the appeal on the basis of the provisions of this chapter, and the applicable regulations, together with such briefs, testimony, and oral argument as the hearings board in its discretion may require. The department determination of whether to grant approval shall depend on the reasonableness and practicability of compliance. Particular attention shall be given to stationary sources located near jurisdictional boundaries, and temporary noise producing operations which may operate across one or more jurisdictional boundaries.

. In carrying out the rule-making authority provided in this chapter, the department shall follow the procedures of the administrative procedure act, chapter 34.05 RCW, and shall take care that no rules adopted purport to exercise any powers preempted by the United States under federal law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c103.pdf?cite=1987%20c%20103%20§%201[1987 c 103 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c183.pdf?cite=1974%20ex.s.%20c%20183%20§%206[1974 ex.s. c 183 § 6]; ]

== 70A.20.070 - Rules relating to motor vehicles—Violations—Penalty.
Any rule adopted under this chapter relating to the operation of motor vehicles on public highways shall be administered according to testing and inspection procedures adopted by rule by the state patrol. Violation of any motor vehicle performance standard adopted pursuant to this chapter shall be a misdemeanor, enforced by such authorities and in such manner as violations of chapter 46.37 RCW. Violations subject to the provisions of this section shall be exempt from the provisions of RCW 70A.20.050.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201326[2020 c 20 § 1326]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c330.pdf?cite=1987%20c%20330%20§%20749[1987 c 330 § 749]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c183.pdf?cite=1974%20ex.s.%20c%20183%20§%207[1974 ex.s. c 183 § 7]; ]

== 70A.20.080 - Exemptions.
The department shall, in the exercise of rule-making power under this chapter, provide exemptions or specially limited regulations relating to recreational shooting and emergency or law enforcement equipment where appropriate in the interests of public safety.

The department in the development of rules under this chapter, shall consult and take into consideration the land use policies and programs of local government.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c183.pdf?cite=1974%20ex.s.%20c%20183%20§%208[1974 ex.s. c 183 § 8]; ]

== 70A.20.900 - Construction—Severability—1974 ex.s. c 183.
. This chapter shall be liberally construed to carry out its broad purposes.

. If any provision of this chapter, or its application to any person or circumstance is held invalid, the remainder of the chapter, or the application of the provision to other persons or circumstances is not affected.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c183.pdf?cite=1974%20ex.s.%20c%20183%20§%2011[1974 ex.s. c 183 § 11]; ]

== 70A.20.901 - Short title.
This chapter shall be known and may be cited as the "Noise Control Act of 1974".

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c183.pdf?cite=1974%20ex.s.%20c%20183%20§%2012[1974 ex.s. c 183 § 12]; ]

