= 70A.386 - High-level nuclear waste repository siting.
:toc:

== 70A.386.010 - Findings.
The legislature and the people of the state of Washington find that:

. In order to solve the problem of high-level radioactive waste disposal, congress established a process for selecting two sites for the safe, permanent, and regionally equitable disposal of such waste.

. The process of selecting three sites as final candidates, including the Hanford reservation, for a first high-level nuclear waste repository by the United States department of energy violated the intent and the mandate of congress.

. The United States department of energy has prematurely deferred consideration of numerous potential sites and disposal media that its own research indicates are more appropriate, safer, and less expensive.

. Placement of a repository at Hanford without methodical and independently verified scientific evaluation will pose a threat to the health and safety of the people and the environment of this state.

. The selection process is flawed and not credible because it did not include independent experts in the selection of the sites and in the review of that selection, as recommended by the National Academy of Sciences.

. By postponing indefinitely all site specific work for a second repository, the United States department of energy has not complied with the intent of congress expressed in the Nuclear Waste Policy Act, Public Law 97-425, and the fundamental compromise which enabled its enactment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986ex1c1.pdf?cite=1986%20ex.s.%20c%201%20ยง%201[1986 ex.s. c 1 ยง 1]; ]

== 70A.386.020 - Duties relating to the site selection process for a high-level nuclear waste repository.
In order to achieve complete compliance with federal law and protect the health, safety, and welfare of the people of the state of Washington, the governor, the legislature, other statewide elected officials, and the nuclear waste board shall use all legal means necessary to:

. Suspend the preliminary site selection process for a high-level nuclear waste repository, including the process of site characterization, until there is compliance with the intent of the Nuclear Waste Policy Act;

. Reverse the secretary of energy's decision to postpone indefinitely all site specific work on locating and developing a second repository for high-level nuclear waste;

. Insist that the United States department of energy's site selection process, when resumed, considers all acceptable geologic media and results in safe, scientifically justified, and regionally and geographically equitable high-level nuclear waste disposal;

. Demand that federal budget actions fully and completely follow the intent of the Nuclear Waste Policy Act; and

. Continue to pursue alliances with other states and interested parties, particularly with Pacific Northwest governors, legislatures, and other parties, affected by the site selection and transportation of high-level nuclear waste.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986ex1c1.pdf?cite=1986%20ex.s.%20c%201%20ยง%202[1986 ex.s. c 1 ยง 2]; ]

