= 70A.235 - Beverage containers.
:toc:

== 70A.235.010 - Legislative findings.
The legislature finds that beverage containers designed to be opened through the use of detachable metal rings or tabs are hazardous to the health and welfare of the citizens of this state and detrimental to certain wildlife. The detachable parts are susceptible to ingestion by human beings and wildlife. The legislature intends to eliminate the danger posed by these unnecessary containers by prohibiting their retail sale in this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c113.pdf?cite=1982%20c%20113%20§%201[1982 c 113 § 1]; ]

== 70A.235.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter:

. "Beverage" means beer or other malt beverage or mineral water, soda water, or other drink in liquid form and intended for human consumption. The term does not include milk-based, soy-based, or similar products requiring heat and pressure in the canning process.

. "Beverage container" means a separate and sealed can containing a beverage.

. "Department" means the department of ecology created under chapter 43.21A RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c257.pdf?cite=1983%20c%20257%20§%201[1983 c 257 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c113.pdf?cite=1982%20c%20113%20§%202[1982 c 113 § 2]; ]

== 70A.235.030 - Sale of containers with detachable metal rings or tabs prohibited.
No person may sell or offer to sell at retail in this state any beverage container so designed and constructed that a metal part of the container is detachable in opening the container through use of a metal ring or tab. Nothing in this section prohibits the sale of a beverage container which container's only detachable part is a piece of pressure sensitive or metallic tape.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c113.pdf?cite=1982%20c%20113%20§%203[1982 c 113 § 3]; ]

== 70A.235.040 - Enforcement—Rules.
The department shall administer and enforce this chapter. The department shall adopt rules interpreting and implementing this chapter. Any rule adopted under this section shall be adopted under the administrative procedure act, chapter 34.05 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c113.pdf?cite=1982%20c%20113%20§%204[1982 c 113 § 4]; ]

== 70A.235.050 - Penalty.
Except as provided in RCW 43.05.060 through 43.05.080 and 43.05.150, any person who violates any provision of this chapter or any rule adopted under this chapter is subject to a civil penalty not exceeding five hundred dollars for each violation. Each day of a continuing violation is a separate violation.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1010-S.SL.pdf?cite=1995%20c%20403%20§%20632[1995 c 403 § 632]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c113.pdf?cite=1982%20c%20113%20§%205[1982 c 113 § 5]; ]

== 70A.235.900 - Effective date—Implementation—1982 c 113.
This act shall take effect on July 1, 1983. The director of the department of ecology is authorized to take such steps prior to such date as are necessary to ensure that this act is implemented on its effective date.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c113.pdf?cite=1982%20c%20113%20§%207[1982 c 113 § 7]; ]

