= 70A.216 - Solid waste incinerator and landfill operators.
:toc:

== 70A.216.010 - Definitions.
Unless the context clearly requires otherwise the definitions in this section apply throughout this chapter.

. "Certificate" means a certificate of competency issued by the director stating that the operator has met the requirements for the specified operator classification of the certification program.

. "Department" means the department of ecology.

. "Director" means the director of ecology.

. "Incinerator" means a facility which has the primary purpose of burning or which is designed with the primary purpose of burning solid waste or solid waste derived fuel, but excludes facilities that have the primary purpose of burning hog fuel.

. "Landfill" means a landfill as defined under RCW 70A.205.015.

. "Owner" means, in the case of a town or city, the city or town acting through its chief executive officer or the lessee if operated pursuant to a lease or contract; in the case of a county, the chief elected official of the county legislative authority or the chief elected official's designee; in the case of a board of public utilities, association, municipality, or other public body, the president or chief elected official of the body or the president's or chief elected official's designee; in the case of a privately owned landfill or incinerator, the legal owner.

. "Solid waste" means solid waste as defined under RCW 70A.205.015.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201220[2020 c 20 § 1220]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1107-S.SL.pdf?cite=1995%20c%20269%20§%202801[1995 c 269 § 2801]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2065[1989 c 431 § 65]; ]

== 70A.216.020 - Incineration facilities—Owner and operator certification requirements.
. By January 1, 1992, the owner or operator of a solid waste incineration facility shall employ a certified operator. At a minimum, the individual on-site at a solid waste incineration facility who is designated by the owner as the operator in responsible charge of the operation and maintenance of the facility on a routine basis shall be certified by the department.

. If a solid waste incinerator is operated on more than one daily shift, the operator in charge of each shift shall be certified.

. Operators not required to be certified are encouraged to become certified on a voluntary basis.

. The department shall adopt and enforce such rules as may be necessary for the administration of this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2066[1989 c 431 § 66]; ]

== 70A.216.030 - Landfills—Owner and operator certification requirements.
. By January 1, 1992, the owner or operator of a landfill shall employ a certified landfill operator.

. For each of the following types of landfills defined in existing regulations: Inert, demolition waste, problem waste, and municipal solid waste, the department shall adopt rules classifying all landfills in each class. The factors to be considered in the classification shall include, but not be limited to, the type and amount of waste in place and projected to be disposed of at the site, whether the landfill currently meets state and federal operating criteria, the location of the landfill, and such other factors as may be determined to affect the skill, knowledge, and experience required of an operator to operate the landfill in a manner protective of human health and the environment.

. The rules shall identify the landfills in each class in which the owner or operator will be required to employ a certified landfill operator who is on-site at all times the landfill is operating. At a minimum, the rule shall require that owners and operators of landfills are required to employ a certified landfill operator who is on call at all times the landfill is operating.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2067[1989 c 431 § 67]; ]

== 70A.216.040 - Certification process—Suspension of license or certificate for noncompliance with support order.
. The department shall establish a process to certify incinerator and landfill operators. To the greatest extent possible, the department shall rely on the certification standards and procedures developed by national organizations and the federal government.

. Operators shall be certified if they:

.. Attend the required training sessions;

.. Successfully complete required examinations; and

.. Pay the prescribed fee.

. By January 1, 1991, the department shall adopt rules to require incinerator and appropriate landfill operators to:

.. Attend a training session concerning the operation of the relevant type of landfill or incinerator;

.. Demonstrate sufficient skill and competency for proper operation of the incinerator or landfill by successfully completing an examination prepared by the department; and

.. Renew the certificate of competency at reasonable intervals established by the department.

. The department shall provide for the collection of fees for the issuance and renewal of certificates. These fees shall be sufficient to recover the costs of the certification program.

. The department shall establish an appeals process for the denial or revocation of a certificate.

. The department shall establish a process to automatically certify operators who have received comparable certification from another state, the federal government, a local government, or a professional association.

. Upon July 23, 1989, and prior to January 1, 1992, the owner or operator of an incinerator or landfill may apply to the department for interim certification. Operators shall receive interim certification if they:

.. Have received training provided by a recognized national organization, educational institution, or the federal government that is acceptable to the department; or

.. Have received individualized training in a manner approved by the department; and

.. Have successfully completed any required examinations.

. No interim certification shall be valid after January 1, 1992, and interim certification shall not automatically qualify operators for certification pursuant to subsections (2) through (4) of this section.

. The department shall immediately suspend the license or certificate of a person who has been certified pursuant to RCW 74.20A.320 by the department of social and health services as a person who is not in compliance with a support order or a *residential or visitation order. If the person has continued to meet all other requirements for reinstatement during the suspension, reissuance of the license or certificate shall be automatic upon the department's receipt of a release issued by the department of social and health services stating that the licensee is in compliance with the order.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20875[1997 c 58 § 875]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2068[1989 c 431 § 68]; ]

== 70A.216.050 - Ad hoc advisory committees.
The director may establish ad hoc advisory committees, as necessary, to obtain advice and technical assistance on the certification of solid waste incinerator and landfill operators.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1107-S.SL.pdf?cite=1995%20c%20269%20§%202804[1995 c 269 § 2804]; ]

== 70A.216.060 - Revocation of certification.
. The director may revoke a certificate:

.. If it were found to have been obtained by fraud or deceit;

.. For gross negligence in the operation of a solid waste incinerator or landfill;

.. For violating the requirements of this chapter or any lawful rule or order of the department; or

.. If the facility operated by the certified employee is operated in violation of state or federal environmental laws.

. A person whose certificate is revoked under this section shall not be eligible to apply for a certificate for one year from the effective date of the final order of revocation.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1107-S.SL.pdf?cite=1995%20c%20269%20§%202802[1995 c 269 § 2802]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2070[1989 c 431 § 70]; ]

== 70A.216.070 - Certification of inspectors.
Any person who is employed by a public agency to inspect the operation of a landfill or a solid waste incinerator to determine the compliance of the facility with state or local laws or rules shall be required to be certified in the same manner as an operator under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2071[1989 c 431 § 71]; ]

== 70A.216.080 - Authority of director.
To carry out the provisions and purposes of this chapter, the director may:

. Enter into agreements, contracts, or cooperative arrangements, under such terms and conditions as the director deems appropriate, with other state, federal, or interstate agencies, municipalities, educational institutions, or other organizations or individuals.

. Receive financial and technical assistance from the federal government, other public agencies, and private agencies.

. Participate in related programs of the federal government, other states, interstate agencies, other public agencies, or private agencies or organizations.

. Upon request, furnish reports, information, and materials relating to the certification program authorized by this chapter to federal, state, or interstate agencies, municipalities, educational institutions, and other organizations and individuals.

. Establish adequate fiscal controls and accounting procedures to assure proper disbursement of and accounting for funds appropriated or otherwise provided for the purpose of carrying out this chapter.

. Adopt rules under chapter 34.05 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2072[1989 c 431 § 72]; ]

== 70A.216.090 - Unlawful acts—Variance from requirements.
After January 1, 1992, it is unlawful for any person, firm, corporation, municipal corporation, or other governmental subdivision or agency to operate a solid waste incineration or landfill facility unless the operators are duly certified by the director under this chapter or any lawful rule or order of the department. It is unlawful for any person to perform the duties of an operator without being duly certified under this chapter. The department shall adopt rules that allow the owner or operator of a landfill or solid waste incineration facility to request a variance from this requirement under emergency conditions. The department may impose such conditions as may be necessary to protect human health and the environment during the term of the variance.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2073[1989 c 431 § 73]; ]

== 70A.216.100 - Penalties.
. Any person, including any firm, corporation, municipal corporation, or other governmental subdivision or agency, with the exception of incinerator operators, violating any provision of this chapter or the rules adopted under this chapter, is guilty of a misdemeanor.

. Any incinerator operator who violates any provision of this chapter is guilty of a gross misdemeanor.

. Each day of operation in violation of this chapter or any rules adopted under this chapter shall constitute a separate offense.

. The prosecuting attorney or the attorney general, as appropriate, shall secure injunctions of continuing violations of any provisions of this chapter or the rules adopted under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20356[2003 c 53 § 356]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2074[1989 c 431 § 74]; ]

== 70A.216.110 - Deposit of receipts.
All receipts realized in the administration of this chapter shall be paid into the general fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2075[1989 c 431 § 75]; ]

