= 70A.355 - Underground storage tanks.
:toc:

== 70A.355.005 - Findings—Intent.
The legislature finds that leaking underground storage tanks containing petroleum and other regulated substances pose a serious threat to human health and the environment. To address this threat, the legislature intends for the department of ecology to establish an underground storage tank program designed, operated, and enforced in a manner that, at a minimum, meets the requirements for delegation of the federal underground storage tank program of the resource conservation and recovery act of 1976, as amended (42 U.S.C. Sec. 6901, et seq.). The legislature intends that statewide requirements for underground storage tanks adopted by the department be consistent with and no less stringent than the requirements in the federal regulations and the underground storage tank compliance act of 2005 (42 U.S.C. Sec. 15801 et seq., energy policy act of 2005, P.L. 109-58, Title XV, subtitle B).

The legislature further finds that certain areas of the state possess physical characteristics that make them especially vulnerable to threats from leaking underground storage tanks and that in these environmentally sensitive areas, local requirements more stringent than the statewide requirements may apply.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5475-S.SL.pdf?cite=2007%20c%20147%20§%201[2007 c 147 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c346.pdf?cite=1989%20c%20346%20§%201[1989 c 346 § 1]; ]

== 70A.355.010 - Definitions.
. The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

.. "Department" means the department of ecology.

.. "Director" means the director of the department.

.. "Facility compliance tag" means a marker, constructed of metal, plastic, or other durable material, that clearly identifies all qualifying underground storage tanks on the particular site for which it is issued.

.. "Federal act" means the federal resource conservation and recovery act, as amended (42 U.S.C. Sec. 6901, et seq.).

.. "Federal regulations" means the underground storage tanks regulations (40 C.F.R. Secs. 280 and 281) adopted by the United States environmental protection agency under the federal act.

.. "License" means the business license underground storage tank endorsement issued by the department of revenue under chapter 19.02 RCW.

.. "Underground storage tank compliance act of 2005" means Title XV and subtitle B of P.L. 109-58 (42 U.S.C. Sec. 15801 et seq.) which have amended the federal resource conservation and recovery act's subtitle I.

.. "Underground storage tank system" means an underground storage tank, connected underground piping, underground ancillary equipment, and containment system, if any.

. Except as provided in this section and any rules adopted by the department under this chapter, the definitions contained in the federal regulations apply to the terms in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1568-S.SL.pdf?cite=2013%20c%20144%20§%2053[2013 c 144 § 53]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2017-S.SL.pdf?cite=2011%20c%20298%20§%2039[2011 c 298 § 39]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5475-S.SL.pdf?cite=2007%20c%20147%20§%202[2007 c 147 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6130-S.SL.pdf?cite=1998%20c%20155%20§%201[1998 c 155 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c346.pdf?cite=1989%20c%20346%20§%202[1989 c 346 § 2]; ]

== 70A.355.020 - Department's powers and duties—Rule-making authority.
. The department must adopt rules establishing requirements for all underground storage tanks that are regulated under the federal act, taking into account the various classes or categories of tanks to be regulated. The rules must be consistent with and no less stringent than the federal regulations and the underground storage tank compliance act of 2005 and consist of requirements for the following:

.. New underground storage tank system design, construction, installation, and notification;

.. Upgrading existing underground storage tank systems;

.. General operating requirements;

.. Release detection;

.. Release reporting;

.. Out-of-service underground storage tank systems and closure;

.. Financial responsibility for underground storage tanks containing regulated substances; and

.. Groundwater protection measures, including secondary containment and monitoring for installation or replacement of all underground storage tank systems or components, such as tanks and piping, installed after July 1, 2007, and under dispenser spill containment for installation or replacement of all dispenser systems installed after July 1, 2007.

. The department must adopt rules:

.. Establishing physical site criteria to be used in designating local environmentally sensitive areas;

.. Establishing procedures for local government application for this designation; and

.. Establishing procedures for local government adoption and department approval of rules more stringent than the statewide standards in these designated areas.

. The department must establish by rule an administrative and enforcement program that is consistent with and no less stringent than the program required under the federal regulations in the areas of:

.. Compliance monitoring, including procedures for recordkeeping and a program for systematic inspections;

.. Enforcement;

.. Public participation;

.. Information sharing;

.. Owner and operator training; and

.. Delivery prohibition for underground storage tank systems or facilities that are determined by the department to be ineligible to receive regulated substances.

. The department must establish a program that provides for the annual licensing of underground storage tanks. The license must take the form of a tank endorsement on the facility's annual business license issued by the department of revenue under chapter 19.02 RCW. A tank is not eligible for a license unless the owner or operator can demonstrate compliance with the requirements of this chapter and the annual tank fees have been remitted. The department may revoke a tank license if a facility is not in compliance with this chapter, or any rules adopted under this chapter. The business license must be displayed by the tank owner or operator in a location clearly identifiable.

. [Empty]
.. The department must issue a one-time "facility compliance tag" to underground storage tank facilities that have installed the equipment required to meet corrosion protection, spill prevention, overfill prevention, leak detection standards, have demonstrated financial responsibility, and have paid annual tank fees. The facility must continue to maintain compliance with corrosion protection, spill prevention, overfill prevention, and leak detection standards, financial responsibility, and have remitted annual tank fees to display a facility compliance tag. The facility compliance tag must be displayed on or near the fire emergency shutoff device, or in the absence of such a device in close proximity to the fill pipes and clearly identifiable to persons delivering regulated substance to underground storage tanks.

.. The department may revoke a facility compliance tag if a facility is not in compliance with the requirements of this chapter, or any rules adopted under this chapter.

. The department may place a red tag on a tank at a facility if the department determines that the owner or operator is not in compliance with this chapter or the rules adopted under this chapter regarding the compliance requirements related to that tank. Removal of a red tag without authorization from the department is a violation of this chapter.

. The department may establish programs to certify persons who install or decommission underground storage tank systems or conduct inspections, testing, closure, cathodic protection, interior tank lining, corrective action, site assessments, or other activities required under this chapter. Certification programs must be designed to ensure that each certification will be effective in all jurisdictions of the state.

. When adopting rules under this chapter, the department must consult with the state building code council to ensure coordination with the building and fire codes adopted under chapter 19.27 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1568-S.SL.pdf?cite=2013%20c%20144%20§%2054[2013 c 144 § 54]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2017-S.SL.pdf?cite=2011%20c%20298%20§%2040[2011 c 298 § 40]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5475-S.SL.pdf?cite=2007%20c%20147%20§%203[2007 c 147 § 3]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6130-S.SL.pdf?cite=1998%20c%20155%20§%202[1998 c 155 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c346.pdf?cite=1989%20c%20346%20§%203[1989 c 346 § 3]; ]

== 70A.355.030 - Environmentally sensitive areas.
. A city, town, or county may apply to the department to have an area within its jurisdictional boundaries designated an environmentally sensitive area. A city, town, or county may submit a joint application with any other city, town, or county for joint administration under chapter 39.34 RCW of a single environmentally sensitive area located in both jurisdictions.

. A city, town, or county may adopt proposed ordinances or resolutions establishing requirements for underground storage tanks located within an environmentally sensitive area that are more stringent than the statewide standards established under RCW 70A.355.020. Proposed local ordinances and resolutions shall only apply to new underground storage tank installations. The local government adopting the ordinances and resolutions shall submit them to the department for approval. Disapproved ordinances and resolutions may be modified and resubmitted to the department for approval. Proposed local ordinances and resolutions become effective when approved by the department.

. The department shall approve or disapprove each proposed local ordinance or resolution based on the following criteria:

.. The area to be regulated is found to be an environmentally sensitive area based on rules adopted by the department; and

.. The proposed local regulations are reasonably consistent with previously approved local regulations for similar environmentally sensitive areas.

. A city, town, or county for which a proposed local ordinance or resolution establishing more stringent requirements is approved by the department may establish local tank fees that meet the requirements of RCW 70A.355.080, if such fees are necessary for enhanced program administration or enforcement.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201510[2020 c 20 § 1510]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6130-S.SL.pdf?cite=1998%20c%20155%20§%203[1998 c 155 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c346.pdf?cite=1989%20c%20346%20§%205[1989 c 346 § 5]; ]

== 70A.355.040 - Delivery of regulated substances.
. A person delivering regulated substances to underground storage tanks shall not deliver or deposit regulated substances to underground storage tanks or facilities that do not have a facility compliance tag displayed as required in RCW 70A.355.020(5)(a). Additionally, a person delivering regulated substances to underground storage tanks shall not deliver or deposit regulated substances to an individual underground storage tank on which the department has placed a red tag under RCW 70A.355.020(6).

. An owner or operator of an underground storage tank system or facility shall not accept delivery or deposit of regulated substances to that underground storage tank system or facility, if the system does not have a facility compliance tag displayed as required in RCW 70A.355.020(5)(a). Additionally, an owner or operator of an underground storage tank system or facility shall not accept delivery or deposit of regulated substances to an individual underground storage tank on which the department has placed a red tag under RCW 70A.355.020(6).

. A supplier shall not refuse to deliver regulated substances to an underground storage tank regulated under this chapter on the basis of its potential to leak contents where the facility displays a valid facility compliance tag as required in this chapter, and the department has not placed a red tag on the underground storage tank. This section does not apply to a supplier who does not directly transfer a regulated substance into an underground storage tank.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201511[2020 c 20 § 1511]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5475-S.SL.pdf?cite=2007%20c%20147%20§%204[2007 c 147 § 4]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6130-S.SL.pdf?cite=1998%20c%20155%20§%204[1998 c 155 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c346.pdf?cite=1989%20c%20346%20§%206[1989 c 346 § 6]; ]

== 70A.355.050 - Investigation and access.
. If necessary to determine compliance with the requirements of this chapter, an authorized representative of the state engaged in compliance inspections, monitoring, and testing may, by request, require an owner or operator to submit relevant information or documents. The department may subpoena witnesses, documents, and other relevant information that the department deems necessary. In the case of any refusal to obey the subpoena, the superior court for any county in which the person is found, resides, or transacts business has jurisdiction to issue an order requiring the person to appear before the department and give testimony or produce documents. Any failure to obey the order of the court may be punished by the court as contempt.

. Any authorized representative of the state may require an owner or operator to conduct monitoring or testing.

. Upon reasonable notice, an authorized representative of the state may enter a premises or site subject to regulation under this chapter or in which records relevant to the operation of an underground storage tank system are kept. In the event of an emergency or in circumstances where notice would undermine the effectiveness of an inspection, notice is not required. The authorized representative may copy these records, obtain samples of regulated substances, and inspect or conduct monitoring or testing of an underground storage tank system.

. For purposes of this section, the term "authorized representative" or "authorized representative of the state" means an enforcement officer, employee, or representative of the department.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6130-S.SL.pdf?cite=1998%20c%20155%20§%205[1998 c 155 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c346.pdf?cite=1989%20c%20346%20§%207[1989 c 346 § 7]; ]

== 70A.355.060 - Enforcement.
The director may seek appropriate injunctive or other judicial relief by filing an action in Thurston county superior court or issue such order as the director deems appropriate to:

. Enjoin any threatened or continuing violation of this chapter or rules adopted under this chapter;

. Restrain immediately and effectively a person from engaging in unauthorized activity that results in a violation of any requirement of this chapter or rules adopted under this chapter and is endangering or causing damage to public health or the environment;

. Require compliance with requests for information, access, testing, or monitoring under RCW 70A.355.050; or

. Assess and recover civil penalties authorized under RCW 70A.355.070.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201512[2020 c 20 § 1512]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5475-S.SL.pdf?cite=2007%20c%20147%20§%205[2007 c 147 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c346.pdf?cite=1989%20c%20346%20§%208[1989 c 346 § 8]; ]

== 70A.355.070 - Penalties.
. A person who fails to notify the department pursuant to tank notification requirements or who submits false information is subject to a civil penalty not to exceed five thousand dollars per violation.

. A person who violates this chapter or rules adopted under this chapter is subject to a civil penalty not to exceed five thousand dollars for each tank per day of violation.

. A person incurring a penalty under this chapter or rules adopted under this chapter may apply to the department in writing for the remission or mitigation of the penalty as set out in RCW 43.21B.300. A person also may appeal a penalty directly to the pollution control hearings board in accordance with RCW 43.21B.300.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5475-S.SL.pdf?cite=2007%20c%20147%20§%206[2007 c 147 § 6]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1010-S.SL.pdf?cite=1995%20c%20403%20§%20639[1995 c 403 § 639]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c346.pdf?cite=1989%20c%20346%20§%209[1989 c 346 § 9]; ]

== 70A.355.080 - Annual tank fee.
. An annual tank fee of one hundred twenty dollars per tank is effective July 1, 2007, to June 30, 2008. An annual tank fee of one hundred forty dollars per tank is effective from July 1, 2008, to June 30, 2009. Effective July 1, 2009, the annual tank fee will increase up to one hundred sixty dollars per tank unless the department has received sufficient additional federal grant funding to offset the increased cost of implementation of the underground storage tank compliance act of 2005 (Title XV, Subtitle B of the energy policy act of 2005). Annually, beginning on July 1, 2010, and upon a finding by the department that a fee increase is necessary, the previous tank fee amount may be increased up to the fiscal growth factor for the next year. The fiscal growth factor is calculated by the office of financial management under RCW 43.135.025 for the upcoming biennium. The department shall use the fiscal growth factor to calculate the fee for the next year and shall publish the new fee by March 1st before the year for which the new fee is effective. The new tank fee is effective from July 1st to June 30th of every year. The tank fee shall be paid by every person who:

.. Owns an underground storage tank located in this state; and

.. Was required to provide notification to the department under the federal act.

This fee is not required of persons who have (i) permanently closed their tanks, and (ii) if required, have completed corrective action in accordance with the rules adopted under this chapter.

. The department may authorize the imposition of additional annual local tank fees in environmentally sensitive areas designated under RCW 70A.355.030. Annual local tank fees may not exceed fifty percent of the annual state tank fee.

. State and local tank fees collected under this section shall be deposited in the account established under RCW 70A.355.090.

. Other than the annual local tank fee authorized for environmentally sensitive areas, no local government may levy an annual tank fee on the ownership or operation of an underground storage tank.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201513[2020 c 20 § 1513]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5475-S.SL.pdf?cite=2007%20c%20147%20§%207[2007 c 147 § 7]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6130-S.SL.pdf?cite=1998%20c%20155%20§%206[1998 c 155 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c346.pdf?cite=1989%20c%20346%20§%2010[1989 c 346 § 10]; ]

== 70A.355.090 - Underground storage tank account.
The underground storage tank account is created in the state treasury. Money in the account may only be spent, subject to legislative appropriation, for the administration and enforcement of the underground storage tank program established under this chapter. The account shall contain:

. All fees collected under RCW 70A.355.080; and

. All fines or penalties collected under RCW 70A.355.070.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201514[2020 c 20 § 1514]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1058-S.SL.pdf?cite=1991%20sp.s.%20c%2013%20§%2072[1991 sp.s. c 13 § 72]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c346.pdf?cite=1989%20c%20346%20§%2011[1989 c 346 § 11]; ]

== 70A.355.100 - Preemption.
. Except as provided in RCW 70A.355.030 and subsections (2), (3), (4), and (5) of this section, the rules adopted under this chapter supersede and preempt any state or local underground storage tank law, ordinance, or resolution governing any aspect of regulation covered by the rules adopted under this chapter.

. Provisions of the international fire code adopted under chapter 19.27 RCW, which are not more stringent than, and do not directly conflict with, rules adopted under this chapter are not superseded or preempted.

. Local laws, ordinances, and resolutions pertaining to local authority to take immediate action in response to a release of a regulated substance are not superseded or preempted.

. City, town, or county underground storage tank ordinances that are more stringent than the federal regulations and the uniform codes adopted under chapter 19.27 RCW and that were in effect on or before November 1, 1988, are not superseded or preempted.

. Local laws, ordinances, and resolutions pertaining to permits and fees for the use of underground storage tanks in street right-of-ways that were in existence prior to July 1, 1990, are not superseded or preempted.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201515[2020 c 20 § 1515]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5475-S.SL.pdf?cite=2007%20c%20147%20§%208[2007 c 147 § 8]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1454-S.SL.pdf?cite=1991%20c%2083%20§%201[1991 c 83 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c346.pdf?cite=1989%20c%20346%20§%2012[1989 c 346 § 12]; ]

== 70A.355.900 - Captions not law.
Section headings used in this chapter do not constitute any part of the law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c346.pdf?cite=1989%20c%20346%20§%2015[1989 c 346 § 15]; ]

== 70A.355.901 - Severability—1989 c 346.
If any provision of this act or its application to any person or circumstance is held invalid, the remainder of the act or the application of the provision to other persons or circumstances is not affected.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c346.pdf?cite=1989%20c%20346%20§%2014[1989 c 346 § 14]; ]

== 70A.355.902 - Effective date—1989 c 346.
. Except as provided in subsection (2) of this section, RCW 70A.355.040, 70A.355.100, and 19.27.080 take effect on July 1, 1990.

. This section shall apply only if this act becomes effective as provided under *section 20(2) of this act.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201516[2020 c 20 § 1516]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c346.pdf?cite=1989%20c%20346%20§%2018[1989 c 346 § 18]; ]

