= 70A.218 - Hazardous waste fees.
:toc:

== 70A.218.010 - Definitions.
As used in this chapter, the following terms have the meanings indicated unless the context clearly requires otherwise.

. "Dangerous waste" shall have the same definition as set forth in RCW 70A.300.010(1) and shall include those wastes designated as dangerous by rules adopted pursuant to chapter 70A.300 RCW.

. "Department" means the department of ecology.

. "EPA/state identification number" means the number assigned by the EPA (environmental protection agency) or by the department of ecology to each generator and/or transporter and treatment, storage, and/or disposal facility.

. "Extremely hazardous waste" shall have the same definition as set forth in RCW 70A.300.010(7) and shall specifically include those wastes designated as extremely hazardous by rules adopted pursuant to chapter 70A.300 RCW.

. "Fee" means the annual fees imposed under this chapter.

. "Generate" means any act or process which produces hazardous waste or first causes a hazardous waste to become subject to regulation.

. "Hazardous waste" means and includes all dangerous and extremely hazardous wastes but for the purposes of this chapter excludes all radioactive wastes or substances composed of both radioactive and hazardous components.

. "Hazardous waste generator" means all persons whose primary business activities are identified by the department to generate any quantity of hazardous waste in the calendar year for which the fee is imposed.

. "Person" means an individual, trust, firm, joint stock company, partnership, association, state, public or private or municipal corporation, commission, political subdivision of a state, interstate body, the federal government including any agency or officer thereof, and any Indian tribe or authorized tribal organization.

. "Price deflator" means the United States department of commerce bureau of economic analysis, "Implicit Price Deflator for Gross National Product" for "Government Purchases of Goods and Services," for "State and Local Government."

. "Recycled for beneficial use" means the use of hazardous waste, either before or after reclamation, as a substitute for a commercial product or raw material, but does not include: (a) Use constituting disposal; (b) incineration; or (c) use as a fuel.

. "Waste generation site" means any geographical area that has been assigned an EPA/state identification number.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201221[2020 c 20 § 1221]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1162-S2.SL.pdf?cite=1995%20c%20207%20§%201[1995 c 207 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2662-S.SL.pdf?cite=1994%20c%20136%20§%201[1994 c 136 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c114.pdf?cite=1990%20c%20114%20§%2011[1990 c 114 § 11]; ]

== 70A.218.020 - Hazardous waste generation—Fee.
A fee is imposed for the privilege of generating hazardous waste in the state. The annual amount of the fee shall be thirty-five dollars upon every hazardous waste generator doing business in Washington in the current calendar year or any part thereof. This fee shall be collected by the department or its designee. A hazardous waste generator shall be exempt from the fee imposed under this section if the value of products, gross proceeds of sales, or gross income of the business, from all business activities of the hazardous waste generator, is less than twelve thousand dollars in the current calendar year. The department shall, subject to appropriation, use the funds collected from the fees assessed in this subsection to support the activities of the office of waste reduction as specified in RCW 70A.214.030. The fee imposed pursuant to this section is due annually by July 1 of the year following the calendar year for which the fee is imposed.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201222[2020 c 20 § 1222]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1162-S2.SL.pdf?cite=1995%20c%20207%20§%202[1995 c 207 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2671-S.SL.pdf?cite=1994%20sp.s.%20c%202%20§%203[1994 sp.s. c 2 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2662-S.SL.pdf?cite=1994%20c%20136%20§%202[1994 c 136 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c114.pdf?cite=1990%20c%20114%20§%2012[1990 c 114 § 12]; ]

== 70A.218.030 - Voluntary reduction plan—Fees.
Hazardous waste generators and hazardous substance users required to prepare plans under RCW 70A.214.110 shall pay an annual fee to support implementation of RCW 70A.214.110 and 70A.214.040. These fees are to be used by the department, subject to appropriation, for plan review, technical assistance to facilities that are required to prepare plans, other activities related to plan development and implementation, and associated indirect costs. The total fees collected under this subsection shall not exceed the department's costs of implementing RCW 70A.214.110 and 70A.214.040 and shall not exceed one million dollars per year. The annual fee for a facility shall not exceed ten thousand dollars per year. Any facility that generates less than two thousand six hundred forty pounds of hazardous waste per waste generation site in the previous calendar year shall be exempt from the fee imposed by this section. The annual fee for a facility generating at least two thousand six hundred forty pounds but not more than four thousand pounds of hazardous waste per waste generation site in the previous calendar year shall not exceed fifty dollars. A person that develops a plan covering more than one interrelated facility as provided for in RCW 70A.214.110 shall be assessed fees only for the number of plans prepared. The department shall adopt a fee schedule by rule after consultation with typical affected businesses and other interested parties. Hazardous waste generated and recycled for beneficial use, including initial amount of hazardous substances introduced into a process and subsequently recycled for beneficial use, shall not be used in the calculations of hazardous waste generated for purposes of this section.

The annual fee imposed by this section shall be first due on July 1st of the year prior to the year that the facility is required to prepare a plan, and by July 1st of each year thereafter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201223[2020 c 20 § 1223]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2662-S.SL.pdf?cite=1994%20c%20136%20§%203[1994 c 136 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c114.pdf?cite=1990%20c%20114%20§%2013[1990 c 114 § 13]; ]

== 70A.218.040 - Fees—Generally.
On an annual basis, the department shall adjust the fees provided for in RCW 70A.218.020 and 70A.218.030, including the maximum annual fee, and maximum total fees, by conducting the calculation in subsection (1) of this section and taking the actions set forth in subsection (2) of this section:

. In November of each year, the fees, annual fee, and maximum total fees imposed in RCW 70A.218.020 and 70A.218.030, or as subsequently adjusted by this section, shall be multiplied by a factor equal to the most current quarterly "price deflator" available, divided by the "price deflator" used in the numerator the previous year. However, the "price deflator" used in the denominator for the first adjustment shall be defined by the second quarter "price deflator" for 1990.

. Each year by March 1st the fee schedule, as adjusted in subsection (1) of this section will be published. The department will round the published fees to the nearest dollar.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201224[2020 c 20 § 1224]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c114.pdf?cite=1990%20c%20114%20§%2014[1990 c 114 § 14]; ]

== 70A.218.050 - Administration of fees.
In administration of this chapter for the enforcement and collection of the fees due and owing under RCW 70A.218.020 and 70A.218.030, the department may apply RCW 43.17.240.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201225[2020 c 20 § 1225]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1162-S2.SL.pdf?cite=1995%20c%20207%20§%203[1995 c 207 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2662-S.SL.pdf?cite=1994%20c%20136%20§%204[1994 c 136 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c114.pdf?cite=1990%20c%20114%20§%2015[1990 c 114 § 15]; ]

== 70A.218.060 - Hazardous waste assistance account.
The hazardous waste assistance account is hereby created in the state treasury. The following moneys shall be deposited into the hazardous waste assistance account:

. Those revenues which are raised by the fees imposed under RCW 70A.218.020 and 70A.218.030;

. Penalties and surcharges collected under chapter 70A.214 RCW and this chapter; and

. Any other moneys appropriated or transferred to the account by the legislature. Moneys in the hazardous waste assistance account may be spent only for the purposes of this chapter following legislative appropriation.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201226[2020 c 20 § 1226]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1058-S.SL.pdf?cite=1991%20sp.s.%20c%2013%20§%2075[1991 sp.s. c 13 § 75]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c114.pdf?cite=1990%20c%20114%20§%2018[1990 c 114 § 18]; ]

== 70A.218.070 - Technical assistance and compliance education—Grants.
The department may use funds in the hazardous waste assistance account to provide technical assistance and compliance education assistance to hazardous substance users and waste generators, to provide grants to local governments, and for administration of this chapter.

Technical assistance may include the activities authorized under chapter 70A.214 RCW and RCW 70A.300.290 to encourage hazardous waste reduction and hazardous use reduction and the assistance provided for by RCW 70A.300.140(2).

Compliance education may include the activities authorized under RCW 70A.300.140(2) to train local agency officials and to inform hazardous substance users and hazardous waste generators and owners and operators of hazardous waste management facilities of the requirements of chapter 70A.300 RCW and related federal laws and regulations. To the extent practicable, the department shall contract with private businesses to provide compliance education.

Grants to local governments shall be used for small quantity generator technical assistance and compliance education components of their moderate risk waste plans as required by RCW 70A.300.350.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201227[2020 c 20 § 1227]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1162-S2.SL.pdf?cite=1995%20c%20207%20§%204[1995 c 207 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c114.pdf?cite=1990%20c%20114%20§%2019[1990 c 114 § 19]; ]

== 70A.218.080 - Exclusion from chapter.
Nothing in this chapter relates to radioactive wastes or substances composed of both radioactive and hazardous components, and the department is precluded from using the funds of the hazardous waste assistance account for the regulation and control of such wastes.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c114.pdf?cite=1990%20c%20114%20§%2020[1990 c 114 § 20]; ]

