= 70A.220 - Labeling of plastics.
:toc:

== 70A.220.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Container," unless otherwise specified, refers to "rigid plastic container" or "plastic bottle" as those terms are defined in this section.

. "Distributors" means those persons engaged in the distribution of packaged goods for sale in the state of Washington, including manufacturers, wholesalers, and retailers.

. "Label" means a molded, imprinted, or raised symbol on or near the bottom of a plastic container or bottle.

. "Person" means an individual, sole proprietor, partnership, association, or other legal entity.

. "Plastic" means a material made of polymeric organic compounds and additives that can be shaped by flow.

. "Plastic bottle" means a plastic container intended for single use that has a neck that is smaller than the body of the container, accepts a screw-type, snap cap, or other closure and has a capacity of sixteen fluid ounces or more, but less than five gallons.

. "Rigid plastic container" means a formed or molded container, other than a bottle, intended for single use, composed predominantly of plastic resin, and having a relatively inflexible finite shape or form with a capacity of eight ounces or more but less than five gallons.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5591-S2.SL.pdf?cite=1991%20c%20319%20§%20103[1991 c 319 § 103]; ]

== 70A.220.020 - Plastic bottle or rigid plastic container—Labeling requirements.
Except as provided in RCW 70A.220.030(2), after January 1, 1992, no person may distribute, sell, or offer for sale in this state a plastic bottle or rigid plastic container unless the container is labeled with a code identifying the appropriate resin type used to produce the structure of the container. The numbers and letters used shall be as follows:

.. [(1)] 1.= PETE (polyethylene terephthalate)

.. [(2)] 2.= HDPE (high density polyethylene)

.. [(3)] 3.= V (vinyl) or PVC (polyvinyl chloride)

.. [(4)] 4.= LDPE (low density polyethylene)

.. [(5)] 5.= PP (polypropylene)

.. [(6)] 6.= PS (polystyrene)

.. [(7)] 7.= OTHER

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5022-S2.SL.pdf?cite=2021%20c%20313%20§%2018[2021 c 313 § 18]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201228[2020 c 20 § 1228]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5591-S2.SL.pdf?cite=1991%20c%20319%20§%20104[1991 c 319 § 104]; ]

== 70A.220.030 - Violations, penalty.
. A person who, after written notice from the department, violates RCW 70A.220.020 is subject to a civil penalty of fifty dollars for each violation up to a maximum of five hundred dollars and may be enjoined from continuing violations. Each distribution constitutes a separate offense.

. Retailers and distributors shall have two years from May 21, 1991, to clear current inventory, delivered or received and held in their possession as of May 21, 1991.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201229[2020 c 20 § 1229]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5591-S2.SL.pdf?cite=1991%20c%20319%20§%20105[1991 c 319 § 105]; ]

