= 70A.320 - Area-wide soil contamination.
:toc:

== 70A.320.010 - Findings.
The legislature finds that state and local agencies are currently implementing actions to reduce children's exposure to soils that contain hazardous substances. The legislature further finds that it is in the public interest to enhance those efforts in western Washington in areas located within the central Puget Sound smelter plume.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1605-S2.SL.pdf?cite=2005%20c%20306%20§%201[2005 c 306 § 1]; ]

== 70A.320.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Area-wide soil contamination" means low to moderate arsenic and lead soil contamination dispersed over a large geographic area.

. "Child care facility" means a child day-care center or a family day-care provider as those terms are defined under *RCW 74.15.020.

. "Department" means the department of ecology.

. "Director" means the director of the department of ecology.

. "Low to moderate soil contamination" means low level arsenic or lead concentrations where a child's exposure to soil contamination at a school or a child care facility may be reduced through best management practices.

. "School" means a public or private kindergarten, elementary, or secondary school.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1605-S2.SL.pdf?cite=2005%20c%20306%20§%202[2005 c 306 § 2]; ]

== 70A.320.030 - Children in schools and child care facilities—Department duties—School and child care facility duties.
. The department, in cooperation with the department of social and health services, the department of health, the office of the superintendent of public instruction, and local health districts, shall assist schools and child care facilities west of the crest of the Cascade mountains to reduce the potential for children's exposure to area-wide soil contamination.

. The department shall:

.. Identify schools and child care facilities that are located within the central Puget Sound smelter plume based on available information;

.. Conduct qualitative evaluations to determine the potential for children's exposure to area-wide soil contamination;

.. If the qualitative evaluation determines that children may be routinely exposed to area-wide soil contamination at a property, conduct soil samples at that property by December 31, 2009; and

.. If soil sample results confirm the presence of area-wide soil contamination, notify schools and child care facilities regarding the test results and the steps necessary for implementing best management practices.

. If a school or a child care facility with area-wide soil contamination does not implement best management practices within six months of receiving written notification from the department, the superintendent or board of directors of a school or the owner or operator of a child care facility must notify parents and guardians in writing of the results of soil tests. The written notice shall be prepared by the department.

. The department shall recognize schools and child care facilities that successfully implement best management practices with a voluntary certification letter confirming that the facility has successfully implemented best management practices.

. Schools and child care facilities must work with the department to provide the department with site access for soil sampling at times that are the most convenient for all parties.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1605-S2.SL.pdf?cite=2005%20c%20306%20§%203[2005 c 306 § 3]; ]

== 70A.320.040 - Department assistance—Best management practice guidelines—Grants—Interagency agreements authorized—Reports.
. The department shall assist schools and owners and operators of child care facilities located within the central Puget Sound smelter plume. Such assistance may include the following:

.. Technical assistance in conducting qualitative evaluations to determine where area-wide soil contamination exposures could occur;

.. Technical and financial assistance in testing soils where evaluations indicate potential for contamination; and

.. Technical and financial assistance to implement best management practices.

. The department shall develop best management practice guidelines for schools and day care facilities with area-wide soil contamination. The guidelines shall recommend a range of methods for reducing exposure to contaminated soil, considering the concentration, extent, and location of contamination and the nature and frequency of child use of the area.

. The department shall develop a grant program to assist schools and child care facilities with implementing best management practices.

. The department, within available funds, may provide grants to schools and child care facilities for the purpose of implementing best management practices.

. The department, within available funds, may provide financial assistance to the department of health and the department of social and health services to implement this chapter.

. The department may, through an interagency agreement, authorize a local health jurisdiction to administer any activity in this chapter that is otherwise not assigned to a local health jurisdiction by this chapter.

. The department shall evaluate actions to reduce child exposure to contaminated soils and submit progress reports to the governor and to the appropriate committees of the legislature by December 31, 2006, and December 31, 2008.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1605-S2.SL.pdf?cite=2005%20c%20306%20§%204[2005 c 306 § 4]; ]

== 70A.320.050 - Department of health to provide assistance.
The department of health shall assist the department in implementing this chapter, including but not limited to developing best management practices and guidelines.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1605-S2.SL.pdf?cite=2005%20c%20306%20§%205[2005 c 306 § 5]; ]

== 70A.320.060 - Department of social and health services to provide assistance.
The department of social and health services shall assist the department by providing information on the location of child care facilities and contacts for these facilities.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1605-S2.SL.pdf?cite=2005%20c%20306%20§%206[2005 c 306 § 6]; ]

== 70A.320.070 - Livestock, agricultural land exempt from chapter.
This chapter does not apply to land devoted primarily to the commercial production of livestock or agricultural commodities.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1605-S2.SL.pdf?cite=2005%20c%20306%20§%207[2005 c 306 § 7]; ]

== 70A.320.080 - Existing authority of department not affected.
Nothing in this chapter is intended to change ongoing actions or the authority of the department or other agencies to require actions to address soil contamination under existing laws.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1605-S2.SL.pdf?cite=2005%20c%20306%20§%208[2005 c 306 § 8]; ]

