= 70A.445 - Recreational water vessels—Antifouling paints.
:toc:

== 70A.445.005 - Intent.
Antifouling paints and coatings are necessary for the proper performance and preservation of boats and other marine craft. However, many of these substances contain copper, biocides, and other chemicals that are toxic to many aquatic organisms, including salmon. The legislature intends to phase out the use of copper-based and other antifouling paints and coatings that pose an undue threat to the environment when used on recreational water vessels. The legislature also intends to encourage the development of safer alternatives to traditional antifouling paints and coatings.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2634-S.SL.pdf?cite=2018%20c%2094%20§%201[2018 c 94 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5436-S.SL.pdf?cite=2011%20c%20248%20§%201[2011 c 248 § 1]; ]

== 70A.445.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Department" means the department of ecology.

. "Director" means the director of the department of ecology.

. [Empty]
.. "Recreational water vessel" means any vessel that is no more than sixty-five feet in length and is: (i) Manufactured or used primarily for pleasure; or (ii) leased, rented, or chartered by a person for the pleasure of that person.

.. "Recreational water vessel" does not include a vessel that is subject to United States coast guard inspection and that: (i) Is engaged in commercial use; or (ii) carries paying passengers.

. "Wood boat" means a recreational water vessel with an external hull surface entirely constructed of wood planks or sheets. A vessel with a wood hull sheathed in a nonwood material, such as fiberglass, is not a "wood boat" for purposes of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2634-S.SL.pdf?cite=2018%20c%2094%20§%202[2018 c 94 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5436-S.SL.pdf?cite=2011%20c%20248%20§%202[2011 c 248 § 2]; ]

== 70A.445.020 - Antifouling paint—Review—Report to the legislature—Restrictions on sale and application.
. The department will conduct a review of information about antifouling paints and ingredients, including information received from manufacturers and others pursuant to this chapter; information on the feasibility of best management practices and nonbiocidal antifouling alternatives; and any additional scientific or technical information and studies it determines are relevant to that review.

. The department must submit a report to the legislature summarizing its findings no later than June 30, 2024. Prior to submitting the report to the legislature, the department will conduct a public comment process to obtain expertise, input, and a review of the department's proposed determinations by relevant stakeholders and other interested parties. The input received from the public comment process must be considered before finalizing the report.

. If the department determines that safer and effective alternatives to copper-based antifouling paints are feasible, reasonable, and readily available, then:

.. Beginning January 1, 2026, no manufacturer, wholesaler, retailer, or distributor may sell or offer for sale in this state any new recreational water vessel manufactured on or after January 1, 2026, with antifouling paint containing more than 0.5 percent copper. This restriction does not apply to wood boats.

.. Beginning January 1, 2026, antifouling paint that is intended for use on a recreational water vessel and that contains more than 0.5 percent copper may not be offered for sale in this state.

.. Beginning January 1, 2026, antifouling paint containing more than 0.5 percent copper may not be applied to a recreational water vessel in this state. This restriction does not apply to wood boats.

. If the department does not determine by June 30, 2024, that safer and effective alternatives to copper-based antifouling paints are feasible, reasonable, and readily available, then the department must conduct a second review of relevant studies and information on alternatives to copper-based antifouling paints and submit a report to the legislature summarizing its findings no later than June 30, 2029.

. Nothing in this section restricts the department from reviewing and restricting antifouling paints under chapter 70A.350 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1192.SL.pdf?cite=2021%20c%2065%20§%2076[2021 c 65 § 76]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6210-S.SL.pdf?cite=2020%20c%2067%20§%201[2020 c 67 § 1]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2634-S.SL.pdf?cite=2018%20c%2094%20§%203[2018 c 94 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5436-S.SL.pdf?cite=2011%20c%20248%20§%203[2011 c 248 § 3]; ]

== 70A.445.030 - Recreational water vessel hull cleaning—Best practices.
The department, in consultation and cooperation with other state natural resources agencies, must increase educational efforts regarding recreational water vessel hull cleaning to reduce the spread of invasive species. This effort must include a review of best practices that consider the type of antifouling paint used and recommendations regarding appropriate hull cleaning that includes in-water methods.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5436-S.SL.pdf?cite=2011%20c%20248%20§%204[2011 c 248 § 4]; ]

== 70A.445.040 - Civil penalty.
. The department must enforce the requirements of this chapter.

. [Empty]
.. A person or entity that violates this chapter is subject to a civil penalty. The department may assess and collect a civil penalty of up to ten thousand dollars per day per violation.

.. All penalties collected by the department under this chapter must be deposited in the model toxics control operating account created in RCW 70A.305.180.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201425[2020 c 20 § 1425]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5993-S.SL.pdf?cite=2019%20c%20422%20§%20411[2019 c 422 § 411]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5436-S.SL.pdf?cite=2011%20c%20248%20§%205[2011 c 248 § 5]; ]

== 70A.445.050 - Statewide advisory committee—Survey—Report to the legislature.
. On or after January 1, 2016, the director may establish and maintain a statewide advisory committee to assist the department in implementing the requirements of this chapter.

. [Empty]
.. By January 1, 2017, the department shall survey the manufacturers of antifouling paints sold or offered for sale in this state to determine the types of antifouling paints that are available in this state. The department shall also study how antifouling paints affect marine organisms and water quality. The department shall report its findings to the legislature, consistent with RCW 43.01.036, by December 31, 2017.

.. If the statewide advisory committee authorized under subsection (1) of this section is established by the director, the department may consult with the statewide advisory committee to prepare the report required under (a) of this subsection.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5436-S.SL.pdf?cite=2011%20c%20248%20§%206[2011 c 248 § 6]; ]

== 70A.445.060 - Rule-making authority.
The department may adopt rules as necessary to implement this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5436-S.SL.pdf?cite=2011%20c%20248%20§%207[2011 c 248 § 7]; ]

== 70A.445.070 - Prohibition on sales of new recreational water vessels containing certain antifouling paint.
. Beginning January 1, 2023, no manufacturer, wholesaler, retailer, or distributor may sell or offer for sale in this state any new recreational water vessel manufactured on or after January 1, 2023, with antifouling paint containing cybutryne, chemical abstracts service registration number 28159-98-0.

. Beginning January 1, 2023, antifouling paint that is intended for use on a recreational water vessel and that contains cybutryne may not be offered for sale in this state.

. Beginning January 1, 2023, antifouling paint containing cybutryne may not be applied to a recreational water vessel in this state.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6210-S.SL.pdf?cite=2020%20c%2067%20§%202[2020 c 67 § 2]; ]

== 70A.445.080 - Notice to the department.
. The department may require a manufacturer, wholesaler, or retailer of antifouling paints or related substances to submit a notice to the department containing the following information:

.. A list of products, including a brief description of each product or product component containing the substance;

.. Product ingredients, including the names of the chemicals used or produced and applicable chemical abstracts service registry numbers;

.. Information regarding exposure and chemical hazard;

.. A description of the function of each chemical in the product;

.. The amount of the chemical used in each unit of the product or product component;

.. The name and address of the manufacturer and the name, address, and phone number of a contact person for the manufacturer;

.. Any other information the manufacturer deems relevant to the appropriate use of the product; and

.. Any other information requested by the department.

. The manufacturer must provide the notice required in subsection (1) of this section to the department no later than six months after receipt of such a demand by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6210-S.SL.pdf?cite=2020%20c%2067%20§%203[2020 c 67 § 3]; ]

