= 70A.420 - Lead-based paint.
:toc:

== 70A.420.010 - Finding.
. The legislature finds that lead hazards associated with lead-based paint represent a significant and preventable environmental health problem. Lead-based paint is the most widespread of the various sources of lead exposure to the public. Census data show that one million five hundred sixty thousand homes in Washington state were built prior to 1978 when the sale of residential lead-based paint was banned. These are homes that are believed to contain some lead-based paint.

Lead negatively affects every system of the body. It is harmful to individuals of all ages and is especially harmful to children, fetuses, and adults of childbearing age. The effects of lead on a child's cognitive, behavioral, and developmental abilities may necessitate large expenditures of public funds for health care and special education. The irreversible damage to children and subsequent expenditures could be avoided if exposure to lead is reduced.

. The federal government regulates lead poisoning and lead hazard reduction through:

.. [Empty]
... The lead-based paint poisoning prevention act;

... The lead contamination control act;

... The safe drinking water act;

... The resource conservation and recovery act of 1976; and

.. The residential lead-based paint hazard reduction act of 1992; and

.. Implementing regulations of:

... The environmental protection agency;

... The department of housing and urban development;

... The occupational safety and health administration; and

... The centers for disease control and prevention.

. In 1992, congress passed the federal residential lead-based paint hazard reduction act, which allows states to provide for the accreditation of lead-based paint activities programs, the certification of persons completing such training programs, and the licensing of lead-based paint activities contractors under standards developed by the United States environmental protection agency.

. The legislature recognizes the state's need to protect the public from exposure to lead hazards. A qualified and properly trained workforce is needed to assist in the prevention, detection, reduction, and elimination of hazards associated with lead-based paint. The purpose of training workers, supervisors, inspectors, risk assessors, project designers, renovators, and dust sampling technicians engaged in lead-based paint activities is to protect building occupants, particularly children ages six years and younger from potential lead-based paint hazards and exposures both during and after lead-based paint activities. Qualified and properly trained individuals and firms will help to ensure lead-based paint activities are conducted in a way that protects the health of the citizens of Washington state and safeguards the environment. The state lead-based paint activities program requires that all lead-based paint activities be performed by certified personnel trained by an accredited program, and that all lead-based paint activities meet minimum work practice standards established by the department of commerce. Therefore, the lead-based paint activities accreditation, training, and certification program shall be established in accordance with this chapter. The lead-based paint activities accreditation, training, and certification program shall be administered by the department of commerce and shall be used as a means to assure the protection of the general public from exposure to lead hazards.

. For the welfare of the people of the state of Washington, this chapter establishes a lead-based paint activities program within the department of commerce to protect the general public from exposure to lead hazards and to ensure the availability of a trained and qualified workforce to identify and address lead-based paint hazards. The legislature recognizes the department of commerce is not a regulatory agency and may delegate enforcement responsibilities under chapter 322, Laws of 2003 to local governments or private entities.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2745-S.SL.pdf?cite=2010%20c%20158%20§%201[2010 c 158 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5586-S.SL.pdf?cite=2003%20c%20322%20§%201[2003 c 322 § 1]; ]

== 70A.420.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Abatement" means any measure or set of measures designed to permanently eliminate lead-based paint hazards.

.. Abatement includes, but is not limited to:

... The removal of paint and dust, the permanent enclosure or encapsulation of lead-based paint, the replacement of painted surfaces or fixtures, or the removal or permanent covering of soil, when lead-based paint hazards are present in such paint, dust, or soil; and

... All preparation, cleanup, disposal, and postabatement clearance testing activities associated with such measures.

.. Specifically, abatement includes, but is not limited to:

... Projects for which there is a written contract or other documentation, which provides that an individual or firm will be conducting activities in or to a residential dwelling or child-occupied facility that:

(A) Shall result in the permanent elimination of lead-based paint hazards; or

(B) Are designed to permanently eliminate lead-based paint hazards and are described in (a)(i) and (ii) of this subsection;

... Projects resulting in the permanent elimination of lead-based paint hazards, conducted by certified firms or individuals, unless such projects are covered by (c) of this subsection;

... Projects resulting in the permanent elimination of lead-based paint hazards, conducted by firms or individuals who, through their company name or promotional literature, represent, advertise, or hold themselves out to be in the business of performing lead-based paint activities as identified and defined by this section, unless such projects are covered by (c) of this subsection; or

... Projects resulting in the permanent elimination of lead-based paint hazards, that are conducted in response to state or local abatement orders.

.. Abatement does not include renovation, remodeling, landscaping, or other activities, when such activities are not designed to permanently eliminate lead-based paint hazards, but, instead, are designed to repair, restore, or remodel a given structure or dwelling, even though these activities may incidentally result in a reduction or elimination of lead-based paint hazards. Furthermore, abatement does not include interim controls, operations and maintenance activities, or other measures and activities designed to temporarily, but not permanently, reduce lead-based paint hazards.

. "Accredited training program" means a training program that has been accredited by the department to provide training for individuals engaged in lead-based paint activities.

. "Certified abatement worker" means an individual who has been trained by an accredited training program, meets all the qualifications established by the department, and is certified by the department to perform abatements.

. "Certified dust sampling technician" means an individual who has been trained by an accredited training program, meets all the qualifications established by the department, and is certified by the department to conduct dust sampling for renovation projects.

. "Certified firm" includes a company, partnership, corporation, sole proprietorship, association, agency, or other business entity that meets all the qualifications established by the department and performs lead-based paint activities to which the department has issued a certificate.

. "Certified inspector" means an individual who has been trained by an accredited training program, meets all the qualifications established by the department, and is certified by the department to conduct inspections.

. "Certified project designer" means an individual who has been trained by an accredited training program, meets all the qualifications established by the department, and is certified by the department to prepare abatement project designs, occupant protection plans, and abatement reports.

. "Certified renovator" means an individual who has been trained by an accredited training program, meets all the qualifications established by the department, and is certified by the department to perform renovations or direct workers in the performance of renovation work.

. "Certified risk assessor" means an individual who has been trained by an accredited training program, meets all the qualifications established by the department, and is certified by the department to conduct risk assessments and sample for the presence of lead in dust and soil for the purposes of abatement clearance testing.

. "Certified supervisor" means an individual who has been trained by an accredited training program, meets all the qualifications established by the department, and is certified by the department to supervise and conduct abatements, and to prepare occupant protection plans and abatement reports.

. "Department" means the Washington state department of commerce.

. "Director" means the director of the Washington state department of commerce.

. "Federal laws and rules" means:

.. Title IV, toxic substances control act (15 U.S.C. Sec. 2681 et seq.) and the rules adopted by the United States environmental protection agency under that law for authorization of state programs;

.. Any regulations or requirements adopted by the United States department of housing and urban development regarding eligibility for grants to states and local governments; and

.. Any other requirements adopted by a federal agency with jurisdiction over lead-based paint hazards.

. "Lead-based paint" means paint or other surface coatings that contain lead equal to or in excess of 1.0 milligrams per square centimeter or more than 0.5 percent by weight.

. "Lead-based paint activity" includes inspection, testing, risk assessment, lead-based paint hazard reduction project design or planning, abatement, or renovation of lead-based paint hazards.

. "Lead-based paint hazard" means any condition that causes exposure to lead from lead-contaminated dust, lead-contaminated soil, or lead-contaminated paint that is deteriorated or present in accessible surfaces, friction surfaces, or impact surfaces that would result in adverse human health effects as identified by the administrator of the United States environmental protection agency under the toxic substances control act, section 403.

. "Person" includes an individual, corporation, firm, partnership, or association, an Indian tribe, state, or political subdivision of a state, and a state department or agency.

. "Renovation" means the modification of any existing structure, or portion thereof, that results in the disturbance of painted surfaces, unless that activity is performed as part of an abatement as defined in this section. The term includes but is not limited to:

.. The removal, modification, or repair of painted surface or painted components;

.. Modification of painted doors;

.. Surface restoration;

.. Window repair;

.. Surface preparation, such as sanding, scraping, or activities that generates paint dust;

.. Removal of building components, such as walls, windows, or other like structures;

.. Weatherization projects, such as cutting holes in painted surfaces to install blown-in insulation;

.. Interim controls that disturb painted surfaces; or

.. A renovation performed for the purposes of converting a building or part of a building in target housing or a child-occupied facility.

The term renovation as defined in this subsection (18) does not include minor repair and maintenance activities.

. "Risk assessment" means:

.. An on-site investigation to determine the existence, nature, severity, and location of lead-based paint hazards; and

.. The provision of a report by the individual or the firm conducting the risk assessment, explaining the results of the investigation and options for reducing lead-based paint hazards.

. "State program" means a state administered lead-based paint activities certification and training program that meets the federal environmental protection agency requirements.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2745-S.SL.pdf?cite=2010%20c%20158%20§%202[2010 c 158 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2009%20c%20565%20§%2049[2009 c 565 § 49]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5586-S.SL.pdf?cite=2003%20c%20322%20§%202[2003 c 322 § 2]; ]

== 70A.420.030 - Certification and training—Local governments—Rules.
. The department shall administer and enforce a state program for worker training and certification, and training program accreditation, which shall include those program elements necessary to assume responsibility for federal requirements for a program as set forth in Title IV of the toxic substances control act (15 U.S.C. Sec. 2601 et seq.), the residential lead-based paint hazard reduction act of 1992 (42 U.S.C. Sec. 4851 et seq.), 40 C.F.R. Part 745, Subparts L and Q (1996), and Title X of the housing and community development act of 1992 (P.L. 102-550). The department may delegate or enter into a memorandum of understanding with local governments or private entities for implementation of components of the state program.

. The department is authorized to adopt rules that are consistent with federal requirements to implement a state program. Rules adopted under this section shall:

.. Establish minimum accreditation requirements for lead-based paint activities for training providers;

.. Establish work practice standards for conduct of lead-based paint activities;

.. Establish certification requirements for individuals and firms engaged in lead-based paint activities including provisions for recognizing certifications accomplished under existing certification programs;

.. Require the use of certified personnel in all lead-based paint activities;

.. Be revised as necessary to comply with federal law and rules and to maintain eligibility for federal funding;

.. Facilitate reciprocity and communication with other states having a lead-based paint certification program;

.. Provide for decertification, deaccreditation, and financial assurance for a person certified by or a training provider accredited by the department; and

.. Be issued in accordance with the administrative procedure act, chapter 34.05 RCW.

. The department may accept federal funds for the administration of the program.

. This program shall equal, but not exceed, legislative authority under federal requirements as set forth in Title IV of the toxic substances control act (15 U.S.C. Sec. 2601 et seq.), the residential lead-based paint hazard reduction act of 1992 (42 U.S.C. Sec. 4851 et seq.), and Title X of the housing and community development act of 1992 (P.L. 102-550).

. Any rules adopted by the department shall be consistent with federal laws, regulations, and requirements relating to lead-based paint activities specified by the residential lead-based paint hazard reduction act of 1992 (42 U.S.C. Sec. 4851 et seq.) and Title X of the housing and community development act of 1992 (P.L. 102-550), and rules adopted pursuant to chapter 70A.305 RCW, to ensure consistency in regulatory action. The rules may not be more restrictive than corresponding federal and state regulations unless such stringency is specifically authorized by this chapter.

. The department shall collect a fee in the amount of twenty-five dollars for certification and recertification of lead paint firms, inspectors, project developers, risk assessors, supervisors, abatement workers, renovators, and dust sampling technicians.

. The department shall collect a fee in the amount of two hundred dollars for the accreditation of lead paint training programs.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201272[2020 c 20 § 1272]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2745-S.SL.pdf?cite=2010%20c%20158%20§%203[2010 c 158 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5586-S.SL.pdf?cite=2003%20c%20322%20§%203[2003 c 322 § 3]; ]

== 70A.420.040 - Certification and accreditation—Rules.
. The department shall establish a program for certification of persons involved in lead-based paint activities and for accreditation of training providers in compliance with federal laws and rules.

. Rules adopted under this section shall:

.. Establish minimum accreditation requirements for lead-based paint activities for training providers;

.. Establish work practice standards for conduct of lead-based paint activities;

.. Establish certification requirements for individuals and firms engaged in lead-based paint activities including provisions for recognizing certifications accomplished under existing certification programs;

.. Require the use of certified personnel in any lead-based paint hazard reduction activity;

.. Be revised as necessary to comply with federal law and rules and to maintain eligibility for federal funding;

.. Facilitate reciprocity and communication with other states having a lead-based paint certification program;

.. Provide for decertification, deaccreditation, and financial assurance for a person certified or accredited by the department; and

.. Be issued in accordance with the administrative procedure act, chapter 34.05 RCW.

. This program shall equal, but not exceed, legislative authority under federal requirements as set forth in Title IV of the toxic substances control act (15 U.S.C. Sec. 2601 et seq.), the residential lead-based paint hazard reduction act of 1992 (42 U.S.C. Sec. 4851 et seq.), 40 C.F.R. Part 745 (1996), Subparts L and Q, and Title X of the housing and community development act of 1992 (P.L. 102-550).

. Any rules adopted by the department shall be consistent with federal laws, regulations, and requirements relating to lead-based paint activities specified by the residential lead-based paint hazard reduction act of 1992 (42 U.S.C. Sec. 4851 et seq.) and Title X of the housing and community development act of 1992 (P.L. 102-550), and rules adopted pursuant to chapter 70A.305 RCW, to ensure consistency in regulatory action. The rules may not be more restrictive than corresponding federal and state regulations unless such stringency is specifically authorized by this chapter.

. The department may accept federal funds for the administration of the program.

. For the purposes of certification under the federal requirements as set forth in section 2682 of the toxic substances control act (15 U.S.C. Sec. 2682), the department may require renovators and dust sampling technicians to apply for a certification badge issued by the department. The department may impose a fee on the applicant for processing the application. The application shall include a photograph of the applicant and a fee in the amount imposed by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201273[2020 c 20 § 1273]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2745-S.SL.pdf?cite=2010%20c%20158%20§%204[2010 c 158 § 4]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5586-S.SL.pdf?cite=2003%20c%20322%20§%204[2003 c 322 § 4]; ]

== 70A.420.050 - Rules—Report.
The department shall adopt rules to:

. Establish procedures and requirements for the accreditation of lead-based paint activities training programs including, but not limited to, the following:

.. Training curriculum;

.. Training hours;

.. Hands-on training;

.. Trainee competency and proficiency;

.. Training program quality control;

.. Procedures for the reaccreditation of training programs;

.. Procedures for the oversight of training programs; and

.. Procedures for the suspension, revocation, or modification of training program accreditations, or acceptance of training offered by an accredited training provider in another state or Indian tribe authorized by the environmental protection agency;

. Establish procedures for the purposes of certification, for the acceptance of training offered by an accredited training provider in a state or Indian tribe authorized by the environmental protection agency;

. Certify individuals involved in lead-based paint activities to ensure that certified individuals are trained by an accredited training program and possess appropriate educational or experience qualifications for certification;

. Establish procedures for recertification;

. Require the conduct of lead-based paint activities in accordance with work practice standards;

. Establish procedures for the suspension, revocation, or modification of certifications;

. Establish requirements for the administration of third-party certification exams;

. Use laboratories accredited under the environmental protection agency's national lead laboratory accreditation program;

. Establish work practice standards for the conduct of lead-based paint activities, as defined in RCW 70A.420.020;

. Establish an enforcement response policy that shall include:

.. Warning letters, notices of noncompliance, notices of violation, or the equivalent;

.. Administrative or civil actions, including penalty authority, including accreditation or certification suspension, revocation, or modification; and

.. Authority to apply criminal sanctions or other criminal authority using existing state laws as applicable.

The department shall prepare and submit a biennial report to the legislature regarding the program's status, its costs, and the number of persons certified by the program.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201274[2020 c 20 § 1274]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2745-S.SL.pdf?cite=2010%20c%20158%20§%205[2010 c 158 § 5]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5586-S.SL.pdf?cite=2003%20c%20322%20§%205[2003 c 322 § 5]; ]

== 70A.420.060 - Lead paint account.
The lead paint account is created in the state treasury. All receipts from RCW 70A.420.030 shall be deposited into the account. Moneys in the account may be spent only after appropriation. Expenditures from the account may be used only for the purposes of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201275[2020 c 20 § 1275]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5586-S.SL.pdf?cite=2003%20c%20322%20§%206[2003 c 322 § 6]; ]

== 70A.420.070 - Inspections.
. [Empty]
.. The director or the director's designee is authorized to inspect at reasonable times and, when feasible, with at least twenty-four hours prior notification:

... Premises or facilities where those engaged in training for lead-based paint activities conduct business; and

... The business records of, and take samples at, the businesses accredited or certified under this chapter to conduct lead-based paint training or activities.

.. Any accredited training program or any firm or individual certified under this chapter that denies access to the department for the purposes of (a) of this subsection is subject to deaccreditation or decertification under RCW 70A.420.040.

. The director or the director's designee is authorized to inspect premises or facilities, with the consent of the owner or owner's agent, where violations may occur concerning lead-based paint activities, as defined under RCW 70A.420.020, at reasonable times and, when feasible, with at least forty-eight hours prior notification of the inspection.

. Prior to receipt of federal lead-based paint abatement funding, all premise or facility owners shall be notified by any entity that receives and disburses the federal funds that an inspection may be conducted. If a premise or facility owner does not wish to have an inspection conducted, that owner is not eligible to receive lead-based paint abatement funding.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201276[2020 c 20 § 1276]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5586-S.SL.pdf?cite=2003%20c%20322%20§%207[2003 c 322 § 7]; ]

== 70A.420.080 - Certification required to perform lead-based paint activities—Certificate revocation—Penalties.
. The department is designated as the official agency of this state for purposes of cooperating with, and implementing the state lead-based paint activities program under the jurisdiction of the United States environmental protection agency.

. No individual or firm can perform, offer, or claim to perform lead-based paint activities without certification from the department to conduct these activities.

. The department may deny, suspend, or revoke a certificate for failure to comply with the requirements of this chapter or any rule adopted under this chapter. No person whose certificate is revoked under this chapter shall be eligible to apply for a certificate for one year from the effective date of the final order of revocation. A certificate may be denied, suspended, or revoked on any of the following grounds:

.. A risk assessor, inspector, contractor, project designer, worker, dust sampling technician, or renovator violates work practice standards established by the United States environmental protection agency or the United States department of housing and urban development governing work practices and procedures; or

.. The certificate was obtained by error, misrepresentation, or fraud.

. Any person convicted of violating any of the provisions of this chapter is guilty of a misdemeanor. A conviction is an unvacated forfeiture of bail or collateral deposited to secure the defendant's appearance in court, the payment of a fine, a plea of guilty, or a finding of guilt on a violation of this chapter, regardless of whether imposition of sentence is deferred or the penalty is suspended, and shall be treated as a violation conviction for purposes of certification forfeiture under this chapter. Violations of this chapter include:

.. Failure to comply with any requirement of this chapter;

.. Failure or refusal to establish, maintain, provide, copy, or permit access to records or reports as required;

.. Obtaining certification through fraud or misrepresentation;

.. Failure to obtain certification from the department and performing work requiring certification at a jobsite; or

.. Fraudulently obtaining certification and engaging in any lead-based paint activities requiring certification.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2745-S.SL.pdf?cite=2010%20c%20158%20§%206[2010 c 158 § 6]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5586-S.SL.pdf?cite=2003%20c%20322%20§%208[2003 c 322 § 8]; ]

== 70A.420.090 - Chapter contingent on federal action.
. The department's duties under chapter 322, Laws of 2003 are subject to authorization of the state program from the federal government within two years of July 27, 2003. Chapter 322, Laws of 2003 expires if the federal environmental protection agency does not authorize a state program within two years of July 27, 2003.

. The department's duties under chapter 322, Laws of 2003, as amended, are subject to the availability of sufficient funding from the federal government for this purpose. The director or his or her designee shall seek funding of the department's efforts under this chapter from the federal government. By October 15th of each year, the director shall determine if sufficient federal funding has been provided or guaranteed by the federal government. If the director determines sufficient funding has not been provided, the department shall:

.. Cease efforts under this chapter due to the lack of federal funding; and

.. Inform the code reviser that it has ceased its efforts due to the lack of federal funding.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2745-S.SL.pdf?cite=2010%20c%20158%20§%207[2010 c 158 § 7]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5586-S.SL.pdf?cite=2003%20c%20322%20§%209[2003 c 322 § 9]; ]

