= 70A.145 - Water purveyors—Fire suppression water facilities.
:toc:

== 70A.145.010 - Findings and declaration of purpose.
. The legislature finds that historically governmental and nongovernmental water purveyors have played two key public service roles: Providing safe drinking water and providing water for fire protection. This dual function approach is a deeply embedded and state-regulated feature of water system planning, engineering, operation, and maintenance. This dual function enables purveyors to provide these critical public services in a cost-effective way that protects public health and safety, promotes economic development, and supports appropriate land use planning.

. The legislature finds that the provision of integrated, dual function water facilities and services benefits all customers of a purveyor, similar to other benefits provided to water system customers in response to regulation regarding safe drinking water such as treatment and water quality monitoring.

. The legislature finds that water purveyors plan, construct, acquire, operate, and maintain fire suppression water facilities in response to regulatory requirements, including without limitation the public water system coordination act, RCW 70A.100.080, the design of public water systems and water system operations requirements, chapter 246-290 WAC, Parts 3 and 5, the state building code, chapter 19.27 RCW, and the international fire code. The availability of infrastructure and water to fight fires allows for the development and habitability of property, increases property values, and benefits customers and property through lower casualty insurance rates.

. The legislature finds that recent Washington supreme court decisions, including Lane v. City of Seattle, 164 Wn.2d 875 (2008), and City of Tacoma v. City of Bonney Lake, et al., 173 Wn.2d 584 (2012), have created uncertainty and confusion as to the role, responsibilities, cost allocation, and recovery authority of water purveyors. If left unresolved, the absence of legal clarity will adversely affect the availability and condition of fire suppression infrastructure necessary to protect life and property.

. It is the legislature's intent to determine appropriate methods of organizing public services and the authority of water purveyors with respect to critical public services. The legislature further intends this chapter to clarify the authority of water purveyors to provide fire suppression water facilities and services and to recover the costs for those facilities and services. The legislature also intends to provide liability protections appropriate for water purveyors engaged in this vital public service.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201429[2020 c 20 § 1429]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1512-S.SL.pdf?cite=2013%20c%20127%20§%201[2013 c 127 § 1]; ]

== 70A.145.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Fire suppression water facilities" means water supply transmission and distribution facilities, interties, pipes, valves, control systems, lines, storage, pumps, fire hydrants, and other facilities, or any part thereof, used or usable for the delivery of water for fire suppression purposes.

. "Fire suppression water services" or "services" means operation and maintenance of fire suppression water facilities and the delivery of water for fire suppression purposes.

. "Municipal corporation" means any city, town, county, water-sewer district, port district, public utility district, irrigation district, and any other municipal corporation, quasi-municipal corporation, or political subdivision of the state.

. "Purveyor" has the same meaning as set forth in RCW 70A.100.030(4).

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201430[2020 c 20 § 1430]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1512-S.SL.pdf?cite=2013%20c%20127%20§%202[2013 c 127 § 2]; ]

== 70A.145.030 - Cost allocation and recovery.
A purveyor may allocate and recover the costs of fire suppression water facilities and services from all customers as costs of complying with state laws and regulations, or from customers based on service to, benefits conferred upon, and burdens and impacts caused by various classes of customers, or both.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1512-S.SL.pdf?cite=2013%20c%20127%20§%203[2013 c 127 § 3]; ]

== 70A.145.040 - Contracts to provide for facilities and services.
A city, town, or county may contract with purveyors for the provision of fire suppression water facilities, services, or both. The contract may take the form of a franchise agreement, an interlocal agreement pursuant to chapter 39.34 RCW, or an agreement under other contracting authority, and may provide for funding or cost recovery of fire suppression water facilities, services, or both, as the parties may agree.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1512-S.SL.pdf?cite=2013%20c%20127%20§%204[2013 c 127 § 4]; ]

== 70A.145.050 - Payment by counties.
A county is not required to pay for fire suppression water facilities or services except: (1) As a customer of a purveyor; (2) in areas where a county is acting as a purveyor; or (3) where a county has agreed to do so consistent with RCW 70A.145.040.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201431[2020 c 20 § 1431]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1512-S.SL.pdf?cite=2013%20c%20127%20§%205[2013 c 127 § 5]; ]

== 70A.145.060 - Liability protection for fire suppression water facilities and services.
. A purveyor that is a municipal corporation is not liable for any damages that arise out of a fire event and relate to the operation, maintenance, and provision of fire suppression water facilities and services that are located within or outside its corporate boundaries.

. A purveyor that is not a municipal corporation is not liable for any damages that arise out of a fire event and relate to the operation, maintenance, and provision of fire suppression water facilities and services if the purveyor has a description of fire hydrant maintenance measures. The description of fire hydrant maintenance measures must be kept on file by the water purveyor and be available to the public, and may be included within the purveyor's most recently approved water system plan or small water system management program.

. Consistent with RCW 36.55.060, with respect to counties and notwithstanding the provisions of subsections (1) and (2) of this section, agreements or franchises may, as the parties mutually agree, include indemnification, hold harmless, or other risk management provisions under which purveyors indemnify and hold harmless cities, towns, and counties against damages arising from fire suppression activities during fire events. Such provisions are unaffected by subsections (1) and (2) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1512-S.SL.pdf?cite=2013%20c%20127%20§%206[2013 c 127 § 6]; ]

== 70A.145.900 - Liberal construction.
This chapter is exempted from the rule of strict construction and must be liberally construed to give full effect to the objectives and purposes for which it was enacted.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1512-S.SL.pdf?cite=2013%20c%20127%20§%207[2013 c 127 § 7]; ]

== 70A.145.901 - Powers conferred by chapter are supplemental.
. The powers and authority conferred by this chapter are supplemental to powers and authority conferred by other law, and nothing contained in this chapter may be construed as limiting any other powers or authority of any municipal corporation or other entity under applicable law.

. As to water companies that are regulated by the utilities and transportation commission under Title 80 RCW, nothing in this chapter is intended to change or limit the authority or jurisdiction of the utilities and transportation commission.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1512-S.SL.pdf?cite=2013%20c%20127%20§%208[2013 c 127 § 8]; ]

== 70A.145.902 - Ratification of prior acts.
To the extent that they provide for or address funding, cost allocation, and recovery of fire suppression water facilities and services, all ordinances, resolutions, and contracts adopted, entered, implemented, or performed prior to July 28, 2013, are hereby validated, ratified, and confirmed. This chapter must not affect or impair any ordinance, resolution, or contract lawfully entered into prior to July 28, 2013.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1512-S.SL.pdf?cite=2013%20c%20127%20§%209[2013 c 127 § 9]; ]

