= 2.14 - Retirement of judges—Supplemental retirement.
:toc:

== 2.14.010 - Purpose.
. The purpose of this chapter is to provide a supplemental retirement benefit to judges who are elected or appointed under chapter 2.04, 2.06, or 2.08 RCW and who are members of the public employees' retirement system for their service as a judge.

. This chapter may be known and cited as the judicial retirement account act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c109.pdf?cite=1988%20c%20109%20§%2012[1988 c 109 § 12]; ]

== 2.14.020 - Definitions.
The definitions in this section apply throughout this chapter.

. "Plan" means the judicial retirement account plan.

. "Principal account" means the judicial retirement principal account.

. "Member" means a judge participating in the judicial retirement account plan.

. "Administrative account" means the judicial retirement administrative account.

. "Accumulated contributions" means the total amount contributed to a member's account under RCW 2.14.090 (1) and (2), together with any interest and earnings that have been credited to the member's account.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c109.pdf?cite=1988%20c%20109%20§%2013[1988 c 109 § 13]; ]

== 2.14.030 - Judicial retirement account plan established.
The judicial retirement account plan is established for judges appointed or elected under chapter 2.04, 2.06, or 2.08 RCW and who are members of the public employees' retirement system for their service as a judge.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c109.pdf?cite=1988%20c%20109%20§%2014[1988 c 109 § 14]; ]

== 2.14.040 - Administration of plan.
The administrator for the courts, under the direction of the board for judicial administration, shall administer the plan. The administrator shall:

. Deposit or invest contributions to the plan consistent with RCW 2.14.080;

. Credit investment earnings or interest to individual judicial retirement accounts consistent with RCW 2.14.070;

. Keep or cause to be kept full and adequate accounts and records of the assets, obligations, transactions, and affairs of any judicial retirement accounts created under this chapter; and

. Adopt rules necessary to carry out this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%201[1998 c 245 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c109.pdf?cite=1988%20c%20109%20§%2015[1988 c 109 § 15]; ]

== 2.14.050 - Administrator—Discharge of duties.
The administrator for the courts shall be deemed to stand in a fiduciary relationship to the members participating in the plan and shall discharge his or her duties in good faith and with that diligence, care, and skill which ordinary prudent persons would exercise under similar circumstances in like positions.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c109.pdf?cite=1988%20c%20109%20§%2016[1988 c 109 § 16]; ]

== 2.14.060 - Judicial retirement principal account—Creation—Transfer of deficiencies—Contributions—Use.
The judicial retirement principal account is created in the state treasury. Any deficiency in the judicial retirement administrative account caused by an excess of administrative expenses disbursed from that account over earnings of investments of balances credited to that account shall be transferred to that account from the principal account.

The contributions under *section 19 of this act shall be paid into the principal account and shall be sufficient to cover costs of administration and staffing in addition to such other amounts as determined by the administrator for the courts. The principal account shall be used to carry out the purposes of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c109.pdf?cite=1988%20c%20109%20§%2017[1988 c 109 § 17]; ]

== 2.14.070 - Judicial retirement administrative account—Creation—Use—Excess balance—Deficiencies.
The judicial retirement administrative account is created in the state treasury. All expenses of the administrator for the courts under this chapter, including staffing and administrative expenses, shall be paid out of the administrative account. Any excess balance of this account over administrative expenses disbursed from this account shall be transferred to the principal account. Any deficiency in the administrative account caused by an excess of administrative expenses disbursed from this account over the excess balance of this account shall be transferred to this account from the principal account.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1058-S.SL.pdf?cite=1991%20sp.s.%20c%2013%20§%2070[1991 sp.s. c 13 § 70]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c109.pdf?cite=1988%20c%20109%20§%2018[1988 c 109 § 18]; ]

== 2.14.080 - Duties of administrator—Investments and earnings.
. The administrator for the courts shall:

.. Deposit or invest the contributions under RCW 2.14.090 in a credit union, savings and loan association, bank, or mutual savings bank;

.. Purchase life insurance, shares of an investment company, or fixed and/or variable annuity contracts from any insurance company or investment company licensed to contract business in this state; or

.. Invest in any of the class of investments described in RCW 43.84.150.

. The state investment board or the department of retirement systems, at the request of the administrator for the courts, may invest moneys in the principal account. Moneys invested by the investment board shall be invested in accordance with RCW 43.84.150. Moneys invested by the department of retirement systems shall be invested in accordance with applicable law. Except as provided in RCW 43.33A.160 or as necessary to pay a pro rata share of expenses incurred by the department of retirement systems, one hundred percent of all earnings from these investments, exclusive of investment income pursuant to RCW 43.84.080, shall accrue directly to the principal account.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2192-S.SL.pdf?cite=1996%20c%2039%20§%2020[1996 c 39 § 20]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1058-S.SL.pdf?cite=1991%20sp.s.%20c%2013%20§%20103[1991 sp.s. c 13 § 103]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c139.pdf?cite=1989%20c%20139%20§%203[1989 c 139 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c109.pdf?cite=1988%20c%20109%20§%2019[1988 c 109 § 19]; ]

== 2.14.090 - Funding of plan—Contributions.
The plan shall be funded as provided in this section.

. Two and one-half percent shall be deducted from each member's salary.

. The state, as employer, shall contribute an equal amount on a monthly basis.

. The contributions shall be collected by the administrator for the courts and deposited in the member's account within the principal account.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c109.pdf?cite=1988%20c%20109%20§%2020[1988 c 109 § 20]; ]

== 2.14.100 - Contributions—Distribution upon member's separation—Exemption from taxation and judicial process—Assignability—Exceptions.
. A member who separates from judicial service for any reason is entitled to receive a lump sum distribution of the member's accumulated contributions. The administrator for the courts may adopt rules establishing other payment options, in addition to lump sum distributions, if the other payment options conform to the requirements of the federal internal revenue code.

. The right of a person to receive a payment under this chapter and the moneys in the accounts created under this chapter are exempt from any state, county, municipal, or other local tax and are not subject to execution, garnishment, attachment, the operation of bankruptcy or insolvency law, or any other process of law whatsoever and is not assignable, except as is otherwise specifically provided in this section.

. If a judgment, decree or other order, including a court-approved property settlement agreement, that relates to the provision of child support, spousal maintenance, or the marital property rights of a spouse or former spouse, child, or other dependent of a member is made pursuant to the domestic relations law of the state of Washington or such order issued by a court of competent jurisdiction in another state or country, that has been registered or otherwise made enforceable in this state, then the amount of the member's accumulated contributions shall be paid in the manner and to the person or persons so directed in the domestic relations order. However, this subsection does not permit or require a benefit to be paid or to be provided that is not otherwise available under the terms of this chapter or any rules adopted under this chapter. The administrator for the courts shall establish reasonable procedures for determining the status or any such decree or order and for effectuating distribution pursuant to the domestic relations order.

. The administrator for the courts may pay from a member's accumulated contributions the amount that the administrator finds is lawfully demanded under a levy issued by the internal revenue service with respect to that member or is sought to be collected by the United States government under a judgment resulting from an unpaid tax assessment against the member.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5918.SL.pdf?cite=2007%20c%20108%20§%201[2007 c 108 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c109.pdf?cite=1988%20c%20109%20§%2021[1988 c 109 § 21]; ]

== 2.14.110 - Payment of contributions upon member's death.
If a member dies, the amount of the accumulated contributions standing to the member's credit at the time of the member's death, subject to the provisions of chapter 26.16 RCW, shall be paid to the member's estate, or such person or persons, trust, or organization as the member has nominated by written designation duly executed and filed with the administrative office of the courts. If there is no such designated person or persons still living at the time of the member's death, the member's accumulated contributions shall be paid to the member's surviving spouse as if in fact the spouse had been nominated by written designation or, if there is no such surviving spouse, then to the member's legal representatives.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5918.SL.pdf?cite=2007%20c%20108%20§%202[2007 c 108 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1668.SL.pdf?cite=2005%20c%20282%20§%201[2005 c 282 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2333.SL.pdf?cite=1996%20c%2042%20§%201[1996 c 42 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c109.pdf?cite=1988%20c%20109%20§%2022[1988 c 109 § 22]; ]

== 2.14.115 - Discontinuing plan contributions—One-time irrevocable election.
Beginning January 1, 2007, through December 31, 2007, any member of the public employees' retirement system eligible to participate in the judicial retirement account plan under this chapter may make a one-time irrevocable election, filed in writing with the member's employer, the department of retirement systems, and the administrative office of the courts, to discontinue future contributions to the judicial retirement account plan in lieu of prospective contribution and benefit provisions under chapter 189, Laws of 2006.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2691-S.SL.pdf?cite=2006%20c%20189%20§%201[2006 c 189 § 1]; ]

== 2.14.900 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%208[2009 c 521 § 8]; ]

