= 2.20 - Magistrates.
:toc:

== 2.20.010 - Magistrate defined.
A magistrate is an officer having power to issue a warrant for the arrest of a person charged with the commission of a crime.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c53.pdf?cite=1891%20c%2053%20§%201[1891 c 53 § 1]; RRS § 50; ]

== 2.20.020 - Who are magistrates.
The following persons are magistrates:

. The justices of the supreme court.

. The judges of the court of appeals.

. The superior judges, and district judges.

. All municipal officers authorized to exercise the powers and perform the duties of district judges.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c202.pdf?cite=1987%20c%20202%20§%20103[1987 c 202 § 103]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c81.pdf?cite=1971%20c%2081%20§%209[1971 c 81 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c53.pdf?cite=1891%20c%2053%20§%202[1891 c 53 § 2]; RRS § 51; ]

== 2.20.030 - Issuance of search warrants by district and municipal court judges—Jurisdiction in more than one county.
Any district or municipal court judge, in the county in which the offense is alleged to have occurred, may issue a search warrant for any person or evidence located anywhere within the state. If the jurisdiction of a district or municipal court encompasses all or part of more than one county, a judge for that district or municipal court may issue a search warrant for any person or evidence located anywhere within the state as long as the county in which the offense is alleged to have occurred is one of the counties encompassed within that court's jurisdiction.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2752-S.SL.pdf?cite=2018%20c%2050%20§%201[2018 c 50 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6279-S.SL.pdf?cite=2014%20c%2093%20§%202[2014 c 93 § 2]; ]

