= 2.30 - Therapeutic courts.
:toc:

== 2.30.010 - Findings—Scope of therapeutic court programs.
. The legislature finds that judges in the trial courts throughout the state effectively utilize what are known as therapeutic courts to remove a defendant's or respondent's case from the criminal and civil court traditional trial track and allow those defendants or respondents the opportunity to obtain treatment services to address particular issues that may have contributed to the conduct that led to their arrest or other issues before the court. Trial courts have proved adept at creative approaches in fashioning a wide variety of therapeutic courts addressing the spectrum of social issues that can contribute to criminal activity and engagement with the child welfare system.

. The legislature further finds that by focusing on the specific individual's needs, providing treatment for the issues presented, and ensuring rapid and appropriate accountability for program violations, therapeutic courts may decrease recidivism, improve the safety of the community, and improve the life of the program participant and the lives of the participant's family members by decreasing the severity and frequency of the specific behavior addressed by the therapeutic court.

. The legislature recognizes the inherent authority of the judiciary under Article IV, section 1 of the state Constitution to establish therapeutic courts, and the outstanding contribution to the state and local communities made by the establishment of therapeutic courts and desires to provide a general provision in statute acknowledging and encouraging the judiciary to provide for therapeutic court programs to address the particular needs within a given judicial jurisdiction.

. Therapeutic court programs may include, but are not limited to:

.. Adult drug court;

.. Juvenile drug court;

.. Family dependency treatment court or family drug court;

.. Mental health court, which may include participants with developmental disabilities;

.. DUI court;

.. Veterans treatment court;

.. Truancy court;

.. Domestic violence court;

.. Gambling court;

.. Community court;

.. Homeless court;

.. Treatment, responsibility, and accountability on campus (Back on TRAC) court.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=2015%20c%20291%20§%201[2015 c 291 § 1]; ]

== 2.30.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Emerging best practice" or "promising practice" means a program or practice that, based on statistical analyses or a well- established theory of change, shows potential for meeting the evidence-based or research-based criteria, which may include the use of a program that is evidence-based for outcomes other than those listed in this section.

. "Evidence-based" means a program or practice that: (a) Has been tested in heterogeneous or intended populations with multiple randomized, or statistically controlled evaluations, or both; or one large multiple site randomized, or statistically controlled evaluation, or both, where the weight of the evidence from a systemic review demonstrates sustained improvements in at least one outcome; or (b) may be implemented with a set of procedures to allow successful replication in Washington and, when possible, is determined to be cost-beneficial.

. "Government authority" means prosecutor or other representative initiating action leading to a proceeding in therapeutic court.

. "Participant" means an accused person, offender, or respondent in the judicial proceeding.

. "Research-based" means a program or practice that has been tested with a single randomized, or statistically controlled evaluation, or both, demonstrating sustained desirable outcomes; or where the weight of the evidence from a systemic review supports sustained outcomes as described in this subsection but does not meet the full criteria for evidence-based.

. "Specialty court" and "therapeutic court" both mean a court utilizing a program or programs structured to achieve both a reduction in recidivism and an increase in the likelihood of rehabilitation, or to reduce child abuse and neglect, out-of-home placements of children, termination of parental rights, and substance abuse and mental health symptoms among parents or guardians and their children through continuous and intense judicially supervised treatment and the appropriate use of services, sanctions, and incentives.

. "Therapeutic court personnel" means the staff of a therapeutic court including, but not limited to: Court and clerk personnel with therapeutic court duties, prosecuting attorneys, the attorney general or his or her representatives, defense counsel, monitoring personnel, and others acting within the scope of therapeutic court duties.

. "Trial court" means a superior court authorized under this title or a district or municipal court authorized under Title 3 or 35 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1388-S.SL.pdf?cite=2018%20c%20201%20§%209001[2018 c 201 § 9001]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=2015%20c%20291%20§%202[2015 c 291 § 2]; ]

== 2.30.030 - Therapeutic courts authorized—Establishment of processes—Determination of eligibility—Persons not eligible—Use of best practices—Dependency matters—Foreign law limitations.
. Every trial and juvenile court in the state of Washington is authorized and encouraged to establish and operate therapeutic courts. Therapeutic courts, in conjunction with the government authority and subject matter experts specific to the focus of the therapeutic court, develop and process cases in ways that depart from traditional judicial processes to allow defendants or respondents the opportunity to obtain treatment services to address particular issues that may have contributed to the conduct that led to their arrest or involvement in the child welfare system in exchange for resolution of the case or charges. In criminal cases, the consent of the prosecutor is required.

. While a therapeutic court judge retains the discretion to decline to accept a case into the therapeutic court, and while a therapeutic court retains discretion to establish processes and determine eligibility for admission to the therapeutic court process unique to their community and jurisdiction, the effectiveness and credibility of any therapeutic court will be enhanced when the court implements evidence-based practices, research-based practices, emerging best practices, or promising practices that have been identified and accepted at the state and national levels. Promising practices, emerging best practices, and/or research-based programs are authorized where determined by the court to be appropriate. As practices evolve, the trial court shall regularly assess the effectiveness of its program and the methods by which it implements and adopts new best practices.

. Except under special findings by the court, the following individuals are not eligible for participation in therapeutic courts:

.. Individuals who are currently charged or who have been previously convicted of a serious violent offense or sex offense as defined in RCW 9.94A.030;

.. Individuals who are currently charged with an offense alleging intentional discharge, threat to discharge, or attempt to discharge a firearm in furtherance of the offense;

.. Individuals who are currently charged with or who have been previously convicted of vehicular homicide or an equivalent out-of- state offense; or

.. Individuals who are currently charged with or who have been previously convicted of: An offense alleging substantial bodily harm or great bodily harm as defined in RCW 9A.04.110, or death of another person.

. Any jurisdiction establishing a therapeutic court shall endeavor to incorporate the therapeutic court principles of best practices as recognized by state and national therapeutic court organizations in structuring a particular program, which may include:

.. Determining the population;

.. Performing a clinical assessment;

.. Developing the treatment plan;

.. Monitoring the participant, including any appropriate testing;

.. Forging agency, organization, and community partnerships;

.. Taking a judicial leadership role;

.. Developing case management strategies;

.. Addressing transportation, housing, and subsistence issues;

.. Evaluating the program;

.. Ensuring a sustainable program.

. Upon a showing of indigence under RCW 10.101.010, fees may be reduced or waived.

. The health care authority shall furnish services to therapeutic courts addressing dependency matters where substance abuse or mental health are an issue unless the court contracts with providers outside of the health care authority.

. Any jurisdiction that has established more than one therapeutic court under this chapter may combine the functions of these courts into a single therapeutic court.

. Nothing in this section prohibits a district or municipal court from ordering treatment or other conditions of sentence or probation following a conviction, without the consent of either the prosecutor or defendant.

. No therapeutic or specialty court may be established specifically for the purpose of applying foreign law, including foreign criminal, civil, or religious law, that is otherwise not required by treaty.

. No therapeutic or specialty court established by court rule shall enforce a foreign law, if doing so would violate a right guaranteed by the Constitution of this state or of the United States.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1388-S.SL.pdf?cite=2018%20c%20201%20§%209002[2018 c 201 § 9002]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=2015%20c%20291%20§%203[2015 c 291 § 3]; ]

== 2.30.040 - Funding—Federal funding—Use of state moneys.
Jurisdictions may seek federal funding available to support the operation of its therapeutic court and associated services and must match, on a dollar-for-dollar basis, state moneys allocated for therapeutic courts with local cash or in-kind resources. Moneys allocated by the state may be used to supplement, not supplant other federal, state, and local funds for therapeutic courts. However, until June 30, 2016, no match is required for state moneys expended for the administrative and overhead costs associated with the operation of a therapeutic court authorized under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=2015%20c%20291%20§%204[2015 c 291 § 4]; ]

== 2.30.050 - Courts authorized to work cooperatively.
Individual trial courts are authorized and encouraged to establish multijurisdictional partnerships and/or interlocal agreements under RCW 39.34.180 to enhance and expand the coverage area of the therapeutic court. Specifically, district and municipal courts may work cooperatively with each other and with the superior courts to identify and implement nontraditional case processing methods which can eliminate traditional barriers that decrease judicial efficiency.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=2015%20c%20291%20§%206[2015 c 291 § 6]; ]

== 2.30.060 - Authorization for therapeutic courts existing on July 24, 2015.
Any therapeutic court meeting the definition of therapeutic court in RCW 2.30.020 and existing on July 24, 2015, continues to be authorized.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=2015%20c%20291%20§%207[2015 c 291 § 7]; ]

== 2.30.100 - Early childhood court programs—Authorized.
. [Empty]
.. A superior court may establish an early childhood court program to serve the needs of infants and toddlers who are under the age of three at the time the case enters the program and dependent pursuant to chapter 13.34 RCW.

.. An early childhood court program is a therapeutic court as defined in this chapter that provides an intensive court process for families with a child under age three who has been found dependent pursuant to chapter 13.34 RCW. To be eligible for the early childhood court program, a parent must have a child under age three that is dependent pursuant to chapter 13.34 RCW at the time the case enters the early childhood court program. The case may remain in the early childhood court program after the child is age three or older if the child is still dependent pursuant to chapter 13.34 RCW.

. If a superior court creates an early childhood court program, it shall incorporate the following core components into the program:

.. The court shall obtain a memorandum of understanding or other agreement with the department of children, youth, and families developed in collaboration with counsel for parents and children that outlines how the two entities will coordinate and collaborate to implement the core components overall.

.. A community coordinator who may be employed by the courts, the county, or a nonprofit entity and who is a person with experience and training in diversity, equity, and inclusion measures and is dedicated to:

... Facilitating real-time information sharing and collaboration among cross-sector professionals participating in the early childhood court program;

... Coordinating and participating in family team meetings;

... Identifying community-based resources and supporting the family's connection to these resources;

... Building relationships and forming new partnerships across traditional and nontraditional services and systems;

.. Identifying training needs of early childhood court professionals and facilitating the provision of training;

.. Supporting the convening of community team meetings; and

.. Performing the tasks outlined in this subsection describing the core components of an early childhood court program unless otherwise specified.

.. A community team established by the court and consisting of stakeholders to the court that serve as an advisory body to the court and who implement the early childhood court program. The community team shall include diverse membership to include, but not be limited to, former parent participants, foster parents, parent and child advocates, an attorney for parents, a department of children, youth, and families caseworker, and a judicial officer. The community team aims to:

... Foster a learning environment and encourage an interdisciplinary approach to meeting the needs of young children and families;

... Identify and respond to challenges to accessing resources and needed systems reforms;

... Support multidisciplinary trainings; and

... Recommend local court policies and procedures to improve families receipt of equitable and timely access to resources and remedial services for the parent and child.

.. More frequent status hearings than the review hearings required under RCW 13.34.138 established by the judicial officer, these status hearings are separate from the review hearings required under RCW 13.34.138 and are intended to provide additional support to the family.

.. A community coordinator that serves as a liaison between the court and community-based resources to identify community-based resources, identify barriers to engagement, and collaborate with stakeholders to connect families to assessments and referrals. The community coordinator shall facilitate connecting parents with informal and formal social supports, including but not limited to peer, community, and cultural supports.

.. Family team meetings neutrally facilitated by the community coordinator. The family team may include all parties to the case and other people or other service providers identified by the parent to be part of the support system for the parent involved. The family team engages the parents, and the attorney for the parent, in their case plan and expediently addresses family needs and access to services and support.

.. Ensuring that parents are critical participants in the early childhood court program. Having experienced and culturally informed professionals supporting and working with families involved in the dependency court system is critical to successful reunification of families. The court shall aim to foster an environment in which all professionals involved in the early childhood court program increase their awareness of different forms of bias and the trauma and adversity that often accompany poverty, mental health, and substance use by identifying or developing training that increases such awareness.

.. Ensuring that families receive early, consistent, and frequent visitation that is developmentally appropriate for infants and toddlers; minimizes stress and anxiety for both children and parents; and occurs in a safe, comfortable, and unintimidating setting that supports parents to nurture and care for their child.

.. The court shall ensure that the individualized case plan for parents involved in the early childhood court program address protective factors that mitigate or eliminate safety risks to the child.

.. The court should encourage a respectful, strength-based, compassionate approach to working with parents in the context of the early childhood court program.

.. The court shall support the development of agreements that encourage:

... Stakeholders participation in any available statewide structure that supports alignment to the approach of the early childhood court program, cross-site cooperation, and consistency;

... Program data is regularly and continuously reviewed to ensure equity and inform and improve practice; and

... Stakeholder utilization of technical assistance, training, and evaluation to assess effectiveness and improve outcomes.

.. Each early childhood court program must collect and review its data, including data related to race and ethnicity of program participants, to assess its effectiveness and share this data with the oversight board for children, youth, and families established under RCW 43.216.015. The oversight board for children, youth, and families established under RCW 43.216.015 shall share this data and hold or offer to assist in holding statewide meetings to support alignment to the core components and statewide consistency.

.. The caseworker assigned to an early childhood court program must have received training and competency related to cultural antibias , and antiracism.

.. Each early childhood court program must be responsive to community needs and adopt best practices related to family reunification and serving all families, including those who are:

... Black, indigenous, and persons of color;

... Lesbian, gay, bisexual, transgender, and queer; and

... Experiencing disabilities.

.. An attorney for the parent must be present during every meeting of the early childhood court program.

.. Ensuring that parents voluntarily participating in the early childhood court program receive all available and appropriate services.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5331-S2.SL.pdf?cite=2021%20c%20285%20§%202[2021 c 285 § 2]; ]

== 2.30.110 - Early childhood court programs—Judicial officer training.
. Judicial officers who preside over early childhood court program hearings shall participate in required trainings, as follows:

.. An initial, eight-hour training program that can include the topic areas of:

... The benefits to infants and toddlers of secure attachment with primary caregivers;

... A trauma-informed approach;

... The importance of maintaining children within their biological connections;

... The importance of reunification of children with their families;

.. Diversity, equity, and inclusion; and

.. The impact of trauma on child development;

.. After the initial training, annually attend a minimum of eight hours of continuing education of pertinence to the early childhood court program.

. Subject to the availability of amounts appropriated for this specific purpose, the administrative office of the courts shall administer the certification of training requirements.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5331-S2.SL.pdf?cite=2021%20c%20285%20§%203[2021 c 285 § 3]; ]

== 2.30.120 - Early childhood court programs—Evaluation—Provision of assistance.
. Subject to the availability of amounts appropriated for this specific purpose, the administrative office of the courts shall perform, or contract for, an evaluation of the early childhood court program to ensure the quality, accountability, and fidelity of the programs' evidence-based treatment. Any evaluation of the early childhood court program shall be posted on the administrative office of the courts website.

. The administrative office of the courts may provide, or contract for the provision of, training and technical assistance related to program services, consultation and guidance for difficult cases, and ongoing training for court teams.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5331-S2.SL.pdf?cite=2021%20c%20285%20§%204[2021 c 285 § 4]; ]

== 2.30.130 - Early childhood court programs—Transitional provision.
Any early childhood court program in operation as of July 25, 2021, shall have until January 1, 2022, to adjust its practices to comply with RCW 2.30.100 and 2.30.110.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5331-S2.SL.pdf?cite=2021%20c%20285%20§%205[2021 c 285 § 5]; ]

