= 2.30 - Therapeutic courts.
:toc:

== 2.30.010 - Findings—Scope of therapeutic court programs.
. The legislature finds that judges in the trial courts throughout the state effectively utilize what are known as therapeutic courts to remove a defendant's or respondent's case from the criminal and civil court traditional trial track and allow those defendants or respondents the opportunity to obtain treatment services to address particular issues that may have contributed to the conduct that led to their arrest or other issues before the court. Trial courts have proved adept at creative approaches in fashioning a wide variety of therapeutic courts addressing the spectrum of social issues that can contribute to criminal activity and engagement with the child welfare system.

. The legislature further finds that by focusing on the specific individual's needs, providing treatment for the issues presented, and ensuring rapid and appropriate accountability for program violations, therapeutic courts may decrease recidivism, improve the safety of the community, and improve the life of the program participant and the lives of the participant's family members by decreasing the severity and frequency of the specific behavior addressed by the therapeutic court.

. The legislature recognizes the inherent authority of the judiciary under Article IV, section 1 of the state Constitution to establish therapeutic courts, and the outstanding contribution to the state and local communities made by the establishment of therapeutic courts and desires to provide a general provision in statute acknowledging and encouraging the judiciary to provide for therapeutic court programs to address the particular needs within a given judicial jurisdiction.

. Therapeutic court programs may include, but are not limited to:

.. Adult drug court;

.. Juvenile drug court;

.. Family dependency treatment court or family drug court;

.. Mental health court, which may include participants with developmental disabilities;

.. DUI court;

.. Veterans treatment court;

.. Truancy court;

.. Domestic violence court;

.. Gambling court;

.. Community court;

.. Homeless court;

.. Treatment, responsibility, and accountability on campus (Back on TRAC) court.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=2015%20c%20291%20§%201[2015 c 291 § 1]; ]

== 2.30.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Emerging best practice" or "promising practice" means a program or practice that, based on statistical analyses or a well- established theory of change, shows potential for meeting the evidence-based or research-based criteria, which may include the use of a program that is evidence-based for outcomes other than those listed in this section.

. "Evidence-based" means a program or practice that: (a) Has been tested in heterogeneous or intended populations with multiple randomized, or statistically controlled evaluations, or both; or one large multiple site randomized, or statistically controlled evaluation, or both, where the weight of the evidence from a systemic review demonstrates sustained improvements in at least one outcome; or (b) may be implemented with a set of procedures to allow successful replication in Washington and, when possible, is determined to be cost-beneficial.

. "Government authority" means prosecutor or other representative initiating action leading to a proceeding in therapeutic court.

. "Participant" means an accused person, offender, or respondent in the judicial proceeding.

. "Research-based" means a program or practice that has been tested with a single randomized, or statistically controlled evaluation, or both, demonstrating sustained desirable outcomes; or where the weight of the evidence from a systemic review supports sustained outcomes as described in this subsection but does not meet the full criteria for evidence-based.

. "Specialty court" and "therapeutic court" both mean a court utilizing a program or programs structured to achieve both a reduction in recidivism and an increase in the likelihood of rehabilitation, or to reduce child abuse and neglect, out-of-home placements of children, termination of parental rights, and substance abuse and mental health symptoms among parents or guardians and their children through continuous and intense judicially supervised treatment and the appropriate use of services, sanctions, and incentives.

. "Therapeutic court personnel" means the staff of a therapeutic court including, but not limited to: Court and clerk personnel with therapeutic court duties, prosecuting attorneys, the attorney general or his or her representatives, defense counsel, monitoring personnel, and others acting within the scope of therapeutic court duties.

. "Trial court" means a superior court authorized under this title or a district or municipal court authorized under Title 3 or 35 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1388-S.SL.pdf?cite=2018%20c%20201%20§%209001[2018 c 201 § 9001]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=2015%20c%20291%20§%202[2015 c 291 § 2]; ]

== 2.30.030 - Therapeutic courts authorized—Establishment of processes—Determination of eligibility—Persons not eligible—Use of best practices—Dependency matters—Foreign law limitations.
. Every trial and juvenile court in the state of Washington is authorized and encouraged to establish and operate therapeutic courts. Therapeutic courts, in conjunction with the government authority and subject matter experts specific to the focus of the therapeutic court, develop and process cases in ways that depart from traditional judicial processes to allow defendants or respondents the opportunity to obtain treatment services to address particular issues that may have contributed to the conduct that led to their arrest or involvement in the child welfare system in exchange for resolution of the case or charges. In criminal cases, the consent of the prosecutor is required.

. While a therapeutic court judge retains the discretion to decline to accept a case into the therapeutic court, and while a therapeutic court retains discretion to establish processes and determine eligibility for admission to the therapeutic court process unique to their community and jurisdiction, the effectiveness and credibility of any therapeutic court will be enhanced when the court implements evidence-based practices, research-based practices, emerging best practices, or promising practices that have been identified and accepted at the state and national levels. Promising practices, emerging best practices, and/or research-based programs are authorized where determined by the court to be appropriate. As practices evolve, the trial court shall regularly assess the effectiveness of its program and the methods by which it implements and adopts new best practices.

. Except under special findings by the court, the following individuals are not eligible for participation in therapeutic courts:

.. Individuals who are currently charged or who have been previously convicted of a serious violent offense or sex offense as defined in RCW 9.94A.030;

.. Individuals who are currently charged with an offense alleging intentional discharge, threat to discharge, or attempt to discharge a firearm in furtherance of the offense;

.. Individuals who are currently charged with or who have been previously convicted of vehicular homicide or an equivalent out-of- state offense; or

.. Individuals who are currently charged with or who have been previously convicted of: An offense alleging substantial bodily harm or great bodily harm as defined in RCW 9A.04.110, or death of another person.

. Any jurisdiction establishing a therapeutic court shall endeavor to incorporate the therapeutic court principles of best practices as recognized by state and national therapeutic court organizations in structuring a particular program, which may include:

.. Determining the population;

.. Performing a clinical assessment;

.. Developing the treatment plan;

.. Monitoring the participant, including any appropriate testing;

.. Forging agency, organization, and community partnerships;

.. Taking a judicial leadership role;

.. Developing case management strategies;

.. Addressing transportation, housing, and subsistence issues;

.. Evaluating the program;

.. Ensuring a sustainable program.

. Upon a showing of indigence under RCW 10.101.010, fees may be reduced or waived.

. The health care authority shall furnish services to therapeutic courts addressing dependency matters where substance abuse or mental health are an issue unless the court contracts with providers outside of the health care authority.

. Any jurisdiction that has established more than one therapeutic court under this chapter may combine the functions of these courts into a single therapeutic court.

. Nothing in this section prohibits a district or municipal court from ordering treatment or other conditions of sentence or probation following a conviction, without the consent of either the prosecutor or defendant.

. No therapeutic or specialty court may be established specifically for the purpose of applying foreign law, including foreign criminal, civil, or religious law, that is otherwise not required by treaty.

. No therapeutic or specialty court established by court rule shall enforce a foreign law, if doing so would violate a right guaranteed by the Constitution of this state or of the United States.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1388-S.SL.pdf?cite=2018%20c%20201%20§%209002[2018 c 201 § 9002]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=2015%20c%20291%20§%203[2015 c 291 § 3]; ]

== 2.30.040 - Funding—Federal funding—Use of state moneys.
Jurisdictions may seek federal funding available to support the operation of its therapeutic court and associated services and must match, on a dollar-for-dollar basis, state moneys allocated for therapeutic courts with local cash or in-kind resources. Moneys allocated by the state may be used to supplement, not supplant other federal, state, and local funds for therapeutic courts. However, until June 30, 2016, no match is required for state moneys expended for the administrative and overhead costs associated with the operation of a therapeutic court authorized under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=2015%20c%20291%20§%204[2015 c 291 § 4]; ]

== 2.30.050 - Courts authorized to work cooperatively.
Individual trial courts are authorized and encouraged to establish multijurisdictional partnerships and/or interlocal agreements under RCW 39.34.180 to enhance and expand the coverage area of the therapeutic court. Specifically, district and municipal courts may work cooperatively with each other and with the superior courts to identify and implement nontraditional case processing methods which can eliminate traditional barriers that decrease judicial efficiency.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=2015%20c%20291%20§%206[2015 c 291 § 6]; ]

== 2.30.060 - Authorization for therapeutic courts existing on July 24, 2015.
Any therapeutic court meeting the definition of therapeutic court in RCW 2.30.020 and existing on July 24, 2015, continues to be authorized.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5107.SL.pdf?cite=2015%20c%20291%20§%207[2015 c 291 § 7]; ]

