= 2.43 - Interpreters for non-English-speaking persons.
:toc:

== 2.43.010 - Legislative intent.
It is hereby declared to be the policy of this state to secure the rights, constitutional or otherwise, of persons who, because of a non-English-speaking cultural background, are unable to readily understand or communicate in the English language, and who consequently cannot be fully protected in legal proceedings unless qualified interpreters are available to assist them.

It is the intent of the legislature in the passage of this chapter to provide for the use and procedure for the appointment of such interpreters. Nothing in chapter 358, Laws of 1989 abridges the parties' rights or obligations under other statutes or court rules or other law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c358.pdf?cite=1989%20c%20358%20§%201[1989 c 358 § 1]; ]

== 2.43.020 - Definitions.
As used in this chapter:

. "Appointing authority" means the presiding officer or similar official of any court, department, board, commission, agency, licensing authority, or legislative body of the state or of any political subdivision thereof.

. "Certified interpreter" means an interpreter who is certified by the administrative office of the courts.

. "Legal proceeding" means a proceeding in any court in this state, grand jury hearing, or hearing before an inquiry judge, or before an administrative board, commission, agency, or licensing body of the state or any political subdivision thereof.

. "Non-English-speaking person" means any person involved in a legal proceeding who cannot readily speak or understand the English language, but does not include hearing-impaired persons who are covered under chapter 2.42 RCW.

. "Qualified interpreter" means a person who is able readily to interpret or translate spoken and written English for non-English-speaking persons and to interpret or translate oral or written statements of non-English-speaking persons into spoken English.

. "Registered interpreter" means an interpreter who is registered by the administrative office of the courts.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2518-S.SL.pdf?cite=2010%20c%20190%20§%202[2010 c 190 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1668.SL.pdf?cite=2005%20c%20282%20§%202[2005 c 282 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c358.pdf?cite=1989%20c%20358%20§%202[1989 c 358 § 2]; ]

== 2.43.030 - Appointment of interpreter.
. Whenever an interpreter is appointed to assist a non-English-speaking person in a legal proceeding, the appointing authority shall, in the absence of a written waiver by the person, appoint a certified or a qualified interpreter to assist the person throughout the proceedings.

.. Except as otherwise provided for in (b) of this subsection, the interpreter appointed shall be a qualified interpreter.

.. Beginning on July 1, 1990, when a non-English-speaking person is a party to a legal proceeding, or is subpoenaed or summoned by an appointing authority or is otherwise compelled by an appointing authority to appear at a legal proceeding, the appointing authority shall use the services of only those language interpreters who have been certified by the administrative office of the courts, unless good cause is found and noted on the record by the appointing authority. For purposes of chapter 358, Laws of 1989, "good cause" includes but is not limited to a determination that:

... Given the totality of the circumstances, including the nature of the proceeding and the potential penalty or consequences involved, the services of a certified interpreter are not reasonably available to the appointing authority; or

... The current list of certified interpreters maintained by the administrative office of the courts does not include an interpreter certified in the language spoken by the non-English-speaking person.

.. Except as otherwise provided in this section, when a non-English-speaking person is involved in a legal proceeding, the appointing authority shall appoint a qualified interpreter.

. If good cause is found for using an interpreter who is not certified or if a qualified interpreter is appointed, the appointing authority shall make a preliminary determination, on the basis of testimony or stated needs of the non-English-speaking person, that the proposed interpreter is able to interpret accurately all communications to and from such person in that particular proceeding. The appointing authority shall satisfy itself on the record that the proposed interpreter:

.. Is capable of communicating effectively with the court or agency and the person for whom the interpreter would interpret; and

.. Has read, understands, and will abide by the code of ethics for language interpreters established by court rules.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1668.SL.pdf?cite=2005%20c%20282%20§%203[2005 c 282 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c183.pdf?cite=1990%20c%20183%20§%201[1990 c 183 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c358.pdf?cite=1989%20c%20358%20§%203[1989 c 358 § 3]; ]

== 2.43.040 - Fees and expenses—Cost of providing interpreter—Reimbursement.
. Interpreters appointed according to this chapter are entitled to a reasonable fee for their services and shall be reimbursed for actual expenses which are reasonable as provided in this section.

. In all legal proceedings in which the non-English-speaking person is a party, or is subpoenaed or summoned by the appointing authority or is otherwise compelled by the appointing authority to appear, including criminal proceedings, grand jury proceedings, coroner's inquests, mental health commitment proceedings, and other legal proceedings initiated by agencies of government, the cost of providing the interpreter shall be borne by the governmental body initiating the legal proceedings.

. In other legal proceedings, the cost of providing the interpreter shall be borne by the non-English-speaking person unless such person is indigent according to adopted standards of the body. In such a case the cost shall be an administrative cost of the governmental body under the authority of which the legal proceeding is conducted.

. The cost of providing the interpreter is a taxable cost of any proceeding in which costs ordinarily are taxed.

. Subject to the availability of funds specifically appropriated therefor, the administrative office of the courts shall reimburse the appointing authority for up to one-half of the payment to the interpreter where an interpreter is appointed by a judicial officer in a proceeding before a court at public expense and:

.. The interpreter appointed is an interpreter certified by the administrative office of the courts or is a qualified interpreter registered by the administrative office of the courts in a noncertified language, or where the necessary language is not certified or registered, the interpreter has been qualified by the judicial officer pursuant to this chapter;

.. The court conducting the legal proceeding has an approved language assistance plan that complies with RCW 2.43.090; and

.. The fee paid to the interpreter for services is in accordance with standards established by the administrative office of the courts.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2176-S2.SL.pdf?cite=2008%20c%20291%20§%203[2008 c 291 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c358.pdf?cite=1989%20c%20358%20§%204[1989 c 358 § 4]; ]

== 2.43.050 - Oath.
. Upon certification or registration with the administrative office of the courts, certified or registered interpreters shall take an oath, affirming that the interpreter will make a true interpretation to the person being examined of all the proceedings in a language which the person understands, and that the interpreter will repeat the statements of the person being examined to the court or agency conducting the proceedings, in the English language, to the best of the interpreter's skill and judgment. The administrative office of the courts shall maintain a record of the oath in the same manner that the list of certified and registered interpreters is maintained.

. Before any person serving as an interpreter for the court or agency begins to interpret, the appointing authority shall require the interpreter to state the interpreter's name on the record and whether the interpreter is a certified or registered interpreter. If the interpreter is not a certified or registered interpreter, the interpreter must submit the interpreter's qualifications on the record.

. Before beginning to interpret, every interpreter appointed under this chapter shall take an oath unless the interpreter is a certified or registered interpreter who has taken the oath as required in subsection (1) of this section. The oath must affirm that the interpreter will make a true interpretation to the person being examined of all the proceedings in a language which the person understands, and that the interpreter will repeat the statements of the person being examined to the court or agency conducting the proceedings, in the English language, to the best of the interpreter's skill and judgment.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1285.SL.pdf?cite=2017%20c%2083%20§%202[2017 c 83 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2518-S.SL.pdf?cite=2010%20c%20190%20§%201[2010 c 190 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c358.pdf?cite=1989%20c%20358%20§%205[1989 c 358 § 5]; ]

== 2.43.060 - Waiver of right to interpreter.
. The right to a qualified interpreter may not be waived except when:

.. A non-English-speaking person requests a waiver; and

.. The appointing authority determines on the record that the waiver has been made knowingly, voluntarily, and intelligently.

. Waiver of a qualified interpreter may be set aside and an interpreter appointed, in the discretion of the appointing authority, at any time during the proceedings.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c358.pdf?cite=1989%20c%20358%20§%206[1989 c 358 § 6]; ]

== 2.43.070 - Testing, certification of interpreters.
. Subject to the availability of funds, the administrative office of the courts shall establish and administer a comprehensive testing and certification program for language interpreters.

. The administrative office of the courts shall work cooperatively with community colleges and other private or public educational institutions, and with other public or private organizations to establish a certification preparation curriculum and suitable training programs to ensure the availability of certified interpreters. Training programs shall be made readily available in both eastern and western Washington locations.

. The administrative office of the courts shall establish and adopt standards of proficiency, written and oral, in English and the language to be interpreted.

. The administrative office of the courts shall conduct periodic examinations to ensure the availability of certified interpreters. Periodic examinations shall be made readily available in both eastern and western Washington locations.

. The administrative office of the courts shall compile, maintain, and disseminate a current list of interpreters certified by the office.

. The administrative office of the courts may charge reasonable fees for testing, training, and certification.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1668.SL.pdf?cite=2005%20c%20282%20§%204[2005 c 282 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c358.pdf?cite=1989%20c%20358%20§%207[1989 c 358 § 7]; ]

== 2.43.080 - Code of ethics.
All language interpreters serving in a legal proceeding, whether or not certified or qualified, shall abide by a code of ethics established by supreme court rule.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c358.pdf?cite=1989%20c%20358%20§%208[1989 c 358 § 8]; ]

== 2.43.090 - Language assistance plan—Required for each trial court—Submission of plan to interpreter commission—Report.
. Each trial court organized under this title and Titles 3 and 35 RCW must develop a written language assistance plan to provide a framework for the provision of interpreter services for non-English-speaking persons accessing the court system in both civil and criminal legal matters. The language assistance plan must include, at a minimum, provisions addressing the following:

.. Procedures to identify and assess the language needs of non-English-speaking persons using the court system;

.. Procedures for the appointment of interpreters as required under RCW 2.43.030. Such procedures shall not require the non-English-speaking person to make the arrangements for the interpreter to appear in court;

.. Procedures for notifying court users of the right to and availability of interpreter services. Such information shall be prominently displayed in the courthouse in the five foreign languages that census data indicates are predominate in the jurisdiction;

.. A process for providing timely communication with non-English speakers by all court employees who have regular contact with the public and meaningful access to court services, including access to services provided by the clerk's office;

.. Procedures for evaluating the need for translation of written materials, prioritizing those translation needs, and translating the highest priority materials. These procedures should take into account the frequency of use of forms by the language group, and the cost of orally interpreting the forms;

.. A process for requiring and providing training to judges, court clerks, and other court staff on the requirements of the language assistance plan and how to effectively access and work with interpreters; and

.. A process for ongoing evaluation of the language assistance plan and monitoring of the implementation of the language assistance plan.

. Each court, when developing its language assistance plan, must consult with judges, court administrators and court clerks, interpreters, and members of the community, such as domestic violence organizations, pro bono programs, courthouse facilitators, legal services programs, and/or other community groups whose members speak a language other than English.

. Each court must provide a copy of its language assistance plan to the interpreter commission established by supreme court rule for approval prior to receiving state reimbursement for interpreter costs under this chapter.

. Each court receiving reimbursement for interpreter costs under RCW 2.42.120 or 2.43.040 must provide to the administrative office of the courts by November 15, 2009, a report detailing an assessment of the need for interpreter services for non-English speakers in court-mandated classes or programs, the extent to which interpreter services are currently available for court-mandated classes or programs, and the resources that would be required to ensure that interpreters are provided to non-English speakers in court-mandated classes or programs. The report shall also include the amounts spent annually on interpreter services for fiscal years 2005, 2006, 2007, 2008, and 2009. The administrative office of the courts shall compile these reports and provide them along with the specific reimbursements provided, by court and fiscal year, to the appropriate committees of the legislature by December 15, 2009.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2176-S2.SL.pdf?cite=2008%20c%20291%20§%201[2008 c 291 § 1]; ]

