= 2.48 - State bar act.
:toc:

== 2.48.010 - Objects and powers.
There is hereby created as an agency of the state, for the purpose and with the powers hereinafter set forth, an association to be known as the Washington State Bar Association, hereinafter designated as the state bar, which association shall have a common seal and may sue and be sued, and which may, for the purpose of carrying into effect and promoting the objects of said association, enter into contracts and acquire, hold, encumber and dispose of such real and personal property as is necessary thereto.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c94.pdf?cite=1933%20c%2094%20§%202[1933 c 94 § 2]; RRS § 138-2; ]

== 2.48.020 - First members.
The first members of the Washington State Bar Association shall be all persons now [on June 7, 1933] entitled to practice law in this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c94.pdf?cite=1933%20c%2094%20§%203[1933 c 94 § 3]; RRS § 138-3. FORMER PART OF SECTION:  1933 c 94 § 4; RRS § 138-4 now codified as RCW  2.48.021; ]

== 2.48.021 - New members.
After the organization of the state bar, as herein provided, all persons who are admitted to practice in accordance with the provisions of RCW 2.48.010 through 2.48.180, except judges of courts of record, shall become by that fact active members of the state bar.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c94.pdf?cite=1933%20c%2094%20§%204[1933 c 94 § 4]; RRS § 138-4; ]

== 2.48.030 - Board of governors.
There is hereby constituted a board of governors of the state bar which shall consist of not more than fifteen members, to include: The president of the state bar elected as provided by the bylaws of the association, one member from each congressional district now or hereafter existing in the state elected by secret ballot by mail by the active members residing therein, and such additional members elected as provided by the bylaws of the association. The members of the board of governors shall hold office for three years and until their successors are elected and qualified. Any vacancies in the board of governors shall be filled by the continuing members of the board until the next election, held in accordance with the bylaws of the association.

The board shall not be deemed to be unlawfully constituted and a member of the board shall not be deemed ineligible to serve the remainder of the member's unexpired term on the board solely by reason of the establishment of new or revised boundaries for congressional districts.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c30.pdf?cite=1982%201st%20ex.s.%20c%2030%20§%201[1982 1st ex.s. c 30 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c66.pdf?cite=1972%20ex.s.%20c%2066%20§%201[1972 ex.s. c 66 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c94.pdf?cite=1933%20c%2094%20§%205[1933 c 94 § 5]; RRS § 138-5; ]

== 2.48.035 - Board of governors—Membership—Effect of creation of new congressional districts or boundaries.
The terms of office of members of the board of governors of the state bar who are elected from the various congressional districts shall not be affected by the creation of either new boundaries for congressional districts or additional districts. In such an event, each board member so elected may continue to serve in office for the balance of the term for which he or she was elected or appointed: PROVIDED, That the board member continues to reside within the boundaries of the congressional district as they existed at the time of his or her election or appointment. Vacancies which occur in a board member position during the balance of any such term shall be filled pursuant to RCW 2.48.030, as now or hereafter amended, by a successor who resides within the boundaries of the congressional district from which the member whose office was vacated was elected as they existed at the time of his or her election. At the election immediately preceding expiration of the term of office of each board member provided for in this section following the creation of either new boundaries for congressional districts or additional districts, and thereafter, a successor shall be elected from the congressional district which corresponds in number with the congressional district from which the incumbent was appointed or elected.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c30.pdf?cite=1982%201st%20ex.s.%20c%2030%20§%202[1982 1st ex.s. c 30 § 2]; ]

== 2.48.040 - State bar governed by board of governors.
The state bar shall be governed by the board of governors which shall be charged with the executive functions of the state bar and the enforcement of the provisions of RCW 2.48.010 through 2.48.180 and all rules adopted in pursuance thereof. The members of the board of governors shall receive no salary by virtue of their office.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c94.pdf?cite=1933%20c%2094%20§%206[1933 c 94 § 6]; RRS § 138-6; ]

== 2.48.050 - Powers of governors.
The said board of governors shall have power, in its discretion, from time to time to adopt rules

. concerning membership and the classification thereof into active, inactive and honorary members; and

. concerning the enrollment and privileges of membership; and

. defining the other officers of the state bar, the time, place and method of their selection, and their respective powers, duties, terms of office and compensation; and

. concerning annual and special meetings; and

. concerning the collection, the deposit and the disbursement of the membership and admission fees, penalties, and all other funds; and

. providing for the organization and government of district and/or other local subdivisions of the state bar; and

. providing for all other matters, whether similar to the foregoing or not, affecting in any way whatsoever, the organization and functioning of the state bar. Any such rule may be modified, or rescinded, or a new rule adopted, by a vote of the active members under rules to be prescribed by the board of governors.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c94.pdf?cite=1933%20c%2094%20§%207[1933 c 94 § 7]; RRS § 138-7; ]

== 2.48.060 - Admission and disbarment.
The said board of governors shall likewise have power, in its discretion, from time to time to adopt rules, subject to the approval of the supreme court, fixing the qualifications, requirements and procedure for admission to the practice of law; and, with such approval, to establish from time to time and enforce rules of professional conduct for all members of the state bar; and, with such approval, to appoint boards or committees to examine applicants for admission; and, to investigate, prosecute and hear all causes involving discipline, disbarment, suspension or reinstatement, and make recommendations thereon to the supreme court; and, with such approval, to prescribe rules establishing the procedure for the investigation and hearing of such matters, and establishing county or district agencies to assist therein to the extent provided by such rules: PROVIDED, HOWEVER, That no person who shall have participated in the investigation or prosecution of any such cause shall sit as a member of any board or committee hearing the same.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c94.pdf?cite=1933%20c%2094%20§%208[1933 c 94 § 8]; RRS § 138-8; ]

== 2.48.070 - Admission of veterans.
Any person who shall have graduated from any accredited law school and after such graduation shall have served in the armed forces of the United States of America between December 7, 1941, and the termination of the present World War, may be admitted to the practice of law in the state of Washington and to membership in the Washington State Bar Association, upon motion made before the supreme court of the state of Washington, provided the following is made to appear:

. That the applicant is a person of good moral character over the age of twenty-one years;

. That the applicant, at the time of entering the armed forces of the United States, was a legal resident of the state of Washington;

. That the applicant's service in the armed forces of the United States is or was satisfactory and honorable.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c181.pdf?cite=1945%20c%20181%20§%201[1945 c 181 § 1]; Rem. Supp. 1945 § 138-7A; ]

== 2.48.080 - Admission of veterans—Establishment of requirements if in service.
If an applicant under RCW 2.48.070 through 2.48.110 is, at the time he or she applies for admission to practice law in the state of Washington, still in the armed forces of the United States, he or she may establish the requirements of the proviso in RCW 2.48.070 by a letter or certificate from his or her commanding officer and by the certificates of at least two active members of the Washington state bar association.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%2063[2011 c 336 § 63]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c181.pdf?cite=1945%20c%20181%20§%202[1945 c 181 § 2]; Rem. Supp. 1945 § 138-7B; ]

== 2.48.090 - Admission of veterans—Establishment of requirements if discharged.
If an applicant under RCW 2.48.070 through 2.48.110 is, at the time he or she applies for admission to practice law in the state of Washington, no longer in the armed forces of the United States, he or she may establish the requirements of the proviso in RCW 2.48.070 as follows:

. If he or she shall have been an enlisted person, by producing an honorable discharge, and by the certificates of at least two active members of the Washington state bar association.

. If he or she shall have been an officer, by an affidavit showing that he or she has been relieved from active duty under circumstances other than dishonorable, and by the certificates of at least two active members of the Washington state bar association.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%2064[2011 c 336 § 64]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c181.pdf?cite=1945%20c%20181%20§%203[1945 c 181 § 3]; Rem. Supp. 1945 § 138-7C; ]

== 2.48.100 - Admission of veterans—Effect of disability discharge.
A physical disability discharge shall be considered an honorable discharge unless it be coupled with a dishonorable discharge.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c181.pdf?cite=1945%20c%20181%20§%204[1945 c 181 § 4]; Rem. Supp. 1945 § 138-7D; ]

== 2.48.110 - Admission of veterans—Fees of veterans.
An applicant applying for admission to practice law under the provisions of RCW 2.48.070 through 2.48.090, shall pay the same fees as are required of residents of the state of Washington seeking admission to practice law by examination.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c181.pdf?cite=1945%20c%20181%20§%205[1945 c 181 § 5]; Rem. Supp. 1945 § 138-7E; ]

== 2.48.130 - Membership fee—Active.
The annual membership fees for active members shall be payable on or before February 1st of each year. The board of governors may establish the amount of such annual membership fee to be effective each year: PROVIDED, That written notice of any proposed increase in membership fee shall be sent to active members not less than sixty days prior to the effective date of such increase: PROVIDED FURTHER, That the board of governors may establish the fee at a reduced rate for those who have been active members for less than five years in this state or elsewhere.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c138.pdf?cite=1957%20c%20138%20§%201[1957 c 138 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c256.pdf?cite=1953%20c%20256%20§%201[1953 c 256 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c94.pdf?cite=1933%20c%2094%20§%209[1933 c 94 § 9]; RRS § 138-9; ]

== 2.48.140 - Membership fee—Inactive.
The annual membership fee for inactive members shall be the sum of two dollars, payable on or before the first day of February of each year.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c34.pdf?cite=1955%20c%2034%20§%201[1955 c 34 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c94.pdf?cite=1933%20c%2094%20§%2010[1933 c 94 § 10]; RRS § 138-10; ]

== 2.48.150 - Admission fees.
Applicants for admission to the bar upon accredited certificates or upon examination, not having been admitted to the bar in another state or territory, shall pay a fee of twenty-five dollars and all other applicants a fee of fifty dollars. Said admission fees shall be used to pay the expenses incurred in connection with examining and admitting applicants to the bar, including salaries of examiners, and any balance remaining at the close of each biennium shall be paid to the state treasurer and be by him or her credited to the general fund.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%2065[2011 c 336 § 65]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c94.pdf?cite=1933%20c%2094%20§%2011[1933 c 94 § 11]; RRS § 138-11; ]

== 2.48.160 - Suspension for nonpayment of fees.
Any member failing to pay any fees after the same become due, and after two months' written notice of his or her delinquency, must be suspended from membership in the state bar, but may be reinstated upon payment of accrued fees and such penalties as may be imposed by the board of governors, not exceeding double the amount of the delinquent fee.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%2066[2011 c 336 § 66]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c94.pdf?cite=1933%20c%2094%20§%2012[1933 c 94 § 12]; RRS § 138-12; ]

== 2.48.166 - Admission to or suspension from practice—Noncompliance with support order—Rules.
The Washington state supreme court may provide by rule that no person who has been certified by the department of social and health services as a person who is in noncompliance with a support order or a *residential or visitation order as provided in RCW 74.20A.320 may be admitted to the practice of law in this state, and that any member of the Washington state bar association who has been certified by the department of social and health services as a person who is in noncompliance with a support order or a residential or visitation order as provided in RCW 74.20A.320 shall be immediately suspended from membership. The court's rules may provide for review of an application for admission or reinstatement of membership after the department of social and health services has issued a release stating that the person is in compliance with the order.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20810[1997 c 58 § 810]; ]

== 2.48.170 - Only active members may practice law.
No person shall practice law in this state subsequent to the first meeting of the state bar unless he or she shall be an active member thereof as hereinbefore defined: PROVIDED, That a member of the bar in good standing in any other state or jurisdiction shall be entitled to appear in the courts of this state under such rules as the board of governors may prescribe.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%2067[2011 c 336 § 67]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c94.pdf?cite=1933%20c%2094%20§%2013[1933 c 94 § 13]; RRS § 138-13; ]

== 2.48.180 - Definitions—Unlawful practice a crime—Cause for discipline—Unprofessional conduct—Defense—Injunction—Remedies—Costs—Attorneys' fees—Time limit for action.
. As used in this section:

.. "Legal provider" means an active member in good standing of the state bar, and any other person authorized by the Washington state supreme court to engage in full or limited practice of law;

.. "Nonlawyer" means a person to whom the Washington supreme court has granted a limited authorization to practice law but who practices law outside that authorization, and a person who is not an active member in good standing of the state bar, including persons who are disbarred or suspended from membership;

.. "Ownership interest" means the right to control the affairs of a business, or the right to share in the profits of a business, and includes a loan to the business when the interest on the loan is based upon the income of the business or the loan carries more than a commercially reasonable rate of interest.

. The following constitutes unlawful practice of law:

.. A nonlawyer practices law, or holds himself or herself out as entitled to practice law;

.. A legal provider holds an investment or ownership interest in a business primarily engaged in the practice of law, knowing that a nonlawyer holds an investment or ownership interest in the business;

.. A nonlawyer knowingly holds an investment or ownership interest in a business primarily engaged in the practice of law;

.. A legal provider works for a business that is primarily engaged in the practice of law, knowing that a nonlawyer holds an investment or ownership interest in the business; or

.. A nonlawyer shares legal fees with a legal provider.

. [Empty]
.. Unlawful practice of law is a crime. A single violation of this section is a gross misdemeanor.

.. Each subsequent violation of this section, whether alleged in the same or in subsequent prosecutions, is a class C felony punishable according to chapter 9A.20 RCW.

. Nothing contained in this section affects the power of the courts to grant injunctive or other equitable relief or to punish as for contempt.

. Whenever a legal provider or a person licensed by the state in a business or profession is convicted, enjoined, or found liable for damages or a civil penalty or other equitable relief under this section, the plaintiff's attorney shall provide written notification of the judgment to the appropriate regulatory or disciplinary body or agency.

. A violation of this section is cause for discipline and constitutes unprofessional conduct that could result in any regulatory penalty provided by law, including refusal, revocation, or suspension of a business or professional license, or right or admission to practice. Conduct that constitutes a violation of this section is unprofessional conduct in violation of RCW 18.130.180.

. In a proceeding under this section it is a defense if proven by the defendant by a preponderance of the evidence that, at the time of the offense, the conduct alleged was authorized by the rules of professional conduct or the admission to practice rules, or Washington business and professions licensing statutes or rules.

. Independent of authority granted to the attorney general, the prosecuting attorney may petition the superior court for an injunction against a person who has violated this chapter. Remedies in an injunctive action brought by a prosecuting attorney are limited to an order enjoining, restraining, or preventing the doing of any act or practice that constitutes a violation of this chapter and imposing a civil penalty of up to five thousand dollars for each violation. The prevailing party in the action may, in the discretion of the court, recover its reasonable investigative costs and the costs of the action including a reasonable attorney's fee. The degree of proof required in an action brought under this subsection is a preponderance of the evidence. An action under this subsection must be brought within three years after the violation of this chapter occurred.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%202[2003 c 53 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1579.SL.pdf?cite=2001%20c%20310%20§%202[2001 c 310 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1557-S2.SL.pdf?cite=1995%20c%20285%20§%2026[1995 c 285 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c117.pdf?cite=1989%20c%20117%20§%2013[1989 c 117 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c94.pdf?cite=1933%20c%2094%20§%2014[1933 c 94 § 14]; RRS § 138-14; ]

== 2.48.190 - Qualifications on admission to practice.
No person shall be permitted to practice as an attorney or counselor at law or to do work of a legal nature for compensation, or to represent himself or herself as an attorney or counselor at law or qualified to do work of a legal nature, unless he or she is a citizen of the United States and a bona fide resident of this state and has been admitted to practice law in this state: PROVIDED, That any person may appear and conduct his or her own case in any action or proceeding brought by or against him or her, or may appear in his or her own behalf in the small claims department of the district court: AND PROVIDED FURTHER, That an attorney of another state may appear as counselor in a court of this state without admission, upon satisfying the court that his or her state grants the same right to attorneys of this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c202.pdf?cite=1987%20c%20202%20§%20107[1987 c 202 § 107]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c126.pdf?cite=1921%20c%20126%20§%204[1921 c 126 § 4]; RRS § 139-4; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c100.pdf?cite=1919%20c%20100%20§%201[1919 c 100 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c115.pdf?cite=1917%20c%20115%20§%201[1917 c 115 § 1]; ]

== 2.48.200 - Restrictions on practice by certain officers.
No person shall practice law who holds a commission as judge in any court of record, or as sheriff or coroner; nor shall the clerk of the supreme court, the court of appeals, or of the superior court or any deputy thereof practice in the court of which he or she is clerk or deputy clerk: PROVIDED, It shall be unlawful for a deputy prosecuting attorney, or for the employee, partner, or agent of a prosecuting attorney, or for an attorney occupying offices with a prosecuting attorney, to appear for an adverse interest in any proceeding in which a prosecuting attorney is appearing, or to appear in any suit, action or proceeding in which a prosecuting attorney is prohibited by law from appearing, but nothing herein shall prohibit a prosecuting attorney or a deputy prosecuting attorney from appearing in any action or proceeding for an interest divergent from that represented in the same action or proceeding by another attorney or special attorney in or for the same office, so long as such appearances are pursuant to the duties of prosecuting attorneys as set out in RCW 36.27.020 and such appearances are consistent with the code of professional responsibility or other code of ethics adopted by the Washington state supreme court, but nothing herein shall preclude a judge or justice of a court of this state from finishing any business undertaken in a court of the United States prior to him or her becoming a judge or justice.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2368.SL.pdf?cite=1992%20c%20225%20§%201[1992 c 225 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c19.pdf?cite=1975%201st%20ex.s.%20c%2019%20§%203[1975 1st ex.s. c 19 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c81.pdf?cite=1971%20c%2081%20§%2013[1971 c 81 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c126.pdf?cite=1921%20c%20126%20§%205[1921 c 126 § 5]; RRS § 139-5; ]

== 2.48.210 - Oath on admission.
Every person before being admitted to practice law in this state shall take and subscribe the following oath:

I do solemnly swear:

I am a citizen of the United States and owe my allegiance thereto;

I will support the Constitution of the United States and the Constitution of the state of Washington;

I will maintain the respect due to courts of justice and judicial officers;

I will not counsel or maintain any suit or proceeding which shall appear to me to be unjust, nor any defense except such as I believe to be honestly debatable under the law of the land, unless it be in defense of a person charged with a public offense; I will employ for the purpose of maintaining the causes confided to me such means only as are consistent with truth and honor, and will never seek to mislead the judge or jury by any artifice or false statement of fact or law;

I will maintain the confidence and preserve inviolate the secrets of my client, and will accept no compensation in connection with his or her business except from him or her or with his or her knowledge and approval;

I will abstain from all offensive personality, and advance no fact prejudicial to the honor or reputation of a party or witness, unless required by the justice of the cause with which I am charged;

I will never reject, from any consideration personal to myself, the cause of the defenseless or oppressed, or delay any person's cause for lucre or malice. So help me God.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%201[2013 c 23 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c126.pdf?cite=1921%20c%20126%20§%2012[1921 c 126 § 12]; RRS § 139-12; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c115.pdf?cite=1917%20c%20115%20§%2014[1917 c 115 § 14]; ]

== 2.48.220 - Grounds of disbarment or suspension.
An attorney or counselor may be disbarred or suspended for any of the following causes arising after his or her admission to practice:

. His or her conviction of a felony or misdemeanor involving moral turpitude, in which case the record of conviction shall be conclusive evidence.

. Willful disobedience or violation of an order of the court requiring him or her to do or forbear an act connected with, or in the course of, his or her profession, which he or she ought in good faith to do or forbear.

. Violation of his or her oath as an attorney, or of his or her duties as an attorney and counselor.

. Corruptly or willfully, and without authority, appearing as attorney for a party to an action or proceeding.

. Lending his or her name to be used as attorney and counselor by another person who is not an attorney and counselor.

. For the commission of any act involving moral turpitude, dishonesty, or corruption, whether the same be committed in the course of his or her relations as an attorney or counselor at law, or otherwise, and whether the same constitute a felony or misdemeanor or not; and if the act constitute a felony or misdemeanor, conviction thereof in a criminal proceeding shall not be a condition precedent to disbarment or suspension from practice therefor.

. Misrepresentation or concealment of a material fact made in his or her application for admission or in support thereof.

. Disbarment by a foreign court of competent jurisdiction.

. Practicing law with or in cooperation with a disbarred or suspended attorney, or maintaining an office for the practice of law in a room or office occupied or used in whole or in part by a disbarred or suspended attorney, or permitting a disbarred or suspended attorney to use his or her name for the practice of law, or practicing law for or on behalf of a disbarred or suspended attorney, or practicing law under any arrangement or understanding for division of fees or compensation of any kind with a disbarred or suspended attorney or with any person not a licensed attorney.

. Gross incompetency in the practice of the profession.

. Violation of the ethics of the profession.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%2068[2011 c 336 § 68]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c126.pdf?cite=1921%20c%20126%20§%2014[1921 c 126 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c139.pdf?cite=1909%20c%20139%20§%207[1909 c 139 § 7]; RRS § 139-14; ]

== 2.48.230 - Code of ethics.
The code of ethics of the American Bar Association shall be the standard of ethics for the members of the bar of this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c126.pdf?cite=1921%20c%20126%20§%2015[1921 c 126 § 15]; RRS § 139-15; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c115.pdf?cite=1917%20c%20115%20§%2020[1917 c 115 § 20]; ]

