= 2.60 - Federal court local law certificate procedure act.
:toc:

== 2.60.010 - Definitions.
As used in this chapter:

. The term "certificate procedure" shall mean the procedure authorized herein by which a federal court in disposing of a cause pending before it submits a question of local law to the supreme court for answer;

. The term "federal court" means any court of the United States of America including the supreme court of the United States, courts of appeal, district courts and any other court created by act of congress;

. The term "supreme court" shall mean supreme court of Washington;

. The term "record" shall mean: (a) A stipulation of facts approved by the federal court showing the nature of the case and the circumstances out of which the question of law arises or such part of the pleadings, proceedings and testimony in the cause pending before the federal court as in its opinion is necessary to enable the supreme court to answer the question submitted; (b) a statement of the question of local law certified for answer. The record shall contain a certificate under the official seal of the court, signed by the chief judge of a multi-judge federal court or judge of the district court utilizing certificate procedure stating that the record contains all matters in the pending cause deemed material for consideration of the local law question certified for answer;

. The term "supplemental record" shall mean the original or copies of any other portion of the proceedings, pleadings and testimony before the federal court deemed desirable by the supreme court in the determination of the local law question certified for answer. The supplemental record shall contain a certificate under the official seal of the court signed by the chief judge of such multi-judge federal court or judge of the district court, certifying that the supplemental record contains all additional matters requested;

. The term "opinion" shall mean the written opinion of the supreme court of Washington and shall include the certificate of the clerk of such court under seal of court stating that the opinion is in answer to the local law question submitted.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c99.pdf?cite=1965%20c%2099%20§%201[1965 c 99 § 1]; ]

== 2.60.020 - Federal court certification of local law question.
When in the opinion of any federal court before whom a proceeding is pending, it is necessary to ascertain the local law of this state in order to dispose of such proceeding and the local law has not been clearly determined, such federal court may certify to the supreme court for answer the question of local law involved and the supreme court shall render its opinion in answer thereto.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c99.pdf?cite=1965%20c%2099%20§%202[1965 c 99 § 2]; ]

== 2.60.030 - Practice and procedure.
Certificate procedure shall be governed by the following provisions:

. Certificate procedure may be invoked by a federal court upon its own motion or upon the motion of any interested party in the litigation involved if the federal court grants such motion.

. Certificate procedure shall include and be based upon the record and may include a supplemental record.

. Certificate procedure costs shall be equally divided between plaintiff and defendant, subject to reallocation as between or among the parties by the federal court involved.

. The appellant or moving party in the federal court shall file and serve upon its adversary its brief on the question certified within thirty days after the filing of the record in the supreme court. The appellee or responding party in the federal court shall file and serve upon its adversary its brief within twenty days after receipt of appellant's or moving party's brief and a reply brief shall be filed within ten days. Time for filing record, supplemental record or briefs may be extended for cause.

. Oral argument as in other causes on the merits may be had upon request of the supreme court or upon application of any interested party in the certificate procedure.

. The supreme court shall forward to the federal court utilizing certificate procedure its opinion answering the local law question submitted.

. The supreme court may adopt rules of practice and procedure to implement or otherwise facilitate utilization of certificate procedure.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c99.pdf?cite=1965%20c%2099%20§%203[1965 c 99 § 3]; ]

== 2.60.900 - Short title.
This act may be cited as the "federal court local law certificate procedure act."

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c99.pdf?cite=1965%20c%2099%20§%204[1965 c 99 § 4]; ]

