= 28B.900 - Construction.
:toc:

== 28B.900.010 - Repeals and savings—1969 ex.s. c 223.
See 1969 ex.s. c 223 s 28B.98.010. Formerly RCW 28B.98.010.

[ ]

== 28B.900.020 - Moneys transferred.
All moneys in the Southwestern Washington State College bond retirement fund and the Southwestern Washington State College capital projects account are hereby transferred to The Evergreen State College bond retirement fund and The Evergreen State College capital projects account respectively, which latter fund and account are created in RCW 28B.35.370.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.98.020[1969 ex.s. c 223 § 28B.98.020]; ]

== 28B.900.030 - Continuation of existing law.
The provisions of this title, Title 28B RCW, insofar as they are substantially the same as statutory provisions repealed by this chapter, and relating to the same subject matter, shall be construed as restatements and continuations, and not as new enactments. Nothing in this 1969 code revision of Title 28 RCW shall be construed as authorizing any new bond issues or new or additional appropriations of moneys but the bond issue authorizations herein contained shall be construed only as continuations of bond issues authorized by prior laws herein repealed and reenacted, and the appropriations of moneys herein contained are continued herein for historical purposes only and this 1969 act shall not be construed as a reappropriation thereof and no appropriation contained herein shall be deemed to be extended or revived hereby and such appropriation shall lapse or shall have lapsed in accordance with the original enactment: PROVIDED, That this 1969 act shall not operate to terminate, extend, or otherwise affect any appropriation for the biennium commencing July 1, 1967 and ending June 30, 1969.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.98.030[1969 ex.s. c 223 § 28B.98.030]; ]

== 28B.900.040 - Provisions to be construed in pari materia.
The provisions of this title, Title 28B RCW, shall be construed in pari materia even though as a matter of prior legislative history they were not originally enacted in the same statute. The provisions of this title shall also be construed in pari materia with the provisions of Title 28A RCW, and with other laws relating to education. This section shall not operate retroactively.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.98.040[1969 ex.s. c 223 § 28B.98.040]; ]

== 28B.900.050 - Title, chapter, section headings not part of law.
Title headings, chapter headings, and section or subsection headings, as used in this title, Title 28B RCW, do not constitute any part of the law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.98.050[1969 ex.s. c 223 § 28B.98.050]; ]

== 28B.900.060 - Invalidity of part of title not to affect remainder.
If any provision of this title, Title 28B RCW, or its application to any person or circumstance is held invalid, the remainder of the title, or the application of the provision to other persons or circumstances is not affected.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.98.060[1969 ex.s. c 223 § 28B.98.060]; ]

== 28B.900.070 - This code defined.
As used in this title, Title 28B RCW, "this code" means Titles 28A and 28B of this 1969 act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.98.070[1969 ex.s. c 223 § 28B.98.070]; ]

== 28B.900.080 - Effective date—1969 ex.s. c 223.
This act shall take effect on July 1, 1970.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.98.080[1969 ex.s. c 223 § 28B.98.080]; ]

