= 28B.130 - Transportation demand management programs.
:toc:

== 28B.130.005 - Findings—Intent.
Transportation demand management strategies that reduce the number of vehicles on Washington state's highways, roads, and streets, and provide attractive and effective alternatives to single-occupancy travel, can improve ambient air quality, conserve fossil fuels, and forestall the need for capital improvements to the state's transportation system. The legislature has required many public and private employers in the state's largest counties to implement transportation demand management programs to reduce the number of single-occupant vehicle travelers during the morning and evening rush hours, and has provided substantial funding for the University of Washington's UPASS program, which has been immensely successful in its first two years of implementation. The legislature finds that additional transportation demand management strategies are required to mitigate the adverse social, environmental, and economic effects of auto dependency and traffic congestion. While expensive capital improvements, including dedicated busways and commuter rail systems, may be necessary to improve the region's mobility, they are only part of the solution. All public and private entities that attract single-occupant vehicle drivers must develop imaginative and cost-effective ways to encourage walking, bicycling, carpooling, vanpooling, bus riding, and telecommuting. It is the intent of the legislature to revise those portions of state law that inhibit the application of imaginative solutions to the state's transportation mobility problems, and to encourage many more public and private institutions of higher learning to adopt effective transportation demand management strategies.

The legislature finds further that many of the institutions of higher education in the state's largest counties are responsible for significant numbers of single-occupant vehicle trips to and from their campuses. These single-occupant vehicle trips are not only contributing to the degradation of the state's environment and deterioration of its transportation system, but are also usurping parking spaces from surrounding residential communities because existing parking facilities cannot accommodate students' current demand. Therefore, it is the intent of the legislature to permit these institutions to develop and fund transportation demand management programs that reduce single-occupant vehicle travel and promote alternatives to single-occupant vehicle driving. The legislature encourages institutions of higher education to include faculty and staff in their transportation demand management programs.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1085-S.SL.pdf?cite=1993%20c%20447%20§%201[1993 c 447 § 1]; ]

== 28B.130.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Transportation fee" means the fee charged to employees and students at institutions of higher education for the purposes provided in RCW 28B.130.020.

. "Transportation demand management program" means the set of strategies adopted by an institution of higher education to reduce the number of single-occupant vehicles traveling to its campus. These strategies may include but are not limited to those identified in *RCW 70.94.531.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1085-S.SL.pdf?cite=1993%20c%20447%20§%202[1993 c 447 § 2]; ]

== 28B.130.020 - Transportation fee.
. The governing board of an institution of higher education as defined in RCW 28B.10.016 may impose either a voluntary or a mandatory transportation fee on employees and on students at the institution. The board of regents of Washington State University may impose either a voluntary or a mandatory transportation fee on faculty and staff working at the Riverpoint higher education park and on students attending classes there. The transportation fee shall be used solely to fund transportation demand management programs that reduce the demand for campus and neighborhood parking, and promote alternatives to single-occupant vehicle driving. If the board charges a mandatory transportation fee to students, it shall charge a mandatory transportation fee to employees. The transportation fee for employees may exceed, but shall not be lower than the transportation fee charged to students. The transportation fee for employees may be deducted from the employees' paychecks. The transportation fee for students may be imposed annually, or each academic term. For students attending community colleges and technical colleges, the mandatory transportation fee shall not exceed sixty percent of the maximum rate permitted for services and activities fees at community colleges, unless, through a vote, a majority of students consent to increase the transportation fee. For students attending four-year institutions of higher education or classes at the Riverpoint higher education park, the mandatory transportation fee shall not exceed thirty-five percent of the maximum rate permitted for services and activities fees at the institution where the student is enrolled unless, through a vote, a majority of students consents to increase the transportation fee. The board may make a limited number of exceptions to the fee based on a policy adopted by the board.

. The board of regents of Washington State University shall not impose a transportation fee on any student who is already paying a transportation fee to the institution of higher education in which the student is enrolled.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6655-S.SL.pdf?cite=1998%20c%20344%20§%207[1998 c 344 § 7]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2193-S.SL.pdf?cite=1997%20c%20273%20§%202[1997 c 273 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1085-S.SL.pdf?cite=1993%20c%20447%20§%203[1993 c 447 § 3]; ]

== 28B.130.030 - Use of transportation fees.
Transportation fees shall be spent only on activities directly related to the institution of higher education's transportation demand management program. These may include, but are not limited to the following activities: Transit, carpool, and vanpool subsidies; ride-sharing programs, and program advertising for carpools, vanpools, and transit service; guaranteed ride-home and telecommuting programs; and bicycle storage facilities. Funds may be spent on capital or operating costs incurred in the implementation of any of these strategies, and may be also used to contract with local or regional transit agencies for transportation services. Funds may be used for existing programs if they are incorporated into the campus transportation demand management program.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1085-S.SL.pdf?cite=1993%20c%20447%20§%204[1993 c 447 § 4]; ]

== 28B.130.040 - Adoption of guidelines for establishing and funding transportation demand management programs.
The board of trustees or board of regents of each institution of higher education imposing a transportation fee shall adopt guidelines governing the establishment and funding of transportation demand management programs supported by transportation fees. These guidelines shall establish procedures for budgeting and expending transportation fee revenue.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1085-S.SL.pdf?cite=1993%20c%20447%20§%205[1993 c 447 § 5]; ]

