= 28B.105 - GET ready for math and science scholarship program.
:toc:

== 28B.105.010 - GET ready for math and science scholarship program—Purpose—Awards.
. The GET ready for math and science scholarship program is established. The purpose of the program is to provide scholarships to students who achieve level four on the mathematics or science portions of the high school statewide student assessment or achieve a score in the math section of the SAT or the math section of the ACT that is above the ninety-fifth percentile, major in a mathematics, science, or related field in college, and commit to working in mathematics, science, or a related field for at least three years in Washington following completion of their bachelor's degree. The program shall be administered by the nonprofit organization selected as the private partner in the public-private partnership.

. The total annual amount of each GET ready for math and science scholarship may vary, but shall not exceed the annual cost of resident undergraduate tuition fees and mandatory fees at the University of Washington. An eligible recipient may receive a GET ready for math and science scholarship for up to one hundred eighty quarter credits, or the semester equivalent, or for up to five years, whichever comes first.

. Scholarships shall be awarded only to the extent that state funds and private matching funds are available for that purpose in the GET ready for math and science scholarship account established in RCW 28B.105.110.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2013%202nd%20sp.s.%20c%2022%20§%2010[2013 2nd sp.s. c 22 § 10]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1779-S2.SL.pdf?cite=2007%20c%20214%20§%201[2007 c 214 § 1]; ]

== 28B.105.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "GET units" means tuition units under the advanced college tuition payment program in chapter 28B.95 RCW.

. "Institution of higher education" has the same meaning as in RCW 28B.92.030(4) (a) and (b) (i) and (ii).

. "Office" means the office of student financial assistance.

. "Program administrator" means the private nonprofit corporation that is registered under Title 24 RCW and qualified as a tax-exempt entity under section 501(c)(3) of the federal internal revenue code, that will serve as the private partner in the public-private partnership under this chapter.

. "Qualified program" or "qualified major" means a mathematics, science, or related degree program or major line of study offered by an institution of higher education that is included on the list of programs or majors selected by the office and the program administrator under RCW 28B.105.100.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5195-S.SL.pdf?cite=2013%20c%20248%20§%203[2013 c 248 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20183[2011 1st sp.s. c 11 § 183]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1779-S2.SL.pdf?cite=2007%20c%20214%20§%202[2007 c 214 § 2]; ]

== 28B.105.030 - Eligibility.
. An eligible student is a student who:

.. Is eligible for resident tuition and fee rates as defined in RCW 28B.15.012;

.. Achieved level four on the mathematics or science portion of the high school statewide student assessment or achieved a score in the math section of the SAT or the math section of the ACT that is above the ninety-fifth percentile;

.. Has a family income at or below one hundred twenty-five percent of the state median family income at the time the student applies for a GET ready for math and science scholarship and for up to the two previous years;

.. Has declared an intention to complete a qualified program or qualified major or has entered a qualified program or declared a qualified major at an institution of higher education;

.. Has declared an intention to work in a mathematics, science, or related field in Washington for at least three years immediately following completion of a bachelor's degree or higher degree.

. An eligible recipient is an eligible student who:

.. Has been awarded a scholarship in accordance with the selection criteria and process established by the student achievement council and the program administrator;

.. Enrolls at an institution of higher education within one year of graduating from high school;

.. Maintains satisfactory academic progress, as defined by the institution of higher education where the student is enrolled;

.. Takes at least one college-level mathematics or science course each term since enrolling in an institution of higher education; and

.. Enters a qualified program or qualified major no later than the end of the first term in which the student has junior level standing.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2013%202nd%20sp.s.%20c%2022%20§%2011[2013 2nd sp.s. c 22 § 11]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1779-S2.SL.pdf?cite=2007%20c%20214%20§%203[2007 c 214 § 3]; ]

== 28B.105.040 - Changes in eligibility—Consequences.
. If the student enrolls in a qualified program or declares a qualified major and the program or major is subsequently removed from the list of qualified programs and qualified majors by the office and the program administrator, the student's eligibility to receive a GET ready for math and science scholarship shall not be affected.

. If a student who received a GET ready for math and science scholarship ceases to be enrolled in an institution of higher education, withdraws or is no longer enrolled in a qualified program, declares a major that is not a qualified major, or otherwise is no longer eligible to receive a GET ready for math and science scholarship, the student shall notify the program administrator as soon as practicable and is not eligible for further GET ready for math and science scholarship awards. Such a student shall also repay the amount of the GET ready for math and science scholarship awarded to the student as required by RCW 28B.105.050.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20184[2011 1st sp.s. c 11 § 184]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1779-S2.SL.pdf?cite=2007%20c%20214%20§%204[2007 c 214 § 4]; ]

== 28B.105.050 - Repayment obligation—Conditions.
. A recipient of a GET ready for math and science scholarship incurs an obligation to repay the scholarship, with interest and an equalization fee, if he or she does not:

.. Graduate with a bachelor's degree from a qualified program or in a qualified major within five years of first enrolling at an institution of higher education; and

.. Work in Washington in a mathematics, science, or related occupation full time for at least three years following completion of a bachelor's degree, unless he or she is enrolled in a graduate degree program as provided in subsection (4) of this section.

. A former scholarship recipient who has earned a bachelor's degree shall annually verify to the office that he or she is working full time in a mathematics, science, or related field for three years.

. If a former scholarship recipient begins but then stops working full time in a mathematics, science, or related field within three years following completion of a bachelor's degree, he or she shall pay back a prorated portion of the amount of the GET ready for math and science scholarship award received by the recipient, plus interest and a prorated equalization fee.

. A recipient may postpone for up to three years his or her in-state work obligation if he or she enrolls full time in a graduate degree program in mathematics, science, or a related field.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20185[2011 1st sp.s. c 11 § 185]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1779-S2.SL.pdf?cite=2007%20c%20214%20§%205[2007 c 214 § 5]; ]

== 28B.105.060 - Office of the superintendent of public instruction—Duties.
The office of the superintendent of public instruction shall:

. Notify elementary, middle, junior high, high school, and school district staff and administrators, and the department of children, youth, and families about the GET ready for math and science scholarship program using methods in place for communicating with schools and school districts; and

. Provide data showing the race, ethnicity, income, and other available demographic information of students who achieve level four on the math and science high school statewide student assessment; compare those data with comparable information on the student population as a whole; and submit a report with the analysis to the committees responsible for education and higher education in the legislature on December 1st of even-numbered years.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6287.SL.pdf?cite=2018%20c%2058%20§%2062[2018 c 58 § 62]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1450.SL.pdf?cite=2013%202nd%20sp.s.%20c%2022%20§%2012[2013 2nd sp.s. c 22 § 12]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1779-S2.SL.pdf?cite=2007%20c%20214%20§%206[2007 c 214 § 6]; ]

== 28B.105.070 - Office of student financial assistance—Duties.
The office shall:

. Purchase GET units to be owned and held in trust by the office, for the purpose of scholarship awards as provided for in this section;

. Distribute scholarship funds, in the form of GET units or through direct payments from the GET ready for math and science scholarship account, to institutions of higher education on behalf of eligible recipients identified by the program administrator;

. Provide the program administrator with annual reports regarding enrollment, contact, and graduation information of GET ready for math and science scholarship recipients, if the recipients have given permission for the office to do so;

. Collect repayments from former scholarship recipients who do not meet the eligibility criteria or work obligations;

. Establish rules for scholarship repayment, approved leaves of absence, deferments, and exceptions to recognize extenuating circumstances that may impact students; and

. Provide information to school districts in Washington, at least once per year, about the GET ready for math and science scholarship program.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20186[2011 1st sp.s. c 11 § 186]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1779-S2.SL.pdf?cite=2007%20c%20214%20§%207[2007 c 214 § 7]; ]

== 28B.105.080 - School districts—Duties.
School districts shall:

. Notify parents, teachers, counselors, and principals about the GET ready for math and science scholarship program through existing channels. Notification methods may include, but are not limited to, regular school district and building communications, online scholarship bulletins and announcements, notices posted on school walls and bulletin boards, information available in each counselor's office, and school or district scholarship information sessions;

. Provide each student who achieves level four on the mathematics or science high school Washington assessment of student learning with information regarding the scholarship program and how to contact the program administrator.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1779-S2.SL.pdf?cite=2007%20c%20214%20§%208[2007 c 214 § 8]; ]

== 28B.105.090 - Program administrator—Duties.
The program administrator shall:

. Solicit and accept grants and donations from private sources to match state funds appropriated for the GET ready for math and science scholarship program;

. Develop and implement an application, selection, and notification process for awarding GET ready for math and science scholarships;

. Notify institutions of higher education of scholarship recipients who will attend their institutions and inform them of the terms of the students' eligibility; and

. Report to private donors on the program outcomes and facilitate contact between scholarship recipients and donors, if the recipients have given the program administrator permission to do so, in order for donors to offer employment opportunities, internships, and career information to recipients.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1779-S2.SL.pdf?cite=2007%20c%20214%20§%209[2007 c 214 § 9]; ]

== 28B.105.100 - Office of student financial assistance and program administrator—Joint duties.
The office and the program administrator shall jointly:

. Determine criteria for qualifying undergraduate programs, majors, and courses leading to a bachelor's degree in mathematics, science, or a related field, offered by institutions of higher education. The office shall publish the criteria for qualified courses, and lists of qualified programs and qualified majors, on its website on a biennial basis; and

. Establish criteria for selecting among eligible applicants those who, without scholarship assistance, would be least likely to pursue a qualified undergraduate program at an institution of higher education in Washington state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20187[2011 1st sp.s. c 11 § 187]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1779-S2.SL.pdf?cite=2007%20c%20214%20§%2010[2007 c 214 § 10]; ]

== 28B.105.110 - GET ready for math and science scholarship account.
. The GET ready for math and science scholarship account is created in the custody of the state treasurer.

. The office shall deposit into the account all money received for the GET ready for math and science scholarship program from appropriations and private sources. The account shall be self-sustaining.

. Expenditures from the account shall be used for scholarships to eligible students and for purchases of GET units. Purchased GET units shall be owned and held in trust by the office. Expenditures from the account shall be an equal match of state appropriations and private funds raised by the program administrator. During the 2009-2011 fiscal biennium, expenditures from the account not to exceed five percent may be used by the program administrator to carry out the provisions of RCW 28B.105.090.

. With the exception of the operating costs associated with the management of the account by the treasurer's office as authorized in chapter 43.79A RCW, the account shall be credited with all investment income earned by the account.

. Disbursements from the account are exempt from appropriations and the allotment provisions of chapter 43.88 RCW.

. Disbursements from the account shall be made only on the authorization of the office.

. During the 2013-2015 fiscal biennium, appropriated state funds available in the GET ready for math and science scholarship account and GET units owned by the office and not used for the GET ready for math and science scholarship program may be used for the college bound scholarship program created in chapter 28B.118 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5034-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%204%20§%20963[2013 2nd sp.s. c 4 § 963]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20188[2011 1st sp.s. c 11 § 188]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6444-S.SL.pdf?cite=2010%201st%20sp.s.%20c%2037%20§%20918[2010 1st sp.s. c 37 § 918]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1244-S.SL.pdf?cite=2009%20c%20564%20§%201807[2009 c 564 § 1807]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1244-S.SL.pdf?cite=2009%20c%20564%20§%20920[2009 c 564 § 920]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2687-S.SL.pdf?cite=2008%20c%20329%20§%20908[2008 c 329 § 908]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1779-S2.SL.pdf?cite=2007%20c%20214%20§%2011[2007 c 214 § 11]; ]

