= 28B.118 - College bound scholarship program.
:toc:

== 28B.118.005 - Intent—Finding.
The legislature intends to inspire and encourage all Washington students to dream big by creating a guaranteed four-year tuition scholarship program for students from low-income families. The legislature finds that, too often, financial barriers prevent many of the brightest students from considering college as a future possibility. Often the cost of tuition coupled with the complexity of finding and applying for financial aid is enough to prevent a student from even applying to college. Many students become disconnected from the education system early on and may give up or drop out before graduation. It is the intent of the legislature to alert students early in their educational career to the options and opportunities available beyond high school.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5098-S2.SL.pdf?cite=2007%20c%20405%20§%201[2007 c 405 § 1]; ]

== 28B.118.010 - Program design and student eligibility.
The office of student financial assistance shall design the Washington college bound scholarship program in accordance with this section and in alignment with the Washington college grant program in chapter 28B.92 RCW unless otherwise provided in this section.

. "Eligible students" are those students who:

.. Qualify for free or reduced-price lunches.

... If a student qualifies in the seventh or eighth grade, the student remains eligible even if the student does not receive free or reduced-price lunches thereafter.

... Beginning in the 2019-20 academic year, if a student qualifies for free or reduced-price lunches in the ninth grade and was previously ineligible during the seventh or eighth grade while he or she was a student in Washington, the student is eligible for the college bound scholarship program;

.. Are dependent pursuant to chapter 13.34 RCW and:

... In grade seven through twelve; or

... Are between the ages of eighteen and twenty-one and have not graduated from high school; or

.. Were dependent pursuant to chapter 13.34 RCW and were adopted between the ages of fourteen and eighteen with a negotiated adoption agreement that includes continued eligibility for the Washington state college bound scholarship program pursuant to RCW 74.13A.025.

. Eligible students and the students' parents or guardians shall be notified of the student's eligibility for the Washington college bound scholarship program. Students and the students' parents or guardians shall also be notified of the requirements for award of the scholarship.

. [Empty]
.. To be eligible for a Washington college bound scholarship, a student eligible under subsection (1)(a)(i) of this section must sign a pledge during seventh or eighth grade or a student eligible under subsection (1)(a)(ii) of this section must sign a pledge during ninth grade. The pledge must include a commitment to graduate from high school with at least a C average and with no felony convictions. The pledge must be witnessed by a parent or guardian and forwarded to the office of student financial assistance by mail or electronically, as indicated on the pledge form.

.. [Empty]
... Beginning in the 2018-19 academic year, the office of student financial assistance shall make multiple attempts to secure the signature of the student's parent or guardian for the purpose of witnessing the pledge.

... If the signature of the student's parent or guardian is not obtained, the office of student financial assistance may partner with the school counselor or administrator to secure the parent's or guardian's signature to witness the pledge. The school counselor or administrator shall make multiple attempts via all phone numbers, email addresses, and mailing addresses on record to secure the parent's or guardian's signature. All attempts to contact the parent or guardian must be documented and maintained in the student's official file.

... If a parent's or guardian's signature is still not obtained, the school counselor or administrator shall indicate to the office of student financial assistance the nature of the unsuccessful efforts to contact the student's parent or guardian and the reasons the signature is not available. Then the school counselor or administrator may witness the pledge unless the parent or guardian has indicated that he or she does not wish for the student to participate in the program.

.. A student eligible under subsection (1)(b) of this section shall be automatically enrolled, with no action necessary by the student or the student's family, and the enrollment form must be forwarded by the department of social and health services to the office of student financial assistance by mail or electronically, as indicated on the form.

. [Empty]
.. Scholarships shall be awarded to eligible students graduating from public high schools, approved private high schools under chapter 28A.195 RCW, or who received home-based instruction under chapter 28A.200 RCW.

.. [Empty]
... To receive the Washington college bound scholarship, a student must graduate with at least a "C" average from a public high school or an approved private high school under chapter 28A.195 RCW in Washington or have received home-based instruction under chapter 28A.200 RCW, must have no felony convictions, and must be a resident student as defined in RCW 28B.15.012(2) (a) through (e). A student who is eligible to receive the Washington college bound scholarship because the student is a resident student under RCW 28B.15.012(2)(e) must provide the institution, as defined in RCW 28B.15.012, an affidavit indicating that the individual will file an application to become a permanent resident at the earliest opportunity the individual is eligible to do so and a willingness to engage in any other activities necessary to acquire citizenship, including but not limited to citizenship or civics review courses.

... For eligible children as defined in subsection (1)(b) and (c) of this section, to receive the Washington college bound scholarship, a student must have received a high school equivalency certificate as provided in RCW 28B.50.536 or have graduated with at least a "C" average from a public high school or an approved private high school under chapter 28A.195 RCW in Washington or have received home-based instruction under chapter 28A.200 RCW, must have no felony convictions, and must be a resident student as defined in RCW 28B.15.012(2) (a) through (e).

For a student who does not meet the "C" average requirement, and who completes fewer than two quarters in the running start program, under chapter 28A.600 RCW, the student's first quarter of running start course grades must be excluded from the student's overall grade point average for purposes of determining their eligibility to receive the scholarship.

. A student's family income will be assessed upon graduation before awarding the scholarship. If at graduation from high school the student's family income does not exceed sixty-five percent of the state median family income, scholarship award amounts shall be as provided in this section.

. [Empty]
.. For students attending two or four-year institutions of higher education as defined in RCW 28B.10.016, the value of the award shall be (i) the difference between the student's tuition and required fees, less the value of any state-funded grant, scholarship, or waiver assistance the student receives; (ii) plus five hundred dollars for books and materials.

.. For students attending private four-year institutions of higher education in Washington, the award amount shall be the representative average of awards granted to students in public research universities in Washington or the representative average of awards granted to students in public research universities in Washington in the 2014-15 academic year, whichever is greater.

.. For students attending private vocational schools in Washington, the award amount shall be the representative average of awards granted to students in public community and technical colleges in Washington or the representative average of awards granted to students in public community and technical colleges in Washington in the 2014-15 academic year, whichever is greater.

. Recipients may receive no more than four full-time years' worth of scholarship awards.

. Institutions of higher education shall award the student all need-based and merit-based financial aid for which the student would otherwise qualify. The Washington college bound scholarship is intended to replace unmet need, loans, and, at the student's option, work-study award before any other grants or scholarships are reduced.

. The first scholarships shall be awarded to students graduating in 2012.

. The state of Washington retains legal ownership of tuition units awarded as scholarships under this chapter until the tuition units are redeemed. These tuition units shall remain separately held from any tuition units owned under chapter 28B.95 RCW by a Washington college bound scholarship recipient.

. The scholarship award must be used within five years of receipt. Any unused scholarship tuition units revert to the Washington college bound scholarship account.

. Should the recipient terminate his or her enrollment for any reason during the academic year, the unused portion of the scholarship tuition units shall revert to the Washington college bound scholarship account.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2158-S2.SL.pdf?cite=2019%20c%20406%20§%2044[2019 c 406 § 44]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1311-S2.SL.pdf?cite=2019%20c%20298%20§%201[2019 c 298 § 1]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1488-S3.SL.pdf?cite=2018%20c%20204%20§%201[2018 c 204 § 1]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1293-S2.SL.pdf?cite=2018%20c%2012%20§%201[2018 c 12 § 1]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5890-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%2020%20§%2011[2017 3rd sp.s. c 20 § 11]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5954-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2036%20§%208[2015 3rd sp.s. c 36 § 8]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5851-S2.SL.pdf?cite=2015%20c%20244%20§%203[2015 c 244 § 3]; prior:  2012 c 229 § 402; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2254-S.SL.pdf?cite=2012%20c%20163%20§%208[2012 c 163 § 8]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20226[2011 1st sp.s. c 11 § 226]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6673-S2.SL.pdf?cite=2008%20c%20321%20§%209[2008 c 321 § 9]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5098-S2.SL.pdf?cite=2007%20c%20405%20§%202[2007 c 405 § 2]; ]

== 28B.118.020 - Duties of the office of the superintendent of public instruction.
The office of the superintendent of public instruction shall:

. Notify elementary, middle, and junior high schools about the Washington college bound scholarship program using methods in place for communicating with schools and school districts; and

. Work with the office of student financial assistance to develop application collection and student tracking procedures.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20227[2011 1st sp.s. c 11 § 227]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5098-S2.SL.pdf?cite=2007%20c%20405%20§%203[2007 c 405 § 3]; ]

== 28B.118.030 - Duty of school districts—Notification.
Each school district shall notify students, parents, teachers, counselors, and principals about the Washington college bound scholarship program through existing channels. Notification methods may include, but are not limited to, regular school district and building communications, online scholarship bulletins and announcements, notices posted on school walls and bulletin boards, information available in each counselor's office, and school or district scholarship information sessions.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5098-S2.SL.pdf?cite=2007%20c%20405%20§%204[2007 c 405 § 4]; ]

== 28B.118.040 - Duties of the office of student financial assistance.
The office of student financial assistance shall:

. With the assistance of the office of the superintendent of public instruction, implement and administer the Washington college bound scholarship program;

. Develop and distribute, to all schools with students enrolled in grades seven through nine, a pledge form that can be completed and returned electronically or by mail by the student or the school to the office of student financial assistance;

. Develop and implement a student application, selection, and notification process for scholarships, which includes working with other state agencies, law enforcement, or the court system to verify that eligible students do not have felony convictions;

. Annually in March, with the assistance of the office of the superintendent of public instruction, distribute to tenth grade college bound scholarship students and their families: (a) Notification that, to qualify for the scholarship, a student's family income may not exceed sixty-five percent of the state median family income at graduation from high school; (b) the current year's value for sixty-five percent of the state median family income; and (c) a statement that a student should consult their school counselor if their family makes, or is projected to make, more than this value before the student graduates;

. Develop comprehensive social media outreach with grade-level specific information designed to keep students on track to graduate and leverage current tools such as the high school and beyond plan required by the state board of education and the ready set grad web site maintained by the student achievement council;

. Track scholarship recipients to ensure continued eligibility and determine student compliance for awarding of scholarships;

. Within existing resources, collaborate with college access providers and K-12, postsecondary, and youth-serving organizations to map and coordinate mentoring and advising resources across the state;

. Subject to appropriation, deposit funds into the state educational trust fund;

. Purchase tuition units under the advanced college tuition payment program in chapter 28B.95 RCW to be owned and held in trust by the office of student financial assistance, for the purpose of scholarship awards as provided for in this section; and

. Distribute scholarship funds, in the form of tuition units purchased under the advanced college tuition payment program in chapter 28B.95 RCW or through direct payments from the state educational trust fund, to institutions of higher education on behalf of scholarship recipients identified by the office, as long as recipients maintain satisfactory academic progress.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1311-S2.SL.pdf?cite=2019%20c%20298%20§%202[2019 c 298 § 2]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1293-S2.SL.pdf?cite=2018%20c%2012%20§%202[2018 c 12 § 2]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5851-S2.SL.pdf?cite=2015%20c%20244%20§%204[2015 c 244 § 4]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20228[2011 1st sp.s. c 11 § 228]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5098-S2.SL.pdf?cite=2007%20c%20405%20§%205[2007 c 405 § 5]; ]

== 28B.118.050 - Grants, gifts, bequests, and devises.
The office of student financial assistance may accept grants, gifts, bequests, and devises of real and personal property from any source for the purpose of granting financial aid in addition to that funded by the state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20229[2011 1st sp.s. c 11 § 229]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5098-S2.SL.pdf?cite=2007%20c%20405%20§%206[2007 c 405 § 6]; ]

== 28B.118.060 - Rules.
The office of student financial assistance may adopt rules to implement this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20230[2011 1st sp.s. c 11 § 230]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5098-S2.SL.pdf?cite=2007%20c%20405%20§%207[2007 c 405 § 7]; ]

== 28B.118.075 - Caseload estimate.
The caseload forecast council shall estimate the anticipated caseload of the Washington college bound scholarship program and shall submit this forecast as specified in RCW 43.88C.020.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5304.SL.pdf?cite=2011%20c%20304%20§%201[2011 c 304 § 1]; ]

== 28B.118.080 - Advising resources—Identification of officials, resources, programs, and students.
Each institution of higher education is encouraged to tailor advising resources for any enrolled student who is the recipient of a college bound scholarship. The institutions of higher education should identify campus officials, resources, programs, and other college bound scholarship students available to work with college bound scholarship recipients.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5851-S2.SL.pdf?cite=2015%20c%20244%20§%205[2015 c 244 § 5]; ]

== 28B.118.090 - Transmitting data to the education data center.
. Beginning January 1, 2015, and at a minimum every year thereafter, the student achievement council and all institutions of higher education eligible to participate in the college bound scholarship program shall ensure data needed to analyze and evaluate the effectiveness of the college bound scholarship program is promptly transmitted to the education data center created in RCW 43.41.400 so that it is available and easily accessible. The data to be reported should include but not be limited to:

.. The number of students who sign up for the college bound scholarship program in seventh, eighth, or ninth grade;

.. The number of college bound scholarship students who graduate from high school;

.. The number of college bound scholarship students who enroll in postsecondary education;

.. Persistence and completion rates of college bound scholarship recipients disaggregated by institutions of higher education;

.. College bound scholarship recipient grade point averages;

.. The number of college bound scholarship recipients who did not remain eligible and reasons for ineligibility;

.. College bound scholarship program costs; and

.. Impacts to the Washington college grant program.

. Beginning May 12, 2015, and at a minimum every December 1st thereafter, the student achievement council shall submit student unit record data for the college bound scholarship program applicants and recipients to the education data center.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2158-S2.SL.pdf?cite=2019%20c%20406%20§%2045[2019 c 406 § 45]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1311-S2.SL.pdf?cite=2019%20c%20298%20§%203[2019 c 298 § 3]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5851-S2.SL.pdf?cite=2015%20c%20244%20§%206[2015 c 244 § 6]; ]

