= 28B.120 - Washington fund for innovation and quality in higher education program.
:toc:

== 28B.120.005 - Findings.
The legislature finds that encouraging collaboration among the various educational sectors to meet statewide productivity and educational attainment needs as described in the system design plan developed by the *higher education coordinating board will strengthen the entire educational system, kindergarten through twelfth grade and higher education. The legislature also recognizes that the most effective way to develop innovative and collaborative programs is to encourage institutions to develop them voluntarily, in line with established state goals. Through a system of competitive grants, the legislature shall encourage the development of innovative and collaborative and cost-effective solutions to issues of critical statewide need, including:

. Raising educational attainment and planning and piloting innovative initiatives to reach new locations and populations;

. Recognizing needs of special populations of students, including access and completion efforts targeting underrepresented populations;

. Furthering the development of learner-centered, technology-assisted course delivery, including expansion of online and hybrid coursework, open courseware, and other uses of technology in order to effectively and efficiently share costs, improve the quality of instruction and student, faculty, and administrative services, increase undergraduate and graduate student access, retention, and graduation, and to enhance transfer capability;

. Furthering the development of competency-based measurements of student achievement to be used as the basis for awarding degrees and certificates;

. Increasing the collaboration among both public and private sector institutions of higher education; and

. Improving productivity through innovations such as accelerated programs and alternative scheduling.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6355-S.SL.pdf?cite=2010%20c%20245%20§%206[2010 c 245 § 6]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1013-S.SL.pdf?cite=1999%20c%20169%20§%202[1999 c 169 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1723.SL.pdf?cite=1991%20c%2098%20§%201[1991 c 98 § 1]; ]

== 28B.120.010 - Washington fund for innovation and quality in higher education program—Incentive grants.
The Washington fund for innovation and quality in higher education program is established. The student achievement council shall administer the program and shall work in close collaboration with the state board for community and technical colleges and other local and regional entities. Through this program the student achievement council may award on a competitive basis incentive grants to state public or private nonprofit institutions of higher education or consortia of institutions to encourage programs designed to address specific system problems. Each institution or consortia of institutions receiving the award shall contribute some financial support, either by covering part of the costs for the program during its implementation, or by assuming continuing support at the end of the grant period. Strong priority will be given to proposals that involve more than one sector of education. Institutions are encouraged to solicit nonstate funds to support these cooperative programs.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20571[2012 c 229 § 571]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6355-S.SL.pdf?cite=2010%20c%20245%20§%207[2010 c 245 § 7]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1013-S.SL.pdf?cite=1999%20c%20169%20§%205[1999 c 169 § 5]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2292-S2.SL.pdf?cite=1996%20c%2041%20§%201[1996 c 41 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1723.SL.pdf?cite=1991%20c%2098%20§%202[1991 c 98 § 2]; ]

== 28B.120.020 - Program administration—Powers and duties of student achievement council.
The student achievement council shall have the following powers and duties in administering the program for those proposals in which a four-year institution of higher education is named as the lead institution and fiscal agent:

. To adopt rules necessary to carry out the program;

. To award grants no later than September 1st in those years when funding is available by June 30th;

. To establish each biennium specific guidelines for submitting grant proposals consistent with RCW 28B.120.005 and consistent with the ten-year plan for higher education, the system design plan, the overall goals of the program and the guidelines established by the state board for community and technical colleges under RCW 28B.120.025.

After June 30, 2001, and each biennium thereafter, the council shall determine funding priorities for proposals for the biennium in consultation with the legislature, the office of the superintendent of public instruction, the state board for community and technical colleges, the workforce training and education coordinating board, higher education institutions, educational associations, and business and community groups consistent with statewide needs;

. To solicit grant proposals and provide information to the institutions of higher education about the program; and

. To establish reporting, evaluation, accountability, monitoring, and dissemination requirements for the recipients of the grants awarded by the office of financial management.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20572[2012 c 229 § 572]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20235[2011 1st sp.s. c 11 § 235]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6355-S.SL.pdf?cite=2010%20c%20245%20§%208[2010 c 245 § 8]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1013-S.SL.pdf?cite=1999%20c%20169%20§%203[1999 c 169 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2292-S2.SL.pdf?cite=1996%20c%2041%20§%202[1996 c 41 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1723.SL.pdf?cite=1991%20c%2098%20§%203[1991 c 98 § 3]; ]

== 28B.120.025 - Program administration—Powers and duties of state board for community and technical colleges.
The state board for community and technical colleges has the following powers and duties in administering the program for those proposals in which a community or technical college is named as the lead institution and fiscal agent:

. To adopt rules necessary to carry out the program;

. To establish one or more review committees to assist in the evaluation of proposals for funding. The review committee shall include individuals with significant experience in higher education in areas relevant to one or more of the funding period priorities and shall include representatives from both the four-year and two-year sectors of higher education;

. To award grants no later than September 1st in those years when funding is available by June 30th;

. To establish each biennium specific guidelines for submitting grant proposals consistent with the overall goals of the program and consistent with the guidelines established by the student achievement council under RCW 28B.120.020. During the 1999-01 biennium the guidelines shall be consistent with the following desired outcomes of:

.. Minority and diversity initiatives that encourage the participation of minorities in higher education, including students with disabilities;

.. K-12 teacher preparation models that encourage collaboration between higher education and K-12 to improve the preparedness of teachers, including provisions for higher education faculty involved with teacher preparation to spend time teaching in K-12 schools;

.. Collaborative instructional programs involving K-12, community and technical colleges, and four-year institutions of higher education to develop a three-year degree program, or reduce the time to degree;

.. Contracts with public or private institutions or businesses to provide services or the development of collaborative programs;

.. Articulation and transfer activities to smooth the transfer of students from K-12 to higher education, or from the community colleges and technical colleges to four-year institutions;

.. Projects that further the development of learner-centered, technology-assisted course delivery; and

.. Projects that further the development of competency-based measurements of student achievement to be used as the basis for awarding degrees and certificates;

. To solicit grant proposals and provide information to the community and technical colleges and private career schools; and

. To establish reporting, evaluation, accountability, monitoring, and dissemination requirements for the recipients of the grants awarded by the state board for community and technical colleges.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20573[2012 c 229 § 573]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1013-S.SL.pdf?cite=1999%20c%20169%20§%204[1999 c 169 § 4]; ]

== 28B.120.030 - Receipt of gifts, grants, and endowments.
The student achievement council and the state board for community and technical colleges may solicit and receive such gifts, grants, and endowments from public or private sources as may be made from time to time, in trust or otherwise, for the use and benefit of the purposes of the program and may expend the same or any income therefrom according to the terms of the gifts, grants, or endowments.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20574[2012 c 229 § 574]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1013-S.SL.pdf?cite=1999%20c%20169%20§%206[1999 c 169 § 6]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1723.SL.pdf?cite=1991%20c%2098%20§%204[1991 c 98 § 4]; ]

== 28B.120.040 - Student achievement council fund for innovation and quality.
The student achievement council fund for innovation and quality is hereby established in the custody of the state treasurer. The student achievement council shall deposit in the fund all moneys received under RCW 28B.120.030. Moneys in the fund may be spent only for the purposes of RCW 28B.120.010 and 28B.120.020. Disbursements from the fund shall be on the authorization of the student achievement council. The fund is subject to the allotment procedure provided under chapter 43.88 RCW, but no appropriation is required for disbursements.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20575[2012 c 229 § 575]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1013-S.SL.pdf?cite=1999%20c%20169%20§%207[1999 c 169 § 7]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2292-S2.SL.pdf?cite=1996%20c%2041%20§%203[1996 c 41 § 3]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1723.SL.pdf?cite=1991%20c%2098%20§%205[1991 c 98 § 5]; ]

== 28B.120.900 - Intent—1999 c 169.
It is the intent of the legislature to update and fund the higher education competitive grant program established by the 1991 legislature, known as the Washington fund for innovation and quality in higher education. Changes are needed so that the goals and priorities set forth for awarding grants reflect the 1999-01 goals and priorities. The legislature also intends to improve the administration of the program by separating responsibilities between the *higher education coordinating board and the state board for community and technical colleges.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1013-S.SL.pdf?cite=1999%20c%20169%20§%201[1999 c 169 § 1]; ]

