= 28B.63 - Commercial activities by institutions of higher education.
:toc:

== 28B.63.010 - Intent.
The primary mission of institutions of higher education is the creation and dissemination of knowledge. Institutions of higher education must be mindful that in providing goods and services for fees, they may be competing with local private businesses.

It is the intent of the legislature to require institutions of higher education to define the legitimate purposes under which commercial activities may be approved, and to establish a mechanism for review of such activities.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c97.pdf?cite=1987%20c%2097%20§%201[1987 c 97 § 1]; ]

== 28B.63.020 - Definitions.
For the purposes of this chapter:

. "Institutions of higher education" or "institutions" mean those institutions as defined in RCW 28B.10.016(4).

. "Commercial activity" means an activity which provides a product or service for a fee which could be obtained from a commercial source.

. "Fees" means any fees or charges imposed for goods, services, or facilities.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c97.pdf?cite=1987%20c%2097%20§%202[1987 c 97 § 2]; ]

== 28B.63.030 - Development of policies and mechanisms for defining and reviewing commercial activities.
Institutions of higher education in consultation with local business organizations and representatives of the small business community are required to develop:

. Comprehensive policies that define the legitimate purposes under which the institutions shall provide goods, services, or facilities that are practically available from private businesses;

. A mechanism for reviewing current and proposed commercial activities to ensure that activities are consistent with institutional policies; and

. A mechanism for receiving, reviewing, and responding to enquiries from private businesses about commercial activities carried on by institutions of higher education.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c97.pdf?cite=1987%20c%2097%20§%203[1987 c 97 § 3]; ]

== 28B.63.040 - Criteria for developing policies.
. The following criteria shall be considered in developing policies in regard to providing goods, services, or facilities to persons other than students, faculty, staff, patients, and invited guests:

.. The goods, services, or facilities represent a resource which is substantially and directly related to the institution's instructional, research, or public service mission, which is not practically available in the private marketplace and for which there is a demand from the external community.

.. Fees charged for the goods, services, or facilities shall take into account the full direct and indirect costs, overhead, and the price of such items in the private marketplace.

. The following criteria shall be considered in developing policies in regard to providing goods, services, or facilities to students, faculty, staff, patients, and invited guests:

.. The goods, services, or facilities are substantially and directly related to the institution's instructional, research, or public service mission.

.. Provision of the goods, services, or facilities on campus represents a special convenience to and supports the campus community, or facilitates extracurricular, public service, or on-campus residential life.

.. Fees charged for the goods, services, or facilities shall take into account the full direct and indirect costs, including overhead.

.. The adequacy of security procedures to ensure that the goods, services, or facilities are provided only to persons who are students, faculty, staff, patients, or invited guests.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c97.pdf?cite=1987%20c%2097%20§%204[1987 c 97 § 4]; ]

== 28B.63.050 - Programs and activities exempt from chapter.
This chapter shall not apply to the initiation of or changes in academic or vocational programs of instruction in the institutions' regular, extension, evening, or continuing education programs, or the fees therefor, fees for services provided in the practicum aspects of instruction, or research programs, and in extracurricular or residential life programs, including residence halls, food services, athletic and recreational programs, and performing arts programs.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c97.pdf?cite=1987%20c%2097%20§%205[1987 c 97 § 5]; ]

