= 28B.160 - Applicant criminal history.
:toc:

== 28B.160.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Admissions application" means an individual application to enroll as an undergraduate or graduate student at an institution of higher education.

. "Criminal record" or "criminal history" includes any record about a citation or arrest for criminal conduct, including any records relating to probable cause to arrest, and includes any record about a criminal or juvenile case filed with any court, whether or not the case resulted in a finding of guilt.

. "Institutions of higher education" means the state universities, the regional universities, The Evergreen State College, the community colleges, and the technical colleges that receive state funds.

. "Third-party admissions application" means an admissions application not controlled by the institution.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6582.SL.pdf?cite=2018%20c%2083%20§%201[2018 c 83 § 1]; ]

== 28B.160.020 - Admissions applications.
. Except as provided in subsection (2) of this section, an institution of higher education may not use an initial admissions application that requests information about the criminal history of the applicant.

. An institution of higher education may, but is not required to, use a third-party admissions application that contains information about the criminal history of the applicant if the institution of higher education posts a notice on its website stating that the institution of higher education may not automatically or unreasonably deny an applicant's admission or restrict access to campus residency based on an applicant's criminal history.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6582.SL.pdf?cite=2018%20c%2083%20§%202[2018 c 83 § 2]; ]

== 28B.160.030 - Authorized inquiries.
. After an applicant has otherwise been determined to be qualified for admission, an institution of higher education may, but is not required to, inquire into or obtain information about an applicant's criminal history for the purpose of:

.. Accepting or denying an applicant for admission to the institution of higher education or restricting access to campus residency; or

.. Offering supportive counseling or services to help rehabilitate and educate the student on barriers a criminal record may present.

. After inquiring into or obtaining information under this section, an institution of higher education may not automatically or unreasonably deny an applicant's admission or restrict access to campus residency based on that applicant's criminal history.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6582.SL.pdf?cite=2018%20c%2083%20§%203[2018 c 83 § 3]; ]

== 28B.160.040 - Process development.
. Each institution of higher education shall develop a process to determine whether or not there is a relationship between an applicant's criminal history and a specific academic program or campus residency to justify denial of admission or restrict access to campus residency.

. The process developed under this section shall be set forth in writing and shall include consideration of:

.. The age of the applicant at the time any aspect of the applicant's criminal history occurred;

.. The time that has elapsed since any aspect of the applicant's criminal history occurred;

.. The nature of the criminal history, including but not limited to whether the applicant was convicted of a "serious violent offense" or a "sex offense" as those terms are defined in RCW 9.94A.030; and

.. Evidence of rehabilitation or good conduct produced by the applicant.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6582.SL.pdf?cite=2018%20c%2083%20§%204[2018 c 83 § 4]; ]

== 28B.160.900 - Short title—2018 c 83.
This act may be known and cited as the Washington fair chance to education act.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6582.SL.pdf?cite=2018%20c%2083%20§%205[2018 c 83 § 5]; ]

