= 28B.85 - Degree-granting institutions.
:toc:

== 28B.85.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter:

. "Council" means the student achievement council.

. "Degree" means any designation, appellation, letters, or words including but not limited to "associate," "bachelor," "master," "doctor," or "fellow" which signify or purport to signify satisfactory completion of the requirements of an academic program of study beyond the secondary school level.

. "Degree-granting institution" means an entity that offers educational credentials, instruction, or services prerequisite to or indicative of an academic or professional degree beyond the secondary level.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20542[2012 c 229 § 542]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c136.pdf?cite=1986%20c%20136%20§%201[1986 c 136 § 1]; ]

== 28B.85.020 - Council's duties—Rule-making authority.
. The council:

.. Shall adopt by rule, in accordance with chapter 34.05 RCW, minimum standards for degree-granting institutions concerning granting of degrees, quality of education, unfair business practices, financial stability, and other necessary measures to protect citizens of this state against substandard, fraudulent, or deceptive practices. The rules shall require that an institution operating in Washington:

... Be accredited;

... Have applied for accreditation and such application is pending before the accrediting agency;

... Have been granted a waiver by the council waiving the requirement of accreditation; or

... Have been granted an exemption by the council from the requirements of this subsection (1)(a);

.. May investigate any entity the council reasonably believes to be subject to the jurisdiction of this chapter. In connection with the investigation, the council may administer oaths and affirmations, issue subpoenas and compel attendance, take evidence, and require the production of any books, papers, correspondence, memorandums, or other records which the council deems relevant or material to the investigation. The council, including its staff and any other authorized persons, may conduct site inspections, the cost of which shall be borne by the institution, and examine records of all institutions subject to this chapter;

.. May negotiate and enter into interstate reciprocity agreements with other state or multistate entities if the agreements are consistent with the purposes in this chapter as determined by the council;

.. May enter into agreements with degree-granting institutions of higher education based in this state, that are otherwise exempt under the provisions of subsection (1)(a) of this section, for the purpose of ensuring consistent consumer protection in interstate distance delivery of higher education;

.. Shall develop an interagency agreement with the workforce training and education coordinating board to regulate degree-granting private vocational schools with respect to degree and nondegree programs; and

.. Shall develop and disseminate information to the public about entities that sell or award degrees without requiring appropriate academic achievement at the postsecondary level, including but not limited to, a description of the substandard and potentially fraudulent practices of these entities, and advice about how the public can recognize and avoid the entities. To the extent feasible, the information shall include links to additional resources that may assist the public in identifying specific institutions offering substandard or fraudulent degree programs.

. Financial disclosures provided to the council by degree-granting private vocational schools are not subject to public disclosure under chapter 42.56 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1736.SL.pdf?cite=2013%20c%20218%20§%203[2013 c 218 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20543[2012 c 229 § 543]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2507-S.SL.pdf?cite=2006%20c%20234%20§%203[2006 c 234 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20246[2005 c 274 § 246]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2381-S.SL.pdf?cite=2004%20c%2096%20§%201[2004 c 96 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6174.SL.pdf?cite=1996%20c%20305%20§%201[1996 c 305 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6371-S.SL.pdf?cite=1994%20c%2038%20§%201[1994 c 38 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c136.pdf?cite=1986%20c%20136%20§%202[1986 c 136 § 2]; ]

== 28B.85.030 - Current authorization required to offer or grant degree—Penalty for violation.
. A degree-granting institution shall not operate and shall not grant or offer to grant any degree unless the institution has obtained current authorization from the council.

. Any person, group, or entity or any owner, officer, agent, or employee of such entity who willfully violates this section is guilty of a gross misdemeanor and shall be punished by a fine not to exceed one thousand dollars or by imprisonment in the county jail for a term not to exceed one year, or by both such fine and imprisonment. Each day on which a violation occurs constitutes a separate violation. The criminal sanctions may be imposed by a court of competent jurisdiction in an action brought by the attorney general of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20544[2012 c 229 § 544]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20175[2003 c 53 § 175]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c136.pdf?cite=1986%20c%20136%20§%203[1986 c 136 § 3]; ]

== 28B.85.040 - Completion of program of study prerequisite to degree—Application of chapter.
. An institution or person shall not advertise, offer, sell, or award a degree or any other type of educational credential unless the student has enrolled in and successfully completed a prescribed program of study, as outlined in the institution's publications. This prohibition shall not apply to honorary credentials clearly designated as such on the front side of the diploma or certificate and awarded by institutions offering other educational credentials in compliance with state law.

. No exemption or waiver granted under this chapter is permanent. The council shall periodically review exempted degree-granting institutions and degree-granting institutions granted a waiver, and continue exemptions or waivers only if an institution meets the statutory or council requirements for exemption or waiver in effect on the date of the review.

. Except as provided in subsection (1) of this section, this chapter shall not apply to:

.. Any public college, university, community college, technical college, or institute operating as part of the public higher educational system of this state;

.. Institutions that have been accredited by an accrediting association recognized by the council for the purposes of this chapter: PROVIDED, That those institutions meet minimum exemption standards adopted by the council; and PROVIDED FURTHER, That an institution, branch, extension, or facility operating within the state of Washington which is affiliated with an institution operating in another state must be a separately accredited member institution of any such accrediting association to qualify for this exemption;

.. Institutions of a religious character, but only as to those education programs devoted exclusively to religious or theological objectives if the programs are represented in an accurate manner in institutional catalogs and other official publications;

.. Honorary credentials clearly designated as such on the front side of the diploma or certificate awarded by institutions offering other educational credentials in compliance with state law; or

.. Institutions not otherwise exempt which offer only workshops or seminars and institutions offering only credit-bearing workshops or seminars lasting no longer than three calendar days.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20545[2012 c 229 § 545]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2507-S.SL.pdf?cite=2006%20c%20234%20§%204[2006 c 234 § 4]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2381-S.SL.pdf?cite=2004%20c%2096%20§%202[2004 c 96 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6177.SL.pdf?cite=1996%20c%2097%20§%201[1996 c 97 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6371-S.SL.pdf?cite=1994%20c%2038%20§%202[1994 c 38 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c136.pdf?cite=1986%20c%20136%20§%204[1986 c 136 § 4]; ]

== 28B.85.050 - Council may require information.
All degree-granting institutions subject to this chapter shall file information with the council as the council may require.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20546[2012 c 229 § 546]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c136.pdf?cite=1986%20c%20136%20§%205[1986 c 136 § 5]; ]

== 28B.85.060 - Fees.
The council shall impose fees on any degree-granting institution authorized to operate under this chapter. Fees shall be set and revised by the council by rule at the level necessary to approximately recover the staffing costs incurred in administering this chapter. Fees shall be deposited in the general fund.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20547[2012 c 229 § 547]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c136.pdf?cite=1986%20c%20136%20§%206[1986 c 136 § 6]; ]

== 28B.85.070 - Surety bonds—Security in lieu of bond—Cancellation of bond—Notice—Claims.
. The council may require any degree-granting institution to have on file with the council an approved surety bond or other security in lieu of a bond in an amount determined by the council.

. In lieu of a surety bond, an institution may deposit with the council a cash deposit or other negotiable security acceptable to the council. The security deposited with the council in lieu of the surety bond shall be returned to the institution one year after the institution's authorization has expired or been revoked if legal action has not been instituted against the institution or the security deposit at the expiration of the year. The obligations and remedies relating to surety bonds authorized by this section, including but not limited to the settlement of claims procedure in subsection (5) of this section, shall apply to deposits filed with the council, as applicable.

. Each bond shall:

.. Be executed by the institution as principal and by a corporate surety licensed to do business in the state;

.. Be payable to the state for the benefit and protection of any student or enrollee of an institution, or, in the case of a minor, his or her parents or guardian;

.. Be conditioned on compliance with all provisions of this chapter and the council's rules adopted under this chapter;

.. Require the surety to give written notice to the council at least thirty-five days before cancellation of the bond; and

.. Remain in effect for one year following the effective date of its cancellation or termination as to any obligation occurring on or before the effective date of cancellation or termination.

. Upon receiving notice of a bond cancellation, the council shall notify the institution that the authorization will be suspended on the effective date of the bond cancellation unless the institution files with the council another approved surety bond or other security. The council may suspend or revoke the authorization at an earlier date if it has reason to believe that such action will prevent students from losing their tuition or fees.

. If a complaint is filed under RCW 28B.85.090(1) against an institution, the council may file a claim against the surety and settle claims against the surety by following the procedure in this subsection.

.. The council shall attempt to notify all potential claimants. If the absence of records or other circumstances makes it impossible or unreasonable for the council to ascertain the names and addresses of all the claimants, the council after exerting due diligence and making reasonable inquiry to secure that information from all reasonable and available sources, may make a demand on a bond on the basis of information in the council's possession. The council is not liable or responsible for claims or the handling of claims that may subsequently appear or be discovered.

.. Thirty days after notification, if a claimant fails, refuses, or neglects to file with the council a verified claim, the council shall be relieved of further duty or action under this chapter on behalf of the claimant.

.. After reviewing the claims, the council may make demands upon the bond on behalf of those claimants whose claims have been filed. The council may settle or compromise the claims with the surety and may execute and deliver a release and discharge of the bond.

.. If the surety refuses to pay the demand, the council may bring an action on the bond in behalf of the claimants. If an action is commenced on the bond, the council may require a new bond to be filed.

.. Within ten days after a recovery on a bond or other posted security has occurred, the institution shall file a new bond or otherwise restore its security on file to the required amount.

. The liability of the surety shall not exceed the amount of the bond.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20548[2012 c 229 § 548]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c136.pdf?cite=1986%20c%20136%20§%207[1986 c 136 § 7]; ]

== 28B.85.080 - Suspension or modification of requirements authorized.
The council may suspend or modify any of the requirements under this chapter in a particular case if the council finds that:

. The suspension or modification is consistent with the purposes of this chapter; and

. The education to be offered addresses a substantial, demonstrated need among residents of the state or that literal application of this chapter would cause a manifestly unreasonable hardship.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20549[2012 c 229 § 549]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c136.pdf?cite=1986%20c%20136%20§%208[1986 c 136 § 8]; ]

== 28B.85.090 - Claims—Complaints—Investigations—Hearings—Orders.
. Complaints may be filed with the council under this chapter by a person claiming loss of tuition or fees as a result of an unfair business practice. The complaint shall set forth the alleged violation and shall contain information required by the council. A complaint may also be filed with the council by an authorized staff member of the council or by the attorney general.

. The council shall investigate any complaint under this section and may attempt to bring about a settlement. The council may hold a hearing pursuant to the Administrative Procedure Act, chapter 34.05 RCW, in order to determine whether a violation has occurred. If the council prevails, the degree-granting institution shall pay the costs of the administrative hearing.

. If, after the hearing, the council finds that the institution or its agent engaged in or is engaging in any unfair business practice, the council shall issue and cause to be served upon the violator an order requiring the violator to cease and desist from the act or practice and may impose the penalties under RCW 28B.85.095 and 28B.85.100. If the council finds that the complainant has suffered loss as a result of the act or practice, the council may order full or partial restitution for the loss. The complainant is not bound by the council's determination of restitution and may pursue any other legal remedy.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1439-S2.SL.pdf?cite=2018%20c%20203%20§%203[2018 c 203 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20550[2012 c 229 § 550]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%2082[1989 c 175 § 82]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c136.pdf?cite=1986%20c%20136%20§%209[1986 c 136 § 9]; ]

== 28B.85.095 - Council's authority to enforce compliance—Violations.
. [Empty]
.. The council may deny, revoke, or suspend the authorization of any degree-granting institution authorized to operate under this chapter that is found to be in violation of this chapter.

.. The council may not delegate to any other state its authority to oversee and enforce compliance with this chapter or its authority to respond to complaints by students in this state, regardless of whether the institution is authorized by, or has its home in, another state. Under RCW 28B.85.020(1)(c), participation in interstate reciprocity agreements consistent with the purposes of this chapter does not delegate authority for compliance with this chapter or authority to respond to student complaints.

. It is a violation of this chapter for a degree-granting institution authorized to operate under this chapter or an agent employed by such a degree-granting institution to:

.. Provide prospective students with any testimonial, endorsement, or other information that a reasonable person would find was likely to mislead or deceive prospective students or the public regarding current practices of the school, current conditions for employment opportunities, postgraduation employment by industry, or probable earnings in the occupation for which the education was designed, the likelihood of obtaining financial aid or low-interest loans for tuition, or the ability of graduates to repay loans;

.. Use any official United States military logo in advertising or promotional materials; or

.. Violate the provision of RCW 28B.85.175(1)(b) regarding the sale of, or inducing of students to obtain, specific consumer student loan products.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1439-S2.SL.pdf?cite=2018%20c%20203%20§%204[2018 c 203 § 4]; ]

== 28B.85.100 - Violations—Civil penalties.
Any person, group, or entity or any owner, officer, agent, or employee of such entity who willfully violates any provision of this chapter or the rules adopted under this chapter shall be subject to a civil penalty of not more than one hundred dollars for each violation. Each day on which a violation occurs constitutes a separate violation. The fine may be imposed by the council or by any court of competent jurisdiction.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20551[2012 c 229 § 551]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c136.pdf?cite=1986%20c%20136%20§%2010[1986 c 136 § 10]; ]

== 28B.85.120 - Actions resulting in jurisdiction of courts.
A degree-granting institution, whether located in this state or outside of this state, that conducts business of any kind, makes any offers, advertises, solicits, or enters into any contracts in this state or with a resident of this state is subject to the jurisdiction of the courts of this state for any cause of action arising from the acts.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c136.pdf?cite=1986%20c%20136%20§%2012[1986 c 136 § 12]; ]

== 28B.85.130 - Educational records—Permanent file—Protection.
If any degree-granting institution discontinues its operation, the chief administrative officer of the institution shall file with the council the original or legible true copies of all educational records required by the council. If the council determines that any educational records are in danger of being made unavailable to the council, the council may seek a court order to protect and if necessary take possession of the records. The council shall cause to be maintained a permanent file of educational records coming into its possession.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20552[2012 c 229 § 552]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c136.pdf?cite=1986%20c%20136%20§%2013[1986 c 136 § 13]; ]

== 28B.85.140 - Contracts voidable—When.
If a student or prospective student is a resident of this state at the time any contract relating to payment for education or any note, instrument, or other evidence of indebtedness relating thereto is entered into, RCW 28B.85.150 shall govern the rights of the parties to the contract or evidence of indebtedness. If a contract or evidence of indebtedness contains any of the following agreements, the contract is voidable at the option of the student or prospective student:

. That the law of another state shall apply;

. That the maker or any person liable on the contract or evidence of indebtedness consents to the jurisdiction of another state;

. That another person is authorized to confess judgment on the contract or evidence of indebtedness; or

. That fixes venue.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c136.pdf?cite=1986%20c%20136%20§%2014[1986 c 136 § 14]; ]

== 28B.85.150 - Enforceability of debts—Authority to offer degree required.
A note, instrument, or other evidence of indebtedness or contract relating to payment for education for a degree is not enforceable in the courts of this state by a degree-granting institution or holder of the instrument unless the institution was authorized to offer the degree under this chapter at the time the note, instrument, or other evidence of indebtedness or contract was entered into.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c136.pdf?cite=1986%20c%20136%20§%2015[1986 c 136 § 15]; ]

== 28B.85.160 - Actions to enforce chapter—Who may bring—Relief.
The attorney general or the prosecuting attorney of any county in which a degree-granting institution or agent of the institution is found may bring an action in any court of competent jurisdiction for the enforcement of this chapter. The court may issue an injunction or grant any other appropriate form of relief.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c136.pdf?cite=1986%20c%20136%20§%2016[1986 c 136 § 16]; ]

== 28B.85.170 - Injunctive relief—Council may seek.
The council may seek injunctive relief, after giving notice to the affected party, in a court of competent jurisdiction for a violation of this chapter or the rules adopted under this chapter. The council need not allege or prove that the council has no adequate remedy at law. The right of injunction provided in this section is in addition to any other legal remedy which the council has and is in addition to any right of criminal prosecution provided by law. The existence of council action with respect to alleged violations of this chapter and rules adopted under this chapter does not operate as a bar to an action for injunctive relief under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20553[2012 c 229 § 553]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c136.pdf?cite=1986%20c%20136%20§%2017[1986 c 136 § 17]; ]

== 28B.85.175 - Degree-granting institution requirements—Consumer protection act violations.
. A degree-granting institution authorized to operate under this chapter must:

.. Present data about its completion rates, employment rates, loan or indebtedness metrics, or its graduates' median hourly and annual earnings, the posted data consistent with the data posted on the workforce training and education coordinating board's career bridge web site or the data posted by the United States department of education, if the board or the department of education has posted such data;

.. Not engage in any practice regarding the sale of, or inducing of students to obtain, specific consumer student loan products to fund education that financially benefits any person or entity that has an ownership interest in the institution, unless the institution can demonstrate to the council that the student has exhausted all federal aid options and has been denied noninstitutional private commercial loan products. The prohibition in this subsection (1)(b) applies to any degree-granting institution authorized to operate under this chapter, and any agent of the institution, that has at least one hundred fifty students or more enrolled in the state in any given year or that has been operating in the state for less than two consecutive years. A financial benefit for purposes of this subsection (1)(b) does not include merely having an interest in students with loans enrolling in the institution or assisting students with financial aid matters. For purposes of this subsection (1)(b), "agent" means any employee, officer, or contractor working on behalf of the institution; and

.. Disclose to the council regarding any pending investigations by an oversight entity, including the nature of that investigation, within thirty days of the degree-granting institution's first knowledge of the investigation. For the purposes of this subsection, "investigation" means any inquiry into possible violations of any applicable laws or accreditation standards. For the purposes of this subsection, "oversight entity" means all of the following:

... Any federal or state entity that provides financial aid to students of the institution or approves the institution for participation in a financial aid program;

... Any state or federal attorney general's office or department of justice;

... Any regulator that approves the operation of the private vocational school;

... The federal consumer financial protection bureau or the federal securities and exchange commission; and

.. Any accrediting agency.

. A violation of any provision of this section is also a violation of RCW 19.86.020 of the consumer protection act. The penalties authorized pursuant to subsection (1) of this section do not preclude remedies available under the provisions of the consumer protection act.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1439-S2.SL.pdf?cite=2018%20c%20203%20§%205[2018 c 203 § 5]; ]

== 28B.85.180 - Violation of chapter unfair or deceptive practice under RCW  19.86.020.
A violation of this chapter or the rules adopted under this chapter affects the public interest and is an unfair or deceptive act or practice in violation of RCW 19.86.020 of the consumer protection act. The remedies and sanctions provided by this section shall not preclude application of other remedies and sanctions.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c136.pdf?cite=1986%20c%20136%20§%2018[1986 c 136 § 18]; ]

== 28B.85.190 - Remedies and penalties in chapter nonexclusive and cumulative.
The remedies and penalties provided for in this chapter are nonexclusive and cumulative and do not affect any other actions or proceedings.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c136.pdf?cite=1986%20c%20136%20§%2019[1986 c 136 § 19]; ]

== 28B.85.220 - False academic credentials—Unlawful acts—Violation of consumer protection act—Venue.
. It is unlawful for a person to:

.. Grant or award a false academic credential or offer to grant or award a false academic credential in violation of this section;

.. Represent that a credit earned or granted by the person, in violation of this section, can be applied toward a credential offered by another person; or

.. Solicit another person to seek a credential or to earn a credit that is offered in violation of this section.

. The definitions in RCW 9A.60.070 apply to this section.

. A violation of this section constitutes an unfair or deceptive act or practice in the conduct of trade or commerce under chapter 19.86 RCW.

. In addition to any other venue authorized by law, venue for the prosecution of an offense under this section is in the county in which an element of the offense occurs.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2507-S.SL.pdf?cite=2006%20c%20234%20§%201[2006 c 234 § 1]; ]

== 28B.85.230 - Student achievement council tuition recovery trust fund.
. [Empty]
.. For the purpose of providing relief to students impacted by the voluntary or involuntary closure of schools regulated under this chapter, the council shall establish, maintain, and administer a student achievement council tuition recovery trust fund created in RCW 28B.85.240. All funds collected for the student achievement council tuition recovery trust fund are payable to the state for the benefit and protection of any student or enrollee of a private school licensed under this chapter, for purposes including but not limited to the settlement of claims related to school closures.

.. No liability accrues to the state from claims made against the student achievement council tuition recovery trust fund.

. [Empty]
.. The council may impose a fee structure, set forth in rule, on schools licensed under this chapter to fund the student achievement council tuition recovery trust fund.

.. The council must determine an amount that would be sufficient in the student achievement council tuition recovery trust fund to provide relief to students in the event of a school closure. The council shall adopt schedules of times and amounts for effecting payments of fees. To reach the amount determined, the council may phase in the collection of fees, but must achieve the amount determined to be sufficient no later than five years from June 7, 2018.

. Money from the student achievement council tuition recovery trust fund may be used for:

.. Providing refunds to students affected by school closures;

.. Securing and administering student records; and

.. Any other response the council determines is necessary to mitigate impacts of a potential or actual school closure.

. In order for a school to be and remain licensed under this chapter, each school owner shall, in addition to other requirements under this chapter, make cash deposits on behalf of the school into a student achievement council tuition recovery trust fund.

. The student achievement council tuition recovery trust fund's liability with respect to each participating school commences on the date of the initial deposit into the student achievement council tuition recovery trust fund made on its behalf and ceases one year from the date the school is no longer licensed under this chapter.

. The council shall adopt by rule a matrix for calculating the deposits into the student achievement council tuition recovery trust fund on behalf of each school.

. No vested right or interest in deposited funds is created or implied for the depositor at any time during the operation of the student achievement council tuition recovery trust fund or at any such future time that the student achievement council tuition recovery trust fund may be dissolved. All funds deposited are payable to the state for the purposes described under this section. The council shall maintain the student achievement council tuition recovery trust fund, serve appropriate notices to affected owners when scheduled deposits are due, collect deposits, and make disbursements to settle claims against the student achievement council tuition recovery trust fund.

. The council shall adopt rules to address notifying potential claimants, settling claims, disbursing funds, and any other processes necessary to implement the purpose of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1439-S2.SL.pdf?cite=2018%20c%20203%20§%2011[2018 c 203 § 11]; ]

== 28B.85.240 - Student achievement council tuition recovery trust fund—State treasurer.
The student achievement council tuition recovery trust fund is created in the custody of the state treasurer. All receipts from fees imposed on schools licensed under this chapter and RCW 28B.85.230 must be deposited into the fund. Expenditures from the fund may be used only for the purposes in RCW 28B.85.230. Only the council may authorize expenditures from the fund. The fund is subject to allotment procedures under chapter 43.88 RCW, but an appropriation is not required for expenditures.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1439-S2.SL.pdf?cite=2018%20c%20203%20§%2012[2018 c 203 § 12]; ]

== 28B.85.902 - Effective date—1986 c 136.
This act shall take effect July 1, 1986.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c136.pdf?cite=1986%20c%20136%20§%2024[1986 c 136 § 24]; ]

== 28B.85.905 - Validity of registration under prior laws.
A degree-granting institution registered under chapter 188, Laws of 1979, as amended, as of June 30, 1986, is not required to apply for authorization under chapter 28B.85 RCW until the expiration date of such registration.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c136.pdf?cite=1986%20c%20136%20§%2022[1986 c 136 § 22]; ]

== 28B.85.906 - Application of chapter to foreign degree-granting institution branch campuses.
This chapter shall not apply to any approved branch campus of a foreign degree-granting institution in compliance with chapter 28B.90 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1497-S.SL.pdf?cite=1993%20c%20181%20§%207[1993 c 181 § 7]; ]

