= 28B.142 - Local borrowing authority—Research universities.
:toc:

== 28B.142.005 - Finding—Intent.
The legislature hereby recognizes that the University of Washington and Washington State University will require additional methods of funding to meet the universities' educational and research missions and remain competitive in a challenging environment. State appropriations are sufficient to meet only a portion of these research universities' funding requirements. The state authorizes the universities to collect student tuition, services and activities fees, building fees, and technology fees, subject to statutory limits. In addition, the universities generate revenue from other sources such as grants, contracts, other fees, sales and services, and investment income. The legislature finds that the research universities are able to leverage these local nonstate-appropriated funds to enhance university facilities and services for the benefit of students, faculty, and the larger community. The legislature intends that the research universities be permitted to borrow and incur obligations for any university purpose, so long as repayment is limited to local nonappropriated university funds and so long as the state's credit or general state revenues are not obligated or used for repayment. To permit the University of Washington to refinance the real and personal property acquired between August and October 2006 before the end of the fiscal biennium, sections of chapter 24, Laws of 2007 necessary to accomplish this limited purpose are made effective before the end of the biennium.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1398-S.SL.pdf?cite=2007%20c%2024%20§%201[2007 c 24 § 1]; ]

== 28B.142.010 - Bonds, notes, evidences of indebtedness—University of Washington and Washington State University.
The board of regents of the University of Washington and Washington State University may issue bonds, notes, or other evidences of indebtedness for any university purpose. The board of regents of the University of Washington and Washington State University may obligate all or a component of the fees and revenues of the university for the payment of such bonds, notes, or evidences of indebtedness: PROVIDED, That such fees and revenues are not subject to appropriation by the legislature and do not constitute general state revenues as defined in Article VIII, section 1 of the state Constitution. Such bonds, notes, and other indebtedness shall not constitute bonds, notes, or other evidences of indebtedness secured by the full faith and credit of the state or required to be paid, directly or indirectly, from general state revenues. Bonds, notes, or other evidences of indebtedness issued under this chapter shall be issued in accordance with the procedures in RCW 28B.10.310 and 28B.10.315 or the provisions applicable to either the state or local governments under chapter 39.46 or 39.53 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5537-S.SL.pdf?cite=2009%20c%20500%20§%204[2009 c 500 § 4]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1398-S.SL.pdf?cite=2007%20c%2024%20§%202[2007 c 24 § 2]; ]

== 28B.142.020 - Reports.
The University of Washington and Washington State University must report annually to the ways and means committee of the senate, the capital budget committee of the house of representatives, and the office of the state treasurer on any bonds, notes, and other evidences of indebtedness issued under this chapter as a part of a public securities offering. The report shall include a summary of the total outstanding debt of the university, a summary of any public securities offerings issued that year by purpose, including rating information from at least one nationally recognized credit rating agency, issuance costs, interest rate information, sources of repayment, and a copy of the annual bondholder report filed by the University of Washington and Washington State University in accordance with Rule 15c2-12 of the securities and exchange commission.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1398-S.SL.pdf?cite=2007%20c%2024%20§%203[2007 c 24 § 3]; ]

== 28B.142.030 - Bonds, notes, evidences of indebtedness—University of Washington—Refinancing.
The board of regents of the University of Washington may issue bonds, notes, or other evidences of indebtedness under this section for the purpose of refinancing real and personal property acquired by the University of Washington during the period between August and October 2006. The board of regents of the University of Washington may obligate all or a component of the fees and revenues of the university for the payment of such bonds, notes, or evidences of indebtedness: PROVIDED, That such fees and revenues are not subject to appropriation by the legislature and do not constitute general state revenues as defined in Article VIII, section 1 of the state Constitution. Bonds, notes, or other evidences of indebtedness issued under this section shall be issued in accordance with the procedures in RCW 28B.10.310 and 28B.10.315 or the provisions applicable to either the state or local governments under chapter 39.46 or 39.53 RCW. Such bonds, notes, and other indebtedness shall not constitute bonds, notes, or other evidences of indebtedness secured by the full faith and credit of the state or required to be paid, directly or indirectly, from general state revenues.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5537-S.SL.pdf?cite=2009%20c%20500%20§%205[2009 c 500 § 5]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1398-S.SL.pdf?cite=2007%20c%2024%20§%204[2007 c 24 § 4]; ]

== 28B.142.040 - Authority of chapter—Supplemental.
The authority granted by this chapter is in addition and supplemental to any previously granted or future authority granted to the University of Washington or Washington State University and shall not be construed to limit the existing or future powers or authority of these universities, including without limitation the authority to issue bonds, notes, and other evidences of indebtedness pursuant to RCW 28B.10.300 through 28B.10.330, 28B.20.145, or 28B.20.395 through 28B.20.398, or chapter 28B.140 RCW, or to participate in state reimbursable bond, certificate of participation, or other state debt programs.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1398-S.SL.pdf?cite=2007%20c%2024%20§%205[2007 c 24 § 5]; ]

