= 28B.133 - Gaining independence for students with dependents program.
:toc:

== 28B.133.005 - Finding—Intent.
The legislature finds that financially needy students, especially those with dependents, are finding it increasingly difficult to stay in school due to the high costs of caring for their dependent children.

The legislature intends to establish an educational assistance grant program, funded through gifts, grants, or endowments from private sources, for students with dependents who have additional financial needs due to the care they provide for their dependents eighteen years of age or younger.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1277-S.SL.pdf?cite=2003%20c%2019%20§%201[2003 c 19 § 1]; ]

== 28B.133.010 - Program created.
The educational assistance grant program for students with dependents is hereby created, subject to the availability of receipts of gifts, grants, or endowments from private sources. The program is created to serve students who demonstrate financial need with dependents eighteen years of age or younger, by assisting them directly through a grant program to pursue a degree or certificate at public or private institutions of higher education, as defined in RCW 28B.92.030(4) (a) and (b) (i) and (ii), that participate in the Washington college grant program.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2158-S2.SL.pdf?cite=2019%20c%20406%20§%2046[2019 c 406 § 46]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5195-S.SL.pdf?cite=2013%20c%20248%20§%204[2013 c 248 § 4]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/3103-S.SL.pdf?cite=2004%20c%20275%20§%2072[2004 c 275 § 72]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1277-S.SL.pdf?cite=2003%20c%2019%20§%202[2003 c 19 § 2]; ]

== 28B.133.020 - Eligibility.
To be eligible for the educational assistance grant program for students with dependents, applicants shall: (1) Be residents of the state of Washington; (2) be students who demonstrate financial need as defined in RCW 28B.92.030; (3) be eligible to participate in the Washington college grant program as set forth under chapter 28B.92 RCW; and (4) have dependents eighteen years of age or younger who are under their care.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2158-S2.SL.pdf?cite=2019%20c%20406%20§%2047[2019 c 406 § 47]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/3103-S.SL.pdf?cite=2004%20c%20275%20§%2073[2004 c 275 § 73]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1277-S.SL.pdf?cite=2003%20c%2019%20§%203[2003 c 19 § 3]; ]

== 28B.133.030 - Solicitation of gifts, grants, or endowments—Use.
The office may solicit and receive gifts, grants, or endowments from private sources that are made from time to time, in trust or otherwise, for the use and benefit of the purposes of the educational assistance grant program. The director, or the director's designee, may spend gifts, grants, or endowments or income from the private sources according to their terms unless the receipt of the gifts, grants, or endowments violates RCW 42.17A.560.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6581-S.SL.pdf?cite=2012%20c%20198%20§%2024[2012 c 198 § 24]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20236[2011 1st sp.s. c 11 § 236]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1048-S.SL.pdf?cite=2011%20c%2060%20§%2012[2011 c 60 § 12]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1277-S.SL.pdf?cite=2003%20c%2019%20§%204[2003 c 19 § 4]; ]

== 28B.133.040 - Program administration.
The office of student financial assistance shall develop and administer the educational assistance grant program for students with dependents. In administering the program, once the balance in the students with dependents grant account is five hundred thousand dollars, the office's powers and duties shall include but not be limited to:

. Adopting necessary rules and guidelines;

. Publicizing the program;

. Accepting and depositing donations into the grant account established in *RCW 28B.133.030; and

. Soliciting and accepting grants and donations from private sources for the program.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20237[2011 1st sp.s. c 11 § 237]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1277-S.SL.pdf?cite=2003%20c%2019%20§%205[2003 c 19 § 5]; ]

== 28B.133.050 - Use of grants.
The educational assistance grant program for students with dependents grants may be used by eligible participants to attend any public or private college or university in the state of Washington as defined in RCW 28B.92.030(4) (a) and (b) (i) and (ii). Each participating student may receive an amount to be determined by the office of student financial assistance, with a minimum amount of one thousand dollars per academic year, not to exceed the student's documented financial need for the course of study as determined by the institution.

Educational assistance grants for students with dependents are not intended to supplant any grant scholarship or tax program related to postsecondary education. If the office of student financial assistance finds that the educational assistance grants for students with dependents supplant or reduce any grant, scholarship, or tax program for categories of students, then the office shall adjust the financial eligibility criteria or the amount of the grant to the level necessary to avoid supplanting.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5195-S.SL.pdf?cite=2013%20c%20248%20§%205[2013 c 248 § 5]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20238[2011 1st sp.s. c 11 § 238]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/3103-S.SL.pdf?cite=2004%20c%20275%20§%2074[2004 c 275 § 74]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1277-S.SL.pdf?cite=2003%20c%2019%20§%206[2003 c 19 § 6]; ]

== 28B.133.900 - Short title.
This chapter may be known and cited as the gaining independence for students with dependents program.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1277-S.SL.pdf?cite=2003%20c%2019%20§%207[2003 c 19 § 7]; ]

