= 28B.99 - Medical student loan program.
:toc:

== 28B.99.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Eligible student" means a resident student who is enrolled in an accredited doctor of medicine or doctor of osteopathic medicine program in the state, is making satisfactory progress, and has declared an intention to work as a physician in a rural underserved area in Washington following residency.

. "Medical student loan" means a loan that is approved by the office and awarded to a participant under the program.

. "Office" means the office of student financial assistance.

. "Participant" means an eligible student who has received a medical student loan under the program.

. "Program" means the medical student loan program.

. "Rural underserved area" means a rural county as defined in RCW 82.14.370 that is also designated by the health resources and services administration as a medically underserved area or having a medically underserved population.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2143-S2.SL.pdf?cite=2018%20c%20209%20§%201[2018 c 209 § 1]; ]

== 28B.99.020 - Office powers and duties.
The medical student loan program is established to increase the physician workforce in rural underserved areas in Washington state. The program must be funded exclusively with private funding for the purpose of providing medical student loans. State funding may be used for the administration of the program. The office shall administer the program and has the following powers and duties:

. To design and implement a low interest medical student loan program with the following elements:

.. A low interest rate, comparable to or more favorable than the federal direct loan program, with interest charges that begin to accrue once the participant finishes his or her medical residency program;

.. An annual loan limit not to exceed forty thousand dollars and no more than the participant's estimated cost of attendance as determined by his or her medical program;

.. Loan repayments that do not commence until:

... Six months after the participant completes his or her medical residency program; or

... Six months after a participant leaves his or her doctor of medicine program, doctor of osteopathic medicine program, or medical residency program before completing; and

.. An interest rate of at least twelve percent plus capitalized interest that was deferred during the participant's doctor of medicine or doctor of osteopathic medicine program, and residency program, if the participant does not work as a physician in a rural underserved area in Washington for three years following completion of his or her medical residency program;

. To establish an application, selection, and notification process for awarding medical student loans to eligible students;

. To define the terms of repayment, including applicable interest rates, fees, and deferments;

. To collect and manage repayments on the medical student loans;

. To solicit and accept grants and donations from nonstate public and private sources for the program;

. To exercise discretion to revise repayment obligations in certain cases, such as economic hardship or disability;

. To publicize the program; and

. To adopt necessary rules.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2143-S2.SL.pdf?cite=2018%20c%20209%20§%202[2018 c 209 § 2]; ]

== 28B.99.030 - Medical student loan account.
. The medical student loan account is created in the custody of the state treasurer. Only the executive director of the office or the executive director's designee may authorize expenditures from the account. No appropriation is required for expenditures from the account for medical student loans. An appropriation is required for expenditures from the account for costs associated with program administration by the office.

. The office shall deposit into the account all moneys received for the program. Revenues to the account consist of moneys received for the program by the office, including grants and donations, and receipts from participant repayments, including principal and interest.

. Expenditures from the account may be used solely for medical student loans to participants in the program established by this chapter and costs associated with program administration by the office.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2143-S2.SL.pdf?cite=2018%20c%20209%20§%203[2018 c 209 § 3]; ]

== 28B.99.040 - Office annual report.
. The office shall submit an annual report regarding the program to the governor and the appropriate committees of the legislature in accordance with the reporting requirements in RCW 43.01.036.

. The annual report shall describe the design and implementation of the program, and must include the following:

.. The number of applicants for medical student loans;

.. The number of participants in the program;

.. The number of participants in the program who complete their medical program;

.. The number of participants in the program who are placed in employment;

.. The nature of that employment, including the type of job; whether the job is full-time, part-time, or temporary; and the income range;

.. Whether the participant is working in a rural underserved area, and what percent of the participant's patients are served by medicaid, the children's health insurance program, apple health, or other programs with similar eligibility requirements;

.. Demographic profiles of both applicants and participants;

.. The amount of the private funding collected for the program; and

.. An estimate of when the program will be self-sustaining.

. The annual report must be submitted by December 1st of each year after July 1, 2020.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2143-S2.SL.pdf?cite=2018%20c%20209%20§%204[2018 c 209 § 4]; ]

