= 28B.20 - University of Washington.
:toc:

== 28B.20.010 - Designation.
The state university located and established in Seattle, King county, shall be designated the University of Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.010[1969 ex.s. c 223 § 28B.20.010]; 1909 c 97 p 238 § 1; RRS § 4544; prior:  1897 c 118 § 182; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c395.pdf?cite=1890%20p%20395%20§%201[1890 p 395 § 1]; ]

== 28B.20.020 - Purpose.
The aim and purpose of the University of Washington shall be to provide a liberal education in literature, science, art, law, medicine, military science and such other fields as may be established therein from time to time by the board of regents or by law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.020[1969 ex.s. c 223 § 28B.20.020]; 1909 c 97 p 238 § 2; RRS § 4545; prior:  1897 c 118 § 183; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1893c122.pdf?cite=1893%20c%20122%20§%206[1893 c 122 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c395.pdf?cite=1890%20p%20395%20§%202[1890 p 395 § 2]; ]

== 28B.20.054 - Credits—Statewide transfer policy and agreement—Establishment.
See RCW 28B.77.210 and 28B.77.215.

[ ]

== 28B.20.055 - "Major line" defined.
See RCW 28B.10.100.

[ ]

== 28B.20.057 - Major lines common to University of Washington and Washington State University.
See RCW 28B.10.115.

[ ]

== 28B.20.060 - Courses exclusive to University of Washington.
Except as provided in RCW 28B.30.058, the courses of instruction of the University of Washington shall embrace as exclusive major lines, law, medicine, forest products, logging engineering, library sciences, and fisheries.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1559-S.SL.pdf?cite=2015%20c%206%20§%203[2015 c 6 § 3]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5276-S.SL.pdf?cite=2009%20c%20207%20§%202[2009 c 207 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c218.pdf?cite=1985%20c%20218%20§%202[1985 c 218 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.060[1969 ex.s. c 223 § 28B.20.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c23.pdf?cite=1963%20c%2023%20§%201[1963 c 23 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c71.pdf?cite=1961%20c%2071%20§%201[1961 c 71 § 1]; prior:   1917 c 10 § 2; RRS § 4533.   1917 c 10 § 5; RRS § 4536. Formerly RCW  28.77.025; 28.76.060; ]

== 28B.20.100 - Regents—Appointment—Terms—Vacancies—Quorum.
. The governance of the University of Washington shall be vested in a board of regents to consist of ten members, one of whom shall be a student. The governor shall select the student member from a list of candidates, of at least three and not more than five, submitted by the governing body of the associated students. They shall be appointed by the governor with the consent of the senate, and, except for the student member, shall hold their offices for a term of six years from the first day of October and until their successors shall be appointed and qualified. The student member shall hold his or her office for a term of one year from the first day of July until the first day of July of the following year or until his or her successor is appointed and qualified, whichever is later. The student member shall be a full-time student in good standing at the university at the time of appointment.

. Six members of said board shall constitute a quorum for the transaction of business. In the case of a vacancy, or when an appointment is made after the date of the expiration of a term, the governor shall fill the vacancy for the remainder of the term of the regent whose office has become vacant or expired.

. Except for the term of the student member, no more than the terms of two members will expire simultaneously on the last day of September in any one year.

. A student appointed under this section shall excuse himself or herself from participation or voting on matters relating to the hiring, discipline, or tenure of faculty members and personnel.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2857.SL.pdf?cite=2006%20c%2078%20§%201[2006 c 78 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5517-S.SL.pdf?cite=1998%20c%2095%20§%201[1998 c 95 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c61.pdf?cite=1985%20c%2061%20§%201[1985 c 61 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c103.pdf?cite=1979%20ex.s.%20c%20103%20§%202[1979 ex.s. c 103 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c62.pdf?cite=1973%20c%2062%20§%207[1973 c 62 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.100[1969 ex.s. c 223 § 28B.20.100]; 1909 c 97 p 239 § 3; RRS § 4554; prior:  1897 c 118 § 184; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c101.pdf?cite=1895%20c%20101%20§%201[1895 c 101 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c396.pdf?cite=1890%20p%20396%20§%203[1890 p 396 § 3]; ]

== 28B.20.105 - Regents—Organization and conduct of business—Bylaws, rules and regulations—Open public meetings.
The board shall organize by electing from its membership a president and an executive committee, of which committee the president shall be ex officio chair. The board may adopt bylaws or rules and regulations for its own government and shall follow procedures for open public meetings in chapter 42.30 RCW. The board shall provide time for public comment at each meeting. The board shall hold regular quarterly meetings, and during the interim between such meetings the executive committee may transact business for the whole board: PROVIDED, That the executive committee may call special meetings of the whole board when such action is deemed necessary.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2313-S.SL.pdf?cite=2012%20c%20228%20§%201[2012 c 228 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20717[2011 c 336 § 717]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.105[1969 ex.s. c 223 § 28B.20.105]; 1909 c 97 p 240 § 4; RRS § 4555; prior:  1897 c 118 § 185. Formerly RCW  28.77.100.  1939 c 176 § 1, part; 1927 c 227 § 1, part; 1909 c 97 p 240 § 5, part; RRS § 4557, part; ]

== 28B.20.110 - Regents—Secretary—Treasurer—Duties—Treasurer's bond.
The board shall appoint a secretary and a treasurer who shall hold their respective offices during the pleasure of the board and carry out such respective duties as the board shall prescribe. In addition to such other duties as the board prescribes, the secretary shall record all proceedings of the board and carefully preserve the same. The treasurer shall give bond for the faithful performance of the duties of his or her office in such amount as the regents may require: PROVIDED, That the university shall pay the fee for such bond.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20718[2011 c 336 § 718]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.110[1969 ex.s. c 223 § 28B.20.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c396.pdf?cite=1890%20p%20396%20§%206[1890 p 396 § 6]; RRS § 4556; ]

== 28B.20.115 - Regents—Oaths.
See RCW 28B.10.520.

[ ]

== 28B.20.116 - Regents—Expenses.
See RCW 28B.10.525.

[ ]

== 28B.20.117 - Regents—Attorney general as advisor.
See RCW 28B.10.510.

[ ]

== 28B.20.130 - Powers and duties of regents—General.
General powers and duties of the board of regents are as follows:

. To have full control of the university and its property of various kinds, except as otherwise provided by law.

. To employ the president of the university, his or her assistants, members of the faculty, and employees of the institution, who except as otherwise provided by law, shall hold their positions during the pleasure of said board of regents.

. Establish entrance requirements for students seeking admission to the university which meet or exceed the standards specified under RCW 28B.77.020. Completion of examinations satisfactory to the university may be a prerequisite for entrance by any applicant at the university's discretion. Evidence of completion of public high schools and other educational institutions whose courses of study meet the approval of the university may be acceptable for entrance.

. Establish such colleges, schools, or departments necessary to carry out the purpose of the university and not otherwise proscribed by law.

. With the assistance of the faculty of the university, prescribe the course of study in the various colleges, schools, and departments of the institution and publish the necessary catalogues thereof.

. Grant to students such certificates or degrees as recommended for such students by the faculty. The board, upon recommendation of the faculty, may also confer honorary degrees upon persons other than graduates of this university in recognition of their learning or devotion to literature, art, or science: PROVIDED, That no degree shall ever be conferred in consideration of the payment of money or the giving of property of whatsoever kind.

. Accept such gifts, grants, conveyances, bequests, and devises, whether real or personal property, or both, in trust or otherwise, for the use or benefit of the university, its colleges, schools, departments, or agencies; and sell, lease or exchange, invest or expend the same or the proceeds, rents, profits, and income thereof except as limited by the terms of said gifts, grants, conveyances, bequests, and devises. The board shall adopt proper rules to govern and protect the receipt and expenditure of the proceeds of all fees, and the proceeds, rents, profits, and income of all gifts, grants, conveyances, bequests, and devises above-mentioned.

. Except as otherwise provided by law, to enter into such contracts as the regents deem essential to university purposes.

. To submit upon request such reports as will be helpful to the governor and to the legislature in providing for the institution.

. To offer new degree programs, offer off-campus programs, participate in consortia or centers, contract for off-campus educational programs, and purchase or lease major off-campus facilities in accordance with RCW 28B.77.080.

. To confer honorary degrees upon persons who request an honorary degree if they were students at the university in 1942 and did not graduate because they were ordered into an internment camp. The honorary degree may also be requested by a representative of deceased persons who meet these requirements. For the purposes of this subsection, "internment camp" means a relocation center to which persons were ordered evacuated by Presidential Executive Order 9066, signed February 19, 1942.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20804[2012 c 229 § 804]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6467.SL.pdf?cite=2010%20c%2051%20§%201[2010 c 51 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/3103-S.SL.pdf?cite=2004%20c%20275%20§%2052[2004 c 275 § 52]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%2016[1998 c 245 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c370.pdf?cite=1985%20c%20370%20§%2092[1985 c 370 § 92]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977c75.pdf?cite=1977%20c%2075%20§%2020[1977 c 75 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.130[1969 ex.s. c 223 § 28B.20.130]; 1939 c 176 § 1, part; 1927 c 227 § 1, part; 1909 c 97 p 240 § 5, part; RRS § 4557, part; prior: 1895 c 101 § 2, part; 1893 c 122 § 10, part; 1890 pp 396, 397, 398 §§ 7, 9, 11; ]

== 28B.20.134 - Powers and duties of regents—Consent to sale of university granted lands.
See RCW 79.11.010.

[ ]

== 28B.20.135 - Powers and duties of regents—Employment of architects, engineers, for construction of buildings and facilities.
The board shall have power to employ or contract for the services of skilled architects and engineers to prepare plans and specifications, and supervise the construction of university buildings and facilities and to fix the compensation for such employees or for such services.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.135[1969 ex.s. c 223 § 28B.20.135]; 1909 c 97 p 242 § 10; RRS § 4563; ]

== 28B.20.140 - Powers and duties of regents—Contracts for erection of buildings or improvements.
The board of regents shall enter into such contracts with one or more contractors for the erection and construction of university buildings or improvements thereto as in their judgment shall be deemed for the best interest of the university; such contract or contracts shall be let after public notice and under such regulations as shall be established by said board or as otherwise provided by law to the person or persons able to perform the same on the most advantageous terms: PROVIDED, That in all cases said board shall require from contractors a good and sufficient bond for the faithful performance of the work, and the full protection of the state against mechanics' and other liens: AND PROVIDED FURTHER, That the board shall not have the power to enter into any contract for the erection of any buildings or improvements which shall bind said board to pay out any sum of money in excess of the amount provided for said purpose.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.140[1969 ex.s. c 223 § 28B.20.140]; 1909 c 97 p 242 § 9; RRS § 4562; ]

== 28B.20.145 - Powers and duties of regents—Regents' spending limited by income.
The board of regents are hereby prohibited from creating any debt or in any manner encumbering the university beyond its capacity for payment thereof from the biennial income of the university for the then current biennium.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.145[1969 ex.s. c 223 § 28B.20.145]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c399.pdf?cite=1890%20p%20399%20§%2020[1890 p 399 § 20]; RRS § 4566; ]

== 28B.20.150 - Endowment investments—Disclosure of private fund information—Conflicts of interest.
The University of Washington must disclose: (1) The names and commitment amounts of the private funds in which it is invested; and (2) the aggregate quarterly performance results for its portfolio of investments in such funds. The University of Washington shall have formal policies addressing conflicts of interest in regard to the private funds in which the endowment is invested, in compliance with RCW 42.52.190, and shall post these policies on their public website.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1640.SL.pdf?cite=2009%20c%20394%20§%202[2009 c 394 § 2]; ]

== 28B.20.200 - Faculty—Composition—General powers.
The faculty of the University of Washington shall consist of the president of the university and the professors and the said faculty shall have charge of the immediate government of the institution under such rules as may be prescribed by the board of regents.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.200[1969 ex.s. c 223 § 28B.20.200]; 1909 c 97 p 241 § 6; RRS § 4558; prior:  1897 c 118 § 187; ]

== 28B.20.250 - Liability coverage of university personnel and students—Authorized—Scope.
The board of regents of the University of Washington, subject to such conditions and limitations and to the extent it may prescribe, is authorized to provide by purchase of insurance, by self-insurance, or by any combination of arrangements, indemnification of regents, officers, employees, agents, and students from liability on any action, claim, or proceeding instituted against them arising out of the performance or failure of performance, of duties for or employment with the university, or of responsibilities imposed by approved programs of the university, and to hold such persons harmless from any expenses connected with the defense, settlement, or payment of monetary judgments from such action, claim, or proceeding.

[ 1975-'76 2nd ex.s. c 12 § 1; ]

== 28B.20.253 - Liability coverage of university personnel and students—Self-insurance revolving fund.
. A self-insurance revolving fund in the custody of the university is hereby created to be used solely and exclusively by the board of regents of the University of Washington for the following purposes:

.. The payment of judgments against the university, its schools, colleges, departments, and hospitals and against its regents, officers, employees, agents, and students for whom the defense of an action, claim, or proceeding has been provided pursuant to RCW 28B.20.250.

.. The payment of claims against the university, its schools, colleges, departments, and hospitals and against its regents, officers, employees, agents, and students for whom the defense of an action, claim, or proceeding has been provided pursuant to RCW 28B.20.250: PROVIDED, That payment of claims in excess of twenty-five thousand dollars must be approved by the state attorney general.

.. For the cost of investigation, administration, and defense of actions, claims, or proceedings, and other purposes essential to its liability program.

. Said self-insurance revolving fund shall consist of periodic payments by the University of Washington from any source available to it in such amounts as are deemed reasonably necessary to maintain the fund at levels adequate to provide for the anticipated cost of payments of incurred claims and other costs to be charged against the fund.

. No money shall be paid from the self-insurance revolving fund unless first approved by the board of regents, and unless all proceeds available to the claimant from any valid and collectible liability insurance shall have been exhausted.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5954.SL.pdf?cite=1997%20c%20288%20§%201[1997 c 288 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1058-S.SL.pdf?cite=1991%20sp.s.%20c%2013%20§%20117[1991 sp.s. c 13 § 117]; 1975-'76 2nd ex.s. c 12 § 2; ]

== 28B.20.255 - Liability coverage of university personnel and students—As exclusive authority.
RCW 28B.20.250 through 28B.20.255 constitutes the exclusive authority for the board of regents of the University of Washington to provide liability coverage for its regents, officers, employees, agents, and students, and further provides the means for defending and payment of all such actions, claims, or proceedings. RCW 28B.20.250 through 28B.20.255 shall govern notwithstanding the provisions of chapter 4.92 RCW and RCW 28B.10.842 and 28B.10.844.

[ 1975-'76 2nd ex.s. c 12 § 3; ]

== 28B.20.277 - Mathematics, engineering, and science achievement program—Establishment and administration through university.
See RCW 28A.188.082.

[ ]

== 28B.20.298 - Clean energy research, development, manufacturing, and marketing—Findings—Policy.
. The legislature finds that Washington state currently derives many benefits from its renewable energy and energy efficiency sectors. These sectors are an important source of employment and income for a significant number of Washington residents, currently generating close to one billion dollars in annual revenue and employing over three thousand eight hundred people. Equally important, energy efficiency and renewable energy businesses add to the region's quality of life by employing technologies that can reduce some of the harmful effects of the reliance on fossil fuels. Washington state possesses all the necessary elements to do much more to develop these sectors and to become a national leader in the research, development, manufacturing, and marketing of clean energy technologies and services. The state's workforce is highly educated; the state's higher education institutions are supportive of clean energy research and cooperate closely with the private sector in developing and deploying new energy technologies; there are numerous enterprises already located in the state that are engaged in clean energy research and development; and the state's citizens, utilities, and governmental sectors at all levels are committed to diversifying the state's energy sources and increasing energy efficiency.

. It is therefore declared to be the policy of the state that its public agencies and institutions of higher learning maximize their efforts collectively and cooperatively with the private sector to establish the state as a leader in clean energy research, development, manufacturing, and marketing. To this end, all state agencies are directed to employ their existing authorities and responsibilities to:

.. Work with local organizations and energy companies to facilitate the development and implementation of workable renewable energy and energy efficiency projects;

.. Actively promote policies that support energy efficiency and renewable energy development;

.. Encourage utilities and customer groups to invest in new renewables and products and services that promote energy efficiency; and

.. Assist in the development of stronger markets for renewables and products and services that promote energy efficiency.

. For the purposes of this section and *RCW 28B.20.296 and for *RCW 28B.20.285 and 28B.20.287, energy efficiency shall include the application of digital technologies to the generation, delivery, and use of power.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6146-S.SL.pdf?cite=2004%20c%20151%20§%201[2004 c 151 § 1]; ]

== 28B.20.300 - Schools of medicine, dentistry, and related health services—Authorization.
The board of regents of the University of Washington is hereby authorized and directed forthwith to establish, operate and maintain schools of medicine, dentistry, and related health sciences at the university.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.300[1969 ex.s. c 223 § 28B.20.300]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c15.pdf?cite=1945%20c%2015%20§%201[1945 c 15 § 1]; Rem. Supp. 1945 § 4566-5; ]

== 28B.20.305 - Schools of medicine, dentistry, and related health services—Purpose.
The aim and purpose of the schools of medicine, dentistry and related health sciences shall be to provide for students of both sexes, on equal terms, all and every type of instruction in the various branches of medicine, dentistry, and related health sciences and to grant such degrees as are commonly granted by similar institutions.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.305[1969 ex.s. c 223 § 28B.20.305]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c15.pdf?cite=1945%20c%2015%20§%202[1945 c 15 § 2]; Rem. Supp. 1945 § 4566-6; ]

== 28B.20.308 - Global Asia institute.
. A global Asia institute is created within the Henry M. Jackson School of International Studies. The mission of the institute is to promote the understanding of Asia and its interactions with Washington state and the world. The institute shall host visiting scholars and policymakers, sponsor programs and learning initiatives, engage in collaborative research projects, and facilitate broader understanding and cooperation between the state of Washington and Asia through general public programs and targeted collaborations with specific communities in the state.

. Within existing resources, a global Asia institute advisory board is established. The director of the Henry M. Jackson School of International Studies shall appoint members of the advisory board and determine the advisory board's roles and responsibilities. The board shall include members representing academia, business, and government.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20806[2012 c 229 § 806]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5177-S.SL.pdf?cite=2009%20c%20466%20§%202[2009 c 466 § 2]; ]

== 28B.20.315 - Drug testing laboratory—Service—Employees as expert witnesses, traveling expenses and per diem.
The University of Washington is authorized and directed to arrange for a drug testing laboratory. The laboratory shall offer a testing service for law enforcement officers for the identification of known or suspected dangerous and narcotic drugs. Employees of the laboratory are authorized to appear as expert witnesses in criminal trials held within the state: PROVIDED, That the traveling expenses and per diem of such employees shall be borne by the party for the benefit of whom the testimony of such employees is requested.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c266.pdf?cite=1969%20ex.s.%20c%20266%20§%201[1969 ex.s. c 266 § 1]; ]

== 28B.20.320 - Marine biological preserve—Established and described—Unlawful gathering of marine biological materials—Penalty.
. There is hereby created an area of preserve of marine biological materials useful for scientific purposes, except when gathered for human food, and except, also, the plant nereocystis, commonly called "kelp." Such area of preserve shall consist of the salt waters and the beds and shores of the islands constituting San Juan county and of Cypress Island in Skagit county.

. No person shall gather such marine biological materials from the area of preserve, except upon permission first granted by the director of the Friday Harbor Laboratories of the University of Washington.

. A person gathering such marine biological materials contrary to the terms of this section is guilty of a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20174[2003 c 53 § 174]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.320[1969 ex.s. c 223 § 28B.20.320]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c74.pdf?cite=1923%20c%2074%20§%201[1923 c 74 § 1]; RRS § 8436-1; ]

== 28B.20.328 - Lease of lands with outdoor recreation potential—Restrictions—Unlawful to use posted lands.
. Any lease of public lands with outdoor recreation potential authorized by the regents of the University of Washington shall be open and available to the public for compatible recreational use unless the regents of the University of Washington determine that the leased land should be closed in order to prevent damage to crops or other land cover, to improvements on the land, to the lessee, or to the general public or is necessary to avoid undue interference with carrying forward a university program. Any lessee may file an application with the regents of the University of Washington to close the leased land to any public use. The regents shall cause a written notice of the impending closure to be posted in a conspicuous place in the university's business office and in the office of the county auditor in which the land is located thirty days prior to the public hearing. This notice shall state the parcel or parcels involved and shall indicate the time and place of the public hearing. Upon a determination by the regents that posting is not necessary, the lessee shall desist from posting. Upon a determination by the regents that posting is necessary, the lessee shall post his or her leased premises so as to prohibit recreational uses thereon. In the event any such lands are so posted, it shall be unlawful for any person to hunt or fish, or for any person other than the lessee or his or her immediate family to use any such posted lands for recreational purposes.

. The regents of the University of Washington may insert the provisions of subsection (1) of this section in all leases hereafter issued.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20719[2011 c 336 § 719]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c46.pdf?cite=1969%20ex.s.%20c%2046%20§%203[1969 ex.s. c 46 § 3]; ]

== 28B.20.330 - Rights-of-way to railroads and streetcar railways—Conditions.
Any railroad company now having in operation a line of railroad, or branches, sidings, or spurs thereof, upon any property in this state in use by the University of Washington for university purposes, or as a part of the grounds set aside or devoted to university purposes, may have such right-of-way confirmed to it, its successors and assigns, upon the following terms and conditions: Such railroad company shall file with the board of regents of said university a plat showing the right-of-way desired, and shall file a duplicate thereof with the commissioner of public lands; and any railroad company or streetcar company desiring hereafter to construct a railroad or streetcar line, or extensions thereof, with branches, sidings, or spurs, upon any property in this state in use by the University of Washington for university purposes, or as a part of the ground set aside or devoted to university purposes, may have such right-of-way confirmed to it, its successors and assigns, upon the following terms and conditions: Such railroad company or streetcar company shall file with the board of regents of said university a plat showing the right-of-way desired, and shall file a duplicate thereof with the commissioner of public lands.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.330[1969 ex.s. c 223 § 28B.20.330]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c248.pdf?cite=1909%20c%20248%20§%201[1909 c 248 § 1]; RRS § 8095; ]

== 28B.20.332 - Rights-of-way to railroads and streetcar railways—Regents to make agreement.
The board of regents of said University of Washington are authorized, upon the filing of such plat with it, to agree in writing with any such railroad company or streetcar company, upon the boundaries and the extent of such right-of-way, the manner in which the same shall be maintained and fenced and occupied, and prescribe the number, character, and maintenance of crossings, cross-overs, and subways, and as to what sum said railroad company or streetcar company shall pay for the right-of-way granted.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.332[1969 ex.s. c 223 § 28B.20.332]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c248.pdf?cite=1909%20c%20248%20§%202[1909 c 248 § 2]; RRS § 8096; ]

== 28B.20.334 - Rights-of-way to railroads and streetcar railways—Form of deed—Certified copy filed.
If such agreement is entered into, said board of regents shall transmit a certified copy thereof to the commissioner of public lands, who shall, after the full amount of money provided in such agreement shall be paid by said railroad company or streetcar company to the state treasurer, issue to such railroad company or streetcar company, in the name of the state of Washington, a deed for the right-of-way described in such agreement, which said deed shall recite and be subject to all the terms and conditions of such agreement, and certified copies of said deed shall be filed, one in the office of the commissioner of public lands, and the other with the secretary of said board of regents.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.334[1969 ex.s. c 223 § 28B.20.334]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c248.pdf?cite=1909%20c%20248%20§%203[1909 c 248 § 3]; RRS § 8097; ]

== 28B.20.336 - Rights-of-way to railroads and streetcar railways—Deed conveys conditional easement.
The conveyance herein provided for shall not be deemed to convey the fee to the land described, but an easement only thereover and for railroad or streetcar purposes only, and when the right-of-way granted as aforesaid shall not be used for the purposes for which it was granted, then and thereupon the easement right shall immediately become void.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.336[1969 ex.s. c 223 § 28B.20.336]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c248.pdf?cite=1909%20c%20248%20§%204[1909 c 248 § 4]; RRS § 8098; ]

== 28B.20.340 - University site dedicated for street and boulevard purposes—Description.
There is hereby dedicated to the public for street and boulevard purposes the following described lands situated in section 16, township 25 north, range 4 east, W.M., and blocks 7 and 8 of Lake Washington shore lands, to wit: Beginning at the one-quarter (1/4) corner on the north line of said section sixteen (16); thence east along the north line thereof, a distance of three hundred forty-nine and thirty-four one-hundredths (349.34) feet; thence south at right angles to the said north line, a distance of thirty-five feet to the point of beginning of this description; thence south eighty-nine degrees fifty-seven minutes and forty-three seconds (89˚57'43") east a distance of six hundred seventy-three and seventeen one-hundredths (673.17) feet; thence southwesterly along the arc of a curve to the left, having a uniform radius of one thousand (1,000) feet, said curve being tangent to the last above described line, a distance of one thousand three hundred seventy-three and six one-hundredths (1,373.06) feet to a point of tangency; thence south eleven degrees twenty-two minutes and two seconds (11˚22'02") west, a distance of five hundred fifty-six and twenty-two one-hundredths (556.22) feet to a point of tangency on the easterly margin of Montlake Boulevard as laid off and established by Ordinance No. 26332; thence along said easterly margin northerly along the arc of a curve to the left, having a uniform radius of four hundred sixty (460) feet, a distance of one hundred forty-three and forty-one one-hundredths (143.41) feet to a point of a reverse curve; thence northerly along the arc of a curve to the right having a uniform radius of four hundred sixty (460) feet, a distance of one hundred twenty and ninety-four one-hundredths (120.94) feet to a point of reverse curve; thence northerly along the arc of a curve to the left, having a uniform radius of two thousand nine hundred seventy-four and ninety-three one-hundredths (2,974.93) feet, a distance of two hundred eighty-four (284) feet; thence departing from said easterly margin north eleven degrees twenty-two minutes and two seconds (11˚22'02") east, a distance of fourteen and seventy-four one-hundredths (14.74) feet to the beginning of a curve to the right, having a uniform radius of one thousand seventy (1,070) feet; thence northeasterly along the arc of said curve, a distance of seven hundred ninety-six and thirty-three one-hundredths (796.33) feet to a point of reverse curve; thence northeasterly, northerly and northwesterly along the arc of a curve to the left, having a uniform radius of seventy-four and forty-six one-hundredths (74.46) feet, a distance of one hundred eighty-seven and ten one-hundredths (187.10) feet to the point of beginning.

Also the following described lands, to wit: Beginning at a point on the east line of said section, said point being distant nine hundred eighty-nine and sixty one-hundredths (989.60) feet south from the northeast corner of said section; thence south along said east line a distance of four hundred seventy-nine and fifty-three one-hundredths (479.53) feet to a point on the government meander line along the shore of Lake Washington; thence along said meander line south seventy-eight degrees thirteen minutes thirty-three seconds (78˚13'33") west, a distance of sixty-six and fifty one-hundredths (66.50) feet; thence north twenty-nine degrees forty-six minutes twenty-seven seconds (29˚46'27") west, a distance of one hundred sixty-six and ninety-two one-hundredths (166.92) feet; thence departing from said meander line north no degrees fifty-three minutes seven seconds (0˚53'07") east, a distance of three hundred fifty-four and sixty-three one-hundredths (354.63) feet; thence northwesterly along the arc of a curve to the right having a uniform radius of one hundred eighty-five (185) feet, a distance of twenty-two and two one-hundredths (22.02) feet to a point of tangency on a line which bears north twenty-nine degrees six minutes fifty-three seconds (29˚06'53") west; thence northwesterly along said line, a distance of nine hundred eighteen and sixty-five one-hundredths (918.65) feet to the beginning of a curve to the left, having a uniform radius of two hundred fifty (250) feet; thence northwesterly along the arc of said curve, a distance of two hundred sixty-five and fifty one-hundredths (265.50) feet to a point of tangency on the south margin of East Forty-fifth Street; thence east along said south margin, a distance of three hundred twenty-nine and fourteen one-hundredths (329.14) feet to a point which is distant five hundred ten and seventy-nine one-hundredths (510.79) feet west from the east line of said section sixteen (16); thence southwesterly, southerly and southeasterly along the arc of a curve to the left having a uniform radius of sixty (60) feet a distance of one hundred twenty-four and seventy-eight one-hundredths (124.78) feet to a point of tangency; thence south twenty-nine degrees six minutes fifty-three seconds (29˚06'53") east, a distance of nine hundred twenty-four and twenty-four one-hundredths (924.24) feet to the beginning of a curve to the left having a uniform radius of one hundred fifteen (115) feet; thence southeasterly along the arc of said curve, a distance of one hundred twenty and fifty-one one-hundredths (120.51) feet to the point of beginning.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.340[1969 ex.s. c 223 § 28B.20.340]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c24.pdf?cite=1913%20c%2024%20§%201[1913 c 24 § 1]; ]

== 28B.20.342 - University site dedicated for street and boulevard purposes—Local assessments barred against site.
No assessments for the opening, improvement or maintenance of any public street upon the tracts of land described in RCW 28B.20.340 shall ever be levied, assessed or collected upon any portion of section 16, township 25 north, range 4 east, W.M., or upon any portion of blocks 7 and 8 Lake Washington shorelands.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.342[1969 ex.s. c 223 § 28B.20.342]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c24.pdf?cite=1913%20c%2024%20§%202[1913 c 24 § 2]; ]

== 28B.20.344 - University site dedicated for street and boulevard purposes—Eminent domain may not be exercised against site.
The power of eminent domain of any municipal or other corporation whatever is hereby declared not to extend to any portion of said section 16, township 25 north, range 4 east, W.M., and blocks 7 and 8 of Lake Washington shorelands.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.344[1969 ex.s. c 223 § 28B.20.344]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c24.pdf?cite=1913%20c%2024%20§%203[1913 c 24 § 3]; ]

== 28B.20.350 - 1947 conveyance for arboretum and botanical garden purposes—Description.
There is hereby granted to the University of Washington the following described land, to wit:

Lots two (2) and three (3), Block eleven-A (11-A) of the supplemental map of Lake Washington shorelands, filed September 5, 1916 in the office of the commissioner of public lands, to be used for arboretum and botanical garden purposes and for no other purposes, except as provided in RCW 28B.20.354.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.350[1969 ex.s. c 223 § 28B.20.350]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c45.pdf?cite=1947%20c%2045%20§%201[1947 c 45 § 1]; ]

== 28B.20.352 - 1947 conveyance for arboretum and botanical garden purposes—Deed of conveyance.
The commissioner of public lands is hereby authorized and directed to certify the lands described in RCW 28B.20.350 to the governor, and the governor is hereby authorized and directed to execute, and the secretary of state to attest, a deed of said shorelands to the university.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.352[1969 ex.s. c 223 § 28B.20.352]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c45.pdf?cite=1947%20c%2045%20§%202[1947 c 45 § 2]; ]

== 28B.20.354 - 1947 conveyance for arboretum and botanical garden purposes—Part may be conveyed by regents to city of Seattle.
. The board of regents of the University of Washington is hereby authorized to convey to the city of Seattle that portion of said lot three (3) of the shorelands described in RCW 28B.20.350 which is within the following described tract, to wit:

A rectangular tract of land one hundred twenty (120) feet in north-south width, and four hundred (400) feet in east-west length, with the north boundary coincident with the north boundary of the old canal right-of-way, and the west boundary on the southerly extension of the west line of Lot eleven (11), Block four (4), Montlake Park, according to the recorded plat thereof, approximately five hundred sixty (560) feet east of the east line of Montlake Boulevard.

. The board of regents is authorized to convey to the city of Seattle free of all restrictions or limitations, or to incorporate in the conveyance to the city of Seattle such provisions for reverter of said land to the university as the board deems appropriate. Should any portion of the land so conveyed to the city of Seattle again vest in the university by reason of the operation of any provisions incorporated by the board in the conveyance to the city of Seattle, the University of Washington shall hold such reverted portion subject to the reverter provisions of RCW 28B.20.356.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.354[1969 ex.s. c 223 § 28B.20.354]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c45.pdf?cite=1947%20c%2045%20§%203[1947 c 45 § 3]; ]

== 28B.20.356 - 1947 conveyance for arboretum and botanical garden purposes—Reversion for unauthorized use—Reconveyance for highway purposes.
In case the University of Washington should attempt to use or permit the use of such shorelands or any portion thereof for any other purpose than for arboretum and botanical garden purposes, except as provided in RCW 28B.20.354, the same shall forthwith revert to the state of Washington without suit, action or any proceedings whatsoever or the judgment of any court forfeiting the same: PROVIDED, That the board of regents of the University of Washington is hereby authorized and directed to reconvey to the state of Washington block eleven-A (11-A) of the supplemental map of Lake Washington shorelands, filed September 5, 1916 in the office of the commissioner of public lands, or such portion thereof as may be required by the state of Washington or any agency thereof for state highway purposes. The state of Washington or any agency thereof requiring said land shall pay to the University of Washington the fair market value thereof and such moneys paid shall be used solely for arboretum purposes. Such reconveyance shall be made at such time as the state or such agency has agreed to pay the same.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.356[1969 ex.s. c 223 § 28B.20.356]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c164.pdf?cite=1959%20c%20164%20§%202[1959 c 164 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c45.pdf?cite=1947%20c%2045%20§%204[1947 c 45 § 4]; No RRS; ]

== 28B.20.360 - 1939 conveyance of shorelands to university—Description.
The commissioner of public lands of the state of Washington is hereby authorized and directed to certify in the manner now provided by law to the governor for deeding to the University of Washington all of the following described Lake Washington shorelands, to wit: Blocks sixteen (16) and seventeen (17), Lake Washington Shorelands, as shown on the map of said shorelands on file in the office of the commissioner of public lands.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.360[1969 ex.s. c 223 § 28B.20.360]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c60.pdf?cite=1939%20c%2060%20§%201[1939 c 60 § 1]; No RRS; ]

== 28B.20.362 - 1939 conveyance of shorelands to university—Deed of conveyance.
The governor is hereby authorized and directed to execute, and the secretary of state to attest, a deed conveying to the University of Washington all of said shorelands.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.362[1969 ex.s. c 223 § 28B.20.362]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c60.pdf?cite=1939%20c%2060%20§%202[1939 c 60 § 2]; No RRS; ]

== 28B.20.364 - 1939 conveyance of shorelands to university—Grant for arboretum and botanical garden purposes—Reversion for unauthorized use—Reconveyance for highway purposes.
All of the shorelands described in RCW 28B.20.360 are hereby granted to the University of Washington to be used for arboretum and botanical garden purposes and for no other purposes. In case the said University of Washington should attempt to use or permit the use of said shorelands or any portion thereof for any other purpose, the same shall forthwith revert to the state of Washington without suit, action or any proceedings whatsoever or the judgment of any court forfeiting the same: PROVIDED, That the board of regents of the University of Washington is hereby authorized and directed to reconvey to the state of Washington blocks 16 and 17 of Lake Washington shorelands, or such portions thereof as may be required by the state of Washington or any agency thereof for state highway purposes. The state of Washington or any agency thereof requiring said land shall pay to the University of Washington the fair market value thereof and such moneys paid shall be used solely for arboretum purposes. Such reconveyance shall be made at such time as the state or such agency has agreed to pay the same.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.364[1969 ex.s. c 223 § 28B.20.364]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c164.pdf?cite=1959%20c%20164%20§%201[1959 c 164 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c60.pdf?cite=1939%20c%2060%20§%203[1939 c 60 § 3]; No RRS; ]

== 28B.20.370 - Transfer of certain Lake Union shorelands to university.
Block 18-A, Second Supplemental Maps of Lake Union Shore Lands, as shown on the official maps thereof on file in the office of the commissioner of public lands, is hereby transferred to the University of Washington and shall be held and used for university purposes only.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.370[1969 ex.s. c 223 § 28B.20.370]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c71.pdf?cite=1963%20c%2071%20§%201[1963 c 71 § 1]; ]

== 28B.20.381 - "University tract" defined.
For the purposes of this chapter, "university tract" means the tract of land in the city of Seattle, consisting of approximately ten acres, originally known as the "old university grounds," and more recently referred to as the "metropolitan tract," together with all buildings, improvements, facilities, and appurtenances thereon.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1991-S.SL.pdf?cite=1999%20c%20346%20§%202[1999 c 346 § 2]; ]

== 28B.20.382 - University tract—Conditions for sale, lease, or lease renewal—Inspection of records—Deposit of proceeds—University of Washington facilities bond retirement account.
. Until authorized by statute of the legislature, the board of regents of the university, with respect to the university tract, shall not sell the land or any part thereof or any improvement thereon, or lease the land or any part thereof or any improvement thereon or renew or extend any lease thereof for a term of more than eighty years. Any sale of the land or any part thereof or any improvement thereon, or any lease or renewal or extension of any lease of the land or any part thereof or any improvement thereon for a term of more than eighty years made or attempted to be made by the board of regents shall be null and void until the same has been approved or ratified and confirmed by legislative act.

. The board of regents shall have power from time to time to lease the land, or any part thereof or any improvement thereon for a term of not more than eighty years. Any and all records, books, accounts, and agreements of any lessee or sublessee under this section, pertaining to compliance with the terms and conditions of such lease or sublease, shall be open to inspection by the board of regents, the ways and means committee of the senate, the appropriations committee of the house of representatives, and the joint legislative audit and review committee or any successor committees. It is not intended that unrelated records, books, accounts, and agreements of lessees, sublessees, or related companies be open to such inspection. The board of regents shall make a full, detailed report of all leases and transactions pertaining to the land or any part thereof or any improvement thereon to the joint legislative audit and review committee, including one copy to the staff of the committee, during odd-numbered years.

. The net proceeds from the sale or lease of land in the university tract, or any part thereof or any improvement thereon, shall be deposited into the University of Washington facilities bond retirement account hereby established outside the state treasury as a nonappropriated local fund to be used exclusively for the purpose of erecting, altering, maintaining, equipping, or furnishing buildings at the University of Washington. The board of regents shall transfer from the University of Washington facilities bond retirement account to the University of Washington building account under RCW 43.79.080 any funds in excess of amounts reasonably necessary for payment of debt service in combination with other nonappropriated local funds related to capital projects for which debt service is required under section 4, chapter 380, Laws of 1999.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1991-S.SL.pdf?cite=1999%20c%20346%20§%203[1999 c 346 § 3]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%2017[1998 c 245 § 17]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2222-S2.SL.pdf?cite=1996%20c%20288%20§%2027[1996 c 288 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c505.pdf?cite=1987%20c%20505%20§%2013[1987 c 505 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c87.pdf?cite=1980%20c%2087%20§%2010[1980 c 87 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c365.pdf?cite=1977%20ex.s.%20c%20365%20§%201[1977 ex.s. c 365 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c174.pdf?cite=1974%20ex.s.%20c%20174%20§%201[1974 ex.s. c 174 § 1]; ]

== 28B.20.394 - University tract—Powers of regents—Agreements to pay for governmental services.
In addition to the powers conferred upon the board of regents of the University of Washington by RCW 28B.20.395, the board of regents is authorized and shall have the power to enter into an agreement or agreements with the city of Seattle and the county of King, Washington, to pay to the city and the county such sums as shall be mutually agreed upon for governmental services rendered to the university tract, which sums shall not exceed the amounts that would be received pursuant to limitations imposed by RCW 84.52.043 by the city of Seattle and county of King respectively from real and personal property taxes paid on the university tract or any leaseholds thereon if such taxes could lawfully be levied.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1991-S.SL.pdf?cite=1999%20c%20346%20§%204[1999 c 346 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c195.pdf?cite=1973%201st%20ex.s.%20c%20195%20§%2010[1973 1st ex.s. c 195 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c107.pdf?cite=1972%20ex.s.%20c%20107%20§%201[1972 ex.s. c 107 § 1]; 1969 ex.s. c 223 § 28B.20.394. See also  1973 1st ex.s. c 195 § 140; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c229.pdf?cite=1955%20c%20229%20§%201[1955 c 229 § 1]; ]

== 28B.20.395 - University tract—Powers of regents, generally.
In addition to the powers conferred under the original deeds of conveyance to the state of Washington and under existing law, and subject to RCW 28B.20.382, the board of regents has full control of the university tract as provided in this chapter including, but not limited to:

. With regard to the whole or portions of the land, the authority to manage, to improve, to alter, to operate, to lease, to contract indebtedness, to borrow funds, to issue bonds, notes, and warrants, to provide for the amortization of and to pay the bonds, notes, warrants, and other evidences of indebtedness, at or prior to maturity, to use and pledge the income derived from operating, managing, and leasing the university tract for such purpose, and to otherwise own, operate, and control the university tract to the same extent as any other property of the university;

. With regard to the whole or portions of any building or buildings or other improvements thereon or appurtenances thereto, the authority to sell, subject to the terms of any underlying lease on the land, to manage, to improve, to alter, to operate, to lease, to grant a deed of trust or a mortgage lien, to contract indebtedness, to borrow funds, to issue bonds, notes, and warrants, to provide for the amortization thereof and to pay the bonds, notes, warrants, and other evidences of indebtedness, at or prior to maturity, to use and pledge the income derived from operating, managing, and leasing the university tract for such purpose, and to otherwise own, operate, and control the university tract to the same extent as any other property of the university consistent with the purpose of the donors of the metropolitan tract.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1991-S.SL.pdf?cite=1999%20c%20346%20§%205[1999 c 346 § 5]; ]

== 28B.20.396 - University tract—Bonding authority.
Bonds issued pursuant to the authority granted under RCW 28B.20.395:

. Shall not constitute (a) an obligation, either general or special, of the state or (b) a general obligation of the University of Washington or of the board of regents;

. Shall be:

.. Either in bearer form or in registered form as provided in RCW 39.46.030, and

.. Issued in denominations of not less than one hundred dollars;

. Shall state:

.. The date of issue, and

.. The series of the issue and be consecutively numbered within the series, and

.. That the bond is payable only out of a special fund established for the purpose, and designate the fund;

. Shall bear interest, payable either annually, or semiannually as the board of regents may determine;

. Shall be payable solely out of:

.. Revenue derived from operating, managing and leasing the university tract, and

.. A special fund, created by the board of regents for the purpose, consisting either of (i) a fixed proportion, or (ii) a fixed amount out of and not exceeding a fixed proportion, or (iii) a fixed amount without regard to any fixed proportion, of the revenue so derived;

. May contain covenants by the board of regents in conformity with the provisions of RCW 28B.20.398(2);

. Shall be payable at such times over a period of not to exceed thirty years, in such manner and at such place or places as the board of regents determines;

. Shall be executed in such manner as the board of regents by resolution determines;

. Shall be sold in such manner as the board of regents deems for the best interest of the University of Washington;

. May be issued under chapter 39.46 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1991-S.SL.pdf?cite=1999%20c%20346%20§%206[1999 c 346 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c167.pdf?cite=1983%20c%20167%20§%2033[1983 c 167 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c56.pdf?cite=1970%20ex.s.%20c%2056%20§%2025[1970 ex.s. c 56 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c232.pdf?cite=1969%20ex.s.%20c%20232%20§%2099[1969 ex.s. c 232 § 99]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.396[1969 ex.s. c 223 § 28B.20.396]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c284.pdf?cite=1947%20c%20284%20§%203[1947 c 284 § 3]; Rem. Supp. 1947 § 4566-13; ]

== 28B.20.398 - University tract—Powers of regents—Bond issuance—Covenants—Redemption—Action for compliance.
. Any resolution of the board of regents pursuant to the provisions of RCW 28B.20.395 shall provide for the creation of a special fund, in conformity with the provisions of RCW 28B.20.396(5)(b).

. Any resolution authorizing the issuance of bonds pursuant to the provisions of RCW 28B.20.395, 28B.20.396, and 28B.20.398 may contain covenants of the board of regents to protect and safeguard the security and rights of the owners of any such bonds such as are then customary in connection with similar bonds and considered advisable in order to assure the maximum marketability for said bonds. Without limiting the generality of the foregoing, any such resolution may contain covenants as to:

.. The creation of a special fund into which the proceeds of all bonds issued pursuant to the provisions of such resolution shall be deposited, the terms and conditions upon which payments may be made from such special fund, and for the payment of interest on bonds issued pursuant to such resolution from the moneys in said fund;

.. Maintaining rental and leasehold rates and other charges at a level sufficient at all times to provide revenue (i) to pay the interest on and principal of all bonds and other obligations payable from said revenue, (ii) to make all other payments from said revenues required under the provisions of any resolution adopted in connection with the issuance of warrants or bonds under RCW 28B.20.395, 28B.20.396, and 28B.20.398 and (iii) to pay the operating, management, maintenance, repair and upkeep costs of the university tract;

.. Collection, deposit, custody and disbursement of the revenues from the university tract or any portions thereof including (i) a specification of the depositaries to be designated, and (ii) authorization of such depositaries, or other banks or trust companies, to act as fiscal agent of the board of regents for the custody of the proceeds of bonds and the moneys held in any funds created pursuant to RCW 28B.20.395, 28B.20.396, and 28B.20.398, or any resolution authorizing such bonds, and to represent bond owners in the event of a default on such bonds or in the event of a default in the performance of any duty or obligation of the board of regents in connection therewith, with such power and duty as such resolution may provide;

.. Creation and administration of reserve and other funds for the payment, at or prior to maturity, of any indebtedness chargeable against the revenues from the university tract and for creation of working funds, depreciation funds, replacement funds, reserves for extraordinary repairs and any other fund deemed necessary or desirable to insure the continued profitable operation of the said university tract;

.. Deposit of collateral security or indemnity bonds to secure the proceeds (i) of bonds issued pursuant to the provisions of such resolution and (ii) of all revenues which are pledged to secure the repayment of bonds issued pursuant to the provisions of such resolution and (iii) of all moneys deposited in any special fund created under the authority of RCW 28B.20.395, 28B.20.396, and 28B.20.398 or any covenant thereunder;

.. The obligation of the board of regents to maintain the building or buildings in good condition and to operate and manage the same in an economical and efficient manner;

.. The amount and kind of insurance to be carried by the board of regents in connection with the building or buildings, the companies in which such insurance shall be carried, the term thereof, the application of the proceeds of any such insurance, and adjustments of losses under any such policy of insurance;

.. Limitations upon the amount of additional bonds, warrants and other obligations payable out of the revenues from the building or buildings which may be thereafter issued and the terms and conditions upon which such additional bonds, warrants or other obligations may be issued;

.. Limitations upon the creation of additional liens or encumbrances on the building or buildings or the personal property used in connection therewith;

.. The terms and conditions upon which the building or buildings, or any part thereof, may be sold, mortgaged, leased or otherwise disposed of, and the use or other disposition of the proceeds of any such sale, mortgage or lease;

.. The methods of operation, management and maintenance of the building or buildings;

.. Accounting and auditing and the keeping of records, reports and audits with respect to the building or buildings;

.. The amendment or modification of any resolution authorizing the issuance of bonds pursuant to the provisions of RCW 28B.20.395, 28B.20.396, and 28B.20.398, including the terms and conditions upon which such amendment or modification may be effected and the number, amount or percentage of assenting bonds necessary to effectuate the same;

.. Limitations upon the use of space or facilities in the building or buildings without payment therefor; and

.. Such other matters as may be necessary or desirable to insure a successful and profitable operation of the building or buildings.

. The term "building or buildings" as used in subsection (2) of this section means the building or buildings or improvements upon the university tract with respect to which the revenues are pledged, under the terms of the resolution, to secure the payment of bonds issued under such resolution.

. The provisions of RCW 28B.20.395, 28B.20.396, and 28B.20.398 and of any resolution adopted in conformity with the provisions of this section shall constitute a contract with the owners of warrants or bonds issued pursuant thereto, and the provisions thereof shall be enforceable in any court of competent jurisdiction by any owner of such warrants or bonds by mandamus or any other appropriate suit, action or proceeding at law or in equity.

. Bonds issued pursuant to the provisions of RCW 28B.20.395, 28B.20.396, and 28B.20.398 may be redeemed, at the option of the board of regents, at such time or times, upon such terms and conditions, and at such premiums as the board of regents specifies in the resolution.

. If the board of regents fails to pay the required amounts into the special fund, established in conformity with subsection (2) of this section, the owner of any bond or bonds affected thereby may maintain an action against the board of regents to compel compliance with the terms of the resolution in this respect.

. Pending the preparation and execution of any bonds the issuance of which is authorized under the provisions of subsection (2) of this section, temporary bonds may be issued in such form as the board of regents determines.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1991-S.SL.pdf?cite=1999%20c%20346%20§%207[1999 c 346 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c167.pdf?cite=1983%20c%20167%20§%2034[1983 c 167 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.398[1969 ex.s. c 223 § 28B.20.398]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c284.pdf?cite=1947%20c%20284%20§%204[1947 c 284 § 4]; Rem. Supp. 1947 § 4566-14; ]

== 28B.20.410 - Center for research and training in intellectual and developmental disabilities—Established.
There is hereby established at the University of Washington a center for research and training in intellectual and developmental disabilities.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2490.SL.pdf?cite=2010%20c%2094%20§%208[2010 c 94 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.410[1969 ex.s. c 223 § 28B.20.410]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c193.pdf?cite=1963%20c%20193%20§%201[1963 c 193 § 1]; ]

== 28B.20.412 - Center for research and training in intellectual and developmental disabilities—Administration.
The center shall be administered by the board of regents of the University of Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c163.pdf?cite=1982%20c%20163%20§%204[1982 c 163 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c62.pdf?cite=1973%20c%2062%20§%208[1973 c 62 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.412[1969 ex.s. c 223 § 28B.20.412]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c193.pdf?cite=1963%20c%20193%20§%202[1963 c 193 § 2]; ]

== 28B.20.414 - Center for research and training in intellectual and developmental disabilities—Purpose.
The general purposes of the center shall be:

. To provide clinical and laboratory facilities for research on the causes, diagnosis, prevention, and treatment of intellectual and developmental disabilities;

. To develop improved professional and in-service training programs in the various disciplines concerned with persons with disabilities;

. To provide diagnostic and consultative services to various state programs and to regional and local centers, to an extent compatible with the primary research and teaching objectives of the center.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2490.SL.pdf?cite=2010%20c%2094%20§%209[2010 c 94 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.414[1969 ex.s. c 223 § 28B.20.414]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c193.pdf?cite=1963%20c%20193%20§%203[1963 c 193 § 3]; ]

== 28B.20.420 - Graduate scholarships for engineering research—Established.
In order to further the development of advance studies in engineering there shall be established in the engineering laboratories of the University of Washington, ten graduate scholarships and/or fellowships to the amount of one thousand dollars and tuition each, per academic year. These scholarships shall be in the field of engineering which can best be used to aid the industrial development of the state of Washington and its resources. This graduate work shall be done in the laboratories of the university and shall be directed along the lines of professional research and testing.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.420[1969 ex.s. c 223 § 28B.20.420]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c241.pdf?cite=1945%20c%20241%20§%201[1945 c 241 § 1]; ]

== 28B.20.422 - Graduate scholarships for engineering research—Studies published—Direction of program—Qualifications for candidates.
The studies and results of such scholarships shall be published as bulletins or engineering reports of the college of engineering of the university and a reasonable number of copies thereof shall be available to the public without cost. The provisions of RCW 28B.20.420 and this section shall include the cost of individual scholarships, the cost of necessary supplies and materials to be utilized, and the cost of printing and distribution of the bulletins or engineering reports. The direction of this research program shall rest in the proper department or departments and schools of the engineering college of the university and the candidates must meet the qualifications of the graduate school of the university for graduate students.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.422[1969 ex.s. c 223 § 28B.20.422]; 1945 c 241 § 2. Formerly RCW  28.77.225; 28.77.220, part; ]

== 28B.20.440 - University hospital.
The board of regents of the University of Washington is hereby authorized to operate a hospital upon university grounds to be used in conjunction with the university's medical and dental schools, including equipping and additional construction to the same.

[ 1969 ex.s. c 223 § 28B.20.440. Cf.   1947 c 286 § 2. No RRS.   1945 c 15 § 4. No RRS; ]

== 28B.20.445 - Child and adolescent psychiatry residency program—Requirement to offer additional residency position. (Effective until July 1, 2022.)
Subject to the availability of amounts appropriated for this specific purpose, the child and adolescent psychiatry residency program at the University of Washington shall offer one additional twenty-four month residency position that is approved by the accreditation council for graduate medical education to one resident specializing in child and adolescent psychiatry. The residency must include a minimum of twelve months of training in settings where children's mental health services are provided under the supervision of experienced psychiatric consultants and must be located west of the crest of the Cascade mountains.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2779-S2.SL.pdf?cite=2018%20c%20175%20§%2011[2018 c 175 § 11]; ]

== 28B.20.450 - Occupational and environmental research facility—Construction and maintenance authorized—Purpose.
There shall be constructed and maintained at the University of Washington an occupational and environmental research facility in the school of medicine having as its objects and purposes testing, research, training, teaching, consulting and service in the fields of industrial and occupational medicine and health, the prevention of industrial and occupational disease among workers, the promotion and protection of safer working environments and dissemination of the knowledge and information acquired from such objects and purposes.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c12.pdf?cite=1989%20c%2012%20§%204[1989 c 12 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.450[1969 ex.s. c 223 § 28B.20.450]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c151.pdf?cite=1963%20c%20151%20§%201[1963 c 151 § 1]; ]

== 28B.20.452 - Occupational and environmental research facility—Industry to share costs.
See RCW 51.16.042.

[ ]

== 28B.20.454 - Occupational and environmental research facility—Submission of industrial and occupational health problems to facility—Availability of information.
Any matter or problem relating to the industrial and occupational health of workers may be submitted to the environmental research facility by any public agency or interested party. All research data and pertinent information available or compiled at such facility related to the industrial and occupational health of workers shall be made available and supplied without cost to any public agency or interested party.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c12.pdf?cite=1989%20c%2012%20§%205[1989 c 12 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.454[1969 ex.s. c 223 § 28B.20.454]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c151.pdf?cite=1963%20c%20151%20§%203[1963 c 151 § 3]; ]

== 28B.20.456 - Occupational and environmental research facility—Advisory committee.
There is hereby created an advisory committee to the environmental research facility consisting of eight members. Membership on the committee shall consist of the director of the department of labor and industries, the assistant secretary for the division of health services of the department of social and health services, the president of the Washington state labor council, the president of the association of Washington business, the dean of the school of public health and community medicine of the University of Washington, the dean of the school of engineering of the University of Washington, the president of the Washington state medical association, or their representatives, and the chair of the department of environmental health of the University of Washington, who shall be ex officio chair of the committee without vote. Such committee shall meet at least semiannually at the call of the chair. Members shall serve without compensation. It shall consult, review and evaluate policies, budgets, activities, and programs of the facility relating to industrial and occupational health to the end that the facility will serve in the broadest sense the health of the worker as it may be related to his or her employment.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20720[2011 c 336 § 720]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c62.pdf?cite=1973%20c%2062%20§%209[1973 c 62 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.456[1969 ex.s. c 223 § 28B.20.456]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c151.pdf?cite=1963%20c%20151%20§%204[1963 c 151 § 4]; ]

== 28B.20.458 - Occupational and environmental research facility—Acceptance of loans, gifts, etc.—Presentment of vouchers for payments from accident and medical aid funds.
The University of Washington may accept and administer loans, grants, funds, or gifts, conditional or otherwise, in furtherance of the objects and purposes of RCW 28B.20.450 through 28B.20.458, from the federal government and from other sources public or private. For the purpose of securing payment from the accident fund and medical aid fund as funds are required, vouchers shall be presented to the department of labor and industries.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.458[1969 ex.s. c 223 § 28B.20.458]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c151.pdf?cite=1963%20c%20151%20§%205[1963 c 151 § 5]; ]

== 28B.20.462 - Warren G. Magnuson institute for biomedical research and health professions training—Established.
The Warren G. Magnuson institute for biomedical research and health professions training is established within the Warren G. Magnuson health sciences center at the University of Washington. The institute shall be administered by the university. The institute may be funded through a combination of federal, state, and private funds, including earnings on the endowment fund in RCW 28B.20.472.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c282.pdf?cite=1990%20c%20282%20§%201[1990 c 282 § 1]; ]

== 28B.20.464 - Warren G. Magnuson institute—Purposes.
The purposes of the Warren G. Magnuson institute for biomedical research and health professions training are as follows:

. Supporting one or more individuals engaged in biomedical research into the causes of, the treatments for, or the management of diabetes is the primary purpose of the institute;

. Providing financial assistance to students in graduate or postgraduate training programs in the health professions at the university is the secondary purpose of the institute;

. Supporting biomedical research into the causes of, the treatment for, or the management of Parkinson's disease, osteoporosis, or any other disease or medical disorder where the achievement of a significant result in the near term is especially promising; and

. Enhancing the training, research, and public service missions of the health sciences schools of the University of Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c282.pdf?cite=1990%20c%20282%20§%202[1990 c 282 § 2]; ]

== 28B.20.466 - Warren G. Magnuson institute—Endowment fund earnings.
Unless designated otherwise by donors, the earnings on the endowment fund in RCW 28B.20.472 shall be distributed as follows:

. Earnings on the first seven hundred fifty thousand dollars shall be expended at the direction of the dean of the school of medicine, in support of one or more individuals engaged in biomedical research into the causes of, the treatments for, or the management of diabetes;

. Earnings on the next two hundred fifty thousand dollars shall be expended to provide financial assistance to students in graduate or postgraduate training programs in the health professions at the university, including: Medicine, nursing, public health and community medicine, dentistry, pharmacy, and social work. At least one such student at all times shall be in a career pathway preparing for or engaged in research related to diabetes, its antecedents, or complications; and

. Earnings on additional funds within the endowment may be used for any purpose of the institute as outlined in RCW 28B.20.464.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c282.pdf?cite=1990%20c%20282%20§%203[1990 c 282 § 3]; ]

== 28B.20.472 - Warren G. Magnuson institute—Local endowment fund.
The state matching funds and the private donations shall be deposited in the university's local endowment fund. The university is responsible for investing and maintaining all moneys within the fund. The principal of the invested endowment fund shall not be invaded. The university may augment the endowment fund with additional private donations. The earnings of the fund shall be used solely to support the purposes of the Warren G. Magnuson institute for biomedical research and health professions training as set forth in RCW 28B.20.464.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c282.pdf?cite=1990%20c%20282%20§%206[1990 c 282 § 6]; ]

== 28B.20.475 - Sea grant program—Geoduck aquaculture—Scientific research studies—Reports.
. The sea grant program at the University of Washington shall, consistent with this section, commission a series of scientific research studies that examines the possible effects, including the cumulative effects, of the current prevalent geoduck aquaculture techniques and practices on the natural environment in and around Puget Sound, including the Strait of Juan de Fuca. The sea grant program shall use funding provided from the geoduck aquaculture research account created in RCW 28B.20.476 to review existing literature, directly perform research identified as needed, or to enter into and manage contracts with scientific organizations or institutions to accomplish these results.

. Prior to entering into a contract with a scientific organization or institution, the sea grant program must:

.. Analyze, through peer review, the credibility of the proposed party to the contract, including whether the party has credible experience and knowledge and has access to the facilities necessary to fully execute the research required by the contract; and

.. Require that all proposed parties to a contract fully disclose any past, present, or planned future personal or professional connections with the shellfish industry or public interest groups.

. All research commissioned under this section must be subjected to a rigorous peer review process prior to being accepted and reported by the sea grant program.

. In prioritizing and directing research under this section, the sea grant program shall meet with the department of ecology at least annually and rely on guidance submitted by the department of ecology. The department of ecology shall convene the shellfish aquaculture regulatory committee created in section 4, chapter 216, Laws of 2007 as necessary to serve as an oversight committee to formulate the guidance provided to the sea grant program. The objective of the oversight committee, and the resulting guidance provided to the sea grant program, is to ensure that the research required under this section satisfies the planning, permitting, and data management needs of the state, to assist in the prioritization of research given limited funding, and to help identify any research that is beneficial to complete other than what is listed in subsection (5) of this section.

. To satisfy the minimum requirements of subsection (1) of this section, the sea grant program shall review all scientific research that is existing or in progress that examines the possible effect of currently prevalent geoduck practices, on the natural environment, and prioritize and conduct new studies as needed, to measure and assess the following:

.. The environmental effects of structures commonly used in the aquaculture industry to protect juvenile geoducks from predation;

.. The environmental effects of commercial harvesting of geoducks from intertidal geoduck beds, focusing on current prevalent harvesting techniques, including a review of the recovery rates for benthic communities after harvest;

.. The extent to which geoducks in standard aquaculture tracts alter the ecological characteristics of overlying waters while the tracts are submerged, including impacts on species diversity, and the abundance of other benthic organisms;

.. Baseline information regarding naturally existing parasites and diseases in wild and cultured geoducks, including whether and to what extent commercial intertidal geoduck aquaculture practices impact the baseline;

.. Genetic interactions between cultured and wild geoduck, including measurements of differences between cultured geoducks and wild geoducks in terms of genetics and reproductive status; and

.. The impact of the use of sterile triploid geoducks and whether triploid animals diminish the genetic interactions between wild and cultured geoducks.

. If adequate funding is not made available for the completion of all research required under this section, the sea grant program shall consult with the shellfish aquaculture regulatory committee, via the department of ecology, to prioritize which of the enumerated research projects have the greatest cost/benefit ratio in terms of providing information important for regulatory decisions; however, the study identified in subsection (5)(b) of this section shall receive top priority. The prioritization process may include the addition of any new studies that may be appropriate in addition to, or in place of, studies listed in this section.

. When appropriate, all research commissioned under this section must address localized and cumulative effects of geoduck aquaculture.

. The sea grant program and the University of Washington are prohibited from retaining greater than fifteen percent of any funding provided to implement this section for administrative overhead or other deductions not directly associated with conducting the research required by this section.

. Individual commissioned contracts under this section may address single or multiple components listed for study under this section.

. All research commissioned under this section must be completed and the results reported to the appropriate committees of the legislature by December 1, 2013. In addition, the sea grant program shall provide the appropriate committees of the legislature with annual reports updating the status and progress of the ongoing studies that are completed in advance of the 2013 deadline.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2220-S2.SL.pdf?cite=2007%20c%20216%20§%201[2007 c 216 § 1]; ]

== 28B.20.476 - Sea grant program—Geoduck aquaculture research account.
The geoduck aquaculture research account is created in the custody of the state treasurer. All receipts from any legislative appropriations, the aquaculture industry, or any other private or public source directed to the account must be deposited in the account. Expenditures from the account may only be used by the sea grant program for the geoduck research projects identified by RCW 28B.20.475. Only the president of the University of Washington or the president's designee may authorize expenditures from the account. The account is subject to the allotment procedures under chapter 43.88 RCW, but an appropriation is not required for expenditures. During the 2017-2019, 2019-2021, and 2021-2023 fiscal biennia, amounts available in the geoduck aquaculture research account may also be appropriated for the sea grant program at the University of Washington to conduct research examining the possible negative and positive effects of evolving shellfish aquaculture techniques and practices on Washington's economy and marine ecosystems. It is the intent of the legislature that this policy be continued in future biennia.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5092-S.SL.pdf?cite=2021%20c%20334%20§%20961[2021 c 334 § 961]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1109-S.SL.pdf?cite=2019%20c%20415%20§%20953[2019 c 415 § 953]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6032-S.SL.pdf?cite=2018%20c%20299%20§%20905[2018 c 299 § 905]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5034-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%204%20§%20960[2013 2nd sp.s. c 4 § 960]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2220-S2.SL.pdf?cite=2007%20c%20216%20§%202[2007 c 216 § 2]; ]

== 28B.20.478 - Center for human rights.
A University of Washington center for human rights is created. The mission of the center is to expand opportunities for Washington residents to receive a world-class education in human rights, generate research data and expert knowledge to enhance public and private policymaking, and become an academic center for human rights teaching and research in the nation. The center shall align with the founding principles and philosophies of the United States of America and engage faculty, staff, and students in service to enhance the promise of life and liberty as outlined in the Preamble of the United States Constitution. Key substantive issues for the center include: The rights of all persons to security against violence; the rights of immigrants, native Americans, and ethnic or religious minorities; human rights and the environment; health as a human right; human rights and trade; the human rights of working people; and women's rights as human rights. State funds may not be used to support the center for human rights created in this section.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20807[2012 c 229 § 807]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5172-S.SL.pdf?cite=2009%20c%20465%20§%201[2009 c 465 § 1]; ]

== 28B.20.4781 - Center for human rights—Reports.
The University of Washington center for human rights shall report to the appropriate committees of the legislature by December 1, 2010, and biennially thereafter regarding the center's activities. The report shall include, but not be limited to, descriptions of the center's activities and accomplishments especially as they relate to: International human rights issues and community service; documentation of measurable accomplishments in improving outcomes in the issue areas outlined in RCW 28B.20.478; and documentation of engagement with agencies and nongovernmental organizations outside of the University of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5172-S.SL.pdf?cite=2009%20c%20465%20§%202[2009 c 465 § 2]; ]

== 28B.20.500 - Medical students from rural areas—Admission preference.
The school of medicine at the University of Washington shall develop and implement a policy to grant admission preference to prospective medical students from rural areas of the state who agree to serve for at least five years as primary care physicians in rural areas of Washington after completion of their medical education and have applied for and meet the qualifications of the program under chapter 28B.115 RCW. Should the school of medicine be unable to fill any or all of the admission openings due to a lack of applicants from rural areas who meet minimum qualifications for study at the medical school, it may admit students not eligible for preferential admission under this section.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1960-S.SL.pdf?cite=1991%20c%20332%20§%2026[1991 c 332 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c271.pdf?cite=1990%20c%20271%20§%209[1990 c 271 § 9]; ]

== 28B.20.502 - Medical marijuana research.
. The University of Washington and Washington State University may conduct scientific research on the efficacy and safety of administering marijuana as part of medical treatment. As part of this research, the University of Washington and Washington State University may develop and conduct studies to ascertain the general medical safety and efficacy of marijuana, and may develop medical guidelines for the appropriate administration and use of marijuana.

. The University of Washington and Washington State University may, in accordance with RCW 69.50.372, contract with marijuana research licensees to conduct research permitted under this section and RCW 69.50.372.

. The University of Washington and Washington State University may contract to conduct marijuana research with an entity licensed to conduct such research by a federally recognized Indian tribe located within the geographical boundaries of the state of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2136-S2.SL.pdf?cite=2015%202nd%20sp.s.%20c%204%20§%201502[2015 2nd sp.s. c 4 § 1502]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5121.SL.pdf?cite=2015%20c%2071%20§%202[2015 c 71 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5073-S2.SL.pdf?cite=2011%20c%20181%20§%201002[2011 c 181 § 1002]; ]

== 28B.20.510 - Behavioral health and suicide prevention—Statewide resource.
. Subject to availability of amounts appropriated for this specific purpose, an entity within the University of Washington school of social work that has expertise in suicide prevention, in collaboration with the student achievement council, shall develop a statewide resource for behavioral health and suicide prevention for the state's postsecondary institutions.

. To establish the components of the statewide resource, the entity shall convene and consult with a work group that consists of representatives from stakeholder groups the entity deems appropriate. The entity must consider representatives from those organizations listed in the mental health and suicide prevention in higher education task force, created by chapter 67, Laws of 2015. At a minimum, the stakeholders in the work group must include:

.. Representation from a tribal college;

.. Representation from a veterans training support center;

.. Representation from students and families;

.. Representatives selected by the educational opportunity gap oversight and accountability committee;

.. Representation from a community behavioral health provider;

.. A suicide prevention expert;

.. Representation from the department of health; and

.. Three institutional counseling center directors or executive directors to include one from each of the following: A public four-year college or university, a private, nonprofit institution, and a community and technical college.

. The entity must be responsible for constructing and hosting the statewide resource and linking the resource to the student achievement council's and the department of health's websites.

. At a minimum, the statewide resource must:

.. Be made publicly available through a web-based portal or a support line;

.. Provide a free curriculum to train faculty, staff, and students in suicide recognition and referral skills and in the specific needs of student veterans;

.. Provide a resource to build capacity within the institutions to train individuals to deliver training in person;

.. Contain model crisis protocols, per sector, that include behavioral health and suicide identification, intervention, reentry, and postvention;

.. Contain model marketing materials and messages that promote student behavioral health on college campuses;

.. Develop capacity for an annual conference for postsecondary institutions seeking to address students' behavioral health and suicide prevention needs. The entity must be responsible for hosting the first conference for postsecondary institutions; and

.. Include resources that will serve diverse communities and underrepresented populations, including resources that are culturally relevant.

. The statewide resource must be made available to postsecondary institutions by June 30, 2020.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6514-S.SL.pdf?cite=2018%20c%20293%20§%202[2018 c 293 § 2]; ]

== 28B.20.515 - Behavioral health and suicide prevention—Annual report. (Expires December 31, 2022.)
. Beginning June 1, 2019, and every June 1st thereafter until 2022, postsecondary institutions shall submit a report to the entity within the University of Washington school of social work specified under RCW 28B.20.510 for the purposes of establishing a baseline for behavioral health concerns and responses at the institutions of higher education.

. The annual report must include the following information as reported to the postsecondary institution, in compliance with the entity's established data collection requirements, and if an institution does not collect or have access to the information it must indicate this in the report:

.. The awareness of students, faculty, and staff regarding behavioral health and suicide prevention resources;

.. The institution's counselor-to-student ratio;

.. The number of students referred to off-campus behavioral health providers;

.. The number of students identifying emotional distress as reasons for withdrawal;

.. The number of student suicide deaths;

.. The number of student suicide attempts that result in hospitalization;

.. Information about dissemination of material to students about behavioral health resources that are available on and off campus;

.. Confirmation of campus plans for suicide recognition and referral training that identifies groups receiving the required training and which groups are recommended to receive training in the future;

.. The entity or entities on campus responsible for the development and maintenance of the campus crisis plan that integrate policies for suicide identification, intervention, reentry, and postvention;

.. The campus point person or persons responsible for the crisis plan; and

.. Information about behavioral health services and supports available to veterans on campus.

. For purposes of this section, "postsecondary institutions" has the same meaning as that term is defined in RCW 28B.77.120.

. This section expires December 31, 2022.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6514-S.SL.pdf?cite=2018%20c%20293%20§%204[2018 c 293 § 4]; ]

== 28B.20.520 - Behavioral health and suicide prevention—Data.
. By December 31, 2018, for the purposes of collecting data on suicide prevention and behavioral health in higher education, the entity within the University of Washington school of social work specified under RCW 28B.20.510 shall identify data, methods for data collection, and data definitions to be used by postsecondary institutions required to submit annual reports under RCW 28B.20.515. The entity shall collaborate with the postsecondary institutions, as defined in RCW 28B.77.120, in establishing data collection requirements and criteria.

. The entity shall aggregate the information it receives by sector and, by December 1st of each year, the entity must submit an aggregated summary report to the relevant committees of the legislature. The entity shall serve as the depository for annual reports submitted by institutions of higher education under RCW 28B.20.515.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6514-S.SL.pdf?cite=2018%20c%20293%20§%205[2018 c 293 § 5]; ]

== 28B.20.522 - Suicide prevention training modules—Construction industry.
. Subject to funds appropriated for this specific purpose, the University of Washington's forefront suicide prevention center of excellence, in coordination with associations representing the construction industry, shall develop:

.. An online, interactive training module in suicide prevention; and

.. A series of modules intended to be delivered by the construction industry that complement the online training module, which must include training on available resources, lethal means safety, screening tools, men's mental health, and a refresher on the online training.

. The University of Washington's forefront suicide prevention center of excellence shall complete the modules developed under subsection (1) of this section by July 1, 2021.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2411-S.SL.pdf?cite=2020%20c%20229%20§%203[2020 c 229 § 3]; ]

== 28B.20.530 - Behavioral health innovation and integration campus.
. A behavioral health innovation and integration campus is created within the University of Washington school of medicine. The campus must include inpatient treatment capacity and focus on inpatient and outpatient care for individuals with behavioral health needs while training a behavioral health provider workforce. The training must include an interdisciplinary curriculum and programs that support and encourage professionals to work in teams. The training must use current best practices, including best practices in suicide prevention, must encourage innovation of future best practices in order to provide behavioral health care across the entire spectrum of health care providers, and must be culturally appropriate, including training specifically appropriate for providing care to federally recognized tribes and tribal members.

. The siting and design for the new campus should take into account local community needs and resources, with attention to diversity and cultural competence, a focus on training and supporting the next generation of health care providers, and close coordination with existing local and regional programs, clinics, and resources.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1593-S2.SL.pdf?cite=2019%20c%20323%20§%202[2019 c 323 § 2]; ]

== 28B.20.535 - Behavioral health innovation and integration campus—Teaching facility.
For purposes of siting and other land use planning and approval process, work should be done within the existing major institution master plan including the existing community advisory committee addressing land use and building permit approval for the behavioral health teaching facility under RCW 28B.20.530 and section 3, chapter 323, Laws of 2019.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1593-S2.SL.pdf?cite=2019%20c%20323%20§%204[2019 c 323 § 4]; ]

== 28B.20.700 - Construction, remodeling, improvement, financing, etc., authorized.
The board of regents of the University of Washington is empowered, in accordance with the provisions of this chapter, to provide for the construction, completion, reconstruction, remodeling, rehabilitation and improvement of buildings and facilities authorized by the legislature for the use of the university and to finance the payment thereof by bonds payable out of a special fund from revenues hereafter derived from the payment of building fees, gifts, bequests or grants, and such additional funds as the legislature may provide.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c390.pdf?cite=1985%20c%20390%20§%2036[1985 c 390 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.700[1969 ex.s. c 223 § 28B.20.700]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c193.pdf?cite=1959%20c%20193%20§%201[1959 c 193 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c254.pdf?cite=1957%20c%20254%20§%201[1957 c 254 § 1]; ]

== 28B.20.705 - Definitions.
The following terms, whenever used or referred to in this chapter, shall have the following meaning, excepting in those instances where the context clearly indicates otherwise:

. The word "board" means the board of regents of the University of Washington.

. The words "building fees" mean the building fees charged students registering at the university.

. The words "bond retirement fund" mean the special fund created by chapter 254, Laws of 1957, to be known as the University of Washington bond retirement fund.

. The word "bonds" means the bonds payable out of the bond retirement fund.

. The word "projects" means the construction, completion, reconstruction, remodeling, rehabilitation, or improvement of any building or other facility of the university authorized by the legislature at any time and to be financed by the issuance and sale of bonds.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c390.pdf?cite=1985%20c%20390%20§%2037[1985 c 390 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.705[1969 ex.s. c 223 § 28B.20.705]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c224.pdf?cite=1963%20c%20224%20§%202[1963 c 224 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c182.pdf?cite=1963%20c%20182%20§%201[1963 c 182 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c193.pdf?cite=1959%20c%20193%20§%202[1959 c 193 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c254.pdf?cite=1957%20c%20254%20§%202[1957 c 254 § 2]; ]

== 28B.20.710 - Contracts, issuance of evidences of indebtedness, acceptance of grants.
In addition to the powers conferred under existing law, the board is authorized and shall have the power:

. To contract for the construction, completion, reconstruction, remodeling, rehabilitation and improvement of such buildings or other facilities of the university as are and which may hereafter be authorized by the legislature.

. To finance the same by the issuance of bonds secured by the pledge of any or all of the revenues and receipts of the bond retirement fund.

. Without limitation of the foregoing, to accept grants from the United States government, or any federal or state agency or instrumentality, or any public or private corporation, association, or person to aid in defraying the costs of any such projects.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.710[1969 ex.s. c 223 § 28B.20.710]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c182.pdf?cite=1963%20c%20182%20§%202[1963 c 182 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c193.pdf?cite=1959%20c%20193%20§%203[1959 c 193 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c254.pdf?cite=1957%20c%20254%20§%203[1957 c 254 § 3]; ]

== 28B.20.715 - Bonds—Issuance, sale, form, term, interest, etc.—Covenants—Use of proceeds.
For the purpose of financing the cost of any projects, the board is hereby authorized to adopt the resolution or resolutions and prepare all other documents necessary for the issuance, sale and delivery of the bonds or any part thereof at such time or times as it shall deem necessary and advisable. Said bonds:

. Shall not constitute

.. An obligation, either general or special, of the state; or

.. A general obligation of the University of Washington or of the board;

. Shall be

.. Either registered or in coupon form; and

.. Issued in denominations of not less than one hundred dollars; and

.. Fully negotiable instruments under the laws of this state; and

.. Signed on behalf of the university by the president of the board, attested by the secretary of the board, have the seal of the university impressed thereon or a facsimile of such seal printed or lithographed in the bottom border thereof, and the coupons attached thereto shall be signed with the facsimile signatures of such president and secretary;

. Shall state

.. The date of issue; and

.. The series of the issue and be consecutively numbered within the series; and

.. That, except as otherwise provided in subsection (8)(e) of this section, the bond is payable both principal and interest solely out of the bond retirement fund;

. Each series of bonds shall bear interest, payable either annually or semiannually, as the board may determine;

. Shall be payable both principal and interest out of the bond retirement fund;

. Shall be payable at such times over a period of not to exceed forty years from date of issuance, at such place or places, and with such reserved rights of prior redemption, as the board may prescribe;

. Shall be sold in such manner and at such price as the board may prescribe;

. Shall be issued under and subject to such terms, conditions and covenants providing for the payment of the principal thereof and interest thereon and such other terms, conditions, covenants and protective provisions safeguarding such payment, not inconsistent with this chapter, and as found to be necessary by the board for the most advantageous sale thereof, which may include but not be limited to:

.. A covenant that the building fees shall be established, maintained and collected in such amounts that will provide money sufficient to pay the principal of and interest on all bonds payable out of the bond retirement fund, to set aside and maintain the reserves required to secure the payment of such principal and interest, and to maintain any coverage which may be required over such principal and interest;

.. A covenant that a reserve account shall be created in the bond retirement fund to secure the payment of the principal of and interest on all bonds issued and a provision made that certain amounts be set aside and maintained therein;

.. A covenant that sufficient moneys may be transferred from the University of Washington building account to the bond retirement fund when ordered by the board of regents in the event there is ever an insufficient amount of money in the bond retirement fund to pay any installment of interest or principal and interest coming due on the bonds or any of them;

.. A covenant fixing conditions under which bonds on a parity with any bonds outstanding may be issued;

.. A covenant to obligate, to pay the principal of or interest on the bonds, all or a component of the fees and revenues of the University of Washington that are not subject to appropriation by the legislature and that do not constitute general state revenues as defined in Article VIII, section 1 of the state Constitution or general state revenues for the purpose of calculating statutory limits on state indebtedness pursuant to *RCW 39.42.060.

The proceeds of the sale of all bonds issued in accordance with this chapter shall be used solely for paying the costs of the projects, including costs of issuance and other financing costs.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2254-S.SL.pdf?cite=2009%20c%20499%20§%207[2009 c 499 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c390.pdf?cite=1985%20c%20390%20§%2038[1985 c 390 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c56.pdf?cite=1970%20ex.s.%20c%2056%20§%2026[1970 ex.s. c 56 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c232.pdf?cite=1969%20ex.s.%20c%20232%20§%20100[1969 ex.s. c 232 § 100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.715[1969 ex.s. c 223 § 28B.20.715]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c193.pdf?cite=1959%20c%20193%20§%204[1959 c 193 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c254.pdf?cite=1957%20c%20254%20§%204[1957 c 254 § 4]; ]

== 28B.20.720 - University of Washington bond retirement fund—Composition—Pledge of building fees.
For the purpose of paying and securing the payment of the principal of and interest on the bonds as the same shall become due, there is created in the custody of the state treasurer a special trust fund to be known as the University of Washington bond retirement fund. An appropriation is not required for expenditures from the fund. There shall be paid into the fund, the following:

. One-half of such building fees as the board may from time to time determine, or such larger portion as may be necessary to prevent default in the payments required to be made out of the bond retirement fund;

. Any gifts, bequests, or grants which may be made, or may become available, for the purpose of furthering the construction of any authorized projects, or for the repayment of the costs thereof;

. Such additional funds as the legislature may provide.

While any bonds issued in accordance with the provisions of this chapter or any interest thereon remain unpaid, the bond retirement fund shall be available solely for the payment thereof except as provided in RCW 28B.20.725(5). As a part of the contract of sale of such bonds, the board undertakes to charge and collect building fees and to deposit the portion of such fees in the bond retirement fund in amounts which will be sufficient to pay the principal of, and interest on all such bonds outstanding.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2254-S.SL.pdf?cite=2009%20c%20499%20§%203[2009 c 499 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c390.pdf?cite=1985%20c%20390%20§%2039[1985 c 390 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.720[1969 ex.s. c 223 § 28B.20.720]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c193.pdf?cite=1959%20c%20193%20§%205[1959 c 193 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c254.pdf?cite=1957%20c%20254%20§%205[1957 c 254 § 5]; ]

== 28B.20.721 - Revenues derived from certain university lands deposited in University of Washington bond retirement fund.
All moneys received from the lease or rental of lands set apart by the enabling act for university purposes; all interest or income arising from the proceeds of the sale of such lands or of the timber, fallen timber, stone, gravel, or other valuable material thereon; and all moneys received as interest on deferred payments on contracts for the sale of such lands shall be deposited in the "University of Washington bond retirement fund" to be expended for the purposes set forth in RCW 28B.20.720.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.721[1969 ex.s. c 223 § 28B.20.721]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c216.pdf?cite=1963%20c%20216%20§%201[1963 c 216 § 1]; ]

== 28B.20.725 - Additional powers of board—Issuance of bonds, investments, transfer of funds, etc.
The board is hereby empowered:

. To reserve the right to issue bonds later on a parity with any bonds being issued;

. To authorize the investing of moneys in the bond retirement fund and any reserve account therein;

. To authorize the transfer of money from the University of Washington building account to the bond retirement fund when necessary to prevent a default in the payments required to be made out of such fund;

. To create a reserve account or accounts in the bond retirement fund to secure the payment of the principal of and interest on any bonds;

. To authorize the transfer to the University of Washington building account of any money on deposit in the bond retirement fund in excess of debt service for a period of three years from the date of such transfer on all outstanding bonds payable out of such fund. However, during the 2019-2021 fiscal biennium, the legislature may transfer to the University of Washington building account moneys that are in excess of the debt service due within the 2019-2021 fiscal biennium from the date of such transfer on all outstanding bonds payable out of the bond retirement fund. However, during the 2021-2023 fiscal biennium, the legislature may transfer to the University of Washington building account moneys that are in excess of the debt service due within the 2021-2023 fiscal biennium from the date of such transfer on all outstanding bonds payable out of the bond retirement fund.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1080-S.SL.pdf?cite=2021%20c%20332%20§%207027[2021 c 332 § 7027]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1102-S.SL.pdf?cite=2019%20c%20413%20§%207025[2019 c 413 § 7025]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6090-S.SL.pdf?cite=2018%20c%202%20§%207019[2018 c 2 § 7019]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=2015%203rd%20sp.s.%20c%203%20§%207025[2015 3rd sp.s. c 3 § 7025]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5035-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%2019%20§%207027[2013 2nd sp.s. c 19 § 7027]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1497-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2048%20§%207020[2011 1st sp.s. c 48 § 7020]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2836-S.SL.pdf?cite=2010%201st%20sp.s.%20c%2036%20§%206008[2010 1st sp.s. c 36 § 6008]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.725[1969 ex.s. c 223 § 28B.20.725]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c193.pdf?cite=1959%20c%20193%20§%206[1959 c 193 § 6]; ]

== 28B.20.730 - Refunding bonds.
The board is hereby empowered to issue refunding bonds to provide funds to refund any or all outstanding bonds payable from the bond retirement fund and to pay any redemption premium payable on such outstanding bonds being refunded. Such refunding bonds may be issued in the manner and on terms and conditions and with the covenants permitted by this chapter for the issuance of bonds. The refunding bonds shall be payable out of the bond retirement fund and shall not constitute an obligation either general or special, of the state or a general obligation of the University of Washington or the board. The board may exchange the refunding bonds at par for the bonds which are being refunded or may sell them in such manner, at such price and at such rate or rates of interest as it deems for the best interest of the university.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c56.pdf?cite=1970%20ex.s.%20c%2056%20§%2027[1970 ex.s. c 56 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c232.pdf?cite=1969%20ex.s.%20c%20232%20§%20101[1969 ex.s. c 232 § 101]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.730[1969 ex.s. c 223 § 28B.20.730]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c193.pdf?cite=1959%20c%20193%20§%208[1959 c 193 § 8]; ]

== 28B.20.735 - Bonds not general obligations—Legislature may provide additional means of payment.
The bonds authorized to be issued pursuant to the provisions of RCW 28B.20.700 through 28B.20.740 shall not be general obligations of the state of Washington, but shall be limited obligation bonds payable only from the special fund created for their payment as herein provided. The legislature may provide additional means for raising money for the payment of interest and principal of said bonds. RCW 28B.20.700 through 28B.20.740 shall not be deemed to provide an exclusive method for such payment. The power given to the legislature by this section to provide additional means for raising money is permissive, and shall not in any way be construed as a pledge of the general credit of the state of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2254-S.SL.pdf?cite=2009%20c%20499%20§%208[2009 c 499 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c390.pdf?cite=1985%20c%20390%20§%2040[1985 c 390 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.735[1969 ex.s. c 223 § 28B.20.735]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c254.pdf?cite=1957%20c%20254%20§%207[1957 c 254 § 7]; ]

== 28B.20.740 - RCW  28B.20.700 through  28B.20.740 as concurrent with other laws.
RCW 28B.20.700 through 28B.20.740 is to be construed as concurrent with other legislation with reference to providing funds for the construction of buildings at the University of Washington, and is not to be construed as limiting any other provision of law with reference thereto.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.740[1969 ex.s. c 223 § 28B.20.740]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c254.pdf?cite=1957%20c%20254%20§%2010[1957 c 254 § 10]; ]

== 28B.20.744 - University buildings and facilities for critical patient care or specialized medical research—Alternative process for awarding contracts—Reports.
. This section provides an alternative process for awarding contracts for construction, building, renovation, remodeling, alteration, repair, or improvement of university buildings and facilities in which critical patient care or highly specialized medical research is located. These provisions may be used, in lieu of other procedures to award contracts for such work, when the estimated cost of the work is equal to or less than five million dollars and the project involves construction, renovation, remodeling, or alteration of improvements within a building that is used directly for critical patient care or highly specialized medical research.

. The university may create a single critical patient care or specialized medical research facilities roster or may create multiple critical patient care or specialized medical research facilities rosters for different trade specialties or categories of anticipated work. At least once a year, the university shall publish in a newspaper of general circulation and with the office of minority and women's business enterprises, a notice of the existence of the roster or rosters and solicit a statement of qualifications from contractors who wish to be on the roster or rosters of prime contractors. In addition, qualified contractors shall be added to the roster or rosters at any time they submit a written request, necessary records, and meet the qualifications established by the university. The university may require eligible contractors desiring to be placed on a roster to keep current records of any applicable licenses, certifications, registrations, bonding, insurance, or other appropriate matters on file with the university with input from the women-owned and minority-owned business community as a condition of being placed on a roster or rosters. Placement on a roster shall be on the basis of qualifications.

. The public solicitation of qualifications shall include but not be limited to:

.. A description of the types of projects to be completed and where possible may include programmatic, performance, and technical requirements and specifications;

.. The reasons for using the critical patient care and specialized medical research roster process;

.. A description of the qualifications to be required of a contractor, including submission of an accident prevention program;

.. A description of the process the university will use to evaluate qualifications, including evaluation factors and the relative weight of factors;

.. The form of the contract to be awarded;

.. A description of the administrative process by which the required qualifications, evaluation process, and project types may be appealed; and

.. A description of the administrative process by which decisions of the university may be appealed.

. The university shall establish a committee that includes one representative from the minority-owned business community and one representative from the women-owned business community to evaluate the contractors submitting qualifications. Evaluation criteria for selection of the contractor or contractors to be included on a roster shall include, but not be limited to:

.. Ability of a contractor's professional personnel;

.. A contractor's past performance on similar projects, including but not limited to medical facilities, and involving either negotiated work or other public works contracts;

.. The contractor's ability to meet time and budget requirements;

.. The contractor's ability to provide preconstruction services, as appropriate;

.. The contractor's capacity to successfully complete the project;

.. The contractor's approach to executing projects;

.. The contractor's approach to safety and the contractor's safety history;

.. The contractor's record of performance, integrity, judgment, and skills;

.. The contractor's record of including office of minority and women's business enterprises-certified, minority, women, veteran, and small businesses; and

.. The contractor's past history of use of small business entities, disadvantaged business enterprises, minority business enterprises, women business enterprises, and minority women business enterprises over the last five years on projects of five million dollars or less and the contractor's proposed outreach plan and commitment to include such firms.

. Contractors meeting the evaluation committee's criteria for selection must be placed on the applicable roster or rosters.

. When a project is selected for delivery through this roster process, the university must establish a procedure for securing written quotations from all contractors on a roster to assure that a competitive price is established. Invitations for quotations shall include an estimate of the scope and nature of the work to be performed as well as materials and equipment to be furnished. Plans and specifications must be included in the invitation but may not be detailed. Award of a project must be made to the responsible bidder submitting the lowest responsive bid.

. The university shall make an effort to solicit proposals from certified minority or certified woman-owned contractors. The university business diversity program shall establish aspirational goals for small business entities, disadvantaged business enterprises, minority business enterprises, women business enterprises, and minority women business enterprises for each roster based on the projected subcontracting opportunities and to the extent permitted by the Washington state civil rights act, RCW 49.60.400.

. Beginning in September 2010 and every other September thereafter, the university shall provide a report to the capital projects advisory review board which must, at a minimum, include a list of rosters used, contracts awarded, office of minority and women's business enterprises-certified small business entities, disadvantaged business enterprises, veterans, and women and minority-owned business use rates on the projects.

. Beginning in September 2015 and every September thereafter, the university shall report to the office of minority and women's business enterprises and to the appropriate legislative fiscal committees the number of qualified women and minority-owned business contractors on the roster or rosters and the number of contracts awarded to women and minority-owned businesses.

. The university shall require contractors to solicit proposals from office of minority and women's business enterprises-certified firms.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5631.SL.pdf?cite=2017%20c%20124%20§%201[2017 c 124 § 1]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1115.SL.pdf?cite=2015%203rd%20sp.s.%20c%203%20§%207043[2015 3rd sp.s. c 3 § 7043]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6355-S.SL.pdf?cite=2010%20c%20245%20§%2011[2010 c 245 § 11]; ]

== 28B.20.745 - Validation—1959 c 193.
Any covenants of the bonds issued by the University of Washington under the authority of chapter 254, Laws of 1957 not expressly authorized by said chapter but authorized in chapter 193, Laws of 1959 are hereby declared to be legal and binding in all respects.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.745[1969 ex.s. c 223 § 28B.20.745]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c193.pdf?cite=1959%20c%20193%20§%2011[1959 c 193 § 11]; ]

== 28B.20.746 - Development of curriculum for pharmacy students on suicide assessment, treatment, and management—Work group.
The schools of pharmacy at the University of Washington and Washington State University shall convene a work group to jointly develop a curriculum on suicide assessment, treatment, and management for pharmacy students. The curriculum must include material on identifying at-risk patients and limiting access to lethal means. When developing the curriculum, the schools shall consult with experts on suicide assessment, treatment, and management, and with the safe homes task force created in *RCW 43.70.445 on appropriate suicide awareness and prevention messaging. The schools of pharmacy shall submit a progress report to the governor and the relevant committees of the legislature by December 1, 2016.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2793-S2.SL.pdf?cite=2016%20c%2090%20§%206[2016 c 90 § 6]; ]

== 28B.20.770 - Acquisition, construction, equipping and betterment of lands, buildings and facilities at universities and The Evergreen State College.
See RCW 28B.10.300 through 28B.10.330.

[ ]

== 28B.20.800 - Revenues derived from certain university lands and income from university permanent fund deposited in University of Washington bond retirement fund—Covenant.
All moneys hereafter received from the lease or rental of lands set apart for the University of Washington by chapter 91, Laws of 1903 and section 9, chapter 122, Laws of 1893, and all interest or income arising from the proceeds of the sale of such land, less the allocation to the state treasurer's service account [fund] pursuant to RCW 43.08.190 and the state investment board expense account pursuant to RCW 43.33A.160, and all proceeds from the sale of timber, fallen timber, stone, gravel, or other valuable material and all other receipts therefrom shall be deposited to the credit of the "University of Washington bond retirement fund" to be expended for the purposes set forth in RCW 28B.20.720. All proceeds of sale of such lands, exclusive of investment income, shall be deposited to the credit of the state university permanent fund, shall be retained therein and shall not be transferred to any other fund or account. All interest earned or income received from the investment of the money in the state university permanent fund shall be deposited to the credit of the University of Washington bond retirement fund less the allocations to the state treasurer's service fund pursuant to RCW 43.08.190 and the state investment board expense account pursuant to RCW 43.33A.160.

As a part of the contract of sale of bonds payable out of the University of Washington bond retirement fund, the board of regents of the University of Washington may covenant that all moneys derived from the above provided sources, which are required to be paid into the bond retirement fund, shall continue to be paid into such bond retirement fund for as long as any of such bonds are outstanding.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1058-S.SL.pdf?cite=1991%20sp.s.%20c%2013%20§%2097[1991 sp.s. c 13 § 97]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.800[1969 ex.s. c 223 § 28B.20.800]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c135.pdf?cite=1965%20ex.s.%20c%20135%20§%201[1965 ex.s. c 135 § 1]; ]

== 28B.20.805 - Revenues derived from certain university lands and income from university permanent fund deposited in University of Washington bond retirement fund—Ratification of previous transfers.
The transfers heretofore made of all moneys from the sources described in RCW 28B.20.800 and 43.79.201 into the University of Washington bond retirement fund and permanent fund are in all respects ratified and confirmed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.805[1969 ex.s. c 223 § 28B.20.805]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c135.pdf?cite=1965%20ex.s.%20c%20135%20§%203[1965 ex.s. c 135 § 3]; ]

== 28B.20.810 - Revenues derived from certain university lands and income from university permanent fund deposited in University of Washington bond retirement fund—Transfers of certain funds and investments from university permanent fund to University of Washington bond retirement fund and University of Washington building account.
The board of regents of the University of Washington is empowered to authorize from time to time the transfer from the state university permanent fund to be held in reserve in the bond retirement fund created by RCW 28B.20.720 any unobligated funds and investments derived from lands set apart for the support of the university by chapter 91, Laws of 1903 and section 9, chapter 122, Laws of 1893, to the extent required to comply with bond covenants regarding principal and interest payments and reserve requirements for bonds payable out of the bond retirement fund up to a total amount of five million dollars, and to transfer any or all of said unobligated funds and investments in excess of five million dollars to the university building account created by *RCW 43.79.330(22). Any funds transferred to the bond retirement fund pursuant to this section shall be replaced by moneys first available out of the moneys required to be deposited in such fund pursuant to RCW 28B.20.800. The board is further empowered to direct the state finance committee to convert any investments in such permanent fund acquired with funds derived from such lands into cash or obligations of or guaranteed by the United States of America prior to the transfer of such funds and investments to such reserve account or building account.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1058-S.SL.pdf?cite=1991%20sp.s.%20c%2013%20§%2078[1991 sp.s. c 13 § 78]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.810[1969 ex.s. c 223 § 28B.20.810]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c135.pdf?cite=1965%20ex.s.%20c%20135%20§%204[1965 ex.s. c 135 § 4]; ]

== 28B.20.820 - Revenues derived from certain university lands and income from university permanent fund deposited in University of Washington bond retirement fund—RCW  79.64.040 not affected.
Nothing contained in RCW 28B.20.800 through 28B.20.820 and RCW 43.79.201 is intended to amend or modify RCW 79.64.040 (section 4, chapter 178, Laws of 1961).

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c223.pdf?cite=1969%20ex.s.%20c%20223%20§%2028B.20.820[1969 ex.s. c 223 § 28B.20.820]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c135.pdf?cite=1965%20ex.s.%20c%20135%20§%205[1965 ex.s. c 135 § 5]; ]

== 28B.20.830 - Collaborative for the advancement of telemedicine—Reports—Open meetings.
. The collaborative for the advancement of telemedicine is created to enhance the understanding and use of health services provided through telemedicine and other similar models in Washington state. The collaborative shall be hosted by the University of Washington telehealth services and shall be comprised of one member from each of the two largest caucuses of the senate and the house of representatives, and representatives from the academic community, hospitals, clinics, and health care providers in primary care and specialty practices, carriers, and other interested parties.

. By July 1, 2016, the collaborative shall be convened. The collaborative shall develop recommendations on improving reimbursement and access to services, including originating site restrictions, provider to provider consultative models, and technologies and models of care not currently reimbursed; identify the existence of telemedicine best practices, guidelines, billing requirements, and fraud prevention developed by recognized medical and telemedicine organizations; and explore other priorities identified by members of the collaborative. After review of existing resources, the collaborative shall explore and make recommendations on whether to create a technical assistance center to support providers in implementing or expanding services delivered through telemedicine technologies.

. The collaborative must submit an initial progress report by December 1, 2016, with follow-up policy reports including recommendations by December 1, 2017, December 1, 2018, and December 1, 2021. The reports shall be shared with the relevant professional associations, governing boards or commissions, and the health care committees of the legislature.

. The collaborative shall study store and forward technology, with a focus on:

.. Utilization;

.. Whether store and forward technology should be paid for at parity with in-person services;

.. The potential for store and forward technology to improve rural health outcomes in Washington state; and

.. Ocular services.

. The meetings of the board shall be open public meetings, with meeting summaries available on a web page.

. The collaborative must study the need for an established patient/provider relationship before providing audio-only telemedicine, including considering what types of services may be provided without an established relationship. By December 1, 2021, the collaborative must submit a report to the legislature on its recommendations regarding the need for an established relationship for audio-only telemedicine.

. The future of the collaborative shall be reviewed by the legislature with consideration of ongoing technical assistance needs and opportunities. The collaborative terminates December 31, 2023.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1196-S.SL.pdf?cite=2021%20c%20157%20§%209[2021 c 157 § 9]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5385-S.SL.pdf?cite=2020%20c%2092%20§%204[2020 c 92 § 4]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6163.SL.pdf?cite=2018%20c%20256%20§%201[2018 c 256 § 1]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6519-S.SL.pdf?cite=2016%20c%2068%20§%202[2016 c 68 § 2]; ]

