= 28B.52 - Collective bargaining—Academic personnel in community colleges.
:toc:

== 28B.52.010 - Declaration of purpose.
It is the purpose of this chapter to strengthen methods of administering employer-employee relations through the establishment of orderly methods of communication between academic employees and the college districts by which they are employed.

It is the purpose of this chapter to promote cooperative efforts by prescribing certain rights and obligations of the employees and employers and by establishing orderly procedures governing the relationship between the employees and their employers which procedures are designed to meet the special requirements and needs of public employment in higher education. It is the intent of this chapter to promote activity that includes the elements of open communication and access to information in a timely manner, with reasonable discussion and interpretation of that information. It is the further intent that such activity shall be characterized by mutual respect, integrity, reasonableness, and a desire on the part of the parties to address and resolve the points of concern.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5184-S.SL.pdf?cite=1991%20c%20238%20§%20145[1991 c 238 § 145]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c314.pdf?cite=1987%20c%20314%20§%201[1987 c 314 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c196.pdf?cite=1971%20ex.s.%20c%20196%20§%201[1971 ex.s. c 196 § 1]; ]

== 28B.52.020 - Definitions.
As used in this chapter:

. "Employee organization" means any organization which includes as members the academic employees of a college district and which has as one of its purposes the representation of the employees in their employment relations with the college district.

. "Academic employee" means any teacher, counselor, librarian, or department head, who is employed by any college district, whether full or part time, with the exception of the chief administrative officer of, and any administrator in, each college district.

. "Administrator" means any person employed either full or part time by the college district and who performs administrative functions as at least fifty percent or more of his or her assignments, and has responsibilities to hire, dismiss, or discipline other employees. Administrators shall not be members of the bargaining unit unless a majority of such administrators and a majority of the bargaining unit elect by secret ballot for such inclusion pursuant to rules as adopted in accordance with RCW 28B.52.080.

. "Commission" means the public employment relations commission.

. "Unfair labor practice" means any unfair labor practice listed in RCW 28B.52.073.

. "Exclusive bargaining representative" means any employee organization which has:

.. Been certified or recognized under this chapter as the representative of the employees in an appropriate collective bargaining unit; or

.. Before July 26, 1987, been certified or recognized under a predecessor statute as the representative of the employees in a bargaining unit which continues to be appropriate under this chapter.

. "Collective bargaining" and "bargaining" mean the performance of the mutual obligation of the representatives of the employer and the exclusive bargaining representative to meet at reasonable times to bargain in good faith in an effort to reach agreement with respect to wages, hours, and other terms and conditions of employment, such as procedures related to nonretention, dismissal, denial of tenure, and reduction in force. Prior law, practice, or interpretation shall be neither restrictive, expansive, nor determinative with respect to the scope of bargaining. A written contract incorporating any agreements reached shall be executed if requested by either party. The obligation to bargain does not compel either party to agree to a proposal or to make a concession.

In the event of a dispute between an employer and an exclusive bargaining representative over the matters that are terms and conditions of employment, the commission shall decide which items are mandatory subjects for bargaining.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1575-S.SL.pdf?cite=2019%20c%20230%20§%202[2019 c 230 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5184-S.SL.pdf?cite=1991%20c%20238%20§%20146[1991 c 238 § 146]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c314.pdf?cite=1987%20c%20314%20§%202[1987 c 314 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c296.pdf?cite=1975%201st%20ex.s.%20c%20296%20§%2012[1975 1st ex.s. c 296 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c205.pdf?cite=1973%201st%20ex.s.%20c%20205%20§%201[1973 1st ex.s. c 205 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c196.pdf?cite=1971%20ex.s.%20c%20196%20§%202[1971 ex.s. c 196 § 2]; ]

== 28B.52.025 - Right to organize or refrain from organizing.
Employees have the right to self-organization, to form, join, or assist employee organizations, to bargain collectively through representatives of their own choosing, and also have the right to refrain from any or all of these activities.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1575-S.SL.pdf?cite=2019%20c%20230%20§%204[2019 c 230 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c314.pdf?cite=1987%20c%20314%20§%205[1987 c 314 § 5]; ]

== 28B.52.027 - Application of RCW  41.56.037—Bargaining representative access to new employees.
RCW 41.56.037 applies to this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6229.SL.pdf?cite=2018%20c%20250%20§%202[2018 c 250 § 2]; ]

== 28B.52.030 - Representatives of employee organization—Right to collective bargaining.
Representatives of an employee organization, which organization shall by secret ballot have won a majority in an election to represent the academic employees within its college district, shall have the right to bargain.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1575-S.SL.pdf?cite=2019%20c%20230%20§%203[2019 c 230 § 3]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5184-S.SL.pdf?cite=1991%20c%20238%20§%20147[1991 c 238 § 147]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c314.pdf?cite=1987%20c%20314%20§%203[1987 c 314 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c205.pdf?cite=1973%201st%20ex.s.%20c%20205%20§%202[1973 1st ex.s. c 205 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c196.pdf?cite=1971%20ex.s.%20c%20196%20§%203[1971 ex.s. c 196 § 3]; ]

== 28B.52.035 - Negotiations reduced to written agreements—Provisions relating to salary increases—Restrictions.
. At the conclusion of any negotiation processes as provided for in RCW 28B.52.030, any matter upon which the parties have reached agreement shall be reduced to writing and acted upon in a regular or special meeting of the boards of trustees, and become part of the official proceedings of said board meeting. Except as provided in this section, provisions of written contracts relating to salary increases shall not exceed the amount or percentage established by the legislature in the appropriations act and allocated to the board of trustees by the state board for community and technical colleges.

. The written agreement acted upon by a board of trustees must be submitted to the director of the office of financial management by October 1 prior to the fiscal year in which the provisions of the agreement go into effect. The length of term of any such agreement shall be for not more than three fiscal years. If any provision of a salary increase is changed by subsequent modification of the appropriations act by the legislature, both parties shall immediately enter into collective bargaining for the sole purpose of arriving at a mutually agreed upon replacement for the modified provision. A board of trustees may provide additional compensation to academic employees that exceeds that provided by the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1237.SL.pdf?cite=2018%20c%20267%20§%202[2018 c 267 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5184-S.SL.pdf?cite=1991%20c%20238%20§%20148[1991 c 238 § 148]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c314.pdf?cite=1987%20c%20314%20§%204[1987 c 314 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c205.pdf?cite=1973%201st%20ex.s.%20c%20205%20§%204[1973 1st ex.s. c 205 § 4]; ]

== 28B.52.040 - Negotiated agreements—Procedures for binding arbitration.
A board of trustees or an employee organization that enters into a negotiated agreement under RCW 28B.52.030 may include in the agreement procedures for binding arbitration of the disputes arising about the interpretation or application of the agreement including but not limited to nonretention, dismissal, denial of tenure, and reduction in force.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c314.pdf?cite=1987%20c%20314%20§%206[1987 c 314 § 6]; ]

== 28B.52.043 - Collective bargaining—Employee authorization of membership dues—Revocation.
. [Empty]
.. An employee's written, electronic, or recorded voice authorization to have the employer deduct membership dues from the employee's salary must be made by the employee to the exclusive bargaining representative. If the employer receives a request for authorization of deductions, the employer shall as soon as practicable forward the request to the exclusive bargaining representative.

.. Upon receiving notice of the employee's authorization from the exclusive bargaining representative, the employer shall deduct from the employee's salary membership dues and remit the amounts to the exclusive bargaining representative.

.. The employee's authorization remains in effect until expressly revoked by the employee in accordance with the terms and conditions of the authorization.

. [Empty]
.. An employee's request to revoke authorization for payroll deductions must be in writing and submitted by the employee to the exclusive bargaining representative in accordance with the terms and conditions of the authorization.

.. After the employer receives confirmation from the exclusive bargaining representative that the employee has revoked authorization for deductions, the employer shall end the deduction no later than the second payroll after receipt of the confirmation.

. The employer shall rely on information provided by the exclusive bargaining representative regarding the authorization and revocation of deductions.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1575-S.SL.pdf?cite=2019%20c%20230%20§%205[2019 c 230 § 5]; ]

== 28B.52.045 - Collective bargaining—Exclusive bargaining representative—Dues and other payments.
. Upon authorization of an employee within the bargaining unit and after the certification or recognition of the bargaining unit's exclusive bargaining representative, the employer must deduct from the payments to the employee the monthly amount of dues as certified by the secretary of the exclusive bargaining representative and must transmit the same to the treasurer of the exclusive bargaining representative.

. If the employer and the exclusive bargaining representative of a bargaining unit enter into a collective bargaining agreement that includes requirements for deductions of other payments, the employer must make such deductions upon authorization of the employee.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1575-S.SL.pdf?cite=2019%20c%20230%20§%206[2019 c 230 § 6]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2751.SL.pdf?cite=2018%20c%20247%20§%201[2018 c 247 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c314.pdf?cite=1987%20c%20314%20§%208[1987 c 314 § 8]; ]

== 28B.52.050 - Academic employee may appear in own behalf.
Nothing in this chapter shall prohibit any academic employee from appearing in his or her own behalf on matters relating to his or her employment relations with the college district.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5184-S.SL.pdf?cite=1991%20c%20238%20§%20149[1991 c 238 § 149]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c196.pdf?cite=1971%20ex.s.%20c%20196%20§%204[1971 ex.s. c 196 § 4]; ]

== 28B.52.060 - Commission—Mediation activities—Other dispute resolution procedures authorized.
The commission shall conduct mediation activities upon the request of either party as a means of assisting in the settlement of unresolved matters considered under this chapter.

In the event that any matter being jointly considered by the employee organization and the board of trustees of the college district is not settled by the means provided in this chapter, either party, twenty-four hours after serving written notice of its intended action to the other party, may, request the assistance and advice of the commission. Nothing in this section prohibits an employer and an employee organization from agreeing to substitute, at their own expense, some other impasse procedure or other means of resolving matters considered under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5184-S.SL.pdf?cite=1991%20c%20238%20§%20150[1991 c 238 § 150]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c314.pdf?cite=1987%20c%20314%20§%209[1987 c 314 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c296.pdf?cite=1975%201st%20ex.s.%20c%20296%20§%2013[1975 1st ex.s. c 296 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c205.pdf?cite=1973%201st%20ex.s.%20c%20205%20§%203[1973 1st ex.s. c 205 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c196.pdf?cite=1971%20ex.s.%20c%20196%20§%205[1971 ex.s. c 196 § 5]; ]

== 28B.52.065 - Commission's adjudication of unfair labor practices—Rules—Binding arbitration authorized.
The commission may adjudicate any unfair labor practices alleged by a board of trustees or an employee organization and shall adopt reasonable rules to administer this section, except that a complaint must not be processed for any unfair labor practice occurring more than six months before the filing of the complaint with the commission or in superior court. However, the parties may agree to seek relief from unfair labor practices through binding arbitration.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6231.SL.pdf?cite=2018%20c%20252%20§%207[2018 c 252 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c314.pdf?cite=1987%20c%20314%20§%2010[1987 c 314 § 10]; ]

== 28B.52.070 - Discrimination prohibited.
Boards of trustees of college districts or any administrative officer thereof shall not discriminate against academic employees or applicants for such positions because of their membership or nonmembership in employee organizations or their exercise of other rights under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5184-S.SL.pdf?cite=1991%20c%20238%20§%20151[1991 c 238 § 151]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c196.pdf?cite=1971%20ex.s.%20c%20196%20§%206[1971 ex.s. c 196 § 6]; ]

== 28B.52.073 - Unfair labor practices.
. It shall be an unfair labor practice for an employer:

.. To interfere with, restrain, or coerce employees in the exercise of the rights guaranteed by this chapter;

.. To dominate or interfere with the formation or administration of any employee organization or contribute financial or other support to it: PROVIDED, That subject to rules adopted by the commission, an employer shall not be prohibited from permitting employees to confer with it or its representatives or agents during working hours without loss of time or pay;

.. To encourage or discourage membership in any employee organization by discrimination in regard to hire, tenure of employment, or any term or condition of employment;

.. To discharge or discriminate otherwise against an employee because that employee has filed charges or given testimony under this chapter;

.. To refuse to bargain collectively with the representatives of its employees.

. It shall be an unfair labor practice for an employee organization:

.. To restrain or coerce an employee in the exercise of the rights guaranteed by this chapter: PROVIDED, That this subsection shall not impair the right of an employee organization to prescribe its own rules with respect to the acquisition or retention of membership in the employee organization or to an employer in the selection of its representatives for the purpose of bargaining or the adjustment of grievances;

.. To cause or attempt to cause an employer to discriminate against an employee in violation of subsection (1)(c) of this section;

.. To discriminate against an employee because that employee has filed charges or given testimony under this chapter;

.. To refuse to bargain collectively with an employer.

. The expressing of any views, arguments, or opinion, or the dissemination thereof to the public, whether in written, printed, graphic, or visual form, shall not constitute or be evidence of an unfair labor practice under this chapter, if such expression contains no threat of reprisal or force or promise of benefit.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c314.pdf?cite=1987%20c%20314%20§%2011[1987 c 314 § 11]; ]

== 28B.52.078 - Strikes and lockouts prohibited—Violations—Remedies.
The right of college faculty to engage in any strike is prohibited. The right of a board of trustees to engage in any lockout is prohibited. Should either a strike or lockout occur, the representative of the faculty or board of trustees may invoke the jurisdiction of the superior court in the county in which the labor dispute exists and such court shall have jurisdiction to issue an appropriate order against either or both parties. In fashioning an order, the court shall take into consideration not only the elements necessary for injunctive relief but also the purpose and goals of this chapter and any mitigating factors such as the commission of an unfair labor practice by either party.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5184-S.SL.pdf?cite=1991%20c%20238%20§%20152[1991 c 238 § 152]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c314.pdf?cite=1987%20c%20314%20§%2013[1987 c 314 § 13]; ]

== 28B.52.080 - Commission to adopt rules and regulations—Boards may request commission services.
The commission shall adopt reasonable rules and regulations for the administration of employer-employee relations under this chapter. The boards may request the services of the commission to assist in the conduction of certification elections as provided for in RCW 28B.52.030.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c296.pdf?cite=1975%201st%20ex.s.%20c%20296%20§%2014[1975 1st ex.s. c 296 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c205.pdf?cite=1973%201st%20ex.s.%20c%20205%20§%205[1973 1st ex.s. c 205 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c196.pdf?cite=1971%20ex.s.%20c%20196%20§%207[1971 ex.s. c 196 § 7]; ]

== 28B.52.090 - Prior agreements.
Nothing in this chapter shall be construed to annul or modify, or to preclude the renewal or continuation of, any lawful agreement heretofore entered into between any college district and any representative of its employees.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5184-S.SL.pdf?cite=1991%20c%20238%20§%20153[1991 c 238 § 153]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c196.pdf?cite=1971%20ex.s.%20c%20196%20§%208[1971 ex.s. c 196 § 8]; ]

== 28B.52.100 - State higher education administrative procedure act not to affect.
Contracts or agreements, or any provision thereof entered into between boards of trustees and employees organizations pursuant to this chapter shall not be affected by or be subject to chapter 34.05 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c196.pdf?cite=1971%20ex.s.%20c%20196%20§%209[1971 ex.s. c 196 § 9]; ]

== 28B.52.200 - Scope of chapter—Limitations—When attempts to resolve dispute required.
Nothing in chapter 28B.52 RCW as now or hereafter amended shall compel either party to agree to a proposal or to make a concession, nor shall any provision in chapter 28B.52 RCW as now or hereafter amended be construed as limiting or precluding the exercise by each college board of trustees of any powers or duties authorized or provided to it by law unless such exercise is contrary to the terms and conditions of any lawful negotiated agreement, except that other than to extend the terms of a previous contract, a board of trustees shall not take unilateral action on any unresolved issue under negotiation, unless the parties have first participated in good faith mediation or some other procedure as authorized by RCW 28B.52.060 to seek resolution of the issue.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5184-S.SL.pdf?cite=1991%20c%20238%20§%20154[1991 c 238 § 154]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c314.pdf?cite=1987%20c%20314%20§%2012[1987 c 314 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c205.pdf?cite=1973%201st%20ex.s.%20c%20205%20§%206[1973 1st ex.s. c 205 § 6]; ]

== 28B.52.210 - Scope of chapter—Community and technical colleges faculty awards trust program.
With respect to the community and technical colleges faculty awards trust program, the permissible scope of collective bargaining under this chapter shall be governed by RCW 28B.50.843.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5184-S.SL.pdf?cite=1991%20c%20238%20§%20155[1991 c 238 § 155]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c29.pdf?cite=1990%20c%2029%20§%206[1990 c 29 § 6]; ]

== 28B.52.220 - Scope of chapter—Community and technical colleges part-time academic employees.
With respect to the community and technical colleges part-time academic employees, the permissible scope of collective bargaining under this chapter shall be governed by RCW 28B.50.4893 and 28B.50.489.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6811-S2.SL.pdf?cite=2000%20c%20128%20§%204[2000 c 128 § 4]; ]

== 28B.52.300 - Construction of chapter.
Except as otherwise expressly provided in this chapter, this chapter shall not be construed to deny or otherwise abridge any rights, privileges, or benefits granted by law to employees. This chapter shall not be construed to interfere with the responsibilities and rights of the board of trustees as specified by federal and state law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c314.pdf?cite=1987%20c%20314%20§%207[1987 c 314 § 7]; ]

