= 28B.103 - Washington national guard postsecondary education grant program.
:toc:

== 28B.103.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this section and RCW 28B.103.020 and 28B.103.030.

. "Eligible student" means a member of the Washington national guard who attends an institution of higher education that is located in this state and accredited by the Northwest Association of Schools and Colleges, or an institution that is located in this state that provides approved training under the Montgomery GI Bill, and who meets any additional selection criteria adopted by the office and all of the following participation requirements:

.. Has not achieved a baccalaureate or higher degree from any postsecondary institution;

.. Is an active drilling member in good standing in the Washington national guard as specified in rules adopted by the office for implementation of the Washington national guard postsecondary education grant;

.. Has completed and submitted an application for student aid approved by the office;

.. Is a resident student as defined in RCW 28B.15.012; and

.. Agrees to fulfill his or her service obligation.

. "Forgiven" or "to forgive" or "forgiveness" means either to render service in the Washington national guard in lieu of monetary repayment, or to be relieved of the service obligation under rules adopted by the office.

. "Grant" means the Washington national guard postsecondary education grant as established in RCW 28B.103.020.

. "Office" means the office of student financial assistance created in RCW 28B.76.090.

. "Participant" means an eligible student who has received a Washington national guard postsecondary education grant under this chapter.

. "Service obligation" means serving in the Washington national guard for a time period of at least one year of service in the Washington national guard for each year the student receives a Washington national guard postsecondary education grant.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5197.SL.pdf?cite=2020%20c%20297%20§%201[2020 c 297 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6766.SL.pdf?cite=2006%20c%2071%20§%201[2006 c 71 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2022-S.SL.pdf?cite=2000%20c%20159%20§%201[2000 c 159 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2605-S2.SL.pdf?cite=1994%20c%20234%20§%205[1994 c 234 § 5]; ]

== 28B.103.020 - Program established—Powers and duties of office.
Subject to amounts appropriated for this specific purpose, the Washington national guard postsecondary education grant program is established. The program shall be administered by the office. In administering the program, the powers and duties of the office shall include, but need not be limited to:

. With the assistance of the Washington military department, the selection of eligible students to receive the Washington national guard postsecondary education grant as follows:

.. An eligible student may receive a grant under this section to help pay for postsecondary education program costs as approved by the office. Awards shall be valued as follows:

... The difference between the student's tuition and required fees, less the value of any federal and state funded grant, scholarship, or waiver assistance the students [student] receives; and

... Five hundred dollars for books and materials.

.. The Washington military department shall ensure that data needed to identify eligible recipients are promptly transmitted to the office.

.. The annual amount of each Washington national guard postsecondary education grant may vary, but may not exceed the annual cost of undergraduate tuition fees and services and activities fees at the University of Washington, plus an allowance for books and supplies.

.. Washington national guard postsecondary [education] grant eligibility may not extend beyond five years or one hundred twenty-five percent of the published length of the program in which the student is enrolled or the credit or clock-hour equivalent;

. The award of grants funded by federal and state funds, private donations, or repayments from any participant who does not complete the participant's service obligation;

. The adoption of necessary rules and policies, including establishing a priority for eligible students attending an institution of higher education located in this state that is accredited by the Northwest Association of Schools and Colleges;

. The adoption of participant selection criteria. The criteria may include but need not be limited to requirements for: Satisfactory academic progress, enrollment in courses or programs that lead to a baccalaureate degree or an associate degree or a certificate, and satisfactory participation as a member of the Washington national guard;

. With the assistance of the Washington military department, the notification of participants of their additional service obligation or required repayment of the Washington national guard postsecondary education grant; and

. The collection of repayments from participants who do not meet the service obligations.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5197.SL.pdf?cite=2020%20c%20297%20§%202[2020 c 297 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6766.SL.pdf?cite=2006%20c%2071%20§%202[2006 c 71 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2605-S2.SL.pdf?cite=1994%20c%20234%20§%206[1994 c 234 § 6]; ]

== 28B.103.030 - Repayment obligation.
. Participants in the Washington national guard postsecondary education grant program incur an obligation to repay the grant, with interest, unless they serve in the Washington national guard for one year for each year they received the grant, under rules adopted by the office.

. The office shall adopt rules addressing the terms for repayment, including applicable interest rates, fees, and deferments, by a participant who does not render service as a member of the Washington national guard necessary to satisfy his or her service obligation.

. The office is responsible for collection of repayments made under this section. The office shall exercise due diligence in such collection, maintaining all necessary records to ensure that maximum repayments are made. Collection and servicing of repayments under this section shall be pursued using the full extent of law, including wage garnishment if necessary. The office is responsible to forgive all or parts of such repayments under the criteria established in this section, and shall maintain all necessary records of forgiven payments.

. Receipts from the payment of principal or interest paid by or on behalf of participants shall be deposited with the office and shall be used to cover the costs of administration of the grant, maintaining necessary records, and making collections under subsection (3) of this section. The office shall maintain accurate records of these costs, and all receipts beyond those necessary to pay such costs shall be used to make grant awards to eligible students.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5197.SL.pdf?cite=2020%20c%20297%20§%203[2020 c 297 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20607[2012 c 229 § 607]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2605-S2.SL.pdf?cite=1994%20c%20234%20§%207[1994 c 234 § 7]; ]

