= 28B.109 - Washington international exchange scholarship program.
:toc:

== 28B.109.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Eligible participant" means an international student whose country of residence has a trade relationship with the state of Washington.

. "Institution of higher education" or "institution" means a college or university in the state of Washington that is accredited by an accrediting association recognized as such by rule of the student achievement council.

. "Office" means the office of student financial assistance.

. "Service obligation" means volunteering for a minimum number of hours as established by the student achievement council based on the amount of scholarship award, to speak to or teach groups of Washington citizens, including but not limited to elementary, middle, and high schools, service clubs, and universities.

. "Washington international exchange scholarship program" means a scholarship award for a period not to exceed one academic year to attend a Washington institution of higher education made to an international student whose country has an established trade relationship with Washington.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20565[2012 c 229 § 565]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20195[2011 1st sp.s. c 11 § 195]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2291.SL.pdf?cite=1996%20c%20253%20§%20401[1996 c 253 § 401]; ]

== 28B.109.020 - Washington international exchange scholarship program—Administration by office of student financial assistance.
The Washington international exchange scholarship program is created. The program shall be administered by the office. In administering the program, the office may:

. Convene an advisory committee that may include but need not be limited to representatives of the office of the superintendent of public instruction, the department of commerce, the secretary of state, private business, and institutions of higher education;

. Select students to receive the scholarship with the assistance of a screening committee composed of leaders in business, international trade, and education;

. Adopt necessary rules and guidelines including rules for disbursing scholarship funds to participants;

. Publicize the program;

. Solicit and accept grants and donations from public and private sources for the program;

. Establish and notify participants of service obligations; and

. Establish a formula for selecting the countries from which participants may be selected in consultation with the department of commerce.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6581-S.SL.pdf?cite=2012%20c%20198%20§%2022[2012 c 198 § 22]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20196[2011 1st sp.s. c 11 § 196]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2291.SL.pdf?cite=1996%20c%20253%20§%20402[1996 c 253 § 402]; ]

== 28B.109.030 - Reciprocal agreements to attend foreign institutions.
The office may negotiate and enter into a reciprocal agreement with foreign countries that have international students attending institutions in Washington. The goal of the reciprocal agreements shall be to allow Washington students enrolled in an institution of higher education to attend an international institution under similar terms and conditions.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20197[2011 1st sp.s. c 11 § 197]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2291.SL.pdf?cite=1996%20c%20253%20§%20403[1996 c 253 § 403]; ]

== 28B.109.040 - Washington international exchange student scholarships.
If funds are available, the office shall select students yearly to receive a Washington international exchange student scholarship from funds appropriated to the office for this purpose, or from any private donations, or from any other funds given to the office for this program.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6581-S.SL.pdf?cite=2012%20c%20198%20§%2023[2012 c 198 § 23]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20198[2011 1st sp.s. c 11 § 198]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2291.SL.pdf?cite=1996%20c%20253%20§%20404[1996 c 253 § 404]; ]

== 28B.109.070 - Washington international exchange scholarship endowment fund—State matching funds.
The office may request that the treasurer deposit state matching funds into the Washington international exchange scholarship endowment fund when the office can match the state funds with an equal amount of private cash donations, including conditional gifts.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20201[2011 1st sp.s. c 11 § 201]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2291.SL.pdf?cite=1996%20c%20253%20§%20407[1996 c 253 § 407]; ]

== 28B.109.080 - Scholarship recipients—Service obligation.
Each Washington international exchange scholarship recipient shall agree to complete the service obligation as defined by the office.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20202[2011 1st sp.s. c 11 § 202]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2291.SL.pdf?cite=1996%20c%20253%20§%20408[1996 c 253 § 408]; ]

