= 28B.137 - Religious reasonable accommodation.
:toc:

== 28B.137.010 - Reasonable accommodation for religious holidays.
. Postsecondary educational institutions must develop policies to accommodate student absences to allow students to take holidays for reasons of faith or conscience or for organized activities conducted under the auspices of a religious denomination, church, or religious organization, so that students' grades are not adversely impacted by the absences.

. The institution's policy must require faculty to reasonably accommodate students who, due to the observance of religious holidays, expect to be absent or endure a significant hardship during certain days of the course or program. "Reasonably accommodate" means coordinating with the student on scheduling examinations or other activities necessary for completion of the program and includes rescheduling examinations or activities or offering different times for examinations or activities.

. Any student seeking reasonable accommodations under this section must provide written notice to the faculty, within the first two weeks of the beginning of the course, of the specific dates the student requests accommodations regarding examinations or other activities.

. A postsecondary educational institution shall provide notice to students of its policy by publishing the policy on the institution's web site and including either the policy or a link to the policy in course or program syllabi. The notice to students must also include notification of the institution's grievance procedure.

. A postsecondary educational institution may not require a student to pay any fees for seeking reasonable accommodations under this section.

. For the purposes of this section, "postsecondary educational institution" means an institution of higher education as defined in RCW 28B.10.016, a degree-granting institution as defined in RCW 28B.85.010, a private vocational school as defined in RCW 28C.10.020, school as defined in RCW 18.16.020, and any entity offering academic credit for an apprenticeship program under RCW 49.04.150.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5166-S.SL.pdf?cite=2019%20c%20182%20ยง%201[2019 c 182 ยง 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5173-S.SL.pdf?cite=2014%20c%20168%20ยง%204[2014 c 168 ยง 4]; ]

