= 28B.102 - Educator conditional scholarship and repayment programs.
:toc:

== 28B.102.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Approved education program" means an education program in a common school as defined in RCW 28A.150.020.

. "Certificate" or "certificated" does not include a limited or conditioned certificate.

. "Certificated employee" has the definition in RCW 28A.150.203. "Certificated employee" does not include a paraeducator.

. "Conditional scholarship" means a loan that is forgiven in whole or in part in exchange for service as a certificated employee in an approved education program.

. "Eligible veteran or national guard member" means a Washington domiciliary who was an active or reserve member of the United States military or naval forces, or a national guard member called to active duty, who served in active federal service, under either Title 10 or Title 32 of the United States Code, in a war or conflict fought on foreign soil or in international waters or in another location in support of those serving on foreign soil or in international waters, and if discharged from service, has received an honorable discharge.

. "Forgiven" or "to forgive" or "forgiveness" means that all or part of a loan is canceled in exchange for service as a certificated employee in an approved education program.

. "Institution of higher education" or "institution" means a college or university in the state of Washington that is accredited by an accrediting association recognized as such by rule of the student achievement council.

. "Loan repayment" means a federal student loan that is repaid in whole or in part if the borrower serves as a certificated employee in an approved education program.

. "Office" means the office of student financial assistance.

. "Participant" means a person who has received a conditional scholarship or loan repayment under this chapter.

. "Public school" has the same meaning as in RCW 28A.150.010.

. "Shortage area" means an endorsement or geographic area as defined by the Washington professional educator standards board, in consultation with the office of the superintendent of public instruction, with a shortage of certificated employees. "Shortage area" must be defined biennially using quantitative and qualitative measures.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1139-S2.SL.pdf?cite=2019%20c%20295%20§%20211[2019 c 295 § 211]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20562[2012 c 229 § 562]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20176[2011 1st sp.s. c 11 § 176]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2708-S.SL.pdf?cite=2004%20c%2058%20§%202[2004 c 58 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2913.SL.pdf?cite=1996%20c%2053%20§%201[1996 c 53 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5982-S.SL.pdf?cite=1993%20sp.s.%20c%2018%20§%2036[1993 sp.s. c 18 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c437.pdf?cite=1987%20c%20437%20§%202[1987 c 437 § 2]; ]

== 28B.102.030 - Educator conditional scholarship and loan repayment programs—Powers and duties of student achievement council.
In administering educator conditional scholarship and loan repayment programs under this chapter, the student achievement council shall have the following powers and duties:

. Select persons to receive conditional scholarships or loan repayments;

. Adopt necessary rules and guidelines;

. Publicize the programs in collaboration with the office of the superintendent of public instruction and the Washington professional educator standards board;

. Collect and manage repayments from participants who do not meet their service obligations under this chapter; and

. Solicit and accept grants and donations from public and private sources for the programs.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1139-S2.SL.pdf?cite=2019%20c%20295%20§%20212[2019 c 295 § 212]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20563[2012 c 229 § 563]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20177[2011 1st sp.s. c 11 § 177]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2708-S.SL.pdf?cite=2004%20c%2058%20§%203[2004 c 58 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c437.pdf?cite=1987%20c%20437%20§%203[1987 c 437 § 3]; ]

== 28B.102.045 - Conditional scholarship program—Satisfactory progress required.
To receive additional disbursements under a conditional scholarship program authorized by this chapter, a participant must be considered by his or her Washington professional educator standards board-approved educator preparation program to be in a satisfactory progress condition.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1139-S2.SL.pdf?cite=2019%20c%20295%20§%20214[2019 c 295 § 214]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2708-S.SL.pdf?cite=2004%20c%2058%20§%205[2004 c 58 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c125.pdf?cite=1988%20c%20125%20§%207[1988 c 125 § 7]; ]

== 28B.102.055 - Loan repayment agreements.
. Upon documentation of federal student loan indebtedness, the office may enter into agreements with certificated teachers to repay all or part of a federal student loan in exchange for teaching service in a shortage area in an approved education program. Teachers eligible for loan repayment under this section must hold an endorsement in the content area in which they are assigned to teach during the period of repayment.

. The agreement shall specify the period of time it is in effect and detail the obligations of the office and the participant, including the amount to be paid to the participant. The ratio of loan repayment to years of teaching service for the loan repayment program must be the same as established for the conditional scholarship programs under RCW 28B.102.150. The agreement must also specify the shortage area of teaching service for which loan repayment will be provided.

. At the end of each school year, a participant under this section shall provide evidence to the office that the requisite teaching service has been provided. Upon receipt of the evidence, the office shall pay the participant the agreed-upon amount for one year of full-time teaching service or a prorated amount for less than full-time teaching service. To qualify for additional loan repayments, the participant must be engaged in continuous teaching service as defined by the office. The office may approve leaves of absence from continuous service and other deferments as may be necessary.

. The office may, at its discretion, arrange to make the loan repayment directly to the holder of the participant's federal student loan.

. The office may not reimburse a participant for loan repayments made before the participant entered into an agreement with the office under this section.

. The office's obligations to a participant under this section shall cease when:

.. The terms of the agreement have been fulfilled;

.. The participant is assigned to teach in a content area in which he or she is not endorsed;

.. The participant fails to maintain continuous teaching service as determined by the office; or

.. All of the participant's federal student loans have been repaid.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1139-S2.SL.pdf?cite=2019%20c%20295%20§%20222[2019 c 295 § 222]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20180[2011 1st sp.s. c 11 § 180]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2708-S.SL.pdf?cite=2004%20c%2058%20§%208[2004 c 58 § 8]; ]

== 28B.102.080 - Educator conditional scholarship account.
. The educator conditional scholarship account is created in the custody of the state treasurer. An appropriation is not required for expenditures of funds from the account. The account is not subject to allotment procedures under chapter 43.88 RCW except for moneys used for program administration.

. The office shall deposit in the account all moneys received for the educator conditional scholarship and loan repayment programs under this chapter. The account shall be self-sustaining and consist of funds appropriated by the legislature for the educator conditional scholarship and loan repayment programs under this chapter, private contributions to the programs, and receipts from participant repayments from the programs. Beginning July 1, 2004, the office shall also deposit into the account: (a) All funds from the institution of higher education loan account that are traceable to any conditional scholarship program for teachers or prospective teachers established by the legislature before June 10, 2004; and (b) all amounts repaid by participants under any such program.

. Expenditures from the account may be used only for the purposes of this chapter.

. Disbursements from the account may be made only on the authorization of the office.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1139-S2.SL.pdf?cite=2019%20c%20295%20§%20224[2019 c 295 § 224]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20182[2011 1st sp.s. c 11 § 182]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6444-S.SL.pdf?cite=2010%201st%20sp.s.%20c%2037%20§%20917[2010 1st sp.s. c 37 § 917]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1906-S2.SL.pdf?cite=2007%20c%20396%20§%209[2007 c 396 § 9]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2708-S.SL.pdf?cite=2004%20c%2058%20§%209[2004 c 58 § 9]; ]

== 28B.102.090 - Teacher shortage conditional scholarship program.
. The teacher shortage conditional scholarship program is created. The purpose of the program is to provide financial aid to encourage persons to become teachers and to retain these teachers in shortage areas.

. To qualify for the program an applicant must:

.. Be accepted into, and maintain enrollment in, a Washington professional educator standards board-approved teacher preparation program leading to an initial teacher certificate; and

.. Intend to pursue an initial teacher certificate with an endorsement in a shortage area.

. Participants are eligible to receive a teacher shortage conditional scholarship for up to four academic years.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1139-S2.SL.pdf?cite=2019%20c%20295%20§%20216[2019 c 295 § 216]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6455-S2.SL.pdf?cite=2016%20c%20233%20§%2015[2016 c 233 § 15]; ]

== 28B.102.100 - Maximization of awards.
. [Empty]
.. The office is directed to maximize the impact of conditional scholarships and loan repayments awarded under this chapter in light of shortage areas and in response to the trending financial needs of the applicant pool.

.. In maximizing the impact of the awards, the office may adjust the number and amounts of the conditional scholarships and loan repayments made each year. However, the maximum award authorized under this chapter is eight thousand dollars per person, per academic year. Beginning in the 2020-21 academic year, the office may adjust the maximum award by the average rate of resident undergraduate tuition and fee increases at the state universities as defined in RCW 28B.10.016.

. The allowable uses of a conditional scholarship under this chapter include the cost of attendance as determined by the office, such as tuition, room, board, and books.

. The award of a conditional scholarship under this chapter may not result in reduction of a participant's federal or other state financial aid.

. The office must make conditional scholarship and loan repayment awards from moneys in the educator conditional scholarship account created in RCW 28B.102.080.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1139-S2.SL.pdf?cite=2019%20c%20295%20§%20215[2019 c 295 § 215]; ]

== 28B.102.110 - Alternative route conditional scholarship program.
. The alternative route conditional scholarship program is created. The purpose of the program is to provide financial assistance to encourage persons to become teachers through alternative route teacher certification programs and to retain these teachers in shortage areas.

. To qualify for the program an applicant must:

.. Be accepted into, and maintain enrollment in, an alternative route teacher certification program under chapter 28A.660 RCW; and

.. Intend to pursue an initial teacher certificate with an endorsement in a shortage area.

. Participants are eligible to receive an alternative route conditional scholarship for up to two academic years.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1139-S2.SL.pdf?cite=2019%20c%20295%20§%20217[2019 c 295 § 217]; ]

== 28B.102.120 - Pipeline for paraeducators conditional scholarship program.
. The pipeline for paraeducators conditional scholarship program is created. The purpose of the program is to support paraeducators who wish to become teachers by providing financial aid for the completion of an associate of arts degree.

. To qualify for the program an applicant must:

.. Not have earned a college degree;

.. Provide documentation:

... From his or her school district or building of one year of successful student interaction and leadership as a classified instructional employee; or

... Of his or her completion of two years of a recruiting Washington teachers program, established under RCW 28A.415.370;

.. Intend to pursue an initial teacher certificate with an endorsement in a shortage area via a Washington professional educator standards board-approved teacher preparation program; and

.. Be accepted into, and maintain enrollment for no more than the equivalent of four full-time academic years at, a community and technical college under RCW 28B.50.020.

. Participants are eligible to receive a pipeline for paraeducators conditional scholarship for up to four academic years.

. The office must prioritize applicants in the following order:

.. Applicants recruited and supported by their school districts to become teachers;

.. Applicants who completed two years of a recruiting Washington teachers program, established under RCW 28A.415.370; and

.. Applicants intending to complete an associate of arts degree in two academic years or less.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1139-S2.SL.pdf?cite=2019%20c%20295%20§%20218[2019 c 295 § 218]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1115-S.SL.pdf?cite=2017%20c%20237%20§%2019[2017 c 237 § 19]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1906-S2.SL.pdf?cite=2007%20c%20396%20§%206[2007 c 396 § 6]; ]

== 28B.102.130 - Educator retooling conditional scholarship program.
. The educator retooling conditional scholarship program is created. The purpose of the program is to increase the number of public school teachers with endorsements in shortage areas.

. To qualify for the program an applicant must:

.. Hold a current Washington teacher certificate or an expired Washington teacher certificate issued after 2005;

.. Pursue an additional endorsement in a shortage area; and

.. Use one of the Washington professional educator standards board's pathways to complete the additional endorsement requirements in the equivalent of one full-time academic year.

. Participants are eligible to receive an educator retooling conditional scholarship for up to two academic years.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1139-S2.SL.pdf?cite=2019%20c%20295%20§%20219[2019 c 295 § 219]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1570-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%209%20§%201[2015 3rd sp.s. c 9 § 1]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1813-S.SL.pdf?cite=2015%201st%20sp.s.%20c%203%20§%203[2015 1st sp.s. c 3 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1906-S2.SL.pdf?cite=2007%20c%20396%20§%207[2007 c 396 § 7]; ]

== 28B.102.140 - Career and technical education conditional scholarship program.
. The career and technical education conditional scholarship program is created. The purpose of the program is to provide financial aid for nonteachers and teachers to obtain necessary certificates and endorsements through any approved route to become career and technical education teachers.

. To qualify for the program, an applicant must be:

.. Accepted into, and maintain enrollment in, a Washington professional educator standards board-approved teacher preparation program; and

.. Pursuing the necessary certificates and endorsements to teach career and technical education courses.

. The office must give priority to applicants who:

.. Possess a professional license and occupational industry experience applicable to the career and technical education endorsement being pursued; or

.. Are accepted into an alternative route teacher certification program under RCW 28A.660.020.

. Participants are eligible to receive a career and technical education conditional scholarship for up to two academic years.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1139-S2.SL.pdf?cite=2019%20c%20295%20§%20220[2019 c 295 § 220]; ]

== 28B.102.150 - Conditional scholarships—Forgiveness and repayment.
. [Empty]
.. A conditional scholarship awarded under this chapter is forgiven when the participant fulfills the terms of his or her service obligation. The office shall develop the service obligation terms for each conditional scholarship program under this chapter, including that participants must either:

... Serve as a certificated employee in an approved education program for two full-time school years for each year of conditional scholarship received; or

... Serve as a certificated employee in a shortage area in an approved education program for one full-time school year for each year of conditional scholarship received.

.. For participants who meet the terms of their service obligation, the office shall forgive the conditional scholarships according to the service obligation terms and shall maintain all necessary records of such forgiveness.

. [Empty]
.. Participants who do not fulfill their service obligation as required under subsection (1) of this section incur an obligation to repay the conditional scholarship award, with interest and other fees. The office shall develop repayment terms for each conditional scholarship program under this chapter, including interest rate, other fees, minimum payment, and maximum repayment period.

.. The office shall collect repayments from participants who do not fulfill their service obligation as required under subsection (1) of this section. Collection and servicing of repayments under this section must be pursued using the full extent of the law, including wage garnishment if necessary. The office shall exercise due diligence in maintaining all necessary records to ensure that maximum repayments are collected.

. The office shall establish a process for forgiveness, deferment, or forbearance for participants who fail to complete their service obligation due to circumstances beyond the participants' control, for example certain medical conditions, military deployment, declassification of a participant's shortage area, or hardship for a participant to relocate to an approved education program with a shortage area, provided the participant was serving as a certificated employee in a shortage area in an approved education program.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1139-S2.SL.pdf?cite=2019%20c%20295%20§%20221[2019 c 295 § 221]; ]

== 28B.102.160 - Educator conditional scholarship and loan repayment programs—Report.
Beginning November 1, 2020, and by November 1st each even-numbered year thereafter, the office shall submit a report, in accordance with RCW 43.01.036, to the appropriate committees of the legislature recommending whether the educator conditional scholarship and loan repayment programs under this chapter should be continued, modified, or terminated. The report must include information about the number of applicants for, and participants in, each program. To the extent possible, this information should be disaggregated by age, gender, race and ethnicity, family income, and unmet financial need. The report must include information about participant deferments and repayments. The report must also include information on moneys received by and disbursed from the educator conditional scholarship account under RCW 28B.102.080 each fiscal year.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1139-S2.SL.pdf?cite=2019%20c%20295%20§%20223[2019 c 295 § 223]; ]

== 28B.102.170 - Application—Conditional scholarship and loan repayment agreements.
Nothing in RCW 28B.102.020, 28B.102.030, 28B.102.045, 28B.102.055, 28B.102.080 through 28B.102.160, 43.79A.040, or sections 210 and 226, chapter 295, Laws of 2019 modifies or otherwise affects conditional scholarship or loan repayment agreements under this chapter or chapter 28A.660 RCW existing before May 8, 2019.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1139-S2.SL.pdf?cite=2019%20c%20295%20§%20229[2019 c 295 § 229]; ]

