= 28B.123 - Certified public accounting scholarship program.
:toc:

== 28B.123.010 - Certified public accounting scholarship program—Established—Purpose—Awards—Limitation.
. The certified public accounting scholarship program is established.

. The purpose of this scholarship program is to increase the number of students pursuing the certified public accounting license in Washington state.

. Scholarships shall be awarded to eligible students based on merit and without regard to age, gender, race, creed, religion, ethnic or national origin, or sexual orientation. In the selection process, the foundation is encouraged to consider the level of financial need demonstrated by applicants who otherwise meet merit-based scholarship criteria.

. Scholarships shall be awarded every year not to exceed the net balance of the foundation's scholarship award account. 

. Scholarships shall be awarded to eligible students for one year. Qualified applicants may reapply in subsequent years.

. Scholarships awarded to program participants shall be paid directly to the Washington-based college or university where the program participant is enrolled.

. A scholarship award for any program participant shall not exceed the cost of tuition and fees assessed by the college or university on that individual program participant for the academic year of the award.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5534-S.SL.pdf?cite=2015%20c%20215%20§%201[2015 c 215 § 1]; ]

== 28B.123.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Board" means the board of accountancy created in RCW 18.04.035.

. "Eligible student" means a student enrolled at an accredited Washington-based college or university with a declared major in accounting, entering his or her junior year or higher. "Eligible student" includes community college transfer students, residents of Washington pursuing an online degree in accounting, and students pursuing a masters in tax, masters in accounting, or a PhD in accounting.

. "Foundation" means the Washington CPA foundation.

. "Program" means the certificated public accounting scholarship program created in this chapter.

. "Program participant" means an eligible student who is awarded a scholarship under the program.

. "Resident student" has the definition in RCW 28B.15.012.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5534-S.SL.pdf?cite=2015%20c%20215%20§%202[2015 c 215 § 2]; ]

== 28B.123.030 - Role of a foundation under contract with the board.
The board must contract with a foundation to develop and administer the program. The board shall provide oversight and guidance for the program in light of established legislative priorities and to fulfill the duties and responsibilities under this chapter and chapter 18.04 RCW, including determining eligible education programs for purposes of the program. The board shall negotiate a reasonable administrative fee for the services provided by the foundation. In addition to its contractual obligations with the board, the foundation has the duties and responsibilities to:

. Establish a separate scholarship award account to receive state funds and from which to disburse scholarship awards;

. Manage and invest funds in the separate scholarship award account to maximize returns at a prudent level of risk and to maintain books and records of the account for examination by the board as it deems necessary or appropriate;

. In consultation with the board, make an assessment of the reasonable annual eligible expenses associated with eligible education programs identified by the board;

. Work with [the] board, institutions of higher education, the student achievement council, and other organizations to promote and publicize the program to obtain a wide and diverse group of applicants;

. Develop and implement an application, selection, and notification process for awarding certified public accounting scholarships;

. Determine the annual amount of the certified public accounting scholarship for each program participant;

. Distribute scholarship awards to colleges and universities for program participants; and

. Notify the student achievement council and colleges and universities of enrolled program participants and inform them of the terms and conditions of the scholarship award.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5534-S.SL.pdf?cite=2015%20c%20215%20§%203[2015 c 215 § 3]; ]

== 28B.123.040 - Foundation's report to the board.
By January 1, 2016, and annually each January 1st thereafter, the foundation contracted with under RCW 28B.123.030 shall report to the board regarding the program, including:

. An accounting of receipts and disbursements of the foundation's separate scholarship award account including any realized or unrealized gains or losses and the resulting change in account balance;

. A list of the program participants and the scholarship amount awarded, by year; and

. Other outcome measures necessary for the board to assess the impacts of the program.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5534-S.SL.pdf?cite=2015%20c%20215%20§%204[2015 c 215 § 4]; ]

== 28B.123.050 - Certified public accounting scholarship transfer account.
. The certified public accounting scholarship transfer account is created in the custody of the state treasurer. Expenditures from the account may be used solely for scholarships and the administration of the program created in RCW 28B.123.010.

. Revenues to the account shall consist of appropriations by the legislature and any gifts, grants, or donations received by the board for this purpose.

. Only the director of the board or the director's designee may authorize expenditures from the certified public accounting scholarship transfer account. The account is not subject to the allotment procedures under chapter 43.88 RCW and an appropriation is not required for expenditures.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5534-S.SL.pdf?cite=2015%20c%20215%20§%205[2015 c 215 § 5]; ]

