= 28B.14H - Washington's future bond issue.
:toc:

== 28B.14H.005 - Intent.
The state's institutions of higher education are a vital component of the future economic prosperity of our state. In order to ensure that Washington continues to be able to provide a highly qualified workforce that can attract businesses and support the economic vitality of the state, it is the intent of chapter 18, Laws of 2003 1st sp. sess. to provide new money for capital projects to help fulfill higher education needs across the state.

This new source of funding for the critical capital needs of the state's institutions of higher education furthers the mission of higher education and is intended to enhance the abilities of those institutions, over the next six years, to fulfill their critical roles in maintaining and stimulating the state's economy.

It is the intent of the legislature that this new source of funding not displace funding levels for the capital and operating budgets of the institutions of higher education. It is instead intended that the new funding will allow the institutions, over the next three biennia, to use the current level of capital funding to provide for many of those urgent preservation, replacement, and maintenance needs that have been deferred. This approach is designed to maintain or improve the current infrastructure of our institutions of higher education, and simultaneously to provide new instruction and research capacity to serve the increasing number of traditional college-aged students and those adults returning to college to update skills or retrain so that they can meet the demands of Washington's changing workforce. This new source of funding may also be used for major preservation projects that renovate, replace, or modernize facilities to enhance capacity/access by maintaining or improving the usefulness of existing space for important instruction and research programs.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5908-S.SL.pdf?cite=2003%201st%20sp.s.%20c%2018%20§%202[2003 1st sp.s. c 18 § 2]; ]

== 28B.14H.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Bonds" means bonds, notes, commercial paper, certificates of indebtedness, or other evidences of indebtedness of the state issued under this chapter.

. "Institutions of higher education" means the University of Washington and Washington State University, Western Washington University at Bellingham, Central Washington University at Ellensburg, Eastern Washington University at Cheney, The Evergreen State College, and the community colleges and technical colleges as defined by RCW 28B.50.030.

. "Washington's future bonds" means all or any portion of the general obligation bonds authorized in RCW 28B.14H.020.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5908-S.SL.pdf?cite=2003%201st%20sp.s.%20c%2018%20§%203[2003 1st sp.s. c 18 § 3]; ]

== 28B.14H.020 - Washington's future bonds authorized.
. For the purpose of providing needed capital improvements consisting of the predesign, design, acquisition, construction, modification, renovation, expansion, equipping, and other improvement of state buildings and facilities for the institutions of higher education, the state finance committee is authorized to issue general obligation bonds of the state of Washington in the sum of seven hundred seventy-two million five hundred thousand dollars, or so much thereof as may be required, to finance all or a part of the cost of these projects and all costs incidental thereto. The bonds issued under the authority of this section shall be known as Washington's future bonds.

. Bonds authorized in this section shall be sold in the manner, at the time or times, in amounts, and at such prices as the state finance committee shall determine.

. No bonds authorized in this section may be offered for sale without prior legislative appropriation of the net proceeds of the sale of the bonds.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5908-S.SL.pdf?cite=2003%201st%20sp.s.%20c%2018%20§%204[2003 1st sp.s. c 18 § 4]; ]

== 28B.14H.030 - Bond issuance—Intent.
It is the intent of the legislature that the proceeds of new bonds authorized in this chapter will be appropriated in phases over three biennia, beginning with the 2003-2005 biennium, to provide additional funding for capital projects and facilities of the institutions of higher education above historical levels of funding.

This chapter is not intended to limit the legislature's ability to appropriate bond proceeds if the full amount authorized in this chapter has not been appropriated after three biennia, and the authorization to issue bonds contained in this chapter does not expire until the full authorization has been appropriated and issued.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5908-S.SL.pdf?cite=2003%201st%20sp.s.%20c%2018%20§%205[2003 1st sp.s. c 18 § 5]; ]

== 28B.14H.040 - Terms and covenants.
. The state finance committee is authorized to prescribe the form, terms, conditions, and covenants of the bonds provided for in this chapter, the time or times of sale of all or any portion of them, and the conditions and manner of their sale and issuance.

. Bonds issued under this chapter shall state that they are a general obligation of the state of Washington, shall pledge the full faith and credit of the state to the payment of the principal thereof and the interest thereon, and shall contain an unconditional promise to pay the principal and interest as the same shall become due.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5908-S.SL.pdf?cite=2003%201st%20sp.s.%20c%2018%20§%206[2003 1st sp.s. c 18 § 6]; ]

== 28B.14H.050 - Proceeds.
. [Empty]
.. The proceeds from the sale of the bonds authorized in RCW 28B.14H.020 shall be deposited in the Gardner-Evans higher education construction account created in RCW 28B.14H.110.

.. If the state finance committee deems it necessary to issue the bonds authorized in RCW 28B.14H.020 as taxable bonds in order to comply with federal internal revenue service rules and regulations pertaining to the use of nontaxable bond proceeds, the proceeds of such taxable bonds shall be deposited to the state taxable building construction account in lieu of any deposit otherwise provided by this section. The state treasurer shall submit written notice to the director of financial management if it is determined that any such deposit to the state taxable building construction account is necessary. Moneys in the account may be spent only after appropriation.

. The proceeds shall be used exclusively for the purposes in RCW 28B.14H.020 and for the payment of the expenses incurred in connection with the sale and issuance of the bonds.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2299-S.SL.pdf?cite=2005%20c%20487%20§%206[2005 c 487 § 6]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5908-S.SL.pdf?cite=2003%201st%20sp.s.%20c%2018%20§%207[2003 1st sp.s. c 18 § 7]; ]

== 28B.14H.060 - Projects for the 2005-07 and 2007-09 biennia—Intent.
The legislature intends to use the proceeds from the sale of bonds issued under this chapter for the following projects during the 2005-07 and 2007-09 biennia:

. For the University of Washington:

.. Life sciences I building;

.. Bothell branch campus phase 2B;

. For Washington State University:

.. Spokane Riverpoint campus - academic center building;

.. Pullman campus - Holland Library renovation;

.. Pullman campus - biotechnology/life sciences 1;

.. Tri-Cities campus - bioproducts and sciences building; and

.. Intercollegiate College of Nursing, Spokane - nursing building at Riverpoint;

. For Eastern Washington University: Hargreaves Hall;

. For Central Washington University: Hogue technology;

. For The Evergreen State College:

.. Daniel J. Evans building;

.. Communications building and theater expansion;

. For Western Washington University:

.. Academic instructional center;

.. Parks Hall;

.. Performing Arts Center renovation;

. For the community and technical college system:

.. Green River Community College science building;

.. Walla Walla Community College basic skills/computer lab;

.. Pierce College Puyallup, communication arts and allied health; or

. For other projects that maintain or increase access to institutions of higher education.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5908-S.SL.pdf?cite=2003%201st%20sp.s.%20c%2018%20§%208[2003 1st sp.s. c 18 § 8]; ]

== 28B.14H.070 - Payment procedures.
. The debt-limit general fund bond retirement account shall be used for the payment of the principal of and interest on the bonds authorized in this chapter.

. The state finance committee shall, on or before June 30th of each year, certify to the state treasurer the amount needed in the ensuing twelve months to meet the bond retirement and interest requirements on the bonds authorized in this chapter.

. On each date on which any interest or principal and interest payment is due on bonds issued under this chapter, the state treasurer shall withdraw from any general state revenues received in the state treasury and deposit in the debt-limit general fund bond retirement account an amount equal to the amount certified by the state finance committee to be due on the payment date.

. The owner and holder of each of the bonds or the trustee for the owner and holder of any of the bonds may by mandamus or other appropriate proceeding require the transfer and payment of funds as directed in this section.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5908-S.SL.pdf?cite=2003%201st%20sp.s.%20c%2018%20§%209[2003 1st sp.s. c 18 § 9]; ]

== 28B.14H.080 - Bonds—Legal investment for public funds.
The bonds authorized by this chapter shall constitute a legal investment for all state funds or for funds under state control and all funds of municipal corporations.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5908-S.SL.pdf?cite=2003%201st%20sp.s.%20c%2018%20§%2010[2003 1st sp.s. c 18 § 10]; ]

== 28B.14H.090 - Additional methods of paying debt service authorized.
The legislature may provide additional means for raising moneys for the payment of the principal of and interest on the bonds authorized under this chapter, and RCW 28B.14H.070 shall not be deemed to provide an exclusive method for payment.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5908-S.SL.pdf?cite=2003%201st%20sp.s.%20c%2018%20§%2011[2003 1st sp.s. c 18 § 11]; ]

== 28B.14H.100 - Chapter supplemental.
This chapter provides a complete, additional, and alternative method for accomplishing the purposes of this chapter and is supplemental and additional to powers conferred by other laws. The issuance of bonds under this chapter shall not be deemed to be the only method to fund projects under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5908-S.SL.pdf?cite=2003%201st%20sp.s.%20c%2018%20§%2012[2003 1st sp.s. c 18 § 12]; ]

== 28B.14H.110 - Creation of the Gardner-Evans higher education construction account.
The Gardner-Evans higher education construction account is created in the state treasury. Proceeds from the bonds issued under RCW 28B.14H.020 shall be deposited in the account. The account shall be used for purposes of RCW 28B.14H.020. Moneys in the account may be spent only after appropriation.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5908-S.SL.pdf?cite=2003%201st%20sp.s.%20c%2018%20§%2013[2003 1st sp.s. c 18 § 13]; ]

== 28B.14H.120 - Expiration of authority to issue bonds.
If any bonds authorized in this chapter have not been issued by June 30, 2018, the authority of the state finance committee to issue such remaining unissued bonds expires June 30, 2018.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1080-S2.SL.pdf?cite=2018%20c%203%20§%20304[2018 c 3 § 304]; ]

== 28B.14H.901 - Short title.
This act shall be known as the building Washington's future act.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5908-S.SL.pdf?cite=2003%201st%20sp.s.%20c%2018%20§%201[2003 1st sp.s. c 18 § 1]; ]

