= 28B.117 - Passport to careers program.
:toc:

== 28B.117.005 - Findings—Intent.
. [Empty]
.. The legislature finds that with the creation of the passport to college promise program this state took a significant step toward providing higher education opportunities to youth and alumni of foster care. The passport to college promise program not only provides financial aid to former foster youth but, just as important, it recognizes the critical role of wraparound services and provides early outreach to foster care youth regarding postsecondary higher educational opportunities. Since 2007, the passport to college promise program has increased the number of former foster youth enrolling in higher education and working toward college degrees.

.. Recognizing the success of creating pathways for foster youth to access higher education, the legislature now seeks to create an additional postsecondary pathway through access to registered apprenticeships or recognized preapprenticeships. Former foster and unaccompanied homeless youth face critical hurdles to accessing registered apprenticeships and recognized preapprenticeships. The first is a lack of information regarding preparation for and enrolling in registered apprenticeships or recognized preapprenticeships. The second is finding the financial resources to begin and continue in an apprenticeship or preapprenticeship. As a result of the unique hurdles and challenges that face youth in and alumni of foster care and unaccompanied homeless and former homeless youth, a disproportionate number of them are part of society's large group of marginalized youth.

.. The legislature reiterates its earlier recognition of the critical role education plays in improving outcomes for youth in and alumni of foster care and unaccompanied homeless and former homeless youth, as well as the key role played by wraparound services in providing continuity and seamless transitions to postsecondary credential programs. With the creation of a parallel pathway with a passport for registered apprenticeships or recognized preapprenticeships, including for the provision of wraparound services, the legislature strives to make Washington the leader in the nation with respect to foster and unaccompanied homeless youth graduating from high school and enrolling in and achieving a postsecondary credential.

.. The legislature further finds that students experiencing homelessness face similar challenges and educational outcomes as their peers in foster care. In 2016, fifty-three and two-fifths percent of Washington youth experiencing homelessness graduated from high school on time, compared to seventy-nine percent of their peers. Students experiencing homelessness are more likely to be students of color, chronically absent, and have lower test scores in reading and math. Homeless students may also be former foster youth and foster youth may be formerly homeless students. Similar to youth in foster care, students experiencing homelessness need opportunities for financial aid, wraparound services, and early outreach regarding postsecondary higher educational opportunities and apprenticeships.

. It is the intent of the legislature to create the passport to careers program with two programmatic pathways: The passport to college promise program and the passport to apprenticeship opportunities. The passport to careers program expands upon the passport to college promise program created in 2007 to include a program of financial assistance for eligible youth and young adults to participate in apprenticeship or preapprenticeship programs called the passport to apprenticeship opportunities program. The passport to careers program will have three primary components:

.. Outreach to foster and unaccompanied homeless youth and young adults regarding the higher education and registered apprenticeship opportunities available to them, how to apply, and how to apply for and obtain financial aid;

.. Provide financial support to former foster and unaccompanied homeless youth to assist with the costs of their public undergraduate college education or provide financial assistance to meet apprenticeship or preapprenticeship program minimum qualifications and occupational-specific costs and the supportive services to help them apply and complete a registered apprenticeship or recognized preapprenticeship; and

.. Measurably increase the number of foster and homeless youth accessing and completing higher education or registered apprenticeship programs and successfully entering and retaining employment.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6274-S2.SL.pdf?cite=2018%20c%20232%20§%201[2018 c 232 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1686-S.SL.pdf?cite=2013%20c%2039%20§%2011[2013 c 39 § 11]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1131-S.SL.pdf?cite=2007%20c%20314%20§%201[2007 c 314 § 1]; ]

== 28B.117.010 - Program created—Purpose.
The passport to careers program is created. The purpose of the program is:

. To encourage current and former foster care youth and unaccompanied youth experiencing homelessness to prepare for, enroll in, and successfully complete higher education or a registered apprenticeship or preapprenticeship program;

. To improve the high school graduation outcomes of foster youth and unaccompanied youth experiencing homelessness through coordinated P-20 and child welfare outreach, intervention, and planning; and

. To improve postsecondary outcomes by providing current and former foster care youth and unaccompanied youth who have experienced homelessness with the educational planning, information, institutional support, and direct financial resources necessary for them to succeed in either higher education or a registered apprenticeship or preapprenticeship program.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6274-S2.SL.pdf?cite=2018%20c%20232%20§%202[2018 c 232 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2254-S.SL.pdf?cite=2012%20c%20163%20§%202[2012 c 163 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1131-S.SL.pdf?cite=2007%20c%20314%20§%203[2007 c 314 § 3]; ]

== 28B.117.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Apprentice" means a person enrolled in a state-approved, federally registered, or reciprocally recognized apprenticeship program.

. "Apprenticeship" means an apprenticeship training program approved or recognized by the state apprenticeship council or similar federal entity.

. "Cost of attendance" means the cost associated with attending a particular institution of higher education as determined by the office, including but not limited to tuition, fees, room, board, books, personal expenses, and transportation, plus the cost of reasonable additional expenses incurred by an eligible student and approved by a financial aid administrator at the student's school of attendance.

. "Federal foster care system" means the foster care program under the federal unaccompanied refugee minors program, Title 8 U.S.C. Sec. 1522 of the immigration and nationality act.

. "Financial need" means the difference between a student's cost of attendance and the student's total family contribution as determined by the method prescribed by the United States department of education.

. "Homeless" or "homelessness" means without a fixed, regular, and adequate nighttime residence as set forth in the federal McKinney-Vento homeless assistance act, 42 U.S.C. Sec. 11301 et seq.

. "Independent college or university" means a private, nonprofit institution of higher education, open to residents of the state, providing programs of education beyond the high school level leading to at least the baccalaureate degree, and accredited by the Northwest association of schools and colleges, and other institutions as may be developed that are approved by the student achievement council as meeting equivalent standards as those institutions accredited under this section.

. "Institution of higher education" means any institution eligible to and participating in the Washington college grant program.

. "Occupational-specific costs" means the costs associated with entering an apprenticeship or preapprenticeship, including but not limited to fees, tuition for classes, work clothes, rain gear, boots, occupation-specific tools.

. "Office" means the office of student financial assistance.

. "Preapprenticeship" means an apprenticeship preparation program recognized by the state apprenticeship council and as defined in RCW 28C.18.162.

. "Program" means the passport to careers program created in this chapter.

. "State foster care system" means out-of-home care pursuant to a dependency and includes the placement of dependents from other states who are placed in Washington pursuant to orders issued under the interstate compact on the placement of children, chapter 26.34 RCW.

. "Tribal court" has the same meaning as defined in RCW 13.38.040.

. "Tribal foster care system" means an out-of-home placement under a dependency order from a tribal court.

. "Unaccompanied" means a youth or young adult experiencing homelessness while not in the physical custody of a parent or guardian.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2158-S2.SL.pdf?cite=2019%20c%20406%20§%2043[2019 c 406 § 43]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6274-S2.SL.pdf?cite=2018%20c%20232%20§%203[2018 c 232 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2254-S.SL.pdf?cite=2012%20c%20163%20§%203[2012 c 163 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20220[2011 1st sp.s. c 11 § 220]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1131-S.SL.pdf?cite=2007%20c%20314%20§%202[2007 c 314 § 2]; ]

== 28B.117.030 - Program design and implementation—Passport to college promise and passport to apprenticeship opportunities—Student eligibility.
. The office shall design and, to the extent funds are appropriated for this purpose, implement, passport to careers with two programmatic pathways: The passport to college promise program and the passport to apprenticeship opportunities program. Both programs offer supplemental scholarship and student assistance for students who were under the care of the state foster care system, tribal foster care system, or federal foster care system, and verified unaccompanied youth or young adults who have experienced homelessness.

. The office shall convene and consult with an advisory committee to assist with program design and implementation. The committee shall include but not be limited to former foster care and unaccompanied homeless youth and their advocates; representatives from the state board for community and technical colleges, public and private agencies that assist current and former foster care recipients and unaccompanied youth or young adults experiencing homelessness in their transition to adulthood; student support specialists from public and private colleges and universities; the state workforce training and education coordinating board; the employment security department; and the state apprenticeship council.

. To the extent that sufficient funds have been appropriated for this purpose, a student is eligible for assistance under this section if he or she:

.. [Empty]
... Was in the care of the state foster care system, tribal foster care system, or federal foster care system in Washington state at any time before age twenty-one subsequent to the following:

(A) Age fifteen as of July 1, 2018;

(B) Age fourteen as of July 1, 2019; and

(C) Age thirteen as of July 1, 2020; or

... Beginning July 1, 2019, was verified on or after July 1st of the prior academic year as an unaccompanied youth experiencing homelessness, before age twenty-one;

.. Is a resident student, as defined in RCW 28B.15.012(2), or if unable to establish residency because of homelessness or placement in out-of-state foster care under the interstate compact for the placement of children, has residency determined through verification by the office;

.. Is enrolled with or will enroll on at least a half-time basis with an institution of higher education or a registered apprenticeship or recognized preapprenticeship in Washington state by the age of twenty-one;

.. Is making satisfactory academic progress toward the completion of a degree, certificate program, or registered apprenticeship or recognized preapprenticeship, if receiving supplemental scholarship assistance;

.. Has not earned a bachelor's or professional degree; and

.. Is not pursuing a degree in theology.

. The office shall define a process for verifying unaccompanied homeless status for determining eligibility under subsection (3)(a)(ii) of this section. The office may use a letter from the following persons or entities to provide verification: A high school or school district McKinney-Vento liaison; the director or designated staff member of an emergency shelter, transitional housing program, or homeless youth drop-in center; or other similar professional case manager or school employee. Students who have no formal connection with such a professional may also submit to the office an essay that describes their experience with homelessness and the barriers it created to their academic progress. The office may consider this essay in lieu of a letter of homelessness determination and may interview the student if further information is needed to verify eligibility.

. A passport to college promise program is created.

.. A passport to college promise scholarship under this section:

... Shall not exceed resident undergraduate tuition and fees at the highest-priced public institution of higher education in the state; and

... Shall not exceed the student's financial need, when combined with all other public and private grant, scholarship, and waiver assistance the student receives.

.. An eligible student may receive a passport to college promise scholarship under this section for a maximum of five years after the student first enrolls with an institution of higher education or until the student turns age twenty-six, whichever occurs first. If a student turns age twenty-six during an academic year, and would otherwise be eligible for a scholarship under this section, the student shall continue to be eligible for a scholarship for the remainder of the academic year.

.. The office, in consultation with and with assistance from the state board for community and technical colleges, shall perform an annual analysis to verify that those institutions of higher education at which students have received a scholarship under this section have awarded the student all available need-based and merit-based grant and scholarship aid for which the student qualifies.

.. In designing and implementing the passport to college promise student support program under this section, the office, in consultation with and with assistance from the state board for community and technical colleges, shall ensure that a participating college or university:

... Has a viable plan for identifying students eligible for assistance under this section, for tracking and enhancing their academic progress, for addressing their unique needs for assistance during school vacations and academic interims, and for linking them to appropriate sources of assistance in their transition to adulthood;

... Receives financial and other incentives for achieving measurable progress in the recruitment, retention, and graduation of eligible students.

.. To the extent funds are appropriated for this specific purpose, the office shall contract with at least one nongovernmental entity to provide services to support effective program implementation, resulting in increased postsecondary completion rates for passport scholars.

. The passport to apprenticeship opportunities program is created. The office shall:

.. Identify students and applicants who are eligible for services under RCW 28B.117.030 through coordination of certain agencies as detailed in RCW 28B.117.040;

.. Provide financial assistance through the nongovernmental entity or entities in RCW 28B.117.055 for registered apprenticeship and recognized preapprenticeship entrance requirements and occupational-specific costs that does not exceed the individual's financial need; and

.. Extend financial assistance to any eligible applicant for a maximum of six years after first enrolling with a registered apprenticeship or recognized preapprenticeship, or until the applicant turns twenty-six, whichever occurs first.

. Recipients may utilize passport to college promise or passport to apprenticeship opportunities at different times, but not concurrently. The total award an individual may receive in any combination of the programs shall not exceed the equivalent amount that would have been awarded for the individual to attend a public university for five years with the highest annual tuition and state-mandated fees in the state.

. Personally identifiable information shared pursuant to this section retains its confidentiality and may not be further disclosed except as allowed under state and federal law.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5955-S.SL.pdf?cite=2019%20c%20470%20§%2023[2019 c 470 § 23]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6274-S2.SL.pdf?cite=2018%20c%20232%20§%204[2018 c 232 § 4]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1566-S2.SL.pdf?cite=2013%20c%20182%20§%208[2013 c 182 § 8]; 2012 c 229 § 609; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20221[2011 1st sp.s. c 11 § 221]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1131-S.SL.pdf?cite=2007%20c%20314%20§%204[2007 c 314 § 4]; ]

== 28B.117.040 - Identification of eligible students and applicants—Duties of institutions of higher education, the department of social and health services, and the department of children, youth, and families.
Effective operation of the passport to careers program requires early and accurate identification of former foster care youth and unaccompanied youth experiencing homelessness so that they can be linked to the financial and other assistance that will help them succeed in college or in a registered apprenticeship or recognized preapprenticeship. To that end:

. All institutions of higher education that receive funding for student support services under RCW 28B.117.030 shall include on their applications for admission or on their registration materials a question asking whether the applicant has been in state, tribal, or federal foster care in Washington state or experienced unaccompanied homelessness under the parameters in RCW 28B.117.030(3)(a), as determined by the office, with an explanation that financial and support services may be available. All other institutions of higher education are strongly encouraged to include such a question and explanation. No institution may consider whether an applicant may be eligible for a scholarship or student support services under this chapter when deciding whether the applicant will be granted admission.

. With substantial input from the office of the superintendent of public instruction, the department of social and health services and the department of children, youth, and families shall devise and implement procedures for efficiently, promptly, and accurately identifying students and applicants who are eligible for services under RCW 28B.117.030, and for sharing that information with the office, the institutions of higher education, and the nongovernmental entity or entities identified in RCW 28B.77.250, 28B.117.030(5)(e), and 28B.117.055. The procedures shall include appropriate safeguards for consent by the applicant or student before disclosure. This information retains its confidentiality under chapter 13.50 RCW and federal law and may not be further disclosed except as allowed under state and federal law.

. Nothing in this chapter allows the sharing of confidential information that is prohibited by state or federal law.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5955-S.SL.pdf?cite=2019%20c%20470%20§%2024[2019 c 470 § 24]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1091-S.SL.pdf?cite=2019%20c%2064%20§%205[2019 c 64 § 5]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6274-S2.SL.pdf?cite=2018%20c%20232%20§%205[2018 c 232 § 5]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2254-S.SL.pdf?cite=2012%20c%20163%20§%204[2012 c 163 § 4]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20222[2011 1st sp.s. c 11 § 222]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1131-S.SL.pdf?cite=2007%20c%20314%20§%205[2007 c 314 § 5]; ]

== 28B.117.050 - Internet website and outreach program.
. To the extent funds are appropriated for this purpose, the office shall develop and maintain an internet website and outreach program to serve as a comprehensive portal for foster care youth and unaccompanied youth or young adults who have experienced homelessness in Washington state to obtain information regarding higher education and registered apprenticeship and recognized preapprenticeship programs. In developing the website and conducting the outreach program, the office shall get input from community and technical colleges; the foster care partnership; institutions of higher education; the employment security department; the state apprenticeship and training council; the workforce training and education coordinating board; department of commerce office of homeless youth prevention and protection programs; department of children, youth, and families; the department of licensing; and the department of labor and industries. The outreach program and website shall include, but not be limited to:

.. Academic, social, family, financial, and logistical information important to successful postsecondary educational success;

.. How and when to obtain and complete college applications;

.. How and when to apply for a registered apprenticeship or preapprenticeship program;

.. What academic subject matter prerequisites, if any, are generally required for acceptance to an institute of higher education, a registered apprenticeship, or a preapprenticeship program;

.. What college placement tests, if any, are generally required for admission to college and when and how to register for such tests;

.. How and when to obtain and complete a federal free application for federal student aid (FAFSA) or if ineligible to apply for the FAFSA, the state financial aid application approved by the office; and

.. Detailed sources of financial aid and assistance likely available to eligible former foster care and unaccompanied homeless youth, including the financial aid and assistance provided by this chapter.

. The office shall determine whether to design, build, and operate such program and website directly or to use, support, and modify existing websites created by government or nongovernmental entities for a similar purpose.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6274-S2.SL.pdf?cite=2018%20c%20232%20§%207[2018 c 232 § 7]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5182-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2011%20§%20223[2011 1st sp.s. c 11 § 223]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1131-S.SL.pdf?cite=2007%20c%20314%20§%206[2007 c 314 § 6]; ]

== 28B.117.055 - Training for disadvantaged populations.
Subject to availability of amounts appropriated for this specific purpose, the office, with approval from the employment security department and the apprenticeship and training council pursuant to chapter 49.04 RCW, shall contract with at least one nongovernmental entity to provide quality training, employment navigation, and supportive services to disadvantaged populations seeking to complete apprenticeships and preapprenticeships through the passport to apprenticeship opportunities program. The nongovernmental entity shall also disburse state financial assistance under RCW 28B.117.030(5) to meet registered apprenticeship and preapprenticeship entrance requirements and occupational-specific costs.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6274-S2.SL.pdf?cite=2018%20c%20232%20§%208[2018 c 232 § 8]; ]

== 28B.117.900 - Construction—2007 c 314.
Nothing in this chapter may be construed to:

. Guarantee acceptance by, or entrance into, any institution of higher education; or

. Limit the participation of youth, in or formerly in, foster care in Washington state in any other program of financial assistance for postsecondary education.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1131-S.SL.pdf?cite=2007%20c%20314%20§%209[2007 c 314 § 9]; ]

