= 28B.145 - Opportunity scholarship act.
:toc:

== 28B.145.005 - Finding—Intent.
The legislature finds that, despite increases in degree production, there remain acute shortages in high employer demand programs of study, particularly in the science, technology, engineering, and mathematics (STEM) and health care fields of study. According to the workforce training and education coordinating board, seventeen percent of Washington businesses had difficulty finding job applicants in 2010. Eleven thousand employers did not fill a vacancy because they lacked qualified job applicants. Fifty-nine percent of projected job openings in Washington state from now until 2017 will require some form of postsecondary education and training.

It is the intent of the legislature to provide jobs and opportunity by making Washington the place where the world's most productive companies find the world's most talented people. The legislature intends to accomplish this through the creation of the opportunity scholarship and the opportunity expansion programs to: Help mitigate the impact of tuition increases; increase the number of professional-technical certificates, professional-technical degrees, baccalaureate degrees in high employer demand and other programs, and advanced degrees in health professions; and invest in programs and students to meet market demands for a knowledge-based economy while filling middle-income jobs with a sufficient supply of skilled workers.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2158-S2.SL.pdf?cite=2019%20c%20406%20§%2062[2019 c 406 § 62]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2143-S2.SL.pdf?cite=2018%20c%20209%20§%205[2018 c 209 § 5]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1452.SL.pdf?cite=2018%20c%20114%20§%201[2018 c 114 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2088-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2013%20§%201[2011 1st sp.s. c 13 § 1]; ]

== 28B.145.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Board" means the opportunity scholarship board.

. "Council" means the student achievement council.

. "Eligible advanced degree program" means a health professional degree program beyond the baccalaureate level and includes graduate and professional degree programs.

. "Eligible county" has the same meaning as "rural county" as defined in RCW 82.14.370 and also includes any county that shares a common border with Canada and has a population of over one hundred twenty-five thousand.

. "Eligible education programs" means high employer demand and other programs of study as determined by the board.

. "Eligible expenses" means reasonable expenses associated with the costs of acquiring an education such as tuition, books, equipment, fees, room and board, and other expenses as determined by the program administrator in consultation with the council and the state board for community and technical colleges.

. "Eligible school district" means a school district of the second class as identified in RCW 28A.300.065(2).

. "Eligible student" means a resident student who received his or her high school diploma or high school equivalency certificate as provided in RCW 28B.50.536 in Washington and who:

.. [Empty]
... Has been accepted at a four-year institution of higher education into an eligible education program leading to a baccalaureate degree;

... Will attend a two-year institution of higher education and intends to transfer to an eligible education program at a four-year institution of higher education;

... Has been accepted at an institution of higher education into a professional-technical degree program in an eligible education program;

... Has been accepted at an institution of higher education into a professional-technical certificate program in an eligible education program; or

.. Has been accepted at an institution of higher education into an eligible advanced degree program that leads to credentials in health professions;

.. Declares an intention to obtain a professional-technical certificate, professional-technical degree, baccalaureate degree, or an advanced degree; and

.. Has a family income at or below one hundred twenty-five percent of the state median family income at the time the student applies for an opportunity scholarship.

. "Gift aid" means financial aid received from the federal Pell grant, the Washington college grant program in chapter 28B.92 RCW, the college bound scholarship program in chapter 28B.118 RCW, the opportunity grant program in chapter 28B.50 RCW, or any other state grant, scholarship, or worker retraining program that provides funds for educational purposes with no obligation of repayment. "Gift aid" does not include student loans, work-study programs, the basic food employment and training program administered by the department of social and health services, or other employment assistance programs that provide job readiness opportunities and support beyond the costs of tuition, books, and fees.

. "High employer demand program of study" has the same meaning as provided in RCW 28B.50.030.

. "Participant" means an eligible student who has received a scholarship under the opportunity scholarship program.

. "Private sources," "private funds," "private contributions," or "private sector contributions" means donations from private organizations, corporations, federally recognized Indian tribes, municipalities, counties, and other sources, but excludes state dollars.

. "Professional-technical certificate" means a program as approved by the state board for community and technical colleges under RCW 28B.50.090(7)(c), that is offered by an institution of higher education.

. "Professional-technical degree" means a program as approved by the state board for community and technical colleges under RCW 28B.50.090(7)(c), that is offered by an institution of higher education.

. "Program administrator" means a private nonprofit corporation registered under Title 24 RCW and qualified as a tax-exempt entity under section 501(c)(3) of the federal internal revenue code.

. "Resident student" has the same meaning as provided in RCW 28B.15.012.

. "Rural jobs program" means the rural county high employer demand jobs program created in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2158-S2.SL.pdf?cite=2019%20c%20406%20§%2063[2019 c 406 § 63]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2177-S2.SL.pdf?cite=2018%20c%20254%20§%209[2018 c 254 § 9]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2143-S2.SL.pdf?cite=2018%20c%20209%20§%206[2018 c 209 § 6]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1452.SL.pdf?cite=2018%20c%20114%20§%202[2018 c 114 § 2]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2612-S.SL.pdf?cite=2014%20c%20208%20§%201[2014 c 208 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1686-S.SL.pdf?cite=2013%20c%2039%20§%2013[2013 c 39 § 13]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2088-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2013%20§%202[2011 1st sp.s. c 13 § 2]; ]

== 28B.145.020 - Opportunity scholarship board.
. The opportunity scholarship board is created. The board consists of eleven members:

.. Six members appointed by the governor. For three of the six appointments, the governor shall consider names from a list provided by the president of the senate and the speaker of the house of representatives; and

.. Five foundation or business and industry representatives appointed by the governor from among the state's most productive industries such as aerospace, manufacturing, health care, information technology, engineering, agriculture, and others, as well as philanthropy. The foundation or business and industry representatives shall be selected from among nominations provided by the private sector donors to the opportunity scholarship and opportunity expansion programs. However, the governor may request, and the private sector donors shall provide, an additional list or lists from which the governor shall select these representatives.

. Board members shall hold their offices for a term of four years from the first day of September and until their successors are appointed. No more than the terms of two members may expire simultaneously on the last day of August in any one year.

. The members of the board shall elect one of the business and industry representatives to serve as chair.

. Seven members of the board constitute a quorum for the transaction of business. In case of a vacancy, or when an appointment is made after the date of expiration of the term, the governor or the president of the senate or the speaker of the house of representatives, depending upon which made the initial appointment to that position, shall fill the vacancy for the remainder of the term of the board member whose office has become vacant or expired.

. The board shall be staffed by a program administrator, under contract with the board and the council.

. The purpose of the board is to provide oversight and guidance for the opportunity expansion program, the opportunity scholarship program, and the rural jobs program, in light of established legislative priorities and to fulfill the duties and responsibilities under this chapter, including but not limited to determining eligible education programs and eligible advanced degree programs for purposes of the opportunity scholarship program and rural jobs program. In determining eligible advanced degree programs, the board shall consider advanced degree programs that lead to credentials in health professions that include, but are not limited to, primary care, dental care, behavioral health, and public health. Duties, exercised jointly with the program administrator, include soliciting funds and setting annual fund-raising goals.

. The board may report to the governor and the appropriate committees of the legislature with recommendations as to:

.. Whether some or all of the scholarships should be changed to conditional scholarships that must be repaid in the event the participant does not complete the eligible education program;

.. A source or sources of funds for the opportunity expansion program in addition to the voluntary contributions of the high-technology research and development tax credit under RCW 82.32.800; and

.. Whether the program should include a loan repayment or low-interest or no-interest loan component for the advanced degree portion of the program.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2158-S2.SL.pdf?cite=2019%20c%20406%20§%2064[2019 c 406 § 64]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2177-S2.SL.pdf?cite=2018%20c%20254%20§%202[2018 c 254 § 2]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2143-S2.SL.pdf?cite=2018%20c%20209%20§%207[2018 c 209 § 7]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1452.SL.pdf?cite=2018%20c%20114%20§%203[2018 c 114 § 3]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2612-S.SL.pdf?cite=2014%20c%20208%20§%202[2014 c 208 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2088-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2013%20§%203[2011 1st sp.s. c 13 § 3]; ]

== 28B.145.030 - Program administrator—Duties—Specified accounts.
. The program administrator shall provide administrative support to execute the duties and responsibilities provided in this chapter, including but not limited to publicizing the program, selecting participants for the opportunity scholarship award, distributing opportunity scholarship awards, and achieving the maximum possible rate of return on investment of the accounts in subsection (2) of this section, while ensuring transparency in the investment decisions and processes. Duties, exercised jointly with the board, include soliciting funds and setting annual fund-raising goals. The program administrator shall be paid an administrative fee as determined by the board.

. With respect to the opportunity scholarship program, the program administrator shall:

.. Establish and manage the specified accounts created in (b) of this subsection, into which to receive grants and contributions from private sources as well as state matching funds, and from which to disburse scholarship funds to participants;

.. Solicit and accept grants and contributions from private sources, via direct payment, pledge agreement, or escrow account, of private sources for deposit into any of the specified accounts created in this subsection (2)(b) upon the direction of the donor and in accordance with this subsection (2)(b):

... The "scholarship account," whose principal may be invaded, and from which scholarships must be disbursed for baccalaureate programs beginning no later than December 1, 2011, if, by that date, state matching funds in the amount of five million dollars or more have been received. Thereafter, scholarships shall be disbursed on an annual basis beginning no later than May 1, 2012, and every October 1st thereafter;

... The "student support pathways account," whose principal may be invaded, and from which scholarships may be disbursed for professional-technical certificate or degree programs in the fiscal year following appropriations of state matching funds. Thereafter, scholarships shall be disbursed on an annual basis;

... The "advanced degrees pathways account," whose principal may be invaded, and from which scholarships may be disbursed for eligible advanced degree programs in the fiscal year following appropriations of state matching funds. Thereafter, scholarships shall be disbursed on an annual basis;

... The "endowment account," from which scholarship moneys may be disbursed for baccalaureate programs from earnings only in years when:

(A) The state match has been made into both the scholarship and the endowment account; and

(B) The state appropriations for the Washington college grant program under chapter 28B.92 RCW meet or exceed state appropriations for the state need grant made in the 2011-2013 biennium, adjusted for inflation, and eligibility for Washington college grant recipients is at least seventy percent of state median family income;

.. An amount equal to at least fifty percent of all grants and contributions must be deposited into the scholarship account until such time as twenty million dollars have been deposited into the scholarship account, after which time the private donors may designate whether their contributions must be deposited to the scholarship account, the student support pathways account, the advanced degrees pathways account, or the endowment account. The board and the program administrator must work to maximize private sector contributions to these accounts to maintain a robust scholarship program while simultaneously building the endowment, and to determine the division between the accounts in the case of undesignated grants and contributions, taking into account the need for a long-term funding mechanism and the short-term needs of families and students in Washington. The first five million dollars in state match, as provided in RCW 28B.145.040, shall be deposited into the scholarship account and thereafter the state match shall be deposited into the specified accounts created in this subsection (2)(b) in equal proportion to the private funds deposited in each account, except that no more than one million dollars in state match shall be deposited into the advanced degrees pathways account in a single fiscal biennium; and

.. Once moneys in the opportunity scholarship match transfer account are subject to an agreement under RCW 28B.145.050(5) and are deposited in the scholarship account, the student support pathways account, the advanced degrees pathways account, or the endowment account under this section, the state acts in a fiduciary rather than ownership capacity with regard to those assets. Assets in the scholarship account, the student support pathways account, the advanced degrees pathways account, and the endowment account are not considered state money, common cash, or revenue to the state;

.. Provide proof of receipt of grants and contributions from private sources to the council, identifying the amounts received by name of private source and date, and whether the amounts received were deposited into the scholarship account, the student support pathways account, the advanced degrees pathways account, or the endowment account;

.. In consultation with the council and the state board for community and technical colleges, make an assessment of the reasonable annual eligible expenses associated with eligible education programs and eligible advanced degree programs identified by the board;

.. Determine the dollar difference between tuition fees charged by institutions of higher education in the 2008-09 academic year and the academic year for which an opportunity scholarship is being distributed;

.. Develop and implement an application, selection, and notification process for awarding opportunity scholarships;

.. Ensure that if the private source is from a federally recognized Indian tribe, municipality, or county, an amount at least equal to the value of the private source plus the state match is awarded to participants within that federally recognized Indian tribe, municipality, or county according to the federally recognized Indian tribe's, municipality's, or county's program rules;

.. Determine the annual amount of the opportunity scholarship for each selected participant. The annual amount shall be at least one thousand dollars or the amount determined under (e) of this subsection, but may be increased on an income-based, sliding scale basis up to the amount necessary to cover all reasonable annual eligible expenses as assessed pursuant to (d) of this subsection, or to encourage participation in professional-technical certificate programs, professional-technical degree programs, baccalaureate degree programs, or eligible advanced degree programs identified by the board;

.. Distribute scholarship funds to selected participants. Once awarded, and to the extent funds are available for distribution, an opportunity scholarship shall be automatically renewed as long as the participant annually submits documentation of filing both a free application for federal student aid (FAFSA) and for available federal education tax credits including, but not limited to, the American opportunity tax credit, or if ineligible to apply for federal student aid, the participant annually submits documentation of filing a state financial aid application as approved by the office of student financial assistance; and until the participant withdraws from or is no longer attending the program, completes the program, or has taken the credit or clock hour equivalent of one hundred twenty-five percent of the published length of time of the participant's program, whichever occurs first;

.. Notify institutions of scholarship recipients who will attend their institutions and inform them of the terms of the students' eligibility; and

.. For participants enrolled in an eligible advanced degree program, document each participant's employment following graduation.

. With respect to the opportunity expansion program, the program administrator shall:

.. Assist the board in developing and implementing an application, selection, and notification process for making opportunity expansion awards; and

.. Solicit and accept grants and contributions from private sources for opportunity expansion awards.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2158-S2.SL.pdf?cite=2019%20c%20406%20§%2065[2019 c 406 § 65]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2143-S2.SL.pdf?cite=2018%20c%20209%20§%208[2018 c 209 § 8]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1488-S3.SL.pdf?cite=2018%20c%20204%20§%202[2018 c 204 § 2]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1452.SL.pdf?cite=2018%20c%20114%20§%204[2018 c 114 § 4]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2612-S.SL.pdf?cite=2014%20c%20208%20§%203[2014 c 208 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2088-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2013%20§%204[2011 1st sp.s. c 13 § 4]; ]

== 28B.145.040 - Opportunity scholarship program.
. The opportunity scholarship program is established.

. The purpose of this scholarship program is to provide scholarships that will help low and middle-income Washington residents earn professional-technical certificates, professional-technical degrees, baccalaureate degrees in high employer demand and other programs of study, and advanced degrees in health professions, and encourage them to remain in the state to work. The program must be designed for students starting professional-technical certificate or degree programs, students starting at two-year institutions of higher education and intending to transfer to four-year institutions of higher education, students starting at four-year institutions of higher education, and students enrolled in eligible advanced degree programs.

. The opportunity scholarship board shall determine which programs of study, including but not limited to high employer demand programs, are eligible for purposes of the opportunity scholarship. For eligible advanced degree programs, the board shall limit scholarships to eligible students enrolling in programs that lead to credentials in health professions.

. [Empty]
.. The source of funds for the program shall be a combination of private grants and contributions and state matching funds. A state match may be earned under this section for private contributions made on or after June 6, 2011.

.. The state match must be based on donations and pledges received as of the date each official state caseload forecast is submitted by the caseload forecast council to the legislative fiscal committees, as provided under RCW 43.88C.020. The purpose of this subsection (4)(b) is to ensure the predictable treatment of the program in the budget process by clarifying the calculation process of the state match required by this section and ensuring the program is budgeted at maintenance level.

.. A state match, up to a maximum of fifty million dollars annually, shall be provided beginning the later of January 1, 2014, or January 1st next following the end of the fiscal year in which collections of state retail sales and use tax, state business and occupation tax, and state public utility tax exceed, by ten percent the amounts collected from these tax resources in the fiscal year that ended June 30, 2008, as determined by the department of revenue.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2158-S2.SL.pdf?cite=2019%20c%20406%20§%2066[2019 c 406 § 66]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2143-S2.SL.pdf?cite=2018%20c%20209%20§%209[2018 c 209 § 9]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1452.SL.pdf?cite=2018%20c%20114%20§%205[2018 c 114 § 5]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2088-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2013%20§%205[2011 1st sp.s. c 13 § 5]; ]

== 28B.145.050 - Opportunity scholarship match transfer account.
. The opportunity scholarship match transfer account is created in the custody of the state treasurer as a nonappropriated account to be used solely and exclusively for the opportunity scholarship program created in RCW 28B.145.040. The purpose of the account is to provide matching funds for the opportunity scholarship program.

. Revenues to the account shall consist of appropriations by the legislature into the account and any gifts, grants, or donations received by the executive director of the council for this purpose.

. No expenditures from the account may be made except upon receipt of proof, by the executive director of the council from the program administrator, of private contributions to the opportunity scholarship program. Expenditures, in the form of matching funds, may not exceed the total amount of private contributions.

. Only the executive director of the council or the executive director's designee may authorize expenditures from the opportunity scholarship match transfer account. Such authorization must be made as soon as practicable following receipt of proof as required under subsection (3) of this section.

. The council shall enter into an appropriate agreement with the program administrator to demonstrate exchange of consideration for the matching funds.

. During the 2019-2021 fiscal biennium, expenditures from the opportunity scholarship match transfer account may be used for payment to the program administrator for administrative duties carried out under this chapter in an amount not to exceed two hundred fifty thousand dollars per fiscal year.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6168-S.SL.pdf?cite=2020%20c%20357%20§%20912[2020 c 357 § 912]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2612-S.SL.pdf?cite=2014%20c%20208%20§%205[2014 c 208 § 5]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2088-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2013%20§%206[2011 1st sp.s. c 13 § 6]; ]

== 28B.145.055 - Opportunity scholarship program—Awards not considered state-funded.
The office of student financial assistance and the institutions of higher education may not consider awards made under the opportunity scholarship program to be state-funded for the purpose of determining the value of an award for other state financial aid programs.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2158-S2.SL.pdf?cite=2019%20c%20406%20§%2068[2019 c 406 § 68]; ]

== 28B.145.060 - Opportunity expansion program—Generally—Reports.
. The opportunity expansion program is established.

. The board shall select institutions of higher education to receive opportunity expansion awards. In so doing, the board must:

.. Solicit, receive, and evaluate proposals from institutions of higher education that are designed to directly increase the number of baccalaureate degrees produced in high employer demand and other programs of study, and that include annual numerical targets for the number of such degrees, with a strong emphasis on serving students who received their high school diploma or high school equivalency certificate as provided in RCW 28B.50.536 in Washington or are adult Washington residents who are returning to school to gain a baccalaureate degree;

.. Develop criteria for evaluating proposals and awarding funds to the proposals deemed most likely to increase the number of baccalaureate degrees and degrees produced in high employer demand and other programs of study;

.. Give priority to proposals that include a partnership between public and private partnership entities that leverage additional private funds;

.. Give priority to proposals that are innovative, efficient, and cost-effective, given the nature and cost of the particular program of study;

.. Consult and operate in consultation with existing higher education stakeholders, including but not limited to: Faculty, labor, student organizations, and relevant higher education agencies; and

.. Determine which proposals to improve and accelerate the production of baccalaureate degrees in high employer demand and other programs of study will receive opportunity expansion awards for the following state fiscal year, notify the state treasurer, and announce the awards.

. The state treasurer, at the direction of the board, must distribute the funds that have been awarded to the institutions of higher education from the opportunity expansion account.

. Institutions of higher education receiving awards under this section may not supplant existing general fund state revenues with opportunity expansion awards.

. Annually, the office of financial management shall report to the board, the governor, and the relevant committees of the legislature regarding the percentage of Washington households with incomes in the middle-income bracket or higher. For purposes of this section, "middle-income bracket" means household incomes between two hundred and five hundred percent of the 2010 federal poverty level, as determined by the United States department of health and human services for a family of four, adjusted annually for inflation.

. Annually, the council must report to the board, the governor, and the relevant committees of the legislature regarding the increase in the number of degrees in high employer demand and other programs of study awarded by institutions of higher education over the average of the preceding ten academic years.

. In its comprehensive plan, the workforce training and education coordinating board shall include specific strategies to reach the goal of increasing the percentage of Washington households living in the middle-income bracket or higher, as calculated by the office of financial management and developed by the agency or education institution that will lead the strategy.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2612-S.SL.pdf?cite=2014%20c%20208%20§%206[2014 c 208 § 6]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1686-S.SL.pdf?cite=2013%20c%2039%20§%2014[2013 c 39 § 14]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2088-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2013%20§%207[2011 1st sp.s. c 13 § 7]; ]

== 28B.145.070 - Reports—Review for legislative action.
. Annually each December 1st, the board, together with the program administrator, shall report to the council, the governor, and the appropriate committees of the legislature regarding the rural jobs program and opportunity scholarship and opportunity expansion programs, including but not limited to:

.. Which education programs the board determined were eligible for purposes of the opportunity scholarship and which high employer demand fields within eligible counties were identified for purposes of the rural jobs program;

.. The number of applicants for the opportunity scholarship and rural jobs program, disaggregated, to the extent possible, by race, ethnicity, gender, county of origin, age, and median family income;

.. The number of participants in the opportunity scholarship program and rural jobs program, disaggregated, to the extent possible, by race, ethnicity, gender, county of origin, age, and median family income;

.. The number and amount of the scholarships actually awarded, whether the scholarships were paid from the student support pathways account, the scholarship account, or the endowment account, and the number and amount of scholarships actually awarded under the rural jobs program;

.. The institutions and eligible education programs in which opportunity scholarship participants enrolled, together with data regarding participants' completion and graduation, and the institutions and programs in which recipients of the rural jobs program scholarship enrolled, together with recipients' data on completion and graduation;

.. The total amount of private contributions and state match moneys received for the rural jobs program and the opportunity scholarship program, how the funds under the opportunity scholarship program were distributed between the student support pathways account, the scholarship account, and the endowment account, the interest or other earnings on all the accounts created under this chapter, and the amount of any administrative fee paid to the program administrator; and

.. Identification of the programs the board selected to receive opportunity expansion awards and the amount of such awards.

. In the next succeeding legislative session following receipt of a report required under subsection (1) of this section, the appropriate committees of the legislature shall review the report and consider whether any legislative action is necessary with respect to the rural jobs program, the opportunity scholarship program, or the opportunity expansion program, including but not limited to consideration of whether any legislative action is necessary with respect to the nature and level of focus on high employer demand fields and the number and amount of scholarships.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2177-S2.SL.pdf?cite=2018%20c%20254%20§%208[2018 c 254 § 8]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2612-S.SL.pdf?cite=2014%20c%20208%20§%207[2014 c 208 § 7]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2088-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2013%20§%208[2011 1st sp.s. c 13 § 8]; ]

== 28B.145.080 - Evaluation of opportunity scholarship and opportunity expansion programs by joint legislative audit and review committee.
. Beginning in 2018, the joint legislative audit and review committee shall evaluate the opportunity scholarship and opportunity expansion programs, and submit a report to the appropriate committees of the legislature by December 1, 2018. The committee's evaluation shall include, but not be limited to:

.. The number and type of eligible education programs as determined by the opportunity scholarship board;

.. The number of participants in the opportunity scholarship program in relation to the number of participants who completed a baccalaureate degree;

.. The total cumulative number of students who received opportunity scholarships, and the total cumulative number of students who gained a baccalaureate degree after receiving an opportunity scholarship and the types of baccalaureate degrees awarded;

.. The amount of private contributions to the opportunity scholarship program, annually and in total;

.. The amount of state match moneys to the opportunity scholarship program, annually and in total;

.. The amount of any administrative fees paid to the program administrator, annually and in total;

.. The source and amount of funding, annually and cumulatively, for the opportunity expansion program;

.. The number and type of proposals submitted by institutions for opportunity expansion awards, the number and type of proposals that received an award of opportunity expansion funds, and the amount of such awards;

.. The total cumulative number of additional high employer demand degrees produced in Washington state due to the opportunity expansion program, including both the initial opportunity expansion awards and the subsequent inclusion in base funding; and

.. Evidence that the existence of the opportunity scholarship and opportunity expansion programs have contributed to the achievement of the public policy objectives of helping to mitigate the impact of tuition increases, increasing the number of baccalaureate degrees in high employer demand and other programs, and investing in programs and students to meet market demands for a knowledge-based economy while filling middle-income jobs with a sufficient supply of skilled workers.

. In the event that the joint legislative audit and review committee is charged with completing an evaluation of other aspects of degree production, funding, or other aspects of higher education in 2018, and to the extent that it is economical and feasible to do so, the committee shall combine the multiple evaluations and submit a single report.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2088-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2013%20§%209[2011 1st sp.s. c 13 § 9]; ]

== 28B.145.090 - Investments by the state investment board.
. The board may elect to have the state investment board invest the funds in the scholarship account, the student support pathways account, the advanced degrees pathways account, and the endowment account described under RCW 28B.145.030(2)(b). If the board so elects, the state investment board has the full power to invest, reinvest, manage, contract, sell, or exchange investment money in these accounts. All investment and operating costs associated with the investment of money shall be paid under RCW 43.33A.160 and 43.84.160. With the exception of these expenses, the earnings from the investment of the money shall be retained by the accounts.

. All investments made by the state investment board shall be made with the exercise of that degree of judgment and care under RCW 43.33A.140 and the investment policy established by the state investment board.

. As deemed appropriate by the state investment board, money in the scholarship account, the student support pathways account, the advanced degrees pathways account, and the endowment account may be commingled for investment with other funds subject to investment by the state investment board.

. Members of the state investment board shall not be considered an insurer of the funds or assets and are not liable for any action or inaction.

. Members of the state investment board are not liable to the state, to the fund, or to any other person as a result of their activities as members, whether ministerial or discretionary, except for willful dishonesty or intentional violations of law. The state investment board in its discretion may purchase liability insurance for members.

. The authority to establish all policies relating to the scholarship account, the student support pathways account, the advanced degrees pathways account, and the endowment account, other than the investment policies as provided in subsections (1) through (3) of this section, resides with the board and program administrator acting in accordance with the principles set forth in this chapter. With the exception of expenses of the state investment board in subsection (1) of this section, disbursements from the scholarship account, the student support pathways account, the advanced degrees pathways account, and the endowment account shall be made only on the authorization of the opportunity scholarship board or its designee, and moneys in the accounts may be spent only for the purposes specified in this chapter.

. The state investment board shall routinely consult and communicate with the board on the investment policy, earnings of the accounts, and related needs of the program.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2158-S2.SL.pdf?cite=2019%20c%20406%20§%2067[2019 c 406 § 67]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2177-S2.SL.pdf?cite=2018%20c%20254%20§%203[2018 c 254 § 3]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2143-S2.SL.pdf?cite=2018%20c%20209%20§%2010[2018 c 209 § 10]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1452.SL.pdf?cite=2018%20c%20114%20§%206[2018 c 114 § 6]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2612-S.SL.pdf?cite=2014%20c%20208%20§%204[2014 c 208 § 4]; ]

== 28B.145.100 - Rural jobs program.
. [Empty]
.. The rural county high employer demand jobs program is created to meet the workforce needs of business and industry in rural counties by assisting students in earning certificates, associate degrees, or other industry-recognized credentials necessary for employment in high employer demand fields.

.. Subject to the requirements of this section, the rural jobs program provides selected students scholarship funds and support services, as determined by the board, to help students meet their eligible expenses when they enroll in a community or technical college program that prepares them for high employer demand fields.

.. The source of funds for the rural jobs program shall be a combination of private donations, grants, and contributions and state matching funds.

. The program administrator has the duties and responsibilities provided under this section, including but not limited to:

.. Publicizing the rural jobs program and conducting outreach to eligible counties;

.. In consultation with the state board for community and technical colleges, any interested community or technical college located in an eligible county, and the county's workforce development council, identify high employer demand fields within the eligible counties. When identifying high employer demand fields, the board must consider:

... County-specific employer demand reports issued by the employment security department or the list of statewide high-demand programs for secondary career and technical education established under RCW 28A.700.020; and

... The ability and capacity of the community and technical college to meet the needs of qualifying students and industry in the eligible county;

.. Develop and implement an application, selection, and notification process for awarding rural jobs program scholarship funds. In making determinations on scholarship recipients, the board shall use county-specific employer high-demand data;

.. Determine the annual scholarship fund amounts to be awarded to selected students;

.. Distribute funds to selected students;

.. Notify institutions of higher education of the rural jobs program recipients who will attend their institutions of higher education and inform them of the scholarship fund amounts and terms of the awards; and

.. Establish and manage an account as provided under RCW 28B.145.110 to receive donations, grants, contributions from private sources, and state matching funds, and from which to disburse scholarship funds to selected students.

. To be eligible for scholarship funds under the rural jobs program, a student must:

.. Be a resident of an eligible county or have attended and graduated from a school in an eligible school district;

.. Be a resident student as defined in RCW 28B.15.012;

.. Be enrolled in a community or technical college established under chapter 28B.50 RCW located in an eligible county;

.. Be in a certificate, degree, or other industry-recognized credential or training program that has been identified by the board as a program that prepares students for a high employer demand field;

.. Have a family income that does not exceed seventy percent of the state median family income adjusted for family size; and

.. Demonstrate financial need according to the free application for federal student aid or the Washington application for state financial aid.

. To remain eligible for scholarship funds under the rural jobs program, the student must maintain a cumulative grade point average of 2.0.

. A scholarship award under the rural jobs program may not result in a reduction of any gift aid. Nothing in this section creates any right or entitlement.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2177-S2.SL.pdf?cite=2018%20c%20254%20§%204[2018 c 254 § 4]; ]

== 28B.145.110 - Rural jobs program—Administrator duties—Student support pathways account.
. For the purposes of the rural jobs program, the program administrator shall:

.. Jointly with the board, solicit and accept donations, grants, and contributions from private sources via direct payment, pledge agreement, or escrow account, for deposit into the student support pathways account created in this section, and set annual fund-raising goals;

.. Establish and manage the student support pathways account to receive grants, contributions from private sources, and state matching funds, and from which to disburse scholarship funds to selected students; and

.. Provide proof of receipt of grants and contributions from private sources to the council, identifying the amounts received by the name of the private source and date received, and whether the amounts received were deposited into the student support pathways account.

. The student support pathways account, whose principal may be invaded, must be created by the board from which scholarship funds will be disbursed beginning no later than the fall term of the 2020 academic year, if by that date, state matching funds have been received. Thereafter, scholarship funds shall be disbursed on an annual basis.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2177-S2.SL.pdf?cite=2018%20c%20254%20§%205[2018 c 254 § 5]; ]

== 28B.145.120 - Rural jobs program—Match transfer account.
. The rural jobs program match transfer account is created in the custody of the state treasurer as a nonappropriated account to be used solely and exclusively for the rural jobs program created in RCW 28B.145.100. The purpose of the rural jobs program match transfer account is to provide state matching funds for the rural jobs program.

. Revenues to the rural jobs program match transfer account shall consist of appropriations by the legislature into the rural jobs program match transfer account.

. No expenditures from the rural jobs program match transfer account may be made except upon receipt of proof, by the executive director of the council from the program administrator, of private contributions to the rural jobs program. Expenditures, in the form of matching funds, may not exceed the total amount of private contributions.

. Only the executive director of the council or the executive director's designee may authorize expenditures from the rural jobs program match transfer account. Such authorization must be made as soon as practicable following receipt of proof as required under this section.

. [Empty]
.. The council shall enter into an appropriate agreement with the program administrator to demonstrate exchange of consideration for the matching funds.

.. Once moneys in the rural jobs program match transfer account are subject to an agreement under this subsection and are deposited in the student support pathways account, the state acts in a fiduciary rather than ownership capacity with regard to those assets. Assets in the student support pathways account are not considered state money, common cash, or revenue to the state.

. The state match must not exceed one million dollars in a single fiscal biennium and must be based on donations and pledges received by the rural jobs program as of the date each official state caseload forecast is submitted by the caseload forecast council to the legislative fiscal committees, as provided under RCW 43.88C.020. Nothing in this section expands or modifies the responsibilities of the caseload forecast council.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2177-S2.SL.pdf?cite=2018%20c%20254%20§%206[2018 c 254 § 6]; ]

== 28B.145.130 - Rural jobs program—State matching funds.
The total amount of state matching funds for the rural jobs program shall not exceed one million dollars in a single fiscal biennium.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2177-S2.SL.pdf?cite=2018%20c%20254%20§%207[2018 c 254 § 7]; ]

== 28B.145.900 - Short title.
This chapter may be known and cited as the opportunity scholarship act.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2088-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2013%20§%2011[2011 1st sp.s. c 13 § 11]; ]

== 28B.145.901 - Effective date—2011 1st sp.s. c 13.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and takes effect immediately [June 6, 2011].

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2088-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2013%20§%2013[2011 1st sp.s. c 13 § 13]; ]

