= 28B.94 - Washington student loan refinancing program.
:toc:

== 28B.94.010 - Definitions. (Expires July 1, 2029.)
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Council" means the Washington student achievement council.

. "Financial institution" has the same meaning as in RCW 7.88.010.

. "Interest rate buy down incentive" means the use of state funds to enable qualified borrowers to receive below market rate interest rates for the purposes of this chapter.

. "Loan loss reserve coverage" means partial risk coverage to financial institutions to cover losses on qualified loans according to the terms set forth in the contract between the agency and the financial institution for the purposes of this chapter.

. "Program" means the Washington student loan refinancing program.

. "Qualified borrower" means an individual meeting all of the following requirements:

.. Resident of the state of Washington;

.. Is enrolled in, or has completed, a certificate, associate's, bachelor's, graduate, or professional degree program; and

.. Other criteria as deemed appropriate by the council.

. "Qualified loan" means a loan or a portion of a loan made by a financial institution to a qualified borrower to refinance an existing student loan under the program. Only a federal direct PLUS loan or a private student loan determined by the financial institution to be an educational loan that is nondischargeable in bankruptcy as set forth in 11 U.S.C. Sec. 523 as it existed on January 14, 2019, shall be a qualified loan eligible for refinancing. A qualified loan made under the program shall:

.. Carry a contractual interest rate at least one-quarter of one percentage point lower than the loan being refinanced, and may be made with the interest rates, fees, and other terms and conditions agreed upon by the financial institution and the qualified borrower; and

.. Specify that a qualified borrower's obligation under a qualified loan must be discharged if the qualified borrower dies, based on the following:

... An original or certified copy of the qualified borrower's death certificate;

... An accurate and complete photocopy of the original or certified copy of the qualified borrower's death certificate;

... An accurate and complete original or certified copy of the qualified borrower's death certificate that is scanned and submitted electronically or sent by facsimile transmission; or

... Verification of the qualified borrower's death through an authoritative federal or state electronic database approved for use by the council.

. This section expires July 1, 2029.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2158-S2.SL.pdf?cite=2019%20c%20406%20§%2050[2019 c 406 § 50]; ]

== 28B.94.020 - Program administration—Report. (Expires July 1, 2029.)
. Subject to the availability of amounts appropriated for this specific purpose, the Washington student loan refinancing program is created.

. The program shall be administered by the council. To execute the program the council shall contract with up to five financial institutions. The financial institutions, in consultation with the council, may leverage the interest rate buy down incentive or the loan loss reserve coverage, or some combination thereof, to refinance existing student loans. In administering the program, the council may:

.. Impose reasonable limits on the terms of qualified loans;

.. Impose reasonable limits on the terms of qualified borrowers;

.. Impose reasonable limits on the use of state funds for the marketing on qualified loan products by financial institutions;

.. Establish minimum reporting requirements for financial institutions participating in the program;

.. Establish minimum required disclosures by financial institutions for qualified loans. At a minimum, the disclosures must notify qualified borrowers of the:

... Loss of borrower protections including income contingent repayment and public service loan forgiveness options if the qualified borrower is refinancing a federal direct PLUS student loan under this chapter; and

... Estimated total cost of the qualified loan, including accrued interest under this chapter;

.. Appoint and use advisory committees and the department of financial institutions as needed to provide program guidance and direction;

.. Formulate and adopt all other policies and rules necessary for the efficient administration of the program;

.. Make, execute, and deliver contracts, conveyances, and other instruments necessary to the exercise and discharge of its powers and duties under this chapter; and

.. Perform all acts necessary and proper to carry out the duties and responsibilities of the program under this chapter.

. On a biennial basis beginning July 1, 2020, the council must report to the appropriate committees of the legislature the:

.. Number of financial institutions currently under contract through the program;

.. Number of qualified student loans successfully refinanced under the program;

.. Qualified borrower requirements established by the council and the financial institutions;

.. Demographic information for borrowers that includes gender, race or ethnicity, income level, and geography; and

.. Estimated total savings by qualified borrowers with qualified loans as defined by the difference between what the student would have paid under the existing loan and what the student would pay when given the option to refinance.

. This section expires July 1, 2029.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2158-S2.SL.pdf?cite=2019%20c%20406%20§%2051[2019 c 406 § 51]; ]

