= 9A.36 - Assault—Physical harm.
:toc:

== 9A.36.011 - Assault in the first degree.
. A person is guilty of assault in the first degree if he or she, with intent to inflict great bodily harm:

.. Assaults another with a firearm or any deadly weapon or by any force or means likely to produce great bodily harm or death; or

.. Transmits HIV to a child or vulnerable adult; or

.. Administers, exposes, or transmits to or causes to be taken by another, poison or any other destructive or noxious substance; or

.. Assaults another and inflicts great bodily harm.

. Assault in the first degree is a class A felony.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1551-S.SL.pdf?cite=2020%20c%2076%20§%2016[2020 c 76 § 16]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5044-S.SL.pdf?cite=1997%20c%20196%20§%201[1997 c 196 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c257.pdf?cite=1986%20c%20257%20§%204[1986 c 257 § 4]; ]

== 9A.36.021 - Assault in the second degree.
. A person is guilty of assault in the second degree if he or she, under circumstances not amounting to assault in the first degree:

.. Intentionally assaults another and thereby recklessly inflicts substantial bodily harm; or

.. Intentionally and unlawfully causes substantial bodily harm to an unborn quick child by intentionally and unlawfully inflicting any injury upon the mother of such child; or

.. Assaults another with a deadly weapon; or

.. With intent to inflict bodily harm, administers to or causes to be taken by another, poison or any other destructive or noxious substance; or

.. With intent to commit a felony, assaults another; or

.. Knowingly inflicts bodily harm which by design causes such pain or agony as to be the equivalent of that produced by torture; or

.. Assaults another by strangulation or suffocation.

. [Empty]
.. Except as provided in (b) of this subsection, assault in the second degree is a class B felony.

.. Assault in the second degree with a finding of sexual motivation under RCW 9.94A.835 or 13.40.135 is a class A felony.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1188-S.SL.pdf?cite=2011%20c%20166%20§%201[2011 c 166 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5953.SL.pdf?cite=2007%20c%2079%20§%202[2007 c 79 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%2064[2003 c 53 § 64]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6151-S.SL.pdf?cite=2001%202nd%20sp.s.%20c%2012%20§%20355[2001 2nd sp.s. c 12 § 355]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5044-S.SL.pdf?cite=1997%20c%20196%20§%202[1997 c 196 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c266.pdf?cite=1988%20c%20266%20§%202[1988 c 266 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c206.pdf?cite=1988%20c%20206%20§%20916[1988 c 206 § 916]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c158.pdf?cite=1988%20c%20158%20§%202[1988 c 158 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c324.pdf?cite=1987%20c%20324%20§%202[1987 c 324 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c257.pdf?cite=1986%20c%20257%20§%205[1986 c 257 § 5]; ]

== 9A.36.031 - Assault in the third degree.
. A person is guilty of assault in the third degree if he or she, under circumstances not amounting to assault in the first or second degree:

.. With intent to prevent or resist the execution of any lawful process or mandate of any court officer or the lawful apprehension or detention of himself, herself, or another person, assaults another; or

.. Assaults a person employed as a transit operator or driver, the immediate supervisor of a transit operator or driver, a mechanic, or a security officer, by a public or private transit company or a contracted transit service provider, while that person is performing his or her official duties at the time of the assault; or

.. Assaults a school bus driver, the immediate supervisor of a driver, a mechanic, or a security officer, employed by a school district transportation service or a private company under contract for transportation services with a school district, while the person is performing his or her official duties at the time of the assault; or

.. With criminal negligence, causes bodily harm to another person by means of a weapon or other instrument or thing likely to produce bodily harm; or

.. Assaults a firefighter or other employee of a fire department, county fire marshal's office, county fire prevention bureau, or fire protection district who was performing his or her official duties at the time of the assault; or

.. With criminal negligence, causes bodily harm accompanied by substantial pain that extends for a period sufficient to cause considerable suffering; or

.. Assaults a law enforcement officer or other employee of a law enforcement agency who was performing his or her official duties at the time of the assault; or

.. Assaults a peace officer with a projectile stun gun; or

.. Assaults a nurse, physician, or health care provider who was performing his or her nursing or health care duties at the time of the assault. For purposes of this subsection: "Nurse" means a person licensed under chapter 18.79 RCW; "physician" means a person licensed under chapter 18.57 or 18.71 RCW; and "health care provider" means a person certified under chapter 18.71 or 18.73 RCW who performs emergency medical services or a person regulated under Title 18 RCW and employed by, or contracting with, a hospital licensed under chapter 70.41 RCW; or

.. Assaults a judicial officer, court-related employee, county clerk, or county clerk's employee, while that person is performing his or her official duties at the time of the assault or as a result of that person's employment within the judicial system. For purposes of this subsection, "court-related employee" includes bailiffs, court reporters, judicial assistants, court managers, court managers' employees, and any other employee, regardless of title, who is engaged in equivalent functions; or

.. Assaults a person located in a courtroom, jury room, judge's chamber, or any waiting area or corridor immediately adjacent to a courtroom, jury room, or judge's chamber. This section shall apply only: (i) During the times when a courtroom, jury room, or judge's chamber is being used for judicial purposes during court proceedings; and (ii) if signage was posted in compliance with RCW 2.28.200 at the time of the assault.

. Assault in the third degree is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5484.SL.pdf?cite=2013%20c%20256%20§%201[2013 c 256 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20359[2011 c 336 § 359]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1794.SL.pdf?cite=2011%20c%20238%20§%201[2011 c 238 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1934-S.SL.pdf?cite=2005%20c%20458%20§%201[2005 c 458 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1442.SL.pdf?cite=1999%20c%20328%20§%201[1999 c 328 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5499.SL.pdf?cite=1998%20c%2094%20§%201[1998 c 94 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5681.SL.pdf?cite=1997%20c%20172%20§%201[1997 c 172 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2791.SL.pdf?cite=1996%20c%20266%20§%201[1996 c 266 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c236.pdf?cite=1990%20c%20236%20§%201[1990 c 236 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c169.pdf?cite=1989%20c%20169%20§%201[1989 c 169 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c158.pdf?cite=1988%20c%20158%20§%203[1988 c 158 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c257.pdf?cite=1986%20c%20257%20§%206[1986 c 257 § 6]; ]

== 9A.36.041 - Assault in the fourth degree.
. A person is guilty of assault in the fourth degree if, under circumstances not amounting to assault in the first, second, or third degree, or custodial assault, he or she assaults another.

. Assault in the fourth degree is a gross misdemeanor, except as provided in subsection (3) of this section.

. [Empty]
.. Assault in the fourth degree occurring after July 23, 2017, and before March 18, 2020, where domestic violence is pleaded and proven, is a class C felony if the person has two or more prior adult convictions within ten years for any of the following offenses occurring after July 23, 2017, where domestic violence was pleaded and proven:

... Repetitive domestic violence offense as defined in RCW 9.94A.030;

... Crime of harassment as defined by RCW 9A.46.060;

... Assault in the third degree;

... Assault in the second degree;

.. Assault in the first degree; or

.. A municipal, tribal, federal, or out-of-state offense comparable to any offense under (a)(i) through (v) of this subsection.

For purposes of this subsection (3)(a), "family or household members" for purposes of the definition of "domestic violence" means spouses, domestic partners, former spouses, former domestic partners, persons who have a child in common regardless of whether they have been married or have lived together at any time, persons sixteen years of age or older who are presently residing together or who have resided together in the past and who have or have had a dating relationship, and persons sixteen years of age or older with whom a person sixteen years of age or older has or has had a dating relationship. "Family or household member" also includes an "intimate partner" as defined in RCW 26.50.010.

.. Assault in the fourth degree occurring on or after March 18, 2020, where domestic violence against an "intimate partner" as defined in RCW 26.50.010 is pleaded and proven, is a class C felony if the person has two or more prior adult convictions within ten years for any of the following offenses occurring after July 23, 2017, where domestic violence against an "intimate partner" as defined in RCW 26.50.010 or domestic violence against a "family or household member" as defined in (a) of this subsection was pleaded and proven:

... Repetitive domestic violence offense as defined in RCW 9.94A.030;

... Crime of harassment as defined by RCW 9A.46.060;

... Assault in the third degree;

... Assault in the second degree;

.. Assault in the first degree; or

.. A municipal, tribal, federal, or out-of-state offense comparable to any offense under (b)(i) through (v) of this subsection.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2473-S.SL.pdf?cite=2020%20c%2029%20§%207[2020 c 29 § 7]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1163-S2.SL.pdf?cite=2017%20c%20272%20§%201[2017 c 272 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c188.pdf?cite=1987%20c%20188%20§%202[1987 c 188 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c257.pdf?cite=1986%20c%20257%20§%207[1986 c 257 § 7]; ]

== 9A.36.045 - Drive-by shooting.
. A person is guilty of drive-by shooting when he or she recklessly discharges a firearm as defined in RCW 9.41.010 in a manner which creates a substantial risk of death or serious physical injury to another person and the discharge is either from a motor vehicle or from the immediate area of a motor vehicle that was used to transport the shooter or the firearm, or both, to the scene of the discharge.

. A person who unlawfully discharges a firearm from a moving motor vehicle may be inferred to have engaged in reckless conduct, unless the discharge is shown by evidence satisfactory to the trier of fact to have been made without such recklessness.

. Drive-by shooting is a class B felony.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3900-S3.SL.pdf?cite=1997%20c%20338%20§%2044[1997 c 338 § 44]; 1995 c 129 § 8 (Initiative Measure No. 159); 1994 sp.s. c 7 § 511;  1995 c 129 § 19 (Initiative Measure No. 159; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20109[1989 c 271 § 109]; ]

== 9A.36.050 - Reckless endangerment.
. A person is guilty of reckless endangerment when he or she recklessly engages in conduct not amounting to drive-by shooting but that creates a substantial risk of death or serious physical injury to another person.

. Reckless endangerment is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3900-S3.SL.pdf?cite=1997%20c%20338%20§%2045[1997 c 338 § 45]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c271.pdf?cite=1989%20c%20271%20§%20110[1989 c 271 § 110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.36.050[1975 1st ex.s. c 260 § 9A.36.050]; ]

== 9A.36.060 - Promoting a suicide attempt.
. A person is guilty of promoting a suicide attempt when he or she knowingly causes or aids another person to attempt suicide.

. Promoting a suicide attempt is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20360[2011 c 336 § 360]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.36.060[1975 1st ex.s. c 260 § 9A.36.060]; ]

== 9A.36.070 - Coercion.
. A person is guilty of coercion if by use of a threat he or she compels or induces a person to engage in conduct which the latter has a legal right to abstain from, or to abstain from conduct which he or she has a legal right to engage in.

. "Threat" as used in this section means:

.. To communicate, directly or indirectly, the intent immediately to use force against any person who is present at the time; or

.. Threats as defined in *RCW 9A.04.110(27) (a), (b), or (c).

. Coercion is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20361[2011 c 336 § 361]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.36.070[1975 1st ex.s. c 260 § 9A.36.070]; ]

== 9A.36.078 - Hate crime offenses—Finding.
The legislature finds that crimes and threats against persons because of their race, color, religion, ancestry, national origin, gender, sexual orientation, gender expression or identity, or mental, physical, or sensory disabilities are serious and increasing. The legislature also finds that crimes and threats are often directed against interracial couples and their children or couples of mixed religions, colors, ancestries, or national origins because of bias and bigotry against the race, color, religion, ancestry, or national origin of one person in the couple or family. The legislature finds that the state interest in preventing crimes and threats motivated by bigotry and bias goes beyond the state interest in preventing other felonies or misdemeanors such as criminal trespass, malicious mischief, assault, or other crimes that are not motivated by hatred, bigotry, and bias, and that prosecution of those other crimes inadequately protects citizens from crimes and threats motivated by bigotry and bias. Therefore, the legislature finds that protection of those citizens from threats of harm due to bias and bigotry is a compelling state interest.

The legislature also finds that in many cases, certain discrete words or symbols are used to threaten the victims. Those discrete words or symbols have historically or traditionally been used to connote hatred or threats towards members of the class of which the victim or a member of the victim's family or household is a member. In particular, the legislature finds that cross burnings historically and traditionally have been used to threaten, terrorize, intimidate, and harass African Americans and their families. Cross burnings often preceded lynchings, murders, burning of homes, and other acts of terror. Further, Nazi swastikas historically and traditionally have been used to threaten, terrorize, intimidate, and harass Jewish people and their families. Swastikas symbolize the massive destruction of the Jewish population, commonly known as the holocaust. Therefore, the legislature finds that any person who burns or attempts to burn a cross or displays a swastika on the property of the victim or burns a cross or displays a swastika as part of a series of acts directed towards a particular person, the person's family or household members, or a particular group, knows or reasonably should know that the cross burning or swastika may create a reasonable fear of harm in the mind of the person, the person's family and household members, or the group.

The legislature also finds that attacks on religious places of worship and threatening defacement of religious texts have increased, as have assaults and attacks on those who visibly self-identify as members of a religious minority, such as by wearing religious head covering or other visible articles of faith. The legislature finds that any person who defaces religious real property with derogatory words, symbols, or items, who places a vandalized or defaced religious item or scripture on the property of a victim, or who attacks or attempts to remove the religious garb or faith-based attire of a victim, knows or reasonably should know that such actions create a reasonable fear of harm in the mind of the victim.

The legislature also finds that a hate crime committed against a victim because of the victim's gender may be identified in the same manner that a hate crime committed against a victim of another protected group is identified. Affirmative indications of hatred towards gender as a class is the predominant factor to consider. Other factors to consider include the perpetrator's use of language, slurs, or symbols expressing hatred towards the victim's gender as a class; the severity of the attack including mutilation of the victim's sexual organs; a history of similar attacks against victims of the same gender by the perpetrator or a history of similar incidents in the same area; a lack of provocation; an absence of any other apparent motivation; and common sense.

The legislature recognizes that, since 2015, Washington state has experienced a sharp increase in malicious harassment offenses, and, in response, the legislature intends to rename the offense to its more commonly understood title of "hate crime offense" and create a multidisciplinary working group to establish recommendations for best practices for identifying and responding to hate crimes.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1732-S.SL.pdf?cite=2019%20c%20271%20§%201[2019 c 271 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1569-S.SL.pdf?cite=1993%20c%20127%20§%201[1993 c 127 § 1]; ]

== 9A.36.080 - Hate crime offense—Definition and criminal penalty.
. A person is guilty of a hate crime offense if he or she maliciously and intentionally commits one of the following acts because of his or her perception of the victim's race, color, religion, ancestry, national origin, gender, sexual orientation, gender expression or identity, or mental, physical, or sensory disability:

.. Causes physical injury to the victim or another person;

.. Causes physical damage to or destruction of the property of the victim or another person; or

.. Threatens a specific person or group of persons and places that person, or members of the specific group of persons, in reasonable fear of harm to person or property. The fear must be a fear that a reasonable person would have under all the circumstances. For purposes of this section, a "reasonable person" is a reasonable person who is a member of the victim's race, color, religion, ancestry, national origin, gender, or sexual orientation, or who has the same gender expression or identity, or the same mental, physical, or sensory disability as the victim. Words alone do not constitute a hate crime offense unless the context or circumstances surrounding the words indicate the words are a threat. Threatening words do not constitute a hate crime offense if it is apparent to the victim that the person does not have the ability to carry out the threat.

. In any prosecution for a hate crime offense, unless evidence exists which explains to the trier of fact's satisfaction that the person did not intend to threaten the victim or victims, the trier of fact may infer that the person intended to threaten a specific victim or group of victims because of the person's perception of the victim's or victims' race, color, religion, ancestry, national origin, gender, sexual orientation, gender expression or identity, or mental, physical, or sensory disability if the person commits one of the following acts:

.. Burns a cross on property of a victim who is or whom the actor perceives to be of African American heritage;

.. Defaces property of a victim who is or whom the actor perceives to be of Jewish heritage by defacing the property with a swastika;

.. Defaces religious real property with words, symbols, or items that are derogatory to persons of the faith associated with the property;

.. Places a vandalized or defaced religious item or scripture on the property of a victim who is or whom the actor perceives to be of the faith with which that item or scripture is associated;

.. Damages, destroys, or defaces religious garb or other faith-based attire belonging to the victim or attempts to or successfully removes religious garb or other faith-based attire from the victim's person without the victim's authorization; or

.. Places a noose on the property of a victim who is or whom the actor perceives to be of a racial or ethnic minority group.

This subsection only applies to the creation of a reasonable inference for evidentiary purposes. This subsection does not restrict the state's ability to prosecute a person under subsection (1) of this section when the facts of a particular case do not fall within (a) through (f) of this subsection.

. It is not a defense that the accused was mistaken that the victim was a member of a certain race, color, religion, ancestry, national origin, gender, or sexual orientation, had a particular gender expression or identity, or had a mental, physical, or sensory disability.

. Evidence of expressions or associations of the accused may not be introduced as substantive evidence at trial unless the evidence specifically relates to the crime charged. Nothing in this chapter shall affect the rules of evidence governing impeachment of a witness.

. Every person who commits another crime during the commission of a crime under this section may be punished and prosecuted for the other crime separately.

. For the purposes of this section:

.. "Gender expression or identity" means having or being perceived as having a gender identity, self-image, appearance, behavior, or expression, whether or not that gender identity, self-image, appearance, behavior, or expression is different from that traditionally associated with the sex assigned to that person at birth.

.. "Sexual orientation" means heterosexuality, homosexuality, or bisexuality.

.. "Threat" means to communicate, directly or indirectly, the intent to:

... Cause bodily injury immediately or in the future to the person threatened or to any other person; or

... Cause physical damage immediately or in the future to the property of a person threatened or that of any other person.

. Commission of a hate crime offense is a class C felony.

. The penalties provided in this section for hate crime offenses do not preclude the victims from seeking any other remedies otherwise available under law.

. Nothing in this section confers or expands any civil rights or protections to any group or class identified under this section, beyond those rights or protections that exist under the federal or state Constitution or the civil laws of the state of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1732-S.SL.pdf?cite=2019%20c%20271%20§%202[2019 c 271 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6398-S.SL.pdf?cite=2010%20c%20119%20§%201[2010 c 119 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5952.SL.pdf?cite=2009%20c%20180%20§%201[2009 c 180 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1569-S.SL.pdf?cite=1993%20c%20127%20§%202[1993 c 127 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c95.pdf?cite=1989%20c%2095%20§%201[1989 c 95 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c268.pdf?cite=1984%20c%20268%20§%201[1984 c 268 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c267.pdf?cite=1981%20c%20267%20§%201[1981 c 267 § 1]; ]

== 9A.36.083 - Hate crime offense—Civil action.
In addition to the criminal penalty provided in RCW 9A.36.080 for committing a hate crime offense, the victim may bring a civil cause of action for the hate crime offense against the person who committed the offense. A person may be liable to the victim of the hate crime offense for actual damages, punitive damages of up to one hundred thousand dollars, and reasonable attorneys' fees and costs incurred in bringing the action.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1732-S.SL.pdf?cite=2019%20c%20271%20§%203[2019 c 271 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1569-S.SL.pdf?cite=1993%20c%20127%20§%203[1993 c 127 § 3]; ]

== 9A.36.090 - Threats against governor or family.
. Whoever knowingly and willfully deposits for conveyance in the mail or for a delivery from any post office or by any letter carrier any letter, paper, writing, print, missive, or document containing any threat to take the life of or to inflict bodily harm upon the governor of the state or his or her immediate family, the governor-elect, the lieutenant governor, other officer next in the order of succession to the office of governor of the state, or the lieutenant governor-elect, or knowingly and willfully otherwise makes any such threat against the governor, governor-elect, lieutenant governor, other officer next in the order of succession to the office of governor, or lieutenant governor-elect, shall be guilty of a class C felony.

. As used in this section, the term "governor-elect" and "lieutenant governor-elect" means such persons as are the successful candidates for the offices of governor and lieutenant governor, respectively, as ascertained from the results of the general election. As used in this section, the phrase "other officer next in the order of succession to the office of governor" means the person other than the lieutenant governor next in order of succession to the office of governor under Article 3, section 10 of the state Constitution.

. The Washington state patrol may investigate for violations of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20362[2011 c 336 § 362]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c185.pdf?cite=1982%20c%20185%20§%201[1982 c 185 § 1]; ]

== 9A.36.100 - Custodial assault.
. A person is guilty of custodial assault if that person is not guilty of an assault in the first or second degree and where the person:

.. Assaults a full or part-time staff member or volunteer, any educational personnel, any personal service provider, or any vendor or agent thereof at any juvenile corrections institution or local juvenile detention facilities who was performing official duties at the time of the assault;

.. Assaults a full or part-time staff member or volunteer, any educational personnel, any personal service provider, or any vendor or agent thereof at any adult corrections institution or local adult detention facilities who was performing official duties at the time of the assault;

.. [Empty]
... Assaults a full or part-time community correction officer while the officer is performing official duties; or

... Assaults any other full or part-time employee who is employed in a community corrections office while the employee is performing official duties; or

.. Assaults any volunteer who was assisting a person described in (c) of this subsection at the time of the assault.

. Custodial assault is a class C felony.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c151.pdf?cite=1988%20c%20151%20§%201[1988 c 151 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c188.pdf?cite=1987%20c%20188%20§%201[1987 c 188 § 1]; ]

== 9A.36.120 - Assault of a child in the first degree.
. A person eighteen years of age or older is guilty of the crime of assault of a child in the first degree if the child is under the age of thirteen and the person:

.. Commits the crime of assault in the first degree, as defined in RCW 9A.36.011, against the child; or

.. Intentionally assaults the child and either:

... Recklessly inflicts great bodily harm; or

... Causes substantial bodily harm, and the person has previously engaged in a pattern or practice either of (A) assaulting the child which has resulted in bodily harm that is greater than transient physical pain or minor temporary marks, or (B) causing the child physical pain or agony that is equivalent to that produced by torture.

. Assault of a child in the first degree is a class A felony.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6104-S.SL.pdf?cite=1992%20c%20145%20§%201[1992 c 145 § 1]; ]

== 9A.36.130 - Assault of a child in the second degree.
. A person eighteen years of age or older is guilty of the crime of assault of a child in the second degree if the child is under the age of thirteen and the person:

.. Commits the crime of assault in the second degree, as defined in RCW 9A.36.021, against a child; or

.. Intentionally assaults the child and causes bodily harm that is greater than transient physical pain or minor temporary marks, and the person has previously engaged in a pattern or practice either of (i) assaulting the child which has resulted in bodily harm that is greater than transient pain or minor temporary marks, or (ii) causing the child physical pain or agony that is equivalent to that produced by torture.

. Assault of a child in the second degree is a class B felony.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6104-S.SL.pdf?cite=1992%20c%20145%20§%202[1992 c 145 § 2]; ]

== 9A.36.140 - Assault of a child in the third degree.
. A person eighteen years of age or older is guilty of the crime of assault of a child in the third degree if the child is under the age of thirteen and the person commits the crime of assault in the third degree as defined in RCW 9A.36.031(1) (d) or (f) against the child.

. Assault of a child in the third degree is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6104-S.SL.pdf?cite=1992%20c%20145%20§%203[1992 c 145 § 3]; ]

== 9A.36.150 - Interfering with the reporting of domestic violence.
. A person commits the crime of interfering with the reporting of domestic violence if the person:

.. Commits a crime of domestic violence, as defined in RCW 10.99.020; and

.. Prevents or attempts to prevent the victim of or a witness to that domestic violence crime from calling a 911 emergency communication system, obtaining medical assistance, or making a report to any law enforcement official.

. Commission of a crime of domestic violence under subsection (1) of this section is a necessary element of the crime of interfering with the reporting of domestic violence.

. Interference with the reporting of domestic violence is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2472.SL.pdf?cite=1996%20c%20248%20§%203[1996 c 248 § 3]; ]

== 9A.36.160 - Failing to summon assistance.
A person is guilty of the crime of failing to summon assistance if:

. He or she was present when a crime was committed against another person; and

. He or she knows that the other person has suffered substantial bodily harm as a result of the crime committed against the other person and that the other person is in need of assistance; and

. He or she could reasonably summon assistance for the person in need without danger to himself or herself and without interference with an important duty owed to a third party; and

. He or she fails to summon assistance for the person in need; and

. Another person is not summoning or has not summoned assistance for the person in need of such assistance.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1236-S.SL.pdf?cite=2005%20c%20209%20§%201[2005 c 209 § 1]; ]

== 9A.36.161 - Failing to summon assistance—Penalty.
A violation of RCW 9A.36.160 is a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1236-S.SL.pdf?cite=2005%20c%20209%20§%202[2005 c 209 § 2]; ]

