= 9A.32 - Homicide.
:toc:

== 9A.32.010 - Homicide defined.
Homicide is the killing of a human being by the act, procurement, or omission of another, death occurring at any time, and is either (1) murder, (2) homicide by abuse, (3) manslaughter, (4) excusable homicide, or (5) justifiable homicide.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5044-S.SL.pdf?cite=1997%20c%20196%20§%203[1997 c 196 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c187.pdf?cite=1987%20c%20187%20§%202[1987 c 187 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c10.pdf?cite=1983%20c%2010%20§%201[1983 c 10 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.32.010[1975 1st ex.s. c 260 § 9A.32.010]; ]

== 9A.32.020 - Premeditation—Limitations.
. As used in this chapter, the premeditation required in order to support a conviction of the crime of murder in the first degree must involve more than a moment in point of time.

. Nothing contained in this chapter shall affect RCW 46.61.520.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.32.020[1975 1st ex.s. c 260 § 9A.32.020]; ]

== 9A.32.030 - Murder in the first degree.
. A person is guilty of murder in the first degree when:

.. With a premeditated intent to cause the death of another person, he or she causes the death of such person or of a third person; or

.. Under circumstances manifesting an extreme indifference to human life, he or she engages in conduct which creates a grave risk of death to any person, and thereby causes the death of a person; or

.. He or she commits or attempts to commit the crime of either (1) robbery in the first or second degree, (2) rape in the first or second degree, (3) burglary in the first degree, (4) arson in the first or second degree, or (5) kidnapping in the first or second degree, and in the course of or in furtherance of such crime or in immediate flight therefrom, he or she, or another participant, causes the death of a person other than one of the participants: Except that in any prosecution under this subdivision (1)(c) in which the defendant was not the only participant in the underlying crime, if established by the defendant by a preponderance of the evidence, it is a defense that the defendant:

... Did not commit the homicidal act or in any way solicit, request, command, importune, cause, or aid the commission thereof; and

... Was not armed with a deadly weapon, or any instrument, article, or substance readily capable of causing death or serious physical injury; and

... Had no reasonable grounds to believe that any other participant was armed with such a weapon, instrument, article, or substance; and

... Had no reasonable grounds to believe that any other participant intended to engage in conduct likely to result in death or serious physical injury.

. Murder in the first degree is a class A felony.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c200.pdf?cite=1990%20c%20200%20§%201[1990 c 200 § 1]; 1975-'76 2nd ex.s. c 38 § 3; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.32.030[1975 1st ex.s. c 260 § 9A.32.030]; ]

== 9A.32.040 - Murder in the first degree—Sentence.
Notwithstanding RCW 9A.32.030(2), any person convicted of the crime of murder in the first degree shall be sentenced to life imprisonment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c10.pdf?cite=1982%20c%2010%20§%202[1982 c 10 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c138.pdf?cite=1981%20c%20138%20§%2021[1981 c 138 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c206.pdf?cite=1977%20ex.s.%20c%20206%20§%203[1977 ex.s. c 206 § 3]; 1975 1st ex.s. c 260 § 9A.32.040.  1981 c 136 § 55;  1982 c 10 § 18; ]

== 9A.32.050 - Murder in the second degree.
. A person is guilty of murder in the second degree when:

.. With intent to cause the death of another person but without premeditation, he or she causes the death of such person or of a third person; or

.. He or she commits or attempts to commit any felony, including assault, other than those enumerated in RCW 9A.32.030(1)(c), and, in the course of and in furtherance of such crime or in immediate flight therefrom, he or she, or another participant, causes the death of a person other than one of the participants; except that in any prosecution under this subdivision (1)(b) in which the defendant was not the only participant in the underlying crime, if established by the defendant by a preponderance of the evidence, it is a defense that the defendant:

... Did not commit the homicidal act or in any way solicit, request, command, importune, cause, or aid the commission thereof; and

... Was not armed with a deadly weapon, or any instrument, article, or substance readily capable of causing death or serious physical injury; and

... Had no reasonable grounds to believe that any other participant was armed with such a weapon, instrument, article, or substance; and

... Had no reasonable grounds to believe that any other participant intended to engage in conduct likely to result in death or serious physical injury.

. Murder in the second degree is a class A felony.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5001.SL.pdf?cite=2003%20c%203%20§%202[2003 c 3 § 2]; 1975-'76 2nd ex.s. c 38 § 4; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.32.050[1975 1st ex.s. c 260 § 9A.32.050]; ]

== 9A.32.055 - Homicide by abuse.
. A person is guilty of homicide by abuse if, under circumstances manifesting an extreme indifference to human life, the person causes the death of a child or person under sixteen years of age, a developmentally disabled person, or a dependent adult, and the person has previously engaged in a pattern or practice of assault or torture of said child, person under sixteen years of age, developmentally disabled person, or dependent person.

. As used in this section, "dependent adult" means a person who, because of physical or mental disability, or because of extreme advanced age, is dependent upon another person to provide the basic necessities of life.

. Homicide by abuse is a class A felony.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c187.pdf?cite=1987%20c%20187%20§%201[1987 c 187 § 1]; ]

== 9A.32.060 - Manslaughter in the first degree.
. A person is guilty of manslaughter in the first degree when:

.. He or she recklessly causes the death of another person; or

.. He or she intentionally and unlawfully kills an unborn quick child by inflicting any injury upon the mother of such child.

. Manslaughter in the first degree is a class A felony.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20357[2011 c 336 § 357]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5938.SL.pdf?cite=1997%20c%20365%20§%205[1997 c 365 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.32.060[1975 1st ex.s. c 260 § 9A.32.060]; ]

== 9A.32.070 - Manslaughter in the second degree.
. A person is guilty of manslaughter in the second degree when, with criminal negligence, he or she causes the death of another person.

. Manslaughter in the second degree is a class B felony.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20358[2011 c 336 § 358]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5938.SL.pdf?cite=1997%20c%20365%20§%206[1997 c 365 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.32.070[1975 1st ex.s. c 260 § 9A.32.070]; ]

