= 9A.49 - Lasers.
:toc:

== 9A.49.001 - Findings.
The legislature finds that lasers are becoming both less expensive and more accessible in our technologically advanced society. Laser devices are being used by individuals in a manner so as to intimidate and harass. This creates an especially serious problem for law enforcement officers who reasonably believe they are the target of a laser sighting device on a firearm. Additionally, emergency service providers, service providers, and others who operate aircraft or motor vehicles may be negatively affected to the point of jeopardizing their safety as well as the safety of others. In order to address the misuse of lasers, the legislature hereby finds it necessary to criminalize the discharge of lasers under certain circumstances.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2086-S.SL.pdf?cite=1999%20c%20180%20§%201[1999 c 180 § 1]; ]

== 9A.49.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Aircraft" means any contrivance known or hereafter invented, used, or designed for navigation of or flight in air.

. "Laser" means any device designed or used to amplify electromagnetic radiation by simulated [stimulated] emission which is visible to the human eye.

. "Laser sighting system or device" means any system or device which is integrated with or affixed to a firearm and which emits a laser light beam that is used by the shooter to assist in the sight alignment of that firearm.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2086-S.SL.pdf?cite=1999%20c%20180%20§%202[1999 c 180 § 2]; ]

== 9A.49.020 - Unlawful discharge of a laser in the first degree.
. A person is guilty of unlawful discharge of a laser in the first degree if he or she knowingly and maliciously discharges a laser, under circumstances not amounting to malicious mischief in the first degree:

.. At a law enforcement officer or other employee of a law enforcement agency who is performing his or her official duties in uniform or exhibiting evidence of his or her authority, and in a manner that would support that officer's or employee's reasonable belief that he or she is targeted with a laser sighting device or system; or

.. At a law enforcement officer or other employee of a law enforcement agency who is performing his or her official duties, causing an impairment of the safety or operation of a law enforcement vehicle or causing an interruption or impairment of service rendered to the public by negatively affecting the officer or employee; or

.. At a pilot, causing an impairment of the safety or operation of an aircraft or causing an interruption or impairment of service rendered to the public by negatively affecting the pilot; or

.. At a firefighter or other employee of a fire department, county fire marshal's office, county fire prevention bureau, or fire protection district who is performing his or her official duties, causing an impairment of the safety or operation of an emergency vehicle or causing an interruption or impairment of service rendered to the public by negatively affecting the firefighter or employee; or

.. At a transit operator or driver of a public or private transit company while that person is performing his or her official duties, causing an impairment of the safety or operation of a transit vehicle or causing an interruption or impairment of service rendered to the public by negatively affecting the operator or driver; or

.. At a school bus driver employed by a school district or private company while the driver is performing his or her official duties, causing an impairment of the safety or operation of a school bus or causing an interruption or impairment of service by negatively affecting the bus driver.

. Except as provided in RCW 9A.49.040, unlawful discharge of a laser in the first degree is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2086-S.SL.pdf?cite=1999%20c%20180%20§%203[1999 c 180 § 3]; ]

== 9A.49.030 - Unlawful discharge of a laser in the second degree.
. A person is guilty of unlawful discharge of a laser in the second degree if he or she knowingly and maliciously discharges a laser, under circumstances not amounting to unlawful discharge of a laser in the first degree or malicious mischief in the first or second degree:

.. At a person, not described in RCW 9A.49.020(1) (a) through (f), who is operating a motor vehicle at the time, causing an impairment of the safety or operation of a motor vehicle by negatively affecting the driver; or

.. At a person described in RCW 9A.49.020(1) (b) through (f), causing a substantial risk of an impairment or interruption as described in RCW 9A.49.020(1) (b) through (f); or

.. At a person in order to intimidate or threaten that person.

. Except as provided in RCW 9A.49.040, unlawful discharge of a laser in the second degree is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2086-S.SL.pdf?cite=1999%20c%20180%20§%204[1999 c 180 § 4]; ]

== 9A.49.040 - Civil infraction, when.
Unlawful discharge of a laser in the first degree or second degree is a civil infraction if committed by a juvenile who has not before committed either offense. The monetary penalty imposed upon a juvenile may not exceed one hundred dollars.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2086-S.SL.pdf?cite=1999%20c%20180%20§%205[1999 c 180 § 5]; ]

== 9A.49.050 - Exclusions.
This chapter does not apply to the conduct of a laser development activity by or on behalf of the United States armed forces.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2086-S.SL.pdf?cite=1999%20c%20180%20§%206[1999 c 180 § 6]; ]

