= 9A.48 - Arson, reckless burning, and malicious mischief.
:toc:

== 9A.48.010 - Definitions.
. For the purpose of this chapter, unless the context indicates otherwise:

.. "Building" has the definition in RCW 9A.04.110(5), and where a building consists of two or more units separately secured or occupied, each unit shall not be treated as a separate building;

.. "Damages", in addition to its ordinary meaning, includes any charring, scorching, burning, or breaking, or agricultural or industrial sabotage, and shall include any diminution in the value of any property as a consequence of an act;

.. "Property of another" means property in which the actor possesses anything less than exclusive ownership.

. To constitute arson it is not necessary that a person other than the actor has ownership in the building or structure damaged or set on fire.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6422-S.SL.pdf?cite=2002%20c%2032%20§%201[2002 c 32 § 1]; 1975-'76 2nd ex.s. c 38 § 6; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.48.010[1975 1st ex.s. c 260 § 9A.48.010]; ]

== 9A.48.020 - Arson in the first degree.
. A person is guilty of arson in the first degree if he or she knowingly and maliciously:

.. Causes a fire or explosion which is manifestly dangerous to any human life, including firefighters; or

.. Causes a fire or explosion which damages a dwelling; or

.. Causes a fire or explosion in any building in which there shall be at the time a human being who is not a participant in the crime; or

.. Causes a fire or explosion on property valued at ten thousand dollars or more with intent to collect insurance proceeds.

. Arson in the first degree is a class A felony.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5063.SL.pdf?cite=2007%20c%20218%20§%2063[2007 c 218 § 63]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c203.pdf?cite=1981%20c%20203%20§%202[1981 c 203 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.48.020[1975 1st ex.s. c 260 § 9A.48.020]; ]

== 9A.48.030 - Arson in the second degree.
. A person is guilty of arson in the second degree if he or she knowingly and maliciously causes a fire or explosion which damages a building, or any structure or erection appurtenant to or joining any building, or any wharf, dock, machine, engine, automobile, or other motor vehicle, watercraft, aircraft, bridge, or trestle, or hay, grain, crop, or timber, whether cut or standing or any range land, or pasture land, or any fence, or any lumber, shingle, or other timber products, or any property.

. Arson in the second degree is a class B felony.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20366[2011 c 336 § 366]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.48.030[1975 1st ex.s. c 260 § 9A.48.030]; ]

== 9A.48.040 - Reckless burning in the first degree.
. A person is guilty of reckless burning in the first degree if he or she recklessly damages a building or other structure or any vehicle, railway car, aircraft, or watercraft or any hay, grain, crop, or timber whether cut or standing, by knowingly causing a fire or explosion.

. Reckless burning in the first degree is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20367[2011 c 336 § 367]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.48.040[1975 1st ex.s. c 260 § 9A.48.040]; ]

== 9A.48.050 - Reckless burning in the second degree.
. A person is guilty of reckless burning in the second degree if he or she knowingly causes a fire or explosion, whether on his or her own property or that of another, and thereby recklessly places a building or other structure, or any vehicle, railway car, aircraft, or watercraft, or any hay, grain, crop or timber, whether cut or standing, in danger of destruction or damage.

. Reckless burning in the second degree is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20368[2011 c 336 § 368]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.48.050[1975 1st ex.s. c 260 § 9A.48.050]; ]

== 9A.48.060 - Reckless burning—Defense.
In any prosecution for the crime of reckless burning in the first or second degrees, it shall be a defense if the defendant establishes by a preponderance of the evidence that:

.. No person other than the defendant had a possessory, or pecuniary interest in the damaged or endangered property, or if other persons had such an interest, all of them consented to the defendant's conduct; and

.. The defendant's sole intent was to destroy or damage the property for a lawful purpose.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.48.060[1975 1st ex.s. c 260 § 9A.48.060]; ]

== 9A.48.070 - Malicious mischief in the first degree.
. A person is guilty of malicious mischief in the first degree if he or she knowingly and maliciously:

.. Causes physical damage to the property of another in an amount exceeding five thousand dollars;

.. Causes an interruption or impairment of service rendered to the public by physically damaging or tampering with an emergency vehicle or property of the state, a political subdivision thereof, or a public utility or mode of public transportation, power, or communication;

.. Causes an impairment of the safety, efficiency, or operation of an aircraft by physically damaging or tampering with the aircraft or aircraft equipment, fuel, lubricant, or parts; or

.. Causes an interruption or impairment of service rendered to the public by, without lawful authority, physically damaging, destroying, or removing an official ballot deposit box or ballot drop box or, without lawful authority, damaging, destroying, removing, or tampering with the contents thereof.

. Malicious mischief in the first degree is a class B felony.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5336.SL.pdf?cite=2017%20c%20283%20§%201[2017 c 283 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6167.SL.pdf?cite=2009%20c%20431%20§%204[2009 c 431 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c4.pdf?cite=1983%201st%20ex.s.%20c%204%20§%201[1983 1st ex.s. c 4 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.48.070[1975 1st ex.s. c 260 § 9A.48.070]; ]

== 9A.48.080 - Malicious mischief in the second degree.
. A person is guilty of malicious mischief in the second degree if he or she knowingly and maliciously:

.. Causes physical damage to the property of another in an amount exceeding seven hundred fifty dollars;

.. Creates a substantial risk of interruption or impairment of service rendered to the public, by physically damaging or tampering with an emergency vehicle or property of the state, a political subdivision thereof, or a public utility or mode of public transportation, power, or communication; or

.. Creates a substantial risk of interruption or impairment of service rendered to the public by, without lawful authority, physically damaging, destroying, or removing an official ballot deposit box or ballot drop box or, without lawful authority, damaging, destroying, removing, or tampering with the contents thereof.

. Malicious mischief in the second degree is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5336.SL.pdf?cite=2017%20c%20283%20§%202[2017 c 283 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6167.SL.pdf?cite=2009%20c%20431%20§%205[2009 c 431 § 5]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1652-S.SL.pdf?cite=1994%20c%20261%20§%2017[1994 c 261 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c145.pdf?cite=1979%20c%20145%20§%202[1979 c 145 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.48.080[1975 1st ex.s. c 260 § 9A.48.080]; ]

== 9A.48.090 - Malicious mischief in the third degree.
. A person is guilty of malicious mischief in the third degree if he or she:

.. Knowingly and maliciously causes physical damage to the property of another, under circumstances not amounting to malicious mischief in the first or second degree; or

.. Writes, paints, or draws any inscription, figure, or mark of any type on any public or private building or other structure or any real or personal property owned by any other person unless the person has obtained the express permission of the owner or operator of the property, under circumstances not amounting to malicious mischief in the first or second degree.

. Malicious mischief in the third degree is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6167.SL.pdf?cite=2009%20c%20431%20§%206[2009 c 431 § 6]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%2071[2003 c 53 § 71]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6115.SL.pdf?cite=1996%20c%2035%20§%201[1996 c 35 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.48.090[1975 1st ex.s. c 260 § 9A.48.090]; ]

== 9A.48.100 - Malicious mischief—"Physical damage" defined.
For the purposes of RCW 9A.48.070 through 9A.48.090 inclusive:

. "Physical damage," in addition to its ordinary meaning, shall include the total or partial alteration, damage, obliteration, or erasure of records, information, data, computer programs, or their computer representations, which are recorded for use in computers or the impairment, interruption, or interference with the use of such records, information, data, or computer programs, or the impairment, interruption, or interference with the use of any computer or services provided by computers. "Physical damage" also includes any diminution in the value of any property as the consequence of an act and the cost to repair any physical damage;

. If more than one item of property is physically damaged as a result of a common scheme or plan by a person and the physical damage to the property would, when considered separately, constitute mischief in the third degree because of value, then the value of the damages may be aggregated in one count. If the sum of the value of all the physical damages exceeds two hundred fifty dollars, the defendant may be charged with and convicted of malicious mischief in the second degree.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1552-S.SL.pdf?cite=2013%20c%20322%20§%201[2013 c 322 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c273.pdf?cite=1984%20c%20273%20§%204[1984 c 273 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c260.pdf?cite=1981%20c%20260%20§%202[1981 c 260 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c244.pdf?cite=1979%20ex.s.%20c%20244%20§%2011[1979 ex.s. c 244 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c145.pdf?cite=1979%20c%20145%20§%203[1979 c 145 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c174.pdf?cite=1977%20ex.s.%20c%20174%20§%201[1977 ex.s. c 174 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.48.100[1975 1st ex.s. c 260 § 9A.48.100]; ]

== 9A.48.105 - Criminal street gang tagging and graffiti.
. A person is guilty of criminal street gang tagging and graffiti if he or she commits malicious mischief in the third degree under RCW 9A.48.090(1)(b) and he or she:

.. Has multiple current convictions for malicious mischief in the third degree offenses under RCW 9A.48.090(1)(b); or

.. Has previously been convicted for a malicious mischief in the third degree offense under RCW 9A.48.090(1)(b) or a comparable offense under a municipal code provision of any city or town; and

.. The current offense or one of the current offenses is a "criminal street gang-related offense" as defined in RCW 9.94A.030.

. Criminal street gang tagging and graffiti is a gross misdemeanor offense.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2712-S2.SL.pdf?cite=2008%20c%20276%20§%20306[2008 c 276 § 306]; ]

== 9A.48.110 - Defacing a state monument.
. A person is guilty of defacing a state monument if he or she knowingly defaces a monument or memorial on the state capitol campus or other state property.

. Defacing a state monument is a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1433.SL.pdf?cite=1995%20c%2066%20§%201[1995 c 66 § 1]; ]

== 9A.48.120 - Civil disorder training.
. A person is guilty of civil disorder training if he or she teaches or demonstrates to any other person the use, application, or making of any device or technique capable of causing significant bodily injury or death to persons, knowing, or having reason to know or intending that same will be unlawfully employed for use in, or in furtherance of, a civil disorder.

. Civil disorder training is a class B felony.

. Nothing in this section makes unlawful any act of any law enforcement officer that is performed in the lawful performance of his or her official duties.

. Nothing in this section makes unlawful any act of firearms training, target shooting, or other firearms activity, so long as it is not done for the purpose of furthering a civil disorder.

. For the purposes of this section:

.. "Civil disorder" means any public disturbance involving acts of violence that is intended to cause an immediate danger of, or to result in, significant injury to property or the person of any other individual.

.. "Law enforcement officer" means any law enforcement officer as defined in RCW 9A.76.020(2) including members of the Washington national guard, as defined in RCW 38.04.010.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5868.SL.pdf?cite=2008%20c%20206%20§%201[2008 c 206 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2505-S.SL.pdf?cite=2002%20c%20340%20§%201[2002 c 340 § 1]; ]

