= 9A.50 - Interference with health care facilities or providers.
:toc:

== 9A.50.005 - Finding.
The legislature finds that seeking or obtaining health care is fundamental to public health and safety.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1338-S.SL.pdf?cite=1993%20c%20128%20§%201[1993 c 128 § 1]; ]

== 9A.50.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Health care facility" means a facility that provides health care services directly to patients, including but not limited to, a hospital, clinic, health care provider's office, health maintenance organization, diagnostic or treatment center, neuropsychiatric or mental health facility, hospice, or nursing home.

. "Health care provider" has the same meaning as defined in RCW 7.70.020 (1) and (2), and also means an officer, director, employee, or agent of a health care facility who sues or testifies regarding matters within the scope of his or her employment.

. "Aggrieved" means:

.. A person, physically present at the health care facility when the prohibited actions occur, whose access is or is about to be obstructed or impeded;

.. A person, physically present at the health care facility when the prohibited actions occur, whose care is or is about to be disrupted;

.. The health care facility, its employees, or agents;

.. The owner of the health care facility or the building or property upon which the health care facility is located.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1338-S.SL.pdf?cite=1993%20c%20128%20§%202[1993 c 128 § 2]; ]

== 9A.50.020 - Interference with health care facility.
It is unlawful for a person except as otherwise protected by state or federal law, alone or in concert with others, to willfully or recklessly interfere with access to or from a health care facility or willfully or recklessly disrupt the normal functioning of such facility by:

. Physically obstructing or impeding the free passage of a person seeking to enter or depart from the facility or from the common areas of the real property upon which the facility is located;

. Making noise that unreasonably disturbs the peace within the facility;

. Trespassing on the facility or the common areas of the real property upon which the facility is located;

. Telephoning the facility repeatedly, or knowingly permitting any telephone under his or her control to be used for such purpose; or

. Threatening to inflict injury on the owners, agents, patients, employees, or property of the facility or knowingly permitting any telephone under his or her control to be used for such purpose.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1338-S.SL.pdf?cite=1993%20c%20128%20§%203[1993 c 128 § 3]; ]

== 9A.50.030 - Penalty.
. A violation of RCW 9A.50.020 is a gross misdemeanor. A person convicted of violating RCW 9A.50.020 shall be punished as follows:

.. For a first offense, a fine of not less than two hundred fifty dollars and a jail term of not less than twenty-four consecutive hours;

.. For a second offense, a fine of not less than five hundred dollars and a jail term of not less than seven consecutive days; and

.. For a third or subsequent offense, a fine of not less than one thousand dollars and a jail term of not less than thirty consecutive days.

. The fines imposed by this section apply to adult offenders only.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5564-S2.SL.pdf?cite=2015%20c%20265%20§%2017[2015 c 265 § 17]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1338-S.SL.pdf?cite=1993%20c%20128%20§%204[1993 c 128 § 4]; ]

== 9A.50.040 - Civil remedies.
. A person or health care facility aggrieved by the actions prohibited by RCW 9A.50.020 may seek civil damages from those who committed the prohibited acts and those acting in concert with them. A plaintiff in an action brought under this chapter shall not recover more than his or her actual damages and additional sums authorized in RCW 9A.50.050. Once a plaintiff recovers his or her actual damages and any additional sums authorized under this chapter, additional damages shall not be recovered. A person does not have to be criminally convicted of violating RCW 9A.50.020 to be held civilly liable under this section. It is not necessary to prove actual damages to recover the additional sums authorized under RCW 9A.50.050, costs, and attorneys' fees. The prevailing party is entitled to recover costs and attorneys' fees.

. The superior courts of this state shall have authority to grant temporary, preliminary, and permanent injunctive relief to enjoin violations of this chapter.

In appropriate circumstances, any superior court having personal jurisdiction over one or more defendants may issue injunctive relief that shall have binding effect on the original defendants and persons acting in concert with the original defendants, in any county in the state.

Due to the nature of the harm involved, injunctive relief may be issued without bond in the discretion of the court, notwithstanding any other requirement imposed by statute.

The state and its political subdivisions shall cooperate in the enforcement of court injunctions that seek to protect against acts prohibited by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1338-S.SL.pdf?cite=1993%20c%20128%20§%206[1993 c 128 § 6]; ]

== 9A.50.050 - Civil damages.
In a civil action brought under this chapter, an individual plaintiff aggrieved by the actions prohibited by RCW 9A.50.020 may be entitled to recover up to five hundred dollars for each day that the actions occurred, or up to five thousand dollars for each day that the actions occurred if the plaintiff aggrieved by the actions prohibited under RCW 9A.50.020 is a health care facility.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1338-S.SL.pdf?cite=1993%20c%20128%20§%207[1993 c 128 § 7]; ]

== 9A.50.060 - Informational picketing.
Nothing in RCW 9A.50.020 shall prohibit either lawful picketing or other publicity for the purpose of providing the public with information.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1338-S.SL.pdf?cite=1993%20c%20128%20§%208[1993 c 128 § 8]; ]

== 9A.50.070 - Protection of health care patients and providers.
A court having jurisdiction over a criminal or civil proceeding under this chapter shall take all steps reasonably necessary to safeguard the individual privacy and prevent harassment of a health care patient or health care provider who is a party or witness in a proceeding, including granting protective orders and orders in limine.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1338-S.SL.pdf?cite=1993%20c%20128%20§%209[1993 c 128 § 9]; ]

== 9A.50.900 - Construction.
Nothing in this chapter shall be construed to limit the right to seek other available criminal or civil remedies. The remedies provided in this chapter are cumulative, not exclusive.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1338-S.SL.pdf?cite=1993%20c%20128%20§%2011[1993 c 128 § 11]; ]

== 9A.50.902 - Effective date—1993 c 128.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and shall take effect immediately [April 26, 1993].

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1338-S.SL.pdf?cite=1993%20c%20128%20§%2014[1993 c 128 § 14]; ]

