= 9A.52 - Burglary and trespass.
:toc:

== 9A.52.010 - Definitions.
The following definitions apply in this chapter:

. "Enter." The word "enter" when constituting an element or part of a crime, shall include the entrance of the person, or the insertion of any part of his or her body, or any instrument or weapon held in his or her hand and used or intended to be used to threaten or intimidate a person or to detach or remove property.

. "Enters or remains unlawfully." A person "enters or remains unlawfully" in or upon premises when he or she is not then licensed, invited, or otherwise privileged to so enter or remain.

A license or privilege to enter or remain in a building which is only partly open to the public is not a license or privilege to enter or remain in that part of a building which is not open to the public. A person who enters or remains upon unimproved and apparently unused land, which is neither fenced nor otherwise enclosed in a manner designed to exclude intruders, does so with license and privilege unless notice against trespass is personally communicated to him or her by the owner of the land or some other authorized person, or unless notice is given by posting in a conspicuous manner. Land that is used for commercial aquaculture or for growing an agricultural crop or crops, other than timber, is not unimproved and apparently unused land if a crop or any other sign of cultivation is clearly visible or if notice is given by posting in a conspicuous manner. Similarly, a field fenced in any manner is not unimproved and apparently unused land. A license or privilege to enter or remain on improved and apparently used land that is open to the public at particular times, which is neither fenced nor otherwise enclosed in a manner to exclude intruders, is not a license or privilege to enter or remain on the land at other times if notice of prohibited times of entry is posted in a conspicuous manner.

. "Premises" includes any building, dwelling, structure used for commercial aquaculture, or any real property.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2375-S2.SL.pdf?cite=2016%20c%20164%20§%2012[2016 c 164 § 12]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20369[2011 c 336 § 369]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6357.SL.pdf?cite=2004%20c%2069%20§%201[2004 c 69 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c289.pdf?cite=1985%20c%20289%20§%201[1985 c 289 § 1]; prior:  1984 c 273 § 5; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c49.pdf?cite=1984%20c%2049%20§%201[1984 c 49 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.52.010[1975 1st ex.s. c 260 § 9A.52.010]; ]

== 9A.52.020 - Burglary in the first degree.
. A person is guilty of burglary in the first degree if, with intent to commit a crime against a person or property therein, he or she enters or remains unlawfully in a building and if, in entering or while in the building or in immediate flight therefrom, the actor or another participant in the crime (a) is armed with a deadly weapon, or (b) assaults any person.

. Burglary in the first degree is a class A felony.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5050-S.SL.pdf?cite=1996%20c%2015%20§%201[1996 c 15 § 1]; 1995 c 129 § 9 (Initiative Measure No. 159); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.52.020[1975 1st ex.s. c 260 § 9A.52.020]; ]

== 9A.52.025 - Residential burglary.
. A person is guilty of residential burglary if, with intent to commit a crime against a person or property therein, the person enters or remains unlawfully in a dwelling other than a vehicle.

. Residential burglary is a class B felony. In establishing sentencing guidelines and disposition standards, residential burglary is to be considered a more serious offense than second degree burglary.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5891-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2040%20§%2038[2011 1st sp.s. c 40 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex2c1.pdf?cite=1989%202nd%20ex.s.%20c%201%20§%201[1989 2nd ex.s. c 1 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c412.pdf?cite=1989%20c%20412%20§%201[1989 c 412 § 1]; ]

== 9A.52.030 - Burglary in the second degree.
. A person is guilty of burglary in the second degree if, with intent to commit a crime against a person or property therein, he or she enters or remains unlawfully in a building other than a vehicle or a dwelling.

. Burglary in the second degree is a class B felony.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20370[2011 c 336 § 370]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex2c1.pdf?cite=1989%202nd%20ex.s.%20c%201%20§%202[1989 2nd ex.s. c 1 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c412.pdf?cite=1989%20c%20412%20§%202[1989 c 412 § 2]; 1975-'76 2nd ex.s. c 38 § 7; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.52.030[1975 1st ex.s. c 260 § 9A.52.030]; ]

== 9A.52.040 - Inference of intent.
In any prosecution for burglary, any person who enters or remains unlawfully in a building may be inferred to have acted with intent to commit a crime against a person or property therein, unless such entering or remaining shall be explained by evidence satisfactory to the trier of fact to have been made without such criminal intent.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.52.040[1975 1st ex.s. c 260 § 9A.52.040]; ]

== 9A.52.050 - Other crime in committing burglary punishable.
Every person who, in the commission of a burglary shall commit any other crime, may be punished therefor as well as for the burglary, and may be prosecuted for each crime separately.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.52.050[1975 1st ex.s. c 260 § 9A.52.050]; ]

== 9A.52.060 - Making or having burglar tools.
. Every person who shall make or mend or cause to be made or mended, or have in his or her possession, any engine, machine, tool, false key, pick lock, bit, nippers, or implement adapted, designed, or commonly used for the commission of burglary under circumstances evincing an intent to use or employ, or allow the same to be used or employed in the commission of a burglary, or knowing that the same is intended to be so used, shall be guilty of making or having burglar tools.

. Making or having burglar tools is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20371[2011 c 336 § 371]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.52.060[1975 1st ex.s. c 260 § 9A.52.060]; ]

== 9A.52.070 - Criminal trespass in the first degree.
. A person is guilty of criminal trespass in the first degree if he or she knowingly enters or remains unlawfully in a building.

. Criminal trespass in the first degree is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20372[2011 c 336 § 372]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c244.pdf?cite=1979%20ex.s.%20c%20244%20§%2012[1979 ex.s. c 244 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.52.070[1975 1st ex.s. c 260 § 9A.52.070]; ]

== 9A.52.080 - Criminal trespass in the second degree.
. A person is guilty of criminal trespass in the second degree if he or she knowingly enters or remains unlawfully in or upon premises of another under circumstances not constituting criminal trespass in the first degree.

. Criminal trespass in the second degree is a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20373[2011 c 336 § 373]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c244.pdf?cite=1979%20ex.s.%20c%20244%20§%2013[1979 ex.s. c 244 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.52.080[1975 1st ex.s. c 260 § 9A.52.080]; ]

== 9A.52.090 - Criminal trespass—Defenses.
In any prosecution under RCW 9A.52.070 and 9A.52.080, it is a defense that:

. A building involved in an offense under RCW 9A.52.070 was abandoned; or

. The premises were at the time open to members of the public and the actor complied with all lawful conditions imposed on access to or remaining in the premises; or

. The actor reasonably believed that the owner of the premises, or other person empowered to license access thereto, would have licensed him or her to enter or remain; or

. The actor was attempting to serve legal process which includes any document required or allowed to be served upon persons or property, by any statute, rule, ordinance, regulation, or court order, excluding delivery by the mails of the United States. This defense applies only if the actor did not enter into a private residence or other building not open to the public and the entry onto the premises was reasonable and necessary for service of the legal process.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20374[2011 c 336 § 374]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c219.pdf?cite=1986%20c%20219%20§%202[1986 c 219 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.52.090[1975 1st ex.s. c 260 § 9A.52.090]; ]

== 9A.52.095 - Vehicle prowling in the first degree.
. A person is guilty of vehicle prowling in the first degree if, with intent to commit a crime against a person or property therein, he or she enters or remains unlawfully in a motor home, as defined in RCW 46.04.305, or in a vessel equipped for propulsion by mechanical means or by sail which has a cabin equipped with permanently installed sleeping quarters or cooking facilities.

. Vehicle prowling in the first degree is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20375[2011 c 336 § 375]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c47.pdf?cite=1982%201st%20ex.s.%20c%2047%20§%2013[1982 1st ex.s. c 47 § 13]; ]

== 9A.52.100 - Vehicle prowling in the second degree.
. A person is guilty of vehicle prowling in the second degree if, with intent to commit a crime against a person or property therein, he or she enters or remains unlawfully in a vehicle other than a motor home, as defined in RCW 46.04.305, or a vessel equipped for propulsion by mechanical means or by sail which has a cabin equipped with permanently installed sleeping quarters or cooking facilities.

. Except as provided in subsection (3) of this section, vehicle prowling in the second degree is a gross misdemeanor.

. Vehicle prowling in the second degree is a class C felony upon a third or subsequent conviction of vehicle prowling in the second degree. A third or subsequent conviction means that a person has been previously convicted at least two separate occasions of the crime of vehicle prowling in the second degree.

. Multiple counts of vehicle prowling (a) charged in the same charging document do not count as separate offenses for the purposes of charging as a felony based on previous convictions for vehicle prowling in the second degree and (b) based on the same date of occurrence do not count as separate offenses for the purposes of charging as a felony based on previous convictions for vehicle prowling in the second degree.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5053.SL.pdf?cite=2013%20c%20267%20§%201[2013 c 267 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20376[2011 c 336 § 376]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c47.pdf?cite=1982%201st%20ex.s.%20c%2047%20§%2014[1982 1st ex.s. c 47 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.52.100[1975 1st ex.s. c 260 § 9A.52.100]; ]

== 9A.52.105 - Removal of unauthorized persons—Declaration—Liability—Rights.
. Subject to subsections (2) and (3) of this section and upon the receipt of a declaration signed under penalty of perjury, in the form prescribed in RCW 9A.52.115, declaring the truth of all of the required elements set forth in subsection (4) of this section, a peace officer shall have the authority to: 

.. Remove the person or persons from the premises, with or without arresting the person or persons; and

.. Order the person or persons to remain off the premises or be subject to arrest for criminal trespass.

. Only a peace officer having probable cause to believe that a person is guilty of criminal trespass under RCW 9A.52.070 for knowingly entering or remaining unlawfully in a building considered residential real property, as defined in RCW 61.24.005, has the authority and discretion to make an arrest or exclude anyone under penalty of criminal trespass.

. While a peace officer can take into account a declaration from the property owner signed under penalty of perjury containing all of the required elements and in the form prescribed in RCW 9A.52.115, the peace officer must provide the occupant or occupants with a reasonable opportunity to secure and present any credible evidence provided by the person or persons on the premises, which the peace officer must consider, showing that the person or persons are tenants, legal occupants, or the guests or invitees of tenants or legal occupants.

. The declaration must include the following elements:

.. That the declarant is the owner of the premises or the authorized agent of the owner of the premises;

.. That an unauthorized person or persons have entered and are remaining unlawfully on the premises;

.. That the person or persons were not authorized to enter or remain;

.. That the person or persons are not a tenant or tenants and have not been a tenant or tenants, or a homeowner or homeowners who have been on title, within the last twelve months on the property;

.. That the declarant has demanded that the unauthorized person or persons vacate the premises but they have not done so;

.. That the premises were not abandoned at the time the unauthorized person or persons entered;

.. That the premises were not open to members of the public at the time the unauthorized person or persons entered;

.. That the declarant understands that a person or persons removed from the premises pursuant to this section may bring a cause of action under RCW 4.24.355 against the declarant for any false statements made in the declaration, and that as a result of such action the declarant may be held liable for actual damages, costs, and reasonable attorneys' fees;

.. That the declarant understands and acknowledges the prohibitions in RCW 59.18.230 and 59.18.290 against taking or detaining an occupant's personal property or removing or excluding an occupant from a dwelling unit or rental premises without an authorizing court order; and

.. That the declarant agrees to indemnify and hold harmless law enforcement for its actions or omissions made in good faith pursuant to the declaration.

. Neither the peace officer nor his or her law enforcement agency shall be held liable for actions or omissions made in good faith under this section.

. This section may not be construed to in any way limit rights under RCW 61.24.060 or to allow a peace officer to remove or exclude an occupant who is entitled to occupy a dwelling unit under a rental agreement or the occupant's guests or invitees.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5388-S.SL.pdf?cite=2017%20c%20284%20§%201[2017 c 284 § 1]; ]

== 9A.52.115 - Removal of unauthorized persons—Declaration form—Penalty for false swearing.
The owner of premises, or his or her authorized agent, may initiate the investigation and request the removal of an unauthorized person or persons from the premises by providing to law enforcement a declaration containing all of the following required elements and in substantially the following form:

REQUEST TO REMOVE TRESPASSER(S) FORM

The undersigned owner, or authorized agent of the owner, of the premises located at .......... hereby represents and declares under the penalty of perjury that (initial each box):

. [ ] The declarant is the owner of the premises or the authorized agent of the owner of the premises;

. [ ] An unauthorized person or persons have entered and are remaining unlawfully on the premises;

. [ ] The person or persons were not authorized to enter or remain;

. [ ] The person or persons are not a tenant or tenants and have not been a tenant or tenants, or a homeowner or homeowners who have been on title, within the last twelve months on the property;

. [ ] The declarant has demanded that the unauthorized person or persons vacate the premises but they have not done so;

. [ ] The premises were not abandoned at the time the unauthorized person or persons entered;

. [ ] The premises were not open to members of the public at the time the unauthorized person or persons entered;

. [ ] The declarant understands that a person or persons removed from the premises pursuant to RCW 9A.52.105 may bring a cause of action under RCW 4.24.355 against the declarant for any false statements made in this declaration, and that as a result of such action the declarant may be held liable for actual damages, costs, and reasonable attorneys' fees;

. [ ] The declarant understands and acknowledges the prohibitions in RCW 59.18.230 and 59.18.290 against taking or detaining an occupant's personal property or removing or excluding an occupant from a dwelling unit or rental premises without an authorizing court order;

. [ ] The declarant agrees to indemnify and hold harmless law enforcement for its actions or omissions made in good faith pursuant to this declaration; and

. [ ] Additional Optional Explanatory Comments:

...................................................................

...................................................................

A declarant of premises who falsely swears on a declaration provided under this section may be guilty of false swearing under RCW 9A.72.040 or of making a false or misleading statement to a public servant under RCW 9A.76.175, both of which are gross misdemeanors.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5388-S.SL.pdf?cite=2017%20c%20284%20§%202[2017 c 284 § 2]; ]

