= 9A.56 - Theft and robbery.
:toc:

== 9A.56.010 - Definitions.
The following definitions are applicable in this chapter unless the context otherwise requires:

. "Access device" means any card, plate, code, account number, or other means of account access that can be used alone or in conjunction with another access device to obtain money, goods, services, or anything else of value, or that can be used to initiate a transfer of funds, other than a transfer originated solely by paper instrument;

. "Appropriate lost or misdelivered property or services" means obtaining or exerting control over the property or services of another which the actor knows to have been lost or mislaid, or to have been delivered under a mistake as to identity of the recipient or as to the nature or amount of the property;

. "Beverage crate" means a plastic or metal box-like container used by a manufacturer or distributor in the transportation or distribution of individually packaged beverages to retail outlets, and affixed with language stating "property of . . . . .," "owned by . . . . .," or other markings or words identifying ownership;

. "By color or aid of deception" means that the deception operated to bring about the obtaining of the property or services; it is not necessary that deception be the sole means of obtaining the property or services;

. "Deception" occurs when an actor knowingly:

.. Creates or confirms another's false impression which the actor knows to be false; or

.. Fails to correct another's impression which the actor previously has created or confirmed; or

.. Prevents another from acquiring information material to the disposition of the property involved; or

.. Transfers or encumbers property without disclosing a lien, adverse claim, or other legal impediment to the enjoyment of the property, whether that impediment is or is not valid, or is or is not a matter of official record; or

.. Promises performance which the actor does not intend to perform or knows will not be performed;

. "Deprive" in addition to its common meaning means to make unauthorized use or an unauthorized copy of records, information, data, trade secrets, or computer programs;

. "Mail," in addition to its common meaning, means any letter, postal card, package, bag, or other item that is addressed to a specific address for delivery by the United States postal service or any commercial carrier performing the function of delivering similar items to residences or businesses, provided the mail:

.. [Empty]
... Is addressed with a specific person's name, family name, or company, business, or corporation name on the outside of the item of mail or on the contents inside; and

... Is not addressed to a generic unnamed occupant or resident of the address without an identifiable person, family, or company, business, or corporation name on the outside of the item of mail or on the contents inside; and

.. Has been left for collection or delivery in any letter box, mailbox, mail receptacle, or other authorized depository for mail, or given to a mail carrier, or left with any private business that provides mailboxes or mail addresses for customers or when left in a similar location for collection or delivery by any commercial carrier; or

.. Is in transit with a postal service, mail carrier, letter carrier, commercial carrier, or that is at or in a postal vehicle, postal station, mailbox, postal airplane, transit station, or similar location of a commercial carrier; or

.. Has been delivered to the intended address, but has not been received by the intended addressee.

Mail, for purposes of chapter 164, Laws of 2011, does not include magazines, catalogs, direct mail inserts, newsletters, advertising circulars, or any mail that is considered third-class mail by the United States postal service;

. "Mailbox," in addition to its common meaning, means any authorized depository or receptacle of mail for the United States postal service or authorized depository for a commercial carrier that provides services to the general public, including any address to which mail is or can be addressed, or a place where the United States postal service or equivalent commercial carrier delivers mail to its addressee;

. "Merchandise pallet" means a wood or plastic carrier designed and manufactured as an item on which products can be placed before or during transport to retail outlets, manufacturers, or contractors, and affixed with language stating "property of . . .," "owned by . . .," or other markings or words identifying ownership;

. "Obtain control over" in addition to its common meaning, means:

.. In relation to property, to bring about a transfer or purported transfer to the obtainer or another of a legally recognized interest in the property; or

.. In relation to labor or service, to secure performance thereof for the benefits of the obtainer or another;

. "Owner" means a person, other than the actor, who has possession of or any other interest in the property or services involved, and without whose consent the actor has no authority to exert control over the property or services;

. "Parking area" means a parking lot or other property provided by retailers for use by a customer for parking an automobile or other vehicle;

. "Receive" includes, but is not limited to, acquiring title, possession, control, or a security interest, or any other interest in the property;

. "Received by the intended addressee" means that the addressee, owner of the delivery mailbox, or authorized agent has removed the delivered mail from its delivery mailbox;

. "Services" includes, but is not limited to, labor, professional services, transportation services, electronic computer services, the supplying of hotel accommodations, restaurant services, entertainment, the supplying of equipment for use, and the supplying of commodities of a public utility nature such as gas, electricity, steam, and water;

. "Shopping cart" means a basket mounted on wheels or similar container generally used in a retail establishment by a customer for the purpose of transporting goods of any kind;

. "Stolen" means obtained by theft, robbery, or extortion;

. "Subscription television service" means cable or encrypted video and related audio and data services intended for viewing on a home television by authorized members of the public only, who have agreed to pay a fee for the service. Subscription services include but are not limited to those video services presently delivered by coaxial cable, fiber optic cable, terrestrial microwave, television broadcast, and satellite transmission;

. "Telecommunication device" means (a) any type of instrument, device, machine, or equipment that is capable of transmitting or receiving telephonic or electronic communications; or (b) any part of such an instrument, device, machine, or equipment, or any computer circuit, computer chip, electronic mechanism, or other component, that is capable of facilitating the transmission or reception of telephonic or electronic communications;

. "Telecommunication service" includes any service other than subscription television service provided for a charge or compensation to facilitate the transmission, transfer, or reception of a telephonic communication or an electronic communication;

. Value. (a) "Value" means the market value of the property or services at the time and in the approximate area of the criminal act.

.. Whether or not they have been issued or delivered, written instruments, except those having a readily ascertained market value, shall be evaluated as follows:

... The value of an instrument constituting an evidence of debt, such as a check, draft, or promissory note, shall be deemed the amount due or collectible thereon or thereby, that figure ordinarily being the face amount of the indebtedness less any portion thereof which has been satisfied;

... The value of a ticket or equivalent instrument which evidences a right to receive transportation, entertainment, or other service shall be deemed the price stated thereon, if any; and if no price is stated thereon, the value shall be deemed the price of such ticket or equivalent instrument which the issuer charged the general public;

... The value of any other instrument that creates, releases, discharges, or otherwise affects any valuable legal right, privilege, or obligation shall be deemed the greatest amount of economic loss which the owner of the instrument might reasonably suffer by virtue of the loss of the instrument.

.. Except as provided in RCW 9A.56.340(4) and 9A.56.350(4), whenever any series of transactions which constitute theft, would, when considered separately, constitute theft in the third degree because of value, and said series of transactions are a part of a criminal episode or a common scheme or plan, then the transactions may be aggregated in one count and the sum of the value of all said transactions shall be the value considered in determining the degree of theft involved.

For purposes of this subsection, "criminal episode" means a series of thefts committed by the same person from one or more mercantile establishments on three or more occasions within a five-day period.

.. Whenever any person is charged with possessing stolen property and such person has unlawfully in his possession at the same time the stolen property of more than one person, then the stolen property possessed may be aggregated in one count and the sum of the value of all said stolen property shall be the value considered in determining the degree of theft involved. Thefts committed by the same person in different counties that have been aggregated in one county may be prosecuted in any county in which one of the thefts occurred.

.. Property or services having value that cannot be ascertained pursuant to the standards set forth above shall be deemed to be of a value not exceeding two hundred and fifty dollars;

. "Vulnerable adult" includes a person eighteen years of age or older who:

.. Is functionally, mentally, or physically unable to care for himself or herself; or

.. Is suffering from a cognitive impairment other than voluntary intoxication;

. "Wrongfully obtains" or "exerts unauthorized control" means:

.. To take the property or services of another;

.. Having any property or services in one's possession, custody or control as bailee, factor, lessee, pledgee, renter, servant, attorney, agent, employee, trustee, executor, administrator, guardian, or officer of any person, estate, association, or corporation, or as a public officer, or person authorized by agreement or competent authority to take or hold such possession, custody, or control, to secrete, withhold, or appropriate the same to his or her own use or to the use of any person other than the true owner or person entitled thereto; or

.. Having any property or services in one's possession, custody, or control as partner, to secrete, withhold, or appropriate the same to his or her use or to the use of any person other than the true owner or person entitled thereto, where the use is unauthorized by the partnership agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1153-S.SL.pdf?cite=2017%20c%20266%20§%207[2017 c 266 § 7]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1145-S.SL.pdf?cite=2011%20c%20164%20§%202[2011 c 164 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2704.SL.pdf?cite=2006%20c%20277%20§%204[2006 c 277 § 4]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2605.SL.pdf?cite=2002%20c%2097%20§%201[2002 c 97 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1142.SL.pdf?cite=1999%20c%20143%20§%2036[1999 c 143 § 36]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5769-S.SL.pdf?cite=1998%20c%20236%20§%201[1998 c 236 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2059-S.SL.pdf?cite=1997%20c%20346%20§%202[1997 c 346 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5820-S.SL.pdf?cite=1995%20c%2092%20§%201[1995 c 92 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c140.pdf?cite=1987%20c%20140%20§%201[1987 c 140 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c257.pdf?cite=1986%20c%20257%20§%202[1986 c 257 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c382.pdf?cite=1985%20c%20382%20§%201[1985 c 382 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c273.pdf?cite=1984%20c%20273%20§%206[1984 c 273 § 6]; 1975-'76 2nd ex.s. c 38 § 8; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.56.010[1975 1st ex.s. c 260 § 9A.56.010]; ]

== 9A.56.020 - Theft—Definition, defense.
. "Theft" means:

.. To wrongfully obtain or exert unauthorized control over the property or services of another or the value thereof, with intent to deprive him or her of such property or services; or

.. By color or aid of deception to obtain control over the property or services of another or the value thereof, with intent to deprive him or her of such property or services; or

.. To appropriate lost or misdelivered property or services of another, or the value thereof, with intent to deprive him or her of such property or services.

. In any prosecution for theft, it shall be a sufficient defense that:

.. The property or service was appropriated openly and avowedly under a claim of title made in good faith, even though the claim be untenable; or

.. The property was merchandise pallets that were received by a pallet recycler or repairer in the ordinary course of its business.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6338.SL.pdf?cite=2004%20c%20122%20§%201[2004 c 122 § 1]; 1975-'76 2nd ex.s. c 38 § 9; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.56.020[1975 1st ex.s. c 260 § 9A.56.020]; ]

== 9A.56.030 - Theft in the first degree.
. Except as provided in RCW 9A.56.400, a person is guilty of theft in the first degree if he or she commits theft of:

.. Property or services which exceed(s) five thousand dollars in value other than a firearm as defined in RCW 9.41.010;

.. Property of any value, other than a firearm as defined in RCW 9.41.010 or a motor vehicle, taken from the person of another;

.. A search and rescue dog, as defined in RCW 9.91.175, while the search and rescue dog is on duty; or

.. Commercial metal property, nonferrous metal property, or private metal property, as those terms are defined in RCW 19.290.010, and the costs of the damage to the owner's property exceed five thousand dollars in value.

. Theft in the first degree is a class B felony.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1153-S.SL.pdf?cite=2017%20c%20266%20§%2010[2017 c 266 § 10]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1552-S.SL.pdf?cite=2013%20c%20322%20§%202[2013 c 322 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2570-S.SL.pdf?cite=2012%20c%20233%20§%202[2012 c 233 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6167.SL.pdf?cite=2009%20c%20431%20§%207[2009 c 431 § 7]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1001-S3.SL.pdf?cite=2007%20c%20199%20§%203[2007 c 199 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5979.SL.pdf?cite=2005%20c%20212%20§%202[2005 c 212 § 2]; 1995 c 129 § 11 (Initiative Measure No. 159); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.56.030[1975 1st ex.s. c 260 § 9A.56.030]; ]

== 9A.56.040 - Theft in the second degree.
. Except as provided in RCW 9A.56.400, a person is guilty of theft in the second degree if he or she commits theft of:

.. Property or services which exceed(s) seven hundred fifty dollars in value but does not exceed five thousand dollars in value, other than a firearm as defined in RCW 9.41.010 or a motor vehicle;

.. A public record, writing, or instrument kept, filed, or deposited according to law with or in the keeping of any public office or public servant;

.. Commercial metal property, nonferrous metal property, or private metal property, as those terms are defined in RCW 19.290.010, and the costs of the damage to the owner's property exceed seven hundred fifty dollars but does not exceed five thousand dollars in value; or

.. An access device.

. Theft in the second degree is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1153-S.SL.pdf?cite=2017%20c%20266%20§%2011[2017 c 266 § 11]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1552-S.SL.pdf?cite=2013%20c%20322%20§%203[2013 c 322 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2570-S.SL.pdf?cite=2012%20c%20233%20§%203[2012 c 233 § 3]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6167.SL.pdf?cite=2009%20c%20431%20§%208[2009 c 431 § 8]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1001-S3.SL.pdf?cite=2007%20c%20199%20§%204[2007 c 199 § 4]; 1995 c 129 § 12 (Initiative Measure No. 159); http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=1994%20sp.s.%20c%207%20§%20433[1994 sp.s. c 7 § 433]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c140.pdf?cite=1987%20c%20140%20§%202[1987 c 140 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c47.pdf?cite=1982%201st%20ex.s.%20c%2047%20§%2015[1982 1st ex.s. c 47 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.56.040[1975 1st ex.s. c 260 § 9A.56.040]; ]

== 9A.56.050 - Theft in the third degree.
. A person is guilty of theft in the third degree if he or she commits theft of property or services which (a) does not exceed seven hundred fifty dollars in value, or (b) includes ten or more merchandise pallets, or ten or more beverage crates, or a combination of ten or more merchandise pallets and beverage crates.

. Theft in the third degree is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6167.SL.pdf?cite=2009%20c%20431%20§%209[2009 c 431 § 9]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5769-S.SL.pdf?cite=1998%20c%20236%20§%204[1998 c 236 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.56.050[1975 1st ex.s. c 260 § 9A.56.050]; ]

== 9A.56.060 - Unlawful issuance of checks or drafts.
. Any person who shall with intent to defraud, make, or draw, or utter, or deliver to another person any check, or draft, on a bank or other depository for the payment of money, knowing at the time of such drawing, or delivery, that he or she has not sufficient funds in, or credit with the bank or other depository, to meet the check or draft, in full upon its presentation, is guilty of unlawful issuance of bank check. The word "credit" as used herein shall be construed to mean an arrangement or understanding with the bank or other depository for the payment of such check or draft, and the uttering or delivery of such a check or draft to another person without such fund or credit to meet the same shall be prima facie evidence of an intent to defraud.

. Any person who shall with intent to defraud, make, or draw, or utter, or deliver to another person any check, or draft on a bank or other depository for the payment of money and who issues a stop-payment order directing the bank or depository on which the check is drawn not to honor the check, and who fails to make payment of money in the amount of the check or draft or otherwise arrange a settlement agreed upon by the holder of the check within twenty days of issuing the check or draft is guilty of unlawful issuance of a bank check.

. When any series of transactions which constitute unlawful issuance of a bank check would, when considered separately, constitute unlawful issuance of a bank check in an amount of seven hundred fifty dollars or less because of value, and the series of transactions are a part of a common scheme or plan, the transactions may be aggregated in one count and the sum of the value of all of the transactions shall be the value considered in determining whether the unlawful issuance of a bank check is to be punished as a class C felony or a gross misdemeanor.

. Unlawful issuance of a bank check in an amount greater than seven hundred fifty dollars is a class C felony.

. Unlawful issuance of a bank check in an amount of seven hundred fifty dollars or less is a gross misdemeanor and shall be punished as follows:

.. The court shall order the defendant to make full restitution;

.. The defendant need not be imprisoned, but the court shall impose a fine of up to one thousand one hundred twenty-five dollars for adult offenders. Of the fine imposed, at least three hundred seventy-five dollars or an amount equal to one hundred fifty percent of the amount of the bank check, whichever is greater, shall not be suspended or deferred. Upon conviction for a second offense within any twelve-month period, the court may not suspend or defer any portion of the fine.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5564-S2.SL.pdf?cite=2015%20c%20265%20§%2018[2015 c 265 § 18]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6167.SL.pdf?cite=2009%20c%20431%20§%2010[2009 c 431 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c138.pdf?cite=1982%20c%20138%20§%201[1982 c 138 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c244.pdf?cite=1979%20ex.s.%20c%20244%20§%2014[1979 ex.s. c 244 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.56.060[1975 1st ex.s. c 260 § 9A.56.060]; ]

== 9A.56.063 - Making or possessing motor vehicle theft tools.
. Any person who makes or mends, or causes to be made or mended, uses, or has in his or her possession any motor vehicle theft tool, that is adapted, designed, or commonly used for the commission of motor vehicle related theft, under circumstances evincing an intent to use or employ, or allow the same to be used or employed, in the commission of motor vehicle theft, or knowing that the same is intended to be so used, is guilty of making or having motor vehicle theft tools.

. For the purpose of this section, motor vehicle theft tool includes, but is not limited to, the following: Slim jim, false master key, master purpose key, altered or shaved key, trial or jiggler key, slide hammer, lock puller, picklock, bit, nipper, any other implement shown by facts and circumstances that is intended to be used in the commission of a motor vehicle related theft, or knowing that the same is intended to be so used.

. For the purposes of this section, the following definitions apply:

.. "False master" or "master key" is any key or other device made or altered to fit locks or ignitions of multiple vehicles, or vehicles other than that for which the key was originally manufactured.

.. "Altered or shaved key" is any key so altered, by cutting, filing, or other means, to fit multiple vehicles or vehicles other than the vehicles for which the key was originally manufactured.

.. "Trial keys" or "jiggler keys" are keys or sets designed or altered to manipulate a vehicle locking mechanism other than the lock for which the key was originally manufactured.

. Making or having motor vehicle theft tools is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1001-S3.SL.pdf?cite=2007%20c%20199%20§%2018[2007 c 199 § 18]; ]

== 9A.56.065 - Theft of motor vehicle.
. A person is guilty of theft of a motor vehicle if he or she commits theft of a motor vehicle.

. Theft of a motor vehicle is a class B felony.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1001-S3.SL.pdf?cite=2007%20c%20199%20§%202[2007 c 199 § 2]; ]

== 9A.56.068 - Possession of stolen vehicle.
. A person is guilty of possession of a stolen vehicle if he or she possess [possesses] a stolen motor vehicle.

. Possession of a stolen motor vehicle is a class B felony.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1001-S3.SL.pdf?cite=2007%20c%20199%20§%205[2007 c 199 § 5]; ]

== 9A.56.070 - Taking motor vehicle without permission in the first degree.
. A person is guilty of taking a motor vehicle without permission in the first degree if he or she, without the permission of the owner or person entitled to possession, intentionally takes or drives away an automobile or motor vehicle, whether propelled by steam, electricity, or internal combustion engine, that is the property of another, and he or she:

.. Alters the motor vehicle for the purpose of changing its appearance or primary identification, including obscuring, removing, or changing the manufacturer's serial number or the vehicle identification number plates;

.. Removes, or participates in the removal of, parts from the motor vehicle with the intent to sell the parts;

.. Exports, or attempts to export, the motor vehicle across state lines or out of the United States for profit;

.. Intends to sell the motor vehicle; or

.. Is engaged in a conspiracy and the central object of the conspiratorial agreement is the theft of motor vehicles for sale to others for profit or is engaged in a conspiracy and has solicited a juvenile to participate in the theft of a motor vehicle.

. Taking a motor vehicle without permission in the first degree is a class B felony.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1001-S3.SL.pdf?cite=2007%20c%20199%20§%2016[2007 c 199 § 16]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%2072[2003 c 53 § 72]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6490-S.SL.pdf?cite=2002%20c%20324%20§%201[2002 c 324 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.56.070[1975 1st ex.s. c 260 § 9A.56.070]; ]

== 9A.56.075 - Taking motor vehicle without permission in the second degree.
. A person is guilty of taking a motor vehicle without permission in the second degree if he or she, without the permission of the owner or person entitled to possession, intentionally takes or drives away any automobile or motor vehicle, whether propelled by steam, electricity, or internal combustion engine, that is the property of another, or he or she voluntarily rides in or upon the automobile or motor vehicle with knowledge of the fact that the automobile or motor vehicle was unlawfully taken.

. Taking a motor vehicle without permission in the second degree is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%2073[2003 c 53 § 73]; ]

== 9A.56.078 - Motor vehicle crimes—Civil action.
. A person who is deprived of his or her motor vehicle because of a violation of RCW 9A.56.030, 9A.56.040, 9A.56.070, or 9A.56.075 may file an action in superior court against the perpetrator for the recovery of actual damages, limited to the value of any damage to the vehicle and any property stolen from the vehicle, civil damages of up to five thousand dollars, and the costs of the suit, including reasonable attorneys' fees.

. [Empty]
.. Except as provided in (b) of this subsection, service of any summons or other process under this section shall be by personal service.

.. [Empty]
... If the defendant cannot be found after a due and diligent search, the defendant's violation of RCW 9A.56.030, 9A.56.040, 9A.56.070, or 9A.56.075 shall be deemed to constitute an appointment by the defendant of the secretary of state of the state of Washington to be his or her true and lawful attorney upon whom may be served all lawful summons and processes against him or her under this section. The plaintiff shall perform the service allowed under this subsection (2)(b)(i) by leaving two copies of the summons or other process with the secretary of state or at the secretary of state's office. Service in this manner constitutes sufficient and valid personal service upon the defendant.

... After performing service under (b)(i) of this subsection, the plaintiff shall promptly send notice of service under (b)(i) of this subsection and a copy of the summons or process to the defendant by registered mail, with return receipt requested, to the defendant's last known address. After complying with this subsection (2)(b)(ii), the plaintiff shall file the following with the secretary of state to be attached to the summons or process filed under (b)(i) of this subsection:

(A) An affidavit from the plaintiff attesting to compliance with (b)(ii) of this subsection; and

(B) An affidavit from the plaintiff's attorney that he or she has, with due diligence, attempted to serve personal process upon the defendant at all addresses known to him or her and listing the addresses at which he or she attempted to personally serve the defendant. However, if the defendant's endorsed return receipt is received, then the affidavit need only show that the defendant received personal service by mail.

... The secretary of state shall send, by prepaid mail, a copy of the summons or process received under (b)(i) of this subsection to the defendant's address, if known. The secretary of state shall keep a record that shows the day of service of all summons and processes made under (b)(i) of this subsection.

... The court in which an action is brought under this section may order continuances as may be necessary to afford the defendant a reasonable opportunity to defend the action.

.. The secretary of state may charge a fee for his or her services under (b) of this subsection. The fee shall be part of the costs of suit that may be awarded to the plaintiff.

. The department of licensing shall suspend the driver's license or driving privilege of a defendant until any monetary obligation imposed under subsection (1) of this section is paid in full, unless the defendant has entered into a payment plan under subsection (4) of this section.

. If the court determines that a person is not able to pay a monetary obligation made under subsection (1) of this section in full, the court may enter into a payment plan with the person. If the person fails to meet the obligations of the payment plan, the court may modify or revoke the plan and order the defendant to pay the obligation in full. If the court revokes the plan, it shall notify the department of licensing and the department of licensing shall suspend the driver's license or driving privilege of the defendant until the monetary obligation is paid in full.

. The court shall notify the department of licensing when the monetary obligation of a defendant whose license is suspended under this section is paid in full.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2034.SL.pdf?cite=2007%20c%20393%20§%201[2007 c 393 § 1]; ]

== 9A.56.080 - Theft of livestock in the first degree.
. Every person who, with intent to sell or exchange and to deprive or defraud the lawful owner thereof, willfully takes, leads, or transports away, conceals, withholds, slaughters, or otherwise appropriates any horse, mule, cow, heifer, bull, steer, swine, goat, or sheep is guilty of theft of livestock in the first degree.

. Theft of livestock in the first degree is a class B felony.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5290-S.SL.pdf?cite=2005%20c%20419%20§%201[2005 c 419 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%2074[2003 c 53 § 74]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c257.pdf?cite=1986%20c%20257%20§%2032[1986 c 257 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c174.pdf?cite=1977%20ex.s.%20c%20174%20§%202[1977 ex.s. c 174 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.56.080[1975 1st ex.s. c 260 § 9A.56.080]; ]

== 9A.56.083 - Theft of livestock in the second degree.
. A person who commits what would otherwise be theft of livestock in the first degree but without intent to sell or exchange, and for the person's own use only, is guilty of theft of livestock in the second degree.

. Theft of livestock in the second degree is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%2075[2003 c 53 § 75]; ]

== 9A.56.085 - Minimum fine for theft of livestock.
. Whenever an adult offender is convicted of a violation of RCW 9A.56.080 or 9A.56.083, the convicting court shall order the person to pay the amount of two thousand dollars for each animal killed or possessed.

. For the purpose of this section, the term "convicted" includes a plea of guilty, a finding of guilt regardless of whether the imposition of the sentence is deferred or any part of the penalty is suspended, or the levying of a fine.

. If two or more persons are convicted of any violation of this section, the amount required under this section shall be imposed upon them jointly and severally.

. The fine in this section shall be imposed in addition to and regardless of any penalty, including fines or costs, that is provided for any violation of this section. The amount imposed by this section shall be included by the court in any pronouncement of sentence and may not be suspended, waived, modified, or deferred in any respect. Nothing in this section may be construed to abridge or alter alternative rights of action or remedies in equity or under common law or statutory law, criminal or civil.

. A defaulted payment or any installment payment may be collected by any means authorized by law for the enforcement of orders of the court or collection of a fine or costs, including vacation of a deferral of sentencing or of a suspension of sentence.

. The two thousand dollars additional penalty shall be remitted by the county treasurer to the state treasurer as provided under RCW 10.82.070.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5564-S2.SL.pdf?cite=2015%20c%20265%20§%2019[2015 c 265 § 19]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%2076[2003 c 53 § 76]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c131.pdf?cite=1989%20c%20131%20§%201[1989 c 131 § 1]; ]

== 9A.56.096 - Theft of rental, leased, lease-purchased, or loaned property.
. A person who, with intent to deprive the owner or owner's agent, wrongfully obtains, or exerts unauthorized control over, or by color or aid of deception gains control of personal property that is rented, leased, or loaned by written agreement to the person, is guilty of theft of rental, leased, lease-purchased, or loaned property.

. The finder of fact may presume intent to deprive if the finder of fact finds either of the following:

.. That the person who rented or leased the property failed to return or make arrangements acceptable to the owner of the property or the owner's agent to return the property to the owner or the owner's agent within seventy-two hours after receipt of proper notice following the due date of the rental, lease, lease-purchase, or loan agreement; or

.. That the renter, lessee, or borrower presented identification to the owner or the owner's agent that was materially false, fictitious, or not current with respect to name, address, place of employment, or other appropriate items.

. As used in subsection (2) of this section, "proper notice" consists of a written demand by the owner or the owner's agent made after the due date of the rental, lease, lease-purchase, or loan period, mailed by certified or registered mail to the renter, lessee, or borrower at: (a) The address the renter, lessee, or borrower gave when the contract was made; or (b) the renter, lessee, or borrower's last known address if later furnished in writing by the renter, lessee, borrower, or the agent of the renter, lessee, or borrower.

. The replacement value of the property obtained must be utilized in determining the amount involved in the theft of rental, leased, lease-purchased, or loaned property.

. [Empty]
.. Theft of rental, leased, lease-purchased, or loaned property is a class B felony if the rental, leased, lease-purchased, or loaned property is valued at five thousand dollars or more.

.. Theft of rental, leased, lease-purchased, or loaned property is a class C felony if the rental, leased, lease-purchased, or loaned property is valued at seven hundred fifty dollars or more but less than five thousand dollars.

.. Theft of rental, leased, lease-purchased, or loaned property is a gross misdemeanor if the rental, leased, lease-purchased, or loaned property is valued at less than seven hundred fifty dollars.

. The crime of theft of rental, leased, lease-purchased, or loaned property may be deemed to have been committed either at the physical location where the written agreement for the rental, lease, lease-purchase, or loan of the property was executed under subsection (1) of this section, or at the address where proper notice may be mailed to the renter, lessee, or borrower under subsection (3) of this section.

. This section applies to rental agreements that provide that the renter may return the property any time within the rental period and pay only for the time the renter actually retained the property, in addition to any minimum rental fee, to lease agreements, to lease-purchase agreements as defined under RCW 63.19.010, and to vehicles loaned to prospective purchasers borrowing a vehicle by written agreement from a motor vehicle dealer licensed under chapter 46.70 RCW. This section does not apply to rental or leasing of real property under the residential landlord-tenant act, chapter 59.18 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6108.SL.pdf?cite=2012%20c%2030%20§%201[2012 c 30 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6167.SL.pdf?cite=2009%20c%20431%20§%2011[2009 c 431 § 11]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1001-S3.SL.pdf?cite=2007%20c%20199%20§%2017[2007 c 199 § 17]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%2077[2003 c 53 § 77]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2059-S.SL.pdf?cite=1997%20c%20346%20§%201[1997 c 346 § 1]; ]

== 9A.56.100 - Theft and larceny equated.
All offenses defined as larcenies outside of this title shall be treated as thefts as provided in this title.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.56.100[1975 1st ex.s. c 260 § 9A.56.100]; ]

== 9A.56.110 - Extortion—Definition.
"Extortion" means knowingly to obtain or attempt to obtain by threat property or services of the owner, and specifically includes sexual favors.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1142.SL.pdf?cite=1999%20c%20143%20§%2037[1999 c 143 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c4.pdf?cite=1983%201st%20ex.s.%20c%204%20§%202[1983 1st ex.s. c 4 § 2]; 1975-'76 2nd ex.s. c 38 § 10; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.56.110[1975 1st ex.s. c 260 § 9A.56.110]; ]

== 9A.56.120 - Extortion in the first degree.
. A person is guilty of extortion in the first degree if he or she commits extortion by means of a threat as defined in *RCW 9A.04.110(27) (a), (b), or (c).

. Extortion in the first degree is a class B felony.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20377[2011 c 336 § 377]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.56.120[1975 1st ex.s. c 260 § 9A.56.120]; ]

== 9A.56.130 - Extortion in the second degree.
. A person is guilty of extortion in the second degree if he or she commits extortion by means of a wrongful threat as defined in RCW 9A.04.110(28) (d) through (j).

. In any prosecution under this section based on a threat to accuse any person of a crime or cause criminal charges to be instituted against any person, it is a defense that the actor reasonably believed the threatened criminal charge to be true and that his or her sole purpose was to compel or induce the person threatened to take reasonable action to make good the wrong which was the subject of such threatened criminal charge.

. Extortion in the second degree is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2368.SL.pdf?cite=2018%20c%2022%20§%205[2018 c 22 § 5]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6602-S.SL.pdf?cite=2002%20c%2047%20§%202[2002 c 47 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.56.130[1975 1st ex.s. c 260 § 9A.56.130]; ]

== 9A.56.140 - Possessing stolen property—Definition—Presumption.
. "Possessing stolen property" means knowingly to receive, retain, possess, conceal, or dispose of stolen property knowing that it has been stolen and to withhold or appropriate the same to the use of any person other than the true owner or person entitled thereto.

. The fact that the person who stole the property has not been convicted, apprehended, or identified is not a defense to a charge of possessing stolen property.

. When a person has in his or her possession, or under his or her control, stolen access devices issued in the names of two or more persons, or ten or more stolen merchandise pallets, or ten or more stolen beverage crates, or a combination of ten or more stolen merchandise pallets and beverage crates, as defined under RCW 9A.56.010, he or she is presumed to know that they are stolen.

. The presumption in subsection (3) of this section is rebuttable by evidence raising a reasonable inference that the possession of such stolen access devices, merchandise pallets, or beverage crates was without knowledge that they were stolen.

. In any prosecution for possessing stolen property, it is a sufficient defense that the property was merchandise pallets that were received by a pallet recycler or repairer in the ordinary course of its business.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6338.SL.pdf?cite=2004%20c%20122%20§%202[2004 c 122 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5769-S.SL.pdf?cite=1998%20c%20236%20§%203[1998 c 236 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c140.pdf?cite=1987%20c%20140%20§%203[1987 c 140 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.56.140[1975 1st ex.s. c 260 § 9A.56.140]; ]

== 9A.56.150 - Possessing stolen property in the first degree—Other than firearm or motor vehicle.
. A person is guilty of possessing stolen property in the first degree if he or she possesses stolen property, other than a firearm as defined in RCW 9.41.010 or a motor vehicle, which exceeds five thousand dollars in value.

. Possessing stolen property in the first degree is a class B felony.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6167.SL.pdf?cite=2009%20c%20431%20§%2012[2009 c 431 § 12]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1001-S3.SL.pdf?cite=2007%20c%20199%20§%206[2007 c 199 § 6]; 1995 c 129 § 14 (Initiative Measure No. 159); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.56.150[1975 1st ex.s. c 260 § 9A.56.150]; ]

== 9A.56.160 - Possessing stolen property in the second degree—Other than firearm or motor vehicle.
. A person is guilty of possessing stolen property in the second degree if:

.. He or she possesses stolen property, other than a firearm as defined in RCW 9.41.010 or a motor vehicle, which exceeds seven hundred fifty dollars in value but does not exceed five thousand dollars in value; or

.. He or she possesses a stolen public record, writing or instrument kept, filed, or deposited according to law; or

.. He or she possesses a stolen access device.

. Possessing stolen property in the second degree is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6167.SL.pdf?cite=2009%20c%20431%20§%2013[2009 c 431 § 13]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1001-S3.SL.pdf?cite=2007%20c%20199%20§%207[2007 c 199 § 7]; 1995 c 129 § 15 (Initiative Measure No. 159); http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=1994%20sp.s.%20c%207%20§%20434[1994 sp.s. c 7 § 434]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c140.pdf?cite=1987%20c%20140%20§%204[1987 c 140 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.56.160[1975 1st ex.s. c 260 § 9A.56.160]; ]

== 9A.56.170 - Possessing stolen property in the third degree.
. A person is guilty of possessing stolen property in the third degree if he or she possesses (a) stolen property which does not exceed seven hundred fifty dollars in value, or (b) ten or more stolen merchandise pallets, or ten or more stolen beverage crates, or a combination of ten or more stolen merchandise pallets and beverage crates.

. Possessing stolen property in the third degree is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6167.SL.pdf?cite=2009%20c%20431%20§%2014[2009 c 431 § 14]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5769-S.SL.pdf?cite=1998%20c%20236%20§%202[1998 c 236 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.56.170[1975 1st ex.s. c 260 § 9A.56.170]; ]

== 9A.56.180 - Obscuring the identity of a machine.
. A person is guilty of obscuring the identity of a machine if he or she knowingly:

.. Obscures the manufacturer's serial number or any other distinguishing identification number or mark upon any vehicle, machine, engine, apparatus, appliance, or other device with intent to render it unidentifiable; or

.. Possesses a vehicle, machine, engine, apparatus, appliance, or other device held for sale knowing that the serial number or other identification number or mark has been obscured.

. "Obscure" means to remove, deface, cover, alter, destroy, or otherwise render unidentifiable.

. Obscuring the identity of a machine is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20378[2011 c 336 § 378]; 1975-'76 2nd ex.s. c 38 § 11; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.56.180[1975 1st ex.s. c 260 § 9A.56.180]; ]

== 9A.56.190 - Robbery—Definition.
A person commits robbery when he or she unlawfully takes personal property from the person of another or in his or her presence against his or her will by the use or threatened use of immediate force, violence, or fear of injury to that person or his or her property or the person or property of anyone. Such force or fear must be used to obtain or retain possession of the property, or to prevent or overcome resistance to the taking; in either of which cases the degree of force is immaterial. Such taking constitutes robbery whenever it appears that, although the taking was fully completed without the knowledge of the person from whom taken, such knowledge was prevented by the use of force or fear.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20379[2011 c 336 § 379]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.56.190[1975 1st ex.s. c 260 § 9A.56.190]; ]

== 9A.56.200 - Robbery in the first degree.
. A person is guilty of robbery in the first degree if:

.. In the commission of a robbery or of immediate flight therefrom, he or she:

... Is armed with a deadly weapon; or

... Displays what appears to be a firearm or other deadly weapon; or

... Inflicts bodily injury; or

.. He or she commits a robbery within and against a financial institution as defined in RCW 7.88.010 or 35.38.060.

. Robbery in the first degree is a class A felony.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2511-S2.SL.pdf?cite=2002%20c%2085%20§%201[2002 c 85 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.56.200[1975 1st ex.s. c 260 § 9A.56.200]; ]

== 9A.56.210 - Robbery in the second degree.
. A person is guilty of robbery in the second degree if he or she commits robbery.

. Robbery in the second degree is a class B felony.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20380[2011 c 336 § 380]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.56.210[1975 1st ex.s. c 260 § 9A.56.210]; ]

== 9A.56.220 - Theft of subscription television services.
. A person is guilty of theft of subscription television services if, with intent to avoid payment of the lawful charge of a subscription television service, he or she:

.. Obtains or attempts to obtain subscription television service from a subscription television service company by trick, artifice, deception, use of a device or decoder, or other fraudulent means without authority from the company providing the service;

.. Assists or instructs a person in obtaining or attempting to obtain subscription television service without authority of the company providing the service;

.. Makes or maintains a connection or connections, whether physical, electrical, mechanical, acoustical, or by other means, with cables, wires, components, or other devices used for the distribution of subscription television services without authority from the company providing the services;

.. Makes or maintains a modification or alteration to a device installed with the authorization of a subscription television service company for the purpose of interception or receiving a program or other service carried by the company that the person is not authorized by the company to receive; or

.. Possesses without authority a device designed in whole or in part to receive subscription television services offered for sale by the subscription television service company, regardless of whether the program or services are encoded, filtered, scrambled, or otherwise made unintelligible, or to perform or facilitate the performance of any other acts set out in (a) through (d) of this subsection for the reception of subscription television services without authority.

. Theft of subscription television services is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5820-S.SL.pdf?cite=1995%20c%2092%20§%202[1995 c 92 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c11.pdf?cite=1989%20c%2011%20§%201[1989 c 11 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c430.pdf?cite=1985%20c%20430%20§%201[1985 c 430 § 1]; ]

== 9A.56.230 - Unlawful sale of subscription television services.
. A person is guilty of unlawful sale of subscription television services if, with intent to avoid payment or to facilitate the avoidance of payment of the lawful charge for any subscription television service, he or she, without authorization from the subscription television service company:

.. Publishes or advertises for sale a plan for a device that is designed in whole or in part to receive subscription television or services offered for sale by the subscription television service company, regardless of whether the programming or services are encoded, filtered, scrambled, or otherwise made unintelligible;

.. Advertises for sale or lease a device or kit for a device designed in whole or in part to receive subscription television services offered for sale by the subscription television service company, regardless of whether the programming or services are encoded, filtered, scrambled, or otherwise made unintelligible; or

.. Manufactures, imports into the state of Washington, distributes, sells, leases, or offers for sale or lease a device, plan, or kit for a device designed in whole or in part to receive subscription television services offered for sale by the subscription television service company, regardless of whether the programming or services are encoded, filtered, scrambled, or otherwise made unintelligible.

. Unlawful sale of subscription television services is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5820-S.SL.pdf?cite=1995%20c%2092%20§%203[1995 c 92 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c430.pdf?cite=1985%20c%20430%20§%202[1985 c 430 § 2]; ]

== 9A.56.240 - Forfeiture and disposal of device used to commit violation.
Upon conviction of theft or unlawful sale of cable television services and upon motion and hearing, the court shall order the forfeiture of any decoder, descrambler, or other device used in committing the violation of RCW 9A.56.220 or 9A.56.230 as contraband and dispose of it at the court's discretion.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c430.pdf?cite=1985%20c%20430%20§%203[1985 c 430 § 3]; ]

== 9A.56.250 - Civil cause of action.
. In addition to the criminal penalties provided in RCW 9A.56.220 and 9A.56.230, there is created a civil cause of action for theft of subscription television services and for unlawful sale of subscription television services.

. A person who sustains injury to his or her person, business, or property by an act described in RCW 9A.56.220 or 9A.56.230 may file an action in superior court for recovery of damages and the costs of the suit, including reasonable investigative and attorneys' fees and costs.

. Upon finding a violation of RCW 9A.56.220 or 9A.56.230, in addition to the remedies described in this section, the court may impose a civil penalty not exceeding twenty-five thousand dollars.

. The superior court may grant temporary and final injunctions on such terms as it deems reasonable to prevent or restrain violations of RCW 9A.56.220 and 9A.56.230.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5820-S.SL.pdf?cite=1995%20c%2092%20§%204[1995 c 92 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c430.pdf?cite=1985%20c%20430%20§%204[1985 c 430 § 4]; ]

== 9A.56.260 - Connection of channel converter.
No person may be charged with theft under RCW 9A.56.220 or subject to a civil cause of action under RCW 9A.56.250 for connecting a nondecoding or nondescrambling channel frequency converter, which includes cable-ready television sets, video recorders, or similar equipment, to a cable system.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c430.pdf?cite=1985%20c%20430%20§%205[1985 c 430 § 5]; ]

== 9A.56.262 - Theft of telecommunication services.
. A person is guilty of theft of telecommunication services if he or she knowingly and with intent to avoid payment:

.. Uses a telecommunication device to obtain telecommunication services without having entered into a prior agreement with a telecommunication service provider to pay for the telecommunication services; or

.. Possesses a telecommunication device.

. Theft of telecommunication services is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5820-S.SL.pdf?cite=1995%20c%2092%20§%206[1995 c 92 § 6]; ]

== 9A.56.264 - Unlawful manufacture of telecommunication device.
. A person is guilty of unlawful manufacture of a telecommunication device if he or she knowingly and with intent to avoid payment or to facilitate avoidance of payment:

.. Manufactures, produces, or assembles a telecommunication device;

.. Modifies, alters, programs, or reprograms a telecommunication device to be capable of acquiring or of facilitating the acquisition of telecommunication service without the consent of the telecommunication service provider; or

.. Writes, creates, or modifies a computer program that he or she knows is thereby capable of being used to manufacture a telecommunication device.

. Unlawful manufacture of a telecommunication device is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5820-S.SL.pdf?cite=1995%20c%2092%20§%207[1995 c 92 § 7]; ]

== 9A.56.266 - Unlawful sale of telecommunication device.
. A person is guilty of unlawful sale of a telecommunication device if he or she sells, leases, exchanges, or offers to sell, lease, or exchange:

.. A telecommunication device, knowing that the purchaser, lessee, or recipient, or a third person, intends to use the device to avoid payment or to facilitate avoidance of payment for telecommunication services; or

.. Any material, including data, computer software, or other information and equipment, knowing that the purchaser, lessee, or recipient, or a third person, intends to use the material to avoid payment or to facilitate avoidance of payment for telecommunication services.

. Unlawful sale of a telecommunication device is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5820-S.SL.pdf?cite=1995%20c%2092%20§%208[1995 c 92 § 8]; ]

== 9A.56.268 - Civil cause of action.
. In addition to the criminal penalties provided in RCW 9A.56.262 through 9A.56.266, there is created a civil cause of action for theft of telecommunication services, for unlawful manufacture of a telecommunication device, and for unlawful sale of a telecommunication device.

. A person who sustains injury to his or her person, business, or property by an act described in RCW 9A.56.262, 9A.56.264, or 9A.56.266 may file an action in superior court for recovery of damages and the costs of the suit, including reasonable investigative and attorneys' fees and costs.

. Upon finding a violation of 9A.56.262, 9A.56.264, or 9A.56.266, in addition to the remedies described in this section, the court may impose a civil penalty not exceeding twenty-five thousand dollars.

. The superior court may grant temporary and final injunctions on such terms as it deems reasonable to prevent or restrain violations of RCW 9A.56.262 through 9A.56.266.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5820-S.SL.pdf?cite=1995%20c%2092%20§%209[1995 c 92 § 9]; ]

== 9A.56.270 - Shopping cart theft.
. It is unlawful to do any of the following acts, if a shopping cart has a permanently affixed sign as provided in subsection (2) of this section:

.. To remove a shopping cart from the parking area of a retail establishment with the intent to deprive the owner of the shopping cart the use of the cart; or

.. To be in possession of any shopping cart that has been removed from the parking area of a retail establishment with the intent to deprive the owner of the shopping cart the use of the cart.

. This section shall apply only when a shopping cart: (a) Has a sign permanently affixed to it that identifies the owner of the cart or the retailer, or both; (b) notifies the public of the procedure to be utilized for authorized removal of the cart from the premises; (c) notifies the public that the unauthorized removal of the cart from the premises or parking area of the retail establishment, or the unauthorized possession of the cart, is unlawful; and (d) lists a telephone number or address for returning carts removed from the premises or parking area to the owner or retailer.

. Any person who violates any provision of this section is guilty of a misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c382.pdf?cite=1985%20c%20382%20§%202[1985 c 382 § 2]; ]

== 9A.56.280 - Credit, debit cards, checks, etc.—Definitions.
As used in RCW 9A.56.280, 9A.56.290, 9A.60.020, 9A.56.320, and 9A.56.330, unless the context requires otherwise:

. "Cardholder" means a person to whom a credit card or payment card is issued or a person who otherwise is authorized to use a credit card or payment card.

. "Check" means a negotiable instrument that meets the definition of "check" under RCW 62A.3-104 or a blank form instrument that would meet the definition of "check" under RCW 62A.3-104 if it were completed and signed.

. "Credit card" means a card, plate, booklet, credit card number, credit card account number, or other identifying symbol, instrument, or device that can be used to pay for, or to obtain on credit, goods or services.

. "Credit card or payment card transaction" means a sale or other transaction in which a credit card or payment card is used to pay for, or to obtain on credit, goods or services.

. "Credit card or payment card transaction record" means a record or evidence of a credit card or payment card transaction, including, without limitation, a paper, sales draft, instrument, or other writing and an electronic or magnetic transmission or record.

. "Debit card" means a card used to obtain goods or services by a transaction that debits the cardholder's account, rather than extending credit.

. "Financial information" means financial information as defined in RCW 9.35.005.

. "Financial institution" means a bank, trust company, mutual savings bank, savings and loan association, or credit union authorized under state or federal law to do business and accept deposits in Washington.

. "Means of identification" means means of identification as defined in RCW 9.35.005.

. "Merchant" means an owner or operator of any retail mercantile establishment or any agent, employee, lessee, consignee, officer, director, franchisee, or independent contractor of such owner or operator. "Merchant" also means a person who receives from an authorized user, a payment card or information from a payment card, or what the person believes to be a payment card or information from a payment card, as the instrument for obtaining, purchasing, or receiving goods, services, money, or anything else of value from the person.

. "Payment card" means a credit card, charge card, debit card, stored value card, or any card that is issued to an authorized card user and that allows the user to obtain goods, services, money, or anything else of value from a merchant.

. "Person" means an individual, partnership, corporation, trust, or unincorporated association, but does not include a financial institution or its authorized employees, representatives, or agents.

. "Personal identification" means any driver's license, passport, or identification card actually or purportedly issued by any federal, state, local or foreign governmental entity; any credit card or debit card; or any employee identification card actually or purportedly issued by any employer, public or private, including but not limited to a badge or identification or access card.

. "Reencoder" means an electronic device that places encoded information from a payment card onto a different payment card.

. "Scanning device" means a scanner, reader, or any other electronic device that is used to access, read, scan, obtain, memorize, or store, temporarily or permanently, information encoded on a payment card.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1844-S.SL.pdf?cite=2003%20c%20119%20§%203[2003 c 119 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5719-S.SL.pdf?cite=2003%20c%2052%20§%201[2003 c 52 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5704-S.SL.pdf?cite=1993%20c%20484%20§%201[1993 c 484 § 1]; ]

== 9A.56.290 - Credit, payment cards—Unlawful factoring of transactions.
. A person commits the crime of unlawful factoring of a credit card or payment card transaction if the person:

.. Uses a scanning device to access, read, obtain, memorize, or store, temporarily or permanently, information encoded on a payment card without the permission of the authorized user of the payment card or with the intent to defraud the authorized user, another person, or a financial institution;

.. Uses a reencoder to place information encoded on a payment card onto a different card without the permission of the authorized issuer of the card from which the information is being reencoded or with the intent to defraud the authorized user, another person, or a financial institution;

.. Presents to or deposits with, or causes another to present to or deposit with, a financial institution for payment a credit card or payment card transaction record that is not the result of a credit card or payment card transaction between the cardholder and the person;

.. Employs, solicits, or otherwise causes a merchant or an employee, representative, or agent of a merchant to present to or deposit with a financial institution for payment a credit card or payment card transaction record that is not the result of a credit card or payment card transaction between the cardholder and the merchant; or

.. Employs, solicits, or otherwise causes another to become a merchant for purposes of engaging in conduct made unlawful by this section.

. Normal transactions conducted by or through airline reporting corporation-appointed travel agents or cruise-only travel agents recognized by passenger cruise lines are not considered factoring for the purposes of this section.

. In a proceeding under this section that is related to an identity theft under RCW 9.35.020, the crime will be considered to have been committed in any locality where the person whose means of identification or financial information was appropriated resides, or in which any part of the offense took place, regardless of whether the defendant was ever actually in that locality.

. [Empty]
.. Unlawful factoring of a credit card or payment card transaction is a class C felony.

.. A second or subsequent violation of subsection (1) of this section is a class B felony.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1844-S.SL.pdf?cite=2003%20c%20119%20§%204[2003 c 119 § 4]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5719-S.SL.pdf?cite=2003%20c%2052%20§%202[2003 c 52 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5704-S.SL.pdf?cite=1993%20c%20484%20§%202[1993 c 484 § 2]; ]

== 9A.56.300 - Theft of a firearm.
. A person is guilty of theft of a firearm if he or she commits a theft of any firearm.

. This section applies regardless of the value of the firearm taken in the theft.

. Each firearm taken in the theft under this section is a separate offense.

. The definition of "theft" and the defense allowed against the prosecution for theft under RCW 9A.56.020 shall apply to the crime of theft of a firearm.

. As used in this section, "firearm" means any firearm as defined in RCW 9.41.010.

. Theft of a firearm is a class B felony.

[ 1995 c 129 § 10 (Initiative Measure No. 159); http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=1994%20sp.s.%20c%207%20§%20432[1994 sp.s. c 7 § 432]; ]

== 9A.56.310 - Possessing a stolen firearm.
. A person is guilty of possessing a stolen firearm if he or she possesses, carries, delivers, sells, or is in control of a stolen firearm.

. This section applies regardless of the stolen firearm's value.

. Each stolen firearm possessed under this section is a separate offense.

. The definition of "possessing stolen property" and the defense allowed against the prosecution for possessing stolen property under RCW 9A.56.140 shall apply to the crime of possessing a stolen firearm.

. As used in this section, "firearm" means any firearm as defined in RCW 9.41.010.

. Possessing a stolen firearm is a class B felony.

[ 1995 c 129 § 13 (Initiative Measure No. 159); ]

== 9A.56.320 - Financial fraud—Unlawful possession, production of instruments of.
. A person is guilty of unlawful production of payment instruments if he or she prints or produces a check or other payment instrument in the name of a person or entity, or with the routing number or account number of a person or entity, without the permission of the person or entity to manufacture or reproduce such payment instrument with such name, routing number, or account number.

. [Empty]
.. A person is guilty of unlawful possession of payment instruments if he or she possesses two or more checks or other payment instruments, alone or in combination:

... In the name of a person or entity, or with the routing number or account number of a person or entity, without the permission of the person or entity to possess such payment instrument, and with intent either to deprive the person of possession of such payment instrument or to commit theft, forgery, or identity theft; or

... In the name of a fictitious person or entity, or with a fictitious routing number or account number of a person or entity, with intent to use the payment instruments to commit theft, forgery, or identity theft.

.. (a)(i) of this subsection does not apply to:

... A person or financial institution that has lawful possession of a check, which is endorsed to that person or financial institution; and

... A person or financial institution that processes checks for a lawful business purpose.

. A person is guilty of unlawful possession of a personal identification device if the person possesses a personal identification device with intent to use such device to commit theft, forgery, or identity theft. "Personal identification device" includes any machine or instrument whose purpose is to manufacture or print any driver's license or identification card issued by any state or the federal government, or any employee identification issued by any employer, public or private, including but not limited to badges and identification cards, or any credit or debit card.

. A person is guilty of unlawful possession of fictitious identification if the person possesses a personal identification card with a fictitious person's identification with intent to use such identification card to commit theft, forgery, or identity theft, when the possession does not amount to a violation of RCW 9.35.020.

. A person is guilty of unlawful possession of instruments of financial fraud if the person possesses a check-making machine, equipment, or software, with intent to use or distribute checks for purposes of defrauding an account holder, business, financial institution, or any other person or organization.

. This section does not apply to:

.. A person, business, or other entity, that has lawful possession of a check, which is endorsed to that person, business, or other entity;

.. A financial institution or other entity that processes checks for a lawful business purpose;

.. A person engaged in a lawful business who obtains another person's personal identification in the ordinary course of that lawful business;

.. A person who obtains another person's personal identification for the sole purpose of misrepresenting his or her age; and

.. A law enforcement agency that produces or displays counterfeit credit or debit cards, checks or other payment instruments, or personal identification devices for investigative or educational purposes.

. In a proceeding under this section that is related to an identity theft under RCW 9.35.020, the crime will be considered to have been committed in any locality where the person whose means of identification or financial information was appropriated resides, or in which any part of the offense took place, regardless of whether the defendant was ever actually in that locality.

. A violation of this section is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1844-S.SL.pdf?cite=2003%20c%20119%20§%201[2003 c 119 § 1]; ]

== 9A.56.330 - Possession of another's identification.
. A person is guilty of possession of another's identification if the person knowingly possesses personal identification bearing another person's identity, when the person possessing the personal identification does not have the other person's permission to possess it, and when the possession does not amount to a violation of RCW 9.35.020.

. This section does not apply to:

.. A person who obtains, by means other than theft, another person's personal identification for the sole purpose of misrepresenting his or her age;

.. A person engaged in a lawful business who obtains another person's personal identification in the ordinary course of business;

.. A person who finds another person's lost personal identification, does not intend to deprive the other person of the personal identification or to use it to commit a crime, and takes reasonably prompt steps to return it to its owner; and

.. A law enforcement agency that produces or displays counterfeit credit or debit cards, checks or other payment instruments, or personal identification for investigative or educational purposes.

. In a proceeding under this section that is related to an identity theft under RCW 9.35.020, the crime will be considered to have been committed in any locality where the person whose means of identification or financial information was appropriated resides, or in which any part of the offense took place, regardless of whether the defendant was ever actually in that locality.

. A violation of this section is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1844-S.SL.pdf?cite=2003%20c%20119%20§%202[2003 c 119 § 2]; ]

== 9A.56.340 - Theft with the intent to resell.
. A person is guilty of theft with the intent to resell if he or she commits theft of property with a value of at least two hundred fifty dollars from a mercantile establishment with the intent to resell the property for monetary or other gain.

. The person is guilty of theft with the intent to resell in the first degree if the property has a value of one thousand five hundred dollars or more. Theft with the intent to resell in the first degree is a class B felony.

. The person is guilty of theft with the intent to resell in the second degree if the property has a value of at least two hundred fifty dollars, but less than one thousand five hundred dollars. Theft with the intent to resell in the second degree is a class C felony.

. For purposes of this section, a series of thefts committed by the same person from one or more mercantile establishments over a period of one hundred eighty days may be aggregated in one count and the sum of the value of all the property shall be the value considered in determining the degree of the theft with the intent to resell involved. Thefts committed by the same person in different counties that have been aggregated in one county may be prosecuted in any county in which one of the thefts occurred.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2704.SL.pdf?cite=2006%20c%20277%20§%201[2006 c 277 § 1]; ]

== 9A.56.350 - Organized retail theft.
. A person is guilty of organized retail theft if he or she:

.. Commits theft of property with a value of at least seven hundred fifty dollars from a mercantile establishment with an accomplice;

.. Possesses stolen property, as defined in RCW 9A.56.140, with a value of at least seven hundred fifty dollars from a mercantile establishment with an accomplice;

.. Commits theft of property with a cumulative value of at least seven hundred fifty dollars from one or more mercantile establishments within a period of up to one hundred eighty days; or

.. Commits theft of property with a cumulative value of at least seven hundred fifty dollars from a mercantile establishment with no less than six accomplices and makes or sends at least one electronic communication seeking participation in the theft in the course of planning or commission of the theft. For the purposes of this subsection, "electronic communication" has the same meaning as defined in RCW 9.61.260(5).

. A person is guilty of organized retail theft in the first degree if the property stolen or possessed has a value of five thousand dollars or more. Organized retail theft in the first degree is a class B felony.

. A person is guilty of organized retail theft in the second degree if the property stolen or possessed has a value of at least seven hundred fifty dollars, but less than five thousand dollars. Organized retail theft in the second degree is a class C felony.

. For purposes of this section, a series of thefts committed by the same person from one or more mercantile establishments over a period of one hundred eighty days may be aggregated in one count and the sum of the value of all the property shall be the value considered in determining the degree of the organized retail theft involved. Thefts committed by the same person in different counties that have been aggregated in one county may be prosecuted in any county in which any one of the thefts occurred. For purposes of subsection (1)(d) of this section, thefts committed by the principal and accomplices may be aggregated into one count and the value of all the property shall be the value considered in determining the degree of organized retail theft involved.

. The mercantile establishment or establishments whose property is alleged to have been stolen may request that the charge be aggregated with other thefts of property about which the mercantile establishment or establishments is aware. In the event a request to aggregate the prosecution is declined, the mercantile establishment or establishments shall be promptly advised by the prosecuting jurisdiction making the decision to decline aggregating the prosecution of the decision and the reasons for such decision.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5632.SL.pdf?cite=2017%20c%20329%20§%201[2017 c 329 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6167.SL.pdf?cite=2009%20c%20431%20§%2015[2009 c 431 § 15]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2704.SL.pdf?cite=2006%20c%20277%20§%202[2006 c 277 § 2]; ]

== 9A.56.360 - Retail theft with special circumstances.
. A person commits retail theft with special circumstances if he or she commits theft of property from a mercantile establishment with one of the following special circumstances:

.. To facilitate the theft, the person leaves the mercantile establishment through a designated emergency exit;

.. The person was, at the time of the theft, in possession of an item, article, implement, or device used, under circumstances evincing an intent to use or employ, or designed to overcome security systems including, but not limited to, lined bags or tag removers; or

.. The person committed theft at three or more separate and distinct mercantile establishments within a one hundred eighty-day period.

. A person is guilty of retail theft with special circumstances in the first degree if the theft involved constitutes theft in the first degree. Retail theft with special circumstances in the first degree is a class B felony.

. A person is guilty of retail theft with special circumstances in the second degree if the theft involved constitutes theft in the second degree. Retail theft with special circumstances in the second degree is a class C felony.

. A person is guilty of retail theft with special circumstances in the third degree if the theft involved constitutes theft in the third degree. Retail theft with special circumstances in the third degree is a class C felony.

. For the purposes of this section, "special circumstances" means the particular aggravating circumstances described in subsection (1)(a) through (c) of this section.

. [Empty]
.. A series of thefts committed by the same person from one or more mercantile establishments over a period of one hundred eighty days may be aggregated in one count and the sum of the value of all the property shall be the value considered in determining the degree of the retail theft with special circumstances involved. Thefts committed by the same person in different counties that have been aggregated in one county may be prosecuted in any county in which any one of the thefts occurred. In no case may an aggregated series of thefts, or a single theft that has been aggregated in one county, be prosecuted in more than one county.

.. The mercantile establishment or establishments whose property is alleged to have been stolen may request that the charge be aggregated with other thefts of property about which the mercantile establishment or establishments is aware. In the event a request to aggregate the prosecution is declined, the mercantile establishment or establishments shall be promptly advised by the prosecuting jurisdiction making the decision to decline aggregating the prosecution of the decision and the reasons for the decision.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5635.SL.pdf?cite=2017%20c%20224%20§%201[2017 c 224 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5022-S.SL.pdf?cite=2013%20c%20153%20§%201[2013 c 153 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2704.SL.pdf?cite=2006%20c%20277%20§%203[2006 c 277 § 3]; ]

== 9A.56.370 - Mail theft.
. A person is guilty of mail theft if he or she: (a) Commits theft of mail addressed to three or more different addresses; and (b) commits theft of a minimum of ten separate pieces of mail.

. Each set of ten separate pieces of stolen mail addressed to three or more different mailboxes constitutes a separate and distinct crime and may be punished accordingly.

. Mail theft is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1145-S.SL.pdf?cite=2011%20c%20164%20§%203[2011 c 164 § 3]; ]

== 9A.56.380 - Possession of stolen mail.
. A person is guilty of possession of stolen mail if he or she: (a) Possesses stolen mail addressed to three or more different mailboxes; and (b) possesses a minimum of ten separate pieces of stolen mail.

. "Possesses stolen mail" means to knowingly receive, retain, possess, conceal, or dispose of stolen mail knowing that it has been stolen, and to withhold or appropriate to the use of any person other than the true owner, or the person to whom the mail is addressed.

. The fact that the person who stole the mail has not been convicted, apprehended, or identified is not a defense to the charge of possessing stolen mail.

. Each set of ten separate pieces of stolen mail addressed to three or more different mailboxes constitutes a separate and distinct crime and may be punished accordingly.

. Possession of stolen mail is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1145-S.SL.pdf?cite=2011%20c%20164%20§%204[2011 c 164 § 4]; ]

== 9A.56.390 - Mail theft—Possession of stolen mail—Commission of other crime.
Every person who, in the commission of mail theft or possession of stolen mail, shall commit any other crime, may be punished therefor as well as for the mail theft or possession of stolen mail, and may be prosecuted for each crime separately.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1145-S.SL.pdf?cite=2011%20c%20164%20§%205[2011 c 164 § 5]; ]

== 9A.56.400 - Theft from a vulnerable adult in the first degree—Theft from a vulnerable adult in the second degree.
. [Empty]
.. A person is guilty of theft from a vulnerable adult in the first degree if he or she commits theft of property or services that exceed(s) five thousand dollars in value, other than a firearm as defined in RCW 9.41.010, of a vulnerable adult. The defendant must have known or should have known that the victim was a vulnerable adult.

.. Theft from a vulnerable adult in the first degree is a class B felony.

. [Empty]
.. A person is guilty of theft from a vulnerable adult in the second degree if he or she commits theft of property or services that exceed(s) seven hundred fifty dollars in value but does not exceed five thousand dollars in value, other than a firearm as defined in RCW 9.41.010 or a motor vehicle, of a vulnerable adult. The defendant must have known or should have known that the victim was a vulnerable adult.

.. Theft from a vulnerable adult in the second degree is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1153-S.SL.pdf?cite=2017%20c%20266%20§%206[2017 c 266 § 6]; ]

