= 9A.58 - Identification documents.
:toc:

== 9A.58.005 - Findings.
The legislature finds that:

. Washington state recognizes the importance of protecting

its citizens from unwanted wireless surveillance.

. Enhanced drivers' licenses and enhanced identicards are intended to facilitate efficient travel at land and sea borders between the United States, Canada, and Mexico, not to facilitate the profiling and tracking of individuals.

. Easy access to the information found on enhanced drivers' licenses and enhanced identicards could facilitate the commission of other unwanted offenses, such as identity theft.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2729-S.SL.pdf?cite=2008%20c%20200%20§%201[2008 c 200 § 1]; ]

== 9A.58.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Enhanced driver's license" means a driver's license that is issued under RCW 46.20.202.

. "Enhanced identicard" means an identicard that is issued under RCW 46.20.202.

. "Identification document" means an enhanced driver's license or an enhanced identicard.

. "Radio frequency identification" means a technology that uses radio waves to transmit data remotely to readers.

. "Reader" means a scanning device that is capable of using radio waves to communicate with an identification document and read the data transmitted by the identification document.

. "Remotely" means that no physical contact between the identification document and a reader is necessary in order to transmit data using radio waves.

. "Unique personal identifier number" means a randomly assigned string of numbers or symbols issued by the department of licensing that is encoded on an identification document and is intended to be read remotely by a reader to identify the identification document that has been issued to a particular individual.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2729-S.SL.pdf?cite=2008%20c%20200%20§%202[2008 c 200 § 2]; ]

== 9A.58.020 - Possessing, or reading or capturing, information contained on another person's identification document—Exceptions.
. Except as provided in subsection (2) of this section, a person is guilty of a class C felony if the person intentionally possesses, or reads or captures remotely using radio waves, information contained on another person's identification document, including the unique personal identifier number encoded on the identification document, without that person's express knowledge or consent.

. This section does not apply to:

.. A person or entity that reads an identification document to facilitate border crossing;

.. A person or entity that reads a person's identification document in the course of an act of good faith security research, experimentation, or scientific inquiry including, but not limited to, activities useful in identifying and analyzing security flaws and vulnerabilities; or

.. A person or entity that unintentionally reads an identification document remotely in the course of operating its own radio frequency identification system, provided that the inadvertently received information:

... Is not disclosed to any other party;

... Is not used for any purpose; and

... Is not stored or is promptly destroyed.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2729-S.SL.pdf?cite=2008%20c%20200%20§%203[2008 c 200 § 3]; ]

== 9A.58.030 - Violation—Consumer protection act.
The legislature finds that the practices covered by this chapter are matters vitally affecting the public interest for the purpose of applying chapter 19.86 RCW. A violation of this chapter is not reasonable in relation to the development and preservation of business and is an unfair or deceptive act in trade or commerce and an unfair method of competition for the purpose of applying chapter 19.86 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2729-S.SL.pdf?cite=2008%20c%20200%20§%204[2008 c 200 § 4]; ]

