= 9A.64 - Family offenses.
:toc:

== 9A.64.010 - Bigamy.
. A person is guilty of bigamy if he or she intentionally marries or purports to marry another person when either person has a living spouse.

. In any prosecution under this section, it is a defense that at the time of the subsequent marriage or purported marriage:

.. The actor reasonably believed that the prior spouse was dead; or

.. A court had entered a judgment purporting to terminate or annul any prior disqualifying marriage and the actor did not know that such judgment was invalid; or

.. The actor reasonably believed that he or she was legally eligible to marry.

. The limitation imposed by RCW 9A.04.080 on commencing a prosecution for bigamy does not begin to run until the death of the prior or subsequent spouse of the actor or until a court enters a judgment terminating or annulling the prior or subsequent marriage.

. Bigamy is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20385[2011 c 336 § 385]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c257.pdf?cite=1986%20c%20257%20§%2014[1986 c 257 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.64.010[1975 1st ex.s. c 260 § 9A.64.010]; ]

== 9A.64.020 - Incest.
. [Empty]
.. A person is guilty of incest in the first degree if he or she engages in sexual intercourse with a person whom he or she knows to be related to him or her, either legitimately or illegitimately, as an ancestor, descendant, brother, or sister of either the whole or the half blood.

.. Incest in the first degree is a class B felony.

. [Empty]
.. A person is guilty of incest in the second degree if he or she engages in sexual contact with a person whom he or she knows to be related to him or her, either legitimately or illegitimately, as an ancestor, descendant, brother, or sister of either the whole or the half blood.

.. Incest in the second degree is a class C felony.

. As used in this section:

.. "Descendant" includes stepchildren and adopted children under eighteen years of age;

.. "Sexual contact" has the same meaning as in RCW 9A.44.010; and

.. "Sexual intercourse" has the same meaning as in RCW 9A.44.010.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%2080[2003 c 53 § 80]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1142.SL.pdf?cite=1999%20c%20143%20§%2039[1999 c 143 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c53.pdf?cite=1985%20c%2053%20§%201[1985 c 53 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c129.pdf?cite=1982%20c%20129%20§%203[1982 c 129 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.64.020[1975 1st ex.s. c 260 § 9A.64.020]; ]

== 9A.64.030 - Child selling—Child buying.
. It is unlawful for any person to sell or purchase a minor child.

. A transaction shall not be a purchase or sale under subsection (1) of this section if any of the following exists:

.. The transaction is between the parents of the minor child; or

.. The transaction is between a person receiving or to receive the child and an agency recognized under RCW 26.33.020; or

.. The transaction is between the person receiving or to receive the child and a state agency or other governmental agency; or

.. The transaction is pursuant to chapter 26.34 RCW; or

.. The transaction is pursuant to court order; or

.. The only consideration paid by the person receiving or to receive the child is intended to pay for the prenatal hospital or medical expenses involved in the birth of the child, or attorneys' fees and court costs involved in effectuating transfer of child custody.

. [Empty]
.. Child selling is a class C felony.

.. Child buying is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%2081[2003 c 53 § 81]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%203[1985 c 7 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c85.pdf?cite=1980%20c%2085%20§%203[1980 c 85 § 3]; ]

