= 9A.61 - Defrauding a public utility.
:toc:

== 9A.61.010 - Definitions.
The definitions set forth in this section apply throughout this chapter.

. "Customer" means the person in whose name a utility service is provided.

. "Divert" means to change the intended course or path of electricity, gas, or water without the authorization or consent of the utility.

. "Person" means an individual, partnership, firm, association, or corporation or government agency.

. "Reconnection" means the commencement of utility service to a customer or other person after service has been lawfully disconnected by the utility.

. "Tamper" means to rearrange, injure, alter, interfere with, or otherwise prevent from performing the normal or customary function.

. "Utility" means an electrical company, gas company, or water company as those terms are defined in RCW 80.04.010, and includes an electrical, gas, or water system operated by a public agency.

. "Utility service" means the provision of electricity, gas, water, or any other service or commodity furnished by the utility for compensation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c109.pdf?cite=1989%20c%20109%20§%201[1989 c 109 § 1]; ]

== 9A.61.020 - Defrauding a public utility.
"Defrauding a public utility" means to commit, authorize, solicit, aid, abet, or attempt to:

. Divert, or cause to be diverted, utility services by any means whatsoever;

. Make, or cause to be made, a connection or reconnection with property owned or used by the utility to provide utility service without the authorization or consent of the utility;

. Prevent a utility meter or other device used in determining the charge for utility services from accurately performing its measuring function by tampering or by any other means;

. Tamper with property owned or used by the utility to provide utility services; or

. Use or receive the direct benefit of all or a portion of the utility service with knowledge of, or reason to believe that, the diversion, tampering, or unauthorized connection existed at the time of the use or that the use or receipt was without the authorization or consent of the utility.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c109.pdf?cite=1989%20c%20109%20§%202[1989 c 109 § 2]; ]

== 9A.61.030 - Defrauding a public utility in the first degree.
. A person is guilty of defrauding a public utility in the first degree if:

.. The utility service diverted or used exceeds one thousand five hundred dollars in value; or

.. Tampering has occurred in furtherance of other criminal activity.

. Defrauding a public utility in the first degree is a class B felony.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c109.pdf?cite=1989%20c%20109%20§%203[1989 c 109 § 3]; ]

== 9A.61.040 - Defrauding a public utility in the second degree.
. A person is guilty of defrauding a public utility in the second degree if the utility service diverted or used exceeds five hundred dollars in value.

. Defrauding a public utility in the second degree is a class C felony.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c109.pdf?cite=1989%20c%20109%20§%204[1989 c 109 § 4]; ]

== 9A.61.050 - Defrauding a public utility in the third degree.
. A person is guilty of defrauding a public utility in the third degree if:

.. The utility service diverted or used is five hundred dollars or less in value; or

.. A connection or reconnection has occurred without authorization or consent of the utility.

. Defrauding a public utility in the third degree is a gross misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c109.pdf?cite=1989%20c%20109%20§%205[1989 c 109 § 5]; ]

== 9A.61.060 - Restitution and costs.
In any prosecution under this section, the court may require restitution from the defendant as provided by chapter 9A.20 RCW, plus court costs plus the costs incurred by the utility on account of the bypassing, tampering, or unauthorized reconnection, including but not limited to costs and expenses for investigation, disconnection, reconnection, service calls, and expert witnesses.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c109.pdf?cite=1989%20c%20109%20§%206[1989 c 109 § 6]; ]

== 9A.61.070 - Damages not precluded.
Restitution ordered or fines imposed under this chapter do not preclude a utility from collecting damages under RCW 80.28.240 to which it may be entitled.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c109.pdf?cite=1989%20c%20109%20§%207[1989 c 109 § 7]; ]

