= 9A.60 - Fraud.
:toc:

== 9A.60.010 - Definitions.
The following definitions and the definitions of RCW 9A.56.010 are applicable in this chapter unless the context otherwise requires:

. "Complete written instrument" means one which is fully drawn with respect to every essential feature thereof;

. "Incomplete written instrument" means one which contains some matter by way of content or authentication but which requires additional matter in order to render it a complete written instrument;

. To "falsely alter" a written instrument means to change, without authorization by anyone entitled to grant it, a written instrument, whether complete or incomplete, by means of erasure, obliteration, deletion, insertion of new matter, transposition of matter, or in any other manner;

. To "falsely complete" a written instrument means to transform an incomplete written instrument into a complete one by adding or inserting matter, without the authority of anyone entitled to grant it;

. To "falsely make" a written instrument means to make or draw a complete or incomplete written instrument which purports to be authentic, but which is not authentic either because the ostensible maker is fictitious or because, if real, he or she did not authorize the making or drawing thereof;

. "Forged instrument" means a written instrument which has been falsely made, completed, or altered;

. "Written instrument" means: (a) Any paper, document, or other instrument containing written or printed matter or its equivalent; or (b) any access device, token, stamp, seal, badge, trademark, or other evidence or symbol of value, right, privilege, or identification.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20381[2011 c 336 § 381]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1142.SL.pdf?cite=1999%20c%20143%20§%2038[1999 c 143 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c140.pdf?cite=1987%20c%20140%20§%205[1987 c 140 § 5]; 1975-'76 2nd ex.s. c 38 § 12; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.60.010[1975 1st ex.s. c 260 § 9A.60.010]; ]

== 9A.60.020 - Forgery.
. A person is guilty of forgery if, with intent to injure or defraud:

.. He or she falsely makes, completes, or alters a written instrument or;

.. He or she possesses, utters, offers, disposes of, or puts off as true a written instrument which he or she knows to be forged.

. In a proceeding under this section that is related to an identity theft under RCW 9.35.020, the crime will be considered to have been committed in any locality where the person whose means of identification or financial information was appropriated resides, or in which any part of the offense took place, regardless of whether the defendant was ever actually in that locality.

. Forgery is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20382[2011 c 336 § 382]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1844-S.SL.pdf?cite=2003%20c%20119%20§%205[2003 c 119 § 5]; 1975-'76 2nd ex.s. c 38 § 13; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.60.020[1975 1st ex.s. c 260 § 9A.60.020]; ]

== 9A.60.030 - Obtaining a signature by deception or duress.
. A person is guilty of obtaining a signature by deception or duress if by deception or duress and with intent to defraud or deprive he or she causes another person to sign or execute a written instrument.

. Obtaining a signature by deception or duress is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20383[2011 c 336 § 383]; 1975-'76 2nd ex.s. c 38 § 14; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.60.030[1975 1st ex.s. c 260 § 9A.60.030]; ]

== 9A.60.040 - Criminal impersonation in the first degree.
. A person is guilty of criminal impersonation in the first degree if the person:

.. Assumes a false identity and does an act in his or her assumed character with intent to defraud another or for any other unlawful purpose; or

.. Pretends to be a representative of some person or organization or a public servant and does an act in his or her pretended capacity with intent to defraud another or for any other unlawful purpose.

. Criminal impersonation in the first degree is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6177.SL.pdf?cite=2004%20c%2011%20§%201[2004 c 11 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%2078[2003 c 53 § 78]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1689.SL.pdf?cite=1993%20c%20457%20§%201[1993 c 457 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.60.040[1975 1st ex.s. c 260 § 9A.60.040]; ]

== 9A.60.045 - Criminal impersonation in the second degree.
. A person is guilty of criminal impersonation in the second degree if the person:

.. [Empty]
... Claims to be a law enforcement officer or creates an impression that he or she is a law enforcement officer; and

... Under circumstances not amounting to criminal impersonation in the first degree, does an act with intent to convey the impression that he or she is acting in an official capacity and a reasonable person would believe the person is a law enforcement officer; or

.. Falsely assumes the identity of a veteran or active duty member of the armed forces of the United States with intent to defraud for the purpose of personal gain or to facilitate any unlawful activity.

. Criminal impersonation in the second degree is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5861-S.SL.pdf?cite=2004%20c%20124%20§%201[2004 c 124 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6177.SL.pdf?cite=2004%20c%2011%20§%202[2004 c 11 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%2079[2003 c 53 § 79]; ]

== 9A.60.050 - False certification.
. A person is guilty of false certification, if, being an officer authorized to take a proof or acknowledgment of an instrument which by law may be recorded, he or she knowingly certifies falsely that the execution of such instrument was acknowledged by any party thereto or that the execution thereof was proved.

. A person is guilty of false certification, if, being a notarial officer making a certification authorized by RCW 42.45.020(3), he or she knowingly certifies falsely that a tangible copy of an electronic record is an accurate copy of the electronic record.

. False certification is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5641.SL.pdf?cite=2019%20c%20154%20§%207[2019 c 154 § 7]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20384[2011 c 336 § 384]; 1975-'76 2nd ex.s. c 38 § 15; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.60.050[1975 1st ex.s. c 260 § 9A.60.050]; ]

== 9A.60.060 - Fraudulent creation or revocation of a mental health advance directive.
. For purposes of this section "mental health advance directive" means a written document that is a "mental health advance directive" as defined in RCW 71.32.020.

. A person is guilty of fraudulent creation or revocation of a mental health advance directive if he or she knowingly:

.. Makes, completes, alters, or revokes the mental health advance directive of another without the principal's consent;

.. Utters, offers, or puts off as true a mental health advance directive that he or she knows to be forged; or

.. Obtains or prevents the signature of a principal or witness to a mental health advance directive by deception or duress.

. Fraudulent creation or revocation of a mental health advance directive is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5223-S.SL.pdf?cite=2003%20c%20283%20§%2031[2003 c 283 § 31]; ]

== 9A.60.070 - False academic credentials—Unlawful issuance or use—Definitions—Penalties.
. A person is guilty of issuing a false academic credential if the person knowingly:

.. Grants or awards a false academic credential or offers to grant or award a false academic credential in violation of this section;

.. Represents that a credit earned or granted by the person in violation of this section can be applied toward a credential offered by another person;

.. Grants or offers to grant a credit for which a representation as described in (b) of this subsection is made; or

.. Solicits another person to seek a credential or to earn a credit the person knows is offered in violation of this section.

. A person is guilty of knowingly using a false academic credential if the person knowingly uses a false academic credential or falsely claims to have a credential issued by an institution of higher education that is accredited by an accrediting association recognized as such by rule of the student achievement council:

.. In a written or oral advertisement or other promotion of a business; or

.. With the intent to:

... Obtain employment;

... Obtain a license or certificate to practice a trade, profession, or occupation;

... Obtain a promotion, compensation or other benefit, or an increase in compensation or other benefit, in employment or in the practice of a trade, profession, or occupation;

... Obtain admission to an educational program in this state; or

.. Gain a position in government with authority over another person, regardless of whether the person receives compensation for the position.

. The definitions in this subsection apply throughout this section and RCW 28B.85.220.

.. "False academic credential" means a document that provides evidence or demonstrates completion of an academic or professional course of instruction beyond the secondary level that results in the attainment of an academic certificate, degree, or rank, and that is not issued by a person or entity that: (i) Is an entity accredited by an agency recognized as such by rule of the student achievement council or has the international equivalents of such accreditation; or (ii) is an entity authorized as a degree-granting institution by the student achievement council; or (iii) is an entity exempt from the requirements of authorization as a degree-granting institution by the student achievement council; or (iv) is an entity that has been granted a waiver by the student achievement council from the requirements of authorization by the council. Such documents include, but are not limited to, academic certificates, degrees, coursework, degree credits, transcripts, or certification of completion of a degree.

.. "Grant" means award, bestow, confer, convey, sell, or give.

.. "Offer," in addition to its usual meanings, means advertise, publicize, or solicit.

.. "Operate" includes but is not limited to the following:

... Offering courses in person, by correspondence, or by electronic media at or to any Washington location for degree credit;

... Granting or offering to grant degrees in Washington;

... Maintaining or advertising a Washington location, mailing address, computer server, or telephone number, for any purpose, other than for contact with the institution's former students for any legitimate purpose related to the students having attended the institution.

. Issuing a false academic credential is a class C felony.

. Knowingly using a false academic credential is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20501[2012 c 229 § 501]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2507-S.SL.pdf?cite=2006%20c%20234%20§%202[2006 c 234 § 2]; ]

== 9A.60.080 - Impersonating a census taker.
. A person is guilty of impersonating a census taker if the person falsely represents that he or she is a census taker with the intent to:

.. Interfere with the operation of the census;

.. Obtain information; or

.. Obtain consent to enter a private dwelling.

. Impersonating a census taker is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2527-S.SL.pdf?cite=2020%20c%2034%20§%202[2020 c 34 § 2]; ]

