= 9A.72 - Perjury and interference with official proceedings.
:toc:

== 9A.72.010 - Definitions.
The following definitions are applicable in this chapter unless the context otherwise requires:

. "Materially false statement" means any false statement oral or written, regardless of its admissibility under the rules of evidence, which could have affected the course or outcome of the proceeding;

. "Oath" includes an affirmation and every other mode authorized by law of attesting to the truth of that which is stated; in this chapter, written statements shall be treated as if made under oath if:

.. The statement was made on or pursuant to instructions on an official form bearing notice, authorized by law, to the effect that false statements made therein are punishable;

.. The statement recites that it was made under oath, the declarant was aware of such recitation at the time he or she made the statement, intended that the statement should be represented as a sworn statement, and the statement was in fact so represented by its delivery or utterance with the signed jurat of an officer authorized to administer oaths appended thereto; or

.. It is a statement, declaration, verification, or certificate, made within or outside the state of Washington, which is declared to be true under penalty of perjury as provided in chapter 5.50 RCW.

. An oath is "required or authorized by law" when the use of the oath is specifically provided for by statute or regulatory provision or when the oath is administered by a person authorized by state or federal law to administer oaths;

. "Official proceeding" means a proceeding heard before any legislative, judicial, administrative, or other government agency or official authorized to hear evidence under oath, including any referee, hearing examiner, commissioner, notary, or other person taking testimony or depositions;

. "Juror" means any person who is a member of any jury, including a grand jury, impaneled by any court of this state or by any public servant authorized by law to impanel a jury; the term juror also includes any person who has been drawn or summoned to attend as a prospective juror;

. "Testimony" includes oral or written statements, documents, or any other material that may be offered by a witness in an official proceeding.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5017-S.SL.pdf?cite=2019%20c%20232%20§%2010[2019 c 232 § 10]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1692.SL.pdf?cite=2001%20c%20171%20§%202[2001 c 171 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1557-S2.SL.pdf?cite=1995%20c%20285%20§%2030[1995 c 285 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c187.pdf?cite=1981%20c%20187%20§%201[1981 c 187 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.72.010[1975 1st ex.s. c 260 § 9A.72.010]; ]

== 9A.72.020 - Perjury in the first degree.
. A person is guilty of perjury in the first degree if in any official proceeding he or she makes a materially false statement which he or she knows to be false under an oath required or authorized by law.

. Knowledge of the materiality of the statement is not an element of this crime, and the actor's mistaken belief that his or her statement was not material is not a defense to a prosecution under this section.

. Perjury in the first degree is a class B felony.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20391[2011 c 336 § 391]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.72.020[1975 1st ex.s. c 260 § 9A.72.020]; ]

== 9A.72.030 - Perjury in the second degree.
. A person is guilty of perjury in the second degree if, in an examination under oath under the terms of a contract of insurance, or with intent to mislead a public servant in the performance of his or her duty, he or she makes a materially false statement, which he or she knows to be false under an oath required or authorized by law.

. Perjury in the second degree is a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1692.SL.pdf?cite=2001%20c%20171%20§%203[2001 c 171 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1557-S2.SL.pdf?cite=1995%20c%20285%20§%2031[1995 c 285 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.72.030[1975 1st ex.s. c 260 § 9A.72.030]; ]

== 9A.72.040 - False swearing.
. A person is guilty of false swearing if he or she makes a false statement, which he or she knows to be false, under an oath required or authorized by law.

. False swearing is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20392[2011 c 336 § 392]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.72.040[1975 1st ex.s. c 260 § 9A.72.040]; ]

== 9A.72.050 - Perjury and false swearing—Inconsistent statements—Degree of crime.
. Where, in the course of one or more official proceedings, a person makes inconsistent material statements under oath, the prosecution may proceed by setting forth the inconsistent statements in a single count alleging in the alternative that one or the other was false and known by the defendant to be false. In such case it shall not be necessary for the prosecution to prove which material statement was false but only that one or the other was false and known by the defendant to be false.

. The highest offense of which a person may be convicted in such an instance as set forth in subsection (1) of this section shall be determined by hypothetically assuming each statement to be false. If perjury of different degrees would be established by the making of the two statements, the person may only be convicted of the lesser degree. If perjury or false swearing would be established by the making of the two statements, the person may only be convicted of false swearing. For purposes of this section, no corroboration shall be required of either inconsistent statement.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.72.050[1975 1st ex.s. c 260 § 9A.72.050]; ]

== 9A.72.060 - Perjury and false swearing—Retraction.
No person shall be convicted of perjury or false swearing if he or she retracts his or her false statement in the course of the same proceeding in which it was made, if in fact he or she does so before it becomes manifest that the falsification is or will be exposed and before the falsification substantially affects the proceeding. Statements made in separate hearings at separate stages of the same trial, administrative, or other official proceeding shall be treated as if made in the course of the same proceeding.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20393[2011 c 336 § 393]; 1975-'76 2nd ex.s. c 38 § 16; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.72.060[1975 1st ex.s. c 260 § 9A.72.060]; ]

== 9A.72.070 - Perjury and false swearing—Irregularities no defense.
It is no defense to a prosecution for perjury or false swearing:

. That the oath was administered or taken in an irregular manner; or

. That the person administering the oath lacked authority to do so, if the taking of the oath was required or authorized by law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.72.070[1975 1st ex.s. c 260 § 9A.72.070]; ]

== 9A.72.080 - Statement of what one does not know to be true.
Every unqualified statement of that which one does not know to be true is equivalent to a statement of that which he or she knows to be false.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20394[2011 c 336 § 394]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.72.080[1975 1st ex.s. c 260 § 9A.72.080]; ]

== 9A.72.085 - Unsworn statements, certification—Standards for subscribing to an unsworn statement. (Effective until July 1, 2021.)
. Whenever, under any law of this state or under any rule, order, or requirement made under the law of this state, any matter in an official proceeding is required or permitted to be supported, evidenced, established, or proved by a person's sworn written statement, declaration, verification, certificate, oath, or affidavit, the matter may with like force and effect be supported, evidenced, established, or proved in the official proceeding by an unsworn written statement, declaration, verification, or certificate, which:

.. Recites that it is certified or declared by the person to be true under penalty of perjury;

.. Is subscribed by the person;

.. States the date and place of its execution; and

.. States that it is so certified or declared under the laws of the state of Washington.

. The certification or declaration may be in substantially the following form:

"I certify (or declare) under penalty of perjury under the laws of the State of Washington that the foregoing is true and correct":. . . .. . . .(Date and Place)(Signature)

"I certify (or declare) under penalty of perjury under the laws of the State of Washington that the foregoing is true and correct":

. . . .

. . . .

(Date and Place)

(Signature)

. For purposes of this section, a person subscribes to an unsworn written statement, declaration, verification, or certificate by:

.. Affixing or placing his or her signature as defined in RCW 9A.04.110 on the document;

.. Attaching or logically associating his or her digital signature or electronic signature to the document;

.. Affixing or logically associating his or her signature in the manner described in general rule 30 to the document if he or she is a licensed attorney; or

.. Affixing or logically associating his or her full name, department or agency, and badge or personnel number to any document that is electronically submitted to a court, a prosecutor, or a magistrate from an electronic device that is owned, issued, or maintained by a criminal justice agency if he or she is a law enforcement officer.

. This section does not apply to writings requiring an acknowledgment, depositions, oaths of office, or oaths required to be taken before a special official other than a notary public.

. "Digital signature" means an electronic signature that is a transformation of a message using an asymmetric cryptosystem such that a person who has the initial message and the signer's public key can accurately determine whether the:

.. Transformation was created using the private key that corresponds to the signer's public key; and

.. Initial message has been altered since the transformation was made.

. "Electronic signature" has the same meaning as in *RCW 19.360.030.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1908.SL.pdf?cite=2019%20c%20132%20§%202[2019 c 132 § 2]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6279-S.SL.pdf?cite=2014%20c%2093%20§%204[2014 c 93 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c187.pdf?cite=1981%20c%20187%20§%203[1981 c 187 § 3]; ]

== 9A.72.090 - Bribing a witness.
. A person is guilty of bribing a witness if he or she offers, confers, or agrees to confer any benefit upon a witness or a person he or she has reason to believe is about to be called as a witness in any official proceeding or upon a person whom he or she has reason to believe may have information relevant to a criminal investigation or the abuse or neglect of a minor child, with intent to:

.. Influence the testimony of that person; or

.. Induce that person to avoid legal process summoning him or her to testify; or

.. Induce that person to absent himself or herself from an official proceeding to which he or she has been legally summoned; or

.. Induce that person to refrain from reporting information relevant to a criminal investigation or the abuse or neglect of a minor child.

. Bribing a witness is a class B felony.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6007-S.SL.pdf?cite=1994%20c%20271%20§%20202[1994 c 271 § 202]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c47.pdf?cite=1982%201st%20ex.s.%20c%2047%20§%2016[1982 1st ex.s. c 47 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.72.090[1975 1st ex.s. c 260 § 9A.72.090]; ]

== 9A.72.100 - Bribe receiving by a witness.
. A witness or a person who has reason to believe he or she is about to be called as a witness in any official proceeding or that he or she may have information relevant to a criminal investigation or the abuse or neglect of a minor child is guilty of bribe receiving by a witness if he or she requests, accepts, or agrees to accept any benefit pursuant to an agreement or understanding that:

.. The person's testimony will thereby be influenced; or

.. The person will attempt to avoid legal process summoning him or her to testify; or

.. The person will attempt to absent himself or herself from an official proceeding to which he or she has been legally summoned; or

.. The person will not report information he or she has relevant to a criminal investigation or the abuse or neglect of a minor child.

. Bribe receiving by a witness is a class B felony.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6007-S.SL.pdf?cite=1994%20c%20271%20§%20203[1994 c 271 § 203]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c47.pdf?cite=1982%201st%20ex.s.%20c%2047%20§%2017[1982 1st ex.s. c 47 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.72.100[1975 1st ex.s. c 260 § 9A.72.100]; ]

== 9A.72.110 - Intimidating a witness.
. A person is guilty of intimidating a witness if a person, by use of a threat against a current or prospective witness, attempts to:

.. Influence the testimony of that person;

.. Induce that person to elude legal process summoning him or her to testify;

.. Induce that person to absent himself or herself from such proceedings; or

.. Induce that person not to report the information relevant to a criminal investigation or the abuse or neglect of a minor child, not to have the crime or the abuse or neglect of a minor child prosecuted, or not to give truthful or complete information relevant to a criminal investigation or the abuse or neglect of a minor child.

. A person also is guilty of intimidating a witness if the person directs a threat to a former witness because of the witness's role in an official proceeding.

. As used in this section:

.. "Threat" means:

... To communicate, directly or indirectly, the intent immediately to use force against any person who is present at the time; or

... Threat as defined in *RCW 9A.04.110(27).

.. "Current or prospective witness" means:

... A person endorsed as a witness in an official proceeding;

... A person whom the actor believes may be called as a witness in any official proceeding; or

... A person whom the actor has reason to believe may have information relevant to a criminal investigation or the abuse or neglect of a minor child.

.. "Former witness" means:

... A person who testified in an official proceeding;

... A person who was endorsed as a witness in an official proceeding;

... A person whom the actor knew or believed may have been called as a witness if a hearing or trial had been held; or

... A person whom the actor knew or believed may have provided information related to a criminal investigation or an investigation into the abuse or neglect of a minor child.

. Intimidating a witness is a class B felony.

. For purposes of this section, each instance of an attempt to intimidate a witness constitutes a separate offense.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1182.SL.pdf?cite=2011%20c%20165%20§%202[2011 c 165 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5520.SL.pdf?cite=1997%20c%2029%20§%201[1997 c 29 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6007-S.SL.pdf?cite=1994%20c%20271%20§%20204[1994 c 271 § 204]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c327.pdf?cite=1985%20c%20327%20§%202[1985 c 327 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c47.pdf?cite=1982%201st%20ex.s.%20c%2047%20§%2018[1982 1st ex.s. c 47 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.72.110[1975 1st ex.s. c 260 § 9A.72.110]; ]

== 9A.72.120 - Tampering with a witness.
. A person is guilty of tampering with a witness if he or she attempts to induce a witness or person he or she has reason to believe is about to be called as a witness in any official proceeding or a person whom he or she has reason to believe may have information relevant to a criminal investigation or the abuse or neglect of a minor child to:

.. Testify falsely or, without right or privilege to do so, to withhold any testimony; or

.. Absent himself or herself from such proceedings; or

.. Withhold from a law enforcement agency information which he or she has relevant to a criminal investigation or the abuse or neglect of a minor child to the agency.

. Tampering with a witness is a class C felony.

. For purposes of this section, each instance of an attempt to tamper with a witness constitutes a separate offense.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1182.SL.pdf?cite=2011%20c%20165%20§%203[2011 c 165 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6007-S.SL.pdf?cite=1994%20c%20271%20§%20205[1994 c 271 § 205]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c47.pdf?cite=1982%201st%20ex.s.%20c%2047%20§%2019[1982 1st ex.s. c 47 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.72.120[1975 1st ex.s. c 260 § 9A.72.120]; ]

== 9A.72.130 - Intimidating a juror.
. A person is guilty of intimidating a juror if a person directs a threat to a former juror because of the juror's vote, opinion, decision, or other official action as a juror, or if, by use of a threat, he or she attempts to influence a juror's vote, opinion, decision, or other official action as a juror.

. "Threat" as used in this section means:

.. To communicate, directly or indirectly, the intent immediately to use force against any person who is present at the time; or

.. Threats as defined in RCW 9A.04.110.

. Intimidating a juror is a class B felony.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20395[2011 c 336 § 395]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c327.pdf?cite=1985%20c%20327%20§%203[1985 c 327 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.72.130[1975 1st ex.s. c 260 § 9A.72.130]; ]

== 9A.72.140 - Jury tampering.
. A person is guilty of jury tampering if with intent to influence a juror's vote, opinion, decision, or other official action in a case, he or she attempts to communicate directly or indirectly with a juror other than as part of the proceedings in the trial of the case.

. Jury tampering is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20396[2011 c 336 § 396]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.72.140[1975 1st ex.s. c 260 § 9A.72.140]; ]

== 9A.72.150 - Tampering with physical evidence.
. A person is guilty of tampering with physical evidence if, having reason to believe that an official proceeding is pending or about to be instituted and acting without legal right or authority, he or she:

.. Destroys, mutilates, conceals, removes, or alters physical evidence with intent to impair its appearance, character, or availability in such pending or prospective official proceeding; or

.. Knowingly presents or offers any false physical evidence.

. "Physical evidence" as used in this section includes any article, object, document, record, or other thing of physical substance.

. Tampering with physical evidence is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20397[2011 c 336 § 397]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.72.150[1975 1st ex.s. c 260 § 9A.72.150]; ]

== 9A.72.160 - Intimidating a judge.
. A person is guilty of intimidating a judge if a person directs a threat to a judge because of a ruling or decision of the judge in any official proceeding, or if by use of a threat directed to a judge, a person attempts to influence a ruling or decision of the judge in any official proceeding.

. "Threat" as used in this section means:

.. To communicate, directly or indirectly, the intent immediately to use force against any person who is present at the time; or

.. Threats as defined in *RCW 9A.04.110(25).

. Intimidating a judge is a class B felony.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c327.pdf?cite=1985%20c%20327%20§%201[1985 c 327 § 1]; ]

