= 9A.84 - Public disturbance.
:toc:

== 9A.84.010 - Criminal mischief.
. A person is guilty of the crime of criminal mischief if, acting with three or more other persons, he or she knowingly and unlawfully uses or threatens to use force, or in any way participates in the use of such force, against any other person or against property.

. [Empty]
.. Except as provided in (b) of this subsection, the crime of criminal mischief is a gross misdemeanor.

.. The crime of criminal mischief is a class C felony if the actor is armed with a deadly weapon.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5021-S.SL.pdf?cite=2013%20c%2020%20§%201[2013 c 20 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%2091[2003 c 53 § 91]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.84.010[1975 1st ex.s. c 260 § 9A.84.010]; ]

== 9A.84.020 - Failure to disperse.
. A person is guilty of failure to disperse if:

.. He or she congregates with a group of three or more other persons and there are acts of conduct within that group which create a substantial risk of causing injury to any person, or substantial harm to property; and

.. He or she refuses or fails to disperse when ordered to do so by a peace officer or other public servant engaged in enforcing or executing the law.

. Failure to disperse is a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20410[2011 c 336 § 410]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.84.020[1975 1st ex.s. c 260 § 9A.84.020]; ]

== 9A.84.030 - Disorderly conduct.
. A person is guilty of disorderly conduct if the person:

.. Uses abusive language and thereby intentionally creates a risk of assault;

.. Intentionally disrupts any lawful assembly or meeting of persons without lawful authority;

.. Intentionally obstructs vehicular or pedestrian traffic without lawful authority; or

.. [Empty]
... Intentionally engages in fighting or in tumultuous conduct or makes unreasonable noise, within five hundred feet of:

(A) The location where a funeral or burial is being performed;

(B) A funeral home during the viewing of a deceased person;

(C) A funeral procession, if the person described in this subsection (1)(d) knows that the funeral procession is taking place; or

(D) A building in which a funeral or memorial service is being conducted; and

... Knows that the activity adversely affects the funeral, burial, viewing, funeral procession, or memorial service.

. Disorderly conduct is a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1168.SL.pdf?cite=2007%20c%202%20§%201[2007 c 2 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.84.030[1975 1st ex.s. c 260 § 9A.84.030]; ]

== 9A.84.040 - False reporting.
. A person commits false reporting if, with knowledge that the information reported, conveyed, or circulated is false, he or she initiates or circulates a false report or warning of an alleged occurrence or impending occurrence knowing that such false report is likely to cause: Evacuation of a building, place of assembly, or transportation facility; public inconvenience or alarm; or an emergency response.

. [Empty]
.. A person is guilty of false reporting in the first degree if the report was made with reckless disregard for the safety of others, the false reporting caused an emergency response, and death is sustained by any person as a proximate result of an emergency response. False reporting in the first degree is a class B felony.

.. A person is guilty of false reporting in the second degree if the report was made with reckless disregard for the safety of others, the false reporting caused an emergency response, and substantial bodily harm is sustained by any person as a proximate result of an emergency response. False reporting in the second degree is a class C felony.

.. A person is guilty of false reporting in the third degree if he or she commits false reporting under circumstances not constituting false reporting in the first or second degree. False reporting in the third degree is a gross misdemeanor.

. Any criminal offense committed under this section may be deemed to have been committed either at the place from which the false report was made, at the place where the false report was received by law enforcement, or at the place where an evacuation, public inconvenience or alarm, or emergency response occurred.

. Where a case is legally sufficient to charge a person under the age of eighteen with the crime of false reporting and the alleged offense is the offender's first violation of this section, the prosecutor may divert the case.

. For the purposes of this section, "emergency response" means any action to protect life, health, or property by:

.. A peace officer or law enforcement agency of the United States, the state, or a political subdivision of the state; or

.. An agency of the United States, the state, or a political subdivision of the state, or a private not-for-profit organization that provides fire, rescue, or emergency medical services.

. Nothing in this section will be construed to: (a) Impose liability on a person who contacts law enforcement for the purpose of, or in connection with, the reporting of unlawful conduct; (b) conflict with Title 47 U.S.C. Sec. 230 of the communication decency act; or (c) conflict with Title 42 U.S.C. Sec. 1983 of the civil rights act.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2632-S.SL.pdf?cite=2020%20c%20344%20§%202[2020 c 344 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20411[2011 c 336 § 411]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c260.pdf?cite=1975%201st%20ex.s.%20c%20260%20§%209A.84.040[1975 1st ex.s. c 260 § 9A.84.040]; ]

