= 41.07 - Central personnel-payroll system.
:toc:

== 41.07.010 - Definitions.
. As used in this chapter "state agency" means all offices, departments, agencies, institutions, boards, and commissions of state government including those headed by an elected official and including institutions of higher education.

. As used in this chapter "central personnel-payroll system" means an automated data processing system capable of keeping records and processing necessary transactions in the process of employing persons, changing their employment status, and paying employees of any or all state agencies. Such system shall include production of reports and documents required or authorized by state or federal agencies.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c239.pdf?cite=1975%201st%20ex.s.%20c%20239%20§%201[1975 1st ex.s. c 239 § 1]; ]

== 41.07.020 - Administration, maintenance, and operation of system—Intent.
The office of financial management is authorized to administer, maintain, and operate the central personnel-payroll system and to provide its services for any state agency designated by the director of financial management.

State agencies shall convert personnel and payroll processing to the central personnel-payroll system as soon as administratively and technically feasible as determined by the office of financial management and the consolidated technology services agency. It is the intent of the legislature to provide, through the central personnel-payroll system, for uniform reporting to the office of financial management and to the legislature regarding salaries and related costs, and to reduce present costs of manual procedures in personnel and payroll recordkeeping and reporting.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5310.SL.pdf?cite=2019%20c%20146%20§%201[2019 c 146 § 1]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5315-S2.SL.pdf?cite=2015%203rd%20sp.s.%20c%201%20§%20107[2015 3rd sp.s. c 1 § 107]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5931-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2043%20§%20441[2011 1st sp.s. c 43 § 441]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c151.pdf?cite=1979%20c%20151%20§%2062[1979 c 151 § 62]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c239.pdf?cite=1975%201st%20ex.s.%20c%20239%20§%202[1975 1st ex.s. c 239 § 2]; ]

== 41.07.030 - Costs.
The costs of administering, maintaining, and operating the central personnel-payroll system shall be distributed to the using state agencies. In order to insure proper and equitable distribution of costs the office of financial management shall utilize cost accounting procedures to identify all costs incurred in the administration, maintenance, and operation of the central personnel-payroll system. In order to facilitate proper and equitable distribution of costs to the using state agencies the office of financial management is authorized to utilize the statewide information technology system maintenance and operations revolving account created by RCW 43.41.442.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5310.SL.pdf?cite=2019%20c%20146%20§%202[2019 c 146 § 2]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5931-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2043%20§%20611[2011 1st sp.s. c 43 § 611]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5931-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2043%20§%20442[2011 1st sp.s. c 43 § 442]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c239.pdf?cite=1975%201st%20ex.s.%20c%20239%20§%203[1975 1st ex.s. c 239 § 3]; ]

== 41.07.901 - Effective date—1975 1st ex.s. c 239.
This act is necessary for the immediate preservation of the public peace, health, and safety, the support of the state government and its existing public institutions, and shall take effect July 1, 1975.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c239.pdf?cite=1975%201st%20ex.s.%20c%20239%20§%206[1975 1st ex.s. c 239 § 6]; ]

