= 41.14 - Civil service for sheriff's office.
:toc:

== 41.14.010 - Declaration of purpose.
The general purpose of this chapter is to establish a merit system of employment for county deputy sheriffs and other employees of the office of county sheriff, thereby raising the standards and efficiency of such offices and law enforcement in general.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c251.pdf?cite=1987%20c%20251%20§%201[1987 c 251 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c429.pdf?cite=1985%20c%20429%20§%203[1985 c 429 § 3]; 1959 c 1 § 1 (Initiative Measure No. 23, approved November 4, 1958); ]

== 41.14.020 - Terms defined.
Definition of terms:

. "Appointing power" means the county sheriff who is invested by law with power and authority to select, appoint, or employ any deputy, deputies, or other necessary employees subject to civil service;

. "Appointment" includes all means of selecting, appointing, or employing any person to any office, place, position, or employment subject to civil service;

. "Commission" means the civil service commission, or combined county civil service commission, herein created, and "commissioner" means any one of the members of any such commission;

. "County" means any county of the state, or any counties combined pursuant to RCW 41.14.040 for the purpose of carrying out the provisions of this chapter;

. "Deputy sheriff or other members of the office of county sheriff" means all persons regularly employed in the office of county sheriff either on a part time or full time basis.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5322.SL.pdf?cite=2009%20c%20112%20§%201[2009 c 112 § 1]; 1959 c 1 § 2 (Initiative Measure No. 23, approved November 4, 1958); ]

== 41.14.030 - Civil service commission—Appointment, terms, qualifications, compensation, etc.
. There is created in each county and in each combination of counties, combined pursuant to RCW 41.14.040 to carry out the provisions of this chapter, a civil service commission which shall be composed of three persons, or five persons under subsection (2) of this section. The commission members shall be appointed by the board of county commissioners, or boards of county commissioners of each combination of counties, within sixty days after December 4, 1958. No person shall be appointed to the commission who is not a citizen of the United States, a resident of the county, or one of the counties combined, for at least two years immediately preceding his or her appointment, and an elector of the county wherein he or she resides. The term of office of the commissioners shall be six years, except that the first three members of the commission shall be appointed for different terms, as follows: One to serve for a period of two years, one to serve for a period of four years, and one to serve for a period of six years. Any member of the commission may be removed from office for incompetency, incompatibility, or dereliction of duty, or malfeasance in office, or other good cause: PROVIDED, That no member of the commission shall be removed until charges have been preferred, in writing, due notice, and a full hearing had. Any vacancy in the commission shall be filled by the county commissioners for the unexpired term. Two members of the commission shall constitute a quorum and the votes of any two members concurring shall be sufficient for the decision of all matters and the transaction of all business to be decided or transacted by the commission. Confirmation of the appointment of commissioners by any legislative body shall not be required. At the time of appointment not more than two commissioners shall be adherents of the same political party. No member after appointment shall hold any salaried public office or engage in county employment, other than his or her commission duties. The members of the commission shall serve without compensation.

. [Empty]
.. Each county and each combination of counties under RCW 41.14.040 may, by ordinance, increase the number of members serving on a commission from three to five members. If a commission is increased to five members, the terms of the three commissioners serving at the time of the increase are not affected. The initial term of office for the two additional commissioners is six years.

.. Three commissioners constitute a quorum for a five-member commission and the votes of three commissioners concurring are sufficient for the decision of all matters and the transaction of all business decided or transacted by a five-member commission.

.. At the time of appointment of the two additional commissioners, no more than three commissioners may be adherents of the same political party.

.. Except as provided otherwise in this subsection (2), subsection (1) of this section applies to five-member commissions.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%2011[2012 c 117 § 11]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5322.SL.pdf?cite=2009%20c%20112%20§%202[2009 c 112 § 2]; 1959 c 1 § 3 (Initiative Measure No. 23, approved November 4, 1958); ]

== 41.14.040 - Combined system authorized in counties with populations of less than forty thousand.
Any counties with populations of less than forty thousand, whether contiguous or not, are authorized to establish and operate a combined civil service system to serve all counties so combined. The combination of any such counties shall be effective whenever each board of county commissioners of the counties involved adopts a resolution declaring intention to participate in the operation of a combined county civil service system in accordance with agreements made between any such counties. Any such combined county civil service commission shall serve the employees of each county sheriff's office impartially and according to need.

All matters affecting the combined civil service commission, including the selection of commissioners, shall be decided by majority vote of all the county commissioners of the counties involved.

All the provisions of this chapter shall apply equally to any such combined civil service system.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1201-S.SL.pdf?cite=1991%20c%20363%20§%20114[1991 c 363 § 114]; 1959 c 1 § 4 (Initiative Measure No. 23, approved November 4, 1958); ]

== 41.14.050 - Commission—Organization, meetings—Chief examiner, qualifications, duties.
Immediately after appointment the commission shall organize by electing one of its members as chair and shall hold regular meetings at least once a month, and such additional meetings as may be required for the proper discharge of its duties.

The commission shall appoint a chief examiner who shall also serve as secretary of the commission and such assistants as may be necessary. The commission has supervisory responsibility over the chief examiner. The chief examiner shall keep the records for the commission, preserve all reports made to it, superintend and keep a record of all examinations held under its direction, and perform such other duties as the commission may prescribe.

The chief examiner shall be appointed as a result of competitive examination, which examination must be open to all properly qualified citizens of the county or of an adjacent county: PROVIDED, That no appointee of the commission, either as chief examiner or as an assistant to the chief examiner, shall be an employee of the sheriff's department. The chief examiner may be subject to suspension, reduction, or discharge in the same manner and subject to the same limitations as are provided in the case of members of the classified service.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1752.SL.pdf?cite=2016%20c%2082%20§%201[2016 c 82 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5620.SL.pdf?cite=2007%20c%2012%20§%201[2007 c 12 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c153.pdf?cite=1979%20ex.s.%20c%20153%20§%201[1979 ex.s. c 153 § 1]; 1959 c 1 § 5 (Initiative Measure No. 23, approved November 4, 1958); ]

== 41.14.060 - Powers and duties of commission.
It shall be the duty of the civil service commission:

. To make suitable rules and regulations not inconsistent with the provisions hereof. Such rules and regulations shall provide in detail the manner in which examinations may be held, and appointments, promotions, reallocations, transfers, reinstatements, demotions, suspensions, and discharges shall be made, and may also provide for any other matters connected with the general subject of personnel administration, and which may be considered desirable to further carry out the general purposes of this chapter, or which may be found to be in the interest of good personnel administration. The rules and regulations and any amendments thereof shall be printed, mimeographed, or multigraphed for free public distribution. Such rules and regulations may be changed from time to time.

. To give practical tests which shall consist only of subjects which will fairly determine the capacity of persons examined to perform duties of the position to which appointment is to be made. Such tests may include tests of physical fitness or manual skill or both.

. To make investigations concerning and report upon all matters touching the enforcement and effect of the provisions of this chapter, and the rules and regulations prescribed hereunder; to inspect all departments, offices, places, positions, and employments affected by this chapter, and ascertain whether this chapter and all such rules and regulations are being obeyed. Such investigations may be made by the commission or by any commissioner designated by the commission for that purpose. Not only must these investigations be made by the commission as aforesaid, but the commission must make like investigation on petition of a citizen, duly verified, stating that irregularities or abuses exist, or setting forth in concise language, in writing, the necessity for such investigation. In the course of such investigation the commission or designated commissioner, or chief examiner, may administer oaths, subpoena and require the attendance of witnesses and the production by them of books, papers, documents, and accounts appertaining to the investigation and also cause the deposition of witnesses residing within or without the state to be taken in the manner prescribed by law for like depositions in civil actions in the superior court; and the oaths administered and the subpoenas issued hereunder shall have the same force and effect as the oaths administered and subpoenas issued by a superior court judge in his or her judicial capacity; and the failure of any person so subpoenaed to comply with the provisions of this section shall be deemed a violation of this chapter, and punishable as such.

. To conduct hearings and investigations in accordance with this chapter and by the rules of practice and procedure adopted by the commission, and in the conduct thereof neither the commission, nor designated commissioner shall be bound by technical rules of evidence. No informality in any proceedings or hearing, or in the manner of taking testimony before the commission or designated commissioner, shall invalidate any order, decision, rule, or regulation made, approved, or confirmed by the commission: PROVIDED, That no order, decision, rule, or regulation made by any designated commissioner conducting any hearing or investigation alone shall be of any force or effect whatsoever unless and until concurred in by at least one of the other two members.

. To hear and determine appeals or complaints respecting the allocation of positions, the rejection of an examinee, and such other matters as may be referred to the commission.

. To provide for, formulate, and hold competitive tests to determine the relative qualifications of persons who seek employment in any class or position and as a result thereof establish eligible lists for the various classes of positions, and provide that persons laid off, or who have accepted voluntary demotion in lieu of layoff, because of curtailment of expenditures, reduction in force, and for like causes, head the list in the order of their seniority, to the end that they shall be the first to be reemployed or reinstated in their former job class.

. To certify to the appointing authority, when a vacant position is to be filled, on written request, the names of the five persons highest on the eligible list for the class. If there is no such list, to authorize a provisional or temporary appointment list for such class. A temporary appointment expires after four months. However, the appointing authority may extend the temporary appointment beyond the four-month period up to one year if the commission continues to advertise and test for the position. If, after one year from the date the initial temporary appointment was first made, there are less than five persons on the eligible list for the class, then the appointing authority may fill the position with any person or persons on the eligible list.

. To keep such records as may be necessary for the proper administration of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1750.SL.pdf?cite=2020%20c%2014%20§%201[2020 c 14 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%2012[2012 c 117 § 12]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2001%20c%20232%20§%201[2001 c 232 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c153.pdf?cite=1979%20ex.s.%20c%20153%20§%202[1979 ex.s. c 153 § 2]; 1959 c 1 § 6 (Initiative Measure No. 23, approved November 4, 1958); ]

== 41.14.065 - Delegation of powers and duties of commission in county with a population of one million or more.
Any county with a population of one million or more may assign the powers and duties of the commission to such county agencies or departments as may be designated by charter or ordinance: PROVIDED, That the powers and duties of the commission under RCW 41.14.120 shall not be assigned to any other body but shall continue to be vested in the commission, which shall exist to perform such powers and duties, together with such other adjudicative functions as may be designated by charter or ordinance.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1201-S.SL.pdf?cite=1991%20c%20363%20§%20115[1991 c 363 § 115]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c251.pdf?cite=1987%20c%20251%20§%202[1987 c 251 § 2]; ]

== 41.14.070 - Classified and unclassified service designated—Procedures.
. The classified civil service and provisions of this chapter shall include all deputy sheriffs and other employees of the office of sheriff in each county except the county sheriff in every county and an additional number of positions, designated the unclassified service, determined as follows:

Staff PersonnelUnclassifiedPosition Appointments1through 10211through 20321through 50451through 1005101through 2506251through 5008501and over10



Staff Personnel

Unclassified

Position Appointments

1

through 10

2

11

through 20

3

21

through 50

4

51

through 100

5

101

through 250

6

251

through 500

8

501

and over

10

. The unclassified position appointments authorized by this section must include selections from the following positions up to the limit of the number of positions authorized: Undersheriff, inspector, chief criminal deputy, chief civil deputy, jail superintendent, and administrative assistant or administrative secretary. The initial selection of specific positions to be exempt shall be made by the sheriff, who shall notify the civil service commission of his or her selection. Subsequent changes in the designation of which positions are to be exempt may be made only with the concurrence of the sheriff and the civil service commission, and then only after the civil service commission has heard the issue in open meeting. Should the position or positions initially selected by the sheriff to be exempt (unclassified) pursuant to this section be under the classified civil service at the time of such selection, and should it (or they) be occupied, the employee(s) occupying said position(s) shall have the right to return to the next highest position or a like position under classified civil service.

. In counties with a sheriff's department that operates the 911 emergency communications system, in addition to the unclassified positions authorized in subsections (1), (2), and (4) of this section, the sheriff may designate one unclassified position for the 911 emergency communications system.

. In addition to the unclassified positions authorized in this section, the county legislative authority of any county with a population of five hundred thousand or more operating under a home rule charter may designate unclassified positions of administrative responsibility not to exceed twenty positions.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5127.SL.pdf?cite=2001%20c%20151%20§%201[2001 c 151 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5364.SL.pdf?cite=1997%20c%2062%20§%201[1997 c 62 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1201-S.SL.pdf?cite=1991%20c%20363%20§%20116[1991 c 363 § 116]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c153.pdf?cite=1979%20ex.s.%20c%20153%20§%203[1979 ex.s. c 153 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c186.pdf?cite=1975%201st%20ex.s.%20c%20186%20§%201[1975 1st ex.s. c 186 § 1]; 1959 c 1 § 7 (Initiative Measure No. 23, approved November 4, 1958); ]

== 41.14.080 - Classified service—Appointment, promotion, transfer, suspension, discharge.
All appointments to and promotions to positions in the classified civil service of the office of county sheriff shall be made solely on merit, efficiency, and fitness, which shall be ascertained by open competitive examination and impartial investigation: PROVIDED, That before June 30, 1981, employees in an existing county personnel system may be transferred to newly created and classified positions within such county's sheriff's office, in order to permanently transfer the functions of these positions, without meeting the open competitive examination requirements of this section if the transfer is approved by the civil service commission created in RCW 41.14.030. No person in the classified civil service shall be reinstated in or transferred, suspended, or discharged from any such place, position, or employment contrary to the provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c108.pdf?cite=1980%20c%20108%20§%201[1980 c 108 § 1]; 1959 c 1 § 8 (Initiative Measure No. 23, approved November 4, 1958); ]

== 41.14.090 - Status of existing employees in classified service.
For the benefit of the public service and to prevent delay, injury, or interruption therein by reason of the enactment hereof, all persons holding a position which is deemed classified by RCW 41.14.070 for a continuous period of six months prior to December 4, 1958, are eligible for permanent appointment under civil service to the offices, places, positions, or employments which they then held without examination or other act on their part, and not on probation; and every such person is automatically adopted and inducted permanently into civil service, into the office, place, position, or employment which he or she then held as completely and effectually to all intents and purposes as if such person had been permanently appointed thereto under civil service after examination and investigation.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%2013[2012 c 117 § 13]; 1959 c 1 § 9 (Initiative Measure No. 23, approved November 4, 1958); ]

== 41.14.100 - Qualifications of applicants for position—Law enforcement agencies.
An applicant for a position of any kind under civil service under the provisions of this chapter, must be a citizen of the United States or a lawful permanent resident who can read and write the English language.

An application for a position with a law enforcement agency may be rejected if the law enforcement agency deems that it does not have the resources to conduct the background investigation required pursuant to chapter 43.101 RCW. Resources means materials, funding, and staff time. Nothing in this section impairs an applicant's rights under state antidiscrimination laws.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6145.SL.pdf?cite=2018%20c%2032%20§%203[2018 c 32 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c95.pdf?cite=1963%20c%2095%20§%203[1963 c 95 § 3]; 1959 c 1 § 10 (Initiative Measure No. 23, approved November 4, 1958); ]

== 41.14.110 - Tenure—Grounds for deprivation.
The tenure of every person holding an office, place, position, or employment under the provisions of this chapter shall be only during good behavior, and any such person may be removed or discharged, suspended without pay, demoted, or reduced in rank, or deprived of vacation privileges or other special privileges for any of the following reasons:

. Incompetency, inefficiency, or inattention to, or dereliction of duty;

. Dishonesty, intemperance, immoral conduct, insubordination, discourteous treatment of the public, or a fellow employee, or any other act of omission or commission tending to injure the public service; or any other willful failure on the part of the employee to properly conduct himself or herself; or any willful violation of the provisions of this chapter or the rules and regulations to be adopted hereunder;

. Mental or physical unfitness for the position which the employee holds;

. Dishonest, disgraceful, or prejudicial conduct;

. Drunkenness or use of intoxicating liquors, narcotics, or any other habit forming drug, liquid, or preparation to such extent that the use thereof interferes with the efficiency or mental or physical fitness of the employee, or which precludes the employee from properly performing the function and duties of any position under civil service;

. Conviction of a felony, or a misdemeanor involving moral turpitude;

. Any other act or failure to act which in the judgment of the civil service commission is sufficient to show the offender to be an unsuitable and unfit person to be employed in the public service.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%2014[2012 c 117 § 14]; 1959 c 1 § 11 (Initiative Measure No. 23, approved November 4, 1958); ]

== 41.14.120 - Removal, suspension, demotion, or discharge—Procedure—Appeal.
No person in the classified civil service who has been permanently appointed or inducted into civil service under provisions of this chapter, shall be removed, suspended, demoted, or discharged except for cause, and only upon written accusation of the appointing power or any citizen or taxpayer; a written statement of which accusation, in general terms, shall be served upon the accused, and a duplicate filed with the commission. Any person so removed, suspended, discharged, or demoted may within ten days from the time of his or her removal, suspension, discharge, or demotion file with the commission a written demand for an investigation, whereupon the commission shall conduct such investigation. Upon receipt of the written demand for an investigation, the commission shall within ten days set a date for a public hearing which will be held within thirty days from the date of receipt. The investigation shall be confined to the determination of the question of whether the removal, suspension, demotion, or discharge was made in good faith for cause. After such investigation the commission shall render a written decision within ten days and may affirm the removal, suspension, demotion, or discharge, or if it finds that removal, suspension, demotion, or discharge was not made in good faith for cause, shall order the immediate reinstatement or reemployment of such person in the office, place, position, or employment from which he or she was removed, suspended, demoted, or discharged, which reinstatement shall, if the commission so provides, be retroactive, and entitle such person to pay or compensation from the time of the removal, suspension, demotion, or discharge. The commission upon such investigation, in lieu of affirming a removal, suspension, demotion, or discharge, may modify the order by directing the removal, suspension, demotion, or discharge without pay, for a given period, and subsequent restoration to duty, or demotion in classification, grade, or pay. The findings of the commission shall be certified, in writing to the appointing power, and shall be forthwith enforced by such officer.

All investigations made by the commission pursuant to this section shall be by public hearing, after reasonable notice to the accused of the time and place thereof, at which hearing the accused shall be afforded an opportunity of appearing in person and by counsel, and presenting his or her defense. If order of removal, suspension, demotion, or discharge is concurred in by the commission or a majority thereof, the accused may appeal therefrom to the superior court of the county wherein he or she resides. Such appeal shall be taken by serving the commission, within thirty days after the entry of its order, a written notice of appeal, stating the grounds thereof, and demanding that a certified transcript of the record and of all papers on file in the office of the commission affecting or relating to its order, be filed by the commission with the court. The commission shall, within ten days after the filing of the notice, make, certify, and file such transcript with the court. The court shall thereupon proceed to hear and determine the appeal in a summary manner. Such hearing shall be confined to the determination of whether the order of removal, suspension, demotion, or discharge made by the commission, was or was not made in good faith for cause, and no appeal shall be taken except upon such ground or grounds. The decision of the superior court may be appealed to the supreme court or the court of appeals.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%2015[2012 c 117 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c199.pdf?cite=1984%20c%20199%20§%201[1984 c 199 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c133.pdf?cite=1982%20c%20133%20§%201[1982 c 133 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c81.pdf?cite=1971%20c%2081%20§%20102[1971 c 81 § 102]; 1959 c 1 § 12 (Initiative Measure No. 23, approved November 4, 1958); ]

== 41.14.130 - Filling vacancies in classified service—Eligibility list—Probation.
Whenever a position in the classified service becomes vacant, the appointing power, if it desires to fill the vacancy, shall requisition the commission for the names and addresses of persons eligible for appointment thereto. Before a requisition can be made, the appointing authority shall give employees of the appointing authority who are in layoff status or who have been notified of an intended layoff an opportunity to qualify for any class within the office of the appointing authority. The commission shall certify the names of the five persons highest on the eligible list for the class to which the vacant position has been allocated, who are willing to accept employment. If there is no appropriate eligible list for the class, the commission shall certify the names of the five persons standing highest on the list held appropriate for such class. If more than one vacancy is to be filled an additional name shall be certified for each additional vacancy. The appointing power shall forthwith appoint a person from those certified to the vacant position.

To enable the appointing power to exercise a greater degree of choice in the filling of positions, no appointment, employment, or promotion in any position in the classified service shall be deemed complete until after the expiration of a period of one year's probationary service, as may be provided in the rules of the civil service commission, during which the appointing power may terminate the employment of the person appointed, if during the performance test thus afforded, upon observation or consideration of the performance of duty, the appointing power deems such person unfit or unsatisfactory for service in the office of county sheriff. Thereupon the appointing power shall again requisition the commission for the names and addresses of persons eligible for appointment in the manner provided by this section and the person appointed in the manner provided by this section shall likewise enter upon said duties for the probationary period, until some person is found who is deemed fit for appointment, employment, or promotion whereupon the appointment, employment, or promotion shall be deemed complete.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1750.SL.pdf?cite=2020%20c%2014%20§%202[2020 c 14 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c199.pdf?cite=1984%20c%20199%20§%202[1984 c 199 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c153.pdf?cite=1979%20ex.s.%20c%20153%20§%204[1979 ex.s. c 153 § 4]; 1959 c 1 § 13 (Initiative Measure No. 23, approved November 4, 1958); ]

== 41.14.140 - Power to fill positions—Consent of county commissioners—Salaries and compensation.
All offices, places, positions, and employments coming within the purview of this chapter, shall be filled by the appointing power with the consent of the board of county commissioners, and nothing herein contained shall infringe upon such authority that an appointing power may have to fix the salaries and compensation of all employees employed hereunder.

[ 1959 c 1 § 14 (Initiative Measure No. 23, approved November 4, 1958); ]

== 41.14.150 - Procedure for payment of compensation—Refusal to pay.
No treasurer, auditor or other officer, or employee of any county subject to this chapter shall approve the payment of or be in any manner concerned in paying, auditing, or approving any salary, wage, or other compensation for services, to any person subject to the jurisdiction and scope of this chapter, unless a payroll, estimate, or account for such salary, wage, or other compensation, containing the names of the persons to be paid, the amount to be paid to each such person, the services on account of which same is paid, and any other information which, in the judgment of the civil service commission, should be furnished on such payroll, bears the certificate of the civil service commission, or of its chief examiner or other duly authorized agent, that the persons named therein have been appointed or employed in compliance with the terms of this chapter and the rules of the commission, and that the payroll, estimate, or account is, insofar as known to the commission, a true and accurate statement. The commission shall refuse to certify the pay of any public officer or employee whom it finds to be illegally or improperly appointed, and may further refuse to certify the pay of any public officer or employee who wilfully or through culpable negligence, violates or fails to comply with this chapter or with the rules of the commission.

[ 1959 c 1 § 15 (Initiative Measure No. 23, approved November 4, 1958); ]

== 41.14.160 - Leaves of absence.
Leave of absence, without pay, may be granted by any appointing power to any person under civil service: PROVIDED, That such appointing power gives notice of the leave to the commission. All temporary employment caused by leaves of absence shall be made from the eligible list of the classified civil service.

[ 1959 c 1 § 16 (Initiative Measure No. 23, approved November 4, 1958); ]

== 41.14.170 - Actions to enforce chapter—Duties of prosecuting attorneys.
The commission shall begin and conduct all civil suits which may be necessary for the proper enforcement of this chapter and rules of the commission. The commission shall be represented in such suits by the prosecuting attorney of the county. In the case of combined counties any one or more of the prosecuting attorneys of each county so combined may be selected by the commission to represent it.

[ 1959 c 1 § 17 (Initiative Measure No. 23, approved November 4, 1958); ]

== 41.14.180 - Prohibited acts relating to registration, examination, certification—Discrimination prohibited.
No commissioner or any other person , shall, by himself or herself or in cooperation with others, defeat, deceive, or obstruct any person in respect of his or her right of examination or registration according to the rules and regulations, or falsely mark, grade, estimate, or report upon the examination or proper standing of any person examined, registered, or certified pursuant to this chapter, or aid in so doing, or make any false representation concerning the same, or concerning the person examined, or furnish any person any special or secret information for the purpose of improving or injuring the prospects or chances of any person so examined, registered or certified, or to be examined, registered, or certified, or persuade any other person, or permit or aid in any manner any other person to personate him or her, in connection with any examination or registration of application or request to be examined or registered.

The right of any person to an appointment or promotion to any position in a sheriff's office shall not be withheld because of his or her race, color, creed, national origin, political affiliation or belief, nor shall any person be dismissed, demoted, or reduced in grade for such reason.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%2016[2012 c 117 § 16]; 1959 c 1 § 18 (Initiative Measure No. 23, approved November 4, 1958); ]

== 41.14.190 - Political activities regulated.
No person holding any office, place, position, or employment subject to civil service, shall contribute to any political fund or render any political service to any person or party whatsoever, and no person shall be removed, reduced in grade or salary, or otherwise prejudiced for refusing so to do. No public officer, whether elected or appointed, shall discharge, promote, demote, or in any manner change the official rank, employment, or compensation of any person under civil service or promise or threaten so to do for giving or withholding, or neglecting to make any contribution of money, or service, or any other valuable thing, for any political purpose.

[ 1959 c 1 § 19 (Initiative Measure No. 23, approved November 4, 1958); ]

== 41.14.200 - Cooperation and aid by other county officers and employees.
All officers and employees of each county shall aid in all proper ways in carrying out the provisions of this chapter, and such rules and regulations as may, from time to time, be prescribed by the commission and afford the commission, its members, and employees, all reasonable facilities and assistance in the inspection of books, papers, documents, and accounts applying or in any way appertaining to any and all offices, places, positions, and employments, subject to civil service, and also shall produce such books, papers, documents, and accounts, and attend and testify, whenever required so to do by the commission or any commissioner.

[ 1959 c 1 § 20 (Initiative Measure No. 23, approved November 4, 1958); ]

== 41.14.210 - Funds for commission in counties with populations of two hundred ten thousand or more—County budget—Surplus.
The county legislative authority or [of] each county with a population of two hundred ten thousand or more may provide in the county budget for each fiscal year a sum equal to one percent of the preceding year's total payroll of those included under the jurisdiction and scope of this chapter. The funds so provided shall be used for the support of the commission. Any part of the funds so provided and not expended for the support of the commission during the fiscal year shall be placed in the general fund of the county, or counties according to the ratio of contribution, on the first day of January following the close of such fiscal year.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1201-S.SL.pdf?cite=1991%20c%20363%20§%20117[1991 c 363 § 117]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c214.pdf?cite=1971%20ex.s.%20c%20214%20§%203[1971 ex.s. c 214 § 3]; 1959 c 1 § 21 (Initiative Measure No. 23, approved November 4, 1958); ]

== 41.14.220 - Penalty—Jurisdiction.
Any person who wilfully violates any of the provisions of this chapter shall be guilty of a misdemeanor, and upon conviction thereof, shall be punished by a fine of not more than one hundred dollars and by imprisonment in the county jail for not longer than thirty days or by both such fine and imprisonment. The superior court shall have jurisdiction of all such offenses.

[ 1959 c 1 § 22 (Initiative Measure No. 23, approved November 4, 1958); ]

== 41.14.250 - City contracts to obtain sheriff's office law enforcement services—Transfer of police department employees.
When any city or town shall contract with the county sheriff's office to obtain law enforcement services to the city or town, any employee of the police department of such city or town who (1) was at the time such contract was entered into employed exclusively or principally in performing the powers, duties, and functions which are to be performed by the county sheriff's office under such contract (2) will, as a direct consequence of such contract, be separated from the employ of the city or town, and (3) meets the minimum standards and qualifications of the county sheriff's office, then such employee may transfer his or her employment to the county sheriff's office as provided for in RCW 41.14.260 and 41.14.270.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%2017[2012 c 117 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c48.pdf?cite=1972%20ex.s.%20c%2048%20§%201[1972 ex.s. c 48 § 1]; ]

== 41.14.260 - City contracts to obtain sheriff's office law enforcement services—Transfer of police department employees into county civil service for sheriff's office—Seniority for employment.
. An eligible employee may transfer into the county civil service system for the sheriff's office by filing a written request with the county civil service commission and by giving written notice thereof to the legislative authority of the city or town. Upon receipt of such request by the civil service commission the transfer of employment shall be made. The employee so transferring will (1) be on probation for the same period as are new employees of the sheriff's office, (2) be eligible for promotion after completion of the probationary period as completed, (3) receive a salary at least equal to that of other new employees of the sheriff's office, and (4) in all other matters, such as retirement, vacation, etc., have, within the county civil service system, all the rights, benefits, and privileges that he or she would have been entitled to had he or she been a member of the county sheriff's office from the beginning of his or her employment with the city or town police department. The city or town shall, upon receipt of such notice, transmit to the county civil service commission a record of the employee's service with the city or town which shall be credited to such member as a part of his or her period of employment in the county sheriff's office. The sheriff may appoint the transferring employee to whatever duties he or she feels are in the best interest of the department and the individual.

. If in the process of contracting for law enforcement services economies or efficiencies are achieved or if the city or town intends by such contract to curtail expenditures and the level of services to the city or town, then only so many of the transferring employees shall be placed upon the payroll of the sheriff's office as the sheriff determines are needed to provide the contracted services. These needed employees shall be taken in order of seniority and the remaining employees who transfer as provided in RCW 41.14.250, 41.14.260, and 41.14.270 shall head the list of their respective class or job listing in the civil service system in order of their seniority, to the end that they shall be the first to be reemployed in the county sheriff's office when appropriate positions become available.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%2018[2012 c 117 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c48.pdf?cite=1972%20ex.s.%20c%2048%20§%202[1972 ex.s. c 48 § 2]; ]

== 41.14.270 - City contracts to obtain sheriff's office law enforcement services—Layoffs—Notice—Time limitation for transfers.
When a city or town shall contract with the county sheriff's office for law enforcement services and as a result thereof lays off any employee who is eligible to transfer to the county sheriff's office pursuant to RCW 41.14.250 and 41.14.260, the city or town shall notify such employee of his or her right to so transfer and such employee shall have ninety days to transfer his or her employment to the county sheriff's office: PROVIDED, That any employee layed off [laid off] during the year prior to February 21, 1972 shall have ninety days after the effective date to transfer his or her employment.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%2019[2012 c 117 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c48.pdf?cite=1972%20ex.s.%20c%2048%20§%203[1972 ex.s. c 48 § 3]; ]

== 41.14.280 - City contracts to obtain sheriff's office law enforcement services—Rules and regulations.
In addition to its other duties prescribed by law, the civil service commission shall make such rules and regulations as may be necessary to provide for the orderly integration of employees of a city or town who shall transfer to the county sheriff's office pursuant to RCW 41.14.250, 41.14.260, and 41.14.270.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c48.pdf?cite=1972%20ex.s.%20c%2048%20§%204[1972 ex.s. c 48 § 4]; ]

== 41.14.290 - Appointment of classified employee to exempt position—Return to regular position.
Any classified employee having civil service status in a position may take an appointment in an exempt position in the same county and maintain the right to return to his or her regular position or to a like position at the conclusion of such appointment. Such employee must apply to return to classified service within thirty calendar days of:

. Termination of employment in such exempt position; or

. Termination of employment in any other exempt position in which the employee subsequently serves provided there was no break in service with the county of more than thirty calendar days.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c153.pdf?cite=1979%20ex.s.%20c%20153%20§%205[1979 ex.s. c 153 § 5]; ]

