= 41.22 - Law enforcement chaplains.
:toc:

== 41.22.010 - Legislative findings.
The career of a police officer is highly stressful, resulting in unacceptable rates of divorce, alcoholism, low morale and suicide. The nature of law enforcement work requires that much information be kept confidential, unfairly burdening the emotional capacity of law enforcement personnel. Police officers may become the hidden victims of society because of their daily work with crisis.

The legislature finds that law enforcement chaplains can provide emotional support for law enforcement personnel, including counseling, stress management, and family life counseling. The legislature also finds that law enforcement chaplains can serve as a crisis intervention resource for personnel of police, fire, and corrections departments, and medical examiners or coroners.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c223.pdf?cite=1985%20c%20223%20§%201[1985 c 223 § 1]; ]

== 41.22.020 - Washington state patrol and the department of fish and wildlife—Volunteer chaplain authorized.
The Washington state patrol and the department of fish and wildlife may utilize the services of a volunteer chaplain.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1437.SL.pdf?cite=2009%20c%20204%20§%202[2009 c 204 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c223.pdf?cite=1985%20c%20223%20§%202[1985 c 223 § 2]; ]

== 41.22.030 - Local law enforcement agencies—Volunteer chaplains authorized.
The legislature authorizes local law enforcement agencies to use the services of volunteer chaplains associated with an agency.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c223.pdf?cite=1985%20c%20223%20§%203[1985 c 223 § 3]; ]

== 41.22.040 - Volunteer chaplains—Duties.
The duties of a volunteer law enforcement chaplain include counseling, training, and crises intervention for law enforcement personnel, their families and the general public.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c223.pdf?cite=1985%20c%20223%20§%204[1985 c 223 § 4]; ]

