= 41.59 - Educational employment relations act.
:toc:

== 41.59.010 - Purpose.
It is the purpose of this chapter to prescribe certain rights and obligations of the educational employees of the school districts of the state of Washington, and to establish procedures governing the relationship between such employees and their employers which are designed to meet the special requirements and needs of public employment in education.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c288.pdf?cite=1975%201st%20ex.s.%20c%20288%20§%202[1975 1st ex.s. c 288 § 2]; ]

== 41.59.020 - Definitions.
As used in this chapter:

. The term "employee organization" means any organization, union, association, agency, committee, council, or group of any kind in which employees participate, and which exists for the purpose, in whole or in part, of collective bargaining with employers.

. The term "collective bargaining" or "bargaining" means the performance of the mutual obligation of the representatives of the employer and the exclusive bargaining representative to meet at reasonable times in light of the time limitations of the budget-making process, and to bargain in good faith in an effort to reach agreement with respect to the wages, hours, and terms and conditions of employment: PROVIDED, That prior law, practice or interpretation shall be neither restrictive, expansive, nor determinative with respect to the scope of bargaining. A written contract incorporating any agreements reached shall be executed if requested by either party. The obligation to bargain does not compel either party to agree to a proposal or to make a concession.

In the event of a dispute between an employer and an exclusive bargaining representative over the matters that are terms and conditions of employment, the commission shall decide which item(s) are mandatory subjects for bargaining and which item(s) are nonmandatory.

. The term "commission" means the public employment relations commission established by RCW 41.58.010.

. The terms "employee" and "educational employee" means any certificated employee of a school district, except:

.. The chief executive officer of the employer.

.. The chief administrative officers of the employer, which shall mean the superintendent of the district, deputy superintendents, administrative assistants to the superintendent, assistant superintendents, and business manager. Title variation from all positions enumerated in this subsection (b) may be appealed to the commission for determination of inclusion in, or exclusion from, the term "educational employee".

.. Confidential employees, which shall mean:

... Any person who participates directly on behalf of an employer in the formulation of labor relations policy, the preparation for or conduct of collective bargaining, or the administration of collective bargaining agreements, except that the role of such person is not merely routine or clerical in nature but calls for the consistent exercise of independent judgment; and

... Any person who assists and acts in a confidential capacity to such person.

.. Unless included within a bargaining unit pursuant to RCW 41.59.080, any supervisor, which means any employee having authority, in the interest of an employer, to hire, assign, promote, transfer, layoff, recall, suspend, discipline, or discharge other employees, or to adjust their grievances, or to recommend effectively such action, if in connection with the foregoing the exercise of such authority is not merely routine or clerical in nature but calls for the consistent exercise of independent judgment, and shall not include any persons solely by reason of their membership on a faculty tenure or other governance committee or body. The term "supervisor" shall include only those employees who perform a preponderance of the above-specified acts of authority.

.. Unless included within a bargaining unit pursuant to RCW 41.59.080, principals and assistant principals in school districts.

. The term "employer" means any school district.

. The term "exclusive bargaining representative" means any employee organization which has:

.. Been selected or designated pursuant to the provisions of this chapter as the representative of the employees in an appropriate collective bargaining unit; or

.. Prior to January 1, 1976, been recognized under a predecessor statute as the representative of the employees in an appropriate collective bargaining or negotiations unit.

. The term "person" means one or more individuals, organizations, unions, associations, partnerships, corporations, boards, committees, commissions, agencies, or other entities, or their representatives.

. The term "nonsupervisory employee" means all educational employees other than principals, assistant principals and supervisors.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c11.pdf?cite=1989%20c%2011%20§%2011[1989 c 11 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c288.pdf?cite=1975%201st%20ex.s.%20c%20288%20§%203[1975 1st ex.s. c 288 § 3]; ]

== 41.59.031 - Application of chapter to charter schools.
This chapter applies to any charter school established under chapter 28A.710 RCW. Any bargaining unit or units established at the charter school must be limited to employees working in the charter school and must be separate from other bargaining units in school districts, educational service districts, or institutions of higher education. Any charter school established under chapter 28A.710 RCW is a separate employer from any school district, including the school district in which it is located.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6194-S2.SL.pdf?cite=2016%20c%20241%20§%20138[2016 c 241 § 138]; 2013 c 2 § 308 (Initiative Measure No. 1240, approved November 6, 2012); ]

== 41.59.060 - Employee rights enumerated—Employee authorization of membership dues and other payments—Revocation.
. Employees shall have the right to self-organization, to form, join, or assist employee organizations, to bargain collectively through representatives of their own choosing, and shall also have the right to refrain from any or all of such activities.

. [Empty]
.. Upon authorization of an employee within the bargaining unit and after the certification or recognition of the bargaining unit's exclusive bargaining representative, the employer must deduct from the payments to the employee the monthly amount of dues as certified by the secretary of the exclusive bargaining representative and must transmit the same to the treasurer of the exclusive bargaining representative.

.. An employee's written, electronic, or recorded voice authorization to have the employer deduct membership dues from the employee's salary must be made by the employee to the exclusive bargaining representative. If the employer receives a request for authorization of deductions, the employer shall as soon as practicable forward the request to the exclusive bargaining representative.

.. Upon receiving notice of the employee's authorization from the exclusive bargaining representative, the employer shall deduct from the employee's salary membership dues and remit the amounts to the exclusive bargaining representative.

.. The employee's authorization remains in effect until expressly revoked by the employee in accordance with the terms and conditions of the authorization.

.. An employee's request to revoke authorization for payroll deductions must be in writing and submitted by the employee to the exclusive bargaining representative in accordance with the terms and conditions of the authorization.

.. After the employer receives confirmation from the exclusive bargaining representative that the employee has revoked authorization for deductions, the employer shall end the deduction no later than the second payroll after receipt of the confirmation.

.. The employer shall rely on information provided by the exclusive bargaining representative regarding the authorization and revocation of deductions.

. If the employer and the exclusive bargaining representative of a bargaining unit enter into a collective bargaining agreement that includes requirements for deductions of other payments, the employer must make such deductions upon authorization of the employee.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1575-S.SL.pdf?cite=2019%20c%20230%20§%2012[2019 c 230 § 12]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2751.SL.pdf?cite=2018%20c%20247%20§%203[2018 c 247 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c288.pdf?cite=1975%201st%20ex.s.%20c%20288%20§%207[1975 1st ex.s. c 288 § 7]; ]

== 41.59.068 - Application of RCW  41.56.037—Bargaining representative access to new employees.
RCW 41.56.037 applies to this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6229.SL.pdf?cite=2018%20c%20250%20§%203[2018 c 250 § 3]; ]

== 41.59.070 - Election to ascertain exclusive bargaining representative, when—Runoff election—Decertification election.
. Any employee organization may file a request with the commission for recognition as the exclusive representative. Such request shall allege that a majority of the employees in an appropriate collective bargaining unit wish to be represented for the purpose of collective bargaining by such organization, shall describe the grouping of jobs or positions which constitute the unit claimed to be appropriate, shall be supported by credible evidence demonstrating that at least thirty percent of the employees in the appropriate unit desire the organization requesting recognition as their exclusive representative, and shall indicate the name, address, and telephone number of any other interested employee organization, if known to the requesting organization.

. The commission shall determine the exclusive representative by conducting an election by secret ballot, except under the following circumstances:

.. In instances where a serious unfair labor practice has been committed which interfered with the election process and precluded the holding of a fair election, the commission shall determine the exclusive bargaining representative by an examination of organization membership rolls or a comparison of signatures on organization bargaining authorization cards.

.. In instances where there is then in effect a lawful written collective bargaining agreement between the employer and another employee organization covering any employees included in the unit described in the request for recognition, the request for recognition shall not be entertained unless it shall be filed within the time limits prescribed in subsection (3) of this section for decertification or a new recognition election.

.. In instances where within the previous twelve months another employee organization has been lawfully recognized or certified as the exclusive bargaining representative of any employees included in the unit described in the request for recognition, the request for recognition shall not be entertained.

.. In instances where the commission has within the previous twelve months conducted a secret ballot election involving any employees included in the unit described in the request for recognition in which a majority of the valid ballots cast chose not to be represented by any employee organization, the request for recognition shall not be entertained.

. Whenever the commission conducts an election to ascertain the exclusive bargaining representative, the ballot shall contain the name of the proposed bargaining representative and of any other bargaining representative showing written proof of at least ten percent representation of the educational employees within the unit, together with a choice for any educational employee to designate that he or she does not desire to be represented by any bargaining agent. Where more than one organization is on the ballot and neither of the three or more choices receives a majority of the valid ballots cast by the educational employees within the bargaining unit, a runoff election shall be held. The runoff ballot shall contain the two choices which receive the largest and second largest number of votes. No question concerning representation may be raised within one year of a certification or attempted certification. Where there is a valid collective bargaining agreement in effect, no question of representation may be raised except during the period not more than ninety nor less than sixty days prior to the expiration date of the agreement. In the event that a valid collective bargaining agreement, together with any renewals or extensions thereof, has been or will be in existence for three years, then the question of representation may be raised not more than ninety nor less than sixty days prior to the third anniversary date of the agreement or any renewals or extensions thereof as long as such renewals and extensions do not exceed three years; and if the exclusive bargaining representative is removed as a result of such procedure, the then existing collective bargaining agreement shall be terminable by the new exclusive bargaining representative so selected within sixty days after its certification or terminated on its expiration date, whichever is sooner, or if no exclusive bargaining representative is so selected, then the agreement shall be deemed to be terminated at its expiration date or as of such third anniversary date, whichever is sooner.

. Within the time limits prescribed in subsection (3) of this section, a petition may be filed signed by at least thirty percent of the employees of a collective bargaining unit, then represented by an exclusive bargaining representative, alleging that a majority of the employees in that unit do not wish to be represented by an employee organization, requesting that the exclusive bargaining representative be decertified, and indicating the name, address and telephone number of the exclusive bargaining representative and any other interested employee organization, if known. Upon the verification of the signatures on the petition, the commission shall conduct an election by secret ballot as prescribed by subsection (3) of this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c288.pdf?cite=1975%201st%20ex.s.%20c%20288%20§%208[1975 1st ex.s. c 288 § 8]; ]

== 41.59.080 - Determination of bargaining unit—Standards.
The commission, upon proper application for certification as an exclusive bargaining representative or upon petition for change of unit definition by the employer or any employee organization within the time limits specified in RCW 41.59.070(3), and after hearing upon reasonable notice, shall determine the unit appropriate for the purpose of collective bargaining. In determining, modifying or combining the bargaining unit, the commission shall consider the duties, skills, and working conditions of the educational employees; the history of collective bargaining; the extent of organization among the educational employees; and the desire of the educational employees; except that:

. A unit including nonsupervisory educational employees shall not be considered appropriate unless it includes all such nonsupervisory educational employees of the employer; and

. A unit that includes only supervisors may be considered appropriate if a majority of the employees in such category indicate by vote that they desire to be included in such a unit; and

. A unit that includes only principals and assistant principals may be considered appropriate if a majority of such employees indicate by vote that they desire to be included in such a unit; and

. A unit that includes both principals and assistant principals and other supervisory employees may be considered appropriate if a majority of the employees in each category indicate by vote that they desire to be included in such a unit; and

. A unit that includes supervisors and/or principals and assistant principals and nonsupervisory educational employees may be considered appropriate if a majority of the employees in each category indicate by vote that they desire to be included in such a unit; and

. A unit that includes only employees in vocational-technical institutes or occupational skill centers may be considered to constitute an appropriate bargaining unit if the history of bargaining in any such school district so justifies; and

. Notwithstanding the definition of collective bargaining, a unit that contains only supervisors and/or principals and assistant principals shall be limited in scope of bargaining to compensation, hours of work, and the number of days of work in the annual employment contracts; and

. The bargaining unit of certificated employees of school districts, educational service districts, or institutions of higher education that are education providers under chapter 28A.193 RCW must be limited to the employees working as education providers to juveniles in each adult correctional facility maintained by the department of corrections and must be separate from other bargaining units in school districts, educational service districts, or institutions of higher education.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6600-S.SL.pdf?cite=1998%20c%20244%20§%2011[1998 c 244 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c288.pdf?cite=1975%201st%20ex.s.%20c%20288%20§%209[1975 1st ex.s. c 288 § 9]; ]

== 41.59.090 - Certification of exclusive bargaining representative—Scope of representation.
The employee organization which has been determined to represent a majority of the employees in a bargaining unit shall be certified by the commission as the exclusive bargaining representative of, and shall be required to represent all the employees within the unit without regard to membership in that bargaining representative: PROVIDED, That any employee at any time may present his or her grievance to the employer and have such grievance adjusted without the intervention of the exclusive bargaining representative, as long as such representative has been given an opportunity to be present at that adjustment and to make its views known, and as long as the adjustment is not inconsistent with the terms of a collective bargaining agreement then in effect.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%2091[2012 c 117 § 91]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c288.pdf?cite=1975%201st%20ex.s.%20c%20288%20§%2010[1975 1st ex.s. c 288 § 10]; ]

== 41.59.105 - School district collective bargaining agreements.
. All collective bargaining agreements entered into between a school district employer and school district employees under this chapter after June 10, 2010, as well as bargaining agreements existing on June 10, 2010, but renewed or extended after June 10, 2010, shall be consistent with RCW 28A.657.050.

. All collective bargaining agreements entered into between a school district employer and school district employees under this chapter shall be consistent with RCW 28A.400.280 and 28A.400.350.

. Employee bargaining shall be initiated after July 1, 2018, over the dollar amount to be contributed beginning January 1, 2020, on behalf of each employee for health care benefits. Bargaining must subsequently be conducted in even-numbered years between the governor or governor's designee and one coalition of all the exclusive bargaining representatives impacted by benefit purchasing with the school employees' benefits board established in RCW 41.05.740, consistent with RCW 28A.400.280 and 28A.400.350. The coalition bargaining must follow the model initially established for state employees in RCW 41.80.020.

. The governor shall submit a request for funds necessary to implement the collective bargaining agreement for the dollar amount to be expended for school employee health benefits, or for legislation necessary to implement the agreement. A request for funds shall not be submitted to the legislature by the governor unless such request:

.. Has been submitted to the director of the office of financial management by October 1st prior to the legislative session at which the request is to be considered; and

.. Has been certified by the director of the office of financial management as being feasible financially for the state.

The legislature shall approve or reject the submission of the request for funds. The legislature shall not consider a request for funds unless the request is transmitted to the legislature as part of the governor's budget document submitted under RCW 43.88.030 and 43.88.060.

If the legislature rejects or fails to act on the submission, either party may reopen all or part of the agreement. However, if the director of the office of financial management does not certify a request under this section as being feasible financially for the state, the parties shall enter into collective bargaining solely for the purpose of reaching a mutually agreed upon modification of the agreement necessary to address the absence of those requested funds. The legislature may act upon the health care benefit provisions of the modified collective bargaining agreement if those provisions are agreed upon and submitted to the office of financial management and legislative budget committees before final legislative action on the biennial or supplemental operating budget. If the legislature rejects or fails to act on the submission, either party may reopen all or part of the agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2017%203rd%20sp.s.%20c%2013%20§%20818[2017 3rd sp.s. c 13 § 818]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6696-S2.SL.pdf?cite=2010%20c%20235%20§%20803[2010 c 235 § 803]; ]

== 41.59.106 - Rights of employees and bargaining representatives of school districts dissolved due to financial insolvency.
Notwithstanding any other provision of this chapter, employees and bargaining representatives of school districts that are dissolved due to financial insolvency shall have resort to collective bargaining, including grievance arbitration and other processes, only to the extent provided by RCW 28A.315.229.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2617-S.SL.pdf?cite=2012%20c%20186%20§%2024[2012 c 186 § 24]; ]

== 41.59.110 - Commission, rules and regulations of—Federal precedents as standard.
. The commission shall promulgate, revise, or rescind, in the manner prescribed by the administrative procedure act, chapter 34.05 RCW, such rules and regulations as it may deem necessary and appropriate to administer the provisions of this chapter, in conformity with the intent and purpose of this chapter, and consistent with the best standards of labor-management relations.

. The rules, precedents, and practices of the national labor relations board, provided they are consistent with this chapter, shall be considered by the commission in its interpretation of this chapter, and prior to adoption of any aforesaid commission rules and regulations.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c288.pdf?cite=1975%201st%20ex.s.%20c%20288%20§%2012[1975 1st ex.s. c 288 § 12]; ]

== 41.59.120 - Resolving impasses in collective bargaining—Mediation—Fact-finding with recommendations—Other.
. Either an employer or an exclusive bargaining representative may declare that an impasse has been reached between them in collective bargaining and may request the commission to appoint a mediator for the purpose of assisting them in reconciling their differences and resolving the controversy on terms which are mutually acceptable. If the commission determines that its assistance is needed, not later than five days after the receipt of a request therefor, it shall appoint a mediator in accordance with rules and regulations for such appointment prescribed by the commission. The mediator shall meet with the parties or their representatives, or both, forthwith, either jointly or separately, and shall take such other steps as he or she may deem appropriate in order to persuade the parties to resolve their differences and effect a mutually acceptable agreement. The mediator, without the consent of both parties, shall not make findings of fact or recommend terms of settlement. The services of the mediator, including, if any, per diem expenses, shall be provided by the commission without cost to the parties. Nothing in this subsection (1) shall be construed to prevent the parties from mutually agreeing upon their own mediation procedure, and in the event of such agreement, the commission shall not appoint its own mediator unless failure to do so would be inconsistent with the effectuation of the purposes and policy of this chapter.

. If the mediator is unable to effect settlement of the controversy within ten days after his or her appointment, either party, by written notification to the other, may request that their differences be submitted to fact-finding with recommendations, except that the time for mediation may be extended by mutual agreement between the parties. Within five days after receipt of the aforesaid written request for fact-finding, the parties shall select a person to serve as fact finder and obtain a commitment from that person to serve. If they are unable to agree upon a fact finder or to obtain such a commitment within that time, either party may request the commission to designate a fact finder. The commission, within five days after receipt of such request, shall designate a fact finder in accordance with rules and regulations for such designation prescribed by the commission. The fact finder so designated shall not be the same person who was appointed mediator pursuant to subsection (1) of this section without the consent of both parties.

The fact finder, within five days after his or her appointment, shall meet with the parties or their representatives, or both, either jointly or separately, and make inquiries and investigations, hold hearings, and take such other steps as he or she may deem appropriate. For the purpose of such hearings, investigations and inquiries, the fact finder shall have the power to issue subpoenas requiring the attendance and testimony of witnesses and the production of evidence. If the dispute is not settled within ten days after his or her appointment, the fact finder shall make findings of fact and recommend terms of settlement within thirty days after his or her appointment, which recommendations shall be advisory only.

. Such recommendations, together with the findings of fact, shall be submitted in writing to the parties and the commission privately before they are made public. Either the commission, the fact finder, the employer, or the exclusive bargaining representative may make such findings and recommendations public if the dispute is not settled within five days after their receipt from the fact finder.

. The costs for the services of the fact finder, including, if any, per diem expenses and actual and necessary travel and subsistence expenses, and any other incurred costs, shall be borne by the commission without cost to the parties.

. Nothing in this section shall be construed to prohibit an employer and an exclusive bargaining representative from agreeing to substitute, at their own expense, their own procedure for resolving impasses in collective bargaining for that provided in this section or from agreeing to utilize for the purposes of this section any other governmental or other agency or person in lieu of the commission.

. Any fact finder designated by an employer and an exclusive representative or the commission for the purposes of this section shall be deemed an agent of the state.

. This section does not apply to negotiations and mediations conducted under RCW 28A.657.050.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%2092[2012 c 117 § 92]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6696-S2.SL.pdf?cite=2010%20c%20235%20§%20804[2010 c 235 § 804]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c288.pdf?cite=1975%201st%20ex.s.%20c%20288%20§%2013[1975 1st ex.s. c 288 § 13]; ]

== 41.59.130 - Binding arbitration procedures authorized.
An employer and an exclusive bargaining representative who enter into a collective bargaining agreement may include in such agreement procedures for binding arbitration of such disputes as may arise involving the interpretation or application of such agreement.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c288.pdf?cite=1975%201st%20ex.s.%20c%20288%20§%2014[1975 1st ex.s. c 288 § 14]; ]

== 41.59.140 - Unfair labor practices for employer, employee organization, enumerated.
. It shall be an unfair labor practice for an employer:

.. To interfere with, restrain, or coerce employees in the exercise of the rights guaranteed in RCW 41.59.060;

.. To dominate or interfere with the formation or administration of any employee organization or contribute financial or other support to it: PROVIDED, That subject to rules and regulations made by the commission pursuant to RCW 41.59.110, an employer shall not be prohibited from permitting employees to confer with it or its representatives or agents during working hours without loss of time or pay;

.. To encourage or discourage membership in any employee organization by discrimination in regard to hire, tenure of employment or any term or condition of employment, but nothing contained in this subsection shall prevent an employer from requiring, as a condition of continued employment, payment of periodic dues and fees uniformly required to an exclusive bargaining representative pursuant to *RCW 41.59.100;

.. To discharge or otherwise discriminate against an employee because he or she has filed charges or given testimony under **this chapter;

.. To refuse to bargain collectively with the representatives of its employees.

. It shall be an unfair labor practice for an employee organization:

.. To restrain or coerce (i) employees in the exercise of the rights guaranteed in RCW 41.59.060: PROVIDED, That this paragraph shall not impair the right of an employee organization to prescribe its own rules with respect to the acquisition or retention of membership therein; or (ii) an employer in the selection of his or her representatives for the purposes of collective bargaining or the adjustment of grievances;

.. To cause or attempt to cause an employer to discriminate against an employee in violation of subsection (1)(c) of this section;

.. To refuse to bargain collectively with an employer, provided it is the representative of its employees subject to RCW 41.59.090.

. The expressing of any views, argument, or opinion, or the dissemination thereof to the public, whether in written, printed, graphic, or visual form, shall not constitute or be evidence of an unfair labor practice under any of the provisions of **this chapter, if such expression contains no threat of reprisal or force or promise of benefit.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%2093[2012 c 117 § 93]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c288.pdf?cite=1975%201st%20ex.s.%20c%20288%20§%2015[1975 1st ex.s. c 288 § 15]; ]

== 41.59.150 - Commission to prevent unfair labor practices—Scope.
. The commission is empowered to prevent any person from engaging in any unfair labor practice as defined in RCW 41.59.140: PROVIDED, That a complaint shall not be processed for any unfair labor practice occurring more than six months before the filing of the complaint with the commission or in superior court. This power shall not be affected by any other means of adjustment or prevention that has been or may be established by agreement, law, equity or otherwise.

. If the commission determines that any person has engaged in or is engaging in any such unfair labor practices as defined in RCW 41.59.140, then the commission shall issue and cause to be served upon such person an order requiring such person to cease and desist from such unfair labor practice, and to take such affirmative action as will effectuate the purposes and policy of this chapter, such as the payment of damages and/or the reinstatement of employees.

. The commission may petition the superior court for the county in which the main office of the employer is located or wherein the person who has engaged or is engaging in such unfair labor practice resides or transacts business, for the enforcement of its order and for appropriate temporary relief.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6231.SL.pdf?cite=2018%20c%20252%20§%202[2018 c 252 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c58.pdf?cite=1983%20c%2058%20§%203[1983 c 58 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c288.pdf?cite=1975%201st%20ex.s.%20c%20288%20§%2016[1975 1st ex.s. c 288 § 16]; ]

== 41.59.160 - Applicability of administrative procedure act provisions to commission action.
Actions taken by or on behalf of the commission shall be pursuant to chapter 34.05 RCW, or rules and regulations adopted in accordance therewith, and the right of judicial review provided by chapter 34.05 RCW shall be applicable to all such actions and rules and regulations.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c288.pdf?cite=1975%201st%20ex.s.%20c%20288%20§%2017[1975 1st ex.s. c 288 § 17]; ]

== 41.59.170 - Effective date of certain agreements—Increased benefits during agreement authorized, when.
. Whenever a collective bargaining agreement between an employer and an exclusive bargaining representative is concluded after the termination date of the previous collective bargaining agreement between the employer and an employee organization representing the same employees, the effective date of such collective bargaining agreement may be the day after the termination date of the previous collective bargaining agreement and all benefits included in the new collective bargaining agreement, including wage or salary increases, may accrue beginning with such effective date as established by this subsection, and may also accrue beginning with the effective date of any individual employee contracts affected thereby.

. Any collective bargaining agreement may provide for the increase of any wages, salaries and other benefits during the term of such agreement or the term of any individual employee contracts concerned, in the event that the employer receives by increased appropriation or from other sources, additional moneys for such purposes.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c288.pdf?cite=1975%201st%20ex.s.%20c%20288%20§%2018[1975 1st ex.s. c 288 § 18]; ]

== 41.59.180 - Employees in specialized job category—Exclusion.
Notwithstanding the definition of "employee" in RCW 41.59.020, the commission may exclude from the coverage of chapter 288, Laws of 1975 1st ex. sess. any specialized job category of an employer where a majority of the persons employed in that job category consists of classified employees. At such time as a majority of such employees are certificated, the job category may be considered an appropriate unit under chapter 288, Laws of 1975 1st ex. sess.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1288.SL.pdf?cite=1997%20c%2013%20§%2014[1997 c 13 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c288.pdf?cite=1975%201st%20ex.s.%20c%20288%20§%2023[1975 1st ex.s. c 288 § 23]; ]

== 41.59.900 - Short title.
This chapter may be cited as the educational employment relations act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c288.pdf?cite=1975%201st%20ex.s.%20c%20288%20§%201[1975 1st ex.s. c 288 § 1]; ]

== 41.59.910 - Construction of chapter—Effect on existing agreements—Collective bargaining agreement prevails where conflict.
This chapter shall supersede existing statutes not expressly repealed to the extent that there is a conflict between a provision of this chapter and those other statutes. Except as otherwise expressly provided herein, nothing in this chapter shall be construed to annul, modify or preclude the renewal or continuation of any lawful agreement entered into prior to January 1, 1976 between an employer and an employee organization covering wages, hours, and terms and conditions of employment. Where there is a conflict between any collective bargaining agreement and any resolution, rule, policy or regulation of the employer or its agents, the terms of the collective bargaining agreement shall prevail.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c288.pdf?cite=1975%201st%20ex.s.%20c%20288%20§%2019[1975 1st ex.s. c 288 § 19]; ]

== 41.59.920 - Construction of chapter—Employee's rights preserved.
Except as otherwise expressly provided herein, nothing contained in this chapter shall be construed to deny or otherwise abridge any rights, privileges or benefits granted by law to employees.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c288.pdf?cite=1975%201st%20ex.s.%20c%20288%20§%2020[1975 1st ex.s. c 288 § 20]; ]

== 41.59.930 - Construction of chapter—Employer's responsibilities and rights preserved.
Nothing in this chapter shall be construed to interfere with the responsibilities and rights of the employer as specified by federal and state law, including the employer's responsibilities to students, the public, and other constituent elements of the institution.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c288.pdf?cite=1975%201st%20ex.s.%20c%20288%20§%2024[1975 1st ex.s. c 288 § 24]; ]

== 41.59.935 - Construction of chapter—Certain agreements subject to RCW  28A.150.410,  28A.400.200, and  28A.150.276.
Nothing in this chapter grants employers or employees the right to reach agreements regarding salary or compensation increases for the state's statutory program of basic education in excess of those authorized in accordance with RCW 28A.150.410 and 28A.400.200. School districts are authorized to reach agreements regarding salaries or compensation for enrichment activities subject to RCW 28A.400.200 and 28A.150.276.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2017%203rd%20sp.s.%20c%2013%20§%20706[2017 3rd sp.s. c 13 § 706]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20571[1990 c 33 § 571]; 1997 c 431 § 22; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987ex1c2.pdf?cite=1987%201st%20ex.s.%20c%202%20§%20206[1987 1st ex.s. c 2 § 206]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c16.pdf?cite=1981%20c%2016%20§%203[1981 c 16 § 3]; ]

== 41.59.936 - Construction of chapter—Certain agreements subject to RCW  28A.405.470.
Nothing in this chapter may be construed to grant employers or employees the right to reach agreements that are in conflict with the termination provisions of RCW 28A.405.470.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1741-S.SL.pdf?cite=2009%20c%20396%20§%2010[2009 c 396 § 10]; ]

== 41.59.937 - Collective bargaining agreements not altered or impaired—Compliance with chapter—2017 3rd sp.s. c 13.
Nothing in chapter 13, Laws of 2017 3rd sp. sess. is intended to alter or impair school district collective bargaining agreements that are in effect on October 19, 2017. Any school district collective bargaining agreement executed or modified after October 19, 2017, must comply with chapter 13, Laws of 2017 3rd sp. sess.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2017%203rd%20sp.s.%20c%2013%20§%20705[2017 3rd sp.s. c 13 § 705]; ]

== 41.59.940 - Effective date—1975 1st ex.s. c 288.
Except for RCW 41.59.040, 41.59.050, 41.59.110 and 41.59.160 which shall take effect ninety days following enactment hereof, this chapter and RCW * 28A.150.060 and 28A.405.100 as amended by chapter 288, Laws of 1975 1st ex. sess. shall take effect on January 1, 1976. Where the term "effective date of this chapter" is used elsewhere in this chapter it shall mean January 1, 1976.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c33.pdf?cite=1990%20c%2033%20§%20572[1990 c 33 § 572]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c288.pdf?cite=1975%201st%20ex.s.%20c%20288%20§%2026[1975 1st ex.s. c 288 § 26]; ]

