= 41.56 - Public employees' collective bargaining.
:toc:

== 41.56.010 - Declaration of purpose.
The intent and purpose of this chapter is to promote the continued improvement of the relationship between public employers and their employees by providing a uniform basis for implementing the right of public employees to join labor organizations of their own choosing and to be represented by such organizations in matters concerning their employment relations with public employers.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c108.pdf?cite=1967%20ex.s.%20c%20108%20§%201[1967 ex.s. c 108 § 1]; ]

== 41.56.020 - Application of chapter.
This chapter shall apply to any county or municipal corporation, or any political subdivision of the state of Washington, including district courts and superior courts, except as otherwise provided by RCW 54.04.170, 54.04.180, and chapters 41.59, 47.64, and 53.18 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5171-S2.SL.pdf?cite=1999%20c%20217%20§%201[1999 c 217 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2641.SL.pdf?cite=1994%20c%20297%20§%201[1994 c 297 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1152.SL.pdf?cite=1993%20c%2076%20§%202[1993 c 76 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5105.SL.pdf?cite=1992%20c%2036%20§%201[1992 c 36 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c275.pdf?cite=1989%20c%20275%20§%201[1989 c 275 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c135.pdf?cite=1987%20c%20135%20§%201[1987 c 135 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%20107[1985 c 7 § 107]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%2098[1983 c 3 § 98]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c108.pdf?cite=1967%20ex.s.%20c%20108%20§%202[1967 ex.s. c 108 § 2]; ]

== 41.56.021 - Application of chapter to employees of institutions of higher education—Exceptions—Limitations on bargaining.
. In addition to the entities listed in RCW 41.56.020, this chapter applies to employees of institutions of higher education who are exempted from civil service pursuant to RCW 41.06.070(2), with the following exceptions:

.. Executive employees, including all members of the governing board of each institution of higher education and related boards; all presidents and vice presidents; deans, directors, and chairs; and executive heads of major administrative or academic divisions;

.. Managers who perform any of the following functions:

... Formulate, develop, or establish institutional policy, or direct the work of an administrative unit;

... Manage, administer, and control a program, including its physical, financial, or personnel resources;

... Have substantial responsibility for human resources administration, legislative relations, public information, internal audits and investigations, or the preparation and administration of budgets;

... Functionally is above the first level of supervision and exercises authority that is not merely routine or clerical in nature and requires the consistent use of independent judgment;

.. Employees who, in the regular course of their duties, act as a principal assistant, administrative assistant, or personal assistant to employees as defined by (a) of this subsection;

.. Confidential employees;

.. Employees who assist assistant attorneys general who advise and represent managers or confidential employees in personnel or labor relations matters, or who advise or represent the state in tort actions.

. Employees subject to this section shall not be included in any unit of employees certified under RCW 41.56.022, 41.56.024, or 41.56.203, chapter 41.76 RCW, or chapter 41.80 RCW. Employees whose eligibility for collective bargaining is covered by chapter 28B.52, 41.76, or 41.80 RCW are exempt from the provisions of this chapter.

. Institutions of higher education and the exclusive bargaining representatives shall not agree to any proposal that would prevent the implementation of approved affirmative action plans or that would be inconsistent with the comparable worth agreement that provided the basis for the salary changes implemented beginning with the 1983-1985 biennium to achieve comparable worth.

. Institutions of higher education and the exclusive bargaining representative shall not bargain over rights of management that, in addition to all powers, duties, and rights established by constitutional provision or statute, shall include but not be limited to the following:

.. The functions and programs of the institution, the use of technology, and the structure of the organization;

.. The institution's budget and the size of its workforce, including determining the financial basis for layoffs;

.. The right to direct and supervise employees;

.. The right to take whatever actions are deemed necessary to carry out the mission of the state and the institutions of higher education during emergencies;

.. Retirement plans and retirement benefits; or

.. Health care benefits or other employee insurance benefits, except as provided in RCW 41.80.020.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2361-S.SL.pdf?cite=2007%20c%20136%20§%201[2007 c 136 § 1]; ]

== 41.56.022 - Application of chapter to University of Washington printing craft employees.
In addition to the entities listed in RCW 41.56.020, this chapter shall apply to the University of Washington with respect to the printing craft employees in the department of printing at the University of Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c484.pdf?cite=1987%20c%20484%20§%201[1987 c 484 § 1]; ]

== 41.56.024 - Application of chapter to classified employees of technical colleges.
In addition to the entities listed in RCW 41.56.020, this chapter shall apply to classified employees of technical colleges as provided for in RCW 28B.50.874.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5184-S.SL.pdf?cite=1991%20c%20238%20§%20112[1991 c 238 § 112]; ]

== 41.56.025 - Application of chapter to education providers under chapter  28A.193 RCW.
This chapter applies to the bargaining unit of classified employees of school districts, educational service districts, or institutions of higher education that are education providers under chapter 28A.193 RCW. Such bargaining units must be limited to the employees working as education providers to juveniles in each adult correctional facility maintained by the department of corrections and must be separate from other bargaining units in school districts, educational service districts, or institutions of higher education.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6600-S.SL.pdf?cite=1998%20c%20244%20§%2012[1998 c 244 § 12]; ]

== 41.56.0251 - Application of chapter to charter schools.
In addition to the entities listed in RCW 41.56.020, this chapter applies to any charter school established under chapter 28A.710 RCW. Any bargaining unit or units established at the charter school must be limited to employees working in the charter school and must be separate from other bargaining units in school districts, educational service districts, or institutions of higher education. Any charter school established under chapter 28A.710 RCW is a separate employer from any school district, including the school district in which it is located.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6194-S2.SL.pdf?cite=2016%20c%20241%20§%20137[2016 c 241 § 137]; 2013 c 2 § 307 (Initiative Measure No. 1240, approved November 6, 2012); ]

== 41.56.026 - Application of chapter to individual providers under chapter  74.39A RCW.
In addition to the entities listed in RCW 41.56.020, this chapter applies to individual providers who have contracts with the department under chapter 74.39A RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%2028[2018 c 278 § 28]; 2002 c 3 § 12 (Initiative Measure No. 775, approved November 6, 2001); ]

== 41.56.027 - Application of chapter to passenger-only ferry employees.
In addition to the entities listed in RCW 41.56.020, this chapter does apply to:

. Public employees of public transportation benefit areas providing passenger-only ferry service as provided in RCW 47.64.090; and

. Public employees of ferry districts providing passenger-only ferry service as provided in RCW 47.64.090.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6074-S.SL.pdf?cite=2003%20c%2091%20§%202[2003 c 91 § 2]; ]

== 41.56.028 - Application of chapter to family child care providers—Governor as public employer—Procedure—Intent.
. In addition to the entities listed in RCW 41.56.020, this chapter applies to the governor with respect to family child care providers. Solely for the purposes of collective bargaining and as expressly limited under subsections (2) and (3) of this section, the governor is the public employer of family child care providers who, solely for the purposes of collective bargaining, are public employees. The public employer shall be represented for bargaining purposes by the governor or the governor's designee appointed under chapter 41.80 RCW.

. This chapter governs the collective bargaining relationship between the governor and family child care providers, except as follows:

.. A statewide unit of all family child care providers is the only unit appropriate for purposes of collective bargaining under RCW 41.56.060.

.. The exclusive bargaining representative of family child care providers in the unit specified in (a) of this subsection shall be the representative chosen in an election conducted pursuant to RCW 41.56.070, except that in the initial election conducted under chapter 54, Laws of 2006, if more than one labor organization is on the ballot and none of the choices receives a majority of the votes cast, a runoff election shall be held.

.. Notwithstanding the definition of "collective bargaining" in RCW 41.56.030(4), the scope of collective bargaining for child care providers under this section shall be limited solely to: (i) Economic compensation, such as manner and rate of subsidy and reimbursement, including tiered reimbursements; (ii) health and welfare benefits; (iii) professional development and training; (iv) labor-management committees; (v) grievance procedures; and (vi) other economic matters. Retirement benefits shall not be subject to collective bargaining. By such obligation neither party shall be compelled to agree to a proposal or be required to make a concession unless otherwise provided in this chapter.

.. The mediation and interest arbitration provisions of RCW 41.56.430 through 41.56.470 and 41.56.480 apply, except that:

... With respect to commencement of negotiations between the governor and the exclusive bargaining representative of family child care providers, negotiations shall be commenced initially upon certification of an exclusive bargaining representative under (a) of this subsection and, thereafter, by February 1st of any even-numbered year; and

... The decision of the arbitration panel is not binding on the legislature and, if the legislature does not approve the request for funds necessary to implement the compensation and benefit provisions of the arbitrated collective bargaining agreement, is not binding on the state.

.. Family child care providers do not have the right to strike.

. Family child care providers who are public employees solely for the purposes of collective bargaining under subsection (1) of this section are not, for that reason, employees of the state for any purpose. This section applies only to the governance of the collective bargaining relationship between the employer and family child care providers as provided in subsections (1) and (2) of this section.

. This section does not create or modify:

.. The parents' or legal guardians' right to choose and terminate the services of any family child care provider that provides care for their child or children;

.. The secretary of the department of social and health services' right to adopt requirements under RCW 74.15.030, except for requirements related to grievance procedures and collective negotiations on personnel matters as specified in subsection (2)(c) of this section;

.. Chapter 26.44 RCW, RCW 43.43.832, 43.20A.205, and 74.15.130; and

.. The legislature's right to make programmatic modifications to the delivery of state services through child care subsidy programs, including standards of eligibility of parents, legal guardians, and family child care providers participating in child care subsidy programs, and the nature of services provided. The governor shall not enter into, extend, or renew any agreement under this section that does not expressly reserve the legislative rights described in this subsection (4)(d).

. Upon meeting the requirements of subsection (6) of this section, the governor must submit, as a part of the proposed biennial or supplemental operating budget submitted to the legislature under RCW 43.88.030, a request for funds necessary to implement the compensation and benefit provisions of a collective bargaining agreement entered into under this section or for legislation necessary to implement such agreement.

. A request for funds necessary to implement the compensation and benefit provisions of a collective bargaining agreement entered into under this section shall not be submitted by the governor to the legislature unless such request has been:

.. Submitted to the director of financial management by October 1st before the legislative session at which the request is to be considered, except that, for initial negotiations under this section, the request must be submitted by November 15, 2006; and

.. Certified by the director of financial management as being feasible financially for the state or reflects the binding decision of an arbitration panel reached under this section.

. The legislature must approve or reject the submission of the request for funds as a whole. If the legislature rejects or fails to act on the submission, any such agreement will be reopened solely for the purpose of renegotiating the funds necessary to implement the agreement.

. The governor shall periodically consult with the joint committee on employment relations established by RCW 41.80.010 regarding appropriations necessary to implement the compensation and benefit provisions of any collective bargaining agreement and, upon completion of negotiations, advise the committee on the elements of the agreement and on any legislation necessary to implement such agreement.

. After the expiration date of any collective bargaining agreement entered into under this section, all of the terms and conditions specified in any such agreement remain in effect until the effective date of a subsequent agreement, not to exceed one year from the expiration date stated in the agreement, except as provided in subsection (4)(d) of this section.

. If, after the compensation and benefit provisions of an agreement are approved by the legislature, a significant revenue shortfall occurs resulting in reduced appropriations, as declared by proclamation of the governor or by resolution of the legislature, both parties shall immediately enter into collective bargaining for a mutually agreed upon modification of the agreement.

. In enacting this section, the legislature intends to provide state action immunity under federal and state antitrust laws for the joint activities of family child care providers and their exclusive bargaining representative to the extent such activities are authorized by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1916-S.SL.pdf?cite=2007%20c%20278%20§%202[2007 c 278 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2353-S2.SL.pdf?cite=2006%20c%2054%20§%201[2006 c 54 § 1]; ]

== 41.56.029 - Application of chapter to adult family home providers—Governor as public employer—Procedure—Intent.
. In addition to the entities listed in RCW 41.56.020, this chapter applies to the governor with respect to adult family home providers. Solely for the purposes of collective bargaining and as expressly limited under subsections (2) and (3) of this section, the governor is the public employer of adult family home providers who, solely for the purposes of collective bargaining, are public employees. The public employer shall be represented for bargaining purposes by the governor or the governor's designee.

. There shall be collective bargaining, as defined in RCW 41.56.030, between the governor and adult family home providers, except as follows:

.. A statewide unit of all adult family home providers is the only unit appropriate for purposes of collective bargaining under RCW 41.56.060.

.. The exclusive bargaining representative of adult family home providers in the unit specified in (a) of this subsection shall be the representative chosen in an election conducted pursuant to RCW 41.56.070.

Bargaining authorization cards furnished as the showing of interest in support of any representation petition or motion for intervention filed under this section shall be exempt from disclosure under chapter 42.56 RCW.

.. Notwithstanding the definition of "collective bargaining" in RCW 41.56.030(4), the scope of collective bargaining for adult family home providers under this section shall be limited solely to: (i) Economic compensation, such as manner and rate of subsidy and reimbursement, including tiered reimbursements; (ii) health and welfare benefits; (iii) professional development and training; (iv) labor-management committees; (v) grievance procedures; and (vi) other economic matters. Retirement benefits shall not be subject to collective bargaining. By such obligation neither party shall be compelled to agree to a proposal or be required to make a concession unless otherwise provided in this chapter.

.. In addition to the entities listed in the mediation and interest arbitration provisions of RCW 41.56.430 through 41.56.470 and 41.56.480, the provisions apply to the governor or the governor's designee and the exclusive bargaining representative of adult family home providers, except that:

... In addition to the factors to be taken into consideration by an interest arbitration panel under RCW 41.56.465, the panel shall consider the financial ability of the state to pay for the compensation and benefit provisions of a collective bargaining agreement.

... The decision of the arbitration panel is not binding on the legislature and, if the legislature does not approve the request for funds necessary to implement the compensation and benefit provisions of the arbitrated collective bargaining agreement, the decision is not binding on the state.

.. Adult family home providers do not have the right to strike.

. Adult family home providers who are public employees solely for the purposes of collective bargaining under subsection (1) of this section are not, for that reason, employees of the state for any other purpose. This section applies only to the governance of the collective bargaining relationship between the employer and adult family home providers as provided in subsections (1) and (2) of this section.

. This section does not create or modify:

.. The department's authority to establish a plan of care for each consumer or its core responsibility to manage long-term care services under chapter 70.128 RCW, including determination of the level of care that each consumer is eligible to receive. However, at the request of the exclusive bargaining representative, the governor or the governor's designee appointed under chapter 41.80 RCW shall engage in collective bargaining, as defined in RCW 41.56.030(4), with the exclusive bargaining representative over how the department's core responsibility affects hours of work for adult family home providers. This subsection shall not be interpreted to require collective bargaining over an individual consumer's plan of care;

.. The department's obligation to comply with the federal medicaid statute and regulations and the terms of any community-based waiver granted by the federal department of health and human services and to ensure federal financial participation in the provision of the services;

.. The legislature's right to make programmatic modifications to the delivery of state services under chapter 70.128 RCW, including standards of eligibility of consumers and adult family home providers participating in the programs under chapter 70.128 RCW, and the nature of services provided. The governor shall not enter into, extend, or renew any agreement under this chapter that does not expressly reserve the legislative rights described in this subsection (4)(c);

.. The residents', parents', or legal guardians' right to choose and terminate the services of any licensed adult family home provider; and

.. RCW 43.43.832, 43.20A.205, or 74.15.130.

. Upon meeting the requirements of subsection (6) of this section, the governor must submit, as a part of the proposed biennial or supplemental operating budget submitted to the legislature under RCW 43.88.030, a request for funds necessary to implement the compensation and benefit provisions of a collective bargaining agreement entered into under this section or for legislation necessary to implement the agreement.

. A request for funds necessary to implement the compensation and benefit provisions of a collective bargaining agreement entered into under this section shall not be submitted by the governor to the legislature unless the request has been:

.. Submitted to the director of financial management by October 1st prior to the legislative session at which the requests are to be considered; and

.. Certified by the director of financial management as financially feasible for the state or reflective of a binding decision of an arbitration panel reached under subsection (2)(d) of this section.

. The legislature must approve or reject the submission of the request for funds as a whole. If the legislature rejects or fails to act on the submission, any collective bargaining agreement must be reopened for the sole purpose of renegotiating the funds necessary to implement the agreement.

. If, after the compensation and benefit provisions of an agreement are approved by the legislature, a significant revenue shortfall occurs resulting in reduced appropriations, as declared by proclamation of the governor or by resolution of the legislature, both parties shall immediately enter into collective bargaining for a mutually agreed upon modification of the agreement.

. After the expiration date of any collective bargaining agreement entered into under this section, all of the terms and conditions specified in the agreement remain in effect until the effective date of a subsequent agreement, not to exceed one year from the expiration date stated in the agreement.

. In enacting this section, the legislature intends to provide state action immunity under federal and state antitrust laws for the joint activities of adult family home providers and their exclusive bargaining representative to the extent the activities are authorized by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2111-S.SL.pdf?cite=2007%20c%20184%20§%201[2007 c 184 § 1]; ]

== 41.56.030 - Definitions.
As used in this chapter:

. "Adult family home provider" means a provider as defined in RCW 70.128.010 who receives payments from the medicaid and state-funded long-term care programs.

. "Bargaining representative" means any lawful organization which has as one of its primary purposes the representation of employees in their employment relations with employers.

. "Child care subsidy" means a payment from the state through a child care subsidy program established pursuant to RCW 74.12.340, 45 C.F.R. Sec. 98.1 through 98.17, or any successor program.

. "Collective bargaining" means the performance of the mutual obligations of the public employer and the exclusive bargaining representative to meet at reasonable times, to confer and negotiate in good faith, and to execute a written agreement with respect to grievance procedures and collective negotiations on personnel matters, including wages, hours and working conditions, which may be peculiar to an appropriate bargaining unit of such public employer, except that by such obligation neither party shall be compelled to agree to a proposal or be required to make a concession unless otherwise provided in this chapter.

. "Commission" means the public employment relations commission.

. "Executive director" means the executive director of the commission.

. "Family child care provider" means a person who: (a) Provides regularly scheduled care for a child or children in the home of the provider or in the home of the child or children for periods of less than twenty-four hours or, if necessary due to the nature of the parent's work, for periods equal to or greater than twenty-four hours; (b) receives child care subsidies; and (c) under chapter 43.216 RCW, is either licensed by the state or is exempt from licensing.

. "Fish and wildlife officer" means a fish and wildlife officer as defined in RCW 77.08.010 who ranks below lieutenant and includes officers, detectives, and sergeants of the department of fish and wildlife.

. "Individual provider" means an individual provider as defined in RCW 74.39A.240(3) who, solely for the purposes of collective bargaining, is a public employee as provided in RCW 74.39A.270.

. "Institution of higher education" means the University of Washington, Washington State University, Central Washington University, Eastern Washington University, Western Washington University, The Evergreen State College, and the various state community colleges.

. [Empty]
.. "Language access provider" means any independent contractor who provides spoken language interpreter services, whether paid by a broker, language access agency, or the respective department:

... For department of social and health services appointments, department of children, youth, and families appointments, medicaid enrollee appointments, or who provided these services on or after January 1, 2011, and before June 10, 2012;

... For department of labor and industries authorized medical and vocational providers who provided these services on or after January 1, 2019; or

... For state agencies who provided these services on or after January 1, 2019.

.. "Language access provider" does not mean a manager or employee of a broker or a language access agency.

. "Public employee" means any employee of a public employer except any person (a) elected by popular vote, or (b) appointed to office pursuant to statute, ordinance or resolution for a specified term of office as a member of a multimember board, commission, or committee, whether appointed by the executive head or body of the public employer, or (c) whose duties as deputy, administrative assistant or secretary necessarily imply a confidential relationship to (i) the executive head or body of the applicable bargaining unit, or (ii) any person elected by popular vote, or (iii) any person appointed to office pursuant to statute, ordinance or resolution for a specified term of office as a member of a multimember board, commission, or committee, whether appointed by the executive head or body of the public employer, or (d) who is a court commissioner or a court magistrate of superior court, district court, or a department of a district court organized under chapter 3.46 RCW, or (e) who is a personal assistant to a district court judge, superior court judge, or court commissioner. For the purpose of (e) of this subsection, no more than one assistant for each judge or commissioner may be excluded from a bargaining unit.

. "Public employer" means any officer, board, commission, council, or other person or body acting on behalf of any public body governed by this chapter, or any subdivision of such public body. For the purposes of this section, the public employer of district court or superior court employees for wage-related matters is the respective county legislative authority, or person or body acting on behalf of the legislative authority, and the public employer for nonwage-related matters is the judge or judge's designee of the respective district court or superior court.

. "Uniformed personnel" means: (a) Law enforcement officers as defined in RCW 41.26.030 employed by the governing body of any city or town with a population of two thousand five hundred or more and law enforcement officers employed by the governing body of any county with a population of ten thousand or more; (b) correctional employees who are uniformed and nonuniformed, commissioned and noncommissioned security personnel employed in a jail as defined in RCW 70.48.020(9), by a county with a population of seventy thousand or more, in a correctional facility created under RCW 70.48.095, or in a detention facility created under chapter 13.40 RCW that is located in a county with a population over one million five hundred thousand, and who are trained for and charged with the responsibility of controlling and maintaining custody of inmates in the jail and safeguarding inmates from other inmates; (c) general authority Washington peace officers as defined in RCW 10.93.020 employed by a port district in a county with a population of one million or more; (d) security forces established under RCW 43.52.520; (e) firefighters as that term is defined in RCW 41.26.030; (f) employees of a port district in a county with a population of one million or more whose duties include crash fire rescue or other firefighting duties; (g) employees of fire departments of public employers who dispatch exclusively either fire or emergency medical services, or both; (h) employees in the several classes of advanced life support technicians, as defined in RCW 18.71.200, who are employed by a public employer; or (i) court marshals of any county who are employed by, trained for, and commissioned by the county sheriff and charged with the responsibility of enforcing laws, protecting and maintaining security in all county-owned or contracted property, and performing any other duties assigned to them by the county sheriff or mandated by judicial order.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5481-S2.SL.pdf?cite=2020%20c%20298%20§%201[2020 c 298 § 1]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2691.SL.pdf?cite=2020%20c%20289%20§%201[2020 c 289 § 1]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5199.SL.pdf?cite=2019%20c%20280%20§%201[2019 c 280 § 1]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6245-S2.SL.pdf?cite=2018%20c%20253%20§%206[2018 c 253 § 6]; 2018 c 253 § 5; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20808[2017 3rd sp.s. c 6 § 808]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6092.SL.pdf?cite=2015%202nd%20sp.s.%20c%206%20§%201[2015 2nd sp.s. c 6 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1371-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2021%20§%2011[2011 1st sp.s. c 21 § 11]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6726-S.SL.pdf?cite=2010%20c%20296%20§%203[2010 c 296 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2111-S.SL.pdf?cite=2007%20c%20184%20§%202[2007 c 184 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2353-S2.SL.pdf?cite=2006%20c%2054%20§%202[2006 c 54 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2933-S.SL.pdf?cite=2004%20c%203%20§%206[2004 c 3 § 6]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2662-S.SL.pdf?cite=2002%20c%2099%20§%202[2002 c 99 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5152.SL.pdf?cite=2000%20c%2023%20§%201[2000 c 23 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2722.SL.pdf?cite=2000%20c%2019%20§%201[2000 c 19 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5171-S2.SL.pdf?cite=1999%20c%20217%20§%202[1999 c 217 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1730-S.SL.pdf?cite=1995%20c%20273%20§%201[1995 c 273 § 1]; prior:  1993 c 398 § 1; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1067.SL.pdf?cite=1993%20c%20397%20§%201[1993 c 397 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1509-S.SL.pdf?cite=1993%20c%20379%20§%20302[1993 c 379 § 302]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5105.SL.pdf?cite=1992%20c%2036%20§%202[1992 c 36 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1201-S.SL.pdf?cite=1991%20c%20363%20§%20119[1991 c 363 § 119]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c275.pdf?cite=1989%20c%20275%20§%202[1989 c 275 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c135.pdf?cite=1987%20c%20135%20§%202[1987 c 135 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c150.pdf?cite=1984%20c%20150%20§%201[1984 c 150 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c296.pdf?cite=1975%201st%20ex.s.%20c%20296%20§%2015[1975 1st ex.s. c 296 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c131.pdf?cite=1973%20c%20131%20§%202[1973 c 131 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c108.pdf?cite=1967%20ex.s.%20c%20108%20§%203[1967 ex.s. c 108 § 3]; ]

== 41.56.037 - Presenting information about the exclusive bargaining representative—Access to new employees.
. [Empty]
.. The employer must provide the exclusive bargaining representative reasonable access to new employees of the bargaining unit for the purposes of presenting information about their exclusive bargaining representative to the new employee. The presentation may occur during a new employee orientation provided by the employer, or at another time mutually agreed to by the employer and the exclusive bargaining representative.

.. No employee may be mandated to attend the meetings or presentations by the exclusive bargaining representative.

.. "Reasonable access" for the purposes of this section means:

... The access to the new employee occurs within ninety days of the employee's start date within the bargaining unit;

... The access is for no less than thirty minutes; and

... The access occurs during the new employee's regular work hours at the employee's regular worksite, or at a location mutually agreed to by the employer and the exclusive bargaining representative.

. Nothing in this section prohibits an employer from agreeing to longer or more frequent new employee access, but in no case may an employer agree to less access than required by this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6229.SL.pdf?cite=2018%20c%20250%20§%201[2018 c 250 § 1]; ]

== 41.56.040 - Right of employees to organize and designate representatives without interference.
No public employer, or other person, shall directly or indirectly, interfere with, restrain, coerce, or discriminate against any public employee or group of public employees in the free exercise of their right to organize and designate representatives of their own choosing for the purpose of collective bargaining, or in the free exercise of any other right under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c108.pdf?cite=1967%20ex.s.%20c%20108%20§%204[1967 ex.s. c 108 § 4]; ]

== 41.56.050 - Disagreement in selection of bargaining representative—Disagreement as to merger of bargaining units—Intervention by commission.
. In the event that a public employer and public employees are in disagreement as to the selection of a bargaining representative, the commission shall be invited to intervene as is provided in RCW 41.56.060 through 41.56.090.

. In the event that a public employer and a bargaining representative are in disagreement as to the merger of two or more bargaining units in the employer's workforce that are represented by the same bargaining representative, the commission shall be invited to intervene as is provided in RCW 41.56.060 through 41.56.090.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1127-S.SL.pdf?cite=2011%20c%20222%20§%201[2011 c 222 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c296.pdf?cite=1975%201st%20ex.s.%20c%20296%20§%2016[1975 1st ex.s. c 296 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c108.pdf?cite=1967%20ex.s.%20c%20108%20§%205[1967 ex.s. c 108 § 5]; ]

== 41.56.060 - Determination of bargaining unit—Bargaining representative.
. The commission, after hearing upon reasonable notice, shall decide in each application for certification as an exclusive bargaining representative, the unit appropriate for the purpose of collective bargaining. In determining, modifying, or combining the bargaining unit, the commission shall consider the duties, skills, and working conditions of the public employees; the history of collective bargaining by the public employees and their bargaining representatives; the extent of organization among the public employees; and the desire of the public employees. The commission shall determine the bargaining representative by: (a) Examination of organization membership rolls; (b) comparison of signatures on organization bargaining authorization cards, as provided under RCW 41.56.095; or (c) conducting an election specifically therefor.

. For classified employees of school districts and educational service districts:

.. Appropriate bargaining units existing on July 24, 2005, may not be divided into more than one unit without the agreement of the public employer and the certified bargaining representative of the unit; and

.. In making bargaining unit determinations under this section, the commission must consider, in addition to the factors listed in subsection (1) of this section, the avoidance of excessive fragmentation.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1575-S.SL.pdf?cite=2019%20c%20230%20§%207[2019 c 230 § 7]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1432.SL.pdf?cite=2005%20c%20232%20§%201[2005 c 232 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c296.pdf?cite=1975%201st%20ex.s.%20c%20296%20§%2017[1975 1st ex.s. c 296 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c108.pdf?cite=1967%20ex.s.%20c%20108%20§%206[1967 ex.s. c 108 § 6]; ]

== 41.56.070 - Election to ascertain bargaining representative.
In the event the commission elects to conduct an election to ascertain the exclusive bargaining representative, and upon the request of a prospective bargaining representative showing written proof of at least thirty percent representation of the public employees within the unit, the commission shall hold an election by secret ballot to determine the issue. The ballot shall contain the name of such bargaining representative and of any other bargaining representative showing written proof of at least ten percent representation of the public employees within the unit, together with a choice for any public employee to designate that he or she does not desire to be represented by any bargaining agent. Where more than one organization is on the ballot and neither of the three or more choices receives a majority vote of the public employees within the bargaining unit, a runoff election shall be held. The runoff ballot shall contain the two choices which received the largest and second-largest number of votes. No question concerning representation may be raised within one year of a certification or attempted certification. Where there is a valid collective bargaining agreement in effect, no question of representation may be raised except during the period not more than ninety nor less than sixty days prior to the expiration date of the agreement. Any agreement which contains a provision for automatic renewal or extension of the agreement shall not be a valid agreement; nor shall any agreement be valid if it provides for a term of existence for more than three years, except that any agreement entered into between school districts, cities, counties, or municipal corporations, and their respective employees, may provide for a term of existence of up to six years.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%2083[2012 c 117 § 83]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5251.SL.pdf?cite=2007%20c%2075%20§%202[2007 c 75 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5251.SL.pdf?cite=2007%20c%2075%20§%201[2007 c 75 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c296.pdf?cite=1975%201st%20ex.s.%20c%20296%20§%2018[1975 1st ex.s. c 296 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c108.pdf?cite=1967%20ex.s.%20c%20108%20§%207[1967 ex.s. c 108 § 7]; ]

== 41.56.080 - Certification of bargaining representative—Scope of representation.
The bargaining representative which has been determined to represent a majority of the employees in a bargaining unit shall be certified by the commission as the exclusive bargaining representative of, and shall be required to represent, all the public employees within the unit without regard to membership in said bargaining representative: PROVIDED, That any public employee at any time may present his or her grievance to the public employer and have such grievance adjusted without the intervention of the exclusive bargaining representative, if the adjustment is not inconsistent with the terms of a collective bargaining agreement then in effect, and if the exclusive bargaining representative has been given reasonable opportunity to be present at any initial meeting called for the resolution of such grievance.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%2084[2012 c 117 § 84]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c296.pdf?cite=1975%201st%20ex.s.%20c%20296%20§%2019[1975 1st ex.s. c 296 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c108.pdf?cite=1967%20ex.s.%20c%20108%20§%208[1967 ex.s. c 108 § 8]; ]

== 41.56.090 - Rules and regulations.
The commission shall promulgate, revise or rescind such rules and regulations as it may deem necessary or appropriate to administer the provisions of this chapter in conformity with the intent and purpose of this chapter and consistent with the best standards of labor-management relations.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c296.pdf?cite=1975%201st%20ex.s.%20c%20296%20§%2020[1975 1st ex.s. c 296 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c108.pdf?cite=1967%20ex.s.%20c%20108%20§%209[1967 ex.s. c 108 § 9]; ]

== 41.56.095 - Certification of bargaining representative—Cross-check.
. Except as provided under subsection (2) of this section, if only one employee organization is seeking certification as the exclusive bargaining representative of a bargaining unit for which there is no incumbent exclusive bargaining representative, the commission may determine the question concerning representation by conducting a cross-check comparing the employee organization's membership records or bargaining authorization cards against the employment records of the employer. A determination through a cross-check process may be made upon a showing of interest submitted in support of the exclusive bargaining representative by more than fifty percent of the employees. The commission may adopt rules to implement this section.

. This section does not apply to those employees under RCW 41.56.026, 41.56.028, 41.56.029, and 41.56.510.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1575-S.SL.pdf?cite=2019%20c%20230%20§%208[2019 c 230 § 8]; ]

== 41.56.100 - Authority and duty of employer to engage in collective bargaining—Limitations—Mediation, grievance procedures upon failure to agree.
. A public employer shall have the authority to engage in collective bargaining with the exclusive bargaining representative and no public employer shall refuse to engage in collective bargaining with the exclusive bargaining representative. However, a public employer is not required to bargain collectively with any bargaining representative concerning any matter which by ordinance, resolution, or charter of said public employer has been delegated to any civil service commission or personnel board similar in scope, structure, and authority to the board created by chapter 41.06 RCW.

. Upon the failure of the public employer and the exclusive bargaining representative to conclude a collective bargaining agreement, any matter in dispute may be submitted by either party to the commission. This subsection does not apply to negotiations and mediations conducted between a school district employer and an exclusive bargaining representative under RCW 28A.657.050.

. If a public employer implements its last and best offer where there is no contract settlement, allegations that either party is violating the terms of the implemented offer shall be subject to grievance arbitration procedures if and as such procedures are set forth in the implemented offer, or, if not in the implemented offer, if and as such procedures are set forth in the parties' last contract.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6696-S2.SL.pdf?cite=2010%20c%20235%20§%20801[2010 c 235 § 801]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c45.pdf?cite=1989%20c%2045%20§%201[1989 c 45 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c296.pdf?cite=1975%201st%20ex.s.%20c%20296%20§%2021[1975 1st ex.s. c 296 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c108.pdf?cite=1967%20ex.s.%20c%20108%20§%2010[1967 ex.s. c 108 § 10]; ]

== 41.56.110 - Employee authorization of membership dues and other payments—Revocation.
. Upon the authorization of an employee within the bargaining unit and after the certification or recognition of the bargaining unit's exclusive bargaining representative, the employer shall deduct from the payments to the employee the monthly amount of dues as certified by the secretary of the exclusive bargaining representative and shall transmit the same to the treasurer of the exclusive bargaining representative.

. [Empty]
.. An employee's written, electronic, or recorded voice authorization to have the employer deduct membership dues from the employee's salary must be made by the employee to the exclusive bargaining representative. If the employer receives a request for authorization of deductions, the employer shall as soon as practicable forward the request to the exclusive bargaining representative.

.. Upon receiving notice of the employee's authorization from the exclusive bargaining representative, the employer shall deduct from the employee's salary membership dues and remit the amounts to the exclusive bargaining representative.

.. The employee's authorization remains in effect until expressly revoked by the employee in accordance with the terms and conditions of the authorization.

. [Empty]
.. An employee's request to revoke authorization for payroll deductions must be in writing and submitted by the employee to the exclusive bargaining representative in accordance with the terms and conditions of the authorization.

.. After the employer receives confirmation from the exclusive bargaining representative that the employee has revoked authorization for deductions, the employer shall end the deduction no later than the second payroll after receipt of the confirmation.

. The employer shall rely on information provided by the exclusive bargaining representative regarding the authorization and revocation of deductions.

. If the employer and the exclusive bargaining representative of a bargaining unit enter into a collective bargaining agreement that includes requirements for deductions of other payments, the employer must make such deductions upon authorization of the employee.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1575-S.SL.pdf?cite=2019%20c%20230%20§%209[2019 c 230 § 9]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2751.SL.pdf?cite=2018%20c%20247%20§%202[2018 c 247 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c59.pdf?cite=1973%20c%2059%20§%201[1973 c 59 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c108.pdf?cite=1967%20ex.s.%20c%20108%20§%2011[1967 ex.s. c 108 § 11]; ]

== 41.56.113 - Department-contracted individual providers—Family child care providers—Adult family home providers—Language access providers—Employee authorization of membership dues and other payments—Revocation—Third-party entity permitted to act as an individual provider's agent.
. This subsection (1) applies only if the state makes the payments directly to a provider.

.. Upon the authorization of an individual provider who contracts with the department of social and health services, a family child care provider, an adult family home provider, or a language access provider within the bargaining unit and after the certification or recognition of the bargaining unit's exclusive bargaining representative, the state as payor, but not as the employer, shall, subject to (c) of this subsection, deduct from the payments to an individual provider who contracts with the department of social and health services, a family child care provider, an adult family home provider, or a language access provider the monthly amount of dues as certified by the secretary of the exclusive bargaining representative and shall transmit the same to the treasurer of the exclusive bargaining representative.

.. [Empty]
... An employee's written, electronic, or recorded voice authorization to have the employer deduct membership dues from the employee's salary must be made by the employee to the exclusive bargaining representative. If the employer receives a request for authorization of deductions, the employer shall as soon as practicable forward the request to the exclusive bargaining representative.

... Upon receiving notice of the employee's authorization from the exclusive bargaining representative, the employer shall deduct from the employee's salary membership dues and remit the amounts to the exclusive bargaining representative.

... The employee's authorization remains in effect until expressly revoked by the employee in accordance with the terms and conditions of the authorization.

... An employee's request to revoke authorization for payroll deductions must be in writing and submitted by the employee to the exclusive bargaining representative in accordance with the terms and conditions of the authorization.

.. After the employer receives confirmation from the exclusive bargaining representative that the employee has revoked authorization for deductions, the employer shall end the deduction no later than the second payroll after receipt of the confirmation.

.. The employer shall rely on information provided by the exclusive bargaining representative regarding the authorization and revocation of deductions.

.. If the governor and the exclusive bargaining representative of a bargaining unit of individual providers who contract with the department of social and health services, family child care providers, adult family home providers, or language access providers enter into a collective bargaining agreement that includes requirements for deductions of other payments, the state, as payor, but not as the employer, shall, subject to (c) of this subsection, make such deductions upon authorization of the individual provider, family child care provider, adult family home provider, or language access provider.

.. [Empty]
... The initial additional costs to the state in making deductions from the payments to individual providers, family child care providers, adult family home providers, and language access providers under this section shall be negotiated, agreed upon in advance, and reimbursed to the state by the exclusive bargaining representative.

... The allocation of ongoing additional costs to the state in making deductions from the payments to individual providers, family child care providers, adult family home providers, or language access providers under this section shall be an appropriate subject of collective bargaining between the exclusive bargaining representative and the governor unless prohibited by another statute. If no collective bargaining agreement containing a provision allocating the ongoing additional cost is entered into between the exclusive bargaining representative and the governor, or if the legislature does not approve funding for the collective bargaining agreement as provided in RCW 74.39A.300, 41.56.028, 41.56.029, or 41.56.510, as applicable, the ongoing additional costs to the state in making deductions from the payments to individual providers, family child care providers, adult family home providers, or language access providers under this section shall be negotiated, agreed upon in advance, and reimbursed to the state by the exclusive bargaining representative.

. This subsection (2) applies only if the state does not make the payments directly to a language access provider. Upon the authorization of a language access provider within the bargaining unit and after the certification or recognition of the bargaining unit's exclusive bargaining representative, the state shall require through its contracts with third parties that:

.. The monthly amount of dues as certified by the secretary of the exclusive bargaining representative be deducted from the payments to the language access provider and transmitted to the treasurer of the exclusive bargaining representative; and

.. A record showing that dues have been deducted as specified in (a) of this subsection be provided to the state.

. This subsection (3) applies only to individual providers who contract with the department of social and health services. The exclusive bargaining representative of individual providers may designate a third-party entity to act as the individual provider's agent in receiving payments from the state to the individual provider, so long as the individual provider has entered into an agency agreement with a third-party entity for the purposes of deducting and remitting voluntary payments to the exclusive bargaining representative. A third-party entity that receives such payments is responsible for making and remitting deductions authorized by the individual provider. The costs of such deductions must be paid by the exclusive bargaining representative.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1575-S.SL.pdf?cite=2019%20c%20230%20§%2010[2019 c 230 § 10]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6199-S.SL.pdf?cite=2018%20c%20278%20§%2029[2018 c 278 § 29]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6726-S.SL.pdf?cite=2010%20c%20296%20§%204[2010 c 296 § 4]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2111-S.SL.pdf?cite=2007%20c%20184%20§%203[2007 c 184 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2353-S2.SL.pdf?cite=2006%20c%2054%20§%203[2006 c 54 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2933-S.SL.pdf?cite=2004%20c%203%20§%207[2004 c 3 § 7]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2662-S.SL.pdf?cite=2002%20c%2099%20§%201[2002 c 99 § 1]; ]

== 41.56.120 - Right to strike not granted.
Nothing contained in this chapter shall permit or grant any public employee the right to strike or refuse to perform his or her official duties.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%2085[2012 c 117 § 85]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c108.pdf?cite=1967%20ex.s.%20c%20108%20§%2012[1967 ex.s. c 108 § 12]; ]

== 41.56.122 - Collective bargaining agreements—Binding arbitration.
A collective bargaining agreement may provide for binding arbitration of a labor dispute arising from the application or the interpretation of the matters contained in a collective bargaining agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1575-S.SL.pdf?cite=2019%20c%20230%20§%2011[2019 c 230 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c296.pdf?cite=1975%201st%20ex.s.%20c%20296%20§%2022[1975 1st ex.s. c 296 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c59.pdf?cite=1973%20c%2059%20§%202[1973 c 59 § 2]; ]

== 41.56.123 - Collective bargaining agreements—Effect of termination—Application of section.
. After the termination date of a collective bargaining agreement, all of the terms and conditions specified in the collective bargaining agreement shall remain in effect until the effective date of a subsequent agreement, not to exceed one year from the termination date stated in the agreement. Thereafter, the employer may unilaterally implement according to law.

. This section does not apply to provisions of a collective bargaining agreement which both parties agree to exclude from the provisions of subsection (1) of this section and to provisions within the collective bargaining agreement with separate and specific termination dates.

. This section shall not apply to the following:

.. Bargaining units covered by RCW 41.56.430 et seq. for fact-finding and interest arbitration;

.. Collective bargaining agreements authorized by chapter 53.18 RCW; or

.. Collective bargaining agreements authorized by chapter 54.04 RCW.

. This section shall not apply to collective bargaining agreements in effect or being bargained on July 23, 1989.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1081.SL.pdf?cite=1993%20c%20398%20§%204[1993 c 398 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c46.pdf?cite=1989%20c%2046%20§%201[1989 c 46 § 1]; ]

== 41.56.125 - Arbitrators—Selection—Additional method.
In addition to any other method for selecting arbitrators, the parties may request the public employment relations commission to, and the commission shall, appoint a qualified person who may be an employee of the commission to act as an arbitrator to assist in the resolution of a labor dispute between such public employer and such bargaining representative arising from the application of the matters contained in a collective bargaining agreement. The arbitrator shall conduct such arbitration of such dispute in a manner as provided for in the collective bargaining agreement: PROVIDED, That the commission shall not collect any fees or charges from such public employer or such bargaining representative for services performed by the commission under the provisions of this chapter: PROVIDED FURTHER, That the provisions of chapter 49.08 RCW shall have no application to this chapter.

[ 1975 1st ex.s. 296 § 23; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c59.pdf?cite=1973%20c%2059%20§%203[1973 c 59 § 3]; ]

== 41.56.130 - Rules and regulations of Washington state personnel resources board—Mandatory subjects.
See RCW 41.06.150.

[ ]

== 41.56.140 - Unfair labor practices for public employer enumerated.
It shall be an unfair labor practice for a public employer:

. To interfere with, restrain, or coerce public employees in the exercise of their rights guaranteed by this chapter;

. To control, dominate, or interfere with a bargaining representative;

. To discriminate against a public employee who has filed an unfair labor practice charge;

. To refuse to engage in collective bargaining with the certified exclusive bargaining representative.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1127-S.SL.pdf?cite=2011%20c%20222%20§%202[2011 c 222 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c215.pdf?cite=1969%20ex.s.%20c%20215%20§%201[1969 ex.s. c 215 § 1]; ]

== 41.56.150 - Unfair labor practices for bargaining representative enumerated.
It shall be an unfair labor practice for a bargaining representative:

. To interfere with, restrain, or coerce public employees in the exercise of their rights guaranteed by this chapter;

. To induce the public employer to commit an unfair labor practice;

. To discriminate against a public employee who has filed an unfair labor practice charge;

. To refuse to engage in collective bargaining.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c215.pdf?cite=1969%20ex.s.%20c%20215%20§%202[1969 ex.s. c 215 § 2]; ]

== 41.56.160 - Commission to prevent unfair labor practices and issue remedial orders and cease and desist orders.
. The commission is empowered and directed to prevent any unfair labor practice and to issue appropriate remedial orders: PROVIDED, That a complaint shall not be processed for any unfair labor practice occurring more than six months before the filing of the complaint with the commission or in superior court. This power shall not be affected or impaired by any means of adjustment, mediation or conciliation in labor disputes that have been or may hereafter be established by law.

. If the commission determines that any person has engaged in or is engaging in an unfair labor practice, the commission shall issue and cause to be served upon the person an order requiring the person to cease and desist from such unfair labor practice, and to take such affirmative action as will effectuate the purposes and policy of this chapter, such as the payment of damages and the reinstatement of employees.

. The commission may petition the superior court for the county in which the main office of the employer is located or in which the person who has engaged or is engaging in such unfair labor practice resides or transacts business, for the enforcement of its order and for appropriate temporary relief.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6231.SL.pdf?cite=2018%20c%20252%20§%201[2018 c 252 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6195-S.SL.pdf?cite=1994%20c%2058%20§%201[1994 c 58 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c58.pdf?cite=1983%20c%2058%20§%201[1983 c 58 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c296.pdf?cite=1975%201st%20ex.s.%20c%20296%20§%2024[1975 1st ex.s. c 296 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c215.pdf?cite=1969%20ex.s.%20c%20215%20§%203[1969 ex.s. c 215 § 3]; ]

== 41.56.165 - Applicability of administrative procedure act to commission action.
Actions taken by or on behalf of the commission shall be pursuant to chapter 34.05 RCW, or rules adopted in accordance with chapter 34.05 RCW, and the right of judicial review provided by chapter 34.05 RCW shall be applicable to all such actions and rules.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6195-S.SL.pdf?cite=1994%20c%2058%20§%202[1994 c 58 § 2]; ]

== 41.56.203 - University of Washington—Certain employees enrolled in an academic program—Scope of collective bargaining.
. In addition to the entities listed in RCW 41.56.020, this chapter applies to the University of Washington with respect to employees who are enrolled in an academic program and are in a classification in (a) through (i) of this subsection on any University of Washington campus. The employees in (a) through (i) of this subsection constitute an appropriate bargaining unit:

.. Predoctoral instructor;

.. Predoctoral lecturer;

.. Predoctoral teaching assistant;

.. Predoctoral teaching associates I and II;

.. Tutors, readers, and graders in all academic units and tutoring centers;

.. Predoctoral staff assistant;

.. Predoctoral staff associates I and II;

.. Except as provided in this subsection (1)(h), predoctoral researcher, predoctoral research assistant, and predoctoral research associates I and II. The employees that constitute an appropriate bargaining unit under this subsection (1) do not include predoctoral researchers, predoctoral research assistants, and predoctoral research associates I and II who are performing research primarily related to their dissertation and who have incidental or no service expectations placed upon them by the university; and

.. All employees enrolled in an academic program whose duties and responsibilities are substantially equivalent to those employees in (a) through (h) of this subsection.

. [Empty]
.. The scope of bargaining for employees at the University of Washington under this section excludes:

... The ability to terminate the employment of any individual if the individual is not meeting academic requirements as determined by the University of Washington;

... The amount of tuition or fees at the University of Washington. However, tuition and fee remission and waiver is within the scope of bargaining;

... The academic calendar of the University of Washington; and

... The number of students to be admitted to a particular class or class section at the University of Washington.

.. [Empty]
... Except as provided in (b)(ii) of this subsection, provisions of collective bargaining agreements relating to compensation must not exceed the amount or percentage established by the legislature in the appropriations act. If any compensation provision is affected by subsequent modification of the appropriations act by the legislature, both parties must immediately enter into collective bargaining for the sole purpose of arriving at a mutually agreed upon replacement for the affected provision.

... The University of Washington may provide additional compensation to student employees covered by this section that exceeds that provided by the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2540-S.SL.pdf?cite=2002%20c%2034%20§%202[2002 c 34 § 2]; ]

== 41.56.205 - Washington State University—Certain employees enrolled in an academic program—Scope of collective bargaining.
. In addition to the entities listed in RCW 41.56.020, this chapter applies to Washington State University with respect to employees who are enrolled in an academic program and are in a classification in (a) through (g) of this subsection on any Washington State University campus. The employees in (a) through (g) of this subsection constitute an appropriate bargaining unit:

.. Graduate teaching assistant;

.. Graduate staff assistant;

.. Graduate project assistant;

.. Graduate veterinary assistant;

.. Tutor, reader, and graders in all academic units and tutoring centers;

.. Except as provided in this subsection (1)(f), graduate research assistant. The employees that constitute an appropriate bargaining unit under this subsection (1) do not include graduate research assistants who are performing research primarily related to their dissertation and who have incidental or no service expectations placed upon them by the university; and

.. All employees enrolled in an academic program whose duties and responsibilities are substantially equivalent to those employees in (a) through (f) of this subsection.

. [Empty]
.. The scope of bargaining for employees at Washington State University under this section excludes:

... The ability to terminate the employment of any individual if the individual is not meeting academic requirements as determined by Washington State University;

... The amount of tuition or fees at Washington State University. However, tuition and fee remission and waiver is within the scope of bargaining;

... The academic calendar of Washington State University; and

... The number of students to be admitted to a particular class or class section at Washington State University.

.. [Empty]
... Except as provided in (b)(ii) of this subsection, provisions of collective bargaining agreements relating to compensation must not exceed the amount or percentage established by the legislature in the appropriations act. If any compensation provision is affected by subsequent modification of the appropriations act by the legislature, both parties must immediately enter into collective bargaining for the sole purpose of arriving at a mutually agreed upon replacement for the affected provision.

... Washington State University may provide additional compensation to student employees covered by this section that exceeds that provided by the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2963-S.SL.pdf?cite=2008%20c%20203%20§%202[2008 c 203 § 2]; ]

== 41.56.210 - Department to prevent unfair labor practices and issue remedial orders—Application to state civil service employees.
See RCW 41.06.340.

[ ]

== 41.56.220 - Right of employee representing bargaining unit to be absent from employment during legislative session—Replacement.
Any public employee who represents fifty percent or more of a bargaining unit or who represents on a statewide basis a group of five or more bargaining units shall have the right to absent himself or herself from his or her employment without pay and without suffering any discrimination in his or her future employment and without losing benefits incident to his or her employment while representing his or her bargaining unit at the legislature of the state of Washington during any regular or special session thereof: PROVIDED, That such employee is replaced by his or her bargaining unit with an employee who shall be paid by the employer and who shall be qualified to perform the duties and obligations of the absent member in accordance with the rules of the civil service or other standards established by his or her employer for such absent employee.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%2086[2012 c 117 § 86]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c87.pdf?cite=1980%20c%2087%20§%2017[1980 c 87 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c174.pdf?cite=1969%20ex.s.%20c%20174%20§%201[1969 ex.s. c 174 § 1]; ]

== 41.56.230 - Rights of employees and bargaining representatives of school districts dissolved due to financial insolvency.
Notwithstanding any other provision of this chapter, employees and bargaining representatives of school districts that are dissolved due to financial insolvency shall have resort to collective bargaining, including grievance arbitration and other processes, only to the extent provided by RCW 28A.315.229.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2617-S.SL.pdf?cite=2012%20c%20186%20§%2023[2012 c 186 § 23]; ]

== 41.56.430 - Uniformed personnel—Legislative declaration.
The intent and purpose of chapter 131, Laws of 1973 is to recognize that there exists a public policy in the state of Washington against strikes by uniformed personnel as a means of settling their labor disputes; that the uninterrupted and dedicated service of these classes of employees is vital to the welfare and public safety of the state of Washington; that to promote such dedicated and uninterrupted public service there should exist an effective and adequate alternative means of settling disputes.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c131.pdf?cite=1973%20c%20131%20§%201[1973 c 131 § 1]; ]

== 41.56.440 - Uniformed personnel—Negotiations—Declaration of an impasse—Appointment of mediator.
Negotiations between a public employer and the bargaining representative in a unit of uniformed personnel shall be commenced at least five months prior to the submission of the budget to the legislative body of the public employer. If no agreement has been reached sixty days after the commencement of such negotiations then, at any time thereafter, either party may declare that an impasse exists and may submit the dispute to the commission for mediation, with or without the concurrence of the other party. The commission shall appoint a mediator, who shall forthwith meet with the representatives of the parties, either jointly or separately, and shall take such other steps as he or she may deem appropriate in order to persuade the parties to resolve their differences and effect an agreement: PROVIDED, That a mediator does not have a power of compulsion.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c184.pdf?cite=1979%20ex.s.%20c%20184%20§%201[1979 ex.s. c 184 § 1]; 1975-'76 2nd ex.s. c 14 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c296.pdf?cite=1975%201st%20ex.s.%20c%20296%20§%2028[1975 1st ex.s. c 296 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c131.pdf?cite=1973%20c%20131%20§%203[1973 c 131 § 3]; ]

== 41.56.450 - Uniformed personnel—Interest arbitration panel—Powers and duties—Hearings—Findings and determination.
If an agreement has not been reached following a reasonable period of negotiations and mediation, and the executive director, upon the recommendation of the assigned mediator, finds that the parties remain at impasse, then an interest arbitration panel shall be created to resolve the dispute. The issues for determination by the arbitration panel shall be limited to the issues certified by the executive director. Within seven days following the issuance of the determination of the executive director, each party shall name one person to serve as its arbitrator on the arbitration panel. The two members so appointed shall meet within seven days following the appointment of the later appointed member to attempt to choose a third member to act as the neutral chair of the arbitration panel. Upon the failure of the arbitrators to select a neutral chair within seven days, the two appointed members shall use one of the two following options in the appointment of the third member, who shall act as chair of the panel: (1) By mutual consent, the two appointed members may jointly request the commission to, and the commission shall, appoint a third member within two days of such request. Costs of each party's appointee shall be borne by each party respectively; other costs of the arbitration proceedings shall be borne by the commission; or (2) either party may apply to the commission, the federal mediation and conciliation service, or the American Arbitration Association to provide a list of five qualified arbitrators from which the neutral chair shall be chosen. Each party shall pay the fees and expenses of its arbitrator, and the fees and expenses of the neutral chair shall be shared equally between the parties.

The arbitration panel so constituted shall promptly establish a date, time, and place for a hearing and shall provide reasonable notice thereof to the parties to the dispute. A hearing, which shall be informal, shall be held, and each party shall have the opportunity to present evidence and make argument. No member of the arbitration panel may present the case for a party to the proceedings. The rules of evidence prevailing in judicial proceedings may be considered, but are not binding, and any oral testimony or documentary evidence or other data deemed relevant by the chair of the arbitration panel may be received in evidence. A recording of the proceedings shall be taken. The arbitration panel has the power to administer oaths, require the attendance of witnesses, and require the production of such books, papers, contracts, agreements, and documents as may be deemed by the panel to be material to a just determination of the issues in dispute. If any person refuses to obey a subpoena issued by the arbitration panel, or refuses to be sworn or to make an affirmation to testify, or any witness, party, or attorney for a party is guilty of any contempt while in attendance at any hearing held hereunder, the arbitration panel may invoke the jurisdiction of the superior court in the county where the labor dispute exists, and the court has jurisdiction to issue an appropriate order. Any failure to obey the order may be punished by the court as a contempt thereof. The hearing conducted by the arbitration panel shall be concluded within twenty-five days following the selection or designation of the neutral chair of the arbitration panel, unless the parties agree to a longer period.

The neutral chair shall consult with the other members of the arbitration panel, and, within thirty days following the conclusion of the hearing, the neutral chair shall make written findings of fact and a written determination of the issues in dispute, based on the evidence presented. A copy thereof shall be served on the commission, on each of the other members of the arbitration panel, and on each of the parties to the dispute. That determination shall be final and binding upon both parties, subject to review by the superior court upon the application of either party solely upon the question of whether the decision of the panel was arbitrary or capricious.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%2087[2012 c 117 § 87]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c287.pdf?cite=1983%20c%20287%20§%202[1983 c 287 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c184.pdf?cite=1979%20ex.s.%20c%20184%20§%202[1979 ex.s. c 184 § 2]; 1975-'76 2nd ex.s. c 14 § 2; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c296.pdf?cite=1975%201st%20ex.s.%20c%20296%20§%2029[1975 1st ex.s. c 296 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c131.pdf?cite=1973%20c%20131%20§%204[1973 c 131 § 4]; ]

== 41.56.452 - Interest arbitration panel a state agency.
An interest arbitration panel created pursuant to RCW 41.56.450, in the performance of its duties under chapter 41.56 RCW, exercises a state function and is, for the purposes of this chapter, a state agency. Chapter 34.05 RCW does not apply to proceedings before an interest arbitration panel under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c287.pdf?cite=1983%20c%20287%20§%203[1983 c 287 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c87.pdf?cite=1980%20c%2087%20§%2019[1980 c 87 § 19]; ]

== 41.56.465 - Uniformed personnel—Interest arbitration panel—Determinations—Factors to be considered.
. In making its determination, the panel shall be mindful of the legislative purpose enumerated in RCW 41.56.430 and, as additional standards or guidelines to aid it in reaching a decision, the panel shall consider:

.. The constitutional and statutory authority of the employer;

.. Stipulations of the parties;

.. The average consumer prices for goods and services, commonly known as the cost of living;

.. Changes in any of the circumstances under (a) through (c) of this subsection during the pendency of the proceedings; and

.. Such other factors, not confined to the factors under (a) through (d) of this subsection, that are normally or traditionally taken into consideration in the determination of wages, hours, and conditions of employment. For those employees listed in *RCW 41.56.030(7)(a) who are employed by the governing body of a city or town with a population of less than fifteen thousand, or a county with a population of less than seventy thousand, consideration must also be given to regional differences in the cost of living.

. For employees listed in *RCW 41.56.030(7) (a) through (d), the panel shall also consider a comparison of the wages, hours, and conditions of employment of personnel involved in the proceedings with the wages, hours, and conditions of employment of like personnel of like employers of similar size on the west coast of the United States.

. For employees listed in *RCW 41.56.030(7) (e) through (h), the panel shall also consider a comparison of the wages, hours, and conditions of employment of personnel involved in the proceedings with the wages, hours, and conditions of employment of like personnel of public fire departments of similar size on the west coast of the United States. However, when an adequate number of comparable employers exists within the state of Washington, other west coast employers may not be considered.

. For employees listed in RCW 41.56.028:

.. The panel shall also consider:

... A comparison of child care provider subsidy rates and reimbursement programs by public entities, including counties and municipalities, along the west coast of the United States; and

... The financial ability of the state to pay for the compensation and benefit provisions of a collective bargaining agreement; and

.. The panel may consider:

... The public's interest in reducing turnover and increasing retention of child care providers;

... The state's interest in promoting, through education and training, a stable child care workforce to provide quality and reliable child care from all providers throughout the state; and

... In addition, for employees exempt from licensing under chapter 74.15 RCW, the state's fiscal interest in reducing reliance upon public benefit programs including but not limited to medical coupons, food stamps, subsidized housing, and emergency medical services.

. For employees listed in RCW 74.39A.270:

.. The panel shall consider:

... A comparison of wages, hours, and conditions of employment of publicly reimbursed personnel providing similar services to similar clients, including clients who are elderly, frail, or have developmental disabilities, both in the state and across the United States; and

... The financial ability of the state to pay for the compensation and fringe benefit provisions of a collective bargaining agreement; and

.. The panel may consider:

... A comparison of wages, hours, and conditions of employment of publicly employed personnel providing similar services to similar clients, including clients who are elderly, frail, or have developmental disabilities, both in the state and across the United States;

... The state's interest in promoting a stable long-term care workforce to provide quality and reliable care to vulnerable elderly and disabled recipients;

... The state's interest in ensuring access to affordable, quality health care for all state citizens; and

... The state's fiscal interest in reducing reliance upon public benefit programs including but not limited to medical coupons, food stamps, subsidized housing, and emergency medical services.

. Subsections (2) and (3) of this section may not be construed to authorize the panel to require the employer to pay, directly or indirectly, the increased employee contributions resulting from chapter 502, Laws of 1993 or chapter 517, Laws of 1993 as required under chapter 41.26 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1916-S.SL.pdf?cite=2007%20c%20278%20§%201[2007 c 278 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1730-S.SL.pdf?cite=1995%20c%20273%20§%202[1995 c 273 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1081.SL.pdf?cite=1993%20c%20398%20§%203[1993 c 398 § 3]; ]

== 41.56.470 - Uniformed personnel—Arbitration panel—Rights of parties.
During the pendency of the proceedings before the arbitration panel, existing wages, hours, and other conditions of employment shall not be changed by action of either party without the consent of the other but a party may so consent without prejudice to his or her rights or position under chapter 131, Laws of 1973.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%2088[2012 c 117 § 88]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c131.pdf?cite=1973%20c%20131%20§%206[1973 c 131 § 6]; ]

== 41.56.473 - Uniformed personnel—Application of chapter to Washington state patrol—Bargaining subjects.
. In addition to the entities listed in RCW 41.56.020, this chapter applies to the state with respect to the officers of the Washington state patrol appointed under RCW 43.43.020, except that the state is prohibited from negotiating any matters relating to retirement benefits or health care benefits or other employee insurance benefits.

. For the purposes of negotiating wages, wage-related matters, and nonwage matters, the state shall be represented by the governor or the governor's designee who is appointed under chapter 41.80 RCW, and costs of the negotiations under this section shall be reimbursed as provided in RCW 41.80.140.

. The governor or the governor's designee shall consult with the chief of the Washington state patrol regarding collective bargaining.

. The negotiation of provisions pertaining to wages and wage-related matters in a collective bargaining agreement between the state and the Washington state patrol officers is subject to the following:

.. The state's bargaining representative must periodically consult with a subcommittee of the joint committee on employment relations created in *RCW 41.80.010(5) which shall consist of the four members appointed to the joint committee with leadership positions in the senate and the house of representatives, and the chairs and ranking minority members of the senate transportation committee and the house transportation committee, or their successor committees. The subcommittee must be consulted regarding the appropriations necessary to implement these provisions in a collective bargaining agreement and, on completion of negotiations, must be advised on the elements of these provisions.

.. Provisions that are entered into before the legislature approves the funds necessary to implement the provisions must be conditioned upon the legislature's subsequent approval of the funds.

. The governor shall submit a request for funds necessary to implement the wage and wage-related matters in the collective bargaining agreement or for legislation necessary to implement the agreement. Requests for funds necessary to implement the provisions of bargaining agreements may not be submitted to the legislature by the governor unless such requests:

.. Have been submitted to the director of financial management by October 1st before the legislative session at which the requests are to be considered; and

.. Have been certified by the director of financial management as being feasible financially for the state or reflects the decision of an arbitration panel reached under RCW 41.56.475.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1188-S2.SL.pdf?cite=2005%20c%20438%20§%201[2005 c 438 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5171-S2.SL.pdf?cite=1999%20c%20217%20§%203[1999 c 217 § 3]; ]

== 41.56.475 - Uniformed personnel—Application of chapter to Washington state patrol—Mediation and arbitration.
In addition to the classes of employees listed in *RCW 41.56.030(7), the provisions of RCW 41.56.430 through 41.56.452 and 41.56.470, 41.56.480, and 41.56.490 also apply to Washington state patrol officers appointed under RCW 43.43.020 as provided in this section, subject to the following:

. Within ten working days after the first Monday in September of every odd-numbered year, the state's bargaining representative and the bargaining representative for the appropriate bargaining unit shall attempt to agree on an interest arbitration panel consisting of three members to be used if the parties are not successful in negotiating a comprehensive collective bargaining agreement. Each party shall name one person to serve as its arbitrator on the arbitration panel. The two members so appointed shall meet within seven days following the appointment of the later appointed member to attempt to choose a third member to act as the neutral chair of the arbitration panel. Upon the failure of the arbitrators to select a neutral chair within seven days, the two appointed members shall use one of the two following options in the appointment of the third member, who shall act as chair of the panel: (a) By mutual consent, the two appointed members may jointly request the commission to, and the commission shall, appoint a third member within two days of such a request. Costs of each party's appointee shall be borne by each party respectively; other costs of the arbitration proceedings shall be borne by the commission; or (b) either party may apply to the commission, the federal mediation and conciliation service, or the American arbitration association to provide a list of five qualified arbitrators from which the neutral chair shall be chosen. Each party shall pay the fees and expenses of its arbitrator, and the fees and expenses of the neutral chair shall be shared equally between the parties. Immediately upon selecting an interest arbitration panel, the parties shall cooperate to reserve dates with the arbitration panel for potential arbitration between August 1st and September 15th of the following even-numbered year. The parties shall also prepare a schedule of at least five negotiation dates for the following year, absent an agreement to the contrary. The parties shall execute a written agreement before November 1st of each odd-numbered year setting forth the names of the members of the arbitration panel and the dates reserved for bargaining and arbitration. This subsection imposes minimum obligations only and is not intended to define or limit a party's full, good faith bargaining obligation under other sections of this chapter.

. The mediator or arbitration panel may consider only matters that are subject to bargaining under RCW 41.56.473.

. The decision of an arbitration panel is not binding on the legislature and, if the legislature does not approve the funds necessary to implement provisions pertaining to wages and wage-related matters of an arbitrated collective bargaining agreement, is not binding on the state or the Washington state patrol.

. In making its determination, the arbitration panel shall be mindful of the legislative purpose enumerated in RCW 41.56.430 and, as additional standards or guidelines to aid it in reaching a decision, shall take into consideration the following factors:

.. The constitutional and statutory authority of the employer;

.. Stipulations of the parties;

.. Comparison of the hours and conditions of employment of personnel involved in the proceedings with the hours and conditions of employment of like personnel of like employers of similar size on the west coast of the United States;

.. Changes in any of the foregoing circumstances during the pendency of the proceedings; and

.. Such other factors, not confined to the foregoing, which are normally or traditionally taken into consideration in the determination of matters that are subject to bargaining under RCW 41.56.473.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3002-S.SL.pdf?cite=2008%20c%20149%20§%201[2008 c 149 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1188-S2.SL.pdf?cite=2005%20c%20438%20§%202[2005 c 438 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5171-S2.SL.pdf?cite=1999%20c%20217%20§%204[1999 c 217 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5380-S.SL.pdf?cite=1993%20c%20351%20§%201[1993 c 351 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c110.pdf?cite=1988%20c%20110%20§%202[1988 c 110 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c135.pdf?cite=1987%20c%20135%20§%203[1987 c 135 § 3]; ]

== 41.56.480 - Uniformed personnel—Refusal to submit to procedures—Invoking jurisdiction of superior court—Contempt.
If the representative of either or both the uniformed personnel and the public employer refuse to submit to the procedures set forth in RCW 41.56.440 and 41.56.450, the parties, or the commission on its own motion, may invoke the jurisdiction of the superior court for the county in which the labor dispute exists and such court shall have jurisdiction to issue an appropriate order. A failure to obey such order may be punished by the court as a contempt thereof. A decision of the arbitration panel shall be final and binding on the parties, and may be enforced at the instance of either party, the arbitration panel or the commission in the superior court for the county where the dispute arose.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c296.pdf?cite=1975%201st%20ex.s.%20c%20296%20§%2030[1975 1st ex.s. c 296 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c131.pdf?cite=1973%20c%20131%20§%207[1973 c 131 § 7]; ]

== 41.56.490 - Uniformed employees—Strikes prohibited—Violations—Contempt of court.
The right of uniformed employees to engage in any strike, work slowdown, or stoppage is not granted. An organization recognized as the bargaining representative of uniformed employees subject to this chapter that willfully disobeys a lawful order of enforcement by a superior court pursuant to RCW 41.56.480 and 41.56.490, or willfully offers resistance to such order, whether by strike or otherwise, is in contempt of court as provided in chapter 7.21 RCW. An employer that willfully disobeys a lawful order of enforcement by a superior court pursuant to RCW 41.56.480 or willfully offers resistance to such order is in contempt of court as provided in chapter 7.21 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c373.pdf?cite=1989%20c%20373%20§%2024[1989 c 373 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c131.pdf?cite=1973%20c%20131%20§%208[1973 c 131 § 8]; ]

== 41.56.492 - Application of uniformed personnel collective bargaining provisions to employees of public passenger transportation systems—Conditions.
In addition to the classes of employees listed in *RCW 41.56.030(7), the provisions of RCW 41.56.430 through 41.56.452, 41.56.470, 41.56.480, and 41.56.490 shall also be applicable to the employees of a public passenger transportation system of a metropolitan municipal corporation, county transportation authority, public transportation benefit area, or city public passenger transportation system, subject to the following:

. Negotiations between the public employer and the bargaining representative may commence at any time agreed to by the parties. If no agreement has been reached ninety days after commencement of negotiations, either party may demand that the issues in disagreement be submitted to a mediator. The services of the mediator shall be provided by the commission without cost to the parties, but nothing in this section or RCW 41.56.440 shall be construed to prohibit the public employer and the bargaining representative from agreeing to substitute at their own expense some other mediator or mediation procedure; and

. If an agreement has not been reached following a reasonable period of negotiations and mediation, and the mediator finds that the parties remain at impasse, either party may demand that the issues in disagreement be submitted to an arbitration panel for a binding and final determination. In making its determination, the arbitration panel shall be mindful of the legislative purpose enumerated in RCW 41.56.430 and as additional standards or guidelines to aid it in reaching a decisions [decision], shall take into consideration the following factors:

.. The constitutional and statutory authority of the employer;

.. Stipulations of the parties;

.. Compensation package comparisons, economic indices, fiscal constraints, and similar factors determined by the arbitration panel to be pertinent to the case; and

.. Such other factors, not confined to the foregoing, which are normally or traditionally taken into consideration in the determination of wages, hours, and conditions of employment.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5483-S.SL.pdf?cite=1993%20c%20473%20§%201[1993 c 473 § 1]; ]

== 41.56.496 - Commercial nuclear plants—Application of chapter to certain employees.
. In order to assure the uninterrupted and dedicated service of employees employed by employees of operators of certain commercial nuclear plants, the provisions of RCW 41.56.430 through 41.56.470, 41.56.480, and 41.56.490 shall apply to the operating and maintenance employees of a joint operating agency as defined in RCW 43.52.250 who are employed at a commercial nuclear power plant operating under a site certificate issued under chapter 80.50 RCW, except as provided in subsection (2) of this section.

. In making its determination, the arbitration panel shall take into consideration the following factors:

.. The constitutional and statutory authority of the employer;

.. Stipulations of the parties;

.. A comparison of the wages, benefits, hours of work, and working conditions of the personnel involved in the proceeding with those of like personnel in relevant Washington labor markets. For classifications not found in Washington, the comparison shall be made with similar personnel in the states of California and Arizona, taking into account the relative differences in the cost of living;

.. Economic indices, fiscal constraints, relative differences in the cost of living, and similar factors determined by the arbitration panel to be pertinent to the case;

.. Other factors, not confined to the factors under (a) through (d) of this subsection, that are normally or traditionally taken into consideration in the determination of wages, benefits, hours of work, and working conditions.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5492.SL.pdf?cite=2009%20c%20126%20§%201[2009 c 126 § 1]; ]

== 41.56.500 - School district collective bargaining agreements.
. All collective bargaining agreements entered into between a school district employer and school district employees under this chapter after June 10, 2010, as well as bargaining agreements existing on June 10, 2010, but renewed or extended after June 10, 2010, shall be consistent with RCW 28A.657.050.

. All collective bargaining agreements entered into between a school district employer and school district employees under this chapter shall be consistent with RCW 28A.400.280 and 28A.400.350.

. Employee bargaining shall be initiated after July 1, 2018, over the dollar amount to be contributed for school employee health benefits beginning January 1, 2020, on behalf of each employee for health care benefits. Bargaining must subsequently be conducted in even-numbered years between the governor or governor's designee and one coalition of all the exclusive bargaining representatives impacted by benefit purchasing with the school employees' benefits board established in RCW 41.05.740, consistent with RCW 28A.400.280 and 28A.400.350. The coalition bargaining must follow the model initially established for state employees in RCW 41.80.020.

. The governor shall submit a request for funds necessary to implement the collective bargaining agreement for the dollar amount to be expended for school employee health benefits, or for legislation necessary to implement the agreement. A request for funds shall not be submitted to the legislature by the governor unless such request:

.. Has been submitted to the director of the office of financial management by October 1st prior to the legislative session at which the request is to be considered; and

.. Has been certified by the director of the office of financial management as being feasible financially for the state.

The legislature shall approve or reject the submission of the request for funds. The legislature shall not consider a request for funds unless the request is transmitted to the legislature as part of the governor's budget document submitted under RCW 43.88.030 and 43.88.060.

If the legislature rejects or fails to act on the submission, either party may reopen all or part of the agreement. However, if the director of the office of financial management does not certify a request under this section as being feasible financially for the state, the parties shall enter into collective bargaining solely for the purpose of reaching a mutually agreed upon modification of the agreement necessary to address the absence of those requested funds. The legislature may act upon the health care benefit provisions of the modified collective bargaining agreement if those provisions are agreed upon and submitted to the office of financial management and legislative budget committees before final legislative action on the biennial or supplemental operating budget. If the legislature rejects or fails to act on the submission, either party may reopen all or part of the agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2017%203rd%20sp.s.%20c%2013%20§%20817[2017 3rd sp.s. c 13 § 817]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6696-S2.SL.pdf?cite=2010%20c%20235%20§%20802[2010 c 235 § 802]; ]

== 41.56.510 - Application of chapter to language access providers—Governor as public employer—Procedure—Intent—Report.
. In addition to the entities listed in RCW 41.56.020, this chapter applies to the governor with respect to language access providers. Solely for the purposes of collective bargaining and as expressly limited under subsections (2) and (3) of this section, the governor is the public employer of language access providers who, solely for the purposes of collective bargaining, are public employees. The governor or the governor's designee shall represent the public employer for bargaining purposes.

. There shall be collective bargaining, as defined in RCW 41.56.030, between the governor and language access providers, except as follows:

.. The only units appropriate for purposes of collective bargaining under RCW 41.56.060 are:

... A statewide unit for language access providers who provide spoken language interpreter services for department of social and health services appointments, department of children, youth, and families appointments, or medicaid enrollee appointments;

... A statewide unit for language access providers who provide spoken language interpreter services for injured workers or crime victims receiving benefits from the department of labor and industries; and

... A statewide unit for language access providers who provide spoken language interpreter services for any state agency through the department of enterprise services, excluding language access providers included in (a)(i) and (ii) of this subsection;

.. The exclusive bargaining representative of language access providers in the unit specified in (a) of this subsection shall be the representative chosen in an election conducted pursuant to RCW 41.56.070.

Bargaining authorization cards furnished as the showing of interest in support of any representation petition or motion for intervention filed under this section are exempt from disclosure under chapter 42.56 RCW;

.. Notwithstanding the definition of "collective bargaining" in RCW 41.56.030(4), the scope of collective bargaining for language access providers under this section is limited solely to: (i) Economic compensation, such as the manner and rate of payments, including tiered payments; (ii) professional development and training; (iii) labor-management committees; (iv) grievance procedures; (v) health and welfare benefits; and (vii) [(vi)] other economic matters. Retirement benefits are not subject to collective bargaining. By such obligation neither party may be compelled to agree to a proposal or be required to make a concession unless otherwise provided in this chapter;

.. In addition to the entities listed in the mediation and interest arbitration provisions of RCW 41.56.430 through 41.56.470 and 41.56.480, the provisions apply to the governor or the governor's designee and the exclusive bargaining representative of language access providers, except that:

... In addition to the factors to be taken into consideration by an interest arbitration panel under RCW 41.56.465, the panel shall consider the financial ability of the state to pay for the compensation and benefit provisions of a collective bargaining agreement;

... The decision of the arbitration panel is not binding on the legislature and, if the legislature does not approve the request for funds necessary to implement the compensation and benefit provisions of the arbitrated collective bargaining agreement, the decision is not binding on the state;

.. Language access providers do not have the right to strike;

.. If a single employee organization is the exclusive bargaining representative for two or more units, upon petition by the employee organization, the units may be consolidated into a single larger unit if the commission considers the larger unit to be appropriate. If consolidation is appropriate, the commission shall certify the employee organization as the exclusive bargaining representative of the new unit;

.. If a single employee organization is the exclusive bargaining representative for two or more bargaining units, the governor and the employee organization may agree to negotiate a single collective bargaining agreement for all of the bargaining units that the employee organization represents.

. Language access providers who are public employees solely for the purposes of collective bargaining under subsection (1) of this section are not, for that reason, employees of the state for any other purpose. This section applies only to the governance of the collective bargaining relationship between the employer and language access providers as provided in subsections (1) and (2) of this section.

. Each party with whom the department of social and health services, the department of children, youth, and families, the department of labor and industries, and the department of enterprise services contracts for language access services and each of their subcontractors shall provide to the respective department an accurate list of language access providers, as defined in RCW 41.56.030, including their names, addresses, and other contact information, annually by January 30th, except that initially the lists must be provided within thirty days of July 1, 2018. The department shall, upon request, provide a list of all language access providers, including their names, addresses, and other contact information, to a labor union seeking to represent language access providers.

. This section does not create or modify:

.. The obligation of any state agency to comply with federal statute and regulations; and

.. The legislature's right to make programmatic modifications to the delivery of state services under chapter 74.04 or 39.26 RCW or Title 51 RCW. The governor may not enter into, extend, or renew any agreement under this chapter that does not expressly reserve the legislative rights described in this subsection.

. Upon meeting the requirements of subsection (7) of this section, the governor must submit, as a part of the proposed biennial or supplemental operating budget submitted to the legislature under RCW 43.88.030, a request for funds necessary to implement the compensation and benefit provisions of a collective bargaining agreement entered into under this section or for legislation necessary to implement the agreement.

. A request for funds necessary to implement the compensation and benefit provisions of a collective bargaining agreement entered into under this section may not be submitted by the governor to the legislature unless the request has been:

.. Submitted to the director of financial management by October 1st prior to the legislative session at which the requests are to be considered, except that, for initial negotiations under this section, the request may not be submitted before July 1, 2011; and

.. Certified by the director of financial management as financially feasible for the state or reflective of a binding decision of an arbitration panel reached under subsection (2)(d) of this section.

. The legislature must approve or reject the submission of the request for funds as a whole. If the legislature rejects or fails to act on the submission, any collective bargaining agreement must be reopened for the sole purpose of renegotiating the funds necessary to implement the agreement.

. If, after the compensation and benefit provisions of an agreement are approved by the legislature, a significant revenue shortfall occurs resulting in reduced appropriations, as declared by proclamation of the governor or by resolution of the legislature, both parties shall immediately enter into collective bargaining for a mutually agreed upon modification of the agreement.

. After the expiration date of any collective bargaining agreement entered into under this section, all of the terms and conditions specified in the agreement remain in effect until the effective date of a subsequent agreement, not to exceed one year from the expiration date stated in the agreement.

. In enacting this section, the legislature intends to provide state action immunity under federal and state antitrust laws for the joint activities of language access providers and their exclusive bargaining representative to the extent the activities are authorized by this chapter.

. By December 1, 2020, the department of social and health services, the department of children, youth, and families, the department of labor and industries, the health care authority, and the department of enterprise services must report to the legislature on the following:

.. Each agency's current process for procuring spoken language interpreters and whether the changes in chapter 253, Laws of 2018 have been implemented;

.. If chapter 253, Laws of 2018 has not been fully implemented by an agency, the barriers to implementation the agency has encountered and recommendations for removing the barriers to implementation;

.. The impacts of the changes to the bargaining units for language access providers in chapter 253, Laws of 2018; and

.. Recommendations on how to improve the procurement and accessibility of language access providers.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2691.SL.pdf?cite=2020%20c%20289%20§%202[2020 c 289 § 2]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6245-S2.SL.pdf?cite=2018%20c%20253%20§%208[2018 c 253 § 8]; 2018 c 253 § 7; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1661-S2.SL.pdf?cite=2017%203rd%20sp.s.%20c%206%20§%20809[2017 3rd sp.s. c 6 § 809]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6726-S.SL.pdf?cite=2010%20c%20296%20§%202[2010 c 296 § 2]; ]

== 41.56.513 - Application of chapter to certain postdoctoral and clinical university employees.
In addition to the entities listed in RCW 41.56.020, this chapter applies to postdoctoral and clinical employees as excluded in chapter 41.76 RCW at the University of Washington and at Washington State University.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6486-S.SL.pdf?cite=2012%20c%20255%20§%201[2012 c 255 § 1]; ]

== 41.56.515 - Fish and wildlife officers—Application of chapter.
. In addition to the entities listed in RCW 41.56.020, this chapter applies to the state with respect to fish and wildlife officers except the state may not negotiate any matters relating to retirement benefits or health care benefits or other employee insurance benefits.

. For the purposes of negotiating wages, wage-related matters, and nonwage matters, the state shall be represented by the governor or the governor's designee who is appointed under RCW 41.80.010, and costs of the negotiations under this section shall be reimbursed as provided in RCW 41.80.140.

. Fish and wildlife officers shall be excluded from the coalition bargaining for a master agreement of all exclusive bargaining representatives of fewer than five hundred employees under chapter 41.80 RCW.

. The governor or the governor's designee shall consult with the director of fish and wildlife regarding collective bargaining.

. The negotiation of provisions pertaining to wages and wage-related matters in a collective bargaining agreement between the state and the bargaining representatives of the fish and wildlife officers is subject to the following:

.. The state's bargaining representative must periodically consult with the committee of the joint committee on employment relations created in RCW 41.80.007 or any such successor committee for the joint committee on employment relations; and

.. Provisions that are entered into before the legislature approves the funds necessary to implement the provisions are conditioned upon the legislature's subsequent approval of the funds.

. The governor shall submit a request for funds necessary to implement the wage and wage-related matters in the collective bargaining agreement or for legislation necessary to implement the agreement. Requests for funds necessary to implement the provisions of bargaining agreements may not be submitted to the legislature by the governor unless such requests:

.. Have been submitted to the director of financial management by October 1st before the legislative session at which the requests are to be considered; and

.. Have been certified by the director of financial management as being feasible financially for the state or reflects the decision of an arbitration panel reached under RCW 41.56.475.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5481-S2.SL.pdf?cite=2020%20c%20298%20§%202[2020 c 298 § 2]; ]

== 41.56.516 - Fish and wildlife officers—Application of certain uniformed personnel provisions.
In addition to the classes of employees listed in RCW 41.56.030(14), the provisions of RCW 41.56.430, 41.56.440, 41.56.450, 41.56.452, 41.56.470, 41.56.480, and 41.56.490 also apply to fish and wildlife officers as provided in this section. If more than one exclusive bargaining unit represents uniformed personnel who are fish and wildlife officers, they may choose to enter into separate bargaining with the employer or agree to conduct bargaining with the employer as one coalition of all the exclusive bargaining representatives. If more than one bargaining unit chooses to advance to interest arbitration, it shall be conducted as coalition. However, one exclusive bargaining representative may singly choose to exercise its right to engage in interest arbitration even if other exclusive bargaining representatives who have chosen to enter into separate bargaining have elected not to take that step. Any exclusive bargaining representative of uniformed personnel who are fish and wildlife officers choosing interest arbitration is subject to the following:

. Within ten working days after the first Monday in September of every odd-numbered year, the state's bargaining representative and the bargaining representative for the appropriate bargaining unit(s) as a coalition, shall attempt to agree on an interest arbitration panel consisting of three members to be used if the parties are not successful in negotiating a comprehensive collective bargaining agreement. Each party shall name one person to serve as its arbitrator on the arbitration panel. The two members so appointed shall meet within seven days following the appointment of the later appointed member to attempt to choose a third member to act as the neutral chair of the arbitration panel. Upon the failure of the arbitrators to select a neutral chair within seven days, the two appointed members shall use one of the two following options in the appointment of the third member, who shall act as chair of the panel: (a) By mutual consent, the two appointed members may jointly request the commission to, and the commission shall, appoint a third member within two days of such a request. Costs of each party's appointee shall be borne by each party respectively; other costs of the arbitration proceedings shall be borne by the commission; or (b) either party may apply to the commission, the federal mediation and conciliation service, or the American arbitration association to provide a list of five qualified arbitrators from which the neutral chair shall be chosen. Each party shall pay the fees and expenses of its arbitrator, and the fees and expenses of the neutral chair shall be shared equally between the parties. Immediately upon selecting an interest arbitration panel, the parties shall cooperate to reserve dates with the arbitration panel for potential arbitration between August 1st and September 15th of the following even-numbered year. The parties shall also prepare a schedule of at least five negotiation dates for the following year, absent an agreement to the contrary. The parties shall execute a written agreement before November 1st of each odd-numbered year setting forth the names of the members of the arbitration panel and the dates reserved for bargaining and arbitration. This subsection imposes minimum obligations only and is not intended to define or limit a party's full, good faith bargaining obligation under other sections of this chapter.

. The mediator or arbitration panel may consider only matters that are subject to bargaining under RCW 41.80.020.

. The decision of an arbitration panel is not binding on the legislature and, if the legislature does not approve the funds necessary to implement provisions pertaining to wages and wage-related matters of an arbitrated collective bargaining agreement, is not binding on the state or the representatives of the department of fish and wildlife.

. In making its determination, the arbitration panel shall be mindful of the legislative purpose enumerated in RCW 41.56.430 and, as additional standards or guidelines to aid it in reaching a decision, shall take into consideration the following factors:

.. The constitutional and statutory authority of the employer;

.. Stipulations of the parties;

.. Comparison of the hours and conditions of employment of personnel involved in the proceedings with the hours and conditions of employment of like personnel of like employers of similar size in the state of Washington;

.. Changes in any of the foregoing circumstances during the pendency of the proceedings; and

.. Such other factors, not confined to the foregoing, which are normally or traditionally taken into consideration in the determination of matters that are subject to bargaining under RCW 41.56.473.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5481-S2.SL.pdf?cite=2020%20c%20298%20§%203[2020 c 298 § 3]; ]

== 41.56.900 - Short title—Effective date—1967 ex.s. c 108.
RCW 41.56.010 through 41.56.900 and 41.06.150 shall be known as the "Public Employees' Collective Bargaining Act" and shall take effect on July 1, 1967.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c108.pdf?cite=1967%20ex.s.%20c%20108%20§%2014[1967 ex.s. c 108 § 14]; ]

== 41.56.905 - Uniformed personnel—Provisions additional—Liberal construction.
The provisions of this chapter are intended to be additional to other remedies and shall be liberally construed to accomplish their purpose. Except as provided in RCW 53.18.015, if any provision of this chapter conflicts with any other statute, ordinance, rule or regulation of any public employer, the provisions of this chapter shall control.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c287.pdf?cite=1983%20c%20287%20§%205[1983 c 287 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c131.pdf?cite=1973%20c%20131%20§%2010[1973 c 131 § 10]; ]

== 41.56.906 - Construction of chapter—Certain agreements subject to RCW  28A.400.320.
Nothing in this chapter may be construed to grant school district employers or classified school district employees the right to reach agreements that are in conflict with the termination provisions of RCW 28A.400.320.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1741-S.SL.pdf?cite=2009%20c%20396%20§%2011[2009 c 396 § 11]; ]

== 41.56.907 - School district collective bargaining agreements not altered or impaired—Compliance with chapter—2017 3rd sp.s. c 13.
Nothing in chapter 13, Laws of 2017 3rd sp. sess. is intended to alter or impair school district collective bargaining agreements that are in effect on October 19, 2017. Any school district collective bargaining agreement executed or modified after October 19, 2017, must comply with chapter 13, Laws of 2017 3rd sp. sess.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2242.SL.pdf?cite=2017%203rd%20sp.s.%20c%2013%20§%20704[2017 3rd sp.s. c 13 § 704]; ]

== 41.56.913 - Conflict with federal requirements—2006 c 54.
If any part of this act is found to be in conflict with federal requirements that are a prescribed condition to the allocation of federal funds to the state, the conflicting part of this act is inoperative solely to the extent of the conflict and with respect to the agencies directly affected, and this finding does not affect the operation of the remainder of this act in its application to the agencies concerned. Rules adopted under this act must meet federal requirements that are a necessary condition to the receipt of federal funds by the state.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2353-S2.SL.pdf?cite=2006%20c%2054%20§%2011[2006 c 54 § 11]; ]

== 41.56.914 - Short title—2006 c 54.
This act may be known and cited as the access to quality family child care act.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2353-S2.SL.pdf?cite=2006%20c%2054%20§%2012[2006 c 54 § 12]; ]

== 41.56.915 - Effective date—2006 c 54.
Sections 1 through 5 of this act are necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and take effect immediately [March 15, 2006].

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2353-S2.SL.pdf?cite=2006%20c%2054%20§%2013[2006 c 54 § 13]; ]

== 41.56.950 - Retroactive date in collective bargaining agreements allowable, when.
Whenever a collective bargaining agreement between a public employer and a bargaining representative is concluded after the termination date of the previous collective bargaining agreement between the same parties, the effective date of such collective bargaining agreement may be the day after the termination date of the previous collective bargaining agreement and all benefits included in the new collective bargaining agreement including wage increases may accrue beginning with such effective date as established by this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c187.pdf?cite=1971%20ex.s.%20c%20187%20§%201[1971 ex.s. c 187 § 1]; ]

