= 41.68 - Reparations to state employees terminated during World War II.
:toc:

== 41.68.010 - Legislative finding.
The dismissal or termination of various state employees during World War II resulted from the promulgation of federal Executive Order 9066 which was based mainly on fear and suspicion rather than on factual justification. It is fair and just that reparations be made to those employees who were terminated from state employment during the wartime years because of these circumstances. The legislature therefore finds that equity and fairness will be served by authorizing the filing of claims with the state for salary losses suffered by the state employees directly affected, and by authorizing the payment thereof, subject to the provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c15.pdf?cite=1983%201st%20ex.s.%20c%2015%20§%201[1983 1st ex.s. c 15 § 1]; ]

== 41.68.020 - Eligibility for reparation.
Any state employee or the living surviving spouse of a state employee who, due to the promulgation of federal Executive Order 9066, was dismissed, terminated from a temporary position, or rejected during the person's probationary period, or who voluntarily resigned in lieu of dismissal from state government employment, and who incurred salary losses as a result thereof, is eligible to file a claim with the state for the reparation of those losses.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c15.pdf?cite=1983%201st%20ex.s.%20c%2015%20§%202[1983 1st ex.s. c 15 § 2]; ]

== 41.68.030 - Submittal of claim.
A claim under this chapter may be submitted to the department of enterprise services for the reparation of salary losses suffered during the years 1942 through 1947. The claim shall be supported by appropriate verification, such as the person's name at the time of the dismissal, the name of the employing department, and a social security number, or by evidence of official action of termination. The claimant shall also provide an address to which the department shall mail notification of its determination regarding the claimant's eligibility.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5931-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2043%20§%20474[2011 1st sp.s. c 43 § 474]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c15.pdf?cite=1983%201st%20ex.s.%20c%2015%20§%203[1983 1st ex.s. c 15 § 3]; ]

== 41.68.040 - Determination of eligibility.
. The department of enterprise services shall determine the eligibility of a claimant to receive reparations authorized by this chapter. The department shall then notify the claimant by mail of its determination regarding the claimant's eligibility.

. The department may adopt rules that will assist in the fair determination of eligibility and the processing of claims. The department, however, has no obligation to directly notify any person of possible eligibility for reparation of salary losses under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5931-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2043%20§%20475[2011 1st sp.s. c 43 § 475]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c15.pdf?cite=1983%201st%20ex.s.%20c%2015%20§%204[1983 1st ex.s. c 15 § 4]; ]

== 41.68.050 - Payment of reparation.
A claimant under this chapter who is determined eligible by the department of enterprise services shall receive two thousand five hundred dollars each year for two years. All claims which the department determines are eligible for reparation shall be immediately forwarded to the state treasurer, who shall issue warrants in the appropriate amounts upon demand and verification of identity. If a claimant dies after filing a claim but before receiving full payment, payments shall be made to the claimant's estate upon demand and verification of identity.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5931-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2043%20§%20476[2011 1st sp.s. c 43 § 476]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c15.pdf?cite=1983%201st%20ex.s.%20c%2015%20§%205[1983 1st ex.s. c 15 § 5]; ]

== 41.68.900 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%20103[2009 c 521 § 103]; ]

