= 41.72 - Law enforcement medal of honor.
:toc:

== 41.72.010 - Law enforcement medal of honor established.
There is established a decoration of the state law enforcement medal of honor with accompanying ribbons and appurtenances for award by the governor in the name of the state to any law enforcement officer who has been seriously injured or killed while in the performance of duty, or who has been distinguished by exceptionally meritorious conduct, upon nomination of the governor's state law enforcement medal of honor committee.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2419.SL.pdf?cite=1994%20c%2089%20§%201[1994 c 89 § 1]; ]

== 41.72.020 - Law enforcement medal of honor committee established—Membership—Establishment of qualifications for award.
There is created the state law enforcement medal of honor committee for nominating candidates for the award of the state law enforcement medal of honor. The committee membership consists of a representative from the governor's office, the Washington state law enforcement association, the Washington state council of police officers, the Washington association of sheriffs and police chiefs, and the Washington state troopers association. The attorney general shall serve as chair of the committee and shall designate a secretary for the committee. The committee shall meet not less than semiannually to consider candidates for nomination. The committee shall adopt rules establishing the qualifications for the state law enforcement medal of honor, the protocol governing the decoration, and the appurtenances necessary to the implementation of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2419.SL.pdf?cite=1994%20c%2089%20§%202[1994 c 89 § 2]; ]

== 41.72.030 - Law enforcement medal of honor awarded—When.
The state law enforcement medal of honor shall be awarded to recipients during the national law enforcement recognition week. The governor may delegate the awarding of the medal to the lieutenant governor or the attorney general.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2419.SL.pdf?cite=1994%20c%2089%20§%203[1994 c 89 § 3]; ]

== 41.72.040 - Law enforcement medal of honor may be awarded posthumously.
The state law enforcement medal of honor may be awarded posthumously to be presented to the representative of the deceased as may be deemed appropriate by the governor or the designees specified in RCW 41.72.030.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2419.SL.pdf?cite=1994%20c%2089%20§%204[1994 c 89 § 4]; ]

== 41.72.050 - Law enforcement medal of honor—Design.
The decoration of the state law enforcement medal of honor shall be bronze and shall consist of a police shield overlaid by a sheriff's star with the seal of the state of Washington in the center and the words "law enforcement medal of honor" within the design and suspended from a ring attached by either a navy blue ribbon with a gold edge or a green ribbon with a gold edge. Such color choice shall be the recipient's. The reverse of the decoration shall be inscribed with the words "For exceptionally honorable and meritorious conduct in performing services as a law enforcement officer."

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2419.SL.pdf?cite=1994%20c%2089%20§%205[1994 c 89 § 5]; ]

