= 9.05 - Sabotage.
:toc:

== 9.05.030 - Assemblages of saboteurs.
Whenever two or more persons assemble for the purpose of committing criminal sabotage, as defined in RCW 9.05.060, such an assembly is unlawful, and every person voluntarily and knowingly participating therein by his or her presence, aid, or instigation, is guilty of a class B felony and shall be punished by imprisonment in a state correctional facility for not more than ten years, or by a fine of not more than five thousand dollars, or both.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%206[2003 c 53 § 6]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5671-S.SL.pdf?cite=1999%20c%20191%20§%201[1999 c 191 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2263-S.SL.pdf?cite=1992%20c%207%20§%202[1992 c 7 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20314[1909 c 249 § 314]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c45.pdf?cite=1903%20c%2045%20§%204[1903 c 45 § 4]; RRS § 2566; ]

== 9.05.060 - Criminal sabotage defined—Penalty.
. Whoever, with intent that his or her act shall, or with reason to believe that it may, injure, interfere with, interrupt, supplant, nullify, impair, or obstruct the owner's or operator's management, operation, or control of any agricultural, stockraising, lumbering, mining, quarrying, fishing, manufacturing, transportation, mercantile, or building enterprise, or any other public or private business or commercial enterprise, wherein any person is employed for wage, shall willfully damage or destroy, or attempt or threaten to damage or destroy, any property whatsoever, or shall unlawfully take or retain, or attempt or threaten unlawfully to take or retain, possession or control of any property, instrumentality, machine, mechanism, or appliance used in such business or enterprise, shall be guilty of criminal sabotage.

. Criminal sabotage is a class B felony punishable according to chapter 9A.20 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%207[2003 c 53 § 7]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5671-S.SL.pdf?cite=1999%20c%20191%20§%202[1999 c 191 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c173.pdf?cite=1919%20c%20173%20§%201[1919 c 173 § 1]; RRS § 2563-3; ]

== 9.05.090 - Provisions cumulative.
RCW 9.05.030 and 9.05.060 shall not be construed to repeal or amend any existing penal statute.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5671-S.SL.pdf?cite=1999%20c%20191%20§%203[1999 c 191 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c173.pdf?cite=1919%20c%20173%20§%204[1919 c 173 § 4]; RRS § 2563-6; ]

