= 9.01 - General provisions.
:toc:

== 9.01.055 - Citizen immunity if aiding officer, scope—When.
Private citizens aiding a police officer, or other officers of the law in the performance of their duties as police officers or officers of the law, shall have the same civil and criminal immunity as such officer, as a result of any act or commission for aiding or attempting to aid a police officer or other officer of the law, when such officer is in imminent danger of loss of life or grave bodily injury or when such officer requests such assistance and when such action was taken under emergency conditions and in good faith.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c37.pdf?cite=1969%20c%2037%20§%201[1969 c 37 § 1]; ]

== 9.01.110 - Omission, when not punishable.
No person shall be punished for an omission to perform an act when such act has been performed by another acting in his or her behalf, and competent to perform it.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20285[2011 c 336 § 285]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%2023[1909 c 249 § 23]; RRS § 2275; ]

== 9.01.120 - Civil remedies preserved.
The omission to specify or affirm in this act any liability to any damages, penalty, forfeiture or other remedy, imposed by law, and allowed to be recovered or enforced in any civil action or proceeding, for any act or omission declared punishable herein, shall not affect any right to recover or enforce the same.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%2044[1909 c 249 § 44]; RRS § 2296; ]

== 9.01.130 - Sending letter, when complete.
Whenever any statute makes the sending of a letter criminal, the offense shall be deemed complete from the time it is deposited in any post office or other place, or delivered to any person, with intent that it shall be forwarded; and the sender may be proceeded against in the county wherein it was so deposited or delivered, or in which it was received by the person to whom it was addressed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%2022[1909 c 249 § 22]; RRS § 2274; ]

== 9.01.160 - Application to existing civil rights.
Nothing in this act shall be deemed to affect any civil right or remedy existing at the time when it shall take effect, by virtue of the common law or of the provision of any statute.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%2043[1909 c 249 § 43]; RRS § 2295; ]

== 9.01.210 - Financial, accounting services to marijuana industry.
. A person or entity that receives deposits, extends credit, conducts funds transfers, transports cash or financial instruments on behalf of a financial institution, or provides other financial services for a marijuana producer, marijuana processor, or marijuana retailer authorized under chapter 69.50 RCW or for a qualifying patient, health care professional, or designated provider authorized under chapter 69.51A RCW, does not commit a crime under any Washington law solely by virtue of receiving deposits, extending credit, conducting funds transfers, transporting cash or other financial instruments, or providing other financial services for the person.

. For the purposes of this section, "person or entity" means a financial institution as defined in RCW 30A.22.040, an armored car service operating under a permit issued by the utilities and transportation commission that has been contracted by a financial institution, or a person providing financial services pursuant to a license issued under chapter 18.44, 19.230, or 31.04 RCW.

. A certified public accountant or certified public accounting firm, which practices public accounting as defined in RCW 18.04.025, does not commit a crime solely for providing professional accounting services as specified in RCW 18.04.025 for a marijuana producer, marijuana processor, or marijuana retailer authorized under chapter 69.50 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5928-S.SL.pdf?cite=2018%20c%2068%20§%201[2018 c 68 § 1]; ]

