= 9.03 - Abandoned refrigeration equipment.
:toc:

== 9.03.010 - Abandoning, discarding refrigeration equipment.
Any person who discards or abandons or leaves in any place accessible to children any refrigerator, icebox, or deep freeze locker having a capacity of one and one-half cubic feet or more, which is no longer in use, and which has not had the door removed or a portion of the latch mechanism removed to prevent latching or locking of the door, is guilty of a misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c298.pdf?cite=1955%20c%20298%20§%201[1955 c 298 § 1]; ]

== 9.03.020 - Permitting unused equipment to remain on premises.
Any owner, lessee, or manager who knowingly permits such an unused refrigerator, icebox, or deep freeze locker to remain on the premises under his or her control without having the door removed or a portion of the latch mechanism removed to prevent latching or locking of the door is guilty of a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20286[2011 c 336 § 286]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c298.pdf?cite=1955%20c%20298%20§%202[1955 c 298 § 2]; ]

== 9.03.030 - Violation of RCW  9.03.010 or  9.03.020.
Guilt of a violation of RCW 9.03.010 or 9.03.020 shall not, in itself, render one guilty of manslaughter, battery, or other crime against a person who may suffer death or injury from entrapment in such refrigerator, icebox, or deep freeze locker.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c298.pdf?cite=1955%20c%20298%20§%203[1955 c 298 § 3]; ]

== 9.03.040 - Keeping or storing equipment for sale.
Any person who keeps or stores refrigerators, iceboxes, or deep freeze lockers for the purpose of selling or offering them for sale shall not be guilty of a violation of this chapter if he or she takes reasonable precautions to effectively secure the door of any refrigerator, icebox, or deep freeze locker held for purpose of sale so as to prevent entrance of children small enough to fit into such articles.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20287[2011 c 336 § 287]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c298.pdf?cite=1955%20c%20298%20§%204[1955 c 298 § 4]; ]

