= 9.16 - Brands and marks, crimes relating to.
:toc:

== 9.16.005 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Counterfeit mark" means:

.. Any unauthorized reproduction or copy of intellectual property; or

.. Intellectual property affixed to any item knowingly sold, offered for sale, manufactured, or distributed, or identifying services offered or rendered, without the authority of the owner of the intellectual property.

. "Intellectual property" means any trademark, service mark, trade name, label, term, device, design, or work adopted or used by a person to identify such person's goods or services. Intellectual property does not have exclusive use rights to trade names registered under chapter 19.80 RCW.

. "Retail value" means the counterfeiter's regular selling price for the item or service bearing or identified by the counterfeit mark. In the case of items bearing a counterfeit mark which are components of a finished product, the retail value shall be the counterfeiter's regular selling price of the finished product on or in which the component would be utilized.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1007.SL.pdf?cite=1999%20c%20322%20§%201[1999 c 322 § 1]; ]

== 9.16.010 - Removing lawful brands.
Every person who shall willfully deface, obliterate, remove, or alter any mark or brand placed by or with the authority of the owner thereof on any shingle bolt, log or stick of timber, or on any horse, mare, gelding, mule, cow, steer, bull, sheep, goat or hog, shall be punished by imprisonment in a state correctional facility for not more than five years, or by imprisonment in the county jail for up to three hundred sixty-four days, or by a fine of not more than one thousand dollars, or by both fine and imprisonment.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5168-S.SL.pdf?cite=2011%20c%2096%20§%204[2011 c 96 § 4]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2263-S.SL.pdf?cite=1992%20c%207%20§%203[1992 c 7 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20342[1909 c 249 § 342]; Code 1881 § 839; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20191%20§%2054[1873 p 191 § 54]; RRS § 2594; ]

== 9.16.020 - Imitating lawful brand.
Every person who, in any county, places upon any property, any brand or mark in the likeness or similitude of another brand or mark filed with the county auditor of such county by the owner thereof as a brand or mark for the designation or identification of a like kind of property, is:

. If done with intent to confuse or commingle such property with, or to appropriate to his or her own use, the property of such other owner, guilty of a felony, punishable by imprisonment in a state correctional facility for not more than five years, or by imprisonment in the county jail for up to three hundred sixty-four days, or by a fine of not more than one thousand dollars, or by both fine and imprisonment; or

. If done without such intent, guilty of a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5168-S.SL.pdf?cite=2011%20c%2096%20§%205[2011 c 96 § 5]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2263-S.SL.pdf?cite=1992%20c%207%20§%204[1992 c 7 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20343[1909 c 249 § 343]; RRS § 2595; ]

== 9.16.030 - Counterfeit mark—Intellectual property.
Any person who willfully and knowingly, and for financial gain, manufactures, uses, displays, advertises, distributes, offers for sale, sells or possesses with intent to sell or distribute any item, or offers any services, bearing or identified by a counterfeit mark, is guilty of the crime of counterfeiting.

Any state or federal certificate of registration of any intellectual property is prima facie evidence of the facts stated in the certificate.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1007.SL.pdf?cite=1999%20c%20322%20§%202[1999 c 322 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20344[1909 c 249 § 344]; Code 1881 § 854; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1873%20p%20194%20§%2063[1873 p 194 § 63]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%2085%20§%2087[1854 p 85 § 87]; RRS § 2596; ]

== 9.16.035 - Counterfeiting—Penalties.
. Counterfeiting is a misdemeanor, except as provided in subsections (2), (3) and (4) of this section.

. Counterfeiting is a gross misdemeanor if:

.. The defendant has previously been convicted under RCW 9.16.030; or

.. The violation involves more than one hundred but fewer than one thousand items bearing a counterfeit mark or the total retail value of all items bearing a counterfeit mark or the total retail value of all items bearing, or services identified by, a counterfeit mark is more than one thousand dollars but less than ten thousand dollars.

. Counterfeiting is a class C felony if:

.. The defendant has been previously convicted of two or more offenses under RCW 9.16.030;

.. The violation involves the manufacture or production of items bearing counterfeit marks; or

.. The violation involves one thousand or more items bearing a counterfeit mark or the total retail value of all items bearing, or services identified by, a counterfeit mark is ten thousand dollars or more.

. Counterfeiting is a class C felony if:

.. The violation involves the manufacture, production, or distribution of items bearing counterfeit marks; and

.. The defendant knew or should have known that the counterfeit items, by their intended use, endangered the health or safety of others.

. For purposes of this section, the quantity or retail value of items or services shall include the aggregate quantity or retail value of all items bearing, or services identified by, every counterfeit mark the defendant manufactures, uses, displays, advertises, distributes, possesses, or possesses with intent to sell.

. A person guilty of counterfeiting shall be fined an amount up to three times the retail value of the items bearing, or services identified by, a counterfeit mark, unless extenuating circumstances are shown by the defendant.

. The penalties provided for in this section are cumulative and do not affect any other civil and criminal penalties provided by law.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1007.SL.pdf?cite=1999%20c%20322%20§%203[1999 c 322 § 3]; ]

== 9.16.041 - Counterfeit items—Seizure and forfeiture.
. Any items bearing a counterfeit mark, and all personal property employed or used in connection with counterfeiting, including but not limited to, any items, objects, tools, machines, equipment, instruments, or vehicles of any kind, shall be seized by any law enforcement officer.

All seized personal property referenced in this subsection shall be forfeited in accordance with RCW 10.105.010.

. Upon request of the intellectual property owner, all seized items bearing a counterfeit mark shall be released to the intellectual property owner for destruction or disposition.

. If the intellectual property owner does not request release of seized items bearing a counterfeit mark, such items shall be destroyed unless the intellectual property owner consents to another disposition.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1007.SL.pdf?cite=1999%20c%20322%20§%204[1999 c 322 § 4]; ]

== 9.16.050 - When deemed affixed.
A label, trademark, term, design, device or form of advertisement shall be deemed to be affixed to any goods, wares, merchandise, mixture, preparation or compound whenever it is in any manner placed in or upon either the article itself, or the box, bale, barrel, bottle, case, cask or other vessel or package, or the cover, wrapper, stopper, brand, label or other thing in, by or with which the goods are packed, enclosed or otherwise prepared for sale or distribution.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20346[1909 c 249 § 346]; RRS § 2598; ]

== 9.16.060 - Fraudulent registration of trademark.
Every person who shall for himself or herself, or on behalf of any other person, corporation, association, or union, procure the filing of any label, trademark, term, design, device, or form of advertisement, with the secretary of state by any fraudulent means, shall be guilty of a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20289[2011 c 336 § 289]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20347[1909 c 249 § 347]; RRS § 2599; ]

== 9.16.070 - Form and similitude defined.
A plate, label, trademark, term, design, device or form of advertisement is in the form and similitude of the genuine instrument imitated if the finished parts of the engraving thereupon shall resemble or conform to the similar parts of the genuine instrument.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20348[1909 c 249 § 348]; RRS § 2600; ]

== 9.16.080 - Petroleum products improperly labeled or graded—Penalty.
. It shall be unlawful for any person, firm, or corporation:

.. To use, adopt, place upon, or permit to be used, adopted or placed upon, any barrel, tank, drum or other container of gasoline or lubricating oil for internal combustion engines, sold or offered for sale, or upon any pump or other device used in delivering the same, any trade name, trademark, designation or other descriptive matter, which is not the true and correct trade name, trademark, designation or other descriptive matter of the gasoline or lubricating oil so sold or offered for sale;

.. To sell, or offer for sale, or have in his or her or its possession with intent to sell, any gasoline or lubricating oil, contained in, or taken from, or through any barrel, tank, drum, or other container or pump or other device, so unlawfully labeled or marked, as hereinabove provided;

.. To sell, or offer for sale, or have in his or her or its possession with intent to sell any gasoline or lubricating oil for internal combustion engines and to represent to the purchaser, or prospective purchaser, that such gasoline or lubricating oil so sold or offered for sale, is of a quality, grade or standard, or the product of a particular gasoline or lubricating oil manufacturing, refining or distributing company or association, other than the true quality, grade, standard, or the product of a particular gasoline or oil manufacturing, refining or distributing company or association, of the gasoline or oil so offered for sale or sold.

. [Empty]
.. Except as provided in (b) of this subsection, any person, firm, or corporation violating this section is guilty of a misdemeanor.

.. A second and each subsequent violation of this section is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%2014[2003 c 53 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c222.pdf?cite=1927%20c%20222%20§%201[1927 c 222 § 1]; RRS § 2637-1; ]

== 9.16.100 - Use of the words "sterling silver," etc.
Every person who shall make, sell or offer to sell or dispose of, or have in his or her possession with intent to sell or dispose of any metal article marked, stamped or branded with the words "sterling," "sterling silver," or "solid silver," unless nine hundred twenty-five one-thousandths of the component parts of the metal of which such article and all parts thereof is manufactured is pure silver, shall be guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20290[2011 c 336 § 290]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20428[1909 c 249 § 428]; RRS § 2680; ]

== 9.16.110 - Use of words "coin silver," etc.
Every person who shall make, sell or offer to sell or dispose of, or have in his or her possession with intent to dispose of any metal article marked, stamped or branded with the words "coin," or "coin silver," unless nine hundred one-thousandths of the component parts of the metal of which such article and all parts thereof is manufactured, is pure silver, shall be guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20291[2011 c 336 § 291]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20429[1909 c 249 § 429]; RRS § 2681; ]

== 9.16.120 - Use of the word "sterling" on mounting.
Every person who shall make, sell, offer to sell or dispose of, or have in his or her possession with intent to sell or dispose of, any article comprised of leather, shell, ivory, celluloid, pearl, glass, porcelain, pottery, steel or wood, to which is applied or attached a metal mounting marked, stamped or branded with the words "sterling," or "sterling silver," unless nine hundred twenty-five one-thousandths of the component parts of the metal of which such metal mounting is manufactured is pure silver, shall be guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20292[2011 c 336 § 292]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20430[1909 c 249 § 430]; RRS § 2682; ]

== 9.16.130 - Use of the words "coin silver" on mounting.
Every person who shall make, sell, offer to sell or dispose of, or have in his or her possession with intent to sell or dispose of, any article comprised of leather, shell, ivory, celluloid, pearl, glass, porcelain, pottery, steel or wood, to which is applied or attached a metal mounting marked, stamped or branded with the words "coin" or "coin silver," unless nine hundred one-thousandths of the component parts of the metal of which such metal mounting is manufactured is pure silver, shall be guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20293[2011 c 336 § 293]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20431[1909 c 249 § 431]; RRS § 2683; ]

== 9.16.140 - Unlawfully marking article made of gold.
Every person who shall make, sell, offer to sell or dispose of, or have in his or her possession with intent to sell or dispose of, any article constructed wholly or in part of gold, or of an alloy of gold, and marked, stamped or branded in such manner as to indicate that the gold or alloy of gold in such article is of a greater degree or carat of fineness, by more than one carat, than the actual carat or fineness of such gold or alloy of gold, shall be guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20294[2011 c 336 § 294]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20432[1909 c 249 § 432]; RRS § 2684; ]

== 9.16.150 - "Marked, stamped or branded" defined.
An article shall be deemed to be "marked, stamped or branded" whenever such article, or any box, package, cover or wrapper in which the same is enclosed, encased or prepared for sale or delivery, or any card, label or placard with which the same may be exhibited or displayed, is so marked, stamped or branded.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20433[1909 c 249 § 433]; RRS § 2685; ]

