= 9.38 - False representations.
:toc:

== 9.38.010 - False representation concerning credit.
Every person who, with intent thereby to obtain credit or financial rating, shall willfully make any false statement in writing of his or her assets or liabilities to any person with whom he or she may be either actually or prospectively engaged in any business transaction or to any commercial agency or other person engaged in the business of collecting or disseminating information concerning financial or commercial ratings, shall be guilty of a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20296[2011 c 336 § 296]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20368[1909 c 249 § 368]; RRS § 2620; ]

== 9.38.015 - False statement by deposit account applicant.
. It is a gross misdemeanor for a deposit account applicant to knowingly make any false statement to a financial institution regarding:

.. The applicant's identity;

.. Past convictions for crimes involving fraud or deception; or

.. Outstanding judgments on checks or drafts issued by the applicant.

. Each violation of subsection (1) of this section after the third violation is a class C felony punishable as provided in chapter 9A.20 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1603.SL.pdf?cite=1995%20c%20186%20§%204[1995 c 186 § 4]; ]

== 9.38.020 - False representation concerning title.
Every person who shall maliciously or fraudulently execute or file for record any instrument, or put forward any claim, by which the right or title of another to any real or personal property is, or purports to be transferred, encumbered or clouded, shall be guilty of a gross misdemeanor.

[ 2000 c 250 § 9A-821; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20369[1909 c 249 § 369]; RRS § 2621; ]

== 9.38.060 - Digital signature violations.
. A person shall not knowingly misrepresent the person's identity or authorization to obtain a public key certificate used to reference a private key for creating a digital signature.

. A person shall not knowingly forge an electronic or digital signature.

. A person shall not knowingly present a public key certificate for which the person is not the owner of the corresponding private key in order to obtain unauthorized access to information or engage in an unauthorized transaction.

. A person who violates this section is guilty of a class C felony punishable under chapter 9A.20 RCW.

. [Empty]
.. "Digital signature" means an electronic signature that is a transformation of a message using an asymmetric cryptosystem such that a person who has the initial message and the signer's public key can accurately determine whether the:

... Transformation was created using the private key that corresponds to the signer's public key; and

... Initial message has been altered since the transformation was made.

.. "Electronic signature" has the meaning provided in RCW 1.80.010.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6028-S.SL.pdf?cite=2020%20c%2057%20§%2024[2020 c 57 § 24]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1908.SL.pdf?cite=2019%20c%20132%20§%201[2019 c 132 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1632-S.SL.pdf?cite=2001%20c%2039%20§%201[2001 c 39 § 1]; ]

