= 9.35 - Identity crimes.
:toc:

== 9.35.001 - Findings—Intent.
. The legislature finds that means of identification and financial information are personal and sensitive information such that if unlawfully obtained, possessed, used, or transferred by others may result in significant harm to a person's privacy, financial security, and other interests. The legislature finds that unscrupulous persons find ever more clever ways, including identity theft, to improperly obtain, possess, use, and transfer another person's means of identification or financial information. The legislature intends to penalize for each unlawful act of improperly obtaining, possessing, using, or transferring means of identification or financial information of an individual person. The unit of prosecution for identity theft by use of a means of identification or financial information is each individual unlawful use of any one person's means of identification or financial information. Unlawfully obtaining, possessing, or transferring each means of identification or financial information of any individual person, with the requisite intent, is a separate unit of prosecution for each victim and for each act of obtaining, possessing, or transferring of the individual person's means of identification or financial information.

. The people find that additional measures are needed to protect seniors and vulnerable individuals from identity theft because such individuals often have less ability to protect themselves and such individuals can be targeted using information available through public sources, including publicly available information that identifies such individuals or their in-home caregivers.

[ 2017 c 4 § 4 (Initiative Measure No. 1501, approved November 8, 2016); http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5878.SL.pdf?cite=2008%20c%20207%20§%203[2008 c 207 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1250-S.SL.pdf?cite=1999%20c%20368%20§%201[1999 c 368 § 1]; ]

== 9.35.005 - Definitions. (Effective until January 1, 2022.)
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Financial information" means any of the following information identifiable to the individual that concerns the amount and conditions of an individual's assets, liabilities, or credit:

.. Account numbers and balances;

.. Transactional information concerning an account; and

.. Codes, passwords, social security numbers, tax identification numbers, driver's license or permit numbers, state identicard numbers issued by the department of licensing, and other information held for the purpose of account access or transaction initiation.

. "Financial information repository" means a person engaged in the business of providing services to customers who have a credit, deposit, trust, stock, or other financial account or relationship with the person.

. "Means of identification" means information or an item that is not describing finances or credit but is personal to or identifiable with an individual or other person, including: A current or former name of the person, telephone number, an electronic address, or identifier of the individual or a member of his or her family, including the ancestor of the person; information relating to a change in name, address, telephone number, or electronic address or identifier of the individual or his or her family; a social security, driver's license, or tax identification number of the individual or a member of his or her family; and other information that could be used to identify the person, including unique biometric data.

. "Person" means a person as defined in RCW 9A.04.110.

. "Senior" means a person over the age of sixty-five.

. "Victim" means a person whose means of identification or financial information has been used or transferred with the intent to commit, or to aid or abet, any unlawful activity.

. "Vulnerable individual" means a person:

... [(a)] Sixty years of age or older who has the functional, mental, or physical inability to care for himself or herself;

... [(b)] Found incapacitated under *chapter 11.88 RCW;

... [(c)] Who has a developmental disability as defined under RCW 71A.10.020;

... [(d)] Admitted to any facility;

.. [(e)] Receiving services from home health, hospice, or home care agencies licensed or required to be licensed under chapter 70.127 RCW;

.. [(f)] Receiving services from an individual provider as defined in RCW 74.39A.240; or

.. [(g)] Who self-directs his or her own care and receives services from a personal aide under chapter 74.39 RCW.

[ 2017 c 4 § 3 (Initiative Measure No. 1501, approved November 8, 2016); http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5449-S.SL.pdf?cite=2001%20c%20217%20§%201[2001 c 217 § 1]; ]

== 9.35.010 - Improperly obtaining financial information.
. No person may obtain or attempt to obtain, or cause to be disclosed or attempt to cause to be disclosed to any person, financial information from a financial information repository, financial services provider, merchant, corporation, trust, partnership, or unincorporated association:

.. By knowingly making a false, fictitious, or fraudulent statement or representation to an officer, employee, or agent of a financial information repository with the intent to deceive the officer, employee, or agent into relying on that statement or representation for purposes of releasing the financial information;

.. By knowingly making a false, fictitious, or fraudulent statement or representation to a customer of a financial information repository, financial services provider, merchant, corporation, trust, partnership, or unincorporated association with the intent to deceive the customer into releasing financial information or authorizing the release of such information;

.. By knowingly providing any document to an officer, employee, or agent of a financial information repository, financial services provider, merchant, corporation, trust, partnership, or unincorporated association, knowing that the document is forged, counterfeit, lost, or stolen; was fraudulently obtained; or contains a false, fictitious, or fraudulent statement or representation, if the document is provided with the intent to deceive the officer, employee, or agent to release the financial information.

. No person may request another person to obtain financial information from a financial information repository, financial services provider, merchant, corporation, trust, partnership, or unincorporated association and knows or should have known that the person will obtain or attempt to obtain the information from the financial institution repository, financial services provider, merchant, corporation, trust, partnership, or unincorporated association in any manner described in subsection (1) of this section.

. No provision of this section shall be construed so as to prevent any action by a law enforcement agency, or any officer, employee, or agent of such agency, or any action of an agent of the financial information repository, financial services provider, merchant, corporation, trust, partnership, or unincorporated association when working in conjunction with a law enforcement agency.

. This section does not apply to:

.. Efforts by the financial information repository to test security procedures or systems of the financial institution repository for maintaining the confidentiality of customer information;

.. Investigation of alleged employee misconduct or negligence; or

.. Efforts to recover financial or personal information of the financial institution obtained or received by another person in any manner described in subsection (1) or (2) of this section.

. Violation of this section is a class C felony.

. A person who violates this section is liable for five hundred dollars or actual damages, whichever is greater, and reasonable attorneys' fees.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5449-S.SL.pdf?cite=2001%20c%20217%20§%208[2001 c 217 § 8]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1250-S.SL.pdf?cite=1999%20c%20368%20§%202[1999 c 368 § 2]; ]

== 9.35.020 - Identity theft.
. No person may knowingly obtain, possess, use, or transfer a means of identification or financial information of another person, living or dead, with the intent to commit, or to aid or abet, any crime.

. Violation of this section when the accused or an accomplice violates subsection (1) of this section and obtains credit, money, goods, services, or anything else of value in excess of one thousand five hundred dollars in value, or when the accused knowingly targets a senior or vulnerable individual in carrying out a violation of subsection (1) of this section, shall constitute identity theft in the first degree. Identity theft in the first degree is a class B felony punishable according to chapter 9A.20 RCW.

. A person is guilty of identity theft in the second degree when he or she violates subsection (1) of this section under circumstances not amounting to identity theft in the first degree. Identity theft in the second degree is a class C felony punishable according to chapter 9A.20 RCW.

. Each crime prosecuted under this section shall be punished separately under chapter 9.94A RCW, unless it is the same criminal conduct as any other crime, under RCW 9.94A.589.

. Whenever any series of transactions involving a single person's means of identification or financial information which constitute identity theft would, when considered separately, constitute identity theft in the second degree because of value, and the series of transactions are a part of a common scheme or plan, then the transactions may be aggregated in one count and the sum of the value of all of the transactions shall be the value considered in determining the degree of identity theft involved.

. Every person who, in the commission of identity theft, shall commit any other crime may be punished therefor as well as for the identity theft, and may be prosecuted for each crime separately.

. A person who violates this section is liable for civil damages of one thousand dollars or actual damages, whichever is greater, including costs to repair the victim's credit record, and reasonable attorneys' fees as determined by the court.

. In a proceeding under this section, the crime will be considered to have been committed in any locality where the person whose means of identification or financial information was appropriated resides, or in which any part of the offense took place, regardless of whether the defendant was ever actually in that locality.

. The provisions of this section do not apply to any person who obtains another person's driver's license or other form of identification for the sole purpose of misrepresenting his or her age.

. In a proceeding under this section in which a person's means of identification or financial information was used without that person's authorization, and when there has been a conviction, the sentencing court may issue such orders as are necessary to correct a public record that contains false information resulting from a violation of this section.

[ 2017 c 4 § 5 (Initiative Measure No. 1501, approved November 8, 2016); http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5878.SL.pdf?cite=2008%20c%20207%20§%204[2008 c 207 § 4]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5412-S3.SL.pdf?cite=2004%20c%20273%20§%202[2004 c 273 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%2022[2003 c 53 § 22]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5449-S.SL.pdf?cite=2001%20c%20217%20§%209[2001 c 217 § 9]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1250-S.SL.pdf?cite=1999%20c%20368%20§%203[1999 c 368 § 3]; ]

== 9.35.030 - Soliciting undesired mail.
. It is unlawful for any person to knowingly use a means of identification or financial information of another person to solicit undesired mail with the intent to annoy, harass, intimidate, torment, or embarrass that person.

. Violation of this section is a misdemeanor.

. Additionally, a person who violates this section is liable for civil damages of five hundred dollars or actual damages, including costs to repair the person's credit record, whichever is greater, and reasonable attorneys' fees as determined by the court.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5449-S.SL.pdf?cite=2001%20c%20217%20§%2010[2001 c 217 § 10]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6459-S.SL.pdf?cite=2000%20c%2077%20§%201[2000 c 77 § 1]; ]

== 9.35.040 - Information available to victim.
. A person, financial information repository, financial service provider, merchant, corporation, trust, partnership, or unincorporated association possessing information relating to an actual or potential violation of this chapter, and who may have entered into a transaction, provided credit, products, goods, or services, accepted payment, or otherwise done business with a person who has used the victim's means of identification, must, upon written request of the victim, provide copies of all relevant application and transaction information related to the transaction being alleged as a potential or actual violation of this chapter. Nothing in this section requires the information provider to disclose information that it is otherwise prohibited from disclosing by law, except that a law that prohibits disclosing a person's information to third parties shall not be used to deny disclosure of such information to the victim under this section.

. Unless the information provider is otherwise willing to verify the victim's identification, the victim shall provide the following as proof of positive identification:

.. The showing of a government-issued photo identification card or, if providing proof by mail, a copy of a government-issued photo identification card;

.. A copy of a filed police report evidencing the victim's claim; and

.. A written statement from the state patrol showing that the state patrol has on file documentation of the victim's identity pursuant to the personal identification procedures in RCW 43.43.760.

. The provider may require compensation for the reasonable cost of providing the information requested.

. No person, financial information repository, financial service provider, merchant, corporation, trust, partnership, or unincorporated association may be held liable for an action taken in good faith to provide information regarding potential or actual violations of this chapter to other financial information repositories, financial service providers, merchants, law enforcement authorities, victims, or any persons alleging to be a victim who comply with subsection (2) of this section which evidences the alleged victim's claim for the purpose of identification and prosecution of violators of this chapter, or to assist a victim in recovery of fines, restitution, rehabilitation of the victim's credit, or such other relief as may be appropriate.

. A person, financial information repository, financial service provider, merchant, corporation, trust, partnership, or unincorporated association may decline to provide information pursuant to this section when, in the exercise of good faith and reasonable judgment, it believes this section does not require disclosure of the information.

. Nothing in this section creates an obligation on the part of a person, financial information repository, financial services provider, merchant, corporation, trust, partnership, or unincorporated association to retain or maintain information or records that they are not otherwise required to retain or maintain in the ordinary course of its business.

. The legislature finds that the practices covered by this section are matters vitally affecting the public interest for the purpose of applying the Consumer Protection Act, chapter 19.86 RCW. Violations of this section are not reasonable in relation to the development and preservation of business. It is an unfair or deceptive act in trade or commerce and an unfair method of competition for the purpose of applying the Consumer Protection Act, chapter 19.86 RCW. The burden of proof in an action alleging a violation of this section shall be by a preponderance of the evidence, and the applicable statute of limitation shall be as set forth in RCW 19.182.120. For purposes of a judgment awarded pursuant to an action by a consumer under chapter 19.86 RCW, the consumer shall be awarded actual damages. However, where there has been willful failure to comply with any requirement imposed under this section, the consumer shall be awarded actual damages, a monetary penalty of one thousand dollars, and the costs of the action together with reasonable attorneys' fees as determined by the court.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5449-S.SL.pdf?cite=2001%20c%20217%20§%202[2001 c 217 § 2]; ]

== 9.35.050 - Incident reports.
. A person who has learned or reasonably suspects that his or her financial information or means of identification has been unlawfully obtained, used by, or disclosed to another, as described in this chapter, may file an incident report with a law enforcement agency, by contacting the local law enforcement agency that has jurisdiction over his or her actual residence, place of business, or place where the crime occurred. The law enforcement agency shall create a police incident report of the matter and provide the complainant with a copy of that report, and may refer the incident report to another law enforcement agency.

. Nothing in this section shall be construed to require a law enforcement agency to investigate reports claiming identity theft. An incident report filed under this section is not required to be counted as an open case for purposes of compiling open case statistics.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5878.SL.pdf?cite=2008%20c%20207%20§%202[2008 c 207 § 2]; ]

== 9.35.060 - Consumer fraud targeting seniors, vulnerable individuals.
. It is the intent of this section to increase civil penalties for consumer fraud targeting a senior or a vulnerable individual.

. Any consumer fraud that targets a senior or a vulnerable individual, as defined in RCW 9.35.005, is subject to civil penalties of three times the amount of actual damages.

. This section creates no new cause of action. This section increases penalties where a plaintiff proceeds under any existing cause of action under statute or common law and successfully proves that he or she was victim to consumer fraud that targeted him or her as a senior or vulnerable individual.

[ 2017 c 4 § 6 (Initiative Measure No. 1501, approved November 8, 2016); ]

== 9.35.800 - Application of Consumer Protection Act.
The legislature finds that the practices covered by RCW 9.35.010 and 9.35.020 are matters vitally affecting the public interest for the purpose of applying the Consumer Protection Act, chapter 19.86 RCW. Violations of RCW 9.35.010 or 9.35.020 are not reasonable in relation to the development and preservation of business. A violation of RCW 9.35.010 or 9.35.020 is an unfair or deceptive act in trade or commerce and an unfair method of competition for the purpose of applying the Consumer Protection Act, chapter 19.86 RCW.

Nothing in RCW 9.35.010 or 9.35.020 limits a victim's ability to receive treble damages under RCW 19.86.090.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5449-S.SL.pdf?cite=2001%20c%20217%20§%207[2001 c 217 § 7]; ]

== 9.35.900 - Effective date—1999 c 368.
This act takes effect January 1, 2000.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1250-S.SL.pdf?cite=1999%20c%20368%20§%204[1999 c 368 § 4]; ]

