= 9.47 - Gambling.
:toc:

== 9.47.080 - Bucket shop defined.
A bucket shop is hereby defined to be a shed, tent, tenement, booth, building, float or vessel, or any part thereof, wherein may be made contracts respecting the purchase or sale upon margin or credit of any commodities, securities, or property, or option for the purchase thereof, wherein both parties intend that such contract shall or may be terminated, closed and settled; either,

. Upon the basis of the market prices quoted or made on any board of trade or exchange upon which such commodities, securities, or property may be dealt in; or,

. When the market prices for such commodities, securities or property shall reach a certain figure in any such board of trade or exchange; or,

. On the basis of the difference in the market prices at which said commodities, securities or property are, or purport to be, bought and sold.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20223[1909 c 249 § 223]; RRS § 2475; ]

== 9.47.090 - Maintaining bucket shop—Penalty.
Every person, whether in his or her own behalf, or as agent, servant or employee of another person, within or outside of this state, who shall open, conduct or carry on any bucket shop, or make or offer to make any contract described in RCW 9.47.080, or with intent to make such a contract, or assist therein, shall receive, exhibit, or display any statement of market prices of any commodities, securities, or property, is guilty of a class C felony and shall be punished by imprisonment in a state correctional facility for not more than five years.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%2036[2003 c 53 § 36]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2263-S.SL.pdf?cite=1992%20c%207%20§%2013[1992 c 7 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20224[1909 c 249 § 224]; RRS § 2476; ]

== 9.47.100 - Written statement to be furnished—Presumption.
Every person, whether in his or her own behalf, or as the servant, agent, or employee of another person, within or outside of this state, who shall buy or sell for another, or execute any order for the purchase or sale of any commodities, securities, or property, upon margin or credit, whether for immediate or future delivery, shall, upon written demand therefor, furnish such principal or customer with a written statement containing the names of the persons from whom such property was bought, or to whom it has been sold, as the case may be, the time when, the place where, the amount of, and the price at which the same was either bought or sold; and if such person shall refuse or neglect to furnish such statement within forty-eight hours after such written demand, such refusal shall be prima facie evidence as against him or her that such purchase or sale was made in violation of RCW 9.47.090.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20306[2011 c 336 § 306]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20225[1909 c 249 § 225]; RRS § 2477; ]

== 9.47.120 - Bunco steering.
Every person who shall entice, or induce another, upon any pretense, to go to any place where any gambling game, scheme or device, or any trick, sleight of hand performance, fraud or fraudulent scheme, cards, dice or device, is being conducted or operated; or while in such place shall entice or induce another to bet, wager or hazard any money or property, or representative of either, upon any such game, scheme, device, trick, sleight of hand performance, fraud or fraudulent scheme, cards, dice, or device, or to execute any obligation for the payment of money, or delivery of property, or to lose, advance, or loan any money or property, or representative of either, is guilty of a class B felony and shall be punished by imprisonment in a state correctional facility for not more than ten years.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%2037[2003 c 53 § 37]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2263-S.SL.pdf?cite=1992%20c%207%20§%2014[1992 c 7 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20227[1909 c 249 § 227]; RRS § 2479; ]

