= 9.51 - Juries, crimes relating to.
:toc:

== 9.51.010 - Misconduct of officer drawing jury.
Every person charged by law with the preparation of any jury list or list of names from which any jury is to be drawn, and every person authorized by law to assist at the drawing of a grand or petit jury to attend a court or term of court or to try any cause or issue, who shall—

. Place in any such list any name at the request or solicitation, direct or indirect, of any person; or

. Designedly put upon the list of jurors, as having been drawn, any name which was not lawfully drawn for that purpose; or

. Designedly omit to place upon such list any name which was lawfully drawn; or

. Designedly sign or certify a list of such jurors as having been drawn which were not lawfully drawn; or

. Designedly and wrongfully withdraw from the box or other receptacle for the ballots containing the names of such jurors any paper or ballot lawfully placed or belonging there and containing the name of a juror, or omit to place therein any name lawfully drawn or designated, or place therein a paper or ballot containing the name of a person not lawfully drawn and designated as a juror; or

. In drawing or impanelling such jury, do any act which is unfair, partial or improper in any respect;

Shall be guilty of a gross misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%2075[1909 c 249 § 75]; Code 1881 § 922; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%2094%20§%20107[1854 p 94 § 107]; RRS § 2327; ]

== 9.51.020 - Soliciting jury duty.
Every person who shall, directly or indirectly, solicit or request any person charged with the duty of preparing any jury list to put his or her name, or the name of any other person, on any such list, shall be guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20308[2011 c 336 § 308]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%2076[1909 c 249 § 76]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1888%20p%20114%20§%201[1888 p 114 § 1]; RRS § 2328; ]

== 9.51.030 - Misconduct of officer in charge of jury.
Every person to whose charge a jury shall be committed by a court or magistrate, who shall knowingly, without leave of such court or magistrate, permit them or any one of them to receive any communication from any person, to make any communication to any person, to obtain or receive any book, paper or refreshment, or to leave the jury room, shall be guilty of a gross misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%2077[1909 c 249 § 77]; RRS § 2329; ]

== 9.51.040 - Grand juror acting after challenge allowed.
Every grand juror who, with knowledge that a challenge interposed against him or her by a defendant has been allowed, shall be present at, or take part, or attempt to take part, in the consideration of the charge against the defendant who interposed such challenge, or the deliberations of the grand jury thereon, shall be guilty of a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20309[2011 c 336 § 309]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20121[1909 c 249 § 121]; RRS § 2373; ]

== 9.51.050 - Disclosing transaction of grand jury.
Every judge, grand juror, prosecuting attorney, clerk, stenographer, or other officer who, except in the due discharge of his or her official duty, shall disclose the fact that a presentment has been made or indictment found or ordered against any person, before such person shall be in custody; and every grand juror, clerk, or stenographer who, except when lawfully required by a court or officer, shall disclose any evidence adduced before the grand jury, or any proceeding, discussion, or vote of the grand jury or any member thereof, shall be guilty of a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20310[2011 c 336 § 310]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20126[1909 c 249 § 126]; Code 1881 § 991; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20111%20§%2056[1854 p 111 § 56]; RRS § 2378; ]

== 9.51.060 - Disclosure of deposition returned by grand jury.
Every clerk of any court or other officer who shall willfully permit any deposition, or the transcript of any testimony, returned by a grand jury and filed with such clerk or officer, to be inspected by any person except the court, the deputies or assistants of such clerk, and the prosecuting attorney and his or her deputies, until after the arrest of the defendant, shall be guilty of a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20311[2011 c 336 § 311]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20127[1909 c 249 § 127]; RRS § 2379; ]

