= 9.61 - Malicious mischief—Injury to property.
:toc:

== 9.61.160 - Threats to bomb or injure property—Penalty.
. It shall be unlawful for any person to threaten to bomb or otherwise injure any public or private school building, any place of worship or public assembly, any governmental property, or any other building, common carrier, or structure, or any place used for human occupancy; or to communicate or repeat any information concerning such a threatened bombing or injury, knowing such information to be false and with intent to alarm the person or persons to whom the information is communicated or repeated.

. It shall not be a defense to any prosecution under this section that the threatened bombing or injury was a hoax.

. A violation of this section is a class B felony punishable according to chapter 9A.20 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%2038[2003 c 53 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c231.pdf?cite=1977%20ex.s.%20c%20231%20§%201[1977 ex.s. c 231 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c141.pdf?cite=1959%20c%20141%20§%201[1959 c 141 § 1]; ]

== 9.61.190 - Carrier or racing pigeons—Injury to.
It is a class 1 civil infraction for any person, other than the owner thereof or his or her authorized agent, to knowingly shoot, kill, maim, injure, molest, entrap, or detain any Antwerp Messenger or Racing Pigeon, commonly called "carrier or racing pigeons", having the name of its owner stamped upon its wing or tail or bearing upon its leg a band or ring with the name or initials of the owner or an identification or registration number stamped thereon.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20314[2011 c 336 § 314]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c456.pdf?cite=1987%20c%20456%20§%2025[1987 c 456 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c69.pdf?cite=1963%20c%2069%20§%201[1963 c 69 § 1]; ]

== 9.61.200 - Carrier or racing pigeons—Removal or alteration of identification.
It is a class 2 civil infraction for any person other than the owner thereof or his or her authorized agent to remove or alter any stamp, leg band, ring, or other mark of identification attached to any Antwerp Messenger or Racing Pigeon.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20315[2011 c 336 § 315]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c456.pdf?cite=1987%20c%20456%20§%2026[1987 c 456 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c69.pdf?cite=1963%20c%2069%20§%202[1963 c 69 § 2]; ]

== 9.61.230 - Telephone harassment.
. Every person who, with intent to harass, intimidate, torment or embarrass any other person, shall make a telephone call to such other person:

.. Using any lewd, lascivious, profane, indecent, or obscene words or language, or suggesting the commission of any lewd or lascivious act; or

.. Anonymously or repeatedly or at an extremely inconvenient hour, whether or not conversation ensues; or

.. Threatening to inflict injury on the person or property of the person called or any member of his or her family or household;

is guilty of a gross misdemeanor, except as provided in subsection (2) of this section.

. The person is guilty of a class C felony punishable according to chapter 9A.20 RCW if either of the following applies:

.. That person has previously been convicted of any crime of harassment, as defined in RCW 9A.46.060, with the same victim or member of the victim's family or household or any person specifically named in a no-contact or no-harassment order in this or any other state; or

.. That person harasses another person under subsection (1)(c) of this section by threatening to kill the person threatened or any other person.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%2039[2003 c 53 § 39]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2702-S.SL.pdf?cite=1992%20c%20186%20§%206[1992 c 186 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c288.pdf?cite=1985%20c%20288%20§%2011[1985 c 288 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c16.pdf?cite=1967%20c%2016%20§%201[1967 c 16 § 1]; ]

== 9.61.240 - Telephone harassment—Permitting telephone to be used.
Any person who knowingly permits any telephone under his or her control to be used for any purpose prohibited by RCW 9.61.230 shall be guilty of a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20316[2011 c 336 § 316]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c16.pdf?cite=1967%20c%2016%20§%202[1967 c 16 § 2]; ]

== 9.61.250 - Telephone harassment—Offense, where deemed committed.
Any offense committed by use of a telephone as set forth in RCW 9.61.230 may be deemed to have been committed either at the place from which the telephone call or calls were made or at the place where the telephone call or calls were received.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c16.pdf?cite=1967%20c%2016%20§%203[1967 c 16 § 3]; ]

== 9.61.260 - Cyberstalking.
. A person is guilty of cyberstalking if he or she, with intent to harass, intimidate, torment, or embarrass any other person, and under circumstances not constituting telephone harassment, makes an electronic communication to such other person or a third party:

.. Using any lewd, lascivious, indecent, or obscene words, images, or language, or suggesting the commission of any lewd or lascivious act;

.. Anonymously or repeatedly whether or not conversation occurs; or

.. Threatening to inflict injury on the person or property of the person called or any member of his or her family or household.

. Cyberstalking is a gross misdemeanor, except as provided in subsection (3) of this section.

. Cyberstalking is a class C felony if either of the following applies:

.. The perpetrator has previously been convicted of the crime of harassment, as defined in RCW 9A.46.060, with the same victim or a member of the victim's family or household or any person specifically named in a no-contact order or no-harassment order in this or any other state; or

.. The perpetrator engages in the behavior prohibited under subsection (1)(c) of this section by threatening to kill the person threatened or any other person.

. Any offense committed under this section may be deemed to have been committed either at the place from which the communication was made or at the place where the communication was received.

. For purposes of this section, "electronic communication" means the transmission of information by wire, radio, optical cable, electromagnetic, or other similar means. "Electronic communication" includes, but is not limited to, electronic mail, internet-based communications, pager service, and electronic text messaging.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2771-S.SL.pdf?cite=2004%20c%2094%20§%201[2004 c 94 § 1]; ]

