= 9.66 - Nuisance.
:toc:

== 9.66.010 - Public nuisance.
A public nuisance is a crime against the order and economy of the state. Every place

. Wherein any fighting between people or animals or birds shall be conducted; or,

. Wherein any intoxicating liquors are kept for unlawful use, sale or distribution; or,

. Where vagrants resort; and

Every act unlawfully done and every omission to perform a duty, which act or omission

. Shall annoy, injure or endanger the safety, health, comfort, or repose of any considerable number of persons; or,

. Shall offend public decency; or,

. Shall unlawfully interfere with, befoul, obstruct, or tend to obstruct, or render dangerous for passage, a lake, navigable river, bay, stream, canal or basin, or a public park, square, street, alley, highway, or municipal transit vehicle or station; or,

. Shall in any way render a considerable number of persons insecure in life or the use of property;

Shall be a public nuisance.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6505-S.SL.pdf?cite=1994%20c%2045%20§%203[1994 c 45 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c280.pdf?cite=1971%20ex.s.%20c%20280%20§%2022[1971 ex.s. c 280 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20248[1909 c 249 § 248]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c14.pdf?cite=1895%20c%2014%20§%201[1895 c 14 § 1]; Code 1881 § 1246; RRS § 2500; ]

== 9.66.020 - Unequal damage.
An act which affects a considerable number of persons in any of the ways specified in RCW 9.66.010 is not less a public nuisance because the extent of the damage is unequal.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20249[1909 c 249 § 249]; Code 1881 § 1236; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1875%20p%2079%20§%202[1875 p 79 § 2]; RRS § 2501; ]

== 9.66.030 - Maintaining or permitting nuisance.
Every person who shall commit or maintain a public nuisance, for which no special punishment is prescribed; or who shall wilfully omit or refuse to perform any legal duty relating to the removal of such nuisance; and every person who shall let, or permit to be used, any building or boat, or portion thereof, knowing that it is intended to be, or is being used, for committing or maintaining any such nuisance, shall be guilty of a misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20250[1909 c 249 § 250]; Code 1881 § 1248; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1875%20p%2081%20§%2014[1875 p 81 § 14]; RRS § 2502; ]

== 9.66.040 - Abatement of nuisance.
Any court or magistrate before whom there may be pending any proceeding for a violation of RCW 9.66.030, shall, in addition to any fine or other punishment which it may impose for such violation, order such nuisance abated, and all property unlawfully used in the maintenance thereof destroyed by the sheriff at the cost of the defendant: PROVIDED, That if the conviction was had in a district court, the district judge shall not issue the order and warrant of abatement, but on application therefor, shall transfer the cause to the superior court which shall proceed to try the issue of abatement in the same manner as if the action had been originally commenced therein.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c202.pdf?cite=1987%20c%20202%20§%20140[1987 c 202 § 140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c45.pdf?cite=1957%20c%2045%20§%204[1957 c 45 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20251[1909 c 249 § 251]; Code 1881 §§ 1244, 1245; 1875 p 80 §§ 10, 11; RRS § 2503; ]

== 9.66.050 - Deposit of unwholesome substance.
Every person who shall deposit, leave or keep, on or near a highway or route of public travel, on land or water, any unwholesome substance; or who shall establish, maintain or carry on, upon or near a highway or route of public travel, on land or water, any business, trade or manufacture which is noisome or detrimental to the public health; or who shall deposit or cast into any lake, creek or river, wholly or partly in this state, the offal from or the dead body of any animal, shall be guilty of a gross misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20285[1909 c 249 § 285]; RRS § 2537; ]

