= 9.81 - Subversive activities.
:toc:

== 9.81.010 - Definitions.
. "Organization" means an organization, corporation, company, partnership, association, trust, foundation, fund, club, society, committee, political party, or any group of persons, whether or not incorporated, permanently or temporarily associated together for joint action or advancement of views on any subject or subjects.

. "Subversive organization" means any organization which engages in or advocates, abets, advises, or teaches, or a purpose of which is to engage in or advocate, abet, advise, or teach activities intended to overthrow, destroy or alter, or to assist in the overthrow, destruction or alteration of, the constitutional form of the government of the United States, or of the state of Washington, or of any political subdivision of either of them, by revolution, force or violence.

. "Foreign subversive organization" means any organization directed, dominated or controlled directly or indirectly by a foreign government which engages in or advocates, abets, advises, or teaches, or a purpose of which is to engage in or to advocate, abet, advise, or teach, activities intended to overthrow, destroy or alter, or to assist in the overthrow, destruction or alteration of the constitutional form of the government of the United States, or of the state of Washington, or of any political subdivision of either of them, and to establish in place thereof any form of government the direction and control of which is to be vested in, or exercised by or under, the domination or control of any foreign government, organization, or individual.

. "Foreign government" means the government of any country or nation other than the government of the United States of America or of one of the states thereof.

. "Subversive person" means any person who commits, attempts to commit, or aids in the commission, or advocates, abets, advises or teaches by any means any person to commit, attempt to commit, or aid in the commission of any act intended to overthrow, destroy or alter, or to assist in the overthrow, destruction or alteration of, the constitutional form of the government of the United States, or of the state of Washington, or any political subdivision of either of them by revolution, force, or violence; or who with knowledge that the organization is an organization as described in subsections (2) and (3) hereof, becomes or remains a member of a subversive organization or a foreign subversive organization.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c142.pdf?cite=1953%20c%20142%20§%201[1953 c 142 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c254.pdf?cite=1951%20c%20254%20§%201[1951 c 254 § 1]; ]

== 9.81.020 - Subversive activities made felony—Penalty.
. It is a class B felony for any person knowingly and willfully to:

.. Commit, attempt to commit, or aid in the commission of any act intended to overthrow, destroy or alter, or to assist in the overthrow, destruction or alteration of, the constitutional form of the government of the United States, or of the state of Washington or any political subdivision of either of them, by revolution, force or violence; or

.. Advocate, abet, advise, or teach by any means any person to commit, attempt to commit, or assist in the commission of any such act under such circumstances as to constitute a clear and present danger to the security of the United States, or of the state of Washington or of any political subdivision of either of them; or

.. Conspire with one or more persons to commit any such act; or

.. Assist in the formation or participate in the management or to contribute to the support of any subversive organization or foreign subversive organization knowing the organization to be a subversive organization or a foreign subversive organization; or

.. Destroy any books, records or files, or secrete any funds in this state of a subversive organization or a foreign subversive organization, knowing the organization to be such.

. Any person upon a plea of guilty or upon conviction of violating any of the provisions of this section shall be fined not more than ten thousand dollars, or imprisoned for not more than ten years, or both, at the discretion of the court.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%2044[2003 c 53 § 44]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c254.pdf?cite=1951%20c%20254%20§%202[1951 c 254 § 2]; ]

== 9.81.030 - Membership in subversive organization is felony—Penalty.
It is a class C felony for any person after June 1, 1951, to become, or after September 1, 1951, to remain a member of a subversive organization or a foreign subversive organization knowing the organization to be a subversive organization or foreign subversive organization. Any person upon a plea of guilty or upon conviction of violating this section shall be fined not more than five thousand dollars, or imprisoned for not more than five years, or both, at the discretion of the court.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%2045[2003 c 53 § 45]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c254.pdf?cite=1951%20c%20254%20§%203[1951 c 254 § 3]; ]

== 9.81.040 - Disqualification from voting or holding public office.
Any person who shall be convicted or shall plead guilty of violating any of the provisions of RCW 9.81.020 and 9.81.030, in addition to all other penalties therein provided, shall from the date of such conviction be barred from

. Holding any office, elective or appointive, or any other position of profit or trust in, or employment by the government of the state of Washington or of any agency thereof or of any county, municipal corporation or other political subdivision of said state;

. Filing or standing for election to any public office in the state of Washington; or

. Voting in any election held in this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c254.pdf?cite=1951%20c%20254%20§%204[1951 c 254 § 4]; ]

== 9.81.050 - Dissolution of subversive organizations—Disposition of property.
It shall be unlawful for any subversive organization or foreign subversive organization to exist or function in the state of Washington and any organization which by a court of competent jurisdiction is found to have violated the provisions of this section shall be dissolved, and if it be a corporation organized and existing under the laws of the state of Washington a finding by a court of competent jurisdiction that it has violated the provisions of this section shall constitute legal cause for forfeiture of its charter and its charter shall be forfeited and all funds, books, records and files of every kind and all other property of any organization found to have violated the provisions of this section shall be seized by and for the state of Washington, the funds to be deposited in the state treasury and the books, records, files and other property to be turned over to the attorney general of Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c254.pdf?cite=1951%20c%20254%20§%205[1951 c 254 § 5]; ]

== 9.81.060 - Public employment—Subversive person ineligible.
No subversive person, as defined in this chapter, shall be eligible for employment in, or appointment to any office, or any position of trust or profit in the government, or in the administration of the business, of this state, or of any county, municipality, or other political subdivision of this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c254.pdf?cite=1951%20c%20254%20§%2011[1951 c 254 § 11]; ]

== 9.81.070 - Public employment—Determining eligibility—Inquiries—Oath.
Every person and every board, commission, council, department, court or other agency of the state of Washington or any political subdivision thereof, who or which appoints or employs or supervises in any manner the appointment or employment of public officials or employees shall establish by rules, regulations or otherwise, procedures designed to ascertain whether any person is a subversive person. In securing any facts necessary to ascertain the information herein required, the applicant shall be required to sign a written statement containing answers to such inquiries as may be material, which statement shall contain notice that it is subject to the penalties of perjury. Every such person, board, commission, council, department, court, or other agency shall require every employee or applicant for employment to state under oath whether or not he or she is a member of the Communist party or other subversive organization, and refusal to answer on any grounds shall be cause for immediate termination of such employee's employment or for refusal to accept his or her application for employment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c377.pdf?cite=1955%20c%20377%20§%201[1955 c 377 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c254.pdf?cite=1951%20c%20254%20§%2012[1951 c 254 § 12]; ]

== 9.81.080 - Public employment—Inquiries may be dispensed with, when.
The inquiries prescribed in preceding sections, other than the written statement to be executed by an applicant for employment and the requirement set forth in RCW 9.81.070, relative to membership in the communist party or other subversive organization, shall not be required as a prerequisite to the employment of any persons in any case in which the employing authority may determine, and by rule or regulation specify the reasons why, the nature of the work to be performed is such that employment of such persons will not be dangerous to the health of the citizens or the security of the governments of the United States, the state of Washington, or any political subdivision thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c377.pdf?cite=1955%20c%20377%20§%202[1955 c 377 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c254.pdf?cite=1951%20c%20254%20§%2013[1951 c 254 § 13]; ]

== 9.81.082 - Membership in subversive organization described.
For the purpose of *this act, membership in a subversive organization shall be membership in any organization after it has been placed on the list of organizations designated by the attorney general of the United States as being subversive pursuant to executive order No. 9835.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c377.pdf?cite=1955%20c%20377%20§%203[1955 c 377 § 3]; ]

== 9.81.083 - Communist party declared a subversive organization.
The Communist party is a subversive organization within the purview of chapter 9.81 RCW and membership in the Communist party is a subversive activity thereunder.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c377.pdf?cite=1955%20c%20377%20§%204[1955 c 377 § 4]; ]

== 9.81.090 - Public employees—Discharge of subversive persons—Procedure—Hearing—Appeal.
Reasonable grounds on all the evidence to believe that any person is a subversive person, as defined in this chapter, shall be cause for discharge from any appointive office or other position of profit or trust in the government of or in the administration of the business of this state, or of any county, municipality or other political subdivision of this state, or any agency thereof. The attorney general and the personnel director, and the civil service commission of any county, city, or other political subdivision of this state, shall, by appropriate rules or regulations, prescribe that persons charged with being subversive persons, as defined in this chapter, shall have the right of reasonable notice, date, time, and place of hearing, opportunity to be heard by himself or herself and witnesses on his or her behalf, to be represented by counsel, to be confronted by witnesses against him or her, the right to cross-examination, and such other rights which are in accordance with the procedures prescribed by law for the discharge of such person for other reasons. Every person and every board, commission, council, department, or other agency of the state of Washington or any political subdivision thereof having responsibility for the appointment, employment, or supervision of public employees not covered by the classified service in this section referred to, shall establish rules or procedures similar to those required herein for classified services for a hearing for any person charged with being a subversive person, as defined in this chapter, after notice and opportunity to be heard. Every employing authority discharging any person pursuant to any provision of this chapter, shall promptly report to the special assistant attorney general in charge of subversive activities the fact of and the circumstances surrounding such discharge. Any person discharged under the provisions of this chapter shall have the right within thirty days thereafter to appeal to the superior court of the county wherein said person may reside or wherein he or she may have been employed for determination by said court as to whether or not the discharge appealed from was justified under the provisions of this chapter. The court shall regularly hear and determine such appeals and the decision of the superior court may be appealed to the supreme court or the court of appeals of the state of Washington as in civil cases. Any person appealing to the superior court may be entitled to trial by jury if he or she so elects.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20328[2011 c 336 § 328]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c81.pdf?cite=1971%20c%2081%20§%2044[1971 c 81 § 44]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c254.pdf?cite=1951%20c%20254%20§%2015[1951 c 254 § 15]; ]

== 9.81.110 - Misstatements are punishable as perjury—Penalty.
Every written statement made pursuant to this chapter by an applicant for appointment or employment, or by any employee, shall be deemed to have been made under oath if it contains a declaration preceding the signature of the maker to the effect that it is made under the penalties of perjury. Any person who wilfully makes a material misstatement of fact (1) in any such written statement, or (2) in any affidavit made pursuant to the provisions of this chapter, or (3) under oath in any hearing conducted by any agency of the state, or of any of its political subdivisions pursuant to this chapter, or (4) in any written statement by an applicant for appointment or employment or by an employee in any state aid or private institution of learning in this state, intended to determine whether or not such applicant or employee is a subversive person as defined in this chapter, which statement contains notice that it is subject to the penalties of perjury, shall be subject to the penalties of perjury, as prescribed in chapter 9.41 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c254.pdf?cite=1951%20c%20254%20§%2017[1951 c 254 § 17]; ]

== 9.81.120 - Constitutional rights—Censorship or infringement.
Nothing in this chapter shall be construed to authorize, require or establish any military or civilian censorship or in any way to limit or infringe upon freedom of the press or freedom of speech or assembly within the meaning and the manner as guaranteed by the Constitution of the United States or of the state of Washington and no regulation shall be promulgated hereunder having that effect.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c254.pdf?cite=1951%20c%20254%20§%2019[1951 c 254 § 19]; ]

