= 9.96 - Restoration of civil rights.
:toc:

== 9.96.010 - Restoration of civil rights.
Whenever the governor shall grant a pardon to a person convicted of an infamous crime, or whenever the maximum term of imprisonment for which any such person was committed is about to expire or has expired, and such person has not otherwise had his or her civil rights restored, the governor shall have the power, in his or her discretion, to restore to such person his or her civil rights in the manner as in this chapter provided.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20342[2011 c 336 § 342]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c187.pdf?cite=1961%20c%20187%20§%202[1961 c 187 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1931c19.pdf?cite=1931%20c%2019%20§%201[1931 c 19 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c26.pdf?cite=1929%20c%2026%20§%202[1929 c 26 § 2]; RRS § 10250; ]

== 9.96.020 - Form of certificate.
Whenever the governor shall determine to restore his or her civil rights to any person convicted of an infamous crime in any superior court of this state, he or she shall execute and file in the office of the secretary of state an instrument in writing in substantially the following form:

"To the People of the State of WashingtonGreeting:I, the undersigned Governor of the State of Washington, by virtue of the power vested in my office by the constitution and laws of the State of Washington, do by these presents restore to  . . . . . . . . . his or her civil rights forfeited by him (or her) by reason of his (or her) conviction of the crime of  . . . . . . . . . (naming it) in the Superior Court for the County of  . . . . . . . . ., on to-wit: The  . . . . day of  . . . . . ., (year) . . . .Dated the  . . . . day of  . . . . . ., (year) . . . .(Signed)  . . . . . . . . . . . . . . . . . . . . . . .Governor of Washington."

"To the People of the State of Washington

Greeting:

I, the undersigned Governor of the State of Washington, by virtue of the power vested in my office by the constitution and laws of the State of Washington, do by these presents restore to  . . . . . . . . . his or her civil rights forfeited by him (or her) by reason of his (or her) conviction of the crime of  . . . . . . . . . (naming it) in the Superior Court for the County of  . . . . . . . . ., on to-wit: The  . . . . day of  . . . . . ., (year) . . . .

Dated the  . . . . day of  . . . . . ., (year) . . . .

(Signed)  . . . . . . . . . . . . . . . . . . . . . . .



Governor of Washington."

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2359-S.SL.pdf?cite=2016%20c%20202%20§%203[2016 c 202 § 3]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%204[2012 c 117 § 4]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20343[2011 c 336 § 343]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1931c19.pdf?cite=1931%20c%2019%20§%202[1931 c 19 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c26.pdf?cite=1929%20c%2026%20§%203[1929 c 26 § 3]; RRS § 10251; ]

== 9.96.030 - Certified copy—Recording and indexing.
Upon the filing of an instrument restoring civil rights in his or her office, it shall be the duty of the secretary of state to transmit a duly certified copy thereof to the clerk of the superior court named therein, who shall record the same in the journal of the court and index the same in the execution docket of the cause in which the conviction was had.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20344[2011 c 336 § 344]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1931c19.pdf?cite=1931%20c%2019%20§%203[1931 c 19 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c26.pdf?cite=1929%20c%2026%20§%204[1929 c 26 § 4]; RRS § 10252; ]

== 9.96.050 - Final discharge of parolee—Restoration of civil rights—Governor's pardoning power not affected.
. [Empty]
.. When an offender on parole has performed all obligations of his or her release, including any and all legal financial obligations, for such time as shall satisfy the indeterminate sentence review board that his or her final release is not incompatible with the best interests of society and the welfare of the paroled individual, the board may make a final order of discharge and issue a certificate of discharge to the offender.

.. The board retains the jurisdiction to issue a certificate of discharge after the expiration of the offender's or parolee's maximum statutory sentence. If not earlier granted and any and all legal financial obligations have been paid, the board shall issue a final order of discharge three years from the date of parole unless the parolee is on suspended or revoked status at the expiration of the three years.

.. The discharge, regardless of when issued, shall have the effect of restoring all civil rights not already restored by RCW 29A.08.520, and the certification of discharge shall so state.

.. This restoration of civil rights shall not restore the right to receive, possess, own, or transport firearms.

.. The board shall issue a certificate of discharge to the offender in person or by mail to the offender's last known address.

. A copy of every signed certificate of discharge for offender sentences under the authority of the department of corrections shall be placed in the department's files.

. The discharge provided for in this section shall be considered as a part of the sentence of the convicted person and shall not in any manner be construed as affecting the powers of the governor to pardon any such person.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5891-S.SL.pdf?cite=2011%201st%20sp.s.%20c%2040%20§%2022[2011 1st sp.s. c 40 § 22]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1517.SL.pdf?cite=2009%20c%20325%20§%204[2009 c 325 § 4]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1592.SL.pdf?cite=2007%20c%20363%20§%204[2007 c 363 § 4]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1431.SL.pdf?cite=2007%20c%20171%20§%202[2007 c 171 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6240-S.SL.pdf?cite=2002%20c%2016%20§%203[2002 c 16 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5060.SL.pdf?cite=1993%20c%20140%20§%204[1993 c 140 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c75.pdf?cite=1980%20c%2075%20§%201[1980 c 75 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c187.pdf?cite=1961%20c%20187%20§%201[1961 c 187 § 1]; ]

== 9.96.060 - Vacating records of conviction for misdemeanor and gross misdemeanor offenses.
. When vacating a conviction under this section, the court effectuates the vacation by: (a)(i) Permitting the applicant to withdraw the applicant's plea of guilty and to enter a plea of not guilty; or (ii) if the applicant has been convicted after a plea of not guilty, the court setting aside the verdict of guilty; and (b) the court dismissing the information, indictment, complaint, or citation against the applicant and vacating the judgment and sentence.

. Every person convicted of a misdemeanor or gross misdemeanor offense may apply to the sentencing court for a vacation of the applicant's record of conviction for the offense. If the court finds the applicant meets the requirements of this subsection, the court may in its discretion vacate the record of conviction. Except as provided in subsections (3), (4), and (5) of this section, an applicant may not have the record of conviction for a misdemeanor or gross misdemeanor offense vacated if any one of the following is present:

.. The applicant has not completed all of the terms of the sentence for the offense;

.. There are any criminal charges against the applicant pending in any court of this state or another state, or in any federal or tribal court, at the time of application;

.. The offense was a violent offense as defined in RCW 9.94A.030 or an attempt to commit a violent offense;

.. The offense was a violation of RCW 46.61.502 (driving while under the influence), 46.61.504 (actual physical control while under the influence), 9.91.020 (operating a railroad, etc. while intoxicated), or the offense is considered a "prior offense" under RCW 46.61.5055 and the applicant has had a subsequent alcohol or drug violation within ten years of the date of arrest for the prior offense or less than ten years has elapsed since the date of the arrest for the prior offense;

.. The offense was any misdemeanor or gross misdemeanor violation, including attempt, of chapter 9.68 RCW (obscenity and pornography), chapter 9.68A RCW (sexual exploitation of children), or chapter 9A.44 RCW (sex offenses), except for failure to register as a sex offender under RCW 9A.44.132;

.. The applicant was convicted of a misdemeanor or gross misdemeanor offense as defined in RCW 10.99.020, or the court determines after a review of the court file that the offense was committed by one family or household member against another or by one intimate partner against another, or the court, after considering the damage to person or property that resulted in the conviction, any prior convictions for crimes defined in RCW 10.99.020, or for comparable offenses in another state or in federal court, and the totality of the records under review by the court regarding the conviction being considered for vacation, determines that the offense involved domestic violence, and any one of the following factors exist:

... The applicant has not provided written notification of the vacation petition to the prosecuting attorney's office that prosecuted the offense for which vacation is sought, or has not provided that notification to the court;

... The applicant has two or more domestic violence convictions stemming from different incidents. For purposes of this subsection, however, if the current application is for more than one conviction that arose out of a single incident, none of those convictions counts as a previous conviction;

... The applicant has signed an affidavit under penalty of perjury affirming that the applicant has not previously had a conviction for a domestic violence offense, and a criminal history check reveals that the applicant has had such a conviction; or

... Less than five years have elapsed since the person completed the terms of the original conditions of the sentence, including any financial obligations and successful completion of any treatment ordered as a condition of sentencing;

.. For any offense other than those described in (f) of this subsection, less than three years have passed since the person completed the terms of the sentence, including any financial obligations;

.. The offender has been convicted of a new crime in this state, another state, or federal or tribal court in the three years prior to the vacation application; or

.. The applicant is currently restrained by a domestic violence protection order, a no-contact order, an antiharassment order, or a civil restraining order which restrains one party from contacting the other party or was previously restrained by such an order and was found to have committed one or more violations of the order in the five years prior to the vacation application.

. Subject to RCW 9.96.070, every person convicted of prostitution under RCW 9A.88.030 who committed the offense as a result of being a victim of trafficking, RCW 9A.40.100, promoting prostitution in the first degree, RCW 9A.88.070, promoting commercial sexual abuse of a minor, RCW 9.68A.101, or trafficking in persons under the trafficking victims protection act of 2000, 22 U.S.C. Sec. 7101 et seq. may apply to the sentencing court for vacation of the applicant's record of conviction for the prostitution offense. An applicant may not have the record of conviction for prostitution vacated if any one of the following is present:

.. There are any criminal charges against the applicant pending in any court of this state or another state, or in any federal court, for any crime other than prostitution; or

.. The offender has been convicted of another crime, except prostitution, in this state, another state, or federal court since the date of conviction. The limitation in this subsection (3)(b) does not apply to convictions where the offender proves by a preponderance of the evidence that he or she committed the crime as a result of being a victim of trafficking, RCW 9A.40.100, promoting prostitution in the first degree, RCW 9A.88.070, promoting commercial sexual abuse of a minor, RCW 9.68A.101, or trafficking in persons under the trafficking victims protection act of 2000, 22 U.S.C. Sec. 7101 et seq., according to the requirements provided in RCW 9.96.070 for each respective conviction.

. Every person convicted prior to January 1, 1975, of violating any statute or rule regarding the regulation of fishing activities, including, but not limited to, RCW 75.08.260, 75.12.060, 75.12.070, 75.12.160, 77.16.020, 77.16.030, 77.16.040, 77.16.060, and 77.16.240 who claimed to be exercising a treaty Indian fishing right, may apply to the sentencing court for vacation of the applicant's record of the misdemeanor, gross misdemeanor, or felony conviction for the offense. If the person is deceased, a member of the person's family or an official representative of the tribe of which the person was a member may apply to the court on behalf of the deceased person. Notwithstanding the requirements of RCW 9.94A.640, the court shall vacate the record of conviction if:

.. The applicant is a member of a tribe that may exercise treaty Indian fishing rights at the location where the offense occurred; and

.. The state has been enjoined from taking enforcement action of the statute or rule to the extent that it interferes with a treaty Indian fishing right as determined under United States v. Washington, 384 F. Supp. 312 (W.D. Wash. 1974), or Sohappy v. Smith, 302 F. Supp. 899 (D. Oregon 1969), and any posttrial orders of those courts, or any other state supreme court or federal court decision.

. Every person convicted of a misdemeanor marijuana offense, who was twenty-one years of age or older at the time of the offense, may apply to the sentencing court for a vacation of the applicant's record of conviction for the offense. A misdemeanor marijuana offense includes, but is not limited to: Any offense under RCW 69.50.4014, from July 1, 2004, onward, and its predecessor statutes, including RCW 69.50.401(e), from March 21, 1979, to July 1, 2004, and RCW 69.50.401(d), from May 21, 1971, to March 21, 1979, and any offense under an equivalent municipal ordinance. If an applicant qualifies under this subsection, the court shall vacate the record of conviction.

. [Empty]
.. Except as provided in (c) of this subsection, once the court vacates a record of conviction under this section, the person shall be released from all penalties and disabilities resulting from the offense and the fact that the person has been convicted of the offense shall not be included in the person's criminal history for purposes of determining a sentence in any subsequent conviction. For all purposes, including responding to questions on employment or housing applications, a person whose conviction has been vacated under this section may state that he or she has never been convicted of that crime. However, nothing in this section affects the requirements for restoring a right to possess a firearm under RCW 9.41.040. Except as provided in (b) of this subsection, nothing in this section affects or prevents the use of an offender's prior conviction in a later criminal prosecution.

.. When a court vacates a record of domestic violence as defined in RCW 10.99.020 under this section, the state may not use the vacated conviction in a later criminal prosecution unless the conviction was for: (i) Violating the provisions of a restraining order, no-contact order, or protection order restraining or enjoining the person or restraining the person from going on to the grounds of or entering a residence, workplace, school, or day care, or prohibiting the person from knowingly coming within, or knowingly remaining within, a specified distance of a location (RCW 10.99.040, 10.99.050, 26.09.300, * 26.10.220, 26.26B.050, 26.44.063, 26.44.150, 26.50.060, 26.50.070, 26.50.130, 26.52.070, or 74.34.145); or (ii) stalking (RCW 9A.46.110). A vacated conviction under this section is not considered a conviction of such an offense for the purposes of 27 C.F.R. 478.11.

.. A conviction vacated on or after July 28, 2019, qualifies as a prior conviction for the purpose of charging a present recidivist offense as defined in RCW 9.94A.030 occurring on or after July 28, 2019.

. The clerk of the court in which the vacation order is entered shall immediately transmit the order vacating the conviction to the Washington state patrol identification section and to the local police agency, if any, which holds criminal history information for the person who is the subject of the conviction. The Washington state patrol and any such local police agency shall immediately update their records to reflect the vacation of the conviction, and shall transmit the order vacating the conviction to the federal bureau of investigation. A conviction that has been vacated under this section may not be disseminated or disclosed by the state patrol or local law enforcement agency to any person, except other criminal justice enforcement agencies.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2473-S.SL.pdf?cite=2020%20c%2029%20§%2018[2020 c 29 § 18]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5605.SL.pdf?cite=2019%20c%20400%20§%201[2019 c 400 § 1]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1041-S.SL.pdf?cite=2019%20c%20331%20§%204[2019 c 331 § 4]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5333-S.SL.pdf?cite=2019%20c%2046%20§%205010[2019 c 46 § 5010]; prior:  2017 c 336 § 2; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1163-S2.SL.pdf?cite=2017%20c%20272%20§%209[2017 c 272 § 9]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5272-S.SL.pdf?cite=2017%20c%20128%20§%201[2017 c 128 § 1]; prior:  2014 c 176 § 1; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1292-S.SL.pdf?cite=2014%20c%20109%20§%201[2014 c 109 § 1]; prior:  2012 c 183 § 5; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6255.SL.pdf?cite=2012%20c%20142%20§%202[2012 c 142 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1174-S.SL.pdf?cite=2001%20c%20140%20§%201[2001 c 140 § 1]; ]

== 9.96.070 - Vacating records of conviction—Prostitution offenses.
. In order to vacate a record of conviction for a prostitution offense pursuant to RCW 9.96.060(3) as a result of being a victim of trafficking, RCW 9A.40.100, the applicant must prove each of the following elements by a preponderance of the evidence:

.. [Empty]
... The applicant was recruited, harbored, transported, provided, obtained, bought, purchased, or received by another person;

... The person who committed any of the acts in (a)(i) of this subsection against the applicant acted knowingly or in reckless disregard for the fact that force, fraud, or coercion would be used to cause the applicant to engage in a sexually explicit act or commercial sex act; and

... The applicant's conviction record for prostitution and other convictions under RCW 9.96.060(3)(b), if applicable, resulted from such acts; or

.. [Empty]
... The applicant was recruited, harbored, transported, provided, obtained, bought, purchased, or received by another person;

... The person who committed any of the acts in (b)(i) of this subsection against the applicant acted knowingly or in reckless disregard for the fact that the applicant had not attained the age of eighteen and would be caused to engage in a sexually explicit act or commercial sex act; and

... The applicant's record of conviction for prostitution and other convictions under RCW 9.96.060(3)(b), if applicable, resulted from such acts.

. In order to vacate a record of conviction for a prostitution offense pursuant to RCW 9.96.060(3) as a result of being a victim of promoting prostitution in the first degree, RCW 9A.88.070, the applicant must prove each of the following elements by a preponderance of the evidence:

.. [Empty]
... The applicant was compelled by threat or force to engage in prostitution;

... The person who compelled the applicant acted knowingly; and

... The applicant's conviction record for prostitution and other convictions under RCW 9.96.060(3)(b), if applicable, resulted from the compulsion; or

.. [Empty]
... The applicant has a mental incapacity or developmental disability that renders the applicant incapable of consent;

... The applicant was compelled to engage in prostitution;

... The person who compelled the applicant acted knowingly; and

... The applicant's record of conviction for prostitution and other convictions under RCW 9.96.060(3)(b), if applicable, resulted from the compulsion.

. In order to vacate a record of conviction for a prostitution offense pursuant to RCW 9.96.060(3) as a result of being a victim of promoting commercial sexual abuse of a minor, RCW 9.68A.101, the applicant must prove each of the following elements by a preponderance of the evidence:

.. [Empty]
... The applicant had not attained the age of eighteen at the time of the prostitution offense;

... A person advanced commercial sexual abuse or a sexually explicit act of the applicant at the time he or she had not attained the age of eighteen;

... The person committing the acts in (a)(ii) of this subsection acted knowingly; and

... The applicant's record of conviction for prostitution and other convictions under RCW 9.96.060(3)(b), if applicable, resulted from any of the acts in (a)(ii) of this subsection.

.. For purposes of this subsection (3), a person:

... "Advanced commercial sexual abuse" of the applicant if, acting other than as a minor receiving compensation for personally rendered sexual conduct or as a person engaged in commercial sexual abuse of a minor, he or she causes or aids a person to commit or engage in commercial sexual abuse of a minor, procures or solicits customers for commercial sexual abuse of a minor, provides persons or premises for the purposes of engaging in commercial sexual abuse of a minor, operates or assists in the operation of a house or enterprise for the purposes of engaging in commercial sexual abuse of a minor, or engages in any other conduct designed to institute, aid, cause, assist, or facilitate an act or enterprise of commercial sexual abuse of a minor;

... "Advanced a sexually explicit act" of the applicant if he or she causes or aids a sexually explicit act of a minor, procures or solicits customers for a sexually explicit act of a minor, provides persons or premises for the purposes of a sexually explicit act of a minor, or engages in any other conduct designed to institute, aid, cause, assist, or facilitate a sexually explicit act of a minor.

. In order to vacate a record of conviction for a prostitution offense pursuant to RCW 9.96.060(3) as a result of being a victim of trafficking in persons under the trafficking victims protection act of 2000, 22 U.S.C. Sec. 7101 et seq., the applicant must prove each of the following elements by a preponderance of the evidence:

.. The applicant was induced by force, fraud, or coercion to engage in a commercial sex act and the record of conviction for prostitution and other convictions under RCW 9.96.060(3)(b), if applicable, resulted from the inducement; or

.. The applicant was induced to engage in a commercial sex act prior to reaching the age of eighteen and the record of conviction for prostitution and other convictions under RCW 9.96.060(3)(b), if applicable, resulted from the inducement.

. Any motion for vacation of a conviction under RCW 9.96.060(3) and this section must be supported by the sworn testimony of the applicant at a hearing before the court.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5272-S.SL.pdf?cite=2017%20c%20128%20§%202[2017 c 128 § 2]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1292-S.SL.pdf?cite=2014%20c%20109%20§%202[2014 c 109 § 2]; ]

