= 17.12 - Agricultural pest districts.
:toc:

== 17.12.010 - Pest districts authorized.
For the purpose of destroying or exterminating squirrels, prairie dogs, gophers, moles or other rodents, or of rabbits or any predatory animals that destroy or interfere with the crops, fruit trees, shrubs, valuable plants, fodder, seeds or other agricultural plants or products, thing or pest injurious to any agricultural plant or product, or to prevent the introduction, propagation, growth or increase in number of any of the above described animals, or rodents, the board of county commissioners of any county may create a pest district or pest districts within such county and may enlarge any district containing a lesser territory than the whole county, or reduce any district already created, or combine or consolidate districts or divide, or create new districts from time to time in the manner hereinafter set forth.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c152.pdf?cite=1919%20c%20152%20§%201[1919 c 152 § 1]; RRS § 2801; ]

== 17.12.020 - Petition—Notice—Hearing.
Whenever ten or more resident freeholders in any county petition the board of county commissioners, asking that their lands be included, either separately or with other lands designated in the petition in a district to be formed for the purpose of preventing, destroying, or exterminating any of the animals, rodents or other such things described in RCW 17.12.010, or that such lands be included within a district already formed by the enlargement of such district, or a new district or districts be formed out of a district or districts then in existence or out of territory partly in districts already formed and not included in any district, and such petition indicating the boundaries of such proposed district, whether all or any part of such county, and stating the purpose of such district, the board shall fix a time for the hearing of such petition and shall give at least thirty days notice of the time and place of such hearing by posting copies of such notice of the time and place of such hearing in three conspicuous places within the proposed district and posting one copy of such notice at the courthouse or place of business of the board, and also by mailing to each freeholder within the proposed district a copy of such notice, to his last known residence, if known, and if not known to the clerk of such board, then and in that event the posting shall be deemed sufficient: PROVIDED, HOWEVER, If the board shall deem it impractical to mail notices to each freeholder, within the proposed district, or if the post office address of all the freeholders are not known, then in that event when recited in a resolution adopted by the board, the notice in addition to posting, shall be published once a week for three successive weeks in the county official paper if there is such, and if there be no official paper, then in some paper published in said county, and if there be no paper published in said county, then in some paper of general circulation within the proposed district. The persons in whose name the property is assessed shall be deemed the owners thereof for the purpose of notice as herein required: PROVIDED, HOWEVER, That for lands belonging to the state, the commissioner of public lands shall be notified, and for lands belonging to the county, the county auditor shall be notified, and if such lands are under lease or conditional sale the lessee or purchaser shall also be notified in the manner above provided. Any person interested may appear at the time of such hearing and may under such rules and regulations as the board may prescribe give his or her reasons for or objections to the creation of such a district.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c152.pdf?cite=1919%20c%20152%20§%202[1919 c 152 § 2]; RRS § 2802; ]

== 17.12.030 - Determination—Boundaries of district.
Upon the hearing of such petition the board shall determine whether such a district shall be created and shall fix the boundaries thereof, but shall not enlarge the boundaries of proposed districts or enlarge or change the boundary or boundaries of any district or districts already formed without first giving the notice to all parties interested as provided in RCW 17.12.020.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c152.pdf?cite=1919%20c%20152%20§%203[1919 c 152 § 3]; RRS § 2803; ]

== 17.12.040 - Designation of district.
If the board shall deem the interests of the county or of any particular section thereof will be benefited by the creation of such a district or districts, or the changing thereof, it shall make a record thereof upon the minutes of the board and shall designate such territory in each such district as "Pest District . . . . . . for . . . . . . County".

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c152.pdf?cite=1919%20c%20152%20§%204[1919 c 152 § 4]; RRS § 2804; ]

== 17.12.050 - Treasurer—Tax levies.
The county treasurer shall be ex officio treasurer for each of such districts so formed and the county assessor and other county officers shall take notice of the formation of such district or districts and shall be governed thereby according to the provisions of this chapter. The assessment or the tax levies as hereinafter provided for shall be extended on the tax rolls against the property liable therefor the same as other assessments or taxes are extended, and shall become a part of the general tax against such property and be collected and accounted for the same as other taxes are, with the terms and penalties attached thereto. The moneys so collected shall be held and disbursed as a special fund for such district and shall be paid out only on warrant issued by the county auditor upon voucher approved by the board of county commissioners.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c152.pdf?cite=1919%20c%20152%20§%205[1919 c 152 § 5]; RRS § 2805; ]

== 17.12.060 - Supervision of the district.
The agricultural expert in counties having an agricultural expert, shall under the direction of Washington State University have general supervision of the methods and means of preventing, destroying, or exterminating any animals or rodents as herein mentioned within his or her county, and of how the funds of any pest district shall be expended to best accomplish the purposes for which such funds were raised; in counties having no such agricultural expert each county commissioner shall be within his or her respective commissioner district, ex officio supervisor, or the board may designate some such person to so act, and shall fix his or her compensation therefor. Whenever any member of the board shall act as supervisor he or she shall be entitled to his or her actual expenses and his or her per diem as county commissioner the same as if he or she were doing other county business.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20458[2011 c 336 § 458]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c169.pdf?cite=1977%20ex.s.%20c%20169%20§%204[1977 ex.s. c 169 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c152.pdf?cite=1919%20c%20152%20§%206[1919 c 152 § 6]; RRS § 2806; ]

== 17.12.080 - Levies on state and county lands—Levies on state lands to be added to rental or purchase price.
Whenever there shall be included within any pest district lands belonging to the state or to the county the board of county commissioners shall determine the amount of the tax or assessment for which such land would be liable if the same were in private ownership for each subdivision of forty acres or fraction thereof. The assessor shall transmit to the county commissioners a statement of the amounts so due from county lands and the county commissioners shall appropriate from the current expense fund of the county sufficient money to pay such amounts. A statement of the amounts due from state lands within each county shall be annually forwarded to the commissioner of public lands who shall examine the same and if he or she finds the same correct and that the determination was made according to law, he or she shall certify the same and issue a warrant for the payment of same against any funds in the state treasury appropriated for such purposes.

The commissioner of public lands shall keep a record of the amounts so paid on account of any state lands which are under lease or contract of sale and such amounts shall be added to and become a part of the annual rental or purchase price of the land, and shall be paid annually at the time of payment of rent or payment of interest or purchase price of such land. When such amounts shall be collected by the commissioner of public lands it shall be paid into the general fund in the state treasury.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20459[2011 c 336 § 459]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c106.pdf?cite=1973%20c%20106%20§%2011[1973 c 106 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c152.pdf?cite=1919%20c%20152%20§%208[1919 c 152 § 8]; RRS § 2808; ]

== 17.12.100 - Limit of indebtedness.
No district shall be permitted to contract obligations in excess of the estimated revenues for the two years next succeeding the incoming [incurring] of such indebtedness and it shall be unlawful for the county commissioners to approve of any bills which will exceed the revenue to any district which shall be estimated to be received by such district during the next two years.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c152.pdf?cite=1919%20c%20152%20§%209[1919 c 152 § 9]; RRS § 2809; ]

