= 17.15 - Integrated pest management.
:toc:

== 17.15.005 - Legislative declaration.
The legislature declares that it is the policy of the state of Washington to require all state agencies that have pest control responsibilities to follow the principles of integrated pest management.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=1997%20c%20357%20§%201[1997 c 357 § 1]; ]

== 17.15.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise:

. "Integrated pest management" means a coordinated decision-making and action process that uses the most appropriate pest control methods and strategy in an environmentally and economically sound manner to meet agency programmatic pest management objectives. The elements of integrated pest management include:

.. Preventing pest problems;

.. Monitoring for the presence of pests and pest damage;

.. Establishing the density of the pest population, that may be set at zero, that can be tolerated or correlated with a damage level sufficient to warrant treatment of the problem based on health, public safety, economic, or aesthetic thresholds;

.. Treating pest problems to reduce populations below those levels established by damage thresholds using strategies that may include biological, cultural, mechanical, and chemical control methods and that must consider human health, ecological impact, feasibility, and cost-effectiveness; and

.. Evaluating the effects and efficacy of pest treatments.

. "Pest" means, but is not limited to, any insect, rodent, nematode, snail, slug, weed, and any form of plant or animal life or virus, except virus, bacteria, or other microorganisms on or in a living person or other animal or in or on processed food or beverages or pharmaceuticals, which is normally considered to be a pest, or which the director of the department of agriculture may declare to be a pest.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=1997%20c%20357%20§%202[1997 c 357 § 2]; ]

== 17.15.020 - Implementation of integrated pest management practices.
Each of the following state agencies or institutions or county agencies shall implement integrated pest management practices when carrying out the agency's or institution's duties related to pest control:

. The department of agriculture;

. The state noxious weed control board;

. The department of ecology;

. The department of fish and wildlife;

. The department of transportation;

. The parks and recreation commission;

. The department of natural resources;

. The department of corrections;

. The department of enterprise services;

. Each state institution of higher education, for the institution's own building and grounds maintenance;

. Each county noxious weed control board; and

. Each weed district.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1355-S.SL.pdf?cite=2021%20c%20217%20§%2017[2021 c 217 § 17]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5024.SL.pdf?cite=2015%20c%20225%20§%2016[2015 c 225 § 16]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=1997%20c%20357%20§%203[1997 c 357 § 3]; ]

== 17.15.030 - Integrated pest management training—Designated coordinator.
. A state agency or institution listed in RCW 17.15.020 shall provide integrated pest management training for employees responsible for pest management.

. A state agency or institution listed in RCW 17.15.020 shall designate an integrated pest management coordinator.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5374-S.SL.pdf?cite=2011%20c%20103%20§%2036[2011 c 103 § 36]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=1997%20c%20357%20§%204[1997 c 357 § 4]; ]

