= 17.24 - Insect pests and plant diseases.
:toc:

== 17.24.003 - Purpose.
The purpose of this chapter is to provide a strong system for the exclusion of plant and bee pests and diseases through regulation of movement and quarantines of infested areas to protect the forest, agricultural, horticultural, floricultural, and apiary industries of the state; plants and shrubs within the state; and the environment of the state from the impact of insect pests, plant pathogens, noxious weeds, and bee pests and the public and private costs that result when these infestations become established.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1956-S.SL.pdf?cite=1991%20c%20257%20§%203[1991 c 257 § 3]; ]

== 17.24.007 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Department" means the state department of agriculture.

. "Director" means the director of the state department of agriculture or the director's designee.

. "Quarantine" means a rule issued by the department that prohibits or regulates the movement of articles, bees, plants, or plant products from designated quarantine areas within or outside the state to prevent the spread of disease, plant pathogens, or pests to nonquarantine areas.

. "Plant pest" means a living stage of an insect, mite, nematode, slug, snail, or protozoa, or other invertebrate animal, bacteria, fungus, or parasitic plant, or their reproductive parts, or viruses, or an organism similar to or allied with any of the foregoing plant pests, including a genetically engineered organism, or an infectious substance that can directly or indirectly injure or cause disease or damage in plants or parts of plants or in processed, manufactured, or other products of plants.

. "Plants and plant products" means trees, shrubs, vines, forage, and cereal plants, and all other plants and plant parts, including cuttings, grafts, scions, buds, fruit, vegetables, roots, bulbs, seeds, wood, lumber, and all products made from the plants and plant products.

. "Certificate" or "certificate of inspection" means an official document certifying compliance with the requirements of this chapter. The term "certificate" includes labels, rubber stamp imprints, tags, permits, written statements, or a form of inspection and certification document that accompanies the movement of inspected and certified plant material and plant products, or bees, bee hives, or beekeeping equipment.

. "Compliance agreement" means a written agreement between the department and a person engaged in growing, handling, or moving articles, plants, plant products, or bees, bee hives, or beekeeping equipment regulated under this chapter, in which the person agrees to comply with stipulated requirements.

. "Distribution" means the movement of a regulated article from the property where it is grown or kept, to property that is not contiguous to the property, regardless of the ownership of the properties.

. "Genetically engineered organism" means an organism altered or produced through genetic modification from a donor, vector, or recipient organism using recombinant DNA techniques, excluding those organisms covered by the food, drug and cosmetic act (21 U.S.C. Secs. 301-392).

. "Person" means a natural person, individual, firm, partnership, corporation, company, society, or association, and every officer, agent, or employee of any of these entities.

. "Sell" means to sell, to hold for sale, offer for sale, handle, or to use as inducement for the sale of another article or product.

. "Noxious weed" means a living stage, including, but not limited to, seeds and reproductive parts, of a parasitic or other plant of a kind that presents a threat to Washington agriculture or environment.

. "Regulated article" means a plant or plant product, bees or beekeeping equipment, noxious weed or other articles or equipment capable of harboring or transporting plant or bee pests or noxious weeds that is specifically addressed in rules or quarantines adopted under this chapter.

. "Owner" means the person having legal ownership, possession, or control over a regulated article covered by this chapter including, but not limited to, the owner, shipper, consignee, or their agent.

. "Nuisance" means a plant, or plant part, apiary, or property found in a commercial area on which is found a pest, pathogen, or disease that is a source of infestation to other properties.

. "Bees" means adult insects, eggs, larvae, pupae, or other immature stages of the species Apis mellifera.

. "Bee pests" means a mite, other parasite, or disease that causes injury to bees and those honey bees generally recognized to have undesirable behavioral characteristics such as or as found in Africanized honey bees.

. "Biological control" means the use by humans of living organisms to control or suppress undesirable animals and plants; the action of parasites, predators, or pathogens on a host or prey population to produce a lower general equilibrium than would prevail in the absence of these agents.

. "Biological control agent" means a parasite, predator, or pathogen intentionally released, by humans, into a target host or prey population with the intent of causing population reduction of that host or prey.

. "Emergency" means a situation where there is an imminent danger of an infestation of plant pests or disease that seriously threatens the state's agricultural or horticultural industries or environment and that cannot be adequately addressed with normal procedures or existing resources.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2995.SL.pdf?cite=2000%20c%20100%20§%206[2000 c 100 § 6]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1956-S.SL.pdf?cite=1991%20c%20257%20§%204[1991 c 257 § 4]; ]

== 17.24.011 - Regulation of plant, plant product, bee movement, and genetically engineered organisms.
Notwithstanding the provisions of RCW 17.24.041, the director may:

. Make rules under which plants, plant products, bees, hives and beekeeping equipment, and noxious weeds may be brought into this state from other states, territories, or foreign countries; and

. Make rules with reference to plants, plant products, bees, bee hives and equipment, and genetically engineered organisms while in transit through this state as may be deemed necessary to prevent the introduction into and dissemination within this state of plant and bee pests and noxious weeds.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1956-S.SL.pdf?cite=1991%20c%20257%20§%205[1991 c 257 § 5]; ]

== 17.24.021 - Inspection and investigation.
. The director may intercept and hold or order held for inspection, or cause to be inspected while in transit or after arrival at their destination, all plants, plant products, bees, or other articles likely to carry plant pests, bee pests, or noxious weeds being moved into this state from another state, territory, or a foreign country or within or through this state for plant and bee pests and disease.

. The director may enter upon public and private premises at reasonable times for the purpose of carrying out this chapter. If the director be denied access, the director may apply to any court of competent jurisdiction for a search warrant authorizing access to such premises. The court may upon such application issue the search warrant for the purposes requested.

. The director may adopt rules in accordance with chapter 34.05 RCW as may be necessary to carry out the purposes and provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1956-S.SL.pdf?cite=1991%20c%20257%20§%206[1991 c 257 § 6]; ]

== 17.24.031 - Determination of origin.
The director may demand of a person who has in his or her possession or under his or her control, plants, bees, plant products, or other articles that may carry plant pests, bee pests, or noxious weeds, full information as to the origin and source of these items. Failure to provide that information, if known, may subject the person to a civil penalty.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1956-S.SL.pdf?cite=1991%20c%20257%20§%207[1991 c 257 § 7]; ]

== 17.24.041 - Power to adopt quarantine measures—Rules.
If determined to be necessary to protect the forest, agricultural, horticultural, floricultural, beekeeping, or environmental interests of this state, the director may declare a quarantine against an area, place, nursery, orchard, vineyard, apiary, or other agricultural establishment, county or counties within the state, or against other states, territories, or foreign countries, or a portion of these areas, in reference to plant pests, or bee pests, or noxious weeds, or genetically engineered plant or plant pest organisms. The director may prohibit the movement of all regulated articles from such quarantined places or areas that are likely to contain such plant pests or noxious weeds or genetically engineered plant, plant pest, or bee pest organisms. The quarantine may be made absolute or rules may be adopted prescribing the conditions under which the regulated articles may be moved into, or sold, or otherwise disposed of in the state.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1956-S.SL.pdf?cite=1991%20c%20257%20§%208[1991 c 257 § 8]; ]

== 17.24.051 - Introduction of plant pests, noxious weeds, or organisms affecting plant life—Special transit permit for brush, yard waste, or debris generated inside a quarantine area for apple maggot.
. The introduction into or release within the state of a plant pest, noxious weeds, bee pest, or any other organism that may directly or indirectly affect the plant life of the state as an injurious pest, parasite, predator, or other organism is prohibited, except under special permit issued by the department under rules adopted by the director. A special permit is not required for the introduction or release within the state of a genetically engineered plant or plant pest organism if the introduction or release has been approved under provisions of federal law and the department has been notified of the planned introduction or release. The department shall be the sole issuing agency for the permits. Except for research projects approved by the department, no permit for a biological control agent shall be issued unless the department has determined that the parasite, predator, or plant pathogen is target organism or plant specific and not likely to become a pest of nontarget plants or other beneficial organisms. The director may also exclude biological control agents that are infested with parasites determined to be detrimental to the biological control efforts of the state. The department may rely upon findings of the United States department of agriculture or any experts that the director may deem appropriate in making a determination about the threat posed by such organisms. In addition, the director may request confidential business information subject to the conditions in RCW 17.24.061.

. Plant pests, noxious weeds, or other organisms introduced into or released within this state in violation of this section shall be subject to detention and disposition as otherwise provided in this chapter.

. Upon the request of a city or town that is located partially inside a quarantine area for apple maggot established by the department, the department may issue a special transit permit for the limited purpose of transporting brush and yard waste or debris generated within the city or town through a pest free area to a destination located inside a quarantine area for apple maggot established by the department, subject to conditions and provisions which the director may prescribe to prevent introduction, escape, or spread of the quarantined pests.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6055-S.SL.pdf?cite=2018%20c%20147%20§%202[2018 c 147 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1956-S.SL.pdf?cite=1991%20c%20257%20§%209[1991 c 257 § 9]; ]

== 17.24.061 - Protection of privileged or confidential information—Procedure—Notice—Declaratory judgment.
. In submitting data required by this chapter, the applicant may: (a) Mark clearly portions of data which in his or her opinion are trade secrets or commercial or financial information; and (b) submit the marked material separately from other material required to be submitted under this chapter.

. Notwithstanding any other provision of this chapter or other law, the director shall not make information submitted by an applicant or registrant under this chapter available to the public if, in the judgment of the director, the information is privileged or confidential because it contains or relates to trade secrets or commercial or financial information. Where necessary to carry out the provisions of this chapter, information relating to unpublished formulas of products acquired by authorization of this chapter may be revealed to any state or federal agency consulted and may be revealed at a public hearing or in findings of fact issued by the director.

. If the director proposes to release for inspection or to reveal at a public hearing or in findings of fact issued by the director, information that the applicant or registrant believes to be protected from disclosure under subsection (2) of this section, he or she shall notify the applicant or registrant in writing, by certified mail. The director may not make this data available for inspection nor reveal the information at a public hearing or in findings of fact issued by the director until thirty days after receipt of the notice by the applicant or registrant. During this period, the applicant or registrant may withdraw the application or may institute an action in the superior court of Thurston county for a declaratory judgment as to whether the information is subject to protection under subsection (2) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1956-S.SL.pdf?cite=1991%20c%20257%20§%2010[1991 c 257 § 10]; ]

== 17.24.071 - Compliance agreements.
The director may enter into compliance agreements with a person engaged in growing, handling, or moving articles, bees, plants, or plant products regulated under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1956-S.SL.pdf?cite=1991%20c%20257%20§%2011[1991 c 257 § 11]; ]

== 17.24.081 - Prohibited acts.
It shall be unlawful for a person to:

. Sell, offer for sale, or distribute a noxious weed or a plant or plant product or regulated article infested or infected with a plant pest declared by rule to be a threat to the state's forest, agricultural, horticultural, floricultural, or beekeeping industries or environment;

. Knowingly receive a noxious weed, or a plant, plant product, bees, bee hive or appliances, or regulated article sold, given away, carried, shipped, or delivered for carriage or shipment within this state, in violation of the provisions of this chapter or the rules adopted under this chapter;

. Fail to immediately notify the department and isolate and hold the noxious weed, bees, bee hives or appliances, plants or plant products, or other thing unopened or unused subject to inspection or other disposition as may be provided by the department, where the item has been received without knowledge of the violation and the receiver has become subsequently aware of the potential problem;

. Knowingly conceal or willfully withhold available information regarding an infected or infested plant, plant product, regulated article, or noxious weed;

. Introduce or move into this state, or to move or dispose of in this state, a plant, plant product, or other item included in a quarantine, except under rules as may be prescribed by the department, after a quarantine order has been adopted under this chapter against a place, nursery, orchard, vineyard, apiary, other agricultural establishment, county of this state, another state, territory, or a foreign country as to a plant pest, bee pest, or noxious weed or genetically engineered plant or plant pest organism, until such quarantine is removed;

. Introduce or move nonnative managed bumble bees into this state to be used in open-field agricultural use.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5253-S2.SL.pdf?cite=2021%20c%20278%20§%205[2021 c 278 § 5]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1956-S.SL.pdf?cite=1991%20c%20257%20§%2012[1991 c 257 § 12]; ]

== 17.24.091 - Impound and disposition.
. If upon inspection, the director finds that an inspected plant or plant product or bees are infected or infested or that a regulated article is being held or transported in violation of a rule or quarantine of the department, the director shall notify the owner that a violation of this chapter exists. The director may impound or order the impounding of the infected or infested or regulated article in such a manner as may be necessary to prevent the threat of infestation. The notice shall be in writing and sent by certified mail or personal service identifying the impounded article and giving notice that the articles will be treated, returned to the shipper or to a quarantined area, or destroyed in a manner as to prevent infestation. The impounded article shall not be destroyed unless the director determines that (a) no effective treatment can be carried out; and (b) the impounded article cannot be returned to the shipper or shipped back to a quarantine area without threat of infestation to this state; and (c) mere possession by the owner constitutes an emergency.

. Before taking action to treat, return, or destroy the impounded article, the director shall notify the owner of the owner's right to a hearing before the director under chapter 34.05 RCW. Within ten days after the notice has been given the owner may request a hearing. The request must be in writing.

. The cost to impound articles along with the cost, if any, to treat, return, or destroy the articles shall be at the owner's expense. The owner is not entitled to compensation for infested or infected articles destroyed by the department under this section.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1956-S.SL.pdf?cite=1991%20c%20257%20§%2013[1991 c 257 § 13]; ]

== 17.24.100 - Penalties—Second and subsequent offenses.
. Except as provided in subsection (2) of this section, every person who violates or fails to comply with any rule or regulation adopted and promulgated by the director of agriculture in accordance with and under the provision of this chapter is guilty of a misdemeanor.

. A second and each subsequent violation or failure to comply with the provisions of this chapter or rule or regulation adopted hereunder is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20119[2003 c 53 § 119]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c296.pdf?cite=1981%20c%20296%20§%2026[1981 c 296 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c292.pdf?cite=1927%20c%20292%20§%207[1927 c 292 § 7]; RRS § 2786; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c105.pdf?cite=1921%20c%20105%20§%207[1921 c 105 § 7]; ]

== 17.24.101 - Statewide survey and control activity.
If there is reason to believe that a plant or bee pest may adversely impact the forestry, agricultural, horticultural, floricultural, or related industries of the state; or may cause harm to the environment of the state; or such information is needed to facilitate or allow the movement of forestry, agricultural, horticultural, or related products to out-of-state, foreign and domestic markets, the director may conduct, or cause to be conducted, surveys to determine the presence, absence, or distribution of a pest.

The director may take such measures as may be required to control or eradicate such pests where such measures are determined to be in the public interest, are technically feasible, and for which funds are appropriated or provided through cooperative agreements.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1956-S.SL.pdf?cite=1991%20c%20257%20§%2014[1991 c 257 § 14]; ]

== 17.24.111 - Director's cooperation with other agencies.
The director may enter into cooperative arrangements with a person, municipality, county, Washington State University or any of its experiment stations, or other agencies of this state, and with boards, officers, and authorities of other states and the United States, including the United States department of agriculture, for the inspection of bees, plants and plant parts and products and the control or eradication of plant pests, bee pests, or noxious weeds and to carry out other provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1956-S.SL.pdf?cite=1991%20c%20257%20§%2015[1991 c 257 § 15]; ]

== 17.24.121 - Acquisition of lands, water supply, or other properties for quarantine locations.
The director may acquire, in fee or in trust, by gift, or whenever funds are appropriated for such purposes, by purchase, easement, lease, or condemnation, lands or other property, water supplies, as may be deemed necessary for use by the department for establishing quarantine stations for the purpose of the isolation, prevention, eradication, elimination, and control of insect pests or plant pathogens that affect the agricultural or horticultural products of the state; for the propagation of biological control agents; or the isolation of genetically engineered plants or plant pests; or the isolation of bee pests.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1956-S.SL.pdf?cite=1991%20c%20257%20§%2016[1991 c 257 § 16]; ]

== 17.24.131 - Requested inspections—Fee for service—Disbursements in lieu of fee.
To facilitate the movement or sale of forest, agricultural, floricultural, horticultural and related products, or bees and related products, the director may provide, if requested by farmers, growers, or other interested persons, special inspections, pest identifications, plant identifications, plant diagnostic services, pest control activities, other special certifications and activities not otherwise authorized by statute and prescribe a fee for that service. The fee shall, as closely as practical, cover the cost of the service rendered, including the salaries and expenses of the personnel involved. Moneys collected shall be deposited in the plant pest account, which is hereby created within the agricultural local fund. No appropriation is required for disbursement from the plant pest account to provide the services authorized by this section. In lieu of a fee, assessments and other funds deposited in the plant pest account may be disbursed to provide the services authorized by this section.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1832.SL.pdf?cite=1997%20c%20227%20§%202[1997 c 227 § 2]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1956-S.SL.pdf?cite=1991%20c%20257%20§%2017[1991 c 257 § 17]; ]

== 17.24.141 - Penalties—Criminal and civil penalty.
Whenever the director finds that a person has committed a violation of any of the provisions of this chapter, and that violation has not been punished pursuant to RCW 17.24.100, the director may impose upon and collect from the violator a civil penalty not exceeding five thousand dollars per violation. Each violation shall be a separate and distinct offense. A person who knowingly, through an act of commission or omission, procures or aids or abets in the violation shall be considered to have violated this section and may be subject to the civil penalty.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1956-S.SL.pdf?cite=1991%20c%20257%20§%2018[1991 c 257 § 18]; ]

== 17.24.151 - Violations—Costs of control.
A person who, through a knowing and willful violation of a quarantine established under this chapter, causes an infestation to become established, may be required to pay the costs of public control or eradication measures caused as a result of that violation.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1956-S.SL.pdf?cite=1991%20c%20257%20§%2019[1991 c 257 § 19]; ]

== 17.24.161 - Funds for technical and scientific services.
The director may, at the director's discretion, provide funds for technical or scientific services, labor, materials and supplies, and biological control agents for the control of plant pests, bee pests, and noxious weeds.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1956-S.SL.pdf?cite=1991%20c%20257%20§%2020[1991 c 257 § 20]; ]

== 17.24.171 - Determination of imminent danger of infestation of plant pests or plant diseases—Emergency measures—Conditions—Procedures.
. If the director determines that there exists an imminent danger of an infestation of plant pests or plant diseases that seriously endangers the agricultural or horticultural industries of the state, or that seriously threatens life, health, economic well-being, or the environment, the director shall request the governor to order emergency measures to control the pests or plant diseases under RCW 43.06.010(13). The director's findings shall contain an evaluation of the affect of the emergency measures on public health.

. If an emergency is declared pursuant to RCW 43.06.010(13), the director may appoint a committee to advise the governor through the director and to review emergency measures necessary under the authority of RCW 43.06.010(13) and this section and make subsequent recommendations to the governor. The committee shall include representatives of the agricultural industries, state and local government, public health interests, technical service providers, and environmental organizations.

. Upon the order of the governor of the use of emergency measures, the director is authorized to implement the emergency measures to prevent, control, or eradicate plant pests or plant diseases that are the subject of the emergency order. Such measures, after thorough evaluation of all other alternatives, may include the aerial application of pesticides.

. Upon the order of the governor of the use of emergency measures, the director is authorized to enter into agreements with individuals, companies, or agencies, to accomplish the prevention, control, or eradication of plant pests or plant diseases, notwithstanding the provisions of chapter 15.58 or 17.21 RCW, or any other statute.

. The director shall continually evaluate the emergency measures taken and report to the governor at intervals of not less than ten days. The director shall immediately advise the governor if he or she finds that the emergency no longer exists or if certain emergency measures should be discontinued.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5144-S.SL.pdf?cite=2003%20c%20314%20§%206[2003 c 314 § 6]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1956-S.SL.pdf?cite=1991%20c%20257%20§%2021[1991 c 257 § 21]; ]

== 17.24.210 - Indemnity contracts for damages resulting from prevention, control, or eradication measures—Authorized—Conditions.
The director of agriculture may, on the behalf of the state of Washington, enter into indemnity contracts wherein the state of Washington agrees to repay any person, firm, corporation, or other entity acting under the direction or control of the proper authority to provide plant pest or plant disease prevention, control, or eradication measures as provided in this chapter or any rule adopted pursuant to the provisions of this chapter, for losses and damages incurred as a result of such prevention, control, or eradication measures if all of the following conditions occur:

. At the time of the incident the worker is performing services as an emergency measures worker and is acting within the course of his or her duties as an emergency measures worker;

. At the time of the injury, loss, or damage, the organization providing emergency measures by which the worker is employed is an approved organization for providing emergency measures;

. The injury, loss, or damage is proximately caused by his or her service either with or without negligence as an emergency measures worker;

. The injury, loss, or damage is not caused by the intoxication of the worker; and

. The injury, loss, or damage is not due to willful misconduct or gross negligence on the part of a worker.

Where an act or omission by an emergency services provider in the course of providing emergency services injures a person or property, the provider and the state may be jointly and severally liable for the injury, if state liability is proved under existing or hereafter enacted law.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20461[2011 c 336 § 461]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5374-S.SL.pdf?cite=2011%20c%20103%20§%2043[2011 c 103 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c153.pdf?cite=1982%20c%20153%20§%203[1982 c 153 § 3]; ]

== 17.24.220 - Sudden oak death syndrome—Coordinated response effort.
The department and the department of natural resources shall coordinate their sudden oak death syndrome response efforts with other plant pest agencies and private organizations to exchange information, monitor the confirmed incidences of the disease, and take action as appropriate under existing plant pest control authorities to prevent the introduction of the disease into Washington and to control or eradicate the disease if it is determined to be present in the state.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5144-S.SL.pdf?cite=2003%20c%20314%20§%208[2003 c 314 § 8]; ]

