= 82.19 - Litter tax.
:toc:

== 82.19.010 - Litter tax imposed—Report to the legislature—Time of collection.
. In addition to any other taxes, there is hereby levied and there shall be collected by the department of revenue from every person for the privilege of engaging within this state in business as a manufacturer, as a wholesaler, or as a retailer, a litter tax equal to the value of products listed in RCW 82.19.020, including by-products, manufactured within this state, multiplied by fifteen one-thousandths of one percent in the case of manufacturers, and equal to the gross proceeds of sales of the products listed in RCW 82.19.020 that are sold within this state multiplied by fifteen one-thousandths of one percent in the case of wholesalers and retailers.

. The frequency and time of collection of the tax will coincide with the reporting periods by payers of their business and occupation tax.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6663.SL.pdf?cite=2008%20c%2086%20§%20201[2008 c 86 § 201]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3058-S2.SL.pdf?cite=1998%20c%20257%20§%207[1998 c 257 § 7]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2635-S.SL.pdf?cite=1992%20c%20175%20§%203[1992 c 175 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c307.pdf?cite=1971%20ex.s.%20c%20307%20§%2012[1971 ex.s. c 307 § 12]; ]

== 82.19.020 - Application to certain products.
To accomplish effective litter control within the state and to allocate a portion of the cost of administering this chapter to those industries whose products, including the packages, wrappings, and containers thereof, are reasonably related to the litter problem, the tax imposed in this chapter shall only apply to the value of products or the gross proceeds of sales of products falling into the following categories:

. Food for human or pet consumption.

. Groceries.

. Cigarettes and tobacco products.

. Soft drinks and carbonated waters.

. Beer and other malt beverages.

. Wine.

. Newspapers and magazines.

. Household paper and paper products.

. Glass containers.

. Metal containers.

. Plastic or fiber containers made of synthetic material.

. Cleaning agents and toiletries.

. Nondrug drugstore sundry products.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2635-S.SL.pdf?cite=1992%20c%20175%20§%204[1992 c 175 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c307.pdf?cite=1971%20ex.s.%20c%20307%20§%2013[1971 ex.s. c 307 § 13]; ]

== 82.19.030 - Rule-making authority tax—Items subject to—Reporting and accounting.
. The department of revenue, by rule, may, if such is required, define those items subject to tax under RCW 82.19.020. In making any such definitions, the department of revenue shall be guided by the following standards:

.. It is the purpose of this chapter to accomplish effective control of litter within this state;

.. It is the purpose of this chapter to allocate a portion of the cost of administration of this chapter to those industries manufacturing and/or selling products and the packages, wrappings, or containers thereof which are reasonably related to the litter problem within this state.

. Instead of requiring each business to separately account for taxable and nontaxable products under this chapter, the department may provide, by rule, that the tax imposed in this chapter be reported and paid based on a percentage of total sales for a particular type of business if the department determines that the percentage reasonably approximates the taxable activity of the particular type of business.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2635-S.SL.pdf?cite=1992%20c%20175%20§%205[1992 c 175 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c307.pdf?cite=1971%20ex.s.%20c%20307%20§%2014[1971 ex.s. c 307 § 14]; ]

== 82.19.040 - Application of chapters  82.04 and  82.32 RCW—Disposition of revenue.
. To the extent applicable, all of the definitions of chapter 82.04 RCW and all of the provisions of chapter 82.32 RCW apply to the tax imposed in this chapter.

. Beginning June 30, 2019, taxes collected under this chapter shall be deposited in the waste reduction, recycling, and litter control account under RCW 70A.200.140, except that until June 30, 2020, one million two hundred fifty thousand dollars must be deposited in equal monthly amounts in the state parks renewal and stewardship account, with the remainder deposited in the waste reduction, recycling, and litter control account.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6168-S.SL.pdf?cite=2020%20c%20357%20§%20920[2020 c 357 § 920]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201482[2020 c 20 § 1482]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1109-S.SL.pdf?cite=2019%20c%20415%20§%20989[2019 c 415 § 989]; 2018 c 299 § 915; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5883-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%201%20§%20990[2017 3rd sp.s. c 1 § 990]; 2017 3rd sp.s. c 1 § 989; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1060-S.SL.pdf?cite=2015%20c%2015%20§%206[2015 c 15 § 6]; 2015 c 15 § 5; 2013 2nd sp.s. c 15 § 5; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1339-S.SL.pdf?cite=2001%20c%20118%20§%206[2001 c 118 § 6]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2635-S.SL.pdf?cite=1992%20c%20175%20§%206[1992 c 175 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c307.pdf?cite=1971%20ex.s.%20c%20307%20§%2016[1971 ex.s. c 307 § 16]; ]

== 82.19.050 - Exemptions.
The litter tax imposed in this chapter does not apply to:

. The manufacture or sale of products for use and consumption outside the state;

. The value of products or gross proceeds of the sales exempt from tax under RCW 82.04.330; 

. The sale of products for resale by a qualified grocery distribution cooperative to customer-owners of the grocery distribution cooperative. For the purposes of this section, "qualified grocery distribution cooperative" and "customer-owner" have the meanings given in RCW 82.04.298; 

. The sale of food or beverages by retailers that are sold solely for immediate consumption indoors at the seller's place of business or at a deck or patio at the seller's place of business, or indoors at an eating area that is contiguous to the seller's place of business; or

. [Empty]
.. The sale of prepared food or beverages by caterers where the food or beverages are to be served for immediate consumption in or on individual nonsingle use containers at premises occupied or controlled by the customer.

.. For the purposes of this subsection, the following definitions apply:

... "Prepared food" has the same meaning as provided in RCW 82.08.0293.

... "Nonsingle use container" means a receptacle for holding a single individual's food or beverage that is designed to be used more than once. Nonsingle use containers do not include pizza delivery bags and similar insulated containers that do not directly contact the food. Nonsingle use containers do not include plastic or paper plates or other containers that are disposable.

... "Caterer" means a person contracted to prepare food where the final cooking or serving occurs at a location selected by the customer.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1887-S.SL.pdf?cite=2005%20c%20289%20§%201[2005 c 289 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1037.SL.pdf?cite=2003%20c%20120%20§%201[2003 c 120 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2260.SL.pdf?cite=2001%201st%20sp.s.%20c%209%20§%207[2001 1st sp.s. c 9 § 7]; 2001 1st sp.s. c 9 § 8; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1339-S.SL.pdf?cite=2001%20c%20118%20§%207[2001 c 118 § 7]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2635-S.SL.pdf?cite=1992%20c%20175%20§%207[1992 c 175 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c307.pdf?cite=1971%20ex.s.%20c%20307%20§%2017[1971 ex.s. c 307 § 17]; ]

== 82.19.055 - Tax preferences—Expiration dates.
See RCW 82.32.805 for the expiration date of new tax preferences for the tax imposed under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5882-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%2013%20§%201710[2013 2nd sp.s. c 13 § 1710]; ]

== 82.19.900 - Effective date—1992 c 175.
This act shall take effect July 1, 1992.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2635-S.SL.pdf?cite=1992%20c%20175%20§%2011[1992 c 175 § 11]; ]

