= 82.23B - Oil spill response tax.
:toc:

== 82.23B.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Barrel" means a unit of measurement of volume equal to forty-two United States gallons of crude oil or petroleum product.

. "Bulk oil terminal" means a facility of any kind, other than a waterborne vessel, that is used for transferring crude oil or petroleum products from a tank car or pipeline.

. "Crude oil" means any naturally occurring hydrocarbons coming from the earth that are liquid at twenty-five degrees Celsius and one atmosphere of pressure including, but not limited to, crude oil, bitumen and diluted bitumen, synthetic crude oil, and natural gas well condensate.

. "Department" means the department of revenue.

. "Marine terminal" means a facility of any kind, other than a waterborne vessel, that is used for transferring crude oil or petroleum products to or from a waterborne vessel or barge.

. "Navigable waters" means those waters of the state and their adjoining shorelines that are subject to the ebb and flow of the tide, including the Columbia and Snake rivers.

. "Person" has the meaning provided in RCW 82.04.030.

. "Petroleum product" means any liquid hydrocarbons at atmospheric temperature and pressure that are the product of the fractionation, distillation, or other refining or processing of crude oil, and that are used as, useable as, or may be refined as a fuel or fuel blendstock, including but not limited to, gasoline, diesel fuel, aviation fuel, bunker fuel, and fuels containing a blend of alcohol and petroleum.

. "Pipeline" means an interstate or intrastate pipeline subject to regulation by the United States department of transportation under 49 C.F.R. Part 195 in effect on April 1, 2018, through which oil moves in transportation, including line pipes, valves, and other appurtenances connected to line pipes, pumping units, and fabricated assemblies associated with pumping units.

. "Tank car" means a rail car, the body of which consists of a tank for transporting liquids.

. "Taxpayer" means the person owning crude oil or petroleum products immediately after receipt of the same into the storage tanks of a marine or bulk oil terminal in this state and who is liable for the taxes imposed by this chapter.

. "Waterborne vessel or barge" means any ship, barge, or other watercraft capable of traveling on the navigable waters of this state and capable of transporting any crude oil or petroleum product in quantities of ten thousand gallons or more for purposes other than providing fuel for its motor or engine.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6269-S2.SL.pdf?cite=2018%20c%20262%20§%20102[2018 c 262 § 102]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1449-S.SL.pdf?cite=2015%20c%20274%20§%2013[2015 c 274 § 13]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2389-S.SL.pdf?cite=1992%20c%2073%20§%206[1992 c 73 § 6]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1027-S.SL.pdf?cite=1991%20c%20200%20§%20801[1991 c 200 § 801]; ]

== 82.23B.020 - Oil spill response tax—Oil spill administration tax.
. An oil spill response tax is imposed on the privilege of receiving: (a) Crude oil or petroleum products at a marine terminal within this state from a waterborne vessel or barge operating on the navigable waters of this state; or (b) crude oil or petroleum products at a bulk oil terminal within this state from a tank car or pipeline. The tax imposed in this section is levied upon the owner of the crude oil or petroleum products immediately after receipt of the same into the storage tanks of a marine or bulk oil terminal from a tank car, pipeline, waterborne vessel, or barge at the rate of one cent per barrel of crude oil or petroleum product received.

. In addition to the tax imposed in subsection (1) of this section, an oil spill administration tax is imposed on the privilege of receiving: (a) Crude oil or petroleum products at a marine terminal within this state from a waterborne vessel or barge operating on the navigable waters of this state; or (b) crude oil or petroleum products at a bulk oil terminal within this state from a tank car or pipeline. The tax imposed in this section is levied upon the owner of the crude oil or petroleum products immediately after receipt of the same into the storage tanks of a marine or bulk oil terminal from a tank car, pipeline, waterborne vessel, or barge at the rate of four cents per barrel of crude oil or petroleum product.

. The taxes imposed by this chapter must be collected by the marine or bulk oil terminal operator from the taxpayer. If any person charged with collecting the taxes fails to bill the taxpayer for the taxes, or in the alternative has not notified the taxpayer in writing of the taxes imposed, or having collected the taxes, fails to pay them to the department in the manner prescribed by this chapter, whether such failure is the result of the person's own acts or the result of acts or conditions beyond the person's control, he or she, nevertheless, is personally liable to the state for the amount of the taxes. Payment of the taxes by the owner to a marine or bulk oil terminal operator relieves the owner from further liability for the taxes.

. Taxes collected under this chapter must be held in trust until paid to the department. Any person collecting the taxes who appropriates or converts the taxes collected is guilty of a gross misdemeanor if the money required to be collected is not available for payment on the date payment is due. The taxes required by this chapter to be collected must be stated separately from other charges made by the marine or bulk oil terminal operator in any invoice or other statement of account provided to the taxpayer.

. If a taxpayer fails to pay the taxes imposed by this chapter to the person charged with collection of the taxes and the person charged with collection fails to pay the taxes to the department, the department may, in its discretion, proceed directly against the taxpayer for collection of the taxes.

. The taxes are due from the marine or bulk oil terminal operator, along with reports and returns on forms prescribed by the department, within twenty-five days after the end of the month in which the taxable activity occurs.

. The amount of taxes, until paid by the taxpayer to the marine or bulk oil terminal operator or to the department, constitutes a debt from the taxpayer to the marine or bulk oil terminal operator. Any person required to collect the taxes under this chapter who, with intent to violate the provisions of this chapter, fails or refuses to do so as required and any taxpayer who refuses to pay any taxes due under this chapter, is guilty of a misdemeanor as provided in chapter 9A.20 RCW.

. Upon prior approval of the department, the taxpayer may pay the taxes imposed by this chapter directly to the department. The department must give its approval for direct payment under this section whenever it appears, in the department's judgment, that direct payment will enhance the administration of the taxes imposed under this chapter. The department must provide by rule for the issuance of a direct payment certificate to any taxpayer qualifying for direct payment of the taxes. Good faith acceptance of a direct payment certificate by a terminal operator relieves the marine or bulk oil terminal operator from any liability for the collection or payment of the taxes imposed under this chapter.

. [Empty]
.. All receipts from the tax imposed in subsection (1) of this section must be deposited into the state oil spill response account.

.. Beginning in fiscal year 2019 and each fiscal year thereafter, the first two hundred thousand dollars of receipts from the tax imposed in subsection (2) of this section must be deposited into the military department active state service account created in RCW 38.40.220, and the remainder of the receipts from the tax imposed in subsection (2) of this section must be deposited into the oil spill prevention account.

. Within forty-five days after the end of each calendar quarter, the office of financial management must determine the balance of the oil spill response account as of the last day of that calendar quarter. Balance determinations by the office of financial management under this section are final and may not be used to challenge the validity of any tax imposed under this chapter. The office of financial management must promptly notify the departments of revenue and ecology of the account balance once a determination is made. For each subsequent calendar quarter, the tax imposed by subsection (1) of this section shall be imposed during the entire calendar quarter unless:

.. Tax was imposed under subsection (1) of this section during the immediately preceding calendar quarter, and the most recent quarterly balance is more than nine million dollars; or

.. Tax was not imposed under subsection (1) of this section during the immediately preceding calendar quarter, and the most recent quarterly balance is more than eight million dollars.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6269-S2.SL.pdf?cite=2018%20c%20262%20§%20103[2018 c 262 § 103]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1449-S.SL.pdf?cite=2015%20c%20274%20§%2014[2015 c 274 § 14]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2671.SL.pdf?cite=2006%20c%20256%20§%202[2006 c 256 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2269.SL.pdf?cite=2003%201st%20sp.s.%20c%2013%20§%209[2003 1st sp.s. c 13 § 9]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6210-S.SL.pdf?cite=2000%20c%2069%20§%2025[2000 c 69 § 25]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2247-S.SL.pdf?cite=1999%20sp.s.%20c%207%20§%201[1999 sp.s. c 7 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2096-S.SL.pdf?cite=1997%20c%20449%20§%202[1997 c 449 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%20214[1995 c 399 § 214]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2389-S.SL.pdf?cite=1992%20c%2073%20§%207[1992 c 73 § 7]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1027-S.SL.pdf?cite=1991%20c%20200%20§%20802[1991 c 200 § 802]; ]

== 82.23B.025 - Tax preferences—Expiration dates.
See RCW 82.32.805 for the expiration date of new tax preferences for the tax imposed under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5882-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%2013%20§%201713[2013 2nd sp.s. c 13 § 1713]; ]

== 82.23B.030 - Exemption.
The taxes imposed under this chapter only apply to the first receipt of crude oil or petroleum products at a marine or bulk oil terminal in this state and not to the later transporting and subsequent receipt of the same oil or petroleum product, whether in the form originally received at a marine or bulk oil terminal in this state or after refining or other processing.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1449-S.SL.pdf?cite=2015%20c%20274%20§%2015[2015 c 274 § 15]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2389-S.SL.pdf?cite=1992%20c%2073%20§%209[1992 c 73 § 9]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1027-S.SL.pdf?cite=1991%20c%20200%20§%20803[1991 c 200 § 803]; ]

== 82.23B.040 - Credit—Crude oil or petroleum exported or sold for export.
Credit must be allowed against the taxes imposed under this chapter for any crude oil or petroleum products received at a marine or bulk oil terminal and subsequently exported from or sold for export from the state.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1449-S.SL.pdf?cite=2015%20c%20274%20§%2016[2015 c 274 § 16]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2389-S.SL.pdf?cite=1992%20c%2073%20§%2010[1992 c 73 § 10]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1027-S.SL.pdf?cite=1991%20c%20200%20§%20804[1991 c 200 § 804]; ]

== 82.23B.045 - Refund or credit—Petroleum products used by consumers for nonfuel purpose or used in manufacture of nonfuel item.
. Any person having paid the tax imposed by this chapter who uses petroleum products as a consumer for a purpose other than as a fuel may claim refund or credit against the tax imposed under this chapter. For this purpose, the term consumer shall be defined as provided in RCW 82.04.190.

. Any person having paid the tax imposed by this chapter who uses petroleum products as a component or ingredient in the manufacture of an item which is not a fuel may claim a refund or credit against the tax imposed by this chapter.

. The amount of refund or credit claimed under this section may not exceed the amount of tax paid by the person making such claim on the petroleum products so consumed or used. The refund or credit allowed by this section shall be claimed on such forms and subject to such requirements as the department may prescribe by rule.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2389-S.SL.pdf?cite=1992%20c%2073%20§%208[1992 c 73 § 8]; ]

== 82.23B.050 - Rules.
The department shall adopt such rules as may be necessary to enforce and administer the provisions of this chapter. Chapter 82.32 RCW applies to the administration, collection, and enforcement of the taxes levied under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1027-S.SL.pdf?cite=1991%20c%20200%20§%20808[1991 c 200 § 808]; ]

== 82.23B.060 - Imposition of taxes.
The taxes imposed in this chapter shall take effect October 1, 1991.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1027-S.SL.pdf?cite=1991%20c%20200%20§%20809[1991 c 200 § 809]; ]

== 82.23B.900 - Effective dates—1991 c 200.
See RCW 90.56.901.

[ ]

== 82.23B.901 - Savings—1992 c 73.
The amendment of RCW 82.23B.010, 82.23B.020, 82.23B.030, and 82.23B.040 by chapter 73, Laws of 1992, shall not be construed as affecting any existing right acquired or liability or obligation incurred under the sections or under any rule or order adopted under the sections, nor as affecting any proceeding instituted under the sections.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2389-S.SL.pdf?cite=1992%20c%2073%20§%2044[1992 c 73 § 44]; ]

== 82.23B.902 - Effective dates—1992 c 73.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and shall take effect immediately [March 26, 1992], except sections 6, 7, 9, and 10 of this act shall take effect October 1, 1992.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2389-S.SL.pdf?cite=1992%20c%2073%20§%2046[1992 c 73 § 46]; ]

