= 82.27 - Tax on enhanced food fish.
:toc:

== 82.27.010 - Definitions.
As used in this chapter, the following terms have the meanings indicated unless the context clearly requires otherwise.

. "Enhanced food fish" includes all species of food fish, except all species of tuna, mackerel, and jack; shellfish; and anadromous game fish, including by-products and parts thereof, originating within the territorial and adjacent waters of Washington and salmon originating from within the territorial and adjacent waters of Oregon, Washington, and British Columbia, and all troll-caught Chinook salmon originating from within the territorial and adjacent waters of southeast Alaska. As used in this subsection, "adjacent" waters of Oregon, Washington, and Alaska are those comprising the United States fish conservation zone; "adjacent" waters of British Columbia are those comprising the Canadian two hundred mile exclusive economic zone; and "southeast Alaska" means that portion of Alaska south and east of Cape Suckling to the Canadian border. For purposes of this chapter, point of origination is established by a document which identifies the product and state or province in which it originates, including, but not limited to fish tickets, bills of lading, invoices, or other documentation required to be kept by governmental agencies.

. "Commercial" means related to or connected with buying, selling, bartering, or processing.

. "Possession" means the control of enhanced food fish by the owner and includes both actual and constructive possession. Constructive possession occurs when the person has legal ownership but not actual possession of the enhanced food fish.

. "Anadromous game fish" means steelhead trout and anadromous cutthroat trout and Dolly Varden char and includes by-products and also parts of anadromous game fish, whether fresh, frozen, canned, or otherwise.

. "Landed" means the act of physically placing enhanced food fish (a) on a tender in the territorial waters of Washington; or (b) on any land within or without the state of Washington including wharves, piers, or any such extensions therefrom.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5157-S2.SL.pdf?cite=1995%20c%20372%20§%204[1995 c 372 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c413.pdf?cite=1985%20c%20413%20§%201[1985 c 413 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c46.pdf?cite=1983%201st%20ex.s.%20c%2046%20§%20180[1983 1st ex.s. c 46 § 180]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c284.pdf?cite=1983%20c%20284%20§%205[1983 c 284 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c98.pdf?cite=1980%20c%2098%20§%201[1980 c 98 § 1]; ]

== 82.27.020 - Excise tax imposed—Deduction—Measure of tax—Rates—Additional tax imposed.
. In addition to all other taxes, licenses, or fees provided by law there is established an excise tax on the commercial possession of enhanced food fish as provided in this chapter. The tax is levied upon and shall be collected from the owner of the enhanced food fish whose possession constitutes the taxable event. The taxable event is the first possession in Washington by an owner after the enhanced food fish has been landed. Processing and handling of enhanced food fish by a person who is not the owner is not a taxable event to the processor or handler.

. A person in possession of enhanced food fish and liable to this tax may deduct from the price paid to the person from which the enhanced food fish (except oysters) are purchased an amount equal to a tax at one-half the rate levied in this section upon these products.

. The measure of the tax is the value of the enhanced food fish at the point of landing.

. The tax shall be equal to the measure of the tax multiplied by the rates for enhanced food fish as follows:

.. Puget Sound Chinook, coho, and chum salmon and anadromous game fish: Five and twenty-five one-hundredths percent;

.. Ocean waters, Columbia river, Willapa Bay, and Grays Harbor Chinook, coho, and chum salmon and anadromous game fish: Six and twenty-five one-hundredths percent;

.. Pink and sockeye salmon: Three and fifteen one-hundredths percent;

.. Other food fish and shellfish, except oysters, sea urchins, and sea cucumbers: Two and one-tenth percent;

.. Oysters: Eight one-hundredths of one percent;

.. Sea urchins: Two and one-tenth percent; and

.. Sea cucumbers: Two and one-tenth percent.

. An additional tax is imposed equal to the rate specified in RCW 82.02.030 multiplied by the tax payable under subsection (4) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2053[2017 3rd sp.s. c 8 § 53]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2593-S.SL.pdf?cite=2010%20c%20193%20§%2016[2010 c 193 § 16]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1958.SL.pdf?cite=2005%20c%20110%20§%203[2005 c 110 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1361.SL.pdf?cite=2001%20c%20320%20§%209[2001 c 320 § 9]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5658-S2.SL.pdf?cite=1999%20c%20126%20§%203[1999 c 126 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5980-S.SL.pdf?cite=1993%20sp.s.%20c%2017%20§%2012[1993 sp.s. c 17 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c413.pdf?cite=1985%20c%20413%20§%202[1985 c 413 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex2c3.pdf?cite=1983%202nd%20ex.s.%20c%203%20§%2017[1983 2nd ex.s. c 3 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c284.pdf?cite=1983%20c%20284%20§%206[1983 c 284 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c35.pdf?cite=1982%201st%20ex.s.%20c%2035%20§%2010[1982 1st ex.s. c 35 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c98.pdf?cite=1980%20c%2098%20§%202[1980 c 98 § 2]; ]

== 82.27.025 - Tax preferences—Expiration dates.
See RCW 82.32.805 for the expiration date of new tax preferences for the tax imposed under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5882-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%2013%20§%201716[2013 2nd sp.s. c 13 § 1716]; ]

== 82.27.030 - Exemptions.
The tax imposed by RCW 82.27.020 shall not apply to: (1) Enhanced food fish originating outside the state which enters the state as (a) frozen enhanced food fish or (b) enhanced food fish packaged for retail sales; (2) the growing, processing, or dealing with food fish or shellfish which are raised from eggs, fry, or larvae and which are under the physical control of the grower at all times until being sold or harvested; and (3) food fish, shellfish, anadromous game fish, and by-products or parts of food fish shipped from outside the state which enter the state, except as provided in RCW 82.27.010, provided the taxpayer must have documentation showing shipping origination of fish exempt under this subsection to qualify for exemption. Such documentation includes, but is not limited to fish tickets, bills of lading, invoices, or other documentation required to be kept by governmental agencies.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1102.SL.pdf?cite=1995%202nd%20sp.s.%20c%207%20§%201[1995 2nd sp.s. c 7 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c413.pdf?cite=1985%20c%20413%20§%203[1985 c 413 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c98.pdf?cite=1980%20c%2098%20§%203[1980 c 98 § 3]; ]

== 82.27.040 - Credit for taxes paid to another taxing authority.
A credit shall be allowed against the tax imposed by RCW 82.27.020 upon enhanced food fish with respect to any tax previously paid on that same enhanced food fish to any other legally established taxing authority. To qualify for a credit, the owner of the enhanced food fish must have documentation showing a tax was paid in another jurisdiction.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c413.pdf?cite=1985%20c%20413%20§%204[1985 c 413 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c98.pdf?cite=1980%20c%2098%20§%204[1980 c 98 § 4]; ]

== 82.27.050 - Application of excise taxes' administrative provisions and definitions.
All of the provisions of chapters 82.02 and 82.32 RCW shall be applicable and have full force and effect with respect to taxes imposed under this chapter. The meaning attributed to words and phrases in chapter 82.04 RCW, insofar as applicable, shall have full force and effect with respect to taxes imposed under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c98.pdf?cite=1980%20c%2098%20§%205[1980 c 98 § 5]; ]

== 82.27.060 - Payment of tax—Remittance—Returns.
The taxes levied by this chapter shall be due for payment monthly and remittance therefor shall be made within twenty-five days after the end of the month in which the taxable activity occurs. The taxpayer on or before the due date shall make out a signed return, setting out such information as the department of revenue may require, including the gross measure of the tax, any deductions, credits, or exemptions claimed, and the amount of tax due for the preceding monthly period, which amount shall be transmitted to the department along with the return.

The department may relieve any taxpayer from the obligation of filing a monthly return and may require the return to cover other periods, but in no event may periodic returns be filed for a period greater than one year. In such cases tax payments are due on or before the last day of the month next succeeding the end of the period covered by the return.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2671.SL.pdf?cite=2006%20c%20256%20§%203[2006 c 256 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2269.SL.pdf?cite=2003%201st%20sp.s.%20c%2013%20§%2010[2003 1st sp.s. c 13 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c214.pdf?cite=1990%20c%20214%20§%201[1990 c 214 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c98.pdf?cite=1980%20c%2098%20§%206[1980 c 98 § 6]; ]

== 82.27.070 - Deposit of taxes.
All taxes collected by the department of revenue under this chapter shall be deposited in the state general fund except for the following:

. The excise tax on anadromous game fish is deposited in the fish, wildlife, and conservation account created in RCW 77.12.170(3).

. The excise tax on ocean waters, Columbia river, Willapa Bay, and Grays Harbor chinook, coho, and chum salmon is deposited as follows:

.. The equivalent of five and twenty-five one-hundredths percent shall be deposited in the state general fund.

.. The equivalent of one percent shall be deposited in the fish, wildlife, and conservation account created in RCW 77.12.170(3).

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6072-S.SL.pdf?cite=2020%20c%20148%20§%2028[2020 c 148 § 28]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1597-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%208%20§%2054[2017 3rd sp.s. c 8 § 54]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2593-S.SL.pdf?cite=2010%20c%20193%20§%2017[2010 c 193 § 17]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1958.SL.pdf?cite=2005%20c%20110%20§%204[2005 c 110 § 4]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5172.SL.pdf?cite=2003%20c%2039%20§%2046[2003 c 39 § 46]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5658-S2.SL.pdf?cite=1999%20c%20126%20§%204[1999 c 126 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c36.pdf?cite=1988%20c%2036%20§%2061[1988 c 36 § 61]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c284.pdf?cite=1983%20c%20284%20§%207[1983 c 284 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c98.pdf?cite=1980%20c%2098%20§%207[1980 c 98 § 7]; ]

== 82.27.900 - Effective date—Implementation—1980 c 98.
This act shall take effect on July 1, 1980. The director of revenue is authorized to immediately take such steps as are necessary to insure that this act is implemented on its effective date.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c98.pdf?cite=1980%20c%2098%20§%2011[1980 c 98 § 11]; ]

