= 82.25 - Tax on vapor products.
:toc:

== 82.25.005 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Accessible container" means a container that is intended to be opened. The term does not mean a closed cartridge or closed container that is not intended to be opened such as a disposable e-cigarette.

. "Affiliated" means related in any way by virtue of any form or amount of common ownership, control, operation, or management.

. "Board" means the Washington state liquor and cannabis board.

. "Business" means any trade, occupation, activity, or enterprise engaged in selling or distributing vapor products in this state.

. "Distributor" mean[s] any person:

.. Engaged in the business of selling vapor products in this state who brings, or causes to be brought, into this state from outside the state any vapor products for sale;

.. Who makes, manufactures, fabricates, or stores vapor products in this state for sale in this state;

.. Engaged in the business of selling vapor products outside this state who ships or transports vapor products to retailers or consumers in this state; or

.. Engaged in the business of selling vapor products in this state who handles for sale any vapor products that are within this state but upon which tax has not been imposed.

. "Indian country" has the same meaning as provided in RCW 82.24.010.

. "Manufacturer" has the same meaning as provided in RCW 70.345.010.

. "Manufacturer's representative" means a person hired by a manufacturer to sell or distribute the manufacturer's vapor products and includes employees and independent contractors.

. "Person" means: Any individual, receiver, administrator, executor, assignee, trustee in bankruptcy, trust, estate, firm, copartnership, joint venture, club, company, joint stock company, business trust, municipal corporation, corporation, limited liability company, association, or society; the state and its departments and institutions; any political subdivision of the state of Washington; and any group of individuals acting as a unit, whether mutual, cooperative, fraternal, nonprofit, or otherwise. Except as provided otherwise in this chapter, "person" does not include any person immune from state taxation, including the United States or its instrumentalities, and federally recognized Indian tribes and enrolled tribal members, conducting business within Indian country.

. "Place of business" means any place where vapor products are sold or where vapor products are manufactured, stored, or kept for the purpose of sale, including any vessel, vehicle, airplane, or train.

. "Retail outlet" has the same meaning as provided in RCW 70.345.010.

. "Retailer" has the same meaning as provided in RCW 70.345.010.

. "Sale" has the same meaning as provided in RCW 70.345.010.

. "Taxpayer" means a person liable for the tax imposed by this chapter.

. "Vapor product" means any noncombustible product containing a solution or other consumable substance, regardless of whether it contains nicotine, which employs a mechanical heating element, battery, or electronic circuit regardless of shape or size that can be used to produce vapor from the solution or other substance, including an electronic cigarette, electronic cigar, electronic cigarillo, electronic pipe, or similar product or device. The term also includes any cartridge or other container of liquid nicotine, solution, or other consumable substance, regardless of whether it contains nicotine, that is intended to be used with or in a device that can be used to deliver aerosolized or vaporized nicotine to a person inhaling from the device and is sold for such purpose.

.. The term does not include:

... Any product approved by the United States food and drug administration for sale as a tobacco cessation product, medical device, or for other therapeutic purposes when such product is marketed and sold solely for such an approved purpose;

... Any product that will become an ingredient or component in a vapor product manufactured by a distributor; or

... Any product that meets the definition of marijuana, useable marijuana, marijuana concentrates, marijuana-infused products, cigarette, or tobacco products.

.. For purposes of this subsection (15):

... "Cigarette" has the same meaning as provided in RCW 82.24.010; and

... "Marijuana," "useable marijuana," "marijuana concentrates," and "marijuana-infused products" have the same meaning as provided in RCW 69.50.101.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20101[2019 c 445 § 101]; ]

== 82.25.010 - Tax imposed—Time of collection—Deposits.
. [Empty]
.. There is levied and collected a tax upon the sale, use, consumption, handling, possession, or distribution of all vapor products in this state as follows:

... All vapor products other than those taxed under (a)(ii) of this subsection are taxed at a rate equal to twenty-seven cents per milliliter of solution, regardless of whether it contains nicotine, and a proportionate tax at the like rate on all fractional parts of a milliliter thereof.

... Any accessible container of solution, regardless of whether it contains nicotine, that is greater than five milliliters, is taxed at a rate equal to nine cents per milliliter of solution and a proportionate tax at the like rate on all fractional parts of a milliliter thereof.

.. The tax in this section must be imposed based on the volume of the solution as listed by the manufacturer.

. [Empty]
.. The tax under this section must be collected at the time the distributor: (i) Brings, or causes to be brought, into this state from without the state vapor products for sale; (ii) makes, manufactures, fabricates, or stores vapor products in this state for sale in this state; (iii) ships or transports vapor products to retailers or consumers in this state; or (iv) handles for sale any vapor products that are within this state but upon which tax has not been imposed.

.. The tax imposed under this section must also be collected by the department from the consumer of vapor products where the tax imposed under this section was not paid by the distributor on such vapor products.

. [Empty]
.. The moneys collected under this section must be deposited as follows:

... Fifty percent into the Andy Hill cancer research endowment fund match transfer account created in RCW 43.348.080; and

... Fifty percent into the foundational public health services account created in RCW 82.25.015.

.. The funding provided under this subsection is intended to supplement and not supplant general fund investments in cancer research and foundational public health services.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20102[2019 c 445 § 102]; ]

== 82.25.015 - Foundational public health services account.
The foundational public health services account is created in the state treasury. Half of all of the moneys collected from the tax imposed on vapor products under RCW 66.44.010 must be deposited into the account. Moneys in the account may be spent only after appropriation. Moneys in the account are to be used for the following purposes:

. To fund foundational health services. In the 2019-2021 biennium, at least twelve million dollars of the funds deposited into the account must be appropriated for this purpose. Beginning in the 2021-2023 biennium, fifty percent of the funds deposited into the account, but not less than twelve million dollars each biennium, are to be used for this purpose;

. To fund tobacco, vapor product, and nicotine control and prevention, and other substance use prevention and education. Beginning in the 2021-2023 biennium, seventeen percent of the funds deposited into the account are to be used for this purpose;

. To support increased access and training of public health professionals at public health programs at accredited public institutions of higher education in Washington. Beginning in the 2021-2023 biennium, five percent of the funds deposited into the account are to be used for this purpose;

. To fund enforcement by the state liquor and cannabis board of the provisions of this chapter to prevent sales of vapor products to minors and related provisions for control of marketing and product safety, provided that no more than eight percent of the funds deposited into the account may be appropriated for these enforcement purposes.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20103[2019 c 445 § 103]; ]

== 82.25.020 - Intent—Purpose.
It is the intent and purpose of this chapter to levy a tax on all vapor products sold, used, consumed, handled, possessed, or distributed within this state. It is the further intent and purpose of this chapter to impose the tax only once on all vapor products in this state. Nothing in this chapter may be construed to exempt any person taxable under any other law or under any other tax imposed under this title.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20104[2019 c 445 § 104]; ]

== 82.25.025 - Federal law preemption.
The tax imposed by RCW 82.25.010 does not apply with respect to any vapor products which under the Constitution and laws of the United States may not be made the subject of taxation by this state.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20105[2019 c 445 § 105]; ]

== 82.25.030 - Recordkeeping requirements.
. Every distributor must keep at each place of business complete and accurate records for that place of business, including itemized invoices, of vapor products held, purchased, manufactured, brought in or caused to be brought in from without the state, or shipped or transported to retailers in this state, and of all sales of vapor products made.

. These records must show the names and addresses of purchasers, the inventory of all vapor products, and other pertinent papers and documents relating to the purchase, sale, or disposition of vapor products. All invoices and other records required by this section to be kept must be preserved for a period of five years from the date of the invoices or other documents or the date of the entries appearing in the records.

. At any time during usual business hours the department, board, or its duly authorized agents or employees may enter any place of business of a distributor, without a search warrant, and inspect the premises, the records required to be kept under this chapter, and the vapor products contained therein, to determine whether or not all the provisions of this chapter are being fully complied with. If the department, board, or any of its agents or employees are denied free access or are hindered or interfered with in making such examination, the registration certificate issued under RCW 82.32.030 of the distributor at such premises are subject to revocation by the department, and any licenses issued under chapter 70.345, 82.26, or 82.24 RCW are subject to suspension or revocation by the board.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20106[2019 c 445 § 106]; ]

== 82.25.035 - Itemized invoice requirement when sold to person other than ultimate consumer.
Every person required to be licensed under chapter 70.345 RCW who sells vapor products to persons other than the ultimate consumer must render with each sale itemized invoices showing the seller's name and address, the purchaser's name and address, the date of sale, and all prices. The person must preserve legible copies of all such invoices for five years from the date of sale.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20107[2019 c 445 § 107]; ]

== 82.25.040 - Itemized invoice requirement—Retailers.
. Every retailer must procure itemized invoices of all vapor products purchased. The invoices must show the seller's name and address, the date of purchase, and all prices and discounts.

. The retailer must keep at each retail outlet copies of complete, accurate, and legible invoices for that retail outlet or place of business. All invoices required to be kept under this section must be preserved for five years from the date of purchase.

. At any time during usual business hours the department, board, or its duly authorized agents or employees may enter any retail outlet without a search warrant, and inspect the premises for invoices required to be kept under this section and the vapor products contained in the retail outlet, to determine whether or not all the provisions of this chapter are being fully complied with. If the department, board, or any of its agents or employees are denied free access or are hindered or interfered with in making the inspection, the registration certificate issued under RCW 82.32.030 of the retailer at the premises is subject to revocation by the department, and any licenses issued under chapter 70.345, 82.26, or 82.24 RCW are subject to suspension or revocation by the board.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20108[2019 c 445 § 108]; ]

== 82.25.050 - Chapter  82.32 RCW application.
All of the provisions contained in chapter 82.32 RCW not inconsistent with the provisions of this chapter have full force and application with respect to taxes imposed under the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20110[2019 c 445 § 110]; ]

== 82.25.055 - Enforcement officers.
The department must authorize, as duly authorized agents, enforcement officers of the board to enforce provisions of this chapter. These officers are not employees of the department.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20111[2019 c 445 § 111]; ]

== 82.25.060 - Invoice requirements—Rules—Liability.
. The department may by rule establish the invoice detail required under RCW 82.25.030 for a distributor and for those invoices required to be provided to retailers under RCW 82.25.040.

. If a retailer fails to keep invoices as required under RCW 82.25.040, the retailer is liable for the tax owed on any uninvoiced vapor products but not penalties and interest, except as provided in subsection (3) of this section.

. If the department finds that the nonpayment of tax by the retailer was willful or if in the case of a second or plural nonpayment of tax by the retailer, penalties and interest must be assessed in accordance with chapter 82.32 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20112[2019 c 445 § 112]; ]

== 82.25.065 - Transporting vapor products for sale—Notice.
. No person may transport or cause to be transported in this state vapor products for sale other than: (a) A licensed distributor under chapter 70.345 RCW, or a manufacturer's representative authorized to sell or distribute vapor products in this state under chapter 70.345 RCW; (b) a licensed retailer under chapter 70.345 RCW; (c) a seller with a valid delivery sale license under chapter 70.345 RCW; or (d) a person who has given notice to the board in advance of the commencement of transportation.

. When transporting vapor products for sale, the person must have in his or her actual possession, or cause to have in the actual possession of those persons transporting such vapor products on his or her behalf, invoices or delivery tickets for the vapor products, which must show the true name and address of the consignor or seller, the true name and address of the consignee or purchaser, and the quantity and brands of the vapor products being transported.

. In any case where the department or the board, or any peace officer of the state, has knowledge or reasonable grounds to believe that any vehicle is transporting vapor products in violation of this section, the department, board, or peace officer is authorized to stop the vehicle and to inspect it for contraband vapor products.

. This section does not apply to a motor carrier or freight forwarder as defined in Title 49 U.S.C. Sec. 13102 or an air carrier as defined in Title 49 U.S.C. Sec. 40102.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20113[2019 c 445 § 113]; ]

== 82.25.070 - Recordkeeping by the board.
The board must compile and maintain a current record of the names of all distributors, retailers, and delivery sales licenses under chapter 70.345 RCW and the status of their license or licenses. The information must be updated on a monthly basis and published on the board's official internet website. This information is not subject to the confidentiality provisions of RCW 82.32.330 and must be disclosed to manufacturers, distributors, retailers, and the general public upon request.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20114[2019 c 445 § 114]; ]

== 82.25.075 - Distributors and retailers—Invoices—Transportation—Additional licenses.
. No person engaged in or conducting business as a distributor or retailer in this state may:

.. Make, use, or present or exhibit to the department or the board any invoice for any of the vapor products taxed under this chapter that bears an untrue date or falsely states the nature or quantity of the goods invoiced; or

.. Fail to produce on demand of the department or the board all invoices of all the vapor products taxed under this chapter within five years prior to such demand unless the person can show by satisfactory proof that the nonproduction of the invoices was due to causes beyond the person's control.

. [Empty]
.. No person, other than a licensed distributor, retailer or delivery sales licensee, or manufacturer's representative, may transport vapor products for sale in this state for which the taxes imposed under this chapter have not been paid unless:

... Notice of the transportation has been given as required under RCW 82.25.065;

... The person transporting the vapor products actually possesses invoices or delivery tickets showing the true name and address of the consignor or seller, the true name and address of the consignee or purchaser, and the quantity and brands of vapor products being transported; and

... The vapor products are consigned to or purchased by a person in this state who is licensed under chapter 70.345 RCW.

.. A violation of this subsection (2) is a gross misdemeanor.

. Any person licensed under chapter 70.345 RCW as a distributor, and any person licensed under chapter 70.345 RCW as a retailer, may not operate in any other capacity unless the additional appropriate license is first secured, except as otherwise provided by law. A violation of this subsection (3) is a misdemeanor.

. The penalties provided in this section are in addition to any other penalties provided by law for violating the provisions of this chapter or the rules adopted under this chapter.

. This section does not apply to a motor carrier or freight forwarder as defined in Title 49 U.S.C. Sec. 13102 or an air carrier as defined in Title 49 U.S.C. Sec. 40102.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20115[2019 c 445 § 115]; ]

== 82.25.080 - Distributor and retailer license requirements.
. A retailer that obtains vapor products from an unlicensed distributor or any other person that is not licensed under chapter 70.345 RCW must be licensed both as a retailer and a distributor and is liable for the tax imposed under RCW 82.25.010 with respect to the vapor products acquired from the unlicensed person that are held for sale, handling, or distribution in this state. For the purposes of this subsection, "person" includes both persons defined in chapter 445, Laws of 2019 and any person immune from state taxation, such as the United States or its instrumentalities, and federally recognized Indian tribes and enrolled tribal members, conducting business within Indian country.

. Every distributor licensed under chapter 70.345 RCW may sell vapor products to retailers located in Washington only if the retailer has a current retailer's license under chapter 70.345 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20116[2019 c 445 § 116]; ]

== 82.25.085 - Manufacturer's representatives.
A manufacturer that has manufacturer's representatives who sell or distribute the manufacturer's vapor products in this state must provide the board a list of the names and addresses of all such representatives and must ensure that the list provided to the board is kept current. A manufacturer's representative is not authorized to distribute or sell vapor products in this state unless the manufacturer that hired the representative has a valid distributor's license under chapter 70.345 RCW and that manufacturer provides the board a current list of all of its manufacturer's representatives as required by this section. A manufacturer's representative must carry a copy of the distributor's license of the manufacturer that hired the representative at all times when selling or distributing the manufacturer's vapor products.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20117[2019 c 445 § 117]; ]

== 82.25.090 - License and notice requirement violations—Seizure and forfeiture.
. Any vapor products in the possession of a person selling vapor products in this state acting as a distributor or retailer and who is not licensed as required under chapter 70.345 RCW, or a person who is selling vapor products in violation of RCW 82.24.550(6), may be seized without a warrant by any agent of the department, agent of the board, or law enforcement officer of this state. Any vapor products seized under this subsection are deemed forfeited.

. Any vapor products in the possession of a person who is not a licensed distributor, delivery seller, manufacturer's representative, or retailer and who transports vapor products for sale without having provided notice to the board required under RCW 82.25.065, or without invoices or delivery tickets showing the true name and address of the consignor or seller, the true name and address of the consignee or purchaser, and the quantity and brands of vapor products being transported may be seized and are subject to forfeiture.

. All conveyances, including aircraft, vehicles, or vessels that are used, or intended for use to transport, or in any manner to facilitate the transportation, for the purpose of sale or receipt of vapor products under subsection (2) of this section, may be seized and are subject to forfeiture except:

.. A conveyance used by any person as a common or contract carrier having in actual possession invoices or delivery tickets showing the true name and address of the consignor or seller, the true name of the consignee or purchaser, and the quantity and brands of the vapor products transported, unless it appears that the owner or other person in charge of the conveyance is a consenting party or privy to a violation of this chapter;

.. A conveyance subject to forfeiture under this section by reason of any act or omission of which the owner establishes to have been committed or omitted without his or her knowledge or consent; or

.. A conveyance encumbered by a bona fide security interest if the secured party neither had knowledge of nor consented to the act or omission.

. Property subject to forfeiture under subsections (2) and (3) of this section may be seized by any agent of the department, the board, or law enforcement officer of this state upon process issued by any superior court or district court having jurisdiction over the property. Seizure without process may be made if:

.. The seizure is incident to an arrest or a search warrant or an inspection under an administrative inspection warrant; or

.. The department, board, or law enforcement officer has probable cause to believe that the property was used or is intended to be used in violation of this chapter and exigent circumstances exist making procurement of a search warrant impracticable.

. This section may not be construed to require the seizure of vapor products if the department's agent, board's agent, or law enforcement officer reasonably believes that the vapor products are possessed for personal consumption by the person in possession of the vapor products.

. Any vapor products seized by a law enforcement officer must be turned over to the board as soon as practicable.

. This section does not apply to a motor carrier or freight forwarder as defined in Title 49 U.S.C. Sec. 13102 or an air carrier as defined in Title 49 U.S.C. Sec. 40102.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20118[2019 c 445 § 118]; ]

== 82.25.095 - Seizure and forfeiture procedures.
. In all cases of seizure of any vapor products made subject to forfeiture under this chapter, the department or board must proceed as provided in RCW 82.24.135.

. When vapor products are forfeited under this chapter, the department or board may:

.. Retain the property for official use or upon application by any law enforcement agency of this state, another state, or the District of Columbia, or of the United States for the exclusive use of enforcing this chapter or the laws of any other state or the District of Columbia or of the United States; or

.. Sell the vapor products at public auction to the highest bidder after due advertisement. Before delivering any of the goods to the successful bidder, the department or board must require the purchaser to pay the proper amount of any tax due. The proceeds of the sale must be first applied to the payment of all proper expenses of any investigation leading to the seizure and of the proceedings for forfeiture and sale, including expenses of seizure, maintenance of custody, advertising, and court costs. The balance of the proceeds and all money must be deposited in the general fund of the state. Proper expenses of investigation include costs incurred by any law enforcement agency or any federal, state, or local agency.

. The department or the board may return any property seized under the provisions of this chapter when it is shown that there was no intention to violate the provisions of this chapter. When any property is returned under this section, the department or the board may return the property to the parties from whom they were seized if and when such parties have paid the proper amount of tax due under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20119[2019 c 445 § 119]; ]

== 82.25.100 - Violations of chapter—Affidavit—Search warrants.
When the department or the board has good reason to believe that any of the vapor products taxed under this chapter are being kept, sold, offered for sale, or given away in violation of the provisions of this chapter, it may make affidavit of facts describing the place or thing to be searched, before any judge of any court in this state, and the judge must issue a search warrant directed to the sheriff, any deputy, police officer, or duly authorized agent of the department or the board commanding him or her diligently to search any building, room in a building, place, or vehicle as may be designated in the affidavit and search warrant, and to seize the vapor products and hold them until disposed of by law.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20120[2019 c 445 § 120]; ]

== 82.25.105 - Tax credit—Sold outside state—Returned, destroyed products—Sold to United States or an Indian tribal organization.
. [Empty]
.. Where vapor products upon which the tax imposed by this chapter has been reported and paid are shipped or transported outside this state by the distributor to a person engaged in the business of selling vapor products, to be sold by that person, or are returned to the manufacturer by the distributor or destroyed by the distributor, or are sold by the distributor to the United States or any of its agencies or instrumentalities, or are sold by the distributor to any Indian tribal organization, credit of such tax may be made to the distributor in accordance with rules prescribed by the department.

.. For purposes of this subsection (1), the following definitions apply:

... "Indian distributor" means a federally recognized Indian tribe or tribal entity that would otherwise meet the definition of "distributor" under RCW 82.25.005, if federally recognized Indian tribes and tribal entities were not excluded from the definition of "person" in RCW 82.25.005.

... "Indian retailer" means a federally recognized Indian tribe or tribal entity that would otherwise meet the definition of "retailer" under RCW 82.25.005, if federally recognized Indian tribes and tribal entities were not excluded from the definition of "person" in RCW 82.25.005.

... "Indian tribal organization" means a federally recognized Indian tribe, or tribal entity, and includes an Indian distributor or retailer that is owned by an Indian who is an enrolled tribal member conducting business under tribal license or similar tribal approval within Indian country.

. Credit allowed under this section must be determined based on the tax rate in effect for the period for which the tax imposed by this chapter, for which a credit is sought, was paid.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20121[2019 c 445 § 121]; ]

== 82.25.110 - Preexisting inventories.
. Preexisting inventories of vapor products are subject to the tax imposed in RCW 82.25.010. All retailers and other distributors must report the tax due under RCW 82.25.010 on preexisting inventories of vapor products on a form, as prescribed by the department, on or before October 31, 2019, and the tax due on such preexisting inventories must be paid on or before January 31, 2020.

. Reports under subsection (1) of this section not filed with the department by October 31, 2019, are subject to a late filing penalty equal to the greater of two hundred fifty dollars or ten percent of the tax due under RCW 82.25.010 on the taxpayer's preexisting inventories.

. The department must notify the taxpayer of the amount of tax due under RCW 82.25.010 on preexisting inventories, which is subject to applicable penalties under RCW 82.32.090 (2) through (7) if unpaid after January 31, 2020. Amounts due in accordance with this section are not considered to be substantially underpaid for the purposes of RCW 82.32.090(2).

. Interest, at the rate provided in RCW 82.32.050(2), must be computed daily beginning February 1, 2020, on any remaining tax due under RCW 82.25.010 on preexisting inventories until paid.

. A retailer required to comply with subsection (1) of this section is not required to obtain a distributor license as otherwise required under chapter 70.345 RCW as long as the retailer:

.. Does not sell vapor products other than to ultimate consumers; and

.. Does not meet the definition of "distributor" in RCW 82.25.005 other than with respect to the sale of that retailer's preexisting inventory of vapor products.

. Taxes may not be collected under RCW 82.25.010 from consumers with respect to any vapor products acquired before October 1, 2019.

. For purposes of this section, "preexisting inventory" means an inventory of vapor products located in this state as of the moment that RCW 82.25.010 takes effect and held by a distributor for sale, handling, or distribution in this state.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20122[2019 c 445 § 122]; ]

== 82.25.900 - Conflict with federal requirements—2019 c 445.
If any part of this act is found to be in conflict with federal requirements that are a prescribed condition to the allocation of federal funds to the state, the conflicting part of this act is inoperative solely to the extent of the conflict and with respect to the agencies directly affected, and this finding does not affect the operation of the remainder of this act in its application to the agencies concerned. Rules adopted under this act must meet federal requirements that are a necessary condition to the receipt of federal funds by the state.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20407[2019 c 445 § 407]; ]

== 82.25.901 - Effective date—2019 c 445.
This act takes effect October 1, 2019.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20409[2019 c 445 § 409]; ]

