= 82.26 - Tax on tobacco products.
:toc:

== 82.26.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Actual price" means the total amount of consideration for which tobacco products are sold, valued in money, whether received in money or otherwise, including any charges by the seller necessary to complete the sale such as charges for delivery, freight, transportation, or handling.

. "Affiliated" means related in any way by virtue of any form or amount of common ownership, control, operation, or management.

. "Board" means the liquor and cannabis board.

. "Business" means any trade, occupation, activity, or enterprise engaged in for the purpose of selling or distributing tobacco products in this state.

. "Cigar" means a roll for smoking that is of any size or shape and that is made wholly or in part of tobacco, irrespective of whether the tobacco is pure or flavored, adulterated or mixed with any other ingredient, if the roll has a wrapper made wholly or in greater part of tobacco. "Cigar" does not include a cigarette.

. "Cigarette" has the same meaning as in RCW 82.24.010.

. "Department" means the department of revenue.

. "Distributor" means (a) any person engaged in the business of selling tobacco products in this state who brings, or causes to be brought, into this state from without the state any tobacco products for sale, (b) any person who makes, manufactures, fabricates, or stores tobacco products in this state for sale in this state, (c) any person engaged in the business of selling tobacco products without this state who ships or transports tobacco products to retailers in this state, to be sold by those retailers, (d) any person engaged in the business of selling tobacco products in this state who handles for sale any tobacco products that are within this state but upon which tax has not been imposed.

. "Indian country" means the same as defined in chapter 82.24 RCW.

. "Little cigar" means a cigar that has a cellulose acetate integrated filter.

. "Manufacturer" means a person who manufactures and sells tobacco products.

. "Manufacturer's representative" means a person hired by a manufacturer to sell or distribute the manufacturer's tobacco products, and includes employees and independent contractors.

. "Moist snuff" means tobacco that is finely cut, ground, or powdered; is not for smoking; and is intended to be placed in the oral, but not the nasal, cavity.

. "Person" means any individual, receiver, administrator, executor, assignee, trustee in bankruptcy, trust, estate, firm, copartnership, joint venture, club, company, joint stock company, business trust, municipal corporation, the state and its departments and institutions, political subdivision of the state of Washington, corporation, limited liability company, association, society, any group of individuals acting as a unit, whether mutual, cooperative, fraternal, nonprofit, or otherwise. The term excludes any person immune from state taxation, including the United States or its instrumentalities, and federally recognized Indian tribes and enrolled tribal members, conducting business within Indian country.

. "Place of business" means any place where tobacco products are sold or where tobacco products are manufactured, stored, or kept for the purpose of sale, including any vessel, vehicle, airplane, train, or vending machine.

. "Retail outlet" means each place of business from which tobacco products are sold to consumers.

. "Retailer" means any person engaged in the business of selling tobacco products to ultimate consumers.

. [Empty]
.. "Sale" means any transfer, exchange, or barter, in any manner or by any means whatsoever, for a consideration, and includes and means all sales made by any person.

.. The term "sale" includes a gift by a person engaged in the business of selling tobacco products, for advertising, promoting, or as a means of evading the provisions of this chapter.

. [Empty]
.. "Taxable sales price" means:

... In the case of a taxpayer that is not affiliated with the manufacturer, distributor, or other person from whom the taxpayer purchased tobacco products, the actual price for which the taxpayer purchased the tobacco products;

... In the case of a taxpayer that purchases tobacco products from an affiliated manufacturer, affiliated distributor, or other affiliated person, and that sells those tobacco products to unaffiliated distributors, unaffiliated retailers, or ultimate consumers, the actual price for which that taxpayer sells those tobacco products to unaffiliated distributors, unaffiliated retailers, or ultimate consumers;

... In the case of a taxpayer that sells tobacco products only to affiliated distributors or affiliated retailers, the price, determined as nearly as possible according to the actual price, that other distributors sell similar tobacco products of like quality and character to unaffiliated distributors, unaffiliated retailers, or ultimate consumers;

... In the case of a taxpayer that is a manufacturer selling tobacco products directly to ultimate consumers, the actual price for which the taxpayer sells those tobacco products to ultimate consumers;

.. In the case of a taxpayer that has acquired tobacco products under a sale as defined in subsection (18)(b) of this section, the price, determined as nearly as possible according to the actual price, that the taxpayer or other distributors sell the same tobacco products or similar tobacco products of like quality and character to unaffiliated distributors, unaffiliated retailers, or ultimate consumers; or

.. In any case where (a)(i) through (v) of this subsection do not apply, the price, determined as nearly as possible according to the actual price, that the taxpayer or other distributors sell the same tobacco products or similar tobacco products of like quality and character to unaffiliated distributors, unaffiliated retailers, or ultimate consumers.

.. For purposes of (a)(i) and (ii) of this subsection only, "person" includes both persons as defined in subsection (14) of this section and any person immune from state taxation, including the United States or its instrumentalities, and federally recognized Indian tribes and enrolled tribal members, conducting business within Indian country.

.. The department may adopt rules regarding the determination of taxable sales price under this subsection.

. "Taxpayer" means a person liable for the tax imposed by this chapter.

. "Tobacco products" means cigars, cheroots, stogies, periques, granulated, plug cut, crimp cut, ready rubbed, and other smoking tobacco, snuff, snuff flour, cavendish, plug and twist tobacco, fine-cut and other chewing tobaccos, shorts, refuse scraps, clippings, cuttings and sweepings of tobacco, and other kinds and forms of tobacco, prepared in such manner as to be suitable for chewing or smoking in a pipe or otherwise, or both for chewing and smoking, and any other product, regardless of form, that contains tobacco and is intended for human consumption or placement in the oral or nasal cavity or absorption into the human body by any other means, but does not include cigarettes as defined in RCW 82.24.010.

. "Unaffiliated distributor" means a distributor that is not affiliated with the manufacturer, distributor, or other person from whom the distributor has purchased tobacco products.

. "Unaffiliated retailer" means a retailer that is not affiliated with the manufacturer, distributor, or other person from whom the retailer has purchased tobacco products.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5402.SL.pdf?cite=2020%20c%20139%20§%2031[2020 c 139 § 31]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2493-S.SL.pdf?cite=2010%201st%20sp.s.%20c%2022%20§%204[2010 1st sp.s. c 22 § 4]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6097.SL.pdf?cite=2005%20c%20180%20§%202[2005 c 180 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6591.SL.pdf?cite=2002%20c%20325%20§%201[2002 c 325 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1359.SL.pdf?cite=1995%20c%20278%20§%2016[1995 c 278 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%2070[1975 1st ex.s. c 278 § 70]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2082.26.010[1961 c 15 § 82.26.010]; prior:  1959 ex.s. c 5 § 11; ]

== 82.26.020 - Tax imposed—Deposited into the general fund.
. There is levied and collected a tax upon the sale, handling, or distribution of all tobacco products in this state at the following rate:

.. For cigars except little cigars, ninety-five percent of the taxable sales price of cigars, not to exceed sixty-five cents per cigar;

.. For all tobacco products except those covered under separate provisions of this subsection, ninety-five percent of the taxable sales price. The tax imposed on a product under this subsection must be reduced by fifty percent if that same product is issued a modified risk tobacco product order by the secretary of the United States department of health and human services pursuant to Title 21 U.S.C. Sec. 387k(g)(1), or by twenty-five percent if that same product is issued a modified risk tobacco product order by the secretary of the United States department of health and human services pursuant to Title 21 U.S.C. Sec. 387k(g)(2). The tax reduction applies during the period the modified risk tobacco product order is in effect;

.. For moist snuff, as established in this subsection (1)(c) and computed on the net weight listed by the manufacturer:

... On each single unit consumer-sized can or package whose net weight is one and two-tenths ounces or less, a rate per single unit that is equal to the greater of 2.526 dollars or eighty-three and one-half percent of the cigarette tax under chapter 82.24 RCW multiplied by twenty; or

... On each single unit consumer-sized can or package whose net weight is more than one and two-tenths ounces, a proportionate tax at the rate established in (c)(i) of this subsection (1) on each ounce or fractional part of an ounce; and

.. For little cigars, an amount per cigar equal to the cigarette tax under chapter 82.24 RCW.

. Taxes under this section must be imposed at the time the distributor (a) brings, or causes to be brought, into this state from without the state tobacco products for sale, (b) makes, manufactures, fabricates, or stores tobacco products in this state for sale in this state, (c) ships or transports tobacco products to retailers in this state, to be sold by those retailers, or (d) handles for sale any tobacco products that are within this state but upon which tax has not been imposed.

. The moneys collected under this section must be deposited into the state general fund.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20404[2019 c 445 § 404]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2493-S.SL.pdf?cite=2010%201st%20sp.s.%20c%2022%20§%205[2010 1st sp.s. c 22 § 5]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5073-S.SL.pdf?cite=2009%20c%20479%20§%2070[2009 c 479 § 70]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6097.SL.pdf?cite=2005%20c%20180%20§%203[2005 c 180 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6591.SL.pdf?cite=2002%20c%20325%20§%202[2002 c 325 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5304-S2.SL.pdf?cite=1993%20c%20492%20§%20309[1993 c 492 § 309]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex2c3.pdf?cite=1983%202nd%20ex.s.%20c%203%20§%2016[1983 2nd ex.s. c 3 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c35.pdf?cite=1982%201st%20ex.s.%20c%2035%20§%209[1982 1st ex.s. c 35 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%2071[1975 1st ex.s. c 278 § 71]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c299.pdf?cite=1971%20ex.s.%20c%20299%20§%2077[1971 ex.s. c 299 § 77]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c173.pdf?cite=1965%20ex.s.%20c%20173%20§%2025[1965 ex.s. c 173 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2082.26.020[1961 c 15 § 82.26.020]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959ex1c5.pdf?cite=1959%20ex.s.%20c%205%20§%2012[1959 ex.s. c 5 § 12]; ]

== 82.26.027 - Tax preferences—Expiration dates.
See RCW 82.32.805 for the expiration date of new tax preferences for the tax imposed under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5882-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%2013%20§%201715[2013 2nd sp.s. c 13 § 1715]; ]

== 82.26.030 - Legislative intent—Purpose.
It is the intent and purpose of this chapter to levy a tax on all tobacco products sold, used, consumed, handled, or distributed within this state and to collect the tax from the distributor as defined in RCW 82.26.010. It is the further intent and purpose of this chapter to impose the tax once, and only once, on all tobacco products for sale in this state, but nothing in this chapter may be construed to exempt any person taxable under any other law or under any other tax imposed under Title 82 RCW. It is the further intent and purpose of this chapter that the distributor who first possesses the tobacco product in this state is the distributor liable for the tax and that (1) for moist snuff the tax will be based on the net weight listed by the manufacturer and (2) in most other instances the tax will be based on the actual price that the distributor paid for the tobacco product, unless the distributor is affiliated with the seller.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2493-S.SL.pdf?cite=2010%201st%20sp.s.%20c%2022%20§%207[2010 1st sp.s. c 22 § 7]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6097.SL.pdf?cite=2005%20c%20180%20§%201[2005 c 180 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6591.SL.pdf?cite=2002%20c%20325%20§%204[2002 c 325 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2082.26.030[1961 c 15 § 82.26.030]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959ex1c5.pdf?cite=1959%20ex.s.%20c%205%20§%2013[1959 ex.s. c 5 § 13]; ]

== 82.26.040 - When tax not applicable under laws of United States.
The tax imposed by RCW 82.26.020 shall not apply with respect to any tobacco products which under the Constitution and laws of the United States may not be made the subject of taxation by this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2082.26.040[1961 c 15 § 82.26.040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959ex1c5.pdf?cite=1959%20ex.s.%20c%205%20§%2014[1959 ex.s. c 5 § 14]; ]

== 82.26.060 - Books and records to be preserved—Entry and inspection by department or board.
. Every distributor must keep at each place of business complete and accurate records for that place of business, including itemized invoices, of tobacco products held, purchased, manufactured, brought in or caused to be brought in from without the state, or shipped or transported to retailers in this state, and of all sales of tobacco products made.

. These records must show the names and addresses of purchasers, the inventory of all tobacco products, and other pertinent papers and documents relating to the purchase, sale, or disposition of tobacco products. All invoices and other records required by this section to be kept must be preserved for a period of five years from the date of the invoices or other documents or the date of the entries appearing in the records.

. At any time during usual business hours the department, board, or its duly authorized agents or employees, may enter any place of business of a distributor, without a search warrant, and inspect the premises, the records required to be kept under this chapter, and the tobacco products contained therein, to determine whether or not all the provisions of this chapter are being fully complied with. If the department, board, or any of its agents or employees, are denied free access or are hindered or interfered with in making such examination, the registration certificate issued under RCW 82.32.030 of the distributor at such premises is subject to revocation, and any licenses issued under this chapter or chapter 82.24 or 70.345 RCW are subject to suspension or revocation, by the department or board.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20205[2019 c 445 § 205]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1435-S.SL.pdf?cite=2009%20c%20154%20§%203[2009 c 154 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6097.SL.pdf?cite=2005%20c%20180%20§%204[2005 c 180 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%2073[1975 1st ex.s. c 278 § 73]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2082.26.060[1961 c 15 § 82.26.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959ex1c5.pdf?cite=1959%20ex.s.%20c%205%20§%2016[1959 ex.s. c 5 § 16]; ]

== 82.26.070 - Preservation of invoices of sales to other than ultimate consumer.
Every person required to be licensed under this chapter who sells tobacco products to persons other than the ultimate consumer shall render with each sale itemized invoices showing the seller's name and address, the purchaser's name and address, the date of sale, and all prices. The person shall preserve legible copies of all such invoices for five years from the date of sale.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6097.SL.pdf?cite=2005%20c%20180%20§%207[2005 c 180 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2082.26.070[1961 c 15 § 82.26.070]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959ex1c5.pdf?cite=1959%20ex.s.%20c%205%20§%2017[1959 ex.s. c 5 § 17]; ]

== 82.26.080 - Retailer invoices—Requirements—Inspection.
. Every retailer must procure itemized invoices of all tobacco products purchased. The invoices must show the seller's name and address, the date of purchase, and all prices and discounts.

. The retailer must keep at each retail outlet copies of complete, accurate, and legible invoices for that retail outlet or place of business. All invoices required to be kept under this section must be preserved for five years from the date of purchase.

. At any time during usual business hours the department, board, or its duly authorized agents or employees may enter any retail outlet without a search warrant, and inspect the premises for invoices required to be kept under this section and the tobacco products contained in the retail outlet, to determine whether or not all the provisions of this chapter are being fully complied with. If the department, board, or any of its agents or employees, are denied free access or are hindered or interfered with in making the inspection, the registration certificate issued under RCW 82.32.030 of the retailer at the premises is subject to revocation, and any licenses issued under this chapter or chapter 82.24 or 70.345 RCW are subject to suspension or revocation by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20206[2019 c 445 § 206]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6097.SL.pdf?cite=2005%20c%20180%20§%205[2005 c 180 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%2074[1975 1st ex.s. c 278 § 74]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2082.26.080[1961 c 15 § 82.26.080]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959ex1c5.pdf?cite=1959%20ex.s.%20c%205%20§%2018[1959 ex.s. c 5 § 18]; ]

== 82.26.090 - Records of shipments, deliveries from public warehouse of first destination—Preservation—Inspection.
Records of all deliveries or shipments of tobacco products from any public warehouse of first destination in this state shall be kept by the warehouse and be available to the department of revenue for inspection. They shall show the name and address of the consignee, the date, the quantity of tobacco products delivered, and such other information as the department may require. These records shall be preserved for five years from the date of delivery of the tobacco products.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%2075[1975 1st ex.s. c 278 § 75]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2082.26.090[1961 c 15 § 82.26.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959ex1c5.pdf?cite=1959%20ex.s.%20c%205%20§%2019[1959 ex.s. c 5 § 19]; ]

== 82.26.100 - Reports and returns.
Every taxpayer shall report and make returns as provided in RCW 82.32.045.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6097.SL.pdf?cite=2005%20c%20180%20§%208[2005 c 180 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%20218[1983 c 3 § 218]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2082.26.100[1961 c 15 § 82.26.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959ex1c5.pdf?cite=1959%20ex.s.%20c%205%20§%2020[1959 ex.s. c 5 § 20]; ]

== 82.26.105 - Inspection of books, documents, or records of carriers.
. For the purposes of obtaining information concerning any matter relating to the administration or enforcement of this chapter, the department, the board, or any of its agents may inspect the books, documents, or records of any person transporting tobacco products for sale to any person or entity in the state, and books, documents, or records containing any information relating to the transportation or possession of tobacco products for sale in the possession of a specific common carrier as defined in RCW 81.80.010 doing business in this state, or books, documents, and records of vehicle rental agencies whose vehicles are being rented for the purpose of transporting contraband tobacco products.

. If a person neglects or refuses to produce and submit for inspection any book, record, or document as required by this section when requested to do so by the department, the board, or its agent, then the department or the board may seek an order in superior court compelling production of the books, records, or documents.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5551.SL.pdf?cite=2007%20c%20221%20§%203[2007 c 221 § 3]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6097.SL.pdf?cite=2005%20c%20180%20§%206[2005 c 180 § 6]; ]

== 82.26.110 - When credit may be obtained for tax paid.
. [Empty]
.. Where tobacco products upon which the tax imposed by this chapter has been reported and paid are shipped or transported outside this state by the distributor to a person engaged in the business of selling tobacco products, to be sold by that person, or are returned to the manufacturer by the distributor or destroyed by the distributor, or are sold by the distributor to the United States or any of its agencies or instrumentalities, or are sold by the distributor to any Indian tribal organization, credit of such tax may be made to the distributor in accordance with rules prescribed by the department.

.. For purposes of this subsection, the following definitions apply:

... "Indian distributor" means a federally recognized Indian tribe or tribal entity that would otherwise meet the definition of distributor under RCW 82.26.010, if federally recognized Indian tribes and tribal entities were not excluded from the definition of person in RCW 82.26.010.

... "Indian retailer" means a federally recognized Indian tribe or tribal entity that would otherwise meet the definition of retailer under RCW 82.26.010, if federally recognized Indian tribes and tribal entities were not excluded from the definition of person in RCW 82.26.010.

... "Indian tribal organization" means a federally recognized Indian tribe, or tribal entity, and includes an Indian distributor or retailer that is owned by an Indian who is an enrolled tribal member conducting business under tribal license or similar tribal approval within Indian country.

. Credit allowed under this section shall be determined based on the tax rate in effect for the period for which the tax imposed by this chapter, for which a credit is sought, was paid.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5551.SL.pdf?cite=2007%20c%20221%20§%204[2007 c 221 § 4]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6097.SL.pdf?cite=2005%20c%20180%20§%209[2005 c 180 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%2076[1975 1st ex.s. c 278 § 76]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2082.26.110[1961 c 15 § 82.26.110]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959ex1c5.pdf?cite=1959%20ex.s.%20c%205%20§%2021[1959 ex.s. c 5 § 21]; ]

== 82.26.120 - Administration.
All of the provisions contained in chapter 82.32 RCW shall have full force and application with respect to taxes imposed under the provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963ex1c28.pdf?cite=1963%20ex.s.%20c%2028%20§%205[1963 ex.s. c 28 § 5]; ]

== 82.26.121 - Enforcement—Appointment of officers of liquor and cannabis board.
The department must appoint, as duly authorized agents, enforcement officers of the liquor and cannabis board to enforce provisions of this chapter. These officers are not considered employees of the department.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5402.SL.pdf?cite=2020%20c%20139%20§%2032[2020 c 139 § 32]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2272-S.SL.pdf?cite=1997%20c%20420%20§%2011[1997 c 420 § 11]; ]

== 82.26.130 - Invoices—Nonpayment—Penalties and interest.
. The department must by rule establish the invoice detail required under RCW 82.26.060 for a distributor under RCW 82.26.010(8)(d) and for those invoices required to be provided to retailers under RCW 82.26.070.

. If a retailer fails to keep invoices as required under chapter 82.32 RCW, the retailer is liable for the tax owed on any uninvoiced tobacco products but not penalties and interest, except as provided in subsection (3) of this section.

. If the department finds that the nonpayment of tax by the retailer was willful or if in the case of a second or plural nonpayment of tax by the retailer, penalties and interest must be assessed in accordance with chapter 82.32 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5402.SL.pdf?cite=2020%20c%20139%20§%2033[2020 c 139 § 33]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6591.SL.pdf?cite=2002%20c%20325%20§%205[2002 c 325 § 5]; ]

== 82.26.140 - Transport of tobacco products—Requirements—Vehicle inspection.
. No person other than (a) a licensed distributor in the distributor's own vehicle, a manufacturer's representative authorized to sell or distribute tobacco products in this state under RCW 82.26.210, or a licensed retailer in the retailer's own vehicle, or (b) a person who has given notice to the board in advance of the commencement of transportation shall transport or cause to be transported in this state tobacco products for sale.

. When transporting tobacco products for sale, the person shall have in his or her actual possession, or cause to have in the actual possession of those persons transporting such tobacco products on his or her behalf, invoices or delivery tickets for the tobacco products, which shall show the true name and address of the consignor or seller, the true name and address of the consignee or purchaser, and the quantity and brands of the tobacco products being transported.

. In any case where the department or the board, or any peace officer of the state, has knowledge or reasonable grounds to believe that any vehicle is transporting tobacco products in violation of this section, the department, the board, or peace officer, is authorized to stop the vehicle and to inspect it for contraband tobacco products.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6097.SL.pdf?cite=2005%20c%20180%20§%2010[2005 c 180 § 10]; ]

== 82.26.150 - Distributor's license, retailer's license—Application—Approval—Display.
. The licenses issuable by the board under this chapter are as follows:

.. A distributor's license; and

.. A retailer's license.

. Application for the licenses must be made through the business licensing system under chapter 19.02 RCW. The board may adopt rules regarding the regulation of the licenses. The board may refuse to issue any license under this chapter if the board has reasonable cause to believe that the applicant has willfully withheld information requested for the purpose of determining the eligibility of the applicant to receive a license, or if the board has reasonable cause to believe that information submitted in the application is false or misleading or is not made in good faith. In addition, for the purpose of reviewing an application for a distributor's license or retailer's license and for considering the denial, suspension, or revocation of any such license, the board may consider criminal conduct of the applicant, including an administrative violation history record with the board and a criminal history record information check within the previous five years, in any state, tribal, or federal jurisdiction in the United States, its territories, or possessions, and the provisions of RCW 9.95.240 and chapter 9.96A RCW do not apply to such cases. The board may, in its discretion, issue or refuse to issue the distributor's license or retailer's license, subject to the provisions of RCW 82.26.220.

. No person may qualify for a distributor's license or a retailer's license under this section without first undergoing a criminal background check. The background check must be performed by the board and must disclose any criminal conduct within the previous five years in any state, tribal, or federal jurisdiction in the United States, its territories, or possessions. If the applicant or licensee also has a license issued under chapter 66.24, 82.24, or 70.345 RCW, the background check done under the authority of chapter 66.24, 70.345, or 82.24 RCW satisfies the requirements of this section.

. Each license issued under this chapter expires on the business license expiration date. The license must be continued annually if the licensee has paid the required fee and complied with all the provisions of this chapter and the rules of the board adopted pursuant to this chapter.

. Each license and any other evidence of the license required under this chapter must be exhibited in each place of business for which it is issued and in the manner required for the display of a business license.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20207[2019 c 445 § 207]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1568-S.SL.pdf?cite=2013%20c%20144%20§%2052[2013 c 144 § 52]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1435-S.SL.pdf?cite=2009%20c%20154%20§%204[2009 c 154 § 4]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6097.SL.pdf?cite=2005%20c%20180%20§%2011[2005 c 180 § 11]; ]

== 82.26.160 - Distributor's license—Application fees.
. A fee of six hundred fifty dollars shall accompany each distributor's license application or license renewal application. If a distributor sells or intends to sell tobacco products at two or more places of business, whether established or temporary, a separate license with a license fee of one hundred fifteen dollars shall be required for each additional place of business.

. The fees imposed under subsection (1) of this section do not apply to any person applying for a distributor's license or for renewal of a distributor's license if the person has a valid wholesaler's license under RCW 82.24.510 for the place of business associated with the distributor's license application or license renewal application.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6097.SL.pdf?cite=2005%20c%20180%20§%2012[2005 c 180 § 12]; ]

== 82.26.170 - Retailer's license—Application fee.
. A fee of one hundred seventy-five dollars shall accompany each retailer's license application or license renewal application. A separate license is required for each separate location at which the retailer operates.

. The fee imposed under subsection (1) of this section does not apply to any person applying for a retailer's license or for renewal of a retailer's license if the person has a valid retailer's license under RCW 82.24.510 for the place of business associated with the retailer's license application or renewal application.

. A retailer applying for, or renewing, both a retailer's license under RCW 82.26.170 and a vapor products retailer's license under RCW 70.345.020 may pay a combined application fee of two hundred fifty dollars for both licenses.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=2016%20sp.s.%20c%2038%20§%2028[2016 sp.s. c 38 § 28]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6097.SL.pdf?cite=2005%20c%20180%20§%2013[2005 c 180 § 13]; ]

== 82.26.180 - Board web site listing distributors and retailers.
The board shall compile and maintain a current record of the names of all distributors and retailers licensed under this chapter and the status of their license or licenses. The information must be updated on a monthly basis and published on the board's official internet web site. This information is not subject to the confidentiality provisions of RCW 82.32.330 and shall be disclosed to manufacturers, distributors, retailers, and the general public upon request.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1435-S.SL.pdf?cite=2009%20c%20154%20§%205[2009 c 154 § 5]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6097.SL.pdf?cite=2005%20c%20180%20§%2015[2005 c 180 § 15]; ]

== 82.26.190 - Distributors and retailers—Valid license required—Violations—Penalties.
. [Empty]
.. No person may engage in or conduct business as a distributor or retailer in this state after September 30, 2005, without a valid license issued under this chapter. Any person who sells tobacco products to persons other than ultimate consumers or who meets the definition of distributor under RCW 82.26.010(8)(d) must obtain a distributor's license under this chapter. Any person who sells tobacco products to ultimate consumers must obtain a retailer's license under this chapter.

.. A violation of this subsection (1) is punishable as a class C felony according to chapter 9A.20 RCW.

. [Empty]
.. No person engaged in or conducting business as a distributor or retailer in this state may:

... Refuse to allow the department or the board, on demand, to make a full inspection of any place of business where any of the tobacco products taxed under this chapter are sold, stored, or handled, or otherwise hinder or prevent such inspection;

... Make, use, or present or exhibit to the department or the board any invoice for any of the tobacco products taxed under this chapter that bears an untrue date or falsely states the nature or quantity of the goods invoiced; or

... Fail to produce on demand of the department or the board all invoices of all the tobacco products taxed under this chapter within five years prior to such demand unless the person can show by satisfactory proof that the nonproduction of the invoices was due to causes beyond the person's control.

.. No person, other than a licensed distributor or retailer, may transport tobacco products for sale in this state for which the taxes imposed under this chapter have not been paid unless:

... Notice of the transportation has been given as required under RCW 82.26.140;

... The person transporting the tobacco products actually possesses invoices or delivery tickets showing the true name and address of the consignor or seller, the true name and address of the consignee or purchaser, and the quantity and brands of tobacco products being transported; and

... The tobacco products are consigned to or purchased by a person in this state who is licensed under this chapter.

.. A violation of this subsection (2) is a gross misdemeanor.

. Any person licensed under this chapter as a distributor, and any person licensed under this chapter as a retailer, may not operate in any other capacity unless the additional appropriate license is first secured. A violation of this subsection (3) is a misdemeanor.

. The penalties provided in this section are in addition to any other penalties provided by law for violating the provisions of this chapter or the rules adopted under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5402.SL.pdf?cite=2020%20c%20139%20§%2034[2020 c 139 § 34]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1435-S.SL.pdf?cite=2009%20c%20154%20§%206[2009 c 154 § 6]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6097.SL.pdf?cite=2005%20c%20180%20§%2016[2005 c 180 § 16]; ]

== 82.26.200 - Sales from distributors to retailers—Requirements.
. A retailer that obtains tobacco products from an unlicensed distributor or any other person that is not licensed under this chapter must be licensed both as a retailer and a distributor under this chapter and is liable for the tax imposed under RCW 82.26.020 with respect to the tobacco products acquired from the unlicensed person that are held for sale, handling, or distribution in this state. For the purposes of this subsection, "person" includes both persons defined in RCW 82.26.010(14) and any person immune from state taxation, such as the United States or its instrumentalities, and federally recognized Indian tribes and enrolled tribal members, conducting business within Indian country.

. Every distributor licensed under this chapter must sell tobacco products to retailers located in Washington only if the retailer has a current retailer's license under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5402.SL.pdf?cite=2020%20c%20139%20§%2035[2020 c 139 § 35]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6097.SL.pdf?cite=2005%20c%20180%20§%2017[2005 c 180 § 17]; ]

== 82.26.210 - Manufacturer's representatives—Requirements.
A manufacturer that has manufacturer's representatives who sell or distribute the manufacturer's tobacco products in this state must provide the board a list of the names and addresses of all such representatives and must ensure that the list provided to the board is kept current. A manufacturer's representative is not authorized to distribute or sell tobacco products in this state unless the manufacturer that hired the representative has a valid distributor's license under this chapter and that manufacturer provides the board a current list of all of its manufacturer's representatives as required by this section. A manufacturer's representative must carry a copy of the distributor's license of the manufacturer that hired the representative at all times when selling or distributing the manufacturer's tobacco products.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1435-S.SL.pdf?cite=2009%20c%20154%20§%207[2009 c 154 § 7]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6097.SL.pdf?cite=2005%20c%20180%20§%2014[2005 c 180 § 14]; ]

== 82.26.220 - Enforcement, administration of chapter—License suspension, revocation.
. The board must enforce this chapter. The board may adopt, amend, and repeal rules necessary to enforce this chapter.

. The department may adopt, amend, and repeal rules necessary to administer this chapter. The board may revoke or suspend the distributor's or retailer's license of any distributor or retailer of tobacco products in the state upon sufficient cause showing a violation of this chapter or upon the failure of the licensee to comply with any of the rules adopted under it.

. A license may not be suspended or revoked except upon notice to the licensee and after a hearing as prescribed by the board. The board, upon finding that the licensee has failed to comply with any provision of this chapter or of any rule adopted under it, must, in the case of the first offense, suspend the license or licenses of the licensee for a period of not less than thirty consecutive business days, and in the case of a second or further offense, suspend the license or licenses for a period of not less than ninety consecutive business days but not more than twelve months, and in the event the board finds the licensee has been guilty of willful and persistent violations, it may revoke the license or licenses.

. Any licenses issued under chapter 82.24 or 70.345 RCW to a person whose license or licenses have been suspended or revoked under this section must also be suspended or revoked during the period of suspension or revocation under this section.

. Any person whose license or licenses have been revoked under this section may reapply to the board at the expiration of one year of the license or licenses. The license or licenses may be approved by the board if it appears to the satisfaction of the board that the licensee will comply with the provisions of this chapter and the rules adopted under it.

. A person whose license has been suspended or revoked may not sell tobacco products, vapor products, or cigarettes or permit tobacco products, vapor products, or cigarettes to be sold during the period of suspension or revocation on the premises occupied by the person or upon other premises controlled by the person or others or in any other manner or form.

. Any determination and order by the board, and any order of suspension or revocation by the board of the license or licenses issued under this chapter, or refusal to reinstate a license or licenses after revocation is reviewable by an appeal to the superior court of Thurston county. The superior court must review the order or ruling of the board and may hear the matter de novo, having due regard to the provisions of this chapter and the duties imposed upon the board.

. If the board makes an initial decision to deny a license or renewal, or suspend or revoke a license, the applicant may request a hearing subject to the applicable provisions under Title 34 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1873-S2.SL.pdf?cite=2019%20c%20445%20§%20208[2019 c 445 § 208]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5275-S.SL.pdf?cite=2015%20c%2086%20§%20308[2015 c 86 § 308]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1435-S.SL.pdf?cite=2009%20c%20154%20§%208[2009 c 154 § 8]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6097.SL.pdf?cite=2005%20c%20180%20§%2018[2005 c 180 § 18]; ]

== 82.26.230 - Enforcement—Unlicensed distributors or retailers—Seizure and forfeiture of property.
. Any tobacco products in the possession of a person selling tobacco products in this state acting as a distributor or retailer and who is not licensed as required under RCW 82.26.190, or a person who is selling tobacco products in violation of RCW 82.26.220(6), may be seized without a warrant by any agent of the department, agent of the board, or law enforcement officer of this state. Any tobacco products seized under this subsection shall be deemed forfeited.

. Any tobacco products in the possession of a person who is not a licensed distributor or retailer and who transports tobacco products for sale without having provided notice to the board required under RCW 82.26.140, or without invoices or delivery tickets showing the true name and address of the consignor or seller, the true name and address of the consignee or purchaser, and the quantity and brands of tobacco products being transported may be seized and are subject to forfeiture.

. All conveyances, including aircraft, vehicles, or vessels that are used, or intended for use to transport, or in any manner to facilitate the transportation, for the purpose of sale or receipt of tobacco products under subsection (2) of this section, may be seized and are subject to forfeiture except:

.. A conveyance used by any person as a common or contract carrier having in actual possession invoices or delivery tickets showing the true name and address of the consignor or seller, the true name of the consignee or purchaser, and the quantity and brands of the tobacco products transported, unless it appears that the owner or other person in charge of the conveyance is a consenting party or privy to a violation of this chapter;

.. A conveyance subject to forfeiture under this section by reason of any act or omission of which the owner establishes to have been committed or omitted without his or her knowledge or consent; or

.. A conveyance encumbered by a bona fide security interest if the secured party neither had knowledge of nor consented to the act or omission.

. Property subject to forfeiture under subsections (2) and (3) of this section may be seized by any agent of the department, the board, or law enforcement officer of this state upon process issued by any superior court or district court having jurisdiction over the property. Seizure without process may be made if:

.. The seizure is incident to an arrest or a search warrant or an inspection under an administrative inspection warrant; or

.. The department, board, or law enforcement officer has probable cause to believe that the property was used or is intended to be used in violation of this chapter and exigent circumstances exist making procurement of a search warrant impracticable.

. This section shall not be construed to require the seizure of tobacco products if the department's agent, board's agent, or law enforcement officer reasonably believes that the tobacco products are possessed for personal consumption by the person in possession of the tobacco products.

. Any tobacco products seized by a law enforcement officer shall be turned over to the board as soon as practicable.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6097.SL.pdf?cite=2005%20c%20180%20§%2020[2005 c 180 § 20]; ]

== 82.26.240 - Seizure and forfeiture of property—Department and board requirements.
. In all cases of seizure of any tobacco products made subject to forfeiture under this chapter, the department or board shall proceed as provided in RCW 82.24.135.

. When tobacco products are forfeited under this chapter, the department or board may:

.. Retain the property for official use or upon application by any law enforcement agency of this state, another state, or the District of Columbia, or of the United States for the exclusive use of enforcing this chapter or the laws of any other state or the District of Columbia or of the United States; or

.. Sell the tobacco products at public auction to the highest bidder after due advertisement. Before delivering any of the goods to the successful bidder, the department or board shall require the purchaser to pay the proper amount of any tax due. The proceeds of the sale shall be first applied to the payment of all proper expenses of any investigation leading to the seizure and of the proceedings for forfeiture and sale, including expenses of seizure, maintenance of custody, advertising, and court costs. The balance of the proceeds and all money shall be deposited in the general fund of the state. Proper expenses of investigation include costs incurred by any law enforcement agency or any federal, state, or local agency.

. The department or the board may return any property seized under the provisions of this chapter when it is shown that there was no intention to violate the provisions of this chapter. When any property is returned under this section, the department or the board may return the property to the parties from whom they were seized if and when such parties have paid the proper amount of tax due under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6097.SL.pdf?cite=2005%20c%20180%20§%2021[2005 c 180 § 21]; ]

== 82.26.250 - Enforcement—Search warrants.
When the department or the board has good reason to believe that any of the tobacco products taxed under this chapter are being kept, sold, offered for sale, or given away in violation of the provisions of this chapter, it may make affidavit of facts describing the place or thing to be searched, before any judge of any court in this state, and the judge shall issue a search warrant directed to the sheriff, any deputy, police officer, or duly authorized agent of the department or the board commanding him or her diligently to search any building, room in a building, place, or vehicle as may be designated in the affidavit and search warrant, and to seize the tobacco products and hold them until disposed of by law.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6097.SL.pdf?cite=2005%20c%20180%20§%2022[2005 c 180 § 22]; ]

== 82.26.260 - Tobacco product code—Tax payment and exemption verification.
. [Empty]
.. Within one year following the date on which the requirement for a tobacco product code is effective, payment of, or exemption from, the tax imposed in RCW 82.26.020 must be verifiable on each single-unit consumer-sized can or package of moist snuff, as provided in (b) of this subsection.

.. Within thirty days following the date on which notice of proposed rule making to require a tobacco product code is published in the federal register, the department must commence to develop a method for using a tobacco product code to verify payment of, or exemption from, the tax imposed in RCW 82.26.020; to develop and implement a pilot project to test the method; and to develop a plan for adoption of rules to implement the method. The department must report to the legislature on its progress annually by December 1st through the year following the year in which the method is implemented.

. If notice of proposed rule making to require a tobacco product code is not published in the federal register by July 1, 2011, the department must determine and recommend to the legislature by November 1, 2014, a method to verify payment of, or exemption from, the tax imposed in RCW 82.26.020, by means of stamping, use of manufacturers' digitally readable product identifiers, or any other method, and must complete and present to the legislature a study of compliance with the tax imposed in RCW 82.26.020, the effect of noncompliance on state revenue, and the effect of adopting a method to verify payment of, or exemption from, the tax.

. For purposes of this section, "tobacco product code" means a code that is required on the label of a tobacco product for purposes of tracking or tracing the product through the distribution system under final regulations adopted by the secretary of the United States department of health and human services.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2493-S.SL.pdf?cite=2010%201st%20sp.s.%20c%2022%20§%206[2010 1st sp.s. c 22 § 6]; ]

