= 82.32A - Taxpayer rights and responsibilities.
:toc:

== 82.32A.002 - Short title.
This chapter shall be known and cited as "Washington taxpayers' rights and responsibilities."

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1401-S.SL.pdf?cite=1991%20c%20142%20§%201[1991 c 142 § 1]; ]

== 82.32A.005 - Finding.
. The legislature finds that taxes are one of the most sensitive points of contact between citizens and their government, and that there is a delicate balance between revenue collection and taxpayers' rights and responsibilities. The rights, privacy, and property of Washington taxpayers should be protected adequately during the process of the assessment and collection of taxes.

. The legislature further finds that the Washington tax system is based largely on voluntary compliance and that taxpayers have a responsibility to inform themselves about applicable tax laws. The legislature also finds that the rights of the taxpayers and their attendant responsibilities are best implemented where the department of revenue provides accurate tax information, instructions, forms, administrative policies, and procedures to assist taxpayers to voluntarily comply with the provisions of the revenue act, Title 82 RCW, and where taxpayers cooperate in the administration of these provisions.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1401-S.SL.pdf?cite=1991%20c%20142%20§%202[1991 c 142 § 2]; ]

== 82.32A.010 - Administration of chapter.
The department of revenue shall administer this chapter. The department of revenue shall adopt or amend rules as may be necessary to fully implement this chapter and the rights established under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1401-S.SL.pdf?cite=1991%20c%20142%20§%203[1991 c 142 § 3]; ]

== 82.32A.020 - Rights.
The taxpayers of the state of Washington have:

. The right to a written explanation of the basis for any tax deficiency assessment, interest, and penalties at the time the assessments are issued;

. The right to rely on specific, official written advice and written tax reporting instructions from the department of revenue to that taxpayer, and to have interest, penalties, and in some instances, tax deficiency assessments waived where the taxpayer has so relied to their proven detriment;

. The right to redress and relief where tax laws or rules are found to be unconstitutional by the final decision of a court of record and the right to prompt administrative remedies in such cases;

. The right to confidentiality and protection from public inquiry regarding financial and business information in the possession of the department of revenue in accordance with the requirements of RCW 82.32.330;

. The right to receive, upon request, clear and current tax instructions, rules, procedures, forms, and other tax information; and

. The right to a prompt and independent administrative review by the department of revenue of a decision to revoke a tax registration, and to a written determination that either sustains the revocation or reinstates the registration.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1401-S.SL.pdf?cite=1991%20c%20142%20§%204[1991 c 142 § 4]; ]

== 82.32A.030 - Responsibilities.
To ensure consistent application of the revenue laws, taxpayers have certain responsibilities under chapter 82.32 RCW, including, but not limited to, the responsibility to:

. Register with the department of revenue;

. Know their tax reporting obligations, and when they are uncertain about their obligations, seek instructions from the department of revenue;

. Keep accurate and complete business records;

. File accurate returns and pay taxes in a timely manner;

. Ensure the accuracy of the information entered on their tax returns;

. Substantiate claims for refund;

. Timely pay all taxes after closing a business and request cancellation of registration number; and

. Timely respond to communications from the department of revenue.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1401-S.SL.pdf?cite=1991%20c%20142%20§%205[1991 c 142 § 5]; ]

== 82.32A.040 - Taxpayer rights advocate.
The director of revenue shall appoint a taxpayer rights advocate. The advocate shall be responsible for directly assisting taxpayers and their representatives to assure their understanding and utilization of the policies, processes, and procedures available to them in the resolution of problems.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1401-S.SL.pdf?cite=1991%20c%20142%20§%206[1991 c 142 § 6]; ]

== 82.32A.050 - Taxpayer services program.
The department of revenue shall maintain a taxpayer services program consisting of, but not limited to:

. Providing taxpayer assistance in the form of information, education, and instruction in person, by telephone, or by correspondence;

. Conducting tax workshops at locations most conveniently accessible to the majority of taxpayers affected; and

. Publishing written bulletins, instructions, current revenue laws, rules, court decisions, and interpretive rulings of the department of revenue.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1401-S.SL.pdf?cite=1991%20c%20142%20§%207[1991 c 142 § 7]; ]

