= 82.42 - Aircraft fuel tax.
:toc:

== 82.42.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Air carrier" means any airline, air cargo carrier, air taxi, air commuter, or air charter operator, that provides routine air service to the general population for compensation or hire, and operates at least fifteen round trips per week between two or more points and publishes flight schedules which specify the times, days of the week, and points between which it operates. Where it is doubtful that an operation is for "compensation or hire," the test applied is whether the air service is merely incidental to the person's other business or is, in itself, a major enterprise for profit.

. "Aircraft" means every contrivance now known or hereafter invented, used or designed for navigation of or flight in the air, operated or propelled by the use of aircraft fuel.

. "Aircraft fuel" means gasoline and any other inflammable liquid, by whatever name such liquid is known or sold, the chief use of which is as fuel for the propulsion of aircraft, except gas or liquid, the chief use of which as determined by the director, is for purposes other than the propulsion of aircraft.

. "Dealer" means any person engaged in the retail sale of aircraft fuel.

. "Department" means the department of licensing.

. "Director" means the director of licensing.

. "Distributor" means any person engaged in the sale of aircraft fuel to any dealer and includes any dealer from whom the tax hereinafter imposed has not been collected.

. "Local service commuter" means an air taxi operator who operates at least five round-trips per week between two or more points; publishes flight schedules which specify the times, days of the week, and points between which it operates; and whose aircraft has a maximum capacity of sixty passengers or eighteen thousand pounds of useful load.

. "Person" means every natural person, firm, partnership, association, or private or public corporation.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20301[2013 c 225 § 301]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c49.pdf?cite=1983%20c%2049%20§%201[1983 c 49 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c25.pdf?cite=1982%201st%20ex.s.%20c%2025%20§%201[1982 1st ex.s. c 25 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%20229[1979 c 158 § 229]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c254.pdf?cite=1969%20ex.s.%20c%20254%20§%201[1969 ex.s. c 254 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c10.pdf?cite=1967%20ex.s.%20c%2010%20§%201[1967 ex.s. c 10 § 1]; ]

== 82.42.020 - Aircraft fuel tax imposed—Rate.
There is levied upon every distributor of aircraft fuel, an excise tax at the rate of eleven cents on each gallon of aircraft fuel sold, delivered, or used in this state. There must be collected from every user of aircraft fuel either the use tax imposed by RCW 82.12.020 or the retail sales tax imposed by RCW 82.08.020. The taxes imposed by this chapter must be collected and paid to the state but once in respect to any aircraft fuel.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20302[2013 c 225 § 302]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5414-S.SL.pdf?cite=2005%20c%20341%20§%203[2005 c 341 § 3]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6056.SL.pdf?cite=2003%20c%20375%20§%205[2003 c 375 § 5]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6673-S.SL.pdf?cite=1996%20c%20104%20§%2013[1996 c 104 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c25.pdf?cite=1982%201st%20ex.s.%20c%2025%20§%202[1982 1st ex.s. c 25 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c254.pdf?cite=1969%20ex.s.%20c%20254%20§%202[1969 ex.s. c 254 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c10.pdf?cite=1967%20ex.s.%20c%2010%20§%202[1967 ex.s. c 10 § 2]; ]

== 82.42.030 - Exemptions.
The provision of RCW 82.42.020 imposing the payment of an excise tax on each gallon of aircraft fuel sold, delivered or used in this state does not apply to:

. Aircraft fuel sold for export and exported from this state;

. Aircraft fuel imported into the state in interstate or foreign commerce and intended to be sold while in interstate or foreign commerce;

. Aircraft fuel sold to an agency of the United States government;

. Aircraft fuel delivered directly into the aircraft fuel tanks of equipment operated by an air carrier or supplemental air carrier operating under a certificate of public convenience and necessity under the provisions of the federal aviation act of 1958, P.L. 85-726, as amended;

. Aircraft fuel delivered directly into the aircraft fuel tanks of equipment operated by a local service commuter;

. Aircraft fuel sold to emergency medical air transport entities;

. Aircraft fuel sold to a licensed aircraft fuel distributor;

. Aircraft fuel delivered into the bulk storage tank of a certified user;

. Aircraft fuel used in the operation of aircraft for testing or experimental purposes; and

. Aircraft fuel used in the operation of aircraft when such operation is for the training of crews in Washington state for purchasers of aircraft who are certified air carriers.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20303[2013 c 225 § 303]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5414-S.SL.pdf?cite=2005%20c%20341%20§%204[2005 c 341 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c193.pdf?cite=1989%20c%20193%20§%204[1989 c 193 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c25.pdf?cite=1982%201st%20ex.s.%20c%2025%20§%204[1982 1st ex.s. c 25 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c10.pdf?cite=1967%20ex.s.%20c%2010%20§%203[1967 ex.s. c 10 § 3]; ]

== 82.42.040 - Collection of tax—Procedure—Licensing—Surety bond or other security—Records, reports, statements—Extensions during state of emergency—Application—Investigation—Fee—Penalty for false statement (as amended by 2013 c 23).
The director shall by rule and regulation adopted as provided in chapter 34.05 RCW (Administrative Procedure Act) set up the necessary administrative procedure for collection by the department of the aircraft fuel excise tax as provided for in RCW 82.42.020, placing the responsibility of collection of said tax upon every distributor of aircraft fuel within the state; he or she may require the licensing of every distributor of aircraft fuel and shall require such a corporate surety bond or security of any distributor or person not otherwise bonded under provisions of *chapter 82.36 RCW as is provided for distributors of motor vehicle fuel under *RCW 82.36.060; he or she shall provide such forms and may require such reports or statements as in his or her determination shall be necessary for the proper administration of this chapter. The director may require such records to be kept, and for such periods of time, as deemed necessary for the administration of this chapter, which records shall be available at all times for the director or his or her representative who may require a statement under oath as to the contents thereof. During a state of emergency declared under RCW 43.06.010(12), the director, on his or her own motion or at the request of any taxpayer affected by the emergency, may extend the time for filing any report or the due date for tax remittances as the director deems proper.

Every application for a distributor's license must contain the following information to the extent it applies to the applicant:

. Proof as the department may require concerning the applicant's identity, including but not limited to his or her fingerprints or those of the officers of a corporation making the application;

. The applicant's form and place of organization including proof that the individual, partnership, or corporation is licensed to do business in this state;

. The qualification and business history of the applicant and any partner, officer, or director;

. The applicant's financial condition or history including a bank reference and whether the applicant or any partner, officer, or director has ever been adjudged bankrupt or has an unsatisfied judgment in a federal or state court;

. Whether the applicant has been adjudged guilty of a crime that directly relates to the business for which the license is sought and the time elapsed since the conviction is less than ten years, or has suffered a judgment within the preceding five years in a civil action involving fraud, misrepresentation, or conversion and in the case of a corporation or partnership, all directors, officers, or partners.

After receipt of an application for a license, the director may conduct an investigation to determine whether the facts set forth are true. The director may require a fingerprint record check of the applicant through the Washington state patrol criminal identification system and the federal bureau of investigation before issuance of a license. The results of the background investigation including criminal history information may be released to authorized department personnel as the director deems necessary. The department shall charge a license holder or license applicant a fee of fifty dollars for each background investigation conducted.

An applicant who makes a false statement of a material fact on the application may be prosecuted for false swearing as defined by RCW 9A.72.040.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20335[2013 c 23 § 335]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6950.SL.pdf?cite=2008%20c%20181%20§%20507[2008 c 181 § 507]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6673-S.SL.pdf?cite=1996%20c%20104%20§%2014[1996 c 104 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c25.pdf?cite=1982%201st%20ex.s.%20c%2025%20§%205[1982 1st ex.s. c 25 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c254.pdf?cite=1969%20ex.s.%20c%20254%20§%203[1969 ex.s. c 254 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c10.pdf?cite=1967%20ex.s.%20c%2010%20§%204[1967 ex.s. c 10 § 4]; ]

== 82.42.055 - Computation and payment of tax—Remittance—Electronic funds transfer.
. The tax must be computed by multiplying the tax rate per gallon by the number of gallons of fuel subject to the fuel tax.

. An aircraft fuel distributor is liable for and must pay the tax imposed under RCW 82.42.020 to the department on or before the twenty-fifth day of the month immediately following the reporting period. The tax report required in RCW 82.42.140 must accompany the remittance.

. If the tax is paid by electronic funds transfer, the tax must be paid on or before the twenty-sixth calendar day of the month immediately following the reporting period. If the payment due date falls on a Saturday, Sunday, or legal holiday, payment is due on the state business day immediately preceding the due date.

. The tax must be paid by electronic funds transfer whenever the amount due is fifty thousand dollars or more.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20405[2013 c 225 § 405]; ]

== 82.42.065 - Delinquency.
. If a person is delinquent in the payment of any obligation, the department may give notice of the amount of delinquency to persons having possession or control of credits, personal and real property belonging to the person, or owing debts to the person. Any person notified may not transfer or dispose of credits, personal and real property, or debts without the consent of the department. A person notified must, within twenty days after receipt of notice, advise the department of any credits, personal and real property, or debts in their possession, under their control or owing by them, and must immediately deliver the credits, personal and real property, or debts to the department.

. The notice and order to withhold and deliver constitutes a continuing lien on property of the person. The department must include in the notice to withhold and deliver "continuing lien." The effective date of a notice to withhold and deliver is the date of mailing.

. If a person fails to timely answer the notice, a court may render a judgment, plus costs by default against the person.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20407[2013 c 225 § 407]; ]

== 82.42.067 - Delinquency—Seizure and sale of property.
. If a person is delinquent in the payment of any obligation and the delinquency continues after notice and demand for payment the department must collect the amount due. The department must seize any property subject to the lien of tax, penalty, and interest and sell it at public auction. Notice of sale and the time and place must be given to the person and to all persons appearing with an interest in the property. The notice must be in writing at least ten days before the date of sale. Notice must be published for at least ten days before the date of sale in a newspaper of general circulation published in the county the property will be sold. If there is no newspaper of general circulation in the county, the notice must be posted in three public places in the county for a period of ten days. The notice must contain a description of the property together with a statement of the amount due, the name of the person and a statement that unless the amount is paid on or before the time in the notice the property will be sold.

. The department must sell the property and deliver to the purchaser a bill of sale or deed. If the moneys received exceed the amount due from the person, the excess must be returned to the person and a receipt obtained. If any person having an interest in or lien upon the property has filed notice with the department prior to the sale, the department must withhold payment of any excess to the person pending determination of the rights of the respective parties by a court of competent jurisdiction. If the receipt of the person is not available, the department must deposit the excess with the state treasurer as trustee for the person or their heirs, successors, or assigns. Prior to making any seizure of property, the department may first serve upon the person's bondsperson a notice of delinquency and demand for payment of the amount due.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20408[2013 c 225 § 408]; ]

== 82.42.068 - Payment of tax by a nonlicensee.
Every person, other than a licensee, who acquires fuel upon which payment of tax is required, if the tax has not been paid, must comply with the provisions of this chapter, and pay tax at the rate provided in RCW 82.42.020. The person is subject to the same duties and penalties imposed upon licensees.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20412[2013 c 225 § 412]; ]

== 82.42.075 - Bonding requirements.
. A license may not be issued or continued in force unless a bond is provided to secure payment of all taxes, interest, and penalties. This requirement may be waived for licensees properly bonded under the provisions of chapter 82.38 RCW or licensed aircraft fuel distributors who, upon determination by the department, have sufficient resources, assets, other financial instruments, or other means to adequately make payments on monthly aircraft fuel tax payments, penalties, and interest.

. The department may require a licensee to post a bond if the department determines a bond is required to protect the interests of the state.

. The total amount of the bond or bonds is three times the estimated monthly aircraft fuel tax liability. The total bonding amount may never be less than five thousand dollars nor more than one hundred thousand dollars.

. In lieu of a bond, a licensee may deposit with the state treasurer, a like amount of money of the United States or bonds or other obligations of the United States, the state, or any county of the state, of a market value not less than the amount of the required bond.

. The department may require a licensee to increase the bond amount or to deposit additional securities as described in this section if the security of the bond or the market value of the securities becomes impaired or inadequate.

. Any surety on a bond furnished by a licensee must be released and discharged from any liability accruing on such bond after the expiration of forty-five days from the date the surety provided written notification to the department. This subsection does not relieve, release, or discharge the surety from any liability accrued or which will accrue before the expiration of the forty-five day period. The department must promptly notify the licensee who furnished the bond, and unless the licensee, on or before the expiration of the forty-five day period, files a new bond the department must cancel the license.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20403[2013 c 225 § 403]; ]

== 82.42.085 - Violations—Penalties.
. It is unlawful for a person to:

.. Evade a tax or fee imposed under this chapter;

.. Knowingly assist another person to evade a tax or fee imposed by this chapter;

.. File a false statement of a material fact or otherwise commit any fraud or make a false representation on an aircraft fuel tax license application, aircraft fuel tax refund application, aircraft fuel tax return, aircraft fuel tax record, or aircraft fuel tax refund claim;

.. Act as an aircraft fuel distributor unless the person holds a license issued by the department authorizing the person to engage in that business;

.. Knowingly operate a conveyance for the purpose of hauling, transporting, or delivering aircraft fuel in bulk and not possess an invoice, bill of sale, or other statement showing the name, address, and tax license number of the seller or consignor, the destination, the name, address, and tax license number of the purchaser or consignee, and the number of gallons;

.. Refuse to permit the department or its authorized representative to examine the person's books, papers, records, storage facilities, and equipment used in conjunction with the use, distribution, or sale of aircraft fuel;

.. To display, or cause to permit to be displayed, or to have in possession, an aircraft fuel license knowing the same to be fictitious or to have been suspended, canceled, revoked, or altered;

.. To lend to, or knowingly permit the use of, by one not entitled thereto, any aircraft fuel license issued to the person lending it or permitting it to be used;

.. To display or to represent as one's own any aircraft fuel license not issued to the person displaying the same; and

.. To use or to conspire with any governmental official, agent, or employee for the use of any requisition, purchase order, or any card or any authority to which he or she is not specifically entitled by government regulations, for the purpose of obtaining any aircraft fuel upon which the state tax has not been paid.

. [Empty]
.. A single violation of subsection (1)(a) and (b) of this section is a gross misdemeanor under chapter 9A.20 RCW.

.. Multiple violations of subsection (1)(a) and (b) of this section are a class C felony under chapter 9A.20 RCW.

. Violations of (1)(c) through (j) of this section are a gross misdemeanor under chapter 9A.20 RCW.

. In addition to other penalties and remedies provided by law, the court must order a person or corporation found guilty of violating subsection (1)(a) through (b) of this section to:

.. Pay the tax or fee evaded plus interest, commencing at the date the tax or fee was first due, at the rate of twelve percent per year, compounded monthly; and

.. Pay a penalty of one hundred percent of the tax evaded.

. The tax imposed by this chapter is held in trust by the licensee until paid to the department, and a licensee who appropriates the tax to his or her own use or to any use other than the payment of the tax is guilty of a felony or gross misdemeanor in accordance with the theft and anticipatory provisions of Title 9A RCW. A person, partnership, corporation, or corporate officer who fails to pay to the department the tax is personally liable to the state for the amount of the tax.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20420[2013 c 225 § 420]; ]

== 82.42.090 - Tax proceeds—Disposition—Aeronautics account.
All moneys collected by the director from the aircraft fuel excise tax as provided in RCW 82.42.020 shall be transmitted to the state treasurer and shall be credited to the aeronautics account hereby created in the state treasury. Moneys collected from the consumer or user of aircraft fuel from either the use tax imposed by RCW 82.12.020 or the retail sales tax imposed by RCW 82.08.020 shall be transmitted to the state treasurer and credited to the state general fund.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5316.SL.pdf?cite=2017%203rd%20sp.s.%20c%2025%20§%2042[2017 3rd sp.s. c 25 § 42]; 2013 c 225 § 305; 2015 c 228 § 39; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1190.SL.pdf?cite=1995%20c%20170%20§%201[1995 c 170 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1058-S.SL.pdf?cite=1991%20sp.s.%20c%2013%20§%2037[1991 sp.s. c 13 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c57.pdf?cite=1985%20c%2057%20§%2086[1985 c 57 § 86]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c25.pdf?cite=1982%201st%20ex.s.%20c%2025%20§%208[1982 1st ex.s. c 25 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c10.pdf?cite=1967%20ex.s.%20c%2010%20§%209[1967 ex.s. c 10 § 9]; ]

== 82.42.095 - Date of mailing deemed date of filing or receipt—Timely mailing bars penalties and tolls statutory time limitations.
An application, report, notice, payment, or claim for credit or refund properly addressed and deposited in the United States mail is deemed filed or received on the date shown by the post office cancellation mark on the envelope. No penalty for delinquency attaches, nor is the statutory period deemed to have elapsed in the case of credit or refund claims, if it is established by competent evidence that the application, report, notice, payment, or claim for credit or refund was properly addressed and timely deposited in the United States mail, if a duplicate of the document or payment is filed.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20406[2013 c 225 § 406]; ]

== 82.42.100 - Enforcement.
The director is charged with the enforcement of the provisions of this chapter and rules and regulations promulgated hereunder. The director may, in his or her discretion, call on the state patrol or any peace officer in the state, who shall then aid in the enforcement of this chapter or any rules or regulations promulgated hereunder.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20336[2013 c 23 § 336]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c10.pdf?cite=1967%20ex.s.%20c%2010%20§%2010[1967 ex.s. c 10 § 10]; ]

== 82.42.110 - Tax upon persons other than distributors—Imposition—Collection—Distribution—Enforcement.
Every person other than a distributor who acquires any aircraft fuel within this state upon which payment of tax is required under the provisions of this chapter, or imports such aircraft fuel into this state and sells, delivers, or in any manner uses it in this state, if the tax has not been paid, is subject to the provisions of this chapter provided for aircraft fuel distributors and must pay a tax at the rate computed under RCW 82.42.020 for each gallon thereof so sold, delivered, or used in the manner provided for distributors. The proceeds of the tax imposed by this section must be distributed in the manner provided for the distribution of the aircraft fuel tax in RCW 82.42.090. For failure to comply with the terms of this chapter, such person is subject to the same penalties imposed upon distributors. The director must pursue against such persons the same procedure and remedies for audits, adjustments, collection, and enforcement of this chapter as is provided with respect to distributors. Nothing herein must be construed as classifying such persons as distributors.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20306[2013 c 225 § 306]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c25.pdf?cite=1982%201st%20ex.s.%20c%2025%20§%209[1982 1st ex.s. c 25 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c156.pdf?cite=1971%20ex.s.%20c%20156%20§%205[1971 ex.s. c 156 § 5]; ]

== 82.42.115 - Assessments—Warrant—Lien—Filing fee—Writs of execution and garnishment.
When an assessment becomes final the department may file with the clerk of any county within the state a warrant in the amount of the assessment of taxes, penalties, interest and a filing fee under RCW 36.18.012(10). The warrant is a lien upon title to, and interest in all real and personal property of the person against whom the warrant is issued. The warrant is sufficient to support the issuance of writs of execution and writs of garnishment in favor of the state.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20402[2013 c 225 § 402]; ]

== 82.42.118 - Civil and statutory penalties and interest—Deficiency assessments.
. If any licensee fails to pay any taxes due the state of Washington within the time prescribed in this chapter, the licensee must pay a penalty of ten percent of the tax due.

. If the tax reported by any licensee is deficient a penalty of ten percent of the deficiency must be assessed.

. If any licensee, whether or not licensed as such, fails, neglects, or refuses to file a required fuel tax report, the department must determine the tax liability and add the penalty provided in subsection (2) of this section to the liability. An assessment made by the department pursuant to this subsection or to subsection (2) of this section is presumed to be correct, and the burden is on the person who challenges the assessment to establish by a fair preponderance of the evidence that it is erroneous or excessive.

. If any licensee establishes by a fair preponderance of evidence that failure to file a report or pay the proper amount of tax within the time prescribed was due to reasonable cause and was not intentional or willful, the department may waive the penalty prescribed in subsections (1) and (2) of this section.

. If any licensee files a false or fraudulent report with intent to evade the tax imposed by this chapter, a penalty of twenty-five percent of the deficiency must be added to the amount of deficiency, which is in addition to all other penalties prescribed by law.

. If any person acts as a licensee without first securing the required license, all fuel tax liability incurred by that person becomes immediately due and payable. The department must determine the amount of the tax liability and must assess the person along with a penalty of one hundred percent of the tax.

. Any fuel tax, penalties, and interest payable under this chapter bear interest at the rate of one percent per month, or fraction thereof, from the first day of the calendar month after the amount or any portion thereof should have been paid until the date of payment. The department may waive interest when it determines the cost of processing the collection exceeds the amount of interest due.

. Except in the case of violations of filing a false or fraudulent report, if the department deems mitigation of penalties and interest to be reasonable and in the best interests of carrying out the purpose of this chapter, it may mitigate the assessments.

. Except in the case of a fraudulent report or failure to file a report, deficiencies, penalties, and interest must be assessed within five years from the twenty-fifth day of the next succeeding month following the reporting period for which the amount is determined or within five years after the return is filed, whichever period expires later.

. [Empty]
.. Any licensee against whom an assessment is made under the provisions of subsection (2) or (3) of this section may petition for a reassessment within thirty days after service upon the licensee of the assessment. If such petition is not filed within such thirty-day period, the amount of the assessment becomes final.

.. If a petition for reassessment is filed within the thirty-day period, the department must reconsider the assessment and, if the licensee has requested in the petition, must grant an informal hearing and give ten days' notice of the time and place. The department may continue the hearing as needed. The decision of the department upon a petition for reassessment becomes final thirty days after service upon the licensee.

. Every assessment made by the department becomes due and payable at the time it becomes final and if not timely paid to the department a penalty of ten percent of the amount of the tax must be added to the assessment.

. Any notice of assessment required by this section must be served by depositing such notice in the United States mail, postage prepaid addressed to the licensee at the address shown in the records of the department.

. Any licensee who has had a fuel license revoked must pay a one hundred dollar penalty prior to the issuance of a new license.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20404[2013 c 225 § 404]; ]

== 82.42.125 - Bankruptcy proceedings—Notice.
A licensee who files a bankruptcy petition, or against whom a petition for bankruptcy is filed, must notify the department of the filing within ten days of the filing. The notice must include the name and location of the court in which the petition was filed.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20307[2013 c 225 § 307]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1459.SL.pdf?cite=1997%20c%20183%20§%2011[1997 c 183 § 11]; ]

== 82.42.130 - Administration and enforcement.
. The department may prescribe, adopt, and enforce reasonable rules relating to administration and enforcement of this chapter.

. The department or its authorized representative is empowered to examine the books, papers, records, and equipment of any person distributing, transporting, storing, or using aircraft fuel and to investigate the disposition any person makes of aircraft fuel to determine whether all taxes due or refundable are properly reported, paid, or claimed. If books, papers, records, and equipment are not maintained in this state at the time of demand the department does not lose any right of examination.

. The director may, from time to time, require additional reports from any licensee with reference to any of the matters herein concerned. Such reports must be made and filed on forms prepared by the director.

. For the purpose of any investigation or proceeding, the director or designee may administer oaths and affirmations, subpoena witnesses, compel their attendance, take evidence, and require the production of any books, papers, correspondence, memoranda, agreements, or other documents or records which the director deems relevant or material to the inquiry.

. In the case of contumacy by or refusal to obey a subpoena issued to, any person, any court of competent jurisdiction upon application by the director, may issue to that person an order requiring appearance before the director or designee to produce testimony of other evidence regarding the matter under investigation or in question.

. The department must, upon request from officials responsible for enforcement of aircraft fuel tax laws of any state, the District of Columbia, the United States, its territories and possessions, the provinces or the dominion of Canada, forward information relative to the receipt, storage, delivery, sale, use, or other disposition of aircraft fuel by any person if the other furnishes like information.

. The department may enter into an aircraft fuel tax cooperative agreement with another state, the District of Columbia, the United States, its territories and possessions, or Canadian Province for the administration, collection, and enforcement of their respective fuel taxes.

. The foregoing remedies of the state in this chapter are cumulative and no action taken by the department may be construed to be an election on the part of the state or any of its officers to pursue any remedy hereunder to the exclusion of any other remedy for which provision is made in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20401[2013 c 225 § 401]; ]

== 82.42.135 - Discontinuance, sale, or transfer of business—Notice—Payment of taxes, interest, penalties.
A licensee who ceases to engage in business must notify the department in writing at the time of cessation. The notice must give the date of cessation and the name and address of any purchaser or transferee. The licensee must file a report and pay all taxes, interest, and penalties owing.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20409[2013 c 225 § 409]; ]

== 82.42.140 - Periodic tax reports.
. For the purpose of determining the amount of liability for the tax imposed under this chapter, each aircraft fuel distributor must file monthly tax reports with the department.

. Tax reports must be filed on or before the twenty-fifth day of the calendar month following the reporting period to which it relates. A report must be filed even though no tax is due for the reporting period. Each report must contain a declaration that the statements contained therein are true and are made under penalties of perjury. The report must show information as the department may reasonably require for the proper administration and enforcement of this chapter.

. If the filing date falls on a Saturday, Sunday, or legal holiday the next secular or business day is the filing date.

. The department in order to insure payment of the tax or to facilitate administration of this chapter may require the filing of reports and tax remittances at intervals other than one month.

. During a state of emergency declared under RCW 43.06.010(12), the department, on its own motion or at the request of any taxpayer affected by the emergency, may extend the time for filing any report or the due date for tax remittances as the department deems proper.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20413[2013 c 225 § 413]; ]

== 82.42.145 - Fuel records.
. Every person importing, manufacturing, refining, transporting, blending, or storing aircraft fuel must keep for a period of five years open to inspection at all times during the business hours of the day to the department or its authorized representatives, a complete record of all aircraft fuel purchased or received and all aircraft fuel sold, delivered, or used by them.

. Records must show:

.. The date of receipt;

.. The name and address of the person from whom purchased or received;

.. The number of gallons received at each place of business or place of storage in the state of Washington;

.. The date of sale or delivery;

.. The number of gallons sold, delivered, or used for taxable purposes;

.. The number of gallons sold, delivered, or used for any purpose not subject to tax;

.. The name, address, and aircraft fuel license number of the purchaser if the fuel tax is not collected on the sale or delivery;

.. The physical inventories of aircraft fuel and petroleum products on hand at each place of business at the end of each month;

.. Stocks of raw gasoline, gasoline stock, diesel oil, kerosene, kerosene distillates, casing head gasoline, and other petroleum products which may be used in the compounding, blending, or manufacturing of aircraft fuel.

. The department may require a person other than a licensee engaged in the business of selling, purchasing, distributing, storing, transporting, or delivering aircraft fuel to submit periodic reports to the department regarding the disposition of the aircraft fuel. The reports must be on forms prescribed by the department and must contain information as the department may require.

. Every person operating any conveyance transporting fuel in bulk must possess during the entire time an invoice, bill of sale, or other statement showing the name, address, and license number of the seller or consigner, the destination, name, and address of the purchaser or consignee, license number, if applicable, and the number of gallons. The person transporting fuel must at the request of any law enforcement officer or authorized representative of the department, produce for inspection required records and must permit inspection of the contents of the vehicle.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20414[2013 c 225 § 414]; ]

== 82.42.200 - Injunctions—Writs.
No injunction or writ of mandate or other legal or equitable process may be issued in any suit, action, or proceeding in any court against this state or against any officer of the state to prevent or enjoin the collection under this chapter of any tax or any amount of tax required to be collected.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20410[2013 c 225 § 410]; ]

== 82.42.205 - Suits for recovery of taxes illegally or erroneously collected.
. No suit or proceeding may be maintained in any court for the recovery of any amount alleged to have been overpaid under RCW 82.42.020 unless a claim for refund or credit has been duly filed pursuant to RCW 82.42.220.

. Within ninety days after the mailing of the notice of the department's action upon a claim filed pursuant to RCW 82.42.220, the claimant may bring an action against the department on the grounds set forth in the claim in a court of competent jurisdiction in Thurston county for the recovery of the whole or any part of the amount with respect to which the claim has been disallowed. Failure to bring action within the time specified constitutes a waiver of any demand against the state on account of the alleged overpayments.

. If the department fails to mail notice of action on a claim within six months after the claim is filed, the claimant may, prior to the mailing of notice by the department of its intention on the claim, consider the claim disallowed and bring an action against the department, on the grounds set forth in the claim for the recovery of the whole or any part of the amount claimed as an overpayment.

. If judgment is rendered for the plaintiff, the amount of the judgment must first be credited on any aircraft fuel tax due and payable from the plaintiff. The balance of the judgment must be refunded to the plaintiff.

. In any judgment, interest must be allowed at the rate of twelve percent per annum upon the amount found to have been illegally collected from the date of payment of the amount to the date of allowance of credit on account of the judgment or to a date preceding the date of the refund warrant, but not more than thirty days, the date to be determined by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20415[2013 c 225 § 415]; ]

== 82.42.210 - Denial—Suspension—Revocation.
. The department may refuse to issue to, or suspend or revoke a license of any licensee or applicant:

.. Who formerly held a license issued under chapter 82.36, 82.38, 82.42, or 46.87 RCW which has been suspended or revoked for cause;

.. Who is a subterfuge for the real party in interest whose license issued under chapter 82.36, 82.38, 82.42, or 46.87 RCW has been revoked for cause;

.. Who, as an individual licensee, or partner, officer, director, owner, or managing employee of a licensee, has had a license issued under chapter 82.36, 82.38, 82.42, or 46.87 RCW denied, suspended, or revoked for cause;

.. Who has an unsatisfied debt to the state assessed under either chapter 82.36, 82.38, 82.42, or 46.87 RCW;

.. Who formerly held as an individual, partner, officer, director, owner, managing employee of a licensee, or subterfuge for a real party in interest, a license issued by the federal government or a state that allowed a person to buy or sell untaxed motor vehicle or special fuel, which, has been suspended or revoked for cause;

.. Who pled guilty to or was convicted as an individual, partner, officer, director, owner, or managing employee of a licensee in this or any other state, Canadian province, or in any federal jurisdiction of a gross misdemeanor or felony crime directly related to the fuel distribution business or has been subject to a civil judgment involving fraud, misrepresentation, conversion, or dishonesty, notwithstanding chapter 9.96A RCW;

.. Who misrepresented or concealed a material fact in obtaining a license or reinstating a license;

.. Who violated a statute or administrative rule regulating fuel taxation or distribution;

.. Who failed to cooperate with the department's investigations by:

... Not furnishing papers or documents;

... Not furnishing in writing a full and complete explanation regarding a matter under investigation by the department; or

... Not responding to subpoenas issued by the department, whether or not the recipient of the subpoena is the subject of the proceeding;

.. Who failed to comply with an order issued by the director; or

.. Upon other sufficient cause being shown.

. Before such refusal, suspension, or revocation the department must grant the applicant a hearing and must grant the applicant at least twenty days' written notice of the time and place thereof.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20411[2013 c 225 § 411]; ]

== 82.42.220 - Claim of refund or credit.
. Claims for refund or credit for aircraft fuel taxes paid under this chapter must be filed with the department on forms prescribed by the department and must contain and be supported by such information and documentation as the department may require. Claims for refund of aircraft fuel taxes must be for at least twenty dollars.

. Any amount determined to be refundable by the department must first be credited on any amounts then due and payable from a person to whom the refund is due.

. No refund or credit may be approved by the department unless a written claim for refund or credit stating the specific grounds upon which the claim is founded is filed with the department:

.. Within thirteen months from the date of purchase or from the last day of the month following the close of the reporting period for which the refundable amount or credit is due with respect to refunds or credits allowed and if not filed within this period the right to refund is barred; or

.. Within five years from the last day of the month following the close of the reporting period for which the overpayment is due with respect to the refunds or credits allowed for aircraft fuel tax licensees.

. The department must refund any amount paid that has been verified by the department to be more than twenty dollars over the amount actually due for the reporting period.

. Payment credits may not be carried forward and applied to subsequent tax returns for a person licensed under this chapter.

. Within thirty days after disallowing any refund claim in whole or in part, the department must provide written notice of its action to the claimant.

. [Empty]
.. Interest must be paid upon any refundable amount or credit due at the rate of one percent per month from the last day of the calendar month following the reporting period for which the refundable amount or credit is due.

.. The interest must be paid:

... In the case of a refund, to the last day of the calendar month following the date upon which the claim is approved by the department; and

... In the case of a credit, to the same date as that to which interest is computed on the tax or amount against which the credit is applied.

.. If the department determines that any overpayment has been made intentionally or by reason of carelessness, interest is not allowed.

. The department must pay interest of one percent on any refund payable that is issued more than thirty state business days after the receipt of a claim properly filed and completed. After the end of the thirty business day period, additional interest accrues at the rate of one percent on the amount payable for each thirty calendar day period.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20416[2013 c 225 § 416]; ]

== 82.42.230 - Refunds.
Any person who has purchased aircraft fuel on which tax has been paid may file a claim with the department for a refund of the tax for:

. Aircraft fuel used in aircraft that both operate from a private, nonstate-funded airfield during at least ninety-five percent of the aircraft's normal use and are used principally for the application of pesticides, herbicides, or other agricultural chemicals;

. Aircraft fuel used in the operation of aircraft for testing or experimental purposes; and

. Aircraft fuel used in the operation of aircraft when the operation is for the training of crews in Washington state for purchasers of aircraft who are certified air carriers.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20417[2013 c 225 § 417]; ]

== 82.42.240 - Remedies cumulative.
The remedies of the state in this chapter are cumulative and no action taken by the department may be construed to be an election to pursue any remedy to the exclusion of another.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20418[2013 c 225 § 418]; ]

== 82.42.250 - Tax lien.
. If a person liable for payment of tax fails to pay the amount including any interest, penalty, or addition, together with costs accrued, there must be a lien in favor of the state upon all franchises, property, and rights to property, whether real or personal, belonging to or acquired, whether the property is employed by such person for personal or business use or is in the control of a trustee, receiver, or assignee. The lien is effective from the date taxes were due and payable until the amount is satisfied. The lien has priority over any lien or encumbrance except liens of other taxes having priority by law.

. The department must file with any county auditor a statement of claim and lien specifying the amount of delinquent taxes, penalties, and interest owed.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1883-S.SL.pdf?cite=2013%20c%20225%20§%20419[2013 c 225 § 419]; ]

