= 82.49 - Watercraft excise tax.
:toc:

== 82.49.010 - Excise tax imposed—Failure to register—Out-of-state registration to avoid tax, liability—Penalties.
. An excise tax is imposed for the privilege of using a vessel upon the waters of this state, except vessels exempt under RCW 82.49.020. The annual amount of the excise tax is one-half of one percent of fair market value, as determined under this chapter, or five dollars, whichever is greater. Violation of this subsection is a misdemeanor.

. A person who is required under chapter 88.02 RCW to register a vessel in this state and who fails to register the vessel in this state or registers the vessel in another state or foreign country and avoids the Washington watercraft excise tax is guilty of a gross misdemeanor and is liable for such unpaid excise tax. The department of revenue may assess and collect the unpaid excise tax under chapter 82.32 RCW, including the penalty imposed in RCW 82.49.080 and penalties and interest provided in chapter 82.32 RCW.

. The excise tax upon a vessel registered for the first time in this state shall be imposed for a twelve-month period, including the month in which the vessel is registered, unless the director of licensing extends or diminishes vessel registration periods for the purpose of staggered renewal periods under RCW 88.02.560. A vessel is registered for the first time in this state when the vessel was not registered in this state for the immediately preceding registration year, or when the vessel was registered in another jurisdiction for the immediately preceding year.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2457-S2.SL.pdf?cite=2014%20c%20195%20§%20503[2014 c 195 § 503]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201044[2010 c 161 § 1044]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6467-S.SL.pdf?cite=2000%20c%20229%20§%205[2000 c 229 § 5]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5706-S.SL.pdf?cite=1999%20c%20277%20§%208[1999 c 277 § 8]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1127-S.SL.pdf?cite=1993%20c%20238%20§%206[1993 c 238 § 6]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2727.SL.pdf?cite=1992%20c%20154%20§%203[1992 c 154 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex2c3.pdf?cite=1983%202nd%20ex.s.%20c%203%20§%2042[1983 2nd ex.s. c 3 § 42]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c7.pdf?cite=1983%20c%207%20§%209[1983 c 7 § 9]; ]

== 82.49.020 - Exemptions.
The following are exempt from the tax imposed under this chapter:

. Vessels exempt from the registration requirements of chapter 88.02 RCW;

. Vessels used exclusively for commercial fishing purposes;

. Vessels under sixteen feet in overall length;

. Vessels owned and operated by the United States, a state of the United States, or any municipality or political subdivision thereof;

. Vessels owned by a nonprofit organization or association engaged in character building of boys and girls under eighteen years of age and solely used for such purposes, as determined by the department for the purposes of RCW 84.36.030; and

. Vessels owned and held for sale by a dealer, but not rented on a regular commercial basis.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c250.pdf?cite=1984%20c%20250%20§%201[1984 c 250 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex2c3.pdf?cite=1983%202nd%20ex.s.%20c%203%20§%2043[1983 2nd ex.s. c 3 § 43]; ]

== 82.49.030 - Payment of tax—Deposit in general fund.
. The excise tax imposed under this chapter is due and payable to the department of licensing, county auditor or other agent, or subagent appointed by the director of the department of licensing at the time of registration of a vessel. The department of licensing shall not issue or renew a registration for a vessel until the tax is paid in full.

. The excise tax collected under this chapter must be deposited in the general fund.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201045[2010 c 161 § 1045]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2398-S.SL.pdf?cite=2000%20c%20103%20§%2018[2000 c 103 § 18]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1330-S.SL.pdf?cite=1991%20sp.s.%20c%2016%20§%20925[1991 sp.s. c 16 § 925]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c393.pdf?cite=1989%20c%20393%20§%2010[1989 c 393 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c7.pdf?cite=1983%20c%207%20§%2010[1983 c 7 § 10]; ]

== 82.49.040 - Depreciation schedule for use in determining fair market value.
The department of revenue shall prepare at least once each year a depreciation schedule for use in the determination of fair market value for the purposes of this chapter. The schedule shall be based upon information available to the department of revenue pertaining to the current fair market value of vessels. The fair market value of a vessel for the purposes of this chapter shall be based on the most recent purchase price depreciated according to the year of the most recent purchase of the vessel. The most recent purchase price is the consideration, whether money, credit, rights, or other property expressed in terms of money, paid or given or contracted to be paid or given by the purchaser to the seller for the vessel.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c7.pdf?cite=1983%20c%207%20§%2011[1983 c 7 § 11]; ]

== 82.49.050 - Appraisal of vessel by department of revenue.
. If a vessel has been acquired by lease or gift, or the most recent purchase price of a vessel is not known to the owner, the department of revenue shall appraise the vessel before registration.

. If after registration the department of revenue determines that the purchase price stated by the owner is not a reasonable representation of the true fair market value of a vessel at the time of purchase, the department of revenue shall appraise the vessel.

. If a vessel is homemade, the owner shall make a notarized declaration of fair market value. The fair market value of the vessel for the purposes of this chapter shall be the declared value, unless after registration the department of revenue determines that the declared value is not a reasonable representation of the true fair market value of the vessel in which case the department of revenue shall appraise the vessel.

. If the department of revenue appraises a vessel, the fair market value of the vessel for the purposes of this chapter shall be the appraised value. If the vessel has been registered before appraisal, the department of revenue shall refund any overpayment of tax to the owner or notify the owner of any additional tax due. The owner shall pay any additional tax due within thirty days after notification by the department.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c7.pdf?cite=1983%20c%207%20§%2012[1983 c 7 § 12]; ]

== 82.49.060 - Disputes as to appraised value or status as taxable—Petition for conference or reduction of tax—Appeal to board of tax appeals—Independent appraisal.
. Any vessel owner disputing an appraised value under RCW 82.49.050 or disputing whether the vessel is taxable, may petition for a conference with the department as provided under RCW 82.32.160, or for reduction of the tax due as provided under RCW 82.32.170.

. Any vessel owner having received a notice of denial of a petition or a notice of determination made for the owner's vessel under RCW 82.32.160 or 82.32.170 may appeal to the board of tax appeals as provided under RCW 82.03.190. In deciding a case appealed under this section, the board of tax appeals may require an independent appraisal of the vessel. The cost of the independent appraisal shall be apportioned between the department and the vessel owner as provided by the board.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1481.SL.pdf?cite=1993%20c%2033%20§%201[1993 c 33 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c7.pdf?cite=1983%20c%207%20§%2013[1983 c 7 § 13]; ]

== 82.49.065 - Refunds—When, to whom—Amounts.
. Refunds of the excise tax imposed under this chapter must be handled in the same manner and under the same terms and conditions as provided in RCW 88.02.350.

. The excise tax imposed under this chapter may be refunded to the person who paid the excise tax at the same time the registration fee under chapter 88.02 RCW was paid. The amount of the excise tax that may be refunded includes:

.. The entire amount of the excise tax, if the entire amount of the registration fee is also refunded; or

.. Any amount that was greater than the amount due.

. Excise tax refunds include interest at the rate specified in RCW 82.32.060.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201046[2010 c 161 § 1046]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20405[2003 c 53 § 405]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2727.SL.pdf?cite=1992%20c%20154%20§%204[1992 c 154 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c68.pdf?cite=1989%20c%2068%20§%203[1989 c 68 § 3]; ]

== 82.49.080 - Vessels not registered as required under chapter  88.02 RCW—Penalty.
. An owner of a vessel that is not registered as required by chapter 88.02 RCW and for which watercraft excise tax is due under this chapter is liable for a penalty in the following amount:

.. One hundred dollars for the owner's first violation;

.. Two hundred dollars for the owner's second violation involving the same or any other vessel; or

.. Four hundred dollars for the owner's third and successive violations involving the same or any other vessel.

. The department of revenue may collect this penalty under the procedures established in chapter 82.32 RCW. The penalty imposed under this section is in addition to any other civil or criminal penalty imposed by law.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2457-S2.SL.pdf?cite=2014%20c%20195%20§%20502[2014 c 195 § 502]; ]

== 82.49.900 - Construction—Severability—Effective dates—1983 c 7.
See notes following RCW 82.08.020.

[ ]

