= 82.44 - Motor vehicle excise tax.
:toc:

== 82.44.010 - Definitions.
For the purposes of this chapter, unless the context otherwise requires:

. "Department" means the department of licensing.

. "Motor vehicle" means all motor vehicles, trailers and semitrailers used, or of the type designed primarily to be used, upon the public streets and highways, for the convenience or pleasure of the owner, or for the conveyance, for hire or otherwise, of persons or property, including fixed loads and facilities for human habitation; but shall not include (a) vehicles carrying exempt licenses, (b) dock and warehouse tractors and their cars or trailers, lumber carriers of the type known as spiders, and all other automotive equipment not designed primarily for use upon public streets, or highways, (c) motor vehicles or their trailers used entirely upon private property, (d) mobile homes and travel trailers as defined in RCW 82.50.010, or (e) motor vehicles owned by nonresident military personnel of the armed forces of the United States stationed in the state of Washington provided personnel were also nonresident at the time of their entry into military service.

. "Truck-type power or trailing unit" means any vehicle that is subject to the fees under RCW 46.17.355, except vehicles with an unladen weight of six thousand pounds or less, RCW 46.16A.425, 46.17.335, or 46.17.350(1)(c).

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201166[2010 c 161 § 1166]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c42.pdf?cite=1990%20c%2042%20§%20301[1990 c 42 § 301]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c107.pdf?cite=1979%20c%20107%20§%2010[1979 c 107 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c299.pdf?cite=1971%20ex.s.%20c%20299%20§%2054[1971 ex.s. c 299 § 54]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c121.pdf?cite=1967%20c%20121%20§%204[1967 c 121 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c199.pdf?cite=1963%20c%20199%20§%201[1963 c 199 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2082.44.010[1961 c 15 § 82.44.010]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c269.pdf?cite=1957%20c%20269%20§%2018[1957 c 269 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c264.pdf?cite=1955%20c%20264%20§%201[1955 c 264 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c152.pdf?cite=1945%20c%20152%20§%201[1945 c 152 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c144.pdf?cite=1943%20c%20144%20§%201[1943 c 144 § 1]; Rem. Supp. 1945 § 6312-115; ]

== 82.44.015 - Ride-sharing passenger motor vehicles excluded—Exemption requirements—Notice—Liability for tax.
. Passenger motor vehicles used primarily for ride sharing and ride sharing for persons with special transportation needs, as defined in RCW 46.74.010, are not subject to the motor vehicle excise tax authorized under this chapter if the vehicles are used as ride-sharing vehicles for thirty-six consecutive months beginning from the date of purchase.

. To qualify for the motor vehicle excise tax exemption for ride-sharing vehicles, passenger motor vehicles must:

.. Have a seating capacity of three or more passengers, including the driver;

.. Be used for ride sharing;

.. Be operated either within:

... The state's eight largest counties that are required to develop commute trip reduction plans as directed by chapter 70A.15 RCW;

... Other counties, or cities and towns within those counties, that elect to adopt and implement a commute trip reduction plan; or

... Other counties, where the vehicle is registered with or operated by a public transportation agency; and

.. Meet at least one of the following conditions:

... The vehicle must be operated by a public transportation agency for the benefit of the general public;

... The vehicle must be used by a major employer, as defined in RCW 70A.15.4010 as an element of its commute trip reduction program for their employees; or

... The vehicle must be owned and operated by individual employees and must be registered either with the employer as part of its commute trip reduction program or with a public transportation agency. Individual employee owned and operated motor vehicles will require certification that the vehicle is registered with a major employer or a public transportation agency. Major employers who own and operate motor vehicles for their employees must certify that the ride-sharing arrangement conforms to a carpool/vanpool element contained within their commute trip reduction program.

. The registered owner of a passenger motor vehicle described in subsection (2) of this section:

.. Shall notify the department upon the termination of the primary use of the vehicle in ride sharing or ride sharing for persons with special transportation needs; and

.. Is liable for the motor vehicle excise tax imposed under this chapter, prorated on the remaining months for which the vehicle is registered.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1514-S.SL.pdf?cite=2021%20c%20135%20§%209[2021 c 135 § 9]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201488[2020 c 20 § 1488]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6333-S.SL.pdf?cite=2014%20c%2097%20§%20502[2014 c 97 § 502]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20909[2010 c 161 § 909]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6699-S.SL.pdf?cite=1996%20c%20244%20§%207[1996 c 244 § 7]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5876-S.SL.pdf?cite=1993%20c%20488%20§%203[1993 c 488 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c142.pdf?cite=1982%20c%20142%20§%201[1982 c 142 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1980c166.pdf?cite=1980%20c%20166%20§%203[1980 c 166 § 3]; ]

== 82.44.035 - Valuation of vehicles.
. For the purpose of determining any locally imposed motor vehicle excise tax, the value of a truck or trailer shall be the latest purchase price of the vehicle, excluding applicable federal excise taxes, state and local sales or use taxes, transportation or shipping costs, or preparatory or delivery costs, multiplied by the following percentage based on year of service of the vehicle since last sale. The latest purchase year shall be considered the first year of service.

YEAR OF SERVICEPERCENTAGE110028136745554563773082592010161113121113914715316 or older0

YEAR OF SERVICE

PERCENTAGE

1

100

2

81

3

67

4

55

5

45

6

37

7

30

8

25

9

20

10

16

11

13

12

11

13

9

14

7

15

3

16 or older

0

. The reissuance of a certificate of title and registration certificate for a truck or trailer because of the installation of body or special equipment shall be treated as a sale, and the value of the truck or trailer at that time, as determined by the department from such information as may be available, shall be considered the latest purchase price.

. For the purpose of determining any locally imposed motor vehicle excise tax, the value of a vehicle other than a truck or trailer shall be eighty-five percent of the manufacturer's base suggested retail price of the vehicle when first offered for sale as a new vehicle, excluding any optional equipment, applicable federal excise taxes, state and local sales or use taxes, transportation or shipping costs, or preparatory or delivery costs, multiplied by the applicable percentage listed in this subsection (3) based on year of service of the vehicle.

If the manufacturer's base suggested retail price is unavailable or otherwise unascertainable at the time of initial registration in this state, the department shall determine a value equivalent to a manufacturer's base suggested retail price as follows:

.. The department shall determine a value using any information that may be available, including any guidebook, report, or compendium of recognized standing in the automotive industry or the selling price and year of sale of the vehicle. The department may use an appraisal by the county assessor. In valuing a vehicle for which the current value or selling price is not indicative of the value of similar vehicles of the same year and model, the department shall establish a value that more closely represents the average value of similar vehicles of the same year and model. The value determined in this subsection (3)(a) shall be divided by the applicable percentage listed in (b) of this subsection (3) to establish a value equivalent to a manufacturer's base suggested retail price and this value shall be multiplied by eighty-five percent.

.. The year the vehicle is offered for sale as a new vehicle shall be considered the first year of service.

YEAR OF SERVICEPERCENTAGE110028137246355564774183693210271126122413231421151616 or older10

YEAR OF SERVICE

PERCENTAGE

1

100

2

81

3

72

4

63

5

55

6

47

7

41

8

36

9

32

10

27

11

26

12

24

13

23

14

21

15

16

16 or older

10

. For purposes of this chapter, value shall exclude value attributable to modifications of a vehicle and equipment that are designed to facilitate the use or operation of the vehicle by a person with a disability.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20910[2010 c 161 § 910]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6247-S.SL.pdf?cite=2006%20c%20318%20§%201[2006 c 318 § 1]; ]

== 82.44.060 - Tax requirements—Payment of tax based on registration year—Transfer of ownership.
. Any locally imposed excise tax:

.. Is due at the time of registration of a vehicle;

.. Must be paid in full before any registration certificate or license tab may be issued;

.. Is in addition to any other vehicle license fees required by law;

.. Must be collected by the department, county auditor or other agent, or subagent appointed by the director of licensing before issuing the registration certificate;

.. Must be collected for each registration year; and

.. Must be levied for one full registration year beginning on the date of the calendar year designated by the department and ending on the same date of the next succeeding calendar year. For vehicles registered under chapter 46.87 RCW, proportional registration, and for vehicle dealer plates issued under chapter 46.70 RCW, the registration year is the period provided in those chapters. However, the tax shall in no case be less than two dollars except for proportionally registered vehicles.

. A vehicle is deemed registered for the first time in this state when the vehicle was not previously registered by this state for the registration year immediately preceding the registration year in which the application for registration is made or when the vehicle has been registered in another jurisdiction subsequent to any prior registration in this state.

. An additional tax may not be imposed under this chapter on any vehicle when the certificate of title is being transferred if the tax has already been paid for the registration year or fraction of a registration year in which transfer of ownership occurs.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20911[2010 c 161 § 911]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6247-S.SL.pdf?cite=2006%20c%20318%20§%203[2006 c 318 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c42.pdf?cite=1990%20c%2042%20§%20304[1990 c 42 § 304]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c222.pdf?cite=1981%20c%20222%20§%2012[1981 c 222 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%20233[1979 c 158 § 233]; 1975-'76 2nd ex.s. c 54 § 2; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c118.pdf?cite=1975%201st%20ex.s.%20c%20118%20§%2014[1975 1st ex.s. c 118 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c199.pdf?cite=1963%20c%20199%20§%204[1963 c 199 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2082.44.060[1961 c 15 § 82.44.060]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c269.pdf?cite=1957%20c%20269%20§%2015[1957 c 269 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c139.pdf?cite=1955%20c%20139%20§%2025[1955 c 139 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c144.pdf?cite=1943%20c%20144%20§%206[1943 c 144 § 6]; Rem. Supp. 1943 § 6312-120; prior:  1937 c 228 § 5; ]

== 82.44.065 - Appeal of valuation.
If the department determines a value for a vehicle equivalent to a manufacturer's base suggested retail price or the value of a truck or trailer under RCW 82.44.035, any person who pays a locally imposed tax for that vehicle may appeal the valuation to the department under chapter 34.05 RCW. If the taxpayer is successful on appeal, the department shall refund the excess tax in the manner provided in RCW 82.44.120.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20912[2010 c 161 § 912]; ( 2020 c 1 § 9 (Initiative Measure No. 976, approved November 5, 2019)); http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6247-S.SL.pdf?cite=2006%20c%20318%20§%205[2006 c 318 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c42.pdf?cite=1990%20c%2042%20§%20305[1990 c 42 § 305]; ]

== 82.44.090 - Penalty for issuing a dealer's license, plates, or a registration without collecting tax.
It is unlawful for the county auditor or any other person to issue a dealer's license or dealer's license plates or a registration or identification plates with respect to any motor vehicle without collecting, with the required vehicle license fee, the amount of any locally imposed motor vehicle excise tax due. Any violation of this section shall constitute a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20913[2010 c 161 § 913]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6247-S.SL.pdf?cite=2006%20c%20318%20§%206[2006 c 318 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2082.44.090[1961 c 15 § 82.44.090]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c144.pdf?cite=1943%20c%20144%20§%208[1943 c 144 § 8]; Rem. Supp. 1943 § 6312-122; prior:  1937 c 228 § 7; ]

== 82.44.100 - Tax receipt.
The department, county auditor or other agent, or subagent appointed by the director of licensing shall give to each person paying a locally imposed motor vehicle excise tax a receipt identifying the vehicle for which the tax is paid. The receipt may be incorporated in the receipt given for the vehicle license fee or dealer's license fee paid.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20914[2010 c 161 § 914]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6247-S.SL.pdf?cite=2006%20c%20318%20§%207[2006 c 318 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2082.44.100[1961 c 15 § 82.44.100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c144.pdf?cite=1943%20c%20144%20§%209[1943 c 144 § 9]; Rem. Supp. 1943 § 6312-123; prior:  1937 c 228 § 8; ]

== 82.44.120 - Claims for refunds.
. Refunds of locally imposed motor vehicle excise taxes must be handled in the same manner and under the same terms and conditions as provided in RCW 46.68.010.

. A claim for a refund may be made by a person who:

.. Is not seeking a full refund; and

.. Believes the amount of the locally imposed motor vehicle excise tax paid was incorrect or too much.

. When a claim for a refund is made as provided in subsection (2) of this section, the department shall:

.. Determine the amount of the locally imposed motor vehicle excise tax that had been greater than the amount actually due, if any; and

.. Certify to the state treasurer the amount of the partial refund due.

. Before a local government subject to this chapter may impose a motor vehicle excise tax, the local government shall contract with the department for reimbursement for any refunds paid to a person by the treasurer.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20915[2010 c 161 § 915]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6247-S.SL.pdf?cite=2006%20c%20318%20§%208[2006 c 318 § 8]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20403[2003 c 53 § 403]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1379.SL.pdf?cite=1993%20c%20307%20§%203[1993 c 307 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c42.pdf?cite=1990%20c%2042%20§%20307[1990 c 42 § 307]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c68.pdf?cite=1989%20c%2068%20§%202[1989 c 68 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c26.pdf?cite=1983%20c%2026%20§%203[1983 c 26 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c120.pdf?cite=1979%20c%20120%20§%202[1979 c 120 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c278.pdf?cite=1975%201st%20ex.s.%20c%20278%20§%2095[1975 1st ex.s. c 278 § 95]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c54.pdf?cite=1974%20ex.s.%20c%2054%20§%204[1974 ex.s. c 54 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c121.pdf?cite=1967%20c%20121%20§%202[1967 c 121 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c199.pdf?cite=1963%20c%20199%20§%205[1963 c 199 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2082.44.120[1961 c 15 § 82.44.120]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c196.pdf?cite=1949%20c%20196%20§%2018[1949 c 196 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1945c152.pdf?cite=1945%20c%20152%20§%203[1945 c 152 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c144.pdf?cite=1943%20c%20144%20§%2011[1943 c 144 § 11]; Rem. Supp. 1949 § 6312-125; ]

== 82.44.125 - Vehicles subject to tax—Exemptions.
. The motor vehicle excise tax authorized under this chapter applies to the following vehicles:

.. Commercial trailers, as defined in RCW 46.04.136;

.. Farm trucks registered under RCW 46.16A.425;

.. Fixed load vehicles, as defined in RCW 46.04.186;

.. Motor homes, as defined in RCW 46.04.305;

.. Motor trucks, as defined in RCW 46.04.310, with a scale weight greater than six thousand pounds;

.. Motor vehicles, as defined in RCW 46.04.320; and

.. Trailers, as defined in RCW 46.04.620.

. The motor vehicle excise tax authorized under this chapter does not apply to the following vehicles:

.. Campers, as defined in RCW 46.04.085;

.. Dock and warehouse tractors and their cars or trailers;

.. Equipment not designed primarily for use on public highways;

.. Exempt registered vehicles;

.. Lumber carriers of the type known as spiders;

.. Mobile homes, as defined in RCW 46.04.302;

.. Passenger motor vehicles, as described in RCW 82.44.015;

.. Travel trailers, as defined in RCW 46.04.623;

.. Vehicles not used on the public highways; and

.. Vehicles owned by nonresident military personnel of the armed forces of the United States stationed in the state of Washington if the nonresident military member was a nonresident of this state when enlisted into military service.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%20908[2010 c 161 § 908]; ]

== 82.44.135 - Local government must contract with department of licensing.
. Before a local government subject to this chapter may impose a motor vehicle excise tax, the local government must contract with the department for the collection of the tax. The department may charge a reasonable amount, not to exceed one percent of tax collections, or two and one-half percent during the 2019-2021 biennium, for the administration and collection of the tax.

. For fiscal year 2021, the department shall charge a minimum of seven million eight hundred two thousand dollars, which is the reasonable amount aimed at achieving full cost recovery for the administration and collection of a motor vehicle excise tax. The amount of the full reimbursement for the administration and collection of the motor vehicle excise tax must be deducted before distributing any revenues to a regional transit authority. Any reimbursement to ensure full cost recovery beyond the amount specified in this subsection may be negotiated between the department and the regional transit authority if full cost recovery has not been achieved, or if based on emergent issues.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2322-S.SL.pdf?cite=2020%20c%20219%20§%20706[2020 c 219 § 706]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6247-S.SL.pdf?cite=2006%20c%20318%20§%209[2006 c 318 § 9]; ]

== 82.44.140 - Director of licensing may act.
Any duties required by this chapter to be performed by the county auditor may be performed by any other person designated by the director of licensing and authorized by him or her to receive motor vehicle license fees and issue receipt therefor.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20337[2013 c 23 § 337]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%20237[1979 c 158 § 237]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c121.pdf?cite=1967%20c%20121%20§%203[1967 c 121 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2082.44.140[1961 c 15 § 82.44.140]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c144.pdf?cite=1943%20c%20144%20§%2013[1943 c 144 § 13]; Rem. Supp. 1943 § 6312-127; ]

== 82.44.190 - Transportation infrastructure account—Deposits and distributions—Subaccounts.
The transportation infrastructure account is hereby created in the state treasury. Public and private entities may deposit moneys in the transportation infrastructure account from federal, state, local, or private sources. Proceeds from bonds or other financial instruments sold to finance surface transportation projects from the transportation infrastructure account shall be deposited into the account. Principal and interest payments made on loans from the transportation infrastructure account shall be deposited into the account. Moneys in the account shall be available for purposes specified in RCW 82.44.195. Expenditures from the transportation infrastructure account shall be subject to appropriation by the legislature. To the extent required by federal law or regulations promulgated by the United States secretary of transportation, the state treasurer is authorized to create separate subaccounts within the transportation infrastructure account.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5316.SL.pdf?cite=2017%203rd%20sp.s.%20c%2025%20§%2049[2017 3rd sp.s. c 25 § 49]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2727-S.SL.pdf?cite=1996%20c%20262%20§%202[1996 c 262 § 2]; ]

== 82.44.195 - Transportation infrastructure account—Highway infrastructure account—Finding—Intent—Purpose—1996 c 262.
The legislature finds that new financing mechanisms are necessary to provide greater flexibility and additional funds for needed transportation infrastructure projects in the state. The creation of a financing mechanism, like the one contained in section 350 of the national highway system designation act of 1995, P.L. 104-59, relating to a state infrastructure bank program, will enable the state and local jurisdictions to use federal, state, local, or private funds to construct surface transportation projects for various modes of transportation. It is the intent of the legislature that accounts be created in the state treasury and dedicated funding sources be established to generate revenue to support transportation projects financed with the proceeds of bonds or other financial instruments issued against this dedicated revenue and other revenues which may be available to these accounts. P.L. 104-59 allows the deposit of certain federal highway and transit funds into these accounts to leverage other forms of investment in transportation infrastructure by expanding the eligible uses of the federal funds. Other public and private entities may also deposit funds into these accounts to leverage transportation investments. The purpose of chapter 262, Laws of 1996 is to provide, from these accounts, authorization for loans, grants, or other means of assistance, in amounts equal to all or part of the cost, to public or private entities building surface transportation facilities in this state. It is the further intent of the legislature that projects representing critical mobility or economic development needs and involving various transportation modes and jurisdictions receive top priority in the use of these funds. Funds from the accounts created in chapter 262, Laws of 1996 may be used to support the issuance of public or private debt, to provide credit enhancement for such debt, for direct loans to public or private entities, or for other purposes necessary to facilitate investment in surface transportation facilities in this state.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2727-S.SL.pdf?cite=1996%20c%20262%20§%201[1996 c 262 § 1]; ]

== 82.44.200 - Electric vehicle account.
The electric vehicle account is created in the transportation infrastructure account. Proceeds from the principal and interest payments made on loans from the account must be deposited into the account. Expenditures from the account may be used only for the purposes specified in RCW 47.04.350, 82.08.9999, and 82.12.9999, and the support of other transportation electrification and alternative fuel related purposes, including RCW 47.01.520. Moneys in the account may be spent only after appropriation.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1287-S2.SL.pdf?cite=2021%20c%20300%20§%205[2021 c 300 § 5]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2042-S2.SL.pdf?cite=2019%20c%20287%20§%2015[2019 c 287 § 15]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5987-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2044%20§%20404[2015 3rd sp.s. c 44 § 404]; ]

== 82.44.900 - Severability—Construction—1961 c 15.
If any provision of this chapter relating either to the apportionment or allocation of the revenue derived from the excise tax thereby imposed, or to any appropriation made by this chapter, be adjudged unconstitutional, such adjudication shall not be held to render unconstitutional or ineffectual the remaining portions of said chapter or any part thereof: PROVIDED, HOWEVER, That except as otherwise hereinabove provided by this section, if any section or part of a section of this chapter be adjudged unconstitutional, this entire chapter shall thereupon be and become inoperative and of no force or effect whatsoever.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c15.pdf?cite=1961%20c%2015%20§%2082.44.900[1961 c 15 § 82.44.900]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c144.pdf?cite=1943%20c%20144%20§%2017[1943 c 144 § 17]; Rem. Supp. 1943 § 6312-131; ]

