= 82.41 - Multistate motor fuel tax agreement.
:toc:

== 82.41.010 - Purpose.
It is the purpose of this chapter to simplify the confusing, unnecessarily duplicative, and burdensome motor fuel use tax licensing, reporting, and remittance requirements imposed on motor carriers involved in interstate commerce by authorizing the state of Washington to participate in a multistate motor fuel tax agreement for the administration, collection, and enforcement of those states' motor fuel use taxes.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c161.pdf?cite=1982%20c%20161%20§%201[1982 c 161 § 1]; ]

== 82.41.020 - Definitions.
As used in this chapter unless the context clearly requires otherwise:

. "Department" means the department of licensing;

. "Motor fuel" means all combustible gases and liquids used for the generation of power for propulsion of motor vehicles;

. "Motor carrier" means an individual, partnership, firm, association, or private or public corporation engaged in interstate commercial operation of motor vehicles, any part of which is within this state or any other state which is party to an agreement under this chapter;

. "State" means a state, territory, or possession of the United States, the District of Columbia, a foreign country, or a state or province of a foreign country;

. "Base state" means the state in which the motor carrier is legally domiciled, or in the case of a motor carrier who has no legal domicile, the state from or in which the motor carrier's vehicles are most frequently dispatched, garaged, serviced, maintained, operated, or otherwise controlled;

. "Agreement" means a motor fuel tax agreement under this chapter;

. "Licensee" means a motor carrier who has been issued a fuel tax license under a motor fuel tax agreement.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c161.pdf?cite=1982%20c%20161%20§%202[1982 c 161 § 2]; ]

== 82.41.030 - Motor fuel tax cooperative agreement authorized—Prohibition.
The department may enter into a motor fuel tax cooperative agreement with another state or states which provides for the administration, collection, and enforcement of each state's motor fuel taxes on motor fuel used by motor carriers. The agreement shall not contain any provision which exempts any motor vehicle, owner, or operator from complying with the laws, rules, and regulations pertaining to vehicle licensing, size, weight, load, or operation of motor vehicles upon the public highways of this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c161.pdf?cite=1982%20c%20161%20§%203[1982 c 161 § 3]; ]

== 82.41.040 - Amount of tax collected for this state.
The amount of the tax imposed and collected on behalf of this state under an agreement entered into under this chapter shall be determined as provided in chapter 82.38 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1225.SL.pdf?cite=1995%20c%20274%20§%2026[1995 c 274 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c161.pdf?cite=1982%20c%20161%20§%204[1982 c 161 § 4]; ]

== 82.41.050 - Provisions of agreement.
An agreement entered into under this chapter may provide for:

. Defining the classes of motor vehicles upon which taxes are to be collected under the agreement;

. Establishing methods for base state fuel tax licensing, license revocation, and tax collection from motor carriers on behalf of the states which are parties to the agreement;

. Establishing procedures for the granting of credits or refunds on the purchase of excess tax-paid fuel;

. Defining conditions and criteria relative to bonding requirements, including criteria for exemption from bonding;

. Establishing tax reporting periods not to exceed one calendar quarter, and tax report due dates not to exceed one calendar month after the close of the reporting period;

. Penalties and interest for filing of tax reports after the due dates prescribed by the agreement;

. Establishing procedures for forwarding of fuel taxes, penalties, and interest collected on behalf of another state to that state;

. Recordkeeping requirements for licensees; and

. Any additional provisions which will facilitate the administration of the agreement.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c161.pdf?cite=1982%20c%20161%20§%205[1982 c 161 § 5]; ]

== 82.41.070 - Audits.
The agreement may require the department to perform audits of licensees, or persons required to be licensed, based in this state to determine whether motor fuel taxes to be collected under the agreement have been properly reported and paid to each state party to the agreement. The agreement may authorize other states to perform audits on licensees, or persons required to be licensed, based in their states on behalf of the state of Washington and forward the audit findings to the department. Such findings may be served upon the licensee or such other person in the same manner as audits performed by the department.

The agreement shall not preclude the department from auditing the records of any person who has used motor fuels in this state. Any licensee or person required to be licensed from whom the department has requested records shall make the records available at the location designated by the department or may request the department to audit such records at that licensee's or person's place of business. If the place of business is located outside this state, the department may require the licensee or such other person to reimburse the department for authorized per diem and travel expenses.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c161.pdf?cite=1982%20c%20161%20§%207[1982 c 161 § 7]; ]

== 82.41.080 - Investigatory power.
The department may initiate and conduct investigations as may be reasonably necessary to establish the existence of any alleged violations of or noncompliance with this chapter or any rules issued hereunder.

For the purpose of any investigation or proceeding under this chapter, the director or any officer designated by the director may administer oaths and affirmations, subpoena witnesses, compel their attendance, take evidence, and require the production of any books, papers, correspondence, memoranda, agreements, or other documents or records which the director deems relevant or material to the inquiry.

In case of contumacy by or refusal to obey a subpoena issued to any person, any court of competent jurisdiction, upon application by the director, may issue to that person an order requiring him or her to appear before the director, or the officer designated by the director, to produce testimony or other evidence touching the matter under investigation or in question. The failure to obey an order of the court may be punishable by contempt.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20334[2013 c 23 § 334]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c161.pdf?cite=1982%20c%20161%20§%208[1982 c 161 § 8]; ]

== 82.41.090 - Appeal procedures.
The agreement shall specify procedures by which a licensee may appeal a license revocation or audit assessment by the department. Such appeal procedures shall be in accordance with chapters 34.05 and 82.38 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c161.pdf?cite=1982%20c%20161%20§%209[1982 c 161 § 9]; ]

== 82.41.100 - Exchange of information.
The agreement may require each state to forward to other states any information available which relates to the acquisition, sale, use, or movement of motor fuels by any licensee or person required to be licensed. The department may further disclose to other states information which relates to the persons, offices, motor vehicles and other real and personal property of persons licensed or required to be licensed under the agreement.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c161.pdf?cite=1982%20c%20161%20§%2010[1982 c 161 § 10]; ]

== 82.41.110 - Construction and application.
This chapter shall be applied and construed to effectuate its general purpose to make uniform the law with respect to the subject of this chapter among states enacting it for the purpose of participating in a multistate motor fuel tax agreement.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c161.pdf?cite=1982%20c%20161%20§%2011[1982 c 161 § 11]; ]

== 82.41.120 - Implementing rules required.
The department shall adopt such rules as are necessary to implement this chapter and any agreement entered into under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c161.pdf?cite=1982%20c%20161%20§%2012[1982 c 161 § 12]; ]

