= 82.58 - Simplified sales and use tax administration act.
:toc:

== 82.58.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Agreement" means the streamlined sales and use tax agreement as adopted.

. "Certified automated system" means software certified jointly by the states that are signatories to the agreement to calculate the tax imposed by each jurisdiction on a transaction, determine the amount of tax to remit to the appropriate state, and maintain a record of the transaction.

. "Certified service provider" means an agent certified jointly by the states that are signatories to the agreement to perform all of the seller's sales tax functions.

. "Person" means an individual, trust, estate, fiduciary, partnership, limited liability company, limited liability partnership, corporation, or any other legal entity.

. "Sales tax" means the tax levied under chapter 82.08 RCW.

. "Seller" means any person making sales, leases, or rentals of personal property or services.

. "State" means any state of the United States and the District of Columbia.

. "Use tax" means the tax levied under chapter 82.12 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6342-S.SL.pdf?cite=2002%20c%20267%20§%202[2002 c 267 § 2]; ]

== 82.58.020 - Multistate discussions.
 For the purposes of reviewing or amending the agreement embodying the simplification requirements in RCW 82.58.050, the state shall enter into multistate discussions. For purposes of these discussions, the state shall be represented by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2617-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%207%20§%2017[2010 1st sp.s. c 7 § 17]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6342-S.SL.pdf?cite=2002%20c%20267%20§%204[2002 c 267 § 4]; ]

== 82.58.030 - Streamlined sales and use tax agreement.
The department shall enter into the streamlined sales and use tax agreement with one or more states to simplify and modernize sales and use tax administration in order to substantially reduce the burden of tax compliance for all sellers and for all types of commerce. In furtherance of the agreement, the department may act jointly with other states that are members of the agreement to establish standards for certification of a certified service provider and certified automated system and establish performance standards for multistate sellers. The department is further authorized to take other actions reasonably required to implement this chapter. Other actions authorized by this section include, but are not limited to, the adoption of rules and the joint procurement, with other member states, of goods and services in furtherance of the cooperative agreement. The department, or the department's designee, may represent this state before the other states that are signatories to the agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6342-S.SL.pdf?cite=2002%20c%20267%20§%205[2002 c 267 § 5]; ]

== 82.58.040 - State adoption of agreement—Existing laws unaffected.
No provision of the agreement authorized by this chapter in whole or part invalidates or amends any provision of the law of this state. Adoption of the agreement by this state does not amend or modify any law of this state. Implementation of any condition of the agreement in this state, whether adopted before, at, or after membership of this state in the agreement, must be by the action of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6342-S.SL.pdf?cite=2002%20c%20267%20§%206[2002 c 267 § 6]; ]

== 82.58.050 - Requirements for agreement.
The department shall not enter into the streamlined sales and use tax agreement unless the agreement requires each state to abide by the requirements in this section.

. The agreement must set restrictions to limit over time the number of state rates.

. The agreement must establish uniform standards for:

.. The sourcing of transactions to taxing jurisdictions;

.. The administration of exempt sales; and

.. Sales and use tax returns and remittances.

. The agreement must provide a central, electronic registration system that allows a seller to register to collect and remit sales and use taxes for all signatory states.

. The agreement must provide that registration with the central registration system and the collection of sales and use taxes in the signatory states will not be used as a factor in determining whether the seller has nexus with a state for any tax.

. The agreement must provide for reduction of the burdens of complying with local sales and use taxes by:

.. Restricting variances between the state and local tax bases;

.. Requiring states to administer any sales and use taxes levied by local jurisdictions within the state so that sellers collecting and remitting these taxes will not have to register or file returns with, remit funds to, or be subject to independent audits from local taxing jurisdictions;

.. Restricting the frequency of changes in the local sales and use tax rates and setting effective dates for the application of local jurisdictional boundary changes to local sales and use taxes; and

.. Providing notice of changes in local sales and use tax rates and of changes in the boundaries of local taxing jurisdictions.

. The agreement must outline any monetary allowances that are to be provided by the states to sellers or certified service providers. The agreement must allow for a joint public and private sector study of the compliance cost on sellers and certified service providers to collect sales and use taxes for state and local governments under various levels of complexity.

. The agreement must require each state to certify compliance with the terms of the agreement before joining and to maintain compliance, under the laws of the member state, with all provisions of the agreement while a member.

. The agreement must require each state to adopt a uniform policy for certified service providers that protects the privacy of consumers and maintains the confidentiality of tax information.

. The agreement must provide for the appointment of an advisory council of private sector representatives and an advisory council of nonmember state representatives to consult with in the administration of the agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6515.SL.pdf?cite=2004%20c%20153%20§%20401[2004 c 153 § 401]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6342-S.SL.pdf?cite=2002%20c%20267%20§%207[2002 c 267 § 7]; ]

== 82.58.060 - General purpose of agreement.
The agreement authorized by this chapter is an accord among individual cooperating sovereigns in furtherance of their governmental functions. The agreement provides a mechanism among the member states to establish and maintain a cooperative, simplified system for the application and administration of sales and use taxes under the duly adopted law of each member state.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6342-S.SL.pdf?cite=2002%20c%20267%20§%208[2002 c 267 § 8]; ]

== 82.58.070 - Agreement for benefit of member states only—No legal action.
. The agreement authorized by this chapter binds and inures only to the benefit of this state and the other member states. No person, other than a member state, is an intended beneficiary of the agreement. Any benefit to a person other than a state is established by the law of this state and the other member states and not by the terms of the agreement.

. Consistent with subsection (1) of this section, no person has any cause of action or defense under the agreement or by virtue of this state's approval of the agreement. No person may challenge, in any action brought under any provision of law, any action or inaction by any department, agency, other instrumentality of this state, or any political subdivision of this state on the ground that the action or inaction is inconsistent with the agreement.

. No law of this state, or the application thereof, may be declared invalid as to any person or circumstance on the ground that the provision or application is inconsistent with the agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6342-S.SL.pdf?cite=2002%20c%20267%20§%209[2002 c 267 § 9]; ]

== 82.58.080 - Certified service provider—Certified automated system.
. A certified service provider is the agent of a seller, with whom the certified service provider has contracted, for the collection and remittance of sales and use taxes. As the seller's agent, the certified service provider is liable for sales and use tax due each member state on all sales transactions it processes for the seller except as set out in this section. A seller that contracts with a certified service provider is not liable to the state for sales or use tax due on transactions processed by the certified service provider unless the seller misrepresented the type of items it sells or committed fraud. In the absence of probable cause to believe that the seller has committed fraud or made a material misrepresentation, the seller is not subject to audit on the transactions processed by the certified service provider. A seller is subject to audit for transactions not processed by the certified service provider. The member states acting jointly may perform a system check of the seller and review the seller's procedures to determine if the certified service provider's system is functioning properly and the extent to which the seller's transactions are being processed by the certified service provider.

. A person that provides a certified automated system is responsible for the proper functioning of that system and is liable to the state for underpayments of tax attributable to errors in the functioning of the certified automated system. A seller that uses a certified automated system remains responsible and is liable to the state for reporting and remitting tax.

. A seller that has a proprietary system for determining the amount of tax due on transactions and has signed an agreement establishing a performance standard for that system is liable for the failure of the system to meet the performance standard.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6342-S.SL.pdf?cite=2002%20c%20267%20§%2010[2002 c 267 § 10]; ]

== 82.58.090 - Legislation to conform state law.
Upon becoming a member of the streamlined sales and use tax agreement, the department shall prepare legislation conforming state law as necessary and shall provide such legislation to the fiscal committees of the legislature.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6342-S.SL.pdf?cite=2002%20c%20267%20§%2011[2002 c 267 § 11]; ]

== 82.58.900 - Short title.
This chapter shall be known and cited as the "simplified sales and use tax administration act."

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6342-S.SL.pdf?cite=2002%20c%20267%20§%201[2002 c 267 § 1]; ]

