= 82.51 - Heavy equipment rental tax.
:toc:

== 82.51.010 - Heavy equipment rental tax imposed—Rate—Reporting and remittance—Collection—Penalty—Definitions.
. Beginning January 1, 2022, there is levied and collected a heavy equipment rental tax equal to one and one-quarter percent of the rental price on each rental in this state of heavy equipment rental property to a consumer by a heavy equipment rental property dealer.

. [Empty]
.. Each heavy equipment rental property dealer shall add the heavy equipment rental tax to the rental invoice of any rental subject to the heavy equipment rental tax under this section. All heavy equipment rental taxes shall be reported and remitted to the department in a manner and frequency consistent with the reporting and remittance of state sales taxes, and on such forms as the department shall prescribe and approve.

.. The tax required by this section, to be collected by the heavy equipment rental property dealer, is deemed to be held in trust by the heavy equipment rental property dealer until paid to the department. Any heavy equipment rental property dealer who appropriates or converts the tax collected to the dealer's own use or to any use other than the payment of the tax to the extent that the money required to be collected is not available for payment on the due date as prescribed in this chapter is guilty of a gross misdemeanor.

. The definitions in this subsection apply throughout this chapter, unless the context clearly requires otherwise.

.. "Consumer" means the same as provided in RCW 82.04.190.

.. "Heavy equipment rental property" and "heavy equipment rental property dealer" mean the same as provided in RCW 84.36.597.

.. "Rental price" means the same as "sales price" as defined in RCW 82.08.010.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5628-S.SL.pdf?cite=2020%20c%20301%20§%202[2020 c 301 § 2]; ]

== 82.51.020 - Deposits in motor vehicle fund and multimodal transportation account.
. Fifty percent of the receipts from the tax imposed in RCW 82.51.010 must be deposited in the motor vehicle fund created in RCW 46.68.070; and

. Fifty percent of the receipts from the tax imposed in RCW 82.51.010 must be deposited in the multimodal transportation account created in RCW 47.66.070.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5628-S.SL.pdf?cite=2020%20c%20301%20§%203[2020 c 301 § 3]; ]

== 82.51.030 - Application—Exemptions.
. The heavy equipment rental tax does not apply to any transaction that the state is prohibited from taxing under the Constitution of this state or the Constitution or laws of the United States, or to the rental of heavy equipment rental property to the state or any of its political subdivisions, or to any municipal corporation.

. The heavy equipment rental tax applies to all rentals of heavy equipment rental property made from a rental location in this state where the customer picks up the heavy equipment rental property or from where the heavy equipment rental property is delivered to the consumer in this state. The heavy equipment rental tax does not apply to rentals of heavy equipment rental property made from a rental location in this state and delivered to the consumer outside this state or made from a rental location outside of this state and delivered to the consumer in this state.

. There are no other exemptions from this tax.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5628-S.SL.pdf?cite=2020%20c%20301%20§%204[2020 c 301 § 4]; ]

== 82.51.040 - Administration.
Chapter 82.32 RCW applies to the administration of the heavy equipment rental tax in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5628-S.SL.pdf?cite=2020%20c%20301%20§%205[2020 c 301 § 5]; ]

== 82.51.900 - Automatic expiration date and tax preference performance statement exemption—2020 c 301.
The provisions of RCW 82.32.805 and 82.32.808 do not apply to this act.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5628-S.SL.pdf?cite=2020%20c%20301%20§%2010[2020 c 301 § 10]; ]

