= 82.75 - Tax deferrals for biotechnology and medical device manufacturing businesses.
:toc:

== 82.75.005 - Findings—Intent.
The legislature finds that the state's economy is increasingly dependent on the expansion of knowledge-based sectors, including the life sciences. The legislature also finds that commercial enterprises in the life sciences create high-wage, high-skilled jobs that are part of the state's effort to encourage economic diversification and stability. However, the legislature also finds that commercial life sciences businesses, particularly in biotechnology product and medical device manufacturing, incur significant costs associated with capital infrastructure and job training often years before a product is licensed for marketing or a facility is licensed for manufacturing by governmental agencies in the United States and abroad. The legislature also finds that current state tax policy discourages the growth of these companies in two ways: (1) Washington state's higher rate of taxation compared with other states and nations encourages the export of intellectual property and commercial operations out of Washington; and (2) taxing these businesses before facilities, or products produced therein, are licensed for marketing by regulatory agencies.

The legislature further finds that targeted tax incentives may encourage the formation, expansion, and retention of commercial operations within the life sciences sector. The legislature also finds that tax incentives should be subject to the same rigorous requirements for efficiency and accountability as are other expenditure programs, and that tax incentives should therefore be focused to provide the greatest possible return on the state's investment.

For these reasons, the legislature hereby establishes a tax deferral program for commercial manufacturing facilities in this sector. The legislature declares that these limited programs serve the vital public purposes of incenting expenditures in commercial life science operations and the development of employment opportunities in this state. The legislature further declares its intent to create a contract within the meaning of Article I, section 23 of the state Constitution as to those businesses that make capital investments in consideration of the tax deferral program established in this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2640-S.SL.pdf?cite=2006%20c%20178%20§%201[2006 c 178 § 1]; ]

== 82.75.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Applicant" means a person applying for a tax deferral under this chapter.

. "Biotechnology" means a technology based on the science of biology, microbiology, molecular biology, cellular biology, biochemistry, or biophysics, or any combination of these, and includes, but is not limited to, recombinant DNA techniques, genetics and genetic engineering, cell fusion techniques, and new bioprocesses, using living organisms, or parts of organisms.

. "Biotechnology product" means any virus, therapeutic serum, antibody, protein, toxin, antitoxin, vaccine, blood, blood component or derivative, allergenic product, or analogous product produced through the application of biotechnology that is used in the prevention, treatment, or cure of diseases or injuries to humans.

. "Department" means the department of revenue.

. [Empty]
.. "Eligible investment project" means an investment in qualified buildings or qualified machinery and equipment, including labor and services rendered in the planning, installation, and construction of the project.

.. The lessor or owner of a qualified building is not eligible for a deferral unless:

... The underlying ownership of the buildings, machinery, and equipment vests exclusively in the same person; or

...(A) The lessor by written contract agrees to pass the economic benefit of the deferral to the lessee;

(B) The lessee that receives the economic benefit of the deferral agrees in writing with the department to complete the annual tax performance report required under RCW 82.75.070; and

(C) The economic benefit of the deferral passed to the lessee is no less than the amount of tax deferred by the lessor and is evidenced by written documentation of any type of payment, credit, or other financial arrangement between the lessor or owner of the qualified building and the lessee.

. [Empty]
.. "Initiation of construction" means the date that a building permit is issued under the building code adopted under RCW 19.27.031 for:

... Construction of the qualified building, if the underlying ownership of the building vests exclusively with the person receiving the economic benefit of the deferral;

... Construction of the qualified building, if the economic benefits of the deferral are passed to a lessee as provided in subsection (5)(b)(ii)(A) of this section; or

... Tenant improvements for a qualified building, if the economic benefits of the deferral are passed to a lessee as provided in subsection (5)(b)(ii)(A) of this section.

.. "Initiation of construction" does not include soil testing, site clearing and grading, site preparation, or any other related activities that are initiated before the issuance of a building permit for the construction of the foundation of the building.

.. If the investment project is a phased project, "initiation of construction" applies separately to each phase.

. "Manufacturing" has the meaning provided in RCW 82.04.120.

. "Medical device" means an instrument, apparatus, implement, machine, contrivance, implant, in vitro reagent, or other similar or related article, including any component, part, or accessory, that is designed or developed and:

.. Recognized in the national formulary, or the United States pharmacopeia, or any supplement to them;

.. Intended for use in the diagnosis of disease, or in the cure, mitigation, treatment, or prevention of disease or other conditions in human beings or other animals; or

.. Intended to affect the structure or any function of the body of human beings or other animals, and which does not achieve any of its primary intended purposes through chemical action within or on the body of human beings or other animals and which is not dependent upon being metabolized for the achievement of any of its principal intended purposes.

. "Person" has the meaning provided in RCW 82.04.030.

. "Qualified buildings" means construction of new structures, and expansion or renovation of existing structures for the purpose of increasing floor space or production capacity used for biotechnology product manufacturing or medical device manufacturing activities, including plant offices, commercial laboratories for process development, quality assurance and quality control, and warehouses or other facilities for the storage of raw material or finished goods if the facilities are an essential or an integral part of a factory, plant, or laboratory used for biotechnology product manufacturing or medical device manufacturing. If a building is used partly for biotechnology product manufacturing or medical device manufacturing and partly for other purposes, the applicable tax deferral must be determined by apportionment of the costs of construction under rules adopted by the department.

. "Qualified machinery and equipment" means all new industrial and research fixtures, equipment, and support facilities that are an integral and necessary part of a biotechnology product manufacturing or medical device manufacturing operation. "Qualified machinery and equipment" includes: Computers; software; data processing equipment; laboratory equipment; manufacturing components such as belts, pulleys, shafts, and moving parts; molds, tools, and dies; operating structures; and all equipment used to control or operate the machinery.

. "Recipient" means a person receiving a tax deferral under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5402.SL.pdf?cite=2020%20c%20139%20§%2045[2020 c 139 § 45]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/3066-S.SL.pdf?cite=2010%20c%20114%20§%20145[2010 c 114 § 145]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%201033[2009 c 549 § 1033]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2640-S.SL.pdf?cite=2006%20c%20178%20§%202[2006 c 178 § 2]; ]

== 82.75.020 - Application for tax deferral.
Application for deferral of taxes under this chapter must be made before initiation of the construction of the investment project or acquisition of equipment or machinery. The application must be made to the department in a form and manner prescribed by the department. The application must contain information regarding the location of the investment project, the applicant's average employment in the state for the prior year, estimated or actual new employment related to the project, estimated or actual wages of employees related to the project, estimated or actual costs, time schedules for completion and operation, and other information required by the department. The department must rule on the application within sixty days.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/3066-S.SL.pdf?cite=2010%20c%20114%20§%20146[2010 c 114 § 146]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2640-S.SL.pdf?cite=2006%20c%20178%20§%203[2006 c 178 § 3]; ]

== 82.75.040 - Repayment of deferred taxes.
. Except as provided in subsection (2) of this section and RCW 82.32.534, taxes deferred under this chapter need not be repaid.

. [Empty]
.. If, on the basis of the tax performance report under RCW 82.32.534 or other information, the department finds that an investment project is used for purposes other than qualified biotechnology product manufacturing or medical device manufacturing activities at any time during the calendar year in which the eligible investment project is certified by the department as having been operationally completed, or at any time during any of the seven succeeding calendar years, a portion of deferred taxes is immediately due and payable according to the following schedule:

Year in which use occurs% of deferred taxes due1100%287.5%375%462.5%550%637.5%725%812.5%

Year in which use occurs

% of deferred taxes due

1

100%

2

87.5%

3

75%

4

62.5%

5

50%

6

37.5%

7

25%

8

12.5%

.. If the economic benefits of the deferral are passed to a lessee as provided in RCW 82.75.010, the lessee is responsible for payment to the extent the lessee has received the economic benefit.

. For a violation of subsection (2)(a) of this section, the department must assess interest at the rate provided for delinquent taxes, but not penalties, retroactively to the date of deferral. The debt for deferred taxes will not be extinguished by insolvency or other failure of the recipient. Transfer of ownership does not terminate the deferral. The deferral is transferred, subject to the successor meeting the eligibility requirements of this chapter, for the remaining periods of the deferral.

. Notwithstanding subsection (2) of this section or RCW 82.32.534, deferred taxes on the following need not be repaid:

.. Machinery and equipment, and sales of or charges made for labor and services, which at the time of purchase would have qualified for exemption under RCW 82.08.02565; and

.. Machinery and equipment which at the time of first use would have qualified for exemption under RCW 82.12.02565.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1296-S.SL.pdf?cite=2017%20c%20135%20§%2041[2017 c 135 § 41]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/3066-S.SL.pdf?cite=2010%20c%20114%20§%20147[2010 c 114 § 147]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2640-S.SL.pdf?cite=2006%20c%20178%20§%205[2006 c 178 § 5]; ]

== 82.75.050 - Application of chapter  82.32 RCW.
Chapter 82.32 RCW applies to the administration of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2640-S.SL.pdf?cite=2006%20c%20178%20§%206[2006 c 178 § 6]; ]

== 82.75.060 - Confidentiality of applications.
Applications approved by the department under this chapter are not confidential and are subject to disclosure.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1597-S2.SL.pdf?cite=2010%20c%20106%20§%20110[2010 c 106 § 110]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2640-S.SL.pdf?cite=2006%20c%20178%20§%207[2006 c 178 § 7]; ]

== 82.75.070 - Annual tax performance report requirement.
. Each recipient of a deferral of taxes granted under this chapter must file a complete annual tax performance report with the department under RCW 82.32.534. If the economic benefits of the deferral are passed to a lessee as provided in RCW 82.75.010(5), the lessee must file a complete annual tax performance report, and the applicant is not required to file the annual tax performance report.

. A recipient who must repay deferred taxes under RCW 82.75.040(2) because the department has found that an investment project is used for purposes other than qualified biotechnology product manufacturing or medical device manufacturing activities is no longer required to file annual tax performance reports under RCW 82.32.534 beginning on the date an investment project is used for nonqualifying purposes.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1296-S.SL.pdf?cite=2017%20c%20135%20§%2042[2017 c 135 § 42]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/3066-S.SL.pdf?cite=2010%20c%20114%20§%20144[2010 c 114 § 144]; ]

