= 82.86 - 988 behavioral health crisis response and suicide prevention line tax.
:toc:

== 82.86.010 - Definitions. (Effective October 1, 2021.)
. The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

.. "988 crisis hotline" has the same meaning as in RCW 71.24.025.

.. "Crisis call center hub" has the same meaning as in RCW 71.24.025.

. The definitions in RCW 82.14B.020 apply to this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1477-S2.SL.pdf?cite=2021%20c%20302%20§%20201[2021 c 302 § 201]; ]

== 82.86.020 - Tax imposed. (Effective October 1, 2021.)
. [Empty]
.. A statewide 988 behavioral health crisis response and suicide prevention line tax is imposed on the use of all radio access lines:

... By subscribers whose place of primary use is located within the state in the amount set forth in (a)(ii) of this subsection (1) per month for each radio access line. The tax must be uniform for each radio access line under this subsection (1); and

... By consumers whose retail transaction occurs within the state in the amount set forth in this subsection (1)(a)(ii) per retail transaction. The amount of tax must be uniform for each retail transaction under this subsection (1) and is as follows:

(A) Beginning October 1, 2021, through December 31, 2022, the tax rate is 24 cents for each radio access line; and

(B) Beginning January 1, 2023, the tax rate is 40 cents for each radio access line.

.. The tax imposed under this subsection (1) must be remitted to the department by radio communications service companies, including those companies that resell radio access lines, and sellers of prepaid wireless telecommunications service, on a tax return provided by the department. Tax proceeds must be deposited by the treasurer into the statewide 988 behavioral health crisis response and suicide prevention line account created in RCW 82.86.050.

.. For the purposes of this subsection (1), the retail transaction is deemed to occur at the location where the transaction is sourced under RCW 82.32.520(3)(c).

. A statewide 988 behavioral health crisis response and suicide prevention line tax is imposed on all interconnected voice over internet protocol service lines in the state. The amount of tax must be uniform for each line and must be levied on no more than the number of voice over internet protocol service lines on an account that is capable of simultaneous unrestricted outward calling to the public switched telephone network. The tax imposed under this subsection (2) must be remitted to the department by interconnected voice over internet protocol service companies on a tax return provided by the department. The amount of tax for each interconnected voice over internet protocol service line whose place of primary use is located in the state is as follows:

.. Beginning October 1, 2021, through December 31, 2022, the tax rate is 24 cents for an interconnected voice over internet protocol service line; and

.. Beginning January 1, 2023, the tax rate is 40 cents for an interconnected voice over internet protocol service line.

. A statewide 988 behavioral health crisis response and suicide prevention line tax is imposed on all switched access lines in the state. The amount of tax must be uniform for each line and must be levied on no more than the number of switched access lines on an account that is capable of simultaneous unrestricted outward calling to the public switched telephone network. The tax imposed under this subsection (3) must be remitted to the department by local exchange companies on a tax return provided by the department. The amount of tax for each switched access line whose place of primary use is located in the state is as follows:

.. Beginning October 1, 2021, through December 31, 2022, the tax rate is 24 cents for each switched access line; and

.. Beginning January 1, 2023, the tax rate is 40 cents for each switched access line.

. Tax proceeds collected pursuant to this section must be deposited by the treasurer into the statewide 988 behavioral health crisis response and suicide prevention line account created in RCW 82.86.050.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1477-S2.SL.pdf?cite=2021%20c%20302%20§%20202[2021 c 302 § 202]; ]

== 82.86.030 - Collection of tax. (Effective October 1, 2021.)
. Except as provided otherwise in subsection (2) of this section:

.. The statewide 988 behavioral health crisis response and suicide prevention line tax on radio access lines must be collected from the subscriber by the radio communications service company, including those companies that resell radio access lines, providing the radio access line to the subscriber, and the seller of prepaid wireless telecommunications services.

.. The statewide 988 behavioral health crisis response and suicide prevention line tax on interconnected voice over internet protocol service lines must be collected from the subscriber by the interconnected voice over internet protocol service company providing the interconnected voice over internet protocol service line to the subscriber.

.. The statewide 988 behavioral health crisis response and suicide prevention line tax on switched access lines must be collected from the subscriber by the local exchange company.

.. The amount of the tax must be stated separately on the billing statement which is sent to the subscriber.

. [Empty]
.. The statewide 988 behavioral health crisis response and suicide prevention line tax imposed by this chapter must be collected from the consumer by the seller of a prepaid wireless telecommunications service for each retail transaction occurring in this state.

.. The department must transfer all tax proceeds remitted by a seller under this subsection (2) to the statewide 988 behavioral health crisis response and suicide prevention line account created in RCW 82.86.050.

.. The taxes required by this subsection to be collected by the seller must be separately stated in any sales invoice or instrument of sale provided to the consumer.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1477-S2.SL.pdf?cite=2021%20c%20302%20§%20203[2021 c 302 § 203]; ]

== 82.86.040 - Payment and collection. (Effective October 1, 2021.)
. [Empty]
.. The statewide 988 behavioral health crisis response and suicide prevention line tax imposed by this chapter must be paid by the subscriber to the radio communications service company providing the radio access line, the local exchange company, or the interconnected voice over internet protocol service company providing the interconnected voice over internet protocol service line.

.. Each radio communications service company, each local exchange company, and each interconnected voice over internet protocol service company, must collect from the subscriber the full amount of the taxes payable. The statewide 988 behavioral health crisis response and suicide prevention line tax required by this chapter to be collected by a company or seller, are deemed to be held in trust by the company or seller until paid to the department. Any radio communications service company, local exchange company, or interconnected voice over internet protocol service company that appropriates or converts the tax collected to its own use or to any use other than the payment of the tax to the extent that the money collected is not available for payment on the due date as prescribed in this chapter is guilty of a gross misdemeanor.

. If any radio communications service company, local exchange company, or interconnected voice over internet protocol service company fails to collect the statewide 988 behavioral health crisis response and suicide prevention line tax or, after collecting the tax, fails to pay it to the department in the manner prescribed by this chapter, whether such failure is the result of its own act or the result of acts or conditions beyond its control, the company or seller is personally liable to the state for the amount of the tax, unless the company or seller has taken from the buyer in good faith documentation, in a form and manner prescribed by the department, stating that the buyer is not a subscriber or consumer or is otherwise not liable for the statewide 988 behavioral health crisis response and suicide prevention line tax.

. The amount of tax, until paid by the subscriber to the radio communications service company, local exchange company, the interconnected voice over internet protocol service company, or to the department, constitutes a debt from the subscriber to the company, or from the consumer to the seller. Any company or seller that fails or refuses to collect the tax as required with intent to violate the provisions of this chapter or to gain some advantage or benefit, either direct or indirect, and any subscriber or consumer who refuses to pay any tax due under this chapter is guilty of a misdemeanor. The statewide 988 behavioral health crisis response and suicide prevention line tax required by this chapter to be collected by the radio communications service company, local exchange company, or interconnected voice over internet protocol service company must be stated separately on the billing statement that is sent to the subscriber.

. If a subscriber has failed to pay to the radio communications service company, local exchange company, or interconnected voice over internet protocol service company, the statewide 988 behavioral health crisis response and suicide prevention line tax imposed by this chapter and the company or seller has not paid the amount of the tax to the department, the department may, in its discretion, proceed directly against the subscriber or consumer for collection of the tax, in which case a penalty of 10 percent may be added to the amount of the tax for failure of the subscriber or consumer to pay the tax to the company or seller, regardless of when the tax is collected by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1477-S2.SL.pdf?cite=2021%20c%20302%20§%20204[2021 c 302 § 204]; ]

== 82.86.050 - Account creation. (Effective October 1, 2021.)
. The statewide 988 behavioral health crisis response and suicide prevention line account is created in the state treasury. All receipts from the statewide 988 behavioral health crisis response and suicide prevention line tax imposed pursuant to this chapter must be deposited into the account. Moneys may only be spent after appropriation.

. Expenditures from the account may only be used for (a) ensuring the efficient and effective routing of calls made to the 988 crisis hotline to an appropriate crisis hotline center or crisis call center hub; and (b) personnel and the provision of acute behavioral health, crisis outreach, and crisis stabilization services, as defined in RCW 71.24.025, by directly responding to the 988 crisis hotline.

. Moneys in the account may not be used to supplant general fund appropriations for behavioral health services or for medicaid covered services to individuals enrolled in the medicaid program.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1477-S2.SL.pdf?cite=2021%20c%20302%20§%20205[2021 c 302 § 205]; ]

== 82.86.060 - Preemption.
A city or county may not impose a tax, measured on a per line basis, on radio access lines, interconnected voice over internet protocol service lines, or switched access lines, for the purpose of ensuring the efficient and effective routing of calls made to the 988 crisis hotline to an appropriate crisis hotline center or crisis call center hub; or providing personnel or acute behavioral health, crisis outreach, or crisis stabilization services, as defined in RCW 71.24.025, associated with directly responding to the 988 crisis hotline.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1477-S2.SL.pdf?cite=2021%20c%20302%20§%20206[2021 c 302 § 206]; ]

