= 26.04 - Marriage.
:toc:

== 26.04.007 - Definition—Religious organization.
For purposes of this chapter, "religious organization" includes, but is not limited to, churches, mosques, synagogues, temples, nondenominational ministries, interdenominational and ecumenical organizations, mission organizations, faith-based social agencies, and other entities whose principal purpose is the study, practice, or advancement of religion.

[ 2012 c 3 § 7 (Referendum Measure No. 74, approved November 6, 2012); ]

== 26.04.010 - Marriage contract—Void marriages—Construction of gender-specific terms—Recognition of solemnization of marriage not required.
. Marriage is a civil contract between two persons who have each attained the age of eighteen years, and who are otherwise capable.

. Every marriage entered into in which either person has not attained the age of seventeen years is void except where this section has been waived by a superior court judge of the county in which one of the parties resides on a showing of necessity.

. Where necessary to implement the rights and responsibilities of spouses under the law, gender-specific terms such as husband and wife used in any statute, rule, or other law must be construed to be gender neutral and applicable to spouses of the same sex.

. No regularly licensed or ordained minister or any priest, imam, rabbi, or similar official of any religious organization is required to solemnize or recognize any marriage. A regularly licensed or ordained minister or priest, imam, rabbi, or similar official of any religious organization shall be immune from any civil claim or cause of action based on a refusal to solemnize or recognize any marriage under this section. No state agency or local government may base a decision to penalize, withhold benefits from, or refuse to contract with any religious organization on the refusal of a person associated with such religious organization to solemnize or recognize a marriage under this section.

. No religious organization is required to provide accommodations, facilities, advantages, privileges, services, or goods related to the solemnization or celebration of a marriage.

. A religious organization shall be immune from any civil claim or cause of action, including a claim pursuant to chapter 49.60 RCW, based on its refusal to provide accommodations, facilities, advantages, privileges, services, or goods related to the solemnization or celebration of a marriage.

. For purposes of this section:

.. "Recognize" means to provide religious-based services that:

... Are delivered by a religious organization, or by an individual who is managed, supervised, or directed by a religious organization; and

... Are designed for married couples or couples engaged to marry and are directly related to solemnizing, celebrating, strengthening, or promoting a marriage, such as religious counseling programs, courses, retreats, and workshops; and

.. "Religious organization" includes, but is not limited to, churches, mosques, synagogues, temples, nondenominational ministries, interdenominational and ecumenical organizations, mission organizations, faith-based social agencies, and other entities whose principal purpose is the study, practice, or advancement of religion.

[ 2012 c 3 § 1 (Referendum Measure No. 74, approved November 6, 2012); http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1130-S.SL.pdf?cite=1998%20c%201%20§%203[1998 c 1 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c154.pdf?cite=1973%201st%20ex.s.%20c%20154%20§%2026[1973 1st ex.s. c 154 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c17.pdf?cite=1970%20ex.s.%20c%2017%20§%202[1970 ex.s. c 17 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c230.pdf?cite=1963%20c%20230%20§%201[1963 c 230 § 1]; Code 1881 § 2380; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1866%20p%2081%20§%201[1866 p 81 § 1]; 1854 p 404 §§ 1, 5; RRS § 8437; ]

== 26.04.020 - Prohibited marriages.
. Marriages in the following cases are prohibited:

.. When either party thereto has a spouse or registered domestic partner living at the time of such marriage, unless the registered domestic partner is the other party to the marriage; or

.. When the spouses are nearer of kin to each other than second cousins, whether of the whole or half blood computing by the rules of the civil law.

. It is unlawful for any person to marry his or her sibling, child, grandchild, aunt, uncle, niece, or nephew.

. A marriage between two persons that is recognized as valid in another jurisdiction is valid in this state only if the marriage is not prohibited or made unlawful under subsection (1)(a) or (2) of this section.

. A legal union, other than a marriage, between two individuals that was validly formed in another state or jurisdiction and that provides substantially the same rights, benefits, and responsibilities as a marriage, does not prohibit those same two individuals from obtaining a marriage license in Washington.

. No state agency or local government may base a decision to penalize, withhold benefits from, license, or refuse to contract with any religious organization based on the opposition to or refusal to provide accommodations, facilities, advantages, privileges, service, or goods related to the solemnization or celebration of a marriage.

. No religiously affiliated educational institution shall be required to provide accommodations, facilities, advantages, privileges, service, or goods related to the solemnization or celebration of a marriage, including a use of any campus chapel or church. A religiously affiliated educational institution shall be immune from a civil claim or cause of action, including a claim pursuant to chapter 49.60 RCW, based on its refusal to provide accommodations, facilities, advantages, privileges, service, or goods related to the solemnization or celebration of a marriage under this subsection shall be immune for civil claim or cause of action, including a claim pursuant to chapter 49.60 RCW.

[ 2012 c 3 § 2 (Referendum Measure No. 74, approved November 6, 2012); http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1130-S.SL.pdf?cite=1998%20c%201%20§%204[1998 c 1 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c189.pdf?cite=1927%20c%20189%20§%201[1927 c 189 § 1]; Code 1881 § 949; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1866%20p%2081%20§%202[1866 p 81 § 2]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%2096%20§%20115[1854 p 96 § 115]; RRS § 8438; ]

== 26.04.050 - Who may solemnize.
The following named officers and persons, active or retired, are hereby authorized to solemnize marriages, to wit: Justices of the supreme court, judges of the court of appeals, judges of the superior courts, supreme court commissioners, court of appeals commissioners, superior court commissioners, judges and commissioners of courts of limited jurisdiction as defined in RCW 3.02.010, judges of tribal courts from a federally recognized tribe, and any regularly licensed or ordained minister or any priest, imam, rabbi, or similar official of any religious organization. The solemnization of a marriage by a tribal court judge pursuant to authority under this section does not create tribal court jurisdiction and does not affect state court authority as otherwise provided by law to enter a judgment for purposes of any dissolution, legal separation, or other proceedings related to the marriage that is binding on the parties and entitled to full faith and credit.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5622.SL.pdf?cite=2019%20c%2052%20§%202[2019 c 52 § 2]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1091.SL.pdf?cite=2017%20c%20130%20§%201[2017 c 130 § 1]; 2012 c 3 § 4 (Referendum Measure No. 74, approved November 6, 2012); http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5079.SL.pdf?cite=2007%20c%2029%20§%201[2007 c 29 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c291.pdf?cite=1987%20c%20291%20§%201[1987 c 291 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c258.pdf?cite=1984%20c%20258%20§%2095[1984 c 258 § 95]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c186.pdf?cite=1983%20c%20186%20§%201[1983 c 186 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c81.pdf?cite=1971%20c%2081%20§%2069[1971 c 81 § 69]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c35.pdf?cite=1913%20c%2035%20§%201[1913 c 35 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1890c98.pdf?cite=1890%20p%2098%20§%201[1890 p 98 § 1]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1883%20p%2043%20§%201[1883 p 43 § 1]; Code 1881 § 2382; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1866%20p%2082%20§%204[1866 p 82 § 4]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20404%20§%204[1854 p 404 § 4]; RRS § 8441; ]

== 26.04.060 - Marriage before unauthorized cleric—Effect.
A marriage solemnized before any person professing to be a minister or a priest, imam, rabbi, or similar official of any religious organization in this state or professing to be an authorized officer thereof, is not void, nor shall the validity thereof be in any way affected on account of any want of power or authority in such person, if such marriage be consummated with a belief on the part of the persons so married, or either of them, that they have been lawfully joined in marriage.

[ 2012 c 3 § 5 (Referendum Measure No. 74, approved November 6, 2012); 1975-'76 2nd ex.s. c 42 § 25; Code 1881 § 2388; 1866 p 83 §§ 10 and 11; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20405%20§%206[1854 p 405 § 6]; RRS § 8442; ]

== 26.04.070 - Form of solemnization.
In the solemnization of marriage no particular form is required, except that the parties thereto shall assent or declare in the presence of the minister, priest, imam, rabbi, or similar official of any religious organization, or judicial officer solemnizing the same, and in the presence of at least two attending witnesses, that they take each other to be spouses.

[ 2012 c 3 § 6 (Referendum Measure No. 74, approved November 6, 2012); Code 1881 § 2383; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1866%20p%2082%20§%205[1866 p 82 § 5]; RRS § 8443; ]

== 26.04.080 - Marriage certificate—Contents.
The person solemnizing a marriage shall give to each of the parties thereto, if required, a certificate thereof, specifying therein the names and residence of the parties, and of at least two witnesses present, the time and place of such marriage, and the date of the license thereof, and by whom issued.

[ Code 1881 § 2384; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1866%20p%2082%20§%206[1866 p 82 § 6]; RRS § 8444; ]

== 26.04.090 - Certificate for files of county auditor and state registrar of vital statistics—Forms.
A person solemnizing a marriage shall, within thirty days thereafter, make and deliver to the county auditor of the county wherein the license was issued a certificate for the files of the county auditor, and a certificate for the files of the state registrar of vital statistics. The certificate for the files of the county auditor shall be substantially as follows:

STATE OF WASHINGTONCOUNTY OF . . . . This is to certify that the undersigned, a . . . . . ., by authority of a license bearing date the . . . . day of . . . . . . A.D. (year) . . . ., and issued by the County auditor of the county of . . . . . ., did, on the . . . . day of . . . . . . A.D. (year) . . . ., at . . . . . . in this county and state, join inlawful wedlock A.B. of the county of . . . . . ., state of . . . . . . and C.D. of the county of . . . . . ., state of . . . . . ., with their mutual assent, in the presence of F H and E G, witnesses.In Testimony Whereof, witness the signatures of the parties to said ceremony, the witnesses and myself, this . . . . day of . . . . . ., A.D. (year) . . . .

STATE OF WASHINGTON



COUNTY OF . . . .











 

This is to certify that the undersigned, a . . . . . ., by authority of a license bearing date the . . . . day of . . . . . . A.D. (year) . . . ., and issued by the County auditor of the county of . . . . . ., did, on the . . . . day of . . . . . . A.D. (year) . . . ., at . . . . . . in this county and state, join in

lawful wedlock A.B. of the county of . . . . . ., state of . . . . . . and C.D. of the county of . . . . . ., state of . . . . . ., with their mutual assent, in the presence of F H and E G, witnesses.

In Testimony Whereof, witness the signatures of the parties to said ceremony, the witnesses and myself, this . . . . day of . . . . . ., A.D. (year) . . . .

The certificate forms for the files of the county auditor and for the files of the state registrar of vital statistics shall be provided by the state registrar of vital statistics.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%2031[2019 c 148 § 31]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2359-S.SL.pdf?cite=2016%20c%20202%20§%2023[2016 c 202 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c26.pdf?cite=1967%20c%2026%20§%204[1967 c 26 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c59.pdf?cite=1947%20c%2059%20§%201[1947 c 59 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1927c172.pdf?cite=1927%20c%20172%20§%201[1927 c 172 § 1]; Code 1881 § 2385; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1866%20p%2082%20§%207[1866 p 82 § 7]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20405%20§%207[1854 p 405 § 7]; RRS § 8445; ]

== 26.04.100 - Filing and recording—County auditor.
The county auditor shall file said certificates and record them or bind them into numbered volumes, and note on the original index to the license issued the volume and page wherein such certificate is recorded or bound. He or she shall enter the date of filing and his or her name on the certificates for the files of the state registrar of vital statistics, and transmit, by the tenth day of each month, all such certificates filed with him or her during the preceding month.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20684[2011 c 336 § 684]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c26.pdf?cite=1967%20c%2026%20§%205[1967 c 26 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c59.pdf?cite=1947%20c%2059%20§%202[1947 c 59 § 2]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1886%20p%2066%20§%201[1886 p 66 § 1]; Code 1881 § 2386; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1867%20p%20105%20§%202[1867 p 105 § 2]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1866%20p%2082%20§%208[1866 p 82 § 8]; Rem. Supp. 1947 § 8446; ]

== 26.04.105 - Preservation of copies of applications and licenses—County auditor.
The county auditor may preserve copies of marriage license applications submitted and marriage licenses issued under this chapter in the same manner as authorized for the recording of instruments under RCW 65.04.040.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c44.pdf?cite=1985%20c%2044%20§%201[1985 c 44 § 1]; ]

== 26.04.110 - Penalty for failure to deliver certificates.
Any person solemnizing a marriage, who shall wilfully refuse or neglect to make and deliver to the county auditor for record, the certificates mentioned in RCW 26.04.090, within the time in such section specified, shall be deemed guilty of a misdemeanor, and upon conviction shall pay for such refusal, or neglect, a fine of not less than twenty-five nor more than three hundred dollars.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c26.pdf?cite=1967%20c%2026%20§%206[1967 c 26 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c59.pdf?cite=1947%20c%2059%20§%203[1947 c 59 § 3]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1886%20p%2066%20§%202[1886 p 66 § 2]; Code 1881 § 2387; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1866%20p%2083%20§%209[1866 p 83 § 9]; Rem. Supp. 1947 § 8447; ]

== 26.04.120 - Marriage according to religious ritual.
All marriages to which there are no legal impediments, solemnized before or in any religious organization or congregation, according to the established ritual or form commonly practiced therein, are valid, and a certificate containing the particulars specified in RCW 26.04.080 and 26.04.090, shall be made and filed for record by the person or persons presiding or officiating in or recording the proceedings of such religious organization or congregation, in the manner and with like effect as in ordinary cases.

[ Code 1881 § 2389; RRS § 8448; ]

== 26.04.130 - Voidable marriages.
When either party to a marriage shall be incapable of consenting thereto, for want of legal age or a sufficient understanding, or when the consent of either party shall be obtained by force or fraud, such marriage is voidable, but only at the suit of the party laboring under the disability, or upon whom the force or fraud is imposed.

[ Code 1881 § 2381; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1866%20p%2081%20§%203[1866 p 81 § 3]; RRS § 8449; ]

== 26.04.140 - Marriage license.
Before any persons can be joined in marriage, they shall procure a license from a county auditor, as provided in RCW 26.04.150 through 26.04.190.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c82.pdf?cite=1985%20c%2082%20§%201[1985 c 82 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c204.pdf?cite=1939%20c%20204%20§%202[1939 c 204 § 2]; RRS § 8450-1; Code 1881 § 2390; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1866%20p%2083%20§%2012[1866 p 83 § 12]; ]

== 26.04.150 - Application for license—May be secured by mail—Execution and acknowledgment.
Any person may secure by mail from the county auditor of the county in the state of Washington where he or she intends to be married, an application, and execute and acknowledge said application before a notary public.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20685[2011 c 336 § 685]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c230.pdf?cite=1963%20c%20230%20§%202[1963 c 230 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c204.pdf?cite=1939%20c%20204%20§%203[1939 c 204 § 3]; RRS § 8450-2; ]

== 26.04.160 - Application for license—Contents—Oath.
. Application for a marriage license must be made and filed with the appropriate county auditor upon blanks to be provided by the county auditor for that purpose, which application shall be under the oath of each of the applicants, and each application shall state the name, address at the time of execution of application, age, social security number, birthplace, whether single, widowed or divorced, and whether under control of a guardian, residence during the past six months: PROVIDED, That each county may require such other and further information on said application as it shall deem necessary.

. The county legislative authority may impose an additional fee up to fifteen dollars on a marriage license for the purpose of funding family services such as family support centers.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20909[1997 c 58 § 909]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1395.SL.pdf?cite=1993%20c%20451%20§%201[1993 c 451 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c82.pdf?cite=1985%20c%2082%20§%202[1985 c 82 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c26.pdf?cite=1967%20c%2026%20§%207[1967 c 26 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c204.pdf?cite=1939%20c%20204%20§%204[1939 c 204 § 4]; RRS § 8450-3; ]

== 26.04.165 - Additional marriage certificate form. 
In addition to the application provided for in RCW 26.04.160, the county auditor for the county wherein the license is issued shall submit to each applicant at the time for application for a license the Washington state department of health marriage certificate form provided by the state registrar of vital statistics to be completed by the applicants and returned to the county auditor for the files of the state registrar of vital statistics. After the execution of the application for, and the issuance of a license, no county shall require the persons authorized to solemnize marriages to obtain any further information from the persons to be married except the names and county of residence of the persons to be married.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%2032[2019 c 148 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989ex1c9.pdf?cite=1989%201st%20ex.s.%20c%209%20§%20203[1989 1st ex.s. c 9 § 203]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%2034[1979 c 141 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c279.pdf?cite=1969%20ex.s.%20c%20279%20§%201[1969 ex.s. c 279 § 1]; ]

== 26.04.170 - Inspection of applications.
Any such application shall be open to public inspection as a part of the records of the office of such county auditor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c82.pdf?cite=1985%20c%2082%20§%203[1985 c 82 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c204.pdf?cite=1939%20c%20204%20§%205[1939 c 204 § 5]; RRS § 8450-4; ]

== 26.04.175 - When disclosure of marriage applications and records prohibited.
If a program participant under chapter 40.24 RCW notifies the appropriate county auditor as required under rules adopted by the secretary of state, the county auditor shall not make available for inspection or copying the name and address of a program participant contained in marriage applications and records filed under chapter 26.04 RCW, except under the following circumstances:

. If requested by a law enforcement agency, to the law enforcement agency; and

. If directed by a court order, to a person identified in the order.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5906.SL.pdf?cite=1991%20c%2023%20§%2012[1991 c 23 § 12]; ]

== 26.04.180 - License—Time limitations as to issuance and use—Notification.
The county auditor may issue the marriage license at the time of application, but shall issue such license no later than the third full day following the date of the application. A marriage license issued pursuant to the provisions of this chapter may not be used until three days after the date of application and shall become void if the marriage is not solemnized within sixty days of the date of the issuance of the license, and the county auditor shall notify the applicant in writing of this requirement at the time of issuance of the license.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c82.pdf?cite=1985%20c%2082%20§%204[1985 c 82 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c128.pdf?cite=1979%20ex.s.%20c%20128%20§%201[1979 ex.s. c 128 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c230.pdf?cite=1963%20c%20230%20§%203[1963 c 230 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c107.pdf?cite=1953%20c%20107%20§%201[1953 c 107 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c250.pdf?cite=1943%20c%20250%20§%201[1943 c 250 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c204.pdf?cite=1939%20c%20204%20§%206[1939 c 204 § 6]; Rem. Supp. 1943 § 8450-5; ]

== 26.04.190 - Refusal of license—Appeal.
Any county auditor is hereby authorized to refuse to issue a license to marry if, in his or her discretion, the applications executed by the parties or information coming to his or her knowledge as a result of the execution of said applications, justifies said refusal: PROVIDED, HOWEVER, The denied parties may appeal to the superior court of said county for an order to show cause, directed to said county auditor to appear before said court to show why said court should not grant an order to issue a license to said denied parties and, after due hearing, or if the auditor fails to appear, said court may in its discretion, issue an order to said auditor directing him or her to issue said license; any hearings held by a superior court under RCW 26.04.140 through 26.04.200 may, in the discretion of said court, be held in chambers.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20686[2011 c 336 § 686]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c204.pdf?cite=1939%20c%20204%20§%207[1939 c 204 § 7]; RRS § 8450-6; ]

== 26.04.200 - Penalty for violations—1939 c 204.
Any person intentionally violating any provision of RCW 26.04.140 through 26.04.190 shall be guilty of a misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1939c204.pdf?cite=1939%20c%20204%20§%208[1939 c 204 § 8]; RRS § 8450-7; ]

== 26.04.210 - Affidavits required for issuance of license—Penalties.
. The county auditor, before a marriage license is issued, upon the payment of a license fee as fixed in RCW 36.18.010 shall require each applicant therefor to make and file in the auditor's office upon blanks to be provided by the county for that purpose, an affidavit showing that if an applicant is afflicted with any contagious sexually transmitted disease, the condition is known to both applicants, and that the applicants are the age of eighteen years or over. If the consent in writing is obtained of the father, mother, or legal guardian of the person for whom the license is required, the license may be granted in cases where the female has attained the age of seventeen years or the male has attained the age of seventeen years. Such affidavit may be subscribed and sworn to before any person authorized to administer oaths.

. Anyone knowingly swearing falsely to any of the statements contained in the affidavits mentioned in this section is guilty of perjury under chapter 9A.72 RCW.

. The affidavit form shall be designed to require a statement that no contagious sexually transmitted disease is present or that the condition is known to both applicants, without requiring the applicants to state whether or not either or both of them are afflicted by such disease.

. Any person knowingly violating this section is guilty of a class C felony and shall be punished by a fine of not more than one thousand dollars, or by imprisonment in a state correctional facility for a period of not more than three years, or by both such fine and imprisonment.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20166[2003 c 53 § 166]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1889.SL.pdf?cite=1995%20c%20301%20§%2078[1995 c 301 § 78]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c82.pdf?cite=1985%20c%2082%20§%205[1985 c 82 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c128.pdf?cite=1979%20ex.s.%20c%20128%20§%202[1979 ex.s. c 128 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c154.pdf?cite=1973%201st%20ex.s.%20c%20154%20§%2029[1973 1st ex.s. c 154 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c17.pdf?cite=1970%20ex.s.%20c%2017%20§%205[1970 ex.s. c 17 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c230.pdf?cite=1963%20c%20230%20§%204[1963 c 230 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c149.pdf?cite=1959%20c%20149%20§%203[1959 c 149 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909ex1c16.pdf?cite=1909%20ex.s.%20c%2016%20§%203[1909 ex.s. c 16 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c174.pdf?cite=1909%20c%20174%20§%203[1909 c 174 § 3]; Code 1881 §§ 2391, 2392; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1867%20p%20104%20§%201[1867 p 104 § 1]; 1866 p 83 §§ 13, 14; RRS § 8451; ]

== 26.04.220 - Retention of license by person solemnizing—Auditor's record.
The person solemnizing the marriage is authorized to retain in his or her possession the license, but the county auditor who issues the same, before delivering it, shall enter in his or her marriage record a memorandum of the names of the parties, the consent of the parents or guardian, if any, and the name of the affiant and the substance of the affidavit upon which said license issued, and the date of such license.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20687[2011 c 336 § 687]; Code 1881 § 2393; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1866%20p%2084%20§%2015[1866 p 84 § 15]; RRS § 8453; ]

== 26.04.240 - Penalty for unlawful solemnization—Code 1881.
Any person who shall undertake to join others in marriage knowing that he or she is not lawfully authorized so to do, or any person authorized to solemnize marriage, who shall join persons in marriage contrary to the provisions of *this chapter, shall, upon conviction thereof, be punished by a fine of not more than five hundred, nor less than one hundred dollars.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20688[2011 c 336 § 688]; Code 1881 § 2395; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1866%20p%2084%20§%2017[1866 p 84 § 17]; RRS § 8454. FORMER PART OF SECTION:  1909 c 249 § 419; RRS § 2671 now codified as RCW  26.04.250; ]

== 26.04.250 - Penalty for unlawful solemnization—1909 c 249.
Every person who shall solemnize a marriage when either party thereto is known to him or her to be under the age of legal consent or a marriage to which, within his or her knowledge, any legal impediment exists, shall be guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20689[2011 c 336 § 689]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c128.pdf?cite=1979%20ex.s.%20c%20128%20§%203[1979 ex.s. c 128 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20419[1909 c 249 § 419]; RRS § 2671; ]

== 26.04.260 - Recognition of a legal union.
If two persons in Washington have a legal union, other than a marriage, that:

. Was validly formed in another state or jurisdiction;

. Provides substantially the same rights, benefits, and responsibilities as a marriage; and

. Does not meet the definition of domestic partnership in RCW 26.60.030,

then they shall be treated as having the same rights and responsibilities as married spouses in this state, unless:

.. Such relationship is prohibited by RCW 26.04.020 (1)(a) or (2); or

.. They become permanent residents of Washington state and do not enter into a marriage within one year after becoming permanent residents.

[ 2012 c 3 § 11 (Referendum Measure No. 74, approved November 6, 2012); ]

== 26.04.900 - Construction—Religious organization.
"Religious organization" as defined in this chapter must be interpreted liberally to include faith-based social service organizations involved in social services directed at the larger community.

[ 2012 c 3 § 3 (Referendum Measure No. 74, approved November 6, 2012); ]

