= 26.18 - Child support enforcement.
:toc:

== 26.18.010 - Legislative findings.
The legislature finds that there is an urgent need for vigorous enforcement of child support and maintenance obligations, and that stronger and more efficient statutory remedies need to be established to supplement and complement the remedies provided in chapters 26.09, 26.21A, 26.26A, 26.26B, 74.20, and 74.20A RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5333-S.SL.pdf?cite=2019%20c%2046%20§%205024[2019 c 46 § 5024]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%201026[2008 c 6 § 1026]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1760-S.SL.pdf?cite=1993%20c%20426%20§%201[1993 c 426 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c260.pdf?cite=1984%20c%20260%20§%201[1984 c 260 § 1]; ]

== 26.18.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Department" means the department of social and health services.

. "Dependent child" means any child for whom a support order has been established or for whom a duty of support is owed.

. "Disposable earnings" means that part of the earnings of an individual remaining after the deduction from those earnings of any amount required by law to be withheld.

. "Duty of maintenance" means the duty to provide for the needs of a spouse or former spouse or domestic partner or former domestic partner imposed under chapter 26.09 RCW.

. "Duty of support" means the duty to provide for the needs of a dependent child, which may include necessary food, clothing, shelter, education, and health care. The duty includes any obligation to make monetary payments, to pay expenses, including maintenance in cases in which there is a dependent child, or to reimburse another person or an agency for the cost of necessary support furnished a dependent child. The duty may be imposed by court order, by operation of law, or otherwise.

. "Earnings" means compensation paid or payable for personal services or remuneration for employment, whether denominated as wages, salary, commission, bonus, or otherwise, and, notwithstanding any other provision of law making the payments exempt from garnishment, attachment, or other process to satisfy support or maintenance obligations, specifically includes periodic payments pursuant to pension or retirement programs, or insurance policies of any type, but does not include payments made under Title 50 RCW, except as provided in RCW 50.40.020 and 50.40.050, or Title 74 RCW.

. "Employer" includes the United States government, a state or local unit of government, and any person or entity who pays or owes earnings or remuneration for employment to the obligor.

. "Health care coverage" means fee for service, health maintenance organization, preferred provider organization, and other types of private health insurance and public health care coverage under which medical services could be provided to a dependent child or children. The term "health care coverage" includes, but is not limited to, health insurance coverage.

. "Health insurance coverage" is another term for, and included in the definition of, "health care coverage." Health insurance coverage includes any coverage under which medical services are provided by an employer or a union whether that coverage is provided through a self-insurance program, under the employee retirement income security act of 1974, a commercial insurer pursuant to chapters 48.20 and 48.21 RCW, a health care service contractor pursuant to chapter 48.44 RCW, or a health maintenance organization pursuant to chapter 48.46 RCW, and the state through chapter 41.05 RCW.

. "Income withholding order" means an order regarding withholding of income of amounts payable as a support obligation that complies with the requirements in 42 U.S.C. Sec. 666.

. "Insurer" means a commercial insurance company providing disability insurance under chapter 48.20 or 48.21 RCW, a health care service contractor providing health care coverage under chapter 48.44 RCW, a health maintenance organization providing comprehensive health care services under chapter 48.46 RCW, and shall also include any employer or union which is providing health insurance coverage on a self-insured basis.

. "Obligee" means the custodian of a dependent child, the spouse or former spouse or domestic partner or former domestic partner, or person or agency, to whom a duty of support or duty of maintenance is owed, or the person or agency to whom the right to receive or collect support or maintenance has been assigned.

. "Obligor" means the person owing a duty of support or duty of maintenance.

. "Public health care coverage," sometimes called "state purchased health care," means state-financed or federally financed medical coverage, whether or not there is an assignment of rights. For children residing in Washington state, this includes coverage through the department of social and health services or the health care authority, except for coverage under chapter 41.05 RCW; for children residing outside of Washington, this includes coverage through another state's agencies that administer state purchased health care programs.

. "Remuneration for employment" means moneys due from or payable by the United States to an individual within the scope of 42 U.S.C. Sec. 659 and 42 U.S.C. Sec. 662(f).

. "Support or maintenance order" means any judgment, decree, or order of support or maintenance issued by the superior court or authorized agency of the state of Washington; or a judgment, decree, or other order of support or maintenance issued by a court or agency of competent jurisdiction in another state or country, which has been registered or otherwise made enforceable in this state.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1171-S.SL.pdf?cite=2021%20c%2035%20§%205[2021 c 35 § 5]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6334-S.SL.pdf?cite=2018%20c%20150%20§%20102[2018 c 150 § 102]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%201027[2008 c 6 § 1027]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1760-S.SL.pdf?cite=1993%20c%20426%20§%202[1993 c 426 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c416.pdf?cite=1989%20c%20416%20§%202[1989 c 416 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c435.pdf?cite=1987%20c%20435%20§%2017[1987 c 435 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c260.pdf?cite=1984%20c%20260%20§%202[1984 c 260 § 2]; ]

== 26.18.030 - Application—Liberal construction.
. The remedies provided in this chapter are in addition to, and not in substitution for, any other remedies provided by law.

. This chapter applies to any dependent child, whether born before or after June 7, 1984, and regardless of the past or current marital status or domestic partnership status of the parents, and to a spouse or former spouse or domestic partner or former domestic partner.

. This chapter shall be liberally construed to assure that all dependent children are adequately supported.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%201028[2008 c 6 § 1028]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1760-S.SL.pdf?cite=1993%20c%20426%20§%203[1993 c 426 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c260.pdf?cite=1984%20c%20260%20§%203[1984 c 260 § 3]; ]

== 26.18.035 - Other civil and criminal remedies applicable.
Nothing in this chapter limits the authority of the attorney general or prosecuting attorney to use any and all civil and criminal remedies to enforce child support obligations regardless of whether or not the custodial parent receives public assistance payments.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c260.pdf?cite=1984%20c%20260%20§%2024[1984 c 260 § 24]; ]

== 26.18.040 - Support or maintenance proceedings.
. A proceeding to enforce a duty of support or maintenance is commenced:

.. By filing a petition for an original action; or

.. By motion in an existing action or under an existing cause number.

. Venue for the action is in the superior court of the county where the dependent child resides or is present, where the obligor or obligee resides, or where the prior support or maintenance order was entered. The petition or motion may be filed by the obligee, the state, or any agency providing care or support to the dependent child. A filing fee shall not be assessed in cases brought on behalf of the state of Washington.

. The court retains continuing jurisdiction under this chapter until all duties of either support or maintenance, or both, of the obligor, including arrearages, have been satisfied.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%201029[2008 c 6 § 1029]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1760-S.SL.pdf?cite=1993%20c%20426%20§%204[1993 c 426 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c260.pdf?cite=1984%20c%20260%20§%204[1984 c 260 § 4]; ]

== 26.18.050 - Failure to comply with support or maintenance order—Contempt action—Order to show cause—Bench warrant—Continuing jurisdiction.
. If an obligor fails to comply with a support or maintenance order, a petition or motion may be filed without notice under RCW 26.18.040 to initiate a contempt action as provided in chapter 7.21 RCW. If the court finds there is reasonable cause to believe the obligor has failed to comply with a support or maintenance order, the court may issue an order to show cause requiring the obligor to appear at a certain time and place for a hearing, at which time the obligor may appear to show cause why the relief requested should not be granted. A copy of the petition or motion shall be served on the obligor along with the order to show cause.

. Service of the order to show cause shall be by personal service, or in the manner provided in the civil rules of superior court or applicable statute.

. If the order to show cause served upon the obligor included a warning that an arrest warrant could be issued for failure to appear, the court may issue a bench warrant for the arrest of the obligor if the obligor fails to appear on the return date provided in the order.

. If the obligor contends at the hearing that he or she lacked the means to comply with the support or maintenance order, the obligor shall establish that he or she exercised due diligence in seeking employment, in conserving assets, or otherwise in rendering himself or herself able to comply with the court's order.

. As provided in RCW 26.18.040, the court retains continuing jurisdiction under this chapter and may use a contempt action to enforce a support or maintenance order until the obligor satisfies all duties of support, including arrearages, that accrued pursuant to the support or maintenance order.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%201030[2008 c 6 § 1030]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1760-S.SL.pdf?cite=1993%20c%20426%20§%205[1993 c 426 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c373.pdf?cite=1989%20c%20373%20§%2022[1989 c 373 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c260.pdf?cite=1984%20c%20260%20§%205[1984 c 260 § 5]; ]

== 26.18.055 - Child support liens.
Child support debts, not paid when due, become liens by operation of law against all property of the debtor with priority of a secured creditor. This lien shall be separate and apart from, and in addition to, any other lien created by, or provided for, in this title. The lien attaches to all real and personal property of the debtor on the date of filing with the county auditor of the county in which the property is located. Liens filed by other states or jurisdictions that comply with the procedural rules for filing liens under chapter 65.04 RCW shall be accorded full faith and credit and are enforceable without judicial notice or hearing.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2579.SL.pdf?cite=2000%20c%2086%20§%201[2000 c 86 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20942[1997 c 58 § 942]; ]

== 26.18.070 - Mandatory wage assignment—Petition or motion.
. A petition or motion seeking a mandatory wage assignment in an action under RCW 26.18.040 may be filed by an obligee if the obligor is:

.. Subject to a support order allowing immediate income withholding; or

.. More than fifteen days past due in child support or maintenance payments in an amount equal to or greater than the obligation payable for one month.

. The petition or motion shall include a sworn statement by the obligee, stating the facts authorizing the issuance of the wage assignment order, including:

.. That the obligor, stating his or her name and residence, is:

... Subject to a support order allowing immediate income withholding; or

... More than fifteen days past due in child support or maintenance payments in an amount equal to or greater than the obligation payable for one month;

.. A description of the terms of the order requiring payment of support or maintenance, and the amount past due, if any;

.. The name and address of the obligor's employer;

.. That notice by personal service or any form of mail requiring a return receipt, has been provided to the obligor at least fifteen days prior to the obligee seeking a mandatory wage assignment, unless the order for support or maintenance states that the obligee may seek a mandatory wage assignment without notice to the obligor; and

.. In cases not filed by the state, whether the obligee has received public assistance from any source and, if the obligee has received public assistance, that the department of social and health services has been notified in writing of the pending action.

. If the court in which a mandatory wage assignment is sought does not already have a copy of the support or maintenance order in the court file, then the obligee shall attach a copy of the support or maintenance order to the petition or motion seeking the wage assignment.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%201031[2008 c 6 § 1031]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2488-S.SL.pdf?cite=1994%20c%20230%20§%203[1994 c 230 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1760-S.SL.pdf?cite=1993%20c%20426%20§%206[1993 c 426 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c435.pdf?cite=1987%20c%20435%20§%2018[1987 c 435 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c260.pdf?cite=1984%20c%20260%20§%207[1984 c 260 § 7]; ]

== 26.18.080 - Wage assignment order or income withholding order—Issuance—Information transmitted to state support registry.
. Upon receipt of a petition or motion seeking a mandatory wage assignment that complies with RCW 26.18.070, the court shall issue: (a) A wage assignment order for unpaid maintenance; (b) an income withholding order for unpaid child support; or (c) an income withholding order for unpaid maintenance and unpaid child support, including the information required in RCW 26.18.090, directed to the employer, and commanding the employer to answer the order on the forms served with the order that comply with RCW 26.18.120 within twenty days after service of the order upon the employer.

. The clerk of the court shall forward a copy of the mandatory wage assignment or income withholding order, a true and correct copy of the support orders in the court file, and a statement containing the obligee's address and social security number shall be forwarded to the Washington state support registry within five days of the entry of the order.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1171-S.SL.pdf?cite=2021%20c%2035%20§%206[2021 c 35 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c435.pdf?cite=1987%20c%20435%20§%2019[1987 c 435 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c260.pdf?cite=1984%20c%20260%20§%208[1984 c 260 § 8]; ]

== 26.18.090 - Wage assignment order for unpaid maintenance—Contents—Amounts—Apportionment of disbursements.
. The wage assignment order in RCW 26.18.080 for unpaid maintenance only shall include:

.. The maximum amount of current maintenance, if any, to be withheld from the obligor's earnings each month, or from each earnings disbursement; and

.. The total amount of the arrearage or reimbursement judgment previously entered by the court, if any, together with interest, if any.

. The total amount to be withheld from the obligor's earnings each month, or from each earnings disbursement, shall not exceed fifty percent of the disposable earnings of the obligor. If the amounts to be paid toward the arrearage are specified in the maintenance order, then the maximum amount to be withheld is the sum of: Either the current support or maintenance ordered, or both; and the amount ordered to be paid toward the arrearage, or fifty percent of the disposable earnings of the obligor, whichever is less.

. The provisions of RCW 6.27.150 do not apply to wage assignments for maintenance authorized under this chapter, but fifty percent of the disposable earnings of the obligor are exempt, and may be disbursed to the obligor.

. If an obligor is subject to two or more attachments for maintenance on account of different obligees, the employer shall, if the nonexempt portion of the obligor's earnings is not sufficient to respond fully to all the attachments, apportion the obligor's nonexempt disposable earnings between or among the various obligees equally. An obligee may seek a court order reapportioning the obligor's nonexempt disposable earnings upon notice to all interested obligees. Notice shall be by personal service, or in the manner provided by the civil rules of superior court or applicable statute.

. An income withholding order for unpaid child support or unpaid child support and unpaid maintenance shall meet federal requirements in 42 U.S.C. Sec. 666.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1171-S.SL.pdf?cite=2021%20c%2035%20§%207[2021 c 35 § 7]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%201032[2008 c 6 § 1032]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1760-S.SL.pdf?cite=1993%20c%20426%20§%207[1993 c 426 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c260.pdf?cite=1984%20c%20260%20§%209[1984 c 260 § 9]; ]

== 26.18.110 - Wage assignment order or income withholding order—Employer's answer, duties, and liability—Priorities.
. An employer upon whom service of a wage assignment order or income withholding order has been made shall answer the order by sworn affidavit within twenty days after the date of service. The answer shall state whether the obligor is employed by or receives earnings or other remuneration from the employer, whether the employer will honor the wage assignment order or income withholding order, and whether there are either multiple child support or maintenance attachments, or both, against the obligor.

. If the employer possesses any earnings or remuneration due and owing to the obligor, the earnings subject to the wage assignment order or income withholding order shall be withheld immediately upon receipt of the wage assignment order or income withholding order. The withheld earnings shall be delivered to the Washington state support registry or, if the wage assignment order is to satisfy a duty of maintenance, to the addressee specified in the assignment within five working days of each regular pay interval.

. The employer shall continue to withhold the ordered amounts from nonexempt earnings or remuneration of the obligor until notified by:

.. The court that the wage assignment has been modified or terminated; or

.. In the case of an income withholding order, the Washington state support registry that the accrued child support or maintenance debt has been paid. The employer shall promptly notify the addressee specified in the assignment when the employee is no longer employed. If the employer no longer employs the employee, the wage assignment order shall remain in effect for one year after the employee has left the employment or the employer has been in possession of any earnings or remuneration owed to the employee, whichever is later. The employer shall continue to hold the wage assignment order during that period. If the employee returns to the employer's employment during the one-year period the employer shall immediately begin to withhold the employee's earnings or remuneration according to the terms of the wage assignment order. If the employee has not returned within one year, the wage assignment shall cease to have effect at the expiration of the one-year period, unless the employer continues to owe remuneration for employment to the obligor.

. The employer may deduct a processing fee from the remainder of the employee's earnings after withholding under the wage assignment order or income withholding order, even if the remainder is exempt under RCW 26.18.090. The processing fee may not exceed (a) ten dollars for the first disbursement made by the employer to the Washington state support registry; and (b) one dollar for each subsequent disbursement to the clerk.

. An income withholding order for support for a dependent child entered under this chapter shall have priority over any other wage assignment or garnishment, except for another wage assignment or garnishment for child support, or order to withhold and deliver under chapter 74.20A RCW. An order for wage assignment for spousal maintenance entered under this chapter shall have priority over any other wage assignment or garnishment, except for a wage assignment, garnishment, or order to withhold and deliver under chapter 74.20A RCW for support of a dependent child, and except for another wage assignment or garnishment for maintenance.

. An employer who fails to withhold earnings as required by a wage assignment order or income withholding order issued under this chapter may be held liable to the obligee for one hundred percent of the support or maintenance debt, or the amount of support or maintenance moneys that should have been withheld from the employee's earnings whichever is the lesser amount, if the employer:

.. Fails or refuses, after being served with a wage assignment order or income withholding order, to deduct and promptly remit from the unpaid earnings the amounts of money required in the order;

.. Fails or refuses to submit an answer to the notice of wage assignment or income withholding after being served; or

.. Is unwilling to comply with the other requirements of this section.

Liability may be established in superior court. Awards in superior court shall include costs, interest under RCW 19.52.020 and 4.56.110, and reasonable attorneys' fees.

. No employer who complies with a wage assignment order or income withholding order issued under this chapter may be liable to the employee for wrongful withholding.

. No employer may discharge, discipline, or refuse to hire an employee because of the entry or service of a wage assignment or income withholding order issued and executed under this chapter. If an employer discharges, disciplines, or refuses to hire an employee in violation of this section, the employee or person shall have a cause of action against the employer. The employer shall be liable for double the amount of damages suffered as a result of the violation and for costs and reasonable attorneys' fees, and shall be subject to a civil penalty of not more than two thousand five hundred dollars for each violation. The employer may also be ordered to hire, rehire, or reinstate the aggrieved individual.

. For wage assignments or income withholding payable to the Washington state support registry, an employer may combine amounts withheld from various employees into a single payment to the Washington state support registry, if the payment includes a listing of the amounts attributable to each employee and other information as required by the registry.

. An employer shall deliver a copy of the wage assignment order or income withholding order to the obligor as soon as is reasonably possible.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1171-S.SL.pdf?cite=2021%20c%2035%20§%209[2021 c 35 § 9]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%201034[2008 c 6 § 1034]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2732.SL.pdf?cite=1998%20c%2077%20§%202[1998 c 77 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2488-S.SL.pdf?cite=1994%20c%20230%20§%205[1994 c 230 § 5]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1760-S.SL.pdf?cite=1993%20c%20426%20§%209[1993 c 426 § 9]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5120-S2.SL.pdf?cite=1991%20c%20367%20§%2021[1991 c 367 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c416.pdf?cite=1989%20c%20416%20§%2011[1989 c 416 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c435.pdf?cite=1987%20c%20435%20§%2021[1987 c 435 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c260.pdf?cite=1984%20c%20260%20§%2011[1984 c 260 § 11]; ]

== 26.18.120 - Wage assignment order—Employer's answer—Form.
The answer of the employer shall be made on forms, served on the employer with the wage assignment order, substantially as follows:

IN THE SUPERIOR COURT OF THESTATE OF WASHINGTON IN AND FOR THECOUNTY OF  . . . . . . . . . . . . . . . . . . . . .No.  . . . . . . . . . . . .Obligee  vs.ANSWER . . . . . . . . . . . .TO WAGEObligorASSIGNMENT ORDER . . . . . . . . . . . . Employer 1. At the time of the service of the wage assignment order on the employer, was the above-named obligor employed by or receiving earnings or other remuneration for employment from the employer?Yes  . . . . . .  No  . . . . . . (check one).2. Are there any other attachments for child support or maintenance currently in effect against the obligor?Yes  . . . . . . No  . . . . . . (check one).3. If the answer to question one is yes and the employer cannot comply with the wage assignment order, provide an explanation: I declare under penalty of perjury under the laws of the state of Washington that the foregoing is true and correct.. . . .. . . .Signature of employerDate and place . . . .. . . .. . . .Signature of personAddress for future noticeanswering for employerto employer. . . . Connection with employer

IN THE SUPERIOR COURT OF THE

STATE OF WASHINGTON IN AND FOR THE

COUNTY OF  . . . . . . . . .

 . . . . . . . . . . . .

No.  . . . . . . . . . . . .

Obligee

 

 

vs.

ANSWER

 . . . . . . . . . . . .

TO WAGE

Obligor

ASSIGNMENT ORDER

 . . . . . . . . . . . .

 

Employer

 

1. At the time of the service of the wage assignment order on the employer, was the above-named obligor employed by or receiving earnings or other remuneration for employment from the employer?

Yes  . . . . . .  No  . . . . . . (check one).

2. Are there any other attachments for child support or maintenance currently in effect against the obligor?

Yes  . . . . . . No  . . . . . . (check one).

3. If the answer to question one is yes and the employer cannot comply with the wage assignment order, provide an explanation:

 

I declare under penalty of perjury under the laws of the state of Washington that the foregoing is true and correct.

. . . .

. . . .

Signature of employer

Date and place

 

. . . .

. . . .

. . . .

Signature of person

Address for future notice

answering for employer

to employer

. . . .

 

Connection with employer

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%201035[2008 c 6 § 1035]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1760-S.SL.pdf?cite=1993%20c%20426%20§%2010[1993 c 426 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c260.pdf?cite=1984%20c%20260%20§%2012[1984 c 260 § 12]; ]

== 26.18.130 - Wage assignment order or income withholding order—Service.
. Service of the wage assignment order or income withholding order on the employer is invalid unless it is served with five answer forms in substantial conformance with RCW 26.18.120, together with stamped envelopes addressed to, respectively, the clerk of the court where the order was issued, the Washington state support registry, the obligee's attorney or the obligee, and the obligor. The obligee shall also include an extra copy of the wage assignment order or income withholding order for the employer to deliver to the obligor. Service on the employer shall be in person or by any form of mail requiring a return receipt.

. On or before the date of service of the wage assignment order or income withholding order on the employer, the obligee shall mail or cause to be mailed by certified mail a copy of the wage assignment order or income withholding order to the obligor at the obligor's last known post office address; or, in the alternative, a copy of the wage assignment order or income withholding order shall be served on the obligor in the same manner as a summons in a civil action on, before, or within two days after the date of service of the order on the employer. This requirement is not jurisdictional, but if the copy is not mailed or served as this subsection provides, or if any irregularity appears with respect to the mailing or service, the superior court, in its discretion, may quash the wage assignment order or income withholding order, upon motion of the obligor promptly made and supported by an affidavit showing that the obligor has suffered substantial injury due to the failure to mail or serve the copy.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1171-S.SL.pdf?cite=2021%20c%2035%20§%2010[2021 c 35 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c435.pdf?cite=1987%20c%20435%20§%2022[1987 c 435 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c260.pdf?cite=1984%20c%20260%20§%2013[1984 c 260 § 13]; ]

== 26.18.140 - Hearing to quash, modify, or terminate wage assignment order or income withholding order—Grounds—Alternate payment plan.
. Except as provided in subsection (2) of this section, in a hearing to quash, modify, or terminate the wage assignment order or income withholding order, the court may grant relief only upon a showing that the wage assignment order or income withholding order causes extreme hardship or substantial injustice. Satisfaction by the obligor of all past due payments subsequent to the issuance of the wage assignment order or income withholding order is not grounds to quash, modify, or terminate the wage assignment order or income withholding order. If a wage assignment order or income withholding order has been in operation for twelve consecutive months and the obligor's support or maintenance obligation is current, the court may terminate the order upon motion of the obligor unless the obligee can show good cause as to why the wage assignment order or income withholding order should remain in effect.

. The court may enter an order delaying, modifying, or terminating the wage assignment order or income withholding order and order the obligor to make payments directly to the obligee as provided in RCW 26.23.050(2).

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1171-S.SL.pdf?cite=2021%20c%2035%20§%2011[2021 c 35 § 11]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%201036[2008 c 6 § 1036]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2488-S.SL.pdf?cite=1994%20c%20230%20§%206[1994 c 230 § 6]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1760-S.SL.pdf?cite=1993%20c%20426%20§%2011[1993 c 426 § 11]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5120-S2.SL.pdf?cite=1991%20c%20367%20§%2022[1991 c 367 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c260.pdf?cite=1984%20c%20260%20§%2014[1984 c 260 § 14]; ]

== 26.18.150 - Bond or other security.
. In any action to enforce a support or maintenance order under Title 26 RCW, the court may, in its discretion, order a parent obligated to pay support for a minor child or person owing a duty of maintenance to post a bond or other security with the court. The bond or other security shall be in the amount of support or maintenance due for a two-year period. The bond or other security is subject to approval by the court. The bond shall include the name and address of the issuer. If the bond is canceled, any person issuing a bond under this section shall notify the court and the person entitled to receive payment under the order.

. If the obligor fails to make payments as required under the court order, the person entitled to receive payment may recover on the bond or other security in the existing proceeding. The court may, after notice and hearing, increase the amount of the bond or other security. Failure to comply with the court's order to obtain and maintain a bond or other security may be treated as contempt of court.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%201037[2008 c 6 § 1037]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1760-S.SL.pdf?cite=1993%20c%20426%20§%2012[1993 c 426 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c260.pdf?cite=1984%20c%20260%20§%2015[1984 c 260 § 15]; ]

== 26.18.160 - Costs.
In any action to enforce a support or maintenance order under this chapter, the prevailing party is entitled to a recovery of costs, including an award for reasonable attorney fees. An obligor may not be considered a prevailing party under this section unless the obligee has acted in bad faith in connection with the proceeding in question.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1760-S.SL.pdf?cite=1993%20c%20426%20§%2013[1993 c 426 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c260.pdf?cite=1984%20c%20260%20§%2025[1984 c 260 § 25]; ]

== 26.18.170 - Medical support—Enforcement—Rules.
. Whenever a parent has been ordered to provide medical support for a dependent child, the department or the other parent may seek enforcement of the medical support as provided under this section.

.. If the obligated parent provides proof that he or she provides accessible health care coverage for the child, that parent has satisfied his or her obligation to provide health care coverage.

.. If the obligated parent does not provide proof of coverage, either the department or the other parent may take appropriate action as provided in this section to enforce the obligation.

. An obligated parent may satisfy his or her health care coverage obligation by enrolling the child in public health care coverage, but that parent is also required to provide accessible health insurance coverage for the child if it is available at no cost through the parent's employer or union.

. The fact that one parent enrolled the child in public health care coverage does not satisfy the other parent's health care coverage obligation unless the support order provides otherwise. A parent may satisfy the obligation to provide health care coverage by:

.. First enrolling the child in available and accessible health insurance coverage through the parent's employer or union if such coverage is available for no more than twenty-five percent of the parent's basic support obligation;

.. If there is no accessible health insurance coverage for the child available through the parent's employer or union, contributing a proportionate share of any premium paid by the other parent or the state for public health care coverage for the child.

. The department may attempt to enforce a parent's obligation to provide health insurance coverage for the dependent child. If health insurance coverage is not available through the parent's employment or union at a cost not to exceed twenty-five percent of the parent's basic support obligation, or as otherwise provided in the support order, the department may enforce any monthly payment toward the premium ordered to be provided under RCW 26.09.105 or 74.20A.300.

. A parent seeking to enforce another parent's monthly payment toward the premium under RCW 26.09.105 may:

.. Apply for support enforcement services from the division of child support as provided by rule; or

.. Take action on his or her own behalf by:

... Filing a motion in the underlying superior court action; or

... Initiating an action in superior court to determine the amount owed by the obligated parent, if there is not already an underlying superior court action.

. [Empty]
.. The department may serve a notice of support owed under RCW 26.23.110 on a parent to determine the amount of that parent's monthly payment toward the premium.

.. Whether or not the child receives temporary assistance for needy families or medicaid, the department may enforce the responsible parent's monthly payment toward the premium. When the child receives public health care coverage for which there is an assignment, the department may disburse amounts collected to the custodial parent to be used for the medical costs of the child or the department may retain amounts collected and apply them toward the cost of providing the child's state-financed medical coverage. The department may disregard monthly payments toward the premium which are passed through to the family in accordance with federal law.

. [Empty]
.. If the order to provide health insurance coverage contains language notifying the parent ordered to provide coverage that failure to provide such coverage or proof that such coverage is unavailable may result in direct enforcement of the order and orders payments through, or has been submitted to, the Washington state support registry for enforcement, then the department may, without further notice to the parent, send a national medical support notice pursuant to 42 U.S.C. Sec. 666(a)(19), and sections 401 (e) and (f) of the federal child support and performance incentive act of 1998 to the parent's employer or union. The notice shall be served:

... By regular mail;

... In the manner prescribed for the service of a summons in a civil action;

... By certified mail, return receipt requested; or

... By electronic means if there is an agreement between the secretary of the department and the person, firm, corporation, association, political subdivision, department of the state, or agency, subdivision, or instrumentality of the United States to accept service by electronic means.

.. The notice shall require the employer or union to enroll the child in the health insurance plan as provided in subsection (10) of this section.

.. The returned part A of the national medical support notice to the division of child support by the employer constitutes proof of service of the notice in the case where the notice was served by regular mail.

. Upon receipt of a national medical support notice from a child support agency operating under Title IV-D of the federal social security act:

.. The parent's employer or union shall comply with the provisions of the notice, including meeting response time frames and withholding requirements required under part A of the notice;

.. The parent's employer or union shall also be responsible for complying with forwarding part B of the notice to the child's plan administrator, if required by the notice;

.. The plan administrator is responsible for complying with the provisions of the notice.

. If the parent's order to provide health insurance coverage does not order payments through, and has not been submitted to, the Washington state support registry for enforcement:

.. The parent seeking enforcement may, without further notice to the obligated parent, send a certified copy of the order requiring health insurance coverage to the parent's employer or union by certified mail, return receipt requested; and

.. The parent seeking enforcement shall attach a notarized statement to the order declaring that the order is the latest order addressing coverage entered by the court and require the employer or union to enroll the child in the health insurance plan as provided in subsection (10) of this section.

. Upon receipt of an order that provides for health insurance coverage:

.. The parent's employer or union shall answer the party who sent the order within twenty days and confirm that the child:

... Has been enrolled in the health insurance plan;

... Will be enrolled; or

... Cannot be covered, stating the reasons why such coverage cannot be provided;

.. The employer or union shall withhold any required premium from the parent's income or wages;

.. If more than one plan is offered by the employer or union, and each plan may be extended to cover the child, then the child shall be enrolled in the parent's plan. If the parent's plan does not provide coverage which is accessible to the child, the child shall be enrolled in the least expensive plan otherwise available to the parent;

.. The employer or union shall provide information about the name of the health insurance coverage provider or issuer and the extent of coverage available to the parent and shall make available any necessary claim forms or enrollment membership cards.

. If the order for coverage contains no language notifying either or both parents that failure to provide health insurance coverage or proof that such coverage is unavailable may result in direct enforcement of the order, the department or the parent seeking enforcement may serve a written notice of intent to enforce the order on the obligated parent by certified mail, return receipt requested, or by personal service. If the parent required to provide medical support fails to provide written proof that such coverage has been obtained or applied for or fails to provide proof that such coverage is unavailable within twenty days of service of the notice, the department or the parent seeking enforcement may proceed to enforce the order directly as provided in subsection (7) of this section.

. If the parent ordered to provide health insurance coverage elects to provide coverage that will not be accessible to the child because of geographic or other limitations when accessible coverage is otherwise available, the department or the parent seeking enforcement may serve a written notice of intent to purchase health insurance coverage on the obligated parent by certified mail, return receipt requested. The notice shall also specify the type and cost of coverage.

. If the department serves a notice under subsection (12) of this section the parent required to provide medical support shall, within twenty days of the date of service:

.. File an application for an adjudicative proceeding; or

.. Provide written proof to the department that the obligated parent has either applied for, or obtained, coverage accessible to the child.

. If the parent seeking enforcement serves a notice under subsection (12) of this section, within twenty days of the date of service the parent required to provide medical support shall provide written proof to the parent seeking enforcement that he or she has either applied for, or obtained, coverage accessible to the child.

. If the parent required to provide medical support fails to respond to a notice served under subsection (12) of this section to the party who served the notice, the party who served the notice may purchase the health insurance coverage specified in the notice directly.

.. If the obligated parent is the responsible parent, the amount of the monthly premium shall be added to the support debt and be collectible without further notice.

.. If the obligated parent is the custodial parent, the responsible parent may file an application for enforcement services and ask the department to establish and enforce the custodial parent's obligation.

.. The amount of the monthly premium may be collected or accrued until the parent required to provide medical support provides proof of the required coverage.

. The signature of the parent seeking enforcement or of a department employee shall be a valid authorization to the coverage provider or issuer for purposes of processing a payment to the child's health services provider. An order for health insurance coverage shall operate as an assignment of all benefit rights to the parent seeking enforcement or to the child's health services provider, and in any claim against the coverage provider or issuer, the parent seeking enforcement or his or her assignee shall be subrogated to the rights of the parent obligated to provide medical support for the child. Notwithstanding the provisions of this section regarding assignment of benefits, this section shall not require a health care service contractor authorized under chapter 48.44 RCW or a health maintenance organization authorized under chapter 48.46 RCW to deviate from their contractual provisions and restrictions regarding reimbursement for covered services. If the coverage is terminated, the employer shall mail a notice of termination to the department or the parent seeking enforcement at that parent's last known address within thirty days of the termination date.

. This section shall not be construed to limit the right of the parents or parties to the support order to bring an action in superior court at any time to enforce, modify, or clarify the original support order.

. Where a child does not reside in the issuer's service area, an issuer shall cover no less than urgent and emergent care. Where the issuer offers broader coverage, whether by policy or reciprocal agreement, the issuer shall provide such coverage to any child otherwise covered that does not reside in the issuer's service area.

. If a parent required to provide medical support fails to pay his or her portion, determined under RCW 26.19.080, of any premium, deductible, copay, or uninsured medical expense incurred on behalf of the child, pursuant to a child support order, the department or the parent seeking reimbursement of medical expenses may enforce collection of the obligated parent's portion of the premium, deductible, copay, or uninsured medical expense incurred on behalf of the child.

.. If the department is enforcing the order and the responsible parent is the obligated parent, the obligated parent's portion of the premium, deductible, copay, or uninsured medical expenses incurred on behalf of the child added to the support debt and be collectible without further notice, following the reduction of the expenses to a sum certain either in a court order or by the department, pursuant to RCW 26.23.110.

.. If the custodial parent is the obligated parent, the responsible parent may file an application for enforcement services and ask the department to establish and enforce the custodial parent's obligation.

. As used in this section:

.. "Accessible" means health insurance coverage which provides primary care services to the child or children with reasonable effort by the custodian.

.. "Cash medical support" means a combination of: (i) A parent's monthly payment toward the premium paid for coverage by either the other parent or the state, which represents the obligated parent's proportionate share of the premium paid, but no more than twenty-five percent of the obligated parent's basic support obligation; and (ii) a parent's proportionate share of uninsured medical expenses.

.. "Uninsured medical expenses" includes premiums, copays, deductibles, along with other health care costs not covered by insurance.

.. "Obligated parent" means a parent ordered to provide health insurance coverage for the children.

.. "Monthly payment toward the premium" means a parent's contribution toward premiums paid by the other parent or the state for insurance coverage for the child, which is based on the obligated parent's proportionate share of the premium paid, but no more than twenty-five percent of the obligated parent's basic support obligation.

. The department has rule-making authority to enact rules consistent with 42 U.S.C. Sec. 652(f) and 42 U.S.C. Sec. 666(a)(19) as amended by section 7307 of the deficit reduction act of 2005. Additionally, the department has rule-making authority to implement regulations required under 45 C.F.R. Parts 302, 303, 304, 305, and 308.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6334-S.SL.pdf?cite=2018%20c%20150%20§%20103[2018 c 150 § 103]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1845-S.SL.pdf?cite=2009%20c%20476%20§%202[2009 c 476 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5244-S.SL.pdf?cite=2007%20c%20143%20§%201[2007 c 143 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2579.SL.pdf?cite=2000%20c%2086%20§%202[2000 c 86 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5419-S.SL.pdf?cite=1995%20c%2034%20§%207[1995 c 34 § 7]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2488-S.SL.pdf?cite=1994%20c%20230%20§%207[1994 c 230 § 7]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1760-S.SL.pdf?cite=1993%20c%20426%20§%2014[1993 c 426 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c416.pdf?cite=1989%20c%20416%20§%205[1989 c 416 § 5]; ]

== 26.18.180 - Liability of employer or union—Penalties.
. The employer or union of a parent who has been ordered to provide health insurance coverage shall be liable for a fine of up to one thousand dollars per occurrence, if the employer or union fails or refuses, within twenty days of receiving the order or notice for health insurance coverage to:

.. Promptly enroll the parent's child in the health insurance plan; or

.. Make a written answer to the person or entity who sent the order or notice for health insurance coverage stating that the child:

... Will be enrolled in the next available open enrollment period; or

... Cannot be covered and explaining the reasons why coverage cannot be provided.

. Liability may be established and the fine may be collected by the office of support enforcement under chapter 74.20A or 26.23 RCW using any of the remedies contained in those chapters.

. Any employer or union who enrolls a child in a health insurance plan in compliance with chapter 26.18 RCW shall be exempt from liability resulting from such enrollment.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1845-S.SL.pdf?cite=2009%20c%20476%20§%203[2009 c 476 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2579.SL.pdf?cite=2000%20c%2086%20§%203[2000 c 86 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c416.pdf?cite=1989%20c%20416%20§%209[1989 c 416 § 9]; ]

== 26.18.190 - Compensation paid by agency, self-insurer, social security administration, or veterans' administration on behalf of child.
. When the department of labor and industries or a self-insurer pays compensation under chapter 51.32 RCW on behalf of or on account of the child or children of the injured worker for whom the injured worker owes a duty of child support, the amount of compensation the department or self-insurer pays on behalf of the child or children shall be treated for all purposes as if the injured worker paid the compensation toward satisfaction of the injured worker's child support obligations.

. When the social security administration pays social security disability dependency benefits, retirement benefits, or survivors insurance benefits on behalf of or on account of the child or children of a person with disabilities, a retired person, or a deceased person, the amount of benefits paid for the child or children shall be treated for all purposes as if the person with disabilities, the retired person, or the deceased person paid the benefits toward the satisfaction of that person's child support obligation for that period for which benefits are paid.

. When the veterans' administration apportions a veteran's benefits to pay child support on behalf of or on account of the child or children of the veteran, the amount paid for the child or children shall be treated for all purposes as if the veteran paid the benefits toward the satisfaction of that person's child support obligation for that period for which benefits are paid.

. Under no circumstances shall the person who has the obligation to make the transfer payment have a right to reimbursement of any compensation paid under subsection (1), (2), or (3) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5793.SL.pdf?cite=2015%20c%20124%20§%201[2015 c 124 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1186.SL.pdf?cite=1995%20c%20236%20§%201[1995 c 236 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c2.pdf?cite=1990%201st%20ex.s.%20c%202%20§%2017[1990 1st ex.s. c 2 § 17]; ]

== 26.18.210 - Child support data report.
 In order to perform the required quadrennial review of the Washington state child support guidelines under RCW 26.19.025, the division of child support must prepare a report at least every four years using data compiled from child support court and administrative orders. The report must include all information the division of child support determines is necessary to perform the quadrennial review. On a monthly basis, the clerk of the court must forward all child support worksheets that have been filed with the court to the division of child support.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1298.SL.pdf?cite=2011%20c%2021%20§%201[2011 c 21 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1009-S2.SL.pdf?cite=2007%20c%20313%20§%204[2007 c 313 § 4]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1668.SL.pdf?cite=2005%20c%20282%20§%2033[2005 c 282 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c2.pdf?cite=1990%201st%20ex.s.%20c%202%20§%2022[1990 1st ex.s. c 2 § 22]; ]

== 26.18.220 - Standard court forms—Mandatory use.
. The administrative office of the courts shall develop not later than July 1, 1991, standard court forms and format rules for mandatory use by litigants in all actions commenced under chapters 26.09, *26.10, 26.26A, and 26.26B RCW effective January 1, 1992. The administrator for the courts shall develop mandatory forms for financial affidavits for integration into the worksheets. The forms shall be developed and approved not later than September 1, 1992. The parties shall use the mandatory form for financial affidavits for actions commenced on or after September 1, 1992. The administrative office of the courts has continuing responsibility to develop and revise mandatory forms and format rules as appropriate.

. A party may delete unnecessary portions of the forms according to the rules established by the administrative office of the courts. A party may supplement the mandatory forms with additional material.

. A party's failure to use the mandatory forms or follow the format rules shall not be a reason to dismiss a case, refuse a filing, or strike a pleading. However, the court may require the party to submit a corrected pleading and may impose terms payable to the opposing party or payable to the court, or both.

. The administrative office of the courts shall distribute a master copy of the forms to all county court clerks. The administrative office of the courts and county clerks shall distribute the mandatory forms to the public upon request and may charge for the cost of production and distribution of the forms. Private vendors may distribute the mandatory forms. Distribution may be in printed or electronic form.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5333-S.SL.pdf?cite=2019%20c%2046%20§%205025[2019 c 46 § 5025]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1668.SL.pdf?cite=2005%20c%20282%20§%2034[2005 c 282 § 34]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2784-S.SL.pdf?cite=1992%20c%20229%20§%205[1992 c 229 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990ex1c2.pdf?cite=1990%201st%20ex.s.%20c%202%20§%2025[1990 1st ex.s. c 2 § 25]; ]

== 26.18.230 - Residential time summary report form.
. The administrative office of the courts in consultation with the department of social and health services, division of child support, shall develop a residential time summary report form to provide for the reporting of summary information in every case in which residential time with children is to be established or modified.

. The residential time summary report must include at a minimum: A breakdown of residential schedules with a reasonable degree of specificity regarding actual time with each parent, including enforcement practices, representation status of the parties, whether domestic violence, child abuse, chemical dependency, or mental health issues exist, and whether the matter was agreed or contested.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5327-S.SL.pdf?cite=2017%20c%20183%20§%203[2017 c 183 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5470-S2.SL.pdf?cite=2007%20c%20496%20§%20702[2007 c 496 § 702]; ]

== 26.18.240 - Extension of rights and responsibilities—Domestic partnerships.
. For the purposes of chapter 26.21A RCW, any privilege, immunity, right, benefit, or responsibility granted or imposed by chapter 26.21A RCW, the uniform interstate family support act, to or on an individual because the individual is or was married is granted or imposed on equivalent terms, substantive and procedural, to or on an individual who is or was in a domestic partnership.

. For the purposes of chapter 26.21A RCW, any privilege, immunity, right, benefit, or responsibility granted or imposed by chapter 26.21A RCW, the uniform interstate family support act, to or on a spouse with respect to a child is granted or imposed on equivalent terms, substantive and procedural, to or on a domestic partner with respect to a child.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%201048[2008 c 6 § 1048]; ]

== 26.18.901 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%2066[2009 c 521 § 66]; ]

