= 26.11 - Nonparental child visitation—Relatives.
:toc:

== 26.11.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Parent" means a legal parent whose rights have not been terminated, relinquished, or declared not to exist.

. [Empty]
.. "Relative" means:

... Any blood relative, including those of half-blood, and including first cousins, second cousins, nephews or nieces, and persons of preceding generations as denoted by prefixes of grand, great, or great-great;

... Stepfather, stepmother, stepbrother, and stepsister;

... A person who legally adopts a child or the child's parent as well as the biological and other legally adopted children of such persons, and other relatives of the adoptive parents in accordance with state law;

... Spouses of any persons named in (a)(i), (ii), or (iii) of this subsection, even after the marriage is terminated;

.. Relatives, as named in (a)(i), (ii), or (iii) of this subsection, of any half sibling of the child; or

.. Extended family members, as defined by the law or custom of an Indian child's tribe or, in the absence of such law or custom, a person who has reached the age of eighteen and who is the Indian child's grandparent, aunt or uncle, brother or sister, brother-in-law or sister-in-law, niece or nephew, first or second cousin, or stepparent who provides care in the family abode on a twenty-four hour basis to an Indian child as defined in 25 U.S.C. Sec. 1903(4).

.. "Relative" does not include a person whose parental rights have been terminated, relinquished, or determined not to exist with respect to a child who is the subject of a petition under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5598.SL.pdf?cite=2018%20c%20183%20§%201[2018 c 183 § 1]; ]

== 26.11.020 - Petition for visitation—Criteria—Ongoing and substantial relationship with child—Relatives—Likelihood of harm to child.
. A person who is not the parent of the child may petition for visitation with the child if:

.. The petitioner has an ongoing and substantial relationship with the child;

.. The petitioner is a relative of the child or a parent of the child; and

.. The child is likely to suffer harm or a substantial risk of harm if visitation is denied.

. A person has established an ongoing and substantial relationship with a child if the person and the child have had a relationship formed and sustained through interaction, companionship, and mutuality of interest and affection, without expectation of financial compensation, with substantial continuity for at least two years unless the child is under the age of two years, in which case there must be substantial continuity for at least half of the child's life, and with a shared expectation of and desire for an ongoing relationship.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5598.SL.pdf?cite=2018%20c%20183%20§%202[2018 c 183 § 2]; ]

== 26.11.030 - Venue—Filing requirements—Affidavit—Notice—Hearing—Temporary visitation orders not authorized.
. If a court has jurisdiction over the child pursuant to chapter 26.27 RCW, a petition for visitation under RCW 26.11.020 must be filed with that court.

. Except as otherwise provided in subsection (1) of this section, if a court has exclusive original jurisdiction over the child under *RCW 13.04.030(1) (a) through (d), (h), or (j), a petition for visitation under RCW 26.11.020 must be filed with that court. Granting of a petition for visitation under this chapter does not entitle the petitioner to party status in a child custody proceeding under Title 13 RCW.

. Except as otherwise provided in subsections (1) and (2) of this section, a petition for visitation under RCW 26.11.020 must be filed in the county where the child primarily resides.

. The petitioner may not file a petition for visitation more than once.

. The petitioner must file with the petition an affidavit alleging that:

.. A relationship with the child that satisfies the requirements of RCW 26.11.020 exists or existed before action by the respondent; and

.. The child would likely suffer harm or the substantial risk of harm if visitation between the petitioner and child was not granted.

. The petitioner shall set forth facts in the affidavit supporting the petitioner's requested order for visitation.

. The petitioner shall serve notice of the filing to each person having legal custody of, or court-ordered residential time with, the child. A person having legal custody or residential time with the child may file an opposing affidavit.

. If, based on the petition and affidavits, the court finds that it is more likely than not that visitation will be granted, the court shall hold a hearing.

. The court may not enter any temporary orders to establish, enforce, or modify visitation under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5598.SL.pdf?cite=2018%20c%20183%20§%203[2018 c 183 § 3]; ]

== 26.11.040 - Orders granting visitation—Factors for consideration by the court—Best interest of the child—Presumption in favor of fit parent's decision—Rebuttal.
. [Empty]
.. At a hearing pursuant to RCW 26.11.030(8), the court shall enter an order granting visitation if it finds that the child would likely suffer harm or the substantial risk of harm if visitation between the petitioner and the child is not granted and that granting visitation between the child and the petitioner is in the best interest of the child.

.. An order granting visitation does not confer upon the petitioner the rights and duties of a parent.

. In making its determination, the court shall consider the respondent's reasons for denying visitation. It is presumed that a fit parent's decision to deny visitation is in the best interest of the child and does not create a likelihood of harm or a substantial risk of harm to the child.

. To rebut the presumption in subsection (2) of this section, the petitioner must prove by clear and convincing evidence that the child would likely suffer harm or the substantial risk of harm if visitation between the petitioner and the child were not granted.

. If the court finds that the petitioner has met the standard for rebutting the presumption in subsection (2) of this section, or if there is no presumption because no parent has custody of the child, the court shall consider whether it is in the best interest of the child to enter an order granting visitation. The petitioner must prove by clear and convincing evidence that visitation is in the child's best interest. In determining whether it is in the best interest of the child, the court shall consider the following, nonexclusive factors:

.. The love, affection, and strength of the current relationship between the child and the petitioner and how the relationship is beneficial to the child;

.. The length and quality of the prior relationship between the child and the petitioner before the respondent denied visitation, including the role performed by the petitioner and the emotional ties that existed between the child and the petitioner;

.. The relationship between the petitioner and the respondent;

.. The love, affection, and strength of the current relationship between the child and the respondent;

.. The nature and reason for the respondent's objection to granting the petitioner visitation;

.. The effect that granting visitation will have on the relationship between the child and the respondent;

.. The residential time-sharing arrangements between the parties having residential time with the child;

.. The good faith of the petitioner and respondent;

.. Any history of physical, emotional, or sexual abuse or neglect by the petitioner, or any history of physical, emotional, or sexual abuse or neglect by a person residing with the petitioner if visitation would involve contact between the child and the person with such history;

.. The child's reasonable preference, if the court considers the child to be of sufficient age to express a preference;

.. Any other factor relevant to the child's best interest; and

.. The fact that the respondent has not lost his or her parental rights by being adjudicated as an unfit parent.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5598.SL.pdf?cite=2018%20c%20183%20§%204[2018 c 183 § 4]; ]

== 26.11.050 - Attorneys' fees—Transportation costs.
. [Empty]
.. For the purposes of RCW 26.11.020 through 26.11.040, the court shall, on motion of the respondent, order the petitioner to pay a reasonable amount for costs and reasonable attorneys' fees to the respondent in advance and prior to any hearing, unless the court finds, considering the financial resources of all parties, that it would be unjust to do so.

.. Regardless of the financial resources of the parties, if the court finds that a petition for visitation was brought in bad faith or without reasonable basis in light of the requirements of RCW 26.11.020 through 26.11.040, the court shall order the petitioner to pay a reasonable amount for costs and reasonable attorneys' fees to the respondent.

. If visitation is granted, the court shall order the petitioner to pay all transportation costs associated with visitation.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5598.SL.pdf?cite=2018%20c%20183%20§%205[2018 c 183 § 5]; ]

== 26.11.060 - Modification or termination of orders granting visitation—Substantial change of circumstances.
. A court may not modify or terminate an order granting visitation under RCW 26.11.040 unless it finds, on the basis of facts that have arisen since the entry of the order or were unknown to the court at the time it entered the order, that a substantial change of circumstances has occurred in the circumstances of the child or nonmoving party and that modification or termination of the order is necessary for the best interest of the child.

. [Empty]
.. If a court has jurisdiction over the child pursuant to chapter 26.27 RCW, a petition for modification or termination under this section must be filed with that court.

.. Except as otherwise provided in (a) of this subsection, if a court has exclusive original jurisdiction over the child under *RCW 13.04.030(1) (a) through (d), (h), or (j), a petition for modification or termination under this section must be filed with that court.

.. Except as otherwise provided in (a) or (b) of this subsection, a petition for modification or termination under this section must be filed in the county where the child primarily resides.

. The petitioner must file with the petition an affidavit alleging that, on the basis of facts that have arisen since the entry of the order or were unknown to the court at the time it entered the order, there is a substantial change of circumstances of the child or nonmoving party and that modification or termination of the order is necessary for the best interest of the child. The petitioner shall set forth facts in the affidavit supporting the petitioner's requested order.

. The petitioner shall serve notice of the petition to each person having legal custody of, or court-ordered residential time or court-ordered visitation with, the child. A person having legal custody or residential or visitation time with the child may file an opposing affidavit.

. If, based on the petition and affidavits, the court finds that it is more likely than not that a modification or termination will be granted, the court shall hold a hearing.

. The court may award reasonable attorneys' fees and costs to either party.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5598.SL.pdf?cite=2018%20c%20183%20§%206[2018 c 183 § 6]; ]

