= 26.20 - Family abandonment or nonsupport.
:toc:

== 26.20.030 - Family abandonment—Penalty—Exception.
. Except as provided in subsection (2) of this section, any person who has a child dependent upon him or her for care, education or support and deserts such child in any manner whatever with intent to abandon it is guilty of the crime of family abandonment.

. A parent of a newborn who transfers the newborn to a qualified person at an appropriate location pursuant to RCW 13.34.360 is not subject to criminal liability under this section.

. The crime of family abandonment is a class C felony under chapter 9A.20 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5236-S.SL.pdf?cite=2002%20c%20331%20§%206[2002 c 331 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c260.pdf?cite=1984%20c%20260%20§%2026[1984 c 260 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c154.pdf?cite=1973%201st%20ex.s.%20c%20154%20§%2034[1973 1st ex.s. c 154 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c207.pdf?cite=1969%20ex.s.%20c%20207%20§%202[1969 ex.s. c 207 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c249.pdf?cite=1955%20c%20249%20§%201[1955 c 249 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c255.pdf?cite=1953%20c%20255%20§%201[1953 c 255 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c158.pdf?cite=1943%20c%20158%20§%201[1943 c 158 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c28.pdf?cite=1913%20c%2028%20§%201[1913 c 28 § 1]; Rem. Supp. 1943 § 6908; 1907 c 103 § 1, part; ]

== 26.20.035 - Family nonsupport—Penalty—Exception.
. Except as provided in subsection (2) of this section, any person who is able to provide support, or has the ability to earn the means to provide support, and who:

.. Willfully omits to provide necessary food, clothing, shelter, or medical attendance to a child dependent upon him or her; or

.. Willfully omits to provide necessary food, clothing, shelter, or medical attendance to his or her spouse or his or her domestic partner,

is guilty of the crime of family nonsupport.

. A parent of a newborn who transfers the newborn to a qualified person at an appropriate location pursuant to RCW 13.34.360 is not subject to criminal liability under this section.

. The crime of family nonsupport is a gross misdemeanor under chapter 9A.20 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%201040[2008 c 6 § 1040]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5236-S.SL.pdf?cite=2002%20c%20331%20§%207[2002 c 331 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c260.pdf?cite=1984%20c%20260%20§%2027[1984 c 260 § 27]; ]

== 26.20.071 - Evidence—Spouse or domestic partner as witness.
In any proceedings relating to nonsupport or family desertion the laws attaching a privilege against the disclosure of communications between spouses or domestic partners shall be inapplicable and both spouses or domestic partners in such proceedings shall be competent witnesses to testify to any relevant matter, including marriage, domestic partnership, and parentage.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%201041[2008 c 6 § 1041]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c10.pdf?cite=1963%20c%2010%20§%201[1963 c 10 § 1]; ]

== 26.20.080 - Proof of wilfulness—Application of penalty provisions.
Proof of the nonsupport of a spouse or domestic partner or of a child or children, or the omission to furnish necessary food, clothing, shelter, or medical attendance for a spouse or domestic partner, or for a child or children, is prima facie evidence that the nonsupport or omission to furnish food, clothing, shelter, or medical attendance is wilful. The provisions of RCW 26.20.030 and 26.20.035 are applicable regardless of the marital or domestic partnership status of the person who has a child dependent upon him or her, and regardless of the nonexistence of any decree requiring payment of support or maintenance.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%201042[2008 c 6 § 1042]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c260.pdf?cite=1984%20c%20260%20§%2028[1984 c 260 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c154.pdf?cite=1973%201st%20ex.s.%20c%20154%20§%2036[1973 1st ex.s. c 154 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c28.pdf?cite=1913%20c%2028%20§%203[1913 c 28 § 3]; RRS § 6910; ]

