= 26.28 - Age of majority.
:toc:

== 26.28.010 - Age of majority.
Except as otherwise specifically provided by law, all persons shall be deemed and taken to be of full age for all purposes at the age of eighteen years.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c292.pdf?cite=1971%20ex.s.%20c%20292%20§%201[1971 ex.s. c 292 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c17.pdf?cite=1970%20ex.s.%20c%2017%20§%201[1970 ex.s. c 17 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c72.pdf?cite=1923%20c%2072%20§%202[1923 c 72 § 2]; Code 1881 § 2363; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1866%20p%2092%20§%201[1866 p 92 § 1]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20434%20§%201[1863 p 434 § 1]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20407%20§%201[1854 p 407 § 1]; RRS § 10548; ]

== 26.28.015 - Age of majority for enumerated specific purposes. (Effective until July 1, 2022.)
Notwithstanding any other provision of law, and except as provided under RCW 26.50.020, all persons shall be deemed and taken to be of full age for the specific purposes hereafter enumerated at the age of eighteen years:

. To enter into any marriage contract without parental consent if otherwise qualified by law;

. To execute a will for the disposition of both real and personal property if otherwise qualified by law;

. To vote in any election if authorized by the Constitution and otherwise qualified by law;

. To enter into any legal contractual obligation and to be legally bound thereby to the full extent as any other adult person;

. To make decisions in regard to their own body and the body of their lawful issue whether natural born to or adopted by such person to the full extent allowed to any other adult person including but not limited to consent to surgical operations;

. To sue and be sued on any action to the full extent as any other adult person in any of the courts of this state, without the necessity for a guardian ad litem.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6347-S2.SL.pdf?cite=1992%20c%20111%20§%2012[1992 c 111 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c292.pdf?cite=1971%20ex.s.%20c%20292%20§%202[1971 ex.s. c 292 § 2]; ]

== 26.28.020 - Married persons—When deemed of full age.
All minor persons married to a person of full age shall be deemed and taken to be of full age.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c154.pdf?cite=1973%201st%20ex.s.%20c%20154%20§%2038[1973 1st ex.s. c 154 § 38]; Code 1881 § 2364; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20434%20§%202[1863 p 434 § 2]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20407%20§%202[1854 p 407 § 2]; RRS § 10549; ]

== 26.28.030 - Contracts of minors—Disaffirmance.
A minor is bound, not only by contracts for necessaries, but also by his or her other contracts, unless he or she disaffirms them within a reasonable time after he or she attains his or her majority, and restores to the other party all money and property received by him or her by virtue of the contract, and remaining within his or her control at any time after his or her attaining his or her majority.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20694[2011 c 336 § 694]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1866%20p%2092%20§%202[1866 p 92 § 2]; RRS § 5829; ]

== 26.28.040 - Disaffirmance barred in certain cases.
No contract can be thus disaffirmed in cases where on account of the minor's own misrepresentations as to his or her majority, or from his or her having engaged in business as an adult, the other party had good reasons to believe the minor capable of contracting.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20695[2011 c 336 § 695]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1866%20p%2093%20§%203[1866 p 93 § 3]; RRS § 5830; ]

== 26.28.050 - Satisfaction of minor's contract for services.
When a contract for the personal services of a minor has been made with him or her alone, and those services are afterwards performed, payment made therefor to such minor in accordance with the terms of the contract, is a full satisfaction for those services, and the parents or guardian cannot recover therefor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20696[2011 c 336 § 696]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1866%20p%2093%20§%204[1866 p 93 § 4]; RRS § 5831; ]

== 26.28.060 - Child labor—Penalty.
. Every person who shall employ, and every parent, guardian or other person having the care, custody or control of such child, who shall permit to be employed, by another, any child under the age of fourteen years at any labor whatever, in or in connection with any store, shop, factory, mine or any inside employment not connected with farm or house work, without the written permit thereto of a judge of a superior court of the county wherein such child may live, shall be guilty of a misdemeanor.

. Subsection (1) of this section does not apply to children employed as:

.. Actors or performers in film, video, audio, or theatrical productions; or

.. Youth soccer referees who have been certified by a national referee certification program.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1457.SL.pdf?cite=2007%20c%20464%20§%201[2007 c 464 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6305-S.SL.pdf?cite=1994%20c%2062%20§%201[1994 c 62 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c154.pdf?cite=1973%201st%20ex.s.%20c%20154%20§%2039[1973 1st ex.s. c 154 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20195[1909 c 249 § 195]; RRS § 2447; ]

== 26.28.070 - Certain types of employment prohibited—Penalty.
Every person who shall employ, or cause to be employed, exhibit or have in his or her custody for exhibition or employment any minor actually or apparently under the age of eighteen years; and every parent, relative, guardian, employer, or other person having the care, custody, or control of any such minor, who shall in any way procure or consent to the employment of such minor:

. In begging, receiving alms, or in any mendicant occupation; or,

. In any indecent or immoral exhibition or practice; or,

. In any practice or exhibition dangerous or injurious to life, limb, health, or morals; or,

. As a messenger for delivering letters, telegrams, packages, or bundles, to any known house of prostitution or assignation;

Shall be guilty of a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20697[2011 c 336 § 697]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20194[1909 c 249 § 194]; RRS § 2446; ]

== 26.28.080 - Selling or giving tobacco to minor—Belief of representative capacity, no defense—Penalty.
. A person who sells or gives, or permits to be sold or given, to any person under the age of twenty-one years any cigar, cigarette, cigarette paper or wrapper, tobacco in any form, or a vapor product is guilty of a gross misdemeanor.

. It is not a defense to a prosecution for a violation of this section that the person acted, or was believed by the defendant to act, as agent or representative of another.

. For the purposes of this section, "vapor product" has the same meaning as provided in RCW 70.345.010.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1074.SL.pdf?cite=2019%20c%2015%20§%201[2019 c 15 § 1]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6328-S.SL.pdf?cite=2016%20sp.s.%20c%2038%20§%201[2016 sp.s. c 38 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1937.SL.pdf?cite=2013%20c%2047%20§%201[2013 c 47 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2319-S2.SL.pdf?cite=1994%20sp.s.%20c%207%20§%20437[1994 sp.s. c 7 § 437]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c250.pdf?cite=1987%20c%20250%20§%202[1987 c 250 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c204.pdf?cite=1987%20c%20204%20§%201[1987 c 204 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c292.pdf?cite=1971%20ex.s.%20c%20292%20§%2037[1971 ex.s. c 292 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1919c17.pdf?cite=1919%20c%2017%20§%201[1919 c 17 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1911c133.pdf?cite=1911%20c%20133%20§%201[1911 c 133 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909ex1c27.pdf?cite=1909%20ex.s.%20c%2027%20§%201[1909 ex.s. c 27 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20193[1909 c 249 § 193]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1901c122.pdf?cite=1901%20c%20122%20§%201[1901 c 122 § 1]; 1895 c 126 §§ 1, 3 and 4; RRS § 2445; ]

== 26.28.085 - Applying tattoo to a minor—Penalty.
Every person who applies a tattoo to any minor under the age of eighteen is guilty of a misdemeanor. It is not a defense to a violation of this section that the person applying the tattoo did not know the minor's age unless the person applying the tattoo establishes by a preponderance of the evidence that he or she made a reasonable, bona fide attempt to ascertain the true age of the minor by requiring production of a driver's license or other picture identification card or paper and did not rely solely on the oral allegations or apparent age of the minor.

For the purposes of this section, "tattoo" includes any permanent marking or coloring of the skin with any pigment, ink, or dye, or any procedure that leaves a visible scar on the skin. Medical procedures performed by a licensed physician are exempted from this section.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5190-S.SL.pdf?cite=1995%20c%20373%20§%201[1995 c 373 § 1]; ]

== 26.28.900 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%2069[2009 c 521 § 69]; ]

