= 26.26A - Uniform parentage act.
:toc:

== 26.26A.005 - Short title—2018 c 6.
This act may be known and cited as the uniform parentage act.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20101[2018 c 6 § 101]; ]

== 26.26A.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Acknowledged parent" means an individual who has established a parent-child relationship under RCW 26.26A.200 through 26.26A.265.

. "Adjudicated parent" means an individual who has been adjudicated to be a parent of a child by a court with jurisdiction.

. "Alleged genetic parent" means an individual who is alleged to be, or alleges that the individual is, a genetic parent or possible genetic parent of a child whose parentage has not been adjudicated. The term includes an alleged genetic father and alleged genetic mother. The term does not include:

.. A presumed parent;

.. An individual whose parental rights have been terminated or declared not to exist; or

.. A donor.

. "Assisted reproduction" means a method of causing pregnancy other than sexual intercourse. The term includes:

.. Intrauterine or intracervical insemination;

.. Donation of gametes;

.. Donation of embryos;

.. In-vitro fertilization and transfer of embryos; and

.. Intracytoplasmic sperm injection.

. "Birth record" means a report of birth that has been registered by the state registrar of vital statistics.

. "Child" means an individual of any age whose parentage may be determined under this chapter.

. "Child support agency" means a government entity, public official, or private agency, authorized to provide parentage-establishment services under Title IV-D of the social security act, 42 U.S.C. Secs. 651 through 669.

. "Determination of parentage" means establishment of a parent-child relationship by a judicial proceeding or signing of a valid acknowledgment of parentage under RCW 26.26A.200 through 26.26A.265.

. "Donor" means an individual who provides gametes intended for use in assisted reproduction, whether or not for consideration. The term does not include:

.. A woman who gives birth to a child conceived by assisted reproduction, except as otherwise provided in RCW 26.26A.700 through 26.26A.785; or

.. A parent under RCW 26.26A.600 through 26.26A.635 or an intended parent under RCW 26.26A.700 through 26.26A.785.

. "Gamete" means sperm, egg, or any part of a sperm or egg.

. "Genetic testing" means an analysis of genetic markers to identify or exclude a genetic relationship.

. "Individual" means a natural person of any age.

. "Intended parent" means an individual, married or unmarried, who manifests an intent to be legally bound as a parent of a child conceived by assisted reproduction.

. "Man" means a male individual of any age.

. "Parent" means an individual who has established a parent-child relationship under RCW 26.26A.100.

. "Parentage" or "parent-child relationship" means the legal relationship between a child and a parent of the child.

. "Presumed parent" means an individual who under RCW 26.26A.115 is presumed to be a parent of a child, unless the presumption is overcome in a judicial proceeding, a valid denial of parentage is made under RCW 26.26A.200 through 26.26A.265, or a court adjudicates the individual to be a parent.

. "Record" means information that is inscribed on a tangible medium or that is stored in an electronic or other medium and is retrievable in perceivable form.

. "Sign" means, with present intent to authenticate or adopt a record:

.. To execute or adopt a tangible symbol; or

.. To attach to or logically associate with the record an electronic symbol, sound, or process.

. "Signatory" means an individual who signs a record.

. "State" means a state of the United States, the District of Columbia, Puerto Rico, the United States Virgin Islands, or any territory or insular possession under the jurisdiction of the United States. The term includes a federally recognized Indian tribe.

. "Transfer" means a procedure for assisted reproduction by which an embryo or sperm is placed in the body of the woman who will give birth to the child.

. "Witnessed" means that at least one individual who is authorized to sign has signed a record to verify that the individual personally observed a signatory sign the record.

. "Woman" means a female individual of any age.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20102[2018 c 6 § 102]; ]

== 26.26A.020 - Scope.
. This chapter applies to an adjudication or determination of parentage.

. This chapter does not create, affect, enlarge, or diminish parental rights or duties under law of this state other than this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20103[2018 c 6 § 103]; ]

== 26.26A.030 - Authorized courts.
The superior courts of this state may adjudicate parentage under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20104[2018 c 6 § 104]; ]

== 26.26A.040 - Choice of law.
The court shall apply the law of this state to adjudicate parentage. The applicable law does not depend on:

. The place of birth of the child; or

. The past or present residence of the child.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20105[2018 c 6 § 105]; ]

== 26.26A.050 - Data privacy.
A proceeding under this chapter is subject to law of this state other than this chapter which governs the health, safety, privacy, and liberty of a child or other individual who could be affected by disclosure of information that could identify the child or other individual, including address, telephone number, digital contact information, place of employment, social security number, and the child's day care facility or school.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20106[2018 c 6 § 106]; ]

== 26.26A.060 - Provisions applicable to father-child relationship also applicable to mother-child relationship and vice versa.
To the extent practicable, a provision of this chapter applicable to a father-child relationship applies to a mother-child relationship and a provision of this chapter applicable to a mother-child relationship applies to a father-child relationship.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20107[2018 c 6 § 107]; ]

== 26.26A.070 - Mandatory use of approved forms and format rules.
. Effective January 1, 2020, a party shall not file any pleading with the clerk of the court in an action commenced under this chapter unless on forms approved by the administrator for the courts.

. The administrative office of the courts shall develop and approve standard court forms and format rules for mandatory use by litigants in all actions commenced under this chapter effective January 1, 2020. The administrative office of the courts has continuing responsibility to develop and revise mandatory forms and format rules as appropriate.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5333-S.SL.pdf?cite=2019%20c%2046%20§%201003[2019 c 46 § 1003]; ]

== 26.26A.100 - Establishment of parent-child relationship.
A parent-child relationship is established between an individual and a child if:

. The individual gives birth to the child, except as otherwise provided in RCW 26.26A.700 through 26.26A.785;

. There is a presumption under RCW 26.26A.115 of the individual's parentage of the child, unless the presumption is overcome in a judicial proceeding or a valid denial of parentage is made under RCW 26.26A.200 through 26.26A.265;

. The individual is adjudicated a parent of the child under RCW 26.26A.400 through 26.26A.515;

. The individual adopts the child;

. The individual acknowledges parentage of the child under RCW 26.26A.200 through 26.26A.265, unless the acknowledgment is rescinded under RCW 26.26A.235 or successfully challenged under RCW 26.26A.200 through 26.26A.265 or 26.26A.400 through 26.26A.515;

. The individual's parentage of the child is established under RCW 26.26A.600 through 26.26A.635; or

. The individual's parentage of the child is established under RCW 26.26A.705 through 26.26A.730.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20201[2018 c 6 § 201]; ]

== 26.26A.105 - No discrimination based on marital status of parent.
A parent-child relationship extends equally to every child and parent, regardless of the marital status of the parent.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20202[2018 c 6 § 202]; ]

== 26.26A.110 - Consequences of establishing parentage.
Unless parental rights are terminated, a parent-child relationship established under this chapter applies for all purposes, except as otherwise provided by law of this state other than this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20203[2018 c 6 § 203]; ]

== 26.26A.115 - Presumption of parentage.
. An individual is presumed to be a parent of a child if:

.. Except as otherwise provided under RCW 26.26A.700 through 26.26A.785, or law of this state other than this chapter:

... The individual and the woman who gave birth to the child are married to or in a state registered domestic partnership with each other and the child is born during the marriage or partnership, whether the marriage or partnership is or could be declared invalid;

... The individual and the woman who gave birth to the child were married to or in a state registered domestic partnership with each other and the child is born not later than three hundred days after the marriage or partnership is terminated by death, dissolution, annulment, declaration of invalidity, or legal separation, whether the marriage or partnership is or could be declared invalid; or

... The individual and the woman who gave birth to the child married or entered into a state registered domestic partnership with each other after the birth of the child, whether the marriage or partnership is or could be declared invalid, the individual at any time asserted parentage of the child, and:

(A) The assertion is in a record filed with the state registrar of vital statistics; or

(B) The individual agreed to be and is named as a parent of the child on the birth record of the child; or

.. The individual resided in the same household with the child for the first four years of the life of the child, including any period of temporary absence, and openly held out the child as the individual's child.

. A presumption of parentage under this section may be overcome, and competing claims to parentage may be resolved, only by an adjudication under RCW 26.26A.400 through 26.26A.515, or a valid denial of parentage under RCW 26.26A.200 through 26.26A.265.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20204[2018 c 6 § 204]; ]

== 26.26A.120 - Rule-making authority—RCW  26.26A.115.
The secretary of the department of health may adopt rules under the state administrative procedure act, chapter 34.05 RCW, to implement RCW 26.26A.115.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20205[2018 c 6 § 205]; ]

== 26.26A.125 - Filing fee—Assertion of parentage.
The secretary of the department of health may charge a fee for filing an assertion of parentage.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20206[2018 c 6 § 206]; ]

== 26.26A.200 - Acknowledgment of parentage.
A woman who gave birth to a child and an alleged genetic father of the child, intended parent under RCW 26.26A.600 through 26.26A.635, or presumed parent may sign an acknowledgment of parentage to establish the parentage of the child.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20301[2018 c 6 § 301]; ]

== 26.26A.205 - Execution of acknowledgment of parentage.
. An acknowledgment of parentage under RCW 26.26A.200 must:

.. Be in a record signed by the woman who gave birth to the child and by the individual seeking to establish a parent-child relationship, and the signatures must be attested by a notarial officer or witnessed;

.. State that the child whose parentage is being acknowledged:

... Does not have a presumed parent other than the individual seeking to establish the parent-child relationship or has a presumed parent whose full name is stated; and

... Does not have another acknowledged parent, adjudicated parent, or individual who is a parent of the child under RCW 26.26A.600 through 26.26A.635 and 26.26A.700 through 26.26A.785, other than the woman who gave birth to the child; and

.. State that the signatories understand that the acknowledgment is the equivalent of an adjudication of parentage of the child and that a challenge to the acknowledgment is permitted only under limited circumstances and is barred four years after the effective date of the acknowledgment.

. An acknowledgment of parentage is void if, at the time of signing:

.. An individual other than the individual seeking to establish parentage is a presumed parent, unless a denial of parentage by the presumed parent in a signed record is filed with the state registrar of vital statistics; or

.. An individual, other than the woman who gave birth to the child or the individual seeking to establish parentage, is an acknowledged or adjudicated parent or a parent under RCW 26.26A.600 through 26.26A.635 and 26.26A.700 through 26.26A.785.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20302[2018 c 6 § 302]; ]

== 26.26A.210 - Denial of parentage.
A presumed parent or alleged genetic parent may sign a denial of parentage in a record. The denial of parentage is valid only if:

. An acknowledgment of parentage by another individual is filed under RCW 26.26A.220;

. The signature of the presumed parent or alleged genetic parent is attested by a notarial officer or witnessed; and

. The presumed parent or alleged genetic parent has not previously:

.. Completed a valid acknowledgment of parentage, unless the previous acknowledgment was rescinded under RCW 26.26A.235 or challenged successfully under RCW 26.26A.240; or

.. Been adjudicated to be a parent of the child.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20303[2018 c 6 § 303]; ]

== 26.26A.215 - Acknowledgment or denial of parentage—Requirements.
. An acknowledgment of parentage and a denial of parentage may be contained in a single document or may be in counterparts and may be filed with the state registrar of vital statistics separately or simultaneously. If filing of the acknowledgment and denial both are required under this chapter, neither is effective until both are filed.

. An acknowledgment of parentage or denial of parentage may be signed before or after the birth of the child.

. Subject to subsection (1) of this section, an acknowledgment of parentage or denial of parentage takes effect on the birth of the child or filing of the document with the state registrar of vital statistics, whichever occurs later.

. An acknowledgment of parentage or denial of parentage signed by a minor is valid if the acknowledgment complies with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20304[2018 c 6 § 304]; ]

== 26.26A.220 - Effect of acknowledgment or denial of parentage.
. Except as otherwise provided in RCW 26.26A.235 and 26.26A.240, an acknowledgment of parentage that complies with RCW 26.26A.200 through 26.26A.265 and is filed with the state registrar of vital statistics is equivalent to an adjudication of parentage of the child and confers on the acknowledged parent all rights and duties of a parent.

. Except as otherwise provided in RCW 26.26A.235 and 26.26A.240, a denial of parentage by a presumed parent or alleged genetic parent which complies with RCW 26.26A.200 through 26.26A.265 and is filed with the state registrar of vital statistics with an acknowledgment of parentage that complies with RCW 26.26A.200 through 26.26A.265 is equivalent to an adjudication of the nonparentage of the presumed parent or alleged genetic parent and discharges the presumed parent or alleged genetic parent from all rights and duties of a parent.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20305[2018 c 6 § 305]; ]

== 26.26A.225 - Filing fee—Acknowledgment or denial of parentage.
The secretary of the department of health may charge a fee for filing an acknowledgment of parentage or denial of parentage, or for filing a rescission of an acknowledgment of parentage or denial of parentage.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20306[2018 c 6 § 306]; ]

== 26.26A.230 - Ratification of an unchallenged acknowledgment of parentage barred.
A court conducting a judicial proceeding or an administrative agency conducting an administrative proceeding is not required or permitted to ratify an unchallenged acknowledgment of parentage.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20307[2018 c 6 § 307]; ]

== 26.26A.235 - Procedure for rescission of an acknowledgment or denial of parentage.
. A signatory may rescind an acknowledgment of parentage or denial of parentage by filing with the state registrar of vital statistics a rescission in a signed record which is attested by a notarial officer or witnessed, before the earlier of:

.. Sixty days after the effective date under RCW 26.26A.215 of the acknowledgment or denial; or

.. The date of the first hearing before a court in a proceeding, to which the signatory is a party, to adjudicate an issue relating to the child, including a proceeding that establishes support.

. If an acknowledgment of parentage is rescinded under subsection (1) of this section, an associated denial of parentage is invalid, and the state registrar of vital statistics shall notify the woman who gave birth to the child and the individual who signed a denial of parentage of the child that the acknowledgment has been rescinded. Failure to give the notice required by this subsection does not affect the validity of the rescission.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20308[2018 c 6 § 308]; ]

== 26.26A.240 - Challenge after expiration of period for rescission.
. After the period for rescission under RCW 26.26A.235 expires, but not later than four years after the effective date under RCW 26.26A.215 of an acknowledgment of parentage or denial of parentage, a signatory of the acknowledgment or denial may commence a proceeding to challenge the acknowledgment or denial, including a challenge brought under RCW 26.26A.465, only on the basis of fraud, duress, or material mistake of fact.

. A challenge to an acknowledgment of parentage or denial of parentage by an individual who was not a signatory to the acknowledgment or denial is governed by RCW 26.26A.445.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20309[2018 c 6 § 309]; ]

== 26.26A.245 - Procedure for challenge of an acknowledgment or denial of parentage by signatory.
. Every signatory to an acknowledgment of parentage and any related denial of parentage must be made a party to a proceeding to challenge the acknowledgment or denial.

. By signing an acknowledgment of parentage or denial of parentage, a signatory submits to personal jurisdiction in this state in a proceeding to challenge the acknowledgment or denial, effective on the filing of the acknowledgment or denial with the state registrar of vital statistics.

. The court may not suspend the legal responsibilities arising from an acknowledgment of parentage, including the duty to pay child support, during the pendency of a proceeding to challenge the acknowledgment or a related denial of parentage, unless the party challenging the acknowledgment or denial shows good cause.

. A party challenging an acknowledgment of parentage or denial of parentage has the burden of proof.

. If the court determines that a party has satisfied the burden of proof under subsection (4) of this section, the court shall order the state registrar of vital statistics to amend the birth record of the child to reflect the legal parentage of the child.

. A proceeding to challenge an acknowledgment of parentage or denial of parentage must be conducted under RCW 26.26A.400 through 26.26A.515.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20310[2018 c 6 § 310]; ]

== 26.26A.250 - Full faith and credit.
The court shall give full faith and credit to an acknowledgment of parentage or denial of parentage effective in another state if the acknowledgment or denial was in a signed record and otherwise complies with law of the other state.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20311[2018 c 6 § 311]; ]

== 26.26A.255 - Forms for acknowledgment or denial of parentage.
. The state registrar of vital statistics shall prescribe forms for an acknowledgment of parentage and denial of parentage.

. A valid acknowledgment of parentage or denial of parentage is not affected by a later modification of the form under subsection (1) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20312[2018 c 6 § 312]; ]

== 26.26A.260 - Release of information relating to an acknowledgment or denial of parentage.
The state registrar of vital statistics may release information relating to an acknowledgment of parentage or denial of parentage to a signatory of the acknowledgment or denial, a court, a federal agency, an agency operating a child welfare program under Title IV-E of the social security act, and a child support agency of this or another state.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5955-S.SL.pdf?cite=2019%20c%20470%20§%204[2019 c 470 § 4]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20313[2018 c 6 § 313]; ]

== 26.26A.265 - Rule-making authority—RCW  26.26A.200 through  26.26A.265.
The secretary of the department of health may adopt rules under the state administrative procedure act, chapter 34.05 RCW, to implement RCW 26.26A.200 through 26.26A.265.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20314[2018 c 6 § 314]; ]

== 26.26A.300 - Definitions—Genetic testing—RCW  26.26A.300 through  26.26A.355.
The definitions in this section apply throughout RCW 26.26A.300 through 26.26A.355 unless the context clearly requires otherwise.

. "Combined relationship index" means the product of all tested relationship indices.

. "Ethnic or racial group" means, for the purpose of genetic testing, a recognized group that an individual identifies as the individual's ancestry or part of the ancestry or that is identified by other information.

. "Hypothesized genetic relationship" means an asserted genetic relationship between an individual and a child.

. "Probability of parentage" means, for the ethnic or racial group to which an individual alleged to be a parent belongs, the probability that a hypothesized genetic relationship is supported, compared to the probability that a genetic relationship is supported between the child and a random individual of the ethnic or racial group used in the hypothesized genetic relationship, expressed as a percentage incorporating the combined relationship index and a prior probability.

. "Relationship index" means a likelihood ratio that compares the probability of a genetic marker given a hypothesized genetic relationship and the probability of the genetic marker given a genetic relationship between the child and a random individual of the ethnic or racial group used in the hypothesized genetic relationship.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20401[2018 c 6 § 401]; ]

== 26.26A.305 - Scope—Limitation on use of genetic testing.
. This subchapter, RCW 26.26A.300 through 26.26A.355, governs genetic testing of an individual in a proceeding to adjudicate parentage, whether the individual:

.. Voluntarily submits to testing; or

.. Is tested under an order of the court or a child support agency.

. Genetic testing may not be used:

.. To challenge the parentage of an individual who is a parent under RCW 26.26A.600 through 26.26A.635 and 26.26A.700 through 26.26A.785; or

.. To establish the parentage of an individual who is a donor.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20402[2018 c 6 § 402]; ]

== 26.26A.310 - Authority to order or deny genetic testing.
. Except as otherwise provided in RCW 26.26A.300 through 26.26A.355 or 26.26A.400 through 26.26A.515, in a proceeding under this chapter to determine parentage, the court shall order the child and any other individual to submit to genetic testing if a request for testing is supported by the sworn statement of a party:

.. Alleging a reasonable possibility that the individual is the child's genetic parent; or

.. Denying genetic parentage of the child and stating facts establishing a reasonable possibility that the individual is not a genetic parent.

. A child support agency may order genetic testing only if there is no presumed, acknowledged, or adjudicated parent of a child other than the woman who gave birth to the child.

. The court or child support agency may not order in utero genetic testing.

. If two or more individuals are subject to court-ordered genetic testing, the court may order that testing be completed concurrently or sequentially.

. Genetic testing of a woman who gave birth to a child is not a condition precedent to testing of the child and an individual whose genetic parentage of the child is being determined. If the woman is unavailable or declines to submit to genetic testing, the court may order genetic testing of the child and each individual whose genetic parentage of the child is being adjudicated.

. In a proceeding to adjudicate the parentage of a child having a presumed parent or an individual who claims to be a parent under RCW 26.26A.440, or to challenge an acknowledgment of parentage, the court may deny a motion for genetic testing of the child and any other individual after considering the factors in RCW 26.26A.460 (1) and (2).

. If an individual requesting genetic testing is barred under RCW 26.26A.400 through 26.26A.515 from establishing the individual's parentage, the court shall deny the request for genetic testing.

. An order under this section for genetic testing is enforceable by contempt.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20403[2018 c 6 § 403]; ]

== 26.26A.315 - Requirements for genetic testing.
. Genetic testing must be of a type reasonably relied on by experts in the field of genetic testing and performed in a testing laboratory accredited by:

.. The AABB, formerly known as the American association of blood banks, or a successor to its functions; or

.. An accrediting body designated by the secretary of the United States department of health and human services.

. A specimen used in genetic testing may consist of a sample or a combination of samples of blood, buccal cells, bone, hair, or other body tissue or fluid. The specimen used in the testing need not be of the same kind for each individual undergoing genetic testing.

. Based on the ethnic or racial group of an individual undergoing genetic testing, a testing laboratory shall determine the databases from which to select frequencies for use in calculating a relationship index. If an individual or a child support agency objects to the laboratory's choice, the following rules apply:

.. Not later than thirty days after receipt of the report of the test, the objecting individual or child support agency may request the court to require the laboratory to recalculate the relationship index using an ethnic or racial group different from that used by the laboratory.

.. The individual or the child support agency objecting to the laboratory's choice under this subsection shall:

... If the requested frequencies are not available to the laboratory for the ethnic or racial group requested, provide the requested frequencies compiled in a manner recognized by accrediting bodies; or

... Engage another laboratory to perform the calculations.

.. The laboratory may use its own statistical estimate if there is a question which ethnic or racial group is appropriate. The laboratory shall calculate the frequencies using statistics, if available, for any other ethnic or racial group requested.

. If, after recalculation of the relationship index under subsection (3) of this section using a different ethnic or racial group, genetic testing under RCW 26.26A.325 does not identify an individual as a genetic parent of a child, the court may require an individual who has been tested to submit to additional genetic testing to identify a genetic parent.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20404[2018 c 6 § 404]; ]

== 26.26A.320 - Report of genetic testing.
. A report of genetic testing must be in a record and signed under penalty of perjury by a designee of the testing laboratory. A report complying with the requirements of RCW 26.26A.300 through 26.26A.355 is self-authenticating.

. Documentation from a testing laboratory of the following information is sufficient to establish a reliable chain of custody and allow the results of genetic testing to be admissible without testimony:

.. The name and photograph of each individual whose specimen has been taken;

.. The name of the individual who collected each specimen;

.. The place and date each specimen was collected;

.. The name of the individual who received each specimen in the testing laboratory; and

.. The date each specimen was received.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20405[2018 c 6 § 405]; ]

== 26.26A.325 - Genetic testing results—Challenge to results.
. Subject to a challenge under subsection (2) of this section, an individual is identified under this chapter as a genetic parent of a child if genetic testing complies with RCW 26.26A.300 through 26.26A.355 and the results of the testing disclose:

.. The individual has at least a ninety-nine percent probability of parentage, using a prior probability of 0.50, as calculated by using the combined relationship index obtained in the testing; and

.. A combined relationship index of at least one hundred to one.

. An individual identified under subsection (1) of this section as a genetic parent of the child may challenge the genetic testing results only by other genetic testing satisfying the requirements of RCW 26.26A.300 through 26.26A.355 which:

.. Excludes the individual as a genetic parent of the child; or

.. Identifies another individual as a possible genetic parent of the child other than:

... The woman who gave birth to the child; or

... The individual identified under subsection (1) of this section.

. Except as otherwise provided in RCW 26.26A.350, if more than one individual other than the woman who gave birth is identified by genetic testing as a possible genetic parent of the child, the court shall order each individual to submit to further genetic testing to identify a genetic parent.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20406[2018 c 6 § 406]; ]

== 26.26A.330 - Cost of genetic testing.
. Subject to assessment of fees under RCW 26.26A.400 through 26.26A.515, payment of the cost of initial genetic testing must be made in advance:

.. By a child support agency in a proceeding in which the child support agency is providing services;

.. By the individual who made the request for genetic testing;

.. As agreed by the parties; or

.. As ordered by the court.

. If the cost of genetic testing is paid by a child support agency, the agency may seek reimbursement from the genetic parent whose parent-child relationship is established.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20407[2018 c 6 § 407]; ]

== 26.26A.335 - Additional genetic testing.
The court or child support agency shall order additional genetic testing on request of an individual who contests the result of the initial testing under RCW 26.26A.325. If initial genetic testing under RCW 26.26A.325 identified an individual as a genetic parent of the child, the court or agency may not order additional testing unless the contesting individual pays for the testing in advance.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20408[2018 c 6 § 408]; ]

== 26.26A.340 - Genetic testing when specimen not available.
. Subject to subsection (2) of this section, if a genetic testing specimen is not available from an alleged genetic parent of a child, an individual seeking genetic testing demonstrates good cause, and the court finds that the circumstances are just, the court may order any of the following individuals to submit specimens for genetic testing:

.. A parent of the alleged genetic parent;

.. A sibling of the alleged genetic parent;

.. Another child of the alleged genetic parent and the woman who gave birth to the other child; and

.. Another relative of the alleged genetic parent necessary to complete genetic testing.

. To issue an order under this section, the court must find that a need for genetic testing outweighs the legitimate interests of the individual sought to be tested.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20409[2018 c 6 § 409]; ]

== 26.26A.345 - Genetic testing—Deceased individual.
If an individual seeking genetic testing demonstrates good cause, the court may order genetic testing of a deceased individual.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20410[2018 c 6 § 410]; ]

== 26.26A.350 - Genetic testing—Identical siblings.
. If the court finds there is reason to believe that an alleged genetic parent has an identical sibling and evidence that the sibling may be a genetic parent of the child, the court may order genetic testing of the sibling.

. If more than one sibling is identified under RCW 26.26A.325 as a genetic parent of the child, the court may rely on nongenetic evidence to adjudicate which sibling is a genetic parent of the child.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20411[2018 c 6 § 411]; ]

== 26.26A.355 - Confidentiality of genetic testing—Penalty.
. Release of a report of genetic testing for parentage is controlled by chapter 70.02 RCW.

. An individual who intentionally releases an identifiable specimen of another individual collected for genetic testing under RCW 26.26A.300 through 26.26A.355, for a purpose not relevant to a proceeding regarding parentage, without a court order or written permission of the individual who furnished the specimen, commits a gross misdemeanor punishable under RCW 9.92.020.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20412[2018 c 6 § 412]; ]

== 26.26A.400 - Proceeding to adjudicate parentage—Authorization.
. A proceeding may be commenced to adjudicate the parentage of a child. Except as otherwise provided in this chapter, the proceeding is governed by the rules of civil procedure.

. A proceeding to adjudicate the parentage of a child born under a surrogacy agreement is governed by RCW 26.26A.700 through 26.26A.785.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20501[2018 c 6 § 501]; ]

== 26.26A.405 - Standing to maintain proceeding to adjudicate parentage.
Except as otherwise provided in RCW 26.26A.200 through 26.26A.265 and 26.26A.435 through 26.26A.450, a proceeding to adjudicate parentage may be maintained by:

. The child;

. The woman who gave birth to the child, unless a court has adjudicated that she is not a parent;

. An individual who is a parent under this chapter;

. An individual whose parentage of the child is to be adjudicated;

. The division of child support;

. An adoption agency authorized by law of this state other than this chapter or licensed child placement agency; or

. A representative authorized by law of this state other than this chapter to act for an individual who otherwise would be entitled to maintain a proceeding but is deceased, incapacitated, or a minor.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20502[2018 c 6 § 502]; ]

== 26.26A.410 - Notice of proceeding to adjudicate parentage.
. The petitioner shall give notice of a proceeding to adjudicate parentage to the following individuals:

.. The woman who gave birth to the child, unless a court has adjudicated that she is not a parent;

.. An individual who is a parent of the child under this chapter;

.. A presumed, acknowledged, or adjudicated parent of the child; and

.. An individual whose parentage of the child is to be adjudicated.

. An individual entitled to notice under subsection (1) of this section has a right to intervene in the proceeding.

. Lack of notice required by subsection (1) of this section does not render a judgment void. Lack of notice does not preclude an individual entitled to notice under subsection (1) of this section from bringing a proceeding under RCW 26.26A.450(2).

. Notice must be by service of the summons and complaint on all parties entitled to receive notice under subsection (1) of this section.

. In cases where the child is dependent or alleged to be dependent under chapter 13.34 RCW, the petitioner shall give notice to the state agency administering the plan under Title IV-E of the social security act.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5955-S.SL.pdf?cite=2019%20c%20470%20§%2025[2019 c 470 § 25]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5333-S.SL.pdf?cite=2019%20c%2046%20§%201004[2019 c 46 § 1004]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20503[2018 c 6 § 503]; ]

== 26.26A.415 - Proceeding to adjudicate parentage—Personal jurisdiction.
. The court may adjudicate an individual's parentage of a child only if the court has personal jurisdiction over the individual.

. A court of this state with jurisdiction to adjudicate parentage may exercise personal jurisdiction over a nonresident individual, or the guardian or conservator of the individual, if the conditions prescribed in RCW 26.21A.100 are satisfied.

. Lack of jurisdiction over one individual does not preclude the court from making an adjudication of parentage binding on another individual.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20504[2018 c 6 § 504]; ]

== 26.26A.420 - Proceeding to adjudicate parentage—Venue.
Except as otherwise provided in RCW 26.26A.730, venue for a proceeding to adjudicate parentage is in the county of this state in which:

. The child resides or is located;

. If the child does not reside in this state, the respondent resides or is located; or

. A proceeding has been commenced for administration of the estate of an individual who is or may be a parent under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20505[2018 c 6 § 505]; ]

== 26.26A.425 - Proceeding to adjudicate parentage—Admissibility of results of genetic testing.
. Except as otherwise provided in RCW 26.26A.305(2), the court shall admit a report of genetic testing ordered by the court under RCW 26.26A.310 as evidence of the truth of the facts asserted in the report.

. A party may object to the admission of a report described in subsection (1) of this section, not later than fourteen days after the party receives the report. The party shall cite specific grounds for exclusion.

. A party that objects to the results of genetic testing may call a genetic testing expert to testify in person or by another method approved by the court. Unless the court orders otherwise, the party offering the testimony bears the expense for the expert testifying.

. Admissibility of a report of genetic testing is not affected by whether the testing was performed:

.. Voluntarily or under an order of the court or a child support agency; or

.. Before, on, or after commencement of the proceeding.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20506[2018 c 6 § 506]; ]

== 26.26A.430 - Adjudicating parentage of child with alleged genetic parent.
. A proceeding to determine whether an alleged genetic parent who is not a presumed parent is a parent of a child may be commenced:

.. Before the child becomes an adult; or

.. After the child becomes an adult, but only if the child initiates the proceeding.

. Except as otherwise provided in RCW 26.26A.465, this subsection applies in a proceeding described in subsection (1) of this section if the woman who gave birth to the child is the only other individual with a claim to parentage of the child. The court shall adjudicate an alleged genetic parent to be a parent of the child if the alleged genetic parent:

.. Is identified under RCW 26.26A.325 as a genetic parent of the child and the identification is not successfully challenged under RCW 26.26A.325;

.. Admits parentage in a pleading, when making an appearance, or during a hearing, the court accepts the admission, and the court determines the alleged genetic parent to be a parent of the child;

.. Declines to submit to genetic testing ordered by the court or a child support agency, in which case the court may adjudicate the alleged genetic parent to be a parent of the child even if the alleged genetic parent denies a genetic relationship with the child;

.. Is in default after service of process and the court determines the alleged genetic parent to be a parent of the child; or

.. Is neither identified nor excluded as a genetic parent by genetic testing and, based on other evidence, the court determines the alleged genetic parent to be a parent of the child.

. Except as otherwise provided in RCW 26.26A.465 and subject to other limitations in RCW 26.26A.400 through 26.26A.515, if in a proceeding involving an alleged genetic parent, at least one other individual in addition to the woman who gave birth to the child has a claim to parentage of the child, the court shall adjudicate parentage under RCW 26.26A.460.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20507[2018 c 6 § 507]; ]

== 26.26A.435 - Adjudicating parentage of child with presumed parent.
. A proceeding to determine whether a presumed parent is a parent of a child may be commenced:

.. Before the child becomes an adult; or

.. After the child becomes an adult, but only if the child initiates the proceeding.

. A presumption of parentage under RCW 26.26A.115 cannot be overcome after the child attains four years of age unless the court determines:

.. The presumed parent is not a genetic parent, never resided with the child, and never held out the child as the presumed parent's child; or

.. The child has more than one presumed parent.

. Except as otherwise provided in RCW 26.26A.465, the following rules apply in a proceeding to adjudicate a presumed parent's parentage of a child if the woman who gave birth to the child is the only other individual with a claim to parentage of the child:

.. If no party to the proceeding challenges the presumed parent's parentage of the child, the court shall adjudicate the presumed parent to be a parent of the child.

.. If the presumed parent is identified under RCW 26.26A.325 as a genetic parent of the child and that identification is not successfully challenged under RCW 26.26A.325, the court shall adjudicate the presumed parent to be a parent of the child.

.. If the presumed parent is not identified under RCW 26.26A.325 as a genetic parent of the child and the presumed parent or the woman who gave birth to the child challenges the presumed parent's parentage of the child, the court shall adjudicate the parentage of the child in the best interest of the child based on the factors under RCW 26.26A.460 (1) and (2).

. Except as otherwise provided in RCW 26.26A.465 and subject to other limitations in RCW 26.26A.400 through 26.26A.515, if in a proceeding to adjudicate a presumed parent's parentage of a child, another individual in addition to the woman who gave birth to the child asserts a claim to parentage of the child, the court shall adjudicate parentage under RCW 26.26A.460.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20508[2018 c 6 § 508]; ]

== 26.26A.440 - Adjudicating claim of de facto parentage of child.
. A proceeding to establish parentage of a child under this section may be commenced only by an individual who:

.. Is alive when the proceeding is commenced; and

.. Claims to be a de facto parent of the child.

. An individual who claims to be a de facto parent of a child must commence a proceeding to establish parentage of a child under this section:

.. Before the child attains eighteen years of age; and

.. While the child is alive.

. The following rules govern standing of an individual who claims to be a de facto parent of a child to maintain a proceeding under this section:

.. The individual must file an initial verified pleading alleging specific facts that support the claim to parentage of the child asserted under this section. The verified pleading must be served on all parents and legal guardians of the child and any other party to the proceeding.

.. An adverse party, parent, or legal guardian may file a pleading in response to the pleading filed under (a) of this subsection. A responsive pleading must be verified and must be served on parties to the proceeding.

.. Unless the court finds a hearing is necessary to determine disputed facts material to the issue of standing, the court shall determine, based on the pleadings under (a) and (b) of this subsection, whether the individual has alleged facts sufficient to satisfy by a preponderance of the evidence the requirements of subsection (4)(a) through (g) of this section. If the court holds a hearing under this subsection, the hearing must be held on an expedited basis.

. In a proceeding to adjudicate parentage of an individual who claims to be a de facto parent of the child, the court shall adjudicate the individual who claims to be a de facto parent to be a parent of the child if the individual demonstrates by a preponderance of the evidence that:

.. The individual resided with the child as a regular member of the child's household for a significant period;

.. The individual engaged in consistent caretaking of the child;

.. The individual undertook full and permanent responsibilities of a parent of the child without expectation of financial compensation;

.. The individual held out the child as the individual's child;

.. The individual established a bonded and dependent relationship with the child which is parental in nature;

.. Another parent of the child fostered or supported the bonded and dependent relationship required under (e) of this subsection; and

.. Continuing the relationship between the individual and the child is in the best interest of the child.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20509[2018 c 6 § 509]; ]

== 26.26A.445 - Adjudicating parentage of child with acknowledged parent.
. If a child has an acknowledged parent, a proceeding to challenge the acknowledgment of parentage or a denial of parentage, brought by a signatory to the acknowledgment or denial, is governed by RCW 26.26A.240 and 26.26A.245.

. If a child has an acknowledged parent, the following rules apply in a proceeding to challenge the acknowledgment of parentage or a denial of parentage brought by an individual, other than the child, who has standing under RCW 26.26A.405 and was not a signatory to the acknowledgment or denial:

.. The individual must commence the proceeding not later than four years after the effective date of the acknowledgment.

.. The court may permit the proceeding only if the court finds permitting the proceeding is in the best interest of the child.

.. If the court permits the proceeding, the court shall adjudicate parentage under RCW 26.26A.460.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20510[2018 c 6 § 510]; ]

== 26.26A.450 - Adjudicating parentage of child with adjudicated parent.
. If a child has an adjudicated parent, a proceeding to challenge the adjudication, brought by an individual who was a party to the adjudication or received notice under RCW 26.26A.410, is governed by the rules governing a collateral attack on a judgment.

. If a child has an adjudicated parent, the following rules apply to a proceeding to challenge the adjudication of parentage brought by an individual, other than the child, who has standing under RCW 26.26A.405 and was not a party to the adjudication and did not receive notice under RCW 26.26A.410:

.. The individual must commence the proceeding not later than four years after the effective date of the adjudication.

.. The court may permit the proceeding only if the court finds permitting the proceeding is in the best interest of the child.

.. If the court permits the proceeding, the court shall adjudicate parentage under RCW 26.26A.460.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20511[2018 c 6 § 511]; ]

== 26.26A.455 - Adjudicating parentage of child of assisted reproduction.
. An individual who is a parent under RCW 26.26A.600 through 26.26A.635 or the woman who gave birth to the child may bring a proceeding to adjudicate parentage. If the court determines the individual is a parent under RCW 26.26A.600 through 26.26A.635, the court shall adjudicate the individual to be a parent of the child.

. In a proceeding to adjudicate an individual's parentage of a child, if another individual other than the woman who gave birth to the child is a parent under RCW 26.26A.600 through 26.26A.635, the court shall adjudicate the individual's parentage of the child under RCW 26.26A.460.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20512[2018 c 6 § 512]; ]

== 26.26A.460 - Adjudicating competing claims of parentage.
. Except as otherwise provided in RCW 26.26A.465, in a proceeding to adjudicate competing claims of, or challenges under RCW 26.26A.435(3), 26.26A.445, or 26.26A.450 to, parentage of a child by two or more individuals, the court shall adjudicate parentage in the best interest of the child, based on:

.. The age of the child;

.. The length of time during which each individual assumed the role of parent of the child;

.. The nature of the relationship between the child and each individual;

.. The harm to the child if the relationship between the child and each individual is not recognized;

.. The basis for each individual's claim to parentage of the child; and

.. Other equitable factors arising from the disruption of the relationship between the child and each individual or the likelihood of other harm to the child.

. If an individual challenges parentage based on the results of genetic testing, in addition to the factors listed in subsection (1) of this section, the court shall consider:

.. The facts surrounding the discovery the individual might not be a genetic parent of the child; and

.. The length of time between the time that the individual was placed on notice that the individual might not be a genetic parent and the commencement of the proceeding.

. The court may adjudicate a child to have more than two parents under this chapter if the court finds that failure to recognize more than two parents would be detrimental to the child. A finding of detriment to the child does not require a finding of unfitness of any parent or individual seeking an adjudication of parentage. In determining detriment to the child, the court shall consider all relevant factors, including the harm if the child is removed from a stable placement with an individual who has fulfilled the child's physical needs and psychological needs for care and affection and has assumed the role for a substantial period.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20513[2018 c 6 § 513]; ]

== 26.26A.465 - Precluding establishment of parentage by perpetrator of sexual assault.
. For the purposes of this section, "sexual assault" means nonconsensual sexual penetration that results in pregnancy.

. In a proceeding in which a parent alleges that a person committed a sexual assault that resulted in the parent becoming pregnant and subsequently giving birth to a child, the parent may seek to preclude the person from establishing or maintaining the person's parentage of the child. A parent who alleges that a child was born as a result of sexual assault may also seek additional relief as described in this section.

. This section does not apply if the person described in subsection (2) of this section has previously been adjudicated in a proceeding brought under RCW 26.26A.400 to be a parent of the child, except as may be specifically permitted under subsection (4) of this section.

. Unless RCW 26.26A.240 or 26.26A.430 applies, a parent must file a pleading making an allegation under subsection (2) of this section not later than four years after the birth of the child, except that for a period of one year after January 1, 2019, a court may waive the time bar in cases in which a presumed, acknowledged, or adjudicated parent was found in a criminal or separate civil proceeding to have committed a sexual assault against the parent alleging that the child was born as a result of the sexual assault.

. If a parent makes an allegation under subsection (2) of this section and subsection (3) of this section does not apply, the court must conduct a fact-finding hearing on the allegation.

.. The court may not enter any temporary orders providing residential time or decision making to the alleged perpetrator prior to the fact-finding hearing on the sexual assault allegation unless both of the following criteria are satisfied: (i) The alleged perpetrator has a bonded and dependent relationship with the child that is parental in nature; and (ii) the court specifically finds that it would be in the best interest of the child if such temporary orders are entered.

.. Prior to the fact-finding hearing, the court may order genetic testing to determine whether the alleged perpetrator is biologically related to the child. If genetic testing reveals that the alleged perpetrator is not biologically related to the child, the fact-finding hearing must be stricken.

.. Fourteen days prior to the fact-finding hearing, the parent alleging that the child was born as a result of a sexual assault shall submit affidavits setting forth facts supporting the allegation and shall give notice, together with a copy of the affidavit, to other parties to the proceedings, who may file opposing affidavits. Opposing affidavits must be submitted and served to other parties to the proceeding five days prior to the fact-finding hearing.

.. The court shall determine on the record whether affidavits and documents submitted for the fact-finding hearing should be sealed.

. An allegation under subsection (2) of this section may be proved by:

.. Evidence that the person was convicted of or pleaded guilty to a sexual assault under RCW 9A.44.040, 9A.44.050, or 9A.44.060, or a comparable crime of sexual assault, including child rape of any degree, in this state or any other jurisdiction, against the child's parent and the child was born within three hundred twenty days after the sexual assault; or

.. Clear, cogent, and convincing evidence that the person committed sexual assault, as defined in this section, against the child's parent and the child was born within three hundred twenty days after the sexual assault.

. Subject to subsections (1) through (5) of this section, if the court determines that an allegation has been proved under subsection (6) of this section at the fact-finding hearing or after a bench trial, the court shall:

.. Adjudicate that the person described in subsection (2) of this section is not a parent of the child, has no right to residential time or decision-making responsibilities for the child, has no right to inheritance from the child, and has no right to notification of, or standing to object to, the adoption of the child. If the parent who was the victim of the sexual assault expressly consents in writing for the court to decline to enter one or more of these restrictions or limitations, the court may do so;

.. Require the state registrar of vital statistics to amend the birth record if requested by the parent and the court determines that the amendment is in the best interest of the child; and

.. Require the person pay to child support, birth-related costs, or both, unless the parent requests otherwise and the court determines that granting the request is in the best interest of the child.

. The child's parent or guardian may decline an order for child support or birth-related costs. If the child's parent or guardian declines an order for child support, and is either currently receiving public assistance or later applies for it for the child born as a result of the sexual assault, support enforcement agencies as defined in this chapter shall not file administrative or court proceedings to establish or collect child support, including medical support, from the person described in subsection (2) of this section.

. If the court enters an order under subsection (8) of this section providing that no child support obligation may be established or collected from the person described in subsection (2) of this section, the court shall forward a copy of the order to the Washington state support registry.

. The court may order an award of attorneys' fees under this section on the same basis as attorneys' fees are awarded under RCW 26.09.140.

. Any party may move to close the fact-finding hearing and any related proceedings under this section to the public. If no party files such a motion, the court shall determine on its own initiative whether the fact-finding hearing and any related proceedings under this section should be closed to the public. Upon finding good cause for closing the proceeding, and if consistent with Article I, section 10 of the state Constitution, the court may:

.. Restrict admission to only those persons whom the court finds to have a direct interest in the case or in the work of the court, including witnesses deemed necessary to the disposition of the case; and

.. Restrict persons who are admitted from disclosing any information obtained at the hearing that would identify the parties involved or the child.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5333-S.SL.pdf?cite=2019%20c%2046%20§%204001[2019 c 46 § 4001]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20514[2018 c 6 § 514]; ]

== 26.26A.470 - Proceeding to adjudicate parentage—Temporary child support orders, restraining orders, preliminary injunctions, domestic violence protection orders, antiharassment protection orders, and other court orders—Preservation of support debt. (Effective until July 1, 2022.)
. In a proceeding under RCW 26.26A.400 through 26.26A.515, the court may issue a temporary order for child support if the order is consistent with law of this state other than this chapter and the individual ordered to pay support is:

.. A presumed parent of the child;

.. Petitioning to be adjudicated a parent;

.. Identified as a genetic parent through genetic testing under RCW 26.26A.325;

.. An alleged genetic parent who has declined to submit to genetic testing;

.. Shown by clear and convincing evidence to be a parent of the child; or

.. A parent under this chapter.

. A temporary order may include a provision for parenting time and visitation under law of this state other than this chapter.

. Any party may request the court to issue a temporary restraining order or preliminary injunction, providing relief proper in the circumstances, and restraining or enjoining any party from:

.. Molesting or disturbing the peace of another party;

.. Going onto the grounds of or entering the home, workplace, or school of another party or the day care or school of any child;

.. Knowingly coming within, or knowingly remaining within, a specified distance from a specified location; and

.. Removing a child from the jurisdiction of the court.

. Either party may request a domestic violence protection order under chapter 26.50 RCW or an antiharassment protection order under chapter 10.14 RCW on a temporary basis. The court may grant any of the relief provided in RCW 26.50.060 except relief pertaining to residential provisions for the children which provisions shall be provided for under this chapter, and any of the relief provided in RCW 10.14.080. Ex parte orders issued under this subsection shall be effective for a fixed period not to exceed fourteen days, or upon court order, not to exceed twenty-four days if necessary to ensure that all temporary motions in the case can be heard at the same time.

. Restraining orders issued under this section restraining or enjoining the person from molesting or disturbing another party, or from going onto the grounds of or entering the home, workplace, or school of the other party or the day care or school of any child, or prohibiting the person from knowingly coming within, or knowingly remaining within, a specified distance of a location, shall prominently bear on the front page of the order the legend: VIOLATION OF THIS ORDER WITH ACTUAL NOTICE OF ITS TERMS IS A CRIMINAL OFFENSE UNDER CHAPTER 26.50 RCW AND WILL SUBJECT A VIOLATOR TO ARREST.

. The court shall order that any temporary restraining order bearing a criminal offense legend, any domestic violence protection order, or any antiharassment protection order granted under this section be forwarded by the clerk of the court on or before the next judicial day to the appropriate law enforcement agency specified in the order. Upon receipt of the order, the law enforcement agency shall enter the order into any computer-based criminal intelligence information system available in this state used by law enforcement agencies to list outstanding warrants. The order is fully enforceable in any county in the state.

. If a restraining order issued pursuant to this section is modified or terminated, the clerk of the court shall notify the law enforcement agency specified in the order on or before the next judicial day. Upon receipt of notice that an order has been terminated, the law enforcement agency shall remove the order from any computer-based criminal intelligence information system.

. The court may issue a temporary restraining order without requiring notice to the other party only if it finds on the basis of the moving affidavit or other evidence that irreparable injury could result if an order is not issued until the time for responding has elapsed.

. The court may issue a temporary restraining order or preliminary injunction and an order for temporary support in such amounts and on such terms as are just and proper in the circumstances. In issuing the order, the court shall consider the provisions of RCW 9.41.800.

. A temporary order, temporary restraining order, or preliminary injunction:

.. Does not prejudice the rights of a party or any child which are to be adjudicated at subsequent hearings in the proceeding;

.. May be revoked or modified;

.. Terminates when the final order is entered or when the petition is dismissed; and

.. May be entered in a proceeding for the modification of an existing order.

. A support debt owed to the state for public assistance expenditures which has been charged against a party pursuant to RCW 74.20A.040 and/or 74.20A.055 shall not be merged in, or otherwise extinguished by, the final decree or order, unless the office of support enforcement has been given notice of the final proceeding and an opportunity to present its claim for the support debt to the court and has failed to file an affidavit as provided in this subsection. Notice of the proceeding shall be served upon the office of support enforcement personally, or by certified mail, and shall be given no fewer than thirty days prior to the date of the final proceeding. An original copy of the notice shall be filed with the court either before service or within a reasonable time thereafter. The office of support enforcement may present its claim, and thereby preserve the support debt, by filing an affidavit setting forth the amount of the debt with the court, and by mailing a copy of the affidavit to the parties or their attorney prior to the date of the final proceeding.

. Any party may request the court to issue any order referenced by RCW 9.41.800.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5333-S.SL.pdf?cite=2019%20c%2046%20§%201002[2019 c 46 § 1002]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20515[2018 c 6 § 515]; ]

== 26.26A.475 - Combining a proceeding to adjudicate parentage with other proceedings.
. Except as otherwise provided in subsection (2) of this section, the court may combine a proceeding to adjudicate parentage under this chapter with a proceeding for adoption or termination of parental rights under chapter 26.33 RCW; determination of a parenting plan, child support, annulment, dissolution of marriage, dissolution of a domestic partnership, or legal separation under chapter 26.09 or 26.19 RCW; or probate or administration of an estate under chapter 11.48 or 11.54 RCW; or other appropriate proceeding.

. A respondent may not combine a proceeding described in subsection (1) [of this section] with a proceeding to adjudicate parentage brought under the uniform interstate family support act, chapter 26.21A RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20516[2018 c 6 § 516]; ]

== 26.26A.480 - Proceeding to adjudicate parentage—Before birth of child.
Except as otherwise provided in RCW 26.26A.700 through 26.26A.785, a proceeding to adjudicate parentage may be commenced before the birth of the child and an order or judgment may be entered before birth, but enforcement of the order or judgment must be stayed until the birth of the child. It is the responsibility of the parent to present the order or judgment to the hospital, midwife, or other party handling the delivery of the child so that the birth record may be entered properly.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20517[2018 c 6 § 517]; ]

== 26.26A.485 - Proceeding to adjudicate parentage—Child as party—Representation.
. A minor child is a permissive party but not a necessary party to a proceeding under RCW 26.26A.400 through 26.26A.515.

. The court shall appoint a guardian ad litem, subject to RCW 74.20.310, to represent a child in a proceeding under RCW 26.26A.400 through 26.26A.515, if the court finds that the interests of the child are not adequately represented.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20518[2018 c 6 § 518]; ]

== 26.26A.490 - Proceeding to adjudicate parentage—Without jury.
The court shall adjudicate parentage of a child without a jury.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20519[2018 c 6 § 519]; ]

== 26.26A.500 - Proceeding to adjudicate parentage—Hearing—Inspection of records.
. On request of a party and for good cause, the court may close a proceeding under RCW 26.26A.400 through 26.26A.515 to the public.

. A final order in a proceeding under RCW 26.26A.400 through 26.26A.515 is available for public inspection. Except as provided by applicable court rules, records entered after the entry of a final order determining parentage in a proceeding under this chapter are publicly accessible.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5333-S.SL.pdf?cite=2019%20c%2046%20§%201001[2019 c 46 § 1001]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20520[2018 c 6 § 520]; ]

== 26.26A.505 - Proceeding to adjudicate parentage—Dismissal for want of prosecution—Without prejudice.
The court may dismiss a proceeding under this chapter for want of prosecution only without prejudice. An order of dismissal for want of prosecution purportedly with prejudice is void and has only the effect of a dismissal without prejudice.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20521[2018 c 6 § 521]; ]

== 26.26A.510 - Order adjudicating parentage.
. An order adjudicating parentage must identify the child in a manner provided by law of this state other than this chapter.

. Except as otherwise provided in subsection (3) of this section, the court may assess filing fees, reasonable attorneys' fees, fees for genetic testing, other costs, and necessary travel and other reasonable expenses incurred in a proceeding under RCW 26.26A.400 through 26.26A.515. Attorneys' fees awarded under this subsection may be paid directly to the attorney, and the attorney may enforce the order in the attorney's own name.

. The court may not assess fees, costs, or expenses in a proceeding under RCW 26.26A.400 through 26.26A.515, against a child support agency of this state or another state, except as provided by law of this state other than this chapter.

. In a proceeding under RCW 26.26A.400 through 26.26A.515, a copy of a bill for genetic testing or prenatal or postnatal health care for the woman who gave birth to the child and the child, provided to the adverse party not later than ten days before a hearing, is admissible to establish:

.. The amount of the charge billed; and

.. That the charge is reasonable and necessary.

. On request of a party and for good cause, the court in a proceeding under RCW 26.26A.400 through 26.26A.515, may order the name of the child changed. If the court order changing the name varies from the name on the birth record of the child, the court shall order the state registrar of vital statistics to amend the birth record.

. On request of a party and for good cause, the court in a proceeding under RCW 26.26A.400 through 26.26A.515 may order the parents listed on the birth record of the child changed. If the adjudicated parents listed in the court order vary from the parents listed on the birth record of the child, the court shall order the state registrar of vital statistics to amend the birth record.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20522[2018 c 6 § 522]; ]

== 26.26A.515 - Binding effect of determination of parentage.
. Except as otherwise provided in subsection (2) of this section:

.. A signatory to an acknowledgment of parentage or denial of parentage is bound by the acknowledgment and denial as provided in RCW 26.26A.200 through 26.26A.265; and

.. A party to an adjudication of parentage by a court acting under circumstances that satisfy the jurisdiction requirements of RCW 26.21A.100 and any individual who received notice of the proceeding are bound by the adjudication.

. A child is not bound by a determination of parentage under this chapter unless:

.. The determination was based on an unrescinded acknowledgment of parentage and the acknowledgment is consistent with the results of genetic testing;

.. The determination was based on a finding consistent with the results of genetic testing, and the consistency is declared in the determination or otherwise shown;

.. The determination of parentage was made under RCW 26.26A.600 through 26.26A.635 or 26.26A.700 through 26.26A.785; or

.. The child was a party or was represented by a guardian ad litem in the proceeding.

. In a proceeding for dissolution of marriage or domestic partnership, the court is deemed to have made an adjudication of parentage of a child if the court acts under circumstances that satisfy the jurisdiction requirements of RCW 26.21A.100 and the final order:

.. Expressly identifies the child as a "child of the marriage," "issue of the marriage," "child of the domestic partnership," "issue of the domestic partnership," or includes similar words indicating that both spouses in the marriage or domestic partners in the domestic partnership are parents of the child; or

.. Provides for support of the child by a spouse or domestic partner unless that spouse or domestic partner's parentage is disclaimed specifically in the order.

. Except as otherwise provided in subsection (2) of this section or RCW 26.26A.450, a determination of parentage may be asserted as a defense in a subsequent proceeding seeking to adjudicate parentage of an individual who was not a party to the earlier proceeding.

. A party to an adjudication of parentage may challenge the adjudication only under law of this state other than this chapter relating to appeal, vacation of judgment, or other judicial review.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20523[2018 c 6 § 523]; ]

== 26.26A.600 - Scope—Assisted reproduction—RCW  26.26A.600 through  26.26A.635.
This subchapter, RCW 26.26A.600 through 26.26A.635, does not apply to the birth of a child conceived by sexual intercourse or assisted reproduction under a surrogacy agreement under RCW 26.26A.700 through 26.26A.785.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20601[2018 c 6 § 601]; ]

== 26.26A.605 - Assisted reproduction—Parental status of donor.
A donor is not a parent of a child conceived by assisted reproduction.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20602[2018 c 6 § 602]; ]

== 26.26A.610 - Parentage of child of assisted reproduction.
An individual who consents under RCW 26.26A.615 to assisted reproduction by a woman with the intent to be a parent of a child conceived by the assisted reproduction is a parent of the child.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20603[2018 c 6 § 603]; ]

== 26.26A.615 - Consent to assisted reproduction.
. Except as otherwise provided in subsection (2) of this section, the consent described in RCW 26.26A.610 must be in a record signed by a woman giving birth to a child conceived by assisted reproduction and an individual who intends to be a parent of the child.

. Failure to consent in a record as required by subsection (1) of this section, before, on, or after birth of the child, does not preclude the court from finding consent to parentage if:

.. The woman or the individual proves by clear and convincing evidence the existence of an express agreement entered into before conception that the individual and the woman intended they both would be parents of the child; or

.. The woman and the individual for the first four years of the child's life, including any period of temporary absence, resided together in the same household with the child and both openly held out the child as the individual's child, unless the individual dies or becomes incapacitated before the child attains four years of age or the child dies before the child attains four years of age, in which case the court may find consent under this subsection to parentage if a party proves by clear and convincing evidence that the woman and the individual intended to reside together in the same household with the child and both intended the individual would openly hold out the child as the individual's child, but the individual was prevented from carrying out that intent by death or incapacity.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20604[2018 c 6 § 604]; ]

== 26.26A.620 - Assisted reproduction—Limitation on spouse's dispute of parentage.
. Except as otherwise provided in subsection (2) of this section, an individual who, at the time of a child's birth, is the spouse of the woman who gave birth to the child by assisted reproduction may not challenge the individual's parentage of the child unless:

.. Not later than four years after the birth of the child, the individual commences a proceeding to adjudicate the individual's parentage of the child; and

.. The court finds the individual did not consent to the assisted reproduction, before, on, or after birth of the child, or withdrew consent under RCW 26.26A.630.

. A proceeding to adjudicate a spouse's parentage of a child born by assisted reproduction may be commenced at any time if the court determines:

.. The spouse neither provided a gamete for, nor consented to, the assisted reproduction;

.. The spouse and the woman who gave birth to the child have not cohabited since the probable time of assisted reproduction; and

.. The spouse never openly held out the child as the spouse's child.

. This section applies to a spouse's dispute of parentage even if the spouse's marriage is declared invalid after assisted reproduction occurs.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20605[2018 c 6 § 605]; ]

== 26.26A.625 - Assisted reproduction—Effect of certain legal proceedings regarding marriage or domestic partnership.
If a marriage or domestic partnership of a woman who gives birth to a child conceived by assisted reproduction is terminated through dissolution, subject to legal separation, declared invalid, or annulled before transfer of gametes or embryos to the woman, a former spouse or domestic partner of the woman is not a parent of the child unless the former spouse or domestic partner consented in a record that the former spouse or domestic partner would be a parent of the child if assisted reproduction were to occur after a dissolution, legal separation, declaration of invalidity, or annulment, and the former spouse or domestic partner did not withdraw consent under RCW 26.26A.630.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20606[2018 c 6 § 606]; ]

== 26.26A.630 - Assisted reproduction—Withdrawal of consent.
. An individual who consents under RCW 26.26A.615 to assisted reproduction may withdraw consent any time before a transfer that results in a pregnancy, by giving notice in a record of the withdrawal of consent to the woman who agreed to give birth to a child conceived by assisted reproduction and to any clinic or health care provider facilitating the assisted reproduction. Failure to give notice to the clinic or health care provider does not affect a determination of parentage under this chapter.

. An individual who withdraws consent under subsection (1) of this section is not a parent of the child under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20607[2018 c 6 § 607]; ]

== 26.26A.635 - Assisted reproduction—Parental status of deceased individual.
. If an individual who intends to be a parent of a child conceived by assisted reproduction dies during the period between the transfer of a gamete or embryo and the birth of the child, the individual's death does not preclude the establishment of the individual's parentage of the child if the individual otherwise would be a parent of the child under this chapter.

. If an individual who consented in a record to assisted reproduction by a woman who agreed to give birth to a child dies before a transfer of gametes or embryos, the deceased individual is a parent of a child conceived by the assisted reproduction only if:

.. Either:

... The individual consented in a record that if assisted reproduction were to occur after the death of the individual, the individual would be a parent of the child; or

... The individual's intent to be a parent of a child conceived by assisted reproduction after the individual's death is established by clear and convincing evidence; and

.. Either:

... The embryo is in utero not later than thirty-six months after the individual's death; or

... The child is born not later than forty-five months after the individual's death.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20608[2018 c 6 § 608]; ]

== 26.26A.700 - Definitions—Surrogacy agreement—RCW  26.26A.700 through  26.26A.785.
The definitions in this section apply throughout this subchapter, RCW 26.26A.700 through 26.26A.785, unless the context clearly requires otherwise.

. "Genetic surrogate" means a woman who is not an intended parent and who agrees to become pregnant through assisted reproduction using her own gamete, under a genetic surrogacy agreement as provided in RCW 26.26A.700 through 26.26A.785.

. "Gestational surrogate" means a woman who is not an intended parent and who agrees to become pregnant through assisted reproduction using gametes that are not her own, under a gestational surrogacy agreement as provided in RCW 26.26A.700 through 26.26A.785.

. "Surrogacy agreement" means an agreement between one or more intended parents and a woman who is not an intended parent in which the woman agrees to become pregnant through assisted reproduction and which provides that each intended parent is a parent of a child conceived under the agreement. Unless otherwise specified, the term refers to both a gestational surrogacy agreement and a genetic surrogacy agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20701[2018 c 6 § 701]; ]

== 26.26A.705 - Eligibility to enter gestational or genetic surrogacy agreement.
. To execute an agreement to act as a gestational or genetic surrogate, a woman must:

.. Have attained twenty-one years of age;

.. Previously have given birth to at least one child but not enter into more than two surrogacy agreements that result in the birth of children;

.. Complete a medical evaluation related to the surrogacy arrangement by a licensed medical doctor;

.. Complete a mental health consultation by a licensed mental health professional; and

.. Have independent legal representation of her choice throughout the surrogacy arrangement regarding the terms of the surrogacy agreement and the potential legal consequences of the agreement.

. To execute a surrogacy agreement, each intended parent, whether or not genetically related to the child, must:

.. Have attained twenty-one years of age;

.. Complete a medical evaluation related to the surrogacy arrangement by a licensed medical doctor;

.. Complete a mental health consultation by a licensed mental health professional; and

.. Have independent legal representation of the intended parent's choice throughout the surrogacy arrangement regarding the terms of the surrogacy agreement and the potential legal consequences of the agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20702[2018 c 6 § 702]; ]

== 26.26A.710 - Requirements of gestational or genetic surrogacy agreement—Process.
A surrogacy agreement must be executed in compliance with the following rules:

. At least one party must be a resident of this state or, if no party is a resident of this state, at least one medical evaluation or procedure or mental health consultation under the agreement must occur in this state.

. A woman acting as a surrogate and each intended parent must meet the requirements of RCW 26.26A.705.

. Each intended parent, the woman acting as a surrogate, and the spouse of the woman acting as a surrogate, if any, must be parties to the agreement.

. The agreement must be in a record signed by each party listed in subsection (3) of this section.

. The woman acting as a surrogate and each intended parent must acknowledge in a record receipt of a copy of the agreement.

. The signature of each party to the agreement must be attested by a notarial officer or witnessed.

. The woman acting as a surrogate and the intended parent or parents must have independent legal representation throughout the surrogacy arrangement regarding the terms of the surrogacy agreement and the potential legal consequences of the agreement, and each counsel must be identified in the surrogacy agreement.

. The intended parent or parents must pay for independent legal representation for the woman acting as a surrogate.

. The agreement must be executed before a medical procedure occurs related to the surrogacy agreement, other than the medical evaluation and mental health consultation required by RCW 26.26A.705.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20703[2018 c 6 § 703]; ]

== 26.26A.715 - Requirements of gestational or genetic surrogacy agreement—Content.
. A surrogacy agreement must comply with the following requirements:

.. A woman acting as a surrogate agrees to attempt to become pregnant by means of assisted reproduction.

.. Except as otherwise provided in RCW 26.26A.750, 26.26A.765, and 26.26A.770, the woman acting as a surrogate and the spouse or former spouse of the woman acting as a surrogate, if any, have no claim to parentage of a child conceived by assisted reproduction under the agreement.

.. The spouse of the woman acting as a surrogate, if any, must acknowledge and agree to comply with the obligations imposed on the woman acting as a surrogate by the agreement.

.. Except as otherwise provided in RCW 26.26A.750, 26.26A.765, and 26.26A.770, the intended parent or, if there are two intended parents, each one jointly and severally, immediately on birth will be the exclusive parent or parents of the child, regardless of number of children born or gender or mental or physical condition of each child.

.. Except as otherwise provided in RCW 26.26A.750, 26.26A.765, and 26.26A.770, the intended parent or, if there are two intended parents, each parent jointly and severally, immediately on birth will assume responsibility for the financial support of the child, regardless of number of children born or gender or mental or physical condition of each child.

.. The agreement must include information disclosing how each intended parent will cover the surrogacy-related expenses of the surrogate and the medical expenses of the child. If health care coverage is used to cover the medical expenses, the disclosure must include a summary of the health care policy provisions related to coverage for surrogate pregnancy, including any possible liability of the woman acting as a surrogate, third-party liability liens, other insurance coverage, and any notice requirement that could affect coverage or liability of the woman acting as a surrogate. Unless the agreement expressly provides otherwise, the review and disclosure do not constitute legal advice. If the extent of coverage is uncertain, a statement of that fact is sufficient to comply with this subsection (1)(f).

.. The agreement must permit the woman acting as a surrogate to make all health and welfare decisions regarding herself and her pregnancy and, notwithstanding any other provisions in this chapter, provisions in the agreement to the contrary are void and unenforceable. This chapter does not diminish the right of the woman acting as a surrogate to terminate her pregnancy.

.. The agreement must include information about each party's right under RCW 26.26A.700 through 26.26A.785 to terminate the surrogacy agreement.

. A surrogacy agreement may provide for:

.. Payment of consideration and reasonable expenses; and

.. Reimbursement of specific expenses if the agreement is terminated under RCW 26.26A.700 through 26.26A.785.

. A right created under a surrogacy agreement is not assignable and there is no third-party beneficiary of the agreement other than the child.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20704[2018 c 6 § 704]; ]

== 26.26A.720 - Surrogacy agreement—Effect of subsequent change of marital status.
. Unless a surrogacy agreement expressly provides otherwise:

.. The marriage or domestic partnership of a woman acting as a surrogate after the agreement is signed by all parties does not affect the validity of the agreement, her spouse or domestic partner's consent to the agreement is not required, and her spouse or domestic partner is not a presumed parent of a child conceived by assisted reproduction under the agreement; and

.. The dissolution, annulment, declaration of invalidity, or legal separation of the woman acting as a surrogate after the agreement is signed by all parties does not affect the validity of the agreement.

. Unless a surrogacy agreement expressly provides otherwise:

.. The marriage or domestic partnership of an intended parent after the agreement is signed by all parties does not affect the validity of a surrogacy agreement, the consent of the spouse or domestic partner of the intended parent is not required, and the spouse or domestic partner of the intended parent is not, based on the agreement, a parent of a child conceived by assisted reproduction under the agreement; and

.. The dissolution, annulment, declaration of invalidity, or legal separation of an intended parent after the agreement is signed by all parties does not affect the validity of the agreement and, except as otherwise provided in RCW 26.26A.765, the intended parents are the parents of the child.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20705[2018 c 6 § 705]; ]

== 26.26A.725 - Surrogacy agreement—Inspection of documents.
Unless the court orders otherwise, a petition and any other document related to a surrogacy agreement filed with the court under RCW 26.26A.700 through 26.26A.785, are not open to inspection by any individual other than the parties to the proceeding, a child conceived by assisted reproduction under the agreement, their attorneys, and the state registrar of vital statistics. A court may not authorize an individual to inspect a document related to the agreement, unless required by exigent circumstances. The individual seeking to inspect the document may be required to pay the expense of preparing a copy of the document to be inspected.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20706[2018 c 6 § 706]; ]

== 26.26A.730 - Surrogacy agreement—Venue—Exclusive, continuing jurisdiction.
. Notwithstanding the provisions of RCW 26.26A.420, venue for a proceeding under this subchapter, RCW 26.26A.700 through 26.26A.785, may be in a county of this state in which:

.. The child resides or is located;

.. The respondent resides or is located;

.. An intended parent resides;

.. A medical evaluation or procedure or mental health consultation under the surrogacy agreement occurred; or

.. A proceeding has been commenced for administration of the estate of an individual who is or may be a parent under this subchapter.

. During the period after the execution of a surrogacy agreement until ninety days after the birth of a child conceived by assisted reproduction under the agreement, a court of this state conducting a proceeding under this chapter has exclusive, continuing jurisdiction over all matters arising out of the agreement. This section does not give the court jurisdiction over a child custody or child support proceeding if jurisdiction is not otherwise authorized by law of this state other than this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20707[2018 c 6 § 707]; ]

== 26.26A.735 - Gestational surrogacy agreement—Termination.
. A party to a gestational surrogacy agreement may terminate the agreement, at any time before an embryo transfer, by giving notice of termination in a record to all other parties. If an embryo transfer does not result in a pregnancy, a party may terminate the agreement at any time before a subsequent embryo transfer.

. Unless a gestational surrogacy agreement provides otherwise, on termination of the agreement under subsection (1) of this section, the parties are released from the agreement, except that each intended parent remains responsible for expenses that are reimbursable under the agreement and incurred by the woman acting as a gestational surrogate through the date of termination.

. Except in a case involving fraud, neither a woman acting as a gestational surrogate nor the surrogate's spouse or former spouse, if any, is liable to the intended parent or parents for a penalty or liquidated damages, for terminating a gestational surrogacy agreement under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20708[2018 c 6 § 708]; ]

== 26.26A.740 - Gestational surrogacy agreement—Parentage.
. Except as otherwise provided in subsection (3) of this section or RCW 26.26A.745(2) or 26.26A.755, on birth of a child conceived by assisted reproduction under a gestational surrogacy agreement, each intended parent is, by operation of law, a parent of the child.

. Except as otherwise provided in subsection (3) of this section or RCW 26.26A.755, neither a woman acting as a gestational surrogate nor the surrogate's spouse or former spouse, if any, is a parent of the child.

. If a child is alleged to be a genetic child of the woman who agreed to be a gestational surrogate, the court shall order genetic testing of the child. If the child is a genetic child of the woman who agreed to be a gestational surrogate, parentage must be determined based on RCW 26.26A.005 through 26.26A.515.

. Except as otherwise provided in subsection (3) of this section or RCW 26.26A.745(2) or 26.26A.755, if, due to a clinical or laboratory error, a child conceived by assisted reproduction under a gestational surrogacy agreement is not genetically related to an intended parent or a donor who donated to the intended parent or parents, each intended parent, and not the woman acting as a gestational surrogate and the surrogate's spouse or former spouse, if any, is a parent of the child, subject to any other claim of parentage.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20709[2018 c 6 § 709]; ]

== 26.26A.745 - Gestational surrogacy agreement—Parentage of deceased intended parent.
. RCW 26.26A.740 applies to an intended parent even if the intended parent died during the period between the transfer of a gamete or embryo and the birth of the child.

. Except as otherwise provided in RCW 26.26A.755, an intended parent is not a parent of a child conceived by assisted reproduction under a gestational surrogacy agreement if the intended parent dies before the transfer of a gamete or embryo unless:

.. The agreement provides otherwise; and

.. The transfer of a gamete or embryo occurs not later than thirty-six months after the death of the intended parent or birth of the child occurs not later than forty-five months after the death of the intended parent.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20710[2018 c 6 § 710]; ]

== 26.26A.750 - Gestational surrogacy agreement—Order of parentage.
. Except as otherwise provided in RCW 26.26A.740(3) or 26.26A.755, before, on, or after the birth of a child conceived by assisted reproduction under a gestational surrogacy agreement, a party to the agreement may commence a proceeding in the superior court for an order or judgment:

.. Declaring that each intended parent is a parent of the child and ordering that parental rights and duties vest immediately on the birth of the child exclusively in each intended parent;

.. Declaring that the woman acting as a gestational surrogate and the surrogate's spouse or former spouse, if any, are not the parents of the child;

.. Directing the state registrar of vital statistics to list each intended parent as a parent of the child on the birth record;

.. To protect the privacy of the child and the parties, declaring that the court record is not open to inspection except as authorized under RCW 26.26A.725;

.. If necessary, that the child be surrendered to the intended parent or parents; and

.. For other relief the court determines necessary and proper.

. The court may issue an order or judgment under subsection (1) of this section before the birth of the child. The court shall stay enforcement of the order or judgment until the birth of the child.

. Neither this state nor the state registrar of vital statistics is a necessary party to a proceeding under subsection (1) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20711[2018 c 6 § 711]; ]

== 26.26A.755 - Gestational surrogacy agreement—Effect.
. A gestational surrogacy agreement that complies with RCW 26.26A.705, 26.26A.710, and 26.26A.715 is enforceable.

. If a child was conceived by assisted reproduction under a gestational surrogacy agreement that does not comply with RCW 26.26A.705, 26.26A.710, and 26.26A.715, the court shall determine the rights and duties of the parties to the agreement consistent with the intent of the parties at the time of execution of the agreement. Each party to the agreement and any individual who at the time of the execution of the agreement was a spouse of a party to the agreement has standing to maintain a proceeding to adjudicate an issue related to the enforcement of the agreement.

. Except as expressly provided in a gestational surrogacy agreement or subsection (4) or (5) of this section, if the agreement is breached by the woman acting as a gestational surrogate or one or more intended parents, the nonbreaching party is entitled to the remedies available at law or in equity.

. Specific performance is not a remedy available for breach by a woman acting as a gestational surrogate of a provision in the agreement that the gestational surrogate be impregnated.

. Except as otherwise provided in subsection (4) of this section, if an intended parent is determined to be a parent of the child, specific performance is a remedy available for:

.. Breach of the agreement by a woman acting as a gestational surrogate which prevents the intended parent from exercising immediately on birth of the child the full rights of parentage; or

.. Breach by the intended parent which prevents the intended parent's acceptance, immediately on birth of the child conceived by assisted reproduction under the agreement, of the duties of parentage.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20712[2018 c 6 § 712]; ]

== 26.26A.760 - Genetic surrogacy agreement—Requirements for validation.
. Except as otherwise provided in RCW 26.26A.775, to be enforceable, a genetic surrogacy agreement must be validated by the superior court. A proceeding to validate the agreement must be commenced before assisted reproduction related to the surrogacy agreement.

. The court shall issue an order validating a genetic surrogacy agreement if the court finds that:

.. RCW 26.26A.705, 26.26A.710, and 26.26A.715 are satisfied; and

.. All parties entered into the agreement voluntarily and understand its terms.

. An individual who terminates under RCW 26.26A.765 a genetic surrogacy agreement shall file notice of the termination with the court. On receipt of the notice, the court shall vacate any order issued under subsection (2) of this section. An individual who does not notify the court of the termination of the agreement is subject to sanctions.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20713[2018 c 6 § 713]; ]

== 26.26A.765 - Genetic surrogacy agreement—Termination.
. A party to a genetic surrogacy agreement may terminate the agreement as follows:

.. An intended parent who is a party to the agreement may terminate the agreement at any time before a gamete or embryo transfer by giving notice of termination in a record to all other parties. If a gamete or embryo transfer does not result in a pregnancy, a party may terminate the agreement at any time before a subsequent gamete or embryo transfer. The notice of termination must be attested by a notarial officer or witnessed.

.. A woman acting as a genetic surrogate who is a party to the agreement may withdraw consent to the agreement any time before forty-eight hours after the birth of a child conceived by assisted reproduction under the agreement. To withdraw consent, the woman acting as a genetic surrogate must execute a notice of termination in a record stating the surrogate's intent to terminate the agreement. The notice of termination must be attested by a notarial officer or witnessed and be delivered to each intended parent any time before forty-eight hours after the birth of the child.

. On termination of the genetic surrogacy agreement under subsection (1) of this section, the parties are released from all obligations under the agreement except that each intended parent remains responsible for all expenses incurred by the woman acting as a surrogate through the date of termination which are reimbursable under the agreement. Unless the agreement provides otherwise, the woman acting as a surrogate is not entitled to any nonexpense related compensation paid for serving as a surrogate.

. Except in a case involving fraud, neither a woman acting as a genetic surrogate nor the surrogate's spouse or former spouse, if any, is liable to the intended parent or parents for a penalty or liquidated damages, for terminating a genetic surrogacy agreement under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20714[2018 c 6 § 714]; ]

== 26.26A.770 - Validated genetic surrogacy agreement—Parentage.
. Unless a woman acting as a genetic surrogate exercises the right under RCW 26.26A.765 to terminate a genetic surrogacy agreement, each intended parent is a parent of a child conceived by assisted reproduction under an agreement validated under RCW 26.26A.760.

. Unless a woman acting as a genetic surrogate exercises the right under RCW 26.26A.765 to terminate the genetic surrogacy agreement, on proof of a court order issued under RCW 26.26A.760 validating the agreement, the court shall make an order:

.. Declaring that each intended parent is a parent of a child conceived by assisted reproduction under the agreement and ordering that parental rights and duties vest exclusively in each intended parent;

.. Declaring that the woman acting as a genetic surrogate and the surrogate's spouse or former spouse, if any, are not parents of the child;

.. Directing the state registrar of vital statistics to list each intended parent as a parent of the child on the birth record;

.. To protect the privacy of the child and the parties, declaring that the court record is not open to inspection except as authorized under RCW 26.26A.725;

.. If necessary, that the child be surrendered to the intended parent or parents; and

.. For other relief the court determines necessary and proper.

. If a woman acting as a genetic surrogate terminates under RCW 26.26A.765(1)(b) a genetic surrogacy agreement, parentage of the child conceived by assisted reproduction under the agreement must be determined under RCW 26.26A.005 through 26.26A.515.

. If a child born to a woman acting as a genetic surrogate is alleged not to have been conceived by assisted reproduction, the court shall order genetic testing to determine the genetic parentage of the child. If the child was not conceived by assisted reproduction, parentage must be determined under RCW 26.26A.005 through 26.26A.515. Unless the genetic surrogacy agreement provides otherwise, if the child was not conceived by assisted reproduction the woman acting as a surrogate is not entitled to any nonexpense related compensation paid for serving as a surrogate.

. Unless a party exercises the right under RCW 26.26A.765 to terminate the genetic surrogacy agreement, the woman acting as a genetic surrogate or the department of social and health services division of child support may file with the court, not later than sixty days after the birth of a child conceived by assisted reproduction under the agreement, notice that the child has been born to the woman acting as a genetic surrogate. Unless the woman acting as a genetic surrogate has properly exercised the right under RCW 26.26A.765 to withdraw consent to the agreement, on proof of a court order issued under RCW 26.26A.760 validating the agreement, the court shall order that each intended parent is a parent of the child.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20715[2018 c 6 § 715]; ]

== 26.26A.775 - Nonvalidated genetic surrogacy agreement—Effect.
. A genetic surrogacy agreement, whether or not in a record, that is not validated under RCW 26.26A.760 is enforceable only to the extent provided in this section and RCW 26.26A.785.

. If all parties agree, a court may validate a genetic surrogacy agreement after assisted reproduction has occurred but before the birth of a child conceived by assisted reproduction under the agreement.

. If a child conceived by assisted reproduction under a genetic surrogacy agreement that is not validated under RCW 26.26A.760 is born and the woman acting as a genetic surrogate, consistent with RCW 26.26A.765(1)(b), withdraws her consent to the agreement before forty-eight hours after the birth of the child, the court shall adjudicate the parentage of the child under RCW 26.26A.005 through 26.26A.515.

. If a child conceived by assisted reproduction under a genetic surrogacy agreement that is not validated under RCW 26.26A.760 is born and a woman acting as a genetic surrogate does not withdraw her consent to the agreement, consistent with RCW 26.26A.765(1)(b), before forty-eight hours after the birth of the child, the woman acting as a genetic surrogate is not automatically a parent and the court shall adjudicate parentage of the child based on the best interest of the child, taking into account the factors in RCW 26.26A.460(1) and the intent of the parties at the time of the execution of the agreement.

. The parties to a genetic surrogacy agreement have standing to maintain a proceeding to adjudicate parentage under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20716[2018 c 6 § 716]; ]

== 26.26A.780 - Genetic surrogacy agreement—Parentage of deceased intended parent.
. Except as otherwise provided in RCW 26.26A.770 or 26.26A.775, on birth of a child conceived by assisted reproduction under a genetic surrogacy agreement, each intended parent is, by operation of law, a parent of the child, notwithstanding the death of an intended parent during the period between the transfer of a gamete or embryo and the birth of the child.

. Except as otherwise provided in RCW 26.26A.770 or 26.26A.775, an intended parent is not a parent of a child conceived by assisted reproduction under a genetic surrogacy agreement if the intended parent dies before the transfer of a gamete or embryo unless:

.. The agreement provides otherwise; and

.. The transfer of the gamete or embryo occurs not later than thirty-six months after the death of the intended parent, or birth of the child occurs not later than forty-five months after the death of the intended parent.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20717[2018 c 6 § 717]; ]

== 26.26A.785 - Genetic surrogacy agreement—Breach.
. Subject to RCW 26.26A.715(1)(g) and 26.26A.765(2), if a genetic surrogacy agreement is breached by a woman acting as a genetic surrogate or one or more intended parents, the nonbreaching party is entitled to the remedies available at law or in equity.

. Specific performance is not a remedy available for breach by a woman acting as a genetic surrogate of a requirement of a validated or nonvalidated genetic surrogacy agreement that the surrogate be impregnated.

. Except as otherwise provided in subsection (2) of this section, specific performance is a remedy available for:

.. Breach of a validated genetic surrogacy agreement by a woman acting as a genetic surrogate of a requirement which prevents an intended parent from exercising the full rights of parentage forty-eight hours after the birth of the child; or

.. Breach by an intended parent which prevents the intended parent's acceptance of duties of parentage forty-eight hours after the birth of the child.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20718[2018 c 6 § 718]; ]

== 26.26A.800 - Definitions—Information about donor—RCW  26.26A.800 through  26.26A.825.
The definitions in this section apply throughout RCW 26.26A.800 through 26.26A.825, unless the context clearly requires otherwise.

. "Identifying information" means:

.. The full name of a donor;

.. The date of birth of the donor; and

.. The permanent and, if different, current address of the donor at the time of the donation.

. "Medical history" means information regarding any:

.. Present illness of a donor;

.. Past illness of the donor; and

.. Social, genetic, and family history pertaining to the health of the donor.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20801[2018 c 6 § 801]; ]

== 26.26A.805 - Applicability—RCW  26.26A.800 through  26.26A.825.
RCW 26.26A.800 through 26.26A.825 apply only to gametes collected on or after January 1, 2019.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20802[2018 c 6 § 802]; ]

== 26.26A.810 - Collection of information about donor.
. A gamete bank or fertility clinic licensed in this state shall collect from a donor the donor's identifying information and medical history at the time of the donation.

. A gamete bank or fertility clinic licensed in this state which receives gametes of a donor collected by another gamete bank or fertility clinic shall collect the name, address, telephone number, and email address of the gamete bank or fertility clinic from which it received the gametes.

. A gamete bank or fertility clinic licensed in this state shall disclose the information collected under subsections (1) and (2) of this section as provided under RCW 26.26A.820.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5333-S.SL.pdf?cite=2019%20c%2046%20§%202001[2019 c 46 § 2001]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20803[2018 c 6 § 803]; ]

== 26.26A.815 - Information about donor—Declaration regarding identity disclosure to child conceived by assisted reproduction.
. A gamete bank or fertility clinic licensed in this state which collects gametes from a donor shall:

.. Provide the donor with information in a record about the donor's choice regarding identity disclosure; and

.. Obtain a declaration from the donor regarding identity disclosure.

. A gamete bank or fertility clinic licensed in this state shall give a donor the choice to sign a declaration, attested by a notarial officer or witnessed, that either:

.. States that the donor agrees to disclose the donor's identity to a child conceived by assisted reproduction with the donor's gametes on request once the child attains eighteen years of age; or

.. States that the donor does not agree presently to disclose the donor's identity to the child.

. A gamete bank or fertility clinic licensed in this state shall permit a donor who has signed a declaration under subsection (2)(b) of this section to withdraw the declaration at any time by signing a declaration under subsection (2)(a) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20804[2018 c 6 § 804]; ]

== 26.26A.820 - Information about donor—Disclosure of identifying information and medical history on request of a child conceived by assisted reproduction—Access to nonidentifying medical history.
. On request of a child conceived by assisted reproduction who attains eighteen years of age, a gamete bank or fertility clinic licensed in this state which collected the gametes used in the assisted reproduction shall make a good faith effort to provide the child with identifying information of the donor who provided the gametes, unless the donor signed and did not withdraw a declaration under RCW 26.26A.815(2)(b). If the donor signed and did not withdraw the declaration, the gamete bank or fertility clinic shall make a good faith effort to notify the donor, who may elect under RCW 26.26A.815(3) to withdraw the donor's declaration.

. Regardless whether a donor signed a declaration under RCW 26.26A.815(2)(b), on request by a child conceived by assisted reproduction who attains eighteen years of age, or, if the child is a minor, by a parent or guardian of the child, a gamete bank or fertility clinic licensed in this state which collected the gametes used in the assisted reproduction shall make a good faith effort to provide the child or, if the child is a minor, the parent or guardian of the child, access to nonidentifying medical history of the donor.

. On request of a child conceived by assisted reproduction who attains eighteen years of age, a gamete bank or fertility clinic licensed in this state which received the gametes used in the assisted reproduction from another gamete bank or fertility clinic shall disclose the name, address, telephone number, and email address of the gamete bank or fertility clinic from which it received the gametes.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5333-S.SL.pdf?cite=2019%20c%2046%20§%202002[2019 c 46 § 2002]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20805[2018 c 6 § 805]; ]

== 26.26A.825 - Information about donor—Recordkeeping duty of gamete bank or fertility clinic.
. A gamete bank or fertility clinic licensed in this state which collects gametes for use in assisted reproduction shall maintain identifying information and medical history about each gamete donor. The gamete bank or fertility clinic shall maintain records of gamete screening and testing and comply with reporting requirements, in accordance with federal law and applicable law of this state other than this chapter.

. A gamete bank or fertility clinic licensed in this state that receives gametes from another gamete bank or fertility clinic shall maintain the name, address, and telephone number of the gamete bank or fertility clinic from which it received the gametes.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5333-S.SL.pdf?cite=2019%20c%2046%20§%202003[2019 c 46 § 2003]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20806[2018 c 6 § 806]; ]

== 26.26A.900 - Uniformity of application and construction—2018 c 6.
In applying and construing this uniform act, consideration must be given to the need to promote uniformity of the law with respect to its subject matter among states that enact it.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20901[2018 c 6 § 901]; ]

== 26.26A.901 - Relation to electronic signatures in global and national commerce act.
This chapter modifies, limits, or supersedes the electronic signatures in global and national commerce act, 15 U.S.C. Sec. 7001 et seq., but does not modify, limit, or supersede section 101(c) of that act, 15 U.S.C. Sec. 7001(c), or authorize electronic delivery of any of the notices described in section 103(b) of that act, 15 U.S.C. Sec. 7003(b).

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20902[2018 c 6 § 902]; ]

== 26.26A.902 - Transitional provision—Applicability to pending proceedings.
This chapter applies to a pending proceeding to adjudicate parentage commenced before January 1, 2019, for an issue on which a judgment has not been entered.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20903[2018 c 6 § 903]; ]

== 26.26A.903 - Effective date—2018 c 6.
This act takes effect January 1, 2019.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6037-S.SL.pdf?cite=2018%20c%206%20§%20909[2018 c 6 § 909]; ]

