= 26.21A - Uniform interstate family support act.
:toc:

== 26.21A.005 - Short title.
This chapter may be cited as the uniform interstate family support act.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20101[2002 c 198 § 101]; ]

== 26.21A.010 - Definitions.
In this chapter:

. "Child" means an individual, whether over or under the age of majority, who is or is alleged to be owed a duty of support by the individual's parent or who is or is alleged to be the beneficiary of a support order directed to the parent.

. "Child support order" means a support order for a child, including a child who has attained the age of majority under the law of the issuing state or foreign country.

. "Convention" means the convention on the international recovery of child support and other forms of family maintenance, concluded at the Hague on November 23, 2007.

. "Duty of support" means an obligation imposed or imposable by law to provide support for a child, spouse, or former spouse, including an unsatisfied obligation to provide support.

. "Foreign country" means a country, including a political subdivision thereof, other than the United States, that authorizes the issuance of support orders and:

.. Which has been declared under the law of the United States to be a foreign reciprocating country;

.. Which has established a reciprocal arrangement for child support with this state as provided in RCW 26.21A.235;

.. Which has enacted a law or established procedures for the issuance and enforcement of support orders which are substantially similar to the procedures under this chapter; or

.. In which the convention is in force with respect to the United States.

. "Foreign support order" means a support order of a foreign tribunal.

. "Foreign tribunal" means a court, administrative agency, or quasi-judicial entity of a foreign country which is authorized to establish, enforce, or modify support orders or to determine parentage of a child. The term includes a competent authority under the convention.

. "Home state" means the state or foreign country in which a child lived with a parent or a person acting as parent for at least six consecutive months immediately preceding the time of filing of a petition or comparable pleading for support and, if a child is less than six months old, the state or foreign country in which the child lived from birth with any of them. A period of temporary absence of any of them is counted as part of the six-month or other period.

. "Income" includes earnings or other periodic entitlements to money from any source and any other property subject to withholding for support under the law of this state.

. "Income-withholding order" means an order or other legal process directed to an obligor's employer or other debtor, as defined by RCW 50.04.080, to withhold support from the income of the obligor.

. "Initiating tribunal" means the tribunal of a state or foreign country from which a petition or comparable pleading is forwarded or in which a petition or comparable pleading is filed for forwarding to another state or foreign country.

. "Issuing foreign country" means the foreign country in which a tribunal issues a support order or a judgment determining parentage of a child.

. "Issuing state" means the state in which a tribunal issues a support order or a judgment determining parentage of a child.

. "Issuing tribunal" means the tribunal of a state or foreign country that issues a support order or a judgment determining parentage of a child.

. "Law" includes decisional and statutory law and rules having the force of law.

. "Obligee" means:

.. An individual to whom a duty of support is or is alleged to be owed or in whose favor a support order has been issued or a judgment determining parentage of a child has been issued;

.. A foreign country, state, or political subdivision of a state to which the rights under a duty of support or support order have been assigned or which has independent claims based on financial assistance provided to an individual obligee in place of child support;

.. An individual seeking a judgment determining parentage of the individual's child; or

.. A person that is a creditor in a proceeding under Article 7 of this chapter.

. "Obligor" means an individual, or the estate of a decedent that:

.. Owes or is alleged to owe a duty of support;

.. Is alleged but has not been adjudicated to be a parent of a child;

.. Is liable under a support order; or

.. Is a debtor in a proceeding under Article 7 of this chapter.

. "Outside this state" means a location in another state or a country other than the United States, whether or not the country is a foreign country.

. "Person" means an individual, corporation, business trust, estate, trust, partnership, limited liability company, association, joint venture, public corporation, government or governmental subdivision, agency, or instrumentality, or any other legal or commercial entity.

. "Record" means information that is inscribed on a tangible medium or that is stored in an electronic or other medium and is retrievable in perceivable form.

. "Register" means to record or file in a tribunal of this state a support order or judgment determining parentage of a child issued in another state or a foreign country.

. "Registering tribunal" means a tribunal in which a support order or judgment determining parentage of a child is registered.

. "Responding state" means a state in which a petition or comparable pleading for support or to determine parentage of a child is filed or to which a petition or comparable pleading is forwarded for filing from another state or foreign country.

. "Responding tribunal" means the authorized tribunal in a responding state or foreign country.

. "Spousal support order" means a support order for a spouse or former spouse of the obligor.

. "State" means a state of the United States, the District of Columbia, Puerto Rico, the United States Virgin Islands, or any territory or insular possession under the jurisdiction of the United States. The term includes an Indian nation or tribe.

. "Support enforcement agency" means a public official, governmental entity, or private agency authorized to:

.. Seek enforcement of support orders or laws relating to the duty of support;

.. Seek establishment or modification of child support;

.. Request determination of parentage of a child;

.. Attempt to locate obligors or their assets; or

.. Request determination of the controlling child support order.

. "Support order" means a judgment, decree, order, decision, or directive, whether temporary, final, or subject to modification, issued in a state or foreign country for the benefit of a child, a spouse, or a former spouse, which provides for monetary support, health care, arrearages, retroactive support, or reimbursement for financial assistance provided to an individual obligee in place of child support. The term may include related costs and fees, interest, income withholding, automatic adjustment, reasonable attorneys' fees, and other relief.

. "Tribunal" means a court, administrative agency, or quasi-judicial entity authorized to establish, enforce, or modify support orders or to determine parentage of a child.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%201[2015 c 214 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20102[2002 c 198 § 102]; ]

== 26.21A.015 - State tribunal and support enforcement agency.
. The superior court is the tribunal for judicial proceedings, and the department of social and health services division of child support is the tribunal for administrative proceedings, of this state.

. The department of social and health services division of child support is the support enforcement agency of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%202[2015 c 214 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20103[2002 c 198 § 103]; ]

== 26.21A.020 - Remedies cumulative.
. Remedies provided by this chapter are cumulative and do not affect the availability of remedies under other law or the recognition of a foreign support order on the basis of comity.

. This chapter does not:

.. Provide the exclusive method of establishing or enforcing a support order under the law of this state; or

.. Grant a tribunal of this state jurisdiction to render judgment or issue an order relating to child custody or visitation in a proceeding under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%203[2015 c 214 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20104[2002 c 198 § 104]; ]

== 26.21A.025 - Application of chapter to resident of foreign country and foreign support proceeding.
. A tribunal of this state shall apply Articles 1 through 6 of this chapter and, as applicable, Article 7 of this chapter, to a support proceeding involving:

.. A foreign support order;

.. A foreign tribunal; or

.. An obligee, obligor, or child residing in a foreign country.

. A tribunal of this state that is requested to recognize and enforce a support order on the basis of comity may apply the procedural and substantive provisions of Articles 1 through 6 of this chapter.

. Article 7 of this chapter applies only to a support proceeding under the convention. In such a proceeding, if a provision of Article 7 of this chapter is inconsistent with a provision of Articles 1 through 6 of this chapter, Article 7 of this chapter controls.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2041[2015 c 214 § 41]; ]

== 26.21A.100 - Bases for jurisdiction over nonresident.
. In a proceeding to establish or enforce a support order or to determine parentage of a child, a tribunal of this state may exercise personal jurisdiction over a nonresident individual or the individual's guardian or conservator if:

.. The individual is personally served with a citation, summons, or notice within this state;

.. The individual submits to the jurisdiction of this state by consent in a record, by entering a general appearance, or by filing a responsive document having the effect of waiving any contest to personal jurisdiction;

.. The individual resided with the child in this state;

.. The individual resided in this state and provided prenatal expenses or support for the child;

.. The child resides in this state as a result of the acts or directives of the individual;

.. The individual engaged in sexual intercourse in this state and the child may have been conceived by that act of intercourse; or

.. There is any other basis consistent with the constitutions of this state and the United States for the exercise of personal jurisdiction.

. The bases of personal jurisdiction set forth in subsection (1) of this section or in any other law of this state may not be used to acquire personal jurisdiction for a tribunal of this state to modify a child support order of another state unless the requirements of RCW 26.21A.550 are met, or, in the case of a foreign support order, unless the requirements of RCW 26.21A.570 are met.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%204[2015 c 214 § 4]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20201[2002 c 198 § 201]; ]

== 26.21A.106 - Duration of personal jurisdiction.
Personal jurisdiction acquired by a tribunal of this state in a proceeding under this chapter or other law of this state relating to a support order continues as long as a tribunal of this state has continuing, exclusive jurisdiction to modify its order or continuing jurisdiction to enforce its order as provided by RCW 26.21A.120, 26.21A.125, and 26.21A.150.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2042[2015 c 214 § 42]; ]

== 26.21A.110 - Initiating and responding tribunal of this state.
Under this chapter, a tribunal of this state may serve as an initiating tribunal to forward proceedings to a tribunal of another state and as a responding tribunal for proceedings initiated in another state or a foreign country.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%205[2015 c 214 § 5]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20203[2002 c 198 § 203]; ]

== 26.21A.115 - Simultaneous proceedings.
. A tribunal of this state may exercise jurisdiction to establish a support order if the petition or comparable pleading is filed after a pleading is filed in another state or a foreign country only if:

.. The petition or comparable pleading in this state is filed before the expiration of the time allowed in the other state or the foreign country for filing a responsive pleading challenging the exercise of jurisdiction by the other state or the foreign country;

.. The contesting party timely challenges the exercise of jurisdiction in the other state or the foreign country; and

.. If relevant, this state is the home state of the child.

. A tribunal of this state may not exercise jurisdiction to establish a support order if the petition or comparable pleading is filed before a petition or comparable pleading is filed in another state or a foreign country if:

.. The petition or comparable pleading in the other state or foreign country is filed before the expiration of the time allowed in this state for filing a responsive pleading challenging the exercise of jurisdiction by this state;

.. The contesting party timely challenges the exercise of jurisdiction in this state; and

.. If relevant, the other state or foreign country is the home state of the child.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%206[2015 c 214 § 6]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20204[2002 c 198 § 204]; ]

== 26.21A.120 - Continuing, exclusive jurisdiction to modify child support order.
. A tribunal of this state that has issued a child support order consistent with the law of this state has and shall exercise continuing, exclusive jurisdiction to modify its child support order if the order is the controlling order and:

.. At the time of the filing of a request for modification this state is the residence of the obligor, the individual obligee, or the child for whose benefit the support order is issued; or

.. Even if this state is not the residence of the obligor, the individual obligee, or the child for whose benefit the support order is issued, the parties consent in a record or in open court that the tribunal of this state may continue to exercise jurisdiction to modify its order.

. A tribunal of this state that has issued a child support order consistent with the law of this state shall not exercise continuing, exclusive jurisdiction to modify the order if:

.. All of the parties who are individuals file consent in a record with the tribunal of this state that a tribunal of another state that has jurisdiction over at least one of the parties who is an individual or that is located in the state of residence of the child may modify the order and assume continuing, exclusive jurisdiction; or

.. Its order is not the controlling order.

. If a tribunal of another state has issued a child support order pursuant to the uniform interstate family support act or a law substantially similar to that act which modifies a child support order of a tribunal of this state, tribunals of this state shall recognize the continuing, exclusive jurisdiction of the tribunal of the other state.

. A tribunal of this state that lacks continuing, exclusive jurisdiction to modify a child support order may serve as an initiating tribunal to request a tribunal of another state to modify a support order issued in that state.

. A temporary support order issued ex parte or pending resolution of a jurisdictional conflict does not create continuing, exclusive jurisdiction in the issuing tribunal.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20205[2002 c 198 § 205]; ]

== 26.21A.125 - Continuing jurisdiction to enforce child support order.
. A tribunal of this state that has issued a child support order consistent with the law of this state may serve as an initiating tribunal to request a tribunal of another state to enforce:

.. The order if the order is the controlling order and has not been modified by a tribunal of another state that assumed jurisdiction pursuant to the uniform interstate family support act; or

.. A money judgment for arrears of support and interest on the order accrued before a determination that an order of a tribunal of another state is the controlling order.

. A tribunal of this state having continuing jurisdiction over a support order may act as a responding tribunal to enforce the order.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%207[2015 c 214 § 7]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20206[2002 c 198 § 206]; ]

== 26.21A.130 - Determination of controlling child support order.
. If a proceeding is brought under this chapter and only one tribunal has issued a child support order, the order of that tribunal controls and must be so recognized.

. If a proceeding is brought under this chapter, and two or more child support orders have been issued by tribunals of this state, or another state, or a foreign country with regard to the same obligor and same child, a tribunal of this state having personal jurisdiction over both the obligor and individual obligee shall apply the following rules and by order shall determine which order controls and must be recognized:

.. If only one of the tribunals would have continuing, exclusive jurisdiction under this chapter, the order of that tribunal controls.

.. If more than one of the tribunals would have continuing, exclusive jurisdiction under this chapter:

... An order issued by a tribunal in the current home state of the child controls; or

... If an order has not been issued in the current home state of the child, the order most recently issued controls.

.. If none of the tribunals would have continuing, exclusive jurisdiction under this chapter, the tribunal of this state shall issue a child support order, which controls.

. If two or more child support orders have been issued for the same obligor and same child, upon request of a party who is an individual or that is a support enforcement agency, a tribunal of this state having personal jurisdiction over both the obligor and the obligee who is an individual shall determine which order controls under subsection (2) of this section. The request may be filed with a registration for enforcement or registration for modification pursuant to Article 6 of this chapter, or may be filed as a separate proceeding.

. A request to determine which is the controlling order must be accompanied by a copy of every child support order in effect and the applicable record of payments. The requesting party shall give notice of the request to each party whose rights may be affected by the determination.

. The tribunal that issued the controlling order under subsection (1), (2), or (3) of this section has continuing jurisdiction to the extent provided in RCW 26.21A.120 or 26.21A.125.

. A tribunal of this state that determines by order which is the controlling order under subsection (2)(a) or (b) or (3) of this section or that issues a new controlling order under subsection (2)(c) of this section shall state in that order:

.. The basis upon which the tribunal made its determination;

.. The amount of prospective support, if any; and

.. The total amount of consolidated arrears and accrued interest, if any, under all of the orders after all payments made are credited as provided by RCW 26.21A.140.

. Within thirty days after issuance of an order determining which is the controlling order, the party obtaining the order shall file a certified copy of it in each tribunal that issued or registered an earlier order of child support. A party or support enforcement agency obtaining the order that fails to file a certified copy is subject to appropriate sanctions by a tribunal in which the issue of failure to file arises. The failure to file does not affect the validity or enforceability of the controlling order.

. An order that has been determined to be the controlling order, or a judgment for consolidated arrears of support and interest, if any, made pursuant to this section must be recognized in proceedings under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%208[2015 c 214 § 8]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20207[2002 c 198 § 207]; ]

== 26.21A.135 - Child support orders for two or more obligees.
In responding to registrations or petitions for enforcement of two or more child support orders in effect at the same time with regard to the same obligor and different individual obligees, at least one of which was issued by a tribunal of another state or a foreign country, a tribunal of this state shall enforce those orders in the same manner as if the orders had been issued by a tribunal of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%209[2015 c 214 § 9]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20208[2002 c 198 § 208]; ]

== 26.21A.140 - Credit for payments.
A tribunal of this state shall credit amounts collected for a particular period pursuant to any child support order against the amounts owed for the same period under any other child support order for support of the same child issued by a tribunal of this state, another state, or a foreign country.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2010[2015 c 214 § 10]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20209[2002 c 198 § 209]; ]

== 26.21A.146 - Application of chapter to nonresident subject to personal jurisdiction.
A tribunal of this state exercising personal jurisdiction over a nonresident in a proceeding under this chapter, under other law of this state relating to a support order, or recognizing a foreign support order may receive evidence from outside this state pursuant to RCW 26.21A.275, communicate with a tribunal outside this state pursuant to RCW 26.21A.280, and obtain discovery through a tribunal outside this state pursuant to RCW 26.21A.285. In all other respects, Articles 3 through 6 of this chapter do not apply and the tribunal shall apply the procedural and substantive law of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2043[2015 c 214 § 43]; ]

== 26.21A.150 - Continuing, exclusive jurisdiction to modify spousal support order.
. A tribunal of this state issuing a spousal support order consistent with the law of this state has continuing, exclusive jurisdiction to modify the spousal support order throughout the existence of the support obligation.

. A tribunal of this state may not modify a spousal support order issued by a tribunal of another state or a foreign country having continuing, exclusive jurisdiction over that order under the law of that state or foreign country.

. A tribunal of this state that has continuing, exclusive jurisdiction over a spousal support order may serve as:

.. An initiating tribunal to request a tribunal of another state to enforce the spousal support order issued in this state; or

.. A responding tribunal to enforce or modify its own spousal support order.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2011[2015 c 214 § 11]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20211[2002 c 198 § 211]; ]

== 26.21A.200 - Proceedings under this chapter.
. Except as otherwise provided in this chapter, this article applies to all proceedings under this chapter.

. An individual petitioner or a support enforcement agency may initiate a proceeding authorized under this chapter by filing a petition in an initiating tribunal for forwarding to a responding tribunal or by filing a petition or a comparable pleading directly in a tribunal of another state or a foreign country which has or can obtain personal jurisdiction over the respondent.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2012[2015 c 214 § 12]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20301[2002 c 198 § 301]; ]

== 26.21A.205 - Proceeding by minor parent.
A minor parent, or a guardian or other legal representative of a minor parent, may maintain a proceeding on behalf of or for the benefit of the minor's child.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20302[2002 c 198 § 302]; ]

== 26.21A.210 - Application of law of this state.
Except as otherwise provided by this chapter, a responding tribunal of this state shall:

. Apply the procedural and substantive law generally applicable to similar proceedings originating in this state and may exercise all powers and provide all remedies available in those proceedings; and

. Determine the duty of support and the amount payable in accordance with the law and support guidelines of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20303[2002 c 198 § 303]; ]

== 26.21A.215 - Duties of initiating tribunal.
. Upon the filing of a petition authorized by this chapter, an initiating tribunal of this state shall forward the petition and its accompanying documents:

.. To the responding tribunal or appropriate support enforcement agency in the responding state; or

.. If the identity of the responding tribunal is unknown, to the state information agency of the responding state with a request that they be forwarded to the appropriate tribunal and that receipt be acknowledged.

. If requested by the responding tribunal, a tribunal of this state shall issue a certificate or other document and make findings required by the law of the responding state. If the responding tribunal is in a foreign country, upon request the tribunal of this state shall specify the amount of support sought, convert that amount into the equivalent amount in the foreign currency under applicable official or market exchange rate as publicly reported, and provide any other documents necessary to satisfy the requirements of the responding foreign tribunal.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2013[2015 c 214 § 13]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20304[2002 c 198 § 304]; ]

== 26.21A.220 - Duties and powers of responding tribunal.
. When a responding tribunal of this state receives a petition or comparable pleading from an initiating tribunal or directly pursuant to RCW 26.21A.200(2), it shall cause the petition or pleading to be filed and notify the petitioner where and when it was filed.

. A responding tribunal of this state, to the extent not prohibited by other law, may do one or more of the following:

.. Establish or enforce a support order, modify a child support order, determine the controlling child support order, or determine parentage of a child;

.. Order an obligor to comply with a support order, specifying the amount and the manner of compliance;

.. Order income withholding;

.. Determine the amount of any arrearages, and specify a method of payment;

.. Enforce orders by civil or criminal contempt, or both;

.. Set aside property for satisfaction of the support order;

.. Place liens and order execution on the obligor's property;

.. Order an obligor to keep the tribunal informed of the obligor's current residential address, email address, telephone number, employer, address of employment, and telephone number at the place of employment;

.. Issue a bench warrant for an obligor who has failed after proper notice to appear at a hearing ordered by the tribunal and enter the bench warrant in any local and state computer systems for criminal warrants;

.. Order the obligor to seek appropriate employment by specified methods;

.. Award reasonable attorneys' fees and other fees and costs; and

.. Grant any other available remedy.

. A responding tribunal of this state shall include in a support order issued under this chapter, or in the documents accompanying the order, the calculations on which the support order is based.

. A responding tribunal of this state may not condition the payment of a support order issued under this chapter upon compliance by a party with provisions for visitation.

. If a responding tribunal of this state issues an order under this chapter, the tribunal shall send a copy of the order to the petitioner and the respondent and to the initiating tribunal, if any.

. If requested to enforce a support order, arrears, or judgment or modify a support order stated in a foreign currency, a responding tribunal of this state shall convert the amount stated in the foreign currency to the equivalent amount in dollars under the applicable official or market exchange rate as publicly reported.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2014[2015 c 214 § 14]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20305[2002 c 198 § 305]; ]

== 26.21A.225 - Inappropriate tribunal.
If a petition or comparable pleading is received by an inappropriate tribunal of this state, the tribunal shall forward the pleading and accompanying documents to an appropriate tribunal of this state or another state and notify the petitioner where and when the pleading was sent.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2015[2015 c 214 § 15]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20306[2002 c 198 § 306]; ]

== 26.21A.230 - Duties of support enforcement agency.
. A support enforcement agency of this state, upon request, shall provide services to a petitioner in a proceeding under this chapter.

. A support enforcement agency of this state that is providing services to the petitioner shall:

.. Take all steps necessary to enable an appropriate tribunal of this state, another state, or a foreign country to obtain jurisdiction over the respondent;

.. Request an appropriate tribunal to set a date, time, and place for a hearing;

.. Make a reasonable effort to obtain all relevant information, including information as to income and property of the parties;

.. Within two days, exclusive of Saturdays, Sundays, and legal holidays, after receipt of a written notice in a record from an initiating, responding, or registering tribunal, send a copy of the notice to the petitioner;

.. Within two days, exclusive of Saturdays, Sundays, and legal holidays, after receipt of a written communication in a record from the respondent or the respondent's attorney, send a copy of the communication to the petitioner; and

.. Notify the petitioner if jurisdiction over the respondent cannot be obtained.

. A support enforcement agency of this state that requests registration of a child support order in this state for enforcement or for modification shall make reasonable efforts:

.. To ensure that the order to be registered is the controlling order; or

.. If two or more child support orders exist and the identity of the controlling order has not been determined, to ensure that a request for such a determination is made in a tribunal having jurisdiction to do so.

. A support enforcement agency of this state that requests registration and enforcement of a support order, arrears, or judgment stated in a foreign currency shall convert the amounts stated in the foreign currency into the equivalent amounts in dollars under the applicable official or market exchange rate as publicly reported.

. A support enforcement agency of this state shall issue or request a tribunal of this state to issue a child support order and an income-withholding order that redirect payment of current support, arrears, and interest if requested to do so by a support enforcement agency of another state pursuant to RCW 26.21A.290.

. This chapter does not create or negate a relationship of attorney and client or other fiduciary relationship between a support enforcement agency or the attorney for the agency and the individual being assisted by the agency.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2016[2015 c 214 § 16]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20307[2002 c 198 § 307]; ]

== 26.21A.235 - Duty of state official or agency.
. If the appropriate state official or agency determines that the support enforcement agency is neglecting or refusing to provide services to an individual, the state official or agency may order the agency to perform its duties under this chapter or may provide those services directly to the individual.

. The appropriate state official or agency may determine that a foreign country has established a reciprocal arrangement for child support with this state and take appropriate action for notification of the determination.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2017[2015 c 214 § 17]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20308[2002 c 198 § 308]; ]

== 26.21A.240 - Private counsel.
An individual may employ private counsel to represent the individual in proceedings authorized by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20309[2002 c 198 § 309]; ]

== 26.21A.245 - Duties of state information agency.
. The Washington state support registry under chapter 26.23 RCW is the state information agency under this chapter.

. The state information agency shall:

.. Compile and maintain a current list, including addresses, of the tribunals in this state which have jurisdiction under this chapter and any support enforcement agencies in this state and transmit a copy to the state information agency of every other state;

.. Maintain a register of names and addresses of tribunals and support enforcement agencies received from other states;

.. Forward to the appropriate tribunal in the county in this state in which the obligee who is an individual or the obligor resides, or in which the obligor's property is believed to be located, all documents concerning a proceeding under this chapter received from another state or a foreign country; and

.. Obtain information concerning the location of the obligor and the obligor's property within this state not exempt from execution, by such means as postal verification and federal or state locator services, examination of telephone directories, requests for the obligor's address from employers, and examination of governmental records, including, to the extent not prohibited by other law, those relating to real property, vital statistics, law enforcement, taxation, motor vehicles, driver's licenses, and social security.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2018[2015 c 214 § 18]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20310[2002 c 198 § 310]; ]

== 26.21A.250 - Pleadings and accompanying documents.
. In a proceeding under this chapter, a petitioner seeking to establish a support order, to determine parentage of a child, or to register and modify a support order of a tribunal of another state or a foreign country must file a petition. Unless otherwise ordered under RCW 26.21A.255, the petition or accompanying documents must provide, so far as known, the name, residential address, and social security numbers of the obligor and the obligee or the parent and alleged parent, and the name, sex, residential address, social security number, and date of birth of each child for whose benefit support is sought or whose parentage is to be determined. Unless filed at the time of registration, the petition must be accompanied by a copy of any support order known to have been issued by another tribunal. The petition may include any other information that may assist in locating or identifying the respondent.

. The petition must specify the relief sought. The petition and accompanying documents must conform substantially with the requirements imposed by the forms mandated by federal law for use in cases filed by a support enforcement agency.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2019[2015 c 214 § 19]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20311[2002 c 198 § 311]; ]

== 26.21A.255 - Nondisclosure of information in exceptional circumstances.
If a party alleges in an affidavit or a pleading under oath that the health, safety, or liberty of a party or child would be jeopardized by disclosure of specific identifying information, that information must be sealed and may not be disclosed to the other party or the public. After a hearing in which a tribunal takes into consideration the health, safety, or liberty of the party or child, the tribunal may order disclosure of information that the tribunal determines to be in the interest of justice.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20312[2002 c 198 § 312]; ]

== 26.21A.260 - Costs and fees.
. The petitioner may not be required to pay a filing fee or other costs.

. If an obligee prevails, a responding tribunal of this state may assess against an obligor filing fees, reasonable attorneys' fees, other costs, and necessary travel and other reasonable expenses incurred by the obligee and the obligee's witnesses. The tribunal may not assess fees, costs, or expenses against the obligee or the support enforcement agency of either the initiating or responding state or foreign country, except as provided by other law. Attorneys' fees may be taxed as costs, and may be ordered paid directly to the attorney, who may enforce the order in the attorney's own name. Payment of support owed to the obligee has priority over fees, costs, and expenses.

. The tribunal shall order the payment of costs and reasonable attorneys' fees if it determines that a hearing was requested primarily for delay. In a proceeding under Article 6 of this chapter, a hearing is presumed to have been requested primarily for delay if a registered support order is confirmed or enforced without change.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2020[2015 c 214 § 20]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20313[2002 c 198 § 313]; ]

== 26.21A.265 - Limited immunity of petitioner.
. Participation by a petitioner in a proceeding under this chapter before a responding tribunal, whether in person, by private attorney, or through services provided by the support enforcement agency, does not confer personal jurisdiction over the petitioner in another proceeding.

. A petitioner is not amenable to service of civil process while physically present in this state to participate in a proceeding under this chapter.

. The immunity granted by this section does not extend to civil litigation based on acts unrelated to a proceeding under this chapter committed by a party while physically present in this state to participate in the proceeding.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20314[2002 c 198 § 314]; ]

== 26.21A.270 - Nonparentage as defense.
A party whose parentage of a child has been previously determined by or pursuant to law may not plead nonparentage as a defense to a proceeding under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20315[2002 c 198 § 315]; ]

== 26.21A.275 - Special rules of evidence and procedure.
. The physical presence of a nonresident party who is an individual in a tribunal of this state is not required for the establishment, enforcement, or modification of a support order or the rendition of a judgment determining parentage of a child.

. An affidavit, a document substantially complying with federally mandated forms, or a document incorporated by reference in any of them, which would not be excluded under the hearsay rule if given in person, is admissible in evidence if given under penalty of perjury by a party or witness residing outside this state.

. A copy of the record of child support payments certified as a true copy of the original by the custodian of the record may be forwarded to a responding tribunal. The copy is evidence of facts asserted in it, and is admissible to show whether payments were made.

. Copies of bills for testing for parentage of a child, and for prenatal and postnatal health care of the mother and child, furnished to the adverse party at least ten days before trial, are admissible in evidence to prove the amount of the charges billed and that the charges were reasonable, necessary, and customary.

. Documentary evidence transmitted from outside this state to a tribunal of this state by telephone, telecopier, or other electronic means that do not provide an original record may not be excluded from evidence on an objection based on the means of transmission.

. In a proceeding under this chapter, a tribunal of this state shall permit a party or witness residing outside this state to be deposed or to testify under penalty of perjury by telephone, audiovisual means, or other electronic means at a designated tribunal or other location. A tribunal of this state shall cooperate with other tribunals in designating an appropriate location for the deposition or testimony.

. If a party called to testify at a civil hearing refuses to answer on the ground that the testimony may be self-incriminating, the trier of fact may draw an adverse inference from the refusal.

. A privilege against disclosure of communications between spouses does not apply in a proceeding under this chapter.

. The defense of immunity based on the relationship of husband and wife or parent and child does not apply in a proceeding under this chapter.

. A voluntary acknowledgment of paternity, certified as a true copy, is admissible to establish parentage of the child.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2021[2015 c 214 § 21]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20316[2002 c 198 § 316]; ]

== 26.21A.280 - Communications between tribunals.
A tribunal of this state may communicate with a tribunal outside this state in a record, or by telephone, email, or other means, to obtain information concerning the laws, the legal effect of a judgment, decree, or order of that tribunal, and the status of a proceeding. A tribunal of this state may furnish similar information by similar means to a tribunal outside this state.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2022[2015 c 214 § 22]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20317[2002 c 198 § 317]; ]

== 26.21A.285 - Assistance with discovery.
A tribunal of this state may:

. Request a tribunal outside this state to assist in obtaining discovery; and

. Upon request, compel a person over which it has jurisdiction to respond to a discovery order issued by a tribunal outside this state.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2023[2015 c 214 § 23]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20318[2002 c 198 § 318]; ]

== 26.21A.290 - Receipt and disbursement of payments.
. A support enforcement agency or tribunal of this state shall disburse promptly any amounts received pursuant to a support order, as directed by the order. The agency or tribunal shall furnish to a requesting party or tribunal of another state or a foreign country a certified statement by the custodian of the record of the amounts and dates of all payments received.

. If neither the obligor, nor the obligee who is an individual, nor the child resides in this state, upon request from the support enforcement agency of this state or another state, the support enforcement agency of this state or a tribunal of this state shall:

.. Direct that the support payment be made to the support enforcement agency in the state in which the obligee is receiving services; and

.. Issue and send to the obligor's employer a conforming income-withholding order or an administrative notice of change of payee, reflecting the redirected payments.

. The support enforcement agency of this state receiving redirected payments from another state pursuant to a law similar to subsection (2) of this section shall furnish to a requesting party or tribunal of the other state a certified statement by the custodian of the record of the amount and dates of all payments received.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2024[2015 c 214 § 24]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20319[2002 c 198 § 319]; ]

== 26.21A.350 - Establishment of support order.
. If a support order entitled to recognition under this chapter has not been issued, a responding tribunal of this state with personal jurisdiction over the parties may issue a support order if:

.. The individual seeking the order resides outside this state; or

.. The support enforcement agency seeking the order is located outside this state.

. The tribunal may issue a temporary child support order if the tribunal determines that such an order is appropriate and the individual ordered to pay is:

.. A presumed father of the child;

.. Petitioning to have his paternity adjudicated;

.. Identified as the father of the child through genetic testing;

.. An alleged father who has declined to submit to genetic testing;

.. Shown by clear and convincing evidence to be the father of the child;

.. An acknowledged father as provided by applicable state law;

.. The mother of the child; or

.. An individual who has been ordered to pay child support in a previous proceeding and the order has not been reversed or vacated.

. Upon finding, after notice and opportunity to be heard, that an obligor owes a duty of support, the tribunal shall issue a support order directed to the obligor and may issue other orders pursuant to RCW 26.21A.220.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2025[2015 c 214 § 25]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20401[2002 c 198 § 401]; ]

== 26.21A.355 - Proceeding to determine parentage.
A tribunal of this state authorized to determine parentage of a child may serve as a responding tribunal in a proceeding to determine parentage of a child brought under this chapter or a law or procedure substantially similar to this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2044[2015 c 214 § 44]; ]

== 26.21A.400 - Employer's receipt of income-withholding order of another state.
An income-withholding order issued in another state may be sent by or on behalf of the obligee, or by the support enforcement agency, to the person defined as the obligor's employer under RCW 50.04.080 without first filing a petition or comparable pleading or registering the order with a tribunal of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20501[2002 c 198 § 501]; ]

== 26.21A.405 - Employer's compliance with income-withholding order of another state.
. Upon receipt of an income-withholding order, the obligor's employer shall immediately provide a copy of the order to the obligor.

. The employer shall treat an income-withholding order issued in another state that appears regular on its face as if it had been issued by a tribunal of this state.

. Except as provided in subsection (4) of this section and RCW 26.21A.410, the employer shall withhold and distribute the funds as directed in the withholding order by complying with terms of the order which specify:

.. The duration and amount of periodic payments of current child support, stated as a sum certain;

.. The person designated to receive payments and the address to which the payments are to be forwarded;

.. Medical support, whether in the form of periodic cash payment, stated as a sum certain, or ordering the obligor to provide health insurance coverage for the child under a policy available through the obligor's employment;

.. The amount of periodic payments of fees and costs for a support enforcement agency, the issuing tribunal, and the obligee's attorney, stated as sums certain; and

.. The amount of periodic payments of arrearages and interest on arrearages, stated as sums certain.

. An employer shall comply with the law of the state of the obligor's principal place of employment for withholding from income with respect to:

.. The employer's fee for processing an income-withholding order;

.. The maximum amount permitted to be withheld from the obligor's income; and

.. The times within which the employer must implement the withholding order and forward the child support payment.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20502[2002 c 198 § 502]; ]

== 26.21A.410 - Employer's compliance with two or more income-withholding orders.
If an obligor's employer receives two or more income-withholding orders with respect to the earnings of the same obligor, the employer satisfies the terms of the orders if the employer complies with the law of the state of the obligor's principal place of employment to establish the priorities for withholding and allocating income withheld for two or more child support obligees.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20503[2002 c 198 § 503]; ]

== 26.21A.415 - Immunity from civil liability.
An employer that complies with an income-withholding order issued in another state in accordance with this article is not subject to civil liability to an individual or agency with regard to the employer's withholding of child support from the obligor's income.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2026[2015 c 214 § 26]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20504[2002 c 198 § 504]; ]

== 26.21A.420 - Penalties for noncompliance.
An employer that willfully fails to comply with an income-withholding order issued in another state and received for enforcement is subject to the same penalties that may be imposed for noncompliance with an order issued by a tribunal of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2027[2015 c 214 § 27]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20505[2002 c 198 § 505]; ]

== 26.21A.425 - Contest by obligor.
. An obligor may contest the validity or enforcement of an income-withholding order issued in another state and received directly by an employer in this state by registering the order in a tribunal of this state and filing a contest to that order as provided in Article 6 of this chapter, or otherwise contesting the order in the same manner as if the order had been issued by a tribunal of this state. RCW 26.21A.515 applies to the contest.

. The obligor shall give notice of the contest to:

.. A support enforcement agency providing services to the obligee;

.. Each employer that has directly received an income-withholding order relating to the obligor; and

.. The person designated to receive payments in the income-withholding order or, if no person or agency is designated, to the obligee.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20506[2002 c 198 § 506]; ]

== 26.21A.430 - Administrative enforcement of orders.
. A party or support enforcement agency seeking to enforce a support order or an income-withholding order, or both, issued in another state or a foreign support order may send the documents required for registering the order to a support enforcement agency of this state.

. Upon receipt of the documents, the support enforcement agency, without initially seeking to register the order, shall consider and, if appropriate, use any administrative procedure authorized by the law of this state to enforce a support order or an income-withholding order, or both. If the obligor does not contest administrative enforcement, the order need not be registered. If the obligor contests the validity or administrative enforcement of the order, the support enforcement agency shall register the order pursuant to this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2028[2015 c 214 § 28]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20507[2002 c 198 § 507]; ]

== 26.21A.500 - Registration of order for enforcement.
A support order or income-withholding order issued in another state or a foreign support order may be registered in this state for enforcement.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2029[2015 c 214 § 29]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20601[2002 c 198 § 601]; ]

== 26.21A.505 - Procedure to register order for enforcement.
. Except as otherwise provided in RCW 26.21A.613, a support order or income-withholding order of another state or a foreign support order may be registered in this state by sending the following records to the appropriate tribunal in this state:

.. A letter of transmittal to the tribunal requesting registration and enforcement;

.. Two copies, including one certified copy, of the order to be registered, including any modification of the order;

.. A sworn statement by the person requesting registration or a certified statement by the custodian of the records showing the amount of any arrearage;

.. The name of the obligor and, if known:

... The obligor's address and social security number;

... The name and address of the obligor's employer and any other source of income of the obligor; and

... A description and the location of property of the obligor in this state not exempt from execution; and

.. Except as otherwise provided in RCW 26.21A.255, the name and address of the obligee and, if applicable, the person to whom support payments are to be remitted.

. On receipt of a request for registration, the registering tribunal shall cause the order to be filed as an order of a tribunal of another state or a foreign support order, together with one copy of the documents and information, regardless of their form.

. A petition or comparable pleading seeking a remedy that must be affirmatively sought under other law of this state may be filed at the same time as the request for registration or later. The pleading must specify the grounds for the remedy sought.

. If two or more orders are in effect, the person requesting registration shall:

.. Furnish to the tribunal a copy of every support order asserted to be in effect in addition to the documents specified in this section;

.. Specify the order alleged to be the controlling order, if any; and

.. Specify the amount of consolidated arrears, if any.

. A request for a determination of which is the controlling order may be filed separately or with a request for registration and enforcement or for registration and modification. The person requesting registration shall give notice of the request to each party whose rights may be affected by the determination.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2030[2015 c 214 § 30]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20602[2002 c 198 § 602]; ]

== 26.21A.510 - Effect of registration for enforcement.
. A support order or income-withholding order issued in another state or a foreign support order is registered when the order is filed in the registering tribunal of this state.

. A registered support order issued in another state or a foreign country is enforceable in the same manner and is subject to the same procedures as an order issued by a tribunal of this state.

. Except as otherwise provided in this chapter, a tribunal of this state shall recognize and enforce, but may not modify, a registered support order if the issuing tribunal had jurisdiction.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2031[2015 c 214 § 31]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20603[2002 c 198 § 603]; ]

== 26.21A.515 - Choice of law.
. Except as otherwise provided in subsection (4) of this section, the law of the issuing state or foreign country governs:

.. The nature, extent, amount, and duration of current payments under a registered support order;

.. The computation and payment of arrearages and accrual of interest on the arrearages under the support order; and

.. The existence and satisfaction of other obligations under the support order.

. In a proceeding for arrears under a registered support order, the statute of limitation of this state or of the issuing state or foreign country, whichever is longer, applies.

. A responding tribunal of this state shall apply the procedures and remedies of this state to enforce current support and collect arrears and interest due on a support order of another state or foreign country registered in this state.

. After a tribunal of this or another state determines which is the controlling order and issues an order consolidating arrears, if any, a tribunal of this state shall prospectively apply the law of the state or foreign country issuing the controlling order, including its law on interest on arrears, on current and future support, and on consolidated arrears.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2032[2015 c 214 § 32]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20604[2002 c 198 § 604]; ]

== 26.21A.520 - Notice of registration of order.
. When a support order or income-withholding order issued in another state or a foreign support order is registered, the registering tribunal of this state shall notify the nonregistering party. The notice must be accompanied by a copy of the registered order and the documents and relevant information accompanying the order.

. A notice must inform the nonregistering party:

.. That a registered order is enforceable as of the date of registration in the same manner as an order issued by a tribunal of this state;

.. That a hearing to contest the validity or enforcement of the registered order must be requested within twenty days after notice unless the registered order is under RCW 26.21A.615;

.. That failure to contest the validity or enforcement of the registered order in a timely manner will result in confirmation of the order and enforcement of the order and the alleged arrearages; and

.. Of the amount of any alleged arrearages.

. If the registering party asserts that two or more orders are in effect, a notice must also:

.. Identify the two or more orders and the order alleged by the registering party to be the controlling order and the consolidated arrears, if any;

.. Notify the nonregistering party of the right to a determination of which is the controlling order;

.. State that the procedures provided in subsection (2) of this section apply to the determination of which is the controlling order; and

.. State that failure to contest the validity or enforcement of the order alleged to be the controlling order in a timely manner may result in confirmation that the order is the controlling order.

. Upon registration of an income-withholding order for enforcement, the support enforcement agency or the registering tribunal shall notify the obligor's employer pursuant to the income-withholding law of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2033[2015 c 214 § 33]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20605[2002 c 198 § 605]; ]

== 26.21A.525 - Procedure to contest validity or enforcement of registered support order.
. A nonregistering party seeking to contest the validity or enforcement of a registered support order in this state shall request a hearing within the time required by RCW 26.21A.520. The nonregistering party may seek to vacate the registration, to assert any defense to an allegation of noncompliance with the registered order, or to contest the remedies being sought or the amount of any alleged arrearages pursuant to RCW 26.21A.530.

. If the nonregistering party fails to contest the validity or enforcement of the registered order in a timely manner, the order is confirmed by operation of law.

. If a nonregistering party requests a hearing to contest the validity or enforcement of the registered order, the registering tribunal shall schedule the matter for hearing and give notice to the parties of the date, time, and place of the hearing.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2034[2015 c 214 § 34]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20606[2002 c 198 § 606]; ]

== 26.21A.530 - Contest of registration or enforcement.
. A party contesting the validity or enforcement of a registered support order or seeking to vacate the registration has the burden of proving one or more of the following defenses:

.. The issuing tribunal lacked personal jurisdiction over the contesting party;

.. The order was obtained by fraud;

.. The order has been vacated, suspended, or modified by a later order;

.. The issuing tribunal has stayed the order pending appeal;

.. There is a defense under the law of this state to the remedy sought;

.. Full or partial payment has been made;

.. The statute of limitation under RCW 26.21A.515 precludes enforcement of some or all of the alleged arrearages; or

.. The alleged controlling order is not the controlling order.

. If a party presents evidence establishing a full or partial defense under subsection (1) of this section, a tribunal may stay enforcement of a registered support order, continue the proceeding to permit production of additional relevant evidence, and issue other appropriate orders. An uncontested portion of the registered support order may be enforced by all remedies available under the law of this state.

. If the contesting party does not establish a defense under subsection (1) of this section to the validity or enforcement of a registered support order, the registering tribunal shall issue an order confirming the order.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2035[2015 c 214 § 35]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20607[2002 c 198 § 607]; ]

== 26.21A.535 - Confirmed order.
Confirmation of a registered support order, whether by operation of law or after notice and hearing, precludes further contest of the order with respect to any matter that could have been asserted at the time of registration.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2036[2015 c 214 § 36]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20608[2002 c 198 § 608]; ]

== 26.21A.540 - Procedure to register child support order of another state for modification.
A party or support enforcement agency seeking to modify, or to modify and enforce, a child support order issued in another state shall register that order in this state in the same manner provided in RCW 26.21A.500 through 26.21A.535 if the order has not been registered. A petition for modification may be filed at the same time as a request for registration, or later. The pleading must specify the grounds for modification.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2037[2015 c 214 § 37]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20609[2002 c 198 § 609]; ]

== 26.21A.545 - Effect of registration for modification.
A tribunal of this state may enforce a child support order of another state registered for purposes of modification, in the same manner as if the order had been issued by a tribunal of this state, but the registered support order may be modified only if the requirements of RCW 26.21A.550 or 26.21A.560 have been met.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2038[2015 c 214 § 38]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20610[2002 c 198 § 610]; ]

== 26.21A.550 - Modification of child support order of another state.
. If RCW 26.21A.560 does not apply, upon petition a tribunal of this state may modify a child support order issued in another state which is registered in this state if, after notice and hearing the tribunal finds that:

.. The following requirements are met:

... Neither the child, nor the obligee who is an individual, nor the obligor resides in the issuing state;

... A petitioner who is a nonresident of this state seeks modification; and

... The respondent is subject to the personal jurisdiction of the tribunal of this state; or

.. This state is the residence of the child, or a party who is an individual is subject to the personal jurisdiction of the tribunal of this state, and all of the parties who are individuals have filed consents in a record in the issuing tribunal for a tribunal of this state to modify the support order and assume continuing, exclusive jurisdiction.

. Modification of a registered child support order is subject to the same requirements, procedures, and defenses that apply to the modification of an order issued by a tribunal of this state and the order may be enforced and satisfied in the same manner.

. A tribunal of this state may not modify any aspect of a child support order that may not be modified under the law of the issuing state, including the duration of the obligation of support. If two or more tribunals have issued child support orders for the same obligor and same child, the order that controls and must be so recognized under RCW 26.21A.130 establishes the aspects of the support order which are nonmodifiable.

. In a proceeding to modify a child support order, the law of the state that is determined to have issued the initial controlling order governs the duration of the obligation of support. The obligor's fulfillment of the duty of support established by that order precludes imposition of a further obligation of support by a tribunal of this state.

. On the issuance of an order by a tribunal of this state modifying a child support order issued in another state, the tribunal of this state becomes the tribunal having continuing, exclusive jurisdiction.

. Notwithstanding subsections (1) through (5) of this section and RCW 26.21A.100(2), a tribunal of this state retains jurisdiction to modify an order issued by a tribunal of this state if:

.. One party resides in another state; and

.. The other party resides outside the United States.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2039[2015 c 214 § 39]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20611[2002 c 198 § 611]; ]

== 26.21A.555 - Recognition of order modified in another state.
If a child support order issued by a tribunal of this state is modified by a tribunal of another state that assumed jurisdiction pursuant to the uniform interstate family support act, a tribunal of this state:

. May enforce its order that was modified only as to arrears and interest accruing before the modification;

. May provide other appropriate relief for violations of its order which occurred before the effective date of the modification; and

. Shall recognize the modifying order of the other state, upon registration, for the purpose of enforcement.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20612[2002 c 198 § 612]; ]

== 26.21A.560 - Jurisdiction to modify child support order of another state when individual parties reside in this state.
. If all of the parties who are individuals reside in this state and the child does not reside in the issuing state, a tribunal of this state has jurisdiction to enforce and to modify the issuing state's child support order in a proceeding to register that order.

. A tribunal of this state exercising jurisdiction under this section shall apply the provisions of Articles 1 and 2 of this chapter, this article, and the procedural and substantive law of this state to the proceeding for enforcement or modification. Articles 3, 4, 5, 7, and 8 of this chapter do not apply.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20613[2002 c 198 § 613]; ]

== 26.21A.565 - Notice to issuing tribunal of modification.
Within thirty days after issuance of a modified child support order, the party obtaining the modification shall file a certified copy of the order with the issuing tribunal that had continuing, exclusive jurisdiction over the earlier order, and in each tribunal in which the party knows the earlier order has been registered. A party who obtains the order and fails to file a certified copy is subject to appropriate sanctions by a tribunal in which the issue of failure to file arises. The failure to file does not affect the validity or enforceability of the modified order of the new tribunal having continuing, exclusive jurisdiction.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20614[2002 c 198 § 614]; ]

== 26.21A.570 - Jurisdiction to modify child support order of foreign country.
. Except as otherwise provided in RCW 26.21A.625, if a foreign country lacks or refuses to exercise jurisdiction to modify its child support order pursuant to its laws, a tribunal of this state may assume jurisdiction to modify the child support order and bind all individuals subject to the personal jurisdiction of the tribunal whether or not the consent to modification of a child support order otherwise required of the individual pursuant to RCW 26.21A.550 has been given or whether the individual seeking modification is a resident of this state or of the foreign country.

. An order issued by a tribunal of this state modifying a foreign child support order pursuant to this section is the controlling order.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2040[2015 c 214 § 40]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20615[2002 c 198 § 615]; ]

== 26.21A.575 - Procedure to register child support order of foreign country for modification.
A party or support enforcement agency seeking to modify, or to modify and enforce, a foreign child support order not under the convention may register that order in this state under RCW 26.21A.500 through 26.21A.535 if the order has not been registered. A petition for modification may be filed at the same time as a request for registration, or at another time. The petition must specify the grounds for modification.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2045[2015 c 214 § 45]; ]

== 26.21A.601 - Definitions.
In this article:

. "Application" means a request under the convention by an obligee or obligor, or on behalf of a child, made through a central authority for assistance from another central authority.

. "Central authority" means the entity designated by the United States or a foreign country described in RCW 26.21A.010(5)(d) to perform the functions specified in the convention.

. "Convention support order" means a support order of a tribunal of a foreign country described in RCW 26.21A.010(5)(d).

. "Direct request" means a petition filed by an individual in a tribunal of this state in a proceeding involving an obligee, obligor, or child residing outside the United States.

. "Foreign central authority" means the entity designated by a foreign country described in RCW 26.21A.010(5)(d) to perform the functions specified in the convention.

. "Foreign support agreement":

.. Means an agreement for support in a record that:

... Is enforceable as a support order in the country of origin;

... Has been:

(A) Formally drawn up or registered as an authentic instrument by a foreign tribunal; or

(B) Authenticated by or concluded, registered, or filed with a foreign tribunal; and

... May be reviewed and modified by a foreign tribunal; and

.. Includes a maintenance arrangement or authentic instrument under the convention.

. "United States central authority" means the secretary of the United States department of health and human services.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2046[2015 c 214 § 46]; ]

== 26.21A.603 - Applicability.
This article applies only to a support proceeding under the convention. In such a proceeding, if a provision of this article is inconsistent with Articles 1 through 6 of this chapter, this article controls.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2047[2015 c 214 § 47]; ]

== 26.21A.605 - Relationship of department of social and health services to United States central authority.
The department of social and health services of this state is recognized as the agency designated by the United States central authority to perform specific functions under the convention.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2048[2015 c 214 § 48]; ]

== 26.21A.607 - Initiation by department of social and health services of support proceeding under convention.
. In a support proceeding under this article, the department of social and health services of this state shall:

.. Transmit and receive applications; and

.. Initiate or facilitate the institution of a proceeding regarding an application in a tribunal of this state.

. The following support proceedings are available to an obligee under the convention:

.. Recognition or recognition and enforcement of a foreign support order;

.. Enforcement of a support order issued or recognized in this state;

.. Establishment of a support order if there is no existing order including, if necessary, determination of parentage of a child;

.. Establishment of a support order if recognition of a foreign support order is refused under RCW 26.21A.617(2) (b), (d), or (i);

.. Modification of a support order of a tribunal of this state; and

.. Modification of a support order of a tribunal of another state or a foreign country.

. The following support proceedings are available under the convention to an obligor against which there is an existing support order:

.. Recognition of an order suspending or limiting enforcement of an existing support order of a tribunal of this state;

.. Modification of a support order of a tribunal of this state; and

.. Modification of a support order of a tribunal of another state or a foreign country.

. A tribunal of this state may not require security, bond, or deposit, however described, to guarantee the payment of costs and expenses in proceedings under the convention.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2049[2015 c 214 § 49]; ]

== 26.21A.610 - Direct request.
. A petitioner may file a direct request seeking establishment or modification of a support order or determination of parentage of a child. In such a proceeding, the law of this state applies.

. A petitioner may file a direct request seeking recognition and enforcement of a support order or support agreement. In the proceeding, RCW 26.21A.613 through 26.21A.630 apply.

. In a direct request for recognition and enforcement of a convention support order or foreign support agreement:

.. A security, bond, or deposit is not required to guarantee the payment of costs and expenses; and

.. An obligee or obligor that in the issuing country has benefited from free legal assistance is entitled to benefit, at least to the same extent, from any free legal assistance provided for by the law of this state under the same circumstances.

. A petitioner filing a direct request is not entitled to assistance from the department of social and health services.

. This article does not prevent the application of laws of this state that provide simplified, more expeditious rules regarding a direct request for recognition and enforcement of a foreign support order or foreign support agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2050[2015 c 214 § 50]; ]

== 26.21A.613 - Registration of convention support order.
. Except as otherwise provided in this article, a party who is an individual or a support enforcement agency seeking recognition of a convention support order shall register the order in this state as provided in Article 6 of this chapter.

. Notwithstanding RCW 26.21A.250 and 26.21A.505(1), a request for registration of a convention support order must be accompanied by:

.. A complete text of the support order, or an abstract or extract of the support order drawn up by the issuing foreign tribunal, which may be in the form recommended by the Hague conference on private international law;

.. A record stating that the support order is enforceable in the issuing country;

.. If the respondent did not appear and was not represented in the proceedings in the issuing country, a record attesting, as appropriate, either that the respondent had proper notice of the proceedings and an opportunity to be heard or that the respondent had proper notice of the support order and an opportunity to be heard in a challenge or appeal on fact or law before a tribunal;

.. A record showing the amount of arrears, if any, and the date the amount was calculated;

.. A record showing a requirement for automatic adjustment of the amount of support, if any, and the information necessary to make the appropriate calculations; and

.. If necessary, a record showing the extent to which the applicant received free legal assistance in the issuing country.

. A request for registration of a convention support order may seek recognition and partial enforcement of the order.

. A tribunal of this state may vacate the registration of a convention support order without the filing of a contest under RCW 26.21A.615, only if, acting on its own motion, the tribunal finds that recognition and enforcement of the order would be manifestly incompatible with public policy.

. The tribunal shall promptly notify the parties of the registration or the order vacating the registration of a convention support order.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2051[2015 c 214 § 51]; ]

== 26.21A.615 - Contest of registered convention support order.
. Except as otherwise provided in this article, RCW 26.21A.520 through 26.21A.535 apply to a contest of a registered convention support order.

. A party contesting a registered convention support order shall file a contest not later than thirty days after notice of the registration, but if the contesting party does not reside in the United States, the contest must be filed not later than sixty days after notice of the registration.

. If the nonregistering party fails to contest the registered convention support order by the time specified in subsection (2) of this section, the order is enforceable.

. A contest of a registered convention support order may be based only on grounds set forth in RCW 26.21A.617. The contesting party bears the burden of proof.

. In a contest of a registered convention support order, a tribunal of this state:

.. Is bound by the findings of fact on which the foreign tribunal based its jurisdiction; and

.. May not review the merits of the order.

. A tribunal of this state deciding a contest of a registered convention support order shall promptly notify the parties of its decision.

. A challenge or appeal, if any, does not stay the enforcement of a convention support order unless there are exceptional circumstances.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2052[2015 c 214 § 52]; ]

== 26.21A.617 - Recognition and enforcement of registered convention support order.
. Except as otherwise provided in subsection (2) of this section, a tribunal of this state shall recognize and enforce a registered convention support order.

. The following grounds are the only grounds on which a tribunal of this state may refuse recognition and enforcement of a registered convention support order:

.. Recognition and enforcement of the order is manifestly incompatible with public policy, including the failure of the issuing tribunal to observe minimum standards of due process, which include notice and an opportunity to be heard;

.. The issuing tribunal lacked personal jurisdiction consistent with RCW 26.21A.100;

.. The order is not enforceable in the issuing country;

.. The order was obtained by fraud in connection with a matter of procedure;

.. A record transmitted in accordance with RCW 26.21A.613 lacks authenticity or integrity;

.. A proceeding between the same parties and having the same purpose is pending before a tribunal of this state and that proceeding was the first to be filed;

.. The order is incompatible with a more recent support order involving the same parties and having the same purpose if the more recent support order is entitled to recognition and enforcement under this chapter in this state;

.. Payment, to the extent alleged arrears have been paid in whole or in part;

.. In a case in which the respondent neither appeared nor was represented in the proceeding in the issuing foreign country:

... If the law of that country provides for prior notice of proceedings, the respondent did not have proper notice of the proceedings and an opportunity to be heard; or

... If the law of that country does not provide for prior notice of the proceedings, the respondent did not have proper notice of the order and an opportunity to be heard in a challenge or appeal on fact or law before a tribunal; or

.. The order was made in violation of RCW 26.21A.625.

. If a tribunal of this state does not recognize a convention support order under subsection (2)(b), (d), or (i) of this section:

.. The tribunal may not dismiss the proceeding without allowing a reasonable time for a party to request the establishment of a new convention support order; and

.. The department of social and health services shall take all appropriate measures to request a child support order for the obligee if the application for recognition and enforcement was received under RCW 26.21A.607.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2053[2015 c 214 § 53]; ]

== 26.21A.620 - Partial enforcement.
If a tribunal of this state does not recognize and enforce a convention support order in its entirety, it shall enforce any severable part of the order. An application or direct request may seek recognition and partial enforcement of a convention support order.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2054[2015 c 214 § 54]; ]

== 26.21A.623 - Foreign support agreement.
. Except as otherwise provided in subsections (3) and (4) of this section, a tribunal of this state shall recognize and enforce a foreign support agreement registered in this state.

. An application or direct request for recognition and enforcement of a foreign support agreement must be accompanied by:

.. A complete text of the foreign support agreement; and

.. A record stating that the foreign support agreement is enforceable as an order of support in the issuing country.

. A tribunal of this state may vacate the registration of a foreign support agreement only if, acting on its own motion, the tribunal finds that recognition and enforcement would be manifestly incompatible with public policy.

. In a contest of a foreign support agreement, a tribunal of this state may refuse recognition and enforcement of the agreement if it finds:

.. Recognition and enforcement of the agreement is manifestly incompatible with public policy;

.. The agreement was obtained by fraud or falsification;

.. The agreement is incompatible with a support order involving the same parties and having the same purpose in this state, another state, or a foreign country if the support order is entitled to recognition and enforcement under this chapter in this state; or

.. The record submitted under subsection (2) of this section lacks authenticity or integrity.

. A proceeding for recognition and enforcement of a foreign support agreement must be suspended during the pendency of a challenge to or appeal of the agreement before a tribunal of another state or a foreign country.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2055[2015 c 214 § 55]; ]

== 26.21A.625 - Modification of convention child support order.
. A tribunal of this state may not modify a convention child support order if the obligee remains a resident of the foreign country where the support order was issued unless:

.. The obligee submits to the jurisdiction of a tribunal of this state, either expressly or by defending on the merits of the case without objecting to the jurisdiction at the first available opportunity; or

.. The foreign tribunal lacks or refuses to exercise jurisdiction to modify its support order or issue a new support order.

. If a tribunal of this state does not modify a convention child support order because the order is not recognized in this state, RCW 26.21A.617(3) applies.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2056[2015 c 214 § 56]; ]

== 26.21A.627 - Personal information—Limit on use.
Personal information gathered or transmitted under this article may be used only for the purposes for which it was gathered or transmitted.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2057[2015 c 214 § 57]; ]

== 26.21A.630 - Record in original language—English translation.
A record filed with a tribunal of this state under this article must be in the original language and, if not in English, must be accompanied by an English translation.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2058[2015 c 214 § 58]; ]

== 26.21A.650 - Grounds for rendition.
. For purposes of this article, "governor" includes an individual performing the functions of governor or the executive authority of a state covered by this chapter.

. The governor of this state may:

.. Demand that the governor of another state surrender an individual found in the other state who is charged criminally in this state with having failed to provide for the support of an obligee; or

.. On the demand by the governor of another state, surrender an individual found in this state who is charged criminally in the other state with having failed to provide for the support of an obligee.

. A provision for extradition of individuals not inconsistent with this chapter applies to the demand even if the individual whose surrender is demanded was not in the demanding state when the crime was allegedly committed and has not fled from the demanding state.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20801[2002 c 198 § 801]; ]

== 26.21A.655 - Conditions of rendition.
. Before making a demand that the governor of another state surrender an individual charged criminally in this state with having failed to provide for the support of an obligee, the governor of this state may require a prosecutor of this state to demonstrate that at least sixty days previously the obligee had initiated proceedings for support pursuant to this chapter or that the proceeding would be of no avail.

. If, under this chapter or a law substantially similar to this chapter, the governor of another state makes a demand that the governor of this state surrender an individual charged criminally in that state with having failed to provide for the support of a child or other individual to whom a duty of support is owed, the governor may require a prosecutor to investigate the demand and report whether a proceeding for support has been initiated or would be effective. If it appears that a proceeding would be effective but has not been initiated, the governor may delay honoring the demand for a reasonable time to permit the initiation of a proceeding.

. If a proceeding for support has been initiated and the individual whose rendition is demanded prevails, the governor may decline to honor the demand. If the petitioner prevails and the individual whose rendition is demanded is subject to a support order, the governor may decline to honor the demand if the individual is complying with the support order.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20802[2002 c 198 § 802]; ]

== 26.21A.900 - Effective date—2002 c 198.
This act takes effect January 1, 2007.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3048.SL.pdf?cite=2006%20c%2096%20§%201[2006 c 96 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20906[2002 c 198 § 906]; ]

== 26.21A.905 - Uniformity of application and construction.
In applying and construing this chapter, consideration must be given to the need to promote uniformity of the law with respect to its subject matter among states that enact it.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20903[2002 c 198 § 903]; ]

== 26.21A.907 - Transitional provision.
This act applies to proceedings begun on or after July 1, 2015, to establish a support order or determine parentage of a child or to register, recognize, enforce, or modify a prior support order, determination, or agreement, whenever issued or entered.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5498-S.SL.pdf?cite=2015%20c%20214%20§%2060[2015 c 214 § 60]; ]

== 26.21A.915 - Captions, part headings, and articles not part of law—2002 c 198.
Captions, part headings, and articles used in this act are not any part of the law.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2347-S.SL.pdf?cite=2002%20c%20198%20§%20902[2002 c 198 § 902]; ]

