= 26.55 - Uniform recognition and enforcement of Canadian domestic violence protection orders act.
:toc:

== 26.55.005 - Short title.
This chapter may be cited as the uniform recognition and enforcement of Canadian domestic violence protection orders act.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1517-S2.SL.pdf?cite=2019%20c%20263%20§%20901[2019 c 263 § 901]; ]

== 26.55.010 - Definitions. (Effective until July 1, 2022.)
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Canadian domestic violence protection order" means a judgment or part of a judgment or order issued in a civil proceeding by a court of Canada under law of the issuing jurisdiction which relates to domestic violence and prohibits a respondent from:

.. Being in physical proximity to a protected individual or following a protected individual;

.. Directly or indirectly contacting or communicating with a protected individual or other individual described in the order;

.. Being within a certain distance of a specified place or location associated with a protected individual; or

.. Molesting, annoying, harassing, or engaging in threatening conduct directed at a protected individual.

. "Domestic protection order" means an injunction or other order issued by a tribunal which relates to domestic or family violence laws to prevent an individual from engaging in violent or threatening acts against, harassment of, direct or indirect contact or communication with, or being in physical proximity to another individual.

. "Issuing court" means the court that issues a Canadian domestic violence protection order.

. "Law enforcement officer" means an individual authorized by law of this state other than this chapter to enforce a domestic protection order.

. "Person" means an individual, estate, business or nonprofit entity, public corporation, government or governmental subdivision, agency, or instrumentality, or other legal entity.

. "Protected individual" means an individual protected by a Canadian domestic violence protection order.

. "Record" means information that is inscribed on a tangible medium or that is stored in an electronic or other medium and is retrievable in perceivable form.

. "Respondent" means an individual against whom a Canadian domestic violence protection order is issued.

. "State" means a state of the United States, the District of Columbia, Puerto Rico, the United States Virgin Islands, or any territory or insular possession subject to the jurisdiction of the United States. The term includes a federally recognized Indian tribe.

. "Tribunal" means a court, agency, or other entity authorized by law of this state other than this chapter to establish, enforce, or modify a domestic protection order.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1517-S2.SL.pdf?cite=2019%20c%20263%20§%20902[2019 c 263 § 902]; ]

== 26.55.015 - Enforceability—Evidence—Extent—Filing not required. (Effective July 1, 2022.)
. A Canadian domestic violence protection order that identifies both a protected individual and a respondent and appears valid on its face is prima facie evidence of its enforceability under chapter 215, Laws of 2021.

. A Canadian domestic violence protection order is enforceable only to the extent it prohibits a respondent from the following conduct as ordered by a Canadian court:

.. Being in physical proximity to a protected individual or following a protected individual;

.. Directly or indirectly contacting or communicating with a protected individual or other individual described in the order;

.. Being within a certain distance of a specified place or location associated with a protected individual; or

.. Molesting, annoying, harassing, or engaging in threatening conduct directed at a protected individual.

. Neither filing with the clerk of the court under RCW 26.55.040 nor obtaining an order granting recognition and enforcement under RCW 26.55.030 is required prior to the enforcement of a Canadian domestic violence protection order by a law enforcement officer.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1320-S2.SL.pdf?cite=2021%20c%20215%20§%2080[2021 c 215 § 80]; ]

== 26.55.020 - Enforcement of Canadian domestic violence protection order by law enforcement officer. (Effective until July 1, 2022.)
. If a law enforcement officer determines under subsection (2) or (3) of this section that there is probable cause to believe a valid Canadian domestic violence protection order exists and the order has been violated, the officer shall enforce the terms of the Canadian domestic violence protection order as if the terms were in an order of a tribunal. Presentation to a law enforcement officer of a certified copy of a Canadian domestic violence protection order is not required for enforcement.

. Presentation to a law enforcement officer of a record of a Canadian domestic violence protection order that identifies both a protected individual and a respondent and on its face is in effect constitutes probable cause to believe that a valid order exists.

. If a record of a Canadian domestic violence protection order is not presented as provided in subsection (2) of this section, a law enforcement officer may consider other information in determining whether there is probable cause to believe that a valid Canadian domestic violence protection order exists.

. If a law enforcement officer determines that an otherwise valid Canadian domestic violence protection order cannot be enforced because the respondent has not been notified of or served with the order, the officer shall notify the protected individual that the officer will make reasonable efforts to contact the respondent, consistent with the safety of the protected individual. After notice to the protected individual and consistent with the safety of the individual, the officer shall make a reasonable effort to inform the respondent of the order, notify the respondent of the terms of the order, provide a record of the order, if available, to the respondent, and allow the respondent a reasonable opportunity to comply with the order before the officer enforces the order.

. If a law enforcement officer determines that an individual is a protected individual, the officer shall inform the individual of available local victim services.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1517-S2.SL.pdf?cite=2019%20c%20263%20§%20903[2019 c 263 § 903]; ]

== 26.55.030 - Enforcement of Canadian domestic violence protection order by tribunal. (Effective until July 1, 2022.)
. A tribunal may issue an order enforcing or refusing to enforce a Canadian domestic violence protection order on application of:

.. A person authorized by law of this state other than this chapter to seek enforcement of a domestic protection order; or

.. A respondent.

. In a proceeding under subsection (1) of this section, the tribunal shall follow the procedures of this state for enforcement of a domestic protection order. An order entered under this section is limited to the enforcement of the terms of the Canadian domestic violence protection order as defined in RCW 26.55.010.

. A Canadian domestic violence protection order is enforceable under this section if:

.. The order identifies a protected individual and a respondent;

.. The order is valid and in effect;

.. The issuing court had jurisdiction over the parties and the subject matter under law applicable in the issuing court; and

.. The order was issued after:

... The respondent was given reasonable notice and had an opportunity to be heard before the court issued the order; or

... In the case of an ex parte order, the respondent was given reasonable notice and had or will have an opportunity to be heard within a reasonable time after the order was issued, in a manner consistent with the right of the respondent to due process.

. A Canadian domestic violence protection order valid on its face is prima facie evidence of its enforceability under this section.

. A claim that a Canadian domestic violence protection order does not comply with subsection (3) of this section is an affirmative defense in a proceeding seeking enforcement of the order. If the tribunal determines that the order is not enforceable, the tribunal shall issue an order that the Canadian domestic violence protection order is not enforceable under this section and RCW 26.55.020 and may not be registered under RCW 26.55.040.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1517-S2.SL.pdf?cite=2019%20c%20263%20§%20904[2019 c 263 § 904]; ]

== 26.55.040 - Registration of Canadian domestic violence protection order. (Effective until July 1, 2022.)
. A person entitled to protection who has a valid Canadian domestic violence protection order may file that order by presenting a certified, authenticated, or exemplified copy of the Canadian domestic violence protection order to a clerk of the court of a Washington court in which the person entitled to protection resides or to a clerk of the court of a Washington court where the person entitled to protection believes enforcement may be necessary. Any out-of-state department, agency, or court responsible for maintaining protection order records, may by facsimile or electronic transmission send a reproduction of the foreign protection order to the clerk of the court of Washington as long as it contains a facsimile or digital signature by any person authorized to make such transmission.

. On receipt of a certified copy of a Canadian domestic violence protection order, the clerk of the court shall register the order in accordance with this section.

. An individual registering a Canadian domestic violence protection order under this section shall file an affidavit stating that, to the best of the individual's knowledge, the order is valid and in effect.

. After a Canadian domestic violence protection order is registered under this section, the clerk of the court shall provide the individual registering the order a certified copy of the registered order.

. A Canadian domestic violence protection order registered under this section may be entered in a state or federal registry of protection orders in accordance with law.

. An inaccurate, expired, or unenforceable Canadian domestic violence protection order may be corrected or removed from the registry of protection orders maintained in this state in accordance with law of this state other than this chapter.

. A fee may not be charged for the registration of a Canadian domestic violence protection order under this section.

. Registration in this state or filing under law of this state other than this chapter of a Canadian domestic violence protection order is not required for its enforcement under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1517-S2.SL.pdf?cite=2019%20c%20263%20§%20905[2019 c 263 § 905]; ]

== 26.55.045 - Forwarding of order to law enforcement agency. (Effective July 1, 2022.)
. A copy of a Canadian domestic violence protection order filed with the clerk, an order granting recognition and enforcement, or an order denying recognition and enforcement under this chapter, shall be forwarded by the clerk of the court on or before the next judicial day to the law enforcement agency specified in the order. An order granting or denying recognition and enforcement shall be accompanied by a copy of the related Canadian domestic violence protection order.

. Upon receipt of the order, the law enforcement agency shall comply with the requirements of RCW 7.105.325.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1320-S2.SL.pdf?cite=2021%20c%20215%20§%2084[2021 c 215 § 84]; ]

== 26.55.050 - Immunity from civil and criminal liability. (Effective until July 1, 2022.)
The state, state agency, local governmental agency, law enforcement officer, prosecuting attorney, clerk of court, and state or local governmental official acting in an official capacity are immune from civil and criminal liability for an act or omission arising out of the registration or enforcement of a Canadian domestic violence protection order or the detention or arrest of an alleged violator of a Canadian domestic violence protection order if the act or omission was a good faith effort to comply with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1517-S2.SL.pdf?cite=2019%20c%20263%20§%20906[2019 c 263 § 906]; ]

== 26.55.060 - Other remedies.
An individual who seeks a remedy under this chapter may seek other legal or equitable remedies.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1517-S2.SL.pdf?cite=2019%20c%20263%20§%20907[2019 c 263 § 907]; ]

== 26.55.900 - Uniformity of application and construction—2019 c 263.
In applying and construing this uniform act, consideration must be given to the need to promote uniformity of the law with respect to its subject matter among states that enact it.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1517-S2.SL.pdf?cite=2019%20c%20263%20§%20908[2019 c 263 § 908]; ]

== 26.55.901 - Relation to electronic signatures in global and national commerce act.
This chapter modifies, limits, or supersedes the electronic signatures in global and national commerce act, 15 U.S.C. Sec. 7001 et seq., but does not modify, limit, or supersede Section 101(c) of that act, 15 U.S.C. Sec. 7001(c), or authorize electronic delivery of any of the notices described in Section 103(b) of that act, 15 U.S.C. Sec. 7003(b).

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1517-S2.SL.pdf?cite=2019%20c%20263%20§%20909[2019 c 263 § 909]; ]

== 26.55.902 - Applicability.
This chapter applies to a Canadian domestic violence protection order issued before, on, or after January 1, 2020, and to a continuing action for enforcement of a Canadian domestic violence protection order commenced before, on, or after January 1, 2020. A request for enforcement of a Canadian domestic violence protection order made on or after January 1, 2020, for a violation of the order occurring before, on, or after January 1, 2020, is governed by this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1517-S2.SL.pdf?cite=2019%20c%20263%20§%20910[2019 c 263 § 910]; ]

== 26.55.903 - Effective date—2019 c 263 §§ 901-915, 1001, and 1002.
Sections 901 through 915, 1001, and 1002 of this act take effect January 1, 2020.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1517-S2.SL.pdf?cite=2019%20c%20263%20§%201003[2019 c 263 § 1003]; ]

