= 26.60 - State registered domestic partnerships.
:toc:

== 26.60.010 - Finding.
Many Washingtonians are in intimate, committed, and exclusive relationships with another person to whom they are not legally married. These relationships are important to the individuals involved and their families; they also benefit the public by providing a private source of mutual support for the financial, physical, and emotional health of those individuals and their families. The public has an interest in providing a legal framework for such mutually supportive relationships, whether the partners are of the same or different sexes, and irrespective of their sexual orientation.

The legislature finds that the public interest would be served by extending rights and benefits to couples in which either or both of the partners are at least sixty-two years of age. While these couples are entitled to marry under the state's marriage statutes, some social security and pension laws nevertheless make it impractical for these couples to marry. For this reason, chapter 156, Laws of 2007 specifically allows couples to enter into a state registered domestic partnership if one of the persons is at least sixty-two years of age, the age at which many people choose to retire and are eligible to begin collecting social security and pension benefits.

The rights granted to state registered domestic partners in chapter 156, Laws of 2007 will further Washington's interest in promoting family relationships and protecting family members during life crises. Chapter 156, Laws of 2007 does not affect marriage or any other ways in which legal rights and responsibilities between two adults may be created, recognized, or given effect in Washington.

[ 2012 c 3 § 8 (Referendum Measure No. 74, approved November 6, 2012); http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5336-S.SL.pdf?cite=2007%20c%20156%20§%201[2007 c 156 § 1]; ]

== 26.60.015 - Intent.
It is the intent of the legislature that for all purposes under state law, state registered domestic partners shall be treated the same as married spouses. Any privilege, immunity, right, benefit, or responsibility granted or imposed by statute, administrative or court rule, policy, common law or any other law to an individual because the individual is or was a spouse, or because the individual is or was an in-law in a specified way to another individual, is granted on equivalent terms, substantive and procedural, to an individual because the individual is or was in a state registered domestic partnership or because the individual is or was, based on a state registered domestic partnership, related in a specified way to another individual. The provisions of chapter 521, Laws of 2009 shall be liberally construed to achieve equal treatment, to the extent not in conflict with federal law, of state registered domestic partners and married spouses.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%201[2009 c 521 § 1]; ]

== 26.60.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "State registered domestic partners" means two adults who meet the requirements for a valid state registered domestic partnership as established by RCW 26.60.030 and who have been issued a certificate of state registered domestic partnership by the secretary.

. "Secretary" means the secretary of state's office.

. "Share a common residence" means inhabit the same residence. Two persons shall be considered to share a common residence even if:

.. Only one of the domestic partners has legal ownership of the common residence;

.. One or both domestic partners have additional residences not shared with the other domestic partner; or

.. One domestic partner leaves the common residence with the intent to return.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5336-S.SL.pdf?cite=2007%20c%20156%20§%202[2007 c 156 § 2]; ]

== 26.60.025 - Definition—Domestic partnership.
Whenever the term "domestic partnership" is used in the Revised Code of Washington it shall be defined to mean "state registered domestic partnership" and whenever the term "domestic partner" is used in the Revised Code of Washington it shall be defined to mean "state registered domestic partner."

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%201201[2008 c 6 § 1201]; ]

== 26.60.030 - Requirements.
To enter into a state registered domestic partnership the two persons involved must meet the following requirements:

. Both persons share a common residence;

. Both persons are at least eighteen years of age and at least one of the persons is sixty-two years of age or older;

. Neither person is married to someone other than the party to the domestic partnership and neither person is in a state registered domestic partnership with another person;

. Both persons are capable of consenting to the domestic partnership; and

. Both of the following are true:

.. The persons are not nearer of kin to each other than second cousins, whether of the whole or half blood computing by the rules of the civil law; and

.. Neither person is a sibling, child, grandchild, aunt, uncle, niece, or nephew to the other person.

[ 2012 c 3 § 9 (Referendum Measure No. 74, approved November 6, 2012); http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5336-S.SL.pdf?cite=2007%20c%20156%20§%204[2007 c 156 § 4]; ]

== 26.60.040 - Registration—Records—Fees.
. Two persons desiring to become state registered domestic partners who meet the requirements of RCW 26.60.030 may register their domestic partnership by filing a declaration of state registered domestic partnership with the secretary and paying the filing fee established pursuant to subsection (4) of this section. The declaration must be signed by both parties and notarized.

. Upon receipt of a signed, notarized declaration and the filing fee, the secretary shall register the declaration and provide a certificate of state registered domestic partnership to each party named on the declaration.

. The secretary shall permanently maintain a record of each declaration of state registered domestic partnership filed with the secretary. The secretary has the authority to update the records to reflect changes in the status of a state registered domestic partnership, such as a change of address, name, dissolution, or death. The secretary shall provide the state registrar of vital statistics with records of declarations of state registered domestic partnerships.

. The secretary shall set by rule and collect a reasonable fee for filing the declaration, calculated to cover the secretary's costs, but not to exceed fifty dollars. Fees collected under this section are expressly designated for deposit in the secretary of state's revolving fund established under RCW 43.07.130.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%2071[2009 c 521 § 71]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5336-S.SL.pdf?cite=2007%20c%20156%20§%205[2007 c 156 § 5]; ]

== 26.60.060 - Domestic partnerships created by subdivisions of the state.
. [Empty]
.. A domestic partnership created by a subdivision of the state is not a state registered domestic partnership for the purposes of a state registered domestic partnership under this chapter. Those persons desiring to become state registered domestic partners under this chapter must register pursuant to RCW 26.60.040.

.. A subdivision of the state that provides benefits to the domestic partners of its employees and chooses to use the definition of state registered domestic partner as set forth in RCW 26.60.020 must allow the certificate issued by the secretary of state to satisfy any registration requirements of the subdivision. A subdivision that uses the definition of state registered domestic partner as set forth in RCW 26.60.020 shall notify the secretary of state. The secretary of state shall compile and maintain a list of all subdivisions that have filed such notice. The secretary of state shall post this list on the secretary's web page and provide a copy of the list to each person that receives a certificate of state registered domestic partnership under RCW 26.60.040(2).

.. Nothing in this section shall affect domestic partnerships created by any public entity.

. Nothing in chapter 156, Laws of 2007 affects any remedy available in common law.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5336-S.SL.pdf?cite=2007%20c%20156%20§%207[2007 c 156 § 7]; ]

== 26.60.070 - Patient visitation.
A patient's state registered domestic partner shall have the same rights as a spouse with respect to visitation of the patient in a health care facility as defined in RCW 48.43.005.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5336-S.SL.pdf?cite=2007%20c%20156%20§%208[2007 c 156 § 8]; ]

== 26.60.080 - Community property rights—Date of application.
Any community property rights of domestic partners established by chapter 6, Laws of 2008 shall apply from the date of the initial registration of the domestic partnership or June 12, 2008, whichever is later.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%20601[2008 c 6 § 601]; ]

== 26.60.090 - Reciprocity.
A legal union, other than a marriage, of two persons that was validly formed in another jurisdiction, and that is substantially equivalent to a domestic partnership under this chapter, shall be recognized as a valid domestic partnership in this state and shall be treated the same as a domestic partnership registered in this state regardless of whether it bears the name domestic partnership.

[ 2012 c 3 § 12 (Referendum Measure No. 74, approved November 6, 2012); http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1649.SL.pdf?cite=2011%20c%209%20§%201[2011 c 9 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%2072[2009 c 521 § 72]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%201101[2008 c 6 § 1101]; ]

== 26.60.100 - Application for marriage—Dissolution of partnership by marriage—Automatic merger of partnership into marriage—Legal date of marriage.
. Partners in a state registered domestic partnership may apply and receive a marriage license and have such marriage solemnized pursuant to chapter 26.04 RCW, so long as the parties are otherwise eligible to marry, and the parties to the marriage are the same as the parties to the state registered domestic partnership.

. A state registered domestic partnership is dissolved by operation of law by any marriage of the same parties to each other, as of the date of the marriage stated in the certificate.

. [Empty]
.. Except as provided in (b) of this subsection, any state registered domestic partnership in which the parties are the same sex, and neither party is sixty-two years of age or older, that has not been dissolved or converted into a marriage by the parties by June 30, 2014, is automatically merged into a marriage and is deemed a marriage as of June 30, 2014.

.. If the parties to a state registered domestic partnership have proceedings for dissolution, annulment, or legal separation pending as of June 30, 2014, the parties' state registered domestic partnership is not automatically merged into a marriage and the dissolution, annulment, or legal separation of the state registered domestic partnership is governed by the provisions of the statutes applicable to state registered domestic partnerships in effect before June 30, 2014. If such proceedings are finalized without dissolution, annulment, or legal separation, the state registered domestic partnership is automatically merged into a marriage and is deemed a marriage as of June 30, 2014.

. For purposes of determining the legal rights and responsibilities involving individuals who had previously had a state registered domestic partnership and have been issued a marriage license or are deemed married under the provisions of this section, the date of the original state registered domestic partnership is the legal date of the marriage. Nothing in this subsection prohibits a different date from being included on the marriage license.

[ 2012 c 3 § 10 (Referendum Measure No. 74, approved November 6, 2012); ]

== 26.60.900 - Part headings not law—2008 c 6.
Part headings used in this act are not any part of the law.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%201301[2008 c 6 § 1301]; ]

== 26.60.901 - Severability—2008 c 6.
If any provision of this act or its application to any person or circumstance is held invalid, the remainder of the act or the application of the provision to other persons or circumstances is not affected.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3104-S2.SL.pdf?cite=2008%20c%206%20§%201302[2008 c 6 § 1302]; ]

