= 8.16 - Eminent domain by school districts.
:toc:

== 8.16.005 - Condemnation final actions—Notice requirements.
Proceedings under this chapter are subject to the notice requirements of RCW 8.25.290. Compliance with RCW 8.25.290 is required before an action can be filed under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1458-S.SL.pdf?cite=2007%20c%2068%20§%205[2007 c 68 § 5]; ]

== 8.16.010 - Condemnation authorized for schoolhouse sites.
Whenever any school district shall select any real estate as a site for a schoolhouse, or as additional grounds to an existing schoolhouse site, within the district, and the board of school directors of such district and the owner or owners of the site or any part thereof, or addition thereto selected, shall be unable to agree upon the compensation to be paid by such school district to the owner or owners thereof, such school district shall have the right to take and acquire title to such real estate for use as a schoolhouse site or additional site, upon first paying to the owner or owners thereof therefor the value thereof, to be ascertained in the manner hereinafter provided.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c372.pdf?cite=1909%20p%20372%20§%201[1909 p 372 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c111.pdf?cite=1903%20c%20111%20§%201[1903 c 111 § 1]; RRS § 906; ]

== 8.16.020 - Petition—Contents.
The board of directors of the school district shall present to the superior court of the state of Washington in and for the county wherein is situated the real estate desired to be acquired for schoolhouse site purposes, a petition, reciting that the board of directors of such school district have selected certain real estate, describing it, as a schoolhouse site, or as additional grounds to an existing site, for such school district; that the site so selected, or some part thereof, describing it, belongs to a person or persons, naming him, her, or them, that such school district has offered to give the owner or owners thereof therefor . . . . . . dollars, and that the owner of such real estate has refused to accept the same therefor; that the board of school directors of such school district and the said owner or owners of such real estate are unable to agree upon the compensation to be paid by such school district to the owner or owners of such real estate therefor, and praying that a jury be impaneled to ascertain and determine the compensation to be made in money by such school district to such owner or owners for the taking of such real estate for the use as a schoolhouse site for such school district; or in case a jury be waived in the manner provided by law in other civil actions in courts of record, then that the compensation to be made as aforesaid, be ascertained and determined by the court, or judge thereof.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20272[2011 c 336 § 272]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c372.pdf?cite=1909%20p%20372%20§%202[1909 p 372 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c111.pdf?cite=1903%20c%20111%20§%202[1903 c 111 § 2]; RRS § 907; ]

== 8.16.030 - Notice of petition—Service.
A notice, stating the time and place when and where such petition shall be presented to the court, or the judge thereof, together with a copy of such petition, shall be served on each and every person named therein as owner, or otherwise interested therein, at least ten days previous to the time designated in such notice for the presentation of such petition. Such notice shall be signed by the prosecuting attorney of the county wherein the real estate sought to be taken is situated, and may be served in the same manner as summons in a civil action in such superior court is authorized by law to be served.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c373.pdf?cite=1909%20p%20373%20§%203[1909 p 373 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c111.pdf?cite=1903%20c%20111%20§%203[1903 c 111 § 3]; RRS § 908; ]

== 8.16.040 - Adjournment of proceedings—Further notice.
The court may, upon application of the petitioner or of any owner of said real estate, or any person interested therein, for reasonable cause, adjourn the proceedings from time to time, and may order new or further notice to be given to any party whose interests may be affected by such proceedings.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c373.pdf?cite=1909%20p%20373%20§%204[1909 p 373 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c111.pdf?cite=1903%20c%20111%20§%204[1903 c 111 § 4]; RRS § 909; ]

== 8.16.050 - Hearing—Finding of necessity—Setting for trial.
At the time and place appointed for the hearing of such petition, or to which the same may have been adjourned, if the court shall find that all parties interested in such real estate sought to be taken have been duly served with notice and a copy of the petition as above prescribed, and shall further find that such real estate sought to be taken is required and necessary for the purposes of a schoolhouse site, or as an addition to a schoolhouse site, for such school district, the court shall make an order reciting such findings, and shall thereupon set the hearing of such petition down for trial by a jury, as other civil actions are tried, unless a jury is waived in the manner provided by law in other civil actions.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c373.pdf?cite=1909%20p%20373%20§%205[1909 p 373 § 5]; RRS § 910; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c111.pdf?cite=1903%20c%20111%20§%205[1903 c 111 § 5]; ]

== 8.16.060 - Impaneling of jury.
The jury impaneled to hear the evidence and determine the compensation to be paid to the owner or owners of such real estate desired for such schoolhouse site purpose shall consist of twelve persons unless a less number be agreed upon, and shall be selected, impaneled, and sworn in the same manner that juries in other civil actions are selected, impaneled, and sworn, provided a juror may be challenged for cause on the ground that he or she is a taxpayer of the district seeking the condemnation of any real estate.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20273[2011 c 336 § 273]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c373.pdf?cite=1909%20p%20373%20§%206[1909 p 373 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c111.pdf?cite=1903%20c%20111%20§%206[1903 c 111 § 6]; RRS § 911; ]

== 8.16.070 - Trial—View by jury.
A judge of the superior court shall preside at the trial and witnesses may be examined in behalf of either party to the proceedings, as in other civil actions, and upon the request of all the parties interested in such proceedings the court shall cause the jury impaneled to hear the same, to view the premises sought to be taken, and upon the request of any less number of the persons interested in the proceedings, the court may cause the jury to view the premises, pending the hearing of the case.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c374.pdf?cite=1909%20p%20374%20§%207[1909 p 374 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c111.pdf?cite=1903%20c%20111%20§%207[1903 c 111 § 7]; RRS § 912; ]

== 8.16.080 - Verdict.
Upon the close of the evidence, and the argument of counsel, the court shall instruct the jury as to the matters submitted to them, and the law pertaining thereto, whereupon the jury shall retire and deliberate and determine upon the amount of compensation in money that shall be paid to the owner or owners of the real estate sought to be taken for such schoolhouse site purposes therefor, which shall be the amount found by the jury to be the fair and full value of such premises; and when the jury shall have determined upon their verdict, they shall return the same to the court as in other civil actions.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c374.pdf?cite=1909%20p%20374%20§%208[1909 p 374 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c111.pdf?cite=1903%20c%20111%20§%208[1903 c 111 § 8]; RRS § 913; ]

== 8.16.090 - Ten jurors may render verdict.
When ten of the jurors agree upon a verdict, the verdict so agreed upon shall be signed by the jury foreperson, and the verdict so agreed upon shall be and stand as the verdict of the jury.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%203[2013 c 23 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c374.pdf?cite=1909%20p%20374%20§%209[1909 p 374 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c111.pdf?cite=1903%20c%20111%20§%209[1903 c 111 § 9]; RRS § 914; ]

== 8.16.100 - Waiver of jury.
In case a jury is waived, the compensation that shall be paid for the premises taken shall be determined by the court and the proceedings shall be the same as in the trial of issues of fact by the court in other civil actions.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c374.pdf?cite=1909%20p%20374%20§%2010[1909 p 374 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c111.pdf?cite=1903%20c%20111%20§%2010[1903 c 111 § 10]; RRS § 915; ]

== 8.16.110 - Judgment—Payment of award—Decree of appropriation.
Upon the verdict of the jury, or upon the determination by the court of the compensation to be paid for the property sought to be taken as herein provided, judgment shall be entered against such school district in favor of the owner or owners of the real estate sought to be taken, for the amount found as compensation therefor, and upon the payment of such amount by such school district to the clerk of such court for the use of the owner or owners of, and the persons interested in the premises sought to be taken, the court shall enter a decree of appropriation of the real estate sought to be taken, thereby vesting the title to the same in such school district; and a certified copy of such decree of appropriation may be filed in the office of the county auditor of the county wherein the real estate taken is situated, and shall be recorded by such auditor like a deed of real estate, and with like effect. The money so paid to the clerk of the court shall be by him or her paid to the person or persons entitled thereto, upon the order of the court.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20274[2011 c 336 § 274]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c374.pdf?cite=1909%20p%20374%20§%2011[1909 p 374 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c111.pdf?cite=1903%20c%20111%20§%2011[1903 c 111 § 11]; RRS § 916; ]

== 8.16.120 - Costs.
All the costs of such proceedings in the superior court shall be paid by the school district initiating such proceedings.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c375.pdf?cite=1909%20p%20375%20§%2012[1909 p 375 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c111.pdf?cite=1903%20c%20111%20§%2012[1903 c 111 § 12]; RRS § 917; ]

== 8.16.130 - Appellate review.
Either party may seek appellate review of the judgment for compensation awarded for the property taken, entered in the superior court, to the supreme court or the court of appeals of the state within sixty days after the entry of the judgment, and such review shall bring before the supreme court or the court of appeals the justness of the compensation awarded for the property taken, and any error occurring on the hearing of such matter, prejudicial to the party appealing: PROVIDED, HOWEVER, That if the owner or owners of the land taken accepts the sum awarded by the jury or court, he, she, or they shall be deemed thereby to have waived appellate review.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20275[2011 c 336 § 275]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c202.pdf?cite=1988%20c%20202%20§%2012[1988 c 202 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971c81.pdf?cite=1971%20c%2081%20§%2041[1971 c 81 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c375.pdf?cite=1909%20p%20375%20§%2013[1909 p 375 § 13]; RRS § 918; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c111.pdf?cite=1903%20c%20111%20§%2013[1903 c 111 § 13]; ]

== 8.16.140 - Appeal does not delay possession if award paid.
An appeal from such judgment by the owner or owners of the land sought to be taken, shall not have the effect to preclude the school district from taking possession of the premises sought, pending the appeal, provided the amount of the judgment against the school district shall have been paid in to the clerk of the court, as hereinbefore provided.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c375.pdf?cite=1909%20p%20375%20§%2014[1909 p 375 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c111.pdf?cite=1903%20c%20111%20§%2014[1903 c 111 § 14]; RRS § 919; ]

== 8.16.150 - Designation of parties—Fees.
In all proceedings under this chapter the school district seeking to acquire title to real estate for a schoolhouse site, shall be denominated plaintiff, and all other persons interested therein shall be denominated defendants; and in all such proceedings the clerk of the superior court wherein any such proceeding is brought shall charge nothing for his or her services, except in taking an appeal from the judgment entered in the superior court.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20276[2011 c 336 § 276]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c375.pdf?cite=1909%20p%20375%20§%2015[1909 p 375 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c111.pdf?cite=1903%20c%20111%20§%2015[1903 c 111 § 15]; RRS § 920; ]

