= 62A.2 - Sales.
:toc:

== 62A.2-101 - Short title.
This Article shall be known and may be cited as Uniform Commercial Code—Sales.

[ 1965 ex.s. c 157 § 2-101; ]

== 62A.2-102 - Scope; certain security and other transactions excluded from this Article.
Unless the context otherwise requires, this Article applies to transactions in goods; it does not apply to any transaction which although in the form of an unconditional contract to sell or present sale is intended to operate only as a security transaction nor does this Article impair or repeal any statute regulating sales to consumers, farmers or other specified classes of buyers.

[ 1965 ex.s. c 157 § 2-102. Cf. former RCW  63.04.750; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2075[1925 ex.s. c 142 § 75]; RRS § 5836-75; ]

== 62A.2-103 - Definitions and index of definitions.
. In this Article unless the context otherwise requires:

.. "Buyer" means a person who buys or contracts to buy goods.

.. [Reserved.]

.. "Receipt" of goods means taking physical possession of them.

.. "Seller" means a person who sells or contracts to sell goods.

. Other definitions applying to this Article or to specified Parts thereof, and the sections in which they appear are:

 "Acceptance."RCW 62A.2-606. "Banker's credit."RCW 62A.2-325. "Between merchants."RCW 62A.2-104. "Cancellation."RCW 62A.2-106(4). "Commercial unit."RCW 62A.2-105. "Confirmed credit."RCW 62A.2-325. "Conforming to contract."RCW 62A.2-106. "Contract for sale."RCW 62A.2-106. "Cover."RCW 62A.2-712. "Entrusting."RCW 62A.2-403. "Financing agency."RCW 62A.2-104. "Future goods."RCW 62A.2-105. "Goods."RCW 62A.2-105. "Identification."RCW 62A.2-501. "Installment contract."RCW 62A.2-612. "Letter of credit."RCW 62A.2-325. "Lot."RCW 62A.2-105. "Merchant."RCW 62A.2-104. "Overseas."RCW 62A.2-323. "Person in position of seller."RCW 62A.2-707. "Present sale."RCW 62A.2-106. "Sale."RCW 62A.2-106. "Sale on approval."RCW 62A.2-326. "Sale or return."RCW 62A.2-326. "Termination."RCW 62A.2-106.

 

"Acceptance."

RCW 62A.2-606.

 

"Banker's credit."

RCW 62A.2-325.

 

"Between merchants."

RCW 62A.2-104.

 

"Cancellation."

RCW 62A.2-106(4).

 

"Commercial unit."

RCW 62A.2-105.

 

"Confirmed credit."

RCW 62A.2-325.

 

"Conforming to contract."

RCW 62A.2-106.

 

"Contract for sale."

RCW 62A.2-106.

 

"Cover."

RCW 62A.2-712.

 

"Entrusting."

RCW 62A.2-403.

 

"Financing agency."

RCW 62A.2-104.

 

"Future goods."

RCW 62A.2-105.

 

"Goods."

RCW 62A.2-105.

 

"Identification."

RCW 62A.2-501.

 

"Installment contract."

RCW 62A.2-612.

 

"Letter of credit."

RCW 62A.2-325.

 

"Lot."

RCW 62A.2-105.

 

"Merchant."

RCW 62A.2-104.

 

"Overseas."

RCW 62A.2-323.

 

"Person in position of seller."

RCW 62A.2-707.

 

"Present sale."

RCW 62A.2-106.

 

"Sale."

RCW 62A.2-106.

 

"Sale on approval."

RCW 62A.2-326.

 

"Sale or return."

RCW 62A.2-326.

 

"Termination."

RCW 62A.2-106.

. "Control" as provided in RCW 62A.7-106 and the following definitions in other articles apply to this Article:

 "Check."RCW 62A.3-104. "Consignee."RCW 62A.7-102. "Consignor."RCW 62A.7-102. "Consumer goods."RCW 62A.9A-102. "Dishonor."RCW 62A.3-502. "Draft."RCW 62A.3-104.

 

"Check."

RCW 62A.3-104.

 

"Consignee."

RCW 62A.7-102.

 

"Consignor."

RCW 62A.7-102.

 

"Consumer goods."

RCW 62A.9A-102.

 

"Dishonor."

RCW 62A.3-502.

 

"Draft."

RCW 62A.3-104.

. In addition Article 1 contains general definitions and principles of construction and interpretation applicable throughout this Article.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20801[2012 c 214 § 801]; 2000 c 250 § 9A-803; 1965 ex.s. c 157 § 2-103. Cf. former RCW  63.04.755; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2076[1925 ex.s. c 142 § 76]; RRS § 5836-76; formerly RCW  63.04.010; ]

== 62A.2-104 - Definitions: "Merchant"; "between merchants"; "financing agency".
. "Merchant" means a person who deals in goods of the kind or otherwise by his or her occupation holds himself or herself out as having knowledge or skill peculiar to the practices or goods involved in the transaction or to whom such knowledge or skill may be attributed by his or her employment of an agent or broker or other intermediary who by his or her occupation holds himself or herself out as having such knowledge or skill.

. "Financing agency" means a bank, finance company or other person who in the ordinary course of business makes advances against goods or documents of title or who by arrangement with either the seller or the buyer intervenes in ordinary course to make or collect payment due or claimed under the contract for sale, as by purchasing or paying the seller's draft or making advances against it or by merely taking it for collection whether or not documents of title accompany or are associated with the draft. "Financing agency" includes also a bank or other person who similarly intervenes between persons who are in the position of seller and buyer in respect to the goods (RCW 62A.2-707).

. "Between merchants" means in any transaction with respect to which both parties are chargeable with the knowledge or skill of merchants.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20802[2012 c 214 § 802]; 1965 ex.s. c 157 § 2-104. Cf. former RCW sections:  RCW  63.04.160, (5); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2015[1925 ex.s. c 142 § 15]; RRS § 5836-15.  RCW  63.04.170(c); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2016[1925 ex.s. c 142 § 16]; RRS § 5836-16. (iii) RCW  63.04.460; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2045[1925 ex.s. c 142 § 45]; RRS § 5836-45. (iv) RCW  63.04.720; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2071[1925 ex.s. c 142 § 71]; RRS § 5836-71. (v) RCW  81.32.351; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.32.351[1961 c 14 § 81.32.351]; prior:  1915 c 159 § 35; RRS § 3681; formerly RCW  81.32.440. (vi) RCW  81.32.371; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.32.371[1961 c 14 § 81.32.371]; prior:  1915 c 159 § 37; RRS § 3683; formerly RCW  81.32.460; ]

== 62A.2-105 - Definitions: Transferability; "goods"; "future" goods; "lot"; "commercial unit".
. "Goods" means all things (including specially manufactured goods) which are movable at the time of identification to the contract for sale other than the money in which the price is to be paid, investment securities (Article 8) and things in action. "Goods" also includes the unborn young of animals and growing crops and other identified things attached to realty as described in the section on goods to be severed from realty (RCW 62A.2-107).

. Goods must be both existing and identified before any interest in them can pass. Goods which are not both existing and identified are "future" goods. A purported present sale of future goods or of any interest therein operates as a contract to sell.

. There may be a sale of a part interest in existing identified goods.

. An undivided share in an identified bulk of fungible goods is sufficiently identified to be sold although the quantity of the bulk is not determined. Any agreed proportion of such a bulk or any quantity thereof agreed upon by number, weight or other measure may to the extent of the seller's interest in the bulk be sold to the buyer who then becomes an owner in common.

. "Lot" means a parcel or a single article which is the subject matter of a separate sale or delivery, whether or not it is sufficient to perform the contract.

. "Commercial unit" means such a unit of goods as by commercial usage is a single whole for purposes of sale and division of which materially impairs its character or value on the market or in use. A commercial unit may be a single article (as a machine) or a set of articles (as a suite of furniture or an assortment of sizes) or a quantity (as a bale, gross, or carload) or any other unit treated in use or in the relevant market as a single whole.

[ 1965 ex.s. c 157 § 2-105. Subds. , , (3), (4), cf. former RCW sections:  RCW  63.04.060; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%205[1925 ex.s. c 142 § 5]; RRS § 5836-5.  RCW  63.04.070; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%206[1925 ex.s. c 142 § 6]; RRS § 5836-6. (iii) RCW  63.04.755; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2076[1925 ex.s. c 142 § 76]; RRS § 5836-76; formerly RCW  63.04.010; ]

== 62A.2-106 - Definitions: "Contract"; "agreement"; "contract for sale"; "sale"; "present sale"; "conforming" to contract; "termination"; "cancellation".
. In this Article unless the context otherwise requires "contract" and "agreement" are limited to those relating to the present or future sale of goods. "Contract for sale" includes both a present sale of goods and a contract to sell goods at a future time. A "sale" consists in the passing of title from the seller to the buyer for a price (RCW 62A.2-401). A "present sale" means a sale which is accomplished by the making of the contract.

. Goods or conduct including any part of a performance are "conforming" or conform to the contract when they are in accordance with the obligations under the contract.

. "Termination" occurs when either party pursuant to a power created by agreement or law puts an end to the contract otherwise than for its breach. On "termination" all obligations which are still executory on both sides are discharged but any right based on prior breach or performance survives.

. "Cancellation" occurs when either party puts an end to the contract for breach by the other and its effect is the same as that of "termination" except that the canceling party also retains any remedy for breach of the whole contract or any unperformed balance.

[ 1965 ex.s. c 157 § 2-106. Subd.  cf. former RCW  63.04.020; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%201[1925 ex.s. c 142 § 1]; RRS § 5836-1. Subd.  cf. former RCW sections:  RCW  63.04.120; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2011[1925 ex.s. c 142 § 11]; RRS § 5836-11.  RCW  63.04.450; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2044[1925 ex.s. c 142 § 44]; RRS § 5836-44. (iii) RCW  63.04.700; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2069[1925 ex.s. c 142 § 69]; RRS § 5836-69; ]

== 62A.2-107 - Goods to be severed from realty: Recording.
. A contract for the sale of minerals or the like including oil and gas or a structure or its materials to be removed from realty is a contract for the sale of goods within this Article if they are to be severed by the seller but until severance a purported present sale thereof which is not effective as a transfer of an interest in land is effective only as a contract to sell.

. A contract for the sale apart from the land of growing crops or other things attached to realty and capable of severance without material harm thereto but not described in subsection (1) or of timber to be cut is a contract for the sale of goods within this Article whether the subject matter is to be severed by the buyer or by the seller even though it forms part of the realty at the time of contracting, and the parties can by identification effect a present sale before severance.

. The provisions of this section are subject to any third party rights provided by the law relating to realty records, and the contract for sale may be executed and recorded as a document transferring an interest in land and shall then constitute notice to third parties of the buyer's rights under the contract for sale.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c41.pdf?cite=1981%20c%2041%20§%203[1981 c 41 § 3]; 1965 ex.s. c 157 § 2-107. Cf. former RCW sections:  RCW  63.04.755; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2076[1925 ex.s. c 142 § 76]; RRS § 5836-76; formerly RCW  63.04.010.  RCW  65.08.040; Code 1881 § 2327; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20413%20§%204[1863 p 413 § 4]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20404%20§%204[1854 p 404 § 4]; RRS § 5827; ]

== 62A.2-201 - Formal requirements; statute of frauds.
. Except as otherwise provided in this section, a contract for the sale of goods for the price of five hundred dollars or more is not enforceable by way of action or defense unless there is some writing sufficient to indicate that a contract for sale has been made between the parties and signed by the party against whom enforcement is sought or by his or her authorized agent or broker. A writing is not insufficient because it omits or incorrectly states a term agreed upon but the contract is not enforceable under this paragraph beyond the quantity of goods shown in such writing.

. Between merchants if within a reasonable time a writing in confirmation of the contract and sufficient against the sender is received and the party receiving it has reason to know its contents, it satisfies the requirements of subsection (1) of this section against such party unless written notice of objection to its contents is given within ten days after it is received.

. A contract which does not satisfy the requirements of subsection (1) of this section but which is valid in other respects is enforceable:

.. If the goods are to be specially manufactured for the buyer and are not suitable for sale to others in the ordinary course of the seller's business and the seller, before notice of repudiation is received and under circumstances which reasonably indicate that the goods are for the buyer, has made either a substantial beginning of their manufacture or commitments for their procurement; or

.. If the party against whom enforcement is sought admits in his or her pleading, testimony, or otherwise in court that a contract for sale was made, but the contract is not enforceable under this provision beyond the quantity of goods admitted; or

.. With respect to goods for which payment has been made and accepted or which have been received and accepted (RCW 62A.2-606).

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20126[2013 c 23 § 126]; 1965 ex.s c 157 § 2-201. Cf. former RCW  63.04.050; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%204[1925 ex.s. c 142 § 4]; RRS § 5836-4; prior: Code 1881 § 2326; ]

== 62A.2-202 - Final written expression: Parol or extrinsic evidence.
Terms with respect to which the confirmatory memoranda of the parties agree or which are otherwise set forth in a writing intended by the parties as a final expression of their agreement with respect to such terms as are included therein may not be contradicted by evidence of any prior agreement or of a contemporaneous oral agreement but may be explained or supplemented:

.. By course of performance, course of dealing, or usage of trade (RCW 62A.1-303); and

.. By evidence of consistent additional terms unless the court finds the writing to have been intended also as a complete and exclusive statement of the terms of the agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20803[2012 c 214 § 803]; 1965 ex.s. c 157 § 2-202; ]

== 62A.2-203 - Seals inoperative.
The affixing of a seal to a writing evidencing a contract for sale or an offer to buy or sell goods does not constitute the writing a sealed instrument and the law with respect to sealed instruments does not apply to such contract or offer.

[ 1965 ex.s. c 157 § 2-203. Cf. former RCW  63.04.040; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%203[1925 ex.s. c 142 § 3]; RRS § 5836-3; ]

== 62A.2-204 - Formation in general.
. A contract for sale of goods may be made in any manner sufficient to show agreement, including conduct by both parties which recognizes the existence of such a contract.

. An agreement sufficient to constitute a contract for sale may be found even though the moment of its making is undetermined.

. Even though one or more terms are left open a contract for sale does not fail for indefiniteness if the parties have intended to make a contract and there is a reasonably certain basis for giving an appropriate remedy.

[ 1965 ex.s. c 157 § 2-204. Cf. former RCW sections:  RCW  63.04.020; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%201[1925 ex.s. c 142 § 1]; RRS § 5836-1.  RCW  63.04.040; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%203[1925 ex.s. c 142 § 3]; RRS § 5836-3; ]

== 62A.2-205 - Firm offers.
An offer by a merchant to buy or sell goods in a signed writing which by its terms gives assurance that it will be held open is not revocable, for lack of consideration, during the time stated or if no time is stated for a reasonable time, but in no event may such period of irrevocability exceed three months; but any such term of assurance on a form supplied by the offeree must be separately signed by the offeror.

[ 1965 ex.s. c 157 § 2-205. Cf. former RCW sections:  RCW  63.04.020; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%201[1925 ex.s. c 142 § 1]; RRS § 5836-1.  RCW  63.04.040; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%203[1925 ex.s. c 142 § 3]; RRS § 5836-3; ]

== 62A.2-206 - Offer and acceptance in formation of contract.
. Unless otherwise unambiguously indicated by the language or circumstances 

.. an offer to make a contract shall be construed as inviting acceptance in any manner and by any medium reasonable in the circumstances;

.. an order or other offer to buy goods for prompt or current shipment shall be construed as inviting acceptance either by a prompt promise to ship or by the prompt or current shipment of conforming or non-conforming goods, but such a shipment of non-conforming goods does not constitute an acceptance if the seller seasonably notifies the buyer that the shipment is offered only as an accommodation to the buyer.

. Where the beginning of a requested performance is a reasonable mode of acceptance an offeror who is not notified of acceptance within a reasonable time may treat the offer as having lapsed before acceptance.

[ 1965 ex.s. c 157 § 2-206. Cf. former RCW sections:  RCW  63.04.020; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%201[1925 ex.s. c 142 § 1]; RRS § 5836-1.  RCW  63.04.040; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%203[1925 ex.s. c 142 § 3]; RRS § 5836-3; ]

== 62A.2-207 - Additional terms in acceptance or confirmation.
. A definite and seasonable expression of acceptance or a written confirmation which is sent within a reasonable time operates as an acceptance even though it states terms additional to or different from those offered or agreed upon, unless acceptance is expressly made conditional on assent to the additional or different terms.

. The additional terms are to be construed as proposals for addition to the contract. Between merchants such terms become part of the contract unless:

.. the offer expressly limits acceptance to the terms of the offer;

.. they materially alter it; or

.. notification of objection to them has already been given or is given within a reasonable time after notice of them is received.

. Conduct by both parties which recognizes the existence of a contract is sufficient to establish a contract for sale although the writings of the parties do not otherwise establish a contract. In such case the terms of the particular contract consist of those terms on which the writings of the parties agree, together with any supplementary terms incorporated under any other provisions of this Title.

[ 1965 ex.s. c 157 § 2-207. Cf. former RCW sections:  RCW  63.04.020; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%201[1925 ex.s. c 142 § 1]; RRS § 5836-1.  RCW  63.04.040; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%203[1925 ex.s. c 142 § 3]; RRS § 5836-3; ]

== 62A.2-209 - Modification, rescission and waiver.
. An agreement modifying a contract within this Article needs no consideration to be binding.

. A signed agreement which excludes modification or rescission except by a signed writing cannot be otherwise modified or rescinded, but except as between merchants such a requirement on a form supplied by the merchant must be separately signed by the other party.

. The requirements of the statute of frauds section of this Article (RCW 62A.2-201) must be satisfied if the contract as modified is within its provisions.

. Although an attempt at modification or rescission does not satisfy the requirements of subsection (2) or (3) it can operate as a waiver.

. A party who has made a waiver affecting an executory portion of the contract may retract the waiver by reasonable notification received by the other party that strict performance will be required of any term waived, unless the retraction would be unjust in view of a material change of position in reliance on the waiver.

[ 1965 ex.s. c 157 § 2-209; ]

== 62A.2-210 - Delegation of performance; assignment of rights.
. A party may perform his or her duty through a delegate unless otherwise agreed or unless the other party has a substantial interest in having his or her original promisor perform or control the acts required by the contract. No delegation of performance relieves the party delegating of any duty to perform or any liability for breach.

. Except as otherwise provided in RCW 62A.9A-406, unless otherwise agreed, all rights of either seller or buyer can be assigned except where the assignment would materially change the duty of the other party, or increase materially the burden or risk imposed on him or her by his or her contract, or impair materially his or her chance of obtaining return performance. A right to damages for breach of the whole contract or a right arising out of the assignor's due performance of his or her entire obligation can be assigned despite agreement otherwise.

. The creation, attachment, perfection, or enforcement of a security interest in the seller's interest under a contract is not a transfer that materially changes the duty of or increases materially the burden or risk imposed on the buyer or impairs materially the buyer's chance of obtaining return performance within the purview of subsection (2) of this section unless, and then only to the extent that, enforcement actually results in a delegation of material performance of the seller. Even in that event, the creation, attachment, perfection, and enforcement of the security interest remain effective, but (a) the seller is liable to the buyer for damages caused by the delegation to the extent that the damages could not reasonably be prevented by the buyer, and (b) a court having jurisdiction may grant other appropriate relief, including cancellation of the contract for sale or an injunction against enforcement of the security interest or consummation of the enforcement.

. Unless the circumstances indicate the contrary, a prohibition of assignment of "the contract" is to be construed as barring only the delegation to the assignee of the assignor's performance.

. An assignment of "the contract" or of "all my rights under the contract" or an assignment in similar general terms is an assignment of rights and unless the language or the circumstances (as in an assignment for security) indicate the contrary, it is a delegation of performance of the duties of the assignor and its acceptance by the assignee constitutes a promise by him or her to perform those duties. This promise is enforceable by either the assignor or the other party to the original contract.

. The other party may treat any assignment which delegates performance as creating reasonable grounds for insecurity and may without prejudice to his or her rights against the assignor demand assurances from the assignee (RCW 62A.2-609).

. Notwithstanding subsections (2) and (3) of this section, an assignment that would be a breach but for the provisions of RCW 62A.9A-406 may create reasonable grounds for insecurity with respect to the due performance of the assignor (RCW 62A.2-609).

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20127[2013 c 23 § 127]; 2000 c 250 § 9A-804; 1965 ex.s. c 157 § 2-210; ]

== 62A.2-301 - General obligations of parties.
The obligation of the seller is to transfer and deliver and that of the buyer is to accept and pay in accordance with the contract.

[ 1965 ex.s. c 157 § 2-301. Cf. former RCW sections:  RCW  63.04.120; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2011[1925 ex.s. c 142 § 11]; RRS § 5836-11.  RCW  63.04.420; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2041[1925 ex.s. c 142 § 41]; RRS § 5836-41; ]

== 62A.2-302 - Unconscionable contract or clause.
. If the court as a matter of law finds the contract or any clause of the contract to have been unconscionable at the time it was made the court may refuse to enforce the contract, or it may enforce the remainder of the contract without the unconscionable clause, or it may so limit the application of any unconscionable clause as to avoid any unconscionable result.

. When it is claimed or appears to the court that the contract or any clause thereof may be unconscionable the parties shall be afforded a reasonable opportunity to present evidence as to its commercial setting, purpose and effect to aid the court in making the determination.

[ 1965 ex.s. c 157 § 2-302; ]

== 62A.2-303 - Allocation or division of risks.
Where this Article allocates a risk or a burden as between the parties "unless otherwise agreed", the agreement may not only shift the allocation but may also divide the risk or burden.

[ 1965 ex.s. c 157 § 2-303; ]

== 62A.2-304 - Price payable in money, goods, realty, or otherwise.
. The price can be made payable in money or otherwise. If it is payable in whole or in part in goods each party is a seller of the goods which he or she is to transfer.

. Even though all or part of the price is payable in an interest in realty the transfer of the goods and the seller's obligations with reference to them are subject to this Article, but not the transfer of the interest in realty or the transferor's obligations in connection therewith.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20128[2013 c 23 § 128]; 1965 ex.s. c 157 § 2-304. Cf. former RCW  63.04.100, (3); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%209[1925 ex.s. c 142 § 9]; RRS § 5836-9; ]

== 62A.2-305 - Open price term.
. The parties if they so intend can conclude a contract for sale even though the price is not settled. In such a case, the price is a reasonable price at the time for delivery if:

.. Nothing is said as to price; or

.. The price is left to be agreed by the parties and they fail to agree; or

.. The price is to be fixed in terms of some agreed market or other standard as set or recorded by a third person or agency and it is not so set or recorded.

. A price to be fixed by the seller or by the buyer means a price for him or her to fix in good faith.

. When a price left to be fixed otherwise than by agreement of the parties fails to be fixed through fault of one party the other may at his or her option treat the contract as canceled or himself or herself fix a reasonable price.

. Where, however, the parties intend not to be bound unless the price be fixed or agreed and it is not fixed or agreed there is no contract. In such a case, the buyer must return any goods already received or if unable so to do must pay their reasonable value at the time of delivery and the seller must return any portion of the price paid on account.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20129[2013 c 23 § 129]; 1965 ex.s. c 157 § 2-305. Cf. former RCW sections:  RCW  63.04.100; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%209[1925 ex.s. c 142 § 9]; RRS § 5836-9.  RCW  63.04.110; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2010[1925 ex.s. c 142 § 10]; RRS § 5836-10. Subd. (3) cf. former RCW  63.04.120; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2011[1925 ex.s. c 142 § 11]; RRS § 5836-11; ]

== 62A.2-306 - Output, requirements and exclusive dealings.
. A term which measures the quantity by the output of the seller or the requirements of the buyer means such actual output or requirements as may occur in good faith, except that no quantity unreasonably disproportionate to any stated estimate or in the absence of a stated estimate to any normal or otherwise comparable prior output or requirements may be tendered or demanded.

. A lawful agreement by either the seller or the buyer for exclusive dealing in the kind of goods concerned imposes unless otherwise agreed an obligation by the seller to use best efforts to supply the goods and by the buyer to use best efforts to promote their sale.

[ 1965 ex.s. c 157 § 2-306; ]

== 62A.2-307 - Delivery in single lot or several lots.
Unless otherwise agreed all goods called for by a contract for sale must be tendered in a single delivery and payment is due only on such tender but where the circumstances give either party the right to make or demand delivery in lots the price if it can be apportioned may be demanded for each lot.

[ 1965 ex.s. c 157 § 2-307. Cf. former RCW  63.04.460; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2045[1925 ex.s. c 142 § 45]; RRS § 5836-45; ]

== 62A.2-308 - Absence of specified place for delivery.
Unless otherwise agreed:

.. The place for delivery of goods is the seller's place of business or if he or she has none his or her residence; but

.. In a contract for sale of identified goods which to the knowledge of the parties at the time of contracting are in some other place, that place is the place for their delivery; and

.. Documents of title may be delivered through customary banking channels.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20130[2013 c 23 § 130]; 1965 ex.s. c 157 § 2-308. Subd. (a), (b) cf. former RCW  63.04.440; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2043[1925 ex.s. c 142 § 43]; RRS § 5836-43; ]

== 62A.2-309 - Absence of specific time provisions; notice of termination.
. The time for shipment or delivery or any other action under a contract if not provided in this Article or agreed upon shall be a reasonable time.

. Where the contract provides for successive performances but is indefinite in duration it is valid for a reasonable time but unless otherwise agreed may be terminated at any time by either party.

. Termination of a contract by one party except on the happening of an agreed event requires that reasonable notification be received by the other party and an agreement dispensing with notification is invalid if its operation would be unconscionable.

[ 1965 ex.s. c 157 § 2-309. Cf. former RCW sections:  RCW  63.04.440; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2043[1925 ex.s. c 142 § 43]; RRS § 5836-43.  RCW  63.04.460; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2045[1925 ex.s. c 142 § 45]; RRS § 5836-45. (iii) RCW  63.04.480; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2047[1925 ex.s. c 142 § 47]; RRS § 5836-47. (iv) RCW  63.04.490; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2048[1925 ex.s. c 142 § 48]; RRS § 5836-48; ]

== 62A.2-310 - Open time for payment or running of credit; authority to ship under reservation.
Unless otherwise agreed:

.. Payment is due at the time and place at which the buyer is to receive the goods even though the place of shipment is the place of delivery; and

.. If the seller is authorized to send the goods he or she may ship them under reservation, and may tender the documents of title, but the buyer may inspect the goods after their arrival before payment is due unless such inspection is inconsistent with the terms of the contract (RCW 62A.2-513); and

.. If delivery is authorized and made by way of documents of title otherwise than by subsection (b) of this section then payment is due regardless of where the goods are to be received (i) at the time and place at which the buyer is to receive delivery of the tangible documents or (ii) at the time the buyer is to receive delivery of the electronic documents and at the seller's place of business or if none, the seller's residence; and

.. Where the seller is required or authorized to ship the goods on credit the credit period runs from the time of shipment but post-dating the invoice or delaying its dispatch will correspondingly delay the starting of the credit period.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20804[2012 c 214 § 804]; 1965 ex.s. c 157 § 2-310. Cf. former RCW sections:  RCW  63.04.430; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2042[1925 ex.s. c 142 § 42]; RRS § 5836-42.  RCW  63.04.470; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2046[1925 ex.s. c 142 § 46]; RRS § 5836-46. (iii) RCW  63.04.480; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2047[1925 ex.s. c 142 § 47]; RRS § 5836-47; ]

== 62A.2-311 - Options and cooperation respecting performance.
. An agreement for sale which is otherwise sufficiently definite (RCW 62A.2-204(3)) to be a contract is not made invalid by the fact that it leaves particulars of performance to be specified by one of the parties. Any such specification must be made in good faith and within limits set by commercial reasonableness.

. Unless otherwise agreed, specifications relating to assortment of the goods are at the buyer's option and except as otherwise provided in RCW 62A.2-319 (1)(c) and (3) specifications or arrangements relating to shipment are at the seller's option.

. Where such specification would materially affect the other party's performance but is not seasonably made or where one party's cooperation is necessary to the agreed performance of the other but is not seasonably forthcoming, the other party in addition to all other remedies:

.. Is excused for any resulting delay in his or her own performance; and

.. May also either proceed to perform in any reasonable manner or after the time for a material part of his or her own performance treat the failure to specify or to cooperate as a breach by failure to deliver or accept the goods.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20131[2013 c 23 § 131]; 1965 ex.s. c 157 § 2-311; ]

== 62A.2-312 - Warranty of title and against infringement; buyer's obligation against infringement.
. Subject to subsection (2) of this section, there is in a contract for sale a warranty by the seller that:

.. The title conveyed shall be good, and its transfer rightful; and

.. The goods shall be delivered free from any security interest or other lien or encumbrance of which the buyer at the time of contracting has no knowledge.

. A warranty under subsection (1) of this section will be excluded or modified only by specific language or by circumstances which give the buyer reason to know that the person selling does not claim title in himself or herself or that he or she is purporting to sell only such right or title as he or she or a third person may have.

. Unless otherwise agreed, a seller who is a merchant regularly dealing in goods of the kind warrants that the goods shall be delivered free of the rightful claim of any third person by way of infringement or the like but a buyer who furnishes specifications to the seller must hold the seller harmless against any such claim which arises out of compliance with the specifications.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20132[2013 c 23 § 132]; 1965 ex.s. c 157 § 2-312. Cf. former RCW  63.04.140; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2013[1925 ex.s. c 142 § 13]; RRS § 5836-13; ]

== 62A.2-313 - Express warranties by affirmation, promise, description, sample.
. Express warranties by the seller are created as follows:

.. Any affirmation of fact or promise made by the seller to the buyer which relates to the goods and becomes part of the basis of the bargain creates an express warranty that the goods shall conform to the affirmation or promise.

.. Any description of the goods which is made part of the basis of the bargain creates an express warranty that the goods shall conform to the description.

.. Any sample or model which is made part of the basis of the bargain creates an express warranty that the whole of the goods shall conform to the sample or model.

. It is not necessary to the creation of an express warranty that the seller use formal words such as "warrant" or "guarantee" or that he or she have a specific intention to make a warranty, but an affirmation merely of the value of the goods or a statement purporting to be merely the seller's opinion or commendation of the goods does not create a warranty.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20133[2013 c 23 § 133]; 1965 ex.s. c 157 § 2-313. Cf. former RCW sections:  RCW  63.04.130; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2012[1925 ex.s. c 142 § 12]; RRS § 5836-12.  RCW  63.04.150; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2014[1925 ex.s. c 142 § 14]; RRS § 5836-14. (iii) RCW  63.04.170; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2016[1925 ex.s. c 142 § 16]; RRS § 5836-16; ]

== 62A.2-314 - Implied warranty: Merchantability; usage of trade.
. Unless excluded or modified (RCW 62A.2-316), a warranty that the goods shall be merchantable is implied in a contract for their sale if the seller is a merchant with respect to goods of that kind. Under this section the serving for value of food or drink to be consumed either on the premises or elsewhere is a sale.

. Goods to be merchantable must be at least such as

.. pass without objection in the trade under the contract description; and

.. in the case of fungible goods, are of fair average quality within the description; and

.. are fit for the ordinary purposes for which such goods are used; and

.. run, within the variations permitted by the agreement, of even kind, quality and quantity within each unit and among all units involved; and

.. are adequately contained, packaged, and labeled as the agreement may require; and

.. conform to the promises or affirmations of fact made on the container or label if any.

. Unless excluded or modified (RCW 62A.2-316) other implied warranties may arise from course of dealing or usage of trade.

[ 1965 ex.s. c 157 § 2-314. Cf. former RCW  63.04.160; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2015[1925 ex.s. c 142 § 15]; RRS § 5836-15; ]

== 62A.2-315 - Implied warranty: Fitness for particular purpose.
Where the seller at the time of contracting has reason to know any particular purpose for which the goods are required and that the buyer is relying on the seller's skill or judgment to select or furnish suitable goods, there is unless excluded or modified under the next section an implied warranty that the goods shall be fit for such purpose.

[ 1965 ex.s. c 157 § 2-315. Cf. former RCW  63.04.160, (4), (5); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2015[1925 ex.s. c 142 § 15]; RRS § 5836-15; ]

== 62A.2-316 - Exclusion or modification of warranties.
. Words or conduct relevant to the creation of an express warranty and words or conduct tending to negate or limit warranty shall be construed wherever reasonable as consistent with each other; but subject to the provisions of this Article on parol or extrinsic evidence (RCW 62A.2-202) negation or limitation is inoperative to the extent that such construction is unreasonable.

. Subject to subsection (3) of this section, to exclude or modify the implied warranty of merchantability or any part of it the language must mention merchantability and in case of a writing must be conspicuous, and to exclude or modify any implied warranty of fitness the exclusion must be by a writing and conspicuous. Language to exclude all implied warranties of fitness is sufficient if it states, for example, that "There are no warranties which extend beyond the description on the face hereof."

. Notwithstanding subsection (2) of this section:

.. Unless the circumstances indicate otherwise, all implied warranties are excluded by expressions like "as is," "with all faults," or other language which in common understanding calls the buyer's attention to the exclusion of warranties and makes plain that there is no implied warranty; and

.. When the buyer before entering into the contract has examined the goods or the sample or model as fully as he or she desired or has refused to examine the goods there is no implied warranty with regard to defects which an examination ought in the circumstances to have revealed to him or her;

.. An implied warranty can also be excluded or modified by course of dealing or course of performance or usage of trade; and

.. In sales of livestock, including but not limited to, horses, mules, cattle, sheep, swine, goats, poultry, and rabbits, there are no implied warranties as defined in this article that the livestock are free from sickness or disease: PROVIDED, That the seller has complied with all state and federal laws and regulations that apply to animal health and disease, and the seller is not guilty of fraud, deceit, or misrepresentation.

. Notwithstanding the provisions of subsections (2) and (3) of this section and the provisions of RCW 62A.2-719, as now or hereafter amended, in any case where goods are purchased primarily for personal, family, or household use and not for commercial or business use, disclaimers of the warranty of merchantability or fitness for particular purpose shall not be effective to limit the liability of merchant sellers except insofar as the disclaimer sets forth with particularity the qualities and characteristics which are not being warranted. Remedies for breach of warranty can be limited in accordance with the provisions of this Article on liquidation or limitation of damages and on contractual modification of remedy (RCW 62A.2-718 and RCW 62A.2-719).

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20134[2013 c 23 § 134]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c199.pdf?cite=1982%20c%20199%20§%201[1982 c 199 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c180.pdf?cite=1974%20ex.s.%20c%20180%20§%201[1974 ex.s. c 180 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c78.pdf?cite=1974%20ex.s.%20c%2078%20§%201[1974 ex.s. c 78 § 1]; 1965 ex.s. c 157 § 2-316. Subd. (3)(b) cf. former RCW  63.04.160(3); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2015[1925 ex.s. c 142 § 15]; RRS § 5836-15. Subd. (3)(c) cf. former RCW  63.04.720; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2071[1925 ex.s. c 142 § 71]; RRS § 5836-71; ]

== 62A.2-317 - Cumulation and conflict of warranties express or implied.
Warranties whether express or implied shall be construed as consistent with each other and as cumulative, but if such construction is unreasonable the intention of the parties shall determine which warranty is dominant. In ascertaining that intention the following rules apply:

.. Exact or technical specifications displace an inconsistent sample or model or general language of description.

.. A sample from an existing bulk displaces inconsistent general language of description.

.. Express warranties displace inconsistent implied warranties other than an implied warranty of fitness for a particular purpose.

[ 1965 ex.s. c 157 § 2-317. Cf. former RCW sections: RCW  63.04.150 through  63.04.170; 1925 ex.s. c 142 §§ 14 through 16; RRS §§ 5836-14 through 5836-16; ]

== 62A.2-318 - Third-party beneficiaries of warranties express or implied.
A seller's warranty whether express or implied extends to any natural person who is in the family or household of his or her buyer or who is a guest in his or her home if it is reasonable to expect that such person may use, consume, or be affected by the goods and who is injured in person by breach of the warranty. A seller may not exclude or limit the operation of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20135[2013 c 23 § 135]; 1965 ex.s. c 157 § 2-318; ]

== 62A.2-319 - F.O.B. and F.A.S. terms.
. Unless otherwise agreed, the term F.O.B. (which means "free on board") at a named place, even though used only in connection with the stated price, is a delivery term under which:

.. When the term is F.O.B. the place of shipment, the seller must at that place ship the goods in the manner provided in this Article (RCW 62A.2-504) and bear the expense and risk of putting them into the possession of the carrier; or

.. When the term is F.O.B. the place of destination, the seller must at his or her own expense and risk transport the goods to that place and there tender delivery of them in the manner provided in this Article (RCW 62A.2-503);

.. When under either (a) or (b) of this subsection the term is also F.O.B. vessel, car, or other vehicle, the seller must in addition at his or her own expense and risk load the goods on board. If the term is F.O.B. vessel, the buyer must name the vessel and in an appropriate case the seller must comply with the provisions of this Article on the form of bill of lading (RCW 62A.2-323).

. Unless otherwise agreed the term F.A.S. vessel (which means "free alongside") at a named port, even though used only in connection with the stated price, is a delivery term under which the seller must:

.. At his or her own expense and risk deliver the goods alongside the vessel in the manner usual in that port or on a dock designated and provided by the buyer; and

.. Obtain and tender a receipt for the goods in exchange for which the carrier is under a duty to issue a bill of lading.

. Unless otherwise agreed, in any case falling within subsection (1)(a) or (c) or (2) of this section, the buyer must seasonably give any needed instructions for making delivery, including when the term is F.A.S. or F.O.B. the loading berth of the vessel and in an appropriate case its name and sailing date. The seller may treat the failure of needed instructions as a failure of cooperation under this Article (RCW 62A.2-311). He or she may also at his or her option move the goods in any reasonable manner preparatory to delivery or shipment.

. Under the term F.O.B. vessel or F.A.S., unless otherwise agreed, the buyer must make payment against tender of the required documents and the seller may not tender nor the buyer demand delivery of the goods in substitution for the documents.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20136[2013 c 23 § 136]; 1965 ex.s. c 157 § 2-319; ]

== 62A.2-320 - C.I.F. and C.&F. terms.
. The term C.I.F. means that the price includes in a lump sum the cost of the goods and the insurance and freight to the named destination. The term C.&F. or C.F. means that the price so includes cost and freight to the named destination.

. Unless otherwise agreed and even though used only in connection with the stated price and destination, the term C.I.F. destination or its equivalent requires the seller at his or her own expense and risk to:

.. Put the goods into the possession of a carrier at the port for shipment and obtain a negotiable bill or bills of lading covering the entire transportation to the named destination; and

.. Load the goods and obtain a receipt from the carrier (which may be contained in the bill of lading) showing that the freight has been paid or provided for; and

.. Obtain a policy or certificate of insurance, including any war risk insurance, of a kind and on terms then current at the port of shipment in the usual amount, in the currency of the contract, shown to cover the same goods covered by the bill of lading and providing for payment of loss to the order of the buyer or for the account of whom it may concern; but the seller may add to the price the amount of the premium for any such war risk insurance; and

.. Prepare an invoice of the goods and procure any other documents required to effect shipment or to comply with the contract; and

.. Forward and tender with commercial promptness all the documents in due form and with any indorsement necessary to perfect the buyer's rights.

. Unless otherwise agreed, the term C.&F. or its equivalent has the same effect and imposes upon the seller the same obligations and risks as a C.I.F. term except the obligation as to insurance.

. Under the term C.I.F. or C.&F., unless otherwise agreed, the buyer must make payment against tender of the required documents and the seller may not tender nor the buyer demand delivery of the goods in substitution for the documents.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20137[2013 c 23 § 137]; 1965 ex.s. c 157 § 2-320; ]

== 62A.2-321 - C.I.F. or C.&F.:  "Net landed weights"; "payment on arrival"; warranty of condition on arrival.
Under a contract containing a term C.I.F. or C.&F.

. Where the price is based on or is to be adjusted according to "net landed weights", "delivered weights", "out turn" quantity or quality or the like, unless otherwise agreed the seller must reasonably estimate the price. The payment due on tender of the documents called for by the contract is the amount so estimated, but after final adjustment of the price a settlement must be made with commercial promptness.

. An agreement described in subsection (1) or any warranty of quality or condition of the goods on arrival places upon the seller the risk of ordinary deterioration, shrinkage and the like in transportation but has no effect on the place or time of identification to the contract for sale or delivery or on the passing of the risk of loss.

. Unless otherwise agreed where the contract provides for payment on or after arrival of the goods the seller must before payment allow such preliminary inspection as is feasible; but if the goods are lost delivery of the documents and payment are due when the goods should have arrived.

[ 1965 ex.s. c 157 § 2-321; ]

== 62A.2-322 - Delivery "ex-ship".
. Unless otherwise agreed a term for delivery of goods "ex-ship" (which means from the carrying vessel) or in equivalent language is not restricted to a particular ship and requires delivery from a ship which has reached a place at the named port of destination where goods of the kind are usually discharged.

. Under such a term unless otherwise agreed

.. the seller must discharge all liens arising out of the carriage and furnish the buyer with a direction which puts the carrier under a duty to deliver the goods; and

.. the risk of loss does not pass to the buyer until the goods leave the ship's tackle or are otherwise properly unloaded.

[ 1965 ex.s. c 157 § 2-322; ]

== 62A.2-323 - Form of bill of lading required in overseas shipment; "overseas".
. Where the contract contemplates overseas shipment and contains a term C.I.F. or C.&F. or F.O.B. vessel, the seller unless otherwise agreed must obtain a negotiable bill of lading stating that the goods have been loaded on board or, in the case of a term C.I.F. or C.&F., received for shipment.

. Where in a case within subsection (1) of this section a tangible bill of lading has been issued in a set of parts, unless otherwise agreed if the documents are not to be sent from abroad the buyer may demand tender of the full set; otherwise only one part of the bill of lading need be tendered. Even if the agreement expressly requires a full set:

.. Due tender of a single part is acceptable within the provisions of this Article on cure of improper delivery (RCW 62A.2-508(1)); and

.. Even though the full set is demanded, if the documents are sent from abroad the person tendering an incomplete set may nevertheless require payment upon furnishing an indemnity which the buyer in good faith deems adequate.

. A shipment by water or by air or a contract contemplating such shipment is "overseas" insofar as by usage of trade or agreement it is subject to the commercial, financing or shipping practices characteristic of international deep water commerce.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20805[2012 c 214 § 805]; 1965 ex.s. c 157 § 2-323; ]

== 62A.2-324 - "No arrival, no sale" term.
Under a term "no arrival, no sale" or terms of like meaning, unless otherwise agreed:

.. The seller must properly ship conforming goods and if they arrive by any means he or she must tender them on arrival but he or she assumes no obligation that the goods will arrive unless he or she has caused the nonarrival; and

.. Where without fault of the seller the goods are in part lost or have so deteriorated as no longer to conform to the contract or arrive after the contract time, the buyer may proceed as if there had been casualty to identified goods (RCW 62A.2-613).

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20138[2013 c 23 § 138]; 1965 ex.s. c 157 § 2-324; ]

== 62A.2-325 - "Letter of credit" term; "confirmed credit".
. Failure of the buyer seasonably to furnish an agreed letter of credit is a breach of the contract for sale.

. The delivery to seller of a proper letter of credit suspends the buyer's obligation to pay. If the letter of credit is dishonored, the seller may on seasonable notification to the buyer require payment directly from him or her.

. Unless otherwise agreed, the term "letter of credit" or "banker's credit" in a contract for sale means an irrevocable credit issued by a financing agency of good repute and, where the shipment is overseas, of good international repute. The term "confirmed credit" means that the credit must also carry the direct obligation of such an agency which does business in the seller's financial market.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20139[2013 c 23 § 139]; 1965 ex.s. c 157 § 2-325; ]

== 62A.2-326 - Sale on approval and sale or return; rights of creditors.
. Unless otherwise agreed, if delivered goods may be returned by the buyer even though they conform to the contract, the transaction is

.. a "sale on approval" if the goods are delivered primarily for use, and

.. a "sale or return" if the goods are delivered primarily for resale.

. Goods held on approval are not subject to the claims of the buyer's creditors until acceptance; goods held on sale or return are subject to such claims while in the buyer's possession.

. Any "or return" term of a contract for sale is to be treated as a separate contract for sale within the statute of frauds section of this Article (RCW 62A.2-201) and as contradicting the sale aspect of the contract within the provisions of this Article on parol or extrinsic evidence (RCW 62A.2-202).

[ 2000 c 250 § 9A-805; 1965 ex.s. c 157 § 2-326. Cf. former RCW  63.04.200(3); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2019[1925 ex.s. c 142 § 19]; RRS § 5836-19; ]

== 62A.2-327 - Special incidents of sale on approval and sale or return.
. Under a sale on approval unless otherwise agreed

.. although the goods are identified to the contract the risk of loss and the title do not pass to the buyer until acceptance; and

.. use of the goods consistent with the purpose of trial is not acceptance but failure seasonably to notify the seller of election to return the goods is acceptance, and if the goods conform to the contract acceptance of any part is acceptance of the whole; and

.. after due notification of election to return, the return is at the seller's risk and expense but a merchant buyer must follow any reasonable instructions.

. Under a sale or return unless otherwise agreed

.. the option to return extends to the whole or any commercial unit of the goods while in substantially their original condition, but must be exercised seasonably; and

.. the return is at the buyer's risk and expense.

[ 1965 ex.s. c 157 § 2-327. Cf. former RCW  63.04.200(3); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2019[1925 ex.s. c 142 § 19]; RRS § 5836-19; ]

== 62A.2-328 - Sale by auction.
. In a sale by auction if goods are put up in lots each lot is the subject of a separate sale.

. A sale by auction is complete when the auctioneer so announces by the fall of the hammer or in other customary manner. Where a bid is made while the hammer is falling in acceptance of a prior bid the auctioneer may in his or her discretion reopen the bidding or declare the goods sold under the bid on which the hammer was falling.

. Such a sale is with reserve unless the goods are in explicit terms put up without reserve. In an auction with reserve, the auctioneer may withdraw the goods at any time until he or she announces completion of the sale. In an auction without reserve, after the auctioneer calls for bids on an article or lot, that article or lot cannot be withdrawn unless no bid is made within a reasonable time. In either case a bidder may retract his or her bid until the auctioneer's announcement of completion of the sale, but a bidder's retraction does not revive any previous bid.

. If the auctioneer knowingly receives a bid on the seller's behalf or the seller makes or procures such a bid, and notice has not been given that liberty for such bidding is reserved, the buyer may at his or her option avoid the sale or take the goods at the price of the last good faith bid prior to the completion of the sale. This subsection shall not apply to any bid at a forced sale.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20140[2013 c 23 § 140]; 1965 ex.s. c 157 § 2-328. Cf. former RCW  63.04.220; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2021[1925 ex.s. c 142 § 21]; RRS § 5836-21; ]

== 62A.2-401 - Passing of title; reservation for security; limited application of this section.
Each provision of this Article with regard to the rights, obligations and remedies of the seller, the buyer, purchasers or other third parties applies irrespective of title to the goods except where the provision refers to such title. Insofar as situations are not covered by the other provisions of this Article and matters concerning title become material the following rules apply:

. Title to goods cannot pass under a contract for sale prior to their identification to the contract (RCW 62A.2-501), and unless otherwise explicitly agreed the buyer acquires by their identification a special property as limited by this title. Any retention or reservation by the seller of the title (property) in goods shipped or delivered to the buyer is limited in effect to a reservation of a security interest. Subject to these provisions and to the provisions of the Article on Secured Transactions (Article 9A), title to goods passes from the seller to the buyer in any manner and on any conditions explicitly agreed on by the parties.

. Unless otherwise explicitly agreed title passes to the buyer at the time and place at which the seller completes his or her performance with reference to the physical delivery of the goods, despite any reservation of a security interest and even though a document of title is to be delivered at a different time or place; and in particular and despite any reservation of a security interest by the bill of lading:

.. If the contract requires or authorizes the seller to send the goods to the buyer but does not require him or her to deliver them at destination, title passes to the buyer at the time and place of shipment; but

.. If the contract requires delivery at destination, title passes on tender there.

. Unless otherwise explicitly agreed where delivery is to be made without moving the goods:

.. If the seller is to deliver a tangible document of title, title passes at the time when and the place where he or she delivers such documents and if the seller is to deliver an electronic document of title, title passes when the seller delivers the document; or

.. If the goods are at the time of contracting already identified and no documents of title are to be delivered, title passes at the time and place of contracting.

. A rejection or other refusal by the buyer to receive or retain the goods, whether or not justified, or a justified revocation of acceptance revests title to the goods in the seller. Such revesting occurs by operation of law and is not a "sale."

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20806[2012 c 214 § 806]; 1965 ex.s. c 157 § 2-401. Cf. former RCW sections: RCW  63.04.180 through  63.04.210; 1925 ex.s. c 142 §§ 17 through 20; RRS § 5836-17 through 5836-20; ]

== 62A.2-402 - Rights of seller's creditors against sold goods.
. Except as provided in subsections (2) and (3) of this section, rights of unsecured creditors of the seller with respect to goods which have been identified to a contract for sale are subject to the buyer's rights to recover the goods under this Article (RCW 62A.2-502 and RCW 62A.2-716).

. A creditor of the seller may treat a sale or an identification of goods to a contract for sale as void if as against him or her a retention of possession by the seller is fraudulent under any rule of law of the state where the goods are situated, except that retention of possession in good faith and current course of trade by a merchant-seller for a commercially reasonable time after a sale or identification is not fraudulent.

. Nothing in this Article shall be deemed to impair the rights of creditors of the seller:

.. Under the provisions of the Article on Secured Transactions (Article 9A); or

.. Where identification to the contract or delivery is made not in current course of trade but in satisfaction of or as security for a preexisting claim for money, security, or the like and is made under circumstances which under any rule of law of the state where the goods are situated would apart from this Article constitute the transaction a fraudulent transfer or voidable preference.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20141[2013 c 23 § 141]; 1965 ex.s. c 157 § 2-402. Subd.  cf. former RCW sections:  RCW  63.04.270; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2026[1925 ex.s. c 142 § 26]; RRS § 5836-26.  RCW  63.08.040; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c247.pdf?cite=1953%20c%20247%20§%203[1953 c 247 § 3]; 1943 c 98 § 1, part; 1939 c 122 § 1, part; 1925 ex.s. c 135 § 2, part; Rem. Supp. 1943 § 5832, part; prior: 1901 c 109 § 1, part; ]

== 62A.2-403 - Power to transfer; good faith purchase of goods; "entrusting".
. A purchaser of goods acquires all title which his or her transferor had or had power to transfer except that a purchaser of a limited interest acquires rights only to the extent of the interest purchased. A person with voidable title has power to transfer a good title to a good faith purchaser for value. When goods have been delivered under a transaction of purchase the purchaser has such power even though

.. the transferor was deceived as to the identity of the purchaser, or

.. the delivery was in exchange for a check which is later dishonored, or

.. it was agreed that the transaction was to be a "cash sale".

. Any entrusting of possession of goods to a merchant who deals in goods of that kind gives him or her power to transfer all rights of the entruster to a buyer in ordinary course of business.

. "Entrusting" includes any delivery and any acquiescence in retention of possession regardless of any condition expressed between the parties to the delivery or acquiescence and regardless of whether the procurement of the entrusting or the possessor's disposition of the goods have been such as to be larcenous under the criminal law.

. The rights of other purchasers of goods and of lien creditors are governed by the Articles on Secured Transactions (*Article 9) and Documents of Title (Article 7).

[ 1993 c 395 § 6-103; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c114.pdf?cite=1967%20c%20114%20§%208[1967 c 114 § 8]; 1965 ex.s. c 157 § 2-403. Cf. former RCW sections:  RCW  61.20.090; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c71.pdf?cite=1943%20c%2071%20§%209[1943 c 71 § 9]; Rem. Supp. 1943 § 11548-38.  RCW  63.04.210(4); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2020[1925 ex.s. c 142 § 20]; RRS § 5836-20. (iii) RCW  63.04.240; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2023[1925 ex.s. c 142 § 23]; RRS § 5836-23. (iv) RCW  63.04.250; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2024[1925 ex.s. c 142 § 24]; RRS § 5836-24. (v) RCW  63.04.260; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2025[1925 ex.s. c 142 § 25]; RRS § 5836-25. (vi) RCW  65.08.040; Code 1881 § 2327; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1863%20p%20413%20§%204[1863 p 413 § 4]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1854%20p%20404%20§%204[1854 p 404 § 4]; RRS § 5827; ]

== 62A.2-501 - Insurable interest in goods; manner of identification of goods.
. The buyer obtains a special property and an insurable interest in goods by identification of existing goods as goods to which the contract refers even though the goods so identified are nonconforming and he or she has an option to return or reject them. Such identification can be made at any time and in any manner explicitly agreed to by the parties. In the absence of explicit agreement, identification occurs:

.. When the contract is made if it is for the sale of goods already existing and identified;

.. If the contract is for the sale of future goods other than those described in (c) of this subsection, when goods are shipped, marked, or otherwise designated by the seller as goods to which the contract refers;

.. When the crops are planted or otherwise become growing crops or the young are conceived if the contract is for the sale of unborn young to be born within twelve months after contracting or for the sale of crops to be harvested within twelve months or the next normal harvest season after contracting whichever is longer.

. The seller retains an insurable interest in goods so long as title to or any security interest in the goods remains in him or her and where the identification is by the seller alone he or she may until default or insolvency or notification to the buyer that the identification is final substitute other goods for those identified.

. Nothing in this section impairs any insurable interest recognized under any other statute or rule of law.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20142[2013 c 23 § 142]; 1965 ex.s. c 157 § 2-501. Cf. former RCW sections:  RCW  63.04.180; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2017[1925 ex.s. c 142 § 17]; RRS § 5836-17.  RCW  63.04.200; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2019[1925 ex.s. c 142 § 19]; RRS § 5836-19; ]

== 62A.2-502 - Buyer's right to goods on seller's insolvency.
. Subject to subsections (2) and (3) of this section and even though the goods have not been shipped, a buyer who has paid a part or all of the price of goods in which he or she has a special property under the provisions of the immediately preceding section may on making and keeping good a tender of any unpaid portion of their price recover them from the seller if:

.. In the case of goods bought for personal, family, or household purposes, the seller repudiates or fails to deliver as required by the contract; or

.. In all cases, the seller becomes insolvent within ten days after receipt of the first installment on their price.

. The buyer's right to recover the goods under subsection (1)(a) of this section vests upon acquisition of a special property, even if the seller had not then repudiated or failed to deliver.

. If the identification creating his or her special property has been made by the buyer, he or she acquires the right to recover the goods only if they conform to the contract for sale.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20143[2013 c 23 § 143]; 2000 c 250 § 9A-806; 1965 ex.s. c 157 § 2-502. Cf. former RCW sections: RCW  63.04.180 through  63.04.200; 1925 ex.s. c 142 §§ 17 through 19; RRS §§ 5836-17 through 5836-19; ]

== 62A.2-503 - Manner of seller's tender of delivery.
. Tender of delivery requires that the seller put and hold conforming goods at the buyer's disposition and give the buyer any notification reasonably necessary to enable him or her to take delivery. The manner, time and place for tender are determined by the agreement and this Article, and in particular:

.. Tender must be at a reasonable hour, and if it is of goods they must be kept available for the period reasonably necessary to enable the buyer to take possession; but

.. Unless otherwise agreed the buyer must furnish facilities reasonably suited to the receipt of the goods.

. Where the case is within the next section respecting shipment tender requires that the seller comply with its provisions.

. Where the seller is required to deliver at a particular destination tender requires that he or she comply with subsection (1) of this section and also in any appropriate case tender documents as described in subsections (4) and (5) of this section.

. Where goods are in the possession of a bailee and are to be delivered without being moved:

.. Tender requires that the seller either tender a negotiable document of title covering such goods or procure acknowledgment by the bailee of the buyer's right to possession of the goods; but

.. Tender to the buyer of a nonnegotiable document of title or of a record directing the bailee to deliver is sufficient tender unless the buyer seasonably objects, and except as otherwise provided in Article 9A of this title, receipt by the bailee of notification of the buyer's rights fixes those rights as against the bailee and all third persons; but risk of loss of the goods and of any failure by the bailee to honor the nonnegotiable document of title or to obey the direction remains on the seller until the buyer has had a reasonable time to present the document or direction, and a refusal by the bailee to honor the document or to obey the direction defeats the tender.

. Where the contract requires the seller to deliver documents:

.. He or she must tender all such documents in correct form, except as provided in this Article with respect to bills of lading in a set (RCW 62A.2-323(2)); and

.. Tender through customary banking channels is sufficient and dishonor of a draft accompanying or associated with the documents constitutes nonacceptance or rejection.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20807[2012 c 214 § 807]; 1965 ex.s. c 157 § 2-503. Cf. former RCW sections: RCW  63.04.120,  63.04.200,  63.04.210,  63.04.440,  63.04.470, and  63.04.520; 1925 ex.s. c 142 §§ 11, 19, 20, 43, 46, and 51; RRS §§ 5836-11, 5836-19, 5836-20, 5836-43, 5836-46, and 5836-51; ]

== 62A.2-504 - Shipment by seller.
Where the seller is required or authorized to send the goods to the buyer and the contract does not require him or her to deliver them at a particular destination, then unless otherwise agreed he or she must:

.. Put the goods in the possession of such a carrier and make such a contract for their transportation as may be reasonable having regard to the nature of the goods and other circumstances of the case; and

.. Obtain and promptly deliver or tender in due form any document necessary to enable the buyer to obtain possession of the goods or otherwise required by the agreement or by usage of trade; and

.. Promptly notify the buyer of the shipment. Failure to notify the buyer under this subsection or to make a proper contract under subsection (a) of this section is a ground for rejection only if material delay or loss ensues.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20144[2013 c 23 § 144]; 1965 ex.s. c 157 § 2-504. Cf. former RCW  63.04.470; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2046[1925 ex.s. c 142 § 46]; RRS § 5836-46; ]

== 62A.2-505 - Seller's shipment under reservation.
. Where the seller has identified goods to the contract by or before shipment:

.. His or her procurement of a negotiable bill of lading to his or her own order or otherwise reserves in him or her a security interest in the goods. His or her procurement of the bill to the order of a financing agency or of the buyer indicates in addition only the seller's expectation of transferring that interest to the person named.

.. A nonnegotiable bill of lading to himself or herself or his or her nominee reserves possession of the goods as security but except in a case of conditional delivery (RCW 62A.2-507(2)) a nonnegotiable bill of lading naming the buyer as consignee reserves no security interest even though the seller retains possession or control of the bill of lading.

. When shipment by the seller with reservation of a security interest is in violation of the contract for sale it constitutes an improper contract for transportation within the preceding section but impairs neither the rights given to the buyer by shipment and identification of the goods to the contract nor the seller's powers as a holder of a negotiable document of title.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20808[2012 c 214 § 808]; 1965 ex.s. c 157 § 2-505. Cf. former RCW  63.04.210 , (3), (4); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2020[1925 ex.s. c 142 § 20]; RRS § 5836-20; ]

== 62A.2-506 - Rights of financing agency.
. A financing agency by paying or purchasing for value a draft which relates to a shipment of goods acquires to the extent of the payment or purchase and in addition to its own rights under the draft and any document of title securing it any rights of the shipper in the goods including the right to stop delivery and the shipper's right to have the draft honored by the buyer.

. The right to reimbursement of a financing agency which has in good faith honored or purchased the draft under commitment to or authority from the buyer is not impaired by subsequent discovery of defects with reference to any relevant document which was apparently regular.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20809[2012 c 214 § 809]; 1965 ex.s. c 157 § 2-506; ]

== 62A.2-507 - Effect of seller's tender; delivery on condition.
. Tender of delivery is a condition to the buyer's duty to accept the goods and, unless otherwise agreed, to his or her duty to pay for them. Tender entitles the seller to acceptance of the goods and to payment according to the contract.

. Where payment is due and demanded on the delivery to the buyer of goods or documents of title, his or her right as against the seller to retain or dispose of them is conditional upon his or her making the payment due.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20145[2013 c 23 § 145]; 1965 ex.s. c 157 § 2-507. Cf. former RCW sections:  RCW  63.04.120; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2011[1925 ex.s. c 142 § 11]; RRS § 5836-11.  RCW  63.04.420; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2041[1925 ex.s. c 142 § 41]; RRS § 5836-41. (iii) RCW  63.04.430; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2042[1925 ex.s. c 142 § 42]; RRS § 5836-42. (iv) RCW  63.04.700; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2069[1925 ex.s. c 142 § 69]; RRS § 5836-69; ]

== 62A.2-508 - Cure by seller of improper tender or delivery; replacement.
. Where any tender or delivery by the seller is rejected because nonconforming and the time for performance has not yet expired, the seller may seasonably notify the buyer of his or her intention to cure and may then within the contract time make a conforming delivery.

. Where the buyer rejects a nonconforming tender which the seller had reasonable grounds to believe would be acceptable with or without money allowance, the seller may if he or she seasonably notifies the buyer have a further reasonable time to substitute a conforming tender.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20146[2013 c 23 § 146]; 1965 ex.s. c 157 § 2-508; ]

== 62A.2-509 - Risk of loss in the absence of breach.
. Where the contract requires or authorizes the seller to ship the goods by carrier:

.. If it does not require him or her to deliver them at a particular destination, the risk of loss passes to the buyer when the goods are duly delivered to the carrier even though the shipment is under reservation (RCW 62A.2-505); but

.. If it does require him or her to deliver them at a particular destination and the goods are there duly tendered while in the possession of the carrier, the risk of loss passes to the buyer when the goods are there duly so tendered as to enable the buyer to take delivery.

. Where the goods are held by a bailee to be delivered without being moved, the risk of loss passes to the buyer:

.. On his or her receipt of possession or control of a negotiable document of title covering the goods; or

.. On acknowledgment by the bailee of the buyer's right to possession of the goods; or

.. After his or her receipt of possession or control of a nonnegotiable document of title or other direction to deliver in a record, as provided in RCW 62A.2-503(4)(b).

. In any case not within subsection (1) or (2) of this section, the risk of loss passes to the buyer on his or her receipt of the goods if the seller is a merchant; otherwise the risk passes to the buyer on tender of delivery.

. The provisions of this section are subject to contrary agreement of the parties and to the provisions of this Article on sale on approval (RCW 62A.2-327) and on effect of breach on risk of loss (RCW 62A.2-510).

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20810[2012 c 214 § 810]; 1965 ex.s. c 157 § 2-509. Cf. former RCW sections:  RCW  63.04.200; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2019[1925 ex.s. c 142 § 19]; RRS § 5836-19.  RCW  63.04.230; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2022[1925 ex.s. c 142 § 22]; RRS § 5836-22; ]

== 62A.2-510 - Effect of breach on risk of loss.
. Where a tender or delivery of goods so fails to conform to the contract as to give a right of rejection, the risk of their loss remains on the seller until cure or acceptance.

. Where the buyer rightfully revokes acceptance, he or she may to the extent of any deficiency in his or her effective insurance coverage treat the risk of loss as having rested on the seller from the beginning.

. Where the buyer as to conforming goods already identified to the contract for sale repudiates or is otherwise in breach before risk of their loss has passed to him or her, the seller may to the extent of any deficiency in his or her effective insurance coverage treat the risk of loss as resting on the buyer for a commercially reasonable time.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20147[2013 c 23 § 147]; 1965 ex.s. c 157 § 2-510; ]

== 62A.2-511 - Tender of payment by buyer; payment by check.
. Unless otherwise agreed tender of payment is a condition to the seller's duty to tender and complete any delivery.

. Tender of payment is sufficient when made by any means or in any manner current in the ordinary course of business unless the seller demands payment in legal tender and gives any extension of time reasonably necessary to procure it.

. Subject to the provisions of this Title on the effect of an instrument on an obligation (RCW 62A.3-310), payment by check is conditional and is defeated as between the parties by dishonor of the check on due presentment.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1182-S2.SL.pdf?cite=1996%20c%2077%20§%202[1996 c 77 § 2]; 1965 ex.s. c 157 § 2-511. Cf. former RCW  63.04.430; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2042[1925 ex.s. c 142 § 42]; RRS § 5836-42; ]

== 62A.2-512 - Payment by buyer before inspection.
. Where the contract requires payment before inspection non-conformity of the goods does not excuse the buyer from so making payment unless

.. the non-conformity appears without inspection; or

.. despite tender of the required documents the circumstances would justify injunction against honor under the provisions of this Title (RCW 62A.5-109(b)).

. Payment pursuant to subsection (1) does not constitute an acceptance of goods or impair the buyer's right to inspect or any of his or her remedies.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%201715[2012 c 214 § 1715]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1799-S.SL.pdf?cite=1997%20c%2056%20§%2020[1997 c 56 § 20]; 1965 ex.s. c 157 § 2-512. Cf. former RCW sections:  RCW  63.04.480; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2047[1925 ex.s. c 142 § 47]; RRS § 5836-47.  RCW  63.04.500; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2049[1925 ex.s. c 142 § 49]; RRS § 5836-49; ]

== 62A.2-513 - Buyer's right to inspection of goods.
. Unless otherwise agreed and subject to subsection (3), where goods are tendered or delivered or identified to the contract for sale, the buyer has a right before payment or acceptance to inspect them at any reasonable place and time and in any reasonable manner. When the seller is required or authorized to send the goods to the buyer, the inspection may be after their arrival.

. Expenses of inspection must be borne by the buyer but may be recovered from the seller if the goods do not conform and are rejected.

. Unless otherwise agreed and subject to the provisions of this Article on C.I.F. contracts (subsection (3) of RCW 62A.2-321), the buyer is not entitled to inspect the goods before payment of the price when the contract provides

.. for delivery "C.O.D." or on other like terms; or

.. for payment against documents of title, except where such payment is due only after the goods are to become available for inspection.

. A place or method of inspection fixed by the parties is presumed to be exclusive but unless otherwise expressly agreed it does not postpone identification or shift the place for delivery or for passing the risk of loss. If compliance becomes impossible, inspection shall be as provided in this section unless the place or method fixed was clearly intended as an indispensable condition failure of which avoids the contract.

[ 1965 ex.s. c 157 § 2-513. Cf. former RCW  63.04.480 , (3); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2047[1925 ex.s. c 142 § 47]; RRS § 5836-47; ]

== 62A.2-514 - When documents deliverable on acceptance; when on payment.
Unless otherwise agreed documents against which a draft is drawn are to be delivered to the drawee on acceptance of the draft if it is payable more than three days after presentment; otherwise, only on payment.

[ 1965 ex.s. c 157 § 2-514. Cf. former RCW  81.32.411; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.32.411[1961 c 14 § 81.32.411]; prior:  1915 c 159 § 41; RRS § 3687; formerly RCW  81.32.500; ]

== 62A.2-515 - Preserving evidence of goods in dispute.
In furtherance of the adjustment of any claim or dispute

.. either party on reasonable notification to the other and for the purpose of ascertaining the facts and preserving evidence has the right to inspect, test and sample the goods including such of them as may be in the possession or control of the other; and

.. the parties may agree to a third party inspection or survey to determine the conformity or condition of the goods and may agree that the findings shall be binding upon them in any subsequent litigation or adjustment.

[ 1965 ex.s. c 157 § 2-515; ]

== 62A.2-601 - Buyer's rights on improper delivery.
Subject to the provisions of this Article on breach in installment contracts (RCW 62A.2-612) and unless otherwise agreed under the sections on contractual limitations of remedy (RCW 62A.2-718 and RCW 62A.2-719), if the goods or the tender of delivery fail in any respect to conform to the contract, the buyer may

.. reject the whole; or

.. accept the whole; or

.. accept any commercial unit or units and reject the rest.

[ 1965 ex.s. c 157 § 2-601. Cf. former RCW sections:  RCW  63.04.120; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2011[1925 ex.s. c 142 § 11]; RRS § 5836-11.  RCW  63.04.480; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2047[1925 ex.s. c 142 § 47]; RRS § 5836-47. (iii) RCW  63.04.700; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2069[1925 ex.s. c 142 § 69]; RRS § 5836-69; ]

== 62A.2-602 - Manner and effect of rightful rejection.
. Rejection of goods must be within a reasonable time after their delivery or tender. It is ineffective unless the buyer seasonably notifies the seller.

. Subject to the provisions of the two following sections on rejected goods (RCW 62A.2-603 and RCW 62A.2-604):

.. After rejection, any exercise of ownership by the buyer with respect to any commercial unit is wrongful as against the seller; and

.. If the buyer has before rejection taken physical possession of goods in which he or she does not have a security interest under the provisions of this Article (RCW 62A.2-711(3)), he or she is under a duty after rejection to hold them with reasonable care at the seller's disposition for a time sufficient to permit the seller to remove them; but

.. The buyer has no further obligations with regard to goods rightfully rejected.

. The seller's rights with respect to goods wrongfully rejected are governed by the provisions of this Article on seller's remedies in general (RCW 62A.2-703).

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20148[2013 c 23 § 148]; 1965 ex.s. c 157 § 2-602. Cf. former RCW sections:  RCW  63.04.090; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%208[1925 ex.s. c 142 § 8]; RRS § 5836-8.  RCW  63.04.510; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2050[1925 ex.s. c 142 § 50]; RRS § 5836-50; ]

== 62A.2-603 - Merchant buyer's duties as to rightfully rejected goods.
. Subject to any security interest in the buyer (RCW 62A.2-711(3)), when the seller has no agent or place of business at the market of rejection a merchant buyer is under a duty after rejection of goods in his or her possession or control to follow any reasonable instructions received from the seller with respect to the goods and in the absence of such instructions to make reasonable efforts to sell them for the seller's account if they are perishable or threaten to decline in value speedily. Instructions are not reasonable if on demand indemnity for expenses is not forthcoming.

. When the buyer sells goods under subsection (1) of this section, he or she is entitled to reimbursement from the seller or out of the proceeds for reasonable expenses of caring for and selling them, and if the expenses include no selling commission then to such commission as is usual in the trade or if there is none to a reasonable sum not exceeding ten per cent on the gross proceeds.

. In complying with this section, the buyer is held only to good faith and good faith conduct hereunder is neither acceptance nor conversion nor the basis of an action for damages.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20149[2013 c 23 § 149]; 1965 ex.s. c 157 § 2-603; ]

== 62A.2-604 - Buyer's options as to salvage of rightfully rejected goods.
Subject to the provisions of the immediately preceding section on perishables, if the seller gives no instructions within a reasonable time after notification of rejection, the buyer may store the rejected goods for the seller's account or reship them to him or her or resell them for the seller's account with reimbursement as provided in the preceding section. Such action is not acceptance or conversion.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20150[2013 c 23 § 150]; 1965 ex.s. c 157 § 2-604; ]

== 62A.2-605 - Waiver of buyer's objections by failure to particularize.
. The buyer's failure to state in connection with rejection a particular defect which is ascertainable by reasonable inspection precludes him or her from relying on the unstated defect to justify rejection or to establish breach:

.. Where the seller could have cured it if stated seasonably; or

.. Between merchants when the seller has after rejection made a request in writing for a full and final written statement of all defects on which the buyer proposes to rely.

. Payment against documents made without reservation of rights precludes recovery of the payment for defects apparent in the documents.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20811[2012 c 214 § 811]; 1965 ex.s. c 157 § 2-605; ]

== 62A.2-606 - What constitutes acceptance of goods.
. Acceptance of goods occurs when the buyer:

.. After a reasonable opportunity to inspect the goods signifies to the seller that the goods are conforming or that he or she will take or retain them in spite of their nonconformity; or

.. Fails to make an effective rejection (RCW 62A.2-602(1)), but such acceptance does not occur until the buyer has had a reasonable opportunity to inspect them; or

.. Does any act inconsistent with the seller's ownership; but if such act is wrongful as against the seller it is an acceptance only if ratified by him or her.

. Acceptance of a part of any commercial unit is acceptance of that entire unit.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20151[2013 c 23 § 151]; 1965 ex.s. c 157 § 2-606. Cf. former RCW sections:  RCW  63.04.480; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2047[1925 ex.s. c 142 § 47]; RRS § 5836-47.  RCW  63.04.490; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2048[1925 ex.s. c 142 § 48]; RRS § 5836-48; ]

== 62A.2-607 - Effect of acceptance; notice of breach; burden of establishing breach after acceptance; notice of claim or litigation to person answerable over.
. The buyer must pay at the contract rate for any goods accepted.

. Acceptance of goods by the buyer precludes rejection of the goods accepted and if made with knowledge of a nonconformity cannot be revoked because of it unless the acceptance was on the reasonable assumption that the nonconformity would be seasonably cured but acceptance does not of itself impair any other remedy provided by this Article for nonconformity.

. Where a tender has been accepted:

.. The buyer must within a reasonable time after he or she discovers or should have discovered any breach notify the seller of breach or be barred from any remedy; and

.. If the claim is one for infringement or the like (RCW 62A.2-312(3)) and the buyer is sued as a result of such a breach, he or she must so notify the seller within a reasonable time after he or she receives notice of the litigation or be barred from any remedy over for liability established by the litigation.

. The burden is on the buyer to establish any breach with respect to the goods accepted.

. Where the buyer is sued for breach of a warranty or other obligation for which his or her seller is answerable over:

.. He or she may give his or her seller written notice of the litigation. If the notice states that the seller may come in and defend and that if the seller does not do so he or she will be bound in any action against him or her by his or her buyer by any determination of fact common to the two litigations, then unless the seller after seasonable receipt of the notice does come in and defend he or she is so bound.

.. If the claim is one for infringement or the like (RCW 62A.2-312(3)), the original seller may demand in writing that his or her buyer turn over to him or her control of the litigation including settlement or else be barred from any remedy over and if he or she also agrees to bear all expense and to satisfy any adverse judgment, then unless the buyer after seasonable receipt of the demand does turn over control the buyer is so barred.

. The provisions of subsections (3), (4), and (5) of this section apply to any obligation of a buyer to hold the seller harmless against infringement or the like (RCW 62A.2-312(3)).

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20152[2013 c 23 § 152]; 1965 ex.s. c 157 § 2-607. Subd.  cf. former RCW  63.04.420; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2041[1925 ex.s. c 142 § 41]; RRS § 5836-41. Subd. , (3) cf. former RCW sections:  RCW  63.04.500; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2049[1925 ex.s. c 142 § 49]; RRS § 5836-49.  RCW  63.04.700; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2069[1925 ex.s. c 142 § 69]; RRS § 5836-69; ]

== 62A.2-608 - Revocation of acceptance in whole or in part.
. The buyer may revoke his or her acceptance of a lot or commercial unit whose nonconformity substantially impairs its value to him or her if he or she has accepted it:

.. On the reasonable assumption that its nonconformity would be cured and it has not been seasonably cured; or

.. Without discovery of such nonconformity if his or her acceptance was reasonably induced either by the difficulty of discovery before acceptance or by the seller's assurances.

. Revocation of acceptance must occur within a reasonable time after the buyer discovers or should have discovered the ground for it and before any substantial change in condition of the goods which is not caused by their own defects. It is not effective until the buyer notifies the seller of it.

. A buyer who so revokes has the same rights and duties with regard to the goods involved as if he or she had rejected them.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20153[2013 c 23 § 153]; 1965 ex.s. c 157 § 2-608. Cf. former RCW  63.04.700 (d), (3), (4), (5); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2069[1925 ex.s. c 142 § 69]; RRS § 5836-69; ]

== 62A.2-609 - Right to adequate assurance of performance.
. A contract for sale imposes an obligation on each party that the other's expectation of receiving due performance will not be impaired. When reasonable grounds for insecurity arise with respect to the performance of either party the other may in writing demand adequate assurance of due performance and until he or she receives such assurance may if commercially reasonable suspend any performance for which he or she has not already received the agreed return.

. Between merchants, the reasonableness of grounds for insecurity and the adequacy of any assurance offered shall be determined according to commercial standards.

. Acceptance of any improper delivery or payment does not prejudice the aggrieved party's right to demand adequate assurance of future performance.

. After receipt of a justified demand, failure to provide within a reasonable time not exceeding thirty days such assurance of due performance as is adequate under the circumstances of the particular case is a repudiation of the contract.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20154[2013 c 23 § 154]; 1965 ex.s. c 157 § 2-609. Cf. former RCW sections:  RCW  63.04.540; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2053[1925 ex.s. c 142 § 53]; RRS § 5836-53.  RCW  63.04.550(b); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2054[1925 ex.s. c 142 § 54]; RRS § 5836-54. (iii) RCW  63.04.560; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2055[1925 ex.s. c 142 § 55]; RRS § 5836-55. (iv) RCW  63.04.640; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2063[1925 ex.s. c 142 § 63]; RRS § 5836-63; ]

== 62A.2-610 - Anticipatory repudiation.
When either party repudiates the contract with respect to a performance not yet due the loss of which will substantially impair the value of the contract to the other, the aggrieved party may:

.. For a commercially reasonable time await performance by the repudiating party; or

.. Resort to any remedy for breach (RCW 62A.2-703 or 62A.2-711), even though he or she has notified the repudiating party that he or she would await the latter's performance and has urged retraction; and

.. In either case suspend his or her own performance or proceed in accordance with the provisions of this Article on the seller's right to identify goods to the contract notwithstanding breach or to salvage unfinished goods (RCW 62A.2-704).

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20155[2013 c 23 § 155]; 1965 ex.s. c 157 § 2-610. Cf. former RCW section:  RCW  63.04.640; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2063[1925 ex.s. c 142 § 63]; RRS § 5836-63.  RCW  63.04.660; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2065[1925 ex.s. c 142 § 65]; RRS § 5836-65; ]

== 62A.2-611 - Retraction of anticipatory repudiation.
. Until the repudiating party's next performance is due, he or she can retract his or her repudiation unless the aggrieved party has since the repudiation canceled or materially changed his or her position or otherwise indicated that he or she considers the repudiation final.

. Retraction may be by any method which clearly indicates to the aggrieved party that the repudiating party intends to perform, but must include any assurance justifiably demanded under the provisions of this Article (RCW 62A.2-609).

. Retraction reinstates the repudiating party's rights under the contract with due excuse and allowance to the aggrieved party for any delay occasioned by the repudiation.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20156[2013 c 23 § 156]; 1965 ex.s. c 157 § 2-611; ]

== 62A.2-612 - "Installment contract"; breach.
. An "installment contract" is one which requires or authorizes the delivery of goods in separate lots to be separately accepted, even though the contract contains a clause "each delivery is a separate contract" or its equivalent.

. The buyer may reject any installment which is nonconforming if the nonconformity substantially impairs the value of that installment and cannot be cured or if the nonconformity is a defect in the required documents; but if the nonconformity does not fall within subsection (3) of this section and the seller gives adequate assurance of its cure, the buyer must accept that installment.

. Whenever nonconformity or default with respect to one or more installments substantially impairs the value of the whole contract there is a breach of the whole. But the aggrieved party reinstates the contract if he or she accepts a nonconforming installment without seasonably notifying of cancellation or if he or she brings an action with respect only to past installments or demands performance as to future installments.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20157[2013 c 23 § 157]; 1965 ex.s. c 157 § 2-612. Cf. former RCW  63.04.460; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2045[1925 ex.s. c 142 § 45]; RRS § 5836-45; ]

== 62A.2-613 - Casualty to identified goods.
Where the contract requires for its performance goods identified when the contract is made, and the goods suffer casualty without fault of either party before the risk of loss passes to the buyer, or in a proper case under a "no arrival, no sale" term (RCW 62A.2-324) then:

.. If the loss is total, the contract is avoided; and

.. If the loss is partial or the goods have so deteriorated as no longer to conform to the contract, the buyer may nevertheless demand inspection and at his or her option either treat the contract as avoided or accept the goods with due allowance from the contract price for the deterioration or the deficiency in quantity but without further right against the seller.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20158[2013 c 23 § 158]; 1965 ex.s. c 157 § 2-613. Cf. former RCW sections:  RCW  63.04.080; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%207[1925 ex.s. c 142 § 7]; RRS § 5836-7.  RCW  63.04.090; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%208[1925 ex.s. c 142 § 8]; RRS § 5836-8; ]

== 62A.2-614 - Substituted performance.
. Where without fault of either party the agreed berthing, loading, or unloading facilities fail or an agreed type of carrier becomes unavailable or the agreed manner of delivery otherwise becomes commercially impracticable but a commercially reasonable substitute is available, such substitute performance must be tendered and accepted.

. If the agreed means or manner of payment fails because of domestic or foreign governmental regulation, the seller may withhold or stop delivery unless the buyer provides a means or manner of payment which is commercially a substantial equivalent. If delivery has already been taken, payment by the means or in the manner provided by the regulation discharges the buyer's obligation unless the regulation is discriminatory, oppressive or predatory.

[ 1965 ex.s. c 157 § 2-614; ]

== 62A.2-615 - Excuse by failure of presupposed conditions.
Except so far as a seller may have assumed a greater obligation and subject to the preceding section on substituted performance:

.. Delay in delivery or nondelivery in whole or in part by a seller who complies with subsections (b) and (c) of this section is not a breach of his or her duty under a contract for sale if performance as agreed has been made impracticable by the occurrence of a contingency the nonoccurrence of which was a basic assumption on which the contract was made or by compliance in good faith with any applicable foreign or domestic governmental regulation or order whether or not it later proves to be invalid.

.. Where the causes mentioned in subsection (a) of this section affect only a part of the seller's capacity to perform, he or she must allocate production and deliveries among his or her customers but may at his or her option include regular customers not then under contract as well as his or her own requirements for further manufacture. He or she may so allocate in any manner which is fair and reasonable.

.. The seller must notify the buyer seasonably that there will be delay or nondelivery and, when allocation is required under subsection (b) of this section, of the estimated quota thus made available for the buyer.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20159[2013 c 23 § 159]; 1965 ex.s. c 157 § 2-615; ]

== 62A.2-616 - Procedure on notice claiming excuse.
. Where the buyer receives notification of a material or indefinite delay or an allocation justified under the preceding section, he or she may by written notification to the seller as to any delivery concerned, and where the prospective deficiency substantially impairs the value of the whole contract under the provisions of this Article relating to breach of installment contracts (RCW 62A.2-612), then also as to the whole:

.. Terminate and thereby discharge any unexecuted portion of the contract; or

.. Modify the contract by agreeing to take his or her available quota in substitution.

. If after receipt of such notification from the seller the buyer fails so to modify the contract within a reasonable time not exceeding thirty days, the contract lapses with respect to any deliveries affected.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20160[2013 c 23 § 160]; 1965 ex.s. c 157 § 2-616; ]

== 62A.2-701 - Remedies for breach of collateral contracts not impaired.
Remedies for breach of any obligation or promise collateral or ancillary to a contract for sale are not impaired by the provisions of this Article.

[ 1965 ex.s. c 157 § 2-701; ]

== 62A.2-702 - Seller's remedies on discovery of buyer's insolvency.
. Where the seller discovers the buyer to be insolvent, he or she may refuse delivery except for cash including payment for all goods theretofore delivered under the contract, and stop delivery under this Article (RCW 62A.2-705).

. Where the seller discovers that the buyer has received goods on credit while insolvent, he or she may reclaim the goods upon demand made within ten days after the receipt, but if misrepresentation of solvency has been made to the particular seller in writing within three months before delivery the ten-day limitation does not apply. Except as provided in this subsection, the seller may not base a right to reclaim goods on the buyer's fraudulent or innocent misrepresentation of solvency or of intent to pay.

. The seller's right to reclaim under subsection (2) of this section is subject to the rights of a buyer in ordinary course or other good faith purchaser under this Article (RCW 62A.2-403). Successful reclamation of goods excludes all other remedies with respect to them.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20161[2013 c 23 § 161]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c41.pdf?cite=1981%20c%2041%20§%204[1981 c 41 § 4]; 1965 ex.s. c 157 § 2-702. Subd.  cf. former RCW sections:  RCW  63.04.540(b); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2053[1925 ex.s. c 142 § 53]; RRS § 5836-53.  RCW  63.04.550(c); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2054[1925 ex.s. c 142 § 54]; RRS § 5836-54. (iii) RCW  63.04.560; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2055[1925 ex.s. c 142 § 55]; RRS § 5836-55. (iv) RCW  63.04.580; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2057[1925 ex.s. c 142 § 57]; RRS § 5836-57. Subd. (3) cf. former RCW  63.04.755(3); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2076[1925 ex.s. c 142 § 76]; RRS § 5836-76; formerly RCW  63.04.010; ]

== 62A.2-703 - Seller's remedies in general.
Where the buyer wrongfully rejects or revokes acceptance of goods or fails to make a payment due on or before delivery or repudiates with respect to a part or the whole, then with respect to any goods directly affected and, if the breach is of the whole contract (RCW 62A.2-612), then also with respect to the whole undelivered balance, the aggrieved seller may

.. withhold delivery of such goods;

.. stop delivery by any bailee as hereafter provided (RCW 62A.2-705);

.. proceed under the next section respecting goods still unidentified to the contract;

.. resell and recover damages as hereafter provided (RCW 62A.2-706);

.. recover damages for non-acceptance (RCW 62A.2-708) or in a proper case the price (RCW 62A.2-709);

.. cancel.

[ 1965 ex.s. c 157 § 2-703. Cf. former RCW sections:  RCW  63.04.540; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2053[1925 ex.s. c 142 § 53]; RRS § 5836-53.  RCW  63.04.620; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2061[1925 ex.s. c 142 § 61]; RRS § 5836-61; ]

== 62A.2-704 - Seller's right to identify goods to the contract notwithstanding breach or to salvage unfinished goods.
. An aggrieved seller under the preceding section may:

.. Identify to the contract conforming goods not already identified if at the time he or she learned of the breach they are in his or her possession or control;

.. Treat as the subject of resale goods which have demonstrably been intended for the particular contract even though those goods are unfinished.

. Where the goods are unfinished, an aggrieved seller may in the exercise of reasonable commercial judgment for the purposes of avoiding loss and of effective realization either complete the manufacture and wholly identify the goods to the contract or cease manufacture and resell for scrap or salvage value or proceed in any other reasonable manner.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20162[2013 c 23 § 162]; 1965 ex.s. c 157 § 2-704. Cf. former RCW sections:  RCW  63.04.640(3); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2063[1925 ex.s. c 142 § 63]; RRS § 5836-63.  RCW  63.04.650(4); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2064[1925 ex.s. c 142 § 64]; RRS § 5836-64; ]

== 62A.2-705 - Seller's stoppage of delivery in transit or otherwise.
. The seller may stop delivery of goods in the possession of a carrier or other bailee when he or she discovers the buyer to be insolvent (RCW 62A.2-702) and may stop delivery of carload, truckload, planeload or larger shipments of express or freight when the buyer repudiates or fails to make a payment due before delivery or if for any other reason the seller has a right to withhold or reclaim the goods.

. As against such buyer the seller may stop delivery until:

.. Receipt of the goods by the buyer; or

.. Acknowledgment to the buyer by any bailee of the goods except a carrier that the bailee holds the goods for the buyer; or

.. Such acknowledgment to the buyer by a carrier by reshipment or as a warehouse; or

.. Negotiation to the buyer of any negotiable document of title covering the goods.

. [Empty]
.. To stop delivery the seller must so notify as to enable the bailee by reasonable diligence to prevent delivery of the goods.

.. After such notification the bailee must hold and deliver the goods according to the directions of the seller but the seller is liable to the bailee for any ensuing charges or damages.

.. If a negotiable document of title has been issued for goods the bailee is not obliged to obey a notification to stop until surrender of possession or control of the document.

.. A carrier who has issued a nonnegotiable bill of lading is not obliged to obey a notification to stop received from a person other than the consignor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20812[2012 c 214 § 812]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20823[2011 c 336 § 823]; 1965 ex.s. c 157 § 2-705. Cf. former RCW sections:  RCW  22.04.100; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%209[1913 c 99 § 9]; RRS § 3595; prior:  1891 c 134 § 7.  RCW  22.04.120; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%2011[1913 c 99 § 11]; RRS § 3597; prior:  1886 p 121 § 7. (iii) RCW  22.04.500; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%2049[1913 c 99 § 49]; RRS § 3635. (iv) RCW  63.04.580 through  63.04.600; 1925 ex.s. c 142 §§ 57 through 59; RRS §§ 5836-57 through 5836-59. (v) RCW  81.32.121,  81.32.141, and  81.32.421; 1961 c 14 §§ 81.32.121,  81.32.141, and  81.32.421; prior: 1915 c 159 §§ 12, 14, and 42; RRS §§ 3658, 3660, and 3688; formerly RCW  81.32.130,  81.32.160 and  81.32.510; ]

== 62A.2-706 - Seller's resale including contract for resale.
. Under the conditions stated in RCW 62A.2-703 on seller's remedies, the seller may resell the goods concerned or the undelivered balance thereof. Where the resale is made in good faith and in a commercially reasonable manner, the seller may recover the difference between the resale price and the contract price together with any incidental damages allowed under the provisions of this Article (RCW 62A.2-710), but less expenses saved in consequence of the buyer's breach.

. Except as otherwise provided in subsection (3) of this section or unless otherwise agreed, resale may be at public or private sale including sale by way of one or more contracts to sell or of identification to an existing contract of the seller. Sale may be as a unit or in parcels and at any time and place and on any terms but every aspect of the sale including the method, manner, time, place, and terms must be commercially reasonable. The resale must be reasonably identified as referring to the broken contract, but it is not necessary that the goods be in existence or that any or all of them have been identified to the contract before the breach.

. Where the resale is at private sale, the seller must give the buyer reasonable notification of his or her intention to resell.

. Where the resale is at public sale:

.. Only identified goods can be sold except where there is a recognized market for a public sale of futures in goods of the kind; and

.. It must be made at a usual place or market for public sale if one is reasonably available and except in the case of goods which are perishable or threaten to decline in value speedily the seller must give the buyer reasonable notice of the time and place of the resale; and

.. If the goods are not to be within the view of those attending the sale the notification of sale must state the place where the goods are located and provide for their reasonable inspection by prospective bidders; and

.. The seller may buy.

. A purchaser who buys in good faith at a resale takes the goods free of any rights of the original buyer even though the seller fails to comply with one or more of the requirements of this section.

. The seller is not accountable to the buyer for any profit made on any resale. A person in the position of a seller (RCW 62A.2-707) or a buyer who has rightfully rejected or justifiably revoked acceptance must account for any excess over the amount of his or her security interest, as hereinafter defined (RCW 62A.2-711(3)).

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20163[2013 c 23 § 163]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c114.pdf?cite=1967%20c%20114%20§%2013[1967 c 114 § 13]; 1965 ex.s. c 157 § 2-706. Cf. former RCW  63.04.610; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2060[1925 ex.s. c 142 § 60]; RRS § 5836-60; ]

== 62A.2-707 - "Person in the position of a seller".
. A "person in the position of a seller" includes as against a principal an agent who has paid or become responsible for the price of goods on behalf of his or her principal or anyone who otherwise holds a security interest or other right in goods similar to that of a seller.

. A person in the position of a seller may as provided in this Article withhold or stop delivery (RCW 62A.2-705) and resell (RCW 62A.2-706) and recover incidental damages (RCW 62A.2-710).

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20164[2013 c 23 § 164]; 1965 ex.s. c 157 § 2-707. Cf. former RCW  63.04.530; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2052[1925 ex.s. c 142 § 52]; RRS § 5836-52; ]

== 62A.2-708 - Seller's damages for non-acceptance or repudiation.
. Subject to subsection (2) and to the provisions of this Article with respect to proof of market price (RCW 62A.2-723), the measure of damages for non-acceptance or repudiation by the buyer is the difference between the market price at the time and place for tender and the unpaid contract price together with any incidental damages provided in this Article (RCW 62A.2-710), but less expenses saved in consequence of the buyer's breach.

. If the measure of damages provided in subsection (1) is inadequate to put the seller in as good a position as performance would have done then the measure of damages is the profit (including reasonable overhead) which the seller would have made from full performance by the buyer, together with any incidental damages provided in this Article (RCW 62A.2-710), due allowance for costs reasonably incurred and due credit for payments or proceeds of resale.

[ 1965 ex.s. c 157 § 2-708. Cf. former RCW  63.04.650; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2064[1925 ex.s. c 142 § 64]; RRS § 5836-64; ]

== 62A.2-709 - Action for the price.
. When the buyer fails to pay the price as it becomes due, the seller may recover, together with any incidental damages under the next section, the price:

.. Of goods accepted or of conforming goods lost or damaged within a commercially reasonable time after risk of their loss has passed to the buyer; and

.. Of goods identified to the contract if the seller is unable after reasonable effort to resell them at a reasonable price or the circumstances reasonably indicate that such effort will be unavailing.

. Where the seller sues for the price, he or she must hold for the buyer any goods which have been identified to the contract and are still in his or her control except that if resale becomes possible he or she may resell them at any time prior to the collection of the judgment. The net proceeds of any such resale must be credited to the buyer and payment of the judgment entitles him or her to any goods not resold.

. After the buyer has wrongfully rejected or revoked acceptance of the goods or has failed to make a payment due or has repudiated (RCW 62A.2-610), a seller who is held not entitled to the price under this section shall nevertheless be awarded damages for nonacceptance under the preceding section.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20165[2013 c 23 § 165]; 1965 ex.s. c 157 § 2-709. Cf. former RCW  63.04.640; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2063[1925 ex.s. c 142 § 63]; RRS § 5836-63; ]

== 62A.2-710 - Seller's incidental damages.
Incidental damages to an aggrieved seller include any commercially reasonable charges, expenses or commissions incurred in stopping delivery, in the transportation, care and custody of goods after the buyer's breach, in connection with return or resale of the goods or otherwise resulting from the breach.

[ 1965 ex.s. c 157 § 2-710. Cf. former RCW sections:  RCW  63.04.650; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2064[1925 ex.s. c 142 § 64]; RRS § 5836-64.  RCW  63.04.710; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2070[1925 ex.s. c 142 § 70]; RRS § 5836-70; ]

== 62A.2-711 - Buyer's remedies in general; buyer's security interest in rejected goods.
. Where the seller fails to make delivery or repudiates or the buyer rightfully rejects or justifiably revokes acceptance, then with respect to any goods involved, and with respect to the whole if the breach goes to the whole contract (RCW 62A.2-612), the buyer may cancel and whether or not he or she has done so may in addition to recovering so much of the price as has been paid:

.. "Cover" and have damages under the next section as to all the goods affected whether or not they have been identified to the contract; or

.. Recover damages for nondelivery as provided in this Article (RCW 62A.2-713).

. Where the seller fails to deliver or repudiates, the buyer may also:

.. If the goods have been identified recover them as provided in this Article (RCW 62A.2-502); or

.. In a proper case obtain specific performance or replevy the goods as provided in this Article (RCW 62A.2-716).

. On rightful rejection or justifiable revocation of acceptance, a buyer has a security interest in goods in his or her possession or control for any payments made on their price and any expenses reasonably incurred in their inspection, receipt, transportation, care, and custody and may hold such goods and resell them in like manner as an aggrieved seller (RCW 62A.2-706).

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20166[2013 c 23 § 166]; 1965 ex.s. c 157 § 2-711. Subd. (3) cf. former RCW  63.04.700(5); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2069[1925 ex.s. c 142 § 69]; RRS § 5836-69; ]

== 62A.2-712 - "Cover"; buyer's procurement of substitute goods.
. After a breach within the preceding section, the buyer may "cover" by making in good faith and without unreasonable delay any reasonable purchase of or contract to purchase goods in substitution for those due from the seller.

. The buyer may recover from the seller as damages the difference between the cost of cover and the contract price together with any incidental or consequential damages as hereinafter defined (RCW 62A.2-715), but less expenses saved in consequence of the seller's breach.

. Failure of the buyer to effect cover within this section does not bar him or her from any other remedy.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20167[2013 c 23 § 167]; 1965 ex.s. c 157 § 2-712; ]

== 62A.2-713 - Buyer's damages for non-delivery or repudiation.
. Subject to the provisions of this Article with respect to proof of market price (RCW 62A.2-723), the measure of damages for nondelivery or repudiation by the seller is the difference between the market price at the time when the buyer learned of the breach and the contract price together with any incidental and consequential damages provided in this Article (RCW 62A.2-715), but less expenses saved in consequence of the seller's breach.

. Market price is to be determined as of the place for tender or, in cases of rejection after arrival or revocation of acceptance, as of the place of arrival.

[ 1965 ex.s. c 157 § 2-713. Cf. former RCW  63.04.680(3); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2067[1925 ex.s. c 142 § 67]; RRS § 5836-67; ]

== 62A.2-714 - Buyer's damages for breach in regard to accepted goods.
. Where the buyer has accepted goods and given notification (RCW 62A.2-607(3)), he or she may recover as damages for any nonconformity of tender the loss resulting in the ordinary course of events from the seller's breach as determined in any manner which is reasonable.

. The measure of damages for breach of warranty is the difference at the time and place of acceptance between the value of the goods accepted and the value they would have had if they had been as warranted, unless special circumstances show proximate damages of a different amount.

. In a proper case, any incidental and consequential damages under the next section may also be recovered.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20168[2013 c 23 § 168]; 1965 ex.s. c 157 § 2-714. Cf. former RCW  63.04.700 (6), (7); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2069[1925 ex.s. c 142 § 69]; RRS § 5836-69; ]

== 62A.2-715 - Buyer's incidental and consequential damages.
. Incidental damages resulting from the seller's breach include expenses reasonably incurred in inspection, receipt, transportation and care and custody of goods rightfully rejected, any commercially reasonable charges, expenses or commissions in connection with effecting cover and any other reasonable expense incident to the delay or other breach.

. Consequential damages resulting from the seller's breach include

.. any loss resulting from general or particular requirements and needs of which the seller at the time of contracting had reason to know and which could not reasonably be prevented by cover or otherwise; and

.. injury to person or property proximately resulting from any breach of warranty.

[ 1965 ex.s. c 157 § 2-715. Subd.  cf. former RCW sections:  RCW  63.04.700(7); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2069[1925 ex.s. c 142 § 69]; RRS § 5836-69.  RCW  63.04.710; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2070[1925 ex.s. c 142 § 70]; RRS § 5836-70; ]

== 62A.2-716 - Buyer's right to specific performance or replevin.
. Specific performance may be decreed where the goods are unique or in other proper circumstances.

. The decree for specific performance may include such terms and conditions as to payment of the price, damages, or other relief as the court may deem just.

. The buyer has a right of replevin for goods identified to the contract if after reasonable effort he or she is unable to effect cover for such goods or the circumstances reasonably indicate that such effort will be unavailing or if the goods have been shipped under reservation and satisfaction of the security interest in them has been made or tendered. In the case of goods bought for personal, family, or household purposes, the buyer's right of replevin vests upon acquisition of a special property, even if the seller had not then repudiated or failed to deliver.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20169[2013 c 23 § 169]; 2000 c 250 § 9A-807; 1965 ex.s. c 157 § 2-716. Cf. former RCW  63.04.690; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2068[1925 ex.s. c 142 § 68]; RRS § 5836-68; ]

== 62A.2-717 - Deduction of damages from the price.
The buyer on notifying the seller of his or her intention to do so may deduct all or any part of the damages resulting from any breach of the contract from any part of the price still due under the same contract.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20170[2013 c 23 § 170]; 1965 ex.s. c 157 § 2-717. Cf. former RCW  63.04.700(a); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2069[1925 ex.s. c 142 § 69]; RRS § 5836-69; ]

== 62A.2-718 - Liquidation or limitation of damages; deposits.
. Damages for breach by either party may be liquidated in the agreement but only at an amount which is reasonable in the light of the anticipated or actual harm caused by the breach, the difficulties of proof of loss, and the inconvenience or nonfeasibility of otherwise obtaining an adequate remedy. A term fixing unreasonably large liquidated damages is void as a penalty.

. Where the seller justifiably withholds delivery of goods because of the buyer's breach, the buyer is entitled to restitution of any amount by which the sum of his or her payments exceeds:

.. The amount to which the seller is entitled by virtue of terms liquidating the seller's damages in accordance with subsection (1) of this section, or

.. In the absence of such terms, twenty per cent of the value of the total performance for which the buyer is obligated under the contract or five hundred dollars, whichever is smaller.

. The buyer's right to restitution under subsection (2) of this section is subject to offset to the extent that the seller establishes:

.. A right to recover damages under the provisions of this Article other than subsection (1) of this section, and

.. The amount or value of any benefits received by the buyer directly or indirectly by reason of the contract.

. Where a seller has received payment in goods, their reasonable value or the proceeds of their resale shall be treated as payments for the purposes of subsection (2) of this section; but if the seller has notice of the buyer's breach before reselling goods received in part performance, his or her resale is subject to the conditions laid down in this Article on resale by an aggrieved seller (RCW 62A.2-706).

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20171[2013 c 23 § 171]; 1965 ex.s. c 157 § 2-718; ]

== 62A.2-719 - Contractual modification or limitation of remedy.
. Subject to the provisions of subsections (2) and (3) of this section and of the preceding section on liquidation and limitation of damages,

.. the agreement may provide for remedies in addition to or in substitution for those provided in this Article and may limit or alter the measure of damages recoverable under this Article, as by limiting the buyer's remedies to return of the goods and repayment of the price or to repair and replacement of non-conforming goods or parts; and

.. resort to a remedy as provided is optional unless the remedy is expressly agreed to be exclusive, in which case it is the sole remedy.

. Where circumstances cause an exclusive or limited remedy to fail of its essential purpose, remedy may be had as provided in this Title.

. Limitation of consequential damages for injury to the person in the case of goods purchased primarily for personal, family or household use or of any services related thereto is invalid unless it is proved that the limitation is not unconscionable. Limitation of remedy to repair or replacement of defective parts or non-conforming goods is invalid in sales of goods primarily for personal, family or household use unless the manufacturer or seller maintains or provides within this state facilities adequate to provide reasonable and expeditious performance of repair or replacement obligations.

Limitation of other consequential damages is valid unless it is established that the limitation is unconscionable.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c180.pdf?cite=1974%20ex.s.%20c%20180%20§%202[1974 ex.s. c 180 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c78.pdf?cite=1974%20ex.s.%20c%2078%20§%202[1974 ex.s. c 78 § 2]; 1965 ex.s. c 157 § 2-719. Subd. (a) cf. former RCW  63.04.720; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2071[1925 ex.s. c 142 § 71]; RRS § 5836-71; ]

== 62A.2-720 - Effect of "cancellation" or "rescission" on claims for antecedent breach.
Unless the contrary intention clearly appears, expressions of "cancellation" or "rescission" of the contract or the like shall not be construed as a renunciation or discharge of any claim in damages for an antecedent breach.

[ 1965 ex.s. c 157 § 2-720; ]

== 62A.2-721 - Remedies for fraud.
Remedies for material misrepresentation or fraud include all remedies available under this Article for non-fraudulent breach. Neither rescission or a claim for rescission of the contract for sale nor rejection or return of the goods shall bar or be deemed inconsistent with a claim for damages or other remedy.

[ 1965 ex.s. c 157 § 2-721; ]

== 62A.2-722 - Who can sue third parties for injury to goods.
Where a third party so deals with goods which have been identified to a contract for sale as to cause actionable injury to a party to that contract:

.. A right of action against the third party is in either party to the contract for sale who has title to or a security interest or a special property or an insurable interest in the goods; and if the goods have been destroyed or converted a right of action is also in the party who either bore the risk of loss under the contract for sale or has since the injury assumed that risk as against the other;

.. If at the time of the injury the party plaintiff did not bear the risk of loss as against the other party to the contract for sale and there is no arrangement between them for disposition of the recovery, his or her suit or settlement is, subject to his or her own interest, as a fiduciary for the other party to the contract;

.. Either party may with the consent of the other sue for the benefit of whom it may concern.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20172[2013 c 23 § 172]; 1965 ex.s. c 157 § 2-722; ]

== 62A.2-723 - Proof of market price: Time and place.
. If an action based on anticipatory repudiation comes to trial before the time for performance with respect to some or all of the goods, any damages based on market price (RCW 62A.2-708 or 62A.2-713) shall be determined according to the price of such goods prevailing at the time when the aggrieved party learned of the repudiation.

. If evidence of a price prevailing at the times or places described in this Article is not readily available, the price prevailing within any reasonable time before or after the time described or at any other place which in commercial judgment or under usage of trade would serve as a reasonable substitute for the one described may be used, making any proper allowance for the cost of transporting the goods to or from such other place.

. Evidence of a relevant price prevailing at a time or place other than the one described in this Article offered by one party is not admissible unless and until he or she has given the other party such notice as the court finds sufficient to prevent unfair surprise.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20173[2013 c 23 § 173]; 1965 ex.s. c 157 § 2-723; ]

== 62A.2-724 - Admissibility of market quotations.
Whenever the prevailing price or value of any goods regularly bought and sold in any established commodity market is in issue, reports in official publications or trade journals or in newspapers or periodicals of general circulation published as the reports of such market shall be admissible in evidence. The circumstances of the preparation of such a report may be shown to affect its weight but not its admissibility.

[ 1965 ex.s. c 157 § 2-724; ]

== 62A.2-725 - Statute of limitations in contracts for sale.
. An action for breach of any contract for sale must be commenced within four years after the cause of action has accrued. By the original agreement the parties may reduce the period of limitation to not less than one year but may not extend it.

. A cause of action accrues when the breach occurs, regardless of the aggrieved party's lack of knowledge of the breach. A breach of warranty occurs when tender of delivery is made, except that where a warranty explicitly extends to future performance of the goods and discovery of the breach must await the time of such performance the cause of action accrues when the breach is or should have been discovered.

. Where an action commenced within the time limited by subsection (1) is so terminated as to leave available a remedy by another action for the same breach such other action may be commenced after the expiration of the time limited and within six months after the termination of the first action unless the termination resulted from voluntary discontinuance or from dismissal for failure or neglect to prosecute.

. This section does not alter the law on tolling of the statute of limitations nor does it apply to causes of action which have accrued before this Title becomes effective.

[ 1965 ex.s. c 157 § 2-725; ]

