= 62A.7 - Warehouse receipts, bills of lading and other documents of title.
:toc:

== 62A.7-101 - Short title.
This Article may be cited as Uniform Commercial Code—Documents of Title.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20201[2012 c 214 § 201]; 1965 ex.s. c 157 § 7-101; ]

== 62A.7-102 - Definitions and index of definitions.
.. In this Article, unless the context otherwise requires:

. "Bailee" means a person that by a warehouse receipt, bill of lading, or other document of title acknowledges possession of goods and contracts to deliver them.

. "Carrier" means a person that issues a bill of lading.

. "Consignee" means a person named in a bill of lading to which or to whose order the bill promises delivery.

. "Consignor" means a person named in a bill of lading as the person from which the goods have been received for shipment.

. "Delivery order" means a record that contains an order to deliver goods directed to a warehouse, carrier, or other person that in the ordinary course of business issues warehouse receipts or bills of lading.

. [Reserved.]

. "Goods" means all things that are treated as movable for the purposes of a contract for storage or transportation.

. "Issuer" means a bailee that issues a document of title or, in the case of an unaccepted delivery order, the person that orders the possessor of goods to deliver. The term includes a person for which an agent or employee purports to act in issuing a document if the agent or employee has real or apparent authority to issue documents, even if the issuer did not receive any goods, the goods were misdescribed, or in any other respect the agent or employee violated the issuer's instructions.

. "Person entitled under the document" means the holder, in the case of a negotiable document of title, or the person to which delivery of the goods is to be made by the terms of, or pursuant to instructions in a record under, a nonnegotiable document of title.

. [Reserved.]

. "Sign" means, with present intent to authenticate or adopt a record:

(A) To execute or adopt a tangible symbol; or

(B) To attach to or logically associate with the record an electronic sound, symbol, or process.

. "Shipper" means a person that enters into a contract of transportation with a carrier.

. "Warehouse" means a person engaged in the business of storing goods for hire.

.. Definitions in other articles applying to this Article and the sections in which they appear are:

. "Contract for sale", RCW 62A.2-106;

. "Lessee in ordinary course of business," RCW 62A.2A-103; and

. "Receipt" of goods, RCW 62A.2-103.

.. In addition, Article 1 contains general definitions and principles of construction and interpretation applicable throughout this Article.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20202[2012 c 214 § 202]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20825[2011 c 336 § 825]; 1965 ex.s. c 157 § 7-102. Cf. former RCW sections:  RCW  22.04.585; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%2058[1913 c 99 § 58]; RRS § 3644; formerly RCW  22.04.010.  RCW  63.04.755; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2076[1925 ex.s. c 142 § 76]; RRS § 5836-76; formerly RCW  63.04.010. (iii) RCW  81.32.011; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.32.011[1961 c 14 § 81.32.011]; prior:  1915 c 159 § 1; RRS § 3647; formerly RCW  81.32.020. (iv) RCW  81.32.531; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.32.531[1961 c 14 § 81.32.531]; prior:  1915 c 159 § 53; RRS § 3699; formerly RCW  81.32.010, part; ]

== 62A.7-103 - Relation of Article to treaty or statute.
.. This Article is subject to any treaty or statute of the United States or regulatory statute of this state to the extent the treaty, statute, or regulatory statute is applicable.

.. This Article does not modify or repeal any law prescribing the form or content of a document of title or the services or facilities to be afforded by a bailee, or otherwise regulating a bailee's business in respects not specifically treated in this Article. However, violation of such a law does not affect the status of a document of title that otherwise is within the definition of a document of title.

.. Chapter 214, Laws of 2012 modifies, limits, and supersedes the federal electronic signatures in global and national commerce act (15 U.S.C. Sec. 7001, et seq.) but does not modify, limit, or supersede section 101(c) of that act (15 U.S.C. Sec. 7001(c)) or authorize electronic delivery of any of the notices described in section 103(b) of that act (15 U.S.C. Sec. 7003(b)).

.. A person in its capacity as an electronic data storage provider or an electronic data transmitter is not subject to this Article.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20203[2012 c 214 § 203]; 1965 ex.s. c 157 § 7-103; ]

== 62A.7-104 - Negotiable and nonnegotiable document of title.
.. Except as otherwise provided in subsection (c) of this section, a document of title is negotiable if by its terms the goods are to be delivered to bearer or to the order of a named person.

.. A document of title other than one described in subsection (a) of this section is nonnegotiable. A bill of lading that states that the goods are consigned to a named person is not made negotiable by a provision that the goods are to be delivered only against an order in a record signed by the same or another named person.

.. A document of title is nonnegotiable if, at the time it is issued, the document has a conspicuous legend, however expressed, that it is nonnegotiable.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20204[2012 c 214 § 204]; 1965 ex.s. c 157 § 7-104. Cf. former RCW sections:  RCW  22.04.030,  22.04.050, and  22.04.060; 1913 c 99 §§ 2, 4, and 5; RRS §§ 3588, 3590, and 3591; prior: 1891 c 134 §§ 5 and 8.  RCW  22.04.040 and  22.04.080; 1913 c 99 §§ 3, 7; RRS §§ 3589, 3593. (iii) RCW  63.04.280 and  63.04.310; 1925 ex.s. c 142 §§ 27 and 30; RRS §§ 5836-27 and 5836-30. (iv) RCW  63.04.755; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2076[1925 ex.s. c 142 § 76]; RRS § 5836-76; formerly RCW  63.04.010. (v) RCW  81.32.021 through  81.32.051, and  81.32.081; 1961 c 14 §§ 81.32.021 through  81.32.051, and  81.32.081; prior: 1915 c 159 §§ 2 through 5, and 8; RRS §§ 3648 through 3651, and 3654; formerly RCW  81.32.030 through  81.32.060, and  81.32.090. (vi) RCW  81.32.531; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.32.531[1961 c 14 § 81.32.531]; prior:  1915 c 159 § 53; RRS § 3699; formerly RCW  81.32.010, part; ]

== 62A.7-105 - Reissuance in alternative medium.
.. Upon request of a person entitled under an electronic document of title, the issuer of the electronic document may issue a tangible document of title as a substitute for the electronic document if:

. The person entitled under the electronic document surrenders control of the document to the issuer; and

. The tangible document when issued contains a statement that it is issued in substitution for the electronic document.

.. Upon issuance of a tangible document of title in substitution for an electronic document of title in accordance with subsection (a) of this section:

. The electronic document ceases to have any effect or validity; and

. The person that procured issuance of the tangible document warrants to all subsequent persons entitled under the tangible document that the warrantor was a person entitled under the electronic document when the warrantor surrendered control of the electronic document to the issuer.

.. Upon request of a person entitled under a tangible document of title, the issuer of the tangible document may issue an electronic document of title as a substitute for the tangible document if:

. The person entitled under the tangible document surrenders possession of the document to the issuer; and

. The electronic document when issued contains a statement that it is issued in substitution for the tangible document.

.. Upon issuance of an electronic document of title in substitution for a tangible document of title in accordance with subsection (c) of this section:

. The tangible document ceases to have any effect or validity; and

. The person that procured issuance of the electronic document warrants to all subsequent persons entitled under the electronic document that the warrantor was a person entitled under the tangible document when the warrantor surrendered possession of the tangible document to the issuer.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20205[2012 c 214 § 205]; 1965 ex.s. c 157 § 7-105; ]

== 62A.7-106 - Control of electronic document of title.
.. A person has control of an electronic document of title if a system employed for evidencing the transfer of interests in the electronic document reliably establishes that person as the person to which the electronic document was issued or transferred.

.. A system satisfies subsection (a) of this section, and a person is deemed to have control of an electronic document of title, if the document is created, stored, and assigned in such a manner that:

. A single authoritative copy of the document exists which is unique, identifiable, and, except as otherwise provided in (4), (5), and (6) of this subsection, unalterable;

. The authoritative copy identifies the person asserting control as:

(A) The person to which the document was issued; or

(B) If the authoritative copy indicates that the document has been transferred, the person to which the document was most recently transferred;

. The authoritative copy is communicated to and maintained by the person asserting control or its designated custodian;

. Copies or amendments that add or change an identified assignee of the authoritative copy can be made only with the consent of the person asserting control; 

. Each copy of the authoritative copy and any copy of a copy is readily identifiable as a copy that is not the authoritative copy; and

. Any amendment of the authoritative copy is readily identifiable as authorized or unauthorized.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20206[2012 c 214 § 206]; ]

== 62A.7-201 - Person that may issue a warehouse receipt; storage under bond.
.. A warehouse receipt may be issued by any warehouse.

.. If goods, including distilled spirits and agricultural commodities, are stored under a statute requiring a bond against withdrawal or a license for the issuance of receipts in the nature of warehouse receipts, a receipt issued for the goods is deemed to be a warehouse receipt even if issued by a person that is the owner of the goods and is not a warehouse.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20301[2012 c 214 § 301]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20826[2011 c 336 § 826]; 1965 ex.s. c 157 § 7-201. Cf. former RCW  22.04.020; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%201[1913 c 99 § 1]; RRS § 3587; prior:  1891 c 134 § 1; ]

== 62A.7-202 - Form of warehouse receipt; effect of omission.
.. A warehouse receipt need not be in any particular form.

.. Unless a warehouse receipt provides for each of the following, the warehouse is liable for damages caused to a person injured by its omission:

. A statement of the location of the warehouse facility where the goods are stored;

. The date of issue of the receipt;

. The unique identification code of the receipt;

. A statement whether the goods received will be delivered to the bearer, to a named person, or to a named person or its order;

. The rate of storage and handling charges, unless goods are stored under a field warehousing arrangement, in which case a statement of that fact is sufficient on a nonnegotiable receipt;

. A description of the goods or the packages containing them;

. The signature of the warehouse or its agent;

. If the receipt is issued for goods that the warehouse owns, either solely, jointly, or in common with others, a statement of the fact of that ownership; and

. A statement of the amount of advances made and of liabilities incurred for which the warehouse claims a lien or security interest, unless the precise amount of advances made or liabilities incurred, at the time of the issue of the receipt, is unknown to the warehouse or to its agent that issued the receipt, in which case a statement of the fact that advances have been made or liabilities incurred and the purpose of the advances or liabilities is sufficient.

.. A warehouse may insert in its receipt any terms that are not contrary to the provisions of this title and do not impair its obligation of delivery under RCW 62A.7-403 or its duty of care under RCW 62A.7-204. Any contrary provision is ineffective.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20302[2012 c 214 § 302]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20827[2011 c 336 § 827]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2868.SL.pdf?cite=2000%20c%2058%20§%201[2000 c 58 § 1]; 1965 ex.s. c 157 § 7-202. Cf. former RCW sections:  RCW  22.04.030; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%202[1913 c 99 § 2]; RRS § 3588; prior:  1891 c 134 § 8.  RCW  22.04.040; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%203[1913 c 99 § 3]; RRS § 3589; ]

== 62A.7-203 - Liability for nonreceipt or misdescription.
A party to or purchaser for value in good faith of a document of title, other than a bill of lading, that relies upon the description of the goods in the document may recover from the issuer damages caused by the nonreceipt or misdescription of the goods, except to the extent that:

. The document conspicuously indicates that the issuer does not know whether all or part of the goods in fact were received or conform to the description, such as a case in which the description is in terms of marks or labels or kind, quantity, or condition, or the receipt or description is qualified by "contents, condition, and quality unknown," "said to contain," or words of similar import, if the indication is true; or

. The party or purchaser otherwise has notice of the nonreceipt or misdescription.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20303[2012 c 214 § 303]; 1965 ex.s. c 157 § 7-203. Cf. former RCW  22.04.210; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%2020[1913 c 99 § 20]; RRS § 3606; ]

== 62A.7-204 - Duty of care; contractual limitation of warehouse's liability.
.. A warehouse is liable for damages for loss of or injury to the goods caused by its failure to exercise care with regard to the goods that a reasonably careful person would exercise under similar circumstances. Unless otherwise agreed, the warehouse is not liable for damages that could not have been avoided by the exercise of that care.

.. Damages may be limited by a term in the warehouse receipt or storage agreement limiting the amount of liability in case of loss or damage beyond which the warehouse is not liable. Such a limitation is not effective with respect to the warehouse's liability for conversion to its own use. On request of the bailor in a record at the time of signing the storage agreement or within a reasonable time after receipt of the warehouse receipt, the warehouse's liability may be increased on part or all of the goods covered by the storage agreement or the warehouse receipt. In this event, increased rates may be charged based on an increased valuation of the goods.

.. Reasonable provisions as to the time and manner of presenting claims and commencing actions based on the bailment may be included in the warehouse receipt or storage agreement.

.. This section does not modify or repeal the provisions of chapters 22.09 and 22.32 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20304[2012 c 214 § 304]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20828[2011 c 336 § 828]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%201016[2009 c 549 § 1016]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c13.pdf?cite=1981%20c%2013%20§%201[1981 c 13 § 1]; 1965 ex.s. c 157 § 7-204. Cf. former RCW sections:  RCW  22.04.040; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%203[1913 c 99 § 3]; RRS § 3589.  RCW  22.04.220; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%2021[1913 c 99 § 21]; RRS § 3607; ]

== 62A.7-205 - Title under warehouse receipt defeated in certain cases.
A buyer in ordinary course of business of fungible goods sold and delivered by a warehouse that is also in the business of buying and selling such goods takes the goods free of any claim under a warehouse receipt even if the receipt is negotiable and has been duly negotiated.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20305[2012 c 214 § 305]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20829[2011 c 336 § 829]; 1965 ex.s. c 157 § 7-205; ]

== 62A.7-206 - Termination of storage at warehouse's option.
.. A warehouse, by giving notice to the person on whose account the goods are held and any other person known to claim an interest in the goods, may require payment of any charges and removal of the goods from the warehouse at the termination of the period of storage fixed by the document of title or, if a period is not fixed, within a stated period not less than thirty days after the warehouse gives notice. If the goods are not removed before the date specified in the notice, the warehouse may sell them pursuant to RCW 62A.7-210.

.. If a warehouse in good faith believes that goods are about to deteriorate or decline in value to less than the amount of its lien within the time provided in subsection (a) of this section and RCW 62A.7-210, the warehouse may specify in the notice given under subsection (a) of this section any reasonable shorter time for removal of the goods and, if the goods are not removed, may sell them at public sale held not less than one week after a single advertisement or posting.

.. If, as a result of a quality or condition of the goods of which the warehouse did not have notice at the time of deposit, the goods are a hazard to other property, the warehouse facilities, or other persons, the warehouse may sell the goods at public or private sale without advertisement or posting on reasonable notification to all persons known to claim an interest in the goods. If the warehouse, after a reasonable effort, is unable to sell the goods, it may dispose of them in any lawful manner and does not incur liability by reason of that disposition.

.. The warehouse shall deliver the goods to any person entitled to them under this Article upon due demand made at any time before sale or other disposition under this section.

.. The warehouse may satisfy its lien from the proceeds of any sale or disposition under this section but shall hold the balance for delivery on the demand of any person to which the warehouse would have been bound to deliver the goods.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20306[2012 c 214 § 306]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20830[2011 c 336 § 830]; 1965 ex.s. c 157 § 7-206. Cf. former RCW  22.04.350; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%2034[1913 c 99 § 34]; RRS § 3620; ]

== 62A.7-207 - Goods must be kept separate; fungible goods.
.. Unless the warehouse receipt provides otherwise, a warehouse shall keep separate the goods covered by each receipt so as to permit at all times identification and delivery of those goods. However, different lots of fungible goods may be commingled.

.. If different lots of fungible goods are commingled, the goods are owned in common by the persons entitled thereto and the warehouse is severally liable to each owner for that owner's share. If, because of over-issue, a mass of fungible goods is insufficient to meet all the receipts the warehouse has issued against it, the persons entitled include all holders to which overissued receipts have been duly negotiated.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20307[2012 c 214 § 307]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20831[2011 c 336 § 831]; 1965 ex.s. c 157 § 7-207. Cf. former RCW sections:  RCW  22.04.230; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%2022[1913 c 99 § 22]; RRS § 3608; prior:  1891 c 134 § 3.  RCW  22.04.240; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%2023[1913 c 99 § 23]; RRS § 3609; ]

== 62A.7-208 - Altered warehouse receipts.
If a blank in a negotiable tangible warehouse receipt has been filled in without authority, a good-faith purchaser for value and without notice of the lack of authority may treat the insertion as authorized. Any other unauthorized alteration leaves any tangible or electronic warehouse receipt enforceable against the issuer according to its original tenor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20308[2012 c 214 § 308]; 1965 ex.s. c 157 § 7-208. Cf. former RCW  22.04.140; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%2013[1913 c 99 § 13]; RRS § 3599; ]

== 62A.7-209 - Lien of warehouse.
.. A warehouse has a lien against the bailor on the goods covered by a warehouse receipt or storage agreement or on the proceeds thereof in its possession for charges for storage or transportation, including demurrage and terminal charges, insurance, labor, or other charges, present or future, in relation to the goods, and for expenses necessary for preservation of the goods or reasonably incurred in their sale pursuant to law. If the person on whose account the goods are held is liable for similar charges or expenses in relation to other goods whenever deposited and it is stated in the warehouse receipt or storage agreement that a lien is claimed for charges and expenses in relation to other goods, the warehouse also has a lien against the goods covered by the warehouse receipt or storage agreement or on the proceeds thereof in its possession for those charges and expenses, whether or not the other goods have been delivered by the warehouse. However, as against a person to which a negotiable warehouse receipt is duly negotiated, a warehouse's lien is limited to charges in an amount or at a rate specified in the warehouse receipt or, if no charges are so specified, to a reasonable charge for storage of the specific goods covered by the receipt subsequent to the date of the receipt. A warehouse's lien as provided in this chapter takes priority over all other liens and perfected or unperfected security interests.

.. The warehouse may also reserve a security interest against the bailor for the maximum amount specified on the receipt for charges other than those specified in subsection (a) of this section, such as for money advanced and interest. The security interest is governed by Article 9A of this title.

.. A warehouse's lien for charges and expenses under subsection (a) of this section or a security interest under subsection (b) of this section is also effective against any person that so entrusted the bailor with possession of the goods that a pledge of them by the bailor to a good-faith purchaser for value would have been valid.

However, the lien or security interest is not effective against a person that before issuance of a document of title had a legal interest or a perfected security interest in the goods and that did not:

. Deliver or entrust the goods or any document of title covering the goods to the bailor or the bailor's nominee with:

(A) Actual or apparent authority to ship, store, or sell;

(B) Power to obtain delivery under RCW 62A.7-403; or

(C) Power of disposition under RCW 62A.2-403, 62A.2A-304(2), 62A.2A-305(2), 62A.9A-320, or 62A.9A-321(c) or other statute or rule of law; or

. Acquiesce in the procurement by the bailor or its nominee of any document.

.. A warehouse's lien on household goods for charges and expenses in relation to the goods under subsection (a) of this section is also effective against all persons if the depositor was the legal possessor of the goods at the time of deposit. In this subsection, "household goods" means furniture, furnishings, or personal effects used by the depositor in a dwelling.

.. A warehouse loses its lien on any goods that it voluntarily delivers or unjustifiably refuses to deliver.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20309[2012 c 214 § 309]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20832[2011 c 336 § 832]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c395.pdf?cite=1987%20c%20395%20§%201[1987 c 395 § 1]; 1965 ex.s. c 157 § 7-209. Cf. former RCW sections: RCW  22.04.280 through  22.04.330; 1913 c 99 §§ 27 through 32; RRS §§ 3613 through 3618; ]

== 62A.7-210 - Enforcement of warehouse lien.
.. Except as otherwise provided in subsection (b) of this section, a warehouse's lien may be enforced by public or private sale of the goods, in bulk or in packages, at any time or place and on any terms that are commercially reasonable, after notifying all persons known to claim an interest in the goods. The notification must include a statement of the amount due, the nature of the proposed sale, and the time and place of any public sale. The fact that a better price could have been obtained by a sale at a different time or in a method different from that selected by the warehouse is not of itself sufficient to establish that the sale was not made in a commercially reasonable manner. The warehouse sells in a commercially reasonable manner if the warehouse sells the goods in the usual manner in any recognized market therefor, sells at the price current in that market at the time of the sale, or otherwise sells in conformity with commercially reasonable practices among dealers in the type of goods sold. A sale of more goods than apparently necessary to be offered to ensure satisfaction of the obligation is not commercially reasonable, except in cases covered by the preceding sentence.

.. A warehouse may enforce its lien on goods, other than goods stored by a merchant in the course of its business, only if the following requirements are satisfied:

. All persons known to claim an interest in the goods must be notified.

. The notification must include an itemized statement of the claim, a description of the goods subject to the lien, a demand for payment within a specified time not less than ten days after receipt of the notification, and a conspicuous statement that unless the claim is paid within that time the goods will be advertised for sale and sold by auction at a specified time and place.

. The sale must conform to the terms of the notification.

. The sale must be held at the nearest suitable place to that where the goods are held or stored.

. After the expiration of the time given in the notification, an advertisement of the sale must be published once a week for two weeks consecutively in a newspaper of general circulation where the sale is to be held. The advertisement must include a description of the goods, the name of the person on whose account the goods are being held, and the time and place of the sale. The sale must take place at least fifteen days after the first publication. If there is no newspaper of general circulation where the sale is to be held, the advertisement must be posted at least ten days before the sale in not fewer than six conspicuous places in the neighborhood of the proposed sale.

.. Before any sale pursuant to this section, any person claiming a right in the goods may pay the amount necessary to satisfy the lien and the reasonable expenses incurred in complying with this section. In that event, the goods may not be sold, but must be retained by the warehouse subject to the terms of the receipt and this Article.

.. A warehouse may buy at any public sale held pursuant to this section.

.. A purchaser in good faith of goods sold to enforce a warehouse's lien takes the goods free of any rights of persons against which the lien was valid, despite the warehouse's noncompliance with this section.

.. A warehouse may satisfy its lien from the proceeds of any sale pursuant to this section but must hold the balance, if any, for delivery on demand to any person to which the warehouse would have been bound to deliver the goods.

.. The rights provided by this section are in addition to all other rights allowed by law to a creditor against a debtor.

.. If a lien is on goods stored by a merchant in the course of its business, the lien may be enforced in accordance with either subsection (a) or (b) of this section.

.. A warehouse is liable for damages caused by failure to comply with the requirements for sale under this section and, in case of willful violation, is liable for conversion.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20310[2012 c 214 § 310]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20833[2011 c 336 § 833]; 1965 ex.s. c 157 § 7-210. Cf. former RCW sections: RCW  22.04.340,  22.04.360, and  22.04.370; 1913 c 99 §§ 33, 35, and 36; RRS §§ 3619, 3621, and 3622; ]

== 62A.7-301 - Liability for nonreceipt or misdescription; "said to contain"; "shipper's weight, load, and count"; improper handling.
.. A consignee of a nonnegotiable bill of lading which has given value in good faith, or a holder to which a negotiable bill has been duly negotiated, relying upon the description of the goods in the bill or upon the date shown in the bill, may recover from the issuer damages caused by the misdating of the bill or the nonreceipt or misdescription of the goods, except to the extent that the bill indicates that the issuer does not know whether any part or all of the goods in fact were received or conform to the description, such as in a case in which the description is in terms of marks or labels or kind, quantity, or condition or the receipt or description is qualified by "contents or condition of contents of packages unknown," "said to contain," "shipper's weight, load, and count," or words of similar import, if that indication is true.

.. If goods are loaded by the issuer of a bill of lading:

. The issuer shall count the packages of goods if shipped in packages and ascertain the kind and quantity if shipped in bulk; and

. Words such as "shipper's weight, load, and count," or words of similar import indicating that the description was made by the shipper are ineffective except as to goods concealed in packages.

.. If bulk goods are loaded by a shipper that makes available to the issuer of a bill of lading adequate facilities for weighing those goods, the issuer shall ascertain the kind and quantity within a reasonable time after receiving the shipper's request in a record to do so. In that case, "shipper's weight" or words of similar import are ineffective.

.. The issuer of a bill of lading, by including in the bill the words "shipper's weight, load, and count," or words of similar import, may indicate that the goods were loaded by the shipper, and, if that statement is true, the issuer is not liable for damages caused by the improper loading. However, omission of such words does not imply liability for damages caused by improper loading.

.. A shipper guarantees to an issuer the accuracy at the time of shipment of the description, marks, labels, number, kind, quantity, condition, and weight, as furnished by the shipper, and the shipper shall indemnify the issuer against damage caused by inaccuracies in those particulars. This right of indemnity does not limit the issuer's responsibility or liability under the contract of carriage to any person other than the shipper.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20401[2012 c 214 § 401]; 1965 ex.s. c 157 § 7-301. Cf. former RCW  81.32.231; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.32.231[1961 c 14 § 81.32.231]; prior:  1915 c 159 § 23; RRS § 3669; formerly RCW  81.32.240; ]

== 62A.7-302 - Through bills of lading and similar documents of title.
.. The issuer of a through bill of lading, or other document of title embodying an undertaking to be performed in part by a person acting as its agent or by a performing carrier, is liable to any person entitled to recover on the bill or other document for any breach by the other person or the performing carrier of its obligation under the bill or other document. However, to the extent that the bill or other document covers an undertaking to be performed overseas or in territory not contiguous to the continental United States or an undertaking including matters other than transportation, this liability for breach by the other person or the performing carrier may be varied by agreement of the parties.

.. If goods covered by a through bill of lading or other document of title embodying an undertaking to be performed in part by a person other than the issuer are received by that person, the person is subject, with respect to its own performance while the goods are in its possession, to the obligation of the issuer. The person's obligation is discharged by delivery of the goods to another person pursuant to the bill or other document and does not include liability for breach by any other person or by the issuer.

.. The issuer of a through bill of lading or other document of title described in subsection (a) of this section is entitled to recover from the performing carrier, or other person in possession of the goods when the breach of the obligation under the bill or other document occurred:

. The amount it may be required to pay to any person entitled to recover on the bill or other document for the breach, as may be evidenced by any receipt, judgment, or transcript of judgment; and

. The amount of any expense reasonably incurred by the issuer in defending any action commenced by any person entitled to recover on the bill or other document for the breach.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20402[2012 c 214 § 402]; 1965 ex.s. c 157 § 7-302; ]

== 62A.7-303 - Diversion; reconsignment; change of instructions.
.. Unless the bill of lading otherwise provides, a carrier may deliver the goods to a person or destination other than that stated in the bill or may otherwise dispose of the goods, without liability for misdelivery, on instructions from:

. The holder of a negotiable bill; (2) The consignor on a nonnegotiable bill, even if the consignee has given contrary instructions; (3) The consignee on a nonnegotiable bill in the absence of contrary instructions from the consignor, if the goods have arrived at the billed destination or if the consignee is in possession of the tangible bill or in control of the electronic bill; or

. The consignee on a nonnegotiable bill, if the consignee is entitled as against the consignor to dispose of the goods.

.. Unless instructions described in subsection (a) of this section are included in a negotiable bill of lading, a person to which the bill is duly negotiated may hold the bailee according to the original terms.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20403[2012 c 214 § 403]; 1965 ex.s. c 157 § 7-303; ]

== 62A.7-304 - Tangible bills of lading in a set.
.. Except as customary in international transportation, a tangible bill of lading may not be issued in a set of parts. The issuer is liable for damages caused by violation of this subsection.

.. If a tangible bill of lading is lawfully issued in a set of parts, each of which contains an identification code and is expressed to be valid only if the goods have not been delivered against any other part, the whole of the parts constitutes one bill.

.. If a tangible negotiable bill of lading is lawfully issued in a set of parts and different parts are negotiated to different persons, the title of the holder to which the first due negotiation is made prevails as to both the document of title and the goods even if any later holder may have received the goods from the carrier in good faith and discharged the carrier's obligation by surrendering its part.

.. A person that negotiates or transfers a single part of a tangible bill of lading issued in a set is liable to holders of that part as if it were the whole set.

.. The bailee shall deliver in accordance with RCW 62A.7-401 through 62A.7-404 against the first presented part of a tangible bill of lading lawfully issued in a set. Delivery in this manner discharges the bailee's obligation on the whole bill.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20404[2012 c 214 § 404]; 1965 ex.s. c 157 § 7-304. Cf. former RCW  81.32.061; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.32.061[1961 c 14 § 81.32.061]; prior:  1915 c 159 § 6; RRS § 3652; formerly RCW  81.32.070; ]

== 62A.7-305 - Destination bills.
.. Instead of issuing a bill of lading to the consignor at the place of shipment, a carrier, at the request of the consignor, may procure the bill to be issued at destination or at any other place designated in the request.

.. Upon request of any person entitled as against a carrier to control the goods while in transit and on surrender of possession or control of any outstanding bill of lading or other receipt covering the goods, the issuer, subject to RCW 62A.7-105, may procure a substitute bill to be issued at any place designated in the request.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20405[2012 c 214 § 405]; 1965 ex.s. c 157 § 7-305; ]

== 62A.7-306 - Altered bills of lading.
An unauthorized alteration or filling in of a blank in a bill of lading leaves the bill enforceable according to its original tenor.

[ 1965 ex.s. c 157 § 7-306. Cf. former RCW  81.32.161; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.32.161[1961 c 14 § 81.32.161]; prior:  1915 c 159 § 16; RRS § 3662; formerly RCW  81.32.170; ]

== 62A.7-307 - Lien of carrier.
.. A carrier has a lien on the goods covered by a bill of lading or on the proceeds thereof in its possession for charges after the date of the carrier's receipt of the goods for storage or transportation, including demurrage and terminal charges, and for expenses necessary for preservation of the goods incident to their transportation or reasonably incurred in their sale pursuant to law. However, against a purchaser for value of a negotiable bill of lading, a carrier's lien is limited to charges stated in the bill or the applicable tariffs or, if no charges are stated, a reasonable charge.

.. A lien for charges and expenses under subsection (a) of this section on goods that the carrier was required by law to receive for transportation is effective against the consignor or any person entitled to the goods unless the carrier had notice that the consignor lacked authority to subject the goods to those charges and expenses. Any other lien under subsection (a) of this section is effective against the consignor and any person that permitted the bailor to have control or possession of the goods unless the carrier had notice that the bailor lacked authority.

.. A carrier loses its lien on any goods that it voluntarily delivers or unjustifiably refuses to deliver.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20406[2012 c 214 § 406]; 1965 ex.s. c 157 § 7-307. Cf. former RCW sections: RCW  22.04.280 through  22.04.330; 1913 c 99 §§ 27 through 32; RRS §§ 3613 through 3618; ]

== 62A.7-308 - Enforcement of carrier's lien.
.. A carrier's lien on goods may be enforced by public or private sale of the goods, in bulk or in packages, at any time or place and on any terms that are commercially reasonable, after notifying all persons known to claim an interest in the goods. The notification must include a statement of the amount due, the nature of the proposed sale, and the time and place of any public sale. The fact that a better price could have been obtained by a sale at a different time or in a method different from that selected by the carrier is not of itself sufficient to establish that the sale was not made in a commercially reasonable manner. The carrier sells goods in a commercially reasonable manner if the carrier sells the goods in the usual manner in any recognized market therefor, sells at the price current in that market at the time of the sale, or otherwise sells in conformity with commercially reasonable practices among dealers in the type of goods sold. A sale of more goods than apparently necessary to be offered to ensure satisfaction of the obligation is not commercially reasonable, except in cases covered by the preceding sentence.

.. Before any sale pursuant to this section, any person claiming a right in the goods may pay the amount necessary to satisfy the lien and the reasonable expenses incurred in complying with this section. In that event, the goods may not be sold but must be retained by the carrier, subject to the terms of the bill of lading and this Article.

.. A carrier may buy at any public sale pursuant to this section.

.. A purchaser in good faith of goods sold to enforce a carrier's lien takes the goods free of any rights of persons against which the lien was valid, despite the carrier's noncompliance with this section.

.. A carrier may satisfy its lien from the proceeds of any sale pursuant to this section but shall hold the balance, if any, for delivery on demand to any person to which the carrier would have been bound to deliver the goods.

.. The rights provided by this section are in addition to all other rights allowed by law to a creditor against a debtor.

.. A carrier's lien may be enforced pursuant to either subsection (a) of this section or the procedure set forth in RCW 62A.7-210(b).

.. A carrier is liable for damages caused by failure to comply with the requirements for sale under this section and, in case of willful violation, is liable for conversion.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20407[2012 c 214 § 407]; 1965 ex.s. c 157 § 7-308. Cf. former RCW  22.04.340; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%2033[1913 c 99 § 33]; RRS § 3619; ]

== 62A.7-309 - Duty of care; contractual limitation of carrier's liability.
Save as otherwise provided in RCW 81.29.010 and 81.29.020:

.. A carrier that issues a bill of lading, whether negotiable or nonnegotiable, shall exercise the degree of care in relation to the goods which a reasonably careful person would exercise under similar circumstances. This subsection does not affect any statute, regulation, or rule of law that imposes liability upon a common carrier for damages not caused by its negligence.

.. Damages may be limited by a term in the bill of lading or in a transportation agreement that the carrier's liability may not exceed a value stated in the bill of lading or transportation agreement if the carrier's rates are dependent upon value and the consignor is afforded an opportunity to declare a higher value and the consignor is advised of the opportunity. However, such a limitation is not effective with respect to the carrier's liability for conversion to its own use.

.. Reasonable provisions as to the time and manner of presenting claims and commencing actions based on the shipment may be included in a bill of lading or a transportation agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20408[2012 c 214 § 408]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%201017[2009 c 549 § 1017]; 1965 ex.s. c 157 § 7-309. Cf. former RCW  81.32.031; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.32.031[1961 c 14 § 81.32.031]; prior:  1915 c 159 § 3; RRS § 3649; formerly RCW  81.32.040; ]

== 62A.7-401 - Irregularities in issue of receipt or bill or conduct of issuer.
The obligations imposed by this Article on an issuer apply to a document of title even if:

. The document does not comply with the requirements of this Article or of any other statute, rule, or regulation regarding its issuance, form, or content;

. The issuer violated laws regulating the conduct of its business;

. The goods covered by the document were owned by the bailee when the document was issued; or

. The person issuing the document is not a warehouse but the document purports to be a warehouse receipt.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20501[2012 c 214 § 501]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20834[2011 c 336 § 834]; 1965 ex.s. c 157 § 7-401. Cf. former RCW sections:  RCW  22.04.210; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%2020[1913 c 99 § 20]; RRS § 3606.  RCW  81.32.231; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.32.231[1961 c 14 § 81.32.231]; prior:  1915 c 159 § 23; RRS § 3669; formerly RCW  81.32.240; ]

== 62A.7-402 - Duplicate document of title; overissue.
A duplicate or any other document of title purporting to cover goods already represented by an outstanding document of the same issuer does not confer any right in the goods, except as provided in the case of tangible bills of lading in a set of parts, overissue of documents for fungible goods, substitutes for lost, stolen, or destroyed documents, or substitute documents issued pursuant to RCW 62A.7-105. The issuer is liable for damages caused by its overissue or failure to identify a duplicate document by a conspicuous notation.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20502[2012 c 214 § 502]; 1965 ex.s. c 157 § 7-402. Cf. former RCW sections:  RCW  22.04.070; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%206[1913 c 99 § 6]; RRS § 3592; prior:  1886 p 121 § 5.  RCW  81.32.071; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.32.071[1961 c 14 § 81.32.071]; prior:  1915 c 159 § 7; RRS § 3653; formerly RCW  81.32.080; ]

== 62A.7-403 - Obligation of bailee to deliver; excuse.
.. A bailee shall deliver the goods to a person entitled under a document of title if the person complies with subsections (b) and (c) of this section, unless and to the extent that the bailee establishes any of the following:

. Delivery of the goods to a person whose receipt was rightful as against the claimant;

. Damage to or delay, loss, or destruction of the goods for which the bailee is not liable;

. Previous sale or other disposition of the goods in lawful enforcement of a lien or on a warehouse's lawful termination of storage;

. The exercise by a seller of its right to stop delivery pursuant to RCW 62A.2-705 or by a lessor of its right to stop delivery pursuant to RCW 62A.2A-526;

. A diversion, reconsignment, or other disposition pursuant to RCW 62A.7-303;

. Release, satisfaction, or any other personal defense against the claimant; or

. Any other lawful excuse.

.. A person claiming goods covered by a document of title shall satisfy the bailee's lien if the bailee so requests or if the bailee is prohibited by law from delivering the goods until the charges are paid.

.. Unless a person claiming the goods is a person against which the document of title does not confer a right under RCW 62A.7-503(a):

. The person claiming under a document shall surrender possession or control of any outstanding negotiable document covering the goods for cancellation or indication of partial deliveries; and

. The bailee shall cancel the document or conspicuously indicate in the document the partial delivery or the bailee is liable to any person to which the document is duly negotiated.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20503[2012 c 214 § 503]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20835[2011 c 336 § 835]; 1965 ex.s. c 157 § 7-403. Cf. former RCW sections:  RCW  22.04.090, and  22.04.100; 1913 c 99 §§ 8 and 9; RRS §§ 3594, and 3595; prior: 1891 c 134 §§ 6, and 7.  RCW  22.04.110,  22.04.130,  22.04.170, and  22.04.200; 1913 c 99 §§ 10, 12, 16, and 19; RRS §§ 3596, 3598, 3602, and 3605. (iii) RCW  22.04.120; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%2011[1913 c 99 § 11]; RRS § 3597; prior:  1886 p 121 § 7. (iv) RCW  81.32.111 through  81.32.151,  81.32.191, and  81.32.221; 1961 c 14 §§ 81.32.111 through  81.32.151,  81.32.191, and  81.32.221; 1915 c 159 §§ 11 through 15, 19, and 22; RRS §§ 3657 through 3661, 3665, and 3668; formerly RCW  81.32.120 through  81.32.160,  81.32.200, and  81.32.230; ]

== 62A.7-404 - No liability for good-faith delivery pursuant to document of title.
A bailee that in good faith has received goods and delivered or otherwise disposed of the goods according to the terms of a document of title or pursuant to this Article is not liable for the goods even if:

. The person from which the bailee received the goods did not have authority to procure the document or to dispose of the goods; or

. The person to which the bailee delivered the goods did not have authority to receive the goods.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20504[2012 c 214 § 504]; 1965 ex.s. c 157 § 7-404. Cf. former RCW sections:  RCW  22.04.110; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%2010[1913 c 99 § 10]; RRS § 3596.  RCW  81.32.131; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.32.131[1961 c 14 § 81.32.131]; prior:  1915 c 159 § 13; RRS § 3659; formerly RCW  81.32.140; ]

== 62A.7-501 - Form of negotiation and requirements of due negotiation.
.. The following rules apply to a negotiable tangible document of title:

. If the document's original terms run to the order of a named person, the document is negotiated by the named person's indorsement and delivery. After the named person's indorsement in blank or to bearer, any person may negotiate the document by delivery alone.

. If the document's original terms run to bearer, it is negotiated by delivery alone.

. If the document's original terms run to the order of a named person and it is delivered to the named person, the effect is the same as if the document had been negotiated.

. Negotiation of the document after it has been indorsed to a named person requires indorsement by the named person and delivery.

. A document is duly negotiated if it is negotiated in the manner stated in this subsection to a holder that purchases it in good faith, without notice of any defense against or claim to it on the part of any person, and for value, unless it is established that the negotiation is not in the regular course of business or financing or involves receiving the document in settlement or payment of a monetary obligation.

.. The following rules apply to a negotiable electronic document of title:

. If the document's original terms run to the order of a named person or to bearer, the document is negotiated by delivery of the document to another person. Indorsement by the named person is not required to negotiate the document.

. If the document's original terms run to the order of a named person and the named person has control of the document, the effect is the same as if the document had been negotiated.

. A document is duly negotiated if it is negotiated in the manner stated in this subsection to a holder that purchases it in good faith, without notice of any defense against or claim to it on the part of any person, and for value, unless it is established that the negotiation is not in the regular course of business or financing or involves taking delivery of the document in settlement or payment of a monetary obligation.

.. Indorsement of a nonnegotiable document of title neither makes it negotiable nor adds to the transferee's rights.

.. The naming in a negotiable bill of lading of a person to be notified of the arrival of the goods does not limit the negotiability of the bill or constitute notice to a purchaser of the bill of any interest of that person in the goods.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20601[2012 c 214 § 601]; 1965 ex.s. c 157 § 7-501. Cf. former RCW sections:  RCW  22.04.380 through  22.04.410, and  22.04.480; 1913 c 99 §§ 37 through 40, and 47; RRS §§ 3623 through 3626, and 3633.  RCW  63.04.290,  63.04.300,  63.04.320,  63.04.330, and  63.04.390; 1925 ex.s. c 142 §§ 28, 29, 31, 32, and 38; RRS §§ 5836-28, 5836-29, 5836-31, 5836-32 and 5836-38. (iii) RCW  81.32.281 through  81.32.311, and  81.32.381; 1961 c 14 §§ 81.32.281 through  81.32.311, and  81.32.381; prior: 1915 c 159 §§ 28 through 31, and 38; RRS §§ 3674 through 3677, and 3684; formerly RCW  81.32.370 through  81.32.400, and  81.32.470; ]

== 62A.7-502 - Rights acquired by due negotiation.
.. Subject to RCW 62A.7-205 and 62A.7-503, a holder to which a negotiable document of title has been duly negotiated acquires thereby:

. Title to the document;

. Title to the goods;

. All rights accruing under the law of agency or estoppel, including rights to goods delivered to the bailee after the document was issued; and

. The direct obligation of the issuer to hold or deliver the goods according to the terms of the document free of any defense or claim by the issuer except those arising under the terms of the document or under this Article, but in the case of a delivery order, the bailee's obligation accrues only upon the bailee's acceptance of the delivery order and the obligation acquired by the holder is that the issuer and any indorser will procure the acceptance of the bailee.

.. Subject to RCW 62A.7-503, title and rights acquired by due negotiation are not defeated by any stoppage of the goods represented by the document of title or by surrender of the goods by the bailee and are not impaired even if:

. The due negotiation or any prior due negotiation constituted a breach of duty;

. Any person has been deprived of possession of a negotiable tangible document or control of a negotiable electronic document by misrepresentation, fraud, accident, mistake, duress, loss, theft, or conversion; or

. A previous sale or other transfer of the goods or document has been made to a third person.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20602[2012 c 214 § 602]; 1965 ex.s. c 157 § 7-502. Cf. former RCW sections:  RCW  22.04.420, and  22.04.480 through  22.04.500; 1913 c 99 §§ 41, and 47 through 49; RRS §§ 3627, and 3633 through 3635.  RCW  63.04.210(4),  63.04.260,  63.04.340,  63.04.390, and  63.04.630; 1925 ex.s. c 142 §§ 20, 25, 33, 38, and 62; RRS §§ 5836-20, 5836-25, 5836-33, 5836-38, and 5836-62. (iii) RCW  81.32.321,  81.32.381,  81.32.391,  81.32.401, and  81.32.421; 1961 c 14 §§ 81.32.321,  81.32.381,  81.32.391,  81.32.401, and  81.32.421; prior: 1915 c 159 §§ 32, 38, 39, 40, and 42; RRS §§ 3678, 3684, 3685, 3686, and 3688; formerly RCW  81.32.410,  81.32.470,  81.32.480,  81.32.490, and  81.32.510; ]

== 62A.7-503 - Document of title to goods defeated in certain cases.
.. A document of title confers no right in goods against a person that before issuance of the document had a legal interest or a perfected security interest in the goods and that did not:

. Deliver or entrust the goods or any document of title covering the goods to the bailor or the bailor's nominee with:

(A) Actual or apparent authority to ship, store, or sell;

(B) Power to obtain delivery under RCW 62A.7-403; or

(C) Power of disposition under RCW 62A.2-403, 62A.2A-304(2), 62A.2A-305(2), 62A.9A-320, or 62A.9A-321(c) or other statute or rule of law; or

. Acquiesce in the procurement by the bailor or its nominee of any document.

.. Title to goods based upon an unaccepted delivery order is subject to the rights of any person to which a negotiable warehouse receipt or bill of lading covering the goods has been duly negotiated. That title may be defeated under RCW 62A.7-504 to the same extent as the rights of the issuer or a transferee from the issuer.

.. Title to goods based upon a bill of lading issued to a freight forwarder is subject to the rights of any person to which a bill issued by the freight forwarder is duly negotiated. However, delivery by the carrier in accordance with RCW 62A.7-401 through 62A.7-404 pursuant to its own bill of lading discharges the carrier's obligation to deliver.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20603[2012 c 214 § 603]; 2000 c 250 § 9A-814; 1965 ex.s. c 157 § 7-503. Cf. former RCW sections:  RCW  22.04.420; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%2041[1913 c 99 § 41]; RRS § 3627.  RCW  63.04.340; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2033[1925 ex.s. c 142 § 33]; RRS § 5836-33. (iii) RCW  81.32.321; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.32.321[1961 c 14 § 81.32.321]; prior:  1915 c 159 § 32; RRS § 3678; formerly RCW  81.32.410; ]

== 62A.7-504 - Rights acquired in absence of due negotiation; effect of diversion; stoppage of delivery.
.. A transferee of a document of title, whether negotiable or nonnegotiable, to which the document has been delivered but not duly negotiated, acquires the title and rights that its transferor had or had actual authority to convey.

.. In the case of a transfer of a nonnegotiable document of title, until but not after the bailee receives notice of the transfer, the rights of the transferee may be defeated:

. By those creditors of the transferor which could treat the transfer as void under RCW 62A.2-402 or 62A.2A-308;

. By a buyer from the transferor in ordinary course of business if the bailee has delivered the goods to the buyer or received notification of the buyer's rights;

. By a lessee from the transferor in ordinary course of business if the bailee has delivered the goods to the lessee or received notification of the lessee's rights; or

. As against the bailee, by good-faith dealings of the bailee with the transferor.

.. A diversion or other change of shipping instructions by the consignor in a nonnegotiable bill of lading which causes the bailee not to deliver the goods to the consignee defeats the consignee's title to the goods if the goods have been delivered to a buyer in ordinary course of business or a lessee in ordinary course of business and, in any event, defeats the consignee's rights against the bailee.

.. Delivery of the goods pursuant to a nonnegotiable document of title may be stopped by a seller under RCW 62A.2-705 or a lessor under RCW 62A.2A-526, subject to the requirements of due notification in those statutes. A bailee that honors the seller's or lessor's instructions is entitled to be indemnified by the seller or lessor against any resulting loss or expense.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20604[2012 c 214 § 604]; 1965 ex.s. c 157 § 7-504. Cf. former RCW sections:  RCW  22.04.420 and  22.04.430; 1913 c 99 §§ 41 and 42; RRS §§ 3627, and 3628.  RCW  63.04.350; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2034[1925 ex.s. c 142 § 34]; RRS § 5834-34. (iii) RCW  81.32.321 and  81.32.331; 1961 c 14 §§ 81.32.321 and  81.32.331; prior: 1915 c 159 §§ 32 and 33; RRS §§ 3678 and 3679; formerly RCW  81.32.410 and  81.32.420; ]

== 62A.7-505 - Indorser not guarantor for other parties.
The indorsement of a tangible document of title issued by a bailee does not make the indorser liable for any default by the bailee or previous indorsers.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20605[2012 c 214 § 605]; 1965 ex.s. c 157 § 7-505. Cf. former RCW sections:  RCW  22.04.460; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%2045[1913 c 99 § 45]; RRS § 3631.  RCW  63.04.380; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2037[1925 ex.s. c 142 § 37]; RRS § 5836-37. (iii) RCW  81.32.361; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.32.361[1961 c 14 § 81.32.361]; prior:  1915 c 159 § 36; RRS § 3682; formerly RCW  81.32.450; ]

== 62A.7-506 - Delivery without indorsement: Right to compel indorsement.
The transferee of a negotiable tangible document of title has a specifically enforceable right to have its transferor supply any necessary indorsement, but the transfer becomes a negotiation only as of the time the indorsement is supplied.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20606[2012 c 214 § 606]; 1965 ex.s. c 157 § 7-506. Cf. former RCW sections:  RCW  22.04.440; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%2043[1913 c 99 § 43]; RRS § 3629.  RCW  63.04.360; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2035[1925 ex.s. c 142 § 35]; RRS § 5836-35. (iii) RCW  81.32.341; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.32.341[1961 c 14 § 81.32.341]; prior:  1915 c 159 § 34; RRS § 3680; formerly RCW  81.32.430; ]

== 62A.7-507 - Warranties on negotiation or delivery of document of title.
If a person negotiates or delivers a document of title for value, otherwise than as a mere intermediary under RCW 62A.7-508, unless otherwise agreed, the transferor, in addition to any warranty made in selling or leasing the goods, warrants to its immediate purchaser only that:

. The document is genuine;

. The transferor does not have knowledge of any fact that would impair the document's validity or worth; and

. The negotiation or delivery is rightful and fully effective with respect to the title to the document and the goods it represents.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20607[2012 c 214 § 607]; 1965 ex.s. c 157 § 7-507. Cf. former RCW sections:  RCW  22.04.450; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%2044[1913 c 99 § 44]; RRS § 3630.  RCW  63.04.370; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c142.pdf?cite=1925%20ex.s.%20c%20142%20§%2036[1925 ex.s. c 142 § 36]; RRS § 5836-36. (iii) RCW  81.32.351; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.32.351[1961 c 14 § 81.32.351]; prior:  1915 c 159 § 35; RRS § 3681; formerly RCW  81.32.440; ]

== 62A.7-508 - Warranties of collecting bank as to documents of title.
A collecting bank or other intermediary known to be entrusted with documents of title on behalf of another or with collection of a draft or other claim against delivery of documents warrants by the delivery of the documents only its own good faith and authority even if the collecting bank or other intermediary has purchased or made advances against the claim or draft to be collected.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20608[2012 c 214 § 608]; 1965 ex.s. c 157 § 7-508. Cf. former RCW sections:  RCW  22.04.470; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%2046[1913 c 99 § 46]; RRS § 3632.  RCW  81.32.371; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.32.371[1961 c 14 § 81.32.371]; prior:  1915 c 159 § 37; RRS § 3683; formerly RCW  81.32.460; ]

== 62A.7-509 - Adequate compliance with commercial contract.
Whether a document of title is adequate to fulfill the obligations of a contract for sale, a contract for lease, or the conditions of a letter of credit is determined by Article 2, 2A, or 5 of this title.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20609[2012 c 214 § 609]; 1965 ex.s. c 157 § 7-509; ]

== 62A.7-601 - Lost, stolen, or destroyed documents of title.
.. If a document of title is lost, stolen, or destroyed, a court may order delivery of the goods or issuance of a substitute document and the bailee may without liability to any person comply with the order. If the document was negotiable, a court may not order delivery of the goods or issuance of a substitute document without the claimant's posting security unless it finds that any person that may suffer loss as a result of nonsurrender of possession or control of the document is adequately protected against the loss. If the document was nonnegotiable, the court may require security. The court may also order payment of the bailee's reasonable costs and attorneys' fees in any action under this subsection.

.. A bailee that, without a court order, delivers goods to a person claiming under a missing negotiable document of title is liable to any person injured thereby. If the delivery is not in good faith, the bailee is liable for conversion. Delivery in good faith is not conversion if the claimant posts security with the bailee in an amount at least double the value of the goods at the time of posting to indemnify any person injured by the delivery which files a notice of claim within one year after the delivery.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20701[2012 c 214 § 701]; 1965 ex.s. c 157 § 7-601. Cf. former RCW sections:  RCW  22.04.150; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%2014[1913 c 99 § 14]; RRS § 3600.  RCW  81.32.171; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.32.171[1961 c 14 § 81.32.171]; prior:  1915 c 159 § 17; RRS § 3663; formerly RCW  81.32.180; ]

== 62A.7-602 - Judicial process against goods covered by negotiable document of title.
Unless a document of title was originally issued upon delivery of the goods by a person that did not have power to dispose of them, a lien does not attach by virtue of any judicial process to goods in the possession of a bailee for which a negotiable document of title is outstanding unless possession or control of the document is first surrendered to the bailee or the document's negotiation is enjoined. The bailee may not be compelled to deliver the goods pursuant to process until possession or control of the document is surrendered to the bailee or to the court. A purchaser of the document for value without notice of the process or injunction takes free of the lien imposed by judicial process.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20702[2012 c 214 § 702]; 1965 ex.s. c 157 § 7-602. Cf. former RCW sections:  RCW  22.04.260; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1913c99.pdf?cite=1913%20c%2099%20§%2025[1913 c 99 § 25]; RRS § 3611.  RCW  81.32.241; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c14.pdf?cite=1961%20c%2014%20§%2081.32.241[1961 c 14 § 81.32.241]; prior:  1915 c 159 § 24; RRS § 3670; formerly RCW  81.32.250; ]

== 62A.7-603 - Conflicting claims; interpleader.
If more than one person claims title to or possession of the goods, the bailee is excused from delivery until the bailee has a reasonable time to ascertain the validity of the adverse claims or to commence an action for interpleader. The bailee may assert an interpleader either in defending an action for nondelivery of the goods or by original action.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%20703[2012 c 214 § 703]; 1965 ex.s. c 157 § 7-603. Cf. former RCW sections:  RCW  22.04.170 and  22.04.180; 1913 c 99 §§ 16 and 17; RRS §§ 3602 and 3603.  RCW  81.32.201 and  81.32.211; 1961 c 14 §§ 81.32.201 and  81.32.211; prior: 1915 c 159 §§ 20 and 21; RRS §§ 3666 and 3667; formerly RCW  81.32.210 and  81.32.220; ]

