= 62A.3 - Negotiable instruments.
:toc:

== 62A.3-101 - Short title.
This Article may be cited as Uniform Commercial Code—Negotiable Instruments.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%203[1993 c 229 § 3]; 1965 ex.s. c 157 § 3-101; ]

== 62A.3-102 - Subject matter.
.. This Article applies to negotiable instruments. It does not apply to money, to payment orders governed by Article 4A, or to securities governed by Article 8.

.. If there is conflict between this Article and Article 4 or 9A, Articles 4 and 9A govern.

.. Regulations of the Board of Governors of the Federal Reserve System and operating circulars of the Federal Reserve Banks supersede any inconsistent provision of this Article to the extent of the inconsistency.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5053.SL.pdf?cite=2001%20c%2032%20§%2012[2001 c 32 § 12]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%204[1993 c 229 § 4]; 1965 ex.s. c 157 § 3-102. Cf. former RCW sections:  RCW  62.01.001(5); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.001[1955 c 35 § 62.01.001]; prior:  1899 c 149 § 1; RRS § 3392.  RCW  62.01.128; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.128[1955 c 35 § 62.01.128]; prior:  1899 c 149 § 128; RRS § 3518. (iii) RCW  62.01.191; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.191[1955 c 35 § 62.01.191]; prior:  1899 c 149 § 191; RRS § 3581; ]

== 62A.3-103 - Definitions.
.. In this Article:

. "Acceptor" means a drawee who has accepted a draft.

. "Drawee" means a person ordered in a draft to make payment.

. "Drawer" means a person who signs or is identified in a draft as a person ordering payment.

. [Reserved.]

. "Maker" means a person who signs or is identified in a note as a person undertaking to pay.

. "Order" means a written instruction to pay money signed by the person giving the instruction. The instruction may be addressed to any person, including the person giving the instruction, or to one or more persons jointly or in the alternative but not in succession. An authorization to pay is not an order unless the person authorized to pay is also instructed to pay.

. "Ordinary care" in the case of a person engaged in business means observance of reasonable commercial standards, prevailing in the area in which the person is located, with respect to the business in which the person is engaged. In the case of a bank that takes an instrument for processing for collection or payment by automated means, reasonable commercial standards do not require the bank to examine the instrument if the failure to examine does not violate the bank's prescribed procedures and the bank's procedures do not vary unreasonably from general banking usage not disapproved by this Article or Article 4.

. "Party" means a party to an instrument.

. "Promise" means a written undertaking to pay money signed by the person undertaking to pay. An acknowledgment of an obligation by the obligor is not a promise unless the obligor also undertakes to pay the obligation.

. "Prove" with respect to a fact means to meet the burden of establishing the fact (RCW 62A.1-201(b)(8)).

. "Remitter" means a person who purchases an instrument from its issuer if the instrument is payable to an identified person other than the purchaser.

.. Other definitions applying to this Article and the sections in which they appear are:

 "Acceptance"RCW 62A.3-409 "Accommodated party"RCW 62A.3-419 "Accommodation party"RCW 62A.3-419 "Alteration"RCW 62A.3-407 "Anomalous indorsement"RCW 62A.3-205 "Blank indorsement"RCW 62A.3-205 "Cashier's check"RCW 62A.3-104 "Certificate of deposit"RCW 62A.3-104 "Certified check"RCW 62A.3-409 "Check"RCW 62A.3-104 "Consideration"RCW 62A.3-303 "Draft"RCW 62A.3-104 "Holder in due course"RCW 62A.3-302 "Incomplete instrument"RCW 62A.3-115 "Indorsement"RCW 62A.3-204 "Indorser"RCW 62A.3-204 "Instrument"RCW 62A.3-104 "Issue"RCW 62A.3-105 "Issuer"RCW 62A.3-105 "Negotiable instrument"RCW 62A.3-104 "Negotiation"RCW 62A.3-201 "Note"RCW 62A.3-104 "Payable at a definite time"RCW 62A.3-108 "Payable on demand"RCW 62A.3-108 "Payable to bearer"RCW 62A.3-109 "Payable to order"RCW 62A.3-109 "Payment"RCW 62A.3-602 "Person entitled to enforce"RCW 62A.3-301 "Presentment"RCW 62A.3-501 "Reacquisition"RCW 62A.3-207 "Special indorsement"RCW 62A.3-205 "Teller's check"RCW 62A.3-104 "Transfer of instrument"RCW 62A.3-203 "Traveler's check"RCW 62A.3-104 "Value"RCW 62A.3-303

 

"Acceptance"

RCW 62A.3-409

 

"Accommodated party"

RCW 62A.3-419

 

"Accommodation party"

RCW 62A.3-419

 

"Alteration"

RCW 62A.3-407

 

"Anomalous indorsement"

RCW 62A.3-205

 

"Blank indorsement"

RCW 62A.3-205

 

"Cashier's check"

RCW 62A.3-104

 

"Certificate of deposit"

RCW 62A.3-104

 

"Certified check"

RCW 62A.3-409

 

"Check"

RCW 62A.3-104

 

"Consideration"

RCW 62A.3-303

 

"Draft"

RCW 62A.3-104

 

"Holder in due course"

RCW 62A.3-302

 

"Incomplete instrument"

RCW 62A.3-115

 

"Indorsement"

RCW 62A.3-204

 

"Indorser"

RCW 62A.3-204

 

"Instrument"

RCW 62A.3-104

 

"Issue"

RCW 62A.3-105

 

"Issuer"

RCW 62A.3-105

 

"Negotiable instrument"

RCW 62A.3-104

 

"Negotiation"

RCW 62A.3-201

 

"Note"

RCW 62A.3-104

 

"Payable at a definite time"

RCW 62A.3-108

 

"Payable on demand"

RCW 62A.3-108

 

"Payable to bearer"

RCW 62A.3-109

 

"Payable to order"

RCW 62A.3-109

 

"Payment"

RCW 62A.3-602

 

"Person entitled to enforce"

RCW 62A.3-301

 

"Presentment"

RCW 62A.3-501

 

"Reacquisition"

RCW 62A.3-207

 

"Special indorsement"

RCW 62A.3-205

 

"Teller's check"

RCW 62A.3-104

 

"Transfer of instrument"

RCW 62A.3-203

 

"Traveler's check"

RCW 62A.3-104

 

"Value"

RCW 62A.3-303

.. The following definitions in other articles apply to this Article:

 "Banking day"RCW 62A.4-104 "Clearinghouse"RCW 62A.4-104 "Collecting bank"RCW 62A.4-105 "Depositary bank"RCW 62A.4-105 "Documentary draft"RCW 62A.4-104 "Intermediary bank"RCW 62A.4-105 "Item"RCW 62A.4-104 "Payor bank"RCW 62A.4-105 "Suspends payments"RCW 62A.4-104

 

"Banking day"

RCW 62A.4-104

 

"Clearinghouse"

RCW 62A.4-104

 

"Collecting bank"

RCW 62A.4-105

 

"Depositary bank"

RCW 62A.4-105

 

"Documentary draft"

RCW 62A.4-104

 

"Intermediary bank"

RCW 62A.4-105

 

"Item"

RCW 62A.4-104

 

"Payor bank"

RCW 62A.4-105

 

"Suspends payments"

RCW 62A.4-104

.. In addition, Article 1 contains general definitions and principles of construction and interpretation applicable throughout this Article.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2197-S.SL.pdf?cite=2012%20c%20214%20§%201001[2012 c 214 § 1001]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%205[1993 c 229 § 5]; 1965 ex.s. c 157 § 3-103; ]

== 62A.3-104 - Negotiable instrument.
.. Except as provided in subsections (c) and (d), "negotiable instrument" means an unconditional promise or order to pay a fixed amount of money, with or without interest or other charges described in the promise or order, if it:

. Is payable to bearer or to order at the time it is issued or first comes into possession of a holder;

. Is payable on demand or at a definite time; and

. Does not state any other undertaking or instruction by the person promising or ordering payment to do any act in addition to the payment of money, but the promise or order may contain (i) an undertaking or power to give, maintain, or protect collateral to secure payment, (ii) an authorization or power to the holder to confess judgment or realize on or dispose of collateral, or (iii) a waiver of the benefit of any law intended for the advantage or protection of an obligor.

.. "Instrument" means a negotiable instrument.

.. An order that meets all of the requirements of subsection (a), except subsection (a)(1), and otherwise falls within the definition of "check" in subsection (f) is a negotiable instrument and a check.

.. A promise or order other than a check is not an instrument if, at the time it is issued or first comes into possession of a holder, it contains a conspicuous statement, however expressed, to the effect that the promise or order is not negotiable or is not an instrument governed by this Article.

.. An instrument is a "note" if it is a promise and is a "draft" if it is an order. If an instrument falls within the definition of both "note" and "draft," a person entitled to enforce the instrument may treat it as either.

.. "Check" means (i) a draft, other than a documentary draft, payable on demand and drawn on a bank, or (ii) a cashier's check or teller's check. An instrument may be a check even though it is described on its face by another term, such as "money order."

.. "Cashier's check" means a draft with respect to which the drawer and drawee are the same bank or branches of the same bank.

.. "Teller's check" means a draft drawn by a bank (i) on another bank, or (ii) payable at or through a bank.

.. "Traveler's check" means an instrument that (i) is payable on demand, (ii) is drawn on or payable at or through a bank, (iii) is designated by the term "traveler's check" or by a substantially similar term, and (iv) requires, as a condition to payment, a countersignature by a person whose specimen signature appears on the instrument.

.. "Certificate of deposit" means an instrument containing an acknowledgment by a bank that a sum of money has been received by the bank and a promise by the bank to repay the sum of money. A certificate of deposit is a note of the bank.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%206[1993 c 229 § 6]; 1965 ex.s. c 157 § 3-104. Cf. former RCW sections: RCW  62.01.001,  62.01.005,  62.01.010,  62.01.126,  62.01.184, and  62.01.185; 1955 c 35 §§ 62.01.001,  62.01.005,  62.01.010,  62.01.126,  62.01.184, and  62.01.185; prior: 1899 c 149 §§ 1, 5, 10, 126, 184, and 185; RRS §§ 3392, 3396, 3401, 3516, 3574, and 3575; ]

== 62A.3-105 - Issue of instrument.
.. "Issue" means the first delivery of an instrument by the maker or drawer, whether to a holder or nonholder, for the purpose of giving rights on the instrument to any person.

.. An unissued instrument, or an unissued incomplete instrument that is completed, is binding on the maker or drawer, but nonissuance is a defense. An instrument that is conditionally issued or is issued for a special purpose is binding on the maker or drawer, but failure of the condition or special purpose to be fulfilled is a defense.

.. "Issuer" applies to issued and unissued instruments and means a maker or drawer of an instrument.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%207[1993 c 229 § 7]; 1965 ex.s. c 157 § 3-105. Cf. former RCW  62.01.003; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.003[1955 c 35 § 62.01.003]; prior:  1899 c 149 § 3; RRS § 3394; ]

== 62A.3-106 - Unconditional promise or order.
.. Except as provided in this section, for the purposes of RCW 62A.3-104(a), a promise or order is unconditional unless it states (i) an express condition to payment, (ii) that the promise or order is subject to or governed by another writing, or (iii) that rights or obligations with respect to the promise or order are stated in another writing. A reference to another writing does not of itself make the promise or order conditional.

.. A promise or order is not made conditional (i) by a reference to another writing for a statement of rights with respect to collateral, prepayment, or acceleration, or (ii) because payment is limited to resort to a particular fund or source.

.. If a promise or order requires, as a condition to payment, a countersignature by a person whose specimen signature appears on the promise or order, the condition does not make the promise or order conditional for the purposes of RCW 62A.3-104(a). If the person whose specimen signature appears on an instrument fails to countersign the instrument, the failure to countersign is a defense to the obligation of the issuer, but the failure does not prevent a transferee of the instrument from becoming a holder of the instrument.

.. If a promise or order at the time it is issued or first comes into possession of a holder contains a statement, required by applicable statutory or administrative law, to the effect that the rights of a holder or transferee are subject to claims or defenses that the issuer could assert against the original payee, the promise or order is not thereby made conditional for the purposes of RCW 62A.3-104(a); but if the promise or order is an instrument, there cannot be a holder in due course of the instrument.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%208[1993 c 229 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c13.pdf?cite=1989%20c%2013%20§%201[1989 c 13 § 1]; 1965 ex.s. c 157 § 3-106. Cf. former RCW sections:  RCW  62.01.002; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.002[1955 c 35 § 62.01.002]; prior:  1899 c 149 § 2; RRS § 3393.  RCW  62.01.006(5); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.006[1955 c 35 § 62.01.006]; prior:  1899 c 149 § 6; RRS § 3397; ]

== 62A.3-107 - Instrument payable in foreign money.
Unless the instrument otherwise provides, an instrument that states the amount payable in foreign money may be paid in the foreign money or in an equivalent amount in dollars calculated by using the current bank-offered spot rate at the place of payment for the purchase of dollars on the day on which the instrument is paid.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%209[1993 c 229 § 9]; 1965 ex.s. c 157 § 3-107. Cf. former RCW  62.01.006(5); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.006[1955 c 35 § 62.01.006]; prior:  1899 c 149 § 6; RRS § 3397; ]

== 62A.3-108 - Payable on demand or at definite time.
.. A promise or order is "payable on demand" if it (i) states that it is payable on demand or at sight, or otherwise indicates that it is payable at the will of the holder, or (ii) does not state any time of payment.

.. A promise or order is "payable at a definite time" if it is payable on elapse of a definite period of time after sight or acceptance or at a fixed date or dates or at a time or times readily ascertainable at the time the promise or order is issued, subject to rights of (i) prepayment, (ii) acceleration, (iii) extension at the option of the holder, or (iv) extension to a further definite time at the option of the maker or acceptor or automatically upon or after a specified act or event.

.. If an instrument, payable at a fixed date, is also payable upon demand made before the fixed date, the instrument is payable on demand until the fixed date and, if demand for payment is not made before that date, becomes payable at a definite time on the fixed date.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2010[1993 c 229 § 10]; 1965 ex.s. c 157 § 3-108. Cf. former RCW  62.01.007; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.007[1955 c 35 § 62.01.007]; prior:  1899 c 149 § 7; RRS § 3398; ]

== 62A.3-109 - Payable to bearer or to order.
.. A promise or order is payable to bearer if it:

. States that it is payable to bearer or to the order of bearer or otherwise indicates that the person in possession of the promise or order is entitled to payment; 

. Does not state a payee; or

. States that it is payable to or to the order of cash or otherwise indicates that it is not payable to an identified person.

.. A promise or order that is not payable to bearer is payable to order if it is payable (i) to the order of an identified person or (ii) to an identified person or order. A promise or order that is payable to order is payable to the identified person.

.. An instrument payable to bearer may become payable to an identified person if it is specially indorsed pursuant to RCW 62A.3-205(a). An instrument payable to an identified person may become payable to bearer if it is indorsed in blank pursuant to RCW 62A.3-205(b).

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2011[1993 c 229 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c13.pdf?cite=1989%20c%2013%20§%202[1989 c 13 § 2]; 1965 ex.s. c 157 § 3-109. Cf. former RCW sections:  RCW  62.01.002(3); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.002[1955 c 35 § 62.01.002]; prior:  1899 c 149 § 2; RRS § 3393.  RCW  62.01.004; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.004[1955 c 35 § 62.01.004]; prior:  1899 c 149 § 4; RRS § 3395. (iii) RCW  62.01.017(3); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.017[1955 c 35 § 62.01.017]; prior:  1899 c 149 § 17; RRS § 3408; ]

== 62A.3-110 - Identification of person to whom instrument is payable.
.. The person to whom an instrument is initially payable is determined by the intent of the person, whether or not authorized, signing as, or in the name or behalf of, the issuer of the instrument. The instrument is payable to the person intended by the signer even if that person is identified in the instrument by a name or other identification that is not that of the intended person. If more than one person signs in the name or behalf of the issuer of an instrument and all the signers do not intend the same person as payee, the instrument is payable to any person intended by one or more of the signers.

.. If the signature of the issuer of an instrument is made by automated means, such as a check-writing machine, the payee of the instrument is determined by the intent of the person who supplied the name or identification of the payee, whether or not authorized to do so.

.. A person to whom an instrument is payable may be identified in any way, including by name, identifying number, office, or account number. For the purpose of determining the holder of an instrument, the following rules apply:

. If an instrument is payable to an account and the account is identified only by number, the instrument is payable to the person to whom the account is payable. If an instrument is payable to an account identified by number and by the name of a person, the instrument is payable to the named person, whether or not that person is the owner of the account identified by number.

. If an instrument is payable to:

... A trust, an estate, or a person described as trustee or representative of a trust or estate, the instrument is payable to the trustee, the representative, or a successor of either, whether or not the beneficiary or estate is also named;

... A person described as agent or similar representative of a named or identified person, the instrument is payable to the represented person, the representative, or a successor of the representative;

... A fund or organization that is not a legal entity, the instrument is payable to a representative of the members of the fund or organization; or

... An office or to a person described as holding an office, the instrument is payable to the named person, the incumbent of the office, or a successor to the incumbent.

.. If an instrument is payable to two or more persons alternatively, it is payable to any of them and may be negotiated, discharged, or enforced by any or all of them in possession of the instrument. If an instrument is payable to two or more persons not alternatively, it is payable to all of them and may be negotiated, discharged, or enforced only by all of them. If an instrument payable to two or more persons is ambiguous as to whether it is payable to the persons alternatively, the instrument is payable to the persons alternatively.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2012[1993 c 229 § 12]; 1965 ex.s. c 157 § 3-110. Cf. former RCW  62.01.008; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.008[1955 c 35 § 62.01.008]; prior:  1899 c 149 § 8; RRS § 3399; ]

== 62A.3-111 - Place of payment.
Except as otherwise provided for items in Article 4, an instrument is payable at the place of payment stated in the instrument. If no place of payment is stated, an instrument is payable at the address of the drawee or maker stated in the instrument. If no address is stated, the place of payment is the place of business of the drawee or maker. If a drawee or maker has more than one place of business, the place of payment is any place of business of the drawee or maker chosen by the person entitled to enforce the instrument. If the drawee or maker has no place of business, the place of payment is the residence of the drawee or maker.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2013[1993 c 229 § 13]; 1965 ex.s. c 157 § 3-111. Cf. former RCW  62.01.009; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.009[1955 c 35 § 62.01.009]; prior:  1899 c 149 § 9; RRS § 3400; ]

== 62A.3-112 - Interest.
.. Unless otherwise provided in the instrument or in RCW 19.52.010, (i) an instrument is not payable with interest, and (ii) interest on an interest-bearing instrument is payable from the date of the instrument.

.. Interest may be stated in an instrument as a fixed or variable amount of money or it may be expressed as a fixed or variable rate or rates. The amount or rate of interest may be stated or described in the instrument in any manner and may require reference to information not contained in the instrument. If an instrument provides for interest, but the amount of interest payable cannot be ascertained from the description, then except as otherwise provided in RCW 19.52.010, interest is payable at the judgment rate in effect at the place of payment of the instrument and at the time interest first accrues.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1182-S2.SL.pdf?cite=1996%20c%2077%20§%203[1996 c 77 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2014[1993 c 229 § 14]; 1965 ex.s. c 157 § 3-112. Cf. former RCW sections:  62.01.005; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.005[1955 c 35 § 62.01.005]; prior:  1899 c 149 § 5; RRS § 3396.  RCW  62.01.006; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.006[1955 c 35 § 62.01.006]; prior:  1899 c 149 § 6; RRS § 3397; ]

== 62A.3-113 - Date of instrument.
.. An instrument may be antedated or postdated. The date stated determines the time of payment if the instrument is payable at a fixed period after date. Except as provided in RCW 62A.4-401(c), an instrument payable on demand is not payable before the date of the instrument.

.. If an instrument is undated, its date is the date of its issue or, in the case of an unissued instrument, the date it first comes into possession of a holder.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2015[1993 c 229 § 15]; 1965 ex.s. c 157 § 3-113. Cf. former RCW  62.01.006(4); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.006[1955 c 35 § 62.01.006]; prior:  1899 c 149 § 6; RRS § 3397; ]

== 62A.3-114 - Contradictory terms of instrument.
If an instrument contains contradictory terms, typewritten terms prevail over printed terms, handwritten terms prevail over both, and words prevail over numbers.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2016[1993 c 229 § 16]; 1965 ex.s. c 157 § 3-114. Cf. former RCW sections:  RCW  62.01.006; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.006[1955 c 35 § 62.01.006]; prior:  1899 c 149 § 6; RRS § 3397.  RCW  62.01.011; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.011[1955 c 35 § 62.01.011]; prior:  1899 c 149 § 11; RRS § 3402. (iii) RCW  62.01.012; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.012[1955 c 35 § 62.01.012]; prior:  1899 c 149 § 12; RRS § 3403. (iv) RCW  62.01.017(3); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.017[1955 c 35 § 62.01.017]; prior:  1899 c 149 § 17; RRS § 3408; ]

== 62A.3-115 - Incomplete instrument.
.. "Incomplete instrument" means a signed writing, whether or not issued by the signer, the contents of which show at the time of signing that it is incomplete but that the signer intended it to be completed by the addition of words or numbers.

.. Subject to subsection (c), if an incomplete instrument is an instrument under RCW 62A.3-104, it may be enforced according to its terms if it is not completed, or according to its terms as augmented by completion. If an incomplete instrument is not an instrument under RCW 62A.3-104, but, after completion, the requirements of RCW 62A.3-104 are met, the instrument may be enforced according to its terms as augmented by completion.

.. If words or numbers are added to an incomplete instrument without authority of the signer, there is an alteration of the incomplete instrument under RCW 62A.3-407.

.. The burden of establishing that words or numbers were added to an incomplete instrument without authority of the signer is on the person asserting the lack of authority.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2017[1993 c 229 § 17]; 1965 ex.s. c 157 § 3-115. Cf. former RCW sections:  RCW  62.01.013; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.013[1955 c 35 § 62.01.013]; prior:  1899 c 149 § 13; RRS § 3404.  RCW  62.01.014; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.014[1955 c 35 § 62.01.014]; prior:  1899 c 149 § 14; RRS § 3405. (iii) RCW  62.01.015; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.015[1955 c 35 § 62.01.015]; prior:  1899 c 149 § 15; RRS § 3406; ]

== 62A.3-116 - Joint and several liability; contribution.
.. Except as otherwise provided in the instrument, two or more persons who have the same liability on an instrument as makers, drawers, acceptors, indorsers who indorse as joint payees, or anomalous indorsers are jointly and severally liable in the capacity in which they sign.

.. Except as provided in RCW 62A.3-419(e) or by agreement of the affected parties, a party having joint and several liability who pays the instrument is entitled to receive from any party having the same joint and several liability contribution in accordance with applicable law.

.. Discharge of one party having joint and several liability by a person entitled to enforce the instrument does not affect the right under subsection (b) of a party having the same joint and several liability to receive contribution from the party discharged.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2018[1993 c 229 § 18]; 1965 ex.s. c 157 § 3-116. Cf. former RCW  62.01.041; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.041[1955 c 35 § 62.01.041]; prior:  1899 c 149 § 41; RRS § 3432; ]

== 62A.3-117 - Other agreements affecting instrument.
Subject to applicable law regarding exclusion of proof of contemporaneous or previous agreements, the obligation of a party to an instrument to pay the instrument may be modified, supplemented, or nullified by a separate agreement of the obligor and a person entitled to enforce the instrument, if the instrument is issued or the obligation is incurred in reliance on the agreement or as part of the same transaction giving rise to the agreement. To the extent an obligation is modified, supplemented, or nullified by an agreement under this section, the agreement is a defense to the obligation.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2019[1993 c 229 § 19]; 1965 ex.s. c 157 § 3-117. Cf. former RCW  62.01.042; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.042[1955 c 35 § 62.01.042]; prior:  1899 c 149 § 42; RRS § 3433; ]

== 62A.3-118 - Statute of limitations.
.. Except as provided in subsection (e), an action to enforce the obligation of a party to pay a note payable at a definite time must be commenced within six years after the due date or dates stated in the note or, if a due date is accelerated, within six years after the accelerated due date.

.. Except as provided in subsection (d) or (e), if demand for payment is made to the maker of a note payable on demand, an action to enforce the obligation of a party to pay the note must be commenced within six years after the demand. If no demand for payment is made to the maker, an action to enforce the note is barred if neither principal nor interest on the note has been paid for a continuous period of ten years.

.. Except as provided in subsection (d), an action to enforce the obligation of a party to an unaccepted draft to pay the draft must be commenced within six years after dishonor of the draft or ten years after the date of the draft, whichever period expires first.

.. An action to enforce the obligation of the acceptor of a certified check or the issuer of a teller's check, cashier's check, or traveler's check must be commenced within three years after demand for payment is made to the acceptor or issuer, as the case may be.

.. An action to enforce the obligation of a party to a certificate of deposit to pay the instrument must be commenced within six years after demand for payment is made to the maker, but if the instrument states a due date and the maker is not required to pay before that date, the six-year period begins when a demand for payment is in effect and the due date has passed.

.. An action to enforce the obligation of a party to pay an accepted draft, other than a certified check, must be commenced (i) within six years after the due date or dates stated in the draft or acceptance if the obligation of the acceptor is payable at a definite time, or (ii) within six years after the date of the acceptance if the obligation of the acceptor is payable on demand.

.. Unless governed by other law regarding claims for indemnity or contribution, an action (i) for conversion of an instrument, for money had and received, or like action based on conversion, (ii) for breach of warranty, or (iii) to enforce an obligation, duty, or right arising under this Article and not governed by this section must be commenced within three years after the cause of action accrues.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5165.SL.pdf?cite=1995%20c%2074%20§%201[1995 c 74 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2020[1993 c 229 § 20]; 1965 ex.s. c 157 § 3-118. Cf. former RCW sections:  RCW  62.01.017; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.017[1955 c 35 § 62.01.017]; prior:  1899 c 149 § 17; RRS § 3408.  RCW  62.01.068; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.068[1955 c 35 § 62.01.068]; prior:  1899 c 149 § 68; RRS § 3459. (iii) RCW  62.01.130; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.130[1955 c 35 § 62.01.130]; prior:  1899 c 149 § 130; RRS § 3520; ]

== 62A.3-119 - Notice of right to defend action.
In an action for breach of an obligation for which a third person is answerable over pursuant to this Article or Article 4, the defendant may give the third person written notice of the litigation, and the person notified may then give similar notice to any other person who is answerable over. If the notice states (i) that the person notified may come in and defend and (ii) that failure to do so will bind the person notified in an action later brought by the person giving the notice as to any determination of fact common to the two litigations, the person notified is so bound unless after seasonable receipt of the notice the person notified does come in and defend.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2021[1993 c 229 § 21]; 1965 ex.s. c 157 § 3-119; ]

== 62A.3-201 - Negotiation.
.. "Negotiation" means a transfer of possession, whether voluntary or involuntary, of an instrument by a person other than the issuer to a person who thereby becomes its holder.

.. Except for negotiation by a remitter, if an instrument is payable to an identified person, negotiation requires transfer of possession of the instrument and its indorsement by the holder. If an instrument is payable to bearer, it may be negotiated by transfer of possession alone.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2022[1993 c 229 § 22]; 1965 ex.s. c 157 § 3-201. Cf. former RCW sections:  RCW  62.01.027; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.027[1955 c 35 § 62.01.027]; prior:  1899 c 149 § 27; RRS § 3418.  RCW  62.01.049; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.049[1955 c 35 § 62.01.049]; prior:  1899 c 149 § 49; RRS § 3440. (iii) RCW  62.01.058; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.058[1955 c 35 § 62.01.058]; prior:  1899 c 149 § 58; RRS § 3449; ]

== 62A.3-202 - Negotiation subject to rescission.
.. Negotiation is effective even if obtained (i) from an infant, a corporation exceeding its powers, or a person without capacity, (ii) by fraud, duress, or mistake, or (iii) in breach of duty or as part of an illegal transaction.

.. To the extent permitted by other law, negotiation may be rescinded or may be subject to other remedies, but those remedies may not be asserted against a subsequent holder in due course or a person paying the instrument in good faith and without knowledge of facts that are a basis for rescission or other remedy.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2023[1993 c 229 § 23]; 1965 ex.s. c 157 § 3-202. Cf. former RCW sections:  RCW  62.01.030; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.030[1955 c 35 § 62.01.030]; prior:  1899 c 149 § 30; RRS § 3421.  RCW  62.01.031; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.031[1955 c 35 § 62.01.031]; prior:  1899 c 149 § 31; RRS § 3422. (iii) RCW  62.01.032; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.032[1955 c 35 § 62.01.032]; prior:  1899 c 149 § 32; RRS § 3423; ]

== 62A.3-203 - Transfer of instrument; rights acquired by transfer.
.. An instrument is transferred when it is delivered by a person other than its issuer for the purpose of giving to the person receiving delivery the right to enforce the instrument.

.. Transfer of an instrument, whether or not the transfer is a negotiation, vests in the transferee any right of the transferor to enforce the instrument, including any right as a holder in due course, but the transferee cannot acquire rights of a holder in due course by a transfer, directly or indirectly, from a holder in due course if the transferee engaged in fraud or illegality affecting the instrument.

.. Unless otherwise agreed, if an instrument is transferred for value and the transferee does not become a holder because of lack of indorsement by the transferor, the transferee has a specifically enforceable right to the unqualified indorsement of the transferor, but negotiation of the instrument does not occur until the indorsement is made.

.. If a transferor purports to transfer less than the entire instrument, negotiation of the instrument does not occur. The transferee obtains no rights under this Article and has only the rights of a partial assignee.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2024[1993 c 229 § 24]; 1965 ex.s. c 157 § 3-203. Cf. former RCW  62.01.043; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.043[1955 c 35 § 62.01.043]; prior:  1899 c 149 § 43; RRS § 3434; ]

== 62A.3-204 - Indorsement.
.. "Indorsement" means a signature, other than that of a signer as maker, drawer, or acceptor, that alone or accompanied by other words is made on an instrument for the purpose of (i) negotiating the instrument, (ii) restricting payment of the instrument, or (iii) incurring indorser's liability on the instrument, but regardless of the intent of the signer, a signature and its accompanying words is an indorsement unless the accompanying words, terms of the instrument, place of the signature, or other circumstances unambiguously indicate that the signature was made for a purpose other than indorsement. For the purpose of determining whether a signature is made on an instrument, a paper affixed to the instrument is a part of the instrument.

.. "Indorser" means a person who makes an indorsement.

.. For the purpose of determining whether the transferee of an instrument is a holder, an indorsement that transfers a security interest in the instrument is effective as an unqualified indorsement of the instrument.

.. If an instrument is payable to a holder under a name that is not the name of the holder, indorsement may be made by the holder in the name stated in the instrument or in the holder's name or both, but signature in both names may be required by a person paying or taking the instrument for value or collection.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2025[1993 c 229 § 25]; 1965 ex.s. c 157 § 3-204. Cf. former RCW sections:  RCW  62.01.009(5); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.009[1955 c 35 § 62.01.009]; prior:  1899 c 149 § 9; RRS § 3400.  RCW  62.01.033 through  62.01.036; 1955 c 35 §§ 62.01.033 through  62.01.036; prior: 1899 c 149 §§ 33 through 36; RRS §§ 3424 through 3427. (iii) RCW  62.01.040; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.040[1955 c 35 § 62.01.040]; prior:  1899 c 149 § 40; RRS § 3431; ]

== 62A.3-205 - Special indorsement; blank indorsement; anomalous indorsement.
.. If an indorsement is made by the holder of an instrument, whether payable to an identified person or payable to bearer, and the indorsement identifies a person to whom it makes the instrument payable, it is a "special indorsement." When specially indorsed, an instrument becomes payable to the identified person and may be negotiated only by the indorsement of that person. The principles stated in RCW 62A.3-110 apply to special indorsements.

.. If an indorsement is made by the holder of an instrument and it is not a special indorsement, it is a "blank indorsement." When indorsed in blank, an instrument becomes payable to bearer and may be negotiated by transfer of possession alone until specially indorsed.

.. The holder may convert a blank indorsement that consists only of a signature into a special indorsement by writing, above the signature of the indorser, words identifying the person to whom the instrument is made payable.

.. "Anomalous indorsement" means an indorsement made by a person who is not the holder of the instrument. An anomalous indorsement does not affect the manner in which the instrument may be negotiated.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2026[1993 c 229 § 26]; 1965 ex.s. c 157 § 3-205. Cf. former RCW sections:  RCW  62.01.036; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.036[1955 c 35 § 62.01.036]; prior:  1899 c 149 § 36; RRS § 3427.  RCW  62.01.039; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.039[1955 c 35 § 62.01.039]; prior:  1899 c 149 § 39; RRS § 3430; ]

== 62A.3-206 - Restrictive indorsement.
.. An indorsement limiting payment to a particular person or otherwise prohibiting further transfer or negotiation of the instrument is not effective to prevent further transfer or negotiation of the instrument.

.. An indorsement stating a condition to the right of the indorsee to receive payment does not affect the right of the indorsee to enforce the instrument. A person paying the instrument or taking it for value or collection may disregard the condition, and the rights and liabilities of that person are not affected by whether the condition has been fulfilled.

.. If an instrument bears an indorsement (i) described in RCW 62A.4-201(b), or (ii) in blank or to a particular bank using the words "for deposit," "for collection," or other words indicating a purpose of having the instrument collected by a bank for the indorser or for a particular account, the following rules apply:

. A person, other than a bank, who purchases the instrument when so indorsed converts the instrument unless the amount paid for the instrument is received by the indorser or applied consistently with the indorsement.

. A depositary bank that purchases the instrument or takes it for collection when so indorsed converts the instrument unless the amount paid by the bank with respect to the instrument is received by the indorser or applied consistently with the indorsement.

. A payor bank that is also the depositary bank or that takes the instrument for immediate payment over the counter from a person other than a collecting bank converts the instrument unless the proceeds of the instrument are received by the indorser or applied consistently with the indorsement.

. Except as otherwise provided in subsection (c)(3), a payor bank or intermediary bank may disregard the indorsement and is not liable if the proceeds of the instrument are not received by the indorser or applied consistently with the indorsement.

.. Except for an indorsement covered by subsection (c), if an instrument bears an indorsement using words to the effect that payment is to be made to the indorsee as agent, trustee, or other fiduciary for the benefit of the indorser or another person, the following rules apply:

. Unless there is notice of breach of fiduciary duty as provided in RCW 62A.3-307, a person who purchases the instrument from the indorsee or takes the instrument from the indorsee for collection or payment may pay the proceeds of payment or the value given for the instrument to the indorsee without regard to whether the indorsee violates a fiduciary duty to the indorser.

. A subsequent transferee of the instrument or person who pays the instrument is neither given notice nor otherwise affected by the restriction in the indorsement unless the transferee or payor knows that the fiduciary dealt with the instrument or its proceeds in breach of fiduciary duty.

.. The presence on an instrument of an indorsement to which this section applies does not prevent a purchaser of the instrument from becoming a holder in due course of the instrument unless the purchaser is a converter under subsection (c) or has notice or knowledge of breach of fiduciary duty as stated in subsection (d).

.. In an action to enforce the obligation of a party to pay the instrument, the obligor has a defense if payment would violate an indorsement to which this section applies and the payment is not permitted by this section.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2027[1993 c 229 § 27]; 1965 ex.s. c 157 § 3-206. Cf. former RCW sections:  RCW  62.01.036; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.036[1955 c 35 § 62.01.036]; prior:  1899 c 149 § 36; RRS § 3427.  RCW  62.01.037; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.037[1955 c 35 § 62.01.037]; prior:  1899 c 149 § 37; RRS § 3428. (iii) RCW  62.01.039; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.039[1955 c 35 § 62.01.039]; prior:  1899 c 149 § 39; RRS § 3430. (iv) RCW  62.01.047; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.047[1955 c 35 § 62.01.047]; prior:  1899 c 149 § 47; RRS § 3438; ]

== 62A.3-207 - Reacquisition.
Reacquisition of an instrument occurs if it is transferred to a former holder, by negotiation or otherwise. A former holder who reacquires the instrument may cancel indorsements made after the reacquirer first became a holder of the instrument. If the cancellation causes the instrument to be payable to the reacquirer or to bearer, the reacquirer may negotiate the instrument. An indorser whose indorsement is canceled is discharged, and the discharge is effective against any subsequent holder.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2028[1993 c 229 § 28]; 1965 ex.s. c 157 § 3-207. Cf. former RCW sections:  RCW  62.01.022; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.022[1955 c 35 § 62.01.022]; prior:  1899 c 149 § 22; RRS § 3413.  RCW  62.01.058; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.058[1955 c 35 § 62.01.058]; prior:  1899 c 149 § 58; RRS § 3449. (iii) RCW  62.01.059; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.059[1955 c 35 § 62.01.059]; prior:  1899 c 149 § 59; RRS § 3450; ]

== 62A.3-301 - Person entitled to enforce instrument.
"Person entitled to enforce" an instrument means (i) the holder of the instrument, (ii) a nonholder in possession of the instrument who has the rights of a holder, or (iii) a person not in possession of the instrument who is entitled to enforce the instrument pursuant to RCW 62A.3-309 or 62A.3-418(d). A person may be a person entitled to enforce the instrument even though the person is not the owner of the instrument or is in wrongful possession of the instrument.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2029[1993 c 229 § 29]; 1965 ex.s. c 157 § 3-301. Cf. former RCW  62.01.051; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.051[1955 c 35 § 62.01.051]; prior:  1899 c 149 § 51; RRS § 3442; ]

== 62A.3-302 - Holder in due course.
.. Subject to subsection (c) and RCW 62A.3-106(d), "holder in due course" means the holder of an instrument if:

. The instrument when issued or negotiated to the holder does not bear such apparent evidence of forgery or alteration or is not otherwise so irregular or incomplete as to call into question its authenticity; and

. The holder took the instrument (i) for value, (ii) in good faith, (iii) without notice that the instrument is overdue or has been dishonored or that there is an uncured default with respect to payment of another instrument issued as part of the same series, (iv) without notice that the instrument contains an unauthorized signature or has been altered, (v) without notice of any claim to the instrument described in RCW 62A.3-306, and (vi) without notice that any party has a defense or claim in recoupment described in RCW 62A.3-305(a).

.. Notice of discharge of a party, other than discharge in an insolvency proceeding, is not notice of a defense under subsection (a), but discharge is effective against a person who became a holder in due course with notice of the discharge. Public filing or recording of a document does not of itself constitute notice of a defense, claim in recoupment, or claim to the instrument.

.. Except to the extent a transferor or predecessor in interest has rights as a holder in due course, a person does not acquire rights of a holder in due course of an instrument taken (i) by legal process or by purchase in an execution, bankruptcy, or creditor's sale or similar proceeding, (ii) by purchase as part of a bulk transaction not in ordinary course of business of the transferor, or (iii) as the successor in interest to an estate or other organization.

.. If, under RCW 62A.3-303(a)(1), the promise of performance that is the consideration for an instrument has been partially performed, the holder may assert rights as a holder in due course of the instrument only to the fraction of the amount payable under the instrument equal to the value of the partial performance divided by the value of the promised performance.

.. If (i) the person entitled to enforce an instrument has only a security interest in the instrument and (ii) the person obliged to pay the instrument has a defense, claim in recoupment, or claim to the instrument that may be asserted against the person who granted the security interest, the person entitled to enforce the instrument may assert rights as a holder in due course only to an amount payable under the instrument which, at the time of enforcement of the instrument, does not exceed the amount of the unpaid obligation secured.

.. To be effective, notice must be received at a time and in a manner that gives a reasonable opportunity to act on it.

.. This section is subject to any law limiting status as a holder in due course in particular classes of transactions.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2030[1993 c 229 § 30]; 1965 ex.s. c 157 § 3-302. Cf. former RCW sections:  RCW  62.01.027; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.027[1955 c 35 § 62.01.027]; prior:  1899 c 149 § 27; RRS § 3418.  RCW  62.01.052; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.052[1955 c 35 § 62.01.052]; prior:  1899 c 149 § 52; RRS § 3443; ]

== 62A.3-303 - Value and consideration.
.. An instrument is issued or transferred for value if:

. The instrument is issued or transferred for a promise of performance, to the extent the promise has been performed;

. The transferee acquires a security interest or other lien in the instrument other than a lien obtained by judicial proceeding;

. The instrument is issued or transferred as payment of, or as security for, an antecedent claim against any person, whether or not the claim is due;

. The instrument is issued or transferred in exchange for a negotiable instrument; or

. The instrument is issued or transferred in exchange for the incurring of an irrevocable obligation to a third party by the person taking the instrument.

.. "Consideration" means any consideration sufficient to support a simple contract. The drawer or maker of an instrument has a defense if the instrument is issued without consideration. If an instrument is issued for a promise of performance, the issuer has a defense to the extent performance of the promise is due and the promise has not been performed. If an instrument is issued for value as stated in subsection (a), the instrument is also issued for consideration.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2031[1993 c 229 § 31]; 1965 ex.s. c 157 § 3-303. Cf. former RCW sections:  RCW  62.01.025 through  62.01.027; 1955 c 35 §§ 62.01.025 through  62.01.027; prior: 1899 c 149 §§ 25 through 27; RRS §§ 3416 through 3418.  RCW  62.01.054; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.054[1955 c 35 § 62.01.054]; prior:  1899 c 149 § 54; RRS § 3445; ]

== 62A.3-304 - Overdue instrument.
.. An instrument payable on demand becomes overdue at the earliest of the following times:

. On the day after the day demand for payment is duly made;

. If the instrument is a check, 90 days after its date; or

. If the instrument is not a check, when the instrument has been outstanding for a period of time after its date which is unreasonably long under the circumstances of the particular case in light of the nature of the instrument and usage of the trade.

.. With respect to an instrument payable at a definite time the following rules apply:

. If the principal is payable in installments and a due date has not been accelerated, the instrument becomes overdue upon default under the instrument for nonpayment of an installment, and the instrument remains overdue until the default is cured.

. If the principal is not payable in installments and the due date has not been accelerated, the instrument becomes overdue on the day after the due date.

. If a due date with respect to principal has been accelerated, the instrument becomes overdue on the day after the accelerated due date.

.. Unless the due date of principal has been accelerated, an instrument does not become overdue if there is default in payment of interest but no default in payment of principal.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2032[1993 c 229 § 32]; 1965 ex.s. c 157 § 3-304. Cf. former RCW sections:  RCW  62.01.045,  62.01.052,  62.01.053,  62.01.055, and  62.01.056; 1955 c 35 §§ 62.01.045,  62.01.052,  62.01.053,  62.01.055, and  62.01.056; prior: 1899 c 149 §§ 45, 52, 53, 55, and 56; RRS §§ 3436, 3443, 3444, 3446, and 3447.  RCW  62.01.0195; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.0195[1955 c 35 § 62.01.0195]; prior:  1927 c 296 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c54.pdf?cite=1925%20ex.s.%20c%2054%20§%201[1925 ex.s. c 54 § 1]; RRS § 3410-1; ]

== 62A.3-305 - Defenses and claims in recoupment.
.. Except as stated in subsection (b), the right to enforce the obligation of a party to pay an instrument is subject to the following:

. A defense of the obligor based on (i) infancy of the obligor to the extent it is a defense to a simple contract, (ii) duress, lack of legal capacity, or illegality of the transaction which, under other law, nullifies the obligation of the obligor, (iii) fraud that induced the obligor to sign the instrument with neither knowledge nor reasonable opportunity to learn of its character or its essential terms, or (iv) discharge of the obligor in insolvency proceedings;

. A defense of the obligor stated in another section of this Article or a defense of the obligor that would be available if the person entitled to enforce the instrument were enforcing a right to payment under a simple contract; and

. A claim in recoupment of the obligor against the original payee of the instrument if the claim arose from the transaction that gave rise to the instrument; but the claim of the obligor may be asserted against a transferee of the instrument only to reduce the amount owing on the instrument at the time the action is brought.

.. The right of a holder in due course to enforce the obligation of a party to pay the instrument is subject to defenses of the obligor stated in subsection (a)(1), but is not subject to defenses of the obligor stated in subsection (a)(2) or claims in recoupment stated in subsection (a)(3) against a person other than the holder.

.. Except as stated in subsection (d), in an action to enforce the obligation of a party to pay the instrument, the obligor may not assert against the person entitled to enforce the instrument a defense, claim in recoupment, or claim to the instrument (RCW 62A.3-306) of another person, but the other person's claim to the instrument may be asserted by the obligor if the other person is joined in the action and personally asserts the claim against the person entitled to enforce the instrument. An obligor is not obliged to pay the instrument if the person seeking enforcement of the instrument does not have rights of a holder in due course and the obligor proves that the instrument is a lost or stolen instrument.

.. In an action to enforce the obligation of an accommodation party to pay an instrument, the accommodation party may assert against the person entitled to enforce the instrument any defense or claim in recoupment under subsection (a) that the accommodated party could assert against the person entitled to enforce the instrument, except the defenses of discharge in insolvency proceedings, infancy, and lack of legal capacity.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2033[1993 c 229 § 33]; 1965 ex.s. c 157 § 3-305. Cf. former RCW sections:  RCW  62.01.015; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.015[1955 c 35 § 62.01.015]; prior:  1899 c 149 § 15; RRS § 3406.  RCW  62.01.016; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.016[1955 c 35 § 62.01.016]; prior:  1899 c 149 § 16; RRS § 3407. (iii) RCW  62.01.057; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.057[1955 c 35 § 62.01.057]; prior:  1899 c 149 § 57; RRS § 3448; ]

== 62A.3-306 - Claims to an instrument.
A person taking an instrument, other than a person having rights of a holder in due course, is subject to a claim of a property or possessory right in the instrument or its proceeds, including a claim to rescind a negotiation and to recover the instrument or its proceeds. A person having rights of a holder in due course takes free of the claim to the instrument.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2034[1993 c 229 § 34]; 1965 ex.s. c 157 § 3-306. Cf. former RCW sections:  RCW  62.01.016; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.016[1955 c 35 § 62.01.016]; prior:  1899 c 149 § 16; RRS § 3407.  RCW  62.01.028; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.028[1955 c 35 § 62.01.028]; prior:  1899 c 149 § 28; RRS § 3419. (iii) RCW  62.01.058; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.058[1955 c 35 § 62.01.058]; prior:  1899 c 149 § 58; RRS § 3449. (iv) RCW  62.01.059; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.059[1955 c 35 § 62.01.059]; prior:  1899 c 149 § 59; RRS § 3450; ]

== 62A.3-307 - Notice of breach of fiduciary duty.
.. In this section:

. "Fiduciary" means an agent, trustee, partner, corporate officer or director, or other representative owing a fiduciary duty with respect to an instrument.

. "Represented person" means the principal, beneficiary, partnership, corporation, or other person to whom the duty stated in subsection (a)(1) is owed.

.. If (i) an instrument is taken from a fiduciary for payment or collection or for value, (ii) the taker has knowledge of the fiduciary status of the fiduciary, and (iii) the represented person makes a claim to the instrument or its proceeds on the basis that the transaction of the fiduciary is a breach of fiduciary duty, the following rules apply:

. Notice of breach of fiduciary duty by the fiduciary is notice of the claim of the represented person.

. In the case of an instrument payable to the represented person or the fiduciary as such, the taker has notice of the breach of fiduciary duty if the instrument is (i) taken in payment of or as security for a debt known by the taker to be the personal debt of the fiduciary, (ii) taken in a transaction known by the taker to be for the personal benefit of the fiduciary, or (iii) deposited to an account other than an account of the fiduciary, as such, or an account of the represented person.

. If an instrument is issued by the represented person or the fiduciary as such, and made payable to the fiduciary personally, the taker does not have notice of the breach of fiduciary duty unless the taker knows of the breach of fiduciary duty.

. If an instrument is issued by the represented person or the fiduciary as such, to the taker as payee, the taker has notice of the breach of fiduciary duty if the instrument is (i) taken in payment of or as security for a debt known by the taker to be the personal debt of the fiduciary, (ii) taken in a transaction known by the taker to be for the personal benefit of the fiduciary, or (iii) deposited to an account other than an account of the fiduciary, as such, or an account of the represented person.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2035[1993 c 229 § 35]; 1965 ex.s. c 157 § 3-307. Cf. former RCW  62.01.059; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.059[1955 c 35 § 62.01.059]; prior:  1899 c 149 § 59; RRS § 3450; ]

== 62A.3-308 - Proof of signatures and status as holder in due course.
.. In an action with respect to an instrument, the authenticity of, and authority to make, each signature on the instrument is admitted unless specifically denied in the pleadings. If the validity of a signature is denied in the pleadings, the burden of establishing validity is on the person claiming validity, but the signature is presumed to be authentic and authorized unless the action is to enforce the liability of the purported signer and the signer is dead or incompetent at the time of trial of the issue of validity of the signature. If an action to enforce the instrument is brought against a person as the undisclosed principal of a person who signed the instrument as a party to the instrument, the plaintiff has the burden of establishing that the defendant is liable on the instrument as a represented person under RCW 62A.3-402(a).

.. If the validity of signatures is admitted or proved and there is compliance with subsection (a), a plaintiff producing the instrument is entitled to payment if the plaintiff proves entitlement to enforce the instrument under RCW 62A.3-301, unless the defendant proves a defense or claim in recoupment. If a defense or claim in recoupment is proved, the right to payment of the plaintiff is subject to the defense or claim, except to the extent the plaintiff proves that the plaintiff has rights of a holder in due course which are not subject to the defense or claim.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2036[1993 c 229 § 36]; ]

== 62A.3-309 - Enforcement of lost, destroyed, or stolen instrument.
.. A person not in possession of an instrument is entitled to enforce the instrument if (i) the person was in possession of the instrument and entitled to enforce it when loss of possession occurred, (ii) the loss of possession was not the result of a transfer by the person or a lawful seizure, and (iii) the person cannot reasonably obtain possession of the instrument because the instrument was destroyed, its whereabouts cannot be determined, or it is in the wrongful possession of an unknown person or a person that cannot be found or is not amenable to service of process.

.. A person seeking enforcement of an instrument under subsection (a) must prove the terms of the instrument and the person's right to enforce the instrument. If that proof is made, RCW 62A.3-308 applies to the case as if the person seeking enforcement had produced the instrument. The court may not enter judgment in favor of the person seeking enforcement unless it finds that the person required to pay the instrument is adequately protected against loss that might occur by reason of a claim by another person to enforce the instrument. Adequate protection may be provided by any reasonable means.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2037[1993 c 229 § 37]; ]

== 62A.3-310 - Effect of instrument on obligation for which taken.
.. Unless otherwise agreed, if a certified check, cashier's check, or teller's check is taken for an obligation, the obligation is discharged to the same extent discharge would result if an amount of money equal to the amount of the instrument were taken in payment of the obligation. Discharge of the obligation does not affect any liability that the obligor may have as an indorser of the instrument.

.. Unless otherwise agreed and except as provided in subsection (a), if a note or an uncertified check is taken for an obligation, the obligation is suspended to the same extent the obligation would be discharged if an amount of money equal to the amount of the instrument were taken, and the following rules apply:

. In the case of an uncertified check, suspension of the obligation continues until dishonor of the check or until it is paid or certified. Payment or certification of the check results in discharge of the obligation to the extent of the amount of the check.

. In the case of a note, suspension of the obligation continues until dishonor of the note or until it is paid. Payment of the note results in discharge of the obligation to the extent of the payment.

. Except as provided in subsection (b)(4), if the check or note is dishonored and the obligee of the obligation for which the instrument was taken is the person entitled to enforce the instrument, the obligee may enforce either the instrument or the obligation. In the case of an instrument of a third person which is negotiated to the obligee by the obligor, discharge of the obligor on the instrument also discharges the obligation.

. If the person entitled to enforce the instrument taken for an obligation is a person other than the obligee, the obligee may not enforce the obligation to the extent the obligation is suspended. If the obligee is the person entitled to enforce the instrument but no longer has possession of it because it was lost, stolen, or destroyed, the obligation may not be enforced to the extent of the amount payable on the instrument, and to that extent the obligee's rights against the obligor are limited to enforcement of the instrument.

.. If an instrument other than one described in subsection (a) or (b) is taken for an obligation, the effect is (i) that stated in subsection (a) if the instrument is one on which a bank is liable as maker or acceptor, or (ii) that stated in subsection (b) in any other case.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2038[1993 c 229 § 38]; ]

== 62A.3-311 - Accord and satisfaction by use of instrument.
.. If a person against whom a claim is asserted proves that (i) that person in good faith tendered an instrument to the claimant as full satisfaction of the claim, (ii) the amount of the claim was unliquidated or subject to a bona fide dispute, and (iii) the claimant obtained payment of the instrument, the following subsections apply.

.. Unless subsection (c) applies, the claim is discharged if the person against whom the claim is asserted proves that the instrument or an accompanying written communication contained a conspicuous statement to the effect that the instrument was tendered as full satisfaction of the claim.

.. Subject to subsection (d), a claim is not discharged under subsection (b) if either of the following applies:

. The claimant, if an organization, proves that (i) within a reasonable time before the tender, the claimant sent a conspicuous statement to the person against whom the claim is asserted that communications concerning disputed debts, including an instrument tendered as full satisfaction of a debt, are to be sent to a designated person, office, or place, and (ii) the instrument or accompanying communication was not received by that designated person, office, or place.

. The claimant, whether or not an organization, proves that within 90 days after payment of the instrument, the claimant tendered repayment of the amount of the instrument to the person against whom the claim is asserted. This subsection (c)(2) does not apply if the claimant is an organization that sent a statement complying with subsection (c)(1)(i).

.. A claim is discharged if the person against whom the claim is asserted proves that within a reasonable time before collection of the instrument was initiated, the claimant, or an agent of the claimant having direct responsibility with respect to the disputed obligation, knew that the instrument was tendered in full satisfaction of the claim.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2039[1993 c 229 § 39]; ]

== 62A.3-312 - Lost, destroyed, or stolen cashier's check, teller's check, or certified check.
.. In this section:

. "Check" means a cashier's check, teller's check, or certified check.

. "Claimant" means a person who claims the right to receive the amount of a cashier's check, teller's check, or certified check that was lost, destroyed, or stolen.

. "Declaration of loss" means a written statement, made under penalty of perjury, to the effect that (i) the declarer lost possession of a check, (ii) the declarer is the drawer or payee of the check, in the case of a certified check, or the remitter or payee of the check, in the case of a cashier's check or teller's check, (iii) the loss of possession was not the result of a transfer by the declarer or a lawful seizure, and (iv) the declarer cannot reasonably obtain possession of the check because the check was destroyed, its whereabouts cannot be determined, or it is in the wrongful possession of an unknown person or a person that cannot be found or is not amendable [amenable] to service of process.

. "Obligated bank" means the insurer of a cashier's check or teller's check or the acceptor of a certified check.

.. A claimant may assert a claim to the amount of a check by a communication to the obligated bank describing the check with reasonable certainty and requesting payment of the amount of the check, if (i) the claimant is the drawer or payee of a certified check or the remitter or payee of a cashier's check or teller's check, (ii) the communication contains or is accompanied by a declaration of loss of the claimant with respect to the check, (iii) the communication is received at a time and in a manner affording the bank a reasonable time to act on it before the check is paid, and (iv) the claimant provides reasonable identification if requested by the obligated bank. Delivery of a declaration of loss is a warranty of the truth of the statements made in the declaration. If a claim is asserted in compliance with this subsection, the following rules apply:

. The claim becomes enforceable at the later of (i) the time the claim is asserted, or (ii) the ninetieth day following the date of the check, in the case of a cashier's check or teller's check, or the ninetieth day following the date of the acceptance, in the case of a certified check.

. Until the claim becomes enforceable, it has no legal effect and the obligated bank may pay the check or, in the case of a teller's check, may permit the drawee to pay the check. Payment to a person entitled to enforce the check discharges all liability of the obligated bank with respect to the check.

. If the claim becomes enforceable before the check is presented for payment, the obligated bank is not obliged to pay the check.

. When the claim becomes enforceable, the obligated bank becomes obliged to pay the amount of the check to the claimant if payment of the check has not been made to a person entitled to enforce the check. Subject to RCW 62A.4-302(a), payment to the claimant discharges all liability of the obligated bank with respect to the check.

.. If the obligated bank pays the amount of a check to a claimant under subsection (b)(4) and the check is presented for payment by a person having rights of a holder in due course, the claimant is obliged to (i) refund the payment to the obligated bank if the check is paid, or (ii) pay the amount of the check to the person having rights of a holder in due course if the check is dishonored.

.. If a claimant has the right to assert a claim under subsection (b) and is also a person entitled to enforce a cashier's check, teller's check, or certified check that is lost, destroyed, or stolen, the claimant may assert rights with respect to the check under this section.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2040[1993 c 229 § 40]; ]

== 62A.3-401 - Signature.
.. A person is not liable on an instrument unless (i) the person signed the instrument, or (ii) the person is represented by an agent or representative who signed the instrument and the signature is binding on the represented person under RCW 62A.3-402.

.. A signature may be made (i) manually or by means of a device or machine, and (ii) by the use of any name, including a trade or assumed name, or by a word, mark, or symbol executed or adopted by a person with present intention to authenticate a writing.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2041[1993 c 229 § 41]; 1965 ex.s. c 157 § 3-401. Cf. former RCW  62.01.018; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.018[1955 c 35 § 62.01.018]; prior:  1899 c 149 § 18; RRS § 3409; ]

== 62A.3-402 - Signature by representative.
.. If a person acting, or purporting to act, as a representative signs an instrument by signing either the name of the represented person or the name of the signer, the represented person is bound by the signature to the same extent the represented person would be bound if the signature were on a simple contract. If the represented person is bound, the signature of the representative is the "authorized signature of the represented person" and the represented person is liable on the instrument, whether or not identified in the instrument.

.. If a representative signs the name of the representative to an instrument and the signature is an authorized signature of the represented person, the following rules apply:

. If the form of the signature shows unambiguously that the signature is made on behalf of the represented person who is identified in the instrument, the representative is not liable on the instrument.

. Subject to subsection (c), if (i) the form of the signature does not show unambiguously that the signature is made in a representative capacity or (ii) the represented person is not identified in the instrument, the representative is liable on the instrument to a holder in due course that took the instrument without notice that the representative was not intended to be liable on the instrument. With respect to any other person, the representative is liable on the instrument unless the representative proves that the original parties did not intend the representative to be liable on the instrument.

.. If a representative signs the name of the representative as drawer of a check without indication of the representative status and the check is payable from an account of the represented person who is identified on the check, the signer is not liable on the check if the signature is an authorized signature of the represented person.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2042[1993 c 229 § 42]; 1965 ex.s. c 157 § 3-402. Cf. former RCW sections:  RCW  62.01.017(6); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c149.pdf?cite=1955%20c%20149%20§%2062.01.017[1955 c 149 § 62.01.017]; prior:  1899 c 149 § 17; RRS § 3408.  RCW  62.01.063; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c149.pdf?cite=1955%20c%20149%20§%2062.01.063[1955 c 149 § 62.01.063]; prior:  1899 c 149 § 63; RRS § 3454; ]

== 62A.3-403 - Unauthorized signature.
.. Unless otherwise provided in this Article or Article 4, an unauthorized signature is ineffective except as the signature of the unauthorized signer in favor of a person who in good faith pays the instrument or takes it for value. An unauthorized signature may be ratified for all purposes of this Article.

.. If the signature of more than one person is required to constitute the authorized signature of an organization, the signature of the organization is unauthorized if one of the required signatures is lacking.

.. The civil or criminal liability of a person who makes an unauthorized signature is not affected by any provision of this Article which makes the unauthorized signature effective for the purposes of this Article.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2043[1993 c 229 § 43]; 1965 ex.s. c 157 § 3-403. Cf. former RCW sections: RCW  62.01.019 through  62.01.021; 1955 c 35 §§ 62.01.019 through  62.01.021; prior: 1899 c 149 §§ 19 through 21; RRS §§ 3410 through 3412; ]

== 62A.3-404 - Impostors; fictitious payees.
.. If an impostor, by use of the mails or otherwise, induces the issuer of an instrument to issue the instrument to the impostor, or to a person acting in concert with the impostor, by impersonating the payee of the instrument or a person authorized to act for the payee, an indorsement of the instrument by any person in the name of the payee is effective as the indorsement of the payee in favor of a person who, in good faith, pays the instrument or takes it for value or for collection.

.. If (i) a person whose intent determines to whom an instrument is payable (RCW 62A.3-110 (a) or (b)) does not intend the person identified as payee to have any interest in the instrument, or (ii) the person identified as payee of an instrument is a fictitious person, the following rules apply until the instrument is negotiated by special indorsement:

. Any person in possession of the instrument is its holder.

. An indorsement by any person in the name of the payee stated in the instrument is effective as the indorsement of the payee in favor of a person who, in good faith, pays the instrument or takes it for value or for collection.

.. Under subsection (a) or (b), an indorsement is made in the name of a payee if (i) it is made in a name substantially similar to that of the payee or (ii) the instrument, whether or not indorsed, is deposited in a depositary bank to an account in a name substantially similar to that of the payee.

.. With respect to an instrument to which subsection (a) or (b) applies, if a person paying the instrument or taking it for value or for collection fails to exercise ordinary care in paying or taking the instrument and that failure contributes to loss resulting from payment of the instrument, the person bearing the loss may recover from the person failing to exercise ordinary care to the extent the failure to exercise ordinary care contributed to the loss.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2044[1993 c 229 § 44]; 1965 ex.s. c 157 § 3-404. Cf. former RCW  62.01.023; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.023[1955 c 35 § 62.01.023]; prior:  1899 c 149 § 23; RRS § 3414; ]

== 62A.3-405 - Employer's responsibility for fraudulent indorsement by employee.
.. In this section:

. "Employee" includes an independent contractor and employee of an independent contractor retained by the employer.

. "Fraudulent indorsement" means (i) in the case of an instrument payable to the employer, a forged indorsement purporting to be that of the employer, or (ii) in the case of an instrument with respect to which the employer is the issuer, a forged indorsement purporting to be that of the person identified as payee.

. "Responsibility" with respect to instruments means authority (i) to sign or indorse instruments on behalf of the employer, (ii) to process instruments received by the employer for bookkeeping purposes, for deposit to an account, or for other disposition, (iii) to prepare or process instruments for issue in the name of the employer, (iv) to supply information determining the names or addresses of payees of instruments to be issued in the name of the employer, (v) to control the disposition of instruments to be issued in the name of the employer, or (vi) to act otherwise with respect to instruments in a responsible capacity. "Responsibility" does not include authority that merely allows an employee to have access to instruments or blank or incomplete instrument forms that are being stored or transported or are part of incoming or outgoing mail, or similar access.

.. For the purpose of determining the rights and liabilities of a person who, in good faith, pays an instrument or takes it for value or for collection, if an employer entrusted an employee with responsibility with respect to the instrument and the employee or a person acting in concert with the employee makes a fraudulent indorsement of the instrument, the indorsement is effective as the indorsement of the person to whom the instrument is payable if it is made in the name of that person. If the person paying the instrument or taking it for value or for collection fails to exercise ordinary care in paying or taking the instrument and that failure contributes to loss resulting from the fraud, the person bearing the loss may recover from the person failing to exercise ordinary care to the extent the failure to exercise ordinary care contributed to the loss.

.. Under subsection (b), an indorsement is made in the name of the person to whom an instrument is payable if (i) it is made in a name substantially similar to the name of that person or (ii) the instrument, whether or not indorsed, is deposited in a depositary bank to an account in a name substantially similar to the name of that person.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2045[1993 c 229 § 45]; 1965 ex.s. c 157 § 3-405. Cf. former RCW  62.01.009(3); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.009[1955 c 35 § 62.01.009]; prior:  1899 c 149 § 9; RRS § 3400; ]

== 62A.3-406 - Negligence contributing to forged signature or alteration of instrument.
.. A person whose failure to exercise ordinary care contributes to an alteration of an instrument or to the making of a forged signature on an instrument is precluded from asserting the alteration or the forgery against a person who, in good faith, pays the instrument or takes it for value or for collection.

.. Under subsection (a), if the person asserting the preclusion fails to exercise ordinary care in paying or taking the instrument and that failure contributes to loss, the loss is allocated between the person precluded and the person asserting the preclusion according to the extent to which the failure of each to exercise ordinary care contributed to the loss.

.. Under subsection (a), the burden of proving failure to exercise ordinary care is on the person asserting the preclusion. Under subsection (b), the burden of proving failure to exercise ordinary care is on the person precluded.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2046[1993 c 229 § 46]; 1965 ex.s. c 157 § 3-406; ]

== 62A.3-407 - Alteration.
.. "Alteration" means (i) an unauthorized change in an instrument that purports to modify in any respect the obligation of a party, or (ii) an unauthorized addition of words or numbers or other change to an incomplete instrument relating to the obligation of a party.

.. Except as provided in subsection (c), an alteration fraudulently made discharges a party whose obligation is affected by the alteration unless that party assents or is precluded from asserting the alteration. No other alteration discharges a party, and the instrument may be enforced according to its original terms.

.. A payor bank or drawee paying a fraudulently altered instrument or a person taking it for value, in good faith and without notice of the alteration, may enforce rights with respect to the instrument (i) according to its original terms, or (ii) in the case of an incomplete instrument altered by unauthorized completion, according to its terms as completed.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2047[1993 c 229 § 47]; 1965 ex.s. c 157 § 3-407. Cf. former RCW sections:  RCW  62.01.014; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.014[1955 c 35 § 62.01.014]; prior:  1899 c 149 § 14; RRS § 3405.  RCW  62.01.015; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.015[1955 c 35 § 62.01.015]; prior:  1899 c 149 § 15; RRS § 3406. (iii) RCW  62.01.124; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.124[1955 c 35 § 62.01.124]; prior:  1899 c 149 § 124; RRS § 3514. (iv) RCW  62.01.125; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.125[1955 c 35 § 62.01.125]; prior:  1899 c 149 § 125; RRS § 3515; ]

== 62A.3-408 - Drawee not liable on unaccepted draft.
 A check or other draft does not of itself operate as an assignment of funds in the hands of the drawee available for its payment, and the drawee is not liable on the instrument until the drawee accepts it.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2048[1993 c 229 § 48]; 1965 ex.s. c 157 § 3-408. Cf. former RCW sections:  RCW  62.01.024; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.024[1955 c 35 § 62.01.024]; prior:  1899 c 149 § 24; RRS § 3415.  RCW  62.01.025; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.025[1955 c 35 § 62.01.025]; prior:  1899 c 149 § 25; RRS § 3416. (iii) RCW  62.01.028; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.028[1955 c 35 § 62.01.028]; prior:  1899 c 149 § 28; RRS § 3419; ]

== 62A.3-409 - Acceptance of draft; certified check.
.. "Acceptance" means the drawee's signed agreement to pay a draft as presented. It must be written on the draft and may consist of the drawee's signature alone. Acceptance may be made at any time and becomes effective when notification pursuant to instructions is given or the accepted draft is delivered for the purpose of giving rights on the acceptance to any person.

.. A draft may be accepted although it has not been signed by the drawer, is otherwise incomplete, is overdue, or has been dishonored.

.. If a draft is payable at a fixed period after sight and the acceptor fails to date the acceptance, the holder may complete the acceptance by supplying a date in good faith.

.. "Certified check" means a check accepted by the bank on which it is drawn. Acceptance may be made as stated in subsection (a) or by a writing on the check which indicates that the check is certified. The drawee of a check has no obligation to certify the check, and refusal to certify is not dishonor of the check.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2049[1993 c 229 § 49]; 1965 ex.s. c 157 § 3-409. Cf. former RCW sections:  RCW  62.01.127; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.127[1955 c 35 § 62.01.127]; prior:  1899 c 149 § 127; RRS § 3517.  RCW  62.01.189; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.189[1955 c 35 § 62.01.189]; prior:  1899 c 149 § 189; RRS § 3579; ]

== 62A.3-410 - Acceptance varying draft.
.. If the terms of a drawee's acceptance vary from the terms of the draft as presented, the holder may refuse the acceptance and treat the draft as dishonored. In that case, the drawee may cancel the acceptance.

.. The terms of a draft are not varied by an acceptance to pay at a particular bank or place in the United States, unless the acceptance states that the draft is to be paid only at that bank or place.

.. If the holder assents to an acceptance varying the terms of a draft, the obligation of each drawer and indorser that does not expressly assent to the acceptance is discharged.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2050[1993 c 229 § 50]; 1965 ex.s. c 157 § 3-410. Cf. former RCW sections:  RCW  62.01.013; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.013[1955 c 35 § 62.01.013]; prior:  1899 c 149 § 13; RRS § 3404.  RCW  62.01.132 through  62.01.138; 1955 c 35 §§ 62.01.132 through  62.01.138; prior: 1899 c 149 §§ 132 through 138; RRS §§ 3522 through 3528. (iii) RCW  62.01.161 through  62.01.170; 1955 c 35 §§ 62.01.161 through  62.01.170; prior: 1899 c 149 §§ 161 through 170; RRS §§ 3551 through 3560. (iv) RCW  62.01.191; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.191[1955 c 35 § 62.01.191]; prior:  1899 c 149 § 191; RRS § 3581; ]

== 62A.3-411 - Refusal to pay cashier's checks, teller's checks, and certified checks.
.. In this section, "obligated bank" means the acceptor of a certified check or the issuer of a cashier's check or teller's check bought from the issuer.

.. If the obligated bank wrongfully (i) refuses to pay a cashier's check or certified check, (ii) stops payment of a teller's check, or (iii) refuses to pay a dishonored teller's check, the person asserting the right to enforce the check is entitled to compensation for expenses and loss of interest resulting from the nonpayment and may recover consequential damages if the obligated bank refuses to pay after receiving notice of particular circumstances giving rise to the damages.

.. Expenses or consequential damages under subsection (b) are not recoverable if the refusal of the obligated bank to pay occurs because (i) the bank suspends payments, (ii) the obligated bank asserts a claim or defense of the bank that it has reasonable grounds to believe is available against the person entitled to enforce the instrument, (iii) the obligated bank has a reasonable doubt whether the person demanding payment is the person entitled to enforce the instrument, or (iv) payment is prohibited by law.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2051[1993 c 229 § 51]; 1965 ex.s. c 157 § 3-411. Cf. former RCW sections:  RCW  62.01.187; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.187[1955 c 35 § 62.01.187]; prior:  1899 c 149 § 187; RRS § 3577.  RCW  62.01.188; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.188[1955 c 35 § 62.01.188]; prior:  1899 c 149 § 188; RRS § 3578; ]

== 62A.3-412 - Obligation of issuer of note or cashier's check.
The issuer of a note or cashier's check or other draft drawn on the drawer is obliged to pay the instrument (i) according to its terms at the time it was issued or, if not issued, at the time it first came into possession of a holder, or (ii) if the issuer signed an incomplete instrument, according to its terms when completed, to the extent stated in RCW 62A.3-115 and 62A.3-407. The obligation is owed to a person entitled to enforce the instrument or to an indorser who paid the instrument under RCW 62A.3-415.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2052[1993 c 229 § 52]; 1965 ex.s. c 157 § 3-412. Cf. former RCW sections: RCW  62.01.139 through  62.01.142; 1955 c 35 §§ 62.01.139 through  62.01.142; prior: 1899 c 149 §§ 139 through 142; RRS §§ 3529 through 3532; ]

== 62A.3-413 - Obligation of acceptor.
.. The acceptor of a draft is obliged to pay the draft (i) according to its terms at the time it was accepted, even though the acceptance states that the draft is payable "as originally drawn" or equivalent terms, (ii) if the acceptance varies the terms of the draft, according to the terms of the draft as varied, or (iii) if the acceptance is of a draft that is an incomplete instrument, according to its terms when completed, to the extent stated in RCW 62A.3-115 and 62A.3-407. The obligation is owed to a person entitled to enforce the draft or to the drawer or an indorser who paid the draft under RCW 62A.3-414 or 62A.3-415.

.. If the certification of a check or other acceptance of a draft states the amount certified or accepted, the obligation of the acceptor is that amount. If (i) the certification or acceptance does not state an amount, (ii) the amount of the instrument is subsequently raised, and (iii) the instrument is then negotiated to a holder in due course, the obligation of the acceptor is the amount of the instrument at the time it was taken by the holder in due course.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2053[1993 c 229 § 53]; 1965 ex.s. c 157 § 3-413. Cf. former RCW sections: RCW  62.01.060 through  62.01.062; 1955 c 35 §§ 62.01.060 through  62.01.062; prior: 1899 c 149 §§ 60 through 62; RRS §§ 3451 through 3453; ]

== 62A.3-414 - Obligation of drawer.
.. This section does not apply to cashier's checks or other drafts drawn on the drawer.

.. If an unaccepted draft is dishonored, the drawer is obliged to pay the draft (i) according to its terms at the time it was issued or, if not issued, at the time it first came into possession of a holder, or (ii) if the drawer signed an incomplete instrument, according to its terms when completed, to the extent stated in RCW 62A.3-115 and 62A.3-407. The obligation is owed to a person entitled to enforce the draft or to an indorser who paid the draft under RCW 62A.3-415.

.. If a draft is accepted by a bank, the drawer is discharged, regardless of when or by whom acceptance was obtained.

.. If a draft is accepted and the acceptor is not a bank, the obligation of the drawer to pay the draft if the draft is dishonored by the acceptor is the same as the obligation of an indorser under RCW 62A.3-415 (a) and (c).

.. If a draft states that it is drawn "without recourse" or otherwise disclaims liability of the drawer to pay the draft, the drawer is not liable under subsection (b) to pay the draft if the draft is not a check. A disclaimer of the liability stated in subsection (b) is not effective if the draft is a check.

.. If (i) a check is not presented for payment or given to a depositary bank for collection within 30 days after its date, (ii) the drawee suspends payments after expiration of the 30-day period without paying the check, and (iii) because of the suspension of payments, the drawer is deprived of funds maintained with the drawee to cover payment of the check, the drawer to the extent deprived of funds may discharge its obligation to pay the check by assigning to the person entitled to enforce the check the rights of the drawer against the drawee with respect to the funds.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2054[1993 c 229 § 54]; 1965 ex.s. c 157 § 3-414. Cf. former RCW sections:  RCW  62.01.038; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.038[1955 c 35 § 62.01.038]; prior:  1899 c 149 § 38; RRS § 3429.  RCW  62.01.044; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.044[1955 c 35 § 62.01.044]; prior:  1899 c 149 § 44; RRS § 3435. (iii) RCW  62.01.066 through  62.01.068; 1955 c 35 §§ 62.01.066 through  62.01.068; prior: 1899 c 149 §§ 66 through 68; RRS §§ 3457 through 3459; ]

== 62A.3-415 - Obligation of indorser.
.. Subject to subsections (b), (c), (d), and (e) and to RCW 62A.3-419(d), if an instrument is dishonored, an indorser is obliged to pay the amount due on the instrument (i) according to the terms of the instrument at the time it was indorsed, or (ii) if the indorser indorsed an incomplete instrument, according to its terms when completed, to the extent stated in RCW 62A.3-115 and 62A.3-407. The obligation of the indorser is owed to a person entitled to enforce the instrument or to a subsequent indorser who paid the instrument under this section.

.. If an indorsement states that it is made "without recourse" or otherwise disclaims liability of the indorser, the indorser is not liable under subsection (a) to pay the instrument.

.. If notice of dishonor of an instrument is required by RCW 62A.3-503 and notice of dishonor complying with that section is not given to an indorser, the liability of the indorser under subsection (a) is discharged.

.. If a draft is accepted by a bank after an indorsement is made, the liability of the indorser under subsection (a) is discharged.

.. If an indorser of a check is liable under subsection (a) and the check is not presented for payment, or given to a depositary bank for collection, within 30 days after the day the indorsement was made, the liability of the indorser under subsection (a) is discharged.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2055[1993 c 229 § 55]; 1965 ex.s. c 157 § 3-415. Cf. former RCW sections:  RCW  62.01.028; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.028[1955 c 35 § 62.01.028]; prior:  1899 c 149 § 28; RRS § 3419.  RCW  62.01.029; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.029[1955 c 35 § 62.01.029]; prior:  1899 c 149 § 29; RRS § 3420. (iii) RCW  62.01.064; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.064[1955 c 35 § 62.01.064]; prior:  1899 c 149 § 64; RRS § 3455; ]

== 62A.3-416 - Transfer warranties.
.. A person who transfers an instrument for consideration warrants to the transferee and, if the transfer is by indorsement, to any subsequent transferee that:

. The warrantor is a person entitled to enforce the instrument;

. All signatures on the instrument are authentic and authorized;

. The instrument has not been altered;

. The instrument is not subject to a defense or claim in recoupment of any party which can be asserted against the warrantor; and

. The warrantor has no knowledge of any insolvency proceeding commenced with respect to the maker or acceptor or, in the case of an unaccepted draft, the drawer.

.. A person to whom the warranties under subsection (a) are made and who took the instrument in good faith may recover from the warrantor as damages for breach of warranty an amount equal to the loss suffered as a result of the breach, but not more than the amount of the instrument plus expenses and loss of interest incurred as a result of the breach.

.. The warranties stated in subsection (a) cannot be disclaimed with respect to checks. Unless notice of a claim for breach of warranty is given to the warrantor within 30 days after the claimant has reason to know of the breach and the identity of the warrantor, the liability of the warrantor under subsection (b) is discharged to the extent of any loss caused by the delay in giving notice of the claim.

.. A cause of action for breach of warranty under this section accrues when the claimant has reason to know of the breach.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2056[1993 c 229 § 56]; 1965 ex.s. c 157 § 3-416; ]

== 62A.3-417 - Presentment warranties.
.. If an unaccepted draft is presented to the drawee for payment or acceptance and the drawee pays or accepts the draft, (i) the person obtaining payment or acceptance, at the time of presentment, and (ii) a previous transferor of the draft, at the time of transfer, warrant to the drawee making payment or accepting the draft in good faith that:

. The warrantor is, or was, at the time the warrantor transferred the draft, a person entitled to enforce the draft or authorized to obtain payment or acceptance of the draft on behalf of a person entitled to enforce the draft;

. The draft has not been altered; and

. The warrantor has no knowledge that the signature of the drawer of the draft is unauthorized.

.. A drawee making payment may recover from any warrantor damages for breach of warranty equal to the amount paid by the drawee less the amount the drawee received or is entitled to receive from the drawer because of the payment. In addition, the drawee is entitled to compensation for expenses and loss of interest resulting from the breach. The right of the drawee to recover damages under this subsection is not affected by any failure of the drawee to exercise ordinary care in making payment. If the drawee accepts the draft, breach of warranty is a defense to the obligation of the acceptor. If the acceptor makes payment with respect to the draft, the acceptor is entitled to recover from any warrantor for breach of warranty the amounts stated in this subsection.

.. If a drawee asserts a claim for breach of warranty under subsection (a) based on an unauthorized indorsement of the draft or an alteration of the draft, the warrantor may defend by proving that the indorsement is effective under RCW 62A.3-404 or 62A.3-405 or the drawer is precluded under RCW 62A.3-406 or 62A.4-406 from asserting against the drawee the unauthorized indorsement or alteration.

.. If (i) a dishonored draft is presented for payment to the drawer or an indorser or (ii) any other instrument is presented for payment to a party obliged to pay the instrument, and (iii) payment is received, the following rules apply:

. The person obtaining payment and a prior transferor of the instrument warrant to the person making payment in good faith that the warrantor is, or was, at the time the warrantor transferred the instrument, a person entitled to enforce the instrument or authorized to obtain payment on behalf of a person entitled to enforce the instrument.

. The person making payment may recover from any warrantor for breach of warranty an amount equal to the amount paid plus expenses and loss of interest resulting from the breach.

.. The warranties stated in subsections (a) and (d) cannot be disclaimed with respect to checks. Unless notice of a claim for breach of warranty is given to the warrantor within 30 days after the claimant has reason to know of the breach and the identity of the warrantor, the liability of the warrantor under subsection (b) or (d) is discharged to the extent of any loss caused by the delay in giving notice of the claim.

.. A cause of action for breach of warranty under this section accrues when the claimant has reason to know of the breach.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2057[1993 c 229 § 57]; 1965 ex.s. c 157 § 3-417. Cf. former RCW sections:  RCW  62.01.065; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.065[1955 c 35 § 62.01.065]; prior:  1899 c 149 § 65; RRS § 3456.  RCW  62.01.066; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.066[1955 c 35 § 62.01.066]; prior:  1899 c 149 § 66; RRS § 3457. (iii) RCW  62.01.069; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.069[1955 c 35 § 62.01.069]; prior:  1899 c 149 § 69; RRS § 3460; ]

== 62A.3-418 - Payment or acceptance by mistake.
.. Except as provided in subsection (c), if the drawee of a draft pays or accepts the draft and the drawee acted on the mistaken belief that (i) payment of the draft had not been stopped pursuant to RCW 62A.4-403 or (ii) the signature of the drawer of the draft was authorized, the drawee may recover the amount of the draft from the person to whom or for whose benefit payment was made or, in the case of acceptance, may revoke the acceptance. Rights of the drawee under this subsection are not affected by failure of the drawee to exercise ordinary care in paying or accepting the draft.

.. Except as provided in subsection (c), if an instrument has been paid or accepted by mistake and the case is not covered by subsection (a), the person paying or accepting may, to the extent permitted by the law governing mistake and restitution, (i) recover the payment from the person to whom or for whose benefit payment was made or (ii) in the case of acceptance, may revoke the acceptance.

.. The remedies provided by subsection (a) or (b) may not be asserted against a person who took the instrument in good faith and for value or who in good faith changed position in reliance on the payment or acceptance. This subsection does not limit remedies provided by RCW 62A.3-417 or 62A.4-407.

.. Notwithstanding RCW 62A.4-213, if an instrument is paid or accepted by mistake and the payor or acceptor recovers payment or revokes acceptance under subsection (a) or (b), the instrument is deemed not to have been paid or accepted and is treated as dishonored, and the person from whom payment is recovered has rights as a person entitled to enforce the dishonored instrument.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2058[1993 c 229 § 58]; 1965 ex.s. c 157 § 3-418. Cf. former RCW  62.01.062; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.062[1955 c 35 § 62.01.062]; prior:  1899 c 149 § 62; RRS § 3453; ]

== 62A.3-419 - Instruments signed for accommodation.
.. If an instrument is issued for value given for the benefit of a party to the instrument ("accommodated party") and another party to the instrument ("accommodation party") signs the instrument for the purpose of incurring liability on the instrument without being a direct beneficiary of the value given for the instrument, the instrument is signed by the accommodation party "for accommodation."

.. An accommodation party may sign the instrument as maker, drawer, acceptor, or indorser and, subject to subsection (d), is obliged to pay the instrument in the capacity in which the accommodation party signs. The obligation of an accommodation party may be enforced notwithstanding any statute of frauds and whether or not the accommodation party receives consideration for the accommodation.

.. A person signing an instrument is presumed to be an accommodation party and there is notice that the instrument is signed for accommodation if the signature is an anomalous indorsement or is accompanied by words indicating that the signer is acting as surety or guarantor with respect to the obligation of another party to the instrument. Except as provided in RCW 62A.3-605, the obligation of an accommodation party to pay the instrument is not affected by the fact that the person enforcing the obligation had notice when the instrument was taken by that person that the accommodation party signed the instrument for accommodation.

.. If the signature of a party to an instrument is accompanied by words indicating unambiguously that the party is guaranteeing collection rather than payment of the obligation of another party to the instrument, the signer is obliged to pay the amount due on the instrument to a person entitled to enforce the instrument only if (i) execution of judgment against the other party has been returned unsatisfied, (ii) the other party is insolvent or in an insolvency proceeding, (iii) the other party cannot be served with process, or (iv) it is otherwise apparent that payment cannot be obtained from the other party.

.. An accommodation party who pays the instrument is entitled to reimbursement from the accommodated party and is entitled to enforce the instrument against the accommodated party. An accommodated party who pays the instrument has no right of recourse against, and is not entitled to contribution from, an accommodation party.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2059[1993 c 229 § 59]; 1965 ex.s. c 157 § 3-419. Cf. former RCW  62.01.137; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.137[1955 c 35 § 62.01.137]; prior:  1899 c 149 § 137; RRS § 3527; ]

== 62A.3-420 - Conversion of instrument.
.. The law applicable to conversion of personal property applies to instruments. An instrument is also converted if it is taken by transfer, other than a negotiation, from a person not entitled to enforce the instrument or a bank makes or obtains payment with respect to the instrument for a person not entitled to enforce the instrument or receive payment. An action for conversion of an instrument may not be brought by (i) the issuer or acceptor of the instrument or (ii) a payee or indorsee who did not receive delivery of the instrument either directly or through delivery to an agent or a copayee.

.. In an action under subsection (a), the measure of liability is presumed to be the amount payable on the instrument, but recovery may not exceed the amount of the plaintiff's interest in the instrument.

.. A representative, other than a depositary bank, who has in good faith dealt with an instrument or its proceeds on behalf of one who was not the person entitled to enforce the instrument is not liable in conversion to that person beyond the amount of any proceeds that it has not paid out.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2060[1993 c 229 § 60]; ]

== 62A.3-501 - Presentment.
.. "Presentment" means a demand made by or on behalf of a person entitled to enforce an instrument (i) to pay the instrument made to the drawee or a party obliged to pay the instrument or, in the case of a note or accepted draft payable at a bank, to the bank, or (ii) to accept a draft made to the drawee.

.. The following rules are subject to Article 4, agreement of the parties, and clearinghouse rules and the like:

. Presentment may be made at the place of payment of the instrument and must be made at the place of payment if the instrument is payable at a bank in the United States; may be made by any commercially reasonable means, including an oral, written, or electronic communication; is effective when the demand for payment or acceptance is received by the person to whom presentment is made; and is effective if made to any one of two or more makers, acceptors, drawees, or other payors.

. Upon demand of the person to whom presentment is made, the person making presentment must (i) exhibit the instrument, (ii) give reasonable identification and, if presentment is made on behalf of another person, reasonable evidence of authority to do so, and (iii) sign a receipt on the instrument for any payment made or surrender the instrument if full payment is made.

. Without dishonoring the instrument, the party to whom presentment is made may (i) return the instrument for lack of a necessary indorsement, or (ii) refuse payment or acceptance for failure of the presentment to comply with the terms of the instrument, an agreement of the parties, or other applicable law or rule.

. The party to whom presentment is made may treat presentment as occurring on the next business day after the day of presentment if the party to whom presentment is made has established a cut-off hour not earlier than 2:00 p.m. for the receipt and processing of instruments presented for payment or acceptance and presentment is made after the cut-off hour.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2061[1993 c 229 § 61]; 1965 ex.s. c 157 § 3-501. Cf. former RCW sections: RCW  62.01.070,  62.01.089,  62.01.118,  62.01.129,  62.01.143,  62.01.144,  62.01.150,  62.01.151,  62.01.152,  62.01.157,  62.01.158, and  62.01.186; 1955 c 35 §§ 62.01.070,  62.01.089,  62.01.118,  62.01.129,  62.01.143,  62.01.144,  62.01.150,  62.01.151,  62.01.152,  62.01.157,  62.01.158, and  62.01.186; prior: 1899 c 149 §§ 70, 89, 118, 129, 143, 144, 150, 151, 152, 157, 158, and 186; RRS §§ 3461, 3479, 3508, 3519, 3533, 3534, 3540, 3541, 3542, 3547, 3548, and 3576; ]

== 62A.3-502 - Dishonor.
.. Dishonor of a note is governed by the following rules:

. If the note is payable on demand, the note is dishonored if presentment is duly made to the maker and the note is not paid on the day of presentment.

. If the note is not payable on demand and is payable at or through a bank or the terms of the note require presentment, the note is dishonored if presentment is duly made and the note is not paid on the day it becomes payable or the day of presentment, whichever is later.

. If the note is not payable on demand and subsection (a)(2) does not apply, the note is dishonored if it is not paid on the day it becomes payable.

.. Dishonor of an unaccepted draft other than a documentary draft is governed by the following rules:

. If a check is duly presented for payment to the payor bank otherwise than for immediate payment over the counter, the check is dishonored if the payor bank makes timely return of the check or sends timely notice of dishonor or nonpayment under RCW 62A.4-301 or 62A.4-302, or becomes accountable for the amount of the check under RCW 62A.4-302.

. If a draft is payable on demand and subsection (b)(1) does not apply, the draft is dishonored if presentment for payment is duly made to the drawee and the draft is not paid on the day of presentment.

. If a draft is payable on a date stated in the draft, the draft is dishonored if (i) presentment for payment is duly made to the drawee and payment is not made on the day the draft becomes payable or the day of presentment, whichever is later, or (ii) presentment for acceptance is duly made before the day the draft becomes payable and the draft is not accepted on the day of presentment.

. If a draft is payable on elapse of a period of time after sight or acceptance, the draft is dishonored if presentment for acceptance is duly made and the draft is not accepted on the day of presentment.

.. Dishonor of an unaccepted documentary draft occurs according to the rules stated in subsection (b) (2), (3), and (4), except that payment or acceptance may be delayed without dishonor until no later than the close of the third business day of the drawee following the day on which payment or acceptance is required by subsection (b) (2), (3), and (4).

.. Dishonor of an accepted draft is governed by the following rules:

. If the draft is payable on demand, the draft is dishonored if presentment for payment is duly made to the acceptor and the draft is not paid on the day of presentment; or

. If the draft is not payable on demand, the draft is dishonored if presentment for payment is duly made to the acceptor and payment is not made on the day it becomes payable or the day of presentment, whichever is later.

.. In any case in which presentment is otherwise required for dishonor under this section and presentment is excused under RCW 62A.3-504, dishonor occurs without presentment if the instrument is not duly accepted or paid.

.. If a draft is dishonored because timely acceptance of the draft was not made and the person entitled to demand acceptance consents to a late acceptance, from the time of acceptance the draft is treated as never having been dishonored.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2062[1993 c 229 § 62]; 1965 ex.s. c 157 § 3-502. Cf. former RCW sections: RCW  62.01.007,  62.01.070,  62.01.089,  62.01.144,  62.01.150,  62.01.152, and  62.01.186; 1955 c 35 §§ 62.01.007,  62.01.070,  62.01.089,  62.01.144,  62.01.150,  62.01.152, and  62.01.186; prior: 1899 c 149 §§ 7, 70, 89, 144, 150, 152, and 186; RRS §§ 3398, 3461, 3479, 3534, 3540, 3542, and 3576; ]

== 62A.3-503 - Notice of dishonor.
.. The obligation of an indorser stated in RCW 62A.3-415(a) and the obligation of a drawer stated in RCW 62A.3-414(d) may not be enforced unless (i) the indorser or drawer is given notice of dishonor of the instrument complying with this section or (ii) notice of dishonor is excused under RCW 62A.3-504(b).

.. Notice of dishonor may be given by any person; may be given by any commercially reasonable means, including an oral, written, or electronic communication; and is sufficient if it reasonably identifies the instrument and indicates that the instrument has been dishonored or has not been paid or accepted. Return of an instrument given to a bank for collection is sufficient notice of dishonor.

.. Subject to RCW 62A.3-504(c), with respect to an instrument taken for collection by a collecting bank, notice of dishonor must be given (i) by the bank before midnight of the next banking day following the banking day on which the bank receives notice of dishonor of the instrument, or (ii) by any other person within 30 days following the day on which the person receives notice of dishonor. With respect to any other instrument, notice of dishonor must be given within 30 days following the day on which dishonor occurs.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2063[1993 c 229 § 63]; 1965 ex.s. c 157 § 3-503. Cf. former RCW sections:  RCW  62.01.071,  62.01.072,  62.01.075,  62.01.086,  62.01.144,  62.01.145,  62.01.146,  62.01.186, and  62.01.193; 1955 c 35 §§ 62.01.071,  62.01.072,  62.01.075,  62.01.086,  62.01.144,  62.01.145,  62.01.146,  62.01.186, and  62.01.193; prior: 1899 c 149 §§ 71, 72, 75, 86, 144, 145, 146, 186, and 193; RRS §§ 3462, 3463, 3466, 3476, 3534, 3535, 3536, 3576, and 3583.  RCW  62.01.085; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.085[1955 c 35 § 62.01.085]; prior:  1915 c 173 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1899c149.pdf?cite=1899%20c%20149%20§%2085[1899 c 149 § 85]; RRS § 3475 1/2; ]

== 62A.3-504 - Excused presentment and notice of dishonor.
.. Presentment for payment or acceptance of an instrument is excused if (i) the person entitled to present the instrument cannot with reasonable diligence make presentment, (ii) the maker or acceptor has repudiated an obligation to pay the instrument or is dead or in insolvency proceedings, (iii) by the terms of the instrument presentment is not necessary to enforce the obligation of indorsers or the drawer, (iv) the drawer or indorser whose obligation is being enforced has waived presentment or otherwise has no reason to expect or right to require that the instrument be paid or accepted, or (v) the drawer instructed the drawee not to pay or accept the draft or the drawee was not obligated to the drawer to pay the draft.

.. Notice of dishonor is excused if (i) by the terms of the instrument notice of dishonor is not necessary to enforce the obligation of a party to pay the instrument, or (ii) the party whose obligation is being enforced waived notice of dishonor. A waiver of presentment is also a waiver of notice of dishonor.

.. Delay in giving notice of dishonor is excused if the delay was caused by circumstances beyond the control of the person giving the notice and the person giving the notice exercised reasonable diligence after the cause of the delay ceased to operate.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2064[1993 c 229 § 64]; 1965 ex.s. c 157 § 3-504. Cf. former RCW sections: RCW  62.01.072,  62.01.073,  62.01.077,  62.01.078, and  62.01.145; 1955 c 35 §§ 62.01.072,  62.01.073,  62.01.077,  62.01.078, and  62.01.145; prior: 1899 c 149 §§ 72, 73, 77, 78, and 145; RRS §§ 3463, 3464, 3468, 3469, and 3535; ]

== 62A.3-505 - Evidence of dishonor.
.. The following are admissible as evidence and create a presumption of dishonor and of any notice of dishonor stated:

. A document regular in form as provided in subsection (b) that purports to be a protest;

. A purported stamp or writing of the drawee, payor bank, or presenting bank on or accompanying the instrument stating that acceptance or payment has been refused unless reasons for the refusal are stated and the reasons are not consistent with dishonor;

. A book or record of the drawee, payor bank, or collecting bank, kept in the usual course of business which shows dishonor, even if there is no evidence of who made the entry.

.. A protest is a certificate of dishonor made by a United States consul or vice-consul, or a notary public or other person authorized to administer oaths by the law of the place where dishonor occurs. It may be made upon information satisfactory to that person. The protest must identify the instrument and certify either that presentment has been made or, if not made, the reason why it was not made, and that the instrument has been dishonored by nonacceptance or nonpayment. The protest may also certify that notice of dishonor has been given to some or all parties.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2065[1993 c 229 § 65]; 1965 ex.s. c 157 § 3-505. Cf. former RCW sections:  RCW  62.01.072(3); http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.072[1955 c 35 § 62.01.072]; prior:  1899 c 149 § 72; RRS § 3463.  RCW  62.01.074; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.074[1955 c 35 § 62.01.074]; prior:  1899 c 149 § 74; RRS § 3465. (iii) RCW  62.01.133; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.133[1955 c 35 § 62.01.133]; prior:  1899 c 149 § 133; RRS § 3523; ]

== 62A.3-512 - Credit cards—As identification—In lieu of deposit.
A person may not record the number of a credit card given as identification under *RCW 62A.3-501(a)(2) or given as proof of creditworthiness when payment for goods or services is made by check or draft. Nothing in this section prohibits the recording of the number of a credit card given in lieu of a deposit to secure payment in the event of a default, loss, damage, or other occurrence.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2066[1993 c 229 § 66]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c203.pdf?cite=1990%20c%20203%20§%202[1990 c 203 § 2]; ]

== 62A.3-515 - Checks dishonored by nonacceptance or nonpayment; liability for interest; rate; collection costs and attorneys' fees; satisfaction of claim.
.. If a check as defined in RCW 62A.3-104 is dishonored by nonacceptance or nonpayment, the payee or person entitled to enforce the check under RCW 62A.3-301 may collect a reasonable handling fee for each instrument. If the check is not paid within fifteen days and after the person entitled to enforce the check or the person's agent sends a notice of dishonor as provided by RCW 62A.3-520 to the drawer at the drawer's last known address, and if the instrument does not provide for the payment of interest or collection costs and attorneys' fees, the drawer of the instrument is liable for payment of interest at the rate of twelve percent per annum from the date of dishonor, and cost of collection not to exceed forty dollars or the face amount of the check, whichever is less, payable to the person entitled to enforce the check. In addition, in the event of court action on the check, the court, after notice and the expiration of the fifteen days, shall award reasonable attorneys' fees, and three times the face amount of the check or three hundred dollars, whichever is less, as part of the damages payable to the person enforcing the check. This section does not apply to an instrument that is dishonored by reason of a justifiable stop payment order.

.. [Empty]
. Subsequent to the commencement of an action on the check (subsection (a)) but prior to the hearing, the defendant may tender to the plaintiff as satisfaction of the claim, an amount of money equal to the face amount of the check, a reasonable handling fee, accrued interest, collection costs equal to the face amount of the check not to exceed forty dollars, and the incurred court costs, service costs, and statutory attorneys' fees.

. Nothing in this section precludes the right to commence action in a court under chapter 12.40 RCW for small claims.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2609.SL.pdf?cite=2000%20c%20215%20§%201[2000 c 215 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1771.SL.pdf?cite=1995%20c%20187%20§%201[1995 c 187 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2067[1993 c 229 § 67]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5494-S.SL.pdf?cite=1991%20c%20168%20§%201[1991 c 168 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c128.pdf?cite=1986%20c%20128%20§%201[1986 c 128 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c254.pdf?cite=1981%20c%20254%20§%201[1981 c 254 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c62.pdf?cite=1969%20c%2062%20§%201[1969 c 62 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c23.pdf?cite=1967%20ex.s.%20c%2023%20§%201[1967 ex.s. c 23 § 1]; ]

== 62A.3-520 - Statutory form for notice of dishonor.
The notice of dishonor shall be sent by mail to the drawer at the drawer's last known address, and the notice shall be substantially in the following form:

NOTICE OF DISHONOR OF CHECK

A check drawn by you and made payable by you to . . . . . . in the amount of . . . . . . has not been accepted for payment by . . . . . ., which is the drawee bank designated on your check. This check is dated . . . . . ., and it is numbered, No. . . . . . ..

You are CAUTIONED that unless you pay the amount of this check within fifteen days after the date this letter is postmarked, you may very well have to pay the following additional amounts:

. Costs of collecting the amount of the check, including an attorney's fee which will be set by the court;

. Interest on the amount of the check which shall accrue at the rate of twelve percent per annum from the date of dishonor; and

. Three hundred dollars or three times the face amount of the check, whichever is less, by award of the court.

You are also CAUTIONED that law enforcement agencies may be provided with a copy of this notice of dishonor and the check drawn by you for the possibility of proceeding with criminal charges if you do not pay the amount of this check within fifteen days after the date this letter is postmarked.

You are advised to make your payment to . . . . . . at the following address: . . . . . . . . . .

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2068[1993 c 229 § 68]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5494-S.SL.pdf?cite=1991%20c%20168%20§%202[1991 c 168 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c128.pdf?cite=1986%20c%20128%20§%202[1986 c 128 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c254.pdf?cite=1981%20c%20254%20§%202[1981 c 254 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c62.pdf?cite=1969%20c%2062%20§%202[1969 c 62 § 2]; ]

== 62A.3-522 - Notice of dishonor—Affidavit of service by mail.
In addition to sending a notice of dishonor to the drawer of the check under RCW 62A.3-520, the person sending notice shall execute an affidavit certifying service of the notice by mail. The affidavit of service by mail must be attached to a copy of the notice of dishonor and must be substantially in the following form:

AFFIDAVIT OF SERVICE BY MAIL

I, . . . . . ., hereby certify that on the . . . . . . day of . . . . . ., 20. . ., a copy of the foregoing Notice was served on . . . . . . by mailing via the United States Postal Service, postage prepaid, at . . . . . ., Washington.

Dated:. . . . . . . . . . . . . . . .

(Signature)

The person enforcing the check shall retain the affidavit with the check but shall file a copy of the affidavit with the clerk of the court in which an action on the check is commenced.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2609.SL.pdf?cite=2000%20c%20215%20§%202[2000 c 215 § 2]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2069[1993 c 229 § 69]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c254.pdf?cite=1981%20c%20254%20§%203[1981 c 254 § 3]; ]

== 62A.3-525 - Consequences for failing to comply with requirements.
No interest, collection costs, and attorneys' fees, except handling fees, are recoverable on any dishonored check under the provisions of RCW 62A.3-515 where a person entitled to such recovery or any agent, employee, or assign has demanded:

. Interest or collection costs in excess of that provided by RCW 62A.3-515; or

. Interest or collection costs prior to the expiration of fifteen days after the mailing of notice of dishonor, as provided by RCW 62A.3-515 and 62A.3-520; or

. Attorneys' fees either without having the fees set by the court, or prior to the expiration of fifteen days after the mailing of notice of dishonor, as provided by RCW 62A.3-515 and 62A.3-520.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2609.SL.pdf?cite=2000%20c%20215%20§%203[2000 c 215 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2070[1993 c 229 § 70]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c254.pdf?cite=1981%20c%20254%20§%204[1981 c 254 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969c62.pdf?cite=1969%20c%2062%20§%203[1969 c 62 § 3]; ]

== 62A.3-530 - Collection agencies—Checks dishonored by nonacceptance or nonpayment; liability for interest; rate; collection costs and attorneys' fees; satisfaction of claim.
. If a check as defined in RCW 62A.3-104 is dishonored by nonacceptance or nonpayment and the check is assigned or written to a collection agency as defined in RCW 19.16.100, the collection agency may collect a reasonable handling fee for each instrument. If the collection agency or its agent provides a notice of dishonor in the form provided in RCW 62A.3-540 to the drawer and the check amount plus the reasonable handling fee are not paid within thirty-three days after providing the notice of dishonor, then, unless the instrument otherwise provides, the drawer of the instrument is liable for payment of interest at the rate of twelve percent per annum from the date of dishonor, and a cost of collection of forty dollars or the face amount of the check, whichever is less, payable to the collection agency. In addition, in the event of court action on the check and after notice and the expiration of the thirty-three days, the court shall award reasonable attorneys' fees, and three times the face amount of the check or three hundred dollars, whichever is less, as part of the damages payable to the collection agency. This section does not apply to an instrument that is dishonored by reason of a justifiable stop payment order.

. Subsequent to the commencement of an action on the check under subsection (1) of this section but prior to the hearing, the defendant may tender to the plaintiff as satisfaction of the claim, an amount of money equal to the face amount of the check, a reasonable handling fee, accrued interest, collection costs equal to the face amount of the check not to exceed forty dollars, and the incurred court costs, service costs, and statutory attorneys' fees.

. Nothing in this section precludes the right to commence action in a court under chapter 12.40 RCW for small claims.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1347-S.SL.pdf?cite=2005%20c%20277%20§%203[2005 c 277 § 3]; ]

== 62A.3-540 - Collection agencies—Statutory form for notice of dishonor.
. If a check is assigned or written to a collection agency as defined in RCW 19.16.100 and the collection agency or its agent provides a notice of dishonor, the notice of dishonor may be sent by mail to the drawer at the drawer's last known address. The drawer is presumed to have received the notice of dishonor three days from the date it is mailed. The collection agency may, as an alternative to providing a notice in the form described in RCW 62A.3-520, provide a notice in substantially the following form:

NOTICE OF DISHONOR OF CHECK

A check drawn by you and made payable by you to . . . . . . in the amount of . . . . . . has not been accepted for payment by . . . . . ., which is the drawee bank designated on your check. This check is dated . . . . . ., and it is numbered, No. . . . . . ..

You are CAUTIONED that unless you pay the amount of this check and a handling fee of . . . . . within thirty-three days after the date this letter is postmarked or personally delivered, you may very well have to pay the following additional amounts:

.. Costs of collecting the amount of the check in the lesser of the check amount or forty dollars;

.. Interest on the amount of the check which shall accrue at the rate of twelve percent per annum from the date of dishonor; and

.. Three hundred dollars or three times the face amount of the check, whichever is less, plus court costs and attorneys' fees, by award of the court in the event of legal action. Note that this caution regarding increased amounts in any possible legal action is advisory only and should not be construed as a representation or implication that legal action is contemplated or intended.

You are also CAUTIONED that law enforcement agencies may be provided with a copy of this notice of dishonor and the check drawn by you for the possibility of proceeding with criminal charges if you do not pay the amount of this check within thirty-three days after the date this letter is postmarked.

You are advised to make your payment of $. . . . . to . . . . . . at the following address: . . . . . . . . . .

. The cautionary statement regarding law enforcement in subsection (1) of this section need not be included in a notice of dishonor sent by a collection agency. However, if included and whether or not the collection agency regularly refers dishonored checks to law enforcement, the cautionary statement in subsection (1) of this section shall not be construed as a threat to take any action not intended to be taken or that cannot legally be taken; nor shall it be construed to be harassing, oppressive, or abusive conduct; nor shall it be construed to be a false, deceptive, or misleading representation; nor shall it be construed to be unfair or unconscionable; nor shall it otherwise be construed to violate any law.

. In addition to sending a notice of dishonor to the drawer of the check under this section, the person sending notice shall execute an affidavit certifying service of the notice by mail. The affidavit of service by mail must be substantially in the following form:

AFFIDAVIT OF SERVICE BY MAIL

I, . . . . . ., hereby certify that on the . . . . . . day of . . . . . ., 20. . ., a copy of the foregoing Notice was served on . . . . . . by mailing via the United States Postal Service, postage prepaid, at . . . . . ., Washington.

Dated:. . . . . . . . . . . . . . . .

(Signature)

. The person enforcing a check under this section shall file the affidavit and check, or a true copy thereof, with the clerk of the court in which an action on the check is commenced as permitted by court rule or practice.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1042.SL.pdf?cite=2009%20c%20185%20§%201[2009 c 185 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1347-S.SL.pdf?cite=2005%20c%20277%20§%204[2005 c 277 § 4]; ]

== 62A.3-550 - Collection agencies—Consequences for failing to comply with requirements.
No interest, collection costs, and attorneys' fees, except handling fees, are recoverable on any dishonored check under the provisions of RCW 62A.3-530 where a collection agency or its agent, employee, or assign has demanded:

. Interest or collection costs in excess of that provided by RCW 62A.3-530; or

. Interest or collection costs prior to the expiration of thirty-three days after the serving or mailing of the notice of dishonor, as provided by RCW 62A.3-530 or 62A.3-540; or

. Attorneys' fees other than statutory attorneys' fees without having the fees set by the court, or any attorneys' fees prior to thirty-three days after the serving or mailing of the notice of dishonor, as provided by RCW 62A.3-530 or 62A.3-540.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1347-S.SL.pdf?cite=2005%20c%20277%20§%205[2005 c 277 § 5]; ]

== 62A.3-601 - Discharge and effect of discharge.
.. The obligation of a party to pay the instrument is discharged as stated in this Article or by an act or agreement with the party which would discharge an obligation to pay money under a simple contract.

.. Discharge of the obligation of a party is not effective against a person acquiring rights of a holder in due course of the instrument without notice of the discharge.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2071[1993 c 229 § 71]; 1965 ex.s. c 157 § 3-601. Cf. former RCW sections: RCW  62.01.119 through  62.01.121; 1955 c 35 §§ 62.01.119 through  62.01.121; prior: 1899 c 149 §§ 119 through 121; RRS §§ 3509 through 3511; ]

== 62A.3-602 - Payment.
.. Subject to subsection (b), an instrument is paid to the extent payment is made (i) by or on behalf of a party obliged to pay the instrument, and (ii) to a person entitled to enforce the instrument. To the extent of the payment, the obligation of the party obliged to pay the instrument is discharged even though payment is made with knowledge of a claim to the instrument under RCW 62A.3-306 by another person.

.. The obligation of a party to pay the instrument is not discharged under subsection (a) if:

. A claim to the instrument under RCW 62A.3-306 is enforceable against the party receiving payment and (i) payment is made with knowledge by the payor that payment is prohibited by injunction or similar process of a court of competent jurisdiction, or (ii) in the case of an instrument other than a cashier's check, teller's check, or certified check, the party making payment accepted, from the person having a claim to the instrument, indemnity against loss resulting from refusal to pay the person entitled to enforce the instrument; or

. The person making payment knows that the instrument is a stolen instrument and pays a person it knows is in wrongful possession of the instrument.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2072[1993 c 229 § 72]; 1965 ex.s. c 157 § 3-602. Cf. former RCW  62.01.122; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.122[1955 c 35 § 62.01.122]; prior:  1899 c 149 § 122; RRS § 3512; ]

== 62A.3-603 - Tender of payment.
.. If tender of payment of an obligation to pay an instrument is made to a person entitled to enforce the instrument, the effect of tender is governed by principles of law applicable to tender of payment under a simple contract.

.. If tender of payment of an obligation to pay an instrument is made to a person entitled to enforce the instrument and the tender is refused, there is discharge, to the extent of the amount of the tender, of the obligation of an indorser or accommodation party having a right of recourse with respect to the obligation to which the tender relates.

.. If tender of payment of an amount due on an instrument is made to a person entitled to enforce the instrument, the obligation of the obligor to pay interest after the due date on the amount tendered is discharged. If presentment is required with respect to an instrument and the obligor is able and ready to pay on the due date at every place of payment stated in the instrument, the obligor is deemed to have made tender of payment on the due date to the person entitled to enforce the instrument.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2073[1993 c 229 § 73]; 1965 ex.s. c 157 § 3-603. Cf. former RCW sections:  RCW  62.01.051,  62.01.088,  62.01.119, and  62.01.121; 1955 c 35 §§ 62.01.051,  62.01.088,  62.01.119, and  62.01.121; prior: 1899 c 149 §§ 51, 88, 119, and 121; RRS §§ 3442, 3478, 3509, and 3511.  RCW  62.01.171 through  62.01.177; 1955 c 35 §§ 62.01.171 through  62.01.177; prior: 1899 c 149 §§ 171 through 177; RRS §§ 3561 through 3567. (iii) Subd. (3) cf. former RCW  30.20.090; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c280.pdf?cite=1961%20c%20280%20§%204[1961 c 280 § 4]; ]

== 62A.3-604 - Discharge by cancellation or renunciation.
.. A person entitled to enforce an instrument, with or without consideration, may discharge the obligation of a party to pay the instrument (i) by an intentional voluntary act, such as surrender of the instrument to the party, destruction, mutilation, or cancellation of the instrument, cancellation or striking out of the party's signature, or the addition of words to the instrument indicating discharge, or (ii) by agreeing not to sue or otherwise renouncing rights against the party by a signed writing.

.. Cancellation or striking out of an indorsement pursuant to subsection (a) does not affect the status and rights of a party derived from the indorsement.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2074[1993 c 229 § 74]; 1965 ex.s. c 157 § 3-604. Cf. former RCW sections:  RCW  62.01.070; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.070[1955 c 35 § 62.01.070]; prior:  1899 c 149 § 70; RRS § 3461.  RCW  62.01.120; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c35.pdf?cite=1955%20c%2035%20§%2062.01.120[1955 c 35 § 62.01.120]; prior:  1899 c 149 § 120; RRS § 3510; ]

== 62A.3-605 - Discharge of indorsers and accommodation parties.
.. In this section, the term "indorser" includes a drawer having the obligation described in RCW 62A.3-414(d).

.. Discharge, under RCW 62A.3-604, of the obligation of a party to pay an instrument does not discharge the obligation of an indorser or accommodation party having a right of recourse against the discharged party.

.. If a person entitled to enforce an instrument agrees, with or without consideration, to an extension of the due date of the obligation of a party to pay the instrument, the extension discharges an indorser or accommodation party having a right of recourse against the party whose obligation is extended to the extent the indorser or accommodation party proves that the extension caused loss to the indorser or accommodation party with respect to the right of recourse.

.. If a person entitled to enforce an instrument agrees, with or without consideration, to a material modification of the obligation of a party other than an extension of the due date, the modification discharges the obligation of an indorser or accommodation party having a right of recourse against the person whose obligation is modified to the extent the modification causes loss to the indorser or accommodation party with respect to the right of recourse. The loss suffered by the indorser or accommodation party as a result of the modification is equal to the amount of the right of recourse unless the person enforcing the instrument proves that no loss was caused by the modification or that the loss caused by the modification was an amount less than the amount of the right of recourse.

.. If the obligation of a party to pay an instrument is secured by an interest in collateral and a person entitled to enforce the instrument impairs the value of the interest in collateral, the obligation of an indorser or accommodation party having a right of recourse against the obligor is discharged to the extent of the impairment. The value of an interest in collateral is impaired to the extent (i) the value of the interest is reduced to an amount less than the amount of the right of recourse of the party asserting discharge, or (ii) the reduction in value of the interest causes an increase in the amount by which the amount of the right of recourse exceeds the value of the interest. The burden of proving impairment is on the party asserting discharge.

.. If the obligation of a party is secured by an interest in collateral not provided by an accommodation party and a person entitled to enforce the instrument impairs the value of the interest in collateral, the obligation of any party who is jointly and severally liable with respect to the secured obligation is discharged to the extent the impairment causes the party asserting discharge to pay more than that party would have been obliged to pay, taking into account rights of contribution, if impairment had not occurred. If the party asserting discharge is an accommodation party not entitled to discharge under subsection (e), the party is deemed to have a right to contribution based on joint and several liability rather than a right to reimbursement. The burden of proving impairment is on the party asserting discharge.

.. Under subsection (e) or (f), impairing value of an interest in collateral includes (i) failure to obtain or maintain perfection or recordation of the interest in collateral, (ii) release of collateral without substitution of collateral of equal value, (iii) failure to perform a duty to preserve the value of collateral owed, under *Article 9 or other law, to a debtor or surety or other person secondarily liable, or (iv) failure to comply with applicable law in disposing of collateral.

.. An accommodation party is not discharged under subsection (c), (d), or (e) unless the person entitled to enforce the instrument knows of the accommodation or has notice under RCW 62A.3-419(c) that the instrument was signed for accommodation.

.. A party is not discharged under this section if (i) the party asserting discharge consents to the event or conduct that is the basis of the discharge, or (ii) the instrument or a separate agreement of the party provides for waiver of discharge under this section either specifically or by general language indicating that parties waive defenses based on suretyship or impairment of collateral.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1014-S.SL.pdf?cite=1993%20c%20229%20§%2075[1993 c 229 § 75]; 1965 ex.s. c 157 § 3-605. Cf. former RCW sections: RCW  62.01.048,  62.01.119(3),  62.01.120,  62.01.122, and  62.01.123; 1955 c 35 §§ 62.01.048,  62.01.119,  62.01.120,  62.01.122, and  62.01.123; prior: 1899 c 149 §§ 48, 119, 120, 122, and 123; RRS §§ 3439, 3509, 3510, 3512, and 3513; ]

