= 64.38 - Homeowners' associations.
:toc:

== 64.38.005 - Intent.
The intent of this chapter is to provide consistent laws regarding the formation and legal administration of homeowners' associations.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1471-S.SL.pdf?cite=1995%20c%20283%20§%201[1995 c 283 § 1]; ]

== 64.38.010 - Definitions.
For purposes of this chapter:

. "Assessment" means all sums chargeable to an owner by an association in accordance with RCW 64.38.020.

. "Baseline funding plan" means establishing a reserve funding goal of maintaining a reserve account balance above zero dollars throughout the thirty-year study period described under RCW 64.38.065.

. "Board of directors" or "board" means the body, regardless of name, with primary authority to manage the affairs of the association.

. "Common areas" means property owned, or otherwise maintained, repaired or administered by the association.

. "Common expense" means the costs incurred by the association to exercise any of the powers provided for in this chapter.

. "Contribution rate" means, in a reserve study as described in *RCW 64.34.380, the amount contributed to the reserve account so that the association will have cash reserves to pay major maintenance, repair, or replacement costs without the need of a special assessment.

. "Effective age" means the difference between the estimated useful life and remaining useful life.

. "Full funding plan" means setting a reserve funding goal of achieving one hundred percent fully funded reserves by the end of the thirty-year study period described under RCW 64.38.065, in which the reserve account balance equals the sum of the deteriorated portion of all reserve components.

. "Fully funded balance" means the current value of the deteriorated portion, not the total replacement value, of all the reserve components. The fully funded balance for each reserve component is calculated by multiplying the current replacement cost of the reserve component by its effective age, then dividing the result by the reserve component's useful life. The sum total of all reserve components' fully funded balances is the association's fully funded balance.

. "Governing documents" means the articles of incorporation, bylaws, plat, declaration of covenants, conditions, and restrictions, rules and regulations of the association, or other written instrument by which the association has the authority to exercise any of the powers provided for in this chapter or to manage, maintain, or otherwise affect the property under its jurisdiction.

. "Homeowners' association" or "association" means a corporation, unincorporated association, or other legal entity, each member of which is an owner of residential real property located within the association's jurisdiction, as described in the governing documents, and by virtue of membership or ownership of property is obligated to pay real property taxes, insurance premiums, maintenance costs, or for improvement of real property other than that which is owned by the member. "Homeowners' association" does not mean an association created under chapter 64.32 or 64.34 RCW.

. "Lot" means a physical portion of the real property located within an association's jurisdiction designated for separate ownership.

. "Owner" means the owner of a lot, but does not include a person who has an interest in a lot solely as security for an obligation. "Owner" also means the vendee, not the vendor, of a lot under a real estate contract.

. "Remaining useful life" means the estimated time, in years, before a reserve component will require major maintenance, repair, or replacement to perform its intended function.

. "Replacement cost" means the current cost of replacing, repairing, or restoring a reserve component to its original functional condition.

. "Reserve component" means a common element whose cost of maintenance, repair, or replacement is infrequent, significant, and impractical to include in an annual budget.

. "Reserve study professional" means an independent person who is suitably qualified by knowledge, skill, experience, training, or education to prepare a reserve study in accordance with *RCW 64.34.380 and 64.34.382.

. "Residential real property" means any real property, the use of which is limited by law, covenant or otherwise to primarily residential or recreational purposes.

. "Significant assets" means that the current replacement value of the major reserve components is seventy-five percent or more of the gross budget of the association, excluding the association's reserve account funds.

. "Useful life" means the estimated time, between years, that major maintenance, repair, or replacement is estimated to occur.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1309-S.SL.pdf?cite=2011%20c%20189%20§%207[2011 c 189 § 7]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1471-S.SL.pdf?cite=1995%20c%20283%20§%202[1995 c 283 § 2]; ]

== 64.38.015 - Association membership.
The membership of an association at all times shall consist exclusively of the owners of all real property over which the association has jurisdiction, both developed and undeveloped.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1471-S.SL.pdf?cite=1995%20c%20283%20§%203[1995 c 283 § 3]; ]

== 64.38.020 - Association powers.
Unless otherwise provided in the governing documents, an association may:

. Adopt and amend bylaws, rules, and regulations;

. Adopt and amend budgets for revenues, expenditures, and reserves, and impose and collect assessments for common expenses from owners;

. Hire and discharge or contract with managing agents and other employees, agents, and independent contractors;

. Institute, defend, or intervene in litigation or administrative proceedings in its own name on behalf of itself or two or more owners on matters affecting the homeowners' association, but not on behalf of owners involved in disputes that are not the responsibility of the association;

. Make contracts and incur liabilities;

. Regulate the use, maintenance, repair, replacement, and modification of common areas;

. Cause additional improvements to be made as a part of the common areas;

. Acquire, hold, encumber, and convey in its own name any right, title, or interest to real or personal property;

. Grant easements, leases, licenses, and concessions through or over the common areas and petition for or consent to the vacation of streets and alleys;

. Impose and collect any payments, fees, or charges for the use, rental, or operation of the common areas;

. Impose and collect charges for late payments of assessments and, after notice and an opportunity to be heard by the board of directors or by the representative designated by the board of directors and in accordance with the procedures as provided in the bylaws or rules and regulations adopted by the board of directors, levy reasonable fines in accordance with a previously established schedule adopted by the board of directors and furnished to the owners for violation of the bylaws, rules, and regulations of the association;

. Exercise any other powers conferred by the bylaws;

. Exercise all other powers that may be exercised in this state by the same type of corporation as the association; and 

. Exercise any other powers necessary and proper for the governance and operation of the association.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1471-S.SL.pdf?cite=1995%20c%20283%20§%204[1995 c 283 § 4]; ]

== 64.38.025 - Board of directors—Standard of care—Restrictions—Budget—Removal from board.
. Except as provided in the association's governing documents or this chapter, the board of directors shall act in all instances on behalf of the association. In the performance of their duties, the officers and members of the board of directors shall exercise the degree of care and loyalty required of an officer or director of a corporation organized under chapter 24.03 RCW.

. The board of directors shall not act on behalf of the association to amend the articles of incorporation, to take any action that requires the vote or approval of the owners, to terminate the association, to elect members of the board of directors, or to determine the qualifications, powers, and duties, or terms of office of members of the board of directors; but the board of directors may fill vacancies in its membership of the unexpired portion of any term.

. Except as provided in RCW 64.90.080, 64.90.405(1) (b) and (c), and 64.90.525, within thirty days after adoption by the board of directors of any proposed regular or special budget of the association, the board shall set a date for a meeting of the owners to consider ratification of the budget not less than fourteen nor more than sixty days after mailing of the summary. Unless at that meeting the owners of a majority of the votes in the association are allocated or any larger percentage specified in the governing documents reject the budget, in person or by proxy, the budget is ratified, whether or not a quorum is present. In the event the proposed budget is rejected or the required notice is not given, the periodic budget last ratified by the owners shall be continued until such time as the owners ratify a subsequent budget proposed by the board of directors.

. As part of the summary of the budget provided to all owners, the board of directors shall disclose to the owners:

.. The current amount of regular assessments budgeted for contribution to the reserve account, the recommended contribution rate from the reserve study, and the funding plan upon which the recommended contribution rate is based;

.. If additional regular or special assessments are scheduled to be imposed, the date the assessments are due, the amount of the assessments per each owner per month or year, and the purpose of the assessments;

.. Based upon the most recent reserve study and other information, whether currently projected reserve account balances will be sufficient at the end of each year to meet the association's obligation for major maintenance, repair, or replacement of reserve components during the next thirty years;

.. If reserve account balances are not projected to be sufficient, what additional assessments may be necessary to ensure that sufficient reserve account funds will be available each year during the next thirty years, the approximate dates assessments may be due, and the amount of the assessments per owner per month or year;

.. The estimated amount recommended in the reserve account at the end of the current fiscal year based on the most recent reserve study, the projected reserve account cash balance at the end of the current fiscal year, and the percent funded at the date of the latest reserve study;

.. The estimated amount recommended in the reserve account based upon the most recent reserve study at the end of each of the next five budget years, the projected reserve account cash balance in each of those years, and the projected percent funded for each of those years; and

.. If the funding plan approved by the association is implemented, the projected reserve account cash balance in each of the next five budget years and the percent funded for each of those years.

. The owners by a majority vote of the voting power in the association present, in person or by proxy, and entitled to vote at any meeting of the owners at which a quorum is present, may remove any member of the board of directors with or without cause.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5334.SL.pdf?cite=2019%20c%20238%20§%20222[2019 c 238 § 222]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1309-S.SL.pdf?cite=2011%20c%20189%20§%208[2011 c 189 § 8]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1471-S.SL.pdf?cite=1995%20c%20283%20§%205[1995 c 283 § 5]; ]

== 64.38.028 - Removal of discriminatory provisions in governing documents—Procedure.
. The association, acting through a simple majority vote of its board, may amend the association's governing documents for the purpose of removing:

.. Every covenant, condition, or restriction that is void by reason of RCW 49.60.224; and

.. Every covenant, condition, restriction, or prohibition, including a right of entry or possibility of reverter, that directly or indirectly limits the use or occupancy of real property on the basis of a protected class under chapter 49.60 RCW.

. Upon the board's receipt of a written request by a member of the association that the board exercise its amending authority granted under subsection (1) of this section, the board must, within a reasonable time, amend the governing documents, as provided under this section.

. Amendments under subsection (1) of this section may be executed by any board officer.

. Amendments made under subsection (1) of this section must be recorded in the public records and state the following:

"This amendment strikes from these covenants, conditions, and restrictions those provisions that are void under RCW 49.60.224. Specifically, this amendment strikes:

.. Those provisions that forbid or restrict use, occupancy, conveyance, encumbrance, or lease of real property to individuals on the basis of a protected class under chapter 49.60 RCW; and

.. Every covenant, condition, restriction, or prohibition, including a right of entry or possibility of reverter, that directly or indirectly limits the use or occupancy of real property on the basis of a protected class under chapter 49.60 RCW."

. Board action under this section does not require the vote or approval of the owners.

. As provided in RCW 49.60.227:

.. Any owner, occupant, or tenant in the association or board may bring an action in superior court to have any provision of a written instrument that is void pursuant to RCW 49.60.224 stricken from the public records; or

.. Any owner of property subject to a written instrument that contains a provision that is void pursuant to RCW 49.60.224 may record a restrictive covenant modification as defined in RCW 49.60.227.

. Nothing in this section prohibiting discrimination based on families with children status applies to housing for older persons as defined by the federal fair housing amendments act of 1988, 42 U.S.C. Sec. 3607(b)(1) through (3), as amended by the housing for older persons act of 1995, P.L. 104-76, as enacted on December 28, 1995. Nothing in this section authorizes requirements for housing for older persons different than the requirements in the federal fair housing amendments act of 1988, 42 U.S.C. Sec. 3607(b)(1) through (3), as amended by the housing for older persons act of 1995, P.L. 104-76, as enacted on December 28, 1995.

. Except as otherwise provided in subsection (2) of this section, (a) nothing in this section creates a duty on the part of owners, occupants, tenants, associations, or boards to amend the governing documents as provided in this section, or to bring an action as authorized under this section and RCW 49.60.227; and (b) an owner, occupant, tenant, association, or board is not liable for failing to amend the governing documents or to pursue an action in court as authorized under this section and RCW 49.60.227.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2514-S.SL.pdf?cite=2018%20c%2065%20§%202[2018 c 65 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6169.SL.pdf?cite=2006%20c%2058%20§%202[2006 c 58 § 2]; ]

== 64.38.030 - Association bylaws.
Unless provided for in the governing documents, the bylaws of the association shall provide for:

. The number, qualifications, powers and duties, terms of office, and manner of electing and removing the board of directors and officers and filling vacancies;

. Election by the board of directors of the officers of the association as the bylaws specify;

. Which, if any, of its powers the board of directors or officers may delegate to other persons or to a managing agent;

. Which of its officers may prepare, execute, certify, and record amendments to the governing documents on behalf of the association; 

. The method of amending the bylaws; and

. Subject to the provisions of the governing documents, any other matters the association deems necessary and appropriate.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1471-S.SL.pdf?cite=1995%20c%20283%20§%206[1995 c 283 § 6]; ]

== 64.38.033 - Flag of the United States—Outdoor display—Governing documents.
. The governing documents may not prohibit the outdoor display of the flag of the United States by an owner or resident on the owner's or resident's property if the flag is displayed in a manner consistent with federal flag display law, 4 U.S.C. Sec. 1 et seq. The governing documents may include reasonable rules and regulations, consistent with 4 U.S.C. Sec. 1 et seq., regarding the placement and manner of display of the flag of the United States.

. The governing documents may not prohibit the installation of a flagpole for the display of the flag of the United States. The governing documents may include reasonable rules and regulations regarding the location and the size of the flagpole.

. For purposes of this section, "flag of the United States" means the flag of the United States as defined in federal flag display law, 4 U.S.C. Sec. 1 et seq., that is made of fabric, cloth, or paper and that is displayed from a staff or flagpole or in a window. For purposes of this section, "flag of the United States" does not mean a flag depiction or emblem made of lights, paint, roofing, siding, paving materials, flora, or balloons, or of any similar building, landscaping, or decorative component.

. The provisions of this section shall be construed to apply retroactively to any governing documents in effect on June 10, 2004. Any provision in a governing document in effect on June 10, 2004, that is inconsistent with this section shall be void and unenforceable.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2934.SL.pdf?cite=2004%20c%20169%20§%201[2004 c 169 § 1]; ]

== 64.38.034 - Political yard signs—Governing documents.
. The governing documents may not prohibit the outdoor display of political yard signs by an owner or resident on the owner's or resident's property before any primary or general election. The governing documents may include reasonable rules and regulations regarding the placement and manner of display of political yard signs.

. This section applies retroactively to any governing documents in effect on July 24, 2005. Any provision in a governing document in effect on July 24, 2005, that is inconsistent with this section is void and unenforceable.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6064-S.SL.pdf?cite=2005%20c%20179%20§%201[2005 c 179 § 1]; ]

== 64.38.035 - Association meetings—Notice—Board of directors.
. A meeting of the association must be held at least once each year. Special meetings of the association may be called by the president, a majority of the board of directors, or by owners having ten percent of the votes in the association. The association must make available to each owner of record for examination and copying minutes from the previous association meeting not more than sixty days after the meeting. Minutes of the previous association meeting must be approved at the next association meeting in accordance with the association's governing documents.

. Not less than fourteen nor more than sixty days in advance of any meeting of the association, the secretary or other officers specified in the bylaws shall provide written notice to each owner of record by:

.. Hand-delivery to the mailing address of the owner or other address designated in writing by the owner;

.. Prepaid first-class United States mail to the mailing address of the owner or to any other mailing address designated in writing by the owner; or

.. Electronic transmission to an address, location, or system designated in writing by the owner. Notice to owners by an electronic transmission complies with this section only with respect to those owners who have delivered to the secretary or other officers specified in the bylaws a written record consenting to receive electronically transmitted notices. An owner who has consented to receipt of electronically transmitted notices may revoke the consent at any time by delivering a written record of the revocation to the secretary or other officer specified in the bylaws. Consent is deemed revoked if the secretary or other officer specified in the bylaws is unable to electronically transmit two consecutive notices given in accordance with the consent.

. The notice of any meeting shall state the time and place of the meeting and the business to be placed on the agenda by the board of directors for a vote by the owners, including the general nature of any proposed amendment to the articles of incorporation, bylaws, any budget or changes in the previously approved budget that result in a change in assessment obligation, and any proposal to remove a director.

. Except as provided in this subsection, all meetings of the board of directors shall be open for observation by all owners of record and their authorized agents. The board of directors shall keep minutes of all actions taken by the board, which shall be available to all owners. Upon the affirmative vote in open meeting to assemble in closed session, the board of directors may convene in closed executive session to consider personnel matters; consult with legal counsel or consider communications with legal counsel; and discuss likely or pending litigation, matters involving possible violations of the governing documents of the association, and matters involving the possible liability of an owner to the association. The motion shall state specifically the purpose for the closed session. Reference to the motion and the stated purpose for the closed session shall be included in the minutes. The board of directors shall restrict the consideration of matters during the closed portions of meetings only to those purposes specifically exempted and stated in the motion. No motion, or other action adopted, passed, or agreed to in closed session may become effective unless the board of directors, following the closed session, reconvenes in open meeting and votes in the open meeting on such motion, or other action which is reasonably identified. The requirements of this subsection shall not require the disclosure of information in violation of law or which is otherwise exempt from disclosure.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2567-S.SL.pdf?cite=2014%20c%2020%20§%201[2014 c 20 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1370-S.SL.pdf?cite=2013%20c%20108%20§%201[2013 c 108 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1471-S.SL.pdf?cite=1995%20c%20283%20§%207[1995 c 283 § 7]; ]

== 64.38.040 - Quorum for meeting.
Unless the governing documents specify a different percentage, a quorum is present throughout any meeting of the association if the owners to which thirty-four percent of the votes of the association are allocated are present in person or by proxy at the beginning of the meeting.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1471-S.SL.pdf?cite=1995%20c%20283%20§%208[1995 c 283 § 8]; ]

== 64.38.045 - Financial and other records—Property of association—Copies—Examination—Annual financial statement—Accounts.
. The association or its managing agent shall keep financial and other records sufficiently detailed to enable the association to fully declare to each owner the true statement of its financial status. All financial and other records of the association, including but not limited to checks, bank records, and invoices, in whatever form they are kept, are the property of the association. Each association managing agent shall turn over all original books and records to the association immediately upon termination of the management relationship with the association, or upon such other demand as is made by the board of directors. An association managing agent is entitled to keep copies of association records. All records which the managing agent has turned over to the association shall be made reasonably available for the examination and copying by the managing agent.

. All records of the association, including the names and addresses of owners and other occupants of the lots, shall be available for examination by all owners, holders of mortgages on the lots, and their respective authorized agents on reasonable advance notice during normal working hours at the offices of the association or its managing agent. The association shall not release the unlisted telephone number of any owner. The association may impose and collect a reasonable charge for copies and any reasonable costs incurred by the association in providing access to records.

. At least annually, the association shall prepare, or cause to be prepared, a financial statement of the association. The financial statements of associations with annual assessments of fifty thousand dollars or more shall be audited at least annually by an independent certified public accountant, but the audit may be waived if sixty-seven percent of the votes cast by owners, in person or by proxy, at a meeting of the association at which a quorum is present, vote each year to waive the audit.

. The funds of the association shall be kept in accounts in the name of the association and shall not be commingled with the funds of any other association, nor with the funds of any manager of the association or any other person responsible for the custody of such funds.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1471-S.SL.pdf?cite=1995%20c%20283%20§%209[1995 c 283 § 9]; ]

== 64.38.050 - Violation—Remedy—Attorneys' fees.
Any violation of the provisions of this chapter entitles an aggrieved party to any remedy provided by law or in equity. The court, in an appropriate case, may award reasonable attorneys' fees to the prevailing party.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1471-S.SL.pdf?cite=1995%20c%20283%20§%2010[1995 c 283 § 10]; ]

== 64.38.055 - Governing documents—Solar panels.
. The governing documents may not prohibit the installation of a solar energy panel by an owner or resident on the owner's or resident's property as long as the solar energy panel:

.. Meets applicable health and safety standards and requirements imposed by state and local permitting authorities;

.. If used to heat water, is certified by the solar rating certification corporation or another nationally recognized certification agency. Certification must be for the solar energy panel and for installation; and

.. If used to produce electricity, meets all applicable safety and performance standards established by the national electric code, the institute of electrical and electronics engineers, accredited testing laboratories, such as underwriters laboratories, and, where applicable, rules of the utilities and transportation commission regarding safety and reliability.

. The governing documents may:

.. Prohibit the visibility of any part of a roof-mounted solar energy panel above the roofline;

.. Permit the attachment of a solar energy panel to the slope of a roof facing a street only if:

... The solar energy panel conforms to the slope of the roof; and

... The top edge of the solar energy panel is parallel to the roof ridge; or

.. Require:

... A solar energy panel frame, a support bracket, or any visible piping or wiring to be painted to coordinate with the roofing material;

... An owner or resident to shield a ground-mounted solar energy panel if shielding the panel does not prohibit economic installation of the solar energy panel or degrade the operational performance quality of the solar energy panel by more than ten percent; or

... Owners or residents who install solar energy panels to indemnify or reimburse the association or its members for loss or damage caused by the installation, maintenance, or use of a solar energy panel.

. The governing documents may include other reasonable rules regarding the placement and manner of a solar energy panel.

. For purposes of this section, "solar energy panel" means a panel device or system or combination of panel devices or systems that relies on direct sunlight as an energy source, including a panel device or system or combination of panel devices or systems that collects sunlight for use in:

.. The heating or cooling of a structure or building;

.. The heating or pumping of water;

.. Industrial, commercial, or agricultural processes; or

.. The generation of electricity.

. This section does not apply to common areas as defined in RCW 64.38.010.

. This section applies retroactively to a governing document in effect on July 26, 2009. A provision in a governing document in effect on July 26, 2009, that is inconsistent with this section is void and unenforceable.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5136-S.SL.pdf?cite=2009%20c%2051%20§%201[2009 c 51 § 1]; ]

== 64.38.057 - Governing documents—Drought resistant landscaping, wildfire ignition resistant landscaping.
. The governing documents may not prohibit the installation of drought resistant landscaping or wildfire ignition resistant landscaping. However, the governing documents may include reasonable rules regarding the placement and aesthetic appearance of drought resistant landscaping or wildfire ignition resistant landscaping, as long as the rules do not render the use of drought resistant landscaping or wildfire ignition resistant landscaping unreasonably costly or otherwise effectively infeasible.

. If a property is located within the geographic designation of an order of a drought condition issued by the department of ecology under RCW 43.83B.405, an association may not sanction or impose a fine or assessment against an owner, or resident on the owner's property, for reducing or eliminating the watering of vegetation or lawns for the duration of the drought condition order.

. Nothing in this section may be construed to prohibit or restrict the establishment and maintenance of a fire buffer within the building ignition zone.

. The definitions in this subsection apply throughout this section unless the context clearly requires otherwise.

.. "Building ignition zone" means a building and surrounding area up to two hundred feet from the foundation.

.. "Drought resistant landscaping" means the use of any noninvasive vegetation adapted to arid or dry conditions, stone, or landscaping rock.

.. "Firewise" means the firewise communities program developed by the national fire protection association, which encourages local solutions for wildfire safety by involving homeowners, community leaders, planners, developers, firefighters, and others in the effort to protect people and property from wildfire risks.

.. "Wildfire ignition resistant landscaping" includes:

... Any landscaping tools or techniques, or noninvasive vegetation, that do not readily ignite from a flame or other ignition source; or

... The use of firewise methods to reduce ignition risk in a building ignition zone.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1165.SL.pdf?cite=2020%20c%209%20§%202[2020 c 9 § 2]; ]

== 64.38.060 - Adult family homes.
. To effectuate the public policy of chapter 70.128 RCW, the governing documents may not limit, directly or indirectly:

.. Persons with disabilities from living in an adult family home licensed under chapter 70.128 RCW; or

.. Persons and legal entities from operating adult family homes licensed under chapter 70.128 RCW, whether for-profit or nonprofit, to provide services covered under chapter 70.128 RCW. However, this subsection does not prohibit application of reasonable nondiscriminatory regulation, including but not limited to landscaping standards or regulation of sign location or size, that applies to all residential property subject to the governing documents.

. This section applies retroactively to any governing documents in effect on July 26, 2009. Any provision in a governing document in effect on or after July 26, 2009, that is inconsistent with subsection (1) of this section is unenforceable to the extent of the conflict.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1935-S2.SL.pdf?cite=2009%20c%20530%20§%204[2009 c 530 § 4]; ]

== 64.38.065 - Reserve account and study.
. An association is encouraged to establish a reserve account with a financial institution to fund major maintenance, repair, and replacement of common elements, including limited common elements that will require major maintenance, repair, or replacement within thirty years. If the association establishes a reserve account, the account must be in the name of the association. The board of directors is responsible for administering the reserve account.

. Except as provided in RCW 64.90.080 and 64.90.545, unless doing so would impose an unreasonable hardship, an association with significant assets shall prepare and update a reserve study, in accordance with the association's governing documents and this chapter. The initial reserve study must be based upon a visual site inspection conducted by a reserve study professional.

. Except as provided in RCW 64.90.080 and 64.90.545, unless doing so would impose an unreasonable hardship, the association shall update the reserve study annually. At least every three years, an updated reserve study must be prepared and based upon a visual site inspection conducted by a reserve study professional.

. The decisions relating to the preparation and updating of a reserve study must be made by the board of directors in the exercise of the reasonable discretion of the board. The decisions must include whether a reserve study will be prepared or updated, and whether the assistance of a reserve study professional will be utilized.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5334.SL.pdf?cite=2019%20c%20238%20§%20223[2019 c 238 § 223]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1309-S.SL.pdf?cite=2011%20c%20189%20§%209[2011 c 189 § 9]; ]

== 64.38.070 - Reserve study—Requirements.
. A reserve study as described in RCW 64.38.065 is supplemental to the association's operating and maintenance budget. In preparing a reserve study, the association shall estimate the anticipated major maintenance, repair, and replacement costs, whose infrequent and significant nature make them impractical to be included in an annual budget.

. A reserve study must include:

.. A reserve component list, including any reserve component that would cost more than one percent of the annual budget of the association, not including the reserve account, for major maintenance, repair, or replacement. If one of these reserve components is not included in the reserve study, the study should provide commentary explaining the basis for its exclusion. The study must also include quantities and estimates for the useful life of each reserve component, remaining useful life of each reserve component, and current major maintenance, repair, or replacement cost for each reserve component;

.. The date of the study, and a statement that the study meets the requirements of this section;

.. The following level of reserve study performed:

... Level I: Full reserve study funding analysis and plan;

... Level II: Update with visual site inspection; or

... Level III: Update with no visual site inspection;

.. The association's reserve account balance;

.. The percentage of the fully funded balance that the reserve account is funded;

.. Special assessments already implemented or planned;

.. Interest and inflation assumptions;

.. Current reserve account contribution rates for a full funding plan and baseline funding plan;

.. A recommended reserve account contribution rate, a contribution rate for a full funding plan to achieve one hundred percent fully funded reserves by the end of the thirty-year study period, a baseline funding plan to maintain the reserve balance above zero throughout the thirty-year study period without special assessments, and a contribution rate recommended by the reserve study professional;

.. A projected reserve account balance for thirty years and a funding plan to pay for projected costs from that reserve account balance without reliance on future unplanned special assessments; and

.. A statement on whether the reserve study was prepared with the assistance of a reserve study professional.

. A reserve study must also include the following disclosure: "This reserve study should be reviewed carefully. It may not include all common and limited common element components that will require major maintenance, repair, or replacement in future years, and may not include regular contributions to a reserve account for the cost of such maintenance, repair, or replacement. The failure to include a component in a reserve study, or to provide contributions to a reserve account for a component, may, under some circumstances, require you to pay on demand as a special assessment your share of common expenses for the cost of major maintenance, repair, or replacement of a reserve component."

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1309-S.SL.pdf?cite=2011%20c%20189%20§%2010[2011 c 189 § 10]; ]

== 64.38.075 - Reserve account—Withdrawals.
An association may withdraw funds from its reserve account to pay for unforeseen or unbudgeted costs that are unrelated to maintenance, repair, or replacement of the reserve components. The board of directors shall record any such withdrawal in the minute books of the association, cause notice of any such withdrawal to be hand delivered or sent prepaid by first-class United States mail to the mailing address of each owner or to any other mailing address designated in writing by the owner, and adopt a repayment schedule not to exceed twenty-four months unless it determines that repayment within twenty-four months would impose an unreasonable burden on the owners. Payment for major maintenance, repair, or replacement of the reserve components out of cycle with the reserve study projections or not included in the reserve study may be made from the reserve account without meeting the notification or repayment requirements under this section.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1309-S.SL.pdf?cite=2011%20c%20189%20§%2011[2011 c 189 § 11]; ]

== 64.38.080 - Reserve study—Demand for preparation and inclusion in budget.
. When more than three years have passed since the date of the last reserve study prepared by a reserve study professional, the owners to which at least thirty-five percent of the votes are allocated may demand, in writing, to the association that the cost of a reserve study be included in the next budget and that the study be prepared by the end of that budget year. The written demand must refer to this section. The board of directors shall, upon receipt of the written demand, provide the owners who make the demand reasonable assurance that the board will include a reserve study in the next budget and, if the budget is not rejected by a majority of the owners, will arrange for the completion of a reserve study.

. If a written demand under this section is made and a reserve study is not timely prepared, a court may order specific performance and award reasonable attorneys' fees to the prevailing party in any legal action brought to enforce this section. An association may assert unreasonable hardship as an affirmative defense in any action brought against it under this section. Without limiting this affirmative defense, an unreasonable hardship exists where the cost of preparing a reserve study would exceed five percent of the association's annual budget.

. An owner's duty to pay for common expenses is not excused because of the association's failure to comply with this section or this chapter. A budget ratified by the owners is not invalidated because of the association's failure to comply with this section or this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1309-S.SL.pdf?cite=2011%20c%20189%20§%2012[2011 c 189 § 12]; ]

== 64.38.085 - Reserve account and study—Liability.
Monetary damages or any other liability may not be awarded against or imposed upon the association, the officers or board of directors of the association, or those persons who may have provided advice or assistance to the association or its officers or directors, for failure to: Establish a reserve account; have a current reserve study prepared or updated in accordance with the requirements of this chapter; or make the reserve disclosures in accordance with this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1309-S.SL.pdf?cite=2011%20c%20189%20§%2013[2011 c 189 § 13]; ]

== 64.38.090 - Reserve study—Exemptions.
Except as provided in RCW 64.90.080 and 64.90.545, an association is not required to follow the reserve study requirements under RCW 64.38.025 and RCW 64.38.065 through 64.38.085 if the cost of the reserve study exceeds five percent of the association's annual budget, the association does not have significant assets, or there are ten or fewer homes in the association.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5334.SL.pdf?cite=2019%20c%20238%20§%20224[2019 c 238 § 224]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1309-S.SL.pdf?cite=2011%20c%20189%20§%2014[2011 c 189 § 14]; ]

== 64.38.095 - Application to common interest communities.
. This chapter does not apply to common interest communities as defined in RCW 64.90.010:

.. Created on or after July 1, 2018; or

.. That have amended their governing documents to provide that chapter 64.90 RCW will apply to the common interest community pursuant to RCW 64.90.095.

. Pursuant to RCW 64.90.080, the following provisions of chapter 64.90 RCW apply, and any inconsistent provisions of this chapter do not apply, to a common interest community created before July 1, 2018:

.. RCW 64.90.095;

.. RCW 64.90.405(1) (b) and (c);

.. RCW 64.90.525; and

.. RCW 64.90.545.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5334.SL.pdf?cite=2019%20c%20238%20§%20225[2019 c 238 § 225]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6175-S.SL.pdf?cite=2018%20c%20277%20§%20505[2018 c 277 § 505]; ]

