= 64.36 - Timeshare regulation.
:toc:

== 64.36.010 - Definitions.
As used in this chapter, the following terms have the meanings indicated unless the context clearly requires otherwise.

. "Advertisement" means any written, printed, audio, or visual communication which is published in whole or part to sell, offer to sell, or solicit an offer for a timeshare.

. "Affiliate of a promoter" means any person who controls, is controlled by, or is under the control of a promoter.

. "Commercial promotional programs" mean packaging or putting together advertising or promotional materials involving promises of gifts, prizes, awards, or other items of value to solicit prospective purchasers to purchase a product or commodity.

. "Director" means the director of licensing.

. "Interval" means that period of time when a timeshare owner is entitled to the possession and use of the timeshare unit.

. "Offer" means any inducement, solicitation, or attempt to encourage any person to acquire a timeshare.

. "Person" means a natural person, corporation, business trust, estate, trust, partnership, association, joint venture, or other legal or commercial entity.

. "Promoter" means any person directly or indirectly instrumental in organizing, wholly or in part, a timeshare offering.

. "Purchaser" means any person, other than a promoter, who by means of a voluntary transfer acquires a legal or equitable interest in a timeshare, other than as security for an obligation.

. "Sale" or "sell" includes every contract of sale of, contract to sell, or disposition of, a timeshare for value.

. "Timeshare" means a right to occupy a unit or any of several units during three or more separate time periods over a period of at least three years, including renewal options, whether or not coupled with an estate in land.

. "Timeshare expenses" means expenditures, fees, charges, or liabilities: (a) Incurred with respect to the timeshares by or on behalf of all timeshare owners in one timeshare property; and (b) imposed on the timeshare units by the entity governing a project of which the timeshare property is a part, together with any allocations to reserves but excluding purchase money payable for timeshares.

. "Timeshare instrument" means one or more documents, by whatever name denominated, creating or regulating timeshares.

. "Timeshare owner" means a person who is an owner or co-owner of a timeshare. If title to a timeshare is held in trust, "timeshare owner" means the beneficiary of the trust.

. "Timeshare salesperson" means any natural person who offers a timeshare unit for sale.

. "Unit" means the real or personal property, or portion thereof, in which the timeshare exists and which is designated for separate use.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c370.pdf?cite=1987%20c%20370%20§%201[1987 c 370 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c358.pdf?cite=1985%20c%20358%20§%201[1985 c 358 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%201[1983 1st ex.s. c 22 § 1]; ]

== 64.36.020 - Registration required before advertisement, solicitation, or offer—Requirements for registration—Exemption authorized—Penalties.
. A timeshare offering registration must be effective before any advertisement, solicitation of an offer, or any offer or sale of a timeshare may be made in this state.

. An applicant shall apply for registration by filing with the director:

.. A copy of the disclosure document prepared in accordance with RCW 64.36.140 and signed by the applicant;

.. An application for registration prepared in accordance with RCW 64.36.030;

.. An irrevocable consent to service of process signed by the applicant;

.. The prescribed registration fee; and

.. Any other information the director may by rule require in the protection of the public interest.

. The registration requirements do not apply to:

.. An offer, sale, or transfer of not more than one timeshare in any twelve-month period;

.. A gratuitous transfer of a timeshare;

.. A sale under court order;

.. A sale by a government or governmental agency;

.. A sale by forfeiture, foreclosure, or deed in lieu of foreclosure; or

.. A sale of a timeshare property or all timeshare units therein to any one purchaser.

. The director may by rule or order exempt any potential registrant from the requirements of this chapter if the director finds registration is unnecessary for the protection of the public interest.

. [Empty]
.. Except as provided in (b) of this subsection, any person who violates this section is guilty of a gross misdemeanor.

.. Any person who knowingly violates this section is guilty of a class C felony punishable according to chapter 9A.20 RCW.

.. No indictment or information for a felony may be returned under this chapter more than five years after the alleged violation.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20289[2003 c 53 § 289]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%202[1983 1st ex.s. c 22 § 2]; ]

== 64.36.025 - Timeshare interest reservation—Definition—Registration required—Promoter's obligations—Deposits—Escrow—Purchaser cancellation rights—Insolvency prior to completion.
. For the purpose of this section, "timeshare interest reservation" means a revocable right to purchase an interest in a timeshare project for which construction has not yet been completed and an effective registration has been obtained under this chapter.

. An effective registration pursuant to this chapter is required for any party to offer to sell a timeshare interest reservation. Promoters offering a timeshare interest reservation under this section must provide the registered disclosure document required by RCW 64.36.140 to each prospective purchaser before he or she enters into a timeshare interest reservation. Prior to the signing of a purchase agreement, the subject property or properties must be completed, the timeshare offering registration required by RCW 64.36.020 must be amended to reflect any changes to the property and must be reapproved by the department, the disclosure document required by RCW 64.36.140 must be revised, and the new version of the disclosure document must be provided to the prospective purchaser.

. Deposits accepted by promoters on a timeshare interest reservation may be no more than twenty percent of the total purchase price of the timeshare interest that is being purchased. Within one business day after being accepted by the promoter, any deposit on a timeshare interest reservation shall be deposited in an account in a federally insured depository located in the state of Washington. This account must be an escrow account wherein the deposited funds are held for the benefit of the purchaser. The department may request that deposits be placed in impoundment under RCW 64.36.130.

. In addition to the cancellation rights provided in RCW 64.36.150, the purchaser has the right to cancel the purchase at any time before the signing of a purchase agreement. If the purchaser notifies the promoter that he or she wishes to cancel the timeshare interest reservation, the promoter must refund the full amount of the deposit minus any account fees within ten days of the notice.

. If prior to signing a purchase agreement the purchaser learns that the promoter proposes to raise the purchase price above the price agreed to in the written reservation agreement for the timeshare interest reservation, the written reservation agreement is void and all deposit moneys including account fees shall be returned to the purchaser within ten days after the purchaser learns of the proposed price increase.

. If the promoter charges account fees to pay for administrative costs of holding the purchaser's funds in escrow, these fees may be no more than one percent of the total deposit paid towards the timeshare interest reservation by the purchaser.

. The promoter shall provide instructions to the escrow company for release of the funds to be held in escrow in compliance with this section and rules of the department.

. The purchaser's right to cancel and the amount of the deposit proposed to be retained for account fees in the event of cancellation must be included in the contract for the sale of a timeshare interest reservation and the contract must state:

PURCHASER CANCELLATION RIGHTS

As a purchaser of a timeshare interest reservation, you have the right to cancel this timeshare interest reservation and receive a refund of all consideration paid (less only those account fee deductions which were fully disclosed at the time of the agreement) by providing written notice of the cancellation to the promoter or the promoter's agent at any time prior to signing a purchase agreement. You also have a right to cancel your purchase within seven days of signing a purchase agreement.

. If it appears that the timeshare project will become or does become insolvent prior to completion, the promoter shall instruct the escrow company to immediately return all deposits to purchasers of timeshare interest reservations. If funds are returned under this subsection, the promoter may not retain any portion of the deposits for account fees.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2513-S.SL.pdf?cite=2002%20c%20226%20§%202[2002 c 226 § 2]; ]

== 64.36.028 - Timeshare interest—Incomplete projects or facilities—Promoter's obligations—Funds—Purchaser's rights.
. An effective registration pursuant to this chapter is required for any party to offer to sell a timeshare interest. A promoter who offers to sell or sells revocable timeshare interests in incomplete projects or facilities is limited by and must comply with all of the requirements of RCW 64.36.025. If a promoter seeks to enter into irrevocable purchase agreements with purchasers for timeshare interests in incomplete projects or facilities, the promoter must meet the requirements in this section in addition to RCW 64.36.020 and the following limitations and conditions apply:

.. The promoter is limited to offering or selling only fee simple deeded timeshare interests;

.. Construction on the project must have begun by the time the irrevocable purchase agreement is signed and the purchaser must have the right to occupy the unit and use all contracted for amenities no later than within two years of the date that the irrevocable purchase agreement is signed;

.. The promoter must establish an independent third-party escrow account for the purpose of protecting the funds or other property paid, pledged, or deposited by purchasers;

.. The promoter's solicitations, advertisements, and promotional materials must clearly and conspicuously disclose that "THE PROJECT IS NOT YET COMPLETED; IT IS STILL UNDER CONSTRUCTION"; and

.. The promoter's solicitations, advertisements, and promotional materials and the timeshare interest purchase agreement must clearly and conspicuously provide for and disclose the last possible estimated date for completion of construction of any building the promoter is contractually obligated to the purchaser to complete.

. The timeshare interest purchase agreement must contain the following language in fourteen-point bold face type: "If the building in which the timeshare interest is located and all contracted for amenities are not completed by [estimated date of completion], the purchaser has the right to void the purchase agreement and is entitled to a full, unqualified refund of all moneys paid."

. One hundred percent of all funds or other property that is received from or on behalf of purchasers of timeshare interests prior to the occurrence of events required in this section must be deposited pursuant to a third-party escrow agreement approved by the director. For purposes of this section, "purchasers" includes all persons solicited, offered, or who purchased a timeshare interest by a promoter within the state of Washington. An escrow agent shall maintain the account only in such a manner as to be under the direct supervision and control of the escrow agent. The escrow agent has a fiduciary duty to each purchaser to maintain the escrow accounts in accordance with good accounting practices and to release the purchaser's funds or other property from escrow only in accordance with this chapter. If the escrow agent receives conflicting demands for funds or property held in escrow, the escrow agent shall immediately notify the department of licensing of the dispute and the department shall determine if and how the funds should be distributed. If the purchaser, promoter, or escrow agent disagrees with the department's determination, the parties have the right to request an administrative hearing under chapter 34.05 RCW. Funds may be released from the escrow account to the purchaser if the purchaser cancels within the cancellation period, or to the promoter only when all three of the following conditions occur:

.. The purchaser's cancellation period has expired;

.. Closing has occurred; and

.. Construction is complete and the building is ready to occupy.

. In lieu of depositing purchaser funds into an escrow account, the promoter may post with the department a bond in an amount equal to or greater than the amount that would otherwise be required to be placed into the escrow account.

. Any purchaser has the right to void the timeshare purchase agreement and request a full, unqualified refund if construction of the building in which the timeshare interest is located or all contracted for amenities are not completed within two years from the date that the irrevocable purchase agreement is signed or by the last estimated date of construction contained in the irrevocable purchase agreement, whichever is earlier.

. If the completed timeshare building or contracted for amenities are materially and adversely different from the building or amenities that were promised to purchasers at the time that the purchase agreements were signed, the director may declare any or all of the purchaser contracts void. Before declaring the contracts void, the director shall give the promoter the opportunity for a hearing in accordance with chapters 34.05 and 18.235 RCW.

. If the promoter intends to or does pledge or borrow against funds or properties, that are held in escrow or protected by a bond, to help finance in whole or in part the construction of the timeshare project or to help pay for operating costs, this must be fully, plainly, and conspicuously disclosed in all written advertising, in all written solicitations for the sale of the timeshare interests, in the registration with the director, and in the purchase agreement or contract.

. A promoter who obtains an effective registration for a revocable timeshare interest reservation must meet the requirements of this section in order to complete an irrevocable purchase agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1442-S.SL.pdf?cite=2003%20c%20348%20§%201[2003 c 348 § 1]; ]

== 64.36.030 - Application for registration—Contents.
The application for registration signed by the promoter shall contain the following information on a form prescribed by the director:

. The following financial statements showing the financial condition of the promoter and any affiliate:

.. A balance sheet as of a date within four months before the filing of the application for registration; and

.. Statements of income, shareholders' equity, and material changes in financial position as of the end of the last fiscal year and for any period between the end of the last fiscal year and the date of the last balance sheet;

. A projected budget for the timeshare project for two years after the offering being made, including but not limited to source of revenues and expenses of construction, development, management, maintenance, advertisement, operating reserves, interest, and any other necessary reserves;

. A statement of the selling costs per unit and total sales costs for the project, including sales commissions, advertisement fees, and fees for promotional literature;

. A description of the background of the promoters for the previous ten years, including information about the business experience of the promoter and any relevant criminal convictions, civil law suits, or administrative actions related to such promotion during that period;

. A statement disclosing any fees in excess of the stated price per unit to be charged to the purchasers, a description of their purpose, and the method of calculation;

. A statement disclosing when and where the promoter or an affiliate has previously sold timeshares;

. A statement of any liens, defects, or encumbrances on or affecting the title to the timeshare units;

. Copies of all timeshare instruments; and

. Any additional information to describe the risks which the director considers appropriate.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%204[1983 1st ex.s. c 22 § 4]; ]

== 64.36.035 - Applications for registration, consents to service, affidavits, and permits to market—Authorized signatures required—Corporate shield disclaimer prohibited.
. Applications, consents to service of process, affidavits, and permits to market shall be signed by the promoter, unless a trustee or person with power of attorney is specifically authorized to make such signatures. If the signature of a person with a power of attorney or trustee is used, the filing of the signature shall include a copy of the authorizations for the signature. No promoter or other person responsible under this chapter shall disclaim responsibility because the signature of a trustee or attorney-in-fact, or other substitute was used.

. If the promoter is a corporation or a general partnership, each natural person therein, with a ten percent or greater interest or share in the promoter, shall, in addition to the promoter, be required to sign as required in this section, but may authorize a trustee or a person with power of attorney to make the signatures.

. All persons required to use or authorizing the use of their signatures in this section, individually or otherwise, shall be responsible for affidavits, applications, and permits signed, and for compliance with the provisions of this chapter. Individuals whose signatures are required under this section shall not disclaim their responsibilities because of any corporate shield.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c370.pdf?cite=1987%20c%20370%20§%202[1987 c 370 § 2]; ]

== 64.36.040 - Application for registration—When effective.
If no stop order is in effect and no proceeding is pending under RCW 64.36.100, a complete registration application becomes effective at 3:00 p.m. Pacific Standard Time on the afternoon of the thirtieth calendar day after the filing of the application or the last amendment or at such earlier time as the director determines.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20297[2002 c 86 § 297]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%205[1983 1st ex.s. c 22 § 5]; ]

== 64.36.050 - Timeshare offering—Duration of registration—Renewal—Amendment—Penalties.
. A timeshare offering is registered for a period of one year from the effective date of registration unless the director specifies a different period.

. Registration of a timeshare offering may be renewed for additional periods of one year each, unless the director by rule specifies a different period, by filing a renewal application with the director no later than thirty days before the expiration of the period in subsection (1) of this section and paying the prescribed fees. A renewal application shall contain any information the director requires to indicate any material changes in the information contained in the original application.

. If a material change in the condition of the promoter, the promoter's affiliates, the timeshare project, or the operation or management of the timeshare project occurs during any year, an amendment to the documents filed under RCW 64.36.030 shall be filed, along with the prescribed fees, as soon as reasonably possible and before any further sales occur.

. The promoter shall keep the information in the written disclosures reasonably current at all times by amending the registration. If the promoter fails to amend and keep current the written disclosures or the registrations in instances of material change, the director may require compliance under RCW 64.36.100 and assess penalties.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c370.pdf?cite=1987%20c%20370%20§%203[1987 c 370 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%206[1983 1st ex.s. c 22 § 6]; ]

== 64.36.060 - Application for registration—Acceptance of disclosure documents—Waiver of information—Additional information.
. In lieu of the documents required to be filed under RCW 64.36.030, the director may by rule accept:

.. Any disclosure document filed with agencies of the United States or any other state;

.. Any disclosure document compiled in accordance with any rule of any agency of the United States or any other state; or

.. Any documents submitted pursuant to registration of a timeshare offering under chapter 58.19 RCW before August 1, 1983.

. The director may by rule waive disclosure of information which the director considers unnecessary for the protection of timeshare purchasers.

. The director may by rule require the provision of any other information the director considers necessary to protect timeshare purchasers.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%207[1983 1st ex.s. c 22 § 7]; ]

== 64.36.070 - Registration as timeshare salesperson required—Exemption.
Any individual offering timeshare units or timeshare interest reservations for the individual's own account or for the account of others shall be registered as a timeshare salesperson unless the timeshare offering is exempt from registration under RCW 64.36.020. Registration may be obtained by filing an application with the department of licensing on a form prescribed by the director. The director may require that the applicant demonstrate sufficient knowledge of the timeshare industry and this chapter. A timeshare salesperson who is licensed as a real estate broker or salesperson under chapter 18.85 RCW is exempt from the registration requirement of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2513-S.SL.pdf?cite=2002%20c%20226%20§%201[2002 c 226 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%208[1983 1st ex.s. c 22 § 8]; ]

== 64.36.081 - Fees.
. Applicants or registrants under this chapter shall pay fees determined by the director as provided in RCW 43.24.086. These fees shall be prepaid and the director may establish fees for the following:

.. Processing an original application for registration of a timeshare offering, along with an additional fee for each interval registered or in the timeshare program;

.. Processing consolidations or adding additional inventory into the program;

.. Reviewing and granting exemptions;

.. Processing annual or periodic renewals;

.. Initially and annually processing and administering any required impound, trust, or escrow arrangement;

.. The review of advertising or promotional materials;

.. Registering persons in the business of selling promotional programs for use in timeshare offerings or sales presentations;

.. Registrations and renewal of registrations of salespersons;

.. The transfer of salespersons' permits to other promoters;

.. Administering and processing examinations for salespersons;

.. Conducting site inspections of registered projects and projects for which registration is pending.

. The director may establish penalties for registrants in any situation where a registrant has failed to file an amendment to the registration or the disclosure document in a timely manner for material changes, as required in this chapter and rules adopted under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c370.pdf?cite=1987%20c%20370%20§%204[1987 c 370 § 4]; ]

== 64.36.085 - Inspections of projects—Identification of inspectors.
. The director may require inspections of projects registered under this chapter and promoters and their agents shall cooperate by permitting staff of the department to conduct the inspections.

. The director may perform "spot checks" or inspections of sales offices, during tours or sales presentations or normal business hours, for purposes of enforcing this chapter and determining compliance by the operator and salespersons in the sales, advertising, and promotional activities regulated under this chapter. These inspections or spot checks may be conducted during or at the time of sales presentations or during the hours during which sales are ordinarily scheduled.

. The department employee making the inspections shall show identification upon request. It is a violation of this chapter for the operator or its sales representatives to refuse an inspection or refuse to cooperate with employees of the department conducting the inspection.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c370.pdf?cite=1987%20c%20370%20§%205[1987 c 370 § 5]; ]

== 64.36.090 - Disciplinary action against a timeshare salesperson's application, registration, or license—Unprofessional conduct.
The director may take disciplinary action against a timeshare salesperson's registration or application for registration or a salesperson's license under chapter 18.85 RCW who is selling under this chapter, if the director finds that the applicant or registrant has committed unprofessional conduct as described in RCW 18.235.130. In addition, the director may take disciplinary action if the applicant or registrant:

. Has filed an application for registration as a timeshare salesperson or as a licensee under chapter 18.85 RCW which, as of its effective date, is incomplete in any material respect;

. Has violated or failed to comply with any provision of this chapter or a predecessor act or any rule or order issued under this chapter or a predecessor act;

. Is permanently or temporarily enjoined by any court or administrative order from engaging in or continuing any conduct or practice involving any aspect of the timeshare business;

. Has engaged in dishonest or unethical practices in the timeshare, real estate, or camp resort business;

. Is insolvent either in the sense that the individual's liabilities exceed his or her assets or in the sense that the individual cannot meet his or her obligations as they mature; or

. Has not complied with any condition imposed by the director or is not qualified on the basis of such factors as training, experience, or knowledge of the timeshare business or this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20298[2002 c 86 § 298]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c370.pdf?cite=1987%20c%20370%20§%209[1987 c 370 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%209[1983 1st ex.s. c 22 § 9]; ]

== 64.36.100 - Disciplinary action—Unprofessional conduct—Other conduct, acts, or conditions.
The director may deny or take disciplinary action against any timeshare application or registration if the director finds that the applicant or registrant has engaged in unprofessional conduct as described in RCW 18.235.130. In addition, the director may deny or take disciplinary action based on the following conduct, acts, or conditions:

. The application, written disclosure, or registration is incomplete;

. The activities of the promoter include, or would include, activities which are unlawful or in violation of a law, rule, or ordinance in this state or another jurisdiction;

. The timeshare offering has worked or tended to work a fraud on purchasers, or would likely be adverse to the interests or the economic or physical welfare of purchasers;

. The protections and security arrangements to ensure future quiet enjoyment required under RCW 64.36.130 have not been provided as required by the director for the protection of purchasers; or

. The operating budget proposed by the promoter or promoter-controlled association appears inadequate to meet operating costs or funding of reserve accounts or fees for a consultant to determine adequacy have not been paid by the promoter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20299[2002 c 86 § 299]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c370.pdf?cite=1987%20c%20370%20§%2010[1987 c 370 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%2010[1983 1st ex.s. c 22 § 10]; ]

== 64.36.110 - Requirements of transfer of promoter's interest—Notice to purchaser.
A promoter shall not sell, lease, assign, or otherwise transfer the promoter's interest in the timeshare program unless the transferee agrees in writing to honor the timeshare purchaser's right to use and occupy the timeshare unit, honor the purchaser's right to cancel, and comply with this chapter. In the event of a transfer, each timeshare purchaser whose contract may be affected shall be given written notice of the transfer when the transfer is made.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%2011[1983 1st ex.s. c 22 § 11]; ]

== 64.36.120 - Good faith required—Provision relieving person from duty prohibited—Out-of-state jurisdiction or venue designation void.
. The parties to a timeshare agreement shall deal with each other in good faith.

. A timeshare promoter shall not require any timeshare purchaser to agree to a release, assignment, novation, waiver, or any other provision which relieves any person from a duty imposed by this chapter.

. Any provision in a timeshare contract or agreement which designates jurisdiction or venue in a forum outside this state is void with respect to any cause of action which is enforceable in this state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%2012[1983 1st ex.s. c 22 § 12]; ]

== 64.36.130 - Impoundment of proceeds from sales authorized—Establishment of trusts, escrows, etc.
. The director may by rule require as a condition of registration under this chapter that the proceeds from the sale of the timeshares be impounded until the promoter receives an amount established by the director. The director may by rule determine the conditions of any impoundment required under this section, including the release of moneys for promotional purposes.

. The director, in lieu of or in addition to requiring impoundment under subsection (1) of this section, may require that the registrant establish trusts, escrows, or any other similar arrangement that assures the timeshare purchaser quiet enjoyment of the timeshare unit.

. Impounding will not be required for those timeshare offerors who are able to convey fee simple title, along with title insurance: PROVIDED, That no other facilities are promised in the offering.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%2013[1983 1st ex.s. c 22 § 13]; ]

== 64.36.140 - Disclosure document—Contents.
Any person who offers or sells a timeshare shall provide the prospective purchaser a written disclosure document before the prospective purchaser signs an agreement for the purchase of a timeshare. The timeshare salesperson shall date and sign the disclosure document. The disclosure document shall include:

. The official name and address of the promoter, its parent or affiliates, and the names and addresses of the director and officers of each;

. The location of the timeshare property;

. A general description of the timeshare property and the timeshare units;

. A list of all units offered by the promoter in the same project including:

.. The types, prices, and number of units;

.. Identification and location of units;

.. The types and durations of the timeshares;

.. The maximum number of units that may become part of the timeshare property; and

.. A statement of the maximum number of timeshares that may be created or a statement that there is no maximum.

. A description of any financing offered by the promoter;

. A statement of ownership of all properties included in the timeshare offering including any liens or encumbrances affecting the property;

. Copies of any agreements or leases to be signed by timeshare purchasers at closing and a copy of the timeshare instrument;

. The identity of the managing entity and the manner, if any, whereby the promoter may change the managing entity;

. A description of the selling costs both per unit and for the total project at the time the sale is made;

. A statement disclosing when and where the promoter or its affiliate has previously sold timeshares;

. A description of the nature and purpose of all charges, dues, maintenance fees, and other expenses that may be assessed, including:

.. The current amounts assessed;

.. The method and formula for changes; and

.. The formula for payment of charges if all timeshares are not sold and a statement of who pays additional costs;

. Any services which the promoter provides or expenses the promoter pays which the promoter expects may become a timeshare expense at any subsequent time;

. A statement in bold face type on the cover page of the disclosure document and the cover page of the timeshare purchase agreement that within seven days after receipt of a disclosure document or the signing of the timeshare purchase agreement, whichever is later, a purchaser may cancel any agreement for the purchase of a timeshare from a promoter or a timeshare salesperson and that the cancellation must be in writing and be either hand delivered or mailed to the promoter or the promoter's agent;

. Any restraints on transfer of a timeshare or portion thereof;

. A description of the insurance coverage provided for the benefit of timeshare owners;

. A full and accurate disclosure of whether the timeshare owners are to be permitted or required to become members of or participate in any program for the exchange of property rights among themselves or with the timeshare owners of other timeshare units, or both, and a complete description of the program; and

. Any additional information the director finds necessary to fully inform prospective timeshare purchasers, including but not limited to information required by RCW 64.36.030.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%203[1983 1st ex.s. c 22 § 3]; ]

== 64.36.150 - Disclosure document to prospective purchasers—Cancellation and refund—Voidable agreement.
The promoter or any person offering timeshare interest shall provide a prospective purchaser with a copy of the disclosure document described in RCW 64.36.140 before the execution of any agreement for the purchase of a timeshare. A purchaser may, for seven days following execution of an agreement to purchase a timeshare, cancel the agreement and receive a refund of any consideration paid by providing written notice of the cancellation to the promoter or the promoter's agent either by mail or hand delivery. If the purchaser does not receive the disclosure document, the agreement is voidable by the purchaser until the purchaser receives the document and for seven days thereafter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%2014[1983 1st ex.s. c 22 § 14]; ]

== 64.36.160 - Application of liability provisions.
No provision of this chapter imposing any liability applies to any act or omission in good faith in conformity with any rule, form, or order of the director, notwithstanding that the rule, form, or order may later be amended or rescinded or determined by judicial or other authority to be invalid for any reason.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%2015[1983 1st ex.s. c 22 § 15]; ]

== 64.36.170 - Noncompliance—Unfair practice under chapter  19.86 RCW.
Any failure to comply with this chapter constitutes an unfair and deceptive trade practice under chapter 19.86 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%2016[1983 1st ex.s. c 22 § 16]; ]

== 64.36.185 - Director's powers—Employment of outside persons for advice on project operating budget—Reimbursement by promoter—Notice and hearing.
. If it appears that the operating budget of a project fails to adequately provide for funding of reserve accounts, the director may employ outside professionals or consultants to provide advice or to develop an alternative budget. The promoter shall pay or reimburse the department for the costs incurred for such professional opinions.

. Before employing consultants under this section, the director shall provide the applicant with written notice and an opportunity for a hearing under chapter 34.05 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c370.pdf?cite=1987%20c%20370%20§%206[1987 c 370 § 6]; ]

== 64.36.195 - Assurances of discontinuance—Violation of assurance constitutes unprofessional conduct.
The director or persons to whom the director delegates such powers may enter into assurances of discontinuance in lieu of issuing a statement of charges or a cease and desist order or conducting a hearing under this chapter. The assurances shall consist of a statement of the law in question and an agreement to not violate the stated provision. The applicant or registrant shall not be required to admit to any violation of the law, nor shall the assurance be construed as such an admission. Violation or breaching of an assurance under this section shall constitute unprofessional conduct for which disciplinary action may be taken under RCW 18.235.110 and 18.235.130.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20300[2002 c 86 § 300]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c370.pdf?cite=1987%20c%20370%20§%207[1987 c 370 § 7]; ]

== 64.36.200 - Cease and desist order—Notification—Hearing.
. The director may order any person to cease and desist from an act or practice if it appears that the person is violating or is about to violate any provision of this chapter or any rule or order issued under this chapter.

. Upon the entry of the temporary order to cease and desist, the director shall promptly notify the recipient of the order that it has been entered and the reasons therefor and that if requested in writing by such person within fifteen days after service of the director's notification, the matter will be scheduled for hearing which shall be held within a reasonable time and in accordance with chapter 34.05 RCW. The temporary order shall remain in effect until ten days after the hearing is held.

. If a person does not request a hearing, the order shall become final.

. Unlicensed timeshare activity is subject to RCW 18.235.150.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20301[2002 c 86 § 301]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%2019[1983 1st ex.s. c 22 § 19]; ]

== 64.36.210 - Unlawful acts—Penalties.
. It is unlawful for any person in connection with the offer, sale, or lease of any timeshare in the state:

.. To make any untrue or misleading statement of a material fact, or to omit a material fact;

.. To employ any device, scheme, or artifice to defraud;

.. To engage in any act, practice, or course of business which operates or would operate as a fraud or deceit upon any person;

.. To file, or cause to be filed, with the director any document which contains any untrue or misleading information; or

.. To violate any rule or order of the director.

. [Empty]
.. Any person who knowingly violates this section is guilty of a class C felony punishable according to chapter 9A.20 RCW.

.. No indictment or information for a felony may be returned under this chapter more than five years after the alleged violation.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20290[2003 c 53 § 290]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%2020[1983 1st ex.s. c 22 § 20]; ]

== 64.36.220 - Injunction, restraining order, writ of mandamus—Costs and attorney's fees—Penalties—Appointment of receiver or conservator.
. The attorney general, in the name of the state or the director, may bring an action to enjoin any person from violating any provision of this chapter. Upon a proper showing, the superior court shall grant a permanent or temporary injunction, restraining order, or writ of mandamus. The court may make any additional orders or judgments which may be necessary to restore to any person any interest in any money or property, real or personal, which may have been acquired by means of any act prohibited or declared to be unlawful under this chapter. The prevailing party may recover costs of the action, including a reasonable attorney's fee.

. The superior court issuing an injunction shall retain jurisdiction. Any person who violates the terms of an injunction shall pay a civil penalty of not more than twenty-five thousand dollars.

. The attorney general, in the name of the state or the director, may apply to the superior court to appoint a receiver or conservator for any person, or the assets of any person, who is subject to a cease and desist order, permanent or temporary injunction, restraining order, or writ of mandamus.

. Proceedings for injunctions for unlicensed timeshare activity must be conducted under the provisions of RCW 18.235.150.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20302[2002 c 86 § 302]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%2021[1983 1st ex.s. c 22 § 21]; ]

== 64.36.225 - Liability of registrant or applicant for costs of proceedings.
A registrant or applicant against whom an administrative or legal proceeding authorized under this chapter has been filed, shall be liable for and reimburse to the state of Washington by payment into the business and professions account created in RCW 43.24.150, all administrative and legal costs, including attorneys' fees, incurred by the department in issuing and conducting administrative or legal proceedings that result in a final legal or administrative determination of any type or degree, in favor of the department or the state of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1394-S.SL.pdf?cite=2005%20c%2025%20§%204[2005 c 25 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c370.pdf?cite=1987%20c%20370%20§%208[1987 c 370 § 8]; ]

== 64.36.240 - Liability for violation of chapter.
Any person who offers, sells, or materially aids in such offer or sale of a timeshare in violation of this chapter is liable to the person buying the timeshare who may sue either at law or in equity to recover the consideration paid for the timeshare, together with interest at ten percent per annum from date of payment and costs upon the tender of the timeshare, or for damages if the person no longer owns the timeshare.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%2023[1983 1st ex.s. c 22 § 23]; ]

== 64.36.250 - Appointment of director to receive service—Requirements for effective service.
Every applicant for registration under this chapter shall file with the director, in a form the director prescribes by rule, an irrevocable consent appointing the director to be the attorney of the applicant to receive service of any lawful process in any civil suit, action, or proceeding against the applicant or the applicant's successor, executor, or administrator which arises under this chapter or any rule or order issued under this chapter after the consent has been filed, with the same force and validity as if served personally on the person filing the consent. Service may be made by leaving a copy of the process in the office of the director, but it is not effective unless: (1) The plaintiff, who may be the director in a suit, action, or proceeding instituted by the director, forthwith sends notice of the service and a copy of the process by certified mail to the defendant or respondent at the last address of the respondent or defendant on file with the director; and (2) the plaintiff's affidavit of compliance with this section is filed in the case on or before the return day of the process, if any, or within such further time as the court allows.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%2024[1983 1st ex.s. c 22 § 24]; ]

== 64.36.260 - Certain acts not constituting findings or approval by the director—Certain representations unlawful.
Neither the fact that an application for registration nor a disclosure document under RCW 64.36.140 has been filed, nor the fact that a timeshare offering is effectively registered, constitutes a finding by the director that any document filed under this chapter is true, complete, and not misleading, nor does either fact mean that the director has determined in any way the merits of, qualifications of, or recommended or given approval to any person, timeshare, or transaction. It is unlawful to make, or cause to be made, to any prospective purchaser any representation inconsistent with this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%2025[1983 1st ex.s. c 22 § 25]; ]

== 64.36.270 - Rules, forms, and orders—Interpretive opinions.
The director may make, amend, and repeal rules, forms, and orders when necessary to carry out this chapter. The director may honor requests for interpretive opinions.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%2026[1983 1st ex.s. c 22 § 26]; ]

== 64.36.290 - Application of chapters  21.20, 58.19, and  19.105 RCW—Exemption of certain camping and outdoor recreation enterprises.
. All timeshares registered under this chapter are exempt from chapters 21.20, 58.19, and 19.105 RCW.

. This chapter shall not apply to any enterprise that has as its primary purpose camping and outdoor recreation and camping sites designed and promoted for the purpose of purchasers locating a trailer, tent, tent trailer, pickup camper, or other similar device used for land-based portable housing.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c370.pdf?cite=1987%20c%20370%20§%2011[1987 c 370 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%2028[1983 1st ex.s. c 22 § 28]; ]

== 64.36.310 - Copy of advertisement to be filed with director before publication—Application of chapter limited.
. No person may publish any advertisement in this state offering a timeshare which is subject to the registration requirements of RCW 64.36.020 unless a true copy of the advertisement has been filed in the office of the director at least seven days before publication or a shorter period which the director by rule may establish. The right to subsequently publish the advertisement is subject to the approval of the director within that seven day period.

. Nothing in this chapter applies to any radio or television station or any publisher, printer, or distributor of any newspaper, magazine, billboard, or other advertising medium which accepts advertising in good faith without knowledge of its violation of any provision of this chapter. This subsection does not apply, however, to any publication devoted primarily to the soliciting of resale timeshare offerings and where the publisher or owner of the publication collects advance fees for the purpose of locating or finding potential resale buyers or sellers.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c370.pdf?cite=1987%20c%20370%20§%2012[1987 c 370 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%2031[1983 1st ex.s. c 22 § 31]; ]

== 64.36.320 - Free gifts, awards, and prizes—Security arrangement required of promisor—Other requirements—Private causes of action.
. No person, including a promoter, may advertise, sell, contract for, solicit, arrange, or promise a free gift, an award, a prize, or other item of value in this state as a condition for attending a sales presentation, touring a facility, or performing other activities in connection with the offer or sale of a timeshare under this chapter, without first providing the director with a bond, letter of credit, cash depository, or other security arrangement that will assure performance by the promisor and delivery of the promised gift, award, sweepstakes, prize, or other item of value.

. Promoters under this chapter shall be strictly liable for delivering promised gifts, prizes, awards, or other items of value offered or advertised in connection with the marketing of timeshares.

. Persons promised but not receiving gifts, prizes, awards, or other items of consideration covered under this section, shall be entitled in any cause of action in the courts of this state in which their causes prevail, to be awarded treble the stated value of the gifts, prizes, or awards, court costs, and reasonable attorney fees.

. The director may require that any fees or funds of any description collected from persons in advance, in connection with delivery by the promisor of gifts, prizes, awards, or other items of value covered under this section, be placed in a depository in this state, where they shall remain until performance by the promisor.

. The director may require commercial promotional programs to be registered and require the provision of whatever information, including financial information, the department deems necessary for protection of purchasers.

. Persons offering commercial promotional programs shall sign and present to the department a consent to service of process, in the manner required of promoters in this chapter.

. Registrants or their agents or other persons shall not take possession of promotional materials covered under this section and RCW 64.36.310, from recipients who have received the materials for attending a sales presentation or touring a project, unless the permission of the recipient is received and the recipient is provided with an accurate signed copy describing such promotional materials. The department shall adopt rules enforcing this subsection.

. Chapter 19.170 RCW applies to free gifts, awards, prizes, or other items of value regulated under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5108-S.SL.pdf?cite=1991%20c%20227%20§%2010[1991 c 227 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c370.pdf?cite=1987%20c%20370%20§%2013[1987 c 370 § 13]; ]

== 64.36.330 - Membership lists available for members and owners—Conditions—Exclusion of members' names from list—Commercial use of list.
. Concerning any timeshare offered or sited in this state, it is unlawful and a violation of this chapter and chapter 19.86 RCW for any person, developer, promoter, operator, or other person in control of timeshares or the board of directors or appropriate officer of timeshares with such responsibilities, to fail to provide a member/owner of a timeshare with a membership list, including names, addresses, and lot, unit, or interval owned, under the following circumstances:

.. Upon demand or by rule or order of the director of the department, for whatever purpose deemed necessary to administer this chapter;

.. Upon written request sent by certified mail being made by a member of the timeshare, to a declarant, promoter, or other person who has established and is yet in control of the timeshare;

.. Upon written request sent by certified mail of a member of a timeshare to the board of directors or appropriate officer of the timeshare or an affiliated timeshare.

. The board of directors of the timeshare may require that any applicant for a membership list, other than the department, pay reasonable costs for providing the list and an affidavit that the applicant will not use and will be responsible for any use of the list for commercial purposes.

. Upon request, a member's name shall be excluded from a membership list available to any person other than the director of licensing for purposes of administering statutes that are its responsibility. Such persons shall make their request for exclusion in writing by certified mail to the board of directors or the appropriate officer or director of the timeshare.

. It is unlawful for any person to use a membership list obtained under this section or otherwise, for commercial purposes, unless written permission to do so has been received from the board of directors or appropriate officer of the timeshare. Wilful use of a membership list for commercial purposes without such permission shall subject the violator to damages, costs, and reasonable attorneys' fees in any legal proceedings instituted by a member in which the member prevails alleging violation of this section. Members may petition the courts of this state for orders restraining such commercial use.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c370.pdf?cite=1987%20c%20370%20§%2014[1987 c 370 § 14]; ]

== 64.36.340 - Uniform regulation of business and professions act.
The uniform regulation of business and professions act, chapter 18.235 RCW, governs unlicensed practice, the issuance and denial of licenses, and the discipline of licensees under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20304[2002 c 86 § 304]; ]

== 64.36.350 - Military training or experience.
An applicant with military training or experience satisfies the training or experience requirements of this chapter unless the director determines that the military training or experience is not substantially equivalent to the standards of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1418.SL.pdf?cite=2011%20c%20351%20§%2020[2011 c 351 § 20]; ]

== 64.36.351 - Spouses of military personnel—Registration.
The director shall develop rules consistent with RCW 18.340.020 for the registration of spouses of military personnel.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5969-S.SL.pdf?cite=2011%202nd%20sp.s.%20c%205%20§%209[2011 2nd sp.s. c 5 § 9]; ]

== 64.36.900 - Short title.
This chapter may be known and cited as "The Timeshare Act."

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c22.pdf?cite=1983%201st%20ex.s.%20c%2022%20§%2032[1983 1st ex.s. c 22 § 32]; ]

