= 64.80 - Uniform real property transfer on death act.
:toc:

== 64.80.010 - Definitions.
The following definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Beneficiary" means a person that receives property under a transfer on death deed.

. "Designated beneficiary" means a person designated to receive property in a transfer on death deed.

. "Joint owner" means an individual who owns property concurrently with one or more other individuals with a right of survivorship. The term includes a joint tenant with a right to survivorship. The term does not include a tenant in common or owner of community property.

. "Person" means an individual, corporation, business trust, estate, trust, partnership, limited liability company, association, joint venture, public corporation, government or governmental subdivision, agency, or instrumentality, or any other legal or commercial entity.

. "Property" means an interest in real property located in this state which is transferable on the death of the owner.

. "Transfer on death deed" means a deed authorized under this chapter.

. "Transferor" means an individual who makes a transfer on death deed.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1117-S.SL.pdf?cite=2014%20c%2058%20§%202[2014 c 58 § 2]; ]

== 64.80.020 - Authorized—Prohibited use.
An individual may transfer property to one or more beneficiaries effective at the transferor's death by a transfer on death deed. A transfer on death deed may not be used to effect a deed in lieu of foreclosure of a deed of trust.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1117-S.SL.pdf?cite=2014%20c%2058%20§%205[2014 c 58 § 5]; ]

== 64.80.030 - Revocable.
A transfer on death deed is revocable even if the deed or another instrument contains a contrary provision.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1117-S.SL.pdf?cite=2014%20c%2058%20§%206[2014 c 58 § 6]; ]

== 64.80.040 - Nontestamentary.
A transfer on death deed is nontestamentary.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1117-S.SL.pdf?cite=2014%20c%2058%20§%207[2014 c 58 § 7]; ]

== 64.80.050 - Capacity of transferor.
The capacity required to make or revoke a transfer on death deed is the same as the capacity required to make a will.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1117-S.SL.pdf?cite=2014%20c%2058%20§%208[2014 c 58 § 8]; ]

== 64.80.060 - Requirements.
A transfer on death deed:

. Except as otherwise provided in subsection (2) of this section, must contain the essential elements and formalities of a properly recordable inter vivos deed;

. Must state that the transfer to the designated beneficiary is to occur at the transferor's death; and

. Must be recorded before the transferor's death in the public records in the office of the auditor of the county where the property is located.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1117-S.SL.pdf?cite=2014%20c%2058%20§%209[2014 c 58 § 9]; ]

== 64.80.070 - Notice, delivery, acceptance, consideration not required.
A transfer on death deed is effective without:

. Notice or delivery to or acceptance by the designated beneficiary during the transferor's life; or

. Consideration.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1117-S.SL.pdf?cite=2014%20c%2058%20§%2010[2014 c 58 § 10]; ]

== 64.80.080 - Revocation, when authorized or prohibited.
. Subject to subsection (2) of this section, an instrument is effective to revoke a recorded transfer on death deed, or any part of it, only if the instrument:

.. Is one of the following:

... A transfer on death deed that revokes the deed or part of the deed expressly or by inconsistency;

... An instrument of revocation that expressly revokes the deed or part of the deed; or

... An inter vivos deed that expressly revokes the transfer on death deed or part of the deed; and

.. Is acknowledged by the transferor after the acknowledgment of the deed being revoked and recorded before the transferor's death in the public records in the office of the county auditor of the county where the deed is recorded.

. If a transfer on death deed is made by more than one transferor:

.. Revocation by a transferor does not affect the deed as to the interest of another transferor;

.. A deed of joint owners is revoked only if it is revoked by all of the joint owners living at the time that the revocation is recorded; and

.. A deed of community property by both spouses or by both domestic partners is revoked only if it is revoked by both of the spouses or domestic partners, provided that if only one of the spouses or domestic partners is then surviving, that spouse or domestic partner may revoke the deed.

. After a transfer on death deed is recorded, it may not be revoked by a revocatory act on the deed.

. This section does not limit the effect of an inter vivos transfer of the property.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1117-S.SL.pdf?cite=2014%20c%2058%20§%2011[2014 c 58 § 11]; ]

== 64.80.090 - Effect during transferor's life.
During a transferor's life, a transfer on death deed does not:

. Affect an interest or right of the transferor or any other owner, including the right to transfer or encumber the property;

. Affect an interest or right of a transferee, even if the transferee has actual or constructive notice of the deed;

. Affect an interest or right of a secured or unsecured creditor or future creditor of the transferor, even if the creditor has actual or constructive notice of the deed;

. Affect the transferor's or designated beneficiary's eligibility for any form of public assistance;

. Create a legal or equitable interest in favor of the designated beneficiary; or

. Subject the property to claims or process of a creditor of the designated beneficiary.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1117-S.SL.pdf?cite=2014%20c%2058%20§%2012[2014 c 58 § 12]; ]

== 64.80.100 - Effect at transferor's death.
. Except as otherwise provided in this section, or in RCW 11.07.010, and 11.05A.030, on the death of the transferor, the following rules apply to property that is the subject of a transfer on death deed and owned by the transferor at death:

.. Subject to (b) of this subsection, the interest in the property is transferred to the designated beneficiary in accordance with the deed.

.. The interest of a designated beneficiary is contingent on the designated beneficiary surviving the transferor. The interest of a designated beneficiary that fails to survive the transferor lapses.

.. Subject to (d) of this subsection, concurrent interests are transferred to the beneficiaries in equal and undivided shares with no right of survivorship.

.. If the transferor has identified two or more designated beneficiaries to receive concurrent interests in the property, the share of one which lapses or fails for any reason is transferred to the other, or to the others in proportion to the interest of each in the remaining part of the property held concurrently.

. Subject to chapter 65.08 RCW, a beneficiary takes the property subject to all conveyances, encumbrances, assignments, contracts, mortgages, liens, and other interests to which the property is subject at the transferor's death, including liens recorded within twenty-four months after the transferor's death under RCW 41.05A.090 and 43.20B.080. For purposes of this subsection and chapter 65.08 RCW, the recording of the transfer on death deed is deemed to have occurred at the transferor's death.

. If a transferor is a joint owner and is:

.. Survived by one or more other joint owners, the property that is the subject of a transfer on death deed belongs to the surviving joint owner or owners with right of survivorship; or

.. The last surviving joint owner, the transfer on death deed is effective.

. If the property that is the subject of a transfer on death deed is community property and:

.. The transferor is married and is not joined in the deed by the transferor's spouse or is in a registered domestic partnership and is not joined in the deed by the transferor's domestic partner, the transferor's interest in the property is transferred to the designated beneficiary in accordance with the deed on the transferor's death; or

.. The transferor is married and is joined in the deed by the transferor's spouse, or is in a registered domestic partnership and is joined in the deed by the transferor's domestic partner, and:

... Is survived by the transferor's spouse or domestic partner, the deed is not effective upon the transferor's death; or

... Is the surviving spouse or domestic partner, the transfer on death deed is effective on the transferor's death with respect to the transferor's interest in the property as of the time of the transferor's death.

. A transfer on death deed transfers property without covenant or warranty of title even if the deed contains a contrary provision.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1117-S.SL.pdf?cite=2014%20c%2058%20§%2013[2014 c 58 § 13]; ]

== 64.80.110 - Disclaimer of interest.
A beneficiary may disclaim all or part of the beneficiary's interest as provided by chapter 11.86 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1117-S.SL.pdf?cite=2014%20c%2058%20§%2014[2014 c 58 § 14]; ]

== 64.80.120 - Liability for creditor claims and statutory allowances.
A beneficiary of a transfer on death deed is liable for an allowed claim against the transferor's probate estate and statutory allowances to a surviving spouse and children to the extent provided in RCW 11.18.200, 11.42.085, and chapter 11.54 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1117-S.SL.pdf?cite=2014%20c%2058%20§%2015[2014 c 58 § 15]; ]

== 64.80.900 - Short title.
This chapter may be cited as the Washington uniform real property transfer on death act.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1117-S.SL.pdf?cite=2014%20c%2058%20§%201[2014 c 58 § 1]; ]

== 64.80.901 - Application.
This chapter applies to a transfer on death deed made before, on, or after June 12, 2014, by a transferor dying on or after June 12, 2014.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1117-S.SL.pdf?cite=2014%20c%2058%20§%203[2014 c 58 § 3]; ]

== 64.80.902 - Nonexclusivity.
The chapter does not affect any method of transferring property otherwise permitted under the law of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1117-S.SL.pdf?cite=2014%20c%2058%20§%204[2014 c 58 § 4]; ]

== 64.80.903 - Uniformity of application and construction—2014 c 58.
In applying and construing this uniform act, consideration must be given to the need to promote uniformity of the law with respect to its subject matter among the states that enact it.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1117-S.SL.pdf?cite=2014%20c%2058%20§%2016[2014 c 58 § 16]; ]

== 64.80.904 - Relation to electronic signatures in global and national commerce act—2014 c 58.
Chapter 58, Laws of 2014 modifies, limits, and supersedes the federal electronic signatures in global and national commerce act, 15 U.S.C. Sec. 7001, et seq., but does not modify, limit, or supersede section 101(c) of that act, 15 U.S.C. Sec. 7001(c), or authorize electronic delivery of any of the notices described in section 103(b) of that act, 15 U.S.C. Sec. 7003(b).

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1117-S.SL.pdf?cite=2014%20c%2058%20§%2017[2014 c 58 § 17]; ]

