= 67.04 - Baseball.
:toc:

== 67.04.010 - Penalty for bribery in relation to baseball game.
Any person who shall bribe or offer to bribe, any baseball player with intent to influence his or her play, action, or conduct in any baseball game, or any person who shall bribe or offer to bribe any umpire of a baseball game, with intent to influence him or her to make a wrong decision or to bias his or her opinion or judgment in relation to any baseball game or any play occurring therein, or any person who shall bribe or offer to bribe any manager, or other official of a baseball club, league, or association, by whatsoever name called, conducting said game of baseball to throw or lose a game of baseball, shall be guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20294[2012 c 117 § 294]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c181.pdf?cite=1921%20c%20181%20§%201[1921 c 181 § 1]; RRS § 2321-1; ]

== 67.04.020 - Penalty for acceptance of bribe.
Any baseball player who shall accept or agree to accept, a bribe offered for the purpose of wrongfully influencing his or her play, action, or conduct in any baseball game, or any umpire of a baseball game who shall accept or agree to accept a bribe offered for the purpose of influencing him or her to make a wrong decision, or biasing his or her opinions, rulings or judgment with regard to any play, or any manager of a baseball club, or club or league official, who shall accept, or agree to accept, any bribe offered for the purpose of inducing him or her to lose or cause to be lost any baseball game, as set forth in RCW 67.04.010, shall be guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20295[2012 c 117 § 295]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c181.pdf?cite=1921%20c%20181%20§%202[1921 c 181 § 2]; RRS § 2321-2; ]

== 67.04.030 - Elements of offense outlined.
To complete the offenses mentioned in RCW 67.04.010 and 67.04.020, it shall not be necessary that the baseball player, manager, umpire, or official, shall, at the time, have been actually employed, selected, or appointed to perform his or her respective duties; it shall be sufficient if the bribe be offered, accepted, or agreed to with the view of probable employment, selection, or appointment of the person to whom the bribe is offered, or by whom it is accepted. Neither shall it be necessary that such baseball player, umpire, or manager actually play or participate in a game or games concerning which said bribe is offered or accepted; it shall be sufficient if the bribe be given, offered, or accepted in view of his or her possibly participating therein.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20296[2012 c 117 § 296]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c181.pdf?cite=1921%20c%20181%20§%203[1921 c 181 § 3]; RRS § 2321-3; ]

== 67.04.040 - "Bribe" defined.
By a "bribe" as used in RCW 67.04.010 through 67.04.080, is meant any gift, emolument, money or thing of value, testimonial, privilege, appointment, or personal advantage, or the promise of either, bestowed or promised for the purpose of influencing, directly or indirectly, any baseball player, manager, umpire, club or league official, to see which game an admission fee may be charged, or in which game of baseball any player, manager, or umpire is paid any compensation for his or her services. Said bribe as defined in RCW 67.04.010 through 67.04.080 need not be direct; it may be such as is hidden under the semblance of a sale, bet, wager, payment of a debt, or in any other manner designed to cover the true intention of the parties.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20297[2012 c 117 § 297]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c181.pdf?cite=1921%20c%20181%20§%204[1921 c 181 § 4]; RRS § 2321-4; ]

== 67.04.050 - Corrupt baseball playing—Penalty.
Any baseball player, manager, or club or league official who shall commit any willful act of omission or commission in playing, or directing the playing, of a baseball game, with intent to cause the ball club, with which he or she is affiliated, to lose a baseball game; or any umpire officiating in a baseball game, or any club or league official who shall commit any willful act connected with his or her official duties for the purpose and with the intent to cause a baseball club to win or lose a baseball game, which it would not otherwise have won or lost under the rules governing the playing of said game, shall be guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20298[2012 c 117 § 298]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c181.pdf?cite=1921%20c%20181%20§%205[1921 c 181 § 5]; RRS § 2321-5; ]

== 67.04.060 - Venue of action.
In all prosecutions under RCW 67.04.010 through 67.04.080 the venue may be laid in any county where the bribe herein referred to was given, offered or accepted, or in which the baseball game was played in relation to which the bribe was offered, given or accepted, or the acts referred to in RCW 67.04.050 committed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c181.pdf?cite=1921%20c%20181%20§%206[1921 c 181 § 6]; RRS § 2321-6; ]

== 67.04.070 - Bonus or extra compensation.
Nothing in RCW 67.04.010 through 67.04.080 shall be construed to prohibit the giving or offering of any bonus or extra compensation to any manager or baseball player by any person to encourage such manager or player to a higher degree of skill, ability, or diligence in the performance of his or her duties.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20299[2012 c 117 § 299]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c181.pdf?cite=1921%20c%20181%20§%207[1921 c 181 § 7]; RRS § 2321-7; ]

== 67.04.080 - Scope of provisions as to bribes.
RCW 67.04.010 through 67.04.080 shall apply only to baseball league and club officials, umpires, managers and players who act in such capacity in games where the public is generally invited to attend and a general admission fee is charged.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c181.pdf?cite=1921%20c%20181%20§%208[1921 c 181 § 8]; RRS § 2321-8; ]

== 67.04.090 - Baseball contracts with minors—Definitions.
As used in RCW 67.04.090 through 67.04.150 the following terms shall have the following meanings:

. "Agent" shall, in addition to its generally accepted legal meaning, mean and include those persons commonly known as "baseball scouts";

. "Contract" shall mean any contract, agreement, bonus, or gratuity arrangement, whether oral or written;

. "Minor" shall mean any person under the age of eighteen years, and who has not graduated from high school: PROVIDED, That should he or she become eighteen during his or her senior year he or she shall be a minor until the end of the school year;

. "Organized professional baseball" shall mean and include all persons, firms, corporations, associations, or teams or clubs, or agents thereof, engaged in professional baseball, or in promoting the interest of professional baseball, or sponsoring or managing other persons, firms, corporations, associations, teams, or clubs who play baseball in any of the major or minor professional baseball leagues, or any such league hereafter organized;

. "Parent" shall mean parent, parents, or guardian;

. "Prosecuting attorney" shall mean the prosecuting attorney, or his or her regular deputy, of the county in which the minor's parent is domiciled.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20300[2012 c 117 § 300]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c78.pdf?cite=1951%20c%2078%20§%202[1951 c 78 § 2]; ]

== 67.04.100 - Contract with minor void unless approved.
Any contract between organized professional baseball and a minor shall be null and void and contrary to the public policy of the state, unless and until such contract be approved as hereinafter provided.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c78.pdf?cite=1951%20c%2078%20§%203[1951 c 78 § 3]; ]

== 67.04.110 - Contract with minor—Approval by prosecuting attorney.
No contract within RCW 67.04.090 through 67.04.150 shall be null and void, nor shall any of the prohibitions or penalties provided in RCW 67.04.090 through 67.04.150 be applicable if such contract be first approved in writing by the prosecuting attorney. Such approval may be sought jointly, or at the request of either party seeking a contract.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c78.pdf?cite=1951%20c%2078%20§%204[1951 c 78 § 4]; ]

== 67.04.120 - Contract with minor—Basis of approval.
The prosecuting attorney shall have the authority to examine all the parties to the proposed contract and any other interested person and shall approve such contract if the following facts and circumstances are found to exist:

. That the minor has not been signed, approached, or contacted, directly or indirectly, pertaining to a professional baseball contract except as herein permitted by approval of the prosecuting attorney;

. That the minor has been apprised of the fact that approval of the contract may deprive him or her of his or her amateur status;

. That the parent of the minor and the minor have consented to the contract;

. That the prosecuting attorney has concluded that the contract conforms to the provisions of RCW 67.04.090 through 67.04.150, and is a valid and binding contract;

. That the contract permits the minor to have at least five months available each year to continue his or her high school education.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20301[2012 c 117 § 301]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c78.pdf?cite=1951%20c%2078%20§%205[1951 c 78 § 5]; ]

== 67.04.130 - Contract with minor—Effect of disapproval.
Should the prosecuting attorney not approve the contract as above provided, then such contract shall be void, and the status of the minor shall remain as if no contract had been made, unless the prosecuting attorney's determination be the result of arbitrary or capricious action.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c78.pdf?cite=1951%20c%2078%20§%206[1951 c 78 § 6]; ]

== 67.04.140 - Negotiations with minor prohibited.
No representative of organized professional baseball nor agent, nor person purporting to be able to represent any institution in organized baseball, whether so authorized to represent such institution or not, shall initiate or participate in any negotiations which would induce an evasion of this law in any way, including the removal of any minor to another state, or violate the minor's high school athletic eligibility.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c78.pdf?cite=1951%20c%2078%20§%207[1951 c 78 § 7]; ]

== 67.04.150 - Contract with minor—Penalty for violation.
Any person, firm, corporation, association, or agent thereof, who enters into a contract with a minor, or gives a bonus or any gratuity to any minor to secure the minor's promise to enter into a contract in violation of the provisions of RCW 67.04.090 through 67.04.150, or shall otherwise violate any provisions of RCW 67.04.090 through 67.04.150, shall be guilty of a gross misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c78.pdf?cite=1951%20c%2078%20§%208[1951 c 78 § 8]; ]

