= 67.17 - Live horse racing compact.
:toc:

== 67.17.005 - Purpose.
The purposes of the live horse racing compact are to:

. Establish uniform requirements among the party states for the licensing of participants in live horse racing with pari-mutuel wagering, and ensure that all such participants who are licensed pursuant to the compact meet a uniform minimum standard of honesty and integrity;

. Facilitate the growth of the horse racing industry in each party state and nationwide by simplifying the process for licensing participants in live racing, and reduce the duplicative and costly process of separate licensing by the regulatory agency in each state that conducts live horse racing with pari-mutuel wagering;

. Authorize the Washington horse racing commission to participate in the live horse racing compact;

. Provide for participation in the live horse racing compact by officials of the party states, and permit those officials, through the compact committee established by this chapter, to enter into contracts with governmental agencies and nongovernmental persons to carry out the purposes of the live horse racing compact; and

. Establish the compact committee created by this chapter as an interstate governmental entity duly authorized to request and receive criminal history record information from the federal bureau of investigation and other state and local law enforcement agencies.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1027-S.SL.pdf?cite=2001%20c%2018%20§%201[2001 c 18 § 1]; ]

== 67.17.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Compact committee" means the organization of officials from the party states that is authorized and empowered by the live horse racing compact to carry out the purposes of the compact.

. "Official" means the appointed, elected, designated, or otherwise duly selected member of a racing commission or the equivalent thereof in a party state who represents that party state as a member of the compact committee.

. "Participants in live racing" means participants in live horse racing with pari-mutuel wagering in the party states.

. "Party state" means each state that has enacted the live horse racing compact.

. "State" means each of the several states of the United States, the District of Columbia, the Commonwealth of Puerto Rico, and each territory or possession of the United States.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1027-S.SL.pdf?cite=2001%20c%2018%20§%202[2001 c 18 § 2]; ]

== 67.17.020 - Compact effective date.
The live horse racing compact shall come into force when enacted by any four states. Thereafter, the compact shall become effective as to any other state upon: (1) That state's enactment of the compact; and (2) the affirmative vote of a majority of the officials on the compact committee as provided in RCW 67.17.070.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1027-S.SL.pdf?cite=2001%20c%2018%20§%203[2001 c 18 § 3]; ]

== 67.17.030 - Eligibility to enter compact.
Any state that has adopted or authorized horse racing with pari-mutuel wagering is eligible to become party to the live horse racing compact.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1027-S.SL.pdf?cite=2001%20c%2018%20§%204[2001 c 18 § 4]; ]

== 67.17.040 - Withdrawal from compact.
Any party state may withdraw from the live horse racing compact by enacting a statute repealing the compact, but no such withdrawal is effective until the head of the executive branch of the withdrawing state has given notice in writing of such withdrawal to the head of the executive branch of all other party states. If, as a result of withdrawals, participation in the compact decreases to less than three party states, the compact no longer shall be in force and effect unless and until there are at least three or more party states again participating in the compact.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1027-S.SL.pdf?cite=2001%20c%2018%20§%205[2001 c 18 § 5]; ]

== 67.17.050 - Creation of compact committee.
. There is created an interstate governmental entity to be known as the "compact committee" which shall be comprised of one official from the racing commission or its equivalent in each party state who shall be appointed, serve, and be subject to removal in accordance with the laws of the party state he or she represents. Under the laws of his or her party state, each official shall have the assistance of his or her state's racing commission or the equivalent thereof in considering issues related to licensing of participants in live racing and in fulfilling his or her responsibilities as the representative from his or her state to the compact committee. If an official is unable to perform any duty in connection with the powers and duties of the compact committee, the racing commission or equivalent thereof from his or her state shall designate another of its members as an alternate who shall serve in his or her place and represent the party state as its official on the compact committee until that racing commission or equivalent thereof determines that the original representative official is able once again to perform his or her duties as that party state's representative official on the compact committee. The designation of an alternate shall be communicated by the affected state's racing commission or equivalent thereof to the compact committee as the committee's bylaws may provide.

. The horse racing commission shall appoint the official to represent the state of Washington on the compact committee for a term of four years. No official may serve more than three consecutive terms. A vacancy shall be filled by the horse racing commission for the unexpired term.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1371-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2021%20§%2029[2011 1st sp.s. c 21 § 29]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1027-S.SL.pdf?cite=2001%20c%2018%20§%206[2001 c 18 § 6]; ]

== 67.17.060 - Compact committee powers and duties.
In order to carry out the live horse racing compact, the compact committee is granted the power and duty to:

. Determine which categories of participants in live racing, including but not limited to owners, trainers, jockeys, grooms, mutuel clerks, racing officials, veterinarians, and farriers, should be licensed by the compact committee, and establish the requirements for the initial licensure of applicants in each such category, the term of the license for each category, and the requirements for renewal of licenses in each category. However, with regard to requests for criminal history record information on each applicant for a license, and with regard to the effect of a criminal record on the issuance or renewal of a license, the compact committee shall determine for each category of participants in live racing which licensure requirements for that category are, in its judgment, the most restrictive licensure requirements of any party state for that category and shall adopt licensure requirements for that category that are, in its judgment, comparable to those most restrictive requirements;

. Investigate applicants for a license from the compact committee and, as permitted by federal and state law, gather information on such applicants, including criminal history record information from the federal bureau of investigation and relevant state and local law enforcement agencies, and, where appropriate, from the royal Canadian mounted police and law enforcement agencies of other countries, necessary to determine whether a license should be issued under the licensure requirements established by the compact committee under subsection (1) of this section. Only officials on, and employees of, the compact committee may receive and review such criminal history record information, and those officials and employees may use that information only for the purposes of the compact. No such official or employee may disclose or disseminate such information to any person or entity other than another official on or employee of the compact committee. The fingerprints of each applicant for a license from the compact committee shall be taken by the compact committee, its employees, or its designee and shall be forwarded to a state identification bureau, or to an association of state officials regulating pari-mutuel wagering designated by the attorney general of the United States, for submission to the federal bureau of investigation for a criminal history record check. Such fingerprints may be submitted on a fingerprint card or by electronic or other means authorized by the federal bureau of investigation or other receiving law enforcement agency;

. Issue licenses to, and renew the licenses of, participants in live racing listed in subsection (1) of this section who are found by the compact committee to have met the licensure and renewal requirements established by the compact committee. The compact committee shall not have the power or authority to deny a license. If it determines that an applicant will not be eligible for the issuance or renewal of a compact committee license, the compact committee shall notify the applicant that it will not be able to process his or her application further. Such notification does not constitute and shall not be considered to be the denial of a license. Any such applicant has the right to present additional evidence to, and to be heard by, the compact committee, but the final decision on issuance or renewal of the license shall be made by the compact committee using the requirements established under subsection (1) of this section;

. Enter into contracts or agreements with governmental agencies and with nongovernmental persons to provide personal services for its activities and such other services as may be necessary to carry out the compact;

. Create, appoint, and abolish those offices, employments, and positions, including an executive director, as it deems necessary for the purposes of the compact, prescribe their powers, duties, and qualifications, hire persons to fill those offices, employments, and positions, and provide for the removal, term, tenure, compensation, fringe benefits, retirement benefits, and other conditions of employment of its officers, employees, and other positions;

. Borrow, accept, or contract for the services of personnel from any state, the United States, or any other governmental agency, or from any person, firm, association, corporation, or other entity;

. Acquire, hold, and dispose of real and personal property by gift, purchase, lease, license, or in other similar manner, in furtherance of the compact;

. Charge a fee to each applicant for an initial license or renewal of a license; and

. Receive other funds through gifts, grants, and appropriations.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1027-S.SL.pdf?cite=2001%20c%2018%20§%207[2001 c 18 § 7]; ]

== 67.17.070 - Compact committee voting requirements.
. Each official is entitled to one vote on the compact committee.

. All action taken by the compact committee with regard to the addition of party states as provided in RCW 67.17.020, the licensure of participants in live racing, and the receipt and disbursement of funds require a majority vote of the total number of officials, or their alternates, on the compact committee. All other action by the compact committee requires a majority vote of those officials, or their alternates, present and voting.

. No action of the compact committee may be taken unless a quorum is present. A majority of the officials, or their alternates, on the compact committee constitutes a quorum.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1027-S.SL.pdf?cite=2001%20c%2018%20§%208[2001 c 18 § 8]; ]

== 67.17.080 - Compact committee governance.
. The compact committee shall elect annually from among its members a chair, a vice chair, and a secretary/treasurer.

. The compact committee shall adopt bylaws for the conduct of its business by a two-thirds vote of the total number of officials, or their alternates, on the compact committee at that time and shall have the power by the same vote to amend and rescind such bylaws. The compact committee shall publish its bylaws in convenient form and shall file a copy thereof and a copy of any amendments thereto with the secretary of state or equivalent agency of each of the party states.

. The compact committee may delegate the day-to-day management and administration of its duties and responsibilities to an executive director and the executive director's support staff.

. Employees of the compact committee are considered governmental employees.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1027-S.SL.pdf?cite=2001%20c%2018%20§%209[2001 c 18 § 9]; ]

== 67.17.090 - Liability of compact committee employees or officials.
No official of a party state or employee of the compact committee shall be held personally liable for any good faith act or omission that occurs during the performance and within the scope of his or her responsibilities and duties under the live horse racing compact.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1027-S.SL.pdf?cite=2001%20c%2018%20§%2010[2001 c 18 § 10]; ]

== 67.17.100 - Conditions and terms for participating states.
. By enacting the compact, each party state:

.. Agrees: (i) To accept the decisions of the compact committee regarding the issuance of compact committee licenses to participants in live racing under the compact committee's licensure requirements; and (ii) to reimburse or otherwise pay the expenses of its official representative on the compact committee or his or her alternate;

.. Agrees not to treat a notification to an applicant by the compact committee under RCW 67.17.060(3) that the compact committee will not be able to process the application further as the denial of a license, or to penalize such an applicant in any other way based solely on such a decision by the compact committee; and

.. Reserves the right: (i) To charge a fee for the use of a compact committee license in that state; (ii) to apply its own standards in determining whether, on the facts of a particular case, a compact committee license should be suspended or revoked; (iii) to apply its own standards in determining licensure eligibility, under the laws of that party state, for categories of participants in live racing that the compact committee determines not to license and for individual participants in live racing who do not meet the licensure requirements of the compact committee; and (iv) to establish its own licensure standards for the licensure of nonracing employees at horse racetracks and employees at separate satellite wagering facilities. Any party state that suspends or revokes a compact committee license shall, through its racing commission or the equivalent thereof or otherwise, promptly notify the compact committee of that suspension or revocation.

. No party state shall be held liable for the debts or other financial obligations incurred by the compact committee.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1027-S.SL.pdf?cite=2001%20c%2018%20§%2011[2001 c 18 § 11]; ]

== 67.17.110 - Cooperation by governmental entities with compact committee.
All departments, agencies, and officers of the state of Washington and its political subdivisions are authorized to cooperate with the compact committee in furtherance of any of its activities of the live horse racing compact.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1027-S.SL.pdf?cite=2001%20c%2018%20§%2012[2001 c 18 § 12]; ]

== 67.17.120 - Impact on horse racing commission.
Nothing in this chapter shall be construed to diminish or limit the powers and responsibilities of the Washington horse racing commission established in chapter 67.16 RCW or to invalidate any action of the Washington horse racing commission previously taken, including without limitation any regulation issued by the commission.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1027-S.SL.pdf?cite=2001%20c%2018%20§%2013[2001 c 18 § 13]; ]

== 67.17.130 - Construction and severability of language.
This chapter shall be liberally construed so as to effectuate its purposes. The provisions of this chapter are severable, and, if any phrase, clause, sentence, or provision of the compact is declared to be contrary to the Constitution of the United States or of any party state, or the applicability of the live horse racing compact to any government, agency, person, or circumstance is held invalid, the validity of the remainder of the compact and the applicability thereof to any government, agency, person, or circumstance shall not be affected thereby. If all or some portion of the live horse racing compact is held to be contrary to the constitution of any party state, the compact shall remain in full force and effect as to the remaining party states and in full force and effect as to the state affected as to all severable matters.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1027-S.SL.pdf?cite=2001%20c%2018%20§%2014[2001 c 18 § 14]; ]

== 67.17.900 - Short title—2001 c 18.
This act may be known and cited as the live horse racing compact.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1027-S.SL.pdf?cite=2001%20c%2018%20§%2015[2001 c 18 § 15]; ]

