= 67.20 - Parks, bathing beaches, public camps.
:toc:

== 67.20.010 - Authority to acquire and operate certain recreational facilities—Charges—Eminent domain.
Any city in this state acting through its city council, or its board of park commissioners when authorized by charter or ordinance, any separately organized park district acting through its board of park commissioners or other governing officers, any school district acting through its board of school directors, any county acting through its board of county commissioners, any park and recreation service area acting through its governing body, and any town acting through its town council shall have power, acting independently or in conjunction with the United States, the state of Washington, any county, city, park district, school district or town or any number of such public organizations to acquire any land within this state for park, playground, gymnasiums, swimming pools, field houses and other recreational facilities, bathing beach or public camp purposes and roads leading from said parks, playgrounds, gymnasiums, swimming pools, field houses and other recreational facilities, bathing beaches, or public camps to nearby highways by donation, purchase or condemnation, and to build, construct, care for, control, supervise, improve, operate and maintain parks, playgrounds, gymnasiums, swimming pools, field houses and other recreational facilities, bathing beaches, roads and public camps upon any such land, including the power to enact and enforce such police regulations not inconsistent with the constitution and laws of the state of Washington, as are deemed necessary for the government and control of the same. The power of eminent domain herein granted shall not extend to any land outside the territorial limits of the governmental unit or units exercising said power.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c82.pdf?cite=1988%20c%2082%20§%207[1988 c 82 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c97.pdf?cite=1949%20c%2097%20§%201[1949 c 97 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c107.pdf?cite=1921%20c%20107%20§%201[1921 c 107 § 1]; Rem. Supp. 1949 § 9319. FORMER PART OF SECTION:  1949 c 97 § 3; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c107.pdf?cite=1921%20c%20107%20§%203[1921 c 107 § 3]; Rem. Supp. 1949 § 9321 now codified as RCW  67.20.015; ]

== 67.20.015 - Authority to establish and operate public camps—Charges.
Any city, town, county, separately organized park district, or school district shall have power to establish, care for, control, supervise, improve, operate and maintain a public camp, or camps anywhere within the state, and to that end may make, promulgate and enforce any reasonable rules and regulations in reference to such camps and make such charges for the use thereof as may be deemed expedient.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c97.pdf?cite=1949%20c%2097%20§%203[1949 c 97 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c107.pdf?cite=1921%20c%20107%20§%203[1921 c 107 § 3]; Rem. Supp. 1949 § 9321; ]

== 67.20.020 - Contracts for cooperation.
Any city, park district, school district, county or town shall have power to enter into any contract in writing with any organization or organizations referred to in this chapter for the purpose of conducting a recreation program or exercising any other power granted by this chapter. In the conduct of such recreation program property or facilities owned by any individual, group or organization, whether public or private, may be utilized by consent of the owner.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c97.pdf?cite=1949%20c%2097%20§%202[1949 c 97 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c107.pdf?cite=1921%20c%20107%20§%202[1921 c 107 § 2]; Rem. Supp. 1949 § 9320; ]

== 67.20.030 - Scope of chapter.
This chapter shall not be construed to repeal or limit any existing power of any city or park district, but to grant powers in addition thereto.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1949c97.pdf?cite=1949%20c%2097%20§%204[1949 c 97 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c107.pdf?cite=1921%20c%20107%20§%204[1921 c 107 § 4]; Rem. Supp. 1949 § 9319 note; ]

