= 67.30 - Multipurpose sports stadia.
:toc:

== 67.30.010 - Declaration of public purpose and necessity.
The participation of counties and cities in multipurpose sports stadia which may be used for football, baseball, soccer, conventions, home shows or any and all similar activities; the purchase, lease, condemnation, or other acquisition of necessary real property therefor; the acquisition by condemnation or otherwise, lease, construction, improvement, maintenance, and equipping of buildings or other structures upon such real property or other real property; the operation and maintenance necessary for such participation, and the exercise of any other powers herein granted to counties and cities, are hereby declared to be public, governmental, and municipal functions, exercised for a public purpose, and matters of public necessity, and such real property and other property acquired, constructed, improved, maintained, equipped, and used by counties and cities in the manner and for the purposes enumerated in this chapter shall and are hereby declared to be acquired, constructed, improved, maintained, equipped and used for public, governmental, and municipal purposes and as a matter of public necessity.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c166.pdf?cite=1967%20c%20166%20§%202[1967 c 166 § 2]; ]

== 67.30.020 - Participation by cities and counties—Powers—Costs, how paid.
The counties and cities are authorized, upon passage of an ordinance in the prescribed manner, to participate in the financing, construction, acquisition, operation, and maintenance of multipurpose sports stadia within their boundaries. Counties and cities are also authorized, through their governing authorities, to purchase, lease, condemn, or otherwise acquire property, real or personal; to construct, improve, maintain and equip buildings or other structures; and expend moneys for investigations, planning, operations, and maintenance necessary for such participation.

The cost of any such acquisition, condemnation, construction, improvement, maintenance, equipping, investigations, planning, operation, or maintenance necessary for such participation may be paid for by appropriation of moneys available therefor, gifts, or wholly or partly from the proceeds of revenue bonds as the governing authority may determine.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c166.pdf?cite=1967%20c%20166%20§%203[1967 c 166 § 3]; ]

== 67.30.030 - Issuance of revenue bonds—Limitations—Retirement.
Any revenue bonds to be issued by any county or city pursuant to the provisions of this chapter, shall be authorized and issued in the manner prescribed by the laws of this state for the issuance and authorization of bonds thereof for public purposes generally: PROVIDED, That the bonds shall not be issued for a period beyond the life of the improvement to be acquired by the use of the bonds.

The bonding authority authorized for the purposes of this chapter shall be limited to the issuance of revenue bonds payable from a special fund or funds created solely from revenues derived from the facility. The owners and holders of such bonds shall have a lien and charge against the gross revenue of the facility. Such revenue bonds and the interest thereon against such fund or funds shall be a valid claim of the holders thereof only as against such fund or funds and the revenue pledged therefor, and shall not constitute a general indebtedness of the municipality. The governing authority of any county or city may by ordinance take such action as may be necessary and incidental to the issuance of such bonds and the retirement thereof. The provisions of chapter 36.67 RCW not inconsistent with this chapter shall apply to the issuance and retirement of any such revenue bonds.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c166.pdf?cite=1967%20c%20166%20§%204[1967 c 166 § 4]; ]

== 67.30.040 - Power to appropriate and raise moneys.
The governing body having power to appropriate moneys within any county or city for the purpose of purchasing, condemning, leasing or otherwise acquiring property, constructing, improving, maintaining, and equipping buildings or other structures, and the investigations, planning, operation or maintenance necessary to participation in any such all-purpose or multipurpose sports stadium, is hereby authorized to appropriate and cause to be raised by taxation or otherwise moneys sufficient to carry out such purpose.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c166.pdf?cite=1967%20c%20166%20§%205[1967 c 166 § 5]; ]

== 67.30.050 - Powers additional and supplemental to other laws.
The powers and authority conferred upon counties and cities under the provisions of this chapter, shall be construed as in addition and supplemental to powers or authority conferred by any other law, and nothing contained herein shall be construed as limiting any other such powers or authority.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c166.pdf?cite=1967%20c%20166%20§%206[1967 c 166 § 6]; ]

