= 67.42 - Amusement rides.
:toc:

== 67.42.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Amusement structure" means electrical or mechanical devices or combinations of devices operated for revenue and to provide amusement or entertainment to viewers or audiences at carnivals, fairs, or amusement parks. "Amusement structure" also means a bungee jumping device regardless of where located. "Amusement structure" does not include games in which a member of the public must perform an act, nor concessions at which customers may make purchases.

. "Amusement ride" means any vehicle, boat, bungee jumping device, or other mechanical device moving upon or within a structure, along cables or rails, through the air by centrifugal force or otherwise, or across water, that is used to convey one or more individuals for amusement, entertainment, diversion, or recreation. "Amusement ride" includes, but is not limited to, devices commonly known as skyrides, ferris wheels, carousels, parachute towers, tunnels of love, bungee jumping devices, and roller coasters. "Amusement ride" does not include: (a) Conveyances for persons in recreational winter sports activities such as ski lifts, ski tows, j-bars, t-bars, and similar devices subject to regulation under *chapter 70.88 RCW; (b) any single-passenger coin-operated ride that is manually, mechanically, or electrically operated and customarily placed in a public location and that does not normally require the supervision or services of an operator; (c) nonmechanized playground equipment, including but not limited to, swings, seesaws, stationary spring-mounted animal features, rider-propelled merry-go-rounds, climbers, slides, trampolines, and physical fitness devices; or (d) water slides.

. "Department" means the department of labor and industries.

. "Insurance policy" means an insurance policy written by an insurer authorized to do business in this state under Title 48 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5145-S.SL.pdf?cite=1993%20c%20203%20§%202[1993 c 203 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c262.pdf?cite=1985%20c%20262%20§%201[1985 c 262 § 1]; ]

== 67.42.020 - Requirements—Operation of amusement ride or structure—Bungee jumping device inspection.
Before operating any amusement ride or structure, the owner or operator shall:

. Obtain a permit pursuant to RCW 67.42.030;

. Have the amusement ride or structure inspected for safety at least once annually by an insurer, a person with whom the insurer has contracted, or a person who meets the qualifications set by the department and obtain from the insurer or person a written certificate that the inspection has been made and that the amusement ride or structure meets the standards for coverage and is covered by the insurer as required by subsection (3) of this section. A bungee jumping device, including, but not limited to, the crane, tower, balloon or bridge, person lift basket, platforms, bungee cords, end attachments, anchors, carabiners or locking devices, harnesses, landing devices, and additional ride operation hardware shall be inspected for safety prior to beginning operation and annually by an insurer, a person with whom the insurer has contracted, or a person authorized by the department to inspect bungee jumping devices. The operator of the bungee jumping device shall obtain a written certificate which states that the required inspection has been made and the bungee jumping device meets the standards for coverage and is covered by the insurer as required by subsection (3) of this section;

. Have and keep in effect an insurance policy in an amount not less than one million dollars per occurrence insuring: (a) The owner or operator; and (b) any municipality or county on whose property the amusement ride or structure stands, or any municipality or county which has contracted with the owner or operator against liability for injury to persons arising out of the use of the amusement ride or structure;

. File with the department the inspection certificate and insurance policy required by this section; and

. File with each sponsor, lessor, landowner, or other person responsible for an amusement structure or ride being offered for use by the public a certificate stating that the insurance required by subsection (3) of this section is in effect.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5145-S.SL.pdf?cite=1993%20c%20203%20§%203[1993 c 203 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c86.pdf?cite=1986%20c%2086%20§%201[1986 c 86 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c262.pdf?cite=1985%20c%20262%20§%202[1985 c 262 § 2]; ]

== 67.42.025 - Inspections and inspectors—Comparable regulation and comparable qualification.
. An amusement ride that has been inspected in any state, territory, or possession of the United States that, in the discretion of the department, has a level of regulation comparable to this chapter, shall be deemed to meet the inspection requirement of this chapter.

. An amusement ride inspector who is authorized to inspect amusement rides in any state, territory, or possession of the United States, who, in the discretion of the department, has a level of qualifications comparable to those required under this chapter, shall be deemed qualified to inspect amusement rides under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c86.pdf?cite=1986%20c%2086%20§%202[1986 c 86 § 2]; ]

== 67.42.030 - Permit—Application—Decal.
. Application for an operating permit to operate an amusement ride or structure shall be made on an annual basis by the owner or operator of the amusement ride or structure. The application shall be made on forms prescribed by the department and shall include the certificate required by RCW 67.42.020(2).

. The department shall issue a decal with each permit. The decal shall be affixed on or adjacent to the control panel of the amusement ride or structure in a location visible to the patrons of the ride or structure.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c262.pdf?cite=1985%20c%20262%20§%203[1985 c 262 § 3]; ]

== 67.42.040 - Permit—Duration—Material modification of ride or structure—Bungee jumping device replacement, movement, purchase.
. Except as provided in subsection (2) of this section or unless a shorter period is specified by the department, permits issued under RCW 67.42.030 are valid for a one-year period.

. If an amusement ride or structure is materially rebuilt or materially modified so as to change the original action of the amusement ride or structure, the amusement ride or structure shall be subject to a new inspection under RCW 67.42.020 and the owner or operator shall apply for a new permit under RCW 67.42.030.

. If an amusement ride or structure for which a permit has been issued pursuant to RCW 67.42.030 is moved and installed in another place but is not materially rebuilt or materially modified so as to change the original action of the amusement ride or structure, no new permit is required prior to the expiration of the permit.

. A bungee jumping device or a part of a device, including, but not limited to, the crane, person lift basket, mobile crane, balloon or balloon basket, anchor or anchor attachment structure, or landing device, that is replaced shall be reinspected by an insurer, a person with whom the insurer has contracted, or by a person authorized by the department to inspect bungee jumping devices, and the owner or operator of the device shall apply for a new permit under RCW 67.42.030.

. A bungee jumping operator shall have any bungee jumping device or structure that is moved and installed in another location reinspected by an insurer, a person with whom the insurer has contracted, or a person authorized by the department to inspect bungee jumping devices before beginning operation.

. Any new operator who purchases an existing bungee jumping device or structure must have the bungee jumping device inspected and permitted as required under RCW 67.42.020 before beginning operation.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5145-S.SL.pdf?cite=1993%20c%20203%20§%204[1993 c 203 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c262.pdf?cite=1985%20c%20262%20§%204[1985 c 262 § 4]; ]

== 67.42.050 - Rules—Orders to cease operation—Administrative proceedings.
. The department shall adopt rules under chapter 34.05 RCW to administer this chapter. Such rules may exempt amusement rides or structures otherwise subject to this chapter if the amusement rides or structures are located on lands owned by [the] United States government or its agencies and are required to comply with federal safety standards at least equal to those under this chapter.

. The department may order in writing the cessation of the operation of an amusement ride or structure for which no valid permit is in effect or for which the owner or operator does not have an insurance policy as required by RCW 67.42.020.

. All proceedings relating to permits or orders to cease operation under this chapter shall be conducted pursuant to chapter 34.05 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c262.pdf?cite=1985%20c%20262%20§%205[1985 c 262 § 5]; ]

== 67.42.060 - Fees.
. The department may charge a reasonable fee not to exceed ten dollars for each permit issued under RCW 67.42.030. All fees collected by the department under this chapter shall be deposited in the state general fund. This subsection does not apply to permits issued under RCW 67.42.030 to operate a bungee jumping device.

. The department may charge a reasonable fee not to exceed one hundred dollars for each permit issued under RCW 67.42.030 to operate a bungee jumping device. Fees collected under this subsection shall be deposited in the state general fund for appropriation for the permitting and inspection of bungee jumping devices under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5145-S.SL.pdf?cite=1993%20c%20203%20§%205[1993 c 203 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c262.pdf?cite=1985%20c%20262%20§%206[1985 c 262 § 6]; ]

== 67.42.070 - Penalty.
Any person who operates an amusement ride or structure without complying with the requirements of this chapter is guilty of a gross misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c262.pdf?cite=1985%20c%20262%20§%207[1985 c 262 § 7]; ]

== 67.42.080 - Counties and municipalities—Supplemental ordinances.
Nothing contained in this chapter prevents a county or municipality from adopting and enforcing ordinances which relate to the operation of amusement rides or structures and supplement the provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c262.pdf?cite=1985%20c%20262%20§%208[1985 c 262 § 8]; ]

== 67.42.090 - Bungee jumping—Permission.
. Bungee jumping from a publicly owned bridge or publicly owned land is allowed only if permission has been granted by the government body that has jurisdiction over the bridge or land.

. Bungee jumping into publicly owned waters is allowed only if permission has been granted by the government body that has jurisdiction over the body of water.

. Bungee jumping from a privately owned bridge is allowed only if permission has been granted by the owner of the bridge.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5145-S.SL.pdf?cite=1993%20c%20203%20§%206[1993 c 203 § 6]; ]

== 67.42.901 - Effective date—1985 c 262.
This act shall take effect on January 1, 1986.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c262.pdf?cite=1985%20c%20262%20§%2011[1985 c 262 § 11]; ]

