= 57.08 - Powers.
:toc:

== 57.08.005 - Powers.
A district shall have the following powers:

. To acquire by purchase or condemnation, or both, all lands, property and property rights, and all water and water rights, both within and without the district, necessary for its purposes. The right of eminent domain shall be exercised in the same manner and by the same procedure as provided for cities and towns, insofar as consistent with this title, except that all assessment or reassessment rolls to be prepared and filed by eminent domain commissioners or commissioners appointed by the court shall be prepared and filed by the district, and the duties devolving upon the city treasurer are imposed upon the county treasurer;

. To lease real or personal property necessary for its purposes for a term of years for which that leased property may reasonably be needed;

. To construct, condemn and purchase, add to, maintain, and supply waterworks to furnish the district and inhabitants thereof and any other persons, both within and without the district, with an ample supply of water for all uses and purposes public and private with full authority to regulate and control the use, content, distribution, and price thereof in such a manner as is not in conflict with general law and may construct, acquire, or own buildings and other necessary district facilities. Where a customer connected to the district's system uses the water on an intermittent or transient basis, a district may charge for providing water service to such a customer, regardless of the amount of water, if any, used by the customer. District waterworks may include facilities which result in combined water supply and electric generation, if the electricity generated thereby is a by-product of the water supply system. That electricity may be used by the district or sold to any entity authorized by law to use or distribute electricity. Electricity is deemed a by-product when the electrical generation is subordinate to the primary purpose of water supply. For such purposes, a district may take, condemn and purchase, acquire, and retain water from any public or navigable lake, river or watercourse, or any underflowing water, and by means of aqueducts or pipeline conduct the same throughout the district and any city or town therein and carry it along and upon public highways, roads, and streets, within and without such district. For the purpose of constructing or laying aqueducts or pipelines, dams, or waterworks or other necessary structures in storing and retaining water or for any other lawful purpose such district may occupy the beds and shores up to the high water mark of any such lake, river, or other watercourse, and may acquire by purchase or condemnation such property or property rights or privileges as may be necessary to protect its water supply from pollution. For the purposes of waterworks which include facilities for the generation of electricity as a by-product, nothing in this section may be construed to authorize a district to condemn electric generating, transmission, or distribution rights or facilities of entities authorized by law to distribute electricity, or to acquire such rights or facilities without the consent of the owner;

. To purchase and take water from any municipal corporation, private person, or entity. A district contiguous to Canada may contract with a Canadian corporation for the purchase of water and for the construction, purchase, maintenance, and supply of waterworks to furnish the district and inhabitants thereof and residents of Canada with an ample supply of water under the terms approved by the board of commissioners;

. To construct, condemn and purchase, add to, maintain, and operate systems of sewers for the purpose of furnishing the district, the inhabitants thereof, and persons outside the district with an adequate system of sewers for all uses and purposes, public and private, including but not limited to on-site sewage disposal facilities, approved septic tanks or approved septic tank systems, on-site sanitary sewerage systems, inspection services and maintenance services for private and public on-site systems, point and nonpoint water pollution monitoring programs that are directly related to the sewerage facilities and programs operated by a district, other facilities, programs, and systems for the collection, interception, treatment, and disposal of wastewater, and for the control of pollution from wastewater with full authority to regulate the use and operation thereof and the service rates to be charged. Under this chapter, after July 1, 1998, any requirements for pumping the septic tank of an on-site sewage system should be based, among other things, on actual measurement of accumulation of sludge and scum by a trained inspector, trained owner's agent, or trained owner. Training must occur in a program approved by the state board of health or by a local health officer. Sewage facilities may include facilities which result in combined sewage disposal or treatment and electric or methane gas generation, except that the electricity or methane gas generated thereby is a by-product of the system of sewers. Such electricity or methane gas may be used by the district or sold to any entity authorized by law to distribute electricity or methane gas. Electricity and methane gas are deemed by-products when the electrical or methane gas generation is subordinate to the primary purpose of sewage disposal or treatment. The district may also sell surplus methane gas, which may be produced as a by-product. For such purposes a district may conduct sewage throughout the district and throughout other political subdivisions within the district, and construct and lay sewer pipe along and upon public highways, roads, and streets, within and without the district, and condemn and purchase or acquire land and rights-of-way necessary for such sewer pipe. A district may erect sewage treatment plants within or without the district, and may acquire, by purchase or condemnation, properties or privileges necessary to be had to protect any lakes, rivers, or watercourses and also other areas of land from pollution from its sewers or its sewage treatment plant. For the purposes of sewage facilities which include facilities that result in combined sewage disposal or treatment and electric generation where the electric generation is a by-product, nothing in this section may be construed to authorize a district to condemn electric generating, transmission, or distribution rights or facilities of entities authorized by law to distribute electricity, or to acquire such rights or facilities without the consent of the owners;

. The authority to construct, condemn and purchase, add to, maintain, and operate systems of reclaimed water as authorized by chapter 90.46 RCW for the purpose of furnishing the district and the inhabitants thereof with reclaimed water for all authorized uses and purposes, public and private, including with full authority to regulate the use and operation thereof and the service rates to be charged. In compliance with other sections of this chapter, a district may also provide reclaimed water services to persons outside the district;

. [Empty]
.. To construct, condemn and purchase, add to, maintain, and operate systems of drainage for the benefit and use of the district, the inhabitants thereof, and persons outside the district with an adequate system of drainage, including but not limited to facilities and systems for the collection, interception, treatment, and disposal of storm or surface waters, and for the protection, preservation, and rehabilitation of surface and underground waters, and drainage facilities for public highways, streets, and roads, with full authority to regulate the use and operation thereof and, except as provided in (b) of this subsection, the service rates to be charged.

.. The rate a district may charge under this section for storm or surface water sewer systems or the portion of the rate allocable to the storm or surface water sewer system of combined sanitary sewage and storm or surface water sewer systems shall be reduced by a minimum of ten percent for any new or remodeled commercial building that utilizes a permissive rainwater harvesting system. Rainwater harvesting systems shall be properly sized to utilize the available roof surface of the building. The jurisdiction shall consider rate reductions in excess of ten percent dependent upon the amount of rainwater harvested.

.. Drainage facilities may include natural systems. Drainage facilities may include facilities which result in combined drainage facilities and electric generation, except that the electricity generated thereby is a by-product of the drainage system. Such electricity may be used by the district or sold to any entity authorized by law to distribute electricity. Electricity is deemed a by-product when the electrical generation is subordinate to the primary purpose of drainage collection, disposal, and treatment. For such purposes, a district may conduct storm or surface water throughout the district and throughout other political subdivisions within the district, construct and lay drainage pipe and culverts along and upon public highways, roads, and streets, within and without the district, and condemn and purchase or acquire land and rights-of-way necessary for such drainage systems. A district may provide or erect facilities and improvements for the treatment and disposal of storm or surface water within or without the district, and may acquire, by purchase or condemnation, properties or privileges necessary to be had to protect any lakes, rivers, or watercourses and also other areas of land from pollution from storm or surface waters. For the purposes of drainage facilities which include facilities that also generate electricity as a by-product, nothing in this section may be construed to authorize a district to condemn electric generating, transmission, or distribution rights or facilities of entities authorized by law to distribute electricity, or to acquire such rights or facilities without the consent of the owners;

. To construct, condemn, acquire, and own buildings and other necessary district facilities;

. To compel all property owners within the district located within an area served by the district's system of sewers to connect their private drain and sewer systems with the district's system under such penalty as the commissioners shall prescribe by resolution. The district may for such purpose enter upon private property and connect the private drains or sewers with the district system and the cost thereof shall be charged against the property owner and shall be a lien upon property served;

. Where a district contains within its borders, abuts, or is located adjacent to any lake, stream, groundwater as defined by RCW 90.44.035, or other waterway within the state of Washington, to provide for the reduction, minimization, or elimination of pollutants from those waters in accordance with the district's comprehensive plan, and to issue general obligation bonds, revenue bonds, local improvement district bonds, or utility local improvement bonds for the purpose of paying all or any part of the cost of reducing, minimizing, or eliminating the pollutants from these waters;

. Subject to subsection (7) of this section, to fix rates and charges for water, sewer, reclaimed water, and drain service supplied and to charge property owners seeking to connect to the district's systems, as a condition to granting the right to so connect, in addition to the cost of the connection, such reasonable connection charge as the board of commissioners shall determine to be proper in order that those property owners shall bear their equitable share of the cost of the system. For the purposes of calculating a connection charge, the board of commissioners shall determine the pro rata share of the cost of existing facilities and facilities planned for construction within the next ten years and contained in an adopted comprehensive plan and other costs borne by the district which are directly attributable to the improvements required by property owners seeking to connect to the system. The cost of existing facilities shall not include those portions of the system which have been donated or which have been paid for by grants. The connection charge may include interest charges applied from the date of construction of the system until the connection, or for a period not to exceed ten years, whichever is shorter, at a rate commensurate with the rate of interest applicable to the district at the time of construction or major rehabilitation of the system, or at the time of installation of the lines to which the property owner is seeking to connect. In lieu of requiring the installation of permanent local facilities not planned for construction by the district, a district may permit connection to the water and/or sewer systems through temporary facilities installed at the property owner's expense, provided the property owner pays a connection charge consistent with the provisions of this chapter and agrees, in the future, to connect to permanent facilities when they are installed; or a district may permit connection to the water and/or sewer systems through temporary facilities and collect from property owners so connecting a proportionate share of the estimated cost of future local facilities needed to serve the property, as determined by the district. The amount collected, including interest at a rate commensurate with the rate of interest applicable to the district at the time of construction of the temporary facilities, shall be held for contribution to the construction of the permanent local facilities by other developers or the district. The amount collected shall be deemed full satisfaction of the proportionate share of the actual cost of construction of the permanent local facilities. If the permanent local facilities are not constructed within fifteen years of the date of payment, the amount collected, including any accrued interest, shall be returned to the property owner, according to the records of the county auditor on the date of return. If the amount collected is returned to the property owner, and permanent local facilities capable of serving the property are constructed thereafter, the property owner at the time of construction of such permanent local facilities shall pay a proportionate share of the cost of such permanent local facilities, in addition to reasonable connection charges and other charges authorized by this section. A district may permit payment of the cost of connection and the reasonable connection charge to be paid with interest in installments over a period not exceeding fifteen years. The county treasurer may charge and collect a fee of three dollars for each year for the treasurer's services. Those fees shall be a charge to be included as part of each annual installment, and shall be credited to the county current expense fund by the county treasurer. Revenues from connection charges excluding permit fees are to be considered payments in aid of construction as defined by department of revenue rule. Rates or charges for on-site inspection and maintenance services may not be imposed under this chapter on the development, construction, or reconstruction of property.

Before adopting on-site inspection and maintenance utility services, or incorporating residences into an on-site inspection and maintenance or sewer utility under this chapter, notification must be provided, prior to the applicable public hearing, to all residences within the proposed service area that have on-site systems permitted by the local health officer. The notice must clearly state that the residence is within the proposed service area and must provide information on estimated rates or charges that may be imposed for the service.

A water-sewer district shall not provide on-site sewage system inspection, pumping services, or other maintenance or repair services under this section using water-sewer district employees unless the on-site system is connected by a publicly owned collection system to the water-sewer district's sewerage system, and the on-site system represents the first step in the sewage disposal process.

Except as otherwise provided in RCW 90.03.525, any public entity and public property, including the state of Washington and state property, shall be subject to rates and charges for sewer, water, stormwater control, drainage, and street lighting facilities to the same extent private persons and private property are subject to those rates and charges that are imposed by districts. In setting those rates and charges, consideration may be made of in-kind services, such as stream improvements or donation of property;

. To contract with individuals, associations and corporations, the state of Washington, and the United States;

. To employ such persons as are needed to carry out the district's purposes and fix salaries and any bond requirements for those employees;

. To contract for the provision of engineering, legal, and other professional services as in the board of commissioner's discretion is necessary in carrying out their duties;

. To sue and be sued;

. To loan and borrow funds and to issue bonds and instruments evidencing indebtedness under chapter 57.20 RCW and other applicable laws;

. To transfer funds, real or personal property, property interests, or services subject to RCW 57.08.015;

. To levy taxes in accordance with this chapter and chapters 57.04 and 57.20 RCW;

. To provide for making local improvements and to levy and collect special assessments on property benefited thereby, and for paying for the same or any portion thereof in accordance with chapter 57.16 RCW;

. To establish street lighting systems under RCW 57.08.060;

. To exercise such other powers as are granted to water-sewer districts by this title or other applicable laws; and

. To exercise any of the powers granted to cities and counties with respect to the acquisition, construction, maintenance, operation of, and fixing rates and charges for waterworks and systems of sewerage and drainage.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1532-S.SL.pdf?cite=2009%20c%20253%20§%201[2009 c 253 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5231-S.SL.pdf?cite=2007%20c%2031%20§%208[2007 c 31 § 8]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6208-S.SL.pdf?cite=2004%20c%20202%20§%201[2004 c 202 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2088-S.SL.pdf?cite=2003%20c%20394%20§%205[2003 c 394 § 5]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%202[1999 c 153 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5838-S.SL.pdf?cite=1997%20c%20447%20§%2016[1997 c 447 § 16]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20301[1996 c 230 § 301]; ]

== 57.08.007 - Concurrent service by two districts.
Except upon approval of both districts by resolution, a district may not provide a service within an area in which that service is available from another district or within an area in which that service is planned to be made available under an effective comprehensive plan of another district.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20302[1996 c 230 § 302]; ]

== 57.08.009 - Use of property not immediately necessary to district for park or recreational purposes.
A district may operate and maintain a park or recreational facilities on real property that it owns or in which it has an interest that is not immediately necessary for its purposes.

If such park or recreational facilities are operated by a person other than the district, including a corporation, partnership, or other business enterprise, the person shall indemnify and hold harmless the district for any injury or damage caused by the action of the person.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1031-S.SL.pdf?cite=1991%20c%2082%20§%203[1991 c 82 § 3]; ]

== 57.08.011 - Authority to manage, operate, maintain, or repair public or private water system—Contract.
A district may enter into a contract with any person, corporation, or other entity, public or private, that owns a water system located in the district to manage, operate, maintain, or repair the water system. Such a contract may be entered into only if the general comprehensive plan of the district reflects the water system that is to be so managed, operated, maintained, or repaired.

A district shall be liable to provide the services provided in such a contract only if the required contractual payments are made to the district, and such payments shall be secured by a lien on the property served by the water system to the same extent that rates and charges imposed by the district constitute liens on the property served by the district. The responsibility for all costs incurred by the water system in complying with water quality laws, regulations, and standards shall be solely that of the water system and not the district, except to the extent payments have been made to the district for the costs of such compliance.

A district periodically may transfer to another account surplus moneys that may accumulate in an account established by the district to receive payments for the provision of services for such a water system.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20303[1996 c 230 § 303]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c308.pdf?cite=1989%20c%20308%20§%2014[1989 c 308 § 14]; ]

== 57.08.012 - Fluoridation of water authorized.
A water district by a majority vote of its board of commissioners may fluoridate the water supply system of the water district. The commissioners may cause the proposition of fluoridation of the water supply to be submitted to the electors of the water district at any general election or special election to be called for the purpose of voting on the proposition. The proposition must be approved by a majority of the electors voting on the proposition to become effective.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c11.pdf?cite=1988%20c%2011%20§%202[1988 c 11 § 2]; ]

== 57.08.014 - Authority to adjust or delay rates or charges for low-income persons—Notice.
In addition to the authority of a district to establish classifications for rates and charges and impose such rates and charges, a district may adjust or delay those rates and charges for low-income persons or classes of low-income persons , including but not limited to, low-income persons with disabilities and low-income senior citizens. Other financial assistance available to low-income persons shall be considered in determining charges and rates under this section. Notification of special rates or charges established under this section shall be provided to all persons served by the district annually and upon initiating service. Information on cost shifts caused by establishment of the special rates or charges shall be included in the notification. Any reduction in charges and rates granted to low-income persons in one part of a service area shall be uniformly extended to low-income persons in all other parts of the service area.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2390.SL.pdf?cite=2020%20c%20274%20§%2044[2020 c 274 § 44]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%203[1999 c 153 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20304[1996 c 230 § 304]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c198.pdf?cite=1983%20c%20198%20§%202[1983 c 198 § 2]; ]

== 57.08.015 - Sale of unnecessary property authorized—Notice.
The board of commissioners of a district may sell, at public or private sale, property belonging to the district if the board determines that the property is not and will not be needed for district purposes and if the board gives notice of intention to sell as in this section provided. However, no such notice of intention shall be required to sell personal property of less than two thousand five hundred dollars in value.

The notice of intention to sell shall be published once a week for two consecutive weeks in a newspaper of general circulation in the district. The notice shall describe the property and state the time and place at which it will be sold or offered for sale, the terms of sale, whether the property is to be sold at public or private sale, and if at public sale the notice shall call for bids, fix the conditions of the bids and reserve the right to reject any and all bids for good cause.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%204[1999 c 153 § 4]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20305[1996 c 230 § 305]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5048-S.SL.pdf?cite=1993%20c%20198%20§%2019[1993 c 198 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c308.pdf?cite=1989%20c%20308%20§%207[1989 c 308 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c299.pdf?cite=1977%20ex.s.%20c%20299%20§%202[1977 ex.s. c 299 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c50.pdf?cite=1953%20c%2050%20§%201[1953 c 50 § 1]; ]

== 57.08.016 - Sale of unnecessary property authorized—Additional requirements for sale of realty.
. There shall be no private sale of real property where the estimated value exceeds the sum of five thousand dollars. Estimated value shall be determined by the board of commissioners and based upon real estate appraiser and broker advice as it considers appropriate. Subject to the provisions of subsection (2) of this section, no real property of the district shall be sold for less than ninety percent of the value thereof. Where the estimated value of the real property exceeds five thousand dollars, value shall be established by a written broker price opinion made not more than six months prior to the date of sale by three disinterested real estate brokers licensed under the laws of the state or by one professionally designated real estate appraiser as defined in chapter 18.140 RCW. A broker price opinion shall be signed by the broker and an appraisal must be signed by the appraiser and filed with the secretary of the board of commissioners of the district, who shall keep it at the office of the district open to public inspection. Any notice of intention to sell real property of the district shall recite the estimated value or, if an appraisal has been made, the appraised value thereof.

. If no purchasers can be obtained for the property at ninety percent or more of its estimated or appraised value after one hundred twenty days of offering the property for sale, the board of commissioners of the district may adopt a resolution stating that the district has been unable to sell the property at the ninety percent amount. The district then may sell the property at the highest price it can obtain at public auction. A notice of intention to sell at public auction shall be published once a week for two consecutive weeks in a newspaper of general circulation in the district. The notice shall describe the property, state the time and place at which it will be offered for sale and the terms of sale, and shall call for bids, fix the conditions thereof, and reserve the right to reject any and all bids for good cause.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5033.SL.pdf?cite=2011%20c%2090%20§%201[2011 c 90 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%205[1999 c 153 § 5]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20306[1996 c 230 § 306]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5048-S.SL.pdf?cite=1993%20c%20198%20§%2020[1993 c 198 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c308.pdf?cite=1989%20c%20308%20§%208[1989 c 308 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c162.pdf?cite=1988%20c%20162%20§%202[1988 c 162 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c103.pdf?cite=1984%20c%20103%20§%203[1984 c 103 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c50.pdf?cite=1953%20c%2050%20§%202[1953 c 50 § 2]; ]

== 57.08.017 - Application of sections to certain service provider agreements under chapter  70.150 RCW.
RCW 57.08.015, 57.08.016, 57.08.050, and 57.08.120 shall not apply to agreements entered into under authority of *chapter 70.150 RCW if there is compliance with the procurement procedure under **RCW 70.150.040.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20321[1996 c 230 § 321]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c244.pdf?cite=1986%20c%20244%20§%2016[1986 c 244 § 16]; ]

== 57.08.020 - Conveyance of water system to city or town.
That water districts duly organized under the laws of the state of Washington shall have the following powers in addition to those conferred by existing statutes. Whenever any water district shall have installed a distributing system of mains and laterals and as a source of supply of water shall be purchasing or intending to purchase water from any city or town, and whenever it shall appear to be advantageous to the water consumers in said water district that such city or town shall take over the water system of the water district and supply water to the said water users, the commissioners of said water district, upon being authorized as provided in RCW 57.08.030, shall have the right to convey such distributing system to any such city or town: PROVIDED, Such city or town is willing to accept, maintain and repair the same: PROVIDED, FURTHER, That all bonded and other indebtedness of said water district except local improvement district bonds shall have been paid.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c142.pdf?cite=1933%20c%20142%20§%201[1933 c 142 § 1]; RRS § 11586-1; ]

== 57.08.030 - Election on conveyance—Contract for operation of facilities.
. Whenever any district shall have installed a distributing system of water mains and laterals, and as a source of supply of water shall be purchasing or intending to purchase water from any city or town, and whenever it appears to be advantageous to the water consumers in the district that such city or town shall take over the water system of the district and supply water to those water users, the commissioners of the district, when authorized as provided in subsection (2) of this section, shall have the right to convey the distributing system to that city or town if that city or town is willing to accept, maintain, and repair the same.

. Should the commissioners of the district decide that it would be to the advantage of the water consumers of the district to make the conveyance provided for in subsection (1) of this section, they shall cause the proposition of making that conveyance to be submitted to the voters of the district at any general election or at a special election to be called for the purpose of voting on the same. If at the election a majority of the voters voting on the proposition shall be in favor of making the conveyance, the district commissioners shall have the right to convey to the city or town the mains and laterals belonging to the district upon the city or town entering into a contract satisfactory to the commissioners to maintain and repair the same.

. Whenever a city or town located wholly or in part within a district shall enter into a contract with the commissioners of a district providing that the city or town shall take over all of the operation of the water supply facilities of the district located within its boundaries, the area of the district located within the city or town shall upon the execution of the contract cease to be served by the district for water service purposes. However, the affected land within that city or town shall remain liable for the payment of all assessments, any lien upon the property at the time of the execution of the agreement, and for any lien of all general obligation bonds due at the date of the contract, and the city or town shall remain liable for its fair prorated share of the debt of the area for any revenue bonds, outstanding as of the date of contract.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%206[1999 c 153 § 6]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20307[1996 c 230 § 307]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c142.pdf?cite=1933%20c%20142%20§%202[1933 c 142 § 2]; RRS § 11586-2; ]

== 57.08.035 - Effect when city or town takes over portion of water system.
Whenever a city or town located wholly or in part within a water district shall enter into a contract with the commissioners of a water district providing that the city or town shall take over all of the operation of the facilities of the district located within its boundaries, such area of said water district located within said city or town shall upon the execution of said contract cease to be a part of said water district and the inhabitants therein shall no longer be permitted to vote in said water district. The land, however, within such city or town shall remain liable for the payment of all assessments, any lien upon said property at the time of the execution of said agreement and for any lien of all general obligation bonds due at the date of said contract, and the city shall remain liable for its fair prorated share of the debt of the area for any revenue bonds outstanding as of said date of contract.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c272.pdf?cite=1971%20ex.s.%20c%20272%20§%2013[1971 ex.s. c 272 § 13]; ]

== 57.08.040 - City or town may accept and agree to maintain system.
Whenever any city or town is selling or proposes to sell water to a district, the city or town may by ordinance accept a conveyance of any distributing system and enter into a contract with the district for the maintenance and repair of the system and the supplying of water to the district consumers.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20308[1996 c 230 § 308]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1933c142.pdf?cite=1933%20c%20142%20§%203[1933 c 142 § 3]; RRS § 11586-3; ]

== 57.08.041 - Contracting for management of water storage assets—Notice—Procedure—Definitions.
. Any water-sewer district may elect to contract for asset management service of its water storage assets in accordance with this section. If a water-sewer district elects to contract under this subsection for all, some, or one component of water storage asset management services for its water storage assets, each water-sewer district shall publish notice of its requirements to procure asset management service of its water storage assets. The announcement must concisely state the scope and nature of the water storage asset management service for which a contract is required and encourage firms to submit proposals to meet these requirements. If a water-sewer district chooses to negotiate a water storage asset management service contract under this section, no otherwise applicable statutory procurement requirement applies.

. The water-sewer district may negotiate a fair and reasonable water storage asset management service contract with the firm that submits the best proposal based on criteria that is established by the water-sewer district.

. If the water-sewer district is unable to negotiate a satisfactory water storage asset management service contract with the firm that submits the best proposal, negotiations with that firm must formally be terminated and the water-sewer district may select another firm in accordance with this section and continue negotiation until a water storage asset management service contract is reached or the selection process is terminated.

. For the purposes of this section:

.. "Water storage asset management services" means the financing, designing, improving, operating, maintaining, repairing, testing, inspecting, cleaning, administering, or managing, or any combination thereof, of a water storage asset.

.. "Water storage asset" means water storage structures and associated distribution systems, such as the water tank, tower, well, meter, or water filter.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5119.SL.pdf?cite=2017%20c%20314%20§%202[2017 c 314 § 2]; ]

== 57.08.044 - Contracts for acquisition, use, operation, etc., authorized—Service to areas in other districts.
A district may enter into contracts with any county, city, town, or any other municipal or quasi-municipal corporation, or with any private person or corporation, for the acquisition, ownership, use, and operation of any property, facilities, or services, within or without the district, and necessary or desirable to carry out the purposes of the district. A district may provide water, reclaimed water, sewer, drainage, or street lighting services to property owners in areas within or without the limits of the district, except that if the area to be served is located within another existing district duly authorized to exercise district powers in that area, then water, reclaimed water, sewer, drainage, or street lighting service may not be so provided by contract or otherwise without the consent by resolution of the board of commissioners of that other district.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1532-S.SL.pdf?cite=2009%20c%20253%20§%202[2009 c 253 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%207[1999 c 153 § 7]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20309[1996 c 230 § 309]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c45.pdf?cite=1981%20c%2045%20§%204[1981 c 45 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c103.pdf?cite=1959%20c%20103%20§%203[1959 c 103 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c250.pdf?cite=1953%20c%20250%20§%208[1953 c 250 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c210.pdf?cite=1941%20c%20210%20§%2048[1941 c 210 § 48]; Rem. Supp. 1941 § 9425-57; ]

== 57.08.047 - Provision of water, reclaimed water, sewer, or drainage service beyond district or city subject to review by boundary review board.
The provision of water, reclaimed water, sewer, or drainage service beyond the boundaries of a special purpose district or city may be subject to potential review by a boundary review board under chapter 36.93 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1532-S.SL.pdf?cite=2009%20c%20253%20§%203[2009 c 253 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%208[1999 c 153 § 8]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20310[1996 c 230 § 310]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c84.pdf?cite=1989%20c%2084%20§%2057[1989 c 84 § 57]; ]

== 57.08.050 - Contracts for materials and work—Notice—Bids—Small works roster—Waiver of requirements.
. All work ordered, the estimated cost of which is in excess of fifty thousand dollars, shall be let by contract and competitive bidding. Before awarding any such contract the board of commissioners shall publish a notice in a newspaper of general circulation where the district is located at least once thirteen days before the last date upon which bids will be received, inviting sealed proposals for such work, plans and specifications which must at the time of publication of such notice be on file in the office of the board of commissioners subject to the public inspection. The notice shall state generally the work to be done and shall call for proposals for doing the same to be sealed and filed with the board of commissioners on or before the day and hour named therein.

Each bid shall be accompanied by a certified or cashier's check or postal money order payable to the order of the county treasurer for a sum not less than five percent of the amount of the bid, or accompanied by a bid bond in an amount not less than five percent of the bid with a corporate surety licensed to do business in the state, conditioned that the bidder will pay the district as liquidated damages the amount specified in the bond, unless the bidder enters into a contract in accordance with the bidder's bid, and no bid shall be considered unless accompanied by such check, cash or bid bond. At the time and place named such bids shall be publicly opened and read and the board of commissioners shall proceed to canvass the bids and may let such contract to the lowest responsible bidder upon plans and specifications on file or to the best bidder submitting the bidder's own plans and specifications. The board of commissioners may reject all bids for good cause and readvertise and in such case all checks, cash or bid bonds shall be returned to the bidders. If the contract is let, then all checks, cash, or bid bonds shall be returned to the bidders, except that of the successful bidder, which shall be retained until a contract shall be entered into for doing the work, and a bond to perform such work furnished with sureties satisfactory to the board of commissioners in the full amount of the contract price between the bidder and the commission in accordance with the bid. If the bidder fails to enter into the contract in accordance with the bid and furnish the bond within ten days from the date at which the bidder is notified that the bidder is the successful bidder, the check, cash, or bid bonds and the amount thereof shall be forfeited to the district. If the bidder fails to enter into a contract in accordance with the bidder's bid, and the board of commissioners deems it necessary to take legal action to collect on any bid bond required by this section, then the district shall be entitled to collect from the bidder any legal expenses, including reasonable attorneys' fees occasioned thereby. A low bidder who claims error and fails to enter into a contract is prohibited from bidding on the same project if a second or subsequent call for bids is made for the project.

. As an alternative to requirements under subsection (1) of this section, a water-sewer district may let contracts using the small works roster process under RCW 39.04.155.

. Any purchase of materials, supplies, or equipment, with an estimated cost in excess of forty thousand dollars, shall be by contract. Any purchase of materials, supplies, or equipment, with an estimated cost of less than fifty thousand dollars shall be made using the process provided in RCW 39.04.190. Any purchase of materials, supplies, or equipment with an estimated cost of fifty thousand dollars or more shall be made by competitive bidding following the procedure for letting contracts for projects under subsection (1) of this section.

. As an alternative to requirements under subsection (3) of this section, a water-sewer district may let contracts for purchase of materials, supplies, or equipment with the suppliers designated on current state agency, county, city, or town purchasing rosters for the materials, supplies, or equipment, when the roster has been established in accordance with the competitive bidding law for purchases applicable to the state agency, county, city, or town. The price and terms for purchases shall be as described on the applicable roster.

. The board may waive the competitive bidding requirements of this section pursuant to RCW 39.04.280 if an exemption contained within that section applies to the purchase or public work.

. [Empty]
.. A district may procure public works with a unit priced contract under this section for the purpose of completing anticipated types of work based on hourly rates or unit pricing for one or more categories of work or trades.

.. For the purposes of this section, "unit priced contract" means a competitively bid contract in which public works are anticipated on a recurring basis to meet the business or operational needs of the district, under which the contractor agrees to a fixed period indefinite quantity delivery of work, at a defined unit price for each category of work.

.. Unit priced contracts must be executed for an initial contract term not to exceed one year, with the district having the option of extending or renewing the unit priced contract for one additional year.

.. Invitations for unit price bids must include, for purposes of the bid evaluation, estimated quantities of the anticipated types of work or trades, and specify how the district will issue or release work assignments, work orders, or task authorizations pursuant to a unit priced contract for projects, tasks, or other work based on the hourly rates or unit prices bid by the contractor. Contracts must be awarded to the lowest responsible bidder as per RCW 39.04.010. Whenever possible, the district must invite at least one proposal from a certified minority or woman contractor who otherwise qualifies under this section.

.. Unit price contractors shall pay prevailing wages for all work that would otherwise be subject to the requirements of chapter 39.12 RCW. Prevailing wages for all work performed pursuant to each work order must be the prevailing wage rates in effect at the beginning date for each contract year. Unit priced contracts must have prevailing wage rates updated annually. Intents and affidavits for prevailing wages paid must be submitted annually for all work completed within the previous twelve-month period of the unit priced contract.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5418-S.SL.pdf?cite=2019%20c%20434%20§%2010[2019 c 434 § 10]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1410-S.SL.pdf?cite=2015%20c%20136%20§%201[2015 c 136 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1847-S.SL.pdf?cite=2009%20c%20229%20§%2011[2009 c 229 § 11]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2183.SL.pdf?cite=2003%20c%20145%20§%201[2003 c 145 § 1]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1045.SL.pdf?cite=2003%20c%2060%20§%201[2003 c 60 § 1]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6347-S.SL.pdf?cite=2000%20c%20138%20§%20212[2000 c 138 § 212]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%209[1999 c 153 § 9]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2077-S.SL.pdf?cite=1998%20c%20278%20§%208[1998 c 278 § 8]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5018.SL.pdf?cite=1997%20c%20245%20§%204[1997 c 245 § 4]; prior:  1996 c 230 § 311; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5757-S2.SL.pdf?cite=1996%20c%2018%20§%2014[1996 c 18 § 14]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6030.SL.pdf?cite=1994%20c%2031%20§%202[1994 c 31 § 2]; prior:  1993 c 198 § 21; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5110-S.SL.pdf?cite=1993%20c%2045%20§%208[1993 c 45 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c105.pdf?cite=1989%20c%20105%20§%202[1989 c 105 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c309.pdf?cite=1987%20c%20309%20§%202[1987 c 309 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c154.pdf?cite=1985%20c%20154%20§%202[1985 c 154 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c38.pdf?cite=1983%20c%2038%20§%202[1983 c 38 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c137.pdf?cite=1979%20ex.s.%20c%20137%20§%202[1979 ex.s. c 137 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c64.pdf?cite=1975%201st%20ex.s.%20c%2064%20§%202[1975 1st ex.s. c 64 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965c72.pdf?cite=1965%20c%2072%20§%201[1965 c 72 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c216.pdf?cite=1947%20c%20216%20§%202[1947 c 216 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1929c114.pdf?cite=1929%20c%20114%20§%2021[1929 c 114 § 21]; Rem. Supp. 1947 § 11598. Cf.  1913 c 161 § 20; ]

== 57.08.060 - Powers as to street lighting systems—Establishment.
In addition to the powers given districts by law, a district shall also have power to acquire, construct, maintain, operate, and develop street lighting systems.

To establish a street lighting system, the board of commissioners shall adopt a resolution proposing a street lighting system and delineating the boundaries of the area to be served by the proposed street lighting system. The board shall conduct a public hearing on the resolution to create a street lighting system. Notice of the hearing shall be published at least once each week for two consecutive weeks in one or more newspapers of general circulation in the area to be served by the proposed street lighting system. Following the hearing, the board may by resolution establish the street lighting system.

A street lighting system shall not be established if, within thirty days following the decision of the board, a petition opposing the street lighting system is filed with the board and contains the signatures of at least forty percent of the voters registered in the area to be served by the proposed system.

The district has the same powers of imposing charges for providing street lighting, collecting delinquent street lighting charges, and financing street lighting systems by issuing general obligation bonds, issuing revenue bonds, and creating improvement districts as it has for imposing charges for providing water, collecting delinquent water service charges, and financing water systems by issuing general obligation bonds, issuing revenue bonds, and creating improvement districts.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20312[1996 c 230 § 312]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c449.pdf?cite=1987%20c%20449%20§%2011[1987 c 449 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c105.pdf?cite=1982%20c%20105%20§%201[1982 c 105 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1941c68.pdf?cite=1941%20c%2068%20§%201[1941 c 68 § 1]; Rem. Supp. 1941 § 11604-12; ]

== 57.08.065 - Powers as to mutual systems—Overlapping districts—Operation of system of sewerage or drainage by former water district.
. A district shall have power to establish, maintain, and operate a mutual water, sewerage, drainage, and street lighting system, a mutual system of any two or three of the systems, or separate systems.

. Where any two or more districts include the same territory as of July 1, 1997, none of the overlapping districts may provide any service that was made available by any of the other districts prior to July 1, 1997, within the overlapping territory without the consent by resolution of the board of commissioners of the other district or districts.

. A district that was a water district prior to July 1, 1997, that did not operate a system of sewerage or drainage prior to July 1, 1997, may not proceed to exercise the powers to establish, maintain, construct, and operate any system of sewerage or drainage without first obtaining written approval and certification of necessity from the department of ecology and department of health. Any comprehensive plan for a system of sewers or drainages or addition thereto or betterment thereof, proposed by a district that was a water district prior to July 1, 1997, shall be approved by the same county and state officials as were required to approve such plans adopted by a sewer district immediately prior to July 1, 1997, and as subsequently may be required.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%2010[1999 c 153 § 10]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5838-S.SL.pdf?cite=1997%20c%20447%20§%2017[1997 c 447 § 17]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20313[1996 c 230 § 313]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c45.pdf?cite=1981%20c%2045%20§%2011[1981 c 45 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c141.pdf?cite=1979%20c%20141%20§%2069[1979 c 141 § 69]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c135.pdf?cite=1967%20ex.s.%20c%20135%20§%203[1967 ex.s. c 135 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c111.pdf?cite=1963%20c%20111%20§%201[1963 c 111 § 1]; ]

== 57.08.081 - Rates and charges—Delinquencies.
. Subject to *RCW 57.08.005(6), the commissioners of any district shall provide for revenues by fixing rates and charges for furnishing sewer and drainage service and facilities to those to whom service is available or for providing water, such rates and charges to be fixed as deemed necessary by the commissioners, so that uniform charges will be made for the same class of customer or service and facility. Rates and charges may be combined for the furnishing of more than one type of sewer or drainage service and facilities.

. In classifying customers of such water, sewer, or drainage system, the board of commissioners may in its discretion consider any or all of the following factors: The difference in cost to various customers; the location of the various customers within and without the district; the difference in cost of maintenance, operation, repair, and replacement of the various parts of the system; the different character of the service furnished various customers; the quantity and quality of the service and facility furnished; the time of its use; the achievement of water conservation goals and the discouragement of wasteful practices; capital contributions made to the system including but not limited to assessments; and any other matters which present a reasonable difference as a ground for distinction. Rates shall be established as deemed proper by the commissioners and as fixed by resolution and shall produce revenues sufficient to take care of the costs of maintenance and operation, revenue bond and warrant interest and principal amortization requirements, and all other charges necessary for efficient and proper operation of the system. Prior to furnishing services, a district may require a deposit to guarantee payment for services. However, failure to require a deposit does not affect the validity of any lien authorized by this section.

. The commissioners shall enforce collection of connection charges, and rates and charges for water supplied against property owners connecting with the system or receiving such water, and for sewer and drainage services charged against property to which and its owners to whom the service is available, such charges being deemed charges against the property served, by addition of penalties of not more than ten percent thereof in case of failure to pay the charges at times fixed by resolution. The commissioners may provide by resolution that where either connection charges or rates and charges for services supplied are delinquent for any specified period of time, the district shall certify the delinquencies to the auditor of the county in which the real property is located, and the charges and any penalties added thereto and interest thereon at the rate of not more than the prime lending rate of the district's bank plus four percentage points per year shall be a lien against the property upon which the service was received, subject only to the lien for general taxes.

. The district may, at any time after the connection charges or rates and charges for services supplied or available and penalties are delinquent for a period of sixty days, bring suit in foreclosure by civil action in the superior court of the county in which the real property is located. The court may allow, in addition to the costs and disbursements provided by statute, attorneys' fees, title search and report costs, and expenses as it adjudges reasonable. The action shall be in rem, and may be brought in the name of the district against an individual or against all of those who are delinquent in one action. The laws and rules of the court shall control as in other civil actions.

. In addition to the right to foreclose provided in this section, the district may also cut off all or part of the service after charges for water or sewer service supplied or available are delinquent for a period of thirty days.

. A district may determine how to apply partial payments on past due accounts.

. A district may provide a real property owner or the owner's designee with duplicate bills for service to tenants, or may notify an owner or the owner's designee that a tenant's service account is delinquent. However, if an owner or the owner's designee notifies the district in writing that a property served by the district is a rental property, asks to be notified of a tenant's delinquency, and has provided, in writing, a complete and accurate mailing address, the district shall notify the owner or the owner's designee of a tenant's delinquency at the same time and in the same manner the district notifies the tenant of the tenant's delinquency or by mail. When a district provides a real property owner or the owner's designee with duplicates of tenant utility service bills or notice that a tenant's utility account is delinquent, the district shall notify the tenant that it is providing the duplicate bills or delinquency notice to the owner or the owner's designee. After January 1, 1999, if a district fails to notify the owner of a tenant's delinquency after receiving a written request to do so and after receiving the other information required by this subsection (7), the district shall have no lien against the premises for the tenant's delinquent and unpaid charges.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/2088-S.SL.pdf?cite=2003%20c%20394%20§%206[2003 c 394 § 6]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%2011[1999 c 153 § 11]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2551-S.SL.pdf?cite=1998%20c%20285%20§%202[1998 c 285 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2411-S.SL.pdf?cite=1998%20c%20106%20§%209[1998 c 106 § 9]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5838-S.SL.pdf?cite=1997%20c%20447%20§%2019[1997 c 447 § 19]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20314[1996 c 230 § 314]; ]

== 57.08.085 - Public property subject to rates and charges for drainage facilities.
Except as otherwise provided in RCW 90.03.525, any public entity and public property, including state of Washington property, shall be subject to rates and charges for drainage facilities to the same extent as private persons and private property are subject to such rates and charges that are imposed by districts pursuant to RCW 57.08.005 or 57.08.081. In setting those rates and charges, consideration may be given to in-kind services, such as stream improvements or donation of property.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%2012[1999 c 153 § 12]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20315[1996 c 230 § 315]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c278.pdf?cite=1986%20c%20278%20§%2059[1986 c 278 § 59]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c315.pdf?cite=1983%20c%20315%20§%205[1983 c 315 § 5]; ]

== 57.08.100 - Health care, group, life, and social security insurance contracts for employees', commissioners' benefit—Joint action with other districts.
Subject to chapter 48.62 RCW, a district, by a majority vote of its board of commissioners, may enter into contracts to provide health care services and/or group insurance and/or term life insurance and/or social security insurance for the benefit of its employees and may pay all or any part of the cost thereof. Any two or more districts, by a majority vote of their respective boards of commissioners, may, if deemed expedient, join in the procuring of such health care services and/or group insurance and/or term life insurance, and the board of commissioners of a participating district may by appropriate resolution authorize its respective district to pay all or any portion of the cost thereof.

A district providing health, group, or life insurance to its employees may provide its commissioners with the same coverage. However, the per person amounts for such insurance paid by the district shall not exceed the per person amounts paid by the district for its employees.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5122.SL.pdf?cite=2019%20c%2040%20§%201[2019 c 40 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20316[1996 c 230 § 316]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1907-S.SL.pdf?cite=1991%20sp.s.%20c%2030%20§%2025[1991 sp.s. c 30 § 25]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1031-S.SL.pdf?cite=1991%20c%2082%20§%205[1991 c 82 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c190.pdf?cite=1981%20c%20190%20§%206[1981 c 190 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c24.pdf?cite=1973%20c%2024%20§%202[1973 c 24 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c261.pdf?cite=1961%20c%20261%20§%202[1961 c 261 § 2]; ]

== 57.08.105 - Liability insurance for officials and employees.
The board of commissioners of each district may purchase liability insurance with such limits as it may deem reasonable for the purpose of protecting its officials and employees against liability for personal or bodily injuries and property damage arising from their acts or omissions while performing or in good faith purporting to perform their official duties.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20317[1996 c 230 § 317]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973c125.pdf?cite=1973%20c%20125%20§%207[1973 c 125 § 7]; ]

== 57.08.120 - Lease of real property—Notice, hearing—Performance bond or security.
A district may lease out real property which it owns or in which it has an interest and which is not immediately necessary for its purposes upon such terms as the board of commissioners deems proper. No such lease shall be made until the district has first caused notice thereof to be published twice in a newspaper in general circulation in the district, the first publication to be at least fifteen days and the second at least seven days prior to the making of such lease. The notice shall describe the property, the lessee, and the lease payments. A hearing shall be held pursuant to the terms of the notice, at which time any and all persons who may be interested shall have the right to appear and to be heard.

No such lease shall be made unless secured by a bond conditioned on the performance of the terms of the lease, with surety satisfactory to the commissioners and with a penalty of not less than one-sixth of the term of the lease or for one year's rental, whichever is greater.

No such lease shall be made for a term longer than fifty years. In cases involving leases of more than five years, the commissioners may provide for or stipulate to acceptance of a bond conditioned on the performance of a part of the term for five years or more whenever it is further provided that the lessee must procure and deliver to the commissioners renewal bonds with like terms and conditions no more than two years prior nor less than one year prior to the expiration of such bond during the entire term of the lease. However, no such bond shall be construed to secure the furnishing of any other bond by the same surety or indemnity company. The board of commissioners may require a reasonable security deposit in lieu of a bond on leased property owned by a district.

The commissioners may accept as surety on any bond required by this section an approved surety company, or may accept in lieu thereof a secured interest in property of a value at least twice the amount of the bond required, conditioned further that in the event the commissioners determine that the value of the bond security has become or is about to become impaired, additional security shall be required from the lessee.

The authority granted under this section shall not be exercised by the board of commissioners unless the property is declared by resolution of the board of commissioners to be property for which there is a future need by the district and for the use of which provision is made in the comprehensive plan of the district as the same may be amended from time to time.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5231-S.SL.pdf?cite=2007%20c%2031%20§%209[2007 c 31 § 9]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20319[1996 c 230 § 319]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1031-S.SL.pdf?cite=1991%20c%2082%20§%206[1991 c 82 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c135.pdf?cite=1967%20ex.s.%20c%20135%20§%201[1967 ex.s. c 135 § 1]; ]

== 57.08.140 - RCW  39.33.060 to govern on sales by district for park and recreational purposes.
The provisions of RCW 57.08.015, 57.08.016, and 57.08.120 shall have no application as to the sale or conveyance of real or personal property or any interest or right therein by a district to the county or park and recreation district wherein such property is located for park and recreational purposes, but in those cases the provisions of RCW 39.33.060 shall govern.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20320[1996 c 230 § 320]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c243.pdf?cite=1971%20ex.s.%20c%20243%20§%208[1971 ex.s. c 243 § 8]; ]

== 57.08.150 - Extensions by private party—Preparation of plans—Review by district.
A district may not require that a specified engineer prepare plans or designs for extensions to its systems if the extensions are to be financed and constructed by a private party, but may review, and approve or reject, the plans or designs which have been prepared for such a private party based upon standards and requirements established by the district.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20323[1996 c 230 § 323]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c309.pdf?cite=1987%20c%20309%20§%204[1987 c 309 § 4]; ]

== 57.08.160 - Authority to assist customers in the acquisition of water conservation equipment—Limitations.
Any district is hereby authorized, within limits established by the Constitution of the state of Washington, to assist the owners of structures in financing the acquisition and installation of fixtures, systems, and equipment, for compensation or otherwise, for the conservation or more efficient use of water in the structures under a water conservation plan adopted by the district if the cost per unit of water saved or conserved by the use of the fixtures, systems, and equipment is less than the cost per unit of water supplied by the next least costly new water source available to the district to meet future demand. Except where otherwise authorized, assistance shall be limited to:

. Providing an inspection of the structure, either directly or through one or more inspectors under contract, to determine and inform the owner of the estimated cost of purchasing and installing conservation fixtures, systems, and equipment for which financial assistance will be approved and the estimated life-cycle savings to the water system and the consumer that are likely to result from the installation of the fixtures, systems, or equipment;

. Providing a list of businesses that sell and install the fixtures, systems, and equipment within or in close proximity to the service area of the city or town, each of which businesses shall have requested to be included and shall have the ability to provide the products in a workmanlike manner and to utilize the fixtures, systems, and equipment in accordance with the prevailing national standards;

. Arranging to have approved conservation fixtures, systems, and equipment installed by a private contractor whose bid is acceptable to the owner of the structure and verifying the installation; and

. Arranging or providing financing for the purchase and installation of approved conservation fixtures, systems, and equipment. The fixtures, systems, and equipment shall be purchased or installed by a private business, the owner, or the utility.

Pay back shall be in the form of incremental additions to the utility bill, billed either together with the use charge or separately. Loans shall not exceed two hundred forty months in length.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2677.SL.pdf?cite=2010%201st%20sp.s.%20c%205%20§%203[2010 1st sp.s. c 5 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20324[1996 c 230 § 324]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c421.pdf?cite=1989%20c%20421%20§%205[1989 c 421 § 5]; ]

== 57.08.170 - Water conservation plan—Emergency water use restrictions—Fine.
A district may adopt a water conservation plan and emergency water use restrictions. The district may enforce a water conservation plan and emergency water use restrictions by imposing a fine as provided by resolution for failure to comply with any such plan or restrictions. The commissioners may provide by resolution that if a fine for failure to comply with the water conservation plan or emergency water use restrictions is delinquent for a specified period of time, the district shall certify the delinquency to the treasurer of the county in which the real property is located and serve notice of the delinquency on the subscribing water customer who fails to comply, and the fine is then a separate item for inclusion on the bill of the party failing to comply with the water conservation plan or emergency water use restrictions.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20325[1996 c 230 § 325]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1031-S.SL.pdf?cite=1991%20c%2082%20§%207[1991 c 82 § 7]; ]

== 57.08.180 - Sewer, drainage, and water connections without district permission—Penalties.
It is unlawful and a misdemeanor to make, or cause to be made, or to maintain any connection with any sewer, drainage, or water system of any district, or with any sewer, drainage, or water system which is connected directly or indirectly with any sewer, drainage, or water system of any district without having permission from the district.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%2014[1999 c 153 § 14]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20322[1996 c 230 § 322]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5448-S2.SL.pdf?cite=1995%20c%20376%20§%2015[1995 c 376 § 15]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5512.SL.pdf?cite=1991%20c%20190%20§%205[1991 c 190 § 5]; ]

== 57.08.190 - Cooperative watershed management.
In addition to the authority provided in RCW 57.08.005, a water district, sewer district, or water-sewer district may participate in and expend revenue on cooperative watershed management actions, including watershed management partnerships under RCW 39.34.210 and other intergovernmental agreements, for purposes of water supply, water quality, and water resource and habitat protection and management.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5073.SL.pdf?cite=2003%20c%20327%20§%2013[2003 c 327 § 13]; ]

