= 57.22 - Contracts for system extensions.
:toc:

== 57.22.010 - Contracts—Conditions.
If the district approves an extension to the system, the district shall contract with owners of real estate located within the district boundaries, at an owner's request, for the purpose of permitting extensions to the district's system to be constructed by such owner at such owner's sole cost where such extensions are required as a prerequisite to further property development. The contract shall contain such conditions as the district may require pursuant to the district's adopted policies and standards. The district shall request comprehensive plan approval for such extension, if required, and connection of the extension to the district system is conditioned upon:

. Construction of such extension according to plans and specifications approved by the district;

. Inspection and approval of such extension by the district;

. Transfer to the district of such extension without cost to the district upon acceptance by the district of such extension;

. Payment of all required connection charges to the district;

. Full compliance with the owner's obligations under such contract and with the district's rules and regulations;

. Provision of sufficient security to the district to ensure completion of the extension and other performance under the contract;

. Payment by the owner to the district of all of the district's costs associated with such extension including, but not limited to, the district's engineering, legal, and administrative costs; and

. Verification and approval of all contracts and costs related to such extension.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20801[1996 c 230 § 801]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c389.pdf?cite=1989%20c%20389%20§%2011[1989 c 389 § 11]; ]

== 57.22.020 - Reimbursement to owner—Contract requirements.
. Except as otherwise provided in subsection (2) of this section, the contract shall also provide, subject to the terms and conditions in this section, for the reimbursement to the owner or the owner's assigns for a period not to exceed fifteen years of a portion of the costs of the facilities constructed pursuant to such contract from connection charges received by the district from other property owners who subsequently connect to or use the facilities within the period of time that the contract is effective and who did not contribute to the original cost of such facilities.

. [Empty]
.. The contract may provide for an extension of the fifteen-year reimbursement period for a time not to exceed the duration of any moratorium, phasing ordinance, concurrency designation, or other governmental action that prevents making applications for, or the approval of, any new development for a period of six months or more within the benefit area of the system extensions authorized under this chapter.

.. Upon the extension of the reimbursement period pursuant to (a) of this subsection, the contract must specify the duration of the contract extension and must be filed and recorded with the county auditor. Property owners who are subject to the reimbursement obligations under subsection (1) of this section shall be notified by the water-sewer district of the extension filed under this subsection.

. Each contract shall include a provision requiring that every two years from the date the contract is executed a property owner entitled to reimbursement under this section provide the water-sewer district with information regarding the current contract name, address, and telephone number of the person, company, or partnership that originally entered into the contract. If the property owner fails to comply with the notification requirements of this subsection within sixty days of the specified time, then the water-sewer district may collect any reimbursement funds owed to the property owner under the contract. Such funds must be deposited in the capital fund of the water-sewer district.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3192.SL.pdf?cite=2006%20c%2088%20§%203[2006 c 88 § 3]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20802[1996 c 230 § 802]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c389.pdf?cite=1989%20c%20389%20§%2012[1989 c 389 § 12]; ]

== 57.22.030 - Scope of reimbursement.
The reimbursement shall be a pro rata share of construction and contract administration costs of the project. Reimbursement for projects shall include, but not be limited to, design, engineering, installation, and restoration.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20803[1996 c 230 § 803]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c389.pdf?cite=1989%20c%20389%20§%2013[1989 c 389 § 13]; ]

== 57.22.040 - Reimbursement—Procedures.
The procedures for reimbursement contracts shall be governed by the following:

. A reimbursement area shall be formulated by the board of commissioners within a reasonable time after the acceptance of the extension. The reimbursement shall be based upon a determination by the board of commissioners of which parcels would require similar improvements upon development.

. The contract must be recorded in the appropriate county auditor's office after the final execution of the agreement.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20804[1996 c 230 § 804]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c389.pdf?cite=1989%20c%20389%20§%2014[1989 c 389 § 14]; ]

== 57.22.050 - District participation in financing project.
As an alternative to financing projects under this chapter solely by owners of real estate, districts may join in the financing of improvement projects and may be reimbursed in the same manner as the owners of real estate who participate in the projects, if the board of commissioners has specified the conditions of its participation in a resolution.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%20805[1996 c 230 § 805]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c389.pdf?cite=1989%20c%20389%20§%2015[1989 c 389 § 15]; ]

