= 57.36 - Merger of districts.
:toc:

== 57.36.001 - Actions subject to review by boundary review board.
Actions taken under this chapter may be subject to potential review by a boundary review board under chapter 36.93 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%201201[1996 c 230 § 1201]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c84.pdf?cite=1989%20c%2084%20§%2061[1989 c 84 § 61]; ]

== 57.36.010 - Merger of districts authorized.
Whenever one or more districts desire to merge into another district, the district or districts desiring to merge into the other district shall be referred to as the "merging district" or "merging districts" and the district into which the merging district or districts desire to merge shall be referred to as the "merger district." After the merger, the merger district shall survive under its original name or number.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%201202[1996 c 230 § 1202]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c308.pdf?cite=1989%20c%20308%20§%2012[1989 c 308 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c17.pdf?cite=1982%201st%20ex.s.%20c%2017%20§%2029[1982 1st ex.s. c 17 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c39.pdf?cite=1967%20ex.s.%20c%2039%20§%203[1967 ex.s. c 39 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c28.pdf?cite=1961%20c%2028%20§%201[1961 c 28 § 1]; ]

== 57.36.020 - Initiation of merger—Procedure.
A merger of districts may be initiated in either of the following ways:

. Whenever the boards of commissioners of districts determine by resolution that the merger of such districts shall be conducive to the public health, welfare, and convenience and to be of special benefit to the lands of such districts.

. Whenever ten percent of the voters residing within the merging district or districts petition the board of commissioners of the merging district or districts for a merger, and the board of commissioners of the merger district determines by resolution that the merger of the districts shall be conducive to the public health, welfare, and convenience of the districts.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%201203[1996 c 230 § 1203]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c39.pdf?cite=1967%20ex.s.%20c%2039%20§%204[1967 ex.s. c 39 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c28.pdf?cite=1961%20c%2028%20§%202[1961 c 28 § 2]; ]

== 57.36.030 - Agreement—Certification to county auditor—Election—Notice, conduct.
Whenever a merger is initiated in either of the two ways provided under this chapter, the boards of commissioners of the districts shall enter into an agreement providing for the merger. The agreement must be entered into within ninety days following completion of the last act in initiation of the merger.

The respective boards of commissioners shall certify the agreement to the county auditor of each county in which the districts are located. Each county auditor shall call a special election for the purpose of submitting to the voters of the respective districts the proposition of whether the merging district or districts shall be merged into the merger district. Notice of the elections shall be given and the elections conducted in accordance with the general election laws.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%201204[1996 c 230 § 1204]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982ex1c17.pdf?cite=1982%201st%20ex.s.%20c%2017%20§%2033[1982 1st ex.s. c 17 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c39.pdf?cite=1967%20ex.s.%20c%2039%20§%205[1967 ex.s. c 39 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c28.pdf?cite=1961%20c%2028%20§%203[1961 c 28 § 3]; ]

== 57.36.040 - When merger effective—Cessation of merging district—Commissioners.
If at such election a majority of the voters of the merging district or districts shall vote in favor of the merger, the merger shall be authorized. The merger shall be effective and the merging district or districts shall cease to exist and shall become a part of the merger district, upon the certification of the election results. The commissioners of the merging district or districts shall hold office as commissioners of the new merged district until their respective terms of office expire or until they resign from office if the resignation is before the expiration of their terms of office. The election of commissioners in the merger district after the merger shall occur as provided in RCW 57.32.130 in a consolidated district after the consolidation.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1264.SL.pdf?cite=1999%20c%20153%20§%2023[1999 c 153 § 23]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%201205[1996 c 230 § 1205]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c104.pdf?cite=1982%20c%20104%20§%202[1982 c 104 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c39.pdf?cite=1967%20ex.s.%20c%2039%20§%206[1967 ex.s. c 39 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c28.pdf?cite=1961%20c%2028%20§%204[1961 c 28 § 4]; ]

== 57.36.050 - Vesting of funds and property in merger district—Outstanding indebtedness.
All funds and property, real and personal, of the merging district or districts, shall vest in and become the property of the merger district. Unless the agreement of merger provides to the contrary, any outstanding indebtedness of any form, owed by the districts, shall remain the obligation of the area of the original debtor district; and the commissioners of the merger district shall make such levies, assessments, or charges for service upon such area or the users therein as shall pay off such indebtedness at maturity.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%201207[1996 c 230 § 1207]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c39.pdf?cite=1967%20ex.s.%20c%2039%20§%207[1967 ex.s. c 39 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c28.pdf?cite=1961%20c%2028%20§%205[1961 c 28 § 5]; ]

== 57.36.060 - Persons serving on both boards to hold only one position after merger.
A person who serves on the board of commissioners of a merging district and a merger district shall hold only one position on the board of commissioners of the merger district and shall only receive compensation, expenses, and benefits that are available to a single commissioner.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%201206[1996 c 230 § 1206]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c162.pdf?cite=1988%20c%20162%20§%204[1988 c 162 § 4]; ]

