= 57.42 - Disposition of property to public utility district.
:toc:

== 57.42.010 - Authorized.
Subject to the provisions of RCW 57.42.020 and 57.42.030, any district created under the provisions of this title may sell, transfer, exchange, lease or otherwise dispose of any property, real or personal, or property rights, including but not limited to the title to real property, to a public utility district in the same county on such terms as may be mutually agreed upon by the board of commissioners of each district.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%201301[1996 c 230 § 1301]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c56.pdf?cite=1973%201st%20ex.s.%20c%2056%20§%201[1973 1st ex.s. c 56 § 1]; ]

== 57.42.020 - Disposition must be in public interest—Filings—Indebtedness.
No district shall dispose of its property to a public utility district unless the respective board of commissioners of each district shall determine by resolution that such disposition is in the public interest and conducive to the public health, welfare, and convenience. Copies of each resolution, together with copies of the proposed disposition agreement, shall be filed with the legislative authority of the county in which the district is located and with the superior court of that county. Unless the proposed agreement provides otherwise, any outstanding indebtedness of any form owed by the water district shall remain the obligation of the area of the district, and the board of commissioners of the public utility district shall be empowered to make such levies, assessments, or charges upon that area or the water, sewer, or drainage users therein as shall pay off the indebtedness at maturity.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%201302[1996 c 230 § 1302]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c56.pdf?cite=1973%201st%20ex.s.%20c%2056%20§%202[1973 1st ex.s. c 56 § 2]; ]

== 57.42.030 - Hearing—Notice—Decree.
Within ninety days after the resolutions and proposed agreement have been filed with the court, the court shall fix a date for a hearing and shall direct that notice of the hearing be given by publication. After reviewing the proposed agreement and considering other evidence presented at the hearing, the court may determine by decree that the proposed disposition is in the public interest and conducive to the public health, welfare, and convenience. In addition, the decree shall authorize the payment of all or a portion of the indebtedness of the district relating to property disposed of under such decree. Pursuant to the court decree, the district shall dispose of its property under the terms of the disposition agreement with the public utility district.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6091-S.SL.pdf?cite=1996%20c%20230%20§%201303[1996 c 230 § 1303]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c56.pdf?cite=1973%201st%20ex.s.%20c%2056%20§%203[1973 1st ex.s. c 56 § 3]; ]

