= 88.08 - Specific acts prohibited.
:toc:

== 88.08.020 - Tampering with lights or signals.
Every person who, in such manner as might, if not discovered, endanger a vessel, railway engine, motor, train, or car, shall show, mask, extinguish, alter, or remove any light or signal, or exhibit any false light or signal, is guilty of a class B felony and shall be punished by imprisonment in a state correctional facility for not more than ten years.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20415[2003 c 53 § 415]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2263-S.SL.pdf?cite=1992%20c%207%20§%2062[1992 c 7 § 62]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20402[1909 c 249 § 402]; RRS § 2654; ]

== 88.08.030 - Bringing certain foreign convicts into state.
Every person who, being the master or commander of any vessel or boat arriving from a foreign country, shall knowingly bring into this state a person who has been or is a foreign convict of any offense, which, if committed in this state would be punishable under the laws thereof, shall be guilty of a misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20435[1909 c 249 § 435]; RRS § 2687; ]

== 88.08.050 - Injury to lighthouses or United States light.
Every person who shall willfully break, injure, deface, or destroy any lighthouse station, post, platform, step, lamp, or other structure pertaining to such lighthouse station, or shall extinguish or tamper with any light erected by the United States upon or along the navigable waters of this state to aid in the navigation thereof, in case no punishment is provided therefor by the laws of the United States, shall be punished:

. As a class B felony punishable by imprisonment in a state correctional facility for not more than ten years whenever such act may endanger the safety of any vessel navigating such waters, or jeopardize the safety of any person or property in or upon such vessel.

. In all other cases by imprisonment in the county jail for up to three hundred sixty-four days, or by a fine of not more than one thousand dollars, or by both.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5168-S.SL.pdf?cite=2011%20c%2096%20§%2058[2011 c 96 § 58]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20416[2003 c 53 § 416]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2263-S.SL.pdf?cite=1992%20c%207%20§%2063[1992 c 7 § 63]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20403[1909 c 249 § 403]; RRS § 2655; ]

== 88.08.060 - Unlicensed pilotage.
Every person not duly licensed thereto, who shall pilot or offer to pilot any vessel into, within or out of the waters of Juan de Fuca Strait or Puget Sound, shall be guilty of a misdemeanor: PROVIDED, That nothing herein shall prohibit a master of a vessel acting as his or her own pilot, nor compel a master or owner of any vessel to take out a pilot license for that purpose.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%20532[2013 c 23 § 532]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20293[1909 c 249 § 293]; RRS § 2545; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1888%20p%20177%20§%2018[1888 p 177 § 18]; ]

