= 88.01 - Boating offense compact.
:toc:

== 88.01.010 - Compact provisions.
The Boating Offense Compact is enacted into law and entered into on behalf of this state with all other states legally joining therein in a form substantially as follows:

ARTICLE I

Findings and Declaration of Policy

. The party states find that:

.. The safety of their waters is materially affected by the degree of compliance with state laws and local ordinances relating to the operation of boats;

.. Violation of such a law or ordinance is evidence that the violator engages in conduct which is likely to endanger the safety of persons and property;

. It is the policy of each of the party states to promote compliance with the laws, ordinances, and administrative rules and regulations relating to the operation of boats by their operators in each of the jurisdictions where such operators operate boats.

ARTICLE II

Definition

As used in this compact, "state" means a state that has entered into this compact.

ARTICLE III

Concurrent Jurisdiction

. If conduct is prohibited by two adjoining party states, courts and law enforcement officers in either state who have jurisdiction over boating offenses committed where waters form a common interstate boundary have concurrent jurisdiction to arrest, prosecute, and try offenders for the prohibited conduct committed anywhere on the boundary water between the two states.

. This compact does not authorize:

.. Prosecution of any person for conduct that is unlawful in the state where it was committed, but lawful in the other party state;

.. A prohibited conduct by the party state.

ARTICLE IV

Entry Into Force and Withdrawal

. This compact shall enter into force and become effective as to any state when it has enacted the same into law.

. Any party state may withdraw from this compact by enacting a statute repealing the same.

ARTICLE V

Construction and Severability

This compact shall be liberally construed so as to effectuate the purposes thereof. The provisions of this compact shall be severable and if any phrase, clause, sentence, or provision of this compact is declared to be contrary to the constitution of any party state or of the United States or the applicability thereof to any government, agency, person, or circumstance is held invalid, the validity of the remainder of this compact and the applicability thereof to any government, agency, person, or circumstance shall not be affected thereby. If this compact shall be held contrary to the constitution of any state party thereto, the compact shall remain in full force and effect as to the remaining states and in full force and effect as to the state affected as to all severable matters.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/6199.SL.pdf?cite=1992%20c%2033%20ยง%201[1992 c 33 ยง 1]; ]

