= 88.02 - Vessel registration.
:toc:

== 88.02.310 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Dealer" means a person, partnership, association, or corporation engaged in the business of selling vessels at wholesale or retail in this state.

. "Department" means the department of licensing.

. "Director" means the director of the department of licensing.

. "Owner" means a person who has a lawful right to possession of a vessel by purchase, exchange, gift, lease, inheritance, or legal action whether or not the vessel is subject to a security interest, and means registered owner where the reference to owner may be construed as either to registered or legal owner.

. "Person" has the same meaning as in RCW 46.04.405.

. "Vessel" means every watercraft used or capable of being used as a means of transportation on the water, other than a seaplane.

. "Waters of this state" means any waters within the territorial limits of this state as described in 43 U.S.C. Sec. 1312.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201001[2010 c 161 § 1001]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c7.pdf?cite=1983%20c%207%20§%2014[1983 c 7 § 14]; ]

== 88.02.320 - Department—Powers and duties.
The department:

. Shall provide for the issuance of vessel certificates of title and registration certificates;

. May appoint county auditors or other agents or subagents under chapter 46.01 RCW for collecting fees and issuing vessel registration certificates, numbers, and decals; and

. May adopt rules under chapter 34.05 RCW to implement this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201002[2010 c 161 § 1002]; ]

== 88.02.330 - Confidential vessel registrations—Rules.
. The department may issue confidential vessel registrations to units of local government and to agencies of the federal government for law enforcement purposes only.

. The department shall limit confidential vessel registrations owned or operated by the state of Washington or by any officer or employee of the state, to confidential, investigative, or undercover work of state law enforcement agencies.

. The director may adopt rules governing applications for and the use of confidential vessel registrations.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201003[2010 c 161 § 1003]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1704-S.SL.pdf?cite=1991%20c%20339%20§%2032[1991 c 339 § 32]; ]

== 88.02.340 - Inspection of registration certificates, out-of-state vessels.
. Any person charged with the enforcement of this chapter may inspect the registration certificate of a vessel to ascertain the legal and registered ownership of the vessel. A vessel owner or operator who fails to provide the registration certificate for inspection upon the request of any person charged with enforcement of this chapter may be found to be in violation of this chapter.

. The department may require the inspection of vessels that are brought into this state from another state and for which a certificate of title has not been issued and for any other vessel if the department determines that inspection of the vessel will help to verify the accuracy of the information set forth on the application.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1245-S.SL.pdf?cite=2013%20c%20291%20§%2030[2013 c 291 § 30]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201004[2010 c 161 § 1004]; ]

== 88.02.350 - Refunds, overpayments, and underpayments—Penalty for false statement.
. A person who has paid all or part of a vessel registration fee under this chapter is entitled to a refund if the amount was paid in error or if the vessel:

.. Was destroyed before the new registration period began;

.. Was permanently removed from Washington state before the new registration period began;

.. Registration was purchased after the owner sold the vessel;

.. Was registered in another jurisdiction after the Washington state registration had been purchased. Any full months of Washington state registration fees remaining after the application for out-of-state registration was made are refundable; or

.. Registration was purchased before the vessel was sold and before the new registration period began. The person who paid the fee must return the unused, never-affixed decals to the department before the new registration period begins.

. The department shall refund overpayments of registration fees and watercraft excise tax under chapter 82.49 RCW that are ten dollars or more. A request for a refund is not required.

. The department shall certify refunds to the state treasurer as correct and being claimed in the time required by law. The state treasurer shall mail or deliver the amount of each refund to the person who is entitled to the refund.

. The department shall not authorize refunds of fees paid in error unless the claim is filed with the director within three years after the fees were paid.

. If, due to error, the department, county auditor or other agent, or subagent appointed by the director has failed to collect the full amount of the registration fee and watercraft excise tax due, and the underpayment is in the amount of ten dollars or more, the department shall charge and collect the additional amount to constitute full payment of the tax and fee.

. Any person who makes a false statement under which he or she obtains a refund to which he or she is not entitled under this section is guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201005[2010 c 161 § 1005]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20413[2003 c 53 § 413]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5113.SL.pdf?cite=1997%20c%2022%20§%202[1997 c 22 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6489.SL.pdf?cite=1996%20c%2031%20§%202[1996 c 31 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c68.pdf?cite=1989%20c%2068%20§%205[1989 c 68 § 5]; ]

== 88.02.360 - Contaminated vessels.
. A local health officer may notify the department that a vessel has been:

.. Declared unfit and prohibited from use as authorized in chapter 64.44 RCW if the vessel has become contaminated as defined in RCW 64.44.010;

.. Satisfactorily decontaminated and the vessel has been retested according to the written work plan approved by the local health officer.

. The department shall brand vessel records and certificates of title when it receives the notification from a local health officer as provided in subsection (1) of this section.

. A person is guilty of a gross misdemeanor if he or she advertises for sale or sells a vessel that has been declared unfit and prohibited from use by a local health officer if:

.. The person has knowledge that the local health officer has issued an order declaring the vessel unfit and prohibiting its use; or

.. A notification has been placed on the certificate of title under subsection (2) of this section that the vessel has been declared unfit and prohibited from use.

. A person may advertise or sell a vessel if a release for reuse document has been issued by a local health officer under chapter 64.44 RCW or a notification has been placed on the certificate of title under subsection (2) of this section that the vessel has been decontaminated and released for reuse.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201016[2010 c 161 § 1016]; ]

== 88.02.370 - Five business-day notice—Vessel disposition or filing of report of sale.
. A vessel owner shall notify the department in writing within five business days after a vessel is or has been:

.. Sold;

.. Given as a gift to another person;

.. Traded, either privately or to a vessel dealer;

.. Donated to charity;

.. Turned over to an insurance company or wrecking yard; or

.. Disposed of.

. A report of sale is properly filed if it is received by the department within five business days after the date of sale or transfer and it includes:

.. The date of sale or transfer;

.. The owner's name and address;

.. The name and address of the person acquiring the vessel;

.. The vessel hull identification number and vessel registration number; and

.. A date stamp by the department showing it was received on or before the fifth business day after the date of sale or transfer.

. The department shall:

.. Provide or approve reports of sale forms;

.. Provide a system enabling a vessel owner to submit reports of sale electronically;

.. Immediately update the department's vessel record when a report of sale has been filed;

.. Provide instructions on release of interest forms that allow the seller of a vessel to release their interest in a vessel at the same time a financial institution, as defined in RCW 30A.22.040, releases its lien on the vessel; and

.. Send a report to the department of revenue that lists vessels for which a report of sale has been received but no transfer of ownership has taken place. The department shall send the report once each quarter.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2190.SL.pdf?cite=2015%20c%20148%20§%201[2015 c 148 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201014[2010 c 161 § 1014]; ]

== 88.02.375 - Ten-day notice—Owner name or address change or destruction, loss, etc. of vessel or registration certificate.
A vessel owner shall notify the department within ten days of any of the following:

. A change of name or address of the owner, as provided in RCW 46.08.195;

. Destruction, loss, abandonment, theft, or recovery of the vessel; or

. Loss or destruction of a valid registration certificate issued for the vessel.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1813-S.SL.pdf?cite=2017%20c%20147%20§%2011[2017 c 147 § 11]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201013[2010 c 161 § 1013]; ]

== 88.02.380 - Penalties—Disposition of moneys collected—Enforcement authority.
. Except as otherwise provided in this chapter, and, in part, in order to prevent the future potential dereliction or abandonment of a vessel, a violation of this chapter and the rules adopted by the department is a class 2 civil infraction.

. A civil infraction issued under this chapter must be processed under chapter 7.80 RCW.

. After the subtraction of court costs and administrative collection fees, moneys collected under this section must be credited to the ticketing jurisdiction and used only for the support of the enforcement agency, department, division, or program that issued the violation.

. All law enforcement officers may enforce this chapter and the rules adopted by the department within their respective jurisdictions. A city, town, or county may contract with a fire protection district for enforcement of this chapter, and fire protection districts may engage in enforcement activities.

. In order to prevent the future potential dereliction or abandonment of a vessel, derelict vessel removal program staff of the department of natural resources have authority to issue tickets by mail for the purpose of enforcing vessel registration requirements.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/6528-S2.SL.pdf?cite=2020%20c%20324%20§%205[2020 c 324 § 5]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1245-S.SL.pdf?cite=2013%20c%20291%20§%2029[2013 c 291 § 29]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201006[2010 c 161 § 1006]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1641.SL.pdf?cite=2006%20c%2029%20§%203[2006 c 29 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1318-S.SL.pdf?cite=1993%20c%20244%20§%204[1993 c 244 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c149.pdf?cite=1987%20c%20149%20§%2013[1987 c 149 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c183.pdf?cite=1984%20c%20183%20§%202[1984 c 183 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex2c3.pdf?cite=1983%202nd%20ex.s.%20c%203%20§%2050[1983 2nd ex.s. c 3 § 50]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c7.pdf?cite=1983%20c%207%20§%2022[1983 c 7 § 22]; ]

== 88.02.390 - Carbon monoxide warning sticker—Display required.
. The department shall:

.. Develop and approve a carbon monoxide warning sticker;

.. Approve a carbon monoxide warning sticker that has been approved by the United States coast guard for similar uses in other states;

.. Provide the carbon monoxide warning sticker when an application for a certificate of title is made and the ownership of the vessel is transferred between natural persons; and

.. Notify the new vessel owner described in (c) of this subsection that the carbon monoxide sticker must be affixed to the vessel as described in subsection (2) of this section.

. A new or used motor driven vessel, as defined in RCW 79A.60.010, other than a personal watercraft, as defined in RCW 79A.60.010, sold within this state must display a carbon monoxide warning sticker as provided in subsection (1) of this section.

. A vessel dealer shall ensure that a carbon monoxide warning sticker has been affixed to any vessel sold by the dealer before completing the sale.

. A carbon monoxide warning sticker already developed by a vessel manufacturer satisfies the requirements of this section if it has been approved by the department.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201024[2010 c 161 § 1024]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6364.SL.pdf?cite=2006%20c%20140%20§%202[2006 c 140 § 2]; ]

== 88.02.400 - Evasive registration and excise tax evasion—Penalty.
. It is a gross misdemeanor punishable as provided under chapter 9A.20 RCW for any person owning a vessel subject to taxation under chapter 82.49 RCW to:

.. Register a vessel in another state to avoid Washington state vessel excise tax required under chapter 82.49 RCW; or

.. Obtain a vessel dealer's license for the purpose of evading excise tax on vessels under chapter 82.49 RCW.

. For a second or subsequent offense, the person convicted is also subject to a fine equal to four times the amount of avoided taxes and fees, which may not be suspended, except as provided in RCW 10.05.180.

. Excise taxes owed and fines assessed must be deposited in the manner provided under RCW 46.16A.030(6).

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5362-S.SL.pdf?cite=2019%20c%20459%20§%205[2019 c 459 § 5]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5997-S.SL.pdf?cite=2019%20c%20423%20§%20205[2019 c 423 § 205]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201007[2010 c 161 § 1007]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20414[2003 c 53 § 414]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6467-S.SL.pdf?cite=2000%20c%20229%20§%206[2000 c 229 § 6]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5706-S.SL.pdf?cite=1999%20c%20277%20§%2010[1999 c 277 § 10]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1967-S.SL.pdf?cite=1996%20c%20184%20§%204[1996 c 184 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1127-S.SL.pdf?cite=1993%20c%20238%20§%204[1993 c 238 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c149.pdf?cite=1987%20c%20149%20§%207[1987 c 149 § 7]; ]

== 88.02.410 - Department and state immune from suit for administration of chapter.
A suit or action may not be commenced or prosecuted against the department or the state of Washington by reason of any act done or omitted to be done in the administration of the duties and responsibilities imposed upon the department under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201008[2010 c 161 § 1008]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c258.pdf?cite=1985%20c%20258%20§%2011[1985 c 258 § 11]; ]

== 88.02.420 - Moorage providers—Long-term moorage—Required information.
. A moorage provider that provides long-term moorage must obtain the following information and documentation from persons entering into long-term moorage agreements with the moorage provider:

.. The name of the legal owner of the vessel;

.. A local contact person and that person's address and telephone number, if different than the owner;

.. The owner's address and telephone number;

.. The vessel's hull identification number;

.. If applicable, the vessel's coast guard registration;

.. The vessel's home port;

.. The date on which the moorage began;

.. The vessel's country or state of registration and registration number; and

.. Proof of vessel registration, a written statement of the lessee's intent to register a vessel, or an affidavit in a form and manner approved by the department certifying that the vessel is exempt from state vessel registration requirements as provided by RCW 88.02.570.

. For moorage agreements entered into effective on or after July 1, 2014, a long-term moorage agreement for vessels not registered in this state must include, in a form and manner approved by the department and the department of revenue, notice of state vessel registration requirements as provided by this chapter and tax requirements as provided by chapters 82.08, 82.12, and 82.49 RCW and listing requirements as provided by RCW 84.40.065.

. A moorage provider must maintain records of the information and documents required under this section for at least two years. Upon request, a moorage provider must:

.. Permit any authorized agent of a requesting agency to:

... Inspect the moorage facility for vessels that are not registered as required by this chapter or listed as required under RCW 84.40.065; and

... Inspect and copy records identified in subsection (1) of this section for vessels that the requesting agency determines are not properly registered or listed as required by law; or

.. Provide to the requesting agency:

... Information as provided in subsection (1)(a), (c), (d), and (e) of this section; and

... Information as provided in subsection (1)(b), (f), (g), (h), and (i) of this section for those vessels that the requesting agency subsequently determines are not registered as required by this chapter or listed as required under RCW 84.40.065.

. Requesting agencies must coordinate their requests to ensure that a moorage provider does not receive more than two requests per calendar year. For the purpose of enforcing vessel registration and vessel listing requirements, requesting agencies may share the results of information requests with each other.

. The information required to be collected under this section must be collected at the time the long-term moorage agreement is entered into and at the time of any renewals of the agreement. The moorage provider is not responsible for updating any changes in the information that occurs after the initial agreement is entered into or in the time period between agreement renewals.

. The definitions in this subsection apply throughout this section unless the context clearly requires otherwise.

.. "Long-term moorage" means moorage provided for more than thirty consecutive days, unless the moorage is for a vessel that has been taken into custody under RCW 79.100.040.

.. "Moorage facility" means any properties or facilities located in this state that are used for the moorage of vessels and are owned or operated by a moorage provider.

.. "Moorage facility operator" has the same meaning as defined in RCW 53.08.310.

.. "Moorage provider" means any public or private entity that owns or operates any moorage facility, including a moorage facility operator, private moorage facility operator, the state of Washington, or any other person.

.. "Private moorage facility operator" has the same meaning as defined in RCW 88.26.010.

.. "Requesting agency" means the department, the department of revenue, or the department of natural resources.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2457-S2.SL.pdf?cite=2014%20c%20195%20§%20501[2014 c 195 § 501]; ]

== 88.02.430 - Disclosure of vessel owner records.
The disclosure of vessel owner records by the department of licensing is governed under RCW 46.12.630, 46.12.635, and 46.12.640.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1409.SL.pdf?cite=2016%20c%2080%20§%204[2016 c 80 § 4]; ]

== 88.02.500 - Certificate of title system—Intent.
It is the intention of the legislature:

. To establish a system of certificates of title for vessels similar to that in existence for motor vehicles under chapter 46.12 RCW;

. That certificates of title become sufficient evidence of ownership of the vessel it describes so that persons may rely upon that certificate; and

. That security interest in vessels be perfected solely by notation of a secured party upon the certificate of title.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201009[2010 c 161 § 1009]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c258.pdf?cite=1985%20c%20258%20§%201[1985 c 258 § 1]; ]

== 88.02.510 - Application—When, by whom.
. An application for a certificate of title must be made at the same time when a vessel is registered for the first time as required under this chapter.

. A person who purchases or otherwise obtains majority ownership of any vessel subject to this chapter shall, within fifteen days of purchase or obtainment, apply for a new certificate of title that shows the vessel's change of ownership.

. This section does not apply to a vessel that has a valid marine document as a vessel of the United States.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201011[2010 c 161 § 1011]; ]

== 88.02.515 - Application—Form and contents.
. The application for a certificate of title of a vessel must be made by the owner or the owner's representative to the department, county auditor or other agent, or subagent appointed by the director on a form furnished or approved by the department and must contain:

.. A description of the vessel, including make, model, hull identification number, and type of body;

.. The name and address of the person who is to be the registered owner of the vessel and, if the vessel is subject to a security interest, the name and address of the secured party; and

.. Other information the department may require.

. The application for a certificate of title must be signed by the person applying to be the registered owner and be sworn to by that person under penalty of the perjury laws of this state that:

.. The applicant is the owner or an authorized agent of the owner of the vessel; and

.. The vessel is free of any claim of lien, mortgage, conditional sale, or other security interest of any person except the person or persons on the application as secured parties.

. The application for a certificate of title must be accompanied by:

.. A draft, money order, certified bank check, or cash for all fees and taxes due for the application for the certificate of title; and

.. The most recent certificate of title or other satisfactory evidence of ownership.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201012[2010 c 161 § 1012]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c258.pdf?cite=1985%20c%20258%20§%206[1985 c 258 § 6]; ]

== 88.02.520 - Security interests.
. Security interests in vessels subject to the requirements of this chapter must be perfected only by indication upon the vessel's certificate of title. The provisions of chapters 46.12 and * 46.16 RCW relating to vehicle registration certificates, certificates of title, certificate issuance, ownership transfer, and perfection of security interests, and other provisions that may be applied to vessels subject to this chapter, may be so applied by rule of the department if they are not inconsistent with this chapter.

. Security interests may be released or acted upon as provided by the law under which they arose or were perfected. A new security interest or renewal or extension of an existing security interest is not affected except as provided under the terms of this chapter and **RCW 46.12.095.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201010[2010 c 161 § 1010]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6476.SL.pdf?cite=1996%20c%20315%20§%205[1996 c 315 § 5]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1704-S.SL.pdf?cite=1991%20c%20339%20§%2031[1991 c 339 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c258.pdf?cite=1985%20c%20258%20§%204[1985 c 258 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex2c3.pdf?cite=1983%202nd%20ex.s.%20c%203%20§%2046[1983 2nd ex.s. c 3 § 46]; ]

== 88.02.530 - Duplicate certificates of title.
. A legal owner or the legal owner's authorized representative shall promptly apply for a duplicate certificate of title if a certificate of title is lost, stolen, mutilated, or destroyed, or becomes illegible. The application for a duplicate certificate of title must:

.. Include information required by the department;

.. Be accompanied by an affidavit of loss or destruction;

.. Be accompanied by the fee required in *RCW 88.02.640(1)(k).

. The duplicate certificate of title must contain the word "duplicate." It must be mailed to the first priority secured party named in it or, if none, to the registered owner.

. A person recovering a certificate of title for which a duplicate has been issued shall promptly return the certificate of title that has been recovered to the department.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%20127[2011 c 171 § 127]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201015[2010 c 161 § 1015]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1457.SL.pdf?cite=1997%20c%20241%20§%2012[1997 c 241 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c71.pdf?cite=1986%20c%2071%20§%201[1986 c 71 § 1]; ]

== 88.02.540 - Quick title—Application requirements—Subagents.
. The application for a quick title of a vessel must be made by the owner or the owner's representative to the department, participating county auditor or other agent, or subagent appointed by the director on a form furnished or approved by the department and must contain:

.. A description of the vessel, including make, model, hull identification number, series, and body;

.. The name and address of the person who is to be the registered owner of the vessel and, if the vessel is subject to a security interest, the name and address of the secured party; and

.. Other information as may be required by the department.

. The application for a quick title must be signed by the person applying to be the registered owner and be sworn to by that person in the manner described under chapter 5.50 RCW. The department must keep a copy of the application.

. The application for a quick title must be accompanied by:

.. All fees and taxes due for an application for a certificate of title, including a quick title service fee under RCW 88.02.640(1); and

.. The most recent certificate of title or other satisfactory evidence of ownership.

. All applications for quick title must meet the requirements established by the department.

. For the purposes of this section, "quick title" means a certificate of title printed at the time of application.

. A subagent may process a quick title under this section only after (a) the department has instituted a process in which blank certificates of title can be inventoried; (b) the county auditor of the county in which the subagent is located has processed quick titles for a minimum of six months; and (c) the county auditor approves a request from a subagent in its county to process quick titles.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5017-S.SL.pdf?cite=2019%20c%20232%20§%2027[2019 c 232 § 27]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1046-S.SL.pdf?cite=2011%20c%20326%20§%204[2011 c 326 § 4]; ]

== 88.02.550 - Registration and display of registration number and decal required—Exemptions.
. Except as provided in this chapter, a person may not own or operate any vessel, including a rented vessel, on the waters of this state unless the vessel has been registered and displays a registration number and a valid decal in accordance with this chapter. A vessel that has or is required to have a valid marine document as a vessel of the United States is only required to display a valid decal. 

. A vessel numbered in this state under the federal boat safety act of 1971 (85 Stat. 213, 46 U.S.C. 4301 et seq.) is not required to be registered under this chapter until the certificate of number issued for the vessel under the federal boat safety act expires. When registering under this chapter, this type of vessel is subject to the amount of excise tax due under chapter 82.49 RCW that would have been due under chapter 82.49 RCW if the vessel had been registered at the time otherwise required under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1245-S.SL.pdf?cite=2013%20c%20291%20§%2031[2013 c 291 § 31]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201017[2010 c 161 § 1017]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1641.SL.pdf?cite=2006%20c%2029%20§%201[2006 c 29 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c267.pdf?cite=1985%20c%20267%20§%201[1985 c 267 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex2c3.pdf?cite=1983%202nd%20ex.s.%20c%203%20§%2047[1983 2nd ex.s. c 3 § 47]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c7.pdf?cite=1983%20c%207%20§%2015[1983 c 7 § 15]; ]

== 88.02.560 - Application—Form and contents—Registration number and decal—Renewals—Marine oil refuse dump and holding tank information—Transfer.
. An application for a vessel registration must be made by the owner or the owner's authorized representative to the department, county auditor or other agent, or subagent appointed by the director on a form furnished or approved by the department. The application must contain:

.. The name and address of each owner of the vessel;

.. Other information the department may require; and

.. The signature of at least one owner.

. The application for vessel registration must be accompanied by the:

.. Vessel registration fee required under RCW 88.02.640(1)(k);

.. Derelict vessel and invasive species removal fee under RCW 88.02.640(1)(b) and derelict vessel removal surcharge required under RCW 88.02.640(1)(c);

.. Filing fee required under RCW 88.02.640(1)(f);

.. License plate technology fee required under RCW 88.02.640(1)(g);

.. License service fee required under RCW 88.02.640(1)(h);

.. Watercraft excise tax required under chapter 82.49 RCW; and

.. Beginning January 1, 2016, service fee required under RCW 46.17.040.

. Upon receipt of an application for vessel registration and the required fees and taxes, the department shall assign a registration number and issue a decal for each vessel. The registration number and decal must be issued and affixed to the vessel in a manner prescribed by the department consistent with the standard numbering system for vessels required in 33 C.F.R. Part 174. A valid decal affixed as prescribed must indicate compliance with the annual registration requirements of this chapter.

. Vessel registrations and decals are valid for a period of one year, except that the director may extend or diminish vessel registration periods and vessel decals for the purpose of staggered renewal periods. For registration periods of more or less than one year, the department may collect prorated annual registration fees and excise taxes based upon the number of months in the registration period.

. Vessel registrations are renewable every year in a manner prescribed by the department upon payment of the fees and taxes described in subsection (2) of this section. Upon renewing a vessel registration, the department shall issue a new decal to be affixed as prescribed by the department.

. When the department issues either a notice to renew a vessel registration or a decal for a new or renewed vessel registration, it shall also provide information on the location of marine oil recycling tanks and sewage holding tank pumping stations. This information must be provided to the department by the state parks and recreation commission in a form ready for distribution. The form must be developed and prepared by the state parks and recreation commission with the cooperation of the department of ecology. The department, the state parks and recreation commission, and the department of ecology shall enter into a memorandum of agreement to implement this process.

. A person acquiring a vessel from a dealer or a vessel already validly registered under this chapter shall, within fifteen days of the acquisition or purchase of the vessel, apply to the department, county auditor or other agent, or subagent appointed by the director for transfer of the vessel registration, and the application must be accompanied by a transfer fee as required in RCW 88.02.640(1)(o).

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5987-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2044%20§%20215[2015 3rd sp.s. c 44 § 215]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%20129[2011 c 171 § 129]; 2011 c 171 § 128; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201020[2010 c 161 § 1020]; 2010 c 161 § 1019; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/6044-S2.SL.pdf?cite=2007%20c%20342%20§%206[2007 c 342 § 6]; 2007 c 342 § 5; 2005 c 464 § 2; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2376-S.SL.pdf?cite=2002%20c%20286%20§%2013[2002 c 286 § 13]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1318-S.SL.pdf?cite=1993%20c%20244%20§%2038[1993 c 244 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c17.pdf?cite=1989%20c%2017%20§%201[1989 c 17 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex2c3.pdf?cite=1983%202nd%20ex.s.%20c%203%20§%2045[1983 2nd ex.s. c 3 § 45]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c7.pdf?cite=1983%20c%207%20§%2018[1983 c 7 § 18]; ]

== 88.02.570 - Exemptions. (Effective until July 1, 2026.)
Vessel registration is required under this chapter except for the following:

. A military vessel owned by the United States government;

. A public vessel owned by the United States government, unless the vessel is a type used for recreation;

. A vessel clearly identified as being:

.. Owned by a state, county, or city; and

.. Used primarily for governmental purposes;

. A vessel either (a) registered or numbered under the laws of a country other than the United States or (b) having a valid United States customs service cruising license issued pursuant to 19 C.F.R. Sec. 4.94. Either vessel is exempt from registration only for the first sixty days of use on Washington state waters. On or before the sixty-first day of use on Washington state waters, any vessel in the state under this subsection must obtain a vessel visitor permit as required under RCW 88.02.610;

. A vessel that is currently registered or numbered under the laws of the state of principal operation or that has been issued a valid number under federal law. However, either vessel must be registered in Washington state if the state of principal operation changes to Washington state by the sixty-first day after the vessel arrives in Washington state;

. [Empty]
.. A vessel owned by a nonresident if:

... The vessel is located upon the waters of this state exclusively for repairs, alteration, or reconstruction, or any testing related to these services;

... An employee of the facility providing these services is on board the vessel during any testing; and

... The nonresident files an affidavit with the department of revenue by the sixty-first day verifying that the vessel is located upon the waters of this state for these services.

.. The nonresident must continue to file an affidavit every sixty days thereafter, as long as the vessel is located upon the waters of this state exclusively for repairs, alteration, reconstruction, or testing;

. A vessel equipped with propulsion machinery of less than ten horsepower that:

.. Is owned by the owner of a vessel for which a valid vessel number has been issued;

.. Displays the number of that numbered vessel followed by the suffix "1" in the manner prescribed by the department; and

.. Is used as a tender for direct transportation between the numbered vessel and the shore and for no other purpose;

. A vessel under sixteen feet in overall length that has no propulsion machinery of any type or that is not used on waters subject to the jurisdiction of the United States or on the high seas beyond the territorial seas for vessels owned in the United States and are powered by propulsion machinery of ten or less horsepower;

. A vessel with no propulsion machinery of any type for which the primary mode of propulsion is human power;

. A vessel primarily engaged in commerce that has or is required to have a valid marine document as a vessel of the United States. A commercial vessel that the department of revenue determines has the external appearance of a vessel that would otherwise be required to register under this chapter, must display decals issued annually by the department of revenue that indicate the vessel's exempt status;

. A vessel primarily engaged in commerce that is owned by a resident of a country other than the United States;

. A vessel owned by a nonresident person brought into the state for use or enjoyment while temporarily within the state for not more than six months in any continuous twelve-month period that (a) is currently registered or numbered under the laws of the state of principal use or (b) has been issued a valid number under federal law. This type of vessel is exempt from registration only for the first sixty days of use on Washington state waters. On or before the sixty-first day of use on Washington state waters, any vessel under this subsection must obtain a nonresident vessel permit as required under RCW 88.02.620;

. A vessel used in this state by a nonresident individual possessing a valid use permit issued under RCW 82.08.700 or 82.12.700;

. A vessel held for sale by any licensed dealer; and

. A vessel with propulsion machinery that draws two hundred fifty watts or less and propels the vessel no faster than ten miles per hour and is not used on waters subject to the jurisdiction of the United States or on the high seas beyond the territorial seas for vessels owned in the United States.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6120-S.SL.pdf?cite=2016%20c%20114%20§%202[2016 c 114 § 2]; 2016 c 114 § 1; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6057-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%206%20§%20804[2015 3rd sp.s. c 6 § 804]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201018[2010 c 161 § 1018]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1002-S.SL.pdf?cite=2007%20c%2022%20§%203[2007 c 22 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2376-S.SL.pdf?cite=2002%20c%20286%20§%2012[2002 c 286 § 12]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6603-S.SL.pdf?cite=1998%20c%20198%20§%201[1998 c 198 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5513-S.SL.pdf?cite=1997%20c%2083%20§%201[1997 c 83 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1704-S.SL.pdf?cite=1991%20c%20339%20§%2030[1991 c 339 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c393.pdf?cite=1989%20c%20393%20§%2013[1989 c 393 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c102.pdf?cite=1989%20c%20102%20§%201[1989 c 102 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c452.pdf?cite=1985%20c%20452%20§%201[1985 c 452 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c250.pdf?cite=1984%20c%20250%20§%202[1984 c 250 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex2c3.pdf?cite=1983%202nd%20ex.s.%20c%203%20§%2044[1983 2nd ex.s. c 3 § 44]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c7.pdf?cite=1983%20c%207%20§%2016[1983 c 7 § 16]; ]

== 88.02.580 - Voluntary donations—Maritime historic restoration and preservation.
The department shall provide an opportunity for each person registering a vessel under this chapter to make a voluntary donation to support the maritime historic restoration and preservation activities of the Grays Harbor Historical Seaport and the Steamer Virginia V Foundation. All voluntary donations collected under this section must be deposited in the maritime historic restoration and preservation account created under RCW 88.02.660.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201023[2010 c 161 § 1023]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2509-S.SL.pdf?cite=1996%20c%203%20§%201[1996 c 3 § 1]; ]

== 88.02.590 - Duplicate registration certificates.
. A registered owner or the registered owner's authorized representative shall promptly apply for a duplicate registration certificate when a registration certificate is lost, stolen, mutilated, or destroyed, or becomes illegible. The application for a duplicate registration certificate must:

.. Be accompanied by an affidavit of loss or destruction;

.. Include information required by the department; and

.. Be accompanied by the fee required in *RCW 88.02.640(1)(d), in addition to any other fees or taxes required for the transaction.

. A person recovering a registration certificate for which a duplicate has been issued shall promptly return the registration certificate that has been recovered to the department.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%20130[2011 c 171 § 130]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201021[2010 c 161 § 1021]; ]

== 88.02.595 - Replacement decals.
. A registered owner or the registered owner's authorized representative shall promptly apply for a pair of replacement decals when the decals are lost, stolen, mutilated, or destroyed, or become illegible. The application for replacement decals must:

.. Be accompanied by an affidavit of loss or destruction;

.. Include information required by the department;

.. Be accompanied by the fee required in *RCW 88.02.640(1)(j), in addition to any other fees or taxes required for the transaction.

. A person recovering decals for which a replacement has been issued shall promptly return the decals that have been recovered to the department.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%20131[2011 c 171 § 131]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201022[2010 c 161 § 1022]; ]

== 88.02.600 - Carbon monoxide poisoning informational brochure.
The department shall include an informational brochure about the dangers of carbon monoxide poisoning and vessels and the warning stickers required under RCW 88.02.390 as part of the registration materials mailed by the department for two consecutive years for registrations that are due or become due on or after January 1, 2007, upon recommendation by the director. The materials must instruct the vessel owner to affix the stickers as required under RCW 88.02.390.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201025[2010 c 161 § 1025]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6364.SL.pdf?cite=2006%20c%20140%20§%203[2006 c 140 § 3]; ]

== 88.02.610 - Vessel visitor permit.
. A vessel owner shall apply for a vessel visitor permit if the vessel is:

.. Currently registered or numbered under the laws of a country other than the United States or has a valid United States customs service cruising license issued under 19 C.F.R. Sec. 4.94; and

.. Being used on Washington state waters for the personal use of the owner for more than sixty days.

. A vessel visitor permit:

.. May be obtained from the department, county auditor or other agent, or subagent appointed by the director;

.. Must show the date the vessel first came into Washington state; and

.. Is valid as long as the vessel remains currently registered or numbered under the laws of a country other than the United States or the United States customs service cruising license remains valid.

. The department, county auditor or other agent, or subagent appointed by the director shall collect the fee required in *RCW 88.02.640(1)(m) when issuing a vessel visitor permit.

. The department shall adopt rules to implement this section, including rules on issuing and displaying the vessel visitor permit.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%20132[2011 c 171 § 132]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201026[2010 c 161 § 1026]; ]

== 88.02.620 - Nonresident vessel permit. (Effective until July 1, 2026.)
. A vessel owner who is a nonresident person must obtain a nonresident vessel permit on or before the sixty-first day of use in Washington state if the vessel:

.. Is currently registered or numbered under the laws of the state of principal operation or has been issued a valid number under federal law; and

.. Has been brought into Washington state for personal use for not more than six months in any continuous twelve-month period.

. In addition to the requirements in subsection (1) of this section, a nonresident vessel owner that is not a natural person may only obtain a nonresident vessel permit if:

.. The vessel is at least thirty feet in length, but no more than one hundred sixty-four feet in length;

.. No Washington state resident is a principal, as defined in RCW 82.32.865, of the nonresident person; and

.. The department of revenue has provided the nonresident vessel owner written approval authorizing the permit as provided in RCW 82.32.865.

. A nonresident vessel permit:

.. May be obtained from the department, county auditor or other agent, or subagent appointed by the director;

.. Must show the date the vessel first came into Washington state;

.. Is valid for two months; and

.. May not be issued after December 31, 2025, to a nonresident vessel owner that is not a natural person.

. The department, county auditor or other agent, or subagent appointed by the director must collect the fee required in RCW 88.02.640(1)(i) when issuing nonresident vessel permits.

. A nonresident vessel permit is not required under this section if the vessel is used in conducting temporary business activity within Washington state.

. For any permits issued under this section to a nonresident vessel owner that is not a natural person, the department must maintain a record of the following information and provide it to the department of revenue quarterly or as otherwise mutually agreed to by the department and department of revenue:

.. The name of the record owner of the vessel;

.. The vessel's hull identification number;

.. The amount of the fee paid under RCW 88.02.640(5);

.. The date the vessel first entered the waters of this state;

.. The expiration date for the permit; and

.. Any other information mutually agreed to by the department and department of revenue.

. The department must adopt rules to implement this section, including rules on issuing and displaying the nonresident vessel permit.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6057-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%206%20§%20802[2015 3rd sp.s. c 6 § 802]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%20133[2011 c 171 § 133]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201027[2010 c 161 § 1027]; ]

== 88.02.640 - Fees by type—Disposition, distribution. (Effective until January 1, 2026.)
. In addition to any other fees and taxes required by law, the department, county auditor or other agent, or subagent appointed by the director must charge the following vessel fees and surcharge:

FEEAMOUNTAUTHORITYDISTRIBUTION(a) Dealer temporary permit$5.00RCW 88.02.800(2)General fund(b) Derelict vessel and invasive species removalSubsection (3) of this sectionSubsection (3) of this sectionSubsection (3) of this section(c) Derelict vessel removal surcharge$1.00Subsection (4) of this sectionSubsection (4) of this section(d) Duplicate certificate of title$1.25RCW 88.02.530(1)(c)General fund(e) Duplicate registration$1.25RCW 88.02.590(1)(c)General fund(f) FilingRCW 46.17.005RCW 88.02.560(2)RCW 46.68.400(g) License plate technologyRCW 46.17.015RCW 88.02.560(2)RCW 46.68.370(h) License serviceRCW 46.17.025RCW 88.02.560(2)RCW 46.68.220(i) Nonresident vessel permitSubsection (5) of this sectionRCW 88.02.620(4)Subsection (5) of this section(j) Quick title service$50.00RCW 88.02.540(3)Subsection (7) of this section(k) Registration$10.50RCW 88.02.560(2)RCW 88.02.650(l) Replacement decal$1.25RCW 88.02.595(1)(c)General fund(m) Service feeRCW 46.17.040RCW 88.02.515 and 88.02.560(2)RCW 46.17.040(n) Title application$5.00RCW 88.02.515General fund(o) Transfer$1.00RCW 88.02.560(7)General fund(p) Vessel visitor permit$30.00RCW 88.02.610(3)Subsection (6) of this section

FEE

AMOUNT

AUTHORITY

DISTRIBUTION

.. Dealer temporary permit

$5.00

RCW 88.02.800(2)

General fund

.. Derelict vessel and invasive species removal

Subsection (3) of this section

Subsection (3) of this section

Subsection (3) of this section

.. Derelict vessel removal surcharge

$1.00

Subsection (4) of this section

Subsection (4) of this section

.. Duplicate certificate of title

$1.25

RCW 88.02.530(1)(c)

General fund

.. Duplicate registration

$1.25

RCW 88.02.590(1)(c)

General fund

.. Filing

RCW 46.17.005

RCW 88.02.560(2)

RCW 46.68.400

.. License plate technology

RCW 46.17.015

RCW 88.02.560(2)

RCW 46.68.370

.. License service

RCW 46.17.025

RCW 88.02.560(2)

RCW 46.68.220

.. Nonresident vessel permit

Subsection (5) of this section

RCW 88.02.620(4)

Subsection (5) of this section

.. Quick title service

$50.00

RCW 88.02.540(3)

Subsection (7) of this section

.. Registration

$10.50

RCW 88.02.560(2)

RCW 88.02.650

.. Replacement decal

$1.25

RCW 88.02.595(1)(c)

General fund

.. Service fee

RCW 46.17.040

RCW 88.02.515 and 88.02.560(2)

RCW 46.17.040

.. Title application

$5.00

RCW 88.02.515

General fund

.. Transfer

$1.00

RCW 88.02.560(7)

General fund

.. Vessel visitor permit

$30.00

RCW 88.02.610(3)

Subsection (6) of this section

. The five dollar dealer temporary permit fee required in subsection (1) of this section must be credited to the payment of registration fees at the time application for registration is made.

. The derelict vessel and invasive species removal fee required in subsection (1) of this section is five dollars and must be distributed as follows:

.. Two dollars must be deposited in the aquatic invasive species management account created in RCW 77.135.200;

.. One dollar must be deposited into the aquatic algae control account created in RCW 43.21A.667; and

.. Two dollars must be deposited in the derelict vessel removal account created in RCW 79.100.100.

. In addition to other fees required in this section, an annual derelict vessel removal surcharge of one dollar must be charged with each vessel registration. The surcharge is to address the significant backlog of derelict vessels accumulated in Washington waters that pose a threat to the health and safety of the people and to the environment and must be deposited into the derelict vessel removal account created in RCW 79.100.100.

. [Empty]
.. The amount of the nonresident vessel permit fee is:

... For a vessel owned by a nonresident natural person, twenty-five dollars; and

... For a nonresident vessel owner that is not a natural person, the fee is equal to:

(A) Twenty-five dollars per foot for vessels between thirty and ninety-nine feet in length;

(B) Thirty dollars per foot for vessels between one hundred and one hundred twenty feet in length; and

(C) Thirty-seven dollars and fifty cents per foot for vessels between one hundred twenty-one and one hundred sixty-four feet in length. The fee must be multiplied by the extreme length of the vessel in feet, rounded up to the nearest whole foot.

.. The fee must be paid by the vessel owner to the department. Any moneys remaining from the fee after the payment of costs to administer the permit must be allocated to counties by the state treasurer for approved boating safety programs under RCW 88.02.650.

.. A nonresident vessel owner that is not a natural person may not obtain more than two nonresident vessel permits under RCW 88.02.620 within any thirty-six month period.

. The thirty dollar vessel visitor permit fee must be distributed as follows:

.. Five dollars must be deposited in the derelict vessel removal account created in RCW 79.100.100;

.. The department may keep an amount to cover costs for providing the vessel visitor permit;

.. Any moneys remaining must be allocated to counties by the state treasurer for approved boating safety programs under RCW 88.02.650; and

.. Any fees required for licensing agents under RCW 46.17.005 are in addition to any other fee or tax due for the titling and registration of vessels.

. [Empty]
.. The fifty dollar quick title service fee must be distributed as follows:

... If the fee is paid to the director, the fee must be deposited to the general fund.

... If the fee is paid to the participating county auditor or other agent appointed by the director, twenty-five dollars must be deposited to the general fund. The remainder must be retained by the county treasurer in the same manner as other fees collected by the county auditor.

... If the fee is paid to a subagent appointed by the director, twenty-five dollars must be deposited to the general fund. The remaining twenty-five dollars must be distributed as follows: Twelve dollars and fifty cents must be retained by the county treasurer in the same manner as other fees collected by the county auditor and twelve dollars and fifty cents must be retained by the subagent.

.. For the purposes of this subsection, "quick title" has the same meaning as in RCW 88.02.540.

. The department, county auditor or other agent, or subagent appointed by the director shall charge the service fee under subsection (1)(m) of this section beginning January 1, 2016.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5303-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%2017%20§%20104[2017 3rd sp.s. c 17 § 104]; 2017 3rd sp.s. c 17 § 103; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5987-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2044%20§%20216[2015 3rd sp.s. c 44 § 216]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6057-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%206%20§%20803[2015 3rd sp.s. c 6 § 803]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1157-S.SL.pdf?cite=2015%202nd%20sp.s.%20c%201%20§%202[2015 2nd sp.s. c 1 § 2]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1245-S.SL.pdf?cite=2013%20c%20291%20§%201[2013 c 291 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2660.SL.pdf?cite=2012%20c%2074%20§%2016[2012 c 74 § 16]; prior:  2011 c 326 § 5; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%20134[2011 c 171 § 134]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5036-S.SL.pdf?cite=2011%20c%20169%20§%201[2011 c 169 § 1]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201028[2010 c 161 § 1028]; ]

== 88.02.650 - Deposit of fees in general fund—Allocation for boating safety and education and law enforcement purposes.
. General fees for vessel registrations collected by the director must be deposited in the general fund. Except as provided in subsection (2) of this section, any amount above one million one hundred thousand dollars per fiscal year must be allocated to counties by the state treasurer for boating safety/education and law enforcement programs. Eligibility for boating safety/education and law enforcement program allocations is contingent upon approval of the local boating safety program by the state parks and recreation commission. Fund allocation must be based on the numbers of registered vessels by county of moorage. Each benefiting county is responsible for equitable distribution of such allocation to other jurisdictions with approved boating safety programs within the county. Any fees not allocated to counties due to the absence of an approved boating safety program must be allocated to the state parks and recreation commission for awards to local governments to offset law enforcement and boating safety impacts of boaters recreating in jurisdictions other than where registered. Jurisdictions receiving funds under this section shall deposit the funds into an account dedicated solely for supporting the jurisdiction's boating safety programs. These funds may not replace existing local funds used for boating safety programs.

. During the 2015-2017 fiscal biennium, if 2015 *Engrossed Senate Bill No. 5416 is enacted before August 1, 2015, any amount above one million three hundred fifty thousand dollars per fiscal year must be allocated to counties by the state treasurer for boating safety, education, and law enforcement programs.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6052-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%204%20§%20979[2015 3rd sp.s. c 4 § 979]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5061.SL.pdf?cite=2011%20c%20171%20§%20135[2011 c 171 § 135]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201029[2010 c 161 § 1029]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2376-S.SL.pdf?cite=2002%20c%20286%20§%2014[2002 c 286 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c393.pdf?cite=1989%20c%20393%20§%2012[1989 c 393 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c7.pdf?cite=1983%20c%207%20§%2017[1983 c 7 § 17]; ]

== 88.02.660 - Maritime historic restoration and preservation account.
. The maritime historic restoration and preservation account is created in the custody of the state treasurer. All receipts from the voluntary donations made simultaneously with the registration of vessels under this chapter must be deposited into this account. These deposits are not public funds and are not subject to allotment procedures under chapter 43.88 RCW.

. At the end of each fiscal year, the state treasurer shall pay from this account to the department an amount equal to the reasonable administrative expenses of that agency for that fiscal year for collecting the voluntary donations and transmitting them to the state treasurer and shall pay to the state treasurer an amount equal to the reasonable administrative expenses of that agency for that fiscal year for maintaining the account and disbursing funds from the account.

. At the end of each fiscal year, the state treasurer shall pay one-half of the balance of the funds in the account after payment of the administrative costs provided in subsection (2) of this section, to the Grays Harbor historical seaport or its corporate successor and the remainder to the Steamer Virginia V foundation or its corporate successor.

. If either the Grays Harbor historical seaport and its corporate successors or the Steamer Virginia V foundation and its corporate successors legally ceases to exist, the state treasurer shall, at the end of each fiscal year, pay the balance of the funds in the account to the remaining organization.

. If both the Grays Harbor historical seaport and its corporate successors and the Steamer Virginia V foundation and its corporate successors legally cease to exist, the department shall discontinue the collection of the voluntary donations in conjunction with the registration of vessels under RCW 88.02.580, and the balance of the funds in the account escheat to the state. If funds in the account escheat to the state, one-half of the fund balance must be provided to the department of archaeology and historic preservation, and the remainder must be deposited into the parks renewal and stewardship account.

. The secretary of state, the directors of the state historical societies, the director of the department of archaeology and historic preservation within the department of commerce, and two members representing the recreational boating community appointed by the secretary of state, shall review the success of the voluntary donation program for maritime historic restoration and preservation established under RCW 88.02.580.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201031[2010 c 161 § 1031]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2509-S.SL.pdf?cite=1996%20c%203%20§%202[1996 c 3 § 2]; ]

== 88.02.710 - Requirements—Surety bond—Fees.
. Each vessel dealer in this state shall:

.. Obtain a vessel dealer license from the department in a manner prescribed by the department in accordance with rules adopted under chapter 34.05 RCW;

.. File a surety bond in the amount of five thousand dollars, running to the state of Washington. The surety bond must be:

... Issued by a surety company authorized to do business in the state of Washington;

... Approved by the attorney general as to form; and

... Conditioned that the vessel dealer shall conduct business as required under this chapter; and

.. Pay the vessel dealer license and vessel dealer display decal fees as provided by rules adopted by the department. All vessel dealer license and vessel dealer display decal fees collected under this section must be deposited with the state treasurer and credited to the general fund.

. A vessel dealer selling fewer than sixteen vessels per year having a retail value of no more than two thousand dollars each is not required to file a bond as provided in subsection (1)(b) of this section.

. The director shall establish by rule vessel dealer license and vessel dealer display decal fees at a sufficient level to defray the costs of administering the vessel dealer license program.

. The department shall issue vessel dealer licenses with staggered annual expiration dates when:

.. The completed vessel dealer application has been satisfactorily filed;

.. The department determines that the applicant is eligible as determined by department rules; and

.. No denial proceeding is in effect.

. A vessel consignor or purchaser who has suffered any loss or damage by reason of an act or omission by a vessel dealer that constitutes a violation of this chapter may institute an action for recovery against the vessel dealer and the surety upon the bond. Successive recoveries against the bond are permitted, but the aggregate liability of the surety to all persons may not exceed the amount of the bond. Upon exhaustion of the penalty of the bond or cancellation of the bond by the surety, the vessel dealer license must automatically be deemed canceled.

. Vessel dealer license numbers are not transferable.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201032[2010 c 161 § 1032]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c149.pdf?cite=1987%20c%20149%20§%201[1987 c 149 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c7.pdf?cite=1983%20c%207%20§%2019[1983 c 7 § 19]; ]

== 88.02.720 - Exemptions.
. The department may exempt from compliance with the vessel dealer requirements of this chapter, any person who is engaged in the business of selling in this state at wholesale or retail, human-powered watercraft that is: (a) Under sixteen feet in length; (b) unable to be powered by propulsion machinery or wind propulsion as designed by the manufacturer; and (c) not designed for use on commonly-used navigable waters.

. Any person engaged in the business of selling at wholesale or retail, exempt and nonexempt watercraft under this section is only required to comply with this chapter in regard to the sale of nonexempt watercraft.

. An auction company licensed under chapter 18.11 RCW and licensed as a motor vehicle dealer under chapter 46.70 RCW may sell at auction, without being licensed as a vessel dealer, all vessels that a vessel dealer is authorized to sell, so long as the sale of vessels is incidental to the auction company's primary source of business and the length of any vessel being sold is no greater than twenty-five feet. The auction company shall comply with all other vessel dealer requirements of this chapter and rules adopted by the department if the vessel dealer license fees and surety bond requirements in RCW 88.02.710 are determined to not be due.

. A broker licensed under chapter 18.85 RCW may sell, without being licensed as a vessel dealer, floating on-water residences, as defined in RCW 90.58.270.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1309.SL.pdf?cite=2015%20c%20133%20§%202[2015 c 133 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201033[2010 c 161 § 1033]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5112-S.SL.pdf?cite=2007%20c%20378%20§%201[2007 c 378 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c250.pdf?cite=1990%20c%20250%20§%2090[1990 c 250 § 90]; ]

== 88.02.730 - Business address—Office—Identification of business.
. A vessel dealer must have and maintain an office in which to conduct business at the business address of the dealer.

. The vessel dealer's place of business must be identified by an exterior sign with the business name. In the absence of other identifiers that the business conducted is a marine business, the sign must identify the nature of the business, such as marine sales, service, repair, or manufacturing.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201034[2010 c 161 § 1034]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c149.pdf?cite=1987%20c%20149%20§%202[1987 c 149 § 2]; ]

== 88.02.740 - Vessel dealer license required—Penalty.
Any person engaging in vessel dealer activities without first obtaining a vessel dealer license is guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201036[2010 c 161 § 1036]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c149.pdf?cite=1987%20c%20149%20§%203[1987 c 149 § 3]; ]

== 88.02.750 - Denial, suspension, or revocation of vessel dealer license—Penalties—Subterfuge.
. Except as otherwise provided in this chapter, the director may by order deny, suspend, or revoke a vessel dealer license, or in lieu of or in addition to, may by order assess monetary penalties of a civil nature not to exceed one thousand dollars per violation, if the director finds that the applicant or licensee:

.. Is applying for a dealer's license or has obtained a dealer's license for the purpose of evading excise taxes on vessels;

.. Has been adjudged guilty of a felony that directly relates to marine trade and the time elapsed since the adjudication is less than ten years. For purposes of this section, "adjudged guilty" means, in addition to a final conviction in court, an unvacated forfeiture of bail or collateral deposited to secure a defendant's appearance in court, the payment of a fine, a plea of guilty, or a finding of guilt regardless of whether the sentence is deferred or the penalty is suspended;

.. Has failed to comply with the trust account requirements of this chapter;

.. Has failed to transfer a certificate of title to a purchaser as required in this chapter;

.. Has misrepresented the facts at the time of application for registration or renewal; or

.. Has failed to comply with applicable provisions of this chapter or any rules adopted under it.

. The director may deny a vessel dealer license under this chapter if the application is a subterfuge that conceals the real person in interest whose vessel dealer license has been denied, suspended, or revoked for cause under this chapter and (a) the terms have not been fulfilled or a civil penalty has not been paid or (b) the director finds that the application was not filed in good faith. This subsection does not prevent the department from taking an action against a current vessel dealer licensee.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201035[2010 c 161 § 1035]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c149.pdf?cite=1987%20c%20149%20§%2012[1987 c 149 § 12]; ]

== 88.02.755 - Vessel registration or vessel dealer license suspension—Noncompliance with support order—Reissuance.
The department shall immediately suspend the vessel registration or vessel dealer's license of a person who has been certified pursuant to RCW 74.20A.320 by the department of social and health services as a person who is not in compliance with a support order. If the person has continued to meet all other requirements for reinstatement during the suspension, reissuance of the registration must be automatic upon the department's receipt of a release issued by the department of social and health services stating that the licensee is in compliance with the order.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201038[2010 c 161 § 1038]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/3901.SL.pdf?cite=1997%20c%2058%20§%20863[1997 c 58 § 863]; ]

== 88.02.760 - Evidence of ownership by vessel dealers—Sales of consigned vessels—Assignment and warranty of certificates of title.
. A vessel dealer shall possess a certificate of title, a manufacturer's statement of origin, a carpenter's certificate, or a factory invoice or other evidence of ownership approved by the department for each vessel in the vessel dealer's inventory unless the vessel for sale is consigned or subject to an inventory security agreement. Evidence of ownership must be either in the name of the dealer or in the name of the dealer's immediate vendor properly assigned.

. A vessel dealer may display and sell consigned vessels or vessels subject to an inventory security agreement if there is a written and signed consignment agreement for each vessel or an inventory security agreement covering all inventory vessels. The consignment agreement must include verification by the vessel dealer that evidence of ownership by the consignor exists and its location, the name and address of the registered owner, and the legal owner, if any. Vessels that are subject to an inventory security interest must be supported with evidence of ownership that is in the dealer's possession or the possession of the inventory security party. Upon payment of the debt secured for that vessel, the secured party shall deliver the ownership document, appropriately released, to the dealer. It is the vessel dealer's responsibility to ensure that ownership documents are available for ownership transfer upon the sale of the vessel.

. Following the retail sale of any vessel, the dealer shall promptly make application and execute the assignment and warranty of the certificate of title. The assignment must show any secured party holding a security interest created at the time of sale. The dealer shall deliver the certificate of title and application for registration to the department, county auditor or other agent, or subagent appointed by the director.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201043[2010 c 161 § 1043]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2224-S.SL.pdf?cite=1994%20c%20262%20§%2027[1994 c 262 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c149.pdf?cite=1987%20c%20149%20§%208[1987 c 149 § 8]; ]

== 88.02.770 - Receipt of cash or negotiable instrument before delivery of vessel—Trust account.
. A vessel dealer who receives cash or a negotiable instrument of deposit in excess of one thousand dollars, or a deposit of any amount that will be held for more than fourteen calendar days, shall place the funds in a separate trust account.

The cash or negotiable instrument must be:

.. Set aside immediately upon receipt for the trust account, or endorsed to the trust account immediately upon receipt; and

.. Deposited in the trust account by the close of banking hours on the day following the receipt.

. After delivery of the purchaser's vessel, the vessel dealer shall remove the deposited funds from the trust account.

. The dealer shall not commingle the purchaser's funds with any other funds at any time.

. The funds must remain in the trust account until the delivery of the purchased vessel. However, upon written agreement from the purchaser, the vessel dealer may remove and release trust funds before delivery.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201039[2010 c 161 § 1039]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1704-S.SL.pdf?cite=1991%20c%20339%20§%2033[1991 c 339 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c149.pdf?cite=1987%20c%20149%20§%2011[1987 c 149 § 11]; ]

== 88.02.780 - Records of the purchase and sale of vessels.
. A vessel dealer shall complete and maintain for a period of at least three years a record of the purchase and sale of all vessels purchased or consigned and sold by the vessel dealer. Records must be made available for inspection by the department during normal business hours.

. Before renewal of the vessel dealer license, the department shall require, on the forms prescribed, a record of the number of vessels sold during the license year. Vessel dealers who assert that they qualify for the exemption provided in RCW 88.02.710(2) shall also record, on forms prescribed, the highest retail value of any vessel sold in the license year.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201040[2010 c 161 § 1040]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c149.pdf?cite=1987%20c%20149%20§%2010[1987 c 149 § 10]; ]

== 88.02.790 - Vessel dealer display decals—Use.
. Vessel dealer display decals must only be used:

.. To demonstrate vessels held for sale when operated by a prospective customer holding a dated demonstration permit. The demonstration permit must be carried in the vessel at all times when it is being operated by a prospective customer;

.. On vessels owned or consigned for sale that are available for sale and being used only for vessel dealer business purposes by an officer of the corporation, a partner, a proprietor, or by a bona fide employee of the firm. A card identifying the individual as described in this section must be carried in the vessel at all times it is being operated.

. A vessel held for sale by a licensed vessel dealer is not required to be registered and display a registration number and a valid vessel decal.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201041[2010 c 161 § 1041]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c149.pdf?cite=1987%20c%20149%20§%204[1987 c 149 § 4]; ]

== 88.02.795 - Additional penalties for unauthorized or personal use of dealer display decals.
. In addition to other penalties imposed under this chapter for unauthorized or personal use of vessel dealer display decals, the director may:

.. Confiscate all vessel dealer display decals for a period that the director deems appropriate; and

.. Impose a monetary penalty not exceeding twice the amount of excise tax that should have been paid to properly register each vessel. The monetary penalty:

... May be in addition to or in lieu of other sanctions; and

... Is in addition to any fees owing to properly register each vessel.

. Any monetary penalty imposed or vessel dealer display decals confiscated must be done in accordance with chapter 34.05 RCW. Any monetary penalty imposed by the director and the delinquent excise taxes collected must be deposited in the general fund.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201037[2010 c 161 § 1037]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c149.pdf?cite=1987%20c%20149%20§%206[1987 c 149 § 6]; ]

== 88.02.800 - Issuance of temporary permits—Fee.
. The department may authorize vessel dealers properly licensed under this chapter to issue temporary permits to operate vessels under rules adopted by the department.

. The department, county auditor or other agent, or subagent appointed by the director shall collect the fee required under RCW 88.02.640(1)(a) for each temporary permit application sold to an authorized vessel dealer.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6379.SL.pdf?cite=2010%20c%20161%20§%201042[2010 c 161 § 1042]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c149.pdf?cite=1987%20c%20149%20§%209[1987 c 149 § 9]; ]

