= 59.04 - Tenancies.
:toc:

== 59.04.010 - Tenancies from year to year abolished except under written contract.
Tenancies from year to year are hereby abolished except when the same are created by express written contract. Leases may be in writing or print, or partly in writing and partly in print, and shall be legal and valid for any term or period not exceeding one year, without acknowledgment, witnesses or seals.

[ Code 1881 § 2053; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1867%20p%20101%20§%201[1867 p 101 § 1]; RRS § 10619; ]

== 59.04.020 - Tenancy from month to month—Termination.
When premises are rented for an indefinite time, with monthly or other periodic rent reserved, such tenancy shall be construed to be a tenancy from month to month, or from period to period on which rent is payable, and shall be terminated by written notice of thirty days or more, preceding the end of any of said months or periods, given by either party to the other.

[ Code 1881 § 2054; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1867%20p%20101%20§%202[1867 p 101 § 2]; RRS § 10619; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1866%20p%2078%20§%201[1866 p 78 § 1]; ]

== 59.04.030 - Tenancy for specified time—Termination.
In all cases where premises are rented for a specified time, by express or implied contract, the tenancy shall be deemed terminated at the end of such specified time.

[ Code 1881 § 2055; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1867%20p%20101%20§%203[1867 p 101 § 3]; RRS § 10620; ]

== 59.04.040 - Ten-day notice to pay rent or quit premises.
When a tenant fails to pay rent when the same is due, and the landlord notifies him or her to pay said rent or quit the premises within ten days, unless the rent is paid within said ten days, the tenancy shall be forfeited at the end of said ten days.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%2019001[2010 c 8 § 19001]; Code 1881 § 2056; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1867%20p%20101%20§%204[1867 p 101 § 4]; no RRS; ]

== 59.04.050 - Tenancy by sufferance—Termination.
Whenever any person obtains possession of premises without the consent of the owner or other person having the right to give said possession, he or she shall be deemed a tenant by sufferance merely, and shall be liable to pay reasonable rent for the actual time he or she occupied the premises, and shall forthwith on demand surrender his or her said possession to the owner or person who had the right of possession before said entry, and all his or her right to possession of said premises shall terminate immediately upon said demand.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6239-S.SL.pdf?cite=2010%20c%208%20§%2019002[2010 c 8 § 19002]; Code 1881 § 2057; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1867%20p%20101%20§%205[1867 p 101 § 5]; RRS § 10621; ]

== 59.04.900 - Chapter inapplicable to rental agreements under landlord-tenant act.
This chapter does not apply to any rental agreement included under the provisions of chapter 59.18 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c207.pdf?cite=1973%201st%20ex.s.%20c%20207%20§%2045[1973 1st ex.s. c 207 § 45]; ]

