= 28C.30 - Career connected learning.
:toc:

== 28C.30.020 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Career awareness and exploration" means programs, activities, and events that provide early exposure to jobs and industries. "Career awareness and exploration" are structured programs that include job fairs, guest speakers, job shadows, jobsite tours, and other similar activities.

. "Career connected learning" means a learning experience that is integrated with work-related content and skills in the following three categories: (a) Career awareness and exploration; (b) career preparation; and (c) career launch. "Career connected learning" includes work-integrated learning and work-integrated experiences.

. [Empty]
.. "Career launch programs" means registered apprenticeships and programs that combine the following three elements:

... Supervised paid work experience;

... Aligned classroom learning to academic and employer standards. For career launch programs involving the K-12 system, aligned classroom learning must meet educational requirements and standards of the office of the superintendent of public instruction; and

... Culmination in a valuable credential beyond a high school diploma or forty-five college credits towards a two-year or four-year postsecondary credential.

.. "Career launch programs" include the elements in (a) of this subsection and may be achieved through, but are not limited to, one or more of the following:

... A state-approved career and technical education sequence of courses or program of study that include requirements in alignment with RCW 28A.700.030;

... A qualifying degree or credential earned through a community or technical college or university.

.. "Career launch programs" may be initiated in a secondary education system and completed in a postsecondary education system, or first year of paid employment, as long as all parties jointly plan the program.

.. "Career launch programs" must be endorsed through the process created under RCW 28C.30.040(1)(a).

. "Career preparation programs" means programs that give students hands-on skills and knowledge experience within a particular business, career track, or industry, and help prepare students to work in a professional setting. "Career preparation programs" include career and technical education courses, on-site internships, preapprenticeship programs, and other similar opportunities.

. "Complete Washington" means the program established in the 2018 omnibus operating appropriations act, section 117, chapter 299, Laws of 2018, for the purpose of connecting prior learning with postsecondary degree completion.

. "Work group" means the career connected learning cross-agency work group established in RCW 28C.30.030.

. "Work-integrated learning" has the meaning provided in RCW 28A.630.135.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2158-S2.SL.pdf?cite=2019%20c%20406%20§%2057[2019 c 406 § 57]; ]

== 28C.30.030 - Career connected learning cross-agency work group—Establishment.
. Within existing resources, a career connected learning cross-agency work group is established to scale up and expand high-quality career connected learning opportunities in communities across the state.

. The purpose of the work group is to coordinate agency functions and external partnerships and carry out the duties and responsibilities set forth in RCW 28C.30.040.

. The governor shall select the chair of the work group.

. The governor's office may consult or contract with entities with expertise in industry and education partnerships to provide staffing support and guidance on industry talent needs. The governor's office may convene additional ad hoc committees that include industry sector advisory groups and leaders including, but not limited to, high-level representatives from education, industry, philanthropy, as well as students, parents, and community partners.

. The work group must consist of, but is not limited to, representatives from the following offices and agencies:

.. The department of labor and industries in consultation with the regulatory apprenticeship council under RCW 49.04.010;

.. The department of social and health services, including the division of vocational rehabilitation;

.. The work-integrated learning advisory committee established in RCW 28A.300.196 or its successor;

.. The education research and data center at the office of financial management;

.. The employment security department;

.. The office of the superintendent of public instruction;

.. The state board of education;

.. The state board for community and technical colleges;

.. The student achievement council;

.. The workforce training and education coordinating board;

.. One representative of the public baccalaureate institutions;

.. One representative of the independent four-year institutions of higher education;

.. The department of children, youth, and families;

.. The office of the lieutenant governor; and

.. The office of the governor.

. The office of the governor may establish subcommittees of the work group to plan and execute the duties and responsibilities under RCW 28C.30.040.

. The work group shall:

.. Coordinate its strategies and actions related to the common schools with the recommendations of the work-integrated learning advisory committee;

.. Meet at least six times during the calendar year; and

.. Report progress to the governor and appropriate committees of the legislature by September 1st annually.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2158-S2.SL.pdf?cite=2019%20c%20406%20§%2054[2019 c 406 § 54]; ]

== 28C.30.040 - Career connected learning cross-agency work group—Duties and responsibilities.
The career connected learning cross-agency work group established in RCW 28C.30.030 shall have the following duties and responsibilities:

. Advance and promote the career connect Washington vision to create a statewide system for career connected learning and the need for joint action as follows:

.. Create, and periodically update, clear guidance for endorsing career launch programs to guide quality assurance for the purpose of expanding enrollments by August 1, 2019. Registered apprenticeships as approved by the Washington apprenticeship and training council at the department of labor and industries are considered endorsed career launch programs;

.. Prioritize activities including coordinating cross-agency and industry sector leadership to advance strategic priorities;

.. Implement a marketing and communications agenda;

.. Mobilize private sector and philanthropic leadership and resources to support system building;

.. Build systemic functions in key agencies and existing systems;

.. Create a statewide inventory that identifies existing support programs to promote equitable participation in career connected learning, including resources for populations to reengage with educational opportunities;

.. Develop web sites and other resources, and coordinate current resources managed by the workforce training and education coordinating board, the student achievement council, and the employment security department, to inform students, employers, and the public about career connected learning opportunities;

.. Develop financial and other support services to increase access and success in career connected learning for students facing barriers or living in underserved communities;

.. Address transfer and articulation issues to ensure career launch program participants receive high school and college credit in programs initiated in K-12 or dropout reengagement programs, or college credit in postsecondary programs and registered apprenticeships, and work to expand the portability of credits to the maximum extent possible;

.. With respect to the portability of credit for the purposes of postsecondary degree attainment, the career connected learning [cross-agency] work group shall coordinate when appropriate with the complete Washington program;

.. Establish clear targets for equity to guide state data development and action by regional partners related to program design and expansion, including specific equity-focused criteria within grant funding processes and strategies; and

.. Develop data systems and protocols for career connected learning planning and evaluation purposes;

. By September 1, 2019, and by each September 1st thereafter, make budget recommendations to the office of financial management, to direct resources to education programs for career connected learning as follows:

.. Support the K-12 system and the office of the superintendent of public instruction to increase student participation in career connected learning and work-integrated learning programs that include career awareness and exploration, career preparation, and career launch;

.. Support expansion of innovative program design in registered apprenticeships, year-round and summer programs, and equitable access to dual credit;

.. Support two-year and four-year institutions of higher education to expand career connected learning enrollments, and specifically:

... Build capacity at community and technical colleges to support innovative design in career launch and registered apprenticeship programs, as well as program participation by high school graduates or out-of-school youth;

... Align the use of work-study to support career launch and registered apprenticeship programs; and

... Clarify financial aid eligibility and exclusions from financial aid caps for career launch and registered apprenticeship programs;

.. Promote innovation in equivalency and credentialing within endorsed career launch and registered apprenticeship programs;

.. Expand the number of portable credits and credit for prior learning to ensure that career launch programs transfer for high school or college credit to the maximum extent possible; and

.. Support the registered apprenticeship system and the department of labor and industries to build capacity to expand registered apprenticeship and preapprenticeship programs;

. Support regional leadership, program intermediaries, and career connected learning and work-integrated learning navigation and coordination to expand participation in career connected learning and work-integrated learning opportunities and the implementation of the career connected learning grant program established in RCW 28C.30.050;

. Support the formation and operation of regional networks in both rural and urban areas to guide career connected learning and work-integrated learning opportunities that are both tailored to the local needs of students and employers, and designed for portable credentials across education settings and across an industry; and

. Develop a data enclave for career connected learning and work-integrated learning to measure progress and ensure equity of opportunity for career connected learning and work-integrated learning, led by the education research and data center at the office of financial management, as follows:

.. Develop program codes for career connected learning and work-integrated learning opportunities in K-12 and postsecondary education in order to track those programs that are designated as career connected learning programs for each of the three categories set forth in the definition of "career connected learning" in RCW 28C.30.020; and

.. Collect and disaggregate program participation and outcomes data by race, gender, income, rurality, ability, foster youth, homeless youth, English language learner, and other relevant categories.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2158-S2.SL.pdf?cite=2019%20c%20406%20§%2055[2019 c 406 § 55]; ]

== 28C.30.050 - Career connected learning grant program.
. Subject to the availability of amounts appropriated for this specific purpose, the career connected learning grant program is established as a competitive grant program to advance the career connect Washington vision under RCW 28C.30.040. The employment security department shall administer the program. The governor's office shall work with the employment security department to establish grant criteria and guide the process for selection with consultation from the career connected learning cross-agency work group.

. The purpose of the career connected learning grant program is to create career connected learning opportunities, including career awareness and exploration, career preparation, and career launch programs, that are both tailored to the local needs of students and employers and designed so that students may receive high school or college credit across industries and regions of the state to the maximum extent possible.

. The program funds shall be used for two overarching purposes:

.. Support regional career connected learning and work-integrated learning networks in both rural and urban areas under subsection (5) of this section; and

.. Support career connected learning program intermediaries working within and across regions who partner with multiple employers, labor partners, and educational institutions, work with K-12 and postsecondary career representatives to develop curricula for new and innovative programs, and scale existing career awareness and exploration, career preparation, and endorsed career launch programs.

. The program administrator shall consult with the governor's office and the career connected learning cross-agency work group established in RCW 28C.30.030 to develop a formal request for proposal for both the regional career connected learning and work-integrated learning networks and the program intermediaries.

. [Empty]
.. Proposals for regional career connected learning and work-integrated learning networks and intermediaries may be sought from applicants within the geographic areas of the nine educational service districts. Successful applicants shall convene and manage regional, cross-industry networks that will lead to the expansion of career connected learning opportunities.

.. Regional career connected learning and work-integrated learning network applicants must demonstrate regional knowledge and status as a trusted partner of industry and education stakeholders, a track record of success with career connected learning and aligned initiatives, and a commitment to equity. Regional career connected learning networks may include, but are not limited to, regional education networks, school districts, educational service districts, higher education institutions, workforce development councils, chambers of commerce, industry associations, joint labor management councils, multiemployer training partnerships, economic development councils, and nonprofit organizations.

. Eligible program intermediary applicants may include, but are not limited to, new or existing industry associations, joint labor management councils, regional networks, career technical student organizations, postsecondary education and training institutions working with multiple employer partners, state agencies, and other community-based organizations and expanded learning partners.

. Program intermediaries must work with appropriate faculty and staff at the state universities, the regional universities, and the state college, and K-12 education representatives, to expand the number of career launch program credits that may be articulated and transferred to postsecondary degree programs.

. Subject to the availability of amounts appropriated for this specific purpose, the employment security department, as the administrator of the program, has the authority to utilize funds deposited in the career connected learning account for the purposes of the program.

. During the 2019-2021 fiscal biennium, the employment security department must provide sufficient funding from amounts appropriated for the program to the office of the superintendent of public instruction to provide a grant to each of the nine educational service districts for costs of employing one full-time equivalent employee to support the expansion of career connected learning opportunities.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2140-S.SL.pdf?cite=2019%20c%20411%20§%209[2019 c 411 § 9]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2158-S2.SL.pdf?cite=2019%20c%20406%20§%2056[2019 c 406 § 56]; ]

== 28C.30.060 - Career connected learning account.
The career connected learning account is created in the state treasury. All receipts from public or private sources provided for the purpose of funding grants under RCW 28C.30.050 must be deposited into the account. Moneys in the account may be spent only after appropriation. Expenditures from the account may be used only for career connected learning grants.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2158-S2.SL.pdf?cite=2019%20c%20406%20§%2059[2019 c 406 § 59]; ]

== 28C.30.070 - Employing minors.
Where applicable, career awareness and exploration, career connected learning, career launch programs, and career preparation programs are subject to RCW 49.12.121 and 49.12.123 regarding employing minors.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2158-S2.SL.pdf?cite=2019%20c%20406%20§%2058[2019 c 406 § 58]; ]

