= 28C.10 - Private vocational schools.
:toc:

== 28C.10.010 - Intent.
It is the intent of this chapter to protect against practices by private vocational schools which are false, deceptive, misleading, or unfair, and to help ensure adequate educational quality at private vocational schools.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c299.pdf?cite=1986%20c%20299%20§%201[1986 c 299 § 1]; ]

== 28C.10.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Agency" means the workforce training and education coordinating board.

. "Agent" means a person owning an interest in, employed by, or representing for remuneration a private vocational school within or without this state, who enrolls or personally attempts to secure the enrollment in a private vocational school of a resident of this state, offers to award educational credentials for remuneration on behalf of a private vocational school, or holds himself or herself out to residents of this state as representing a private vocational school for any of these purposes.

. "Degree" means any designation, appellation, letters, or words including but not limited to "associate," "bachelor," "master," "doctor," or "fellow" which signify or purport to signify satisfactory completion of an academic program of study beyond the secondary school level.

. "Education" includes but is not limited to, any class, course, or program of training, instruction, or study.

. "Educational credentials" means degrees, diplomas, certificates, transcripts, reports, or documents, that signify satisfactory completion of the requirements or prerequisites for any educational program.

. "Entity" includes, but is not limited to, a person, company, firm, society, association, partnership, corporation, or trust.

. "Private vocational school" means any location where an entity is offering postsecondary education in any form or manner for the purpose of instructing, training, or preparing persons for any vocation or profession.

. "Probation" means the agency has officially notified a private vocational school in writing that the school or a program offered by the school has been identified by the agency as at risk and has deficiencies that must be corrected within a specified time period.

. "Program" means a sequence of approved subjects offered by a school that teaches skills and fundamental knowledge required for employment in a particular occupation.

. "To grant" includes to award, issue, sell, confer, bestow, or give.

. "To offer" includes, in addition to its usual meanings, to advertise or publicize. "To offer" also means to solicit or encourage any person, directly or indirectly, to perform the act described.

. "To operate" means to establish, keep, or maintain any facility or location where, from, or through which education is offered or educational credentials are offered or granted to residents of this state, and includes contracting for the performance of any such act.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5402.SL.pdf?cite=2007%20c%20462%20§%201[2007 c 462 § 1]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5828.SL.pdf?cite=1993%20c%20445%20§%201[1993 c 445 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5184-S.SL.pdf?cite=1991%20c%20238%20§%2081[1991 c 238 § 81]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c188.pdf?cite=1990%20c%20188%20§%205[1990 c 188 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c299.pdf?cite=1986%20c%20299%20§%202[1986 c 299 § 2]; ]

== 28C.10.030 - Application of chapter.
This chapter does not apply to:

. Bona fide trade, business, professional, or fraternal organizations conducting educational programs primarily for that organization's membership or offered by that organization on a no-fee basis;

. Entities offering education that is exclusively avocational or recreational;

. Education not requiring payment of money or other consideration if this education is not advertised or promoted as leading toward educational credentials;

. Entities that are established, operated, and governed by this state or its political subdivisions under Title 28A or 28B RCW or this title;

. Degree-granting programs in compliance with the rules of the student achievement council;

. Any other entity to the extent that it has been exempted from some or all of the provisions of this chapter under RCW 28C.10.100;

. Entities not otherwise exempt that are of a religious character, but only as to those educational programs exclusively devoted to religious or theological objectives and represented accurately in institutional catalogs or other official publications;

. Entities offering only courses certified by the federal aviation administration;

. Barber and cosmetology schools licensed under chapter 18.16 RCW;

. Entities which only offer courses approved to meet the continuing education requirements for licensure under chapter 18.04, 18.79, or 48.17 RCW; and

. Entities not otherwise exempt offering only workshops or seminars lasting no longer than three calendar days.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2228.SL.pdf?cite=2014%20c%2011%20§%201[2014 c 11 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20576[2012 c 229 § 576]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2676-S.SL.pdf?cite=1994%20sp.s.%20c%209%20§%20723[1994 sp.s. c 9 § 723]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c188.pdf?cite=1990%20c%20188%20§%206[1990 c 188 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c299.pdf?cite=1986%20c%20299%20§%203[1986 c 299 § 3]; ]

== 28C.10.040 - Agency's duties—Rules—Investigations—Interagency agreements about degree and nondegree programs.
The agency:

. Shall maintain a list of private vocational schools licensed under this chapter;

. Shall adopt rules in accordance with chapter 34.05 RCW to carry out this chapter;

. May investigate any entity the agency reasonably believes to be subject to the jurisdiction of this chapter. In connection with the investigation, the agency may administer oaths and affirmations, issue subpoenas and compel attendance, take evidence, and require the production of any books, papers, correspondence, memorandums, or other records which the agency deems relevant or material to the investigation. The agency, including its staff and any other authorized persons, may conduct site inspections and examine records of all schools subject to this chapter;

. Shall develop an interagency agreement with the student achievement council to regulate degree-granting private vocational schools with respect to degree and nondegree programs.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2483-S2.SL.pdf?cite=2012%20c%20229%20§%20577[2012 c 229 § 577]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6371-S.SL.pdf?cite=1994%20c%2038%20§%205[1994 c 38 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c299.pdf?cite=1986%20c%20299%20§%204[1986 c 299 § 4]; ]

== 28C.10.050 - Minimum standards—Consumer student loan products—Denial of application for licensure—Determination that school or program is at risk of closure or termination.
. The agency shall adopt by rule minimum standards for entities operating private vocational schools. The minimum standards shall include, but not be limited to, requirements to assess whether a private vocational school is eligible to obtain and maintain a license in this state.

. The requirements adopted by the agency shall, at a minimum, require a private vocational school to:

.. Disclose to the agency information about its ownership and financial position and demonstrate to the agency that the school is financially viable and responsible and that it has sufficient financial resources to fulfill its commitments to students. Financial disclosures provided to the agency shall not be subject to public disclosure under chapter 42.56 RCW;

.. Follow a uniform statewide cancellation and refund policy as specified by the agency;

.. Disclose through use of a school catalog, web site, brochure, or other written material, necessary information to students so that students may make informed enrollment decisions. The agency shall specify what data and information are required. To the extent that these web sites or materials present any data on the completion rates, employment rates, loan or indebtedness metrics, and its graduates' median hourly and annual earnings for any of the private vocational schools or its programs, the posted data must be consistent with the data posted on the agency's career bridge web site or the data posted by the United States department of education, if the agency or the department of education has posted such data. Nothing in this subsection requires the agency to make changes to the career bridge web site or add new elements or features to the career bridge web site;

.. Use an enrollment contract or agreement that includes: (i) The school's cancellation and refund policy, (ii) a brief statement that the school is licensed under this chapter and that inquiries, concerns, or complaints may be made to the agency, and (iii) other necessary information as determined by the agency;

.. Describe accurately and completely in writing to students before their enrollment prerequisites and requirements for (i) completing successfully the programs of study in which they are interested and (ii) qualifying for the fields of employment for which their education is designed;

.. Comply with the requirements of RCW 28C.10.084;

.. Assess the basic skills and relevant aptitudes of each potential student to determine that a potential student has the basic skills and relevant aptitudes necessary to complete and benefit from the program in which the student plans to enroll, including but not limited to administering a United States department of education-approved English as a second language exam before enrolling students for whom English is a second language unless the students provide proof of graduation from a United States high school or proof of completion of a high school equivalency certificate as provided in RCW 28B.50.536 in English or results of another academic assessment determined appropriate by the agency. Guidelines for such assessments shall be developed by the agency, in consultation with the schools;

.. Discuss with each potential student the potential student's obligations in signing any enrollment contract and/or incurring any debt for educational purposes. The discussion shall include the inadvisability of acquiring an excessive educational debt burden that will be difficult to repay given employment opportunities and average starting salaries in the potential student's chosen occupation;

.. Ensure that any enrollment contract between the private vocational school and its students has an attachment in a format provided by the agency. The attachment shall be signed by both the school and the student. The attachment shall stipulate that the school has complied with (h) of this subsection and that the student understands and accepts his or her responsibilities in signing any enrollment contract or debt application. The attachment shall also stipulate that the enrollment contract shall not be binding for at least five days, excluding Sundays and holidays, following signature of the enrollment contract by both parties;

.. Comply with the requirements related to qualifications of administrators and instructors; and

.. Disclose to the agency regarding any pending investigations by an oversight entity, including the nature of that investigation, within thirty days of the school's first knowledge of the investigation. For the purposes of this subsection, "investigation" means any inquiry into possible violations of any applicable laws or accreditation standards. For the purposes of this subsection, "oversight entity" means all of the following:

... Any federal or state entity that provides financial aid to students of the institution or approves the school for participation in a financial aid program;

... Any state or federal attorney general's office or department of justice;

... Any regulator that approves the operation of the private vocational school;

... The federal consumer financial protection bureau or the federal securities and exchange commission; and

.. Any accrediting agency.

. A private vocational school that has at least one hundred fifty students or more in the state during any given year, or that has been operating in the state for less than two consecutive years, or that has not had at least one of its programs recognized by the agency as an eligible training provider for at least two consecutive years, may not engage in any practice regarding the sale of, or inducing of students to obtain, specific consumer student loan products to fund education that financially benefits any person or entity that has an ownership interest in the institution, unless the institution can demonstrate to the agency that the student has exhausted all federal aid options and has been denied noninstitutional private commercial loan products. A financial benefit for purposes of this subsection does not include merely having an interest in students with loans enrolling in the institution or assisting students with financial aid matters. For purposes of this subsection, "agent" means any employee, officer, or contractor working on behalf of the institution.

. The agency may deny a private vocational school's application for licensure if the school fails to meet the requirements in this section.

. The agency may determine that a licensed private vocational school or a particular program of a private vocational school is at risk of closure or termination if:

.. There is a pattern or history of substantiated student complaints filed with the agency pursuant to RCW 28C.10.120; or

.. The private vocational school fails to meet minimum licensing requirements and has a pattern or history of failing to meet the minimum requirements.

. If the agency determines that a private vocational school or a particular program is at risk of closure or termination, the agency shall require the school to take corrective action.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1439-S2.SL.pdf?cite=2018%20c%20203%20§%206[2018 c 203 § 6]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2228.SL.pdf?cite=2014%20c%2011%20§%202[2014 c 11 § 2]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1686-S.SL.pdf?cite=2013%20c%2039%20§%2015[2013 c 39 § 15]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5402.SL.pdf?cite=2007%20c%20462%20§%202[2007 c 462 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20247[2005 c 274 § 247]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1313.SL.pdf?cite=2001%20c%2023%20§%201[2001 c 23 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c188.pdf?cite=1990%20c%20188%20§%207[1990 c 188 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c459.pdf?cite=1987%20c%20459%20§%203[1987 c 459 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c299.pdf?cite=1986%20c%20299%20§%205[1986 c 299 § 5]; ]

== 28C.10.060 - Licenses—Requirements—Renewal.
Any entity desiring to operate a private vocational school shall apply for a license to the agency on a form provided by the agency. The agency shall issue a license if the school:

. Files a completed application with information satisfactory to the agency. Misrepresentation by an applicant shall be grounds for the agency, at its discretion, to deny or revoke a license.

. Complies with the requirements for the tuition recovery trust fund under RCW 28C.10.084.

. Pays the required fees.

. Meets the minimum standards adopted by the agency under RCW 28C.10.050.

Licenses shall be valid for one year from the date of issue unless revoked or suspended. If a school fails to file a completed renewal application at least thirty days before the expiration date of its current license the school shall be subject to payment of a late filing fee fixed by the agency.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2228.SL.pdf?cite=2014%20c%2011%20§%203[2014 c 11 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c459.pdf?cite=1987%20c%20459%20§%204[1987 c 459 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c299.pdf?cite=1986%20c%20299%20§%206[1986 c 299 § 6]; ]

== 28C.10.070 - Fees.
The agency shall establish fees by rule at a level necessary to approximately recover the staffing costs incurred in administering this chapter. All fees collected under this section shall be deposited in the state general fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c299.pdf?cite=1986%20c%20299%20§%207[1986 c 299 § 7]; ]

== 28C.10.082 - Tuition recovery trust fund—Established.
The tuition recovery trust fund is hereby established in the custody of the state treasurer. The agency shall deposit in the fund all moneys received under RCW 28C.10.084. Moneys in the fund may be spent only for the purposes under RCW 28C.10.084. Disbursements from the fund shall be on authorization of the agency. Disbursements from the fund shall only be used to reimburse students who are Washington state residents, or agencies or businesses that pay tuition and fees on behalf of Washington students. During the 2013-2015 fiscal biennium, the legislature may transfer from the tuition recovery trust fund to the state general fund such amounts as reflect the excess fund balance in the fund. The fund is subject to the allotment procedure provided under chapter 43.88 RCW, but no appropriation is required for disbursements.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2228.SL.pdf?cite=2014%20c%2011%20§%204[2014 c 11 § 4]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5034-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%204%20§%20965[2013 2nd sp.s. c 4 § 965]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1058-S.SL.pdf?cite=1991%20sp.s.%20c%2013%20§%2085[1991 sp.s. c 13 § 85]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c459.pdf?cite=1987%20c%20459%20§%202[1987 c 459 § 2]; ]

== 28C.10.084 - Tuition recovery trust fund—Operation—Liability—Claims.
. The agency shall establish, maintain, and administer a tuition recovery trust fund. All funds collected for the tuition recovery trust fund are payable to the state for the benefit and protection of any student or enrollee of a private vocational school licensed under this chapter, in the case of a minor, his or her parents or guardian, or an agency or business that paid tuition and fees on behalf of Washington state students, for purposes including but not limited to the settlement of claims related to school closures under subsection (10) of this section and the settlement of claims under RCW 28C.10.120. The fund shall be liable for settlement of claims and costs of administration but shall not be liable to pay out or recover penalties assessed under RCW 28C.10.130 or 28C.10.140. No liability accrues to the state of Washington from claims made against the fund.

. By June 30, 1998, a minimum operating balance of one million dollars shall be achieved in the fund and maintained thereafter. If disbursements reduce the operating balance below two hundred thousand dollars at any time before June 30, 1998, or below one million dollars thereafter, each participating owner shall be assessed a pro rata share of the deficiency created, based upon the incremental scale created under subsection (6) of this section for each private vocational school. The agency shall adopt schedules of times and amounts for effecting payments of assessment.

. In order for a private vocational school to be and remain licensed under this chapter each owner shall, in addition to other requirements under this chapter, make cash deposits on behalf of the school into a tuition recovery trust fund as a means to assure payment of claims brought under this chapter.

. The amount of liability that can be satisfied by this fund on behalf of each private vocational school licensed under this chapter shall be the amount of unearned prepaid tuition and fees. If the claimant provides evidence to the agency of the lack of availability to continue his or her program of study at another institution, the agency's executive director or the executive director's designee has the authority to reimburse the student, agency, or business up to the full value of tuition and fees paid to date, subject to subsection (10) of this section. The agency may use the fund to pay for prior learning assessments for students who choose to attend another institution.

. The fund's liability with respect to each participating private vocational school commences on the date of the initial deposit into the fund made on its behalf and ceases one year from the date the school is no longer licensed under this chapter.

. The agency shall adopt by rule a matrix for calculating the deposits into the fund on behalf of each vocational school. Proration shall be determined by factoring the school's share of liability in proportion to the aggregated liability of all participants under the fund by grouping such prorations under the incremental scale created by subsection (4) of this section. Expressed as a percentage of the total liability, that figure determines the amount to be contributed when factored into a fund containing one million dollars. The total amount of its prorated share, minus the amount paid for initial capitalization, shall be payable in up to twenty increments over a ten-year period, commencing with the sixth month after the initial capitalization deposit has been made on behalf of the school. Additionally, the agency shall require deposits for initial capitalization, under which the amount each owner deposits is proportionate to the school's share of two hundred thousand dollars, employing the matrix developed under this subsection.

. No vested right or interests in deposited funds is created or implied for the depositor, either at any time during the operation of the fund or at any such future time that the fund may be dissolved. All funds deposited are payable to the state for the purposes described under this section. The agency shall maintain the fund, serve appropriate notices to affected owners when scheduled deposits are due, collect deposits, and make disbursements to settle claims against the fund. When the aggregated deposits total five million dollars and the history of disbursements justifies such modifications, the agency may at its own option reduce the schedule of deposits whether as to time, amount, or both and the agency may also entertain proposals from among the licensees with regard to disbursing surplus funds for such purposes as vocational scholarships.

. Based on annual financial data supplied by the owner, the agency shall determine whether the increment assigned to that private vocational school on the incremental scale established under subsection (6) of this section has changed. If an increase or decrease in gross annual tuition income has occurred, a corresponding change in the school's incremental position and contribution schedule shall be made before the date of the owner's next scheduled deposit into the fund. Such adjustments shall only be calculated and applied annually.

. If the majority ownership interest in a private vocational school is conveyed through sale or other means into different ownership, all contributions made to the date of transfer remain in the fund. The new owner shall continue to make contributions to the fund until the original ten-year cycle is completed. All tuition recovery trust fund contributions shall remain with the private vocational school transferred, and no additional cash deposits may be required beyond the original ten-year contribution cycle.

. [Empty]
.. To settle claims adjudicated under RCW 28C.10.120 and claims resulting when a private vocational school ceases to provide educational services, the agency may make disbursements from the fund. Students enrolled under a training contract executed between a school and a public or private agency or business are not eligible to make a claim against the fund until January 1, 2016.

.. In addition to the processes described for making reimbursements related to claims under RCW 28C.10.120, the following procedures are established to deal with reimbursements related to school closures:

... The agency shall attempt to notify all potential claimants. The unavailability of records and other circumstances surrounding a school closure may make it impossible or unreasonable for the agency to ascertain the names and whereabouts of each potential claimant but the agency shall make reasonable inquiries to secure that information from all likely sources. The agency shall then proceed to settle the claims on the basis of information in its possession. The agency is not responsible or liable for claims or for handling claims that may subsequently appear or be discovered.

... Thirty days after identified potential claimants have been notified, if a claimant refuses or neglects to file a claim verification as requested in such notice, the agency may be relieved of further duty or action on behalf of the claimant under this chapter. The executive director of the agency or the executive director's designee will determine if an exemption to the thirty days shall be granted if the claimant furnishes proof of an extraordinary or exigent circumstance.

... After verification and review, the agency may disburse funds from the tuition recovery trust fund to settle or compromise the claims for an amount up to the value of unearned prepaid tuition and fees. If the claimant provides evidence to the agency of the lack of availability to continue his or her program of study at another institution, the agency's executive director or the executive director's designee has the authority to reimburse the student, agency, or business up to the full value of tuition and fees paid to date, subject to (a) of this subsection. The agency may use the fund to pay for prior learning assessments for students who choose to attend another institution.

... In the instance of claims against a closed school, the agency shall seek to recover such disbursed funds from the assets of the defaulted owner, including but not limited to asserting claims as a creditor in bankruptcy proceedings.

. When funds are disbursed to settle claims against a licensed private vocational school, the agency shall make demand upon the owner for recovery. The agency shall adopt schedules of times and amounts for effecting recoveries. An owner's failure to perform subjects the school's license to suspension or revocation under *RCW 28C.10.050 in addition to any other available remedies.

. For purposes of this section, "owner" includes, but is not limited to, a person, company, firm, society, association, partnership, corporation, or trust having a controlling ownership interest in a private vocational school.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2228.SL.pdf?cite=2014%20c%2011%20§%205[2014 c 11 § 5]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1313.SL.pdf?cite=2001%20c%2023%20§%202[2001 c 23 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2061-S2.SL.pdf?cite=1999%20c%20321%20§%203[1999 c 321 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5828.SL.pdf?cite=1993%20c%20445%20§%202[1993 c 445 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c188.pdf?cite=1990%20c%20188%20§%208[1990 c 188 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c459.pdf?cite=1987%20c%20459%20§%201[1987 c 459 § 1]; ]

== 28C.10.090 - Actions prohibited without license.
A private vocational school, whether located in this state or outside of this state, shall not conduct business of any kind, make any offers, advertise or solicit, or enter into any contracts unless the private vocational school is licensed under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c299.pdf?cite=1986%20c%20299%20§%209[1986 c 299 § 9]; ]

== 28C.10.100 - Suspension or modification of requirements of chapter.
The executive director of the agency may suspend or modify any of the requirements under this chapter in a particular case if the agency finds that:

. The suspension or modification is consistent with the purposes of this chapter; and

. The education to be offered addresses a substantial, demonstrated need among residents of the state or that literal application of this chapter would cause a manifestly unreasonable hardship.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c299.pdf?cite=1986%20c%20299%20§%2010[1986 c 299 § 10]; ]

== 28C.10.110 - Unfair business practices.
. It is a violation of this chapter for an entity operating a private vocational school to engage in an unfair business practice. The agency may deny, revoke, or suspend the license of any entity that is found to have engaged in a substantial number of unfair business practices or that has engaged in significant unfair business practices.

. It is an unfair business practice for an entity operating a private vocational school or an agent employed by a private vocational school to:

.. Fail to comply with the terms of a student enrollment contract or agreement;

.. Use an enrollment contract form, catalog, brochure, or similar written material affecting the terms and conditions of student enrollment other than that previously submitted to the agency and authorized for use;

.. Advertise in the help wanted section of a newspaper or otherwise represent falsely, directly or by implication, that the school is an employment agency, is making an offer of employment or otherwise is attempting to conceal the fact that what is being represented are course offerings of a school;

.. Represent falsely, directly or by implication, that an educational program is approved by a particular industry or that successful completion of the program qualifies a student for admission to a labor union or similar organization or for the receipt of a state license in any business, occupation, or profession;

.. Represent falsely, directly or by implication, that a student who successfully completes a course or program of instruction may transfer credit for the course or program to any institution of higher education;

.. Represent falsely, directly or by implication, in advertising or in any other manner, the school's size, location, facilities, equipment, faculty qualifications, number of faculty, or the extent or nature of any approval received from an accrediting association;

.. Represent that the school is approved, recommended, or endorsed by the state of Washington or by the agency, except the fact that the school is authorized to operate under this chapter may be stated;

.. Provide prospective students with: Any testimonial, endorsement, or other information that a reasonable person would find likely to mislead or deceive prospective students or the public, including those regarding current practices of the school; information regarding rates of completion or postgraduation employment by industry, or its graduates' median hourly or annual earnings, that is not consistent with the presentation of data as established under RCW 28C.10.050(2)(c); current conditions for employment opportunities; postgraduation employment by industry or probable earnings in the occupation for which the education was designed; total cost to obtain a diploma or certificate; the acceptance of a diploma or certificate by employers as a qualification for employment; the acceptance of courses, a diploma, or certificate by higher education institutions; the likelihood of obtaining financial aid or low-interest loans for tuition; and the ability of graduates to repay loans;

.. Designate or refer to sales representatives as "counselors," "advisors," or similar terms which have the tendency to mislead or deceive prospective students or the public regarding the authority or qualifications of the sales representatives;

.. Make or cause to be made any statement or representation in connection with the offering of education if the school or agent knows or reasonably should have known the statement or representation to be false, substantially inaccurate, or misleading;

.. Engage in methods of advertising, sales, collection, credit, or other business practices which are false, deceptive, misleading, or unfair, as determined by the agency by rule;

.. Attempt to recruit students in or within forty feet of a building that contains a welfare or unemployment office. Recruiting includes, but is not limited to canvassing and surveying. Recruiting does not include leaving materials at or near an office for a person to pick up of his or her own accord, or handing a brochure or leaflet to a person provided that no attempt is made to obtain a name, address, telephone number, or other data, or to otherwise actively pursue the enrollment of the individual;

.. Violate RCW 28C.10.050(3) regarding the sale of, or inducing of students to obtain, specific consumer student loan products; or

.. Use any official United States military logos in advertising or promotional materials.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1439-S2.SL.pdf?cite=2018%20c%20203%20§%207[2018 c 203 § 7]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2228.SL.pdf?cite=2014%20c%2011%20§%206[2014 c 11 § 6]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1313.SL.pdf?cite=2001%20c%2023%20§%203[2001 c 23 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c188.pdf?cite=1990%20c%20188%20§%209[1990 c 188 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c299.pdf?cite=1986%20c%20299%20§%2011[1986 c 299 § 11]; ]

== 28C.10.120 - Complaints—Investigations—Hearings—Remedies—Transition assistance for students.
. Complaints may be filed under this chapter only by a current student or exiter of a program or training affected by an unfair business practice. The complaint shall set forth the alleged violation and shall contain information required by the agency on forms provided for that purpose. A complaint may also be filed with the agency by an authorized staff member of the agency or by the attorney general.

. The agency shall investigate any complaint under this section and shall first attempt to bring about a negotiated settlement. The agency director or the director's designee may conduct an informal hearing with the affected parties in order to determine whether a violation has occurred.

. If the agency finds that the private vocational school or its agent engaged in or is engaging in any unfair business practice, the agency shall issue and cause to be served upon the violator an order requiring the violator to cease and desist from the act or practice and may impose the penalties provided under RCW 28C.10.130. If the agency finds that the complainant has suffered loss as a result of the act or practice, the agency may order the violator to pay full or partial restitution of any amounts lost. The loss may include any money paid for tuition, required or recommended course materials, and any reasonable living expenses incurred by the complainant during the time the complainant was enrolled at the school.

. The complainant is not bound by the agency's determination of restitution. The complainant may reject that determination and may pursue any other legal remedy.

. The violator may, within twenty days of being served any order described under subsection (3) of this section, file an appeal under the administrative procedure act, chapter 34.05 RCW. Timely filing stays the agency's order during the pendency of the appeal. If the agency prevails, the appellant shall pay the costs of the administrative hearing.

. If a private vocational school closes without providing adequate notice to its enrolled students, the agency shall provide transition assistance to the school's students including, but not limited to, information regarding: (a) Transfer options available to students; (b) financial aid discharge eligibility and procedures; (c) the labor market, job search strategies, and placement assistance services; and (d) other support services available to students.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2228.SL.pdf?cite=2014%20c%2011%20§%207[2014 c 11 § 7]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5402.SL.pdf?cite=2007%20c%20462%20§%203[2007 c 462 § 3]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5828.SL.pdf?cite=1993%20c%20445%20§%203[1993 c 445 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c188.pdf?cite=1990%20c%20188%20§%2010[1990 c 188 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%2083[1989 c 175 § 83]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c299.pdf?cite=1986%20c%20299%20§%2012[1986 c 299 § 12]; ]

== 28C.10.130 - Violations—Civil penalties—Consumer protection act.
. Any private vocational school or agent violating RCW 28C.10.060, 28C.10.090, or 28C.10.110 or the applicable agency rules is subject to a civil penalty of not more than one hundred dollars for each separate violation. Each day on which a violation occurs constitutes a separate violation. Multiple violations on a single day may be considered separate violations. The fine may be imposed by the agency under RCW 28C.10.120, or in any court of competent jurisdiction.

. In addition to the penalties authorized pursuant to subsection (1) of this section, any violation of any provision of this chapter is also a violation of RCW 19.86.020 of the consumer protection act, pursuant to RCW 28C.10.210. The penalties authorized under subsection (1) of this section do not preclude remedies available under the provisions of the consumer protection act.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1439-S2.SL.pdf?cite=2018%20c%20203%20§%208[2018 c 203 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c299.pdf?cite=1986%20c%20299%20§%2013[1986 c 299 § 13]; ]

== 28C.10.140 - Violations—Criminal sanctions.
Any entity or any owner, officer, agent, or employee of such entity who wilfully violates RCW 28C.10.060 or 28C.10.090 is guilty of a gross misdemeanor and, upon conviction, shall be punished by a fine of not to exceed one thousand dollars or by imprisonment in the county jail for up to three hundred sixty-four days, or by both such fine and imprisonment.

Each day on which a violation occurs constitutes a separate violation. The criminal sanctions may be imposed by a court of competent jurisdiction in an action brought by the attorney general of this state.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5168-S.SL.pdf?cite=2011%20c%2096%20§%2023[2011 c 96 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c299.pdf?cite=1986%20c%20299%20§%2014[1986 c 299 § 14]; ]

== 28C.10.150 - Actions resulting in jurisdiction of courts.
A private vocational school, whether located in this state or outside of this state, that conducts business of any kind, makes any offers, advertises, solicits, or enters into any contracts in this state or with a resident of this state is subject to the jurisdiction of the courts of this state for any cause of action arising from the acts.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c299.pdf?cite=1986%20c%20299%20§%2015[1986 c 299 § 15]; ]

== 28C.10.160 - Educational records—Permanent file—Protection.
If any private vocational school discontinues its operation, the chief administrative officer of the school shall file with the agency the original or legible true copies of all educational records required by the agency. If the agency determines that any educational records are in danger of being made unavailable to the agency, the agency may seek a court order to protect and if necessary take possession of the records. The agency shall cause to be maintained a permanent file of educational records coming into its possession.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c299.pdf?cite=1986%20c%20299%20§%2016[1986 c 299 § 16]; ]

== 28C.10.170 - Contracts voidable—When.
If a student or prospective student is a resident of this state at the time any contract relating to payment for education or any note, instrument, or other evidence of indebtedness relating thereto is entered into, RCW 28C.10.180 shall govern the rights of the parties to the contract or evidence of indebtedness. If a contract or evidence of indebtedness contains any of the following agreements, the contract is voidable at the option of the student or prospective student:

. That the law of another state shall apply;

. That the maker or any person liable on the contract or evidence of indebtedness consents to the jurisdiction of another state;

. That another person is authorized to confess judgment on the contract or evidence of indebtedness; or

. That fixes venue.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c299.pdf?cite=1986%20c%20299%20§%2017[1986 c 299 § 17]; ]

== 28C.10.180 - Enforceability of debts—Authority to offer degree required.
A note, instrument, or other evidence of indebtedness or contract relating to payment for education is not enforceable in the courts of this state by a private vocational school or holder of the instrument unless the private vocational school was licensed under this chapter at the time the note, instrument, or other evidence of indebtedness or contract was entered into.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c299.pdf?cite=1986%20c%20299%20§%2018[1986 c 299 § 18]; ]

== 28C.10.190 - Actions to enforce chapter—Who may bring—Relief.
The attorney general or the prosecuting attorney of any county in which a private vocational school or agent of the school is found may bring an action in any court of competent jurisdiction for the enforcement of this chapter. The court may issue an injunction or grant any other appropriate form of relief.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c299.pdf?cite=1986%20c%20299%20§%2019[1986 c 299 § 19]; ]

== 28C.10.200 - Injunctive relief—Agency may seek.
The agency may seek injunctive relief, after giving notice to the affected party, in a court of competent jurisdiction for a violation of this chapter or the rules adopted under this chapter. The agency need not allege or prove that the agency has no adequate remedy at law. The right of injunction provided in this section is in addition to any other legal remedy which the agency has and is in addition to any right of criminal prosecution provided by law. The existence of agency action with respect to alleged violations of this chapter and rules adopted under this chapter does not operate as a bar to an action for injunctive relief under this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c299.pdf?cite=1986%20c%20299%20§%2020[1986 c 299 § 20]; ]

== 28C.10.210 - Violation of chapter unfair or deceptive practice under RCW  19.86.020.
A violation of this chapter or the rules adopted under this chapter affects the public interest and is an unfair or deceptive act or practice in violation of RCW 19.86.020 of the consumer protection act. The remedies and sanctions provided by this section shall not preclude application of other remedies and sanctions.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c299.pdf?cite=1986%20c%20299%20§%2021[1986 c 299 § 21]; ]

== 28C.10.220 - Remedies and penalties in chapter nonexclusive and cumulative.
The remedies and penalties provided for in this chapter are nonexclusive and cumulative and do not affect any other actions or proceedings.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c299.pdf?cite=1986%20c%20299%20§%2022[1986 c 299 § 22]; ]

== 28C.10.902 - Effective date—1986 c 299.
This act shall take effect July 1, 1986.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c299.pdf?cite=1986%20c%20299%20§%2031[1986 c 299 § 31]; ]

