= 63.19 - Lease-purchase agreements.
:toc:

== 63.19.010 - Definitions.
As used in this chapter, unless the context otherwise requires:

. "Advertisement" means a commercial message in any medium that aids, promotes, or assists, directly or indirectly, a lease-purchase agreement.

. "Cash price" means the price at which the lessor would have sold the property to the consumer for cash on the date of the lease-purchase agreement.

. "Consumer" means a natural person who rents personal property under a lease-purchase agreement to be used primarily for personal, family, or household purposes.

. "Consummation" means the time a consumer becomes contractually obligated on a lease-purchase agreement.

. "Lease-purchase agreement" means an agreement for the use of personal property by a natural person primarily for personal, family, or household purposes, for an initial period of four months or less that is automatically renewable with each payment after the initial period, but does not obligate or require the consumer to continue leasing or using the property beyond the initial period, and that permits the consumer to become the owner of the property.

. "Lessor" means a person who regularly provides the use of property through lease-purchase agreements and to whom lease payments are initially payable on the face of the lease-purchase agreement.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2299-S.SL.pdf?cite=1992%20c%20134%20§%202[1992 c 134 § 2]; ]

== 63.19.020 - Chapter application.
. Lease-purchase agreements that comply with this chapter are not governed by the laws relating to:

.. A consumer lease as defined in chapter 63.10 RCW;

.. A retail installment sale of goods or services as regulated under chapter 63.14 RCW;

.. A security interest as defined in Title 62A RCW; or

.. Loans, forbearances of money, goods, or things in action as governed by chapter 19.52 RCW.

. This chapter does not apply to the following:

.. Lease-purchase agreements primarily for business, commercial, or agricultural purposes, or those made with governmental agencies or instrumentalities or with organizations;

.. A lease of a safe deposit box;

.. A lease or bailment of personal property that is incidental to the lease of real property, and that provides that the consumer has no option to purchase the leased property; or

.. A lease of an automobile.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2299-S.SL.pdf?cite=1992%20c%20134%20§%203[1992 c 134 § 3]; ]

== 63.19.030 - Disclosure by lessor—Requirement.
. The lessor shall disclose to the consumer the information required under this chapter. In a transaction involving more than one lessor, only one lessor need make the disclosures, but all lessors shall be bound by such disclosures.

. The disclosure shall be made at or before consummation of the lease-purchase agreement.

. The disclosure shall be made clearly and conspicuously in writing and a copy of the lease-purchase agreement provided to the consumer. The disclosures required under RCW 63.19.040(1) shall be made on the face of the contract above the line for the consumer's signature.

. If a disclosure becomes inaccurate as the result of any act, occurrence, or agreement by the consumer after delivery of the required disclosures, the resulting inaccuracy is not a violation of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2299-S.SL.pdf?cite=1992%20c%20134%20§%204[1992 c 134 § 4]; ]

== 63.19.040 - Disclosure by lessor—Contents.
. For each lease-purchase agreement, the lessor shall disclose in the agreement the following items, as applicable:

.. The total number, total amount, and timing of all payments necessary to acquire ownership of the property;

.. A statement that the consumer will not own the property until the consumer has made the total payment necessary to acquire ownership;

.. A statement that the consumer is responsible for the fair market value of the property if, and as of the time, it is lost, stolen, damage, or destroyed;

.. A brief description of the leased property, sufficient to identify the property to the consumer and the lessor, including an identification number, if applicable, and a statement indicating whether the property is new or used, but a statement that indicates new property is used is not a violation of this chapter;

.. A brief description of any damage to the leased property;

.. A statement of the cash price of the property. Where the agreement involves a lease of five or more items as a set, in one agreement, a statement of the aggregate cash price of all items shall satisfy this requirement;

.. The total of initial payments paid or required at or before consummation of the agreement or delivery of the property, whichever is later;

.. A statement that the total of payments does not include other charges, such as late payment, default, pickup, and reinstatement fees, which fees shall be separately disclosed in the contract;

.. A statement clearly summarizing the terms of the consumer's option to purchase, including a statement that the consumer has the right to exercise an early purchase option and the price, formula, or method for determining the price at which the property may be so purchased;

.. A statement identifying the party responsible for maintaining or servicing the property while it is being leased, together with a description of that responsibility, and a statement that if any part of a manufacturer's express warranty covers the lease property at the time the consumer acquires ownership of the property, it shall be transferred to the consumer, if allowed by the terms of the warranty;

.. The date of the transaction and the identities of the lessor and consumer;

.. A statement that the consumer may terminate the agreement without penalty by voluntarily surrendering or returning the property in good repair upon expiration of any lease term along with any past due rental payments; and

.. Notice of the right to reinstate an agreement as herein provided.

. With respect to matters specifically governed by the federal consumer credit protection act, compliance with the act satisfies the requirements of this section.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2299-S.SL.pdf?cite=1992%20c%20134%20§%205[1992 c 134 § 5]; ]

== 63.19.050 - Agreement—Restrictions.
A lease-purchase agreement may not contain:

. A confession of judgment;

. A negotiable instrument;

. A security interest or any other claim of a property interest in any goods except those goods delivered by the lessor pursuant to the lease-purchase agreement;

. A wage assignment;

. A waiver by the consumer of claims or defenses; or

. A provision authorizing the lessor or a person acting on the lessor's behalf to enter upon the consumer's premises or to commit any breach of the peace in the repossession of goods.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2299-S.SL.pdf?cite=1992%20c%20134%20§%206[1992 c 134 § 6]; ]

== 63.19.060 - Consumer—Reinstatement of agreement—Terms.
. A consumer who fails to make a timely rental payment may reinstate the agreement, without losing any rights or options that exist under the agreement, by the payment of:

.. All past due rental charges;

.. If the property has been picked up, the reasonable costs of pickup and redelivery; and

.. Any applicable late fee, within ten days of the renewal date if the consumer pays monthly, or within five days of the renewal date if the consumer pays more frequently than monthly.

. In the case of a consumer who has paid less than two-thirds of the total of payments necessary to acquire ownership and where the consumer has returned or voluntarily surrendered the property, other than through judicial process, during the applicable reinstatement period set forth in subsection (1) of this section, the consumer may reinstate the agreement during a period of not less than twenty-one days after the date of the return of the property.

. In the case of a consumer who has paid two-thirds or more of the total of payments necessary to acquire ownership, and where the consumer has returned or voluntarily surrendered the property, other than through judicial process, during the applicable period set forth in subsection (1) of this section, the consumer may reinstate the agreement during a period of not less than forty-five days after the date of the return of the property.

. Nothing in this section shall prevent a lessor from attempting to repossess property during the reinstatement period, but such a repossession shall not affect the consumer's right to reinstate. Upon reinstatement, the lessor shall provide the consumer with the same property or substitute property of comparable quality and condition.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2299-S.SL.pdf?cite=1992%20c%20134%20§%207[1992 c 134 § 7]; ]

== 63.19.070 - Written receipt—Lessor's duty.
A lessor shall provide the consumer a written receipt for each payment made by cash or money order.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2299-S.SL.pdf?cite=1992%20c%20134%20§%208[1992 c 134 § 8]; ]

== 63.19.080 - Renegotiation—Same lessor and consumer.
. A renegotiation shall occur when an existing lease-purchase agreement is satisfied and replaced by a new agreement undertaken by the same lessor and consumer. A renegotiation shall be considered a new agreement requiring new disclosures. However, events such as the following shall not be treated as renegotiations:

.. The addition or return of property in a multiple-item agreement or the substitution of the lease property, if in either case the average payment allocable to a payment period is not changed by more than twenty-five percent;

.. A deferral or extension of one or more periodic payments, or portions of a periodic payment;

.. A reduction in charges in the lease or agreement; and

.. A lease or agreement involved in a court proceeding.

. No disclosures are required for any extension of a lease-purchase agreement.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2299-S.SL.pdf?cite=1992%20c%20134%20§%209[1992 c 134 § 9]; ]

== 63.19.090 - Advertising—Requirements—Liability.
. If an advertisement for a lease-purchase agreement refers to or states the dollar amount of any payment and the right to acquire ownership for any one specific item, the advertisement shall also clearly and conspicuously state the following items, as applicable:

.. That the transaction advertised is a lease-purchase agreement;

.. The total of payments necessary to acquire ownership; and

.. That the consumer acquires no ownership rights if the total amount necessary to acquire ownership is not paid.

. Any owner or personnel of any medium in which an advertisement appears or through which it is disseminated shall not be liable under this section.

. The provisions of subsection (1) of this section shall not apply to an advertisement that does not refer to or state the amount of any payment, or which is published in the yellow pages of a telephone directory or in any similar directory of business.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2299-S.SL.pdf?cite=1992%20c%20134%20§%2010[1992 c 134 § 10]; ]

== 63.19.100 - Upholstered furniture or bedding.
Upon the return of leased upholstered furniture or bedding, the lessor shall sanitize the property. A lessor shall not lease used upholstered furniture or bedding that has not been sanitized.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2299-S.SL.pdf?cite=1992%20c%20134%20§%2011[1992 c 134 § 11]; ]

== 63.19.110 - Violation—Application of chapter  19.86 RCW.
The Washington lease-purchase agreement act is a matter affecting the public interest for the purpose of applying chapter 19.86 RCW. The violation of this chapter is not reasonable in relation to the development and preservation of business. A violation of this chapter constitutes an unfair or deceptive act or practice in trade or commerce for the purpose of applying chapter 19.86 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2299-S.SL.pdf?cite=1992%20c%20134%20§%2012[1992 c 134 § 12]; ]

== 63.19.900 - Short title—1992 c 134.
This act may be known and cited as the Washington lease-purchase agreement act.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2299-S.SL.pdf?cite=1992%20c%20134%20§%201[1992 c 134 § 1]; ]

