= 63.26 - Unclaimed property held by museum or historical society.
:toc:

== 63.26.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Museum or historical society" means an institution operated by a nonprofit corporation, nonprofit association, or public agency, primarily educational, scientific, historic, or aesthetic in purpose, which owns, borrows, studies, or cares for tangible objects, including archives, and exhibits them as appropriate.

. "Property" includes all documents and tangible objects, animate and inanimate, under the care of a museum or historical society which have intrinsic scientific, historic, artistic, or cultural value.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c226.pdf?cite=1988%20c%20226%20§%203[1988 c 226 § 3]; ]

== 63.26.020 - Abandoned property—Notice.
Any property held by a museum or historical society within the state, other than by terms of a loan agreement, that has been held for five years or more and has remained unclaimed shall be deemed to be abandoned. Such property shall become the property of the museum or historical society if the museum or society has given notice pursuant to RCW 63.26.040 and no assertion of title has been filed for the property within ninety days from the date of the second published notice.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c226.pdf?cite=1988%20c%20226%20§%204[1988 c 226 § 4]; ]

== 63.26.030 - Loaned property deemed donated—Notice of owner's change of address—Notice of provisions of chapter.
. Property subject to a loan agreement which is on loan to a museum or historical society shall be deemed to be donated to the museum or society if no claim is made or action filed to recover the property after termination or expiration of the loan and if the museum or society has given notice pursuant to RCW 63.26.040 and no assertion of title has been filed within ninety days from the date of the second published notice.

. A museum or society may terminate a loan of property if the property was loaned to the museum or society for an indefinite term and the property has been held by the museum or society for five years or more. Property on "permanent loan" shall be deemed to be loaned for an indefinite term.

. If property was loaned to the museum or society for a specified term, the museum or society may give notice of termination of the loan at any time after expiration of the specified term.

. It is the responsibility of the owner of property on loan to a museum or society to notify the museum or society promptly in writing of any change of address or change in ownership of the property.

. When a museum or society accepts a loan of property, the museum or society shall inform the owner in writing of the provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c226.pdf?cite=1988%20c%20226%20§%205[1988 c 226 § 5]; ]

== 63.26.040 - Notice of abandonment of property.
. When a museum or historical society is required to give notice of abandonment of property or of termination of a loan, the museum or historical society shall mail such notice by certified mail, return receipt requested, to the last known owner at the most recent address of such owner as shown on the museum's or society's records. If the museum or society has no address on record, or the museum or society does not receive written proof of receipt of the mailed notice within thirty days of the date the notice was mailed, the museum or society shall publish notice, at least once each week for two consecutive weeks, in a newspaper of general circulation in both the county in which the museum is located and the county in which the last known address, if available, of the owner is located.

. The published notice shall contain:

.. A description of the unclaimed property;

.. The name and last known address of the owner;

.. A request that all persons who may have any knowledge of the whereabouts of the owner provide written notice to the museum or society; and

.. A statement that if written assertion of title is not presented by the owner to the museum or society within ninety days from the date of the second published notice, the property shall be deemed abandoned or donated and shall become the property of the museum or society.

. For purposes of this chapter, if the loan of property was made to a branch of a museum or society, the museum or society is deemed to be located in the county in which the branch is located. Otherwise the museum or society is located in the county in which it has its principal place of business.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c226.pdf?cite=1988%20c%20226%20§%206[1988 c 226 § 6]; ]

== 63.26.050 - Vesting of title in museum or historical society—Subsequent purchase from museum or historical society.
. If no written assertion of title has been presented by the owner to the museum or society within ninety days from the date of the second published notice, title to the property shall vest in the museum or historical society, free of all claims of the owner and of all persons claiming under the owner.

. One who purchases or otherwise acquires property from a museum or historical society acquires good title to the property if the museum or society has acquired title to the property under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c226.pdf?cite=1988%20c%20226%20§%207[1988 c 226 § 7]; ]

