= 63.35 - Unclaimed property in hands of state patrol.
:toc:

== 63.35.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Agency" means the Washington state patrol.

. "Chief" means the chief of the Washington state patrol or designee.

. "Personal property" or "property" includes both corporeal and incorporeal personal property and includes, among other property, contraband and money.

. "Contraband" means any property which is unlawful to produce or possess.

. "Money" means all currency, script, personal checks, money orders, or other negotiable instruments.

. "Owner" means the person in whom is vested the ownership, dominion, or title of the property.

. "Unclaimed" means that no owner of the property has been identified or has requested, in writing, the release of the property to themselves nor has the owner of the property designated an individual to receive the property or paid the required postage to effect delivery of the property.

. "Illegal items" means those items unlawful to be possessed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c222.pdf?cite=1989%20c%20222%20§%201[1989 c 222 § 1]; ]

== 63.35.020 - Methods of disposition—Sale, retention, destruction, or trade.
Whenever any personal property shall come into the possession of the officers of the state patrol in connection with the official performance of their duties and said personal property shall remain unclaimed or not taken away for a period of sixty days from the date of written notice to the owner thereof, if known, which notice shall inform the owner of the disposition which may be made of the property under this section and the time that the owner has to claim the property and in all other cases for a period of sixty days from the time said property came into the possession of the state agency, unless said property has been held as evidence in any court, then, in that event, after sixty days from date when said case has been finally disposed of and said property released as evidence by order of the court, said agency may:

. At any time thereafter sell said personal property at public auction to the highest and best bidder for cash in the manner hereinafter provided;

. Retain the property for the use of the state patrol subject to giving notice in the manner prescribed in RCW 63.35.030 and the right of the owner, or the owner's legal representative, to reclaim the property within one year after receipt of notice, without compensation for ordinary wear and tear if, in the opinion of the chief, the property consists of firearms or other items specifically usable in law enforcement work: PROVIDED, That at the end of each calendar year during which there has been such a retention, the state patrol shall provide the office of financial management and retain for public inspection a list of such retained items and an estimation of each item's replacement value;

. Destroy an item of personal property at the discretion of the chief if the chief determines that the following circumstances have occurred:

.. The property has no substantial commercial value, or the probable cost of sale exceeds the value of the property;

.. The item has been unclaimed by any person after notice procedures have been met, as prescribed in this section; and

.. The chief has determined that the item is illegal to possess or sell or unsafe and unable to be made safe for use by any member of the general public;

. If the item is not unsafe or illegal to possess or sell, such item, after satisfying the notice requirements as prescribed in this section may be offered by the chief to bona fide dealers, in trade for law enforcement equipment, which equipment shall be treated as retained property for purpose of annual listing requirements of subsection (2) of this section; or

. At the end of one year, any unclaimed firearm shall be disposed of pursuant to RCW 9.41.098(2). Any other item which is not unsafe or illegal to possess or sell, but has been, or may be used, in the judgment of the chief, in a manner that is illegal, may be destroyed.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c222.pdf?cite=1989%20c%20222%20§%202[1989 c 222 § 2]; ]

== 63.35.030 - Notice of sale.
Before said personal property shall be sold, a notice of such sale fixing the time and place thereof which shall be at a suitable place, which will be noted in the advertisement for sale, and containing a description of the property to be sold shall be published at least once in a newspaper of general circulation in the county in which the property is to be sold at least ten days prior to the date fixed for the auction. The notice shall be signed by the chief. If the owner fails to reclaim said property prior to the time fixed for the sale in such notice, the chief shall conduct said sale and sell the property described in the notice at public auction to the highest and best bidder for cash, and upon payment of the amount of such bid shall deliver the said property to such bidder.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c222.pdf?cite=1989%20c%20222%20§%203[1989 c 222 § 3]; ]

== 63.35.040 - Disposition of proceeds.
The moneys arising from sales under the provisions of this chapter shall be first applied to the payment of the costs and expenses of the sale and then to the payment of lawful charges and expenses for the keep of said personal property and the balance, if any, shall be forwarded to the state treasurer to be deposited into the state patrol highway account.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c222.pdf?cite=1989%20c%20222%20§%204[1989 c 222 § 4]; ]

== 63.35.050 - Reimbursement to owner.
If the owner of said personal property so sold, or the owner's legal representative, shall, at any time within three years after such money shall have been deposited in the state patrol highway account, furnish satisfactory evidence to the state treasurer of the ownership of said personal property, the owner or the owner's legal representative shall be entitled to receive from said state patrol highway account the amount so deposited therein with interest.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c222.pdf?cite=1989%20c%20222%20§%205[1989 c 222 § 5]; ]

== 63.35.060 - Applicability of other statutes.
. Chapter 63.24 RCW, unclaimed property in hands of bailee, does not apply to personal property in the possession of the state patrol.

. The uniform unclaimed property act, chapter 63.29 RCW, does not apply to personal property in the possession of the state patrol.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c222.pdf?cite=1989%20c%20222%20§%206[1989 c 222 § 6]; ]

== 63.35.065 - Donation of unclaimed personal property to nonprofit charitable organizations.
In addition to any other method of disposition of unclaimed property provided under this chapter, the state patrol may donate unclaimed personal property to nonprofit charitable organizations. A nonprofit charitable organization receiving personal property donated under this section must use the property, or its proceeds, to benefit needy persons. Such organization must qualify for tax-exempt status under 26 U.S.C. Sec. 501(c)(3) of the federal internal revenue code.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5193-S.SL.pdf?cite=2007%20c%20219%20§%202[2007 c 219 § 2]; ]

