= 63.60 - Personality rights.
:toc:

== 63.60.010 - Property right—Use of name, voice, signature, photograph, or likeness.
Every individual or personality has a property right in the use of his or her name, voice, signature, photograph, or likeness. Such right exists in the name, voice, signature, photograph, or likeness of individuals or personalities deceased before, on, or after June 11, 1998. This right shall be freely transferable, assignable, and licensable, in whole or in part, by any otherwise permissible form of inter vivos or testamentary transfer, including without limitation a will or other testamentary instrument, trust, contract, community property agreement, or cotenancy with survivorship provisions or payable-on-death provisions, whether the will or other testamentary instrument, trust, contract, community property agreement, or cotenancy document is entered into or executed before, on, or after June 11, 1998, by the deceased individual or personality or by any subsequent owner of the deceased individual's or personality's rights as recognized by this chapter; or, if none is applicable, then the owner of the rights shall be determined under the laws of intestate succession applicable to interests in intangible personal property. The property right does not expire upon the death of the individual or personality, regardless of whether the law of the domicile, residence, or citizenship of the individual or personality at the time of death or otherwise recognizes a similar or identical property right. The right exists whether or not it was commercially exploited by the individual or the personality during the individual's or the personality's lifetime. The rights recognized under this chapter shall be deemed to have existed before June 11, 1998, and at the time of death of any deceased individual or personality or subsequent successor of their rights for the purpose of determining the person or persons entitled to these property rights as provided in RCW 63.60.030. This chapter is intended to apply to all individuals and personalities, living and deceased, regardless of place of domicile or place of domicile at time of death.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2727-S.SL.pdf?cite=2008%20c%2062%20§%201[2008 c 62 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1074-S.SL.pdf?cite=1998%20c%20274%20§%201[1998 c 274 § 1]; ]

== 63.60.020 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Deceased individual" means any individual, regardless of the individual's place of domicile, residence, or citizenship at the time of death or otherwise, who has died within ten years before January 1, 1998, or thereafter.

. "Deceased personality" means any individual, regardless of the personality's place of domicile, residence, or citizenship at the time of death or otherwise, whose name, voice, signature, photograph, or likeness had commercial value at the time of his or her death, whether or not during the lifetime of that individual he or she used his or her name, voice, signature, photograph, or likeness on or in products, merchandise or goods, or for purposes of advertising or selling, or soliciting the purchase or sale of, products, merchandise, goods, or services. A "deceased personality" includes, without limitation, any such individual who has died within fifty years before January 1, 1998, or thereafter.

. "Fund-raising" means an organized activity to solicit donations of money or other goods or services from persons or entities by an organization, company, or public entity. A fund-raising activity does not include a live, public performance by an individual or group of individuals for which money is received in solicited or unsolicited gratuities.

. "Individual" means a natural person, living or dead.

. "Likeness" means an image, painting, sketching, model, diagram, or other clear representation, other than a photograph, of an individual's face, body, or parts thereof, or the distinctive appearance, gestures, or mannerisms of an individual.

. "Name" means the actual or assumed name, or nickname, of a living or deceased individual that is intended to identify that individual.

. "Person" means any natural person, firm, association, partnership, corporation, joint stock company, syndicate, receiver, common law trust, conservator, statutory trust, or any other concern by whatever name known or however organized, formed, or created, and includes not-for-profit corporations, associations, educational and religious institutions, political parties, and community, civic, or other organizations.

. "Personality" means any individual whose name, voice, signature, photograph, or likeness has commercial value, whether or not that individual uses his or her name, voice, signature, photograph, or likeness on or in products, merchandise, or goods, or for purposes of advertising or selling, or solicitation of purchase of, products, merchandise, goods, or services.

. "Photograph" means any photograph or photographic reproduction, still or moving, or any videotape, online or live television transmission, of any individual, so that the individual is readily identifiable.

. "Signature" means the one handwritten or otherwise legally binding form of an individual's name, written or authorized by that individual, that distinguishes the individual from all others.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2727-S.SL.pdf?cite=2008%20c%2062%20§%202[2008 c 62 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1580.SL.pdf?cite=2004%20c%2071%20§%201[2004 c 71 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1074-S.SL.pdf?cite=1998%20c%20274%20§%202[1998 c 274 § 2]; ]

== 63.60.030 - Transfer, assignment, and license.
. Every individual or personality has a property right in the use of his or her name, voice, signature, photograph, or likeness. Such right shall be freely transferable, assignable, and licensable, in whole or in part, by contract or inter vivos transfer. This right shall not expire upon the death of the individual or personality, but shall be owned and enforceable by the following successors, heirs, or other transferees of living or deceased individuals or personalities:

.. Except where such rights were transferred or assigned before such deceased personality's death by means of any contract or trust instrument, the right shall be owned by the person entitled to such rights under the deceased individual's or personality's last will and testament or, if none, then by the beneficiaries or heirs under the laws of intestate succession applicable to interests in intangible personal property generally of the individual's or personality's domicile, regardless of whether the law of the domicile of the deceased individual or personality, at the time of death, or thereafter, recognizes a similar or identical property right; or

.. If the deceased individual or personality transferred or assigned any interest in the personality rights during his or her life by means of any contract or trust instrument, then the transferred or assigned interest shall be held as follows:

... If the transferred or assigned interest was held in trust, in accordance with the terms of the trust;

... If the interest is subject to a cotenancy with any survivorship provisions or payable-on-death provisions, in accordance with those provisions;

... If the interest is subject to any contract, including without limitation an exclusive license, assignment, or a community property agreement, in accordance with the terms of the applicable contract or contracts;

... If the interest has been transferred or assigned to a third person in a form that is not addressed in this section, by the individual or personality, or the successor, heir, or other transferee of the living or deceased individual or personality, then the interest may be transferred, assigned, or licensed by such third person, in whole or in part, by any otherwise permissible form of inter vivos or testamentary transfer or, if none is applicable, under the laws of intestate succession applicable to interests in intangible personal property of the third person's domicile, regardless of whether the law of the domicile of the deceased third party, at the time of death, or thereafter, recognizes a similar or identical property right.

. A property right exists whether or not such rights were commercially exploited by or under the authority of the individual or the personality or the individual's or personality's successors or transferees during the individual's or the personality's lifetime.

. The rights recognized under this chapter shall be deemed to have existed before June 11, 1998, and at the time of death of any deceased individual or personality or subsequent successor of their rights for the purpose of determining the person or persons entitled to these property rights as provided in this section.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2727-S.SL.pdf?cite=2008%20c%2062%20§%203[2008 c 62 § 3]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1074-S.SL.pdf?cite=1998%20c%20274%20§%203[1998 c 274 § 3]; ]

== 63.60.040 - Right is exclusive for individuals and personalities.
. For individuals, except to the extent that the individual may have assigned or licensed such rights, the rights protected in this chapter are exclusive to the individual, subject to the assignment or licensing of such rights, during such individual's lifetime and are exclusive to the persons entitled to such rights under RCW 63.60.030 for a period of ten years after the death of the individual except to the extent that the persons entitled to such rights under RCW 63.60.030 may have assigned or licensed such rights to others.

. For personalities, except to the extent that the personality may have assigned or licensed such rights, the rights protected in this chapter are exclusive to the personality, subject to the assignment or licensing of such rights, during such personality's lifetime and to the persons entitled to such rights under RCW 63.60.030 for a period of seventy-five years after the death of the personality except to the extent that the persons entitled to such rights under RCW 63.60.030 may have assigned or licensed such rights to others.

. The rights granted in this chapter may be exercised by a personal representative, attorney-in-fact, parent of a minor child, or guardian, or as authorized by a court of competent jurisdiction. The terms "personal representative," "attorney-in-fact," and "guardian" shall have the same meanings in this chapter as they have in Title 11 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1580.SL.pdf?cite=2004%20c%2071%20§%202[2004 c 71 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1074-S.SL.pdf?cite=1998%20c%20274%20§%204[1998 c 274 § 4]; ]

== 63.60.050 - Infringement of right—Use without consent—Profit or not for profit.
Any person who uses or authorizes the use of a living or deceased individual's or personality's name, voice, signature, photograph, or likeness, on or in goods, merchandise, or products entered into commerce in this state, or for purposes of advertising products, merchandise, goods, or services, or for purposes of fund-raising or solicitation of donations, or if any person disseminates or publishes such advertisements in this state, without written or oral, express or implied consent of the owner of the right, has infringed such right. An infringement may occur under this section without regard to whether the use or activity is for profit or not for profit.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1074-S.SL.pdf?cite=1998%20c%20274%20§%205[1998 c 274 § 5]; ]

== 63.60.060 - Infringement of right—Superior courts—Injunctions—Liability for damages and profits—Impoundment—Destruction—Attorneys' fees.
. The superior courts of this state may grant injunctions on reasonable terms to prevent or restrain the unauthorized use of the rights in a living or deceased individual's or personality's name, voice, signature, photograph, or likeness.

. Any person who infringes the rights under this chapter shall be liable for the greater of one thousand five hundred dollars or the actual damages sustained as a result of the infringement, and any profits that are attributable to the infringement and not taken into account when calculating actual damages. To prove profits under this section, the injured party or parties must submit proof of gross revenues attributable to the infringement, and the infringing party is required to prove his or her deductible expenses. For the purposes of computing statutory damages, use of a name, voice, signature, photograph, and/or likeness in or related to one work constitutes a single act of infringement regardless of the number of copies made or the number of times the name, voice, signature, photograph, or likeness is displayed.

. At any time while an action under this chapter is pending, the court may order the impounding, on reasonable terms, of all materials or any part thereof claimed to have been made or used in violation of the injured party's rights, and the court may enjoin the use of all plates, molds, matrices, masters, tapes, film negatives, or other articles by means of which such materials may be reproduced.

. As part of a final judgment or decree, the court may order the destruction or other reasonable disposition of all materials found to have been made or used in violation of the injured party's rights, and of all plates, molds, matrices, masters, tapes, film negatives, or other articles by means of which such materials may be reproduced.

. The prevailing party may recover reasonable attorneys' fees, expenses, and court costs incurred in recovering any remedy or defending any claim brought under this section.

. The remedies provided for in this section are cumulative and are in addition to any others provided for by law.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1074-S.SL.pdf?cite=1998%20c%20274%20§%206[1998 c 274 § 6]; ]

== 63.60.070 - Exemptions from use restrictions—When chapter does not apply.
. For purposes of RCW 63.60.050, the use of a name, voice, signature, photograph, or likeness in connection with matters of cultural, historical, political, religious, educational, newsworthy, or public interest, including, without limitation, comment, criticism, satire, and parody relating thereto, shall not constitute a use for which consent is required under this chapter. A matter exempt from consent under this subsection does not lose such exempt status because it appears in the form of a paid advertisement if it is clear that the principal purpose of the advertisement is to comment on such matter.

. This chapter does not apply to the use or authorization of use of an individual's or personality's name, voice, signature, photograph, or likeness, in any of the following:

.. Single and original works of fine art, including but not limited to photographic, graphic, and sculptural works of art that are not published in more than five copies;

.. A literary work, theatrical work, musical composition, film, radio, online or television program, magazine article, news story, public affairs report, or sports broadcast or account, or with any political campaign when the use does not inaccurately claim or state an endorsement by the individual or personality;

.. An advertisement or commercial announcement for a use permitted by subsections (1) and (7) of this section and (a) or (b) of this subsection;

.. An advertisement, commercial announcement, or packaging for the authorized sale, distribution, performance, broadcast, or display of a literary, musical, cinematographic, or other artistic work using the name, voice, signature, photograph, or likeness of the writer, author, composer, director, actor, or artist who created the work, where such individual or personality consented to the use of his or her name, voice, signature, photograph, or likeness on or in connection with the initial sale, distribution, performance, or display thereof; and

.. The advertisement or sale of a rare or fine product, including but not limited to books, which incorporates the signature of the author.

. It is no defense to an infringement action under this chapter that the use of an individual's or personality's name, voice, signature, photograph, or likeness includes more than one individual or personality so identifiable. However, the individuals or personalities complaining of the use shall not bring their cause of action as a class action.

. RCW 63.60.050 does not apply to the owners or employees of any medium used for advertising, including but not limited to, newspapers, magazines, radio and television stations, online service providers, billboards, and transit ads, who have published or disseminated any advertisement or solicitation in violation of this chapter, unless the advertisement or solicitation was intended to promote the medium itself.

. This chapter does not apply to a use or authorization of use of an individual's or personality's name that is merely descriptive and used fairly and in good faith only to identify or describe something other than the individual or personality, such as, without limitation, to describe or identify a place, a legacy, a style, a theory, an ownership interest, or a party to a transaction or to accurately describe the goods or services of a party.

. This chapter does not apply to the use of an individual's or personality's name, voice, signature, photograph, or likeness when the use of the individual's or personality's name, voice, signature, photograph, or likeness is an insignificant, de minimis, or incidental use.

. This chapter does not apply to the distribution, promotion, transfer, or license of a photograph or other material containing an individual's or personality's name, voice, signature, photograph, or likeness to a third party for use in a manner which is lawful under this chapter, or to a third party for further distribution, promotion, transfer, or license for use in a manner which is lawful under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/House/1580.SL.pdf?cite=2004%20c%2071%20§%203[2004 c 71 § 3]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1074-S.SL.pdf?cite=1998%20c%20274%20§%207[1998 c 274 § 7]; ]

== 63.60.080 - Community property rights.
Nothing contained in this chapter is intended to invalidate any community property rights.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1074-S.SL.pdf?cite=1998%20c%20274%20§%208[1998 c 274 § 8]; ]

