= 35A.82 - Taxation—Excises.
:toc:

== 35A.82.010 - State shared excises.
A code city shall collect, receive and share in the distribution of state collected and distributed excise taxes to the same extent and manner as general laws relating thereto apply to any class of city or town including, but not limited to, funds distributed to cities under *RCW 82.36.020 relating to motor vehicle fuel tax, RCW 82.38.290 relating to use fuel tax, and RCW * 82.36.275 and ** 82.38.080(3).

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2659-S.SL.pdf?cite=1998%20c%20176%20§%202[1998 c 176 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1225.SL.pdf?cite=1995%20c%20274%20§%204[1995 c 274 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%20102[1985 c 7 § 102]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%2074[1983 c 3 § 74]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.82.010[1967 ex.s. c 119 § 35A.82.010]; ]

== 35A.82.020 - Licenses and permits—Excises for regulation.
A code city may exercise the authority authorized by general law for any class of city to license and revoke the same for cause, to regulate, make inspections and to impose excises for regulation or revenue in regard to all places and kinds of business, production, commerce, entertainment, exhibition, and upon all occupations, trades and professions and any other lawful activity: PROVIDED, That no license or permit to engage in any such activity or place shall be granted to any who shall not first comply with the general laws of the state.

No such license shall be granted to continue for longer than a period of one year from the date thereof and no license or excise shall be required where the same shall have been preempted by the state, nor where exempted by the state, including, but not limited to, the provisions of RCW 36.71.090 and chapter 73.04 RCW relating to veterans.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.82.020[1967 ex.s. c 119 § 35A.82.020]; ]

== 35A.82.025 - Authority to regulate massage therapists—Limitations.
. A state licensed massage therapist seeking a city license to operate a massage business must provide verification of his or her state massage license as provided for in RCW 18.108.030.

. The city may charge a licensing or operating fee, but the fee charged a state licensed massage therapist shall not exceed the licensing or operating fee imposed on similar health care providers, such as physical therapists or occupational therapists, operating within the same city.

. A state licensed massage therapist is not subject to additional licensing requirements not currently imposed on similar health care providers, such as physical therapists or occupational therapists.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2425-S.SL.pdf?cite=2016%20c%2041%20§%2024[2016 c 41 § 24]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1911-S.SL.pdf?cite=1991%20c%20182%20§%202[1991 c 182 § 2]; ]

== 35A.82.030 - City and county retail sales excise tax and use tax.
See chapter 82.14 RCW.

[ ]

== 35A.82.040 - City and town license fees and taxes on financial institutions.
See chapter 82.14A RCW.

[ ]

== 35A.82.042 - City license fees or taxes on certain business activities to be at a single uniform rate.
See RCW 35.21.710.

[ ]

== 35A.82.050 - License fees or taxes upon certain business activities to be at single uniform rate.
Any code city which imposes a license fee or tax upon business activities consisting of the making of retail sales of tangible personal property which are measured by gross receipts or gross income from such sales, shall impose such tax at a single uniform rate upon all such business activities. This section shall not apply to any business activities subject to the tax imposed by chapter 82.16 RCW. For purposes of this section, the providing to consumers of competitive telephone service, as defined in RCW 82.04.065, or the providing of payphone service as defined in RCW 35.21.710, shall be subject to tax at the same rate as business activities consisting of the making of retail sales of tangible personal property.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2031-S.SL.pdf?cite=2002%20c%20179%20§%203[2002 c 179 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex2c3.pdf?cite=1983%202nd%20ex.s.%20c%203%20§%2034[1983 2nd ex.s. c 3 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c144.pdf?cite=1981%20c%20144%20§%207[1981 c 144 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c134.pdf?cite=1972%20ex.s.%20c%20134%20§%207[1972 ex.s. c 134 § 7]; ]

== 35A.82.055 - License fees or taxes on telephone business to be at uniform rate.
Any code city which imposes a license fee or tax upon the business activity of engaging in the telephone business, as defined in RCW 82.16.010, which is measured by gross receipts or gross income from the business shall impose the tax at a uniform rate on all persons engaged in the telephone business in the code city.

This section does not apply to the providing of competitive telephone service as defined in RCW 82.04.065 or to the providing of payphone service as defined in RCW 35.21.710.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5089-S.SL.pdf?cite=2007%20c%206%20§%201012[2007 c 6 § 1012]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2031-S.SL.pdf?cite=2002%20c%20179%20§%204[2002 c 179 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex2c3.pdf?cite=1983%202nd%20ex.s.%20c%203%20§%2036[1983 2nd ex.s. c 3 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c144.pdf?cite=1981%20c%20144%20§%209[1981 c 144 § 9]; ]

== 35A.82.060 - License fees or taxes on telephone business—Imposition on certain gross revenues authorized—Limitations.
. Any code city which imposes a license fee or tax upon the business activity of engaging in the telephone business which is measured by gross receipts or gross income may impose the fee or tax, if it desires, on one hundred percent of the total gross revenue derived from intrastate toll telephone services subject to the fee or tax: PROVIDED, That the city shall not impose the fee or tax on that portion of network telephone service which represents charges to another telecommunications company, as defined in RCW 80.04.010, for connecting fees, switching charges, or carrier access charges relating to intrastate toll telephone services, or for access to, or charges for, interstate services, or charges for network telephone service that is purchased for the purpose of resale, or charges for mobile telecommunications services provided to customers whose place of primary use is not within the city.

. Any city that imposes a license tax or fee under subsection (1) of this section has the authority, rights, and obligations of a taxing jurisdiction as provided in RCW 82.32.490 through 82.32.510.

. The definitions in RCW 82.04.065 and 82.16.010 apply to this section.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5089-S.SL.pdf?cite=2007%20c%206%20§%201014[2007 c 6 § 1014]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5089-S.SL.pdf?cite=2007%20c%206%20§%201013[2007 c 6 § 1013]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6539.SL.pdf?cite=2002%20c%2067%20§%2010[2002 c 67 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c103.pdf?cite=1989%20c%20103%20§%203[1989 c 103 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c70.pdf?cite=1986%20c%2070%20§%204[1986 c 70 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex2c3.pdf?cite=1983%202nd%20ex.s.%20c%203%20§%2038[1983 2nd ex.s. c 3 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c144.pdf?cite=1981%20c%20144%20§%2011[1981 c 144 § 11]; ]

== 35A.82.065 - Taxes on network telephone services.
Notwithstanding RCW 35.21.714 or 35A.82.060, any city or town which imposes a tax upon business activities measured by gross receipts or gross income from sales, may impose such tax on that portion of network telephone service, as defined in RCW 82.16.010, which represents charges to another telecommunications company, as defined in RCW 80.04.010, for connecting fees, switching charges, or carrier access charges relating to intrastate toll services, or charges for network telephone service that is purchased for the purpose of resale. Such tax shall be levied at the same rate as is applicable to other competitive telephone service as defined in RCW 82.04.065.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5089-S.SL.pdf?cite=2007%20c%206%20§%201015[2007 c 6 § 1015]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c103.pdf?cite=1989%20c%20103%20§%204[1989 c 103 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c70.pdf?cite=1986%20c%2070%20§%205[1986 c 70 § 5]; ]

== 35A.82.070 - Taxes on telephone business—Deferral of rate reduction.
A city or town required by RCW 35.21.870(2) to reduce its rate of taxation on telephone business may defer for one year the required reduction in rates for the year 1987. If the delay in rate reductions authorized by the preceding sentence is inadequate for a code city to offset the impact of revenue reductions arising from the removal of revenues from connecting fees, switching charges, or carrier access charges under the provisions of RCW 35A.82.060, then the legislative body of such code city may reimpose for 1987 the rates that such code city had in effect upon telephone business during 1985. In each succeeding year, the city or town shall reduce the rate by one-tenth of the difference between the tax rate on April 20, 1982, and six percent.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c70.pdf?cite=1986%20c%2070%20§%206[1986 c 70 § 6]; ]

