= 35A.64 - Public property, real and personal.
:toc:

== 35A.64.010 - Acquisition of by conditional sales contracts.
A code city may exercise the powers relating to acquisition of real or personal property under executory conditional sales contracts as authorized by RCW 39.30.010.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.64.010[1967 ex.s. c 119 § 35A.64.010]; ]

== 35A.64.020 - Purchase of products made by blind.
A code city may exercise the powers relating to the acquisition of products made by the blind as authorized by RCW 19.06.020.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.64.020[1967 ex.s. c 119 § 35A.64.020]; ]

== 35A.64.180 - Disinfection of property.
Every code city shall disinfect or destroy all infected trees or shrubs growing upon public property within the city's jurisdiction and may expend city funds in carrying out the provisions of this section, and shall otherwise be governed by the provisions of chapter 15.08 RCW relating to horticultural pests and diseases.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.64.180[1967 ex.s. c 119 § 35A.64.180]; ]

== 35A.64.200 - Eminent domain by cities.
A code city may exercise all powers relating to eminent domain as authorized by chapters 8.12 and 8.28 RCW in accordance with the procedures therein prescribed and subject to any limitations therein provided.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.64.200[1967 ex.s. c 119 § 35A.64.200]; ]

