= 35A.21 - Provisions affecting all code cities.
:toc:

== 35A.21.010 - Validity of ordinances and resolutions—Deficiencies of form.
Deficiencies in the form of an ordinance or resolution shall not affect the validity thereof if the following requirements are met:

. The purpose and intent of the ordinance or resolution are clear.

. Any regulatory or procedural provisions thereof are expressed in clear and unambiguous terms, or the legislative intent can be determined by usual methods of judicial construction.

. The legislative action was taken at an authorized public meeting held within the code city limits at a time and place made known to residents of the city, as provided by law.

. The legislative body of the code city followed the prescribed procedures, if any, for passage of such an ordinance or resolution, as provided in the law or charter provision delegating to the legislative body the authority to so legislate; or, if prescribed procedures were not strictly complied with, no substantial detriment was incurred by any affected person, by reason of such irregularity.

If the foregoing requirements have been met, brevity or awkwardness of language, or defects of form not going to the substance, or inadvertent use of an incorrect or inaccurate proper name or term shall not render an ordinance or resolution invalid, if otherwise in compliance with law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.21.010[1967 ex.s. c 119 § 35A.21.010]; ]

== 35A.21.020 - Conflict between charter and optional code.
This optional municipal code is intended to be a general law, available to all cities and towns within the state, and to all legal intents and purposes a "general law" within the meaning of Article 11, section 10 of the state Constitution, as amended.

If any provision of this title is in conflict with any provision of the charter or amendments thereto of any charter code city, the provisions of this title shall govern and control, except where the legislative body of such charter code city, by ordinance, elects to retain such charter provision or amendment, in which event such charter provision shall prevail notwithstanding a conflict with provisions of this optional code: PROVIDED, That such ordinance shall be subject to referendum as provided in RCW 35A.29.170.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.21.020[1967 ex.s. c 119 § 35A.21.020]; ]

== 35A.21.030 - Mandatory duties of code city officers.
Except as otherwise provided in this title, every officer of a code city shall perform, in the manner provided, all duties of his or her office which are imposed by state law on officers of every other class of city who occupy a like position and perform like functions.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5038.SL.pdf?cite=2009%20c%20549%20§%203031[2009 c 549 § 3031]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.21.030[1967 ex.s. c 119 § 35A.21.030]; ]

== 35A.21.040 - Merit systems.
Provisions for a merit system, made by charter or ordinance of a code city, shall be in compliance with any applicable statutes relating to civil service for employees of such city: PROVIDED, That nothing herein shall impair the validity of charter provisions adopted prior to the effective date of this title and relating to a merit system.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.21.040[1967 ex.s. c 119 § 35A.21.040]; ]

== 35A.21.050 - Pension and retirement systems.
Nothing in this title shall be construed to alter or affect vested rights of city employees under pension and retirement systems in effect at the time this title becomes effective.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.21.050[1967 ex.s. c 119 § 35A.21.050]; ]

== 35A.21.060 - Garbage ordinance—Lien—Foreclosure.
A garbage ordinance of a code city may contain the provisions authorized by RCW 35.21.130. Notice shall be given of a lien for garbage collection and disposal service, the lien shall have priority and be foreclosed all as provided in RCW 35.21.140 and 35.21.150.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.21.060[1967 ex.s. c 119 § 35A.21.060]; ]

== 35A.21.070 - Office hours prescribed by ordinance.
All code city offices shall be kept open for the transaction of business during such days and hours as the legislative body of such city shall by ordinance prescribe.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.21.070[1967 ex.s. c 119 § 35A.21.070]; ]

== 35A.21.080 - Computation of time.
When, under the provisions of this title, an act is to be done within a certain time period, the time shall be computed by excluding the first day and including the last, except that when the last day is a Saturday, Sunday, or a day designated by RCW 1.16.050 or by the city's ordinances as a holiday, then it also is excluded and the act must be completed on the next business day.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.21.080[1967 ex.s. c 119 § 35A.21.080]; ]

== 35A.21.090 - Jurisdiction over adjacent waters—Control of street over tidelands.
The legislative body of a code city shall have supervision and control within its corporate limits of streets over tidelands or upon or across tide and shore lands of the first class as provided in RCW 35.21.230, 35.21.240 and 35.21.250; and shall have jurisdiction over adjacent waters as provided in RCW 35.21.160.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.21.090[1967 ex.s. c 119 § 35A.21.090]; ]

== 35A.21.100 - Lien for utility services.
Code cities owning or operating waterworks or electric light distribution or power plants shall have a lien for such utility services as provided by RCW 35.21.290 for cities owning such plants and as limited therein, which lien may be enforced only as provided in RCW 35.21.300.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.21.100[1967 ex.s. c 119 § 35A.21.100]; ]

== 35A.21.110 - Warrants—Interest rate—Payment.
Code city warrants shall draw interest, be paid, and called for all as provided in RCW 35.21.320 and the duty and liability of the treasurer of a code city in calling and paying warrants of the city shall be as provided in RCW 35.21.320.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.21.110[1967 ex.s. c 119 § 35A.21.110]; ]

== 35A.21.120 - Utilities—Facilities for generation of electricity.
Any code city owning and operating a public utility and having facilities and/or land for the generation of electricity shall be governed by the provisions of RCW 35.21.420 through 35.21.450.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.21.120[1967 ex.s. c 119 § 35A.21.120]; ]

== 35A.21.125 - Locally regulated utilities—Attachments to poles.
. As used in this section:

.. "Attachment" means the affixation or installation of any wire, cable or other physical material capable of carrying electronic impulses or light waves for the carrying of intelligence for telecommunications or television, including, but not limited to cable, and any related device, apparatus, or auxiliary equipment upon any pole owned or controlled in whole or in part by one or more locally regulated utilities where the installation has been made with the necessary consent.

.. "Locally regulated utility" means a code city owning and operating an electric utility not subject to rate or service regulation by the utilities and transportation commission.

.. "Nondiscriminatory" means that pole owners may not arbitrarily differentiate among or between similar classes of persons approved for attachments.

. All rates, terms, and conditions made, demanded or received by a locally regulated utility for attachments to its poles must be just, reasonable, nondiscriminatory and sufficient. A locally regulated utility shall levy attachment space rental rates that are uniform for the same class of service within the locally regulated utility service area.

. Nothing in this section shall be construed or is intended to confer upon the utilities and transportation commission any authority to exercise jurisdiction over locally regulated utilities.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/6554-S.SL.pdf?cite=1996%20c%2032%20§%204[1996 c 32 § 4]; ]

== 35A.21.130 - Codification of ordinances.
Compilation, codification, and revision of code city ordinances shall be as provided by and be governed by the provisions of RCW 35.21.500 through 35.21.570.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.21.130[1967 ex.s. c 119 § 35A.21.130]; ]

== 35A.21.140 - Change of name.
Any code city may change its name in accordance with the procedure provided in chapter 35.62 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.21.140[1967 ex.s. c 119 § 35A.21.140]; ]

== 35A.21.150 - Sewerage and refuse collection and disposal systems.
The general law as contained in, but not limited to, chapter 35.67 RCW, relating to sewerage systems and the collection and disposal of refuse, the manner of providing therefor, and the issuance of general obligation or revenue bonds therefor, the establishment of a revenue bond fund in connection therewith, compulsory connection with a city sewer system, setting and collection of rates, fees, and charges therefor, and the existence, enforcement, and foreclosure of a lien for sewer services is hereby recognized as applicable to code cities operating systems of sewerage and systems and plants for refuse collection and disposal. A code city may exercise the powers, in the manner provided, perform the duties, and shall have the rights and obligations provided in chapter 35.67 RCW, subject to the conditions and limitations therein provided.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.21.150[1967 ex.s. c 119 § 35A.21.150]; ]

== 35A.21.152 - Solid waste collection—Rate increase notice.
. A city that contracts for the collection of solid waste, or provides for the collection of solid waste directly, shall notify the public of each proposed rate increase for a solid waste handling service. The notice may be mailed to each affected ratepayer or published once a week for two consecutive weeks in a newspaper of general circulation in the collection area. The notice shall be available to affected ratepayers at least forty-five days prior to the proposed effective date of the rate increase.

. For purposes of this section, "solid waste handling" has the same meaning as provided in RCW 70A.205.015.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201016[2020 c 20 § 1016]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2226-S.SL.pdf?cite=1994%20c%20161%20§%203[1994 c 161 § 3]; ]

== 35A.21.153 - Solid waste collection curbside recycling—Reduced rate.
. Each city or town providing by ordinance or resolution a reduced solid waste collection rate to residents participating in a residential curbside recycling program implemented under RCW 70A.205.045, may provide a similar reduced rate to residents participating in any other recycling program, if such program is approved by the jurisdiction. Nothing in this section shall be interpreted to reduce the authority of a city to adopt ordinances under RCW 35.21.130(1).

. For the purposes of this section, "reduced rate" means a residential solid waste collection rate incorporating a rebate, refund, or discount. Reduced rate shall not include residential solid waste collection rate based on the volume or weight of solid waste set out for collection.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201017[2020 c 20 § 1017]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5591-S2.SL.pdf?cite=1991%20c%20319%20§%20405[1991 c 319 § 405]; ]

== 35A.21.155 - Collection and transportation of recyclable materials by recycling companies or nonprofit entities—Reuse or reclamation—Application of chapter.
Nothing in this chapter shall prevent a recycling company or nonprofit entity from collecting and transporting recyclable materials from a buy-back center, drop-box, or from a commercial or industrial generator of recyclable materials, or upon agreement with a solid waste collection company.

Nothing in this chapter shall be construed as prohibiting a commercial or industrial generator of commercial recyclable materials from selling, conveying, or arranging for transportation of such material to a recycler for reuse or reclamation.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c431.pdf?cite=1989%20c%20431%20§%2035[1989 c 431 § 35]; ]

== 35A.21.160 - General application of laws to code cities.
A code city organized or reorganized under this title shall have all of the powers which any city of any class may have and shall be governed in matters of state concern by statutes applicable to such cities in connection with such powers to the extent to which such laws are appropriate and are not in conflict with the provisions specifically applicable to code cities.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.21.160[1967 ex.s. c 119 § 35A.21.160]; ]

== 35A.21.161 - Regulation of activities and enforcement of penal laws.
All code cities shall observe and enforce, in addition to its local regulations, the provisions of state laws relating to the conduct, location and limitation on activities as regulated by state law and shall supply police information to the *section on identification of the state patrol as required by chapter 43.43 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%2059[1983 c 3 § 59]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.21.161[1967 ex.s. c 119 § 35A.21.161]; ]

== 35A.21.162 - Nonpolluting power generation by individual—Exemption from regulation—Authorization to contract with utility.
See chapter 80.58 RCW.

[ ]

== 35A.21.164 - Hydroelectric resources—Separate legal authority—Creation by irrigation districts and cities, towns, or public utility districts.
See RCW 87.03.825 through 87.03.840.

[ ]

== 35A.21.170 - Fiscal year.
The fiscal year of a code city shall commence on the first day of January and end on the thirty-first day of December of each calendar year unless a different fiscal period is authorized by RCW 1.16.030, as amended.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.21.170[1967 ex.s. c 119 § 35A.21.170]; ]

== 35A.21.180 - Flags to be displayed.
The flag of the United States and the flag of the state shall be prominently installed and displayed and maintained in code city buildings and shall be as provided in RCW 1.20.010.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.21.180[1967 ex.s. c 119 § 35A.21.180]; ]

== 35A.21.190 - Daylight saving time. (Contingent expiration date.)
No code city shall adopt any provision for the observance of daylight saving time other than as authorized by RCW 1.20.050 and 1.20.051.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.21.190[1967 ex.s. c 119 § 35A.21.190]; ]

== 35A.21.195 - Actions by and against code cities.
A code city may exercise the power to bring an action or special proceeding at law as authorized by Title 4 RCW, chapters 7.24, 7.25, and 6.27 RCW, and shall be subject to actions and process of law in accordance with procedures prescribed by law and rules of court.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c442.pdf?cite=1987%20c%20442%20§%201117[1987 c 442 § 1117]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%2058[1983 c 3 § 58]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.20.150[1967 ex.s. c 119 § 35A.20.150]; ]

== 35A.21.200 - Limitation of actions.
The limitations prescribed in chapter 4.16 RCW shall apply to actions brought in the name or for the benefit of, or against, a code city, except as otherwise provided by general law or by this title.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.21.200[1967 ex.s. c 119 § 35A.21.200]; ]

== 35A.21.210 - Revision of corporate boundary within street, road, or highway right-of-way by substituting right-of-way line—Not subject to review.
. The governing bodies of a county and any code city located therein may by agreement revise any part of the corporate boundary of the city which coincides with the centerline, edge, or any portion of a public street, road or highway right-of-way by substituting therefor a right-of-way line of the same public street, road or highway so as fully to include or fully to exclude that segment of the public street, road or highway from the corporate limits of the city.

. The revision of a corporate boundary as authorized by this section shall become effective when approved by ordinance of the city council and by ordinance or resolution of the county legislative authority. Such a boundary revision is not subject to potential review by a boundary review board.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c84.pdf?cite=1989%20c%2084%20§%2011[1989 c 84 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c220.pdf?cite=1975%201st%20ex.s.%20c%20220%20§%2018[1975 1st ex.s. c 220 § 18]; ]

== 35A.21.220 - Insurance and workers' compensation for offenders performing community restitution.
The legislative authority of a code city may purchase liability insurance in an amount it deems reasonable to protect the code city, its officers, and employees against liability for the wrongful acts of offenders or injury or damage incurred by offenders in the course of court-ordered community restitution, and may elect to treat offenders as employees and/or workers under Title 51 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6627.SL.pdf?cite=2002%20c%20175%20§%2031[2002 c 175 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c24.pdf?cite=1984%20c%2024%20§%202[1984 c 24 § 2]; ]

== 35A.21.230 - Designation of official newspaper.
Each code city shall designate an official newspaper by resolution. The newspaper shall be of general circulation in the city and have the qualifications prescribed by chapter 65.16 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c469.pdf?cite=1985%20c%20469%20§%20102[1985 c 469 § 102]; ]

== 35A.21.240 - Right-of-way donations—Credit against required improvements.
Where the zoning and planning provisions of a city or town require landscaping, parking, or other improvements as a condition to granting permits for commercial or industrial developments, the city or town may credit donations of right-of-way in excess of that required for traffic improvement against such landscaping, parking, or other requirements.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c267.pdf?cite=1987%20c%20267%20§%208[1987 c 267 § 8]; ]

== 35A.21.245 - Facilities and rights-of-way—Requirements and restrictions—Application to code cities.
Each code city is subject to the requirements and restrictions regarding facilities and rights-of-way under *this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6676-S.SL.pdf?cite=2000%20c%2083%20§%2010[2000 c 83 § 10]; ]

== 35A.21.250 - Building construction projects—Code city prohibited from requiring state agencies or local governments to provide bond or other security as a condition for issuance of permit.
A code city may not require any state agency or unit of local government to secure the performance of a permit requirement with a surety bond or other financial security device, including cash or assigned account, as a condition of issuing a permit to that unit of local government for a building construction project.

As used in this section, "building construction project" includes, in addition to its usual meaning, associated landscaping, street alteration, pedestrian or vehicular access alteration, or other amenities or alterations necessarily associated with the project.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5858-S.SL.pdf?cite=1993%20c%20439%20§%202[1993 c 439 § 2]; ]

== 35A.21.260 - Amateur radio antennas—Local regulation to conform with federal law.
No code city shall enact or enforce an ordinance or regulation that fails to conform to the limited preemption entitled "Amateur Radio Preemption, 101 FCC 2nd 952 (1985)" issued by the federal communications commission. An ordinance or regulation adopted by a code city with respect to amateur radio antennas shall conform to the limited federal preemption, that states local regulations that involve placement, screening, or height of antennas based on health, safety, or aesthetic considerations must be crafted to reasonably accommodate amateur communications, and to represent the minimal practicable regulation to accomplish the local authority's legitimate purpose.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5697.SL.pdf?cite=1994%20c%2050%20§%202[1994 c 50 § 2]; ]

== 35A.21.270 - Assumption of substandard water system—Limited immunity from liability.
A code city assuming responsibility for a water system that is not in compliance with state or federal requirements for public drinking water systems, and its agents and employees, are immune from lawsuits or causes of action, based on noncompliance with state or federal requirements for public drinking water systems, which predate the date of assuming responsibility and continue after the date of assuming responsibility, provided that the city has submitted and is complying with a plan and schedule of improvements approved by the department of health. This immunity shall expire on the earlier of the date the plan of improvements is completed or four years from the date of assuming responsibility. This immunity does not apply to intentional injuries, fraud, or bad faith.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6428-S.SL.pdf?cite=1994%20c%20292%20§%206[1994 c 292 § 6]; ]

== 35A.21.275 - Regulation of automatic number or location identification—Prohibited.
No code city may enact or enforce an ordinance or regulation mandating automatic number identification or automatic location identification for a private telecommunications system or for a provider of private shared telecommunications services.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5089-S.SL.pdf?cite=1995%20c%20243%20§%207[1995 c 243 § 7]; ]

== 35A.21.280 - Statement of restrictions applicable to real property.
. A property owner may make a written request for a statement of restrictions applicable to a single parcel, tract, lot, or block of real property to the code city in which the real property is located.

. Within thirty days of the receipt of the request, the code city shall provide the owner, by registered mail, with a statement of restrictions as described in subsection (3) of this section.

. The statement of restrictions shall include the following:

.. The zoning currently applicable to the real property;

.. Pending zoning changes currently advertised for public hearing that would be applicable to the real property;

.. Any designations made by the code city pursuant to chapter 36.70A RCW of any portion of the real property as agricultural land, forestland, mineral resource land, wetland, an area with a critical recharging effect on aquifers used for potable water, a fish and wildlife habitat conservation area, a frequently flooded area, and as a geological hazardous area; and

.. If information regarding the designations listed in (c) of this subsection are not readily available, inform the owner of the procedure by which the owner can obtain that site-specific information from the code city.

. If a code city fails to provide the statement of restrictions within thirty days after receipt of the written request, the owner shall be awarded recovery of all attorneys' fees and costs incurred in any successful application for a writ of mandamus to compel production of a statement.

. For purposes of this section:

.. "Owner" means any vested owner or any person holding the buyer's interest under a recorded real estate contract in which the seller is the vested owner; and

.. "Real property" means a parcel, tract, lot or block: (i) Containing a single-family residence that is occupied by the owner or a member of his or her family, or rented to another by the owner; or (ii) five acres or less in size.

. This section does not affect the vesting of permits or development rights.

Nothing in this section shall be deemed to create any liability on the part of a code city.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/2386-S.SL.pdf?cite=1996%20c%20206%20§%207[1996 c 206 § 7]; ]

== 35A.21.290 - Fish enhancement project—Code city's liability.
A code city is not liable for adverse impacts resulting from a fish enhancement project that meets the criteria of RCW 77.55.181 and has been permitted by the department of fish and wildlife.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2251-S2.SL.pdf?cite=2014%20c%20120%20§%2011[2014 c 120 § 11]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5172.SL.pdf?cite=2003%20c%2039%20§%2016[2003 c 39 § 16]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2879-S2.SL.pdf?cite=1998%20c%20249%20§%2010[1998 c 249 § 10]; ]

== 35A.21.300 - Rail fixed guideway public transportation system—Safety program plan and security and emergency preparedness plan.
. Each code city that owns or operates a rail fixed guideway public transportation system as defined in RCW 81.104.015 shall submit a system safety program plan and a system security and emergency preparedness plan for that guideway to the state department of transportation by September 1, 1999, or at least one hundred eighty calendar days before beginning operations or instituting significant revisions to its plans. These plans must describe the code city's procedures for (a) reporting and investigating any reportable incident, accident, or security breach and identifying and resolving hazards or security vulnerabilities discovered during planning, design, construction, testing, or operations, (b) developing and submitting corrective action plans and annual safety and security audit reports, (c) facilitating on-site safety and security reviews by the state department of transportation and the federal transit administration, and (d) addressing passenger and employee safety and security. The plans must, at a minimum, conform to the standards adopted by the state department of transportation as set forth in the most current version of the Washington state rail safety oversight program standard manual as it exists on March 25, 2016, or such subsequent date as may be provided by the department by rule, consistent with the purposes of this section. If required by the department, the code city shall revise its plans to incorporate the department's review comments within sixty days after their receipt, and resubmit its revised plans for review.

. Each code city shall implement and comply with its system safety program plan and system security and emergency preparedness plan. The code city shall perform internal safety and security audits to evaluate its compliance with the plans, and submit its audit schedule to the department of transportation pursuant to the requirements in the most current version of the Washington state rail safety oversight program standard manual as it exists on March 25, 2016, or such subsequent date as may be provided by the department by rule, consistent with the purposes of this section. The code city shall prepare an annual report for its internal safety and security audits undertaken in the prior year and submit it to the department no later than February 15th. The department shall establish the requirements for the annual report. The contents of the annual report must include, at a minimum, the dates the audits were conducted, the scope of the audit activity, the audit findings and recommendations, the status of any corrective actions taken as a result of the audit activity, and the results of each audit in terms of the adequacy and effectiveness of the plans.

. Each code city shall notify the department of transportation, pursuant to the most current version of the Washington state rail safety oversight program standard manual as it exists on March 25, 2016, or such subsequent date as may be provided by the department by rule, consistent with the purposes of this section, any reportable incident, accident, security breach, hazard, or security vulnerability. The department may adopt rules further defining any reportable incident, accident, security breach, hazard, or security vulnerability. The code city shall investigate any reportable incident, accident, security breach, hazard, or security vulnerability and provide a written investigation report to the department as described in the most current version of the Washington state rail safety oversight program standard manual as it exists on March 25, 2016, or such subsequent date as may be provided by the department by rule, consistent with the purposes of this section.

. The system security and emergency preparedness plan required in subsection (1) of this section is exempt from public disclosure under chapter 42.56 RCW. However, the system safety program plan as described in this section is not subject to this exemption.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6358-S.SL.pdf?cite=2016%20c%2033%20§%203[2016 c 33 § 3]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5084.SL.pdf?cite=2007%20c%20422%20§%202[2007 c 422 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/1133-S.SL.pdf?cite=2005%20c%20274%20§%20267[2005 c 274 § 267]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1324-S.SL.pdf?cite=1999%20c%20202%20§%202[1999 c 202 § 2]; ]

== 35A.21.305 - Permanent supportive housing—Code city may not prohibit where multifamily housing is permitted.
A code city may not prohibit permanent supportive housing in areas where multifamily housing is permitted.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1923-S2.SL.pdf?cite=2019%20c%20348%20§%2010[2019 c 348 § 10]; ]

== 35A.21.310 - Mobile home, manufactured home, or park model moving or installing—Copies of permits—Definitions.
. A code city shall transmit a copy of any permit issued to a tenant or the tenant's agent for a mobile home, manufactured home, or park model installation in a mobile home park to the landlord.

. A code city shall transmit a copy of any permit issued to a person engaged in the business of moving or installing a mobile home, manufactured home, or park model in a mobile home park to the tenant and the landlord.

. As used in this section:

.. "Landlord" has the same meaning as in RCW 59.20.030;

.. "Mobile home park" has the same meaning as in RCW 59.20.030;

.. "Mobile or manufactured home installation" has the same meaning as in *RCW 43.63B.010; and

.. "Tenant" has the same meaning as in RCW 59.20.030.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1378.SL.pdf?cite=1999%20c%20359%20§%2019[1999 c 359 § 19]; ]

== 35A.21.312 - Authority to regulate placement or use of homes—Regulation of manufactured homes—Issuance of permits—Restrictions on location of manufactured/mobile homes and entry or removal of recreational vehicles used as primary residences.
. A code city may not adopt an ordinance that has the effect, directly or indirectly, of discriminating against consumers' choices in the placement or use of a home in such a manner that is not equally applicable to all homes. Homes built to 42 U.S.C. Sec. 5401-5403 standards (as amended in 2000) must be regulated for the purposes of siting in the same manner as site built homes, factory built homes, or homes built to any other state construction or local design standard. However, except as provided in subsection (2) of this section, any code city may require that:

.. A manufactured home be a new manufactured home;

.. The manufactured home be set upon a permanent foundation, as specified by the manufacturer, and that the space from the bottom of the home to the ground be enclosed by concrete or an approved concrete product which can be either load bearing or decorative;

.. The manufactured home comply with all local design standards applicable to all other homes within the neighborhood in which the manufactured home is to be located;

.. The home is thermally equivalent to the state energy code; and

.. The manufactured home otherwise meets all other requirements for a designated manufactured home as defined in RCW 35.63.160.

A code city with a population of one hundred thirty-five thousand or more may choose to designate its building official as the person responsible for issuing all permits, including department of labor and industries permits issued under chapter 43.22 RCW in accordance with an interlocal agreement under chapter 39.34 RCW, for alterations, remodeling, or expansion of manufactured housing located within the city limits under this section.

. [Empty]
.. A code city may not adopt an ordinance that has the effect, directly or indirectly, of restricting the location of manufactured/mobile homes in manufactured/mobile home communities that were legally in existence before June 12, 2008, based exclusively on the age or dimensions of the manufactured/mobile home.

.. A code city may not prohibit the siting of a manufactured/mobile home on an existing lot based solely on lack of compliance with existing separation and setback requirements that regulate the distance between homes.

.. A code city is not precluded by (a) or (b) of this subsection from restricting the location of a manufactured/mobile home in manufactured/mobile home communities for any other reason including, but not limited to, failure to comply with fire, safety, or other local ordinances or state laws related to manufactured/mobile homes.

. Except as provided under subsection (4) of this section, a code city may not adopt an ordinance that has the effect, directly or indirectly, of preventing the entry or requiring the removal of a recreational vehicle used as a primary residence in manufactured/mobile home communities.

. Subsection (3) of this section does not apply to any local ordinance or state law that:

.. Imposes fire, safety, or other regulations related to recreational vehicles;

.. Requires utility hookups in manufactured/mobile home communities to meet state or federal building code standards for manufactured/mobile home communities or recreational vehicle parks; or

.. Includes both of the following provisions:

... A recreational vehicle must contain at least one internal toilet and at least one internal shower; and

... If the requirement in (c)(i) of this subsection is not met, a manufactured/mobile home community must provide toilets and showers.

. For the purposes of this section, "manufactured/mobile home community" has the same meaning as in RCW 59.20.030.

. This section does not override any legally recorded covenants or deed restrictions of record.

. This section does not affect the authority granted under chapter 43.22 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5183-S.SL.pdf?cite=2019%20c%20390%20§%2015[2019 c 390 § 15]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1227.SL.pdf?cite=2009%20c%2079%20§%202[2009 c 79 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5524-S.SL.pdf?cite=2008%20c%20117%20§%202[2008 c 117 § 2]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/6593.SL.pdf?cite=2004%20c%20256%20§%203[2004 c 256 § 3]; ]

== 35A.21.314 - Code city may not limit number of unrelated persons occupying a household or dwelling unit—Exceptions.
Except for occupant limits on group living arrangements regulated under state law or on short-term rentals as defined in RCW 64.37.010 and any lawful limits on occupant load per square foot or generally applicable health and safety provisions as established by applicable building code or city ordinance, a code city may not regulate or limit the number of unrelated persons that may occupy a household or dwelling unit.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/Senate/5235-S.SL.pdf?cite=2021%20c%20306%20§%206[2021 c 306 § 6]; ]

== 35A.21.320 - Abandoned or derelict vessels.
A code city has the authority, subject to the processes and limitation outlined in chapter 79.100 RCW, to store, strip, use, auction, sell, salvage, scrap, or dispose of an abandoned or derelict vessel found on or above publicly or privately owned aquatic lands within the jurisdiction of the code city.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2376-S.SL.pdf?cite=2002%20c%20286%20§%2016[2002 c 286 § 16]; ]

== 35A.21.322 - Transfer of ownership of a code city-owned vessel—Review of vessel's physical condition.
. Prior to transferring ownership of a code city-owned vessel, the code city shall conduct a thorough review of the physical condition of the vessel, the vessel's operating capability, and any containers and other materials that are not fixed to the vessel.

. If the code city determines that the vessel is in a state of advanced deterioration or poses a reasonably imminent threat to human health or safety, including a threat of environmental contamination, the code city may: (a) Not transfer the vessel until the conditions identified under this subsection have been corrected; or (b) permanently dispose of the vessel by landfill, deconstruction, or other related method.

. Vessels taken into custody under chapter 79.100 RCW are not subject to this section or RCW 35A.21.324.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1245-S.SL.pdf?cite=2013%20c%20291%20§%2017[2013 c 291 § 17]; ]

== 35A.21.324 - Transfer of ownership of a code city-owned vessel—Further requirements.
. Following the inspection required under RCW 35A.21.322 and prior to transferring ownership of a code city-owned vessel, a code city shall obtain the following from the transferee:

.. The purposes for which the transferee intends to use the vessel; and

.. Information demonstrating the prospective owner's intent to obtain legal moorage following the transfer, in the manner determined by the code city.

. [Empty]
.. The code city shall remove any containers or other materials that are not fixed to the vessel and contain hazardous substances, as defined under RCW 70A.305.020.

.. However, the code city may transfer a vessel with:

... Those containers or materials described under (a) of this subsection where the transferee demonstrates to the code city's satisfaction that the container's or material's presence is consistent with the anticipated use of the vessel; and

... A reasonable amount of fuel as determined by the code city, based on factors including the vessel's size, condition, and anticipated use of the vessel, including initial destination following transfer.

.. The code city may consult with the department of ecology in carrying out the requirements of this subsection.

. Prior to sale, and unless the vessel has a title or valid marine document, the code city is required to apply for a certificate of title for the vessel under RCW 88.02.510 and register the vessel under RCW 88.02.550.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2246-S.SL.pdf?cite=2020%20c%2020%20§%201018[2020 c 20 § 1018]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1245-S.SL.pdf?cite=2013%20c%20291%20§%2018[2013 c 291 § 18]; ]

== 35A.21.330 - Regulation of financial transactions—Limitations.
A code city or governmental entity subject to this title may not regulate the terms, conditions, or disclosures of any lawful financial transaction between a consumer and (1) a business or professional under the jurisdiction of the department of financial institutions, or (2) any financial institution as defined under *RCW 30.22.041.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5266-S.SL.pdf?cite=2005%20c%20338%20§%203[2005 c 338 § 3]; ]

== 35A.21.335 - Registration under or compliance with streamlined sales and use tax agreement—Prohibited requirement for businesses.
A code city may not require a business to be licensed based solely upon registration under or compliance with the streamlined sales and use tax agreement.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/3126-S.SL.pdf?cite=2008%20c%20129%20§%205[2008 c 129 § 5]; ]

== 35A.21.340 - Contractors—Authority of city to verify registration and report violations.
A city that issues a business license to a person required to be registered under chapter 18.27 RCW may verify that the person is registered under chapter 18.27 RCW and report violations to the department of labor and industries. The department of revenue must conduct the verification for cities that participate in the business licensing system.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1568-S.SL.pdf?cite=2013%20c%20144%20§%2037[2013 c 144 § 37]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2017-S.SL.pdf?cite=2011%20c%20298%20§%2023[2011 c 298 § 23]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1555-S.SL.pdf?cite=2009%20c%20432%20§%203[2009 c 432 § 3]; ]

== 35A.21.350 - Community athletics programs—Sex discrimination prohibited.
The antidiscrimination provisions of RCW 49.60.500 apply to community athletics programs and facilities operated, conducted, or administered by a code city.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5967-S.SL.pdf?cite=2009%20c%20467%20§%206[2009 c 467 § 6]; ]

== 35A.21.360 - Hosting the homeless by religious organizations—When authorized—Requirements—Prohibitions on local actions.
. A religious organization may host the homeless on property owned or controlled by the religious organization whether within buildings located on the property or elsewhere on the property outside of buildings.

. Except as provided in subsection (7) of this section, a code city may not enact an ordinance or regulation or take any other action that:

.. Imposes conditions other than those necessary to protect public health and safety and that do not substantially burden the decisions or actions of a religious organization regarding the location of housing or shelter, such as an outdoor encampment, indoor overnight shelter, temporary small house on-site, or vehicle resident safe parking, for homeless persons on property owned or controlled by the religious organization;

.. Requires a religious organization to obtain insurance pertaining to the liability of a municipality with respect to homeless persons housed on property owned by a religious organization or otherwise requires the religious organization to indemnify the municipality against such liability;

.. Imposes permit fees in excess of the actual costs associated with the review and approval of permit applications. A code city has discretion to reduce or waive permit fees for a religious organization that is hosting the homeless;

.. Specifically limits a religious organization's availability to host an outdoor encampment on its property or property controlled by the religious organization to fewer than six months during any calendar year. However, a code city may enact an ordinance or regulation that requires a separation of time of no more than three months between subsequent or established outdoor encampments at a particular site;

.. Specifically limits a religious organization's outdoor encampment hosting term to fewer than four consecutive months;

.. Limits the number of simultaneous religious organization outdoor encampment hostings within the same municipality during any given period of time. Simultaneous and adjacent hostings of outdoor encampments by religious organizations may be limited if located within one thousand feet of another outdoor encampment concurrently hosted by a religious organization;

.. Limits a religious organization's availability to host safe parking efforts at its on-site parking lot, including limitations on any other congregationally sponsored uses and the parking available to support such uses during the hosting, except for limitations that are in accord with the following criteria that would govern if enacted by local ordinance or memorandum of understanding between the host religious organization and the jurisdiction:

... No less than one space may be devoted to safe parking per ten on-site parking spaces;

... Restroom access must be provided either within the buildings on the property or through use of portable facilities, with the provision for proper disposal of waste if recreational vehicles are hosted; and

... Religious organizations providing spaces for safe parking must continue to abide by any existing on-site parking minimum requirement so that the provision of safe parking spaces does not reduce the total number of available parking spaces below the minimum number of spaces required by the code city, but a code city may enter into a memorandum of understanding with a religious organization that reduces the minimum number of on-site parking spaces required;

.. Limits a religious organization's availability to host an indoor overnight shelter in spaces with at least two accessible exits due to lack of sprinklers or other fire-related concerns, except that:

.. If a code city fire official finds that fire-related concerns associated with an indoor overnight shelter pose an imminent danger to persons within the shelter, the code city may take action to limit the religious organization's availability to host the indoor overnight shelter; and

... A code city may require a host religious organization to enter into a memorandum of understanding for fire safety that includes local fire district inspections, an outline for appropriate emergency procedures, a determination of the most viable means to evacuate occupants from inside the host site with appropriate illuminated exit signage, panic bar exit doors, and a completed fire watch agreement indicating:

(A) Posted safe means of egress;

(B) Operable smoke detectors, carbon monoxide detectors as necessary, and fire extinguishers;

(C) A plan for monitors who spend the night awake and are familiar with emergency protocols, who have suitable communication devices, and who know how to contact the local fire department; or

... Limits a religious organization's ability to host temporary small houses on land owned or controlled by the religious organization, except for recommendations that are in accord with the following criteria:

... A renewable one-year duration agreed to by the host religious organization and local jurisdiction via a memorandum of understanding;

... Maintaining a maximum unit square footage of one hundred twenty square feet, with units set at least six feet apart;

... Electricity and heat, if provided, must be inspected by the local jurisdiction;

... Space heaters, if provided, must be approved by the local fire authority;

.. Doors and windows must be included and be lockable, with a recommendation that the managing agency and host religious organization also possess keys;

.. Each unit must have a fire extinguisher;

.. Adequate restrooms must be provided, including restrooms solely for families if present, along with handwashing and potable running water to be available if not provided within the individual units, including accommodating black water;

.. A recommendation for the host religious organization to partner with regional homeless service providers to develop pathways to permanent housing.

. [Empty]
.. A code city may enact an ordinance or regulation or take any other action that requires a host religious organization and a distinct managing agency using the religious organization's property, owned or controlled by the religious organization, for hostings to include outdoor encampments, temporary small houses on-site, indoor overnight shelters, or vehicle resident safe parking to enter into a memorandum of understanding to protect the public health and safety of both the residents of the particular hosting and the residents of the code city.

.. At a minimum, the agreement must include information regarding: The right of a resident in an outdoor encampment, vehicle resident safe parking, temporary small house on-site, or indoor overnight shelter to seek public health and safety assistance, the resident's ability to access social services on-site, and the resident's ability to directly interact with the host religious organization, including the ability to express any concerns regarding the managing agency to the religious organization; a written code of conduct agreed to by the managing agency, if any, host religious organization, and all volunteers working with residents of the outdoor encampment, temporary small house on-site, indoor overnight shelter, or vehicle resident safe parking; and when a publicly funded managing agency exists, the ability for the host religious organization to interact with residents of the outdoor encampment, indoor overnight shelter, temporary small house on-site, or vehicle resident safe parking using a release of information.

. If required to do so by a code city, any host religious organization performing any hosting of an outdoor encampment, vehicle resident safe parking, or indoor overnight shelter, or the host religious organization's managing agency, must ensure that the code city or local law enforcement agency has completed sex offender checks of all adult residents and guests. The host religious organization retains the authority to allow such offenders to remain on the property. A host religious organization or host religious organization's managing agency performing any hosting of vehicle resident safe parking must inform vehicle residents how to comply with laws regarding the legal status of vehicles and drivers, and provide a written code of conduct consistent with area standards.

. Any host religious organization performing any hosting of an outdoor encampment, vehicle resident safe parking, temporary small house on-site, or indoor overnight shelter, with a publicly funded managing agency, must work with the code city to utilize Washington's homeless client management information system, as provided for in RCW 43.185C.180. When the religious organization does not partner with a managing agency, the religious organization is encouraged to partner with a local homeless services provider using the Washington homeless client managing information system. Any managing agency receiving any funding from local continuum of care programs must utilize the homeless client management information system. Temporary, overnight, extreme weather shelter provided in religious organization buildings does not need to meet this requirement.

. For the purposes of this section:

.. "Managing agency" means an organization such as a religious organization or other organized entity that has the capacity to organize and manage a homeless outdoor encampment, temporary small houses on-site, indoor overnight shelter, and a vehicle resident safe parking program.

.. "Outdoor encampment" means any temporary tent or structure encampment, or both.

.. "Religious organization" means the federally protected practice of a recognized religious assembly, school, or institution that owns or controls real property.

.. "Temporary" means not affixed to land permanently and not using underground utilities.

. [Empty]
.. Subsection (2) of this section does not affect a code city policy, ordinance, memorandum of understanding, or applicable consent decree that regulates religious organizations' hosting of the homeless if such policies, ordinances, memoranda of understanding, or consent decrees:

... Exist prior to June 11, 2020;

... Do not categorically prohibit the hosting of the homeless by religious organizations; and

... Have not been previously ruled by a court to violate the religious land use and institutionalized persons act, 42 U.S.C. Sec. 2000cc.

.. If such policies, ordinances, memoranda of understanding, and consent decrees are amended after June 11, 2020, those amendments are not affected by subsection (2) of this section if those amendments satisfy (a)(ii) and (iii) of this subsection.

. An appointed or elected public official, public employee, or public agency as defined in RCW 4.24.470 is immune from civil liability for (a) damages arising from the permitting decisions for a temporary encampment for the homeless as provided in this section and (b) any conduct or unlawful activity that may occur as a result of the temporary encampment for the homeless as provided in this section.

. A religious organization hosting outdoor encampments, vehicle resident safe parking, or indoor overnight shelters for the homeless that receives funds from any government agency may not refuse to host any resident or prospective resident because of age, sex, marital status, sexual orientation, race, creed, color, national origin, honorably discharged veteran or military status, or the presence of any sensory, mental, or physical disability or the use of a trained dog guide or service animal by a person with a disability, as these terms are defined in RCW 49.60.040.

. [Empty]
.. Prior to the opening of an outdoor encampment, indoor overnight shelter, temporary small house on-site, or vehicle resident safe parking, a religious organization hosting the homeless on property owned or controlled by the religious organization must host a meeting open to the public for the purpose of providing a forum for discussion of related neighborhood concerns, unless the use is in response to a declared emergency. The religious organization must provide written notice of the meeting to the code city legislative authority at least one week if possible but no later than ninety-six hours prior to the meeting. The notice must specify the time, place, and purpose of the meeting.

.. A code city must provide community notice of the meeting described in (a) of this subsection by taking at least two of the following actions at any time prior to the time of the meeting:

... Delivering to each local newspaper of general circulation and local radio or television station that has on file with the governing body a written request to be notified of special meetings;

... Posting on the code city's website. A code city is not required to post a special meeting notice on its website if it: (A) Does not have a website; (B) employs fewer than ten full-time equivalent employees; or (C) does not employ personnel whose duty, as defined by a job description or existing contract, is to maintain or update the website;

... Prominently displaying, on signage at least two feet in height and two feet in width, one or more meeting notices that can be placed on or adjacent to the main arterials in proximity to the location of the meeting; or

... Prominently displaying the notice at the meeting site.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1754-S.SL.pdf?cite=2020%20c%20223%20§%204[2020 c 223 § 4]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1956-S.SL.pdf?cite=2010%20c%20175%20§%204[2010 c 175 § 4]; ]

== 35A.21.370 - State and federal background checks of license applicants and licensees of occupations under local licensing authority.
. For the purpose of receiving criminal history record information by code city officials, code cities may:

.. By ordinance, require a state and federal background investigation of license applicants or licensees in occupations specified by ordinance;

.. By ordinance, require a federal background investigation of code city employees, applicants for employment, volunteers, vendors, and independent contractors, who, in the course of their work or volunteer activity with the code city, may have unsupervised access to children, persons with developmental disabilities, or vulnerable adults;

.. Require a state criminal background investigation of code city employees, applicants for employment, volunteers, vendors, and independent contractors, who, in the course of their work or volunteer activity with the code city, may have unsupervised access to children, persons with developmental disabilities, or vulnerable adults; and

.. Require a criminal background investigation conducted through a private organization of code city employees, applicants for employment, volunteers, vendors, and independent contractors, who, in the course of their work or volunteer activity with the code city, may have unsupervised access to children, persons with developmental disabilities, or vulnerable adults.

. The investigation conducted under subsection (1)(a) through (c) of this section shall consist of a background check as allowed through the Washington state criminal records privacy act under RCW 10.97.050, the Washington state patrol criminal identification system under RCW 43.43.832 through 43.43.834, and the federal bureau of investigation.

. The background checks conducted under subsection (1)(a) through (c) of this section must be done through the Washington state patrol identification and criminal history section and may include a national check from the federal bureau of investigation, which shall be through the submission of fingerprints. The Washington state patrol shall serve as the sole source for receipt of fingerprint submissions and the responses to the submissions from the federal bureau of investigation, which must be disseminated to the code city.

. For a criminal background check conducted under subsection (1)(a) through (c) of this section, the code city shall transmit appropriate fees for a state and national criminal history check to the Washington state patrol, unless alternately arranged. The cost of investigations conducted under this section shall be borne by the code city.

. The authority for background checks outlined in this section is in addition to any other authority for such checks provided by law.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1620.SL.pdf?cite=2017%20c%20332%20§%202[2017 c 332 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6288.SL.pdf?cite=2010%20c%2047%20§%203[2010 c 47 § 3]; ]

== 35A.21.380 - Warrant officers—Training requirements—Authority.
. Any code city may establish the position of warrant officer.

. If any code city establishes the position of warrant officer, the position shall be maintained by the city within the city police department. The number and qualifications of warrant officers shall be fixed by ordinance, and their compensation shall be paid by the city. The chief of police of the city must establish training requirements consistent with the job description of warrant officer established in that city. Training requirements must be approved by the criminal justice training commission.

. Warrant officers shall be vested only with the special authority identified in ordinance, which may include the authority to make arrests authorized by warrants and other authority related to service of civil and criminal process.

. Process issuing from any court that is directed to a police department in which a warrant officer position is maintained may be served or enforced by the warrant officer, if within the warrant officer's authority as identified in ordinance.

. Warrant officers shall not be entitled to death, disability, or retirement benefits pursuant to chapter 41.26 RCW on the basis of service as a warrant officer as described in this section.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5004-S.SL.pdf?cite=2015%20c%20288%20§%202[2015 c 288 § 2]; ]

== 35A.21.390 - Failing septic systems—Connection to public sewer systems—Appeals process.
. A city with an ordinance or resolution requiring, upon the failure of an on-site septic system, connection to a public sewer system must, in accordance with this section, provide an administrative appeals process to consider denials of permit applications to repair or replace the septic system. The administrative appeals process required by this section applies only to requests to repair or replace existing, failing on-site septic systems that:

.. Were made for a single-family residence by its owner or owners;

.. Were denied solely because of a law, regulation, or ordinance requiring connection to a public sewer system; and

.. Absent the applicable law, regulation, or ordinance requiring connection to a public sewer system upon which the denial was based, would be approved. 

. If the city has an administrative appeals process, the city may, subject to the requirements of this section, use that process. The administrative appeals process required by this section, however, must be presided over by the legislative body of the city or by an administrative hearings officer.

. The administrative appeals process required by this section must, at a minimum, consider whether:

.. It is cost-prohibitive to require the property owner to connect to the public sewer system. In complying with this subsection (3)(a), the city must consider the estimated cost to repair or replace the on-site septic system compared to the estimated cost to connect to the public sewer system;

.. There are public health or environmental considerations related to allowing the property owner to repair or replace the on-site septic system. In complying with this subsection (3)(b), the city must consider whether the repaired or replaced on-site septic system contributes to the pollution of surface waters or groundwater;

.. There are public sewer system performance or financing considerations related to allowing the property owner to repair or replace the on-site septic system; and

.. There are financial assistance programs or latecomer agreements offered by the city or state that may impact a decision of the property owner to repair or replace the on-site septic system.

. If the city, following the appeals process required by this section, determines that the property owner must connect the residence to the public sewer system, the property owner may, in complying with the determination and subject to approval of appropriate permits, select and hire contractors at his or her own expense to perform the work necessary to connect the residence to the public sewer system.

. Unless otherwise required by law, a city determination requiring the owner of a single-family residence with a failing on-site septic system to connect a residence to a public sewer system is not subject to appeal.

. For purposes of this section, "city" means a "code city" as defined in RCW 35A.01.035.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5871.SL.pdf?cite=2015%20c%20297%20§%202[2015 c 297 § 2]; ]

== 35A.21.400 - Final determination on state highway project permits.
A code city must comply with the requirements of RCW 47.01.485 in making a final determination on a permit as part of a project on a state highway as defined in RCW 46.04.560.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/5994-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%2015%20§%204[2015 3rd sp.s. c 15 § 4]; ]

== 35A.21.405 - Nuisance abatement—Special assessment—Notice requirements.
. A code city that exercises its authority under chapter   7.48 RCW, RCW 35.22.280, 35.23.440, or 35.27.410, or other applicable law to abate a nuisance which threatens health or safety must provide prior notice to the property owner that abatement is pending and a special assessment may be levied on the property for the expense of abatement. Such special assessment authority is supplemental to any existing authority of a code city to levy an assessment or obtain a lien for costs of abatement. The notice must be sent by regular mail.

. A code city that exercises its authority under chapter 7.48 RCW, RCW 35.22.280, 35.23.440, or 35.27.410, or other applicable law to declare a nuisance, abate a nuisance, or impose fines or costs upon persons who create, continue, or maintain a nuisance may levy a special assessment on the land or premises where the nuisance is situated to reimburse the code city for the expense of abatement. A code city must, before levying a special assessment, notify the property owner and any identifiable mortgage holder that a special assessment will be levied on the property and provide the estimated amount of the special assessment. The notice must be sent by regular mail.

. The special assessment authorized by this section constitutes a lien against the property, and is binding upon successors in title only from the date the lien is recorded in the county where the affected real property is located. Up to two thousand dollars of the recorded lien is of equal rank with state, county, and municipal taxes.

. A code city levying a special assessment under this section may contract with the county treasurer to collect the special assessment in accordance with RCW 84.56.035.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2519-S.SL.pdf?cite=2016%20c%20100%20§%202[2016 c 100 § 2]; ]

== 35A.21.410 - Removal of restrictive covenants—Hearing, notice.
Any code city must hold a public hearing upon a proposal to remove, vacate, or extinguish a restrictive covenant from property owned by the code city before the action is finalized. The public hearing must allow individuals to provide testimony regarding the proposed action. The code city must provide notice of the public hearing at least ten days before the hearing at its usual place of business and issue a press release to local media providing the date, time, location, and reason for the public hearing. The notice must be posted on the code city's website if it is updated for any reason prior to the hearing date. The notice must also identify the property and provide a brief explanation of the restrictive covenant to be removed, vacated, or extinguished. Any member of the public, in person or by counsel, may submit testimony regarding the proposed action at the public hearing.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1959.SL.pdf?cite=2017%20c%20119%20§%204[2017 c 119 § 4]; ]

== 35A.21.415 - Voluntary change to electoral system.
The legislative authority of a code city or town may authorize a change to its electoral system pursuant to RCW 29A.92.040.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/6002-S.SL.pdf?cite=2018%20c%20113%20§%20207[2018 c 113 § 207]; ]

== 35A.21.420 - Urban agriculture zone.
. A code city may, by ordinance, establish an urban agriculture zone within the boundaries of the code city.

. To establish an urban agriculture zone, the code city must conduct at least one public hearing on the question of whether to establish the urban agriculture zone.

. An ordinance adopted pursuant to this section must not prohibit the use of structures that support agricultural activity including, without limitation, apiaries, toolsheds, greenhouses, produce stands, and instructional spaces.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5552-S.SL.pdf?cite=2019%20c%20353%20§%2016[2019 c 353 § 16]; ]

== 35A.21.425 - Community gardens.
A code city may authorize, by ordinance, the use of vacant or blighted city land for the purpose of community gardening under the terms and conditions established for the use of the city land set forth by the ordinance. The ordinance may establish fees for the use of the city land, provide requirements for liability insurance, and provide requirements for a deposit to use the city land, which may be refunded. The ordinance must require that a portion of the community garden include habitat beneficial for the feeding, nesting, and reproduction of all pollinators, including honey bees.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5552-S.SL.pdf?cite=2019%20c%20353%20§%2017[2019 c 353 § 17]; ]

== 35A.21.430 - Transitional housing, permanent supportive housing, indoor emergency housing, and indoor emergency shelters.
A code city shall not prohibit transitional housing or permanent supportive housing in any zones in which residential dwelling units or hotels are allowed. Effective September 30, 2021, a code city shall not prohibit indoor emergency shelters and indoor emergency housing in any zones in which hotels are allowed, except in such cities that have adopted an ordinance authorizing indoor emergency shelters and indoor emergency housing in a majority of zones within a one-mile proximity to transit. Reasonable occupancy, spacing, and intensity of use requirements may be imposed by ordinance on permanent supportive housing, transitional housing, indoor emergency housing, and indoor emergency shelters to protect public health and safety. Any such requirements on occupancy, spacing, and intensity of use may not prevent the siting of a sufficient number of permanent supportive housing, transitional housing, indoor emergency housing, or indoor emergency shelters necessary to accommodate each code city's projected need for such housing and shelter under RCW 36.70A.070(2)(a)(ii).

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1220-S2.SL.pdf?cite=2021%20c%20254%20§%203[2021 c 254 § 3]; ]

