= 35A.58 - Boundaries and plats.
:toc:

== 35A.58.010 - Locating corners and boundaries.
General laws shall govern the methods, procedures, and standards for surveying, establishing corners and boundaries, describing and perpetuating and recording information and descriptions relating thereto. The boundaries and corners of sections, parcels, plats, and subdivisions of land within a code city, may be surveyed, established, relocated, and perpetuated whenever a majority of the resident owners of any section or part or parts of any section of land within the city makes application in accordance with the provisions of chapter 58.04 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.58.010[1967 ex.s. c 119 § 35A.58.010]; ]

== 35A.58.020 - Alteration and vacation of plats.
The provisions of *chapters 58.11 and 58.12 RCW shall apply in appropriate cases to the alteration or vacation of plats including land or lots within a code city or the vacation of streets therein as provided in chapter 35.79 RCW. The vacation of waterways within a code city shall be governed by the provisions of **chapter 79.16 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.58.020[1967 ex.s. c 119 § 35A.58.020]; ]

== 35A.58.030 - Platting and subdivision of land.
The provisions of chapter 58.17 RCW together with the provisions of a code city's subdivision regulations as adopted by ordinance not inconsistent with the provisions of chapter 58.17 RCW shall control the platting and subdividing of land into lots or tracts comprising five or more of such lots or tracts or containing a dedication of any part thereof as a public street or highway, or other public place or use: PROVIDED, That nothing herein shall prohibit the legislative body of a code city from adopting reasonable ordinances regulating the subdivision of land into two or more parcels without requiring compliance with all of the requirements of the platting law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%2070[1983 c 3 § 70]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c251.pdf?cite=1971%20ex.s.%20c%20251%20§%209[1971 ex.s. c 251 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.58.030[1967 ex.s. c 119 § 35A.58.030]; ]

