= 35A.31 - Accident claims and funds.
:toc:

== 35A.31.010 - Claims—Statement of residence required—Time for filing—Verification.
Claims for damages sounding in tort against any code city shall be presented and filed within the time, in the manner and by the person prescribed in RCW 4.96.020.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.31.010[1967 ex.s. c 119 § 35A.31.010]; ]

== 35A.31.020 - Liberal construction.
With respect to the content of such claims the provisions of RCW 4.96.020 shall be liberally construed so that substantial compliance will be deemed satisfactory.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.31.020[1967 ex.s. c 119 § 35A.31.020]; ]

== 35A.31.030 - Report—Manner of filing.
No ordinance or resolution shall be passed allowing such claim or any part thereof, or appropriating any money or other property to pay or satisfy the same or any part thereof, until the claim has first been referred to the proper department or committee, nor until such department or committee has made its report thereon to the legislative body of the code city pursuant to such reference.

No action shall be maintained against any code city for any claim for damages until the claim has been filed in the manner set forth in chapter 4.96 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1218.SL.pdf?cite=1993%20c%20449%20§%209[1993 c 449 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.31.030[1967 ex.s. c 119 § 35A.31.030]; ]

== 35A.31.050 - Charter code cities—Provisions cumulative.
Nothing herein shall be construed as in anywise modifying, limiting, or repealing any valid provision of the charter of any charter code city relating to such claims for damages, except when in conflict herewith, but the provisions hereof shall be in addition to such charter provisions, and such claims for damages, in all other respects, shall conform to and comply with such charter provisions.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.31.050[1967 ex.s. c 119 § 35A.31.050]; ]

== 35A.31.060 - Accident fund—Warrants for judgments.
Every code city may create an accident fund upon which the clerk shall draw warrants for the full amount of any judgment including interest and costs against the city on account of personal injuries suffered by any person as shown by a transcript of the judgment duly certified to the clerk. Warrants issued for such purpose shall be in denominations not less than one hundred dollars nor more than five hundred dollars; they shall draw interest at the rate of six percent per annum, shall be numbered consecutively and be paid in the order of their issue.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.31.060[1967 ex.s. c 119 § 35A.31.060]; ]

== 35A.31.070 - Tax levy for fund.
The legislative body of the code city, after the drawing of warrants against the accident fund, shall estimate the amount necessary to pay the warrant with accrued interest thereon and may appropriate and transfer money from the contingency fund sufficient therefor, or if there is not sufficient money in the contingency fund the legislative body shall levy a tax sufficient to pay all or such unpaid portion of any judgment not exceeding seventy-five cents per thousand dollars of assessed value. If a single levy of seventy-five cents per thousand dollars of assessed value is not sufficient, and if other moneys are not available therefor, an annual levy of seventy-five cents per thousand dollars of assessed value shall be made until the warrants and interest are fully paid.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c195.pdf?cite=1973%201st%20ex.s.%20c%20195%20§%2027[1973 1st ex.s. c 195 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.31.070[1967 ex.s. c 119 § 35A.31.070]; ]

== 35A.31.080 - Surplus to general fund.
If there is no judgment outstanding against the city for personal injuries, the money remaining in the accident fund after the payment of the warrants drawn on that fund and interest in full shall be transferred to the general fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.31.080[1967 ex.s. c 119 § 35A.31.080]; ]

