= 35A.88 - Harbors and navigation.
:toc:

== 35A.88.010 - Discharge of ballast.
A code city may exercise the powers relating to regulation of discharge of ballast in harbors within or in front of such city as authorized by RCW 88.28.060.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.88.010[1967 ex.s. c 119 § 35A.88.010]; ]

== 35A.88.020 - Wharves and landings.
A code city shall have and exercise all powers granted by general laws to cities and towns of any class relative to docks and other appurtenances to harbor and shipping, including but not limited to, the provisions of RCW 35.22.280, 35.23.440, * 35.24.290, and 88.24.030.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.88.020[1967 ex.s. c 119 § 35A.88.020]; ]

== 35A.88.030 - General laws applicable.
General laws relating to harbor areas within cities, including but not limited to, chapter 36.08 RCW relating to transfer of territory lying in two or more counties; *RCW 79.92.110 relating to disposition of rental from leasehold in the harbor areas; and RCW 88.32.240 and 88.32.250 relating to joint planning by cities and counties shall apply to, benefit and obligate code cities to the same extent as such general laws apply to any class of city.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%20103[1985 c 7 § 103]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%2075[1983 c 3 § 75]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.88.030[1967 ex.s. c 119 § 35A.88.030]; ]

