= 35A.43 - Local improvements in code cities.
:toc:

== 35A.43.010 - General law applicable to code cities.
Chapters 35.43, 35.44, 35.45, 35.47, 35.48, 35.49, 35.50, 35.53, 35.54, 35.55, and 35.56 RCW all relating to municipal local improvements and made applicable to all incorporated cities and towns by RCW 35.43.030 are hereby recognized as applicable to all code cities, and the provisions thereof shall supersede the provisions of any charter of a charter code city inconsistent therewith. The provisions of the chapters named in this section shall be effective as to charter code cities to the same extent as such provisions are effective as to cities of the first class, and all code cities may exercise, in the manner provided, any authority therein granted to any class of city.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20ยง%2035A.43.010[1967 ex.s. c 119 ยง 35A.43.010]; ]

== 35A.43.020 - Public lands subject to local assessments.
In addition to the authority provided by chapter 35.44 RCW, and chapter 79.44 RCW, a code city may assess public lands for the cost of local improvements specially benefiting such lands.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20ยง%2035A.43.020[1967 ex.s. c 119 ยง 35A.43.020]; ]

