= 35A.90 - Construction.
:toc:

== 35A.90.010 - Becoming code city—Rights, actions saved—Continuation of ordinances.
Unless otherwise provided by this title, the election by a city or town to become a code city and to be governed by this title shall not affect any right or liability either in favor of or against such city or town existing at the time, nor any civil or criminal proceeding involving or relating to such city or town; and all rights and property of every description which were vested in such city or town immediately prior to becoming a code city shall continue to be vested in such code city; and all charter provisions, ordinances, resolutions, rules, regulations, or orders lawfully in force in such city or town at the time of becoming a code city, and not inconsistent with or repugnant to this title, shall continue in force in such code city until amended or repealed as provided by law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.90.010[1967 ex.s. c 119 § 35A.90.010]; ]

== 35A.90.020 - Invalidity of part of title not to affect remainder.
If any provision, section, or chapter of this title or its application to any person or circumstance is held invalid, the remainder of the provision, section, chapter, or title, or the application thereof to other persons or circumstances is not affected.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.90.020[1967 ex.s. c 119 § 35A.90.020]; ]

