= 35A.37 - Funds, special purpose.
:toc:

== 35A.37.010 - Segregating and accounting.
Code cities shall establish such funds for the segregation, budgeting, expenditure, and accounting for moneys received for special purposes as are required by general law applicable to such cities' activities and the officers thereof shall pay into, expend from, and account for such moneys in the manner provided therefor including, but not limited to, the requirements of the following:

. Accounting funds as required by RCW 35.37.010;

. Annexation and consolidation fund as required by chapters 35.10 and 35.13 RCW;

. Assessment fund as required by RCW 8.12.480;

. Equipment rental fund as authorized by RCW 35.21.088;

. Current expense fund as required by RCW 35.37.010, usually referred to as the general fund;

. Local improvement guaranty fund as required by RCW 35.54.010;

. An indebtedness and sinking fund, together with separate funds for utilities and institutions as required by RCW 35.37.020;

. Local improvement district fund and revolving fund as required by RCW 35.45.130 and 35.48.010;

. City street fund as required by chapter 35.76 RCW and RCW 47.24.040;

. Firefighters' relief and pension fund as required by chapters 41.16 and 41.18 RCW;

. Police relief and pension fund as required by RCW 41.20.130 and 63.32.030;

. First-class cities' employees retirement and pension system as authorized by chapter 41.28 RCW;

. Applicable rules of the state auditor.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5077-S.SL.pdf?cite=2013%20c%2023%20§%2064[2013 c 23 § 64]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1889.SL.pdf?cite=1995%20c%20301%20§%2060[1995 c 301 § 60]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%2062[1983 c 3 § 62]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.37.010[1967 ex.s. c 119 § 35A.37.010]; ]

