= 35A.41 - Public employment.
:toc:

== 35A.41.010 - Retirement and pension systems for code cities having a population of more than twenty thousand.
A code city having a population of more than twenty thousand inhabitants, or having been classed theretofore as a city of the first class may exercise all of the powers relating to retirement and pension systems for employees as authorized by RCW 35A.11.020 and by chapter 41.28 RCW in accordance with the procedures prescribed therein and subject to the limitations and penalties thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.41.010[1967 ex.s. c 119 § 35A.41.010]; ]

== 35A.41.020 - Public employment and civil service.
Except as otherwise provided in this title, the general provisions relating to public employment, including hospitalization and medical aid as provided in chapter 41.04 RCW, and the application of federal social security for public employees, the acceptance of old age and survivors insurance as provided in chapters 41.47 and 41.48 RCW, military leave as provided in RCW 38.40.060, self-insurance as provided in chapter 48.62 RCW, the application of industrial insurance as provided in Title 51 RCW, and chapter 43.101 RCW relating to training of law enforcement officers, shall apply to code cities. Any code city may retain any civil service system theretofore in effect in such city and may adopt any system of civil service which would be available to any class of city under general law.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1907-S.SL.pdf?cite=1991%20sp.s.%20c%2030%20§%2020[1991 sp.s. c 30 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%2066[1983 c 3 § 66]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.41.020[1967 ex.s. c 119 § 35A.41.020]; ]

== 35A.41.030 - City contracts to obtain sheriff's office law enforcement services.
See RCW 41.14.250 through 41.14.280.

[ ]

