= 35A.27 - Libraries, museums, and historical activities.
:toc:

== 35A.27.010 - General laws applicable.
Every code city may exercise the powers relating to the acquisition, development, improvement and operation of libraries and museums and the preservation of historical materials to the same extent authorized by general law for cities of any class, including, but not limited to, the authority for city libraries granted by RCW 35.22.280, the power to acquire and operate art museums, auditoriums, and other facilities as authorized by RCW 35.21.020, to participate in the establishment of regional libraries, and to contract for library service for public libraries with county, intercounty, and rural library districts, and for regional libraries as authorized by chapter 27.12 RCW, to have a county law library or branch thereof generally under the provisions of chapter 27.24 RCW, to preserve historical materials, markers, graves and records as provided in chapters 27.48 and 27.34 RCW, and to expend municipal funds thereon.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c7.pdf?cite=1985%20c%207%20§%20101[1985 c 7 § 101]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%2060[1983 c 3 § 60]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967ex1c119.pdf?cite=1967%20ex.s.%20c%20119%20§%2035A.27.010[1967 ex.s. c 119 § 35A.27.010]; ]

