= 38.12 - Militia officers and advisory council.
:toc:

== 38.12.010 - Adjutant general—Bond.
The governor, with the advice and consent of the senate, shall appoint an adjutant general who shall be chief of staff to the governor, and may be removed by the governor at will. The adjutant general shall appoint the civilian employees and other personnel of the department and may remove any of them in accordance with applicable law.

The expenses of the adjutant general's department, necessary to the military service, shall be audited, allowed, and paid as other military expenditures.

The adjutant general must execute an official bond running to the state in the penal sum of twenty thousand dollars conditioned for the faithful performance of his or her duties. The bond shall be submitted to the attorney general for approval, and when approved shall be filed in the office of the secretary of state. The cost of the bond shall be paid by the state.

The adjutant general may obtain and pay for, from funds appropriated for military purposes, a surety bond or bonds running to the state covering such officers of the organized militia responsible to the state for money or military property, as may be advisable to insure proper accountability. The bond or bonds shall be approved and filed in the same manner as the adjutant general's bond.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c19.pdf?cite=1989%20c%2019%20§%2011[1989 c 19 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c338.pdf?cite=1981%20c%20338%20§%203[1981 c 338 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c250.pdf?cite=1957%20c%20250%20§%202[1957 c 250 § 2]; 1943 c 130 § 16, part; 1917 c 107 § 11, part; 1913 c 66 § 4, part; 1909 c 134 § 27, part; 1901 c 78 § 4, part; 1895 c 108 § 38, part; Rem. Supp. 1943 § 8603-16, part; ]

== 38.12.015 - Department organized into separate divisions—Army national guard—Air national guard—Assistant adjutants general.
The adjutant general's department shall be organized into separate divisions for the Washington army national guard and the Washington air national guard. Each division may have a general officer at its head who will be referred to as the assistant adjutant general for the Washington army national guard and the assistant adjutant general for the Washington air national guard.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c210.pdf?cite=1961%20c%20210%20§%202[1961 c 210 § 2]; ]

== 38.12.020 - Powers and duties.
The adjutant general shall:

. Subject to the orders of the commander-in-chief, command the Washington national guard and recruit, train, maintain, and administer the organized militia of the state of Washington.

. Supervise the preparation and submission of any records required by the federal government, the governor, or as otherwise required by law.

. Maintain records of the organized militia and state military department as required by law. The adjutant general shall deposit records with the state archivist for historical purposes.

. Cause to be published and distributed to the organized militia at state expense necessary documents or publications, to include the Washington code of military justice.

. Keep just and true accounts of all moneys received and disbursed by the military department.

. Attest all commissions issued to military officers of this state.

. Be the custodian of the seal of the office of adjutant general and deliver the same to his or her successor. All orders issued from the office of the adjutant general shall be authenticated with the seal. Orders or records under the seal shall be prima facie proof of certification or authenticity.

. Promulgate in orders such regulations pertaining to the operation and function of the state military department and organized militia, as in his or her opinion the conditions demand.

. Attend to the care, preservation, safekeeping, and repairing of all military property belonging to the state, or issued to the state by the United States for military purposes. Any property of the state military department which, after proper inspection, is found unsuitable or no longer needed for use of the organized militia shall be disposed of in such manner as the governor shall direct and the proceeds thereof used for replacements in kind or by other needed authorized military supplies, and the adjutant general may execute the necessary instruments of conveyance to effect such sale or disposal.

. Issue the military property as the necessity of service requires and make purchases for that purpose. 

. Be the custodian of all military relics, trophies, colors, and histories now in possession of, or which may be acquired by, the state.

. Keep a record of all real property owned or used by the state for military purposes, and in connection therewith he or she shall have sole power to execute all leases to acquire the use of real property by the state for military purposes, or lease it to other agencies for use for authorized activities. The adjutant general shall also have full power to execute and grant easements for rights-of-way for construction, operation, and maintenance of utility service, water, sewage, and drainage for such realty.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5030-S.SL.pdf?cite=2009%20c%2021%20§%201[2009 c 21 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c19.pdf?cite=1989%20c%2019%20§%2012[1989 c 19 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977c75.pdf?cite=1977%20c%2075%20§%2032[1977 c 75 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1957c250.pdf?cite=1957%20c%20250%20§%203[1957 c 250 § 3]; 1943 c 130 § 16, part; 1917 c 107 § 11, part; 1913 c 66 § 4, part; 1909 c 134 § 27, part; 1901 c 78 § 4, part; 1895 c 108 § 38, part; Rem. Supp. 1943 § 8603-16, part; ]

== 38.12.030 - Adjutant general and assistant adjutants general—How chosen—Annual salaries—Members of judiciary eligible to serve in guard.
Whenever a vacancy has occurred, or is about to occur in the office of the adjutant general, the governor shall order to active service for that position from the active list of the Washington army national guard or Washington air national guard an officer not below the rank of a field grade officer who has had at least ten years service as an officer on the active list of the Washington army national guard or the Washington air national guard during the fifteen years next prior to such detail. The officer so detailed shall during the continuance of his or her service as the adjutant general hold the rank of a general officer.

Whenever a vacancy has occurred, or is about to occur, in the offices of assistant adjutants general for the Washington army national guard or the Washington air national guard, the adjutant general with the concurrence of the governor may appoint an officer of the army national guard or the air national guard, who has had at least ten years service in the active list of his respective branch during the fifteen years next prior to such detail. The officer so detailed, may during the continuance of his service as assistant adjutant general hold the rank of a general officer.

If, by reason of the call or draft of officers of the Washington army national guard and/or air national guard into federal service, there is no officer of the Washington national guard available for detail as the adjutant general or as an assistant adjutant general who possesses the requisite qualifications, the governor may appoint any officer or former officer of the organized militia of Washington as acting adjutant general or as an acting assistant adjutant general. If the officers on detail as the adjutant general or as assistant adjutants general are appointed, called, or drafted into the military service of the United States by order or proclamation of the president, they shall be granted leaves of absence by the governor, and are entitled, upon release from federal service, to return to their former status as adjutant general or as assistant adjutants general of Washington, and during the period that they are in federal service, the duties of these offices shall be performed by an acting adjutant general and acting assistant adjutants general, appointed by the governor, as provided in this section, who shall receive the same pay provided for the adjutant general and/or assistant adjutants general respectively, during the period of such assignments.

The adjutant general shall receive an annual salary equal to the base pay of a major general in the United States army. The assistant adjutant general for the Washington army national guard and the assistant adjutant general for the Washington air national guard shall each receive an annual salary equal to the base pay of an officer of equivalent grade in the United States army or United States air force but not to exceed that of a brigadier general. So long as a member of the judiciary of the state of Washington is available for judicial work at such times and under such conditions as may be set forth by local rules and custom, that member may serve as an active member of the national guard or air national guard.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c19.pdf?cite=1989%20c%2019%20§%2013[1989 c 19 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c218.pdf?cite=1983%20c%20218%20§%201[1983 c 218 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c100.pdf?cite=1965%20ex.s.%20c%20100%20§%201[1965 ex.s. c 100 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c210.pdf?cite=1961%20c%20210%20§%203[1961 c 210 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c130.pdf?cite=1943%20c%20130%20§%2021[1943 c 130 § 21]; Rem. Supp. 1943 § 8603-21; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1921c75.pdf?cite=1921%20c%2075%20§%202[1921 c 75 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c107.pdf?cite=1917%20c%20107%20§%2014[1917 c 107 § 14]; 1909 c 134 § 31, part; 1895 c 108 § 42, part; ]

== 38.12.060 - Officers to be commissioned by the governor.
All commissioned and warrant officers of the organized militia of Washington shall be appointed and commissioned or warranted by the governor only as hereinafter provided. No person shall be so appointed and commissioned or warranted unless he or she shall be a citizen of the United States and of this state and more than eighteen years of age. Every commissioned and warranted officer shall hold office under his or her commission or warrant until he or she shall have been regularly appointed and commissioned or warranted to another rank or office, or until he or she shall have been regularly retired, discharged, dismissed or placed in the reserve.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c19.pdf?cite=1989%20c%2019%20§%2014[1989 c 19 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c292.pdf?cite=1971%20ex.s.%20c%20292%20§%2041[1971 ex.s. c 292 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c130.pdf?cite=1943%20c%20130%20§%2019[1943 c 130 § 19]; Rem. Supp. 1943 § 8603-19; 1917 c 107 § 12, part; 1909 c 134 § 31, part; 1895 c 108 § 42, part; ]

== 38.12.070 - Examining board.
No person shall be appointed and commissioned or warranted to any office in the organized militia of Washington unless he or she shall have been examined and adjudged qualified therefor by an examining board, appointed by the adjutant general, and whose report shall have been approved by the authority appointing the board. The composition, appointment and procedure of examining boards and the nature and scope of examinations shall be as prescribed by the laws or regulations of the United States or those of this state. Whenever a commissioned officer shall have been examined for promotion pursuant to this section and shall have been adjudged not qualified therefor, upon approval by the authority appointing the board of its report to that effect such officer may be honorably discharged, retired or placed in the reserve as the governor shall direct.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c19.pdf?cite=1989%20c%2019%20§%2015[1989 c 19 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c130.pdf?cite=1943%20c%20130%20§%2020[1943 c 130 § 20]; Rem. Supp. 1943 § 8603-20; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c107.pdf?cite=1917%20c%20107%20§%2013[1917 c 107 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c134.pdf?cite=1909%20c%20134%20§%2032[1909 c 134 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c108.pdf?cite=1895%20c%20108%20§%2053[1895 c 108 § 53]; ]

== 38.12.095 - Appointment or promotion of commissioned officers to be made by officer promotion board—Exceptions.
Whenever a commissioned officer is to be appointed or promoted either to fill a vacancy in the organized militia (Washington army national guard, Washington air national guard and the Washington state guard) or for any other reason, the officer to be appointed or promoted shall be selected by the officer promotion board. This selection in no way will change the powers of the governor under RCW 38.12.060. This section in no way applies to appointments or promotions to adjutant general or assistant adjutant general, to the appointment of officers to the rank of captain, lieutenant, or warrant officer, or to the promotion of second lieutenants, first lieutenants, or warrant officers.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c19.pdf?cite=1989%20c%2019%20§%2016[1989 c 19 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c34.pdf?cite=1974%20ex.s.%20c%2034%20§%201[1974 ex.s. c 34 § 1]; ]

== 38.12.105 - Criteria and guidelines for promotion of commissioned officers.
All promotions of commissioned officers in the organized militia will be made on a best-qualified basis. The officer promotion board will select the best-qualified officer for each promotion from among those officers fully qualified for promotion. To be promoted, the selected officer must also meet the requirements of RCW 38.12.070. In no event will seniority be the sole guideline for selecting the officer to be promoted. The officer promotion board will, in determining the best qualified officer, consider the overall qualifications of an officer and not just the qualifications for one position.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c34.pdf?cite=1974%20ex.s.%20c%2034%20§%202[1974 ex.s. c 34 § 2]; ]

== 38.12.115 - Officer promotion board—Meetings—Powers and duties.
The officer promotion board will meet from time to time as directed by the adjutant general. The board will select the best qualified officer for each promotion to be made in the organized militia, and will do any other act pertaining thereto directed by the adjutant general or allowed or directed by statute.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c19.pdf?cite=1989%20c%2019%20§%2017[1989 c 19 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c34.pdf?cite=1974%20ex.s.%20c%2034%20§%203[1974 ex.s. c 34 § 3]; ]

== 38.12.125 - Officer promotion board—Composition.
The officer promotion board shall be composed as follows:

. For promotions of army national guard officers, the adjutant general must appoint a board that includes at least five voting members who are officers in the army national guard senior in grade to those officers being considered by the board for promotion.

.. Any officer appointed to the board who is not senior in grade to officers being considered for promotion must be recused from participating in the consideration for promotion of those officers to whom he or she is not senior.

.. For consideration of an officer for promotion to the grade of O5 and above, the board must include at least one general officer appointed by the adjutant general as a voting member.

. For promotions of air national guard officers, the adjutant general must appoint a board that includes at least five voting members who are officers in the air national guard senior in grade to those officers being considered by the board for promotion.

.. Any officer appointed to the board who is not senior in grade to officers being considered for promotion must be recused from participating in the consideration for promotion of those officers to whom he or she is not senior.

.. For consideration of an officer for promotion to the grade of O5 and above, the board must include at least one general officer appointed by the adjutant general as a voting member.

. For promotions of state guard officers, the adjutant general must appoint a board that includes at least five voting members who are officers in the state guard senior in grade to those officers being considered by the board for promotion.

.. Any officer appointed to the board who is not senior in grade to officers being considered for promotion must be recused from participating in the consideration for promotion of those officers to whom he or she is not senior.

.. For consideration of an officer for promotion to the grade of O5 and above, the board must include at least one general officer appointed by the adjutant general as a voting member.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2115.SL.pdf?cite=2014%20c%20178%20§%201[2014 c 178 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c19.pdf?cite=1989%20c%2019%20§%2018[1989 c 19 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c34.pdf?cite=1974%20ex.s.%20c%2034%20§%204[1974 ex.s. c 34 § 4]; ]

== 38.12.135 - Officer promotion board—Official acts—Approval requirements—Rules.
To be an official act of the officer promotion board, an act of that board must be approved by not less than four of the members of the board: PROVIDED, HOWEVER, That if the board consists of less than four officers, the approval of the board shall be unanimous.

An action of an officer promotion board may be an official act of the board without a meeting if all members of the board approve in writing the act in question.

The adjutant general will from time to time fix the rules under which the board will operate.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c34.pdf?cite=1974%20ex.s.%20c%2034%20§%205[1974 ex.s. c 34 § 5]; ]

== 38.12.150 - Officer to take oath.
Every officer, duly commissioned or warranted shall within such time as may be provided by law or by regulations, take the oath of office prescribed by law, and give bond, if required. In case of neglect or refusal so to do, the officer shall be considered to have resigned such office and a new appointment may be made as provided by law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c19.pdf?cite=1989%20c%2019%20§%2019[1989 c 19 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c130.pdf?cite=1943%20c%20130%20§%2029[1943 c 130 § 29]; Rem. Supp. 1943 § 8603-29; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c107.pdf?cite=1917%20c%20107%20§%2026[1917 c 107 § 26]; 1909 c 134 § 36, part; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c108.pdf?cite=1895%20c%20108%20§%2051[1895 c 108 § 51]; ]

== 38.12.160 - Oath, form of.
The oath of office for commissioned and warrant officers in the organized militia of Washington shall be substantially as follows: "I, . . . . . ., do solemnly swear that I will support and defend the Constitution of the United States and the Constitution of the state of Washington, against all enemies, foreign or domestic; that I will bear true faith and allegiance to the same; that I will obey the orders of the president of the United States and of the governor of the state of Washington, that I make this obligation freely, without any mental reservation or purpose of evasion, and that I will well and faithfully discharge the duties of the office of . . . . . . in the organized militia of the state of Washington upon which I am about to enter, so help me God."

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c130.pdf?cite=1943%20c%20130%20§%2030[1943 c 130 § 30]; Rem. Supp. 1943 § 8603-30; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c107.pdf?cite=1917%20c%20107%20§%2027[1917 c 107 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c134.pdf?cite=1909%20c%20134%20§%2037[1909 c 134 § 37]; ]

== 38.12.170 - Termination of officers' membership—Review of retention potential.
The governor may terminate the membership of any commissioned or warrant officer of the organized militia of Washington for any of the following reasons:

. Conviction of an infamous crime;

. Absence from his or her command for more than thirty days without proper leave;

. Sentence of dismissal by court martial, duly approved;

. Upon muster out of the organization to which the officer is then assigned;

. Acceptance of the resignation of the officer, but no officer may be discharged or his or her resignation accepted while under arrest or against whom military charges have been preferred, or until he or she has turned over to his or her successor or satisfactorily accounted for all state and federal moneys and military property for which he or she is accountable or responsible;

. Removal of his or her actual residence to such distance from the station of his or her command as to render it impracticable for him or her to perform the duties of his or her office;

. Incompetence or unfitness for military service as determined by the duly approved findings of a board of officers appointed for that purpose by the adjutant general.

The adjutant general shall annually appoint and convene qualitative retention boards to review the military personnel records of officers who have completed three or more years service in the Washington state guard to determine their retention potential and acceptability for continuation in an active status. In the conduct of the reviews, the regulation issued by the adjutant general to implement this provision shall conform to the extent practicable to that governing the army national guard.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c19.pdf?cite=1989%20c%2019%20§%2020[1989 c 19 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c198.pdf?cite=1984%20c%20198%20§%201[1984 c 198 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c130.pdf?cite=1943%20c%20130%20§%2031[1943 c 130 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1925ex1c72.pdf?cite=1925%20ex.s.%20c%2072%20§%201[1925 ex.s. c 72 § 1]; Rem. Supp. 1943 § 8603-31; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c107.pdf?cite=1917%20c%20107%20§%2028[1917 c 107 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c134.pdf?cite=1909%20c%20134%20§%2039[1909 c 134 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c108.pdf?cite=1895%20c%20108%20§%2063[1895 c 108 § 63]; ]

== 38.12.180 - Retirement of officers.
Commissioned officers of the organized militia of Washington shall be retired by order of the commander-in-chief with the rank respectively held by them at the time of such retirement for the following reasons:

. Unfitness for military service by reason of permanent physical disability.

. Upon request after at least five years continuous service as an officer in the organized militia of Washington.

Except as provided otherwise in RCW 38.16.015(2), commissioned officers of the state guard shall upon reaching the age of sixty-four years be retired.

Retired officers shall draw no pay or allowance from the state unless recalled to service.

Retired officers are subject, with their consent, to temporary detail on active state service by the commander-in-chief, and while on such duty shall receive the same pay and allowances as officers of like rank on the active list.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2181-S.SL.pdf?cite=2012%20c%2012%20§%202[2012 c 12 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c19.pdf?cite=1989%20c%2019%20§%2021[1989 c 19 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c198.pdf?cite=1984%20c%20198%20§%202[1984 c 198 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c130.pdf?cite=1943%20c%20130%20§%2033[1943 c 130 § 33]; Rem. Supp. 1943 § 8603-33; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c134.pdf?cite=1909%20c%20134%20§%2040[1909 c 134 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c108.pdf?cite=1895%20c%20108%20§%2066[1895 c 108 § 66]; ]

== 38.12.200 - Uniform allowance to officers.
Every commissioned officer of the organized militia of Washington shall, within sixty days from the date of the order whereby he or she shall have been appointed, provide at the officer's own expense the uniform and equipment prescribed by the governor for his or her rank and assignment.

There shall be audited and may be paid, at the option of the adjutant general, to each properly uniformed and equipped officer of the active list of the organized militia of Washington, not in federal service an initial uniform allowance of one hundred dollars and annually thereafter for each twelve months state service an additional uniform allowance of fifty dollars, subject to such regulations as the commander-in-chief may prescribe to be audited and paid upon presentation of proper voucher.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5586.SL.pdf?cite=1991%20c%2043%20§%202[1991 c 43 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c19.pdf?cite=1989%20c%2019%20§%2022[1989 c 19 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1982c93.pdf?cite=1982%20c%2093%20§%201[1982 c 93 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c130.pdf?cite=1943%20c%20130%20§%2037[1943 c 130 § 37]; Rem. Supp. 1943 § 8603-37; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1923c49.pdf?cite=1923%20c%2049%20§%201[1923 c 49 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c107.pdf?cite=1917%20c%20107%20§%2032[1917 c 107 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c134.pdf?cite=1909%20c%20134%20§%2049[1909 c 134 § 49]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1903c155.pdf?cite=1903%20c%20155%20§%2011[1903 c 155 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1901c78.pdf?cite=1901%20c%2078%20§%208[1901 c 78 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c108.pdf?cite=1895%20c%20108%20§%2076[1895 c 108 § 76]; ]

