= 38.14 - Washington state guard.
:toc:

== 38.14.006 - Availability and composition of state guard.
The Washington state guard will be available to serve, at the call of the governor in the place of the national guard of the state of Washington under the provisions of this title when the national guard is in the service of the United States, or when otherwise ordered to active state service by the governor. The Washington state guard shall consist of commissioned and warrant officers and enlisted persons commissioned, warranted, or enlisted under the provisions of this title. Persons enlisted under RCW 38.16.015 shall be enrolled in accordance with regulations promulgated by the adjutant general.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c19.pdf?cite=1989%20c%2019%20§%2023[1989 c 19 § 23]; ]

== 38.14.012 - Federal military service.
No member of the Washington state guard shall by reason of such membership be exempt from federal military service under the laws of the United States.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c19.pdf?cite=1989%20c%2019%20§%2024[1989 c 19 § 24]; ]

== 38.14.018 - Pay of state guard members.
Members of the Washington state guard shall serve without pay except when on active state service with the state as defined in RCW 38.04.010, or when serving on inactive duty as defined in RCW 38.04.010 under orders of the governor specifically authorizing pay. When ordered to active state service or when serving on inactive duty in a pay status, members of the Washington state guard will be paid as prescribed for members of the national guard in RCW 38.24.050, except longevity adjustments for pay will be based solely on total service with the Washington state guard.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c19.pdf?cite=1989%20c%2019%20§%2025[1989 c 19 § 25]; ]

== 38.14.024 - Equipment and supplies.
The governor may obtain from the federal government such arms and other equipment and supplies as may be available for issue, donation or loan for the use of the Washington state guard. When such property is provided by the federal government, it will be utilized, maintained, and disposed of in accordance with federal requirements and with property rules and regulations promulgated under the provisions of RCW 38.08.090.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c19.pdf?cite=1989%20c%2019%20§%2026[1989 c 19 § 26]; ]

== 38.14.030 - Training.
Members of the Washington state guard may participate in such training opportunities as may be available from the federal government and as approved by the adjutant general. Where required as a condition of such participation, the military department may reimburse the federal government for the costs of such training.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c19.pdf?cite=1989%20c%2019%20§%2027[1989 c 19 § 27]; ]

== 38.14.036 - Qualifications for appointment of officers.
The adjutant general shall establish by regulation qualifications for appointment of commissioned and warrant officers in the Washington state guard.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c19.pdf?cite=1989%20c%2019%20§%2028[1989 c 19 § 28]; ]

