= 38.32 - Offenses—Punishment.
:toc:

== 38.32.010 - Nonmilitary offenses by members on-duty status.
Any member of the organized militia committing nonmilitary offenses under chapter 38.38 RCW while on-duty status or within state armories shall be promptly arrested by the military authorities and turned over to the civil authorities of the county or city in which the offense was committed.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1036-S.SL.pdf?cite=2009%20c%20378%20§%201[2009 c 378 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c19.pdf?cite=1989%20c%2019%20§%2039[1989 c 19 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c220.pdf?cite=1963%20c%20220%20§%20134[1963 c 220 § 134]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c130.pdf?cite=1943%20c%20130%20§%2082[1943 c 130 § 82]; Rem. Supp. 1943 § 8603-82; ]

== 38.32.020 - Military offenses.
. Military offenses under chapter 38.38 RCW committed by members of the organized militia may be tried and punished as provided under chapter 38.38 RCW.

. Primary jurisdiction over military offenses enumerated in chapter 38.38 RCW is with military authorities. Primary jurisdiction over nonmilitary offenses is with civilian authorities. If an offense may be both military and nonmilitary, the military authorities may proceed only after the civilian authorities have declined to prosecute or dismissed the charge, provided jeopardy has not attached. Jurisdiction over attempted crimes, conspiracy crimes, solicitation, and accessory crimes must be determined by whether the underlying offense is a military or nonmilitary offense.

. Any member of the organized militia committing any offense under chapter 38.38 RCW may, if such offense is committed on a military reservation of the United States within this state, be turned over to the civil authorities for trial as provided by federal law.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/1036-S.SL.pdf?cite=2009%20c%20378%20§%202[2009 c 378 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c19.pdf?cite=1989%20c%2019%20§%2040[1989 c 19 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c220.pdf?cite=1963%20c%20220%20§%20135[1963 c 220 § 135]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c130.pdf?cite=1943%20c%20130%20§%2081[1943 c 130 § 81]; Rem. Supp. 1943 § 8603-81; ]

== 38.32.030 - Exemptions while on duty.
No person belonging to the military forces of this state shall be arrested on any warrant, except for treason or felony, while going to, remaining at, or returning from any place at which he or she may be required to attend military duty. Any members of the organized militia parading, or performing any duty according to the law shall have the right-of-way in any street or highway through which they may pass and while on field duty shall have the right to enter upon, cross, or occupy any uninclosed [unenclosed] lands, or any inclosed [enclosed] lands where no damage will be caused thereby: PROVIDED, That the carriage of the United States mail and legitimate functions of the police and fire departments shall not be interfered with thereby.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20768[2011 c 336 § 768]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c130.pdf?cite=1943%20c%20130%20§%2045[1943 c 130 § 45]; Rem. Supp. 1943 § 8603-45; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c107.pdf?cite=1917%20c%20107%20§%2040[1917 c 107 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c134.pdf?cite=1909%20c%20134%20§%2066[1909 c 134 § 66]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c108.pdf?cite=1895%20c%20108%20§%20103[1895 c 108 § 103]; ]

== 38.32.070 - Member removed from state, request for discharge.
If any member is known to have removed from the state, and, through ignorance or neglect, has failed to apply for discharge, the discharge may be requested by his or her immediate commanding officer.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c19.pdf?cite=1989%20c%2019%20§%2041[1989 c 19 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c220.pdf?cite=1963%20c%20220%20§%20136[1963 c 220 § 136]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c130.pdf?cite=1943%20c%20130%20§%2084[1943 c 130 § 84]; Rem. Supp. 1943 § 8603-84. Cf.  1917 c 107 § 83; ]

== 38.32.080 - Penalty for failure to obey call.
Any member of the militia who shall have been ordered out for either state or federal service and who shall refuse or wilfully or negligently fail to report at the time and place and to the officer designated in the order or to the representative or successor of such officer, shall be deemed guilty of desertion, and shall suffer such penalty as a general court martial may direct, unless he or she shall produce a sworn certificate from a licensed physician of good standing that he or she was physically unable to appear at the time and place designated. Any person chargeable with desertion under this section may be taken by force and compelled to serve.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c19.pdf?cite=1989%20c%2019%20§%2042[1989 c 19 § 42]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c130.pdf?cite=1943%20c%20130%20§%2010[1943 c 130 § 10]; Rem. Supp. 1943 § 8603-10; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c107.pdf?cite=1917%20c%20107%20§%2010[1917 c 107 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c134.pdf?cite=1909%20c%20134%20§%2021[1909 c 134 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c108.pdf?cite=1895%20c%20108%20§%20114[1895 c 108 § 114]; ]

== 38.32.090 - Penalty for physician making false certificate.
Any physician who shall knowingly make and deliver a false certificate of physical disability concerning any member of the militia who shall have been ordered out or summoned for active service is guilty of perjury under chapter 9A.72 RCW and, upon conviction, as an additional penalty, shall forfeit forever his or her license and right to practice in this state.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20209[2003 c 53 § 209]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c19.pdf?cite=1989%20c%2019%20§%2043[1989 c 19 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c130.pdf?cite=1943%20c%20130%20§%2011[1943 c 130 § 11]; Rem. Supp. 1943 § 8603-11; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c134.pdf?cite=1909%20c%20134%20§%2022[1909 c 134 § 22]; ]

== 38.32.100 - Buying and receiving military property.
Any person who shall purchase or receive in pawn or pledge any military property of the state or of the United States shall be guilty of a gross misdemeanor and, upon conviction thereof, shall be fined not more than five hundred dollars or imprisoned for not more than six months or both such fine and imprisonment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c130.pdf?cite=1943%20c%20130%20§%2087[1943 c 130 § 87]; Rem. Supp. 1943 § 8603-87. Cf.  1917 c 107 § 68; ]

== 38.32.120 - Authority of commanding officer.
. The commanding officer at any drill, parade, encampment or other duty may place in arrest for the time of such drill, parade, encampment or other duty any person or persons who shall trespass on the camp grounds, parade grounds, rifle range or armory, or in any way or manner interrupt or molest the orderly discharge of duty of those on duty, or who shall disturb or prevent the passage of troops going to or returning from any regularly ordered tour of duty; and may prohibit and prevent the sale or use of all spirituous liquors, wines, ale or beer, or holding of huckster or auction sales, and all gambling therein, and remove disorderly persons beyond the limits of such parade or encampment, or within a distance of two miles therefrom, and the commanding officer shall have full authority to abate as common nuisances all disorderly places, and bar all unauthorized sales within such limits.

. Any person violating this section, or any order issued in pursuance thereof, is guilty of a misdemeanor and upon conviction shall be fined not more than one hundred dollars, or imprisoned not more than thirty days, or both such fine and imprisonment.

. No license or renewal thereof shall be issued or granted to any person, firm or corporation for the sale of intoxicating or spirituous liquors within a distance of three hundred feet from any armory used by the state of Washington for military purposes, without the approval of the adjutant general.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20210[2003 c 53 § 210]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c19.pdf?cite=1989%20c%2019%20§%2044[1989 c 19 § 44]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c220.pdf?cite=1963%20c%20220%20§%20137[1963 c 220 § 137]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c130.pdf?cite=1943%20c%20130%20§%2052[1943 c 130 § 52]; Rem. Supp. 1943 § 8603-52; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c51.pdf?cite=1937%20c%2051%20§%201[1937 c 51 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c134.pdf?cite=1909%20c%20134%20§%2062[1909 c 134 § 62]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1895c108.pdf?cite=1895%20c%20108%20§%2099[1895 c 108 § 99]; ]

== 38.32.140 - Sentence to confinement.
All military courts of the organized militia of Washington shall have power to sentence to confinement in lieu of fines authorized to be imposed: PROVIDED, That such sentence of confinement shall not exceed one day for each dollar of fine authorized.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c130.pdf?cite=1943%20c%20130%20§%2061[1943 c 130 § 61]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c107.pdf?cite=1917%20c%20107%20§%2053[1917 c 107 § 53]; Rem. Supp. 1943 § 8603-61; ]

