= 38.42 - Service members' civil relief.
:toc:

== 38.42.010 - Definitions.
The definitions in this section apply throughout this chapter, unless the context clearly requires otherwise.

. "Attorney general" means the attorney general of the state of Washington or any person designated by the attorney general to carry out a responsibility of the attorney general under this chapter.

. "Business loan" means a loan or extension of credit granted to a business entity that: (a) Is owned and operated by a service member, in which the service member is either (i) a sole proprietor, or (ii) the owner of at least fifty percent of the entity; and (b) experiences a material reduction in revenue due to the service member's military service.

. "Dependent" means:

.. The service member's spouse;

.. The service member's minor child; or

.. An individual for whom the service member provided more than one-half of the individual's support for one hundred eighty days immediately preceding an application for relief under this chapter.

. "Financial institution" means an institution as defined in RCW 30A.22.041.

. "Judgment" does not include temporary orders as issued by a judicial court or administrative tribunal in domestic relations cases under Title 26 RCW, including but not limited to establishment of a temporary child support obligation, creation of a temporary parenting plan, or entry of a temporary protective or restraining order.

. "Military service" means a service member:

.. Under a call to active service authorized by the president of the United States or the secretary of defense for a period of more than thirty consecutive days; or

.. Under a call to active service authorized by the governor under RCW 38.08.040 for a period of more than thirty consecutive days.

. "National guard" has the meaning in RCW 38.04.010.

. "Service member" means an active member of the United States armed forces, a member of a military reserve component, or a member of the national guard who is either stationed in or a resident of Washington state.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1056.SL.pdf?cite=2018%20c%20197%20§%201[2018 c 197 § 1]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2171-S.SL.pdf?cite=2014%20c%2065%20§%201[2014 c 65 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5627-S.SL.pdf?cite=2012%20c%2024%20§%201[2012 c 24 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2497-S.SL.pdf?cite=2006%20c%20253%20§%201[2006 c 253 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2173-S.SL.pdf?cite=2005%20c%20254%20§%201[2005 c 254 § 1]; ]

== 38.42.020 - Applicability of chapter.
. Any service member who is ordered to report for military service and his or her dependents are entitled to the rights and protections of this chapter during the period beginning on the date on which the service member receives the order and ending one hundred eighty days after termination of or release from military service.

. This chapter applies to any judicial or administrative proceeding commenced in any court or agency in Washington state in which a service member or his or her dependent is a party. This chapter does not apply to criminal proceedings.

. This chapter shall be construed liberally so as to provide fairness and do substantial justice to service members and their dependents.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2171-S.SL.pdf?cite=2014%20c%2065%20§%202[2014 c 65 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2173-S.SL.pdf?cite=2005%20c%20254%20§%202[2005 c 254 § 2]; ]

== 38.42.030 - Protection of persons secondarily liable.
. Whenever pursuant to this chapter a court stays, postpones, or suspends (a) the enforcement of an obligation or liability, (b) the prosecution of a suit or proceeding, (c) the entry or enforcement of an order, writ, judgment, or decree, or (d) the performance of any other act, the court may likewise grant such a stay, postponement, or suspension to a surety, guarantor, endorser, accommodation maker, comaker, or other person who is or may be primarily or secondarily subject to the obligation or liability the performance or enforcement of which is stayed, postponed, or suspended.

. When a judgment or decree is vacated or set aside, in whole or in part, pursuant to this chapter, the court may also set aside or vacate, as the case may be, the judgment or decree as to a surety, guarantor, endorser, accommodation maker, comaker, or other person who is or may be primarily or secondarily liable on the contract or liability for the enforcement of the judgment decree.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2173-S.SL.pdf?cite=2005%20c%20254%20§%203[2005 c 254 § 3]; ]

== 38.42.040 - Waiver of rights pursuant to written agreement.
. A service member may waive any of the rights and protections provided by this chapter. In the case of a waiver that permits an action described in subsection (2) of this section, the waiver is effective only if made pursuant to a written agreement of the parties that is executed during or after the service member's period of military service. The written agreement shall specify the legal instrument to which the waiver applies and, if the service member is not party to that instrument, the service member concerned.

. The requirement in subsection (1) of this section for a written waiver applies to the following: (a) The modification, termination, or cancellation of a contract, lease, or bailment; or an obligation secured by a mortgage, trust, deed, lien, or other security in the nature of a mortgage; and (b) the repossession, retention, foreclosure, sale, forfeiture, or taking possession of property that is security for any obligation or was purchased or received under a contract, lease, or bailment.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2173-S.SL.pdf?cite=2005%20c%20254%20§%204[2005 c 254 § 4]; ]

== 38.42.050 - Protection of service members and their dependents against default judgments.
. This section applies to any civil action or proceeding in which a service member or his or her dependent is a defendant and does not make an appearance under applicable court rules or by law.

. In any action or proceeding covered by this section, the court, before entering judgment for the plaintiff, shall require the plaintiff to file with the court an affidavit:

.. Stating whether the defendant is in military service, or is a dependent of a service member in military service, and showing necessary facts to support the affidavit; or

.. If the plaintiff is unable to determine whether the defendant is in military service or is a dependent of a service member in military service, stating that the plaintiff is unable to determine whether the defendant is in military service or is a dependent of a service member in military service.

. [Empty]
.. To determine whether or not a defendant is a dependent of a service member in the military service under this chapter, the plaintiff may serve on or mail via first-class mail to the defendant a written notice in substantially the following form:



"NOTICE: State and federal law provide protections to defendants who are in the military service, and to their dependents. Dependents of a service member are the service member's spouse, the service member's minor child, or an individual for whom the service member provided more than one-half of the individual's support for one hundred eighty days immediately preceding an application for relief.

One protection provided is the protection against the entry of a default judgment in certain circumstances. This notice pertains only to a defendant who is a dependent of a member of the national guard or a military reserve component under a call to active service, or a national guard member under a call to service authorized by the governor of the state of Washington, for a period of more than thirty consecutive days. Other defendants in military service also have protections against default judgments not covered by this notice. If you are the dependent of a member of the national guard or a military reserve component under a call to active service, or a national guard member under a call to service authorized by the governor of the state of Washington, for a period of more than thirty consecutive days, you should notify the plaintiff or the plaintiff's attorneys in writing of your status as such within twenty days of the receipt of this notice. If you fail to do so, then a court or an administrative tribunal may presume that you are not a dependent of an active duty member of the national guard or reserves, or a national guard member under a call to service authorized by the governor of the state of Washington, and proceed with the entry of an order of default and/or a default judgment without further proof of your status. Your response to the plaintiff or plaintiff's attorneys about your status does not constitute an appearance for jurisdictional purposes in any pending litigation nor a waiver of your rights."

.. If the notice is either served on the defendant twenty or more days prior to an application for an order of default or a default judgment, or mailed to the defendant more than twenty-three days prior to such application, and the defendant fails to timely respond, then for purposes of entry of an order of default or default judgment, the court or administrative tribunal may presume that the defendant is not a dependent of a service member in the military service under this chapter.

.. Nothing prohibits the plaintiff from allowing a defendant more than twenty days to respond to the notice, or from amending the notice to so provide.

. If in an action covered by this section it appears that the defendant is in military service or is a dependent of a service member in military service, the court may not enter a judgment until after the court appoints an attorney to represent the defendant. If an attorney appointed under this section to represent a service member or his or her dependent cannot locate the service member or dependent, actions by the attorney in the case do not waive any defense of the service member or dependent or otherwise bind the service member or dependent.

. In an action covered by this section in which the defendant is in military service or is a dependent of a service member in military service, the court shall grant a stay of proceedings until one hundred eighty days after termination of or release from military service, upon application of defense counsel, or on the court's own motion, if the court determines that:

.. There may be a defense to the action and a defense cannot be presented without presence of the defendant; or

.. After due diligence, counsel has been unable to contact the defendant or otherwise determine if a meritorious defense exists. The defendant's failure to communicate or cooperate with counsel after having been contacted is not grounds to find that counsel has been unable to contact the defendant or that counsel has been unable to determine if a meritorious defense exists.

. No bar to entry of judgment under subsection (4) of this section or requirement for grant of stay under subsection (5) of this section precludes the entry of temporary orders in domestic relations cases. If a court or administrative tribunal enters a temporary order as allowed under this subsection, it shall include a finding that failure to act, despite the absence of the service member, would result in manifest injustice to the other interested parties. Temporary orders issued without the service member's participation shall not set any precedent for the final disposition of the matters addressed therein.

. If a service member or dependent who is a defendant in an action covered by this section receives actual notice of the action, the service member or dependent may request a stay of proceedings pursuant to RCW 38.42.060.

. A person who makes or uses an affidavit permitted under this section knowing it to be false, is guilty of a class C felony.

. If a default judgment is entered in an action covered by this section against a service member or his or her dependent during the service member's period of military service or within one hundred eighty days after termination of or release from military service, the court entering the judgment shall, upon application by or on behalf of the service member or his or her dependent, reopen the judgment for the purpose of allowing the service member or his or her dependent to defend the action if it appears that:

.. The service member or dependent was materially affected by reason of that military service in making a defense to the action; and

.. The service member or dependent has a meritorious or legal defense to the action or some part of it.

. If a court vacates, sets aside, or reverses a default judgment against a service member or his or her dependent and the vacating, setting aside, or reversing is because of a provision of this chapter, that action does not impair a right or title acquired by a bona fide purchaser for value.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5627-S.SL.pdf?cite=2012%20c%2024%20§%202[2012 c 24 § 2]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/3074.SL.pdf?cite=2006%20c%2080%20§%201[2006 c 80 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2173-S.SL.pdf?cite=2005%20c%20254%20§%205[2005 c 254 § 5]; ]

== 38.42.060 - Stay of proceedings when service member has notice.
. This section applies to any civil action or proceeding in which a defendant at the time of filing an application under this section:

.. [Empty]
... Is in military service, or it is within one hundred eighty days after termination of or release from military service; or

... Is a dependent of a service member in military service; and

.. Has received actual notice of the action or proceeding.

. At any stage before final judgment in a civil action or proceeding in which a service member or his or her dependent described in subsection (1) of this section is a party, the court may on its own motion and shall, upon application by the service member or his or her dependent, stay the action until one hundred eighty days after termination of or release from military service, if the conditions in subsection (3) of this section are met.

. An application for a stay under subsection (2) of this section shall include the following:

.. A letter or other communication setting forth facts stating the manner in which current military duty requirements materially affect the service member's or dependent's ability to appear and stating a date when the service member or dependent will be available to appear; and

.. A letter or other communication from the service member's commanding officer stating that the service member's current military duty prevents either the service member's or dependent's appearance and that military leave is not authorized for the service member at the time of the letter.

. An application for a stay under this section does not constitute an appearance for jurisdictional purposes and does not constitute a waiver of any substantive or procedural defense, including a defense relating to lack of personal jurisdiction.

. A service member or dependent who is granted a stay of a civil action or proceeding under subsection (2) of this section may apply for an additional stay based on the continuing material affect of military duty on the service member's or dependent's ability to appear. Such application may be made by the service member or his or her dependent at the time of the initial application under subsection (2) of this section or when it appears that the service member or his or her dependent is unable to prosecute or defend the action. The same information required under subsection (3) of this subsection shall be included in an application under this subsection.

. If the court refuses to grant an additional stay of proceedings under subsection (2) of this section, the court shall appoint counsel to represent the service member or his or her dependent in the action or proceeding.

. A service member or dependent who applies for a stay under this section and is unsuccessful may not seek the protections afforded by RCW 38.42.050.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2173-S.SL.pdf?cite=2005%20c%20254%20§%206[2005 c 254 § 6]; ]

== 38.42.070 - Fines and penalties under contracts.
. If an action for compliance with the terms of a contract is stayed pursuant to this chapter, a penalty shall not accrue for failure to comply with the terms of the contract during the period of the stay.

. If a service member or his or her dependent fails to perform an obligation arising under a contract and a penalty is incurred arising from that nonperformance, a court may reduce or waive the fine or penalty if:

.. [Empty]
... The service member was in military service at the time the fine or penalty was incurred; or

... The action is against a dependent of the service member and the service member was in military service at the time the fine or penalty was incurred; and

.. The ability of the service member or dependent to perform the obligation was materially affected by the military service.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2173-S.SL.pdf?cite=2005%20c%20254%20§%207[2005 c 254 § 7]; ]

== 38.42.080 - Codefendants.
If the service member or his or her dependent is a codefendant with others who are not in military service and who are not entitled to the relief and protections provided under this chapter, the plaintiff may proceed against those other defendants with the approval of the court.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2173-S.SL.pdf?cite=2005%20c%20254%20§%208[2005 c 254 § 8]; ]

== 38.42.090 - Computation of statutes of limitation.
. The period of a service member's military service may not be included in computing any period limited by law, rule, or order, for the bringing of any action or proceeding in a court, or in any board bureau, commission, department, or other agency of a state, or political subdivision of a state, or the United States by or against the service member or the service member's dependents, heirs, executors, administrators, or assigns.

. A period of military service may not be included in computing any period provided by law for the redemption of real property sold or forfeited to enforce an obligation, tax, or assessment.

. This section does not apply to any period of limitation prescribed by or under the internal revenue laws of the United States.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2173-S.SL.pdf?cite=2005%20c%20254%20§%209[2005 c 254 § 9]; ]

== 38.42.100 - Inappropriate use of chapter.
If a court determines, in any proceeding to enforce a civil right, that any interest, property, or contract has been transferred or acquired with the intent to delay the just enforcement of such right by taking advantage of this chapter, the court shall enter such judgment or make such order as might lawfully be entered or made concerning such transfer or acquisition.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2173-S.SL.pdf?cite=2005%20c%20254%20§%2010[2005 c 254 § 10]; ]

== 38.42.110 - Restructure of business loan interest rate.
. Upon the request of a service member with a qualifying business loan, the financial institution must restructure the interest rate of the loan to the equivalent provisions in the federal servicemembers civil relief act (50 U.S.C. App. 501 et seq.). The service member must notify the institution at least five days prior to the beginning of military service and submit official documentation that substantiates their eligibility for the protections of this chapter.

. This section applies only to loans with an outstanding balance of less than one hundred thousand dollars at the time the service member is called to military service.

. This section applies only to business loans executed on or after January 1, 2007.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2497-S.SL.pdf?cite=2006%20c%20253%20§%202[2006 c 253 § 2]; ]

== 38.42.120 - Federal servicemembers civil relief act—Applicability.
. The federal servicemembers civil relief act of 2003, P.L. 108-189, as amended, is specifically declared to apply in proper cases in all the courts of this state.

. A violation of the federal servicemembers civil relief act of 2003 is a violation of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2171-S.SL.pdf?cite=2014%20c%2065%20§%203[2014 c 65 § 3]; ]

== 38.42.130 - Civil action—Person aggrieved.
. Any person aggrieved by a violation of this chapter may in a civil action:

.. Obtain any appropriate equitable or declaratory relief with respect to the violation; and

.. Recover all other appropriate relief, including monetary damages.

. The court may award to a person aggrieved by a violation of this chapter who prevails in an action brought under this section the costs of the action, including reasonable attorneys' fees.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1056.SL.pdf?cite=2018%20c%20197%20§%202[2018 c 197 § 2]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2171-S.SL.pdf?cite=2014%20c%2065%20§%204[2014 c 65 § 4]; ]

== 38.42.140 - Civil action—Attorney general.
. Civil proceedings to enforce this chapter may be brought by the attorney general against any person that:

.. Engages in a pattern or practice of violating this chapter; or

.. Engages in a violation of this chapter that raises an issue of significant public importance.

. In a civil action commenced under this section, the court may:

.. Grant any appropriate equitable or declaratory relief, including costs and reasonable attorneys' fees, with respect to the violation of this chapter;

.. Award all other appropriate relief, including monetary damages, to any person aggrieved by the violation; and

.. To vindicate the public interest, assess a civil penalty:

... In an amount not exceeding fifty-five thousand dollars for a first violation; and

... In an amount not exceeding one hundred ten thousand dollars for any subsequent violation.

. Upon timely application, a person aggrieved by a violation of this chapter with respect to which the civil action is commenced may intervene in such an action and may obtain appropriate relief as the person could obtain in a civil action under RCW 38.42.130 with respect to that violation, along with costs and reasonable attorneys' fees.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1056.SL.pdf?cite=2018%20c%20197%20§%203[2018 c 197 § 3]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2171-S.SL.pdf?cite=2014%20c%2065%20§%205[2014 c 65 § 5]; ]

== 38.42.150 - Civil investigative demands—Standards—Limitations—Enforcement.
. Whenever the attorney general believes that any person may: (a) Be in possession, custody, or control of any original or copy of any book, record, report, memorandum, paper, communication, tabulation, map, chart, photograph, mechanical transcription, or other tangible document or recording, wherever situated, which he or she believes to be relevant to the subject matter of an investigation of a possible violation of this chapter, or federal statutes dealing with the same or similar matters that the attorney general is authorized to enforce; or (b) have knowledge of any information that the attorney general believes relevant to the subject matter of such an investigation, he or she may, prior to the institution of a civil proceeding thereon, execute in writing and cause to be served upon such a person, a civil investigative demand requiring such a person to produce the documentary material and permit inspection and copying, to answer in writing written interrogatories, to give oral testimony, or any combination of these demands pertaining to the documentary material or information. Documents and information obtained under this section are not admissible in criminal prosecutions.

. Each demand must:

.. State the statute and section or sections thereof, the alleged violation of which is under investigation, and the general subject matter of the investigation;

.. If the demand is for the production of documentary material, describe the class or classes of documentary material to be produced thereunder with reasonable specificity so as fairly to indicate the material demanded;

.. Prescribe a return date within which the documentary material is to be produced, the answers to written interrogatories are to be made, or a date, time, and place at which oral testimony is to be taken; and

.. Identify the members of the attorney general's staff to whom the documentary material is to be made available for inspection and copying, to whom answers to written interrogatories are to be made, or who are to conduct the examination for oral testimony.

. No demand may:

.. Contain any requirement that would be unreasonable or improper if contained in a subpoena duces tecum, a request for answers to written interrogatories, or a request for deposition upon oral examination issued by a court of this state; or

.. Require the disclosure of any documentary material that would be privileged or which for any other reason would not be required by a subpoena duces tecum issued by a court of this state.

. Service of such a demand may be made by:

.. Delivering a duly executed copy thereof to the person to be served, or, if such a person is not a natural person, to any officer or managing agent of the person to be served;

.. Delivering a duly executed copy thereof to the principal place of business in this state of the person to be served; or

.. Mailing by registered or certified mail a duly executed copy thereof addressed to the person to be served at the principal place of business in this state, or, if the person has no place of business in this state, to his or her principal office or place of business.

. [Empty]
.. Documentary material demanded pursuant to the provisions of this section must be produced for inspection and copying during normal business hours at the principal office or place of business of the person served, or at such other times and places as may be agreed upon by the person served and the attorney general.

.. Written interrogatories in a demand served under this section must be answered in the same manner as provided in the civil rules for superior court.

.. The oral testimony of any person obtained pursuant to a demand served under this section must be taken in the same manner as provided in the civil rules for superior court for the taking of depositions. In the course of the deposition, the assistant attorney general conducting the examination may exclude from the place where the examination is held all persons other than the person being examined, the person's counsel, and the officer before whom the testimony is to be taken.

.. Any person compelled to appear pursuant to a demand for oral testimony under this section may be accompanied by counsel.

.. The oral testimony of any person obtained pursuant to a demand served under this section must be taken in the county within which the person resides, is found, or transacts business, or in another place as may be agreed upon between the person served and the attorney general.

. If, after prior court approval, a civil investigative demand specifically prohibits disclosure of the existence or content of the demand, unless otherwise ordered by a superior court for good cause shown, it is a misdemeanor for any person if not a bank, trust company, mutual savings bank, credit union, or savings and loan association organized under the laws of the United States or of any one of the states to disclose to any other person the existence or content of the demand, except for disclosure to counsel for the recipient of the demand or unless otherwise required by law.

. No documentary material, answers to written interrogatories, or transcripts of oral testimony produced pursuant to a demand, or copies thereof, shall, unless otherwise ordered by a superior court for good cause shown, be produced for inspection or copying by, nor may the contents thereof be disclosed to, other than an authorized employee of the attorney general, without the consent of the person who produced the material, answered written interrogatories, or gave oral testimony, except as otherwise provided in this section: PROVIDED, That:

.. Under the reasonable terms and conditions as the attorney general prescribes, the copies of the documentary material, answers to written interrogatories, or transcripts of oral testimony must be available for inspection and copying by the person who produced the material, answered written interrogatories, or gave oral testimony, or any duly authorized representative of such a person;

.. The attorney general or any assistant attorney general may use the copies of documentary material, answers to written interrogatories, or transcripts of oral testimony as he or she determines necessary in the enforcement of this chapter, including presentation before any court: PROVIDED, That any material, answers to written interrogatories, or transcripts of oral testimony that contain trade secrets may not be presented except with the approval of the court in which action is pending after adequate notice to the person furnishing the material, answers to written interrogatories, or oral testimony.

. At any time before the return date specified in the demand, or within twenty days after the demand has been served, whichever period is shorter, a petition to extend the return date for, or to modify or set aside a demand issued pursuant to subsection (1) of this section, stating good cause, may be filed in the superior court for Thurston county, or in another county where the parties reside. A petition, by the person on whom the demand is served, stating good cause, to require the attorney general or any person to perform any duty imposed by the provisions of this section, and all other petitions in connection with a demand, may be filed in the superior court for Thurston county, or in the county where the parties reside. The court has jurisdiction to impose such sanctions as are provided for in the civil rules for superior court with respect to discovery motions.

. Whenever any person fails to comply with any civil investigative demand for documentary material, answers to written interrogatories, or oral testimony duly served upon him or her under this section, or whenever satisfactory copying or reproduction of any such material cannot be done and the person refuses to surrender the material, the attorney general may file, in the trial court of general jurisdiction of the county in which the person resides, is found, or transacts business, and serve upon the person a petition for an order of the court for the enforcement of this section, except that if the person transacts business in more than one county the petition must be filed in the county in which the person maintains his or her principal place of business, or in another county as may be agreed upon by the parties to the petition. Whenever any petition is filed in the trial court of general jurisdiction of any county under this section, the court has jurisdiction to hear and determine the matter so presented and to enter such an order or orders as may be required to carry into effect the provisions of this section, and may impose such sanctions as are provided for in the civil rules for superior court with respect to discovery motions.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/2171-S.SL.pdf?cite=2014%20c%2065%20§%206[2014 c 65 § 6]; ]

== 38.42.160 - Termination or suspension of contracts upon receipt of military service orders.
. A service member may, upon written notice, including electronic mail, terminate or suspend a contract described in subsection (2) of this section at any time after the date the service member receives military service orders:

.. For a permanent change of station; or

.. To deploy with a military unit, or as an individual in support of a military operation, for a period of not less than thirty days.

. For the purposes of this section, a contract includes the provision of any of the following:

.. Telecommunication services from a telecommunications company, as defined in RCW 80.04.010, except as provided in subsection (7) of this section;

.. Internet services provided from an internet service provider;

.. Health studio services from a health studio, as defined in RCW 19.142.010; and

.. Subscription television services, as defined in RCW 9A.56.010, from a television service provider.

. The service member must provide written proof to the service provider of the official orders showing that the service member has been called into military service:

.. At the time written notice is given; or

.. If precluded by military necessity or circumstances that make the provision of proof at the time of giving written notice unreasonable or impossible, within ninety days after written notice has been given.

. A termination or suspension of services under this section is effective on the day written notice is given under subsection (2) of this section. The termination or suspension of services does not eliminate or alter any contractual obligation to pay for services rendered before the effective date of the written notice, unless otherwise provided for by law.

. [Empty]
.. A service member who terminates or suspends the provision of services under this section may upon giving written notice, including electronic mail, to the provider within ninety days after termination of the service member's military service, reinstate the provision of services:

... On the same terms and conditions as originally agreed upon with the service provider before the termination or suspension, if the service member was in military service no longer than twelve consecutive months; or

... On the same terms and conditions that have been offered by the provider to any new consumer at the lowest discounted or promotional rate within the previous twelve-month period immediately before termination of the service member's military service, if the service member was in military service longer than twelve consecutive months.

.. Upon receipt of the written notice of reinstatement, the service provider must resume the provision of services or, if the services are no longer available, provide substantially similar services within a reasonable period of time not to exceed thirty days from the date of receipt of the written notice of reinstatement.

. A service member who terminates, suspends, or reinstates the provision of services under this section:

.. May not be charged a penalty, fee, loss of deposit, or any other additional cost because of the termination, suspension, or reinstatement; and

.. Is not liable for payment for any services after the effective date of the termination or suspension, or until the effective date of a reinstatement of services as described in subsection (4) of this section.

. A service member may terminate a contract for any service provided by a commercial mobile radio services provider in accordance with 50 U.S.C. Sec. 3956.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1056.SL.pdf?cite=2018%20c%20197%20§%204[2018 c 197 § 4]; ]

== 38.42.900 - Short title.
This chapter may be known and cited as the Washington service members' civil relief act.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2173-S.SL.pdf?cite=2005%20c%20254%20§%2011[2005 c 254 § 11]; ]

== 38.42.903 - Effective date—2005 c 254.
This act is necessary for the immediate preservation of the public peace, health, or safety, or support of the state government and its existing public institutions, and takes effect immediately [May 3, 2005].

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2173-S.SL.pdf?cite=2005%20c%20254%20§%2015[2005 c 254 § 15]; ]

== 38.42.904 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%2083[2009 c 521 § 83]; ]

