= 38.52 - Emergency management.
:toc:

== 38.52.005 - State military department to administer emergency management program—Local organizations authorized to change name.
The department shall administer the comprehensive emergency management program of the state of Washington as provided for in this chapter. All local organizations, organized and performing emergency management functions pursuant to RCW 38.52.070, may change their name and be called the . . . . . . department/division of emergency management.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1017-S.SL.pdf?cite=1995%20c%20391%20§%201[1995 c 391 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2022[1986 c 266 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%201[1984 c 38 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1972ex1c6.pdf?cite=1972%20ex.s.%20c%206%20§%201[1972 ex.s. c 6 § 1]; ]

== 38.52.010 - Definitions.
As used in this chapter:

. "Broadcaster" means a person or entity that holds a license issued by the federal communications commission under 47 C.F.R. Part 73, 74, 76, or 78.

. [Empty]
.. "Catastrophic incident" means any natural or human-caused incident, including terrorism and enemy attack, that results in extraordinary levels of mass casualties, damage, or disruption severely affecting the population, infrastructure, environment, economy, or government functions.

.. "Catastrophic incident" does not include an event resulting from individuals exercising their rights, under the first amendment, of freedom of speech, and of the people to peaceably assemble.

. "Communication plan," as used in RCW 38.52.070, means a section in a local comprehensive emergency management plan that addresses emergency notification of life safety information.

. "Continuity of government planning" means the internal effort of all levels and branches of government to provide that the capability exists to continue essential functions and services following a catastrophic incident. These efforts include, but are not limited to, providing for: (a) Orderly succession and appropriate changes of leadership whether appointed or elected; (b) filling vacancies; (c) interoperability communications; and (d) processes and procedures to reconvene government following periods of disruption that may be caused by a catastrophic incident. Continuity of government planning is intended to preserve the constitutional and statutory authority of elected officials at the state and local level and provide for the continued performance of essential functions and services by each level and branch of government.

. "Continuity of operations planning" means the internal effort of an organization to provide that the capability exists to continue essential functions and services in response to a comprehensive array of potential emergencies or disasters.

. "Department" means the state military department.

. "Director" means the adjutant general.

. "Emergency management" or "comprehensive emergency management" means the preparation for and the carrying out of all emergency functions, other than functions for which the military forces are primarily responsible, to mitigate, prepare for, respond to, and recover from emergencies and disasters, and to aid victims suffering from injury or damage, resulting from disasters caused by all hazards, whether natural, technological, or human caused, and to provide support for search and rescue operations for persons and property in distress. However, "emergency management" or "comprehensive emergency management" does not mean preparation for emergency evacuation or relocation of residents in anticipation of nuclear attack.

. [Empty]
.. "Emergency or disaster" as used in all sections of this chapter except RCW 38.52.430 means an event or set of circumstances which: (i) Demands immediate action to preserve public health, protect life, protect public property, or to provide relief to any stricken community overtaken by such occurrences; or (ii) reaches such a dimension or degree of destructiveness as to warrant the governor proclaiming a state of emergency pursuant to RCW 43.06.010.

.. "Emergency" as used in RCW 38.52.430 means an incident that requires a normal police, coroner, fire, rescue, emergency medical services, or utility response as a result of a violation of one of the statutes enumerated in RCW 38.52.430.

. "Emergency response" as used in RCW 38.52.430 means a public agency's use of emergency services during an emergency or disaster as defined in subsection (9)(b) of this section.

. "Emergency worker" means any person who is registered with a local emergency management organization or the department and holds an identification card issued by the local emergency management director or the department for the purpose of engaging in authorized emergency management activities or is an employee of the state of Washington or any political subdivision thereof who is called upon to perform emergency management activities.

. "Executive head" and "executive heads" means the county executive in those charter counties with an elective office of county executive, however designated, and, in the case of other counties, the county legislative authority. In the case of cities and towns, it means the mayor in those cities and towns with mayor-council or commission forms of government, where the mayor is directly elected, and it means the city manager in those cities and towns with council manager forms of government. Cities and towns may also designate an executive head for the purposes of this chapter by ordinance.

. "Expense of an emergency response" as used in RCW 38.52.430 means reasonable costs incurred by a public agency in reasonably making an appropriate emergency response to the incident, but shall only include those costs directly arising from the response to the particular incident. Reasonable costs shall include the costs of providing police, coroner, firefighting, rescue, emergency medical services, or utility response at the scene of the incident, as well as the salaries of the personnel responding to the incident.

. "First informer broadcaster" means an individual who:

.. Is employed by, or acting pursuant to a contract under the direction of, a broadcaster; and

.. [Empty]
... Maintains, including repairing or resupplying, transmitters, generators, or other essential equipment at a broadcast station or facility; or (ii) provides technical support services to broadcasters needed during a period of proclaimed emergency.

. "Incident command system" means: (a) An all-hazards, on-scene functional management system that establishes common standards in organization, terminology, and procedures; provides a means (unified command) for the establishment of a common set of incident objectives and strategies during multiagency/multijurisdiction operations while maintaining individual agency/jurisdiction authority, responsibility, and accountability; and is a component of the national interagency incident management system; or (b) an equivalent and compatible all-hazards, on-scene functional management system.

. "Injury" as used in this chapter shall mean and include accidental injuries and/or occupational diseases arising out of emergency management activities.

. "Life safety information" means information provided to people during a response to a life-threatening emergency or disaster informing them of actions they can take to preserve their safety. Such information may include, but is not limited to, information regarding evacuation, sheltering, sheltering-in-place, facility lockdown, and where to obtain food and water.

. "Local director" means the director of a local organization of emergency management or emergency services.

. "Local organization for emergency services or management" means an organization created in accordance with the provisions of this chapter by state or local authority to perform local emergency management functions.

. "Political subdivision" means any county, city or town.

. "Public agency" means the state, and a city, county, municipal corporation, district, town, or public authority located, in whole or in part, within this state which provides or may provide firefighting, police, ambulance, medical, or other emergency services.

. "Radio communications service company" has the meaning ascribed to it in RCW 82.14B.020.

. "Search and rescue" means the acts of searching for, rescuing, or recovering by means of ground, marine, or air activity any person who becomes lost, injured, or is killed while outdoors or as a result of a natural, technological, or human caused disaster, including instances involving searches for downed aircraft when ground personnel are used. Nothing in this section shall affect appropriate activity by the department of transportation under chapter 47.68 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5012-S.SL.pdf?cite=2019%20c%20471%20§%202[2019 c 471 § 2]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1147.SL.pdf?cite=2019%20c%20207%20§%201[2019 c 207 § 1]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5046-S.SL.pdf?cite=2017%20c%20312%20§%203[2017 c 312 § 3]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1047.SL.pdf?cite=2015%20c%2061%20§%201[2015 c 61 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1073.SL.pdf?cite=2007%20c%20292%20§%201[2007 c 292 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2595.SL.pdf?cite=2002%20c%20341%20§%202[2002 c 341 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1171-S.SL.pdf?cite=1997%20c%2049%20§%201[1997 c 49 § 1]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1017-S.SL.pdf?cite=1995%20c%20391%20§%202[1995 c 391 § 2]; prior:  1993 c 251 § 5; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5768.SL.pdf?cite=1993%20c%20206%20§%201[1993 c 206 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2023[1986 c 266 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%202[1984 c 38 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c268.pdf?cite=1979%20ex.s.%20c%20268%20§%201[1979 ex.s. c 268 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c113.pdf?cite=1975%201st%20ex.s.%20c%20113%20§%201[1975 1st ex.s. c 113 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%204[1974 ex.s. c 171 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c203.pdf?cite=1967%20c%20203%20§%201[1967 c 203 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c223.pdf?cite=1953%20c%20223%20§%202[1953 c 223 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c178.pdf?cite=1951%20c%20178%20§%203[1951 c 178 § 3]; ]

== 38.52.020 - Declaration of policy and purpose.
. Because of the existing and increasing possibility of the occurrence of disasters of unprecedented size and destructiveness as defined in *RCW 38.52.010(5), and in order to insure that preparations of this state will be adequate to deal with such disasters, to insure the administration of state and federal programs providing disaster relief to individuals, and further to insure adequate support for search and rescue operations, and generally to protect the public peace, health, and safety, and to preserve the lives and property of the people of the state, it is hereby found and declared to be necessary:

.. To provide for emergency management by the state, and to authorize the creation of local organizations for emergency management in the political subdivisions of the state;

.. To confer upon the governor and upon the executive heads of the political subdivisions of the state the emergency powers provided herein;

.. To provide for the rendering of mutual aid among the political subdivisions of the state and with other states and to cooperate with the federal government with respect to the carrying out of emergency management functions;

.. To provide a means of compensating emergency management workers who may suffer any injury, as herein defined, or death; who suffer economic harm including personal property damage or loss; or who incur expenses for transportation, telephone or other methods of communication, and the use of personal supplies as a result of participation in emergency management activities;

.. To provide programs, with intergovernmental cooperation, to educate and train the public to be prepared for emergencies; and

.. To provide for the prioritization, development, and exercise of continuity of operations plans by the state.

. It is further declared to be the purpose of this chapter and the policy of the state that all emergency management functions of this state and its political subdivisions be coordinated to the maximum extent with the comparable functions of the federal government including its various departments and agencies of other states and localities, and of private agencies of every type, to the end that the most effective preparation and use may be made of the nation's manpower, resources, and facilities for dealing with any disaster that may occur.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1047.SL.pdf?cite=2015%20c%2061%20§%202[2015 c 61 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2024[1986 c 266 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%203[1984 c 38 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c268.pdf?cite=1979%20ex.s.%20c%20268%20§%202[1979 ex.s. c 268 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c113.pdf?cite=1975%201st%20ex.s.%20c%20113%20§%202[1975 1st ex.s. c 113 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%205[1974 ex.s. c 171 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c203.pdf?cite=1967%20c%20203%20§%202[1967 c 203 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c223.pdf?cite=1953%20c%20223%20§%201[1953 c 223 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c178.pdf?cite=1951%20c%20178%20§%202[1951 c 178 § 2]; ]

== 38.52.030 - Director—Comprehensive emergency management plan—Statewide enhanced 911 emergency communications network—State coordinator of search and rescue operations—State program for emergency assistance—State coordinator for radioactive and hazardous waste emergency response programs—Interagency coordination and prioritization of continuity of operations planning—Catastrophic incidents, program to provide information and education.
. The director may employ such personnel and may make such expenditures within the appropriation therefor, or from other funds made available for purposes of emergency management, as may be necessary to carry out the purposes of this chapter.

. The director, subject to the direction and control of the governor, shall be responsible to the governor for carrying out the program for emergency management of this state. The director shall coordinate the activities of all organizations for emergency management within the state, and shall maintain liaison with and cooperate with emergency management agencies and organizations of other states and of the federal government, and shall have such additional authority, duties, and responsibilities authorized by this chapter, as may be prescribed by the governor.

. The director shall develop and maintain a comprehensive, all-hazard emergency plan for the state which shall include an analysis of the natural, technological, or human caused hazards which could affect the state of Washington, and shall include the procedures to be used during emergencies for coordinating local resources, as necessary, and the resources of all state agencies, departments, commissions, and boards. The comprehensive emergency management plan shall direct the department in times of state emergency to administer and manage the state's emergency operations center. This will include representation from all appropriate state agencies and be available as a single point of contact for the authorizing of state resources or actions, including emergency permits. The comprehensive emergency management plan must specify the use of the incident command system for multiagency/multijurisdiction operations. The comprehensive, all-hazard emergency plan authorized under this subsection may not include preparation for emergency evacuation or relocation of residents in anticipation of nuclear attack. This plan shall be known as the comprehensive emergency management plan.

. In accordance with the comprehensive emergency management plans and the programs for the emergency management of this state, the director shall procure supplies and equipment, institute training programs and public information programs, and shall take all other preparatory steps, including the partial or full mobilization of emergency management organizations in advance of actual disaster, to insure the furnishing of adequately trained and equipped forces of emergency management personnel in time of need.

. The director shall make such studies and surveys of the industries, resources, and facilities in this state as may be necessary to ascertain the capabilities of the state for emergency management, and shall plan for the most efficient emergency use thereof.

. The emergency management council shall advise the director on all aspects of the communications and warning systems and facilities operated or controlled under the provisions of this chapter.

. The director, through the state enhanced 911 coordinator, shall coordinate and facilitate implementation and operation of a statewide enhanced 911 emergency communications network.

. The director shall appoint a state coordinator of search and rescue operations to coordinate those state resources, services and facilities (other than those for which the state director of aeronautics is directly responsible) requested by political subdivisions in support of search and rescue operations, and on request to maintain liaison with and coordinate the resources, services, and facilities of political subdivisions when more than one political subdivision is engaged in joint search and rescue operations.

. The director, subject to the direction and control of the governor, shall prepare and administer a state program for emergency assistance to individuals within the state who are victims of a natural, technological, or human caused disaster, as defined by *RCW 38.52.010(6). Such program may be integrated into and coordinated with disaster assistance plans and programs of the federal government which provide to the state, or through the state to any political subdivision thereof, services, equipment, supplies, materials, or funds by way of gift, grant, or loan for purposes of assistance to individuals affected by a disaster. Further, such program may include, but shall not be limited to, grants, loans, or gifts of services, equipment, supplies, materials, or funds of the state, or any political subdivision thereof, to individuals who, as a result of a disaster, are in need of assistance and who meet standards of eligibility for disaster assistance established by the department of social and health services: PROVIDED, HOWEVER, That nothing herein shall be construed in any manner inconsistent with the provisions of Article VIII, section 5 or section 7 of the Washington state Constitution.

. The director shall appoint a state coordinator for radioactive and hazardous waste emergency response programs. The coordinator shall consult with the state radiation control officer in matters relating to radioactive materials. The duties of the state coordinator for radioactive and hazardous waste emergency response programs shall include:

.. Assessing the current needs and capabilities of state and local radioactive and hazardous waste emergency response teams on an ongoing basis;

.. Coordinating training programs for state and local officials for the purpose of updating skills relating to emergency mitigation, preparedness, response, and recovery;

.. Utilizing appropriate training programs such as those offered by the federal emergency management agency, the department of transportation and the environmental protection agency; and

.. Undertaking other duties in this area that are deemed appropriate by the director.

. The director is responsible to the governor to lead the development and management of a program for interagency coordination and prioritization of continuity of operations planning by state agencies. Each state agency is responsible for developing an organizational continuity of operations plan that is updated and exercised annually in compliance with the program for interagency coordination of continuity of operations planning.

. The director shall maintain a copy of the continuity of operations plan for election operations for each county that has a plan available.

. Subject to the availability of amounts appropriated for this specific purpose, the director is responsible to the governor to lead the development and management of a program to provide information and education to state and local government officials regarding catastrophic incidents and continuity of government planning to assist with statewide development of continuity of government plans by all levels and branches of state and local government that address how essential government functions and services will continue to be provided following a catastrophic incident.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5012-S.SL.pdf?cite=2019%20c%20471%20§%203[2019 c 471 § 3]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/2528-S.SL.pdf?cite=2018%20c%2026%20§%202[2018 c 26 § 2]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1047.SL.pdf?cite=2015%20c%2061%20§%203[2015 c 61 § 3]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1171-S.SL.pdf?cite=1997%20c%2049%20§%202[1997 c 49 § 2]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1107-S.SL.pdf?cite=1995%20c%20269%20§%201201[1995 c 269 § 1201]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5411-S.SL.pdf?cite=1991%20c%20322%20§%2020[1991 c 322 § 20]; ?cite=1991%20c%2054%20§%202[1991 c 54 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2025[1986 c 266 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%204[1984 c 38 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c113.pdf?cite=1975%201st%20ex.s.%20c%20113%20§%203[1975 1st ex.s. c 113 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c154.pdf?cite=1973%201st%20ex.s.%20c%20154%20§%2058[1973 1st ex.s. c 154 § 58]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1967c203.pdf?cite=1967%20c%20203%20§%203[1967 c 203 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c178.pdf?cite=1951%20c%20178%20§%204[1951 c 178 § 4]; ]

== 38.52.037 - Comprehensive state mine rescue plan—Submittal to legislature.
The department shall consult with appropriate local, state, federal, and private sector officials in developing a comprehensive state mine rescue plan. The plan shall identify mine rescue resources, set forth a framework for a coordinated response to mine rescue emergencies, identify shortfalls, and recommend solutions.

The draft of the comprehensive state mine rescue plan and a schedule for submittal of the final plan shall be submitted to the legislature on January 13, 1986.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2026[1986 c 266 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c459.pdf?cite=1985%20c%20459%20§%206[1985 c 459 § 6]; ]

== 38.52.040 - Emergency management council—Members—Ad hoc committees—Rules review—Function as state emergency response commission—Intrastate mutual aid committee.
. There is hereby created the emergency management council (hereinafter called the council), to consist of not more than eighteen members who shall be appointed by the adjutant general. The membership of the council shall include, but not be limited to, representatives of city and county governments, sheriffs and police chiefs, the Washington state patrol, the military department, the department of ecology, state and local fire chiefs, seismic safety experts, state and local emergency management directors, search and rescue volunteers, medical professions who have expertise in emergency medical care, building officials, private industry, and the office of the superintendent of public instruction. The representatives of private industry shall include persons knowledgeable in emergency and hazardous materials management. The councilmembers shall elect a chair from within the council membership. The members of the council shall serve without compensation, but may be reimbursed for their travel expenses incurred in the performance of their duties in accordance with RCW 43.03.050 and 43.03.060 as now existing or hereafter amended.

. The emergency management council shall advise the governor and the director on all matters pertaining to state and local emergency management. The council may appoint such ad hoc committees, subcommittees, and working groups as are required to develop specific recommendations for the improvement of emergency management practices, standards, policies, or procedures. The council shall ensure that the governor receives an annual assessment of statewide emergency preparedness including, but not limited to, specific progress on hazard mitigation and reduction efforts, implementation of seismic safety improvements, reduction of flood hazards, and coordination of hazardous materials planning and response activities. The council shall review administrative rules governing state and local emergency management practices and recommend necessary revisions to the director.

. The council or a council subcommittee shall serve and periodically convene in special session as the state emergency response commission required by the emergency planning and community right-to-know act (42 U.S.C. Sec. 11001 et seq.). The state emergency response commission shall conduct those activities specified in federal statutes and regulations and state administrative rules governing the coordination of hazardous materials policy including, but not limited to, review of local emergency planning committee emergency response plans for compliance with the planning requirements in the emergency planning and community right-to-know act (42 U.S.C. Sec. 11001 et seq.). Committees shall annually review their plans to address changed conditions, and submit their plans to the state emergency response commission for review when updated, but not less than at least once every five years. The department may employ staff to assist local emergency planning committees in the development and annual review of these emergency response plans, with an initial focus on the highest risk communities through which trains that transport oil in bulk travel. By March 1, 2018, the department shall report to the governor and legislature on progress towards compliance with planning requirements. The report must also provide budget and policy recommendations for continued support of local emergency planning.

. [Empty]
.. The intrastate mutual aid committee is created and is a subcommittee of the emergency management council. The intrastate mutual aid committee consists of not more than five members who must be appointed by the council chair from council membership. The chair of the intrastate mutual aid committee is the military department representative appointed as a member of the council. Meetings of the intrastate mutual aid committee must be held at least annually.

.. In support of the intrastate mutual aid system established in chapter 38.56 RCW, the intrastate mutual aid committee shall develop and update guidelines and procedures to facilitate implementation of the intrastate mutual aid system by member jurisdictions, including but not limited to the following: Projected or anticipated costs; checklists and forms for requesting and providing assistance; recordkeeping; reimbursement procedures; and other implementation issues. These guidelines and procedures are not subject to the rule-making requirements of chapter 34.05 RCW.

. On emergency management issues that involve early learning, kindergarten through twelfth grade, or higher education, the emergency management council must consult with representatives from the following organizations: The department of children, youth, and families; the office of the superintendent of public instruction; the state board for community and technical colleges; and an association of public baccalaureate degree-granting institutions.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1216-S2.SL.pdf?cite=2019%20c%20333%20§%209[2019 c 333 § 9]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1449-S.SL.pdf?cite=2015%20c%20274%20§%2017[2015 c 274 § 17]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1371-S2.SL.pdf?cite=2011%201st%20sp.s.%20c%2021%20§%2027[2011 1st sp.s. c 21 § 27]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20789[2011 c 336 § 789]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1585-S.SL.pdf?cite=2011%20c%2079%20§%209[2011 c 79 § 9]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1107-S.SL.pdf?cite=1995%20c%20269%20§%201202[1995 c 269 § 1202]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c81.pdf?cite=1988%20c%2081%20§%2018[1988 c 81 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%205[1984 c 38 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c57.pdf?cite=1979%20ex.s.%20c%2057%20§%208[1979 ex.s. c 57 § 8]; 1975-'76 2nd ex.s. c 34 § 82; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%206[1974 ex.s. c 171 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c178.pdf?cite=1951%20c%20178%20§%205[1951 c 178 § 5]; ]

== 38.52.050 - Governor's general powers and duties.
. The governor, through the director, shall have general supervision and control of the emergency management functions in the department, and shall be responsible for the carrying out of the provisions of this chapter, and in the event of disaster beyond local control, may assume direct operational control over all or any part of the emergency management functions within this state.

. In performing his or her duties under this chapter, the governor is authorized to cooperate with the federal government, with other states, and with private agencies in all matters pertaining to the emergency management of this state and of the nation.

. In performing his or her duties under this chapter and to effect its policy and purpose, the governor is further authorized and empowered:

.. To make, amend, and rescind the necessary orders, rules, and regulations to carry out the provisions of this chapter within the limits of the authority conferred upon him [or her] herein, with due consideration of the plans of the federal government;

.. On behalf of this state, to enter into mutual aid arrangements with other states and territories, or provinces of the Dominion of Canada and to coordinate mutual aid interlocal agreements between political subdivisions of this state;

.. To delegate any administrative authority vested in him [or her] under this chapter, and to provide for the subdelegation of any such authority;

.. To appoint, with the advice of local authorities, metropolitan or regional area coordinators, or both, when practicable;

.. To cooperate with the president and the heads of the armed forces, the emergency management agency of the United States, and other appropriate federal officers and agencies, and with the officers and agencies of other states in matters pertaining to the emergency management of the state and nation.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1171-S.SL.pdf?cite=1997%20c%2049%20§%203[1997 c 49 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2027[1986 c 266 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%206[1984 c 38 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%207[1974 ex.s. c 171 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c178.pdf?cite=1951%20c%20178%20§%206[1951 c 178 § 6]; ]

== 38.52.070 - Local organizations and joint local organizations authorized—Establishment, operation—Emergency powers, procedures—Communication plans.
. Each political subdivision of this state is hereby authorized and directed to establish a local organization or to be a member of a joint local organization for emergency management in accordance with the state comprehensive emergency management plan and program: PROVIDED, That a political subdivision proposing such establishment shall submit its plan and program for emergency management to the state director and secure his or her recommendations thereon, and verification of consistency with the state comprehensive emergency management plan, in order that the plan of the local organization for emergency management may be coordinated with the plan and program of the state. Local comprehensive emergency management plans must specify the use of the incident command system for multiagency/multijurisdiction operations. No political subdivision may be required to include in its plan provisions for the emergency evacuation or relocation of residents in anticipation of nuclear attack. If the director's recommendations are adverse to the plan as submitted, and, if the local organization does not agree to the director's recommendations for modification to the proposal, the matter shall be referred to the council for final action. The director may authorize two or more political subdivisions to join in the establishment and operation of a joint local organization for emergency management as circumstances may warrant, in which case each political subdivision shall contribute to the cost of emergency management upon such fair and equitable basis as may be determined upon by the executive heads of the constituent subdivisions. If in any case the executive heads cannot agree upon the proper division of cost the matter shall be referred to the council for arbitration and its decision shall be final. When two or more political subdivisions join in the establishment and operation of a joint local organization for emergency management each shall pay its share of the cost into a special pooled fund to be administered by the treasurer of the most populous subdivision, which fund shall be known as the . . . . . . emergency management fund. Each local organization or joint local organization for emergency management shall have a director who shall be appointed by the executive head of the political subdivision, and who shall have direct responsibility for the organization, administration, and operation of such local organization for emergency management, subject to the direction and control of such executive officer or officers. In the case of a joint local organization for emergency management, the director shall be appointed by the joint action of the executive heads of the constituent political subdivisions. Each local organization or joint local organization for emergency management shall perform emergency management functions within the territorial limits of the political subdivision within which it is organized, and, in addition, shall conduct such functions outside of such territorial limits as may be required pursuant to the provisions of this chapter.

. In carrying out the provisions of this chapter each political subdivision, in which any disaster as described in RCW 38.52.020 occurs, shall have the power to enter into contracts and incur obligations necessary to combat such disaster, protecting the health and safety of persons and property, and providing emergency assistance to the victims of such disaster. Each political subdivision is authorized to exercise the powers vested under this section in the light of the exigencies of an extreme emergency situation without regard to time-consuming procedures and formalities prescribed by law (excepting mandatory constitutional requirements), including, but not limited to, budget law limitations, requirements of competitive bidding and publication of notices, provisions pertaining to the performance of public work, entering into contracts, the incurring of obligations, the employment of temporary workers, the rental of equipment, the purchase of supplies and materials, the levying of taxes, and the appropriation and expenditures of public funds.

. [Empty]
.. Each local organization or joint local organization for emergency management that produces a local comprehensive emergency management plan must include a communication plan for notifying significant population segments of life safety information during an emergency. Local organizations and joint local organizations are encouraged to consult with affected community organizations in the development of the communication plans.

... In developing communication plans, local organizations and joint organizations should consider, as part of their determination of the extent of the obligation to provide emergency notification to significant population segments, the following factors: The number or proportion of the limited English proficiency persons eligible to be served or likely to be encountered; the frequency with which limited English proficiency individuals come in contact with the emergency notification; the nature and importance of the emergency notification, service, or program to people's lives; and the resources available to the political subdivision to provide emergency notifications.

... "Significant population segment" means, for the purposes of this subsection (3), each limited English proficiency language group that constitutes five percent or one thousand residents, whichever is less, of the population of persons eligible to be served or likely to be affected within a city, town, or county. The office of financial management forecasting division's limited English proficiency population estimates are the demographic data set for determining eligible limited English proficiency language groups.

.. Local organizations and joint local organizations must submit the plans produced under (a) of this subsection to the Washington military department emergency management division, and must implement those plans. An initial communication plan must be submitted with the local organization or joint local organization's next local emergency management plan update following July 23, 2017, and subsequent plans must be reviewed in accordance with the director's schedule.

. When conducting emergency or disaster after-action reviews, local organizations and joint local organizations must evaluate the effectiveness of communication of life safety information and must inform the emergency management division of the Washington military department of technological challenges which limited communications efforts, along with identifying recommendations and resources needed to address those challenges.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5046-S.SL.pdf?cite=2017%20c%20312%20§%204[2017 c 312 § 4]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1171-S.SL.pdf?cite=1997%20c%2049%20§%204[1997 c 49 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2028[1986 c 266 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%207[1984 c 38 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%209[1974 ex.s. c 171 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c178.pdf?cite=1951%20c%20178%20§%208[1951 c 178 § 8]; ]

== 38.52.073 - Communication plan status report—Life safety information communication report.
. Beginning December 1, 2019, the Washington military department emergency management division must submit a report every five years to the relevant committees of the legislature containing the status of communication plans produced under RCW 38.52.070(3)(a).

. The emergency management division of the Washington military department must provide the legislature an annual report on instances of emergency or disaster in which communication of life safety information was technologically infeasible, as reported to the department pursuant to RCW 38.52.070(4). When potential technology solutions exist, the report must include recommendations and an estimate of resources required to remedy the infeasibility. The first annual report is due December 1, 2019.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5046-S.SL.pdf?cite=2017%20c%20312%20§%205[2017 c 312 § 5]; ]

== 38.52.080 - Outside aid—Rights and liabilities—Claims.
. Whenever the employees of any political subdivision are rendering outside aid pursuant to the authority contained in RCW 38.52.070 such employees shall have the same powers, duties, rights, privileges, and immunities as if they were performing their duties in the political subdivisions in which they are normally employed.

. The political subdivision in which any equipment is used pursuant to this section shall be liable for any loss or damage thereto and shall pay any expense incurred in the operation and maintenance thereof. No claim for such loss, damage, or expense shall be allowed unless, within sixty days after the same is sustained or incurred, an itemized notice of such claim under oath is served by mail or otherwise upon the executive head of such political subdivision where the equipment was used. The term "employee" as used in this section shall mean, and the provisions of this section shall apply with equal effect to, volunteer auxiliary employees, and emergency workers.

. The foregoing rights, privileges, and obligations shall also apply in the event such aid is rendered outside the state, provided that payment or reimbursement in such case shall or may be made by the state or political subdivision receiving such aid pursuant to a reciprocal mutual aid agreement or compact with such state or by the federal government.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%208[1984 c 38 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2010[1974 ex.s. c 171 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c178.pdf?cite=1951%20c%20178%20§%209[1951 c 178 § 9]; ]

== 38.52.091 - Mutual aid and interlocal agreements—Requirements.
. The director of each local organization for emergency management may, in collaboration with other public and private agencies within this state, develop or cause to be developed mutual aid arrangements for reciprocal emergency management aid and assistance in case of disaster too great to be dealt with unassisted. Such arrangements must be consistent with the state emergency management plan and program, and in time of emergency it is the duty of each local organization for emergency management to render assistance in accordance with the provisions of such mutual aid arrangements. The adjutant general shall maintain and distribute a mutual aid and interlocal agreement handbook.

. The adjutant general and the director of each local organization for emergency management may, subject to the approval of the governor, enter into mutual aid arrangements with emergency management agencies or organizations in other states for reciprocal emergency management aid and assistance in case of disaster too great to be dealt with unassisted. All such arrangements must contain the language and provisions in subsection (3) of this section.

. Mutual aid and interlocal agreements must include the following:

Purpose

The purpose must state the reason the mutual aid or interlocal agreement or compact is coordinated, the parties to the agreement or compact, and the assistance to be provided.

Authorization

Article I, section 10 of the Constitution of the United States permits a state to enter into an agreement or compact with another state, subject to the consent of Congress. Congress, through enactment of Title 50 U.S.C. Sections 2281(g), 2283 and the Executive Department, by issuance of Executive Orders No. 10186 of December 1, 1950, encourages the states to enter into emergency, disaster and civil defense mutual aid agreements or pacts.

Implementation

The conditions that guide the agreement or compacts may include, but are not limited to:

.. A statement of which authority or authorities are authorized to request and receive assistance and the conditions that must exist for the request or receipt of assistance.

.. A statement of how the requests for assistance may be made, what documentation of the request is required, the specifics of any details included in the request, and the required approval for the request.

.. A statement of the direction and control relationship between the personnel and equipment provided by the jurisdiction to the requester and the requirements of the requester to coordinate the activities of the jurisdiction providing the assets.

.. A statement of the circumstances by which the assisting jurisdiction may withdraw support from the requester and the method by which this is to be communicated.

General Fiscal Provisions

The terms of reimbursement must be stated defining the relationship between the requesting jurisdiction and the aiding jurisdiction, when reimbursement will be made, and details of the claim for reimbursement. The provisions may include statements that discuss but are not limited to:

.. A statement of what costs are incurred by the requesting jurisdiction.

.. A statement of what costs and compensation benefits are made to individuals from the aiding jurisdiction by the requesting jurisdiction.

Privileges and Immunities

The conditions and immunities that are enjoyed by the individuals from the aiding jurisdiction to the requesting jurisdiction must be stated. These provisions may include but are not limited to:

.. A statement of the privileges and immunities from liability and the law an employee of a supporting jurisdiction enjoys while supporting the requesting jurisdiction.

.. A statement of the privileges and immunities from liability and the law a volunteer from a supporting jurisdiction enjoys while supporting the requesting jurisdiction.

.. A statement on the use of the national guard between the requesting and supporting jurisdictions.

.. A hold harmless agreement between the signatory jurisdictions.

.. The precedence this agreement takes with existing agreements.

.. A time line by which information required by the agreement is exchanged and updated annually.

.. The time in which the agreement becomes effective.

.. The time and conditions when a signatory may withdraw and render the agreement ineffective.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1761.SL.pdf?cite=1997%20c%20195%20§%201[1997 c 195 § 1]; ]

== 38.52.100 - Appropriations—Acceptance of funds, services, etc.
. Each political subdivision shall have the power to make appropriations in the manner provided by law for making appropriations for the ordinary expenses of such political subdivision for the payment of expenses of its local organization for emergency management.

. Whenever the federal government or any agency or officer thereof shall offer to the state, or through the state to any political subdivision thereof, services, equipment, supplies, materials, or funds by way of gift, grant, or loan, for purposes of emergency management, the state, acting through the governor, or such political subdivision, acting with the consent of the governor and through its executive head, may accept such offer and upon such acceptance the governor of the state or executive head of such political subdivision may authorize any officer of the state or of the political subdivision, as the case may be, to receive such services, equipment, supplies, materials, or funds on behalf of the state or such political subdivision, and subject to the terms of the offer and the rules and regulations, if any, of the agency making the offer.

. Whenever any person, firm, or corporation shall offer to the state or to any political subdivision thereof, services, equipment, supplies, materials, or funds by way of gift, grant, or loan, for the purposes of emergency management, the state, acting through the governor, or such political subdivision, acting through its executive head, may accept such offer and upon such acceptance the governor of the state or executive head of such political subdivision may authorize any officer of the state or of the political subdivision, as the case may be, to receive such services, equipment, supplies, materials, or funds on behalf of the state or such political subdivision, and subject to the terms of the offer.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2010[1984 c 38 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2012[1974 ex.s. c 171 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c178.pdf?cite=1951%20c%20178%20§%2012[1951 c 178 § 12]; ]

== 38.52.105 - Disaster response account.
The disaster response account is created in the state treasury. Moneys may be placed in the account from legislative appropriations and transfers, federal appropriations, or any other lawful source. Moneys in the account may be spent only after appropriation. Expenditures from the account may be used only for support of state agency and local government disaster response and recovery efforts, including response by state and local government and federally recognized tribes to the novel coronavirus pursuant to the gubernatorial declaration of emergency of February 29, 2020, and to reimburse the workers' compensation funds and self-insured employers under RCW 51.16.220. During the 2017-2019 and 2019-2021 fiscal biennia, expenditures from the disaster response account may be used for military department operations and to support wildland fire suppression preparedness, prevention, and restoration activities by state agencies and local governments. During the 2017-2019 and 2019-2021 fiscal biennia, the legislature may direct the treasurer to make transfers of moneys in the disaster response account to the state general fund. It is the intent of the legislature that these policies will be continued in subsequent fiscal biennia.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2965.SL.pdf?cite=2020%20c%207%20§%206[2020 c 7 § 6]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1109-S.SL.pdf?cite=2019%20c%20415%20§%20956[2019 c 415 § 956]; http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5883-S.SL.pdf?cite=2017%203rd%20sp.s.%20c%201%20§%20962[2017 3rd sp.s. c 1 § 962]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/2376-S.SL.pdf?cite=2016%20sp.s.%20c%2036%20§%20918[2016 sp.s. c 36 § 918]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/3225.SL.pdf?cite=2010%202nd%20sp.s.%20c%201%20§%20901[2010 2nd sp.s. c 1 § 901]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6444-S.SL.pdf?cite=2010%201st%20sp.s.%20c%2037%20§%20919[2010 1st sp.s. c 37 § 919]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6014-S.SL.pdf?cite=2005%20c%20422%20§%202[2005 c 422 § 2]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6387-S.SL.pdf?cite=2002%20c%20371%20§%20903[2002 c 371 § 903]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/2267.SL.pdf?cite=1997%20c%20251%20§%201[1997 c 251 § 1]; ]

== 38.52.110 - Use of existing services and facilities—Impressment of citizenry—First informer broadcasters.
. In carrying out the provisions of this chapter, the governor and the executive heads of the political subdivisions of the state are directed to utilize the services, equipment, supplies, and facilities of existing departments, offices, and agencies of the state, political subdivisions, and all other municipal corporations thereof including but not limited to districts and quasi municipal corporations organized under the laws of the state of Washington to the maximum extent practicable, and the officers and personnel of all such departments, offices, and agencies are directed to cooperate with and extend such services and facilities to the governor and to the emergency management organizations of the state upon request notwithstanding any other provision of law.

. The governor, the chief executive of counties, cities and towns and the emergency management directors of local political subdivisions appointed in accordance with this chapter, in the event of a disaster, after proclamation by the governor of the existence of such disaster, shall have the power to command the service and equipment of as many citizens as considered necessary in the light of the disaster proclaimed: PROVIDED, That citizens so commandeered shall be entitled during the period of such service to all privileges, benefits and immunities as are provided by this chapter and federal and state emergency management regulations for registered emergency workers.

. A vehicle, fuel, food, water, or other essential materials brought into an area affected by an emergency or disaster by a first informer broadcaster may not be seized or confiscated, except as otherwise authorized by law.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1147.SL.pdf?cite=2019%20c%20207%20§%202[2019 c 207 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2011[1984 c 38 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2013[1974 ex.s. c 171 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c8.pdf?cite=1971%20ex.s.%20c%208%20§%201[1971 ex.s. c 8 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1955c210.pdf?cite=1955%20c%20210%20§%201[1955 c 210 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c178.pdf?cite=1951%20c%20178%20§%2013[1951 c 178 § 13]; ]

== 38.52.115 - Liability of federal, state, and local agencies, and employees—Facilitation of access of first informer broadcaster.
Federal, state, and local agencies, and their employees, are not liable for any action, or failure to act, when facilitating access of a first informer broadcaster to an area affected by an emergency or disaster.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1147.SL.pdf?cite=2019%20c%20207%20§%203[2019 c 207 § 3]; ]

== 38.52.120 - Political activity prohibited.
No organization for emergency management established under the authority of this chapter shall participate in any form of political activity, nor shall it be employed directly or indirectly for political purposes.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2012[1984 c 38 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2014[1974 ex.s. c 171 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c178.pdf?cite=1951%20c%20178%20§%2014[1951 c 178 § 14]; ]

== 38.52.140 - Status of civil service employee preserved.
Any civil service employee of the state of Washington or of any political subdivision thereof while on leave of absence and on duty with any emergency management agency authorized under the provisions of this chapter shall be preserved in his or her civil service status as to seniority and retirement rights so long as he or she regularly continues to make the usual contributions incident to the retention of such beneficial rights as if he or she were not on leave of absence.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20790[2011 c 336 § 790]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2013[1984 c 38 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2016[1974 ex.s. c 171 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c178.pdf?cite=1951%20c%20178%20§%2016[1951 c 178 § 16]; ]

== 38.52.150 - Orders, rules, regulations—Enforcement—Availability—Penalty.
. It shall be the duty of every organization for emergency management established pursuant to this chapter and of the officers thereof to execute and enforce such orders, rules, and regulations as may be made by the governor under authority of this chapter. Each such organization shall have available for inspection at its office all orders, rules, and regulations made by the governor, or under his or her authority.

. [Empty]
.. Except as provided in (b) of this subsection, every violation of any rule, regulation, or order issued under the authority of this chapter is a misdemeanor.

.. A second offense hereunder the same is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20211[2003 c 53 § 211]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2014[1984 c 38 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2017[1974 ex.s. c 171 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c178.pdf?cite=1951%20c%20178%20§%2018[1951 c 178 § 18]; ]

== 38.52.160 - Matching funds from political subdivision may be required.
The emergency management agency is hereby authorized to require of any political subdivision to which funds are allocated under this chapter for any project, use or activity that such subdivision shall provide matching funds in equal amounts with respect to such project, use or activity.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2015[1984 c 38 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2018[1974 ex.s. c 171 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c178.pdf?cite=1951%20c%20178%20§%2019[1951 c 178 § 19]; ]

== 38.52.170 - Plan for federal area.
Whenever the director finds that it will be in the interest of the emergency management of this state or of the United States, the director may, with the approval of the governor, agree with the federal government, or any agency thereof carrying on activities within this state, upon a plan of emergency management applicable to a federally owned area, which plan may or may not conform to all of the other provisions of this chapter with the view to integrating federally owned areas into the comprehensive plan and program of the emergency management of this state. Such plan may confer upon persons carrying out such plan any or all of the rights, powers, privileges and immunities granted employees or representatives of the state and/or its political subdivisions by this chapter. The plan of emergency management authorized under this section may not include preparation for emergency evacuation or relocation of residents in anticipation of nuclear attack.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2030[1986 c 266 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2016[1984 c 38 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2019[1974 ex.s. c 171 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c178.pdf?cite=1951%20c%20178%20§%2020[1951 c 178 § 20]; ]

== 38.52.180 - Liability for property damage, bodily injury, death—Immunity—Assumption by state—Indemnification—Immunity from liability for covered volunteers.
. There shall be no liability on the part of anyone including any person, partnership, corporation, the state of Washington or any political subdivision thereof who owns or maintains any building or premises which have been designated by a local organization for emergency management as a shelter from destructive operations or attacks by enemies of the United States for any injuries sustained by any person while in or upon said building or premises, as a result of the condition of said building or premises or as a result of any act or omission, or in any way arising from the designation of such premises as a shelter, when such person has entered or gone upon or into said building or premises for the purpose of seeking refuge therein during destructive operations or attacks by enemies of the United States or during tests ordered by lawful authority, except for an act of willful negligence by such owner or occupant or his or her servants, agents, or employees.

. All legal liability for damage to property or injury or death to persons (except an emergency worker, regularly enrolled and acting as such), caused by acts done or attempted during or while traveling to or from an emergency or disaster, search and rescue, or training or exercise authorized by the department in preparation for an emergency or disaster or search and rescue, under the color of this chapter in a bona fide attempt to comply therewith, except as provided in subsections (3), (4), and (5) of this section regarding covered volunteer emergency workers, shall be the obligation of the state of Washington. Suits may be instituted and maintained against the state for the enforcement of such liability, or for the indemnification of persons appointed and regularly enrolled as emergency workers while actually engaged in emergency management duties, or as members of any agency of the state or political subdivision thereof engaged in emergency management activity, or their dependents, for damage done to their private property, or for any judgment against them for acts done in good faith in compliance with this chapter: PROVIDED, That the foregoing shall not be construed to result in indemnification in any case of willful misconduct, gross negligence, or bad faith on the part of any agent of emergency management: PROVIDED, That should the United States or any agency thereof, in accordance with any federal statute, rule, or regulation, provide for the payment of damages to property and/or for death or injury as provided for in this section, then and in that event there shall be no liability or obligation whatsoever upon the part of the state of Washington for any such damage, death, or injury for which the United States government assumes liability.

. No act or omission by a covered volunteer emergency worker while engaged in a covered activity shall impose any liability for civil damages resulting from such an act or omission upon:

.. The covered volunteer emergency worker;

.. The supervisor or supervisors of the covered volunteer emergency worker;

.. Any facility or their officers or employees;

.. The employer of the covered volunteer emergency worker;

.. The owner of the property or vehicle where the act or omission may have occurred during the covered activity;

.. Any local organization that registered the covered volunteer emergency worker;

.. The state or any state or local governmental entity; and

.. Any professional or trade association of covered volunteer emergency workers.

. The immunity in subsection (3) of this section applies only when the covered volunteer emergency worker was engaged in a covered activity:

.. Within the scope of his or her assigned duties;

.. Under the direction of a local emergency management organization or the department, or a local law enforcement agency for search and rescue; and

.. The act or omission does not constitute gross negligence or willful or wanton misconduct.

. For purposes of this section:

.. "Covered volunteer emergency worker" means an emergency worker as defined in RCW 38.52.010 who (i) is not receiving or expecting compensation as an emergency worker from the state or local government, or (ii) is not a state or local government employee unless on leave without pay status.

.. "Covered activity" means:

... Providing assistance or transportation authorized by the department during an emergency or disaster or search and rescue as defined in RCW 38.52.010, whether such assistance or transportation is provided at the scene of the emergency or disaster or search and rescue, at an alternative care site, at a hospital, or while in route to or from such sites or between sites; or

... Participating in training or exercise authorized by the department in preparation for an emergency or disaster or search and rescue.

. Any requirement for a license to practice any professional, mechanical, or other skill shall not apply to any authorized emergency worker who shall, in the course of performing his or her duties as such, practice such professional, mechanical, or other skill during an emergency described in this chapter.

. The provisions of this section shall not affect the right of any person to receive benefits to which he or she would otherwise be entitled under this chapter, or under the workers' compensation law, or under any pension or retirement law, nor the right of any such person to receive any benefits or compensation under any act of congress.

. Any act or omission by a covered volunteer emergency worker while engaged in a covered activity using an off-road vehicle, nonhighway vehicle, or wheeled all-terrain vehicle does not impose any liability for civil damages resulting from such an act or omission upon the covered volunteer emergency worker or the worker's sponsoring organization.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5185-S.SL.pdf?cite=2017%20c%2036%20§%201[2017 c 36 § 1]; http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1918.SL.pdf?cite=2016%20c%2084%20§%201[2016 c 84 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20791[2011 c 336 § 791]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1073.SL.pdf?cite=2007%20c%20292%20§%202[2007 c 292 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c185.pdf?cite=1987%20c%20185%20§%207[1987 c 185 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2017[1984 c 38 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2020[1974 ex.s. c 171 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c8.pdf?cite=1971%20ex.s.%20c%208%20§%202[1971 ex.s. c 8 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c145.pdf?cite=1953%20c%20145%20§%201[1953 c 145 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c178.pdf?cite=1951%20c%20178%20§%2011[1951 c 178 § 11]; ]

== 38.52.190 - Compensation for injury or death—Chapter exclusive.
Except as provided in this chapter, an emergency worker and his or her dependents shall have no right to receive compensation from the state, from the agency, from the local organization for emergency management with which he or she is registered, or from the county or city which has empowered the local organization for emergency management to register him or her and direct his or her activities, for an injury or death arising out of and occurring in the course of his or her activities as an emergency worker.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20792[2011 c 336 § 792]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2018[1984 c 38 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2021[1974 ex.s. c 171 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c223.pdf?cite=1953%20c%20223%20§%203[1953 c 223 § 3]; ]

== 38.52.195 - Exemption from liability while providing construction, equipment, or work.
Notwithstanding any other provision of law, no person, firm, corporation, or other entity acting under the direction or control of the proper authority to provide construction, equipment, or work as provided for in RCW 38.52.110, 38.52.180, 38.52.195, 38.52.205, 38.52.207, 38.52.220, and 38.52.390 while complying with or attempting to comply with RCW 38.52.110, 38.52.180, 38.52.195, 38.52.205, 38.52.207, 38.52.220, and 38.52.390 or any rule or regulation promulgated pursuant to the provisions of RCW 38.52.110, 38.52.180, 38.52.195, 38.52.205, 38.52.207, 38.52.220, and 38.52.390 shall be liable for the death of or any injury to persons or damage to property as a result of any such activity: PROVIDED, That said exemption shall only apply where all of the following conditions occur:

. Where, at the time of the incident the worker is performing services as an emergency worker, and is acting within the course of his or her duties as an emergency worker;

. Where, at the time of the injury, loss, or damage, the organization for emergency management which the worker is assisting is an approved organization for emergency management;

. Where the injury, loss, or damage is proximately caused by his or her service either with or without negligence as an emergency worker;

. Where the injury, loss, or damage is not caused by the intoxication of the worker; and

. Where the injury, loss, or damage is not due to willful misconduct or gross negligence on the part of a worker.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20793[2011 c 336 § 793]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2019[1984 c 38 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2022[1974 ex.s. c 171 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c8.pdf?cite=1971%20ex.s.%20c%208%20§%207[1971 ex.s. c 8 § 7]; ]

== 38.52.1951 - Application of exemption from liability for architects and engineers.
For purposes of the liability of an architect or engineer serving as a volunteer emergency worker, the exemption from liability provided under RCW 38.52.195 extends to all damages, so long as the conditions specified in RCW 38.52.195 (1) through (5) occur.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5768.SL.pdf?cite=1993%20c%20206%20§%202[1993 c 206 § 2]; ]

== 38.52.198 - Emergency care, rescue, assistance, or recovery services in mine rescue or recovery work—Immunity from liability.
No person engaged in mine rescue or recovery work who, in good faith, renders emergency care, rescue, assistance, or recovery services at the scene of any emergency at or in a mine in this state or who employs, sponsors, or represents any person rendering emergency care, rescue, assistance, or recovery services shall be liable for any civil damages as a result of any act or omission by any person in rendering emergency care, rescue, assistance, or recovery service.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c459.pdf?cite=1985%20c%20459%20§%209[1985 c 459 § 9]; ]

== 38.52.200 - Liability for compensation is in lieu of other liability—Exception.
Liability for the compensation provided by this chapter, as limited by the provisions thereof, is in lieu of any other liability whatsoever to an emergency worker or his or her dependents or any other person on the part of the state, the agency, the local organization for emergency management with which the emergency worker is registered, and the county or city which has empowered the local organization for emergency management to register him or her and direct his or her activities, for injury or death arising out of and in the course of his or her activities while on duty as an emergency worker: PROVIDED, That nothing in this chapter shall limit or bar the liability of the state or its political subdivisions engaged in proprietary functions as distinguished from governmental functions that may exist by reason of injury or death sustained by an emergency worker.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20794[2011 c 336 § 794]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2020[1984 c 38 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2023[1974 ex.s. c 171 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c223.pdf?cite=1953%20c%20223%20§%209[1953 c 223 § 9]; ]

== 38.52.205 - Claims arising from emergency management related activities—Filing—Contents.
All claims against the state for property damages or indemnification therefor arising from emergency management related activities will be presented to and filed with the director of financial management. Contents of all such claims shall conform to the tort claim filing requirements found in RCW 4.92.100 as now or hereafter amended.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2021[1984 c 38 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c151.pdf?cite=1979%20c%20151%20§%2043[1979 c 151 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c144.pdf?cite=1977%20ex.s.%20c%20144%20§%206[1977 ex.s. c 144 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2024[1974 ex.s. c 171 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c8.pdf?cite=1971%20ex.s.%20c%208%20§%204[1971 ex.s. c 8 § 4]; ]

== 38.52.207 - Claims arising from emergency management related activities—Filing—Consideration, adjustment, settlement, etc., by director—Effect.
The director, with the approval of the attorney general, may consider, ascertain, adjust, determine, compromise and settle property loss or damage claims arising out of conduct or circumstances for which the state of Washington would be liable in law for money damages of two thousand dollars or less. The acceptance by the claimant of any such award, compromise, or settlement shall be final and conclusive on the claimant; and upon the state of Washington, unless procured by fraud, and shall constitute a complete release of any claim against the state of Washington. A request for administrative settlement shall not preclude a claimant from filing court action pending administrative determination, or limit the amount recoverable in such a suit, or constitute an admission against interest of either the claimant or the state.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2031[1986 c 266 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2022[1984 c 38 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2025[1974 ex.s. c 171 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c8.pdf?cite=1971%20ex.s.%20c%208%20§%205[1971 ex.s. c 8 § 5]; ]

== 38.52.210 - Compensation boards—Established.
. In each local organization for emergency management established by the legislative authority of the county in accordance with the provisions of RCW 38.52.070, there is hereby created and established a compensation board for the processing of claims as provided in this chapter. The compensation board shall be composed of: (a) The county executive if the county has an elected county executive or, if it does not, one member of the county legislative authority selected by the authority. The executive or the member will serve as the chair of the compensation board; (b) the county director of emergency services; (c) the prosecuting attorney; (d) the emergency services coordinator for medical and health services; and (e) the county auditor who will serve as secretary of the compensation board.

. In each local organization for emergency management established by cities and towns in accordance with RCW 38.52.070, there is hereby created and established a compensation board for the processing of claims as provided in this chapter. The compensation board shall be composed of the mayor; the city director of emergency management; one councilmember or commissioner selected by the council or the commission; the city attorney or corporation counsel; and the local coordinator of medical and health services. The councilmember or commissioner so selected shall serve as the chair of the compensation board and the city director of emergency management shall serve as secretary of the board.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2032[1986 c 266 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2023[1984 c 38 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c213.pdf?cite=1981%20c%20213%20§%206[1981 c 213 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2026[1974 ex.s. c 171 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c223.pdf?cite=1953%20c%20223%20§%204[1953 c 223 § 4]; ]

== 38.52.220 - Compensation boards—Meetings—Claims not necessitating board meeting.
Said compensation board shall meet on the call of its chair on a regular monthly meeting day when there is business to come before it. The chair shall be required to call a meeting on any monthly meeting day when any claim for compensation under this chapter has been submitted to the board: PROVIDED, That as to claims involving amounts of two thousand dollars or less, the local organization director shall submit recommendations directly to the state without convening a compensation board.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20795[2011 c 336 § 795]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2024[1984 c 38 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c8.pdf?cite=1971%20ex.s.%20c%208%20§%203[1971 ex.s. c 8 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c223.pdf?cite=1953%20c%20223%20§%205[1953 c 223 § 5]; ]

== 38.52.230 - Compensation boards—Attendance of witnesses, oaths, rules—Members uncompensated.
The compensation board, in addition to other powers herein granted, shall have the power to compel the attendance of witnesses to testify before it on all matters connected with the operation of this chapter and its chair or any member of said board may administer oath to such witnesses; to make all necessary rules and regulations for its guidance in conformity with the provisions of this chapter: PROVIDED, HOWEVER, That no compensation or emoluments shall be paid to any member of said board for any duties performed as a member of said compensation board.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20796[2011 c 336 § 796]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c223.pdf?cite=1953%20c%20223%20§%206[1953 c 223 § 6]; ]

== 38.52.240 - Compensation boards—Duties as to compensation applications.
The compensation board shall hear and decide all applications for compensation under this chapter. The board shall submit its recommendations to the director on such forms as he or she may prescribe. In case the decision of the director is different from the recommendation of the compensation board, the matter shall be submitted to the state emergency management council for action.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2033[1986 c 266 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2025[1984 c 38 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2027[1974 ex.s. c 171 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c223.pdf?cite=1953%20c%20223%20§%207[1953 c 223 § 7]; ]

== 38.52.250 - Compensation boards—Quorum—Transmittal of minutes, claims—Appeal to department.
A majority of the compensation board shall constitute a quorum, and no business shall be transacted when a majority is not present, and no claim shall be allowed when a majority of the board has not voted favorably thereon.

The board shall send a copy of the minutes of all meetings to the department with copies of all material pertaining to each claim submitted and noting the action of the board on each claim. Appeals may be made by the emergency worker from any action by the board within one year by writing to the department.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2034[1986 c 266 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2026[1984 c 38 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2028[1974 ex.s. c 171 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c223.pdf?cite=1953%20c%20223%20§%208[1953 c 223 § 8]; ]

== 38.52.260 - When compensation furnished.
Compensation shall be furnished to an emergency worker either within or without the state for any injury arising out of and occurring in the course of his or her activities as an emergency worker, and for the death of any such worker if the injury proximately causes death, in those cases where the following conditions occur:

. Where, at the time of the injury the emergency worker is performing services as an emergency worker, and is acting within the course of his or her duties as an emergency worker.

. Where, at the time of the injury the local organization for emergency management with which the emergency worker is registered is an approved local organization for emergency management.

. Where the injury is proximately caused by his or her service as an emergency worker, either with or without negligence.

. Where the injury is not caused by the intoxication of the injured emergency worker.

. Where the injury is not intentionally self-inflicted.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20797[2011 c 336 § 797]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2027[1984 c 38 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2029[1974 ex.s. c 171 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c223.pdf?cite=1953%20c%20223%20§%2010[1953 c 223 § 10]; ]

== 38.52.270 - Minors entitled to benefits.
Emergency workers who are minors shall have the same rights as adults for the purpose of receiving benefits under the provisions of this chapter, but this provision shall not prevent the requirements that a guardian be appointed to receive and administer such benefits until the majority of such minor. Work as an emergency worker shall not be deemed as employment or in violation of any of the provisions of chapter 49.12 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2028[1984 c 38 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2030[1974 ex.s. c 171 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c223.pdf?cite=1953%20c%20223%20§%2011[1953 c 223 § 11]; ]

== 38.52.280 - Compensation and benefits limited by appropriation.
No compensation or benefits shall be paid or furnished to emergency workers or their dependents pursuant to the provisions of this chapter except from money appropriated for the purpose of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2029[1984 c 38 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2031[1974 ex.s. c 171 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c223.pdf?cite=1953%20c%20223%20§%2012[1953 c 223 § 12]; ]

== 38.52.290 - Applicability of workers' compensation law.
Insofar as not inconsistent with the provisions of this chapter, the maximum amount payable to a claimant shall be not greater than the amount allowable for similar disability under the workers' compensation act, chapter 51.32 RCW as amended by chapter 289, Laws of 1971 ex.sess., and any amendments thereto. "Employee" as used in said title shall include an emergency worker when liability for the furnishing of compensation and benefits exists pursuant to the provisions of this chapter and as limited by the provisions of this chapter. Where liability for compensation and benefits exists, such compensation and benefits shall be provided in accordance with the applicable provisions of said sections of chapter 51.32 RCW and at the maximum rate provided therein, subject, however, to the limitations set forth in this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c185.pdf?cite=1987%20c%20185%20§%208[1987 c 185 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2030[1984 c 38 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2032[1974 ex.s. c 171 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c289.pdf?cite=1971%20ex.s.%20c%20289%20§%2071[1971 ex.s. c 289 § 71]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c223.pdf?cite=1953%20c%20223%20§%2013[1953 c 223 § 13]; ]

== 38.52.300 - Right of action against third party.
If the injury to an emergency worker is due to the negligence or wrong of another not on emergency duty, the injured worker, or if death results from the injury, the surviving spouse, children, parents or dependents, as the case may be, shall elect whether to take under this chapter or seek a remedy against such other, such election to be in advance of any suit under this chapter; and if the surviving spouse takes under this chapter, the cause of action against such other shall be assigned to the department; if the other choice is made, the compensation under this chapter shall be only the deficiency, if any, between the amount of recovery against such third person actually collected, and the compensation provided or estimated for such case under authority of this chapter: PROVIDED, That the department shall prosecute all claims assigned to it and do any and all things necessary to recover on behalf of the state any and all amounts which an employer or insurance carrier might recover under the provisions of the law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2035[1986 c 266 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2031[1984 c 38 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c154.pdf?cite=1973%201st%20ex.s.%20c%20154%20§%2059[1973 1st ex.s. c 154 § 59]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c223.pdf?cite=1953%20c%20223%20§%2014[1953 c 223 § 14]; ]

== 38.52.310 - Coverage, classification, registration, of workers.
The department shall establish by rule and regulation various classes of emergency workers, the scope of the duties of each class, and the conditions under which said workers shall be deemed to be on duty and covered by the provisions of this chapter. The department shall also adopt rules and regulations prescribing the manner in which emergency workers of each class are to be registered.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2036[1986 c 266 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2032[1984 c 38 § 32]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2033[1974 ex.s. c 171 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c223.pdf?cite=1953%20c%20223%20§%2015[1953 c 223 § 15]; ]

== 38.52.320 - Schedule of payments.
The department shall provide each compensation board with the approved maximum schedule of payments for injury or death prescribed in chapter 51.32 RCW: PROVIDED, That nothing in this chapter shall be construed as establishing any liability on the part of the department of labor and industries.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2037[1986 c 266 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2033[1984 c 38 § 33]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2034[1974 ex.s. c 171 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c223.pdf?cite=1953%20c%20223%20§%2016[1953 c 223 § 16]; ]

== 38.52.330 - Expenditures authorized—Claims, payment and disposition—Appeals.
The department is authorized to make all expenditures necessary and proper to carry out the provisions of this chapter including payments to claimants for compensation as emergency workers and their dependents; to adjust and dispose of all claims submitted by a local compensation board. When medical treatment is necessary, the department is authorized to make medical and compensation payments on an interim basis. Nothing herein shall be construed to mean that the department or the state emergency management council or its officers or agents shall have the final decision with respect to the compensability of any case or the amount of compensation or benefits due, but any emergency worker or his or her dependents shall have the same right of appeal from any order, decision, or award to the same extent as provided in chapter 51.32 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2038[1986 c 266 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2034[1984 c 38 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c268.pdf?cite=1979%20ex.s.%20c%20268%20§%203[1979 ex.s. c 268 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2035[1974 ex.s. c 171 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c289.pdf?cite=1971%20ex.s.%20c%20289%20§%2072[1971 ex.s. c 289 § 72]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c223.pdf?cite=1953%20c%20223%20§%2017[1953 c 223 § 17]; ]

== 38.52.340 - Benefits under other compensation plans.
Nothing in this chapter shall deprive any emergency worker or his or her dependents of any right to compensation for injury or death sustained in the course of his or her regular employment even though his or her regular work is under direction of emergency management authorities: PROVIDED, That such worker, if he or she is eligible for some other compensation plan, and receives the benefits of such plan shall not also receive any compensation under this chapter. The department shall adopt such rules and regulations as may be necessary to protect the rights of such workers and may enter into agreements with authorities in charge of other compensation plans to insure protection of such workers: PROVIDED, That if the compensation from some other plan is less than would have been available under this chapter, he or she shall be entitled to receive the deficiency between the amount received under such other plan and the amount available under this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2039[1986 c 266 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2035[1984 c 38 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2036[1974 ex.s. c 171 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c223.pdf?cite=1953%20c%20223%20§%2018[1953 c 223 § 18]; ]

== 38.52.350 - Benefits furnished under federal law—Reduction of state benefits.
Should the United States or any agent thereof, in accordance with any federal statute or rule or regulation, furnish monetary assistance, benefits, or other temporary or permanent relief to emergency workers or to their dependents for injuries arising out of and occurring in the course of their activities as emergency workers, then the amount of compensation which any emergency worker or his or her dependents are otherwise entitled to receive from the state of Washington as provided herein, shall be reduced by the amount of monetary assistance, benefits, or other temporary or permanent relief the emergency worker or his or her dependents have received and will receive from the United States or any agent thereof as a result of his or her injury.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20798[2011 c 336 § 798]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2036[1984 c 38 § 36]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2037[1974 ex.s. c 171 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c223.pdf?cite=1953%20c%20223%20§%2019[1953 c 223 § 19]; ]

== 38.52.360 - Medical, surgical or hospital treatment.
If, in addition to monetary assistance, benefits or other temporary or permanent relief, the United States or any agent thereof furnishes medical, surgical or hospital treatment or any combination thereof to an injured emergency worker, then the emergency worker has no right to receive similar medical, surgical or hospital treatment as provided in this chapter. However, the department may furnish medical, surgical or hospital treatment as part of the compensation provided under the provisions of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2040[1986 c 266 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2037[1984 c 38 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2038[1974 ex.s. c 171 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c223.pdf?cite=1953%20c%20223%20§%2020[1953 c 223 § 20]; ]

== 38.52.370 - Medical, surgical or hospital treatment—Reimbursement.
If, in addition to monetary assistance, benefits, or other temporary or permanent relief, the United States or any agent thereof, will reimburse an emergency worker or his or her dependents for medical, surgical or hospital treatment, or any combination thereof, furnished to the injured emergency worker, the emergency worker has no right to receive similar medical, surgical or hospital treatment as provided in this chapter, but the department, may furnish a medical, surgical or hospital treatment as part of the compensation provided under the provisions of this chapter and apply to the United States or its agent for the reimbursement which will be made to the emergency worker or his or her dependents. As a condition to the furnishing of such medical, surgical or hospital treatment, the department shall require the emergency worker and his dependents to assign to the state of Washington, for the purpose of reimbursing for any medical, surgical or hospital treatment furnished or to be furnished by the state, any claim or right such emergency worker or his or her dependents may have to reimbursement from the United States or any agent thereof.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2041[1986 c 266 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2038[1984 c 38 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2039[1974 ex.s. c 171 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c223.pdf?cite=1953%20c%20223%20§%2021[1953 c 223 § 21]; ]

== 38.52.380 - State compensation denied if payment prevents federal benefits.
If the furnishing of compensation under the provisions of this chapter to an emergency worker or his or her dependents prevents such emergency worker or his or her dependents from receiving assistance, benefits, or other temporary or permanent relief under the provisions of a federal statute or rule or regulation, then the emergency worker and his or her dependents shall have no right to, and shall not receive, any compensation from the state of Washington under the provisions of this chapter for any injury for which the United States or any agent thereof will furnish assistance, benefits, or other temporary or permanent relief in the absence of the furnishing of compensation by the state of Washington.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20799[2011 c 336 § 799]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2039[1984 c 38 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2040[1974 ex.s. c 171 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c223.pdf?cite=1953%20c%20223%20§%2022[1953 c 223 § 22]; ]

== 38.52.390 - Contracts or work on cost basis for emergency management activities.
The governor, or upon his or her direction, the director, or any political subdivision of the state, is authorized to contract with any person, firm, corporation, or entity to provide construction or work on a cost basis to be used in emergency management functions or activities as defined in *RCW 38.52.010(1) or as hereafter amended, said functions or activities to expressly include natural disasters, as well as all other emergencies of a type contemplated by RCW 38.52.110, 38.52.180, 38.52.195, 38.52.205, 38.52.207, 38.52.220 and 38.52.390. All funds received for purposes of RCW 38.52.110, 38.52.180, 38.52.195, 38.52.205, 38.52.207, 38.52.220 and 38.52.390, whether appropriated funds, local funds, or from whatever source, may be used to pay for the construction, equipment, or work contracted for under this section.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2042[1986 c 266 § 42]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2040[1984 c 38 § 40]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1971ex1c8.pdf?cite=1971%20ex.s.%20c%208%20§%206[1971 ex.s. c 8 § 6]; ]

== 38.52.400 - Search and rescue activities—Powers and duties of local officials.
. The chief law enforcement officer of each political subdivision shall be responsible for local search and rescue activities. Operation of search and rescue activities shall be in accordance with state and local operations plans adopted by the elected governing body of each local political subdivision. These state and local plans must specify the use of the incident command system for multiagency/multijurisdiction search and rescue operations. The local emergency management director shall notify the department of all search and rescue missions. The local director of emergency management shall work in a coordinating capacity directly supporting all search and rescue activities in that political subdivision and in registering emergency search and rescue workers for employee status. The chief law enforcement officer of each political subdivision may restrict access to a specific search and rescue area to personnel authorized by him or her. Access shall be restricted only for the period of time necessary to accomplish the search and rescue mission. No unauthorized person shall interfere with a search and rescue mission.

. When search and rescue activities result in the discovery of a deceased person or search and rescue workers assist in the recovery of human remains, the chief law enforcement officer of the political subdivision shall insure compliance with chapter 68.50 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20800[2011 c 336 § 800]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1171-S.SL.pdf?cite=1997%20c%2049%20§%205[1997 c 49 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2043[1986 c 266 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2041[1984 c 38 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c268.pdf?cite=1979%20ex.s.%20c%20268%20§%204[1979 ex.s. c 268 § 4]; ]

== 38.52.410 - Search and rescue activities—Distribution of funds for compensation and reimbursement of volunteers.
Funds received by the department specifically for the purposes of compensating search and rescue volunteers shall be distributed by the director to help fund medical and compensation coverage provided by this chapter and provide reimbursement by the state for: (1) Costs involved in extraordinary search and rescue operations such as search and rescue operations lasting over twenty-four hours where food and lodging for workers is necessary; (2) excessive transportation and rescue costs incurred by out-of-county residents which would not be otherwise collectible; and (3) compensation as provided in RCW 38.52.020(1)(d) as now or hereafter amended.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c266.pdf?cite=1986%20c%20266%20§%2044[1986 c 266 § 44]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2042[1984 c 38 § 42]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979ex1c268.pdf?cite=1979%20ex.s.%20c%20268%20§%205[1979 ex.s. c 268 § 5]; ]

== 38.52.420 - Model contingency plan for pollution control facilities and hazardous waste management.
. The department, in consultation with appropriate federal agencies, the departments of natural resources, fish and wildlife, and ecology, representatives of local government, and any other person the director may deem appropriate, shall assist in the development of a model contingency plan, consistent with other plans required for hazardous materials by federal and state law, to serve as a draft plan for local governments which may be incorporated into the state and local emergency management plans.

. The model contingency plan shall:

.. Include specific recommendations for pollution control facilities which are deemed to be most appropriate for the control, collection, storage, treatment, disposal, and recycling of oil and other spilled material and furthering the prevention and mitigation of such pollution;

.. Include recommendations for the training of local personnel consistent with other training proposed, funded, or required by federal or state laws for hazardous materials;

.. Suggest cooperative training exercises between the public and private sector consistent with other training proposed, funded, or required by federal or state laws for hazardous materials;

.. Identify federal and state laws requiring contingency or management plans applicable or related to prevention of pollution, emergency response capabilities, and hazardous waste management, together with a list of funding sources that local governments may use in development of their specific plans;

.. Promote formal agreements between the department and local entities for effective spill response; and

.. Develop policies and procedures for the augmentation of emergency services and agency spill response personnel through the use of volunteers: PROVIDED, That no contingency plan may require the use of volunteers by a responding responsible party without that party's consent.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1171-S.SL.pdf?cite=1997%20c%2049%20§%206[1997 c 49 § 6]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1017-S.SL.pdf?cite=1995%20c%20391%20§%204[1995 c 391 § 4]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2590.SL.pdf?cite=1994%20c%20264%20§%2011[1994 c 264 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1988c36.pdf?cite=1988%20c%2036%20§%2011[1988 c 36 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c479.pdf?cite=1987%20c%20479%20§%203[1987 c 479 § 3]; ]

== 38.52.430 - Emergency response caused by person's intoxication—Recovery of costs from convicted person.
A person whose intoxication causes an incident resulting in an appropriate emergency response, and who, in connection with the incident, has been found guilty of or has had their prosecution deferred for (1) driving while under the influence of intoxicating liquor or any drug, RCW 46.61.502; (2) physical control of a motor vehicle while under the influence of intoxicating liquor or any drug, RCW 46.61.504; (3) operating an aircraft under the influence of intoxicants or drugs, RCW 47.68.220; (4) use of a vessel while under the influence of alcohol or drugs, RCW 79A.60.040; (5) vehicular homicide while under the influence of intoxicating liquor or any drug, RCW 46.61.520(1)(a); or (6) vehicular assault while under the influence of intoxicating liquor or any drug, RCW 46.61.522(1)(b), is liable for the expense of an emergency response by a public agency to the incident.

The expense of an emergency response is a charge against the person liable for expenses under this section. The charge constitutes a debt of that person and is collectible by the public agency incurring those costs in the same manner as in the case of an obligation under a contract, expressed or implied. Following a conviction of an offense listed in this section, and prior to sentencing, the prosecution may present to the court information setting forth the expenses incurred by the public agency for its emergency response to the incident. Upon a finding by the court that the expenses are reasonable, the court shall order the defendant to reimburse the public agency. The cost reimbursement shall be included in the sentencing order as an additional monetary obligation of the defendant and may not be substituted for any other fine or cost required or allowed by statute. The court may establish a payment schedule for the payment of the cost reimbursement, separate from any payment schedule imposed for other fines and costs. All payments for the cost reimbursement must be remitted directly to the public agency or agencies that incurred the cost associated with the emergency response.

In no event shall a person's liability under this section for the expense of an emergency response exceed two thousand five hundred dollars for a particular incident.

If more than one public agency makes a claim for payment from an individual for an emergency response to a single incident under the provisions of this section, and the sum of the claims exceeds the amount recovered, the division of the amount recovered shall be determined by an interlocal agreement consistent with the requirements of chapter 39.34 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1504-S3.SL.pdf?cite=2020%20c%20330%20§%204[2020 c 330 § 4]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2443-S2.SL.pdf?cite=2012%20c%20183%20§%206[2012 c 183 § 6]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1051-S.SL.pdf?cite=1993%20c%20251%20§%202[1993 c 251 § 2]; ]

== 38.52.440 - Assistance for persons with disabilities present at scene of emergency—Assessment and report—Definitions.
. Subject to the availability of amounts appropriated for this specific purpose, the director, through the state enhanced 911 coordinator, and in collaboration with the department of health, the department of social and health services, the Washington state patrol, the Washington association of sheriffs and police chiefs, the Washington council of police and sheriffs, the state fire marshal's office, a representative of a first responder organization with experience in addressing the needs of a person with a disability, and other individuals and entities at the discretion of the director, must assess, and report back to the appropriate committees of the legislature by December 1, 2018, regarding:

.. The resources, capabilities, techniques, protocols, and procedures available or required in order to include as part of the enhanced 911 emergency service the ability to allow an immediate display on the screen indicating that a person with a disability may be present at the scene of an emergency, the caller's identification, location, phone number, address, and if made available, additional information on the person with a disability that would assist the first responder in the emergency response;

.. How best to acquire, implement, and safeguard a secure web site and the information in the system provided by a person with a disability, or a parent, guardian, or caretaker of a person with a disability in order to make such information directly available to first responders at the scene of an emergency or on the way to the scene of an emergency;

.. What information provided by a person must remain confidential under state or federal law, or otherwise should remain confidential without written permission to release it for purposes of chapter 295, Laws of 2017 or the information is otherwise releasable or available under other provisions of law; and

.. The need to provide various agencies and employees that are first responders and emergency personnel immunity from civil liability for acts or omissions in the performance of their duties, and what standard should apply, such as if the act or omission is the result of simple negligence, gross negligence, or willful misconduct.

. For purposes of this section:

.. Both "accident" and "emergency" mean an unforeseen combination of circumstances or a resulting situation that results in a need for assistance or relief and calls for immediate action; and 

.. "Person with a disability" means an individual who has been diagnosed medically to have a physical, mental, emotional, intellectual, behavioral, developmental, or sensory disability.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1258-S.SL.pdf?cite=2017%20c%20295%20§%203[2017 c 295 § 3]; ]

== 38.52.500 - Statewide enhanced 911 service—Finding.
The legislature finds that a statewide emergency communications network of enhanced 911 telephone service, which allows an immediate display of a caller's identification and location, would serve to further the safety, health, and welfare of the state's citizens, and would save lives. The legislature, after reviewing the study outlined in section 1, chapter 260, Laws of 1990, further finds that statewide implementation of enhanced 911 telephone service is feasible and should be accomplished as soon as practicable.

[ ?cite=1991%20c%2054%20§%201[1991 c 54 § 1]; ]

== 38.52.501 - Statewide enhanced 911 service—Findings.
The legislature finds that statewide enhanced 911 has proven to be a lifesaving service and that routing a 911 call to the appropriate public safety answering point with a display of the caller's identification and location should be available for all users of telecommunications services, regardless of the technology used to make and transmit the 911 call. The legislature also finds that it is in the best public interest to ensure that there is adequate ongoing funding to support enhanced 911 service.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2595.SL.pdf?cite=2002%20c%20341%20§%201[2002 c 341 § 1]; ]

== 38.52.505 - Statewide enhanced 911 service—Automatic location identification—Rules.
The adjutant general shall establish rules on minimum information requirements of automatic location identification for the purposes of enhanced 911 emergency service. Such rules shall permit the chief of a local fire department or a chief fire protection officer or such other person as may be designated by the governing body of a city or county to take into consideration local circumstances when approving the accuracy of location information generated when calls are made to 911 from facilities within his or her service area.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5806.SL.pdf?cite=1999%20c%2024%20§%202[1999 c 24 § 2]; ]

== 38.52.510 - Statewide enhanced 911 service—Funding by counties.
Each county, singly or in combination with one or more adjacent counties, must implement countywide or multicounty-wide enhanced 911 emergency communications systems so that enhanced 911 is available throughout the state. The county must provide funding for the enhanced 911 communications system in the county in an amount equal to the amount the maximum tax under RCW 82.14B.030(1) would generate in the county less any applicable administrative fee charged by the department of revenue or the amount necessary to provide full funding of the system in the county. The state enhanced 911 coordination office established by RCW 38.52.520 must assist and facilitate enhanced 911 implementation throughout the state.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6846-S.SL.pdf?cite=2010%201st%20sp.s.%20c%2019%20§%2014[2010 1st sp.s. c 19 § 14]; ?cite=1991%20c%2054%20§%203[1991 c 54 § 3]; ]

== 38.52.520 - State enhanced 911 coordination office.
A state enhanced 911 coordination office, headed by the state enhanced 911 coordinator, is established in the emergency management division of the department. Duties of the office include:

. Coordinating and facilitating the implementation and operation of enhanced 911 emergency communications systems throughout the state;

. Seeking advice and assistance from, and providing staff support for, the enhanced 911 advisory committee; 

. Recommending to the utilities and transportation commission by August 31st of each year the level of the state enhanced 911 excise tax for the following year;

. Considering base needs of individual counties for specific assistance, specify rules defining the purposes for which available state enhanced 911 funding may be expended, with the advice and assistance of the enhanced 911 advisory committee; and

. Providing an annual update to the enhanced 911 advisory committee on how much money each county has spent on:

.. Efforts to modernize their existing enhanced 911 emergency communications system; and

.. Enhanced 911 operational costs.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6846-S.SL.pdf?cite=2010%201st%20sp.s.%20c%2019%20§%2015[2010 1st sp.s. c 19 § 15]; ?cite=1991%20c%2054%20§%204[1991 c 54 § 4]; ]

== 38.52.525 - State enhanced 911 coordination office—Public education materials.
The state enhanced 911 coordination office may develop and implement public education materials regarding the capability of specific equipment used as part of a private telecommunications system or in the provision of private shared telecommunications services to forward automatic location identification and automatic number identification.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5089-S.SL.pdf?cite=1995%20c%20243%20§%209[1995 c 243 § 9]; ]

== 38.52.530 - Enhanced 911 advisory committee (as amended by 2010 1st sp.s. c 7). (Expires December 31, 2011.)
The enhanced 911 advisory committee is created to advise and assist the state enhanced 911 coordinator in coordinating and facilitating the implementation and operation of enhanced 911 throughout the state. The director shall appoint members of the committee who represent diverse geographical areas of the state and include state residents who are members of the national emergency number association, the associated public communications officers Washington chapter, the Washington state fire chiefs association, the Washington association of sheriffs and police chiefs, the Washington state council of firefighters, the Washington state council of police officers, the Washington ambulance association, ((the state fire protection policy board,)) the Washington state firefighters association, the Washington state association of fire marshals, the Washington fire commissioners association, the Washington state patrol, the association of Washington cities, the Washington state association of counties, the utilities and transportation commission or commission staff, a representative of a voice over internet protocol company, and an equal number of representatives of large and small local exchange telephone companies and large and small radio communications service companies offering commercial mobile radio service in the state. This section expires December 31, 2011.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2617-S2.SL.pdf?cite=2010%201st%20sp.s.%20c%207%20§%2051[2010 1st sp.s. c 7 § 51]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2543-S.SL.pdf?cite=2006%20c%20210%20§%201[2006 c 210 § 1]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2595.SL.pdf?cite=2002%20c%20341%20§%203[2002 c 341 § 3]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/6378.SL.pdf?cite=2000%20c%2034%20§%201[2000 c 34 § 1]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1171-S.SL.pdf?cite=1997%20c%2049%20§%207[1997 c 49 § 7]; ?cite=1991%20c%2054%20§%205[1991 c 54 § 5]; ]

== 38.52.532 - Enhanced 911 advisory committee—Annual legislative update.
On an annual basis, the enhanced 911 advisory committee must provide an update on the status of enhanced 911 service in the state to the appropriate committees in the legislature. The update must include progress by counties towards creating greater efficiencies in enhanced 911 operations including, but not limited to, regionalization of facilities, centralization of equipment, and statewide purchasing.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6846-S.SL.pdf?cite=2010%201st%20sp.s.%20c%2019%20§%2017[2010 1st sp.s. c 19 § 17]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2543-S.SL.pdf?cite=2006%20c%20210%20§%202[2006 c 210 § 2]; ]

== 38.52.535 - State enhanced 911 coordination office and advisory committee—Uniform national standards.
The state enhanced 911 coordination office and the enhanced 911 advisory committee may participate in efforts to set uniform national standards for automatic number identification and automatic location identification data transmission for private telecommunications systems and private shared telecommunications services.

[ http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/6219.SL.pdf?cite=1998%20c%20245%20§%2032[1998 c 245 § 32]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5089-S.SL.pdf?cite=1995%20c%20243%20§%2010[1995 c 243 § 10]; ]

== 38.52.540 - Enhanced 911 account.
. The enhanced 911 account is created in the state treasury. All receipts from the state enhanced 911 excise taxes imposed by RCW 82.14B.030 must be deposited into the account. Moneys in the account must be used only to support the statewide coordination and management of the enhanced 911 system, for the implementation of wireless enhanced 911 statewide, for the modernization of enhanced 911 emergency communications systems statewide, and to help supplement, within available funds, the operational costs of the system, including adequate funding of counties to enable implementation of wireless enhanced 911 service and reimbursement of radio communications service companies for costs incurred in providing wireless enhanced 911 service pursuant to negotiated contracts between the counties or their agents and the radio communications service companies. For the 2013-2015 and the 2015-2017 fiscal biennia, the account may be used for a criminal history system upgrade in the Washington state patrol and for activities and programs in the military department. A county must show just cause, including but not limited to a true and accurate accounting of the funds expended, for any inability to provide reimbursement to radio communications service companies of costs incurred in providing enhanced 911 service.

. Funds generated by the enhanced 911 excise tax imposed by RCW 82.14B.030(5) may not be distributed to any county that has not imposed the maximum county enhanced 911 excise tax allowed under RCW 82.14B.030(1). Funds generated by the enhanced 911 excise tax imposed by RCW 82.14B.030(6) may not be distributed to any county that has not imposed the maximum county enhanced 911 excise tax allowed under RCW 82.14B.030(2).

. The state enhanced 911 coordinator, with the advice and assistance of the enhanced 911 advisory committee, is authorized to enter into statewide agreements to improve the efficiency of enhanced 911 services for all counties and shall specify by rule the additional purposes for which moneys, if available, may be expended from this account.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6052-S.SL.pdf?cite=2015%203rd%20sp.s.%20c%204%20§%20949[2015 3rd sp.s. c 4 § 949]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5034-S.SL.pdf?cite=2013%202nd%20sp.s.%20c%204%20§%20966[2013 2nd sp.s. c 4 § 966]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2127-S.SL.pdf?cite=2012%202nd%20sp.s.%20c%207%20§%20915[2012 2nd sp.s. c 7 § 915]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6846-S.SL.pdf?cite=2010%201st%20sp.s.%20c%2019%20§%2018[2010 1st sp.s. c 19 § 18]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/6387-S.SL.pdf?cite=2002%20c%20371%20§%20905[2002 c 371 § 905]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2595.SL.pdf?cite=2002%20c%20341%20§%204[2002 c 341 § 4]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5335-S.SL.pdf?cite=2001%20c%20128%20§%202[2001 c 128 § 2]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/House/1126-S.SL.pdf?cite=1998%20c%20304%20§%2014[1998 c 304 § 14]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/2601.SL.pdf?cite=1994%20c%2096%20§%207[1994 c 96 § 7]; ?cite=1991%20c%2054%20§%206[1991 c 54 § 6]; ]

== 38.52.545 - Priorities for enhanced 911 funding.
In specifying rules defining the purposes for which available state enhanced 911 moneys may be expended, the state enhanced 911 coordinator, with the advice and assistance of the enhanced 911 advisory committee, must consider base needs of individual counties for specific assistance. Priorities for available enhanced 911 funding are as follows:

. To assure that 911 dialing is operational statewide;

. To assist counties as necessary to assure that they can achieve a basic service level for 911 operations; and

. To assist counties as practicable to acquire items of a capital nature appropriate to modernize 911 systems and increase 911 effectiveness.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6846-S.SL.pdf?cite=2010%201st%20sp.s.%20c%2019%20§%2019[2010 1st sp.s. c 19 § 19]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/Senate/5335-S.SL.pdf?cite=2001%20c%20128%20§%203[2001 c 128 § 3]; ]

== 38.52.550 - Emergency communications systems and information—Immunity from civil liability.
A telecommunications company, radio communications service company, or interconnected voice over internet protocol service company, providing emergency communications systems or services or a business or individual providing database information to enhanced 911 emergency communications personnel is not liable for civil damages caused by an act or omission of the company, business, or individual in the:

. Good faith release of information not in the public record, including unpublished or unlisted subscriber information to emergency service providers responding to calls placed to an enhanced 911 emergency communications service; or

. Design, development, installation, maintenance, or provision of consolidated enhanced 911 emergency communications systems or services other than an act or omission constituting gross negligence or wanton or willful misconduct.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6846-S.SL.pdf?cite=2010%201st%20sp.s.%20c%2019%20§%2020[2010 1st sp.s. c 19 § 20]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2595.SL.pdf?cite=2002%20c%20341%20§%205[2002 c 341 § 5]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1938-S.SL.pdf?cite=1991%20c%20329%20§%207[1991 c 329 § 7]; ]

== 38.52.561 - 911 calls from radio communications and interconnected voice over internet protocol service companies—Technical and operational standards.
The state enhanced 911 coordinator, with the advice and assistance of the enhanced 911 advisory committee, must set nondiscriminatory, uniform technical and operational standards consistent with the rules of the federal communications commission for the transmission of 911 calls from radio communications service companies and interconnected voice over internet protocol service companies to enhanced 911 emergency communications systems. These standards must not exceed the requirements set by the federal communications commission. The authority given to the state enhanced 911 coordinator in this section is limited to setting standards as set forth in this section and does not constitute authority to regulate radio communications service companies or interconnected voice over internet protocol service companies.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/6846-S.SL.pdf?cite=2010%201st%20sp.s.%20c%2019%20§%2021[2010 1st sp.s. c 19 § 21]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2595.SL.pdf?cite=2002%20c%20341%20§%206[2002 c 341 § 6]; ]

== 38.52.575 - Information in automatic number identification or automatic location identification database that is part of county enhanced 911 emergency communications system—Other information associated with county enhanced 911 emergency communications system—Exemption from public inspection and copying.
. Information contained in an automatic number identification or automatic location identification database that is part of a county enhanced 911 emergency communications system as defined in RCW 82.14B.020 and intended for display at a public safety answering point with incoming 911 voice or data is exempt from public inspection and copying under chapter 42.56 RCW.

. Information voluntarily submitted to be contained in a database that is part of or associated with a county enhanced 911 emergency communications system as defined in RCW 82.14B.020 and intended for the purpose of display at a public safety answering point with incoming 911 voice or data is exempt from public inspection and copying under chapter 42.56 RCW.

. This section shall not be interpreted to prohibit:

.. Display of information at a public safety answering point;

.. Dissemination of information by the public safety answering point to police, fire, or emergency medical responders for display on a device used by police, fire, or emergency medical responders for the purpose of handling or responding to emergency calls or for training;

.. Maintenance of the database by a county;

.. Dissemination of information by a county to local agency personnel for inclusion in an emergency notification system that makes outgoing calls to telephone numbers to provide notification of a community emergency event;

.. Inspection or copying by the subject of the information or an authorized representative; or

.. The public disclosure of information prepared, retained, disseminated, transmitted, or recorded, for the purpose of handling or responding to emergency calls, unless disclosure of any such information is otherwise exempted under chapter 42.56 RCW or other law.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1980-S.SL.pdf?cite=2015%20c%20224%20§%206[2015 c 224 § 6]; ]

== 38.52.577 - Information from automatic number identification, automatic location identification database, or voluntarily submitted for inclusion in emergency notification system—Exemption from public inspection and copying.
Information obtained from an automatic number identification or automatic location identification database or voluntarily submitted to a local agency for inclusion in an emergency notification system is exempt from public inspection and copying under chapter 42.56 RCW. This section shall not be interpreted to prohibit:

. Making outgoing calls to telephone numbers to provide notification of a community emergency event;

. Maintenance of the database by a local agency; or

. Inspection or copying by the subject of the information or an authorized representative.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/House/1980-S.SL.pdf?cite=2015%20c%20224%20§%207[2015 c 224 § 7]; ]

== 38.52.580 - State agency communication plan for emergencies and disasters—Copy to legislature—Report.
Beginning December 1, 2019, a state agency that provides life safety information in an emergency or disaster must provide, to the relevant committees of the legislature, a copy of its current communication plan for notifying significant population segments of such information, including the agency's point of contact. The state agency must also submit an annual report to the relevant committees of the legislature identifying those instances of emergency or disaster in the preceding year in which life safety information was provided and what public messaging strategies and means were used to notify citizens with limited English proficiency.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5046-S.SL.pdf?cite=2017%20c%20312%20§%202[2017 c 312 § 2]; ]

== 38.52.900 - Short title.
This chapter may be cited as the Washington Emergency Management Act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c38.pdf?cite=1984%20c%2038%20§%2043[1984 c 38 § 43]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1974ex1c171.pdf?cite=1974%20ex.s.%20c%20171%20§%2041[1974 ex.s. c 171 § 41]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c178.pdf?cite=1951%20c%20178%20§%201[1951 c 178 § 1]; ]

== 38.52.920 - Repeal and saving.
Chapter 177, Laws of 1941, chapters 6 and 24, Laws of 1943, and chapter 88, Laws of 1949 are repealed: PROVIDED, That this section shall not affect the validity of any order, rule, regulation, contract, or agreement made or promulgated under authority of the repealed acts, which orders, rules, regulations, contracts, or agreements shall remain in force until they may be repealed, amended, or superseded by orders, rules, regulations, contracts, or agreements made or promulgated under this chapter: PROVIDED FURTHER, That this section shall not affect the tenure of any officer, employee, or person serving under authority of any repealed act and such officer, employee, or person shall continue in his or her position until such time as a successor is appointed or employed under the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5045.SL.pdf?cite=2011%20c%20336%20§%20801[2011 c 336 § 801]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1951c178.pdf?cite=1951%20c%20178%20§%2017[1951 c 178 § 17]; ]

== 38.52.930 - Transfer of powers, duties, and functions to state military department.
All powers, duties, and functions of the *department of community, trade, and economic development pertaining to emergency management are transferred to the state military department. All references to the director or the department of community development or the *department of community, trade, and economic development in the Revised Code of Washington shall be construed to mean the adjutant general or the state military department when referring to the functions transferred in this section.

[ http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1017-S.SL.pdf?cite=1995%20c%20391%20§%2010[1995 c 391 § 10]; ]

== 38.52.940 - Construction—Chapter applicable to state registered domestic partnerships—2009 c 521.
For the purposes of this chapter, the terms spouse, marriage, marital, husband, wife, widow, widower, next of kin, and family shall be interpreted as applying equally to state registered domestic partnerships or individuals in state registered domestic partnerships as well as to marital relationships and married persons, and references to dissolution of marriage shall apply equally to state registered domestic partnerships that have been terminated, dissolved, or invalidated, to the extent that such interpretation does not conflict with federal law. Where necessary to implement chapter 521, Laws of 2009, gender-specific terms such as husband and wife used in any statute, rule, or other law shall be construed to be gender neutral, and applicable to individuals in state registered domestic partnerships.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5688-S2.SL.pdf?cite=2009%20c%20521%20§%2084[2009 c 521 § 84]; ]

