= 68.05 - Funeral and cemetery board.
:toc:

== 68.05.010 - Definitions.
The definitions in chapter 68.04 RCW are applicable to this chapter and govern the meaning of terms used in this chapter, except as otherwise provided.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2046[2005 c 365 § 46]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%2026[1953 c 290 § 26]; ]

== 68.05.020 - "Board" defined.
The term "board" used in this chapter means the funeral and cemetery board.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2126-S.SL.pdf?cite=2009%20c%20102%20§%207[2009 c 102 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%2027[1953 c 290 § 27]; ]

== 68.05.024 - "Department" defined.
"Department" used in this chapter means the department of licensing.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%202[1987 c 331 § 2]; ]

== 68.05.028 - "Director" defined.
"Director" used in this chapter means the director of licensing.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%203[1987 c 331 § 3]; ]

== 68.05.030 - "Endowment care," "endowed care" defined.
The terms "endowment care" or "endowed care" used in this chapter shall include special care funds and all funds held for or represented as maintenance funds.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2047[2005 c 365 § 47]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%204[1987 c 331 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%2028[1953 c 290 § 28]; ]

== 68.05.090 - Administration and enforcement of title.
The board shall enforce and administer the provisions of chapters 68.04 through 68.50 RCW, subject to provisions of RCW 68.05.400. The board may adopt and amend bylaws establishing its organization and method of operation. The board may refer such evidence as may be available concerning violations of chapters 68.04 through 68.50 RCW to the attorney general or the proper prosecuting attorney, who may in his or her discretion, with or without such a reference, in addition to any other action the board might commence, bring an action against any person to restrain or prevent the doing of any act or practice prohibited or declared unlawful in chapters 68.04 through 68.50 RCW and shall have standing to seek enforcement of said provisions in the superior court of the state of Washington for the county in which the principal office of the cemetery authority is located.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2051[2005 c 365 § 51]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%207[1987 c 331 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%206[1979 c 21 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%2039[1953 c 290 § 39]; ]

== 68.05.095 - Program administrator or manager.
The director, in consultation with the board, may employ and prescribe the duties of the program administrator or manager. The program administrator or manager must have a minimum of five years' experience in either cemetery or funeral management, or both, unless this requirement is waived by the board.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2126-S.SL.pdf?cite=2009%20c%20102%20§%208[2009 c 102 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%208[1987 c 331 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%2034[1953 c 290 § 34]; ]

== 68.05.100 - Rules.
The board may establish necessary rules for the enforcement of this title and the laws subject to its jurisdiction. The board shall prescribe the application forms and reports provided for in this title.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2126-S.SL.pdf?cite=2009%20c%20102%20§%209[2009 c 102 § 9]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2052[2005 c 365 § 52]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5026-S.SL.pdf?cite=1993%20c%2043%20§%203[1993 c 43 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%209[1987 c 331 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c402.pdf?cite=1985%20c%20402%20§%208[1985 c 402 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%2036[1953 c 290 § 36]; ]

== 68.05.105 - Authority of the board.
In addition to the authority in RCW 18.235.030, the board has the following authority under this chapter:

. To adopt, amend, and rescind rules necessary to carry out this title; and

. To adopt standards of professional conduct or practice.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2126-S.SL.pdf?cite=2009%20c%20102%20§%2010[2009 c 102 § 10]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2053[2005 c 365 § 53]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20316[2002 c 86 § 316]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2010[1987 c 331 § 10]; ]

== 68.05.115 - Sale or transfer of cemetery authority or creation of a new cemetery—Penalty for noncompliance.
Prior to the sale or transfer of ownership or control of any cemetery authority or the creation of a new cemetery, any person or entity desiring to acquire such ownership or control or to create a new cemetery shall apply in writing to the board for a new certificate of authority to operate a cemetery. The board shall enter any order deemed necessary for the protection of all endowment care funds and/or prearrangement trust fund during such transfer. As a condition of applying for a new certificate of authority, the entity desiring to acquire such ownership or control must agree to be bound by all then existing prearrangement contracts. Persons and business entities selling and persons and business entities purchasing ownership or control of a cemetery authority shall each verify and attest to an endowment care fund report and/or a prearrangement trust fund report showing the status of such funds on the date of the sale on a written report form prescribed by the board. Such reports shall be considered part of the application for authority to operate. Failure to comply with this section shall be a gross misdemeanor and any sale or transfer in violation of this section shall be void.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2054[2005 c 365 § 54]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2011[1987 c 331 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2011[1979 c 21 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c68.pdf?cite=1973%201st%20ex.s.%20c%2068%20§%2017[1973 1st ex.s. c 68 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c99.pdf?cite=1969%20ex.s.%20c%2099%20§%205[1969 ex.s. c 99 § 5]; ]

== 68.05.120 - Actions to enforce law—Attorney general.
The board is authorized to bring actions to enforce the provisions of the law subject to its jurisdiction, in which actions it shall be represented by the attorney general.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%2038[1953 c 290 § 38]; ]

== 68.05.150 - Examination of funds—Powers, duties.
In making such examination the board:

. Shall have free access to the books and records relating to the endowment care funds and prearrangement trust funds;

. Shall inspect and examine the endowment care funds and prearrangement trust funds to determine their condition and the status of the investments; and

. Shall verify that the cemetery authority has complied with all the laws applicable to endowment care funds and prearrangement trust funds.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2055[2005 c 365 § 55]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%208[1979 c 21 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c68.pdf?cite=1973%201st%20ex.s.%20c%2068%20§%2014[1973 1st ex.s. c 68 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%2044[1953 c 290 § 44]; ]

== 68.05.155 - Prearrangement sales license.
To enter into prearrangement contracts as defined in RCW 68.46.010, a cemetery authority shall have a valid prearrangement sales license. To apply for a prearrangement sales license, a cemetery authority shall:

. File with the board its request showing:

.. Its name, location, and organization date;

.. The kinds of cemetery business or merchandise it proposes to transact;

.. A statement of its current financial condition, management, and affairs on a form satisfactory to or furnished by the board; and

.. Such other documents, stipulations, or information as the board may reasonably require to evidence compliance with the provisions of this chapter; and

. Deposit with the department the fees required by this chapter to be paid for filing the accompanying documents, and for the prearrangement sales license, if granted.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2012[1987 c 331 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2028[1979 c 21 § 28]; ]

== 68.05.160 - Action required when authority fails to deposit minimum endowment amount or comply with prearrangement contract provisions.
If any examination made by the board, or any report filed with it, shows that there has not been collected and deposited in the endowment care funds the minimum amounts required by this title, or if the board finds that the cemetery authority has failed to comply with the requirements of this chapter and chapter 68.46 RCW with respect to prearrangement contracts, merchandise, or services, unconstructed crypts or niches or undeveloped graves, or prearrangement trust funds, the board shall require such cemetery authority to comply with this chapter or with chapter 68.40 or 68.46 RCW, as the case may be.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%209[1979 c 21 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c68.pdf?cite=1973%201st%20ex.s.%20c%2068%20§%2015[1973 1st ex.s. c 68 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%2045[1953 c 290 § 45]; ]

== 68.05.170 - Order requiring reinvestment in compliance with title—Actions for preservation and protection.
. Whenever the board finds, after notice and hearing, that any endowment care funds have been invested in violation of this title, it may by written order mailed to the person or body in charge of the fund require the reinvestment of the funds in conformity with this title within the period specified by it which shall be not more than six months. Such period may be extended by the board in its discretion.

. The board may bring actions for the preservation and protection of endowment care funds in the superior court of the county in which the cemetery is located. The court shall appoint substitute trustees and make any other order which may be necessary for the preservation, protection, and recovery of endowment care funds, whenever a cemetery authority or the trustees of its fund have:

.. Transferred or attempted to transfer any property to, or made any loan from, the endowment care funds for the benefit of the cemetery authority or any director, officer, agent or employee of the cemetery authority or trustee of any endowment care funds; or,

.. Failed to reinvest endowment care funds in accordance with a board order issued under subsection (1) of this section; or,

.. Invested endowment care funds in violation of this title; or,

.. Taken action or failed to take action to preserve and protect the endowment care funds; or,

.. Become financially irresponsible or transferred control of the cemetery authority to any person who, or business entity which, is financially irresponsible; or,

.. Is in danger of becoming insolvent or has gone into bankruptcy or receivership; or,

.. Taken any action in violation of Title 68 RCW or failed to take action required by Title 68 RCW or has failed to comply with lawful rules and orders of the board.

. Whenever the board or its representative has reason to believe that endowment care funds or prearrangement trust funds are in danger of being lost or diminished during the time required for notice and hearing, it may immediately impound or seize documents, financial instruments, or other trust fund assets, or take other actions deemed necessary under the circumstances for the preservation and protection of endowment care funds or prearrangement trust funds, including, but not limited to, immediate substitutions of trustees.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2056[2005 c 365 § 56]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20317[2002 c 86 § 317]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2023[1987 c 331 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c99.pdf?cite=1969%20ex.s.%20c%2099%20§%201[1969 ex.s. c 99 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%2046[1953 c 290 § 46]; ]

== 68.05.173 - Revocation, suspension of certificate or license.
Upon violation of any of the provisions of this title, the board may revoke or suspend the certificate of authority or any other license issued by the board.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2057[2005 c 365 § 57]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2024[1987 c 331 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%2049[1953 c 290 § 49]; ]

== 68.05.175 - License or endorsement required for cremation, alkaline hydrolysis, and natural organic reduction.
A license or endorsement issued under chapter 18.39 RCW is required in order to operate a crematory or conduct a cremation, operate or conduct alkaline hydrolysis, operate or conduct natural organic reduction, or operate a natural organic reduction facility.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5001-S.SL.pdf?cite=2019%20c%20432%20§%2012[2019 c 432 § 12]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2126-S.SL.pdf?cite=2009%20c%20102%20§%2011[2009 c 102 § 11]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2013[1987 c 331 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c402.pdf?cite=1985%20c%20402%20§%204[1985 c 402 § 4]; ]

== 68.05.180 - Annual report of authority—Contents—Verification.
Each cemetery authority in charge of cemetery endowment care funds shall annually, and within ninety days after the end of the calendar or fiscal year of the cemetery authority, file with the board a written report in form and content prescribed by the board.

These reports shall be verified by the president or vice president, one other officer of the cemetery authority, the accountant or auditor preparing the same, and, if required by the board for good cause, a certified public accountant in accordance with generally accepted auditing standards.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2010[1979 c 21 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c351.pdf?cite=1977%20ex.s.%20c%20351%20§%203[1977 ex.s. c 351 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c68.pdf?cite=1973%201st%20ex.s.%20c%2068%20§%2016[1973 1st ex.s. c 68 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%2040[1953 c 290 § 40]; ]

== 68.05.190 - Examination of reports.
The board shall examine the reports filed with it as to their compliance with the requirements of the law.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%2041[1953 c 290 § 41]; ]

== 68.05.195 - Burial or scatter of human remains—Permit.
Any person other than persons defined in RCW 68.50.160 who buries or scatters human remains by land, air, or sea or performs any other disposition of human remains outside of a cemetery must have a permit issued in accordance with RCW 68.05.100 and are subject to that section.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5001-S.SL.pdf?cite=2019%20c%20432%20§%2013[2019 c 432 § 13]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2058[2005 c 365 § 58]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2015[1987 c 331 § 15]; ]

== 68.05.205 - Fees.
The director with the consent of the board must set all fees for chapters 18.39, 68.05, 68.20, 68.24, 68.28, 68.32, 68.36, 68.40, 68.44, and 68.46 RCW in accordance with RCW 43.24.086, including fees for licenses, certificates, regulatory charges, permits, or endorsements, and the department must collect the fees.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5001-S.SL.pdf?cite=2019%20c%20432%20§%2014[2019 c 432 § 14]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2126-S.SL.pdf?cite=2009%20c%20102%20§%2012[2009 c 102 § 12]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5026-S.SL.pdf?cite=1993%20c%2043%20§%204[1993 c 43 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2016[1987 c 331 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c5.pdf?cite=1983%201st%20ex.s.%20c%205%20§%201[1983 1st ex.s. c 5 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c351.pdf?cite=1977%20ex.s.%20c%20351%20§%204[1977 ex.s. c 351 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c99.pdf?cite=1969%20ex.s.%20c%2099%20§%204[1969 ex.s. c 99 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%2051[1953 c 290 § 51]; ]

== 68.05.210 - Proof of applicant's compliance with laws and financial responsibility.
The board may require such proof as it deems advisable concerning the compliance by such applicant to all the laws, rules, regulations, ordinances and orders applicable to it. The board shall also require proof that the applicant and its officers and directors are financially responsible, in order that only cemeteries of permanent benefit to the community in which they are located will be established in this state.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2059[2005 c 365 § 59]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c99.pdf?cite=1969%20ex.s.%20c%2099%20§%202[1969 ex.s. c 99 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%2048[1953 c 290 § 48]; ]

== 68.05.215 - Certificates—Regulatory charges—Expiration.
The regulatory charges for cemetery certificates at all periods of the year are the same as provided in this chapter. All regulatory charges are payable at the time of the filing of the application and in advance of the issuance of the certificates. All certificates shall be issued for the year and shall expire at midnight, the thirty-first day of January of each year, or at whatever time during any year that ownership or control of any cemetery authority is transferred or sold. Cemetery certificates shall not be transferable.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2060[2005 c 365 § 60]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2017[1987 c 331 § 17]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1969ex1c99.pdf?cite=1969%20ex.s.%20c%2099%20§%203[1969 ex.s. c 99 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%2050[1953 c 290 § 50]; ]

== 68.05.225 - Sales licenses—Terms—Fees.
All prearrangement sales licenses issued under this chapter shall be issued for the year and shall expire at midnight, the thirty-first day of January of each year, or at whatever time during any year that ownership or control of any cemetery authority is transferred or sold.

The director, in accordance with RCW 43.24.086, shall set and the department shall collect in advance the fees required for licensing.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2061[2005 c 365 § 61]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2018[1987 c 331 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2029[1979 c 21 § 29]; ]

== 68.05.235 - Reports—Failure to file.
. Each authorized cemetery authority shall, within ninety days after the close of its accounting year, file with the board an endowment care trust fund report and a prearrangement trust fund report for the preceding year. The reports shall be on such forms and shall contain such information as required by this chapter and by the board.

. The failure to file a report as required under subsection (1) of this section constitutes unprofessional conduct for which the board may take disciplinary action against the prearrangement sales license of the cemetery authority. In addition, the board may take disciplinary action against any other license held by the cemetery authority.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2062[2005 c 365 § 62]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20318[2002 c 86 § 318]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2019[1987 c 331 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2037[1979 c 21 § 37]; ]

== 68.05.240 - Interment, certificate of authority required—Penalty.
It shall be a misdemeanor for any cemetery authority to make any interment without a valid, unsuspended certificate of authority. Each interment shall be a separate violation.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2063[2005 c 365 § 63]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%2052[1953 c 290 § 52]; ]

== 68.05.245 - Crematory permits, licenses, or endorsements—Terms—Fees.
. All permits, licenses, or endorsements issued under this chapter or chapter 18.39 RCW must be issued for the year and expire at midnight, the thirty-first day of January of each year, or at whatever time during any year that ownership or control of any cemetery authority that operates such facility is transferred or sold.

. The director must set and the department must collect in advance the fees required for licensing.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5001-S.SL.pdf?cite=2019%20c%20432%20§%2015[2019 c 432 § 15]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2064[2005 c 365 § 64]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2020[1987 c 331 § 20]; ]

== 68.05.254 - Examination of endowment funds and prearrangement trust funds.
. The board shall examine the endowment care and prearrangement trust fund or funds of a cemetery authority:

.. Whenever it deems necessary, but at least once every three years after the original examination except where the cemetery authority is either required by the board to, or voluntarily files an annual financial report for the fund certified by a certified public accountant or a licensed public accountant in accordance with generally accepted auditing standards;

.. One year following the issuance of a new certificate of authority;

.. Whenever the cemetery authority in charge of endowment care or prearrangement trust fund or funds fails after reasonable notice from the board to file the reports required by this chapter; or

.. Whenever it is requested by verified petition signed by twenty-five lot owners alleging that the endowment care funds are not in compliance with this title, or whenever it is requested by verified petition signed by twenty-five purchasers or beneficiaries of prearrangement merchandise or services alleging that the prearrangement trust funds are not in compliance with this title, in either of which cases, the examination shall be at the expense of the petitioners.

. The expense of the endowment care and prearrangement trust fund examination as provided in subsection (1)(a) and (b) of this section shall be paid by the cemetery authority. Such examination shall be privately conducted in the principal office of the cemetery authority.

. The requirements that examinations be conducted once every three years and that they be conducted in the principal office of the cemetery authority do not apply to any endowment care or prearrangement fund that is less than twenty-five thousand dollars. The board shall, at its discretion, decide when and where the examinations shall take place.

. Examination expenses incurred in conjunction with a transfer of ownership of a cemetery must be paid by the selling entity.

. All examination expense moneys collected by the department must be paid to the cemetery account created in *RCW 68.05.285.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2065[2005 c 365 § 65]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2021[1987 c 331 § 21]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%207[1979 c 21 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c68.pdf?cite=1973%201st%20ex.s.%20c%2068%20§%2012[1973 1st ex.s. c 68 § 12]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%2042[1953 c 290 § 42]; ]

== 68.05.259 - Payment of examination expenses.
If any cemetery authority refuses to pay any examination expenses within thirty days of completion of the examination or refuses to pay certain examination expenses in advance as required by the department for cause, the board may take disciplinary action against any existing certificate of authority.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2066[2005 c 365 § 66]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20319[2002 c 86 § 319]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2022[1987 c 331 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c68.pdf?cite=1973%201st%20ex.s.%20c%2068%20§%2013[1973 1st ex.s. c 68 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%2043[1953 c 290 § 43]; ]

== 68.05.290 - Board members' immunity from suits.
Members of the board shall be immune from suit in any action, civil or criminal, based upon any official acts performed in good faith as members of the board. The state shall defend, indemnify, and hold the members of the board harmless from all claims or suits arising in any manner from such acts. Expenses incurred by the state under this section shall be paid from the general fund.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2068[2005 c 365 § 68]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2012[1979 c 21 § 12]; ]

== 68.05.300 - Unprofessional conduct—Disciplinary action.
In addition to the unprofessional conduct described in RCW 18.235.130, the board may take disciplinary action if the cemetery authority:

. Fails to comply with any provision of this chapter or any proper order or regulation of the board;

. Is found by the board to be in such condition that further execution of prearrangement contracts would be hazardous to purchasers or beneficiaries and the people of this state; or

. Is found by the board after investigation or receipt of reliable information to be managed by persons who are incompetent or untrustworthy or so lacking in managerial experience as to make the proposed or continued operation hazardous to purchasers, beneficiaries, or the public.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20320[2002 c 86 § 320]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2025[1987 c 331 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2030[1979 c 21 § 30]; ]

== 68.05.310 - Prearrangement sales—Disciplinary action.
No cemetery authority whose prearrangement sales license has been the subject of disciplinary action shall be authorized to enter into prearrangement contracts unless specifically authorized by the board and only upon full compliance with the conditions required by the board. Any prearrangement sale by an unlicensed cemetery authority shall be voidable by the purchaser who shall be entitled to a full refund.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20321[2002 c 86 § 321]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c175.pdf?cite=1989%20c%20175%20§%20124[1989 c 175 § 124]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2026[1987 c 331 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2031[1979 c 21 § 31]; ]

== 68.05.320 - Board action against authorities—Administrative procedures.
. The board or its authorized representative may issue and serve upon a cemetery authority a notice of charges if in the opinion of the board or its authorized representative the cemetery authority:

.. Is engaging in or has engaged in practices likely to endanger the future delivery of cemetery merchandise or services, unconstructed crypts or niches, or undeveloped graves;

.. Is violating or has violated any statute of the state of Washington or any rule of the board; or

.. Is about to do an act prohibited in (a) or (b) of this subsection when the opinion is based upon reasonable cause.

. The notice shall contain a statement of the facts constituting the alleged violation or practice and shall fix a time and place at which a hearing will be held to determine whether an order to cease and desist should issue against the cemetery authority. The hearing shall be set not earlier than ten nor later than thirty days after service of the notice unless a later date is set by the board or its authorized representative at the request of the cemetery authority.

Unless the cemetery authority appears at the hearing by a duly authorized representative it shall be deemed to have consented to the issuance of a cease and desist order. In the event of this consent or if upon the record made at the hearing the board finds that any violation or practice specified in the notice of charges has been established, the board may issue and serve upon the cemetery authority an order to cease and desist from the violation or practice. The order may require the cemetery authority and its directors, officers, employees, and agents to cease and desist from the violation or practice and may require the cemetery authority to take affirmative action to correct the conditions resulting from the violation or practice.

. A cease and desist order shall become effective at the expiration of ten days after service of the order upon the cemetery authority except that a cease and desist order issued upon consent shall become effective as provided in the order unless it is stayed, modified, terminated, or set aside by action of the board or a reviewing court.

. The powers of the board under this section are in addition to the power of the board to take disciplinary action against a cemetery authority's prearrangement sales license.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20322[2002 c 86 § 322]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2032[1979 c 21 § 32]; ]

== 68.05.330 - Violation—Penalty—Unfair practice—Other laws applicable.
Unless specified otherwise in this title, any person who violates or aids or abets any person in the violation of any of the provisions of this title shall be guilty of a class C felony punishable under chapter 9A.20 RCW. A violation shall constitute an unfair practice under chapter 19.86 RCW and shall be grounds for disciplinary action against the certificate of authority or any other license issued by the board under this chapter and chapter 18.235 RCW. Retail installment transactions under this chapter shall be governed by chapter 63.14 RCW. The provisions of this chapter shall not affect any other remedy available at law.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2069[2005 c 365 § 69]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20323[2002 c 86 § 323]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2027[1987 c 331 § 27]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c53.pdf?cite=1984%20c%2053%20§%206[1984 c 53 § 6]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2039[1979 c 21 § 39]; ]

== 68.05.340 - Board action against authorities—Cease and desist orders.
Whenever the board or its authorized representative determines that a cemetery authority is in violation of this title or that the continuation of acts or practices of the cemetery authority is likely to cause insolvency or substantial loss of assets or earnings of the cemetery authority's endowment care or prearrangement trust fund, the board, or its authorized representative, may issue a temporary order requiring the cemetery authority to cease and desist from the violation or practice. The order shall become effective upon service on the cemetery authority. The order shall remain effective unless set aside, limited, or suspended by a court in proceedings under RCW 68.05.350, until the board dismisses the charges specified in the notice, or until the effective date of a cease and desist order issued against the cemetery authority under RCW 68.05.320. Actions for unlicensed activity must be conducted under RCW 18.235.150.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2070[2005 c 365 § 70]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20324[2002 c 86 § 324]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2028[1987 c 331 § 28]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2033[1979 c 21 § 33]; ]

== 68.05.350 - Delaying board action pending administrative proceedings.
Within ten days after a cemetery authority has been served with a temporary cease and desist order issued under RCW 68.05.320, the cemetery authority may apply to the superior court in the county of its principal place of business for an injunction setting aside, limiting, or suspending the order pending completion of the administrative proceedings under RCW 68.05.320.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20325[2002 c 86 § 325]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2029[1987 c 331 § 29]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2034[1979 c 21 § 34]; ]

== 68.05.360 - Board action against authorities—Hearing location—Decision—Review.
Any administrative hearing under RCW 68.05.320 may be held at such place as is designated by the board and shall be conducted in accordance with chapter 34.05 RCW.

Within sixty days after the hearing the board shall render a decision which shall include findings of fact upon which the decision is based and shall issue and serve upon each party to the proceeding an order or orders consistent with RCW 68.05.320.

Review of the decision shall be as provided in chapter 34.05 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2030[1987 c 331 § 30]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2035[1979 c 21 § 35]; ]

== 68.05.370 - Board action against authorities—Enforcement of orders.
The board may apply to the superior court of the county of the principal place of business of the cemetery authority affected for enforcement of any effective and outstanding order issued under RCW 68.05.320 or 68.05.340, and the court shall have jurisdiction to order compliance with the order.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2031[1987 c 331 § 31]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2036[1979 c 21 § 36]; ]

== 68.05.400 - Exemptions from chapter.
The provisions of this chapter do not apply to any of the following:

. Nonprofit cemeteries which are owned or operated by any recognized religious denomination which qualifies for an exemption from real estate taxation under RCW 84.36.020 on any of its churches or the ground upon which any of its churches are or will be built; or

. Any cemetery controlled and operated by a coroner, county, city, town, or cemetery district.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2013[1979 c 21 § 13]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c133.pdf?cite=1961%20c%20133%20§%201[1961 c 133 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%2030[1953 c 290 § 30]; ]

== 68.05.430 - Uniform regulation of business and professions act.
The uniform regulation of business and professions act, chapter 18.235 RCW, governs unlicensed practice, the issuance and denial of licenses, and the discipline of licensees under this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2512-S.SL.pdf?cite=2002%20c%2086%20§%20326[2002 c 86 § 326]; ]

== 68.05.900 - Effective date—1987 c 331.
This act is necessary for the immediate preservation of the public peace, health, and safety, the support of the state government and its existing public institutions, and shall take effect July 1, 1987.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2091[1987 c 331 § 91]; ]

