= 68.24 - Cemetery property.
:toc:

== 68.24.010 - Right to acquire property.
Cemetery authorities may take by purchase, donation, or devise, property consisting of lands, mausoleums, cremation, alkaline hydrolysis, or natural organic reduction facilities, and columbariums, or other property within which the placement of human remains may be authorized by law.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5001-S.SL.pdf?cite=2019%20c%20432%20§%2017[2019 c 432 § 17]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2073[2005 c 365 § 73]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2061[1943 c 247 § 61]; Rem. Supp. 1943 § 3778-61; ]

== 68.24.020 - Surveys and maps.
Every cemetery authority, from time to time as its property may be required for cemetery purposes, shall:

. In case of land, survey and subdivide it into sections, blocks, plots, avenues, walks, or other subdivisions; make a good and substantial map or plat showing the sections, plots, avenues, walks or other subdivisions, with descriptive names or numbers.

. In case of a mausoleum, or columbarium, it shall make a good and substantial map or plat on which shall be delineated the sections, halls, rooms, corridors, elevation, and other divisions, with descriptive names or numbers.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2062[1943 c 247 § 62]; Rem. Supp. 1943 § 3778-62; ]

== 68.24.030 - Declaration of dedication and maps—Filing.
The cemetery authority shall file the map or plat in the office of the recorder of the county in which all or a portion of the property is situated. The cemetery authority shall also file for record in the county recorder's office a written declaration of dedication of the property delineated on the plat or map, dedicating the property exclusively to cemetery purposes.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2063[1943 c 247 § 63]; Rem. Supp. 1943 § 3778-63; ]

== 68.24.040 - Dedication, when complete.
Upon the filing of the map or plat and the filing of the declaration for record, the dedication is complete for all purposes and thereafter the property shall be held, occupied, and used exclusively for a cemetery and for cemetery purposes.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2064[1943 c 247 § 64]; Rem. Supp. 1943 § 3778-64; ]

== 68.24.050 - Constructive notice.
The filed map or plat and the recorded declaration are constructive notice to all persons of the dedication of the property to cemetery purposes.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2066[1943 c 247 § 66]; Rem. Supp. 1943 § 3778-66; ]

== 68.24.060 - Maps and plats—Amendment.
Any part or subdivision of the property so mapped and plotted may, by order of the directors, be resurveyed and altered in shape and size and an amended map or plat filed, so long as such change does not disturb the interred remains of any deceased person.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2065[1943 c 247 § 65]; Rem. Supp. 1943 § 3778-65; ]

== 68.24.070 - Permanency of dedication.
After property is dedicated to cemetery purposes pursuant to RCW 68.24.010 through 68.24.060, neither the dedication, nor the title of a plot owner, shall be affected by the dissolution of the cemetery authority, by nonuser on its part, by alienation of the property, by any incumbrances, by sale under execution, or otherwise except as provided in *this act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2067[1943 c 247 § 67]; Rem. Supp. 1943 § 3778-67; ]

== 68.24.080 - Rule against perpetuities, etc., inapplicable.
Dedication to cemetery purposes pursuant to *this act is not invalid as violating any laws against perpetuities or the suspension of the power of alienation of title to or use of property, but is expressly permitted and shall be deemed to be in respect for the dead, a provision for the placement of human remains, and a duty to, and for the benefit of, the general public.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2074[2005 c 365 § 74]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2068[1943 c 247 § 68]; Rem. Supp. 1943 § 3778-68; ]

== 68.24.090 - Removal of dedication—Procedure.
Property dedicated to cemetery purposes shall be held and used exclusively for cemetery purposes, unless and until the dedication is removed from all or any part of it by an order and decree of the superior court of the county in which the property is situated, in a proceeding brought by the cemetery authority for that purpose and upon notice of hearing and proof satisfactory to the court:

. That no placements of human remains were made in or that all placements of human remains have been removed from that portion of the property from which dedication is sought to be removed.

. That the portion of the property from which dedication is sought to be removed is not being used for placement of human remains.

. That notice of the proposed removal of dedication has been given in writing to both the funeral and cemetery board and the department of archaeology and historic preservation. This notice must be given at least sixty days before filing the proceedings in superior court. The notice of the proposed removal of dedication shall be recorded with the auditor or recording officer of the county where the cemetery is located at least sixty days before filing the proceedings in superior court.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2126-S.SL.pdf?cite=2009%20c%20102%20§%2013[2009 c 102 § 13]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2075[2005 c 365 § 75]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1951-S.SL.pdf?cite=1999%20c%20367%20§%202[1999 c 367 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2034[1987 c 331 § 34]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2076[1943 c 247 § 76]; Rem. Supp. 1943 § 3778-76; ]

== 68.24.100 - Notice of hearing.
The notice of hearing provided in RCW 68.24.090 shall be given by publication once a week for at least three consecutive weeks in a newspaper of general circulation in the county where said cemetery is located, and the posting of copies of the notice in three conspicuous places on that portion of the property from which the dedication is to be removed. The notice shall:

. Describe the portion of the cemetery property sought to be removed from dedication.

. State that all human remains have been removed or that no interments have been made in the portion of the cemetery property sought to be removed from dedication.

. Specify the time and place of the hearing.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2076[2005 c 365 § 76]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2077[1943 c 247 § 77]; Rem. Supp. 1943 § 3778-77; ]

== 68.24.110 - Sale of plots or rights of interment.
After filing the map or plat and recording the declaration of dedication, a cemetery authority may sell and convey plots or rights of interment subject to the rules in effect or thereafter adopted by the cemetery authority. Plots or rights of interment may be subject to other limitations, conditions, and restrictions as may be part of the declaration of dedication by reference, or included in the instrument of conveyance of the plot or rights of interment.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2077[2005 c 365 § 77]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2070[1943 c 247 § 70]; Rem. Supp. 1943 § 3778-70. FORMER PART OF SECTION: 1943 c 247 § 72 now codified as RCW  68.24.115; ]

== 68.24.115 - Execution of conveyances.
All conveyances made by a cemetery authority shall be signed by such officer or officers as are authorized by the cemetery authority.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2072[1943 c 247 § 72]; Rem. Supp. 1943 § 3778-72; ]

== 68.24.120 - Plots or rights of interment indivisible.
All plots or rights of interment, the use of which has been conveyed by deed or certificate of ownership as a separate plot or right of interment, are indivisible except with the consent of the cemetery authority, or as provided by law.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2078[2005 c 365 § 78]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2071[1943 c 247 § 71]; Rem. Supp. 1943 § 3778-71; ]

== 68.24.130 - Sale for resale prohibited—Penalty.
It shall be unlawful for any person, firm, or corporation to sell or offer to sell a cemetery plot or right of interment upon the promise, representation, or inducement of resale at a financial profit. Each person violating this section shall be guilty of a misdemeanor and each violation shall constitute a separate offense.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2079[2005 c 365 § 79]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2073[1943 c 247 § 73]; Rem. Supp. 1943 § 3778-73; ]

== 68.24.140 - Commission on sales prohibited—Penalty.
It shall be unlawful for a cemetery authority to pay or offer to pay to any person, firm, or corporation, directly or indirectly, a commission or bonus or rebate or other thing of value for the sale of a plot, right of interment, or services. This shall not apply to an owner or a person regularly employed by the cemetery authority for such purpose. Each person violating this section shall be guilty of a misdemeanor and each violation shall constitute a separate offense.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2080[2005 c 365 § 80]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2074[1943 c 247 § 74]; Rem. Supp. 1943 § 3778-74; ]

== 68.24.150 - Unlawful employment of others to dispose of human remains.
Every person who pays, causes to be paid, or offers to pay to any other person, firm, or corporation, directly or indirectly, except as provided in RCW 68.24.140, any commission, bonus, or rebate, or other thing of value in consideration of recommending or causing the disposition of human remains in any cremation, alkaline hydrolysis, or natural organic reduction facility or cemetery, is guilty of a misdemeanor. Each violation constitutes a separate offense.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5001-S.SL.pdf?cite=2019%20c%20432%20§%2018[2019 c 432 § 18]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2081[2005 c 365 § 81]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2075[1943 c 247 § 75]; Rem. Supp. 1943 § 3778-75; ]

== 68.24.160 - Liens subordinate to dedication.
All mortgages, deeds of trust, and other liens placed upon property which has been dedicated as a cemetery, or which is afterwards dedicated to cemetery purposes pursuant to this section, shall not affect or defeat the dedication. The mortgage, deed of trust, or other lien is subject and subordinate to the dedication. Any and all sales made upon foreclosure are subject and subordinate to the dedication for cemetery purposes.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2082[2005 c 365 § 82]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2060[1943 c 247 § 60]; Rem. Supp. 1943 § 3778-60; ]

== 68.24.170 - Record of ownership and transfers.
A record shall be kept of the ownership of all plots or rights of interment in the cemetery, which have been conveyed by the cemetery authority and of all transfers of plots and rights of interment in the cemetery. No transfer of any plot or right of interment, shall be complete or effective until recorded on the books of the cemetery authority.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2083[2005 c 365 § 83]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2040[1943 c 247 § 40]; Rem. Supp. 1943 § 3778-40. FORMER PART OF SECTION: 1943 c 247 § 41 now codified as RCW  68.24.175; ]

== 68.24.180 - Opening of roads, railroads through cemetery—Consent required.
After dedication under this title, and as long as the property remains dedicated to cemetery purposes, a railroad, street, road, alley, pipe line, pole line, or other public thoroughfare or utility shall not be laid out, through, over, or across any part of it without the consent of the cemetery authority or of not less than two-thirds of the owners of plots or rights of interment.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2084[2005 c 365 § 84]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6025.SL.pdf?cite=1994%20c%20273%20§%2020[1994 c 273 § 20]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c7.pdf?cite=1984%20c%207%20§%20369[1984 c 7 § 369]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c217.pdf?cite=1959%20c%20217%20§%201[1959 c 217 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1947c69.pdf?cite=1947%20c%2069%20§%201[1947 c 69 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2069[1943 c 247 § 69]; Rem. Supp. 1947 § 3778-69; ]

== 68.24.190 - Opening road through cemetery—Penalty.
Every person who shall make or open any road, or construct any railway, turnpike, canal, or other public easement over, through, in, or upon any property used for the burial of human remains, without authority of law or the consent of the owner, shall be guilty of a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2085[2005 c 365 § 85]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20241[1909 c 249 § 241]; RRS § 2493; ]

== 68.24.220 - Burying place exempt from execution.
Whenever any part of such burying ground shall have been designated and appropriated by the owners as the burying place of any particular person or family, the same shall not be liable to be taken or disposed of by any warrant, execution, tax, or debt whatever; nor shall the same be liable to be sold to satisfy the demands of creditors whenever the estate of the owner shall be insolvent.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2086[2005 c 365 § 86]; http://leg.wa.gov/CodeReviser/Pages/session_laws.aspx?cite=1857%20p%2028%20§%202[1857 p 28 § 2]; RRS § 3760; ]

== 68.24.240 - Certain cemetery lands exempt from taxes, etc.—1901 c 147.
Upon compliance with the requirements of *this act said lands shall forever be exempt from taxation, judgment and other liens and executions.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1901c147.pdf?cite=1901%20c%20147%20§%204[1901 c 147 § 4]; RRS § 3763; ]

== 68.24.250 - Cemetery arrangements, notice requirements—Disclosure of multiple interment.
. Every cemetery shall disclose and give to the person making cemetery arrangements a written statement, contract, or other document that indicates all the items of property, merchandise, and service that the customer is purchasing, and the price of those items.

. Any cemetery offering single burial use of multiple interment space must include the following disclosure on the written statement, contract, or other document in conspicuous bold face type no smaller than other text provisions in the written statement, contract, or other document, to be initialed by the person making the cemetery arrangements in immediate proximity to the space reserved for the signature lines:

"DISCLOSURE OF MULTIPLE INTERMENT

State law provides that "multiple interment" means two or more noncremated human remains are buried in the ground, in outer burial enclosures or chambers, placed one on top of another, with a ground level surface the same size as a single grave or right of interment."

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5182-S.SL.pdf?cite=2005%20c%20359%20§%202[2005 c 359 § 2]; ]

