= 68.20 - Private cemeteries.
:toc:

== 68.20.010 - Incorporation required.
It is unlawful for any corporation, copartnership, firm, trust, association, or individual to engage in or transact any of the businesses of a cemetery within this state except by means of a corporation duly organized for that purpose.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2042[1943 c 247 § 42]; Rem. Supp. 1943 § 3778-42; ]

== 68.20.020 - Corporations, how organized.
Any private corporation authorized by its articles so to do, may establish, maintain, manage, improve, or operate a cemetery, and conduct any or all of the businesses of a cemetery, either for or without profit to its members or stockholders. A nonprofit cemetery corporation may be organized in the manner provided in chapter 24.03 RCW. A profit corporation may be organized in the manner provided in the general corporation laws of the state of Washington.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c3.pdf?cite=1983%20c%203%20§%20167[1983 c 3 § 167]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2043[1943 c 247 § 43]; Rem. Supp. 1943 § 3778-43; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1899c33.pdf?cite=1899%20c%2033%20§%201[1899 c 33 § 1]; 1856-7 p 28 § 1; ]

== 68.20.030 - Powers of existing corporations enlarged.
The powers, privileges and duties conferred and imposed upon any corporation, firm, copartnership, association, trust, or individual, existing and doing business under the laws of this state, are hereby enlarged as each particular case may require to conform to the provisions of *this act.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2045[1943 c 247 § 45]; Rem. Supp. 1943 § 3778-45; ]

== 68.20.040 - Prior corporations not affected.
The provisions of *this act do not affect the corporate existence or rights or powers of any cemetery organized under any law then existing prior to June 9, 1943, and as to such cemeteries and their rights, powers specified in their charters or articles of incorporation, the laws under which the corporation was organized and existed and under which such rights and powers become fixed or vested are applicable.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2044[1943 c 247 § 44]; Rem. Supp. 1943 § 3778-44; ]

== 68.20.050 - General powers of cemetery corporations.
Unless otherwise limited by the law under which created[,] cemetery authorities shall in the conduct of their business have the same powers granted by law to corporations in general, including the right to contract such pecuniary obligations within the limitation of general law as may be required, and may secure them by mortgage, deed of trust, or otherwise upon their property.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2059[1943 c 247 § 59]; Rem. Supp. 1943 § 3778-59; ]

== 68.20.060 - Specific powers—Rule making and enforcement.
A cemetery authority may make, adopt, amend, add to, revise, or modify, and enforce rules and regulations for the use, care, control, management, restriction and protection of all or any part of its cemetery and for the other purposes specified in RCW 68.20.061 through 68.20.067, 68.20.070 and * 68.48.080.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2046[1943 c 247 § 46]; Rem. Supp. 1943 § 3778-46; ]

== 68.20.061 - Specific powers—Control of property.
It may restrict and limit the use of all property within its cemetery, including interment rights.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2071[2005 c 365 § 71]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2047[1943 c 247 § 47]; Rem. Supp. 1943 § 3778-47; ]

== 68.20.062 - Specific powers—Regulation as to type of markers, monuments, etc.
It may regulate the uniformity, class, and kind of all markers, monuments, and other structures within the cemetery and its subdivisions.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2048[1943 c 247 § 48]; Rem. Supp. 1943 § 3778-48; ]

== 68.20.063 - Specific powers—Regulation or prohibition as to the erection of monuments, effigies, etc.
It may regulate or prohibit the erection of monuments, markers, effigies, and structures within any portion of the cemetery.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2049[1943 c 247 § 49]; Rem. Supp. 1943 § 3778-49; ]

== 68.20.064 - Specific powers—Regulation of plants and shrubs.
It may regulate or prevent the introduction or care of plants or shrubs within the cemetery.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2050[1943 c 247 § 50]; Rem. Supp. 1943 § 3778-50; ]

== 68.20.065 - Specific powers—Prevention of interment.
It may prevent interment in any part of the cemetery of human remains not entitled to interment and prevent the use of interment plots for purposes violative of its restrictions or rules and regulations.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2051[1943 c 247 § 51]; Rem. Supp. 1943 § 3778-51; ]

== 68.20.066 - Specific powers—Prevention of improper assemblages.
It may regulate the conduct of persons and prevent improper assemblages in the cemetery.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2052[1943 c 247 § 52]; Rem. Supp. 1943 § 3778-52; ]

== 68.20.067 - Specific powers—Rules and regulations for general purposes.
It may make and enforce rules and regulations for all other purposes deemed necessary by the cemetery authority for the proper conduct of the business of the cemetery, for the transfer of any plot or the right of interment, and the protection and safeguarding of the premises, and the principles, plans, and ideals on which the cemetery is conducted.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2053[1943 c 247 § 53]; Rem. Supp. 1943 § 3778-53; ]

== 68.20.070 - Rules and regulations—Posting.
The rules and regulations made pursuant to RCW 68.20.060 shall be plainly printed or typewritten and maintained subject to inspection in the office of the cemetery authority or in such place or places within the cemetery as the cemetery authority may prescribe.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2054[1943 c 247 § 54]; Rem. Supp. 1943 § 3778-54. FORMER PART OF SECTION: 1943 c 247 §§ 46 and 53 now codified as RCW  68.20.060 and  68.20.067; ]

== 68.20.080 - Cities and counties may regulate cemeteries.
Cities and counties are authorized to enact ordinances regulating or prohibiting the establishment of new cemeteries or the extension of existing ones and to give power to local planning commissions to pass upon and make recommendations to local legislative bodies concerning the establishment or extension of cemeteries.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%20143[1943 c 247 § 143]; Rem. Supp. 1943 § 3778-143; ]

== 68.20.110 - Nonprofit cemetery association—Tax exempt land.
Nonprofit cemetery associations shall be authorized to purchase or take by gift or devise, and hold land exempt from execution and from any appropriation to public purposes for the sole purpose of a cemetery not exceeding eighty acres, which shall be exempt from taxation if intended to be used exclusively for burial purposes without discrimination as to race, color, national origin or ancestry, and in nowise with a view to profit of the members of such association: PROVIDED, That when the land already held by the association is all practically used then the amount thereof may be increased by adding thereto not exceeding twenty acres at a time.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2072[2005 c 365 § 72]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c103.pdf?cite=1961%20c%20103%20§%202[1961 c 103 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1899c33.pdf?cite=1899%20c%2033%20§%203[1899 c 33 § 3]; RRS § 3766; ]

== 68.20.120 - Sold lots exempt from taxes, etc.—Nonprofit associations.
Burial lots, sold by *such association shall be for the sole purpose of interment, and shall be exempt from taxation, execution, attachment or other claims, lien or process whatsoever, if used as intended, exclusively for burial purposes and in nowise with a view to profit.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1899c33.pdf?cite=1899%20c%2033%20§%205[1899 c 33 § 5]; RRS § 3768; ]

== 68.20.140 - Certain cemeteries exempt from chapter.
This chapter does not apply to any cemetery controlled and operated by a coroner, county, city, town, or cemetery district.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2033[1987 c 331 § 33]; ]

