= 68.28 - Mausoleums and columbariums.
:toc:

== 68.28.010 - Sections applicable to mausoleums, columbariums, etc.
RCW 68.28.020 through 68.28.070, 68.20.080, * 68.20.090, 68.56.040, and 68.56.050, apply to all buildings, mausoleums, and columbariums used or intended to be used for the placement of the human remains of fifteen or more persons, whether erected under or above the surface of the earth, where any portion of the building is exposed to view or, when interment is completed, is less than three feet below the surface of the earth and covered by earth.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2087[2005 c 365 § 87]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%20134[1943 c 247 § 134]; Rem. Supp. 1943 § 3778-134; ]

== 68.28.020 - Building converted to use for human remains placement.
A building not erected for, or which is not used as, a place for placement of human remains which is converted or altered for such use is subject to *this act.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2088[2005 c 365 § 88]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%20135[1943 c 247 § 135]; Rem. Supp. 1943 § 3778-135; ]

== 68.28.030 - Standards of construction.
No building or structure intended to be used for the placement of human remains shall be constructed, and a building not used for the placement of human remains shall not be altered for use or used for interment purposes, unless constructed of such material and workmanship as will ensure its durability and permanence as dictated and determined at the time by modern mausoleum construction and engineering science.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2089[2005 c 365 § 89]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%20136[1943 c 247 § 136]; Rem. Supp. 1943 § 3778-136; ]

== 68.28.040 - Fireproof construction.
All mausoleums or columbariums hereafter constructed shall be of class A fireproof construction.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%20137[1943 c 247 § 137]; Rem. Supp. 1943 § 3778-137; ]

== 68.28.050 - Ordinances and specifications to be complied with.
If the proposed site is within the jurisdiction of a city having ordinances and specifications governing class A construction, the provisions of the local ordinances and specifications shall not be violated.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%20138[1943 c 247 § 138]; Rem. Supp. 1943 § 3778-138; ]

== 68.28.060 - Improper construction a nuisance—Penalty.
Every owner or operator of a mausoleum or columbarium erected in violation of *this act is guilty of maintaining a public nuisance. A violation of this section is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2090[2005 c 365 § 90]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20306[2003 c 53 § 306]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%20140[1943 c 247 § 140]; Rem. Supp. 1943 § 3778-140; ]

== 68.28.065 - Court to fix costs.
The costs, expenses and disbursements shall be fixed by the court having jurisdiction of the case.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%20141[1943 c 247 § 141]; Rem. Supp. 1943 § 3778-141; ]

== 68.28.070 - Construction in compliance with existing laws.
The penalties of *this act shall not apply as to any building which, at the time of construction was constructed in compliance with the laws then existing, if its use is not in violation of the laws for the protection of public health.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%20142[1943 c 247 § 142]; Rem. Supp. 1943 § 3778-142; ]

