= 68.32 - Title and rights to cemetery plots.
:toc:

== 68.32.010 - Presumption as to title.
All plots or rights of interment conveyed to individuals are presumed to be the sole and separate property rights of the owner named in the instrument of conveyance.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2091[2005 c 365 § 91]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2088[1943 c 247 § 88]; Rem. Supp. 1943 § 3778-88; ]

== 68.32.020 - Vested right of spouse or state registered domestic partner.
The spouse or state registered domestic partner , of an owner of any plot or right of interment containing more than one placement space has a vested right of placement in the plot and any person thereafter becoming the spouse or state registered domestic partner , of the owner has a vested right of placement in the plot if more than one space is unoccupied at the time the person becomes the spouse or state registered domestic partner , of the owner.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5336-S.SL.pdf?cite=2007%20c%20156%20§%2015[2007 c 156 § 15]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2092[2005 c 365 § 92]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2089[1943 c 247 § 89]; Rem. Supp. 1943 § 3778-89; ]

== 68.32.030 - Vested right—Termination.
No conveyance or other action of the owner without the written consent of the spouse or state registered domestic partner , of the owner divests the spouse or state registered domestic partner , of a vested right of placement. A final decree of divorce between them or certification of termination of the state registered domestic partnership terminates the vested right of placement unless otherwise provided in the decree.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5336-S.SL.pdf?cite=2007%20c%20156%20§%2016[2007 c 156 § 16]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2093[2005 c 365 § 93]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2090[1943 c 247 § 90]; Rem. Supp. 1943 § 3778-90; ]

== 68.32.040 - Descent of title to plot or right of interment.
If no placement is made in a plot or right of interment, which has been transferred by deed or certificate of ownership to an individual owner, the title descends to the surviving spouse or state registered domestic partner. If there is no surviving spouse or state registered domestic partner, the title descends to the heirs at law of the owner. Following death of the owner, if all remains previously placed are lawfully removed and the owner did not dispose of the plot or right of interment by specific devise or by a written declaration filed and recorded in the office of the cemetery authority, the title descends to the surviving spouse or state registered domestic partner. If there is no surviving spouse or state registered domestic partner, the title descends to the heirs at law of the owner.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5336-S.SL.pdf?cite=2007%20c%20156%20§%2017[2007 c 156 § 17]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2094[2005 c 365 § 94]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2015[1979 c 21 § 15]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2091[1943 c 247 § 91]; Rem. Supp. 1943 § 3778-91; ]

== 68.32.050 - Affidavit as authorization.
An affidavit by a person having knowledge of the facts setting forth the fact of the death of the owner and the name of the person or persons entitled to the use of the plot or right of interment pursuant to RCW 68.32.010 through 68.32.040, is complete authorization to the cemetery authority to permit the use of the unoccupied portions of the plot or interment right by the person entitled to the use of it.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2095[2005 c 365 § 95]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2093[1943 c 247 § 93]; Rem. Supp. 1943 § 3778-93; ]

== 68.32.060 - Family plot—Sale.
Whenever an interment of the human remains of a member or of a relative of a member of the family of the record owner or of the remains of the record owner is made in a plot transferred by deed or certificate of ownership to an individual owner and both the owner and the surviving spouse or state registered domestic partner, if any, die with children then living without making disposition of the plot either by a specific devise, or by a written declaration filed and recorded in the office of the cemetery authority, the plot shall thereafter be held as a family plot and shall be subject to sale only upon agreement of the children of the owner living at the time of sale.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5336-S.SL.pdf?cite=2007%20c%20156%20§%2018[2007 c 156 § 18]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2096[2005 c 365 § 96]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2016[1979 c 21 § 16]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2098[1943 c 247 § 98]; Rem. Supp. 1943 § 3778-98; ]

== 68.32.070 - Joint tenants—Vested rights.
In a conveyance to two or more persons as joint tenants each joint tenant has a vested right of placement in the plot or right of interment conveyed.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2097[2005 c 365 § 97]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2094[1943 c 247 § 94]; Rem. Supp. 1943 § 3778-94; ]

== 68.32.080 - Joint tenants—Survivorship.
Upon the death of a joint tenant, the title to the plot or right of interment held in joint tenancy immediately vests in the survivors, subject to the vested right of interment of the deceased joint tenant.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2098[2005 c 365 § 98]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2095[1943 c 247 § 95]; Rem. Supp. 1943 § 3778-95; ]

== 68.32.090 - Joint tenants—Identification.
An affidavit by any person having knowledge of the fact of the death of one joint tenant and establishing the identity of the surviving joint tenants named in the deed to any plot or right of interment, when filed with the cemetery authority, is complete authorization to the cemetery authority to permit the use of the unoccupied portion of the plot or right of interment in accordance with the directions of the surviving joint tenants.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%2099[2005 c 365 § 99]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2096[1943 c 247 § 96]; Rem. Supp. 1943 § 3778-96; ]

== 68.32.100 - Co-owners may designate representative.
When there are several owners of a plot or right of interment, they may designate one or more persons to represent the plot or interment right and file written notice of designation with the cemetery authority. In the absence of such notice or of written objection to its so doing, the cemetery authority is not liable to any owner for permitting the placement in the plot or right of interment upon the request or direction of any co-owner of the plot or right of interment.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20100[2005 c 365 § 100]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2097[1943 c 247 § 97]; Rem. Supp. 1943 § 3778-97; ]

== 68.32.110 - Order of interment—General.
In a family plot one right of interment may be used for the owner's interment and one for the owner's surviving spouse or state registered domestic partner, if any. Any unoccupied spaces may then be used by the remaining parents and children of the deceased owner, if any, then to the spouse or state registered domestic partner of any child of the owner, then to the heirs at law of the owner, in the order of death.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5336-S.SL.pdf?cite=2007%20c%20156%20§%2019[2007 c 156 § 19]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20101[2005 c 365 § 101]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2099[1943 c 247 § 99]; Rem. Supp. 1943 § 3778-99; ]

== 68.32.130 - Waiver of right of placement.
Any surviving spouse, state registered domestic partner, parent, child, or heir having a right of placement in a family plot may waive such right in favor of any other relative, spouse, or state registered domestic partner of a relative of the deceased owner. Upon such a waiver, the remains of the person in whose favor the waiver is made may be placed in the plot.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5336-S.SL.pdf?cite=2007%20c%20156%20§%2020[2007 c 156 § 20]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20102[2005 c 365 § 102]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%20101[1943 c 247 § 101]; Rem. Supp. 1943 § 3778-101; ]

== 68.32.140 - Termination of vested right by waiver.
A vested right of placement may be waived and is terminated upon the placement elsewhere of the remains of the person in whom vested.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20103[2005 c 365 § 103]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%20102[1943 c 247 § 102]; Rem. Supp. 1943 § 3778-102; ]

== 68.32.150 - Limitations on vested rights.
No vested right of interment gives any person the right to have his or her remains interred in any interment space in which the remains of any deceased person having a prior vested right of interment have been interred. No vested right of interment gives any person the right to have the remains of more than one deceased person placed in a single space in violation of the rules and regulations of the cemetery in which the space is located.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20104[2005 c 365 § 104]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%20103[1943 c 247 § 103]; Rem. Supp. 1943 § 3778-103; ]

== 68.32.160 - Conveyance of plot or right of interment to cemetery authority, effect.
A cemetery authority may take and hold any plot or right of interment conveyed to it by the plot owner so that it will be nontransferable. Placements shall be restricted to the persons designated in the conveyance.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20105[2005 c 365 § 105]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%20104[1943 c 247 § 104]; Rem. Supp. 1943 § 3778-104; ]

== 68.32.170 - Exemption from inheritance tax.
Cemetery property passing to an individual by reason of the death of the owner is exempt from all inheritance taxes.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2092[1943 c 247 § 92]; Rem. Supp. 1943 § 3778-92; ]

