= 68.40 - Endowment and nonendowment care.
:toc:

== 68.40.010 - Cemetery authorities—Deposit in endowment care fund required.
A cemetery authority not exempt under this chapter shall deposit in an endowment care fund not less than the following amounts for plots or interment rights sold: Ten percent of the gross sales price for each grave, niche, or crypt.

In the event that a cemetery authority sells an interment right at a price that is less than its current list price, or gives away, bequeaths, or otherwise gives title to an interment right, the interment right shall be endowed at the rate at which it would normally be endowed.

The deposits shall be made not later than the twentieth day of the month following the final payment on the sale price. If a contract for interment rights is sold, pledged, or otherwise encumbered as security for a loan by the cemetery authority, the cemetery authority shall pay into the endowment care fund ten percent of the gross sales price of the interment right within twenty days of receipt of payment of the proceeds from such sale or loan.

Any cemetery hereafter established shall have deposited in an endowment care fund the sum of twenty-five thousand dollars before selling any interment right.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20111[2005 c 365 § 111]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2035[1987 c 331 § 35]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c53.pdf?cite=1984%20c%2053%20§%201[1984 c 53 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c133.pdf?cite=1961%20c%20133%20§%202[1961 c 133 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%204[1953 c 290 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%20118[1943 c 247 § 118]; Rem. Supp. 1943 § 3778-118; ]

== 68.40.025 - Nonendowed sections—Identification.
Cemeteries with nonendowed sections opened before July 1, 1987, shall only be required to endow sections opened after July 1, 1987. On the face of any contract, receipt, or deed used for sales of nonendowed interment rights shall be prominently displayed the words "Nonendowment section." All nonendowed sections shall be identified as such by posting of a legible sign containing the following phrase: "Nonendowment section."

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20112[2005 c 365 § 112]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2036[1987 c 331 § 36]; ]

== 68.40.040 - Endowment care fiscal reports—Review by plot owners.
A cemetery authority not exempt under this chapter shall file in its principal office for review by plot owners the previous seven fiscal years' endowment care reports as filed with the funeral and cemetery board in accordance with RCW 68.44.150.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2126-S.SL.pdf?cite=2009%20c%20102%20§%2014[2009 c 102 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2037[1987 c 331 § 37]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%207[1953 c 290 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%20122[1943 c 247 § 122]; Rem. Supp. 1943 § 3778-122; ]

== 68.40.060 - May accept property in trust—Application of income.
The cemetery authority of an endowment care cemetery may accept any property bequeathed, granted, or given to it in trust and may apply the income from such property to any or all of the following purposes:

. Improvement or embellishment of all or any part of the cemetery;

. Erection, renewal, repair, or preservation of any monument, fence, building, or other structure in the cemetery;

. Planting or cultivation of trees, shrubs, or plants in or around any part of the cemetery;

. Special care or ornamenting of any part of any interment right, section, or building in the cemetery; and

. Any purpose or use consistent with the purpose for which the cemetery was established or is maintained.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20113[2005 c 365 § 113]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2038[1987 c 331 § 38]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%208[1953 c 290 § 8]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%20129[1943 c 247 § 129]; Rem. Supp. 1943 § 3778-129; ]

== 68.40.085 - Representing fund as perpetual—Penalty.
It is a misdemeanor for any cemetery authority, its officers, employees, or agents, or a cemetery broker or salesperson to represent that an endowment care fund, or any other fund set up for maintaining care, is perpetual.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20311[2012 c 117 § 311]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%2024[1953 c 290 § 24]; ]

== 68.40.090 - Penalty.
Any person, partnership, corporation, association, or his or her or its agents or representatives who shall violate any of the provisions of this chapter or make any false statement appearing on any sign, contract, agreement, receipt, statement, literature, or other publication shall be guilty of a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20312[2012 c 117 § 312]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2039[1987 c 331 § 39]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%20125[1943 c 247 § 125]; Rem. Supp. 1943 § 3778-125; ]

== 68.40.095 - Certain cemeteries exempt from chapter.
This chapter does not apply to any cemetery controlled and operated by a coroner, county, city, town, or cemetery district.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2040[1987 c 331 § 40]; ]

== 68.40.100 - Only nonendowment care cemeteries now in existence are authorized.
After June 7, 1979, no nonendowment care cemetery may be established. However, any nonendowment care cemetery in existence on June 7, 1979, may continue to operate as a nonendowment care cemetery.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2018[1979 c 21 § 18]; ]

== 68.40.900 - Effective date—1987 c 331.
See RCW 68.05.900.

[ ]

