= 68.46 - Prearrangement contracts.
:toc:

== 68.46.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Board" means the funeral and cemetery board established under RCW 18.39.173 or its authorized representative.

. "Cemetery merchandise or services" and "merchandise or services" mean those services normally performed by cemetery authorities, including the sale of monuments, markers, memorials, nameplates, liners, vaults, boxes, urns, vases, interment services, or any one or more of them.

. "Prearrangement contract" means a contract for purchase of cemetery merchandise or services, unconstructed crypts or niches, or undeveloped graves to be furnished at a future date for a specific consideration which is paid in advance by one or more payments in one sum or by installment payments.

. "Prearrangement trust fund" means all funds required to be maintained in one or more funds for the benefit of beneficiaries by either this chapter or by the terms of a prearrangement contract, as herein defined.

. "Undeveloped grave" means any grave in an area which a cemetery authority has not landscaped, groomed, or developed to the extent customary in the cemetery industry.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2126-S.SL.pdf?cite=2009%20c%20102%20§%2017[2009 c 102 § 17]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20125[2005 c 365 § 125]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2022[1979 c 21 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c55.pdf?cite=1975%201st%20ex.s.%20c%2055%20§%201[1975 1st ex.s. c 55 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c68.pdf?cite=1973%201st%20ex.s.%20c%2068%20§%201[1973 1st ex.s. c 68 § 1]; ]

== 68.46.020 - Prearrangement trust funds—Required.
Any cemetery authority selling by prearrangement contracts any merchandise or services shall establish and maintain one or more prearrangement trust funds for the benefit of beneficiaries of prearrangement contracts.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20126[2005 c 365 § 126]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c68.pdf?cite=1973%201st%20ex.s.%20c%2068%20§%202[1973 1st ex.s. c 68 § 2]; ]

== 68.46.030 - Prearrangement trust funds—Deposits—Bond requirements.
. For each prearrangement contract, a cemetery authority shall deposit the greater of the following amounts in its prearrangement trust fund:

.. For merchandise:

... Fifty percent of the contract price; or

... The wholesale cost of the item.

.. For services:

... Fifty percent of the contract price; or

... The direct cost of providing the service.

. Any cemetery authority which does not file and maintain with the board a bond as provided in subsection (4) of this section shall deposit in its prearrangement trust fund an amount as determined under subsection (1) of this section, excluding sales tax and endowment care if such charge is made.

. Any cemetery authority which files and maintains with the board a bond as provided in subsection (4) of this section may retain the nontrustable portion of the contract before depositing the balance of payments into its prearrangement trust fund, as determined under subsection (1) of this section, excluding sales tax and endowment care, if such charge is made.

. Each cemetery authority electing to make payments to its prearrangement trust fund pursuant to subsection (3) of this section shall file and maintain with the board a bond, issued by a surety company authorized to do business in the state, in the amount by which the cemetery authority's contingent liability for refunds pursuant to RCW 68.46.060 exceeds the amount deposited in its prearrangement trust fund. The bond shall be conditioned that it is for the use and benefit of any person requesting a refund pursuant to RCW 68.46.060 if the cemetery authority does not promptly pay to the person the refund due pursuant to RCW 68.46.060. In addition to any other remedy, every person not promptly receiving the refund due pursuant to RCW 68.46.060 may sue the surety for the refund. The liability of the surety shall not exceed the amount of the bond. Termination or cancellation shall not be effective unless notice is delivered by the surety to the board at least thirty days prior to the date of termination or cancellation. The board shall immediately notify the cemetery authority affected by the termination or cancellation by certified mail, return receipt requested. The cemetery authority shall thereupon obtain another bond or make such other arrangement as may be satisfactory to the board to ensure its ability to make refunds pursuant to RCW 68.46.060.

. Deposits to the prearrangement trust fund shall be made not later than the twentieth day of each month following receipt of each payment required to be deposited. If a prearrangement contract is sold, pledged, or otherwise encumbered as security for a loan by the cemetery authority, the cemetery authority shall pay into the prearrangement trust fund fifty percent of the total sale price of the prearrangement contract within twenty days of receipt of payment of the proceeds from the sale or loan.

. Any failure to fund a prearrangement contract as required by this section shall be grounds for disciplinary action against the cemetery authority and the cemetery authority's prearrangement sales license.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20127[2005 c 365 § 127]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c53.pdf?cite=1984%20c%2053%20§%203[1984 c 53 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2024[1979 c 21 § 24]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c68.pdf?cite=1973%201st%20ex.s.%20c%2068%20§%203[1973 1st ex.s. c 68 § 3]; ]

== 68.46.040 - Prearrangement trust funds—Deposit of funds.
. All prearrangement trust funds must be deposited in a commercial bank, trust company, mutual savings bank, savings and loan association, or credit union, whether state or federally chartered. Such accounts must be designated as the "prearrangement trust fund" by name and the particular cemetery authority for the benefit of the beneficiaries named in any prearrangement contract.

. All prearrangement trust funds must be invested in accordance with the provisions of RCW 11.100.020 subject to the following restrictions:

.. No officer or director of the cemetery authority, trustee of the prearrangement trust funds, or spouse, sibling, parent, grandparent, or issue of such officer, director, or trustee, may borrow any of such funds for himself or herself, directly or indirectly;

.. No funds may be loaned to the cemetery authority, its agents, or employees, or to any corporation, partnership, or other business entity in which the cemetery authority has any ownership interest; and

.. No funds may be invested with persons or business entities operating in a business field directly related to cemeteries.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/2360-S.SL.pdf?cite=2012%20c%20206%20§%201[2012 c 206 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20128[2005 c 365 § 128]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2050[1987 c 331 § 50]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c68.pdf?cite=1973%201st%20ex.s.%20c%2068%20§%204[1973 1st ex.s. c 68 § 4]; ]

== 68.46.050 - Withdrawals from trust funds—Notice of department of social and health services' claim.
. A depository of prearrangement funds shall permit a cemetery authority to withdraw all funds deposited under any specific prearrangement contract plus interest accrued thereon, under the following circumstances and conditions:

.. If the cemetery authority files a verified statement with the depository that the prearrangement merchandise and services covered by a contract have been furnished and delivered; or

.. If the cemetery authority files a verified statement that a specific prearrangement contract has been canceled in accordance with its terms.

. The department of social and health services shall notify the cemetery authority maintaining a prearrangement trust fund regulated by this chapter that the department has a claim on the estate of a beneficiary for long-term care services. Such notice shall be renewed at least every three years. The cemetery authority, upon becoming aware of the death of a beneficiary, shall give notice to the department of social and health services, office of financial recovery, who shall file any claim there may be within thirty days of the notice.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20129[2005 c 365 § 129]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1908-S2.SL.pdf?cite=1995%201st%20sp.s.%20c%2018%20§%2065[1995 1st sp.s. c 18 § 65]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c68.pdf?cite=1973%201st%20ex.s.%20c%2068%20§%205[1973 1st ex.s. c 68 § 5]; ]

== 68.46.055 - Indebtedness limitations.
No cemetery authority may enter into a retail contract for the purchase of debentures, shares, scrip, bonds, notes, or any instrument or evidence of indebtedness that requires the cemetery authority to furnish cemetery merchandise, services, or interment rights to the holder at a future date. This section does not include retail installment sales transactions governed by chapter 63.14 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20130[2005 c 365 § 130]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c53.pdf?cite=1984%20c%2053%20§%208[1984 c 53 § 8]; ]

== 68.46.060 - Termination of contract by purchaser or beneficiary.
Any purchaser or beneficiary may, upon written demand of any cemetery authority, demand that any prearrangement contract with such cemetery authority be terminated. In such event, the cemetery authority shall, within thirty days, refund to the purchaser or beneficiary fifty percent of the moneys received less the contractual price of any merchandise delivered or services performed before the termination plus interest earned. In any case, where, under a prearrangement contract there is more than one beneficiary, no written demand as provided in this section shall be honored by any cemetery authority unless the written demand provided for in this section shall bear the signatures of all of such beneficiaries.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20132[2005 c 365 § 132]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2051[1987 c 331 § 51]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c53.pdf?cite=1984%20c%2053%20§%204[1984 c 53 § 4]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2025[1979 c 21 § 25]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c68.pdf?cite=1973%201st%20ex.s.%20c%2068%20§%206[1973 1st ex.s. c 68 § 6]; ]

== 68.46.070 - Involuntary termination of contract—Refund.
Prearrangement contracts shall terminate upon demand of the purchaser of the contract if the cemetery authority shall go out of business, become insolvent or bankrupt, make an assignment for the benefit of creditors, or for any other reason be unable to fulfill the obligations under the contract. Upon demand by the purchaser or beneficiary or beneficiaries of any prearrangement contract, the cemetery authority shall refund one hundred percent of the original contract, less delivered services and merchandise, including funds held in deposit and interest earned thereon, unless otherwise ordered by a court of competent jurisdiction.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2052[1987 c 331 § 52]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2026[1979 c 21 § 26]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c68.pdf?cite=1973%201st%20ex.s.%20c%2068%20§%207[1973 1st ex.s. c 68 § 7]; ]

== 68.46.075 - Inactive contracts—Funds transfer—Obligations.
In the event the beneficiary of a prearrangement contract make[s] no claim within fifty years of the date of the contract for the merchandise and services provided in the prearrangement contract, the funds deposited in the prearrangement trust for that contract, plus interest, shall be transferred to the cemetery authority's endowment fund, to be used for the purposes for which the endowment fund was established. However, the cemetery authority shall remain obligated for merchandise and services, unconstructed crypts, niches, and undeveloped property under the terms of the prearrangement contract. Claims may be made for merchandise and services, unconstructed crypts, niches, and undeveloped property on a prearrangement contract after the funds have been transferred to the endowment fund. These claims shall be paid for from the endowment fund income on a contract by contract basis.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20133[2005 c 365 § 133]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2027[1979 c 21 § 27]; ]

== 68.46.080 - Other use of trust funds prohibited.
Prearrangement trust funds shall not be used in any way for the benefit of the cemetery authority or any director, officer, agent, or employee of any cemetery authority, including, but not limited to any encumbrance, pledge, or other utilization or prearrangement trust funds as collateral or other security.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20134[2005 c 365 § 134]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c68.pdf?cite=1973%201st%20ex.s.%20c%2068%20§%208[1973 1st ex.s. c 68 § 8]; ]

== 68.46.090 - Financial reports—Filing—Verification.
Any cemetery authority selling prearrangement merchandise or other prearrangement services shall file in its office and with the board a written report upon forms prepared by the board which shall state the amount of the principle of the prearrangement trust fund, the depository of such fund, and cash on hand which is or may be due to the fund as well as other information the board may deem appropriate. All information appearing on such written reports shall be revised at least annually. These reports shall be verified by the president, or the vice president, and one other officer of the cemetery authority, the accountant or auditor who prepared the report, and, if required by the board for good cause, a certified public accountant in accordance with generally accepted auditing standards.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2126-S.SL.pdf?cite=2009%20c%20102%20§%2018[2009 c 102 § 18]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20135[2005 c 365 § 135]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983c190.pdf?cite=1983%20c%20190%20§%201[1983 c 190 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977ex1c351.pdf?cite=1977%20ex.s.%20c%20351%20§%205[1977 ex.s. c 351 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c68.pdf?cite=1973%201st%20ex.s.%20c%2068%20§%209[1973 1st ex.s. c 68 § 9]; ]

== 68.46.100 - Prearrangement contract requirements.
Every prearrangement contract shall contain language which informs the purchaser of the prearrangement trust fund and the amount to be deposited in the prearrangement trust fund. The amount deposited to the prearrangement trust fund must meet the requirements of RCW 68.46.030.

Every prearrangement contract shall contain language prominently featured on the face of the contract disclosing to the purchaser what items will be delivered before need, either stored or installed, and thus not subject to funding or refund.

Every prearrangement contract for the sale of unconstructed crypts, niches, or undeveloped property shall contain language which informs the purchaser that sales of unconstructed or undeveloped property are subject to the provisions of RCW 68.46.030.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20136[2005 c 365 § 136]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2053[1987 c 331 § 53]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c53.pdf?cite=1984%20c%2053%20§%205[1984 c 53 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c68.pdf?cite=1973%201st%20ex.s.%20c%2068%20§%2010[1973 1st ex.s. c 68 § 10]; ]

== 68.46.110 - Compliance required.
No cemetery authority shall sell, offer to sell, or authorize the sale of cemetery merchandise or services or accept funds in payment of any prearrangement contract unless such acts are performed in compliance with this title and under the authority of a valid and unsuspended certificate of authority to operate a cemetery in this state.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20137[2005 c 365 § 137]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1973ex1c68.pdf?cite=1973%201st%20ex.s.%20c%2068%20§%2011[1973 1st ex.s. c 68 § 11]; ]

== 68.46.125 - Certain cemeteries exempt from chapter.
This chapter does not apply to any cemetery controlled and operated by a coroner, county, city, town, or cemetery district.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2054[1987 c 331 § 54]; ]

== 68.46.130 - Exemptions from chapter granted by board.
The board may grant an exemption from any or all of the requirements of this chapter relating to prearrangement contracts to any cemetery authority which:

. Sells less than twenty prearrangement contracts per year; and

. Deposits one hundred percent of all funds received into a trust fund under RCW 68.46.030, as now or hereafter amended.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2126-S.SL.pdf?cite=2009%20c%20102%20§%2019[2009 c 102 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2043[1979 c 21 § 43]; ]

== 68.46.160 - Contract forms—Filing.
No cemetery authority shall use a prearrangement contract without first filing the form of such contract with the board: PROVIDED, That the board may order the cemetery authority to cease using any prearrangement contract form which:

. Is in violation of any provision of this chapter;

. Is misleading or deceptive; or

. Is being used in connection with solicitation by false, misleading or deceptive advertising or sales practices.

Use of a prearrangement contract form which is not on file with the board or which the board has ordered the cemetery authority not to use shall be a violation of this chapter.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2038[1979 c 21 § 38]; ]

== 68.46.170 - Sales licenses—Requirement.
No cemetery authority shall enter into prearrangement contracts in this state unless the cemetery authority has obtained a prearrangement sales license issued by the board or its authorized representative and such license is then current and valid.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c21.pdf?cite=1979%20c%2021%20§%2023[1979 c 21 § 23]; ]

== 68.46.175 - Unconstructed crypts, etc., as part of contract—Requirements.
. A cemetery authority that enters into prearrangement contracts for the sale of unconstructed crypts, niches, or undeveloped property, or that conveys undeveloped property by gift, shall maintain an adequate inventory of constructed crypts or niches and developed property. The inventory shall be a minimum of ten percent of the unconstructed or undeveloped property sales. The inventory shall be equal or better in quality than the unconstructed crypts or niches, or undeveloped property if they were constructed or developed.

. If the death of a purchaser or owner of an unconstructed crypt, niche, or undeveloped property occurs before the property is constructed or developed, the cemetery authority shall provide a constructed crypt, niche, or developed property of equal or better quality without additional cost or charge.

. If two or more unconstructed crypts, niches, or undeveloped properties are conveyed with the intention that the crypts, niches, or properties shall be contiguous to each other or maintained together as a group and the death of any one purchaser or owner in such group occurs before the unconstructed crypts, niches, or undeveloped property is developed, the cemetery authority shall provide additional constructed crypts, niches, or developed property of equal or better quality, contiguous to each other or together as a group, as originally intended, to other purchasers or owners in the group without additional cost or charge.

. The representative of the deceased purchaser may agree to the placement of the decedent in a temporary crypt, niche, or grave until the construction is completed and the decedent is placed in the new crypt, niche, or grave.

. Prearrangement sales of unconstructed crypts, niches, or undeveloped property must meet the requirements of RCW 68.46.030.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20131[2005 c 365 § 131]; ]

== 68.46.900 - Effective date—1987 c 331.
See RCW 68.05.900.

[ ]

