= 68.50 - Human remains.
:toc:

== 68.50.010 - Coroner's jurisdiction over remains.
The jurisdiction of bodies of all deceased persons who come to their death suddenly when in apparent good health without medical attendance within the thirty-six hours preceding death; or where the circumstances of death indicate death was caused by unnatural or unlawful means; or where death occurs under suspicious circumstances; or where a coroner's autopsy or postmortem or coroner's inquest is to be held; or where death results from unknown or obscure causes, or where death occurs within one year following an accident; or where the death is caused by any violence whatsoever, or where death results from a known or suspected abortion; whether self-induced or otherwise; where death apparently results from drowning, hanging, burns, electrocution, gunshot wounds, stabs or cuts, lightning, starvation, radiation, exposure, alcoholism, narcotics or other addictions, tetanus, strangulations, suffocation or smothering; or where death is due to premature birth or still birth; or where death is due to a violent contagious disease or suspected contagious disease which may be a public health hazard; or where death results from alleged rape, carnal knowledge or sodomy, where death occurs in a jail or prison; where a body is found dead or is not claimed by relatives or friends, is hereby vested in the county coroner or medical examiner, which bodies may be removed and placed in the morgue under such rules as are adopted by the coroner or medical examiner with the approval of the county commissioners, having jurisdiction, providing therein how the bodies shall be brought to and cared for at the morgue and held for the proper identification where necessary.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1326-S.SL.pdf?cite=2021%20c%20127%20§%207[2021 c 127 § 7]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c178.pdf?cite=1963%20c%20178%20§%201[1963 c 178 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c188.pdf?cite=1953%20c%20188%20§%201[1953 c 188 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c90.pdf?cite=1917%20c%2090%20§%203[1917 c 90 § 3]; RRS § 6042; ]

== 68.50.015 - Immunity for determining cause and manner of death—Judicial review of determination.
A county coroner or county medical examiner or persons acting in that capacity shall be immune from civil liability for determining the cause and manner of death. The accuracy of the determinations is subject to judicial review.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c263.pdf?cite=1987%20c%20263%20§%201[1987 c 263 § 1]; ]

== 68.50.020 - Notice to coroner or medical examiner—Penalty.
It shall be the duty of every person who knows of the existence and location of human remains coming under the jurisdiction of the coroner or medical examiner as set forth in RCW 68.50.010 or 27.44.055, to notify the coroner, medical examiner, or law enforcement thereof in the most expeditious manner possible, unless such person shall have good reason to believe that such notice has already been given. Any person knowing of the existence of such human remains and not having good reason to believe that the coroner has notice thereof and who shall fail to give notice to the coroner as aforesaid, shall be guilty of a misdemeanor. For purposes of this section and unless the context clearly requires otherwise, "human remains" has the same meaning as defined in RCW 68.04.020. Human remains also includes, but is not limited to, skeletal remains.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6261-S.SL.pdf?cite=2016%20c%20221%20§%202[2016 c 221 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2055[1987 c 331 § 55]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c90.pdf?cite=1917%20c%2090%20§%204[1917 c 90 § 4]; RRS § 6043; ]

== 68.50.032 - Transportation of remains directed by coroner or medical examiner—Costs.
Whenever a coroner or medical examiner assumes jurisdiction over human remains and directs transportation of those remains by a funeral establishment, as defined in RCW 18.39.010, the reasonable costs of transporting shall be borne by the county if: (1) The funeral establishment transporting the remains is not providing the funeral or disposition services; or (2) the funeral establishment providing the funeral or disposition services is required to transport the remains to a facility other than its own.

Except as provided in RCW 36.39.030, 68.52.030, and 73.08.070, any transportation costs or other costs incurred after the coroner or medical examiner has released jurisdiction over the human remains shall not be borne by the county.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/1032.SL.pdf?cite=1991%20c%20176%20§%201[1991 c 176 § 1]; ]

== 68.50.035 - Unlawful to refuse burial to non-Caucasian.
It shall be unlawful for any cemetery under this chapter to refuse burial to any person because such person may not be of the Caucasian race.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c290.pdf?cite=1953%20c%20290%20§%2053[1953 c 290 § 53]; ]

== 68.50.040 - Deceased's effects to be listed.
All jewelry, moneys, papers, and other personal property of the deceased shall be inventoried immediately upon being taken into custody by the coroner or his or her appointees. The original of such lists shall be certified to by the coroner and kept as a public record at the county morgue.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/Senate/5187.SL.pdf?cite=2017%20c%2037%20§%205[2017 c 37 § 5]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20314[2012 c 117 § 314]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c90.pdf?cite=1917%20c%2090%20§%206[1917 c 90 § 6]; RRS § 6045; ]

== 68.50.050 - Removal or concealment of body—Penalty.
. Any person, not authorized or directed by the coroner or medical examiner or their deputies, who removes the body of a deceased person not claimed by a relative or friend, or moves, disturbs, molests, or interferes with the human remains coming within the jurisdiction of the coroner or medical examiner as set forth in RCW 68.50.010, to any undertaking rooms or elsewhere, or any person who knowingly directs, aids, or abets such unauthorized moving, disturbing, molesting, or taking, and any person who knowingly conceals the human remains, shall in each of said cases be guilty of a gross misdemeanor.

. In evaluating whether it is necessary to retain jurisdiction and custody of human remains under RCW 68.50.010, 68.50.645, and 27.44.055, the coroner or medical examiner shall consider the deceased's religious beliefs, if known, including the tenets, customs, or rites related to death and burial.

. For purposes of this section and unless the context clearly requires otherwise, "human remains" has the same meaning as defined in RCW 68.04.020. Human remains also includes, but is not limited to, skeletal remains.

[ http://lawfilesext.leg.wa.gov/biennium/2015-16/Pdf/Bills/Session%20Laws/Senate/6261-S.SL.pdf?cite=2016%20c%20221%20§%201[2016 c 221 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5168-S.SL.pdf?cite=2011%20c%2096%20§%2048[2011 c 96 § 48]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1917c90.pdf?cite=1917%20c%2090%20§%207[1917 c 90 § 7]; RRS § 6046; ]

== 68.50.060 - Bodies for instruction purposes.
Any physician or surgeon of this state, or any medical student under the authority of any such physician or surgeon, may obtain, as hereinafter provided, and have in his or her possession human dead bodies, or the parts thereof, for the purposes of anatomical inquiry or instruction.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20315[2012 c 117 § 315]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c123.pdf?cite=1891%20c%20123%20§%201[1891 c 123 § 1]; RRS § 10026; ]

== 68.50.070 - Human remains—Disposition.
. Any public agency required to provide for the disposition of human remains in any legal manner at public expense must surrender the human remains to:

.. Any physician or surgeon, to be used for the advancement of anatomical science, preference being given to medical schools in this state, for their use in the instruction of medical students; or

.. An accredited educational institution offering funeral services and embalming programs for use in training embalming students under the supervision of an embalmer licensed under chapter 18.39 RCW.

. If the deceased person requested to be buried, or if some person claiming to be a relative or a responsible officer of a religious organization with which the deceased at the time of death was affiliated requires the remains to be buried, the remains must be buried, subject to the requirements of RCW 68.50.110 and 68.50.230.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1691-S.SL.pdf?cite=2011%20c%20265%20§%201[2011 c 265 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c23.pdf?cite=1959%20c%2023%20§%201[1959 c 23 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c224.pdf?cite=1953%20c%20224%20§%202[1953 c 224 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c123.pdf?cite=1891%20c%20123%20§%202[1891 c 123 § 2]; RRS § 10027; ]

== 68.50.080 - Certificate and bond before receiving bodies.
Every physician or surgeon before receiving the dead body must give to the board or officer surrendering the same to him or her a certificate from the medical society of the county in which he or she resides, or if there is none, from the board of supervisors of the same, that he or she is a fit person to receive such dead body. He or she must also give a bond with two sureties, that each body so by him or her received will be used only for the promotion of anatomical science, and that it will be used for such purpose in this state only, and so as in no event to outrage the public feeling.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20316[2012 c 117 § 316]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c123.pdf?cite=1891%20c%20123%20§%203[1891 c 123 § 3]; RRS § 10028; ]

== 68.50.090 - Penalty.
Any person violating any provision of RCW 68.50.060 through 68.50.080 shall upon conviction thereof be fined in any sum not exceeding five hundred dollars.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2056[1987 c 331 § 56]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1891c123.pdf?cite=1891%20c%20123%20§%204[1891 c 123 § 4]; RRS § 10029; ]

== 68.50.100 - Dissection, when permitted—Autopsy of person under the age of three years.
. The right to dissect a dead body shall be limited to cases specially provided by statute or by the direction or will of the deceased; cases where a coroner is authorized to hold an inquest upon the body, and then only as he or she may authorize dissection; and cases where the spouse, state registered domestic partner, or next of kin charged by law with the duty of burial shall authorize dissection for the purpose of ascertaining the cause of death, and then only to the extent so authorized: PROVIDED, That the coroner, in his or her discretion, may make or cause to be made by a competent pathologist, toxicologist, or physician, an autopsy or postmortem in any case in which the coroner has jurisdiction of a body: PROVIDED, FURTHER, That the coroner may with the approval of the University of Washington and with the consent of a parent or guardian deliver any body of a deceased person under the age of three years over which he or she has jurisdiction to the University of Washington medical school for the purpose of having an autopsy made to determine the cause of death.

. Every person who shall make, cause, or procure to be made any dissection of a body, except as provided in this section, is guilty of a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5336-S.SL.pdf?cite=2007%20c%20156%20§%2021[2007 c 156 § 21]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20307[2003 c 53 § 307]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c178.pdf?cite=1963%20c%20178%20§%202[1963 c 178 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c188.pdf?cite=1953%20c%20188%20§%202[1953 c 188 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20237[1909 c 249 § 237]; RRS § 2489; ]

== 68.50.101 - Autopsy, postmortem—Who may authorize.
Autopsy or postmortem may be performed in any case where authorization has been given by a member of one of the following classes of persons in the following order of priority:

. The surviving spouse or state registered domestic partner;

. Any child of the decedent who is eighteen years of age or older;

. One of the parents of the decedent;

. Any adult brother or sister of the decedent;

. A person who was guardian of the decedent at the time of death;

. Any other person or agency authorized or under an obligation to dispose of the remains of the decedent. The chief official of any such agency shall designate one or more persons to execute authorizations pursuant to the provisions of this section.

If the person seeking authority to perform an autopsy or postmortem makes reasonable efforts to locate and secure authorization from a competent person in the first or succeeding class and finds no such person available, authorization may be given by any person in the next class, in the order of descending priority. However, no person under this section shall have the power to authorize an autopsy or postmortem if a person of higher priority under this section has refused such authorization: PROVIDED, That this section shall not affect autopsies performed pursuant to RCW 68.50.010 or 68.50.103.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5336-S.SL.pdf?cite=2007%20c%20156%20§%2022[2007 c 156 § 22]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2057[1987 c 331 § 57]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977c79.pdf?cite=1977%20c%2079%20§%201[1977 c 79 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c188.pdf?cite=1953%20c%20188%20§%2011[1953 c 188 § 11]; ]

== 68.50.102 - Court petition for autopsy—Cost.
Any party by showing just cause may petition the court to have autopsy made and results thereof made known to said party at his or her own expense.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20317[2012 c 117 § 317]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c188.pdf?cite=1953%20c%20188%20§%2012[1953 c 188 § 12]; ]

== 68.50.103 - Autopsies in industrial deaths.
In an industrial death where the cause of death is unknown, and where the department of labor and industries is concerned, said department in its discretion, may request the coroner in writing to perform an autopsy to determine the cause of death. The coroner shall be required to promptly perform such autopsy upon receipt of the written request from the department of labor and industries.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c188.pdf?cite=1953%20c%20188%20§%206[1953 c 188 § 6]; ]

== 68.50.104 - Cost of autopsy.
. The cost of autopsy shall be borne by the county in which the autopsy is performed, except when requested by the department of labor and industries, in which case, the department shall bear the cost of such autopsy.

. [Empty]
.. Except as provided in (b) of this subsection, when the county bears the cost of an autopsy, it shall be reimbursed from the death investigations account, established by RCW 43.79.445, as follows:

... Up to forty percent of the cost of contracting for the services of a pathologist to perform an autopsy;

... Up to 30 percent of the salary of pathologists who are primarily engaged in performing autopsies and are (A) county coroners or county medical examiners, or (B) employees of a county coroner or county medical examiner; and

... One hundred percent of the cost of autopsies conducted under RCW 70.54.450.

.. When the county bears the cost of an autopsy of a child under the age of three whose death was sudden and unexplained, the county shall be reimbursed for the expenses of the autopsy when the death scene investigation and the autopsy have been conducted under RCW 43.103.100 (4) and (5), and the autopsy has been done at a facility designed for the performance of autopsies.

. Payments from the account shall be made pursuant to biennial appropriation: PROVIDED, That no county may reduce funds appropriated for this purpose below 1983 budgeted levels.

. Where the county coroner's office or county medical examiner's office is not accredited pursuant to RCW 36.24.210, or a coroner, medical examiner, or other medicolegal investigative employee is not certified as required by RCW 36.24.205 and 43.101.480, the state treasurer's office shall withhold 25 percent of autopsy reimbursement funds until accreditation under RCW 36.24.210 or compliance with RCW 36.24.205 and 43.101.480 is achieved.

[ http://lawfilesext.leg.wa.gov/biennium/2021-22/Pdf/Bills/Session%20Laws/House/1326-S.SL.pdf?cite=2021%20c%20127%20§%208[2021 c 127 § 8]; http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5425-S.SL.pdf?cite=2019%20c%20317%20§%204[2019 c 317 § 4]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1216.SL.pdf?cite=2001%20c%2082%20§%202[2001 c 82 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c16.pdf?cite=1983%201st%20ex.s.%20c%2016%20§%2014[1983 1st ex.s. c 16 § 14]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1963c178.pdf?cite=1963%20c%20178%20§%203[1963 c 178 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c188.pdf?cite=1953%20c%20188%20§%207[1953 c 188 § 7]; ]

== 68.50.105 - Autopsies, postmortems—Reports and records confidential—Exceptions.
. Reports and records of autopsies or postmortems shall be confidential, except that the following persons may examine and obtain copies of any such report or record: The personal representative of the decedent as defined in RCW 11.02.005, any family member, the attending physician or advanced registered nurse practitioner, the prosecuting attorney or law enforcement agencies having jurisdiction, public health officials, the department of labor and industries in cases in which it has an interest under RCW 68.50.103, or the secretary of the department of children, youth, and families or his or her designee in cases being reviewed under RCW 74.13.640.

. [Empty]
.. Notwithstanding the restrictions contained in this section regarding the dissemination of records and reports of autopsies or postmortems, nor the exemptions referenced under RCW 42.56.240(1), nothing in this chapter prohibits a coroner, medical examiner, or his or her designee, from publicly discussing his or her findings as to any death subject to the jurisdiction of his or her office where actions of a law enforcement officer or corrections officer have been determined to be a proximate cause of the death, except as provided in (b) of this subsection.

.. A coroner, medical examiner, or his or her designee may not publicly discuss his or her findings outside of formal court or inquest proceedings if there is a pending or active criminal investigation, or a criminal or civil action, concerning a death that has commenced prior to January 1, 2014.

. The coroner, the medical examiner, or the attending physician shall, upon request, meet with the family of the decedent to discuss the findings of the autopsy or postmortem. For the purposes of this section, the term "family" means the surviving spouse, state registered domestic partner, or any child, parent, grandparent, grandchild, brother, or sister of the decedent, or any person who was guardian of the decedent at the time of death.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5955-S.SL.pdf?cite=2019%20c%20470%20§%2014[2019 c 470 § 14]; http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5256-S.SL.pdf?cite=2013%20c%20295%20§%201[2013 c 295 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1105-S.SL.pdf?cite=2011%20c%2061%20§%201[2011 c 61 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2209-S.SL.pdf?cite=2007%20c%20439%20§%201[2007 c 439 § 1]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5336-S.SL.pdf?cite=2007%20c%20156%20§%2023[2007 c 156 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2058[1987 c 331 § 58]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c300.pdf?cite=1985%20c%20300%20§%201[1985 c 300 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977c79.pdf?cite=1977%20c%2079%20§%202[1977 c 79 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c188.pdf?cite=1953%20c%20188%20§%209[1953 c 188 § 9]; ]

== 68.50.106 - Autopsies, postmortems—Analyses—Opinions—Evidence—Costs.
In any case in which an autopsy or postmortem is performed, the coroner or medical examiner, upon his or her own authority or upon the request of the prosecuting attorney or other law enforcement agency having jurisdiction, may make or cause to be made an analysis of the stomach contents, blood, or organs, or tissues of a deceased person and secure professional opinions thereon and retain or dispose of any specimens or organs of the deceased which in his or her discretion are desirable or needful for anatomic, bacteriological, chemical, or toxicological examination or upon lawful request are needed or desired for evidence to be presented in court. Costs shall be borne by the county.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1012-S.SL.pdf?cite=1993%20c%20228%20§%2019[1993 c 228 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2059[1987 c 331 § 59]; 1975-'76 2nd ex.s. c 28 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c188.pdf?cite=1953%20c%20188%20§%2010[1953 c 188 § 10]; ]

== 68.50.107 - State toxicological laboratory established—State toxicologist.
There shall be established in conjunction with the chief of the Washington state patrol and under the authority of the state forensic investigations council a state toxicological laboratory under the direction of the state toxicologist whose duty it will be to perform all necessary toxicologic procedures requested by all coroners, medical examiners, and prosecuting attorneys. The state forensic investigations council, after consulting with the chief of the Washington state patrol and director of the bureau of forensic laboratory services, shall appoint a toxicologist as state toxicologist, who shall report to the director of the bureau of forensic laboratory services and the office of the chief of the Washington state patrol. Toxicological services shall be funded by disbursement from the spirits, beer, and wine restaurant; spirits, beer, and wine private club; spirits, beer, and wine nightclub; spirits, beer, and wine VIP airport lounge; and sports entertainment facility license fees as provided in RCW 66.08.180 and by appropriation from the death investigations account as provided in RCW 43.79.445.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/5156-S.SL.pdf?cite=2011%20c%20325%20§%209[2011 c 325 § 9]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5367-S.SL.pdf?cite=2009%20c%20271%20§%2011[2009 c 271 § 11]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/Senate/5364-S.SL.pdf?cite=1999%20c%20281%20§%2013[1999 c 281 § 13]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1560-S.SL.pdf?cite=1999%20c%2040%20§%208[1999 c 40 § 8]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/Senate/5977-S.SL.pdf?cite=1995%20c%20398%20§%2010[1995 c 398 § 10]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1986c87.pdf?cite=1986%20c%2087%20§%202[1986 c 87 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c16.pdf?cite=1983%201st%20ex.s.%20c%2016%20§%2010[1983 1st ex.s. c 16 § 10]; 1975-'76 2nd ex.s. c 84 § 1; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1970ex1c24.pdf?cite=1970%20ex.s.%20c%2024%20§%201[1970 ex.s. c 24 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c188.pdf?cite=1953%20c%20188%20§%2013[1953 c 188 § 13]; ]

== 68.50.108 - Autopsies, postmortems—Consent to embalm, cremate body, or make final disposition—Time limitation.
No dead body upon which the coroner, or prosecuting attorney, if there is not a coroner in the county, may perform an autopsy or postmortem, may be embalmed or make final disposition without the consent of the coroner having jurisdiction. Failure to obtain such consent is a misdemeanor. However, such autopsy or postmortem must be performed within five days, unless the coroner obtains an order from the superior court extending such time.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5001-S.SL.pdf?cite=2019%20c%20432%20§%2019[2019 c 432 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1953c188.pdf?cite=1953%20c%20188%20§%208[1953 c 188 § 8]; ]

== 68.50.110 - Burial, cremation, alkaline hydrolysis, or natural organic reduction.
Except in cases of dissection provided for in RCW 68.50.100, and where human remains are rightfully carried through or removed from the state for the purpose of burial elsewhere, human remains lying within this state, and the remains of any dissected body, after dissection, must be decently buried, undergo cremation, alkaline hydrolysis, or natural organic reduction within a reasonable time after death.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5001-S.SL.pdf?cite=2019%20c%20432%20§%2020[2019 c 432 § 20]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20138[2005 c 365 § 138]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2060[1987 c 331 § 60]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20238[1909 c 249 § 238]; RRS § 2490; ]

== 68.50.115 - Coroner and medical examiner liability—Release of information.
No coroner, medical examiner, or his or her designee shall be liable, nor shall a cause of action exist, for any loss or damage based upon the release of any information related to his or her findings under RCW 68.50.105 if the coroner, medical examiner, or his or her designee acted in good faith in attempting to comply with the provisions of this chapter.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/5256-S.SL.pdf?cite=2013%20c%20295%20§%202[2013 c 295 § 2]; ]

== 68.50.120 - Holding body for debt—Penalty.
Every person who arrests, attaches, detains, or claims to detain any human remains for any debt or demand, or upon any pretended lien or charge, is guilty of a gross misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2027[1943 c 247 § 27]; Rem. Supp. 1943 § 3778-27; ]

== 68.50.130 - Unlawful disposal of remains.
Every person who performs a disposition of any human remains, except as otherwise provided by law, in any place, except in a cemetery or a building dedicated exclusively for religious purposes, is guilty of a misdemeanor. Disposition of human remains following cremation, alkaline hydrolysis, or natural organic reduction may also occur on private property, with the consent of the property owner; and on public or government lands or waters with the approval of the government agency that has either jurisdiction or control, or both, of the lands or waters.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5001-S.SL.pdf?cite=2019%20c%20432%20§%2021[2019 c 432 § 21]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20139[2005 c 365 § 139]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2028[1943 c 247 § 28]; Rem. Supp. 1943 § 3778-28; ]

== 68.50.140 - Unlawful disturbance, removal, or sale of human remains—Penalty.
. Every person who removes human remains, or any part thereof, from a grave, vault, or other place where the same has been buried or deposited awaiting final disposition, without authority of law, with intent to sell the same, or for the purpose of securing a reward for its return, or for dissection, or from malice or wantonness, is guilty of a class C felony.

. Every person who purchases or receives, except for burial or final disposition, human remains or any part thereof, knowing that the same has been removed contrary to the foregoing provisions, is guilty of a class C felony.

. Every person who opens a grave or other place of interment, temporary or otherwise, or a building where human remains are placed, with intent to sell or remove the casket, urn, or of any part thereof, or anything attached thereto, or any vestment, or other article interred, or intended to be interred with the human remains, is guilty of a class C felony.

. Every person who removes, disinters, or mutilates human remains from a place of interment, without authority of law, is guilty of a class C felony.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5001-S.SL.pdf?cite=2019%20c%20432%20§%2022[2019 c 432 § 22]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20140[2005 c 365 § 140]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20308[2003 c 53 § 308]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2263-S.SL.pdf?cite=1992%20c%207%20§%2044[1992 c 7 § 44]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1909c249.pdf?cite=1909%20c%20249%20§%20239[1909 c 249 § 239]; RRS § 2491. FORMER PART OF SECTION: 1943 c 247 § 25 now codified as RCW  68.50.145; ]

== 68.50.160 - Right to control disposition of remains—Liability of funeral establishment or cemetery authority—Liability for cost.
. A person has the right to control the disposition of his or her own remains without the predeath or postdeath consent of another person. A valid written document expressing the decedent's wishes regarding the place or method of disposition of his or her remains, signed by the decedent in the presence of a witness, is sufficient legal authorization for the procedures to be accomplished.

. Prearrangements that are prepaid, or filed with a licensed funeral establishment or cemetery authority, under RCW 18.39.280 through 18.39.345 and chapter 68.46 RCW are not subject to cancellation or substantial revision by survivors. Absent actual knowledge of contrary legal authorization under this section, a licensed funeral establishment or cemetery authority may not be held criminally nor civilly liable for acting upon such prearrangements.

. If the decedent has not made a prearrangement as set forth in subsection (2) of this section or the costs of executing the decedent's wishes regarding the disposition of the decedent's remains exceeds a reasonable amount or directions have not been given by the decedent, the right to control the disposition of the remains of a deceased person vests in, and the duty of disposition and the liability for the reasonable cost of preparation, care, and disposition of such remains devolves upon the following in the order named:

.. The person designated by the decedent as authorized to direct disposition as listed on the decedent's United States department of defense record of emergency data, DD form 93, or its successor form, if the decedent died while serving in military service as described in 10 U.S.C. Sec. 1481(a) (1)-(8) in any branch of the United States armed forces, United States reserve forces, or national guard;

.. The designated agent of the decedent as directed through a written document signed and dated by the decedent in the presence of a witness. The direction of the designated agent is sufficient to direct the type, place, and method of disposition;

.. The surviving spouse or state registered domestic partner;

.. The majority of the surviving adult children of the decedent;

.. The surviving parents of the decedent;

.. The majority of the surviving siblings of the decedent;

.. A court-appointed guardian for the person at the time of the person's death.

. If any person to whom the right of control has vested pursuant to subsection (3) of this section has been arrested or charged with first or second degree murder or first degree manslaughter in connection with the decedent's death, the right of control is relinquished and passed on in accordance with subsection (3) of this section.

. If a cemetery authority as defined in RCW 68.04.190 or a funeral establishment licensed under chapter 18.39 RCW has made a good faith effort to locate the person cited in subsection (3)(a) through (g) of this section or the legal representative of the decedent's estate, the cemetery authority or funeral establishment has the right to rely on an authority to bury or make final disposition of the human remains, executed by the most responsible party available, and the cemetery authority or funeral establishment may not be held criminally or civilly liable for burying or performing final disposition of the human remains. In the event any government agency or charitable organization provides the funds for the disposition of any human remains, the cemetery authority, alkaline hydrolysis, natural organic reduction facility, or funeral establishment may not be held criminally or civilly liable for making final disposition of the human remains.

. The liability for the reasonable cost of preparation, care, and disposition devolves jointly and severally upon all kin of the decedent in the same degree of kindred, in the order listed in subsection (3) of this section, and upon the estate of the decedent.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5001-S.SL.pdf?cite=2019%20c%20432%20§%2023[2019 c 432 § 23]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1073-S.SL.pdf?cite=2012%20c%205%20§%201[2012 c 5 § 1]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/House/1691-S.SL.pdf?cite=2011%20c%20265%20§%202[2011 c 265 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2777-S.SL.pdf?cite=2010%20c%20274%20§%20602[2010 c 274 § 602]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5336-S.SL.pdf?cite=2007%20c%20156%20§%2024[2007 c 156 § 24]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20141[2005 c 365 § 141]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1195-S.SL.pdf?cite=1993%20c%20297%20§%201[1993 c 297 § 1]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/House/2874-S.SL.pdf?cite=1992%20c%20108%20§%201[1992 c 108 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2029[1943 c 247 § 29]; Rem. Supp. 1943 § 3778-29; ]

== 68.50.170 - Effect of authorization.
Any person signing any authorization for the interment, cremation, alkaline hydrolysis, or natural organic reduction of any human remains warrants the truthfulness of any fact set forth in the authorization, the identity of the person whose human remains are sought to undergo final disposition, and his or her authority to order such. That person is personally liable for all damage occasioned by or resulting from breach of such warranty.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5001-S.SL.pdf?cite=2019%20c%20432%20§%2024[2019 c 432 § 24]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20142[2005 c 365 § 142]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2030[1943 c 247 § 30]; Rem. Supp. 1943 § 3778-30; ]

== 68.50.185 - Individual final disposition—Exception—Penalty.
. A person authorized to dispose of human remains may not perform or cause to be performed final disposition of more than one human remains at a time unless written permission, after full and adequate disclosure regarding the manner of disposition, has been received from the person or persons under RCW 68.50.160 having the authority to order final disposition. This restriction does not apply when equipment, techniques, or devices are employed that keep human remains separate and distinct before, during, and after the final disposition process.

. Violation of this section is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5001-S.SL.pdf?cite=2019%20c%20432%20§%2025[2019 c 432 § 25]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20143[2005 c 365 § 143]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2061[1987 c 331 § 61]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c402.pdf?cite=1985%20c%20402%20§%203[1985 c 402 § 3]; ]

== 68.50.200 - Permission to remove human remains.
Human remains may be removed from a plot in a cemetery with the consent of the cemetery authority and the written consent of one of the following in the order named:

. The surviving spouse or state registered domestic partner.

. The surviving children of the decedent.

. The surviving parents of the decedent.

. The surviving brothers or sisters of the decedent.

If the required consent cannot be obtained, permission by the superior court of the county where the cemetery is situated is sufficient: PROVIDED, That the permission shall not violate the terms of a written contract or the rules and regulations of the cemetery authority.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5336-S.SL.pdf?cite=2007%20c%20156%20§%2025[2007 c 156 § 25]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20144[2005 c 365 § 144]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2033[1943 c 247 § 33]; Rem. Supp. 1943 § 3778-33; ]

== 68.50.210 - Notice for order to remove remains.
Notice of application to the court for such permission shall be given, at least ten days prior thereto, personally, or at least fifteen days prior thereto if by mail, to the cemetery authority and to the persons not consenting, and to every other person on whom service of notice may be required by the court.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2034[1943 c 247 § 34]; Rem. Supp. 1943 § 3778-34; ]

== 68.50.220 - Exceptions.
RCW 68.50.200 and 68.50.210 do not apply to or prohibit the removal of any human remains from one plot to another in the same cemetery or the removal of [human] remains by a cemetery authority from a plot for which the purchase price is past due and unpaid, to some other suitable place; nor do they apply to the disinterment of human remains upon order of court or coroner. However, a cemetery authority shall provide notification to the person cited in RCW 68.50.200 before moving human remains.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20145[2005 c 365 § 145]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2062[1987 c 331 § 62]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2035[1943 c 247 § 35]; Rem. Supp. 1943 § 3778-35; ]

== 68.50.230 - Human remains that have not been disposed—Rules.
. Whenever any human remains shall have been in the lawful possession of any person, firm, corporation, or association for a period of ninety days or more, and the relatives of, or persons interested in, the deceased person shall fail, neglect, or refuse to direct the disposition, the human remains may be disposed of by the person, firm, corporation, or association having such lawful possession thereof, under and in accordance with rules adopted by the funeral and cemetery board, not inconsistent with any statute of the state of Washington or rule adopted by the state board of health.

. [Empty]
.. The department of veterans affairs may certify that the deceased person to whom subsection (1) of this section applies was a veteran or the dependent of a veteran eligible for interment at a federal or state veterans' cemetery.

.. Upon certification of eligible veteran or dependent of a veteran status under (a) of this subsection, the person, firm, corporation, or association in possession of the veteran's or veteran's dependent's remains shall transfer the custody and control of the remains to the department of veterans affairs.

.. The transfer of human remains under (b) of this subsection does not create:

... A private right of action against the state or its officers and employees or instrumentalities, or against any person, firm, corporation, or association transferring the remains; or

... Liability on behalf of the state, the state's officers, employees, or instrumentalities; or on behalf of the person, firm, corporation, or association transferring the remains.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2126-S.SL.pdf?cite=2009%20c%20102%20§%2020[2009 c 102 § 20]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/Senate/5481-S.SL.pdf?cite=2009%20c%2056%20§%201[2009 c 56 § 1]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20146[2005 c 365 § 146]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1985c402.pdf?cite=1985%20c%20402%20§%209[1985 c 402 § 9]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1979c158.pdf?cite=1979%20c%20158%20§%20218[1979 c 158 § 218]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1937c108.pdf?cite=1937%20c%20108%20§%2014[1937 c 108 § 14]; RRS § 8323-3; ]

== 68.50.232 - Remains—Entrusting to funeral homes or mortuaries.
See RCW 36.24.155.

[ ]

== 68.50.240 - Record of human remains to be kept.
The person in charge of any premises on which final dispositions are made must keep a record of all human remains on the premises under his or her charge, in each case stating the name of each deceased person, date of final disposition, and name and address of the funeral establishment.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5001-S.SL.pdf?cite=2019%20c%20432%20§%2026[2019 c 432 § 26]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20147[2005 c 365 § 147]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2039[1943 c 247 § 39]; Rem. Supp. 1943 § 3778-39; ]

== 68.50.270 - Possession of human remains.
The person or persons determined under RCW 68.50.160 as having authority to order disposition is entitled to possession of the human remains without further intervention by the state or its political subdivisions.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5001-S.SL.pdf?cite=2019%20c%20432%20§%2027[2019 c 432 § 27]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20148[2005 c 365 § 148]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2063[1987 c 331 § 63]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1977c47.pdf?cite=1977%20c%2047%20§%204[1977 c 47 § 4]; ]

== 68.50.290 - Corneal tissue for transplantation—Presumption of good faith.
In any subsequent civil action in which the next of kin of a decedent contends that he/she affirmatively informed the county coroner or medical examiner or designee of his/her objection to removal of corneal tissue from the decedent, it shall be presumed that the county coroner or medical examiner acted in good faith and without knowledge of the objection.

[ 1975-'76 2nd ex.s. c 60 § 2; ]

== 68.50.300 - Release of information concerning a death.
. The county coroner, medical examiner, or prosecuting attorney having jurisdiction may in such official's discretion release information concerning a person's death to the media and general public, in order to aid in identifying the deceased, when the identity of the deceased is unknown to the official and when he or she does not know the information to be readily available through other sources.

. [Empty]
.. The county coroner, medical examiner, or prosecuting attorney may withhold any information which directly or indirectly identifies a decedent until either:

... A notification period of forty-eight hours has elapsed after identification of the decedent by such official; or

... The next of kin of the decedent has been notified.

.. During the forty-eight hour notification period, such official shall make a good faith attempt to locate and notify the next of kin of the decedent.

. The county coroner, medical examiner, or prosecuting attorney having jurisdiction may release information contained in a report of death, as defined in chapter 70.58A RCW, to the media and general public.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5332-S.SL.pdf?cite=2019%20c%20148%20§%2037[2019 c 148 § 37]; http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20318[2012 c 117 § 318]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1981c176.pdf?cite=1981%20c%20176%20§%202[1981 c 176 § 2]; ]

== 68.50.310 - Dental identification system established—Powers and duties.
A dental identification system is established in the identification section of the Washington state patrol. The dental identification system shall act as a repository or computer center or both for dental examination records and it shall be responsible for comparing such records with dental records filed under RCW 68.50.330. It shall also determine which scoring probabilities are the highest for purposes of identification and shall submit such information to the coroner or medical examiner who prepared and forwarded the dental examination records. Once the dental identification system is established, operating funds shall come from the state general fund.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1987c331.pdf?cite=1987%20c%20331%20§%2065[1987 c 331 § 65]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c16.pdf?cite=1983%201st%20ex.s.%20c%2016%20§%2015[1983 1st ex.s. c 16 § 15]; ]

== 68.50.320 - Procedures for investigating missing persons—Availability of files.
When a person reported missing has not been found within thirty days of the report, or at any time the investigating agency suspects criminal activity to be the basis of the victim being missing, the sheriff, chief of police, county coroner or county medical examiner, or other law enforcement authority initiating and conducting the investigation for the missing person shall: (1) File a missing person's report with the Washington state patrol missing and unidentified persons unit; (2) initiate the collection of DNA samples from the known missing person and their family members for nuclear and mitochondrial DNA testing along with the necessary consent forms; (3) ask the missing person's family or next of kin to give written consent to contact the dentist or dentists of the missing person and request the person's dental records; and (4) enter the case into the national crime information center system through the Washington state patrol electronic database.

The missing person's dentist or dentists shall provide diagnostic quality copies of the missing person's dental records or original dental records to the sheriff, chief of police, county coroner or county medical examiner, or other law enforcement authority, when presented with the written consent from the missing person's family or next of kin or with a statement from the sheriff, chief of police, county coroner or county medical examiner, or other law enforcement authority that the missing person's family or next of kin could not be located in the exercise of due diligence or that the missing person's family or next of kin refuse to consent to the release of the missing person's dental records and there is reason to believe that the missing person's family or next of kin may have been involved in the missing person's disappearance.

As soon as possible after collecting the DNA samples, the sheriff, chief of police, or other law enforcement authority shall submit the DNA samples to the appropriate laboratory. Dental records shall be submitted as soon as possible to the Washington state patrol missing and unidentified persons unit.

The descriptive information from missing person's reports and dental data submitted to the Washington state patrol missing and unidentified persons unit shall be recorded and maintained by the Washington state patrol missing and unidentified persons unit in the applicable dedicated missing person's databases.

When a person reported missing has been found, the sheriff, chief of police, coroner or medical examiner, or other law enforcement authority shall report such information to the Washington state patrol.

The dental identification system shall maintain a file of information regarding persons reported to it as missing. The file shall contain the information referred to in this section and such other information as the Washington state patrol finds relevant to assist in the location of a missing person.

The files of the dental identification system shall, upon request, be made available to law enforcement agencies attempting to locate missing persons.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2792.SL.pdf?cite=2020%20c%2045%20§%202[2020 c 45 § 2]; http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/Senate/5191-S.SL.pdf?cite=2007%20c%2010%20§%205[2007 c 10 § 5]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/6106-S.SL.pdf?cite=2006%20c%20235%20§%204[2006 c 235 § 4]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/House/2805-S2.SL.pdf?cite=2006%20c%20102%20§%206[2006 c 102 § 6]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1611.SL.pdf?cite=2001%20c%20223%20§%201[2001 c 223 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c17.pdf?cite=1984%20c%2017%20§%2018[1984 c 17 § 18]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c16.pdf?cite=1983%201st%20ex.s.%20c%2016%20§%2016[1983 1st ex.s. c 16 § 16]; ]

== 68.50.330 - Identification of body or human remains by dental examination—Comparison of dental examination records with dental records of dental identification system.
If the county coroner or county medical examiner investigating a death is unable to establish the identity of a body or human remains by visual means, fingerprints, or other identifying data, he or she shall have a qualified dentist, as determined by the county coroner or county medical examiner, carry out a dental examination of the body or human remains. If the county coroner or county medical examiner with the aid of the dental examination and other identifying findings is still unable to establish the identity of the body or human remains, he or she shall prepare and forward such dental examination records within thirty days of the date the body or human remains were found to the dental identification system of the state patrol identification and criminal history section on forms supplied by the state patrol for such purposes.

The dental identification system shall act as a repository or computer center or both with respect to such dental examination records. It shall compare such dental examination records with dental records filed with it and shall determine which scoring probabilities are the highest for the purposes of identification. It shall then submit such information to the county coroner or county medical examiner who prepared and forwarded the dental examination records.

If the body or human remains are still unidentified thirty days after discovery, the county coroner or county medical examiner investigating the death must, as soon as practicable, submit information regarding the body or remains to the national missing and unidentified persons system created by the United States department of justice's national institute of justice. Information submitted to the national missing and unidentified persons system must include, to the extent information is available, a detailed personal description, DNA information, copies of fingerprints on standardized eight inch by eight inch fingerprint cards or the equivalent digital image, forensic dental examination records, and other identifying data, including date and place of death. If the identity of the body or human remains is later established, the county coroner or county medical examiner must notify the national missing and unidentified persons system within forty-eight hours.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/2792.SL.pdf?cite=2020%20c%2045%20§%203[2020 c 45 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/1613.SL.pdf?cite=2001%20c%20172%20§%201[2001 c 172 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1984c17.pdf?cite=1984%20c%2017%20§%2019[1984 c 17 § 19]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1983ex1c16.pdf?cite=1983%201st%20ex.s.%20c%2016%20§%2017[1983 1st ex.s. c 16 § 17]; ]

== 68.50.645 - Skeletal human remains—Duty to notify—Ground disturbing activities—Coroner determination—Definitions.
. It is the duty of every person who knows of the existence and location of skeletal human remains to notify the coroner and local law enforcement in the most expeditious manner possible, unless such person has good reason to believe that such notice has already been given. Any person knowing of the existence of skeletal human remains and not having good reason to believe that the coroner and local law enforcement has notice thereof and who fails to give notice to the coroner and local law enforcement, is guilty of a misdemeanor.

. Any person engaged in ground disturbing activity and who encounters or discovers skeletal human remains in or on the ground shall:

.. Immediately cease any activity which may cause further disturbance;

.. Make a reasonable effort to protect the area from further disturbance;

.. Report the presence and location of the remains to the coroner and local law enforcement in the most expeditious manner possible; and

.. Be held harmless from criminal and civil liability arising under the provisions of this section provided the following criteria are met:

... The finding of the remains was based on inadvertent discovery;

... The requirements of the subsection are otherwise met; and

... The person is otherwise in compliance with applicable law.

. The coroner must make a determination of whether the skeletal human remains are forensic or nonforensic within five business days of receiving notification of a finding of such human remains provided that there is sufficient evidence to make such a determination within that time period. The coroner will retain jurisdiction over forensic remains.

.. Upon determination that the remains are nonforensic, the coroner must notify the department of archaeology and historic preservation within two business days. The department will have jurisdiction over such remains until provenance of the remains is established. A determination that remains are nonforensic does not create a presumption of removal or nonremoval.

.. Upon receiving notice from a coroner of a finding of nonforensic skeletal human remains, the department must notify the appropriate local cemeteries, and all affected Indian tribes via certified mail to the head of the appropriate tribal government, and contact the appropriate tribal cultural resources staff within two business days of the finding. The determination of what are appropriate local cemeteries to be notified is at the discretion of the department. A notification to tribes of a finding of such nonforensic skeletal human remains does not create a presumption that the remains are Indian.

.. The state physical anthropologist must make an initial determination of whether nonforensic skeletal human remains are Indian or non-Indian to the extent possible based on the remains within two business days of notification of a finding of nonforensic remains. If the remains are determined to be Indian, the department must notify all affected Indian tribes via certified mail to the head of the appropriate tribal government within two business days and contact the appropriate tribal cultural resources staff.

.. The affected tribes have five business days to respond via telephone or writing to the department as to their interest in the remains.

. For the purposes of this section:

.. "Affected tribes" are:

... Those federally recognized tribes with usual and accustomed areas in the jurisdiction where the remains were found;

... Those federally recognized tribes that submit to the department maps that reflect the tribe's geographical area of cultural affiliation; and

... Other tribes with historical and cultural affiliation in the jurisdiction where the remains were found.

.. "Forensic remains" are those that come under the jurisdiction of the coroner pursuant to RCW 68.50.010.

.. "Inadvertent discovery" has the same meaning as used in RCW 27.44.040.

. Nothing in this section constitutes, advocates, or otherwise grants, confers, or implies federal or state recognition of those tribes that are not federally recognized pursuant to 25 C.F.R. part 83, procedures for establishing that an American Indian group exists as an Indian tribe.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2624-S2.SL.pdf?cite=2008%20c%20275%20§%201[2008 c 275 § 1]; ]

== 68.50.900 - Effective date—1987 c 331.
See RCW 68.05.900.

[ ]

== 68.50.901 - Application—1993 c 228.
RCW * 68.50.520 through ** 68.50.630 and 68.50.901 through 68.50.904 apply to a document of gift, revocation, or refusal to make an anatomical gift signed by the donor or a person authorized to make or object to making an anatomical gift before, on, or after July 25, 1993.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1012-S.SL.pdf?cite=1993%20c%20228%20§%2012[1993 c 228 § 12]; ]

== 68.50.902 - Application—Construction—1993 c 228.
This act shall be applied and construed to effectuate its general purpose to make uniform the law with respect to the subject of this act among states enacting it.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1012-S.SL.pdf?cite=1993%20c%20228%20§%2013[1993 c 228 § 13]; ]

== 68.50.903 - Severability—1993 c 228.
If any provision of this act or its application to any person or circumstance is held invalid, the remainder of the act or the application of the provision to other persons or circumstances is not affected.

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1012-S.SL.pdf?cite=1993%20c%20228%20§%2014[1993 c 228 § 14]; ]

== 68.50.904 - Short title—1993 c 228.
RCW * 68.50.520 through ** 68.50.630 and 68.50.901 through 68.50.903 may be cited as the "uniform anatomical gift act."

[ http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/House/1012-S.SL.pdf?cite=1993%20c%20228%20§%2016[1993 c 228 § 16]; ]

