= 68.56 - Penal and miscellaneous provisions.
:toc:

== 68.56.010 - Unlawful damage to graves, markers, shrubs, etc.—Interfering with funeral.
Every person is guilty of a gross misdemeanor who unlawfully or without right wilfully does any of the following:

. Destroys, cuts, mutilates, effaces, or otherwise injures, tears down or removes, any tomb, plot, monument, memorial or marker in a cemetery, or any gate, door, fence, wall, post or railing, or any enclosure for the protection of a cemetery or any property in a cemetery.

. Destroys, cuts, breaks, removes or injures any building, statuary, ornamentation, tree, shrub, flower or plant within the limits of a cemetery.

. Disturbs, obstructs, detains or interferes with any person carrying or accompanying human remains to a cemetery or funeral establishment, or engaged in a funeral service, or an interment.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2036[1943 c 247 § 36]; Rem. Supp. 1943 § 3778-36. Cf. 1909 c 249 § 240 and 1856-57 p 28 §§ 4, 5; ]

== 68.56.020 - Unlawful damage to graves, markers, shrubs, etc.—Civil liability for damage.
Any person violating any provision of RCW 68.56.010 is liable, in a civil action by and in the name of the cemetery authority, to pay all damages occasioned by his or her unlawful acts. The sum recovered shall be applied in payment for the repair and restoration of the property injured or destroyed.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20326[2012 c 117 § 326]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2037[1943 c 247 § 37]; Rem. Supp. 1943 § 3778-37; ]

== 68.56.030 - Unlawful damage to graves, markers, shrubs, etc.—Exceptions.
The provisions of *RCW 68.48.010 do not apply to the removal or unavoidable breakage or injury, by a cemetery authority, of any thing placed in or upon any portion of its cemetery in violation of any of the rules or regulations of the cemetery authority, nor to the removal of anything placed in the cemetery by or with the consent of the cemetery authority which has become in a wrecked, unsightly or dilapidated condition.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2037[1943 c 247 § 37]; Rem. Supp. 1943 § 3778-37; ]

== 68.56.040 - Nonconforming cemetery a nuisance—Penalty.
Every person, firm, or corporation who is the owner or operator of a cemetery established in violation of *this act is guilty of maintaining a public nuisance, which is a gross misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20149[2005 c 365 § 149]; http://lawfilesext.leg.wa.gov/biennium/2003-04/Pdf/Bills/Session%20Laws/Senate/5758.SL.pdf?cite=2003%20c%2053%20§%20313[2003 c 53 § 313]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%20145[1943 c 247 § 145]; Rem. Supp. 1943 § 3778-145; ]

== 68.56.050 - Defendant liable for costs.
Every person who violates any provision of *this act is guilty of a misdemeanor, and in addition is liable for all costs, expenses, and disbursements paid or incurred by a person prosecuting the case.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%20139[1943 c 247 § 139]; Rem. Supp. 1943 § 3778-139; ]

== 68.56.060 - Police authority—Who may exercise.
The sexton, superintendent, or other person in charge of a cemetery, and such other persons as the cemetery authority designates have the authority of a police officer for the purpose of maintaining order, enforcing the rules and regulations of the cemetery association, the laws of the state, and the ordinances of the city or county, within the cemetery over which he or she has charge, and within such radius as may be necessary to protect the cemetery property.

[ http://lawfilesext.leg.wa.gov/biennium/2011-12/Pdf/Bills/Session%20Laws/Senate/6095.SL.pdf?cite=2012%20c%20117%20§%20327[2012 c 117 § 327]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%2055[1943 c 247 § 55]; Rem. Supp. 1943 § 3778-55; ]

== 68.56.070 - Forfeiture of office for inattention to duty.
The office of any director or officer who acts or permits action contrary to *this act immediately thereupon becomes vacant.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1943c247.pdf?cite=1943%20c%20247%20§%20132[1943 c 247 § 132]; Rem. Supp. 1943 § 3778-132; ]

== 68.56.900 - Effective date—1987 c 331.
See RCW 68.05.900.

[ ]

