= 68.60 - Abandoned and historic cemeteries and historic graves.
:toc:

== 68.60.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Abandoned cemetery" means a burial ground of the human dead:

.. For which the county assessor can find no record of an owner;

.. Where the last known owner is deceased and lawful conveyance of the title has not been made; or

.. In which the cemetery company, cemetery association, corporation, or other organization that formed for the purposes of burying the human dead:

... Has disbanded, has been administratively dissolved by the secretary of state, or has otherwise ceased to exist, and for which title has not been conveyed; or

... No longer has a valid certificate of authority as determined by the funeral and cemetery board.

. "Cemetery" has the same meaning as provided in RCW 68.04.040.

. "Historic grave" means a grave or graves that were placed outside a cemetery dedicated pursuant to this chapter and to chapter 68.24 RCW, prior to June 7, 1990, except Indian graves and burial cairns protected under chapter 27.44 RCW.

. "Historical cemetery" means any burial site or grounds which contain within them human remains buried prior to November 11, 1889; except that (a) cemeteries holding a valid certificate of authority to operate granted under RCW 68.05.115 and 68.05.215, (b) cemeteries owned or operated by any recognized religious denomination that qualifies for an exemption from real estate taxation under RCW 84.36.020 on any of its churches or the ground upon which any of its churches are or will be built, and (c) cemeteries controlled or operated by a coroner, county, city, town, or cemetery district shall not be considered historical cemeteries.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1907.SL.pdf?cite=2017%20c%20208%20§%201[2017 c 208 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c92.pdf?cite=1990%20c%2092%20§%201[1990 c 92 § 1]; ]

== 68.60.020 - Dedication.
Any cemetery, abandoned cemetery, historical cemetery, or historic grave that has not been dedicated pursuant to RCW 68.24.030 and 68.24.040 shall be considered permanently dedicated and subject to RCW 68.24.070. Removal of dedication may only be made pursuant to RCW 68.24.090 and 68.24.100.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/1951-S.SL.pdf?cite=1999%20c%20367%20§%203[1999 c 367 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c92.pdf?cite=1990%20c%2092%20§%202[1990 c 92 § 2]; ]

== 68.60.030 - Preservation and maintenance corporations—Authorization of other corporations to restore, maintain, and protect abandoned cemeteries.
. [Empty]
.. The department of archaeology and historic preservation may grant, by nontransferable certificate, the authority to maintain and protect an abandoned cemetery upon application made by a state or local governmental organization, such as a city or county, or by a preservation organization that has been incorporated for the purpose of restoring, maintaining, and protecting an abandoned cemetery. Such authority is limited to the care, maintenance, restoration, protection, and historical preservation of the abandoned cemetery, and does not include authority to make burials. In order to activate a historical cemetery for burials, an applicant must apply for a certificate of authority to operate a cemetery from the funeral and cemetery board.

.. Those organizations that are granted authority to maintain and protect an abandoned cemetery are entitled to hold and possess burial records, maps, and other historical documents as may exist. Organizations that are granted authority to maintain and protect an abandoned cemetery are not liable to those claiming burial rights, ancestral ownership, or to any other person or organization alleging to have control by any form of conveyance not previously recorded at the county auditor's office within the county in which the abandoned cemetery exists. Such organizations are not liable for any reasonable alterations made during restoration work on memorials, roadways, walkways, features, plantings, or any other detail of the abandoned cemetery.

.. Should the maintenance and preservation corporation be dissolved, the department of archaeology and historic preservation shall revoke the certificate of authority.

.. Maintenance and preservation corporations that are granted authority to maintain and protect an abandoned cemetery may establish care funds.

. Except as provided in subsection (1) of this section, the department of archaeology and historic preservation may, in its sole discretion, authorize any Washington nonprofit corporation that is not expressly incorporated for the purpose of restoring, maintaining, and protecting an abandoned cemetery, to restore, maintain, and protect one or more abandoned cemeteries. The authorization may include the right of access to any burial records, maps, and other historical documents, but may not include the right to be the permanent custodian of original records, maps, or documents. This authorization must be granted by a nontransferable certificate of authority. Any nonprofit corporation authorized and acting under this subsection is immune from liability to the same extent as if it were a preservation organization holding a certificate of authority under subsection (1) of this section.

. The department of archaeology and historic preservation must establish standards and guidelines for granting certificates of authority under subsections (1) and (2) of this section to assure that any restoration, maintenance, and protection activities authorized under this subsection are conducted and supervised in an appropriate manner.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1801.SL.pdf?cite=2019%20c%20129%20§%202[2019 c 129 § 2]; http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2126-S.SL.pdf?cite=2009%20c%20102%20§%2021[2009 c 102 § 21]; http://lawfilesext.leg.wa.gov/biennium/2005-06/Pdf/Bills/Session%20Laws/Senate/5752-S.SL.pdf?cite=2005%20c%20365%20§%20150[2005 c 365 § 150]; http://lawfilesext.leg.wa.gov/biennium/1995-96/Pdf/Bills/Session%20Laws/House/1014.SL.pdf?cite=1995%20c%20399%20§%20168[1995 c 399 § 168]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/5275.SL.pdf?cite=1993%20c%2067%20§%201[1993 c 67 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c92.pdf?cite=1990%20c%2092%20§%203[1990 c 92 § 3]; ]

== 68.60.040 - Protection of cemeteries—Penalties.
. Every person who in a cemetery unlawfully or without right willfully destroys, cuts, mutilates, effaces, or otherwise injures, tears down or removes, any tomb, plot, monument, memorial, or marker in a cemetery, or any gate, door, fence, wall, post, or railing, or any enclosure for the protection of a cemetery or any property in a cemetery is guilty of a class C felony punishable under chapter 9A.20 RCW.

. Every person who in a cemetery unlawfully or without right willfully destroys, cuts, breaks, removes, or injures any building, statuary, ornamentation, tree, shrub, flower, or plant within the limits of a cemetery is guilty of a gross misdemeanor punishable under chapter 9A.20 RCW.

. Every person who in a cemetery unlawfully or without right willfully opens a grave; removes personal effects of the decedent; removes all or portions of human remains; removes or damages caskets, surrounds, outer burial containers, or any other device used in making the original burial; transports unlawfully removed human remains from the cemetery; or knowingly receives unlawfully removed human remains from the cemetery is guilty of a class C felony punishable under chapter 9A.20 RCW.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c92.pdf?cite=1990%20c%2092%20§%204[1990 c 92 § 4]; ]

== 68.60.050 - Protection of historic graves—Penalty.
. Any person who knowingly removes, mutilates, defaces, injures, or destroys any historic grave shall be guilty of a class C felony punishable under chapter 9A.20 RCW. Persons disturbing historic graves through inadvertence, including disturbance through construction, shall reinter the human remains under the supervision of the department of archaeology and historic preservation. Expenses to reinter such human remains are to be provided by the department of archaeology and historic preservation to the extent that funds for this purpose are appropriated by the legislature.

. This section does not apply to actions taken in the performance of official law enforcement duties.

. It shall be a complete defense in a prosecution under subsection (1) of this section if the defendant can prove by a preponderance of evidence that the alleged acts were accidental or inadvertent and that reasonable efforts were made to preserve the remains accidentally disturbed or discovered, and that the accidental discovery or disturbance was properly reported.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2126-S.SL.pdf?cite=2009%20c%20102%20§%2022[2009 c 102 § 22]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2010.SL.pdf?cite=1999%20c%2067%20§%201[1999 c 67 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1989c44.pdf?cite=1989%20c%2044%20§%205[1989 c 44 § 5]; ]

== 68.60.055 - Skeletal human remains—Duty to notify—Ground disturbing activities—Coroner determination—Definitions.
. Any person who discovers skeletal human remains shall notify the coroner and local law enforcement in the most expeditious manner possible. Any person knowing of the existence of skeletal human remains and not having good reason to believe that the coroner and local law enforcement has notice thereof and who fails to give notice thereof is guilty of a misdemeanor.

. Any person engaged in ground disturbing activity and who encounters or discovers skeletal human remains in or on the ground shall:

.. Immediately cease any activity which may cause further disturbance; 

.. Make a reasonable effort to protect the area from further disturbance;

.. Report the presence and location of the remains to the coroner and local law enforcement in the most expeditious manner possible; and

.. Be held harmless from criminal and civil liability arising under the provisions of this section provided the following criteria are met:

... The finding of the remains was based on inadvertent discovery;

... The requirements of the subsection are otherwise met; and

... The person is otherwise in compliance with applicable law.

. The coroner must make a determination whether the skeletal human remains are forensic or nonforensic within five business days of receiving notification of a finding of such remains provided that there is sufficient evidence to make such a determination within that time period. The coroner will retain jurisdiction over forensic remains.

.. Upon determination that the remains are nonforensic, the coroner must notify the department of archaeology and historic preservation within two business days. The department will have jurisdiction over such remains until provenance of the remains is established. A determination that remains are nonforensic does not create a presumption of removal or nonremoval.

.. Upon receiving notice from a coroner of a finding of nonforensic skeletal human remains, the department must notify the appropriate local cemeteries, and all affected Indian tribes via certified mail to the head of the appropriate tribal government, and contact the appropriate tribal cultural resources staff within two business days of the finding. The determination of what are appropriate local cemeteries to be notified is at the discretion of the department. A notification to tribes of a finding of such nonforensic skeletal human remains does not create a presumption that the remains are Indian.

.. The state physical anthropologist must make an initial determination of whether nonforensic skeletal human remains are Indian or non-Indian to the extent possible based on the remains within two business days of notification of a finding of such nonforensic remains. If the remains are determined to be Indian, the department must notify all affected Indian tribes via certified mail to the head of the appropriate tribal government within two business days and contact the appropriate tribal cultural resources staff.

.. The affected tribes have five business days to respond via telephone or writing to the department as to their interest in the remains.

. For the purposes of this section:

.. "Affected tribes" are:

... Those federally recognized tribes with usual and accustomed areas in the jurisdiction where the remains were found;

... Those federally recognized tribes that submit to the department maps that reflect the tribe's geographical area of cultural affiliation; and

... Other tribes with historical and cultural affiliation in the jurisdiction where the remains were found.

.. "Forensic remains" are those that come under the jurisdiction of the coroner pursuant to RCW 68.50.010.

.. "Inadvertent discovery" has the same meaning as used in RCW 27.44.040.

. Nothing in this section constitutes, advocates, or otherwise grants, confers, or implies federal or state recognition of those tribes that are not federally recognized pursuant to 25 C.F.R. part 83, procedures for establishing that an American Indian group exists as an Indian tribe.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/2624-S2.SL.pdf?cite=2008%20c%20275%20§%203[2008 c 275 § 3]; ]

== 68.60.060 - Violations—Civil liability.
Any person who violates any provision of this chapter is liable in a civil action by and in the name of the department of archaeology and historic preservation to pay all damages occasioned by their unlawful acts. The sum recovered shall be applied in payment for the repair and restoration of the property injured or destroyed and to the care fund if one is established.

[ http://lawfilesext.leg.wa.gov/biennium/2009-10/Pdf/Bills/Session%20Laws/House/2126-S.SL.pdf?cite=2009%20c%20102%20§%2023[2009 c 102 § 23]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c92.pdf?cite=1990%20c%2092%20§%205[1990 c 92 § 5]; ]

== 68.60.070 - Abandoned cemetery burials—Records—Endowment care funds.
. [Empty]
.. The funeral and cemetery board must consult with the department of archaeology and historic preservation to promulgate rules in order to allow for burials in abandoned cemeteries.

.. The landowner of an abandoned cemetery must allow for burials in accordance with rules promulgated by the funeral and cemetery board.

. Any records, maps, or other documents associated with an abandoned cemetery must be transferred to the state archives at the time the cemetery becomes an abandoned cemetery.

. Any endowment care funds held by the cemetery authority at the time such cemetery becomes an abandoned cemetery must be transferred to the department of archaeology and historic preservation.

[ http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Session%20Laws/House/1907.SL.pdf?cite=2017%20c%20208%20§%202[2017 c 208 § 2]; ]

== 68.60.080 - Abandoned cemetery—Lawful entry purposes.
It is lawful to enter an abandoned cemetery for purposes of:

. Burials pursuant to RCW 68.60.070 and associated rules;

. Care and maintenance activities authorized under RCW 68.60.030; and

. Visitation of graves.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/House/1801.SL.pdf?cite=2019%20c%20129%20§%201[2019 c 129 § 1]; ]

