= 68.70 - Organ transplants.
:toc:

== 68.70.010 - Definitions.
The definitions in this section apply throughout this chapter unless the context clearly requires otherwise.

. "Anatomical gift" has the same meaning as provided in RCW 68.64.010.

. "Auxiliary aids and services" include, but are not limited to:

.. Qualified interpreters or other effective methods of making aurally delivered materials available to individuals with hearing impairments;

.. Qualified readers, taped texts, or other effective methods of making visually delivered materials available to individuals with visual impairments;

.. Provision of information in a format that is accessible for individuals with cognitive, neurological, developmental, and/or intellectual disabilities;

.. Provision of supported decision-making services; and

.. Acquisition or modification of equipment or devices.

. "Covered entity" means:

.. Any licensed provider of health care services, including licensed health care practitioners, hospitals, nursing facilities, laboratories, intermediate care facilities, psychiatric residential treatment facilities, institutions for individuals with intellectual or developmental disabilities, and prison health centers; or

.. Any entity responsible for matching anatomical gift donors to potential recipients.

. "Disability" has the same meaning as provided in the Americans with disabilities act of 1990, as amended by the Americans with disabilities act amendments act of 2008, 42 U.S.C. Sec. 12102.

. "Qualified individual" means an individual who, with or without the support networks available to them, provision of auxiliary aids and services, and/or reasonable modifications to policies or practices, meets the essential eligibility requirements for the receipt of an anatomical gift.

. "Reasonable modifications to policies or practices" include, but are not limited to:

.. Communication with individuals responsible for supporting an individual with postsurgical and posttransplantation care, including medication; and

.. Consideration of support networks available to the individual, including family, friends, and home and community-based services, including home and community-based services funded through medicaid, medicare, another health plan in which the individual is enrolled, or any program or source of funding available to the individual, in determining whether the individual is able to comply with posttransplant medical requirements.

. "Supported decision making" means the use of a support person to assist an individual in making medical decisions, communicate information to the individual, or ascertain an individual's wishes. "Supported decision making" may include:

.. The inclusion of the individual's attorney-in-fact, health care proxy, or any person of the individual's choice in communications about the individual's medical care;

.. Permitting the individual to designate a person of their choice for the purposes of supporting that individual in communicating, processing information, or making medical decisions;

.. Providing auxiliary aids and services to facilitate the individual's ability to communicate and process health-related information, including use of assistive communication technology;

.. Providing information to persons designated by the individual, consistent with the provisions of the health insurance portability and accountability act of 1996, 42 U.S.C. Sec. 1301 et seq., and other applicable laws and regulations governing disclosure of health information;

.. Providing health information in a format that is readily understandable by the individual; and

.. Working with a court-appointed guardian or other individual responsible for making medical decisions on behalf of the individual, to ensure that the individual is included in decisions involving his or her own health care and that medical decisions are in accordance with the individual's own expressed interests.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5405-S.SL.pdf?cite=2019%20c%20315%20§%202[2019 c 315 § 2]; ]

== 68.70.020 - Prohibition of discrimination.
. A covered entity may not, solely on the basis of a qualified individual's mental or physical disability:

.. Deem an individual ineligible to receive an anatomical gift or organ transplant;

.. Deny medical or related organ transplantation services, including evaluation, surgery, counseling, and postoperative treatment and care;

.. Refuse to refer the individual to a transplant center or other related specialist for the purpose of evaluation or receipt of an organ transplant;

.. Refuse to place an individual on an organ transplant waiting list, or placement of the individual at a lower-priority position on the list than the position at which he or she would have been placed if not for his or her disability; or

.. Decline insurance coverage for any procedure associated with the receipt of the anatomical gift, including posttransplantation care.

. Notwithstanding subsection (1) of this section, a covered entity may take an individual's disability into account when making treatment and/or coverage recommendations or decisions, solely to the extent that the physical or mental disability has been found by a physician, following an individualized evaluation of the potential recipient, to be medically significant to the provision of the anatomical gift. The provisions of this section may not be deemed to require referrals or recommendations for, or the performance of, medically inappropriate organ transplants.

. If an individual has the necessary support system to provide reasonable assurance that she or he will comply with posttransplant medical requirements, an individual's inability to independently comply with those requirements may not be deemed to be medically significant for the purposes of subsection (2) of this section.

. A covered entity must make reasonable modifications to policies, practices, or procedures, when such modifications are necessary to make services such as transplantation-related counseling, information, coverage, or treatment available to qualified individuals with disabilities, unless the entity can demonstrate that making such modifications would fundamentally alter the nature of such services.

. A covered entity must take such steps as may be necessary to ensure that no qualified individual with a disability is denied services such as transplantation-related counseling, information, coverage, or treatment because of the absence of auxiliary aids and services, unless the entity can demonstrate that taking such steps would fundamentally alter the nature of the services being offered or would result in an undue burden.

. A covered entity must otherwise comply with the requirements of Titles II and III of the Americans with disabilities act of 1990 and the Americans with disabilities act amendments act of 2008.

. The provisions of this section apply to each part of the organ transplant process.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5405-S.SL.pdf?cite=2019%20c%20315%20§%203[2019 c 315 § 3]; ]

== 68.70.030 - Enforcement.
. Any individual who has been subjected to discrimination in violation of this chapter may initiate a civil action in a court of competent jurisdiction to enjoin further violations and recover the cost of the suit including reasonable attorneys' fees.

. The court must accord priority on its calendar and expeditiously proceed with an action brought under this chapter.

. Nothing in this section is intended to limit or replace available remedies under the Americans with disabilities act of 1990 and the Americans with disabilities act amendments act of 2008 or any other applicable law.

[ http://lawfilesext.leg.wa.gov/biennium/2019-20/Pdf/Bills/Session%20Laws/Senate/5405-S.SL.pdf?cite=2019%20c%20315%20§%204[2019 c 315 § 4]; ]

