= 79A.40 - Conveyances for persons in recreational activities.
:toc:

== 79A.40.010 - Safe and adequate facilities and equipment required of owner and operator—Operator not common carrier.
Every owner or operator of any recreational device designed and operated for the conveyance of persons which aids in promoting entertainment, pleasure, play, relaxation, or instruction, specifically including devices generally associated with winter sports activities such as aerial lifts, surface lifts, and similar devices and equipment, shall construct, furnish, maintain, and provide safe and adequate facilities and equipment with which safely and properly to receive and transport all persons offered to and received by the owner or operator of such devices, and to promote the safety of such owner's or operator's patrons, employees and the public. The owner or operator of the devices and equipment covered by this section shall be deemed not to be a common carrier.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6035.SL.pdf?cite=2014%20c%20133%20§%201[2014 c 133 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c85.pdf?cite=1965%20ex.s.%20c%2085%20§%201[1965 ex.s. c 85 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c253.pdf?cite=1961%20c%20253%20§%201[1961 c 253 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c327.pdf?cite=1959%20c%20327%20§%201[1959 c 327 § 1]; ]

== 79A.40.020 - Plans, specifications to be submitted to state parks and recreation commission—Approval—Certification by a qualified engineer—Penalty.
. It shall be unlawful after June 10, 1959, to construct or install any such recreational device as set forth in RCW 79A.40.010 without first submitting plans and specifications for such device to the state parks and recreation commission and receiving the approval of the commission for such construction or installation.

. The plans and specifications must be submitted to the commission in a manner provided by the commission accompanied by a certification by a qualified engineer. The certification must indicate that the conveyance was designed by a qualified engineer and that the conveyance, if properly installed as provided in the plan, will be safe. Upon completion of the installation, the operator or owner shall submit further certification by a qualified engineer to the commission that the conveyance has been installed in accordance with the plan. The qualified engineer submitting a certification as provided in this chapter must be formally approved to submit such a certification by the commission. The commission shall establish the necessary qualifications for any engineer seeking the ability to certify equipment pursuant to this chapter.

. Violation of this section shall be a misdemeanor.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6035.SL.pdf?cite=2014%20c%20133%20§%202[2014 c 133 § 2]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%2087[2000 c 11 § 87]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c327.pdf?cite=1959%20c%20327%20§%202[1959 c 327 § 2]; ]

== 79A.40.030 - Orders directing repairs, improvements, changes, etc.—Notice—Forbidding operation.
The state parks and recreation commission shall have the authority and the responsibility for the inspection of the devices set forth in RCW 79A.40.010 and in addition shall have the following powers and duties:

. Whenever the commission, after hearing called upon its own motion or upon complaint, finds that additional apparatus, equipment, facilities or devices for use or in connection with the transportation or conveyance of persons upon the devices set forth in RCW 79A.40.010, ought reasonably to be provided, or any repairs or improvements to, or changes in, any theretofore in use ought reasonably to be made, or any additions or changes in construction should reasonably be made thereto, in order to promote the security and safety of the public or employees, it may make and serve an order directing such repairs, improvements, changes, or additions to be made.

. If the commission finds that the equipment, or appliances in connection therewith, or the apparatus, or other structures of the recreational device set forth in RCW 79A.40.010 are defective, and that the operation thereof is dangerous to the employees of the owner or operator of such device or to the public, it shall immediately give notice to the owner or operator of such device of the repairs or reconstruction necessary to place the same in a safe condition, and may prescribe the time within which they shall be made. If, in its opinion, it is needful or proper, the commission may forbid the operation of the device until it is repaired and placed in a safe condition.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%2088[2000 c 11 § 88]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c327.pdf?cite=1959%20c%20327%20§%203[1959 c 327 § 3]; ]

== 79A.40.040 - Penalty for violation of chapter or rules, etc., of parks and recreation commission.
Any violation of this chapter or the rules, regulations and codes of the state parks and recreation commission relating to public safety in the construction, operation and maintenance of the recreational devices provided for in this chapter shall be a misdemeanor.

[ http://leg.wa.gov/CodeReviser/documents/sessionlaw/1965ex1c85.pdf?cite=1965%20ex.s.%20c%2085%20§%202[1965 ex.s. c 85 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c327.pdf?cite=1959%20c%20327%20§%204[1959 c 327 § 4]; ]

== 79A.40.050 - Inspector of recreational devices—Employees.
The state parks and recreation commission shall employ or retain a person qualified in engineering experience and training who shall be designated as the inspector of recreational devices, and may employ such additional employees as are necessary to properly administer this chapter. The inspector and such additional employees may be hired on a temporary basis or borrowed from other state departments, or the commission may contract with individuals or firms for such inspecting service on an independent basis.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6035.SL.pdf?cite=2014%20c%20133%20§%203[2014 c 133 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c327.pdf?cite=1959%20c%20327%20§%205[1959 c 327 § 5]; ]

== 79A.40.060 - Powers and duties of inspector—Condemnation of equipment—Annual inspection.
The inspector of recreational devices and his or her assistants shall inspect all equipment and appliances connected with the recreational devices set forth in RCW 79A.40.010 and make such reports of his or her inspection to the commission as may be required. He or she shall, on discovering any defective equipment, or appliances connected therewith, rendering the use of the equipment dangerous, immediately report the same to the owner or operator of the device on which it is found, and in addition report it to the commission. If in the opinion of the inspector the continued operation of the defective equipment constitutes an immediate danger to the safety of the persons operating or being conveyed by such equipment, the inspector may condemn such equipment and shall immediately notify the commission of his or her action in this respect: PROVIDED, That inspection required by this chapter must be conducted at least once each year, prior to each use season.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6035.SL.pdf?cite=2014%20c%20133%20§%204[2014 c 133 § 4]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%2089[2000 c 11 § 89]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c327.pdf?cite=1959%20c%20327%20§%206[1959 c 327 § 6]; ]

== 79A.40.070 - Program funding—Costs of inspection and plan review—Administrative fee—Fee schedule—Lien—Disposition of funds.
The program authorized by this chapter and chapter 79A.45 RCW must be funded by fees charged to the owners or operators of ski areas. The expenses incurred in connection with making inspections and reviewing plans and specifications under this chapter shall be paid by the owner or operator of such recreational devices by reimbursing the commission for the costs it incurred to hire an engineer to complete an inspection or perform plan review. The commission shall maintain accurate and complete records of the costs incurred for each inspection and plan review for construction approval and shall assess the respective owners or operators of the recreational devices an administrative fee associated with the review or service provided by the commission, which amount may vary based on the service or level of review required. The commission shall adopt a fee schedule for the services provided under this chapter, subject to RCW 43.135.055, by rule. The costs as assessed by the commission shall be a lien on the equipment of the owner or operator of the recreational devices so inspected or installed. Such moneys collected by the commission under this section shall be paid into the state parks renewal and stewardship account.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/Senate/6035.SL.pdf?cite=2014%20c%20133%20§%205[2014 c 133 § 5]; http://lawfilesext.leg.wa.gov/biennium/1997-98/Pdf/Bills/Session%20Laws/Senate/5139.SL.pdf?cite=1997%20c%20137%20§%205[1997 c 137 § 5]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c136.pdf?cite=1990%20c%20136%20§%201[1990 c 136 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1975ex1c74.pdf?cite=1975%201st%20ex.s.%20c%2074%20§%201[1975 1st ex.s. c 74 § 1]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1961c253.pdf?cite=1961%20c%20253%20§%202[1961 c 253 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c327.pdf?cite=1959%20c%20327%20§%207[1959 c 327 § 7]; ]

== 79A.40.080 - State immunity from liability—Actions deemed exercise of police power.
Inspections, rules, and orders of the state parks and recreation commission resulting from the exercise of the provisions of this chapter and chapter 79A.45 RCW shall not in any manner be deemed to impose liability upon the state for any injury or damage resulting from the operation or signing of the facilities regulated by this chapter, and all actions of the state parks and recreation commission and its personnel shall be deemed to be an exercise of the police power of the state.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%2090[2000 c 11 § 90]; http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5835-S.SL.pdf?cite=1991%20c%2075%20§%202[1991 c 75 § 2]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1990c136.pdf?cite=1990%20c%20136%20§%203[1990 c 136 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c327.pdf?cite=1959%20c%20327%20§%208[1959 c 327 § 8]; ]

== 79A.40.090 - Rules and codes.
The state parks and recreation commission is empowered to adopt reasonable rules and codes relating to public safety in the construction, operation, signing, and maintenance of the recreational devices provided for in this chapter. The rules and codes authorized hereunder shall be in accordance with established standards, if any, and shall not be discriminatory in their application.

[ http://lawfilesext.leg.wa.gov/biennium/1991-92/Pdf/Bills/Session%20Laws/Senate/5835-S.SL.pdf?cite=1991%20c%2075%20§%203[1991 c 75 § 3]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c327.pdf?cite=1959%20c%20327%20§%209[1959 c 327 § 9]; ]

== 79A.40.100 - Judicial review.
The procedure for review of the orders or actions of the state parks and recreation commission, its agents or employees, shall be conducted in accordance with chapter 34.05 RCW.

[ http://lawfilesext.leg.wa.gov/biennium/2007-08/Pdf/Bills/Session%20Laws/House/1312-S.SL.pdf?cite=2007%20c%20234%20§%2098[2007 c 234 § 98]; http://leg.wa.gov/CodeReviser/documents/sessionlaw/1959c327.pdf?cite=1959%20c%20327%20§%2010[1959 c 327 § 10]; ]

