= 79A.65 - Commission moorage facilities.
:toc:

== 79A.65.010 - Definitions.
Unless the context clearly requires otherwise, the definitions in this section apply throughout this chapter.

. "Charges" means charges of the commission for moorage and storage, and all other charges related to the vessel and owing to or that become owing to the commission, including but not limited to costs of securing, disposing, or removing vessels, damages to any commission facility, and any costs of sale and related legal expenses for implementing RCW 79A.65.020 and 79A.65.030.

. "Commission" means the Washington state parks and recreation commission.

. "Commission facility" means any moorage facility, as that term is defined in RCW 53.08.310, owned, leased, operated, managed, or otherwise controlled by the commission or by a person pursuant to a contract with the commission.

. "Owner" means a person who has a lawful right to possession of a vessel by purchase, exchange, gift, lease, inheritance, or legal action whether or not the vessel is subject to a security interest, and shall not include the holder of a bona fide security interest.

. "Person" means any natural person, firm, partnership, corporation, association, organization, or any other entity.

. [Empty]
.. "Registered owner" means any person that is either: (i) Shown as the owner in a vessel certificate of documentation issued by the secretary of the United States department of transportation under 46 U.S.C. Sec. 12103; or (ii) the registered owner or legal owner of a vessel for which a certificate of title has been issued under chapter 88.02 RCW; or (iii) the owner of a vessel registered under the vessel registration laws of another state under which laws the commission can readily identify the ownership of vessels registered with that state.

.. "Registered owner" also includes: (i) Any holder of a security interest or lien recorded with the United States department of transportation with respect to a vessel on which a certificate of documentation has been issued; (ii) any holder of a security interest identified in a certificate of title for a vessel registered under chapter 88.02 RCW; or (iii) any holder of a security interest in a vessel where the holder is identified in vessel registration information of a state with vessel registration laws that fall within (a)(iii) of this subsection and under which laws the commission can readily determine the identity of the holder.

.. "Registered owner" does not include any vessel owner or holder of a lien or security interest in a vessel if the vessel does not have visible information affixed to it (such as name and hailing port or registration numbers) that will enable the commission to obtain ownership information for the vessel without incurring unreasonable expense.

. "Registered vessel" means a vessel having a registered owner.

. "Secured vessel" means any vessel that has been secured by the commission that remains in the commission's possession and control.

. "Unauthorized vessel" means a vessel using a commission facility of any type whose owner has not paid the required moorage fees or has left the vessel beyond the posted time limits, or a vessel otherwise present without permission of the commission.

. "Vessel" means every watercraft or part thereof constructed, used, or capable of being used as a means of transportation on the water. It includes any equipment or personal property on the vessel that is used or capable of being used for the operation, navigation, or maintenance of the vessel.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2376-S.SL.pdf?cite=2002%20c%20286%20§%2020[2002 c 286 § 20]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%20115[2000 c 11 § 115]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6000-S.SL.pdf?cite=1994%20c%2051%20§%201[1994 c 51 § 1]; ]

== 79A.65.020 - Securing unauthorized vessels—Notice—Claiming vessels—Abandoned vessels—Derelict vessel removal account.
. The commission may take reasonable measures, including but not limited to the use of anchors, chains, ropes, and locks, or removal from the water, to secure unauthorized vessels located at or on a commission facility so that the unauthorized vessels are in the possession and control of the commission. At least ten days before securing any unauthorized registered vessel, the commission shall send notification by registered mail to the last registered owner or registered owners of the vessel at their last known address or addresses.

. The commission may take reasonable measures, including but not limited to the use of anchors, chains, ropes, locks, or removal from the water, to secure any vessel if the vessel, in the opinion of the commission, is a nuisance, is in danger of sinking or creating other damage to a commission facility, or is otherwise a threat to the health, safety, or welfare of the public or environment at a commission facility. The costs of any such procedure shall be paid by the vessel's owner.

. At the time of securing any vessel under subsection (1) or (2) of this section, the commission shall attach to the vessel a readily visible notice or, when practicable, shall post such notice in a conspicuous location at the commission facility in the event the vessel is removed from the premises. The notice shall be of a reasonable size and shall contain the following information:

.. The date and time the notice was attached or posted;

.. A statement that the vessel has been secured by the commission and that if the commission's charges, if any, are not paid and the vessel is not removed by . . . . . . (the thirty-fifth consecutive day following the date of attachment or posting of the notice), the vessel will be considered abandoned and will be sold at public auction to satisfy the charges;

.. The address and telephone number where additional information may be obtained concerning the securing of the vessel and conditions for its release; and

.. A description of the owner's or secured party's rights under this chapter.

. With respect to registered vessels: Within five days of the date that notice is attached or posted under subsection (3) of this section, the commission shall send such notice, by registered mail, to each registered owner.

. If a vessel is secured under subsection (1) or (2) of this section, the owner, or any person with a legal right to possess the vessel, may claim the vessel by:

.. Making arrangements satisfactory to the commission for the immediate removal of the vessel from the commission's control or for authorized storage or moorage; and

.. Making payment to the commission of all reasonable charges incurred by the commission in securing the vessel under subsections (1) and (2) of this section and of all moorage fees owed to the commission.

. A vessel is considered abandoned if, within the thirty-five day period following the date of attachment or posting of notice in subsection (3) of this section, the vessel has not been claimed under subsection (5) of this section.

. If the owner or owners of a vessel are unable to reimburse the commission for all reasonable charges under subsections (1) and (2) of this section within a reasonable time, the commission may seek reimbursement of ninety percent of all reasonable and auditable costs from the derelict vessel removal account established in RCW 79.100.100.

[ http://lawfilesext.leg.wa.gov/biennium/2013-14/Pdf/Bills/Session%20Laws/House/1245-S.SL.pdf?cite=2013%20c%20291%20§%203[2013 c 291 § 3]; http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2376-S.SL.pdf?cite=2002%20c%20286%20§%2021[2002 c 286 § 21]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6000-S.SL.pdf?cite=1994%20c%2051%20§%202[1994 c 51 § 2]; ]

== 79A.65.030 - Sale of abandoned vessels—Notice—Redemption of vessels—Use of proceeds—Disposal of vessels.
. The commission may provide for the public sale of vessels considered abandoned under RCW 79A.65.020. At such sales, the vessels shall be sold for cash to the highest and best bidder. The commission may establish either a minimum bid or require a letter of credit, or both, to discourage the future reabandonment of the vessel.

. Before a vessel is sold, the commission shall make a reasonable effort to provide notice of sale, at least twenty days before the day of the sale, to each registered owner of a registered vessel and each owner of an unregistered vessel. The notice shall contain the time and place of the sale, a reasonable description of the vessel to be sold, and the amount of charges then owing with respect to the vessel, and a summary of the rights and procedures under this chapter. A notice of sale shall be published at least once, more than ten but not more than twenty days before the sale, in a newspaper of general circulation in the county in which the commission facility is located. This notice shall include: (a) If known, the name of the vessel and the last owner and the owner's address; and (b) a reasonable description of the vessel. The commission may bid all or part of its charges at the sale and may become a purchaser at the sale.

. Before a vessel is sold, any person seeking to redeem a secured vessel may commence a lawsuit in the superior court for the county in which the vessel was secured to contest the commission's decision to secure the vessel or the amount of charges owing. This lawsuit shall be commenced within fifteen days of the date the notification was posted under RCW 79A.65.020(3), or the right to a hearing is deemed waived and the owner is liable for any charges owing the commission. In the event of litigation, the prevailing party is entitled to reasonable attorneys' fees and costs.

. The proceeds of a sale under this section shall be applied first to the payment of the amount of the reasonable charges incurred by the commission and moorage fees owed to the commission, then to the owner or to satisfy any liens of record or security interests of record on the vessel in the order of their priority. If an owner cannot in the exercise of due diligence be located by the commission within one year of the date of the sale, any excess funds from the sale, following the satisfaction of any bona fide security interest, shall revert to the derelict vessel removal account established in RCW 79.100.100. If the sale is for a sum less than the applicable charges, the commission is entitled to assert a claim for the deficiency against the vessel owner. Nothing in this section prevents any lienholder or secured party from asserting a claim for any deficiency owed the lienholder or secured party.

. If no one purchases the vessel at a sale, the commission may proceed to properly dispose of the vessel in any way the commission considers appropriate, including, but not limited to, destruction of the vessel or by negotiated sale. The commission may assert a claim against the owner for any charges incurred thereby. If the vessel, or any part of the vessel, or any rights to the vessel, are sold under this subsection, any proceeds from the sale shall be distributed in the manner provided in subsection (4) of this section.

[ http://lawfilesext.leg.wa.gov/biennium/2001-02/Pdf/Bills/Session%20Laws/House/2376-S.SL.pdf?cite=2002%20c%20286%20§%2022[2002 c 286 § 22]; http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%20116[2000 c 11 § 116]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6000-S.SL.pdf?cite=1994%20c%2051%20§%203[1994 c 51 § 3]; ]

== 79A.65.040 - Action to recover charges—Attorneys' fees—Costs.
If the full amount of all charges due the commission on an unauthorized vessel is not paid to the commission within thirty days after the date on which notice is affixed or posted under RCW 79A.65.020(3), the commission may bring an action in any court of competent jurisdiction to recover the charges, plus reasonable attorneys' fees and costs incurred by the commission.

[ http://lawfilesext.leg.wa.gov/biennium/1999-00/Pdf/Bills/Session%20Laws/House/2399-S.SL.pdf?cite=2000%20c%2011%20§%20117[2000 c 11 § 117]; http://lawfilesext.leg.wa.gov/biennium/1993-94/Pdf/Bills/Session%20Laws/Senate/6000-S.SL.pdf?cite=1994%20c%2051%20§%204[1994 c 51 § 4]; ]

== 79A.65.050 - Rights not affected.
The rights granted to the commission under this chapter are in addition to any other legal rights the commission may have to secure, hold, and sell a vessel and in no manner does this section alter those rights, or affect the priority of other liens on a vessel.

[ 1994 c 51 § 5. Formerly 88.27.050; ]

